AzerothCore: npcs_flanis_swiftwing_and_kagrosh Class Reference
npcs_flanis_swiftwing_and_kagrosh Class Reference
Public Member Functions
npcs_flanis_swiftwing_and_kagrosh ()
bool OnGossipSelect (Player *player, Creature *, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npcs_flanis_swiftwing_and_kagrosh()
npcs_flanis_swiftwing_and_kagrosh::npcs_flanis_swiftwing_and_kagrosh () inline
: CreatureScript("npcs_flanis_swiftwing_and_kagrosh") { }
Member Function Documentation
OnGossipHello()
bool npcs_flanis_swiftwing_and_kagrosh::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (player->GetQuestStatus(QUEST_THE_FATE_OF_FLANIS) == QUEST_STATUS_INCOMPLETE && !player->HasItemCount(ITEM_FLAUNISS_PACK, 1, true))
            AddGossipItemFor(player, GOSSIP_MENU_FLANIS, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
        if (player->GetQuestStatus(QUEST_THE_FATE_OF_KAGROSH) == QUEST_STATUS_INCOMPLETE && !player->HasItemCount(ITEM_KAGROSHS_PACK, 1, true))
            AddGossipItemFor(player, GOSSIP_MENU_KAGROSH, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
        SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
        return true;
    }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_MENU_FLANIS, GOSSIP_MENU_KAGROSH, GOSSIP_SENDER_MAIN, Player::HasItemCount(), ITEM_FLAUNISS_PACK, ITEM_KAGROSHS_PACK, QUEST_STATUS_INCOMPLETE, QUEST_THE_FATE_OF_FLANIS, QUEST_THE_FATE_OF_KAGROSH, and SendGossipMenuFor().
OnGossipSelect()
bool npcs_flanis_swiftwing_and_kagrosh::OnGossipSelect (Player * player, Creature * , uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
    {
        ClearGossipMenuFor(player);
        if (action == GOSSIP_ACTION_INFO_DEF + 1)
        {
            ItemPosCountVec dest;
            uint8 msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, ITEM_FLAUNISS_PACK, 1, nullptr);
            if (msg == EQUIP_ERR_OK)
            {
                player->StoreNewItem(dest, ITEM_FLAUNISS_PACK, true);
            }
        }
        if (action == GOSSIP_ACTION_INFO_DEF + 2)
        {
            ItemPosCountVec dest;
            uint8 msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, ITEM_KAGROSHS_PACK, 1, nullptr);
            if (msg == EQUIP_ERR_OK)
            {
                player->StoreNewItem(dest, ITEM_KAGROSHS_PACK, true);
            }
        }
        CloseGossipMenuFor(player);
        return true;
    }
References Player::CanStoreNewItem(), ClearGossipMenuFor(), CloseGossipMenuFor(), EQUIP_ERR_OK, GOSSIP_ACTION_INFO_DEF, ITEM_FLAUNISS_PACK, ITEM_KAGROSHS_PACK, NULL_BAG, NULL_SLOT, and Player::StoreNewItem().