AzerothCore: at_orb_of_command Class Reference
at_orb_of_command Class Reference
Public Member Functions
at_orb_of_command ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
at_orb_of_command()
at_orb_of_command::at_orb_of_command () inline
: AreaTriggerScript("at_orb_of_command") { }
Member Function Documentation
OnTrigger()
bool at_orb_of_command::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (!player->IsAlive() && player->GetQuestRewardStatus(QUEST_BLACKHANDS_COMMAND))
        {
            player->TeleportTo(MAP_BWL, orbOfCommandTP.m_positionX, orbOfCommandTP.m_positionY, orbOfCommandTP.m_positionZ, orbOfCommandTP.m_orientation);
            return true;
        }
        return false;
    }
References Player::GetQuestRewardStatus(), Unit::IsAlive(), Position::m_orientation, Position::m_positionX, Position::m_positionY, Position::m_positionZ, MAP_BWL, orbOfCommandTP, QUEST_BLACKHANDS_COMMAND, and Player::TeleportTo().