AzerothCore: BossBoundaryData Struct Reference
BossBoundaryData Struct Reference
#include "InstanceScript.h"
Public Types
typedef std::vector< BossBoundaryEntry > StorageType
typedef StorageType::const_iterator const_iterator
Public Member Functions
BossBoundaryData (std::initializer_list< BossBoundaryEntry > data)
~BossBoundaryData ()
const_iterator begin () const
const_iterator end () const
Private Attributes
StorageType _data
Detailed Description
Member Typedef Documentation
const_iterator
typedef StorageType::const_iterator BossBoundaryData::const_iterator
StorageType
typedef std::vector<BossBoundaryEntry> BossBoundaryData::StorageType
Constructor & Destructor Documentation
BossBoundaryData()
BossBoundaryData::BossBoundaryData (std::initializer_list< BossBoundaryEntry > data) inline
: _data(data) { }
~BossBoundaryData()
BossBoundaryData::~BossBoundaryData ()
{
    for (const_iterator it = begin(); it != end(); ++it)
        delete it->boundary;
}
References begin(), and end().
Member Function Documentation
begin()
const_iterator BossBoundaryData::begin () const inline
{ return _data.begin(); }
References _data.
Referenced by ~BossBoundaryData().
end()
const_iterator BossBoundaryData::end () const inline
{ return _data.end(); }
References _data.
Referenced by ~BossBoundaryData().
Member Data Documentation
_data
StorageType BossBoundaryData::_data private
Referenced by begin(), and end().