AzerothCore: HasInLineCheck Class Reference
HasInLineCheck Class Reference
Public Member Functions
HasInLineCheck (Unit *caster)
bool operator() (WorldObject *unit)
Private Attributes
Unit * _caster
Detailed Description
Constructor & Destructor Documentation
HasInLineCheck()
HasInLineCheck::HasInLineCheck (Unit * caster) inline
: _caster(caster) { }
Member Function Documentation
operator()()
bool HasInLineCheck::operator() (WorldObject * unit) inline
    {
        return !_caster->HasInLine(unit, 5.0f) || (unit->GetTypeId() == TYPEID_UNIT && unit->ToUnit()->IsUnderWater());
    }
References _caster, Object::GetTypeId(), Position::HasInLine(), Unit::IsUnderWater(), Object::ToUnit(), and TYPEID_UNIT.
Member Data Documentation
_caster
Unit* HasInLineCheck::_caster private
Referenced by operator()().