AzerothCore: MessageBuffer Class Reference
MessageBuffer Class Reference
#include "MessageBuffer.h"
Public Member Functions
MessageBuffer ()
MessageBuffer (std::size_t initialSize)
MessageBuffer (MessageBuffer const &right)
MessageBuffer (MessageBuffer &&right) noexcept
void Reset ()
void Resize (size_type bytes)
uint8 * GetBasePointer ()
uint8 * GetReadPointer ()
uint8 * GetWritePointer ()
void ReadCompleted (size_type bytes)
void WriteCompleted (size_type bytes)
size_type GetActiveSize () const
size_type GetRemainingSpace () const
size_type GetBufferSize () const
void Normalize ()
void EnsureFreeSpace ()
void Write (void const *data, std::size_t size)
std::vector< uint8 > && Move ()
MessageBuffer & operator= (MessageBuffer const &right)
MessageBuffer & operator= (MessageBuffer &&right) noexcept
Private Types
using size_type = std::vector< uint8 >::size_type
Private Attributes
size_type _wpos {0}
size_type _rpos {0}
std::vector< uint8 > _storage
Detailed Description
Member Typedef Documentation
size_type
using MessageBuffer::size_type = std::vector<uint8>::size_type private
Constructor & Destructor Documentation
MessageBuffer() [1/4]
MessageBuffer::MessageBuffer () inline
                    :  _storage()
    {
        _storage.resize(4096);
    }
References _storage.
MessageBuffer() [2/4]
MessageBuffer::MessageBuffer (std::size_t initialSize) inline explicit
                                                  : _wpos(0), _rpos(0), _storage()
    {
        _storage.resize(initialSize);
    }
References _storage.
MessageBuffer() [3/4]
MessageBuffer::MessageBuffer (MessageBuffer const & right) inline
                                              :
        _wpos(right._wpos), _rpos(right._rpos), _storage(right._storage) { }
MessageBuffer() [4/4]
MessageBuffer::MessageBuffer (MessageBuffer && right) inline noexcept
                                                  :
        _wpos(right._wpos), _rpos(right._rpos), _storage(right.Move()) { }
Member Function Documentation
EnsureFreeSpace()
void MessageBuffer::EnsureFreeSpace () inline
    {
        // resize buffer if it's already full
        if (GetRemainingSpace() == 0)
        {
            _storage.resize(_storage.size() * 3 / 2);
        }
    }
References _storage, and GetRemainingSpace().
Referenced by Socket< T >::AsyncRead(), Socket< T >::AsyncReadProxyHeader(), and Socket< T >::AsyncReadWithCallback().
GetActiveSize()
size_type MessageBuffer::GetActiveSize () const inline
{ return _wpos - _rpos; }
References _rpos, and _wpos.
Referenced by Socket< T >::AsyncProcessQueue(), Socket< T >::HandleQueue(), Normalize(), Socket< T >::ProxyReadHeaderHandler(), AuthSession::ReadHandler(), WorldSocket::ReadHandler(), WorldSocket::ReadHeaderHandler(), and WorldSocket::Update().
GetBasePointer()
uint8 * MessageBuffer::GetBasePointer () inline
{ return _storage.data(); }
References _storage.
Referenced by GetReadPointer(), GetWritePointer(), and Normalize().
GetBufferSize()
size_type MessageBuffer::GetBufferSize () const inline
{ return _storage.size(); }
References _storage.
GetReadPointer()
uint8 * MessageBuffer::GetReadPointer () inline
{ return GetBasePointer() + _rpos; }
References _rpos, and GetBasePointer().
Referenced by Socket< T >::AsyncProcessQueue(), AuthSession::HandleLogonChallenge(), AuthSession::HandleLogonProof(), Socket< T >::HandleQueue(), AuthSession::HandleReconnectChallenge(), AuthSession::HandleReconnectProof(), Normalize(), Socket< T >::ProxyReadHeaderHandler(), WorldSocket::ReadDataHandler(), AuthSession::ReadHandler(), WorldSocket::ReadHandler(), and WorldSocket::ReadHeaderHandler().
GetRemainingSpace()
size_type MessageBuffer::GetRemainingSpace () const inline
{ return _storage.size() - _wpos; }
References _storage, and _wpos.
Referenced by Socket< T >::AsyncRead(), Socket< T >::AsyncReadProxyHeader(), Socket< T >::AsyncReadWithCallback(), EnsureFreeSpace(), WorldSocket::ReadHandler(), and WorldSocket::Update().
GetWritePointer()
uint8 * MessageBuffer::GetWritePointer () inline
{ return GetBasePointer() + _wpos; }
References _wpos, and GetBasePointer().
Referenced by Socket< T >::AsyncRead(), Socket< T >::AsyncReadProxyHeader(), Socket< T >::AsyncReadWithCallback(), and Write().
Move()
std::vector< uint8 > && MessageBuffer::Move () inline
    {
        _wpos = 0;
        _rpos = 0;
        return std::move(_storage);
    }
References _rpos, _storage, and _wpos.
Normalize()
void MessageBuffer::Normalize () inline
    {
        if (_rpos)
        {
            if (_rpos != _wpos)
            {
                memmove(GetBasePointer(), GetReadPointer(), GetActiveSize());
            }
            _wpos -= _rpos;
            _rpos = 0;
        }
    }
References _rpos, _wpos, GetActiveSize(), GetBasePointer(), and GetReadPointer().
Referenced by Socket< T >::AsyncRead(), Socket< T >::AsyncReadProxyHeader(), and Socket< T >::AsyncReadWithCallback().
operator=() [1/2]
MessageBuffer & MessageBuffer::operator= (MessageBuffer && right) inline noexcept
    {
        if (this != &right)
        {
            _wpos = right._wpos;
            _rpos = right._rpos;
            _storage = right.Move();
        }
        return *this;
    }
References _rpos, _storage, and _wpos.
operator=() [2/2]
MessageBuffer & MessageBuffer::operator= (MessageBuffer const & right) inline
    {
        if (this != &right)
        {
            _wpos = right._wpos;
            _rpos = right._rpos;
            _storage = right._storage;
        }
        return *this;
    }
References _rpos, _storage, and _wpos.
ReadCompleted()
void MessageBuffer::ReadCompleted (size_type bytes) inline
{ _rpos += bytes; }
References _rpos.
Referenced by AuthSession::HandleLogonProof(), Socket< T >::HandleQueue(), Socket< T >::ProxyReadHeaderHandler(), AuthSession::ReadHandler(), and WorldSocket::ReadHandler().
Reset()
void MessageBuffer::Reset () inline
    {
        _wpos = 0;
        _rpos = 0;
    }
References _rpos, and _wpos.
Referenced by AuthSession::ReadHandler(), and WorldSocket::ReadHandler().
Resize()
void MessageBuffer::Resize (size_type bytes) inline
    {
        _storage.resize(bytes);
    }
References _storage.
Referenced by WorldSocket::ReadHeaderHandler(), Socket< T >::Socket(), WorldSocket::Update(), and WorldSocket::WorldSocket().
Write()
void MessageBuffer::Write (void const * data, std::size_t size) inline
    {
        if (size)
        {
            memcpy(GetWritePointer(), data, size);
            WriteCompleted(size);
        }
    }
References GetWritePointer(), and WriteCompleted().
Referenced by WorldSocket::ReadHandler(), AuthSession::SendPacket(), and WorldSocket::Update().
WriteCompleted()
void MessageBuffer::WriteCompleted (size_type bytes) inline
{ _wpos += bytes; }
References _wpos.
Referenced by Socket< T >::ProxyReadHeaderHandler(), Socket< T >::ReadHandlerInternal(), and Write().
Member Data Documentation
_rpos
size_type MessageBuffer::_rpos {0} private
Referenced by GetActiveSize(), GetReadPointer(), Move(), Normalize(), operator=(), ReadCompleted(), and Reset().
_storage
std::vector<uint8> MessageBuffer::_storage private
Referenced by EnsureFreeSpace(), GetBasePointer(), GetBufferSize(), GetRemainingSpace(), MessageBuffer(), Move(), operator=(), and Resize().
_wpos
size_type MessageBuffer::_wpos {0} private
Referenced by GetActiveSize(), GetRemainingSpace(), GetWritePointer(), Move(), Normalize(), operator=(), Reset(), and WriteCompleted().