AzerothCore: azerothcore-wotlk/src/server/game/Entities/Object/Position.h File Reference
Position.h File Reference
#include "Common.h"
#include "G3D/Vector3.h"
Classes
struct Position
struct Position::PositionXYStreamer
struct Position::PositionXYZStreamer
struct Position::PositionXYZOStreamer
class WorldLocation
Macros
#define MAPID_INVALID 0xFFFFFFFF
Functions
ByteBuffer & operator<< (ByteBuffer &buf, Position::PositionXYStreamer const &streamer)
ByteBuffer & operator>> (ByteBuffer &buf, Position::PositionXYStreamer const &streamer)
ByteBuffer & operator<< (ByteBuffer &buf, Position::PositionXYZStreamer const &streamer)
ByteBuffer & operator>> (ByteBuffer &buf, Position::PositionXYZStreamer const &streamer)
ByteBuffer & operator<< (ByteBuffer &buf, Position::PositionXYZOStreamer const &streamer)
ByteBuffer & operator>> (ByteBuffer &buf, Position::PositionXYZOStreamer const &streamer)
Macro Definition Documentation
MAPID_INVALID
#define MAPID_INVALID 0xFFFFFFFF
Function Documentation
operator<<() [1/3]
ByteBuffer & operator<< (ByteBuffer & buf, Position::PositionXYStreamer const & streamer)
operator<<() [2/3]
ByteBuffer & operator<< (ByteBuffer & buf, Position::PositionXYZOStreamer const & streamer)
{
    float x, y, z, o;
    streamer.m_pos->GetPosition(x, y, z, o);
    buf << x << y << z << o;
    return buf;
}
References Position::GetPosition(), and Position::PositionXYZOStreamer::m_pos.
operator<<() [3/3]
ByteBuffer & operator<< (ByteBuffer & buf, Position::PositionXYZStreamer const & streamer)
{
    float x, y, z;
    streamer.m_pos->GetPosition(x, y, z);
    buf << x << y << z;
    return buf;
}
References Position::GetPosition(), and Position::PositionXYZStreamer::m_pos.
operator>>() [1/3]
ByteBuffer & operator>> (ByteBuffer & buf, Position::PositionXYStreamer const & streamer)
operator>>() [2/3]
ByteBuffer & operator>> (ByteBuffer & buf, Position::PositionXYZOStreamer const & streamer)
{
    float x, y, z, o;
    buf >> x >> y >> z >> o;
    streamer.m_pos->Relocate(x, y, z, o);
    return buf;
}
References Position::PositionXYZOStreamer::m_pos, and Position::Relocate().
operator>>() [3/3]
ByteBuffer & operator>> (ByteBuffer & buf, Position::PositionXYZStreamer const & streamer)
{
    float x, y, z;
    buf >> x >> y >> z;
    streamer.m_pos->Relocate(x, y, z);
    return buf;
}
References Position::PositionXYZStreamer::m_pos, and Position::Relocate().