AzerothCore: Acore::AnyPlayerExactPositionInGameObjectRangeCheck Class Reference
Acore::AnyPlayerExactPositionInGameObjectRangeCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
AnyPlayerExactPositionInGameObjectRangeCheck (GameObject const *go, float range)
bool operator() (Player *u)
Private Attributes
GameObject const * _go
float _range
Detailed Description
Constructor & Destructor Documentation
AnyPlayerExactPositionInGameObjectRangeCheck()
Acore::AnyPlayerExactPositionInGameObjectRangeCheck::AnyPlayerExactPositionInGameObjectRangeCheck (GameObject const * go, float range) inline
: _go(go), _range(range) {}
Member Function Documentation
operator()()
bool Acore::AnyPlayerExactPositionInGameObjectRangeCheck::operator() (Player * u) inline
        {
            if (!_go->IsInRange(u->GetPositionX(), u->GetPositionY(), u->GetPositionZ(), _range))
                return false;
            return true;
        }
References _go, _range, Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), and GameObject::IsInRange().
Member Data Documentation
_go
GameObject const* Acore::AnyPlayerExactPositionInGameObjectRangeCheck::_go private
Referenced by operator()().
_range
float Acore::AnyPlayerExactPositionInGameObjectRangeCheck::_range private
Referenced by operator()().