AzerothCore: azerothcore-wotlk/src/server/game/Grids/Notifiers/GridNotifiers.cpp File Reference
GridNotifiers.cpp File Reference
#include "GridNotifiers.h"
#include "Map.h"
#include "ObjectAccessor.h"
#include "Transport.h"
#include "UpdateData.h"
#include "WorldPacket.h"
Functions
void CreatureUnitRelocationWorker (Creature *c, Unit *u)
Function Documentation
CreatureUnitRelocationWorker()
void CreatureUnitRelocationWorker (Creature * c, Unit * u) inline
{
    if (!u->IsAlive() || !c->IsAlive() || c == u || u->IsInFlight())
    {
        return;
    }
    if (!c->HasUnitState(UNIT_STATE_SIGHTLESS))
    {
        if (c->IsAIEnabled && c->CanSeeOrDetect(u, false, true))
        {
            c->AI()->MoveInLineOfSight_Safe(u);
        }
        else if (u->IsPlayer() && u->HasStealthAura() && c->IsAIEnabled && c->CanSeeOrDetect(u, false, true, true))
        {
            c->AI()->TriggerAlert(u);
        }
    }
}
References Creature::AI(), WorldObject::CanSeeOrDetect(), Unit::HasStealthAura(), Unit::HasUnitState(), Unit::IsAIEnabled, Unit::IsAlive(), Unit::IsInFlight(), Object::IsPlayer(), CreatureAI::MoveInLineOfSight_Safe(), CreatureAI::TriggerAlert(), and UNIT_STATE_SIGHTLESS.
Referenced by Acore::AIRelocationNotifier::Visit(), and Acore::CreatureRelocationNotifier::Visit().