AzerothCore: boss_freya::boss_freyaAI Struct Reference
boss_freya::boss_freyaAI Struct Reference
Public Member Functions
boss_freyaAI (Creature *pCreature)
void Reset () override
void KilledUnit (Unit *victim) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void JustSummoned (Creature *cr) override
void SpawnWave ()
void DoAction (int32 param) override
uint32 GetData (uint32 param) const override
void JustReachedHome () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
bool CheckEvadeIfOutOfCombatArea () const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
uint8 _waveNumber
uint8 _trioKilled
uint8 _spawnedAmount
uint8 _lumberjacked
bool _respawningTrio
bool _backToNature
uint8 _deforestation
ObjectGuid _elderGUID [3]
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_freyaAI()
boss_freya::boss_freyaAI::boss_freyaAI (Creature * pCreature) inline
                                          : ScriptedAI(pCreature), summons(me)
        {
            m_pInstance = pCreature->GetInstanceScript();
            if (!me->IsAlive())
                if (m_pInstance)
                    m_pInstance->SetData(TYPE_FREYA, DONE);
        }
References DONE, WorldObject::GetInstanceScript(), Unit::IsAlive(), m_pInstance, ScriptedAI::me, ZoneScript::SetData(), and TYPE_FREYA.
Member Function Documentation
CheckEvadeIfOutOfCombatArea()
bool boss_freya::boss_freyaAI::CheckEvadeIfOutOfCombatArea () const inline override virtual
Reimplemented from ScriptedAI.
        {
            return me->GetPositionX() < 2135.0f;
        }
References Position::GetPositionX(), and ScriptedAI::me.
DamageTaken()
void boss_freya::boss_freyaAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (damage >= me->GetHealth())
            {
                damage = 0;
                if (m_pInstance->GetData(TYPE_FREYA) != DONE)
                {
                    Talk(SAY_DEATH);
                    me->SetReactState(REACT_PASSIVE);
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->SetFaction(FACTION_FRIENDLY);
                    me->RemoveAllAuras();
                    me->AttackStop();
                    events.Reset();
                    summons.DespawnAll();
                    events.Reset();
                    uint8 _elderCount = 0;
                    for (uint8 i = 0; i < 3; ++i)
                    {
                        if (!_elderGUID[i])
                            continue;
                        if (Creature* e = ObjectAccessor::GetCreature(*me, _elderGUID[i]))
                            e->DespawnOrUnsummon();
                        ++_elderCount;
                    }
                    uint32 chestId = RAID_MODE(GO_FREYA_CHEST, GO_FREYA_CHEST_HERO);
                    chestId -= 2 * _elderCount; // offset
                    if (GameObject* go = me->SummonGameObject(chestId, 2345.61f, -71.20f, 425.104f, 3.0f, 0, 0, 0, 0, 0))
                    {
                        go->ReplaceAllGameObjectFlags((GameObjectFlags)0);
                        go->SetLootRecipient(me->GetMap());
                    }
                    // Defeat credit
                    if (m_pInstance)
                    {
                        me->CastSpell(me, 65074, true); // credit
                        m_pInstance->SetData(TYPE_FREYA, DONE);
                    }
                    scheduler.Schedule(14s, [this](TaskContext /*context*/)
                    {
                        DoCastSelf(SPELL_TELEPORT);
                    });
                }
            }
        }
References _elderGUID, Unit::AttackStop(), Unit::CastSpell(), SummonList::DespawnAll(), UnitAI::DoCastSelf(), DONE, FACTION_FRIENDLY, ObjectAccessor::GetCreature(), ZoneScript::GetData(), Unit::GetHealth(), WorldObject::GetMap(), GO_FREYA_CHEST, GO_FREYA_CHEST_HERO, m_pInstance, ScriptedAI::me, ScriptedAI::RAID_MODE(), REACT_PASSIVE, Unit::RemoveAllAuras(), SAY_DEATH, TaskScheduler::Schedule(), CreatureAI::scheduler, ZoneScript::SetData(), Unit::SetFaction(), Creature::SetReactState(), Unit::SetUnitFlag(), SPELL_TELEPORT, WorldObject::SummonGameObject(), summons, TYPE_FREYA, and UNIT_FLAG_NON_ATTACKABLE.
DoAction()
void boss_freya::boss_freyaAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_LUMBERJACKED)
            {
                if (!m_pInstance)
                    return;
                ++_lumberjacked;
                if (_lumberjacked == 1)
                    m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, CRITERIA_LUMBERJACKED);
                else if (_lumberjacked == 3)
                    m_pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, 65296 /*SPELL_LUMBERJACKED*/, 0, me);
                return;
            }
            if (param == ACTION_RESPAWN_TRIO)
            {
                if (!_respawningTrio)
                {
                    _respawningTrio = true;
                    events.ScheduleEvent(EVENT_FREYA_RESPAWN_TRIO, 10s);
                }
                ++_trioKilled;
                return;
            }
            // Deforestation Achievement Counter
            if (param == ACTION_REMOVE_10_STACK)
            {
                ++_deforestation;
                if (_deforestation >= 6 && m_pInstance)
                    m_pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, SPELL_DEFORESTATION_CREDIT, 0, me);
                // do not return
            }
            if (Aura* aur = me->GetAura(SPELL_ATTUNED_TO_NATURE))
            {
                // Back to Nature achievement
                if (aur->GetStackAmount() - param < 25)
                    _backToNature = false;
                if (aur->GetStackAmount() > param)
                    aur->SetStackAmount(aur->GetStackAmount() - param);
                else // Aura out of stack
                {
                    events.ScheduleEvent(EVENT_FREYA_NATURE_BOMB, 5s);
                    events.SetPhase(EVENT_PHASE_FINAL);
                    aur->Remove();
                    return;
                }
            }
        }
References _backToNature, _deforestation, _lumberjacked, _respawningTrio, _trioKilled, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_TIMED_TYPE_EVENT, ACTION_LUMBERJACKED, ACTION_REMOVE_10_STACK, ACTION_RESPAWN_TRIO, CRITERIA_LUMBERJACKED, InstanceScript::DoStartTimedAchievement(), InstanceScript::DoUpdateAchievementCriteria(), EVENT_FREYA_NATURE_BOMB, EVENT_FREYA_RESPAWN_TRIO, EVENT_PHASE_FINAL, Unit::GetAura(), m_pInstance, ScriptedAI::me, SPELL_ATTUNED_TO_NATURE, and SPELL_DEFORESTATION_CREDIT.
GetData()
uint32 boss_freya::boss_freyaAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_GET_ELDER_COUNT)
            {
                uint8 _count = 0;
                for (uint8 i = 0; i < 3; ++i)
                    if (_elderGUID[i])
                        ++_count;
                return _count;
            }
            if (param == DATA_BACK_TO_NATURE)
                return _backToNature;
            return 0;
        }
References _backToNature, _elderGUID, DATA_BACK_TO_NATURE, and DATA_GET_ELDER_COUNT.
JustEngagedWith()
void boss_freya::boss_freyaAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            me->setActive(true);
            me->SetInCombatWithZone();
            me->CastSpell(me, SPELL_TOUCH_OF_EONAR, true);
            if (Aura* aur = me->AddAura(SPELL_ATTUNED_TO_NATURE, me))
                aur->SetStackAmount(150);
            events.ScheduleEvent(EVENT_FREYA_ADDS_SPAM, 10s, 0, EVENT_PHASE_ADDS);
            events.ScheduleEvent(EVENT_FREYA_LIFEBINDER, 30s);
            events.ScheduleEvent(EVENT_FREYA_SUNBEAM, 17s);
            events.ScheduleEvent(EVENT_FREYA_BERSERK, 10min);
            events.SetPhase(EVENT_PHASE_ADDS);
            if (!m_pInstance)
                return;
            if (m_pInstance->GetData(TYPE_FREYA) != DONE)
                m_pInstance->SetData(TYPE_FREYA, IN_PROGRESS);
            // HARD MODE CHECKS
            Creature* elder = ObjectAccessor::GetCreature(*me, m_pInstance->GetGuidData(NPC_ELDER_STONEBARK));
            if (elder && elder->IsAlive())
            {
                elder->CastSpell(elder, SPELL_DRAINED_OF_POWER, true);
                elder->CastSpell(elder, SPELL_STONEBARK_ESSENCE, true);
                elder->SetInCombatWithZone();
                events.ScheduleEvent(EVENT_FREYA_GROUND_TREMOR, 35s);
                _elderGUID[0] = elder->GetGUID();
            }
            elder = ObjectAccessor::GetCreature(*me, m_pInstance->GetGuidData(NPC_ELDER_IRONBRANCH));
            if (elder && elder->IsAlive())
            {
                elder->CastSpell(elder, SPELL_DRAINED_OF_POWER, true);
                elder->CastSpell(elder, SPELL_IRONBRANCH_ESSENCE, true);
                elder->SetInCombatWithZone();
                events.ScheduleEvent(EVENT_FREYA_IRON_ROOT, 20s);
                _elderGUID[1] = elder->GetGUID();
            }
            elder = ObjectAccessor::GetCreature(*me, m_pInstance->GetGuidData(NPC_ELDER_BRIGHTLEAF));
            if (elder && elder->IsAlive())
            {
                elder->CastSpell(elder, SPELL_DRAINED_OF_POWER, true);
                elder->CastSpell(elder, SPELL_BRIGHTLEAF_ESSENCE, true);
                elder->SetInCombatWithZone();
                events.ScheduleEvent(EVENT_FREYA_UNSTABLE_SUN_BEAM, 1min);
                _elderGUID[2] = elder->GetGUID();
            }
            if (_elderGUID[0] || _elderGUID[1] || _elderGUID[2])
            {
                Talk(SAY_AGGRO_WITH_ELDER);
            }
            else
            {
                Talk(SAY_AGGRO);
            }
        }
References _elderGUID, Unit::AddAura(), Unit::CastSpell(), DONE, EVENT_FREYA_ADDS_SPAM, EVENT_FREYA_BERSERK, EVENT_FREYA_GROUND_TREMOR, EVENT_FREYA_IRON_ROOT, EVENT_FREYA_LIFEBINDER, EVENT_FREYA_SUNBEAM, EVENT_FREYA_UNSTABLE_SUN_BEAM, EVENT_PHASE_ADDS, ObjectAccessor::GetCreature(), ZoneScript::GetData(), Object::GetGUID(), InstanceScript::GetGuidData(), IN_PROGRESS, Unit::IsAlive(), m_pInstance, ScriptedAI::me, NPC_ELDER_BRIGHTLEAF, NPC_ELDER_IRONBRANCH, NPC_ELDER_STONEBARK, SAY_AGGRO, SAY_AGGRO_WITH_ELDER, WorldObject::setActive(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), SPELL_ATTUNED_TO_NATURE, SPELL_BRIGHTLEAF_ESSENCE, SPELL_DRAINED_OF_POWER, SPELL_IRONBRANCH_ESSENCE, SPELL_STONEBARK_ESSENCE, SPELL_TOUCH_OF_EONAR, and TYPE_FREYA.
JustReachedHome()
void boss_freya::boss_freyaAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
{ me->setActive(false); }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_freya::boss_freyaAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (cr->GetEntry() == NPC_FREYA_UNSTABLE_SUN_BEAM)
            {
                cr->CastSpell(cr, SPELL_UNSTABLE_SUN_VISUAL, true);
                cr->CastSpell(cr, SPELL_UNSTABLE_SUN_FREYA_DAMAGE, true);
            }
            summons.Summon(cr);
        }
References Unit::CastSpell(), Object::GetEntry(), NPC_FREYA_UNSTABLE_SUN_BEAM, SPELL_UNSTABLE_SUN_FREYA_DAMAGE, SPELL_UNSTABLE_SUN_VISUAL, SummonList::Summon(), and summons.
KilledUnit()
void boss_freya::boss_freyaAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!victim->IsPlayer() || urand(0, 2))
                return;
            Talk(SAY_SLAY);
        }
References Object::IsPlayer(), SAY_SLAY, and urand().
Reset()
void boss_freya::boss_freyaAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            if (m_pInstance && m_pInstance->GetData(TYPE_FREYA) != DONE)
                m_pInstance->SetData(TYPE_FREYA, NOT_STARTED);
            events.Reset();
            summons.DespawnAll();
            for (uint8 i = 0; i < 3; ++i)
            {
                if (!_elderGUID[i])
                    continue;
                if (Creature* elder = ObjectAccessor::GetCreature(*me, _elderGUID[i]))
                    elder->AI()->EnterEvadeMode();
                _elderGUID[i].Clear();
            }
            _lumberjacked = 0;
            _spawnedAmount = 0;
            _trioKilled = 0;
            _waveNumber = urand(1, 3);
            _respawningTrio = false;
            _backToNature = true;
            _deforestation = 0;
        }
References _backToNature, _deforestation, _elderGUID, _lumberjacked, _respawningTrio, _spawnedAmount, _trioKilled, _waveNumber, ObjectGuid::Clear(), SummonList::DespawnAll(), DONE, ObjectAccessor::GetCreature(), ZoneScript::GetData(), m_pInstance, ScriptedAI::me, NOT_STARTED, ZoneScript::SetData(), summons, TYPE_FREYA, and urand().
SpawnWave()
void boss_freya::boss_freyaAI::SpawnWave () inline
        {
            _waveNumber = _waveNumber == 1 ? 3 : _waveNumber - 1;
            Talk(EMOTE_ALLIES_OF_NATURE);
            // Wave of three
            if (_waveNumber == 1)
            {
                Talk(SAY_SUMMON_TRIO);
                me->SummonCreature(NPC_ANCIENT_WATER_SPIRIT, me->GetPositionX() + urand(5, 15), me->GetPositionY() + urand(5, 15), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                me->SummonCreature(NPC_STORM_LASHER, me->GetPositionX() + urand(5, 15), me->GetPositionY() + urand(5, 15), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                me->SummonCreature(NPC_SNAPLASHER, me->GetPositionX() + urand(5, 15), me->GetPositionY() + urand(5, 15), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
            }
            // Ancient Conservator
            else if (_waveNumber == 2)
            {
                Talk(SAY_SUMMON_CONSERVATOR);
                me->SummonCreature(NPC_ANCIENT_CONSERVATOR, me->GetPositionX() + urand(5, 15), me->GetPositionY() + urand(5, 15), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), 0, TEMPSUMMON_CORPSE_DESPAWN);
            }
            // Detonating Lashers
            else if (_waveNumber == 3)
            {
                Talk(SAY_SUMMON_LASHERS);
                for (uint8 i = 0; i < 10; ++i)
                    me->SummonCreature(NPC_DETONATING_LASHER, me->GetPositionX() + urand(5, 20), me->GetPositionY() + urand(5, 20), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), 0, TEMPSUMMON_CORPSE_DESPAWN);
            }
        }
References _waveNumber, EMOTE_ALLIES_OF_NATURE, WorldObject::GetMapHeight(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, NPC_ANCIENT_CONSERVATOR, NPC_ANCIENT_WATER_SPIRIT, NPC_DETONATING_LASHER, NPC_SNAPLASHER, NPC_STORM_LASHER, SAY_SUMMON_CONSERVATOR, SAY_SUMMON_LASHERS, SAY_SUMMON_TRIO, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_DESPAWN, and urand().
Referenced by UpdateAI().
SpellHit()
void boss_freya::boss_freyaAI::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_TELEPORT)
            {
                me->DespawnOrUnsummon();
                m_pInstance->SetData(EVENT_KEEPER_TELEPORTED, DONE);
            }
        }
References Creature::DespawnOrUnsummon(), DONE, EVENT_KEEPER_TELEPORTED, SpellInfo::Id, m_pInstance, ScriptedAI::me, ZoneScript::SetData(), and SPELL_TELEPORT.
SpellHitTarget()
void boss_freya::boss_freyaAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spell->Id == SPELL_NATURE_BOMB_FLIGHT)
                me->SummonCreature(NPC_NATURE_BOMB, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ());
        }
References Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), SpellInfo::Id, ScriptedAI::me, NPC_NATURE_BOMB, SPELL_NATURE_BOMB_FLIGHT, and WorldObject::SummonCreature().
UpdateAI()
void boss_freya::boss_freyaAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            scheduler.Update(diff);
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_FREYA_ADDS_SPAM:
                    if (_spawnedAmount < 6)
                        SpawnWave();
                    else if (me->GetAura(SPELL_ATTUNED_TO_NATURE))
                    {
                        me->RemoveAura(SPELL_ATTUNED_TO_NATURE);
                        events.ScheduleEvent(EVENT_FREYA_NATURE_BOMB, 5s);
                        events.SetPhase(EVENT_PHASE_FINAL);
                        return;
                    }
                    _spawnedAmount++;
                    events.Repeat(1min);
                    break;
                case EVENT_FREYA_LIFEBINDER:
                    {
                        Talk(EMOTE_LIFEBINDERS_GIFT);
                        events.Repeat(45s);
                        float x, y, z;
                        for (uint8 i = 0; i < 10; ++i)
{
                            x = me->GetPositionX() + urand(7, 25);
                            y = me->GetPositionY() + urand(7, 25);
                            z = me->GetMapHeight(x, y, me->GetPositionZ());
                            if (me->IsWithinLOS(x, y, z))
{
                                me->CastSpell(x, y, z, SPELL_SUMMON_LIFEBINDER, true);
                                return;
                            }
                        }
                        me->CastSpell(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), SPELL_SUMMON_LIFEBINDER, true);
                        break;
                    }
                case EVENT_FREYA_SUNBEAM:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random))
                        me->CastSpell(target, SPELL_SUNBEAM, false);
                    events.Repeat(15s, 20s);
                    break;
                case EVENT_FREYA_RESPAWN_TRIO:
                    _deforestation = 0;
                    _respawningTrio = false;
                    if (_trioKilled < 3)
                        summons.DoAction(ACTION_RESPAWN_TRIO);
                    _trioKilled = 0;
                    break;
                case EVENT_FREYA_NATURE_BOMB:
                    {
                        uint8 _minCount = me->GetMap()->Is25ManRaid() ? urand(7, 10) : urand(3, 4);
                        Map::PlayerList const& pList = me->GetMap()->GetPlayers();
                        for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
{
                            if (me->GetDistance(itr->GetSource()) > 70 || !itr->GetSource()->IsAlive())
                                continue;
                            me->CastSpell(itr->GetSource(), SPELL_NATURE_BOMB_FLIGHT, true);
                            if (!(--_minCount))
                                break;
                        }
                        events.Repeat(18s);
                        break;
                    }
                case EVENT_FREYA_BERSERK:
                    Talk(SAY_BERSERK);
                    me->CastSpell(me, SPELL_BERSERK, true);
                    break;
                case EVENT_FREYA_GROUND_TREMOR:
                    Talk(EMOTE_GROUND_TREMOR);
                    me->CastSpell(me, SPELL_GROUND_TREMOR_FREYA, false);
                    events.Repeat(25s, 35s);
                    break;
                case EVENT_FREYA_IRON_ROOT:
                    Talk(EMOTE_IRON_ROOTS);
                    me->CastCustomSpell(SPELL_IRON_ROOTS_FREYA, SPELLVALUE_MAX_TARGETS, 1, me, false);
                    events.Repeat(45s, 55s);
                    break;
                case EVENT_FREYA_UNSTABLE_SUN_BEAM:
                    me->SummonCreature(NPC_FREYA_UNSTABLE_SUN_BEAM, me->GetPositionX() + urand(7, 25), me->GetPositionY() + urand(7, 25), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), 0, TEMPSUMMON_TIMED_DESPAWN, 10000);
                    if (Is25ManRaid())
                    {
                        me->SummonCreature(NPC_FREYA_UNSTABLE_SUN_BEAM, me->GetPositionX() + urand(7, 25), me->GetPositionY() + urand(7, 25), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), 0, TEMPSUMMON_TIMED_DESPAWN, 10000);
                        me->SummonCreature(NPC_FREYA_UNSTABLE_SUN_BEAM, me->GetPositionX() + urand(7, 25), me->GetPositionY() + urand(7, 25), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), 0, TEMPSUMMON_TIMED_DESPAWN, 10000);
                    }
                    events.Repeat(38s, 48s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References _deforestation, _respawningTrio, _spawnedAmount, _trioKilled, ACTION_RESPAWN_TRIO, MapRefMgr::begin(), Unit::CastCustomSpell(), Unit::CastSpell(), SummonList::DoAction(), UnitAI::DoMeleeAttackIfReady(), EMOTE_GROUND_TREMOR, EMOTE_IRON_ROOTS, EMOTE_LIFEBINDERS_GIFT, MapRefMgr::end(), EVENT_FREYA_ADDS_SPAM, EVENT_FREYA_BERSERK, EVENT_FREYA_GROUND_TREMOR, EVENT_FREYA_IRON_ROOT, EVENT_FREYA_LIFEBINDER, EVENT_FREYA_NATURE_BOMB, EVENT_FREYA_RESPAWN_TRIO, EVENT_FREYA_SUNBEAM, EVENT_FREYA_UNSTABLE_SUN_BEAM, EVENT_PHASE_FINAL, Unit::GetAura(), WorldObject::GetDistance(), WorldObject::GetMap(), WorldObject::GetMapHeight(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::HasUnitState(), ScriptedAI::Is25ManRaid(), Map::Is25ManRaid(), WorldObject::IsWithinLOS(), ScriptedAI::me, NPC_FREYA_UNSTABLE_SUN_BEAM, Unit::RemoveAura(), SAY_BERSERK, CreatureAI::scheduler, UnitAI::SelectTarget(), SpawnWave(), SPELL_ATTUNED_TO_NATURE, SPELL_BERSERK, SPELL_GROUND_TREMOR_FREYA, SPELL_IRON_ROOTS_FREYA, SPELL_NATURE_BOMB_FLIGHT, SPELL_SUMMON_LIFEBINDER, SPELL_SUNBEAM, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), summons, TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, TaskScheduler::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_backToNature
bool boss_freya::boss_freyaAI::_backToNature
Referenced by DoAction(), GetData(), and Reset().
_deforestation
uint8 boss_freya::boss_freyaAI::_deforestation
Referenced by DoAction(), Reset(), and UpdateAI().
_elderGUID
ObjectGuid boss_freya::boss_freyaAI::_elderGUID[3]
Referenced by DamageTaken(), GetData(), JustEngagedWith(), and Reset().
_lumberjacked
uint8 boss_freya::boss_freyaAI::_lumberjacked
Referenced by DoAction(), and Reset().
_respawningTrio
bool boss_freya::boss_freyaAI::_respawningTrio
Referenced by DoAction(), Reset(), and UpdateAI().
_spawnedAmount
uint8 boss_freya::boss_freyaAI::_spawnedAmount
Referenced by Reset(), and UpdateAI().
_trioKilled
uint8 boss_freya::boss_freyaAI::_trioKilled
Referenced by DoAction(), Reset(), and UpdateAI().
_waveNumber
uint8 boss_freya::boss_freyaAI::_waveNumber
Referenced by Reset(), and SpawnWave().
events
EventMap boss_freya::boss_freyaAI::events
m_pInstance
InstanceScript* boss_freya::boss_freyaAI::m_pInstance
Referenced by boss_freyaAI(), DamageTaken(), DoAction(), JustEngagedWith(), Reset(), and SpellHit().
summons
SummonList boss_freya::boss_freyaAI::summons
Referenced by DamageTaken(), JustSummoned(), Reset(), and UpdateAI().