AzerothCore: NotInStomachSelector Class Reference
NotInStomachSelector Class Reference
Public Member Functions
NotInStomachSelector ()
bool operator() (Unit *unit) const
Detailed Description
Constructor & Destructor Documentation
NotInStomachSelector()
NotInStomachSelector::NotInStomachSelector () inline
{ }
Member Function Documentation
operator()()
bool NotInStomachSelector::operator() (Unit * unit) const inline
    {
        return unit->IsPlayer() && !unit->HasAura(SPELL_DIGESTIVE_ACID) && (unit->GetPositionZ() > 0.0f);
    }
References Position::GetPositionZ(), Unit::HasAura(), Object::IsPlayer(), and SPELL_DIGESTIVE_ACID.