AzerothCore: achievement_i_have_the_coolest_friends Class Reference
achievement_i_have_the_coolest_friends Class Reference
Public Member Functions
achievement_i_have_the_coolest_friends ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
virtual bool OnCheck (Player *, Unit *, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_i_have_the_coolest_friends()
achievement_i_have_the_coolest_friends::achievement_i_have_the_coolest_friends () inline
: AchievementCriteriaScript("achievement_i_have_the_coolest_friends") {}
Member Function Documentation
OnCheck()
bool achievement_i_have_the_coolest_friends::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
    {
        return target && target->GetEntry() == NPC_HODIR && target->IsCreature() && target->ToCreature()->AI()->GetData(4);
    }
References Creature::AI(), UnitAI::GetData(), Object::GetEntry(), Object::IsCreature(), NPC_HODIR, and Object::ToCreature().