AzerothCore: boss_headless_horseman Struct Reference
boss_headless_horseman Struct Reference
Public Member Functions
boss_headless_horseman (Creature *creature)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void DoAction (int32 param) override
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void MovementInform (uint32 type, uint32 point) override
Player * GetRhymePlayer ()
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void MoveInLineOfSight (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *cr) override
void Reset () override
void JustReachedHome () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
SummonList summons
ObjectGuid playerGUID
uint8 talkCount
bool inFight
uint8 phase
uint32 health
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_headless_horseman()
boss_headless_horseman::boss_headless_horseman (Creature * creature) inline
: ScriptedAI(creature), summons(me) { }
Member Function Documentation
DamageTaken()
void boss_headless_horseman::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
    {
        // We die... :(
        if (damage >= me->GetHealth())
        {
            damage = 0;
            me->RemoveAura(SPELL_HEAD_VISUAL);
            me->CastSpell(me, SPELL_HORSEMAN_IMMUNITY, true);
            me->CastSpell(me, SPELL_HORSEMAN_BODY_REGEN, true);
            me->CastSpell(me, SPELL_HORSEMAN_BODY_REGEN_CONFUSE, true);
            events.CancelEvent(EVENT_HORSEMAN_CLEAVE);
            // Summon Head
            Position pos = me->GetNearPosition(15.0f, rand_norm() * 2 * M_PI);
            if (Creature* cr = me->SummonCreature(NPC_HORSEMAN_HEAD, pos))
            {
                if (health)
                    cr->SetHealth(health);
                me->CastSpell(cr, SPELL_THROW_HEAD, true);
                cr->CastSpell(cr, SPELL_HORSEMAN_BODY_PHASE + phase, true);
                if (phase < 2)
                    phase++;
                events.ScheduleEvent(EVENT_HORSEMAN_WHIRLWIND, 6s);
                events.ScheduleEvent(EVENT_HORSEMAN_CHECK_HEALTH, 1s);
            }
        }
    }
References Unit::CastSpell(), EVENT_HORSEMAN_CHECK_HEALTH, EVENT_HORSEMAN_CLEAVE, EVENT_HORSEMAN_WHIRLWIND, Unit::GetHealth(), WorldObject::GetNearPosition(), health, ScriptedAI::me, NPC_HORSEMAN_HEAD, rand_norm(), Unit::RemoveAura(), SPELL_HEAD_VISUAL, SPELL_HORSEMAN_BODY_PHASE, SPELL_HORSEMAN_BODY_REGEN, SPELL_HORSEMAN_BODY_REGEN_CONFUSE, SPELL_HORSEMAN_IMMUNITY, SPELL_THROW_HEAD, and WorldObject::SummonCreature().
DoAction()
void boss_headless_horseman::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
    {
        health = param;
    }
References health.
GetRhymePlayer()
Player * boss_headless_horseman::GetRhymePlayer () inline
{ return playerGUID ? ObjectAccessor::GetPlayer(*me, playerGUID) : nullptr; }
References ObjectAccessor::GetPlayer(), ScriptedAI::me, and playerGUID.
Referenced by UpdateAI().
JustDied()
void boss_headless_horseman::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        summons.DespawnAll();
        Talk(TALK_DEATH);
        std::list<Creature*> unitList;
        me->GetCreaturesWithEntryInRange(unitList, 100.0f, NPC_PUMPKIN_FIEND);
        for (std::list<Creature*>::iterator itr = unitList.begin(); itr != unitList.end(); ++itr)
            (*itr)->ToCreature()->DespawnOrUnsummon(500);
        Map::PlayerList const& players = me->GetMap()->GetPlayers();
        if (!players.IsEmpty() && players.begin()->GetSource() && players.begin()->GetSource()->GetGroup())
            sLFGMgr->FinishDungeon(players.begin()->GetSource()->GetGroup()->GetGUID(), lfg::LFG_DUNGEON_HEADLESS_HORSEMAN, me->FindMap());
        if (InstanceScript* instance = me->GetInstanceScript())
            instance->SetData(DATA_HORSEMAN_EVENT, DONE);
    }
References MapRefMgr::begin(), DATA_HORSEMAN_EVENT, SummonList::DespawnAll(), DONE, WorldObject::FindMap(), WorldObject::GetCreaturesWithEntryInRange(), Player::GetGroup(), Group::GetGUID(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), LinkedListHead::IsEmpty(), lfg::LFG_DUNGEON_HEADLESS_HORSEMAN, ScriptedAI::me, NPC_PUMPKIN_FIEND, sLFGMgr, summons, and TALK_DEATH.
JustEngagedWith()
void boss_headless_horseman::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
{ me->SetInCombatWithZone(); }
References ScriptedAI::me, and Creature::SetInCombatWithZone().
JustReachedHome()
void boss_headless_horseman::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
    {
        if (InstanceScript* instance = me->GetInstanceScript())
            instance->SetData(DATA_HORSEMAN_EVENT, FAIL);
        me->DespawnOrUnsummon();
    }
References DATA_HORSEMAN_EVENT, Creature::DespawnOrUnsummon(), FAIL, WorldObject::GetInstanceScript(), and ScriptedAI::me.
JustSummoned()
void boss_headless_horseman::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
{ summons.Summon(cr); }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_headless_horseman::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        Talk(TALK_PLAYER_DEATH);
    }
References TALK_PLAYER_DEATH.
MoveInLineOfSight()
void boss_headless_horseman::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{}
MovementInform()
void boss_headless_horseman::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type == WAYPOINT_MOTION_TYPE)
        {
            if (point == 0)
                me->CastSpell(me, SPELL_HEAD_VISUAL, true);
            else if (point == 11)
            {
                me->ReplaceAllUnitFlags(UNIT_FLAG_NONE);
                me->StopMoving();
                me->SetDisableGravity(false);
                me->SetInCombatWithZone();
                inFight = true;
                events.ScheduleEvent(EVENT_HORSEMAN_FOLLOW, 500ms);
                events.ScheduleEvent(EVENT_HORSEMAN_CLEAVE, 7s);
            }
        }
    }
References Unit::CastSpell(), EVENT_HORSEMAN_CLEAVE, EVENT_HORSEMAN_FOLLOW, inFight, ScriptedAI::me, Unit::ReplaceAllUnitFlags(), Creature::SetDisableGravity(), Creature::SetInCombatWithZone(), SPELL_HEAD_VISUAL, Unit::StopMoving(), UNIT_FLAG_NONE, and WAYPOINT_MOTION_TYPE.
Reset()
void boss_headless_horseman::Reset () inline override virtual
Reimplemented from ScriptedAI.
    {
        events.Reset();
        summons.DespawnAll();
        playerGUID.Clear();
        talkCount = 0;
        phase = 0;
        inFight = false;
        health = 0;
        me->SetDisableGravity(true);
        me->SetSpeed(MOVE_WALK, 5.0f, true);
    }
References ObjectGuid::Clear(), SummonList::DespawnAll(), health, inFight, ScriptedAI::me, MOVE_WALK, playerGUID, Creature::SetDisableGravity(), Unit::SetSpeed(), summons, and talkCount.
SpellHit()
void boss_headless_horseman::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (spellInfo->Id == SPELL_THROW_HEAD_BACK)
        {
            me->SetHealth(me->GetMaxHealth());
            me->CastSpell(me, SPELL_HEAD_VISUAL, true);
            me->RemoveAura(SPELL_HORSEMAN_IMMUNITY);
            me->RemoveAura(SPELL_HORSEMAN_BODY_REGEN);
            me->RemoveAura(SPELL_HORSEMAN_BODY_REGEN_CONFUSE);
            me->RemoveAura(SPELL_HORSEMAN_WHIRLWIND);
            events.CancelEvent(EVENT_HORSEMAN_CHECK_HEALTH);
            events.CancelEvent(EVENT_HORSEMAN_WHIRLWIND);
            events.CancelEvent(EVENT_HORSEMAN_CONFLAGRATION);
            events.CancelEvent(EVENT_SUMMON_PUMPKIN);
            Talk(TALK_REJOINED);
            if (phase == 1)
                events.ScheduleEvent(EVENT_HORSEMAN_CONFLAGRATION, 6s);
            else if (phase == 2)
                events.ScheduleEvent(EVENT_SUMMON_PUMPKIN, 6s);
        }
    }
References Unit::CastSpell(), EVENT_HORSEMAN_CHECK_HEALTH, EVENT_HORSEMAN_CONFLAGRATION, EVENT_HORSEMAN_WHIRLWIND, EVENT_SUMMON_PUMPKIN, Unit::GetMaxHealth(), SpellInfo::Id, ScriptedAI::me, Unit::RemoveAura(), Unit::SetHealth(), SPELL_HEAD_VISUAL, SPELL_HORSEMAN_BODY_REGEN, SPELL_HORSEMAN_BODY_REGEN_CONFUSE, SPELL_HORSEMAN_IMMUNITY, SPELL_HORSEMAN_WHIRLWIND, SPELL_THROW_HEAD_BACK, and TALK_REJOINED.
SpellHitTarget()
void boss_headless_horseman::SpellHitTarget (Unit * target, SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (spellInfo->Id == SPELL_SUMMONING_RHYME_TARGET)
        {
            playerGUID = target->GetGUID();
            events.ScheduleEvent(EVENT_HH_PLAYER_TALK, 2s);
        }
    }
References EVENT_HH_PLAYER_TALK, Object::GetGUID(), SpellInfo::Id, playerGUID, and SPELL_SUMMONING_RHYME_TARGET.
UpdateAI()
void boss_headless_horseman::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
    {
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
            return;
        if (inFight && !UpdateVictim())
            return;
        switch (events.ExecuteEvent())
        {
            case EVENT_HH_PLAYER_TALK:
                {
                    talkCount++;
                    Player* player = GetRhymePlayer();
                    if (!player)
                        return;
                    switch (talkCount)
                    {
                        case 1:
                            player->Say(TALK_PLAYER_RISE);
                            break;
                        case 2:
                            player->Say(TALK_PLAYER_TIME_IS_NIGH);
                            if (Creature* trigger = me->SummonTrigger(1765.28f, 1347.46f, 17.5514f, 0.0f, 15 * IN_MILLISECONDS))
                                trigger->CastSpell(trigger, SPELL_EARTH_EXPLOSION, true);
                            break;
                        case 3:
                            me->SetDisableGravity(true);
                            me->GetMotionMaster()->MovePath(236820, false);
                            me->CastSpell(me, SPELL_SHAKE_CAMERA_SMALL, true);
                            player->Say(TALK_PLAYER_FELT_DEATH);
                            Talk(TALK_ENTRANCE);
                            break;
                        case 4:
                            me->CastSpell(me, SPELL_SHAKE_CAMERA_MEDIUM, true);
                            player->Say(TALK_PLAYER_KNOW_DEMISE);
                            talkCount = 0;
                            return; // pop and return, skip repeat
                    }
                    events.RepeatEvent(2000);
                    break;
                }
            case EVENT_HORSEMAN_FOLLOW:
                {
                    if (Player* player = GetRhymePlayer())
                    {
                        me->GetMotionMaster()->MoveIdle();
                        AttackStart(player);
                        me->GetMotionMaster()->MoveChase(player);
                    }
                    break;
                }
            case EVENT_HORSEMAN_CLEAVE:
                {
                    me->CastSpell(me->GetVictim(), SPELL_HORSEMAN_CLEAVE, false);
                    events.RepeatEvent(8000);
                    break;
                }
            case EVENT_HORSEMAN_WHIRLWIND:
                {
                    if (me->HasAuraEffect(SPELL_HORSEMAN_WHIRLWIND, EFFECT_0))
                    {
                        me->RemoveAura(SPELL_HORSEMAN_WHIRLWIND);
                        events.RepeatEvent(15000);
                        break;
                    }
                    me->CastSpell(me, SPELL_HORSEMAN_WHIRLWIND, true);
                    events.RepeatEvent(6000);
                    break;
                }
            case EVENT_HORSEMAN_CHECK_HEALTH:
                {
                    if (me->GetHealth() == me->GetMaxHealth())
                    {
                        me->CastSpell(me, SPELL_BODY_RESTORED_INFO, true);
                        return;
                    }
                    events.RepeatEvent(1000);
                    break;
                }
            case EVENT_HORSEMAN_CONFLAGRATION:
                {
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
                    {
                        me->CastSpell(target, SPELL_HORSEMAN_CONFLAGRATION, false);
                        target->CastSpell(target, SPELL_HORSEMAN_CONFLAGRATION_SOUND, true);
                        Talk(TALK_CONFLAGRATION);
                    }
                    events.RepeatEvent(12500);
                    break;
                }
            case EVENT_SUMMON_PUMPKIN:
                {
                    if (talkCount < 4)
                    {
                        events.RepeatEvent(1);
                        talkCount++;
                        me->CastSpell(me, SPELL_SUMMON_PUMPKIN, false);
                    }
                    else
                    {
                        Talk(TALK_SPROUTING_PUMPKINS);
                        events.RepeatEvent(15000);
                        talkCount = 0;
                    }
                    break;
                }
        }
        if (inFight)
            DoMeleeAttackIfReady();
    }
References ScriptedAI::AttackStart(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EFFECT_0, EVENT_HH_PLAYER_TALK, EVENT_HORSEMAN_CHECK_HEALTH, EVENT_HORSEMAN_CLEAVE, EVENT_HORSEMAN_CONFLAGRATION, EVENT_HORSEMAN_FOLLOW, EVENT_HORSEMAN_WHIRLWIND, EVENT_SUMMON_PUMPKIN, Unit::GetHealth(), Unit::GetMaxHealth(), Unit::GetMotionMaster(), GetRhymePlayer(), Unit::GetVictim(), Unit::HasAuraEffect(), Unit::HasUnitState(), IN_MILLISECONDS, inFight, ScriptedAI::me, MotionMaster::MoveChase(), MotionMaster::MoveIdle(), MotionMaster::MovePath(), Unit::RemoveAura(), Player::Say(), UnitAI::SelectTarget(), Creature::SetDisableGravity(), SPELL_BODY_RESTORED_INFO, SPELL_EARTH_EXPLOSION, SPELL_HORSEMAN_CLEAVE, SPELL_HORSEMAN_CONFLAGRATION, SPELL_HORSEMAN_CONFLAGRATION_SOUND, SPELL_HORSEMAN_WHIRLWIND, SPELL_SHAKE_CAMERA_MEDIUM, SPELL_SHAKE_CAMERA_SMALL, SPELL_SUMMON_PUMPKIN, WorldObject::SummonTrigger(), TALK_CONFLAGRATION, TALK_ENTRANCE, TALK_PLAYER_FELT_DEATH, TALK_PLAYER_KNOW_DEMISE, TALK_PLAYER_RISE, TALK_PLAYER_TIME_IS_NIGH, TALK_SPROUTING_PUMPKINS, talkCount, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_headless_horseman::events
health
uint32 boss_headless_horseman::health
Referenced by DamageTaken(), DoAction(), and Reset().
inFight
bool boss_headless_horseman::inFight
Referenced by MovementInform(), Reset(), and UpdateAI().
phase
uint8 boss_headless_horseman::phase
playerGUID
ObjectGuid boss_headless_horseman::playerGUID
Referenced by GetRhymePlayer(), Reset(), and SpellHitTarget().
summons
SummonList boss_headless_horseman::summons
Referenced by JustDied(), JustSummoned(), and Reset().
talkCount
uint8 boss_headless_horseman::talkCount
Referenced by Reset(), and UpdateAI().