AzerothCore: OPvPCapturePointNA Class Reference
OPvPCapturePointNA Class Reference
#include "OutdoorPvPNA.h"
Public Member Functions
OPvPCapturePointNA (OutdoorPvP *pvp)
bool Update (uint32 diff) override
void ChangeState () override
void SendChangePhase () override
void FillInitialWorldStates (WorldPacket &data) override
bool HandlePlayerEnter (Player *player) override
void HandlePlayerLeave (Player *player) override
bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go) override
int32 HandleOpenGo (Player *player, GameObject *go) override
uint32 GetAliveGuardsCount ()
TeamId GetControllingFaction () const
Public Member Functions inherited from OPvPCapturePoint
OPvPCapturePoint (OutdoorPvP *pvp)
virtual ~OPvPCapturePoint ()=default
virtual void FillInitialWorldStates (WorldPacket &)
void SendUpdateWorldState (uint32 field, uint32 value)
void SendObjectiveComplete (uint32 id, ObjectGuid guid=ObjectGuid::Empty)
virtual bool HandlePlayerEnter (Player *player)
virtual void HandlePlayerLeave (Player *player)
bool IsInsideObjective (Player *player) const
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual int32 HandleOpenGo (Player *player, GameObject *go)
virtual bool Update (uint32 diff)
virtual void ChangeState ()=0
virtual void ChangeTeam (TeamId)
virtual void SendChangePhase ()
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipId)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual void DeleteSpawns ()
void AddGO (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
void AddCre (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
bool SetCapturePointData (uint32 entry, uint32 map, float x, float y, float z, float o=0, float rotation0=0, float rotation1=0, float rotation2=0, float rotation3=0)
void SetSlider (float slider)
float GetSlider () const
Protected Member Functions
void FactionTakeOver (TeamId teamId)
void DespawnGOs ()
void DespawnCreatures (HalaaNPCS teamNPC)
void SpawnNPCsForTeam (HalaaNPCS teamNPC)
void SpawnGOsForTeam (TeamId teamId)
void UpdateWyvernRoostWorldState (uint32 roost)
void UpdateHalaaWorldState ()
Protected Member Functions inherited from OPvPCapturePoint
bool AddObject (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3)
bool AddCreature (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, uint32 spawntimeDelay=0)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool DelCapturePoint ()
Private Attributes
bool m_capturable
uint32 m_GuardsAlive
TeamId m_ControllingFaction
uint32 m_WyvernStateNorth
uint32 m_WyvernStateSouth
uint32 m_WyvernStateEast
uint32 m_WyvernStateWest
uint32 m_HalaaState
uint32 m_RespawnTimer
uint32 m_GuardCheckTimer
bool m_canRecap
Additional Inherited Members
Public Attributes inherited from OPvPCapturePoint
ObjectGuid::LowType m_capturePointSpawnId {}
GameObject * _capturePoint {}
Protected Attributes inherited from OPvPCapturePoint
std::array< PlayerSet, 2 > _activePlayers
float _maxValue {}
float _minValue {}
float _maxSpeed {}
float _value {}
TeamId _team { TEAM_NEUTRAL }
ObjectiveStates _oldState { OBJECTIVESTATE_NEUTRAL }
ObjectiveStates _state { OBJECTIVESTATE_NEUTRAL }
uint32 _neutralValuePct {}
OutdoorPvP * _pvp {}
std::unordered_map< uint32, ObjectGuid::LowType > _objects
std::unordered_map< uint32, ObjectGuid::LowType > _creatures
std::unordered_map< ObjectGuid::LowType, uint32 > _objectTypes
std::unordered_map< ObjectGuid::LowType, uint32 > _creatureTypes
Detailed Description
Constructor & Destructor Documentation
OPvPCapturePointNA()
OPvPCapturePointNA::OPvPCapturePointNA (OutdoorPvP * pvp)
                                                      :
    OPvPCapturePoint(pvp), m_capturable(true), m_GuardsAlive(0), m_ControllingFaction(TEAM_NEUTRAL),
    m_WyvernStateNorth(0), m_WyvernStateSouth(0), m_WyvernStateEast(0), m_WyvernStateWest(0),
    m_HalaaState(HALAA_N), m_RespawnTimer(NA_RESPAWN_TIME), m_GuardCheckTimer(NA_GUARD_CHECK_TIME), m_canRecap(true)
{
    SetCapturePointData(182210, 530, -1572.57f, 7945.3f, -22.475f, 2.05949f, 0.0f, 0.0f, 0.857167f, 0.515038f);
}
References OPvPCapturePoint::SetCapturePointData().
Member Function Documentation
ChangeState()
void OPvPCapturePointNA::ChangeState () override virtual
Implements OPvPCapturePoint.
{
    uint32 artkit = 21;
    switch (_state)
    {
        case OBJECTIVESTATE_NEUTRAL:
            m_HalaaState = HALAA_N;
            break;
        case OBJECTIVESTATE_ALLIANCE:
            m_HalaaState = HALAA_A;
            if (m_canRecap)
                FactionTakeOver(TEAM_ALLIANCE);
            artkit = 2;
            break;
        case OBJECTIVESTATE_HORDE:
            m_HalaaState = HALAA_H;
            if (m_canRecap)
                FactionTakeOver(TEAM_HORDE);
            artkit = 1;
            break;
        case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
            m_HalaaState = HALAA_N_A;
            break;
        case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
            m_HalaaState = HALAA_N_H;
            break;
        case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
            m_HalaaState = HALAA_N_A;
            artkit = 2;
            break;
        case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
            m_HalaaState = HALAA_N_H;
            artkit = 1;
            break;
    }
    auto bounds = sMapMgr->FindMap(530, 0)->GetGameObjectBySpawnIdStore().equal_range(m_capturePointSpawnId);
    for (auto itr = bounds.first; itr != bounds.second; ++itr)
        itr->second->SetGoArtKit(artkit);
    UpdateHalaaWorldState();
}
References OPvPCapturePoint::_state, FactionTakeOver(), HALAA_A, HALAA_H, HALAA_N, HALAA_N_A, HALAA_N_H, m_canRecap, OPvPCapturePoint::m_capturePointSpawnId, m_HalaaState, OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL, OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE, sMapMgr, TEAM_ALLIANCE, TEAM_HORDE, and UpdateHalaaWorldState().
Referenced by Update().
DespawnCreatures()
void OPvPCapturePointNA::DespawnCreatures (HalaaNPCS teamNPC) protected
{
    for (int i = 0; i < NA_HALAA_CREATURE_TEAM_SPAWN; i++)
    {
        ObjectGuid::LowType spawnId = teamNPC[i];
        auto bounds = _pvp->GetMap()->GetCreatureBySpawnIdStore().equal_range(spawnId);
        CreatureData const* data = sObjectMgr->GetCreatureData(spawnId);
        for (auto itr = bounds.first; itr != bounds.second;)
        {
            // can happen when closing the core
            Creature* c = itr->second;
            if (c)
            {
                ++itr;
                c->AddObjectToRemoveList();
                sObjectMgr->RemoveCreatureFromGrid(spawnId, data);
                _creatures[i] = 0;
                _creatureTypes[_creatures[i]] = 0;
            }
        }
    }
}
References OPvPCapturePoint::_creatures, OPvPCapturePoint::_creatureTypes, OPvPCapturePoint::_pvp, WorldObject::AddObjectToRemoveList(), Map::GetCreatureBySpawnIdStore(), OutdoorPvP::GetMap(), NA_HALAA_CREATURE_TEAM_SPAWN, and sObjectMgr.
Referenced by FactionTakeOver(), and Update().
DespawnGOs()
void OPvPCapturePointNA::DespawnGOs () protected
{
    for (int i = 0; i < NA_CONTROL_GO_NUM; ++i)
    {
        DelObject(i);
    }
}
References OPvPCapturePoint::DelObject(), and NA_CONTROL_GO_NUM.
Referenced by FactionTakeOver(), and Update().
FactionTakeOver()
void OPvPCapturePointNA::FactionTakeOver (TeamId teamId) protected
{
    if (m_ControllingFaction != TEAM_NEUTRAL)
        sGraveyard->RemoveGraveyardLink(NA_HALAA_GRAVEYARD, NA_HALAA_GRAVEYARD_ZONE, m_ControllingFaction, false);
    if (m_ControllingFaction == TEAM_ALLIANCE)
        sWorld->SendZoneText(NA_HALAA_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_NA_LOSE_A));
    else if (m_ControllingFaction == TEAM_HORDE)
        sWorld->SendZoneText(NA_HALAA_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_NA_LOSE_H));
    DespawnCreatures(GetControllingFaction() == TEAM_HORDE ? halaaNPCHorde : halaaNPCAlly);
    m_ControllingFaction = teamId;
    if (m_ControllingFaction != TEAM_NEUTRAL)
        sGraveyard->AddGraveyardLink(NA_HALAA_GRAVEYARD, NA_HALAA_GRAVEYARD_ZONE, m_ControllingFaction, false);
    DespawnGOs();
    SpawnGOsForTeam(teamId);
    SpawnNPCsForTeam(GetControllingFaction() == TEAM_HORDE ? halaaNPCHorde : halaaNPCAlly);
    m_GuardsAlive = NA_GUARDS_MAX;
    m_capturable = false;
    m_canRecap = false;
    this->UpdateHalaaWorldState();
    if (teamId == TEAM_ALLIANCE)
    {
        m_WyvernStateSouth = WYVERN_NEU_HORDE;
        m_WyvernStateNorth = WYVERN_NEU_HORDE;
        m_WyvernStateEast = WYVERN_NEU_HORDE;
        m_WyvernStateWest = WYVERN_NEU_HORDE;
        _pvp->TeamApplyBuff(TEAM_ALLIANCE, NA_CAPTURE_BUFF);
        _pvp->SendUpdateWorldState(NA_UI_HORDE_GUARDS_SHOW, 0);
        _pvp->SendUpdateWorldState(NA_UI_ALLIANCE_GUARDS_SHOW, 1);
        _pvp->SendUpdateWorldState(NA_UI_GUARDS_LEFT, m_GuardsAlive);
        sWorld->SendZoneText(NA_HALAA_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_NA_CAPTURE_A));
    }
    else
    {
        m_WyvernStateSouth = WYVERN_NEU_ALLIANCE;
        m_WyvernStateNorth = WYVERN_NEU_ALLIANCE;
        m_WyvernStateEast = WYVERN_NEU_ALLIANCE;
        m_WyvernStateWest = WYVERN_NEU_ALLIANCE;
        _pvp->TeamApplyBuff(TEAM_HORDE, NA_CAPTURE_BUFF);
        _pvp->SendUpdateWorldState(NA_UI_HORDE_GUARDS_SHOW, 1);
        _pvp->SendUpdateWorldState(NA_UI_ALLIANCE_GUARDS_SHOW, 0);
        _pvp->SendUpdateWorldState(NA_UI_GUARDS_LEFT, m_GuardsAlive);
        sWorld->SendZoneText(NA_HALAA_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_NA_CAPTURE_H));
    }
    UpdateWyvernRoostWorldState(NA_ROOST_S);
    UpdateWyvernRoostWorldState(NA_ROOST_N);
    UpdateWyvernRoostWorldState(NA_ROOST_W);
    UpdateWyvernRoostWorldState(NA_ROOST_E);
}
References OPvPCapturePoint::_pvp, DespawnCreatures(), DespawnGOs(), GetControllingFaction(), halaaNPCAlly, halaaNPCHorde, LANG_OPVP_NA_CAPTURE_A, LANG_OPVP_NA_CAPTURE_H, LANG_OPVP_NA_LOSE_A, LANG_OPVP_NA_LOSE_H, m_canRecap, m_capturable, m_ControllingFaction, m_GuardsAlive, m_WyvernStateEast, m_WyvernStateNorth, m_WyvernStateSouth, m_WyvernStateWest, NA_CAPTURE_BUFF, NA_GUARDS_MAX, NA_HALAA_GRAVEYARD, NA_HALAA_GRAVEYARD_ZONE, NA_ROOST_E, NA_ROOST_N, NA_ROOST_S, NA_ROOST_W, NA_UI_ALLIANCE_GUARDS_SHOW, NA_UI_GUARDS_LEFT, NA_UI_HORDE_GUARDS_SHOW, OutdoorPvP::SendUpdateWorldState(), sGraveyard, sObjectMgr, SpawnGOsForTeam(), SpawnNPCsForTeam(), sWorld, TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, OutdoorPvP::TeamApplyBuff(), UpdateHalaaWorldState(), UpdateWyvernRoostWorldState(), WYVERN_NEU_ALLIANCE, and WYVERN_NEU_HORDE.
Referenced by ChangeState(), and Update().
FillInitialWorldStates()
void OPvPCapturePointNA::FillInitialWorldStates (WorldPacket & data) override virtual
Reimplemented from OPvPCapturePoint.
{
    if (m_ControllingFaction == TEAM_ALLIANCE)
    {
        data << NA_UI_HORDE_GUARDS_SHOW << uint32(0);
        data << NA_UI_ALLIANCE_GUARDS_SHOW << uint32(1);
    }
    else if (m_ControllingFaction == TEAM_HORDE)
    {
        data << NA_UI_HORDE_GUARDS_SHOW << uint32(1);
        data << NA_UI_ALLIANCE_GUARDS_SHOW << uint32(0);
    }
    else
    {
        data << NA_UI_HORDE_GUARDS_SHOW << uint32(0);
        data << NA_UI_ALLIANCE_GUARDS_SHOW << uint32(0);
    }
    data << NA_UI_GUARDS_MAX << NA_GUARDS_MAX;
    data << NA_UI_GUARDS_LEFT << uint32(m_GuardsAlive);
    data << NA_UI_TOWER_SLIDER_DISPLAY << uint32(0);
    data << NA_UI_TOWER_SLIDER_POS << uint32(50);
    data << NA_UI_TOWER_SLIDER_N << uint32(100);
    data << NA_MAP_WYVERN_NORTH_NEU_H << uint32(bool(m_WyvernStateNorth & WYVERN_NEU_HORDE));
    data << NA_MAP_WYVERN_NORTH_NEU_A << uint32(bool(m_WyvernStateNorth & WYVERN_NEU_ALLIANCE));
    data << NA_MAP_WYVERN_NORTH_H << uint32(bool(m_WyvernStateNorth & WYVERN_HORDE));
    data << NA_MAP_WYVERN_NORTH_A << uint32(bool(m_WyvernStateNorth & WYVERN_ALLIANCE));
    data << NA_MAP_WYVERN_SOUTH_NEU_H << uint32(bool(m_WyvernStateSouth & WYVERN_NEU_HORDE));
    data << NA_MAP_WYVERN_SOUTH_NEU_A << uint32(bool(m_WyvernStateSouth & WYVERN_NEU_ALLIANCE));
    data << NA_MAP_WYVERN_SOUTH_H << uint32(bool(m_WyvernStateSouth & WYVERN_HORDE));
    data << NA_MAP_WYVERN_SOUTH_A << uint32(bool(m_WyvernStateSouth & WYVERN_ALLIANCE));
    data << NA_MAP_WYVERN_WEST_NEU_H << uint32(bool(m_WyvernStateWest & WYVERN_NEU_HORDE));
    data << NA_MAP_WYVERN_WEST_NEU_A << uint32(bool(m_WyvernStateWest & WYVERN_NEU_ALLIANCE));
    data << NA_MAP_WYVERN_WEST_H << uint32(bool(m_WyvernStateWest & WYVERN_HORDE));
    data << NA_MAP_WYVERN_WEST_A << uint32(bool(m_WyvernStateWest & WYVERN_ALLIANCE));
    data << NA_MAP_WYVERN_EAST_NEU_H << uint32(bool(m_WyvernStateEast & WYVERN_NEU_HORDE));
    data << NA_MAP_WYVERN_EAST_NEU_A << uint32(bool(m_WyvernStateEast & WYVERN_NEU_ALLIANCE));
    data << NA_MAP_WYVERN_EAST_H << uint32(bool(m_WyvernStateEast & WYVERN_HORDE));
    data << NA_MAP_WYVERN_EAST_A << uint32(bool(m_WyvernStateEast & WYVERN_ALLIANCE));
    data << NA_MAP_HALAA_NEUTRAL << uint32(bool(m_HalaaState & HALAA_N));
    data << NA_MAP_HALAA_NEU_A << uint32(bool(m_HalaaState & HALAA_N_A));
    data << NA_MAP_HALAA_NEU_H << uint32(bool(m_HalaaState & HALAA_N_H));
    data << NA_MAP_HALAA_HORDE << uint32(bool(m_HalaaState & HALAA_H));
    data << NA_MAP_HALAA_ALLIANCE << uint32(bool(m_HalaaState & HALAA_A));
}
References HALAA_A, HALAA_H, HALAA_N, HALAA_N_A, HALAA_N_H, m_ControllingFaction, m_GuardsAlive, m_HalaaState, m_WyvernStateEast, m_WyvernStateNorth, m_WyvernStateSouth, m_WyvernStateWest, NA_GUARDS_MAX, NA_MAP_HALAA_ALLIANCE, NA_MAP_HALAA_HORDE, NA_MAP_HALAA_NEU_A, NA_MAP_HALAA_NEU_H, NA_MAP_HALAA_NEUTRAL, NA_MAP_WYVERN_EAST_A, NA_MAP_WYVERN_EAST_H, NA_MAP_WYVERN_EAST_NEU_A, NA_MAP_WYVERN_EAST_NEU_H, NA_MAP_WYVERN_NORTH_A, NA_MAP_WYVERN_NORTH_H, NA_MAP_WYVERN_NORTH_NEU_A, NA_MAP_WYVERN_NORTH_NEU_H, NA_MAP_WYVERN_SOUTH_A, NA_MAP_WYVERN_SOUTH_H, NA_MAP_WYVERN_SOUTH_NEU_A, NA_MAP_WYVERN_SOUTH_NEU_H, NA_MAP_WYVERN_WEST_A, NA_MAP_WYVERN_WEST_H, NA_MAP_WYVERN_WEST_NEU_A, NA_MAP_WYVERN_WEST_NEU_H, NA_UI_ALLIANCE_GUARDS_SHOW, NA_UI_GUARDS_LEFT, NA_UI_GUARDS_MAX, NA_UI_HORDE_GUARDS_SHOW, NA_UI_TOWER_SLIDER_DISPLAY, NA_UI_TOWER_SLIDER_N, NA_UI_TOWER_SLIDER_POS, TEAM_ALLIANCE, TEAM_HORDE, WYVERN_ALLIANCE, WYVERN_HORDE, WYVERN_NEU_ALLIANCE, and WYVERN_NEU_HORDE.
Referenced by OutdoorPvPNA::FillInitialWorldStates().
GetAliveGuardsCount()
uint32 OPvPCapturePointNA::GetAliveGuardsCount ()
{
    uint32 count = 0;
    for (auto itr = _creatures.begin(); itr != _creatures.end(); ++itr)
    {
        auto bounds = _pvp->GetMap()->GetCreatureBySpawnIdStore().equal_range(itr->second);
        for (auto itr2 = bounds.first; itr2 != bounds.second; ++itr2)
            if (itr2->second->IsAlive() && (itr2->second->GetEntry() == NA_HALAANI_GUARD_A || itr2->second->GetEntry() == NA_HALAANI_GUARD_H))
                ++count;
    }
    return count;
}
References OPvPCapturePoint::_creatures, OPvPCapturePoint::_pvp, Map::GetCreatureBySpawnIdStore(), OutdoorPvP::GetMap(), NA_HALAANI_GUARD_A, and NA_HALAANI_GUARD_H.
Referenced by Update().
GetControllingFaction()
TeamId OPvPCapturePointNA::GetControllingFaction () const
{
    return m_ControllingFaction;
}
References m_ControllingFaction.
Referenced by FactionTakeOver(), OutdoorPvPNA::HandlePlayerEnterZone(), and Update().
HandleCustomSpell()
bool OPvPCapturePointNA::HandleCustomSpell (Player * player, uint32 spellId, GameObject * go) override virtual
Reimplemented from OPvPCapturePoint.
{
    std::vector<uint32> nodes;
    nodes.resize(2);
    bool retval = false;
    switch (spellId)
    {
        case NA_SPELL_FLY_NORTH:
            nodes[0] = FlightPathStartNodes[NA_ROOST_N];
            nodes[1] = FlightPathEndNodes[NA_ROOST_N];
            player->ActivateTaxiPathTo(nodes);
            FlagPlayerPvP(player);
            retval = true;
            break;
        case NA_SPELL_FLY_SOUTH:
            nodes[0] = FlightPathStartNodes[NA_ROOST_S];
            nodes[1] = FlightPathEndNodes[NA_ROOST_S];
            player->ActivateTaxiPathTo(nodes);
            FlagPlayerPvP(player);
            retval = true;
            break;
        case NA_SPELL_FLY_WEST:
            nodes[0] = FlightPathStartNodes[NA_ROOST_W];
            nodes[1] = FlightPathEndNodes[NA_ROOST_W];
            player->ActivateTaxiPathTo(nodes);
            FlagPlayerPvP(player);
            retval = true;
            break;
        case NA_SPELL_FLY_EAST:
            nodes[0] = FlightPathStartNodes[NA_ROOST_E];
            nodes[1] = FlightPathEndNodes[NA_ROOST_E];
            player->ActivateTaxiPathTo(nodes);
            FlagPlayerPvP(player);
            retval = true;
            break;
        default:
            break;
    }
    if (retval)
    {
        //Adding items
        uint32 noSpaceForCount = 0;
        // check space and find places
        ItemPosCountVec dest;
        int32 count = 10;
        // bomb id count
        InventoryResult msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, NA_HALAA_BOMB, count, &noSpaceForCount);
        if (msg != EQUIP_ERR_OK)                               // convert to possible store amount
            count -= noSpaceForCount;
        if (count == 0 || dest.empty())                         // can't add any
        {
            return true;
        }
        Item* item = player->StoreNewItem(dest, NA_HALAA_BOMB, true);
        if (count > 0 && item)
        {
            player->SendNewItem(item, count, true, false);
        }
        return true;
    }
    return false;
}
References Player::ActivateTaxiPathTo(), Player::CanStoreNewItem(), EQUIP_ERR_OK, FlagPlayerPvP(), FlightPathEndNodes, FlightPathStartNodes, NA_HALAA_BOMB, NA_ROOST_E, NA_ROOST_N, NA_ROOST_S, NA_ROOST_W, NA_SPELL_FLY_EAST, NA_SPELL_FLY_NORTH, NA_SPELL_FLY_SOUTH, NA_SPELL_FLY_WEST, NULL_BAG, NULL_SLOT, Player::SendNewItem(), and Player::StoreNewItem().
HandleOpenGo()
int32 OPvPCapturePointNA::HandleOpenGo (Player * player, GameObject * go) override virtual
Reimplemented from OPvPCapturePoint.
{
    int32 retval = OPvPCapturePoint::HandleOpenGo(player, go);
    if (retval >= 0)
    {
        const go_type* gos = nullptr;
        if (m_ControllingFaction == TEAM_ALLIANCE)
            gos = AllianceControlGOs;
        else if (m_ControllingFaction == TEAM_HORDE)
            gos = HordeControlGOs;
        else
            return -1;
        int32 del = -1;
        int32 del2 = -1;
        int32 add = -1;
        int32 add2 = -1;
        switch (retval)
        {
            case NA_DESTROYED_ROOST_S:
                del = NA_DESTROYED_ROOST_S;
                add = NA_ROOST_S;
                add2 = NA_BOMB_WAGON_S;
                if (m_ControllingFaction == TEAM_HORDE)
                    m_WyvernStateSouth = WYVERN_ALLIANCE;
                else
                    m_WyvernStateSouth = WYVERN_HORDE;
                UpdateWyvernRoostWorldState(NA_ROOST_S);
                FlagPlayerPvP(player);
                break;
            case NA_DESTROYED_ROOST_N:
                del = NA_DESTROYED_ROOST_N;
                add = NA_ROOST_N;
                add2 = NA_BOMB_WAGON_N;
                if (m_ControllingFaction == TEAM_HORDE)
                    m_WyvernStateNorth = WYVERN_ALLIANCE;
                else
                    m_WyvernStateNorth = WYVERN_HORDE;
                UpdateWyvernRoostWorldState(NA_ROOST_N);
                FlagPlayerPvP(player);
                break;
            case NA_DESTROYED_ROOST_W:
                del = NA_DESTROYED_ROOST_W;
                add = NA_ROOST_W;
                add2 = NA_BOMB_WAGON_W;
                if (m_ControllingFaction == TEAM_HORDE)
                    m_WyvernStateWest = WYVERN_ALLIANCE;
                else
                    m_WyvernStateWest = WYVERN_HORDE;
                UpdateWyvernRoostWorldState(NA_ROOST_W);
                FlagPlayerPvP(player);
                break;
            case NA_DESTROYED_ROOST_E:
                del = NA_DESTROYED_ROOST_E;
                add = NA_ROOST_E;
                add2 = NA_BOMB_WAGON_E;
                if (m_ControllingFaction == TEAM_HORDE)
                    m_WyvernStateEast = WYVERN_ALLIANCE;
                else
                    m_WyvernStateEast = WYVERN_HORDE;
                UpdateWyvernRoostWorldState(NA_ROOST_E);
                FlagPlayerPvP(player);
                break;
            case NA_BOMB_WAGON_S:
                del = NA_BOMB_WAGON_S;
                del2 = NA_ROOST_S;
                add = NA_DESTROYED_ROOST_S;
                if (m_ControllingFaction == TEAM_HORDE)
                    m_WyvernStateSouth = WYVERN_NEU_ALLIANCE;
                else
                    m_WyvernStateSouth = WYVERN_NEU_HORDE;
                UpdateWyvernRoostWorldState(NA_ROOST_S);
                FlagPlayerPvP(player);
                break;
            case NA_BOMB_WAGON_N:
                del = NA_BOMB_WAGON_N;
                del2 = NA_ROOST_N;
                add = NA_DESTROYED_ROOST_N;
                if (m_ControllingFaction == TEAM_HORDE)
                    m_WyvernStateNorth = WYVERN_NEU_ALLIANCE;
                else
                    m_WyvernStateNorth = WYVERN_NEU_HORDE;
                UpdateWyvernRoostWorldState(NA_ROOST_N);
                FlagPlayerPvP(player);
                break;
            case NA_BOMB_WAGON_W:
                del = NA_BOMB_WAGON_W;
                del2 = NA_ROOST_W;
                add = NA_DESTROYED_ROOST_W;
                if (m_ControllingFaction == TEAM_HORDE)
                    m_WyvernStateWest = WYVERN_NEU_ALLIANCE;
                else
                    m_WyvernStateWest = WYVERN_NEU_HORDE;
                UpdateWyvernRoostWorldState(NA_ROOST_W);
                FlagPlayerPvP(player);
                break;
            case NA_BOMB_WAGON_E:
                del = NA_BOMB_WAGON_E;
                del2 = NA_ROOST_E;
                add = NA_DESTROYED_ROOST_E;
                if (m_ControllingFaction == TEAM_HORDE)
                    m_WyvernStateEast = WYVERN_NEU_ALLIANCE;
                else
                    m_WyvernStateEast = WYVERN_NEU_HORDE;
                UpdateWyvernRoostWorldState(NA_ROOST_E);
                FlagPlayerPvP(player);
                break;
            default:
                return -1;
                break;
        }
        if (del > -1)
            DelObject(del);
        if (del2 > -1)
            DelObject(del2);
        if (add > -1)
            AddObject(add, gos[add].entry, gos[add].map, gos[add].x, gos[add].y, gos[add].z, gos[add].o, gos[add].rot0, gos[add].rot1, gos[add].rot2, gos[add].rot3);
        if (add2 > -1)
            AddObject(add2, gos[add2].entry, gos[add2].map, gos[add2].x, gos[add2].y, gos[add2].z, gos[add2].o, gos[add2].rot0, gos[add2].rot1, gos[add2].rot2, gos[add2].rot3);
        return retval;
    }
    return -1;
}
References OPvPCapturePoint::AddObject(), AllianceControlGOs, OPvPCapturePoint::DelObject(), FlagPlayerPvP(), OPvPCapturePoint::HandleOpenGo(), HordeControlGOs, m_ControllingFaction, m_WyvernStateEast, m_WyvernStateNorth, m_WyvernStateSouth, m_WyvernStateWest, NA_BOMB_WAGON_E, NA_BOMB_WAGON_N, NA_BOMB_WAGON_S, NA_BOMB_WAGON_W, NA_DESTROYED_ROOST_E, NA_DESTROYED_ROOST_N, NA_DESTROYED_ROOST_S, NA_DESTROYED_ROOST_W, NA_ROOST_E, NA_ROOST_N, NA_ROOST_S, NA_ROOST_W, TEAM_ALLIANCE, TEAM_HORDE, UpdateWyvernRoostWorldState(), WYVERN_ALLIANCE, WYVERN_HORDE, WYVERN_NEU_ALLIANCE, and WYVERN_NEU_HORDE.
HandlePlayerEnter()
bool OPvPCapturePointNA::HandlePlayerEnter (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
{
    if (OPvPCapturePoint::HandlePlayerEnter(player))
    {
        player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_DISPLAY, 1);
        uint32 phase = (uint32)ceil((_value + _maxValue) / (2 * _maxValue) * 100.0f);
        player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_POS, phase);
        player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_N, _neutralValuePct);
        return true;
    }
    return false;
}
References OPvPCapturePoint::_maxValue, OPvPCapturePoint::_neutralValuePct, OPvPCapturePoint::_value, OPvPCapturePoint::HandlePlayerEnter(), NA_UI_TOWER_SLIDER_DISPLAY, NA_UI_TOWER_SLIDER_N, NA_UI_TOWER_SLIDER_POS, and Player::SendUpdateWorldState().
Referenced by Update().
HandlePlayerLeave()
void OPvPCapturePointNA::HandlePlayerLeave (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
{
    player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_DISPLAY, 0);
    OPvPCapturePoint::HandlePlayerLeave(player);
}
References OPvPCapturePoint::HandlePlayerLeave(), NA_UI_TOWER_SLIDER_DISPLAY, and Player::SendUpdateWorldState().
Referenced by Update().
SendChangePhase()
void OPvPCapturePointNA::SendChangePhase () override virtual
Reimplemented from OPvPCapturePoint.
{
    // send this too, sometimes the slider disappears, dunno why :(
    SendUpdateWorldState(NA_UI_TOWER_SLIDER_DISPLAY, 1);
    // send these updates to only the ones in this objective
    uint32 phase = (uint32)ceil((_value + _maxValue) / (2 * _maxValue) * 100.0f);
    SendUpdateWorldState(NA_UI_TOWER_SLIDER_POS, phase);
    SendUpdateWorldState(NA_UI_TOWER_SLIDER_N, _neutralValuePct);
}
References OPvPCapturePoint::_maxValue, OPvPCapturePoint::_neutralValuePct, OPvPCapturePoint::_value, NA_UI_TOWER_SLIDER_DISPLAY, NA_UI_TOWER_SLIDER_N, NA_UI_TOWER_SLIDER_POS, and OPvPCapturePoint::SendUpdateWorldState().
Referenced by Update().
SpawnGOsForTeam()
void OPvPCapturePointNA::SpawnGOsForTeam (TeamId teamId) protected
{
    const go_type* gos = nullptr;
    if (teamId == TEAM_ALLIANCE)
        gos = AllianceControlGOs;
    else if (teamId == TEAM_HORDE)
        gos = HordeControlGOs;
    else
        return;
    for (int i = 0; i < NA_CONTROL_GO_NUM; ++i)
    {
        if (i == NA_ROOST_S ||
                i == NA_ROOST_W ||
                i == NA_ROOST_N ||
                i == NA_ROOST_E ||
                i == NA_BOMB_WAGON_S ||
                i == NA_BOMB_WAGON_W ||
                i == NA_BOMB_WAGON_N ||
                i == NA_BOMB_WAGON_E)
            continue;   // roosts and bomb wagons are spawned when someone uses the matching destroyed roost
        AddObject(i, gos[i].entry, gos[i].map, gos[i].x, gos[i].y, gos[i].z, gos[i].o, gos[i].rot0, gos[i].rot1, gos[i].rot2, gos[i].rot3);
    }
}
References OPvPCapturePoint::AddObject(), AllianceControlGOs, HordeControlGOs, NA_BOMB_WAGON_E, NA_BOMB_WAGON_N, NA_BOMB_WAGON_S, NA_BOMB_WAGON_W, NA_CONTROL_GO_NUM, NA_ROOST_E, NA_ROOST_N, NA_ROOST_S, NA_ROOST_W, TEAM_ALLIANCE, and TEAM_HORDE.
Referenced by FactionTakeOver().
SpawnNPCsForTeam()
void OPvPCapturePointNA::SpawnNPCsForTeam (HalaaNPCS teamNPC) protected
{
    for (int i = 0; i < NA_HALAA_CREATURE_TEAM_SPAWN; i++)
    {
        ObjectGuid::LowType spawnId = teamNPC[i];
        const CreatureData* data = sObjectMgr->GetCreatureData(spawnId);
        if (data) {
            UpdateCreatureHalaa(spawnId, _pvp->GetMap(), data->posX, data->posY);
            _creatures[i] = spawnId;
            _creatureTypes[_creatures[i]] = i;
        }
    }
}
References OPvPCapturePoint::_creatures, OPvPCapturePoint::_creatureTypes, OPvPCapturePoint::_pvp, OutdoorPvP::GetMap(), NA_HALAA_CREATURE_TEAM_SPAWN, CreatureData::posX, CreatureData::posY, sObjectMgr, and UpdateCreatureHalaa().
Referenced by FactionTakeOver().
Update()
bool OPvPCapturePointNA::Update (uint32 diff) override virtual
Reimplemented from OPvPCapturePoint.
{
    if (!_capturePoint)
        return false;
    float radius = ((float)_capturePoint->GetGOInfo()->capturePoint.radius);
    for (PlayerSet playerSet : _activePlayers)
    {
        for (ObjectGuid playerGuid : playerSet)
        {
            if (Player* player = ObjectAccessor::FindPlayer(playerGuid))
                if (!_capturePoint->IsWithinDistInMap(player, radius) || !player->IsOutdoorPvPActive())
                    HandlePlayerLeave(player);
        }
    }
    std::list<Player*> players;
    Acore::AnyPlayerInObjectRangeCheck checker(_capturePoint, radius);
    Acore::PlayerListSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(_capturePoint, players, checker);
    Cell::VisitWorldObjects(_capturePoint, searcher, radius);
    for (Player* player : players)
    {
        if (player->IsOutdoorPvPActive())
        {
            if (_activePlayers[player->GetTeamId()].insert(player->GetGUID()).second)
                HandlePlayerEnter(player);
        }
    }
    if (m_GuardCheckTimer < diff)
    {
        m_GuardCheckTimer = NA_GUARD_CHECK_TIME;
        uint32 cnt = GetAliveGuardsCount();
        if (cnt != m_GuardsAlive)
        {
            m_GuardsAlive = cnt;
            if (m_GuardsAlive == 0)
            {
                m_capturable = true;
                m_RespawnTimer = NA_RESPAWN_TIME;
                sWorld->SendZoneText(NA_HALAA_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_NA_DEFENSELESS));
            }
            else
                m_capturable = false;
            // update the guard count for the players in zone
            _pvp->SendUpdateWorldState(NA_UI_GUARDS_LEFT, m_GuardsAlive);
        }
    }
    else m_GuardCheckTimer -= diff;
    if (m_capturable) {
        if (m_RespawnTimer < diff)
        {
            // if the guards have been killed, then the challenger has one hour to take over halaa.
            // in case they fail to do it, the guards are respawned, and they have to start again.
            if (GetControllingFaction() == TEAM_ALLIANCE) {
                _state = OBJECTIVESTATE_ALLIANCE;
                _value = _maxValue;
            }
            else
            {
                _state = OBJECTIVESTATE_HORDE;
                _value = -_maxValue;
            }
            // we reset again the artkit, map icons, sliders and respawn Halaa for controller team
            SendChangePhase();
            ChangeState();
            FactionTakeOver(GetControllingFaction());
            return true;
        }
        else if (GetControllingFaction() != TEAM_NEUTRAL) // Don't decrease the respawn timer if the team is not HORDE or ALLIANCE
            m_RespawnTimer -= diff;
        // get the difference of numbers
        float factDiff = ((float)_activePlayers[0].size() - (float)_activePlayers[1].size()) * diff / OUTDOORPVP_OBJECTIVE_UPDATE_INTERVAL;
        if (!factDiff)
            return false;
        float maxDiff = _maxSpeed * diff;
        if (factDiff < 0)
        {
            // horde is in majority, but it's already horde-controlled -> no change
            if (_state == OBJECTIVESTATE_HORDE && _value <= -_maxValue)
                return false;
            if (factDiff < -maxDiff)
                factDiff = -maxDiff;
        }
        else
        {
            // ally is in majority, but it's already ally-controlled -> no change
            if (_state == OBJECTIVESTATE_ALLIANCE && _value >= _maxValue)
                return false;
            if (factDiff > maxDiff)
                factDiff = maxDiff;
        }
        float oldValue = _value;
        TeamId oldTeam = _team;
        _oldState = _state;
        _value += factDiff;
        if (_value < -_minValue) // red
        {
            if (_value < -_maxValue) //check if the m_value is lower than max, that means horde capped point
            {
                _value = -_maxValue;
                _state = OBJECTIVESTATE_HORDE;
                _team = TEAM_HORDE;
            }
            else //then point is still in battle between teams
            {
                if (_oldState == OBJECTIVESTATE_NEUTRAL || _oldState == OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE || _oldState == OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE)
                {
                    _state = OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE;
                }
                else
                {
                    _state = OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE;
                }
            }
            if (GetControllingFaction() == TEAM_ALLIANCE && !m_canRecap)
            {
                //When the point goes through neutral, the same faction can recapture again to respawn the guards, still need check blizzlike
                m_canRecap = true;
                DespawnGOs();
                DespawnCreatures(GetControllingFaction() == TEAM_HORDE ? halaaNPCHorde : halaaNPCAlly);
            }
        }
        else //blue
        {
            if (_value > _maxValue) //check if the m_value is bigger than max, that means alliance capped point
            {
                _value = _maxValue;
                _state = OBJECTIVESTATE_ALLIANCE;
                _team = TEAM_ALLIANCE;
            }
            else //then point is still in battle between teams
            {
                if (_oldState == OBJECTIVESTATE_NEUTRAL || _oldState == OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE || _oldState == OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE)
                {
                    _state = OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE;
                }
                else
                {
                    _state = OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE;
                }
            }
            if (GetControllingFaction() == TEAM_HORDE && !m_canRecap)
            {
                //When the point goes through neutral, the same faction can recapture again to respawn the guards, still need check blizzlike
                m_canRecap = true;
                DespawnGOs();
                DespawnCreatures(GetControllingFaction() == TEAM_HORDE ? halaaNPCHorde : halaaNPCAlly);
            }
        }
        if (_value != oldValue)
        {
            SendChangePhase();
        }
        if (_oldState != _state)
        {
            if (oldTeam != _team)
            {
                ChangeTeam(oldTeam);
            }
            ChangeState();
            return true;
        }
    }
    else
        SendUpdateWorldState(NA_UI_TOWER_SLIDER_DISPLAY, 0); //Point is not capturable so we hide the slider
    return false;
}
References OPvPCapturePoint::_activePlayers, OPvPCapturePoint::_capturePoint, OPvPCapturePoint::_maxSpeed, OPvPCapturePoint::_maxValue, OPvPCapturePoint::_minValue, OPvPCapturePoint::_oldState, OPvPCapturePoint::_pvp, OPvPCapturePoint::_state, OPvPCapturePoint::_team, OPvPCapturePoint::_value, GameObjectTemplate::capturePoint, ChangeState(), OPvPCapturePoint::ChangeTeam(), DespawnCreatures(), DespawnGOs(), FactionTakeOver(), ObjectAccessor::FindPlayer(), GetAliveGuardsCount(), GetControllingFaction(), GameObject::GetGOInfo(), halaaNPCAlly, halaaNPCHorde, HandlePlayerEnter(), HandlePlayerLeave(), GameObject::IsWithinDistInMap(), LANG_OPVP_NA_DEFENSELESS, m_canRecap, m_capturable, m_GuardCheckTimer, m_GuardsAlive, m_RespawnTimer, NA_GUARD_CHECK_TIME, NA_HALAA_GRAVEYARD_ZONE, NA_RESPAWN_TIME, NA_UI_GUARDS_LEFT, NA_UI_TOWER_SLIDER_DISPLAY, OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL, OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE, OUTDOORPVP_OBJECTIVE_UPDATE_INTERVAL, GameObjectTemplate::radius, SendChangePhase(), OPvPCapturePoint::SendUpdateWorldState(), OutdoorPvP::SendUpdateWorldState(), sObjectMgr, sWorld, TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, and Cell::VisitWorldObjects().
Referenced by OutdoorPvPNA::Update().
UpdateHalaaWorldState()
void OPvPCapturePointNA::UpdateHalaaWorldState () protected
{
    _pvp->SendUpdateWorldState(NA_MAP_HALAA_NEUTRAL, uint32(bool(m_HalaaState & HALAA_N)));
    _pvp->SendUpdateWorldState(NA_MAP_HALAA_NEU_A, uint32(bool(m_HalaaState & HALAA_N_A)));
    _pvp->SendUpdateWorldState(NA_MAP_HALAA_NEU_H, uint32(bool(m_HalaaState & HALAA_N_H)));
    _pvp->SendUpdateWorldState(NA_MAP_HALAA_HORDE, uint32(bool(m_HalaaState & HALAA_H)));
    _pvp->SendUpdateWorldState(NA_MAP_HALAA_ALLIANCE, uint32(bool(m_HalaaState & HALAA_A)));
}
References OPvPCapturePoint::_pvp, HALAA_A, HALAA_H, HALAA_N, HALAA_N_A, HALAA_N_H, m_HalaaState, NA_MAP_HALAA_ALLIANCE, NA_MAP_HALAA_HORDE, NA_MAP_HALAA_NEU_A, NA_MAP_HALAA_NEU_H, NA_MAP_HALAA_NEUTRAL, and OutdoorPvP::SendUpdateWorldState().
Referenced by ChangeState(), and FactionTakeOver().
UpdateWyvernRoostWorldState()
void OPvPCapturePointNA::UpdateWyvernRoostWorldState (uint32 roost) protected
{
    switch (roost)
    {
        case NA_ROOST_S:
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_NEU_H, uint32(bool(m_WyvernStateSouth & WYVERN_NEU_HORDE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_NEU_A, uint32(bool(m_WyvernStateSouth & WYVERN_NEU_ALLIANCE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_H, uint32(bool(m_WyvernStateSouth & WYVERN_HORDE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_A, uint32(bool(m_WyvernStateSouth & WYVERN_ALLIANCE)));
            break;
        case NA_ROOST_N:
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_NEU_H, uint32(bool(m_WyvernStateNorth & WYVERN_NEU_HORDE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_NEU_A, uint32(bool(m_WyvernStateNorth & WYVERN_NEU_ALLIANCE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_H, uint32(bool(m_WyvernStateNorth & WYVERN_HORDE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_A, uint32(bool(m_WyvernStateNorth & WYVERN_ALLIANCE)));
            break;
        case NA_ROOST_W:
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_WEST_NEU_H, uint32(bool(m_WyvernStateWest & WYVERN_NEU_HORDE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_WEST_NEU_A, uint32(bool(m_WyvernStateWest & WYVERN_NEU_ALLIANCE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_WEST_H, uint32(bool(m_WyvernStateWest & WYVERN_HORDE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_WEST_A, uint32(bool(m_WyvernStateWest & WYVERN_ALLIANCE)));
            break;
        case NA_ROOST_E:
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_EAST_NEU_H, uint32(bool(m_WyvernStateEast & WYVERN_NEU_HORDE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_EAST_NEU_A, uint32(bool(m_WyvernStateEast & WYVERN_NEU_ALLIANCE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_EAST_H, uint32(bool(m_WyvernStateEast & WYVERN_HORDE)));
            _pvp->SendUpdateWorldState(NA_MAP_WYVERN_EAST_A, uint32(bool(m_WyvernStateEast & WYVERN_ALLIANCE)));
            break;
    }
}
References OPvPCapturePoint::_pvp, m_WyvernStateEast, m_WyvernStateNorth, m_WyvernStateSouth, m_WyvernStateWest, NA_MAP_WYVERN_EAST_A, NA_MAP_WYVERN_EAST_H, NA_MAP_WYVERN_EAST_NEU_A, NA_MAP_WYVERN_EAST_NEU_H, NA_MAP_WYVERN_NORTH_A, NA_MAP_WYVERN_NORTH_H, NA_MAP_WYVERN_NORTH_NEU_A, NA_MAP_WYVERN_NORTH_NEU_H, NA_MAP_WYVERN_SOUTH_A, NA_MAP_WYVERN_SOUTH_H, NA_MAP_WYVERN_SOUTH_NEU_A, NA_MAP_WYVERN_SOUTH_NEU_H, NA_MAP_WYVERN_WEST_A, NA_MAP_WYVERN_WEST_H, NA_MAP_WYVERN_WEST_NEU_A, NA_MAP_WYVERN_WEST_NEU_H, NA_ROOST_E, NA_ROOST_N, NA_ROOST_S, NA_ROOST_W, OutdoorPvP::SendUpdateWorldState(), WYVERN_ALLIANCE, WYVERN_HORDE, WYVERN_NEU_ALLIANCE, and WYVERN_NEU_HORDE.
Referenced by FactionTakeOver(), and HandleOpenGo().
Member Data Documentation
m_canRecap
bool OPvPCapturePointNA::m_canRecap private
Referenced by ChangeState(), FactionTakeOver(), and Update().
m_capturable
bool OPvPCapturePointNA::m_capturable private
Referenced by FactionTakeOver(), and Update().
m_ControllingFaction
TeamId OPvPCapturePointNA::m_ControllingFaction private
Referenced by FactionTakeOver(), FillInitialWorldStates(), GetControllingFaction(), and HandleOpenGo().
m_GuardCheckTimer
uint32 OPvPCapturePointNA::m_GuardCheckTimer private
Referenced by Update().
m_GuardsAlive
uint32 OPvPCapturePointNA::m_GuardsAlive private
Referenced by FactionTakeOver(), FillInitialWorldStates(), and Update().
m_HalaaState
uint32 OPvPCapturePointNA::m_HalaaState private
Referenced by ChangeState(), FillInitialWorldStates(), and UpdateHalaaWorldState().
m_RespawnTimer
uint32 OPvPCapturePointNA::m_RespawnTimer private
Referenced by Update().
m_WyvernStateEast
uint32 OPvPCapturePointNA::m_WyvernStateEast private
Referenced by FactionTakeOver(), FillInitialWorldStates(), HandleOpenGo(), and UpdateWyvernRoostWorldState().
m_WyvernStateNorth
uint32 OPvPCapturePointNA::m_WyvernStateNorth private
Referenced by FactionTakeOver(), FillInitialWorldStates(), HandleOpenGo(), and UpdateWyvernRoostWorldState().
m_WyvernStateSouth
uint32 OPvPCapturePointNA::m_WyvernStateSouth private
Referenced by FactionTakeOver(), FillInitialWorldStates(), HandleOpenGo(), and UpdateWyvernRoostWorldState().
m_WyvernStateWest
uint32 OPvPCapturePointNA::m_WyvernStateWest private
Referenced by FactionTakeOver(), FillInitialWorldStates(), HandleOpenGo(), and UpdateWyvernRoostWorldState().