AzerothCore: instance_the_black_morass::instance_the_black_morass_InstanceMapScript Struct Reference
instance_the_black_morass::instance_the_black_morass_InstanceMapScript Struct Reference
Public Member Functions
instance_the_black_morass_InstanceMapScript (Map *map)
void CleanupInstance ()
bool SetBossState (uint32 type, EncounterState state) override
void OnPlayerEnter (Player *player) override
void ScheduleNextPortal (Milliseconds time, Position lastPosition)
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
void Update (uint32 diff) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
std::list< Position > _availableRiftPositions
GuidSet _encounterNPCs
uint8 _currentRift
int8 _shieldPercent
bool _noBossSpawnDelay
EventStatus _eventStatus
TaskScheduler _scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_the_black_morass_InstanceMapScript()
instance_the_black_morass::instance_the_black_morass_InstanceMapScript::instance_the_black_morass_InstanceMapScript (Map * map) inline
                                                              : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(EncounterCount);
            LoadObjectData(creatureData, nullptr);
            _currentRift = 0;
            _shieldPercent = 100;
            _encounterNPCs.clear();
            _noBossSpawnDelay = true; // Delay after bosses
            _eventStatus = EVENT_PREPARE;
        }
References _currentRift, _encounterNPCs, _eventStatus, _noBossSpawnDelay, _shieldPercent, creatureData, DataHeader, EncounterCount, EVENT_PREPARE, InstanceScript::LoadObjectData(), InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
CleanupInstance()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::CleanupInstance () inline
        {
            _currentRift = 0;
            _shieldPercent = 100;
            _availableRiftPositions.clear();
            _scheduler.CancelAll();
            for (Position const& pos : PortalLocation)
            {
                _availableRiftPositions.push_back(pos);
            }
            // prevent getting stuck if event fails during boss break
            _noBossSpawnDelay = true;
            instance->LoadGrid(-2023.0f, 7121.0f);
            if (Creature* medivh = GetCreature(DATA_MEDIVH))
            {
                medivh->Respawn();
            }
            for (ObjectGuid const& guid : _encounterNPCs)
            {
                if (guid.GetEntry() == NPC_DP_BEAM_STALKER)
                {
                    if (Creature* creature = instance->GetCreature(guid))
                    {
                            creature->Respawn();
                    }
                    break;
                }
            }
        }
References _availableRiftPositions, _currentRift, _encounterNPCs, _noBossSpawnDelay, _scheduler, _shieldPercent, TaskScheduler::CancelAll(), DATA_MEDIVH, Map::GetCreature(), InstanceScript::GetCreature(), InstanceScript::instance, Map::LoadGrid(), NPC_DP_BEAM_STALKER, and PortalLocation.
Referenced by OnPlayerEnter().
GetData()
uint32 instance_the_black_morass::instance_the_black_morass_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_SHIELD_PERCENT:
                    return _shieldPercent;
                case DATA_RIFT_NUMBER:
                    return _currentRift;
            }
            return 0;
        }
References DATA_RIFT_NUMBER, and DATA_SHIELD_PERCENT.
OnCreatureCreate()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_TIME_RIFT:
                case NPC_CHRONO_LORD_DEJA:
                case NPC_INFINITE_CHRONO_LORD:
                case NPC_TEMPORUS:
                case NPC_INFINITE_TIMEREAVER:
                case NPC_AEONUS:
                case NPC_RIFT_KEEPER_WARLOCK:
                case NPC_RIFT_KEEPER_MAGE:
                case NPC_RIFT_LORD:
                case NPC_RIFT_LORD_2:
                case NPC_INFINITE_ASSASSIN:
                case NPC_INFINITE_ASSASSIN_2:
                case NPC_INFINITE_WHELP:
                case NPC_INFINITE_CHRONOMANCER:
                case NPC_INFINITE_CHRONOMANCER_2:
                case NPC_INFINITE_EXECUTIONER:
                case NPC_INFINITE_EXECUTIONER_2:
                case NPC_INFINITE_VANQUISHER:
                case NPC_INFINITE_VANQUISHER_2:
                case NPC_DP_BEAM_STALKER:
                case NPC_DP_EMITTER_STALKER:
                    _encounterNPCs.insert(creature->GetGUID());
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References Object::GetEntry(), Object::GetGUID(), NPC_AEONUS, NPC_CHRONO_LORD_DEJA, NPC_DP_BEAM_STALKER, NPC_DP_EMITTER_STALKER, NPC_INFINITE_ASSASSIN, NPC_INFINITE_ASSASSIN_2, NPC_INFINITE_CHRONO_LORD, NPC_INFINITE_CHRONOMANCER, NPC_INFINITE_CHRONOMANCER_2, NPC_INFINITE_EXECUTIONER, NPC_INFINITE_EXECUTIONER_2, NPC_INFINITE_TIMEREAVER, NPC_INFINITE_VANQUISHER, NPC_INFINITE_VANQUISHER_2, NPC_INFINITE_WHELP, NPC_RIFT_KEEPER_MAGE, NPC_RIFT_KEEPER_WARLOCK, NPC_RIFT_LORD, NPC_RIFT_LORD_2, NPC_TEMPORUS, NPC_TIME_RIFT, and InstanceScript::OnCreatureCreate().
OnCreatureRemove()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnCreatureRemove (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_TIME_RIFT:
                    if (_currentRift < 18 && _noBossSpawnDelay && _eventStatus == EVENT_IN_PROGRESS)
                    {
                        if (_availableRiftPositions.size() < 3)
{
                            ScheduleNextPortal((_currentRift >= 13 ? 2min : 90s), creature->GetHomePosition());
                        }
                        else
{
                            ScheduleNextPortal(1s, creature->GetHomePosition());
                        }
                    }
                    _availableRiftPositions.push_back(creature->GetHomePosition());
                    [[fallthrough]];
                case NPC_CHRONO_LORD_DEJA:
                case NPC_INFINITE_CHRONO_LORD:
                case NPC_TEMPORUS:
                case NPC_INFINITE_TIMEREAVER:
                case NPC_AEONUS:
                case NPC_RIFT_KEEPER_WARLOCK:
                case NPC_RIFT_KEEPER_MAGE:
                case NPC_RIFT_LORD:
                case NPC_RIFT_LORD_2:
                case NPC_INFINITE_ASSASSIN:
                case NPC_INFINITE_ASSASSIN_2:
                case NPC_INFINITE_WHELP:
                case NPC_INFINITE_CHRONOMANCER:
                case NPC_INFINITE_CHRONOMANCER_2:
                case NPC_INFINITE_EXECUTIONER:
                case NPC_INFINITE_EXECUTIONER_2:
                case NPC_INFINITE_VANQUISHER:
                case NPC_INFINITE_VANQUISHER_2:
                case NPC_DP_EMITTER_STALKER:
                    _encounterNPCs.erase(creature->GetGUID());
                    break;
            }
            InstanceScript::OnCreatureRemove(creature);
        }
References EVENT_IN_PROGRESS, Object::GetEntry(), Object::GetGUID(), Creature::GetHomePosition(), NPC_AEONUS, NPC_CHRONO_LORD_DEJA, NPC_DP_EMITTER_STALKER, NPC_INFINITE_ASSASSIN, NPC_INFINITE_ASSASSIN_2, NPC_INFINITE_CHRONO_LORD, NPC_INFINITE_CHRONOMANCER, NPC_INFINITE_CHRONOMANCER_2, NPC_INFINITE_EXECUTIONER, NPC_INFINITE_EXECUTIONER_2, NPC_INFINITE_TIMEREAVER, NPC_INFINITE_VANQUISHER, NPC_INFINITE_VANQUISHER_2, NPC_INFINITE_WHELP, NPC_RIFT_KEEPER_MAGE, NPC_RIFT_KEEPER_WARLOCK, NPC_RIFT_LORD, NPC_RIFT_LORD_2, NPC_TEMPORUS, NPC_TIME_RIFT, and InstanceScript::OnCreatureRemove().
OnPlayerEnter()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
        {
            if (instance->GetPlayersCountExceptGMs() <= 1 && GetBossState(DATA_AEONUS) != DONE && _eventStatus != EVENT_IN_PROGRESS)
            {
                CleanupInstance();
            }
            player->SendUpdateWorldState(WORLD_STATE_BM, _eventStatus);
            player->SendUpdateWorldState(WORLD_STATE_BM_SHIELD, _shieldPercent);
            player->SendUpdateWorldState(WORLD_STATE_BM_RIFT, _currentRift);
        }
References _currentRift, _eventStatus, _shieldPercent, CleanupInstance(), DATA_AEONUS, DONE, EVENT_IN_PROGRESS, InstanceScript::GetBossState(), Map::GetPlayersCountExceptGMs(), InstanceScript::instance, Player::SendUpdateWorldState(), WORLD_STATE_BM, WORLD_STATE_BM_RIFT, and WORLD_STATE_BM_SHIELD.
ScheduleNextPortal()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::ScheduleNextPortal (Milliseconds time, Position lastPosition) inline
        {
            // only one rift can be scheduled at any time
            _scheduler.CancelGroup(CONTEXT_GROUP_RIFTS);
            _scheduler.Schedule(time, [this, lastPosition](TaskContext context)
            {
                if (GetCreature(DATA_MEDIVH))
                {
                    // Spawning prevented: after-boss-delay or event failed/not started or last portal spawned
                    if (!_noBossSpawnDelay || _eventStatus == EVENT_PREPARE || _currentRift >= 18)
                    {
                        return;
                    }
                    Position spawnPos;
                    if (!_availableRiftPositions.empty())
                    {
                        if (_availableRiftPositions.size() > 1)
{
                            spawnPos = Acore::Containers::SelectRandomContainerElementIf(_availableRiftPositions, [&](Position pos) -> bool
{
                                return pos != lastPosition;
                            });
                        }
                        else
{
                            spawnPos = Acore::Containers::SelectRandomContainerElement(_availableRiftPositions);
                        }
                        _availableRiftPositions.remove(spawnPos);
                        DoUpdateWorldState(WORLD_STATE_BM_RIFT, ++_currentRift);
                        instance->SummonCreature(NPC_TIME_RIFT, spawnPos);
                        // queue next portal if group doesn't kill keepers fast enough
                        context.Repeat((_currentRift >= 13 ? 2min : 90s));
                    }
                    // if no rift positions are available, the next rift will be scheduled in OnCreatureRemove
                }
                context.SetGroup(CONTEXT_GROUP_RIFTS);
            });
        }
References _availableRiftPositions, _currentRift, _eventStatus, _noBossSpawnDelay, _scheduler, TaskScheduler::CancelGroup(), CONTEXT_GROUP_RIFTS, DATA_MEDIVH, InstanceScript::DoUpdateWorldState(), EVENT_PREPARE, InstanceScript::GetCreature(), InstanceScript::instance, NPC_TIME_RIFT, TaskContext::Repeat(), TaskScheduler::Schedule(), TaskContext::SetGroup(), Map::SummonCreature(), and WORLD_STATE_BM_RIFT.
Referenced by SetBossState().
SetBossState()
bool instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
            {
                return false;
            }
            if (state == DONE)
            {
                switch (type)
                {
                    case DATA_AEONUS:
                    {
                        if (Creature* medivh = GetCreature(DATA_MEDIVH))
{
                            medivh->AI()->DoAction(ACTION_OUTRO);
                        }
                        instance->DoForAllPlayers([&](Player* player)
{
                            if (player->GetQuestStatus(QUEST_OPENING_PORTAL) == QUEST_STATUS_INCOMPLETE)
{
                                player->AreaExploredOrEventHappens(QUEST_OPENING_PORTAL);
                            }
                            if (player->GetQuestStatus(QUEST_MASTER_TOUCH) == QUEST_STATUS_INCOMPLETE)
{
                                player->AreaExploredOrEventHappens(QUEST_MASTER_TOUCH);
                            }
                        });
                        for (ObjectGuid const& guid : _encounterNPCs)
{
                            if (Creature* creature = instance->GetCreature(guid))
{
                                switch (creature->GetEntry())
{
                                    case NPC_RIFT_KEEPER_WARLOCK:
                                    case NPC_RIFT_KEEPER_MAGE:
                                    case NPC_RIFT_LORD:
                                    case NPC_RIFT_LORD_2:
                                    case NPC_TIME_RIFT:
                                    case NPC_INFINITE_ASSASSIN:
                                    case NPC_INFINITE_ASSASSIN_2:
                                    case NPC_INFINITE_WHELP:
                                    case NPC_INFINITE_CHRONOMANCER:
                                    case NPC_INFINITE_CHRONOMANCER_2:
                                    case NPC_INFINITE_EXECUTIONER:
                                    case NPC_INFINITE_EXECUTIONER_2:
                                    case NPC_INFINITE_VANQUISHER:
                                    case NPC_INFINITE_VANQUISHER_2:
                                        creature->DespawnOrUnsummon(1);
                                        break;
                                    default:
                                        break;
                                }
                            }
                        }
                        break;
                    }
                    case DATA_CHRONO_LORD_DEJA:
                    case DATA_TEMPORUS:
                    {
                        _noBossSpawnDelay = false;
                        _scheduler.Schedule(2min + 30s, [this](TaskContext)
{
                            _noBossSpawnDelay = true;
                            ScheduleNextPortal(0s, Position(0.0f, 0.0f, 0.0f, 0.0f));
                        });
                        break;
                    }
                    default:
                        break;
                }
            }
            return true;
        }
References _encounterNPCs, _noBossSpawnDelay, _scheduler, ACTION_OUTRO, DATA_AEONUS, DATA_CHRONO_LORD_DEJA, DATA_MEDIVH, DATA_TEMPORUS, Map::DoForAllPlayers(), DONE, Map::GetCreature(), InstanceScript::GetCreature(), Player::GetQuestStatus(), InstanceScript::instance, NPC_INFINITE_ASSASSIN, NPC_INFINITE_ASSASSIN_2, NPC_INFINITE_CHRONOMANCER, NPC_INFINITE_CHRONOMANCER_2, NPC_INFINITE_EXECUTIONER, NPC_INFINITE_EXECUTIONER_2, NPC_INFINITE_VANQUISHER, NPC_INFINITE_VANQUISHER_2, NPC_INFINITE_WHELP, NPC_RIFT_KEEPER_MAGE, NPC_RIFT_KEEPER_WARLOCK, NPC_RIFT_LORD, NPC_RIFT_LORD_2, NPC_TIME_RIFT, QUEST_MASTER_TOUCH, QUEST_OPENING_PORTAL, QUEST_STATUS_INCOMPLETE, TaskScheduler::Schedule(), ScheduleNextPortal(), and InstanceScript::SetBossState().
SetData()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_MEDIVH:
                {
                    _eventStatus = EVENT_IN_PROGRESS;
                    DoUpdateWorldState(WORLD_STATE_BM, _eventStatus);
                    DoUpdateWorldState(WORLD_STATE_BM_SHIELD, _shieldPercent);
                    DoUpdateWorldState(WORLD_STATE_BM_RIFT, _currentRift);
                    ScheduleNextPortal(3s, Position(0.0f, 0.0f, 0.0f, 0.0f));
                    break;
                }
                case DATA_DAMAGE_SHIELD:
                {
                    if (_shieldPercent <= 0)
                    {
                        return;
                    }
                    _shieldPercent -= data;
                    if (_shieldPercent < 0)
                    {
                        _shieldPercent = 0;
                    }
                    DoUpdateWorldState(WORLD_STATE_BM_SHIELD, _shieldPercent);
                    if (!_shieldPercent)
                    {
                        _eventStatus = EVENT_PREPARE;
                        if (Creature* medivh = GetCreature(DATA_MEDIVH))
{
                            if (medivh->IsAlive() && medivh->IsAIEnabled)
{
                                medivh->SetImmuneToNPC(true);
                                medivh->AI()->Talk(SAY_MEDIVH_DEATH);
                                for (ObjectGuid const& guid : _encounterNPCs)
{
                                    if (Creature* creature = instance->GetCreature(guid))
{
                                        creature->InterruptNonMeleeSpells(true);
                                    }
                                }
                                // Step 1 - Medivh loses all auras.
                                _scheduler.Schedule(4s, [this](TaskContext)
{
                                    if (Creature* medivh = GetCreature(DATA_MEDIVH))
{
                                        medivh->RemoveAllAuras();
                                    }
                                    // Step 2 - Medivh dies and visual effect NPCs are despawned.
                                    _scheduler.Schedule(500ms, [this](TaskContext)
{
                                        if (Creature* medivh = GetCreature(DATA_MEDIVH))
{
                                            medivh->KillSelf(false);
                                            GuidSet encounterNPCSCopy = _encounterNPCs;
                                            for (ObjectGuid const& guid : encounterNPCSCopy)
{
                                                switch (guid.GetEntry())
{
                                                    case NPC_TIME_RIFT:
                                                    case NPC_DP_EMITTER_STALKER:
                                                    case NPC_DP_CRYSTAL_STALKER:
                                                    case NPC_DP_BEAM_STALKER:
                                                        if (Creature* creature = instance->GetCreature(guid))
{
                                                            creature->DespawnOrUnsummon();
                                                        }
                                                        break;
                                                    default:
                                                        break;
                                                }
                                            }
                                        }
                                        // Step 3 - All summoned creatures despawn
                                        _scheduler.Schedule(2s, [this](TaskContext)
{
                                            GuidSet encounterNPCSCopy = _encounterNPCs;
                                            for (ObjectGuid const& guid : encounterNPCSCopy)
{
                                                // Don't despawn permanent visual effect NPC twice or it won't respawn correctly
                                                if (guid.GetEntry() == NPC_DP_BEAM_STALKER)
{
                                                    continue;
                                                }
                                                if (Creature* creature = instance->GetCreature(guid))
{
                                                    creature->CastSpell(creature, SPELL_TELEPORT_VISUAL, true);
                                                    creature->DespawnOrUnsummon(1200ms, 0s);
                                                }
                                            }
                                            _scheduler.CancelAll();
                                            // Step 4 - Schedule instance cleanup without player interaction
                                            _scheduler.Schedule(300s, [this](TaskContext)
{
                                                CleanupInstance();
                                                DoUpdateWorldState(WORLD_STATE_BM, _eventStatus);
                                                DoUpdateWorldState(WORLD_STATE_BM_SHIELD, _shieldPercent);
                                                DoUpdateWorldState(WORLD_STATE_BM_RIFT, _currentRift);
                                            });
                                        });
                                    });
                                });
                            }
                        }
                    }
                    break;
                }
                default:
                    break;
            }
        }
References DATA_DAMAGE_SHIELD, DATA_MEDIVH, EVENT_IN_PROGRESS, EVENT_PREPARE, NPC_DP_BEAM_STALKER, SAY_MEDIVH_DEATH, WORLD_STATE_BM, WORLD_STATE_BM_RIFT, and WORLD_STATE_BM_SHIELD.
Update()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            _scheduler.Update(diff);
        }
Member Data Documentation
_availableRiftPositions
std::list<Position> instance_the_black_morass::instance_the_black_morass_InstanceMapScript::_availableRiftPositions protected
Referenced by CleanupInstance(), and ScheduleNextPortal().
_currentRift
uint8 instance_the_black_morass::instance_the_black_morass_InstanceMapScript::_currentRift protected
Referenced by CleanupInstance(), instance_the_black_morass_InstanceMapScript(), OnPlayerEnter(), and ScheduleNextPortal().
_encounterNPCs
GuidSet instance_the_black_morass::instance_the_black_morass_InstanceMapScript::_encounterNPCs protected
Referenced by CleanupInstance(), instance_the_black_morass_InstanceMapScript(), and SetBossState().
_eventStatus
EventStatus instance_the_black_morass::instance_the_black_morass_InstanceMapScript::_eventStatus protected
Referenced by instance_the_black_morass_InstanceMapScript(), OnPlayerEnter(), and ScheduleNextPortal().
_noBossSpawnDelay
bool instance_the_black_morass::instance_the_black_morass_InstanceMapScript::_noBossSpawnDelay protected
Referenced by CleanupInstance(), instance_the_black_morass_InstanceMapScript(), ScheduleNextPortal(), and SetBossState().
_scheduler
TaskScheduler instance_the_black_morass::instance_the_black_morass_InstanceMapScript::_scheduler protected
Referenced by CleanupInstance(), ScheduleNextPortal(), and SetBossState().
_shieldPercent
int8 instance_the_black_morass::instance_the_black_morass_InstanceMapScript::_shieldPercent protected
Referenced by CleanupInstance(), instance_the_black_morass_InstanceMapScript(), and OnPlayerEnter().