AzerothCore: WebTargetSelector Struct Reference
WebTargetSelector Struct Reference
Public Member Functions
WebTargetSelector (Unit *maexxna)
bool operator() (Unit const *target) const
Private Attributes
Unit const * _maexxna
Detailed Description
Constructor & Destructor Documentation
WebTargetSelector()
WebTargetSelector::WebTargetSelector (Unit * maexxna) inline
: _maexxna(maexxna) {}
Member Function Documentation
operator()()
bool WebTargetSelector::operator() (Unit const * target) const inline
    {
        if (!target->IsPlayer()) // never web nonplayers (pets, guardians, etc.)
            return false;
        if (_maexxna->GetVictim() == target) // never target tank
            return false;
        if (target->HasAura(SPELL_WEB_WRAP_STUN)) // never target targets that are already webbed
            return false;
        return true;
    }
References _maexxna, Unit::GetVictim(), Unit::HasAura(), Object::IsPlayer(), and SPELL_WEB_WRAP_STUN.
Member Data Documentation
_maexxna
Unit const* WebTargetSelector::_maexxna private
Referenced by operator()().