AzerothCore: instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript Struct Reference
instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript Struct Reference
Public Member Functions
instance_magisters_terrace_InstanceMapScript (Map *map)
void Initialize () override
bool IsEncounterInProgress () const override
uint32 GetData (uint32 identifier) const override
void SetData (uint32 identifier, uint32 data) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
ObjectGuid GetGuidData (uint32 identifier) const override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 Encounter [MAX_ENCOUNTER]
ObjectGuid VexallusDoorGUID
ObjectGuid SelinDoorGUID
ObjectGuid SelinEncounterDoorGUID
ObjectGuid DelrissaDoorGUID
ObjectGuid KaelDoorGUID
ObjectGuid EscapeOrbGUID
ObjectGuid DelrissaGUID
ObjectGuid KaelGUID
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_magisters_terrace_InstanceMapScript()
instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::instance_magisters_terrace_InstanceMapScript (Map * map) inline
                                                               : InstanceScript(map)
        {
            SetHeaders(DataHeader);
        }
References DataHeader, and InstanceScript::SetHeaders().
Member Function Documentation
GetData()
uint32 instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::GetData (uint32 identifier) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (identifier)
            {
                case DATA_SELIN_EVENT:
                case DATA_VEXALLUS_EVENT:
                case DATA_DELRISSA_EVENT:
                case DATA_KAELTHAS_EVENT:
                    return Encounter[identifier];
            }
            return 0;
        }
References DATA_DELRISSA_EVENT, DATA_KAELTHAS_EVENT, DATA_SELIN_EVENT, and DATA_VEXALLUS_EVENT.
Referenced by OnGameObjectCreate().
GetGuidData()
ObjectGuid instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::GetGuidData (uint32 identifier) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (identifier)
            {
                case NPC_DELRISSA:
                    return DelrissaGUID;
            }
            return ObjectGuid::Empty;
        }
References DelrissaGUID, ObjectGuid::Empty, and NPC_DELRISSA.
Initialize()
void instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            memset(&Encounter, 0, sizeof(Encounter));
        }
IsEncounterInProgress()
bool instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                if (Encounter[i] == IN_PROGRESS)
                    return true;
            return false;
        }
References IN_PROGRESS, and MAX_ENCOUNTER.
OnCreatureCreate()
void instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_DELRISSA:
                    DelrissaGUID = creature->GetGUID();
                    break;
                case NPC_KAEL_THAS:
                    KaelGUID = creature->GetGUID();
                    break;
                case NPC_PHOENIX:
                case NPC_PHOENIX_EGG:
                    if (Creature* kael = instance->GetCreature(KaelGUID))
                        kael->AI()->JustSummoned(creature);
                    break;
            }
        }
References DelrissaGUID, Map::GetCreature(), Object::GetEntry(), Object::GetGUID(), InstanceScript::instance, KaelGUID, NPC_DELRISSA, NPC_KAEL_THAS, NPC_PHOENIX, and NPC_PHOENIX_EGG.
OnGameObjectCreate()
void instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_SELIN_DOOR:
                    if (GetData(DATA_SELIN_EVENT) == DONE)
                        HandleGameObject(ObjectGuid::Empty, true, go);
                    SelinDoorGUID = go->GetGUID();
                    break;
                case GO_SELIN_ENCOUNTER_DOOR:
                    SelinEncounterDoorGUID = go->GetGUID();
                    break;
                case GO_VEXALLUS_DOOR:
                    if (GetData(DATA_VEXALLUS_EVENT) == DONE)
                        HandleGameObject(ObjectGuid::Empty, true, go);
                    VexallusDoorGUID = go->GetGUID();
                    break;
                case GO_DELRISSA_DOOR:
                    if (GetData(DATA_DELRISSA_EVENT) == DONE)
                        HandleGameObject(ObjectGuid::Empty, true, go);
                    DelrissaDoorGUID = go->GetGUID();
                    break;
                case GO_KAEL_DOOR:
                    KaelDoorGUID = go->GetGUID();
                    break;
                case GO_ESCAPE_ORB:
                    if (GetData(DATA_KAELTHAS_EVENT) == DONE)
                        go->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    EscapeOrbGUID = go->GetGUID();
                    break;
            }
        }
References DATA_DELRISSA_EVENT, DATA_KAELTHAS_EVENT, DATA_SELIN_EVENT, DATA_VEXALLUS_EVENT, DelrissaDoorGUID, DONE, ObjectGuid::Empty, EscapeOrbGUID, GetData(), Object::GetEntry(), Object::GetGUID(), GO_DELRISSA_DOOR, GO_ESCAPE_ORB, GO_FLAG_NOT_SELECTABLE, GO_KAEL_DOOR, GO_SELIN_DOOR, GO_SELIN_ENCOUNTER_DOOR, GO_VEXALLUS_DOOR, InstanceScript::HandleGameObject(), KaelDoorGUID, GameObject::RemoveGameObjectFlag(), SelinDoorGUID, SelinEncounterDoorGUID, and VexallusDoorGUID.
ReadSaveDataMore()
void instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> Encounter[1];
            data >> Encounter[2];
            data >> Encounter[3];
        }
SetData()
void instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::SetData (uint32 identifier, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (identifier)
            {
                case DATA_SELIN_EVENT:
                    HandleGameObject(SelinDoorGUID, data == DONE);
                    HandleGameObject(SelinEncounterDoorGUID, data != IN_PROGRESS);
                    Encounter[identifier] = data;
                    break;
                case DATA_VEXALLUS_EVENT:
                    if (data == DONE)
                        HandleGameObject(VexallusDoorGUID, true);
                    Encounter[identifier] = data;
                    break;
                case DATA_DELRISSA_EVENT:
                    if (data == DONE)
                        HandleGameObject(DelrissaDoorGUID, true);
                    Encounter[identifier] = data;
                    break;
                case DATA_KAELTHAS_EVENT:
                    HandleGameObject(KaelDoorGUID, data != IN_PROGRESS);
                    if (data == DONE)
                        if (GameObject* escapeOrb = instance->GetGameObject(EscapeOrbGUID))
                            escapeOrb->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    Encounter[identifier] = data;
                    break;
            }
            SaveToDB();
        }
References DATA_DELRISSA_EVENT, DATA_KAELTHAS_EVENT, DATA_SELIN_EVENT, DATA_VEXALLUS_EVENT, DelrissaDoorGUID, DONE, EscapeOrbGUID, Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, KaelDoorGUID, InstanceScript::SaveToDB(), SelinDoorGUID, SelinEncounterDoorGUID, and VexallusDoorGUID.
WriteSaveDataMore()
void instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << Encounter[0] << ' ' << Encounter[1] << ' ' << Encounter[2] << ' ' << Encounter[3];
        }
Member Data Documentation
DelrissaDoorGUID
ObjectGuid instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::DelrissaDoorGUID
Referenced by OnGameObjectCreate(), and SetData().
DelrissaGUID
ObjectGuid instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::DelrissaGUID
Referenced by GetGuidData(), and OnCreatureCreate().
Encounter
uint32 instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::Encounter[MAX_ENCOUNTER]
EscapeOrbGUID
ObjectGuid instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::EscapeOrbGUID
Referenced by OnGameObjectCreate(), and SetData().
KaelDoorGUID
ObjectGuid instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::KaelDoorGUID
Referenced by OnGameObjectCreate(), and SetData().
KaelGUID
ObjectGuid instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::KaelGUID
Referenced by OnCreatureCreate().
SelinDoorGUID
ObjectGuid instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::SelinDoorGUID
Referenced by OnGameObjectCreate(), and SetData().
SelinEncounterDoorGUID
ObjectGuid instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::SelinEncounterDoorGUID
Referenced by OnGameObjectCreate(), and SetData().
VexallusDoorGUID
ObjectGuid instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::VexallusDoorGUID
Referenced by OnGameObjectCreate(), and SetData().