AzerothCore: boss_sjonnir::boss_sjonnirAI Struct Reference
boss_sjonnir::boss_sjonnirAI Struct Reference
Public Member Functions
boss_sjonnirAI (Creature *c)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void DoAction (int32 param) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void ActivatePipe (uint8 side)
void SummonDwarfes (bool friendly)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
uint8 SummonPhase
uint8 SlugeCount
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_sjonnirAI()
boss_sjonnir::boss_sjonnirAI::boss_sjonnirAI (Creature * c) inline
                                    : ScriptedAI(c), summons(me)
        {
            pInstance = c->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
ActivatePipe()
void boss_sjonnir::boss_sjonnirAI::ActivatePipe (uint8 side) inline
        {
            if (pInstance)
                if (GameObject* pipe = me->GetMap()->GetGameObject(pInstance->GetGuidData(side == POS_GEN_RIGHT ? GO_RIGHT_PIPE : GO_LEFT_PIPE)))
                    pipe->SendCustomAnim(0);
        }
References Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_LEFT_PIPE, GO_RIGHT_PIPE, ScriptedAI::me, pInstance, and POS_GEN_RIGHT.
Referenced by SummonDwarfes(), and UpdateAI().
DoAction()
void boss_sjonnir::boss_sjonnirAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_SLUG_KILLED)
            {
                SlugeCount++;
                if (SlugeCount >= 5 && pInstance)
                    pInstance->SetData(DATA_SJONNIR_ACHIEVEMENT, true);
            }
        }
References ACTION_SLUG_KILLED, DATA_SJONNIR_ACHIEVEMENT, pInstance, ZoneScript::SetData(), and SlugeCount.
JustDied()
void boss_sjonnir::boss_sjonnirAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_DEATH);
            summons.DespawnAll();
            if (pInstance)
            {
                pInstance->SetData(BOSS_SJONNIR, DONE);
                if (GameObject* sd = me->GetMap()->GetGameObject(pInstance->GetGuidData(GO_SJONNIR_DOOR)))
                    sd->SetGoState(GO_STATE_ACTIVE);
                if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
                    brann->AI()->DoAction(ACTION_SJONNIR_DEAD);
            }
        }
References ACTION_SJONNIR_DEAD, BOSS_SJONNIR, SummonList::DespawnAll(), DONE, ObjectAccessor::GetCreature(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_SJONNIR_DOOR, GO_STATE_ACTIVE, ScriptedAI::me, NPC_BRANN, pInstance, SAY_DEATH, ZoneScript::SetData(), and summons.
JustEngagedWith()
void boss_sjonnir::boss_sjonnirAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            Talk(SAY_AGGRO);
            events.ScheduleEvent(EVENT_CHECK_HEALTH, 1s);
            events.ScheduleEvent(EVENT_SHIELD, 14s, 19s);
            events.ScheduleEvent(EVENT_CHAIN_LIGHTNING, 6s, 12s);
            events.ScheduleEvent(EVENT_STATIC_CHARGE, 24s);
            events.ScheduleEvent(EVENT_LIGHTNING_RING, 25s, 31s);
            events.ScheduleEvent(EVENT_SUMMON, 20s);
            events.ScheduleEvent(EVENT_SUMMON, 21s + 500ms);
            events.ScheduleEvent(EVENT_SUMMON_SPEACH, 20s);
            if (pInstance)
            {
                pInstance->SetData(BOSS_SJONNIR, IN_PROGRESS);
                if (GameObject* doors = me->GetMap()->GetGameObject(pInstance->GetGuidData(GO_SJONNIR_DOOR)))
                    doors->SetGoState(GO_STATE_READY);
                if (pInstance->GetData(BOSS_TRIBUNAL_OF_AGES) == DONE)
                    if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
                        brann->AI()->DoAction(ACTION_START_SJONNIR_FIGHT);
            }
        }
References ACTION_START_SJONNIR_FIGHT, BOSS_SJONNIR, BOSS_TRIBUNAL_OF_AGES, DONE, EVENT_CHAIN_LIGHTNING, EVENT_CHECK_HEALTH, EVENT_LIGHTNING_RING, EVENT_SHIELD, EVENT_STATIC_CHARGE, EVENT_SUMMON, EVENT_SUMMON_SPEACH, ObjectAccessor::GetCreature(), ZoneScript::GetData(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_SJONNIR_DOOR, GO_STATE_READY, IN_PROGRESS, ScriptedAI::me, NPC_BRANN, pInstance, SAY_AGGRO, and ZoneScript::SetData().
KilledUnit()
void boss_sjonnir::boss_sjonnirAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (urand(0, 1))
                return;
            Talk(SAY_SLAY);
        }
References SAY_SLAY, and urand().
Reset()
void boss_sjonnir::boss_sjonnirAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Reset();
            summons.DespawnAll();
            SlugeCount = 0;
            SummonPhase = PHASE_SUMMON_UNFRIENDLY_DWARFES;
            if (pInstance)
            {
                pInstance->SetData(BOSS_SJONNIR, NOT_STARTED);
                pInstance->SetData(DATA_SJONNIR_ACHIEVEMENT, false);
                me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                if (pInstance->GetData(BOSS_TRIBUNAL_OF_AGES) == DONE)
                {
                    me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    if (GameObject* console = me->GetMap()->GetGameObject( pInstance->GetGuidData(GO_SJONNIR_CONSOLE)))
                        console->SetGoState(GO_STATE_READY);
                    if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
                    {
                        brann->setDeathState(DeathState::JustDied);
                        brann->Respawn();
                        brann->AI()->DoAction(ACTION_SJONNIR_WIPE_START);
                    }
                }
            }
        }
References ACTION_SJONNIR_WIPE_START, BOSS_SJONNIR, BOSS_TRIBUNAL_OF_AGES, DATA_SJONNIR_ACHIEVEMENT, SummonList::DespawnAll(), DONE, ObjectAccessor::GetCreature(), ZoneScript::GetData(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_SJONNIR_CONSOLE, GO_STATE_READY, ScriptedAI::me, NOT_STARTED, NPC_BRANN, PHASE_SUMMON_UNFRIENDLY_DWARFES, pInstance, Unit::RemoveUnitFlag(), ZoneScript::SetData(), Unit::SetUnitFlag(), SlugeCount, SummonPhase, summons, and UNIT_FLAG_NOT_SELECTABLE.
SummonDwarfes()
void boss_sjonnir::boss_sjonnirAI::SummonDwarfes (bool friendly) inline
        {
            if (friendly)
            {
                for (int i = 0; i < 3; i++)
                {
                    uint8 Pos = urand(POS_GEN_RIGHT, POS_GEN_LEFT);
                    if (Creature* dwarf = me->SummonCreature(NPC_DWARFES_FRIENDLY, RoomPosition[Pos].GetPositionX(), RoomPosition[Pos].GetPositionY(), RoomPosition[Pos].GetPositionZ(), 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000))
                    {
                        if (Player* plr = SelectTargetFromPlayerList(100.0f))
                            dwarf->SetFaction(plr->GetFaction());
                        ActivatePipe(Pos);
                        dwarf->AI()->AttackStart(me);
                        summons.Summon(dwarf);
                    }
                }
            }
            else
            {
                for (int i = 0; i < 2; i++)
                {
                    uint8 Pos = urand(POS_GEN_RIGHT, POS_GEN_LEFT);
                    if (Creature* dwarf = me->SummonCreature(urand(0, 1) ? NPC_FORGED_IRON_TROGG : NPC_FORGED_IRON_DWARF, RoomPosition[Pos].GetPositionX(), RoomPosition[Pos].GetPositionY(), RoomPosition[Pos].GetPositionZ(), 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000))
                    {
                        ActivatePipe(Pos);
                        dwarf->SetInCombatWithZone();
                        summons.Summon(dwarf);
                    }
                }
            }
        }
References ActivatePipe(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, NPC_DWARFES_FRIENDLY, NPC_FORGED_IRON_DWARF, NPC_FORGED_IRON_TROGG, POS_GEN_LEFT, POS_GEN_RIGHT, RoomPosition, ScriptedAI::SelectTargetFromPlayerList(), SummonList::Summon(), WorldObject::SummonCreature(), summons, TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_sjonnir::boss_sjonnirAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_CHECK_HEALTH:
                    {
                        if (SummonPhase == PHASE_SUMMON_UNFRIENDLY_DWARFES && HealthBelowPct(50))
{
                            SummonPhase = PHASE_SUMMON_OOZE;
                            events.CancelEvent(EVENT_SUMMON);
                            events.ScheduleEvent(EVENT_SUMMON, 0ms);
                            events.ScheduleEvent(EVENT_SUMMON, 1500ms);
                            if (pInstance)
                                if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
{
                                    brann->AI()->Talk(SAY_BRANN_SPAWN_OOZE);
                                }
                        }
                        if (HealthBelowPct(20))
{
                            if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
{
                                brann->AI()->Talk(SAY_BRANN_SPAWN_EARTHEN);
                            }
                            SummonPhase = PHASE_SUMMON_FRIENDLY_DWARFES;
                            me->CastSpell(me, SPELL_FRENZY, false);
                            events.CancelEvent(EVENT_SUMMON);
                            events.ScheduleEvent(EVENT_SUMMON, 0ms);
                            break;
                        }
                        events.Repeat(1s);
                        break;
                    }
                case EVENT_SHIELD:
                    {
                        me->CastSpell(me, DUNGEON_MODE(SPELL_LIGHTNING_SHIELD, SPELL_LIGHTNING_SHIELD_H), false);
                        events.Repeat(14s, 19s);
                        break;
                    }
                case EVENT_CHAIN_LIGHTNING:
                    {
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 50.0f, true, 0))
                            me->CastSpell(target, DUNGEON_MODE(SPELL_CHAIN_LIGHTNING, SPELL_CHAIN_LIGHTNING_H), false);
                        events.Repeat(6s, 12s);
                        break;
                    }
                case EVENT_STATIC_CHARGE:
                    {
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 50.0f, true, 0))
                            me->CastSpell(target, DUNGEON_MODE(SPELL_STATIC_CHARGE, SPELL_STATIC_CHARGE_H), false);
                        events.Repeat(20s);
                        break;
                    }
                case EVENT_LIGHTNING_RING:
                    {
                        me->CastSpell(me, DUNGEON_MODE(SPELL_LIGHTNING_RING, SPELL_LIGHTNING_RING_H), false);
                        events.Repeat(25s, 31s);
                        events.DelayEvents(10s); // Channel duration
                        break;
                    }
                case EVENT_SUMMON_SPEACH:
                    {
                        if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
{
                            brann->AI()->Talk(SAY_BRANN_SPAWN_TROGG);
                        }
                        break;
                    }
                case EVENT_SUMMON:
                    {
                        switch (SummonPhase)
{
                            case PHASE_SUMMON_UNFRIENDLY_DWARFES:
{
                                    SummonDwarfes(false);
                                    events.Repeat(20s);
                                    break;
                                }
                            case PHASE_SUMMON_OOZE:
{
                                    for (uint8 i = POS_GEN_RIGHT; i <= POS_GEN_LEFT; i++)
{
                                        if (Creature* ooze = me->SummonCreature(NPC_OOZE, RoomPosition[i].GetPositionX(), RoomPosition[i].GetPositionY(), RoomPosition[i].GetPositionZ(), 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000))
{
                                            ActivatePipe(i);
                                            ooze->GetMotionMaster()->MovePoint(0, RoomPosition[POS_ROOM_CENTER].GetPositionX(), RoomPosition[POS_ROOM_CENTER].GetPositionY(), RoomPosition[POS_ROOM_CENTER].GetPositionZ());
                                            summons.Summon(ooze);
                                        }
                                    }
                                    events.Repeat(10s);
                                    break;
                                }
                            case PHASE_SUMMON_FRIENDLY_DWARFES:
{
                                    SummonDwarfes(true);
                                    break;
                                }
                        }
                        break;
                    }
            }
            DoMeleeAttackIfReady();
        }
References ActivatePipe(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DUNGEON_MODE(), EVENT_CHAIN_LIGHTNING, EVENT_CHECK_HEALTH, EVENT_LIGHTNING_RING, EVENT_SHIELD, EVENT_STATIC_CHARGE, EVENT_SUMMON, EVENT_SUMMON_SPEACH, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), ScriptedAI::me, NPC_BRANN, NPC_OOZE, PHASE_SUMMON_FRIENDLY_DWARFES, PHASE_SUMMON_OOZE, PHASE_SUMMON_UNFRIENDLY_DWARFES, pInstance, POS_GEN_LEFT, POS_GEN_RIGHT, POS_ROOM_CENTER, RoomPosition, SAY_BRANN_SPAWN_EARTHEN, SAY_BRANN_SPAWN_OOZE, SAY_BRANN_SPAWN_TROGG, UnitAI::SelectTarget(), SPELL_CHAIN_LIGHTNING, SPELL_CHAIN_LIGHTNING_H, SPELL_FRENZY, SPELL_LIGHTNING_RING, SPELL_LIGHTNING_RING_H, SPELL_LIGHTNING_SHIELD, SPELL_LIGHTNING_SHIELD_H, SPELL_STATIC_CHARGE, SPELL_STATIC_CHARGE_H, SummonList::Summon(), WorldObject::SummonCreature(), SummonDwarfes(), SummonPhase, summons, TEMPSUMMON_CORPSE_TIMED_DESPAWN, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_sjonnir::boss_sjonnirAI::events
pInstance
InstanceScript* boss_sjonnir::boss_sjonnirAI::pInstance
Referenced by ActivatePipe(), boss_sjonnirAI(), DoAction(), JustDied(), JustEngagedWith(), Reset(), and UpdateAI().
SlugeCount
uint8 boss_sjonnir::boss_sjonnirAI::SlugeCount
Referenced by DoAction(), and Reset().
SummonPhase
uint8 boss_sjonnir::boss_sjonnirAI::SummonPhase
Referenced by Reset(), and UpdateAI().
summons
SummonList boss_sjonnir::boss_sjonnirAI::summons
Referenced by JustDied(), Reset(), SummonDwarfes(), and UpdateAI().