AzerothCore: TicketMgr Class Reference
TicketMgr Class Reference
#include "TicketMgr.h"
Public Member Functions
void LoadTickets ()
void LoadSurveys ()
GmTicket * GetTicket (uint32 ticketId)
GmTicket * GetTicketByPlayer (ObjectGuid playerGuid)
GmTicket * GetOldestOpenTicket ()
void AddTicket (GmTicket *ticket)
void CloseTicket (uint32 ticketId, ObjectGuid source=ObjectGuid::Empty)
void ResolveAndCloseTicket (uint32 ticketId, ObjectGuid source)
void RemoveTicket (uint32 ticketId)
bool GetStatus () const
void SetStatus (bool status)
uint64 GetLastChange () const
void UpdateLastChange ()
uint32 GenerateTicketId ()
uint32 GetOpenTicketCount () const
uint32 GetNextSurveyID ()
void Initialize ()
void ResetTickets ()
void ShowList (ChatHandler &handler, bool onlineOnly) const
void ShowClosedList (ChatHandler &handler) const
void ShowEscalatedList (ChatHandler &handler) const
void SendTicket (WorldSession *session, GmTicket *ticket) const
Static Public Member Functions
static TicketMgr * instance ()
Protected Member Functions
void _RemoveTicket (uint32 ticketId, int64 source=-1, bool permanently=false)
Protected Attributes
GmTicketList _ticketList
bool _status
uint32 _lastTicketId
uint32 _lastSurveyId
uint32 _openTicketCount
uint64 _lastChange
Private Member Functions
TicketMgr ()
~TicketMgr ()
Detailed Description
Constructor & Destructor Documentation
TicketMgr()
TicketMgr::TicketMgr () private
: _status(true), _lastTicketId(0), _lastSurveyId(0), _openTicketCount(0), _lastChange(GameTime::GetGameTime().count()) { }
~TicketMgr()
TicketMgr::~TicketMgr () private
{
    for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
        delete itr->second;
}
References _ticketList.
Member Function Documentation
_RemoveTicket()
void TicketMgr::_RemoveTicket (uint32 ticketId, int64 source = -1, bool permanently = false) protected
AddTicket()
void TicketMgr::AddTicket (GmTicket * ticket)
{
    _ticketList[ticket->GetId()] = ticket;
    if (!ticket->IsClosed())
        ++_openTicketCount;
    CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
    ticket->SaveToDB(trans);
}
References _openTicketCount, _ticketList, GmTicket::GetId(), GmTicket::IsClosed(), and GmTicket::SaveToDB().
CloseTicket()
void TicketMgr::CloseTicket (uint32 ticketId, ObjectGuid source = ObjectGuid::Empty)
{
    if (GmTicket* ticket = GetTicket(ticketId))
    {
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        ticket->SetClosedBy(source);
        if (source)
            --_openTicketCount;
        ticket->SaveToDB(trans);
    }
}
References _openTicketCount, and GetTicket().
GenerateTicketId()
uint32 TicketMgr::GenerateTicketId () inline
{ return ++_lastTicketId; }
References _lastTicketId.
GetLastChange()
uint64 TicketMgr::GetLastChange () const inline
{ return _lastChange; }
References _lastChange.
GetNextSurveyID()
uint32 TicketMgr::GetNextSurveyID () inline
{ return ++_lastSurveyId; }
References _lastSurveyId.
GetOldestOpenTicket()
GmTicket * TicketMgr::GetOldestOpenTicket () inline
    {
        for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
            if (itr->second && !itr->second->IsClosed() && !itr->second->IsCompleted())
                return itr->second;
        return nullptr;
    }
References _ticketList.
GetOpenTicketCount()
uint32 TicketMgr::GetOpenTicketCount () const inline
{ return _openTicketCount; }
References _openTicketCount.
GetStatus()
bool TicketMgr::GetStatus () const inline
{ return _status; }
References _status.
GetTicket()
GmTicket * TicketMgr::GetTicket (uint32 ticketId) inline
    {
        GmTicketList::iterator itr = _ticketList.find(ticketId);
        if (itr != _ticketList.end())
            return itr->second;
        return nullptr;
    }
References _ticketList.
Referenced by CloseTicket(), RemoveTicket(), and ResolveAndCloseTicket().
GetTicketByPlayer()
GmTicket * TicketMgr::GetTicketByPlayer (ObjectGuid playerGuid) inline
    {
        for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
            if (itr->second && itr->second->IsFromPlayer(playerGuid) && !itr->second->IsClosed())
                return itr->second;
        return nullptr;
    }
References _ticketList.
Initialize()
void TicketMgr::Initialize ()
{ SetStatus(sWorld->getBoolConfig(CONFIG_ALLOW_TICKETS)); }
References CONFIG_ALLOW_TICKETS, SetStatus(), and sWorld.
instance()
TicketMgr * TicketMgr::instance () static
{
    static TicketMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadSurveys()
void TicketMgr::LoadSurveys ()
{
    // we don't actually load anything into memory here as there's no reason to
    _lastSurveyId = 0;
    uint32 oldMSTime = getMSTime();
    if (QueryResult result = CharacterDatabase.Query("SELECT MAX(surveyId) FROM gm_survey"))
        _lastSurveyId = (*result)[0].Get<uint32>();
    LOG_INFO("server.loading", ">> Loaded GM Survey count from database in {} ms", GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References _lastSurveyId, CharacterDatabase, getMSTime(), GetMSTimeDiffToNow(), and LOG_INFO.
LoadTickets()
void TicketMgr::LoadTickets ()
{
    uint32 oldMSTime = getMSTime();
    for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
        delete itr->second;
    _ticketList.clear();
    _lastTicketId = 0;
    _openTicketCount = 0;
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_GM_TICKETS);
    PreparedQueryResult result = CharacterDatabase.Query(stmt);
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 GM tickets. DB table `gm_ticket` is empty!");
        return;
    }
    uint32 count = 0;
    do
    {
        Field* fields = result->Fetch();
        GmTicket* ticket = new GmTicket();
        if (!ticket->LoadFromDB(fields))
        {
            delete ticket;
            continue;
        }
        if (!ticket->IsClosed())
            ++_openTicketCount;
        // Update max ticket id if necessary
        uint32 id = ticket->GetId();
        if (_lastTicketId < id)
            _lastTicketId = id;
        _ticketList[id] = ticket;
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} GM tickets in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References _lastTicketId, _openTicketCount, _ticketList, CHAR_SEL_GM_TICKETS, CharacterDatabase, GmTicket::GetId(), getMSTime(), GetMSTimeDiffToNow(), GmTicket::IsClosed(), GmTicket::LoadFromDB(), LOG_INFO, and LOG_WARN.
RemoveTicket()
void TicketMgr::RemoveTicket (uint32 ticketId)
{
    if (GmTicket* ticket = GetTicket(ticketId))
    {
        ticket->DeleteFromDB();
        _ticketList.erase(ticketId);
        delete ticket;
    }
}
References _ticketList, and GetTicket().
ResetTickets()
void TicketMgr::ResetTickets ()
{
    for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end();)
    {
        if (itr->second->IsClosed())
        {
            uint32 ticketId = itr->second->GetId();
            ++itr;
            sTicketMgr->RemoveTicket(ticketId);
        }
        else
            ++itr;
    }
    _lastTicketId = 0;
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_ALL_GM_TICKETS);
    CharacterDatabase.Execute(stmt);
}
References _lastTicketId, _ticketList, CHAR_DEL_ALL_GM_TICKETS, CharacterDatabase, and sTicketMgr.
ResolveAndCloseTicket()
void TicketMgr::ResolveAndCloseTicket (uint32 ticketId, ObjectGuid source)
{
    if (GmTicket* ticket = GetTicket(ticketId))
    {
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        ticket->SetClosedBy(source);
        ticket->SetResolvedBy(source);
        if (source)
            --_openTicketCount;
        ticket->SaveToDB(trans);
    }
}
References _openTicketCount, and GetTicket().
SendTicket()
void TicketMgr::SendTicket (WorldSession * session, GmTicket * ticket) const
{
    WorldPacket data(SMSG_GMTICKET_GETTICKET, (ticket ? (4 + 4 + 1 + 4 + 4 + 4 + 1 + 1) : 4));
    if (ticket)
        ticket->WritePacket(data);
    else
        data << uint32(GMTICKET_STATUS_DEFAULT);
    session->SendPacket(&data);
}
References GMTICKET_STATUS_DEFAULT, WorldSession::SendPacket(), SMSG_GMTICKET_GETTICKET, and GmTicket::WritePacket().
SetStatus()
void TicketMgr::SetStatus (bool status) inline
{ _status = status; }
References _status.
Referenced by Initialize().
ShowClosedList()
void TicketMgr::ShowClosedList (ChatHandler & handler) const
{
    handler.SendSysMessage(LANG_COMMAND_TICKETSHOWCLOSEDLIST);
    for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
        if (itr->second->IsClosed())
            handler.SendSysMessage(itr->second->FormatMessageString(handler).c_str());
}
References _ticketList, LANG_COMMAND_TICKETSHOWCLOSEDLIST, and ChatHandler::SendSysMessage().
ShowEscalatedList()
void TicketMgr::ShowEscalatedList (ChatHandler & handler) const
{
    handler.SendSysMessage(LANG_COMMAND_TICKETSHOWESCALATEDLIST);
    for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
        if (!itr->second->IsClosed() && itr->second->GetEscalatedStatus() == TICKET_IN_ESCALATION_QUEUE)
            handler.SendSysMessage(itr->second->FormatMessageString(handler).c_str());
}
References _ticketList, LANG_COMMAND_TICKETSHOWESCALATEDLIST, ChatHandler::SendSysMessage(), and TICKET_IN_ESCALATION_QUEUE.
ShowList()
void TicketMgr::ShowList (ChatHandler & handler, bool onlineOnly) const
{
    handler.SendSysMessage(onlineOnly ? LANG_COMMAND_TICKETSHOWONLINELIST : LANG_COMMAND_TICKETSHOWLIST);
    for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
        if (!itr->second->IsClosed() && !itr->second->IsCompleted())
            if (!onlineOnly || itr->second->GetPlayer())
                handler.SendSysMessage(itr->second->FormatMessageString(handler).c_str());
}
References _ticketList, LANG_COMMAND_TICKETSHOWLIST, LANG_COMMAND_TICKETSHOWONLINELIST, and ChatHandler::SendSysMessage().
UpdateLastChange()
void TicketMgr::UpdateLastChange ()
{
    _lastChange = GameTime::GetGameTime().count();
}
References _lastChange, and GameTime::GetGameTime().
Member Data Documentation
_lastChange
uint64 TicketMgr::_lastChange protected
Referenced by GetLastChange(), and UpdateLastChange().
_lastSurveyId
uint32 TicketMgr::_lastSurveyId protected
Referenced by GetNextSurveyID(), and LoadSurveys().
_lastTicketId
uint32 TicketMgr::_lastTicketId protected
Referenced by GenerateTicketId(), LoadTickets(), and ResetTickets().
_openTicketCount
uint32 TicketMgr::_openTicketCount protected
Referenced by AddTicket(), CloseTicket(), GetOpenTicketCount(), LoadTickets(), and ResolveAndCloseTicket().
_status
bool TicketMgr::_status protected
Referenced by GetStatus(), and SetStatus().
_ticketList
GmTicketList TicketMgr::_ticketList protected
Referenced by AddTicket(), GetOldestOpenTicket(), GetTicket(), GetTicketByPlayer(), LoadTickets(), RemoveTicket(), ResetTickets(), ShowClosedList(), ShowEscalatedList(), ShowList(), and ~TicketMgr().