var namespace_world_packets =
[
    [ "Bank", "d2/df6/namespace_world_packets_1_1_bank.html", "d2/df6/namespace_world_packets_1_1_bank" ],
    [ "Character", "da/d58/namespace_world_packets_1_1_character.html", "da/d58/namespace_world_packets_1_1_character" ],
    [ "Chat", "dd/d8e/namespace_world_packets_1_1_chat.html", "dd/d8e/namespace_world_packets_1_1_chat" ],
    [ "Combat", "d6/dad/namespace_world_packets_1_1_combat.html", "d6/dad/namespace_world_packets_1_1_combat" ],
    [ "CombatLog", "da/d48/namespace_world_packets_1_1_combat_log.html", "da/d48/namespace_world_packets_1_1_combat_log" ],
    [ "Guild", "da/d28/namespace_world_packets_1_1_guild.html", "da/d28/namespace_world_packets_1_1_guild" ],
    [ "LFG", "d5/db1/namespace_world_packets_1_1_l_f_g.html", "d5/db1/namespace_world_packets_1_1_l_f_g" ],
    [ "Misc", "d3/d59/namespace_world_packets_1_1_misc.html", "d3/d59/namespace_world_packets_1_1_misc" ],
    [ "Pet", "db/dd3/namespace_world_packets_1_1_pet.html", "db/dd3/namespace_world_packets_1_1_pet" ],
    [ "Strings", "d2/d8f/namespace_world_packets_1_1_strings.html", "d2/d8f/namespace_world_packets_1_1_strings" ],
    [ "Totem", "d9/d48/namespace_world_packets_1_1_totem.html", "d9/d48/namespace_world_packets_1_1_totem" ],
    [ "WorldState", "d7/d1d/namespace_world_packets_1_1_world_state.html", "d7/d1d/namespace_world_packets_1_1_world_state" ],
    [ "Array", "da/da9/class_world_packets_1_1_array.html", "da/da9/class_world_packets_1_1_array" ],
    [ "ClientPacket", "d2/d9f/class_world_packets_1_1_client_packet.html", "d2/d9f/class_world_packets_1_1_client_packet" ],
    [ "CompactArray", "df/d48/class_world_packets_1_1_compact_array.html", "df/d48/class_world_packets_1_1_compact_array" ],
    [ "IllegalHyperlinkException", "db/d74/class_world_packets_1_1_illegal_hyperlink_exception.html", "db/d74/class_world_packets_1_1_illegal_hyperlink_exception" ],
    [ "InvalidHyperlinkException", "d2/d70/class_world_packets_1_1_invalid_hyperlink_exception.html", "d2/d70/class_world_packets_1_1_invalid_hyperlink_exception" ],
    [ "InvalidStringValueException", "df/df5/class_world_packets_1_1_invalid_string_value_exception.html", "df/df5/class_world_packets_1_1_invalid_string_value_exception" ],
    [ "InvalidUtf8ValueException", "d3/d2d/class_world_packets_1_1_invalid_utf8_value_exception.html", "d3/d2d/class_world_packets_1_1_invalid_utf8_value_exception" ],
    [ "Packet", "d7/d4e/class_world_packets_1_1_packet.html", "d7/d4e/class_world_packets_1_1_packet" ],
    [ "PacketArrayMaxCapacityException", "dc/d25/class_world_packets_1_1_packet_array_max_capacity_exception.html", "dc/d25/class_world_packets_1_1_packet_array_max_capacity_exception" ],
    [ "ServerPacket", "d6/d50/class_world_packets_1_1_server_packet.html", "d6/d50/class_world_packets_1_1_server_packet" ],
    [ "String", "de/d1a/class_world_packets_1_1_string.html", "de/d1a/class_world_packets_1_1_string" ],
    [ "CheckCompactArrayMaskOverflow", "d3/d87/namespace_world_packets.html#afb4909c8c4c13b14c8eceda2e9b4246d", null ],
    [ "operator<<", "d3/d87/namespace_world_packets.html#a82e35db0d6b671a4f4a581aac05828dc", null ],
    [ "operator>>", "d3/d87/namespace_world_packets.html#ab21e8e534a45a2a33d69cd11562a45c6", null ]
];