AzerothCore: at_cthun_stomach_exit Class Reference
at_cthun_stomach_exit Class Reference
Public Member Functions
at_cthun_stomach_exit ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
at_cthun_stomach_exit()
at_cthun_stomach_exit::at_cthun_stomach_exit () inline
: AreaTriggerScript("at_cthun_stomach_exit") { }
Member Function Documentation
OnTrigger()
bool at_cthun_stomach_exit::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (InstanceScript* instance = player->GetInstanceScript())
        {
            if (Creature* cthun = instance->GetCreature(DATA_CTHUN))
            {
                if (Creature* trigger = player->FindNearestCreature(NPC_TRIGGER, 15.0f))
                {
                    trigger->CastSpell(player, SPELL_EXIT_STOMACH, true);
                    if (Creature* exittrigger = player->FindNearestCreature(NPC_EXIT_TRIGGER, 15.0f))
                        exittrigger->CastSpell(player, SPELL_RUBBLE_ROCKY, true);
                }
                player->m_Events.AddEventAtOffset([player, cthun]()
                {
                    if (player->FindNearestCreature(NPC_EXIT_TRIGGER, 10.0f))
                    {
                        player->JumpTo(0.0f, 80.0f, false);
                        player->m_Events.AddEventAtOffset([player, cthun]()
{
                            if (cthun)
                                player->NearTeleportTo(cthun->GetPositionX(), cthun->GetPositionY(), cthun->GetPositionZ() + 10, float(rand32() % 6));
                            player->RemoveAurasDueToSpell(SPELL_DIGESTIVE_ACID);
                        }, 1s);
                    }
                    else
                    {
                        player->m_Events.KillAllEvents(false);
                    }
                }, 3s);
            }
        }
        return true;
    }
References EventProcessor::AddEventAtOffset(), DATA_CTHUN, WorldObject::FindNearestCreature(), WorldObject::GetInstanceScript(), EventProcessor::KillAllEvents(), Unit::m_Events, NPC_EXIT_TRIGGER, NPC_TRIGGER, SPELL_EXIT_STOMACH, and SPELL_RUBBLE_ROCKY.