AzerothCore: PlayerOrPetCheck Class Reference
PlayerOrPetCheck Class Reference
#include "ScriptedCreature.h"
Public Member Functions
bool operator() (WorldObject *unit) const
Detailed Description
Member Function Documentation
operator()()
bool PlayerOrPetCheck::operator() (WorldObject * unit) const inline
    {
        if (!unit->IsPlayer())
            if (!unit->ToUnit()->GetOwnerGUID().IsPlayer())
                return true;
        return false;
    }
References Unit::GetOwnerGUID(), Object::IsPlayer(), ObjectGuid::IsPlayer(), and Object::ToUnit().