AzerothCore: azerothcore-wotlk/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp File Reference
ScriptedCreature.cpp File Reference
#include "ScriptedCreature.h"
#include "Cell.h"
#include "CellImpl.h"
#include "GameTime.h"
#include "GridNotifiers.h"
#include "ObjectMgr.h"
#include "Spell.h"
#include "TemporarySummon.h"
#include "GridNotifiersImpl.h"
Classes
struct TSpellSummary
Enumerations
enum eNPCs {
NPC_BROODLORD = 12017 ,
NPC_JAN_ALAI = 23578 ,
NPC_SARTHARION = 28860 ,
NPC_FREYA = 32906 ,
NPC_INGVAR_UNDEAD = 23980 ,
NPC_ANNHYLDE = 24068 ,
NPC_THROW = 23997 ,
NPC_FROST_TOMB = 23965 ,
NPC_SKELETON = 23970
}
Functions
Creature * GetClosestCreatureWithEntry (WorldObject *source, uint32 entry, float maxSearchRange, bool alive)
GameObject * GetClosestGameObjectWithEntry (WorldObject *source, uint32 entry, float maxSearchRange, bool onlySpawned)
void GetCreatureListWithEntryInGrid (std::list< Creature * > &list, WorldObject *source, uint32 entry, float maxSearchRange)
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &list, WorldObject *source, uint32 entry, float maxSearchRange)
void GetDeadCreatureListInGrid (std::list< Creature * > &list, WorldObject *source, float maxSearchRange, bool alive)
Variables
struct TSpellSummary * SpellSummary
Enumeration Type Documentation
eNPCs
enum eNPCs
Enumerator
NPC_BROODLORD
NPC_JAN_ALAI
NPC_SARTHARION
NPC_FREYA
NPC_INGVAR_UNDEAD
NPC_ANNHYLDE
NPC_THROW
NPC_FROST_TOMB
NPC_SKELETON
{
    NPC_BROODLORD   = 12017,
    NPC_JAN_ALAI    = 23578,
    NPC_SARTHARION  = 28860,
    NPC_FREYA       = 32906,
};
Function Documentation
GetClosestCreatureWithEntry()
Creature * GetClosestCreatureWithEntry (WorldObject * source, uint32 entry, float maxSearchRange, bool alive)
{
    return source->FindNearestCreature(entry, maxSearchRange, alive);
}
References WorldObject::FindNearestCreature().
Referenced by npc_mrfloppy::npc_mrfloppyAI::EnterEvadeMode(), SmartScript::GetTargets(), spell_q12227_camera_shake::HandleScriptEffect(), npc_mrfloppy::npc_mrfloppyAI::JustEngagedWith(), npc_emily::npc_emilyAI::JustSummoned(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::JustSummoned(), Condition::Meets(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), npc_akama_shade::MovementInform(), go_elune_fire::OnGossipHello(), npc_varian_wrynn::OnGossipSelect(), npc_thrall_bfu::OnGossipSelect(), npc_emily::OnQuestAccept(), at_ancient_leaf::OnTrigger(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), Map::ScriptsProcess(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_a_special_surprise::npc_a_special_surpriseAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), npc_warmage_violetstand::UpdateAI(), npc_deaths_fel_cannon::npc_deaths_fel_cannonAI::UpdateAI(), and npc_emily::npc_emilyAI::WaypointReached().
GetClosestGameObjectWithEntry()
GameObject * GetClosestGameObjectWithEntry (WorldObject * source, uint32 entry, float maxSearchRange, bool onlySpawned)
{
    return source->FindNearestGameObject(entry, maxSearchRange, onlySpawned);
}
References WorldObject::FindNearestGameObject().
Referenced by npc_ranshalla::npc_ranshallaAI::DoChannelTorchSpell(), npc_firework::npc_fireworkAI::FindNearestLauncher(), SmartScript::GetTargets(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), Condition::Meets(), AreaTrigger_at_coilfang_waterfall::OnTrigger(), boss_ossirian::SummonedCreatureDespawn(), boss_grand_warlock_nethekurse::UpdateAI(), npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::UpdateAI(), npc_muglash::npc_muglashAI::WaypointReached(), and npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::WaypointReached().
GetCreatureListWithEntryInGrid()
void GetCreatureListWithEntryInGrid (std::list< Creature * > & list, WorldObject * source, uint32 entry, float maxSearchRange)
{
    source->GetCreatureListWithEntryInGrid(list, entry, maxSearchRange);
}
References WorldObject::GetCreatureListWithEntryInGrid().
Referenced by instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckLichKingAvailability(), boss_mandokir::boss_mandokirAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), boss_grand_warlock_nethekurse::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction(), instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomstore(), boss_arlokk::boss_arlokkAI::EnterEvadeMode(), npc_shattered_hand_scout::FireArrows(), npc_hyjal_ground_trash::GetNearbyFriendlyTrashCreature(), go_tadpole_cage::go_tadpole_cageAI::GossipHello(), spell_frostwarden_handler_order_whelp::HandleForcedCast(), spell_putricide_unstable_experiment::HandleScript(), boss_mandokir::boss_mandokirAI::JustDied(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::JustEngagedWith(), boss_arlokk::boss_arlokkAI::JustEngagedWith(), boss_rotface::boss_rotfaceAI::JustEngagedWith(), npc_sindragosa_trash::npc_sindragosa_trashAI::JustEngagedWith(), npc_shattered_hand_scout::MoveInLineOfSight(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_shattered_hand_scout::MovementInform(), go_veil_skith_cage::OnGossipHello(), at_icc_saurfang_portal::OnTrigger(), npc_harrison_jones::OpenMassiveGateAndCallGuards(), npc_dark_iron_attack_generator::PrepareEvent(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), npc_mograine::npc_mograineAI::PullCathedral(), boss_pandemonius::PullRoom(), RevivePlayer(), npc_corrupted_totem::SetAura(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::StoreTargets(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), npc_supervisor_raelen::UpdateAI(), npc_tiger_matriarch_credit::npc_tiger_matriarch_creditAI::UpdateAI(), npc_warmage_coldarra::npc_warmage_coldarraAI::UpdateAI(), and npc_warmage_violetstand::UpdateAI().
GetDeadCreatureListInGrid()
void GetDeadCreatureListInGrid (std::list< Creature * > & list, WorldObject * source, float maxSearchRange, bool alive)
{
    source->GetDeadCreatureListInGrid(list, maxSearchRange, alive);
}
References WorldObject::GetDeadCreatureListInGrid().
GetGameObjectListWithEntryInGrid()
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > & list, WorldObject * source, uint32 entry, float maxSearchRange)
{
    source->GetGameObjectListWithEntryInGrid(list, entry, maxSearchRange);
}
References WorldObject::GetGameObjectListWithEntryInGrid().
Referenced by boss_broodlord::boss_broodlordAI::JustDied(), npc_coren_direbrew::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), and npc_ranshalla::npc_ranshallaAI::WaypointReached().
Variable Documentation
SpellSummary
struct TSpellSummary* SpellSummary
Referenced by ScriptMgr::FillSpellSummary(), ScriptedAI::SelectSpell(), and ScriptMgr::Unload().