AzerothCore: npc_hor_lich_king::npc_hor_lich_kingAI Struct Reference
npc_hor_lich_king::npc_hor_lich_kingAI Struct Reference
Public Member Functions
npc_hor_lich_kingAI (Creature *creature)
void Reset () override
void DoAction (int32 a) override
void MovementInform (uint32 type, uint32) override
void JustSummoned (Creature *s) override
void SummonedCreatureDespawn (Creature *s) override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
uint8 currentWall
uint8 reqKillCount
uint8 div2
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_hor_lich_kingAI()
npc_hor_lich_king::npc_hor_lich_kingAI::npc_hor_lich_kingAI (Creature * creature) inline
                                                : NullCreatureAI(creature), summons(me)
        {
            pInstance = me->GetInstanceScript();
            if (!pInstance)
                me->IsAIEnabled = false;
        }
References WorldObject::GetInstanceScript(), Unit::IsAIEnabled, CreatureAI::me, and pInstance.
Member Function Documentation
DoAction()
void npc_hor_lich_king::npc_hor_lich_kingAI::DoAction (int32 a) inline override virtual
Reimplemented from UnitAI.
        {
            if (a == ACTION_START_LK_FIGHT_REAL)
                events.ScheduleEvent(EVENT_LK_START_FOLLOWING, 1500ms);
            else if ((a == ACTION_INFORM_TRASH_DIED && reqKillCount) || a == ACTION_CHECK_TRASH_DIED)
            {
                if ((a == ACTION_CHECK_TRASH_DIED && reqKillCount == 0) || (a == ACTION_INFORM_TRASH_DIED && (--reqKillCount) == 0))
                {
                    events.CancelEvent(EVENT_DECREASE_REQ_COUNT_BY_100); // just in case, magic happens sometimes
                    ++currentWall;
                    pInstance->SetData(ACTION_DELETE_ICE_WALL, 1);
                    if (currentWall <= 3)
                    {
                        events.ScheduleEvent(EVENT_LK_SUMMON_NEXT_ICE_WALL, 1s);
                        events.ScheduleEvent(EVENT_LK_SUMMON, currentWall == 3 ? 11s : 7500ms);
                    }
                    else
                        me->RemoveAura(SPELL_REMORSELESS_WINTER);
                    if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_SYLVANAS_PART2)))
                        c->AI()->DoAction(ACTION_INFORM_WALL_DESTROYED);
                }
            }
        }
References ACTION_CHECK_TRASH_DIED, ACTION_DELETE_ICE_WALL, ACTION_INFORM_TRASH_DIED, ACTION_INFORM_WALL_DESTROYED, ACTION_START_LK_FIGHT_REAL, currentWall, EVENT_DECREASE_REQ_COUNT_BY_100, EVENT_LK_START_FOLLOWING, EVENT_LK_SUMMON, EVENT_LK_SUMMON_NEXT_ICE_WALL, Map::GetCreature(), InstanceScript::GetGuidData(), InstanceScript::instance, CreatureAI::me, NPC_SYLVANAS_PART2, pInstance, Unit::RemoveAura(), reqKillCount, ZoneScript::SetData(), and SPELL_REMORSELESS_WINTER.
Referenced by UpdateAI().
JustSummoned()
void npc_hor_lich_king::npc_hor_lich_kingAI::JustSummoned (Creature * s) inline override virtual
Reimplemented from CreatureAI.
        {
            ++reqKillCount;
            if (events.GetNextEventTime(EVENT_DECREASE_REQ_COUNT_BY_100))
                events.RescheduleEvent(EVENT_DECREASE_REQ_COUNT_BY_100, 10s);
            summons.Summon(s);
            s->SetHomePosition(PathWaypoints[WP_STOP[currentWall + 1]]);
            s->GetMotionMaster()->MovePoint(0, PathWaypoints[WP_STOP[currentWall + 1]]);
            s->SetInCombatWithZone();
            if (Unit* target = s->SelectNearestPlayer(350.0f))
            {
                s->AddThreat(target, 1000.0f);
                s->AI()->AttackStart(target);
            }
            s->SetHomePosition(PathWaypoints[WP_STOP[currentWall + 1]]);
        }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), currentWall, EVENT_DECREASE_REQ_COUNT_BY_100, Unit::GetMotionMaster(), MotionMaster::MovePoint(), PathWaypoints, reqKillCount, WorldObject::SelectNearestPlayer(), Creature::SetHomePosition(), Creature::SetInCombatWithZone(), SummonList::Summon(), summons, and WP_STOP.
MovementInform()
void npc_hor_lich_king::npc_hor_lich_kingAI::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from CreatureAI.
        {
            // Xinef: dont use 0, it is no longer the last point
            // Xinef: if type is escort and spline is finalized, it means that we reached last point from the path
            if (type == ESCORT_MOTION_TYPE && me->movespline->Finalized())
            {
                if (currentWall == 0)
                {
                    Talk(SAY_LK_IW_1);
                    me->SetOrientation(4.15f);
                    if (Creature* icewall = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_ICE_WALL_TARGET)))
                    {
                        me->SetFacingToObject(icewall);
                        me->CastSpell(icewall, SPELL_SUMMON_ICE_WALL, false);
                        events.ScheduleEvent(EVENT_LK_REMORSELESS_WINTER, 4s);
                    }
                }
                else if (currentWall == 4)
                {
                    Talk(SAY_LK_NOWHERE_TO_RUN);
                    pInstance->SetData(DATA_LICH_KING, DONE);
                }
            }
        }
References Unit::CastSpell(), currentWall, DATA_LICH_KING, DONE, ESCORT_MOTION_TYPE, EVENT_LK_REMORSELESS_WINTER, Movement::MoveSpline::Finalized(), Map::GetCreature(), InstanceScript::GetGuidData(), InstanceScript::instance, CreatureAI::me, Unit::movespline, NPC_ICE_WALL_TARGET, pInstance, SAY_LK_IW_1, SAY_LK_NOWHERE_TO_RUN, ZoneScript::SetData(), Unit::SetFacingToObject(), Position::SetOrientation(), and SPELL_SUMMON_ICE_WALL.
Reset()
void npc_hor_lich_king::npc_hor_lich_kingAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            currentWall = 0;
            reqKillCount = 0;
            events.Reset();
            events.RescheduleEvent(EVENT_LK_CHECK_COMBAT, 1s);
        }
References currentWall, EVENT_LK_CHECK_COMBAT, and reqKillCount.
SpellHitTarget()
void npc_hor_lich_king::npc_hor_lich_kingAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
        {
            if (target && target->IsAlive() && spell->Id == SPELL_LICH_KING_ZAP_PLAYER)
                Unit::DealDamage(me, target, 10000);
        }
References Unit::DealDamage(), SpellInfo::Id, Unit::IsAlive(), CreatureAI::me, and SPELL_LICH_KING_ZAP_PLAYER.
SummonedCreatureDespawn()
void npc_hor_lich_king::npc_hor_lich_kingAI::SummonedCreatureDespawn (Creature * s) inline override virtual
Reimplemented from CreatureAI.
        {
            summons.Despawn(s);
        }
References SummonList::Despawn(), and summons.
UpdateAI()
void npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
        {
            if (me->HealthBelowPct(70))
                me->SetHealth(me->GetMaxHealth() * 3 / 4);
            events.Update(diff);
            if (me->IsNonMeleeSpellCast(false, true, true))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_LK_CHECK_COMBAT:
                    if (me->isActiveObject()) // during fight
                    {
                        if (Creature* leader = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_SYLVANAS_PART2)))
                            if (leader->IsAlive() && leader->GetPositionX() < 5575.0f && me->GetExactDist2d(leader) <= 12.5f && !leader->HasAura(SPELL_HARVEST_SOUL) && me->HasAura(SPELL_REMORSELESS_WINTER))
{
                                me->GetMotionMaster()->MovementExpired();
                                me->StopMoving();
                                reqKillCount = 255;
                                leader->InterruptNonMeleeSpells(true);
                                me->CastSpell(leader, SPELL_HARVEST_SOUL, false);
                                events.ScheduleEvent(EVENT_LK_KILL_LEADER, 3s);
                                events.ScheduleEvent(EVENT_LK_CHECK_COMBAT, 1s);
                                break;
                            }
                        if (pInstance->instance->HavePlayers())
{
                            me->SetInCombatWithZone();
                            ++div2;
                            if (div2 > 1)
{
                                div2 = 0;
                                if (me->HasAura(SPELL_REMORSELESS_WINTER)) // prevent going behind him during fight
{
                                    Map::PlayerList const& pl = pInstance->instance->GetPlayers();
                                    for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                                        if (Player* p = itr->GetSource())
                                            if (!p->IsGameMaster() && p->IsAlive() && (p->GetPositionX() - me->GetPositionX() + p->GetPositionY() - me->GetPositionY()) > 20.0f)
                                                me->CastSpell(p, SPELL_LICH_KING_ZAP_PLAYER, true);
                                }
                            }
                        }
                        else
{
                            summons.DespawnAll();
                            pInstance->SetData(ACTION_STOP_LK_FIGHT, 1);
                        }
                    }
                    events.ScheduleEvent(EVENT_LK_CHECK_COMBAT, 1s);
                    break;
                case EVENT_LK_KILL_LEADER:
                    if (Creature* leader = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_SYLVANAS_PART2)))
                    {
                        leader->CastSpell(leader, SPELL_HOR_SUICIDE, true);
                        Unit::Kill(me, leader);
                        me->InterruptNonMeleeSpells(true);
                        me->CastSpell((Unit*)nullptr, SPELL_FURY_OF_FROSTMOURNE, false);
                    }
                    break;
                case EVENT_LK_START_FOLLOWING:
                    {
                        me->SetSpeed(MOVE_RUN, 9.0f / 7.0f);
                        Movement::PointsArray path;
                        path.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                        for (uint8 i = 0; i <= 2; ++i)
                            path.push_back(G3D::Vector3(PathWaypoints[i].GetPositionX(), PathWaypoints[i].GetPositionY(), PathWaypoints[i].GetPositionZ()));
                        me->GetMotionMaster()->MoveSplinePath(&path);
                    }
                    break;
                case EVENT_LK_REMORSELESS_WINTER:
                    {
                        me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run);
                        Talk(SAY_LK_WINTER);
                        me->CastSpell(me, SPELL_REMORSELESS_WINTER, true);
                        Movement::PointsArray path;
                        path.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                        for (uint8 i = 3; i < PATH_WP_COUNT - 1; ++i)
                            path.push_back(G3D::Vector3(PathWaypoints[i].GetPositionX(), PathWaypoints[i].GetPositionY(), PathWaypoints[i].GetPositionZ()));
                        me->GetMotionMaster()->MoveSplinePath(&path);
                        me->GetMotionMaster()->propagateSpeedChange();
                        events.ScheduleEvent(EVENT_LK_SUMMON, 1s);
                    }
                    break;
                case EVENT_LK_SUMMON:
                    switch (currentWall)
                    {
                        case 0:
                            events.ScheduleEvent(EVENT_LK_SUMMON_GHOULS, 0ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 4s);
                            break;
                        case 1:
                            events.ScheduleEvent(EVENT_LK_SUMMON_LA, 0ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_GHOULS, 100ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 4s);
                            events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 5100ms);
                            break;
                        case 2:
                            events.ScheduleEvent(EVENT_LK_SUMMON_LA, 0ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_GHOULS, 100ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_LA, 4s);
                            events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 4100ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 5200ms);
                            break;
                        case 3:
                            events.ScheduleEvent(EVENT_LK_SUMMON_LA, 0ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 100ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_GHOULS, 1200ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 5300ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 6400ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_GHOULS, 12s + 500ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_LA, 16s + 500ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 16s + 600ms);
                            events.ScheduleEvent(EVENT_LK_SUMMON_LA, 17s + 700ms);
                            break;
                    }
                    if (currentWall <= 3)
                    {
                        reqKillCount = 100;
                        events.RescheduleEvent(EVENT_DECREASE_REQ_COUNT_BY_100, 10s);
                    }
                    break;
                case EVENT_DECREASE_REQ_COUNT_BY_100:
                    reqKillCount = (reqKillCount <= 100 ? 0 : reqKillCount - 100);
                    DoAction(ACTION_CHECK_TRASH_DIED);
                    break;
                case EVENT_LK_SUMMON_GHOULS:
                    me->CastSpell((Unit*)nullptr, SPELL_SUMMON_RAGING_GHOULS, false);
                    break;
                case EVENT_LK_SUMMON_RWD:
                    me->CastSpell((Unit*)nullptr, SPELL_SUMMON_RISEN_WITCH_DOCTOR, false);
                    break;
                case EVENT_LK_SUMMON_LA:
                    me->CastSpell((Unit*)nullptr, SPELL_SUMMON_LUMBERING_ABOMINATION, false);
                    break;
                case EVENT_LK_SUMMON_NEXT_ICE_WALL:
                    Talk(SAY_LK_IW_1 + currentWall);
                    if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_ICE_WALL_TARGET + currentWall)))
                        me->CastSpell(c, SPELL_SUMMON_ICE_WALL, false);
                    break;
            }
        }
References ACTION_CHECK_TRASH_DIED, ACTION_STOP_LK_FIGHT, MapRefMgr::begin(), Unit::CastSpell(), currentWall, SummonList::DespawnAll(), div2, DoAction(), MapRefMgr::end(), EVENT_DECREASE_REQ_COUNT_BY_100, EVENT_LK_CHECK_COMBAT, EVENT_LK_KILL_LEADER, EVENT_LK_REMORSELESS_WINTER, EVENT_LK_START_FOLLOWING, EVENT_LK_SUMMON, EVENT_LK_SUMMON_GHOULS, EVENT_LK_SUMMON_LA, EVENT_LK_SUMMON_NEXT_ICE_WALL, EVENT_LK_SUMMON_RWD, Map::GetCreature(), Creature::GetCreatureTemplate(), Position::GetExactDist2d(), InstanceScript::GetGuidData(), Unit::GetMaxHealth(), Unit::GetMotionMaster(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::HasAura(), Map::HavePlayers(), Unit::HealthBelowPct(), InstanceScript::instance, Unit::InterruptNonMeleeSpells(), WorldObject::isActiveObject(), Unit::IsNonMeleeSpellCast(), Unit::Kill(), CreatureAI::me, MOVE_RUN, MotionMaster::MovementExpired(), MotionMaster::MoveSplinePath(), NPC_ICE_WALL_TARGET, NPC_SYLVANAS_PART2, PATH_WP_COUNT, PathWaypoints, pInstance, MotionMaster::propagateSpeedChange(), reqKillCount, SAY_LK_IW_1, SAY_LK_WINTER, ZoneScript::SetData(), Unit::SetHealth(), Creature::SetInCombatWithZone(), Unit::SetSpeed(), CreatureTemplate::speed_run, SPELL_FURY_OF_FROSTMOURNE, SPELL_HARVEST_SOUL, SPELL_HOR_SUICIDE, SPELL_LICH_KING_ZAP_PLAYER, SPELL_REMORSELESS_WINTER, SPELL_SUMMON_ICE_WALL, SPELL_SUMMON_LUMBERING_ABOMINATION, SPELL_SUMMON_RAGING_GHOULS, SPELL_SUMMON_RISEN_WITCH_DOCTOR, Unit::StopMoving(), and summons.
Member Data Documentation
currentWall
uint8 npc_hor_lich_king::npc_hor_lich_kingAI::currentWall
Referenced by DoAction(), JustSummoned(), MovementInform(), Reset(), and UpdateAI().
div2
uint8 npc_hor_lich_king::npc_hor_lich_kingAI::div2
Referenced by UpdateAI().
events
EventMap npc_hor_lich_king::npc_hor_lich_kingAI::events
pInstance
InstanceScript* npc_hor_lich_king::npc_hor_lich_kingAI::pInstance
Referenced by DoAction(), MovementInform(), npc_hor_lich_kingAI(), and UpdateAI().
reqKillCount
uint8 npc_hor_lich_king::npc_hor_lich_kingAI::reqKillCount
Referenced by DoAction(), JustSummoned(), Reset(), and UpdateAI().
summons
SummonList npc_hor_lich_king::npc_hor_lich_kingAI::summons
Referenced by JustSummoned(), SummonedCreatureDespawn(), and UpdateAI().