AzerothCore: achievement_everything_counts Class Reference
achievement_everything_counts Class Reference
Public Member Functions
achievement_everything_counts ()
bool OnCheck (Player *source, Unit *, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
virtual bool OnCheck (Player *, Unit *, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_everything_counts()
achievement_everything_counts::achievement_everything_counts () inline
: AchievementCriteriaScript("achievement_everything_counts") { }
Member Function Documentation
OnCheck()
bool achievement_everything_counts::OnCheck (Player * source, Unit * , uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
    {
        Battleground* bg = source->GetBattleground();
        return bg && bg->GetBgTypeID(true) == BATTLEGROUND_AV && bg->ToBattlegroundAV()->IsBothMinesControlledByTeam(source->GetTeamId());
    }
References BATTLEGROUND_AV, Player::GetBattleground(), Battleground::GetBgTypeID(), Player::GetTeamId(), BattlegroundAV::IsBothMinesControlledByTeam(), and Battleground::ToBattlegroundAV().