AzerothCore: OutdoorPvP Class Reference
OutdoorPvP Class Reference
#include "OutdoorPvP.h"
Public Types
typedef std::map< ObjectGuid::LowType, OPvPCapturePoint * > OPvPCapturePointMap
typedef std::pair< ObjectGuid::LowType, GameObject * > GoScriptPair
typedef std::pair< ObjectGuid::LowType, Creature * > CreatureScriptPair
Public Member Functions
OutdoorPvP ()
~OutdoorPvP () override
void DeleteSpawns ()
virtual void FillInitialWorldStates (WorldPacket &)
virtual bool HandleAreaTrigger (Player *player, uint32 trigger)
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual bool HandleOpenGo (Player *player, GameObject *go)
virtual bool SetupOutdoorPvP ()
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SendUpdateWorldState (uint32 field, uint32 value)
virtual bool Update (uint32 diff)
virtual void HandleKill (Player *killer, Unit *killed)
virtual void HandleKillImpl (Player *, Unit *)
bool IsInsideObjective (Player *player) const
virtual void AwardKillBonus (Player *)
uint32 GetTypeId ()
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipid)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
void TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2=0, Player *sameMapPlr=nullptr)
Map * GetMap () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Member Functions
virtual void SendRemoveWorldStates (Player *)
void BroadcastPacket (WorldPacket &data) const
virtual void HandlePlayerEnterZone (Player *player, uint32 zone)
virtual void HandlePlayerLeaveZone (Player *player, uint32 zone)
virtual void HandlePlayerResurrects (Player *player, uint32 zone)
void AddCapturePoint (OPvPCapturePoint *cp)
OPvPCapturePoint * GetCapturePoint (ObjectGuid::LowType spawnId) const
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player const *player) const
void TeamCastSpell (TeamId team, int32 spellId, Player *sameMapPlr=nullptr)
void SetMapFromZone (uint32 zone)
Protected Attributes
OPvPCapturePointMap m_capturePoints
PlayerSet m_players [2]
uint32 m_TypeId
bool m_sendUpdate
std::map< ObjectGuid::LowType, GameObject * > m_GoScriptStore
std::map< ObjectGuid::LowType, Creature * > m_CreatureScriptStore
Map * m_map
Friends
class OutdoorPvPMgr
Detailed Description
Member Typedef Documentation
CreatureScriptPair
typedef std::pair<ObjectGuid::LowType, Creature*> OutdoorPvP::CreatureScriptPair
GoScriptPair
typedef std::pair<ObjectGuid::LowType, GameObject*> OutdoorPvP::GoScriptPair
OPvPCapturePointMap
typedef std::map<ObjectGuid::LowType, OPvPCapturePoint*> OutdoorPvP::OPvPCapturePointMap
Constructor & Destructor Documentation
OutdoorPvP()
OutdoorPvP::OutdoorPvP ()
: m_TypeId(0), m_sendUpdate(true), m_map(nullptr) { }
~OutdoorPvP()
OutdoorPvP::~OutdoorPvP () override
{
    DeleteSpawns();
}
References DeleteSpawns().
Member Function Documentation
AddCapturePoint()
void OutdoorPvP::AddCapturePoint (OPvPCapturePoint * cp) inline protected
    {
        m_capturePoints[cp->m_capturePointSpawnId] = cp;
    }
References m_capturePoints, and OPvPCapturePoint::m_capturePointSpawnId.
Referenced by OutdoorPvPEP::SetupOutdoorPvP(), OutdoorPvPGH::SetupOutdoorPvP(), OutdoorPvPHP::SetupOutdoorPvP(), OutdoorPvPNA::SetupOutdoorPvP(), OutdoorPvPTF::SetupOutdoorPvP(), and OutdoorPvPZM::SetupOutdoorPvP().
AwardKillBonus()
virtual void OutdoorPvP::AwardKillBonus (Player *) inline virtual
{}
BroadcastPacket()
void OutdoorPvP::BroadcastPacket (WorldPacket & data) const protected
{
    // This is faster than sWorld->SendZoneMessage
    for (uint32 team = 0; team < 2; ++team)
        for (PlayerSet::const_iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
            if (Player* const player = ObjectAccessor::FindPlayer(*itr))
                player->GetSession()->SendPacket(&data);
}
References ObjectAccessor::FindPlayer(), and m_players.
CanTalkTo()
bool OutdoorPvP::CanTalkTo (Player * player, Creature * c, GossipMenuItems const & gso) virtual
{
    for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
        if (itr->second->CanTalkTo(player, c, gso))
            return true;
    return false;
}
References m_capturePoints.
DeleteSpawns()
void OutdoorPvP::DeleteSpawns ()
{
    // Remove script from any registered gameobjects/creatures
    for (auto itr = m_GoScriptStore.begin(); itr != m_GoScriptStore.end(); ++itr)
    {
        if (GameObject* go = itr->second)
            go->ClearZoneScript();
    }
    m_GoScriptStore.clear();
    for (auto itr = m_CreatureScriptStore.begin(); itr != m_CreatureScriptStore.end(); ++itr)
    {
        if (Creature* creature = itr->second)
            creature->ClearZoneScript();
    }
    m_CreatureScriptStore.clear();
    for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
    {
        itr->second->DeleteSpawns();
        delete itr->second;
    }
    m_capturePoints.clear();
}
References m_capturePoints, m_CreatureScriptStore, and m_GoScriptStore.
Referenced by ~OutdoorPvP().
FillInitialWorldStates()
virtual void OutdoorPvP::FillInitialWorldStates (WorldPacket &) inline virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{}
Referenced by Player::SendInitWorldStates().
GetCapturePoint()
OPvPCapturePoint * OutdoorPvP::GetCapturePoint (ObjectGuid::LowType spawnId) const inline protected
    {
        OutdoorPvP::OPvPCapturePointMap::const_iterator itr = m_capturePoints.find(spawnId);
        if (itr != m_capturePoints.end())
            return itr->second;
        return nullptr;
    }
References m_capturePoints.
Referenced by OnGameObjectCreate(), and OnGameObjectRemove().
GetMap()
Map * OutdoorPvP::GetMap () const inline
{ return m_map; }
References m_map.
Referenced by OPvPCapturePoint::DelCreature(), OPvPCapturePoint::DelObject(), and OPvPCapturePointNA::GetAliveGuardsCount().
GetTypeId()
uint32 OutdoorPvP::GetTypeId () inline
{return m_TypeId;}
References m_TypeId.
Referenced by Player::SendInitWorldStates().
HandleAreaTrigger()
bool OutdoorPvP::HandleAreaTrigger (Player * player, uint32 trigger) virtual
Reimplemented in OutdoorPvPSI.
{
    return false;
}
HandleCustomSpell()
bool OutdoorPvP::HandleCustomSpell (Player * player, uint32 spellId, GameObject * go) virtual
Reimplemented in OutdoorPvPSI.
{
    for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
        if (itr->second->HandleCustomSpell(player, spellId, go))
            return true;
    return false;
}
References m_capturePoints.
HandleDropFlag()
bool OutdoorPvP::HandleDropFlag (Player * player, uint32 spellId) virtual
Reimplemented in OutdoorPvPSI.
{
    for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
        if (itr->second->HandleDropFlag(player, id))
            return true;
    return false;
}
References m_capturePoints.
HandleGossipOption()
bool OutdoorPvP::HandleGossipOption (Player * player, Creature * creature, uint32 gossipid) virtual
{
    for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
        if (itr->second->HandleGossipOption(player, creature, id))
            return true;
    return false;
}
References m_capturePoints.
HandleKill()
void OutdoorPvP::HandleKill (Player * killer, Unit * killed) virtual
{
    if (Group* group = killer->GetGroup())
    {
        for (GroupReference* itr = group->GetFirstMember(); itr != nullptr; itr = itr->next())
        {
            Player* groupGuy = itr->GetSource();
            if (!groupGuy)
                continue;
            // skip if too far away
            if (!groupGuy->IsAtGroupRewardDistance(killed) && killer != groupGuy)
                continue;
            // creature kills must be notified, even if not inside objective / not outdoor pvp active
            // player kills only count if active and inside objective
            if ((groupGuy->IsOutdoorPvPActive() && IsInsideObjective(groupGuy)) || killed->GetTypeId() == TYPEID_UNIT)
            {
                HandleKillImpl(groupGuy, killed);
            }
        }
    }
    else
    {
        // creature kills must be notified, even if not inside objective / not outdoor pvp active
        if (killer && ((killer->IsOutdoorPvPActive() && IsInsideObjective(killer)) || killed->GetTypeId() == TYPEID_UNIT))
        {
            HandleKillImpl(killer, killed);
        }
    }
}
References Player::GetGroup(), Object::GetTypeId(), HandleKillImpl(), Player::IsAtGroupRewardDistance(), IsInsideObjective(), Player::IsOutdoorPvPActive(), GroupReference::next(), and TYPEID_UNIT.
HandleKillImpl()
virtual void OutdoorPvP::HandleKillImpl (Player * , Unit *) inline virtual
Reimplemented in OutdoorPvPHP, OutdoorPvPNA, and OutdoorPvPZM.
{}
Referenced by HandleKill().
HandleOpenGo()
bool OutdoorPvP::HandleOpenGo (Player * player, GameObject * go) virtual
{
    for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
        if (itr->second->HandleOpenGo(player, go) >= 0)
            return true;
    return false;
}
References m_capturePoints.
HandlePlayerEnterZone()
void OutdoorPvP::HandlePlayerEnterZone (Player * player, uint32 zone) protected virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{
    m_players[player->GetTeamId()].insert(player->GetGUID());
}
References Object::GetGUID(), Player::GetTeamId(), and m_players.
Referenced by OutdoorPvPEP::HandlePlayerEnterZone(), OutdoorPvPHP::HandlePlayerEnterZone(), OutdoorPvPNA::HandlePlayerEnterZone(), OutdoorPvPSI::HandlePlayerEnterZone(), OutdoorPvPTF::HandlePlayerEnterZone(), and OutdoorPvPZM::HandlePlayerEnterZone().
HandlePlayerLeaveZone()
void OutdoorPvP::HandlePlayerLeaveZone (Player * player, uint32 zone) protected virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{
    // inform the objectives of the leaving
    for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
        itr->second->HandlePlayerLeave(player);
    // remove the world state information from the player (we can't keep everyone up to date, so leave out those who are not in the concerning zones)
    if (!player->GetSession()->PlayerLogout())
        SendRemoveWorldStates(player);
    m_players[player->GetTeamId()].erase(player->GetGUID());
    LOG_DEBUG("outdoorpvp", "Player {} left an outdoorpvp zone", player->GetName());
}
References Object::GetGUID(), WorldObject::GetName(), Player::GetSession(), Player::GetTeamId(), LOG_DEBUG, m_capturePoints, m_players, WorldSession::PlayerLogout(), and SendRemoveWorldStates().
Referenced by OutdoorPvPEP::HandlePlayerLeaveZone(), OutdoorPvPHP::HandlePlayerLeaveZone(), OutdoorPvPNA::HandlePlayerLeaveZone(), OutdoorPvPSI::HandlePlayerLeaveZone(), OutdoorPvPTF::HandlePlayerLeaveZone(), and OutdoorPvPZM::HandlePlayerLeaveZone().
HandlePlayerResurrects()
void OutdoorPvP::HandlePlayerResurrects (Player * player, uint32 zone) protected virtual
{
}
HasPlayer()
bool OutdoorPvP::HasPlayer (Player const * player) const protected
{
    PlayerSet const& plSet = m_players[player->GetTeamId()];
    return plSet.find(player->GetGUID()) != plSet.end();
}
References Object::GetGUID(), Player::GetTeamId(), and m_players.
IsInsideObjective()
bool OutdoorPvP::IsInsideObjective (Player * player) const
{
    for (OPvPCapturePointMap::const_iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
        if (itr->second->IsInsideObjective(player))
            return true;
    return false;
}
References m_capturePoints.
Referenced by HandleKill().
OnCreatureCreate()
void OutdoorPvP::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from ZoneScript.
{
    CreatureScriptPair sp(creature->GetGUID().GetCounter(), creature);
    m_CreatureScriptStore.insert(sp);
}
References ObjectGuid::GetCounter(), Object::GetGUID(), and m_CreatureScriptStore.
OnCreatureRemove()
void OutdoorPvP::OnCreatureRemove (Creature * creature) override virtual
Reimplemented from ZoneScript.
{
    m_CreatureScriptStore.erase(creature->GetGUID().GetCounter());
}
References ObjectGuid::GetCounter(), Object::GetGUID(), and m_CreatureScriptStore.
OnGameObjectCreate()
void OutdoorPvP::OnGameObjectCreate (GameObject * go) override virtual
Reimplemented from ZoneScript.
{
    GoScriptPair sp(go->GetGUID().GetCounter(), go);
    m_GoScriptStore.insert(sp);
    if (go->GetGoType() != GAMEOBJECT_TYPE_CAPTURE_POINT)
        return;
    if (OPvPCapturePoint* cp = GetCapturePoint(go->GetSpawnId()))
        cp->m_capturePoint = go;
}
References GAMEOBJECT_TYPE_CAPTURE_POINT, GetCapturePoint(), ObjectGuid::GetCounter(), GameObject::GetGoType(), Object::GetGUID(), GameObject::GetSpawnId(), and m_GoScriptStore.
OnGameObjectRemove()
void OutdoorPvP::OnGameObjectRemove (GameObject * go) override virtual
Reimplemented from ZoneScript.
{
    m_GoScriptStore.erase(go->GetGUID().GetCounter());
    if (go->GetGoType() != GAMEOBJECT_TYPE_CAPTURE_POINT)
        return;
    if (OPvPCapturePoint* cp = GetCapturePoint(go->GetSpawnId()))
        cp->m_capturePoint = nullptr;
}
References GAMEOBJECT_TYPE_CAPTURE_POINT, GetCapturePoint(), ObjectGuid::GetCounter(), GameObject::GetGoType(), Object::GetGUID(), GameObject::GetSpawnId(), and m_GoScriptStore.
RegisterZone()
void OutdoorPvP::RegisterZone (uint32 zoneid) protected
{
    sOutdoorPvPMgr->AddZone(zoneId, this);
}
References sOutdoorPvPMgr.
Referenced by OutdoorPvPEP::SetupOutdoorPvP(), OutdoorPvPGH::SetupOutdoorPvP(), OutdoorPvPHP::SetupOutdoorPvP(), OutdoorPvPNA::SetupOutdoorPvP(), OutdoorPvPSI::SetupOutdoorPvP(), OutdoorPvPTF::SetupOutdoorPvP(), and OutdoorPvPZM::SetupOutdoorPvP().
SendRemoveWorldStates()
virtual void OutdoorPvP::SendRemoveWorldStates (Player *) inline protected virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPGH, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{}
Referenced by HandlePlayerLeaveZone().
SendUpdateWorldState()
void OutdoorPvP::SendUpdateWorldState (uint32 field, uint32 value)
{
    if (m_sendUpdate)
        for (int i = 0; i < 2; ++i)
            for (PlayerSet::iterator itr = m_players[i].begin(); itr != m_players[i].end(); ++itr)
                if (Player* const player = ObjectAccessor::FindPlayer(*itr))
                    player->SendUpdateWorldState(field, value);
}
References ObjectAccessor::FindPlayer(), m_players, and m_sendUpdate.
Referenced by OPvPCapturePointHP::ChangeState(), OPvPCapturePointNA::FactionTakeOver(), OutdoorPvPTF::ResetZoneToTeamControlled(), OutdoorPvPEP::Update(), OutdoorPvPHP::Update(), OPvPCapturePointNA::Update(), OutdoorPvPTF::Update(), OPvPCapturePointNA::UpdateHalaaWorldState(), OPvPCapturePointEP_EWT::UpdateTowerState(), OPvPCapturePointEP_NPT::UpdateTowerState(), OPvPCapturePointEP_CGT::UpdateTowerState(), OPvPCapturePointEP_PWT::UpdateTowerState(), OPvPCapturePointTF::UpdateTowerState(), OPvPCapturePointZM_Beacon::UpdateTowerState(), OPvPCapturePointZM_GraveYard::UpdateTowerState(), OutdoorPvPSI::UpdateWorldState(), and OPvPCapturePointNA::UpdateWyvernRoostWorldState().
SetMapFromZone()
void OutdoorPvP::SetMapFromZone (uint32 zone) protected
{
    AreaTableEntry const* areaTable = sAreaTableStore.LookupEntry(zone);
    ASSERT(areaTable);
    Map* map = sMapMgr->CreateBaseMap(areaTable->mapid);
    ASSERT(!map->Instanceable());
    m_map = map;
}
References ASSERT, Map::Instanceable(), m_map, AreaTableEntry::mapid, sAreaTableStore, and sMapMgr.
Referenced by OutdoorPvPEP::SetupOutdoorPvP(), OutdoorPvPGH::SetupOutdoorPvP(), OutdoorPvPHP::SetupOutdoorPvP(), OutdoorPvPNA::SetupOutdoorPvP(), OutdoorPvPSI::SetupOutdoorPvP(), OutdoorPvPTF::SetupOutdoorPvP(), and OutdoorPvPZM::SetupOutdoorPvP().
SetupOutdoorPvP()
virtual bool OutdoorPvP::SetupOutdoorPvP () inline virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPGH, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{return true;}
Referenced by OutdoorPvPMgr::InitOutdoorPvP().
TeamApplyBuff()
void OutdoorPvP::TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2 = 0, Player * sameMapPlr = nullptr)
{
    TeamCastSpell(teamId, spellId, sameMapPlr);
    TeamCastSpell(teamId == TEAM_ALLIANCE ? TEAM_HORDE : TEAM_ALLIANCE, spellId2 ? -(int32)spellId2 : -(int32)spellId, sameMapPlr);
}
References TEAM_ALLIANCE, TEAM_HORDE, and TeamCastSpell().
Referenced by OPvPCapturePointNA::FactionTakeOver(), OutdoorPvPSI::HandleAreaTrigger(), OPvPCapturePointZM_GraveYard::HandleOpenGo(), OutdoorPvPHP::Update(), and OutdoorPvPTF::Update().
TeamCastSpell()
void OutdoorPvP::TeamCastSpell (TeamId team, int32 spellId, Player * sameMapPlr = nullptr) protected
{
    if (spellId > 0)
    {
        for (PlayerSet::iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
            if (Player* const player = ObjectAccessor::FindPlayer(*itr))
                if (!sameMapPlr || sameMapPlr->FindMap() == player->FindMap())
                    player->CastSpell(player, (uint32)spellId, true);
    }
    else
    {
        for (PlayerSet::iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
            if (Player* const player = ObjectAccessor::FindPlayer(*itr))
                if (!sameMapPlr || sameMapPlr->FindMap() == player->FindMap())
                    player->RemoveAura((uint32) - spellId); // by stack?
    }
}
References WorldObject::FindMap(), ObjectAccessor::FindPlayer(), and m_players.
Referenced by TeamApplyBuff(), OutdoorPvPHP::Update(), and OutdoorPvPTF::Update().
Update()
bool OutdoorPvP::Update (uint32 diff) virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{
    bool objective_changed = false;
    for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
    {
        if (itr->second->Update(diff))
            objective_changed = true;
    }
    return objective_changed;
}
References m_capturePoints.
Referenced by OutdoorPvPEP::Update(), OutdoorPvPHP::Update(), OutdoorPvPTF::Update(), and OutdoorPvPZM::Update().
Friends And Related Function Documentation
OutdoorPvPMgr
friend class OutdoorPvPMgr friend
Member Data Documentation
m_capturePoints
OPvPCapturePointMap OutdoorPvP::m_capturePoints protected
Referenced by AddCapturePoint(), CanTalkTo(), DeleteSpawns(), OutdoorPvPEP::FillInitialWorldStates(), OutdoorPvPHP::FillInitialWorldStates(), OutdoorPvPTF::FillInitialWorldStates(), OutdoorPvPZM::FillInitialWorldStates(), GetCapturePoint(), HandleCustomSpell(), HandleDropFlag(), HandleGossipOption(), HandleOpenGo(), HandlePlayerLeaveZone(), IsInsideObjective(), OutdoorPvPTF::ResetZoneToTeamControlled(), and Update().
m_CreatureScriptStore
std::map<ObjectGuid::LowType, Creature*> OutdoorPvP::m_CreatureScriptStore protected
Referenced by DeleteSpawns(), OnCreatureCreate(), and OnCreatureRemove().
m_GoScriptStore
std::map<ObjectGuid::LowType, GameObject*> OutdoorPvP::m_GoScriptStore protected
Referenced by DeleteSpawns(), OnGameObjectCreate(), and OnGameObjectRemove().
m_map
Map* OutdoorPvP::m_map protected
Referenced by GetMap(), and SetMapFromZone().
m_players
PlayerSet OutdoorPvP::m_players[2] protected
Referenced by BroadcastPacket(), OutdoorPvPEP::BuffTeams(), HandlePlayerEnterZone(), HandlePlayerLeaveZone(), HasPlayer(), SendUpdateWorldState(), and TeamCastSpell().
m_sendUpdate
bool OutdoorPvP::m_sendUpdate protected
Referenced by SendUpdateWorldState().
m_TypeId
uint32 OutdoorPvP::m_TypeId protected
Referenced by GetTypeId(), OutdoorPvPEP::OutdoorPvPEP(), OutdoorPvPGH::OutdoorPvPGH(), OutdoorPvPHP::OutdoorPvPHP(), OutdoorPvPNA::OutdoorPvPNA(), OutdoorPvPSI::OutdoorPvPSI(), OutdoorPvPTF::OutdoorPvPTF(), and OutdoorPvPZM::OutdoorPvPZM().