AzerothCore: Guild::Member Class Reference
Guild::Member Class Reference
#include "Guild.h"
Public Member Functions
Member (uint32 guildId, ObjectGuid guid, uint8 rankId)
void SetStats (Player *player)
void SetStats (std::string_view name, uint8 level, uint8 _class, uint8 gender, uint32 zoneId, uint32 accountId)
bool CheckStats () const
void SetPublicNote (std::string_view publicNote)
void SetOfficerNote (std::string_view officerNote)
void SetZoneID (uint32 id)
void SetLevel (uint8 var)
void AddFlag (uint8 var)
void RemFlag (uint8 var)
void ResetFlags ()
bool LoadFromDB (Field *fields)
void SaveToDB (CharacterDatabaseTransaction trans) const
ObjectGuid GetGUID () const
std::string const & GetName () const
uint32 GetAccountId () const
uint8 GetRankId () const
uint64 GetLogoutTime () const
std::string GetPublicNote () const
std::string GetOfficerNote () const
uint8 GetClass () const
uint8 GetLevel () const
uint8 GetGender () const
uint8 GetFlags () const
uint32 GetZoneId () const
bool IsOnline ()
void ChangeRank (uint8 newRank)
void UpdateLogoutTime ()
bool IsRank (uint8 rankId) const
bool IsRankNotLower (uint8 rankId) const
bool IsSamePlayer (ObjectGuid guid) const
void UpdateBankWithdrawValue (CharacterDatabaseTransaction trans, uint8 tabId, uint32 amount)
int32 GetBankWithdrawValue (uint8 tabId) const
void ResetValues ()
Player * FindPlayer () const
void SubscribeToGuildBankUpdatePackets ()
void UnsubscribeFromGuildBankUpdatePackets ()
bool ShouldReceiveBankPartialUpdatePackets () const
Private Attributes
uint32 m_guildId
ObjectGuid m_guid
std::string m_name
uint32 m_zoneId
uint8 m_level
uint8 m_class
uint8 m_gender
uint8 m_flags
uint64 m_logoutTime
uint32 m_accountId
uint8 m_rankId
std::string m_publicNote
std::string m_officerNote
std::array< int32, GUILD_BANK_MAX_TABS+1 > m_bankWithdraw = {}
bool receiveGuildBankUpdatePackets
Detailed Description
Constructor & Destructor Documentation
Member()
Guild::Member::Member (uint32 guildId, ObjectGuid guid, uint8 rankId) inline
                                                             :
            m_guildId(guildId),
            m_guid(guid),
            m_zoneId(0),
            m_level(0),
            m_class(0),
            m_flags(GUILDMEMBER_STATUS_NONE),
            m_accountId(0),
            m_rankId(rankId),
            receiveGuildBankUpdatePackets(false)
        {
        }
Member Function Documentation
AddFlag()
void Guild::Member::AddFlag (uint8 var) inline
{ m_flags |= var; }
References m_flags.
ChangeRank()
void Guild::Member::ChangeRank (uint8 newRank)
{
    m_rankId = newRank;
    // Update rank information in player's field, if he is online.
    if (Player* player = FindPlayer())
        player->SetRank(newRank);
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_MEMBER_RANK);
    stmt->SetData (0, newRank);
    stmt->SetData(1, m_guid.GetCounter());
    CharacterDatabase.Execute(stmt);
}
References CHAR_UPD_GUILD_MEMBER_RANK, CharacterDatabase, and PreparedStatementBase::SetData().
Referenced by Guild::_SetLeaderGUID().
CheckStats()
bool Guild::Member::CheckStats () const
{
    if (m_level < 1)
    {
        LOG_ERROR("guild", "Player ({}) has a broken data in field `characters`.`level`, deleting him from guild!", m_guid.ToString());
        return false;
    }
    if (m_class < CLASS_WARRIOR || m_class >= MAX_CLASSES)
    {
        LOG_ERROR("guild", "Player ({}) has a broken data in field `characters`.`class`, deleting him from guild!", m_guid.ToString());
        return false;
    }
    return true;
}
References LOG_ERROR, and MAX_CLASSES.
Referenced by Guild::AddMember().
FindPlayer()
Player * Guild::Member::FindPlayer () const inline
{ return ObjectAccessor::FindConnectedPlayer(m_guid); }
References ObjectAccessor::FindConnectedPlayer(), and m_guid.
Referenced by Guild::DeleteMember().
GetAccountId()
uint32 Guild::Member::GetAccountId () const inline
{ return m_accountId; }
References m_accountId.
GetBankWithdrawValue()
int32 Guild::Member::GetBankWithdrawValue (uint8 tabId) const
{
    // Guild master has unlimited amount.
    if (IsRank(GR_GUILDMASTER))
        return tabId == GUILD_BANK_MAX_TABS ? GUILD_WITHDRAW_MONEY_UNLIMITED : GUILD_WITHDRAW_SLOT_UNLIMITED;
    return m_bankWithdraw[tabId];
}
References GR_GUILDMASTER, GUILD_BANK_MAX_TABS, GUILD_WITHDRAW_MONEY_UNLIMITED, and GUILD_WITHDRAW_SLOT_UNLIMITED.
Referenced by Guild::_GetMemberRemainingMoney(), and Guild::_GetMemberRemainingSlots().
GetClass()
uint8 Guild::Member::GetClass () const inline
{ return m_class; }
References m_class.
GetFlags()
uint8 Guild::Member::GetFlags () const inline
{ return m_flags; }
References m_flags.
GetGender()
uint8 Guild::Member::GetGender () const inline
{ return m_gender; }
References m_gender.
GetGUID()
ObjectGuid Guild::Member::GetGUID () const inline
{ return m_guid; }
References m_guid.
Referenced by Guild::_SetLeaderGUID().
GetLevel()
uint8 Guild::Member::GetLevel () const inline
{ return m_level; }
References m_level.
GetLogoutTime()
uint64 Guild::Member::GetLogoutTime () const inline
{ return m_logoutTime; }
References m_logoutTime.
GetName()
std::string const & Guild::Member::GetName () const inline
{ return m_name; }
References m_name.
Referenced by Guild::DeleteMember().
GetOfficerNote()
std::string Guild::Member::GetOfficerNote () const inline
{ return m_officerNote; }
References m_officerNote.
GetPublicNote()
std::string Guild::Member::GetPublicNote () const inline
{ return m_publicNote; }
References m_publicNote.
GetRankId()
uint8 Guild::Member::GetRankId () const inline
{ return m_rankId; }
References m_rankId.
Referenced by Guild::_GetMemberRemainingMoney(), Guild::_GetMemberRemainingSlots(), Guild::DeleteMember(), Guild::HandleMemberWithdrawMoney(), WorldSession::HandlePlayerLoginFromDB(), Guild::HandleRemoveMember(), Guild::HandleUpdateMemberRank(), and Guild::SendPermissions().
GetZoneId()
uint32 Guild::Member::GetZoneId () const inline
{ return m_zoneId; }
References m_zoneId.
IsOnline()
bool Guild::Member::IsOnline () inline
{ return (m_flags & GUILDMEMBER_STATUS_ONLINE); }
References GUILDMEMBER_STATUS_ONLINE, and m_flags.
IsRank()
bool Guild::Member::IsRank (uint8 rankId) const inline
{ return m_rankId == rankId; }
References m_rankId.
Referenced by Guild::Validate().
IsRankNotLower()
bool Guild::Member::IsRankNotLower (uint8 rankId) const inline
{ return m_rankId <= rankId; }
References m_rankId.
Referenced by Guild::HandleRemoveMember().
IsSamePlayer()
bool Guild::Member::IsSamePlayer (ObjectGuid guid) const inline
{ return m_guid == guid; }
References m_guid.
LoadFromDB()
bool Guild::Member::LoadFromDB (Field * fields)
{
    m_publicNote  = fields[3].Get<std::string>();
    m_officerNote = fields[4].Get<std::string>();
    for (uint8 i = 0; i <= GUILD_BANK_MAX_TABS; ++i)
        m_bankWithdraw[i] = fields[5 + i].Get<uint32>();
    SetStats(fields[12].Get<std::string>(),
             fields[13].Get<uint8>(),                         // characters.level
             fields[14].Get<uint8>(),                         // characters.class
             fields[15].Get<uint8>(),                         // characters.gender
             fields[16].Get<uint16>(),                        // characters.zone
             fields[17].Get<uint32>());                       // characters.account
    m_logoutTime = fields[18].Get<uint32>();                  // characters.logout_time
    if (!CheckStats())
        return false;
    if (!m_zoneId)
    {
        LOG_ERROR("guild", "Player ({}) has broken zone-data", m_guid.ToString());
        m_zoneId = Player::GetZoneIdFromDB(m_guid);
    }
    ResetFlags();
    return true;
}
References Field::Get(), Player::GetZoneIdFromDB(), GUILD_BANK_MAX_TABS, and LOG_ERROR.
Referenced by Guild::LoadMemberFromDB().
RemFlag()
void Guild::Member::RemFlag (uint8 var) inline
{ m_flags &= ~var; }
References m_flags.
ResetFlags()
void Guild::Member::ResetFlags () inline
{ m_flags = GUILDMEMBER_STATUS_NONE; }
References GUILDMEMBER_STATUS_NONE, and m_flags.
Referenced by Guild::AddMember().
ResetValues()
void Guild::Member::ResetValues ()
{
    for (uint8 tabId = 0; tabId <= GUILD_BANK_MAX_TABS; ++tabId)
        m_bankWithdraw[tabId] = 0;
}
References GUILD_BANK_MAX_TABS.
SaveToDB()
void Guild::Member::SaveToDB (CharacterDatabaseTransaction trans) const
{
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_MEMBER);
    stmt->SetData(0, m_guildId);
    stmt->SetData(1, m_guid.GetCounter());
    stmt->SetData (2, m_rankId);
    stmt->SetData(3, m_publicNote);
    stmt->SetData(4, m_officerNote);
    CharacterDatabase.ExecuteOrAppend(trans, stmt);
}
References CHAR_INS_GUILD_MEMBER, CharacterDatabase, and PreparedStatementBase::SetData().
Referenced by Guild::AddMember().
SetLevel()
void Guild::Member::SetLevel (uint8 var) inline
{ m_level = var; }
References m_level.
SetOfficerNote()
void Guild::Member::SetOfficerNote (std::string_view officerNote)
{
    if (m_officerNote == officerNote)
        return;
    m_officerNote = officerNote;
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_MEMBER_OFFNOTE);
    stmt->SetData(0, m_officerNote);
    stmt->SetData(1, m_guid.GetCounter());
    CharacterDatabase.Execute(stmt);
}
References CHAR_UPD_GUILD_MEMBER_OFFNOTE, CharacterDatabase, and PreparedStatementBase::SetData().
SetPublicNote()
void Guild::Member::SetPublicNote (std::string_view publicNote)
{
    if (m_publicNote == publicNote)
        return;
    m_publicNote = publicNote;
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_MEMBER_PNOTE);
    stmt->SetData(0, m_publicNote);
    stmt->SetData(1, m_guid.GetCounter());
    CharacterDatabase.Execute(stmt);
}
References CHAR_UPD_GUILD_MEMBER_PNOTE, CharacterDatabase, and PreparedStatementBase::SetData().
SetStats() [1/2]
void Guild::Member::SetStats (Player * player)
{
    m_name      = player->GetName();
    m_level     = player->GetLevel();
    m_class     = player->getClass();
    m_gender    = player->getGender();
    m_zoneId    = player->GetZoneId();
    m_accountId = player->GetSession()->GetAccountId();
}
References WorldSession::GetAccountId(), Unit::getClass(), Unit::getGender(), Unit::GetLevel(), WorldObject::GetName(), Player::GetSession(), WorldObject::GetZoneId(), and Guild::m_name.
Referenced by Guild::AddMember().
SetStats() [2/2]
void Guild::Member::SetStats (std::string_view name, uint8 level, uint8 _class, uint8 gender, uint32 zoneId, uint32 accountId)
{
    m_name      = name;
    m_level     = level;
    m_class     = _class;
    m_gender    = gender;
    m_zoneId    = zoneId;
    m_accountId = accountId;
}
References Guild::m_name.
SetZoneID()
void Guild::Member::SetZoneID (uint32 id) inline
{ m_zoneId = id; }
References m_zoneId.
ShouldReceiveBankPartialUpdatePackets()
bool Guild::Member::ShouldReceiveBankPartialUpdatePackets () const inline
{ return receiveGuildBankUpdatePackets; }
References receiveGuildBankUpdatePackets.
SubscribeToGuildBankUpdatePackets()
void Guild::Member::SubscribeToGuildBankUpdatePackets () inline
{ receiveGuildBankUpdatePackets = true; }
References receiveGuildBankUpdatePackets.
Referenced by Guild::SendBankTabsInfo().
UnsubscribeFromGuildBankUpdatePackets()
void Guild::Member::UnsubscribeFromGuildBankUpdatePackets () inline
{ receiveGuildBankUpdatePackets = false; }
References receiveGuildBankUpdatePackets.
Referenced by Guild::SendPermissions().
UpdateBankWithdrawValue()
void Guild::Member::UpdateBankWithdrawValue (CharacterDatabaseTransaction trans, uint8 tabId, uint32 amount)
{
    m_bankWithdraw[tabId] += amount;
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_MEMBER_WITHDRAW);
    stmt->SetData(0, m_guid.GetCounter());
    for (uint8 i = 0; i <= GUILD_BANK_MAX_TABS;)
    {
        uint32 withdraw = m_bankWithdraw[i++];
        stmt->SetData(i, withdraw);
    }
    CharacterDatabase.ExecuteOrAppend(trans, stmt);
}
References CHAR_INS_GUILD_MEMBER_WITHDRAW, CharacterDatabase, GUILD_BANK_MAX_TABS, and PreparedStatementBase::SetData().
Referenced by Guild::HandleMemberWithdrawMoney().
UpdateLogoutTime()
void Guild::Member::UpdateLogoutTime ()
{
    m_logoutTime = GameTime::GetGameTime().count();
}
References GameTime::GetGameTime().
Member Data Documentation
m_accountId
uint32 Guild::Member::m_accountId private
Referenced by GetAccountId().
m_bankWithdraw
std::array<int32, GUILD_BANK_MAX_TABS + 1> Guild::Member::m_bankWithdraw = {} private
m_class
uint8 Guild::Member::m_class private
Referenced by GetClass().
m_flags
uint8 Guild::Member::m_flags private
Referenced by AddFlag(), GetFlags(), IsOnline(), RemFlag(), and ResetFlags().
m_gender
uint8 Guild::Member::m_gender private
Referenced by GetGender().
m_guid
ObjectGuid Guild::Member::m_guid private
Referenced by FindPlayer(), GetGUID(), and IsSamePlayer().
m_guildId
uint32 Guild::Member::m_guildId private
m_level
uint8 Guild::Member::m_level private
Referenced by GetLevel(), and SetLevel().
m_logoutTime
uint64 Guild::Member::m_logoutTime private
Referenced by GetLogoutTime().
m_name
std::string Guild::Member::m_name private
Referenced by GetName().
m_officerNote
std::string Guild::Member::m_officerNote private
Referenced by GetOfficerNote().
m_publicNote
std::string Guild::Member::m_publicNote private
Referenced by GetPublicNote().
m_rankId
uint8 Guild::Member::m_rankId private
Referenced by GetRankId(), IsRank(), and IsRankNotLower().
m_zoneId
uint32 Guild::Member::m_zoneId private
Referenced by GetZoneId(), and SetZoneID().
receiveGuildBankUpdatePackets
bool Guild::Member::receiveGuildBankUpdatePackets private
Referenced by ShouldReceiveBankPartialUpdatePackets(), SubscribeToGuildBankUpdatePackets(), and UnsubscribeFromGuildBankUpdatePackets().