AzerothCore: spell_pal_sacred_shield_base Class Reference
spell_pal_sacred_shield_base Class Reference
Private Member Functions
PrepareAuraScript (spell_pal_sacred_shield_base)
void CalculateAmount (AuraEffect const *aurEff, int32 &amount, bool &)
bool CheckProc (ProcEventInfo &eventInfo)
void HandleProc (AuraEffect const *aurEff, ProcEventInfo &eventInfo)
void Register () override
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
CalculateAmount()
void spell_pal_sacred_shield_base::CalculateAmount (AuraEffect const * aurEff, int32 & amount, bool &) inline private
    {
        if (Unit* caster = GetCaster())
        {
            SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(GetSpellInfo()->Effects[aurEff->GetEffIndex()].TriggerSpell);
            amount = spellInfo->Effects[EFFECT_0].CalcValue();
            // +75.00% from sp bonus
            amount += CalculatePct(caster->SpellBaseDamageBonusDone(spellInfo->GetSchoolMask()), 75.0f);
            // Xinef: removed divine guardian because it will affect triggered spell with increased amount
            // Arena - Dampening
            if (AuraEffect const* dampening = caster->GetAuraEffect(SPELL_GENERIC_ARENA_DAMPENING, EFFECT_0))
            {
                AddPct(amount, dampening->GetAmount());
            }
            // Battleground - Dampening
            else if (AuraEffect const* dampening2 = caster->GetAuraEffect(SPELL_GENERIC_BATTLEGROUND_DAMPENING, EFFECT_0))
            {
                AddPct(amount, dampening2->GetAmount());
            }
        }
    }
References AddPct(), CalculatePct(), EFFECT_0, SpellInfo::Effects, AuraScript::GetCaster(), AuraEffect::GetEffIndex(), SpellInfo::GetSchoolMask(), AuraScript::GetSpellInfo(), SPELL_GENERIC_ARENA_DAMPENING, SPELL_GENERIC_BATTLEGROUND_DAMPENING, and sSpellMgr.
Referenced by Register().
CheckProc()
bool spell_pal_sacred_shield_base::CheckProc (ProcEventInfo & eventInfo) inline private
    {
        HealInfo* healinfo = eventInfo.GetHealInfo();
        DamageInfo* damageinfo = eventInfo.GetDamageInfo();
        return !(eventInfo.GetHitMask() & PROC_EX_INTERNAL_HOT) && ((healinfo && healinfo->GetHeal() > 0) || (damageinfo && damageinfo->GetDamage() > 0));
    }
References DamageInfo::GetDamage(), ProcEventInfo::GetDamageInfo(), HealInfo::GetHeal(), ProcEventInfo::GetHealInfo(), ProcEventInfo::GetHitMask(), and PROC_EX_INTERNAL_HOT.
Referenced by Register().
HandleProc()
void spell_pal_sacred_shield_base::HandleProc (AuraEffect const * aurEff, ProcEventInfo & eventInfo) inline private
    {
        PreventDefaultAction();
        if (eventInfo.GetTypeMask() & PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_POS)
        {
            Unit* caster = eventInfo.GetActor();
            HealInfo* healinfo = eventInfo.GetHealInfo();
            if (!healinfo || !healinfo->GetHeal())
            {
                return;
            }
            SpellInfo const* procSpell = healinfo->GetSpellInfo();
            if (!procSpell)
            {
                return;
            }
            if (caster && procSpell->SpellFamilyName == SPELLFAMILY_PALADIN &&
                    procSpell->SpellFamilyFlags.HasFlag(0x40000000) && caster->GetAuraEffect(SPELL_AURA_PROC_TRIGGER_SPELL, SPELLFAMILY_PALADIN, 3021, 0)) // need infusion of light
            {
                int32 basepoints = int32(float(healinfo->GetHeal()) / 12.0f);
                // Item - Paladin T9 Holy 4P Bonus (Flash of Light)
                if (AuraEffect const* aurEffect = caster->GetAuraEffect(67191, EFFECT_0))
                    AddPct(basepoints, aurEffect->GetAmount());
                caster->CastCustomSpell(eventInfo.GetActionTarget(), 66922, &basepoints, nullptr, nullptr, true, nullptr, aurEff, caster->GetGUID());
                return;
            }
            return;
        }
        uint32 triggered_spell_id = GetSpellInfo()->Effects[aurEff->GetEffIndex()].TriggerSpell;
        if (eventInfo.GetActionTarget()->HasSpellCooldown(triggered_spell_id))
            return;
        uint32 cooldown = eventInfo.GetProcCooldown();
        int32 basepoints = aurEff->GetAmount();
        // Item - Paladin T8 Holy 4P Bonus
        if (Unit* caster = aurEff->GetCaster())
            if (AuraEffect const* aurEffect = caster->GetAuraEffect(64895, 0))
                cooldown = aurEffect->GetAmount() * IN_MILLISECONDS;
        eventInfo.GetActionTarget()->AddSpellCooldown(triggered_spell_id, 0, cooldown);
        eventInfo.GetActionTarget()->CastCustomSpell(eventInfo.GetActionTarget(), triggered_spell_id, &basepoints, nullptr, nullptr, true, nullptr, aurEff, eventInfo.GetActionTarget()->GetGUID());
    }
References AddPct(), Unit::AddSpellCooldown(), Unit::CastCustomSpell(), EFFECT_0, SpellInfo::Effects, ProcEventInfo::GetActionTarget(), ProcEventInfo::GetActor(), AuraEffect::GetAmount(), Unit::GetAuraEffect(), AuraEffect::GetCaster(), AuraEffect::GetEffIndex(), Object::GetGUID(), HealInfo::GetHeal(), ProcEventInfo::GetHealInfo(), ProcEventInfo::GetProcCooldown(), HealInfo::GetSpellInfo(), AuraScript::GetSpellInfo(), ProcEventInfo::GetTypeMask(), flag96::HasFlag(), Unit::HasSpellCooldown(), IN_MILLISECONDS, AuraScript::PreventDefaultAction(), PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_POS, SPELL_AURA_PROC_TRIGGER_SPELL, SPELLFAMILY_PALADIN, SpellInfo::SpellFamilyFlags, and SpellInfo::SpellFamilyName.
Referenced by Register().
PrepareAuraScript()
spell_pal_sacred_shield_base::PrepareAuraScript (spell_pal_sacred_shield_base) private
Register()
void spell_pal_sacred_shield_base::Register () inline override private virtual
Implements _SpellScript.
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_pal_sacred_shield_base::CalculateAmount, EFFECT_0, SPELL_AURA_DUMMY);
        DoCheckProc += AuraCheckProcFn(spell_pal_sacred_shield_base::CheckProc);
        OnEffectProc += AuraEffectProcFn(spell_pal_sacred_shield_base::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
References AuraCheckProcFn, AuraEffectCalcAmountFn, AuraEffectProcFn, CalculateAmount(), CheckProc(), AuraScript::DoCheckProc, AuraScript::DoEffectCalcAmount, EFFECT_0, HandleProc(), AuraScript::OnEffectProc, and SPELL_AURA_DUMMY.