AzerothCore: go_ahune_ice_stone Struct Reference
go_ahune_ice_stone Struct Reference
Public Member Functions
go_ahune_ice_stone (GameObject *go)
bool GossipSelect (Player *player, uint32, uint32) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Private Attributes
InstanceScript * _instance
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_ahune_ice_stone()
go_ahune_ice_stone::go_ahune_ice_stone (GameObject * go) inline
: GameObjectAI(go), _instance(go->GetInstanceScript()) { }
Member Function Documentation
GossipSelect()
bool go_ahune_ice_stone::GossipSelect (Player * player, uint32 , uint32) inline override virtual
Reimplemented from GameObjectAI.
    {
        ClearGossipMenuFor(player);
        player->DestroyItemCount(ITEM_MAGMA_TOTEM, 1, true, false);
        player->AreaExploredOrEventHappens(QUEST_SUMMON_AHUNE); //auto rewarded
        if (Creature* ahuneBunny = _instance->GetCreature(DATA_AHUNE_BUNNY))
            ahuneBunny->AI()->DoAction(ACTION_START_EVENT);
        if (Creature* luma = _instance->GetCreature(DATA_LUMA_SKYMOTHER))
            luma->CastSpell(player, SPELL_SUMMONING_RHYME_AURA, true);
        CloseGossipMenuFor(player);
        me->Delete();
        return true;
    }
References _instance, ACTION_START_EVENT, Player::AreaExploredOrEventHappens(), ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_AHUNE_BUNNY, DATA_LUMA_SKYMOTHER, GameObject::Delete(), Player::DestroyItemCount(), InstanceScript::GetCreature(), ITEM_MAGMA_TOTEM, GameObjectAI::me, QUEST_SUMMON_AHUNE, and SPELL_SUMMONING_RHYME_AURA.
Member Data Documentation
_instance
InstanceScript* go_ahune_ice_stone::_instance private
Referenced by GossipSelect().