AzerothCore: npc_q24545_lich_king::npc_q24545_lich_kingAI Struct Reference
npc_q24545_lich_king::npc_q24545_lich_kingAI Struct Reference
Public Member Functions
npc_q24545_lich_kingAI (Creature *c)
void CleanAll (bool fromReset=true)
void Reset () override
void SetGUID (ObjectGuid guid, int32) override
void SetData (uint32 type, uint32 data) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
SummonList summons
ObjectGuid playerGUID
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_q24545_lich_kingAI()
npc_q24545_lich_king::npc_q24545_lich_kingAI::npc_q24545_lich_kingAI (Creature * c) inline
                                            : NullCreatureAI(c), summons(me)
        {
        }
Member Function Documentation
CleanAll()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::CleanAll (bool fromReset = true) inline
        {
            if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_BUNNY, 150.0f, true))
                c->RemoveAllAuras();
            if (fromReset)
            {
                if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE, 150.0f, true))
                    c->DespawnOrUnsummon(1);
                if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
                    c->RemoveAllAuras();
            }
            if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_2, 150.0f, true))
                c->DespawnOrUnsummon(1);
            if (GameObject* go = me->FindNearestGameObject(GO_SAC_LIGHTS_VENGEANCE_1, 150.0f))
                go->Delete();
            if (GameObject* go = me->FindNearestGameObject(GO_SAC_LIGHTS_VENGEANCE_2, 150.0f))
                go->Delete();
            WretchedGhoulCleaner cleaner;
            Acore::CreatureWorker<WretchedGhoulCleaner> worker(me, cleaner);
            Cell::VisitGridObjects(me, worker, 150.0f);
        }
References WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), GO_SAC_LIGHTS_VENGEANCE_1, GO_SAC_LIGHTS_VENGEANCE_2, CreatureAI::me, NPC_SAC_LIGHTS_VENGEANCE, NPC_SAC_LIGHTS_VENGEANCE_BUNNY, NPC_SAC_LIGHTS_VENGEANCE_VEH_1, NPC_SAC_LIGHTS_VENGEANCE_VEH_2, and Cell::VisitGridObjects().
Referenced by Reset(), and UpdateAI().
JustSummoned()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
        {
            summons.Summon(summon);
        }
References SummonList::Summon(), and summons.
Reset()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            events.Reset();
            events.ScheduleEvent(998, 10s);
            events.ScheduleEvent(999, 0ms);
            events.ScheduleEvent(1, 3s);
            summons.DespawnAll();
            playerGUID.Clear();
            CleanAll();
            me->setActive(false);
            me->SetWalk(true);
            me->SetVisible(false);
            me->RemoveAllAuras();
            me->InterruptNonMeleeSpells(true);
            float x, y, z, o;
            me->GetHomePosition(x, y, z, o);
            me->UpdatePosition(x, y, z, o, true);
            me->StopMovingOnCurrentPos();
            me->GetMotionMaster()->Clear();
        }
References CleanAll(), ObjectGuid::Clear(), MotionMaster::Clear(), SummonList::DespawnAll(), Creature::GetHomePosition(), Unit::GetMotionMaster(), Unit::InterruptNonMeleeSpells(), CreatureAI::me, playerGUID, Unit::RemoveAllAuras(), WorldObject::setActive(), Unit::SetVisible(), Creature::SetWalk(), Unit::StopMovingOnCurrentPos(), summons, and Unit::UpdatePosition().
Referenced by UpdateAI().
SetData()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
        {
            if (!playerGUID || type != data)
                return;
            if (data == 1)
                events.ScheduleEvent(15, 0ms);
            else if (data == 2)
            {
                if (GameObject* go = me->FindNearestGameObject(GO_SAC_LIGHTS_VENGEANCE_2, 150.0f))
                    go->Delete();
                if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
                {
                    c->CastSpell(c, SPELL_SAC_HAMMER_SHIELD, true);
                    c->CastSpell(c, SPELL_SAC_SUMMON_GO_3, true);
                    if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                        p->KnockbackFrom(c->GetPositionX(), c->GetPositionY(), 5.0f, 3.0f);
                }
                events.ScheduleEvent(18, 3s);
            }
            else if (data == 3)
            {
                if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
                {
                    c->RemoveAllAuras();
                    c->CastSpell(c, SPELL_SAC_HOLY_ZONE_AURA, true);
                    if (GameObject* go = me->FindNearestGameObject(GO_SAC_LIGHTS_VENGEANCE_3, 150.0f))
                        go->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    playerGUID.Clear();
                    events.RescheduleEvent(2, 1min);
                }
            }
        }
References ObjectGuid::Clear(), WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), ObjectAccessor::GetPlayer(), GO_FLAG_NOT_SELECTABLE, GO_SAC_LIGHTS_VENGEANCE_2, GO_SAC_LIGHTS_VENGEANCE_3, CreatureAI::me, NPC_SAC_LIGHTS_VENGEANCE_VEH_1, playerGUID, SPELL_SAC_HAMMER_SHIELD, SPELL_SAC_HOLY_ZONE_AURA, and SPELL_SAC_SUMMON_GO_3.
SetGUID()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::SetGUID (ObjectGuid guid, int32) inline override virtual
Reimplemented from UnitAI.
        {
            if (playerGUID || events.GetNextEventTime(998) || events.GetNextEventTime(2))
                return;
            me->setActive(true);
            playerGUID = guid;
            events.ScheduleEvent(2, 15min);
            events.ScheduleEvent(3, 0ms);
        }
References CreatureAI::me, playerGUID, and WorldObject::setActive().
SpellHitTarget()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
        {
            if (spell->Id == SPELL_SAC_REPEL_HAMMER && target->IsCreature())
            {
                target->CastSpell((Unit*)nullptr, SPELL_SAC_THROW_HAMMER, true);
                target->ToCreature()->DespawnOrUnsummon(1);
                if (Unit* c = target->GetVehicleBase())
                    c->RemoveAurasDueToSpell(SPELL_SAC_HOLY_ZONE_AURA);
            }
        }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), Unit::GetVehicleBase(), SpellInfo::Id, Object::IsCreature(), SPELL_SAC_HOLY_ZONE_AURA, SPELL_SAC_REPEL_HAMMER, SPELL_SAC_THROW_HAMMER, and Object::ToCreature().
SummonedCreatureDespawn()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
        {
            summons.Despawn(summon);
        }
References SummonList::Despawn(), and summons.
UpdateAI()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case 998: // ensure everything is cleaned up
                    CleanAll(false);
                    break;
                case 999: // apply holy aura
                    if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
                        if (Creature* l = me->SummonCreature(NPC_SAC_LIGHTS_VENGEANCE, *c, TEMPSUMMON_MANUAL_DESPAWN))
{
                            l->CastSpell(c, SPELL_SAC_VEHICLE_CONTROL_AURA, true);
                            c->CastSpell(c, SPELL_SAC_HOLY_ZONE_AURA, true);
                        }
                    break;
                case 1: // check player
                    if (playerGUID)
                    {
                        bool valid = false;
                        if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                            if (p->IsAlive() && p->GetPhaseMask() & 2 && p->GetExactDistSq(me) < 100.0f * 100.0f && !p->IsGameMaster())
                                valid = true;
                        if (!valid)
{
                            Reset();
                            return;
                        }
                    }
                    events.ScheduleEvent(1, 3s);
                    break;
                case 2: // reset timer
                    Reset();
                    break;
                case 3: // start event
                    if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                    {
                        me->CastSpell(p, SPELL_SAC_STUN, true);
                        me->SetVisible(true);
                        Movement::PointsArray path;
                        path.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                        path.push_back(G3D::Vector3(4825.35f, -582.99f, 164.83f));
                        path.push_back(G3D::Vector3(4813.38f, -580.94f, 162.62f));
                        me->GetMotionMaster()->MoveSplinePath(&path);
                        events.ScheduleEvent(4, 10s);
                    }
                    break;
                case 4: // talk 0
                    Talk(0);
                    events.ScheduleEvent(5, 6s);
                    break;
                case 5: // talk 1
                    Talk(1);
                    events.ScheduleEvent(6, 4s);
                    events.ScheduleEvent(7, 11s);
                    break;
                case 6: // repel hammer
                    me->CastSpell((Unit*)nullptr, SPELL_SAC_REPEL_HAMMER, false);
                    if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
                        c->CastSpell(c, SPELL_SAC_BLUE_EXPLOSION, true);
                    events.ScheduleEvent(65, 3500ms);
                    break;
                case 65: // spawn hammer go
                    if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_BUNNY, 150.0f, true))
                    {
                        c->CastSpell(c, SPELL_SAC_HOLY_ZONE_AURA, true);
                        c->CastSpell(c, SPELL_SAC_SUMMON_GO_1, true);
                    }
                    break;
                case 7: // talk 2
                    Talk(2);
                    events.ScheduleEvent(8, 8s);
                    events.ScheduleEvent(9, 11s + 500ms);
                    break;
                case 8: // summon ghouls
                    me->CastSpell((Unit*)nullptr, SPELL_SAC_SUMMON_GHOULS_AURA, false);
                    break;
                case 9: // talk 3
                    Talk(3);
                    events.ScheduleEvent(10, 10s);
                    break;
                case 10: // summon vegard
                    me->SummonCreature(NPC_SAC_VEGARD_1, 4812.12f, -586.08f, 162.49f, 3.14f, TEMPSUMMON_MANUAL_DESPAWN);
                    events.ScheduleEvent(11, 4s);
                    events.ScheduleEvent(12, 5s);
                    break;
                case 11: // vagard shield
                    if (Creature* c = me->FindNearestCreature(NPC_SAC_VEGARD_1, 50.0f, true))
                        c->CastSpell(c, SPELL_SAC_SHIELD_OF_THE_LICH_KING, false);
                    break;
                case 12: // talk 4
                    Talk(4);
                    if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                        me->CastSpell(p, SPELL_SAC_ZAP_PLAYER, false);
                    events.ScheduleEvent(13, 3500ms);
                    events.ScheduleEvent(14, 6s);
                    break;
                case 13: // despawn
                    me->CastSpell(me, SPELL_SAC_LK_DESPAWN_ANIM, false);
                    break;
                case 14: // vagard talk 0
                    me->SetVisible(false);
                    me->RemoveAllAuras();
                    if (Creature* c = me->FindNearestCreature(NPC_SAC_VEGARD_1, 50.0f, true))
                    {
                        c->AI()->Talk(0);
                        c->CastSpell(c, SPELL_SAC_VEGARD_SUMMON_GHOULS_AURA, false);
                    }
                    if (GameObject* go = me->FindNearestGameObject(GO_SAC_LIGHTS_VENGEANCE_1, 150.0f))
                        go->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    break;
                case 15: // remove light
                    if (Creature* x = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_2, 150.0f, true))
                        if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_BUNNY, 150.0f, true))
{
                            c->RemoveAurasDueToSpell(SPELL_SAC_HOLY_ZONE_AURA);
                            if (Creature* l = me->SummonCreature(NPC_SAC_LIGHTS_VENGEANCE, *c, TEMPSUMMON_MANUAL_DESPAWN))
{
                                x->SetCanFly(true);
                                x->SetDisableGravity(true);
                                x->SetHover(true);
                                x->NearTeleportTo(4812.09f, -585.55f, 172.03f, 3.75f);
                                l->EnterVehicle(x, 1);
                                //l->ClearUnitState(UNIT_STATE_ONVEHICLE);
                                l->CastSpell(l, SPELL_SAC_HOLY_BOMB_VISUAL, false);
                                l->AddAura(SPELL_SAC_HOLY_BOMB_VISUAL, l);
                                events.ScheduleEvent(16, 5s);
                            }
                        }
                    break;
                case 16: // add aura to kill ghouls
                    if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE, 150.0f, true))
                        c->CastSpell(c, SPELL_SAC_ZAP_GHOULS_AURA, true);
                    if (Creature* c = me->FindNearestCreature(NPC_SAC_VEGARD_1, 50.0f, true))
                        c->RemoveAurasDueToSpell(SPELL_SAC_VEGARD_SUMMON_GHOULS_AURA);
                    events.ScheduleEvent(17, 12s);
                    break;
                case 17: // kill vegard
                    {
                        WretchedGhoulCleaner cleaner;
                        Acore::CreatureWorker<WretchedGhoulCleaner> worker(me, cleaner);
                        Cell::VisitGridObjects(me, worker, 150.0f);
                        if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE, 150.0f, true))
                            if (Creature* v = me->FindNearestCreature(NPC_SAC_VEGARD_1, 50.0f, true))
                                if (Creature* b = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
{
                                    c->CastSpell(v, SPELL_SAC_KILL_VEGARD, true);
                                    v->SetDisplayId(11686);
                                    v->DespawnOrUnsummon(1000);
                                    b->CastSpell(b, SPELL_SAC_HOLY_BOMB_EXPLOSION, true);
                                    b->CastSpell(b, SPELL_SAC_SUMMON_GO_2, true);
                                    if (Unit* vb = c->GetVehicleBase())
{
                                        if (Unit* pass = vb->GetVehicleKit()->GetPassenger(0))
                                            if (pass->IsCreature())
                                                pass->ToCreature()->DespawnOrUnsummon(1);
                                        vb->RemoveAllAuras();
                                        vb->ToCreature()->DespawnOrUnsummon(1);
                                    }
                                    c->ToCreature()->DespawnOrUnsummon(1);
                                }
                    }
                    break;
                case 18: // summon vegard
                    me->CastSpell(me, SPELL_SAC_SUMMON_VEGARD_SKELETON, true);
                    break;
            }
        }
References Unit::CastSpell(), CleanAll(), WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), Unit::GetMotionMaster(), Vehicle::GetPassenger(), ObjectAccessor::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicleBase(), Unit::GetVehicleKit(), GO_FLAG_NOT_SELECTABLE, GO_SAC_LIGHTS_VENGEANCE_1, CreatureAI::me, MotionMaster::MoveSplinePath(), NPC_SAC_LIGHTS_VENGEANCE, NPC_SAC_LIGHTS_VENGEANCE_BUNNY, NPC_SAC_LIGHTS_VENGEANCE_VEH_1, NPC_SAC_LIGHTS_VENGEANCE_VEH_2, NPC_SAC_VEGARD_1, playerGUID, Unit::RemoveAllAuras(), Reset(), Unit::SetVisible(), SPELL_SAC_BLUE_EXPLOSION, SPELL_SAC_HOLY_BOMB_EXPLOSION, SPELL_SAC_HOLY_BOMB_VISUAL, SPELL_SAC_HOLY_ZONE_AURA, SPELL_SAC_KILL_VEGARD, SPELL_SAC_LK_DESPAWN_ANIM, SPELL_SAC_REPEL_HAMMER, SPELL_SAC_SHIELD_OF_THE_LICH_KING, SPELL_SAC_STUN, SPELL_SAC_SUMMON_GHOULS_AURA, SPELL_SAC_SUMMON_GO_1, SPELL_SAC_SUMMON_GO_2, SPELL_SAC_SUMMON_VEGARD_SKELETON, SPELL_SAC_VEGARD_SUMMON_GHOULS_AURA, SPELL_SAC_VEHICLE_CONTROL_AURA, SPELL_SAC_ZAP_GHOULS_AURA, SPELL_SAC_ZAP_PLAYER, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, and Cell::VisitGridObjects().
Member Data Documentation
events
EventMap npc_q24545_lich_king::npc_q24545_lich_kingAI::events
playerGUID
ObjectGuid npc_q24545_lich_king::npc_q24545_lich_kingAI::playerGUID
Referenced by Reset(), SetData(), SetGUID(), and UpdateAI().
summons
SummonList npc_q24545_lich_king::npc_q24545_lich_kingAI::summons
Referenced by JustSummoned(), Reset(), and SummonedCreatureDespawn().