AzerothCore: DefaultTargetSelector Struct Reference
DefaultTargetSelector Struct Reference
#include "UnitAI.h"
Public Member Functions
DefaultTargetSelector (Unit const *unit, float dist, bool playerOnly, bool withMainTank, int32 aura)
bool operator() (Unit const *target) const
Public Attributes
Unit const * me
float m_dist
Unit const * except
bool m_playerOnly
int32 m_aura
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Constructor & Destructor Documentation
DefaultTargetSelector()
DefaultTargetSelector::DefaultTargetSelector (Unit const * unit, float dist, bool playerOnly, bool withMainTank, int32 aura) inline
: me(unit), m_dist(dist), except(!withMainTank ? me->GetThreatMgr().GetCurrentVictim() : nullptr), m_playerOnly(playerOnly), m_aura(aura) {}
Member Function Documentation
operator()()
bool DefaultTargetSelector::operator() (Unit const * target) const inline
    {
        if (!me)
            return false;
        if (!target)
            return false;
        if (target == except)
            return false;
        if (m_playerOnly && (!target->IsPlayer()))
            return false;
        if (m_dist > 0.0f && !me->IsWithinCombatRange(target, m_dist))
            return false;
        if (m_dist < 0.0f && me->IsWithinCombatRange(target, -m_dist))
            return false;
        if (m_aura)
        {
            if (m_aura > 0)
            {
                if (!target->HasAura(m_aura))
                    return false;
            }
            else
            {
                if (target->HasAura(-m_aura))
                    return false;
            }
        }
        return true;
    }
References except, Unit::HasAura(), Object::IsPlayer(), Unit::IsWithinCombatRange(), m_aura, m_dist, m_playerOnly, and me.
Member Data Documentation
except
Unit const* DefaultTargetSelector::except
Referenced by operator()().
m_aura
int32 DefaultTargetSelector::m_aura
Referenced by operator()().
m_dist
float DefaultTargetSelector::m_dist
Referenced by operator()().
m_playerOnly
bool DefaultTargetSelector::m_playerOnly
Referenced by operator()().
me
Unit const* DefaultTargetSelector::me
Referenced by operator()().