AzerothCore: SystemMgr Class Reference
SystemMgr Class Reference
#include "ScriptSystem.h"
Public Types
typedef std::unordered_map< uint32, ScriptPointVector > PointMoveMap
Public Member Functions
void LoadScriptWaypoints ()
ScriptPointVector const & GetPointMoveList (uint32 creatureEntry) const
Static Public Member Functions
static SystemMgr * instance ()
Protected Attributes
PointMoveMap m_mPointMoveMap
Private Member Functions
SystemMgr ()
~SystemMgr ()
Static Private Attributes
static ScriptPointVector const _empty
Detailed Description
Member Typedef Documentation
PointMoveMap
typedef std::unordered_map<uint32, ScriptPointVector> SystemMgr::PointMoveMap
Constructor & Destructor Documentation
SystemMgr()
SystemMgr::SystemMgr () inline private
{}
~SystemMgr()
SystemMgr::~SystemMgr () inline private
{}
Member Function Documentation
GetPointMoveList()
ScriptPointVector const & SystemMgr::GetPointMoveList (uint32 creatureEntry) const inline
    {
        PointMoveMap::const_iterator itr = m_mPointMoveMap.find(creatureEntry);
        if (itr == m_mPointMoveMap.end())
            return _empty;
        return itr->second;
    }
References _empty, and m_mPointMoveMap.
instance()
SystemMgr * SystemMgr::instance () static
{
    static SystemMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadScriptWaypoints()
void SystemMgr::LoadScriptWaypoints ()
{
    uint32 oldMSTime = getMSTime();
    // Drop Existing Waypoint list
    m_mPointMoveMap.clear();
    uint64 uiCreatureCount = 0;
    // Load Waypoints
    QueryResult result = WorldDatabase.Query("SELECT COUNT(entry) FROM script_waypoint GROUP BY entry");
    if (result)
        uiCreatureCount = result->GetRowCount();
    LOG_INFO("server.loading", "Loading Script Waypoints For {} Creature(s)...", uiCreatureCount);
    //                                     0       1         2           3           4           5
    result = WorldDatabase.Query("SELECT entry, pointid, location_x, location_y, location_z, waittime FROM script_waypoint ORDER BY pointid");
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 Script Waypoints. DB table `script_waypoint` is empty.");
        LOG_INFO("server.loading", " ");
        return;
    }
    uint32 count = 0;
    do
    {
        Field* pFields = result->Fetch();
        ScriptPointMove temp;
        temp.uiCreatureEntry   = pFields[0].Get<uint32>();
        uint32 uiEntry          = temp.uiCreatureEntry;
        temp.uiPointId         = pFields[1].Get<uint32>();
        temp.fX                = pFields[2].Get<float>();
        temp.fY                = pFields[3].Get<float>();
        temp.fZ                = pFields[4].Get<float>();
        temp.uiWaitTime        = pFields[5].Get<uint32>();
        CreatureTemplate const* pCInfo = sObjectMgr->GetCreatureTemplate(temp.uiCreatureEntry);
        if (!pCInfo)
        {
            LOG_ERROR("sql.sql", "DB table script_waypoint has waypoint for non-existant creature entry {}", temp.uiCreatureEntry);
            continue;
        }
        if (!pCInfo->ScriptID)
            LOG_ERROR("sql.sql", "DB table script_waypoint has waypoint for creature entry {}, but creature does not have ScriptName defined and then useless.", temp.uiCreatureEntry);
        m_mPointMoveMap[uiEntry].push_back(temp);
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} Script Waypoint nodes in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
}
References ScriptPointMove::fX, ScriptPointMove::fY, ScriptPointMove::fZ, Field::Get(), getMSTime(), GetMSTimeDiffToNow(), LOG_ERROR, LOG_INFO, LOG_WARN, m_mPointMoveMap, sObjectMgr, ScriptPointMove::uiCreatureEntry, ScriptPointMove::uiPointId, ScriptPointMove::uiWaitTime, and WorldDatabase.
Member Data Documentation
_empty
ScriptPointVector const SystemMgr::_empty static private
Referenced by GetPointMoveList().
m_mPointMoveMap
PointMoveMap SystemMgr::m_mPointMoveMap protected
Referenced by GetPointMoveList(), and LoadScriptWaypoints().