document.write(`
  <a id="SpellEntry:GetActiveIconID" class="fn" href="../SpellEntry/GetActiveIconID.html">GetActiveIconID</a>
  <a id="SpellEntry:GetAreaGroupId" class="fn" href="../SpellEntry/GetAreaGroupId.html">GetAreaGroupId</a>
  <a id="SpellEntry:GetAttributes" class="fn" href="../SpellEntry/GetAttributes.html">GetAttributes</a>
  <a id="SpellEntry:GetAttributesEx" class="fn" href="../SpellEntry/GetAttributesEx.html">GetAttributesEx</a>
  <a id="SpellEntry:GetAttributesEx2" class="fn" href="../SpellEntry/GetAttributesEx2.html">GetAttributesEx2</a>
  <a id="SpellEntry:GetAttributesEx3" class="fn" href="../SpellEntry/GetAttributesEx3.html">GetAttributesEx3</a>
  <a id="SpellEntry:GetAttributesEx4" class="fn" href="../SpellEntry/GetAttributesEx4.html">GetAttributesEx4</a>
  <a id="SpellEntry:GetAttributesEx5" class="fn" href="../SpellEntry/GetAttributesEx5.html">GetAttributesEx5</a>
  <a id="SpellEntry:GetAttributesEx6" class="fn" href="../SpellEntry/GetAttributesEx6.html">GetAttributesEx6</a>
  <a id="SpellEntry:GetAttributesEx7" class="fn" href="../SpellEntry/GetAttributesEx7.html">GetAttributesEx7</a>
  <a id="SpellEntry:GetAuraInterruptFlags" class="fn" href="../SpellEntry/GetAuraInterruptFlags.html">GetAuraInterruptFlags</a>
  <a id="SpellEntry:GetBaseLevel" class="fn" href="../SpellEntry/GetBaseLevel.html">GetBaseLevel</a>
  <a id="SpellEntry:GetCasterAuraSpell" class="fn" href="../SpellEntry/GetCasterAuraSpell.html">GetCasterAuraSpell</a>
  <a id="SpellEntry:GetCasterAuraState" class="fn" href="../SpellEntry/GetCasterAuraState.html">GetCasterAuraState</a>
  <a id="SpellEntry:GetCasterAuraStateNot" class="fn" href="../SpellEntry/GetCasterAuraStateNot.html">GetCasterAuraStateNot</a>
  <a id="SpellEntry:GetCastingTimeIndex" class="fn" href="../SpellEntry/GetCastingTimeIndex.html">GetCastingTimeIndex</a>
  <a id="SpellEntry:GetCategory" class="fn" href="../SpellEntry/GetCategory.html">GetCategory</a>
  <a id="SpellEntry:GetCategoryRecoveryTime" class="fn" href="../SpellEntry/GetCategoryRecoveryTime.html">GetCategoryRecoveryTime</a>
  <a id="SpellEntry:GetChannelInterruptFlags" class="fn" href="../SpellEntry/GetChannelInterruptFlags.html">GetChannelInterruptFlags</a>
  <a id="SpellEntry:GetDispel" class="fn" href="../SpellEntry/GetDispel.html">GetDispel</a>
  <a id="SpellEntry:GetDmgClass" class="fn" href="../SpellEntry/GetDmgClass.html">GetDmgClass</a>
  <a id="SpellEntry:GetDurationIndex" class="fn" href="../SpellEntry/GetDurationIndex.html">GetDurationIndex</a>
  <a id="SpellEntry:GetEffect" class="fn" href="../SpellEntry/GetEffect.html">GetEffect</a>
  <a id="SpellEntry:GetEffectAmplitude" class="fn" href="../SpellEntry/GetEffectAmplitude.html">GetEffectAmplitude</a>
  <a id="SpellEntry:GetEffectApplyAuraName" class="fn" href="../SpellEntry/GetEffectApplyAuraName.html">GetEffectApplyAuraName</a>
  <a id="SpellEntry:GetEffectBasePoints" class="fn" href="../SpellEntry/GetEffectBasePoints.html">GetEffectBasePoints</a>
  <a id="SpellEntry:GetEffectBonusMultiplier" class="fn" href="../SpellEntry/GetEffectBonusMultiplier.html">GetEffectBonusMultiplier</a>
  <a id="SpellEntry:GetEffectChainTarget" class="fn" href="../SpellEntry/GetEffectChainTarget.html">GetEffectChainTarget</a>
  <a id="SpellEntry:GetEffectDamageMultiplier" class="fn" href="../SpellEntry/GetEffectDamageMultiplier.html">GetEffectDamageMultiplier</a>
  <a id="SpellEntry:GetEffectDieSides" class="fn" href="../SpellEntry/GetEffectDieSides.html">GetEffectDieSides</a>
  <a id="SpellEntry:GetEffectImplicitTargetA" class="fn" href="../SpellEntry/GetEffectImplicitTargetA.html">GetEffectImplicitTargetA</a>
  <a id="SpellEntry:GetEffectImplicitTargetB" class="fn" href="../SpellEntry/GetEffectImplicitTargetB.html">GetEffectImplicitTargetB</a>
  <a id="SpellEntry:GetEffectItemType" class="fn" href="../SpellEntry/GetEffectItemType.html">GetEffectItemType</a>
  <a id="SpellEntry:GetEffectMechanic" class="fn" href="../SpellEntry/GetEffectMechanic.html">GetEffectMechanic</a>
  <a id="SpellEntry:GetEffectMiscValue" class="fn" href="../SpellEntry/GetEffectMiscValue.html">GetEffectMiscValue</a>
  <a id="SpellEntry:GetEffectMiscValueB" class="fn" href="../SpellEntry/GetEffectMiscValueB.html">GetEffectMiscValueB</a>
  <a id="SpellEntry:GetEffectPointsPerComboPoint" class="fn" href="../SpellEntry/GetEffectPointsPerComboPoint.html">GetEffectPointsPerComboPoint</a>
  <a id="SpellEntry:GetEffectRadiusIndex" class="fn" href="../SpellEntry/GetEffectRadiusIndex.html">GetEffectRadiusIndex</a>
  <a id="SpellEntry:GetEffectRealPointsPerLevel" class="fn" href="../SpellEntry/GetEffectRealPointsPerLevel.html">GetEffectRealPointsPerLevel</a>
  <a id="SpellEntry:GetEffectSpellClassMask" class="fn" href="../SpellEntry/GetEffectSpellClassMask.html">GetEffectSpellClassMask</a>
  <a id="SpellEntry:GetEffectTriggerSpell" class="fn" href="../SpellEntry/GetEffectTriggerSpell.html">GetEffectTriggerSpell</a>
  <a id="SpellEntry:GetEffectValueMultiplier" class="fn" href="../SpellEntry/GetEffectValueMultiplier.html">GetEffectValueMultiplier</a>
  <a id="SpellEntry:GetEquippedItemClass" class="fn" href="../SpellEntry/GetEquippedItemClass.html">GetEquippedItemClass</a>
  <a id="SpellEntry:GetEquippedItemInventoryTypeMask" class="fn" href="../SpellEntry/GetEquippedItemInventoryTypeMask.html">GetEquippedItemInventoryTypeMask</a>
  <a id="SpellEntry:GetEquippedItemSubClassMask" class="fn" href="../SpellEntry/GetEquippedItemSubClassMask.html">GetEquippedItemSubClassMask</a>
  <a id="SpellEntry:GetExcludeCasterAuraSpell" class="fn" href="../SpellEntry/GetExcludeCasterAuraSpell.html">GetExcludeCasterAuraSpell</a>
  <a id="SpellEntry:GetExcludeTargetAuraSpell" class="fn" href="../SpellEntry/GetExcludeTargetAuraSpell.html">GetExcludeTargetAuraSpell</a>
  <a id="SpellEntry:GetFacingCasterFlags" class="fn" href="../SpellEntry/GetFacingCasterFlags.html">GetFacingCasterFlags</a>
  <a id="SpellEntry:GetId" class="fn" href="../SpellEntry/GetId.html">GetId</a>
  <a id="SpellEntry:GetInterruptFlags" class="fn" href="../SpellEntry/GetInterruptFlags.html">GetInterruptFlags</a>
  <a id="SpellEntry:GetManaCost" class="fn" href="../SpellEntry/GetManaCost.html">GetManaCost</a>
  <a id="SpellEntry:GetManaCostPercentage" class="fn" href="../SpellEntry/GetManaCostPercentage.html">GetManaCostPercentage</a>
  <a id="SpellEntry:GetManaCostPerlevel" class="fn" href="../SpellEntry/GetManaCostPerlevel.html">GetManaCostPerlevel</a>
  <a id="SpellEntry:GetManaPerSecond" class="fn" href="../SpellEntry/GetManaPerSecond.html">GetManaPerSecond</a>
  <a id="SpellEntry:GetManaPerSecondPerLevel" class="fn" href="../SpellEntry/GetManaPerSecondPerLevel.html">GetManaPerSecondPerLevel</a>
  <a id="SpellEntry:GetMaxAffectedTargets" class="fn" href="../SpellEntry/GetMaxAffectedTargets.html">GetMaxAffectedTargets</a>
  <a id="SpellEntry:GetMaxLevel" class="fn" href="../SpellEntry/GetMaxLevel.html">GetMaxLevel</a>
  <a id="SpellEntry:GetMaxTargetLevel" class="fn" href="../SpellEntry/GetMaxTargetLevel.html">GetMaxTargetLevel</a>
  <a id="SpellEntry:GetMechanic" class="fn" href="../SpellEntry/GetMechanic.html">GetMechanic</a>
  <a id="SpellEntry:GetPowerType" class="fn" href="../SpellEntry/GetPowerType.html">GetPowerType</a>
  <a id="SpellEntry:GetPreventionType" class="fn" href="../SpellEntry/GetPreventionType.html">GetPreventionType</a>
  <a id="SpellEntry:GetProcChance" class="fn" href="../SpellEntry/GetProcChance.html">GetProcChance</a>
  <a id="SpellEntry:GetProcCharges" class="fn" href="../SpellEntry/GetProcCharges.html">GetProcCharges</a>
  <a id="SpellEntry:GetProcFlags" class="fn" href="../SpellEntry/GetProcFlags.html">GetProcFlags</a>
  <a id="SpellEntry:GetRangeIndex" class="fn" href="../SpellEntry/GetRangeIndex.html">GetRangeIndex</a>
  <a id="SpellEntry:GetRank" class="fn" href="../SpellEntry/GetRank.html">GetRank</a>
  <a id="SpellEntry:GetReagent" class="fn" href="../SpellEntry/GetReagent.html">GetReagent</a>
  <a id="SpellEntry:GetReagentCount" class="fn" href="../SpellEntry/GetReagentCount.html">GetReagentCount</a>
  <a id="SpellEntry:GetRecoveryTime" class="fn" href="../SpellEntry/GetRecoveryTime.html">GetRecoveryTime</a>
  <a id="SpellEntry:GetRequiresSpellFocus" class="fn" href="../SpellEntry/GetRequiresSpellFocus.html">GetRequiresSpellFocus</a>
  <a id="SpellEntry:GetRuneCostID" class="fn" href="../SpellEntry/GetRuneCostID.html">GetRuneCostID</a>
  <a id="SpellEntry:GetSchoolMask" class="fn" href="../SpellEntry/GetSchoolMask.html">GetSchoolMask</a>
  <a id="SpellEntry:GetSpeed" class="fn" href="../SpellEntry/GetSpeed.html">GetSpeed</a>
  <a id="SpellEntry:GetSpellFamilyFlags" class="fn" href="../SpellEntry/GetSpellFamilyFlags.html">GetSpellFamilyFlags</a>
  <a id="SpellEntry:GetSpellFamilyName" class="fn" href="../SpellEntry/GetSpellFamilyName.html">GetSpellFamilyName</a>
  <a id="SpellEntry:GetSpellIconID" class="fn" href="../SpellEntry/GetSpellIconID.html">GetSpellIconID</a>
  <a id="SpellEntry:GetSpellLevel" class="fn" href="../SpellEntry/GetSpellLevel.html">GetSpellLevel</a>
  <a id="SpellEntry:GetSpellName" class="fn" href="../SpellEntry/GetSpellName.html">GetSpellName</a>
  <a id="SpellEntry:GetSpellPriority" class="fn" href="../SpellEntry/GetSpellPriority.html">GetSpellPriority</a>
  <a id="SpellEntry:GetSpellVisual" class="fn" href="../SpellEntry/GetSpellVisual.html">GetSpellVisual</a>
  <a id="SpellEntry:GetStackAmount" class="fn" href="../SpellEntry/GetStackAmount.html">GetStackAmount</a>
  <a id="SpellEntry:GetStances" class="fn" href="../SpellEntry/GetStances.html">GetStances</a>
  <a id="SpellEntry:GetStancesNot" class="fn" href="../SpellEntry/GetStancesNot.html">GetStancesNot</a>
  <a id="SpellEntry:GetStartRecoveryCategory" class="fn" href="../SpellEntry/GetStartRecoveryCategory.html">GetStartRecoveryCategory</a>
  <a id="SpellEntry:GetStartRecoveryTime" class="fn" href="../SpellEntry/GetStartRecoveryTime.html">GetStartRecoveryTime</a>
  <a id="SpellEntry:GetTargetAuraSpell" class="fn" href="../SpellEntry/GetTargetAuraSpell.html">GetTargetAuraSpell</a>
  <a id="SpellEntry:GetTargetAuraState" class="fn" href="../SpellEntry/GetTargetAuraState.html">GetTargetAuraState</a>
  <a id="SpellEntry:GetTargetAuraStateNot" class="fn" href="../SpellEntry/GetTargetAuraStateNot.html">GetTargetAuraStateNot</a>
  <a id="SpellEntry:GetTargetCreatureType" class="fn" href="../SpellEntry/GetTargetCreatureType.html">GetTargetCreatureType</a>
  <a id="SpellEntry:GetTargets" class="fn" href="../SpellEntry/GetTargets.html">GetTargets</a>
  <a id="SpellEntry:GetTotem" class="fn" href="../SpellEntry/GetTotem.html">GetTotem</a>
  <a id="SpellEntry:GetTotemCategory" class="fn" href="../SpellEntry/GetTotemCategory.html">GetTotemCategory</a>
`);