AzerothCore: npc_vh_sinclari Class Reference
npc_vh_sinclari Class Reference
Public Member Functions
npc_vh_sinclari ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_vh_sinclari()
npc_vh_sinclari::npc_vh_sinclari () inline
: CreatureScript("npc_vh_sinclari") { }
Member Function Documentation
OnGossipHello()
bool npc_vh_sinclari::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (InstanceScript* pInstance = creature->GetInstanceScript())
            switch (pInstance->GetData(DATA_ENCOUNTER_STATUS))
            {
                case NOT_STARTED:
                    AddGossipItemFor(player, GOSSIP_MENU_ITEM, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                    AddGossipItemFor(player, GOSSIP_MENU_START_EVENT, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                    SendGossipMenuFor(player, NPC_TEXT_SINCLARI_IN, creature->GetGUID());
                    break;
                case IN_PROGRESS:
                    AddGossipItemFor(player, GOSSIP_MENU_LATE_JOIN, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                    SendGossipMenuFor(player, NPC_TEXT_SINCLARI_LATE_JOIN, creature->GetGUID());
                    break;
                default: // DONE or invalid
                    SendGossipMenuFor(player, NPC_TEXT_SINCLARI_DONE, creature->GetGUID());
            }
        return true;
    }
References AddGossipItemFor(), DATA_ENCOUNTER_STATUS, Object::GetGUID(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, GOSSIP_MENU_ITEM, GOSSIP_MENU_LATE_JOIN, GOSSIP_MENU_START_EVENT, GOSSIP_SENDER_MAIN, IN_PROGRESS, NOT_STARTED, NPC_TEXT_SINCLARI_DONE, NPC_TEXT_SINCLARI_IN, NPC_TEXT_SINCLARI_LATE_JOIN, and SendGossipMenuFor().
OnGossipSelect()
bool npc_vh_sinclari::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
    {
        ClearGossipMenuFor(player);
        switch (uiAction)
        {
            case GOSSIP_ACTION_INFO_DEF+1:
                CloseGossipMenuFor(player);
                if (InstanceScript* pInstance = creature->GetInstanceScript())
                    pInstance->SetData(DATA_START_INSTANCE, 1);
                break;
            case GOSSIP_ACTION_INFO_DEF+2:
                SendGossipMenuFor(player, NPC_TEXT_SINCLARI_ITEM, creature->GetGUID());
                break;
            case GOSSIP_ACTION_INFO_DEF+3:
                player->NearTeleportTo(playerTeleportPosition.GetPositionX(), playerTeleportPosition.GetPositionY(), playerTeleportPosition.GetPositionZ(), playerTeleportPosition.GetOrientation(), true);
                CloseGossipMenuFor(player);
                break;
        }
        return true;
    }
References ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_START_INSTANCE, Object::GetGUID(), WorldObject::GetInstanceScript(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GOSSIP_ACTION_INFO_DEF, Unit::NearTeleportTo(), NPC_TEXT_SINCLARI_ITEM, playerTeleportPosition, and SendGossipMenuFor().