AzerothCore: npc_crok_scourgebane::npc_crok_scourgebaneAI Struct Reference
npc_crok_scourgebane::npc_crok_scourgebaneAI Struct Reference
Public Member Functions
npc_crok_scourgebaneAI (Creature *creature)
void Reset () override
void DoAction (int32 action) override
void SetGUID (ObjectGuid guid, int32 type) override
void WaypointReached (uint32 waypointId) override
void WaypointStart (uint32 waypointId) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateEscortAI (uint32) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
bool CanAIAttack (Unit const *target) const override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
GuidSet _aliveTrash
InstanceScript * _instance
uint32 _currentWPid
uint32 _wipeCheckTimer
bool _handledWP4
bool _isEventDone
bool _didUnderTenPercentText
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_crok_scourgebaneAI()
npc_crok_scourgebane::npc_crok_scourgebaneAI::npc_crok_scourgebaneAI (Creature * creature) inline
                                                   : npc_escortAI(creature), _instance(creature->GetInstanceScript())
        {
            SetDespawnAtEnd(false);
            SetDespawnAtFar(false);
            _isEventDone = _instance->GetBossState(DATA_SISTER_SVALNA) == DONE;
        }
References _instance, _isEventDone, DATA_SISTER_SVALNA, DONE, InstanceScript::GetBossState(), npc_escortAI::SetDespawnAtEnd(), and npc_escortAI::SetDespawnAtFar().
Member Function Documentation
CanAIAttack()
bool npc_crok_scourgebane::npc_crok_scourgebaneAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
        {
            // do not see targets inside Frostwing Halls when we are not there
            return !target->IsPlayer() && (me->GetPositionY() > 2660.0f) == (target->GetPositionY() > 2660.0f) && target->GetEntry() != NPC_SINDRAGOSA;
        }
References Object::GetEntry(), Position::GetPositionY(), Object::IsPlayer(), ScriptedAI::me, and NPC_SINDRAGOSA.
DamageTaken()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (HealthBelowPct(10))
            {
                if (!_didUnderTenPercentText)
                {
                    _didUnderTenPercentText = true;
                    if (me->GetVictim() && me->GetVictim()->GetEntry() == NPC_SISTER_SVALNA)
                        Talk(SAY_CROK_WEAKENING_SVALNA);
                    else
                        Talk(SAY_CROK_WEAKENING_GAUNTLET);
                }
                damage = 0;
                me->CastSpell(me, SPELL_ICEBOUND_ARMOR, true);
                _events.ScheduleEvent(EVENT_HEALTH_CHECK, 1s);
            }
        }
References _didUnderTenPercentText, _events, Unit::CastSpell(), EVENT_HEALTH_CHECK, Object::GetEntry(), Unit::GetVictim(), ScriptedAI::HealthBelowPct(), ScriptedAI::me, NPC_SISTER_SVALNA, SAY_CROK_WEAKENING_GAUNTLET, SAY_CROK_WEAKENING_SVALNA, EventMap::ScheduleEvent(), and SPELL_ICEBOUND_ARMOR.
DoAction()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == ACTION_START_GAUNTLET)
            {
                if (_isEventDone || me->isActiveObject() || !me->IsAlive())
                    return;
                me->setActive(true);
                me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->SetImmuneToAll(true);
                // Load Grid with Sister Svalna
                me->GetMap()->LoadGrid(4356.71f, 2484.33f);
                if (Creature* svalna = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_SISTER_SVALNA)))
                    svalna->AI()->DoAction(ACTION_START_GAUNTLET);
                for (uint32 i = 0; i < 4; ++i)
                    if (Creature* crusader = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_CAPTAIN_ARNATH + i)))
                        crusader->AI()->DoAction(ACTION_START_GAUNTLET);
                Talk(SAY_CROK_INTRO_1);
                _events.ScheduleEvent(EVENT_ARNATH_INTRO_2, 7s);
                _events.ScheduleEvent(EVENT_CROK_INTRO_3, 14s);
                _events.ScheduleEvent(EVENT_START_PATHING, 37s);
            }
            else if (action == ACTION_RESET_EVENT)
            {
                _isEventDone = _instance->GetBossState(DATA_SISTER_SVALNA) == DONE;
                me->setActive(false);
                _aliveTrash.clear();
                _currentWPid = 0;
                _handledWP4 = false;
                me->CombatStop();
                me->GetThreatMgr().ClearAllThreat();
            }
        }
References _aliveTrash, _currentWPid, _events, _handledWP4, _instance, _isEventDone, ACTION_RESET_EVENT, ACTION_START_GAUNTLET, ThreatMgr::ClearAllThreat(), Unit::CombatStop(), DATA_CAPTAIN_ARNATH, DATA_SISTER_SVALNA, DONE, EVENT_ARNATH_INTRO_2, EVENT_CROK_INTRO_3, EVENT_START_PATHING, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetThreatMgr(), WorldObject::isActiveObject(), Unit::IsAlive(), Map::LoadGrid(), ScriptedAI::me, SAY_CROK_INTRO_1, EventMap::ScheduleEvent(), WorldObject::setActive(), Unit::SetImmuneToAll(), Unit::SetUnitFlag(), and UNIT_FLAG_NON_ATTACKABLE.
Reset()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            me->SetReactState(REACT_DEFENSIVE);
            _didUnderTenPercentText = false;
            _wipeCheckTimer = 3000;
            _handledWP4 = false;
            _events.Reset();
            _events.ScheduleEvent(EVENT_SCOURGE_STRIKE, 7500ms, 12s + 500ms);
            _events.ScheduleEvent(EVENT_DEATH_STRIKE, 25s, 30s);
        }
References _didUnderTenPercentText, _events, _handledWP4, _wipeCheckTimer, EVENT_DEATH_STRIKE, EVENT_SCOURGE_STRIKE, ScriptedAI::me, REACT_DEFENSIVE, EventMap::Reset(), EventMap::ScheduleEvent(), and Creature::SetReactState().
SetGUID()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::SetGUID (ObjectGuid guid, int32 type) inline override virtual
Reimplemented from UnitAI.
        {
            if (type == ACTION_VRYKUL_DEATH)
            {
                _aliveTrash.erase(guid);
                if (_aliveTrash.empty())
                {
                    SetEscortPaused(false);
                    if (_currentWPid == 4 && !_handledWP4)
                    {
                        _handledWP4 = true;
                        Talk(SAY_CROK_FINAL_WP);
                        if (Creature* svalna = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_SISTER_SVALNA)))
                            svalna->AI()->DoAction(ACTION_RESURRECT_CAPTAINS);
                    }
                }
            }
        }
References _aliveTrash, _currentWPid, _handledWP4, _instance, ACTION_RESURRECT_CAPTAINS, ACTION_VRYKUL_DEATH, DATA_SISTER_SVALNA, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), ScriptedAI::me, SAY_CROK_FINAL_WP, and npc_escortAI::SetEscortPaused().
UpdateAI()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from npc_escortAI.
        {
            npc_escortAI::UpdateAI(diff);
            //Position pos = me->GetHomePosition();
            if (!me->isActiveObject()/* && me->GetExactDist(&pos) < 5.0f*/) // during event
                return;
            if (_wipeCheckTimer <= diff)
            {
                _wipeCheckTimer = 3000;
                Player* player = nullptr;
                Acore::AnyPlayerInObjectRangeCheck check(me, 140.0f);
                Acore::PlayerSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(me, player, check);
                Cell::VisitWorldObjects(me, searcher, 140.0f);
                // wipe
                if (!player || me->GetExactDist(4357.0f, 2606.0f, 350.0f) > 125.0f)
                {
                    //Talk(SAY_CROK_DEATH);
                    FrostwingGauntletRespawner respawner;
                    Acore::CreatureWorker<FrostwingGauntletRespawner> worker(me, respawner);
                    Cell::VisitGridObjects(me, worker, 333.0f);
                    return;
                }
            }
            else
                _wipeCheckTimer -= diff;
            UpdateVictim();
            _events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (_events.ExecuteEvent())
            {
                case EVENT_ARNATH_INTRO_2:
                    if (Creature* arnath = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_CAPTAIN_ARNATH)))
                        arnath->AI()->Talk(SAY_ARNATH_INTRO_2);
                    break;
                case EVENT_CROK_INTRO_3:
                    Talk(SAY_CROK_INTRO_3);
                    break;
                case EVENT_START_PATHING:
                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->SetImmuneToAll(false);
                    Start(true, true);
                    break;
                case EVENT_SCOURGE_STRIKE:
                    DoCastVictim(SPELL_SCOURGE_STRIKE);
                    _events.ScheduleEvent(EVENT_SCOURGE_STRIKE, 10s, 14s);
                    break;
                case EVENT_DEATH_STRIKE:
                    if (HealthBelowPct(20))
                        DoCastVictim(SPELL_DEATH_STRIKE);
                    _events.ScheduleEvent(EVENT_DEATH_STRIKE, 5s, 10s);
                    break;
                case EVENT_HEALTH_CHECK:
                    if (HealthAbovePct(25))
                    {
                        me->RemoveAurasDueToSpell(SPELL_ICEBOUND_ARMOR);
                        _didUnderTenPercentText = false;
                    }
                    else
                    {
                        Unit::DealHeal(me, me, me->CountPctFromMaxHealth(3));
                        _events.ScheduleEvent(EVENT_HEALTH_CHECK, 1s);
                    }
                    break;
                default:
                    break;
            }
            DoMeleeAttackIfReady();
        }
References _didUnderTenPercentText, _events, _instance, _wipeCheckTimer, Unit::CountPctFromMaxHealth(), DATA_CAPTAIN_ARNATH, Unit::DealHeal(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EVENT_ARNATH_INTRO_2, EVENT_CROK_INTRO_3, EVENT_DEATH_STRIKE, EVENT_HEALTH_CHECK, EVENT_SCOURGE_STRIKE, EVENT_START_PATHING, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), Position::GetExactDist(), InstanceScript::GetGuidData(), Unit::HasUnitState(), ScriptedAI::HealthAbovePct(), ScriptedAI::HealthBelowPct(), WorldObject::isActiveObject(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), Unit::RemoveUnitFlag(), SAY_ARNATH_INTRO_2, SAY_CROK_INTRO_3, EventMap::ScheduleEvent(), Unit::SetImmuneToAll(), SPELL_DEATH_STRIKE, SPELL_ICEBOUND_ARMOR, SPELL_SCOURGE_STRIKE, npc_escortAI::Start(), UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, EventMap::Update(), npc_escortAI::UpdateAI(), CreatureAI::UpdateVictim(), Cell::VisitGridObjects(), and Cell::VisitWorldObjects().
UpdateEscortAI()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateEscortAI (uint32) inline override virtual
Reimplemented from npc_escortAI.
{}
WaypointReached()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
        {
            switch (waypointId)
            {
                // pause pathing until trash pack is cleared
                case 0:
                    Talk(SAY_CROK_COMBAT_WP_0);
                    if (!_aliveTrash.empty())
                        SetEscortPaused(true);
                    break;
                case 1:
                    Talk(SAY_CROK_COMBAT_WP_1);
                    if (!_aliveTrash.empty())
                        SetEscortPaused(true);
                    break;
                case 2:
                    if (!_aliveTrash.empty())
                        SetEscortPaused(true);
                    break;
                case 4:
                    if (_aliveTrash.empty() && !_handledWP4)
                    {
                        _handledWP4 = true;
                        Talk(SAY_CROK_FINAL_WP);
                        if (Creature* svalna = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_SISTER_SVALNA)))
                            svalna->AI()->DoAction(ACTION_RESURRECT_CAPTAINS);
                    }
                    break;
                default:
                    break;
            }
        }
References _aliveTrash, _handledWP4, _instance, ACTION_RESURRECT_CAPTAINS, DATA_SISTER_SVALNA, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), ScriptedAI::me, SAY_CROK_COMBAT_WP_0, SAY_CROK_COMBAT_WP_1, SAY_CROK_FINAL_WP, and npc_escortAI::SetEscortPaused().
WaypointStart()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointStart (uint32 waypointId) inline override virtual
Reimplemented from npc_escortAI.
        {
            _currentWPid = waypointId;
            float minY = 0.0f;
            switch (waypointId)
            {
                case 0:
                    minY = 2600.0f;
                    break;
                case 1:
                    minY = 2550.0f;
                    if (Creature* svalna = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_SISTER_SVALNA)))
                        svalna->AI()->DoAction(ACTION_KILL_CAPTAIN);
                    break;
                case 2:
                    minY = 2515.0f;
                    if (Creature* svalna = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_SISTER_SVALNA)))
                        svalna->AI()->DoAction(ACTION_KILL_CAPTAIN);
                    break;
                case 4:
                    minY = 2475.0f;
                    break;
                default:
                    break;
            }
            if (minY)
            {
                // get all nearby vrykul
                std::list<Creature*> temp;
                FrostwingVrykulSearcher check(me, 150.0f);
                Acore::CreatureListSearcher<FrostwingVrykulSearcher> searcher(me, temp, check);
                Cell::VisitGridObjects(me, searcher, 150.0f);
                _aliveTrash.clear();
                for (std::list<Creature*>::iterator itr = temp.begin(); itr != temp.end(); ++itr)
                    if ((*itr)->GetHomePosition().GetPositionY() > minY)
                        _aliveTrash.insert((*itr)->GetGUID());
            }
        }
References _aliveTrash, _currentWPid, _instance, ACTION_KILL_CAPTAIN, DATA_SISTER_SVALNA, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), ScriptedAI::me, and Cell::VisitGridObjects().
Member Data Documentation
_aliveTrash
GuidSet npc_crok_scourgebane::npc_crok_scourgebaneAI::_aliveTrash private
Referenced by DoAction(), SetGUID(), WaypointReached(), and WaypointStart().
_currentWPid
uint32 npc_crok_scourgebane::npc_crok_scourgebaneAI::_currentWPid private
Referenced by DoAction(), SetGUID(), and WaypointStart().
_didUnderTenPercentText
bool npc_crok_scourgebane::npc_crok_scourgebaneAI::_didUnderTenPercentText private
Referenced by DamageTaken(), Reset(), and UpdateAI().
_events
EventMap npc_crok_scourgebane::npc_crok_scourgebaneAI::_events private
Referenced by DamageTaken(), DoAction(), Reset(), and UpdateAI().
_handledWP4
bool npc_crok_scourgebane::npc_crok_scourgebaneAI::_handledWP4 private
Referenced by DoAction(), Reset(), SetGUID(), and WaypointReached().
_instance
InstanceScript* npc_crok_scourgebane::npc_crok_scourgebaneAI::_instance private
Referenced by DoAction(), npc_crok_scourgebaneAI(), SetGUID(), UpdateAI(), WaypointReached(), and WaypointStart().
_isEventDone
bool npc_crok_scourgebane::npc_crok_scourgebaneAI::_isEventDone private
Referenced by DoAction(), and npc_crok_scourgebaneAI().
_wipeCheckTimer
uint32 npc_crok_scourgebane::npc_crok_scourgebaneAI::_wipeCheckTimer private
Referenced by Reset(), and UpdateAI().