AzerothCore: DefileTargetSelector Struct Reference
DefileTargetSelector Struct Reference
Public Member Functions
DefileTargetSelector (Creature *source)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
Detailed Description
Constructor & Destructor Documentation
DefileTargetSelector()
DefileTargetSelector::DefileTargetSelector (Creature * source) inline
: _source(source) { }
Member Function Documentation
operator()()
bool DefileTargetSelector::operator() (Unit const * target) const inline
    {
        if (!target)
            return false;
        if (!target->IsAlive())
            return false;
        if (!target->IsPlayer())
            return false;
        if (_source->GetExactDist(target) > 100.0f)
            return false;
        if (target->HasAura(SPELL_HARVEST_SOUL_VALKYR) || target->HasAura(SPELL_VALKYR_TARGET_SEARCH))
            return false;
        if (!_source->IsWithinLOSInMap(target))
            return false;
        return true;
    }
References _source, Position::GetExactDist(), Unit::HasAura(), Unit::IsAlive(), Object::IsPlayer(), WorldObject::IsWithinLOSInMap(), SPELL_HARVEST_SOUL_VALKYR, and SPELL_VALKYR_TARGET_SEARCH.
Member Data Documentation
_source
Creature const* DefileTargetSelector::_source private
Referenced by operator()().