AzerothCore: LinkedListElement Class Reference
LinkedListElement Class Reference
#include "LinkedList.h"
Public Member Functions
LinkedListElement ()=default
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Private Attributes
LinkedListElement * iNext {nullptr}
LinkedListElement * iPrev {nullptr}
Friends
class LinkedListHead
Detailed Description
Constructor & Destructor Documentation
LinkedListElement()
LinkedListElement::LinkedListElement () default
~LinkedListElement()
LinkedListElement::~LinkedListElement () inline
{ delink(); }
References delink().
Member Function Documentation
delink()
void LinkedListElement::delink () inline
    {
        if (isInList())
        {
            iNext->iPrev = iPrev;
            iPrev->iNext = iNext;
            iNext = nullptr;
            iPrev = nullptr;
        }
    }
References iNext, iPrev, and isInList().
Referenced by RefMgr< TO, FROM >::clearReferences(), Reference< TO, FROM >::invalidate(), Reference< TO, FROM >::unlink(), and ~LinkedListElement().
hasNext()
bool LinkedListElement::hasNext () const inline
{ return (iNext && iNext->iNext != nullptr); }
References iNext.
Referenced by next().
hasPrev()
bool LinkedListElement::hasPrev () const inline
{ return (iPrev && iPrev->iPrev != nullptr); }
References iPrev.
Referenced by prev().
insertAfter()
void LinkedListElement::insertAfter (LinkedListElement * pElem) inline
    {
        pElem->iPrev = this;
        pElem->iNext = iNext;
        iNext->iPrev = pElem;
        iNext = pElem;
    }
References iNext, and iPrev.
Referenced by LinkedListHead::insertFirst().
insertBefore()
void LinkedListElement::insertBefore (LinkedListElement * pElem) inline
    {
        pElem->iNext = this;
        pElem->iPrev = iPrev;
        iPrev->iNext = pElem;
        iPrev = pElem;
    }
References iNext, and iPrev.
Referenced by LinkedListHead::insertLast().
isInList()
bool LinkedListElement::isInList () const inline
{ return (iNext != nullptr && iPrev != nullptr); }
References iNext, and iPrev.
Referenced by delink(), and LinkedListHead::IsEmpty().
next() [1/2]
LinkedListElement * LinkedListElement::next () inline
{ return hasNext() ? iNext : nullptr; }
References hasNext(), and iNext.
Referenced by LinkedListHead::getSize(), and Reference< TO, FROM >::next().
next() [2/2]
LinkedListElement const * LinkedListElement::next () const inline
{ return hasNext() ? iNext : nullptr; }
References hasNext(), and iNext.
nocheck_next() [1/2]
LinkedListElement * LinkedListElement::nocheck_next () inline
{ return iNext; }
References iNext.
Referenced by Reference< TO, FROM >::nocheck_next().
nocheck_next() [2/2]
LinkedListElement const * LinkedListElement::nocheck_next () const inline
{ return iNext; }
References iNext.
nocheck_prev() [1/2]
LinkedListElement * LinkedListElement::nocheck_prev () inline
{ return iPrev; }
References iPrev.
Referenced by Reference< TO, FROM >::nocheck_prev().
nocheck_prev() [2/2]
LinkedListElement const * LinkedListElement::nocheck_prev () const inline
{ return iPrev; }
References iPrev.
prev() [1/2]
LinkedListElement * LinkedListElement::prev () inline
{ return hasPrev() ? iPrev : nullptr; }
References hasPrev(), and iPrev.
Referenced by Reference< TO, FROM >::prev().
prev() [2/2]
LinkedListElement const * LinkedListElement::prev () const inline
{ return hasPrev() ? iPrev : nullptr; }
References hasPrev(), and iPrev.
Friends And Related Function Documentation
LinkedListHead
friend class LinkedListHead friend
Member Data Documentation
iNext
LinkedListElement* LinkedListElement::iNext {nullptr} private
Referenced by delink(), LinkedListHead::getFirst(), hasNext(), insertAfter(), insertBefore(), LinkedListHead::IsEmpty(), isInList(), LinkedListHead::LinkedListHead(), next(), and nocheck_next().
iPrev
LinkedListElement* LinkedListElement::iPrev {nullptr} private
Referenced by delink(), LinkedListHead::getLast(), hasPrev(), insertAfter(), insertBefore(), isInList(), LinkedListHead::LinkedListHead(), nocheck_prev(), and prev().