AzerothCore: npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI Struct Reference
npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI Struct Reference
Public Member Functions
npc_muradin_bronzebeard_iccAI (Creature *creature)
void Reset () override
void DoAction (int32 action) override
void SpellHit (Unit *, SpellInfo const *spell) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
InstanceScript * _instance
std::list< Creature * > _guardList
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_muradin_bronzebeard_iccAI()
npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::npc_muradin_bronzebeard_iccAI (Creature * creature) inline
                                                          : ScriptedAI(creature)
        {
            _instance = me->GetInstanceScript();
        }
References _instance, WorldObject::GetInstanceScript(), and ScriptedAI::me.
Member Function Documentation
DoAction()
void npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            switch (action)
            {
                case ACTION_START_EVENT:
                    {
                        // Prevent crashes
                        if (_events.GetPhaseMask() & PHASE_INTRO_MASK)
                            return;
                        Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG));
                        if (!deathbringer || deathbringer->IsInEvadeMode())
                            return;
                        if (_guardList.empty())
{
                            GetCreatureListWithEntryInGrid(_guardList, me, NPC_SE_SKYBREAKER_MARINE, 20.0f);
                            _guardList.sort(Acore::ObjectDistanceOrderPred(me));
                        }
                        uint32 x = 1;
                        for (std::list<Creature*>::iterator itr = _guardList.begin(); itr != _guardList.end(); ++itr)
                            (*itr)->AI()->SetData(0, x++);
                        me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        Talk(SAY_INTRO_ALLIANCE_1);
                        _events.SetPhase(PHASE_INTRO_A);
                        _events.ScheduleEvent(EVENT_INTRO_ALLIANCE_2, 2500ms, 0, PHASE_INTRO_A);
                        _events.ScheduleEvent(EVENT_INTRO_ALLIANCE_3, 20s, 0, PHASE_INTRO_A);
                        _events.ScheduleEvent(EVENT_INTRO_ALLIANCE_4, 29s + 500ms, 0, PHASE_INTRO_A);
                        _instance->HandleGameObject(_instance->GetGuidData(GO_SAURFANG_S_DOOR), true);
                        if (GameObject* teleporter = ObjectAccessor::GetGameObject(*me, _instance->GetGuidData(GO_SCOURGE_TRANSPORTER_SAURFANG)))
{
                            _instance->HandleGameObject(ObjectGuid::Empty, false, teleporter);
                            teleporter->SetGameObjectFlag(GO_FLAG_IN_USE);
                        }
                        deathbringer->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        deathbringer->SetWalk(false);
                        deathbringer->GetMotionMaster()->MovePoint(POINT_SAURFANG, deathbringerPos.GetPositionX(), deathbringerPos.GetPositionY(), deathbringerPos.GetPositionZ());
                    }
                    break;
                case ACTION_START_OUTRO:
                    {
                        me->RemoveAurasDueToSpell(SPELL_GRIP_OF_AGONY);
                        me->SetDisableGravity(false);
                        me->MonsterMoveWithSpeed(me->GetPositionX(), me->GetPositionY(), 539.2917f, 10.0f);
                        for (std::list<Creature*>::iterator itr = _guardList.begin(); itr != _guardList.end(); ++itr)
                            (*itr)->AI()->DoAction(ACTION_DESPAWN);
                        //Talk(SAY_OUTRO_ALLIANCE_1);
                        break;
                    }
                case ACTION_EVADE:
                    {
                        float x, y, z, o;
                        me->GetMotionMaster()->Clear();
                        me->GetHomePosition(x, y, z, o);
                        me->SetPosition(x, y, z, o);
                        me->StopMovingOnCurrentPos();
                        me->SetDisableGravity(false);
                        EnterEvadeMode();
                        for (std::list<Creature*>::iterator itr = _guardList.begin(); itr != _guardList.end(); ++itr)
{
                            (*itr)->GetMotionMaster()->Clear();
                            (*itr)->GetHomePosition(x, y, z, o);
                            (*itr)->SetPosition(x, y, z, o);
                            (*itr)->StopMovingOnCurrentPos();
                            (*itr)->SetDisableGravity(false);
                            (*itr)->AI()->EnterEvadeMode();
                        }
                    }
                    break;
                default:
                    break;
            }
        }
References _events, _guardList, _instance, ACTION_DESPAWN, ACTION_EVADE, ACTION_START_EVENT, ACTION_START_OUTRO, MotionMaster::Clear(), DATA_DEATHBRINGER_SAURFANG, deathbringerPos, ObjectGuid::Empty, CreatureAI::EnterEvadeMode(), EVENT_INTRO_ALLIANCE_2, EVENT_INTRO_ALLIANCE_3, EVENT_INTRO_ALLIANCE_4, ObjectAccessor::GetCreature(), GetCreatureListWithEntryInGrid(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), Unit::GetMotionMaster(), EventMap::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_FLAG_IN_USE, GO_SAURFANG_S_DOOR, GO_SCOURGE_TRANSPORTER_SAURFANG, InstanceScript::HandleGameObject(), Creature::IsInEvadeMode(), ScriptedAI::me, Unit::MonsterMoveWithSpeed(), MotionMaster::MovePoint(), NPC_SE_SKYBREAKER_MARINE, PHASE_INTRO_A, PHASE_INTRO_MASK, POINT_SAURFANG, Unit::RemoveAurasDueToSpell(), Unit::RemoveNpcFlag(), Unit::RemoveUnitFlag(), SAY_INTRO_ALLIANCE_1, EventMap::ScheduleEvent(), Creature::SetDisableGravity(), EventMap::SetPhase(), Creature::SetPosition(), Creature::SetWalk(), SPELL_GRIP_OF_AGONY, Unit::StopMovingOnCurrentPos(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_NPC_FLAG_GOSSIP.
MovementInform()
void npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type == POINT_MOTION_TYPE)
            {
                switch (id)
                {
                    case POINT_FIRST_STEP:
                        me->SetWalk(false);
                        Talk(SAY_INTRO_ALLIANCE_4);
                        _events.ScheduleEvent(EVENT_INTRO_ALLIANCE_5, 5s, 0, PHASE_INTRO_A);
                        _events.ScheduleEvent(EVENT_INTRO_ALLIANCE_6, 7s, 0, PHASE_INTRO_A);
                        _events.ScheduleEvent(EVENT_INTRO_ALLIANCE_7, 9s, 0, PHASE_INTRO_A);
                        _events.ScheduleEvent(EVENT_INTRO_FINISH, 14s, 0, PHASE_INTRO_A);
                        break;
                    default:
                        break;
                }
            }
        }
References _events, EVENT_INTRO_ALLIANCE_5, EVENT_INTRO_ALLIANCE_6, EVENT_INTRO_ALLIANCE_7, EVENT_INTRO_FINISH, ScriptedAI::me, PHASE_INTRO_A, POINT_FIRST_STEP, POINT_MOTION_TYPE, SAY_INTRO_ALLIANCE_4, EventMap::ScheduleEvent(), and Creature::SetWalk().
Reset()
void npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _events.Reset();
            me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            me->SetReactState(REACT_PASSIVE);
        }
References _events, ScriptedAI::me, REACT_PASSIVE, EventMap::Reset(), Unit::SetNpcFlag(), Creature::SetReactState(), and UNIT_NPC_FLAG_GOSSIP.
SpellHit()
void npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spell->Id == SPELL_GRIP_OF_AGONY)
            {
                me->SetDisableGravity(true);
                me->GetMotionMaster()->MovePoint(POINT_CHOKE, chokePos[0]);
            }
        }
References chokePos, Unit::GetMotionMaster(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MovePoint(), POINT_CHOKE, Creature::SetDisableGravity(), and SPELL_GRIP_OF_AGONY.
UpdateAI()
void npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            _events.Update(diff);
            switch (_events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_INTRO_ALLIANCE_2:
                    if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                        deathbringer->AI()->Talk(SAY_INTRO_ALLIANCE_2);
                    break;
                case EVENT_INTRO_ALLIANCE_3:
                    if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                        deathbringer->AI()->Talk(SAY_INTRO_ALLIANCE_3);
                    break;
                case EVENT_INTRO_ALLIANCE_4:
                    me->SetWalk(true);
                    me->GetMotionMaster()->MovePoint(POINT_FIRST_STEP, firstStepPos.GetPositionX(), firstStepPos.GetPositionY(), firstStepPos.GetPositionZ());
                    break;
                case EVENT_INTRO_ALLIANCE_5:
                    Talk(SAY_INTRO_ALLIANCE_5);
                    for (std::list<Creature*>::iterator itr = _guardList.begin(); itr != _guardList.end(); ++itr)
                        (*itr)->AI()->DoAction(ACTION_CHARGE);
                    me->GetMotionMaster()->MoveCharge(chargePos[0].GetPositionX(), chargePos[0].GetPositionY(), chargePos[0].GetPositionZ(), 8.5f, POINT_CHARGE);
                    break;
                case EVENT_INTRO_ALLIANCE_6:
                    if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                    {
                        deathbringer->AI()->Talk(SAY_INTRO_ALLIANCE_7);
                        deathbringer->AI()->DoCast(me, SPELL_GRIP_OF_AGONY);
                    }
                    break;
                case EVENT_INTRO_ALLIANCE_7:
                    if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                    {
                        deathbringer->AI()->Talk(SAY_INTRO_ALLIANCE_6);
                    }
                    break;
                case EVENT_INTRO_FINISH:
                    if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                    {
                        deathbringer->AI()->DoAction(ACTION_INTRO_DONE);
                        deathbringer->SetImmuneToPC(false);
                        if (Player* target = deathbringer->SelectNearestPlayer(100.0f))
                            deathbringer->AI()->AttackStart(target);
                    }
                    break;
            }
        }
References _events, _guardList, _instance, ACTION_CHARGE, ACTION_INTRO_DONE, chargePos, DATA_DEATHBRINGER_SAURFANG, EVENT_INTRO_ALLIANCE_2, EVENT_INTRO_ALLIANCE_3, EVENT_INTRO_ALLIANCE_4, EVENT_INTRO_ALLIANCE_5, EVENT_INTRO_ALLIANCE_6, EVENT_INTRO_ALLIANCE_7, EVENT_INTRO_FINISH, EventMap::ExecuteEvent(), firstStepPos, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, MotionMaster::MoveCharge(), MotionMaster::MovePoint(), POINT_CHARGE, POINT_FIRST_STEP, SAY_INTRO_ALLIANCE_2, SAY_INTRO_ALLIANCE_3, SAY_INTRO_ALLIANCE_5, SAY_INTRO_ALLIANCE_6, SAY_INTRO_ALLIANCE_7, WorldObject::SelectNearestPlayer(), Creature::SetWalk(), SPELL_GRIP_OF_AGONY, and EventMap::Update().
Member Data Documentation
_events
EventMap npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::_events private
Referenced by DoAction(), MovementInform(), Reset(), and UpdateAI().
_guardList
std::list<Creature*> npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::_guardList private
Referenced by DoAction(), and UpdateAI().
_instance
InstanceScript* npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::_instance private
Referenced by DoAction(), npc_muradin_bronzebeard_iccAI(), and UpdateAI().