AzerothCore: instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript Struct Reference
instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript Struct Reference
Public Member Functions
instance_ruins_of_ahnqiraj_InstanceMapScript (Map *map)
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureEvade (Creature *creature) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
void OnUnitDeath (Unit *unit) override
void SetGuidData (uint32 type, ObjectGuid data) override
ObjectGuid GetGuidData (uint32 type) const override
void CallNextRajaxxLeader (bool announce=false)
void ResetRajaxxWaves ()
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid _kurinnaxxGUID
ObjectGuid _rajaxxGUID
ObjectGuid _moamGUID
ObjectGuid _buruGUID
ObjectGuid _ossirianGUID
ObjectGuid _paralyzedGUID
ObjectGuid _andorovGUID
uint32 _rajaxWaveCounter
uint8 _buruPhase
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_ruins_of_ahnqiraj_InstanceMapScript()
instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::instance_ruins_of_ahnqiraj_InstanceMapScript (Map * map) inline
                                                               : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(NUM_ENCOUNTER);
            LoadObjectData(creatureData, nullptr);
            _rajaxWaveCounter = 0;
            _buruPhase = 1;
        }
References _buruPhase, _rajaxWaveCounter, creatureData, DataHeader, InstanceScript::LoadObjectData(), NUM_ENCOUNTER, InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
CallNextRajaxxLeader()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::CallNextRajaxxLeader (bool announce = false) inline
        {
            ++_rajaxWaveCounter;
            if (Creature* nextLeader = GetCreature(RajaxxWavesData[_rajaxWaveCounter].at(0)))
            {
                if (announce)
                {
                    if (_rajaxWaveCounter >= 2)
                    {
                        if (Creature* rajaxx = GetCreature(DATA_RAJAXX))
{
                            rajaxx->AI()->Talk(RajaxxWavesData[_rajaxWaveCounter].at(1));
                        }
                    }
                }
                if (nextLeader->IsAlive())
                {
                    Creature* generalAndorov = instance->GetCreature(_andorovGUID);
                    if (generalAndorov && generalAndorov->IsAlive() && generalAndorov->AI()->GetData(DATA_ANDOROV))
                    {
                        nextLeader->AI()->AttackStart(generalAndorov);
                    }
                    else
                    {
                        nextLeader->SetInCombatWithZone();
                    }
                }
                else
                {
                    CallNextRajaxxLeader();
                }
            }
        }
References _andorovGUID, _rajaxWaveCounter, Creature::AI(), UnitAI::AttackStart(), CallNextRajaxxLeader(), DATA_ANDOROV, DATA_RAJAXX, Map::GetCreature(), InstanceScript::GetCreature(), UnitAI::GetData(), InstanceScript::instance, Unit::IsAlive(), and RajaxxWavesData.
Referenced by CallNextRajaxxLeader(), and SetData().
GetData()
uint32 instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == DATA_BURU_PHASE)
                return _buruPhase;
            return 0;
        }
References _buruPhase, and DATA_BURU_PHASE.
GetGuidData()
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case DATA_KURINNAXX:
                    return _kurinnaxxGUID;
                case DATA_RAJAXX:
                    return _rajaxxGUID;
                case DATA_MOAM:
                    return _moamGUID;
                case DATA_BURU:
                    return _buruGUID;
                case DATA_OSSIRIAN:
                    return _ossirianGUID;
                case DATA_PARALYZED:
                    return _paralyzedGUID;
                case DATA_ANDOROV:
                    return _andorovGUID;
            }
            return ObjectGuid::Empty;
        }
References _andorovGUID, _buruGUID, _kurinnaxxGUID, _moamGUID, _ossirianGUID, _paralyzedGUID, _rajaxxGUID, DATA_ANDOROV, DATA_BURU, DATA_KURINNAXX, DATA_MOAM, DATA_OSSIRIAN, DATA_PARALYZED, DATA_RAJAXX, and ObjectGuid::Empty.
OnCreatureCreate()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            InstanceScript::OnCreatureCreate(creature);
            switch (creature->GetEntry())
            {
                case NPC_KURINNAXX:
                    _kurinnaxxGUID = creature->GetGUID();
                    break;
                case NPC_RAJAXX:
                    _rajaxxGUID = creature->GetGUID();
                    break;
                case NPC_MOAM:
                    _moamGUID = creature->GetGUID();
                    break;
                case NPC_BURU:
                    _buruGUID = creature->GetGUID();
                    break;
                case NPC_OSSIRIAN:
                    _ossirianGUID = creature->GetGUID();
                    break;
                case NPC_ANDOROV:
                    _andorovGUID = creature->GetGUID();
                    break;
            }
        }
References _andorovGUID, _buruGUID, _kurinnaxxGUID, _moamGUID, _ossirianGUID, _rajaxxGUID, Object::GetEntry(), Object::GetGUID(), NPC_ANDOROV, NPC_BURU, NPC_KURINNAXX, NPC_MOAM, NPC_OSSIRIAN, NPC_RAJAXX, and InstanceScript::OnCreatureCreate().
OnCreatureEvade()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::OnCreatureEvade (Creature * creature) inline override virtual
Reimplemented from ZoneScript.
        {
            if (CreatureGroup* formation = creature->GetFormation())
            {
                if (Creature* leader = formation->GetLeader())
                {
                    switch (leader->GetEntry())
                    {
                        case NPC_QUUEZ:
                        case NPC_TUUBID:
                        case NPC_DRENN:
                        case NPC_XURREM:
                        case NPC_YEGGETH:
                        case NPC_PAKKON:
                        case NPC_ZERRAN:
                            if (!formation->IsFormationInCombat())
{
                                ResetRajaxxWaves();
                            }
                            break;
                        default:
                            break;
                    }
                }
            }
            else if (creature->GetEntry() == NPC_RAJAXX)
            {
                ResetRajaxxWaves();
            }
        }
References Object::GetEntry(), Creature::GetFormation(), NPC_DRENN, NPC_PAKKON, NPC_QUUEZ, NPC_RAJAXX, NPC_TUUBID, NPC_XURREM, NPC_YEGGETH, NPC_ZERRAN, and ResetRajaxxWaves().
OnPlayerEnter()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
        {
            if (GetBossState(DATA_KURINNAXX) == DONE &&
                GetBossState(DATA_RAJAXX) != DONE &&
                _rajaxWaveCounter == 0 &&                       // if non-zero, encounter is in progress
                !_andorovGUID)                                  // cleared if he is dead
            {
                instance->LoadGrid(-8538.17f, 1486.09f); // Andorov run path grid
                if (Creature* creature = player->SummonCreature(NPC_ANDOROV, -8538.177f, 1486.0956f, 32.39054f, 3.7638654f, TEMPSUMMON_CORPSE_DESPAWN, 0))
                {
                    creature->setActive(true);
                }
            }
        }
References _andorovGUID, _rajaxWaveCounter, DATA_KURINNAXX, DATA_RAJAXX, DONE, InstanceScript::GetBossState(), InstanceScript::instance, Map::LoadGrid(), NPC_ANDOROV, WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_DESPAWN.
OnUnitDeath()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            if (Creature* creature = unit->ToCreature())
            {
                if (CreatureGroup* formation = creature->GetFormation())
                {
                    if (Creature* leader = formation->GetLeader())
                    {
                        switch (leader->GetEntry())
{
                            case NPC_QUUEZ:
                            case NPC_TUUBID:
                            case NPC_DRENN:
                            case NPC_XURREM:
                            case NPC_YEGGETH:
                            case NPC_PAKKON:
                            case NPC_ZERRAN:
                                scheduler.CancelAll();
                                scheduler.Schedule(1s, [this, formation](TaskContext /*context*/)
{
                                    if (!formation->IsAnyMemberAlive())
{
                                        CallNextRajaxxLeader(true);
                                    }
                                });
                                break;
                            default:
                                break;
                        }
                    }
                }
                if (creature->GetEntry() == NPC_ANDOROV)
                {
                    _andorovGUID.Clear();
                }
            }
        }
References _andorovGUID, TaskScheduler::CancelAll(), ObjectGuid::Clear(), NPC_ANDOROV, NPC_DRENN, NPC_PAKKON, NPC_QUUEZ, NPC_TUUBID, NPC_XURREM, NPC_YEGGETH, NPC_ZERRAN, TaskScheduler::Schedule(), InstanceScript::scheduler, and Object::ToCreature().
ResetRajaxxWaves()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::ResetRajaxxWaves () inline
        {
            _rajaxWaveCounter = 0;
            scheduler.CancelAll();
            for (auto const& data : RajaxxWavesData)
            {
                if (Creature* creature = GetCreature(data.at(0)))
                {
                    if (CreatureGroup* group = creature->GetFormation())
                    {
                        group->RespawnFormation(true);
                    }
                }
            }
        }
References _rajaxWaveCounter, TaskScheduler::CancelAll(), InstanceScript::GetCreature(), RajaxxWavesData, and InstanceScript::scheduler.
Referenced by OnCreatureEvade().
SetData()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_RAJAXX_WAVE_ENGAGED:
                    scheduler.CancelGroup(GROUP_RAJAXX_WAVE_TIMER);
                    scheduler.Schedule(2min, [this](TaskContext context)
                    {
                        CallNextRajaxxLeader();
                        context.SetGroup(GROUP_RAJAXX_WAVE_TIMER);
                        context.Repeat();
                    });
                    break;
                case DATA_BURU_PHASE:
                    _buruPhase = data;
                    break;
                default:
                    break;
            }
        }
References _buruPhase, CallNextRajaxxLeader(), TaskScheduler::CancelGroup(), DATA_BURU_PHASE, DATA_RAJAXX_WAVE_ENGAGED, GROUP_RAJAXX_WAVE_TIMER, TaskContext::Repeat(), TaskScheduler::Schedule(), InstanceScript::scheduler, and TaskContext::SetGroup().
SetGuidData()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::SetGuidData (uint32 type, ObjectGuid data) inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == DATA_PARALYZED)
                _paralyzedGUID = data;
        }
References _paralyzedGUID, and DATA_PARALYZED.
Member Data Documentation
_andorovGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_andorovGUID private
Referenced by CallNextRajaxxLeader(), GetGuidData(), OnCreatureCreate(), OnPlayerEnter(), and OnUnitDeath().
_buruGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_buruGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
_buruPhase
uint8 instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_buruPhase private
Referenced by GetData(), instance_ruins_of_ahnqiraj_InstanceMapScript(), and SetData().
_kurinnaxxGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_kurinnaxxGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
_moamGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_moamGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
_ossirianGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_ossirianGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
_paralyzedGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_paralyzedGUID private
Referenced by GetGuidData(), and SetGuidData().
_rajaxWaveCounter
uint32 instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_rajaxWaveCounter private
Referenced by CallNextRajaxxLeader(), instance_ruins_of_ahnqiraj_InstanceMapScript(), OnPlayerEnter(), and ResetRajaxxWaves().
_rajaxxGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_rajaxxGUID private
Referenced by GetGuidData(), and OnCreatureCreate().