AzerothCore: adt_MH2O Class Reference
adt_MH2O Class Reference
#include "adt.h"
Classes
struct adt_LIQUID
Public Member Functions
bool prepareLoadedData ()
adt_liquid_instance const * GetLiquidInstance (int32 x, int32 y) const
adt_liquid_attributes GetLiquidAttributes (int32 x, int32 y) const
uint16 GetLiquidType (adt_liquid_instance const *h) const
float GetLiquidHeight (adt_liquid_instance const *h, int32 pos) const
int8 GetLiquidDepth (adt_liquid_instance const *h, int32 pos) const
uint16 const * GetLiquidTextureCoordMap (adt_liquid_instance const *h, int32 pos) const
uint64 GetLiquidExistsBitmap (adt_liquid_instance const *h) const
Public Attributes
union {
uint32 fcc
char fcc_txt [4]
};
uint32 size
struct adt_MH2O::adt_LIQUID liquid [ADT_CELLS_PER_GRID][ADT_CELLS_PER_GRID]
Detailed Description
Member Function Documentation
GetLiquidAttributes()
adt_liquid_attributes adt_MH2O::GetLiquidAttributes (int32 x, int32 y) const inline
    {
        if (liquid[x][y].used)
        {
            if (liquid[x][y].OffsetAttributes)
                return *((adt_liquid_attributes *)((uint8*)this + 8 + liquid[x][y].OffsetAttributes));
            return { 0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF };
        }
        return { 0, 0 };
    }
References liquid, and adt_MH2O::adt_LIQUID::OffsetAttributes.
Referenced by ConvertADT().
GetLiquidDepth()
int8 adt_MH2O::GetLiquidDepth (adt_liquid_instance const * h, int32 pos) const inline
    {
        if (!h->OffsetVertexData)
            return -1;
        switch (h->LiquidVertexFormat)
        {
            case LiquidVertexFormatType::HeightDepth:
                return ((int8 const*)((int8 const*)this + 8 + h->OffsetVertexData + (h->GetWidth() + 1) * (h->GetHeight() + 1) * 4))[pos];
            case LiquidVertexFormatType::HeightTextureCoord:
                return 0;
            case LiquidVertexFormatType::Depth:
                return ((int8 const*)((uint8*)this + 8 + h->OffsetVertexData))[pos];
            default:
                break;
        }
        return 0;
    }
References adt_liquid_instance::GetHeight(), adt_liquid_instance::GetWidth(), adt_liquid_instance::LiquidVertexFormat, and adt_liquid_instance::OffsetVertexData.
GetLiquidExistsBitmap()
uint64 adt_MH2O::GetLiquidExistsBitmap (adt_liquid_instance const * h) const inline
    {
        if (h->OffsetExistsBitmap)
            return *((uint64 *)((uint8*)this + 8 + h->OffsetExistsBitmap));
        else
            return 0xFFFFFFFFFFFFFFFFuLL;
    }
References adt_liquid_instance::OffsetExistsBitmap.
Referenced by ConvertADT().
GetLiquidHeight()
float adt_MH2O::GetLiquidHeight (adt_liquid_instance const * h, int32 pos) const inline
    {
        if (!h->OffsetVertexData)
            return 0.0f;
        switch (h->LiquidVertexFormat)
        {
            case LiquidVertexFormatType::HeightDepth:
            case LiquidVertexFormatType::HeightTextureCoord:
                return ((float const*)((uint8*)this + 8 + h->OffsetVertexData))[pos];
            case LiquidVertexFormatType::Depth:
                return 0.0f;
            default:
                break;
        }
        return 0.0f;
    }
References adt_liquid_instance::LiquidVertexFormat, and adt_liquid_instance::OffsetVertexData.
Referenced by ConvertADT().
GetLiquidInstance()
adt_liquid_instance const * adt_MH2O::GetLiquidInstance (int32 x, int32 y) const inline
    {
        if (liquid[x][y].used && liquid[x][y].OffsetInstances)
            return (adt_liquid_instance *)((uint8*)this + 8 + liquid[x][y].OffsetInstances);
        return nullptr;
    }
References liquid.
Referenced by ConvertADT().
GetLiquidTextureCoordMap()
uint16 const * adt_MH2O::GetLiquidTextureCoordMap (adt_liquid_instance const * h, int32 pos) const inline
    {
        if (!h->OffsetVertexData)
            return nullptr;
        switch (h->LiquidVertexFormat)
        {
            case LiquidVertexFormatType::HeightDepth:
            case LiquidVertexFormatType::Depth:
                return nullptr;
            case LiquidVertexFormatType::HeightTextureCoord:
                return (uint16 const*)((uint8 const*)this + 8 + h->OffsetVertexData + 4 * ((h->GetWidth() + 1) * (h->GetHeight() + 1) + pos));
            default:
                break;
        }
        return nullptr;
    }
References adt_liquid_instance::GetHeight(), adt_liquid_instance::GetWidth(), adt_liquid_instance::LiquidVertexFormat, and adt_liquid_instance::OffsetVertexData.
GetLiquidType()
uint16 adt_MH2O::GetLiquidType (adt_liquid_instance const * h) const inline
    {
        if (h->LiquidVertexFormat == LiquidVertexFormatType::Depth)
            return 2;
        return h->LiquidType;
    }
References adt_liquid_instance::LiquidType, and adt_liquid_instance::LiquidVertexFormat.
prepareLoadedData()
bool adt_MH2O::prepareLoadedData ()
{
    if (fcc != MH2OMagic.fcc)
        return false;
    // Check liquid data
    //    for (int i=0; i<ADT_CELLS_PER_GRID;i++)
    //        for (int j=0; j<ADT_CELLS_PER_GRID;j++)
    return true;
}
References fcc, u_map_fcc::fcc, and MH2OMagic.
Member Data Documentation
union { ... } adt_MH2O::@385
fcc
uint32 adt_MH2O::fcc
Referenced by prepareLoadedData().
fcc_txt
char adt_MH2O::fcc_txt[4]
liquid
struct adt_MH2O::adt_LIQUID adt_MH2O::liquid[ADT_CELLS_PER_GRID][ADT_CELLS_PER_GRID]
Referenced by GetLiquidAttributes(), and GetLiquidInstance().
size
uint32 adt_MH2O::size