AzerothCore: Guild::BankEventLogEntry Class Reference
Guild::BankEventLogEntry Class Reference
Public Member Functions
bool IsMoneyEvent () const
BankEventLogEntry (uint32 guildId, ObjectGuid::LowType guid, GuildBankEventLogTypes eventType, uint8 tabId, ObjectGuid playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId)
BankEventLogEntry (uint32 guildId, ObjectGuid::LowType guid, time_t timestamp, uint8 tabId, GuildBankEventLogTypes eventType, ObjectGuid playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId)
~BankEventLogEntry () override
void SaveToDB (CharacterDatabaseTransaction trans) const override
void WritePacket (WorldPackets::Guild::GuildBankLogQueryResults &packet) const
Public Member Functions inherited from Guild::LogEntry
LogEntry (uint32 guildId, ObjectGuid::LowType guid)
LogEntry (uint32 guildId, ObjectGuid::LowType guid, time_t timestamp)
virtual ~LogEntry ()
ObjectGuid::LowType GetGUID () const
uint64 GetTimestamp () const
virtual void SaveToDB (CharacterDatabaseTransaction trans) const =0
Static Public Member Functions
static bool IsMoneyEvent (GuildBankEventLogTypes eventType)
Private Attributes
GuildBankEventLogTypes m_eventType
uint8 m_bankTabId
ObjectGuid m_playerGuid
uint32 m_itemOrMoney
uint16 m_itemStackCount
uint8 m_destTabId
Additional Inherited Members
Protected Attributes inherited from Guild::LogEntry
uint32 m_guildId
ObjectGuid::LowType m_guid
uint64 m_timestamp
Detailed Description
Constructor & Destructor Documentation
BankEventLogEntry() [1/2]
Guild::BankEventLogEntry::BankEventLogEntry (uint32 guildId, ObjectGuid::LowType guid, GuildBankEventLogTypes eventType, uint8 tabId, ObjectGuid playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId) inline
                                                                                                                                                                                                    :
            LogEntry(guildId, guid), m_eventType(eventType), m_bankTabId(tabId), m_playerGuid(playerGuid),
            m_itemOrMoney(itemOrMoney), m_itemStackCount(itemStackCount), m_destTabId(destTabId) { }
BankEventLogEntry() [2/2]
Guild::BankEventLogEntry::BankEventLogEntry (uint32 guildId, ObjectGuid::LowType guid, time_t timestamp, uint8 tabId, GuildBankEventLogTypes eventType, ObjectGuid playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId) inline
                                                                                                                                                                                                                      :
            LogEntry(guildId, guid, timestamp), m_eventType(eventType), m_bankTabId(tabId), m_playerGuid(playerGuid),
            m_itemOrMoney(itemOrMoney), m_itemStackCount(itemStackCount), m_destTabId(destTabId) { }
~BankEventLogEntry()
Guild::BankEventLogEntry::~BankEventLogEntry () inline override
{ }
Member Function Documentation
IsMoneyEvent() [1/2]
bool Guild::BankEventLogEntry::IsMoneyEvent () const inline
        {
            return IsMoneyEvent(m_eventType);
        }
References IsMoneyEvent(), and m_eventType.
Referenced by Guild::_LogBankEvent(), IsMoneyEvent(), and Guild::LoadBankEventLogFromDB().
IsMoneyEvent() [2/2]
static bool Guild::BankEventLogEntry::IsMoneyEvent (GuildBankEventLogTypes eventType) inline static
        {
            return
                eventType == GUILD_BANK_LOG_DEPOSIT_MONEY ||
                eventType == GUILD_BANK_LOG_WITHDRAW_MONEY ||
                eventType == GUILD_BANK_LOG_REPAIR_MONEY;
        }
References GUILD_BANK_LOG_DEPOSIT_MONEY, GUILD_BANK_LOG_REPAIR_MONEY, and GUILD_BANK_LOG_WITHDRAW_MONEY.
SaveToDB()
void Guild::BankEventLogEntry::SaveToDB (CharacterDatabaseTransaction trans) const override virtual
Implements Guild::LogEntry.
{
    uint8 index = 0;
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_BANK_EVENTLOG);
    stmt->SetData(  index, m_guildId);
    stmt->SetData(++index, m_guid);
    stmt->SetData (++index, m_bankTabId);
    CharacterDatabase.ExecuteOrAppend(trans, stmt);
    index = 0;
    stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_BANK_EVENTLOG);
    stmt->SetData(  index, m_guildId);
    stmt->SetData(++index, m_guid);
    stmt->SetData (++index, m_bankTabId);
    stmt->SetData (++index, uint8(m_eventType));
    stmt->SetData(++index, m_playerGuid.GetCounter());
    stmt->SetData(++index, m_itemOrMoney);
    stmt->SetData(++index, m_itemStackCount);
    stmt->SetData (++index, m_destTabId);
    stmt->SetData(++index, m_timestamp);
    CharacterDatabase.ExecuteOrAppend(trans, stmt);
}
References CHAR_DEL_GUILD_BANK_EVENTLOG, CHAR_INS_GUILD_BANK_EVENTLOG, CharacterDatabase, and PreparedStatementBase::SetData().
WritePacket()
void Guild::BankEventLogEntry::WritePacket (WorldPackets::Guild::GuildBankLogQueryResults & packet) const
{
    WorldPackets::Guild::GuildBankLogEntry bankLogEntry;
    bankLogEntry.PlayerGUID = ObjectGuid::Create<HighGuid::Player>(m_playerGuid.GetCounter());
    bankLogEntry.TimeOffset = int32(GameTime::GetGameTime().count() - m_timestamp);
    bankLogEntry.EntryType = int8(m_eventType);
    switch (m_eventType)
    {
        case GUILD_BANK_LOG_DEPOSIT_ITEM:
        case GUILD_BANK_LOG_WITHDRAW_ITEM:
            bankLogEntry.ItemID = int32(m_itemOrMoney);
            bankLogEntry.Count = int32(m_itemStackCount);
            break;
        case GUILD_BANK_LOG_MOVE_ITEM:
        case GUILD_BANK_LOG_MOVE_ITEM2:
            bankLogEntry.ItemID = int32(m_itemOrMoney);
            bankLogEntry.Count = int32(m_itemStackCount);
            bankLogEntry.OtherTab = int8(m_destTabId);
            break;
        default:
            bankLogEntry.Money = uint32(m_itemOrMoney);
    }
    packet.Entry.push_back(bankLogEntry);
}
References WorldPackets::Guild::GuildBankLogEntry::Count, WorldPackets::Guild::GuildBankLogQueryResults::Entry, WorldPackets::Guild::GuildBankLogEntry::EntryType, GameTime::GetGameTime(), GUILD_BANK_LOG_DEPOSIT_ITEM, GUILD_BANK_LOG_MOVE_ITEM, GUILD_BANK_LOG_MOVE_ITEM2, GUILD_BANK_LOG_WITHDRAW_ITEM, WorldPackets::Guild::GuildBankLogEntry::ItemID, WorldPackets::Guild::GuildBankLogEntry::Money, WorldPackets::Guild::GuildBankLogEntry::OtherTab, WorldPackets::Guild::GuildBankLogEntry::PlayerGUID, and WorldPackets::Guild::GuildBankLogEntry::TimeOffset.
Member Data Documentation
m_bankTabId
uint8 Guild::BankEventLogEntry::m_bankTabId private
m_destTabId
uint8 Guild::BankEventLogEntry::m_destTabId private
m_eventType
GuildBankEventLogTypes Guild::BankEventLogEntry::m_eventType private
Referenced by IsMoneyEvent().
m_itemOrMoney
uint32 Guild::BankEventLogEntry::m_itemOrMoney private
m_itemStackCount
uint16 Guild::BankEventLogEntry::m_itemStackCount private
m_playerGuid
ObjectGuid Guild::BankEventLogEntry::m_playerGuid private