AzerothCore: Acore::Impl::GenericHMAC< HashCreator, DigestLength > Class Template Reference
Acore::Impl::GenericHMAC< HashCreator, DigestLength > Class Template Reference
#include "HMAC.h"
Public Types
using Digest = std::array< uint8, DIGEST_LENGTH >
Public Member Functions
GenericHMAC (uint8 const *seed, std::size_t len)
template<typename Container >
GenericHMAC (Container const &container)
GenericHMAC (GenericHMAC const &right)
GenericHMAC (GenericHMAC &&right) noexcept
~GenericHMAC ()
GenericHMAC & operator= (GenericHMAC const &right)
GenericHMAC & operator= (GenericHMAC &&right) noexcept
void UpdateData (uint8 const *data, std::size_t len)
void UpdateData (std::string_view str)
void UpdateData (std::string const &str)
void UpdateData (char const *str)
template<typename Container >
void UpdateData (Container const &c)
void Finalize ()
Digest const & GetDigest () const
Static Public Member Functions
template<typename Container >
static Digest GetDigestOf (Container const &seed, uint8 const *data, std::size_t len)
template<typename Container , typename... Ts>
static auto GetDigestOf (Container const &seed, Ts &&... pack) -> std::enable_if_t<!(std::is_integral_v< std::decay_t< Ts > >||...), Digest >
Static Public Attributes
static constexpr std::size_t DIGEST_LENGTH = DigestLength
Private Attributes
EVP_MD_CTX * _ctx {}
EVP_PKEY * _key {}
Digest _digest {}
Detailed Description
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength>
class Acore::Impl::GenericHMAC< HashCreator, DigestLength >
Member Typedef Documentation
Digest
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> using Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Digest = std::array<uint8, DIGEST_LENGTH>
Constructor & Destructor Documentation
GenericHMAC() [1/4]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC (uint8 const * seed, std::size_t len) inline
                                                          : _ctx(GenericHashImpl::MakeCTX()), _key(EVP_PKEY_new_mac_key(EVP_PKEY_HMAC, nullptr, seed, len))
            {
                int result = EVP_DigestSignInit(_ctx, nullptr, HashCreator(), nullptr, _key);
                ASSERT(result == 1);
            }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_key, and ASSERT.
GenericHMAC() [2/4]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> template<typename Container > Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC (Container const & container) inline
: GenericHMAC(std::data(container), std::size(container)) {}
GenericHMAC() [3/4]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC (GenericHMAC< HashCreator, DigestLength > const & right) inline
                                                  : _ctx(GenericHashImpl::MakeCTX())
            {
                *this = right;
            }
GenericHMAC() [4/4]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC (GenericHMAC< HashCreator, DigestLength > && right) inline noexcept
            {
                *this = std::move(right);
            }
~GenericHMAC()
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Acore::Impl::GenericHMAC< HashCreator, DigestLength >::~GenericHMAC () inline
            {
                GenericHashImpl::DestroyCTX(_ctx);
                _ctx = nullptr;
                EVP_PKEY_free(_key);
                _key = nullptr;
            }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_key, and Acore::Impl::GenericHashImpl::DestroyCTX().
Member Function Documentation
Finalize()
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize () inline
            {
                std::size_t length = DIGEST_LENGTH;
                int result = EVP_DigestSignFinal(_ctx, _digest.data(), &length);
                ASSERT(result == 1);
                ASSERT(length == DIGEST_LENGTH);
            }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest, ASSERT, and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::DIGEST_LENGTH.
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf().
GetDigest()
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Digest const & Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigest () const inline
{ return _digest; }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest.
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf().
GetDigestOf() [1/2]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> template<typename Container , typename... Ts> static auto Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf (Container const & seed, Ts &&... pack) -> std::enable_if_t<!(std::is_integral_v<std::decay_t<Ts>> || ...), Digest> inline static
            {
                GenericHMAC hash(seed);
                (hash.UpdateData(std::forward<Ts>(pack)), ...);
                hash.Finalize();
                return hash.GetDigest();
            }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigest(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
GetDigestOf() [2/2]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> template<typename Container > static Digest Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf (Container const & seed, uint8 const * data, std::size_t len) inline static
            {
                GenericHMAC hash(seed);
                hash.UpdateData(data, len);
                hash.Finalize();
                return hash.GetDigest();
            }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigest(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by AuthCrypt::Init(), and WardenWin::RequestChecks().
operator=() [1/2]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> GenericHMAC & Acore::Impl::GenericHMAC< HashCreator, DigestLength >::operator= (GenericHMAC< HashCreator, DigestLength > && right) inline noexcept
            {
                if (this == &right)
                    return *this;
                _ctx = std::exchange(right._ctx, GenericHashImpl::MakeCTX());
                _key = std::exchange(right._key, EVP_PKEY_new());
                _digest = std::exchange(right._digest, Digest{});
                return *this;
            }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest, Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_key, and Acore::Impl::GenericHashImpl::MakeCTX().
operator=() [2/2]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> GenericHMAC & Acore::Impl::GenericHMAC< HashCreator, DigestLength >::operator= (GenericHMAC< HashCreator, DigestLength > const & right) inline
            {
                if (this == &right)
                    return *this;
                int result = EVP_MD_CTX_copy_ex(_ctx, right._ctx);
                ASSERT(result == 1);
                _key = right._key;      // EVP_PKEY uses reference counting internally, just copy the pointer
                EVP_PKEY_up_ref(_key);  // Bump reference count for PKEY, as every instance of this class holds two references to PKEY and destructor decrements it twice
                _digest = right._digest;
                return *this;
            }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest, Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_key, and ASSERT.
UpdateData() [1/5]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (char const * str) inline
{ UpdateData(std::string_view(str)); } /* explicit overload to avoid using the container template */
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [2/5]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> template<typename Container > void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (Container const & c) inline
{ UpdateData(std::data(c), std::size(c)); }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [3/5]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (std::string const & str) inline
{ UpdateData(std::string_view(str)); } /* explicit overload to avoid using the container template */
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [4/5]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (std::string_view str) inline
{ UpdateData(reinterpret_cast<uint8 const*>(str.data()), str.size()); }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [5/5]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (uint8 const * data, std::size_t len) inline
            {
                int result = EVP_DigestSignUpdate(_ctx, data, len);
                ASSERT(result == 1);
            }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, and ASSERT.
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf().
Member Data Documentation
_ctx
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> EVP_MD_CTX* Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx {} private
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::operator=(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::~GenericHMAC().
_digest
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Digest Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest {} private
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigest(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::operator=().
_key
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> EVP_PKEY* Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_key {} private
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::operator=(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::~GenericHMAC().
DIGEST_LENGTH
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> constexpr std::size_t Acore::Impl::GenericHMAC< HashCreator, DigestLength >::DIGEST_LENGTH = DigestLength static constexpr
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize().