AzeorthCore: npc_forest_frog::npc_forest_frogAI Struct Reference
npc_forest_frog::npc_forest_frogAI Struct Reference
Public Member Functions
npc_forest_frogAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void MovementInform (uint32 type, uint32 data) override
void UpdateAI (uint32 diff) override
void DoSpawnRandom ()
void SpellHit (Unit *caster, SpellInfo const *spell) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
EventMap events
uint8 eventTimer
ObjectGuid PlayerGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_forest_frogAI()
npc_forest_frog::npc_forest_frogAI::npc_forest_frogAI (Creature * creature) inline
                                              : ScriptedAI(creature)
        {
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DoSpawnRandom()
void npc_forest_frog::npc_forest_frogAI::DoSpawnRandom () inline
        {
            if (instance)
            {
                uint32 cEntry = NPC_MANNUTH;
                switch (urand(0, 9))
                {
                    case 1:
                        cEntry = NPC_DEEZ;
                        break;
                    case 2:
                        cEntry = NPC_GALATHRYN;
                        break;
                    case 3:
                        cEntry = NPC_ADARRAH;
                        break;
                    case 4:
                        cEntry = NPC_FUDGERICK;
                        break;
                    case 5:
                        cEntry = NPC_DARWEN;
                        break;
                    case 6:
                        cEntry = NPC_MITZI;
                        break;
                    case 7:
                        cEntry = NPC_CHRISTIAN;
                        break;
                    case 8:
                        cEntry = NPC_BRENNAN;
                        break;
                    case 9:
                        cEntry = NPC_HOLLEE;
                        break;
                }
                if (!instance->GetData(TYPE_RAND_VENDOR_1) && roll_chance_i(10))
                {
                    cEntry = NPC_GUNTER;
                    instance->SetData(TYPE_RAND_VENDOR_1, DONE);
                }
                else if (!instance->GetData(TYPE_RAND_VENDOR_2) && roll_chance_i(10))
                {
                    cEntry = NPC_KYREN;
                    instance->SetData(TYPE_RAND_VENDOR_2, DONE);
                }
                // start generic rp
                eventTimer = 1;
                events.ScheduleEvent(eventTimer, 3000);
                me->UpdateEntry(cEntry);
            }
        }
References DONE, eventTimer, ZoneScript::GetData(), instance, ScriptedAI::me, NPC_ADARRAH, NPC_BRENNAN, NPC_CHRISTIAN, NPC_DARWEN, NPC_DEEZ, NPC_FUDGERICK, NPC_GALATHRYN, NPC_GUNTER, NPC_HOLLEE, NPC_KYREN, NPC_MANNUTH, NPC_MITZI, roll_chance_i(), ZoneScript::SetData(), TYPE_RAND_VENDOR_1, TYPE_RAND_VENDOR_2, Creature::UpdateEntry(), and urand().
Referenced by SpellHit().
EnterCombat()
void npc_forest_frog::npc_forest_frogAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
{ }
MovementInform()
void npc_forest_frog::npc_forest_frogAI::MovementInform (uint32 type, uint32 data) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type == POINT_MOTION_TYPE && data == POINT_DESPAWN)
                me->DespawnOrUnsummon(1000);
        }
References Creature::DespawnOrUnsummon(), ScriptedAI::me, POINT_DESPAWN, and POINT_MOTION_TYPE.
Reset()
void npc_forest_frog::npc_forest_frogAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
{ }
SpellHit()
void npc_forest_frog::npc_forest_frogAI::SpellHit (Unit * caster, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spell->Id == SPELL_REMOVE_AMANI_CURSE && caster->GetTypeId() == TYPEID_PLAYER && me->GetEntry() == NPC_FOREST_FROG)
            {
                me->GetMotionMaster()->MoveIdle();
                me->SetFacingToObject(caster);
                PlayerGUID = caster->GetGUID();
                if (roll_chance_i(2))
                {
                    DoCast(caster, SPELL_PUSH_MOJO, true);
                    me->GetMotionMaster()->MovePoint(POINT_DESPAWN, caster->GetPositionX(), caster->GetPositionY(), caster->GetPositionZ());
                }
                else
                    DoSpawnRandom();
            }
        }
References UnitAI::DoCast(), DoSpawnRandom(), Object::GetEntry(), Object::GetGUID(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::GetTypeId(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), NPC_FOREST_FROG, PlayerGUID, POINT_DESPAWN, roll_chance_i(), Unit::SetFacingToObject(), SPELL_PUSH_MOJO, SPELL_REMOVE_AMANI_CURSE, and TYPEID_PLAYER.
UpdateAI()
void npc_forest_frog::npc_forest_frogAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Update(diff);
            if (eventTimer)
            {
                Player* player = ObjectAccessor::GetPlayer(me->GetMap(), PlayerGUID);
                switch (events.ExecuteEvent())
                {
                    case 1:
                        switch (me->GetEntry())
{
                            case NPC_MANNUTH:
                                Talk(SAY_MANNUTH_0, player);
                                break;
                            case NPC_DEEZ:
                                Talk(SAY_DEEZ_0, player);
                                break;
                            case NPC_GALATHRYN:
                                Talk(SAY_GALATHRYN_0, player);
                                break;
                            case NPC_ADARRAH:
                                Talk(SAY_ADARRAH_1, player);
                                break;
                            case NPC_DARWEN:
                                Talk(SAY_DARWEN_0, player);
                                break;
                            case NPC_FUDGERICK:
                                Talk(SAY_FUDGERICK_0, player);
                                break;
                            case NPC_GUNTER:
                                Talk(SAY_GUNTER_0, player);
                                break;
                            case NPC_KYREN:
                                Talk(SAY_KYREN_0, player);
                                break;
                            case NPC_MITZI:
                                Talk(SAY_MITZI_0, player);
                                break;
                            case NPC_CHRISTIAN:
                                Talk(SAY_CHRISTIAN_0, player);
                                break;
                            case NPC_BRENNAN:
                                Talk(SAY_BRENNAN_0, player);
                                break;
                            case NPC_HOLLEE:
                                Talk(SAY_HOLLEE_0, player);
                                break;
                        }
                        eventTimer = 2;
                        events.ScheduleEvent(eventTimer, urand(4000, 5000));
                        break;
                    case 2:
                        if (me->GetEntry() != NPC_GUNTER && me->GetEntry() != NPC_KYREN) // vendors don't kneel?
                            me->SetStandState(UNIT_STAND_STATE_KNEEL);
                        switch (me->GetEntry())
{
                            case NPC_MANNUTH:
                                DoCast(me, SPELL_SUMMON_AMANI_CHARM_CHEST_2, true);
                                Talk(SAY_MANNUTH_1, player);
                                break;
                            case NPC_DEEZ:
                                DoCast(me, SPELL_SUMMON_AMANI_CHARM_CHEST_2, true);
                                Talk(SAY_DEEZ_1, player);
                                break;
                            case NPC_GALATHRYN:
                                DoCast(me, SPELL_SUMMON_AMANI_CHARM_CHEST_2, true);
                                Talk(SAY_GALATHRYN_1, player);
                                break;
                            case NPC_ADARRAH:
                                DoCast(me, SPELL_SUMMON_AMANI_CHARM_CHEST_2, true);
                                Talk(SAY_ADARRAH_2, player);
                                break;
                            case NPC_DARWEN:
                                DoCast(me, SPELL_SUMMON_MONEY_BAG, true);
                                me->LoadEquipment(0, true);
                                Talk(SAY_DARWEN_1, player);
                                break;
                            case NPC_FUDGERICK:
                                DoCast(me, SPELL_SUMMON_MONEY_BAG, true);
                                me->LoadEquipment(0, true);
                                Talk(SAY_FUDGERICK_1, player);
                                break;
                            case NPC_GUNTER:
                                Talk(SAY_GUNTER_1, player);
                                break;
                            case NPC_KYREN:
                                Talk(SAY_KYREN_1, player);
                                break;
                            case NPC_MITZI:
                                DoCast(me, SPELL_SUMMON_AMANI_CHARM_CHEST_1, true);
                                Talk(SAY_MITZI_1, player);
                                break;
                            case NPC_CHRISTIAN:
                                DoCast(me, SPELL_SUMMON_AMANI_CHARM_CHEST_1, true);
                                Talk(SAY_CHRISTIAN_1, player);
                                break;
                            case NPC_BRENNAN:
                                DoCast(me, SPELL_SUMMON_AMANI_CHARM_CHEST_1, true);
                                Talk(SAY_BRENNAN_1, player);
                                break;
                            case NPC_HOLLEE:
                                DoCast(me, SPELL_SUMMON_AMANI_CHARM_CHEST_1, true);
                                Talk(SAY_HOLLEE_1, player);
                                break;
                        }
                        eventTimer = 3;
                        events.ScheduleEvent(eventTimer, urand(6000, 7000));
                        break;
                    case 3:
                        me->SetStandState(EMOTE_ONESHOT_NONE);
                        switch (me->GetEntry())
{
                            case NPC_MANNUTH:
                                Talk(SAY_MANNUTH_2, player);
                                break;
                            case NPC_DEEZ:
                                Talk(SAY_DEEZ_2, player);
                                break;
                            case NPC_GALATHRYN:
                                Talk(SAY_GALATHRYN_2, player);
                                break;
                            case NPC_ADARRAH:
                                Talk(SAY_ADARRAH_3, player);
                                break;
                            case NPC_DARWEN:
                                Talk(SAY_DARWEN_2, player);
                                break;
                            case NPC_FUDGERICK:
                                Talk(SAY_FUDGERICK_2, player);
                                break;
                            case NPC_GUNTER:
                                Talk(SAY_GUNTER_2, player);
                                break;
                            case NPC_KYREN:
                                Talk(SAY_KYREN_2, player);
                                break;
                            case NPC_MITZI:
                                Talk(SAY_MITZI_2, player);
                                break;
                            case NPC_CHRISTIAN:
                                Talk(SAY_CHRISTIAN_2, player);
                                break;
                            case NPC_BRENNAN:
                                Talk(SAY_BRENNAN_2, player);
                                break;
                            case NPC_HOLLEE:
                                Talk(SAY_HOLLEE_2, player);
                                break;
                        }
                        eventTimer = 4;
                        if (me->GetEntry() == NPC_GUNTER || me->GetEntry() == NPC_KYREN)
                            events.ScheduleEvent(eventTimer, 5 * MINUTE * IN_MILLISECONDS); // vendors wait for 5 minutes before running away and despawning
                        else
                            events.ScheduleEvent(eventTimer, 6000);
                        break;
                    case 4:
                        me->HandleEmoteCommand(EMOTE_ONESHOT_WAVE);
                        switch (me->GetEntry())
{
                            case NPC_MANNUTH:
                                Talk(SAY_MANNUTH_3, player);
                                break;
                            case NPC_DEEZ:
                                Talk(SAY_DEEZ_3, player);
                                break;
                            case NPC_GALATHRYN:
                                Talk(SAY_GALATHRYN_3, player);
                                break;
                            case NPC_ADARRAH:
                                Talk(SAY_ADARRAH_4, player);
                                break;
                            case NPC_DARWEN:
                                Talk(SAY_DARWEN_3, player);
                                break;
                            case NPC_FUDGERICK:
                                Talk(SAY_FUDGERICK_3, player);
                                break;
                            case NPC_MITZI:
                                Talk(SAY_MITZI_3, player);
                                break;
                            case NPC_CHRISTIAN:
                                Talk(SAY_CHRISTIAN_3, player);
                                break;
                            case NPC_BRENNAN:
                                Talk(SAY_BRENNAN_3, player);
                                break;
                            case NPC_HOLLEE:
                                Talk(SAY_HOLLEE_3, player);
                                break;
                        }
                        eventTimer = 5;
                        events.ScheduleEvent(eventTimer, 2000);
                        break;
                    case 5:
                        switch (me->GetEntry())
{
                            case NPC_ADARRAH:
                                DoCast(me, SPELL_STEALTH_, true);
                                break;
                        }
                        if (me->GetPositionY() > 1290.0f)
                            me->GetMotionMaster()->MovePoint(POINT_DESPAWN, 118.2742f, 1400.657f, -9.118711f);
                        else
                            me->GetMotionMaster()->MovePoint(POINT_DESPAWN, 114.3155f, 1244.244f, -20.97606f);
                        eventTimer = 0;
                        break;
                }
            }
        }
References UnitAI::DoCast(), EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_WAVE, eventTimer, Object::GetEntry(), WorldObject::GetMap(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Position::GetPositionY(), Unit::HandleEmoteCommand(), IN_MILLISECONDS, Creature::LoadEquipment(), ScriptedAI::me, MINUTE, MotionMaster::MovePoint(), NPC_ADARRAH, NPC_BRENNAN, NPC_CHRISTIAN, NPC_DARWEN, NPC_DEEZ, NPC_FUDGERICK, NPC_GALATHRYN, NPC_GUNTER, NPC_HOLLEE, NPC_KYREN, NPC_MANNUTH, NPC_MITZI, PlayerGUID, POINT_DESPAWN, SAY_ADARRAH_1, SAY_ADARRAH_2, SAY_ADARRAH_3, SAY_ADARRAH_4, SAY_BRENNAN_0, SAY_BRENNAN_1, SAY_BRENNAN_2, SAY_BRENNAN_3, SAY_CHRISTIAN_0, SAY_CHRISTIAN_1, SAY_CHRISTIAN_2, SAY_CHRISTIAN_3, SAY_DARWEN_0, SAY_DARWEN_1, SAY_DARWEN_2, SAY_DARWEN_3, SAY_DEEZ_0, SAY_DEEZ_1, SAY_DEEZ_2, SAY_DEEZ_3, SAY_FUDGERICK_0, SAY_FUDGERICK_1, SAY_FUDGERICK_2, SAY_FUDGERICK_3, SAY_GALATHRYN_0, SAY_GALATHRYN_1, SAY_GALATHRYN_2, SAY_GALATHRYN_3, SAY_GUNTER_0, SAY_GUNTER_1, SAY_GUNTER_2, SAY_HOLLEE_0, SAY_HOLLEE_1, SAY_HOLLEE_2, SAY_HOLLEE_3, SAY_KYREN_0, SAY_KYREN_1, SAY_KYREN_2, SAY_MANNUTH_0, SAY_MANNUTH_1, SAY_MANNUTH_2, SAY_MANNUTH_3, SAY_MITZI_0, SAY_MITZI_1, SAY_MITZI_2, SAY_MITZI_3, Unit::SetStandState(), SPELL_STEALTH_, SPELL_SUMMON_AMANI_CHARM_CHEST_1, SPELL_SUMMON_AMANI_CHARM_CHEST_2, SPELL_SUMMON_MONEY_BAG, UNIT_STAND_STATE_KNEEL, and urand().
Member Data Documentation
events
EventMap npc_forest_frog::npc_forest_frogAI::events
eventTimer
uint8 npc_forest_frog::npc_forest_frogAI::eventTimer
Referenced by DoSpawnRandom(), and UpdateAI().
instance
InstanceScript* npc_forest_frog::npc_forest_frogAI::instance
Referenced by DoSpawnRandom(), and npc_forest_frogAI().
PlayerGUID
ObjectGuid npc_forest_frog::npc_forest_frogAI::PlayerGUID
Referenced by SpellHit(), and UpdateAI().