AzerothCore: npc_wintergarde_gryphon Class Reference
npc_wintergarde_gryphon Class Reference
Public Member Functions
npc_wintergarde_gryphon (Creature *creature)
void JustDied (Unit *) override
void IsSummonedBy (WorldObject *summoner) override
void MovementInform (uint32 type, uint32 id) override
void PassengerBoarded (Unit *passenger, int8 seatId, bool apply) override
== Fields =======================================
Creature * getVillager ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void SpellHit (Unit *, SpellInfo const *spell) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
ObjectGuid villagerGUID
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from VehicleAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_wintergarde_gryphon()
npc_wintergarde_gryphon::npc_wintergarde_gryphon (Creature * creature) inline
                                                : VehicleAI(creature)
    {
        creature->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
    }
References Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Member Function Documentation
getVillager()
Creature * npc_wintergarde_gryphon::getVillager () inline
{ return ObjectAccessor::GetCreature(*me, villagerGUID); }
References ObjectAccessor::GetCreature(), CreatureAI::me, and villagerGUID.
Referenced by UpdateAI().
IsSummonedBy()
void npc_wintergarde_gryphon::IsSummonedBy (WorldObject * summoner) inline override virtual
Reimplemented from CreatureAI.
    {
        me->SetFacingToObject(summoner);
        Position pos = summoner->GetPosition();
        me->GetMotionMaster()->MovePoint(POINT_LAND, pos);
    }
References Unit::GetMotionMaster(), Position::GetPosition(), CreatureAI::me, MotionMaster::MovePoint(), POINT_LAND, and Unit::SetFacingToObject().
JustDied()
void npc_wintergarde_gryphon::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
    {
        me->DespawnOrUnsummon(3s, 0s);
    }
References Creature::DespawnOrUnsummon(), and CreatureAI::me.
MovementInform()
void npc_wintergarde_gryphon::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
    {
        if (type == POINT_MOTION_TYPE && id == POINT_LAND)
            events.ScheduleEvent(EVENT_VEHICLE_GET, 0s);
    }
References EVENT_VEHICLE_GET, POINT_LAND, and POINT_MOTION_TYPE.
PassengerBoarded()
void npc_wintergarde_gryphon::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
    {
        if (!apply && seatId == 0)
        {
            // left the vehicle with a passenger will result in despawn
            if (Vehicle* gryphon = me->GetVehicleKit())
                if (Unit* villager = gryphon->GetPassenger(1))
                {
                    if (!villager->IsCreature())
                        return;
                    if (Creature* seat = villager->ToCreature())
                    {
                        seat->ExitVehicle();
                        seat->DespawnOrUnsummon();
                    }
                }
            events.ScheduleEvent(EVENT_TAKE_OFF, 2s);
            me->CastSpell(passenger, VEHICLE_SPELL_PARACHUTE, true);
        }
    }
References Unit::CastSpell(), EVENT_TAKE_OFF, Unit::GetVehicleKit(), CreatureAI::me, Object::ToCreature(), and VEHICLE_SPELL_PARACHUTE.
SpellHit()
void npc_wintergarde_gryphon::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
    {
        if (spell->Id != SPELL_DROP_OFF_VILLAGER)
            return;
        if (Vehicle* gryphon = me->GetVehicleKit())
            if (Unit* villager = gryphon->GetPassenger(1))
            {
                villager->ExitVehicle();
                villager->GetMotionMaster()->Clear(false);
                villager->GetMotionMaster()->MoveIdle();
                villager->SetCanFly(false); // prevents movement in flight
                villagerGUID = villager->GetGUID();
                villager->HandleEmoteCommand(EMOTE_ONESHOT_CHEER);
                events.ScheduleEvent(EVENT_GET_VILLAGER, 3s);
            }
    }
References EMOTE_ONESHOT_CHEER, EVENT_GET_VILLAGER, Unit::GetVehicleKit(), SpellInfo::Id, CreatureAI::me, SPELL_DROP_OFF_VILLAGER, and villagerGUID.
UpdateAI()
void npc_wintergarde_gryphon::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from VehicleAI.
    {
        events.Update(diff);
        while (uint32 eventId = events.ExecuteEvent())
        {
            switch (eventId)
            {
                case EVENT_VEHICLE_GET:
                {
                    me->SetDisableGravity(false);
                    me->SetHover(false);
                    me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                    break;
                }
                case EVENT_TAKE_OFF:
                {
                    me->DespawnOrUnsummon(4050);
                    me->SetOrientation(2.5f);
                    me->SetSpeedRate(MOVE_FLIGHT, 1.0f);
                    Position pos = me->GetPosition();
                    Position offset = { 14.0f, 14.0f, 16.0f, 0.0f };
                    pos.RelocateOffset(offset);
                    me->GetMotionMaster()->MovePoint(POINT_TAKE_OFF, pos);
                    break;
                }
                case EVENT_GET_VILLAGER:
                {
                    if (getVillager())
                    {
                        getVillager()->GetMotionMaster()->MovePoint(0, 3660.0f, -706.4f, 215.0f);
                        getVillager()->DespawnOrUnsummon(7s, 0s);
                    }
                    break;
                }
            }
        }
    }
References Creature::DespawnOrUnsummon(), EVENT_GET_VILLAGER, EVENT_TAKE_OFF, EVENT_VEHICLE_GET, Unit::GetMotionMaster(), Position::GetPosition(), getVillager(), CreatureAI::me, MOVE_FLIGHT, MotionMaster::MovePoint(), POINT_TAKE_OFF, Position::RelocateOffset(), Object::RemoveFlag(), Creature::SetDisableGravity(), Creature::SetHover(), Position::SetOrientation(), Unit::SetSpeedRate(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Member Data Documentation
villagerGUID
ObjectGuid npc_wintergarde_gryphon::villagerGUID private
Referenced by getVillager(), and SpellHit().