AzerothCore: at_icc_spire_frostwyrm Class Reference
at_icc_spire_frostwyrm Class Reference
Public Member Functions
at_icc_spire_frostwyrm ()
bool _OnTrigger (Player *player, AreaTrigger const *areaTrigger) override
Public Member Functions inherited from OnlyOnceAreaTriggerScript
bool OnTrigger (Player *, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from OnlyOnceAreaTriggerScript
virtual bool _OnTrigger (Player *, AreaTrigger const *)=0
void ResetAreaTriggerDone (InstanceScript *, uint32)
void ResetAreaTriggerDone (Player const *, AreaTrigger const *)
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
at_icc_spire_frostwyrm()
at_icc_spire_frostwyrm::at_icc_spire_frostwyrm () inline
: OnlyOnceAreaTriggerScript("at_icc_spire_frostwyrm") { }
Member Function Documentation
_OnTrigger()
bool at_icc_spire_frostwyrm::_OnTrigger (Player * player, AreaTrigger const * areaTrigger) inline override virtual
Implements OnlyOnceAreaTriggerScript.
    {
        if (player->GetInstanceScript()->GetPersistentData(DATA_SPIRE_FROSTWYRM) != DONE)
        {
            player->GetInstanceScript()->StorePersistentData(DATA_SPIRE_FROSTWYRM, DONE);
            const Position posHordeWyrm = { -375.538879f, 2120.774658f, 242.256775f, 3.714352f };
            const Position posAllianceWyrm = { -361.154358f, 2305.821289f, 244.771713f, 2.704335f };
            bool hordeSide = areaTrigger->entry == HORDE_AREATRIGGER || areaTrigger->entry == HORDE_AREATRIGGER + 1;
            if (Creature* frostwyrm = player->SummonCreature(NPC_SPIRE_FROSTWYRM, hordeSide ? posHordeWyrm : posAllianceWyrm))
            {
                frostwyrm->AI()->DoAction(areaTrigger->entry);
            }
        }
        return true;
    }
References DATA_SPIRE_FROSTWYRM, DONE, AreaTrigger::entry, WorldObject::GetInstanceScript(), InstanceScript::GetPersistentData(), HORDE_AREATRIGGER, NPC_SPIRE_FROSTWYRM, InstanceScript::StorePersistentData(), and WorldObject::SummonCreature().