AzerothCore: InstanceMapScript Class Reference
InstanceMapScript Class Reference
#include "InstanceMapScript.h"
Public Member Functions
bool IsDatabaseBound () const override
void checkValidity () override
virtual InstanceScript * GetInstanceScript (InstanceMap *) const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from MapScript< InstanceMap >
void checkMap ()
MapEntry const * GetEntry ()
virtual void OnCreate (InstanceMap *)
virtual void OnDestroy (InstanceMap *)
virtual void OnLoadGridMap (InstanceMap *, GridMap *, uint32, uint32)
virtual void OnUnloadGridMap (InstanceMap *, GridMap *, uint32, uint32)
virtual void OnPlayerEnter (InstanceMap *, Player *)
virtual void OnPlayerLeave (InstanceMap *, Player *)
void OnUpdate (InstanceMap *, uint32) override
Public Member Functions inherited from UpdatableScript< TObject >
virtual void OnUpdate (TObject *, uint32)
Protected Member Functions
InstanceMapScript (const char *name, uint32 mapId)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from MapScript< InstanceMap >
MapScript (uint32 mapId)
Protected Member Functions inherited from UpdatableScript< TObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
InstanceMapScript()
InstanceMapScript::InstanceMapScript (const char * name, uint32 mapId) protected
                                                                   :
    ScriptObject(name), MapScript<InstanceMap>(mapId)
{
    ScriptRegistry<InstanceMapScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
checkValidity()
void InstanceMapScript::checkValidity () override virtual
Reimplemented from ScriptObject.
{
    checkMap();
    if (GetEntry() && !GetEntry()->IsDungeon())
    {
        LOG_ERROR("maps.script", "InstanceMapScript for map {} is invalid.", GetEntry()->MapID);
    }
}
References MapScript< InstanceMap >::checkMap(), MapScript< InstanceMap >::GetEntry(), and LOG_ERROR.
GetInstanceScript()
virtual InstanceScript * InstanceMapScript::GetInstanceScript (InstanceMap *) const inline virtual
Reimplemented in instance_blackrock_depths, instance_blackrock_spire, instance_blackwing_lair, instance_molten_core, instance_deadmines, instance_gnomeregan, instance_karazhan, instance_magisters_terrace, instance_scarlet_monastery, instance_scholomance, instance_shadowfang_keep, instance_stratholme, instance_sunken_temple, instance_sunwell_plateau, instance_the_stockade, instance_uldaman, instance_zulaman, instance_zulgurub, instance_blackfathom_deeps, instance_hyjal, instance_old_hillsbrad, instance_the_black_morass, instance_dire_maul, instance_maraudon, instance_ragefire_chasm, instance_razorfen_downs, instance_razorfen_kraul, instance_ruins_of_ahnqiraj, instance_temple_of_ahnqiraj, instance_wailing_caverns, instance_zulfarrak, instance_ahnkahet, instance_azjol_nerub, instance_ruby_sanctum, instance_trial_of_the_crusader, instance_drak_tharon_keep, instance_forge_of_souls, instance_pit_of_saron, instance_icecrown_citadel, instance_nexus, instance_vault_of_archavon, instance_auchenai_crypts, instance_mana_tombs, instance_sethekk_halls, instance_shadow_labyrinth, instance_black_temple, instance_serpent_shrine, instance_the_slave_pens, instance_steam_vault, instance_the_underbog, instance_gruuls_lair, instance_blood_furnace, instance_hellfire_ramparts, instance_magtheridons_lair, instance_shattered_halls, instance_arcatraz, instance_the_botanica, instance_the_eye, instance_mechanar, instance_culling_of_stratholme, instance_onyxias_lair, instance_obsidian_sanctum, instance_trial_of_the_champion, instance_halls_of_reflection, instance_gundrak, instance_naxxramas, instance_eye_of_eternity, instance_oculus, instance_halls_of_lightning, instance_halls_of_stone, instance_ulduar, instance_utgarde_keep, instance_utgarde_pinnacle, and instance_violet_hold.
{ return nullptr; }
IsDatabaseBound()
bool InstanceMapScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return true; }