AzerothCore: azerothcore-wotlk/src/server/game/DataStores/M2Stores.h File Reference
M2Stores.h File Reference
#include "Define.h"
#include "Position.h"
#include <vector>
Classes
struct FlyByCamera
Functions
AC_GAME_API void LoadM2Cameras (std::string const &dataPath)
AC_GAME_API std::vector< FlyByCamera > const * GetFlyByCameras (uint32 cinematicCameraId)
Function Documentation
GetFlyByCameras()
AC_GAME_API std::vector< FlyByCamera > const * GetFlyByCameras (uint32 cinematicCameraId)
{
    return Acore::Containers::MapGetValuePtr(sFlyByCameraStore, cinematicCameraId);
}
References Acore::Containers::MapGetValuePtr(), and sFlyByCameraStore.
Referenced by CinematicMgr::BeginCinematic(), and debug_commandscript::HandleDebugPlayCinematicCommand().
LoadM2Cameras()
AC_GAME_API void LoadM2Cameras (std::string const & dataPath)
{
    sFlyByCameraStore.clear();
    LOG_INFO("server.loading", ">> Loading Cinematic Camera files");
    uint32 oldMSTime = getMSTime();
    for (CinematicCameraEntry const* dbcentry : sCinematicCameraStore)
    {
        std::string filenameWork = dataPath;
        filenameWork.append(dbcentry->Model);
        // Replace slashes (always to forward slash, because boost!)
        std::replace(filenameWork.begin(), filenameWork.end(), '\\', '/');
        boost::filesystem::path filename = filenameWork;
        // Convert to native format
        filename.make_preferred();
        // Replace mdx to .m2
        filename.replace_extension("m2");
        std::ifstream m2file(filename.string().c_str(), std::ios::in | std::ios::binary);
        if (!m2file.is_open())
            continue;
        // Get file size
        m2file.seekg(0, std::ios::end);
        std::streamoff fileSize = m2file.tellg();
        // Reject if not at least the size of the header
        if (static_cast<uint32>(fileSize) < sizeof(M2Header))
        {
            LOG_ERROR("server.loading", "Camera file {} is damaged. File is smaller than header size", filename.string());
            m2file.close();
            continue;
        }
        // Read 4 bytes (signature)
        m2file.seekg(0, std::ios::beg);
        char fileCheck[5];
        m2file.read(fileCheck, 4);
        fileCheck[4] = 0;
        // Check file has correct magic (MD20)
        if (strcmp(fileCheck, "MD20"))
        {
            LOG_ERROR("server.loading", "Camera file {} is damaged. File identifier not found", filename.string());
            m2file.close();
            continue;
        }
        // Now we have a good file, read it all into a vector of char's, then close the file.
        std::vector<char> buffer(fileSize);
        m2file.seekg(0, std::ios::beg);
        if (!m2file.read(buffer.data(), fileSize))
        {
            m2file.close();
            continue;
        }
        m2file.close();
        // Read header
        M2Header const* header = reinterpret_cast<M2Header const*>(buffer.data());
        if (header->ofsCameras + sizeof(M2Camera) > static_cast<uint32>(fileSize))
        {
            LOG_ERROR("server.loading", "Camera file {} is damaged. Camera references position beyond file end", filename.string());
            continue;
        }
        // Get camera(s) - Main header, then dump them.
        M2Camera const* cam = reinterpret_cast<M2Camera const*>(buffer.data() + header->ofsCameras);
        if (!readCamera(cam, fileSize, header, dbcentry))
            LOG_ERROR("server.loading", "Camera file {} is damaged. Camera references position beyond file end", filename.string());
    }
    LOG_INFO("server.loading", ">> Loaded {} Cinematic Waypoint Sets in {} ms", (uint32)sFlyByCameraStore.size(), GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References getMSTime(), GetMSTimeDiffToNow(), LOG_ERROR, LOG_INFO, M2Header::ofsCameras, readCamera(), sCinematicCameraStore, and sFlyByCameraStore.
Referenced by World::SetInitialWorldSettings().