AzerothCore: Acore::MessageDistDeliverer Struct Reference
Acore::MessageDistDeliverer Struct Reference
#include "GridNotifiers.h"
Public Member Functions
MessageDistDeliverer (WorldObject const *src, WorldPacket const *msg, float dist, bool own_team_only=false, Player const *skipped=nullptr, bool req3dDist=false)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (DynamicObjectMapType &m)
template<class SKIP >
void Visit (GridRefMgr< SKIP > &)
void SendPacket (Player *player)
Public Attributes
WorldObject const * i_source
WorldPacket const * i_message
uint32 i_phaseMask
float i_distSq
TeamId teamId
Player const * skipped_receiver
bool required3dDist
Detailed Description
Constructor & Destructor Documentation
MessageDistDeliverer()
Acore::MessageDistDeliverer::MessageDistDeliverer (WorldObject const * src, WorldPacket const * msg, float dist, bool own_team_only = false, Player const * skipped = nullptr, bool req3dDist = false) inline
            : i_source(src), i_message(msg), i_phaseMask(src->GetPhaseMask()), i_distSq(dist * dist)
            , teamId((own_team_only && src->IsPlayer()) ? src->ToPlayer()->GetTeamId() : TEAM_NEUTRAL)
            , skipped_receiver(skipped), required3dDist(req3dDist)
        {
        }
Member Function Documentation
SendPacket()
void Acore::MessageDistDeliverer::SendPacket (Player * player) inline
        {
            // never send packet to self
            if (player == i_source || (teamId != TEAM_NEUTRAL && player->GetTeamId() != teamId) || skipped_receiver == player)
                return;
            if (!player->HaveAtClient(i_source))
                return;
            player->GetSession()->SendPacket(i_message);
        }
References Player::GetSession(), Player::GetTeamId(), Player::HaveAtClient(), i_message, i_source, WorldSession::SendPacket(), skipped_receiver, TEAM_NEUTRAL, and teamId.
Referenced by Visit().
Visit() [1/4]
void MessageDistDeliverer::Visit (CreatureMapType & m)
{
    for (CreatureMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
    {
        Creature* target = iter->GetSource();
        if (!target->HasSharedVision() || !target->InSamePhase(i_phaseMask))
            continue;
        if (required3dDist)
        {
            if (target->GetExactDistSq(i_source) > i_distSq)
                continue;
        }
        else
            if (target->GetExactDist2dSq(i_source) > i_distSq)
                continue;
        // Send packet to all who are sharing the creature's vision
        SharedVisionList::const_iterator i = target->GetSharedVisionList().begin();
        for (; i != target->GetSharedVisionList().end(); ++i)
            if ((*i)->m_seer == target)
                SendPacket(*i);
    }
}
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), Position::GetExactDist2dSq(), Position::GetExactDistSq(), Unit::GetSharedVisionList(), Unit::HasSharedVision(), i_distSq, i_phaseMask, i_source, WorldObject::InSamePhase(), required3dDist, and SendPacket().
Visit() [2/4]
void MessageDistDeliverer::Visit (DynamicObjectMapType & m)
{
    for (DynamicObjectMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
    {
        DynamicObject* target = iter->GetSource();
        if (!target->GetCasterGUID().IsPlayer() || !target->InSamePhase(i_phaseMask))
            continue;
        // Xinef: Check whether the dynobject allows to see through it
        if (!target->IsViewpoint())
            continue;
        if (required3dDist)
        {
            if (target->GetExactDistSq(i_source) > i_distSq)
                continue;
        }
        else
            if (target->GetExactDist2dSq(i_source) > i_distSq)
                continue;
        // Send packet back to the caster if the caster has vision of dynamic object
        Player* caster = (Player*)target->GetCaster();
        if (caster && caster->m_seer == target)
            SendPacket(caster);
    }
}
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), DynamicObject::GetCaster(), DynamicObject::GetCasterGUID(), Position::GetExactDist2dSq(), Position::GetExactDistSq(), i_distSq, i_phaseMask, i_source, WorldObject::InSamePhase(), ObjectGuid::IsPlayer(), DynamicObject::IsViewpoint(), Player::m_seer, required3dDist, and SendPacket().
Visit() [3/4]
template<class SKIP > void Acore::MessageDistDeliverer::Visit (GridRefMgr< SKIP > &) inline
{}
Visit() [4/4]
void MessageDistDeliverer::Visit (PlayerMapType & m)
{
    for (PlayerMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
    {
        Player* target = iter->GetSource();
        if (!target->InSamePhase(i_phaseMask))
            continue;
        if (required3dDist)
        {
            if (target->GetExactDistSq(i_source) > i_distSq)
                continue;
        }
        else
            if (target->GetExactDist2dSq(i_source) > i_distSq)
                continue;
        // Send packet to all who are sharing the player's vision
        if (target->HasSharedVision())
        {
            SharedVisionList::const_iterator i = target->GetSharedVisionList().begin();
            for (; i != target->GetSharedVisionList().end(); ++i)
                if ((*i)->m_seer == target)
                    SendPacket(*i);
        }
        if (target->m_seer == target || target->GetVehicle())
            SendPacket(target);
    }
}
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), Position::GetExactDist2dSq(), Position::GetExactDistSq(), Unit::GetSharedVisionList(), Unit::GetVehicle(), Unit::HasSharedVision(), i_distSq, i_phaseMask, i_source, WorldObject::InSamePhase(), Player::m_seer, required3dDist, and SendPacket().
Member Data Documentation
i_distSq
float Acore::MessageDistDeliverer::i_distSq
Referenced by Visit().
i_message
WorldPacket const* Acore::MessageDistDeliverer::i_message
Referenced by SendPacket().
i_phaseMask
uint32 Acore::MessageDistDeliverer::i_phaseMask
Referenced by Visit().
i_source
WorldObject const* Acore::MessageDistDeliverer::i_source
Referenced by SendPacket(), and Visit().
required3dDist
bool Acore::MessageDistDeliverer::required3dDist
Referenced by Visit().
skipped_receiver
Player const* Acore::MessageDistDeliverer::skipped_receiver
Referenced by SendPacket().
teamId
TeamId Acore::MessageDistDeliverer::teamId
Referenced by SendPacket().