AzerothCore: npc_high_overlord_saurfang_icc Class Reference
npc_high_overlord_saurfang_icc Class Reference
Classes
struct npc_high_overlord_saurfangAI
Public Member Functions
npc_high_overlord_saurfang_icc ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_high_overlord_saurfang_icc()
npc_high_overlord_saurfang_icc::npc_high_overlord_saurfang_icc () inline
: CreatureScript("npc_high_overlord_saurfang_icc") { }
Member Function Documentation
GetAI()
CreatureAI * npc_high_overlord_saurfang_icc::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return GetIcecrownCitadelAI<npc_high_overlord_saurfangAI>(creature);
    }
OnGossipHello()
bool npc_high_overlord_saurfang_icc::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        InstanceScript* instance = creature->GetInstanceScript();
        if (instance && instance->GetBossState(DATA_DEATHBRINGER_SAURFANG) != DONE && instance->GetBossState(DATA_DEATHBRINGER_SAURFANG) != IN_PROGRESS)
        {
            AddGossipItemFor(player, 10953, 0, GOSSIP_SENDER_INFO, -ACTION_START_EVENT);
            SendGossipMenuFor(player, player->GetGossipTextId(10953, creature), creature->GetGUID());
        }
        return true;
    }
References ACTION_START_EVENT, AddGossipItemFor(), DATA_DEATHBRINGER_SAURFANG, DONE, InstanceScript::GetBossState(), Player::GetGossipTextId(), Object::GetGUID(), WorldObject::GetInstanceScript(), GOSSIP_SENDER_INFO, IN_PROGRESS, and SendGossipMenuFor().
OnGossipSelect()
bool npc_high_overlord_saurfang_icc::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
    {
        InstanceScript* instance = creature->GetInstanceScript();
        if (instance && instance->GetBossState(DATA_DEATHBRINGER_SAURFANG) != DONE && instance->GetBossState(DATA_DEATHBRINGER_SAURFANG) != IN_PROGRESS)
        {
            ClearGossipMenuFor(player);
            CloseGossipMenuFor(player);
            if (action == -ACTION_START_EVENT)
                creature->AI()->DoAction(ACTION_START_EVENT);
        }
        return true;
    }
References ACTION_START_EVENT, Creature::AI(), ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_DEATHBRINGER_SAURFANG, UnitAI::DoAction(), DONE, InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), and IN_PROGRESS.