AzerothCore: azerothcore-wotlk/src/server/database/Database/QueryCallback.cpp File Reference
QueryCallback.cpp File Reference
#include "QueryCallback.h"
#include "Duration.h"
#include "Errors.h"
Classes
struct QueryCallback::QueryCallbackData
Functions
template<typename T , typename... Args>
void Construct (T &t, Args &&... args)
template<typename T >
void Destroy (T &t)
template<typename T >
void ConstructActiveMember (T *obj)
template<typename T >
void DestroyActiveMember (T *obj)
template<typename T >
void MoveFrom (T *to, T &&from)
Function Documentation
Construct()
template<typename T , typename... Args> void Construct (T & t, Args &&... args) inline
{
    new (&t) T(std::forward<Args>(args)...);
}
Referenced by QueryCallback::QueryCallback().
ConstructActiveMember()
template<typename T > void ConstructActiveMember (T * obj) inline
{
    if (!obj->_isPrepared)
        Construct(obj->_string);
    else
        Construct(obj->_prepared);
}
Referenced by QueryCallback::operator=(), and QueryCallback::QueryCallback().
Destroy()
template<typename T > void Destroy (T & t) inline
{
    t.~T();
}
DestroyActiveMember()
template<typename T > void DestroyActiveMember (T * obj) inline
{
    if (!obj->_isPrepared)
        Destroy(obj->_string);
    else
        Destroy(obj->_prepared);
}
Referenced by QueryCallback::operator=().
MoveFrom()
template<typename T > void MoveFrom (T * to, T && from) inline
{
    ASSERT(to->_isPrepared == from._isPrepared);
    if (!to->_isPrepared)
        to->_string = std::move(from._string);
    else
        to->_prepared = std::move(from._prepared);
}
Referenced by QueryCallback::operator=(), and QueryCallback::QueryCallback().