AzerothCore: boss_majordomo Class Reference
boss_majordomo Class Reference
Classes
struct boss_majordomoAI
Public Member Functions
boss_majordomo ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
boss_majordomo()
boss_majordomo::boss_majordomo () inline
: CreatureScript("boss_majordomo") {}
Member Function Documentation
GetAI()
CreatureAI * boss_majordomo::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return GetMoltenCoreAI<boss_majordomoAI>(creature);
    }
OnGossipHello()
bool boss_majordomo::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        AddGossipItemFor(player, GOSSIP_ITEM_SUMMON_1, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
        SendGossipMenuFor(player, TEXT_ID_SUMMON_1, creature->GetGUID());
        return true;
    }
References AddGossipItemFor(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ITEM_SUMMON_1, GOSSIP_SENDER_MAIN, SendGossipMenuFor(), and TEXT_ID_SUMMON_1.
OnGossipSelect()
bool boss_majordomo::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
    {
        ClearGossipMenuFor(player);
        switch (action)
        {
            case GOSSIP_ACTION_INFO_DEF:
            {
                AddGossipItemFor(player, GOSSIP_ITEM_SUMMON_2, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                SendGossipMenuFor(player, TEXT_ID_SUMMON_2, creature->GetGUID());
                break;
            }
            case GOSSIP_ACTION_INFO_DEF+1:
            {
                AddGossipItemFor(player, GOSSIP_ITEM_SUMMON_2, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                SendGossipMenuFor(player, TEXT_ID_SUMMON_2, creature->GetGUID());
                break;
            }
            case GOSSIP_ACTION_INFO_DEF+2:
            {
                AddGossipItemFor(player, GOSSIP_ITEM_SUMMON_3, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                SendGossipMenuFor(player, TEXT_ID_SUMMON_3, creature->GetGUID());
                break;
            }
            case GOSSIP_ACTION_INFO_DEF+3:
            {
                CloseGossipMenuFor(player);
                creature->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                creature->AI()->Talk(SAY_RAG_SUM_1, player);
                creature->AI()->DoAction(ACTION_START_RAGNAROS_INTRO);
                break;
            }
            default:
                CloseGossipMenuFor(player);
                break;
        }
        return true;
    }
References ACTION_START_RAGNAROS_INTRO, AddGossipItemFor(), Creature::AI(), ClearGossipMenuFor(), CloseGossipMenuFor(), UnitAI::DoAction(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ITEM_SUMMON_2, GOSSIP_ITEM_SUMMON_3, GOSSIP_SENDER_MAIN, Unit::RemoveNpcFlag(), SAY_RAG_SUM_1, SendGossipMenuFor(), CreatureAI::Talk(), TEXT_ID_SUMMON_2, TEXT_ID_SUMMON_3, and UNIT_NPC_FLAG_GOSSIP.