AzerothCore: MPQFile Class Reference
MPQFile Class Reference
#include "mpq_libmpq04.h"
Public Member Functions
MPQFile (const char *filename)
~MPQFile ()
std::size_t read (void *dest, std::size_t bytes)
std::size_t getSize ()
std::size_t getPos ()
char * getBuffer ()
char * getPointer ()
bool isEof ()
void seek (int offset)
void seekRelative (int offset)
void close ()
MPQFile (const char *filename)
~MPQFile ()
std::size_t read (void *dest, std::size_t bytes)
std::size_t getSize ()
std::size_t getPos ()
char * getBuffer ()
char * getPointer ()
bool isEof ()
void seek (int offset)
void seekRelative (int offset)
void close ()
Private Member Functions
MPQFile (const MPQFile &)
void operator= (const MPQFile &)
MPQFile (const MPQFile &)
void operator= (const MPQFile &)
Private Attributes
bool eof
char * buffer
libmpq__off_t pointer
libmpq__off_t size
Detailed Description
Constructor & Destructor Documentation
MPQFile() [1/4]
MPQFile::MPQFile (const MPQFile &) inline private
{}
MPQFile() [2/4]
MPQFile::MPQFile (const char * filename)
                                    :
    eof(false),
    buffer(nullptr),
    pointer(0),
    size(0)
{
    for (auto & gOpenArchive : gOpenArchives)
    {
        mpq_archive* mpq_a = gOpenArchive->mpq_a;
        uint32_t filenum;
        if (libmpq__file_number(mpq_a, filename, &filenum)) continue;
        libmpq__off_t transferred;
        libmpq__file_unpacked_size(mpq_a, filenum, &size);
        // HACK: in patch.mpq some files don't want to open and give 1 for filesize
        if (size <= 1)
        {
            //            printf("warning: file %s has size %d; cannot read.\n", filename, size);
            eof = true;
            buffer = nullptr;
            return;
        }
        buffer = new char[size];
        //libmpq_file_getdata
        libmpq__file_read(mpq_a, filenum, (unsigned char*)buffer, size, &transferred);
        /*libmpq_file_getdata(&mpq_a, hash, fileno, (unsigned char*)buffer);*/
        return;
    }
    eof = true;
    buffer = nullptr;
}
References buffer, eof, gOpenArchives, and size.
~MPQFile() [1/2]
MPQFile::~MPQFile () inline
{ close(); }
References close().
MPQFile() [3/4]
MPQFile::MPQFile (const MPQFile &) inline private
{}
MPQFile() [4/4]
MPQFile::MPQFile (const char * filename)
~MPQFile() [2/2]
MPQFile::~MPQFile () inline
{ close(); }
References close().
Member Function Documentation
close() [1/2]
void MPQFile::close ()
{
    delete[] buffer;
    buffer = nullptr;
    eof = true;
}
References buffer, and eof.
Referenced by ADTFile::init(), WDTFile::init(), FileLoader::loadFile(), DBCFile::open(), Model::open(), WMORoot::open(), WMOGroup::open(), ReadBuild(), ADTFile::~ADTFile(), ~MPQFile(), and WDTFile::~WDTFile().
close() [2/2]
void MPQFile::close ()
getBuffer() [1/2]
char * MPQFile::getBuffer () inline
{ return buffer; }
References buffer.
Referenced by Model::open().
getBuffer() [2/2]
char * MPQFile::getBuffer () inline
{ return buffer; }
References buffer.
getPointer() [1/2]
char * MPQFile::getPointer () inline
{ return buffer + pointer; }
References buffer, and pointer.
Referenced by ExtractFile(), WMORoot::open(), and ReadBuild().
getPointer() [2/2]
char * MPQFile::getPointer () inline
{ return buffer + pointer; }
References buffer, and pointer.
getPos() [1/2]
std::size_t MPQFile::getPos () inline
{ return pointer; }
References pointer.
Referenced by ADTFile::init(), WDTFile::init(), WMORoot::open(), and WMOGroup::open().
getPos() [2/2]
std::size_t MPQFile::getPos () inline
{ return pointer; }
References pointer.
getSize() [1/2]
std::size_t MPQFile::getSize () inline
{ return size; }
References size.
Referenced by ExtractFile(), FileLoader::loadFile(), and ReadBuild().
getSize() [2/2]
std::size_t MPQFile::getSize () inline
{ return size; }
References size.
isEof() [1/2]
bool MPQFile::isEof () inline
{ return eof; }
References eof.
Referenced by ExtractFile(), ADTFile::init(), WDTFile::init(), FileLoader::loadFile(), Model::open(), WMORoot::open(), WMOGroup::open(), and ReadBuild().
isEof() [2/2]
bool MPQFile::isEof () inline
{ return eof; }
References eof.
operator=() [1/2]
void MPQFile::operator= (const MPQFile &) inline private
{}
operator=() [2/2]
void MPQFile::operator= (const MPQFile &) inline private
{}
read() [1/2]
std::size_t MPQFile::read (void * dest, std::size_t bytes)
{
    if (eof) return 0;
    std::size_t rpos = pointer + bytes;
    if (rpos > std::size_t(size))
    {
        bytes = size - pointer;
        eof = true;
    }
    memcpy(dest, &(buffer[pointer]), bytes);
    pointer = rpos;
    return bytes;
}
References buffer, eof, pointer, and size.
Referenced by ADTFile::init(), WDTFile::init(), FileLoader::loadFile(), DBCFile::open(), Model::open(), WMORoot::open(), and WMOGroup::open().
read() [2/2]
std::size_t MPQFile::read (void * dest, std::size_t bytes)
seek() [1/2]
void MPQFile::seek (int offset)
{
    pointer = offset;
    eof = (pointer >= size);
}
References eof, pointer, and size.
Referenced by ADTFile::init(), WDTFile::init(), Model::open(), WMORoot::open(), and WMOGroup::open().
seek() [2/2]
void MPQFile::seek (int offset)
seekRelative() [1/2]
void MPQFile::seekRelative (int offset)
{
    pointer += offset;
    eof = (pointer >= size);
}
References eof, pointer, and size.
Referenced by Model::open().
seekRelative() [2/2]
void MPQFile::seekRelative (int offset)
Member Data Documentation
buffer
char * MPQFile::buffer private
Referenced by close(), getBuffer(), getPointer(), MPQFile(), and read().
eof
bool MPQFile::eof private
Referenced by close(), isEof(), MPQFile(), read(), seek(), and seekRelative().
pointer
libmpq__off_t MPQFile::pointer private
Referenced by getPointer(), getPos(), read(), seek(), and seekRelative().
size
libmpq__off_t MPQFile::size private
Referenced by getSize(), MPQFile(), read(), seek(), and seekRelative().