AzerothCore: Acore::AnyUnfriendlyUnitInObjectRangeCheck Class Reference
Acore::AnyUnfriendlyUnitInObjectRangeCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
AnyUnfriendlyUnitInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range)
bool operator() (Unit *u)
Private Attributes
WorldObject const * i_obj
Unit const * i_funit
float i_range
Detailed Description
Constructor & Destructor Documentation
AnyUnfriendlyUnitInObjectRangeCheck()
Acore::AnyUnfriendlyUnitInObjectRangeCheck::AnyUnfriendlyUnitInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range) inline
: i_obj(obj), i_funit(funit), i_range(range) {}
Member Function Documentation
operator()()
bool Acore::AnyUnfriendlyUnitInObjectRangeCheck::operator() (Unit * u) inline
        {
            if (u->IsAlive() && !u->IsCritter() && i_obj->IsWithinDistInMap(u, i_range) && !i_funit->IsFriendlyTo(u) &&
                    (i_funit->GetTypeId() != TYPEID_UNIT || !i_funit->ToCreature()->IsAvoidingAOE())) // pussywizard
                return true;
            else
                return false;
        }
References Object::GetTypeId(), i_funit, i_obj, i_range, Unit::IsAlive(), Creature::IsAvoidingAOE(), Unit::IsCritter(), Unit::IsFriendlyTo(), WorldObject::IsWithinDistInMap(), Object::ToCreature(), and TYPEID_UNIT.
Member Data Documentation
i_funit
Unit const* Acore::AnyUnfriendlyUnitInObjectRangeCheck::i_funit private
Referenced by operator()().
i_obj
WorldObject const* Acore::AnyUnfriendlyUnitInObjectRangeCheck::i_obj private
Referenced by operator()().
i_range
float Acore::AnyUnfriendlyUnitInObjectRangeCheck::i_range private
Referenced by operator()().