AzerothCore: Acore::BroadcastTextBuilder Class Reference
Acore::BroadcastTextBuilder Class Reference
#include "ChatTextBuilder.h"
Public Member Functions
BroadcastTextBuilder (WorldObject const *obj, ChatMsg msgType, uint32 textId, uint8 gender, WorldObject const *target=nullptr, uint32 achievementId=0)
void operator() (WorldPacket &data, LocaleConstant locale) const
std::size_t operator() (WorldPacket *data, LocaleConstant locale) const
Private Attributes
WorldObject const * _source
ChatMsg _msgType
uint32 _textId
uint8 _gender
WorldObject const * _target
uint32 _achievementId
Detailed Description
Constructor & Destructor Documentation
BroadcastTextBuilder()
Acore::BroadcastTextBuilder::BroadcastTextBuilder (WorldObject const * obj, ChatMsg msgType, uint32 textId, uint8 gender, WorldObject const * target = nullptr, uint32 achievementId = 0) inline
                : _source(obj), _msgType(msgType), _textId(textId), _gender(gender), _target(target), _achievementId(achievementId) { }
Member Function Documentation
operator()() [1/2]
void Acore::BroadcastTextBuilder::operator() (WorldPacket & data, LocaleConstant locale) const
{
    BroadcastText const* bct = sObjectMgr->GetBroadcastText(_textId);
    ChatHandler::BuildChatPacket(data, _msgType, bct ? Language(bct->LanguageID) : LANG_UNIVERSAL, _source, _target, bct ? bct->GetText(locale, _gender) : "", _achievementId, "", locale);
}
References _achievementId, _gender, _msgType, _source, _target, _textId, ChatHandler::BuildChatPacket(), BroadcastText::GetText(), LANG_UNIVERSAL, BroadcastText::LanguageID, and sObjectMgr.
operator()() [2/2]
std::size_t Acore::BroadcastTextBuilder::operator() (WorldPacket * data, LocaleConstant locale) const
{
    BroadcastText const* bct = sObjectMgr->GetBroadcastText(_textId);
    return ChatHandler::BuildChatPacket(*data, _msgType, bct ? Language(bct->LanguageID) : LANG_UNIVERSAL, _source, _target, bct ? bct->GetText(locale, _gender) : "", _achievementId, "", locale);
}
References ChatHandler::BuildChatPacket(), BroadcastText::GetText(), LANG_UNIVERSAL, BroadcastText::LanguageID, and sObjectMgr.
Member Data Documentation
_achievementId
uint32 Acore::BroadcastTextBuilder::_achievementId private
Referenced by operator()().
_gender
uint8 Acore::BroadcastTextBuilder::_gender private
Referenced by operator()().
_msgType
ChatMsg Acore::BroadcastTextBuilder::_msgType private
Referenced by operator()().
_source
WorldObject const* Acore::BroadcastTextBuilder::_source private
Referenced by operator()().
_target
WorldObject const* Acore::BroadcastTextBuilder::_target private
Referenced by operator()().
_textId
uint32 Acore::BroadcastTextBuilder::_textId private
Referenced by operator()().