AzerothCore: npc_hor_leader_second Class Reference
npc_hor_leader_second Class Reference
Classes
struct npc_hor_leader_secondAI
Public Member Functions
npc_hor_leader_second ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_hor_leader_second()
npc_hor_leader_second::npc_hor_leader_second () inline
: CreatureScript("npc_hor_leader_second") { }
Member Function Documentation
GetAI()
CreatureAI * npc_hor_leader_second::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return GetHallsOfReflectionAI<npc_hor_leader_secondAI>(creature);
    }
OnGossipSelect()
bool npc_hor_leader_second::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32) inline override virtual
Reimplemented from CreatureScript.
    {
        if (!creature->HasNpcFlag(UNIT_NPC_FLAG_GOSSIP))
            return true;
        ClearGossipMenuFor(player);
        if (InstanceScript* pInstance = creature->GetInstanceScript())
            if (!pInstance->GetData(DATA_LICH_KING))
            {
                creature->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                creature->AI()->DoAction(ACTION_START_LK_FIGHT_REAL);
                return true;
            }
        return true;
    }
References ACTION_START_LK_FIGHT_REAL, Creature::AI(), ClearGossipMenuFor(), DATA_LICH_KING, UnitAI::DoAction(), WorldObject::GetInstanceScript(), Unit::HasNpcFlag(), Unit::RemoveNpcFlag(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAG_QUESTGIVER.