AzerothCore: NPCStaveQuestAI Struct Reference
NPCStaveQuestAI Struct Reference
#include "npc_stave_of_ancients.h"
Public Member Functions
NPCStaveQuestAI (Creature *creature)
uint32 GetFormEntry (std::string)
bool InNormalForm ()
void RevealForm ()
void StorePlayerGUID ()
Player * GetGossipPlayer ()
bool IsAllowedEntry (uint32)
bool UnitIsUnfair (Unit *unit)
bool IsFairFight ()
bool ValidThreatlist ()
void SetHomePosition ()
void PrepareForEncounter ()
void ClearLootIfUnfair (Unit *killer)
bool PlayerEligibleForReward (Unit *killer)
void StoreAttackerGuidValue (Unit *attacker)
bool QuestIncomplete (Unit *unit, uint32 questItem)
void ResetState (uint32)
void EvadeOnFeignDeath ()
virtual void AttackStart (Unit *)
virtual void AttackedBy (Unit *)
virtual void JustDied (Unit *)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
ObjectGuid gossipPlayerGUID
ObjectGuid playerGUID
bool encounterStarted
ThreatContainer::StorageType const & threatList = me->GetThreatMgr().GetThreatList()
std::map< int, int > entryKeys
std::map< int, std::map< std::string, int > > entryList
std::vector< uint64 > attackerGuids
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
NPCStaveQuestAI()
NPCStaveQuestAI::NPCStaveQuestAI (Creature * creature) inline
: ScriptedAI(creature) { }
Member Function Documentation
AttackedBy()
void NPCStaveQuestAI::AttackedBy (Unit * attacker) virtual
Reimplemented from CreatureAI.
{
    StoreAttackerGuidValue(attacker);
}
References StoreAttackerGuidValue().
AttackStart()
void NPCStaveQuestAI::AttackStart (Unit * target) virtual
Reimplemented from ScriptedAI.
{
    if (playerGUID.IsEmpty() && !InNormalForm())
    {
        StorePlayerGUID();
    }
    ScriptedAI::AttackStart(target);
}
References ScriptedAI::AttackStart(), InNormalForm(), ObjectGuid::IsEmpty(), playerGUID, and StorePlayerGUID().
ClearLootIfUnfair()
void NPCStaveQuestAI::ClearLootIfUnfair (Unit * killer)
{
    // Remove loot if there is more than 1 attacker or Player doesn't have the quest
    // this should prevent party kills and looting the quest item without putting any effort
    if (attackerGuids.size() > 1 || !PlayerEligibleForReward(killer))
    {
        me->loot.clear();
        return;
    }
}
References attackerGuids, Loot::clear(), Creature::loot, ScriptedAI::me, and PlayerEligibleForReward().
Referenced by JustDied().
EvadeOnFeignDeath()
void NPCStaveQuestAI::EvadeOnFeignDeath ()
{
    Player* player = ObjectAccessor::GetPlayer(*me, playerGUID);
    if (player && player->HasAura(SPELL_FEIGN_DEATH))
    {
        EnterEvadeMode();
    }
}
References CreatureAI::EnterEvadeMode(), ObjectAccessor::GetPlayer(), Unit::HasAura(), ScriptedAI::me, playerGUID, and SPELL_FEIGN_DEATH.
Referenced by npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), and npc_precious::npc_preciousAI::UpdateAI().
GetFormEntry()
uint32 NPCStaveQuestAI::GetFormEntry (std::string type)
{
    uint32 currentEntry = me->GetEntry();
    uint32 entryKey = entryKeys[currentEntry];
    return entryList[entryKey][type];
}
References entryKeys, entryList, Object::GetEntry(), and ScriptedAI::me.
Referenced by InNormalForm(), and RevealForm().
GetGossipPlayer()
Player * NPCStaveQuestAI::GetGossipPlayer ()
{
    return ObjectAccessor::GetPlayer(*me, gossipPlayerGUID);
}
References ObjectAccessor::GetPlayer(), gossipPlayerGUID, and ScriptedAI::me.
Referenced by npc_simone::npc_simoneAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
InNormalForm()
bool NPCStaveQuestAI::InNormalForm ()
{
    return me->GetEntry() == GetFormEntry("normal");
}
References Object::GetEntry(), GetFormEntry(), and ScriptedAI::me.
Referenced by AttackStart(), npc_artorius::npc_artoriusAI::JustEngagedWith(), npc_simone::npc_simoneAI::JustEngagedWith(), npc_nelson::npc_nelsonAI::JustEngagedWith(), npc_franklin::npc_franklinAI::JustEngagedWith(), ResetState(), RevealForm(), npc_artorius::npc_artoriusAI::SpellHit(), npc_simone::npc_simoneAI::SpellHit(), npc_nelson::npc_nelsonAI::SpellHit(), npc_franklin::npc_franklinAI::SpellHit(), npc_simone::npc_simoneAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
IsAllowedEntry()
bool NPCStaveQuestAI::IsAllowedEntry (uint32 entry)
{
    uint32 allowedEntries[4] = { 0, 12999, 19833, 19921 }; //player, World Invisible Trigger(traps) and snake trap snakes
    bool isAllowed = std::find(std::begin(allowedEntries), std::end(allowedEntries), entry) != std::end(allowedEntries);
    return isAllowed;
}
Referenced by StoreAttackerGuidValue(), and UnitIsUnfair().
IsFairFight()
bool NPCStaveQuestAI::IsFairFight ()
{
    for (ThreatContainer::StorageType::const_iterator itr = threatList.begin(); itr != threatList.end(); ++itr)
    {
        Unit* unit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid());
        if (!(*itr)->GetThreat())
        {
            // if target threat is 0 its fair, this prevents despawn in the case when
            // there is a bystander since UpdateVictim adds nearby enemies to the threatlist
            continue;
        }
        if (UnitIsUnfair(unit))
        {
            return false;
        }
    }
    return true;
}
References ObjectAccessor::GetUnit(), ScriptedAI::me, threatList, and UnitIsUnfair().
Referenced by ValidThreatlist().
JustDied()
void NPCStaveQuestAI::JustDied (Unit * killer) virtual
Reimplemented from ScriptedAI.
Reimplemented in npc_simone::npc_simoneAI.
{
    // Prevent looting if killer doesn't have the quest
    ClearLootIfUnfair(killer);
}
References ClearLootIfUnfair().
Referenced by npc_simone::npc_simoneAI::JustDied().
PlayerEligibleForReward()
bool NPCStaveQuestAI::PlayerEligibleForReward (Unit * killer)
{
    if (!killer)
    {
        return true;
    }
    if (Player* player = killer->ToPlayer())
    {
        if (player->GetQuestStatus(QUEST_STAVE_OF_THE_ANCIENTS) != QUEST_STATUS_INCOMPLETE)
        {
            return false;
        }
    }
    return true;
}
References QUEST_STATUS_INCOMPLETE, QUEST_STAVE_OF_THE_ANCIENTS, and Object::ToPlayer().
Referenced by ClearLootIfUnfair().
PrepareForEncounter()
void NPCStaveQuestAI::PrepareForEncounter ()
{
    encounterStarted = true;
    me->GetMotionMaster()->MoveIdle();
    me->GetMotionMaster()->Clear();
    SetHomePosition();
    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
    me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
}
References MotionMaster::Clear(), encounterStarted, Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MoveIdle(), Unit::RemoveNpcFlag(), SetHomePosition(), Unit::SetUnitFlag(), UNIT_FLAG_NON_ATTACKABLE, and UNIT_NPC_FLAG_GOSSIP.
Referenced by npc_artorius::npc_artoriusAI::DoAction(), npc_nelson::npc_nelsonAI::DoAction(), npc_simone::npc_simoneAI::ScheduleEncounterStart(), and npc_franklin::npc_franklinAI::ScheduleEncounterStart().
QuestIncomplete()
bool NPCStaveQuestAI::QuestIncomplete (Unit * unit, uint32 questItem)
{
    if (!unit || !unit->IsPlayer())
    {
        return true;
    }
    QuestStatus questStatus = unit->ToPlayer()->GetQuestStatus(QUEST_STAVE_OF_THE_ANCIENTS);
    bool hasQuestItem = unit->ToPlayer()->HasItemCount(questItem, 1, true);
    bool isIncomplete = questStatus == QUEST_STATUS_INCOMPLETE && !hasQuestItem;
    return isIncomplete;
}
References Player::GetQuestStatus(), Player::HasItemCount(), Object::IsPlayer(), QUEST_STATUS_INCOMPLETE, QUEST_STAVE_OF_THE_ANCIENTS, and Object::ToPlayer().
Referenced by npc_artorius::npc_artoriusAI::JustEngagedWith(), npc_simone::npc_simoneAI::JustEngagedWith(), npc_nelson::npc_nelsonAI::JustEngagedWith(), npc_franklin::npc_franklinAI::JustEngagedWith(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
ResetState()
void NPCStaveQuestAI::ResetState (uint32 aura = 0)
{
    encounterStarted = false;
    playerGUID.Clear();
    attackerGuids.clear();
    if (InNormalForm())
    {
        me->m_Events.KillAllEvents(true);
        me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
    }
    me->RemoveAura(aura);
}
References attackerGuids, ObjectGuid::Clear(), encounterStarted, InNormalForm(), EventProcessor::KillAllEvents(), Unit::m_Events, ScriptedAI::me, playerGUID, Unit::RemoveAura(), Unit::SetNpcFlag(), and UNIT_NPC_FLAG_GOSSIP.
Referenced by npc_artorius::npc_artoriusAI::Reset(), npc_precious::npc_preciousAI::Reset(), npc_simone::npc_simoneAI::Reset(), npc_nelson::npc_nelsonAI::Reset(), and npc_franklin::npc_franklinAI::Reset().
RevealForm()
void NPCStaveQuestAI::RevealForm ()
{
    if (encounterStarted && InNormalForm())
    {
        me->UpdateEntry(GetFormEntry("evil"));
        me->SetFullHealth();
        me->DespawnOrUnsummon(900000);
    }
}
References Creature::DespawnOrUnsummon(), encounterStarted, GetFormEntry(), InNormalForm(), ScriptedAI::me, Unit::SetFullHealth(), and Creature::UpdateEntry().
Referenced by npc_precious::npc_preciousAI::JustEngagedWith(), npc_artorius::npc_artoriusAI::JustEngagedWith(), npc_simone::npc_simoneAI::JustEngagedWith(), npc_nelson::npc_nelsonAI::JustEngagedWith(), npc_franklin::npc_franklinAI::JustEngagedWith(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
SetHomePosition()
void NPCStaveQuestAI::SetHomePosition ()
{
    Position homePosition = me->GetPosition();
    if (homePosition.IsPositionValid())
    {
        me->SetHomePosition(homePosition);
    }
}
References Position::GetPosition(), Position::IsPositionValid(), ScriptedAI::me, and Creature::SetHomePosition().
Referenced by PrepareForEncounter(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
StoreAttackerGuidValue()
void NPCStaveQuestAI::StoreAttackerGuidValue (Unit * attacker)
{
    if (!attacker)
    {
        return;
    }
    uint64 guidValue = attacker->GetGUID().GetRawValue();
    bool isGUIDPresent = std::find(attackerGuids.begin(), attackerGuids.end(), guidValue) != attackerGuids.end();
    // don't store snaketrap's snakes and trap triggers
    if (isGUIDPresent || (IsAllowedEntry(attacker->GetEntry()) && !attacker->IsPlayer()))
    {
        return;
    }
    else
    {
        attackerGuids.push_back(guidValue);
    }
}
References attackerGuids, Object::GetEntry(), Object::GetGUID(), ObjectGuid::GetRawValue(), IsAllowedEntry(), and Object::IsPlayer().
Referenced by AttackedBy().
StorePlayerGUID()
void NPCStaveQuestAI::StorePlayerGUID ()
{
    if (!playerGUID.IsEmpty())
    {
        return;
    }
    for (ThreatContainer::StorageType::const_iterator itr = threatList.begin(); itr != threatList.end(); ++itr)
    {
        if ((*itr)->getTarget()->IsPlayer())
        {
            playerGUID = (*itr)->getUnitGuid();
        }
    }
}
References ObjectGuid::IsEmpty(), playerGUID, and threatList.
Referenced by AttackStart().
UnitIsUnfair()
bool NPCStaveQuestAI::UnitIsUnfair (Unit * unit)
{
    if (!unit || playerGUID.IsEmpty())
    {
        return false;
    }
    if (unit->IsPlayer())
    {
        if (playerGUID != unit->GetGUID())
        {
            return true;
        }
    }
    else
    {
        if (unit->GetOwnerGUID() != playerGUID)
        {
            // if a creature attacking isn't owned by the player its unfair
            return true;
        }
        else if (!IsAllowedEntry(unit->GetEntry()))
        {
            // if not in the whitelist its unfair
            return true;
        }
    }
    return false;
}
References Object::GetEntry(), Object::GetGUID(), Unit::GetOwnerGUID(), IsAllowedEntry(), ObjectGuid::IsEmpty(), Object::IsPlayer(), and playerGUID.
Referenced by IsFairFight(), npc_artorius::npc_artoriusAI::JustEngagedWith(), npc_simone::npc_simoneAI::JustEngagedWith(), npc_nelson::npc_nelsonAI::JustEngagedWith(), npc_franklin::npc_franklinAI::JustEngagedWith(), npc_nelson::npc_nelsonAI::SummonedCreatureDies(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
ValidThreatlist()
bool NPCStaveQuestAI::ValidThreatlist ()
{
    if (threatList.size() == 1)
    {
        return true;
    }
    bool isFair = IsFairFight();
    return isFair;
}
References IsFairFight(), and threatList.
Referenced by npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
Member Data Documentation
attackerGuids
std::vector<uint64> NPCStaveQuestAI::attackerGuids
Referenced by ClearLootIfUnfair(), ResetState(), and StoreAttackerGuidValue().
encounterStarted
bool NPCStaveQuestAI::encounterStarted
Referenced by npc_nelson::npc_nelsonAI::JustEngagedWith(), PrepareForEncounter(), ResetState(), and RevealForm().
entryKeys
std::map<int, int> NPCStaveQuestAI::entryKeys
Initial value:
= {
        { ARTORIUS_NORMAL_ENTRY, 1 },
        { ARTORIUS_EVIL_ENTRY,   1 },
        { SIMONE_NORMAL_ENTRY,   2 },
        { SIMONE_EVIL_ENTRY,     2 },
        { PRECIOUS_NORMAL_ENTRY, 3 },
        { PRECIOUS_EVIL_ENTRY,   3 },
        { NELSON_NORMAL_ENTRY,   4 },
        { NELSON_EVIL_ENTRY,     4 },
        { FRANKLIN_NORMAL_ENTRY, 5 },
        { FRANKLIN_EVIL_ENTRY,   5 }
    }
Referenced by GetFormEntry().
entryList
std::map<int, std::map<std::string, int> > NPCStaveQuestAI::entryList
Referenced by GetFormEntry().
gossipPlayerGUID
ObjectGuid NPCStaveQuestAI::gossipPlayerGUID
Referenced by GetGossipPlayer(), npc_simone::npc_simoneAI::ScheduleEncounterStart(), and npc_franklin::npc_franklinAI::ScheduleEncounterStart().
playerGUID
ObjectGuid NPCStaveQuestAI::playerGUID
Referenced by AttackStart(), EvadeOnFeignDeath(), ResetState(), npc_simone::npc_simoneAI::ScheduleEncounterStart(), npc_franklin::npc_franklinAI::ScheduleEncounterStart(), StorePlayerGUID(), and UnitIsUnfair().
threatList
ThreatContainer::StorageType const& NPCStaveQuestAI::threatList = me->GetThreatMgr().GetThreatList()
Referenced by IsFairFight(), StorePlayerGUID(), and ValidThreatlist().