AzerothCore: BattlegroundBE Class Reference
BattlegroundBE Class Reference
#include "BattlegroundBE.h"
Public Member Functions
BattlegroundBE ()
void StartingEventCloseDoors () override
void StartingEventOpenDoors () override
void HandleAreaTrigger (Player *player, uint32 trigger) override
bool SetupBattleground () override
void FillInitialWorldStates (WorldPacket &d) override
bool HandlePlayerUnderMap (Player *player) override
Public Member Functions inherited from Battleground
Battleground ()
virtual ~Battleground ()
void Update (uint32 diff)
virtual bool SetupBattleground ()
virtual void Init ()
virtual void StartingEventCloseDoors ()
virtual void StartingEventOpenDoors ()
virtual void ResetBGSubclass ()
virtual void DestroyGate (Player *, GameObject *)
virtual bool AllNodesConrolledByTeam (TeamId) const
void StartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
std::string GetName () const
BattlegroundTypeId GetBgTypeID (bool GetRandom=false) const
BattlegroundBracketId GetBracketId () const
uint32 GetInstanceID () const
BattlegroundStatus GetStatus () const
uint32 GetClientInstanceID () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetLastResurrectTime () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
bool isTemplate () const
bool isMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
uint8 GetArenaType () const
PvPTeamId GetWinner () const
uint32 GetScriptId () const
uint32 GetBonusHonorFromKill (uint32 kills) const
void SpiritOfCompetitionEvent (PvPTeamId winnerTeamId) const
bool IsRandom ()
void SetName (std::string_view name)
void SetBgTypeID (BattlegroundTypeId TypeID)
void SetRandomTypeID (BattlegroundTypeId TypeID)
void SetBracket (PvPDifficultyEntry const *bracketEntry)
void SetInstanceID (uint32 InstanceID)
void SetStatus (BattlegroundStatus Status)
void SetClientInstanceID (uint32 InstanceID)
void SetStartTime (uint32 Time)
void SetEndTime (uint32 Time)
void SetLastResurrectTime (uint32 Time)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (uint8 type)
void SetArenaorBGType (bool _isArena)
void SetWinner (PvPTeamId winner)
void SetScriptId (uint32 scriptId)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int32 diff)
void SetStartDelayTime (int32 Time)
void SetMaxPlayersPerTeam (uint32 MaxPlayers)
void SetMinPlayersPerTeam (uint32 MinPlayers)
void AddToBGFreeSlotQueue ()
void RemoveFromBGFreeSlotQueue ()
void DecreaseInvitedCount (TeamId teamId)
void IncreaseInvitedCount (TeamId teamId)
uint32 GetInvitedCount (TeamId teamId) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (TeamId teamId) const
uint32 GetMaxFreeSlots () const
void AddSpectator (Player *p)
void RemoveSpectator (Player *p)
bool HaveSpectators ()
const SpectatorList & GetSpectators () const
void AddToBeTeleported (ObjectGuid spectator, ObjectGuid participant)
void RemoveToBeTeleported (ObjectGuid spectator)
void SpectatorsSendPacket (WorldPacket &data)
bool isArena () const
bool isBattleground () const
bool isRated () const
BattlegroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
void ReadyMarkerClicked (Player *p)
BattlegroundScoreMap const * GetPlayerScores () const
std::size_t GetPlayerScoresSize () const
uint32 GetReviveQueueSize () const
void AddPlayerToResurrectQueue (ObjectGuid npc_guid, ObjectGuid player_guid)
void RemovePlayerFromResurrectQueue (Player *player)
void RelocateDeadPlayers (ObjectGuid queueIndex)
Relocate all players in ReviveQueue to the closest graveyard.
void StartBattleground ()
GameObject * GetBGObject (uint32 type)
Creature * GetBGCreature (uint32 type)
void SetMapId (uint32 MapID)
uint32 GetMapId () const
void SetBgMap (BattlegroundMap *map)
BattlegroundMap * GetBgMap () const
BattlegroundMap * FindBgMap () const
void SetTeamStartPosition (TeamId teamId, Position const &pos)
Position const * GetTeamStartPosition (TeamId teamId) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
virtual void FillInitialWorldStates (WorldPacket &)
void SendPacketToTeam (TeamId teamId, WorldPacket const *packet, Player *sender=nullptr, bool self=true)
void SendPacketToAll (WorldPacket const *packet)
void YellToAll (Creature *creature, const char *text, uint32 language)
void SendChatMessage (Creature *source, uint8 textId, WorldObject *target=nullptr)
void SendBroadcastText (uint32 id, ChatMsg msgType, WorldObject const *target=nullptr)
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToAll (uint32 soundId)
void CastSpellOnTeam (uint32 spellId, TeamId teamId)
void RemoveAuraOnTeam (uint32 spellId, TeamId teamId)
void RewardHonorToTeam (uint32 honor, TeamId teamId)
void RewardReputationToTeam (uint32 factionId, uint32 reputation, TeamId teamId)
uint32 GetRealRepFactionForPlayer (uint32 factionId, Player *player)
void UpdateWorldState (uint32 variable, uint32 value)
void EndBattleground (PvPTeamId winnerTeamId)
virtual void EndBattleground (TeamId winnerTeamId)
void BlockMovement (Player *player)
Group * GetBgRaid (TeamId teamId) const
void SetBgRaid (TeamId teamId, Group *bg_raid)
void BuildPvPLogDataPacket (WorldPacket &data)
virtual bool UpdatePlayerScore (Player *player, uint32 type, uint32 value, bool doAddHonor=true)
uint32 GetPlayersCountByTeam (TeamId teamId) const
uint32 GetAlivePlayersCountByTeam (TeamId teamId) const
void UpdatePlayersCountByTeam (TeamId teamId, bool remove)
virtual void CheckWinConditions ()
void SetArenaTeamIdForTeam (TeamId teamId, uint32 ArenaTeamId)
uint32 GetArenaTeamIdForTeam (TeamId teamId) const
void SetArenaMatchmakerRating (TeamId teamId, uint32 MMR)
uint32 GetArenaMatchmakerRating (TeamId teamId) const
virtual void HandleAreaTrigger (Player *, uint32)
virtual void HandleKillPlayer (Player *player, Player *killer)
virtual void HandleKillUnit (Creature *, Player *)
virtual void EventPlayerDroppedFlag (Player *)
virtual void EventPlayerClickedOnFlag (Player *, GameObject *)
virtual void EventPlayerDamagedGO (Player *, GameObject *, uint32)
virtual void EventPlayerUsedGO (Player *, GameObject *)
virtual void DoAction (uint32, ObjectGuid)
virtual void HandlePlayerResurrect (Player *)
virtual GraveyardStruct const * GetClosestGraveyard (Player *player)
virtual void AddPlayer (Player *player)
void AddOrSetPlayerToCorrectBgGroup (Player *player, TeamId teamId)
virtual void RemovePlayerAtLeave (Player *player)
void HandleTriggerBuff (GameObject *gameObject)
void SetHoliday (bool is_holiday)
void SpawnBGObject (uint32 type, uint32 respawntime, uint32 forceRespawnDelay=0)
bool AddObject (uint32 type, uint32 entry, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime=0, GOState goState=GO_STATE_READY)
Creature * AddCreature (uint32 entry, uint32 type, float x, float y, float z, float o, uint32 respawntime=0, MotionTransport *transport=nullptr)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool AddSpiritGuide (uint32 type, float x, float y, float z, float o, TeamId teamId)
int32 GetObjectType (ObjectGuid guid)
void DoorOpen (uint32 type)
void DoorClose (uint32 type)
const char * GetAcoreString (int32 entry)
virtual bool HandlePlayerUnderMap (Player *)
bool IsPlayerInBattleground (ObjectGuid guid) const
bool ToBeDeleted () const
void RewardXPAtKill (Player *killer, Player *victim)
virtual ObjectGuid GetFlagPickerGUID (TeamId=TEAM_NEUTRAL) const
virtual void SetDroppedFlagGUID (ObjectGuid, TeamId=TEAM_NEUTRAL)
uint32 GetTeamScore (TeamId teamId) const
virtual TeamId GetPrematureWinner ()
uint8 GetUniqueBracketId () const
BattlegroundAV * ToBattlegroundAV ()
BattlegroundAV const * ToBattlegroundAV () const
BattlegroundWS * ToBattlegroundWS ()
BattlegroundWS const * ToBattlegroundWS () const
BattlegroundAB * ToBattlegroundAB ()
BattlegroundAB const * ToBattlegroundAB () const
BattlegroundNA * ToBattlegroundNA ()
BattlegroundNA const * ToBattlegroundNA () const
BattlegroundBE * ToBattlegroundBE ()
BattlegroundBE const * ToBattlegroundBE () const
BattlegroundEY * ToBattlegroundEY ()
BattlegroundEY const * ToBattlegroundEY () const
BattlegroundRL * ToBattlegroundRL ()
BattlegroundRL const * ToBattlegroundRL () const
BattlegroundSA * ToBattlegroundSA ()
BattlegroundSA const * ToBattlegroundSA () const
BattlegroundDS * ToBattlegroundDS ()
BattlegroundDS const * ToBattlegroundDS () const
BattlegroundRV * ToBattlegroundRV ()
BattlegroundRV const * ToBattlegroundRV () const
BattlegroundIC * ToBattlegroundIC ()
BattlegroundIC const * ToBattlegroundIC () const
Additional Inherited Members
Public Types inherited from Battleground
typedef std::set< Player * > SpectatorList
typedef std::map< ObjectGuid, ObjectGuid > ToBeTeleportedMap
typedef std::map< ObjectGuid, Player * > BattlegroundPlayerMap
typedef std::unordered_map< ObjectGuid::LowType, BattlegroundScore * > BattlegroundScoreMap
typedef std::unordered_map< ObjectGuid, ArenaLogEntryData > ArenaLogEntryDataMap
typedef GuidVector BGObjects
typedef GuidVector BGCreatures
Static Public Member Functions inherited from Battleground
static TeamId GetOtherTeamId (TeamId teamId)
Public Attributes inherited from Battleground
GuidSet readyMarkerClickedSet
ArenaLogEntryDataMap ArenaLogEntries
BGObjects BgObjects
BGCreatures BgCreatures
Protected Member Functions inherited from Arena
Arena ()
void AddPlayer (Player *player) override
void RemovePlayer (Player *) override
void FillInitialWorldStates (WorldPacket &data) override
void UpdateArenaWorldState ()
void HandleKillPlayer (Player *player, Player *killer) override
Protected Member Functions inherited from Battleground
void EndNow ()
void PlayerAddedToBGCheckIfBGIsRunning (Player *player)
void _ProcessResurrect (uint32 diff)
void _ProcessProgress (uint32 diff)
void _ProcessLeave (uint32 diff)
void _ProcessJoin (uint32 diff)
void _CheckSafePositions (uint32 diff)
virtual void RemovePlayer (Player *)
Protected Attributes inherited from Battleground
BattlegroundScoreMap PlayerScores
BattlegroundPlayerMap m_Players
std::map< ObjectGuid, GuidVector > m_ReviveQueue
uint8 m_Events
BattlegroundStartTimeIntervals StartDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 StartMessageIds [BG_STARTING_EVENT_COUNT]
bool m_BuffChange
bool m_IsRandom
BGHonorMode m_HonorMode
int32 m_TeamScores [PVP_TEAMS_COUNT]
ArenaTeamScore _arenaTeamScores [PVP_TEAMS_COUNT]
uint32 m_UpdateTimer
EventProcessor _reviveEvents
Detailed Description
Constructor & Destructor Documentation
BattlegroundBE()
BattlegroundBE::BattlegroundBE ()
{
    BgObjects.resize(BG_BE_OBJECT_MAX);
}
References BG_BE_OBJECT_MAX, and Battleground::BgObjects.
Member Function Documentation
FillInitialWorldStates()
void BattlegroundBE::FillInitialWorldStates (WorldPacket & d) override virtual
Reimplemented from Arena.
{
    data << uint32(0x9f3) << uint32(1); // 9
    Arena::FillInitialWorldStates(data);
}
References Arena::FillInitialWorldStates().
HandleAreaTrigger()
void BattlegroundBE::HandleAreaTrigger (Player * player, uint32 trigger) override virtual
Reimplemented from Battleground.
{
    // this is wrong way to implement these things. On official it done by gameobject spell cast.
    if (GetStatus() != STATUS_IN_PROGRESS)
        return;
    switch (trigger)
    {
        case 4538:                                          // buff trigger?
            //buff_guid = BgObjects[BG_BE_OBJECT_BUFF_1];
            break;
        case 4539:                                          // buff trigger?
            //buff_guid = BgObjects[BG_BE_OBJECT_BUFF_2];
            break;
        // OUTSIDE OF ARENA, TELEPORT!
        case 4919:
            player->NearTeleportTo(6220.90f, 318.94f, 5.1f, 5.3f);
            break;
        case 4921:
            player->NearTeleportTo(6250.27f, 208.50f, 4.77f, 1.9f);
            break;
        case 4922:
            player->NearTeleportTo(6214.4f, 227.12f, 4.28f, 0.8f);
            break;
        case 4923:
            player->NearTeleportTo(6180.98f, 265.28f, 4.27f, 6.06f);
            break;
        case 4924:
            player->NearTeleportTo(6269.0f, 295.06f, 4.46f, 3.98f);
            break;
        case 4944: // under arena -20
        case 5039: // under arena -40
        case 5040: // under arena -60
            player->NearTeleportTo(6238.930176f, 262.963470f, 0.889519f, player->GetOrientation());
            break;
    }
}
References Position::GetOrientation(), Battleground::GetStatus(), Unit::NearTeleportTo(), and STATUS_IN_PROGRESS.
HandlePlayerUnderMap()
bool BattlegroundBE::HandlePlayerUnderMap (Player * player) override virtual
Reimplemented from Battleground.
{
    player->NearTeleportTo(6238.930176f, 262.963470f, 0.889519f, player->GetOrientation());
    return true;
}
References Position::GetOrientation(), and Unit::NearTeleportTo().
SetupBattleground()
bool BattlegroundBE::SetupBattleground () override virtual
Reimplemented from Battleground.
{
    // gates
    if (!AddObject(BG_BE_OBJECT_DOOR_1, BG_BE_OBJECT_TYPE_DOOR_1, 6287.277f, 282.1877f, 3.810925f, -2.260201f, 0, 0, 0.9044551f, -0.4265689f, RESPAWN_IMMEDIATELY)
            || !AddObject(BG_BE_OBJECT_DOOR_2, BG_BE_OBJECT_TYPE_DOOR_2, 6189.546f, 241.7099f, 3.101481f, 0.8813917f, 0, 0, 0.4265689f, 0.9044551f, RESPAWN_IMMEDIATELY)
            || !AddObject(BG_BE_OBJECT_DOOR_3, BG_BE_OBJECT_TYPE_DOOR_3, 6299.116f, 296.5494f, 3.308032f, 0.8813917f, 0, 0, 0.4265689f, 0.9044551f, RESPAWN_IMMEDIATELY)
            || !AddObject(BG_BE_OBJECT_DOOR_4, BG_BE_OBJECT_TYPE_DOOR_4, 6177.708f, 227.3481f, 3.604374f, -2.260201f, 0, 0, 0.9044551f, -0.4265689f, RESPAWN_IMMEDIATELY)
            // buffs
            || !AddObject(BG_BE_OBJECT_BUFF_1, BG_BE_OBJECT_TYPE_BUFF_1, 6249.042f, 275.3239f, 11.22033f, -1.448624f, 0, 0, 0.6626201f, -0.7489557f, 120)
            || !AddObject(BG_BE_OBJECT_BUFF_2, BG_BE_OBJECT_TYPE_BUFF_2, 6228.26f, 249.566f, 11.21812f, -0.06981307f, 0, 0, 0.03489945f, -0.9993908f, 120)
            // Arena Ready Marker
            || !AddObject(BG_BE_OBJECT_READY_MARKER_1, ARENA_READY_MARKER_ENTRY, 6189.47f, 235.54f, 5.52f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 300)
            || !AddObject(BG_BE_OBJECT_READY_MARKER_2, ARENA_READY_MARKER_ENTRY, 6287.19f, 288.25f, 5.33f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 300))
    {
        LOG_ERROR("sql.sql", "BatteGroundBE: Failed to spawn some object!");
        return false;
    }
    return true;
}
References Battleground::AddObject(), ARENA_READY_MARKER_ENTRY, BG_BE_OBJECT_BUFF_1, BG_BE_OBJECT_BUFF_2, BG_BE_OBJECT_DOOR_1, BG_BE_OBJECT_DOOR_2, BG_BE_OBJECT_DOOR_3, BG_BE_OBJECT_DOOR_4, BG_BE_OBJECT_READY_MARKER_1, BG_BE_OBJECT_READY_MARKER_2, BG_BE_OBJECT_TYPE_BUFF_1, BG_BE_OBJECT_TYPE_BUFF_2, BG_BE_OBJECT_TYPE_DOOR_1, BG_BE_OBJECT_TYPE_DOOR_2, BG_BE_OBJECT_TYPE_DOOR_3, BG_BE_OBJECT_TYPE_DOOR_4, LOG_ERROR, and RESPAWN_IMMEDIATELY.
StartingEventCloseDoors()
void BattlegroundBE::StartingEventCloseDoors () override virtual
Reimplemented from Battleground.
{
    for (uint32 i = BG_BE_OBJECT_DOOR_1; i <= BG_BE_OBJECT_DOOR_4; ++i)
        SpawnBGObject(i, RESPAWN_IMMEDIATELY);
    for (uint32 i = BG_BE_OBJECT_BUFF_1; i <= BG_BE_OBJECT_BUFF_2; ++i)
        SpawnBGObject(i, RESPAWN_ONE_DAY);
}
References BG_BE_OBJECT_BUFF_1, BG_BE_OBJECT_BUFF_2, BG_BE_OBJECT_DOOR_1, BG_BE_OBJECT_DOOR_4, RESPAWN_IMMEDIATELY, RESPAWN_ONE_DAY, and Battleground::SpawnBGObject().
StartingEventOpenDoors()
void BattlegroundBE::StartingEventOpenDoors () override virtual
Reimplemented from Battleground.
{
    for (uint32 i = BG_BE_OBJECT_DOOR_1; i <= BG_BE_OBJECT_DOOR_2; ++i)
        DoorOpen(i);
    for (uint32 i = BG_BE_OBJECT_BUFF_1; i <= BG_BE_OBJECT_BUFF_2; ++i)
        SpawnBGObject(i, 90);
}
References BG_BE_OBJECT_BUFF_1, BG_BE_OBJECT_BUFF_2, BG_BE_OBJECT_DOOR_1, BG_BE_OBJECT_DOOR_2, Battleground::DoorOpen(), and Battleground::SpawnBGObject().