AzerothCore: achievement_save_the_day Class Reference
achievement_save_the_day Class Reference
Public Member Functions
achievement_save_the_day ()
bool OnCheck (Player *source, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
virtual bool OnCheck (Player *, Unit *, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_save_the_day()
achievement_save_the_day::achievement_save_the_day () inline
: AchievementCriteriaScript("achievement_save_the_day") { }
Member Function Documentation
OnCheck()
bool achievement_save_the_day::OnCheck (Player * source, Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
    {
        if (!target)
            return false;
        if (Player const* player = target->ToPlayer())
        {
            Battleground* bg = source->GetBattleground();
            return bg && bg->GetBgTypeID(true) == BATTLEGROUND_WS && bg->ToBattlegroundWS()->GetFlagState(player->GetTeamId()) == BG_WS_FLAG_STATE_ON_BASE;
        }
        return false;
    }
References BATTLEGROUND_WS, BG_WS_FLAG_STATE_ON_BASE, Player::GetBattleground(), Battleground::GetBgTypeID(), BattlegroundWS::GetFlagState(), Battleground::ToBattlegroundWS(), and Object::ToPlayer().