AzerothCore: TypeContainerVisitor< VISITOR, TYPE_CONTAINER > Class Template Reference
TypeContainerVisitor< VISITOR, TYPE_CONTAINER > Class Template Reference
#include "TypeContainerVisitor.h"
Public Member Functions
TypeContainerVisitor (VISITOR &v)
void Visit (TYPE_CONTAINER &c)
void Visit (const TYPE_CONTAINER &c) const
Private Attributes
VISITOR & i_visitor
Detailed Description
template<class VISITOR, class TYPE_CONTAINER>
class TypeContainerVisitor< VISITOR, TYPE_CONTAINER >
Constructor & Destructor Documentation
TypeContainerVisitor()
template<class VISITOR , class TYPE_CONTAINER > TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::TypeContainerVisitor (VISITOR & v) inline
: i_visitor(v) { }
Member Function Documentation
Visit() [1/2]
template<class VISITOR , class TYPE_CONTAINER > void TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::Visit (const TYPE_CONTAINER & c) const inline
    {
        VisitorHelper(i_visitor, c);
    }
References TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::i_visitor, and VisitorHelper().
Visit() [2/2]
template<class VISITOR , class TYPE_CONTAINER > void TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::Visit (TYPE_CONTAINER & c) inline
    {
        VisitorHelper(i_visitor, c);
    }
References TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::i_visitor, and VisitorHelper().
Referenced by debug_commandscript::HandleDebugObjectCountMap(), and GameEventMgr::RunSmartAIScripts().
Member Data Documentation
i_visitor
template<class VISITOR , class TYPE_CONTAINER > VISITOR& TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::i_visitor private
Referenced by TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::Visit().