AzerothCore: QueryCallback::QueryCallbackData Struct Reference
QueryCallback::QueryCallbackData Struct Reference
Public Member Functions
QueryCallbackData (std::function< void(QueryCallback &, QueryResult)> &&callback)
QueryCallbackData (std::function< void(QueryCallback &, PreparedQueryResult)> &&callback)
QueryCallbackData (QueryCallbackData &&right) noexcept
QueryCallbackData & operator= (QueryCallbackData &&right) noexcept
~QueryCallbackData ()
Private Member Functions
QueryCallbackData (QueryCallbackData const &)=delete
QueryCallbackData & operator= (QueryCallbackData const &)=delete
Private Attributes
union {
std::function< void(QueryCallback &, QueryResult)> _string
std::function< void(QueryCallback &, PreparedQueryResult)> _prepared
};
bool _isPrepared
Friends
class QueryCallback
template<typename T >
void ConstructActiveMember (T *obj)
template<typename T >
void DestroyActiveMember (T *obj)
template<typename T >
void MoveFrom (T *to, T &&from)
Detailed Description
Constructor & Destructor Documentation
QueryCallbackData() [1/4]
QueryCallback::QueryCallbackData::QueryCallbackData (std::function< void(QueryCallback &, QueryResult)> && callback) inline
: _string(std::move(callback)), _isPrepared(false) { }
QueryCallbackData() [2/4]
QueryCallback::QueryCallbackData::QueryCallbackData (std::function< void(QueryCallback &, PreparedQueryResult)> && callback) inline
: _prepared(std::move(callback)), _isPrepared(true) { }
QueryCallbackData() [3/4]
QueryCallback::QueryCallbackData::QueryCallbackData (QueryCallbackData && right) inline noexcept
    {
        _isPrepared = right._isPrepared;
        ConstructActiveMember(this);
        MoveFrom(this, std::move(right));
    }
References _isPrepared, ConstructActiveMember, and MoveFrom.
~QueryCallbackData()
QueryCallback::QueryCallbackData::~QueryCallbackData () inline
{ DestroyActiveMember(this); }
References DestroyActiveMember.
QueryCallbackData() [4/4]
QueryCallback::QueryCallbackData::QueryCallbackData (QueryCallbackData const &) private delete
Member Function Documentation
operator=() [1/2]
QueryCallbackData & QueryCallback::QueryCallbackData::operator= (QueryCallbackData && right) inline noexcept
    {
        if (this != &right)
        {
            if (_isPrepared != right._isPrepared)
            {
                DestroyActiveMember(this);
                _isPrepared = right._isPrepared;
                ConstructActiveMember(this);
            }
            MoveFrom(this, std::move(right));
        }
        return *this;
    }
References _isPrepared, ConstructActiveMember, DestroyActiveMember, and MoveFrom.
operator=() [2/2]
QueryCallbackData & QueryCallback::QueryCallbackData::operator= (QueryCallbackData const &) private delete
Friends And Related Function Documentation
ConstructActiveMember
template<typename T > void ConstructActiveMember (T * obj) friend
{
    if (!obj->_isPrepared)
        Construct(obj->_string);
    else
        Construct(obj->_prepared);
}
Referenced by operator=(), and QueryCallbackData().
DestroyActiveMember
template<typename T > void DestroyActiveMember (T * obj) friend
{
    if (!obj->_isPrepared)
        Destroy(obj->_string);
    else
        Destroy(obj->_prepared);
}
Referenced by operator=(), and ~QueryCallbackData().
MoveFrom
template<typename T > void MoveFrom (T * to, T && from) friend
{
    ASSERT(to->_isPrepared == from._isPrepared);
    if (!to->_isPrepared)
        to->_string = std::move(from._string);
    else
        to->_prepared = std::move(from._prepared);
}
Referenced by operator=(), and QueryCallbackData().
QueryCallback
friend class QueryCallback friend
Member Data Documentation
union { ... } QueryCallback::QueryCallbackData::@3
_isPrepared
bool QueryCallback::QueryCallbackData::_isPrepared private
Referenced by operator=(), and QueryCallbackData().
_prepared
std::function<void(QueryCallback&, PreparedQueryResult)> QueryCallback::QueryCallbackData::_prepared
Referenced by QueryCallback::InvokeIfReady().
_string
std::function<void(QueryCallback&, QueryResult)> QueryCallback::QueryCallbackData::_string
Referenced by QueryCallback::InvokeIfReady().