AzerothCore: SpellScriptLoader Class Reference
SpellScriptLoader Class Reference
#include "SpellScriptLoader.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual SpellScript * GetSpellScript () const
virtual AuraScript * GetAuraScript () const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Protected Member Functions
SpellScriptLoader (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
SpellScriptLoader()
SpellScriptLoader::SpellScriptLoader (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<SpellScriptLoader>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
GetAuraScript()
virtual AuraScript * SpellScriptLoader::GetAuraScript () const inline virtual
Reimplemented in GenericSpellAndAuraScriptLoader< Ts >, spell_chapter5_light_of_dawn_aura, spell_scholomance_fixate, spell_scholomance_boon_of_life, spell_shadowfang_keep_haunting_spirits, spell_shadowfang_keep_forsaken_skills, spell_temple_of_atal_hakkar_hex_of_jammal_an, spell_uldaman_stoned, spell_hexlord_unstable_affliction, spell_threatening_gaze, spell_pursuing_spikes, spell_gen_leeching_swarm, spell_faction_champion_warl_unstable_affliction, spell_toc25_mistress_kiss, spell_valkyr_essence, spell_valkyr_touch, spell_valkyr_ball_periodic_dummy, spell_hos_dark_matter, spell_voa_overcharge, spell_koralon_meteor_fists, and spell_flame_warder_meteor_fists.
{ return nullptr; }
Referenced by ScriptMgr::CreateAuraScripts().
GetSpellScript()
virtual SpellScript * SpellScriptLoader::GetSpellScript () const inline virtual
Reimplemented in GenericSpellAndAuraScriptLoader< Ts >, spell_gnomeregan_radiation_bolt, spell_q12641_death_comes_from_on_high_summon_ghouls, spell_item_gift_of_the_harvester, spell_q12698_the_gift_that_keeps_on_giving, spell_chapter5_rebuke, spell_temple_of_atal_hakkar_awaken_the_soulflayer, spell_uldaman_sub_boss_agro_keepers, spell_uldaman_boss_agro_archaedas, spell_gen_leeching_swarm_dmg, spell_mistress_kiss_area, spell_loken_pulsing_shockwave, spell_krystallus_shatter, spell_krystallus_shatter_effect, spell_archavon_rock_shards, spell_voa_lightning_nova, spell_voa_flaming_cinder, spell_q55_sacred_cleansing, and spell_q11515_fel_siphon_dummy.
{ return nullptr; }
Referenced by ScriptMgr::CreateSpellScripts().
IsDatabaseBound()
bool SpellScriptLoader::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return true; }