document.write(`
  <a id="WorldObject:GetAngle" class="fn" href="../WorldObject/GetAngle.html">GetAngle</a>
  <a id="WorldObject:GetAreaId" class="fn" href="../WorldObject/GetAreaId.html">GetAreaId</a>
  <a id="WorldObject:GetCreaturesInRange" class="fn" href="../WorldObject/GetCreaturesInRange.html">GetCreaturesInRange</a>
  <a id="WorldObject:GetDistance" class="fn" href="../WorldObject/GetDistance.html">GetDistance</a>
  <a id="WorldObject:GetDistance2d" class="fn" href="../WorldObject/GetDistance2d.html">GetDistance2d</a>
  <a id="WorldObject:GetExactDistance" class="fn" href="../WorldObject/GetExactDistance.html">GetExactDistance</a>
  <a id="WorldObject:GetExactDistance2d" class="fn" href="../WorldObject/GetExactDistance2d.html">GetExactDistance2d</a>
  <a id="WorldObject:GetGameObjectsInRange" class="fn" href="../WorldObject/GetGameObjectsInRange.html">GetGameObjectsInRange</a>
  <a id="WorldObject:GetInstanceId" class="fn" href="../WorldObject/GetInstanceId.html">GetInstanceId</a>
  <a id="WorldObject:GetLocation" class="fn" href="../WorldObject/GetLocation.html">GetLocation</a>
  <a id="WorldObject:GetMap" class="fn" href="../WorldObject/GetMap.html">GetMap</a>
  <a id="WorldObject:GetMapId" class="fn" href="../WorldObject/GetMapId.html">GetMapId</a>
  <a id="WorldObject:GetName" class="fn" href="../WorldObject/GetName.html">GetName</a>
  <a id="WorldObject:GetNearObject" class="fn" href="../WorldObject/GetNearObject.html">GetNearObject</a>
  <a id="WorldObject:GetNearObjects" class="fn" href="../WorldObject/GetNearObjects.html">GetNearObjects</a>
  <a id="WorldObject:GetNearestCreature" class="fn" href="../WorldObject/GetNearestCreature.html">GetNearestCreature</a>
  <a id="WorldObject:GetNearestGameObject" class="fn" href="../WorldObject/GetNearestGameObject.html">GetNearestGameObject</a>
  <a id="WorldObject:GetNearestPlayer" class="fn" href="../WorldObject/GetNearestPlayer.html">GetNearestPlayer</a>
  <a id="WorldObject:GetO" class="fn" href="../WorldObject/GetO.html">GetO</a>
  <a id="WorldObject:GetPhaseMask" class="fn" href="../WorldObject/GetPhaseMask.html">GetPhaseMask</a>
  <a id="WorldObject:GetPlayersInRange" class="fn" href="../WorldObject/GetPlayersInRange.html">GetPlayersInRange</a>
  <a id="WorldObject:GetRelativePoint" class="fn" href="../WorldObject/GetRelativePoint.html">GetRelativePoint</a>
  <a id="WorldObject:GetX" class="fn" href="../WorldObject/GetX.html">GetX</a>
  <a id="WorldObject:GetY" class="fn" href="../WorldObject/GetY.html">GetY</a>
  <a id="WorldObject:GetZ" class="fn" href="../WorldObject/GetZ.html">GetZ</a>
  <a id="WorldObject:GetZoneId" class="fn" href="../WorldObject/GetZoneId.html">GetZoneId</a>
  <a id="WorldObject:IsInBack" class="fn" href="../WorldObject/IsInBack.html">IsInBack</a>
  <a id="WorldObject:IsInFront" class="fn" href="../WorldObject/IsInFront.html">IsInFront</a>
  <a id="WorldObject:IsInMap" class="fn" href="../WorldObject/IsInMap.html">IsInMap</a>
  <a id="WorldObject:IsInRange" class="fn" href="../WorldObject/IsInRange.html">IsInRange</a>
  <a id="WorldObject:IsInRange2d" class="fn" href="../WorldObject/IsInRange2d.html">IsInRange2d</a>
  <a id="WorldObject:IsInRange3d" class="fn" href="../WorldObject/IsInRange3d.html">IsInRange3d</a>
  <a id="WorldObject:IsWithinDist" class="fn" href="../WorldObject/IsWithinDist.html">IsWithinDist</a>
  <a id="WorldObject:IsWithinDist2d" class="fn" href="../WorldObject/IsWithinDist2d.html">IsWithinDist2d</a>
  <a id="WorldObject:IsWithinDist3d" class="fn" href="../WorldObject/IsWithinDist3d.html">IsWithinDist3d</a>
  <a id="WorldObject:IsWithinDistInMap" class="fn" href="../WorldObject/IsWithinDistInMap.html">IsWithinDistInMap</a>
  <a id="WorldObject:IsWithinLoS" class="fn" href="../WorldObject/IsWithinLoS.html">IsWithinLoS</a>
  <a id="WorldObject:PlayDirectSound" class="fn" href="../WorldObject/PlayDirectSound.html">PlayDirectSound</a>
  <a id="WorldObject:PlayDistanceSound" class="fn" href="../WorldObject/PlayDistanceSound.html">PlayDistanceSound</a>
  <a id="WorldObject:PlayMusic" class="fn" href="../WorldObject/PlayMusic.html">PlayMusic</a>
  <a id="WorldObject:RegisterEvent" class="fn" href="../WorldObject/RegisterEvent.html">RegisterEvent</a>
  <a id="WorldObject:RemoveEventById" class="fn" href="../WorldObject/RemoveEventById.html">RemoveEventById</a>
  <a id="WorldObject:RemoveEvents" class="fn" href="../WorldObject/RemoveEvents.html">RemoveEvents</a>
  <a id="WorldObject:SendPacket" class="fn" href="../WorldObject/SendPacket.html">SendPacket</a>
  <a id="WorldObject:SetPhaseMask" class="fn" href="../WorldObject/SetPhaseMask.html">SetPhaseMask</a>
  <a id="WorldObject:SpawnCreature" class="fn" href="../WorldObject/SpawnCreature.html">SpawnCreature</a>
  <a id="WorldObject:SummonGameObject" class="fn" href="../WorldObject/SummonGameObject.html">SummonGameObject</a>
`);