AzerothCore: AreaTrigger_at_legion_teleporter Class Reference
AreaTrigger_at_legion_teleporter Class Reference
Public Member Functions
AreaTrigger_at_legion_teleporter ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
AreaTrigger_at_legion_teleporter()
AreaTrigger_at_legion_teleporter::AreaTrigger_at_legion_teleporter () inline
        : AreaTriggerScript("at_legion_teleporter")
    {
    }
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_legion_teleporter::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (player->IsAlive() && !player->IsInCombat())
        {
            if (player->GetTeamId() == TEAM_ALLIANCE && player->GetQuestRewardStatus(QUEST_GAINING_ACCESS_A))
            {
                player->CastSpell(player, SPELL_TELE_A_TO, false);
                return true;
            }
            if (player->GetTeamId() == TEAM_HORDE && player->GetQuestRewardStatus(QUEST_GAINING_ACCESS_H))
            {
                player->CastSpell(player, SPELL_TELE_H_TO, false);
                return true;
            }
            return false;
        }
        return false;
    }
References Unit::CastSpell(), Player::GetQuestRewardStatus(), Player::GetTeamId(), Unit::IsAlive(), Unit::IsInCombat(), QUEST_GAINING_ACCESS_A, QUEST_GAINING_ACCESS_H, SPELL_TELE_A_TO, SPELL_TELE_H_TO, TEAM_ALLIANCE, and TEAM_HORDE.