AzerothCore: go_bear_trap::go_bear_trapAI Struct Reference
go_bear_trap::go_bear_trapAI Struct Reference
Public Member Functions
go_bear_trapAI (GameObject *gameObject)
void Initialize ()
void UpdateAI (uint32 const diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Private Attributes
EventMap _events
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_bear_trapAI()
go_bear_trap::go_bear_trapAI::go_bear_trapAI (GameObject * gameObject) inline
                                               : GameObjectAI(gameObject)
        {
            Initialize();
        }
References Initialize().
Member Function Documentation
Initialize()
void go_bear_trap::go_bear_trapAI::Initialize () inline
        {
            _events.ScheduleEvent(EVENT_CHECK, 1000);
        }
References _events, EVENT_CHECK, and EventMap::ScheduleEvent().
Referenced by go_bear_trapAI().
UpdateAI()
void go_bear_trap::go_bear_trapAI::UpdateAI (uint32 const diff) inline override virtual
Reimplemented from GameObjectAI.
        {
            _events.Update(diff);
            while (uint32 eventId = _events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_CHECK:
                    {
                        if (Creature* bear = me->FindNearestCreature(NPC_RABID_THISTLE_BEAR, 1.0f))
{
                            bear->CastSpell(bear, SPELL_BEAR_CAPTURED_IN_TRAP);
                            me->RemoveFromWorld();
                        }
                        else
{
                            _events.ScheduleEvent(EVENT_CHECK, 1000);
                        }
                        break;
                    }
                    default:
                        break;
                }
            }
        }
References _events, EVENT_CHECK, EventMap::ExecuteEvent(), WorldObject::FindNearestCreature(), GameObjectAI::me, NPC_RABID_THISTLE_BEAR, GameObject::RemoveFromWorld(), EventMap::ScheduleEvent(), SPELL_BEAR_CAPTURED_IN_TRAP, and EventMap::Update().
Member Data Documentation
_events
EventMap go_bear_trap::go_bear_trapAI::_events private
Referenced by Initialize(), and UpdateAI().