AzerothCore: npc_rimefang::npc_rimefangAI Struct Reference
npc_rimefang::npc_rimefangAI Struct Reference
Public Member Functions
npc_rimefangAI (Creature *creature)
void InitializeAI () override
void Reset () override
void JustReachedHome () override
void JustRespawned () override
void JustDied (Unit *) override
void DoAction (int32 action) override
void MovementInform (uint32 type, uint32 point) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
InstanceScript * _instance
uint8 _icyBlastCounter
bool _summoned
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_rimefangAI()
npc_rimefang::npc_rimefangAI::npc_rimefangAI (Creature * creature) inline
                                           : ScriptedAI(creature), _instance(creature->GetInstanceScript()), _summoned(false)
        {
        }
Member Function Documentation
DoAction()
void npc_rimefang::npc_rimefangAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == ACTION_START_FROSTWYRM)
            {
                if (_summoned)
                    return;
                _summoned = true;
                if (me->isDead())
                    return;
                me->setActive(true);
                me->SetImmuneToPC(true);
                float moveTime = me->GetExactDist(&RimefangFlyPos) / (me->GetSpeed(MOVE_RUN) * 0.001f);
                me->m_Events.AddEvent(new FrostwyrmLandEvent(*me, RimefangLandPos), me->m_Events.CalculateTime(uint64(moveTime) + 250));
                me->SetDefaultMovementType(IDLE_MOTION_TYPE);
                me->GetMotionMaster()->MoveIdle();
                me->StopMoving();
                me->GetMotionMaster()->MovePoint(POINT_FROSTWYRM_FLY_IN, RimefangFlyPos);
            }
        }
References _summoned, ACTION_START_FROSTWYRM, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Position::GetExactDist(), Unit::GetMotionMaster(), Unit::GetSpeed(), IDLE_MOTION_TYPE, Unit::isDead(), Unit::m_Events, ScriptedAI::me, MOVE_RUN, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), POINT_FROSTWYRM_FLY_IN, RimefangFlyPos, RimefangLandPos, WorldObject::setActive(), Creature::SetDefaultMovementType(), Unit::SetImmuneToPC(), and Unit::StopMoving().
InitializeAI()
void npc_rimefang::npc_rimefangAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
        {
            if (!me->isDead())
            {
                _instance->SetData(DATA_SINDRAGOSA_FROSTWYRMS, me->GetSpawnId());  // this cannot be in Reset because reset also happens on evade
                Reset();
            }
        }
References _instance, DATA_SINDRAGOSA_FROSTWYRMS, Creature::GetSpawnId(), Unit::isDead(), ScriptedAI::me, Reset(), and ZoneScript::SetData().
JustDied()
void npc_rimefang::npc_rimefangAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            _events.Reset();
        }
References _events, and EventMap::Reset().
JustEngagedWith()
void npc_rimefang::npc_rimefangAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            me->CastSpell(me, SPELL_FROST_AURA_RIMEFANG, true);
        }
References Unit::CastSpell(), ScriptedAI::me, and SPELL_FROST_AURA_RIMEFANG.
JustReachedHome()
void npc_rimefang::npc_rimefangAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
        {
            ScriptedAI::JustReachedHome();
            if (_summoned)
            {
                me->SetDisableGravity(false);
            }
        }
References _summoned, CreatureAI::JustReachedHome(), ScriptedAI::me, and Creature::SetDisableGravity().
JustRespawned()
void npc_rimefang::npc_rimefangAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
        {
            ScriptedAI::JustRespawned();
            _instance->SetData(DATA_SINDRAGOSA_FROSTWYRMS, me->GetSpawnId());  // this cannot be in Reset because reset also happens on evade
        }
References _instance, DATA_SINDRAGOSA_FROSTWYRMS, Creature::GetSpawnId(), CreatureAI::JustRespawned(), ScriptedAI::me, and ZoneScript::SetData().
MovementInform()
void npc_rimefang::npc_rimefangAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type != EFFECT_MOTION_TYPE)
                return;
            if (point == POINT_FROSTWYRM_LAND)
            {
                me->setActive(false);
                me->SetDisableGravity(false);
                me->SetHomePosition(RimefangLandPos);
                me->SetFacingTo(RimefangLandPos.GetOrientation());
                me->SetImmuneToPC(false);
            }
            else if (point == POINT_LAND_GROUND)
            {
                me->SetDisableGravity(false);
                me->SetReactState(REACT_DEFENSIVE);
                if (Unit* victim = me->SelectVictim())
                    AttackStart(victim);
            }
        }
References ScriptedAI::AttackStart(), EFFECT_MOTION_TYPE, Position::GetOrientation(), ScriptedAI::me, POINT_FROSTWYRM_LAND, POINT_LAND_GROUND, REACT_DEFENSIVE, RimefangLandPos, Creature::SelectVictim(), WorldObject::setActive(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Creature::SetHomePosition(), Unit::SetImmuneToPC(), and Creature::SetReactState().
Reset()
void npc_rimefang::npc_rimefangAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _events.Reset();
            _events.ScheduleEvent(EVENT_FROST_BREATH_RIMEFANG, 12s, 15s);
            _events.ScheduleEvent(EVENT_ICY_BLAST, 30s, 35s);
            me->SetReactState(REACT_DEFENSIVE);
            _icyBlastCounter = 0;
            if (!_summoned)
            {
                me->SetDisableGravity(true);
            }
        }
References _events, _icyBlastCounter, _summoned, EVENT_FROST_BREATH_RIMEFANG, EVENT_ICY_BLAST, ScriptedAI::me, REACT_DEFENSIVE, EventMap::Reset(), EventMap::ScheduleEvent(), Creature::SetDisableGravity(), and Creature::SetReactState().
Referenced by InitializeAI().
UpdateAI()
void npc_rimefang::npc_rimefangAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            _events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (_events.ExecuteEvent())
            {
                case EVENT_FROST_BREATH_RIMEFANG:
                    if (!me->IsFlying())
                    {
                        me->CastSpell(me->GetVictim(), SPELL_FROST_BREATH, false);
                        _events.ScheduleEvent(EVENT_FROST_BREATH_RIMEFANG, 20s, 25s);
                    }
                    else
                        _events.ScheduleEvent(EVENT_FROST_BREATH_RIMEFANG, 5s);
                    break;
                case EVENT_ICY_BLAST:
                    {
                        _icyBlastCounter = RAID_MODE<uint8>(5, 7, 6, 8);
                        me->SetReactState(REACT_PASSIVE);
                        me->GetMotionMaster()->MoveIdle();
                        me->StopMoving();
                        me->SendMeleeAttackStop(me->GetVictim());
                        me->AttackStop();
                        me->SetDisableGravity(true);
                        float floorZ = me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                        float destZ;
                        if (floorZ > 190.0f) destZ = floorZ + 25.0f;
                        else destZ = me->GetPositionZ() + 25.0f;
                        me->GetMotionMaster()->MoveTakeoff(0, me->GetPositionX(), me->GetPositionY(), destZ, me->GetSpeed(MOVE_RUN));
                        float moveTime = std::fabs(destZ - me->GetPositionZ()) / (me->GetSpeed(MOVE_RUN) * 0.001f);
                        _events.ScheduleEvent(EVENT_ICY_BLAST, uint32(moveTime) + urand(60000, 70000));
                        _events.ScheduleEvent(EVENT_ICY_BLAST_CAST, uint32(moveTime) + 250);
                        break;
                    }
                case EVENT_ICY_BLAST_CAST:
                    if (--_icyBlastCounter)
                    {
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true))
{
                            me->SetFacingToObject(target);
                            me->CastSpell(target, SPELL_ICY_BLAST, false);
                        }
                        _events.ScheduleEvent(EVENT_ICY_BLAST_CAST, 3s);
                    }
                    else
                    {
                        float floorZ = me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                        float destZ;
                        if (floorZ > 190.0f) destZ = floorZ;
                        else destZ = me->GetPositionZ() - 25.0f;
                        me->SendMeleeAttackStop(me->GetVictim());
                        me->GetMotionMaster()->MoveLand(POINT_LAND_GROUND, me->GetPositionX(), me->GetPositionY(), destZ, me->GetSpeed(MOVE_RUN));
                    }
                    break;
                default:
                    break;
            }
            DoMeleeAttackIfReady();
        }
References _events, _icyBlastCounter, Unit::AttackStop(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_FROST_BREATH_RIMEFANG, EVENT_ICY_BLAST, EVENT_ICY_BLAST_CAST, EventMap::ExecuteEvent(), WorldObject::GetMapHeight(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetSpeed(), Unit::GetVictim(), Unit::HasUnitState(), Unit::IsFlying(), ScriptedAI::me, MOVE_RUN, MotionMaster::MoveIdle(), MotionMaster::MoveLand(), MotionMaster::MoveTakeoff(), POINT_LAND_GROUND, REACT_PASSIVE, EventMap::ScheduleEvent(), UnitAI::SelectTarget(), Unit::SendMeleeAttackStop(), Creature::SetDisableGravity(), Unit::SetFacingToObject(), Creature::SetReactState(), SPELL_FROST_BREATH, SPELL_ICY_BLAST, Unit::StopMoving(), UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_events
EventMap npc_rimefang::npc_rimefangAI::_events private
Referenced by JustDied(), Reset(), and UpdateAI().
_icyBlastCounter
uint8 npc_rimefang::npc_rimefangAI::_icyBlastCounter private
Referenced by Reset(), and UpdateAI().
_instance
InstanceScript* npc_rimefang::npc_rimefangAI::_instance private
Referenced by InitializeAI(), and JustRespawned().
_summoned
bool npc_rimefang::npc_rimefangAI::_summoned private
Referenced by DoAction(), JustReachedHome(), and Reset().