AzerothCore: azerothcore-wotlk/src/common/Utilities/ByteConverter.h File Reference
ByteConverter.h File Reference
#include "Define.h"
#include <vector>
Namespaces
namespace ByteConverter
Functions
template<std::size_t T>
void ByteConverter::convert (char *val)
template<>
void ByteConverter::convert< 0 > (char *)
template<>
void ByteConverter::convert< 1 > (char *)
template<typename T >
void ByteConverter::apply (T *val)
template<typename T >
void EndianConvert (T &val)
template<typename T >
void EndianConvertReverse (T &)
template<typename T >
void EndianConvertPtr (void *val)
template<typename T >
void EndianConvertPtrReverse (void *)
template<typename T >
void EndianConvert (T *)
template<typename T >
void EndianConvertReverse (T *)
void EndianConvert (uint8 &)
void EndianConvert (int8 &)
void EndianConvertReverse (uint8 &)
void EndianConvertReverse (int8 &)
Function Documentation
EndianConvert() [1/4]
void EndianConvert (int8 &) inline
{ }
EndianConvert() [2/4]
template<typename T > void EndianConvert (T & val) inline
{ ByteConverter::apply<T>(&val); }
Referenced by ByteBuffer::append(), DBCFileLoader::Record::getFloat(), DBCFileLoader::Record::getUInt(), WardenWin::InitializeModule(), DBCFileLoader::Load(), ByteBuffer::put(), ByteBuffer::read(), WorldSocket::ReadHeaderHandler(), and Warden::RequestModule().
EndianConvert() [3/4]
template<typename T > void EndianConvert (T *)
EndianConvert() [4/4]
void EndianConvert (uint8 &) inline
{ }
EndianConvertPtr()
template<typename T > void EndianConvertPtr (void * val) inline
{ ByteConverter::apply<T>(val); }
EndianConvertPtrReverse()
template<typename T > void EndianConvertPtrReverse (void *) inline
{ }
EndianConvertReverse() [1/4]
void EndianConvertReverse (int8 &) inline
{ }
EndianConvertReverse() [2/4]
template<typename T > void EndianConvertReverse (T &) inline
{ }
Referenced by WorldSocket::ReadHeaderHandler().
EndianConvertReverse() [3/4]
template<typename T > void EndianConvertReverse (T *)
EndianConvertReverse() [4/4]
void EndianConvertReverse (uint8 &) inline
{ }