AzerothCore: instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript Struct Reference
instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript Struct Reference
Public Member Functions
instance_utgarde_keep_InstanceMapScript (Map *pMap)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *plr) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 id) const override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
uint32 ForgeEventMask
std::string str_data
ObjectGuid GO_ForgeBellowGUID [3]
ObjectGuid GO_ForgeFireGUID [3]
ObjectGuid GO_ForgeAnvilGUID [3]
ObjectGuid GO_PortcullisGUID [2]
ObjectGuid NPC_SpecialDrakeGUID
bool bRocksAchiev
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_utgarde_keep_InstanceMapScript()
instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::instance_utgarde_keep_InstanceMapScript (Map * pMap) inline
                                                           : InstanceScript(pMap)
        {
            LoadObjectData(creatureData, nullptr);
        }
References creatureData, and InstanceScript::LoadObjectData().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case 7231: // On The Rocks
                    return bRocksAchiev;
            }
            return false;
        }
References bRocksAchiev.
GetData()
uint32 instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::GetData (uint32 id) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (id)
            {
                case DATA_KELESETH:
                case DATA_DALRONN_AND_SKARVALD:
                case DATA_INGVAR:
                    return m_auiEncounter[id];
                case DATA_FORGE_1:
                case DATA_FORGE_2:
                case DATA_FORGE_3:
                    return ForgeEventMask & (uint32)(1 << (id - 100));
            }
            return 0;
        }
References DATA_DALRONN_AND_SKARVALD, DATA_FORGE_1, DATA_FORGE_2, DATA_FORGE_3, DATA_INGVAR, DATA_KELESETH, ForgeEventMask, and m_auiEncounter.
Initialize()
void instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
            ForgeEventMask = 0;
            bRocksAchiev = true;
        }
References bRocksAchiev, ForgeEventMask, and m_auiEncounter.
IsEncounterInProgress()
bool instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                if (m_auiEncounter[i] == IN_PROGRESS) return true;
            return false;
        }
References IN_PROGRESS, m_auiEncounter, and MAX_ENCOUNTER.
OnCreatureCreate()
void instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_ENSLAVED_PROTO_DRAKE:
                    if (creature->GetPositionX() < 250.0f) NPC_SpecialDrakeGUID = creature->GetGUID();
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References Object::GetEntry(), Object::GetGUID(), Position::GetPositionX(), NPC_ENSLAVED_PROTO_DRAKE, NPC_SpecialDrakeGUID, and InstanceScript::OnCreatureCreate().
OnGameObjectCreate()
void instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_BELLOW_1:
                    GO_ForgeBellowGUID[0] = go->GetGUID();
                    if (ForgeEventMask & 1) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_BELLOW_2:
                    GO_ForgeBellowGUID[1] = go->GetGUID();
                    if (ForgeEventMask & 2) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_BELLOW_3:
                    GO_ForgeBellowGUID[2] = go->GetGUID();
                    if (ForgeEventMask & 4) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_FORGEFIRE_1:
                    GO_ForgeFireGUID[0] = go->GetGUID();
                    if (ForgeEventMask & 1) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_FORGEFIRE_2:
                    GO_ForgeFireGUID[1] = go->GetGUID();
                    if (ForgeEventMask & 2) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_FORGEFIRE_3:
                    GO_ForgeFireGUID[2] = go->GetGUID();
                    if (ForgeEventMask & 4) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_GLOWING_ANVIL_1:
                    GO_ForgeAnvilGUID[0] = go->GetGUID();
                    if (ForgeEventMask & 1) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_GLOWING_ANVIL_2:
                    GO_ForgeAnvilGUID[1] = go->GetGUID();
                    if (ForgeEventMask & 2) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_GLOWING_ANVIL_3:
                    GO_ForgeAnvilGUID[2] = go->GetGUID();
                    if (ForgeEventMask & 4) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_GIANT_PORTCULLIS_1:
                    GO_PortcullisGUID[0] = go->GetGUID();
                    if (m_auiEncounter[2] == DONE) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_GIANT_PORTCULLIS_2:
                    GO_PortcullisGUID[1] = go->GetGUID();
                    if (m_auiEncounter[2] == DONE) HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
            }
        }
References DONE, ObjectGuid::Empty, ForgeEventMask, Object::GetEntry(), Object::GetGUID(), GO_BELLOW_1, GO_BELLOW_2, GO_BELLOW_3, GO_ForgeAnvilGUID, GO_ForgeBellowGUID, GO_FORGEFIRE_1, GO_FORGEFIRE_2, GO_FORGEFIRE_3, GO_ForgeFireGUID, GO_GIANT_PORTCULLIS_1, GO_GIANT_PORTCULLIS_2, GO_GLOWING_ANVIL_1, GO_GLOWING_ANVIL_2, GO_GLOWING_ANVIL_3, GO_PortcullisGUID, InstanceScript::HandleGameObject(), and m_auiEncounter.
OnPlayerEnter()
void instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnPlayerEnter (Player * plr) inline override virtual
Reimplemented from InstanceScript.
        {
            if (Creature* c = GetCreature(DATA_DARK_RANGER_MARRAH))
            {
                c->SetReactState(REACT_PASSIVE);
                c->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                if (plr && plr->GetTeamId() == TEAM_HORDE)
                {
                    if (!c->IsVisible())
                        c->SetVisible(true);
                }
                else if (c->IsVisible())
                {
                    c->SetVisible(false);
                }
            }
        }
References DATA_DARK_RANGER_MARRAH, InstanceScript::GetCreature(), Player::GetTeamId(), REACT_PASSIVE, TEAM_HORDE, and UNIT_FLAG_NON_ATTACKABLE.
ReadSaveDataMore()
void instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> m_auiEncounter[0];
            data >> m_auiEncounter[1];
            data >> m_auiEncounter[2];
            data >> ForgeEventMask;
        }
References ForgeEventMask, and m_auiEncounter.
SetData()
void instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_KELESETH:
                    m_auiEncounter[0] = data;
                    if (data == NOT_STARTED)
                        bRocksAchiev = true;
                    break;
                case DATA_ON_THE_ROCKS_ACHIEV:
                    bRocksAchiev = false;
                    break;
                case DATA_DALRONN_AND_SKARVALD:
                    if (data == NOT_STARTED)
                    {
                        if (Creature* c = GetCreature(DATA_DALRONN))
                            if (c->isDead())
{
                                c->AI()->DoAction(-1);
                                c->Respawn();
                            }
                        if (Creature* c = GetCreature(DATA_SKARVALD))
                            if (c->isDead())
                                c->Respawn();
                        if (Creature* c = GetCreature(DATA_DALRONN_GHOST))
{
                            c->AI()->DoAction(-1);
                            c->DespawnOrUnsummon();
                        }
                        if (Creature* c = GetCreature(DATA_SKARVALD_GHOST))
                            c->DespawnOrUnsummon();
                    }
                    if (data == DONE)
                    {
                        if (Creature* c = GetCreature(DATA_DALRONN_GHOST))
{
                            c->AI()->DoAction(-1);
                            c->DespawnOrUnsummon();
                        }
                        if (Creature* c = GetCreature(DATA_SKARVALD_GHOST))
                            c->DespawnOrUnsummon();
                    }
                    m_auiEncounter[1] = data;
                    break;
                case DATA_UNLOCK_SKARVALD_LOOT:
                    if (Creature* c = GetCreature(DATA_SKARVALD))
                    {
                        c->SetDynamicFlag(UNIT_DYNFLAG_LOOTABLE | UNIT_DYNFLAG_TAPPED | UNIT_DYNFLAG_TAPPED_BY_PLAYER);
                        c->SetLootMode(1);
                        c->loot.clear();
                        if (uint32 lootid = c->GetCreatureTemplate()->lootid)
                            c->loot.FillLoot(lootid, LootTemplates_Creature, c->GetLootRecipient(), false, false, c->GetLootMode(), c);
                        if (c->GetLootMode())
                            c->loot.generateMoneyLoot(c->GetCreatureTemplate()->mingold, c->GetCreatureTemplate()->maxgold);
                        c->DestroyForNearbyPlayers();
                        c->SetVisible(true);
                    }
                    break;
                case DATA_UNLOCK_DALRONN_LOOT:
                    if (Creature* c = GetCreature(DATA_DALRONN))
                    {
                        c->AI()->DoAction(-1);
                        c->SetDynamicFlag(UNIT_DYNFLAG_LOOTABLE | UNIT_DYNFLAG_TAPPED | UNIT_DYNFLAG_TAPPED_BY_PLAYER);
                        c->SetLootMode(1);
                        c->loot.clear();
                        if (uint32 lootid = c->GetCreatureTemplate()->lootid)
                            c->loot.FillLoot(lootid, LootTemplates_Creature, c->GetLootRecipient(), false, false, c->GetLootMode(), c);
                        if (c->GetLootMode())
                            c->loot.generateMoneyLoot(c->GetCreatureTemplate()->mingold, c->GetCreatureTemplate()->maxgold);
                        c->DestroyForNearbyPlayers();
                        c->SetVisible(true);
                    }
                    break;
                case DATA_INGVAR:
                    if (data == DONE)
                    {
                        HandleGameObject(GO_PortcullisGUID[0], true);
                        HandleGameObject(GO_PortcullisGUID[1], true);
                    }
                    m_auiEncounter[2] = data;
                    break;
                case DATA_FORGE_1:
                case DATA_FORGE_2:
                case DATA_FORGE_3:
                    if (data == NOT_STARTED)
                    {
                        HandleGameObject(GO_ForgeBellowGUID[type - 100], false);
                        HandleGameObject(GO_ForgeFireGUID[type - 100], false);
                        HandleGameObject(GO_ForgeAnvilGUID[type - 100], false);
                        ForgeEventMask &= ~((uint32)(1 << (type - 100)));
                    }
                    else
                    {
                        HandleGameObject(GO_ForgeBellowGUID[type - 100], true);
                        HandleGameObject(GO_ForgeFireGUID[type - 100], true);
                        HandleGameObject(GO_ForgeAnvilGUID[type - 100], true);
                        ForgeEventMask |= (uint32)(1 << (type - 100));
                    }
                    break;
                case DATA_SPECIAL_DRAKE:
                    if (Creature* c = instance->GetCreature(NPC_SpecialDrakeGUID))
                        c->AI()->SetData(28, 6);
                    break;
            }
            if (data == DONE)
            {
                SaveToDB();
            }
        }
References bRocksAchiev, DATA_DALRONN, DATA_DALRONN_AND_SKARVALD, DATA_DALRONN_GHOST, DATA_FORGE_1, DATA_FORGE_2, DATA_FORGE_3, DATA_INGVAR, DATA_KELESETH, DATA_ON_THE_ROCKS_ACHIEV, DATA_SKARVALD, DATA_SKARVALD_GHOST, DATA_SPECIAL_DRAKE, DATA_UNLOCK_DALRONN_LOOT, DATA_UNLOCK_SKARVALD_LOOT, DONE, ForgeEventMask, Map::GetCreature(), InstanceScript::GetCreature(), GO_ForgeAnvilGUID, GO_ForgeBellowGUID, GO_ForgeFireGUID, GO_PortcullisGUID, InstanceScript::HandleGameObject(), InstanceScript::instance, LootTemplates_Creature, m_auiEncounter, NOT_STARTED, NPC_SpecialDrakeGUID, InstanceScript::SaveToDB(), UNIT_DYNFLAG_LOOTABLE, UNIT_DYNFLAG_TAPPED, and UNIT_DYNFLAG_TAPPED_BY_PLAYER.
WriteSaveDataMore()
void instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << m_auiEncounter[0] << ' ' << m_auiEncounter[1] << ' ' << m_auiEncounter[2] << ' ' << ForgeEventMask;
        }
References ForgeEventMask, and m_auiEncounter.
Member Data Documentation
bRocksAchiev
bool instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::bRocksAchiev
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
ForgeEventMask
uint32 instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::ForgeEventMask
Referenced by GetData(), Initialize(), OnGameObjectCreate(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
GO_ForgeAnvilGUID
ObjectGuid instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::GO_ForgeAnvilGUID[3]
Referenced by OnGameObjectCreate(), and SetData().
GO_ForgeBellowGUID
ObjectGuid instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::GO_ForgeBellowGUID[3]
Referenced by OnGameObjectCreate(), and SetData().
GO_ForgeFireGUID
ObjectGuid instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::GO_ForgeFireGUID[3]
Referenced by OnGameObjectCreate(), and SetData().
GO_PortcullisGUID
ObjectGuid instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::GO_PortcullisGUID[2]
Referenced by OnGameObjectCreate(), and SetData().
m_auiEncounter
uint32 instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::m_auiEncounter[MAX_ENCOUNTER]
Referenced by GetData(), Initialize(), IsEncounterInProgress(), OnGameObjectCreate(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
NPC_SpecialDrakeGUID
ObjectGuid instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::NPC_SpecialDrakeGUID
Referenced by OnCreatureCreate(), and SetData().
str_data
std::string instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::str_data