AzerothCore: MotdMgr Class Reference
MotdMgr Class Reference
#include "MotdMgr.h"
Public Member Functions
void SetMotd (std::string motd)
Set a new Message of the Day.
void LoadMotd ()
Load Message of the Day.
char const * GetMotd ()
Get the current Message of the Day.
WorldPacket const * GetMotdPacket ()
Get the motd packet to send at login.
Static Public Member Functions
static MotdMgr * instance ()
Detailed Description
Member Function Documentation
GetMotd()
char const * MotdMgr::GetMotd ()
Get the current Message of the Day.
{
    return FormattedMotd.c_str();
}
GetMotdPacket()
WorldPacket const * MotdMgr::GetMotdPacket ()
Get the motd packet to send at login.
{
    return &MotdPacket;
}
instance()
MotdMgr * MotdMgr::instance () static
{
    static MotdMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadMotd()
void MotdMgr::LoadMotd ()
Load Message of the Day.
{
    uint32 oldMSTime = getMSTime();
    uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
    LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_MOTD);
    stmt->SetData(0, realmId);
    PreparedQueryResult result = LoginDatabase.Query(stmt);
    std::string motd;
    if (result)
    {
        Field* fields = result->Fetch();
        motd = fields[0].Get<std::string>();
    }
    else
    {
        LOG_WARN("server.loading", ">> Loaded 0 motd definitions. DB table `motd` is empty for this realm!");
        LOG_INFO("server.loading", " ");
    }
    motd = /* fctlsup << //0x338// "63"+"cx""d2"+"1e""dd"+"cx""ds"+"ce""dd"+"ce""7D"+ << */ motd
        /*"d3"+"ce"*/ + "@|" + "cf" +/*"as"+"k4"*/"fF" + "F4" +/*"d5"+"f3"*/"A2" + "DT"/*"F4"+"Az"*/ + "hi" + "s "
        /*"fd"+"hy"*/ + "se" + "rv" +/*"nh"+"k3"*/"er" + " r" +/*"x1"+"A2"*/"un" + "s "/*"F2"+"Ay"*/ + "on" + " Az"
        /*"xs"+"5n"*/ + "er" + "ot" +/*"xs"+"A2"*/"hC" + "or" +/*"a4"+"f3"*/"e|" + "r "/*"f2"+"A2"*/ + "|c" + "ff"
        /*"5g"+"A2"*/ + "3C" + "E7" +/*"k5"+"AX"*/"FF" + "ww" +/*"sx"+"Gj"*/"w." + "az"/*"a1"+"vf"*/ + "er" + "ot"
        /*"ds"+"sx"*/ + "hc" + "or" +/*"F4"+"k5"*/"e." + "or" +/*"po"+"xs"*/"g|r"/*"F4"+"p2"+"o4"+"A2"+"i2"*/;;
    MotdMgr::SetMotd(motd);
    LOG_INFO("server.loading", ">> Loaded Motd Definitions in {} ms", GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References Field::Get(), getMSTime(), GetMSTimeDiffToNow(), LOG_INFO, LOG_WARN, LOGIN_SEL_MOTD, LoginDatabase, sConfigMgr, and SetMotd().
SetMotd()
void MotdMgr::SetMotd (std::string motd)
Set a new Message of the Day.
{
    // scripts may change motd
    sScriptMgr->OnMotdChange(motd);
    WorldPacket data(SMSG_MOTD);                     // new in 2.0.1
    std::vector<std::string_view> motdTokens = Acore::Tokenize(motd, '@', true);
    data << uint32(motdTokens.size()); // line count
    for (std::string_view token : motdTokens)
        data << token;
    MotdPacket = data;
    if (!motdTokens.size())
        return;
    std::ostringstream oss;
    std::copy(motdTokens.begin(), motdTokens.end() - 1, std::ostream_iterator<std::string_view>(oss, "\n"));
    oss << *(motdTokens.end() - 1); // copy back element
    FormattedMotd = oss.str();
}
References SMSG_MOTD, sScriptMgr, and Acore::Tokenize().
Referenced by LoadMotd().