AzeorthCore: boss_ossirian Struct Reference
boss_ossirian Struct Reference
Public Member Functions
boss_ossirian (Creature *creature)
void InitializeAI () override
void Reset () override
void JustSummoned (Creature *creature) override
void SpellHit (Unit *, SpellInfo const *spell) override
void SetGUID (ObjectGuid guid, int32 action) override
void EnterCombat (Unit *who) override
void SummonedCreatureDespawn (Creature *summon) override
void KilledUnit (Unit *) override
void SpawnNextCrystal (uint8 count=1)
void MoveInLineOfSight (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
virtual void ExecuteEvent (uint32)
void Reset () override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
Cast Spell.
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
Play sound.
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
Reset Threat.
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
Modify Unit Threat.
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
Teleport player.
void DoTeleportAll (float x, float y, float z, float o)
Teleport all.
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
Set Combat Movement.
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectTargetMethod targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Protected Attributes
uint8 _crystalIterator
ObjectGuid _firstCrystalGUID
bool _saidIntro
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Detailed Description
Constructor & Destructor Documentation
boss_ossirian()
boss_ossirian::boss_ossirian (Creature * creature) inline
                                      : BossAI(creature, DATA_OSSIRIAN)
    {
        _saidIntro = false;
    }
References _saidIntro.
Member Function Documentation
EnterCombat()
void boss_ossirian::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
    {
        BossAI::EnterCombat(who);
        events.Reset();
        events.ScheduleEvent(EVENT_SPEEDUP, 10s);
        events.ScheduleEvent(EVENT_SILENCE, 30s);
        events.ScheduleEvent(EVENT_CYCLONE, 20s);
        events.ScheduleEvent(EVENT_STOMP, 30s);
        DoCastSelf(SPELL_STRENGTH_OF_OSSIRIAN);
        Talk(SAY_AGGRO);
        Map* map = me->GetMap();
        if (!map->IsDungeon())
            return;
        WorldPackets::Misc::Weather weather(WEATHER_STATE_HEAVY_SANDSTORM, 1.0f);
        map->SendToPlayers(weather.Write());
        SpawnNextCrystal(3);
        std::list<uint32> pathIds = { 1446800, 1446790 };
        for (Position pos : VortexPositions)
        {
            if (Creature* vortex = me->SummonCreature(NPC_SAND_VORTEX, pos))
            {
                vortex->GetMotionMaster()->MovePath(pathIds.front(), true);
                pathIds.reverse();
            }
        }
    }
References UnitAI::DoCastSelf(), BossAI::EnterCombat(), EVENT_CYCLONE, EVENT_SILENCE, EVENT_SPEEDUP, EVENT_STOMP, WorldObject::GetMap(), Map::IsDungeon(), ScriptedAI::me, NPC_SAND_VORTEX, SAY_AGGRO, Map::SendToPlayers(), SpawnNextCrystal(), SPELL_STRENGTH_OF_OSSIRIAN, WorldObject::SummonCreature(), VortexPositions, WEATHER_STATE_HEAVY_SANDSTORM, and WorldPackets::Misc::Weather::Write().
InitializeAI()
void boss_ossirian::InitializeAI () inline override virtual
Reimplemented from UnitAI.
    {
        Reset();
    }
References Reset().
JustSummoned()
void boss_ossirian::JustSummoned (Creature * creature) inline override virtual
Reimplemented from BossAI.
    {
        summons.Summon(creature);
    }
References SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_ossirian::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        Talk(SAY_SLAY);
    }
References SAY_SLAY.
MoveInLineOfSight()
void boss_ossirian::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
    {
        if (!_saidIntro)
        {
            Talk(SAY_INTRO);
            _saidIntro = true;
        }
        BossAI::MoveInLineOfSight(who);
    }
References _saidIntro, CreatureAI::MoveInLineOfSight(), and SAY_INTRO.
Reset()
void boss_ossirian::Reset () inline override virtual
Reimplemented from BossAI.
    {
        BossAI::Reset();
        _crystalIterator = urand(1, NUM_CRYSTALS - 1);
        if (!ObjectAccessor::GetGameObject(*me, _firstCrystalGUID))
        {
            if (Creature* trigger = me->GetMap()->SummonCreature(NPC_OSSIRIAN_TRIGGER, CrystalCoordinates[0]))
            {
                if (GameObject* crystal = me->SummonGameObject(GO_OSSIRIAN_CRYSTAL,
                    CrystalCoordinates[0].GetPositionX(),
                    CrystalCoordinates[0].GetPositionY(),
                    CrystalCoordinates[0].GetPositionZ(),
                    0, 0, 0, 0, 0, uint32(-1)))
                {
                    _firstCrystalGUID = crystal->GetGUID();
                    crystal->SetOwnerGUID(ObjectGuid::Empty);
                    crystal->RemoveGameObjectFlag(GO_FLAG_IN_USE);
                    crystal->AI()->SetGUID(trigger->GetGUID(), GUID_TRIGGER_PAIR);
                }
            }
        }
    }
References _crystalIterator, _firstCrystalGUID, CrystalCoordinates, ObjectGuid::Empty, ObjectAccessor::GetGameObject(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_FLAG_IN_USE, GO_OSSIRIAN_CRYSTAL, GUID_TRIGGER_PAIR, ScriptedAI::me, NPC_OSSIRIAN_TRIGGER, NUM_CRYSTALS, BossAI::Reset(), Map::SummonCreature(), WorldObject::SummonGameObject(), and urand().
Referenced by InitializeAI().
SetGUID()
void boss_ossirian::SetGUID (ObjectGuid guid, int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        if (action == ACTION_TRIGGER_WEAKNESS && guid != _firstCrystalGUID)
        {
            SpawnNextCrystal();
        }
    }
References _firstCrystalGUID, ACTION_TRIGGER_WEAKNESS, and SpawnNextCrystal().
SpawnNextCrystal()
void boss_ossirian::SpawnNextCrystal (uint8 count = 1) inline
    {
        for (uint8 i = 0; i < count; ++i)
        {
            if (_crystalIterator == NUM_CRYSTALS)
                _crystalIterator = 1;
            if (Creature* trigger = me->SummonCreature(NPC_OSSIRIAN_TRIGGER, CrystalCoordinates[_crystalIterator]))
            {
                if (GameObject* crystal = trigger->SummonGameObject(GO_OSSIRIAN_CRYSTAL,
                    CrystalCoordinates[_crystalIterator].GetPositionX(),
                    CrystalCoordinates[_crystalIterator].GetPositionY(),
                    CrystalCoordinates[_crystalIterator].GetPositionZ(),
                    0, 0, 0, 0, 0, uint32(-1)))
                {
                    ++_crystalIterator;
                    crystal->SetOwnerGUID(ObjectGuid::Empty);
                    crystal->RemoveGameObjectFlag(GO_FLAG_IN_USE);
                    crystal->AI()->SetGUID(trigger->GetGUID(), GUID_TRIGGER_PAIR);
                }
            }
        }
    }
References _crystalIterator, CrystalCoordinates, ObjectGuid::Empty, Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_FLAG_IN_USE, GO_OSSIRIAN_CRYSTAL, GUID_TRIGGER_PAIR, ScriptedAI::me, NPC_OSSIRIAN_TRIGGER, NUM_CRYSTALS, WorldObject::SummonCreature(), and WorldObject::SummonGameObject().
Referenced by EnterCombat(), and SetGUID().
SpellHit()
void boss_ossirian::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
    {
        for (uint32 weakness : spellWeakness)
        {
            if (spell->Id == weakness)
            {
                me->RemoveAurasDueToSpell(SPELL_STRENGTH_OF_OSSIRIAN);
            }
        }
    }
References SpellInfo::Id, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SPELL_STRENGTH_OF_OSSIRIAN, and spellWeakness.
SummonedCreatureDespawn()
void boss_ossirian::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from BossAI.
    {
        summons.Despawn(summon);
        if (summon->GetEntry() == NPC_OSSIRIAN_TRIGGER)
        {
            if (GameObject* crystal = GetClosestGameObjectWithEntry(summon, GO_OSSIRIAN_CRYSTAL, 5.0f))
            {
                crystal->Delete();
            }
        }
    }
References SummonList::Despawn(), GetClosestGameObjectWithEntry(), Object::GetEntry(), GO_OSSIRIAN_CRYSTAL, NPC_OSSIRIAN_TRIGGER, and BossAI::summons.
UpdateAI()
void boss_ossirian::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
    {
        if (!UpdateVictim())
            return;
        events.Update(diff);
        bool applySupreme = true;
        if (me->HasAura(SPELL_STRENGTH_OF_OSSIRIAN))
        {
            applySupreme = false;
        }
        else
        {
            for (uint32 weakness : spellWeakness)
            {
                if (me->HasAura(weakness))
                {
                    applySupreme = false;
                    break;
                }
            }
        }
        if (applySupreme)
        {
            DoCastSelf(SPELL_STRENGTH_OF_OSSIRIAN);
            Talk(SAY_SUPREME);
        }
        while (uint32 eventId = events.ExecuteEvent())
        {
            switch (eventId)
            {
                case EVENT_SPEEDUP:
                    DoCastSelf(SPELL_SPEED_BURST);
                    break;
                case EVENT_SILENCE:
                    DoCastAOE(SPELL_CURSE_OF_TONGUES);
                    events.ScheduleEvent(EVENT_SILENCE, 20s, 30s);
                    break;
                case EVENT_CYCLONE:
                    DoCastVictim(SPELL_ENVELOPING_WINDS);
                    events.ScheduleEvent(EVENT_CYCLONE, 20s);
                    break;
                case EVENT_STOMP:
                    DoCastAOE(SPELL_WAR_STOMP);
                    events.ScheduleEvent(EVENT_STOMP, 30s);
                    break;
                default:
                    break;
            }
        }
        DoMeleeAttackIfReady();
    }
References UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EVENT_CYCLONE, EVENT_SILENCE, EVENT_SPEEDUP, EVENT_STOMP, Unit::HasAura(), ScriptedAI::me, SAY_SUPREME, SPELL_CURSE_OF_TONGUES, SPELL_ENVELOPING_WINDS, SPELL_SPEED_BURST, SPELL_STRENGTH_OF_OSSIRIAN, SPELL_WAR_STOMP, spellWeakness, and CreatureAI::UpdateVictim().
Member Data Documentation
_crystalIterator
uint8 boss_ossirian::_crystalIterator protected
Referenced by Reset(), and SpawnNextCrystal().
_firstCrystalGUID
ObjectGuid boss_ossirian::_firstCrystalGUID protected
Referenced by Reset(), and SetGUID().
_saidIntro
bool boss_ossirian::_saidIntro protected
Referenced by boss_ossirian(), and MoveInLineOfSight().