AzerothCore: BGScript Class Reference
BGScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnBattlegroundStart (Battleground *)
This hook runs before start Battleground.
virtual void OnBattlegroundEndReward (Battleground *, Player *, TeamId)
virtual void OnBattlegroundUpdate (Battleground *, uint32)
virtual void OnBattlegroundAddPlayer (Battleground *, Player *)
virtual void OnBattlegroundBeforeAddPlayer (Battleground *, Player *)
virtual void OnBattlegroundRemovePlayerAtLeave (Battleground *, Player *)
virtual void OnQueueUpdate (BattlegroundQueue *, uint32, BattlegroundTypeId, BattlegroundBracketId, uint8, bool, uint32)
virtual void OnAddGroup (BattlegroundQueue *, GroupQueueInfo *, uint32 &, Player *, Group *, BattlegroundTypeId, PvPDifficultyEntry const *, uint8, bool, bool, uint32, uint32, uint32, uint32)
virtual bool CanFillPlayersToBG (BattlegroundQueue *, Battleground *, BattlegroundBracketId)
virtual bool IsCheckNormalMatch (BattlegroundQueue *, Battleground *, BattlegroundBracketId, uint32, uint32)
virtual bool CanSendMessageBGQueue (BattlegroundQueue *, Player *, Battleground *, PvPDifficultyEntry const *)
virtual bool OnBeforeSendJoinMessageArenaQueue (BattlegroundQueue *, Player *, GroupQueueInfo *, PvPDifficultyEntry const *, bool)
This hook runs before sending the join message during the arena queue, allowing you to run extra operations or disabling the join message.
virtual bool OnBeforeSendExitMessageArenaQueue (BattlegroundQueue *, GroupQueueInfo *)
This hook runs before sending the exit message during the arena queue, allowing you to run extra operations or disabling the exit message.
virtual void OnBattlegroundEnd (Battleground *, TeamId)
This hook runs after end Battleground.
virtual void OnBattlegroundDestroy (Battleground *)
This hook runs before Battleground destroy.
virtual void OnBattlegroundCreate (Battleground *)
This hook runs after Battleground create.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
BGScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
BGScript()
BGScript::BGScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<BGScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanFillPlayersToBG()
virtual bool BGScript::CanFillPlayersToBG (BattlegroundQueue * , Battleground * , BattlegroundBracketId) inline virtual
{ return true; }
Referenced by ScriptMgr::CanFillPlayersToBG().
CanSendMessageBGQueue()
virtual bool BGScript::CanSendMessageBGQueue (BattlegroundQueue * , Player * , Battleground * , PvPDifficultyEntry const *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanSendMessageBGQueue().
IsCheckNormalMatch()
virtual bool BGScript::IsCheckNormalMatch (BattlegroundQueue * , Battleground * , BattlegroundBracketId , uint32 , uint32) inline virtual
{ return false; };
Referenced by ScriptMgr::IsCheckNormalMatch().
IsDatabaseBound()
bool BGScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
OnAddGroup()
virtual void BGScript::OnAddGroup (BattlegroundQueue * , GroupQueueInfo * , uint32 & , Player * , Group * , BattlegroundTypeId , PvPDifficultyEntry const * , uint8 , bool , bool , uint32 , uint32 , uint32 , uint32) inline virtual
                                                                         { }
Referenced by ScriptMgr::OnAddGroup().
OnBattlegroundAddPlayer()
virtual void BGScript::OnBattlegroundAddPlayer (Battleground * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnBattlegroundAddPlayer().
OnBattlegroundBeforeAddPlayer()
virtual void BGScript::OnBattlegroundBeforeAddPlayer (Battleground * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnBattlegroundBeforeAddPlayer().
OnBattlegroundCreate()
virtual void BGScript::OnBattlegroundCreate (Battleground *) inline virtual
This hook runs after Battleground create.
Parameters
bg Contains information about the Battleground
{ }
Referenced by ScriptMgr::OnBattlegroundCreate().
OnBattlegroundDestroy()
virtual void BGScript::OnBattlegroundDestroy (Battleground *) inline virtual
This hook runs before Battleground destroy.
Parameters
bg Contains information about the Battleground
{ }
Referenced by ScriptMgr::OnBattlegroundDestroy().
OnBattlegroundEnd()
virtual void BGScript::OnBattlegroundEnd (Battleground * , TeamId) inline virtual
This hook runs after end Battleground.
Parameters
bg Contains information about the Battleground
TeamId Contains information about the winneer team
{ }
Referenced by ScriptMgr::OnBattlegroundEnd().
OnBattlegroundEndReward()
virtual void BGScript::OnBattlegroundEndReward (Battleground * , Player * , TeamId) inline virtual
{ }
Referenced by ScriptMgr::OnBattlegroundEndReward().
OnBattlegroundRemovePlayerAtLeave()
virtual void BGScript::OnBattlegroundRemovePlayerAtLeave (Battleground * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnBattlegroundRemovePlayerAtLeave().
OnBattlegroundStart()
virtual void BGScript::OnBattlegroundStart (Battleground *) inline virtual
This hook runs before start Battleground.
Parameters
bg Contains information about the Battleground
{ }
Referenced by ScriptMgr::OnBattlegroundStart().
OnBattlegroundUpdate()
virtual void BGScript::OnBattlegroundUpdate (Battleground * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnBattlegroundUpdate().
OnBeforeSendExitMessageArenaQueue()
virtual bool BGScript::OnBeforeSendExitMessageArenaQueue (BattlegroundQueue * , GroupQueueInfo *) inline virtual
This hook runs before sending the exit message during the arena queue, allowing you to run extra operations or disabling the exit message.
Parameters
queue Contains information about the Arena queue
ginfo Contains information about the group of the queue
Returns
True if you want to continue sending the message, false if you want to disable the message
{ return true; }
Referenced by ScriptMgr::OnBeforeSendExitMessageArenaQueue().
OnBeforeSendJoinMessageArenaQueue()
virtual bool BGScript::OnBeforeSendJoinMessageArenaQueue (BattlegroundQueue * , Player * , GroupQueueInfo * , PvPDifficultyEntry const * , bool) inline virtual
This hook runs before sending the join message during the arena queue, allowing you to run extra operations or disabling the join message.
Parameters
queue Contains information about the Arena queue
leader Contains information about the player leader
ginfo Contains information about the group of the queue
bracketEntry Contains information about the bracket
isRated Contains information about rated arena or skirmish
Returns
True if you want to continue sending the message, false if you want to disable the message
{ return true; }
Referenced by ScriptMgr::OnBeforeSendJoinMessageArenaQueue().
OnQueueUpdate()
virtual void BGScript::OnQueueUpdate (BattlegroundQueue * , uint32 , BattlegroundTypeId , BattlegroundBracketId , uint8 , bool , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnQueueUpdate().