AzerothCore: azerothcore-wotlk/src/server/scripts/Commands/cs_misc.cpp File Reference
cs_misc.cpp File Reference
#include "AccountMgr.h"
#include "ArenaTeamMgr.h"
#include "BattlegroundMgr.h"
#include "CellImpl.h"
#include "CharacterCache.h"
#include "Chat.h"
#include "CommandScript.h"
#include "GameGraveyard.h"
#include "GameTime.h"
#include "GridNotifiers.h"
#include "Group.h"
#include "GuildMgr.h"
#include "IPLocation.h"
#include "InstanceSaveMgr.h"
#include "LFG.h"
#include "LFGMgr.h"
#include "Language.h"
#include "MapMgr.h"
#include "MiscPackets.h"
#include "MMapFactory.h"
#include "MovementGenerator.h"
#include "ObjectAccessor.h"
#include "Pet.h"
#include "Player.h"
#include "Realm.h"
#include "ScriptMgr.h"
#include "SpellAuras.h"
#include "TargetedMovementGenerator.h"
#include "Tokenize.h"
#include "WeatherMgr.h"
#include "GridNotifiersImpl.h"
Classes
class misc_commandscript
Functions
std::string const GetLocalizeCreatureName (Creature *creature, LocaleConstant locale)
void AddSC_misc_commandscript ()
Variables
constexpr auto SPELL_STUCK = 7355
constexpr auto SPELL_FREEZE = 9454
Function Documentation
AddSC_misc_commandscript()
void AddSC_misc_commandscript ()
{
    new misc_commandscript();
}
Referenced by AddCommandsScripts().
GetLocalizeCreatureName()
std::string const GetLocalizeCreatureName (Creature * creature, LocaleConstant locale)
{
    auto creatureTemplate = sObjectMgr->GetCreatureTemplate(creature->GetEntry());
    auto cretureLocale = sObjectMgr->GetCreatureLocale(creature->GetEntry());
    std::string name;
    if (cretureLocale)
    {
        name = cretureLocale->Name[locale];
    }
    if (name.empty() && creatureTemplate)
    {
        name = creatureTemplate->Name;
    }
    if (name.empty())
    {
        name = "Unknown creature";
    }
    return name;
}
References Object::GetEntry(), and sObjectMgr.
Referenced by misc_commandscript::HandleFreezeCommand(), and misc_commandscript::HandleUnFreezeCommand().
Variable Documentation
SPELL_FREEZE
constexpr auto SPELL_FREEZE = 9454 constexpr
Referenced by misc_commandscript::HandleFreezeCommand(), and misc_commandscript::HandleUnFreezeCommand().
SPELL_STUCK
constexpr auto SPELL_STUCK = 7355 constexpr
Todo:
: this import is not necessary for compilation and marked as unused by the IDE
Referenced by misc_commandscript::HandleUnstuckCommand().