AzerothCore: npc_announcer_toc5 Class Reference
npc_announcer_toc5 Class Reference
Classes
struct npc_announcer_toc5AI
Public Member Functions
npc_announcer_toc5 ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_announcer_toc5()
npc_announcer_toc5::npc_announcer_toc5 () inline
: CreatureScript("npc_announcer_toc5") {}
Member Function Documentation
GetAI()
CreatureAI * npc_announcer_toc5::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return GetTrialOfTheChampionAI<npc_announcer_toc5AI>(creature);
    }
OnGossipHello()
bool npc_announcer_toc5::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (!creature->HasNpcFlag(UNIT_NPC_FLAG_GOSSIP))
            return true;
        InstanceScript* pInstance = creature->GetInstanceScript();
        if (!pInstance)
            return true;
        uint32 gossipTextId = 0;
        switch (pInstance->GetData(DATA_INSTANCE_PROGRESS))
        {
            case INSTANCE_PROGRESS_INITIAL:
                if (!player->GetVehicle())
                {
                    if (pInstance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE)
                        gossipTextId = NPC_TEXT_NOT_MOUNTED_H;
                    else
                        gossipTextId = NPC_TEXT_NOT_MOUNTED_A;
                }
                else
                {
                    gossipTextId = NPC_TEXT_CHALLENGE_1;
                    AddGossipItemFor(player, GOSSIP_MENU_STAGE, GOSSIP_START_EVENT_1A, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                    AddGossipItemFor(player, GOSSIP_MENU_STAGE, GOSSIP_START_EVENT_1B, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                }
                break;
            case INSTANCE_PROGRESS_CHAMPIONS_DEAD:
                gossipTextId = NPC_TEXT_CHALLENGE_2;
                AddGossipItemFor(player, GOSSIP_MENU_STAGE, GOSSIP_START_EVENT_2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                break;
            case INSTANCE_PROGRESS_ARGENT_CHALLENGE_DIED:
                gossipTextId = NPC_TEXT_CHALLENGE_3;
                AddGossipItemFor(player, GOSSIP_MENU_STAGE, GOSSIP_START_EVENT_3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
                break;
            default:
                return true;
        }
        SendGossipMenuFor(player, gossipTextId, creature->GetGUID());
        return true;
    }
References AddGossipItemFor(), DATA_INSTANCE_PROGRESS, DATA_TEAMID_IN_INSTANCE, ZoneScript::GetData(), Object::GetGUID(), WorldObject::GetInstanceScript(), Unit::GetVehicle(), GOSSIP_ACTION_INFO_DEF, GOSSIP_MENU_STAGE, GOSSIP_SENDER_MAIN, GOSSIP_START_EVENT_1A, GOSSIP_START_EVENT_1B, GOSSIP_START_EVENT_2, GOSSIP_START_EVENT_3, Unit::HasNpcFlag(), INSTANCE_PROGRESS_ARGENT_CHALLENGE_DIED, INSTANCE_PROGRESS_CHAMPIONS_DEAD, INSTANCE_PROGRESS_INITIAL, NPC_TEXT_CHALLENGE_1, NPC_TEXT_CHALLENGE_2, NPC_TEXT_CHALLENGE_3, NPC_TEXT_NOT_MOUNTED_A, NPC_TEXT_NOT_MOUNTED_H, SendGossipMenuFor(), TEAM_HORDE, and UNIT_NPC_FLAG_GOSSIP.
OnGossipSelect()
bool npc_announcer_toc5::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
    {
        if (!creature->HasNpcFlag(UNIT_NPC_FLAG_GOSSIP))
            return true;
        InstanceScript* pInstance = creature->GetInstanceScript();
        if (!pInstance)
            return true;
        if (uiAction == GOSSIP_ACTION_INFO_DEF + 1 || uiAction == GOSSIP_ACTION_INFO_DEF + 2 || uiAction == GOSSIP_ACTION_INFO_DEF + 3 || uiAction == GOSSIP_ACTION_INFO_DEF + 4)
        {
            pInstance->SetData(DATA_ANNOUNCER_GOSSIP_SELECT, (uiAction == GOSSIP_ACTION_INFO_DEF + 2 ? 1 : 0));
            creature->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
        }
        CloseGossipMenuFor(player);
        return true;
    }
References CloseGossipMenuFor(), DATA_ANNOUNCER_GOSSIP_SELECT, WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, Unit::HasNpcFlag(), Unit::RemoveNpcFlag(), ZoneScript::SetData(), and UNIT_NPC_FLAG_GOSSIP.