AzerothCore: LastPhaseIceTombTargetSelector Struct Reference
LastPhaseIceTombTargetSelector Struct Reference
Public Member Functions
LastPhaseIceTombTargetSelector (Creature *source)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
Detailed Description
Constructor & Destructor Documentation
LastPhaseIceTombTargetSelector()
LastPhaseIceTombTargetSelector::LastPhaseIceTombTargetSelector (Creature * source) inline
: _source(source) { }
Member Function Documentation
operator()()
bool LastPhaseIceTombTargetSelector::operator() (Unit const * target) const inline
    {
        if (!target)
            return false;
        if (target->GetExactDist(_source) > 80.0f)
            return false;
        if (!target->IsPlayer())
            return false;
        if (target->HasAura(SPELL_FROST_IMBUED_BLADE))
            return false;
        if (target->IsImmunedToDamageOrSchool(SPELL_SCHOOL_MASK_ALL) || target->HasAura(SPELL_ICE_TOMB_UNTARGETABLE) || target->HasAura(SPELL_ICE_TOMB_DAMAGE) || target->HasAura(SPELL_TANK_MARKER_AURA) || target->HasSpiritOfRedemptionAura())
            return false;
        return target != _source->GetVictim();
    }
References _source, Position::GetExactDist(), Unit::GetVictim(), Unit::HasAura(), Unit::HasSpiritOfRedemptionAura(), Unit::IsImmunedToDamageOrSchool(), Object::IsPlayer(), SPELL_FROST_IMBUED_BLADE, SPELL_ICE_TOMB_DAMAGE, SPELL_ICE_TOMB_UNTARGETABLE, SPELL_SCHOOL_MASK_ALL, and SPELL_TANK_MARKER_AURA.
Member Data Documentation
_source
Creature const* LastPhaseIceTombTargetSelector::_source private
Referenced by operator()().