AzeorthCore: instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript Struct Reference
instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript Struct Reference
Public Member Functions
instance_obsidian_sanctum_InstanceMapScript (Map *pMap)
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *pCreature) override
ObjectGuid GetGuidData (uint32 uiData) const override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *, uint32) override
bool SetBossState (uint32 type, EncounterState state) override
void DoAction (int32 action) override
std::string GetSaveData () override
void Load (const char *strIn) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid m_uiSartharionGUID
ObjectGuid m_uiTenebronGUID
ObjectGuid m_uiShadronGUID
ObjectGuid m_uiVesperonGUID
ObjectGuid m_uiPortalGUID
uint8 portalCount
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Constructor & Destructor Documentation
instance_obsidian_sanctum_InstanceMapScript()
instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::instance_obsidian_sanctum_InstanceMapScript (Map * pMap) inline
                                                               : InstanceScript(pMap), portalCount(0)
        {
            SetBossNumber(MAX_ENCOUNTERS);
            LoadBossBoundaries(boundaries);
        }
References boundaries, InstanceScript::LoadBossBoundaries(), MAX_ENCOUNTERS, and InstanceScript::SetBossNumber().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch(criteria_id)
            {
                // Gonna Go When the Volcano Blows (10 player) (2047)
                case 7326:
                // Gonna Go When the Volcano Blows (25 player) (2048)
                case 7327:
                {
                    Creature const* sartharion = instance->GetCreature(m_uiSartharionGUID);
                    return sartharion && !sartharion->AI()->GetData(source->GetGUID().GetCounter());
                }
                // Less Is More (10 player) (624)
                case 7189:
                case 7190:
                case 7191:
                case 522:
                {
                    return instance->GetPlayersCountExceptGMs() < 9;
                }
                // Less Is More (25 player) (1877)
                case 7185:
                case 7186:
                case 7187:
                case 7188:
                {
                    return instance->GetPlayersCountExceptGMs() < 21;
                }
                // Twilight Assist (10 player) (2049)
                case 7328:
                // Twilight Assist (25 player) (2052)
                case 7331:
                {
                    Creature const* sartharion = instance->GetCreature(m_uiSartharionGUID);
                    return sartharion && sartharion->AI()->GetData(DATA_ACHIEVEMENT_DRAGONS_COUNT) >= 1;
                }
                // Twilight Duo (10 player) (2050)
                case 7329:
                // Twilight Duo (25 player) (2053)
                case 7332:
                {
                    Creature const* sartharion = instance->GetCreature(m_uiSartharionGUID);
                    return sartharion && sartharion->AI()->GetData(DATA_ACHIEVEMENT_DRAGONS_COUNT) >= 2;
                }
                // Twilight Zone (10 player) (2051)
                case 7330:
                // Twilight Zone (25 player) (2054)
                case 7333:
                {
                    Creature const* sartharion = instance->GetCreature(m_uiSartharionGUID);
                    return sartharion && sartharion->AI()->GetData(DATA_ACHIEVEMENT_DRAGONS_COUNT) >= 3;
                }
            }
            return false;
        }
References Creature::AI(), DATA_ACHIEVEMENT_DRAGONS_COUNT, ObjectGuid::GetCounter(), Map::GetCreature(), UnitAI::GetData(), Object::GetGUID(), Map::GetPlayersCountExceptGMs(), InstanceScript::instance, and m_uiSartharionGUID.
DoAction()
void instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::DoAction (int32 action) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (action)
            {
                case ACTION_ADD_PORTAL:
                {
                    if (!m_uiPortalGUID)
                    {
                        if (Creature* sartharion = instance->GetCreature(m_uiSartharionGUID))
{
                            if (GameObject* portal = sartharion->SummonGameObject(GO_TWILIGHT_PORTAL, 3247.29f, 529.804f, 58.9595f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0))
{
                                sartharion->RemoveGameObject(portal, false);
                                m_uiPortalGUID = portal->GetGUID();
                            }
                        }
                        portalCount = 0;
                    }
                    ++portalCount;
                    break;
                }
                case ACTION_CLEAR_PORTAL:
                {
                    --portalCount;
                    if (!portalCount)
                    {
                        if (GameObject* go = instance->GetGameObject(m_uiPortalGUID))
{
                            go->Delete();
                        }
                        DoRemoveAurasDueToSpellOnPlayers(SPELL_TWILIGHT_SHIFT);
                        m_uiPortalGUID.Clear();
                    }
                    break;
                }
            }
        }
References ACTION_ADD_PORTAL, ACTION_CLEAR_PORTAL, ObjectGuid::Clear(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), Map::GetCreature(), Map::GetGameObject(), GO_TWILIGHT_PORTAL, InstanceScript::instance, m_uiPortalGUID, m_uiSartharionGUID, portalCount, SPELL_TWILIGHT_SHIFT, and WorldObject::SummonGameObject().
GetGuidData()
ObjectGuid instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::GetGuidData (uint32 uiData) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch(uiData)
            {
                case DATA_SARTHARION:
                    return m_uiSartharionGUID;
                case DATA_TENEBRON:
                    return m_uiTenebronGUID;
                case DATA_SHADRON:
                    return m_uiShadronGUID;
                case DATA_VESPERON:
                    return m_uiVesperonGUID;
            }
            return ObjectGuid::Empty;
        }
References DATA_SARTHARION, DATA_SHADRON, DATA_TENEBRON, DATA_VESPERON, ObjectGuid::Empty, m_uiSartharionGUID, m_uiShadronGUID, m_uiTenebronGUID, and m_uiVesperonGUID.
GetSaveData()
std::string instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
        {
            OUT_SAVE_INST_DATA;
            std::ostringstream saveStream;
            saveStream << "O S " << GetBossSaveData();
            OUT_SAVE_INST_DATA_COMPLETE;
            return saveStream.str();
        }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
IsEncounterInProgress()
bool instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
            {
                if (GetBossState(i) == IN_PROGRESS)
                    return true;
            }
            return false;
        }
References InstanceScript::GetBossState(), IN_PROGRESS, and MAX_ENCOUNTERS.
Load()
void instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::Load (const char * strIn) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!strIn)
            {
                OUT_LOAD_INST_DATA_FAIL;
                return;
            }
            OUT_LOAD_INST_DATA(strIn);
            char dataHead1, dataHead2;
            std::istringstream loadStream(strIn);
            loadStream >> dataHead1 >> dataHead2;
            if (dataHead1 == 'O' && dataHead2 == 'S')
            {
                for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                {
                    uint32 temp;
                    loadStream >> temp;
                    if (temp == IN_PROGRESS)
                        temp = NOT_STARTED;
                    SetBossState(i, static_cast<EncounterState>(temp));
                }
            }
            OUT_LOAD_INST_DATA_COMPLETE;
        }
References IN_PROGRESS, MAX_ENCOUNTERS, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, and SetBossState().
OnCreatureCreate()
void instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::OnCreatureCreate (Creature * pCreature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch(pCreature->GetEntry())
            {
                case NPC_SARTHARION:
                    m_uiSartharionGUID = pCreature->GetGUID();
                    break;
                case NPC_TENEBRON:
                    m_uiTenebronGUID = pCreature->GetGUID();
                    break;
                case NPC_SHADRON:
                    m_uiShadronGUID = pCreature->GetGUID();
                    break;
                case NPC_VESPERON:
                    m_uiVesperonGUID = pCreature->GetGUID();
                    break;
            }
        }
References Object::GetEntry(), Object::GetGUID(), m_uiSartharionGUID, m_uiShadronGUID, m_uiTenebronGUID, m_uiVesperonGUID, NPC_SARTHARION, NPC_SHADRON, NPC_TENEBRON, and NPC_VESPERON.
SetBossState()
bool instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (InstanceScript::SetBossState(type, state))
            {
                return false;
            }
            if (state == DONE)
            {
                SaveToDB();
            }
            return true;
        }
References DONE, InstanceScript::SaveToDB(), and InstanceScript::SetBossState().
Referenced by Load().
Member Data Documentation
m_uiPortalGUID
ObjectGuid instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::m_uiPortalGUID private
Referenced by DoAction().
m_uiSartharionGUID
ObjectGuid instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::m_uiSartharionGUID private
Referenced by CheckAchievementCriteriaMeet(), DoAction(), GetGuidData(), and OnCreatureCreate().
m_uiShadronGUID
ObjectGuid instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::m_uiShadronGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiTenebronGUID
ObjectGuid instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::m_uiTenebronGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiVesperonGUID
ObjectGuid instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::m_uiVesperonGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
portalCount
uint8 instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::portalCount private
Referenced by DoAction().