version: '3.9'
services:
  gh-page:
    build: 
      context: .
      dockerfile: .env-files/Dockerfile.github
    ports:
     - 4000:4000
     - 35729:35729
    environment: 
     - BUNDLE_GEMFILE=.env-files/Gemfile.github
    volumes:
     - .:/srv/jekyll
     - github_site:/srv/jekyll/_site
     - /srv/jekyll/certs
    command: bundle exec jekyll serve  --ssl-cert certs/cert.pem --ssl-key certs/key.pem --host 0.0.0.0 --port 4000 --force_polling --livereload
volumes:
  github_site: