AzerothCore: Cell Struct Reference
Cell Struct Reference
#include "Cell.h"
Public Member Functions
Cell ()
Cell (Cell const &cell)
Cell (CellCoord const &p)
Cell (float x, float y)
void Compute (uint32 &x, uint32 &y) const
bool DiffCell (const Cell &cell) const
bool DiffGrid (const Cell &cell) const
uint32 CellX () const
uint32 CellY () const
uint32 GridX () const
uint32 GridY () const
bool NoCreate () const
void SetNoCreate ()
CellCoord GetCellCoord () const
Cell & operator= (Cell const &cell)
bool operator== (Cell const &cell) const
bool operator!= (Cell const &cell) const
template<class T , class CONTAINER >
void Visit (CellCoord const &, TypeContainerVisitor< T, CONTAINER > &visitor, Map &, WorldObject const &obj, float radius) const
template<class T , class CONTAINER >
void Visit (CellCoord const &, TypeContainerVisitor< T, CONTAINER > &visitor, Map &, float x, float y, float radius) const
Static Public Member Functions
static CellArea CalculateCellArea (float x, float y, float radius)
template<class T >
static void VisitGridObjects (WorldObject const *obj, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitWorldObjects (WorldObject const *obj, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitAllObjects (WorldObject const *obj, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitGridObjects (float x, float y, Map *map, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitWorldObjects (float x, float y, Map *map, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitAllObjects (float x, float y, Map *map, T &visitor, float radius, bool dont_load=true)
Public Attributes
union {
struct {
unsigned grid_x: 6
unsigned grid_y: 6
unsigned cell_x: 6
unsigned cell_y: 6
unsigned nocreate: 1
unsigned reserved: 7
} Part
uint32 All
} data
Private Member Functions
template<class T , class CONTAINER >
void VisitCircle (TypeContainerVisitor< T, CONTAINER > &, Map &, CellCoord const &, CellCoord const &) const
Detailed Description
Constructor & Destructor Documentation
Cell() [1/4]
Cell::Cell () inline
{ data.All = 0; }
References data.
Cell() [2/4]
Cell::Cell (Cell const & cell) inline
{ data.All = cell.data.All; }
References All, and data.
Cell() [3/4]
Cell::Cell (CellCoord const & p) inline explicit
{
    data.Part.grid_x = p.x_coord / MAX_NUMBER_OF_CELLS;
    data.Part.grid_y = p.y_coord / MAX_NUMBER_OF_CELLS;
    data.Part.cell_x = p.x_coord % MAX_NUMBER_OF_CELLS;
    data.Part.cell_y = p.y_coord % MAX_NUMBER_OF_CELLS;
    data.Part.nocreate = 0;
    data.Part.reserved = 0;
}
References data, MAX_NUMBER_OF_CELLS, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Cell() [4/4]
Cell::Cell (float x, float y) inline explicit
{
    CellCoord p = Acore::ComputeCellCoord(x, y);
    data.Part.grid_x = p.x_coord / MAX_NUMBER_OF_CELLS;
    data.Part.grid_y = p.y_coord / MAX_NUMBER_OF_CELLS;
    data.Part.cell_x = p.x_coord % MAX_NUMBER_OF_CELLS;
    data.Part.cell_y = p.y_coord % MAX_NUMBER_OF_CELLS;
    data.Part.nocreate = 0;
    data.Part.reserved = 0;
}
References Acore::ComputeCellCoord(), data, MAX_NUMBER_OF_CELLS, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Member Function Documentation
CalculateCellArea()
CellArea Cell::CalculateCellArea (float x, float y, float radius) inline static
{
    if (radius <= 0.0f)
    {
        CellCoord center = Acore::ComputeCellCoord(x, y).normalize();
        return CellArea(center, center);
    }
    CellCoord centerX = Acore::ComputeCellCoord(x - radius, y - radius).normalize();
    CellCoord centerY = Acore::ComputeCellCoord(x + radius, y + radius).normalize();
    return CellArea(centerX, centerY);
}
References Acore::ComputeCellCoord(), and CoordPair< LIMIT >::normalize().
Referenced by Visit(), Map::VisitNearbyCellsOf(), and Map::VisitNearbyCellsOfPlayer().
CellX()
uint32 Cell::CellX () const inline
{ return data.Part.cell_x; }
References data.
Referenced by Map::AddToGrid(), GridMap::getMinHeight(), misc_commandscript::HandleGPSCommand(), Map::SwitchGridContainers(), Map::Visit(), and ObjectWorldLoader::Visit().
CellY()
uint32 Cell::CellY () const inline
{ return data.Part.cell_y; }
References data.
Referenced by Map::AddToGrid(), GridMap::getMinHeight(), misc_commandscript::HandleGPSCommand(), Map::SwitchGridContainers(), Map::Visit(), and ObjectWorldLoader::Visit().
Compute()
void Cell::Compute (uint32 & x, uint32 & y) const inline
    {
        x = data.Part.grid_x * MAX_NUMBER_OF_CELLS + data.Part.cell_x;
        y = data.Part.grid_y * MAX_NUMBER_OF_CELLS + data.Part.cell_y;
    }
References data, and MAX_NUMBER_OF_CELLS.
DiffCell()
bool Cell::DiffCell (const Cell & cell) const inline
    {
        return(data.Part.cell_x != cell.data.Part.cell_x ||
               data.Part.cell_y != cell.data.Part.cell_y);
    }
References cell_x, cell_y, data, and Part.
Referenced by Map::CreatureRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), and Map::PlayerRelocation().
DiffGrid()
bool Cell::DiffGrid (const Cell & cell) const inline
    {
        return(data.Part.grid_x != cell.data.Part.grid_x ||
               data.Part.grid_y != cell.data.Part.grid_y);
    }
References data, grid_x, grid_y, and Part.
Referenced by Map::CreatureRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), and Map::PlayerRelocation().
GetCellCoord()
CellCoord Cell::GetCellCoord () const inline
    {
        return CellCoord(
                   data.Part.grid_x * MAX_NUMBER_OF_CELLS + data.Part.cell_x,
                   data.Part.grid_y * MAX_NUMBER_OF_CELLS + data.Part.cell_y);
    }
References data, and MAX_NUMBER_OF_CELLS.
Referenced by ObjectWorldLoader::Visit(), and ObjectGridLoader::Visit().
GridX()
uint32 Cell::GridX () const inline
{ return data.Part.grid_x; }
References data.
Referenced by Map::AddToGrid(), Map::AddToMap(), Map::EnsureGridLoaded(), GridMap::getMinHeight(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMoveWorldportAck(), Map::SwitchGridContainers(), and Map::Visit().
GridY()
uint32 Cell::GridY () const inline
{ return data.Part.grid_y; }
References data.
Referenced by Map::AddToGrid(), Map::AddToMap(), Map::EnsureGridLoaded(), GridMap::getMinHeight(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMoveWorldportAck(), Map::SwitchGridContainers(), and Map::Visit().
NoCreate()
bool Cell::NoCreate () const inline
{ return data.Part.nocreate; }
References data.
Referenced by Map::Visit().
operator!=()
bool Cell::operator!= (Cell const & cell) const inline
{ return !operator == (cell); }
References operator==().
operator=()
Cell & Cell::operator= (Cell const & cell) inline
    {
        this->data.All = cell.data.All;
        return *this;
    }
References All, and data.
operator==()
bool Cell::operator== (Cell const & cell) const inline
{ return (data.All == cell.data.All); }
References All, and data.
Referenced by operator!=().
SetNoCreate()
void Cell::SetNoCreate () inline
{ data.Part.nocreate = 1; }
References data.
Referenced by WorldObject::GetCreaturesWithEntryInRange(), misc_commandscript::HandleRespawnAllCommand(), WorldSession::HandleTextEmoteOpcode(), Spell::SearchTargets(), AchievementMgr::SendAchievementEarned(), VisitAllObjects(), VisitGridObjects(), and VisitWorldObjects().
Visit() [1/2]
template<class T , class CONTAINER > void Cell::Visit (CellCoord const & standing_cell, TypeContainerVisitor< T, CONTAINER > & visitor, Map & map, float x, float y, float radius) const inline
{
    if (!standing_cell.IsCoordValid())
        return;
    // no jokes here... Actually placing ASSERT() here was good idea, but
    // we had some problems with DynamicObjects, which pass radius = 0.0f (DB issue?)
    // maybe it is better to just return when radius <= 0.0f?
    if (radius <= 0.0f)
    {
        map.Visit(*this, visitor);
        return;
    }
    //lets limit the upper value for search radius
    if (radius > SIZE_OF_GRIDS)
        radius = SIZE_OF_GRIDS;
    //lets calculate object coord offsets from cell borders.
    CellArea area = Cell::CalculateCellArea(x_off, y_off, radius);
    //if radius fits inside standing cell
    if (!area)
    {
        map.Visit(*this, visitor);
        return;
    }
    //visit all cells, found in CalculateCellArea()
    //if radius is known to reach cell area more than 4x4 then we should call optimized VisitCircle
    //currently this technique works with MAX_NUMBER_OF_CELLS 16 and higher, with lower values
    //there are nothing to optimize because SIZE_OF_GRID_CELL is too big...
    if ((area.high_bound.x_coord > (area.low_bound.x_coord + 4)) && (area.high_bound.y_coord > (area.low_bound.y_coord + 4)))
    {
        VisitCircle(visitor, map, area.low_bound, area.high_bound);
        return;
    }
    //ALWAYS visit standing cell first!!! Since we deal with small radiuses
    //it is very essential to call visitor for standing cell firstly...
    map.Visit(*this, visitor);
    // loop the cell range
    for (uint32 x = area.low_bound.x_coord; x <= area.high_bound.x_coord; ++x)
    {
        for (uint32 y = area.low_bound.y_coord; y <= area.high_bound.y_coord; ++y)
        {
            CellCoord cellCoord(x, y);
            //lets skip standing cell since we already visited it
            if (cellCoord != standing_cell)
            {
                Cell r_zone(cellCoord);
                r_zone.data.Part.nocreate = this->data.Part.nocreate;
                map.Visit(r_zone, visitor);
            }
        }
    }
}
References CalculateCellArea(), data, CellArea::high_bound, CoordPair< LIMIT >::IsCoordValid(), CellArea::low_bound, nocreate, Part, SIZE_OF_GRIDS, Map::Visit(), VisitCircle(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Visit() [2/2]
template<class T , class CONTAINER > void Cell::Visit (CellCoord const & standing_cell, TypeContainerVisitor< T, CONTAINER > & visitor, Map & map, WorldObject const & obj, float radius) const inline
{
    //we should increase search radius by object's radius, otherwise
    //we could have problems with huge creatures, which won't attack nearest players etc
    Visit(standing_cell, visitor, map, obj.GetPositionX(), obj.GetPositionY(), radius + obj.GetCombatReach());
}
References WorldObject::GetCombatReach(), Position::GetPositionX(), Position::GetPositionY(), and Visit().
Referenced by Spell::CheckSpellFocus(), WorldObject::GetCreaturesWithEntryInRange(), WorldSession::HandleTextEmoteOpcode(), Visit(), VisitAllObjects(), VisitGridObjects(), and VisitWorldObjects().
VisitAllObjects() [1/2]
template<class T > void Cell::VisitAllObjects (float x, float y, Map * map, T & visitor, float radius, bool dont_load = true) inline static
{
    CellCoord p(Acore::ComputeCellCoord(x, y));
    Cell cell(p);
    if (dont_load)
    {
        cell.SetNoCreate();
    }
    TypeContainerVisitor<T, WorldTypeMapContainer> wnotifier(visitor);
    cell.Visit(p, wnotifier, *map, x, y, radius);
    TypeContainerVisitor<T, GridTypeMapContainer> gnotifier(visitor);
    cell.Visit(p, gnotifier, *map, x, y, radius);
}
References Acore::ComputeCellCoord(), SetNoCreate(), and Visit().
VisitAllObjects() [2/2]
template<class T > void Cell::VisitAllObjects (WorldObject const * obj, T & visitor, float radius, bool dont_load = true) inline static
{
    CellCoord p(Acore::ComputeCellCoord(center_obj->GetPositionX(), center_obj->GetPositionY()));
    Cell cell(p);
    if (dont_load)
    {
        cell.SetNoCreate();
    }
    TypeContainerVisitor<T, WorldTypeMapContainer> wnotifier(visitor);
    cell.Visit(p, wnotifier, *center_obj->GetMap(), *center_obj, radius);
    TypeContainerVisitor<T, GridTypeMapContainer> gnotifier(visitor);
    cell.Visit(p, gnotifier, *center_obj->GetMap(), *center_obj, radius);
}
References Acore::ComputeCellCoord(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), SetNoCreate(), and Visit().
Referenced by boss_ouro::CastGroundRupture(), SmartScript::DoFindClosestFriendlyInRange(), ScriptedAI::DoFindFriendlyCC(), ScriptedAI::DoFindFriendlyMissingBuff(), ScriptedAI::DoSelectLowestHpFriendly(), Spell::EffectForceDeselect(), Spell::EffectSanctuary(), Unit::ExecuteDelayedUnitAINotifyEvent(), Unit::ExecuteDelayedUnitRelocationEvent(), UnitAura::FillTargetMap(), DynObjAura::FillTargetMap(), WorldObject::FindNearestCreature(), SmartScript::GetWorldObjectsInDist(), debug_commandscript::HandleDebugEnterVehicleCommand(), AuraEffect::HandleFeignDeath(), spell_zulfarrak_unlocking::HandleOpenLock(), AuraEffect::HandleRaidProcFromChargeWithValueAuraProc(), spell_vehicle_throw_passenger::HandleScript(), Unit::SelectNearbyNoTotemTarget(), Unit::SelectNearbyTarget(), Creature::SelectNearestTarget(), Creature::SelectNearestTargetInAttackDistance(), Unit::SetContestedPvP(), npc_simon_bunny::npc_simon_bunnyAI::StartGame(), Map::SummonCreature(), GameObject::Update(), TotemAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_naxxramas_misc::boss_naxxramas_miscAI::UpdateAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::UpdateAI(), Unit::UpdateObjectVisibility(), and Player::UpdateVisibilityForPlayer().
VisitCircle()
template<class T , class CONTAINER > void Cell::VisitCircle (TypeContainerVisitor< T, CONTAINER > & visitor, Map & map, CellCoord const & begin_cell, CellCoord const & end_cell) const inline private
{
    //here is an algorithm for 'filling' circum-squared octagon
    uint32 x_shift = (uint32)ceilf((end_cell.x_coord - begin_cell.x_coord) * 0.3f - 0.5f);
    //lets calculate x_start/x_end coords for central strip...
    const uint32 x_start = begin_cell.x_coord + x_shift;
    const uint32 x_end = end_cell.x_coord - x_shift;
    //visit central strip with constant width...
    for (uint32 x = x_start; x <= x_end; ++x)
    {
        for (uint32 y = begin_cell.y_coord; y <= end_cell.y_coord; ++y)
        {
            CellCoord cellCoord(x, y);
            Cell r_zone(cellCoord);
            r_zone.data.Part.nocreate = this->data.Part.nocreate;
            map.Visit(r_zone, visitor);
        }
    }
    //if x_shift == 0 then we have too small cell area, which were already
    //visited at previous step, so just return from procedure...
    if (x_shift == 0)
        return;
    uint32 y_start = end_cell.y_coord;
    uint32 y_end = begin_cell.y_coord;
    //now we are visiting borders of an octagon...
    for (uint32 step = 1; step <= (x_start - begin_cell.x_coord); ++step)
    {
        //each step reduces strip height by 2 cells...
        y_end += 1;
        y_start -= 1;
        for (uint32 y = y_start; y >= y_end; --y)
        {
            //we visit cells symmetrically from both sides, heading from center to sides and from up to bottom
            //e.g. filling 2 trapezoids after filling central cell strip...
            CellCoord cellCoord_left(x_start - step, y);
            Cell r_zone_left(cellCoord_left);
            r_zone_left.data.Part.nocreate = this->data.Part.nocreate;
            map.Visit(r_zone_left, visitor);
            //right trapezoid cell visit
            CellCoord cellCoord_right(x_end + step, y);
            Cell r_zone_right(cellCoord_right);
            r_zone_right.data.Part.nocreate = this->data.Part.nocreate;
            map.Visit(r_zone_right, visitor);
        }
    }
}
References data, nocreate, Part, Map::Visit(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by Visit().
VisitGridObjects() [1/2]
template<class T > void Cell::VisitGridObjects (float x, float y, Map * map, T & visitor, float radius, bool dont_load = true) inline static
{
    CellCoord p(Acore::ComputeCellCoord(x, y));
    Cell cell(p);
    if (dont_load)
    {
        cell.SetNoCreate();
    }
    TypeContainerVisitor<T, GridTypeMapContainer> gnotifier(visitor);
    cell.Visit(p, gnotifier, *map, x, y, radius);
}
References Acore::ComputeCellCoord(), SetNoCreate(), and Visit().
VisitGridObjects() [2/2]
template<class T > void Cell::VisitGridObjects (WorldObject const * obj, T & visitor, float radius, bool dont_load = true) inline static
{
    CellCoord p(Acore::ComputeCellCoord(center_obj->GetPositionX(), center_obj->GetPositionY()));
    Cell cell(p);
    if (dont_load)
    {
        cell.SetNoCreate();
    }
    TypeContainerVisitor<T, GridTypeMapContainer> gnotifier(visitor);
    cell.Visit(p, gnotifier, *center_obj->GetMap(), *center_obj, radius);
}
References Acore::ComputeCellCoord(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), SetNoCreate(), and Visit().
Referenced by Creature::CallAssistance(), Creature::CallForHelp(), spell_gen_cannibalize::CheckIfCorpseNear(), spell_hun_pet_carrion_feeder::CheckIfCorpseNear(), npc_q24545_lich_king::npc_q24545_lich_kingAI::CleanAll(), SmartScript::DoFindFriendlyCC(), SmartScript::DoFindFriendlyMissingBuff(), Creature::DoFleeToGetAssistance(), SmartScript::DoSelectLowestHpFriendly(), SmartScript::DoSelectLowestHpPercentFriendly(), ValithriaDespawner::Execute(), npc_captain_arnath::npc_captain_arnathAI::FindFriendlyCreature(), WorldObject::FindNearestGameObject(), WorldObject::FindNearestGameObjectOfType(), WorldObject::GetCreatureListWithEntryInGrid(), WorldObject::GetDeadCreatureListInGrid(), WorldObject::GetGameObjectListWithEntryInGrid(), ChatHandler::GetNearbyGameObject(), mmaps_commandscript::HandleMmapTestArea(), misc_commandscript::HandleRespawnAllCommand(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustEngagedWith(), LoadHelper(), GameObject::LookupFishingHoleAround(), at_icc_start_frostwing_gauntlet::OnTrigger(), boss_the_lich_king::boss_the_lich_kingAI::Reset(), Spell::SearchTargets(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), and npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointStart().
VisitWorldObjects() [1/2]
template<class T > void Cell::VisitWorldObjects (float x, float y, Map * map, T & visitor, float radius, bool dont_load = true) inline static
{
    CellCoord p(Acore::ComputeCellCoord(x, y));
    Cell cell(p);
    if (dont_load)
    {
        cell.SetNoCreate();
    }
    TypeContainerVisitor<T, WorldTypeMapContainer> wnotifier(visitor);
    cell.Visit(p, wnotifier, *map, x, y, radius);
}
References Acore::ComputeCellCoord(), SetNoCreate(), and Visit().
VisitWorldObjects() [2/2]
template<class T > void Cell::VisitWorldObjects (WorldObject const * obj, T & visitor, float radius, bool dont_load = true) inline static
{
    CellCoord p(Acore::ComputeCellCoord(center_obj->GetPositionX(), center_obj->GetPositionY()));
    Cell cell(p);
    if (dont_load)
    {
        cell.SetNoCreate();
    }
    TypeContainerVisitor<T, WorldTypeMapContainer> wnotifier(visitor);
    cell.Visit(p, wnotifier, *center_obj->GetMap(), *center_obj, radius);
}
References Acore::ComputeCellCoord(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), SetNoCreate(), and Visit().
Referenced by WorldObject::BuildUpdate(), npc_hallows_end_soh::CastFires(), spell_gen_cannibalize::CheckIfCorpseNear(), spell_hun_pet_carrion_feeder::CheckIfCorpseNear(), npc_hallows_end_soh::CompleteQuest(), WorldObject::DestroyForNearbyPlayers(), Spell::EffectForceDeselect(), ScriptedAI::GetPlayerAtMinimumRange(), AuraEffect::HandleAuraDummy(), spell_q11010_q11102_q11023_choose_loc::HandleDummy(), npc_clintar_spirit::npc_clintar_spiritAI::IsSummonedBy(), spell_love_is_in_the_air_romantic_picnic::OnPeriodic(), WorldObject::PlayRadiusMusic(), WorldObject::PlayRadiusSound(), Spell::SearchTargets(), WorldObject::SelectNearestPlayer(), AchievementMgr::SendAchievementEarned(), CreatureTextMgr::SendChatPacket(), WorldObject::SendMessageToSet(), Player::SendMessageToSet(), WorldObject::SendMessageToSetInRange(), Player::SendMessageToSetInRange(), Unit::Talk(), BfCapturePoint::Update(), OPvPCapturePoint::Update(), OPvPCapturePointNA::Update(), GameObject::Update(), npc_brewfest_super_brew_trigger::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), go_flames::go_flamesAI::UpdateAI(), go_heat::go_heatAI::UpdateAI(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), and WorldObject::UpdateObjectVisibility().
Member Data Documentation
All
uint32 Cell::All
Referenced by Cell(), operator=(), and operator==().
cell_x
unsigned Cell::cell_x
Referenced by DiffCell(), and ObjectGridLoader::LoadN().
cell_y
unsigned Cell::cell_y
Referenced by DiffCell(), and ObjectGridLoader::LoadN().
union { ... } Cell::data
Referenced by Cell(), CellX(), CellY(), Compute(), DiffCell(), DiffGrid(), GetCellCoord(), GridX(), GridY(), ObjectGridLoader::LoadN(), NoCreate(), operator=(), operator==(), SetNoCreate(), Map::SwitchGridContainers(), Visit(), and VisitCircle().
grid_x
unsigned Cell::grid_x
Referenced by DiffGrid(), and Map::SwitchGridContainers().
grid_y
unsigned Cell::grid_y
Referenced by DiffGrid(), and Map::SwitchGridContainers().
nocreate
unsigned Cell::nocreate
Referenced by Visit(), and VisitCircle().
struct { ... } Cell::Part
Referenced by DiffCell(), DiffGrid(), ObjectGridLoader::LoadN(), Map::SwitchGridContainers(), Visit(), and VisitCircle().
reserved
unsigned Cell::reserved