AzerothCore: LinkValidator< LinkTags::quest > Struct Reference
LinkValidator< LinkTags::quest > Struct Reference
Static Public Member Functions
static bool IsTextValid (QuestLinkData const &data, std::string_view text)
static bool IsColorValid (QuestLinkData const &, HyperlinkColor c)
Detailed Description
Member Function Documentation
IsColorValid()
static bool LinkValidator< LinkTags::quest >::IsColorValid (QuestLinkData const & , HyperlinkColor c) inline static
    {
        for (uint8 i = 0; i < MAX_QUEST_DIFFICULTY; ++i)
            if (c == QuestDifficultyColors[i])
                return true;
        return false;
    }
References MAX_QUEST_DIFFICULTY, and QuestDifficultyColors.
IsTextValid()
static bool LinkValidator< LinkTags::quest >::IsTextValid (QuestLinkData const & data, std::string_view text) inline static
    {
        if (text.empty())
            return false;
        if (text == data.Quest->GetTitle())
            return true;
        QuestLocale const* locale = sObjectMgr->GetQuestLocale(data.Quest->GetQuestId());
        if (!locale)
            return false;
        for (uint8 i = 0; i < TOTAL_LOCALES; ++i)
        {
            if (i == DEFAULT_LOCALE)
                continue;
            std::string_view name = ObjectMgr::GetLocaleString(locale->Title, i);
            if (!name.empty() && (text == name))
                return true;
        }
        return false;
    }
References DEFAULT_LOCALE, ObjectMgr::GetLocaleString(), Quest::GetQuestId(), Quest::GetTitle(), Acore::Hyperlinks::QuestLinkData::Quest, sObjectMgr, QuestLocale::Title, and TOTAL_LOCALES.