AzerothCore: SACDeactivateEvent Class Reference
SACDeactivateEvent Class Reference
Public Member Functions
SACDeactivateEvent (Creature *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _owner
Detailed Description
Constructor & Destructor Documentation
SACDeactivateEvent()
SACDeactivateEvent::SACDeactivateEvent (Creature * owner) inline
: _owner(owner) {}
Member Function Documentation
Execute()
bool SACDeactivateEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        _owner->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        _owner->SetReactState(REACT_PASSIVE);
        _owner->SetDisplayId(11686);
        return true;
    }
References _owner, REACT_PASSIVE, Creature::SetDisplayId(), Creature::SetReactState(), Unit::SetUnitFlag(), and UNIT_FLAG_NOT_SELECTABLE.
Member Data Documentation
_owner
Creature* SACDeactivateEvent::_owner private
Referenced by Execute().