AzerothCore: npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI Struct Reference
npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI Struct Reference
Public Member Functions
npc_thrall_old_hillsbradAI (Creature *creature)
void DoAction (int32 param) override
void WaypointStart (uint32 waypointId) override
void WaypointReached (uint32 waypointId) override
void MountSelf ()
void UnMountSelf ()
void MovementInform (uint32 type, uint32 point) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void Reset () override
void JustReachedHome () override
void KilledUnit (Unit *) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void JustDied (Unit *killer) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void UpdateEscortAI (uint32 diff) override
void ReorderInstance (uint32 data)
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
InstanceScript * instance
EventMap events
EventMap combatEvents
SummonList summons
bool _mounted
bool _barnWave
bool _churchWave
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_thrall_old_hillsbradAI()
npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::npc_thrall_old_hillsbradAI (Creature * creature) inline
                                                       : npc_escortAI(creature), summons(me)
        {
            instance = creature->GetInstanceScript();
            _barnWave = false;
            _churchWave = false;
        }
References _barnWave, _churchWave, WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DoAction()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            switch (param)
            {
                case ENCOUNTER_PROGRESS_BARRELS:
                    events.ScheduleEvent(EVENT_OPEN_DOORS, 0);
                    events.ScheduleEvent(EVENT_START_WP, 3000);
                    break;
                case ENCOUNTER_PROGRESS_THRALL_ARMORED:
                case ENCOUNTER_PROGRESS_AMBUSHES_1:
                case ENCOUNTER_PROGRESS_SKARLOC_KILLED:
                case ENCOUNTER_PROGRESS_TARREN_MILL:
                    SetEscortPaused(false);
                    break;
                case ENCOUNTER_PROGRESS_TARETHA_MEET:
                    events.ScheduleEvent(EVENT_SUMMON_CHRONO, 0);
                    events.ScheduleEvent(EVENT_THRALL_TALK_2, 6000);
                    events.ScheduleEvent(EVENT_TARETHA_FALL, 11000);
                    events.ScheduleEvent(EVENT_THRALL_TALK_3, 15000);
                    events.ScheduleEvent(EVENT_THRALL_MOVE_DOWN, 17000);
                    break;
                case NPC_TARETHA:
                    events.ScheduleEvent(EVENT_THRALL_FACE_TARETHA, 0);
                    events.ScheduleEvent(EVENT_THRALL_TALK_4, 4000);
                    events.ScheduleEvent(EVENT_TARETHA_TALK_1, 13000);
                    events.ScheduleEvent(EVENT_THRALL_TALK_5, 17000);
                    events.ScheduleEvent(EVENT_SUMMON_EROZION, 17500);
                    events.ScheduleEvent(EVENT_EROZION_TALK_1, 18000);
                    events.ScheduleEvent(EVENT_EROZION_ACTION_1, 24000);
                    events.ScheduleEvent(EVENT_EROZION_TALK_2, 29000);
                    events.ScheduleEvent(EVENT_EROZION_TALK_3, 40000);
                    events.ScheduleEvent(EVENT_EROZION_ACTION_2, 46000);
                    events.ScheduleEvent(EVENT_THRALL_TALK_6, 48000);
                    events.ScheduleEvent(EVENT_THRALL_RUN_AWAY, 51000);
                    events.ScheduleEvent(EVENT_TARETHA_TALK_2, 53000);
                    events.ScheduleEvent(EVENT_EROZION_FLAGS, 56000);
                    break;
            }
        }
References ENCOUNTER_PROGRESS_AMBUSHES_1, ENCOUNTER_PROGRESS_BARRELS, ENCOUNTER_PROGRESS_SKARLOC_KILLED, ENCOUNTER_PROGRESS_TARETHA_MEET, ENCOUNTER_PROGRESS_TARREN_MILL, ENCOUNTER_PROGRESS_THRALL_ARMORED, EVENT_EROZION_ACTION_1, EVENT_EROZION_ACTION_2, EVENT_EROZION_FLAGS, EVENT_EROZION_TALK_1, EVENT_EROZION_TALK_2, EVENT_EROZION_TALK_3, EVENT_OPEN_DOORS, EVENT_START_WP, EVENT_SUMMON_CHRONO, EVENT_SUMMON_EROZION, EVENT_TARETHA_FALL, EVENT_TARETHA_TALK_1, EVENT_TARETHA_TALK_2, EVENT_THRALL_FACE_TARETHA, EVENT_THRALL_MOVE_DOWN, EVENT_THRALL_RUN_AWAY, EVENT_THRALL_TALK_2, EVENT_THRALL_TALK_3, EVENT_THRALL_TALK_4, EVENT_THRALL_TALK_5, EVENT_THRALL_TALK_6, NPC_TARETHA, and npc_escortAI::SetEscortPaused().
JustDied()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustDied (Unit * killer) inline override virtual
Reimplemented from npc_escortAI.
        {
            if (killer && killer == me)
                return;
            summons.DespawnAll();
            Talk(SAY_RANDOM_DIE);
            RemoveEscortState(STATE_ESCORT_ESCORTING);
            instance->SetData(DATA_THRALL_REPOSITION, 3);
            if (instance->GetData(DATA_ATTEMPTS_COUNT) < 20)
                me->CastSpell(me, SPELL_SUMMON_EROZION_IMAGE, true);
            else
                me->SetRespawnTime(DAY);
        }
References Unit::CastSpell(), DATA_ATTEMPTS_COUNT, DATA_THRALL_REPOSITION, DAY, SummonList::DespawnAll(), ZoneScript::GetData(), instance, ScriptedAI::me, npc_escortAI::RemoveEscortState(), SAY_RANDOM_DIE, ZoneScript::SetData(), Creature::SetRespawnTime(), SPELL_SUMMON_EROZION_IMAGE, STATE_ESCORT_ESCORTING, and summons.
JustEngagedWith()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            combatEvents.Reset();
            combatEvents.ScheduleEvent(EVENT_CHECK_HEALTH, 500);
            combatEvents.ScheduleEvent(EVENT_SPELL_SHIELD_BLOCK, 8000);
            combatEvents.ScheduleEvent(EVENT_SPELL_STRIKE, 2000);
            if (roll_chance_i(50))
                Talk(SAY_RANDOM_AGGRO);
            if (me->IsMounted())
            {
                _mounted = true;
                UnMountSelf();
            }
        }
References _mounted, combatEvents, EVENT_CHECK_HEALTH, EVENT_SPELL_SHIELD_BLOCK, EVENT_SPELL_STRIKE, Unit::IsMounted(), ScriptedAI::me, EventMap::Reset(), roll_chance_i(), SAY_RANDOM_AGGRO, EventMap::ScheduleEvent(), and UnMountSelf().
JustReachedHome()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
        {
            if (_barnWave)
            {
                _barnWave = false;
                Talk(SAY_LEAD);
            }
            else if (_churchWave)
            {
                _churchWave = false;
                Talk(SAY_CHURCH_END);
            }
        }
References _barnWave, _churchWave, SAY_CHURCH_END, and SAY_LEAD.
JustSummoned()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (summon->GetEntry() == NPC_INFINITE_SLAYER || summon->GetEntry() == NPC_INFINITE_SABOTEUR || summon->GetEntry() == NPC_INFINITE_DEFILER)
                summon->GetMotionMaster()->MovePoint(10, 2634.25f, 672.01f, 54.445f);
            summons.Summon(summon);
        }
References Object::GetEntry(), Unit::GetMotionMaster(), MotionMaster::MovePoint(), NPC_INFINITE_DEFILER, NPC_INFINITE_SABOTEUR, NPC_INFINITE_SLAYER, SummonList::Summon(), and summons.
KilledUnit()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_RANDOM_KILL);
        }
References SAY_RANDOM_KILL.
MountSelf()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::MountSelf () inline
        {
            me->Mount(SKARLOC_MOUNT_MODEL);
            me->SetSpeed(MOVE_RUN, SPEED_MOUNTED);
        }
References ScriptedAI::me, Unit::Mount(), MOVE_RUN, Unit::SetSpeed(), SKARLOC_MOUNT_MODEL, and SPEED_MOUNTED.
Referenced by MovementInform(), and UpdateAI().
MovementInform()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from npc_escortAI.
        {
            npc_escortAI::MovementInform(type, point);
            if (type == POINT_MOTION_TYPE && point == 0xFFFFFF /*POINT_LAST_POINT*/)
            {
                if (roll_chance_i(30))
                    Talk(SAY_LEAVE_COMBAT);
                if (_mounted)
                    MountSelf();
            }
        }
References _mounted, MountSelf(), npc_escortAI::MovementInform(), POINT_MOTION_TYPE, roll_chance_i(), and SAY_LEAVE_COMBAT.
ReorderInstance()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance (uint32 data) inline
        {
            Start(true, true);
            SetEscortPaused(true);
            SetDespawnAtEnd(false);
            me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
            if (data < ENCOUNTER_PROGRESS_THRALL_ARMORED)
            {
                me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID, 0);
                me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, 0);
                me->SetDisplayId(THRALL_MODEL_UNEQUIPPED);
            }
            else
            {
                me->SetDisplayId(THRALL_MODEL_EQUIPPED);
                me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID, THRALL_WEAPON_ITEM);
                me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, THRALL_SHIELD_ITEM);
            }
            switch (data)
            {
                case ENCOUNTER_PROGRESS_THRALL_ARMORED:
                    SetNextWaypoint(11, false);
                    break;
                case ENCOUNTER_PROGRESS_AMBUSHES_1:
                    SetNextWaypoint(27, false);
                    break;
                case ENCOUNTER_PROGRESS_SKARLOC_KILLED:
                    if (Creature* mount = me->SummonCreature(NPC_SKARLOC_MOUNT, 2049.12f, 252.31f, 62.855f, me->GetOrientation(), TEMPSUMMON_MANUAL_DESPAWN))
                    {
                        mount->SetImmuneToNPC(true);
                        mount->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    }
                    SetNextWaypoint(30, false);
                    break;
                case ENCOUNTER_PROGRESS_TARREN_MILL:
                    SetNextWaypoint(61, false);
                    break;
                case ENCOUNTER_PROGRESS_TARETHA_MEET:
                    SetNextWaypoint(95, false);
                    if (Creature* Taretha = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_TARETHA_GUID)))
                        Taretha->SetStandState(UNIT_STAND_STATE_STAND);
                    break;
            }
        }
References DATA_TARETHA_GUID, ENCOUNTER_PROGRESS_AMBUSHES_1, ENCOUNTER_PROGRESS_SKARLOC_KILLED, ENCOUNTER_PROGRESS_TARETHA_MEET, ENCOUNTER_PROGRESS_TARREN_MILL, ENCOUNTER_PROGRESS_THRALL_ARMORED, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Position::GetOrientation(), instance, ScriptedAI::me, NPC_SKARLOC_MOUNT, npc_escortAI::SetDespawnAtEnd(), Creature::SetDisplayId(), npc_escortAI::SetEscortPaused(), npc_escortAI::SetNextWaypoint(), Unit::SetNpcFlag(), Unit::SetUInt32Value(), npc_escortAI::Start(), WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, THRALL_MODEL_EQUIPPED, THRALL_MODEL_UNEQUIPPED, THRALL_SHIELD_ITEM, THRALL_WEAPON_ITEM, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, UNIT_STAND_STATE_STAND, and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by Reset().
Reset()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _mounted = false;
            events.Reset();
            combatEvents.Reset();
            summons.DespawnAll();
            me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
            instance->SetData(DATA_THRALL_REPOSITION, 1);
            uint32 data = instance->GetData(DATA_ESCORT_PROGRESS);
            if (data >= ENCOUNTER_PROGRESS_THRALL_ARMORED)
                ReorderInstance(data);
        }
References _mounted, combatEvents, DATA_ESCORT_PROGRESS, DATA_THRALL_REPOSITION, SummonList::DespawnAll(), ENCOUNTER_PROGRESS_THRALL_ARMORED, ZoneScript::GetData(), instance, ScriptedAI::me, ReorderInstance(), EventMap::Reset(), ZoneScript::SetData(), Unit::SetNpcFlag(), summons, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAG_QUESTGIVER.
SummonedCreatureDespawn()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
{ summons.Despawn(summon); }
References SummonList::Despawn(), and summons.
SummonedCreatureDies()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
{ summons.Despawn(summon); }
References SummonList::Despawn(), and summons.
UnMountSelf()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UnMountSelf () inline
        {
            me->Dismount();
            me->SetSpeed(MOVE_RUN, SPEED_RUNNING);
        }
References Unit::Dismount(), ScriptedAI::me, MOVE_RUN, Unit::SetSpeed(), and SPEED_RUNNING.
Referenced by JustEngagedWith(), and WaypointReached().
UpdateAI()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from npc_escortAI.
        {
            npc_escortAI::UpdateAI(diff);
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_OPEN_DOORS:
                    if (GameObject* doors = me->FindNearestGameObject(GO_PRISON_DOOR, 10.0f))
                        doors->SetGoState(GO_STATE_ACTIVE);
                    me->SummonCreature(NPC_DURNHOLDE_SENTRY, 2142.372f, 174.2907f, 66.30494f, 2.5656f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    me->SummonCreature(NPC_DURNHOLDE_SENTRY, 2138.178f, 168.6046f, 66.30494f, 2.4783f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    me->SummonCreature(NPC_DURNHOLDE_VETERAN, 2140.1458f, 169.23643f, 66.30494f, 2.4958f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    me->SummonCreature(NPC_DURNHOLDE_VETERAN, 2107.9377f, 192.07530f, 66.30494f, 2.5481f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    me->SummonCreature(NPC_DURNHOLDE_MAGE, 2142.3633f, 172.42600f, 66.30494f, 2.5481f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    me->SummonCreature(NPC_DURNHOLDE_MAGE, 2109.8518f, 195.14030f, 66.30493f, 2.4260f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    me->SummonCreature(NPC_DURNHOLDE_MAGE, 2108.4856f, 189.93457f, 66.30494f, 2.6878f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    break;
                case EVENT_START_WP:
                    Start(true, true);
                    SetDespawnAtEnd(false);
                    break;
                case EVENT_SET_FACING:
                    if (Creature* armorer = me->FindNearestCreature(NPC_DURNHOLDE_ARMORER, 30.0f))
                    {
                        armorer->GetMotionMaster()->Clear();
                        armorer->GetMotionMaster()->MoveIdle();
                        armorer->SetFacingToObject(me);
                        me->SetFacingToObject(armorer);
                    }
                    break;
                case EVENT_ARMORER_SAY:
                    if (Creature* armorer = me->FindNearestCreature(NPC_DURNHOLDE_ARMORER, 30.0f))
                    {
                        armorer->AI()->Talk(SAY_ARMORER_THRALL);
                    }
                    break;
                case EVENT_THRALL_EMOTE:
                    me->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
                    break;
                case EVENT_KILL_ARMORER:
                    me->HandleEmoteCommand(EMOTE_ONESHOT_ATTACK_UNARMED);
                    if (Creature* armorer = me->FindNearestCreature(NPC_DURNHOLDE_ARMORER, 30.0f))
                    {
                        DoCast(armorer, SPELL_KNOCKOUT_ARMORER, true);
                        armorer->SetStandState(UNIT_STAND_STATE_DEAD);
                    }
                    break;
                case EVENT_TALK_KILL_ARMORER:
                    Talk(SAY_KILL_ARMORER);
                    break;
                case EVENT_DRESSING_KNEEL:
                    me->SetFacingTo(2.61f);
                    Talk(SAY_ARMORY);
                    me->SetStandState(UNIT_STAND_STATE_KNEEL);
                    break;
                case EVENT_DRESSING_ARMOR:
                    me->SetDisplayId(THRALL_MODEL_EQUIPPED);
                    break;
                case EVENT_DRESSING_STAND:
                    me->SetStandState(UNIT_STAND_STATE_STAND);
                    break;
                case EVENT_DRESSING_AXE:
                    me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID, THRALL_WEAPON_ITEM);
                    break;
                case EVENT_DRESSING_SHIELD:
                    me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, THRALL_SHIELD_ITEM);
                    break;
                case EVENT_DRESSING_TALK:
                    instance->SetData(DATA_ESCORT_PROGRESS, ENCOUNTER_PROGRESS_THRALL_ARMORED);
                    DoCastSelf(SPELL_SALVATION);
                    me->SetFacingTo(5.6897f);
                    Talk(SAY_GO_ARMORED);
                    if (Creature* sentry = me->SummonCreature(NPC_DURNHOLDE_SENTRY, 2185.916f, 140.38835f, 88.299866f, 5.9238f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS))
                    {
                        sentry->SetWalk(true);
                        sentry->GetMotionMaster()->MovePoint(0, 2191.9712f, 138.11394f, 88.2125f);
                    }
                    if (Creature* warden = me->SummonCreature(NPC_DURNHOLDE_WARDEN, 2188.5586f, 138.88553f, 88.299866f, 1.6031f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS))
                    {
                        warden->SetWalk(true);
                        warden->GetMotionMaster()->MovePoint(0, 2188.5068f, 140.48346f, 88.21251f);
                    }
                    if (Creature* veteran = me->SummonCreature(NPC_DURNHOLDE_VETERAN, 2186.9856f, 142.199f, 88.299866f, 5.9049f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS))
                    {
                        veteran->SetWalk(true);
                        veteran->GetMotionMaster()->MovePoint(0, 2190.48f, 140.81056f, 88.21251f);
                    }
                    if (Creature* mage = me->SummonCreature(NPC_DURNHOLDE_MAGE, 2189.7336f, 140.64551f, 88.299866f, 3.9532f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS))
                    {
                        mage->SetWalk(true);
                        mage->GetMotionMaster()->MovePoint(0, 2187.8035f, 138.61118f, 88.21251f);
                    }
                    break;
                case EVENT_ENTER_MOUNT:
                    MountSelf();
                    if (Creature* mount = me->FindNearestCreature(NPC_SKARLOC_MOUNT, 10.0f))
                    {
                        me->SetFacingTo(mount->GetOrientation());
                        mount->DespawnOrUnsummon();
                    }
                    break;
                case EVENT_TALK_START_RIDE:
                    Talk(SAY_MOUNTS_UP);
                    break;
                case EVENT_LOOK_1:
                    me->SetFacingTo(5.0090f);
                    me->SetImmuneToNPC(true);
                    break;
                case EVENT_MOVE_AROUND:
                    me->GetMotionMaster()->MovePoint(0, 2477.146f, 695.041f, 55.801f);
                    break;
                case EVENT_LOOK_2:
                    me->SetFacingTo(2.0071f);
                    break;
                case EVENT_SUMMON_GUARDS:
                    SetRun(true);
                    me->SummonCreature(NPC_TM_PROTECTOR, 2501.5708f, 699.38086f, 55.64138f, 3.8571f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    me->SummonCreature(NPC_TM_LOOKOUT, 2500.7002f, 698.26746f, 55.618248f, 3.7350f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    if (Creature* guardsman = me->SummonCreature(NPC_TM_GUARDSMAN, 2500.0908f, 699.9389f, 55.629555f, 4.2935f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS))
                    {
                        guardsman->CastSpell(guardsman, SPELL_DUMMY_AURA, true);
                    }
                    me->SummonCreature(NPC_TM_GUARDSMAN, 2499.0579f, 698.99725f, 55.611156f, 4.5727f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    summons.DoAction(ACTION_SET_IMMUNE_FLAG);
                    break;
                case EVENT_LOOK_3:
                    me->SetFacingTo(0.3490f);
                    break;
                case EVENT_SUMMON_TALK1:
                    if (Creature* summon = summons.GetCreatureWithEntry(NPC_TM_LOOKOUT))
                        summon->AI()->Talk(SAY_LOOKOUT_SAW);
                    me->SetFacingTo(0.4363f);
                    break;
                case EVENT_LOOK_4:
                    me->SetFacingTo(4.7510f);
                    me->HandleEmoteCommand(EMOTE_ONESHOT_NO);
                    Talk(SAY_EMOTE_HORSE_2);
                    break;
                case EVENT_SUMMON_TALK2:
                    me->SetFacingTo(0.4363f);
                    if (Creature* summon = summons.GetCreatureWithEntry(NPC_TM_LOOKOUT))
                        summon->AI()->Talk(SAY_LOOKOUT_GO);
                    me->SetImmuneToNPC(true);
                    break;
                case EVENT_GUARDS_MOVING:
                    me->SetImmuneToNPC(false);
                    summons.DoAction(ACTION_REMOVE_IMMUNE_FLAG);
                    _barnWave = true;
                    break;
                case EVENT_LOOK_5:
                    me->SetFacingTo(0.4886f);
                    Talk(SAY_ENTER_CHURCH);
                    break;
                case EVENT_SUMMON_GUARDS_2:
                    me->SummonCreature(NPC_TM_PROTECTOR, 2630.75f, 664.80f, 54.28f, 4.37f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    me->SummonCreature(NPC_TM_LOOKOUT, 2632.20f, 661.98f, 54.30f, 4.37f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    me->SummonCreature(NPC_TM_GUARDSMAN, 2630.02f, 662.75f, 54.28f, 4.37f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    me->SummonCreature(NPC_TM_GUARDSMAN, 2632.86f, 664.05f, 54.31f, 4.37f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS);
                    _churchWave = true;
                    break;
                case EVENT_SUMMON_TALK3:
                    if (Creature* summon = summons.GetCreatureWithEntry(NPC_TM_LOOKOUT))
                        summon->AI()->Talk(SAY_LOOKOUT_CHURCH);
                    break;
                case EVENT_THRALL_TALK:
                    Talk(SAY_MEET_TARETHA);
                    me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    break;
                case EVENT_SUMMON_CHRONO:
                    if (Creature* epoch = me->SummonCreature(NPC_EPOCH_HUNTER, 2640.49f, 696.15f, 64.31f, 4.51f, TEMPSUMMON_MANUAL_DESPAWN))
                    {
                        epoch->SetImmuneToAll(true);
                        epoch->AI()->Talk(SAY_EPOCH_ENTER1);
                    }
                    break;
                case EVENT_THRALL_TALK_2:
                    me->SetFacingTo(2.60f);
                    Talk(SAY_EPOCH_WONDER);
                    break;
                case EVENT_TARETHA_FALL:
                    if (Creature* epoch = summons.GetCreatureWithEntry(NPC_EPOCH_HUNTER))
                        epoch->AI()->Talk(SAY_EPOCH_ENTER2);
                    if (Creature* Taretha = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_TARETHA_GUID)))
                    {
                        Taretha->CastSpell(Taretha, SPELL_SHADOW_SPIKE);
                        Taretha->SetStandState(UNIT_STAND_STATE_DEAD);
                    }
                    break;
                case EVENT_THRALL_TALK_3:
                    if (Creature* Taretha = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_TARETHA_GUID)))
                    {
                        me->SetFacingToObject(Taretha);
                    }
                    Talk(SAY_EPOCH_KILL_TARETHA);
                    break;
                case EVENT_THRALL_MOVE_DOWN:
                    SetEscortPaused(false);
                    break;
                case EVENT_EPOCH_INTRO:
                    if (Creature* epoch = summons.GetCreatureWithEntry(NPC_EPOCH_HUNTER))
                    {
                        me->SetFacingToObject(epoch);
                        epoch->SetFacingToObject(me);
                        epoch->AI()->Talk(SAY_EPOCH_ENTER3);
                    }
                    break;
                case EVENT_SUMMON_INFINITES:
                    me->SummonCreature(NPC_EPOCH_LOOKOUT, 2647.57f, 701.17f, 56.215f, 4.3f, TEMPSUMMON_MANUAL_DESPAWN);
                    me->SummonCreature(NPC_EPOCH_GUARDSMAN, 2629.46f, 704.76f, 56.286f, 4.98f, TEMPSUMMON_MANUAL_DESPAWN);
                    me->SummonCreature(NPC_EPOCH_PROTECTOR, 2640.14f, 709.44f, 56.135f, 4.70f, TEMPSUMMON_MANUAL_DESPAWN);
                    summons.DoAction(ACTION_SET_IMMUNE_FLAG);
                    summons.DoAction(ACTION_MOVE);
                    break;
                case EVENT_TRANSFORM:
                    summons.DoAction(ACTION_TRANSFORM);
                    summons.DoAction(ACTION_SET_IMMUNE_FLAG);
                    break;
                case EVENT_START_WAVE_1:
                    events.ScheduleEvent(EVENT_CHECK_WAVE_1, 500);
                    summons.DoAction(ACTION_REMOVE_IMMUNE_FLAG);
                    summons.DoAction(ACTION_START_COMBAT);
                    break;
                case EVENT_CHECK_WAVE_1:
                    if (summons.size() == 1)
                    {
                        me->SummonCreature(NPC_INFINITE_SABOTEUR, 2599.57f, 683.72f, 55.975f, 0.05f, TEMPSUMMON_MANUAL_DESPAWN);
                        me->SummonCreature(NPC_INFINITE_SLAYER, 2599.57f, 677.0f, 55.975f, 0.05f, TEMPSUMMON_MANUAL_DESPAWN);
                        me->SummonCreature(NPC_INFINITE_DEFILER, 2592.57f, 680.0f, 55.975f, 0.05f, TEMPSUMMON_MANUAL_DESPAWN);
                        summons.DoAction(ACTION_START_COMBAT);
                        events.ScheduleEvent(EVENT_CHECK_WAVE_2, 500);
                        break;
                    }
                    events.ScheduleEvent(EVENT_CHECK_WAVE_1, 500);
                    break;
                case EVENT_CHECK_WAVE_2:
                    if (summons.size() == 1)
                    {
                        me->SummonCreature(NPC_INFINITE_SLAYER, 2642.62f, 701.43f, 55.965f, 4.46f, TEMPSUMMON_MANUAL_DESPAWN);
                        me->SummonCreature(NPC_INFINITE_SLAYER, 2638.62f, 701.43f, 55.965f, 4.46f, TEMPSUMMON_MANUAL_DESPAWN);
                        me->SummonCreature(NPC_INFINITE_SABOTEUR, 2638.62f, 705.43f, 55.965f, 4.46f, TEMPSUMMON_MANUAL_DESPAWN);
                        me->SummonCreature(NPC_INFINITE_DEFILER, 2642.62f, 705.43f, 55.965f, 4.46f, TEMPSUMMON_MANUAL_DESPAWN);
                        summons.DoAction(ACTION_START_COMBAT);
                        events.ScheduleEvent(EVENT_CHECK_WAVE_3, 500);
                        break;
                    }
                    events.ScheduleEvent(EVENT_CHECK_WAVE_2, 500);
                    break;
                case EVENT_CHECK_WAVE_3:
                    if (summons.size() == 1)
                    {
                        me->SetHomePosition(2634.79f, 672.964f, 54.8577f, 1.33f);
                        me->GetMotionMaster()->MoveTargetedHome();
                        events.ScheduleEvent(EVENT_CALL_EPOCH, 8000);
                        break;
                    }
                    events.ScheduleEvent(EVENT_CHECK_WAVE_3, 500);
                    break;
                case EVENT_CALL_EPOCH:
                    if (Creature* epoch = summons.GetCreatureWithEntry(NPC_EPOCH_HUNTER))
                    {
                        epoch->SetImmuneToAll(false);
                        epoch->GetMotionMaster()->MovePoint(0, *me, false, true);
                    }
                    break;
                case EVENT_THRALL_FACE_TARETHA:
                    {
                        Map::PlayerList const& players = me->GetMap()->GetPlayers();
                        if (!players.IsEmpty())
                            for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                                if (Player* player = itr->GetSource())
                                    player->KilledMonsterCredit(20156);
                        if (Creature* Taretha = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_TARETHA_GUID)))
{
                            me->SetFacingToObject(Taretha);
                        }
                        me->SetImmuneToNPC(true);
                        break;
                    }
                case EVENT_THRALL_TALK_4:
                    me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_TALK);
                    Talk(SAY_GREET_TARETHA);
                    break;
                case EVENT_TARETHA_TALK_1:
                    me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_NONE);
                    if (Creature* Taretha = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_TARETHA_GUID)))
                    {
                        Taretha->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                        Taretha->AI()->Talk(SAY_TARETHA_TALK1);
                    }
                    break;
                case EVENT_THRALL_TALK_5:
                    Talk(SAY_CHAT_TARETHA1);
                    break;
                case EVENT_SUMMON_EROZION:
                    if (Creature* erozion = me->SummonCreature(NPC_EROZION, 2646.31f, 680.01f, 55.36f, 3.76f, TEMPSUMMON_MANUAL_DESPAWN))
                        erozion->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
                    break;
                case EVENT_EROZION_TALK_1:
                    if (Creature* erozion = summons.GetCreatureWithEntry(NPC_EROZION))
                    {
                        erozion->CastSpell(erozion, SPELL_TELEPORT, true);
                        erozion->AI()->Talk(SAY_EROZION_1);
                    }
                    break;
                case EVENT_EROZION_ACTION_1:
                    if (Creature* erozion = summons.GetCreatureWithEntry(NPC_EROZION))
                        erozion->CastSpell(erozion, SPELL_MEMORY_WIPE, false);
                    break;
                case EVENT_EROZION_TALK_2:
                    if (Creature* erozion = summons.GetCreatureWithEntry(NPC_EROZION))
                        erozion->AI()->Talk(SAY_EROZION_2);
                    break;
                case EVENT_EROZION_TALK_3:
                    if (Creature* erozion = summons.GetCreatureWithEntry(NPC_EROZION))
                        erozion->AI()->Talk(SAY_EROZION_3);
                    break;
                case EVENT_EROZION_ACTION_2:
                    if (Creature* erozion = summons.GetCreatureWithEntry(NPC_EROZION))
                        erozion->CastSpell(erozion, SPELL_MEMORY_WIPE_RESUME, false);
                    break;
                case EVENT_THRALL_TALK_6:
                    Talk(SAY_EVENT_COMPLETE);
                    break;
                case EVENT_THRALL_RUN_AWAY:
                    me->SetImmuneToAll(true);
                    me->SetReactState(REACT_PASSIVE);
                    SetEscortPaused(false);
                    break;
                case EVENT_TARETHA_TALK_2:
                    if (Creature* Taretha = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_TARETHA_GUID)))
                    {
                        Taretha->SetFacingToObject(me);
                        Taretha->AI()->Talk(SAY_TARETHA_TALK2);
                    }
                    break;
                case EVENT_EROZION_FLAGS:
                    if (Creature* erozion = summons.GetCreatureWithEntry(NPC_EROZION))
                        erozion->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                    break;
            }
        }
References _barnWave, _churchWave, ACTION_MOVE, ACTION_REMOVE_IMMUNE_FLAG, ACTION_SET_IMMUNE_FLAG, ACTION_START_COMBAT, ACTION_TRANSFORM, MapRefMgr::begin(), Unit::CastSpell(), DATA_ESCORT_PROGRESS, DATA_TARETHA_GUID, SummonList::DoAction(), UnitAI::DoCast(), UnitAI::DoCastSelf(), EMOTE_ONESHOT_ATTACK_UNARMED, EMOTE_ONESHOT_EXCLAMATION, EMOTE_ONESHOT_NO, EMOTE_ONESHOT_TALK, EMOTE_STATE_NONE, EMOTE_STATE_TALK, ENCOUNTER_PROGRESS_THRALL_ARMORED, MapRefMgr::end(), EVENT_ARMORER_SAY, EVENT_CALL_EPOCH, EVENT_CHECK_WAVE_1, EVENT_CHECK_WAVE_2, EVENT_CHECK_WAVE_3, EVENT_DRESSING_ARMOR, EVENT_DRESSING_AXE, EVENT_DRESSING_KNEEL, EVENT_DRESSING_SHIELD, EVENT_DRESSING_STAND, EVENT_DRESSING_TALK, EVENT_ENTER_MOUNT, EVENT_EPOCH_INTRO, EVENT_EROZION_ACTION_1, EVENT_EROZION_ACTION_2, EVENT_EROZION_FLAGS, EVENT_EROZION_TALK_1, EVENT_EROZION_TALK_2, EVENT_EROZION_TALK_3, EVENT_GUARDS_MOVING, EVENT_KILL_ARMORER, EVENT_LOOK_1, EVENT_LOOK_2, EVENT_LOOK_3, EVENT_LOOK_4, EVENT_LOOK_5, EVENT_MOVE_AROUND, EVENT_OPEN_DOORS, EVENT_SET_FACING, EVENT_START_WAVE_1, EVENT_START_WP, EVENT_SUMMON_CHRONO, EVENT_SUMMON_EROZION, EVENT_SUMMON_GUARDS, EVENT_SUMMON_GUARDS_2, EVENT_SUMMON_INFINITES, EVENT_SUMMON_TALK1, EVENT_SUMMON_TALK2, EVENT_SUMMON_TALK3, EVENT_TALK_KILL_ARMORER, EVENT_TALK_START_RIDE, EVENT_TARETHA_FALL, EVENT_TARETHA_TALK_1, EVENT_TARETHA_TALK_2, EVENT_THRALL_EMOTE, EVENT_THRALL_FACE_TARETHA, EVENT_THRALL_MOVE_DOWN, EVENT_THRALL_RUN_AWAY, EVENT_THRALL_TALK, EVENT_THRALL_TALK_2, EVENT_THRALL_TALK_3, EVENT_THRALL_TALK_4, EVENT_THRALL_TALK_5, EVENT_THRALL_TALK_6, EVENT_TRANSFORM, WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), ObjectAccessor::GetCreature(), SummonList::GetCreatureWithEntry(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetMotionMaster(), Map::GetPlayers(), GO_PRISON_DOOR, GO_STATE_ACTIVE, Unit::HandleEmoteCommand(), IN_MILLISECONDS, instance, LinkedListHead::IsEmpty(), ScriptedAI::me, MountSelf(), MotionMaster::MovePoint(), MotionMaster::MoveTargetedHome(), NPC_DURNHOLDE_ARMORER, NPC_DURNHOLDE_MAGE, NPC_DURNHOLDE_SENTRY, NPC_DURNHOLDE_VETERAN, NPC_DURNHOLDE_WARDEN, NPC_EPOCH_GUARDSMAN, NPC_EPOCH_HUNTER, NPC_EPOCH_LOOKOUT, NPC_EPOCH_PROTECTOR, NPC_EROZION, NPC_INFINITE_DEFILER, NPC_INFINITE_SABOTEUR, NPC_INFINITE_SLAYER, NPC_SKARLOC_MOUNT, NPC_TM_GUARDSMAN, NPC_TM_LOOKOUT, NPC_TM_PROTECTOR, REACT_PASSIVE, SAY_ARMORER_THRALL, SAY_ARMORY, SAY_CHAT_TARETHA1, SAY_EMOTE_HORSE_2, SAY_ENTER_CHURCH, SAY_EPOCH_ENTER1, SAY_EPOCH_ENTER2, SAY_EPOCH_ENTER3, SAY_EPOCH_KILL_TARETHA, SAY_EPOCH_WONDER, SAY_EROZION_1, SAY_EROZION_2, SAY_EROZION_3, SAY_EVENT_COMPLETE, SAY_GO_ARMORED, SAY_GREET_TARETHA, SAY_KILL_ARMORER, SAY_LOOKOUT_CHURCH, SAY_LOOKOUT_GO, SAY_LOOKOUT_SAW, SAY_MEET_TARETHA, SAY_MOUNTS_UP, SAY_TARETHA_TALK1, SAY_TARETHA_TALK2, ZoneScript::SetData(), npc_escortAI::SetDespawnAtEnd(), Creature::SetDisplayId(), npc_escortAI::SetEscortPaused(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Creature::SetHomePosition(), Unit::SetImmuneToAll(), Unit::SetImmuneToNPC(), Unit::SetNpcFlag(), Creature::SetReactState(), npc_escortAI::SetRun(), Unit::SetStandState(), Unit::SetUInt32Value(), SummonList::size(), SPELL_DUMMY_AURA, SPELL_KNOCKOUT_ARMORER, SPELL_MEMORY_WIPE, SPELL_MEMORY_WIPE_RESUME, SPELL_SALVATION, SPELL_SHADOW_SPIKE, SPELL_TELEPORT, npc_escortAI::Start(), WorldObject::SummonCreature(), summons, TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_MANUAL_DESPAWN, THRALL_MODEL_EQUIPPED, THRALL_SHIELD_ITEM, THRALL_WEAPON_ITEM, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAG_QUESTGIVER, UNIT_STAND_STATE_DEAD, UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_STAND, UNIT_VIRTUAL_ITEM_SLOT_ID, and npc_escortAI::UpdateAI().
UpdateEscortAI()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
        {
            if (!UpdateVictim())
                return;
            combatEvents.Update(diff);
            switch (combatEvents.ExecuteEvent())
            {
                case EVENT_CHECK_HEALTH:
                    if (me->HealthBelowPct(20))
                    {
                        Talk(SAY_RANDOM_LOW_HP);
                        break;
                    }
                    events.ScheduleEvent(EVENT_CHECK_HEALTH, 500);
                    break;
                case EVENT_SPELL_STRIKE:
                    me->CastSpell(me->GetVictim(), SPELL_STRIKE, false);
                    events.ScheduleEvent(EVENT_SPELL_STRIKE, 6000);
                    break;
                case EVENT_SPELL_SHIELD_BLOCK:
                    me->CastSpell(me, SPELL_SHIELD_BLOCK, false);
                    events.ScheduleEvent(EVENT_SPELL_SHIELD_BLOCK, 6000);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::CastSpell(), combatEvents, UnitAI::DoMeleeAttackIfReady(), EVENT_CHECK_HEALTH, EVENT_SPELL_SHIELD_BLOCK, EVENT_SPELL_STRIKE, EventMap::ExecuteEvent(), Unit::GetVictim(), Unit::HealthBelowPct(), ScriptedAI::me, SAY_RANDOM_LOW_HP, SPELL_SHIELD_BLOCK, SPELL_STRIKE, EventMap::Update(), and CreatureAI::UpdateVictim().
WaypointReached()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
        {
            switch (waypointId)
            {
                case 0:
                    Talk(SAY_START_EVENT_PART1);
                    break;
                case 8:
                    events.ScheduleEvent(EVENT_SET_FACING, 500);
                    events.ScheduleEvent(EVENT_ARMORER_SAY, 700);
                    events.ScheduleEvent(EVENT_THRALL_EMOTE, 1300);
                    break;
                case 9:
                    SetRun(false);
                    events.ScheduleEvent(EVENT_KILL_ARMORER, 500);
                    events.ScheduleEvent(EVENT_TALK_KILL_ARMORER, 3000);
                    break;
                case 10:
                    SetRun(true);
                    events.ScheduleEvent(EVENT_DRESSING_KNEEL, 500);
                    events.ScheduleEvent(EVENT_DRESSING_ARMOR, 3000);
                    events.ScheduleEvent(EVENT_DRESSING_STAND, 4000);
                    events.ScheduleEvent(EVENT_DRESSING_AXE, 7000);
                    events.ScheduleEvent(EVENT_DRESSING_SHIELD, 9000);
                    events.ScheduleEvent(EVENT_DRESSING_TALK, 12000);
                    break;
                case 18:
                    if (Creature* warden = me->SummonCreature(NPC_DURNHOLDE_WARDEN, 2149.4634f, 104.97559f, 73.632385f, 1.9065f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS))
                    {
                        warden->SetWalk(true);
                        warden->GetMotionMaster()->MovePoint(0, 2144.9893f, 117.81233f, 75.98518f);
                    }
                    if (Creature* veteran = me->SummonCreature(NPC_DURNHOLDE_VETERAN, 2147.3281f, 106.72353f, 74.34447f, 1.6904f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS))
                    {
                        veteran->SetWalk(true);
                        veteran->GetMotionMaster()->MovePoint(0, 2145.2092f, 124.361f, 76.13655f);
                    }
                    if (Creature* veteran = me->SummonCreature(NPC_DURNHOLDE_VETERAN, 2149.212f, 107.20052f, 74.15676f, 1.9887f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS))
                    {
                        veteran->SetWalk(true);
                        veteran->GetMotionMaster()->MovePoint(0, 2143.7898f, 119.41281f, 75.96626f);
                    }
                    if (Creature* mage = me->SummonCreature(NPC_DURNHOLDE_MAGE, 2147.624f, 104.61046f, 73.909294f, 1.6186f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30 * IN_MILLISECONDS))
                    {
                        mage->SetWalk(true);
                        mage->GetMotionMaster()->MovePoint(0, 2146.975f, 118.05078f, 76.098465f);
                    }
                    break;
                case 27:
                    instance->SetData(DATA_ESCORT_PROGRESS, ENCOUNTER_PROGRESS_AMBUSHES_1);
                    break;
                case 28:
                    me->SummonCreature(NPC_CAPTAIN_SKARLOC, 1995.78f, 277.46f, 66.64f, 0.74f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2 * MINUTE * IN_MILLISECONDS);
                    break;
                case 29:
                    SetEscortPaused(true);
                    Talk(SAY_SKARLOC_MEET);
                    break;
                case 30:
                    events.ScheduleEvent(EVENT_ENTER_MOUNT, 3000);
                    events.ScheduleEvent(EVENT_TALK_START_RIDE, 7000);
                    break;
                case 59:
                    instance->SetData(DATA_ESCORT_PROGRESS, ENCOUNTER_PROGRESS_TARREN_MILL);
                    if (Creature* mount = me->SummonCreature(NPC_SKARLOC_MOUNT, 2488.64f, 625.77f, 58.26f, 4.71f, TEMPSUMMON_TIMED_DESPAWN, 7000))
                    {
                        mount->SetImmuneToNPC(true);
                        mount->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    }
                    UnMountSelf();
                    _mounted = false;
                    SetRun(false);
                    me->SetFacingTo(6.0388f);
                    break;
                case 60:
                    me->HandleEmoteCommand(EMOTE_ONESHOT_CHEER);
                    if (Creature* horse = me->FindNearestCreature(NPC_SKARLOC_MOUNT, 10.0f))
                    {
                        horse->GetMotionMaster()->MovePoint(0, 2501.15f, 572.14f, 54.13f);
                        horse->DespawnOrUnsummon(30 * IN_MILLISECONDS);
                    }
                    Talk(SAY_EMOTE_HORSE);
                    SetEscortPaused(true);
                    SetRun(true);
                    me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    me->SetFacingTo(4.1364f);
                    break;
                case 64:
                    SetRun(false);
                    break;
                case 67:
                    events.ScheduleEvent(EVENT_LOOK_1, 1200);
                    events.ScheduleEvent(EVENT_MOVE_AROUND, 3500);
                    events.ScheduleEvent(EVENT_LOOK_2, 5000);
                    events.ScheduleEvent(EVENT_SUMMON_GUARDS, 5100);
                    events.ScheduleEvent(EVENT_LOOK_3, 7000);
                    events.ScheduleEvent(EVENT_SUMMON_TALK1, 12000);
                    events.ScheduleEvent(EVENT_LOOK_4, 17000);
                    events.ScheduleEvent(EVENT_SUMMON_TALK2, 19000);
                    events.ScheduleEvent(EVENT_GUARDS_MOVING, 21000);
                    break;
                case 82:
                    events.ScheduleEvent(EVENT_LOOK_5, 500);
                    events.ScheduleEvent(EVENT_SUMMON_GUARDS_2, 1000);
                    events.ScheduleEvent(EVENT_SUMMON_TALK3, 1500);
                    break;
                case 91:
                    me->SummonCreature(NPC_TM_PROTECTOR, 2652.71f, 660.31f, 61.93f, 1.67f, TEMPSUMMON_MANUAL_DESPAWN);
                    me->SummonCreature(NPC_TM_LOOKOUT, 2648.96f, 662.59f, 61.93f, 0.79f, TEMPSUMMON_MANUAL_DESPAWN);
                    me->SummonCreature(NPC_TM_GUARDSMAN, 2657.36f, 662.34f, 61.93f, 2.68f, TEMPSUMMON_MANUAL_DESPAWN);
                    me->SummonCreature(NPC_TM_GUARDSMAN, 2656.39f, 659.77f, 61.93f, 2.61f, TEMPSUMMON_MANUAL_DESPAWN);
                    if (Creature* summon = summons.GetCreatureWithEntry(NPC_TM_LOOKOUT))
                        summon->AI()->Talk(SAY_LOOKOUT_INN);
                    break;
                case 92:
                    SetRun(false);
                    break;
                case 94:
                    summons.DespawnAll();
                    SetEscortPaused(true);
                    SetRun(true);
                    instance->SetData(DATA_ESCORT_PROGRESS, ENCOUNTER_PROGRESS_TARETHA_MEET);
                    if (Creature* Taretha = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_TARETHA_GUID)))
                    {
                        Taretha->HandleEmoteCommand(EMOTE_ONESHOT_CHEER);
                        Taretha->AI()->Talk(SAY_TARETHA_ESCAPED);
                    }
                    events.ScheduleEvent(EVENT_THRALL_TALK, 4000);
                    break;
                case 101:
                    SetEscortPaused(true);
                    events.ScheduleEvent(EVENT_EPOCH_INTRO, 500);
                    events.ScheduleEvent(EVENT_SUMMON_INFINITES, 1500);
                    events.ScheduleEvent(EVENT_TRANSFORM, 8000);
                    events.ScheduleEvent(EVENT_START_WAVE_1, 25000);
                    break;
                case 103:
                    instance->SetData(DATA_ESCORT_PROGRESS, ENCOUNTER_PROGRESS_FINISHED);
                    me->SetVisible(false);
                    break;
            }
        }
References _mounted, Creature::AI(), DATA_ESCORT_PROGRESS, DATA_TARETHA_GUID, SummonList::DespawnAll(), EMOTE_ONESHOT_CHEER, ENCOUNTER_PROGRESS_AMBUSHES_1, ENCOUNTER_PROGRESS_FINISHED, ENCOUNTER_PROGRESS_TARETHA_MEET, ENCOUNTER_PROGRESS_TARREN_MILL, EVENT_ARMORER_SAY, EVENT_DRESSING_ARMOR, EVENT_DRESSING_AXE, EVENT_DRESSING_KNEEL, EVENT_DRESSING_SHIELD, EVENT_DRESSING_STAND, EVENT_DRESSING_TALK, EVENT_ENTER_MOUNT, EVENT_EPOCH_INTRO, EVENT_GUARDS_MOVING, EVENT_KILL_ARMORER, EVENT_LOOK_1, EVENT_LOOK_2, EVENT_LOOK_3, EVENT_LOOK_4, EVENT_LOOK_5, EVENT_MOVE_AROUND, EVENT_SET_FACING, EVENT_START_WAVE_1, EVENT_SUMMON_GUARDS, EVENT_SUMMON_GUARDS_2, EVENT_SUMMON_INFINITES, EVENT_SUMMON_TALK1, EVENT_SUMMON_TALK2, EVENT_SUMMON_TALK3, EVENT_TALK_KILL_ARMORER, EVENT_TALK_START_RIDE, EVENT_THRALL_EMOTE, EVENT_THRALL_TALK, EVENT_TRANSFORM, WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), SummonList::GetCreatureWithEntry(), InstanceScript::GetGuidData(), Unit::HandleEmoteCommand(), IN_MILLISECONDS, instance, ScriptedAI::me, MINUTE, NPC_CAPTAIN_SKARLOC, NPC_DURNHOLDE_MAGE, NPC_DURNHOLDE_VETERAN, NPC_DURNHOLDE_WARDEN, NPC_SKARLOC_MOUNT, NPC_TM_GUARDSMAN, NPC_TM_LOOKOUT, NPC_TM_PROTECTOR, SAY_EMOTE_HORSE, SAY_LOOKOUT_INN, SAY_SKARLOC_MEET, SAY_START_EVENT_PART1, SAY_TARETHA_ESCAPED, ZoneScript::SetData(), npc_escortAI::SetEscortPaused(), Unit::SetFacingTo(), Unit::SetNpcFlag(), npc_escortAI::SetRun(), Unit::SetVisible(), WorldObject::SummonCreature(), summons, CreatureAI::Talk(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_FLAG_GOSSIP, and UnMountSelf().
WaypointStart()
void npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointStart (uint32 waypointId) inline override virtual
Reimplemented from npc_escortAI.
        {
            switch (waypointId)
            {
                case 30:
                    Talk(SAY_START_EVENT_PART2);
                    break;
            }
        }
References SAY_START_EVENT_PART2.
Member Data Documentation
_barnWave
bool npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::_barnWave private
Referenced by JustReachedHome(), npc_thrall_old_hillsbradAI(), and UpdateAI().
_churchWave
bool npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::_churchWave private
Referenced by JustReachedHome(), npc_thrall_old_hillsbradAI(), and UpdateAI().
_mounted
bool npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::_mounted private
Referenced by JustEngagedWith(), MovementInform(), Reset(), and WaypointReached().
combatEvents
EventMap npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::combatEvents private
Referenced by JustEngagedWith(), Reset(), and UpdateEscortAI().
events
EventMap npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::events private
instance
InstanceScript* npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::instance private
Referenced by JustDied(), npc_thrall_old_hillsbradAI(), ReorderInstance(), Reset(), UpdateAI(), and WaypointReached().
summons
SummonList npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::summons private
Referenced by JustDied(), JustSummoned(), Reset(), SummonedCreatureDespawn(), SummonedCreatureDies(), UpdateAI(), and WaypointReached().