AzerothCore: reload_commandscript Class Reference
reload_commandscript Class Reference
Public Member Functions
reload_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleReloadGMTicketsCommand (ChatHandler *)
static bool HandleReloadAllCommand (ChatHandler *handler)
static bool HandleReloadBattlegroundTemplate (ChatHandler *handler)
static bool HandleReloadAllAchievementCommand (ChatHandler *handler)
static bool HandleReloadAllAreaCommand (ChatHandler *handler)
static bool HandleReloadAllLootCommand (ChatHandler *handler)
static bool HandleReloadAllNpcCommand (ChatHandler *handler)
static bool HandleReloadAllQuestCommand (ChatHandler *handler)
static bool HandleReloadAllScriptsCommand (ChatHandler *handler)
static bool HandleReloadAllSpellCommand (ChatHandler *handler)
static bool HandleReloadAllGossipsCommand (ChatHandler *handler)
static bool HandleReloadAllItemCommand (ChatHandler *handler)
static bool HandleReloadAllLocalesCommand (ChatHandler *handler)
static bool HandleReloadConfigCommand (ChatHandler *handler)
static bool HandleReloadDungeonAccessCommand (ChatHandler *handler)
static bool HandleReloadAchievementCriteriaDataCommand (ChatHandler *handler)
static bool HandleReloadAchievementRewardCommand (ChatHandler *handler)
static bool HandleReloadAreaTriggerTavernCommand (ChatHandler *handler)
static bool HandleReloadAreaTriggerCommand (ChatHandler *handler)
static bool HandleReloadAreaTriggerTeleportCommand (ChatHandler *handler)
static bool HandleReloadAutobroadcastCommand (ChatHandler *handler)
static bool HandleReloadMotdCommand (ChatHandler *handler)
static bool HandleReloadBroadcastTextCommand (ChatHandler *handler)
static bool HandleReloadCommandCommand (ChatHandler *handler)
static bool HandleReloadOnKillReputationCommand (ChatHandler *handler)
static bool HandleReloadCreatureTemplateCommand (ChatHandler *handler, std::string_view args)
static bool HandleReloadCreatureQuestStarterCommand (ChatHandler *handler)
static bool HandleReloadLinkedRespawnCommand (ChatHandler *handler)
static bool HandleReloadCreatureQuestEnderCommand (ChatHandler *handler)
static bool HandleReloadGossipMenuCommand (ChatHandler *handler)
static bool HandleReloadGossipMenuOptionCommand (ChatHandler *handler)
static bool HandleReloadGOQuestStarterCommand (ChatHandler *handler)
static bool HandleReloadGOQuestEnderCommand (ChatHandler *handler)
static bool HandleReloadQuestAreaTriggersCommand (ChatHandler *handler)
static bool HandleReloadQuestGreetingCommand (ChatHandler *handler)
static bool HandleReloadQuestTemplateCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesCreatureCommand (ChatHandler *handler)
static bool HandleReloadCreatureMovementOverrideCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesDisenchantCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesFishingCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesGameobjectCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesItemCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesMillingCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesPickpocketingCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesProspectingCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesMailCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesReferenceCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesSkinningCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesSpellCommand (ChatHandler *handler)
static bool HandleReloadLootTemplatesPlayerCommand (ChatHandler *handler)
static bool HandleReloadModuleStringCommand (ChatHandler *handler)
static bool HandleReloadAcoreStringCommand (ChatHandler *handler)
static bool HandleReloadWardenactionCommand (ChatHandler *handler)
static bool HandleReloadNpcTrainerCommand (ChatHandler *handler)
static bool HandleReloadNpcVendorCommand (ChatHandler *handler)
static bool HandleReloadGameEventNPCVendorCommand (ChatHandler *handler)
static bool HandleReloadPointsOfInterestCommand (ChatHandler *handler)
static bool HandleReloadQuestPOICommand (ChatHandler *handler)
static bool HandleReloadSpellClickSpellsCommand (ChatHandler *handler)
static bool HandleReloadReservedNameCommand (ChatHandler *handler)
static bool HandleReloadProfanityNameCommand (ChatHandler *handler)
static bool HandleReloadReputationRewardRateCommand (ChatHandler *handler)
static bool HandleReloadReputationSpilloverTemplateCommand (ChatHandler *handler)
static bool HandleReloadSkillDiscoveryTemplateCommand (ChatHandler *handler)
static bool HandleReloadSkillPerfectItemTemplateCommand (ChatHandler *handler)
static bool HandleReloadSkillExtraItemTemplateCommand (ChatHandler *handler)
static bool HandleReloadSkillFishingBaseLevelCommand (ChatHandler *handler)
static bool HandleReloadSpellAreaCommand (ChatHandler *handler)
static bool HandleReloadSpellRequiredCommand (ChatHandler *handler)
static bool HandleReloadSpellGroupsCommand (ChatHandler *handler)
static bool HandleReloadSpellLinkedSpellCommand (ChatHandler *handler)
static bool HandleReloadSpellProcEventCommand (ChatHandler *handler)
static bool HandleReloadSpellProcsCommand (ChatHandler *handler)
static bool HandleReloadSpellBonusesCommand (ChatHandler *handler)
static bool HandleReloadSpellTargetPositionCommand (ChatHandler *handler)
static bool HandleReloadSpellThreatsCommand (ChatHandler *handler)
static bool HandleReloadSpellGroupStackRulesCommand (ChatHandler *handler)
static bool HandleReloadSpellPetAurasCommand (ChatHandler *handler)
static bool HandleReloadPageTextsCommand (ChatHandler *handler)
static bool HandleReloadItemEnchantementsCommand (ChatHandler *handler)
static bool HandleReloadItemSetNamesCommand (ChatHandler *handler)
static bool HandleReloadEventScriptsCommand (ChatHandler *handler)
static bool HandleReloadWpScriptsCommand (ChatHandler *handler)
static bool HandleReloadWpCommand (ChatHandler *handler)
static bool HandleReloadSpellScriptsCommand (ChatHandler *handler)
static bool HandleReloadGameGraveyardZoneCommand (ChatHandler *handler)
static bool HandleReloadGameTeleCommand (ChatHandler *handler)
static bool HandleReloadDisablesCommand (ChatHandler *handler)
static bool HandleReloadLocalesAchievementRewardCommand (ChatHandler *handler)
static bool HandleReloadLfgRewardsCommand (ChatHandler *handler)
static bool HandleReloadLocalesCreatureCommand (ChatHandler *handler)
static bool HandleReloadLocalesCreatureTextCommand (ChatHandler *handler)
static bool HandleReloadLocalesGameobjectCommand (ChatHandler *handler)
static bool HandleReloadLocalesGossipMenuOptionCommand (ChatHandler *handler)
static bool HandleReloadLocalesItemCommand (ChatHandler *handler)
static bool HandleReloadLocalesItemSetNameCommand (ChatHandler *handler)
static bool HandleReloadLocalesNpcTextCommand (ChatHandler *handler)
static bool HandleReloadLocalesPageTextCommand (ChatHandler *handler)
static bool HandleReloadLocalesPointsOfInterestCommand (ChatHandler *handler)
static bool HandleReloadLocalesQuestCommand (ChatHandler *handler)
static bool HandleReloadLocalesQuestOfferRewardCommand (ChatHandler *handler)
static bool HandleReloadLocalesQuestRequestItemsCommand (ChatHandler *handler)
static bool HandleReloadMailLevelRewardCommand (ChatHandler *handler)
static bool HandleReloadMailServerTemplateCommand (ChatHandler *handler)
static bool HandleReloadAuctionsCommand (ChatHandler *handler)
static bool HandleReloadConditions (ChatHandler *handler)
static bool HandleReloadCreatureText (ChatHandler *handler)
static bool HandleReloadSmartScripts (ChatHandler *handler)
static bool HandleReloadVehicleAccessoryCommand (ChatHandler *handler)
static bool HandleReloadVehicleTemplateAccessoryCommand (ChatHandler *handler)
static bool HandleReloadGameGraveyardCommand (ChatHandler *handler)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
reload_commandscript()
reload_commandscript::reload_commandscript () inline
: CommandScript("reload_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable reload_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable reloadAllCommandTable =
        {
            { "achievement",                   HandleReloadAllAchievementCommand,             SEC_ADMINISTRATOR, Console::Yes },
            { "area",                          HandleReloadAllAreaCommand,                    SEC_ADMINISTRATOR, Console::Yes },
            { "gossips",                       HandleReloadAllGossipsCommand,                 SEC_ADMINISTRATOR, Console::Yes },
            { "item",                          HandleReloadAllItemCommand,                    SEC_ADMINISTRATOR, Console::Yes },
            { "locales",                       HandleReloadAllLocalesCommand,                 SEC_ADMINISTRATOR, Console::Yes },
            { "loot",                          HandleReloadAllLootCommand,                    SEC_ADMINISTRATOR, Console::Yes },
            { "npc",                           HandleReloadAllNpcCommand,                     SEC_ADMINISTRATOR, Console::Yes },
            { "quest",                         HandleReloadAllQuestCommand,                   SEC_ADMINISTRATOR, Console::Yes },
            { "scripts",                       HandleReloadAllScriptsCommand,                 SEC_ADMINISTRATOR, Console::Yes },
            { "spell",                         HandleReloadAllSpellCommand,                   SEC_ADMINISTRATOR, Console::Yes },
            { "",                              HandleReloadAllCommand,                        SEC_ADMINISTRATOR, Console::Yes },
        };
        static ChatCommandTable reloadCommandTable =
        {
            { "auctions",                      HandleReloadAuctionsCommand,                   SEC_ADMINISTRATOR, Console::Yes },
            { "dungeon_access_template",       HandleReloadDungeonAccessCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "dungeon_access_requirements",   HandleReloadDungeonAccessCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "achievement_criteria_data",     HandleReloadAchievementCriteriaDataCommand,    SEC_ADMINISTRATOR, Console::Yes },
            { "achievement_reward",            HandleReloadAchievementRewardCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "all", reloadAllCommandTable },
            { "areatrigger",                   HandleReloadQuestAreaTriggersCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "areatrigger_involvedrelation",  HandleReloadQuestAreaTriggersCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "areatrigger_tavern",            HandleReloadAreaTriggerTavernCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "areatrigger_teleport",          HandleReloadAreaTriggerTeleportCommand,        SEC_ADMINISTRATOR, Console::Yes },
            { "autobroadcast",                 HandleReloadAutobroadcastCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "motd",                          HandleReloadMotdCommand,                       SEC_ADMINISTRATOR, Console::Yes },
            { "broadcast_text",                HandleReloadBroadcastTextCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "battleground_template",         HandleReloadBattlegroundTemplate,              SEC_ADMINISTRATOR, Console::Yes },
            { "command",                       HandleReloadCommandCommand,                    SEC_ADMINISTRATOR, Console::Yes },
            { "conditions",                    HandleReloadConditions,                        SEC_ADMINISTRATOR, Console::Yes },
            { "config",                        HandleReloadConfigCommand,                     SEC_ADMINISTRATOR, Console::Yes },
            { "creature_text",                 HandleReloadCreatureText,                      SEC_ADMINISTRATOR, Console::Yes },
            { "creature_questender",           HandleReloadCreatureQuestEnderCommand,         SEC_ADMINISTRATOR, Console::Yes },
            { "creature_linked_respawn",       HandleReloadLinkedRespawnCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "creature_loot_template",        HandleReloadLootTemplatesCreatureCommand,      SEC_ADMINISTRATOR, Console::Yes },
            { "creature_movement_override",     HandleReloadCreatureMovementOverrideCommand,    SEC_ADMINISTRATOR, Console::Yes},
            { "creature_onkill_reputation",     HandleReloadOnKillReputationCommand,           SEC_ADMINISTRATOR, Console::Yes },
            { "creature_queststarter",         HandleReloadCreatureQuestStarterCommand,       SEC_ADMINISTRATOR, Console::Yes },
            { "creature_template",             HandleReloadCreatureTemplateCommand,           SEC_ADMINISTRATOR, Console::Yes },
            { "disables",                      HandleReloadDisablesCommand,                   SEC_ADMINISTRATOR, Console::Yes },
            { "disenchant_loot_template",      HandleReloadLootTemplatesDisenchantCommand,    SEC_ADMINISTRATOR, Console::Yes },
            { "event_scripts",                 HandleReloadEventScriptsCommand,               SEC_ADMINISTRATOR, Console::Yes },
            { "fishing_loot_template",         HandleReloadLootTemplatesFishingCommand,       SEC_ADMINISTRATOR, Console::Yes },
            { "game_graveyard",                HandleReloadGameGraveyardCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "graveyard_zone",                HandleReloadGameGraveyardZoneCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "game_tele",                     HandleReloadGameTeleCommand,                   SEC_ADMINISTRATOR, Console::Yes },
            { "gameobject_questender",         HandleReloadGOQuestEnderCommand,               SEC_ADMINISTRATOR, Console::Yes },
            { "gameobject_loot_template",      HandleReloadLootTemplatesGameobjectCommand,    SEC_ADMINISTRATOR, Console::Yes },
            { "gameobject_queststarter",       HandleReloadGOQuestStarterCommand,             SEC_ADMINISTRATOR, Console::Yes },
            { "gm_tickets",                    HandleReloadGMTicketsCommand,                  SEC_ADMINISTRATOR, Console::Yes },
            { "gossip_menu",                   HandleReloadGossipMenuCommand,                 SEC_ADMINISTRATOR, Console::Yes },
            { "gossip_menu_option",            HandleReloadGossipMenuOptionCommand,           SEC_ADMINISTRATOR, Console::Yes },
            { "item_enchantment_template",     HandleReloadItemEnchantementsCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "item_loot_template",            HandleReloadLootTemplatesItemCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "item_set_names",                HandleReloadItemSetNamesCommand,               SEC_ADMINISTRATOR, Console::Yes },
            { "lfg_dungeon_rewards",           HandleReloadLfgRewardsCommand,                 SEC_ADMINISTRATOR, Console::Yes },
            { "achievement_reward_locale",     HandleReloadLocalesAchievementRewardCommand,   SEC_ADMINISTRATOR, Console::Yes },
            { "creature_template_locale",      HandleReloadLocalesCreatureCommand,            SEC_ADMINISTRATOR, Console::Yes },
            { "creature_text_locale",          HandleReloadLocalesCreatureTextCommand,        SEC_ADMINISTRATOR, Console::Yes },
            { "gameobject_template_locale",    HandleReloadLocalesGameobjectCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "gossip_menu_option_locale",     HandleReloadLocalesGossipMenuOptionCommand,    SEC_ADMINISTRATOR, Console::Yes },
            { "item_template_locale",          HandleReloadLocalesItemCommand,                SEC_ADMINISTRATOR, Console::Yes },
            { "item_set_name_locale",          HandleReloadLocalesItemSetNameCommand,         SEC_ADMINISTRATOR, Console::Yes },
            { "npc_text_locale",               HandleReloadLocalesNpcTextCommand,             SEC_ADMINISTRATOR, Console::Yes },
            { "page_text_locale",              HandleReloadLocalesPageTextCommand,            SEC_ADMINISTRATOR, Console::Yes },
            { "points_of_interest_locale",     HandleReloadLocalesPointsOfInterestCommand,    SEC_ADMINISTRATOR, Console::Yes },
            { "quest_template_locale",         HandleReloadLocalesQuestCommand,               SEC_ADMINISTRATOR, Console::Yes },
            { "quest_offer_reward_locale",     HandleReloadLocalesQuestOfferRewardCommand,    SEC_ADMINISTRATOR, Console::Yes },
            { "quest_request_item_locale",     HandleReloadLocalesQuestRequestItemsCommand,   SEC_ADMINISTRATOR, Console::Yes },
            { "mail_level_reward",             HandleReloadMailLevelRewardCommand,            SEC_ADMINISTRATOR, Console::Yes },
            { "mail_loot_template",            HandleReloadLootTemplatesMailCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "mail_server_template",          HandleReloadMailServerTemplateCommand,         SEC_ADMINISTRATOR, Console::Yes },
            { "milling_loot_template",         HandleReloadLootTemplatesMillingCommand,       SEC_ADMINISTRATOR, Console::Yes },
            { "npc_spellclick_spells",         HandleReloadSpellClickSpellsCommand,           SEC_ADMINISTRATOR, Console::Yes },
            { "npc_trainer",                   HandleReloadNpcTrainerCommand,                 SEC_ADMINISTRATOR, Console::Yes },
            { "npc_vendor",                    HandleReloadNpcVendorCommand,                  SEC_ADMINISTRATOR, Console::Yes },
            { "game_event_npc_vendor",         HandleReloadGameEventNPCVendorCommand,         SEC_ADMINISTRATOR, Console::Yes },
            { "page_text",                     HandleReloadPageTextsCommand,                  SEC_ADMINISTRATOR, Console::Yes },
            { "pickpocketing_loot_template",   HandleReloadLootTemplatesPickpocketingCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "points_of_interest",            HandleReloadPointsOfInterestCommand,           SEC_ADMINISTRATOR, Console::Yes },
            { "prospecting_loot_template",     HandleReloadLootTemplatesProspectingCommand,   SEC_ADMINISTRATOR, Console::Yes },
            { "quest_greeting",                HandleReloadQuestGreetingCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "quest_poi",                     HandleReloadQuestPOICommand,                   SEC_ADMINISTRATOR, Console::Yes },
            { "quest_template",                HandleReloadQuestTemplateCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "reference_loot_template",       HandleReloadLootTemplatesReferenceCommand,     SEC_ADMINISTRATOR, Console::Yes },
            { "reserved_name",                 HandleReloadReservedNameCommand,               SEC_ADMINISTRATOR, Console::Yes },
            { "profanity_name",                HandleReloadProfanityNameCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "reputation_reward_rate",        HandleReloadReputationRewardRateCommand,       SEC_ADMINISTRATOR, Console::Yes },
            { "reputation_spillover_template", HandleReloadReputationRewardRateCommand,       SEC_ADMINISTRATOR, Console::Yes },
            { "skill_discovery_template",      HandleReloadSkillDiscoveryTemplateCommand,     SEC_ADMINISTRATOR, Console::Yes },
            { "skill_extra_item_template",     HandleReloadSkillExtraItemTemplateCommand,     SEC_ADMINISTRATOR, Console::Yes },
            { "skill_fishing_base_level",      HandleReloadSkillFishingBaseLevelCommand,      SEC_ADMINISTRATOR, Console::Yes },
            { "skinning_loot_template",        HandleReloadLootTemplatesSkinningCommand,      SEC_ADMINISTRATOR, Console::Yes },
            { "smart_scripts",                 HandleReloadSmartScripts,                      SEC_ADMINISTRATOR, Console::Yes },
            { "spell_required",                HandleReloadSpellRequiredCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "spell_area",                    HandleReloadSpellAreaCommand,                  SEC_ADMINISTRATOR, Console::Yes },
            { "spell_bonus_data",              HandleReloadSpellBonusesCommand,               SEC_ADMINISTRATOR, Console::Yes },
            { "spell_group",                   HandleReloadSpellGroupsCommand,                SEC_ADMINISTRATOR, Console::Yes },
            { "spell_loot_template",           HandleReloadLootTemplatesSpellCommand,         SEC_ADMINISTRATOR, Console::Yes },
            { "spell_linked_spell",            HandleReloadSpellLinkedSpellCommand,           SEC_ADMINISTRATOR, Console::Yes },
            { "spell_pet_auras",               HandleReloadSpellPetAurasCommand,              SEC_ADMINISTRATOR, Console::Yes },
            { "spell_proc_event",              HandleReloadSpellProcEventCommand,             SEC_ADMINISTRATOR, Console::Yes },
            { "spell_proc",                    HandleReloadSpellProcsCommand,                 SEC_ADMINISTRATOR, Console::Yes },
            { "spell_scripts",                 HandleReloadSpellScriptsCommand,               SEC_ADMINISTRATOR, Console::Yes },
            { "spell_target_position",         HandleReloadSpellTargetPositionCommand,        SEC_ADMINISTRATOR, Console::Yes },
            { "spell_threats",                 HandleReloadSpellThreatsCommand,               SEC_ADMINISTRATOR, Console::Yes },
            { "spell_group_stack_rules",       HandleReloadSpellGroupStackRulesCommand,       SEC_ADMINISTRATOR, Console::Yes },
            { "player_loot_template",          HandleReloadLootTemplatesPlayerCommand,        SEC_ADMINISTRATOR, Console::Yes },
            { "module_string",                 HandleReloadModuleStringCommand,               SEC_ADMINISTRATOR, Console::Yes },
            { "acore_string",                  HandleReloadAcoreStringCommand,                SEC_ADMINISTRATOR, Console::Yes },
            { "warden_action",                 HandleReloadWardenactionCommand,               SEC_ADMINISTRATOR, Console::Yes },
            { "waypoint_scripts",              HandleReloadWpScriptsCommand,                  SEC_ADMINISTRATOR, Console::Yes },
            { "waypoint_data",                 HandleReloadWpCommand,                         SEC_ADMINISTRATOR, Console::Yes },
            { "vehicle_accessory",             HandleReloadVehicleAccessoryCommand,           SEC_ADMINISTRATOR, Console::Yes },
            { "vehicle_template_accessory",    HandleReloadVehicleTemplateAccessoryCommand,   SEC_ADMINISTRATOR, Console::Yes },
        };
        static ChatCommandTable commandTable =
        {
            { "reload", reloadCommandTable }
        };
        return commandTable;
    }
References HandleReloadAchievementCriteriaDataCommand(), HandleReloadAchievementRewardCommand(), HandleReloadAcoreStringCommand(), HandleReloadAllAchievementCommand(), HandleReloadAllAreaCommand(), HandleReloadAllCommand(), HandleReloadAllGossipsCommand(), HandleReloadAllItemCommand(), HandleReloadAllLocalesCommand(), HandleReloadAllLootCommand(), HandleReloadAllNpcCommand(), HandleReloadAllQuestCommand(), HandleReloadAllScriptsCommand(), HandleReloadAllSpellCommand(), HandleReloadAreaTriggerTavernCommand(), HandleReloadAreaTriggerTeleportCommand(), HandleReloadAuctionsCommand(), HandleReloadAutobroadcastCommand(), HandleReloadBattlegroundTemplate(), HandleReloadBroadcastTextCommand(), HandleReloadCommandCommand(), HandleReloadConditions(), HandleReloadConfigCommand(), HandleReloadCreatureMovementOverrideCommand(), HandleReloadCreatureQuestEnderCommand(), HandleReloadCreatureQuestStarterCommand(), HandleReloadCreatureTemplateCommand(), HandleReloadCreatureText(), HandleReloadDisablesCommand(), HandleReloadDungeonAccessCommand(), HandleReloadEventScriptsCommand(), HandleReloadGameEventNPCVendorCommand(), HandleReloadGameGraveyardCommand(), HandleReloadGameGraveyardZoneCommand(), HandleReloadGameTeleCommand(), HandleReloadGMTicketsCommand(), HandleReloadGOQuestEnderCommand(), HandleReloadGOQuestStarterCommand(), HandleReloadGossipMenuCommand(), HandleReloadGossipMenuOptionCommand(), HandleReloadItemEnchantementsCommand(), HandleReloadItemSetNamesCommand(), HandleReloadLfgRewardsCommand(), HandleReloadLinkedRespawnCommand(), HandleReloadLocalesAchievementRewardCommand(), HandleReloadLocalesCreatureCommand(), HandleReloadLocalesCreatureTextCommand(), HandleReloadLocalesGameobjectCommand(), HandleReloadLocalesGossipMenuOptionCommand(), HandleReloadLocalesItemCommand(), HandleReloadLocalesItemSetNameCommand(), HandleReloadLocalesNpcTextCommand(), HandleReloadLocalesPageTextCommand(), HandleReloadLocalesPointsOfInterestCommand(), HandleReloadLocalesQuestCommand(), HandleReloadLocalesQuestOfferRewardCommand(), HandleReloadLocalesQuestRequestItemsCommand(), HandleReloadLootTemplatesCreatureCommand(), HandleReloadLootTemplatesDisenchantCommand(), HandleReloadLootTemplatesFishingCommand(), HandleReloadLootTemplatesGameobjectCommand(), HandleReloadLootTemplatesItemCommand(), HandleReloadLootTemplatesMailCommand(), HandleReloadLootTemplatesMillingCommand(), HandleReloadLootTemplatesPickpocketingCommand(), HandleReloadLootTemplatesPlayerCommand(), HandleReloadLootTemplatesProspectingCommand(), HandleReloadLootTemplatesReferenceCommand(), HandleReloadLootTemplatesSkinningCommand(), HandleReloadLootTemplatesSpellCommand(), HandleReloadMailLevelRewardCommand(), HandleReloadMailServerTemplateCommand(), HandleReloadModuleStringCommand(), HandleReloadMotdCommand(), HandleReloadNpcTrainerCommand(), HandleReloadNpcVendorCommand(), HandleReloadOnKillReputationCommand(), HandleReloadPageTextsCommand(), HandleReloadPointsOfInterestCommand(), HandleReloadProfanityNameCommand(), HandleReloadQuestAreaTriggersCommand(), HandleReloadQuestGreetingCommand(), HandleReloadQuestPOICommand(), HandleReloadQuestTemplateCommand(), HandleReloadReputationRewardRateCommand(), HandleReloadReservedNameCommand(), HandleReloadSkillDiscoveryTemplateCommand(), HandleReloadSkillExtraItemTemplateCommand(), HandleReloadSkillFishingBaseLevelCommand(), HandleReloadSmartScripts(), HandleReloadSpellAreaCommand(), HandleReloadSpellBonusesCommand(), HandleReloadSpellClickSpellsCommand(), HandleReloadSpellGroupsCommand(), HandleReloadSpellGroupStackRulesCommand(), HandleReloadSpellLinkedSpellCommand(), HandleReloadSpellPetAurasCommand(), HandleReloadSpellProcEventCommand(), HandleReloadSpellProcsCommand(), HandleReloadSpellRequiredCommand(), HandleReloadSpellScriptsCommand(), HandleReloadSpellTargetPositionCommand(), HandleReloadSpellThreatsCommand(), HandleReloadVehicleAccessoryCommand(), HandleReloadVehicleTemplateAccessoryCommand(), HandleReloadWardenactionCommand(), HandleReloadWpCommand(), HandleReloadWpScriptsCommand(), and SEC_ADMINISTRATOR.
HandleReloadAchievementCriteriaDataCommand()
static bool reload_commandscript::HandleReloadAchievementCriteriaDataCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Additional Achievement Criteria Data...");
        sAchievementMgr->LoadAchievementCriteriaData();
        handler->SendGlobalGMSysMessage("DB table `achievement_criteria_data` reloaded.");
        return true;
    }
References LOG_INFO, sAchievementMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands(), and HandleReloadAllAchievementCommand().
HandleReloadAchievementRewardCommand()
static bool reload_commandscript::HandleReloadAchievementRewardCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Achievement Reward Data...");
        sAchievementMgr->LoadRewards();
        handler->SendGlobalGMSysMessage("DB table `achievement_reward` reloaded.");
        return true;
    }
References LOG_INFO, sAchievementMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands(), and HandleReloadAllAchievementCommand().
HandleReloadAcoreStringCommand()
static bool reload_commandscript::HandleReloadAcoreStringCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading acore_string Table!");
        sObjectMgr->LoadAcoreStrings();
        handler->SendGlobalGMSysMessage("DB table `acore_string` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadAllAchievementCommand()
static bool reload_commandscript::HandleReloadAllAchievementCommand (ChatHandler * handler) inline static
    {
        HandleReloadAchievementCriteriaDataCommand(handler);
        HandleReloadAchievementRewardCommand(handler);
        return true;
    }
References HandleReloadAchievementCriteriaDataCommand(), and HandleReloadAchievementRewardCommand().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadAllAreaCommand()
static bool reload_commandscript::HandleReloadAllAreaCommand (ChatHandler * handler) inline static
    {
        //HandleReloadQuestAreaTriggersCommand(handler); -- reloaded in HandleReloadAllQuestCommand
        HandleReloadAreaTriggerTeleportCommand(handler);
        HandleReloadAreaTriggerTavernCommand(handler);
        HandleReloadGameGraveyardZoneCommand(handler);
        return true;
    }
References HandleReloadAreaTriggerTavernCommand(), HandleReloadAreaTriggerTeleportCommand(), and HandleReloadGameGraveyardZoneCommand().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadAllCommand()
static bool reload_commandscript::HandleReloadAllCommand (ChatHandler * handler) inline static
    {
        HandleReloadSkillFishingBaseLevelCommand(handler);
        HandleReloadAllAchievementCommand(handler);
        HandleReloadAllAreaCommand(handler);
        HandleReloadAllLootCommand(handler);
        HandleReloadAllNpcCommand(handler);
        HandleReloadAllQuestCommand(handler);
        HandleReloadAllSpellCommand(handler);
        HandleReloadAllItemCommand(handler);
        HandleReloadAllGossipsCommand(handler);
        HandleReloadAllLocalesCommand(handler);
        HandleReloadDungeonAccessCommand(handler);
        HandleReloadMailLevelRewardCommand(handler);
        HandleReloadMailServerTemplateCommand(handler);
        HandleReloadCommandCommand(handler);
        HandleReloadReservedNameCommand(handler);
        HandleReloadProfanityNameCommand(handler);
        HandleReloadAcoreStringCommand(handler);
        HandleReloadGameTeleCommand(handler);
        HandleReloadCreatureMovementOverrideCommand(handler);
        HandleReloadVehicleAccessoryCommand(handler);
        HandleReloadVehicleTemplateAccessoryCommand(handler);
        HandleReloadAutobroadcastCommand(handler);
        HandleReloadMotdCommand(handler);
        HandleReloadBroadcastTextCommand(handler);
        HandleReloadBattlegroundTemplate(handler);
        return true;
    }
References HandleReloadAcoreStringCommand(), HandleReloadAllAchievementCommand(), HandleReloadAllAreaCommand(), HandleReloadAllGossipsCommand(), HandleReloadAllItemCommand(), HandleReloadAllLocalesCommand(), HandleReloadAllLootCommand(), HandleReloadAllNpcCommand(), HandleReloadAllQuestCommand(), HandleReloadAllSpellCommand(), HandleReloadAutobroadcastCommand(), HandleReloadBattlegroundTemplate(), HandleReloadBroadcastTextCommand(), HandleReloadCommandCommand(), HandleReloadCreatureMovementOverrideCommand(), HandleReloadDungeonAccessCommand(), HandleReloadGameTeleCommand(), HandleReloadMailLevelRewardCommand(), HandleReloadMailServerTemplateCommand(), HandleReloadMotdCommand(), HandleReloadProfanityNameCommand(), HandleReloadReservedNameCommand(), HandleReloadSkillFishingBaseLevelCommand(), HandleReloadVehicleAccessoryCommand(), and HandleReloadVehicleTemplateAccessoryCommand().
Referenced by GetCommands().
HandleReloadAllGossipsCommand()
static bool reload_commandscript::HandleReloadAllGossipsCommand (ChatHandler * handler) inline static
    {
        HandleReloadGossipMenuCommand(handler);
        HandleReloadGossipMenuOptionCommand(handler);
        HandleReloadPointsOfInterestCommand(handler);
        return true;
    }
References HandleReloadGossipMenuCommand(), HandleReloadGossipMenuOptionCommand(), and HandleReloadPointsOfInterestCommand().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadAllItemCommand()
static bool reload_commandscript::HandleReloadAllItemCommand (ChatHandler * handler) inline static
    {
        HandleReloadPageTextsCommand(handler);
        HandleReloadItemEnchantementsCommand(handler);
        return true;
    }
References HandleReloadItemEnchantementsCommand(), and HandleReloadPageTextsCommand().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadAllLocalesCommand()
static bool reload_commandscript::HandleReloadAllLocalesCommand (ChatHandler * handler) inline static
    {
        HandleReloadLocalesAchievementRewardCommand(handler);
        HandleReloadLocalesCreatureCommand(handler);
        HandleReloadLocalesCreatureTextCommand(handler);
        HandleReloadLocalesGameobjectCommand(handler);
        HandleReloadLocalesGossipMenuOptionCommand(handler);
        HandleReloadLocalesItemCommand(handler);
        HandleReloadLocalesNpcTextCommand(handler);
        HandleReloadLocalesPageTextCommand(handler);
        HandleReloadLocalesPointsOfInterestCommand(handler);
        HandleReloadLocalesQuestCommand(handler);
        HandleReloadLocalesQuestOfferRewardCommand(handler);
        HandleReloadLocalesQuestRequestItemsCommand(handler);
        return true;
    }
References HandleReloadLocalesAchievementRewardCommand(), HandleReloadLocalesCreatureCommand(), HandleReloadLocalesCreatureTextCommand(), HandleReloadLocalesGameobjectCommand(), HandleReloadLocalesGossipMenuOptionCommand(), HandleReloadLocalesItemCommand(), HandleReloadLocalesNpcTextCommand(), HandleReloadLocalesPageTextCommand(), HandleReloadLocalesPointsOfInterestCommand(), HandleReloadLocalesQuestCommand(), HandleReloadLocalesQuestOfferRewardCommand(), and HandleReloadLocalesQuestRequestItemsCommand().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadAllLootCommand()
static bool reload_commandscript::HandleReloadAllLootCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables...");
        LoadLootTables();
        handler->SendGlobalGMSysMessage("DB tables `*_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LoadLootTables(), LOG_INFO, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadAllNpcCommand()
static bool reload_commandscript::HandleReloadAllNpcCommand (ChatHandler * handler) inline static
    {
        HandleReloadNpcTrainerCommand(handler);
        HandleReloadNpcVendorCommand(handler);
        HandleReloadPointsOfInterestCommand(handler);
        HandleReloadSpellClickSpellsCommand(handler);
        return true;
    }
References HandleReloadNpcTrainerCommand(), HandleReloadNpcVendorCommand(), HandleReloadPointsOfInterestCommand(), and HandleReloadSpellClickSpellsCommand().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadAllQuestCommand()
static bool reload_commandscript::HandleReloadAllQuestCommand (ChatHandler * handler) inline static
    {
        HandleReloadQuestGreetingCommand(handler);
        HandleReloadQuestAreaTriggersCommand(handler);
        HandleReloadQuestPOICommand(handler);
        HandleReloadQuestTemplateCommand(handler);
        LOG_INFO("server.loading", "Reloading Quests Relations...");
        sObjectMgr->LoadQuestStartersAndEnders();
        handler->SendGlobalGMSysMessage("DB tables `*_queststarter` and `*_questender` reloaded.");
        return true;
    }
References HandleReloadQuestAreaTriggersCommand(), HandleReloadQuestGreetingCommand(), HandleReloadQuestPOICommand(), HandleReloadQuestTemplateCommand(), LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadAllScriptsCommand()
static bool reload_commandscript::HandleReloadAllScriptsCommand (ChatHandler * handler) inline static
    {
        if (sScriptMgr->IsScriptScheduled())
        {
            handler->SendErrorMessage("DB scripts used currently, please attempt reload later.");
            return false;
        }
        LOG_INFO("server.loading", "Reloading Scripts...");
        HandleReloadEventScriptsCommand(handler);
        HandleReloadSpellScriptsCommand(handler);
        handler->SendGlobalGMSysMessage("DB tables `*_scripts` reloaded.");
        HandleReloadWpScriptsCommand(handler);
        HandleReloadWpCommand(handler);
        return true;
    }
References HandleReloadEventScriptsCommand(), HandleReloadSpellScriptsCommand(), HandleReloadWpCommand(), HandleReloadWpScriptsCommand(), LOG_INFO, ChatHandler::SendErrorMessage(), ChatHandler::SendGlobalGMSysMessage(), and sScriptMgr.
Referenced by GetCommands().
HandleReloadAllSpellCommand()
static bool reload_commandscript::HandleReloadAllSpellCommand (ChatHandler * handler) inline static
    {
        HandleReloadSkillDiscoveryTemplateCommand(handler);
        HandleReloadSkillExtraItemTemplateCommand(handler);
        HandleReloadSpellRequiredCommand(handler);
        HandleReloadSpellAreaCommand(handler);
        HandleReloadSpellGroupsCommand(handler);
        HandleReloadSpellLinkedSpellCommand(handler);
        HandleReloadSpellProcEventCommand(handler);
        HandleReloadSpellProcsCommand(handler);
        HandleReloadSpellBonusesCommand(handler);
        HandleReloadSpellTargetPositionCommand(handler);
        HandleReloadSpellThreatsCommand(handler);
        HandleReloadSpellGroupStackRulesCommand(handler);
        HandleReloadSpellPetAurasCommand(handler);
        return true;
    }
References HandleReloadSkillDiscoveryTemplateCommand(), HandleReloadSkillExtraItemTemplateCommand(), HandleReloadSpellAreaCommand(), HandleReloadSpellBonusesCommand(), HandleReloadSpellGroupsCommand(), HandleReloadSpellGroupStackRulesCommand(), HandleReloadSpellLinkedSpellCommand(), HandleReloadSpellPetAurasCommand(), HandleReloadSpellProcEventCommand(), HandleReloadSpellProcsCommand(), HandleReloadSpellRequiredCommand(), HandleReloadSpellTargetPositionCommand(), and HandleReloadSpellThreatsCommand().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadAreaTriggerCommand()
static bool reload_commandscript::HandleReloadAreaTriggerCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Area Trigger definitions...");
        sObjectMgr->LoadAreaTriggers();
        handler->SendGlobalGMSysMessage("DB table `areatrigger` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
HandleReloadAreaTriggerTavernCommand()
static bool reload_commandscript::HandleReloadAreaTriggerTavernCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Tavern Area Triggers...");
        sObjectMgr->LoadTavernAreaTriggers();
        handler->SendGlobalGMSysMessage("DB table `areatrigger_tavern` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllAreaCommand().
HandleReloadAreaTriggerTeleportCommand()
static bool reload_commandscript::HandleReloadAreaTriggerTeleportCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Area Trigger teleport definitions...");
        sObjectMgr->LoadAreaTriggerTeleports();
        handler->SendGlobalGMSysMessage("DB table `areatrigger_teleport` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllAreaCommand().
HandleReloadAuctionsCommand()
static bool reload_commandscript::HandleReloadAuctionsCommand (ChatHandler * handler) inline static
Reload dynamic data tables from the database
    {
        LOG_INFO("server.loading", "Reloading Auctions...");
        sAuctionMgr->LoadAuctionItems();
        sAuctionMgr->LoadAuctions();
        handler->SendGlobalGMSysMessage("Auctions reloaded.");
        return true;
    }
References LOG_INFO, sAuctionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadAutobroadcastCommand()
static bool reload_commandscript::HandleReloadAutobroadcastCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Autobroadcasts...");
        sAutobroadcastMgr->LoadAutobroadcasts();
        handler->SendGlobalGMSysMessage("DB table `autobroadcast` reloaded.");
        return true;
    }
References LOG_INFO, sAutobroadcastMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadBattlegroundTemplate()
static bool reload_commandscript::HandleReloadBattlegroundTemplate (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Battleground Templates...");
        sBattlegroundMgr->LoadBattlegroundTemplates();
        handler->SendGlobalGMSysMessage("DB table `battleground_template` reloaded.");
        return true;
    }
References LOG_INFO, sBattlegroundMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadBroadcastTextCommand()
static bool reload_commandscript::HandleReloadBroadcastTextCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Broadcast texts...");
        sObjectMgr->LoadBroadcastTexts();
        sObjectMgr->LoadBroadcastTextLocales();
        handler->SendGlobalGMSysMessage("DB table `broadcast_text` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadCommandCommand()
static bool reload_commandscript::HandleReloadCommandCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading .command information...");
        Acore::ChatCommands::LoadCommandMap();
        handler->SendGlobalGMSysMessage("DB table `command` reloaded.");
        // do not log this invocation, otherwise we might crash (the command table we used to get here is no longer valid!)
        handler->SetSentErrorMessage(true);
        return false;
    }
References Acore::ChatCommands::LoadCommandMap(), LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadConditions()
static bool reload_commandscript::HandleReloadConditions (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Conditions...");
        sConditionMgr->LoadConditions(true);
        handler->SendGlobalGMSysMessage("Conditions reloaded.");
        return true;
    }
References LOG_INFO, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadConfigCommand()
static bool reload_commandscript::HandleReloadConfigCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading config settings...");
        sWorld->LoadConfigSettings(true);
        sMapMgr->InitializeVisibilityDistanceInfo();
        handler->SendGlobalGMSysMessage("World config settings reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), sMapMgr, and sWorld.
Referenced by GetCommands().
HandleReloadCreatureMovementOverrideCommand()
static bool reload_commandscript::HandleReloadCreatureMovementOverrideCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Creature movement overrides...");
        sObjectMgr->LoadCreatureMovementOverrides();
        handler->SendGlobalGMSysMessage("DB table `creature_movement_override` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadCreatureQuestEnderCommand()
static bool reload_commandscript::HandleReloadCreatureQuestEnderCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Loading Quests Relations... (`creature_questender`)");
        sObjectMgr->LoadCreatureQuestEnders();
        handler->SendGlobalGMSysMessage("DB table `creature_questender` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleReloadCreatureQuestStarterCommand()
static bool reload_commandscript::HandleReloadCreatureQuestStarterCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Loading Quests Relations... (`creature_queststarter`)");
        sObjectMgr->LoadCreatureQuestStarters();
        handler->SendGlobalGMSysMessage("DB table `creature_queststarter` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleReloadCreatureTemplateCommand()
static bool reload_commandscript::HandleReloadCreatureTemplateCommand (ChatHandler * handler, std::string_view args) inline static
    {
        if (args.empty())
            return false;
        for (std::string_view entryStr : Acore::Tokenize(args, ' ', false))
        {
            uint32 entry = Acore::StringTo<uint32>(entryStr).value_or(0);
            WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_CREATURE_TEMPLATE);
            stmt->SetData(0, entry);
            PreparedQueryResult result = WorldDatabase.Query(stmt);
            if (!result)
            {
                handler->PSendSysMessage(LANG_COMMAND_CREATURETEMPLATE_NOTFOUND, entry);
                continue;
            }
            CreatureTemplate* cInfo = const_cast<CreatureTemplate*>(sObjectMgr->GetCreatureTemplate(entry));
            if (!cInfo)
            {
                handler->PSendSysMessage(LANG_COMMAND_CREATURESTORAGE_NOTFOUND, entry);
                continue;
            }
            LOG_INFO("server.loading", "Reloading creature template entry {}", entry);
            Field* fields = result->Fetch();
            sObjectMgr->LoadCreatureTemplate(fields, true);
            sObjectMgr->CheckCreatureTemplate(cInfo);
        }
        handler->SendGlobalGMSysMessage("Creature template reloaded.");
        return true;
    }
References LANG_COMMAND_CREATURESTORAGE_NOTFOUND, LANG_COMMAND_CREATURETEMPLATE_NOTFOUND, LOG_INFO, ChatHandler::PSendSysMessage(), ChatHandler::SendGlobalGMSysMessage(), PreparedStatementBase::SetData(), sObjectMgr, Acore::Tokenize(), WORLD_SEL_CREATURE_TEMPLATE, and WorldDatabase.
Referenced by GetCommands().
HandleReloadCreatureText()
static bool reload_commandscript::HandleReloadCreatureText (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Creature Texts...");
        sCreatureTextMgr->LoadCreatureTexts();
        handler->SendGlobalGMSysMessage("Creature Texts reloaded.");
        return true;
    }
References LOG_INFO, sCreatureTextMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadDisablesCommand()
static bool reload_commandscript::HandleReloadDisablesCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading disables table...");
        DisableMgr::LoadDisables();
        LOG_INFO("server.loading", "Checking quest disables...");
        DisableMgr::CheckQuestDisables();
        handler->SendGlobalGMSysMessage("DB table `disables` reloaded.");
        return true;
    }
References DisableMgr::CheckQuestDisables(), DisableMgr::LoadDisables(), LOG_INFO, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadDungeonAccessCommand()
static bool reload_commandscript::HandleReloadDungeonAccessCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Dungeon Access Requirement definitions...");
        sObjectMgr->LoadAccessRequirements();
        handler->SendGlobalGMSysMessage("DB tables `dungeon_access_template` AND `dungeon_access_requirements` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadEventScriptsCommand()
static bool reload_commandscript::HandleReloadEventScriptsCommand (ChatHandler * handler) inline static
    {
        if (sScriptMgr->IsScriptScheduled())
        {
            handler->SendErrorMessage("DB scripts used currently, please attempt reload later.");
            return false;
        }
        LOG_INFO("server.loading", "Reloading Scripts from `event_scripts`...");
        sObjectMgr->LoadEventScripts();
        handler->SendGlobalGMSysMessage("DB table `event_scripts` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendErrorMessage(), ChatHandler::SendGlobalGMSysMessage(), sObjectMgr, and sScriptMgr.
Referenced by GetCommands(), and HandleReloadAllScriptsCommand().
HandleReloadGameEventNPCVendorCommand()
static bool reload_commandscript::HandleReloadGameEventNPCVendorCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading `game_event_npc_vendor` Table!");
        sGameEventMgr->LoadEventVendors();
        handler->SendGlobalGMSysMessage("DB table `game_event_npc_vendor` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sGameEventMgr.
Referenced by GetCommands().
HandleReloadGameGraveyardCommand()
static bool reload_commandscript::HandleReloadGameGraveyardCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading game_graveyard table...");
        sGraveyard->LoadGraveyardFromDB();
        handler->SendGlobalGMSysMessage("DB table `game_graveyard` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sGraveyard.
Referenced by GetCommands().
HandleReloadGameGraveyardZoneCommand()
static bool reload_commandscript::HandleReloadGameGraveyardZoneCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Graveyard-zone links...");
        sGraveyard->LoadGraveyardZones();
        handler->SendGlobalGMSysMessage("DB table `graveyard_zone` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sGraveyard.
Referenced by GetCommands(), and HandleReloadAllAreaCommand().
HandleReloadGameTeleCommand()
static bool reload_commandscript::HandleReloadGameTeleCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Game Tele coordinates...");
        sObjectMgr->LoadGameTele();
        handler->SendGlobalGMSysMessage("DB table `game_tele` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadGMTicketsCommand()
static bool reload_commandscript::HandleReloadGMTicketsCommand (ChatHandler *) inline static
    {
        sTicketMgr->LoadTickets();
        return true;
    }
References sTicketMgr.
Referenced by GetCommands().
HandleReloadGOQuestEnderCommand()
static bool reload_commandscript::HandleReloadGOQuestEnderCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Loading Quests Relations... (`gameobject_questender`)");
        sObjectMgr->LoadGameobjectQuestEnders();
        handler->SendGlobalGMSysMessage("DB table `gameobject_questender` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleReloadGOQuestStarterCommand()
static bool reload_commandscript::HandleReloadGOQuestStarterCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Loading Quests Relations... (`gameobject_queststarter`)");
        sObjectMgr->LoadGameobjectQuestStarters();
        handler->SendGlobalGMSysMessage("DB table `gameobject_queststarter` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleReloadGossipMenuCommand()
static bool reload_commandscript::HandleReloadGossipMenuCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading `gossip_menu` Table!");
        sObjectMgr->LoadGossipMenu();
        handler->SendGlobalGMSysMessage("DB table `gossip_menu` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LOG_INFO, sConditionMgr, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllGossipsCommand().
HandleReloadGossipMenuOptionCommand()
static bool reload_commandscript::HandleReloadGossipMenuOptionCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading `gossip_menu_option` Table!");
        sObjectMgr->LoadGossipMenuItems();
        handler->SendGlobalGMSysMessage("DB table `gossip_menu_option` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LOG_INFO, sConditionMgr, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllGossipsCommand().
HandleReloadItemEnchantementsCommand()
static bool reload_commandscript::HandleReloadItemEnchantementsCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Item Random Enchantments Table...");
        LoadRandomEnchantmentsTable();
        handler->SendGlobalGMSysMessage("DB table `item_enchantment_template` reloaded.");
        return true;
    }
References LoadRandomEnchantmentsTable(), LOG_INFO, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands(), and HandleReloadAllItemCommand().
HandleReloadItemSetNamesCommand()
static bool reload_commandscript::HandleReloadItemSetNamesCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Item set names...");
        sObjectMgr->LoadItemSetNames();
        handler->SendGlobalGMSysMessage("DB table `item_set_names` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleReloadLfgRewardsCommand()
static bool reload_commandscript::HandleReloadLfgRewardsCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading lfg dungeon rewards...");
        sLFGMgr->LoadRewards();
        handler->SendGlobalGMSysMessage("DB table `lfg_dungeon_rewards` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sLFGMgr.
Referenced by GetCommands().
HandleReloadLinkedRespawnCommand()
static bool reload_commandscript::HandleReloadLinkedRespawnCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Loading Linked Respawns... (`creature_linked_respawn`)");
        sObjectMgr->LoadLinkedRespawn();
        handler->SendGlobalGMSysMessage("DB table `creature_linked_respawn` (creature linked respawns) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleReloadLocalesAchievementRewardCommand()
static bool reload_commandscript::HandleReloadLocalesAchievementRewardCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Achievement Reward Data Locale...");
        sAchievementMgr->LoadRewardLocales();
        handler->SendGlobalGMSysMessage("DB table `achievement_reward_locale` reloaded.");
        return true;
    }
References LOG_INFO, sAchievementMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesCreatureCommand()
static bool reload_commandscript::HandleReloadLocalesCreatureCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Creature Template Locale...");
        sObjectMgr->LoadCreatureLocales();
        handler->SendGlobalGMSysMessage("DB table `creature_template_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesCreatureTextCommand()
static bool reload_commandscript::HandleReloadLocalesCreatureTextCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Creature Texts Locale...");
        sCreatureTextMgr->LoadCreatureTextLocales();
        handler->SendGlobalGMSysMessage("DB table `creature_text_locale` reloaded.");
        return true;
    }
References LOG_INFO, sCreatureTextMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesGameobjectCommand()
static bool reload_commandscript::HandleReloadLocalesGameobjectCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Gameobject Template Locale ... ");
        sObjectMgr->LoadGameObjectLocales();
        handler->SendGlobalGMSysMessage("DB table `gameobject_template_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesGossipMenuOptionCommand()
static bool reload_commandscript::HandleReloadLocalesGossipMenuOptionCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Gossip Menu Option Locale ... ");
        sObjectMgr->LoadGossipMenuItemsLocales();
        handler->SendGlobalGMSysMessage("DB table `gossip_menu_option_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesItemCommand()
static bool reload_commandscript::HandleReloadLocalesItemCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Item Template Locale ... ");
        sObjectMgr->LoadItemLocales();
        handler->SendGlobalGMSysMessage("DB table `item_template_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesItemSetNameCommand()
static bool reload_commandscript::HandleReloadLocalesItemSetNameCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Item set name Locale... ");
        sObjectMgr->LoadItemSetNameLocales();
        handler->SendGlobalGMSysMessage("DB table `item_set_name_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleReloadLocalesNpcTextCommand()
static bool reload_commandscript::HandleReloadLocalesNpcTextCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading NPC Text Locale ... ");
        sObjectMgr->LoadNpcTextLocales();
        handler->SendGlobalGMSysMessage("DB table `npc_text_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesPageTextCommand()
static bool reload_commandscript::HandleReloadLocalesPageTextCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Page Text Locale ... ");
        sObjectMgr->LoadPageTextLocales();
        handler->SendGlobalGMSysMessage("DB table `page_text_locale` reloaded.");
        handler->SendGlobalGMSysMessage("You need to delete your client cache or change the cache number in config in order for your players see the changes.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesPointsOfInterestCommand()
static bool reload_commandscript::HandleReloadLocalesPointsOfInterestCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Points Of Interest Locale ... ");
        sObjectMgr->LoadPointOfInterestLocales();
        handler->SendGlobalGMSysMessage("DB table `points_of_interest_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesQuestCommand()
static bool reload_commandscript::HandleReloadLocalesQuestCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Locales Quest ... ");
        sObjectMgr->LoadQuestLocales();
        handler->SendGlobalGMSysMessage("DB table `quest_template_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesQuestOfferRewardCommand()
static bool reload_commandscript::HandleReloadLocalesQuestOfferRewardCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Quest Offer Reward Locale... ");
        sObjectMgr->LoadQuestOfferRewardLocale();
        handler->SendGlobalGMSysMessage("DB table `quest_offer_reward_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesQuestRequestItemsCommand()
static bool reload_commandscript::HandleReloadLocalesQuestRequestItemsCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Quest Request Item Locale... ");
        sObjectMgr->LoadQuestRequestItemsLocale();
        handler->SendGlobalGMSysMessage("DB table `quest_request_item_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllLocalesCommand().
HandleReloadLootTemplatesCreatureCommand()
static bool reload_commandscript::HandleReloadLootTemplatesCreatureCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`creature_loot_template`)");
        LoadLootTemplates_Creature();
        LootTemplates_Creature.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `creature_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Creature(), LOG_INFO, LootTemplates_Creature, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesDisenchantCommand()
static bool reload_commandscript::HandleReloadLootTemplatesDisenchantCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`disenchant_loot_template`)");
        LoadLootTemplates_Disenchant();
        LootTemplates_Disenchant.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `disenchant_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Disenchant(), LOG_INFO, LootTemplates_Disenchant, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesFishingCommand()
static bool reload_commandscript::HandleReloadLootTemplatesFishingCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`fishing_loot_template`)");
        LoadLootTemplates_Fishing();
        LootTemplates_Fishing.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `fishing_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Fishing(), LOG_INFO, LootTemplates_Fishing, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesGameobjectCommand()
static bool reload_commandscript::HandleReloadLootTemplatesGameobjectCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`gameobject_loot_template`)");
        LoadLootTemplates_Gameobject();
        LootTemplates_Gameobject.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `gameobject_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Gameobject(), LOG_INFO, LootTemplates_Gameobject, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesItemCommand()
static bool reload_commandscript::HandleReloadLootTemplatesItemCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`item_loot_template`)");
        LoadLootTemplates_Item();
        LootTemplates_Item.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `item_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Item(), LOG_INFO, LootTemplates_Item, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesMailCommand()
static bool reload_commandscript::HandleReloadLootTemplatesMailCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`mail_loot_template`)");
        LoadLootTemplates_Mail();
        LootTemplates_Mail.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `mail_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Mail(), LOG_INFO, LootTemplates_Mail, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesMillingCommand()
static bool reload_commandscript::HandleReloadLootTemplatesMillingCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`milling_loot_template`)");
        LoadLootTemplates_Milling();
        LootTemplates_Milling.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `milling_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Milling(), LOG_INFO, LootTemplates_Milling, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesPickpocketingCommand()
static bool reload_commandscript::HandleReloadLootTemplatesPickpocketingCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`pickpocketing_loot_template`)");
        LoadLootTemplates_Pickpocketing();
        LootTemplates_Pickpocketing.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `pickpocketing_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Pickpocketing(), LOG_INFO, LootTemplates_Pickpocketing, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesPlayerCommand()
static bool reload_commandscript::HandleReloadLootTemplatesPlayerCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`player_loot_template`)");
        LoadLootTemplates_Player();
        LootTemplates_Player.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `player_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Player(), LOG_INFO, LootTemplates_Player, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesProspectingCommand()
static bool reload_commandscript::HandleReloadLootTemplatesProspectingCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`prospecting_loot_template`)");
        LoadLootTemplates_Prospecting();
        LootTemplates_Prospecting.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `prospecting_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Prospecting(), LOG_INFO, LootTemplates_Prospecting, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesReferenceCommand()
static bool reload_commandscript::HandleReloadLootTemplatesReferenceCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`reference_loot_template`)");
        LoadLootTemplates_Reference();
        handler->SendGlobalGMSysMessage("DB table `reference_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LoadLootTemplates_Reference(), LOG_INFO, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesSkinningCommand()
static bool reload_commandscript::HandleReloadLootTemplatesSkinningCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`skinning_loot_template`)");
        LoadLootTemplates_Skinning();
        LootTemplates_Skinning.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `skinning_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Skinning(), LOG_INFO, LootTemplates_Skinning, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadLootTemplatesSpellCommand()
static bool reload_commandscript::HandleReloadLootTemplatesSpellCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Loot Tables... (`spell_loot_template`)");
        LoadLootTemplates_Spell();
        LootTemplates_Spell.CheckLootRefs();
        handler->SendGlobalGMSysMessage("DB table `spell_loot_template` reloaded.");
        sConditionMgr->LoadConditions(true);
        return true;
    }
References LootStore::CheckLootRefs(), LoadLootTemplates_Spell(), LOG_INFO, LootTemplates_Spell, sConditionMgr, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands().
HandleReloadMailLevelRewardCommand()
static bool reload_commandscript::HandleReloadMailLevelRewardCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Player level dependent mail rewards...");
        sObjectMgr->LoadMailLevelRewards();
        handler->SendGlobalGMSysMessage("DB table `mail_level_reward` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadMailServerTemplateCommand()
static bool reload_commandscript::HandleReloadMailServerTemplateCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading `server_mail_template` table");
        sObjectMgr->LoadMailServerTemplates();
        handler->SendGlobalGMSysMessage("DB table `server_mail_template` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadModuleStringCommand()
static bool reload_commandscript::HandleReloadModuleStringCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading module_string Table!");
        sObjectMgr->LoadModuleStrings();
        handler->SendGlobalGMSysMessage("DB table `module_string` reloaded.");
        LOG_INFO("server.loading", "Reloading module_string_locale Table!");
        sObjectMgr->LoadModuleStringsLocale();
        handler->SendGlobalGMSysMessage("DB table `module_string_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleReloadMotdCommand()
static bool reload_commandscript::HandleReloadMotdCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Motd...");
        sMotdMgr->LoadMotd();
        handler->SendGlobalGMSysMessage("DB table `motd` reloaded.");
        LocaleConstant locale = DEFAULT_LOCALE;
        if (Player* player = handler->GetPlayer())
            locale = player->GetSession()->GetSessionDbLocaleIndex();
        handler->SendGlobalSysMessage(sMotdMgr->GetMotd(locale));
        return true;
    }
References DEFAULT_LOCALE, ChatHandler::GetPlayer(), LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendGlobalSysMessage(), and sMotdMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadNpcTrainerCommand()
static bool reload_commandscript::HandleReloadNpcTrainerCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading `npc_trainer` Table!");
        sObjectMgr->LoadTrainerSpell();
        handler->SendGlobalGMSysMessage("DB table `npc_trainer` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllNpcCommand().
HandleReloadNpcVendorCommand()
static bool reload_commandscript::HandleReloadNpcVendorCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading `npc_vendor` Table!");
        sObjectMgr->LoadVendors();
        handler->SendGlobalGMSysMessage("DB table `npc_vendor` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllNpcCommand().
HandleReloadOnKillReputationCommand()
static bool reload_commandscript::HandleReloadOnKillReputationCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading creature award reputation definitions...");
        sObjectMgr->LoadReputationOnKill();
        handler->SendGlobalGMSysMessage("DB table `creature_onkill_reputation` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleReloadPageTextsCommand()
static bool reload_commandscript::HandleReloadPageTextsCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Page Texts...");
        sObjectMgr->LoadPageTexts();
        handler->SendGlobalGMSysMessage("DB table `page_texts` reloaded.");
        handler->SendGlobalGMSysMessage("You need to delete your client cache or change the cache number in config in order for your players see the changes.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllItemCommand().
HandleReloadPointsOfInterestCommand()
static bool reload_commandscript::HandleReloadPointsOfInterestCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading `points_of_interest` Table!");
        sObjectMgr->LoadPointsOfInterest();
        handler->SendGlobalGMSysMessage("DB table `points_of_interest` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), HandleReloadAllGossipsCommand(), and HandleReloadAllNpcCommand().
HandleReloadProfanityNameCommand()
static bool reload_commandscript::HandleReloadProfanityNameCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Profanity Names!");
        sObjectMgr->LoadProfanityNamesFromDB();
        sObjectMgr->LoadProfanityNamesFromDBC(); // Needed because we clear the store in LoadProfanityNamesFromDB()
        handler->SendGlobalGMSysMessage("Profanity Names reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadQuestAreaTriggersCommand()
static bool reload_commandscript::HandleReloadQuestAreaTriggersCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Quest Area Triggers...");
        sObjectMgr->LoadQuestAreaTriggers();
        handler->SendGlobalGMSysMessage("DB table `areatrigger_involvedrelation` (quest area triggers) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllQuestCommand().
HandleReloadQuestGreetingCommand()
static bool reload_commandscript::HandleReloadQuestGreetingCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Quest Greeting ...");
        sObjectMgr->LoadQuestGreetings();
        handler->SendGlobalGMSysMessage("DB table `quest_greeting` reloaded.");
        LOG_INFO("server.loading", "Reloading Quest Greeting locales...");
        sObjectMgr->LoadQuestGreetingsLocales(); // Must be after LoadQuestGreetings()
        handler->SendGlobalGMSysMessage("DB table `quest_greeting_locale` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllQuestCommand().
HandleReloadQuestPOICommand()
static bool reload_commandscript::HandleReloadQuestPOICommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Quest POI ..." );
        sObjectMgr->LoadQuestPOI();
        handler->SendGlobalGMSysMessage("DB Table `quest_poi` and `quest_poi_points` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllQuestCommand().
HandleReloadQuestTemplateCommand()
static bool reload_commandscript::HandleReloadQuestTemplateCommand (ChatHandler * handler) inline static
dependent also from gameobject but this table not reloaded anyway
    {
        LOG_INFO("server.loading", "Reloading Quest Templates...");
        sObjectMgr->LoadQuests();
        handler->SendGlobalGMSysMessage("DB table `quest_template` (quest definitions) reloaded.");
        LOG_INFO("server.loading", "Reloading GameObjects for quests...");
        sObjectMgr->LoadGameObjectForQuests();
        handler->SendGlobalGMSysMessage("Data GameObjects for quests reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllQuestCommand().
HandleReloadReputationRewardRateCommand()
static bool reload_commandscript::HandleReloadReputationRewardRateCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading `reputation_reward_rate` Table!" );
        sObjectMgr->LoadReputationRewardRate();
        handler->SendGlobalGMSysMessage("DB table `reputation_reward_rate` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleReloadReputationSpilloverTemplateCommand()
static bool reload_commandscript::HandleReloadReputationSpilloverTemplateCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading `reputation_spillover_template` Table!" );
        sObjectMgr->LoadReputationSpilloverTemplate();
        handler->SendGlobalGMSysMessage("DB table `reputation_spillover_template` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
HandleReloadReservedNameCommand()
static bool reload_commandscript::HandleReloadReservedNameCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Reserved Names!");
        sObjectMgr->LoadReservedPlayerNamesDB();
        sObjectMgr->LoadReservedPlayerNamesDBC(); // Needed because we clear the store in LoadReservedPlayerNamesDB()
        handler->SendGlobalGMSysMessage("Reserved Names reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadSkillDiscoveryTemplateCommand()
static bool reload_commandscript::HandleReloadSkillDiscoveryTemplateCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Skill Discovery Table...");
        LoadSkillDiscoveryTable();
        handler->SendGlobalGMSysMessage("DB table `skill_discovery_template` (recipes discovered at crafting) reloaded.");
        return true;
    }
References LoadSkillDiscoveryTable(), LOG_INFO, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSkillExtraItemTemplateCommand()
static bool reload_commandscript::HandleReloadSkillExtraItemTemplateCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Skill Extra Item Table...");
        LoadSkillExtraItemTable();
        handler->SendGlobalGMSysMessage("DB table `skill_extra_item_template` (extra item creation when crafting) reloaded.");
        return HandleReloadSkillPerfectItemTemplateCommand(handler);
    }
References HandleReloadSkillPerfectItemTemplateCommand(), LoadSkillExtraItemTable(), LOG_INFO, and ChatHandler::SendGlobalGMSysMessage().
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSkillFishingBaseLevelCommand()
static bool reload_commandscript::HandleReloadSkillFishingBaseLevelCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Skill Fishing base level requirements...");
        sObjectMgr->LoadFishingBaseSkillLevel();
        handler->SendGlobalGMSysMessage("DB table `skill_fishing_base_level` (fishing base level for zone/subzone) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadSkillPerfectItemTemplateCommand()
static bool reload_commandscript::HandleReloadSkillPerfectItemTemplateCommand (ChatHandler * handler) inline static
    {
        // latched onto HandleReloadSkillExtraItemTemplateCommand as it's part of that table group (and i don't want to chance all the command IDs)
        LOG_INFO("server.loading", "Reloading Skill Perfection Data Table...");
        LoadSkillPerfectItemTable();
        handler->SendGlobalGMSysMessage("DB table `skill_perfect_item_template` (perfect item procs when crafting) reloaded.");
        return true;
    }
References LoadSkillPerfectItemTable(), LOG_INFO, and ChatHandler::SendGlobalGMSysMessage().
Referenced by HandleReloadSkillExtraItemTemplateCommand().
HandleReloadSmartScripts()
static bool reload_commandscript::HandleReloadSmartScripts (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Smart Scripts...");
        sSmartScriptMgr->LoadSmartAIFromDB();
        handler->SendGlobalGMSysMessage("Smart Scripts reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSmartScriptMgr.
Referenced by GetCommands().
HandleReloadSpellAreaCommand()
static bool reload_commandscript::HandleReloadSpellAreaCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading SpellArea Data...");
        sSpellMgr->LoadSpellAreas();
        handler->SendGlobalGMSysMessage("DB table `spell_area` (spell dependences from area/quest/auras state) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSpellBonusesCommand()
static bool reload_commandscript::HandleReloadSpellBonusesCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Spell Bonus Data...");
        sSpellMgr->LoadSpellBonuses();
        handler->SendGlobalGMSysMessage("DB table `spell_bonus_data` (spell damage/healing coefficients) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSpellClickSpellsCommand()
static bool reload_commandscript::HandleReloadSpellClickSpellsCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading `npc_spellclick_spells` Table!");
        sObjectMgr->LoadNPCSpellClickSpells();
        handler->SendGlobalGMSysMessage("DB table `npc_spellclick_spells` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllNpcCommand().
HandleReloadSpellGroupsCommand()
static bool reload_commandscript::HandleReloadSpellGroupsCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Spell Groups...");
        sSpellMgr->LoadSpellGroups();
        handler->SendGlobalGMSysMessage("DB table `spell_group` (spell groups) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSpellGroupStackRulesCommand()
static bool reload_commandscript::HandleReloadSpellGroupStackRulesCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Spell Group Stack Rules...");
        sSpellMgr->LoadSpellGroupStackRules();
        handler->SendGlobalGMSysMessage("DB table `spell_group_stack_rules` (spell stacking definitions) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSpellLinkedSpellCommand()
static bool reload_commandscript::HandleReloadSpellLinkedSpellCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Spell Linked Spells...");
        sSpellMgr->LoadSpellLinked();
        handler->SendGlobalGMSysMessage("DB table `spell_linked_spell` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSpellPetAurasCommand()
static bool reload_commandscript::HandleReloadSpellPetAurasCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Spell pet auras...");
        sSpellMgr->LoadSpellPetAuras();
        handler->SendGlobalGMSysMessage("DB table `spell_pet_auras` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSpellProcEventCommand()
static bool reload_commandscript::HandleReloadSpellProcEventCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Spell Proc Event conditions...");
        sSpellMgr->LoadSpellProcEvents();
        handler->SendGlobalGMSysMessage("DB table `spell_proc_event` (spell proc trigger requirements) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSpellProcsCommand()
static bool reload_commandscript::HandleReloadSpellProcsCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Spell Proc conditions and data...");
        sSpellMgr->LoadSpellProcs();
        handler->SendGlobalGMSysMessage("DB table `spell_proc` (spell proc conditions and data) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSpellRequiredCommand()
static bool reload_commandscript::HandleReloadSpellRequiredCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Spell Required Data... ");
        sSpellMgr->LoadSpellRequired();
        handler->SendGlobalGMSysMessage("DB table `spell_required` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSpellScriptsCommand()
static bool reload_commandscript::HandleReloadSpellScriptsCommand (ChatHandler * handler) inline static
    {
        if (sScriptMgr->IsScriptScheduled())
        {
            handler->SendErrorMessage("DB scripts used currently, please attempt reload later.");
            return false;
        }
        LOG_INFO("server.loading", "Reloading Scripts from `spell_scripts`...");
        sObjectMgr->LoadSpellScripts();
        handler->SendGlobalGMSysMessage("DB table `spell_scripts` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendErrorMessage(), ChatHandler::SendGlobalGMSysMessage(), sObjectMgr, and sScriptMgr.
Referenced by GetCommands(), and HandleReloadAllScriptsCommand().
HandleReloadSpellTargetPositionCommand()
static bool reload_commandscript::HandleReloadSpellTargetPositionCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Spell target coordinates...");
        sSpellMgr->LoadSpellTargetPositions();
        handler->SendGlobalGMSysMessage("DB table `spell_target_position` (destination coordinates for spell targets) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadSpellThreatsCommand()
static bool reload_commandscript::HandleReloadSpellThreatsCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Aggro Spells Definitions...");
        sSpellMgr->LoadSpellThreats();
        handler->SendGlobalGMSysMessage("DB table `spell_threat` (spell aggro definitions) reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sSpellMgr.
Referenced by GetCommands(), and HandleReloadAllSpellCommand().
HandleReloadVehicleAccessoryCommand()
static bool reload_commandscript::HandleReloadVehicleAccessoryCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading vehicle_accessory table...");
        sObjectMgr->LoadVehicleAccessories();
        handler->SendGlobalGMSysMessage("Vehicle accessories reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadVehicleTemplateAccessoryCommand()
static bool reload_commandscript::HandleReloadVehicleTemplateAccessoryCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading vehicle_template_accessory table...");
        sObjectMgr->LoadVehicleTemplateAccessories();
        handler->SendGlobalGMSysMessage("Vehicle template accessories reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sObjectMgr.
Referenced by GetCommands(), and HandleReloadAllCommand().
HandleReloadWardenactionCommand()
static bool reload_commandscript::HandleReloadWardenactionCommand (ChatHandler * handler) inline static
    {
        if (!sWorld->getBoolConfig(CONFIG_WARDEN_ENABLED))
        {
            handler->SendErrorMessage("Warden system disabled by config - reloading warden_action skipped.");
            return false;
        }
        LOG_INFO("server.loading", "Reloading warden_action Table!");
        sWardenCheckMgr->LoadWardenOverrides();
        handler->SendGlobalGMSysMessage("DB table `warden_action` reloaded.");
        return true;
    }
References CONFIG_WARDEN_ENABLED, LOG_INFO, ChatHandler::SendErrorMessage(), ChatHandler::SendGlobalGMSysMessage(), sWardenCheckMgr, and sWorld.
Referenced by GetCommands().
HandleReloadWpCommand()
static bool reload_commandscript::HandleReloadWpCommand (ChatHandler * handler) inline static
    {
        LOG_INFO("server.loading", "Reloading Waypoints data from 'waypoints_data'");
        sWaypointMgr->Load();
        handler->SendGlobalGMSysMessage("DB Table 'waypoint_data' reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendGlobalGMSysMessage(), and sWaypointMgr.
Referenced by GetCommands(), and HandleReloadAllScriptsCommand().
HandleReloadWpScriptsCommand()
static bool reload_commandscript::HandleReloadWpScriptsCommand (ChatHandler * handler) inline static
    {
        if (sScriptMgr->IsScriptScheduled())
        {
            handler->SendErrorMessage("DB scripts used currently, please attempt reload later.");
            return false;
        }
        LOG_INFO("server.loading", "Reloading Scripts from `waypoint_scripts`...");
        sObjectMgr->LoadWaypointScripts();
        handler->SendGlobalGMSysMessage("DB table `waypoint_scripts` reloaded.");
        return true;
    }
References LOG_INFO, ChatHandler::SendErrorMessage(), ChatHandler::SendGlobalGMSysMessage(), sObjectMgr, and sScriptMgr.
Referenced by GetCommands(), and HandleReloadAllScriptsCommand().