AzerothCore: BattlegroundQueue::SelectionPool Class Reference
BattlegroundQueue::SelectionPool Class Reference
#include "BattlegroundQueue.h"
Public Member Functions
SelectionPool ()
void Init ()
bool AddGroup (GroupQueueInfo *ginfo, uint32 desiredCount)
bool KickGroup (uint32 size)
uint32 GetPlayerCount () const
Public Attributes
GroupsQueueType SelectedGroups
Private Attributes
uint32 PlayerCount
Detailed Description
Constructor & Destructor Documentation
SelectionPool()
BattlegroundQueue::SelectionPool::SelectionPool () inline
: PlayerCount(0) {};
Member Function Documentation
AddGroup()
bool BattlegroundQueue::SelectionPool::AddGroup (GroupQueueInfo * ginfo, uint32 desiredCount)
{
    // add if we don't exceed desiredCount
    if (!ginfo->IsInvitedToBGInstanceGUID && desiredCount >= PlayerCount + ginfo->Players.size())
    {
        SelectedGroups.push_back(ginfo);
        PlayerCount += ginfo->Players.size();
        return true;
    }
    return PlayerCount < desiredCount;
}
References GroupQueueInfo::IsInvitedToBGInstanceGUID, and GroupQueueInfo::Players.
Referenced by BattlegroundQueue::CheckNormalMatch(), BattlegroundQueue::CheckPremadeMatch(), BattlegroundQueue::CheckSkirmishForSameFaction(), and BattlegroundQueue::FillPlayersToBG().
GetPlayerCount()
uint32 BattlegroundQueue::SelectionPool::GetPlayerCount () const inline
{ return PlayerCount; }
References PlayerCount.
Referenced by BattlegroundQueue::CheckNormalMatch().
Init()
void BattlegroundQueue::SelectionPool::Init ()
{
    SelectedGroups.clear();
    PlayerCount = 0;
}
References PlayerCount, and SelectedGroups.
Referenced by BattlegroundQueue::BattlegroundQueueUpdate(), and BattlegroundQueue::CheckSkirmishForSameFaction().
KickGroup()
bool BattlegroundQueue::SelectionPool::KickGroup (uint32 size)
{
    if (SelectedGroups.empty())
        return false;
    // find last group with proper size or largest
    bool foundProper = false;
    GroupQueueInfo* groupToKick{ SelectedGroups.front() };
    for (auto const& gInfo : SelectedGroups)
    {
        // if proper size - overwrite to kick last one
        if (std::abs(int32(gInfo->Players.size()) - (int32)size) <= 1)
        {
            groupToKick = gInfo;
            foundProper = true;
        }
        else if (!foundProper && gInfo->Players.size() >= groupToKick->Players.size())
            groupToKick = gInfo;
    }
    // remove selected from pool
    auto playersCountInGroup{ groupToKick->Players.size() };
    PlayerCount -= playersCountInGroup;
    std::erase(SelectedGroups, groupToKick);
    if (foundProper)
        return false;
    return playersCountInGroup > size;
}
References GroupQueueInfo::Players.
Referenced by BattlegroundQueue::FillPlayersToBG().
Member Data Documentation
PlayerCount
uint32 BattlegroundQueue::SelectionPool::PlayerCount private
Referenced by GetPlayerCount(), and Init().
SelectedGroups
GroupsQueueType BattlegroundQueue::SelectionPool::SelectedGroups
Referenced by BattlegroundQueue::CheckSkirmishForSameFaction(), and Init().