AzeorthCore: Acore::Impl::GenericHMAC< HashCreator, DigestLength > Class Template Reference
Acore::Impl::GenericHMAC< HashCreator, DigestLength > Class Template Reference
#include "HMAC.h"
Public Types
using Digest = std::array< uint8, DIGEST_LENGTH >
Public Member Functions
GenericHMAC (uint8 const *seed, size_t len)
template<typename Container >
GenericHMAC (Container const &container)
~GenericHMAC ()
void UpdateData (uint8 const *data, size_t len)
void UpdateData (std::string_view str)
void UpdateData (std::string const &str)
void UpdateData (char const *str)
template<typename Container >
void UpdateData (Container const &c)
void Finalize ()
Digest const & GetDigest () const
Static Public Member Functions
template<typename Container >
static Digest GetDigestOf (Container const &seed, uint8 const *data, size_t len)
template<typename Container , typename... Ts>
static auto GetDigestOf (Container const &seed, Ts &&... pack) -> std::enable_if_t< !(std::is_integral_v< std::decay_t< Ts > >||...), Digest >
Static Public Attributes
static constexpr size_t DIGEST_LENGTH = DigestLength
Private Attributes
HMAC_CTX * _ctx
Digest _digest = { }
Detailed Description
template<HMACImpl::HashCreator HashCreator, size_t DigestLength>
class Acore::Impl::GenericHMAC< HashCreator, DigestLength >
Member Typedef Documentation
Digest
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> using Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Digest = std::array<uint8, DIGEST_LENGTH>
Constructor & Destructor Documentation
GenericHMAC() [1/2]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC (uint8 const * seed, size_t len) inline
                                                   : _ctx(HMACImpl::MakeCTX())
        {
            int result = HMAC_Init_ex(_ctx, seed, len, HashCreator(), nullptr);
            ASSERT(result == 1);
        }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, and ASSERT.
GenericHMAC() [2/2]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> template<typename Container > Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC (Container const & container) inline
: GenericHMAC(std::data(container), std::size(container)) {}
~GenericHMAC()
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> Acore::Impl::GenericHMAC< HashCreator, DigestLength >::~GenericHMAC () inline
        {
            if (!_ctx)
            {
                return;
            }
            HMACImpl::DestroyCTX(_ctx);
            _ctx = nullptr;
        }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, and Acore::Impl::HMACImpl::DestroyCTX().
Member Function Documentation
Finalize()
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize () inline
        {
            uint32 length = 0;
            int result = HMAC_Final(_ctx, _digest.data(), &length);
            ASSERT(result == 1);
            ASSERT(length == DIGEST_LENGTH);
            HMACImpl::DestroyCTX(_ctx);
            _ctx = nullptr;
        }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest, ASSERT, Acore::Impl::HMACImpl::DestroyCTX(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::DIGEST_LENGTH.
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf().
GetDigest()
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> Digest const & Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigest () const inline
{ return _digest; }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest.
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf().
GetDigestOf() [1/2]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> template<typename Container , typename... Ts> static auto Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf (Container const & seed, Ts &&... pack) -> std::enable_if_t < !(std::is_integral_v<std::decay_t<Ts>> || ...), Digest > inline static
        {
            GenericHMAC hash(seed);
            (hash.UpdateData(std::forward<Ts>(pack)), ...);
            hash.Finalize();
            return hash.GetDigest();
        }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigest(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
GetDigestOf() [2/2]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> template<typename Container > static Digest Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf (Container const & seed, uint8 const * data, size_t len) inline static
        {
            GenericHMAC hash(seed);
            hash.UpdateData(data, len);
            hash.Finalize();
            return hash.GetDigest();
        }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigest(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by AuthCrypt::Init(), and WardenWin::RequestChecks().
UpdateData() [1/5]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (char const * str) inline
{ UpdateData(std::string_view(str)); } /* explicit overload to avoid using the container template */
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [2/5]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> template<typename Container > void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (Container const & c) inline
{ UpdateData(std::data(c), std::size(c)); }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [3/5]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (std::string const & str) inline
{ UpdateData(std::string_view(str)); } /* explicit overload to avoid using the container template */
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [4/5]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (std::string_view str) inline
{ UpdateData(reinterpret_cast<uint8 const*>(str.data()), str.size()); }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [5/5]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (uint8 const * data, size_t len) inline
        {
            int result = HMAC_Update(_ctx, data, len);
            ASSERT(result == 1);
        }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, and ASSERT.
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf().
Member Data Documentation
_ctx
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> HMAC_CTX* Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx private
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::~GenericHMAC().
_digest
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> Digest Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest = { } private
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigest().
DIGEST_LENGTH
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> constexpr size_t Acore::Impl::GenericHMAC< HashCreator, DigestLength >::DIGEST_LENGTH = DigestLength static constexpr
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize().