AzerothCore: boss_prince_valanar_icc::boss_prince_valanarAI Struct Reference
boss_prince_valanar_icc::boss_prince_valanarAI Struct Reference
Public Member Functions
boss_prince_valanarAI (Creature *creature)
void InitializeAI () override
void Reset () override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void JustRespawned () override
void JustReachedHome () override
void JustSummoned (Creature *summon) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void DamageDealt (Unit *target, uint32 &damage, DamageEffectType) override
Called at any Damage to any victim (before damage apply)
void KilledUnit (Unit *victim) override
void SpellHit (Unit *, SpellInfo const *spell) override
void DoAction (int32 action) override
bool CheckRoom ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason why) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
bool _isEmpowered
bool _evading
bool _canDie
uint32 invocationOrder [3]
uint8 currentInvocationIndex
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_prince_valanarAI()
boss_prince_valanar_icc::boss_prince_valanarAI::boss_prince_valanarAI (Creature * creature) inline
                                                  : BossAI(creature, DATA_BLOOD_PRINCE_COUNCIL)
        {
            if (!instance)
            {
                me->IsAIEnabled = false;
                me->AddUnitState(UNIT_STATE_EVADE);
            }
            _canDie = true;
        }
References _canDie, Unit::AddUnitState(), BossAI::instance, Unit::IsAIEnabled, ScriptedAI::me, and UNIT_STATE_EVADE.
Member Function Documentation
CheckRoom()
bool boss_prince_valanar_icc::boss_prince_valanarAI::CheckRoom () inline
        {
            Creature* keleseth = instance->instance->GetCreature(instance->GetGuidData(DATA_PRINCE_KELESETH_GUID));
            Creature* taldaram = instance->instance->GetCreature(instance->GetGuidData(DATA_PRINCE_TALDARAM_GUID));
            if (keleseth && taldaram && IsInBoundary(me) && IsInBoundary(keleseth) && IsInBoundary(taldaram))
                return true;
            EnterEvadeMode(EVADE_REASON_OTHER);
            return false;
        }
References DATA_PRINCE_KELESETH_GUID, DATA_PRINCE_TALDARAM_GUID, EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, Map::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, InstanceScript::instance, CreatureAI::IsInBoundary(), and ScriptedAI::me.
Referenced by UpdateAI().
DamageDealt()
void boss_prince_valanar_icc::boss_prince_valanarAI::DamageDealt (Unit * , uint32 & , DamageEffectType) inline override virtual
Called at any Damage to any victim (before damage apply)
Reimplemented from UnitAI.
        {
            if (!target->IsPlayer())
                return;
            if (damage > RAID_MODE<uint32>(23000, 25000, 23000, 25000))
                instance->SetData(DATA_ORB_WHISPERER_ACHIEVEMENT, 0);
        }
References DATA_ORB_WHISPERER_ACHIEVEMENT, BossAI::instance, Object::IsPlayer(), and ZoneScript::SetData().
DamageTaken()
void boss_prince_valanar_icc::boss_prince_valanarAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
        {
            if (!_isEmpowered)
            {
                if (attacker)
                    me->AddThreat(attacker, float(damage));
                damage = 0;
            }
        }
References _isEmpowered, Unit::AddThreat(), and ScriptedAI::me.
DoAction()
void boss_prince_valanar_icc::boss_prince_valanarAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            switch (action)
            {
                case ACTION_STAND_UP:
                    summons.DespawnEntry(WORLD_TRIGGER);
                    me->RemoveUnitFlag(UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT | UNIT_FLAG_NOT_SELECTABLE);
                    me->SetImmuneToAll(false);
                    me->RemoveDynamicFlag(UNIT_DYNFLAG_DEAD);
                    me->RemoveUnitFlag2(UNIT_FLAG2_FEIGN_DEATH);
                    me->SetReactState(REACT_AGGRESSIVE);
                    me->ForceValuesUpdateAtIndex(UNIT_NPC_FLAGS);   // was in sniff. don't ask why
                    me->m_Events.AddEvent(new StandUpEvent(*me), me->m_Events.CalculateTime(1000));
                    me->SetHealth(me->GetMaxHealth());
                    DoAction(ACTION_CAST_INVOCATION);
                    break;
                case ACTION_CAST_INVOCATION:
                    if (me->IsInCombat())
                        Talk(SAY_VALANAR_INVOCATION);
                    me->CastSpell(me, SPELL_INVOCATION_OF_BLOOD_VALANAR, true);
                    me->CastSpell(me, SPELL_INVOCATION_VISUAL_ACTIVE, true);
                    _isEmpowered = true;
                    break;
                case ACTION_REMOVE_INVOCATION:
                    _isEmpowered = false;
                    me->RemoveAurasDueToSpell(SPELL_INVOCATION_VISUAL_ACTIVE);
                    me->RemoveAurasDueToSpell(SPELL_INVOCATION_OF_BLOOD_VALANAR);
                    break;
                default:
                    break;
            }
        }
References _isEmpowered, ACTION_CAST_INVOCATION, ACTION_REMOVE_INVOCATION, ACTION_STAND_UP, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::CastSpell(), SummonList::DespawnEntry(), DoAction(), Object::ForceValuesUpdateAtIndex(), Unit::GetMaxHealth(), Unit::IsInCombat(), Unit::m_Events, ScriptedAI::me, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Object::RemoveDynamicFlag(), Unit::RemoveUnitFlag(), Unit::RemoveUnitFlag2(), SAY_VALANAR_INVOCATION, Unit::SetHealth(), Unit::SetImmuneToAll(), Creature::SetReactState(), SPELL_INVOCATION_OF_BLOOD_VALANAR, SPELL_INVOCATION_VISUAL_ACTIVE, BossAI::summons, UNIT_DYNFLAG_DEAD, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_NOT_SELECTABLE, UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT, UNIT_NPC_FLAGS, and WORLD_TRIGGER.
Referenced by DoAction(), EnterEvadeMode(), JustEngagedWith(), JustReachedHome(), and SpellHit().
EnterEvadeMode()
void boss_prince_valanar_icc::boss_prince_valanarAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from BossAI.
        {
            if (_evading)
                return;
            _canDie = false;
            me->SetHealth(me->GetMaxHealth());
            DoAction(ACTION_REMOVE_INVOCATION);
            _evading = true;
            if (Creature* keleseth = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_KELESETH_GUID)))
                keleseth->AI()->EnterEvadeMode(why);
            if (Creature* taldaram = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_TALDARAM_GUID)))
                taldaram->AI()->EnterEvadeMode(why);
            BossAI::EnterEvadeMode(why);
            _evading = false;
        }
References _canDie, _evading, ACTION_REMOVE_INVOCATION, DATA_PRINCE_KELESETH_GUID, DATA_PRINCE_TALDARAM_GUID, DoAction(), BossAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMaxHealth(), BossAI::instance, ScriptedAI::me, and Unit::SetHealth().
Referenced by CheckRoom(), JustEngagedWith(), and UpdateAI().
InitializeAI()
void boss_prince_valanar_icc::boss_prince_valanarAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
        {
            ScriptedAI::InitializeAI();
            if (me->IsAlive())
            {
                if (Creature* c = me->SummonCreature(WORLD_TRIGGER, me->GetHomePosition()))
                {
                    c->SetObjectScale(1.75f);
                    c->CastSpell(c, SPELL_FEIGN_DEATH, true);
                }
                me->SetDynamicFlag(UNIT_DYNFLAG_DEAD);
                me->SetUnitFlag2(UNIT_FLAG2_FEIGN_DEATH);
                me->SetImmuneToAll(true);
                me->SetReactState(REACT_PASSIVE);
            }
        }
References Creature::GetHomePosition(), UnitAI::InitializeAI(), Unit::IsAlive(), ScriptedAI::me, REACT_PASSIVE, Object::SetDynamicFlag(), Unit::SetImmuneToAll(), Creature::SetReactState(), Unit::SetUnitFlag2(), SPELL_FEIGN_DEATH, WorldObject::SummonCreature(), UNIT_DYNFLAG_DEAD, UNIT_FLAG2_FEIGN_DEATH, and WORLD_TRIGGER.
JustDied()
void boss_prince_valanar_icc::boss_prince_valanarAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            events.Reset();
            summons.DespawnAll();
            instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
            if (!_canDie)
            {
                me->RemoveCorpse(false);
                me->SetRespawnTime(10);
                me->SaveRespawnTime();
                Position homePos = me->GetHomePosition();
                me->UpdatePosition(homePos);
                me->GetMotionMaster()->Clear(false);
                me->GetMotionMaster()->MoveIdle();
                me->StopMovingOnCurrentPos();
                return;
            }
            Talk(SAY_VALANAR_DEATH);
            instance->SetBossState(DATA_BLOOD_PRINCE_COUNCIL, DONE);
            if (Creature* keleseth = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_KELESETH_GUID)))
                if (keleseth->IsAlive())
                    Unit::Kill(keleseth, keleseth);
            if (Creature* taldaram = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_TALDARAM_GUID)))
                if (taldaram->IsAlive())
                    Unit::Kill(taldaram, taldaram);
        }
References _canDie, MotionMaster::Clear(), DATA_BLOOD_PRINCE_COUNCIL, DATA_PRINCE_KELESETH_GUID, DATA_PRINCE_TALDARAM_GUID, SummonList::DespawnAll(), DONE, ENCOUNTER_FRAME_DISENGAGE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), Unit::GetMotionMaster(), homePos, BossAI::instance, Unit::Kill(), ScriptedAI::me, MotionMaster::MoveIdle(), Creature::RemoveCorpse(), Creature::SaveRespawnTime(), SAY_VALANAR_DEATH, InstanceScript::SendEncounterUnit(), InstanceScript::SetBossState(), Creature::SetRespawnTime(), Unit::StopMovingOnCurrentPos(), BossAI::summons, and Unit::UpdatePosition().
JustEngagedWith()
void boss_prince_valanar_icc::boss_prince_valanarAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            bool valid = true;
            if (Creature* keleseth = instance->instance->GetCreature(instance->GetGuidData(DATA_PRINCE_KELESETH_GUID)))
                if (!keleseth->IsAlive() || keleseth->IsInEvadeMode())
                    valid = false;
            if (Creature* taldaram = instance->instance->GetCreature(instance->GetGuidData(DATA_PRINCE_TALDARAM_GUID)))
                if (!taldaram->IsAlive() || taldaram->IsInEvadeMode())
                    valid = false;
            if (Creature* valanar = instance->instance->GetCreature(instance->GetGuidData(DATA_PRINCE_VALANAR_GUID)))
                if (!valanar->IsAlive() || valanar->IsInEvadeMode())
                    valid = false;
            if (!valid)
            {
                EnterEvadeMode(EVADE_REASON_OTHER);
                return;
            }
            instance->SetBossState(DATA_BLOOD_PRINCE_COUNCIL, IN_PROGRESS);
            instance->SetData(DATA_ORB_WHISPERER_ACHIEVEMENT, 1);
            me->RemoveAurasDueToSpell(SPELL_FEIGN_DEATH); // just in case
            me->setActive(true);
            DoZoneInCombat();
            if (!me->hasLootRecipient())
                me->SetLootRecipient(who);
            me->LowerPlayerDamageReq(me->GetMaxHealth());
            me->SetReactState(REACT_AGGRESSIVE);
            instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, me);
            if (Creature* keleseth = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_KELESETH_GUID)))
                if (!keleseth->IsInEvadeMode())
                    keleseth->SetInCombatWithZone();
            if (Creature* taldaram = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_TALDARAM_GUID)))
                if (!taldaram->IsInEvadeMode())
                    taldaram->SetInCombatWithZone();
            DoAction(ACTION_CAST_INVOCATION);
            currentInvocationIndex = 0;
            invocationOrder[0] = DATA_PRINCE_VALANAR_GUID;
            invocationOrder[1] = RAND(DATA_PRINCE_KELESETH_GUID, DATA_PRINCE_TALDARAM_GUID);
            invocationOrder[2] = DATA_PRINCE_KELESETH_GUID + DATA_PRINCE_TALDARAM_GUID - invocationOrder[1];
            events.ScheduleEvent(EVENT_BERSERK, 10min);
            events.ScheduleEvent(EVENT_KINETIC_BOMB, 18s, 24s);
            events.ScheduleEvent(EVENT_SHOCK_VORTEX, 15s, 20s);
            events.ScheduleEvent(EVENT_INVOCATION_OF_BLOOD, 45s);
            if (IsHeroic())
            {
                me->AddAura(SPELL_SHADOW_PRISON, me);
                me->CastSpell(me, SPELL_SHADOW_PRISON_DUMMY, true);
            }
        }
References ACTION_CAST_INVOCATION, Unit::AddAura(), Unit::CastSpell(), currentInvocationIndex, DATA_BLOOD_PRINCE_COUNCIL, DATA_ORB_WHISPERER_ACHIEVEMENT, DATA_PRINCE_KELESETH_GUID, DATA_PRINCE_TALDARAM_GUID, DATA_PRINCE_VALANAR_GUID, DoAction(), CreatureAI::DoZoneInCombat(), ENCOUNTER_FRAME_ENGAGE, EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_BERSERK, EVENT_INVOCATION_OF_BLOOD, EVENT_KINETIC_BOMB, EVENT_SHOCK_VORTEX, Map::GetCreature(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMaxHealth(), Creature::hasLootRecipient(), IN_PROGRESS, BossAI::instance, InstanceScript::instance, invocationOrder, ScriptedAI::IsHeroic(), Creature::LowerPlayerDamageReq(), ScriptedAI::me, RAND(), REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), InstanceScript::SendEncounterUnit(), WorldObject::setActive(), InstanceScript::SetBossState(), ZoneScript::SetData(), Creature::SetLootRecipient(), Creature::SetReactState(), SPELL_FEIGN_DEATH, SPELL_SHADOW_PRISON, and SPELL_SHADOW_PRISON_DUMMY.
JustReachedHome()
void boss_prince_valanar_icc::boss_prince_valanarAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
        {
            _canDie = true;
            me->setActive(false);
            instance->SetBossState(DATA_BLOOD_PRINCE_COUNCIL, FAIL);
            instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
            me->SetHealth(me->GetMaxHealth());
            DoAction(ACTION_CAST_INVOCATION);
        }
References _canDie, ACTION_CAST_INVOCATION, DATA_BLOOD_PRINCE_COUNCIL, DoAction(), ENCOUNTER_FRAME_DISENGAGE, FAIL, Unit::GetMaxHealth(), BossAI::instance, ScriptedAI::me, InstanceScript::SendEncounterUnit(), WorldObject::setActive(), InstanceScript::SetBossState(), and Unit::SetHealth().
Referenced by JustRespawned().
JustRespawned()
void boss_prince_valanar_icc::boss_prince_valanarAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
        {
            BossAI::JustRespawned();
            JustReachedHome();
        }
References JustReachedHome(), and CreatureAI::JustRespawned().
JustSummoned()
void boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            summons.Summon(summon);
            switch (summon->GetEntry())
            {
                case NPC_KINETIC_BOMB_TARGET:
                    summon->SetReactState(REACT_PASSIVE);
                    summon->CastSpell(summon, SPELL_KINETIC_BOMB, true, nullptr, nullptr, me->GetGUID());
                    break;
                case NPC_SHOCK_VORTEX:
                    summon->m_Events.AddEvent(new ShockVortexExplodeEvent(*summon), summon->m_Events.CalculateTime(4500));
                    break;
                default:
                    break;
            }
        }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::CastSpell(), Object::GetEntry(), Object::GetGUID(), Unit::m_Events, ScriptedAI::me, NPC_KINETIC_BOMB_TARGET, NPC_SHOCK_VORTEX, REACT_PASSIVE, Creature::SetReactState(), SPELL_KINETIC_BOMB, SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_prince_valanar_icc::boss_prince_valanarAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->IsPlayer())
                Talk(SAY_VALANAR_KILL);
        }
References Object::IsPlayer(), and SAY_VALANAR_KILL.
Reset()
void boss_prince_valanar_icc::boss_prince_valanarAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            events.Reset();
            summons.DespawnAll();
            _isEmpowered = false;
            _evading = false;
            me->SetHealth(me->GetMaxHealth());
            me->SetReactState(REACT_AGGRESSIVE);
            instance->SetBossState(DATA_BLOOD_PRINCE_COUNCIL, NOT_STARTED);
        }
References _evading, _isEmpowered, DATA_BLOOD_PRINCE_COUNCIL, SummonList::DespawnAll(), Unit::GetMaxHealth(), BossAI::instance, ScriptedAI::me, NOT_STARTED, REACT_AGGRESSIVE, InstanceScript::SetBossState(), Unit::SetHealth(), Creature::SetReactState(), and BossAI::summons.
SpellHit()
void boss_prince_valanar_icc::boss_prince_valanarAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spell->Id == 71070 && me->IsInCombat() && !me->IsInEvadeMode())
                DoAction(ACTION_CAST_INVOCATION);
        }
References ACTION_CAST_INVOCATION, DoAction(), SpellInfo::Id, Unit::IsInCombat(), Creature::IsInEvadeMode(), and ScriptedAI::me.
UpdateAI()
void boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            if (!UpdateVictim() || !CheckRoom())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_INVOCATION_OF_BLOOD:
                    {
                        uint32 visualSpellId = 0;
                        Creature* current = instance->instance->GetCreature(instance->GetGuidData(invocationOrder[currentInvocationIndex]));
                        if (++currentInvocationIndex >= 3)
                            currentInvocationIndex = 0;
                        Creature* next = instance->instance->GetCreature(instance->GetGuidData(invocationOrder[currentInvocationIndex]));
                        switch (invocationOrder[currentInvocationIndex])
{
                            case DATA_PRINCE_KELESETH_GUID:
                                visualSpellId = 71080;
                                break;
                            case DATA_PRINCE_TALDARAM_GUID:
                                visualSpellId = 71081;
                                break;
                            case DATA_PRINCE_VALANAR_GUID:
                                visualSpellId = 71070;
                                break;
                        }
                        if (!visualSpellId || !current || !next || !current->IsInCombat() || !next->IsInCombat())
{
                            EnterEvadeMode(EVADE_REASON_OTHER);
                            return;
                        }
                        next->SetHealth(current->GetHealth());
                        current->AI()->DoAction(ACTION_REMOVE_INVOCATION);
                        current->SetHealth(1);
                        current->CastSpell((Unit*)nullptr, visualSpellId, true);
                        next->AI()->Talk(1);
                    }
                    events.ScheduleEvent(EVENT_INVOCATION_OF_BLOOD, 46s);
                    break;
                case EVENT_BERSERK:
                    me->CastSpell(me, SPELL_BERSERK, true);
                    Talk(SAY_VALANAR_BERSERK);
                    break;
                case EVENT_KINETIC_BOMB:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true))
                    {
                        me->CastSpell(target, SPELL_KINETIC_BOMB_TARGET, false);
                        Talk(SAY_VALANAR_SPECIAL);
                    }
                    events.ScheduleEvent(EVENT_KINETIC_BOMB, me->GetMap()->Is25ManRaid() ? 20s + 500ms : 30s + 500ms);
                    break;
                case EVENT_SHOCK_VORTEX:
                    if (_isEmpowered)
                    {
                        me->CastSpell(me, SPELL_EMPOWERED_SHOCK_VORTEX, false);
                        Talk(EMOTE_VALANAR_SHOCK_VORTEX);
                        events.ScheduleEvent(EVENT_SHOCK_VORTEX, 30s);
                    }
                    else
                    {
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true))
                            me->CastSpell(target, SPELL_SHOCK_VORTEX, false);
                        events.ScheduleEvent(EVENT_SHOCK_VORTEX, 18s, 23s);
                    }
                    break;
            }
            DoMeleeAttackIfReady();
        }
References _isEmpowered, ACTION_REMOVE_INVOCATION, Creature::AI(), Unit::CastSpell(), CheckRoom(), currentInvocationIndex, DATA_PRINCE_KELESETH_GUID, DATA_PRINCE_TALDARAM_GUID, DATA_PRINCE_VALANAR_GUID, UnitAI::DoAction(), UnitAI::DoMeleeAttackIfReady(), EMOTE_VALANAR_SHOCK_VORTEX, EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_BERSERK, EVENT_INVOCATION_OF_BLOOD, EVENT_KINETIC_BOMB, EVENT_SHOCK_VORTEX, Map::GetCreature(), InstanceScript::GetGuidData(), Unit::GetHealth(), WorldObject::GetMap(), Unit::HasUnitState(), BossAI::instance, InstanceScript::instance, invocationOrder, Map::Is25ManRaid(), Unit::IsInCombat(), ScriptedAI::me, SAY_VALANAR_BERSERK, SAY_VALANAR_SPECIAL, UnitAI::SelectTarget(), Unit::SetHealth(), SPELL_BERSERK, SPELL_EMPOWERED_SHOCK_VORTEX, SPELL_KINETIC_BOMB_TARGET, SPELL_SHOCK_VORTEX, CreatureAI::Talk(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_canDie
bool boss_prince_valanar_icc::boss_prince_valanarAI::_canDie
Referenced by boss_prince_valanarAI(), EnterEvadeMode(), JustDied(), and JustReachedHome().
_evading
bool boss_prince_valanar_icc::boss_prince_valanarAI::_evading
Referenced by EnterEvadeMode(), and Reset().
_isEmpowered
bool boss_prince_valanar_icc::boss_prince_valanarAI::_isEmpowered
Referenced by DamageTaken(), DoAction(), Reset(), and UpdateAI().
currentInvocationIndex
uint8 boss_prince_valanar_icc::boss_prince_valanarAI::currentInvocationIndex
Referenced by JustEngagedWith(), and UpdateAI().
invocationOrder
uint32 boss_prince_valanar_icc::boss_prince_valanarAI::invocationOrder[3]
Referenced by JustEngagedWith(), and UpdateAI().