AzerothCore: UpdateMask Class Reference
UpdateMask Class Reference
#include "UpdateMask.h"
Public Types
enum UpdateMaskCount { CLIENT_UPDATE_MASK_BITS = sizeof(ClientUpdateMaskType) * 8 }
typedef uint32 ClientUpdateMaskType
Type representing how client reads update mask.
Public Member Functions
UpdateMask ()=default
UpdateMask (UpdateMask const &right)
~UpdateMask ()
void SetBit (uint32 index)
void UnsetBit (uint32 index)
bool GetBit (uint32 index) const
void AppendToPacket (ByteBuffer *data)
uint32 GetBlockCount () const
uint32 GetCount () const
void SetCount (uint32 valuesCount)
void Clear ()
UpdateMask & operator= (UpdateMask const &right)
UpdateMask & operator&= (UpdateMask const &right)
UpdateMask & operator|= (UpdateMask const &right)
UpdateMask operator| (UpdateMask const &right)
Private Attributes
uint32 _fieldCount {0}
uint32 _blockCount {0}
uint8 * _bits {nullptr}
Detailed Description
Member Typedef Documentation
ClientUpdateMaskType
typedef uint32 UpdateMask::ClientUpdateMaskType
Type representing how client reads update mask.
Member Enumeration Documentation
UpdateMaskCount
enum UpdateMask::UpdateMaskCount
Enumerator
CLIENT_UPDATE_MASK_BITS
    {
        CLIENT_UPDATE_MASK_BITS = sizeof(ClientUpdateMaskType) * 8,
    };
Constructor & Destructor Documentation
UpdateMask() [1/2]
UpdateMask::UpdateMask () default
UpdateMask() [2/2]
UpdateMask::UpdateMask (UpdateMask const & right) inline
    {
        SetCount(right.GetCount());
        memcpy(_bits, right._bits, sizeof(uint8) * _blockCount * 32);
    }
References _bits, _blockCount, GetCount(), and SetCount().
~UpdateMask()
UpdateMask::~UpdateMask () inline
{ delete[] _bits; }
References _bits.
Member Function Documentation
AppendToPacket()
void UpdateMask::AppendToPacket (ByteBuffer * data) inline
    {
        for (uint32 i = 0; i < GetBlockCount(); ++i)
        {
            ClientUpdateMaskType maskPart = 0;
            for (uint32 j = 0; j < CLIENT_UPDATE_MASK_BITS; ++j)
                if (_bits[CLIENT_UPDATE_MASK_BITS * i + j])
                    maskPart |= 1 << j;
            *data << maskPart;
        }
    }
References _bits, CLIENT_UPDATE_MASK_BITS, and GetBlockCount().
Referenced by Object::BuildValuesUpdate(), Corpse::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), and Unit::BuildValuesUpdate().
Clear()
void UpdateMask::Clear () inline
    {
        if (_bits)
            memset(_bits, 0, sizeof(uint8) * _blockCount * CLIENT_UPDATE_MASK_BITS);
    }
References _bits, _blockCount, and CLIENT_UPDATE_MASK_BITS.
Referenced by Object::ClearUpdateMask().
GetBit()
bool UpdateMask::GetBit (uint32 index) const inline
{ return _bits[index] != 0; }
References _bits.
Referenced by Object::BuildValuesUpdate(), Corpse::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), and Unit::BuildValuesUpdate().
GetBlockCount()
uint32 UpdateMask::GetBlockCount () const inline
{ return _blockCount; }
References _blockCount.
Referenced by AppendToPacket(), Object::BuildValuesUpdate(), Corpse::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), and Unit::BuildValuesUpdate().
GetCount()
uint32 UpdateMask::GetCount () const inline
{ return _fieldCount; }
References _fieldCount.
Referenced by operator&=(), operator=(), operator|=(), and UpdateMask().
operator&=()
UpdateMask & UpdateMask::operator&= (UpdateMask const & right) inline
    {
        ASSERT(right.GetCount() <= GetCount());
        for (uint32 i = 0; i < _fieldCount; ++i)
            _bits[i] &= right._bits[i];
        return *this;
    }
References _bits, _fieldCount, ASSERT, and GetCount().
operator=()
UpdateMask & UpdateMask::operator= (UpdateMask const & right) inline
    {
        if (this == &right)
            return *this;
        SetCount(right.GetCount());
        memcpy(_bits, right._bits, sizeof(uint8) * _blockCount * CLIENT_UPDATE_MASK_BITS);
        return *this;
    }
References _bits, _blockCount, CLIENT_UPDATE_MASK_BITS, GetCount(), and SetCount().
operator|()
UpdateMask UpdateMask::operator| (UpdateMask const & right) inline
    {
        UpdateMask ret(*this);
        ret |= right;
        return ret;
    }
operator|=()
UpdateMask & UpdateMask::operator|= (UpdateMask const & right) inline
    {
        ASSERT(right.GetCount() <= GetCount());
        for (uint32 i = 0; i < _fieldCount; ++i)
            _bits[i] |= right._bits[i];
        return *this;
    }
References _bits, _fieldCount, ASSERT, and GetCount().
SetBit()
void UpdateMask::SetBit (uint32 index) inline
{ _bits[index] = 1; }
References _bits.
Referenced by Object::_LoadIntoDataField(), Object::AddGuidValue(), Object::BuildValuesUpdate(), Corpse::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), Object::ForceValuesUpdateAtIndex(), Object::RemoveByteFlag(), Object::RemoveFlag(), Object::RemoveGuidValue(), Object::SetByteFlag(), Object::SetByteValue(), Object::SetFlag(), Object::SetFloatValue(), Object::SetGuidValue(), Object::SetInt32Value(), Object::SetUInt16Value(), Object::SetUInt32Value(), Object::SetUInt64Value(), and Object::UpdateUInt32Value().
SetCount()
void UpdateMask::SetCount (uint32 valuesCount) inline
    {
        delete[] _bits;
        _fieldCount = valuesCount;
        _blockCount = (valuesCount + CLIENT_UPDATE_MASK_BITS - 1) / CLIENT_UPDATE_MASK_BITS;
        _bits = new uint8[_blockCount * CLIENT_UPDATE_MASK_BITS];
        memset(_bits, 0, sizeof(uint8) * _blockCount * CLIENT_UPDATE_MASK_BITS);
    }
References _bits, _blockCount, _fieldCount, and CLIENT_UPDATE_MASK_BITS.
Referenced by Object::_InitValues(), Object::BuildValuesUpdate(), Corpse::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), operator=(), and UpdateMask().
UnsetBit()
void UpdateMask::UnsetBit (uint32 index) inline
{ _bits[index] = 0; }
References _bits.
Referenced by Unit::SetLevel().
Member Data Documentation
_bits
uint8* UpdateMask::_bits {nullptr} private
Referenced by AppendToPacket(), Clear(), GetBit(), operator&=(), operator=(), operator|=(), SetBit(), SetCount(), UnsetBit(), UpdateMask(), and ~UpdateMask().
_blockCount
uint32 UpdateMask::_blockCount {0} private
Referenced by Clear(), GetBlockCount(), operator=(), SetCount(), and UpdateMask().
_fieldCount
uint32 UpdateMask::_fieldCount {0} private
Referenced by GetCount(), operator&=(), operator|=(), and SetCount().