AzerothCore: boss_black_knight::boss_black_knightAI Struct Reference
boss_black_knight::boss_black_knightAI Struct Reference
Public Member Functions
boss_black_knightAI (Creature *pCreature)
void Reset () override
void EnterEvadeMode (EvadeReason why) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void DoAction (int32 param) override
void SpellHitTarget (Unit *, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustSummoned (Creature *summon) override
void KilledUnit (Unit *victim) override
void JustDied (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
uint8 Phase
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_black_knightAI()
boss_black_knight::boss_black_knightAI::boss_black_knightAI (Creature * pCreature) inline
                                                 : ScriptedAI(pCreature), summons(me)
        {
            pInstance = pCreature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
DamageTaken()
void boss_black_knight::boss_black_knightAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
            {
                damage = 0;
                return;
            }
            if (Phase < 3 && damage >= me->GetHealth())
            {
                damage = 0;
                me->SetHealth(me->GetMaxHealth());
                events.Reset();
                me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->RemoveAllAuras();
                me->SetControlled(true, UNIT_STATE_STUNNED);
                me->CastSpell(me, SPELL_BK_GHOUL_EXPLODE, true);
                summons.clear();
                me->CastSpell(me, SPELL_BK_FEIGN_DEATH, true);
                me->SetUnitFlag(UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT);
                me->SetUnitFlag2(UNIT_FLAG2_FEIGN_DEATH);
                me->SetDynamicFlag(UNIT_DYNFLAG_DEAD);
                me->AddUnitState(UNIT_STATE_DIED);
            }
        }
References Unit::AddUnitState(), Unit::CastSpell(), SummonList::clear(), Unit::GetHealth(), Unit::GetMaxHealth(), Unit::HasUnitFlag(), ScriptedAI::me, Unit::RemoveAllAuras(), Unit::SetControlled(), Object::SetDynamicFlag(), Unit::SetHealth(), Unit::SetUnitFlag(), Unit::SetUnitFlag2(), SPELL_BK_FEIGN_DEATH, SPELL_BK_GHOUL_EXPLODE, summons, UNIT_DYNFLAG_DEAD, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT, UNIT_STATE_DIED, and UNIT_STATE_STUNNED.
DoAction()
void boss_black_knight::boss_black_knightAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == -1)
            {
                summons.DespawnAll();
            }
            else if (param == 1)
            {
                if (!pInstance)
                    return;
                pInstance->SetData(BOSS_BLACK_KNIGHT, IN_PROGRESS);
                Talk(SAY_BK_AGGRO);
                me->CastSpell((Unit*)nullptr, (pInstance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE ? SPELL_RAISE_DEAD_JAEREN : SPELL_RAISE_DEAD_ARELAS), false);
                if (Creature* announcer = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_ANNOUNCER)))
                    announcer->DespawnOrUnsummon();
                events.Reset();
                events.ScheduleEvent(EVENT_ANNOUNCER_SAY_ZOMBIE, 2500ms);
                events.ScheduleEvent(EVENT_SPELL_PLAGUE_STRIKE, 7s, 9s);
                events.ScheduleEvent(EVENT_SPELL_ICY_TOUCH, 3500ms, 7000ms);
                events.ScheduleEvent(EVENT_SPELL_DEATH_RESPITE, 13s, 15s);
                events.ScheduleEvent(EVENT_SPELL_OBLITERATE, 11s, 19s);
            }
        }
References BOSS_BLACK_KNIGHT, Unit::CastSpell(), DATA_ANNOUNCER, DATA_TEAMID_IN_INSTANCE, SummonList::DespawnAll(), EVENT_ANNOUNCER_SAY_ZOMBIE, EVENT_SPELL_DEATH_RESPITE, EVENT_SPELL_ICY_TOUCH, EVENT_SPELL_OBLITERATE, EVENT_SPELL_PLAGUE_STRIKE, Map::GetCreature(), ZoneScript::GetData(), InstanceScript::GetGuidData(), IN_PROGRESS, InstanceScript::instance, ScriptedAI::me, pInstance, SAY_BK_AGGRO, ZoneScript::SetData(), SPELL_RAISE_DEAD_ARELAS, SPELL_RAISE_DEAD_JAEREN, summons, and TEAM_HORDE.
EnterEvadeMode()
void boss_black_knight::boss_black_knightAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            me->DespawnOrUnsummon(1);
            ScriptedAI::EnterEvadeMode(why);
        }
References Creature::DespawnOrUnsummon(), CreatureAI::EnterEvadeMode(), and ScriptedAI::me.
Referenced by SpellHitTarget().
JustDied()
void boss_black_knight::boss_black_knightAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            me->CastSpell((Unit*)nullptr, SPELL_BK_KILL_CREDIT, true);
            Talk(SAY_BK_DEATH);
            if (pInstance)
                pInstance->SetData(BOSS_BLACK_KNIGHT, DONE);
            if (me->ToTempSummon())
                me->ToTempSummon()->SetTempSummonType(TEMPSUMMON_MANUAL_DESPAWN);
        }
References BOSS_BLACK_KNIGHT, Unit::CastSpell(), DONE, ScriptedAI::me, pInstance, SAY_BK_DEATH, ZoneScript::SetData(), TempSummon::SetTempSummonType(), SPELL_BK_KILL_CREDIT, TEMPSUMMON_MANUAL_DESPAWN, and Unit::ToTempSummon().
JustSummoned()
void boss_black_knight::boss_black_knightAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(summon);
            if (Unit* target = summon->SelectNearestTarget(200.0f))
            {
                summon->AI()->AttackStart(target);
                DoZoneInCombat(summon);
            }
        }
References Creature::AI(), UnitAI::AttackStart(), CreatureAI::DoZoneInCombat(), Creature::SelectNearestTarget(), SummonList::Summon(), and summons.
KilledUnit()
void boss_black_knight::boss_black_knightAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->IsPlayer())
            {
                Talk(SAY_BK_KILL_PLAYER);
            }
        }
References Object::IsPlayer(), and SAY_BK_KILL_PLAYER.
Reset()
void boss_black_knight::boss_black_knightAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Reset();
            summons.DespawnAll();
            Phase = 1;
            me->SetDisplayId(me->GetNativeDisplayId());
            me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            me->SetImmuneToAll(true);
            me->SetReactState(REACT_PASSIVE);
            if (pInstance)
                pInstance->SetData(BOSS_BLACK_KNIGHT, NOT_STARTED);
            //me->SetLootMode(0); // [LOOT]
        }
References BOSS_BLACK_KNIGHT, SummonList::DespawnAll(), Unit::GetNativeDisplayId(), ScriptedAI::me, NOT_STARTED, pInstance, REACT_PASSIVE, ZoneScript::SetData(), Creature::SetDisplayId(), Unit::SetImmuneToAll(), Creature::SetReactState(), Unit::SetUnitFlag(), summons, and UNIT_FLAG_NON_ATTACKABLE.
SpellHitTarget()
void boss_black_knight::boss_black_knightAI::SpellHitTarget (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            switch (spell->Id)
            {
                case SPELL_BLACK_KNIGHT_RES:
                    me->SetHealth(me->GetMaxHealth());
                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->SetImmuneToAll(false);
                    me->SetControlled(false, UNIT_STATE_STUNNED);
                    me->RemoveUnitFlag(UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT);
                    me->RemoveUnitFlag2(UNIT_FLAG2_FEIGN_DEATH);
                    me->RemoveDynamicFlag(UNIT_DYNFLAG_DEAD);
                    me->ClearUnitState(UNIT_STATE_DIED);
                    ++Phase;
                    switch (Phase)
                    {
                        case 2:
                            me->SetDisplayId(MODEL_SKELETON);
                            Talk(SAY_BK_PHASE_2);
                            me->CastSpell(me, SPELL_ARMY_DEAD, false);
                            events.Reset();
                            events.ScheduleEvent(EVENT_SPELL_PLAGUE_STRIKE, 7s, 9s);
                            events.ScheduleEvent(EVENT_SPELL_ICY_TOUCH, 3500ms, 7000ms);
                            events.ScheduleEvent(EVENT_SPELL_OBLITERATE, 11s, 19s);
                            events.ScheduleEvent(EVENT_SPELL_DESECRATION, 2s, 3s);
                            break;
                        case 3:
                            me->SetDisplayId(MODEL_GHOST);
                            Talk(SAY_BK_PHASE_3);
                            events.Reset();
                            events.ScheduleEvent(EVENT_SPELL_DEATH_BITE, 2s);
                            events.ScheduleEvent(EVENT_SPELL_MARKED_DEATH, 1s);
                            break;
                        default:
                            EnterEvadeMode(EVADE_REASON_OTHER);
                            break;
                    }
                    break;
            }
        }
References Unit::CastSpell(), Unit::ClearUnitState(), EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_SPELL_DEATH_BITE, EVENT_SPELL_DESECRATION, EVENT_SPELL_ICY_TOUCH, EVENT_SPELL_MARKED_DEATH, EVENT_SPELL_OBLITERATE, EVENT_SPELL_PLAGUE_STRIKE, Unit::GetMaxHealth(), SpellInfo::Id, ScriptedAI::me, MODEL_GHOST, MODEL_SKELETON, Phase, Object::RemoveDynamicFlag(), Unit::RemoveUnitFlag(), Unit::RemoveUnitFlag2(), SAY_BK_PHASE_2, SAY_BK_PHASE_3, Unit::SetControlled(), Creature::SetDisplayId(), Unit::SetHealth(), Unit::SetImmuneToAll(), SPELL_ARMY_DEAD, SPELL_BLACK_KNIGHT_RES, UNIT_DYNFLAG_DEAD, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT, UNIT_STATE_DIED, and UNIT_STATE_STUNNED.
UpdateAI()
void boss_black_knight::boss_black_knightAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Todo:
: Multiple variations + not always happening, from video sources, needs sniff to transition from DB.
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_ANNOUNCER_SAY_ZOMBIE:
                    if (pInstance && !summons.empty())
                        if (Creature* ghoul = pInstance->instance->GetCreature(*summons.begin()))
                            if (urand(0, 1))
                                ghoul->Yell("[Zombie] .... . Brains ....", LANG_UNIVERSAL);
                    break;
                case EVENT_SPELL_PLAGUE_STRIKE:
                    if (me->GetVictim())
                        me->CastSpell(me->GetVictim(), SPELL_PLAGUE_STRIKE, false);
                    events.Repeat(10s, 12s);
                    break;
                case EVENT_SPELL_ICY_TOUCH:
                    if (me->GetVictim())
                        me->CastSpell(me->GetVictim(), SPELL_ICY_TOUCH, false);
                    events.Repeat(5s, 6s);
                    break;
                case EVENT_SPELL_DEATH_RESPITE:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 50.0f, true))
                        me->CastSpell(target, SPELL_DEATH_RESPITE, false);
                    events.Repeat(13s, 15s);
                    break;
                case EVENT_SPELL_OBLITERATE:
                    if (me->GetVictim())
                        me->CastSpell(me->GetVictim(), SPELL_OBLITERATE, false);
                    events.Repeat(15s, 17s);
                    break;
                case EVENT_SPELL_DESECRATION:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 50.0f, true))
                        me->CastSpell(target, SPELL_DESECRATION, false);
                    events.Repeat(14s, 17s);
                    break;
                case EVENT_SPELL_DEATH_BITE:
                    me->CastSpell((Unit*)nullptr, SPELL_DEATH_BITE, false);
                    events.Repeat(2s, 4s);
                    break;
                case EVENT_SPELL_MARKED_DEATH:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 0.000000f, true))
                        me->CastSpell(target, SPELL_MARKED_DEATH, false);
                    events.Repeat(9s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References SummonList::begin(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), SummonList::empty(), EVENT_ANNOUNCER_SAY_ZOMBIE, EVENT_SPELL_DEATH_BITE, EVENT_SPELL_DEATH_RESPITE, EVENT_SPELL_DESECRATION, EVENT_SPELL_ICY_TOUCH, EVENT_SPELL_MARKED_DEATH, EVENT_SPELL_OBLITERATE, EVENT_SPELL_PLAGUE_STRIKE, Map::GetCreature(), Unit::GetVictim(), Unit::HasUnitState(), InstanceScript::instance, LANG_UNIVERSAL, ScriptedAI::me, pInstance, UnitAI::SelectTarget(), SPELL_DEATH_BITE, SPELL_DEATH_RESPITE, SPELL_DESECRATION, SPELL_ICY_TOUCH, SPELL_MARKED_DEATH, SPELL_OBLITERATE, SPELL_PLAGUE_STRIKE, summons, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap boss_black_knight::boss_black_knightAI::events
Phase
uint8 boss_black_knight::boss_black_knightAI::Phase
Referenced by SpellHitTarget().
pInstance
InstanceScript* boss_black_knight::boss_black_knightAI::pInstance
Referenced by boss_black_knightAI(), DoAction(), JustDied(), Reset(), and UpdateAI().
summons
SummonList boss_black_knight::boss_black_knightAI::summons
Referenced by DamageTaken(), DoAction(), JustSummoned(), Reset(), and UpdateAI().