AzerothCore: item_captured_frog Class Reference
item_captured_frog Class Reference
Public Member Functions
item_captured_frog ()
bool OnUse (Player *player, Item *item, SpellCastTargets const &) override
Public Member Functions inherited from ItemScript
bool IsDatabaseBound () const override
virtual bool OnQuestAccept (Player *, Item *, Quest const *)
virtual bool OnUse (Player *, Item *, SpellCastTargets const &)
virtual bool OnRemove (Player *, Item *)
virtual bool OnCastItemCombatSpell (Player *, Unit *, SpellInfo const *, Item *)
virtual bool OnExpire (Player *, ItemTemplate const *)
virtual void OnGossipSelect (Player *, Item *, uint32, uint32)
virtual void OnGossipSelectCode (Player *, Item *, uint32, uint32, const char *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from ItemScript
ItemScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
item_captured_frog()
item_captured_frog::item_captured_frog () inline
: ItemScript("item_captured_frog") { }
Member Function Documentation
OnUse()
bool item_captured_frog::OnUse (Player * player, Item * item, SpellCastTargets const &) inline override virtual
Reimplemented from ItemScript.
    {
        if (player->GetQuestStatus(QUEST_THE_PERFECT_SPIES) == QUEST_STATUS_INCOMPLETE)
        {
            if (player->FindNearestCreature(NPC_VANIRAS_SENTRY_TOTEM, 10.0f))
                return false;
            else
                player->SendEquipError(EQUIP_ERR_OUT_OF_RANGE, item, nullptr);
        }
        else
            player->SendEquipError(EQUIP_ERR_CANT_DO_RIGHT_NOW, item, nullptr);
        return true;
    }
References EQUIP_ERR_CANT_DO_RIGHT_NOW, EQUIP_ERR_OUT_OF_RANGE, WorldObject::FindNearestCreature(), Player::GetQuestStatus(), NPC_VANIRAS_SENTRY_TOTEM, QUEST_STATUS_INCOMPLETE, QUEST_THE_PERFECT_SPIES, and Player::SendEquipError().