AzerothCore: boss_jormungarAI Struct Reference
boss_jormungarAI Struct Reference
Public Member Functions
boss_jormungarAI (Creature *pCreature)
void DoAction (int32 param) override
void ScheduleEvents ()
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustReachedHome () override
void AttackStart (Unit *who) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void EnterEvadeMode (EvadeReason) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
bool bIsStationary
uint32 _SPELL_BITE
uint32 _SPELL_SPEW
uint32 _SPELL_SPIT
uint32 _SPELL_SPRAY
uint32 _MODEL_STATIONARY
uint32 _MODEL_MOBILE
uint32 _TYPE_OTHER
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_jormungarAI()
boss_jormungarAI::boss_jormungarAI (Creature * pCreature) inline
                                          : ScriptedAI(pCreature)
    {
        pInstance = pCreature->GetInstanceScript();
        me->SetReactState(REACT_PASSIVE);
    }
References WorldObject::GetInstanceScript(), ScriptedAI::me, pInstance, REACT_PASSIVE, and Creature::SetReactState().
Member Function Documentation
AttackStart()
void boss_jormungarAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (me->GetDisplayId() == _MODEL_STATIONARY )
        {
            if (!who)
                return;
            if (me->Attack(who, true))
                DoStartNoMovement(who);
        }
        else
            ScriptedAI::AttackStart(who);
    }
References _MODEL_STATIONARY, Unit::Attack(), ScriptedAI::AttackStart(), ScriptedAI::DoStartNoMovement(), Unit::GetDisplayId(), and ScriptedAI::me.
DoAction()
void boss_jormungarAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
    {
        switch (param)
        {
            case -1:
                if (!me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
                    events.RescheduleEvent(EVENT_SUBMERGE, 1500ms);
                break;
            case -2:
                if (me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
                    bIsStationary = true; // it will come out mobile soon
                else if (me->GetDisplayId() == _MODEL_STATIONARY )
                    events.RescheduleEvent(EVENT_SUBMERGE, 1s);
                else
                    events.CancelEvent(EVENT_SUBMERGE);
                me->CastSpell(me, SPELL_ENRAGE, true);
                Talk(EMOTE_ENRAGE);
                break;
        }
    }
References _MODEL_STATIONARY, bIsStationary, Unit::CastSpell(), EMOTE_ENRAGE, EVENT_SUBMERGE, Unit::GetDisplayId(), Unit::HasUnitFlag(), ScriptedAI::me, SPELL_ENRAGE, and UNIT_FLAG_NON_ATTACKABLE.
EnterEvadeMode()
void boss_jormungarAI::EnterEvadeMode (EvadeReason) inline override virtual
Reimplemented from CreatureAI.
    {
        events.Reset();
        me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
        if (pInstance)
            pInstance->SetData(TYPE_FAILED, 1);
    }
References ScriptedAI::me, pInstance, ZoneScript::SetData(), Unit::SetUnitFlag(), TYPE_FAILED, and UNIT_FLAG_NON_ATTACKABLE.
JustDied()
void boss_jormungarAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (pInstance)
        {
            if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(_TYPE_OTHER)))
                if (c->IsAlive())
                    c->AI()->DoAction(-2);
            pInstance->SetData(TYPE_JORMUNGAR, DONE);
        }
    }
References _TYPE_OTHER, DONE, Map::GetCreature(), InstanceScript::GetGuidData(), InstanceScript::instance, pInstance, ZoneScript::SetData(), and TYPE_JORMUNGAR.
JustEngagedWith()
void boss_jormungarAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
    {
        me->setActive(true);
        ScheduleEvents();
    }
References ScriptedAI::me, ScheduleEvents(), and WorldObject::setActive().
JustReachedHome()
void boss_jormungarAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
    {
        me->setActive(false);
    }
References ScriptedAI::me, and WorldObject::setActive().
ScheduleEvents()
void boss_jormungarAI::ScheduleEvents () inline
    {
        events.Reset();
        if (me->GetDisplayId() == _MODEL_STATIONARY )
        {
            me->SetAttackTime(BASE_ATTACK, 1500);
            events.RescheduleEvent(EVENT_SPELL_SPRAY, (me->GetEntry() == NPC_ACIDMAW ? 20s : 15s));
            events.RescheduleEvent(EVENT_SPELL_SWEEP, 15s, 30s);
        }
        else
        {
            me->SetAttackTime(BASE_ATTACK, 2000);
            events.RescheduleEvent(EVENT_SPELL_BITE, (me->GetEntry() == NPC_ACIDMAW ? 20s : 15s));
            events.RescheduleEvent(EVENT_SPELL_SPEW, 15s, 30s);
            events.RescheduleEvent(EVENT_SPELL_SLIME_POOL, 15s);
        }
        if (!me->HasAura(SPELL_ENRAGE))
            events.RescheduleEvent(EVENT_SUBMERGE, 45s, 50s);
    }
References _MODEL_STATIONARY, BASE_ATTACK, EVENT_SPELL_BITE, EVENT_SPELL_SLIME_POOL, EVENT_SPELL_SPEW, EVENT_SPELL_SPRAY, EVENT_SPELL_SWEEP, EVENT_SUBMERGE, Unit::GetDisplayId(), Object::GetEntry(), Unit::HasAura(), ScriptedAI::me, NPC_ACIDMAW, Unit::SetAttackTime(), and SPELL_ENRAGE.
Referenced by JustEngagedWith(), and UpdateAI().
UpdateAI()
void boss_jormungarAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
    {
        if (!UpdateVictim())
            return;
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
            return;
        switch (events.ExecuteEvent())
        {
            case 0:
                break;
            case EVENT_SUBMERGE:
                {
                    bIsStationary = (me->GetDisplayId() == _MODEL_STATIONARY);
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                    me->CastSpell(me, SPELL_SUBMERGE_0, false);
                    Talk(EMOTE_SUBMERGE);
                    // second one submerge 1.5sec after the first one, used also for synchronizing
                    if (pInstance)
                        if (Creature* c = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(_TYPE_OTHER)))
                            c->AI()->DoAction(-1);
                    events.Reset();
                    events.RescheduleEvent(EVENT_MOVE_UNDERGROUND, 2500ms);
                }
                break;
            case EVENT_MOVE_UNDERGROUND:
                {
                    float angle = me->GetAngle(Locs[LOC_CENTER].GetPositionX() + urand(0, 20) - 10.0f, Locs[LOC_CENTER].GetPositionY() + urand(0, 20) - 10.0f), dist = urand(10, 35);
                    if (Creature* c = me->SummonCreature(NPC_WORLD_TRIGGER, *me, TEMPSUMMON_TIMED_DESPAWN, 6000))
                    {
                        c->SetSpeed(MOVE_RUN, 2.5f);
                        c->CastSpell(c, SPELL_CHURNING_GROUND, true);
                        c->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_PACIFIED);
                        c->GetMotionMaster()->MovePoint(0, Locs[LOC_CENTER].GetPositionX() + cos(angle)*dist, Locs[LOC_CENTER].GetPositionY() + std::sin(angle)*dist, me->GetPositionZ());
                    }
                    me->UpdatePosition(Locs[LOC_CENTER].GetPositionX() + cos(angle)*dist, Locs[LOC_CENTER].GetPositionY() + std::sin(angle)*dist, me->GetPositionZ(), me->GetOrientation(), true);
                    me->StopMovingOnCurrentPos();
                    DoResetThreatList();
                    events.RescheduleEvent(EVENT_EMERGE, 6s);
                }
                break;
            case EVENT_EMERGE:
                {
                    me->GetMotionMaster()->Clear();
                    me->GetMotionMaster()->MoveIdle();
                    me->StopMoving();
                    if (bIsStationary)
                    {
                        me->SetNativeDisplayId(_MODEL_MOBILE);
                        me->SetCombatMovement(true);
                        if (Unit* victim = me->GetVictim())
                            me->GetMotionMaster()->MoveChase(victim);
                    }
                    else
                    {
                        me->SetNativeDisplayId(_MODEL_STATIONARY);
                        me->SetCombatMovement(false);
                    }
                    me->RemoveAurasDueToSpell(SPELL_SUBMERGE_0);
                    me->CastSpell(me, SPELL_EMERGE_0, false);
                    Talk(EMOTE_EMERGE);
                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                    ScheduleEvents();
                }
                break;
            case EVENT_SPELL_SPRAY:
                if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100.0f, true))
                    me->CastSpell(target, _SPELL_SPRAY, false);
                events.Repeat(20s);
                break;
            case EVENT_SPELL_SWEEP:
                me->CastSpell((Unit*)nullptr, SPELL_SWEEP_0, false);
                events.Repeat(15s, 30s);
                break;
            case EVENT_SPELL_BITE:
                if (Unit* victim = me->GetVictim())
                    me->CastSpell(victim, _SPELL_BITE, false);
                events.Repeat(20s);
                break;
            case EVENT_SPELL_SPEW:
                me->CastSpell(me->GetVictim(), _SPELL_SPEW, false);
                events.Repeat(15s, 30s);
                break;
            case EVENT_SPELL_SLIME_POOL:
                if (Creature* c = me->SummonCreature(NPC_SLIME_POOL, *me, TEMPSUMMON_TIMED_DESPAWN, 30000))
                    c->CastSpell(c, SPELL_SLIME_POOL_EFFECT, true);
                events.Repeat(30s);
                break;
        }
        if (!me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
        {
            if (me->GetDisplayId() == _MODEL_STATIONARY )
                DoSpellAttackIfReady(_SPELL_SPIT);
            else
                DoMeleeAttackIfReady();
        }
    }
References _MODEL_MOBILE, _MODEL_STATIONARY, _SPELL_BITE, _SPELL_SPEW, _SPELL_SPIT, _SPELL_SPRAY, _TYPE_OTHER, bIsStationary, Unit::CastSpell(), MotionMaster::Clear(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreatList(), UnitAI::DoSpellAttackIfReady(), EMOTE_EMERGE, EMOTE_SUBMERGE, EVENT_EMERGE, EVENT_MOVE_UNDERGROUND, EVENT_SPELL_BITE, EVENT_SPELL_SLIME_POOL, EVENT_SPELL_SPEW, EVENT_SPELL_SPRAY, EVENT_SPELL_SWEEP, EVENT_SUBMERGE, Position::GetAngle(), ObjectAccessor::GetCreature(), Unit::GetDisplayId(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HasUnitFlag(), Unit::HasUnitState(), LOC_CENTER, Locs, ScriptedAI::me, MOVE_RUN, MotionMaster::MoveChase(), MotionMaster::MoveIdle(), NPC_SLIME_POOL, NPC_WORLD_TRIGGER, pInstance, Unit::RemoveAurasDueToSpell(), Unit::RemoveUnitFlag(), ScheduleEvents(), UnitAI::SelectTarget(), Creature::SetCombatMovement(), Unit::SetNativeDisplayId(), Unit::SetUnitFlag(), SPELL_CHURNING_GROUND, SPELL_EMERGE_0, SPELL_SLIME_POOL_EFFECT, SPELL_SUBMERGE_0, SPELL_SWEEP_0, Unit::StopMoving(), Unit::StopMovingOnCurrentPos(), WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_FLAG_PACIFIED, UNIT_STATE_CASTING, Unit::UpdatePosition(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_MODEL_MOBILE
uint32 boss_jormungarAI::_MODEL_MOBILE
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), and UpdateAI().
_MODEL_STATIONARY
uint32 boss_jormungarAI::_MODEL_STATIONARY
Referenced by AttackStart(), boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), DoAction(), ScheduleEvents(), and UpdateAI().
_SPELL_BITE
uint32 boss_jormungarAI::_SPELL_BITE
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), and UpdateAI().
_SPELL_SPEW
uint32 boss_jormungarAI::_SPELL_SPEW
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), and UpdateAI().
_SPELL_SPIT
uint32 boss_jormungarAI::_SPELL_SPIT
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), and UpdateAI().
_SPELL_SPRAY
uint32 boss_jormungarAI::_SPELL_SPRAY
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), and UpdateAI().
_TYPE_OTHER
uint32 boss_jormungarAI::_TYPE_OTHER
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), JustDied(), and UpdateAI().
bIsStationary
bool boss_jormungarAI::bIsStationary
Referenced by DoAction(), and UpdateAI().
events
EventMap boss_jormungarAI::events
pInstance
InstanceScript* boss_jormungarAI::pInstance
Referenced by boss_jormungarAI(), EnterEvadeMode(), JustDied(), and UpdateAI().