AzerothCore: WorldPackets::Guild::GuildInfoResponse Class Reference
WorldPackets::Guild::GuildInfoResponse Class Reference final
#include "GuildPackets.h"
Public Member Functions
GuildInfoResponse ()
WorldPacket const * Write () override
Public Attributes
std::string GuildName
time_t CreateDate = time_t(0)
int32 NumMembers = 0
int32 NumAccounts = 0
Additional Inherited Members
Private Member Functions inherited from WorldPackets::ServerPacket
ServerPacket (OpcodeServer opcode, std::size_t initialSize=200)
void Read () final
void Clear ()
WorldPacket && Move ()
void ShrinkToFit ()
OpcodeServer GetOpcode () const
Private Member Functions inherited from WorldPackets::Packet
Packet (WorldPacket &&worldPacket)
virtual ~Packet ()=default
Packet (Packet const &right)=delete
Packet & operator= (Packet const &right)=delete
virtual WorldPacket const * Write ()=0
virtual void Read ()=0
WorldPacket const * GetRawPacket () const
std::size_t GetSize () const
Private Attributes inherited from WorldPackets::Packet
WorldPacket _worldPacket
Detailed Description
Constructor & Destructor Documentation
GuildInfoResponse()
WorldPackets::Guild::GuildInfoResponse::GuildInfoResponse () inline
: ServerPacket(SMSG_GUILD_INFO, 123) { }
Member Function Documentation
Write()
WorldPacket const * WorldPackets::Guild::GuildInfoResponse::Write () override virtual
Implements WorldPackets::Packet.
{
    _worldPacket << GuildName;
    _worldPacket.AppendPackedTime(CreateDate);
    _worldPacket << int32(NumMembers);
    _worldPacket << int32(NumAccounts);
    return &_worldPacket;
}
References ByteBuffer::AppendPackedTime().
Referenced by Guild::SendInfo().
Member Data Documentation
CreateDate
time_t WorldPackets::Guild::GuildInfoResponse::CreateDate = time_t(0)
Referenced by Guild::SendInfo().
GuildName
std::string WorldPackets::Guild::GuildInfoResponse::GuildName
Referenced by Guild::SendInfo().
NumAccounts
int32 WorldPackets::Guild::GuildInfoResponse::NumAccounts = 0
Referenced by Guild::SendInfo().
NumMembers
int32 WorldPackets::Guild::GuildInfoResponse::NumMembers = 0
Referenced by Guild::SendInfo().