AzerothCore: lfg::Lfg5Guids Class Reference
lfg::Lfg5Guids Class Reference
#include "LFG.h"
Public Member Functions
Lfg5Guids ()
Lfg5Guids (ObjectGuid g)
Lfg5Guids (Lfg5Guids const &x)
Lfg5Guids (Lfg5Guids const &x, bool)
~Lfg5Guids ()
void addRoles (LfgRolesMap const &r)
void clear ()
bool empty () const
ObjectGuid front () const
uint8 size () const
void insert (const ObjectGuid &g)
void force_insert_front (const ObjectGuid &g)
void remove (const ObjectGuid &g)
bool hasGuid (const ObjectGuid &g) const
bool operator< (const Lfg5Guids &x) const
bool operator== (const Lfg5Guids &x) const
void operator= (const Lfg5Guids &x)
std::string toString () const
Public Attributes
std::array< ObjectGuid, 5 > guids = { }
LfgRolesMap * roles
Detailed Description
Constructor & Destructor Documentation
Lfg5Guids() [1/4]
lfg::Lfg5Guids::Lfg5Guids () inline
        {
            guids.fill(ObjectGuid::Empty);
            roles = nullptr;
        }
References ObjectGuid::Empty, guids, and roles.
Lfg5Guids() [2/4]
lfg::Lfg5Guids::Lfg5Guids (ObjectGuid g) inline
        {
            guids.fill(ObjectGuid::Empty);
            guids[0] = g;
            roles = nullptr;
        }
References ObjectGuid::Empty, guids, and roles.
Lfg5Guids() [3/4]
lfg::Lfg5Guids::Lfg5Guids (Lfg5Guids const & x) inline
        {
            guids = x.guids;
            roles = x.roles ? (new LfgRolesMap(*(x.roles))) : nullptr;
        }
References guids, and roles.
Lfg5Guids() [4/4]
lfg::Lfg5Guids::Lfg5Guids (Lfg5Guids const & x, bool) inline
        {
            guids = x.guids;
            roles = nullptr;
        }
References guids, and roles.
~Lfg5Guids()
lfg::Lfg5Guids::~Lfg5Guids () inline
{ delete roles; }
References roles.
Member Function Documentation
addRoles()
void lfg::Lfg5Guids::addRoles (LfgRolesMap const & r) inline
{ roles = new LfgRolesMap(r); }
References roles.
Referenced by lfg::LFGQueue::CheckCompatibility().
clear()
void lfg::Lfg5Guids::clear () inline
{ guids.fill(ObjectGuid::Empty); }
References ObjectGuid::Empty, and guids.
empty()
bool lfg::Lfg5Guids::empty () const inline
{ return guids[0] == ObjectGuid::Empty; }
References ObjectGuid::Empty, and guids.
Referenced by lfg::LFGMgr::AllQueued(), and lfg::LFGQueue::UpdateQueueTimers().
force_insert_front()
void lfg::Lfg5Guids::force_insert_front (const ObjectGuid & g) inline
        {
            if (guids[3])
            {
                guids[4] = guids[3];
            }
            if (guids[2])
            {
                guids[3] = guids[2];
            }
            if (guids[1])
            {
                guids[2] = guids[1];
            }
            guids[1] = guids[0];
            guids[0] = g;
        }
References guids.
Referenced by lfg::LFGQueue::CheckCompatibility().
front()
ObjectGuid lfg::Lfg5Guids::front () const inline
{ return guids[0]; }
References guids.
Referenced by lfg::LFGQueue::CheckCompatibility().
hasGuid()
bool lfg::Lfg5Guids::hasGuid (const ObjectGuid & g) const inline
        {
            return g && (guids[0] == g || guids[1] == g || guids[2] == g || guids[3] == g || guids[4] == g);
        }
References guids.
insert()
void lfg::Lfg5Guids::insert (const ObjectGuid & g) inline
        {
            // avoid loops for performance
            if (!guids[0])
            {
                guids[0] = g;
                return;
            }
            if (g <= guids[0])
            {
                if (guids[3])
                {
                    guids[4] = guids[3];
                }
                if (guids[2])
                {
                    guids[3] = guids[2];
                }
                if (guids[1])
                {
                    guids[2] = guids[1];
                }
                guids[1] = guids[0];
                guids[0] = g;
                return;
            }
            if (!guids[1])
            {
                guids[1] = g;
                return;
            }
            if (g <= guids[1])
            {
                if (guids[3])
                {
                    guids[4] = guids[3];
                }
                if (guids[2])
                {
                    guids[3] = guids[2];
                }
                guids[2] = guids[1];
                guids[1] = g;
                return;
            }
            if (!guids[2])
            {
                guids[2] = g;
                return;
            }
            if (g <= guids[2])
            {
                if (guids[3])
                {
                    guids[4] = guids[3];
                }
                guids[3] = guids[2];
                guids[2] = g;
                return;
            }
            if (!guids[3])
            {
                guids[3] = g;
                return;
            }
            if (g <= guids[3])
            {
                guids[4] = guids[3];
                guids[3] = g;
                return;
            }
            guids[4] = g;
        }
References guids.
Referenced by lfg::LFGQueue::CheckCompatibility().
operator<()
bool lfg::Lfg5Guids::operator< (const Lfg5Guids & x) const inline
        {
            if (guids[0] <= x.guids[0])
            {
                if (guids[0] != x.guids[0])
                {
                    return true;
                }
                if (guids[1] <= x.guids[1])
                {
                    if (guids[1] != x.guids[1])
                    {
                        return true;
                    }
                    if (guids[2] <= x.guids[2])
                    {
                        if (guids[2] != x.guids[2])
{
                            return true;
                        }
                        if (guids[3] <= x.guids[3])
{
                            if (guids[3] != x.guids[3])
{
                                return true;
                            }
                            if (guids[4] <= x.guids[4])
{
                                return !(guids[4] == x.guids[4]);
                            }
                        }
                    }
                }
            }
            return false;
        }
References guids.
operator=()
void lfg::Lfg5Guids::operator= (const Lfg5Guids & x) inline
        {
            guids = x.guids;
            delete roles;
            roles = x.roles ? (new LfgRolesMap(*(x.roles))) : nullptr;
        }
References guids, and roles.
operator==()
bool lfg::Lfg5Guids::operator== (const Lfg5Guids & x) const inline
        {
            return guids[0] == x.guids[0] && guids[1] == x.guids[1] && guids[2] == x.guids[2] && guids[3] == x.guids[3] && guids[4] == x.guids[4];
        }
References guids.
remove()
void lfg::Lfg5Guids::remove (const ObjectGuid & g) inline
        {
            // avoid loops for performance
            if (guids[0] == g)
            {
                if (guids[1])
                {
                    guids[0] = guids[1];
                }
                else
                {
                    guids[0].Clear();
                    return;
                }
                if (guids[2])
                {
                    guids[1] = guids[2];
                }
                else
                {
                    guids[1].Clear();
                    return;
                }
                if (guids[3])
                {
                    guids[2] = guids[3];
                }
                else
                {
                    guids[2].Clear();
                    return;
                }
                if (guids[4])
                {
                    guids[3] = guids[4];
                }
                else
                {
                    guids[3].Clear();
                    return;
                }
                guids[4].Clear();
                return;
            }
            if (guids[1] == g)
            {
                if (guids[2])
                {
                    guids[1] = guids[2];
                }
                else
                {
                    guids[1].Clear();
                    return;
                }
                if (guids[3])
                {
                    guids[2] = guids[3];
                }
                else
                {
                    guids[2].Clear();
                    return;
                }
                if (guids[4])
                {
                    guids[3] = guids[4];
                }
                else
                {
                    guids[3].Clear();
                    return;
                }
                guids[4].Clear();
                return;
            }
            if (guids[2] == g)
            {
                if (guids[3])
                {
                    guids[2] = guids[3];
                }
                else
                {
                    guids[2].Clear();
                    return;
                }
                if (guids[4])
                {
                    guids[3] = guids[4];
                }
                else
                {
                    guids[3].Clear();
                    return;
                }
                guids[4].Clear();
                return;
            }
            if (guids[3] == g)
            {
                if (guids[4])
                {
                    guids[3] = guids[4];
                }
                else
                {
                    guids[3].Clear();
                    return;
                }
                guids[4].Clear();
                return;
            }
            if (guids[4] == g)
            {
                guids[4].Clear();
            }
        }
References guids.
Referenced by lfg::LFGMgr::RemoveProposal().
size()
uint8 lfg::Lfg5Guids::size () const inline
        {
            if (guids[2])
            {
                if (guids[4])
                {
                    return 5;
                }
                else if (guids[3])
                {
                    return 4;
                }
                return 3;
            }
            else if (guids[1])
            {
                return 2;
            }
            else if (guids[0])
            {
                return 1;
            }
            return 0;
        }
References guids.
Referenced by lfg::LFGQueue::CheckCompatibility(), and lfg::LFGQueue::UpdateBestCompatibleInQueue().
toString()
std::string lfg::Lfg5Guids::toString () const inline
        {
            std::ostringstream o;
            o << guids[0].ToString() << "," << guids[1].ToString() << "," << guids[2].ToString() << "," << guids[3].ToString() << "," << guids[4].ToString() << ":" << (roles ? 1 : 0);
            return o.str();
        }
References guids, and roles.
Referenced by lfg::LFGQueue::AddToCompatibles(), lfg::LFGQueue::CheckCompatibility(), and lfg::LFGQueue::UpdateBestCompatibleInQueue().
Member Data Documentation
guids
std::array<ObjectGuid, 5> lfg::Lfg5Guids::guids = { }
Referenced by lfg::LFGMgr::AllQueued(), lfg::LFGQueue::CheckCompatibility(), clear(), empty(), force_insert_front(), front(), hasGuid(), insert(), Lfg5Guids(), operator<(), operator=(), operator==(), remove(), lfg::LFGMgr::RemoveProposal(), size(), toString(), and lfg::LFGMgr::UpdateProposal().
roles
LfgRolesMap* lfg::Lfg5Guids::roles
Referenced by addRoles(), Lfg5Guids(), operator=(), toString(), lfg::LFGQueue::UpdateBestCompatibleInQueue(), and ~Lfg5Guids().