AzerothCore: Corpse Class Reference
Corpse Class Reference
#include "Corpse.h"
Public Member Functions
Corpse (CorpseType type=CORPSE_BONES)
~Corpse () override
void AddToWorld () override
void RemoveFromWorld () override
void BuildValuesUpdate (uint8 updateType, ByteBuffer *data, Player *target) override
bool Create (ObjectGuid::LowType guidlow)
bool Create (ObjectGuid::LowType guidlow, Player *owner)
void SaveToDB ()
bool LoadCorpseFromDB (ObjectGuid::LowType guid, Field *fields)
void DeleteFromDB (CharacterDatabaseTransaction trans)
ObjectGuid GetOwnerGUID () const
time_t const & GetGhostTime () const
void ResetGhostTime ()
CorpseType GetType () const
CellCoord const & GetCellCoord () const
void SetCellCoord (CellCoord const &cellCoord)
bool IsExpired (time_t t) const
Public Member Functions inherited from WorldObject
~WorldObject () override
virtual void Update (uint32)
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void AddToWorld () override
void RemoveFromWorld () override
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, WorldObject const *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle, bool disableWarning=false)
Position GetNearPosition (float dist, float angle, bool disableWarning=false)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius, bool disableWarning=false)
void GetContactPoint (WorldObject const *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (WorldObject const *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
virtual float GetCombatReach () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
virtual void SetPhaseMask (uint32 newPhaseMask, bool update)
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
virtual std::string const & GetNameForLocaleIdx (LocaleConstant) const
float GetDistance (WorldObject const *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (WorldObject const *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (WorldObject const *obj) const
bool IsSelfOrInSameMap (WorldObject const *obj) const
bool IsInMap (WorldObject const *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinLOS (float x, float y, float z, VMAP::ModelIgnoreFlags ignoreFlags=VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, VMAP::ModelIgnoreFlags ignoreFlags=VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
Position GetHitSpherePointFor (Position const &dest, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (WorldObject const *obj1, WorldObject const *obj2, float size=0) const
virtual void CleanupsBeforeDelete (bool finalCleanup=true)
virtual void SendMessageToSet (WorldPacket const *data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const *data, float dist, bool self) const
virtual void SendMessageToSet (WorldPacket const *data, Player const *skipped_rcvr) const
virtual uint8 getLevelForTarget (WorldObject const *) const
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayRadiusSound (uint32 sound_id, float radius)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void PlayRadiusMusic (uint32 music_id, float radius)
void SendObjectDeSpawnAnim (ObjectGuid guid)
virtual void SaveRespawnTime ()
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (WorldObject const *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr, bool visibleBySummonerOnly=false) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr, bool visibleBySummonerOnly=false)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true, GOSummonType summonType=GO_SUMMON_TIMED_OR_CORPSE_DESPAWN)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
void DestroyForNearbyPlayers ()
virtual void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false)
void BuildUpdate (UpdateDataMapType &data_map, UpdatePlayerSet &player_set) override
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
bool IsFarVisible () const
bool IsVisibilityOverridden () const
void SetVisibilityDistanceOverride (VisibilityDistanceType type)
void SetWorldObject (bool apply)
bool IsPermanentWorldObject () const
bool IsWorldObject () const
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
virtual ObjectGuid GetTransGUID () const
void SetTransport (Transport *t)
virtual float GetStationaryX () const
virtual float GetStationaryY () const
virtual float GetStationaryZ () const
virtual float GetStationaryO () const
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
virtual float GetCollisionHeight () const
virtual float GetCollisionWidth () const
virtual float GetCollisionRadius () const
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
void RemoveAllowedLooter (ObjectGuid guid)
std::string GetDebugInfo () const override
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
virtual void AddToWorld ()
virtual void RemoveFromWorld ()
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
virtual void SetObjectScale (float scale)
virtual uint32 GetDynamicFlags () const
bool HasDynamicFlag (uint32 flag) const
virtual void SetDynamicFlag (uint32 flag)
virtual void RemoveDynamicFlag (uint32 flag)
virtual void ReplaceAllDynamicFlags (uint32 flag)
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target)
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target)
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
virtual bool hasQuest (uint32) const
virtual bool hasInvolvedQuest (uint32) const
virtual void BuildUpdate (UpdateDataMapType &, UpdatePlayerSet &)
void BuildFieldsUpdate (Player *, UpdateDataMapType &)
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
bool IsCreature () const
Creature * ToCreature ()
Creature const * ToCreature () const
bool IsUnit () const
Unit * ToUnit ()
Unit const * ToUnit () const
bool IsGameObject () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
bool IsCorpse () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
bool IsDynamicObject () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
bool IsItem () const
virtual std::string GetDebugInfo () const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
std::string GetDebugInfo () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
Position (Position &&)=default
Position & operator= (const Position &)=default
Position & operator= (Position &&)=default
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (Position const *pos, float width) const
std::string ToString () const
Public Member Functions inherited from GridObject< Corpse >
bool IsInGrid () const
void AddToGrid (GridRefMgr< Corpse > &m)
void RemoveFromGrid ()
Static Public Member Functions
static void DeleteFromDB (ObjectGuid const ownerGuid, CharacterDatabaseTransaction trans)
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Public Attributes
Loot loot
Player * lootRecipient
Public Attributes inherited from WorldObject
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
ElunaEventProcessor * elunaEvents
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Private Attributes
CorpseType m_type
time_t m_time
CellCoord _cellCoord
Additional Inherited Members
Protected Member Functions inherited from WorldObject
WorldObject (bool isWorldObject)
virtual void ProcessPositionDataChanged (PositionFullTerrainStatus const &data)
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsNeverVisible () const
virtual bool IsAlwaysVisibleFor (WorldObject const *) const
virtual bool IsInvisibleDueToDespawn () const
virtual bool IsAlwaysDetectableFor (WorldObject const *) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
bool _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
virtual void BuildValuesUpdate (uint8 updateType, ByteBuffer *data, Player *target)
virtual void AddToObjectUpdate ()=0
virtual void RemoveFromObjectUpdate ()=0
void AddToObjectUpdateIfNeeded ()
Protected Attributes inherited from WorldObject
std::string m_name
bool m_isActive
bool m_isFarVisible
Optional< float > m_visibilityDistanceOverride
const bool m_isWorldObject
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Detailed Description
Constructor & Destructor Documentation
Corpse()
Corpse::Corpse (CorpseType type = CORPSE_BONES) explicit
                              : WorldObject(type != CORPSE_BONES), m_type(type)
{
    m_objectType |= TYPEMASK_CORPSE;
    m_objectTypeId = TYPEID_CORPSE;
    m_updateFlag = (UPDATEFLAG_LOWGUID | UPDATEFLAG_STATIONARY_POSITION | UPDATEFLAG_POSITION);
    m_valuesCount = CORPSE_END;
    m_time = GameTime::GetGameTime().count();
    lootRecipient = nullptr;
}
References CORPSE_END, GameTime::GetGameTime(), lootRecipient, Object::m_objectType, Object::m_objectTypeId, m_time, Object::m_updateFlag, Object::m_valuesCount, TYPEID_CORPSE, TYPEMASK_CORPSE, UPDATEFLAG_LOWGUID, UPDATEFLAG_POSITION, and UPDATEFLAG_STATIONARY_POSITION.
~Corpse()
Corpse::~Corpse () override
{
}
Member Function Documentation
AddToWorld()
void Corpse::AddToWorld () override virtual
Register the corpse for guid lookup
Reimplemented from Object.
{
    if (!IsInWorld())
        GetMap()->GetObjectsStore().Insert<Corpse>(GetGUID(), this);
    Object::AddToWorld();
}
References Object::AddToWorld(), Object::GetGUID(), WorldObject::GetMap(), Map::GetObjectsStore(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Insert(), and Object::IsInWorld().
BuildValuesUpdate()
void Corpse::BuildValuesUpdate (uint8 updateType, ByteBuffer * data, Player * target) override virtual
Reimplemented from Object.
{
    if (!target)
        return;
    ByteBuffer fieldBuffer;
    UpdateMask updateMask;
    updateMask.SetCount(m_valuesCount);
    uint32* flags = nullptr;
    uint32 visibleFlag = GetUpdateFieldData(target, flags);
    for (uint16 index = 0; index < m_valuesCount; ++index)
    {
        if (_fieldNotifyFlags & flags[index] || ((updateType == UPDATETYPE_VALUES ? _changesMask.GetBit(index) : m_uint32Values[index]) && (flags[index] & visibleFlag)))
        {
            updateMask.SetBit(index);
            if (index == CORPSE_FIELD_BYTES_1 || index == CORPSE_FIELD_BYTES_2)
            {
                Player* owner = ObjectAccessor::GetPlayer(*this, GetOwnerGUID());
                if (owner && owner != target && sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_GROUP) && owner->IsInRaidWith(target) && owner->GetTeamId() != target->GetTeamId())
                {
                    uint32 playerBytes = target->GetUInt32Value(PLAYER_BYTES);
                    uint32 playerBytes2 = target->GetUInt32Value(PLAYER_BYTES_2);
                    uint8 race = target->getRace();
                    uint8 skin = (uint8)(playerBytes);
                    uint8 face = (uint8)(playerBytes >> 8);
                    uint8 hairstyle = (uint8)(playerBytes >> 16);
                    uint8 haircolor = (uint8)(playerBytes >> 24);
                    uint8 facialhair = (uint8)(playerBytes2);
                    uint32 corpseBytes1 = ((0x00) | (race << 8) | (target->GetByteValue(PLAYER_BYTES_3, 0) << 16) | (skin << 24));
                    uint32 corpseBytes2 = ((face) | (hairstyle << 8) | (haircolor << 16) | (facialhair << 24));
                    if (index == CORPSE_FIELD_BYTES_1)
                    {
                        fieldBuffer << corpseBytes1;
                    }
                    else
                    {
                        fieldBuffer << corpseBytes2;
                    }
                }
                else
                {
                    fieldBuffer << m_uint32Values[index];
                }
            }
            else
            {
                fieldBuffer << m_uint32Values[index];
            }
        }
    }
    *data << uint8(updateMask.GetBlockCount());
    updateMask.AppendToPacket(data);
    data->append(fieldBuffer);
}
References Object::_changesMask, Object::_fieldNotifyFlags, ByteBuffer::append(), UpdateMask::AppendToPacket(), CONFIG_ALLOW_TWO_SIDE_INTERACTION_GROUP, CORPSE_FIELD_BYTES_1, CORPSE_FIELD_BYTES_2, UpdateMask::GetBit(), UpdateMask::GetBlockCount(), Object::GetByteValue(), GetOwnerGUID(), ObjectAccessor::GetPlayer(), Unit::getRace(), Player::GetTeamId(), Object::GetUInt32Value(), Object::GetUpdateFieldData(), Unit::IsInRaidWith(), Object::m_uint32Values, Object::m_valuesCount, PLAYER_BYTES, PLAYER_BYTES_2, PLAYER_BYTES_3, UpdateMask::SetBit(), UpdateMask::SetCount(), sWorld, and UPDATETYPE_VALUES.
Create() [1/2]
bool Corpse::Create (ObjectGuid::LowType guidlow)
{
    Object::_Create(guidlow, 0, HighGuid::Corpse);
    return true;
}
References Object::_Create().
Referenced by Map::ConvertCorpseToBones(), and Player::CreateCorpse().
Create() [2/2]
bool Corpse::Create (ObjectGuid::LowType guidlow, Player * owner)
{
    ASSERT(owner);
    Relocate(owner->GetPositionX(), owner->GetPositionY(), owner->GetPositionZ(), owner->GetOrientation());
    if (!IsPositionValid())
    {
        LOG_ERROR("entities.player", "Corpse (guidlow {}, owner {}) not created. Suggested coordinates isn't valid (X: {} Y: {})",
            guidlow, owner->GetName(), owner->GetPositionX(), owner->GetPositionY());
        return false;
    }
    WorldObject::_Create(guidlow, HighGuid::Corpse, owner->GetPhaseMask());
    SetObjectScale(1);
    SetGuidValue(CORPSE_FIELD_OWNER, owner->GetGUID());
    _cellCoord = Acore::ComputeCellCoord(GetPositionX(), GetPositionY());
    return true;
}
References _cellCoord, WorldObject::_Create(), ASSERT, Acore::ComputeCellCoord(), CORPSE_FIELD_OWNER, Object::GetGUID(), WorldObject::GetName(), Position::GetOrientation(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Position::IsPositionValid(), LOG_ERROR, Position::Relocate(), Object::SetGuidValue(), and Object::SetObjectScale().
DeleteFromDB() [1/2]
void Corpse::DeleteFromDB (CharacterDatabaseTransaction trans)
{
    DeleteFromDB(GetOwnerGUID(), trans);
}
References DeleteFromDB(), and GetOwnerGUID().
Referenced by Map::ConvertCorpseToBones(), DeleteFromDB(), Player::DeleteFromDB(), Player::OfflineResurrect(), Player::RemoveCorpse(), and SaveToDB().
DeleteFromDB() [2/2]
void Corpse::DeleteFromDB (ObjectGuid const ownerGuid, CharacterDatabaseTransaction trans) static
{
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CORPSE);
    stmt->SetData(0, ownerGuid.GetCounter());
    CharacterDatabase.ExecuteOrAppend(trans, stmt);
}
References CHAR_DEL_CORPSE, CharacterDatabase, ObjectGuid::GetCounter(), and PreparedStatementBase::SetData().
GetCellCoord()
CellCoord const & Corpse::GetCellCoord () const inline
{ return _cellCoord; }
References _cellCoord.
Referenced by Map::AddCorpse(), Map::ConvertCorpseToBones(), and Map::RemoveCorpse().
GetGhostTime()
time_t const & Corpse::GetGhostTime () const inline
{ return m_time; }
References m_time.
Referenced by Player::CalculateCorpseReclaimDelay(), and WorldSession::HandleReclaimCorpseOpcode().
GetOwnerGUID()
ObjectGuid Corpse::GetOwnerGUID () const inline
{ return GetGuidValue(CORPSE_FIELD_OWNER); }
References CORPSE_FIELD_OWNER, and Object::GetGuidValue().
Referenced by Map::AddCorpse(), BuildValuesUpdate(), Spell::CheckEffectTarget(), Map::ConvertCorpseToBones(), DeleteFromDB(), IsExpired(), LoadCorpseFromDB(), Map::RemoveCorpse(), and SaveToDB().
GetType()
CorpseType Corpse::GetType () const inline
{ return m_type; }
References m_type.
Referenced by Map::AddCorpse(), Player::CalculateCorpseReclaimDelay(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandleReclaimCorpseOpcode(), Acore::AnyDeadUnitObjectInRangeCheck::operator()(), Map::RemoveCorpse(), SaveToDB(), and Player::SendLoot().
IsExpired()
bool Corpse::IsExpired (time_t t) const
{
    // Deleted character
    if (!sCharacterCache->GetCharacterCacheByGuid(GetOwnerGUID()))
        return true;
    if (m_type == CORPSE_BONES)
        return m_time < t - 60 * MINUTE;
    else
        return m_time < t - 3 * DAY;
}
References CORPSE_BONES, DAY, GetOwnerGUID(), m_time, m_type, MINUTE, and sCharacterCache.
LoadCorpseFromDB()
bool Corpse::LoadCorpseFromDB (ObjectGuid::LowType guid, Field * fields)
{
    ObjectGuid::LowType ownerGuid = fields[16].Get<uint32>();
    //        0     1     2     3            4      5          6          7       8       9        10     11        12    13          14          15         16
    // SELECT posX, posY, posZ, orientation, mapId, displayId, itemCache, bytes1, bytes2, guildId, flags, dynFlags, time, corpseType, instanceId, phaseMask, guid FROM corpse WHERE mapId = ? AND instanceId = ?
    float posX   = fields[0].Get<float>();
    float posY   = fields[1].Get<float>();
    float posZ   = fields[2].Get<float>();
    float o      = fields[3].Get<float>();
    uint32 mapId = fields[4].Get<uint16>();
    Object::_Create(guid, 0, HighGuid::Corpse);
    SetObjectScale(1.0f);
    SetUInt32Value(CORPSE_FIELD_DISPLAY_ID, fields[5].Get<uint32>());
    if (!_LoadIntoDataField(fields[6].Get<std::string>(), CORPSE_FIELD_ITEM, EQUIPMENT_SLOT_END))
    {
        LOG_ERROR("entities.player", "Corpse ({}, owner: {}) is not created, given equipment info is not valid ('{}')",
            GetGUID().ToString(), GetOwnerGUID().ToString(), fields[6].Get<std::string>());
    }
    SetUInt32Value(CORPSE_FIELD_BYTES_1, fields[7].Get<uint32>());
    SetUInt32Value(CORPSE_FIELD_BYTES_2, fields[8].Get<uint32>());
    SetUInt32Value(CORPSE_FIELD_GUILD, fields[9].Get<uint32>());
    SetUInt32Value(CORPSE_FIELD_FLAGS, fields[10].Get<uint8>());
    SetUInt32Value(CORPSE_FIELD_DYNAMIC_FLAGS, fields[11].Get<uint8>());
    SetGuidValue(CORPSE_FIELD_OWNER, ObjectGuid::Create<HighGuid::Player>(ownerGuid));
    m_time = time_t(fields[12].Get<uint32>());
    uint32 instanceId  = fields[14].Get<uint32>();
    uint32 phaseMask   = fields[15].Get<uint32>();
    // place
    SetLocationInstanceId(instanceId);
    SetLocationMapId(mapId);
    SetPhaseMask(phaseMask, false);
    Relocate(posX, posY, posZ, o);
    if (!IsPositionValid())
    {
        LOG_ERROR("entities.player", "Corpse ( {}, owner: {}) is not created, given coordinates are not valid (X: {}, Y: {}, Z: {})",
            GetGUID().ToString(), GetOwnerGUID().ToString(), posX, posY, posZ);
        return false;
    }
    _cellCoord = Acore::ComputeCellCoord(GetPositionX(), GetPositionY());
    return true;
}
References _cellCoord, Object::_Create(), Object::_LoadIntoDataField(), Acore::ComputeCellCoord(), CORPSE_FIELD_BYTES_1, CORPSE_FIELD_BYTES_2, CORPSE_FIELD_DISPLAY_ID, CORPSE_FIELD_DYNAMIC_FLAGS, CORPSE_FIELD_FLAGS, CORPSE_FIELD_GUILD, CORPSE_FIELD_ITEM, CORPSE_FIELD_OWNER, EQUIPMENT_SLOT_END, Field::Get(), Object::GetGUID(), GetOwnerGUID(), Position::GetPositionX(), Position::GetPositionY(), Position::IsPositionValid(), LOG_ERROR, m_time, Position::Relocate(), Object::SetGuidValue(), WorldObject::SetLocationInstanceId(), WorldObject::SetLocationMapId(), Object::SetObjectScale(), WorldObject::SetPhaseMask(), Object::SetUInt32Value(), and Position::ToString().
Referenced by Map::LoadCorpseData().
RemoveFromWorld()
void Corpse::RemoveFromWorld () override virtual
Remove the corpse from the accessor
Reimplemented from Object.
{
    if (IsInWorld())
        GetMap()->GetObjectsStore().Remove<Corpse>(GetGUID());
    WorldObject::RemoveFromWorld();
}
References Object::GetGUID(), WorldObject::GetMap(), Map::GetObjectsStore(), Object::IsInWorld(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Remove(), and WorldObject::RemoveFromWorld().
Referenced by Player::RemoveCorpse(), Map::RemoveCorpse(), and Map::UnloadAll().
ResetGhostTime()
void Corpse::ResetGhostTime ()
{
    m_time = GameTime::GetGameTime().count();
}
References GameTime::GetGameTime(), and m_time.
Referenced by Player::BuildPlayerRepop().
SaveToDB()
void Corpse::SaveToDB ()
{
    // prevent DB data inconsistence problems and duplicates
    CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
    DeleteFromDB(trans);
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CORPSE);
    stmt->SetData(0, GetOwnerGUID().GetCounter());                            // guid
    stmt->SetData (1, GetPositionX());                                         // posX
    stmt->SetData (2, GetPositionY());                                         // posY
    stmt->SetData (3, GetPositionZ());                                         // posZ
    stmt->SetData (4, GetOrientation());                                       // orientation
    stmt->SetData(5, GetMapId());                                             // mapId
    stmt->SetData(6, GetUInt32Value(CORPSE_FIELD_DISPLAY_ID));                // displayId
    stmt->SetData(7, _ConcatFields(CORPSE_FIELD_ITEM, EQUIPMENT_SLOT_END));   // itemCache
    stmt->SetData(8, GetUInt32Value(CORPSE_FIELD_BYTES_1));                   // bytes1
    stmt->SetData(9, GetUInt32Value(CORPSE_FIELD_BYTES_2));                   // bytes2
    stmt->SetData(10, GetUInt32Value(CORPSE_FIELD_GUILD));                    // guildId
    stmt->SetData (11, GetUInt32Value(CORPSE_FIELD_FLAGS));                    // flags
    stmt->SetData (12, GetUInt32Value(CORPSE_FIELD_DYNAMIC_FLAGS));            // dynFlags
    stmt->SetData(13, uint32(m_time));                                        // time
    stmt->SetData (14, GetType());                                             // corpseType
    stmt->SetData(15, GetInstanceId());                                       // instanceId
    stmt->SetData(16, GetPhaseMask());                                        // phaseMask
    trans->Append(stmt);
    CharacterDatabase.CommitTransaction(trans);
}
References Object::_ConcatFields(), CHAR_INS_CORPSE, CharacterDatabase, CORPSE_FIELD_BYTES_1, CORPSE_FIELD_BYTES_2, CORPSE_FIELD_DISPLAY_ID, CORPSE_FIELD_DYNAMIC_FLAGS, CORPSE_FIELD_FLAGS, CORPSE_FIELD_GUILD, CORPSE_FIELD_ITEM, DeleteFromDB(), EQUIPMENT_SLOT_END, WorldObject::GetInstanceId(), WorldLocation::GetMapId(), Position::GetOrientation(), GetOwnerGUID(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetType(), Object::GetUInt32Value(), m_time, and PreparedStatementBase::SetData().
Referenced by Player::CreateCorpse().
SetCellCoord()
void Corpse::SetCellCoord (CellCoord const & cellCoord) inline
{ _cellCoord = cellCoord; }
References _cellCoord.
Referenced by Map::ConvertCorpseToBones().
Member Data Documentation
_cellCoord
CellCoord Corpse::_cellCoord private
Referenced by Create(), GetCellCoord(), LoadCorpseFromDB(), and SetCellCoord().
loot
Loot Corpse::loot
Referenced by WorldSession::DoLootRelease(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleLootMoneyOpcode(), Player::RemovedInsignia(), and Player::SendLoot().
lootRecipient
Player* Corpse::lootRecipient
Referenced by Corpse(), Player::RemovedInsignia(), and Player::SendLoot().
m_time
time_t Corpse::m_time private
Referenced by Corpse(), GetGhostTime(), IsExpired(), LoadCorpseFromDB(), ResetGhostTime(), and SaveToDB().
m_type
CorpseType Corpse::m_type private
Referenced by GetType(), and IsExpired().