AzerothCore: achievement_flu_shot_shortage Class Reference
achievement_flu_shot_shortage Class Reference
Public Member Functions
achievement_flu_shot_shortage ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
virtual bool OnCheck (Player *, Unit *, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_flu_shot_shortage()
achievement_flu_shot_shortage::achievement_flu_shot_shortage () inline
: AchievementCriteriaScript("achievement_flu_shot_shortage") { }
Member Function Documentation
OnCheck()
bool achievement_flu_shot_shortage::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
    {
        if (target && target->IsCreature())
            return target->ToCreature()->AI()->GetData(DATA_INOCULATED_STACK) < 3;
        return false;
    }
References Creature::AI(), DATA_INOCULATED_STACK, UnitAI::GetData(), Object::IsCreature(), and Object::ToCreature().