AzeorthCore: spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript Class Reference
spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_blood_queen_vampiric_bite_SpellScript)
bool Validate (SpellInfo const *) override
SpellCastResult CheckTarget ()
void OnCast (SpellMissInfo missInfo)
void HandlePresence (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
CheckTarget()
SpellCastResult spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::CheckTarget () inline private
        {
            if (GetExplTargetUnit()->GetMapId() != 631)
                return SPELL_FAILED_CANT_DO_THAT_RIGHT_NOW;
            if (IsVampire(GetExplTargetUnit()))
            {
                SetCustomCastResultMessage(SPELL_CUSTOM_ERROR_CANT_TARGET_VAMPIRES);
                return SPELL_FAILED_CUSTOM_ERROR;
            }
            if (InstanceScript* instance = GetExplTargetUnit()->GetInstanceScript())
                if (instance->GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) == IN_PROGRESS)
                    return SPELL_CAST_OK;
            return SPELL_FAILED_CANT_DO_THAT_RIGHT_NOW;
        }
References DATA_BLOOD_QUEEN_LANA_THEL, SpellScript::GetExplTargetUnit(), IN_PROGRESS, IsVampire(), SpellScript::SetCustomCastResultMessage(), SPELL_CAST_OK, SPELL_CUSTOM_ERROR_CANT_TARGET_VAMPIRES, SPELL_FAILED_CANT_DO_THAT_RIGHT_NOW, and SPELL_FAILED_CUSTOM_ERROR.
Referenced by Register().
HandlePresence()
void spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::HandlePresence (SpellEffIndex) inline private
        {
            GetHitUnit()->CastSpell(GetHitUnit(), SPELL_PRESENCE_OF_THE_DARKFALLEN_DUMMY, TRIGGERED_FULL_MASK);
            GetHitUnit()->CastSpell(GetHitUnit(), SPELL_PRESENCE_OF_THE_DARKFALLEN_SE, TRIGGERED_FULL_MASK);
        }
References Unit::CastSpell(), SpellScript::GetHitUnit(), SPELL_PRESENCE_OF_THE_DARKFALLEN_DUMMY, SPELL_PRESENCE_OF_THE_DARKFALLEN_SE, and TRIGGERED_FULL_MASK.
Referenced by Register().
OnCast()
void spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::OnCast (SpellMissInfo missInfo) inline private
        {
            if (missInfo != SPELL_MISS_NONE)
            {
                return;
            }
            if (GetCaster()->GetTypeId() != TYPEID_PLAYER || GetCaster()->GetMapId() != 631)
                return;
            InstanceScript* instance = GetCaster()->GetInstanceScript();
            if (!instance || instance->GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) != IN_PROGRESS)
                return;
            uint32 spellId = sSpellMgr->GetSpellIdForDifficulty(SPELL_FRENZIED_BLOODTHIRST, GetCaster());
            GetCaster()->RemoveAura(spellId, ObjectGuid::Empty, 0, AURA_REMOVE_BY_ENEMY_SPELL);
            GetCaster()->CastSpell(GetCaster(), SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_PLR, TRIGGERED_FULL_MASK);
            if (Aura* aura = GetCaster()->GetAura(SPELL_GUSHING_WOUND))
            {
                if (aura->GetStackAmount() == 3)
                {
                    GetCaster()->CastSpell(GetCaster(), SPELL_THIRST_QUENCHED, TRIGGERED_FULL_MASK);
                    GetCaster()->RemoveAura(aura);
                }
                else
                    GetCaster()->CastSpell(GetCaster(), SPELL_GUSHING_WOUND, TRIGGERED_FULL_MASK);
            }
            if (InstanceScript* instance = GetCaster()->GetInstanceScript())
                if (Creature* bloodQueen = ObjectAccessor::GetCreature(*GetCaster(), instance->GetGuidData(DATA_BLOOD_QUEEN_LANA_THEL)))
                    bloodQueen->AI()->SetGUID(GetHitUnit()->GetGUID(), GUID_VAMPIRE);
        }
References AURA_REMOVE_BY_ENEMY_SPELL, Unit::CastSpell(), DATA_BLOOD_QUEEN_LANA_THEL, ObjectGuid::Empty, InstanceScript::GetBossState(), SpellScript::GetCaster(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), SpellScript::GetHitUnit(), WorldObject::GetInstanceScript(), GUID_VAMPIRE, IN_PROGRESS, Unit::RemoveAura(), SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_PLR, SPELL_FRENZIED_BLOODTHIRST, SPELL_GUSHING_WOUND, SPELL_MISS_NONE, SPELL_THIRST_QUENCHED, sSpellMgr, TRIGGERED_FULL_MASK, and TYPEID_PLAYER.
PrepareSpellScript()
spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::PrepareSpellScript (spell_blood_queen_vampiric_bite_SpellScript) private
Register()
void spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::Register () inline override private virtual
Implements _SpellScript.
        {
            OnCheckCast += SpellCheckCastFn(spell_blood_queen_vampiric_bite_SpellScript::CheckTarget);
            BeforeHit += BeforeSpellHitFn(spell_blood_queen_vampiric_bite_SpellScript::OnCast);
            OnEffectHitTarget += SpellEffectFn(spell_blood_queen_vampiric_bite_SpellScript::HandlePresence, EFFECT_1, SPELL_EFFECT_TRIGGER_SPELL);
        }
References SpellScript::BeforeHit, BeforeSpellHitFn, CheckTarget(), EFFECT_1, HandlePresence(), SpellScript::OnCast, SpellScript::OnCheckCast, SpellScript::OnEffectHitTarget, SPELL_EFFECT_TRIGGER_SPELL, SpellCheckCastFn, and SpellEffectFn.
Validate()
bool spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
        {
            return ValidateSpellInfo(
                {
                    SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_PLR,
                    SPELL_FRENZIED_BLOODTHIRST,
                    SPELL_PRESENCE_OF_THE_DARKFALLEN_DUMMY
                });
        }
References SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_PLR, SPELL_FRENZIED_BLOODTHIRST, SPELL_PRESENCE_OF_THE_DARKFALLEN_DUMMY, and _SpellScript::ValidateSpellInfo().