AzerothCore: PetLoadQueryHolder Class Reference
PetLoadQueryHolder Class Reference
Public Types
enum {
DECLINED_NAMES ,
AURAS ,
SPELLS ,
COOLDOWNS ,
MAX
}
Public Member Functions
PetLoadQueryHolder (ObjectGuid::LowType ownerGuid, uint32 petNumber)
Public Member Functions inherited from SQLQueryHolder< T >
bool SetPreparedQuery (std::size_t index, PreparedStatement< T > *stmt)
Public Member Functions inherited from SQLQueryHolderBase
SQLQueryHolderBase ()=default
virtual ~SQLQueryHolderBase ()
void SetSize (std::size_t size)
PreparedQueryResult GetPreparedResult (std::size_t index) const
void SetPreparedResult (std::size_t index, PreparedResultSet *result)
Additional Inherited Members
Protected Member Functions inherited from SQLQueryHolderBase
bool SetPreparedQueryImpl (std::size_t index, PreparedStatementBase *stmt)
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
DECLINED_NAMES
AURAS
SPELLS
COOLDOWNS
MAX
    {
        DECLINED_NAMES,
        AURAS,
        SPELLS,
        COOLDOWNS,
        MAX
    };
Constructor & Destructor Documentation
PetLoadQueryHolder()
PetLoadQueryHolder::PetLoadQueryHolder (ObjectGuid::LowType ownerGuid, uint32 petNumber) inline
    {
        SetSize(MAX);
        CharacterDatabasePreparedStatement* stmt = nullptr;
        stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_PET_DECLINED_NAME);
        stmt->SetData(0, ownerGuid);
        stmt->SetData(1, petNumber);
        SetPreparedQuery(DECLINED_NAMES, stmt);
        stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_PET_AURA);
        stmt->SetData(0, petNumber);
        SetPreparedQuery(AURAS, stmt);
        stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_PET_SPELL);
        stmt->SetData(0, petNumber);
        SetPreparedQuery(SPELLS, stmt);
        stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_PET_SPELL_COOLDOWN);
        stmt->SetData(0, petNumber);
        SetPreparedQuery(COOLDOWNS, stmt);
    }
References AURAS, CHAR_SEL_PET_AURA, CHAR_SEL_PET_DECLINED_NAME, CHAR_SEL_PET_SPELL, CHAR_SEL_PET_SPELL_COOLDOWN, CharacterDatabase, COOLDOWNS, DECLINED_NAMES, MAX, PreparedStatementBase::SetData(), SQLQueryHolder< T >::SetPreparedQuery(), SQLQueryHolderBase::SetSize(), and SPELLS.