AzerothCore: NonTankTargetSelector Struct Reference
NonTankTargetSelector Struct Reference
#include "UnitAI.h"
Public Member Functions
NonTankTargetSelector (Creature *source, bool playerOnly=true)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
bool _playerOnly
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Constructor & Destructor Documentation
NonTankTargetSelector()
NonTankTargetSelector::NonTankTargetSelector (Creature * source, bool playerOnly = true) inline
: _source(source), _playerOnly(playerOnly) { }
Member Function Documentation
operator()()
bool NonTankTargetSelector::operator() (Unit const * target) const
{
    if (!target)
        return false;
    if (_playerOnly && !target->IsPlayer())
        return false;
    if (Unit* currentVictim = _source->GetThreatMgr().GetCurrentVictim())
        return target != currentVictim;
    return target != _source->GetVictim();
}
References _playerOnly, _source, ThreatMgr::GetCurrentVictim(), Unit::GetThreatMgr(), Unit::GetVictim(), and Object::IsPlayer().
Member Data Documentation
_playerOnly
bool NonTankTargetSelector::_playerOnly private
Referenced by operator()().
_source
Creature const* NonTankTargetSelector::_source private
Referenced by operator()().