AzeorthCore: npc_eris_hevenfire::npc_eris_hevenfireAI Struct Reference
npc_eris_hevenfire::npc_eris_hevenfireAI Struct Reference
Public Member Functions
npc_eris_hevenfireAI (Creature *c)
void Reset () override
void SetData (uint32 faction, uint32) override
void SetGUID (ObjectGuid guid, int32) override
bool CanBeSeen (Player const *player) override
void SummonArchers ()
void SummonPeasants ()
void JustSummoned (Creature *creature) override
void DoAction (int32 action) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
SummonList summons
EventMap events
ObjectGuid _playerGUID
uint8 _counter
uint8 _savedCount
uint8 _deathCount
bool _spoken
uint32 _faction
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_eris_hevenfireAI()
npc_eris_hevenfire::npc_eris_hevenfireAI::npc_eris_hevenfireAI (Creature * c) inline
: ScriptedAI(c), summons(me) {}
Member Function Documentation
CanBeSeen()
bool npc_eris_hevenfire::npc_eris_hevenfireAI::CanBeSeen (Player const * player) inline override virtual
Reimplemented from CreatureAI.
        {
            // requires this trinket to be seen
            return player->HasItemOrGemWithIdEquipped(ITEM_EYE_OF_DIVINITY, 1);
        }
References Player::HasItemOrGemWithIdEquipped(), and ITEM_EYE_OF_DIVINITY.
DoAction()
void npc_eris_hevenfire::npc_eris_hevenfireAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == 1)
                _savedCount++;
            else
                _deathCount++;
            if (_savedCount > 49)
            {
                Talk(1);
                if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
                    player->AreaExploredOrEventHappens(QUEST_BALANCE_OF_LIGHT_AND_SHADOW);
                EnterEvadeMode();
                return;
            }
            else if (_deathCount > 14)
            {
                Talk(2);
                if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
                    player->FailQuest(QUEST_BALANCE_OF_LIGHT_AND_SHADOW);
                EnterEvadeMode();
                return;
            }
            if (action == 1 && !_spoken)
            {
                _spoken = true;
                Talk(0);
                me->CastSpell(me, SPELL_ERIS_BLESSING, false);
            }
        }
References _deathCount, _playerGUID, _savedCount, _spoken, Unit::CastSpell(), CreatureAI::EnterEvadeMode(), ObjectAccessor::GetPlayer(), ScriptedAI::me, QUEST_BALANCE_OF_LIGHT_AND_SHADOW, and SPELL_ERIS_BLESSING.
JustSummoned()
void npc_eris_hevenfire::npc_eris_hevenfireAI::JustSummoned (Creature * creature) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(creature);
            if (creature->GetEntry() == NPC_INJURED_PEASANT || creature->GetEntry() == NPC_PLAGUED_PEASANT)
            {
                creature->SetFaction(_faction);
                if (!_spoken)
                {
                    _spoken = true;
                    creature->AI()->Talk(0);
                }
                if (creature->GetEntry() == NPC_PLAGUED_PEASANT)
                    creature->CastSpell(creature, SPELL_SEETHING_PLAGUE, true);
                float x = 3324 + frand(-3.0f, 3.0f);
                float y = -2966 + frand(-3.0f, 3.0f);
                float z = 159.65f;
                creature->SetWalk(true);
                creature->GetMotionMaster()->MovePoint(0, x, y, z);
                creature->SetUnitFlag(UNIT_FLAG_PLAYER_CONTROLLED);
            }
        }
References _faction, _spoken, Creature::AI(), Unit::CastSpell(), frand(), Object::GetEntry(), Unit::GetMotionMaster(), MotionMaster::MovePoint(), NPC_INJURED_PEASANT, NPC_PLAGUED_PEASANT, Unit::SetFaction(), Unit::SetUnitFlag(), Creature::SetWalk(), SPELL_SEETHING_PLAGUE, SummonList::Summon(), summons, CreatureAI::Talk(), and UNIT_FLAG_PLAYER_CONTROLLED.
Reset()
void npc_eris_hevenfire::npc_eris_hevenfireAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _faction = 0;
            _spoken = false;
            _savedCount = 0;
            _deathCount = 0;
            _counter = 0;
            _playerGUID.Clear();
            events.Reset();
            summons.DespawnAll();
            me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
        }
References _counter, _deathCount, _faction, _playerGUID, _savedCount, _spoken, ObjectGuid::Clear(), SummonList::DespawnAll(), ScriptedAI::me, Unit::ReplaceAllNpcFlags(), summons, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAG_QUESTGIVER.
SetData()
void npc_eris_hevenfire::npc_eris_hevenfireAI::SetData (uint32 faction, uint32) inline override virtual
Reimplemented from UnitAI.
        {
            _faction = faction;
        }
References _faction.
SetGUID()
void npc_eris_hevenfire::npc_eris_hevenfireAI::SetGUID (ObjectGuid guid, int32) inline override virtual
Reimplemented from UnitAI.
        {
            _playerGUID = guid;
            me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
            events.Reset();
            summons.DespawnAll();
            events.ScheduleEvent(EVENT_CHECK_PLAYER, 1000);
            events.ScheduleEvent(EVENT_SUMMON_ARCHERS, 4000);
            events.ScheduleEvent(EVENT_SUMMON_PEASANTS, 8000);
        }
References _playerGUID, SummonList::DespawnAll(), EVENT_CHECK_PLAYER, EVENT_SUMMON_ARCHERS, EVENT_SUMMON_PEASANTS, ScriptedAI::me, Unit::ReplaceAllNpcFlags(), summons, and UNIT_NPC_FLAG_NONE.
SummonArchers()
void npc_eris_hevenfire::npc_eris_hevenfireAI::SummonArchers () inline
        {
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3330.18f, -3078.97f, 171.814f, 0.799463f);
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3328.34f, -3017.88f, 171.544f, 6.26976f);
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3333.71f, -3052.4f, 174.171f, 0.391055f);
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3316.22f, -3035.49f, 166.428f, 0.163288f);
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3371.54f, -3067.75f, 174.942f, 1.96578f);
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3379.39f, -3060.11f, 181.617f, 2.82186f);
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3352.44f, -3079.01f, 179.07f, 1.32175f);
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3363.07f, -3077.43f, 183.0f, 1.78121f);
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3348.11f, -2991.02f, 172.304f, 4.07064f);
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3377.42f, -3039.77f, 172.594f, 3.20671f);
            me->SummonCreature(NPC_SCOURGE_ARCHER, 3363.87f, -3010.4f, 185.387f, 3.81932f);
        }
References ScriptedAI::me, NPC_SCOURGE_ARCHER, and WorldObject::SummonCreature().
Referenced by UpdateAI().
SummonPeasants()
void npc_eris_hevenfire::npc_eris_hevenfireAI::SummonPeasants () inline
        {
            for (uint8 i = 0; i < 12; ++i)
            {
                float x = 3358 + frand(-6.0f, 6.0f);
                float y = -3049 + frand(-6.0f, 6.0f);
                float z = 165.25;
                float o = 2.0;
                me->SummonCreature(roll_chance_i(5) ? NPC_PLAGUED_PEASANT : NPC_INJURED_PEASANT, x, y, z, o, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 2 * MINUTE * IN_MILLISECONDS);
            }
        }
References frand(), IN_MILLISECONDS, ScriptedAI::me, MINUTE, NPC_INJURED_PEASANT, NPC_PLAGUED_PEASANT, roll_chance_i(), WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN.
Referenced by UpdateAI().
UpdateAI()
void npc_eris_hevenfire::npc_eris_hevenfireAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_CHECK_PLAYER:
                    {
                        Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID);
                        if (!player || me->GetDistance2d(player) > 100.0f)
{
                            EnterEvadeMode();
                            return;
                        }
                        events.RepeatEvent(2000);
                        break;
                    }
                case EVENT_SUMMON_ARCHERS:
                    SummonArchers();
                    break;
                case EVENT_SUMMON_PEASANTS:
                    _spoken = false;
                    SummonPeasants();
                    _spoken = false;
                    events.RepeatEvent(60 * IN_MILLISECONDS);
                    break;
            }
        }
References _playerGUID, _spoken, CreatureAI::EnterEvadeMode(), EVENT_CHECK_PLAYER, EVENT_SUMMON_ARCHERS, EVENT_SUMMON_PEASANTS, WorldObject::GetDistance2d(), ObjectAccessor::GetPlayer(), IN_MILLISECONDS, ScriptedAI::me, SummonArchers(), and SummonPeasants().
Member Data Documentation
_counter
uint8 npc_eris_hevenfire::npc_eris_hevenfireAI::_counter
Referenced by Reset().
_deathCount
uint8 npc_eris_hevenfire::npc_eris_hevenfireAI::_deathCount
Referenced by DoAction(), and Reset().
_faction
uint32 npc_eris_hevenfire::npc_eris_hevenfireAI::_faction
Referenced by JustSummoned(), Reset(), and SetData().
_playerGUID
ObjectGuid npc_eris_hevenfire::npc_eris_hevenfireAI::_playerGUID
Referenced by DoAction(), Reset(), SetGUID(), and UpdateAI().
_savedCount
uint8 npc_eris_hevenfire::npc_eris_hevenfireAI::_savedCount
Referenced by DoAction(), and Reset().
_spoken
bool npc_eris_hevenfire::npc_eris_hevenfireAI::_spoken
Referenced by DoAction(), JustSummoned(), Reset(), and UpdateAI().
events
EventMap npc_eris_hevenfire::npc_eris_hevenfireAI::events
summons
SummonList npc_eris_hevenfire::npc_eris_hevenfireAI::summons
Referenced by JustSummoned(), Reset(), and SetGUID().