AzerothCore: ChatLogScript Class Reference
ChatLogScript Class Reference
Public Member Functions
ChatLogScript ()
void OnChat (Player *player, uint32 type, uint32 lang, std::string &msg) override
void OnChat (Player *player, uint32, uint32 lang, std::string &msg, Player *receiver) override
void OnChat (Player *player, uint32 type, uint32 lang, std::string &msg, Group *group) override
void OnChat (Player *player, uint32 type, uint32 lang, std::string &msg, Guild *guild) override
void OnChat (Player *player, uint32, uint32, std::string &msg, Channel *channel) override
Public Member Functions inherited from PlayerScript
virtual void OnPlayerJustDied (Player *)
virtual void OnCalculateTalentsPoints (Player const *, uint32 &)
virtual void OnPlayerReleasedGhost (Player *)
virtual void OnSendInitialPacketsBeforeAddToMap (Player *, WorldPacket &)
virtual void OnBattlegroundDesertion (Player *, BattlegroundDesertionType const)
virtual void OnPlayerCompleteQuest (Player *, Quest const *)
virtual void OnPVPKill (Player *, Player *)
virtual void OnPlayerPVPFlagChange (Player *, bool)
virtual void OnCreatureKill (Player *, Creature *)
virtual void OnCreatureKilledByPet (Player *, Creature *)
virtual void OnPlayerKilledByCreature (Creature *, Player *)
virtual void OnLevelChanged (Player *, uint8)
virtual void OnFreeTalentPointsChanged (Player *, uint32)
virtual void OnTalentsReset (Player *, bool)
virtual void OnAfterSpecSlotChanged (Player *, uint8)
virtual void OnBeforeUpdate (Player *, uint32)
virtual void OnUpdate (Player *, uint32)
virtual void OnMoneyChanged (Player *, int32 &)
virtual void OnBeforeLootMoney (Player *, Loot *)
virtual void OnGiveXP (Player *, uint32 &, Unit *, uint8)
virtual bool OnReputationChange (Player *, uint32, int32 &, bool)
virtual void OnReputationRankChange (Player *, uint32, ReputationRank, ReputationRank, bool)
virtual void OnLearnSpell (Player *, uint32)
virtual void OnForgotSpell (Player *, uint32)
virtual void OnDuelRequest (Player *, Player *)
virtual void OnDuelStart (Player *, Player *)
virtual void OnDuelEnd (Player *, Player *, DuelCompleteType)
virtual void OnChat (Player *, uint32, uint32, std::string &)
virtual void OnBeforeSendChatMessage (Player *, uint32 &, uint32 &, std::string &)
virtual void OnChat (Player *, uint32, uint32, std::string &, Player *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Group *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Guild *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Channel *)
virtual void OnEmote (Player *, uint32)
virtual void OnTextEmote (Player *, uint32, uint32, ObjectGuid)
virtual void OnSpellCast (Player *, Spell *, bool)
virtual void OnLoadFromDB (Player *)
virtual void OnLogin (Player *)
virtual void OnBeforeLogout (Player *)
virtual void OnLogout (Player *)
virtual void OnCreate (Player *)
virtual void OnDelete (ObjectGuid, uint32)
virtual void OnFailedDelete (ObjectGuid, uint32)
virtual void OnSave (Player *)
virtual void OnBindToInstance (Player *, Difficulty, uint32, bool)
virtual void OnUpdateZone (Player *, uint32, uint32)
virtual void OnUpdateArea (Player *, uint32, uint32)
virtual void OnMapChanged (Player *)
virtual bool OnBeforeTeleport (Player *, uint32, float, float, float, float, uint32, Unit *)
virtual void OnUpdateFaction (Player *)
virtual void OnAddToBattleground (Player *, Battleground *)
virtual void OnQueueRandomDungeon (Player *, uint32 &)
virtual void OnRemoveFromBattleground (Player *, Battleground *)
virtual void OnAchiComplete (Player *, AchievementEntry const *)
virtual bool OnBeforeAchiComplete (Player *, AchievementEntry const *)
virtual void OnCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual bool OnBeforeCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual void OnAchiSave (CharacterDatabaseTransaction, Player *, uint16, CompletedAchievementData)
virtual void OnCriteriaSave (CharacterDatabaseTransaction, Player *, uint16, CriteriaProgress)
virtual void OnGossipSelect (Player *, uint32, uint32, uint32)
virtual void OnGossipSelectCode (Player *, uint32, uint32, uint32, const char *)
virtual void OnBeingCharmed (Player *, Unit *, uint32, uint32)
virtual void OnAfterSetVisibleItemSlot (Player *, uint8, Item *)
virtual void OnAfterMoveItemFromInventory (Player *, Item *, uint8, uint8, bool)
virtual void OnEquip (Player *, Item *, uint8, uint8, bool)
virtual void OnPlayerJoinBG (Player *)
virtual void OnPlayerJoinArena (Player *)
virtual void OnGetMaxPersonalArenaRatingRequirement (Player const *, uint32, uint32 &) const
virtual void OnLootItem (Player *, Item *, uint32, ObjectGuid)
virtual void OnBeforeFillQuestLootItem (Player *, LootItem &)
virtual void OnStoreNewItem (Player *, Item *, uint32)
virtual void OnCreateItem (Player *, Item *, uint32)
virtual void OnQuestRewardItem (Player *, Item *, uint32)
virtual bool CanPlaceAuctionBid (Player *, AuctionEntry *)
virtual void OnGroupRollRewardItem (Player *, Item *, uint32, RollVote, Roll *)
virtual bool OnBeforeOpenItem (Player *, Item *)
virtual bool OnBeforeQuestComplete (Player *, uint32)
virtual void OnQuestComputeXP (Player *, Quest const *, uint32 &)
virtual void OnBeforeDurabilityRepair (Player *, ObjectGuid, ObjectGuid, float &, uint8)
virtual void OnBeforeBuyItemFromVendor (Player *, ObjectGuid, uint32, uint32 &, uint8, uint8, uint8)
virtual void OnBeforeStoreOrEquipNewItem (Player *, uint32, uint32 &, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnAfterStoreOrEquipNewItem (Player *, uint32, Item *, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnAfterUpdateMaxPower (Player *, Powers &, float &)
virtual void OnAfterUpdateMaxHealth (Player *, float &)
virtual void OnBeforeUpdateAttackPowerAndDamage (Player *, float &, float &, bool)
virtual void OnAfterUpdateAttackPowerAndDamage (Player *, float &, float &, float &, float &, bool)
virtual void OnBeforeInitTalentForLevel (Player *, uint8 &, uint32 &)
virtual void OnFirstLogin (Player *)
virtual void OnSetMaxLevel (Player *, uint32 &)
virtual bool CanJoinInBattlegroundQueue (Player *, ObjectGuid, BattlegroundTypeId, uint8, GroupJoinBattlegroundResult &)
virtual bool ShouldBeRewardedWithMoneyInsteadOfExp (Player *)
virtual void OnBeforeTempSummonInitStats (Player *, TempSummon *, uint32 &)
virtual void OnBeforeGuardianInitStatsForLevel (Player *, Guardian *, CreatureTemplate const *, PetType &)
virtual void OnAfterGuardianInitStatsForLevel (Player *, Guardian *)
virtual void OnBeforeLoadPetFromDB (Player *, uint32 &, uint32 &, bool &, bool &)
virtual bool CanJoinInArenaQueue (Player *, ObjectGuid, uint8, BattlegroundTypeId, uint8, uint8, GroupJoinBattlegroundResult &)
virtual bool CanBattleFieldPort (Player *, uint8, BattlegroundTypeId, uint8)
virtual bool CanGroupInvite (Player *, std::string &)
virtual bool CanGroupAccept (Player *, Group *)
virtual bool CanSellItem (Player *, Item *, Creature *)
virtual bool CanSendMail (Player *, ObjectGuid, ObjectGuid, std::string &, std::string &, uint32, uint32, Item *)
virtual void PetitionBuy (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void PetitionShowList (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void OnRewardKillRewarder (Player *, KillRewarder *, bool, float &)
virtual bool CanGiveMailRewardAtGiveLevel (Player *, uint8)
virtual void OnDeleteFromDB (CharacterDatabaseTransaction, uint32)
virtual bool CanRepopAtGraveyard (Player *)
virtual Optional< bool > OnPlayerIsClass (Player const *, Classes, ClassContext)
virtual void OnGetMaxSkillValue (Player *, uint32, int32 &, bool)
virtual bool OnPlayerHasActivePowerType (Player const *, Powers)
virtual void OnUpdateGatheringSkill (Player *, uint32, uint32, uint32, uint32, uint32, uint32 &)
This hook called before gathering skill gain is applied to the character.
virtual void OnUpdateCraftingSkill (Player *, SkillLineAbilityEntry const *, uint32, uint32 &)
This hook is called before crafting skill gain is applied to the character.
virtual bool OnUpdateFishingSkill (Player *, int32, int32, int32, int32)
virtual bool CanAreaExploreAndOutdoor (Player *)
virtual void OnVictimRewardBefore (Player *, Player *, uint32 &, uint32 &)
virtual void OnVictimRewardAfter (Player *, Player *, uint32 &, uint32 &, float &)
virtual void OnCustomScalingStatValueBefore (Player *, ItemTemplate const *, uint8, bool, uint32 &)
virtual void OnCustomScalingStatValue (Player *, ItemTemplate const *, uint32 &, int32 &, uint8, uint32, ScalingStatValuesEntry const *)
virtual void OnApplyItemModsBefore (Player *, uint8, bool, uint8, uint32, int32 &)
virtual void OnApplyEnchantmentItemModsBefore (Player *, Item *, EnchantmentSlot, bool, uint32, uint32 &)
virtual void OnApplyWeaponDamage (Player *, uint8, ItemTemplate const *, float &, float &, uint8)
virtual bool CanArmorDamageModifier (Player *)
virtual void OnGetFeralApBonus (Player *, int32 &, int32, ItemTemplate const *, ScalingStatValuesEntry const *)
virtual bool CanApplyWeaponDependentAuraDamageMod (Player *, Item *, WeaponAttackType, AuraEffect const *, bool)
virtual bool CanApplyEquipSpell (Player *, SpellInfo const *, Item *, bool, bool)
virtual bool CanApplyEquipSpellsItemSet (Player *, ItemSetEffect *)
virtual bool CanCastItemCombatSpell (Player *, Unit *, WeaponAttackType, uint32, uint32, Item *, ItemTemplate const *)
virtual bool CanCastItemUseSpell (Player *, Item *, SpellCastTargets const &, uint8, uint32)
virtual void OnApplyAmmoBonuses (Player *, ItemTemplate const *, float &)
virtual bool CanEquipItem (Player *, uint8, uint16 &, Item *, bool, bool)
virtual bool CanUnequipItem (Player *, uint16, bool)
virtual bool CanUseItem (Player *, ItemTemplate const *, InventoryResult &)
virtual bool CanSaveEquipNewItem (Player *, Item *, uint16, bool)
virtual bool CanApplyEnchantment (Player *, Item *, EnchantmentSlot, bool, bool, bool)
virtual void OnGetQuestRate (Player *, float &)
virtual bool PassedQuestKilledMonsterCredit (Player *, Quest const *, uint32, uint32, ObjectGuid)
virtual bool CheckItemInSlotAtLoadInventory (Player *, Item *, uint8, uint8 &, uint16 &)
virtual bool NotAvoidSatisfy (Player *, DungeonProgressionRequirements const *, uint32, bool)
virtual bool NotVisibleGloballyFor (Player *, Player const *)
virtual void OnGetArenaPersonalRating (Player *, uint8, uint32 &)
virtual void OnGetArenaTeamId (Player *, uint8, uint32 &)
virtual void OnIsFFAPvP (Player *, bool &)
virtual void OnFfaPvpStateUpdate (Player *, bool)
virtual void OnIsPvP (Player *, bool &)
virtual void OnGetMaxSkillValueForLevel (Player *, uint16 &)
virtual bool NotSetArenaTeamInfoField (Player *, uint8, ArenaTeamInfoType, uint32)
virtual bool CanJoinLfg (Player *, uint8, std::set< uint32 > &, const std::string &)
virtual bool CanEnterMap (Player *, MapEntry const *, InstanceTemplate const *, MapDifficulty const *, bool)
virtual bool CanInitTrade (Player *, Player *)
virtual bool CanSetTradeItem (Player *, Item *, uint8)
This hook called just before finishing the handling of the action of a player setting an item in a trade slot.
virtual void OnSetServerSideVisibility (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnSetServerSideVisibilityDetect (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnPlayerResurrect (Player *, float, bool)
virtual void OnBeforeChooseGraveyard (Player *, TeamId, bool, uint32 &)
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &)
This hook called before player sending message in default chat.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Player *)
This hook called before player sending message to other player via private.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Group *)
This hook called before player sending message to group.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Guild *)
This hook called before player sending message to guild.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Channel *)
This hook called before player sending message to channel.
virtual void OnPlayerLearnTalents (Player *, uint32, uint32, uint32)
This hook called after player learning talents.
virtual void OnPlayerEnterCombat (Player *, Unit *)
This hook called after player entering combat.
virtual void OnPlayerLeaveCombat (Player *)
This hook called after player leave combat.
virtual void OnQuestAbandon (Player *, uint32)
This hook called after player abandoning quest.
virtual bool OnCanPlayerFlyInZone (Player *, uint32, uint32, SpellInfo const *)
This hook called before other CanFlyChecks are applied.
virtual void AnticheatSetCanFlybyServer (Player *, bool)
virtual void AnticheatSetUnderACKmount (Player *)
virtual void AnticheatSetRootACKUpd (Player *)
virtual void AnticheatSetJumpingbyOpcode (Player *, bool)
virtual void AnticheatUpdateMovementInfo (Player *, MovementInfo const &)
virtual bool AnticheatHandleDoubleJump (Player *, Unit *)
virtual bool AnticheatCheckMovementInfo (Player *, MovementInfo const &, Unit *, bool)
virtual bool CanSendErrorAlreadyLooted (Player *)
This hook is called, to avoid displaying the error message that the body has already been stripped.
virtual void OnAfterCreatureLoot (Player *)
It is used when an item is taken from a creature.
virtual void OnAfterCreatureLootMoney (Player *)
After a creature's money is taken.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from PlayerScript
PlayerScript (const char *name, std::vector< uint16 > enabledHooks=std::vector< uint16 >())
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
ChatLogScript()
ChatLogScript::ChatLogScript () inline
                    :
        PlayerScript("ChatLogScript",
        {
            PLAYERHOOK_ON_CHAT,
            PLAYERHOOK_ON_CHAT_WITH_GROUP,
            PLAYERHOOK_ON_CHAT_WITH_GUILD,
            PLAYERHOOK_ON_CHAT_WITH_CHANNEL,
            PLAYERHOOK_ON_CHAT_WITH_RECEIVER
        })
    {
    }
References PLAYERHOOK_ON_CHAT, PLAYERHOOK_ON_CHAT_WITH_CHANNEL, PLAYERHOOK_ON_CHAT_WITH_GROUP, PLAYERHOOK_ON_CHAT_WITH_GUILD, and PLAYERHOOK_ON_CHAT_WITH_RECEIVER.
Member Function Documentation
OnChat() [1/5]
void ChatLogScript::OnChat (Player * player, uint32 type, uint32 lang, std::string & msg) inline override virtual
Reimplemented from PlayerScript.
    {
        std::string logType = "";
        std::string chatType = "";
        switch (type)
        {
            case CHAT_MSG_SAY:
                logType = "chat.say";
                chatType = "says";
                break;
            case CHAT_MSG_EMOTE:
                logType = "chat.emote";
                chatType = "emotes";
                break;
            case CHAT_MSG_YELL:
                logType = "chat.yell";
                chatType = "yells";
                break;
            default:
                return;
        }
        LOG_INFO(logType, "Player {} {} (language {}): {}",
            player->GetName(), chatType, lang, msg);
    }
References CHAT_MSG_EMOTE, CHAT_MSG_SAY, CHAT_MSG_YELL, WorldObject::GetName(), and LOG_INFO.
OnChat() [2/5]
void ChatLogScript::OnChat (Player * player, uint32 type, uint32 lang, std::string & msg, Group * group) inline override virtual
NOTE: LANG_ADDON can only be sent by client in "PARTY", "RAID", "GUILD", "BATTLEGROUND", "WHISPER"
Reimplemented from PlayerScript.
    {
        std::string logType = (lang != LANG_ADDON) ? "chat." : "chat.addon.";
        std::string msgType = "";
        switch (type)
        {
            case CHAT_MSG_PARTY:
            case CHAT_MSG_PARTY_LEADER:
                msgType = "party";
                break;
            case CHAT_MSG_RAID:
            case CHAT_MSG_RAID_LEADER:
            case CHAT_MSG_RAID_WARNING:
                msgType = "raid";
                break;
            case CHAT_MSG_BATTLEGROUND:
            case CHAT_MSG_BATTLEGROUND_LEADER:
                msgType = "bg";
                break;
            default:
                return;
        }
        std::string role = (type == CHAT_MSG_PARTY_LEADER || type == CHAT_MSG_RAID_LEADER || type == CHAT_MSG_BATTLEGROUND_LEADER) ? "Leader player" : "Player";
        std::string action = (type == CHAT_MSG_RAID_WARNING) ? "sends raid warning" : "tells";
        std::string targetGroup = group ? group->GetLeaderName() : "<unknown>";
        LOG_INFO(logType + msgType, "{} {} {} {} with leader {}: {}",
            role, player->GetName(), action, msgType, targetGroup, msg);
    }
References CHAT_MSG_BATTLEGROUND, CHAT_MSG_BATTLEGROUND_LEADER, CHAT_MSG_PARTY, CHAT_MSG_PARTY_LEADER, CHAT_MSG_RAID, CHAT_MSG_RAID_LEADER, CHAT_MSG_RAID_WARNING, Group::GetLeaderName(), WorldObject::GetName(), LANG_ADDON, and LOG_INFO.
OnChat() [3/5]
void ChatLogScript::OnChat (Player * player, uint32 type, uint32 lang, std::string & msg, Guild * guild) inline override virtual
NOTE: LANG_ADDON can only be sent by client in "PARTY", "RAID", "GUILD", "BATTLEGROUND", "WHISPER"
Reimplemented from PlayerScript.
    {
        std::string logType = (lang != LANG_ADDON) ? "chat." : "chat.addon.";
        std::string msgType = "";
        switch (type)
        {
            case CHAT_MSG_GUILD:
                msgType = "guild";
                break;
            case CHAT_MSG_OFFICER:
                msgType = "guild.officer";
                break;
            default:
                return;
        }
        LOG_INFO(logType + msgType, "Player {} tells {} \"{}\": {}",
            player->GetName(), msgType, guild ? guild->GetName() : "<unknown>", msg);
    }
References CHAT_MSG_GUILD, CHAT_MSG_OFFICER, WorldObject::GetName(), Guild::GetName(), LANG_ADDON, and LOG_INFO.
OnChat() [4/5]
void ChatLogScript::OnChat (Player * player, uint32 , uint32 lang, std::string & msg, Player * receiver) inline override virtual
NOTE: LANG_ADDON can only be sent by client in "PARTY", "RAID", "GUILD", "BATTLEGROUND", "WHISPER"
Reimplemented from PlayerScript.
    {
        std::string logType = (lang != LANG_ADDON) ? "chat." : "chat.addon.";
        std::string msgType = "whisper";
        LOG_INFO(logType + msgType, "Player {} {} {}: {}",
               player->GetName(), msgType, receiver ? receiver->GetName() : "<unknown>", msg);
    }
References WorldObject::GetName(), LANG_ADDON, and LOG_INFO.
OnChat() [5/5]
void ChatLogScript::OnChat (Player * player, uint32 , uint32 , std::string & msg, Channel * channel) inline override virtual
Reimplemented from PlayerScript.
    {
        bool isSystem = channel &&
                        (channel->HasFlag(CHANNEL_FLAG_TRADE) ||
                         channel->HasFlag(CHANNEL_FLAG_GENERAL) ||
                         channel->HasFlag(CHANNEL_FLAG_CITY) ||
                         channel->HasFlag(CHANNEL_FLAG_LFG));
        if (isSystem)
        {
            LOG_INFO("chat.channel", "Player {} tells channel {}: {}",
                player->GetName(), channel->GetName(), msg);
        }
        else
        {
            // Allow to log custom channels. i.e. world channel
            // in that case set config: Logger.channel.world=6,Chat
            std::string channelName = channel ? channel->GetName() : "<unknown>";
            LOG_INFO("chat.channel." + channelName, "Player {} tells channel {}: {}",
                player->GetName(), channelName, msg);
        }
    }
References CHANNEL_FLAG_CITY, CHANNEL_FLAG_GENERAL, CHANNEL_FLAG_LFG, CHANNEL_FLAG_TRADE, Channel::GetName(), WorldObject::GetName(), Channel::HasFlag(), and LOG_INFO.