AzerothCore: LinkedListHead Class Reference
LinkedListHead Class Reference
#include "LinkedList.h"
Classes
class Iterator
Public Types
typedef Iterator< LinkedListElement > iterator
Public Member Functions
LinkedListHead ()
bool IsEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Private Attributes
LinkedListElement iFirst
LinkedListElement iLast
uint32 iSize {0}
Detailed Description
Member Typedef Documentation
iterator
typedef Iterator<LinkedListElement> LinkedListHead::iterator
Constructor & Destructor Documentation
LinkedListHead()
LinkedListHead::LinkedListHead () inline
    {
        // create empty list
        iFirst.iNext = &iLast;
        iLast.iPrev = &iFirst;
    }
References iFirst, iLast, LinkedListElement::iNext, and LinkedListElement::iPrev.
Member Function Documentation
decSize()
void LinkedListHead::decSize () inline
{ --iSize; }
References iSize.
Referenced by MapReference::sourceObjectDestroyLink(), and MapReference::targetObjectDestroyLink().
getFirst() [1/2]
LinkedListElement * LinkedListHead::getFirst () inline
{ return (IsEmpty() ? nullptr : iFirst.iNext); }
References iFirst, LinkedListElement::iNext, and IsEmpty().
Referenced by RefMgr< TO, FROM >::getFirst(), and getSize().
getFirst() [2/2]
LinkedListElement const * LinkedListHead::getFirst () const inline
{ return (IsEmpty() ? nullptr : iFirst.iNext); }
References iFirst, LinkedListElement::iNext, and IsEmpty().
getLast() [1/2]
LinkedListElement * LinkedListHead::getLast () inline
{ return (IsEmpty() ? nullptr : iLast.iPrev); }
References iLast, LinkedListElement::iPrev, and IsEmpty().
Referenced by RefMgr< TO, FROM >::getLast().
getLast() [2/2]
LinkedListElement const * LinkedListHead::getLast () const inline
{ return (IsEmpty() ? nullptr : iLast.iPrev); }
References iLast, LinkedListElement::iPrev, and IsEmpty().
getSize()
uint32 LinkedListHead::getSize () const inline
    {
        if (!iSize)
        {
            uint32 result = 0;
            LinkedListElement const* e = getFirst();
            while (e)
            {
                ++result;
                e = e->next();
            }
            return result;
        }
        else
        {
            return iSize;
        }
    }
References getFirst(), iSize, and LinkedListElement::next().
Referenced by spell_yogg_saron_brain_link_aura::HandleOnEffectApply(), Group::RemoveMember(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::SelectCorruptionTarget(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT(), HostileRefMgr::threatAssist(), and boss_twin_valkyrAI::UpdateAI().
incSize()
void LinkedListHead::incSize () inline
{ ++iSize; }
References iSize.
Referenced by MapReference::targetObjectBuildLink().
insertFirst()
void LinkedListHead::insertFirst (LinkedListElement * pElem) inline
    {
        iFirst.insertAfter(pElem);
    }
References iFirst, and LinkedListElement::insertAfter().
Referenced by Unit::addFollower(), Unit::addHatedBy(), Loot::addLootValidatorRef(), Group::LinkMember(), and MapReference::targetObjectBuildLink().
insertLast()
void LinkedListHead::insertLast (LinkedListElement * pElem) inline
    {
        iLast.insertBefore(pElem);
    }
References iLast, and LinkedListElement::insertBefore().
IsEmpty()
bool LinkedListHead::IsEmpty () const inline
{ return (!iFirst.iNext->isInList()); }
References iFirst, LinkedListElement::iNext, and LinkedListElement::isInList().
Referenced by Map::AddToMap(), MotionTransport::BuildUpdate(), StaticTransport::BuildUpdate(), InstanceMap::CannotEnter(), boss_gothik::boss_gothikAI::CheckGroupSplitted(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::ChromieWhisper(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), npc_arthas::npc_arthasAI::DoAction(), ScriptedAI::DoPlayMusic(), InstanceScript::DoSendNotifyToInstance(), InstanceScript::DoUpdateWorldState(), CreatureAI::DoZoneInCombat(), boss_sapphiron::boss_sapphironAI::EnterCombatSelfFunction(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::GetCreatureEntry(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetCreatureEntry(), getFirst(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetGameObjectEntry(), getLast(), WorldSession::HandleMoveWorldportAck(), Map::HavePlayers(), boss_ichoron::boss_ichoronAI::IchoronDoCastToAllHostilePlayers(), boss_apothecary_hummel::boss_apothecary_hummelAI::JustDied(), npc_coren_direbrew::JustDied(), boss_headless_horseman::JustDied(), boss_ahune::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), WorldSession::LogoutPlayer(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnCreatureCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), Map::PlayDirectSoundToMap(), SmartScript::ProcessAction(), Map::RemoveFromMap(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::ReplaceMoiraIfSaved(), InstanceMap::Reset(), SendPacketToPlayers(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SendUpdateWorldState(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::SetData(), Map::SetZoneMusic(), Map::SetZoneOverrideLight(), Map::SetZoneWeather(), npc_arthas::npc_arthasAI::SummonNextWave(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::Update(), Unit::Update(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateWorldState(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateWorldState(), and ObjectGridUnloader::Visit().
Member Data Documentation
iFirst
LinkedListElement LinkedListHead::iFirst private
Referenced by getFirst(), insertFirst(), IsEmpty(), and LinkedListHead().
iLast
LinkedListElement LinkedListHead::iLast private
Referenced by getLast(), insertLast(), and LinkedListHead().
iSize
uint32 LinkedListHead::iSize {0} private
Referenced by decSize(), getSize(), and incSize().