AzerothCore: Acore::Impl::GenericHash< HashCreator, DigestLength > Class Template Reference
Acore::Impl::GenericHash< HashCreator, DigestLength > Class Template Reference
#include "CryptoHash.h"
Public Types
using Digest = std::array< uint8, DIGEST_LENGTH >
Public Member Functions
GenericHash ()
GenericHash (GenericHash const &right)
GenericHash (GenericHash &&right) noexcept
~GenericHash ()
GenericHash & operator= (GenericHash const &right)
GenericHash & operator= (GenericHash &&right) noexcept
void UpdateData (uint8 const *data, std::size_t len)
void UpdateData (std::string_view str)
void UpdateData (std::string const &str)
void UpdateData (char const *str)
template<typename Container >
void UpdateData (Container const &c)
void Finalize ()
Digest const & GetDigest () const
Static Public Member Functions
static Digest GetDigestOf (uint8 const *data, std::size_t len)
template<typename... Ts>
static auto GetDigestOf (Ts &&... pack) -> std::enable_if_t<!(std::is_integral_v< std::decay_t< Ts > >||...), Digest >
Static Public Attributes
static constexpr std::size_t DIGEST_LENGTH = DigestLength
Private Attributes
EVP_MD_CTX * _ctx {}
Digest _digest {}
Detailed Description
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength>
class Acore::Impl::GenericHash< HashCreator, DigestLength >
Member Typedef Documentation
Digest
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> using Acore::Impl::GenericHash< HashCreator, DigestLength >::Digest = std::array<uint8, DIGEST_LENGTH>
Constructor & Destructor Documentation
GenericHash() [1/3]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Acore::Impl::GenericHash< HashCreator, DigestLength >::GenericHash () inline
                          : _ctx(GenericHashImpl::MakeCTX())
            {
                int result = EVP_DigestInit_ex(_ctx, HashCreator(), nullptr);
                ASSERT(result == 1);
            }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx, and ASSERT.
GenericHash() [2/3]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Acore::Impl::GenericHash< HashCreator, DigestLength >::GenericHash (GenericHash< HashCreator, DigestLength > const & right) inline
                                                  : _ctx(GenericHashImpl::MakeCTX())
            {
                *this = right;
            }
GenericHash() [3/3]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Acore::Impl::GenericHash< HashCreator, DigestLength >::GenericHash (GenericHash< HashCreator, DigestLength > && right) inline noexcept
            {
                *this = std::move(right);
            }
~GenericHash()
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Acore::Impl::GenericHash< HashCreator, DigestLength >::~GenericHash () inline
            {
                if (!_ctx)
                    return;
                GenericHashImpl::DestroyCTX(_ctx);
                _ctx = nullptr;
            }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx, and Acore::Impl::GenericHashImpl::DestroyCTX().
Member Function Documentation
Finalize()
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> void Acore::Impl::GenericHash< HashCreator, DigestLength >::Finalize () inline
            {
                uint32 length;
                int result = EVP_DigestFinal_ex(_ctx, _digest.data(), &length);
                ASSERT(result == 1);
                ASSERT(length == DIGEST_LENGTH);
            }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHash< HashCreator, DigestLength >::_digest, ASSERT, and Acore::Impl::GenericHash< HashCreator, DigestLength >::DIGEST_LENGTH.
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigestOf(), WorldSocket::HandleAuthSessionCallback(), WardenMac::HandleData(), WardenMac::HandleHashResult(), AuthSession::HandleReconnectProof(), and AuthSession::VerifyVersion().
GetDigest()
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Digest const & Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigest () const inline
{ return _digest; }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_digest.
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigestOf(), WorldSocket::HandleAuthSessionCallback(), WardenMac::HandleData(), WardenMac::HandleHashResult(), AuthSession::HandleReconnectProof(), and AuthSession::VerifyVersion().
GetDigestOf() [1/2]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> template<typename... Ts> static auto Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigestOf (Ts &&... pack) -> std::enable_if_t<!(std::is_integral_v<std::decay_t<Ts>> || ...), Digest> inline static
            {
                GenericHash hash;
                (hash.UpdateData(std::forward<Ts>(pack)), ...);
                hash.Finalize();
                return hash.GetDigest();
            }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigest(), and Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
GetDigestOf() [2/2]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> static Digest Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigestOf (uint8 const * data, std::size_t len) inline static
            {
                GenericHash hash;
                hash.UpdateData(data, len);
                hash.Finalize();
                return hash.GetDigest();
            }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigest(), and Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
Referenced by Warden::BuildChecksum(), Acore::Crypto::SRP6::CalculateVerifier(), WardenMac::GetModuleForClient(), WardenWin::GetModuleForClient(), Acore::Crypto::SRP6::GetSessionVerifier(), WardenMac::HandleData(), AddonMgr::LoadFromDB(), Acore::Crypto::SRP6::SHA1Interleave(), UpdateFetcher::Update(), and Acore::Crypto::SRP6::VerifyChallengeResponse().
operator=() [1/2]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> GenericHash & Acore::Impl::GenericHash< HashCreator, DigestLength >::operator= (GenericHash< HashCreator, DigestLength > && right) inline noexcept
            {
                if (this == &right)
                    return *this;
                _ctx = std::exchange(right._ctx, GenericHashImpl::MakeCTX());
                _digest = std::exchange(right._digest, Digest{});
                return *this;
            }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHash< HashCreator, DigestLength >::_digest, and Acore::Impl::GenericHashImpl::MakeCTX().
operator=() [2/2]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> GenericHash & Acore::Impl::GenericHash< HashCreator, DigestLength >::operator= (GenericHash< HashCreator, DigestLength > const & right) inline
            {
                if (this == &right)
                    return *this;
                int result = EVP_MD_CTX_copy_ex(_ctx, right._ctx);
                ASSERT(result == 1);
                _digest = right._digest;
                return *this;
            }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHash< HashCreator, DigestLength >::_digest, and ASSERT.
UpdateData() [1/5]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> void Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData (char const * str) inline
{ UpdateData(std::string_view(str)); } /* explicit overload to avoid using the container template */
References Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
UpdateData() [2/5]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> template<typename Container > void Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData (Container const & c) inline
{ UpdateData(std::data(c), std::size(c)); }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
UpdateData() [3/5]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> void Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData (std::string const & str) inline
{ UpdateData(std::string_view(str)); } /* explicit overload to avoid using the container template */
References Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
UpdateData() [4/5]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> void Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData (std::string_view str) inline
{ UpdateData(reinterpret_cast<uint8 const*>(str.data()), str.size()); }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
UpdateData() [5/5]
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> void Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData (uint8 const * data, std::size_t len) inline
            {
                int result = EVP_DigestUpdate(_ctx, data, len);
                ASSERT(result == 1);
            }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx, and ASSERT.
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigestOf(), WorldSocket::HandleAuthSessionCallback(), WardenMac::HandleData(), WardenMac::HandleHashResult(), AuthSession::HandleReconnectProof(), and AuthSession::VerifyVersion().
Member Data Documentation
_ctx
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> EVP_MD_CTX* Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx {} private
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHash< HashCreator, DigestLength >::GenericHash(), Acore::Impl::GenericHash< HashCreator, DigestLength >::operator=(), Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData(), and Acore::Impl::GenericHash< HashCreator, DigestLength >::~GenericHash().
_digest
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> Digest Acore::Impl::GenericHash< HashCreator, DigestLength >::_digest {} private
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigest(), and Acore::Impl::GenericHash< HashCreator, DigestLength >::operator=().
DIGEST_LENGTH
template<GenericHashImpl::HashCreator HashCreator, std::size_t DigestLength> constexpr std::size_t Acore::Impl::GenericHash< HashCreator, DigestLength >::DIGEST_LENGTH = DigestLength static constexpr
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::Finalize(), and Acore::Crypto::SRP6::SHA1Interleave().