AzerothCore: spell_hun_pet_heart_of_the_phoenix Class Reference
spell_hun_pet_heart_of_the_phoenix Class Reference
Private Member Functions
PrepareSpellScript (spell_hun_pet_heart_of_the_phoenix)
bool Load () override
bool Validate (SpellInfo const *) override
SpellCastResult CheckCast ()
void HandleScript (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
CheckCast()
SpellCastResult spell_hun_pet_heart_of_the_phoenix::CheckCast () inline private
    {
        Unit* caster = GetCaster();
        if (caster->IsAlive())
            return SPELL_FAILED_TARGET_NOT_DEAD;
        if (caster->HasAura(SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_DEBUFF))
            return SPELL_FAILED_CASTER_AURASTATE;
        return SPELL_CAST_OK;
    }
References SpellScript::GetCaster(), Unit::HasAura(), Unit::IsAlive(), SPELL_CAST_OK, SPELL_FAILED_CASTER_AURASTATE, SPELL_FAILED_TARGET_NOT_DEAD, and SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_DEBUFF.
Referenced by Register().
HandleScript()
void spell_hun_pet_heart_of_the_phoenix::HandleScript (SpellEffIndex) inline private
    {
        Unit* caster = GetCaster();
        if (Unit* owner = caster->GetOwner())
            if (!caster->HasAura(SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_DEBUFF))
            {
                owner->CastCustomSpell(SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_TRIGGERED, SPELLVALUE_BASE_POINT0, 100, caster, true);
                caster->CastSpell(caster, SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_DEBUFF, true);
            }
    }
References Unit::CastSpell(), SpellScript::GetCaster(), Unit::GetOwner(), Unit::HasAura(), SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_DEBUFF, SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_TRIGGERED, and SPELLVALUE_BASE_POINT0.
Referenced by Register().
Load()
bool spell_hun_pet_heart_of_the_phoenix::Load () inline override private virtual
Reimplemented from _SpellScript.
    {
        if (!GetCaster()->IsPet())
            return false;
        return true;
    }
References SpellScript::GetCaster().
PrepareSpellScript()
spell_hun_pet_heart_of_the_phoenix::PrepareSpellScript (spell_hun_pet_heart_of_the_phoenix) private
Register()
void spell_hun_pet_heart_of_the_phoenix::Register () inline override private virtual
Implements _SpellScript.
    {
        OnCheckCast += SpellCheckCastFn(spell_hun_pet_heart_of_the_phoenix::CheckCast);
        OnEffectHitTarget += SpellEffectFn(spell_hun_pet_heart_of_the_phoenix::HandleScript, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
    }
References CheckCast(), EFFECT_0, HandleScript(), SpellScript::OnCheckCast, SpellScript::OnEffectHitTarget, SPELL_EFFECT_SCRIPT_EFFECT, SpellCheckCastFn, and SpellEffectFn.
Validate()
bool spell_hun_pet_heart_of_the_phoenix::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo({ SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_TRIGGERED, SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_DEBUFF });
    }
References SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_DEBUFF, SPELL_HUNTER_PET_HEART_OF_THE_PHOENIX_TRIGGERED, and _SpellScript::ValidateSpellInfo().