AzerothCore: azerothcore-wotlk/src/server/game/Grids/ObjectGridLoader.cpp File Reference
ObjectGridLoader.cpp File Reference
#include "ObjectGridLoader.h"
#include "CellImpl.h"
#include "Corpse.h"
#include "Creature.h"
#include "DynamicObject.h"
#include "GameObject.h"
#include "GridNotifiers.h"
#include "ObjectMgr.h"
#include "Transport.h"
Classes
class ObjectWorldLoader
Functions
template<class T >
void AddObjectHelper (CellCoord &cell, GridRefMgr< T > &m, uint32 &count, Map *, T *obj)
template<>
void AddObjectHelper (CellCoord &cell, CreatureMapType &m, uint32 &count, Map *map, Creature *obj)
template<>
void AddObjectHelper (CellCoord &cell, GameObjectMapType &m, uint32 &count, Map *map, GameObject *obj)
template<class T >
void LoadHelper (CellGuidSet const &, CellCoord &, GridRefMgr< T > &, uint32 &, Map *)
template<>
void LoadHelper (CellGuidSet const &guid_set, CellCoord &cell, GridRefMgr< Creature > &m, uint32 &count, Map *map)
template<>
void LoadHelper (CellGuidSet const &guid_set, CellCoord &cell, GridRefMgr< GameObject > &m, uint32 &count, Map *map)
Function Documentation
AddObjectHelper() [1/3]
template<> void AddObjectHelper (CellCoord & cell, CreatureMapType & m, uint32 & count, Map * map, Creature * obj)
{
    obj->AddToGrid(m);
    ObjectGridLoader::SetObjectCell(obj, cell);
    obj->AddToWorld();
    if (obj->isActiveObject())
        map->AddToActive(obj);
    ++count;
}
References Map::AddToActive(), GridObject< T >::AddToGrid(), Creature::AddToWorld(), WorldObject::isActiveObject(), and ObjectGridLoader::SetObjectCell().
AddObjectHelper() [2/3]
template<> void AddObjectHelper (CellCoord & cell, GameObjectMapType & m, uint32 & count, Map * map, GameObject * obj)
{
    obj->AddToGrid(m);
    ObjectGridLoader::SetObjectCell(obj, cell);
    obj->AddToWorld();
    if (obj->isActiveObject())
        map->AddToActive(obj);
    ++count;
}
References Map::AddToActive(), GridObject< T >::AddToGrid(), GameObject::AddToWorld(), WorldObject::isActiveObject(), and ObjectGridLoader::SetObjectCell().
AddObjectHelper() [3/3]
template<class T > void AddObjectHelper (CellCoord & cell, GridRefMgr< T > & m, uint32 & count, Map * , T * obj)
{
    obj->AddToGrid(m);
    ObjectGridLoader::SetObjectCell(obj, cell);
    obj->AddToWorld();
    ++count;
}
References ObjectGridLoader::SetObjectCell().
Referenced by LoadHelper().
LoadHelper() [1/3]
template<class T > void LoadHelper (CellGuidSet const & , CellCoord & , GridRefMgr< T > & , uint32 & , Map *)
{
}
Referenced by ObjectGridLoader::Visit().
LoadHelper() [2/3]
template<> void LoadHelper (CellGuidSet const & guid_set, CellCoord & cell, GridRefMgr< Creature > & m, uint32 & count, Map * map)
{
    for (CellGuidSet::const_iterator i_guid = guid_set.begin(); i_guid != guid_set.end(); ++i_guid)
    {
        Creature* obj = new Creature();
        ObjectGuid::LowType guid = *i_guid;
        if (!obj->LoadFromDB(guid, map))
        {
            delete obj;
            continue;
        }
        AddObjectHelper(cell, m, count, map, obj);
        if (!obj->IsMoveInLineOfSightDisabled() && obj->GetDefaultMovementType() == IDLE_MOTION_TYPE && !obj->isNeedNotify(NOTIFY_VISIBILITY_CHANGED | NOTIFY_AI_RELOCATION))
        {
            if (obj->IsAlive() && !obj->HasUnitState(UNIT_STATE_SIGHTLESS) && obj->HasReactState(REACT_AGGRESSIVE) && !obj->IsImmuneToNPC())
            {
                // call MoveInLineOfSight for nearby grid creatures
                Acore::AIRelocationNotifier notifier(*obj);
                Cell::VisitGridObjects(obj, notifier, 60.f);
            }
        }
    }
}
References AddObjectHelper(), Creature::GetDefaultMovementType(), Creature::HasReactState(), Unit::HasUnitState(), IDLE_MOTION_TYPE, Unit::IsAlive(), Unit::IsImmuneToNPC(), Creature::IsMoveInLineOfSightDisabled(), WorldObject::isNeedNotify(), Creature::LoadFromDB(), NOTIFY_AI_RELOCATION, NOTIFY_VISIBILITY_CHANGED, REACT_AGGRESSIVE, UNIT_STATE_SIGHTLESS, and Cell::VisitGridObjects().
LoadHelper() [3/3]
template<> void LoadHelper (CellGuidSet const & guid_set, CellCoord & cell, GridRefMgr< GameObject > & m, uint32 & count, Map * map)
{
    for (CellGuidSet::const_iterator i_guid = guid_set.begin(); i_guid != guid_set.end(); ++i_guid)
    {
        ObjectGuid::LowType guid = *i_guid;
        GameObjectData const* data = sObjectMgr->GetGameObjectData(guid);
        GameObject* obj = data && sObjectMgr->IsGameObjectStaticTransport(data->id) ? new StaticTransport() : new GameObject();
        if (!obj->LoadFromDB(guid, map))
        {
            delete obj;
            continue;
        }
        AddObjectHelper(cell, m, count, map, obj);
    }
}
References AddObjectHelper(), GameObjectData::id, GameObject::LoadFromDB(), and sObjectMgr.