AzerothCore: npc_captain_saeed::npc_captain_saeedAI Struct Reference
npc_captain_saeed::npc_captain_saeedAI Struct Reference
Public Member Functions
npc_captain_saeedAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *who) override
void SetGUID (ObjectGuid playerGUID, int32 type) override
void EnterEvadeMode (EvadeReason why) override
void SummonsAction (Unit *who)
void WaypointReached (uint32 i) override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void CorpseRemoved (uint32 &) override
== Triggered Actions Requested ==================
uint32 GetData (uint32 data) const override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
SummonList summons
EventMap events
bool started
bool fight
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_captain_saeedAI()
npc_captain_saeed::npc_captain_saeedAI::npc_captain_saeedAI (Creature * creature) inline
: npc_escortAI(creature), summons(me) {}
Member Function Documentation
CorpseRemoved()
void npc_captain_saeed::npc_captain_saeedAI::CorpseRemoved (uint32 &) inline override virtual
== Triggered Actions Requested ==================
== State checks =================================
Reimplemented from CreatureAI.
        {
            summons.DespawnAll();
        }
References SummonList::DespawnAll(), and summons.
EnterEvadeMode()
void npc_captain_saeed::npc_captain_saeedAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from npc_escortAI.
        {
            if (fight)
                SetEscortPaused(false);
            SummonsAction(nullptr);
            npc_escortAI::EnterEvadeMode(why);
        }
References npc_escortAI::EnterEvadeMode(), fight, npc_escortAI::SetEscortPaused(), and SummonsAction().
GetData()
uint32 npc_captain_saeed::npc_captain_saeedAI::GetData (uint32 data) const inline override virtual
Reimplemented from UnitAI.
        {
            if (data == 1)
                return (uint32)started;
            return 0;
        }
References started.
JustDied()
void npc_captain_saeed::npc_captain_saeedAI::JustDied (Unit *) inline override virtual
Reimplemented from npc_escortAI.
        {
            Player* player = GetPlayerForEscort();
            if (player)
                player->FailQuest(QUEST_DIMENSIUS_DEVOURING);
            summons.DespawnAll();
        }
References SummonList::DespawnAll(), Player::FailQuest(), npc_escortAI::GetPlayerForEscort(), QUEST_DIMENSIUS_DEVOURING, and summons.
JustEngagedWith()
void npc_captain_saeed::npc_captain_saeedAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            SummonsAction(who);
        }
References SummonsAction().
MoveInLineOfSight()
void npc_captain_saeed::npc_captain_saeedAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from npc_escortAI.
        {
            if (Player* player = GetPlayerForEscort())
                if (me->GetDistance(who) < 10.0f && !me->GetVictim())
                    if (player->IsValidAttackTarget(who))
                    {
                        AttackStart(who);
                        return;
                    }
            npc_escortAI::MoveInLineOfSight(who);
        }
References npc_escortAI::AttackStart(), WorldObject::GetDistance(), npc_escortAI::GetPlayerForEscort(), Unit::GetVictim(), ScriptedAI::me, and npc_escortAI::MoveInLineOfSight().
Reset()
void npc_captain_saeed::npc_captain_saeedAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!summons.empty())
            {
                for (ObjectGuid const& guid : summons)
                    if (Creature* cr = ObjectAccessor::GetCreature(*me, guid))
                    {
                        float x, y, z, o;
                        cr->GetRespawnPosition(x, y, z, &o);
                        cr->SetHomePosition(x, y, z, o);
                    }
            }
            events.Reset();
            summons.clear();
            started = false;
            fight = false;
            me->RestoreFaction();
        }
References SummonList::clear(), SummonList::empty(), fight, ObjectAccessor::GetCreature(), ScriptedAI::me, Unit::RestoreFaction(), started, and summons.
SetGUID()
void npc_captain_saeed::npc_captain_saeedAI::SetGUID (ObjectGuid playerGUID, int32 type) inline override virtual
Reimplemented from UnitAI.
        {
            if (type == DATA_START_ENCOUNTER)
            {
                Start(true, true, playerGUID);
                SetEscortPaused(true);
                started = true;
                std::list<Creature*> cl;
                me->GetCreaturesWithEntryInRange(cl, 20.0f, NPC_PROTECTORATE_AVENGER);
                for (std::list<Creature*>::iterator itr = cl.begin(); itr != cl.end(); ++itr)
                {
                    summons.Summon(*itr);
                    (*itr)->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                    (*itr)->SetFaction(FACTION_ESCORTEE_N_NEUTRAL_ACTIVE);
                }
                cl.clear();
                me->GetCreaturesWithEntryInRange(cl, 20.0f, NPC_PROTECTORATE_DEFENDER);
                for (std::list<Creature*>::iterator itr = cl.begin(); itr != cl.end(); ++itr)
                {
                    summons.Summon(*itr);
                    (*itr)->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                    (*itr)->SetFaction(FACTION_ESCORTEE_N_NEUTRAL_ACTIVE);
                }
                me->SetFaction(FACTION_ESCORTEE_N_NEUTRAL_ACTIVE);
                Talk(SAY_SAEED_0);
                events.ScheduleEvent(EVENT_START_WALK, 3000);
            }
            else if (type == DATA_START_FIGHT)
            {
                Talk(SAY_SAEED_2);
                SetEscortPaused(false);
                me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
            }
        }
References DATA_START_ENCOUNTER, DATA_START_FIGHT, EMOTE_ONESHOT_ROAR, EVENT_START_WALK, FACTION_ESCORTEE_N_NEUTRAL_ACTIVE, WorldObject::GetCreaturesWithEntryInRange(), ScriptedAI::me, NPC_PROTECTORATE_AVENGER, NPC_PROTECTORATE_DEFENDER, Unit::ReplaceAllNpcFlags(), SAY_SAEED_0, SAY_SAEED_2, npc_escortAI::SetEscortPaused(), Unit::SetFaction(), npc_escortAI::Start(), started, SummonList::Summon(), summons, and UNIT_NPC_FLAG_NONE.
SummonsAction()
void npc_captain_saeed::npc_captain_saeedAI::SummonsAction (Unit * who) inline
        {
            float i = 0;
            for (GuidList::iterator itr = summons.begin(); itr != summons.end(); ++itr, i += 1.0f)
                if (Creature* cr = ObjectAccessor::GetCreature(*me, *itr))
                {
                    if (!who)
                    {
                        cr->GetMotionMaster()->Clear(false);
                        cr->GetMotionMaster()->MoveFollow(me, 2.0f, M_PI / 2.0f + (i / summons.size() * M_PI));
                    }
                    else
                    {
                        cr->SetHomePosition(cr->GetPositionX(), cr->GetPositionY(), cr->GetPositionZ(), cr->GetOrientation());
                        cr->AI()->AttackStart(who);
                    }
                }
        }
References SummonList::begin(), SummonList::end(), ObjectAccessor::GetCreature(), ScriptedAI::me, SummonList::size(), and summons.
Referenced by EnterEvadeMode(), JustEngagedWith(), and UpdateAI().
UpdateAI()
void npc_captain_saeed::npc_captain_saeedAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from npc_escortAI.
        {
            npc_escortAI::UpdateAI(diff);
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_START_WALK:
                    SummonsAction(nullptr);
                    SetEscortPaused(false);
                    break;
                case EVENT_START_FIGHT1:
                    Talk(SAY_SAEED_3);
                    events.ScheduleEvent(EVENT_START_FIGHT2, 3000);
                    break;
                case EVENT_START_FIGHT2:
                    if (Creature* dimensius = me->FindNearestCreature(NPC_DIMENSIUS, 50.0f))
                    {
                        dimensius->RemoveAurasDueToSpell(SPELL_DIMENSIUS_TRANSFORM);
                        dimensius->ReplaceAllUnitFlags(UNIT_FLAG_DISABLE_MOVE);
                        AttackStart(dimensius);
                        fight = true;
                    }
                    break;
            }
            if (!UpdateVictim())
                return;
            DoMeleeAttackIfReady();
        }
References npc_escortAI::AttackStart(), UnitAI::DoMeleeAttackIfReady(), EVENT_START_FIGHT1, EVENT_START_FIGHT2, EVENT_START_WALK, fight, WorldObject::FindNearestCreature(), ScriptedAI::me, NPC_DIMENSIUS, SAY_SAEED_3, npc_escortAI::SetEscortPaused(), SPELL_DIMENSIUS_TRANSFORM, SummonsAction(), UNIT_FLAG_DISABLE_MOVE, npc_escortAI::UpdateAI(), and CreatureAI::UpdateVictim().
WaypointReached()
void npc_captain_saeed::npc_captain_saeedAI::WaypointReached (uint32 i) inline override virtual
Implements npc_escortAI.
        {
            Player* player = GetPlayerForEscort();
            if (!player)
                return;
            switch (i)
            {
                case 16:
                    Talk(SAY_SAEED_1);
                    me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_GOSSIP);
                    SetEscortPaused(true);
                    break;
                case 18:
                    events.ScheduleEvent(EVENT_START_FIGHT1, 0);
                    SetEscortPaused(true);
                    break;
                case 19:
                    summons.DespawnAll();
                    break;
            }
        }
References SummonList::DespawnAll(), EVENT_START_FIGHT1, npc_escortAI::GetPlayerForEscort(), ScriptedAI::me, Unit::ReplaceAllNpcFlags(), SAY_SAEED_1, npc_escortAI::SetEscortPaused(), summons, and UNIT_NPC_FLAG_GOSSIP.
Member Data Documentation
events
EventMap npc_captain_saeed::npc_captain_saeedAI::events
fight
bool npc_captain_saeed::npc_captain_saeedAI::fight
Referenced by EnterEvadeMode(), Reset(), and UpdateAI().
started
bool npc_captain_saeed::npc_captain_saeedAI::started
Referenced by GetData(), Reset(), and SetGUID().
summons
SummonList npc_captain_saeed::npc_captain_saeedAI::summons
Referenced by CorpseRemoved(), JustDied(), Reset(), SetGUID(), SummonsAction(), and WaypointReached().