AzerothCore: TotemAI Class Reference
TotemAI Class Reference
#include "TotemAI.h"
Public Member Functions
TotemAI (Creature *c)
void MoveInLineOfSight (Unit *who) override
void AttackStart (Unit *victim) override
void EnterEvadeMode (EvadeReason) override
void SpellHit (Unit *, SpellInfo const *) override
void DoAction (int32 param) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Static Public Member Functions
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Private Attributes
ObjectGuid i_victimGuid
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
TotemAI()
TotemAI::TotemAI (Creature * c) explicit
                            : CreatureAI(c)
{
    ASSERT(c->IsTotem());
}
References ASSERT, and Unit::IsTotem().
Member Function Documentation
AttackStart()
void TotemAI::AttackStart (Unit * victim) override virtual
Reimplemented from UnitAI.
{
    // Sentry totem sends ping on attack
    if (me->GetEntry() == SENTRY_TOTEM_ENTRY && me->GetOwner()->IsPlayer())
    {
        WorldPacket data(MSG_MINIMAP_PING, (8 + 4 + 4));
        data << me->GetGUID();
        data << me->GetPositionX();
        data << me->GetPositionY();
        me->GetOwner()->ToPlayer()->GetSession()->SendPacket(&data);
    }
}
References Object::GetEntry(), Object::GetGUID(), Unit::GetOwner(), Position::GetPositionX(), Position::GetPositionY(), Player::GetSession(), Object::IsPlayer(), CreatureAI::me, MSG_MINIMAP_PING, WorldSession::SendPacket(), SENTRY_TOTEM_ENTRY, and Object::ToPlayer().
DoAction()
void TotemAI::DoAction (int32 param) override virtual
Reimplemented from UnitAI.
{
}
EnterEvadeMode()
void TotemAI::EnterEvadeMode (EvadeReason) override virtual
Reimplemented from CreatureAI.
{
    me->CombatStop(true);
}
References Unit::CombatStop(), and CreatureAI::me.
MoveInLineOfSight()
void TotemAI::MoveInLineOfSight (Unit * who) override virtual
Reimplemented from CreatureAI.
{
}
Permissible()
int32 TotemAI::Permissible (Creature const * creature) static
Todo:
: this import is not necessary for compilation and marked as unused by the IDE
{
    if (creature->IsTotem())
        return PERMIT_BASE_PROACTIVE;
    return PERMIT_BASE_NO;
}
References Unit::IsTotem(), PERMIT_BASE_NO, and PERMIT_BASE_PROACTIVE.
SpellHit()
void TotemAI::SpellHit (Unit * , SpellInfo const *) override virtual
Reimplemented from CreatureAI.
{
}
UpdateAI()
void TotemAI::UpdateAI (uint32) override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
{
    if (me->ToTotem()->GetTotemType() != TOTEM_ACTIVE)
        return;
    if (!me->IsAlive())
    {
        return;
    }
    if (me->IsNonMeleeSpellCast(false))
    {
        if (Unit* victim = ObjectAccessor::GetUnit(*me, i_victimGuid))
        {
            if (!victim || !victim->IsAlive())
            {
                me->InterruptNonMeleeSpells(false);
            }
        }
        return;
    }
    // Search spell
    SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(me->ToTotem()->GetSpell());
    if (!spellInfo)
        return;
    // Get spell range
    float max_range = spellInfo->GetMaxRange(false);
    // SPELLMOD_RANGE not applied in this place just because not existence range mods for attacking totems
    // pointer to appropriate target if found any
    Unit* victim = i_victimGuid ? ObjectAccessor::GetUnit(*me, i_victimGuid) : nullptr;
    // Search victim if no, not attackable, or out of range, or friendly (possible in case duel end)
    if (!victim ||
            !victim->isTargetableForAttack(true, me) || !me->IsWithinDistInMap(victim, max_range) ||
            me->IsFriendlyTo(victim) || !me->CanSeeOrDetect(victim))
    {
        victim = nullptr;
        Acore::NearestAttackableUnitInObjectRangeCheck u_check(me, me, max_range);
        Acore::UnitLastSearcher<Acore::NearestAttackableUnitInObjectRangeCheck> checker(me, victim, u_check);
        Cell::VisitAllObjects(me, checker, max_range);
    }
    if (!victim && me->GetCharmerOrOwnerOrSelf()->IsInCombat())
    {
        victim = me->GetCharmerOrOwnerOrSelf()->getAttackerForHelper();
    }
    // If have target
    if (victim)
    {
        // remember
        i_victimGuid = victim->GetGUID();
        // attack
        me->SetInFront(victim);                         // client change orientation by self
        me->CastSpell(victim, me->ToTotem()->GetSpell(), false);
    }
    else
        i_victimGuid.Clear();
}
References WorldObject::CanSeeOrDetect(), Unit::CastSpell(), ObjectGuid::Clear(), Unit::getAttackerForHelper(), Unit::GetCharmerOrOwnerOrSelf(), Object::GetGUID(), SpellInfo::GetMaxRange(), Totem::GetSpell(), Totem::GetTotemType(), ObjectAccessor::GetUnit(), i_victimGuid, Unit::InterruptNonMeleeSpells(), Unit::IsAlive(), Unit::IsFriendlyTo(), Unit::IsInCombat(), Unit::IsNonMeleeSpellCast(), Unit::isTargetableForAttack(), WorldObject::IsWithinDistInMap(), CreatureAI::me, Unit::SetInFront(), sSpellMgr, TOTEM_ACTIVE, Unit::ToTotem(), and Cell::VisitAllObjects().
Member Data Documentation
i_victimGuid
ObjectGuid TotemAI::i_victimGuid private
Referenced by UpdateAI().