AzerothCore: Acore::WorldWorldTextBuilder Class Reference
Acore::WorldWorldTextBuilder Class Reference
Public Types
typedef std::vector< WorldPacket * > WorldPacketList
Public Member Functions
WorldWorldTextBuilder (uint32 textId, va_list *args=nullptr)
void operator() (WorldPacketList &data_list, LocaleConstant loc_idx)
Private Member Functions
char * lineFromMessage (char *&pos)
void do_helper (WorldPacketList &data_list, char *text)
Private Attributes
uint32 i_textId
va_list * i_args
Detailed Description
Member Typedef Documentation
WorldPacketList
typedef std::vector<WorldPacket*> Acore::WorldWorldTextBuilder::WorldPacketList
Constructor & Destructor Documentation
WorldWorldTextBuilder()
Acore::WorldWorldTextBuilder::WorldWorldTextBuilder (uint32 textId, va_list * args = nullptr) inline explicit
: i_textId(textId), i_args(args) {}
Member Function Documentation
do_helper()
void Acore::WorldWorldTextBuilder::do_helper (WorldPacketList & data_list, char * text) inline private
        {
            char* pos = text;
            while (char* line = lineFromMessage(pos))
            {
                WorldPacket* data = new WorldPacket();
                ChatHandler::BuildChatPacket(*data, CHAT_MSG_SYSTEM, LANG_UNIVERSAL, nullptr, nullptr, line);
                data_list.push_back(data);
            }
        }
References ChatHandler::BuildChatPacket(), CHAT_MSG_SYSTEM, LANG_UNIVERSAL, and lineFromMessage().
Referenced by operator()().
lineFromMessage()
char * Acore::WorldWorldTextBuilder::lineFromMessage (char *& pos) inline private
{ char* start = strtok(pos, "\n"); pos = nullptr; return start; }
Referenced by do_helper().
operator()()
void Acore::WorldWorldTextBuilder::operator() (WorldPacketList & data_list, LocaleConstant loc_idx) inline
        {
            char const* text = sObjectMgr->GetAcoreString(i_textId, loc_idx);
            if (i_args)
            {
                // we need copy va_list before use or original va_list will corrupted
                va_list ap;
                va_copy(ap, *i_args);
                char str[2048];
                vsnprintf(str, 2048, text, ap);
                va_end(ap);
                do_helper(data_list, &str[0]);
            }
            else
                do_helper(data_list, (char*)text);
        }
References do_helper(), i_args, i_textId, and sObjectMgr.
Member Data Documentation
i_args
va_list* Acore::WorldWorldTextBuilder::i_args private
Referenced by operator()().
i_textId
uint32 Acore::WorldWorldTextBuilder::i_textId private
Referenced by operator()().