AzeorthCore: boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI Struct Reference
boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI Struct Reference
Public Member Functions
boss_yoggsaron_lich_kingAI (Creature *c)
void Reset () override
void NextStep (const uint32 time)
void Say (std::string text, ObjectGuid guid, bool yell, uint32 soundId)
void Playsound (uint32 soundId)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
bool _running
int32 _checkTimer
uint8 _step
ObjectGuid _championGUID
ObjectGuid _yoggGUID
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_yoggsaron_lich_kingAI()
boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::boss_yoggsaron_lich_kingAI (Creature * c) inline
: NullCreatureAI(c) { }
Member Function Documentation
NextStep()
void boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::NextStep (const uint32 time) inline
        {
            _step++;
            _checkTimer = time;
        }
References _checkTimer, and _step.
Referenced by UpdateAI().
Playsound()
void boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Playsound (uint32 soundId) inline
        {
            WorldPacket data(SMSG_PLAY_SOUND, 4);
            data << uint32(soundId);
            me->SendMessageToSetInRange(&data, 90, false);
        }
References CreatureAI::me, WorldObject::SendMessageToSetInRange(), and SMSG_PLAY_SOUND.
Referenced by Say().
Reset()
void boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            _running = true;
            _checkTimer = 0;
            _step = 0;
            _championGUID.Clear();
            if (me->GetInstanceScript())
                _yoggGUID = me->GetInstanceScript()->GetGuidData(TYPE_YOGGSARON);
        }
References _championGUID, _checkTimer, _running, _step, _yoggGUID, ObjectGuid::Clear(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), CreatureAI::me, and TYPE_YOGGSARON.
Say()
void boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say (std::string text, ObjectGuid guid, bool yell, uint32 soundId) inline
        {
            Creature* creature = guid ? ObjectAccessor::GetCreature(*me, guid) : me;
            if (!creature)
                return;
            WorldPacket data;
            if (creature->GetGUID() != _yoggGUID)
            {
                ChatHandler::BuildChatPacket(data, yell ? CHAT_MSG_MONSTER_YELL : CHAT_MSG_MONSTER_SAY, LANG_UNIVERSAL, creature, nullptr, text);
                creature->SendMessageToSetInRange(&data, 90, true);
            }
            else if (Creature* cr = me->SummonTrigger(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() - 5, 0, 5000))
            {
                ChatHandler::BuildChatPacket(data, yell ? CHAT_MSG_MONSTER_YELL : CHAT_MSG_MONSTER_SAY, LANG_UNIVERSAL, creature, nullptr, text);
                cr->SendMessageToSetInRange(&data, 90, true);
            }
            else
                return;
            Playsound(soundId);
        }
References _yoggGUID, ChatHandler::BuildChatPacket(), CHAT_MSG_MONSTER_SAY, CHAT_MSG_MONSTER_YELL, ObjectAccessor::GetCreature(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), LANG_UNIVERSAL, CreatureAI::me, Playsound(), WorldObject::SendMessageToSetInRange(), and WorldObject::SummonTrigger().
UpdateAI()
void boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
        {
            if (!_running)
                return;
            if (_checkTimer != 0)
            {
                _checkTimer -= diff;
                if (_checkTimer < 0 )
                    _checkTimer = 0;
            }
            else
                switch (_step)
                {
                    case 0:
                        NextStep(5000);
                        break;
                    case 1:
                        if (Creature* cr = me->FindNearestCreature(NPC_IMMOLATED_CHAMPION, 50))
                            _championGUID = cr->GetGUID();
                        Say("Your resilience is admirable.", ObjectGuid::Empty, false, LK_1);
                        NextStep(7000);
                        break;
                    case 2:
                        Say("Arrrrrrgh!", _championGUID, true, IC_1);
                        NextStep(6000);
                        break;
                    case 3:
                        Say("I'm not afraid of you!", _championGUID, false, IC_2);
                        NextStep(6500);
                        break;
                    case 4:
                        Say("I will break you as I broke him.", ObjectGuid::Empty, false, LK_2);
                        NextStep(7500);
                        break;
                    case 5:
                        Say("Yrr n'lyeth... shuul anagg!", _yoggGUID, false, YS_V3_1);
                        NextStep(5000);
                        break;
                    case 6:
                        Say("He will learn... no king rules forever; only death is eternal!", _yoggGUID, false, YS_V3_2);
                        _running = false;
                        break;
                }
        }
References _championGUID, _checkTimer, _running, _step, _yoggGUID, ObjectGuid::Empty, WorldObject::FindNearestCreature(), IC_1, IC_2, LK_1, LK_2, CreatureAI::me, NextStep(), NPC_IMMOLATED_CHAMPION, YS_V3_1, and YS_V3_2.
Member Data Documentation
_championGUID
ObjectGuid boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::_championGUID
Referenced by Reset(), and UpdateAI().
_checkTimer
int32 boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::_checkTimer
Referenced by NextStep(), Reset(), and UpdateAI().
_running
bool boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::_running
Referenced by Reset(), and UpdateAI().
_step
uint8 boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::_step
Referenced by NextStep(), Reset(), and UpdateAI().
_yoggGUID
ObjectGuid boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::_yoggGUID
Referenced by Reset(), Say(), and UpdateAI().