AzeorthCore: boss_nalorakk::boss_nalorakkAI Struct Reference
boss_nalorakk::boss_nalorakkAI Struct Reference
Public Member Functions
boss_nalorakkAI (Creature *creature)
void Reset () override
void ResetMobs ()
void SendAttacker (Unit *target)
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
Cast Spell.
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
Play sound.
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
Reset Threat.
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
Modify Unit Threat.
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
Teleport player.
void DoTeleportAll (float x, float y, float z, float o)
Teleport all.
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
Set Combat Movement.
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectTargetMethod targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
uint32 BrutalSwipe_Timer
uint32 Mangle_Timer
uint32 Surge_Timer
uint32 LaceratingSlash_Timer
uint32 RendFlesh_Timer
uint32 DeafeningRoar_Timer
uint32 ShapeShift_Timer
uint32 Berserk_Timer
bool inBearForm
bool MoveEvent
bool inMove
uint32 MovePhase
uint32 waitTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_nalorakkAI()
boss_nalorakk::boss_nalorakkAI::boss_nalorakkAI (Creature * creature) inline
                                            : ScriptedAI(creature)
        {
            MoveEvent = true;
            MovePhase = 0;
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), instance, MoveEvent, and MovePhase.
Member Function Documentation
AttackStart()
void boss_nalorakk::boss_nalorakkAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!MoveEvent)
                ScriptedAI::AttackStart(who);
        }
References ScriptedAI::AttackStart(), and MoveEvent.
EnterCombat()
void boss_nalorakk::boss_nalorakkAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (instance)
                instance->SetData(DATA_NALORAKKEVENT, IN_PROGRESS);
            Talk(SAY_AGGRO);
            DoZoneInCombat();
        }
References DATA_NALORAKKEVENT, CreatureAI::DoZoneInCombat(), IN_PROGRESS, instance, SAY_AGGRO, and ZoneScript::SetData().
JustDied()
void boss_nalorakk::boss_nalorakkAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            ResetMobs();
            if (instance)
                instance->SetData(DATA_NALORAKKEVENT, DONE);
            Talk(SAY_DEATH);
        }
References DATA_NALORAKKEVENT, DONE, instance, ResetMobs(), SAY_DEATH, and ZoneScript::SetData().
KilledUnit()
void boss_nalorakk::boss_nalorakkAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            switch (urand(0, 1))
            {
                case 0:
                    Talk(SAY_KILL_ONE);
                    break;
                case 1:
                    Talk(SAY_KILL_TWO);
                    break;
            }
        }
References SAY_KILL_ONE, SAY_KILL_TWO, and urand().
MoveInLineOfSight()
void boss_nalorakk::boss_nalorakkAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!MoveEvent)
            {
                ScriptedAI::MoveInLineOfSight(who);
            }
            else
            {
                if (me->IsHostileTo(who))
                {
                    if (!inMove)
                    {
                        switch (MovePhase)
{
                            case 0:
                                if (me->IsWithinDistInMap(who, 50))
{
                                    Talk(SAY_WAVE1);
                                    (*me).GetMotionMaster()->MovePoint(1, NalorakkWay[1][0], NalorakkWay[1][1], NalorakkWay[1][2]);
                                    MovePhase ++;
                                    inMove = true;
                                    SendAttacker(who);
                                }
                                break;
                            case 2:
                                if (me->IsWithinDistInMap(who, 40))
{
                                    Talk(SAY_WAVE2);
                                    (*me).GetMotionMaster()->MovePoint(3, NalorakkWay[3][0], NalorakkWay[3][1], NalorakkWay[3][2]);
                                    MovePhase ++;
                                    inMove = true;
                                    SendAttacker(who);
                                }
                                break;
                            case 5:
                                if (me->IsWithinDistInMap(who, 40))
{
                                    Talk(SAY_WAVE3);
                                    (*me).GetMotionMaster()->MovePoint(6, NalorakkWay[6][0], NalorakkWay[6][1], NalorakkWay[6][2]);
                                    MovePhase ++;
                                    inMove = true;
                                    SendAttacker(who);
                                }
                                break;
                            case 7:
                                if (me->IsWithinDistInMap(who, 50))
{
                                    SendAttacker(who);
                                    Talk(SAY_WAVE4);
                                    me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                                    MoveEvent = false;
                                }
                                break;
                        }
                    }
                }
            }
        }
References inMove, Unit::IsHostileTo(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, MoveEvent, CreatureAI::MoveInLineOfSight(), MovePhase, NalorakkWay, Unit::RemoveUnitFlag(), SAY_WAVE1, SAY_WAVE2, SAY_WAVE3, SAY_WAVE4, SendAttacker(), UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
MovementInform()
void boss_nalorakk::boss_nalorakkAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (MoveEvent)
            {
                if (type != POINT_MOTION_TYPE)
                    return;
                if (!inMove)
                    return;
                if (MovePhase != id)
                    return;
                switch (MovePhase)
                {
                    case 2:
                        me->SetOrientation(3.1415f * 2);
                        inMove = false;
                        return;
                    case 1:
                    case 3:
                    case 4:
                    case 6:
                        MovePhase ++;
                        waitTimer = 1;
                        inMove = true;
                        return;
                    case 5:
                        me->SetOrientation(3.1415f * 0.5f);
                        inMove = false;
                        return;
                    case 7:
                        me->SetOrientation(3.1415f * 0.5f);
                        inMove = false;
                        return;
                }
            }
        }
References inMove, ScriptedAI::me, MoveEvent, MovePhase, POINT_MOTION_TYPE, Position::SetOrientation(), and waitTimer.
Reset()
void boss_nalorakk::boss_nalorakkAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            if (MoveEvent)
            {
                me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                inMove = false;
                waitTimer = 0;
                me->SetSpeed(MOVE_RUN, 2);
                me->SetWalk(false);
                ResetMobs();
            }
            else
            {
                (*me).GetMotionMaster()->MovePoint(0, NalorakkWay[7][0], NalorakkWay[7][1], NalorakkWay[7][2]);
            }
            if (instance)
            {
                instance->SetData(DATA_NALORAKKEVENT, NOT_STARTED);
            }
            Surge_Timer = urand(15000, 20000);
            BrutalSwipe_Timer = urand(7000, 12000);
            Mangle_Timer = urand(10000, 15000);
            ShapeShift_Timer = urand(45000, 50000);
            Berserk_Timer = 600000;
            inBearForm = false;
            // me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, 5122);  /// @todo find the correct equipment id
        }
References Berserk_Timer, BrutalSwipe_Timer, DATA_NALORAKKEVENT, inBearForm, inMove, instance, Mangle_Timer, ScriptedAI::me, MOVE_RUN, MoveEvent, NalorakkWay, NOT_STARTED, ResetMobs(), ZoneScript::SetData(), Unit::SetSpeed(), Unit::SetUnitFlag(), Creature::SetWalk(), ShapeShift_Timer, Surge_Timer, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, urand(), and waitTimer.
ResetMobs()
void boss_nalorakk::boss_nalorakkAI::ResetMobs () inline
        {
            std::list<Creature*> templist;
            float x, y, z;
            me->GetPosition(x, y, z);
            {
                CellCoord pair(Acore::ComputeCellCoord(x, y));
                Cell cell(pair);
                cell.SetNoCreate();
                Acore::AllFriendlyCreaturesInGrid check(me);
                Acore::CreatureListSearcher<Acore::AllFriendlyCreaturesInGrid> searcher(me, templist, check);
                TypeContainerVisitor<Acore::CreatureListSearcher<Acore::AllFriendlyCreaturesInGrid>, GridTypeMapContainer> cSearcher(searcher);
                cell.Visit(pair, cSearcher, *(me->GetMap()), *me, me->GetGridActivationRange());
            }
            if (templist.empty())
                return;
            for (std::list<Creature*>::const_iterator i = templist.begin(); i != templist.end(); ++i)
                if ((*i) && me->GetGUID() != (*i)->GetGUID() && me->IsWithinDistInMap((*i), 25))
                    (*i)->AI()->Reset();
        }
References Acore::ComputeCellCoord(), WorldObject::GetGridActivationRange(), Object::GetGUID(), WorldObject::GetMap(), Position::GetPosition(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, Cell::SetNoCreate(), and Cell::Visit().
Referenced by JustDied(), and Reset().
SendAttacker()
void boss_nalorakk::boss_nalorakkAI::SendAttacker (Unit * target) inline
        {
            std::list<Creature*> templist;
            float x, y, z;
            me->GetPosition(x, y, z);
            {
                CellCoord pair(Acore::ComputeCellCoord(x, y));
                Cell cell(pair);
                cell.SetNoCreate();
                Acore::AllFriendlyCreaturesInGrid check(me);
                Acore::CreatureListSearcher<Acore::AllFriendlyCreaturesInGrid> searcher(me, templist, check);
                TypeContainerVisitor<Acore::CreatureListSearcher<Acore::AllFriendlyCreaturesInGrid>, GridTypeMapContainer> cSearcher(searcher);
                cell.Visit(pair, cSearcher, *(me->GetMap()), *me, me->GetGridActivationRange());
            }
            if (templist.empty())
                return;
            for (std::list<Creature*>::const_iterator i = templist.begin(); i != templist.end(); ++i)
            {
                if ((*i) && me->IsWithinDistInMap((*i), 25))
                {
                    (*i)->SetNoCallAssistance(true);
                    (*i)->AI()->AttackStart(target);
                }
            }
        }
References Acore::ComputeCellCoord(), WorldObject::GetGridActivationRange(), WorldObject::GetMap(), Position::GetPosition(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, Cell::SetNoCreate(), and Cell::Visit().
Referenced by MoveInLineOfSight().
UpdateAI()
void boss_nalorakk::boss_nalorakkAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (waitTimer && inMove)
            {
                if (waitTimer <= diff)
                {
                    (*me).GetMotionMaster()->MovementExpired();
                    (*me).GetMotionMaster()->MovePoint(MovePhase, NalorakkWay[MovePhase][0], NalorakkWay[MovePhase][1], NalorakkWay[MovePhase][2]);
                    waitTimer = 0;
                }
                else waitTimer -= diff;
            }
            if (!UpdateVictim())
                return;
            if (Berserk_Timer <= diff)
            {
                DoCast(me, SPELL_BERSERK, true);
                Talk(SAY_BERSERK);
                Berserk_Timer = 600000;
            }
            else Berserk_Timer -= diff;
            if (ShapeShift_Timer <= diff)
            {
                if (inBearForm)
                {
                    // me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, 5122);
                    Talk(SAY_SHIFTEDTOTROLL);
                    me->RemoveAurasDueToSpell(SPELL_BEARFORM);
                    Surge_Timer = urand(15000, 20000);
                    BrutalSwipe_Timer = urand(7000, 12000);
                    Mangle_Timer = urand(10000, 15000);
                    ShapeShift_Timer = urand(45000, 50000);
                    inBearForm = false;
                }
                else
                {
                    // me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, 0);
                    Talk(SAY_SHIFTEDTOBEAR);
                    DoCast(me, SPELL_BEARFORM, true);
                    LaceratingSlash_Timer = 2000; // dur 18s
                    RendFlesh_Timer = 3000;  // dur 5s
                    DeafeningRoar_Timer = urand(5000, 10000);  // dur 2s
                    ShapeShift_Timer = urand(20000, 25000); // dur 30s
                    inBearForm = true;
                }
            }
            else ShapeShift_Timer -= diff;
            if (!inBearForm)
            {
                if (BrutalSwipe_Timer <= diff)
                {
                    DoCastVictim(SPELL_BRUTALSWIPE);
                    BrutalSwipe_Timer = urand(7000, 12000);
                }
                else BrutalSwipe_Timer -= diff;
                if (Mangle_Timer <= diff)
                {
                    if (me->GetVictim() && !me->GetVictim()->HasAura(SPELL_MANGLEEFFECT))
                    {
                        DoCastVictim(SPELL_MANGLE);
                        Mangle_Timer = 1000;
                    }
                    else Mangle_Timer = urand(10000, 15000);
                }
                else Mangle_Timer -= diff;
                if (Surge_Timer <= diff)
                {
                    Talk(SAY_SURGE);
                    Unit* target = SelectTarget(SelectTargetMethod::Random, 1, 45, true);
                    if (target)
                        DoCast(target, SPELL_SURGE);
                    Surge_Timer = urand(15000, 20000);
                }
                else Surge_Timer -= diff;
            }
            else
            {
                if (LaceratingSlash_Timer <= diff)
                {
                    DoCastVictim(SPELL_LACERATINGSLASH);
                    LaceratingSlash_Timer = urand(18000, 23000);
                }
                else LaceratingSlash_Timer -= diff;
                if (RendFlesh_Timer <= diff)
                {
                    DoCastVictim(SPELL_RENDFLESH);
                    RendFlesh_Timer = urand(5000, 10000);
                }
                else RendFlesh_Timer -= diff;
                if (DeafeningRoar_Timer <= diff)
                {
                    DoCastVictim(SPELL_DEAFENINGROAR);
                    DeafeningRoar_Timer = urand(15000, 20000);
                }
                else DeafeningRoar_Timer -= diff;
            }
            DoMeleeAttackIfReady();
        }
References Berserk_Timer, BrutalSwipe_Timer, DeafeningRoar_Timer, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), Unit::GetVictim(), Unit::HasAura(), inBearForm, inMove, LaceratingSlash_Timer, Mangle_Timer, ScriptedAI::me, MovePhase, NalorakkWay, Unit::RemoveAurasDueToSpell(), RendFlesh_Timer, SAY_BERSERK, SAY_SHIFTEDTOBEAR, SAY_SHIFTEDTOTROLL, SAY_SURGE, UnitAI::SelectTarget(), ShapeShift_Timer, SPELL_BEARFORM, SPELL_BERSERK, SPELL_BRUTALSWIPE, SPELL_DEAFENINGROAR, SPELL_LACERATINGSLASH, SPELL_MANGLE, SPELL_MANGLEEFFECT, SPELL_RENDFLESH, SPELL_SURGE, Surge_Timer, CreatureAI::UpdateVictim(), urand(), and waitTimer.
Member Data Documentation
Berserk_Timer
uint32 boss_nalorakk::boss_nalorakkAI::Berserk_Timer
Referenced by Reset(), and UpdateAI().
BrutalSwipe_Timer
uint32 boss_nalorakk::boss_nalorakkAI::BrutalSwipe_Timer
Referenced by Reset(), and UpdateAI().
DeafeningRoar_Timer
uint32 boss_nalorakk::boss_nalorakkAI::DeafeningRoar_Timer
Referenced by UpdateAI().
inBearForm
bool boss_nalorakk::boss_nalorakkAI::inBearForm
Referenced by Reset(), and UpdateAI().
inMove
bool boss_nalorakk::boss_nalorakkAI::inMove
Referenced by MoveInLineOfSight(), MovementInform(), Reset(), and UpdateAI().
instance
InstanceScript* boss_nalorakk::boss_nalorakkAI::instance
Referenced by boss_nalorakkAI(), EnterCombat(), JustDied(), and Reset().
LaceratingSlash_Timer
uint32 boss_nalorakk::boss_nalorakkAI::LaceratingSlash_Timer
Referenced by UpdateAI().
Mangle_Timer
uint32 boss_nalorakk::boss_nalorakkAI::Mangle_Timer
Referenced by Reset(), and UpdateAI().
MoveEvent
bool boss_nalorakk::boss_nalorakkAI::MoveEvent
Referenced by AttackStart(), boss_nalorakkAI(), MoveInLineOfSight(), MovementInform(), and Reset().
MovePhase
uint32 boss_nalorakk::boss_nalorakkAI::MovePhase
Referenced by boss_nalorakkAI(), MoveInLineOfSight(), MovementInform(), and UpdateAI().
RendFlesh_Timer
uint32 boss_nalorakk::boss_nalorakkAI::RendFlesh_Timer
Referenced by UpdateAI().
ShapeShift_Timer
uint32 boss_nalorakk::boss_nalorakkAI::ShapeShift_Timer
Referenced by Reset(), and UpdateAI().
Surge_Timer
uint32 boss_nalorakk::boss_nalorakkAI::Surge_Timer
Referenced by Reset(), and UpdateAI().
waitTimer
uint32 boss_nalorakk::boss_nalorakkAI::waitTimer
Referenced by MovementInform(), Reset(), and UpdateAI().