AzeorthCore: gear_commandscript Class Reference
gear_commandscript Class Reference
Public Member Functions
gear_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleGearRepairCommand (ChatHandler *handler, Optional< PlayerIdentifier > target)
static bool HandleGearStatsCommand (ChatHandler *handler)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
gear_commandscript()
gear_commandscript::gear_commandscript () inline
: CommandScript("gear_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable gear_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable gearCommandTable =
        {
            { "repair",  HandleGearRepairCommand, SEC_GAMEMASTER, Console::No },
            { "stats",   HandleGearStatsCommand,  SEC_PLAYER,     Console::No }
        };
        static ChatCommandTable commandTable =
        {
            { "gear", gearCommandTable }
        };
        return commandTable;
    }
References HandleGearRepairCommand(), HandleGearStatsCommand(), SEC_GAMEMASTER, and SEC_PLAYER.
HandleGearRepairCommand()
static bool gear_commandscript::HandleGearRepairCommand (ChatHandler * handler, Optional< PlayerIdentifier > target) inline static
    {
        if (!target)
        {
            target = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!target || !target->IsConnected())
        {
            return false;
        }
        // check online security
        if (handler->HasLowerSecurity(target->GetConnectedPlayer()))
        {
            return false;
        }
        // Repair items
        target->GetConnectedPlayer()->DurabilityRepairAll(false, 0, false);
        std::string nameLink = handler->playerLink(target->GetName());
        handler->PSendSysMessage(LANG_YOU_REPAIR_ITEMS, nameLink.c_str());
        if (handler->needReportToTarget(target->GetConnectedPlayer()))
        {
            ChatHandler(target->GetConnectedPlayer()->GetSession()).PSendSysMessage(LANG_YOUR_ITEMS_REPAIRED, nameLink.c_str());
        }
        return true;
    }
References Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), ChatHandler::HasLowerSecurity(), LANG_YOU_REPAIR_ITEMS, LANG_YOUR_ITEMS_REPAIRED, ChatHandler::needReportToTarget(), ChatHandler::playerLink(), and ChatHandler::PSendSysMessage().
Referenced by GetCommands().
HandleGearStatsCommand()
static bool gear_commandscript::HandleGearStatsCommand (ChatHandler * handler) inline static
    {
        Player* player = handler->getSelectedPlayerOrSelf();
        if (!player)
        {
            return false;
        }
        handler->PSendSysMessage("Character: %s", player->GetPlayerName().c_str());
        handler->PSendSysMessage("Current equipment average item level: |cff00ffff%u|r", (int16)player->GetAverageItemLevel());
        if (sWorld->getIntConfig(CONFIG_MIN_LEVEL_STAT_SAVE))
        {
            CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_STATS);
            stmt->SetData(0, player->GetGUID().GetCounter());
            PreparedQueryResult result = CharacterDatabase.Query(stmt);
            if (result)
            {
                Field* fields = result->Fetch();
                uint32 MaxHealth = fields[0].Get<uint32>();
                uint32 Strength = fields[1].Get<uint32>();
                uint32 Agility = fields[2].Get<uint32>();
                uint32 Stamina = fields[3].Get<uint32>();
                uint32 Intellect = fields[4].Get<uint32>();
                uint32 Spirit = fields[5].Get<uint32>();
                uint32 Armor = fields[6].Get<uint32>();
                uint32 AttackPower = fields[7].Get<uint32>();
                uint32 SpellPower = fields[8].Get<uint32>();
                uint32 Resilience = fields[9].Get<uint32>();
                handler->PSendSysMessage("Health: |cff00ffff%u|r - Stamina: |cff00ffff%u|r", MaxHealth, Stamina);
                handler->PSendSysMessage("Strength: |cff00ffff%u|r - Agility: |cff00ffff%u|r", Strength, Agility);
                handler->PSendSysMessage("Intellect: |cff00ffff%u|r - Spirit: |cff00ffff%u|r", Intellect, Spirit);
                handler->PSendSysMessage("AttackPower: |cff00ffff%u|r - SpellPower: |cff00ffff%u|r", AttackPower, SpellPower);
                handler->PSendSysMessage("Armor: |cff00ffff%u|r - Resilience: |cff00ffff%u|r", Armor, Resilience);
            }
        }
        return true;
    }
References CHAR_SEL_CHAR_STATS, CharacterDatabase, CONFIG_MIN_LEVEL_STAT_SAVE, Field::Get(), Player::GetAverageItemLevel(), ObjectGuid::GetCounter(), Object::GetGUID(), Player::GetPlayerName(), ChatHandler::getSelectedPlayerOrSelf(), ChatHandler::PSendSysMessage(), PreparedStatementBase::SetData(), and sWorld.
Referenced by GetCommands().