AzerothCore: spell_gen_bg_preparation Class Reference
spell_gen_bg_preparation Class Reference
Private Member Functions
PrepareAuraScript (spell_gen_bg_preparation) void HandleEffectApply(AuraEffect const *
void HandleEffectRemove (AuraEffect const *, AuraEffectHandleModes)
void CalcPeriodic (AuraEffect const *, bool &isPeriodic, int32 &amplitude)
void Update (AuraEffect *)
void Register () override
Private Attributes
AuraEffectHandleModes
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
CalcPeriodic()
void spell_gen_bg_preparation::CalcPeriodic (AuraEffect const * , bool & isPeriodic, int32 & amplitude) inline private
    {
        isPeriodic = true;
        amplitude = 3 * IN_MILLISECONDS;
    }
References IN_MILLISECONDS.
Referenced by Register().
HandleEffectRemove()
void spell_gen_bg_preparation::HandleEffectRemove (AuraEffect const * , AuraEffectHandleModes) inline private
    {
        GetTarget()->ApplySpellImmune(GetId(), IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_ALL, false);
    }
References Unit::ApplySpellImmune(), AuraScript::GetId(), AuraScript::GetTarget(), IMMUNITY_DAMAGE, and SPELL_SCHOOL_MASK_ALL.
Referenced by Register().
PrepareAuraScript()
spell_gen_bg_preparation::PrepareAuraScript (spell_gen_bg_preparation) const private
Register()
void spell_gen_bg_preparation::Register () inline override private virtual
Implements _SpellScript.
    {
        OnEffectApply += AuraEffectApplyFn(spell_gen_bg_preparation::HandleEffectApply, EFFECT_0, SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT, AURA_EFFECT_HANDLE_REAL);
        OnEffectRemove += AuraEffectRemoveFn(spell_gen_bg_preparation::HandleEffectRemove, EFFECT_0, SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT, AURA_EFFECT_HANDLE_REAL);
        DoEffectCalcPeriodic += AuraEffectCalcPeriodicFn(spell_gen_bg_preparation::CalcPeriodic, EFFECT_0, SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT);
        OnEffectUpdatePeriodic += AuraEffectUpdatePeriodicFn(spell_gen_bg_preparation::Update, EFFECT_0, SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT);
    }
References AURA_EFFECT_HANDLE_REAL, AuraEffectApplyFn, AuraEffectCalcPeriodicFn, AuraEffectRemoveFn, AuraEffectUpdatePeriodicFn, CalcPeriodic(), AuraScript::DoEffectCalcPeriodic, EFFECT_0, HandleEffectRemove(), AuraScript::OnEffectApply, AuraScript::OnEffectRemove, AuraScript::OnEffectUpdatePeriodic, SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT, and Update().
Update()
void spell_gen_bg_preparation::Update (AuraEffect *) inline private
    {
        if (Player* player = GetUnitOwner()->GetCharmerOrOwnerPlayerOrPlayerItself())
            if (MapEntry const* mapEntry = sMapStore.LookupEntry(player->GetMapId()))
                if ((GetId() == 32727 && mapEntry->IsBattleArena()) || (GetId() == 44521 && mapEntry->IsBattleground()))
                    if (Battleground* bg = player->GetBattleground())
                        if (bg->GetStatus() == STATUS_WAIT_JOIN)
                            return;
        SetMaxDuration(1);
        SetDuration(1);
    }
References AuraScript::GetId(), AuraScript::GetUnitOwner(), AuraScript::SetDuration(), AuraScript::SetMaxDuration(), sMapStore, and STATUS_WAIT_JOIN.
Referenced by Register().
Member Data Documentation
AuraEffectHandleModes
spell_gen_bg_preparation::AuraEffectHandleModes private
Initial value:
{
        GetTarget()->ApplySpellImmune(GetId(), IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_ALL, true)