AzerothCore: spell_halion_twilight_division::spell_halion_twilight_division_SpellScript Class Reference
spell_halion_twilight_division::spell_halion_twilight_division_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_halion_twilight_division_SpellScript)
void HandleDummy (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleDummy()
void spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::HandleDummy (SpellEffIndex) inline private
        {
            InstanceScript* instance = GetCaster()->GetInstanceScript();
            Creature* controller = ObjectAccessor::GetCreature(*GetCaster(), instance->GetGuidData(NPC_HALION_CONTROLLER));
            Creature* halion = ObjectAccessor::GetCreature(*GetCaster(), instance->GetGuidData(NPC_HALION));
            if (!controller || !halion)
                return;
            GetCaster()->CastSpell(GetCaster(), _corporealityReference[5], true);
            halion->CastSpell(halion, _corporealityReference[5], true);
            controller->CastSpell(controller, SPELL_SUMMON_EXIT_PORTALS_NORMAL, true);
            controller->CastSpell(controller, SPELL_SUMMON_EXIT_PORTALS, true);
            controller->AI()->DoAction(ACTION_CHECK_CORPOREALITY);
            halion->RemoveAurasDueToSpell(SPELL_TWILIGHT_PHASING);
            if (GameObject* gobject = halion->FindNearestGameObject(GO_HALION_PORTAL_1, 100.0f))
                gobject->Delete();
            instance->DoUpdateWorldState(WORLDSTATE_CORPOREALITY_TOGGLE, 1);
            instance->DoUpdateWorldState(WORLDSTATE_CORPOREALITY_MATERIAL, 50);
            instance->DoUpdateWorldState(WORLDSTATE_CORPOREALITY_TWILIGHT, 50);
        }
References _corporealityReference, ACTION_CHECK_CORPOREALITY, Creature::AI(), Unit::CastSpell(), UnitAI::DoAction(), InstanceScript::DoUpdateWorldState(), WorldObject::FindNearestGameObject(), SpellScript::GetCaster(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), GO_HALION_PORTAL_1, NPC_HALION, NPC_HALION_CONTROLLER, Unit::RemoveAurasDueToSpell(), SPELL_SUMMON_EXIT_PORTALS, SPELL_SUMMON_EXIT_PORTALS_NORMAL, SPELL_TWILIGHT_PHASING, WORLDSTATE_CORPOREALITY_MATERIAL, WORLDSTATE_CORPOREALITY_TOGGLE, and WORLDSTATE_CORPOREALITY_TWILIGHT.
Referenced by Register().
PrepareSpellScript()
spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::PrepareSpellScript (spell_halion_twilight_division_SpellScript) private
Register()
void spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::Register () inline override private virtual
Implements _SpellScript.
        {
            OnEffectHitTarget += SpellEffectFn(spell_halion_twilight_division_SpellScript::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
        }
References EFFECT_0, HandleDummy(), SpellScript::OnEffectHitTarget, SPELL_EFFECT_DUMMY, and SpellEffectFn.