AzerothCore: go_troll_cage::go_troll_cageAI Struct Reference
go_troll_cage::go_troll_cageAI Struct Reference
Public Member Functions
go_troll_cageAI (GameObject *go)
bool GossipHello (Player *, bool reportUse) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Public Attributes
InstanceScript * instance
Private Member Functions
void initBlyCrewMember (uint32 entry, float x, float y, float z)
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_troll_cageAI()
go_troll_cage::go_troll_cageAI::go_troll_cageAI (GameObject * go) inline
: GameObjectAI(go), instance(go->GetInstanceScript()) { }
Member Function Documentation
GossipHello()
bool go_troll_cage::go_troll_cageAI::GossipHello (Player * , bool reportUse) inline override virtual
Reimplemented from GameObjectAI.
        {
            if (reportUse)
            {
                return true;
            }
            instance->SetData(DATA_PYRAMID, PYRAMID_CAGES_OPEN);
            //setting gossip option as soon as the cages open
            if (Creature* bly = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BLY)))
            {
                bly->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            }
            if (Creature* weegli = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_WEEGLI)))
            {
                weegli->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            }
            //set bly & co to aggressive & start moving to top of stairs
            initBlyCrewMember(NPC_BLY, 1884.99f, 1263, 41.52f);
            initBlyCrewMember(NPC_RAVEN, 1882.5f, 1263, 41.52f);
            initBlyCrewMember(NPC_ORO, 1886.47f, 1270.68f, 41.68f);
            initBlyCrewMember(NPC_WEEGLI, 1890, 1263, 41.52f);
            initBlyCrewMember(NPC_MURTA, 1891.19f, 1272.03f, 41.60f);
            return false;
        }
References DATA_PYRAMID, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), initBlyCrewMember(), instance, GameObjectAI::me, NPC_BLY, NPC_MURTA, NPC_ORO, NPC_RAVEN, NPC_WEEGLI, PYRAMID_CAGES_OPEN, ZoneScript::SetData(), and UNIT_NPC_FLAG_GOSSIP.
initBlyCrewMember()
void go_troll_cage::go_troll_cageAI::initBlyCrewMember (uint32 entry, float x, float y, float z) inline private
        {
            if (Creature* crew = ObjectAccessor::GetCreature(*me, instance->GetGuidData(entry)))
            {
                crew->SetReactState(REACT_AGGRESSIVE);
                crew->SetWalk(true);
                crew->SetHomePosition(x, y, z, 4.78f);
                crew->GetMotionMaster()->MovePoint(1, { x, y, z, 4.78f });
                crew->SetFaction(FACTION_ESCORT_N_NEUTRAL_ACTIVE);
            }
        }
References FACTION_ESCORT_N_NEUTRAL_ACTIVE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), instance, GameObjectAI::me, and REACT_AGGRESSIVE.
Referenced by GossipHello().
Member Data Documentation
instance
InstanceScript* go_troll_cage::go_troll_cageAI::instance
Referenced by GossipHello(), and initBlyCrewMember().