AzerothCore: lfg_commandscript Class Reference
lfg_commandscript Class Reference
Public Member Functions
lfg_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleLfgPlayerInfoCommand (ChatHandler *handler, Optional< PlayerIdentifier > player)
static bool HandleLfgGroupInfoCommand (ChatHandler *handler, Optional< PlayerIdentifier > player)
static bool HandleLfgOptionsCommand (ChatHandler *handler, Optional< uint32 > optionsArg)
static bool HandleLfgQueueInfoCommand (ChatHandler *)
static bool HandleLfgCleanCommand (ChatHandler *handler)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
lfg_commandscript()
lfg_commandscript::lfg_commandscript () inline
: CommandScript("lfg_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable lfg_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable lfgCommandTable =
        {
            { "player",  HandleLfgPlayerInfoCommand, SEC_MODERATOR,     Console::No },
            { "group",   HandleLfgGroupInfoCommand,  SEC_MODERATOR,     Console::No },
            { "queue",   HandleLfgQueueInfoCommand,  SEC_MODERATOR,     Console::Yes },
            { "clean",   HandleLfgCleanCommand,      SEC_ADMINISTRATOR, Console::Yes },
            { "options", HandleLfgOptionsCommand,    SEC_GAMEMASTER,    Console::Yes },
        };
        static ChatCommandTable commandTable =
        {
            { "lfg", lfgCommandTable },
        };
        return commandTable;
    }
References HandleLfgCleanCommand(), HandleLfgGroupInfoCommand(), HandleLfgOptionsCommand(), HandleLfgPlayerInfoCommand(), HandleLfgQueueInfoCommand(), SEC_ADMINISTRATOR, SEC_GAMEMASTER, and SEC_MODERATOR.
HandleLfgCleanCommand()
static bool lfg_commandscript::HandleLfgCleanCommand (ChatHandler * handler) inline static
    {
        handler->PSendSysMessage(LANG_LFG_CLEAN);
        sLFGMgr->Clean();
        return true;
    }
References LANG_LFG_CLEAN, ChatHandler::PSendSysMessage(), and sLFGMgr.
Referenced by GetCommands().
HandleLfgGroupInfoCommand()
static bool lfg_commandscript::HandleLfgGroupInfoCommand (ChatHandler * handler, Optional< PlayerIdentifier > player) inline static
    {
        if (!player)
            player = PlayerIdentifier::FromTargetOrSelf(handler);
        if (!player)
            return false;
        Group* groupTarget = nullptr;
        if (Player* target = player->GetConnectedPlayer())
            groupTarget = target->GetGroup();
        if (!groupTarget)
        {
            handler->PSendSysMessage(LANG_LFG_NOT_IN_GROUP, player->GetName());
            return true;
        }
        ObjectGuid guid = groupTarget->GetGUID();
        std::string const& state = lfg::GetStateString(sLFGMgr->GetState(guid));
        handler->PSendSysMessage(LANG_LFG_GROUP_INFO, groupTarget->isLFGGroup(),
                                 state, sLFGMgr->GetDungeon(guid));
        for (GroupReference* itr = groupTarget->GetFirstMember(); itr != nullptr; itr = itr->next())
            GetPlayerInfo(handler, itr->GetSource());
        return true;
    }
References Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Group::GetFirstMember(), Group::GetGUID(), GetPlayerInfo(), lfg::GetStateString(), Group::isLFGGroup(), LANG_LFG_GROUP_INFO, LANG_LFG_NOT_IN_GROUP, GroupReference::next(), ChatHandler::PSendSysMessage(), and sLFGMgr.
Referenced by GetCommands().
HandleLfgOptionsCommand()
static bool lfg_commandscript::HandleLfgOptionsCommand (ChatHandler * handler, Optional< uint32 > optionsArg) inline static
    {
        if (optionsArg)
        {
            sLFGMgr->SetOptions(*optionsArg);
            handler->PSendSysMessage(LANG_LFG_OPTIONS_CHANGED);
        }
        handler->PSendSysMessage(LANG_LFG_OPTIONS, sLFGMgr->GetOptions());
        return true;
    }
References LANG_LFG_OPTIONS, LANG_LFG_OPTIONS_CHANGED, ChatHandler::PSendSysMessage(), and sLFGMgr.
Referenced by GetCommands().
HandleLfgPlayerInfoCommand()
static bool lfg_commandscript::HandleLfgPlayerInfoCommand (ChatHandler * handler, Optional< PlayerIdentifier > player) inline static
    {
        if (!player)
            player = PlayerIdentifier::FromTargetOrSelf(handler);
        if (!player)
            return false;
        if (Player* target = player->GetConnectedPlayer())
        {
            GetPlayerInfo(handler, target);
            return true;
        }
        return false;
    }
References Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), and GetPlayerInfo().
Referenced by GetCommands().
HandleLfgQueueInfoCommand()
static bool lfg_commandscript::HandleLfgQueueInfoCommand (ChatHandler *) inline static
    {
        return true;
    }
Referenced by GetCommands().