AzerothCore: boss_grand_champion::boss_grand_championAI Struct Reference
boss_grand_champion::boss_grand_championAI Struct Reference
Public Member Functions
boss_grand_championAI (Creature *pCreature)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void ScheduleAbilitiesEvents ()
void AddCreatureAddonAuras ()
void DoAction (int32 param) override
void SetData (uint32 uiType, uint32 uiData) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void EnterEvadeMode (EvadeReason) override
void WaypointReached (uint32 i) override
void MovementInform (uint32 type, uint32 id) override
void SpellHit (Unit *, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
uint32 BossOrder
bool MountPhase
ObjectGuid NewMountGUID
ObjectGuid UnitTargetGUID
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_grand_championAI()
boss_grand_champion::boss_grand_championAI::boss_grand_championAI (Creature * pCreature) inline
                                                   : npc_escortAI(pCreature)
        {
            pInstance = pCreature->GetInstanceScript();
            MountPhase = true;
            SetDespawnAtEnd(false);
            me->SetReactState(REACT_PASSIVE);
            BossOrder = 0;
            NewMountGUID.Clear();
            me->CastSpell(me, SPELL_BOSS_DEFEND_PERIODIC, true);
            events.Reset();
            events.ScheduleEvent(EVENT_MOUNT_CHARGE, 2500ms, 4000ms);
            events.ScheduleEvent(EVENT_SHIELD_BREAKER, 5s, 8s);
            events.ScheduleEvent(EVENT_THRUST, 3s, 5s);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_CHARM, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_DISORIENTED, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_DISTRACT, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_FEAR, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_GRIP, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_ROOT, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_SLEEP, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_SNARE, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_FREEZE, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_KNOCKOUT, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_POLYMORPH, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_BANISH, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_SHACKLE, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_TURN, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_HORROR, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_INTERRUPT, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_DAZE, true);
            me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_SAPPED, true);
        }
References Unit::ApplySpellImmune(), BossOrder, Unit::CastSpell(), ObjectGuid::Clear(), EVENT_MOUNT_CHARGE, EVENT_SHIELD_BREAKER, EVENT_THRUST, WorldObject::GetInstanceScript(), IMMUNITY_MECHANIC, ScriptedAI::me, MECHANIC_BANISH, MECHANIC_CHARM, MECHANIC_DAZE, MECHANIC_DISORIENTED, MECHANIC_DISTRACT, MECHANIC_FEAR, MECHANIC_FREEZE, MECHANIC_GRIP, MECHANIC_HORROR, MECHANIC_INTERRUPT, MECHANIC_KNOCKOUT, MECHANIC_POLYMORPH, MECHANIC_ROOT, MECHANIC_SAPPED, MECHANIC_SHACKLE, MECHANIC_SLEEP, MECHANIC_SNARE, MECHANIC_TURN, MountPhase, NewMountGUID, pInstance, REACT_PASSIVE, npc_escortAI::SetDespawnAtEnd(), Creature::SetReactState(), and SPELL_BOSS_DEFEND_PERIODIC.
Member Function Documentation
AddCreatureAddonAuras()
void boss_grand_champion::boss_grand_championAI::AddCreatureAddonAuras () inline
        {
            CreatureAddon const* cainfo = me->GetCreatureAddon();
            if (!cainfo)
                return;
            if (!cainfo->auras.empty())
            {
                for (std::vector<uint32>::const_iterator itr = cainfo->auras.begin(); itr != cainfo->auras.end(); ++itr)
                {
                    SpellInfo const* AdditionalSpellInfo = sSpellMgr->GetSpellInfo(*itr);
                    if (!AdditionalSpellInfo)
                        continue;
                    if (me->HasAura(AdditionalSpellInfo->Id))
                        continue;
                    me->AddAura(AdditionalSpellInfo->Id, me);
                }
            }
        }
References Unit::AddAura(), CreatureAddon::auras, Creature::GetCreatureAddon(), Unit::HasAura(), SpellInfo::Id, ScriptedAI::me, and sSpellMgr.
Referenced by DamageTaken(), and DoAction().
DamageTaken()
void boss_grand_champion::boss_grand_championAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (MountPhase)
            {
                if (me->GetUInt32Value(UNIT_FIELD_MOUNTDISPLAYID) == 0 )
                    damage = 0;
                else if (damage >= me->GetHealth())
                {
                    events.Reset();
                    damage = me->GetHealth() - 1;
                    me->SetReactState(REACT_PASSIVE);
                    me->RemoveAllAuras();
                    AddCreatureAddonAuras();
                    me->GetThreatMgr().ClearAllThreat();
                    me->CombatStop(true);
                    me->GetMotionMaster()->Clear();
                    me->StopMoving();
                    me->SetUInt32Value(UNIT_FIELD_MOUNTDISPLAYID, 0);
                    me->SetRegeneratingHealth(false);
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->SetImmuneToAll(true);
                    me->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                    if (pInstance)
                    {
                        pInstance->SetData(DATA_MOUNT_DIED, BossOrder);
                        if (Creature* mount = me->FindNearestCreature( pInstance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE ? VEHICLE_ARGENT_WARHORSE : VEHICLE_ARGENT_BATTLEWORG, 100.0f, true ))
{
                            NewMountGUID = mount->GetGUID();
                            me->GetMotionMaster()->MovePoint(7, *mount);
                            events.RescheduleEvent(EVENT_FIND_NEW_MOUNT, 1s);
                        }
                    }
                }
            }
            else
            {
                if (damage >= me->GetHealth())
                {
                    MountPhase = true;
                    events.Reset();
                    damage = me->GetHealth() - 1;
                    me->SetReactState(REACT_PASSIVE);
                    me->RemoveAllAuras();
                    AddCreatureAddonAuras();
                    me->GetThreatMgr().ClearAllThreat();
                    me->CombatStop(true);
                    me->GetMotionMaster()->Clear();
                    me->SetRegeneratingHealth(false);
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->SetImmuneToAll(true);
                    if (pInstance)
                        pInstance->SetData(DATA_GRAND_CHAMPION_DIED, BossOrder);
                }
            }
        }
References AddCreatureAddonAuras(), Unit::AddUnitMovementFlag(), BossOrder, MotionMaster::Clear(), ThreatMgr::ClearAllThreat(), Unit::CombatStop(), DATA_GRAND_CHAMPION_DIED, DATA_MOUNT_DIED, DATA_TEAMID_IN_INSTANCE, EVENT_FIND_NEW_MOUNT, WorldObject::FindNearestCreature(), ZoneScript::GetData(), Unit::GetHealth(), Unit::GetMotionMaster(), Unit::GetThreatMgr(), Object::GetUInt32Value(), ScriptedAI::me, MountPhase, MOVEMENTFLAG_WALKING, MotionMaster::MovePoint(), NewMountGUID, pInstance, REACT_PASSIVE, Unit::RemoveAllAuras(), ZoneScript::SetData(), Unit::SetImmuneToAll(), Creature::SetReactState(), Creature::SetRegeneratingHealth(), Unit::SetUInt32Value(), Unit::SetUnitFlag(), Unit::StopMoving(), TEAM_HORDE, UNIT_FIELD_MOUNTDISPLAYID, UNIT_FLAG_NON_ATTACKABLE, VEHICLE_ARGENT_BATTLEWORG, and VEHICLE_ARGENT_WARHORSE.
DoAction()
void boss_grand_champion::boss_grand_championAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == 1)
            {
                MountPhase = false;
                NewMountGUID.Clear();
                me->SetHealth(me->GetMaxHealth());
                me->SetRegeneratingHealth(true);
                me->RemoveUnitFlag(UNIT_FLAG_PACIFIED);
                me->SetSpeed(MOVE_RUN, 1.0f, false);
                me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->SetImmuneToAll(true);
                me->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                me->RemoveAllAuras();
                AddCreatureAddonAuras();
                events.Reset();
            }
            else if (param == 2)
                ScheduleAbilitiesEvents();
        }
References AddCreatureAddonAuras(), ObjectGuid::Clear(), Unit::GetMaxHealth(), ScriptedAI::me, MountPhase, MOVE_RUN, MOVEMENTFLAG_WALKING, NewMountGUID, Unit::RemoveAllAuras(), Unit::RemoveUnitFlag(), Unit::RemoveUnitMovementFlag(), ScheduleAbilitiesEvents(), Unit::SetHealth(), Unit::SetImmuneToAll(), Creature::SetRegeneratingHealth(), Unit::SetSpeed(), Unit::SetUnitFlag(), UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_PACIFIED.
Referenced by Reset().
EnterEvadeMode()
void boss_grand_champion::boss_grand_championAI::EnterEvadeMode (EvadeReason) inline override virtual
Reimplemented from npc_escortAI.
{}
JustEngagedWith()
void boss_grand_champion::boss_grand_championAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            if (pInstance && pInstance->GetData(DATA_INSTANCE_PROGRESS) == INSTANCE_PROGRESS_CHAMPIONS_UNMOUNTED )
                me->CallForHelp(100.0f);
        }
References Creature::CallForHelp(), DATA_INSTANCE_PROGRESS, ZoneScript::GetData(), INSTANCE_PROGRESS_CHAMPIONS_UNMOUNTED, ScriptedAI::me, and pInstance.
MovementInform()
void boss_grand_champion::boss_grand_championAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from npc_escortAI.
        {
            if (id < 4)
                npc_escortAI::MovementInform(type, id);
            if (type == POINT_MOTION_TYPE)
            {
                if (id == 5)
                    me->SetFacingTo(3 * M_PI / 2);
                else if (id == 7) // reached new mount!
                {
                    if (NewMountGUID)
                        if (Creature* mount = ObjectAccessor::GetCreature(*me, NewMountGUID))
{
                            mount->DespawnOrUnsummon();
                            me->SetUInt32Value(UNIT_FIELD_MOUNTDISPLAYID, mount->GetDisplayId());
                            me->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                            me->SetHealth(50000);
                            me->CastSpell(me, SPELL_BOSS_DEFEND_PERIODIC, true);
                            me->SetRegeneratingHealth(true);
                            events.Reset();
                            events.ScheduleEvent(EVENT_MOUNT_CHARGE, 2500ms, 4000ms);
                            events.ScheduleEvent(EVENT_SHIELD_BREAKER, 5s, 8s);
                            events.ScheduleEvent(EVENT_THRUST, 3s, 5s);
                            me->SetReactState(REACT_AGGRESSIVE);
                            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            me->SetImmuneToAll(false);
                            if (Unit* target = me->SelectNearestTarget(200.0f))
                                AttackStart(target);
                            DoZoneInCombat();
                            me->CastSpell(me, SPELL_TRAMPLE_AURA, true);
                            if (pInstance)
                                pInstance->SetData(DATA_REACHED_NEW_MOUNT, 0);
                            NewMountGUID.Clear();
                        }
                }
                else if (id == 9)
                    me->DespawnOrUnsummon();
            }
        }
References npc_escortAI::AttackStart(), Unit::CastSpell(), ObjectGuid::Clear(), DATA_REACHED_NEW_MOUNT, Creature::DespawnOrUnsummon(), CreatureAI::DoZoneInCombat(), EVENT_MOUNT_CHARGE, EVENT_SHIELD_BREAKER, EVENT_THRUST, ObjectAccessor::GetCreature(), ScriptedAI::me, MOVEMENTFLAG_WALKING, npc_escortAI::MovementInform(), NewMountGUID, pInstance, POINT_MOTION_TYPE, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Unit::RemoveUnitMovementFlag(), Creature::SelectNearestTarget(), ZoneScript::SetData(), Unit::SetFacingTo(), Unit::SetHealth(), Unit::SetImmuneToAll(), Creature::SetReactState(), Creature::SetRegeneratingHealth(), Unit::SetUInt32Value(), SPELL_BOSS_DEFEND_PERIODIC, SPELL_TRAMPLE_AURA, UNIT_FIELD_MOUNTDISPLAYID, and UNIT_FLAG_NON_ATTACKABLE.
Reset()
void boss_grand_champion::boss_grand_championAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            if (pInstance && pInstance->GetData(DATA_INSTANCE_PROGRESS) == INSTANCE_PROGRESS_CHAMPIONS_UNMOUNTED )
            {
                DoAction(1);
                DoAction(2);
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->SetImmuneToAll(false);
                me->SetUInt32Value(UNIT_FIELD_MOUNTDISPLAYID, 0);
                me->SetReactState(REACT_AGGRESSIVE);
            }
        }
References DATA_INSTANCE_PROGRESS, DoAction(), ZoneScript::GetData(), INSTANCE_PROGRESS_CHAMPIONS_UNMOUNTED, ScriptedAI::me, pInstance, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Unit::SetImmuneToAll(), Creature::SetReactState(), Unit::SetUInt32Value(), UNIT_FIELD_MOUNTDISPLAYID, and UNIT_FLAG_NON_ATTACKABLE.
ScheduleAbilitiesEvents()
void boss_grand_champion::boss_grand_championAI::ScheduleAbilitiesEvents () inline
        {
            me->m_spellImmune[IMMUNITY_MECHANIC].clear();
            events.Reset();
            switch (me->GetEntry())
            {
                case NPC_AMBROSE: // Ambrose Boltspark
                case NPC_ERESSEA: // Eressea Dawnsinger
                    events.RescheduleEvent(EVEMT_MAGE_SPELL_FIREBALL, 5s);
                    events.RescheduleEvent(EVEMT_MAGE_SPELL_BLAST_WAVE, 12s);
                    events.RescheduleEvent(EVEMT_MAGE_SPELL_HASTE, 22s);
                    events.RescheduleEvent(EVEMT_MAGE_SPELL_POLYMORPH, 8s);
                    break;
                case NPC_COLOSOS: // Colosos
                case NPC_RUNOK: // Runok Wildmane
                    events.RescheduleEvent(EVENT_SHAMAN_SPELL_CHAIN_LIGHTNING, 16s);
                    events.RescheduleEvent(EVENT_SHAMAN_SPELL_EARTH_SHIELD, 30s, 35s);
                    events.RescheduleEvent(EVENT_SHAMAN_SPELL_HEALING_WAVE, 12s);
                    events.RescheduleEvent(EVENT_SHAMAN_SPELL_HEX_OF_MENDING, 20s, 25s);
                    break;
                case NPC_JAELYNE: // Jaelyne Evensong
                case NPC_ZULTORE: // Zul'tore
                    events.RescheduleEvent(EVENT_HUNTER_SPELL_LIGHTNING_ARROWS, 7s);
                    events.RescheduleEvent(EVENT_HUNTER_SPELL_MULTI_SHOT, 12s);
                    break;
                case NPC_LANA: // Lana Stouthammer
                case NPC_VISCERI: // Deathstalker Visceri
                    events.RescheduleEvent(EVENT_ROGUE_SPELL_EVISCERATE, 8s);
                    events.RescheduleEvent(EVENT_ROGUE_SPELL_FAN_OF_KNIVES, 14s);
                    events.RescheduleEvent(EVENT_ROGUE_SPELL_POISON_BOTTLE, 19s);
                    break;
                case NPC_JACOB: // Marshal Jacob Alerius
                case NPC_MOKRA: // Mokra the Skullcrusher
                    events.RescheduleEvent(EVENT_WARRIOR_SPELL_MORTAL_STRIKE, 8s, 12s);
                    events.RescheduleEvent(EVENT_WARRIOR_SPELL_BLADESTORM, 15s, 20s);
                    events.RescheduleEvent(EVENT_WARRIOR_SPELL_INTERCEPT, 7s);
                    break;
                default:
                    break;
            }
        }
References EVEMT_MAGE_SPELL_BLAST_WAVE, EVEMT_MAGE_SPELL_FIREBALL, EVEMT_MAGE_SPELL_HASTE, EVEMT_MAGE_SPELL_POLYMORPH, EVENT_HUNTER_SPELL_LIGHTNING_ARROWS, EVENT_HUNTER_SPELL_MULTI_SHOT, EVENT_ROGUE_SPELL_EVISCERATE, EVENT_ROGUE_SPELL_FAN_OF_KNIVES, EVENT_ROGUE_SPELL_POISON_BOTTLE, EVENT_SHAMAN_SPELL_CHAIN_LIGHTNING, EVENT_SHAMAN_SPELL_EARTH_SHIELD, EVENT_SHAMAN_SPELL_HEALING_WAVE, EVENT_SHAMAN_SPELL_HEX_OF_MENDING, EVENT_WARRIOR_SPELL_BLADESTORM, EVENT_WARRIOR_SPELL_INTERCEPT, EVENT_WARRIOR_SPELL_MORTAL_STRIKE, Object::GetEntry(), IMMUNITY_MECHANIC, Unit::m_spellImmune, ScriptedAI::me, NPC_AMBROSE, NPC_COLOSOS, NPC_ERESSEA, NPC_JACOB, NPC_JAELYNE, NPC_LANA, NPC_MOKRA, NPC_RUNOK, NPC_VISCERI, and NPC_ZULTORE.
Referenced by DoAction().
SetData()
void boss_grand_champion::boss_grand_championAI::SetData (uint32 uiType, uint32 uiData) inline override virtual
Reimplemented from UnitAI.
        {
            BossOrder = uiType;
            if (uiData > 1)
                return;
            switch (BossOrder)
            {
                case 0:
                    if (uiData == 0) // 1 == short version
                    {
                        AddWaypoint(0, 747.36f, 634.07f, 411.572f);
                        AddWaypoint(1, 780.43f, 607.15f, 411.82f);
                    }
                    AddWaypoint(2, 785.99f, 599.41f, 411.92f);
                    AddWaypoint(3, 778.44f, 601.64f, 411.79f);
                    break;
                case 1:
                    if (uiData == 0) // 1 == short version
                    {
                        AddWaypoint(0, 747.35f, 634.07f, 411.57f);
                        AddWaypoint(1, 768.72f, 581.01f, 411.92f);
                    }
                    AddWaypoint(2, 763.55f, 590.52f, 411.71f);
                    break;
                case 2:
                    if (uiData == 0) // 1 == short version
                    {
                        AddWaypoint(0, 747.35f, 634.07f, 411.57f);
                        AddWaypoint(1, 784.02f, 645.33f, 412.39f);
                    }
                    AddWaypoint(2, 775.67f, 641.91f, 411.91f);
                    break;
                default:
                    return;
            }
            Start(false, true);
        }
References npc_escortAI::AddWaypoint(), BossOrder, and npc_escortAI::Start().
SpellHit()
void boss_grand_champion::boss_grand_championAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spell->Id == SPELL_TRAMPLE_STUN)
                Talk(SAY_TRAMPLED, me);
        }
References SpellInfo::Id, ScriptedAI::me, SAY_TRAMPLED, and SPELL_TRAMPLE_STUN.
UpdateAI()
void boss_grand_champion::boss_grand_championAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from npc_escortAI.
        {
            npc_escortAI::UpdateAI(diff);
            if (!UpdateVictim() && !NewMountGUID )
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING) || ((me->GetEntry() == NPC_JACOB || me->GetEntry() == NPC_MOKRA) && me->HasAura(SPELL_BLADESTORM)))
                return;
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_FIND_NEW_MOUNT:
                    {
                        if (me->HasAura(SPELL_TRAMPLE_STUN))
{
                            events.Repeat(200ms);
                            break;
                        }
                        // hackfix, trample won't hit grand champions because of UNIT_FLAG_NON_ATTACKABLE
                        if (pInstance)
{
                            bool trample = false;
                            Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                            for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                                if (Player* plr = itr->GetSource())
                                    if (me->GetExactDist(plr) <= 5.0f )
                                        if (Vehicle* v = plr->GetVehicle())
                                            if (Unit* c = v->GetBase())
                                                if (c->IsCreature() && c->ToCreature()->GetEntry() == (pInstance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE ? VEHICLE_ARGENT_BATTLEWORG : VEHICLE_ARGENT_WARHORSE))
{
                                                    me->GetMotionMaster()->MovementExpired();
                                                    me->GetMotionMaster()->MoveIdle();
                                                    me->StopMoving();
                                                    me->CastSpell(me, SPELL_TRAMPLE_STUN, false);
                                                    trample = true;
                                                    break;
                                                }
                            if (trample)
{
                                events.Repeat(15s);
                                break;
                            }
                        }
                        if (Creature* mount = ObjectAccessor::GetCreature(*me, NewMountGUID))
                            if (mount->IsAlive())
{
                                if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() != POINT_MOTION_TYPE )
                                    me->GetMotionMaster()->MovePoint(7, *mount);
                                events.Repeat(200ms);
                                break;
                            }
                        if (Creature* mount = me->FindNearestCreature( pInstance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE ? VEHICLE_ARGENT_WARHORSE : VEHICLE_ARGENT_BATTLEWORG, 100.0f, true ))
{
                            me->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                            NewMountGUID = mount->GetGUID();
                            me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            me->SetImmuneToAll(true);
                            me->GetMotionMaster()->MovePoint(7, *mount);
                            events.Repeat(200ms);
                            break;
                        }
                    }
                    break;
                case EVENT_MOUNT_CHARGE:
                    {
                        GuidVector LIST;
                        Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                        for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                            if (Player* plr = itr->GetSource())
{
                                if (me->GetExactDist(plr) < 8.0f || me->GetExactDist(plr) > 25.0f || plr->isDead())
                                    continue;
                                if (!plr->GetVehicle())
                                    LIST.push_back(plr->GetGUID());
                                else if (Vehicle* v = plr->GetVehicle())
{
                                    if (Unit* mount = v->GetBase())
                                        LIST.push_back(mount->GetGUID());
                                }
                            }
                        if (!LIST.empty())
{
                            uint8 rnd = LIST.size() > 1 ? urand(0, LIST.size() - 1) : 0;
                            if (Unit* target = ObjectAccessor::GetUnit(*me, LIST.at(rnd)))
{
                                me->GetThreatMgr().ResetAllThreat();
                                me->AddThreat(target, 10000.0f);
                                AttackStart(target);
                                me->CastSpell(target, SPELL_MINIONS_CHARGE, false);
                            }
                        }
                        events.Repeat(4500ms, 6000ms);
                    }
                    break;
                case EVENT_SHIELD_BREAKER:
                    {
                        GuidVector LIST;
                        Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                        for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                            if (Player* plr = itr->GetSource())
{
                                if (me->GetExactDist(plr) < 10.0f || me->GetExactDist(plr) > 30.0f )
                                    continue;
                                if (Vehicle* v = plr->GetVehicle())
                                    if (Unit* mount = v->GetBase())
                                        LIST.push_back(mount->GetGUID());
                            }
                        if (!LIST.empty())
{
                            uint8 rnd = LIST.size() > 1 ? urand(0, LIST.size() - 1) : 0;
                            if (Unit* target = ObjectAccessor::GetCreature(*me, LIST.at(rnd)))
                                me->CastSpell(target, SPELL_NPC_SHIELD_BREAKER, false);
                        }
                        events.Repeat(6s, 8s);
                    }
                    break;
                case EVENT_THRUST:
                    if (Unit* victim = me->GetVictim())
                        if (me->GetExactDist(victim) <= 6.0f )
                            me->CastSpell(victim, SPELL_PLAYER_VEHICLE_THRUST, false);
                    events.Repeat(3s, 5s);
                    break;
                /******************* MAGE *******************/
                case EVEMT_MAGE_SPELL_FIREBALL:
                    if (me->GetVictim())
                        me->CastSpell(me->GetVictim(), SPELL_FIREBALL, false);
                    events.Repeat(5s);
                    break;
                case EVEMT_MAGE_SPELL_BLAST_WAVE:
                    me->CastSpell((Unit*)nullptr, SPELL_BLAST_WAVE, false);
                    events.Repeat(13s);
                    break;
                case EVEMT_MAGE_SPELL_HASTE:
                    me->CastSpell(me, SPELL_HASTE, false);
                    events.Repeat(22s);
                    break;
                case EVEMT_MAGE_SPELL_POLYMORPH:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 30.0f, true))
                        me->CastSpell(target, SPELL_POLYMORPH, false);
                    events.Repeat(8s);
                    break;
                /***************** MAGE END *****************/
                /****************** SHAMAN ******************/
                case EVENT_SHAMAN_SPELL_CHAIN_LIGHTNING:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 30.0f, true))
                        me->CastSpell(target, SPELL_CHAIN_LIGHTNING, false);
                    events.Repeat(16s);
                    break;
                case EVENT_SHAMAN_SPELL_EARTH_SHIELD:
                    me->CastSpell(me, SPELL_EARTH_SHIELD, false);
                    events.Repeat(30s, 35s);
                    break;
                case EVENT_SHAMAN_SPELL_HEALING_WAVE:
                    {
                        Unit* target = nullptr;
                        if (urand(0, 1))
{
                            target = DoSelectLowestHpFriendly(40.0f);
                            if (!target)
                                target = me;
                        }
                        else
                            target = me;
                        me->CastSpell(target, SPELL_HEALING_WAVE, false);
                        events.Repeat(22s);
                    }
                    break;
                case EVENT_SHAMAN_SPELL_HEX_OF_MENDING:
                    if (me->GetVictim())
                        me->CastSpell(me->GetVictim(), SPELL_HEX_OF_MENDING, false);
                    events.Repeat(20s, 25s);
                    break;
                /**************** SHAMAN END ****************/
                /****************** HUNTER ******************/
                case EVENT_HUNTER_SPELL_DISENGAGE:
                    break;
                case EVENT_HUNTER_SPELL_LIGHTNING_ARROWS:
                    me->CastSpell((Unit*)nullptr, SPELL_LIGHTNING_ARROWS, false);
                    events.Repeat(20s, 25s);
                    break;
                case EVENT_HUNTER_SPELL_MULTI_SHOT:
                    {
                        if (!UnitTargetGUID)
{
                            if (Unit* target = SelectTarget(SelectTargetMethod::MinDistance, 0, 30.0f, true))
{
                                me->CastSpell(target, SPELL_SHOOT, false);
                                UnitTargetGUID = target->GetGUID();
                            }
                            events.Repeat(2s);
                            break;
                        }
                        else
{
                            Unit* target = ObjectAccessor::GetUnit(*me, UnitTargetGUID);
                            if (target && me->IsInRange(target, 5.0f, 30.0f, false))
                                me->CastSpell(target, SPELL_MULTI_SHOT, false);
                            else
{
                                Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                                for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
{
                                    Player* player = itr->GetSource();
                                    if (player && me->IsInRange(player, 5.0f, 30.0f, false))
{
                                        me->CastSpell(player, SPELL_MULTI_SHOT, false);
                                        break;
                                    }
                                }
                            }
                            UnitTargetGUID.Clear();
                        }
                        events.Repeat(15s, 20s);
                    }
                    break;
                /**************** HUNTER END ****************/
                /****************** ROGUE *******************/
                case EVENT_ROGUE_SPELL_EVISCERATE:
                    if (me->GetVictim())
                        me->CastSpell(me->GetVictim(), SPELL_EVISCERATE, false);
                    events.Repeat(8s);
                    break;
                case EVENT_ROGUE_SPELL_FAN_OF_KNIVES:
                    me->CastSpell((Unit*)nullptr, SPELL_FAN_OF_KNIVES, false);
                    events.Repeat(14s);
                    break;
                case EVENT_ROGUE_SPELL_POISON_BOTTLE:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 30.0f, true))
                        me->CastSpell(target, SPELL_POISON_BOTTLE, false);
                    events.Repeat(19s);
                    break;
                /**************** ROGUE END *****************/
                /***************** WARRIOR ******************/
                case EVENT_WARRIOR_SPELL_MORTAL_STRIKE:
                    if (me->GetVictim())
                        me->CastSpell(me->GetVictim(), SPELL_MORTAL_STRIKE, false);
                    events.Repeat(8s, 12s);
                    break;
                case EVENT_WARRIOR_SPELL_BLADESTORM:
                    if (me->GetVictim())
                        me->CastSpell(me->GetVictim(), SPELL_BLADESTORM, false);
                    events.Repeat(15s, 20s);
                    break;
                case EVENT_WARRIOR_SPELL_INTERCEPT:
                    {
                        Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                        for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
{
                            Player* player = itr->GetSource();
                            if (player && me->IsInRange(player, 8.0f, 25.0f, false))
{
                                DoResetThreatList();
                                me->AddThreat(player, 5.0f);
                                me->CastSpell(player, SPELL_INTERCEPT, false);
                                break;
                            }
                        }
                        events.Repeat(7s);
                    }
                    break;
                case EVENT_WARRIOR_SPELL_ROLLING_THROW:
                    break;
                    /*************** WARRIOR END ****************/
            }
            DoMeleeAttackIfReady();
        }
References Unit::AddThreat(), Unit::AddUnitMovementFlag(), npc_escortAI::AttackStart(), MapRefMgr::begin(), Unit::CastSpell(), ObjectGuid::Clear(), DATA_TEAMID_IN_INSTANCE, UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreatList(), ScriptedAI::DoSelectLowestHpFriendly(), MapRefMgr::end(), EVEMT_MAGE_SPELL_BLAST_WAVE, EVEMT_MAGE_SPELL_FIREBALL, EVEMT_MAGE_SPELL_HASTE, EVEMT_MAGE_SPELL_POLYMORPH, EVENT_FIND_NEW_MOUNT, EVENT_HUNTER_SPELL_DISENGAGE, EVENT_HUNTER_SPELL_LIGHTNING_ARROWS, EVENT_HUNTER_SPELL_MULTI_SHOT, EVENT_MOUNT_CHARGE, EVENT_ROGUE_SPELL_EVISCERATE, EVENT_ROGUE_SPELL_FAN_OF_KNIVES, EVENT_ROGUE_SPELL_POISON_BOTTLE, EVENT_SHAMAN_SPELL_CHAIN_LIGHTNING, EVENT_SHAMAN_SPELL_EARTH_SHIELD, EVENT_SHAMAN_SPELL_HEALING_WAVE, EVENT_SHAMAN_SPELL_HEX_OF_MENDING, EVENT_SHIELD_BREAKER, EVENT_THRUST, EVENT_WARRIOR_SPELL_BLADESTORM, EVENT_WARRIOR_SPELL_INTERCEPT, EVENT_WARRIOR_SPELL_MORTAL_STRIKE, EVENT_WARRIOR_SPELL_ROLLING_THROW, WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), MotionMaster::GetCurrentMovementGeneratorType(), ZoneScript::GetData(), Object::GetEntry(), Position::GetExactDist(), WorldObject::GetMap(), Unit::GetMotionMaster(), Map::GetPlayers(), Unit::GetThreatMgr(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::HasAura(), Unit::HasUnitState(), WorldObject::IsInRange(), ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovementExpired(), MOVEMENTFLAG_WALKING, MotionMaster::MovePoint(), NewMountGUID, NPC_JACOB, NPC_MOKRA, pInstance, POINT_MOTION_TYPE, ThreatMgr::ResetAllThreat(), UnitAI::SelectTarget(), Unit::SetImmuneToAll(), Unit::SetUnitFlag(), SPELL_BLADESTORM, SPELL_BLAST_WAVE, SPELL_CHAIN_LIGHTNING, SPELL_EARTH_SHIELD, SPELL_EVISCERATE, SPELL_FAN_OF_KNIVES, SPELL_FIREBALL, SPELL_HASTE, SPELL_HEALING_WAVE, SPELL_HEX_OF_MENDING, SPELL_INTERCEPT, SPELL_LIGHTNING_ARROWS, SPELL_MINIONS_CHARGE, SPELL_MORTAL_STRIKE, SPELL_MULTI_SHOT, SPELL_NPC_SHIELD_BREAKER, SPELL_PLAYER_VEHICLE_THRUST, SPELL_POISON_BOTTLE, SPELL_POLYMORPH, SPELL_SHOOT, SPELL_TRAMPLE_STUN, Unit::StopMoving(), TEAM_HORDE, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, UnitTargetGUID, npc_escortAI::UpdateAI(), CreatureAI::UpdateVictim(), urand(), VEHICLE_ARGENT_BATTLEWORG, and VEHICLE_ARGENT_WARHORSE.
WaypointReached()
void boss_grand_champion::boss_grand_championAI::WaypointReached (uint32 i) inline override virtual
Implements npc_escortAI.
        {
            if (!pInstance)
                return;
            if ((i == 2 && (BossOrder == 1 || BossOrder == 2)) || (i == 3 && BossOrder == 0))
                pInstance->SetData(DATA_GRAND_CHAMPION_REACHED_DEST, BossOrder);
        }
References BossOrder, DATA_GRAND_CHAMPION_REACHED_DEST, pInstance, and ZoneScript::SetData().
Member Data Documentation
BossOrder
uint32 boss_grand_champion::boss_grand_championAI::BossOrder
Referenced by boss_grand_championAI(), DamageTaken(), SetData(), and WaypointReached().
events
EventMap boss_grand_champion::boss_grand_championAI::events
MountPhase
bool boss_grand_champion::boss_grand_championAI::MountPhase
Referenced by boss_grand_championAI(), DamageTaken(), and DoAction().
NewMountGUID
ObjectGuid boss_grand_champion::boss_grand_championAI::NewMountGUID
Referenced by boss_grand_championAI(), DamageTaken(), DoAction(), MovementInform(), and UpdateAI().
pInstance
InstanceScript* boss_grand_champion::boss_grand_championAI::pInstance
Referenced by boss_grand_championAI(), DamageTaken(), JustEngagedWith(), MovementInform(), Reset(), UpdateAI(), and WaypointReached().
UnitTargetGUID
ObjectGuid boss_grand_champion::boss_grand_championAI::UnitTargetGUID
Referenced by UpdateAI().