AzerothCore: WorldSessionFilter Class Reference
WorldSessionFilter Class Reference
User to World Communication
#include "WorldSession.h"
Public Member Functions
WorldSessionFilter (WorldSession *pSession)
~WorldSessionFilter () override=default
bool Process (WorldPacket *packet) override
Public Member Functions inherited from PacketFilter
PacketFilter (WorldSession *pSession)
virtual ~PacketFilter ()=default
virtual bool Process (WorldPacket *)
virtual bool ProcessUnsafe () const
Additional Inherited Members
Protected Attributes inherited from PacketFilter
WorldSession *const m_pSession
Detailed Description
Constructor & Destructor Documentation
WorldSessionFilter()
WorldSessionFilter::WorldSessionFilter (WorldSession * pSession) inline explicit
: PacketFilter(pSession) {}
~WorldSessionFilter()
WorldSessionFilter::~WorldSessionFilter () override default
Member Function Documentation
Process()
bool WorldSessionFilter::Process (WorldPacket * packet) override virtual
Reimplemented from PacketFilter.
{
    ClientOpcodeHandler const* opHandle = opcodeTable[static_cast<OpcodeClient>(packet->GetOpcode())];
    //check if packet handler is supposed to be safe
    if (opHandle->ProcessingPlace == PROCESS_INPLACE)
        return true;
    //thread-unsafe packets should be processed in World::UpdateSessions()
    if (opHandle->ProcessingPlace == PROCESS_THREADUNSAFE)
        return true;
    //no player attached? -> our client! ^^
    Player* player = m_pSession->GetPlayer();
    if (!player)
        return true;
    //lets process all packets for non-in-the-world player
    return !player->IsInWorld();
}
References WorldPacket::GetOpcode(), WorldSession::GetPlayer(), Object::IsInWorld(), PacketFilter::m_pSession, opcodeTable, PROCESS_INPLACE, PROCESS_THREADUNSAFE, and ClientOpcodeHandler::ProcessingPlace.