AzerothCore: spell_dk_raise_dead Class Reference
spell_dk_raise_dead Class Reference
Private Member Functions
PrepareSpellScript (spell_dk_raise_dead)
bool Validate (SpellInfo const *) override
bool Load () override
SpellCastResult CheckCast ()
SpellCastResult CheckReagents ()
void CheckTargets (std::list< WorldObject * > &targets)
void CheckTarget (WorldObject *&target)
void ConsumeReagents ()
uint32 GetGhoulSpellId ()
void HandleRaiseDead (SpellEffIndex)
void Register () override
Private Attributes
SpellCastResult _result
bool _corpse
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
CheckCast()
SpellCastResult spell_dk_raise_dead::CheckCast () inline private
process spell target selection before cast starts targets of effect_1 are used to check cast
cleanup spell target map, and fill it again on normal way
_result is set in spell target selection
    {
        GetSpell()->SelectSpellTargets();
        GetSpell()->CleanupTargetList();
        return _result;
    }
References _result, Spell::CleanupTargetList(), SpellScript::GetSpell(), and Spell::SelectSpellTargets().
Referenced by Register().
CheckReagents()
SpellCastResult spell_dk_raise_dead::CheckReagents () inline private
@workaround: there is no access to castresult of other spells, check it manually
    {
        SpellInfo const* reagentSpell = sSpellMgr->GetSpellInfo(SPELL_DK_RAISE_DEAD_USE_REAGENT);
        Player* player = GetCaster()->ToPlayer();
        if (!player->CanNoReagentCast(reagentSpell))
        {
            for (uint32 i = 0; i < MAX_SPELL_REAGENTS; i++)
            {
                if (reagentSpell->Reagent[i] <= 0)
                    continue;
                if (!player->HasItemCount(reagentSpell->Reagent[i], reagentSpell->ReagentCount[i]))
                {
                    Spell::SendCastResult(player, reagentSpell, 0, SPELL_FAILED_REAGENTS);
                    return SPELL_FAILED_DONT_REPORT;
                }
            }
        }
        return SPELL_CAST_OK;
    }
References Player::CanNoReagentCast(), SpellScript::GetCaster(), Player::HasItemCount(), MAX_SPELL_REAGENTS, SpellInfo::Reagent, SpellInfo::ReagentCount, Spell::SendCastResult(), SPELL_CAST_OK, SPELL_DK_RAISE_DEAD_USE_REAGENT, SPELL_FAILED_DONT_REPORT, SPELL_FAILED_REAGENTS, sSpellMgr, and Object::ToPlayer().
Referenced by CheckTargets().
CheckTarget()
void spell_dk_raise_dead::CheckTarget (WorldObject *& target) inline private
    {
        // Don't add caster to target map, if we found a corpse to raise dead
        if (_corpse)
            target = nullptr;
    }
References _corpse.
Referenced by Register().
CheckTargets()
void spell_dk_raise_dead::CheckTargets (std::list< WorldObject * > & targets) inline private
    {
        targets.remove_if(RaiseDeadCheck(GetCaster()->ToPlayer()));
        if (targets.empty())
        {
            if (GetSpell()->getState() == SPELL_STATE_PREPARING)
                _result = CheckReagents();
            return;
        }
        WorldObject* target = Acore::Containers::SelectRandomContainerElement(targets);
        targets.clear();
        targets.push_back(target);
        _corpse = true;
    }
References _corpse, _result, CheckReagents(), SpellScript::GetCaster(), SpellScript::GetSpell(), Acore::Containers::SelectRandomContainerElement(), and SPELL_STATE_PREPARING.
Referenced by Register().
ConsumeReagents()
void spell_dk_raise_dead::ConsumeReagents () inline private
    {
        // No corpse found, take reagents
        if (!_corpse)
            GetCaster()->CastSpell(GetCaster(), SPELL_DK_RAISE_DEAD_USE_REAGENT, TriggerCastFlags(TRIGGERED_FULL_MASK & ~TRIGGERED_IGNORE_POWER_AND_REAGENT_COST));
    }
References _corpse, Unit::CastSpell(), SpellScript::GetCaster(), SPELL_DK_RAISE_DEAD_USE_REAGENT, TRIGGERED_FULL_MASK, and TRIGGERED_IGNORE_POWER_AND_REAGENT_COST.
Referenced by Register().
GetGhoulSpellId()
uint32 spell_dk_raise_dead::GetGhoulSpellId () inline private
    {
        // Do we have talent Master of Ghouls?
        if (GetCaster()->HasAura(SPELL_DK_MASTER_OF_GHOULS))
            // summon as pet
            return GetSpellInfo()->Effects[EFFECT_2].CalcValue();
        // or guardian
        return GetSpellInfo()->Effects[EFFECT_1].CalcValue();
    }
References EFFECT_1, EFFECT_2, SpellInfo::Effects, SpellScript::GetCaster(), SpellScript::GetSpellInfo(), and SPELL_DK_MASTER_OF_GHOULS.
Referenced by HandleRaiseDead().
HandleRaiseDead()
void spell_dk_raise_dead::HandleRaiseDead (SpellEffIndex) inline private
    {
        SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(GetGhoulSpellId());
        SpellCastTargets targets;
        targets.SetDst(*GetHitUnit());
        GetCaster()->CastSpell(targets, spellInfo, nullptr, TRIGGERED_FULL_MASK, nullptr, nullptr, GetCaster()->GetGUID());
        GetCaster()->ToPlayer()->RemoveSpellCooldown(GetSpellInfo()->Id, true);
    }
References Unit::CastSpell(), SpellScript::GetCaster(), GetGhoulSpellId(), SpellScript::GetHitUnit(), SpellScript::GetSpellInfo(), Player::RemoveSpellCooldown(), SpellCastTargets::SetDst(), sSpellMgr, Object::ToPlayer(), and TRIGGERED_FULL_MASK.
Referenced by Register().
Load()
bool spell_dk_raise_dead::Load () inline override private virtual
Reimplemented from _SpellScript.
    {
        _result = SPELL_CAST_OK;
        _corpse = false;
        return GetCaster()->IsPlayer();
    }
References _corpse, _result, SpellScript::GetCaster(), Object::IsPlayer(), and SPELL_CAST_OK.
PrepareSpellScript()
spell_dk_raise_dead::PrepareSpellScript (spell_dk_raise_dead) private
Register()
void spell_dk_raise_dead::Register () inline override private virtual
Implements _SpellScript.
    {
        OnCheckCast += SpellCheckCastFn(spell_dk_raise_dead::CheckCast);
        OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_dk_raise_dead::CheckTargets, EFFECT_1, TARGET_UNIT_DEST_AREA_ENTRY);
        OnObjectTargetSelect += SpellObjectTargetSelectFn(spell_dk_raise_dead::CheckTarget, EFFECT_2, TARGET_UNIT_CASTER);
        OnCast += SpellCastFn(spell_dk_raise_dead::ConsumeReagents);
        OnEffectHitTarget += SpellEffectFn(spell_dk_raise_dead::HandleRaiseDead, EFFECT_1, SPELL_EFFECT_SCRIPT_EFFECT);
        OnEffectHitTarget += SpellEffectFn(spell_dk_raise_dead::HandleRaiseDead, EFFECT_2, SPELL_EFFECT_DUMMY);
    }
References CheckCast(), CheckTarget(), CheckTargets(), ConsumeReagents(), EFFECT_1, EFFECT_2, HandleRaiseDead(), SpellScript::OnCast, SpellScript::OnCheckCast, SpellScript::OnEffectHitTarget, SpellScript::OnObjectAreaTargetSelect, SpellScript::OnObjectTargetSelect, SPELL_EFFECT_DUMMY, SPELL_EFFECT_SCRIPT_EFFECT, SpellCastFn, SpellCheckCastFn, SpellEffectFn, SpellObjectAreaTargetSelectFn, SpellObjectTargetSelectFn, TARGET_UNIT_CASTER, and TARGET_UNIT_DEST_AREA_ENTRY.
Validate()
bool spell_dk_raise_dead::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo(
            {
                SPELL_DK_RAISE_DEAD_USE_REAGENT,
                SPELL_DK_MASTER_OF_GHOULS
            });
    }
References SPELL_DK_MASTER_OF_GHOULS, SPELL_DK_RAISE_DEAD_USE_REAGENT, and _SpellScript::ValidateSpellInfo().
Member Data Documentation
_corpse
bool spell_dk_raise_dead::_corpse private
Referenced by CheckTarget(), CheckTargets(), ConsumeReagents(), and Load().
_result
SpellCastResult spell_dk_raise_dead::_result private
Referenced by CheckCast(), CheckTargets(), and Load().