AzeorthCore: guild_commandscript Class Reference
guild_commandscript Class Reference
Public Member Functions
guild_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleGuildCreateCommand (ChatHandler *handler, char const *args)
GM command level 3 - Create a guild.
static bool HandleGuildDeleteCommand (ChatHandler *handler, char const *args)
static bool HandleGuildInviteCommand (ChatHandler *handler, char const *args)
static bool HandleGuildUninviteCommand (ChatHandler *handler, char const *args)
static bool HandleGuildRankCommand (ChatHandler *handler, Optional< PlayerIdentifier > player, uint8 rank)
static bool HandleGuildRenameCommand (ChatHandler *handler, char const *_args)
static bool HandleGuildInfoCommand (ChatHandler *handler, char const *args)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
guild_commandscript()
guild_commandscript::guild_commandscript () inline
: CommandScript("guild_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable guild_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable guildCommandTable =
        {
            { "create",         SEC_GAMEMASTER,     true,  &HandleGuildCreateCommand,           "" },
            { "delete",         SEC_GAMEMASTER,     true,  &HandleGuildDeleteCommand,           "" },
            { "invite",         SEC_GAMEMASTER,     true,  &HandleGuildInviteCommand,           "" },
            { "uninvite",       SEC_GAMEMASTER,     true,  &HandleGuildUninviteCommand,         "" },
            { "rank",           SEC_GAMEMASTER,     true,  &HandleGuildRankCommand,             "" },
            { "rename",         SEC_GAMEMASTER,     true,  &HandleGuildRenameCommand,           "" },
            { "info",           SEC_GAMEMASTER,     true,  &HandleGuildInfoCommand,             "" }
        };
        static ChatCommandTable commandTable =
        {
            { "guild",          SEC_GAMEMASTER,  true, nullptr,                                 "", guildCommandTable }
        };
        return commandTable;
    }
References HandleGuildCreateCommand(), HandleGuildDeleteCommand(), HandleGuildInfoCommand(), HandleGuildInviteCommand(), HandleGuildRankCommand(), HandleGuildRenameCommand(), HandleGuildUninviteCommand(), and SEC_GAMEMASTER.
HandleGuildCreateCommand()
static bool guild_commandscript::HandleGuildCreateCommand (ChatHandler * handler, char const * args) inline static
GM command level 3 - Create a guild.
This command allows a GM (level 3) to create a guild.
The "args" parameter contains the name of the guild leader and then the name of the guild.
    {
        if (!*args)
            return false;
        // if not guild name only (in "") then player name
        Player* target;
        if (!handler->extractPlayerTarget(*args != '"' ? (char*)args : nullptr, &target))
            return false;
        char* tailStr = *args != '"' ? strtok(nullptr, "") : (char*)args;
        if (!tailStr)
            return false;
        char* guildStr = handler->extractQuotedArg(tailStr);
        if (!guildStr)
            return false;
        std::string guildName = guildStr;
        if (target->GetGuildId())
        {
            handler->SendSysMessage(LANG_PLAYER_IN_GUILD);
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (sGuildMgr->GetGuildByName(guildName))
        {
            handler->SendSysMessage(LANG_GUILD_RENAME_ALREADY_EXISTS);
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (sObjectMgr->IsReservedName(guildName) || !sObjectMgr->IsValidCharterName(guildName))
        {
            handler->SendSysMessage(LANG_BAD_VALUE);
            handler->SetSentErrorMessage(true);
            return false;
        }
        Guild* guild = new Guild;
        if (!guild->Create(target, guildName))
        {
            delete guild;
            handler->SendSysMessage(LANG_GUILD_NOT_CREATED);
            handler->SetSentErrorMessage(true);
            return false;
        }
        sGuildMgr->AddGuild(guild);
        return true;
    }
References Guild::Create(), ChatHandler::extractPlayerTarget(), ChatHandler::extractQuotedArg(), Player::GetGuildId(), LANG_BAD_VALUE, LANG_GUILD_NOT_CREATED, LANG_GUILD_RENAME_ALREADY_EXISTS, LANG_PLAYER_IN_GUILD, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), sGuildMgr, and sObjectMgr.
Referenced by GetCommands().
HandleGuildDeleteCommand()
static bool guild_commandscript::HandleGuildDeleteCommand (ChatHandler * handler, char const * args) inline static
    {
        if (!*args)
            return false;
        char* guildStr = handler->extractQuotedArg((char*)args);
        if (!guildStr)
            return false;
        std::string guildName = guildStr;
        Guild* targetGuild = sGuildMgr->GetGuildByName(guildName);
        if (!targetGuild)
            return false;
        targetGuild->Disband();
        delete targetGuild;
        return true;
    }
References Guild::Disband(), ChatHandler::extractQuotedArg(), and sGuildMgr.
Referenced by GetCommands().
HandleGuildInfoCommand()
static bool guild_commandscript::HandleGuildInfoCommand (ChatHandler * handler, char const * args) inline static
    {
        Guild* guild = nullptr;
        if (args && args[0] != '\0')
        {
            if (isNumeric(args))
                guild = sGuildMgr->GetGuildById(strtoull(args, nullptr, 10));
            else
                guild = sGuildMgr->GetGuildByName(args);
        }
        else if (Player* target = handler->getSelectedPlayerOrSelf())
            guild = target->GetGuild();
        if (!guild)
            return false;
        // Display Guild Information
        handler->PSendSysMessage(LANG_GUILD_INFO_NAME, guild->GetName().c_str(), guild->GetId()); // Guild Id + Name
        std::string guildMasterName;
        if (sCharacterCache->GetCharacterNameByGuid(guild->GetLeaderGUID(), guildMasterName))
        {
            handler->PSendSysMessage(LANG_GUILD_INFO_GUILD_MASTER, guildMasterName.c_str(), guild->GetLeaderGUID().GetCounter()); // Guild Master
        }
        handler->PSendSysMessage(LANG_GUILD_INFO_CREATION_DATE, Acore::Time::TimeToHumanReadable(Seconds(guild->GetCreatedDate())).c_str()); // Creation Date
        handler->PSendSysMessage(LANG_GUILD_INFO_MEMBER_COUNT, guild->GetMemberCount()); // Number of Members
        handler->PSendSysMessage(LANG_GUILD_INFO_BANK_GOLD, guild->GetTotalBankMoney() / 100 / 100); // Bank Gold (in gold coins)
        handler->PSendSysMessage(LANG_GUILD_INFO_MOTD, guild->GetMOTD().c_str()); // Message of the day
        handler->PSendSysMessage(LANG_GUILD_INFO_EXTRA_INFO, guild->GetInfo().c_str()); // Extra Information
        return true;
    }
References ObjectGuid::GetCounter(), Guild::GetCreatedDate(), Guild::GetId(), Guild::GetInfo(), Guild::GetLeaderGUID(), Guild::GetMemberCount(), Guild::GetMOTD(), Guild::GetName(), ChatHandler::getSelectedPlayerOrSelf(), Guild::GetTotalBankMoney(), isNumeric(), LANG_GUILD_INFO_BANK_GOLD, LANG_GUILD_INFO_CREATION_DATE, LANG_GUILD_INFO_EXTRA_INFO, LANG_GUILD_INFO_GUILD_MASTER, LANG_GUILD_INFO_MEMBER_COUNT, LANG_GUILD_INFO_MOTD, LANG_GUILD_INFO_NAME, ChatHandler::PSendSysMessage(), sCharacterCache, sGuildMgr, and Acore::Time::TimeToHumanReadable().
Referenced by GetCommands().
HandleGuildInviteCommand()
static bool guild_commandscript::HandleGuildInviteCommand (ChatHandler * handler, char const * args) inline static
    {
        if (!*args)
            return false;
        // if not guild name only (in "") then player name
        ObjectGuid targetGuid;
        if (!handler->extractPlayerTarget(*args != '"' ? (char*)args : nullptr, nullptr, &targetGuid))
            return false;
        char* tailStr = *args != '"' ? strtok(nullptr, "") : (char*)args;
        if (!tailStr)
            return false;
        char* guildStr = handler->extractQuotedArg(tailStr);
        if (!guildStr)
            return false;
        std::string guildName = guildStr;
        Guild* targetGuild = sGuildMgr->GetGuildByName(guildName);
        if (!targetGuild)
            return false;
        // player's guild membership checked in AddMember before add
        return targetGuild->AddMember(targetGuid);
    }
References Guild::AddMember(), ChatHandler::extractPlayerTarget(), ChatHandler::extractQuotedArg(), and sGuildMgr.
Referenced by GetCommands().
HandleGuildRankCommand()
static bool guild_commandscript::HandleGuildRankCommand (ChatHandler * handler, Optional< PlayerIdentifier > player, uint8 rank) inline static
    {
        if (!player)
            player = PlayerIdentifier::FromTargetOrSelf(handler);
        if (!player)
            return false;
        uint32 guildId = player->IsConnected() ? player->GetConnectedPlayer()->GetGuildId() : sCharacterCache->GetCharacterGuildIdByGuid(player->GetGUID());
        if (!guildId)
            return false;
        Guild* targetGuild = sGuildMgr->GetGuildById(guildId);
        if (!targetGuild)
            return false;
        return targetGuild->ChangeMemberRank(player->GetGUID(), rank);
    }
References Guild::ChangeMemberRank(), Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), sCharacterCache, and sGuildMgr.
Referenced by GetCommands().
HandleGuildRenameCommand()
static bool guild_commandscript::HandleGuildRenameCommand (ChatHandler * handler, char const * _args) inline static
    {
        if (!*_args)
            return false;
        char *args = (char *)_args;
        char const* oldGuildStr = handler->extractQuotedArg(args);
        if (!oldGuildStr)
        {
            handler->SendSysMessage(LANG_BAD_VALUE);
            handler->SetSentErrorMessage(true);
            return false;
        }
        char const* newGuildStr = handler->extractQuotedArg(strtok(nullptr, ""));
        if (!newGuildStr)
        {
            handler->SendSysMessage(LANG_INSERT_GUILD_NAME);
            handler->SetSentErrorMessage(true);
            return false;
        }
        Guild* guild = sGuildMgr->GetGuildByName(oldGuildStr);
        if (!guild)
        {
            handler->PSendSysMessage(LANG_COMMAND_COULDNOTFIND, oldGuildStr);
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (sGuildMgr->GetGuildByName(newGuildStr))
        {
            handler->PSendSysMessage(LANG_GUILD_RENAME_ALREADY_EXISTS, newGuildStr);
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (!guild->SetName(newGuildStr))
        {
            handler->SendSysMessage(LANG_BAD_VALUE);
            handler->SetSentErrorMessage(true);
            return false;
        }
        handler->PSendSysMessage(LANG_GUILD_RENAME_DONE, oldGuildStr, newGuildStr);
        return true;
    }
References ChatHandler::extractQuotedArg(), LANG_BAD_VALUE, LANG_COMMAND_COULDNOTFIND, LANG_GUILD_RENAME_ALREADY_EXISTS, LANG_GUILD_RENAME_DONE, LANG_INSERT_GUILD_NAME, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), Guild::SetName(), ChatHandler::SetSentErrorMessage(), and sGuildMgr.
Referenced by GetCommands().
HandleGuildUninviteCommand()
static bool guild_commandscript::HandleGuildUninviteCommand (ChatHandler * handler, char const * args) inline static
    {
        Player* target;
        ObjectGuid targetGuid;
        if (!handler->extractPlayerTarget((char*)args, &target, &targetGuid))
            return false;
        uint32 guildId = target ? target->GetGuildId() : sCharacterCache->GetCharacterGuildIdByGuid(targetGuid);
        if (!guildId)
            return false;
        Guild* targetGuild = sGuildMgr->GetGuildById(guildId);
        if (!targetGuild)
            return false;
        targetGuild->DeleteMember(targetGuid, false, true, true);
        return true;
    }
References Guild::DeleteMember(), ChatHandler::extractPlayerTarget(), Player::GetGuildId(), sCharacterCache, and sGuildMgr.
Referenced by GetCommands().