AzeorthCore: MiscScript Class Reference
MiscScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnConstructObject (Object *)
virtual void OnDestructObject (Object *)
virtual void OnConstructPlayer (Player *)
virtual void OnDestructPlayer (Player *)
virtual void OnConstructGroup (Group *)
virtual void OnDestructGroup (Group *)
virtual void OnConstructInstanceSave (InstanceSave *)
virtual void OnDestructInstanceSave (InstanceSave *)
virtual void OnItemCreate (Item *, ItemTemplate const *, Player const *)
virtual bool CanApplySoulboundFlag (Item *, ItemTemplate const *)
virtual bool CanItemApplyEquipSpell (Player *, Item *)
virtual bool CanSendAuctionHello (WorldSession const *, ObjectGuid, Creature *)
virtual void ValidateSpellAtCastSpell (Player *, uint32 &, uint32 &, uint8 &, uint8 &)
virtual void ValidateSpellAtCastSpellResult (Player *, Unit *, Spell *, uint32, uint32)
virtual void OnAfterLootTemplateProcess (Loot *, LootTemplate const *, LootStore const &, Player *, bool, bool, uint16)
virtual void OnPlayerSetPhase (const AuraEffect *, AuraApplication const *, uint8, bool, uint32 &)
virtual void OnInstanceSave (InstanceSave *)
virtual void GetDialogStatus (Player *, Object *)
This hook called before get Quest Dialog Status.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
MiscScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
MiscScript()
MiscScript::MiscScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<MiscScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanApplySoulboundFlag()
virtual bool MiscScript::CanApplySoulboundFlag (Item * , ItemTemplate const *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanApplySoulboundFlag().
CanItemApplyEquipSpell()
virtual bool MiscScript::CanItemApplyEquipSpell (Player * , Item *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanItemApplyEquipSpell().
CanSendAuctionHello()
virtual bool MiscScript::CanSendAuctionHello (WorldSession const * , ObjectGuid , Creature *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanSendAuctionHello().
GetDialogStatus()
virtual void MiscScript::GetDialogStatus (Player * , Object *) inline virtual
This hook called before get Quest Dialog Status.
Parameters
player Contains information about the Player
questgiver Contains information about the Object
{ }
Referenced by ScriptMgr::GetDialogStatus().
IsDatabaseBound()
bool MiscScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
OnAfterLootTemplateProcess()
virtual void MiscScript::OnAfterLootTemplateProcess (Loot * , LootTemplate const * , LootStore const & , Player * , bool , bool , uint16) inline virtual
{ }
Referenced by ScriptMgr::OnAfterLootTemplateProcess().
OnConstructGroup()
virtual void MiscScript::OnConstructGroup (Group *) inline virtual
{ }
Referenced by ScriptMgr::OnConstructGroup().
OnConstructInstanceSave()
virtual void MiscScript::OnConstructInstanceSave (InstanceSave *) inline virtual
{ }
Referenced by ScriptMgr::OnConstructInstanceSave().
OnConstructObject()
virtual void MiscScript::OnConstructObject (Object *) inline virtual
{ }
Referenced by ScriptMgr::OnConstructObject().
OnConstructPlayer()
virtual void MiscScript::OnConstructPlayer (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnConstructPlayer().
OnDestructGroup()
virtual void MiscScript::OnDestructGroup (Group *) inline virtual
{ }
Referenced by ScriptMgr::OnDestructGroup().
OnDestructInstanceSave()
virtual void MiscScript::OnDestructInstanceSave (InstanceSave *) inline virtual
{ }
Referenced by ScriptMgr::OnDestructInstanceSave().
OnDestructObject()
virtual void MiscScript::OnDestructObject (Object *) inline virtual
{ }
Referenced by ScriptMgr::OnDestructObject().
OnDestructPlayer()
virtual void MiscScript::OnDestructPlayer (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnDestructPlayer().
OnInstanceSave()
virtual void MiscScript::OnInstanceSave (InstanceSave *) inline virtual
{ }
Referenced by ScriptMgr::OnInstanceSave().
OnItemCreate()
virtual void MiscScript::OnItemCreate (Item * , ItemTemplate const * , Player const *) inline virtual
{ }
Referenced by ScriptMgr::OnItemCreate().
OnPlayerSetPhase()
virtual void MiscScript::OnPlayerSetPhase (const AuraEffect * , AuraApplication const * , uint8 , bool , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerSetPhase().
ValidateSpellAtCastSpell()
virtual void MiscScript::ValidateSpellAtCastSpell (Player * , uint32 & , uint32 & , uint8 & , uint8 &) inline virtual
{ }
Referenced by ScriptMgr::ValidateSpellAtCastSpell().
ValidateSpellAtCastSpellResult()
virtual void MiscScript::ValidateSpellAtCastSpellResult (Player * , Unit * , Spell * , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::ValidateSpellAtCastSpellResult().