AzerothCore: Acore::HealthPctOrderPred Class Reference
Acore::HealthPctOrderPred Class Reference
#include "Unit.h"
Public Member Functions
HealthPctOrderPred (bool ascending=true)
bool operator() (WorldObject const *objA, WorldObject const *objB) const
bool operator() (Unit const *a, Unit const *b) const
Private Attributes
bool const _ascending
Detailed Description
Constructor & Destructor Documentation
HealthPctOrderPred()
Acore::HealthPctOrderPred::HealthPctOrderPred (bool ascending = true) inline
: _ascending(ascending) { }
Member Function Documentation
operator()() [1/2]
bool Acore::HealthPctOrderPred::operator() (Unit const * a, Unit const * b) const inline
        {
            float rA = a->GetMaxHealth() ? float(a->GetHealth()) / float(a->GetMaxHealth()) : 0.0f;
            float rB = b->GetMaxHealth() ? float(b->GetHealth()) / float(b->GetMaxHealth()) : 0.0f;
            return _ascending ? rA < rB : rA > rB;
        }
References _ascending, Unit::GetHealth(), and Unit::GetMaxHealth().
operator()() [2/2]
bool Acore::HealthPctOrderPred::operator() (WorldObject const * objA, WorldObject const * objB) const inline
        {
            Unit const* a = objA->ToUnit();
            Unit const* b = objB->ToUnit();
            float rA = (a && a->GetMaxHealth()) ? float(a->GetHealth()) / float(a->GetMaxHealth()) : 0.0f;
            float rB = (b && b->GetMaxHealth()) ? float(b->GetHealth()) / float(b->GetMaxHealth()) : 0.0f;
            return _ascending ? rA < rB : rA > rB;
        }
References _ascending, Unit::GetHealth(), Unit::GetMaxHealth(), and Object::ToUnit().
Member Data Documentation
_ascending
bool const Acore::HealthPctOrderPred::_ascending private
Referenced by operator()().