AzerothCore: AreaTrigger_at_celestial_planetarium_enterance Class Reference
AreaTrigger_at_celestial_planetarium_enterance Class Reference
Public Member Functions
AreaTrigger_at_celestial_planetarium_enterance ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
AreaTrigger_at_celestial_planetarium_enterance()
AreaTrigger_at_celestial_planetarium_enterance::AreaTrigger_at_celestial_planetarium_enterance () inline
        : AreaTriggerScript("at_celestial_planetarium_enterance")
    {
    }
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_celestial_planetarium_enterance::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (player->IsAlive())
            if (uint32 questId = (player->GetMap()->Is25ManRaid() ? 13816 : 13607 /*QUEST_CELESTIAL_PLANETARIUM*/))
                if (player->GetQuestStatus(questId) == QUEST_STATUS_INCOMPLETE)
                    player->AreaExploredOrEventHappens(questId);
        return false;
    }
References Player::AreaExploredOrEventHappens(), WorldObject::GetMap(), Player::GetQuestStatus(), Map::Is25ManRaid(), Unit::IsAlive(), and QUEST_STATUS_INCOMPLETE.