AzeorthCore: FormulaScript Class Reference
FormulaScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
virtual void OnHonorCalculation (float &, uint8, float)
virtual void OnGrayLevelCalculation (uint8 &, uint8)
virtual void OnColorCodeCalculation (XPColorChar &, uint8, uint8)
virtual void OnZeroDifferenceCalculation (uint8 &, uint8)
virtual void OnBaseGainCalculation (uint32 &, uint8, uint8, ContentLevels)
virtual void OnGainCalculation (uint32 &, Player *, Unit *)
virtual void OnGroupRateCalculation (float &, uint32, bool)
virtual void OnAfterArenaRatingCalculation (Battleground *const, int32 &, int32 &, int32 &, int32 &)
virtual void OnBeforeUpdatingPersonalRating (int32 &, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
FormulaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
FormulaScript()
FormulaScript::FormulaScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<FormulaScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
OnAfterArenaRatingCalculation()
virtual void FormulaScript::OnAfterArenaRatingCalculation (Battleground * const , int32 & , int32 & , int32 & , int32 &) inline virtual
{ };
Referenced by ScriptMgr::OnAfterArenaRatingCalculation().
OnBaseGainCalculation()
virtual void FormulaScript::OnBaseGainCalculation (uint32 & , uint8 , uint8 , ContentLevels) inline virtual
{ }
Referenced by ScriptMgr::OnBaseGainCalculation().
OnBeforeUpdatingPersonalRating()
virtual void FormulaScript::OnBeforeUpdatingPersonalRating (int32 & , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeUpdatingPersonalRating().
OnColorCodeCalculation()
virtual void FormulaScript::OnColorCodeCalculation (XPColorChar & , uint8 , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnColorCodeCalculation().
OnGainCalculation()
virtual void FormulaScript::OnGainCalculation (uint32 & , Player * , Unit *) inline virtual
{ }
Referenced by ScriptMgr::OnGainCalculation().
OnGrayLevelCalculation()
virtual void FormulaScript::OnGrayLevelCalculation (uint8 & , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnGrayLevelCalculation().
OnGroupRateCalculation()
virtual void FormulaScript::OnGroupRateCalculation (float & , uint32 , bool) inline virtual
{ }
Referenced by ScriptMgr::OnGroupRateCalculation().
OnHonorCalculation()
virtual void FormulaScript::OnHonorCalculation (float & , uint8 , float) inline virtual
{ }
Referenced by ScriptMgr::OnHonorCalculation().
OnZeroDifferenceCalculation()
virtual void FormulaScript::OnZeroDifferenceCalculation (uint8 & , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnZeroDifferenceCalculation().