AzerothCore: npc_barnes Class Reference
npc_barnes Class Reference
Classes
struct npc_barnesAI
Public Member Functions
npc_barnes ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_barnes()
npc_barnes::npc_barnes () inline
: CreatureScript("npc_barnes") { }
Member Function Documentation
GetAI()
CreatureAI * npc_barnes::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return GetKarazhanAI<npc_barnesAI>(creature);
    }
OnGossipHello()
bool npc_barnes::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (InstanceScript* instance = creature->GetInstanceScript())
        {
            // Check for death of Moroes and if opera event is not done already
            if (instance->GetBossState(DATA_MOROES) == DONE &&  instance->GetBossState(DATA_OPERA_PERFORMANCE) != DONE)
            {
                AddGossipItemFor(player, OZ_GOSSIP1_MID, OZ_GOSSIP1_OID, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                if (player->IsGameMaster())
                {
                    AddGossipItemFor(player, GOSSIP_ICON_DOT, OZ_GM_GOSSIP1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                    AddGossipItemFor(player, GOSSIP_ICON_DOT, OZ_GM_GOSSIP2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
                    AddGossipItemFor(player, GOSSIP_ICON_DOT, OZ_GM_GOSSIP3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 5);
                }
                if (instance->GetBossState(DATA_OPERA_PERFORMANCE) != FAIL)
                {
                    SendGossipMenuFor(player, BARNES_TEXT_IS_READY, creature->GetGUID());
                }
                else
                {
                    SendGossipMenuFor(player, BARNES_TEXT_WIPED, creature->GetGUID());
                }
                return true;
            }
        }
        SendGossipMenuFor(player, BARNES_TEXT_NOT_READY, creature->GetGUID());
        return true;
    }
References AddGossipItemFor(), BARNES_TEXT_IS_READY, BARNES_TEXT_NOT_READY, BARNES_TEXT_WIPED, DATA_MOROES, DATA_OPERA_PERFORMANCE, DONE, FAIL, Object::GetGUID(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_DOT, GOSSIP_SENDER_MAIN, Player::IsGameMaster(), OZ_GM_GOSSIP1, OZ_GM_GOSSIP2, OZ_GM_GOSSIP3, OZ_GOSSIP1_MID, OZ_GOSSIP1_OID, and SendGossipMenuFor().
OnGossipSelect()
bool npc_barnes::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
    {
        ClearGossipMenuFor(player);
        npc_barnesAI* pBarnesAI = CAST_AI(npc_barnes::npc_barnesAI, creature->AI());
        switch (action)
        {
            case GOSSIP_ACTION_INFO_DEF+1:
                AddGossipItemFor(player, OZ_GOSSIP2_MID, OZ_GOSSIP2_OID, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                SendGossipMenuFor(player, BARNES_TEXT_IS_READY2, creature->GetGUID());
                break;
            case GOSSIP_ACTION_INFO_DEF+2:
                CloseGossipMenuFor(player);
                pBarnesAI->StartEvent();
                break;
            case GOSSIP_ACTION_INFO_DEF+3:
                CloseGossipMenuFor(player);
                pBarnesAI->m_uiEventId = EVENT_OZ;
                break;
            case GOSSIP_ACTION_INFO_DEF+4:
                CloseGossipMenuFor(player);
                pBarnesAI->m_uiEventId = EVENT_HOOD;
                break;
            case GOSSIP_ACTION_INFO_DEF+5:
                CloseGossipMenuFor(player);
                pBarnesAI->m_uiEventId = EVENT_RAJ;
                break;
        }
        return true;
    }
References AddGossipItemFor(), Creature::AI(), BARNES_TEXT_IS_READY2, CAST_AI, ClearGossipMenuFor(), CloseGossipMenuFor(), EVENT_HOOD, EVENT_OZ, EVENT_RAJ, Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, npc_barnes::npc_barnesAI::m_uiEventId, OZ_GOSSIP2_MID, OZ_GOSSIP2_OID, SendGossipMenuFor(), and npc_barnes::npc_barnesAI::StartEvent().