AzerothCore: EnumUtils::Iterator< Enum > Class Template Reference
EnumUtils::Iterator< Enum > Class Template Reference
#include "SmartEnum.h"
Public Types
using iterator_category = std::random_access_iterator_tag
using value_type = Enum
using pointer = Enum *
using reference = Enum &
using difference_type = std::ptrdiff_t
Public Member Functions
Iterator ()
Iterator (std::size_t index)
bool operator== (const Iterator &other) const
bool operator!= (const Iterator &other) const
difference_type operator- (Iterator const &other) const
bool operator< (const Iterator &other) const
bool operator<= (const Iterator &other) const
bool operator> (const Iterator &other) const
bool operator>= (const Iterator &other) const
value_type operator[] (difference_type d) const
value_type operator* () const
Iterator & operator+= (difference_type d)
Iterator & operator++ ()
Iterator operator++ (int)
Iterator operator+ (difference_type d) const
Iterator & operator-= (difference_type d)
Iterator & operator-- ()
Iterator operator-- (int)
Iterator operator- (difference_type d) const
Private Attributes
difference_type _index
Detailed Description
template<typename Enum>
class EnumUtils::Iterator< Enum >
Member Typedef Documentation
difference_type
template<typename Enum > using EnumUtils::Iterator< Enum >::difference_type = std::ptrdiff_t
iterator_category
template<typename Enum > using EnumUtils::Iterator< Enum >::iterator_category = std::random_access_iterator_tag
pointer
template<typename Enum > using EnumUtils::Iterator< Enum >::pointer = Enum*
reference
template<typename Enum > using EnumUtils::Iterator< Enum >::reference = Enum&
value_type
template<typename Enum > using EnumUtils::Iterator< Enum >::value_type = Enum
Constructor & Destructor Documentation
Iterator() [1/2]
template<typename Enum > EnumUtils::Iterator< Enum >::Iterator () inline
: _index(EnumUtils::Count<Enum>()) {}
Iterator() [2/2]
template<typename Enum > EnumUtils::Iterator< Enum >::Iterator (std::size_t index) inline explicit
: _index(index) { }
Member Function Documentation
operator!=()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator!= (const Iterator< Enum > & other) const inline
{ return !operator==(other); }
References EnumUtils::Iterator< Enum >::operator==().
operator*()
template<typename Enum > value_type EnumUtils::Iterator< Enum >::operator* () const inline
{ return operator[](0); }
References EnumUtils::Iterator< Enum >::operator[]().
operator+()
template<typename Enum > Iterator EnumUtils::Iterator< Enum >::operator+ (difference_type d) const inline
{ Iterator i = *this; i += d; return i; }
operator++() [1/2]
template<typename Enum > Iterator & EnumUtils::Iterator< Enum >::operator++ () inline
{ return operator+=(1); }
References EnumUtils::Iterator< Enum >::operator+=().
operator++() [2/2]
template<typename Enum > Iterator EnumUtils::Iterator< Enum >::operator++ (int) inline
{ Iterator i = *this; operator++(); return i; }
References EnumUtils::Iterator< Enum >::operator++().
Referenced by EnumUtils::Iterator< Enum >::operator++().
operator+=()
template<typename Enum > Iterator & EnumUtils::Iterator< Enum >::operator+= (difference_type d) inline
{ _index += d; return *this; }
References EnumUtils::Iterator< Enum >::_index.
Referenced by EnumUtils::Iterator< Enum >::operator++().
operator-() [1/2]
template<typename Enum > Iterator EnumUtils::Iterator< Enum >::operator- (difference_type d) const inline
{ Iterator i = *this; i -= d; return i; }
operator-() [2/2]
template<typename Enum > difference_type EnumUtils::Iterator< Enum >::operator- (Iterator< Enum > const & other) const inline
{ return _index - other._index; }
References EnumUtils::Iterator< Enum >::_index.
operator--() [1/2]
template<typename Enum > Iterator & EnumUtils::Iterator< Enum >::operator-- () inline
{ return operator-=(1); }
References EnumUtils::Iterator< Enum >::operator-=().
operator--() [2/2]
template<typename Enum > Iterator EnumUtils::Iterator< Enum >::operator-- (int) inline
{ Iterator i = *this; operator--(); return i; }
References EnumUtils::Iterator< Enum >::operator--().
Referenced by EnumUtils::Iterator< Enum >::operator--().
operator-=()
template<typename Enum > Iterator & EnumUtils::Iterator< Enum >::operator-= (difference_type d) inline
{ _index -= d; return *this; }
References EnumUtils::Iterator< Enum >::_index.
Referenced by EnumUtils::Iterator< Enum >::operator--().
operator<()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator< (const Iterator< Enum > & other) const inline
{ return _index < other._index; }
References EnumUtils::Iterator< Enum >::_index.
operator<=()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator<= (const Iterator< Enum > & other) const inline
{ return _index <= other._index; }
References EnumUtils::Iterator< Enum >::_index.
operator==()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator== (const Iterator< Enum > & other) const inline
{ return other._index == _index; }
References EnumUtils::Iterator< Enum >::_index.
Referenced by EnumUtils::Iterator< Enum >::operator!=().
operator>()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator> (const Iterator< Enum > & other) const inline
{ return _index > other._index; }
References EnumUtils::Iterator< Enum >::_index.
operator>=()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator>= (const Iterator< Enum > & other) const inline
{ return _index >= other._index; }
References EnumUtils::Iterator< Enum >::_index.
operator[]()
template<typename Enum > value_type EnumUtils::Iterator< Enum >::operator[] (difference_type d) const inline
{ return FromIndex<Enum>(_index + d); }
References EnumUtils::Iterator< Enum >::_index.
Referenced by EnumUtils::Iterator< Enum >::operator*().
Member Data Documentation
_index
template<typename Enum > difference_type EnumUtils::Iterator< Enum >::_index private
Referenced by EnumUtils::Iterator< Enum >::operator+=(), EnumUtils::Iterator< Enum >::operator-(), EnumUtils::Iterator< Enum >::operator-=(), EnumUtils::Iterator< Enum >::operator<(), EnumUtils::Iterator< Enum >::operator<=(), EnumUtils::Iterator< Enum >::operator==(), EnumUtils::Iterator< Enum >::operator>(), EnumUtils::Iterator< Enum >::operator>=(), and EnumUtils::Iterator< Enum >::operator[]().