AzerothCore: OrcMoveEvent Class Reference
OrcMoveEvent Class Reference
Public Member Functions
OrcMoveEvent (Creature *me)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _me
Detailed Description
Constructor & Destructor Documentation
OrcMoveEvent()
OrcMoveEvent::OrcMoveEvent (Creature * me) inline
: _me(me) {}
Member Function Documentation
Execute()
bool OrcMoveEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        _me->SetReactState(REACT_PASSIVE);
        Position movePos = _me->GetRandomPoint(OrcsRunawayPosition, 10.0f);
        _me->GetMotionMaster()->MovePoint(1, movePos);
        return true;
    }
References _me, Unit::GetMotionMaster(), WorldObject::GetRandomPoint(), MotionMaster::MovePoint(), OrcsRunawayPosition, REACT_PASSIVE, and Creature::SetReactState().
Member Data Documentation
_me
Creature* OrcMoveEvent::_me private
Referenced by Execute().