AzerothCore: azerothcore-wotlk/src/server/scripts/OutdoorPvP/outdoorpvp_script_loader.cpp File Reference
outdoorpvp_script_loader.cpp File Reference
Functions
void AddSC_outdoorpvp_ep ()
void AddSC_outdoorpvp_hp ()
void AddSC_outdoorpvp_na ()
void AddSC_outdoorpvp_si ()
void AddSC_outdoorpvp_tf ()
void AddSC_outdoorpvp_zm ()
void AddSC_outdoorpvp_gh ()
void AddOutdoorPvPScripts ()
Function Documentation
AddOutdoorPvPScripts()
void AddOutdoorPvPScripts ()
{
    AddSC_outdoorpvp_ep();
    AddSC_outdoorpvp_hp();
    AddSC_outdoorpvp_na();
    AddSC_outdoorpvp_si();
    AddSC_outdoorpvp_tf();
    AddSC_outdoorpvp_zm();
    AddSC_outdoorpvp_gh();
}
References AddSC_outdoorpvp_ep(), AddSC_outdoorpvp_gh(), AddSC_outdoorpvp_hp(), AddSC_outdoorpvp_na(), AddSC_outdoorpvp_si(), AddSC_outdoorpvp_tf(), and AddSC_outdoorpvp_zm().
AddSC_outdoorpvp_ep()
void AddSC_outdoorpvp_ep ()
{
    new OutdoorPvP_eastern_plaguelands();
}
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_gh()
void AddSC_outdoorpvp_gh ()
{
    new OutdoorPvP_grizzly_hills();
}
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_hp()
void AddSC_outdoorpvp_hp ()
{
    new OutdoorPvP_hellfire_peninsula();
}
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_na()
void AddSC_outdoorpvp_na ()
{
    new OutdoorPvP_nagrand();
    RegisterCreatureAI(outdoorpvp_na_halaa_creatures);
}
References RegisterCreatureAI.
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_si()
void AddSC_outdoorpvp_si ()
{
    new OutdoorPvP_silithus();
}
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_tf()
void AddSC_outdoorpvp_tf ()
{
    new OutdoorPvP_terokkar_forest();
}
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_zm()
void AddSC_outdoorpvp_zm ()
{
    new OutdoorPvP_zangarmarsh();
}
Referenced by AddOutdoorPvPScripts().