AzeorthCore: CommandSC Class Reference
CommandSC Class Reference
#include "ScriptMgr.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnHandleDevCommand (Player *, bool &)
virtual bool CanExecuteCommand (ChatHandler &, std::string_view)
This hook runs execute chat command.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
CommandSC (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
CommandSC()
CommandSC::CommandSC (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<CommandSC>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanExecuteCommand()
virtual bool CommandSC::CanExecuteCommand (ChatHandler & , std::string_view) inline virtual
This hook runs execute chat command.
Parameters
handler Contains information about the ChatHandler
cmdStr Contains information about the command name
{ return true; }
Referenced by ScriptMgr::CanExecuteCommand().
IsDatabaseBound()
bool CommandSC::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
OnHandleDevCommand()
virtual void CommandSC::OnHandleDevCommand (Player * , bool &) inline virtual
{ }
Referenced by ScriptMgr::OnHandleDevCommand().