AzerothCore: Acore::CheckedBufferOutputIterator< T > Class Template Reference
Acore::CheckedBufferOutputIterator< T > Class Template Reference
#include "Containers.h"
Public Types
using iterator_category = std::output_iterator_tag
using value_type = void
using pointer = T *
using reference = T &
using difference_type = std::ptrdiff_t
Public Member Functions
CheckedBufferOutputIterator (T *buf, std::size_t n)
T & operator* () const
CheckedBufferOutputIterator & operator++ ()
CheckedBufferOutputIterator operator++ (int)
std::size_t remaining () const
Private Member Functions
void check () const
Private Attributes
T * _buf
T * _end
Detailed Description
template<class T>
class Acore::CheckedBufferOutputIterator< T >
Member Typedef Documentation
difference_type
template<class T > using Acore::CheckedBufferOutputIterator< T >::difference_type = std::ptrdiff_t
iterator_category
template<class T > using Acore::CheckedBufferOutputIterator< T >::iterator_category = std::output_iterator_tag
pointer
template<class T > using Acore::CheckedBufferOutputIterator< T >::pointer = T*
reference
template<class T > using Acore::CheckedBufferOutputIterator< T >::reference = T&
value_type
template<class T > using Acore::CheckedBufferOutputIterator< T >::value_type = void
Constructor & Destructor Documentation
CheckedBufferOutputIterator()
template<class T > Acore::CheckedBufferOutputIterator< T >::CheckedBufferOutputIterator (T * buf, std::size_t n) inline
: _buf(buf), _end(buf + n) {}
Member Function Documentation
check()
template<class T > void Acore::CheckedBufferOutputIterator< T >::check () const inline private
        {
            if (!(_buf < _end))
            {
                throw std::out_of_range("index");
            }
        }
References Acore::CheckedBufferOutputIterator< T >::_buf, and Acore::CheckedBufferOutputIterator< T >::_end.
Referenced by Acore::CheckedBufferOutputIterator< T >::operator*(), and Acore::CheckedBufferOutputIterator< T >::operator++().
operator*()
template<class T > T & Acore::CheckedBufferOutputIterator< T >::operator* () const inline
{ check(); return *_buf; }
References Acore::CheckedBufferOutputIterator< T >::_buf, and Acore::CheckedBufferOutputIterator< T >::check().
operator++() [1/2]
template<class T > CheckedBufferOutputIterator & Acore::CheckedBufferOutputIterator< T >::operator++ () inline
{ check(); ++_buf; return *this; }
References Acore::CheckedBufferOutputIterator< T >::_buf, and Acore::CheckedBufferOutputIterator< T >::check().
operator++() [2/2]
template<class T > CheckedBufferOutputIterator Acore::CheckedBufferOutputIterator< T >::operator++ (int) inline
{ CheckedBufferOutputIterator v = *this; operator++(); return v; }
References Acore::CheckedBufferOutputIterator< T >::operator++().
Referenced by Acore::CheckedBufferOutputIterator< T >::operator++().
remaining()
template<class T > std::size_t Acore::CheckedBufferOutputIterator< T >::remaining () const inline
{ return (_end - _buf); }
References Acore::CheckedBufferOutputIterator< T >::_buf, and Acore::CheckedBufferOutputIterator< T >::_end.
Referenced by Utf8toWStr().
Member Data Documentation
_buf
template<class T > T* Acore::CheckedBufferOutputIterator< T >::_buf private
Referenced by Acore::CheckedBufferOutputIterator< T >::check(), Acore::CheckedBufferOutputIterator< T >::operator*(), Acore::CheckedBufferOutputIterator< T >::operator++(), and Acore::CheckedBufferOutputIterator< T >::remaining().
_end
template<class T > T* Acore::CheckedBufferOutputIterator< T >::_end private
Referenced by Acore::CheckedBufferOutputIterator< T >::check(), and Acore::CheckedBufferOutputIterator< T >::remaining().