AzerothCore: adt_liquid_instance Struct Reference
adt_liquid_instance Struct Reference
#include "adt.h"
Public Member Functions
uint8 GetOffsetX () const
uint8 GetOffsetY () const
uint8 GetWidth () const
uint8 GetHeight () const
Public Attributes
uint16 LiquidType
LiquidVertexFormatType LiquidVertexFormat
float MinHeightLevel
float MaxHeightLevel
uint8 OffsetX
uint8 OffsetY
uint8 Width
uint8 Height
uint32 OffsetExistsBitmap
uint32 OffsetVertexData
Detailed Description
Member Function Documentation
GetHeight()
uint8 adt_liquid_instance::GetHeight () const inline
{ return Height; }
References Height.
Referenced by ConvertADT(), adt_MH2O::GetLiquidDepth(), and adt_MH2O::GetLiquidTextureCoordMap().
GetOffsetX()
uint8 adt_liquid_instance::GetOffsetX () const inline
{ return OffsetX; }
References OffsetX.
Referenced by ConvertADT().
GetOffsetY()
uint8 adt_liquid_instance::GetOffsetY () const inline
{ return OffsetY; }
References OffsetY.
Referenced by ConvertADT().
GetWidth()
uint8 adt_liquid_instance::GetWidth () const inline
{ return Width; }
References Width.
Referenced by ConvertADT(), adt_MH2O::GetLiquidDepth(), and adt_MH2O::GetLiquidTextureCoordMap().
Member Data Documentation
Height
uint8 adt_liquid_instance::Height
Referenced by GetHeight().
LiquidType
uint16 adt_liquid_instance::LiquidType
Referenced by ConvertADT(), and adt_MH2O::GetLiquidType().
LiquidVertexFormat
LiquidVertexFormatType adt_liquid_instance::LiquidVertexFormat
Referenced by adt_MH2O::GetLiquidDepth(), adt_MH2O::GetLiquidHeight(), adt_MH2O::GetLiquidTextureCoordMap(), and adt_MH2O::GetLiquidType().
MaxHeightLevel
float adt_liquid_instance::MaxHeightLevel
MinHeightLevel
float adt_liquid_instance::MinHeightLevel
OffsetExistsBitmap
uint32 adt_liquid_instance::OffsetExistsBitmap
Referenced by adt_MH2O::GetLiquidExistsBitmap().
OffsetVertexData
uint32 adt_liquid_instance::OffsetVertexData
Referenced by adt_MH2O::GetLiquidDepth(), adt_MH2O::GetLiquidHeight(), and adt_MH2O::GetLiquidTextureCoordMap().
OffsetX
uint8 adt_liquid_instance::OffsetX
Referenced by GetOffsetX().
OffsetY
uint8 adt_liquid_instance::OffsetY
Referenced by GetOffsetY().
Width
uint8 adt_liquid_instance::Width
Referenced by GetWidth().