AzerothCore: ArenaTeamScript Class Reference
ArenaTeamScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnGetSlotByType (const uint32, uint8 &)
virtual void OnGetArenaPoints (ArenaTeam *, float &)
virtual void OnTypeIDToQueueID (const BattlegroundTypeId, const uint8, uint32 &)
virtual void OnQueueIdToArenaType (const BattlegroundQueueTypeId, uint8 &)
virtual void OnSetArenaMaxPlayersPerTeam (const uint8, uint32 &)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
ArenaTeamScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
ArenaTeamScript()
ArenaTeamScript::ArenaTeamScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<ArenaTeamScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
IsDatabaseBound()
bool ArenaTeamScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; };
OnGetArenaPoints()
virtual void ArenaTeamScript::OnGetArenaPoints (ArenaTeam * , float &) inline virtual
{}
Referenced by ScriptMgr::OnGetArenaPoints().
OnGetSlotByType()
virtual void ArenaTeamScript::OnGetSlotByType (const uint32, uint8 &) inline virtual
{}
Referenced by ScriptMgr::OnGetSlotByType().
OnQueueIdToArenaType()
virtual void ArenaTeamScript::OnQueueIdToArenaType (const BattlegroundQueueTypeId, uint8 &) inline virtual
{}
Referenced by ScriptMgr::OnArenaQueueIdToArenaType().
OnSetArenaMaxPlayersPerTeam()
virtual void ArenaTeamScript::OnSetArenaMaxPlayersPerTeam (const uint8, uint32 &) inline virtual
{}
Referenced by ScriptMgr::OnSetArenaMaxPlayersPerTeam().
OnTypeIDToQueueID()
virtual void ArenaTeamScript::OnTypeIDToQueueID (const BattlegroundTypeId, const uint8, uint32 &) inline virtual
{}
Referenced by ScriptMgr::OnArenaTypeIDToQueueID().