AzeorthCore: spell_gen_on_tournament_mount Class Reference
spell_gen_on_tournament_mount Class Reference
Private Member Functions
PrepareAuraScript (spell_gen_on_tournament_mount)
bool Validate (SpellInfo const *) override
bool Load () override
void HandleApplyEffect (AuraEffect const *, AuraEffectHandleModes)
void HandleRemoveEffect (AuraEffect const *, AuraEffectHandleModes)
uint32 GetPennatSpellId (Player *player, Unit *mount)
void Register () override
Private Attributes
uint32 _pennantSpellId
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< CheckProcHandler > DoCheckAfterProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
GetPennatSpellId()
uint32 spell_gen_on_tournament_mount::GetPennatSpellId (Player * player, Unit * mount) inline private
    {
        switch (mount->GetEntry())
        {
            case NPC_ARGENT_STEED_ASPIRANT:
            case NPC_STORMWIND_STEED:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_STORMWIND))
                        return SPELL_PENNANT_STORMWIND_CHAMPION;
                    else if (player->GetQuestRewardStatus(QUEST_VALIANT_OF_STORMWIND) || player->GetQuestRewardStatus(QUEST_A_VALIANT_OF_STORMWIND))
                        return SPELL_PENNANT_STORMWIND_VALIANT;
                    else
                        return SPELL_PENNANT_STORMWIND_ASPIRANT;
                }
            case NPC_GNOMEREGAN_MECHANOSTRIDER:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_GNOMEREGAN))
                        return SPELL_PENNANT_GNOMEREGAN_CHAMPION;
                    else if (player->GetQuestRewardStatus(QUEST_VALIANT_OF_GNOMEREGAN) || player->GetQuestRewardStatus(QUEST_A_VALIANT_OF_GNOMEREGAN))
                        return SPELL_PENNANT_GNOMEREGAN_VALIANT;
                    else
                        return SPELL_PENNANT_GNOMEREGAN_ASPIRANT;
                }
            case NPC_DARK_SPEAR_RAPTOR:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_SEN_JIN))
                        return SPELL_PENNANT_SEN_JIN_CHAMPION;
                    else if (player->GetQuestRewardStatus(QUEST_VALIANT_OF_SEN_JIN) || player->GetQuestRewardStatus(QUEST_A_VALIANT_OF_SEN_JIN))
                        return SPELL_PENNANT_SEN_JIN_VALIANT;
                    else
                        return SPELL_PENNANT_SEN_JIN_ASPIRANT;
                }
            case NPC_ARGENT_HAWKSTRIDER_ASPIRANT:
            case NPC_SILVERMOON_HAWKSTRIDER:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_SILVERMOON))
                        return SPELL_PENNANT_SILVERMOON_CHAMPION;
                    else if (player->GetQuestRewardStatus(QUEST_VALIANT_OF_SILVERMOON) || player->GetQuestRewardStatus(QUEST_A_VALIANT_OF_SILVERMOON))
                        return SPELL_PENNANT_SILVERMOON_VALIANT;
                    else
                        return SPELL_PENNANT_SILVERMOON_ASPIRANT;
                }
            case NPC_DARNASSIAN_NIGHTSABER:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_DARNASSUS))
                        return SPELL_PENNANT_DARNASSUS_CHAMPION;
                    else if (player->GetQuestRewardStatus(QUEST_VALIANT_OF_DARNASSUS) || player->GetQuestRewardStatus(QUEST_A_VALIANT_OF_DARNASSUS))
                        return SPELL_PENNANT_DARNASSUS_VALIANT;
                    else
                        return SPELL_PENNANT_DARNASSUS_ASPIRANT;
                }
            case NPC_EXODAR_ELEKK:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_THE_EXODAR))
                        return SPELL_PENNANT_EXODAR_CHAMPION;
                    else if (player->GetQuestRewardStatus(QUEST_VALIANT_OF_THE_EXODAR) || player->GetQuestRewardStatus(QUEST_A_VALIANT_OF_THE_EXODAR))
                        return SPELL_PENNANT_EXODAR_VALIANT;
                    else
                        return SPELL_PENNANT_EXODAR_ASPIRANT;
                }
            case NPC_IRONFORGE_RAM:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_IRONFORGE))
                        return SPELL_PENNANT_IRONFORGE_CHAMPION;
                    else if (player->GetQuestRewardStatus(QUEST_VALIANT_OF_IRONFORGE) || player->GetQuestRewardStatus(QUEST_A_VALIANT_OF_IRONFORGE))
                        return SPELL_PENNANT_IRONFORGE_VALIANT;
                    else
                        return SPELL_PENNANT_IRONFORGE_ASPIRANT;
                }
            case NPC_FORSAKEN_WARHORSE:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_UNDERCITY))
                        return SPELL_PENNANT_UNDERCITY_CHAMPION;
                    else if (player->GetQuestRewardStatus(QUEST_VALIANT_OF_UNDERCITY) || player->GetQuestRewardStatus(QUEST_A_VALIANT_OF_UNDERCITY))
                        return SPELL_PENNANT_UNDERCITY_VALIANT;
                    else
                        return SPELL_PENNANT_UNDERCITY_ASPIRANT;
                }
            case NPC_ORGRIMMAR_WOLF:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_ORGRIMMAR))
                        return SPELL_PENNANT_ORGRIMMAR_CHAMPION;
                    else if (player->GetQuestRewardStatus(QUEST_VALIANT_OF_ORGRIMMAR) || player->GetQuestRewardStatus(QUEST_A_VALIANT_OF_ORGRIMMAR))
                        return SPELL_PENNANT_ORGRIMMAR_VALIANT;
                    else
                        return SPELL_PENNANT_ORGRIMMAR_ASPIRANT;
                }
            case NPC_THUNDER_BLUFF_KODO:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_THUNDER_BLUFF))
                        return SPELL_PENNANT_THUNDER_BLUFF_CHAMPION;
                    else if (player->GetQuestRewardStatus(QUEST_VALIANT_OF_THUNDER_BLUFF) || player->GetQuestRewardStatus(QUEST_A_VALIANT_OF_THUNDER_BLUFF))
                        return SPELL_PENNANT_THUNDER_BLUFF_VALIANT;
                    else
                        return SPELL_PENNANT_THUNDER_BLUFF_ASPIRANT;
                }
            case NPC_ARGENT_WARHORSE:
                {
                    if (player->HasAchieved(ACHIEVEMENT_CHAMPION_ALLIANCE) || player->HasAchieved(ACHIEVEMENT_CHAMPION_HORDE))
                        return player->getClass() == CLASS_DEATH_KNIGHT ? SPELL_PENNANT_EBON_BLADE_CHAMPION : SPELL_PENNANT_ARGENT_CRUSADE_CHAMPION;
                    else if (player->HasAchieved(ACHIEVEMENT_ARGENT_VALOR))
                        return player->getClass() == CLASS_DEATH_KNIGHT ? SPELL_PENNANT_EBON_BLADE_VALIANT : SPELL_PENNANT_ARGENT_CRUSADE_VALIANT;
                    else
                        return player->getClass() == CLASS_DEATH_KNIGHT ? SPELL_PENNANT_EBON_BLADE_ASPIRANT : SPELL_PENNANT_ARGENT_CRUSADE_ASPIRANT;
                }
            default:
                return 0;
        }
    }
References ACHIEVEMENT_ARGENT_VALOR, ACHIEVEMENT_CHAMPION_ALLIANCE, ACHIEVEMENT_CHAMPION_DARNASSUS, ACHIEVEMENT_CHAMPION_GNOMEREGAN, ACHIEVEMENT_CHAMPION_HORDE, ACHIEVEMENT_CHAMPION_IRONFORGE, ACHIEVEMENT_CHAMPION_ORGRIMMAR, ACHIEVEMENT_CHAMPION_SEN_JIN, ACHIEVEMENT_CHAMPION_SILVERMOON, ACHIEVEMENT_CHAMPION_STORMWIND, ACHIEVEMENT_CHAMPION_THE_EXODAR, ACHIEVEMENT_CHAMPION_THUNDER_BLUFF, ACHIEVEMENT_CHAMPION_UNDERCITY, CLASS_DEATH_KNIGHT, Unit::getClass(), Object::GetEntry(), Player::GetQuestRewardStatus(), Player::HasAchieved(), NPC_ARGENT_HAWKSTRIDER_ASPIRANT, NPC_ARGENT_STEED_ASPIRANT, NPC_ARGENT_WARHORSE, NPC_DARK_SPEAR_RAPTOR, NPC_DARNASSIAN_NIGHTSABER, NPC_EXODAR_ELEKK, NPC_FORSAKEN_WARHORSE, NPC_GNOMEREGAN_MECHANOSTRIDER, NPC_IRONFORGE_RAM, NPC_ORGRIMMAR_WOLF, NPC_SILVERMOON_HAWKSTRIDER, NPC_STORMWIND_STEED, NPC_THUNDER_BLUFF_KODO, QUEST_A_VALIANT_OF_DARNASSUS, QUEST_A_VALIANT_OF_GNOMEREGAN, QUEST_A_VALIANT_OF_IRONFORGE, QUEST_A_VALIANT_OF_ORGRIMMAR, QUEST_A_VALIANT_OF_SEN_JIN, QUEST_A_VALIANT_OF_SILVERMOON, QUEST_A_VALIANT_OF_STORMWIND, QUEST_A_VALIANT_OF_THE_EXODAR, QUEST_A_VALIANT_OF_THUNDER_BLUFF, QUEST_A_VALIANT_OF_UNDERCITY, QUEST_VALIANT_OF_DARNASSUS, QUEST_VALIANT_OF_GNOMEREGAN, QUEST_VALIANT_OF_IRONFORGE, QUEST_VALIANT_OF_ORGRIMMAR, QUEST_VALIANT_OF_SEN_JIN, QUEST_VALIANT_OF_SILVERMOON, QUEST_VALIANT_OF_STORMWIND, QUEST_VALIANT_OF_THE_EXODAR, QUEST_VALIANT_OF_THUNDER_BLUFF, QUEST_VALIANT_OF_UNDERCITY, SPELL_PENNANT_ARGENT_CRUSADE_ASPIRANT, SPELL_PENNANT_ARGENT_CRUSADE_CHAMPION, SPELL_PENNANT_ARGENT_CRUSADE_VALIANT, SPELL_PENNANT_DARNASSUS_ASPIRANT, SPELL_PENNANT_DARNASSUS_CHAMPION, SPELL_PENNANT_DARNASSUS_VALIANT, SPELL_PENNANT_EBON_BLADE_ASPIRANT, SPELL_PENNANT_EBON_BLADE_CHAMPION, SPELL_PENNANT_EBON_BLADE_VALIANT, SPELL_PENNANT_EXODAR_ASPIRANT, SPELL_PENNANT_EXODAR_CHAMPION, SPELL_PENNANT_EXODAR_VALIANT, SPELL_PENNANT_GNOMEREGAN_ASPIRANT, SPELL_PENNANT_GNOMEREGAN_CHAMPION, SPELL_PENNANT_GNOMEREGAN_VALIANT, SPELL_PENNANT_IRONFORGE_ASPIRANT, SPELL_PENNANT_IRONFORGE_CHAMPION, SPELL_PENNANT_IRONFORGE_VALIANT, SPELL_PENNANT_ORGRIMMAR_ASPIRANT, SPELL_PENNANT_ORGRIMMAR_CHAMPION, SPELL_PENNANT_ORGRIMMAR_VALIANT, SPELL_PENNANT_SEN_JIN_ASPIRANT, SPELL_PENNANT_SEN_JIN_CHAMPION, SPELL_PENNANT_SEN_JIN_VALIANT, SPELL_PENNANT_SILVERMOON_ASPIRANT, SPELL_PENNANT_SILVERMOON_CHAMPION, SPELL_PENNANT_SILVERMOON_VALIANT, SPELL_PENNANT_STORMWIND_ASPIRANT, SPELL_PENNANT_STORMWIND_CHAMPION, SPELL_PENNANT_STORMWIND_VALIANT, SPELL_PENNANT_THUNDER_BLUFF_ASPIRANT, SPELL_PENNANT_THUNDER_BLUFF_CHAMPION, SPELL_PENNANT_THUNDER_BLUFF_VALIANT, SPELL_PENNANT_UNDERCITY_ASPIRANT, SPELL_PENNANT_UNDERCITY_CHAMPION, and SPELL_PENNANT_UNDERCITY_VALIANT.
Referenced by HandleApplyEffect().
HandleApplyEffect()
void spell_gen_on_tournament_mount::HandleApplyEffect (AuraEffect const * , AuraEffectHandleModes) inline private
    {
        if (Unit* caster = GetCaster())
        {
            if (Unit* vehicle = caster->GetVehicleBase())
            {
                _pennantSpellId = GetPennatSpellId(caster->ToPlayer(), vehicle);
                caster->CastSpell(caster, _pennantSpellId, true);
            }
        }
    }
References _pennantSpellId, AuraScript::GetCaster(), GetPennatSpellId(), and Unit::GetVehicleBase().
Referenced by Register().
HandleRemoveEffect()
void spell_gen_on_tournament_mount::HandleRemoveEffect (AuraEffect const * , AuraEffectHandleModes) inline private
    {
        if (Unit* caster = GetCaster())
            caster->RemoveAurasDueToSpell(_pennantSpellId);
    }
References _pennantSpellId, and AuraScript::GetCaster().
Referenced by Register().
Load()
bool spell_gen_on_tournament_mount::Load () inline override private virtual
Reimplemented from _SpellScript.
    {
        _pennantSpellId = 0;
        return GetCaster() && GetCaster()->GetTypeId() == TYPEID_PLAYER;
    }
References _pennantSpellId, AuraScript::GetCaster(), Object::GetTypeId(), and TYPEID_PLAYER.
PrepareAuraScript()
spell_gen_on_tournament_mount::PrepareAuraScript (spell_gen_on_tournament_mount) private
Register()
void spell_gen_on_tournament_mount::Register () inline override private virtual
Implements _SpellScript.
    {
        AfterEffectApply += AuraEffectApplyFn(spell_gen_on_tournament_mount::HandleApplyEffect, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
        OnEffectRemove += AuraEffectRemoveFn(spell_gen_on_tournament_mount::HandleRemoveEffect, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
    }
References AuraScript::AfterEffectApply, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK, AuraEffectApplyFn, AuraEffectRemoveFn, EFFECT_0, HandleApplyEffect(), HandleRemoveEffect(), AuraScript::OnEffectRemove, and SPELL_AURA_DUMMY.
Validate()
bool spell_gen_on_tournament_mount::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo(
            {
                SPELL_PENNANT_STORMWIND_ASPIRANT,
                SPELL_PENNANT_STORMWIND_VALIANT,
                SPELL_PENNANT_STORMWIND_CHAMPION,
                SPELL_PENNANT_GNOMEREGAN_ASPIRANT,
                SPELL_PENNANT_GNOMEREGAN_VALIANT,
                SPELL_PENNANT_GNOMEREGAN_CHAMPION,
                SPELL_PENNANT_SEN_JIN_ASPIRANT,
                SPELL_PENNANT_SEN_JIN_VALIANT,
                SPELL_PENNANT_SEN_JIN_CHAMPION,
                SPELL_PENNANT_SILVERMOON_ASPIRANT,
                SPELL_PENNANT_SILVERMOON_VALIANT,
                SPELL_PENNANT_SILVERMOON_CHAMPION,
                SPELL_PENNANT_DARNASSUS_ASPIRANT,
                SPELL_PENNANT_DARNASSUS_VALIANT,
                SPELL_PENNANT_DARNASSUS_CHAMPION,
                SPELL_PENNANT_EXODAR_ASPIRANT,
                SPELL_PENNANT_EXODAR_VALIANT,
                SPELL_PENNANT_EXODAR_CHAMPION,
                SPELL_PENNANT_IRONFORGE_ASPIRANT,
                SPELL_PENNANT_IRONFORGE_VALIANT,
                SPELL_PENNANT_IRONFORGE_CHAMPION,
                SPELL_PENNANT_UNDERCITY_ASPIRANT,
                SPELL_PENNANT_UNDERCITY_VALIANT,
                SPELL_PENNANT_UNDERCITY_CHAMPION,
                SPELL_PENNANT_ORGRIMMAR_ASPIRANT,
                SPELL_PENNANT_ORGRIMMAR_VALIANT,
                SPELL_PENNANT_ORGRIMMAR_CHAMPION,
                SPELL_PENNANT_THUNDER_BLUFF_ASPIRANT,
                SPELL_PENNANT_THUNDER_BLUFF_VALIANT,
                SPELL_PENNANT_THUNDER_BLUFF_CHAMPION,
                SPELL_PENNANT_ARGENT_CRUSADE_ASPIRANT,
                SPELL_PENNANT_ARGENT_CRUSADE_VALIANT,
                SPELL_PENNANT_ARGENT_CRUSADE_CHAMPION,
                SPELL_PENNANT_EBON_BLADE_ASPIRANT,
                SPELL_PENNANT_EBON_BLADE_VALIANT,
                SPELL_PENNANT_EBON_BLADE_CHAMPION
            });
    }
References SPELL_PENNANT_ARGENT_CRUSADE_ASPIRANT, SPELL_PENNANT_ARGENT_CRUSADE_CHAMPION, SPELL_PENNANT_ARGENT_CRUSADE_VALIANT, SPELL_PENNANT_DARNASSUS_ASPIRANT, SPELL_PENNANT_DARNASSUS_CHAMPION, SPELL_PENNANT_DARNASSUS_VALIANT, SPELL_PENNANT_EBON_BLADE_ASPIRANT, SPELL_PENNANT_EBON_BLADE_CHAMPION, SPELL_PENNANT_EBON_BLADE_VALIANT, SPELL_PENNANT_EXODAR_ASPIRANT, SPELL_PENNANT_EXODAR_CHAMPION, SPELL_PENNANT_EXODAR_VALIANT, SPELL_PENNANT_GNOMEREGAN_ASPIRANT, SPELL_PENNANT_GNOMEREGAN_CHAMPION, SPELL_PENNANT_GNOMEREGAN_VALIANT, SPELL_PENNANT_IRONFORGE_ASPIRANT, SPELL_PENNANT_IRONFORGE_CHAMPION, SPELL_PENNANT_IRONFORGE_VALIANT, SPELL_PENNANT_ORGRIMMAR_ASPIRANT, SPELL_PENNANT_ORGRIMMAR_CHAMPION, SPELL_PENNANT_ORGRIMMAR_VALIANT, SPELL_PENNANT_SEN_JIN_ASPIRANT, SPELL_PENNANT_SEN_JIN_CHAMPION, SPELL_PENNANT_SEN_JIN_VALIANT, SPELL_PENNANT_SILVERMOON_ASPIRANT, SPELL_PENNANT_SILVERMOON_CHAMPION, SPELL_PENNANT_SILVERMOON_VALIANT, SPELL_PENNANT_STORMWIND_ASPIRANT, SPELL_PENNANT_STORMWIND_CHAMPION, SPELL_PENNANT_STORMWIND_VALIANT, SPELL_PENNANT_THUNDER_BLUFF_ASPIRANT, SPELL_PENNANT_THUNDER_BLUFF_CHAMPION, SPELL_PENNANT_THUNDER_BLUFF_VALIANT, SPELL_PENNANT_UNDERCITY_ASPIRANT, SPELL_PENNANT_UNDERCITY_CHAMPION, SPELL_PENNANT_UNDERCITY_VALIANT, and _SpellScript::ValidateSpellInfo().
Member Data Documentation
_pennantSpellId
uint32 spell_gen_on_tournament_mount::_pennantSpellId private
Referenced by HandleApplyEffect(), HandleRemoveEffect(), and Load().