AzerothCore: MotdMgr Class Reference
MotdMgr Class Reference
#include "MotdMgr.h"
Public Member Functions
void CreateWorldPackages ()
Converts the localized string to world packages.
void SetMotd (std::string motd, LocaleConstant locale)
Set a new Message of the Day.
void LoadMotd ()
Load Message of the Day.
char const * GetMotd (LocaleConstant locale)
Get the current Message of the Day.
WorldPacket const * GetMotdPacket (LocaleConstant locale)
Returns the current motd packet for the given locale.
bool IsValidLocale (std::string const &locale)
Static Public Member Functions
static MotdMgr * instance ()
Private Member Functions
std::string LoadDefaultMotd (uint32 realmId)
void LoadLocalizedMotds (uint32 realmId)
void SetDefaultMotd ()
WorldPacket CreateWorldPacket (std::string const &motd)
Detailed Description
Member Function Documentation
CreateWorldPackages()
void MotdMgr::CreateWorldPackages ()
Converts the localized string to world packages.
{
    for (auto const& [locale, motd] : MotdMap)
        // Store the constructed packet in MotdPackets with the locale as the key
        MotdPackets[locale] = CreateWorldPacket(motd);
}
References CreateWorldPacket().
Referenced by LoadMotd().
CreateWorldPacket()
WorldPacket MotdMgr::CreateWorldPacket (std::string const & motd) private
{
    // Create a new WorldPacket for this locale
    WorldPacket data(SMSG_MOTD); // new in 2.0.1
    // Tokenize the motd string by '@'
    std::vector<std::string_view> motdTokens = Acore::Tokenize(motd, '@', true);
    data << uint32(motdTokens.size()); // line count
    for (std::string_view token : motdTokens)
        data << token;
    return data;
}
References SMSG_MOTD, and Acore::Tokenize().
Referenced by CreateWorldPackages(), and SetMotd().
GetMotd()
char const * MotdMgr::GetMotd (LocaleConstant locale)
Get the current Message of the Day.
{
    // Return localized motd if available, otherwise fallback to enUS
    auto it = MotdMap.find(locale);
    if (it != MotdMap.end())
        return it->second.c_str();
    return MotdMap[DEFAULT_LOCALE].c_str();  // Fallback to enUS if locale is not found
}
References DEFAULT_LOCALE.
GetMotdPacket()
WorldPacket const * MotdMgr::GetMotdPacket (LocaleConstant locale)
Returns the current motd packet for the given locale.
{
    // Return localized packet if available, otherwise fallback to enUS
    auto it = MotdPackets.find(locale);
    if (it != MotdPackets.end())
        return &it->second;
    return &MotdPackets[DEFAULT_LOCALE];  // Fallback to enUS if locale is not found
}
References DEFAULT_LOCALE.
instance()
MotdMgr * MotdMgr::instance () static
{
    static MotdMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
IsValidLocale()
bool MotdMgr::IsValidLocale (std::string const & locale)
{
    // Use std::find to search for the locale in the array
    return std::find(std::begin(localeNames), std::end(localeNames), locale) != std::end(localeNames);
}
References localeNames.
LoadDefaultMotd()
std::string MotdMgr::LoadDefaultMotd (uint32 realmId) private
{
    LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_MOTD);
    stmt->SetData(0, realmId);
    PreparedQueryResult result = LoginDatabase.Query(stmt);
    if (result)
    {
        Field* fields = result->Fetch();
        return fields[0].Get<std::string>();  // Return the main motd if found
    }
    return ""; // Return empty string if no motd found
}
References Field::Get(), LOGIN_SEL_MOTD, LoginDatabase, and PreparedStatementBase::SetData().
Referenced by LoadMotd().
LoadLocalizedMotds()
void MotdMgr::LoadLocalizedMotds (uint32 realmId) private
{
    // First, check if base MOTD exists
    LoginDatabasePreparedStatement* baseStmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_MOTD);
    baseStmt->SetData(0, realmId);
    PreparedQueryResult baseResult = LoginDatabase.Query(baseStmt);
    if (!baseResult)
    {
        LOG_ERROR("server.loading", "No base MOTD found for realm %u. Localized MOTDs will not be loaded.", realmId);
        return;
    }
    // Now load localized versions
    LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_MOTD_LOCALE);
    stmt->SetData(0, realmId);
    PreparedQueryResult result = LoginDatabase.Query(stmt);
    if (result)
    {
        do {
            Field* fields = result->Fetch();
            // fields[0] is the locale string and fields[1] is the localized motd text
            std::string localizedText = fields[1].Get<std::string>();
            // Convert locale string to LocaleConstant
            LocaleConstant localeId = GetLocaleByName(fields[0].Get<std::string>());
            if (localeId == DEFAULT_LOCALE)
                continue;
            MotdMap[localeId] = localizedText;
        } while (result->NextRow());
    }
}
References DEFAULT_LOCALE, Field::Get(), GetLocaleByName(), LOG_ERROR, LOGIN_SEL_MOTD, LOGIN_SEL_MOTD_LOCALE, LoginDatabase, and PreparedStatementBase::SetData().
Referenced by LoadMotd().
LoadMotd()
void MotdMgr::LoadMotd ()
Load Message of the Day.
{
    uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
    // Load the main motd for the realm and assign it to enUS if available
    std::string motd = LoadDefaultMotd(realmId);
    // Check if motd was loaded; if not, set default only for enUS
    if (motd.empty())
        SetDefaultMotd();  // Only sets enUS default if motd is empty
    else
        MotdMap[DEFAULT_LOCALE] = motd;  // Assign the loaded motd to enUS
    // Load localized texts if available
    LoadLocalizedMotds(realmId);
    // Create all world packages after loading motd and localized texts
    CreateWorldPackages();
}
References CreateWorldPackages(), DEFAULT_LOCALE, LoadDefaultMotd(), LoadLocalizedMotds(), sConfigMgr, and SetDefaultMotd().
SetDefaultMotd()
void MotdMgr::SetDefaultMotd () private
{
    std::string motd = /* fctlsup << //0x338// "63"+"cx""d2"+"1e""dd"+"cx""ds"+"ce""dd"+"ce""7D"+ << */
        /*"d3"+"ce"*/ std::string("@|") + "cf" +/*"as"+"k4"*/"fF" + "F4" +/*"d5"+"f3"*/"A2" + "DT"/*"F4"+"Az"*/ + "hi" + "s "
        /*"fd"+"hy"*/ + "se" + "rv" +/*"nh"+"k3"*/"er" + " r" +/*"x1"+"A2"*/"un" + "s "/*"F2"+"Ay"*/ + "on" + " Az"
        /*"xs"+"5n"*/ + "er" + "ot" +/*"xs"+"A2"*/"hC" + "or" +/*"a4"+"f3"*/"e|" + "r "/*"f2"+"A2"*/ + "|c" + "ff"
        /*"5g"+"A2"*/ + "3C" + "E7" +/*"k5"+"AX"*/"FF" + "ww" +/*"sx"+"Gj"*/"w." + "az"/*"a1"+"vf"*/ + "er" + "ot"
        /*"ds"+"sx"*/ + "hc" + "or" +/*"F4"+"k5"*/"e." + "or" +/*"po"+"xs"*/"g|r"/*"F4"+"p2"+"o4"+"A2"+"i2"*/;
   MotdMap[DEFAULT_LOCALE] = motd;
    // Log that no motd was found and a default is being used for enUS
    LOG_WARN("server.loading", ">> Loaded 0 motd definitions. DB table `motd` is empty for this realm!");
    LOG_INFO("server.loading", " ");
}
References DEFAULT_LOCALE, LOG_INFO, and LOG_WARN.
Referenced by LoadMotd().
SetMotd()
void MotdMgr::SetMotd (std::string motd, LocaleConstant locale)
Set a new Message of the Day.
{
    // scripts may change motd
    sScriptMgr->OnMotdChange(motd, locale);
    MotdMap[locale] = motd;
    MotdPackets[locale] = CreateWorldPacket(motd);
}
References CreateWorldPacket(), and sScriptMgr.