AzerothCore: SQLQueryHolder< T > Class Template Reference
SQLQueryHolder< T > Class Template Reference
#include "QueryHolder.h"
Public Member Functions
bool SetPreparedQuery (std::size_t index, PreparedStatement< T > *stmt)
Public Member Functions inherited from SQLQueryHolderBase
SQLQueryHolderBase ()=default
virtual ~SQLQueryHolderBase ()
void SetSize (std::size_t size)
PreparedQueryResult GetPreparedResult (std::size_t index) const
void SetPreparedResult (std::size_t index, PreparedResultSet *result)
Additional Inherited Members
Protected Member Functions inherited from SQLQueryHolderBase
bool SetPreparedQueryImpl (std::size_t index, PreparedStatementBase *stmt)
Detailed Description
template<typename T>
class SQLQueryHolder< T >
Member Function Documentation
SetPreparedQuery()
template<typename T > bool SQLQueryHolder< T >::SetPreparedQuery (std::size_t index, PreparedStatement< T > * stmt) inline
    {
        return SetPreparedQueryImpl(index, stmt);
    }
References SQLQueryHolderBase::SetPreparedQueryImpl().
Referenced by LoginQueryHolder::Initialize(), and PetLoadQueryHolder::PetLoadQueryHolder().