AzerothCore: send_commandscript Class Reference
send_commandscript Class Reference
Public Member Functions
send_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleSendItemsCommand (ChatHandler *handler, Optional< PlayerIdentifier > target, QuotedString subject, QuotedString text, Tail items)
static bool HandleSendMailCommand (ChatHandler *handler, Optional< PlayerIdentifier > target, QuotedString subject, QuotedString text)
static bool HandleSendMessageCommand (ChatHandler *handler, Optional< PlayerIdentifier > target, Tail message)
static bool HandleSendMoneyCommand (ChatHandler *handler, Optional< PlayerIdentifier > target, QuotedString subject, QuotedString text, uint32 money)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
send_commandscript()
send_commandscript::send_commandscript () inline
: CommandScript("send_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable send_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable sendCommandTable =
        {
            { "items",   HandleSendItemsCommand,   SEC_GAMEMASTER,    Console::Yes },
            { "mail",    HandleSendMailCommand,    SEC_GAMEMASTER,    Console::Yes },
            { "message", HandleSendMessageCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "money",   HandleSendMoneyCommand,   SEC_GAMEMASTER,    Console::Yes }
        };
        static ChatCommandTable commandTable =
        {
            { "send", sendCommandTable }
        };
        return commandTable;
    }
References HandleSendItemsCommand(), HandleSendMailCommand(), HandleSendMessageCommand(), HandleSendMoneyCommand(), SEC_ADMINISTRATOR, and SEC_GAMEMASTER.
HandleSendItemsCommand()
static bool send_commandscript::HandleSendItemsCommand (ChatHandler * handler, Optional< PlayerIdentifier > target, QuotedString subject, QuotedString text, Tail items) inline static
    {
        if (!target)
        {
            target = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!target)
        {
            return false;
        }
        // extract items
        std::vector<std::pair<uint32, uint32>> itemList;
        for (auto const& itemString : Acore::Tokenize(items, ' ', true))
        {
            auto itemTokens = Acore::Tokenize(itemString, ':', false);
            uint32 itemCount;
            switch (itemTokens.size())
            {
                case 1:
                    itemCount = 1; // Default to sending 1 item
                    break;
                case 2:
                    itemCount = *Acore::StringTo<uint32>(itemTokens.at(1));
                    break;
                default:
                    handler->SendSysMessage(Acore::StringFormat("> Incorrect item list format for '{}'", itemString));
                    continue;
            }
            uint32 itemID = *Acore::StringTo<uint32>(itemTokens.at(0));
            ItemTemplate const* itemTemplate = sObjectMgr->GetItemTemplate(itemID);
            if (!itemTemplate)
            {
                handler->SendErrorMessage(LANG_COMMAND_ITEMIDINVALID, itemID);
                return false;
            }
            if (!itemCount || (itemTemplate->MaxCount > 0 && itemCount > uint32(itemTemplate->MaxCount)))
            {
                handler->SendErrorMessage(LANG_COMMAND_INVALID_ITEM_COUNT, itemCount, itemID);
                return false;
            }
            while (itemCount > itemTemplate->GetMaxStackSize())
            {
                itemList.emplace_back(itemID, itemTemplate->GetMaxStackSize());
                itemCount -= itemTemplate->GetMaxStackSize();
            }
            itemList.emplace_back(itemID, itemCount);
            if (itemList.size() > MAX_MAIL_ITEMS)
            {
                handler->SendErrorMessage(LANG_COMMAND_MAIL_ITEMS_LIMIT, MAX_MAIL_ITEMS);
                return false;
            }
        }
        // If the message is sent from console, set it as sent by the target itself, like the other Customer Support mails.
        ObjectGuid::LowType senderGuid = handler->GetSession() ? handler->GetSession()->GetPlayer()->GetGUID().GetCounter() : target->GetGUID().GetCounter();
        // fill mail
        MailDraft draft(subject, text);
        MailSender sender(MAIL_NORMAL, senderGuid, MAIL_STATIONERY_GM);
        CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
        for (auto const& [itemID, itemCount] : itemList)
        {
            if (Item* item = Item::CreateItem(itemID, itemCount, handler->GetSession() ? handler->GetSession()->GetPlayer() : 0))
            {
                item->SaveToDB(trans); // save for prevent lost at next mail load, if send fail then item will deleted
                draft.AddItem(item);
            }
        }
        draft.SendMailTo(trans, MailReceiver(target->GetConnectedPlayer(), target->GetGUID().GetCounter()), sender);
        CharacterDatabase.CommitTransaction(trans);
        handler->PSendSysMessage(LANG_MAIL_SENT, handler->playerLink(target->GetName()));
        return true;
    }
References MailDraft::AddItem(), CharacterDatabase, Item::CreateItem(), Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), ObjectGuid::GetCounter(), Object::GetGUID(), ItemTemplate::GetMaxStackSize(), WorldSession::GetPlayer(), ChatHandler::GetSession(), LANG_COMMAND_INVALID_ITEM_COUNT, LANG_COMMAND_ITEMIDINVALID, LANG_COMMAND_MAIL_ITEMS_LIMIT, LANG_MAIL_SENT, MAIL_NORMAL, MAIL_STATIONERY_GM, MAX_MAIL_ITEMS, ItemTemplate::MaxCount, ChatHandler::playerLink(), ChatHandler::PSendSysMessage(), ChatHandler::SendErrorMessage(), MailDraft::SendMailTo(), ChatHandler::SendSysMessage(), sObjectMgr, Acore::StringFormat(), and Acore::Tokenize().
Referenced by GetCommands().
HandleSendMailCommand()
static bool send_commandscript::HandleSendMailCommand (ChatHandler * handler, Optional< PlayerIdentifier > target, QuotedString subject, QuotedString text) inline static
    {
        if (!target)
        {
            target = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!target)
        {
            return false;
        }
        ObjectGuid::LowType senderGuid = handler->GetSession() ? handler->GetSession()->GetPlayer()->GetGUID().GetCounter() : target->GetGUID().GetCounter();
        // If the message is sent from console, set it as sent by the target itself, like the other Customer Support mails.
        MailSender sender(MAIL_NORMAL, senderGuid, MAIL_STATIONERY_GM);
        MailDraft draft(subject, text);
        CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
        draft.SendMailTo(trans, MailReceiver(target->GetConnectedPlayer(), target->GetGUID().GetCounter()), sender);
        CharacterDatabase.CommitTransaction(trans);
        handler->PSendSysMessage(LANG_MAIL_SENT, handler->playerLink(target->GetName()));
        return true;
    }
References CharacterDatabase, Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), ObjectGuid::GetCounter(), Object::GetGUID(), WorldSession::GetPlayer(), ChatHandler::GetSession(), LANG_MAIL_SENT, MAIL_NORMAL, MAIL_STATIONERY_GM, ChatHandler::playerLink(), ChatHandler::PSendSysMessage(), and MailDraft::SendMailTo().
Referenced by GetCommands().
HandleSendMessageCommand()
static bool send_commandscript::HandleSendMessageCommand (ChatHandler * handler, Optional< PlayerIdentifier > target, Tail message) inline static
Send the message
    {
        if (!target)
        {
            target = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!target || !target->IsConnected())
        {
            return false;
        }
        Player* player = target->GetConnectedPlayer();
        std::string msg = std::string{ message };
        // Use SendAreaTriggerMessage for fastest delivery.
        player->GetSession()->SendAreaTriggerMessage("%s", msg.c_str());
        player->GetSession()->SendAreaTriggerMessage("|cffff0000[Message from administrator]:|r");
        // Confirmation message
        handler->PSendSysMessage(LANG_SENDMESSAGE, handler->playerLink(target->GetName()), msg);
        return true;
    }
References Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Player::GetSession(), LANG_SENDMESSAGE, ChatHandler::playerLink(), ChatHandler::PSendSysMessage(), and WorldSession::SendAreaTriggerMessage().
Referenced by GetCommands().
HandleSendMoneyCommand()
static bool send_commandscript::HandleSendMoneyCommand (ChatHandler * handler, Optional< PlayerIdentifier > target, QuotedString subject, QuotedString text, uint32 money) inline static
    {
        if (!target)
        {
            target = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!target)
        {
            return false;
        }
        // from console show not existed sender
        MailSender sender(MAIL_NORMAL, handler->GetSession() ? handler->GetSession()->GetPlayer()->GetGUID().GetCounter() : 0, MAIL_STATIONERY_GM);
        CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
        MailDraft(subject, text)
        .AddMoney(money)
        .SendMailTo(trans, MailReceiver(target->GetConnectedPlayer(), target->GetGUID().GetCounter()), sender);
        CharacterDatabase.CommitTransaction(trans);
        handler->PSendSysMessage(LANG_MAIL_SENT, handler->playerLink(target->GetName()));
        return true;
    }
References MailDraft::AddMoney(), CharacterDatabase, Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), ObjectGuid::GetCounter(), Object::GetGUID(), WorldSession::GetPlayer(), ChatHandler::GetSession(), LANG_MAIL_SENT, MAIL_NORMAL, MAIL_STATIONERY_GM, ChatHandler::playerLink(), ChatHandler::PSendSysMessage(), and MailDraft::SendMailTo().
Referenced by GetCommands().