AzerothCore: VehicleCheck Class Reference
VehicleCheck Class Reference
Public Member Functions
bool operator() (WorldObject *unit)
Detailed Description
Member Function Documentation
operator()()
bool VehicleCheck::operator() (WorldObject * unit) inline
    {
        return (!unit->IsCreature() && !unit->IsPlayer()) || unit->ToUnit()->GetVehicle();
    }
References Unit::GetVehicle(), Object::IsCreature(), Object::IsPlayer(), and Object::ToUnit().