AzerothCore: spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript Class Reference
spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_putricide_unbound_plague_SpellScript)
bool Validate (SpellInfo const *) override
void FilterTargets (std::list< WorldObject * > &targets)
void HandleScript (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
FilterTargets()
void spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::FilterTargets (std::list< WorldObject * > & targets) inline private
        {
            if (AuraEffect const* eff = GetCaster()->GetAuraEffect(SPELL_UNBOUND_PLAGUE_SEARCHER, EFFECT_0))
            {
                if (eff->GetTickNumber() < 2)
                {
                    targets.clear();
                    return;
                }
            }
            targets.remove_if(Acore::UnitAuraCheck(true, sSpellMgr->GetSpellIdForDifficulty(SPELL_UNBOUND_PLAGUE, GetCaster())));
            Acore::Containers::RandomResize(targets, 1);
        }
References EFFECT_0, SpellScript::GetCaster(), Acore::Containers::RandomResize(), SPELL_UNBOUND_PLAGUE, SPELL_UNBOUND_PLAGUE_SEARCHER, and sSpellMgr.
Referenced by Register().
HandleScript()
void spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::HandleScript (SpellEffIndex) inline private
        {
            if (!GetHitUnit())
                return;
            InstanceScript* instance = GetCaster()->GetInstanceScript();
            if (!instance)
                return;
            uint32 plagueId = sSpellMgr->GetSpellIdForDifficulty(SPELL_UNBOUND_PLAGUE, GetCaster());
            if (!GetHitUnit()->HasAura(plagueId))
            {
                if (Creature* professor = ObjectAccessor::GetCreature(*GetCaster(), instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
                {
                    if (Aura* oldPlague = GetCaster()->GetAura(plagueId, professor->GetGUID()))
                    {
                        if (Aura* newPlague = professor->AddAura(plagueId, GetHitUnit()))
{
                            newPlague->SetMaxDuration(oldPlague->GetMaxDuration());
                            newPlague->SetDuration(oldPlague->GetDuration());
                            oldPlague->Remove();
                            GetCaster()->RemoveAurasDueToSpell(SPELL_UNBOUND_PLAGUE_SEARCHER);
                            GetCaster()->CastSpell(GetCaster(), SPELL_PLAGUE_SICKNESS, true);
                            GetCaster()->CastSpell(GetCaster(), SPELL_UNBOUND_PLAGUE_PROTECTION, true);
                            professor->CastSpell(GetHitUnit(), SPELL_UNBOUND_PLAGUE_SEARCHER, true);
                        }
                    }
                }
            }
        }
References Unit::CastSpell(), DATA_PROFESSOR_PUTRICIDE, SpellScript::GetCaster(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), SpellScript::GetHitUnit(), WorldObject::GetInstanceScript(), Unit::RemoveAurasDueToSpell(), SPELL_PLAGUE_SICKNESS, SPELL_UNBOUND_PLAGUE, SPELL_UNBOUND_PLAGUE_PROTECTION, SPELL_UNBOUND_PLAGUE_SEARCHER, and sSpellMgr.
Referenced by Register().
PrepareSpellScript()
spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::PrepareSpellScript (spell_putricide_unbound_plague_SpellScript) private
Register()
void spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::Register () inline override private virtual
Implements _SpellScript.
        {
            OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_putricide_unbound_plague_SpellScript::FilterTargets, EFFECT_0, TARGET_UNIT_SRC_AREA_ALLY);
            OnEffectHitTarget += SpellEffectFn(spell_putricide_unbound_plague_SpellScript::HandleScript, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
        }
References EFFECT_0, FilterTargets(), HandleScript(), SpellScript::OnEffectHitTarget, SpellScript::OnObjectAreaTargetSelect, SPELL_EFFECT_SCRIPT_EFFECT, SpellEffectFn, SpellObjectAreaTargetSelectFn, and TARGET_UNIT_SRC_AREA_ALLY.
Validate()
bool spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
        {
            return ValidateSpellInfo({ SPELL_UNBOUND_PLAGUE, SPELL_UNBOUND_PLAGUE_SEARCHER });
        }
References SPELL_UNBOUND_PLAGUE, SPELL_UNBOUND_PLAGUE_SEARCHER, and _SpellScript::ValidateSpellInfo().