AzerothCore: CharacterActionIpLogger Class Reference
CharacterActionIpLogger Class Reference
Public Member Functions
CharacterActionIpLogger ()
void OnCreate (Player *player) override
void OnLogin (Player *player) override
void OnLogout (Player *player) override
void CharacterIPLogAction (Player *player, IPLoggingTypes aType)
Logs a number of actions done by players with an IP.
Public Member Functions inherited from PlayerScript
virtual void OnPlayerJustDied (Player *)
virtual void OnCalculateTalentsPoints (Player const *, uint32 &)
virtual void OnPlayerReleasedGhost (Player *)
virtual void OnSendInitialPacketsBeforeAddToMap (Player *, WorldPacket &)
virtual void OnBattlegroundDesertion (Player *, BattlegroundDesertionType const)
virtual void OnPlayerCompleteQuest (Player *, Quest const *)
virtual void OnPVPKill (Player *, Player *)
virtual void OnPlayerPVPFlagChange (Player *, bool)
virtual void OnCreatureKill (Player *, Creature *)
virtual void OnCreatureKilledByPet (Player *, Creature *)
virtual void OnPlayerKilledByCreature (Creature *, Player *)
virtual void OnLevelChanged (Player *, uint8)
virtual void OnFreeTalentPointsChanged (Player *, uint32)
virtual void OnTalentsReset (Player *, bool)
virtual void OnAfterSpecSlotChanged (Player *, uint8)
virtual void OnBeforeUpdate (Player *, uint32)
virtual void OnUpdate (Player *, uint32)
virtual void OnMoneyChanged (Player *, int32 &)
virtual void OnBeforeLootMoney (Player *, Loot *)
virtual void OnGiveXP (Player *, uint32 &, Unit *, uint8)
virtual bool OnReputationChange (Player *, uint32, int32 &, bool)
virtual void OnReputationRankChange (Player *, uint32, ReputationRank, ReputationRank, bool)
virtual void OnLearnSpell (Player *, uint32)
virtual void OnForgotSpell (Player *, uint32)
virtual void OnDuelRequest (Player *, Player *)
virtual void OnDuelStart (Player *, Player *)
virtual void OnDuelEnd (Player *, Player *, DuelCompleteType)
virtual void OnChat (Player *, uint32, uint32, std::string &)
virtual void OnBeforeSendChatMessage (Player *, uint32 &, uint32 &, std::string &)
virtual void OnChat (Player *, uint32, uint32, std::string &, Player *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Group *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Guild *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Channel *)
virtual void OnEmote (Player *, uint32)
virtual void OnTextEmote (Player *, uint32, uint32, ObjectGuid)
virtual void OnSpellCast (Player *, Spell *, bool)
virtual void OnLoadFromDB (Player *)
virtual void OnLogin (Player *)
virtual void OnBeforeLogout (Player *)
virtual void OnLogout (Player *)
virtual void OnCreate (Player *)
virtual void OnDelete (ObjectGuid, uint32)
virtual void OnFailedDelete (ObjectGuid, uint32)
virtual void OnSave (Player *)
virtual void OnBindToInstance (Player *, Difficulty, uint32, bool)
virtual void OnUpdateZone (Player *, uint32, uint32)
virtual void OnUpdateArea (Player *, uint32, uint32)
virtual void OnMapChanged (Player *)
virtual bool OnBeforeTeleport (Player *, uint32, float, float, float, float, uint32, Unit *)
virtual void OnUpdateFaction (Player *)
virtual void OnAddToBattleground (Player *, Battleground *)
virtual void OnQueueRandomDungeon (Player *, uint32 &)
virtual void OnRemoveFromBattleground (Player *, Battleground *)
virtual void OnAchiComplete (Player *, AchievementEntry const *)
virtual bool OnBeforeAchiComplete (Player *, AchievementEntry const *)
virtual void OnCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual bool OnBeforeCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual void OnAchiSave (CharacterDatabaseTransaction, Player *, uint16, CompletedAchievementData)
virtual void OnCriteriaSave (CharacterDatabaseTransaction, Player *, uint16, CriteriaProgress)
virtual void OnGossipSelect (Player *, uint32, uint32, uint32)
virtual void OnGossipSelectCode (Player *, uint32, uint32, uint32, const char *)
virtual void OnBeingCharmed (Player *, Unit *, uint32, uint32)
virtual void OnAfterSetVisibleItemSlot (Player *, uint8, Item *)
virtual void OnAfterMoveItemFromInventory (Player *, Item *, uint8, uint8, bool)
virtual void OnEquip (Player *, Item *, uint8, uint8, bool)
virtual void OnPlayerJoinBG (Player *)
virtual void OnPlayerJoinArena (Player *)
virtual void OnGetMaxPersonalArenaRatingRequirement (Player const *, uint32, uint32 &) const
virtual void OnLootItem (Player *, Item *, uint32, ObjectGuid)
virtual void OnBeforeFillQuestLootItem (Player *, LootItem &)
virtual void OnStoreNewItem (Player *, Item *, uint32)
virtual void OnCreateItem (Player *, Item *, uint32)
virtual void OnQuestRewardItem (Player *, Item *, uint32)
virtual bool CanPlaceAuctionBid (Player *, AuctionEntry *)
virtual void OnGroupRollRewardItem (Player *, Item *, uint32, RollVote, Roll *)
virtual bool OnBeforeOpenItem (Player *, Item *)
virtual bool OnBeforeQuestComplete (Player *, uint32)
virtual void OnQuestComputeXP (Player *, Quest const *, uint32 &)
virtual void OnBeforeDurabilityRepair (Player *, ObjectGuid, ObjectGuid, float &, uint8)
virtual void OnBeforeBuyItemFromVendor (Player *, ObjectGuid, uint32, uint32 &, uint8, uint8, uint8)
virtual void OnBeforeStoreOrEquipNewItem (Player *, uint32, uint32 &, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnAfterStoreOrEquipNewItem (Player *, uint32, Item *, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnAfterUpdateMaxPower (Player *, Powers &, float &)
virtual void OnAfterUpdateMaxHealth (Player *, float &)
virtual void OnBeforeUpdateAttackPowerAndDamage (Player *, float &, float &, bool)
virtual void OnAfterUpdateAttackPowerAndDamage (Player *, float &, float &, float &, float &, bool)
virtual void OnBeforeInitTalentForLevel (Player *, uint8 &, uint32 &)
virtual void OnFirstLogin (Player *)
virtual void OnSetMaxLevel (Player *, uint32 &)
virtual bool CanJoinInBattlegroundQueue (Player *, ObjectGuid, BattlegroundTypeId, uint8, GroupJoinBattlegroundResult &)
virtual bool ShouldBeRewardedWithMoneyInsteadOfExp (Player *)
virtual void OnBeforeTempSummonInitStats (Player *, TempSummon *, uint32 &)
virtual void OnBeforeGuardianInitStatsForLevel (Player *, Guardian *, CreatureTemplate const *, PetType &)
virtual void OnAfterGuardianInitStatsForLevel (Player *, Guardian *)
virtual void OnBeforeLoadPetFromDB (Player *, uint32 &, uint32 &, bool &, bool &)
virtual bool CanJoinInArenaQueue (Player *, ObjectGuid, uint8, BattlegroundTypeId, uint8, uint8, GroupJoinBattlegroundResult &)
virtual bool CanBattleFieldPort (Player *, uint8, BattlegroundTypeId, uint8)
virtual bool CanGroupInvite (Player *, std::string &)
virtual bool CanGroupAccept (Player *, Group *)
virtual bool CanSellItem (Player *, Item *, Creature *)
virtual bool CanSendMail (Player *, ObjectGuid, ObjectGuid, std::string &, std::string &, uint32, uint32, Item *)
virtual void PetitionBuy (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void PetitionShowList (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void OnRewardKillRewarder (Player *, KillRewarder *, bool, float &)
virtual bool CanGiveMailRewardAtGiveLevel (Player *, uint8)
virtual void OnDeleteFromDB (CharacterDatabaseTransaction, uint32)
virtual bool CanRepopAtGraveyard (Player *)
virtual Optional< bool > OnPlayerIsClass (Player const *, Classes, ClassContext)
virtual void OnGetMaxSkillValue (Player *, uint32, int32 &, bool)
virtual bool OnPlayerHasActivePowerType (Player const *, Powers)
virtual void OnUpdateGatheringSkill (Player *, uint32, uint32, uint32, uint32, uint32, uint32 &)
This hook called before gathering skill gain is applied to the character.
virtual void OnUpdateCraftingSkill (Player *, SkillLineAbilityEntry const *, uint32, uint32 &)
This hook is called before crafting skill gain is applied to the character.
virtual bool OnUpdateFishingSkill (Player *, int32, int32, int32, int32)
virtual bool CanAreaExploreAndOutdoor (Player *)
virtual void OnVictimRewardBefore (Player *, Player *, uint32 &, uint32 &)
virtual void OnVictimRewardAfter (Player *, Player *, uint32 &, uint32 &, float &)
virtual void OnCustomScalingStatValueBefore (Player *, ItemTemplate const *, uint8, bool, uint32 &)
virtual void OnCustomScalingStatValue (Player *, ItemTemplate const *, uint32 &, int32 &, uint8, uint32, ScalingStatValuesEntry const *)
virtual void OnApplyItemModsBefore (Player *, uint8, bool, uint8, uint32, int32 &)
virtual void OnApplyEnchantmentItemModsBefore (Player *, Item *, EnchantmentSlot, bool, uint32, uint32 &)
virtual void OnApplyWeaponDamage (Player *, uint8, ItemTemplate const *, float &, float &, uint8)
virtual bool CanArmorDamageModifier (Player *)
virtual void OnGetFeralApBonus (Player *, int32 &, int32, ItemTemplate const *, ScalingStatValuesEntry const *)
virtual bool CanApplyWeaponDependentAuraDamageMod (Player *, Item *, WeaponAttackType, AuraEffect const *, bool)
virtual bool CanApplyEquipSpell (Player *, SpellInfo const *, Item *, bool, bool)
virtual bool CanApplyEquipSpellsItemSet (Player *, ItemSetEffect *)
virtual bool CanCastItemCombatSpell (Player *, Unit *, WeaponAttackType, uint32, uint32, Item *, ItemTemplate const *)
virtual bool CanCastItemUseSpell (Player *, Item *, SpellCastTargets const &, uint8, uint32)
virtual void OnApplyAmmoBonuses (Player *, ItemTemplate const *, float &)
virtual bool CanEquipItem (Player *, uint8, uint16 &, Item *, bool, bool)
virtual bool CanUnequipItem (Player *, uint16, bool)
virtual bool CanUseItem (Player *, ItemTemplate const *, InventoryResult &)
virtual bool CanSaveEquipNewItem (Player *, Item *, uint16, bool)
virtual bool CanApplyEnchantment (Player *, Item *, EnchantmentSlot, bool, bool, bool)
virtual void OnGetQuestRate (Player *, float &)
virtual bool PassedQuestKilledMonsterCredit (Player *, Quest const *, uint32, uint32, ObjectGuid)
virtual bool CheckItemInSlotAtLoadInventory (Player *, Item *, uint8, uint8 &, uint16 &)
virtual bool NotAvoidSatisfy (Player *, DungeonProgressionRequirements const *, uint32, bool)
virtual bool NotVisibleGloballyFor (Player *, Player const *)
virtual void OnGetArenaPersonalRating (Player *, uint8, uint32 &)
virtual void OnGetArenaTeamId (Player *, uint8, uint32 &)
virtual void OnIsFFAPvP (Player *, bool &)
virtual void OnFfaPvpStateUpdate (Player *, bool)
virtual void OnIsPvP (Player *, bool &)
virtual void OnGetMaxSkillValueForLevel (Player *, uint16 &)
virtual bool NotSetArenaTeamInfoField (Player *, uint8, ArenaTeamInfoType, uint32)
virtual bool CanJoinLfg (Player *, uint8, std::set< uint32 > &, const std::string &)
virtual bool CanEnterMap (Player *, MapEntry const *, InstanceTemplate const *, MapDifficulty const *, bool)
virtual bool CanInitTrade (Player *, Player *)
virtual bool CanSetTradeItem (Player *, Item *, uint8)
This hook called just before finishing the handling of the action of a player setting an item in a trade slot.
virtual void OnSetServerSideVisibility (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnSetServerSideVisibilityDetect (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnPlayerResurrect (Player *, float, bool)
virtual void OnBeforeChooseGraveyard (Player *, TeamId, bool, uint32 &)
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &)
This hook called before player sending message in default chat.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Player *)
This hook called before player sending message to other player via private.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Group *)
This hook called before player sending message to group.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Guild *)
This hook called before player sending message to guild.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Channel *)
This hook called before player sending message to channel.
virtual void OnPlayerLearnTalents (Player *, uint32, uint32, uint32)
This hook called after player learning talents.
virtual void OnPlayerEnterCombat (Player *, Unit *)
This hook called after player entering combat.
virtual void OnPlayerLeaveCombat (Player *)
This hook called after player leave combat.
virtual void OnQuestAbandon (Player *, uint32)
This hook called after player abandoning quest.
virtual bool OnCanPlayerFlyInZone (Player *, uint32, uint32, SpellInfo const *)
This hook called before other CanFlyChecks are applied.
virtual void AnticheatSetCanFlybyServer (Player *, bool)
virtual void AnticheatSetUnderACKmount (Player *)
virtual void AnticheatSetRootACKUpd (Player *)
virtual void AnticheatSetJumpingbyOpcode (Player *, bool)
virtual void AnticheatUpdateMovementInfo (Player *, MovementInfo const &)
virtual bool AnticheatHandleDoubleJump (Player *, Unit *)
virtual bool AnticheatCheckMovementInfo (Player *, MovementInfo const &, Unit *, bool)
virtual bool CanSendErrorAlreadyLooted (Player *)
This hook is called, to avoid displaying the error message that the body has already been stripped.
virtual void OnAfterCreatureLoot (Player *)
It is used when an item is taken from a creature.
virtual void OnAfterCreatureLootMoney (Player *)
After a creature's money is taken.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from PlayerScript
PlayerScript (const char *name, std::vector< uint16 > enabledHooks=std::vector< uint16 >())
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
CharacterActionIpLogger()
CharacterActionIpLogger::CharacterActionIpLogger () inline
                              :
        PlayerScript("CharacterActionIpLogger",
        {
            PLAYERHOOK_ON_CREATE,
            PLAYERHOOK_ON_LOGIN,
            PLAYERHOOK_ON_LOGOUT
        })
    {
    }
References PLAYERHOOK_ON_CREATE, PLAYERHOOK_ON_LOGIN, and PLAYERHOOK_ON_LOGOUT.
Member Function Documentation
CharacterIPLogAction()
void CharacterActionIpLogger::CharacterIPLogAction (Player * player, IPLoggingTypes aType) inline
Logs a number of actions done by players with an IP.
    {
        if (!sWorld->getBoolConfig(CONFIG_IP_BASED_ACTION_LOGGING))
            return;
        // Action IP Logger is only intialized if config is set up
        // Else, this script isn't loaded in the first place: We require no config check.
        // We declare all the required variables
        uint32 playerGuid = player->GetSession()->GetAccountId();
        ObjectGuid::LowType characterGuid = player->GetGUID().GetCounter();
        const std::string currentIp = player->GetSession()->GetRemoteAddress();
        std::string systemNote = "ERROR"; // "ERROR" is a placeholder here. We change it...
        // ... with this switch, so that we have a more accurate phrasing of what type it is
        switch (aType)
        {
            case CHARACTER_CREATE:
                systemNote = "Logged on CharacterCreate";
                break;
            case CHARACTER_LOGIN:
                systemNote = "Logged on CharacterLogin";
                break;
            case CHARACTER_LOGOUT:
                systemNote = "Logged on CharacterLogout";
                break;
            case CHARACTER_DELETE:
                systemNote = "Logged on CharacterDelete";
                break;
            case CHARACTER_FAILED_DELETE:
                systemNote = "Logged on Failed CharacterDelete";
                break;
            // Neither should happen. Ever. Period. If it does, call Mythbusters.
            case UNKNOWN_ACTION:
            default:
                systemNote = "ERROR! Unknown action!";
                break;
        }
        // Once we have done everything, we can insert the new log.
        LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_CHAR_IP_LOGGING);
        stmt->SetData(0, playerGuid);
        stmt->SetData(1, characterGuid);
        stmt->SetData(2, aType);
        stmt->SetData(3, currentIp.c_str()); // We query the ip here.
        stmt->SetData(4, systemNote.c_str());
        // Seeing as the time differences should be minimal, we do not get unixtime and the timestamp right now;
        // Rather, we let it be added with the SQL query.
        LoginDatabase.Execute(stmt);
        return;
    }
References CHARACTER_CREATE, CHARACTER_DELETE, CHARACTER_FAILED_DELETE, CHARACTER_LOGIN, CHARACTER_LOGOUT, CONFIG_IP_BASED_ACTION_LOGGING, WorldSession::GetAccountId(), ObjectGuid::GetCounter(), Object::GetGUID(), WorldSession::GetRemoteAddress(), Player::GetSession(), LOGIN_INS_CHAR_IP_LOGGING, LoginDatabase, PreparedStatementBase::SetData(), sWorld, and UNKNOWN_ACTION.
Referenced by OnCreate(), OnLogin(), and OnLogout().
OnCreate()
void CharacterActionIpLogger::OnCreate (Player * player) inline override virtual
Reimplemented from PlayerScript.
    {
        CharacterIPLogAction(player, CHARACTER_CREATE);
    }
References CHARACTER_CREATE, and CharacterIPLogAction().
OnLogin()
void CharacterActionIpLogger::OnLogin (Player * player) inline override virtual
Reimplemented from PlayerScript.
    {
        CharacterIPLogAction(player, CHARACTER_LOGIN);
    }
References CHARACTER_LOGIN, and CharacterIPLogAction().
OnLogout()
void CharacterActionIpLogger::OnLogout (Player * player) inline override virtual
Reimplemented from PlayerScript.
    {
        CharacterIPLogAction(player, CHARACTER_LOGOUT);
    }
References CHARACTER_LOGOUT, and CharacterIPLogAction().