AzerothCore: go_ethereum_prison Class Reference
go_ethereum_prison Class Reference
Public Member Functions
go_ethereum_prison ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, GameObject *)
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnModifyHealth (GameObject *, Unit *, int32 &, SpellInfo const *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
go_ethereum_prison()
go_ethereum_prison::go_ethereum_prison () inline
: GameObjectScript("go_ethereum_prison") { }
Member Function Documentation
OnGossipHello()
bool go_ethereum_prison::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
    {
        int Random = rand() % (sizeof(NpcPrisonEntry) / sizeof(uint32));
        if (Creature* creature = player->SummonCreature(NpcPrisonEntry[Random], go->GetPositionX(), go->GetPositionY(), go->GetPositionZ(), go->GetAngle(player),
                                 TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000))
        {
            if (!creature->IsHostileTo(player))
            {
                uint32 Spell = 0;
                switch (creature->GetEntry())
                {
                    case 22811:
                        Spell = SPELL_REP_LC;
                        break;
                    case 22812:
                        Spell = SPELL_REP_SHAT;
                        break;
                    case 22810:
                        Spell = SPELL_REP_CE;
                        break;
                    case 22813:
                        Spell = SPELL_REP_CON;
                        break;
                    case 22815:
                        Spell = SPELL_REP_KT;
                        break;
                    case 22814:
                        Spell = SPELL_REP_SPOR;
                        break;
                }
                if (Spell)
                    creature->CastSpell(player, Spell, false);
            }
        }
        return false;
    }
References Position::GetAngle(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), NpcPrisonEntry, Random, SPELL_REP_CE, SPELL_REP_CON, SPELL_REP_KT, SPELL_REP_LC, SPELL_REP_SHAT, SPELL_REP_SPOR, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.