AzerothCore: AuctionHouseUsablePlayerInfo Struct Reference
AuctionHouseUsablePlayerInfo Struct Reference
#include "AuctionHouseSearcher.h"
Public Member Functions
bool PlayerCanUseItem (ItemTemplate const *proto) const
uint16 GetSkillValue (uint32 skill) const
bool HasSpell (uint32 spell) const
Public Attributes
uint32 classMask
uint32 raceMask
uint8 level
AuctionPlayerSkills skills
AuctionPlayerSpells spells
Detailed Description
Member Function Documentation
GetSkillValue()
uint16 AuctionHouseUsablePlayerInfo::GetSkillValue (uint32 skill) const
{
    if (!skill)
        return 0;
    AuctionPlayerSkills::const_iterator itr = skills.find(skill);
    if (itr == skills.end())
        return 0;
    return itr->second;
}
References skills.
Referenced by PlayerCanUseItem().
HasSpell()
bool AuctionHouseUsablePlayerInfo::HasSpell (uint32 spell) const
{
    AuctionPlayerSpells::const_iterator itr = spells.find(spell);
    return (itr != spells.end());
}
Referenced by PlayerCanUseItem().
PlayerCanUseItem()
bool AuctionHouseUsablePlayerInfo::PlayerCanUseItem (ItemTemplate const * proto) const
{
    uint32 itemSkill = proto->GetSkill();
    if (itemSkill != 0)
    {
        if (GetSkillValue(itemSkill) == 0)
            return false;
    }
    if ((proto->AllowableClass & classMask) == 0 || (proto->AllowableRace & raceMask) == 0)
        return false;
    if (proto->RequiredSkill != 0)
    {
        if (GetSkillValue(proto->RequiredSkill) == 0)
            return false;
        else if (GetSkillValue(proto->RequiredSkill) < proto->RequiredSkillRank)
            return false;
    }
    if (proto->RequiredSpell != 0 && !HasSpell(proto->RequiredSpell))
        return false;
    if (level < proto->RequiredLevel)
        return false;
    if (proto->Spells[0].SpellId)
    {
        // this check is for vanilla recipies. Spells are learned through individual learning spells instead of spell 483 and 55884
        SpellEntry const* spellEntry = sSpellStore.LookupEntry(proto->Spells[0].SpellId);
        if (spellEntry && spellEntry->Effect[0] == SPELL_EFFECT_LEARN_SPELL && spellEntry->EffectTriggerSpell[0])
            if (HasSpell(spellEntry->EffectTriggerSpell[0]))
                return false;
        // this check is for tbc/wotlk recipies. Spells are learned through 483 and 55884, the second spell in the item will be the actual spell learned.
        if (proto->Spells[0].SpellId == 483 || proto->Spells[0].SpellId == 55884)
            if (HasSpell(proto->Spells[1].SpellId))
                return false;
    }
    return true;
}
References ItemTemplate::AllowableClass, ItemTemplate::AllowableRace, classMask, SpellEntry::Effect, SpellEntry::EffectTriggerSpell, ItemTemplate::GetSkill(), GetSkillValue(), HasSpell(), raceMask, ItemTemplate::RequiredSkill, ItemTemplate::RequiredSkillRank, ItemTemplate::RequiredSpell, SPELL_EFFECT_LEARN_SPELL, _Spell::SpellId, ItemTemplate::Spells, and sSpellStore.
Member Data Documentation
classMask
uint32 AuctionHouseUsablePlayerInfo::classMask
Referenced by PlayerCanUseItem().
level
uint8 AuctionHouseUsablePlayerInfo::level
raceMask
uint32 AuctionHouseUsablePlayerInfo::raceMask
Referenced by PlayerCanUseItem().
skills
AuctionPlayerSkills AuctionHouseUsablePlayerInfo::skills
Referenced by GetSkillValue(), and WorldSession::HandleAuctionListItems().
spells
AuctionPlayerSpells AuctionHouseUsablePlayerInfo::spells
Referenced by WorldSession::HandleAuctionListItems().