AzerothCore: instance_oculus::instance_oculus_InstanceMapScript Struct Reference
instance_oculus::instance_oculus_InstanceMapScript Struct Reference
Public Member Functions
instance_oculus_InstanceMapScript (Map *pMap)
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnGameObjectCreate (GameObject *pGo) override
void OnPlayerEnter (Player *player) override
void OnUnitDeath (Unit *unit) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 identifier) const override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
ObjectGuid DragonCageDoorGUID [3]
ObjectGuid EregosCacheGUID
uint32 CentrifugeCount
ObjectGuid uiDrakosGUID
ObjectGuid uiVarosGUID
ObjectGuid uiUromGUID
ObjectGuid uiEregosGUID
bool bAmberVoid
bool bEmeraldVoid
bool bRubyVoid
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_oculus_InstanceMapScript()
instance_oculus::instance_oculus_InstanceMapScript::instance_oculus_InstanceMapScript (Map * pMap) inline
: InstanceScript(pMap) { Initialize(); }
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_oculus::instance_oculus_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case CRITERIA_EXPERIENCED_AMBER:
                    if (source)
                        if (Unit* drake = source->GetVehicleBase())
                            if (drake->GetEntry() == NPC_AMBER_DRAKE )
                                return true;
                    break;
                case CRITERIA_EXPERIENCED_EMERALD:
                    if (source)
                        if (Unit* drake = source->GetVehicleBase())
                            if (drake->GetEntry() == NPC_EMERALD_DRAKE )
                                return true;
                    break;
                case CRITERIA_EXPERIENCED_RUBY:
                    if (source)
                        if (Unit* drake = source->GetVehicleBase())
                            if (drake->GetEntry() == NPC_RUBY_DRAKE )
                                return true;
                    break;
                case CRITERIA_AMBER_VOID:
                    return bAmberVoid;
                case CRITERIA_EMERALD_VOID:
                    return bEmeraldVoid;
                case CRITERIA_RUBY_VOID:
                    return bRubyVoid;
            }
            return false;
        }
References bAmberVoid, bEmeraldVoid, bRubyVoid, CRITERIA_AMBER_VOID, CRITERIA_EMERALD_VOID, CRITERIA_EXPERIENCED_AMBER, CRITERIA_EXPERIENCED_EMERALD, CRITERIA_EXPERIENCED_RUBY, CRITERIA_RUBY_VOID, Unit::GetVehicleBase(), NPC_AMBER_DRAKE, NPC_EMERALD_DRAKE, and NPC_RUBY_DRAKE.
GetData()
uint32 instance_oculus::instance_oculus_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_DRAKOS:
                case DATA_VAROS:
                case DATA_UROM:
                case DATA_EREGOS:
                    return m_auiEncounter[type];
                case DATA_CC_COUNT:
                    return CentrifugeCount;
            }
            return 0;
        }
References CentrifugeCount, DATA_CC_COUNT, DATA_DRAKOS, DATA_EREGOS, DATA_UROM, DATA_VAROS, and m_auiEncounter.
GetGuidData()
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::GetGuidData (uint32 identifier) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (identifier)
            {
                case DATA_DRAKOS:
                    return uiDrakosGUID;
                case DATA_VAROS:
                    return uiVarosGUID;
                case DATA_UROM:
                    return uiUromGUID;
                case DATA_EREGOS:
                    return uiEregosGUID;
                case DATA_DCD_1:
                case DATA_DCD_2:
                case DATA_DCD_3:
                    return DragonCageDoorGUID[identifier - 100];
            }
            return ObjectGuid::Empty;
        }
References DATA_DCD_1, DATA_DCD_2, DATA_DCD_3, DATA_DRAKOS, DATA_EREGOS, DATA_UROM, DATA_VAROS, DragonCageDoorGUID, ObjectGuid::Empty, uiDrakosGUID, uiEregosGUID, uiUromGUID, and uiVarosGUID.
Initialize()
void instance_oculus::instance_oculus_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetHeaders(DataHeader);
            CentrifugeCount = 0;
            bAmberVoid = false;
            bEmeraldVoid = false;
            bRubyVoid = false;
            memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
        }
References bAmberVoid, bEmeraldVoid, bRubyVoid, CentrifugeCount, DataHeader, m_auiEncounter, and InstanceScript::SetHeaders().
Referenced by instance_oculus_InstanceMapScript().
OnCreatureCreate()
void instance_oculus::instance_oculus_InstanceMapScript::OnCreatureCreate (Creature * pCreature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (pCreature->GetEntry())
            {
                case NPC_DRAKOS:
                    uiDrakosGUID = pCreature->GetGUID();
                    break;
                case NPC_VAROS:
                    uiVarosGUID = pCreature->GetGUID();
                    break;
                case NPC_UROM:
                    uiUromGUID = pCreature->GetGUID();
                    break;
                case NPC_EREGOS:
                    uiEregosGUID = pCreature->GetGUID();
                    break;
            }
        }
References Object::GetEntry(), Object::GetGUID(), NPC_DRAKOS, NPC_EREGOS, NPC_UROM, NPC_VAROS, uiDrakosGUID, uiEregosGUID, uiUromGUID, and uiVarosGUID.
OnGameObjectCreate()
void instance_oculus::instance_oculus_InstanceMapScript::OnGameObjectCreate (GameObject * pGo) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (pGo->GetEntry())
            {
                case GO_DRAGON_CAGE_DOOR:
                    for( uint8 i = 0; i < 3; ++i )
                    {
                        if (DragonCageDoorGUID[i])
                            continue;
                        DragonCageDoorGUID[i] = pGo->GetGUID();
                        break;
                    }
                    if (m_auiEncounter[DATA_DRAKOS] == DONE)
                        if (pGo->GetGoState() != GO_STATE_ACTIVE )
{
                            pGo->SetLootState(GO_READY);
                            pGo->UseDoorOrButton(0, false);
                        }
                    break;
                case GO_CACHE_OF_EREGOS:
                case GO_CACHE_OF_EREGOS_HERO:
                    EregosCacheGUID = pGo->GetGUID();
                    break;
            }
        }
References DATA_DRAKOS, DONE, DragonCageDoorGUID, EregosCacheGUID, Object::GetEntry(), GameObject::GetGoState(), Object::GetGUID(), GO_CACHE_OF_EREGOS, GO_CACHE_OF_EREGOS_HERO, GO_DRAGON_CAGE_DOOR, GO_READY, GO_STATE_ACTIVE, m_auiEncounter, GameObject::SetLootState(), and GameObject::UseDoorOrButton().
OnPlayerEnter()
void instance_oculus::instance_oculus_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
        {
            if (m_auiEncounter[DATA_DRAKOS] == DONE && m_auiEncounter[DATA_VAROS] != DONE)
            {
                player->SendUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW, 1);
                player->SendUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, 10 - CentrifugeCount);
            }
            else
            {
                player->SendUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW, 0);
                player->SendUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, 0);
            }
        }
References CentrifugeCount, DATA_DRAKOS, DATA_VAROS, DONE, m_auiEncounter, Player::SendUpdateWorldState(), WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, and WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW.
OnUnitDeath()
void instance_oculus::instance_oculus_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            if (unit->GetEntry() == NPC_CENTRIFUGE_CONSTRUCT)
                SetData(DATA_CC_COUNT, DONE);
        }
References DATA_CC_COUNT, DONE, Object::GetEntry(), NPC_CENTRIFUGE_CONSTRUCT, and SetData().
ReadSaveDataMore()
void instance_oculus::instance_oculus_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> m_auiEncounter[0];
            data >> m_auiEncounter[1];
            data >> m_auiEncounter[2];
            data >> m_auiEncounter[3];
            data >> CentrifugeCount;
        }
References CentrifugeCount, and m_auiEncounter.
SetData()
void instance_oculus::instance_oculus_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_DRAKOS:
                    m_auiEncounter[DATA_DRAKOS] = data;
                    if (data == DONE)
                    {
                        DoUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW, 1);
                        DoUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, 10 - CentrifugeCount);
                        if (instance->IsHeroic())
                            DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_MAKE_IT_COUNT_TIMED_EVENT);
                    }
                    break;
                case DATA_VAROS:
                    m_auiEncounter[DATA_VAROS] = data;
                    if (data == DONE)
                    {
                        DoUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW, 0);
                        if (Creature* urom = instance->GetCreature(uiUromGUID))
                            urom->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    }
                    break;
                case DATA_UROM:
                    m_auiEncounter[DATA_UROM] = data;
                    if (data == DONE)
                        if (Creature* eregos = instance->GetCreature(uiEregosGUID))
                            eregos->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    break;
                case DATA_EREGOS:
                    m_auiEncounter[DATA_EREGOS] = data;
                    if (data == DONE)
                    {
                        DoRespawnGameObject(EregosCacheGUID, 7 * DAY);
                        if (GameObject* cache = instance->GetGameObject(EregosCacheGUID))
{
                            if (Creature* eregos = instance->GetCreature(uiEregosGUID))
{
                                cache->SetLootRecipient(eregos);
                            }
                        }
                    }
                    break;
                case DATA_CC_COUNT:
                    if (CentrifugeCount < 10)
                    {
                        ++CentrifugeCount;
                        DoUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, 10 - CentrifugeCount);
                    }
                    if (CentrifugeCount >= 10)
                        if (Creature* varos = instance->GetCreature(uiVarosGUID))
{
                            varos->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            varos->InterruptNonMeleeSpells(false);
                            varos->RemoveAura(50053);
                        }
                    break;
                case DATA_AMBER_VOID:
                    bAmberVoid = !!data;
                    break;
                case DATA_EMERALD_VOID:
                    bEmeraldVoid = !!data;
                    break;
                case DATA_RUBY_VOID:
                    bRubyVoid = !!data;
                    break;
            }
            if (data == DONE)
                SaveToDB();
        }
References ACHIEV_MAKE_IT_COUNT_TIMED_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, bAmberVoid, bEmeraldVoid, bRubyVoid, CentrifugeCount, DATA_AMBER_VOID, DATA_CC_COUNT, DATA_DRAKOS, DATA_EMERALD_VOID, DATA_EREGOS, DATA_RUBY_VOID, DATA_UROM, DATA_VAROS, DAY, DONE, InstanceScript::DoRespawnGameObject(), InstanceScript::DoStartTimedAchievement(), InstanceScript::DoUpdateWorldState(), EregosCacheGUID, Map::GetCreature(), Map::GetGameObject(), InstanceScript::instance, Map::IsHeroic(), m_auiEncounter, InstanceScript::SaveToDB(), uiEregosGUID, uiUromGUID, uiVarosGUID, UNIT_FLAG_NON_ATTACKABLE, WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, and WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW.
Referenced by OnUnitDeath().
WriteSaveDataMore()
void instance_oculus::instance_oculus_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << m_auiEncounter[0] << ' '
                << m_auiEncounter[1] << ' '
                << m_auiEncounter[2] << ' '
                << m_auiEncounter[3] << ' '
                << CentrifugeCount;
        }
References CentrifugeCount, and m_auiEncounter.
Member Data Documentation
bAmberVoid
bool instance_oculus::instance_oculus_InstanceMapScript::bAmberVoid
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
bEmeraldVoid
bool instance_oculus::instance_oculus_InstanceMapScript::bEmeraldVoid
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
bRubyVoid
bool instance_oculus::instance_oculus_InstanceMapScript::bRubyVoid
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
CentrifugeCount
uint32 instance_oculus::instance_oculus_InstanceMapScript::CentrifugeCount
Referenced by GetData(), Initialize(), OnPlayerEnter(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
DragonCageDoorGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::DragonCageDoorGUID[3]
Referenced by GetGuidData(), and OnGameObjectCreate().
EregosCacheGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::EregosCacheGUID
Referenced by OnGameObjectCreate(), and SetData().
m_auiEncounter
uint32 instance_oculus::instance_oculus_InstanceMapScript::m_auiEncounter[MAX_ENCOUNTER]
Referenced by GetData(), Initialize(), OnGameObjectCreate(), OnPlayerEnter(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
uiDrakosGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::uiDrakosGUID
Referenced by GetGuidData(), and OnCreatureCreate().
uiEregosGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::uiEregosGUID
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().
uiUromGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::uiUromGUID
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().
uiVarosGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::uiVarosGUID
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().