AzerothCore: MMapTargetData Class Reference
MMapTargetData Class Reference
#include "UnitUtils.h"
Public Member Functions
MMapTargetData ()=default
MMapTargetData (uint32 endTime, const Position *o, const Position *t)
MMapTargetData (const MMapTargetData &c)
MMapTargetData (MMapTargetData &&)=default
MMapTargetData & operator= (const MMapTargetData &)=default
MMapTargetData & operator= (MMapTargetData &&)=default
bool PosChanged (const Position &o, const Position &t) const
Public Attributes
uint32 _endTime
Position _posOwner
Position _posTarget
Detailed Description
Constructor & Destructor Documentation
MMapTargetData() [1/4]
MMapTargetData::MMapTargetData () default
MMapTargetData() [2/4]
MMapTargetData::MMapTargetData (uint32 endTime, const Position * o, const Position * t) inline
    {
        _endTime = endTime;
        _posOwner.Relocate(o);
        _posTarget.Relocate(t);
    }
References _endTime, _posOwner, _posTarget, and Position::Relocate().
MMapTargetData() [3/4]
MMapTargetData::MMapTargetData (const MMapTargetData & c) inline
    {
        _endTime = c._endTime;
        _posOwner.Relocate(c._posOwner);
        _posTarget.Relocate(c._posTarget);
    }
References _endTime, _posOwner, _posTarget, and Position::Relocate().
MMapTargetData() [4/4]
MMapTargetData::MMapTargetData (MMapTargetData &&) default
Member Function Documentation
operator=() [1/2]
MMapTargetData & MMapTargetData::operator= (const MMapTargetData &) default
operator=() [2/2]
MMapTargetData & MMapTargetData::operator= (MMapTargetData &&) default
PosChanged()
bool MMapTargetData::PosChanged (const Position & o, const Position & t) const inline
    {
        return _posOwner.GetExactDistSq(&o) > 0.5f * 0.5f || _posTarget.GetExactDistSq(&t) > 0.5f * 0.5f;
    }
References _posOwner, _posTarget, and Position::GetExactDistSq().
Member Data Documentation
_endTime
uint32 MMapTargetData::_endTime
Referenced by MMapTargetData().
_posOwner
Position MMapTargetData::_posOwner
Referenced by MMapTargetData(), and PosChanged().
_posTarget
Position MMapTargetData::_posTarget
Referenced by MMapTargetData(), and PosChanged().