AzerothCore: EmblemInfo Class Reference
EmblemInfo Class Reference
#include "Guild.h"
Public Member Functions
EmblemInfo ()
void LoadFromDB (Field *fields)
void SaveToDB (uint32 guildId) const
void ReadPacket (WorldPackets::Guild::SaveGuildEmblem &packet)
uint32 GetStyle () const
uint32 GetColor () const
uint32 GetBorderStyle () const
uint32 GetBorderColor () const
uint32 GetBackgroundColor () const
Private Attributes
uint32 m_style
uint32 m_color
uint32 m_borderStyle
uint32 m_borderColor
uint32 m_backgroundColor
Detailed Description
Constructor & Destructor Documentation
EmblemInfo()
EmblemInfo::EmblemInfo () inline
: m_style(0), m_color(0), m_borderStyle(0), m_borderColor(0), m_backgroundColor(0) { }
Member Function Documentation
GetBackgroundColor()
uint32 EmblemInfo::GetBackgroundColor () const inline
{ return m_backgroundColor; }
References m_backgroundColor.
Referenced by Guild::Create(), Guild::HandleQuery(), and WorldSession::HandleSaveGuildEmblemOpcode().
GetBorderColor()
uint32 EmblemInfo::GetBorderColor () const inline
{ return m_borderColor; }
References m_borderColor.
Referenced by Guild::Create(), Guild::HandleQuery(), and WorldSession::HandleSaveGuildEmblemOpcode().
GetBorderStyle()
uint32 EmblemInfo::GetBorderStyle () const inline
{ return m_borderStyle; }
References m_borderStyle.
Referenced by Guild::Create(), Guild::HandleQuery(), and WorldSession::HandleSaveGuildEmblemOpcode().
GetColor()
uint32 EmblemInfo::GetColor () const inline
{ return m_color; }
References m_color.
Referenced by Guild::Create(), Guild::HandleQuery(), and WorldSession::HandleSaveGuildEmblemOpcode().
GetStyle()
uint32 EmblemInfo::GetStyle () const inline
{ return m_style; }
References m_style.
Referenced by Guild::Create(), Guild::HandleQuery(), and WorldSession::HandleSaveGuildEmblemOpcode().
LoadFromDB()
void EmblemInfo::LoadFromDB (Field * fields)
{
    m_style             = fields[3].Get<uint8>();
    m_color             = fields[4].Get<uint8>();
    m_borderStyle       = fields[5].Get<uint8>();
    m_borderColor       = fields[6].Get<uint8>();
    m_backgroundColor   = fields[7].Get<uint8>();
}
References Field::Get().
Referenced by Guild::LoadFromDB().
ReadPacket()
void EmblemInfo::ReadPacket (WorldPackets::Guild::SaveGuildEmblem & packet)
{
    m_style = packet.EStyle;
    m_color = packet.EColor;
    m_borderStyle = packet.BStyle;
    m_borderColor = packet.BColor;
    m_backgroundColor = packet.Bg;
}
References WorldPackets::Guild::SaveGuildEmblem::BColor, WorldPackets::Guild::SaveGuildEmblem::Bg, WorldPackets::Guild::SaveGuildEmblem::BStyle, WorldPackets::Guild::SaveGuildEmblem::EColor, and WorldPackets::Guild::SaveGuildEmblem::EStyle.
Referenced by WorldSession::HandleSaveGuildEmblemOpcode().
SaveToDB()
void EmblemInfo::SaveToDB (uint32 guildId) const
{
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_EMBLEM_INFO);
    stmt->SetData(0, m_style);
    stmt->SetData(1, m_color);
    stmt->SetData(2, m_borderStyle);
    stmt->SetData(3, m_borderColor);
    stmt->SetData(4, m_backgroundColor);
    stmt->SetData(5, guildId);
    CharacterDatabase.Execute(stmt);
}
References CHAR_UPD_GUILD_EMBLEM_INFO, CharacterDatabase, and PreparedStatementBase::SetData().
Referenced by Guild::HandleSetEmblem().
Member Data Documentation
m_backgroundColor
uint32 EmblemInfo::m_backgroundColor private
Referenced by GetBackgroundColor().
m_borderColor
uint32 EmblemInfo::m_borderColor private
Referenced by GetBorderColor().
m_borderStyle
uint32 EmblemInfo::m_borderStyle private
Referenced by GetBorderStyle().
m_color
uint32 EmblemInfo::m_color private
Referenced by GetColor().
m_style
uint32 EmblemInfo::m_style private
Referenced by GetStyle().