AzerothCore: CalendarInvite Struct Reference
CalendarInvite Struct Reference
#include "CalendarMgr.h"
Public Member Functions
CalendarInvite (CalendarInvite const &calendarInvite, uint64 inviteId, uint64 eventId)
CalendarInvite ()
CalendarInvite (uint64 inviteId, uint64 eventId, ObjectGuid invitee, ObjectGuid senderGUID, time_t statusTime, CalendarInviteStatus status, CalendarModerationRank rank, std::string text)
~CalendarInvite ()
void SetInviteId (uint64 inviteId)
uint64 GetInviteId () const
void SetEventId (uint64 eventId)
uint64 GetEventId () const
void SetSenderGUID (ObjectGuid guid)
ObjectGuid GetSenderGUID () const
void SetInvitee (ObjectGuid guid)
ObjectGuid GetInviteeGUID () const
void SetStatusTime (time_t statusTime)
time_t GetStatusTime () const
void SetText (const std::string &text)
std::string GetText () const
void SetStatus (CalendarInviteStatus status)
CalendarInviteStatus GetStatus () const
void SetRank (CalendarModerationRank rank)
CalendarModerationRank GetRank () const
Private Attributes
uint64 _inviteId
uint64 _eventId
ObjectGuid _invitee
ObjectGuid _senderGUID
time_t _statusTime
CalendarInviteStatus _status
CalendarModerationRank _rank
std::string _text
Detailed Description
Constructor & Destructor Documentation
CalendarInvite() [1/3]
CalendarInvite::CalendarInvite (CalendarInvite const & calendarInvite, uint64 inviteId, uint64 eventId) inline
    {
        _inviteId = inviteId;
        _eventId = eventId;
        _invitee = calendarInvite.GetInviteeGUID();
        _senderGUID = calendarInvite.GetSenderGUID();
        _statusTime = calendarInvite.GetStatusTime();
        _status = calendarInvite.GetStatus();
        _rank = calendarInvite.GetRank();
        _text = calendarInvite.GetText();
    }
References _eventId, _invitee, _inviteId, _rank, _senderGUID, _status, _statusTime, _text, GetInviteeGUID(), GetRank(), GetSenderGUID(), GetStatus(), GetStatusTime(), and GetText().
CalendarInvite() [2/3]
CalendarInvite::CalendarInvite ()
                               : _inviteId(1), _eventId(0), _statusTime(GameTime::GetGameTime().count()),
_status(CALENDAR_STATUS_INVITED), _rank(CALENDAR_RANK_PLAYER), _text("") { }
CalendarInvite() [3/3]
CalendarInvite::CalendarInvite (uint64 inviteId, uint64 eventId, ObjectGuid invitee, ObjectGuid senderGUID, time_t statusTime, CalendarInviteStatus status, CalendarModerationRank rank, std::string text) inline
                                                                                             :
        _inviteId(inviteId), _eventId(eventId), _invitee(invitee), _senderGUID(senderGUID), _statusTime(statusTime),
        _status(status), _rank(rank), _text(text) { }
~CalendarInvite()
CalendarInvite::~CalendarInvite ()
{
    // Free _inviteId only if it's a real invite and not just a pre-invite or guild announcement
    if (_inviteId != 0 && _eventId != 0)
        sCalendarMgr->FreeInviteId(_inviteId);
}
References _eventId, _inviteId, and sCalendarMgr.
Member Function Documentation
GetEventId()
uint64 CalendarInvite::GetEventId () const inline
{ return _eventId; }
References _eventId.
Referenced by CalendarMgr::AddInvite(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteRemove(), CalendarMgr::SendCalendarEventModeratorStatusAlert(), and CalendarMgr::UpdateInvite().
GetInviteeGUID()
ObjectGuid CalendarInvite::GetInviteeGUID () const inline
{ return _invitee; }
References _invitee.
Referenced by CalendarMgr::AddInvite(), CalendarInvite(), CalendarMgr::RemoveEvent(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventInviteRemove(), CalendarMgr::SendCalendarEventModeratorStatusAlert(), CalendarMgr::SendCalendarEventStatus(), and CalendarMgr::UpdateInvite().
GetInviteId()
uint64 CalendarInvite::GetInviteId () const inline
{ return _inviteId; }
References _inviteId.
Referenced by CalendarMgr::RemoveEvent(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), and CalendarMgr::UpdateInvite().
GetRank()
CalendarModerationRank CalendarInvite::GetRank () const inline
{ return _rank; }
References _rank.
Referenced by CalendarInvite(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventModeratorStatusAlert(), CalendarMgr::SendCalendarEventStatus(), and CalendarMgr::UpdateInvite().
GetSenderGUID()
ObjectGuid CalendarInvite::GetSenderGUID () const inline
{ return _senderGUID; }
References _senderGUID.
Referenced by CalendarInvite(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), and CalendarMgr::UpdateInvite().
GetStatus()
CalendarInviteStatus CalendarInvite::GetStatus () const inline
{ return _status; }
References _status.
Referenced by CalendarInvite(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventStatus(), and CalendarMgr::UpdateInvite().
GetStatusTime()
time_t CalendarInvite::GetStatusTime () const inline
{ return _statusTime; }
References _statusTime.
Referenced by CalendarInvite(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventStatus(), and CalendarMgr::UpdateInvite().
GetText()
std::string CalendarInvite::GetText () const inline
{ return _text; }
References _text.
Referenced by CalendarInvite(), CalendarMgr::SendCalendarEvent(), and CalendarMgr::UpdateInvite().
SetEventId()
void CalendarInvite::SetEventId (uint64 eventId) inline
{ _eventId = eventId; }
References _eventId.
SetInvitee()
void CalendarInvite::SetInvitee (ObjectGuid guid) inline
{ _invitee = guid; }
References _invitee.
SetInviteId()
void CalendarInvite::SetInviteId (uint64 inviteId) inline
{ _inviteId = inviteId; }
References _inviteId.
SetRank()
void CalendarInvite::SetRank (CalendarModerationRank rank) inline
{ _rank = rank; }
References _rank.
SetSenderGUID()
void CalendarInvite::SetSenderGUID (ObjectGuid guid) inline
{ _senderGUID = guid; }
References _senderGUID.
SetStatus()
void CalendarInvite::SetStatus (CalendarInviteStatus status) inline
{ _status = status; }
References _status.
SetStatusTime()
void CalendarInvite::SetStatusTime (time_t statusTime) inline
{ _statusTime = statusTime; }
References _statusTime.
SetText()
void CalendarInvite::SetText (const std::string & text) inline
{ _text = text; }
References _text.
Member Data Documentation
_eventId
uint64 CalendarInvite::_eventId private
Referenced by CalendarInvite(), GetEventId(), SetEventId(), and ~CalendarInvite().
_invitee
ObjectGuid CalendarInvite::_invitee private
Referenced by CalendarInvite(), GetInviteeGUID(), and SetInvitee().
_inviteId
uint64 CalendarInvite::_inviteId private
Referenced by CalendarInvite(), GetInviteId(), SetInviteId(), and ~CalendarInvite().
_rank
CalendarModerationRank CalendarInvite::_rank private
Referenced by CalendarInvite(), GetRank(), and SetRank().
_senderGUID
ObjectGuid CalendarInvite::_senderGUID private
Referenced by CalendarInvite(), GetSenderGUID(), and SetSenderGUID().
_status
CalendarInviteStatus CalendarInvite::_status private
Referenced by CalendarInvite(), GetStatus(), and SetStatus().
_statusTime
time_t CalendarInvite::_statusTime private
Referenced by CalendarInvite(), GetStatusTime(), and SetStatusTime().
_text
std::string CalendarInvite::_text private
Referenced by CalendarInvite(), GetText(), and SetText().