AzerothCore: RestoreAttack Class Reference
RestoreAttack Class Reference
Public Member Functions
RestoreAttack (Creature *boss)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _boss
Detailed Description
Constructor & Destructor Documentation
RestoreAttack()
RestoreAttack::RestoreAttack (Creature * boss) inline
: _boss(boss) {}
Member Function Documentation
Execute()
bool RestoreAttack::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        _boss->SetReactState(REACT_AGGRESSIVE);
        _boss->AI()->SetData(DATA_GOLEM_LORD_ARGELMACH_INIT, DONE);
        if (Unit* victim = _boss->GetVictim())
        {
            _boss->SetTarget(victim->GetGUID());
            _boss->GetMotionMaster()->MoveChase(victim);
        }
        return true;
    }
References _boss, Creature::AI(), DATA_GOLEM_LORD_ARGELMACH_INIT, DONE, Unit::GetMotionMaster(), Unit::GetVictim(), MotionMaster::MoveChase(), REACT_AGGRESSIVE, UnitAI::SetData(), Creature::SetReactState(), and Creature::SetTarget().
Member Data Documentation
_boss
Creature* RestoreAttack::_boss private
Referenced by Execute().