AzerothCore: PlayerDumpWriter Class Reference
PlayerDumpWriter Class Reference
#include "PlayerDump.h"
Public Member Functions
PlayerDumpWriter ()
bool GetDump (ObjectGuid::LowType guid, std::string &dump)
DumpReturn WriteDumpToFile (std::string const &file, ObjectGuid::LowType guid)
DumpReturn WriteDumpToString (std::string &dump, ObjectGuid::LowType guid)
Private Member Functions
bool AppendTable (StringTransaction &trans, ObjectGuid::LowType guid, TableStruct const &tableStruct, DumpTable const &dumpTable)
void PopulateGuids (ObjectGuid::LowType guid)
Private Attributes
std::set< ObjectGuid::LowType > _pets
std::set< ObjectGuid::LowType > _mails
std::set< ObjectGuid::LowType > _items
std::set< uint64 > _itemSets
Additional Inherited Members
Static Public Member Functions inherited from PlayerDump
static void InitializeTables ()
Protected Member Functions inherited from PlayerDump
PlayerDump ()
Detailed Description
Constructor & Destructor Documentation
PlayerDumpWriter()
PlayerDumpWriter::PlayerDumpWriter () inline
{ }
Member Function Documentation
AppendTable()
bool PlayerDumpWriter::AppendTable (StringTransaction & trans, ObjectGuid::LowType guid, TableStruct const & tableStruct, DumpTable const & dumpTable) private
{
    std::string whereStr;
    switch (dumpTable.Type)
    {
    case DTT_ITEM:
    case DTT_ITEM_GIFT:
        if (_items.empty())
            return true;
        whereStr = GenerateWhereStr(tableStruct.WhereFieldName, _items);
        break;
    case DTT_PET_TABLE:
        if (_pets.empty())
            return true;
        whereStr = GenerateWhereStr(tableStruct.WhereFieldName, _pets);
        break;
    case DTT_MAIL_ITEM:
        if (_mails.empty())
            return true;
        whereStr = GenerateWhereStr(tableStruct.WhereFieldName, _mails);
        break;
    case DTT_EQSET_TABLE:
        if (_itemSets.empty())
            return true;
        whereStr = GenerateWhereStr(tableStruct.WhereFieldName, _itemSets);
        break;
    default:
        // not set case, get single guid string
        whereStr = GenerateWhereStr(tableStruct.WhereFieldName, guid);
        break;
    }
    QueryResult result = CharacterDatabase.Query("SELECT * FROM {} WHERE {}", dumpTable.Name, whereStr);
    switch (dumpTable.Type)
    {
    case DTT_CHARACTER:
        if (result)
        {
            // characters.deleteInfos_Account - if filled error
            int32 index = GetColumnIndexByName(tableStruct, "deleteInfos_Account");
            ASSERT(index != -1); // checked at startup
            if ((*result)[index].Get<uint32>())
                return false;
        }
        break;
    default:
        break;
    }
    AppendTableDump(trans, tableStruct, result);
    return true;
}
References _items, _itemSets, _mails, _pets, AppendTableDump(), ASSERT, CharacterDatabase, DTT_CHARACTER, DTT_EQSET_TABLE, DTT_ITEM, DTT_ITEM_GIFT, DTT_MAIL_ITEM, DTT_PET_TABLE, GenerateWhereStr(), GetColumnIndexByName(), DumpTable::Name, DumpTable::Type, and TableStruct::WhereFieldName.
Referenced by GetDump().
GetDump()
bool PlayerDumpWriter::GetDump (ObjectGuid::LowType guid, std::string & dump)
Todo:
Add instance/group..
Todo:
Todo:
Add a dump level option to skip some non-important tables
{
    dump = "IMPORTANT NOTE: THIS DUMPFILE IS MADE FOR USE WITH THE 'PDUMP' COMMAND ONLY - EITHER THROUGH INGAME CHAT OR ON CONSOLE!\n";
    dump += "IMPORTANT NOTE: DO NOT apply it directly - it will irreversibly DAMAGE and CORRUPT your database! You have been warned!\n\n";
    StringTransaction trans;
    // collect guids
    PopulateGuids(guid);
    for (uint32 i = 0; i < DUMP_TABLE_COUNT; ++i)
        if (!AppendTable(trans, guid, CharacterTables[i], DumpTables[i]))
            return false;
    dump += trans.GetBuffer();
    return true;
}
References AppendTable(), CharacterTables, DUMP_TABLE_COUNT, DumpTables, StringTransaction::GetBuffer(), and PopulateGuids().
Referenced by WriteDumpToFile(), and WriteDumpToString().
PopulateGuids()
void PlayerDumpWriter::PopulateGuids (ObjectGuid::LowType guid) private
{
    for (BaseTable const& baseTable : BaseTables)
    {
        switch (baseTable.StoredType)
        {
        case GUID_TYPE_ITEM:
        case GUID_TYPE_MAIL:
        case GUID_TYPE_PET:
        case GUID_TYPE_EQUIPMENT_SET:
            break;
        default:
            return;
        }
        std::string whereStr = GenerateWhereStr(baseTable.PlayerGuid, guid);
        QueryResult result = CharacterDatabase.Query("SELECT {} FROM {} WHERE {}", baseTable.PrimaryKey, baseTable.TableName, whereStr);
        if (!result)
            continue;
        do
        {
            switch (baseTable.StoredType)
            {
            case GUID_TYPE_ITEM:
                if (ObjectGuid::LowType itemLowGuid = (*result)[0].Get<uint32>())
                    _items.insert(itemLowGuid);
                break;
            case GUID_TYPE_MAIL:
                if (ObjectGuid::LowType mailLowGuid = (*result)[0].Get<uint32>())
                    _mails.insert(mailLowGuid);
                break;
            case GUID_TYPE_PET:
                if (ObjectGuid::LowType petLowGuid = (*result)[0].Get<uint32>())
                    _pets.insert(petLowGuid);
                break;
            case GUID_TYPE_EQUIPMENT_SET:
                if (uint64 eqSetId = (*result)[0].Get<uint64>())
                    _itemSets.insert(eqSetId);
                break;
            default:
                break;
            }
        } while (result->NextRow());
    }
}
References _items, _itemSets, _mails, _pets, BaseTables, CharacterDatabase, GenerateWhereStr(), GUID_TYPE_EQUIPMENT_SET, GUID_TYPE_ITEM, GUID_TYPE_MAIL, and GUID_TYPE_PET.
Referenced by GetDump().
WriteDumpToFile()
DumpReturn PlayerDumpWriter::WriteDumpToFile (std::string const & file, ObjectGuid::LowType guid)
{
    if (sWorld->getBoolConfig(CONFIG_PDUMP_NO_PATHS))
        if (strchr(file.c_str(), '\\') || strchr(file.c_str(), '/'))
            return DUMP_FILE_OPEN_ERROR;
    if (sWorld->getBoolConfig(CONFIG_PDUMP_NO_OVERWRITE))
    {
        // check if file exists already
        if (GetFileHandle(file.c_str(), "r"))
            return DUMP_FILE_OPEN_ERROR;
    }
    FileHandle fout = GetFileHandle(file.c_str(), "w");
    if (!fout)
        return DUMP_FILE_OPEN_ERROR;
    DumpReturn ret = DUMP_SUCCESS;
    std::string dump;
    if (!GetDump(guid, dump))
        ret = DUMP_CHARACTER_DELETED;
    fprintf(fout.get(), "%s", dump.c_str());
    return ret;
}
References CONFIG_PDUMP_NO_OVERWRITE, CONFIG_PDUMP_NO_PATHS, DUMP_CHARACTER_DELETED, DUMP_FILE_OPEN_ERROR, DUMP_SUCCESS, GetDump(), GetFileHandle(), and sWorld.
WriteDumpToString()
DumpReturn PlayerDumpWriter::WriteDumpToString (std::string & dump, ObjectGuid::LowType guid)
{
    DumpReturn ret = DUMP_SUCCESS;
    if (!GetDump(guid, dump))
        ret = DUMP_CHARACTER_DELETED;
    return ret;
}
References DUMP_CHARACTER_DELETED, DUMP_SUCCESS, and GetDump().
Member Data Documentation
_items
std::set<ObjectGuid::LowType> PlayerDumpWriter::_items private
Referenced by AppendTable(), and PopulateGuids().
_itemSets
std::set<uint64> PlayerDumpWriter::_itemSets private
Referenced by AppendTable(), and PopulateGuids().
_mails
std::set<ObjectGuid::LowType> PlayerDumpWriter::_mails private
Referenced by AppendTable(), and PopulateGuids().
_pets
std::set<ObjectGuid::LowType> PlayerDumpWriter::_pets private
Referenced by AppendTable(), and PopulateGuids().