AzerothCore: WorldPackets::Misc::Weather Class Reference
WorldPackets::Misc::Weather Class Reference final
#include "MiscPackets.h"
Public Member Functions
Weather ()
Weather (WeatherState weatherID, float intensity=0.0f, bool abrupt=false)
WorldPacket const * Write () override
Public Member Functions inherited from WorldPackets::ServerPacket
ServerPacket (OpcodeServer opcode, std::size_t initialSize=200)
void Read () final
void Clear ()
WorldPacket && Move ()
void ShrinkToFit ()
OpcodeServer GetOpcode () const
Public Member Functions inherited from WorldPackets::Packet
Packet (WorldPacket &&worldPacket)
virtual ~Packet ()=default
Packet (Packet const &right)=delete
Packet & operator= (Packet const &right)=delete
virtual WorldPacket const * Write ()=0
virtual void Read ()=0
WorldPacket const * GetRawPacket () const
std::size_t GetSize () const
Public Attributes
bool Abrupt = false
float Intensity = 0.0f
WeatherState WeatherID = WeatherState(0)
Additional Inherited Members
Protected Attributes inherited from WorldPackets::Packet
WorldPacket _worldPacket
Detailed Description
Constructor & Destructor Documentation
Weather() [1/2]
Weather::Weather ()
: ServerPacket(SMSG_WEATHER, 4 + 4 + 1) { }
Weather() [2/2]
Weather::Weather (WeatherState weatherID, float intensity = 0.0f, bool abrupt = false)
    : ServerPacket(SMSG_WEATHER, 4 + 4 + 1), Abrupt(abrupt), Intensity(intensity), WeatherID(weatherID) { }
Member Function Documentation
Write()
WorldPacket const * Weather::Write () override virtual
Implements WorldPackets::Packet.
{
    _worldPacket << uint32(WeatherID);
    _worldPacket << float(Intensity);
    _worldPacket << uint8(Abrupt);
    return &_worldPacket;
}
Referenced by boss_ossirian::JustEngagedWith(), WeatherMgr::SendFineWeatherUpdateToPlayer(), Weather::SendWeatherUpdateToPlayer(), Map::SendZoneDynamicInfo(), Map::SetZoneWeather(), and Weather::UpdateWeather().
Member Data Documentation
Abrupt
bool WorldPackets::Misc::Weather::Abrupt = false
Intensity
float WorldPackets::Misc::Weather::Intensity = 0.0f
WeatherID
WeatherState WorldPackets::Misc::Weather::WeatherID = WeatherState(0)