AzerothCore: Acore::CreatureListSearcher< Check > Struct Template Reference
Acore::CreatureListSearcher< Check > Struct Template Reference
#include "GridNotifiers.h"
Public Member Functions
template<typename Container >
CreatureListSearcher (WorldObject const *searcher, Container &container, Check &check)
void Visit (CreatureMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_phaseMask
Check & i_check
Additional Inherited Members
Protected Member Functions inherited from Acore::ContainerInserter< Creature * >
ContainerInserter (T &ref_)
void Insert (Creature * type)
Detailed Description
template<class Check>
struct Acore::CreatureListSearcher< Check >
Constructor & Destructor Documentation
CreatureListSearcher()
template<class Check > template<typename Container > Acore::CreatureListSearcher< Check >::CreatureListSearcher (WorldObject const * searcher, Container & container, Check & check) inline
                : ContainerInserter<Creature*>(container),
                  i_phaseMask(searcher->GetPhaseMask()), i_check(check) { }
Member Function Documentation
Visit() [1/2]
template<class Check > void Acore::CreatureListSearcher< Check >::Visit (CreatureMapType & m)
{
    for (CreatureMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
        if (itr->GetSource()->InSamePhase(i_phaseMask))
            if (i_check(itr->GetSource()))
                Insert(itr->GetSource());
}
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and Acore::Insert().
Visit() [2/2]
template<class Check > template<class NOT_INTERESTED > void Acore::CreatureListSearcher< Check >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
{}
Member Data Documentation
i_check
template<class Check > Check& Acore::CreatureListSearcher< Check >::i_check
i_phaseMask
template<class Check > uint32 Acore::CreatureListSearcher< Check >::i_phaseMask