document.write(`
  <a id="Unit:AddAura" class="fn" href="../Unit/AddAura.html">AddAura</a>
  <a id="Unit:AddThreat" class="fn" href="../Unit/AddThreat.html">AddThreat</a>
  <a id="Unit:AddUnitState" class="fn" href="../Unit/AddUnitState.html">AddUnitState</a>
  <a id="Unit:Attack" class="fn" href="../Unit/Attack.html">Attack</a>
  <a id="Unit:AttackStop" class="fn" href="../Unit/AttackStop.html">AttackStop</a>
  <a id="Unit:CastCustomSpell" class="fn" href="../Unit/CastCustomSpell.html">CastCustomSpell</a>
  <a id="Unit:CastSpell" class="fn" href="../Unit/CastSpell.html">CastSpell</a>
  <a id="Unit:CastSpellAoF" class="fn" href="../Unit/CastSpellAoF.html">CastSpellAoF</a>
  <a id="Unit:ClearInCombat" class="fn" href="../Unit/ClearInCombat.html">ClearInCombat</a>
  <a id="Unit:ClearThreatList" class="fn" href="../Unit/ClearThreatList.html">ClearThreatList</a>
  <a id="Unit:ClearUnitState" class="fn" href="../Unit/ClearUnitState.html">ClearUnitState</a>
  <a id="Unit:CountPctFromCurHealth" class="fn" href="../Unit/CountPctFromCurHealth.html">CountPctFromCurHealth</a>
  <a id="Unit:CountPctFromMaxHealth" class="fn" href="../Unit/CountPctFromMaxHealth.html">CountPctFromMaxHealth</a>
  <a id="Unit:DeMorph" class="fn" href="../Unit/DeMorph.html">DeMorph</a>
  <a id="Unit:DealDamage" class="fn" href="../Unit/DealDamage.html">DealDamage</a>
  <a id="Unit:DealHeal" class="fn" href="../Unit/DealHeal.html">DealHeal</a>
  <a id="Unit:Dismount" class="fn" href="../Unit/Dismount.html">Dismount</a>
  <a id="Unit:EmoteState" class="fn" href="../Unit/EmoteState.html">EmoteState</a>
  <a id="Unit:GetAttackers" class="fn" href="../Unit/GetAttackers.html">GetAttackers</a>
  <a id="Unit:GetAura" class="fn" href="../Unit/GetAura.html">GetAura</a>
  <a id="Unit:GetBaseSpellPower" class="fn" href="../Unit/GetBaseSpellPower.html">GetBaseSpellPower</a>
  <a id="Unit:GetCharmGUID" class="fn" href="../Unit/GetCharmGUID.html">GetCharmGUID</a>
  <a id="Unit:GetCharmerGUID" class="fn" href="../Unit/GetCharmerGUID.html">GetCharmerGUID</a>
  <a id="Unit:GetClass" class="fn" href="../Unit/GetClass.html">GetClass</a>
  <a id="Unit:GetClassAsString" class="fn" href="../Unit/GetClassAsString.html">GetClassAsString</a>
  <a id="Unit:GetClassMask" class="fn" href="../Unit/GetClassMask.html">GetClassMask</a>
  <a id="Unit:GetControllerGUID" class="fn" href="../Unit/GetControllerGUID.html">GetControllerGUID</a>
  <a id="Unit:GetControllerGUIDS" class="fn" href="../Unit/GetControllerGUIDS.html">GetControllerGUIDS</a>
  <a id="Unit:GetCreatorGUID" class="fn" href="../Unit/GetCreatorGUID.html">GetCreatorGUID</a>
  <a id="Unit:GetCreatureType" class="fn" href="../Unit/GetCreatureType.html">GetCreatureType</a>
  <a id="Unit:GetCritterGUID" class="fn" href="../Unit/GetCritterGUID.html">GetCritterGUID</a>
  <a id="Unit:GetCurrentSpell" class="fn" href="../Unit/GetCurrentSpell.html">GetCurrentSpell</a>
  <a id="Unit:GetDisplayId" class="fn" href="../Unit/GetDisplayId.html">GetDisplayId</a>
  <a id="Unit:GetFaction" class="fn" href="../Unit/GetFaction.html">GetFaction</a>
  <a id="Unit:GetFriendlyUnitsInRange" class="fn" href="../Unit/GetFriendlyUnitsInRange.html">GetFriendlyUnitsInRange</a>
  <a id="Unit:GetGender" class="fn" href="../Unit/GetGender.html">GetGender</a>
  <a id="Unit:GetHealth" class="fn" href="../Unit/GetHealth.html">GetHealth</a>
  <a id="Unit:GetHealthPct" class="fn" href="../Unit/GetHealthPct.html">GetHealthPct</a>
  <a id="Unit:GetLevel" class="fn" href="../Unit/GetLevel.html">GetLevel</a>
  <a id="Unit:GetMaxHealth" class="fn" href="../Unit/GetMaxHealth.html">GetMaxHealth</a>
  <a id="Unit:GetMaxPower" class="fn" href="../Unit/GetMaxPower.html">GetMaxPower</a>
  <a id="Unit:GetMountId" class="fn" href="../Unit/GetMountId.html">GetMountId</a>
  <a id="Unit:GetMovementType" class="fn" href="../Unit/GetMovementType.html">GetMovementType</a>
  <a id="Unit:GetNativeDisplayId" class="fn" href="../Unit/GetNativeDisplayId.html">GetNativeDisplayId</a>
  <a id="Unit:GetOwner" class="fn" href="../Unit/GetOwner.html">GetOwner</a>
  <a id="Unit:GetOwnerGUID" class="fn" href="../Unit/GetOwnerGUID.html">GetOwnerGUID</a>
  <a id="Unit:GetPetGUID" class="fn" href="../Unit/GetPetGUID.html">GetPetGUID</a>
  <a id="Unit:GetPower" class="fn" href="../Unit/GetPower.html">GetPower</a>
  <a id="Unit:GetPowerPct" class="fn" href="../Unit/GetPowerPct.html">GetPowerPct</a>
  <a id="Unit:GetPowerType" class="fn" href="../Unit/GetPowerType.html">GetPowerType</a>
  <a id="Unit:GetRace" class="fn" href="../Unit/GetRace.html">GetRace</a>
  <a id="Unit:GetRaceAsString" class="fn" href="../Unit/GetRaceAsString.html">GetRaceAsString</a>
  <a id="Unit:GetRaceMask" class="fn" href="../Unit/GetRaceMask.html">GetRaceMask</a>
  <a id="Unit:GetSpeed" class="fn" href="../Unit/GetSpeed.html">GetSpeed</a>
  <a id="Unit:GetSpeedRate" class="fn" href="../Unit/GetSpeedRate.html">GetSpeedRate</a>
  <a id="Unit:GetStandState" class="fn" href="../Unit/GetStandState.html">GetStandState</a>
  <a id="Unit:GetStat" class="fn" href="../Unit/GetStat.html">GetStat</a>
  <a id="Unit:GetThreatList" class="fn" href="../Unit/GetThreatList.html">GetThreatList</a>
  <a id="Unit:GetUnfriendlyUnitsInRange" class="fn" href="../Unit/GetUnfriendlyUnitsInRange.html">GetUnfriendlyUnitsInRange</a>
  <a id="Unit:GetVehicle" class="fn" href="../Unit/GetVehicle.html">GetVehicle</a>
  <a id="Unit:GetVehicleKit" class="fn" href="../Unit/GetVehicleKit.html">GetVehicleKit</a>
  <a id="Unit:GetVictim" class="fn" href="../Unit/GetVictim.html">GetVictim</a>
  <a id="Unit:HandleStatModifier" class="fn" href="../Unit/HandleStatModifier.html">HandleStatModifier</a>
  <a id="Unit:HasAura" class="fn" href="../Unit/HasAura.html">HasAura</a>
  <a id="Unit:HasUnitState" class="fn" href="../Unit/HasUnitState.html">HasUnitState</a>
  <a id="Unit:HealthAbovePct" class="fn" href="../Unit/HealthAbovePct.html">HealthAbovePct</a>
  <a id="Unit:HealthBelowPct" class="fn" href="../Unit/HealthBelowPct.html">HealthBelowPct</a>
  <a id="Unit:InterruptSpell" class="fn" href="../Unit/InterruptSpell.html">InterruptSpell</a>
  <a id="Unit:IsAlive" class="fn" href="../Unit/IsAlive.html">IsAlive</a>
  <a id="Unit:IsArmorer" class="fn" href="../Unit/IsArmorer.html">IsArmorer</a>
  <a id="Unit:IsAttackingPlayer" class="fn" href="../Unit/IsAttackingPlayer.html">IsAttackingPlayer</a>
  <a id="Unit:IsAuctioneer" class="fn" href="../Unit/IsAuctioneer.html">IsAuctioneer</a>
  <a id="Unit:IsBanker" class="fn" href="../Unit/IsBanker.html">IsBanker</a>
  <a id="Unit:IsBattleMaster" class="fn" href="../Unit/IsBattleMaster.html">IsBattleMaster</a>
  <a id="Unit:IsCasting" class="fn" href="../Unit/IsCasting.html">IsCasting</a>
  <a id="Unit:IsCharmed" class="fn" href="../Unit/IsCharmed.html">IsCharmed</a>
  <a id="Unit:IsDead" class="fn" href="../Unit/IsDead.html">IsDead</a>
  <a id="Unit:IsDying" class="fn" href="../Unit/IsDying.html">IsDying</a>
  <a id="Unit:IsFullHealth" class="fn" href="../Unit/IsFullHealth.html">IsFullHealth</a>
  <a id="Unit:IsGossip" class="fn" href="../Unit/IsGossip.html">IsGossip</a>
  <a id="Unit:IsGuildMaster" class="fn" href="../Unit/IsGuildMaster.html">IsGuildMaster</a>
  <a id="Unit:IsInAccessiblePlaceFor" class="fn" href="../Unit/IsInAccessiblePlaceFor.html">IsInAccessiblePlaceFor</a>
  <a id="Unit:IsInCombat" class="fn" href="../Unit/IsInCombat.html">IsInCombat</a>
  <a id="Unit:IsInWater" class="fn" href="../Unit/IsInWater.html">IsInWater</a>
  <a id="Unit:IsInnkeeper" class="fn" href="../Unit/IsInnkeeper.html">IsInnkeeper</a>
  <a id="Unit:IsMounted" class="fn" href="../Unit/IsMounted.html">IsMounted</a>
  <a id="Unit:IsOnVehicle" class="fn" href="../Unit/IsOnVehicle.html">IsOnVehicle</a>
  <a id="Unit:IsPvPFlagged" class="fn" href="../Unit/IsPvPFlagged.html">IsPvPFlagged</a>
  <a id="Unit:IsQuestGiver" class="fn" href="../Unit/IsQuestGiver.html">IsQuestGiver</a>
  <a id="Unit:IsRooted" class="fn" href="../Unit/IsRooted.html">IsRooted</a>
  <a id="Unit:IsServiceProvider" class="fn" href="../Unit/IsServiceProvider.html">IsServiceProvider</a>
  <a id="Unit:IsSpiritGuide" class="fn" href="../Unit/IsSpiritGuide.html">IsSpiritGuide</a>
  <a id="Unit:IsSpiritHealer" class="fn" href="../Unit/IsSpiritHealer.html">IsSpiritHealer</a>
  <a id="Unit:IsSpiritService" class="fn" href="../Unit/IsSpiritService.html">IsSpiritService</a>
  <a id="Unit:IsStandState" class="fn" href="../Unit/IsStandState.html">IsStandState</a>
  <a id="Unit:IsStopped" class="fn" href="../Unit/IsStopped.html">IsStopped</a>
  <a id="Unit:IsTabardDesigner" class="fn" href="../Unit/IsTabardDesigner.html">IsTabardDesigner</a>
  <a id="Unit:IsTaxi" class="fn" href="../Unit/IsTaxi.html">IsTaxi</a>
  <a id="Unit:IsTrainer" class="fn" href="../Unit/IsTrainer.html">IsTrainer</a>
  <a id="Unit:IsUnderWater" class="fn" href="../Unit/IsUnderWater.html">IsUnderWater</a>
  <a id="Unit:IsVendor" class="fn" href="../Unit/IsVendor.html">IsVendor</a>
  <a id="Unit:Kill" class="fn" href="../Unit/Kill.html">Kill</a>
  <a id="Unit:ModifyPower" class="fn" href="../Unit/ModifyPower.html">ModifyPower</a>
  <a id="Unit:ModifyThreatPct" class="fn" href="../Unit/ModifyThreatPct.html">ModifyThreatPct</a>
  <a id="Unit:Mount" class="fn" href="../Unit/Mount.html">Mount</a>
  <a id="Unit:MoveChase" class="fn" href="../Unit/MoveChase.html">MoveChase</a>
  <a id="Unit:MoveClear" class="fn" href="../Unit/MoveClear.html">MoveClear</a>
  <a id="Unit:MoveConfused" class="fn" href="../Unit/MoveConfused.html">MoveConfused</a>
  <a id="Unit:MoveExpire" class="fn" href="../Unit/MoveExpire.html">MoveExpire</a>
  <a id="Unit:MoveFleeing" class="fn" href="../Unit/MoveFleeing.html">MoveFleeing</a>
  <a id="Unit:MoveFollow" class="fn" href="../Unit/MoveFollow.html">MoveFollow</a>
  <a id="Unit:MoveHome" class="fn" href="../Unit/MoveHome.html">MoveHome</a>
  <a id="Unit:MoveIdle" class="fn" href="../Unit/MoveIdle.html">MoveIdle</a>
  <a id="Unit:MoveJump" class="fn" href="../Unit/MoveJump.html">MoveJump</a>
  <a id="Unit:MoveRandom" class="fn" href="../Unit/MoveRandom.html">MoveRandom</a>
  <a id="Unit:MoveStop" class="fn" href="../Unit/MoveStop.html">MoveStop</a>
  <a id="Unit:MoveTo" class="fn" href="../Unit/MoveTo.html">MoveTo</a>
  <a id="Unit:NearTeleport" class="fn" href="../Unit/NearTeleport.html">NearTeleport</a>
  <a id="Unit:PerformEmote" class="fn" href="../Unit/PerformEmote.html">PerformEmote</a>
  <a id="Unit:RemoveAllAuras" class="fn" href="../Unit/RemoveAllAuras.html">RemoveAllAuras</a>
  <a id="Unit:RemoveArenaAuras" class="fn" href="../Unit/RemoveArenaAuras.html">RemoveArenaAuras</a>
  <a id="Unit:RemoveAura" class="fn" href="../Unit/RemoveAura.html">RemoveAura</a>
  <a id="Unit:SendChatMessageToPlayer" class="fn" href="../Unit/SendChatMessageToPlayer.html">SendChatMessageToPlayer</a>
  <a id="Unit:SendUnitEmote" class="fn" href="../Unit/SendUnitEmote.html">SendUnitEmote</a>
  <a id="Unit:SendUnitSay" class="fn" href="../Unit/SendUnitSay.html">SendUnitSay</a>
  <a id="Unit:SendUnitWhisper" class="fn" href="../Unit/SendUnitWhisper.html">SendUnitWhisper</a>
  <a id="Unit:SendUnitYell" class="fn" href="../Unit/SendUnitYell.html">SendUnitYell</a>
  <a id="Unit:SetConfused" class="fn" href="../Unit/SetConfused.html">SetConfused</a>
  <a id="Unit:SetCreatorGUID" class="fn" href="../Unit/SetCreatorGUID.html">SetCreatorGUID</a>
  <a id="Unit:SetCritterGUID" class="fn" href="../Unit/SetCritterGUID.html">SetCritterGUID</a>
  <a id="Unit:SetDisplayId" class="fn" href="../Unit/SetDisplayId.html">SetDisplayId</a>
  <a id="Unit:SetFFA" class="fn" href="../Unit/SetFFA.html">SetFFA</a>
  <a id="Unit:SetFacing" class="fn" href="../Unit/SetFacing.html">SetFacing</a>
  <a id="Unit:SetFacingToObject" class="fn" href="../Unit/SetFacingToObject.html">SetFacingToObject</a>
  <a id="Unit:SetFaction" class="fn" href="../Unit/SetFaction.html">SetFaction</a>
  <a id="Unit:SetFeared" class="fn" href="../Unit/SetFeared.html">SetFeared</a>
  <a id="Unit:SetHealth" class="fn" href="../Unit/SetHealth.html">SetHealth</a>
  <a id="Unit:SetImmuneTo" class="fn" href="../Unit/SetImmuneTo.html">SetImmuneTo</a>
  <a id="Unit:SetInCombatWith" class="fn" href="../Unit/SetInCombatWith.html">SetInCombatWith</a>
  <a id="Unit:SetLevel" class="fn" href="../Unit/SetLevel.html">SetLevel</a>
  <a id="Unit:SetMaxHealth" class="fn" href="../Unit/SetMaxHealth.html">SetMaxHealth</a>
  <a id="Unit:SetMaxPower" class="fn" href="../Unit/SetMaxPower.html">SetMaxPower</a>
  <a id="Unit:SetName" class="fn" href="../Unit/SetName.html">SetName</a>
  <a id="Unit:SetNativeDisplayId" class="fn" href="../Unit/SetNativeDisplayId.html">SetNativeDisplayId</a>
  <a id="Unit:SetOwnerGUID" class="fn" href="../Unit/SetOwnerGUID.html">SetOwnerGUID</a>
  <a id="Unit:SetPetGUID" class="fn" href="../Unit/SetPetGUID.html">SetPetGUID</a>
  <a id="Unit:SetPower" class="fn" href="../Unit/SetPower.html">SetPower</a>
  <a id="Unit:SetPowerType" class="fn" href="../Unit/SetPowerType.html">SetPowerType</a>
  <a id="Unit:SetPvP" class="fn" href="../Unit/SetPvP.html">SetPvP</a>
  <a id="Unit:SetRooted" class="fn" href="../Unit/SetRooted.html">SetRooted</a>
  <a id="Unit:SetSanctuary" class="fn" href="../Unit/SetSanctuary.html">SetSanctuary</a>
  <a id="Unit:SetSheath" class="fn" href="../Unit/SetSheath.html">SetSheath</a>
  <a id="Unit:SetSpeed" class="fn" href="../Unit/SetSpeed.html">SetSpeed</a>
  <a id="Unit:SetSpeedRate" class="fn" href="../Unit/SetSpeedRate.html">SetSpeedRate</a>
  <a id="Unit:SetStandState" class="fn" href="../Unit/SetStandState.html">SetStandState</a>
  <a id="Unit:SetWaterWalk" class="fn" href="../Unit/SetWaterWalk.html">SetWaterWalk</a>
  <a id="Unit:StopSpellCast" class="fn" href="../Unit/StopSpellCast.html">StopSpellCast</a>
`);