document.write(`
  <a id="Player:AddComboPoints" class="fn" href="../Player/AddComboPoints.html">AddComboPoints</a>
  <a id="Player:AddItem" class="fn" href="../Player/AddItem.html">AddItem</a>
  <a id="Player:AddLifetimeKills" class="fn" href="../Player/AddLifetimeKills.html">AddLifetimeKills</a>
  <a id="Player:AddQuest" class="fn" href="../Player/AddQuest.html">AddQuest</a>
  <a id="Player:AdvanceAllSkills" class="fn" href="../Player/AdvanceAllSkills.html">AdvanceAllSkills</a>
  <a id="Player:AdvanceSkill" class="fn" href="../Player/AdvanceSkill.html">AdvanceSkill</a>
  <a id="Player:AdvanceSkillsToMax" class="fn" href="../Player/AdvanceSkillsToMax.html">AdvanceSkillsToMax</a>
  <a id="Player:AreaExploredOrEventHappens" class="fn" href="../Player/AreaExploredOrEventHappens.html">AreaExploredOrEventHappens</a>
  <a id="Player:CanBlock" class="fn" href="../Player/CanBlock.html">CanBlock</a>
  <a id="Player:CanCompleteQuest" class="fn" href="../Player/CanCompleteQuest.html">CanCompleteQuest</a>
  <a id="Player:CanCompleteRepeatableQuest" class="fn" href="../Player/CanCompleteRepeatableQuest.html">CanCompleteRepeatableQuest</a>
  <a id="Player:CanEquipItem" class="fn" href="../Player/CanEquipItem.html">CanEquipItem</a>
  <a id="Player:CanFly" class="fn" href="../Player/CanFly.html">CanFly</a>
  <a id="Player:CanParry" class="fn" href="../Player/CanParry.html">CanParry</a>
  <a id="Player:CanRewardQuest" class="fn" href="../Player/CanRewardQuest.html">CanRewardQuest</a>
  <a id="Player:CanShareQuest" class="fn" href="../Player/CanShareQuest.html">CanShareQuest</a>
  <a id="Player:CanSpeak" class="fn" href="../Player/CanSpeak.html">CanSpeak</a>
  <a id="Player:CanTitanGrip" class="fn" href="../Player/CanTitanGrip.html">CanTitanGrip</a>
  <a id="Player:CanUninviteFromGroup" class="fn" href="../Player/CanUninviteFromGroup.html">CanUninviteFromGroup</a>
  <a id="Player:CanUseItem" class="fn" href="../Player/CanUseItem.html">CanUseItem</a>
  <a id="Player:ClearComboPoints" class="fn" href="../Player/ClearComboPoints.html">ClearComboPoints</a>
  <a id="Player:ClearHonorInfo" class="fn" href="../Player/ClearHonorInfo.html">ClearHonorInfo</a>
  <a id="Player:CompleteQuest" class="fn" href="../Player/CompleteQuest.html">CompleteQuest</a>
  <a id="Player:DurabilityLoss" class="fn" href="../Player/DurabilityLoss.html">DurabilityLoss</a>
  <a id="Player:DurabilityLossAll" class="fn" href="../Player/DurabilityLossAll.html">DurabilityLossAll</a>
  <a id="Player:DurabilityPointLossForEquipSlot" class="fn" href="../Player/DurabilityPointLossForEquipSlot.html">DurabilityPointLossForEquipSlot</a>
  <a id="Player:DurabilityPointsLoss" class="fn" href="../Player/DurabilityPointsLoss.html">DurabilityPointsLoss</a>
  <a id="Player:DurabilityPointsLossAll" class="fn" href="../Player/DurabilityPointsLossAll.html">DurabilityPointsLossAll</a>
  <a id="Player:DurabilityRepair" class="fn" href="../Player/DurabilityRepair.html">DurabilityRepair</a>
  <a id="Player:DurabilityRepairAll" class="fn" href="../Player/DurabilityRepairAll.html">DurabilityRepairAll</a>
  <a id="Player:EquipItem" class="fn" href="../Player/EquipItem.html">EquipItem</a>
  <a id="Player:FailQuest" class="fn" href="../Player/FailQuest.html">FailQuest</a>
  <a id="Player:GetAccountId" class="fn" href="../Player/GetAccountId.html">GetAccountId</a>
  <a id="Player:GetAccountName" class="fn" href="../Player/GetAccountName.html">GetAccountName</a>
  <a id="Player:GetAchievementCriteriaProgress" class="fn" href="../Player/GetAchievementCriteriaProgress.html">GetAchievementCriteriaProgress</a>
  <a id="Player:GetAchievementPoints" class="fn" href="../Player/GetAchievementPoints.html">GetAchievementPoints</a>
  <a id="Player:GetActiveSpec" class="fn" href="../Player/GetActiveSpec.html">GetActiveSpec</a>
  <a id="Player:GetArenaPoints" class="fn" href="../Player/GetArenaPoints.html">GetArenaPoints</a>
  <a id="Player:GetBaseSkillValue" class="fn" href="../Player/GetBaseSkillValue.html">GetBaseSkillValue</a>
  <a id="Player:GetBattlegroundId" class="fn" href="../Player/GetBattlegroundId.html">GetBattlegroundId</a>
  <a id="Player:GetBattlegroundTypeId" class="fn" href="../Player/GetBattlegroundTypeId.html">GetBattlegroundTypeId</a>
  <a id="Player:GetChampioningFaction" class="fn" href="../Player/GetChampioningFaction.html">GetChampioningFaction</a>
  <a id="Player:GetChatTag" class="fn" href="../Player/GetChatTag.html">GetChatTag</a>
  <a id="Player:GetCoinage" class="fn" href="../Player/GetCoinage.html">GetCoinage</a>
  <a id="Player:GetComboPoints" class="fn" href="../Player/GetComboPoints.html">GetComboPoints</a>
  <a id="Player:GetComboTarget" class="fn" href="../Player/GetComboTarget.html">GetComboTarget</a>
  <a id="Player:GetCompletedAchievementsCount" class="fn" href="../Player/GetCompletedAchievementsCount.html">GetCompletedAchievementsCount</a>
  <a id="Player:GetCompletedQuestsCount" class="fn" href="../Player/GetCompletedQuestsCount.html">GetCompletedQuestsCount</a>
  <a id="Player:GetCorpse" class="fn" href="../Player/GetCorpse.html">GetCorpse</a>
  <a id="Player:GetDbLocaleIndex" class="fn" href="../Player/GetDbLocaleIndex.html">GetDbLocaleIndex</a>
  <a id="Player:GetDbcLocale" class="fn" href="../Player/GetDbcLocale.html">GetDbcLocale</a>
  <a id="Player:GetDifficulty" class="fn" href="../Player/GetDifficulty.html">GetDifficulty</a>
  <a id="Player:GetDrunkValue" class="fn" href="../Player/GetDrunkValue.html">GetDrunkValue</a>
  <a id="Player:GetEquippedItemBySlot" class="fn" href="../Player/GetEquippedItemBySlot.html">GetEquippedItemBySlot</a>
  <a id="Player:GetFreeTalentPoints" class="fn" href="../Player/GetFreeTalentPoints.html">GetFreeTalentPoints</a>
  <a id="Player:GetGMRank" class="fn" href="../Player/GetGMRank.html">GetGMRank</a>
  <a id="Player:GetGlyph" class="fn" href="../Player/GetGlyph.html">GetGlyph</a>
  <a id="Player:GetGossipTextId" class="fn" href="../Player/GetGossipTextId.html">GetGossipTextId</a>
  <a id="Player:GetGroup" class="fn" href="../Player/GetGroup.html">GetGroup</a>
  <a id="Player:GetGroupInvite" class="fn" href="../Player/GetGroupInvite.html">GetGroupInvite</a>
  <a id="Player:GetGuild" class="fn" href="../Player/GetGuild.html">GetGuild</a>
  <a id="Player:GetGuildId" class="fn" href="../Player/GetGuildId.html">GetGuildId</a>
  <a id="Player:GetGuildName" class="fn" href="../Player/GetGuildName.html">GetGuildName</a>
  <a id="Player:GetGuildRank" class="fn" href="../Player/GetGuildRank.html">GetGuildRank</a>
  <a id="Player:GetHealthBonusFromStamina" class="fn" href="../Player/GetHealthBonusFromStamina.html">GetHealthBonusFromStamina</a>
  <a id="Player:GetHonorLastWeekStandingPos" class="fn" href="../Player/GetHonorLastWeekStandingPos.html">GetHonorLastWeekStandingPos</a>
  <a id="Player:GetHonorPoints" class="fn" href="../Player/GetHonorPoints.html">GetHonorPoints</a>
  <a id="Player:GetHonorStoredKills" class="fn" href="../Player/GetHonorStoredKills.html">GetHonorStoredKills</a>
  <a id="Player:GetInGameTime" class="fn" href="../Player/GetInGameTime.html">GetInGameTime</a>
  <a id="Player:GetItemByEntry" class="fn" href="../Player/GetItemByEntry.html">GetItemByEntry</a>
  <a id="Player:GetItemByGUID" class="fn" href="../Player/GetItemByGUID.html">GetItemByGUID</a>
  <a id="Player:GetItemByPos" class="fn" href="../Player/GetItemByPos.html">GetItemByPos</a>
  <a id="Player:GetItemCount" class="fn" href="../Player/GetItemCount.html">GetItemCount</a>
  <a id="Player:GetLatency" class="fn" href="../Player/GetLatency.html">GetLatency</a>
  <a id="Player:GetLevelPlayedTime" class="fn" href="../Player/GetLevelPlayedTime.html">GetLevelPlayedTime</a>
  <a id="Player:GetLifetimeKills" class="fn" href="../Player/GetLifetimeKills.html">GetLifetimeKills</a>
  <a id="Player:GetMailCount" class="fn" href="../Player/GetMailCount.html">GetMailCount</a>
  <a id="Player:GetMailItem" class="fn" href="../Player/GetMailItem.html">GetMailItem</a>
  <a id="Player:GetManaBonusFromIntellect" class="fn" href="../Player/GetManaBonusFromIntellect.html">GetManaBonusFromIntellect</a>
  <a id="Player:GetMaxSkillValue" class="fn" href="../Player/GetMaxSkillValue.html">GetMaxSkillValue</a>
  <a id="Player:GetNextRandomRaidMember" class="fn" href="../Player/GetNextRandomRaidMember.html">GetNextRandomRaidMember</a>
  <a id="Player:GetOriginalGroup" class="fn" href="../Player/GetOriginalGroup.html">GetOriginalGroup</a>
  <a id="Player:GetOriginalSubGroup" class="fn" href="../Player/GetOriginalSubGroup.html">GetOriginalSubGroup</a>
  <a id="Player:GetPhaseMaskForSpawn" class="fn" href="../Player/GetPhaseMaskForSpawn.html">GetPhaseMaskForSpawn</a>
  <a id="Player:GetPlayerIP" class="fn" href="../Player/GetPlayerIP.html">GetPlayerIP</a>
  <a id="Player:GetPlayerSettingValue" class="fn" href="../Player/GetPlayerSettingValue.html">GetPlayerSettingValue</a>
  <a id="Player:GetPureMaxSkillValue" class="fn" href="../Player/GetPureMaxSkillValue.html">GetPureMaxSkillValue</a>
  <a id="Player:GetPureSkillValue" class="fn" href="../Player/GetPureSkillValue.html">GetPureSkillValue</a>
  <a id="Player:GetQuestLevel" class="fn" href="../Player/GetQuestLevel.html">GetQuestLevel</a>
  <a id="Player:GetQuestRewardStatus" class="fn" href="../Player/GetQuestRewardStatus.html">GetQuestRewardStatus</a>
  <a id="Player:GetQuestStatus" class="fn" href="../Player/GetQuestStatus.html">GetQuestStatus</a>
  <a id="Player:GetRankPoints" class="fn" href="../Player/GetRankPoints.html">GetRankPoints</a>
  <a id="Player:GetReputation" class="fn" href="../Player/GetReputation.html">GetReputation</a>
  <a id="Player:GetReputationRank" class="fn" href="../Player/GetReputationRank.html">GetReputationRank</a>
  <a id="Player:GetReqKillOrCastCurrentCount" class="fn" href="../Player/GetReqKillOrCastCurrentCount.html">GetReqKillOrCastCurrentCount</a>
  <a id="Player:GetRestBonus" class="fn" href="../Player/GetRestBonus.html">GetRestBonus</a>
  <a id="Player:GetSelection" class="fn" href="../Player/GetSelection.html">GetSelection</a>
  <a id="Player:GetShieldBlockValue" class="fn" href="../Player/GetShieldBlockValue.html">GetShieldBlockValue</a>
  <a id="Player:GetSkillPermBonusValue" class="fn" href="../Player/GetSkillPermBonusValue.html">GetSkillPermBonusValue</a>
  <a id="Player:GetSkillTempBonusValue" class="fn" href="../Player/GetSkillTempBonusValue.html">GetSkillTempBonusValue</a>
  <a id="Player:GetSkillValue" class="fn" href="../Player/GetSkillValue.html">GetSkillValue</a>
  <a id="Player:GetSpecsCount" class="fn" href="../Player/GetSpecsCount.html">GetSpecsCount</a>
  <a id="Player:GetSpellCooldownDelay" class="fn" href="../Player/GetSpellCooldownDelay.html">GetSpellCooldownDelay</a>
  <a id="Player:GetSubGroup" class="fn" href="../Player/GetSubGroup.html">GetSubGroup</a>
  <a id="Player:GetTeam" class="fn" href="../Player/GetTeam.html">GetTeam</a>
  <a id="Player:GetTotalPlayedTime" class="fn" href="../Player/GetTotalPlayedTime.html">GetTotalPlayedTime</a>
  <a id="Player:GetTrader" class="fn" href="../Player/GetTrader.html">GetTrader</a>
  <a id="Player:GetXP" class="fn" href="../Player/GetXP.html">GetXP</a>
  <a id="Player:GetXPRestBonus" class="fn" href="../Player/GetXPRestBonus.html">GetXPRestBonus</a>
  <a id="Player:GiveXP" class="fn" href="../Player/GiveXP.html">GiveXP</a>
  <a id="Player:GossipAddQuests" class="fn" href="../Player/GossipAddQuests.html">GossipAddQuests</a>
  <a id="Player:GossipClearMenu" class="fn" href="../Player/GossipClearMenu.html">GossipClearMenu</a>
  <a id="Player:GossipComplete" class="fn" href="../Player/GossipComplete.html">GossipComplete</a>
  <a id="Player:GossipMenuAddItem" class="fn" href="../Player/GossipMenuAddItem.html">GossipMenuAddItem</a>
  <a id="Player:GossipSendMenu" class="fn" href="../Player/GossipSendMenu.html">GossipSendMenu</a>
  <a id="Player:GossipSendPOI" class="fn" href="../Player/GossipSendPOI.html">GossipSendPOI</a>
  <a id="Player:GroupCreate" class="fn" href="../Player/GroupCreate.html">GroupCreate</a>
  <a id="Player:GroupEventHappens" class="fn" href="../Player/GroupEventHappens.html">GroupEventHappens</a>
  <a id="Player:GroupInvite" class="fn" href="../Player/GroupInvite.html">GroupInvite</a>
  <a id="Player:HasAchieved" class="fn" href="../Player/HasAchieved.html">HasAchieved</a>
  <a id="Player:HasAtLoginFlag" class="fn" href="../Player/HasAtLoginFlag.html">HasAtLoginFlag</a>
  <a id="Player:HasCasterSpec" class="fn" href="../Player/HasCasterSpec.html">HasCasterSpec</a>
  <a id="Player:HasHealSpec" class="fn" href="../Player/HasHealSpec.html">HasHealSpec</a>
  <a id="Player:HasItem" class="fn" href="../Player/HasItem.html">HasItem</a>
  <a id="Player:HasMeleeSpec" class="fn" href="../Player/HasMeleeSpec.html">HasMeleeSpec</a>
  <a id="Player:HasQuest" class="fn" href="../Player/HasQuest.html">HasQuest</a>
  <a id="Player:HasQuestForGO" class="fn" href="../Player/HasQuestForGO.html">HasQuestForGO</a>
  <a id="Player:HasQuestForItem" class="fn" href="../Player/HasQuestForItem.html">HasQuestForItem</a>
  <a id="Player:HasSkill" class="fn" href="../Player/HasSkill.html">HasSkill</a>
  <a id="Player:HasSpell" class="fn" href="../Player/HasSpell.html">HasSpell</a>
  <a id="Player:HasSpellCooldown" class="fn" href="../Player/HasSpellCooldown.html">HasSpellCooldown</a>
  <a id="Player:HasTalent" class="fn" href="../Player/HasTalent.html">HasTalent</a>
  <a id="Player:HasTankSpec" class="fn" href="../Player/HasTankSpec.html">HasTankSpec</a>
  <a id="Player:HasTitle" class="fn" href="../Player/HasTitle.html">HasTitle</a>
  <a id="Player:InArena" class="fn" href="../Player/InArena.html">InArena</a>
  <a id="Player:InBattleground" class="fn" href="../Player/InBattleground.html">InBattleground</a>
  <a id="Player:InBattlegroundQueue" class="fn" href="../Player/InBattlegroundQueue.html">InBattlegroundQueue</a>
  <a id="Player:IncompleteQuest" class="fn" href="../Player/IncompleteQuest.html">IncompleteQuest</a>
  <a id="Player:IsAFK" class="fn" href="../Player/IsAFK.html">IsAFK</a>
  <a id="Player:IsAcceptingWhispers" class="fn" href="../Player/IsAcceptingWhispers.html">IsAcceptingWhispers</a>
  <a id="Player:IsAlliance" class="fn" href="../Player/IsAlliance.html">IsAlliance</a>
  <a id="Player:IsDND" class="fn" href="../Player/IsDND.html">IsDND</a>
  <a id="Player:IsFalling" class="fn" href="../Player/IsFalling.html">IsFalling</a>
  <a id="Player:IsFlying" class="fn" href="../Player/IsFlying.html">IsFlying</a>
  <a id="Player:IsGM" class="fn" href="../Player/IsGM.html">IsGM</a>
  <a id="Player:IsGMChat" class="fn" href="../Player/IsGMChat.html">IsGMChat</a>
  <a id="Player:IsGMVisible" class="fn" href="../Player/IsGMVisible.html">IsGMVisible</a>
  <a id="Player:IsGroupVisibleFor" class="fn" href="../Player/IsGroupVisibleFor.html">IsGroupVisibleFor</a>
  <a id="Player:IsHonorOrXPTarget" class="fn" href="../Player/IsHonorOrXPTarget.html">IsHonorOrXPTarget</a>
  <a id="Player:IsHorde" class="fn" href="../Player/IsHorde.html">IsHorde</a>
  <a id="Player:IsImmuneToDamage" class="fn" href="../Player/IsImmuneToDamage.html">IsImmuneToDamage</a>
  <a id="Player:IsInArenaTeam" class="fn" href="../Player/IsInArenaTeam.html">IsInArenaTeam</a>
  <a id="Player:IsInGroup" class="fn" href="../Player/IsInGroup.html">IsInGroup</a>
  <a id="Player:IsInGuild" class="fn" href="../Player/IsInGuild.html">IsInGuild</a>
  <a id="Player:IsInSameGroupWith" class="fn" href="../Player/IsInSameGroupWith.html">IsInSameGroupWith</a>
  <a id="Player:IsInSameRaidWith" class="fn" href="../Player/IsInSameRaidWith.html">IsInSameRaidWith</a>
  <a id="Player:IsInWater" class="fn" href="../Player/IsInWater.html">IsInWater</a>
  <a id="Player:IsMoving" class="fn" href="../Player/IsMoving.html">IsMoving</a>
  <a id="Player:IsRested" class="fn" href="../Player/IsRested.html">IsRested</a>
  <a id="Player:IsTaxiCheater" class="fn" href="../Player/IsTaxiCheater.html">IsTaxiCheater</a>
  <a id="Player:IsVisibleForPlayer" class="fn" href="../Player/IsVisibleForPlayer.html">IsVisibleForPlayer</a>
  <a id="Player:KickPlayer" class="fn" href="../Player/KickPlayer.html">KickPlayer</a>
  <a id="Player:KillPlayer" class="fn" href="../Player/KillPlayer.html">KillPlayer</a>
  <a id="Player:KilledMonsterCredit" class="fn" href="../Player/KilledMonsterCredit.html">KilledMonsterCredit</a>
  <a id="Player:LearnSpell" class="fn" href="../Player/LearnSpell.html">LearnSpell</a>
  <a id="Player:LearnTalent" class="fn" href="../Player/LearnTalent.html">LearnTalent</a>
  <a id="Player:LeaveBattleground" class="fn" href="../Player/LeaveBattleground.html">LeaveBattleground</a>
  <a id="Player:LogoutPlayer" class="fn" href="../Player/LogoutPlayer.html">LogoutPlayer</a>
  <a id="Player:ModifyArenaPoints" class="fn" href="../Player/ModifyArenaPoints.html">ModifyArenaPoints</a>
  <a id="Player:ModifyHonorPoints" class="fn" href="../Player/ModifyHonorPoints.html">ModifyHonorPoints</a>
  <a id="Player:ModifyMoney" class="fn" href="../Player/ModifyMoney.html">ModifyMoney</a>
  <a id="Player:Mute" class="fn" href="../Player/Mute.html">Mute</a>
  <a id="Player:RemoveArenaSpellCooldowns" class="fn" href="../Player/RemoveArenaSpellCooldowns.html">RemoveArenaSpellCooldowns</a>
  <a id="Player:RemoveFromBattlegroundRaid" class="fn" href="../Player/RemoveFromBattlegroundRaid.html">RemoveFromBattlegroundRaid</a>
  <a id="Player:RemoveFromGroup" class="fn" href="../Player/RemoveFromGroup.html">RemoveFromGroup</a>
  <a id="Player:RemoveItem" class="fn" href="../Player/RemoveItem.html">RemoveItem</a>
  <a id="Player:RemoveLifetimeKills" class="fn" href="../Player/RemoveLifetimeKills.html">RemoveLifetimeKills</a>
  <a id="Player:RemoveQuest" class="fn" href="../Player/RemoveQuest.html">RemoveQuest</a>
  <a id="Player:RemoveSpell" class="fn" href="../Player/RemoveSpell.html">RemoveSpell</a>
  <a id="Player:RemovedInsignia" class="fn" href="../Player/RemovedInsignia.html">RemovedInsignia</a>
  <a id="Player:ResetAchievements" class="fn" href="../Player/ResetAchievements.html">ResetAchievements</a>
  <a id="Player:ResetAllCooldowns" class="fn" href="../Player/ResetAllCooldowns.html">ResetAllCooldowns</a>
  <a id="Player:ResetHonor" class="fn" href="../Player/ResetHonor.html">ResetHonor</a>
  <a id="Player:ResetPetTalents" class="fn" href="../Player/ResetPetTalents.html">ResetPetTalents</a>
  <a id="Player:ResetSpellCooldown" class="fn" href="../Player/ResetSpellCooldown.html">ResetSpellCooldown</a>
  <a id="Player:ResetTalents" class="fn" href="../Player/ResetTalents.html">ResetTalents</a>
  <a id="Player:ResetTalentsCost" class="fn" href="../Player/ResetTalentsCost.html">ResetTalentsCost</a>
  <a id="Player:ResetTypeCooldowns" class="fn" href="../Player/ResetTypeCooldowns.html">ResetTypeCooldowns</a>
  <a id="Player:ResurrectPlayer" class="fn" href="../Player/ResurrectPlayer.html">ResurrectPlayer</a>
  <a id="Player:RewardQuest" class="fn" href="../Player/RewardQuest.html">RewardQuest</a>
  <a id="Player:RunCommand" class="fn" href="../Player/RunCommand.html">RunCommand</a>
  <a id="Player:SaveToDB" class="fn" href="../Player/SaveToDB.html">SaveToDB</a>
  <a id="Player:Say" class="fn" href="../Player/Say.html">Say</a>
  <a id="Player:SendAddonMessage" class="fn" href="../Player/SendAddonMessage.html">SendAddonMessage</a>
  <a id="Player:SendAreaTriggerMessage" class="fn" href="../Player/SendAreaTriggerMessage.html">SendAreaTriggerMessage</a>
  <a id="Player:SendAuctionMenu" class="fn" href="../Player/SendAuctionMenu.html">SendAuctionMenu</a>
  <a id="Player:SendBroadcastMessage" class="fn" href="../Player/SendBroadcastMessage.html">SendBroadcastMessage</a>
  <a id="Player:SendCinematicStart" class="fn" href="../Player/SendCinematicStart.html">SendCinematicStart</a>
  <a id="Player:SendGuildInvite" class="fn" href="../Player/SendGuildInvite.html">SendGuildInvite</a>
  <a id="Player:SendListInventory" class="fn" href="../Player/SendListInventory.html">SendListInventory</a>
  <a id="Player:SendMovieStart" class="fn" href="../Player/SendMovieStart.html">SendMovieStart</a>
  <a id="Player:SendNotification" class="fn" href="../Player/SendNotification.html">SendNotification</a>
  <a id="Player:SendPacket" class="fn" href="../Player/SendPacket.html">SendPacket</a>
  <a id="Player:SendQuestTemplate" class="fn" href="../Player/SendQuestTemplate.html">SendQuestTemplate</a>
  <a id="Player:SendShowBank" class="fn" href="../Player/SendShowBank.html">SendShowBank</a>
  <a id="Player:SendShowMailBox" class="fn" href="../Player/SendShowMailBox.html">SendShowMailBox</a>
  <a id="Player:SendSpiritResurrect" class="fn" href="../Player/SendSpiritResurrect.html">SendSpiritResurrect</a>
  <a id="Player:SendTabardVendorActivate" class="fn" href="../Player/SendTabardVendorActivate.html">SendTabardVendorActivate</a>
  <a id="Player:SendTaxiMenu" class="fn" href="../Player/SendTaxiMenu.html">SendTaxiMenu</a>
  <a id="Player:SendTrainerList" class="fn" href="../Player/SendTrainerList.html">SendTrainerList</a>
  <a id="Player:SendUpdateWorldState" class="fn" href="../Player/SendUpdateWorldState.html">SendUpdateWorldState</a>
  <a id="Player:SetAcceptWhispers" class="fn" href="../Player/SetAcceptWhispers.html">SetAcceptWhispers</a>
  <a id="Player:SetAchievement" class="fn" href="../Player/SetAchievement.html">SetAchievement</a>
  <a id="Player:SetArenaPoints" class="fn" href="../Player/SetArenaPoints.html">SetArenaPoints</a>
  <a id="Player:SetAtLoginFlag" class="fn" href="../Player/SetAtLoginFlag.html">SetAtLoginFlag</a>
  <a id="Player:SetBindPoint" class="fn" href="../Player/SetBindPoint.html">SetBindPoint</a>
  <a id="Player:SetCoinage" class="fn" href="../Player/SetCoinage.html">SetCoinage</a>
  <a id="Player:SetDrunkValue" class="fn" href="../Player/SetDrunkValue.html">SetDrunkValue</a>
  <a id="Player:SetFFA" class="fn" href="../Player/SetFFA.html">SetFFA</a>
  <a id="Player:SetFactionForRace" class="fn" href="../Player/SetFactionForRace.html">SetFactionForRace</a>
  <a id="Player:SetFreeTalentPoints" class="fn" href="../Player/SetFreeTalentPoints.html">SetFreeTalentPoints</a>
  <a id="Player:SetGMChat" class="fn" href="../Player/SetGMChat.html">SetGMChat</a>
  <a id="Player:SetGMVisible" class="fn" href="../Player/SetGMVisible.html">SetGMVisible</a>
  <a id="Player:SetGameMaster" class="fn" href="../Player/SetGameMaster.html">SetGameMaster</a>
  <a id="Player:SetGender" class="fn" href="../Player/SetGender.html">SetGender</a>
  <a id="Player:SetGlyph" class="fn" href="../Player/SetGlyph.html">SetGlyph</a>
  <a id="Player:SetGuildRank" class="fn" href="../Player/SetGuildRank.html">SetGuildRank</a>
  <a id="Player:SetHonorLastWeekStandingPos" class="fn" href="../Player/SetHonorLastWeekStandingPos.html">SetHonorLastWeekStandingPos</a>
  <a id="Player:SetHonorPoints" class="fn" href="../Player/SetHonorPoints.html">SetHonorPoints</a>
  <a id="Player:SetHonorStoredKills" class="fn" href="../Player/SetHonorStoredKills.html">SetHonorStoredKills</a>
  <a id="Player:SetKnownTitle" class="fn" href="../Player/SetKnownTitle.html">SetKnownTitle</a>
  <a id="Player:SetLifetimeKills" class="fn" href="../Player/SetLifetimeKills.html">SetLifetimeKills</a>
  <a id="Player:SetPlayerLock" class="fn" href="../Player/SetPlayerLock.html">SetPlayerLock</a>
  <a id="Player:SetPvPDeath" class="fn" href="../Player/SetPvPDeath.html">SetPvPDeath</a>
  <a id="Player:SetQuestStatus" class="fn" href="../Player/SetQuestStatus.html">SetQuestStatus</a>
  <a id="Player:SetRankPoints" class="fn" href="../Player/SetRankPoints.html">SetRankPoints</a>
  <a id="Player:SetReputation" class="fn" href="../Player/SetReputation.html">SetReputation</a>
  <a id="Player:SetRestBonus" class="fn" href="../Player/SetRestBonus.html">SetRestBonus</a>
  <a id="Player:SetSheath" class="fn" href="../Player/SetSheath.html">SetSheath</a>
  <a id="Player:SetSkill" class="fn" href="../Player/SetSkill.html">SetSkill</a>
  <a id="Player:SetSpellPower" class="fn" href="../Player/SetSpellPower.html">SetSpellPower</a>
  <a id="Player:SetTaxiCheat" class="fn" href="../Player/SetTaxiCheat.html">SetTaxiCheat</a>
  <a id="Player:SpawnBones" class="fn" href="../Player/SpawnBones.html">SpawnBones</a>
  <a id="Player:StartTaxi" class="fn" href="../Player/StartTaxi.html">StartTaxi</a>
  <a id="Player:SummonPlayer" class="fn" href="../Player/SummonPlayer.html">SummonPlayer</a>
  <a id="Player:TalkedToCreature" class="fn" href="../Player/TalkedToCreature.html">TalkedToCreature</a>
  <a id="Player:Teleport" class="fn" href="../Player/Teleport.html">Teleport</a>
  <a id="Player:TextEmote" class="fn" href="../Player/TextEmote.html">TextEmote</a>
  <a id="Player:ToggleAFK" class="fn" href="../Player/ToggleAFK.html">ToggleAFK</a>
  <a id="Player:ToggleDND" class="fn" href="../Player/ToggleDND.html">ToggleDND</a>
  <a id="Player:UnbindAllInstances" class="fn" href="../Player/UnbindAllInstances.html">UnbindAllInstances</a>
  <a id="Player:UnbindInstance" class="fn" href="../Player/UnbindInstance.html">UnbindInstance</a>
  <a id="Player:UnsetKnownTitle" class="fn" href="../Player/UnsetKnownTitle.html">UnsetKnownTitle</a>
  <a id="Player:UpdateHonor" class="fn" href="../Player/UpdateHonor.html">UpdateHonor</a>
  <a id="Player:UpdatePlayerSetting" class="fn" href="../Player/UpdatePlayerSetting.html">UpdatePlayerSetting</a>
  <a id="Player:Whisper" class="fn" href="../Player/Whisper.html">Whisper</a>
  <a id="Player:Yell" class="fn" href="../Player/Yell.html">Yell</a>
`);