AzerothCore: boss_halion::boss_halionAI Struct Reference
boss_halion::boss_halionAI Struct Reference
Public Member Functions
boss_halionAI (Creature *creature)
void Reset () override
void JustSummoned (Creature *summon) override
bool CanAIAttack (Unit const *who) const override
bool IsAnyPlayerValid ()
void EnterEvadeMode (EvadeReason why) override
void AttackStart (Unit *who) override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void KilledUnit (Unit *victim) override
void JustDied (Unit *killer) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events2
uint32 _livingEmberCount
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_halionAI()
boss_halion::boss_halionAI::boss_halionAI (Creature * creature) inline
                                          : BossAI(creature, DATA_HALION)
        {
        }
Member Function Documentation
AttackStart()
void boss_halion::boss_halionAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            me->SetReactState(REACT_AGGRESSIVE);
            BossAI::AttackStart(who);
        }
References UnitAI::AttackStart(), ScriptedAI::me, REACT_AGGRESSIVE, and Creature::SetReactState().
CanAIAttack()
bool boss_halion::boss_halionAI::CanAIAttack (Unit const * who) const inline override virtual
Reimplemented from UnitAI.
        {
            return me->GetHomePosition().GetExactDist2d(who) < 52.0f;
        }
References Creature::GetHomePosition(), and ScriptedAI::me.
DamageTaken()
void boss_halion::boss_halionAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
        {
            if (events.GetNextEventTime(EVENT_CHECK_HEALTH) != 0)
                return;
            if (!attacker || !me->InSamePhase(attacker))
                return;
            if (Creature* controller = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_HALION_CONTROLLER)))
                controller->AI()->SetData(DATA_MATERIAL_DAMAGE_TAKEN, damage);
        }
References DATA_MATERIAL_DAMAGE_TAKEN, EVENT_CHECK_HEALTH, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::InSamePhase(), BossAI::instance, ScriptedAI::me, and NPC_HALION_CONTROLLER.
EnterEvadeMode()
void boss_halion::boss_halionAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from BossAI.
        {
            if (IsAnyPlayerValid())
                return;
            instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
            if (Creature* controller = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_HALION_CONTROLLER)))
                controller->AI()->DoAction(ACTION_RESET_ENCOUNTER);
            BossAI::EnterEvadeMode(why);
        }
References ACTION_RESET_ENCOUNTER, ENCOUNTER_FRAME_DISENGAGE, BossAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, IsAnyPlayerValid(), ScriptedAI::me, NPC_HALION_CONTROLLER, and InstanceScript::SendEncounterUnit().
IsAnyPlayerValid()
bool boss_halion::boss_halionAI::IsAnyPlayerValid () inline
        {
            Map::PlayerList const& playerList = me->GetMap()->GetPlayers();
            for(Map::PlayerList::const_iterator itr = playerList.begin(); itr != playerList.end(); ++itr)
                if (Player* player = itr->GetSource())
                    if (!player->IsGameMaster() && player->IsAlive() && me->GetHomePosition().GetExactDist2d(player) < 52.0f && me->IsWithinLOSInMap(player) && !player->HasInvisibilityAura() && !player->HasStealthAura() && !player->HasUnattackableAura())
                        return true;
            return false;
        }
References MapRefMgr::begin(), MapRefMgr::end(), Creature::GetHomePosition(), WorldObject::GetMap(), Map::GetPlayers(), WorldObject::IsWithinLOSInMap(), and ScriptedAI::me.
Referenced by EnterEvadeMode().
JustDied()
void boss_halion::boss_halionAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
        {
            BossAI::JustDied(killer);
            Talk(SAY_DEATH);
            instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
            me->CastSpell(me, SPELL_CLEAR_DEBUFFS, false);
            if (Creature* twilightHalion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_TWILIGHT_HALION)))
                if (twilightHalion->IsAlive())
                    Unit::Kill(twilightHalion, twilightHalion);
            if (Creature* controller = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_HALION_CONTROLLER)))
                if (controller->IsAlive())
                    Unit::Kill(controller, controller);
        }
References Unit::CastSpell(), ENCOUNTER_FRAME_DISENGAGE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, BossAI::JustDied(), Unit::Kill(), ScriptedAI::me, NPC_HALION_CONTROLLER, NPC_TWILIGHT_HALION, SAY_DEATH, InstanceScript::SendEncounterUnit(), and SPELL_CLEAR_DEBUFFS.
JustEngagedWith()
void boss_halion::boss_halionAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            BossAI::JustEngagedWith(who);
            Talk(SAY_AGGRO);
            instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, me, 1);
            events.ScheduleEvent(EVENT_CLEAVE, 8s, 10s);
            events.ScheduleEvent(EVENT_TAIL_LASH, 10s);
            events.ScheduleEvent(EVENT_BREATH, 10s, 15s);
            events.ScheduleEvent(EVENT_ACTIVATE_FIREWALL, 5s);
            events.ScheduleEvent(EVENT_METEOR_STRIKE, 20s, 25s);
            events.ScheduleEvent(EVENT_FIERY_COMBUSTION, 15s, 18s);
            events.ScheduleEvent(EVENT_CHECK_HEALTH, 1s);
            _events2.ScheduleEvent(EVENT_TRIGGER_BERSERK, 8min);
        }
References _events2, ENCOUNTER_FRAME_ENGAGE, EVENT_ACTIVATE_FIREWALL, EVENT_BREATH, EVENT_CHECK_HEALTH, EVENT_CLEAVE, EVENT_FIERY_COMBUSTION, EVENT_METEOR_STRIKE, EVENT_TAIL_LASH, EVENT_TRIGGER_BERSERK, BossAI::instance, BossAI::JustEngagedWith(), ScriptedAI::me, SAY_AGGRO, EventMap::ScheduleEvent(), and InstanceScript::SendEncounterUnit().
JustSummoned()
void boss_halion::boss_halionAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            summons.Summon(summon);
            switch (summon->GetEntry())
            {
                case NPC_METEOR_STRIKE_MARK:
                    summon->CastSpell(summon, SPELL_METEOR_STRIKE_COUNTDOWN, false);
                    summon->CastSpell(summon, SPELL_BIRTH_NO_VISUAL, false);
                    break;
                case NPC_METEOR_STRIKE_FLAME:
                    if (Is25ManRaid() && IsHeroic() && roll_chance_i(90) && summons.GetEntryCount(NPC_LIVING_EMBER) < _livingEmberCount + 12)
                        if (Creature* ember = me->SummonCreature(NPC_LIVING_EMBER, *summon, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 1000))
{
                            ember->SetVisible(false);
                        }
                    [[fallthrough]];
                case NPC_METEOR_STRIKE_NORTH:
                case NPC_METEOR_STRIKE_SOUTH:
                case NPC_METEOR_STRIKE_WEST:
                case NPC_METEOR_STRIKE_EAST:
                    summon->CastSpell(summon, SPELL_METEOR_STRIKE_FIRE_AURA_2, true);
                    if (summons.GetEntryCount(NPC_METEOR_STRIKE_FLAME) <= 16)
                        summon->CastSpell(summon, SPELL_METEOR_STRIKE_SPREAD, true);
                    if (Unit* summoner = summon->ToTempSummon()->GetSummonerUnit())
                        summon->SetOrientation(summoner->GetAngle(summon));
                    break;
            }
        }
References _livingEmberCount, Unit::CastSpell(), Object::GetEntry(), SummonList::GetEntryCount(), TempSummon::GetSummonerUnit(), ScriptedAI::Is25ManRaid(), ScriptedAI::IsHeroic(), ScriptedAI::me, NPC_LIVING_EMBER, NPC_METEOR_STRIKE_EAST, NPC_METEOR_STRIKE_FLAME, NPC_METEOR_STRIKE_MARK, NPC_METEOR_STRIKE_NORTH, NPC_METEOR_STRIKE_SOUTH, NPC_METEOR_STRIKE_WEST, roll_chance_i(), Position::SetOrientation(), SPELL_BIRTH_NO_VISUAL, SPELL_METEOR_STRIKE_COUNTDOWN, SPELL_METEOR_STRIKE_FIRE_AURA_2, SPELL_METEOR_STRIKE_SPREAD, SummonList::Summon(), WorldObject::SummonCreature(), BossAI::summons, TEMPSUMMON_CORPSE_TIMED_DESPAWN, and Unit::ToTempSummon().
KilledUnit()
void boss_halion::boss_halionAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->IsPlayer() && events.GetNextEventTime(EVENT_KILL_TALK) == 0)
            {
                Talk(SAY_KILL);
                events.ScheduleEvent(EVENT_KILL_TALK, 6s);
            }
        }
References EVENT_KILL_TALK, Object::IsPlayer(), and SAY_KILL.
Reset()
void boss_halion::boss_halionAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            _livingEmberCount = 0;
            BossAI::Reset();
            me->RemoveAurasDueToSpell(SPELL_TWILIGHT_PHASING);
            me->CastSpell(me, SPELL_CLEAR_DEBUFFS, false);
            me->SetVisible(false);
            me->SetReactState(REACT_PASSIVE);
            _events2.Reset();
            _events2.RescheduleEvent(EVENT_HALION_VISIBILITY, 30s);
        }
References _events2, _livingEmberCount, Unit::CastSpell(), EVENT_HALION_VISIBILITY, ScriptedAI::me, REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), EventMap::RescheduleEvent(), EventMap::Reset(), BossAI::Reset(), Creature::SetReactState(), Unit::SetVisible(), SPELL_CLEAR_DEBUFFS, and SPELL_TWILIGHT_PHASING.
UpdateAI()
void boss_halion::boss_halionAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            _events2.Update(diff);
            switch (_events2.ExecuteEvent())
            {
                case EVENT_HALION_VISIBILITY:
                    me->SetVisible(instance->GetBossState(DATA_HALION_INTRO_DONE) == DONE);
                    me->SetReactState(instance->GetBossState(DATA_HALION_INTRO_DONE) == DONE ? REACT_AGGRESSIVE : REACT_PASSIVE);
                    break;
                case EVENT_TRIGGER_BERSERK:
                    me->CastSpell(me, SPELL_BERSERK, true);
                    if (Creature* twilightHalion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_TWILIGHT_HALION)))
                        twilightHalion->CastSpell(twilightHalion, SPELL_BERSERK, true);
                    break;
            }
            if (!UpdateVictim())
                return;
            // Xinef: halion is invisible (second phase)
            if (me->GetDisplayId() != me->GetNativeDisplayId())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_CLEAVE:
                    me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                    events.ScheduleEvent(EVENT_CLEAVE, 8s, 10s);
                    break;
                case EVENT_TAIL_LASH:
                    me->CastSpell(me, SPELL_TAIL_LASH, false);
                    events.ScheduleEvent(EVENT_TAIL_LASH, 10s);
                    break;
                case EVENT_BREATH:
                    me->CastSpell(me->GetVictim(), SPELL_FLAME_BREATH, false);
                    events.ScheduleEvent(EVENT_BREATH, 10s, 12s);
                    break;
                case EVENT_ACTIVATE_FIREWALL:
                    instance->HandleGameObject(instance->GetGuidData(GO_FLAME_RING), false, nullptr);
                    instance->HandleGameObject(instance->GetGuidData(GO_TWILIGHT_FLAME_RING), false, nullptr);
                    break;
                case EVENT_METEOR_STRIKE:
                    _livingEmberCount = summons.GetEntryCount(NPC_LIVING_EMBER);
                    me->CastCustomSpell(SPELL_METEOR_STRIKE_TARGETING, SPELLVALUE_MAX_TARGETS, 1, me, false);
                    Talk(SAY_METEOR_STRIKE);
                    events.ScheduleEvent(EVENT_METEOR_STRIKE, 40s);
                    break;
                case EVENT_FIERY_COMBUSTION:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 1, 100.0f, true, true, -SPELL_TWILIGHT_REALM))
                        me->CastSpell(target, SPELL_FIERY_COMBUSTION, false);
                    events.ScheduleEvent(EVENT_FIERY_COMBUSTION, 25s);
                    break;
                case EVENT_CHECK_HEALTH:
                    if (me->HealthBelowPct(75))
                    {
                        Talk(SAY_PHASE_TWO);
                        me->CastSpell(me, SPELL_TWILIGHT_PHASING, false);
                        events.DelayEvents(10s);
                        return;
                    }
                    events.ScheduleEvent(EVENT_CHECK_HEALTH, 1s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References _events2, _livingEmberCount, Unit::CastCustomSpell(), Unit::CastSpell(), DATA_HALION_INTRO_DONE, UnitAI::DoMeleeAttackIfReady(), DONE, EVENT_ACTIVATE_FIREWALL, EVENT_BREATH, EVENT_CHECK_HEALTH, EVENT_CLEAVE, EVENT_FIERY_COMBUSTION, EVENT_HALION_VISIBILITY, EVENT_METEOR_STRIKE, EVENT_TAIL_LASH, EVENT_TRIGGER_BERSERK, EventMap::ExecuteEvent(), InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), Unit::GetDisplayId(), SummonList::GetEntryCount(), InstanceScript::GetGuidData(), Unit::GetNativeDisplayId(), Unit::GetVictim(), GO_FLAME_RING, GO_TWILIGHT_FLAME_RING, InstanceScript::HandleGameObject(), Unit::HasUnitState(), Unit::HealthBelowPct(), BossAI::instance, ScriptedAI::me, NPC_LIVING_EMBER, NPC_TWILIGHT_HALION, REACT_AGGRESSIVE, REACT_PASSIVE, SAY_METEOR_STRIKE, SAY_PHASE_TWO, UnitAI::SelectTarget(), Creature::SetReactState(), Unit::SetVisible(), SPELL_BERSERK, SPELL_CLEAVE, SPELL_FIERY_COMBUSTION, SPELL_FLAME_BREATH, SPELL_METEOR_STRIKE_TARGETING, SPELL_TAIL_LASH, SPELL_TWILIGHT_PHASING, SPELL_TWILIGHT_REALM, SPELLVALUE_MAX_TARGETS, BossAI::summons, UNIT_STATE_CASTING, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_events2
EventMap boss_halion::boss_halionAI::_events2 private
Referenced by JustEngagedWith(), Reset(), and UpdateAI().
_livingEmberCount
uint32 boss_halion::boss_halionAI::_livingEmberCount private
Referenced by JustSummoned(), Reset(), and UpdateAI().