AzerothCore: go_flames::go_flamesAI Struct Reference
go_flames::go_flamesAI Struct Reference
Public Member Functions
go_flamesAI (GameObject *gameObject)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Private Attributes
uint32 timer
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_flamesAI()
go_flames::go_flamesAI::go_flamesAI (GameObject * gameObject) inline
                                            : GameObjectAI(gameObject),
            timer { 0 }
        { }
Member Function Documentation
UpdateAI()
void go_flames::go_flamesAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from GameObjectAI.
        {
            timer += diff;
            if (timer > 3000)
            {
                timer = 0;
                std::list<Player*> players;
                Acore::AnyPlayerExactPositionInGameObjectRangeCheck checker(me, 0.3f);
                Acore::PlayerListSearcher<Acore::AnyPlayerExactPositionInGameObjectRangeCheck> searcher(me, players, checker);
                Cell::VisitWorldObjects(me, searcher, 0.3f);
                if (players.size() > 0)
                {
                    std::list<Player*>::iterator itr = players.begin();
                    std::advance(itr, urand(0, players.size() - 1));
                    if (Creature* trigger = me->SummonTrigger((*itr)->GetPositionX(), (*itr)->GetPositionY(), (*itr)->GetPositionZ(), 0, 2000, true))
                        trigger->CastSpell(trigger, SPELL_FLAMES);
                }
            }
        }
References GameObjectAI::me, SPELL_FLAMES, WorldObject::SummonTrigger(), timer, urand(), and Cell::VisitWorldObjects().
Member Data Documentation
timer
uint32 go_flames::go_flamesAI::timer private
Referenced by UpdateAI().