AzerothCore: Quest Class Reference
Quest Class Reference
#include "QuestDef.h"
Public Types
typedef std::vector< int32 > PrevQuests
typedef std::vector< uint32 > PrevChainQuests
Public Member Functions
Quest (Field *questRecord)
void LoadQuestDetails (Field *fields)
void LoadQuestRequestItems (Field *fields)
void LoadQuestOfferReward (Field *fields)
void LoadQuestTemplateAddon (Field *fields)
uint32 XPValue (uint8 playerLevel=0) const
bool HasFlag (uint32 flag) const
void SetFlag (uint32 flag)
bool HasSpecialFlag (uint32 flag) const
void SetSpecialFlag (uint32 flag)
uint32 GetQuestId () const
uint32 GetQuestMethod () const
int32 GetZoneOrSort () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
int32 GetQuestLevel () const
uint32 GetType () const
uint32 GetRequiredClasses () const
uint32 GetAllowableRaces () const
uint32 GetRequiredSkill () const
uint32 GetRequiredSkillValue () const
uint32 GetRepObjectiveFaction () const
int32 GetRepObjectiveValue () const
uint32 GetRepObjectiveFaction2 () const
int32 GetRepObjectiveValue2 () const
uint32 GetRequiredMinRepFaction () const
int32 GetRequiredMinRepValue () const
uint32 GetRequiredMaxRepFaction () const
int32 GetRequiredMaxRepValue () const
uint32 GetSuggestedPlayers () const
uint32 GetTimeAllowed () const
int32 GetPrevQuestId () const
uint32 GetNextQuestId () const
int32 GetExclusiveGroup () const
uint32 GetNextQuestInChain () const
uint32 GetCharTitleId () const
uint32 GetPlayersSlain () const
uint32 GetBonusTalents () const
int32 GetRewArenaPoints () const
uint32 GetXPId () const
uint32 GetSrcItemId () const
uint32 GetSrcItemCount () const
uint32 GetSrcSpell () const
std::string const & GetTitle () const
std::string const & GetDetails () const
std::string const & GetObjectives () const
std::string const & GetOfferRewardText () const
std::string const & GetRequestItemsText () const
std::string const & GetAreaDescription () const
std::string const & GetCompletedText () const
int32 GetRewOrReqMoney (uint8 playerLevel=0) const
uint32 GetRewHonorAddition () const
float GetRewHonorMultiplier () const
uint32 GetRewMoneyMaxLevel () const
uint32 GetRewSpell () const
int32 GetRewSpellCast () const
uint32 GetRewMailTemplateId () const
uint32 GetRewMailDelaySecs () const
uint32 GetRewMailSenderEntry () const
uint32 GetPOIContinent () const
float GetPOIx () const
float GetPOIy () const
uint32 GetPointOpt () const
uint32 GetIncompleteEmote () const
uint32 GetCompleteEmote () const
bool IsRepeatable () const
bool IsAutoAccept () const
bool IsAutoComplete () const
uint32 GetFlags () const
bool IsDaily () const
bool IsWeekly () const
bool IsMonthly () const
bool IsSeasonal () const
bool IsDailyOrWeekly () const
bool IsRaidQuest (Difficulty difficulty) const
bool IsAllowedInRaid (Difficulty difficulty) const
bool IsDFQuest () const
bool IsPVPQuest () const
uint32 CalculateHonorGain (uint8 level) const
uint32 GetReqItemsCount () const
uint32 GetReqCreatureOrGOcount () const
uint32 GetRewChoiceItemsCount () const
uint32 GetRewItemsCount () const
void InitializeQueryData ()
void SetEventIdForQuest (uint16 eventId)
uint16 GetEventIdForQuest () const
Public Attributes
std::string ObjectiveText [QUEST_OBJECTIVES_COUNT]
uint32 RequiredItemId [QUEST_ITEM_OBJECTIVES_COUNT]
uint32 RequiredItemCount [QUEST_ITEM_OBJECTIVES_COUNT]
uint32 ItemDrop [QUEST_SOURCE_ITEM_IDS_COUNT]
uint32 ItemDropQuantity [QUEST_SOURCE_ITEM_IDS_COUNT]
int32 RequiredNpcOrGo [QUEST_OBJECTIVES_COUNT]
uint32 RequiredNpcOrGoCount [QUEST_OBJECTIVES_COUNT]
uint32 RewardChoiceItemId [QUEST_REWARD_CHOICES_COUNT]
uint32 RewardChoiceItemCount [QUEST_REWARD_CHOICES_COUNT]
uint32 RewardItemId [QUEST_REWARDS_COUNT]
uint32 RewardItemIdCount [QUEST_REWARDS_COUNT]
uint32 RewardFactionId [QUEST_REPUTATIONS_COUNT]
int32 RewardFactionValueId [QUEST_REPUTATIONS_COUNT]
int32 RewardFactionValueIdOverride [QUEST_REPUTATIONS_COUNT]
uint32 DetailsEmote [QUEST_EMOTE_COUNT]
uint32 DetailsEmoteDelay [QUEST_EMOTE_COUNT]
uint32 OfferRewardEmote [QUEST_EMOTE_COUNT]
uint32 OfferRewardEmoteDelay [QUEST_EMOTE_COUNT]
PrevQuests prevQuests
PrevChainQuests prevChainQuests
WorldPacket queryData
Protected Attributes
uint32 Id
uint32 Method
int32 ZoneOrSort
uint32 MinLevel
int32 Level
uint32 Type
uint32 AllowableRaces
uint32 RequiredFactionId1
int32 RequiredFactionValue1
uint32 RequiredFactionId2
int32 RequiredFactionValue2
uint32 SuggestedPlayers
uint32 TimeAllowed
uint32 Flags
uint32 RewardTitleId
uint32 RequiredPlayerKills
uint32 RewardTalents
int32 RewardArenaPoints
uint32 RewardNextQuest
uint32 RewardXPDifficulty
uint32 StartItem
std::string Title
std::string Details
std::string Objectives
std::string OfferRewardText
std::string RequestItemsText
std::string AreaDescription
std::string CompletedText
uint32 RewardHonor
float RewardKillHonor
int32 RewardMoney
uint32 RewardMoneyDifficulty
uint32 RewardDisplaySpell
int32 RewardSpell
uint32 POIContinent
float POIx
float POIy
uint32 POIPriority
uint32 EmoteOnIncomplete
uint32 EmoteOnComplete
uint32 MaxLevel = 0
uint32 RequiredClasses = 0
uint32 SourceSpellid = 0
int32 PrevQuestId = 0
uint32 NextQuestId = 0
int32 ExclusiveGroup = 0
uint32 RewardMailTemplateId = 0
uint32 RewardMailDelay = 0
uint32 RequiredSkillId = 0
uint32 RequiredSkillPoints = 0
uint32 RequiredMinRepFaction = 0
int32 RequiredMinRepValue = 0
uint32 RequiredMaxRepFaction = 0
int32 RequiredMaxRepValue = 0
uint32 StartItemCount = 0
uint32 RewardMailSenderEntry = 0
uint32 SpecialFlags = 0
Private Attributes
uint32 _reqItemsCount
uint32 _reqCreatureOrGOcount
uint32 _rewChoiceItemsCount
uint32 _rewItemsCount
uint16 _eventIdForQuest
Friends
class ObjectMgr
Detailed Description
Member Typedef Documentation
PrevChainQuests
typedef std::vector<uint32> Quest::PrevChainQuests
PrevQuests
typedef std::vector<int32> Quest::PrevQuests
Constructor & Destructor Documentation
Quest()
Quest::Quest (Field * questRecord)
{
    EmoteOnIncomplete = 0;
    EmoteOnComplete = 0;
    _reqItemsCount = 0;
    _reqCreatureOrGOcount = 0;
    _rewItemsCount = 0;
    _rewChoiceItemsCount = 0;
    Id = questRecord[0].Get<uint32>();
    Method = questRecord[1].Get<uint8>();
    Level = questRecord[2].Get<int16>();
    MinLevel = questRecord[3].Get<uint8>();
    ZoneOrSort = questRecord[4].Get<int16>();
    Type = questRecord[5].Get<uint16>();
    SuggestedPlayers = questRecord[6].Get<uint8>();
    TimeAllowed = questRecord[7].Get<uint32>();
    AllowableRaces = questRecord[8].Get<uint32>();
    RequiredFactionId1 = questRecord[9].Get<uint16>();
    RequiredFactionId2 = questRecord[10].Get<uint16>();
    RequiredFactionValue1 = questRecord[11].Get<int32>();
    RequiredFactionValue2 = questRecord[12].Get<int32>();
    RewardNextQuest = questRecord[13].Get<uint32>();
    RewardXPDifficulty = questRecord[14].Get<uint8>();
    RewardMoney = questRecord[15].Get<int32>();
    RewardMoneyDifficulty = questRecord[16].Get<uint32>();
    RewardDisplaySpell = questRecord[17].Get<uint32>();
    RewardSpell = questRecord[18].Get<int32>();
    RewardHonor = questRecord[19].Get<uint32>();
    RewardKillHonor = questRecord[20].Get<float>();
    StartItem = questRecord[21].Get<uint32>();
    Flags = questRecord[22].Get<uint32>();
    RewardTitleId = questRecord[23].Get<uint8>();
    RequiredPlayerKills = questRecord[24].Get<uint8>();
    RewardTalents = questRecord[25].Get<uint8>();
    RewardArenaPoints = questRecord[26].Get<uint16>();
    for (int i = 0; i < QUEST_REWARDS_COUNT; ++i)
    {
        RewardItemId[i] = questRecord[27 + i * 2].Get<uint32>();
        RewardItemIdCount[i] = questRecord[28 + i * 2].Get<uint16>();
        if (RewardItemId[i])
            ++_rewItemsCount;
    }
    for (int i = 0; i < QUEST_REWARD_CHOICES_COUNT; ++i)
    {
        RewardChoiceItemId[i] = questRecord[35 + i * 2].Get<uint32>();
        RewardChoiceItemCount[i] = questRecord[36 + i * 2].Get<uint16>();
        if (RewardChoiceItemId[i])
            ++_rewChoiceItemsCount;
    }
    for (int i = 0; i < QUEST_REPUTATIONS_COUNT; ++i)
    {
        RewardFactionId[i] = questRecord[47 + i * 3].Get<uint16>();
        RewardFactionValueId[i] = questRecord[48 + i * 3].Get<int32>();
        RewardFactionValueIdOverride[i] = questRecord[49 + i * 3].Get<int32>();
    }
    POIContinent = questRecord[62].Get<uint16>();
    POIx = questRecord[63].Get<float>();
    POIy = questRecord[64].Get<float>();
    POIPriority = questRecord[65].Get<uint32>();
    Title = questRecord[66].Get<std::string>();
    Objectives = questRecord[67].Get<std::string>();
    Details = questRecord[68].Get<std::string>();
    AreaDescription = questRecord[69].Get<std::string>();
    CompletedText = questRecord[70].Get<std::string>();
    for (int i = 0; i < QUEST_OBJECTIVES_COUNT; ++i)
    {
        RequiredNpcOrGo[i] = questRecord[71 + i].Get<int32>();
        RequiredNpcOrGoCount[i] = questRecord[75 + i].Get<uint16>();
        ObjectiveText[i] = questRecord[100 + i].Get<std::string>();
        if (RequiredNpcOrGo[i])
            ++_reqCreatureOrGOcount;
    }
    for (int i = 0; i < QUEST_SOURCE_ITEM_IDS_COUNT; ++i)
    {
        ItemDrop[i] = questRecord[79 + i].Get<uint32>();
        ItemDropQuantity[i] = questRecord[83 + i].Get<uint16>();
    }
    for (int i = 0; i < QUEST_ITEM_OBJECTIVES_COUNT; ++i)
    {
        RequiredItemId[i] = questRecord[87 + i].Get<uint32>();
        RequiredItemCount[i] = questRecord[93 + i].Get<uint16>();
        if (RequiredItemId[i])
            ++_reqItemsCount;
    }
    // int8 Unknown0 = questRecord[100].Get<uint8>();
    // int32 VerifiedBuild = questRecord[105].Get<int32>();
    for (int i = 0; i < QUEST_EMOTE_COUNT; ++i)
    {
        DetailsEmote[i] = 0;
        DetailsEmoteDelay[i] = 0;
        OfferRewardEmote[i] = 0;
        OfferRewardEmoteDelay[i] = 0;
    }
    _eventIdForQuest = 0;
    if (sWorld->getBoolConfig(CONFIG_QUEST_IGNORE_AUTO_ACCEPT))
    {
        Flags &= ~QUEST_FLAGS_AUTO_ACCEPT;
    }
    if (sWorld->getBoolConfig(CONFIG_QUEST_IGNORE_AUTO_COMPLETE))
    {
        Flags &= ~QUEST_FLAGS_AUTOCOMPLETE;
    }
}
References _eventIdForQuest, _reqCreatureOrGOcount, _reqItemsCount, _rewChoiceItemsCount, _rewItemsCount, AllowableRaces, AreaDescription, CompletedText, CONFIG_QUEST_IGNORE_AUTO_ACCEPT, CONFIG_QUEST_IGNORE_AUTO_COMPLETE, Details, DetailsEmote, DetailsEmoteDelay, EmoteOnComplete, EmoteOnIncomplete, Flags, Field::Get(), Id, ItemDrop, ItemDropQuantity, Level, Method, MinLevel, Objectives, ObjectiveText, OfferRewardEmote, OfferRewardEmoteDelay, POIContinent, POIPriority, POIx, POIy, QUEST_EMOTE_COUNT, QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_REPUTATIONS_COUNT, QUEST_REWARD_CHOICES_COUNT, QUEST_REWARDS_COUNT, QUEST_SOURCE_ITEM_IDS_COUNT, RequiredFactionId1, RequiredFactionId2, RequiredFactionValue1, RequiredFactionValue2, RequiredItemCount, RequiredItemId, RequiredNpcOrGo, RequiredNpcOrGoCount, RequiredPlayerKills, RewardArenaPoints, RewardChoiceItemCount, RewardChoiceItemId, RewardDisplaySpell, RewardFactionId, RewardFactionValueId, RewardFactionValueIdOverride, RewardHonor, RewardItemId, RewardItemIdCount, RewardKillHonor, RewardMoney, RewardMoneyDifficulty, RewardNextQuest, RewardSpell, RewardTalents, RewardTitleId, RewardXPDifficulty, StartItem, SuggestedPlayers, sWorld, TimeAllowed, Title, Type, and ZoneOrSort.
Member Function Documentation
CalculateHonorGain()
uint32 Quest::CalculateHonorGain (uint8 level) const
{
    if (level > GT_MAX_LEVEL)
        level = GT_MAX_LEVEL;
    uint32 honor = 0;
    if (GetRewHonorAddition() > 0 || GetRewHonorMultiplier() > 0.0f)
    {
        // values stored from 0.. for 1...
        TeamContributionPointsEntry const* tc = sTeamContributionPointsStore.LookupEntry(level);
        if (!tc)
            return 0;
        honor = uint32(tc->value * GetRewHonorMultiplier() * 0.1000000014901161);
        // Xinef: exactly this is calculated above, however with higher precision...
        //honor += Acore::Honor::hk_honor_at_level(level, GetRewHonorMultiplier());
        honor += GetRewHonorAddition();
    }
    return honor;
}
References GetRewHonorAddition(), GetRewHonorMultiplier(), GT_MAX_LEVEL, sTeamContributionPointsStore, and TeamContributionPointsEntry::value.
Referenced by quest_commandscript::HandleQuestReward(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and Player::SendQuestReward().
GetAllowableRaces()
uint32 Quest::GetAllowableRaces () const inline
{ return AllowableRaces; }
References AllowableRaces.
Referenced by Player::SatisfyQuestRace().
GetAreaDescription()
std::string const & Quest::GetAreaDescription () const inline
{ return AreaDescription; }
References AreaDescription.
Referenced by InitializeQueryData(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetBonusTalents()
uint32 Quest::GetBonusTalents () const inline
{ return RewardTalents; }
References RewardTalents.
Referenced by InitializeQueryData(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestQueryResponse(), and Player::SendQuestReward().
GetCharTitleId()
uint32 Quest::GetCharTitleId () const inline
{ return RewardTitleId; }
References RewardTitleId.
Referenced by InitializeQueryData(), ObjectMgr::LoadQuests(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetCompletedText()
std::string const & Quest::GetCompletedText () const inline
{ return CompletedText; }
References CompletedText.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetCompleteEmote()
uint32 Quest::GetCompleteEmote () const inline
{ return EmoteOnComplete; }
References EmoteOnComplete.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetDetails()
std::string const & Quest::GetDetails () const inline
{ return Details; }
References Details.
Referenced by InitializeQueryData(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetEventIdForQuest()
uint16 Quest::GetEventIdForQuest () const inline
{ return _eventIdForQuest; }
References _eventIdForQuest.
Referenced by Player::SatisfyQuestSeasonal(), and Player::SetSeasonalQuestStatus().
GetExclusiveGroup()
int32 Quest::GetExclusiveGroup () const inline
{ return ExclusiveGroup; }
References ExclusiveGroup.
Referenced by Player::SatisfyQuestExclusiveGroup(), and Player::SatisfyQuestPreviousQuest().
GetFlags()
uint32 Quest::GetFlags () const inline
{ return Flags; }
References Flags.
Referenced by InitializeQueryData(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), and PlayerMenu::SendQuestQueryResponse().
GetIncompleteEmote()
uint32 Quest::GetIncompleteEmote () const inline
{ return EmoteOnIncomplete; }
References EmoteOnIncomplete.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetMaxLevel()
uint32 Quest::GetMaxLevel () const inline
{ return MaxLevel; }
References MaxLevel.
Referenced by Player::SatisfyQuestLevel().
GetMinLevel()
uint32 Quest::GetMinLevel () const inline
{ return MinLevel; }
References MinLevel.
Referenced by Player::CanSeeStartQuest(), InitializeQueryData(), Player::SatisfyQuestLevel(), and PlayerMenu::SendQuestQueryResponse().
GetNextQuestId()
uint32 Quest::GetNextQuestId () const inline
{ return NextQuestId; }
References NextQuestId.
Referenced by ObjectMgr::LoadQuests().
GetNextQuestInChain()
uint32 Quest::GetNextQuestInChain () const inline
{ return RewardNextQuest; }
References RewardNextQuest.
Referenced by Player::GetNextQuest(), InitializeQueryData(), Player::SatisfyQuestNextChain(), and PlayerMenu::SendQuestQueryResponse().
GetObjectives()
std::string const & Quest::GetObjectives () const inline
{ return Objectives; }
References Objectives.
Referenced by InitializeQueryData(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetOfferRewardText()
std::string const & Quest::GetOfferRewardText () const inline
{ return OfferRewardText; }
References OfferRewardText.
Referenced by PlayerMenu::SendQuestGiverOfferReward().
GetPlayersSlain()
uint32 Quest::GetPlayersSlain () const inline
{ return RequiredPlayerKills; }
References RequiredPlayerKills.
Referenced by Player::CanCompleteQuest(), quest_commandscript::HandleQuestComplete(), InitializeQueryData(), Player::KilledPlayerCreditForQuest(), PlayerMenu::SendQuestQueryResponse(), and Player::SendQuestUpdateAddPlayer().
GetPOIContinent()
uint32 Quest::GetPOIContinent () const inline
{ return POIContinent; }
References POIContinent.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetPointOpt()
uint32 Quest::GetPointOpt () const inline
{ return POIPriority; }
References POIPriority.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetPOIx()
float Quest::GetPOIx () const inline
{ return POIx; }
References POIx.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetPOIy()
float Quest::GetPOIy () const inline
{ return POIy; }
References POIy.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetPrevQuestId()
int32 Quest::GetPrevQuestId () const inline
{ return PrevQuestId; }
References PrevQuestId.
Referenced by ObjectMgr::LoadQuests().
GetQuestId()
uint32 Quest::GetQuestId () const inline
{ return Id; }
References Id.
Referenced by Player::AddQuest(), Player::AddQuestAndCheckCompletion(), Player::AdjustQuestReqItemCount(), Player::CanRewardQuest(), Player::CanSeeStartQuest(), Player::CanTakeQuest(), npc_wg_quest_giver::GetDialogStatus(), Player::GetQuestDialogStatus(), go_commandscript::HandleGoQuestCommand(), quest_commandscript::HandleQuestAdd(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), quest_commandscript::HandleQuestReward(), InitializeQueryData(), LinkValidator< LinkTags::quest >::IsTextValid(), npc_escortAI::JustDied(), FollowerAI::JustDied(), Player::KilledPlayerCreditForQuest(), ObjectMgr::LoadQuests(), Condition::Meets(), QuestApprenticeAnglerPlayerScript::OnPlayerCompleteQuest(), npc_cos_chromie_start::OnQuestAccept(), npc_cos_chromie_middle::OnQuestAccept(), npc_chicken_cluck::OnQuestAccept(), npc_steward_of_time::OnQuestAccept(), npc_kernobee::OnQuestAccept(), npc_koltira_deathweaver::OnQuestAccept(), pyrewood_ambush::OnQuestAccept(), npc_daphne_stilwell::OnQuestAccept(), npc_mikhail::OnQuestAccept(), npc_kerlonian::OnQuestAccept(), npc_prospector_remtravel::OnQuestAccept(), npc_tooga::OnQuestAccept(), npc_gilthares::OnQuestAccept(), npc_lakota_windsong::OnQuestAccept(), npc_paoka_swiftmountain::OnQuestAccept(), npc_ringo::OnQuestAccept(), npc_engineer_helice::OnQuestAccept(), npc_maghar_captive::OnQuestAccept(), npc_kurenai_captive::OnQuestAccept(), npc_maxx_a_million_escort::OnQuestAccept(), npc_eris_hevenfire::OnQuestAccept(), npc_deathstalker_erland::OnQuestAccept(), npc_tyrion::OnQuestAccept(), npc_cork_gizelton::OnQuestAccept(), npc_shenthul::OnQuestAccept(), npc_kaya_flathoof::OnQuestAccept(), npc_wizzlecrank_shredder::OnQuestAccept(), npc_ame::OnQuestAccept(), npc_ranshalla::OnQuestAccept(), npc_lurgglbr::OnQuestAccept(), npc_mootoo_the_younger::OnQuestAccept(), npc_bonker_togglevolt::OnQuestAccept(), npc_emily::OnQuestAccept(), npc_apothecary_hanes::OnQuestAccept(), npc_battle_at_valhalas::OnQuestAccept(), npc_finklestein::OnQuestAccept(), npc_bessy::OnQuestAccept(), npc_karynaku::OnQuestAccept(), npc_isla_starmane::OnQuestAccept(), npc_doctor::OnQuestAccept(), go_crystal_prison::OnQuestAccept(), go_crystalline_tear::OnQuestAccept(), npc_chicken_cluck::OnQuestComplete(), boss_apothecary_hummel::OnQuestReward(), npc_rocknot::OnQuestReward(), npc_thrall_warchief::OnQuestReward(), npc_thrall_bfu::OnQuestReward(), npc_lady_sylvanas_windrunner::OnQuestReward(), npc_tharnarian::OnQuestReward(), npc_elder_clearwater::OnQuestReward(), npc_riggle_bassbait::OnQuestReward(), Player::PrettyPrintRequirementsQuestList(), SmartGameObjectAI::QuestAccept(), SmartGameObjectAI::QuestReward(), Player::RewardQuest(), Player::SatisfyQuestConditions(), Player::SatisfyQuestDay(), Player::SatisfyQuestExclusiveGroup(), Player::SatisfyQuestMonth(), Player::SatisfyQuestSeasonal(), Player::SatisfyQuestStatus(), Player::SatisfyQuestWeek(), Player::SendQuestConfirmAccept(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), PlayerMenu::SendQuestQueryResponse(), Player::SendQuestReward(), Player::SendQuestUpdateAddCreatureOrGo(), Player::SendQuestUpdateAddPlayer(), npc_costumed_orphan_matron::sQuestAccept(), npc_belnistrasz::npc_belnistraszAI::sQuestAccept(), SmartAI::sQuestAccept(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::sQuestAccept(), npc_ranger_lilatha::sQuestAccept(), npc_rinji::npc_rinjiAI::sQuestAccept(), npc_corporal_keeshan::npc_corporal_keeshanAI::sQuestAccept(), npc_muglash::npc_muglashAI::sQuestAccept(), npc_magwin::npc_magwinAI::sQuestAccept(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::sQuestAccept(), SmartAI::sQuestReward(), and npc_escortAI::Start().
GetQuestLevel()
int32 Quest::GetQuestLevel () const inline
{ return Level; }
References Level.
Referenced by Player::GetQuestLevel(), InitializeQueryData(), Player::PrettyPrintRequirementsQuestList(), and PlayerMenu::SendQuestQueryResponse().
GetQuestMethod()
uint32 Quest::GetQuestMethod () const inline
{ return Method; }
References Method.
Referenced by Player::CanCompleteQuest(), Player::CanRewardQuest(), InitializeQueryData(), ObjectMgr::LoadQuests(), and PlayerMenu::SendQuestQueryResponse().
GetRepObjectiveFaction()
uint32 Quest::GetRepObjectiveFaction () const inline
{ return RequiredFactionId1; }
References RequiredFactionId1.
Referenced by Player::AddQuest(), Player::CanCompleteQuest(), quest_commandscript::HandleQuestComplete(), InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetRepObjectiveFaction2()
uint32 Quest::GetRepObjectiveFaction2 () const inline
{ return RequiredFactionId2; }
References RequiredFactionId2.
Referenced by Player::AddQuest(), quest_commandscript::HandleQuestComplete(), InitializeQueryData(), Player::SatisfyQuestReputation(), and PlayerMenu::SendQuestQueryResponse().
GetRepObjectiveValue()
int32 Quest::GetRepObjectiveValue () const inline
{ return RequiredFactionValue1; }
References RequiredFactionValue1.
Referenced by Player::CanCompleteQuest(), quest_commandscript::HandleQuestComplete(), InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetRepObjectiveValue2()
int32 Quest::GetRepObjectiveValue2 () const inline
{ return RequiredFactionValue2; }
References RequiredFactionValue2.
Referenced by quest_commandscript::HandleQuestComplete(), InitializeQueryData(), Player::SatisfyQuestReputation(), and PlayerMenu::SendQuestQueryResponse().
GetReqCreatureOrGOcount()
uint32 Quest::GetReqCreatureOrGOcount () const inline
{ return _reqCreatureOrGOcount; }
References _reqCreatureOrGOcount.
GetReqItemsCount()
uint32 Quest::GetReqItemsCount () const inline
{ return _reqItemsCount; }
References _reqItemsCount.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetRequestItemsText()
std::string const & Quest::GetRequestItemsText () const inline
{ return RequestItemsText; }
References RequestItemsText.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetRequiredClasses()
uint32 Quest::GetRequiredClasses () const inline
{ return RequiredClasses; }
References RequiredClasses.
Referenced by Player::SatisfyQuestClass().
GetRequiredMaxRepFaction()
uint32 Quest::GetRequiredMaxRepFaction () const inline
{ return RequiredMaxRepFaction; }
References RequiredMaxRepFaction.
Referenced by Player::SatisfyQuestReputation().
GetRequiredMaxRepValue()
int32 Quest::GetRequiredMaxRepValue () const inline
{ return RequiredMaxRepValue; }
References RequiredMaxRepValue.
Referenced by Player::SatisfyQuestReputation().
GetRequiredMinRepFaction()
uint32 Quest::GetRequiredMinRepFaction () const inline
{ return RequiredMinRepFaction; }
References RequiredMinRepFaction.
Referenced by Player::SatisfyQuestReputation().
GetRequiredMinRepValue()
int32 Quest::GetRequiredMinRepValue () const inline
{ return RequiredMinRepValue; }
References RequiredMinRepValue.
Referenced by Player::SatisfyQuestReputation().
GetRequiredSkill()
uint32 Quest::GetRequiredSkill () const inline
{ return RequiredSkillId; }
References RequiredSkillId.
Referenced by Player::SatisfyQuestSkill().
GetRequiredSkillValue()
uint32 Quest::GetRequiredSkillValue () const inline
{ return RequiredSkillPoints; }
References RequiredSkillPoints.
Referenced by Player::SatisfyQuestSkill().
GetRewArenaPoints()
int32 Quest::GetRewArenaPoints () const inline
{return RewardArenaPoints; }
References RewardArenaPoints.
Referenced by quest_commandscript::HandleQuestReward(), InitializeQueryData(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestQueryResponse(), and Player::SendQuestReward().
GetRewChoiceItemsCount()
uint32 Quest::GetRewChoiceItemsCount () const inline
{ return _rewChoiceItemsCount; }
References _rewChoiceItemsCount.
Referenced by Player::CanRewardQuest(), quest_commandscript::HandleQuestReward(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetRewHonorAddition()
uint32 Quest::GetRewHonorAddition () const inline
{ return RewardHonor; }
References RewardHonor.
Referenced by CalculateHonorGain(), InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetRewHonorMultiplier()
float Quest::GetRewHonorMultiplier () const inline
{ return RewardKillHonor; }
References RewardKillHonor.
Referenced by CalculateHonorGain(), InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetRewItemsCount()
uint32 Quest::GetRewItemsCount () const inline
{ return _rewItemsCount; }
References _rewItemsCount.
Referenced by Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), quest_commandscript::HandleQuestReward(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetRewMailDelaySecs()
uint32 Quest::GetRewMailDelaySecs () const inline
{ return RewardMailDelay; }
References RewardMailDelay.
Referenced by quest_commandscript::HandleQuestReward(), and Player::RewardQuest().
GetRewMailSenderEntry()
uint32 Quest::GetRewMailSenderEntry () const inline
{ return RewardMailSenderEntry; }
References RewardMailSenderEntry.
Referenced by quest_commandscript::HandleQuestReward(), and Player::RewardQuest().
GetRewMailTemplateId()
uint32 Quest::GetRewMailTemplateId () const inline
{ return RewardMailTemplateId; }
References RewardMailTemplateId.
Referenced by quest_commandscript::HandleQuestReward(), and Player::RewardQuest().
GetRewMoneyMaxLevel()
uint32 Quest::GetRewMoneyMaxLevel () const
{
    uint32 rewMoney = 0;
    if (HasFlag(QUEST_FLAGS_NO_MONEY_FROM_XP))
        return rewMoney;
    rewMoney = (XPValue(sWorld->getIntConfig(CONFIG_MAX_PLAYER_LEVEL)) * (6 * COPPER));
    // https://wowpedia.fandom.com/wiki/Quest?oldid=1035002 Formula is XP gained * 6c
    return static_cast<int32>(rewMoney * sWorld->getRate(RATE_REWARD_BONUS_MONEY));
}
References CONFIG_MAX_PLAYER_LEVEL, COPPER, HasFlag(), QUEST_FLAGS_NO_MONEY_FROM_XP, RATE_REWARD_BONUS_MONEY, sWorld, and XPValue().
Referenced by quest_commandscript::HandleQuestReward(), InitializeQueryData(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestQueryResponse(), and Player::SendQuestReward().
GetRewOrReqMoney()
int32 Quest::GetRewOrReqMoney (uint8 playerLevel = 0) const
{
    int32 rewardedMoney = RewardMoney;
    if (rewardedMoney < 0)
    {
        return rewardedMoney;
    }
    if (playerLevel && RewardMoneyDifficulty)
    {
        if (uint32 questRewardedMoney = sObjectMgr->GetQuestMoneyReward(playerLevel, RewardMoneyDifficulty))
        {
            rewardedMoney = questRewardedMoney;
        }
    }
    return static_cast<int32>(rewardedMoney * sWorld->getRate(RATE_REWARD_QUEST_MONEY));
}
References RATE_REWARD_QUEST_MONEY, RewardMoney, RewardMoneyDifficulty, sObjectMgr, and sWorld.
Referenced by Player::CanCompleteQuest(), Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestReward(), InitializeQueryData(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), PlayerMenu::SendQuestQueryResponse(), and Player::SendQuestReward().
GetRewSpell()
uint32 Quest::GetRewSpell () const inline
{ return RewardDisplaySpell; }
References RewardDisplaySpell.
Referenced by InitializeQueryData(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetRewSpellCast()
int32 Quest::GetRewSpellCast () const inline
{ return RewardSpell; }
References RewardSpell.
Referenced by InitializeQueryData(), Player::learnQuestRewardedSpells(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetSrcItemCount()
uint32 Quest::GetSrcItemCount () const inline
{ return StartItemCount; }
References StartItemCount.
Referenced by Player::CanAddQuest(), Player::GiveQuestSourceItem(), and Player::TakeQuestSourceItem().
GetSrcItemId()
uint32 Quest::GetSrcItemId () const inline
{ return StartItem; }
References StartItem.
Referenced by Player::CanAddQuest(), Player::GiveQuestSourceItem(), InitializeQueryData(), PlayerMenu::SendQuestQueryResponse(), and Player::TakeQuestSourceItem().
GetSrcSpell()
uint32 Quest::GetSrcSpell () const inline
{ return SourceSpellid; }
References SourceSpellid.
GetSuggestedPlayers()
uint32 Quest::GetSuggestedPlayers () const inline
{ return SuggestedPlayers; }
References SuggestedPlayers.
Referenced by InitializeQueryData(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), and PlayerMenu::SendQuestQueryResponse().
GetTimeAllowed()
uint32 Quest::GetTimeAllowed () const inline
{ return TimeAllowed; }
References TimeAllowed.
Referenced by Player::AddQuest().
GetTitle()
std::string const & Quest::GetTitle () const inline
{ return Title; }
References Title.
Referenced by quest_commandscript::HandleQuestAdd(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), quest_commandscript::HandleQuestReward(), InitializeQueryData(), LinkValidator< LinkTags::quest >::IsTextValid(), Player::PrettyPrintRequirementsQuestList(), Player::SendQuestConfirmAccept(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), and PlayerMenu::SendQuestQueryResponse().
GetType()
uint32 Quest::GetType () const inline
{ return Type; }
References Type.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetXPId()
uint32 Quest::GetXPId () const inline
{ return RewardXPDifficulty; }
References RewardXPDifficulty.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetZoneOrSort()
int32 Quest::GetZoneOrSort () const inline
{ return ZoneOrSort; }
References ZoneOrSort.
Referenced by InitializeQueryData(), Player::KilledPlayerCredit(), Player::RewardQuest(), PlayerMenu::SendQuestQueryResponse(), and AchievementMgr::UpdateAchievementCriteria().
HasFlag()
bool Quest::HasFlag (uint32 flag) const inline
{ return (Flags & flag) != 0; }
References Flags.
Referenced by Player::AddQuest(), Player::CanShareQuest(), Player::CompleteQuest(), Spell::EffectQuestClear(), GetRewMoneyMaxLevel(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), Player::HasPvPForcingQuest(), InitializeQueryData(), IsAutoAccept(), IsAutoComplete(), Player::RewardQuest(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
HasSpecialFlag()
bool Quest::HasSpecialFlag (uint32 flag) const inline
{ return (SpecialFlags & flag) != 0; }
References SpecialFlags.
Referenced by Player::AddQuest(), Player::AdjustQuestReqItemCount(), Player::CanCompleteQuest(), Player::CanCompleteRepeatableQuest(), Player::CanRewardQuest(), quest_commandscript::HandleQuestComplete(), Player::ItemAddedQuestCheck(), Player::ItemRemovedQuestCheck(), Player::KillCreditGO(), Player::KilledMonsterCredit(), Player::KilledPlayerCredit(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuests(), ObjectMgr::LoadScripts(), Player::RewardReputation(), Player::SatisfyQuestTimed(), Player::TalkedToCreature(), and AchievementMgr::UpdateAchievementCriteria().
InitializeQueryData()
void Quest::InitializeQueryData ()
{
    queryData.Initialize(SMSG_QUEST_QUERY_RESPONSE, 1);
    queryData << uint32(GetQuestId());                    // quest id
    queryData << uint32(GetQuestMethod());                // Accepted values: 0, 1 or 2. 0 == IsAutoComplete() (skip objectives/details)
    queryData << uint32(GetQuestLevel());                 // may be -1, static data, in other cases must be used dynamic level: Player::GetQuestLevel (0 is not known, but assuming this is no longer valid for quest intended for client)
    queryData << uint32(GetMinLevel());                   // min level
    queryData << uint32(GetZoneOrSort());                 // zone or sort to display in quest log
    queryData << uint32(GetType());                       // quest type
    queryData << uint32(GetSuggestedPlayers());           // suggested players count
    queryData << uint32(GetRepObjectiveFaction());        // shown in quest log as part of quest objective
    queryData << uint32(GetRepObjectiveValue());          // shown in quest log as part of quest objective
    queryData << uint32(GetRepObjectiveFaction2());       // shown in quest log as part of quest objective OPPOSITE faction
    queryData << uint32(GetRepObjectiveValue2());         // shown in quest log as part of quest objective OPPOSITE faction
    queryData << uint32(GetNextQuestInChain());           // client will request this quest from NPC, if not 0
    queryData << uint32(GetXPId());                       // used for calculating rewarded experience
    if (HasFlag(QUEST_FLAGS_HIDDEN_REWARDS))
        queryData << uint32(0);                           // Hide money rewarded
    else
        queryData << int32(GetRewOrReqMoney());           // reward money (below max lvl)
    queryData << uint32(GetRewMoneyMaxLevel());           // used in XP calculation at client
    queryData << uint32(GetRewSpell());                   // reward spell, this spell will display (icon) (casted if RewSpellCast == 0)
    queryData << int32(GetRewSpellCast());                // casted spell
    // rewarded honor points
    queryData << uint32(GetRewHonorAddition());
    queryData << float(GetRewHonorMultiplier());
    queryData << uint32(GetSrcItemId());                  // source item id
    queryData << uint32(GetFlags() & 0xFFFF);             // quest flags
    queryData << uint32(GetCharTitleId());                // CharTitleId, new 2.4.0, player gets this title (id from CharTitles)
    queryData << uint32(GetPlayersSlain());               // players slain
    queryData << uint32(GetBonusTalents());               // bonus talents
    queryData << uint32(GetRewArenaPoints());             // bonus arena points
    queryData << uint32(0);                                      // review rep show mask
    if (HasFlag(QUEST_FLAGS_HIDDEN_REWARDS))
    {
        for (uint32 i = 0; i < QUEST_REWARDS_COUNT; ++i)
            queryData << uint32(0) << uint32(0);
        for (uint32 i = 0; i < QUEST_REWARD_CHOICES_COUNT; ++i)
            queryData << uint32(0) << uint32(0);
    }
    else
    {
        for (uint32 i = 0; i < QUEST_REWARDS_COUNT; ++i)
        {
            queryData << uint32(RewardItemId[i]);
            queryData << uint32(RewardItemIdCount[i]);
        }
        for (uint32 i = 0; i < QUEST_REWARD_CHOICES_COUNT; ++i)
        {
            queryData << uint32(RewardChoiceItemId[i]);
            queryData << uint32(RewardChoiceItemCount[i]);
        }
    }
    for (uint32 i = 0; i < QUEST_REPUTATIONS_COUNT; ++i)        // reward factions ids
        queryData << uint32(RewardFactionId[i]);
    for (uint32 i = 0; i < QUEST_REPUTATIONS_COUNT; ++i)        // columnid+1 QuestFactionReward.dbc?
        queryData << int32(RewardFactionValueId[i]);
    for (int i = 0; i < QUEST_REPUTATIONS_COUNT; ++i)           // unk (0)
        queryData << int32(RewardFactionValueIdOverride[i]);
    queryData << GetPOIContinent();
    queryData << GetPOIx();
    queryData << GetPOIy();
    queryData << GetPointOpt();
    queryData << GetTitle();
    queryData << GetObjectives();
    queryData << GetDetails();
    queryData << GetAreaDescription();
    queryData << GetCompletedText();                                  // display in quest objectives window once all objectives are completed
    for (uint32 i = 0; i < QUEST_OBJECTIVES_COUNT; ++i)
    {
        if (RequiredNpcOrGo[i] < 0)
            queryData << uint32((RequiredNpcOrGo[i] * (-1)) | 0x80000000);    // client expects gameobject template id in form (id|0x80000000)
        else
            queryData << uint32(RequiredNpcOrGo[i]);
        queryData << uint32(RequiredNpcOrGoCount[i]);
        queryData << uint32(ItemDrop[i]);
        queryData << uint32(0);                                  // req source count?
    }
    for (uint32 i = 0; i < QUEST_ITEM_OBJECTIVES_COUNT; ++i)
    {
        queryData << uint32(RequiredItemId[i]);
        queryData << uint32(RequiredItemCount[i]);
    }
    for (uint32 i = 0; i < QUEST_OBJECTIVES_COUNT; ++i)
        queryData << ObjectiveText[i];
}
References GetAreaDescription(), GetBonusTalents(), GetCharTitleId(), GetCompletedText(), GetDetails(), GetFlags(), GetMinLevel(), GetNextQuestInChain(), GetObjectives(), GetPlayersSlain(), GetPOIContinent(), GetPointOpt(), GetPOIx(), GetPOIy(), GetQuestId(), GetQuestLevel(), GetQuestMethod(), GetRepObjectiveFaction(), GetRepObjectiveFaction2(), GetRepObjectiveValue(), GetRepObjectiveValue2(), GetRewArenaPoints(), GetRewHonorAddition(), GetRewHonorMultiplier(), GetRewMoneyMaxLevel(), GetRewOrReqMoney(), GetRewSpell(), GetRewSpellCast(), GetSrcItemId(), GetSuggestedPlayers(), GetTitle(), GetType(), GetXPId(), GetZoneOrSort(), HasFlag(), WorldPacket::Initialize(), ItemDrop, ObjectiveText, queryData, QUEST_FLAGS_HIDDEN_REWARDS, QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_REPUTATIONS_COUNT, QUEST_REWARD_CHOICES_COUNT, QUEST_REWARDS_COUNT, RequiredItemCount, RequiredItemId, RequiredNpcOrGo, RequiredNpcOrGoCount, RewardChoiceItemCount, RewardChoiceItemId, RewardFactionId, RewardFactionValueId, RewardFactionValueIdOverride, RewardItemId, RewardItemIdCount, and SMSG_QUEST_QUERY_RESPONSE.
IsAllowedInRaid()
bool Quest::IsAllowedInRaid (Difficulty difficulty) const
{
    if (IsRaidQuest(difficulty))
        return true;
    return sWorld->getBoolConfig(CONFIG_QUEST_IGNORE_RAID);
}
References CONFIG_QUEST_IGNORE_RAID, IsRaidQuest(), and sWorld.
Referenced by Player::HasQuestForGO(), Player::HasQuestForItem(), Player::KilledMonsterCredit(), and Player::KilledPlayerCredit().
IsAutoAccept()
bool Quest::IsAutoAccept () const
{
    return HasFlag(QUEST_FLAGS_AUTO_ACCEPT);
}
References HasFlag(), and QUEST_FLAGS_AUTO_ACCEPT.
IsAutoComplete()
bool Quest::IsAutoComplete () const
{
    return HasFlag(QUEST_FLAGS_AUTOCOMPLETE);
}
References HasFlag(), and QUEST_FLAGS_AUTOCOMPLETE.
Referenced by Player::CanCompleteQuest(), Player::CanRewardQuest(), npc_wg_quest_giver::GetDialogStatus(), Player::GetQuestDialogStatus(), npc_wg_quest_giver::OnGossipHello(), and Player::PrepareQuestMenu().
IsDaily()
bool Quest::IsDaily () const inline
{ return Flags & QUEST_FLAGS_DAILY; }
References Flags, and QUEST_FLAGS_DAILY.
Referenced by npc_wg_quest_giver::GetDialogStatus(), Player::GetQuestDialogStatus(), quest_commandscript::HandleQuestReward(), Player::PrepareQuestMenu(), Player::RewardQuest(), Player::RewardReputation(), and Player::SatisfyQuestDay().
IsDailyOrWeekly()
bool Quest::IsDailyOrWeekly () const inline
{ return Flags & (QUEST_FLAGS_DAILY | QUEST_FLAGS_WEEKLY); }
References Flags, QUEST_FLAGS_DAILY, and QUEST_FLAGS_WEEKLY.
Referenced by npc_wg_quest_giver::GetDialogStatus(), and Player::GetQuestDialogStatus().
IsDFQuest()
bool Quest::IsDFQuest () const inline
{ return SpecialFlags & QUEST_SPECIAL_FLAGS_DF_QUEST; }
References QUEST_SPECIAL_FLAGS_DF_QUEST, and SpecialFlags.
Referenced by Player::CalculateQuestRewardXP(), Player::CanRewardQuest(), quest_commandscript::HandleQuestReward(), Player::RewardQuest(), and Player::SatisfyQuestDay().
IsMonthly()
bool Quest::IsMonthly () const inline
{ return SpecialFlags & QUEST_SPECIAL_FLAGS_MONTHLY; }
References QUEST_SPECIAL_FLAGS_MONTHLY, and SpecialFlags.
Referenced by Player::GetQuestDialogStatus(), quest_commandscript::HandleQuestReward(), Player::PrepareQuestMenu(), Player::RewardQuest(), Player::RewardReputation(), and Player::SatisfyQuestMonth().
IsPVPQuest()
bool Quest::IsPVPQuest () const inline
{ return Type == QUEST_TYPE_PVP; }
References QUEST_TYPE_PVP, and Type.
Referenced by Player::KilledMonsterCredit().
IsRaidQuest()
bool Quest::IsRaidQuest (Difficulty difficulty) const
{
    switch (Type)
    {
        case QUEST_TYPE_RAID:
            return true;
        case QUEST_TYPE_RAID_10:
            return !(difficulty & RAID_DIFFICULTY_MASK_25MAN);
        case QUEST_TYPE_RAID_25:
            return difficulty & RAID_DIFFICULTY_MASK_25MAN;
        default:
            break;
    }
    return false;
}
References QUEST_TYPE_RAID, QUEST_TYPE_RAID_10, QUEST_TYPE_RAID_25, RAID_DIFFICULTY_MASK_25MAN, and Type.
Referenced by IsAllowedInRaid().
IsRepeatable()
bool Quest::IsRepeatable () const inline
{ return SpecialFlags & QUEST_SPECIAL_FLAGS_REPEATABLE; }
References QUEST_SPECIAL_FLAGS_REPEATABLE, and SpecialFlags.
Referenced by Player::CanCompleteQuest(), npc_wg_quest_giver::GetDialogStatus(), Player::GetQuestDialogStatus(), Player::GetQuestRewardStatus(), IsSeasonal(), Player::PrepareQuestMenu(), Player::RewardQuest(), Player::RewardReputation(), and Player::SatisfyQuestExclusiveGroup().
IsSeasonal()
bool Quest::IsSeasonal () const inline
{ return (ZoneOrSort == -QUEST_SORT_SEASONAL || ZoneOrSort == -QUEST_SORT_SPECIAL || ZoneOrSort == -QUEST_SORT_LUNAR_FESTIVAL || ZoneOrSort == -QUEST_SORT_MIDSUMMER || ZoneOrSort == -QUEST_SORT_BREWFEST || ZoneOrSort == -QUEST_SORT_LOVE_IS_IN_THE_AIR || ZoneOrSort == -QUEST_SORT_NOBLEGARDEN) && !IsRepeatable(); }
References IsRepeatable(), QUEST_SORT_BREWFEST, QUEST_SORT_LOVE_IS_IN_THE_AIR, QUEST_SORT_LUNAR_FESTIVAL, QUEST_SORT_MIDSUMMER, QUEST_SORT_NOBLEGARDEN, QUEST_SORT_SEASONAL, QUEST_SORT_SPECIAL, and ZoneOrSort.
Referenced by Player::CanCompleteQuest(), Player::GetQuestRewardStatus(), quest_commandscript::HandleQuestReward(), Player::RewardQuest(), Player::SatisfyQuestExclusiveGroup(), Player::SatisfyQuestPreviousQuest(), and Player::SatisfyQuestSeasonal().
IsWeekly()
bool Quest::IsWeekly () const inline
{ return Flags & QUEST_FLAGS_WEEKLY; }
References Flags, and QUEST_FLAGS_WEEKLY.
Referenced by Player::GetQuestDialogStatus(), quest_commandscript::HandleQuestReward(), Player::PrepareQuestMenu(), Player::RewardQuest(), Player::RewardReputation(), Player::SatisfyQuestWeek(), and npc_archmage_landalock::npc_archmage_landalockAI::UpdateAI().
LoadQuestDetails()
void Quest::LoadQuestDetails (Field * fields)
{
    for (int i = 0; i < QUEST_EMOTE_COUNT; ++i)
        DetailsEmote[i] = fields[1 + i].Get<uint16>();
    for (int i = 0; i < QUEST_EMOTE_COUNT; ++i)
        DetailsEmoteDelay[i] = fields[5 + i].Get<uint32>();
}
References DetailsEmote, DetailsEmoteDelay, and QUEST_EMOTE_COUNT.
LoadQuestOfferReward()
void Quest::LoadQuestOfferReward (Field * fields)
{
    for (int i = 0; i < QUEST_EMOTE_COUNT; ++i)
        OfferRewardEmote[i] = fields[1 + i].Get<uint16>();
    for (int i = 0; i < QUEST_EMOTE_COUNT; ++i)
        OfferRewardEmoteDelay[i] = fields[5 + i].Get<uint32>();
    OfferRewardText = fields[9].Get<std::string>();
}
References Field::Get(), OfferRewardEmote, OfferRewardEmoteDelay, OfferRewardText, and QUEST_EMOTE_COUNT.
LoadQuestRequestItems()
void Quest::LoadQuestRequestItems (Field * fields)
{
    EmoteOnComplete = fields[1].Get<uint16>();
    EmoteOnIncomplete = fields[2].Get<uint16>();
    RequestItemsText = fields[3].Get<std::string>();
}
References EmoteOnComplete, EmoteOnIncomplete, Field::Get(), and RequestItemsText.
LoadQuestTemplateAddon()
void Quest::LoadQuestTemplateAddon (Field * fields)
{
    MaxLevel = fields[1].Get<uint8>();
    RequiredClasses = fields[2].Get<uint32>();
    SourceSpellid = fields[3].Get<uint32>();
    PrevQuestId = fields[4].Get<int32>();
    NextQuestId = fields[5].Get<uint32>();
    ExclusiveGroup = fields[6].Get<int32>();
    RewardMailTemplateId = fields[7].Get<uint32>();
    RewardMailDelay = fields[8].Get<uint32>();
    RequiredSkillId = fields[9].Get<uint16>();
    RequiredSkillPoints = fields[10].Get<uint16>();
    RequiredMinRepFaction = fields[11].Get<uint16>();
    RequiredMaxRepFaction = fields[12].Get<uint16>();
    RequiredMinRepValue = fields[13].Get<int32>();
    RequiredMaxRepValue = fields[14].Get<int32>();
    StartItemCount = fields[15].Get<uint8>();
    RewardMailSenderEntry = fields[16].Get<uint32>();
    SpecialFlags = fields[17].Get<uint32>();
    if ((SpecialFlags & QUEST_SPECIAL_FLAGS_AUTO_ACCEPT) && !sWorld->getBoolConfig(CONFIG_QUEST_IGNORE_AUTO_ACCEPT))
    {
        Flags |= QUEST_FLAGS_AUTO_ACCEPT;
    }
}
References CONFIG_QUEST_IGNORE_AUTO_ACCEPT, ExclusiveGroup, Flags, Field::Get(), MaxLevel, NextQuestId, PrevQuestId, QUEST_FLAGS_AUTO_ACCEPT, QUEST_SPECIAL_FLAGS_AUTO_ACCEPT, RequiredClasses, RequiredMaxRepFaction, RequiredMaxRepValue, RequiredMinRepFaction, RequiredMinRepValue, RequiredSkillId, RequiredSkillPoints, RewardMailDelay, RewardMailSenderEntry, RewardMailTemplateId, SourceSpellid, SpecialFlags, StartItemCount, and sWorld.
SetEventIdForQuest()
void Quest::SetEventIdForQuest (uint16 eventId) inline
{ _eventIdForQuest = eventId; }
References _eventIdForQuest.
SetFlag()
void Quest::SetFlag (uint32 flag) inline
{ Flags |= flag; }
References Flags.
SetSpecialFlag()
void Quest::SetSpecialFlag (uint32 flag) inline
{ SpecialFlags |= flag; }
References SpecialFlags.
Referenced by ObjectMgr::LoadQuests().
XPValue()
uint32 Quest::XPValue (uint8 playerLevel = 0) const
{
    int32 quest_level = (Level == -1 ? playerLevel : Level);
    const QuestXPEntry* xpentry = sQuestXPStore.LookupEntry(quest_level);
    if (!xpentry)
    {
        return 0;
    }
    int32 diffFactor = 2 * (quest_level - playerLevel) + 20;
    if (diffFactor < 1)
    {
        diffFactor = 1;
    }
    else if (diffFactor > 10)
    {
        diffFactor = 10;
    }
    uint32 xp = diffFactor * xpentry->Exp[RewardXPDifficulty] / 10;
    if (xp <= 100)
    {
        xp = 5 * ((xp + 2) / 5);
    }
    else if (xp <= 500)
    {
        xp = 10 * ((xp + 5) / 10);
    }
    else if (xp <= 1000)
    {
        xp = 25 * ((xp + 12) / 25);
    }
    else
    {
        xp = 50 * ((xp + 25) / 50);
    }
    return xp;
}
References QuestXPEntry::Exp, Level, RewardXPDifficulty, and sQuestXPStore.
Referenced by Player::CalculateQuestRewardXP(), GetRewMoneyMaxLevel(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), quest_commandscript::HandleQuestReward(), and WorldSession::SendLfgPlayerReward().
Friends And Related Function Documentation
ObjectMgr
friend class ObjectMgr friend
Member Data Documentation
_eventIdForQuest
uint16 Quest::_eventIdForQuest private
Referenced by GetEventIdForQuest(), Quest(), and SetEventIdForQuest().
_reqCreatureOrGOcount
uint32 Quest::_reqCreatureOrGOcount private
Referenced by GetReqCreatureOrGOcount(), and Quest().
_reqItemsCount
uint32 Quest::_reqItemsCount private
Referenced by GetReqItemsCount(), and Quest().
_rewChoiceItemsCount
uint32 Quest::_rewChoiceItemsCount private
Referenced by GetRewChoiceItemsCount(), and Quest().
_rewItemsCount
uint32 Quest::_rewItemsCount private
Referenced by GetRewItemsCount(), and Quest().
AllowableRaces
uint32 Quest::AllowableRaces protected
Referenced by GetAllowableRaces(), ObjectMgr::LoadQuests(), and Quest().
AreaDescription
std::string Quest::AreaDescription protected
Referenced by GetAreaDescription(), and Quest().
CompletedText
std::string Quest::CompletedText protected
Referenced by GetCompletedText(), and Quest().
Details
std::string Quest::Details protected
Referenced by GetDetails(), and Quest().
DetailsEmote
uint32 Quest::DetailsEmote[QUEST_EMOTE_COUNT]
Referenced by LoadQuestDetails(), Quest(), and PlayerMenu::SendQuestGiverQuestDetails().
DetailsEmoteDelay
uint32 Quest::DetailsEmoteDelay[QUEST_EMOTE_COUNT]
Referenced by LoadQuestDetails(), Quest(), and PlayerMenu::SendQuestGiverQuestDetails().
EmoteOnComplete
uint32 Quest::EmoteOnComplete protected
Referenced by GetCompleteEmote(), LoadQuestRequestItems(), and Quest().
EmoteOnIncomplete
uint32 Quest::EmoteOnIncomplete protected
Referenced by GetIncompleteEmote(), LoadQuestRequestItems(), and Quest().
ExclusiveGroup
int32 Quest::ExclusiveGroup = 0 protected
Referenced by GetExclusiveGroup(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
Flags
uint32 Quest::Flags protected
Referenced by GetFlags(), HasFlag(), IsDaily(), IsDailyOrWeekly(), IsWeekly(), ObjectMgr::LoadQuests(), LoadQuestTemplateAddon(), Quest(), and SetFlag().
Id
uint32 Quest::Id protected
Referenced by GetQuestId(), and Quest().
ItemDrop
uint32 Quest::ItemDrop[QUEST_SOURCE_ITEM_IDS_COUNT]
Referenced by quest_commandscript::HandleQuestReward(), Player::HasQuestForItem(), InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), and PlayerMenu::SendQuestQueryResponse().
ItemDropQuantity
uint32 Quest::ItemDropQuantity[QUEST_SOURCE_ITEM_IDS_COUNT]
Referenced by Player::HasQuestForItem(), ObjectMgr::LoadQuests(), Quest(), and Player::RewardQuest().
Level
int32 Quest::Level protected
Referenced by GetQuestLevel(), Quest(), and XPValue().
MaxLevel
uint32 Quest::MaxLevel = 0 protected
Referenced by GetMaxLevel(), and LoadQuestTemplateAddon().
Method
uint32 Quest::Method protected
Referenced by GetQuestMethod(), and Quest().
MinLevel
uint32 Quest::MinLevel protected
Referenced by GetMinLevel(), and Quest().
NextQuestId
uint32 Quest::NextQuestId = 0 protected
Referenced by GetNextQuestId(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
Objectives
std::string Quest::Objectives protected
Referenced by GetObjectives(), and Quest().
ObjectiveText
std::string Quest::ObjectiveText[QUEST_OBJECTIVES_COUNT]
Referenced by InitializeQueryData(), Quest(), and PlayerMenu::SendQuestQueryResponse().
OfferRewardEmote
uint32 Quest::OfferRewardEmote[QUEST_EMOTE_COUNT]
Referenced by LoadQuestOfferReward(), Quest(), and PlayerMenu::SendQuestGiverOfferReward().
OfferRewardEmoteDelay
uint32 Quest::OfferRewardEmoteDelay[QUEST_EMOTE_COUNT]
Referenced by LoadQuestOfferReward(), Quest(), and PlayerMenu::SendQuestGiverOfferReward().
OfferRewardText
std::string Quest::OfferRewardText protected
Referenced by GetOfferRewardText(), and LoadQuestOfferReward().
POIContinent
uint32 Quest::POIContinent protected
Referenced by GetPOIContinent(), and Quest().
POIPriority
uint32 Quest::POIPriority protected
Referenced by GetPointOpt(), and Quest().
POIx
float Quest::POIx protected
Referenced by GetPOIx(), and Quest().
POIy
float Quest::POIy protected
Referenced by GetPOIy(), and Quest().
prevChainQuests
PrevChainQuests Quest::prevChainQuests
Referenced by Player::SatisfyQuestPrevChain().
PrevQuestId
int32 Quest::PrevQuestId = 0 protected
Referenced by GetPrevQuestId(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
prevQuests
PrevQuests Quest::prevQuests
Referenced by ObjectMgr::LoadQuests(), and Player::SatisfyQuestPreviousQuest().
queryData
WorldPacket Quest::queryData
Referenced by InitializeQueryData().
RequestItemsText
std::string Quest::RequestItemsText protected
Referenced by GetRequestItemsText(), and LoadQuestRequestItems().
RequiredClasses
uint32 Quest::RequiredClasses = 0 protected
Referenced by GetRequiredClasses(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredFactionId1
uint32 Quest::RequiredFactionId1 protected
Referenced by GetRepObjectiveFaction(), ObjectMgr::LoadQuests(), and Quest().
RequiredFactionId2
uint32 Quest::RequiredFactionId2 protected
Referenced by GetRepObjectiveFaction2(), ObjectMgr::LoadQuests(), and Quest().
RequiredFactionValue1
int32 Quest::RequiredFactionValue1 protected
Referenced by GetRepObjectiveValue(), ObjectMgr::LoadQuests(), and Quest().
RequiredFactionValue2
int32 Quest::RequiredFactionValue2 protected
Referenced by GetRepObjectiveValue2(), ObjectMgr::LoadQuests(), and Quest().
RequiredItemCount
uint32 Quest::RequiredItemCount[QUEST_ITEM_OBJECTIVES_COUNT]
Referenced by Player::AdjustQuestReqItemCount(), Player::CanCompleteQuest(), Player::CanCompleteRepeatableQuest(), Player::CanRewardQuest(), quest_commandscript::HandleQuestComplete(), Player::HasQuestForItem(), InitializeQueryData(), Player::ItemAddedQuestCheck(), Player::ItemRemovedQuestCheck(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverRequestItems(), and PlayerMenu::SendQuestQueryResponse().
RequiredItemId
uint32 Quest::RequiredItemId[QUEST_ITEM_OBJECTIVES_COUNT]
Referenced by Player::AddQuestAndCheckCompletion(), Player::AdjustQuestReqItemCount(), Player::CanCompleteRepeatableQuest(), Player::CanRewardQuest(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), quest_commandscript::HandleQuestReward(), Player::HasQuestForItem(), InitializeQueryData(), Player::ItemAddedQuestCheck(), Player::ItemRemovedQuestCheck(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverRequestItems(), PlayerMenu::SendQuestQueryResponse(), and Player::TakeQuestSourceItem().
RequiredMaxRepFaction
uint32 Quest::RequiredMaxRepFaction = 0 protected
Referenced by GetRequiredMaxRepFaction(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredMaxRepValue
int32 Quest::RequiredMaxRepValue = 0 protected
Referenced by GetRequiredMaxRepValue(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredMinRepFaction
uint32 Quest::RequiredMinRepFaction = 0 protected
Referenced by GetRequiredMinRepFaction(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredMinRepValue
int32 Quest::RequiredMinRepValue = 0 protected
Referenced by GetRequiredMinRepValue(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredNpcOrGo
int32 Quest::RequiredNpcOrGo[QUEST_OBJECTIVES_COUNT]
Referenced by Player::CanCompleteQuest(), Player::GetReqKillOrCastCurrentCount(), quest_commandscript::HandleQuestComplete(), Player::HasQuestForGO(), InitializeQueryData(), ConditionMgr::isConditionTypeValid(), Player::KillCreditGO(), Player::KilledMonsterCredit(), ObjectMgr::LoadQuests(), go_dragonflayer_cage::OnGossipHello(), Quest(), PlayerMenu::SendQuestQueryResponse(), Player::SendQuestUpdateAddCreatureOrGo(), npc_jungle_punch_target::npc_jungle_punch_targetAI::SpellHit(), and Player::TalkedToCreature().
RequiredNpcOrGoCount
uint32 Quest::RequiredNpcOrGoCount[QUEST_OBJECTIVES_COUNT]
Referenced by Player::CanCompleteQuest(), quest_commandscript::HandleQuestComplete(), Player::HasQuestForGO(), InitializeQueryData(), ConditionMgr::isConditionTypeValid(), Player::KillCreditGO(), Player::KilledMonsterCredit(), ObjectMgr::LoadQuests(), Quest(), PlayerMenu::SendQuestQueryResponse(), Player::SendQuestUpdateAddCreatureOrGo(), and Player::TalkedToCreature().
RequiredPlayerKills
uint32 Quest::RequiredPlayerKills protected
Referenced by GetPlayersSlain(), ObjectMgr::LoadQuests(), and Quest().
RequiredSkillId
uint32 Quest::RequiredSkillId = 0 protected
Referenced by GetRequiredSkill(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredSkillPoints
uint32 Quest::RequiredSkillPoints = 0 protected
Referenced by GetRequiredSkillValue(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RewardArenaPoints
int32 Quest::RewardArenaPoints protected
Referenced by GetRewArenaPoints(), and Quest().
RewardChoiceItemCount
uint32 Quest::RewardChoiceItemCount[QUEST_REWARD_CHOICES_COUNT]
Referenced by Player::CanRewardQuest(), quest_commandscript::HandleQuestReward(), InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardChoiceItemId
uint32 Quest::RewardChoiceItemId[QUEST_REWARD_CHOICES_COUNT]
Referenced by Player::CanRewardQuest(), quest_commandscript::HandleQuestReward(), InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardDisplaySpell
uint32 Quest::RewardDisplaySpell protected
Referenced by GetRewSpell(), ObjectMgr::LoadQuests(), and Quest().
RewardFactionId
uint32 Quest::RewardFactionId[QUEST_REPUTATIONS_COUNT]
Referenced by InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardReputation(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardFactionValueId
int32 Quest::RewardFactionValueId[QUEST_REPUTATIONS_COUNT]
Referenced by InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardReputation(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardFactionValueIdOverride
int32 Quest::RewardFactionValueIdOverride[QUEST_REPUTATIONS_COUNT]
Referenced by InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardReputation(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardHonor
uint32 Quest::RewardHonor protected
Referenced by GetRewHonorAddition(), and Quest().
RewardItemId
uint32 Quest::RewardItemId[QUEST_REWARDS_COUNT]
Referenced by Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), quest_commandscript::HandleQuestReward(), InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardItemIdCount
uint32 Quest::RewardItemIdCount[QUEST_REWARDS_COUNT]
Referenced by Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), quest_commandscript::HandleQuestReward(), InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardKillHonor
float Quest::RewardKillHonor protected
Referenced by GetRewHonorMultiplier(), and Quest().
RewardMailDelay
uint32 Quest::RewardMailDelay = 0 protected
Referenced by GetRewMailDelaySecs(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RewardMailSenderEntry
uint32 Quest::RewardMailSenderEntry = 0 protected
Referenced by GetRewMailSenderEntry(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RewardMailTemplateId
uint32 Quest::RewardMailTemplateId = 0 protected
Referenced by GetRewMailTemplateId(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RewardMoney
int32 Quest::RewardMoney protected
Referenced by GetRewOrReqMoney(), and Quest().
RewardMoneyDifficulty
uint32 Quest::RewardMoneyDifficulty protected
Referenced by GetRewOrReqMoney(), and Quest().
RewardNextQuest
uint32 Quest::RewardNextQuest protected
Referenced by GetNextQuestInChain(), ObjectMgr::LoadQuests(), and Quest().
RewardSpell
int32 Quest::RewardSpell protected
Referenced by GetRewSpellCast(), ObjectMgr::LoadQuests(), and Quest().
RewardTalents
uint32 Quest::RewardTalents protected
Referenced by GetBonusTalents(), and Quest().
RewardTitleId
uint32 Quest::RewardTitleId protected
Referenced by GetCharTitleId(), ObjectMgr::LoadQuests(), and Quest().
RewardXPDifficulty
uint32 Quest::RewardXPDifficulty protected
Referenced by GetXPId(), Quest(), and XPValue().
SourceSpellid
uint32 Quest::SourceSpellid = 0 protected
Referenced by GetSrcSpell(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
SpecialFlags
uint32 Quest::SpecialFlags = 0 protected
Referenced by HasSpecialFlag(), IsDFQuest(), IsMonthly(), IsRepeatable(), ObjectMgr::LoadQuests(), LoadQuestTemplateAddon(), and SetSpecialFlag().
StartItem
uint32 Quest::StartItem protected
Referenced by GetSrcItemId(), ObjectMgr::LoadQuests(), and Quest().
StartItemCount
uint32 Quest::StartItemCount = 0 protected
Referenced by GetSrcItemCount(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
SuggestedPlayers
uint32 Quest::SuggestedPlayers protected
Referenced by GetSuggestedPlayers(), and Quest().
TimeAllowed
uint32 Quest::TimeAllowed protected
Referenced by GetTimeAllowed(), ObjectMgr::LoadQuests(), and Quest().
Title
std::string Quest::Title protected
Referenced by GetTitle(), and Quest().
Type
uint32 Quest::Type protected
Referenced by GetType(), IsPVPQuest(), IsRaidQuest(), and Quest().
ZoneOrSort
int32 Quest::ZoneOrSort protected
Referenced by GetZoneOrSort(), IsSeasonal(), ObjectMgr::LoadQuests(), and Quest().