AzerothCore: npc_pos_leader::npc_pos_leaderAI Struct Reference
npc_pos_leader::npc_pos_leaderAI Struct Reference
Public Member Functions
npc_pos_leaderAI (Creature *creature)
void Reset () override
void SetData (uint32 type, uint32) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustSummoned (Creature *s) override
void SummonedCreatureDespawn (Creature *s) override
void AttackStart (Unit *) override
void MoveInLineOfSight (Unit *) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
SummonList summons
InstanceScript * pInstance
uint8 counter
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_pos_leaderAI()
npc_pos_leader::npc_pos_leaderAI::npc_pos_leaderAI (Creature * creature) inline
                                             : NullCreatureAI(creature), summons(me)
        {
            pInstance = me->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), CreatureAI::me, and pInstance.
Member Function Documentation
AttackStart()
void npc_pos_leader::npc_pos_leaderAI::AttackStart (Unit *) inline override virtual
Reimplemented from NullCreatureAI.
{}
JustSummoned()
void npc_pos_leader::npc_pos_leaderAI::JustSummoned (Creature * s) inline override virtual
Reimplemented from CreatureAI.
        {
            summons.Summon(s);
        }
References SummonList::Summon(), and summons.
MoveInLineOfSight()
void npc_pos_leader::npc_pos_leaderAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from NullCreatureAI.
{}
Reset()
void npc_pos_leader::npc_pos_leaderAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            counter = 0;
            events.Reset();
            summons.DespawnAll();
            me->SetVisible(true);
            if (pInstance)
                switch (pInstance->GetData(DATA_INSTANCE_PROGRESS))
                {
                    case INSTANCE_PROGRESS_NONE:
                        me->SetVisible(false);
                        break;
                }
        }
References counter, DATA_INSTANCE_PROGRESS, SummonList::DespawnAll(), ZoneScript::GetData(), INSTANCE_PROGRESS_NONE, CreatureAI::me, pInstance, Unit::SetVisible(), and summons.
SetData()
void npc_pos_leader::npc_pos_leaderAI::SetData (uint32 type, uint32) inline override virtual
Reimplemented from UnitAI.
        {
            if (type == DATA_START_INTRO && pInstance->GetData(DATA_INSTANCE_PROGRESS) == INSTANCE_PROGRESS_NONE && counter == 0 && !me->IsVisible())
            {
                me->setActive(true);
                events.RescheduleEvent(1, 0ms);
            }
        }
References counter, DATA_INSTANCE_PROGRESS, DATA_START_INTRO, ZoneScript::GetData(), INSTANCE_PROGRESS_NONE, Unit::IsVisible(), CreatureAI::me, pInstance, and WorldObject::setActive().
SummonedCreatureDespawn()
void npc_pos_leader::npc_pos_leaderAI::SummonedCreatureDespawn (Creature * s) inline override virtual
Reimplemented from CreatureAI.
        {
            summons.Despawn(s);
        }
References SummonList::Despawn(), and summons.
UpdateAI()
void npc_pos_leader::npc_pos_leaderAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Todo:
This spell check is invalid
Todo:
: (Initial RP, when zoning in the instance) is not complete.
Reimplemented from NullCreatureAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case 1:
                    {
                        if (counter == 0)
{
                            me->SetVisible(true);
                            me->GetMotionMaster()->MovePoint(1, LeaderIntroPos);
                        }
                        uint8 idx = 0;
                        if (pInstance)
                            idx = (pInstance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_ALLIANCE ? 0 : 1);
                        if (introPositions[counter].entry[idx] != 0)
{
                            if (Creature* summon = me->SummonCreature(introPositions[counter].entry[idx], PortalPos))
{
                                summon->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                summon->SetSpeed(MOVE_RUN, 0.8f);
                                summon->GetMotionMaster()->MovePoint(1, introPositions[counter].endPosition);
                                summon->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                            }
                            ++counter;
                            events.Repeat(150ms);
                        }
                        else
{
                            events.RescheduleEvent(2, 2500ms);
                        }
                    }
                    break;
                case 2:
                    if (pInstance)
                        if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
{
                            c->setActive(true);
                            c->AI()->Talk(SAY_TYRANNUS_INTRO_1);
                        }
                    events.RescheduleEvent(3, 7s);
                    break;
                case 3:
                    if (pInstance)
                        if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
                            c->AI()->Talk(SAY_TYRANNUS_INTRO_2);
                    events.RescheduleEvent(4, 14s);
                    break;
                case 4:
                    if (pInstance)
                    {
                        Creature* n1 = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_NECROLYTE_1_GUID));
                        Creature* n2 = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_NECROLYTE_2_GUID));
                        if (n1 && n2)
{
                            if (!n1->IsInCombat() && n1->IsAlive())
{
                                n1->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                n1->GetMotionMaster()->MovePoint(1, NecrolytePos1);
                                n1->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                            }
                            if (!n2->IsInCombat() && n2->IsAlive())
{
                                n2->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                n2->GetMotionMaster()->MovePoint(1, NecrolytePos2);
                                n2->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                            }
                            //                            if (SPELL_NECROLYTE_CHANNELING)
                            //                            {
                            n1->RemoveAura(SPELL_NECROLYTE_CHANNELING);
                            n2->RemoveAura(SPELL_NECROLYTE_CHANNELING);
                            //                            }
                            for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                                if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                    if (c->GetPositionX() < 440.0f)
                                        continue;
                                    if (c->GetPositionY() > 215.0f)
                                        c->GetMotionMaster()->MoveChase(n2, 0.0f, rand_norm() * 2 * M_PI);
                                    else
                                        c->GetMotionMaster()->MoveChase(n1, 0.0f, rand_norm() * 2 * M_PI);
                                }
                        }
                    }
                    events.RescheduleEvent(5, 1ms);
                    break;
                case 5:
                    Talk(me->GetEntry() == NPC_JAINA_PART1 ? SAY_JAINA_INTRO_1 : SAY_SYLVANAS_INTRO_1);
                    events.RescheduleEvent(6, 1s);
                    break;
                case 6:
                    if (pInstance)
                        if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
                            c->AI()->Talk(SAY_TYRANNUS_INTRO_3);
                    events.RescheduleEvent(7, 5s);
                    break;
                case 7:
                    if (pInstance)
                    {
                        if (Creature* n1 = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_NECROLYTE_1_GUID)))
                            n1->AI()->DoAction(1337); // remove invincibility
                        if (Creature* n2 = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_NECROLYTE_2_GUID)))
                            n2->AI()->DoAction(1337); // remove invincibility
                        for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                            if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                if (c->GetPositionX() < 450.0f)
                                    continue;
                                c->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
                                c->GetMotionMaster()->Clear(false);
                                c->GetMotionMaster()->MoveIdle();
                                c->StopMoving();
                                c->CastSpell(c, 69413, true);
                                c->SetCanFly(true);
                                c->SetDisableGravity(true);
                                c->SendMovementFlagUpdate();
                                float dist = rand_norm() * 2.0f;
                                float angle = rand_norm() * 2 * M_PI;
                                c->GetMotionMaster()->MoveTakeoff(0, c->GetPositionX() + dist * cos(angle), c->GetPositionY() + dist * std::sin(angle), c->GetPositionZ() + 6.0f + (float)urand(0, 4), 1.5f + frand(0.0f, 1.5f));
                            }
                    }
                    events.RescheduleEvent(8, 7s);
                    break;
                case 8:
                    if (pInstance)
                        if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
                            c->CastSpell(c, 69753, false);
                    events.RescheduleEvent(9, 400ms);
                    break;
                case 9:
                    if (pInstance)
                        for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                            if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                if (c->GetPositionX() < 450.0f)
                                    continue;
                                Unit::Kill(c, c);
                                c->RemoveAllAuras();
                                c->GetMotionMaster()->MoveFall(0, true);
                            }
                    events.RescheduleEvent(10, 1s);
                    break;
                case 10:
                    Talk(me->GetEntry() == NPC_JAINA_PART1 ? SAY_JAINA_INTRO_2 : SAY_SYLVANAS_INTRO_2);
                    events.RescheduleEvent(11, 1s);
                    break;
                case 11:
                    if (pInstance)
                        for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                            if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                if (c->GetPositionX() < 450.0f)
                                    continue;
                                c->SetCanFly(false);
                                c->SetDisableGravity(false);
                                c->SendMovementFlagUpdate();
                                c->CastSpell(c, 69350, true);
                            }
                    events.RescheduleEvent(12, 2s);
                    break;
                case 12:
                    if (pInstance)
                    {
                        if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
                            c->AI()->Talk(SAY_TYRANNUS_INTRO_4);
                        for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                            if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                if (c->GetPositionX() < 450.0f)
                                    continue;
                                c->SetHomePosition(c->GetPositionX(), c->GetPositionY(), c->GetPositionZ(), c->GetOrientation());
                                c->Respawn(true);
                                c->UpdateEntry(36796, 0, false);
                                c->SetFacingTo(M_PI);
                                c->SetReactState(REACT_PASSIVE);
                            }
                    }
                    events.RescheduleEvent(13, 3s);
                    break;
                case 13:
                    if (pInstance)
                    {
                        for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                            if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                if (c->GetPositionX() < 450.0f)
                                    continue;
                                c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                float dist = rand_norm();
                                float angle = rand_norm() * 2 * M_PI;
                                c->SetSpeed(MOVE_RUN, 0.8f);
                                c->SetInCombatWithZone();
                                c->GetMotionMaster()->MoveChase(me, dist, angle);
                                c->SetHomePosition(me->GetPositionX() + dist * cos(angle), me->GetPositionY() + dist * std::sin(angle), me->GetPositionZ(), 0.0f);
                            }
                    }
                    events.RescheduleEvent(14, 2s);
                    break;
                case 14:
                    if (pInstance)
                    {
                        if (me->GetEntry() == NPC_JAINA_PART1)
{
                            Talk(SAY_JAINA_INTRO_3);
                            me->CastSpell(me, 70132, false);
                        }
                        else
{
                            me->CastSpell(me, 59514, false);
                            for (uint8 i = 0; i < 2; ++i)
                                if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_GUARD_1_GUID + i)))
                                    c->CastSpell(c, 70513, false);
                        }
                    }
                    events.RescheduleEvent(15, 2s);
                    break;
                case 15:
                    if (pInstance)
                    {
                        if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
                            c->GetMotionMaster()->MovePoint(0, SBSTyrannusStartPos);
                        if (me->GetEntry() == NPC_JAINA_PART1)
{
                            for (uint8 i = 0; i < 2; ++i)
                                if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_GUARD_1_GUID + i)))
                                    c->CastSpell(c, 70464, false);
                        }
                    }
                    events.RescheduleEvent(16, 3s);
                    break;
                case 16:
                    Talk(me->GetEntry() == NPC_JAINA_PART1 ? SAY_JAINA_INTRO_4 : SAY_SYLVANAS_INTRO_3);
                    if (pInstance)
                    {
                        for (uint8 i = 0; i < 2; ++i)
                            if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_GUARD_1_GUID + i)))
                                c->SetUInt32Value(UNIT_NPC_EMOTESTATE, 0);
                        for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                            if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                if (c->IsAlive())
{
                                    if (c->GetEntry() == NPC_KALIRA || c->GetEntry() == NPC_ELANDRA || c->GetEntry() == NPC_LORALEN || c->GetEntry() == NPC_KORELN)
                                        continue;
                                    Unit::Kill(c, c, false);
                                }
                                c->DespawnOrUnsummon(10000);
                            }
                        pInstance->SetData(DATA_INSTANCE_PROGRESS, INSTANCE_PROGRESS_FINISHED_INTRO);
                    }
                    events.RescheduleEvent(17, 5s);
                    break;
                case 17:
                    me->setActive(false);
                    Talk(me->GetEntry() == NPC_JAINA_PART1 ? SAY_JAINA_INTRO_5 : SAY_SYLVANAS_INTRO_4);
                    break;
            }
            if (!UpdateVictim())
                return;
            DoMeleeAttackIfReady();
        }
References Unit::AddUnitMovementFlag(), SummonList::begin(), Unit::CastSpell(), counter, DATA_GUARD_1_GUID, DATA_INSTANCE_PROGRESS, DATA_NECROLYTE_1_GUID, DATA_NECROLYTE_2_GUID, DATA_TEAMID_IN_INSTANCE, DATA_TYRANNUS_EVENT_GUID, UnitAI::DoMeleeAttackIfReady(), EMOTE_STATE_READY1H, SummonList::end(), ChampionPosition::entry, frand(), Map::GetCreature(), ZoneScript::GetData(), Object::GetEntry(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), InstanceScript::instance, INSTANCE_PROGRESS_FINISHED_INTRO, introPositions, Unit::IsAlive(), Unit::IsInCombat(), Unit::Kill(), LeaderIntroPos, CreatureAI::me, MOVE_RUN, MOVEMENTFLAG_WALKING, MotionMaster::MovePoint(), NecrolytePos1, NecrolytePos2, NPC_ELANDRA, NPC_JAINA_PART1, NPC_KALIRA, NPC_KORELN, NPC_LORALEN, pInstance, PortalPos, rand_norm(), REACT_PASSIVE, Unit::RemoveAura(), SAY_JAINA_INTRO_1, SAY_JAINA_INTRO_2, SAY_JAINA_INTRO_3, SAY_JAINA_INTRO_4, SAY_JAINA_INTRO_5, SAY_SYLVANAS_INTRO_1, SAY_SYLVANAS_INTRO_2, SAY_SYLVANAS_INTRO_3, SAY_SYLVANAS_INTRO_4, SAY_TYRANNUS_INTRO_1, SAY_TYRANNUS_INTRO_2, SAY_TYRANNUS_INTRO_3, SAY_TYRANNUS_INTRO_4, SBSTyrannusStartPos, WorldObject::setActive(), ZoneScript::SetData(), Unit::SetUInt32Value(), Unit::SetVisible(), SPELL_NECROLYTE_CHANNELING, WorldObject::SummonCreature(), summons, TEAM_ALLIANCE, UNIT_NPC_EMOTESTATE, UNIT_STATE_NO_ENVIRONMENT_UPD, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
counter
uint8 npc_pos_leader::npc_pos_leaderAI::counter
Referenced by Reset(), SetData(), and UpdateAI().
events
EventMap npc_pos_leader::npc_pos_leaderAI::events
pInstance
InstanceScript* npc_pos_leader::npc_pos_leaderAI::pInstance
Referenced by npc_pos_leaderAI(), Reset(), SetData(), and UpdateAI().
summons
SummonList npc_pos_leader::npc_pos_leaderAI::summons
Referenced by JustSummoned(), Reset(), SummonedCreatureDespawn(), and UpdateAI().