AzerothCore: achievement_once_bitten_twice_shy Class Reference
achievement_once_bitten_twice_shy Class Reference
Public Member Functions
achievement_once_bitten_twice_shy (const char *name, uint8 spawnMode, bool wasVampire)
bool OnCheck (Player *source, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
virtual bool OnCheck (Player *, Unit *, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Attributes
uint8 _spawnMode
bool _wasVampire
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_once_bitten_twice_shy()
achievement_once_bitten_twice_shy::achievement_once_bitten_twice_shy (const char * name, uint8 spawnMode, bool wasVampire) inline
: AchievementCriteriaScript(name), _spawnMode(spawnMode), _wasVampire(wasVampire) { }
Member Function Documentation
OnCheck()
bool achievement_once_bitten_twice_shy::OnCheck (Player * source, Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
    {
        if (!target || !target->FindMap())
            return false;
        if (LanaThelAI* lanaThelAI = CAST_AI(LanaThelAI, target->GetAI()))
            return (target->GetMap()->GetSpawnMode() % 2) == _spawnMode && lanaThelAI->WasVampire(source->GetGUID()) == _wasVampire;
        return false;
    }
References _spawnMode, _wasVampire, CAST_AI, WorldObject::FindMap(), Unit::GetAI(), Object::GetGUID(), WorldObject::GetMap(), and Map::GetSpawnMode().
Member Data Documentation
_spawnMode
uint8 achievement_once_bitten_twice_shy::_spawnMode
Referenced by OnCheck().
_wasVampire
bool achievement_once_bitten_twice_shy::_wasVampire
Referenced by OnCheck().