AzerothCore: npc_hover_disk::npc_hover_diskAI Struct Reference
npc_hover_disk::npc_hover_diskAI Struct Reference
Public Member Functions
npc_hover_diskAI (Creature *pCreature)
void PassengerBoarded (Unit *who, int8, bool apply) override
== Fields =======================================
void MovementInform (uint32 type, uint32 id) override
void DoAction (int32 param) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from VehicleAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_hover_diskAI()
npc_hover_disk::npc_hover_diskAI::npc_hover_diskAI (Creature * pCreature) inline
                                              : VehicleAI(pCreature)
        {
            pInstance = me->GetInstanceScript();
            events.Reset();
        }
References WorldObject::GetInstanceScript(), CreatureAI::me, and pInstance.
Member Function Documentation
AttackStart()
void npc_hover_disk::npc_hover_diskAI::AttackStart (Unit *) inline override virtual
Reimplemented from VehicleAI.
{}
DoAction()
void npc_hover_disk::npc_hover_diskAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            switch (param)
            {
                case 1: // move to next point
                    if (Vehicle* v = me->GetVehicleKit())
                        if (Unit* pass = v->GetPassenger(0))
                            switch (pass->GetEntry())
{
                                case NPC_NEXUS_LORD:
{
                                        float angle = CenterPos.GetAngle(me);
                                        float newangle = angle - 0.5f;
                                        if (newangle < 0.0f) newangle += 2 * M_PI;
                                        float newz = me->GetPositionZ() - 4.0f;
                                        if (newz < CenterPos.GetPositionZ()) newz = CenterPos.GetPositionZ();
                                        me->GetMotionMaster()->MovePoint(MI_POINT_NEXUS_LORD, CenterPos.GetPositionX() + cos(newangle) * 22.0f, CenterPos.GetPositionY() + std::sin(newangle) * 22.0f, newz);
                                    }
                                    break;
                                case NPC_SCION_OF_ETERNITY:
{
                                        float angle = CenterPos.GetAngle(me);
                                        float newangle = angle - 0.3f;
                                        if (newangle < 0.0f) newangle += 2 * M_PI;
                                        float newz = me->GetPositionZ() - 2.0f;
                                        if (newz < CenterPos.GetPositionZ() + 20.0f) newz = CenterPos.GetPositionZ() + 20.0f;
                                        me->GetMotionMaster()->MovePoint(MI_POINT_SCION, CenterPos.GetPositionX() + cos(newangle) * 30.0f, CenterPos.GetPositionY() + std::sin(newangle) * 30.0f, newz);
                                    }
                                    break;
                            }
                    break;
            }
        }
References CenterPos, Position::GetAngle(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicleKit(), CreatureAI::me, MI_POINT_NEXUS_LORD, MI_POINT_SCION, MotionMaster::MovePoint(), NPC_NEXUS_LORD, and NPC_SCION_OF_ETERNITY.
Referenced by UpdateAI().
MoveInLineOfSight()
void npc_hover_disk::npc_hover_diskAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from VehicleAI.
{}
MovementInform()
void npc_hover_disk::npc_hover_diskAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
        {
            if (type != POINT_MOTION_TYPE)
                return;
            switch (id)
            {
                case MI_POINT_SCION:
                    events.RescheduleEvent(EVENT_DISK_MOVE_NEXT_POINT, 0ms);
                    break;
                case MI_POINT_NEXUS_LORD:
                    if (me->GetPositionZ() > CenterPos.GetPositionZ() + 2.0f)
                        events.RescheduleEvent(EVENT_DISK_MOVE_NEXT_POINT, 0ms);
                    else if (Vehicle* v = me->GetVehicleKit())
                        if (Unit* pass = v->GetPassenger(0))
                            if (Creature* c = pass->ToCreature())
{
                                c->SetReactState(REACT_AGGRESSIVE);
                                if (Player* plr = c->SelectNearestPlayer(100.0f))
                                    c->AI()->AttackStart(plr);
                            }
                    break;
            }
        }
References CenterPos, EVENT_DISK_MOVE_NEXT_POINT, Position::GetPositionZ(), Unit::GetVehicleKit(), CreatureAI::me, MI_POINT_NEXUS_LORD, MI_POINT_SCION, POINT_MOTION_TYPE, REACT_AGGRESSIVE, WorldObject::SelectNearestPlayer(), and Object::ToCreature().
PassengerBoarded()
void npc_hover_disk::npc_hover_diskAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
        {
            events.Reset();
            if (!who)
                return;
            if (apply)
            {
                if (who->IsPlayer())
                {
                    who->ApplySpellImmune(0, IMMUNITY_ID, SPELL_ARCANE_OVERLOAD_DMG, true);
                    who->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SURGE_OF_POWER_DMG, true);
                    me->SetSpeed(MOVE_RUN, 1.5f);
                    me->SetSpeed(MOVE_FLIGHT, 1.5f);
                }
                else if (who->GetEntry() == NPC_NEXUS_LORD)
                {
                    me->SetSpeed(MOVE_RUN, 1.5f);
                    me->SetSpeed(MOVE_FLIGHT, 1.5f);
                }
                else
                {
                    me->SetSpeed(MOVE_RUN, 0.6f);
                    me->SetSpeed(MOVE_FLIGHT, 0.6f);
                }
                who->SetFacingTo(me->GetOrientation());
                me->SetCanFly(true);
            }
            else
            {
                me->GetMotionMaster()->MoveIdle();
                me->DisableSpline();
                me->SetCanFly(false);
                me->GetMotionMaster()->MoveLand(0, me->GetPositionX(), me->GetPositionY(), 267.24f, 10.0f);
                if (who->IsPlayer())
                {
                    who->ApplySpellImmune(0, IMMUNITY_ID, SPELL_ARCANE_OVERLOAD_DMG, false);
                    who->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SURGE_OF_POWER_DMG, false);
                }
            }
        }
References Unit::ApplySpellImmune(), Unit::DisableSpline(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), IMMUNITY_ID, Object::IsPlayer(), CreatureAI::me, MOVE_FLIGHT, MOVE_RUN, MotionMaster::MoveIdle(), MotionMaster::MoveLand(), NPC_NEXUS_LORD, Creature::SetCanFly(), Unit::SetFacingTo(), Unit::SetSpeed(), SPELL_ARCANE_OVERLOAD_DMG, and SPELL_SURGE_OF_POWER_DMG.
UpdateAI()
void npc_hover_disk::npc_hover_diskAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from VehicleAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_DISK_MOVE_NEXT_POINT:
                    DoAction(1);
                    break;
            }
        }
References DoAction(), and EVENT_DISK_MOVE_NEXT_POINT.
Member Data Documentation
events
EventMap npc_hover_disk::npc_hover_diskAI::events
pInstance
InstanceScript* npc_hover_disk::npc_hover_diskAI::pInstance
Referenced by npc_hover_diskAI().