AzerothCore: boss_sartharion_dragonAI Struct Reference
boss_sartharion_dragonAI Struct Reference
Public Member Functions
boss_sartharion_dragonAI (Creature *pCreature, uint32 bossId)
void Reset () override
void DoAction (int32 param) final
void MoveInLineOfSight (Unit *who) final
void MovementInform (uint32 type, uint32 pointId) final
void JustSummoned (Creature *summon) override
void JustEngagedWith (Unit *) final
Called for reaction when initially engaged.
void JustDied (Unit *) override
void KilledUnit (Unit *victim) final
void UpdateAI (uint32 diff) final
virtual void ClearInstance ()
virtual void HandleExtraEvent (uint32 const)
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Protected Member Functions
void RemoveTwilightPortal ()
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
bool _ProccessHealthCheckEvent (uint8 healthPct, uint32 damage, std::function< void()> exec) const
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes
EventMap extraEvents
ObjectGuid portalGUID
bool isCalledBySartharion
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
TaskScheduler scheduler
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Detailed Description
Constructor & Destructor Documentation
boss_sartharion_dragonAI()
boss_sartharion_dragonAI::boss_sartharion_dragonAI (Creature * pCreature, uint32 bossId) inline
                                                                 : BossAI(pCreature, bossId), isCalledBySartharion(false)
    {
    }
Member Function Documentation
ClearInstance()
virtual void boss_sartharion_dragonAI::ClearInstance () inline virtual
Reimplemented in boss_sartharion_tenebron::boss_sartharion_tenebronAI, and boss_sartharion_vesperon::boss_sartharion_vesperonAI.
    {
        events.Reset();
        summons.DespawnAll();
        // Remove phase shift
        instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_TWILIGHT_SHIFT);
        RemoveTwilightPortal();
    }
References SummonList::DespawnAll(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), BossAI::instance, RemoveTwilightPortal(), SPELL_TWILIGHT_SHIFT, and BossAI::summons.
Referenced by boss_sartharion_tenebron::boss_sartharion_tenebronAI::ClearInstance(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ClearInstance(), JustDied(), Reset(), and boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies().
DoAction()
void boss_sartharion_dragonAI::DoAction (int32 param) inline final virtual
Reimplemented from UnitAI.
    {
        if (param == ACTION_CALL_DRAGON && !isCalledBySartharion)
        {
            isCalledBySartharion = true;
            extraEvents.RescheduleEvent(EVENT_MINIDRAKE_SPEECH, 4s);
        }
    }
References ACTION_CALL_DRAGON, EVENT_MINIDRAKE_SPEECH, extraEvents, isCalledBySartharion, and EventMap::RescheduleEvent().
HandleExtraEvent()
virtual void boss_sartharion_dragonAI::HandleExtraEvent (uint32 const) inline virtual
Reimplemented in boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_sartharion_shadron::boss_sartharion_shadronAI, and boss_sartharion_vesperon::boss_sartharion_vesperonAI.
{ }
Referenced by UpdateAI().
JustDied()
void boss_sartharion_dragonAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Reimplemented in boss_sartharion_tenebron::boss_sartharion_tenebronAI.
    {
        //_JustDied();
        events.Reset();
        // Despawn minions only if not called by Sartharion
        if (!isCalledBySartharion)
        {
            summons.DespawnAll();
        }
        switch (me->GetEntry())
        {
            case NPC_TENEBRON:
            {
                Talk(SAY_TENEBRON_DEATH);
                if (!isCalledBySartharion || instance->GetBossState(DATA_SARTHARION) != IN_PROGRESS)
                {
                    instance->SetBossState(DATA_SHADRON, DONE);
                }
                break;
            }
            case NPC_SHADRON:
            {
                Talk(SAY_SHADRON_DEATH);
                if (isCalledBySartharion)
                {
                    if (Creature* sartharion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SARTHARION)))
                    {
                        sartharion->RemoveAura(SPELL_GIFT_OF_TWILIGHT_FIRE);
                    }
                }
                if (!isCalledBySartharion || instance->GetBossState(DATA_SARTHARION) != IN_PROGRESS)
                {
                    instance->SetBossState(DATA_SHADRON, DONE);
                }
                break;
            }
            case NPC_VESPERON:
            {
                Talk(SAY_VESPERON_DEATH);
                instance->DoAction(ACTION_CLEAR_PORTAL);
                if (!isCalledBySartharion || instance->GetBossState(DATA_SARTHARION) != IN_PROGRESS)
                {
                    instance->SetBossState(DATA_VESPERON, DONE);
                }
                break;
            }
        }
        if (!isCalledBySartharion)
        {
            ClearInstance();
        }
        else
        {
            if (Creature* sartharion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SARTHARION)))
            {
                sartharion->AI()->DoAction(ACTION_DRAKE_DIED);
            }
        }
    }
References ACTION_CLEAR_PORTAL, ACTION_DRAKE_DIED, ClearInstance(), DATA_SARTHARION, DATA_SHADRON, DATA_VESPERON, SummonList::DespawnAll(), InstanceScript::DoAction(), DONE, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), IN_PROGRESS, BossAI::instance, isCalledBySartharion, ScriptedAI::me, NPC_SHADRON, NPC_TENEBRON, NPC_VESPERON, SAY_SHADRON_DEATH, SAY_TENEBRON_DEATH, SAY_VESPERON_DEATH, InstanceScript::SetBossState(), SPELL_GIFT_OF_TWILIGHT_FIRE, and BossAI::summons.
Referenced by boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustDied().
JustEngagedWith()
void boss_sartharion_dragonAI::JustEngagedWith (Unit *) inline final virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        me->setActive(true);
        DoZoneInCombat();
        Talk(SAY_TENEBRON_AGGRO);
        if (me->IsFlying())
        {
            me->SetSpeed(MOVE_FLIGHT, 1.0f);
            me->SetCanFly(false);
        }
        if (!isCalledBySartharion || instance->GetBossState(DATA_SARTHARION) != IN_PROGRESS)
        {
            switch (me->GetEntry())
            {
                case NPC_TENEBRON:
                {
                    instance->SetBossState(DATA_TENEBRON, IN_PROGRESS);
                    break;
                }
                case NPC_SHADRON:
                {
                    instance->SetBossState(DATA_SHADRON, IN_PROGRESS);
                    break;
                }
                case NPC_VESPERON:
                {
                    instance->SetBossState(DATA_VESPERON, IN_PROGRESS);
                    break;
                }
            }
        }
        if (isCalledBySartharion || instance->GetBossState(DATA_SARTHARION) == DONE)
        {
            me->SetLootMode(0);
        }
        if (isCalledBySartharion)
        {
            if (Unit* target = SelectTarget(SelectTargetMethod::MaxThreat, 1, 500, true))
            {
                AttackStart(target);
            }
        }
    }
References ScriptedAI::AttackStart(), DATA_SARTHARION, DATA_SHADRON, DATA_TENEBRON, DATA_VESPERON, DONE, CreatureAI::DoZoneInCombat(), InstanceScript::GetBossState(), Object::GetEntry(), IN_PROGRESS, BossAI::instance, isCalledBySartharion, Unit::IsFlying(), ScriptedAI::me, MOVE_FLIGHT, NPC_SHADRON, NPC_TENEBRON, NPC_VESPERON, SAY_TENEBRON_AGGRO, UnitAI::SelectTarget(), WorldObject::setActive(), InstanceScript::SetBossState(), Creature::SetCanFly(), Creature::SetLootMode(), and Unit::SetSpeed().
JustSummoned()
void boss_sartharion_dragonAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Reimplemented in boss_sartharion_tenebron::boss_sartharion_tenebronAI.
    {
        // Transfer summons to Sartharion
        if (isCalledBySartharion && instance->GetBossState(DATA_SARTHARION) == IN_PROGRESS)
        {
            if (Creature* sartharion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SARTHARION)))
            {
                sartharion->AI()->JustSummoned(summon);
            }
        }
        BossAI::JustSummoned(summon);
    }
References DATA_SARTHARION, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), IN_PROGRESS, BossAI::instance, isCalledBySartharion, BossAI::JustSummoned(), and ScriptedAI::me.
KilledUnit()
void boss_sartharion_dragonAI::KilledUnit (Unit * victim) inline final virtual
Reimplemented from ScriptedAI.
    {
        if (victim->GetTypeId() != TYPEID_PLAYER || urand(0, 2))
        {
            return;
        }
        switch (me->GetEntry())
        {
            case NPC_TENEBRON:
            {
                Talk(SAY_TENEBRON_SLAY);
                break;
            }
            case NPC_SHADRON:
            {
                Talk(SAY_SHADRON_SLAY);
                break;
            }
            case NPC_VESPERON:
            {
                Talk(SAY_VESPERON_SLAY);
                break;
            }
        }
    }
References Object::GetEntry(), ScriptedAI::me, NPC_SHADRON, NPC_TENEBRON, NPC_VESPERON, SAY_SHADRON_SLAY, SAY_TENEBRON_SLAY, SAY_VESPERON_SLAY, TYPEID_PLAYER, and urand().
MoveInLineOfSight()
void boss_sartharion_dragonAI::MoveInLineOfSight (Unit * who) inline final virtual
Reimplemented from CreatureAI.
    {
        if (isCalledBySartharion)
            return;
        ScriptedAI::MoveInLineOfSight(who);
    }
References isCalledBySartharion, and CreatureAI::MoveInLineOfSight().
MovementInform()
void boss_sartharion_dragonAI::MovementInform (uint32 type, uint32 pointId) inline final virtual
Reimplemented from ScriptedAI.
    {
        if (type != WAYPOINT_MOTION_TYPE)
        {
            return;
        }
        switch (me->GetEntry())
        {
            case NPC_TENEBRON:
            {
                if (pointId != POINT_FINAL_TENEBRON)
                {
                    return;
                }
                break;
            }
            case NPC_SHADRON:
            {
                if (pointId != POINT_FINAL_SHADRON)
                {
                    return;
                }
                break;
            }
            case NPC_VESPERON:
            {
                if (pointId != POINT_FINAL_VESPERON)
                {
                    return;
                }
                break;
            }
        }
        me->SetImmuneToNPC(false);
        me->SetInCombatWithZone();
    }
References Object::GetEntry(), ScriptedAI::me, NPC_SHADRON, NPC_TENEBRON, NPC_VESPERON, POINT_FINAL_SHADRON, POINT_FINAL_TENEBRON, POINT_FINAL_VESPERON, Unit::SetImmuneToNPC(), Creature::SetInCombatWithZone(), and WAYPOINT_MOTION_TYPE.
RemoveTwilightPortal()
void boss_sartharion_dragonAI::RemoveTwilightPortal () inline protected
    {
        if (portalGUID)
        {
            if (GameObject* gobj = me->GetMap()->GetGameObject(portalGUID))
            {
                gobj->Delete();
            }
            portalGUID.Clear();
        }
    }
References ObjectGuid::Clear(), Map::GetGameObject(), WorldObject::GetMap(), ScriptedAI::me, and portalGUID.
Referenced by ClearInstance(), and boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent().
Reset()
void boss_sartharion_dragonAI::Reset () inline override virtual
Reimplemented from BossAI.
Reimplemented in boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_sartharion_shadron::boss_sartharion_shadronAI, and boss_sartharion_vesperon::boss_sartharion_vesperonAI.
    {
        _Reset();
        events.Reset();
        ClearInstance();
        me->SetImmuneToNPC(false);
        me->SetSpeed(MOVE_FLIGHT, 1.0f);
        me->SetCanFly(false);
        me->ResetLootMode();
        portalGUID.Clear();
        isCalledBySartharion = false;
        instance->DoAction(ACTION_CLEAR_PORTAL);
    }
References BossAI::_Reset(), ACTION_CLEAR_PORTAL, ObjectGuid::Clear(), ClearInstance(), InstanceScript::DoAction(), BossAI::instance, isCalledBySartharion, ScriptedAI::me, MOVE_FLIGHT, portalGUID, Creature::ResetLootMode(), Creature::SetCanFly(), Unit::SetImmuneToNPC(), and Unit::SetSpeed().
Referenced by boss_sartharion_tenebron::boss_sartharion_tenebronAI::Reset(), boss_sartharion_shadron::boss_sartharion_shadronAI::Reset(), and boss_sartharion_vesperon::boss_sartharion_vesperonAI::Reset().
UpdateAI()
void boss_sartharion_dragonAI::UpdateAI (uint32 diff) inline final virtual
Reimplemented from BossAI.
    {
        extraEvents.Update(diff);
        while (uint32 const eventId = extraEvents.ExecuteEvent())
        {
            HandleExtraEvent(eventId);
        }
        if (!UpdateVictim())
        {
            return;
        }
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
        while (uint32 const eventId = events.ExecuteEvent())
        {
            ExecuteEvent(eventId);
            if (me->HasUnitState(UNIT_STATE_CASTING))
            {
                return;
            }
        }
        DoMeleeAttackIfReady();
    }
References UnitAI::DoMeleeAttackIfReady(), EventMap::ExecuteEvent(), BossAI::ExecuteEvent(), extraEvents, HandleExtraEvent(), Unit::HasUnitState(), ScriptedAI::me, UNIT_STATE_CASTING, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
extraEvents
EventMap boss_sartharion_dragonAI::extraEvents protected
Referenced by DoAction(), and UpdateAI().
isCalledBySartharion
bool boss_sartharion_dragonAI::isCalledBySartharion protected
Referenced by DoAction(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), JustDied(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustDied(), JustEngagedWith(), JustSummoned(), MoveInLineOfSight(), Reset(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::Reset(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), and boss_sartharion_vesperon::boss_sartharion_vesperonAI::SummonedCreatureDies().
portalGUID
ObjectGuid boss_sartharion_dragonAI::portalGUID protected
Referenced by boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), RemoveTwilightPortal(), and Reset().