AzerothCore: WorldMapScript Class Reference
WorldMapScript Class Reference
#include "WorldMapScript.h"
Public Member Functions
bool isAfterLoadScript () const override
void checkValidity () override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from MapScript< Map >
void checkMap ()
MapEntry const * GetEntry ()
virtual void OnCreate (Map *)
virtual void OnDestroy (Map *)
virtual void OnLoadGridMap (Map *, GridMap *, uint32, uint32)
virtual void OnUnloadGridMap (Map *, GridMap *, uint32, uint32)
virtual void OnPlayerEnter (Map *, Player *)
virtual void OnPlayerLeave (Map *, Player *)
void OnUpdate (Map *, uint32) override
Public Member Functions inherited from UpdatableScript< TObject >
virtual void OnUpdate (TObject *, uint32)
Protected Member Functions
WorldMapScript (const char *name, uint32 mapId)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from MapScript< Map >
MapScript (uint32 mapId)
Protected Member Functions inherited from UpdatableScript< TObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
WorldMapScript()
WorldMapScript::WorldMapScript (const char * name, uint32 mapId) protected
                                                             :
    ScriptObject(name), MapScript<Map>(mapId)
{
    ScriptRegistry<WorldMapScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
checkValidity()
void WorldMapScript::checkValidity () override virtual
Reimplemented from ScriptObject.
{
    checkMap();
    if (GetEntry() && !GetEntry()->IsWorldMap())
    {
        LOG_ERROR("maps.script", "WorldMapScript for map {} is invalid.", GetEntry()->MapID);
    }
}
References MapScript< Map >::checkMap(), MapScript< Map >::GetEntry(), and LOG_ERROR.
isAfterLoadScript()
bool WorldMapScript::isAfterLoadScript () const inline override virtual
Reimplemented from ScriptObject.
{ return true; }