AzerothCore: boss_felmyst::boss_felmystAI Struct Reference
boss_felmyst::boss_felmystAI Struct Reference
Public Member Functions
boss_felmystAI (Creature *creature)
void DoAction (int32 param) override
void Reset () override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void KilledUnit (Unit *victim) override
void JustDied (Unit *killer) override
void MovementInform (uint32 type, uint32 point) override
void JustSummoned (Creature *summon) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
virtual void HealDone (Unit *, uint32 &)
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events2
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
bool _ProccessHealthCheckEvent (uint8 healthPct, uint32 damage, std::function< void()> exec) const
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_felmystAI()
boss_felmyst::boss_felmystAI::boss_felmystAI (Creature * creature) inline
                                           : BossAI(creature, DATA_FELMYST)
        {
            bool appear = instance->GetBossState(DATA_BRUTALLUS) == DONE;
            creature->SetVisible(appear);
            creature->SetStandState(UNIT_STAND_STATE_SLEEP);
            creature->SetReactState(REACT_PASSIVE);
        }
References DATA_BRUTALLUS, DONE, InstanceScript::GetBossState(), BossAI::instance, REACT_PASSIVE, Creature::SetReactState(), Unit::SetStandState(), Unit::SetVisible(), and UNIT_STAND_STATE_SLEEP.
Member Function Documentation
DoAction()
void boss_felmyst::boss_felmystAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_START_EVENT)
            {
                me->SetVisible(true);
                me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                events2.ScheduleEvent(EVENT_INTRO_1, 3000);
            }
        }
References ACTION_START_EVENT, EVENT_INTRO_1, events2, ScriptedAI::me, EventMap::ScheduleEvent(), Unit::SetUnitFlag(), Unit::SetVisible(), and UNIT_FLAG_NON_ATTACKABLE.
JustDied()
void boss_felmyst::boss_felmystAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
        {
            BossAI::JustDied(killer);
            Talk(YELL_DEATH);
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_FOG_OF_CORRUPTION_CHARM);
            // Summon Kalecgos (human form of kalecgos fight)
            me->SummonCreature(NPC_KALEC, 1526.28f, 700.10f, 60.0f, 4.33f);
        }
References InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), BossAI::instance, BossAI::JustDied(), ScriptedAI::me, NPC_KALEC, SPELL_FOG_OF_CORRUPTION_CHARM, WorldObject::SummonCreature(), and YELL_DEATH.
JustEngagedWith()
void boss_felmyst::boss_felmystAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            BossAI::JustEngagedWith(who);
            me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            if (events.Empty() && events2.Empty())
                events2.ScheduleEvent(EVENT_INTRO_2, 3000);
        }
References EventMap::Empty(), EVENT_INTRO_2, events2, BossAI::JustEngagedWith(), ScriptedAI::me, EventMap::ScheduleEvent(), Unit::SetUnitFlag(), and UNIT_FLAG_NON_ATTACKABLE.
JustSummoned()
void boss_felmyst::boss_felmystAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            summons.Summon(summon);
        }
References SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_felmyst::boss_felmystAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->GetTypeId() == TYPEID_PLAYER && roll_chance_i(50))
                Talk(YELL_KILL);
        }
References Object::GetTypeId(), roll_chance_i(), TYPEID_PLAYER, and YELL_KILL.
MovementInform()
void boss_felmyst::boss_felmystAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type != POINT_MOTION_TYPE)
                return;
            if (point == POINT_GROUND)
            {
                me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                me->SetDisableGravity(false);
                me->SendMovementFlagUpdate();
                events.ScheduleEvent(EVENT_RESTORE_COMBAT, 0);
                events.ScheduleEvent(EVENT_RESTORE_COMBAT2, 1);
                events.ScheduleEvent(EVENT_SPELL_CLEAVE, 7500, 1);
                events.ScheduleEvent(EVENT_SPELL_CORROSION, 12000, 1);
                events.ScheduleEvent(EVENT_SPELL_GAS_NOVA, 18000, 1);
                events.ScheduleEvent(EVENT_SPELL_ENCAPSULATE, 25000, 1);
                events.ScheduleEvent(EVENT_FLIGHT, 60000, 1);
            }
            else if (point == POINT_AIR_BREATH_START1)
            {
                me->SetTarget();
                me->SetFacingTo(4.71f);
                events.ScheduleEvent(EVENT_FLIGHT_EMOTE, 2000);
                events.ScheduleEvent(EVENT_CORRUPT_TRIGGERS, 5000);
                events.ScheduleEvent(EVENT_FLIGHT_FLYOVER1, 5000);
            }
            else if (point == POINT_AIR_BREATH_END1)
            {
                me->RemoveAurasDueToSpell(SPELL_FELMYST_SPEED_BURST);
                me->SetFacingTo(1.57f);
                if (events.GetNextEventTime(EVENT_FLIGHT_BREATH1) != 0)
                    events.ScheduleEvent(EVENT_FLIGHT_BREATH2, 2000);
            }
            else if (point == POINT_AIR_BREATH_START2)
            {
                me->SetTarget();
                me->SetFacingTo(1.57f);
                events.ScheduleEvent(EVENT_FLIGHT_EMOTE, 2000);
                events.ScheduleEvent(EVENT_CORRUPT_TRIGGERS, 5000);
                events.ScheduleEvent(EVENT_FLIGHT_FLYOVER2, 5000);
            }
            else if (point == POINT_AIR_BREATH_END2)
            {
                me->RemoveAurasDueToSpell(SPELL_FELMYST_SPEED_BURST);
                me->SetFacingTo(4.71f);
            }
        }
References EMOTE_ONESHOT_LAND, EVENT_CORRUPT_TRIGGERS, EVENT_FLIGHT, EVENT_FLIGHT_BREATH1, EVENT_FLIGHT_BREATH2, EVENT_FLIGHT_EMOTE, EVENT_FLIGHT_FLYOVER1, EVENT_FLIGHT_FLYOVER2, EVENT_RESTORE_COMBAT, EVENT_RESTORE_COMBAT2, EVENT_SPELL_CLEAVE, EVENT_SPELL_CORROSION, EVENT_SPELL_ENCAPSULATE, EVENT_SPELL_GAS_NOVA, Unit::HandleEmoteCommand(), ScriptedAI::me, POINT_AIR_BREATH_END1, POINT_AIR_BREATH_END2, POINT_AIR_BREATH_START1, POINT_AIR_BREATH_START2, POINT_GROUND, POINT_MOTION_TYPE, Unit::RemoveAurasDueToSpell(), Unit::SendMovementFlagUpdate(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Creature::SetTarget(), and SPELL_FELMYST_SPEED_BURST.
Reset()
void boss_felmyst::boss_felmystAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            BossAI::Reset();
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            me->SetReactState(REACT_PASSIVE);
            me->SetDisableGravity(false);
            events2.Reset();
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_FOG_OF_CORRUPTION_CHARM);
        }
References InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), events2, BossAI::instance, ScriptedAI::me, REACT_PASSIVE, Unit::RemoveUnitFlag(), EventMap::Reset(), BossAI::Reset(), Creature::SetDisableGravity(), Creature::SetReactState(), SPELL_FOG_OF_CORRUPTION_CHARM, and UNIT_FLAG_NON_ATTACKABLE.
UpdateAI()
void boss_felmyst::boss_felmystAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
        {
            events2.Update(diff);
            switch (events2.ExecuteEvent())
            {
                case EVENT_INTRO_1:
                    me->SetStandState(UNIT_STAND_STATE_STAND);
                    events2.ScheduleEvent(EVENT_INTRO_2, 4000);
                    break;
                case EVENT_INTRO_2:
                    Talk(YELL_BIRTH);
                    me->SetDisableGravity(true);
                    me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                    me->SendMovementFlagUpdate();
                    events2.ScheduleEvent(EVENT_INTRO_3, 1500);
                    break;
                case EVENT_INTRO_3:
                    me->GetMotionMaster()->MovePoint(POINT_AIR, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 10.0f, false, true);
                    events2.ScheduleEvent(EVENT_INTRO_4, 2000);
                    break;
                case EVENT_INTRO_4:
                    events.ScheduleEvent(EVENT_LAND, 3000, 1);
                    events.ScheduleEvent(EVENT_SPELL_BERSERK, 600000);
                    me->SetInCombatWithZone();
                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->CastSpell(me, SPELL_NOXIOUS_FUMES, true);
                    me->GetMotionMaster()->MovePoint(POINT_MISC, 1472.18f, 603.38f, 34.0f, false, true);
                    break;
            }
            if (!events2.Empty())
                return;
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch(events.ExecuteEvent())
            {
                case EVENT_RESTORE_COMBAT:
                    me->SetReactState(REACT_AGGRESSIVE);
                    break;
                case EVENT_RESTORE_COMBAT2:
                    me->SetTarget(me->GetVictim()->GetGUID());
                    me->GetMotionMaster()->MoveChase(me->GetVictim());
                    break;
                case EVENT_LAND:
                    me->GetMotionMaster()->MovePoint(POINT_GROUND, me->GetPositionX(), me->GetPositionY(), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), false, true);
                    break;
                case EVENT_SPELL_BERSERK:
                    Talk(YELL_BERSERK);
                    me->CastSpell(me, SPELL_BERSERK, true);
                    break;
                case EVENT_SPELL_CLEAVE:
                    me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                    events.ScheduleEvent(EVENT_SPELL_CLEAVE, 7500, 1);
                    break;
                case EVENT_SPELL_CORROSION:
                    me->CastSpell(me->GetVictim(), SPELL_CORROSION, false);
                    events.ScheduleEvent(EVENT_SPELL_CORROSION, 20000, 1);
                    break;
                case EVENT_SPELL_GAS_NOVA:
                    DoCast(me, SPELL_GAS_NOVA, false);
                    events.ScheduleEvent(EVENT_SPELL_GAS_NOVA, 20000, 1);
                    break;
                case EVENT_SPELL_ENCAPSULATE:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 50.0f, true))
                        me->CastSpell(target, SPELL_ENCAPSULATE_CHANNEL, false);
                    events.ScheduleEvent(EVENT_SPELL_ENCAPSULATE, 25000, 1);
                    break;
                case EVENT_FLIGHT:
                    events.CancelEventGroup(1);
                    events.ScheduleEvent(EVENT_FLIGHT_SEQ, 1000);
                    me->SetReactState(REACT_PASSIVE);
                    me->StopMoving();
                    me->GetMotionMaster()->Clear();
                    break;
                case EVENT_FLIGHT_SEQ:
                    Talk(YELL_TAKEOFF);
                    me->SetTarget();
                    me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                    me->SetDisableGravity(true);
                    me->SendMovementFlagUpdate();
                    events.ScheduleEvent(EVENT_FLIGHT_MOVE_UP, 2000);
                    events.ScheduleEvent(EVENT_FLIGHT_VAPOR, 8000);
                    events.ScheduleEvent(EVENT_FLIGHT_VAPOR, 21000);
                    events.ScheduleEvent(EVENT_FLIGHT_BREATH1, 35000);
                    events.ScheduleEvent(EVENT_FLIGHT_BREATH1, 72000);
                    events.ScheduleEvent(EVENT_LAND_FIGHT, 86000);
                    break;
                case EVENT_FLIGHT_MOVE_UP:
                    me->GetMotionMaster()->MovePoint(POINT_AIR, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 15.0f, false, true);
                    break;
                case EVENT_FLIGHT_VAPOR:
                    me->CastCustomSpell(SPELL_SUMMON_DEMONIC_VAPOR, SPELLVALUE_MAX_TARGETS, 1, me, true);
                    break;
                case EVENT_FLIGHT_BREATH1:
                    {
                        Position pos = {1447.0f + urand(0, 2) * 25.0f, 705.0f, 50.0f, 4.71f};
                        me->GetMotionMaster()->MovePoint(POINT_AIR_BREATH_START1, pos, false, true);
                        break;
                    }
                case EVENT_FLIGHT_BREATH2:
                    {
                        Position pos = {1447.0f + urand(0, 2) * 25.0f, 515.0f, 50.0f, 1.57f};
                        me->GetMotionMaster()->MovePoint(POINT_AIR_BREATH_START2, pos, false, true);
                        break;
                    }
                case EVENT_FLIGHT_EMOTE:
                    Talk(EMOTE_BREATH);
                    break;
                case EVENT_CORRUPT_TRIGGERS:
                    Talk(YELL_BREATH);
                    me->m_Events.AddEvent(new CorruptTriggers(me), me->m_Events.CalculateTime(0));
                    me->m_Events.AddEvent(new CorruptTriggers(me), me->m_Events.CalculateTime(500));
                    me->m_Events.AddEvent(new CorruptTriggers(me), me->m_Events.CalculateTime(1000));
                    me->m_Events.AddEvent(new CorruptTriggers(me), me->m_Events.CalculateTime(1500));
                    me->m_Events.AddEvent(new CorruptTriggers(me), me->m_Events.CalculateTime(2000));
                    me->m_Events.AddEvent(new CorruptTriggers(me), me->m_Events.CalculateTime(2500));
                    me->m_Events.AddEvent(new CorruptTriggers(me), me->m_Events.CalculateTime(3000));
                    me->m_Events.AddEvent(new CorruptTriggers(me), me->m_Events.CalculateTime(3500));
                    me->m_Events.AddEvent(new CorruptTriggers(me), me->m_Events.CalculateTime(4000));
                    break;
                case EVENT_FLIGHT_FLYOVER1:
                    me->CastSpell(me, SPELL_FELMYST_SPEED_BURST, true);
                    me->GetMotionMaster()->MovePoint(POINT_AIR_BREATH_END1, me->GetPositionX(), me->GetPositionY() - 200.0f, me->GetPositionZ() + 5.0f, false, true);
                    break;
                case EVENT_FLIGHT_FLYOVER2:
                    me->CastSpell(me, SPELL_FELMYST_SPEED_BURST, true);
                    me->GetMotionMaster()->MovePoint(POINT_AIR_BREATH_END2, me->GetPositionX(), me->GetPositionY() + 200.0f, me->GetPositionZ() + 5.0f, false, true);
                    break;
                case EVENT_LAND_FIGHT:
                    me->GetMotionMaster()->MovePoint(POINT_GROUND, 1500.0f, 552.8f, 26.52f, false, true);
                    break;
            }
            if (!me->HasUnitMovementFlag(MOVEMENTFLAG_DISABLE_GRAVITY))
                DoMeleeAttackIfReady();
        }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::CastCustomSpell(), Unit::CastSpell(), MotionMaster::Clear(), UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), EMOTE_BREATH, EMOTE_ONESHOT_LIFTOFF, EventMap::Empty(), EVENT_CORRUPT_TRIGGERS, EVENT_FLIGHT, EVENT_FLIGHT_BREATH1, EVENT_FLIGHT_BREATH2, EVENT_FLIGHT_EMOTE, EVENT_FLIGHT_FLYOVER1, EVENT_FLIGHT_FLYOVER2, EVENT_FLIGHT_MOVE_UP, EVENT_FLIGHT_SEQ, EVENT_FLIGHT_VAPOR, EVENT_INTRO_1, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_INTRO_4, EVENT_LAND, EVENT_LAND_FIGHT, EVENT_RESTORE_COMBAT, EVENT_RESTORE_COMBAT2, EVENT_SPELL_BERSERK, EVENT_SPELL_CLEAVE, EVENT_SPELL_CORROSION, EVENT_SPELL_ENCAPSULATE, EVENT_SPELL_GAS_NOVA, events2, EventMap::ExecuteEvent(), Object::GetGUID(), WorldObject::GetMapHeight(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HandleEmoteCommand(), Unit::HasUnitMovementFlag(), Unit::HasUnitState(), Unit::m_Events, ScriptedAI::me, MotionMaster::MoveChase(), MOVEMENTFLAG_DISABLE_GRAVITY, MotionMaster::MovePoint(), POINT_AIR, POINT_AIR_BREATH_END1, POINT_AIR_BREATH_END2, POINT_AIR_BREATH_START1, POINT_AIR_BREATH_START2, POINT_GROUND, POINT_MISC, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveUnitFlag(), EventMap::ScheduleEvent(), UnitAI::SelectTarget(), Unit::SendMovementFlagUpdate(), Creature::SetDisableGravity(), Creature::SetInCombatWithZone(), Creature::SetReactState(), Unit::SetStandState(), Creature::SetTarget(), SPELL_BERSERK, SPELL_CLEAVE, SPELL_CORROSION, SPELL_ENCAPSULATE_CHANNEL, SPELL_FELMYST_SPEED_BURST, SPELL_GAS_NOVA, SPELL_NOXIOUS_FUMES, SPELL_SUMMON_DEMONIC_VAPOR, SPELLVALUE_MAX_TARGETS, Unit::StopMoving(), UNIT_FLAG_NON_ATTACKABLE, UNIT_STAND_STATE_STAND, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), urand(), YELL_BERSERK, YELL_BIRTH, YELL_BREATH, and YELL_TAKEOFF.
Member Data Documentation
events2
EventMap boss_felmyst::boss_felmystAI::events2
Referenced by DoAction(), JustEngagedWith(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
D:/azerothcore-wotlk/src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp