AzerothCore: DatabaseWorker Class Reference
DatabaseWorker Class Reference
#include "DatabaseWorker.h"
Public Member Functions
DatabaseWorker (ProducerConsumerQueue< SQLOperation * > *newQueue, MySQLConnection *connection)
~DatabaseWorker ()
Private Member Functions
void WorkerThread ()
DatabaseWorker (DatabaseWorker const &right)=delete
DatabaseWorker & operator= (DatabaseWorker const &right)=delete
Private Attributes
ProducerConsumerQueue< SQLOperation * > * _queue
MySQLConnection * _connection
std::thread _workerThread
Detailed Description
Constructor & Destructor Documentation
DatabaseWorker() [1/2]
DatabaseWorker::DatabaseWorker (ProducerConsumerQueue< SQLOperation * > * newQueue, MySQLConnection * connection)
{
    _connection = connection;
    _queue = newQueue;
    _workerThread = std::thread(&DatabaseWorker::WorkerThread, this);
}
References _connection, _queue, _workerThread, and WorkerThread().
~DatabaseWorker()
DatabaseWorker::~DatabaseWorker ()
{
    _workerThread.join();
}
References _workerThread.
DatabaseWorker() [2/2]
DatabaseWorker::DatabaseWorker (DatabaseWorker const & right) private delete
Member Function Documentation
operator=()
DatabaseWorker & DatabaseWorker::operator= (DatabaseWorker const & right) private delete
WorkerThread()
void DatabaseWorker::WorkerThread () private
{
    if (!_queue)
        return;
    for (;;)
    {
        SQLOperation* operation = nullptr;
        _queue->WaitAndPop(operation);
        if (!operation)
            return;
        operation->SetConnection(_connection);
        operation->call();
        delete operation;
    }
}
References _connection, _queue, SQLOperation::call(), SQLOperation::SetConnection(), and ProducerConsumerQueue< T >::WaitAndPop().
Referenced by DatabaseWorker().
Member Data Documentation
_connection
MySQLConnection* DatabaseWorker::_connection private
Referenced by DatabaseWorker(), and WorkerThread().
_queue
ProducerConsumerQueue<SQLOperation*>* DatabaseWorker::_queue private
Referenced by DatabaseWorker(), and WorkerThread().
_workerThread
std::thread DatabaseWorker::_workerThread private
Referenced by DatabaseWorker(), and ~DatabaseWorker().