AzerothCore: OpenSSLCrypto Namespace Reference
OpenSSLCrypto Namespace Reference
Functions
AC_COMMON_API void threadsSetup ()
Needs to be called before threads using openssl are spawned.
AC_COMMON_API void threadsCleanup ()
Needs to be called after threads using openssl are despawned.
Detailed Description
A group of functions which setup openssl crypto module to work properly in multithreaded enviroment If not setup properly - it will crash
Function Documentation
threadsCleanup()
void OpenSSLCrypto::threadsCleanup ()
Needs to be called after threads using openssl are despawned.
{
    OSSL_PROVIDER_unload(LegacyProvider);
    OSSL_PROVIDER_unload(DefaultProvider);
    OSSL_PROVIDER_set_default_search_path(nullptr, nullptr);
}
References DefaultProvider, and LegacyProvider.
Referenced by main().
threadsSetup()
void OpenSSLCrypto::threadsSetup ()
Needs to be called before threads using openssl are spawned.
{
#if AC_PLATFORM == AC_PLATFORM_WINDOWS
    SetupLibrariesForWindows();
#endif
    LegacyProvider = OSSL_PROVIDER_load(nullptr, "legacy");
    DefaultProvider = OSSL_PROVIDER_load(nullptr, "default");
}
References DefaultProvider, LegacyProvider, and SetupLibrariesForWindows().
Referenced by main().