AzerothCore: Acore::ChatCommands::PlayerIdentifier Struct Reference
Acore::ChatCommands::PlayerIdentifier Struct Reference
#include "ChatCommandTags.h"
Public Types
using value_type = Player *
Public Types inherited from Acore::Impl::ChatCommands::ContainerTag
using ChatCommandResult = Acore::Impl::ChatCommands::ChatCommandResult
Public Member Functions
PlayerIdentifier ()
PlayerIdentifier (Player &player)
operator ObjectGuid () const
operator std::string const & () const
operator std::string_view () const
std::string const & GetName () const
ObjectGuid GetGUID () const
bool IsConnected () const
Player * GetConnectedPlayer () const
ChatCommandResult TryConsume (ChatHandler const *handler, std::string_view args)
Static Public Member Functions
static Optional< PlayerIdentifier > FromTarget (ChatHandler *handler)
static Optional< PlayerIdentifier > FromSelf (ChatHandler *handler)
static Optional< PlayerIdentifier > FromTargetOrSelf (ChatHandler *handler)
Private Attributes
std::string _name
ObjectGuid _guid
Player * _player
Detailed Description
Member Typedef Documentation
value_type
using Acore::ChatCommands::PlayerIdentifier::value_type = Player*
Constructor & Destructor Documentation
PlayerIdentifier() [1/2]
Acore::ChatCommands::PlayerIdentifier::PlayerIdentifier () inline
: _name(), _guid(), _player(nullptr) {}
PlayerIdentifier() [2/2]
Acore::ChatCommands::PlayerIdentifier::PlayerIdentifier (Player & player)
    : _name(player.GetName()), _guid(player.GetGUID()), _player(&player) {}
Member Function Documentation
FromSelf()
Optional< Acore::ChatCommands::PlayerIdentifier > Acore::ChatCommands::PlayerIdentifier::FromSelf (ChatHandler * handler) static
{
    if (Player* player = handler->GetPlayer())
        return { *player };
    return std::nullopt;
}
References ChatHandler::GetPlayer().
Referenced by instance_commandscript::HandleInstanceGetBossStateCommand(), and instance_commandscript::HandleInstanceSetBossStateCommand().
FromTarget()
Optional< Acore::ChatCommands::PlayerIdentifier > Acore::ChatCommands::PlayerIdentifier::FromTarget (ChatHandler * handler) static
{
    if (Player* player = handler->GetPlayer())
        if (Player* target = player->GetSelectedPlayer())
            return { *target };
    return std::nullopt;
}
References ChatHandler::GetPlayer(), and Player::GetSelectedPlayer().
Referenced by reset_commandscript::GetPlayerFromIdentifierOrSelectedTarget(), achievement_commandscript::HandleAchievementCheckAllCommand(), misc_commandscript::HandleAppearCommand(), character_commandscript::HandleCharacterChangeFactionCommand(), character_commandscript::HandleCharacterChangeRaceCommand(), character_commandscript::HandleCharacterCustomizeCommand(), character_commandscript::HandleCharacterRenameCommand(), misc_commandscript::HandleMuteCommand(), and misc_commandscript::HandleSummonCommand().
FromTargetOrSelf()
static Optional< PlayerIdentifier > Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf (ChatHandler * handler) inline static
        {
            if (Optional<PlayerIdentifier> fromTarget = FromTarget(handler))
                return fromTarget;
            else
                return FromSelf(handler);
        }
Referenced by misc_commandscript::HandleAddItemCommand(), arena_commandscript::HandleArenaCaptainCommand(), arena_commandscript::HandleArenaCreateCommand(), cache_commandscript::HandleCacheDeleteCommand(), cache_commandscript::HandleCacheInfoCommand(), cache_commandscript::HandleCacheRefreshCommand(), character_commandscript::HandleCharacterChangeAccountCommand(), character_commandscript::HandleCharacterLevelCommand(), character_commandscript::HandleCharacterReputationCommand(), character_commandscript::HandleCharacterTitlesCommand(), misc_commandscript::HandleCombatStopCommand(), deserter_commandscript::HandleDeserterRemove(), misc_commandscript::HandleFreezeCommand(), gear_commandscript::HandleGearRepairCommand(), misc_commandscript::HandleGetDistanceCommand(), misc_commandscript::HandleGPSCommand(), group_commandscript::HandleGroupDisbandCommand(), group_commandscript::HandleGroupLeaderCommand(), group_commandscript::HandleGroupListCommand(), group_commandscript::HandleGroupRemoveCommand(), misc_commandscript::HandleGroupSummonCommand(), guild_commandscript::HandleGuildCreateCommand(), guild_commandscript::HandleGuildInfoCommand(), guild_commandscript::HandleGuildInviteCommand(), guild_commandscript::HandleGuildRankCommand(), guild_commandscript::HandleGuildUninviteCommand(), inventory_commandscript::HandleInventoryCountCommand(), misc_commandscript::HandleKickPlayerCommand(), learn_commandscript::HandleLearnAllDefaultCommand(), character_commandscript::HandleLevelUpCommand(), lfg_commandscript::HandleLfgGroupInfoCommand(), lfg_commandscript::HandleLfgPlayerInfoCommand(), misc_commandscript::HandlePInfoCommand(), player_commandscript::HandlePlayerLearnCommand(), player_commandscript::HandlePlayerUnLearnCommand(), quest_commandscript::HandleQuestAdd(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), quest_commandscript::HandleQuestReward(), misc_commandscript::HandleRecallCommand(), reset_commandscript::HandleResetSpellsCommand(), misc_commandscript::HandleReviveCommand(), send_commandscript::HandleSendItemsCommand(), send_commandscript::HandleSendMailCommand(), send_commandscript::HandleSendMessageCommand(), send_commandscript::HandleSendMoneyCommand(), tele_commandscript::HandleTeleNameCommand(), misc_commandscript::HandleUnFreezeCommand(), misc_commandscript::HandleUnmuteCommand(), and misc_commandscript::HandleUnstuckCommand().
GetConnectedPlayer()
Player * Acore::ChatCommands::PlayerIdentifier::GetConnectedPlayer () const inline
{ return _player; }
Referenced by tele_commandscript::DoNameTeleport(), character_commandscript::HandleCharacterEraseCommand(), item_commandscript::HandleItemRefundCommand(), and item_commandscript::HandleItemRestoreCommand().
GetGUID()
ObjectGuid Acore::ChatCommands::PlayerIdentifier::GetGUID () const inline
{ return _guid; }
Referenced by tele_commandscript::DoNameTeleport(), character_commandscript::HandleCharacterEraseCommand(), item_commandscript::HandleItemRefundCommand(), item_commandscript::HandleItemRestoreCommand(), item_commandscript::HandleItemRestoreListCommand(), character_commandscript::HandlePDumpCopyCommand(), and character_commandscript::HandlePDumpWriteCommand().
GetName()
std::string const & Acore::ChatCommands::PlayerIdentifier::GetName () const inline
{ return _name; }
Referenced by tele_commandscript::DoNameTeleport(), character_commandscript::HandleCharacterEraseCommand(), and item_commandscript::HandleItemRestoreCommand().
IsConnected()
bool Acore::ChatCommands::PlayerIdentifier::IsConnected () const inline
{ return (_player != nullptr); }
operator ObjectGuid()
Acore::ChatCommands::PlayerIdentifier::operator ObjectGuid () const inline
{ return _guid; }
operator std::string const &()
Acore::ChatCommands::PlayerIdentifier::operator std::string const & () const inline
{ return _name; }
operator std::string_view()
Acore::ChatCommands::PlayerIdentifier::operator std::string_view () const inline
{ return _name; }
TryConsume()
ChatCommandResult Acore::ChatCommands::PlayerIdentifier::TryConsume (ChatHandler const * handler, std::string_view args)
{
    Variant<Hyperlink<player>, ObjectGuid::LowType, std::string_view> val;
    ChatCommandResult next = ArgInfo<decltype(val)>::TryConsume(val, handler, args);
    if (!next)
        return next;
    if (val.holds_alternative<ObjectGuid::LowType>())
    {
        _guid = ObjectGuid::Create<HighGuid::Player>(val.get<ObjectGuid::LowType>());
        if ((_player = ObjectAccessor::FindPlayerByLowGUID(_guid.GetCounter())))
        {
            _name = _player->GetName();
        }
        else if (!sCharacterCache->GetCharacterNameByGuid(_guid, _name))
        {
            return FormatAcoreString(handler, LANG_CMDPARSER_CHAR_GUID_NO_EXIST, _guid.ToString());
        }
        return next;
    }
    else
    {
        if (val.holds_alternative<Hyperlink<player>>())
            _name.assign(static_cast<std::string_view>(val.get<Hyperlink<player>>()));
        else
            _name.assign(val.get<std::string_view>());
        if (!normalizePlayerName(_name))
            return FormatAcoreString(handler, LANG_CMDPARSER_CHAR_NAME_INVALID, _name);
        if ((_player = ObjectAccessor::FindPlayerByName(_name)))
        {
            _guid = _player->GetGUID();
        }
        else if (!(_guid = sCharacterCache->GetCharacterGuidByName(_name)))
        {
            return FormatAcoreString(handler, LANG_CMDPARSER_CHAR_NAME_NO_EXIST, _name);
        }
        return next;
    }
}
References ObjectAccessor::FindPlayerByLowGUID(), ObjectAccessor::FindPlayerByName(), Acore::Impl::ChatCommands::FormatAcoreString(), Acore::ChatCommands::Variant< T1, Ts >::get(), Acore::ChatCommands::Variant< T1, Ts >::holds_alternative(), LANG_CMDPARSER_CHAR_GUID_NO_EXIST, LANG_CMDPARSER_CHAR_NAME_INVALID, LANG_CMDPARSER_CHAR_NAME_NO_EXIST, normalizePlayerName(), and sCharacterCache.
Member Data Documentation
_guid
ObjectGuid Acore::ChatCommands::PlayerIdentifier::_guid private
_name
std::string Acore::ChatCommands::PlayerIdentifier::_name private
_player
Player* Acore::ChatCommands::PlayerIdentifier::_player private