AzerothCore: CustomSpellValues Class Reference
CustomSpellValues Class Reference
#include "SpellDefines.h"
Public Member Functions
void AddSpellMod (SpellValueMod mod, int32 value)
Detailed Description
Member Function Documentation
AddSpellMod()
void CustomSpellValues::AddSpellMod (SpellValueMod mod, int32 value) inline
    {
        push_back(std::make_pair(mod, value));
    }
Referenced by spell_the_lich_king_necrotic_plague_jump_aura::AfterDispel(), spell_igb_incinerating_blast::CalculateDamage(), Unit::CastCustomSpell(), Spell::EffectForceCast(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), spell_serpentshrine_cavern_infection::HandleEffectRemove(), AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick(), spell_rog_blade_flurry::HandleProc(), spell_warr_improved_spell_reflection::OnProc(), spell_the_lich_king_necrotic_plague_aura::OnRemove(), and spell_the_lich_king_necrotic_plague_jump_aura::OnRemove().