AzerothCore: InstanceSave Class Reference
InstanceSave Class Reference
#include "InstanceSaveMgr.h"
Public Member Functions
InstanceSave (uint16 MapId, uint32 InstanceId, Difficulty difficulty, time_t resetTime, time_t extendedResetTime)
~InstanceSave ()
uint32 GetInstanceId () const
uint32 GetMapId () const
Difficulty GetDifficulty () const
void InsertToDB ()
std::string GetInstanceData () const
void SetInstanceData (std::string str)
uint32 GetCompletedEncounterMask () const
void SetCompletedEncounterMask (uint32 mask)
time_t GetResetTime () const
time_t GetExtendedResetTime () const
time_t GetResetTimeForDB ()
void SetResetTime (time_t resetTime)
void SetExtendedResetTime (time_t extendedResetTime)
bool CanReset () const
void SetCanReset (bool canReset)
InstanceTemplate const * GetTemplate ()
MapEntry const * GetMapEntry ()
void AddPlayer (ObjectGuid guid)
bool RemovePlayer (ObjectGuid guid, InstanceSaveMgr *ism)
Private Attributes
GuidList m_playerList
time_t m_resetTime
time_t m_extendedResetTime
uint32 m_instanceid
uint32 m_mapid
Difficulty m_difficulty
bool m_canReset
std::string m_instanceData
uint32 m_completedEncounterMask
std::mutex _lock
Friends
class InstanceSaveMgr
Detailed Description
Constructor & Destructor Documentation
InstanceSave()
InstanceSave::InstanceSave (uint16 MapId, uint32 InstanceId, Difficulty difficulty, time_t resetTime, time_t extendedResetTime)
    : m_resetTime(resetTime), m_extendedResetTime(extendedResetTime), m_instanceid(InstanceId), m_mapid(MapId), m_difficulty(IsSharedDifficultyMap(MapId) ? Difficulty(difficulty % 2) : difficulty), m_canReset(true), m_instanceData(""), m_completedEncounterMask(0)
{
    sScriptMgr->OnConstructInstanceSave(this);
}
References sScriptMgr.
~InstanceSave()
InstanceSave::~InstanceSave ()
{
    ASSERT(m_playerList.empty());
    sScriptMgr->OnDestructInstanceSave(this);
}
References ASSERT, m_playerList, and sScriptMgr.
Member Function Documentation
AddPlayer()
void InstanceSave::AddPlayer (ObjectGuid guid)
{
    std::lock_guard<std::mutex> guard(_lock);
    m_playerList.push_back(guid);
}
References _lock, and m_playerList.
Referenced by InstanceSaveMgr::PlayerBindToInstance().
CanReset()
bool InstanceSave::CanReset () const inline
{ return m_canReset; }
References m_canReset.
Referenced by InstanceMap::AddPlayerToMap(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), Player::ResetInstances(), and Group::ResetInstances().
GetCompletedEncounterMask()
uint32 InstanceSave::GetCompletedEncounterMask () const inline
{ return m_completedEncounterMask; }
References m_completedEncounterMask.
Referenced by MapInstanced::CreateInstance().
GetDifficulty()
Difficulty InstanceSave::GetDifficulty () const inline
{ return m_difficulty; }
References m_difficulty.
Referenced by InstanceMap::AddPlayerToMap(), GetResetTimeForDB(), WorldSession::HandleCalendarGetCalendar(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), InsertToDB(), InstanceMap::PermBindAllPlayers(), InstanceSaveMgr::PlayerBindToInstance(), WorldSession::SendCalendarRaidLockout(), WorldSession::SendCalendarRaidLockoutUpdated(), Player::SendRaidInfo(), and InstanceSaveMgr::UnbindAllFor().
GetExtendedResetTime()
time_t InstanceSave::GetExtendedResetTime () const inline
{ return m_extendedResetTime; }
References m_extendedResetTime.
Referenced by WorldSession::HandleCalendarGetCalendar(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), WorldSession::SendCalendarRaidLockoutUpdated(), Player::SendInstanceResetWarning(), and Player::SendRaidInfo().
GetInstanceData()
std::string InstanceSave::GetInstanceData () const inline
{ return m_instanceData; }
References m_instanceData.
Referenced by MapInstanced::CreateInstance().
GetInstanceId()
uint32 InstanceSave::GetInstanceId () const inline
{ return m_instanceid; }
References m_instanceid.
Referenced by Group::_cancelHomebindIfInstance(), InstanceMap::AddPlayerToMap(), InstanceSaveMgr::DeleteInstanceSaveIfNeeded(), WorldSession::HandleCalendarGetCalendar(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), WorldSession::HandleSetSavedInstanceExtend(), InstanceSaveMgr::LoadCharacterBinds(), Player::LoadFromDB(), InstanceSaveMgr::PlayerBindToInstance(), InstanceSaveMgr::PlayerGetDestinationInstanceId(), Player::ResetInstances(), Group::ResetInstances(), WorldSession::SendCalendarRaidLockout(), and Player::SendRaidInfo().
GetMapEntry()
MapEntry const * InstanceSave::GetMapEntry ()
{
    return sMapStore.LookupEntry(m_mapid);
}
References m_mapid, and sMapStore.
GetMapId()
uint32 InstanceSave::GetMapId () const inline
{ return m_mapid; }
References m_mapid.
Referenced by InstanceMap::AddPlayerToMap(), InstanceSaveMgr::DeleteInstanceSaveIfNeeded(), GetResetTimeForDB(), WorldSession::HandleCalendarGetCalendar(), InsertToDB(), InstanceMap::PermBindAllPlayers(), InstanceSaveMgr::PlayerBindToInstance(), Player::ResetInstances(), Group::ResetInstances(), WorldSession::SendCalendarRaidLockout(), WorldSession::SendCalendarRaidLockoutUpdated(), Player::SendRaidInfo(), and InstanceSaveMgr::UnbindAllFor().
GetResetTime()
time_t InstanceSave::GetResetTime () const inline
{ return m_resetTime; }
References m_resetTime.
Referenced by GetResetTimeForDB(), WorldSession::HandleCalendarGetCalendar(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), WorldSession::SendCalendarRaidLockout(), WorldSession::SendCalendarRaidLockoutUpdated(), Player::SendInstanceResetWarning(), and Player::SendRaidInfo().
GetResetTimeForDB()
time_t InstanceSave::GetResetTimeForDB ()
{
    // only save the reset time for normal instances
    MapEntry const* entry = sMapStore.LookupEntry(GetMapId());
    if (!entry || entry->map_type == MAP_RAID || GetDifficulty() == DUNGEON_DIFFICULTY_HEROIC)
        return 0;
    else
        return GetResetTime();
}
References DUNGEON_DIFFICULTY_HEROIC, GetDifficulty(), GetMapId(), GetResetTime(), MAP_RAID, MapEntry::map_type, and sMapStore.
Referenced by InsertToDB().
GetTemplate()
InstanceTemplate const * InstanceSave::GetTemplate ()
{
    return sObjectMgr->GetInstanceTemplate(m_mapid);
}
References m_mapid, and sObjectMgr.
InsertToDB()
void InstanceSave::InsertToDB ()
{
    std::string data;
    uint32 completedEncounters = 0;
    Map* map = sMapMgr->FindMap(GetMapId(), m_instanceid);
    if (map)
    {
        ASSERT(map->IsDungeon());
        if (InstanceScript* instanceScript = map->ToInstanceMap()->GetInstanceScript())
        {
            data = instanceScript->GetSaveData();
            completedEncounters = instanceScript->GetCompletedEncounterMask();
            // pussywizard:
            SetInstanceData(data);
            SetCompletedEncounterMask(completedEncounters);
        }
    }
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_INSTANCE_SAVE);
    stmt->SetData(0, m_instanceid);
    stmt->SetData(1, GetMapId());
    stmt->SetData(2, uint32(GetResetTimeForDB()));
    stmt->SetData(3, uint8(GetDifficulty()));
    stmt->SetData(4, completedEncounters);
    stmt->SetData(5, data);
    CharacterDatabase.Execute(stmt);
    sScriptMgr->OnInstanceSave(this);
}
References ASSERT, CHAR_INS_INSTANCE_SAVE, CharacterDatabase, GetDifficulty(), InstanceMap::GetInstanceScript(), GetMapId(), GetResetTimeForDB(), Map::IsDungeon(), m_instanceid, SetCompletedEncounterMask(), PreparedStatementBase::SetData(), SetInstanceData(), sMapMgr, sScriptMgr, and Map::ToInstanceMap().
Referenced by InstanceSaveMgr::AddInstanceSave().
RemovePlayer()
bool InstanceSave::RemovePlayer (ObjectGuid guid, InstanceSaveMgr * ism)
{
    bool deleteSave = false;
    {
        std::lock_guard lg(_lock);
        m_playerList.remove(guid);
        // ism passed as an argument to avoid calling via singleton (might result in a deadlock)
        deleteSave = ism->DeleteInstanceSaveIfNeeded(this, false, false);
    }
    // Delete save now (avoid mutex memory corruption)
    if (deleteSave)
    {
        delete this;
    }
    return deleteSave;
}
References _lock, InstanceSaveMgr::DeleteInstanceSaveIfNeeded(), and m_playerList.
Referenced by InstanceSaveMgr::LoadCharacterBinds(), InstanceSaveMgr::PlayerBindToInstance(), InstanceSaveMgr::PlayerUnbindInstance(), and InstanceSaveMgr::PlayerUnbindInstanceNotExtended().
SetCanReset()
void InstanceSave::SetCanReset (bool canReset) inline
{ m_canReset = canReset; }
References m_canReset.
Referenced by InstanceSaveMgr::PlayerBindToInstance().
SetCompletedEncounterMask()
void InstanceSave::SetCompletedEncounterMask (uint32 mask) inline
{ m_completedEncounterMask = mask; }
References m_completedEncounterMask.
Referenced by InsertToDB(), InstanceSaveMgr::LoadInstanceSaves(), and InstanceScript::SetCompletedEncountersMask().
SetExtendedResetTime()
void InstanceSave::SetExtendedResetTime (time_t extendedResetTime) inline
{ m_extendedResetTime = extendedResetTime; }
References m_extendedResetTime.
SetInstanceData()
void InstanceSave::SetInstanceData (std::string str) inline
{ m_instanceData = str; }
References m_instanceData.
Referenced by InsertToDB(), InstanceSaveMgr::LoadInstanceSaves(), and InstanceScript::SaveToDB().
SetResetTime()
void InstanceSave::SetResetTime (time_t resetTime) inline
{ m_resetTime = resetTime; }
References m_resetTime.
Referenced by InstanceSaveMgr::LoadInstanceSaves().
Friends And Related Function Documentation
InstanceSaveMgr
friend class InstanceSaveMgr friend
Member Data Documentation
_lock
std::mutex InstanceSave::_lock private
Referenced by AddPlayer(), and RemovePlayer().
m_canReset
bool InstanceSave::m_canReset private
Referenced by CanReset(), and SetCanReset().
m_completedEncounterMask
uint32 InstanceSave::m_completedEncounterMask private
Referenced by GetCompletedEncounterMask(), and SetCompletedEncounterMask().
m_difficulty
Difficulty InstanceSave::m_difficulty private
Referenced by GetDifficulty().
m_extendedResetTime
time_t InstanceSave::m_extendedResetTime private
Referenced by GetExtendedResetTime(), and SetExtendedResetTime().
m_instanceData
std::string InstanceSave::m_instanceData private
Referenced by GetInstanceData(), and SetInstanceData().
m_instanceid
uint32 InstanceSave::m_instanceid private
Referenced by GetInstanceId(), and InsertToDB().
m_mapid
uint32 InstanceSave::m_mapid private
Referenced by GetMapEntry(), GetMapId(), and GetTemplate().
m_playerList
GuidList InstanceSave::m_playerList private
Referenced by InstanceSaveMgr::_ResetOrWarnAll(), AddPlayer(), InstanceSaveMgr::DeleteInstanceSaveIfNeeded(), RemovePlayer(), InstanceSaveMgr::UnbindAllFor(), and ~InstanceSave().
m_resetTime
time_t InstanceSave::m_resetTime private
Referenced by GetResetTime(), and SetResetTime().