AzerothCore: go_gilded_brazier::go_gilded_brazierAI Struct Reference
go_gilded_brazier::go_gilded_brazierAI Struct Reference
Public Member Functions
go_gilded_brazierAI (GameObject *go)
void Initialize ()
bool GossipHello (Player *player, bool reportUse) override
void UpdateAI (uint32 const diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Private Attributes
EventMap _events
ObjectGuid _playerGUID
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_gilded_brazierAI()
go_gilded_brazier::go_gilded_brazierAI::go_gilded_brazierAI (GameObject * go) inline
                                            : GameObjectAI(go)
        {
            Initialize();
        }
References Initialize().
Member Function Documentation
GossipHello()
bool go_gilded_brazier::go_gilded_brazierAI::GossipHello (Player * player, bool reportUse) inline override virtual
Reimplemented from GameObjectAI.
        {
            if (reportUse)
                return false;
            if (me->GetGoType() == GAMEOBJECT_TYPE_GOOBER)
            {
                if (player->GetQuestStatus(QUEST_THE_FIRST_TRIAL) == QUEST_STATUS_INCOMPLETE)
                {
                    _playerGUID = player->GetGUID();
                    me->SetGameObjectFlag((GameObjectFlags)1);
                    me->RemoveByteFlag(GAMEOBJECT_BYTES_1, 0, 1);
                    _events.ScheduleEvent(EVENT_STILLBLADE_SPAWN, 1000);
                }
            }
            return true;
        }
References _events, _playerGUID, EVENT_STILLBLADE_SPAWN, GAMEOBJECT_BYTES_1, GAMEOBJECT_TYPE_GOOBER, GameObject::GetGoType(), Object::GetGUID(), Player::GetQuestStatus(), GameObjectAI::me, QUEST_STATUS_INCOMPLETE, QUEST_THE_FIRST_TRIAL, Object::RemoveByteFlag(), EventMap::ScheduleEvent(), and GameObject::SetGameObjectFlag().
Initialize()
void go_gilded_brazier::go_gilded_brazierAI::Initialize () inline
        {
            _playerGUID.Clear();
        }
References _playerGUID, and ObjectGuid::Clear().
Referenced by go_gilded_brazierAI().
UpdateAI()
void go_gilded_brazier::go_gilded_brazierAI::UpdateAI (uint32 const diff) inline override virtual
Reimplemented from GameObjectAI.
        {
            _events.Update(diff);
            while (uint32 eventId = _events.ExecuteEvent())
            {
                switch (eventId)
                {
                case EVENT_STILLBLADE_SPAWN:
                {
                    if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
                    {
                        player->SummonCreature(NPC_STILLBLADE, 8032.587f, -7524.518f, 149.68073f, 6.161012172698974609f, TEMPSUMMON_DEAD_DESPAWN, 60000);
                        _events.ScheduleEvent(EVENT_RESET_BRAZIER, 4000);
                    }
                    break;
                }
                case EVENT_RESET_BRAZIER:
                {
                    me->RemoveGameObjectFlag((GameObjectFlags)1);
                    me->SetByteFlag(GAMEOBJECT_BYTES_1, 0, 1);
                    break;
                }
                default:
                    break;
                }
            }
        }
References _events, _playerGUID, EVENT_RESET_BRAZIER, EVENT_STILLBLADE_SPAWN, EventMap::ExecuteEvent(), GAMEOBJECT_BYTES_1, ObjectAccessor::GetPlayer(), GameObjectAI::me, NPC_STILLBLADE, GameObject::RemoveGameObjectFlag(), EventMap::ScheduleEvent(), Object::SetByteFlag(), TEMPSUMMON_DEAD_DESPAWN, and EventMap::Update().
Member Data Documentation
_events
EventMap go_gilded_brazier::go_gilded_brazierAI::_events private
Referenced by GossipHello(), and UpdateAI().
_playerGUID
ObjectGuid go_gilded_brazier::go_gilded_brazierAI::_playerGUID private
Referenced by GossipHello(), Initialize(), and UpdateAI().