AzerothCore: Acore::Impl Namespace Reference
Acore::Impl Namespace Reference
Namespaces
namespace ChatCommands
namespace EnumUtilsImpl
namespace StringConvertImpl
Classes
struct CastToVisitor
struct CryptoGenericsImpl
struct CurrentServerProcessHolder
struct GenericBaseEncoding
class GenericHash
struct GenericHashImpl
class GenericHMAC
class MPSCQueueIntrusive
class MPSCQueueNonIntrusive
Functions
template<class T , class Tuple , std::size_t... I>
T * new_from_tuple (Tuple &&args, std::index_sequence< I... >)
AC_COMMON_API std::string ByteArrayToHexStr (uint8 const *bytes, std::size_t length, bool reverse=false)
AC_COMMON_API void HexStrToByteArray (std::string_view str, uint8 *out, std::size_t outlen, bool reverse=false)
Function Documentation
ByteArrayToHexStr()
std::string Acore::Impl::ByteArrayToHexStr (uint8 const * bytes, std::size_t length, bool reverse = false)
{
    int32 init = 0;
    int32 end = arrayLen;
    int8 op = 1;
    if (reverse)
    {
        init = arrayLen - 1;
        end = -1;
        op = -1;
    }
    std::ostringstream ss;
    for (int32 i = init; i != end; i += op)
    {
        char buffer[4];
        snprintf(buffer, sizeof(buffer), "%02X", bytes[i]);
        ss << buffer;
    }
    return ss.str();
}
Referenced by ByteArrayToHexStr(), Guild::HandleMemberDepositMoney(), Guild::HandleMemberWithdrawMoney(), WardenMac::Init(), and WardenWin::Init().
HexStrToByteArray()
void Acore::Impl::HexStrToByteArray (std::string_view str, uint8 * out, std::size_t outlen, bool reverse = false)
{
    ASSERT(str.size() == (2 * outlen));
    int32 init = 0;
    int32 end = int32(str.length());
    int8 op = 1;
    if (reverse)
    {
        init = int32(str.length() - 2);
        end = -2;
        op = -1;
    }
    uint32 j = 0;
    for (int32 i = init; i != end; i += 2 * op)
    {
        char buffer[3] = { str[i], str[i + 1], '\0' };
        out[j++] = uint8(strtoul(buffer, nullptr, 16));
    }
}
References ASSERT.
Referenced by HexStrToByteArray().
new_from_tuple()
template<class T , class Tuple , std::size_t... I> T * Acore::Impl::new_from_tuple (Tuple && args, std::index_sequence< I... >)
        {
            return new T(std::get<I>(std::forward<Tuple>(args))...);
        }