AzerothCore: boss_captain_skarloc::boss_captain_skarlocAI Struct Reference
boss_captain_skarloc::boss_captain_skarlocAI Struct Reference
Public Member Functions
boss_captain_skarlocAI (Creature *creature)
void Reset () override
void JustSummoned (Creature *summon) override
void InitializeAI () override
void MovementInform (uint32 type, uint32 id) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_captain_skarlocAI()
boss_captain_skarloc::boss_captain_skarlocAI::boss_captain_skarlocAI (Creature * creature) inline
: ScriptedAI(creature), summons(me) { }
Member Function Documentation
InitializeAI()
void boss_captain_skarloc::boss_captain_skarlocAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
        {
            ScriptedAI::InitializeAI();
            Movement::PointsArray path;
            path.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
            for (uint8 i = 0; i < WAYPOINTS_COUNT; ++i)
                path.push_back(G3D::Vector3(startPath[i].GetPositionX(), startPath[i].GetPositionY(), startPath[i].GetPositionZ()));
            me->GetMotionMaster()->MoveSplinePath(&path);
            me->SetImmuneToAll(true);
            me->Mount(SKARLOC_MOUNT_MODEL);
        }
References Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), UnitAI::InitializeAI(), ScriptedAI::me, Unit::Mount(), MotionMaster::MoveSplinePath(), Unit::SetImmuneToAll(), SKARLOC_MOUNT_MODEL, startPath, and WAYPOINTS_COUNT.
JustDied()
void boss_captain_skarloc::boss_captain_skarlocAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_DEATH);
            me->GetInstanceScript()->SetData(DATA_ESCORT_PROGRESS, ENCOUNTER_PROGRESS_SKARLOC_KILLED);
            me->GetInstanceScript()->SetData(DATA_THRALL_ADD_FLAG, 0);
        }
References DATA_ESCORT_PROGRESS, DATA_THRALL_ADD_FLAG, ENCOUNTER_PROGRESS_SKARLOC_KILLED, and SAY_DEATH.
JustEngagedWith()
void boss_captain_skarloc::boss_captain_skarlocAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            me->CastSpell(me, SPELL_DEVOTION_AURA, true);
            events.ScheduleEvent(EVENT_SPELL_HOLY_LIGHT, 15000);
            events.ScheduleEvent(EVENT_SPELL_CLEANSE, 6000);
            events.ScheduleEvent(EVENT_SPELL_HAMMER, 20000);
            events.ScheduleEvent(EVENT_SPELL_HOLY_SHIELD, 10000);
            if (IsHeroic())
                events.ScheduleEvent(EVENT_SPELL_CONSECRATION, 1000);
        }
References EVENT_SPELL_CLEANSE, EVENT_SPELL_CONSECRATION, EVENT_SPELL_HAMMER, EVENT_SPELL_HOLY_LIGHT, EVENT_SPELL_HOLY_SHIELD, and SPELL_DEVOTION_AURA.
JustSummoned()
void boss_captain_skarloc::boss_captain_skarlocAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(summon);
            if (Creature* thrall = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(DATA_THRALL_GUID)))
                thrall->AI()->JustSummoned(summon);
            summon->SetImmuneToAll(true);
            if (summon->GetEntry() == NPC_SKARLOC_MOUNT)
                return;
            if (summons.size() == 1)
                summon->GetMotionMaster()->MovePoint(0, 2060.788f, 237.301f, 63.999f);
            else
                summon->GetMotionMaster()->MovePoint(0, 2056.870f, 234.853f, 63.839f);
        }
References DATA_THRALL_GUID, ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MovePoint(), NPC_SKARLOC_MOUNT, Unit::SetImmuneToAll(), SummonList::size(), SummonList::Summon(), and summons.
KilledUnit()
void boss_captain_skarloc::boss_captain_skarlocAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_SLAY);
        }
References SAY_SLAY.
MovementInform()
void boss_captain_skarloc::boss_captain_skarlocAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type != ESCORT_MOTION_TYPE)
                return;
            // Xinef: we can rely here on internal counting
            if (id == 1)
            {
                me->SummonCreature(NPC_DURNHOLDE_MAGE, 2038.549f, 273.303f, 63.420f, 5.30f, TEMPSUMMON_MANUAL_DESPAWN);
                me->SummonCreature(NPC_DURNHOLDE_VETERAN, 2032.810f, 269.416f, 63.561f, 5.30f, TEMPSUMMON_MANUAL_DESPAWN);
            }
            else if (id == 2)
            {
                me->Dismount();
                me->SetWalk(true);
                for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                    if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                        summon->SetWalk(true);
                if (Creature* mount = me->SummonCreature(NPC_SKARLOC_MOUNT, 2049.12f, 252.31f, 62.855f, me->GetOrientation(), TEMPSUMMON_MANUAL_DESPAWN))
                {
                    mount->SetImmuneToNPC(true);
                    mount->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                }
            }
            if (me->movespline->Finalized())
            {
                Talk(SAY_ENTER, 500ms);
                me->m_Events.AddEventAtOffset([this]()
                {
                    me->SetImmuneToAll(false);
                    me->SetInCombatWithZone();
                    for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                    {
                        if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
{
                            if (summon->GetEntry() != NPC_SKARLOC_MOUNT)
{
                                summon->SetImmuneToAll(false);
                                summon->SetInCombatWithZone();
                            }
                        }
                    }
                }, 8s);
            }
        }
References EventProcessor::AddEventAtOffset(), SummonList::begin(), Unit::Dismount(), SummonList::end(), ESCORT_MOTION_TYPE, Movement::MoveSpline::Finalized(), ObjectAccessor::GetCreature(), Position::GetOrientation(), Unit::m_Events, ScriptedAI::me, Unit::movespline, NPC_DURNHOLDE_MAGE, NPC_DURNHOLDE_VETERAN, NPC_SKARLOC_MOUNT, SAY_ENTER, Unit::SetImmuneToAll(), Creature::SetInCombatWithZone(), Creature::SetWalk(), WorldObject::SummonCreature(), summons, TEMPSUMMON_MANUAL_DESPAWN, and UNIT_FLAG_NOT_SELECTABLE.
Reset()
void boss_captain_skarloc::boss_captain_skarlocAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Reset();
            summons.DespawnAll();
        }
References SummonList::DespawnAll(), and summons.
UpdateAI()
void boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_SPELL_HOLY_LIGHT:
                    me->CastSpell(me, SPELL_HOLY_LIGHT, false);
                    events.ScheduleEvent(EVENT_SPELL_HOLY_LIGHT, 20000);
                    break;
                case EVENT_SPELL_CLEANSE:
                    if (roll_chance_i(33))
                        Talk(SAY_TAUNT);
                    me->CastSpell(me, SPELL_CLEANSE, false);
                    events.ScheduleEvent(EVENT_SPELL_CLEANSE, 10000);
                    break;
                case EVENT_SPELL_HAMMER:
                    me->CastSpell(me->GetVictim(), SPELL_HAMMER_OF_JUSTICE, false);
                    events.ScheduleEvent(EVENT_SPELL_HAMMER, 30000);
                    break;
                case EVENT_SPELL_HOLY_SHIELD:
                    me->CastSpell(me, SPELL_HOLY_SHIELD, false);
                    events.ScheduleEvent(SPELL_HOLY_SHIELD, 30000);
                    break;
                case EVENT_SPELL_CONSECRATION:
                    me->CastSpell(me, SPELL_CONSECRATION, false);
                    events.ScheduleEvent(EVENT_SPELL_CONSECRATION, 20000);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References EVENT_SPELL_CLEANSE, EVENT_SPELL_CONSECRATION, EVENT_SPELL_HAMMER, EVENT_SPELL_HOLY_LIGHT, EVENT_SPELL_HOLY_SHIELD, roll_chance_i(), SAY_TAUNT, SPELL_CLEANSE, SPELL_CONSECRATION, SPELL_HAMMER_OF_JUSTICE, SPELL_HOLY_LIGHT, SPELL_HOLY_SHIELD, and UNIT_STATE_CASTING.
Member Data Documentation
events
EventMap boss_captain_skarloc::boss_captain_skarlocAI::events
summons
SummonList boss_captain_skarloc::boss_captain_skarlocAI::summons
Referenced by JustSummoned(), MovementInform(), and Reset().