AzerothCore: spell_the_flag_of_ownership Class Reference
spell_the_flag_of_ownership Class Reference
Private Member Functions
PrepareSpellScript (spell_the_flag_of_ownership)
bool Load () override
void HandleScript (SpellEffIndex)
void FilterTargets (std::list< WorldObject * > &targets)
void HandleFinish ()
void Register () override
Private Attributes
bool haveTarget
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
FilterTargets()
void spell_the_flag_of_ownership::FilterTargets (std::list< WorldObject * > & targets) inline private
    {
        for( std::list<WorldObject*>::iterator itr = targets.begin(); itr != targets.end(); )
        {
            if (!(*itr)->IsPlayer() || (*itr)->ToPlayer()->IsAlive())
            {
                targets.erase(itr);
                itr = targets.begin();
                continue;
            }
            ++itr;
        }
    }
Referenced by Register().
HandleFinish()
void spell_the_flag_of_ownership::HandleFinish () inline private
    {
        Unit* caster = GetCaster();
        if (!caster || !caster->ToPlayer())
            return;
        if (!haveTarget)
        {
            caster->ToPlayer()->RemoveSpellCooldown(GetSpellInfo()->Id, true);
            Spell::SendCastResult(caster->ToPlayer(), GetSpellInfo(), 0, SPELL_FAILED_BAD_TARGETS);
        }
    }
References SpellScript::GetCaster(), SpellScript::GetSpellInfo(), haveTarget, Player::RemoveSpellCooldown(), Spell::SendCastResult(), SPELL_FAILED_BAD_TARGETS, and Object::ToPlayer().
Referenced by Register().
HandleScript()
void spell_the_flag_of_ownership::HandleScript (SpellEffIndex) inline private
    {
        Unit* caster = GetCaster();
        if (!caster || !caster->IsPlayer())
            return;
        Player* target = GetHitPlayer();
        if (!target)
            return;
        caster->CastSpell(target, SPELL_TAUNT_FLAG, true);
        LocaleConstant loc_idx = caster->ToPlayer()->GetSession()->GetSessionDbLocaleIndex();
        BroadcastText const* bct = sObjectMgr->GetBroadcastText(TEXT_FLAG_OF_OWNERSHIP);
        std::string bctMsg = Acore::StringFormat(bct->GetText(loc_idx, caster->getGender()), caster->GetName(), target->GetName());
        caster->Talk(bctMsg, CHAT_MSG_MONSTER_EMOTE, LANG_UNIVERSAL, sWorld->getFloatConfig(CONFIG_LISTEN_RANGE_TEXTEMOTE), target);
        haveTarget = true;
    }
References Unit::CastSpell(), CHAT_MSG_MONSTER_EMOTE, CONFIG_LISTEN_RANGE_TEXTEMOTE, SpellScript::GetCaster(), Unit::getGender(), SpellScript::GetHitPlayer(), WorldObject::GetName(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), BroadcastText::GetText(), haveTarget, Object::IsPlayer(), LANG_UNIVERSAL, sObjectMgr, SPELL_TAUNT_FLAG, Acore::StringFormat(), sWorld, Unit::Talk(), TEXT_FLAG_OF_OWNERSHIP, and Object::ToPlayer().
Referenced by Register().
Load()
bool spell_the_flag_of_ownership::Load () inline override private virtual
Reimplemented from _SpellScript.
    {
        haveTarget = false;
        return true;
    }
References haveTarget.
PrepareSpellScript()
spell_the_flag_of_ownership::PrepareSpellScript (spell_the_flag_of_ownership) private
Register()
void spell_the_flag_of_ownership::Register () inline override private virtual
Implements _SpellScript.
    {
        AfterCast += SpellCastFn(spell_the_flag_of_ownership::HandleFinish);
        OnEffectHitTarget += SpellEffectFn(spell_the_flag_of_ownership::HandleScript, EFFECT_0, SPELL_EFFECT_DUMMY);
        OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_the_flag_of_ownership::FilterTargets, EFFECT_0, TARGET_CORPSE_SRC_AREA_ENEMY);
    }
References SpellScript::AfterCast, EFFECT_0, FilterTargets(), HandleFinish(), HandleScript(), SpellScript::OnEffectHitTarget, SpellScript::OnObjectAreaTargetSelect, SPELL_EFFECT_DUMMY, SpellCastFn, SpellEffectFn, SpellObjectAreaTargetSelectFn, and TARGET_CORPSE_SRC_AREA_ENEMY.
Member Data Documentation
haveTarget
bool spell_the_flag_of_ownership::haveTarget private
Referenced by HandleFinish(), HandleScript(), and Load().