AzerothCore: instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript Struct Reference
instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript Struct Reference
Public Member Functions
instance_eye_of_eternity_InstanceMapScript (Map *pMap)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 type) const override
void ProcessEvent (WorldObject *, uint32 eventId) override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 EncounterStatus
std::string str_data
ObjectGuid NPC_MalygosGUID
ObjectGuid GO_IrisGUID
ObjectGuid GO_ExitPortalGUID
ObjectGuid GO_PlatformGUID
bool bPokeAchiev
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_eye_of_eternity_InstanceMapScript()
instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::instance_eye_of_eternity_InstanceMapScript (Map * pMap) inline
: InstanceScript(pMap) { Initialize(); }
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_10:
                case ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_25:
                    return bPokeAchiev;
                case ACHIEV_CRITERIA_DENYIN_THE_SCION_10:
                case ACHIEV_CRITERIA_DENYIN_THE_SCION_25:
                    return (source && source->GetVehicle() && source->GetVehicle()->GetVehicleInfo()->m_ID == 224);
            }
            return false;
        }
References ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_10, ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_25, ACHIEV_CRITERIA_DENYIN_THE_SCION_10, ACHIEV_CRITERIA_DENYIN_THE_SCION_25, bPokeAchiev, Unit::GetVehicle(), Vehicle::GetVehicleInfo(), and VehicleEntry::m_ID.
GetGuidData()
ObjectGuid instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case DATA_MALYGOS_GUID:
                    return NPC_MalygosGUID;
            }
            return ObjectGuid::Empty;
        }
References DATA_MALYGOS_GUID, ObjectGuid::Empty, and NPC_MalygosGUID.
Initialize()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            EncounterStatus = NOT_STARTED;
            bPokeAchiev = false;
        }
References bPokeAchiev, EncounterStatus, and NOT_STARTED.
Referenced by instance_eye_of_eternity_InstanceMapScript().
IsEncounterInProgress()
bool instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            return EncounterStatus == IN_PROGRESS;
        }
References EncounterStatus, and IN_PROGRESS.
OnCreatureCreate()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_MALYGOS:
                    NPC_MalygosGUID = creature->GetGUID();
                    break;
            }
        }
References Object::GetEntry(), Object::GetGUID(), NPC_MALYGOS, and NPC_MalygosGUID.
OnGameObjectCreate()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_IRIS_N:
                case GO_IRIS_H:
                    GO_IrisGUID = go->GetGUID();
                    break;
                case GO_EXIT_PORTAL:
                    GO_ExitPortalGUID = go->GetGUID();
                    break;
                case GO_NEXUS_PLATFORM:
                    GO_PlatformGUID = go->GetGUID();
                    break;
            }
        }
References Object::GetEntry(), Object::GetGUID(), GO_EXIT_PORTAL, GO_ExitPortalGUID, GO_IRIS_H, GO_IRIS_N, GO_IrisGUID, GO_NEXUS_PLATFORM, and GO_PlatformGUID.
OnPlayerEnter()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter (Player * pPlayer) inline override virtual
Reimplemented from InstanceScript.
        {
            if (EncounterStatus == DONE)
            {
                // destroy platform, hide iris (actually ensure, done at loading, but doesn't always work
                ProcessEvent(nullptr, 20158);
                if (GameObject* go = instance->GetGameObject(GO_IrisGUID))
                    if (go->GetPhaseMask() != 2)
                        go->SetPhaseMask(2, true);
                // no floor, so put players on drakes
                if (pPlayer)
                {
                    if (!pPlayer->IsAlive())
                        return;
                    if (Creature* c = pPlayer->SummonCreature(NPC_WYRMREST_SKYTALON, pPlayer->GetPositionX(), pPlayer->GetPositionY(), pPlayer->GetPositionZ() - 20.0f, 0.0f, TEMPSUMMON_MANUAL_DESPAWN, 0))
                    {
                        c->SetCanFly(true);
                        c->SetFaction(pPlayer->GetFaction());
                        //pPlayer->CastCustomSpell(60683, SPELLVALUE_BASE_POINT0, 1, c, true);
                        c->m_Events.AddEvent(new EoEDrakeEnterVehicleEvent(*c, pPlayer->GetGUID()), c->m_Events.CalculateTime(500));
                    }
                }
            }
        }
References DONE, EncounterStatus, Unit::GetFaction(), Map::GetGameObject(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_IrisGUID, InstanceScript::instance, Unit::IsAlive(), NPC_WYRMREST_SKYTALON, ProcessEvent(), WorldObject::SummonCreature(), and TEMPSUMMON_MANUAL_DESPAWN.
ProcessEvent()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::ProcessEvent (WorldObject * , uint32 eventId) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (eventId)
            {
                case 20158:
                    if (GameObject* go = instance->GetGameObject(GO_PlatformGUID))
                        if (Creature* c = instance->GetCreature(NPC_MalygosGUID))
{
                            go->ModifyHealth(-6500000, c); // We have HP 6 million in the database... So we have to do at least that
                            go->EnableCollision(false);
                        }
                    break;
            }
        }
References Map::GetCreature(), Map::GetGameObject(), GO_PlatformGUID, InstanceScript::instance, and NPC_MalygosGUID.
Referenced by OnPlayerEnter(), and ReadSaveDataMore().
ReadSaveDataMore()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> EncounterStatus;
            switch (EncounterStatus)
            {
                case IN_PROGRESS:
                    EncounterStatus = NOT_STARTED;
                    break;
                case DONE:
                    // destroy platform, hide iris
                    ProcessEvent(nullptr, 20158);
                    if (GameObject* go = instance->GetGameObject(GO_IrisGUID))
                        go->SetPhaseMask(2, true);
                    break;
            }
        }
References DONE, EncounterStatus, Map::GetGameObject(), GO_IrisGUID, IN_PROGRESS, InstanceScript::instance, NOT_STARTED, and ProcessEvent().
SetData()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_IRIS_ACTIVATED:
                    if (EncounterStatus == NOT_STARTED)
                        if (Creature* c = instance->GetCreature(NPC_MalygosGUID))
                            if (Player* plr = c->SelectNearestPlayer(250.0f))
                                c->AI()->AttackStart(plr);
                    break;
                case DATA_ENCOUNTER_STATUS:
                    EncounterStatus = data;
                    switch (data)
                    {
                        case NOT_STARTED:
                            bPokeAchiev = false;
                            if (GameObject* go = instance->GetGameObject(GO_IrisGUID))
{
                                go->SetPhaseMask(1, true);
                                HandleGameObject(GO_IrisGUID, false, go);
                            }
                            if (GameObject* go = instance->GetGameObject(GO_ExitPortalGUID))
                                go->SetPhaseMask(1, true);
                            if (GameObject* go = instance->GetGameObject(GO_PlatformGUID))
{
                                go->SetDestructibleState(GO_DESTRUCTIBLE_REBUILDING, nullptr, true);
                                go->EnableCollision(true);
                            }
                            break;
                        case IN_PROGRESS:
                            bPokeAchiev = (instance->GetPlayersCountExceptGMs() < (instance->GetSpawnMode() == 0 ? (uint32)9 : (uint32)21));
                            break;
                        case DONE:
                            bPokeAchiev = false;
                            if (GameObject* go = instance->GetGameObject(GO_ExitPortalGUID))
                                go->SetPhaseMask(1, true);
                            if (Creature* c = instance->GetCreature(NPC_MalygosGUID))
                                if (c->SummonCreature(NPC_ALEXSTRASZA, 798.0f, 1268.0f, 299.0f, 2.45f, TEMPSUMMON_TIMED_DESPAWN, 604800000))
                                    break;
                    }
                    if (data == DONE)
                        SaveToDB();
                    break;
                case DATA_SET_IRIS_INACTIVE:
                    if (GameObject* go = instance->GetGameObject(GO_IrisGUID))
                    {
                        HandleGameObject(GO_IrisGUID, true, go);
                        if (Creature* c = go->SummonCreature(NPC_WORLD_TRIGGER_LAOI, *go, TEMPSUMMON_TIMED_DESPAWN, 10000))
                            c->CastSpell(c, SPELL_IRIS_ACTIVATED, true);
                    }
                    break;
                case DATA_HIDE_IRIS_AND_PORTAL:
                    if (GameObject* go = instance->GetGameObject(GO_IrisGUID))
                        go->SetPhaseMask(2, true);
                    if (GameObject* go = instance->GetGameObject(GO_ExitPortalGUID))
                        go->SetPhaseMask(2, true);
                    break;
            }
        }
References bPokeAchiev, DATA_ENCOUNTER_STATUS, DATA_HIDE_IRIS_AND_PORTAL, DATA_IRIS_ACTIVATED, DATA_SET_IRIS_INACTIVE, DONE, EncounterStatus, Map::GetCreature(), Map::GetGameObject(), Map::GetPlayersCountExceptGMs(), Map::GetSpawnMode(), GO_DESTRUCTIBLE_REBUILDING, GO_ExitPortalGUID, GO_IrisGUID, GO_PlatformGUID, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, NOT_STARTED, NPC_ALEXSTRASZA, NPC_MalygosGUID, NPC_WORLD_TRIGGER_LAOI, InstanceScript::SaveToDB(), WorldObject::SelectNearestPlayer(), SPELL_IRIS_ACTIVATED, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
WriteSaveDataMore()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << EncounterStatus;
        }
References EncounterStatus.
Member Data Documentation
bPokeAchiev
bool instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::bPokeAchiev
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
EncounterStatus
uint32 instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::EncounterStatus
Referenced by Initialize(), IsEncounterInProgress(), OnPlayerEnter(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
GO_ExitPortalGUID
ObjectGuid instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::GO_ExitPortalGUID
Referenced by OnGameObjectCreate(), and SetData().
GO_IrisGUID
ObjectGuid instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::GO_IrisGUID
Referenced by OnGameObjectCreate(), OnPlayerEnter(), ReadSaveDataMore(), and SetData().
GO_PlatformGUID
ObjectGuid instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::GO_PlatformGUID
Referenced by OnGameObjectCreate(), ProcessEvent(), and SetData().
NPC_MalygosGUID
ObjectGuid instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::NPC_MalygosGUID
Referenced by GetGuidData(), OnCreatureCreate(), ProcessEvent(), and SetData().
str_data
std::string instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::str_data