document.write(`
  <a id="Creature:AddLootMode" class="fn" href="../Creature/AddLootMode.html">AddLootMode</a>
  <a id="Creature:AttackStart" class="fn" href="../Creature/AttackStart.html">AttackStart</a>
  <a id="Creature:CallAssistance" class="fn" href="../Creature/CallAssistance.html">CallAssistance</a>
  <a id="Creature:CallForHelp" class="fn" href="../Creature/CallForHelp.html">CallForHelp</a>
  <a id="Creature:CanAggro" class="fn" href="../Creature/CanAggro.html">CanAggro</a>
  <a id="Creature:CanAssistTo" class="fn" href="../Creature/CanAssistTo.html">CanAssistTo</a>
  <a id="Creature:CanCompleteQuest" class="fn" href="../Creature/CanCompleteQuest.html">CanCompleteQuest</a>
  <a id="Creature:CanFly" class="fn" href="../Creature/CanFly.html">CanFly</a>
  <a id="Creature:CanStartAttack" class="fn" href="../Creature/CanStartAttack.html">CanStartAttack</a>
  <a id="Creature:CanSwim" class="fn" href="../Creature/CanSwim.html">CanSwim</a>
  <a id="Creature:CanWalk" class="fn" href="../Creature/CanWalk.html">CanWalk</a>
  <a id="Creature:DespawnOrUnsummon" class="fn" href="../Creature/DespawnOrUnsummon.html">DespawnOrUnsummon</a>
  <a id="Creature:FleeToGetAssistance" class="fn" href="../Creature/FleeToGetAssistance.html">FleeToGetAssistance</a>
  <a id="Creature:GetAIName" class="fn" href="../Creature/GetAIName.html">GetAIName</a>
  <a id="Creature:GetAITarget" class="fn" href="../Creature/GetAITarget.html">GetAITarget</a>
  <a id="Creature:GetAITargets" class="fn" href="../Creature/GetAITargets.html">GetAITargets</a>
  <a id="Creature:GetAITargetsCount" class="fn" href="../Creature/GetAITargetsCount.html">GetAITargetsCount</a>
  <a id="Creature:GetAggroRange" class="fn" href="../Creature/GetAggroRange.html">GetAggroRange</a>
  <a id="Creature:GetAttackDistance" class="fn" href="../Creature/GetAttackDistance.html">GetAttackDistance</a>
  <a id="Creature:GetCorpseDelay" class="fn" href="../Creature/GetCorpseDelay.html">GetCorpseDelay</a>
  <a id="Creature:GetCreatureFamily" class="fn" href="../Creature/GetCreatureFamily.html">GetCreatureFamily</a>
  <a id="Creature:GetCreatureSpellCooldownDelay" class="fn" href="../Creature/GetCreatureSpellCooldownDelay.html">GetCreatureSpellCooldownDelay</a>
  <a id="Creature:GetCurrentWaypointId" class="fn" href="../Creature/GetCurrentWaypointId.html">GetCurrentWaypointId</a>
  <a id="Creature:GetDBTableGUIDLow" class="fn" href="../Creature/GetDBTableGUIDLow.html">GetDBTableGUIDLow</a>
  <a id="Creature:GetDefaultMovementType" class="fn" href="../Creature/GetDefaultMovementType.html">GetDefaultMovementType</a>
  <a id="Creature:GetExtraFlags" class="fn" href="../Creature/GetExtraFlags.html">GetExtraFlags</a>
  <a id="Creature:GetHomePosition" class="fn" href="../Creature/GetHomePosition.html">GetHomePosition</a>
  <a id="Creature:GetLootMode" class="fn" href="../Creature/GetLootMode.html">GetLootMode</a>
  <a id="Creature:GetLootRecipient" class="fn" href="../Creature/GetLootRecipient.html">GetLootRecipient</a>
  <a id="Creature:GetLootRecipientGroup" class="fn" href="../Creature/GetLootRecipientGroup.html">GetLootRecipientGroup</a>
  <a id="Creature:GetNPCFlags" class="fn" href="../Creature/GetNPCFlags.html">GetNPCFlags</a>
  <a id="Creature:GetRank" class="fn" href="../Creature/GetRank.html">GetRank</a>
  <a id="Creature:GetRespawnDelay" class="fn" href="../Creature/GetRespawnDelay.html">GetRespawnDelay</a>
  <a id="Creature:GetScriptId" class="fn" href="../Creature/GetScriptId.html">GetScriptId</a>
  <a id="Creature:GetScriptName" class="fn" href="../Creature/GetScriptName.html">GetScriptName</a>
  <a id="Creature:GetShieldBlockValue" class="fn" href="../Creature/GetShieldBlockValue.html">GetShieldBlockValue</a>
  <a id="Creature:GetUnitFlags" class="fn" href="../Creature/GetUnitFlags.html">GetUnitFlags</a>
  <a id="Creature:GetUnitFlagsTwo" class="fn" href="../Creature/GetUnitFlagsTwo.html">GetUnitFlagsTwo</a>
  <a id="Creature:GetWanderRadius" class="fn" href="../Creature/GetWanderRadius.html">GetWanderRadius</a>
  <a id="Creature:GetWaypointPath" class="fn" href="../Creature/GetWaypointPath.html">GetWaypointPath</a>
  <a id="Creature:HasCategoryCooldown" class="fn" href="../Creature/HasCategoryCooldown.html">HasCategoryCooldown</a>
  <a id="Creature:HasLootMode" class="fn" href="../Creature/HasLootMode.html">HasLootMode</a>
  <a id="Creature:HasLootRecipient" class="fn" href="../Creature/HasLootRecipient.html">HasLootRecipient</a>
  <a id="Creature:HasQuest" class="fn" href="../Creature/HasQuest.html">HasQuest</a>
  <a id="Creature:HasSearchedAssistance" class="fn" href="../Creature/HasSearchedAssistance.html">HasSearchedAssistance</a>
  <a id="Creature:HasSpell" class="fn" href="../Creature/HasSpell.html">HasSpell</a>
  <a id="Creature:HasSpellCooldown" class="fn" href="../Creature/HasSpellCooldown.html">HasSpellCooldown</a>
  <a id="Creature:IsCivilian" class="fn" href="../Creature/IsCivilian.html">IsCivilian</a>
  <a id="Creature:IsDamageEnoughForLootingAndReward" class="fn" href="../Creature/IsDamageEnoughForLootingAndReward.html">IsDamageEnoughForLootingAndReward</a>
  <a id="Creature:IsDungeonBoss" class="fn" href="../Creature/IsDungeonBoss.html">IsDungeonBoss</a>
  <a id="Creature:IsElite" class="fn" href="../Creature/IsElite.html">IsElite</a>
  <a id="Creature:IsGuard" class="fn" href="../Creature/IsGuard.html">IsGuard</a>
  <a id="Creature:IsInEvadeMode" class="fn" href="../Creature/IsInEvadeMode.html">IsInEvadeMode</a>
  <a id="Creature:IsRacialLeader" class="fn" href="../Creature/IsRacialLeader.html">IsRacialLeader</a>
  <a id="Creature:IsRegeneratingHealth" class="fn" href="../Creature/IsRegeneratingHealth.html">IsRegeneratingHealth</a>
  <a id="Creature:IsReputationGainDisabled" class="fn" href="../Creature/IsReputationGainDisabled.html">IsReputationGainDisabled</a>
  <a id="Creature:IsTappedBy" class="fn" href="../Creature/IsTappedBy.html">IsTappedBy</a>
  <a id="Creature:IsTargetableForAttack" class="fn" href="../Creature/IsTargetableForAttack.html">IsTargetableForAttack</a>
  <a id="Creature:IsTrigger" class="fn" href="../Creature/IsTrigger.html">IsTrigger</a>
  <a id="Creature:IsWorldBoss" class="fn" href="../Creature/IsWorldBoss.html">IsWorldBoss</a>
  <a id="Creature:MoveWaypoint" class="fn" href="../Creature/MoveWaypoint.html">MoveWaypoint</a>
  <a id="Creature:RemoveCorpse" class="fn" href="../Creature/RemoveCorpse.html">RemoveCorpse</a>
  <a id="Creature:RemoveLootMode" class="fn" href="../Creature/RemoveLootMode.html">RemoveLootMode</a>
  <a id="Creature:ResetLootMode" class="fn" href="../Creature/ResetLootMode.html">ResetLootMode</a>
  <a id="Creature:Respawn" class="fn" href="../Creature/Respawn.html">Respawn</a>
  <a id="Creature:SaveToDB" class="fn" href="../Creature/SaveToDB.html">SaveToDB</a>
  <a id="Creature:SelectVictim" class="fn" href="../Creature/SelectVictim.html">SelectVictim</a>
  <a id="Creature:SetAggroEnabled" class="fn" href="../Creature/SetAggroEnabled.html">SetAggroEnabled</a>
  <a id="Creature:SetDeathState" class="fn" href="../Creature/SetDeathState.html">SetDeathState</a>
  <a id="Creature:SetDefaultMovementType" class="fn" href="../Creature/SetDefaultMovementType.html">SetDefaultMovementType</a>
  <a id="Creature:SetDisableGravity" class="fn" href="../Creature/SetDisableGravity.html">SetDisableGravity</a>
  <a id="Creature:SetDisableReputationGain" class="fn" href="../Creature/SetDisableReputationGain.html">SetDisableReputationGain</a>
  <a id="Creature:SetEquipmentSlots" class="fn" href="../Creature/SetEquipmentSlots.html">SetEquipmentSlots</a>
  <a id="Creature:SetHomePosition" class="fn" href="../Creature/SetHomePosition.html">SetHomePosition</a>
  <a id="Creature:SetHover" class="fn" href="../Creature/SetHover.html">SetHover</a>
  <a id="Creature:SetInCombatWithZone" class="fn" href="../Creature/SetInCombatWithZone.html">SetInCombatWithZone</a>
  <a id="Creature:SetLootMode" class="fn" href="../Creature/SetLootMode.html">SetLootMode</a>
  <a id="Creature:SetNPCFlags" class="fn" href="../Creature/SetNPCFlags.html">SetNPCFlags</a>
  <a id="Creature:SetNoCallAssistance" class="fn" href="../Creature/SetNoCallAssistance.html">SetNoCallAssistance</a>
  <a id="Creature:SetNoSearchAssistance" class="fn" href="../Creature/SetNoSearchAssistance.html">SetNoSearchAssistance</a>
  <a id="Creature:SetReactState" class="fn" href="../Creature/SetReactState.html">SetReactState</a>
  <a id="Creature:SetRegeneratingHealth" class="fn" href="../Creature/SetRegeneratingHealth.html">SetRegeneratingHealth</a>
  <a id="Creature:SetRespawnDelay" class="fn" href="../Creature/SetRespawnDelay.html">SetRespawnDelay</a>
  <a id="Creature:SetUnitFlags" class="fn" href="../Creature/SetUnitFlags.html">SetUnitFlags</a>
  <a id="Creature:SetUnitFlagsTwo" class="fn" href="../Creature/SetUnitFlagsTwo.html">SetUnitFlagsTwo</a>
  <a id="Creature:SetWalk" class="fn" href="../Creature/SetWalk.html">SetWalk</a>
  <a id="Creature:SetWanderRadius" class="fn" href="../Creature/SetWanderRadius.html">SetWanderRadius</a>
  <a id="Creature:UpdateEntry" class="fn" href="../Creature/UpdateEntry.html">UpdateEntry</a>
`);