AzeorthCore: instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript Struct Reference
instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript Struct Reference
Public Member Functions
instance_onyxias_lair_InstanceMapScript (Map *pMap)
void Initialize () override
void OnGameObjectCreate (GameObject *go) override
bool SetBossState (uint32 type, EncounterState state) override
void SetData (uint32 uiType, uint32) override
std::string GetSaveData () override
void Load (const char *in) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
std::string str_data
uint16 ManyWhelpsCounter
bool bDeepBreath
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Constructor & Destructor Documentation
instance_onyxias_lair_InstanceMapScript()
instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::instance_onyxias_lair_InstanceMapScript (Map * pMap) inline
: InstanceScript(pMap) {Initialize();};
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch(criteria_id)
            {
                case ACHIEV_CRITERIA_MANY_WHELPS_10_PLAYER:
                case ACHIEV_CRITERIA_MANY_WHELPS_25_PLAYER:
                    return ManyWhelpsCounter >= 50;
                case ACHIEV_CRITERIA_DEEP_BREATH_10_PLAYER:
                case ACHIEV_CRITERIA_DEEP_BREATH_25_PLAYER:
                    return bDeepBreath;
            }
            return false;
        }
References ACHIEV_CRITERIA_DEEP_BREATH_10_PLAYER, ACHIEV_CRITERIA_DEEP_BREATH_25_PLAYER, ACHIEV_CRITERIA_MANY_WHELPS_10_PLAYER, ACHIEV_CRITERIA_MANY_WHELPS_25_PLAYER, bDeepBreath, and ManyWhelpsCounter.
GetSaveData()
std::string instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
        {
            OUT_SAVE_INST_DATA;
            std::ostringstream saveStream;
            saveStream << "O L " << GetBossSaveData();
            str_data = saveStream.str();
            OUT_SAVE_INST_DATA_COMPLETE;
            return str_data;
        }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, and str_data.
Initialize()
void instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetBossNumber(MAX_ENCOUNTER);
            ManyWhelpsCounter = 0;
            bDeepBreath = true;
            LoadObjectData(creatureData, nullptr);
        }
References bDeepBreath, creatureData, InstanceScript::LoadObjectData(), ManyWhelpsCounter, MAX_ENCOUNTER, and InstanceScript::SetBossNumber().
Referenced by instance_onyxias_lair_InstanceMapScript().
Load()
void instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!in)
            {
                OUT_LOAD_INST_DATA_FAIL;
                return;
            }
            OUT_LOAD_INST_DATA(in);
            char dataHead1, dataHead2;
            uint16 data0;
            std::istringstream loadStream(in);
            loadStream >> dataHead1 >> dataHead2 >> data0;
            if (dataHead1 == 'O' && dataHead2 == 'L')
            {
                for (uint32 i = 0; i < MAX_ENCOUNTER; ++i)
                {
                    uint32 tmpState;
                    loadStream >> tmpState;
                    if (tmpState == IN_PROGRESS || tmpState == FAIL || tmpState > SPECIAL)
                    {
                        tmpState = NOT_STARTED;
                    }
                    SetBossState(i, EncounterState(tmpState));
                }
            }
            else
                OUT_LOAD_INST_DATA_FAIL;
            OUT_LOAD_INST_DATA_COMPLETE;
        }
References FAIL, IN_PROGRESS, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), and SPECIAL.
OnGameObjectCreate()
void instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_WHELP_SPAWNER:
                    go->CastSpell((Unit*)nullptr, 17646);
                    if (Creature* onyxia = GetCreature(DATA_ONYXIA))
                    {
                        onyxia->AI()->DoAction(-1);
                    }
                    break;
            }
        }
References GameObject::CastSpell(), DATA_ONYXIA, InstanceScript::GetCreature(), Object::GetEntry(), and GO_WHELP_SPAWNER.
SetBossState()
bool instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
            {
                return false;
            }
            if (type == DATA_ONYXIA && state == NOT_STARTED)
            {
                ManyWhelpsCounter = 0;
                bDeepBreath = true;
            }
            return true;
        }
References bDeepBreath, DATA_ONYXIA, ManyWhelpsCounter, NOT_STARTED, and InstanceScript::SetBossState().
Referenced by Load().
SetData()
void instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::SetData (uint32 uiType, uint32) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (uiType)
            {
                case DATA_WHELP_SUMMONED:
                    ++ManyWhelpsCounter;
                    break;
                case DATA_DEEP_BREATH_FAILED:
                    bDeepBreath = false;
                    break;
            }
        }
References bDeepBreath, DATA_DEEP_BREATH_FAILED, DATA_WHELP_SUMMONED, and ManyWhelpsCounter.
Member Data Documentation
bDeepBreath
bool instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::bDeepBreath
Referenced by CheckAchievementCriteriaMeet(), Initialize(), SetBossState(), and SetData().
ManyWhelpsCounter
uint16 instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::ManyWhelpsCounter
Referenced by CheckAchievementCriteriaMeet(), Initialize(), SetBossState(), and SetData().
str_data
std::string instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::str_data
Referenced by GetSaveData().