AzerothCore: GridObject< T > Class Template Reference
GridObject< T > Class Template Reference
#include "Object.h"
Public Member Functions
bool IsInGrid () const
void AddToGrid (GridRefMgr< T > &m)
void RemoveFromGrid ()
Private Attributes
GridReference< T > _gridRef
Detailed Description
template<class T>
class GridObject< T >
Member Function Documentation
AddToGrid()
template<class T > void GridObject< T >::AddToGrid (GridRefMgr< T > & m) inline
{ ASSERT(!IsInGrid()); _gridRef.link(&m, (T*)this); }
References GridObject< T >::_gridRef, ASSERT, GridObject< T >::IsInGrid(), and Reference< TO, FROM >::link().
Referenced by AddObjectHelper().
IsInGrid()
template<class T > bool GridObject< T >::IsInGrid () const inline
{ return _gridRef.isValid(); }
References GridObject< T >::_gridRef, and Reference< TO, FROM >::isValid().
Referenced by GridObject< T >::AddToGrid(), Map::RemoveCorpse(), GridObject< T >::RemoveFromGrid(), and Map::RemovePlayerFromMap().
RemoveFromGrid()
template<class T > void GridObject< T >::RemoveFromGrid () inline
{ ASSERT(IsInGrid()); _gridRef.unlink(); }
References GridObject< T >::_gridRef, ASSERT, GridObject< T >::IsInGrid(), and Reference< TO, FROM >::unlink().
Referenced by Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), Map::PlayerRelocation(), Map::RemovePlayerFromMap(), and Map::SwitchGridContainers().
Member Data Documentation
_gridRef
template<class T > GridReference<T> GridObject< T >::_gridRef private
Referenced by GridObject< T >::AddToGrid(), GridObject< T >::IsInGrid(), and GridObject< T >::RemoveFromGrid().