AzerothCore: AuthHelper Namespace Reference
AuthHelper Namespace Reference
Functions
bool IsPreBCAcceptedClientBuild (uint32 build)
bool IsPostBCAcceptedClientBuild (uint32 build)
bool IsAcceptedClientBuild (uint32 build)
Variables
static constexpr uint32 MAX_PRE_BC_CLIENT_BUILD = 6141
Function Documentation
IsAcceptedClientBuild()
bool AuthHelper::IsAcceptedClientBuild (uint32 build)
    {
        return sRealmList->GetBuildInfo(build) != nullptr;
    }
References sRealmList.
Referenced by AuthSession::LogonChallengeCallback().
IsPostBCAcceptedClientBuild()
bool AuthHelper::IsPostBCAcceptedClientBuild (uint32 build)
    {
        return build > MAX_PRE_BC_CLIENT_BUILD && sRealmList->GetBuildInfo(build);
    }
References MAX_PRE_BC_CLIENT_BUILD, and sRealmList.
Referenced by AuthSession::HandleLogonChallenge(), and AuthSession::HandleReconnectChallenge().
IsPreBCAcceptedClientBuild()
bool AuthHelper::IsPreBCAcceptedClientBuild (uint32 build)
    {
        return build <= MAX_PRE_BC_CLIENT_BUILD && sRealmList->GetBuildInfo(build);
    }
References MAX_PRE_BC_CLIENT_BUILD, and sRealmList.
Referenced by AuthSession::HandleLogonChallenge(), AuthSession::HandleReconnectChallenge(), and AuthSession::RealmListCallback().
Variable Documentation
MAX_PRE_BC_CLIENT_BUILD
constexpr uint32 AuthHelper::MAX_PRE_BC_CLIENT_BUILD = 6141 static constexpr
Referenced by IsPostBCAcceptedClientBuild(), and IsPreBCAcceptedClientBuild().