AzerothCore: Movement::counter< T, limit > Class Template Reference
Movement::counter< T, limit > Class Template Reference
#include "MovementTypedefs.h"
Public Member Functions
counter ()
void Increase ()
T NewId ()
T getCurrent () const
Private Member Functions
void init ()
Private Attributes
T m_counter
Detailed Description
template<class T, T limit>
class Movement::counter< T, limit >
Constructor & Destructor Documentation
counter()
template<class T , T limit> Movement::counter< T, limit >::counter () inline
{ init(); }
References Movement::counter< T, limit >::init().
Member Function Documentation
getCurrent()
template<class T , T limit> T Movement::counter< T, limit >::getCurrent () const inline
{ return m_counter; }
References Movement::counter< T, limit >::m_counter.
Increase()
template<class T , T limit> void Movement::counter< T, limit >::Increase () inline
        {
            if (m_counter == limit)
                init();
            else
                ++m_counter;
        }
References Movement::counter< T, limit >::init(), and Movement::counter< T, limit >::m_counter.
Referenced by Movement::counter< T, limit >::NewId().
init()
template<class T , T limit> void Movement::counter< T, limit >::init () inline private
{ m_counter = 0; }
References Movement::counter< T, limit >::m_counter.
Referenced by Movement::counter< T, limit >::counter(), and Movement::counter< T, limit >::Increase().
NewId()
template<class T , T limit> T Movement::counter< T, limit >::NewId () inline
{ Increase(); return m_counter; }
References Movement::counter< T, limit >::Increase(), and Movement::counter< T, limit >::m_counter.
Referenced by Movement::MoveSplineInit::MoveSplineInit().
Member Data Documentation
m_counter
template<class T , T limit> T Movement::counter< T, limit >::m_counter private
Referenced by Movement::counter< T, limit >::getCurrent(), Movement::counter< T, limit >::Increase(), Movement::counter< T, limit >::init(), and Movement::counter< T, limit >::NewId().