AzerothCore: DBCFile Class Reference
DBCFile Class Reference
#include "dbcfile.h"
Classes
class Exception
class Iterator
class NotFound
class Record
Public Member Functions
DBCFile (std::string filename)
~DBCFile ()
bool open ()
Record getRecord (std::size_t id)
Iterator begin ()
Get begin iterator over records.
Iterator end ()
Get begin iterator over records.
std::size_t getRecordCount () const
Trivial.
std::size_t getFieldCount () const
std::size_t getMaxId ()
DBCFile (std::string filename)
~DBCFile ()
bool open ()
Record getRecord (std::size_t id)
Iterator begin ()
Get begin iterator over records.
Iterator end ()
Get begin iterator over records.
std::size_t getRecordCount () const
Trivial.
std::size_t getFieldCount () const
Private Attributes
std::string filename
std::size_t recordSize
std::size_t recordCount
std::size_t fieldCount
std::size_t stringSize
unsigned char * data
unsigned char * stringTable
Detailed Description
Constructor & Destructor Documentation
DBCFile() [1/2]
DBCFile::DBCFile (std::string filename)
                                   :
    filename(std::move(filename)), recordSize(0), recordCount(0), fieldCount(0), stringSize(0), data(nullptr), stringTable(nullptr)
{
}
~DBCFile() [1/2]
DBCFile::~DBCFile ()
{
    delete [] data;
}
References data.
DBCFile() [2/2]
DBCFile::DBCFile (std::string filename)
~DBCFile() [2/2]
DBCFile::~DBCFile ()
Member Function Documentation
begin() [1/2]
DBCFile::Iterator DBCFile::begin ()
Get begin iterator over records.
{
    assert(data);
    return Iterator(*this, data);
}
References data.
begin() [2/2]
Iterator DBCFile::begin ()
Get begin iterator over records.
end() [1/2]
DBCFile::Iterator DBCFile::end ()
Get begin iterator over records.
{
    assert(data);
    return Iterator(*this, stringTable);
}
References data, and stringTable.
end() [2/2]
Iterator DBCFile::end ()
Get begin iterator over records.
getFieldCount() [1/2]
std::size_t DBCFile::getFieldCount () const inline
{ return fieldCount; }
References fieldCount.
getFieldCount() [2/2]
std::size_t DBCFile::getFieldCount () const inline
{ return fieldCount; }
References fieldCount.
getMaxId()
std::size_t DBCFile::getMaxId ()
{
    assert(data);
    std::size_t maxId = 0;
    for (std::size_t i = 0; i < getRecordCount(); ++i)
    {
        if (maxId < getRecord(i).getUInt(0))
            maxId = getRecord(i).getUInt(0);
    }
    return maxId;
}
References data, getRecord(), getRecordCount(), and DBCFile::Record::getUInt().
getRecord() [1/2]
DBCFile::Record DBCFile::getRecord (std::size_t id)
{
    assert(data);
    return Record(*this, data + id * recordSize);
}
References data, and recordSize.
Referenced by ExtractCameraFiles(), getMaxId(), main(), ReadLiquidTypeTableDBC(), and ReadMapDBC().
getRecord() [2/2]
Record DBCFile::getRecord (std::size_t id)
getRecordCount() [1/2]
std::size_t DBCFile::getRecordCount () const inline
Trivial.
{ return recordCount;}
References recordCount.
Referenced by ExtractCameraFiles(), getMaxId(), main(), ReadLiquidTypeTableDBC(), and ReadMapDBC().
getRecordCount() [2/2]
std::size_t DBCFile::getRecordCount () const inline
Trivial.
{ return recordCount;}
References recordCount.
open() [1/2]
bool DBCFile::open ()
{
    MPQFile f(filename.c_str());
    char header[4];
    unsigned int na, nb, es, ss;
    if (f.read(header, 4) != 4)                             // Number of records
        return false;
    if (header[0] != 'W' || header[1] != 'D' || header[2] != 'B' || header[3] != 'C')
        return false;
    if (f.read(&na, 4) != 4)                                // Number of records
        return false;
    if (f.read(&nb, 4) != 4)                                // Number of fields
        return false;
    if (f.read(&es, 4) != 4)                                // Size of a record
        return false;
    if (f.read(&ss, 4) != 4)                                // String size
        return false;
    recordSize = es;
    recordCount = na;
    fieldCount = nb;
    stringSize = ss;
    if (fieldCount * 4 != recordSize)
        return false;
    data = new unsigned char[recordSize * recordCount + stringSize];
    stringTable = data + recordSize * recordCount;
    std::size_t data_size = recordSize * recordCount + stringSize;
    if (f.read(data, data_size) != data_size)
        return false;
    f.close();
    return true;
}
References MPQFile::close(), data, fieldCount, filename, MPQFile::read(), recordCount, recordSize, stringSize, and stringTable.
Referenced by ExtractCameraFiles(), ExtractGameobjectModels(), main(), ReadLiquidTypeTableDBC(), and ReadMapDBC().
open() [2/2]
bool DBCFile::open ()
Member Data Documentation
data
unsigned char * DBCFile::data private
Referenced by begin(), end(), getMaxId(), getRecord(), open(), and ~DBCFile().
fieldCount
std::size_t DBCFile::fieldCount private
Referenced by getFieldCount(), DBCFile::Record::getFloat(), DBCFile::Record::getInt(), DBCFile::Record::getString(), DBCFile::Record::getUInt(), and open().
filename
std::string DBCFile::filename private
Referenced by open().
recordCount
std::size_t DBCFile::recordCount private
Referenced by getRecordCount(), and open().
recordSize
std::size_t DBCFile::recordSize private
Referenced by DBCFile::Record::getByte(), getRecord(), open(), and DBCFile::Iterator::operator++().
stringSize
std::size_t DBCFile::stringSize private
Referenced by DBCFile::Record::getString(), and open().
stringTable
unsigned char * DBCFile::stringTable private
Referenced by end(), DBCFile::Record::getString(), and open().