AzerothCore: lapseTeleport Class Reference
lapseTeleport Class Reference
Public Member Functions
lapseTeleport (Player *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Player * _owner
Detailed Description
Constructor & Destructor Documentation
lapseTeleport()
lapseTeleport::lapseTeleport (Player * owner) inline
                                 : _owner(owner)
    {
    }
Member Function Documentation
Execute()
bool lapseTeleport::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        if (_owner->IsBeingTeleportedNear())
            _owner->m_Events.AddEvent(new lapseTeleport(_owner), _owner->m_Events.CalculateTime(1));
        else if (!_owner->IsBeingTeleported())
        {
            _owner->CastSpell(_owner, SPELL_GRAVITY_LAPSE_KNOCKBACK, true);
            _owner->CastSpell(_owner, SPELL_GRAVITY_LAPSE_AURA, true);
        }
        return true;
    }
References _owner, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::CastSpell(), Player::IsBeingTeleported(), Player::IsBeingTeleportedNear(), WorldObject::m_Events, SPELL_GRAVITY_LAPSE_AURA, and SPELL_GRAVITY_LAPSE_KNOCKBACK.
Member Data Documentation
_owner
Player* lapseTeleport::_owner private
Referenced by Execute().