AzerothCore: HostileReference Class Reference
HostileReference Class Reference
#include "ThreatMgr.h"
Public Member Functions
HostileReference (Unit *refUnit, ThreatMgr *threatMgr, float threat)
Unit * GetOwner () const
Unit * GetVictim () const
void AddThreat (float modThreat)
void SetThreat (float threat)
void addThreatPercent (int32 percent)
float GetThreat () const
void ClearThreat ()
bool IsOnline () const
bool IsAvailable () const
bool IsOffline () const
void setTempThreat (float threat)
void addTempThreat (float threat)
void resetTempThreat ()
float getTempThreatModifier ()
void updateOnlineStatus ()
void setOnlineOfflineState (bool isOnline)
bool operator== (const HostileReference &hostileRef) const
ObjectGuid getUnitGuid () const
void removeReference ()
HostileReference * next ()
void targetObjectBuildLink () override
void targetObjectDestroyLink () override
void sourceObjectDestroyLink () override
Public Member Functions inherited from Reference< Unit, ThreatMgr >
Reference ()
virtual ~Reference ()=default
void link (Unit *toObj, ThreatMgr *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< Unit, ThreatMgr > * next ()
Reference< Unit, ThreatMgr > const * next () const
Reference< Unit, ThreatMgr > * prev ()
Reference< Unit, ThreatMgr > const * prev () const
Reference< Unit, ThreatMgr > * nocheck_next ()
Reference< Unit, ThreatMgr > const * nocheck_next () const
Reference< Unit, ThreatMgr > * nocheck_prev ()
Reference< Unit, ThreatMgr > const * nocheck_prev () const
Unit * operator-> () const
Unit * getTarget () const
ThreatMgr * GetSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()=default
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Private Member Functions
void fireStatusChanged (ThreatRefStatusChangeEvent &threatRefStatusChangeEvent)
Unit * GetSourceUnit ()
Private Attributes
float iThreat
float iTempThreatModifier
ObjectGuid iUnitGuid
bool iOnline
Additional Inherited Members
virtual void targetObjectBuildLink ()=0
virtual void targetObjectDestroyLink ()=0
virtual void sourceObjectDestroyLink ()=0
Detailed Description
Constructor & Destructor Documentation
HostileReference()
HostileReference::HostileReference (Unit * refUnit, ThreatMgr * threatMgr, float threat)
{
    iThreat = threat;
    iTempThreatModifier = 0.0f;
    link(refUnit, threatMgr);
    iUnitGuid = refUnit->GetGUID();
    iOnline = true;
}
References Object::GetGUID(), iOnline, iTempThreatModifier, iThreat, iUnitGuid, and Reference< Unit, ThreatMgr >::link().
Member Function Documentation
addTempThreat()
void HostileReference::addTempThreat (float threat) inline
    {
        iTempThreatModifier = threat;
        if (iTempThreatModifier != 0.0f)
            AddThreat(iTempThreatModifier);
    }
References AddThreat(), and iTempThreatModifier.
Referenced by HostileRefMgr::addTempThreat(), and setTempThreat().
AddThreat()
void HostileReference::AddThreat (float modThreat)
{
    iThreat += modThreat;
    // the threat is changed. Source and target unit have to be available
    // if the link was cut before relink it again
    if (!IsOnline())
        updateOnlineStatus();
    if (modThreat != 0.0f)
    {
        ThreatRefStatusChangeEvent event(UEV_THREAT_REF_THREAT_CHANGE, this, modThreat);
        fireStatusChanged(event);
    }
    if (isValid() && modThreat >= 0.0f)
    {
        Unit* target = getTarget();
        if (target->GetEntry() != NPC_EYE_OF_KILROGG) // Excluded Eye of Kilrogg
        {
            Unit* victimOwner = target->GetCharmerOrOwner();
            if (victimOwner && victimOwner->IsAlive())
            {
                GetSource()->AddThreat(victimOwner, 0.0f); // create a threat to the owner of a pet, if the pet attacks
            }
        }
    }
}
References ThreatMgr::AddThreat(), fireStatusChanged(), Unit::GetCharmerOrOwner(), Object::GetEntry(), Reference< Unit, ThreatMgr >::GetSource(), Reference< Unit, ThreatMgr >::getTarget(), Unit::IsAlive(), IsOnline(), Reference< Unit, ThreatMgr >::isValid(), iThreat, NPC_EYE_OF_KILROGG, UEV_THREAT_REF_THREAT_CHANGE, and updateOnlineStatus().
Referenced by ThreatMgr::_addThreat(), addTempThreat(), ThreatContainer::AddThreat(), addThreatPercent(), npc_pet_mage_mirror_image::InitializeAI(), resetTempThreat(), and SetThreat().
addThreatPercent()
void HostileReference::addThreatPercent (int32 percent)
{
    // Xinef: Do not allow to modify threat by percent if threat is negative (forced to big value < 0 by spells adding temporary threat)
    // Xinef: When the temporary effect ends, temporary threat is added back which results in huge additional amount of threat
    if (iThreat <= 0)
        return;
    float tmpThreat = iThreat;
    AddPct(tmpThreat, percent);
    AddThreat(tmpThreat - iThreat);
}
References AddPct(), AddThreat(), and iThreat.
Referenced by HostileRefMgr::addThreatPercent().
ClearThreat()
void HostileReference::ClearThreat () inline
{ removeReference(); }
References removeReference().
fireStatusChanged()
void HostileReference::fireStatusChanged (ThreatRefStatusChangeEvent & threatRefStatusChangeEvent) private
{
    if (GetSource())
        GetSource()->processThreatEvent(&threatRefStatusChangeEvent);
}
References Reference< Unit, ThreatMgr >::GetSource(), and ThreatMgr::processThreatEvent().
Referenced by AddThreat(), removeReference(), and setOnlineOfflineState().
GetOwner()
Unit * HostileReference::GetOwner () const
{ return GetSource()->GetOwner(); }
References ThreatMgr::GetOwner(), and Reference< Unit, ThreatMgr >::GetSource().
Referenced by GetSourceUnit().
GetSourceUnit()
Unit * HostileReference::GetSourceUnit () private
{
    return (GetSource()->GetOwner());
}
References GetOwner(), and Reference< Unit, ThreatMgr >::GetSource().
Referenced by updateOnlineStatus().
getTempThreatModifier()
float HostileReference::getTempThreatModifier () inline
{ return iTempThreatModifier; }
References iTempThreatModifier.
Referenced by HostileRefMgr::addTempThreat(), ThreatMgr::getThreatWithoutTemp(), npc_pet_mage_mirror_image::InitializeAI(), and ThreatMgr::tauntApply().
GetThreat()
float HostileReference::GetThreat () const inline
{ return iThreat; }
References iThreat.
Referenced by Spell::EffectTaunt(), ThreatMgr::GetThreat(), ThreatMgr::getThreatWithoutTemp(), debug_commandscript::HandleDebugHostileRefListCommand(), npc_pet_mage_mirror_image::InitializeAI(), Acore::ThreatOrderPred::operator()(), ThreatMgr::processThreatEvent(), ThreatContainer::SelectNextVictim(), setTempThreat(), SetThreat(), and ThreatMgr::tauntApply().
getUnitGuid()
ObjectGuid HostileReference::getUnitGuid () const inline
{ return iUnitGuid; }
References iUnitGuid.
Referenced by ThreatContainer::getReferenceByTarget(), Unit::IsInCombatWith(), operator==(), ThreatMgr::processThreatEvent(), Unit::SendChangeCurrentVictimOpcode(), Unit::SendRemoveFromThreatListOpcode(), and updateOnlineStatus().
GetVictim()
Unit * HostileReference::GetVictim () const inline
{ return getTarget(); }
References Reference< Unit, ThreatMgr >::getTarget().
IsAvailable()
bool HostileReference::IsAvailable () const inline
{ return iOnline; } // unused for now
References iOnline.
IsOffline()
bool HostileReference::IsOffline () const inline
{ return !iOnline; } // unused for now
References iOnline.
IsOnline()
bool HostileReference::IsOnline () const inline
{ return iOnline; }
References iOnline.
Referenced by AddThreat(), debug_commandscript::HandleDebugHostileRefListCommand(), and ThreatMgr::processThreatEvent().
next()
HostileReference * HostileReference::next () inline
{ return ((HostileReference*) Reference<Unit, ThreatMgr>::next()); }
Referenced by HostileRefMgr::addTempThreat(), HostileRefMgr::addThreatPercent(), HostileRefMgr::deleteReference(), HostileRefMgr::deleteReferences(), HostileRefMgr::deleteReferencesForFaction(), HostileRefMgr::deleteReferencesOutOfRange(), debug_commandscript::HandleDebugHostileRefListCommand(), npc_pet_mage_mirror_image::InitializeAI(), HostileRefMgr::setOnlineOfflineState(), Unit::SetPhaseMask(), HostileRefMgr::threatAssist(), Map::Update(), HostileRefMgr::updateThreatTables(), and HostileRefMgr::UpdateVisibility().
operator==()
bool HostileReference::operator== (const HostileReference & hostileRef) const inline
{ return hostileRef.getUnitGuid() == getUnitGuid(); }
References getUnitGuid().
removeReference()
void HostileReference::removeReference ()
{
    invalidate();
    ThreatRefStatusChangeEvent event(UEV_THREAT_REF_REMOVE_FROM_LIST, this);
    fireStatusChanged(event);
}
References fireStatusChanged(), Reference< Unit, ThreatMgr >::invalidate(), and UEV_THREAT_REF_REMOVE_FROM_LIST.
Referenced by ClearThreat(), HostileRefMgr::deleteReference(), HostileRefMgr::deleteReferences(), HostileRefMgr::deleteReferencesForFaction(), HostileRefMgr::deleteReferencesOutOfRange(), and HostileRefMgr::UpdateVisibility().
resetTempThreat()
void HostileReference::resetTempThreat () inline
    {
        if (iTempThreatModifier != 0.0f)
        {
            AddThreat(-iTempThreatModifier);
            iTempThreatModifier = 0.0f;
        }
    }
References AddThreat(), and iTempThreatModifier.
Referenced by HostileRefMgr::addTempThreat(), and ThreatMgr::tauntFadeOut().
setOnlineOfflineState()
void HostileReference::setOnlineOfflineState (bool isOnline)
{
    if (iOnline != isOnline)
    {
        iOnline = isOnline;
        ThreatRefStatusChangeEvent event(UEV_THREAT_REF_ONLINE_STATUS, this);
        fireStatusChanged(event);
    }
}
References fireStatusChanged(), iOnline, and UEV_THREAT_REF_ONLINE_STATUS.
Referenced by ThreatMgr::_addThreat(), HostileRefMgr::setOnlineOfflineState(), sourceObjectDestroyLink(), and updateOnlineStatus().
setTempThreat()
void HostileReference::setTempThreat (float threat) inline
    {
        addTempThreat(threat - GetThreat());
    }
References addTempThreat(), and GetThreat().
Referenced by ThreatMgr::tauntApply().
SetThreat()
void HostileReference::SetThreat (float threat) inline
{ AddThreat(threat - GetThreat()); }
References AddThreat(), and GetThreat().
sourceObjectDestroyLink()
void HostileReference::sourceObjectDestroyLink () override virtual
Implements Reference< Unit, ThreatMgr >.
{
    setOnlineOfflineState(false);
}
References setOnlineOfflineState().
targetObjectBuildLink()
void HostileReference::targetObjectBuildLink () override virtual
Implements Reference< Unit, ThreatMgr >.
{
    getTarget()->addHatedBy(this);
}
References Unit::addHatedBy(), and Reference< Unit, ThreatMgr >::getTarget().
targetObjectDestroyLink()
void HostileReference::targetObjectDestroyLink () override virtual
Implements Reference< Unit, ThreatMgr >.
{
    getTarget()->removeHatedBy(this);
}
References Reference< Unit, ThreatMgr >::getTarget(), and Unit::removeHatedBy().
updateOnlineStatus()
void HostileReference::updateOnlineStatus ()
{
    bool online = false;
    if (!isValid())
        if (Unit* target = ObjectAccessor::GetUnit(*GetSourceUnit(), getUnitGuid()))
            link(target, GetSource());
    // only check for online status if
    // ref is valid
    // target is no player or not gamemaster
    // target is not in flight
    if (isValid()
            && (!getTarget()->IsPlayer() || !getTarget()->ToPlayer()->IsGameMaster())
            && !getTarget()->IsInFlight()
            && getTarget()->IsInMap(GetSourceUnit())
            && getTarget()->InSamePhase(GetSourceUnit())
       )
    {
        Creature* creature = GetSourceUnit()->ToCreature();
        online = getTarget()->isInAccessiblePlaceFor(creature);
        if (!online)
        {
            if (creature->IsWithinCombatRange(getTarget(), creature->m_CombatDistance))
                online = true;                              // not accessible but stays online
        }
    }
    setOnlineOfflineState(online);
}
References Reference< Unit, ThreatMgr >::GetSource(), GetSourceUnit(), Reference< Unit, ThreatMgr >::getTarget(), ObjectAccessor::GetUnit(), getUnitGuid(), Unit::isInAccessiblePlaceFor(), Reference< Unit, ThreatMgr >::isValid(), Unit::IsWithinCombatRange(), Reference< Unit, ThreatMgr >::link(), Creature::m_CombatDistance, setOnlineOfflineState(), and Object::ToCreature().
Referenced by AddThreat(), and HostileRefMgr::updateThreatTables().
Member Data Documentation
iOnline
bool HostileReference::iOnline private
Referenced by HostileReference(), IsAvailable(), IsOffline(), IsOnline(), and setOnlineOfflineState().
iTempThreatModifier
float HostileReference::iTempThreatModifier private
Referenced by addTempThreat(), getTempThreatModifier(), HostileReference(), and resetTempThreat().
iThreat
float HostileReference::iThreat private
Referenced by AddThreat(), addThreatPercent(), GetThreat(), and HostileReference().
iUnitGuid
ObjectGuid HostileReference::iUnitGuid private
Referenced by getUnitGuid(), and HostileReference().