AzerothCore: npc_strangulate_vehicle::npc_strangulate_vehicleAI Struct Reference
npc_strangulate_vehicle::npc_strangulate_vehicleAI Struct Reference
Public Member Functions
npc_strangulate_vehicleAI (Creature *creature)
void IsSummonedBy (WorldObject *summoner) override
bool IsHeroic ()
void OnCharmed (bool) override
Called when unit is charmed.
void PassengerBoarded (Unit *pass, int8, bool apply) override
== Fields =======================================
void DoAction (int32 action) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap _events
InstanceScript * _instance
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_strangulate_vehicleAI()
npc_strangulate_vehicle::npc_strangulate_vehicleAI::npc_strangulate_vehicleAI (Creature * creature) inline
: NullCreatureAI(creature), _instance(creature->GetInstanceScript()) {}
Member Function Documentation
DoAction()
void npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action != ACTION_TELEPORT_BACK)
                return;
            if (TempSummon* summ = me->ToTempSummon())
            {
                if (Unit* summoner = summ->GetSummonerUnit())
                {
                    bool buff = _instance->GetBossState(DATA_THE_LICH_KING) == IN_PROGRESS && summoner->IsPlayer() && (!summoner->IsAlive() || summoner->ToPlayer()->IsBeingTeleported() || summoner->FindMap() != me->GetMap());
                    if (summoner->IsPlayer() && !summoner->ToPlayer()->IsBeingTeleported() && summoner->FindMap() == me->GetMap())
                    {
                        if (buff)
                            summoner->CastSpell((Unit*)nullptr, SPELL_HARVESTED_SOUL_LK_BUFF, true, nullptr, nullptr, _instance->GetGuidData(DATA_THE_LICH_KING));
                        me->CastSpell(summoner, SPELL_HARVEST_SOUL_TELEPORT_BACK, false);
                    }
                    else if (buff)
                        me->CastSpell((Unit*)nullptr, SPELL_HARVESTED_SOUL_LK_BUFF, true, nullptr, nullptr, _instance->GetGuidData(DATA_THE_LICH_KING));
                    summoner->RemoveAurasDueToSpell(IsHeroic() ? SPELL_HARVEST_SOULS_TELEPORT : SPELL_HARVEST_SOUL_TELEPORT);
                }
                else
                    me->CastSpell((Unit*)nullptr, SPELL_HARVESTED_SOUL_LK_BUFF, true, nullptr, nullptr, _instance->GetGuidData(DATA_THE_LICH_KING));
            }
            _events.Reset();
            me->RemoveAllAuras();
            me->DespawnOrUnsummon(500);
            if (Creature* lichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                lichKing->AI()->SummonedCreatureDespawn(me);
        }
References _events, _instance, ACTION_TELEPORT_BACK, Unit::CastSpell(), DATA_THE_LICH_KING, Creature::DespawnOrUnsummon(), InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetMap(), IN_PROGRESS, IsHeroic(), CreatureAI::me, Unit::RemoveAllAuras(), EventMap::Reset(), SPELL_HARVEST_SOUL_TELEPORT, SPELL_HARVEST_SOUL_TELEPORT_BACK, SPELL_HARVEST_SOULS_TELEPORT, SPELL_HARVESTED_SOUL_LK_BUFF, and Unit::ToTempSummon().
IsHeroic()
bool npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsHeroic () inline
{ return me->GetMap()->IsHeroic(); }
References WorldObject::GetMap(), Map::IsHeroic(), and CreatureAI::me.
Referenced by DoAction(), and UpdateAI().
IsSummonedBy()
void npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy (WorldObject * summoner) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!summoner)
                return;
            if (Creature* lichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
            {
                me->SetWalk(false);
                Movement::PointsArray path;
                path.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                path.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), 843.0f));
                me->GetMotionMaster()->MoveSplinePath(&path);
                ObjectGuid petGUID = summoner->ToUnit()->GetPetGUID();
                summoner->ToUnit()->SetPetGUID(ObjectGuid::Empty);
                summoner->ToUnit()->StopMoving();
                me->CastSpell(summoner->ToUnit(), SPELL_HARVEST_SOUL_VEHICLE, true);
                //summoner->ClearUnitState(UNIT_STATE_ONVEHICLE);
                summoner->ToUnit()->SendMovementFlagUpdate(true);
                summoner->ToUnit()->SetPetGUID(petGUID);
                _events.Reset();
                _events.ScheduleEvent(EVENT_MOVE_TO_LICH_KING, 1s);
                _events.ScheduleEvent(EVENT_TELEPORT, 6250ms);
                _events.ScheduleEvent(EVENT_DESPAWN_SELF, 76s);
                // this will let us easily access all creatures of this entry on heroic mode when its time to teleport back
                lichKing->AI()->JustSummoned(me);
            }
        }
References _events, _instance, Unit::CastSpell(), DATA_THE_LICH_KING, ObjectGuid::Empty, EVENT_DESPAWN_SELF, EVENT_MOVE_TO_LICH_KING, EVENT_TELEPORT, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Unit::GetPetGUID(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), CreatureAI::me, MotionMaster::MoveSplinePath(), EventMap::Reset(), EventMap::ScheduleEvent(), Unit::SendMovementFlagUpdate(), Unit::SetPetGUID(), Creature::SetWalk(), SPELL_HARVEST_SOUL_VEHICLE, Unit::StopMoving(), and Object::ToUnit().
OnCharmed()
void npc_strangulate_vehicle::npc_strangulate_vehicleAI::OnCharmed (bool apply) inline override virtual
Called when unit is charmed.
Reimplemented from NullCreatureAI.
{}
PassengerBoarded()
void npc_strangulate_vehicle::npc_strangulate_vehicleAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
        {
            if (!apply)
                pass->RemoveAurasDueToSpell(VEHICLE_SPELL_PARACHUTE);
        }
References Unit::RemoveAurasDueToSpell(), and VEHICLE_SPELL_PARACHUTE.
UpdateAI()
void npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
        {
            _events.Update(diff);
            switch (_events.ExecuteEvent())
            {
                case EVENT_TELEPORT:
                    me->GetMotionMaster()->Clear(false);
                    me->GetMotionMaster()->MoveIdle();
                    if (TempSummon* summ = me->ToTempSummon())
                        if (Unit* summoner = summ->GetSummonerUnit())
{
                            if (summoner->IsAlive() && summoner->IsPlayer())
{
                                summoner->CastSpell((Unit*)nullptr, SPELL_HARVEST_SOUL_VISUAL, true);
                                summoner->ExitVehicle(summoner);
                                me->UpdatePosition(me->GetPositionX(), me->GetPositionY(), 840.87f, me->GetOrientation(), true);
                                me->StopMovingOnCurrentPos();
                                if (!IsHeroic())
                                    summoner->CastSpell(summoner, SPELL_HARVEST_SOUL_TELEPORT, true);
                                else
                                    summoner->CastSpell(summoner, SPELL_HARVEST_SOULS_TELEPORT, true);
                            }
                            else
{
                                summoner->ExitVehicle(summoner);
                                _events.RescheduleEvent(EVENT_DESPAWN_SELF, 0ms);
                            }
                        }
                    break;
                case EVENT_MOVE_TO_LICH_KING:
                    if (Creature* lichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                        if (me->GetExactDist(lichKing) > 8.0f)
{
                            float dist = float(rand_norm()) * 5.0f + 8.0f;
                            float angle = lichKing->GetAngle(me);
                            Movement::PointsArray path;
                            path.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                            path.push_back(G3D::Vector3(lichKing->GetPositionX() + dist * cos(angle), lichKing->GetPositionY() + dist * std::sin(angle), 843.0f));
                            me->GetMotionMaster()->MoveSplinePath(&path);
                        }
                    break;
                case EVENT_DESPAWN_SELF:
                    if (Creature* lichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                        lichKing->AI()->SummonedCreatureDespawn(me);
                    me->DespawnOrUnsummon(1);
                    break;
                default:
                    break;
            }
        }
References _events, _instance, MotionMaster::Clear(), DATA_THE_LICH_KING, Creature::DespawnOrUnsummon(), EVENT_DESPAWN_SELF, EVENT_MOVE_TO_LICH_KING, EVENT_TELEPORT, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), Position::GetExactDist(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), IsHeroic(), CreatureAI::me, MotionMaster::MoveIdle(), MotionMaster::MoveSplinePath(), rand_norm(), EventMap::RescheduleEvent(), SPELL_HARVEST_SOUL_TELEPORT, SPELL_HARVEST_SOUL_VISUAL, SPELL_HARVEST_SOULS_TELEPORT, Unit::StopMovingOnCurrentPos(), Unit::ToTempSummon(), EventMap::Update(), and Unit::UpdatePosition().
Member Data Documentation
_events
EventMap npc_strangulate_vehicle::npc_strangulate_vehicleAI::_events
Referenced by DoAction(), IsSummonedBy(), and UpdateAI().
_instance
InstanceScript* npc_strangulate_vehicle::npc_strangulate_vehicleAI::_instance
Referenced by DoAction(), IsSummonedBy(), and UpdateAI().