AzeorthCore: go_inconspicuous_landmark Class Reference
go_inconspicuous_landmark Class Reference
Public Member Functions
go_inconspicuous_landmark ()
bool OnGossipHello (Player *player, GameObject *) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, GameObject *)
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Private Attributes
uint32 _lastUsedTime
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
go_inconspicuous_landmark()
go_inconspicuous_landmark::go_inconspicuous_landmark () inline
                                : GameObjectScript("go_inconspicuous_landmark")
    {
        _lastUsedTime = GameTime::GetGameTime().count();
    }
References _lastUsedTime, and GameTime::GetGameTime().
Member Function Documentation
OnGossipHello()
bool go_inconspicuous_landmark::OnGossipHello (Player * player, GameObject *) inline override virtual
Reimplemented from GameObjectScript.
    {
        if (player->HasItemCount(ITEM_CUERGOS_KEY))
            return true;
        if (_lastUsedTime > GameTime::GetGameTime().count())
            return true;
        _lastUsedTime = GameTime::GetGameTime().count() + MINUTE;
        player->CastSpell(player, SPELL_SUMMON_PIRATES_TREASURE_AND_TRIGGER_MOB, true);
        return true;
    }
References _lastUsedTime, Unit::CastSpell(), GameTime::GetGameTime(), Player::HasItemCount(), ITEM_CUERGOS_KEY, MINUTE, and SPELL_SUMMON_PIRATES_TREASURE_AND_TRIGGER_MOB.
Member Data Documentation
_lastUsedTime
uint32 go_inconspicuous_landmark::_lastUsedTime private
Referenced by go_inconspicuous_landmark(), and OnGossipHello().