AzerothCore: SQLQueryHolderBase Class Reference
SQLQueryHolderBase Class Reference
#include "QueryHolder.h"
Public Member Functions
SQLQueryHolderBase ()=default
virtual ~SQLQueryHolderBase ()
void SetSize (std::size_t size)
PreparedQueryResult GetPreparedResult (std::size_t index) const
void SetPreparedResult (std::size_t index, PreparedResultSet *result)
Protected Member Functions
bool SetPreparedQueryImpl (std::size_t index, PreparedStatementBase *stmt)
Private Attributes
std::vector< std::pair< PreparedStatementBase *, PreparedQueryResult > > m_queries
Friends
class SQLQueryHolderTask
Detailed Description
Constructor & Destructor Documentation
SQLQueryHolderBase()
SQLQueryHolderBase::SQLQueryHolderBase () default
~SQLQueryHolderBase()
SQLQueryHolderBase::~SQLQueryHolderBase () virtual
if the result was never used, free the resources results used already (getresult called) are expected to be deleted
{
    for (std::pair<PreparedStatementBase*, PreparedQueryResult>& query : m_queries)
    {
        delete query.first;
    }
}
References m_queries.
Member Function Documentation
GetPreparedResult()
PreparedQueryResult SQLQueryHolderBase::GetPreparedResult (std::size_t index) const
{
    // Don't call to this function if the index is of a prepared statement
    ASSERT(index < m_queries.size(), "Query holder result index out of range, tried to access index {} but there are only {} results",
        index, m_queries.size());
    return m_queries[index].second;
}
References ASSERT, and m_queries.
Referenced by WorldSession::HandlePlayerLoginFromDB(), WorldSession::InitializeSessionCallback(), Player::LoadFromDB(), and Pet::LoadPetFromDB().
SetPreparedQueryImpl()
bool SQLQueryHolderBase::SetPreparedQueryImpl (std::size_t index, PreparedStatementBase * stmt) protected
{
    if (m_queries.size() <= index)
    {
        LOG_ERROR("sql.sql", "Query index ({}) out of range (size: {}) for prepared statement", uint32(index), (uint32)m_queries.size());
        return false;
    }
    m_queries[index].first = stmt;
    return true;
}
References LOG_ERROR, and m_queries.
Referenced by SQLQueryHolder< T >::SetPreparedQuery().
SetPreparedResult()
void SQLQueryHolderBase::SetPreparedResult (std::size_t index, PreparedResultSet * result)
store the result in the holder
{
    if (result && !result->GetRowCount())
    {
        delete result;
        result = nullptr;
    }
    if (index < m_queries.size())
        m_queries[index].second = PreparedQueryResult(result);
}
References PreparedResultSet::GetRowCount(), and m_queries.
SetSize()
void SQLQueryHolderBase::SetSize (std::size_t size)
to optimize push_back, reserve the number of queries about to be executed
{
    m_queries.resize(size);
}
References m_queries.
Referenced by LoginQueryHolder::Initialize(), and PetLoadQueryHolder::PetLoadQueryHolder().
Friends And Related Function Documentation
SQLQueryHolderTask
friend class SQLQueryHolderTask friend
Member Data Documentation
m_queries
std::vector<std::pair<PreparedStatementBase*, PreparedQueryResult> > SQLQueryHolderBase::m_queries private
Referenced by GetPreparedResult(), SetPreparedQueryImpl(), SetPreparedResult(), SetSize(), and ~SQLQueryHolderBase().