AzerothCore: spell_vehicle_throw_passenger Class Reference
spell_vehicle_throw_passenger Class Reference
Private Member Functions
PrepareSpellScript (spell_vehicle_throw_passenger)
void HandleScript ()
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleScript()
void spell_vehicle_throw_passenger::HandleScript () inline private
    {
        Spell* baseSpell = GetSpell();
        SpellCastTargets targets = baseSpell->m_targets;
        if (Vehicle* vehicle = GetCaster()->GetVehicleKit())
            if (Unit* passenger = vehicle->GetPassenger(3))
            {
                // use 99 because it is 3d search
                std::list<WorldObject*> targetList;
                Acore::WorldObjectSpellAreaTargetCheck check(99, GetExplTargetDest(), GetCaster(), GetCaster(), GetSpellInfo(), TARGET_CHECK_DEFAULT, nullptr);
                Acore::WorldObjectListSearcher<Acore::WorldObjectSpellAreaTargetCheck> searcher(GetCaster(), targetList, check);
                Cell::VisitAllObjects(GetCaster(), searcher, 99.0f);
                float minDist = 99 * 99;
                Unit* target = nullptr;
                for (std::list<WorldObject*>::iterator itr = targetList.begin(); itr != targetList.end(); ++itr)
                {
                    if (Unit* unit = (*itr)->ToUnit())
                        if (unit->GetEntry() == NPC_SEAT)
                            if (Vehicle* seat = unit->GetVehicleKit())
                                if (!seat->GetPassenger(0))
                                    if (Unit* device = seat->GetPassenger(2))
                                        if (!device->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
{
                                            float dist = unit->GetExactDistSq(targets.GetDstPos());
                                            if (dist < minDist)
{
                                                minDist = dist;
                                                target = unit;
                                            }
                                        }
                }
                if (target && target->IsWithinDist2d(targets.GetDstPos(), GetSpellInfo()->Effects[EFFECT_0].CalcRadius() * 2)) // now we use *2 because the location of the seat is not correct
                {
                    passenger->ExitVehicle();
                    passenger->EnterVehicle(target, 0);
                }
                else
                {
                    passenger->ExitVehicle();
                    float x, y, z;
                    targets.GetDstPos()->GetPosition(x, y, z);
                    passenger->GetMotionMaster()->MoveJump(x, y, z, targets.GetSpeedXY(), targets.GetSpeedZ());
                }
            }
    }
References CURRENT_CHANNELED_SPELL, EFFECT_0, Unit::ExitVehicle(), SpellCastTargets::GetDstPos(), Position::GetExactDistSq(), Position::GetPosition(), SpellCastTargets::GetSpeedXY(), SpellCastTargets::GetSpeedZ(), WorldObject::IsWithinDist2d(), Spell::m_targets, NPC_SEAT, TARGET_CHECK_DEFAULT, Object::ToUnit(), and Cell::VisitAllObjects().
Referenced by Register().
PrepareSpellScript()
spell_vehicle_throw_passenger::PrepareSpellScript (spell_vehicle_throw_passenger) private
Register()
void spell_vehicle_throw_passenger::Register () inline override private virtual
Implements _SpellScript.
    {
        AfterCast += SpellCastFn(spell_vehicle_throw_passenger::HandleScript);
    }
References HandleScript(), and SpellCastFn.