AzerothCore: npc_finklestein Class Reference
npc_finklestein Class Reference
Classes
struct npc_finklesteinAI
Public Member Functions
npc_finklestein ()
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest) override
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_finklestein()
npc_finklestein::npc_finklestein () inline
: CreatureScript("npc_finklestein") { }
Member Function Documentation
GetAI()
CreatureAI * npc_finklestein::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return new npc_finklesteinAI(creature);
    }
OnGossipHello()
bool npc_finklestein::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (creature->IsQuestGiver())
            player->PrepareQuestMenu(creature->GetGUID());
        SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
        if (player->GetQuestStatus(QUEST_ALCHEMIST_APPRENTICE) == QUEST_STATUS_INCOMPLETE)
        {
            if (creature->AI() && CAST_AI(npc_finklestein::npc_finklesteinAI, creature->AI()))
                if (!CAST_AI(npc_finklestein::npc_finklesteinAI, creature->AI())->IsPlayerOnTask(player->GetGUID()))
                    AddGossipItemFor(player, GOSSIP_ICON_CHAT, "I'm ready to begin. What is the first ingredient you require?", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
            SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
        }
        return true;
    }
References AddGossipItemFor(), Creature::AI(), CAST_AI, Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Unit::IsQuestGiver(), Player::PrepareQuestMenu(), QUEST_ALCHEMIST_APPRENTICE, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_finklestein::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
    {
        CloseGossipMenuFor(player);
        if (uiAction == GOSSIP_ACTION_INFO_DEF + 1)
        {
            CloseGossipMenuFor(player);
            if (creature->AI() && CAST_AI(npc_finklestein::npc_finklesteinAI, creature->AI()))
                CAST_AI(npc_finklestein::npc_finklesteinAI, creature->AI())->StartNextTask(player->GetGUID(), 1);
        }
        return true;
    }
References Creature::AI(), CAST_AI, CloseGossipMenuFor(), Object::GetGUID(), and GOSSIP_ACTION_INFO_DEF.
OnQuestAccept()
bool npc_finklestein::OnQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
    {
        if (quest->GetQuestId() == QUEST_ALCHEMIST_APPRENTICE)
            if (creature->AI() && CAST_AI(npc_finklestein::npc_finklesteinAI, creature->AI()))
                CAST_AI(npc_finklestein::npc_finklesteinAI, creature->AI())->ClearPlayerOnTask(player->GetGUID());
        return true;
    }
References Creature::AI(), CAST_AI, Object::GetGUID(), Quest::GetQuestId(), and QUEST_ALCHEMIST_APPRENTICE.