AzeorthCore: socrethar::socretharAI Struct Reference
socrethar::socretharAI Struct Reference
Public Member Functions
socretharAI (Creature *creature)
bool GetCreature (uint32 CreatureID)
void Reset () override
void DoAction (int32 param) override
void JustDied (Unit *) override
void EnterCombat (Unit *) override
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap _actionEvents
EventMap combatEvents
bool DeathblowToTheLegionRunning = false
Creature * adyen
Creature * orelis
Creature * karja
Creature * kaylaan
Creature * ishanah
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
socretharAI()
socrethar::socretharAI::socretharAI (Creature * creature) inline
                                        : ScriptedAI(creature),
            adyen(nullptr), orelis(nullptr), karja(nullptr), kaylaan(nullptr), ishanah(nullptr) { }
Member Function Documentation
DamageTaken()
void socrethar::socretharAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
        {
            me->SetReactState(REACT_AGGRESSIVE);
        }
References ScriptedAI::me, REACT_AGGRESSIVE, and Creature::SetReactState().
DoAction()
void socrethar::socretharAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            switch (param)
            {
                case EVENT_ADYEN_SAY_1:
                    DeathblowToTheLegionRunning = true;
                    _actionEvents.ScheduleEvent(EVENT_ADYEN_SAY_1, 1000);
                    break;
                case EVENT_ADYEN_SAY_3:
                    _actionEvents.ScheduleEvent(EVENT_ADYEN_SAY_3, 2000);
                    break;
                case EVENT_KAYLAAN_SAY_1:
                    _actionEvents.ScheduleEvent(EVENT_KAYLAAN_SAY_1, 4000);
                    break;
                case EVENT_END_ALDOR_FIGHT:
                    _actionEvents.ScheduleEvent(EVENT_END_ALDOR_FIGHT, 1);
                    break;
                case EVENT_ISHANAH_SAY_1:
                    _actionEvents.ScheduleEvent(EVENT_ISHANAH_SAY_1, 2000);
                    break;
                case RESET_DEATHBLOW_EVENT:
                    DeathblowToTheLegionRunning = false;
                    Reset();
                    break;
            }
        }
References _actionEvents, DeathblowToTheLegionRunning, EVENT_ADYEN_SAY_1, EVENT_ADYEN_SAY_3, EVENT_END_ALDOR_FIGHT, EVENT_ISHANAH_SAY_1, EVENT_KAYLAAN_SAY_1, Reset(), RESET_DEATHBLOW_EVENT, and EventMap::ScheduleEvent().
EnterCombat()
void socrethar::socretharAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            combatEvents.ScheduleEvent(EVENT_SPELL_ANTI_MAGIC_SHIELD, 20000);
            combatEvents.ScheduleEvent(EVENT_SPELL_BACKLASH, 4000);
            combatEvents.ScheduleEvent(EVENT_SPELL_CLEAVE, 2000);
            combatEvents.ScheduleEvent(EVENT_SPELL_FIREBALL_BARRAGE, 9000);
            combatEvents.ScheduleEvent(EVENT_SPELL_SHADOW_BOLT_VOLLEY, 5000);
            combatEvents.ScheduleEvent(EVENT_SPELL_NETHER_PROTECTION, 1);
        }
References combatEvents, EVENT_SPELL_ANTI_MAGIC_SHIELD, EVENT_SPELL_BACKLASH, EVENT_SPELL_CLEAVE, EVENT_SPELL_FIREBALL_BARRAGE, EVENT_SPELL_NETHER_PROTECTION, EVENT_SPELL_SHADOW_BOLT_VOLLEY, and EventMap::ScheduleEvent().
GetCreature()
bool socrethar::socretharAI::GetCreature (uint32 CreatureID) inline
        {
            switch (CreatureID)
            {
                case ADYEN_THE_LIGHTBRINGER:
                    adyen = me->FindNearestCreature(ADYEN_THE_LIGHTBRINGER, 100.0f, true);
                    if (adyen)
                        return true;
                    break;
                case EXARCH_ORELIS:
                    orelis = me->FindNearestCreature(EXARCH_ORELIS, 100.0f, true);
                    if (orelis)
                        return true;
                    break;
                case ANCHORITE_KARJA:
                    karja = me->FindNearestCreature(ANCHORITE_KARJA, 100.0f, true);
                    if (karja)
                        return true;
                    break;
                case KAYLAAN_THE_LOST:
                    kaylaan = me->FindNearestCreature(KAYLAAN_THE_LOST, 100.0f, true);
                    if (kaylaan)
                        return true;
                    break;
                case ISHANAH_HIGH_PRIESTESS:
                    ishanah = me->FindNearestCreature(ISHANAH_HIGH_PRIESTESS, 100.0f, true);
                    if (!ishanah)
                    {
                        // Ishanah may be dead; in this case we also need a reference to the creature for the respawn
                        ishanah = me->FindNearestCreature(ISHANAH_HIGH_PRIESTESS, 100.0f, false);
                        if (ishanah)
                            return true;
                    }
                    else
                        return true;
                    break;
            }
            return false; // When he doesn't find anyone
        }
References adyen, ADYEN_THE_LIGHTBRINGER, ANCHORITE_KARJA, EXARCH_ORELIS, WorldObject::FindNearestCreature(), ishanah, ISHANAH_HIGH_PRIESTESS, karja, kaylaan, KAYLAAN_THE_LOST, ScriptedAI::me, and orelis.
Referenced by JustDied(), and UpdateAI().
JustDied()
void socrethar::socretharAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            DoCast(me, SOCRETHAR_QUEST_CREDIT);
            if (GetCreature(ISHANAH_HIGH_PRIESTESS))
            {
                ishanah->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                ishanah->DespawnOrUnsummon(60000);
            }
            if (GetCreature(ADYEN_THE_LIGHTBRINGER))
                adyen->GetAI()->DoAction(RESET_DEATHBLOW_EVENT);
            if (GetCreature(EXARCH_ORELIS))
                orelis->GetAI()->DoAction(RESET_DEATHBLOW_EVENT);
            if (GetCreature(ANCHORITE_KARJA))
                karja->GetAI()->DoAction(RESET_DEATHBLOW_EVENT);
        }
References adyen, ADYEN_THE_LIGHTBRINGER, ANCHORITE_KARJA, Creature::DespawnOrUnsummon(), UnitAI::DoAction(), UnitAI::DoCast(), EXARCH_ORELIS, Unit::GetAI(), GetCreature(), ishanah, ISHANAH_HIGH_PRIESTESS, karja, ScriptedAI::me, orelis, RESET_DEATHBLOW_EVENT, Unit::SetNpcFlag(), SOCRETHAR_QUEST_CREDIT, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAG_QUESTGIVER.
Reset()
void socrethar::socretharAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            me->SetReactState(REACT_PASSIVE);
            me->SetFaction(FACTION_DEMON);
        }
References FACTION_DEMON, ScriptedAI::me, REACT_PASSIVE, Unit::SetFaction(), and Creature::SetReactState().
Referenced by DoAction().
UpdateAI()
void socrethar::socretharAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (DeathblowToTheLegionRunning)
            {
                _actionEvents.Update(diff);
                switch (_actionEvents.ExecuteEvent())
                {
                    case EVENT_ADYEN_SAY_1:
                        if (GetCreature(ADYEN_THE_LIGHTBRINGER))
                            adyen->AI()->Talk(0);
                        _actionEvents.ScheduleEvent(EVENT_SOCRETHAR_SAY_1, 11000);
                        break;
                    case EVENT_SOCRETHAR_SAY_1:
                        Talk(0);
                        _actionEvents.ScheduleEvent(EVENT_ADYEN_SAY_2, 7000);
                        break;
                    case EVENT_ADYEN_SAY_2:
                        if (GetCreature(ADYEN_THE_LIGHTBRINGER))
                            adyen->AI()->Talk(1);
                        _actionEvents.ScheduleEvent(EVENT_SOCRETHAR_SAY_2, 11000);
                        break;
                    case EVENT_SOCRETHAR_SAY_2:
                        Talk(1);
                        if (Creature* summonKaylaan = me->SummonCreature(KAYLAAN_THE_LOST, KaylaanSpawnPosition, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 240000))
                            summonKaylaan->GetMotionMaster()->MovePath(KAYLAAN_PATH_ID1, false);
                        break;
                    case EVENT_ADYEN_SAY_3:
                        if (GetCreature(ADYEN_THE_LIGHTBRINGER))
                            adyen->AI()->Talk(2);
                        if (GetCreature(KAYLAAN_THE_LOST))
                            kaylaan->SetStandState(UNIT_STAND_STATE_STAND);
                        _actionEvents.ScheduleEvent(EVENT_KAYLAAN_WALK_TO_ADYEN, 3500);
                        break;
                    case EVENT_KAYLAAN_WALK_TO_ADYEN:
                        if (GetCreature(KAYLAAN_THE_LOST))
                            kaylaan->GetMotionMaster()->MovePath(KAYLAAN_PATH_ID2, false);
                        break;
                    case EVENT_KAYLAAN_SAY_1:
                        if (GetCreature(KAYLAAN_THE_LOST))
{
                            kaylaan->AI()->Talk(0);
                            kaylaan->SetHomePosition(kaylaan->GetPosition());
                        }
                        _actionEvents.ScheduleEvent(EVENT_KAYLAAN_SAY_2, 9000);
                        break;
                    case EVENT_KAYLAAN_SAY_2:
                        if (GetCreature(KAYLAAN_THE_LOST))
                            kaylaan->AI()->Talk(1);
                        _actionEvents.ScheduleEvent(EVENT_KAYLAAN_SAY_3, 8000);
                        break;
                    case EVENT_KAYLAAN_SAY_3:
                        if (GetCreature(KAYLAAN_THE_LOST))
                            kaylaan->AI()->Talk(2);
                        _actionEvents.ScheduleEvent(EVENT_ADYEN_SAY_4, 8000);
                        break;
                    case EVENT_ADYEN_SAY_4:
                        if (GetCreature(ADYEN_THE_LIGHTBRINGER))
                            adyen->AI()->Talk(3);
                        _actionEvents.ScheduleEvent(EVENT_KAYLAAN_SAY_4, 11000);
                        break;
                    case EVENT_KAYLAAN_SAY_4:
                        if (GetCreature(KAYLAAN_THE_LOST))
                            kaylaan->AI()->Talk(3);
                        _actionEvents.ScheduleEvent(EVENT_SPELL_POWER_OF_THE_LEGION, 5000);
                        break;
                    case EVENT_SPELL_POWER_OF_THE_LEGION:
                        if (GetCreature(KAYLAAN_THE_LOST))
                            me->CastSpell(kaylaan, POWER_OF_THE_LEGION, false);
                        Talk(2);
                        _actionEvents.ScheduleEvent(EVENT_FIGHT_ALDOR, 3000);
                        break;
                    case EVENT_FIGHT_ALDOR:
                        if (GetCreature(KAYLAAN_THE_LOST))
{
                            kaylaan->SetFaction(FACTION_DEMON);
                            if (GetCreature(ADYEN_THE_LIGHTBRINGER))
                                kaylaan->AI()->AttackStart(adyen);
                        }
                        break;
                    case EVENT_END_ALDOR_FIGHT:
                        if (GetCreature(KAYLAAN_THE_LOST))
{
                            kaylaan->SetFaction(FACTION_DEMON);
                            kaylaan->GetMotionMaster()->MoveTargetedHome();
                            kaylaan->CombatStop();
                            kaylaan->ClearInCombat();
                        }
                        if (GetCreature(ADYEN_THE_LIGHTBRINGER))
{
                            adyen->GetMotionMaster()->MoveTargetedHome();
                            adyen->CombatStop();
                            adyen->ClearInCombat();
                        }
                        if (GetCreature(EXARCH_ORELIS))
{
                            orelis->GetMotionMaster()->MoveTargetedHome();
                            orelis->CombatStop();
                            orelis->ClearInCombat();
                        }
                        if (GetCreature(ANCHORITE_KARJA))
{
                            karja->GetMotionMaster()->MoveTargetedHome();
                            karja->CombatStop();
                            karja->ClearInCombat();
                        }
                        _actionEvents.ScheduleEvent(EVENT_SOCRETHAR_SAY_4, 2000);
                        break;
                    case EVENT_SOCRETHAR_SAY_4:
                        Talk(3);
                        _actionEvents.ScheduleEvent(EVENT_KAYLAAN_SAY_5, 8000);
                        break;
                    case EVENT_KAYLAAN_SAY_5:
                        if (GetCreature(KAYLAAN_THE_LOST))
                            kaylaan->AI()->Talk(4);
                        if (Creature* summonIshanah = me->SummonCreature(ISHANAH_HIGH_PRIESTESS, IshanahSpawnPosition, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 180000))
{
                            summonIshanah->GetMotionMaster()->MovePath(ISHANAH_PATH_ID, false);
                            summonIshanah->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                        }
                        break;
                    case EVENT_ISHANAH_SAY_1:
                        if (GetCreature(ISHANAH_HIGH_PRIESTESS))
                            ishanah->AI()->Talk(0);
                        if (GetCreature(KAYLAAN_THE_LOST))
{
                            kaylaan->RemoveAurasDueToSpell(POWER_OF_THE_LEGION);
                            kaylaan->SetStandState(UNIT_STAND_STATE_KNEEL);
                        }
                        _actionEvents.ScheduleEvent(EVENT_ISHANAH_SAY_2, 6000);
                        break;
                    case EVENT_ISHANAH_SAY_2:
                        if (GetCreature(ISHANAH_HIGH_PRIESTESS))
                            ishanah->AI()->Talk(1);
                        _actionEvents.ScheduleEvent(EVENT_SOCRETHAR_SAY_5, 8000);
                        break;
                    case EVENT_SOCRETHAR_SAY_5:
                        Talk(4);
                        _actionEvents.ScheduleEvent(EVENT_KILL_ISHANAH, 4000);
                        break;
                    case EVENT_KILL_ISHANAH:
                        if (GetCreature(ISHANAH_HIGH_PRIESTESS))
                            me->CastSpell(ishanah, WRATH_OF_SOCRETHAR);
                        _actionEvents.ScheduleEvent(EVENT_ISHANAH_DIES, 1500);
                        break;
                    case EVENT_ISHANAH_DIES:
                        if (GetCreature(ISHANAH_HIGH_PRIESTESS))
                            me->Kill(me, ishanah);
                        _actionEvents.ScheduleEvent(EVENT_KAYLAAN_SAY_6, 4000);
                        break;
                    case EVENT_KAYLAAN_SAY_6:
                        if (GetCreature(KAYLAAN_THE_LOST))
{
                            kaylaan->AI()->Talk(6);
                            kaylaan->SetStandState(UNIT_STAND_STATE_STAND);
                            kaylaan->GetMotionMaster()->MovePath(207942, false);
                        }
                        _actionEvents.ScheduleEvent(EVENT_KAYLAAN_SAY_7, 9000);
                        break;
                    case EVENT_KAYLAAN_SAY_7:
                        if (GetCreature(KAYLAAN_THE_LOST))
{
                            kaylaan->AI()->Talk(7);
                            kaylaan->CastSpell(kaylaan, DIVINE_SHIELD);
                        }
                        _actionEvents.ScheduleEvent(EVENT_KAYLAAN_RESSURECTION, 1000);
                        break;
                    case EVENT_KAYLAAN_RESSURECTION:
                        if (GetCreature(KAYLAAN_THE_LOST))
                            kaylaan->CastSpell(ishanah, REDEMPTION);
                        _actionEvents.ScheduleEvent(EVENT_ISHANAH_IS_BACK_AGAIN, 11000);
                        break;
                    case EVENT_ISHANAH_IS_BACK_AGAIN:
                        if (GetCreature(ISHANAH_HIGH_PRIESTESS))
{
                            ishanah->Respawn();
                            ishanah->setActive(true); // ensure that Ishanah disappears, even when no player is near
                            ishanah->DespawnOrUnsummon(600000); // ensure that Ishanah disappears after 10 minutes
                            ishanah->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                        }
                        _actionEvents.ScheduleEvent(EVENT_SOCRETHAR_SAY_6, 3000);
                        break;
                    case EVENT_SOCRETHAR_SAY_6:
                        Talk(5);
                        _actionEvents.ScheduleEvent(EVENT_KILL_KAYLAAN, 4000);
                        break;
                    case EVENT_KILL_KAYLAAN:
                        if (GetCreature(KAYLAAN_THE_LOST))
                            me->CastSpell(kaylaan, WRATH_OF_SOCRETHAR);
                        _actionEvents.ScheduleEvent(EVENT_KAYLAAN_DIES, 1500);
                        break;
                    case EVENT_KAYLAAN_DIES:
                        if (GetCreature(KAYLAAN_THE_LOST))
                            me->Kill(me, kaylaan);
                        _actionEvents.ScheduleEvent(EVENT_FINAL_FIGHT, 3000);
                        break;
                    case EVENT_FINAL_FIGHT:
                        // Prepare Socrethar for encounter
                        me->SetFaction(FACTION_DEMON);
                        me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_DISABLE_MOVE);
                        me->SetReactState(REACT_AGGRESSIVE);
                        // Engage combat with Socrethar
                        if (GetCreature(ADYEN_THE_LIGHTBRINGER))
                            adyen->AI()->EnterCombat(me);
                        if (GetCreature(EXARCH_ORELIS))
                            orelis->AI()->EnterCombat(me);
                        if (GetCreature(ANCHORITE_KARJA))
                            karja->AI()->EnterCombat(me);
                        if (GetCreature(ISHANAH_HIGH_PRIESTESS))
                            ishanah->AI()->EnterCombat(me);
                        break;
                }
            }
            if (!UpdateVictim())
                return;
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            combatEvents.Update(diff);
            switch (combatEvents.ExecuteEvent())
            {
                case EVENT_SPELL_NETHER_PROTECTION:
                    if (!me->HasAura(NETHER_PROTECTION))
                        me->CastSpell(me, NETHER_PROTECTION, false);
                    break;
                case EVENT_SPELL_ANTI_MAGIC_SHIELD:
                    me->CastSpell(me, ANTI_MAGIC_SHIELD, false);
                    combatEvents.ScheduleEvent(EVENT_SPELL_ANTI_MAGIC_SHIELD, 20000);
                    break;
                case EVENT_SPELL_BACKLASH:
                    DoCastVictim(BACKLASH);
                    combatEvents.ScheduleEvent(EVENT_SPELL_BACKLASH, 7000);
                    break;
                case EVENT_SPELL_CLEAVE:
                    me->CastSpell(me->GetVictim(), CLEAVE, false);
                    combatEvents.ScheduleEvent(EVENT_SPELL_CLEAVE, 3000);
                    break;
                case EVENT_SPELL_FIREBALL_BARRAGE:
                    me->CastSpell(me->GetVictim(), FIREBALL_BARRAGE, false);
                    combatEvents.ScheduleEvent(EVENT_SPELL_FIREBALL_BARRAGE, 15000);
                    break;
                case EVENT_SPELL_SHADOW_BOLT_VOLLEY:
                    me->CastSpell(me->GetVictim(), SHADOW_BOLT_VOLLEY, false);
                    combatEvents.ScheduleEvent(EVENT_SPELL_SHADOW_BOLT_VOLLEY, 10000);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References _actionEvents, adyen, ADYEN_THE_LIGHTBRINGER, Creature::AI(), ANCHORITE_KARJA, ANTI_MAGIC_SHIELD, UnitAI::AttackStart(), BACKLASH, Unit::CastSpell(), Unit::ClearInCombat(), CLEAVE, combatEvents, Unit::CombatStop(), DeathblowToTheLegionRunning, Creature::DespawnOrUnsummon(), DIVINE_SHIELD, UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), CreatureAI::EnterCombat(), EVENT_ADYEN_SAY_1, EVENT_ADYEN_SAY_2, EVENT_ADYEN_SAY_3, EVENT_ADYEN_SAY_4, EVENT_END_ALDOR_FIGHT, EVENT_FIGHT_ALDOR, EVENT_FINAL_FIGHT, EVENT_ISHANAH_DIES, EVENT_ISHANAH_IS_BACK_AGAIN, EVENT_ISHANAH_SAY_1, EVENT_ISHANAH_SAY_2, EVENT_KAYLAAN_DIES, EVENT_KAYLAAN_RESSURECTION, EVENT_KAYLAAN_SAY_1, EVENT_KAYLAAN_SAY_2, EVENT_KAYLAAN_SAY_3, EVENT_KAYLAAN_SAY_4, EVENT_KAYLAAN_SAY_5, EVENT_KAYLAAN_SAY_6, EVENT_KAYLAAN_SAY_7, EVENT_KAYLAAN_WALK_TO_ADYEN, EVENT_KILL_ISHANAH, EVENT_KILL_KAYLAAN, EVENT_SOCRETHAR_SAY_1, EVENT_SOCRETHAR_SAY_2, EVENT_SOCRETHAR_SAY_4, EVENT_SOCRETHAR_SAY_5, EVENT_SOCRETHAR_SAY_6, EVENT_SPELL_ANTI_MAGIC_SHIELD, EVENT_SPELL_BACKLASH, EVENT_SPELL_CLEAVE, EVENT_SPELL_FIREBALL_BARRAGE, EVENT_SPELL_NETHER_PROTECTION, EVENT_SPELL_POWER_OF_THE_LEGION, EVENT_SPELL_SHADOW_BOLT_VOLLEY, EXARCH_ORELIS, EventMap::ExecuteEvent(), FACTION_DEMON, FIREBALL_BARRAGE, GetCreature(), Unit::GetMotionMaster(), Position::GetPosition(), Unit::GetVictim(), Unit::HasAura(), Unit::HasUnitState(), ishanah, ISHANAH_HIGH_PRIESTESS, ISHANAH_PATH_ID, IshanahSpawnPosition, karja, kaylaan, KAYLAAN_PATH_ID1, KAYLAAN_PATH_ID2, KAYLAAN_THE_LOST, KaylaanSpawnPosition, Unit::Kill(), ScriptedAI::me, MotionMaster::MovePath(), MotionMaster::MoveTargetedHome(), NETHER_PROTECTION, orelis, POWER_OF_THE_LEGION, REACT_AGGRESSIVE, REDEMPTION, Unit::RemoveAurasDueToSpell(), Unit::RemoveNpcFlag(), Unit::RemoveUnitFlag(), Creature::Respawn(), EventMap::ScheduleEvent(), WorldObject::setActive(), Unit::SetFaction(), Creature::SetHomePosition(), Creature::SetReactState(), Unit::SetStandState(), SHADOW_BOLT_VOLLEY, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_STAND, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and WRATH_OF_SOCRETHAR.
Member Data Documentation
_actionEvents
EventMap socrethar::socretharAI::_actionEvents
Referenced by DoAction(), and UpdateAI().
adyen
Creature* socrethar::socretharAI::adyen
Referenced by GetCreature(), JustDied(), and UpdateAI().
combatEvents
EventMap socrethar::socretharAI::combatEvents
Referenced by EnterCombat(), and UpdateAI().
DeathblowToTheLegionRunning
bool socrethar::socretharAI::DeathblowToTheLegionRunning = false
Referenced by DoAction(), and UpdateAI().
ishanah
Creature * socrethar::socretharAI::ishanah
Referenced by GetCreature(), JustDied(), and UpdateAI().
karja
Creature * socrethar::socretharAI::karja
Referenced by GetCreature(), JustDied(), and UpdateAI().
kaylaan
Creature * socrethar::socretharAI::kaylaan
Referenced by GetCreature(), and UpdateAI().
orelis
Creature * socrethar::socretharAI::orelis
Referenced by GetCreature(), JustDied(), and UpdateAI().