AzerothCore: Acore::Impl::CryptoGenericsImpl Struct Reference
Acore::Impl::CryptoGenericsImpl Struct Reference
#include "CryptoGenerics.h"
Static Public Member Functions
template<typename Cipher >
static Cipher::IV GenerateRandomIV ()
template<typename Container >
static void AppendToBack (std::vector< uint8 > &data, Container const &tail)
template<typename Container >
static void SplitFromBack (std::vector< uint8 > &data, Container &tail)
Detailed Description
Member Function Documentation
AppendToBack()
template<typename Container > static void Acore::Impl::CryptoGenericsImpl::AppendToBack (std::vector< uint8 > & data, Container const & tail) inline static
        {
            data.insert(data.end(), std::begin(tail), std::end(tail));
        }
Referenced by Acore::Crypto::AEEncryptWithRandomIV().
GenerateRandomIV()
template<typename Cipher > static Cipher::IV Acore::Impl::CryptoGenericsImpl::GenerateRandomIV () inline static
        {
            typename Cipher::IV iv;
            Acore::Crypto::GetRandomBytes(iv);
            return iv;
        }
References Acore::Crypto::GetRandomBytes().
SplitFromBack()
template<typename Container > static void Acore::Impl::CryptoGenericsImpl::SplitFromBack (std::vector< uint8 > & data, Container & tail) inline static
        {
            ASSERT(data.size() >= std::size(tail));
            for (std::size_t i = 1, N = std::size(tail); i <= N; ++i)
            {
                tail[N - i] = data.back();
                data.pop_back();
            }
        }
References ASSERT.
Referenced by Acore::Crypto::AEDecrypt().