AzerothCore: AssistanceDistractMovementGenerator Class Reference
AssistanceDistractMovementGenerator Class Reference
#include "IdleMovementGenerator.h"
Public Member Functions
AssistanceDistractMovementGenerator (uint32 timer)
MovementGeneratorType GetMovementGeneratorType () override
void Finalize (Unit *) override
Public Member Functions inherited from DistractMovementGenerator
DistractMovementGenerator (uint32 timer)
void Initialize (Unit *) override
void Finalize (Unit *) override
void Reset (Unit *owner) override
bool Update (Unit *, uint32) override
MovementGeneratorType GetMovementGeneratorType () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual void Initialize (Unit *)=0
virtual void Finalize (Unit *)=0
virtual void Reset (Unit *)=0
virtual bool Update (Unit *, uint32 time_diff)=0
virtual MovementGeneratorType GetMovementGeneratorType ()=0
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual void Pause (uint32)
virtual void Resume (uint32)
virtual bool GetResetPosition (float &, float &, float &)
Detailed Description
Constructor & Destructor Documentation
AssistanceDistractMovementGenerator()
AssistanceDistractMovementGenerator::AssistanceDistractMovementGenerator (uint32 timer) inline
                                                      :
        DistractMovementGenerator(timer) {}
Member Function Documentation
Finalize()
void AssistanceDistractMovementGenerator::Finalize (Unit * unit) override virtual
Reimplemented from DistractMovementGenerator.
{
    unit->ClearUnitState(UNIT_STATE_DISTRACTED);
    unit->ToCreature()->SetReactState(REACT_AGGRESSIVE);
}
References Unit::ClearUnitState(), REACT_AGGRESSIVE, Creature::SetReactState(), Object::ToCreature(), and UNIT_STATE_DISTRACTED.
GetMovementGeneratorType()
MovementGeneratorType AssistanceDistractMovementGenerator::GetMovementGeneratorType () inline override virtual
Reimplemented from DistractMovementGenerator.
{ return ASSISTANCE_DISTRACT_MOTION_TYPE; }
References ASSISTANCE_DISTRACT_MOTION_TYPE.