AzerothCore: go_skull_pile Class Reference
go_skull_pile Class Reference
Public Member Functions
go_skull_pile ()
bool OnGossipSelect (Player *player, GameObject *go, uint32 sender, uint32 action) override
bool OnGossipHello (Player *player, GameObject *go) override
void SendActionMenu (Player *player, GameObject *go, uint32 action)
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, GameObject *)
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnModifyHealth (GameObject *, Unit *, int32 &, SpellInfo const *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Private Attributes
SpellCastResult _result
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
go_skull_pile()
go_skull_pile::go_skull_pile () inline
: GameObjectScript("go_skull_pile") { }
Member Function Documentation
OnGossipHello()
bool go_skull_pile::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
    {
        if ((player->GetQuestStatus(QUEST_ADVERSARIAL_BLOOD) == QUEST_STATUS_INCOMPLETE) || player->GetQuestRewardStatus(QUEST_ADVERSARIAL_BLOOD))
        {
            AddGossipItemFor(player, GOSSIP_MENU_SKULL_PILE, GOSSIP_OPTION_SUMMON_GEZZARAK_THE_HUNTRESS, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
            AddGossipItemFor(player, GOSSIP_MENU_SKULL_PILE, GOSSIP_OPTION_SUMMON_DARKSCREECHER_AKKARAI, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
            AddGossipItemFor(player, GOSSIP_MENU_SKULL_PILE, GOSSIP_OPTION_SUMMON_KARROG, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
            AddGossipItemFor(player, GOSSIP_MENU_SKULL_PILE, GOSSIP_OPTION_SUMMON_VAKKIZ_THE_WINDRAGER, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
            SendGossipMenuFor(player, GOSSIP_MENU_TEXT_SKULL_PILE_QUEST, go->GetGUID());
        }
        else
            SendGossipMenuFor(player, GOSSIP_MENU_TEXT_SKULL_PILE, go->GetGUID());
        return true;
    }
References AddGossipItemFor(), Object::GetGUID(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_MENU_SKULL_PILE, GOSSIP_MENU_TEXT_SKULL_PILE, GOSSIP_MENU_TEXT_SKULL_PILE_QUEST, GOSSIP_OPTION_SUMMON_DARKSCREECHER_AKKARAI, GOSSIP_OPTION_SUMMON_GEZZARAK_THE_HUNTRESS, GOSSIP_OPTION_SUMMON_KARROG, GOSSIP_OPTION_SUMMON_VAKKIZ_THE_WINDRAGER, GOSSIP_SENDER_MAIN, QUEST_ADVERSARIAL_BLOOD, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool go_skull_pile::OnGossipSelect (Player * player, GameObject * go, uint32 sender, uint32 action) inline override virtual
Reimplemented from GameObjectScript.
    {
        ClearGossipMenuFor(player);
        if (sender == GOSSIP_SENDER_MAIN)
        {
            SendActionMenu(player, go, action);
            CloseGossipMenuFor(player);
        }
        return true;
    }
References ClearGossipMenuFor(), CloseGossipMenuFor(), GOSSIP_SENDER_MAIN, and SendActionMenu().
SendActionMenu()
void go_skull_pile::SendActionMenu (Player * player, GameObject * go, uint32 action) inline
    {
        switch (action)
        {
            case GOSSIP_ACTION_INFO_DEF + 1:
                _result = player->CastSpell(player, SPELL_SUMMON_GEZZARAK_THE_HUNTRESS, false);
                break;
            case GOSSIP_ACTION_INFO_DEF + 2:
                _result = player->CastSpell(player, SPELL_SUMMON_DARKSCREECHER_AKKARAI, false);
                break;
            case GOSSIP_ACTION_INFO_DEF + 3:
                _result = player->CastSpell(player, SPELL_SUMMON_KARROG, false);
                break;
            case GOSSIP_ACTION_INFO_DEF + 4:
                _result = player->CastSpell(player, SPELL_SUMMON_VAKKIZ_THE_WINDRAGER, false);
                break;
            default:
                _result = SPELL_CAST_OK;
                break;
        }
        if (_result == SPELL_CAST_OK)
        {
            go->DespawnOrUnsummon();
        }
    }
References _result, Unit::CastSpell(), GameObject::DespawnOrUnsummon(), GOSSIP_ACTION_INFO_DEF, SPELL_CAST_OK, SPELL_SUMMON_DARKSCREECHER_AKKARAI, SPELL_SUMMON_GEZZARAK_THE_HUNTRESS, SPELL_SUMMON_KARROG, and SPELL_SUMMON_VAKKIZ_THE_WINDRAGER.
Referenced by OnGossipSelect().
Member Data Documentation
_result
SpellCastResult go_skull_pile::_result private
Referenced by SendActionMenu().