AzerothCore: UnitActionBarEntry Struct Reference
UnitActionBarEntry Struct Reference
#include "CharmInfo.h"
Public Member Functions
UnitActionBarEntry ()
ActiveStates GetType () const
uint32 GetAction () const
bool IsActionBarForSpell () const
void SetActionAndType (uint32 action, ActiveStates type)
void SetType (ActiveStates type)
void SetAction (uint32 action)
Public Attributes
uint32 packedData
Detailed Description
Constructor & Destructor Documentation
UnitActionBarEntry()
UnitActionBarEntry::UnitActionBarEntry () inline
: packedData(uint32(ACT_DISABLED) << 24) {}
Member Function Documentation
GetAction()
uint32 UnitActionBarEntry::GetAction () const inline
{ return UNIT_ACTION_BUTTON_ACTION(packedData); }
References packedData, and UNIT_ACTION_BUTTON_ACTION.
Referenced by Player::CharmSpellInitialize(), Pet::GenerateActionBarData(), Creature::GetPetAutoSpellOnPos(), WorldSession::HandlePetSetAction(), CharmInfo::SetSpellAutocast(), and CharmInfo::ToggleCreatureAutocast().
GetType()
ActiveStates UnitActionBarEntry::GetType () const inline
{ return ActiveStates(UNIT_ACTION_BUTTON_TYPE(packedData)); }
References packedData, and UNIT_ACTION_BUTTON_TYPE.
Referenced by Pet::GenerateActionBarData(), Creature::GetPetAutoSpellOnPos(), WorldSession::HandlePetSetAction(), and IsActionBarForSpell().
IsActionBarForSpell()
bool UnitActionBarEntry::IsActionBarForSpell () const inline
    {
        ActiveStates Type = GetType();
        return Type == ACT_DISABLED || Type == ACT_ENABLED || Type == ACT_PASSIVE;
    }
References ACT_DISABLED, ACT_ENABLED, ACT_PASSIVE, and GetType().
Referenced by CharmInfo::SetSpellAutocast().
SetAction()
void UnitActionBarEntry::SetAction (uint32 action) inline
    {
        packedData = (packedData & 0xFF000000) | UNIT_ACTION_BUTTON_ACTION(action);
    }
References packedData, and UNIT_ACTION_BUTTON_ACTION.
Referenced by CharmInfo::AddSpellToActionBar().
SetActionAndType()
void UnitActionBarEntry::SetActionAndType (uint32 action, ActiveStates type) inline
    {
        packedData = MAKE_UNIT_ACTION_BUTTON(action, type);
    }
References MAKE_UNIT_ACTION_BUTTON, and packedData.
Referenced by CharmInfo::InitCharmCreateSpells(), CharmInfo::LoadPetActionBar(), and CharmInfo::SetActionBar().
SetType()
void UnitActionBarEntry::SetType (ActiveStates type) inline
    {
        packedData = MAKE_UNIT_ACTION_BUTTON(UNIT_ACTION_BUTTON_ACTION(packedData), type);
    }
References MAKE_UNIT_ACTION_BUTTON, packedData, and UNIT_ACTION_BUTTON_ACTION.
Referenced by CharmInfo::SetSpellAutocast(), and CharmInfo::ToggleCreatureAutocast().
Member Data Documentation
packedData
uint32 UnitActionBarEntry::packedData
Referenced by Player::CharmSpellInitialize(), GetAction(), GetType(), SetAction(), SetActionAndType(), and SetType().