AzerothCore: BGQueueInviteEvent Class Reference
BGQueueInviteEvent Class Reference
#include "BattlegroundQueue.h"
Public Member Functions
BGQueueInviteEvent (ObjectGuid pl_guid, uint32 BgInstanceGUID, BattlegroundTypeId BgTypeId, uint8 arenaType, uint32 removeTime)
~BGQueueInviteEvent () override=default
bool Execute (uint64 e_time, uint32 p_time) override
void Abort (uint64 e_time) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
ObjectGuid m_PlayerGuid
uint32 m_BgInstanceGUID
BattlegroundTypeId m_BgTypeId
uint8 m_ArenaType
uint32 m_RemoveTime
Detailed Description
Constructor & Destructor Documentation
BGQueueInviteEvent()
BGQueueInviteEvent::BGQueueInviteEvent (ObjectGuid pl_guid, uint32 BgInstanceGUID, BattlegroundTypeId BgTypeId, uint8 arenaType, uint32 removeTime) inline
                                                                                                                                   :
        m_PlayerGuid(pl_guid), m_BgInstanceGUID(BgInstanceGUID), m_BgTypeId(BgTypeId), m_ArenaType(arenaType), m_RemoveTime(removeTime)
    { }
~BGQueueInviteEvent()
BGQueueInviteEvent::~BGQueueInviteEvent () override default
Member Function Documentation
Abort()
void BGQueueInviteEvent::Abort (uint64 e_time) override virtual
Reimplemented from BasicEvent.
{
    //do nothing
}
Execute()
bool BGQueueInviteEvent::Execute (uint64 e_time, uint32 p_time) override virtual
Reimplemented from BasicEvent.
{
    Player* player = ObjectAccessor::FindConnectedPlayer(m_PlayerGuid);
    // player logged off, so he is no longer in queue
    if (!player)
        return true;
    Battleground* bg = sBattlegroundMgr->GetBattleground(m_BgInstanceGUID, m_BgTypeId);
    // if battleground ended, do nothing
    if (!bg)
        return true;
    // check if still in queue for this battleground
    BattlegroundQueueTypeId bgQueueTypeId = BattlegroundMgr::BGQueueTypeId(m_BgTypeId, m_ArenaType);
    uint32 queueSlot = player->GetBattlegroundQueueIndex(bgQueueTypeId);
    if (queueSlot < PLAYER_MAX_BATTLEGROUND_QUEUES)
    {
        // confirm the player is invited to this instance id (he didn't requeue in the meanwhile)
        BattlegroundQueue& bgQueue = sBattlegroundMgr->GetBattlegroundQueue(bgQueueTypeId);
        if (bgQueue.IsPlayerInvited(m_PlayerGuid, m_BgInstanceGUID, m_RemoveTime))
        {
            // send remaining time in queue
            WorldPacket data;
            sBattlegroundMgr->BuildBattlegroundStatusPacket(&data, bg, queueSlot, STATUS_WAIT_JOIN, INVITE_ACCEPT_WAIT_TIME - INVITATION_REMIND_TIME, 0, m_ArenaType, TEAM_NEUTRAL, bg->isRated(), m_BgTypeId);
            player->GetSession()->SendPacket(&data);
        }
    }
    return true;
}
References BattlegroundMgr::BGQueueTypeId(), ObjectAccessor::FindConnectedPlayer(), Player::GetBattlegroundQueueIndex(), Player::GetSession(), INVITATION_REMIND_TIME, INVITE_ACCEPT_WAIT_TIME, BattlegroundQueue::IsPlayerInvited(), Battleground::isRated(), PLAYER_MAX_BATTLEGROUND_QUEUES, sBattlegroundMgr, WorldSession::SendPacket(), STATUS_WAIT_JOIN, and TEAM_NEUTRAL.
Member Data Documentation
m_ArenaType
uint8 BGQueueInviteEvent::m_ArenaType private
m_BgInstanceGUID
uint32 BGQueueInviteEvent::m_BgInstanceGUID private
m_BgTypeId
BattlegroundTypeId BGQueueInviteEvent::m_BgTypeId private
m_PlayerGuid
ObjectGuid BGQueueInviteEvent::m_PlayerGuid private
m_RemoveTime
uint32 BGQueueInviteEvent::m_RemoveTime private