AzerothCore: azerothcore-wotlk/src/server/game/Entities/Object/ObjectDefines.h File Reference
ObjectDefines.h File Reference
#include "Define.h"
Macros
#define CONTACT_DISTANCE 0.5f
#define INTERACTION_DISTANCE 5.5f
#define ATTACK_DISTANCE 5.0f
#define VISIBILITY_COMPENSATION 15.0f
#define INSPECT_DISTANCE 28.0f
#define VISIBILITY_INC_FOR_GOBJECTS 30.0f
#define SPELL_SEARCHER_COMPENSATION 30.0f
#define TRADE_DISTANCE 11.11f
#define MAX_VISIBILITY_DISTANCE 250.0f
#define SIGHT_RANGE_UNIT 50.0f
#define MAX_SEARCHER_DISTANCE 150.0f
#define VISIBILITY_DISTANCE_INFINITE 533.0f
#define VISIBILITY_DISTANCE_GIGANTIC 400.0f
#define VISIBILITY_DISTANCE_LARGE 200.0f
#define VISIBILITY_DISTANCE_NORMAL 100.0f
#define VISIBILITY_DISTANCE_SMALL 50.0f
#define VISIBILITY_DISTANCE_TINY 25.0f
#define DEFAULT_VISIBILITY_DISTANCE 100.0f
#define DEFAULT_VISIBILITY_INSTANCE 170.0f
#define VISIBILITY_DIST_WINTERGRASP 175.0f
#define DEFAULT_VISIBILITY_BGARENAS 250.0f
#define DEFAULT_WORLD_OBJECT_SIZE 0.388999998569489f
#define DEFAULT_COMBAT_REACH 1.5f
#define MIN_MELEE_REACH 2.0f
#define NOMINAL_MELEE_RANGE 5.0f
#define MELEE_RANGE (NOMINAL_MELEE_RANGE - MIN_MELEE_REACH * 2)
#define DEFAULT_COLLISION_HEIGHT 2.03128f
Enumerations
enum class VisibilityDistanceType : uint8 {
Normal = 0 ,
Tiny = 1 ,
Small = 2 ,
Large = 3 ,
Gigantic = 4 ,
Infinite = 5 ,
Max
}
Functions
uint32 PAIR64_HIPART (uint64 x)
uint32 PAIR64_LOPART (uint64 x)
uint16 MAKE_PAIR16 (uint8 l, uint8 h)
uint32 MAKE_PAIR32 (uint16 l, uint16 h)
uint16 PAIR32_HIPART (uint32 x)
uint16 PAIR32_LOPART (uint32 x)
Macro Definition Documentation
ATTACK_DISTANCE
#define ATTACK_DISTANCE 5.0f
CONTACT_DISTANCE
#define CONTACT_DISTANCE 0.5f
DEFAULT_COLLISION_HEIGHT
#define DEFAULT_COLLISION_HEIGHT 2.03128f
DEFAULT_COMBAT_REACH
#define DEFAULT_COMBAT_REACH 1.5f
DEFAULT_VISIBILITY_BGARENAS
#define DEFAULT_VISIBILITY_BGARENAS 250.0f
DEFAULT_VISIBILITY_DISTANCE
#define DEFAULT_VISIBILITY_DISTANCE 100.0f
DEFAULT_VISIBILITY_INSTANCE
#define DEFAULT_VISIBILITY_INSTANCE 170.0f
DEFAULT_WORLD_OBJECT_SIZE
#define DEFAULT_WORLD_OBJECT_SIZE 0.388999998569489f
INSPECT_DISTANCE
#define INSPECT_DISTANCE 28.0f
INTERACTION_DISTANCE
#define INTERACTION_DISTANCE 5.5f
MAX_SEARCHER_DISTANCE
#define MAX_SEARCHER_DISTANCE 150.0f
MAX_VISIBILITY_DISTANCE
#define MAX_VISIBILITY_DISTANCE 250.0f
MELEE_RANGE
#define MELEE_RANGE (NOMINAL_MELEE_RANGE - MIN_MELEE_REACH * 2)
MIN_MELEE_REACH
#define MIN_MELEE_REACH 2.0f
NOMINAL_MELEE_RANGE
#define NOMINAL_MELEE_RANGE 5.0f
SIGHT_RANGE_UNIT
#define SIGHT_RANGE_UNIT 50.0f
SPELL_SEARCHER_COMPENSATION
#define SPELL_SEARCHER_COMPENSATION 30.0f
TRADE_DISTANCE
#define TRADE_DISTANCE 11.11f
VISIBILITY_COMPENSATION
#define VISIBILITY_COMPENSATION 15.0f
VISIBILITY_DIST_WINTERGRASP
#define VISIBILITY_DIST_WINTERGRASP 175.0f
VISIBILITY_DISTANCE_GIGANTIC
#define VISIBILITY_DISTANCE_GIGANTIC 400.0f
VISIBILITY_DISTANCE_INFINITE
#define VISIBILITY_DISTANCE_INFINITE 533.0f
VISIBILITY_DISTANCE_LARGE
#define VISIBILITY_DISTANCE_LARGE 200.0f
VISIBILITY_DISTANCE_NORMAL
#define VISIBILITY_DISTANCE_NORMAL 100.0f
VISIBILITY_DISTANCE_SMALL
#define VISIBILITY_DISTANCE_SMALL 50.0f
VISIBILITY_DISTANCE_TINY
#define VISIBILITY_DISTANCE_TINY 25.0f
VISIBILITY_INC_FOR_GOBJECTS
#define VISIBILITY_INC_FOR_GOBJECTS 30.0f
Enumeration Type Documentation
VisibilityDistanceType
enum class VisibilityDistanceType : uint8 strong
Enumerator
Normal
Tiny
Small
Large
Gigantic
Infinite
Max
{
    Normal   = 0,
    Tiny     = 1,
    Small    = 2,
    Large    = 3,
    Gigantic = 4,
    Infinite = 5,
    Max
};
Function Documentation
MAKE_PAIR16()
uint16 MAKE_PAIR16 (uint8 l, uint8 h) inline
{
    return uint16(l | (uint16(h) << 8));
}
Referenced by ObjectMgr::GetCreatureBaseStats(), and ObjectMgr::LoadCreatureClassLevelStats().
MAKE_PAIR32()
uint32 MAKE_PAIR32 (uint16 l, uint16 h) inline
{
    return uint32(l | (uint32(h) << 16));
}
Referenced by Player::_LoadSkills(), ObjectMgr::AddCreatureToGrid(), ObjectMgr::AddGameobjectToGrid(), GossipMenu::AddMenuItem(), ObjectMgr::GetCellObjectGuids(), ObjectMgr::GetDungeonEncounterList(), InstanceSaveMgr::GetExtendedResetTimeFor(), GetMapDifficultyData(), ObjectMgr::GetMapObjectGuids(), InstanceSaveMgr::GetResetTimeFor(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadInstanceEncounters(), Player::PrepareGossipMenu(), ObjectMgr::RemoveCreatureFromGrid(), ObjectMgr::RemoveGameobjectFromGrid(), InstanceSaveMgr::SetExtendedResetTimeFor(), InstanceSaveMgr::SetResetTimeFor(), Player::SetSkill(), and Player::UpdateHonorFields().
PAIR32_HIPART()
uint16 PAIR32_HIPART (uint32 x) inline
{
    return (uint16)((x >> 16) & 0x0000FFFF);
}
Referenced by Player::GetSkillStep(), WorldSession::HandleCalendarGetCalendar(), and InstanceSaveMgr::LoadResetTimes().
PAIR32_LOPART()
uint16 PAIR32_LOPART (uint32 x) inline
{
    return (uint16)(x & 0x0000FFFF);
}
Referenced by WorldSession::HandleCalendarGetCalendar(), InstanceSaveMgr::LoadResetTimes(), and Player::UpdateHonorFields().
PAIR64_HIPART()
uint32 PAIR64_HIPART (uint64 x) inline
{
    return (uint32)((x >> 32) & UI64LIT(0x00000000FFFFFFFF));
}
References UI64LIT.
Referenced by Object::SetUInt64Value().
PAIR64_LOPART()
uint32 PAIR64_LOPART (uint64 x) inline
{
    return (uint32)(x & UI64LIT(0x00000000FFFFFFFF));
}
References UI64LIT.
Referenced by Object::SetUInt64Value().