AzerothCore: instance_scholomance::instance_scholomance_InstanceMapScript Struct Reference
instance_scholomance::instance_scholomance_InstanceMapScript Struct Reference
Public Member Functions
instance_scholomance_InstanceMapScript (Map *map)
void OnCreatureCreate (Creature *cr) override
void OnGameObjectCreate (GameObject *go) override
ObjectGuid GetGuidData (uint32 type) const override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
ObjectGuid GateKirtonosGUID
ObjectGuid GateMiliciaGUID
ObjectGuid GateTheolenGUID
ObjectGuid GatePolkeltGUID
ObjectGuid GateRavenianGUID
ObjectGuid GateBarovGUID
ObjectGuid GateIlluciaGUID
ObjectGuid BrazierKirtonosGUID
ObjectGuid GandlingGatesGUID [7]
ObjectGuid GandlingGUID
uint32 _kirtonosState
uint32 _miniBosses
uint32 _rasHuman
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_scholomance_InstanceMapScript()
instance_scholomance::instance_scholomance_InstanceMapScript::instance_scholomance_InstanceMapScript (Map * map) inline
                                                         : InstanceScript(map)
        {
            _miniBosses = 0;
            _kirtonosState = 0;
            _rasHuman      = 0;
        }
References _kirtonosState, _miniBosses, and _rasHuman.
Member Function Documentation
GetData()
uint32 instance_scholomance::instance_scholomance_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_KIRTONOS_THE_HERALD:
                    return _kirtonosState;
                case DATA_MINI_BOSSES:
                    return _miniBosses;
                case DATA_RAS_HUMAN:
                    return _rasHuman;
            }
            return 0;
        }
References _kirtonosState, _miniBosses, _rasHuman, DATA_KIRTONOS_THE_HERALD, DATA_MINI_BOSSES, and DATA_RAS_HUMAN.
GetGuidData()
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case GO_GATE_KIRTONOS:
                    return GateKirtonosGUID;
                case GO_BRAZIER_KIRTONOS:
                    return BrazierKirtonosGUID;
                case GO_GATE_GANDLING_DOWN_NORTH:
                    return GandlingGatesGUID[0];
                case GO_GATE_GANDLING_DOWN_EAST:
                    return GandlingGatesGUID[1];
                case GO_GATE_GANDLING_DOWN_SOUTH:
                    return GandlingGatesGUID[2];
                case GO_GATE_GANDLING_UP_NORTH:
                    return GandlingGatesGUID[3];
                case GO_GATE_GANDLING_UP_EAST:
                    return GandlingGatesGUID[4];
                case GO_GATE_GANDLING_UP_SOUTH:
                    return GandlingGatesGUID[5];
                case GO_GATE_GANDLING_ENTRANCE:
                    return GandlingGatesGUID[6];
                case NPC_DARKMASTER_GANDLING:
                    return GandlingGUID;
            }
            return ObjectGuid::Empty;
        }
References BrazierKirtonosGUID, ObjectGuid::Empty, GandlingGatesGUID, GandlingGUID, GateKirtonosGUID, GO_BRAZIER_KIRTONOS, GO_GATE_GANDLING_DOWN_EAST, GO_GATE_GANDLING_DOWN_NORTH, GO_GATE_GANDLING_DOWN_SOUTH, GO_GATE_GANDLING_ENTRANCE, GO_GATE_GANDLING_UP_EAST, GO_GATE_GANDLING_UP_NORTH, GO_GATE_GANDLING_UP_SOUTH, GO_GATE_KIRTONOS, and NPC_DARKMASTER_GANDLING.
Referenced by SetData().
OnCreatureCreate()
void instance_scholomance::instance_scholomance_InstanceMapScript::OnCreatureCreate (Creature * cr) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (cr->GetEntry())
            {
                case NPC_DARKMASTER_GANDLING:
                    GandlingGUID = cr->GetGUID();
                    break;
            }
        }
References GandlingGUID, Object::GetEntry(), Object::GetGUID(), and NPC_DARKMASTER_GANDLING.
OnGameObjectCreate()
void instance_scholomance::instance_scholomance_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_GATE_KIRTONOS:
                    GateKirtonosGUID = go->GetGUID();
                    break;
                case GO_DOOR_OPENED_WITH_KEY:
                    go->AllowSaveToDB(true);
                    break;
                case GO_GATE_GANDLING_DOWN_NORTH:
                    GandlingGatesGUID[0] = go->GetGUID();
                    break;
                case GO_GATE_GANDLING_DOWN_EAST:
                    GandlingGatesGUID[1] = go->GetGUID();
                    break;
                case GO_GATE_GANDLING_DOWN_SOUTH:
                    GandlingGatesGUID[2] = go->GetGUID();
                    break;
                case GO_GATE_GANDLING_UP_NORTH:
                    GandlingGatesGUID[3] = go->GetGUID();
                    break;
                case GO_GATE_GANDLING_UP_EAST:
                    GandlingGatesGUID[4] = go->GetGUID();
                    break;
                case GO_GATE_GANDLING_UP_SOUTH:
                    GandlingGatesGUID[5] = go->GetGUID();
                    break;
                case GO_GATE_GANDLING_ENTRANCE:
                    GandlingGatesGUID[6] = go->GetGUID();
                    break;
                case GO_BRAZIER_KIRTONOS:
                    BrazierKirtonosGUID = go->GetGUID();
                    break;
            }
        }
References GameObject::AllowSaveToDB(), BrazierKirtonosGUID, GandlingGatesGUID, GateKirtonosGUID, Object::GetEntry(), Object::GetGUID(), GO_BRAZIER_KIRTONOS, GO_DOOR_OPENED_WITH_KEY, GO_GATE_GANDLING_DOWN_EAST, GO_GATE_GANDLING_DOWN_NORTH, GO_GATE_GANDLING_DOWN_SOUTH, GO_GATE_GANDLING_ENTRANCE, GO_GATE_GANDLING_UP_EAST, GO_GATE_GANDLING_UP_NORTH, GO_GATE_GANDLING_UP_SOUTH, and GO_GATE_KIRTONOS.
ReadSaveDataMore()
void instance_scholomance::instance_scholomance_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> _kirtonosState;
            data >> _miniBosses;
        }
References _kirtonosState, and _miniBosses.
SetData()
void instance_scholomance::instance_scholomance_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_KIRTONOS_THE_HERALD:
                    switch (data)
                    {
                        case IN_PROGRESS:
                            // summon kirtonos and close door
                            if (_kirtonosState == NOT_STARTED)
{
                                if (Creature* kirtonos = instance->SummonCreature(NPC_KIRTONOS, KirtonosSpawn))
{
                                    kirtonos->AI()->DoAction(IN_PROGRESS);
                                }
                                if (GameObject* gate = instance->GetGameObject(GetGuidData(GO_GATE_KIRTONOS)))
{
                                    gate->SetGoState(GO_STATE_READY);
                                }
                            }
                            _kirtonosState = data;
                            break;
                        case FAIL:
                            // open door and reset brazier
                            if (GameObject* gate = instance->GetGameObject(GetGuidData(GO_GATE_KIRTONOS)))
{
                                gate->SetGoState(GO_STATE_ACTIVE);
                            }
                            if (GameObject* brazier = instance->GetGameObject(GetGuidData(GO_BRAZIER_KIRTONOS)))
{
                                brazier->SetGoState(GO_STATE_READY);
                                brazier->SetLootState(GO_JUST_DEACTIVATED);
                                brazier->Respawn();
                            }
                            _kirtonosState = NOT_STARTED;
                            break;
                        case DONE:
                            // open door
                            if (GameObject* gate = instance->GetGameObject(GetGuidData(GO_GATE_KIRTONOS)))
{
                                gate->SetGoState(GO_STATE_ACTIVE);
                            }
                            [[fallthrough]];
                        default:
                            _kirtonosState = data;
                            break;
                    }
                    break;
                case DATA_MINI_BOSSES:
                    ++_miniBosses;
                    if (_miniBosses == 6)
                    {
                        if (Creature* Gandling = instance->GetCreature(GandlingGUID))
{
                            Gandling->AI()->Talk(0);
                            Gandling->AI()->Reset();
                        }
                    }
                    break;
                case DATA_DARKMASTER_GANDLING:
                    switch (data)
                    {
                        case DONE:
                        case NOT_STARTED:
                        case FAIL:
                            HandleGameObject(GandlingGatesGUID[6], true);
                            break;
                        case IN_PROGRESS:
                            HandleGameObject(GandlingGatesGUID[6], false);
                            break;
                    }
                    break;
                case DATA_RAS_HUMAN:
                    _rasHuman = data;
                    break;
            }
            SaveToDB();
        }
References _kirtonosState, _miniBosses, _rasHuman, DATA_DARKMASTER_GANDLING, DATA_KIRTONOS_THE_HERALD, DATA_MINI_BOSSES, DATA_RAS_HUMAN, DONE, FAIL, GandlingGatesGUID, GandlingGUID, Map::GetCreature(), Map::GetGameObject(), GetGuidData(), GO_BRAZIER_KIRTONOS, GO_GATE_KIRTONOS, GO_JUST_DEACTIVATED, GO_STATE_ACTIVE, GO_STATE_READY, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, KirtonosSpawn, NOT_STARTED, NPC_KIRTONOS, InstanceScript::SaveToDB(), and Map::SummonCreature().
WriteSaveDataMore()
void instance_scholomance::instance_scholomance_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << _kirtonosState << ' ' << _miniBosses;
        }
References _kirtonosState, and _miniBosses.
Member Data Documentation
_kirtonosState
uint32 instance_scholomance::instance_scholomance_InstanceMapScript::_kirtonosState protected
Referenced by GetData(), instance_scholomance_InstanceMapScript(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
_miniBosses
uint32 instance_scholomance::instance_scholomance_InstanceMapScript::_miniBosses protected
Referenced by GetData(), instance_scholomance_InstanceMapScript(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
_rasHuman
uint32 instance_scholomance::instance_scholomance_InstanceMapScript::_rasHuman protected
Referenced by GetData(), instance_scholomance_InstanceMapScript(), and SetData().
BrazierKirtonosGUID
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::BrazierKirtonosGUID protected
Referenced by GetGuidData(), and OnGameObjectCreate().
GandlingGatesGUID
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::GandlingGatesGUID[7] protected
Referenced by GetGuidData(), OnGameObjectCreate(), and SetData().
GandlingGUID
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::GandlingGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().
GateBarovGUID
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::GateBarovGUID protected
GateIlluciaGUID
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::GateIlluciaGUID protected
GateKirtonosGUID
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::GateKirtonosGUID protected
Referenced by GetGuidData(), and OnGameObjectCreate().
GateMiliciaGUID
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::GateMiliciaGUID protected
GatePolkeltGUID
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::GatePolkeltGUID protected
GateRavenianGUID
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::GateRavenianGUID protected
GateTheolenGUID
ObjectGuid instance_scholomance::instance_scholomance_InstanceMapScript::GateTheolenGUID protected