AzerothCore: spell_mother_shahraz_fatal_attraction Class Reference
spell_mother_shahraz_fatal_attraction Class Reference
Private Member Functions
PrepareSpellScript (spell_mother_shahraz_fatal_attraction)
bool Validate (SpellInfo const *) override
void FilterTargets (std::list< WorldObject * > &targets)
void SetDest (SpellDestination &dest)
void HandleTeleportUnits (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
FilterTargets()
void spell_mother_shahraz_fatal_attraction::FilterTargets (std::list< WorldObject * > & targets) inline private
    {
        targets.remove_if(Acore::UnitAuraCheck(true, SPELL_SABER_LASH_IMMUNITY));
    }
References SPELL_SABER_LASH_IMMUNITY.
Referenced by Register().
HandleTeleportUnits()
void spell_mother_shahraz_fatal_attraction::HandleTeleportUnits (SpellEffIndex) inline private
    {
        if (Unit* target = GetHitUnit())
            GetCaster()->CastSpell(target, SPELL_FATAL_ATTRACTION_AURA, true);
    }
References Unit::CastSpell(), SpellScript::GetCaster(), SpellScript::GetHitUnit(), and SPELL_FATAL_ATTRACTION_AURA.
Referenced by Register().
PrepareSpellScript()
spell_mother_shahraz_fatal_attraction::PrepareSpellScript (spell_mother_shahraz_fatal_attraction) private
Register()
void spell_mother_shahraz_fatal_attraction::Register () inline override private virtual
Implements _SpellScript.
    {
        OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_mother_shahraz_fatal_attraction::FilterTargets, EFFECT_ALL, TARGET_UNIT_SRC_AREA_ENEMY);
        OnDestinationTargetSelect += SpellDestinationTargetSelectFn(spell_mother_shahraz_fatal_attraction::SetDest, EFFECT_1, TARGET_DEST_CASTER_RANDOM);
        OnEffectHitTarget += SpellEffectFn(spell_mother_shahraz_fatal_attraction::HandleTeleportUnits, EFFECT_1, SPELL_EFFECT_TELEPORT_UNITS);
    }
References EFFECT_1, EFFECT_ALL, FilterTargets(), HandleTeleportUnits(), SpellScript::OnDestinationTargetSelect, SpellScript::OnEffectHitTarget, SpellScript::OnObjectAreaTargetSelect, SetDest(), SPELL_EFFECT_TELEPORT_UNITS, SpellDestinationTargetSelectFn, SpellEffectFn, SpellObjectAreaTargetSelectFn, TARGET_DEST_CASTER_RANDOM, and TARGET_UNIT_SRC_AREA_ENEMY.
SetDest()
void spell_mother_shahraz_fatal_attraction::SetDest (SpellDestination & dest) inline private
    {
        Position finalDest;
        // Check if the boss is near stairs to avoid players falling through the platform with random teleports.
        if (GetCaster()->GetPositionY() < 194.f)
            finalDest = validTeleportStairsPos[urand(0, 8)];
        else
        {
            finalDest = GetCaster()->GetNearPosition(frand(minTeleportDist, maxTeleportDist), static_cast<float>(rand_norm()) * static_cast<float>(2 * M_PI), true);
            // Maybe not necessary but just in case to avoid LOS issues with an object
            if (!GetCaster()->IsWithinLOS(finalDest.GetPositionX(), finalDest.GetPositionY(), finalDest.GetPositionZ()))
                finalDest = GetCaster()->GetNearPosition(frand(minTeleportDist, maxTeleportDist), static_cast<float>(rand_norm()) * static_cast<float>(2 * M_PI), true);
            /* @note: To avoid teleporting players near a walls, we will define a safe area.
             * As the boss have an area boudary around y: 320.f. We will limit the safe area to this value, avoiding wird issues.
             * x limit: 932.f/960.f | y limit: 224.f/320.f
             */
            if (finalDest.m_positionX < 932.f)
                finalDest.m_positionX = 932.f;
            else if (finalDest.m_positionX > 960.f)
                finalDest.m_positionX = 960.f;
            if (finalDest.m_positionY < 224.f)
                finalDest.m_positionY = 224.f;
            else if (finalDest.m_positionY > 320.f)
                finalDest.m_positionY = 320.f;
            // After relocate a finalDest outside the safe area, we need to recheck the distance with the boss
            if (GetCaster()->GetExactDist2d(finalDest) < minTeleportDist)
            {
                if (finalDest.m_positionX == 932.f || finalDest.m_positionX == 960.f)
                    finalDest.m_positionY = finalDest.m_positionY + (minTeleportDist - GetCaster()->GetExactDist2d(finalDest));
                else if (finalDest.m_positionY == 224.f || finalDest.m_positionY == 320.f)
                    finalDest.m_positionX = finalDest.m_positionX + (minTeleportDist - GetCaster()->GetExactDist2d(finalDest));
            }
        }
        dest.Relocate(finalDest);
    }
References frand(), SpellScript::GetCaster(), Position::GetExactDist2d(), WorldObject::GetNearPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Position::m_positionX, Position::m_positionY, maxTeleportDist, minTeleportDist, rand_norm(), SpellDestination::Relocate(), urand(), and validTeleportStairsPos.
Referenced by Register().
Validate()
bool spell_mother_shahraz_fatal_attraction::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo({ SPELL_FATAL_ATTRACTION_AURA });
    }
References SPELL_FATAL_ATTRACTION_AURA, and _SpellScript::ValidateSpellInfo().