AzerothCore: PetScript Class Reference
PetScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnInitStatsForLevel (Guardian *, uint8)
virtual void OnCalculateMaxTalentPointsForLevel (Pet *, uint8, uint8 &)
virtual bool CanUnlearnSpellSet (Pet *, uint32, uint32)
virtual bool CanUnlearnSpellDefault (Pet *, SpellInfo const *)
virtual bool CanResetTalents (Pet *)
virtual void OnPetAddToWorld (Pet *)
This hook called after add pet in world.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
PetScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
PetScript()
PetScript::PetScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<PetScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanResetTalents()
virtual bool PetScript::CanResetTalents (Pet *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanResetTalents().
CanUnlearnSpellDefault()
virtual bool PetScript::CanUnlearnSpellDefault (Pet * , SpellInfo const *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanUnlearnSpellDefault().
CanUnlearnSpellSet()
virtual bool PetScript::CanUnlearnSpellSet (Pet * , uint32 , uint32) inline virtual
{ return true; }
Referenced by ScriptMgr::CanUnlearnSpellSet().
IsDatabaseBound()
bool PetScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
OnCalculateMaxTalentPointsForLevel()
virtual void PetScript::OnCalculateMaxTalentPointsForLevel (Pet * , uint8 , uint8 &) inline virtual
{ }
Referenced by ScriptMgr::OnCalculateMaxTalentPointsForLevel().
OnInitStatsForLevel()
virtual void PetScript::OnInitStatsForLevel (Guardian * , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnInitStatsForLevel().
OnPetAddToWorld()
virtual void PetScript::OnPetAddToWorld (Pet *) inline virtual
This hook called after add pet in world.
Parameters
pet Contains information about the Pet
{ }
Referenced by ScriptMgr::OnPetAddToWorld().