AzerothCore: SmartTrigger Class Reference
SmartTrigger Class Reference
Public Member Functions
SmartTrigger ()
bool OnTrigger (Player *player, AreaTrigger const *trigger) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
SmartTrigger()
SmartTrigger::SmartTrigger () inline
: AreaTriggerScript("SmartTrigger") {}
Member Function Documentation
OnTrigger()
bool SmartTrigger::OnTrigger (Player * player, AreaTrigger const * trigger) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (!player->IsAlive())
            return false;
        LOG_DEBUG("sql.sql", "AreaTrigger {} is using SmartTrigger script", trigger->entry);
        SmartScript script;
        script.OnInitialize(nullptr, trigger);
        script.ProcessEventsFor(SMART_EVENT_AREATRIGGER_ONTRIGGER, player, trigger->entry);
        return true;
    }
References AreaTrigger::entry, Unit::IsAlive(), LOG_DEBUG, SmartScript::OnInitialize(), SmartScript::ProcessEventsFor(), and SMART_EVENT_AREATRIGGER_ONTRIGGER.