AzerothCore: npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI Struct Reference
npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI Struct Reference
Public Member Functions
npc_icc_gauntlet_controllerAI (Creature *creature)
void ScheduleBroodlings ()
void SummonBroodling ()
void SummonFrostwardens ()
void SummonSpiders ()
void SpidersMoveDown ()
void DoAction (int32 param) override
void Reset () override
void JustReachedHome () override
void JustDied (Unit *) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
SummonList summons
InstanceScript * instance
EventMap events
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_icc_gauntlet_controllerAI()
npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::npc_icc_gauntlet_controllerAI (Creature * creature) inline
                                                          : NullCreatureAI(creature), summons(me)
        {
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DoAction()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_START_GAUNTLET)
            {
                Talk(SAY_INIT);
                me->setActive(true);
                events.Reset();
                events.SetPhase(0);
                events.ScheduleEvent(EVENT_CHECK_FIGHT, 1s);
                events.ScheduleEvent(EVENT_GAUNTLET_PHASE1, 0ms);
                instance->SetBossState(DATA_SINDRAGOSA_GAUNTLET, IN_PROGRESS);
            }
        }
References ACTION_START_GAUNTLET, DATA_SINDRAGOSA_GAUNTLET, EVENT_CHECK_FIGHT, EVENT_GAUNTLET_PHASE1, IN_PROGRESS, instance, CreatureAI::me, SAY_INIT, WorldObject::setActive(), and InstanceScript::SetBossState().
JustDied()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            instance->SetBossState(DATA_SINDRAGOSA_GAUNTLET, DONE);
        }
References DATA_SINDRAGOSA_GAUNTLET, DONE, instance, and InstanceScript::SetBossState().
JustReachedHome()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
        {
            me->setActive(false);
        }
References CreatureAI::me, and WorldObject::setActive().
JustSummoned()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
        {
            summons.Summon(summon);
            if (summon->GetPositionZ() > 220.0f)
            {
                summon->SetDisableGravity(true);
                summon->SetWalk(true);
            }
        }
References Position::GetPositionZ(), Creature::SetDisableGravity(), Creature::SetWalk(), SummonList::Summon(), and summons.
Reset()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            events.Reset();
            summons.DespawnAll();
            if (instance->GetBossState(DATA_SINDRAGOSA_GAUNTLET) != DONE)
            {
                instance->SetBossState(DATA_SINDRAGOSA_GAUNTLET, NOT_STARTED);
                SummonSpiders();
            }
        }
References DATA_SINDRAGOSA_GAUNTLET, SummonList::DespawnAll(), DONE, InstanceScript::GetBossState(), instance, NOT_STARTED, InstanceScript::SetBossState(), summons, and SummonSpiders().
ScheduleBroodlings()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::ScheduleBroodlings () inline
        {
            for (uint8 i = 0; i < 30; ++i)
                events.ScheduleEvent(EVENT_SUMMON_BROODLING, 10000 + i * 350);
        }
References EVENT_SUMMON_BROODLING.
Referenced by UpdateAI().
SpidersMoveDown()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SpidersMoveDown () inline
        {
            for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                if (Creature* spider = ObjectAccessor::GetCreature(*me, *itr))
                    if (spider->GetPositionZ() > 220.0f)
                    {
                        spider->CastSpell(spider, SPELL_WEB_BEAM2, false);
                        spider->GetMotionMaster()->MoveLand(POINT_ENTER_COMBAT, spider->GetPositionX(), spider->GetPositionY(), 213.03f, false);
                    }
        }
References SummonList::begin(), SummonList::end(), ObjectAccessor::GetCreature(), CreatureAI::me, POINT_ENTER_COMBAT, SPELL_WEB_BEAM2, and summons.
Referenced by UpdateAI().
SummonBroodling()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling () inline
        {
            float dist = frand(18.0f, 39.0f);
            float o = rand_norm() * 2 * M_PI;
            if (Creature* broodling = me->SummonCreature(NPC_NERUBAR_BROODLING, me->GetPositionX() + cos(o) * dist, me->GetPositionY() + std::sin(o) * dist, 250.0f, Position::NormalizeOrientation(o - M_PI)))
            {
                broodling->CastSpell(broodling, SPELL_WEB_BEAM2, false);
                broodling->GetMotionMaster()->MovePoint(POINT_ENTER_COMBAT, broodling->GetPositionX(), broodling->GetPositionY(), 213.03f, false);
            }
        }
References frand(), Position::GetPositionX(), Position::GetPositionY(), CreatureAI::me, Position::NormalizeOrientation(), NPC_NERUBAR_BROODLING, POINT_ENTER_COMBAT, rand_norm(), SPELL_WEB_BEAM2, and WorldObject::SummonCreature().
Referenced by UpdateAI().
SummonedCreatureDies()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            summons.Despawn(summon);
            if (summon->GetEntry() != NPC_NERUBAR_BROODLING && summons.GetEntryCount(NPC_NERUBAR_BROODLING) == summons.size())
            {
                if (events.GetPhaseMask() == 0)
                {
                    events.SetPhase(1);
                    events.ScheduleEvent(EVENT_GAUNTLET_PHASE2, 0ms);
                }
                else if (events.GetPhaseMask() == 1)
                {
                    events.SetPhase(2);
                    events.ScheduleEvent(EVENT_GAUNTLET_PHASE3, 0ms);
                }
                else
                    me->KillSelf();
            }
        }
References SummonList::Despawn(), EVENT_GAUNTLET_PHASE2, EVENT_GAUNTLET_PHASE3, Object::GetEntry(), SummonList::GetEntryCount(), Unit::KillSelf(), CreatureAI::me, NPC_NERUBAR_BROODLING, SummonList::size(), and summons.
SummonFrostwardens()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonFrostwardens () inline
        {
            for (uint8 i = 0; i < 3; ++i)
            {
                me->SummonCreature(i == 1 ? NPC_FROSTWARDEN_SORCERESS : NPC_FROSTWARDEN_WARRIOR, 4173.94f + i * 7.0f, 2409.15f, 211.033f, 1.56f);
                me->SummonCreature(i == 1 ? NPC_FROSTWARDEN_SORCERESS : NPC_FROSTWARDEN_WARRIOR, 4173.94f + i * 7.0f, 2556.71f, 211.033f, 4.712f);
            }
        }
References CreatureAI::me, NPC_FROSTWARDEN_SORCERESS, NPC_FROSTWARDEN_WARRIOR, and WorldObject::SummonCreature().
Referenced by UpdateAI().
SummonSpiders()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonSpiders () inline
        {
            me->SummonCreature(NPC_NERUBAR_CHAMPION, 4207.30f, 2532.00f, 256.0, 4.253f);
            me->SummonCreature(NPC_NERUBAR_WEBWEAVER, 4228.79f, 2510.36f, 256.0f, 3.577f);
            me->SummonCreature(NPC_NERUBAR_CHAMPION, 4228.34f, 2458.20f, 256.0f, 2.642f);
            me->SummonCreature(NPC_NERUBAR_WEBWEAVER, 4207.54f, 2437.18f, 256.0f, 2.073f);
            me->SummonCreature(NPC_NERUBAR_CHAMPION, 4156.20f, 2436.80f, 256.0f, 1.083f);
            me->SummonCreature(NPC_NERUBAR_WEBWEAVER, 4133.50f, 2459.28f, 256.0f, 0.483f);
            me->SummonCreature(NPC_NERUBAR_CHAMPION, 4134.28f, 2509.71f, 256.0f, 5.788f);
            me->SummonCreature(NPC_NERUBAR_WEBWEAVER, 4156.29f, 2532.19f, 256.0f, 5.187f);
        }
References CreatureAI::me, NPC_NERUBAR_CHAMPION, NPC_NERUBAR_WEBWEAVER, and WorldObject::SummonCreature().
Referenced by Reset(), and UpdateAI().
UpdateAI()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_CHECK_FIGHT:
                    {
                        Map::PlayerList const& pList = me->GetMap()->GetPlayers();
                        for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
{
                            if (me->GetDistance(itr->GetSource()) > 100.0f || !itr->GetSource()->IsAlive() || itr->GetSource()->IsGameMaster())
                                continue;
                            events.ScheduleEvent(EVENT_CHECK_FIGHT, 1s);
                            return;
                        }
                        CreatureAI::EnterEvadeMode();
                        return;
                    }
                case EVENT_GAUNTLET_PHASE1:
                    ScheduleBroodlings();
                    SpidersMoveDown();
                    break;
                case EVENT_GAUNTLET_PHASE2:
                    ScheduleBroodlings();
                    SummonFrostwardens();
                    break;
                case EVENT_GAUNTLET_PHASE3:
                    ScheduleBroodlings();
                    SummonSpiders();
                    SpidersMoveDown();
                    break;
                case EVENT_SUMMON_BROODLING:
                    SummonBroodling();
                    break;
            }
        }
References MapRefMgr::begin(), MapRefMgr::end(), CreatureAI::EnterEvadeMode(), EVENT_CHECK_FIGHT, EVENT_GAUNTLET_PHASE1, EVENT_GAUNTLET_PHASE2, EVENT_GAUNTLET_PHASE3, EVENT_SUMMON_BROODLING, WorldObject::GetDistance(), WorldObject::GetMap(), Map::GetPlayers(), CreatureAI::me, ScheduleBroodlings(), SpidersMoveDown(), SummonBroodling(), SummonFrostwardens(), and SummonSpiders().
Member Data Documentation
events
EventMap npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::events
instance
InstanceScript* npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::instance
Referenced by DoAction(), JustDied(), npc_icc_gauntlet_controllerAI(), and Reset().
summons
SummonList npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::summons
Referenced by JustSummoned(), Reset(), SpidersMoveDown(), and SummonedCreatureDies().