AzerothCore: WorldSocketMgr Class Reference
WorldSocketMgr Class Reference
User to World Communication
Manages all sockets connected to peers and network threads.
#include "WorldSocketMgr.h"
Public Member Functions
bool StartWorldNetwork (Acore::Asio::IoContext &ioContext, std::string const &bindIp, uint16 port, int networkThreads)
Start network, listen at address:port .
void StopNetwork () override
Stops all network threads, It will wait for all running threads .
void OnSocketOpen (tcp::socket &&sock, uint32 threadIndex) override
std::size_t GetApplicationSendBufferSize () const
Public Member Functions inherited from SocketMgr< WorldSocket >
virtual ~SocketMgr ()
virtual bool StartNetwork (Acore::Asio::IoContext &ioContext, std::string const &bindIp, uint16 port, int threadCount)
virtual void StopNetwork ()
void Wait ()
virtual void OnSocketOpen (tcp::socket &&sock, uint32 threadIndex)
int32 GetNetworkThreadCount () const
uint32 SelectThreadWithMinConnections () const
std::pair< tcp::socket *, uint32 > GetSocketForAccept ()
Static Public Member Functions
static WorldSocketMgr & Instance ()
Protected Member Functions
WorldSocketMgr ()
NetworkThread< WorldSocket > * CreateThreads () const override
Protected Member Functions inherited from SocketMgr< WorldSocket >
SocketMgr ()=default
virtual NetworkThread< WorldSocket > * CreateThreads () const=0
Static Protected Member Functions
static void OnSocketAccept (tcp::socket &&sock, uint32 threadIndex)
Private Types
typedef SocketMgr< WorldSocket > BaseSocketMgr
Private Attributes
int32 _socketSystemSendBufferSize
int32 _socketApplicationSendBufferSize
bool _tcpNoDelay
Additional Inherited Members
Protected Attributes inherited from SocketMgr< WorldSocket >
std::unique_ptr< AsyncAcceptor > _acceptor
std::unique_ptr< NetworkThread< WorldSocket >[]> _threads
int32 _threadCount
Detailed Description
Manages all sockets connected to peers and network threads.
Member Typedef Documentation
BaseSocketMgr
typedef SocketMgr<WorldSocket> WorldSocketMgr::BaseSocketMgr private
Constructor & Destructor Documentation
WorldSocketMgr()
WorldSocketMgr::WorldSocketMgr () protected
                               :
    BaseSocketMgr(), _socketSystemSendBufferSize(-1), _socketApplicationSendBufferSize(4096), _tcpNoDelay(true)
{
}
Member Function Documentation
CreateThreads()
NetworkThread< WorldSocket > * WorldSocketMgr::CreateThreads () const override protected virtual
Implements SocketMgr< WorldSocket >.
{
    NetworkThread<WorldSocket>* threads = new WorldSocketThread[GetNetworkThreadCount()];
    bool proxyProtocolEnabled = sConfigMgr->GetOption<bool>("Network.EnableProxyProtocol", false, true);
    if (proxyProtocolEnabled)
        for (int i = 0; i < GetNetworkThreadCount(); i++)
            threads[i].EnableProxyProtocol();
    return threads;
}
References SocketMgr< WorldSocket >::GetNetworkThreadCount(), and sConfigMgr.
GetApplicationSendBufferSize()
std::size_t WorldSocketMgr::GetApplicationSendBufferSize () const inline
{ return _socketApplicationSendBufferSize; }
Instance()
WorldSocketMgr & WorldSocketMgr::Instance () static
{
    static WorldSocketMgr instance;
    return instance;
}
OnSocketAccept()
static void WorldSocketMgr::OnSocketAccept (tcp::socket && sock, uint32 threadIndex) inline static protected
    {
        Instance().OnSocketOpen(std::forward<tcp::socket>(sock), threadIndex);
    }
References Instance.
Referenced by StartWorldNetwork().
OnSocketOpen()
void WorldSocketMgr::OnSocketOpen (tcp::socket && sock, uint32 threadIndex) override virtual
Reimplemented from SocketMgr< WorldSocket >.
{
    // set some options here
    if (_socketSystemSendBufferSize >= 0)
    {
        boost::system::error_code err;
        sock.set_option(boost::asio::socket_base::send_buffer_size(_socketSystemSendBufferSize), err);
        if (err && err != boost::system::errc::not_supported)
        {
            LOG_ERROR("network", "WorldSocketMgr::OnSocketOpen sock.set_option(boost::asio::socket_base::send_buffer_size) err = {}", err.message());
            return;
        }
    }
    // Set TCP_NODELAY.
    if (_tcpNoDelay)
    {
        boost::system::error_code err;
        sock.set_option(boost::asio::ip::tcp::no_delay(true), err);
        if (err)
        {
            LOG_ERROR("network", "WorldSocketMgr::OnSocketOpen sock.set_option(boost::asio::ip::tcp::no_delay) err = {}", err.message());
            return;
        }
    }
    BaseSocketMgr::OnSocketOpen(std::forward<tcp::socket>(sock), threadIndex);
}
References _socketSystemSendBufferSize, _tcpNoDelay, LOG_ERROR, and SocketMgr< WorldSocket >::OnSocketOpen().
StartWorldNetwork()
bool WorldSocketMgr::StartWorldNetwork (Acore::Asio::IoContext & ioContext, std::string const & bindIp, uint16 port, int networkThreads)
Start network, listen at address:port .
{
    _tcpNoDelay = sConfigMgr->GetOption<bool>("Network.TcpNodelay", true);
    int const max_connections = ACORE_MAX_LISTEN_CONNECTIONS;
    LOG_DEBUG("network", "Max allowed socket connections {}", max_connections);
    // -1 means use default
    _socketSystemSendBufferSize = sConfigMgr->GetOption<int32>("Network.OutKBuff", -1);
    _socketApplicationSendBufferSize = sConfigMgr->GetOption<int32>("Network.OutUBuff", 4096);
    if (_socketApplicationSendBufferSize <= 0)
    {
        LOG_ERROR("network", "Network.OutUBuff is wrong in your config file");
        return false;
    }
    if (!BaseSocketMgr::StartNetwork(ioContext, bindIp, port, threadCount))
        return false;
    _acceptor->AsyncAcceptWithCallback<&WorldSocketMgr::OnSocketAccept>();
    sScriptMgr->OnNetworkStart();
    return true;
}
References SocketMgr< WorldSocket >::_acceptor, _socketApplicationSendBufferSize, _socketSystemSendBufferSize, _tcpNoDelay, ACORE_MAX_LISTEN_CONNECTIONS, LOG_DEBUG, LOG_ERROR, OnSocketAccept(), sConfigMgr, sScriptMgr, and SocketMgr< WorldSocket >::StartNetwork().
StopNetwork()
void WorldSocketMgr::StopNetwork () override virtual
Stops all network threads, It will wait for all running threads .
Reimplemented from SocketMgr< WorldSocket >.
{
    BaseSocketMgr::StopNetwork();
    sScriptMgr->OnNetworkStop();
}
References sScriptMgr, and SocketMgr< WorldSocket >::StopNetwork().
Member Data Documentation
_socketApplicationSendBufferSize
int32 WorldSocketMgr::_socketApplicationSendBufferSize private
Referenced by StartWorldNetwork().
_socketSystemSendBufferSize
int32 WorldSocketMgr::_socketSystemSendBufferSize private
Referenced by OnSocketOpen(), and StartWorldNetwork().
_tcpNoDelay
bool WorldSocketMgr::_tcpNoDelay private
Referenced by OnSocketOpen(), and StartWorldNetwork().