AzerothCore: at_scarshield_infiltrator Class Reference
at_scarshield_infiltrator Class Reference
Public Member Functions
at_scarshield_infiltrator ()
bool OnTrigger (Player *player, const AreaTrigger *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
at_scarshield_infiltrator()
at_scarshield_infiltrator::at_scarshield_infiltrator () inline
: AreaTriggerScript("at_scarshield_infiltrator") { }
Member Function Documentation
OnTrigger()
bool at_scarshield_infiltrator::OnTrigger (Player * player, const AreaTrigger *) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (player && player->IsAlive())
        {
            if (Creature* creature = player->FindNearestCreature(NPC_SCARSHIELD_INFILTRATOR, 100.0f, true))
            {
                if (player->GetLevel() >= 57 && player->HasItemCount(ITEM_UNADORNED_SEAL))
                {
                    creature->AI()->SetData(0, 1); // Start transform into Vaelan
                    return true;
                }
            }
        }
        return false;
    }
References WorldObject::FindNearestCreature(), Unit::GetLevel(), Player::HasItemCount(), Unit::IsAlive(), ITEM_UNADORNED_SEAL, and NPC_SCARSHIELD_INFILTRATOR.