AzerothCore: OutdoorPvP Class Reference
OutdoorPvP Class Reference
#include "OutdoorPvP.h"
Public Types
typedef std::map< ObjectGuid::LowType, OPvPCapturePoint * > OPvPCapturePointMap
typedef std::pair< ObjectGuid::LowType, GameObject * > GoScriptPair
typedef std::pair< ObjectGuid::LowType, Creature * > CreatureScriptPair
Public Member Functions
OutdoorPvP ()=default
~OutdoorPvP () override
void DeleteSpawns ()
virtual void FillInitialWorldStates (WorldPacket &)
virtual bool HandleAreaTrigger (Player *player, uint32 trigger)
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual bool HandleOpenGo (Player *player, GameObject *go)
virtual bool SetupOutdoorPvP ()
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SendUpdateWorldState (uint32 field, uint32 value)
virtual bool Update (uint32 diff)
virtual void HandleKill (Player *killer, Unit *killed)
virtual void HandleKillImpl (Player *, Unit *)
bool IsInsideObjective (Player *player) const
virtual void AwardKillBonus (Player *)
uint32 GetTypeId () const
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipId)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
void TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2=0, Player *sameMapPlr=nullptr)
Map * GetMap () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Member Functions
void BroadcastPacket (WorldPacket &data) const
virtual void SendRemoveWorldStates (Player *)
virtual void HandlePlayerEnterZone (Player *player, uint32 zone)
virtual void HandlePlayerLeaveZone (Player *player, uint32 zone)
virtual void HandlePlayerResurrects (Player *player, uint32 zone)
void AddCapturePoint (OPvPCapturePoint *cp)
OPvPCapturePoint * GetCapturePoint (ObjectGuid::LowType spawnId) const
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player const *player) const
void TeamCastSpell (TeamId team, int32 spellId, Player *sameMapPlr=nullptr)
void SetMapFromZone (uint32 zone)
Protected Attributes
OPvPCapturePointMap _capturePoints
std::array< PlayerSet, 2 > _players
uint32 _typeId {}
bool _sendUpdate { true }
Map * _map {}
std::unordered_map< ObjectGuid::LowType, GameObject * > _goScriptStore
std::unordered_map< ObjectGuid::LowType, Creature * > _creatureScriptStore
Friends
class OutdoorPvPMgr
Detailed Description
Member Typedef Documentation
CreatureScriptPair
typedef std::pair<ObjectGuid::LowType, Creature*> OutdoorPvP::CreatureScriptPair
GoScriptPair
typedef std::pair<ObjectGuid::LowType, GameObject*> OutdoorPvP::GoScriptPair
OPvPCapturePointMap
typedef std::map<ObjectGuid::LowType, OPvPCapturePoint*> OutdoorPvP::OPvPCapturePointMap
Constructor & Destructor Documentation
OutdoorPvP()
OutdoorPvP::OutdoorPvP () default
~OutdoorPvP()
OutdoorPvP::~OutdoorPvP () override
{
    DeleteSpawns();
}
References DeleteSpawns().
Member Function Documentation
AddCapturePoint()
void OutdoorPvP::AddCapturePoint (OPvPCapturePoint * cp) inline protected
    {
        _capturePoints[cp->m_capturePointSpawnId] = cp;
    }
References _capturePoints, and OPvPCapturePoint::m_capturePointSpawnId.
Referenced by OutdoorPvPEP::SetupOutdoorPvP(), OutdoorPvPGH::SetupOutdoorPvP(), OutdoorPvPHP::SetupOutdoorPvP(), OutdoorPvPNA::SetupOutdoorPvP(), OutdoorPvPTF::SetupOutdoorPvP(), and OutdoorPvPZM::SetupOutdoorPvP().
AwardKillBonus()
virtual void OutdoorPvP::AwardKillBonus (Player *) inline virtual
{}
BroadcastPacket()
void OutdoorPvP::BroadcastPacket (WorldPacket & data) const protected
{
    // This is faster than sWorld->SendZoneMessage
    for (auto const& playerSet : _players)
        for (auto itr : playerSet)
            if (Player* const player = ObjectAccessor::FindPlayer(itr))
                player->GetSession()->SendPacket(&data);
}
References _players, and ObjectAccessor::FindPlayer().
CanTalkTo()
bool OutdoorPvP::CanTalkTo (Player * player, Creature * c, GossipMenuItems const & gso) virtual
{
    for (auto& capturePoint : _capturePoints)
        if (capturePoint.second->CanTalkTo(player, c, gso))
            return true;
    return false;
}
References _capturePoints.
DeleteSpawns()
void OutdoorPvP::DeleteSpawns ()
{
    // Remove script from any registered gameobjects/creatures
    for (auto& itr : _goScriptStore)
    {
        if (GameObject* go = itr.second)
            go->ClearZoneScript();
    }
    _goScriptStore.clear();
    for (auto& itr : _creatureScriptStore)
    {
        if (Creature* creature = itr.second)
            creature->ClearZoneScript();
    }
    _creatureScriptStore.clear();
    for (auto& capturePoint : _capturePoints)
    {
        capturePoint.second->DeleteSpawns();
        delete capturePoint.second;
    }
    _capturePoints.clear();
}
References _capturePoints, _creatureScriptStore, and _goScriptStore.
Referenced by ~OutdoorPvP().
FillInitialWorldStates()
virtual void OutdoorPvP::FillInitialWorldStates (WorldPacket &) inline virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{}
Referenced by Player::SendInitWorldStates().
GetCapturePoint()
OPvPCapturePoint * OutdoorPvP::GetCapturePoint (ObjectGuid::LowType spawnId) const protected
{
    auto const itr = _capturePoints.find(spawnId);
    if (itr != _capturePoints.end())
    {
        return itr->second;
    }
    return nullptr;
}
References _capturePoints.
Referenced by OnGameObjectCreate(), and OnGameObjectRemove().
GetMap()
Map * OutdoorPvP::GetMap () const inline
{ return _map; }
References _map.
Referenced by OPvPCapturePoint::DelCreature(), OPvPCapturePoint::DelObject(), OPvPCapturePointNA::DespawnCreatures(), OPvPCapturePointNA::GetAliveGuardsCount(), and OPvPCapturePointNA::SpawnNPCsForTeam().
GetTypeId()
uint32 OutdoorPvP::GetTypeId () const inline
{ return _typeId; }
References _typeId.
Referenced by Player::SendInitWorldStates().
HandleAreaTrigger()
bool OutdoorPvP::HandleAreaTrigger (Player * player, uint32 trigger) virtual
Reimplemented in OutdoorPvPSI.
{
    return false;
}
HandleCustomSpell()
bool OutdoorPvP::HandleCustomSpell (Player * player, uint32 spellId, GameObject * go) virtual
Reimplemented in OutdoorPvPSI.
{
    for (auto& capturePoint : _capturePoints)
        if (capturePoint.second->HandleCustomSpell(player, spellId, go))
            return true;
    return false;
}
References _capturePoints.
HandleDropFlag()
bool OutdoorPvP::HandleDropFlag (Player * player, uint32 spellId) virtual
Reimplemented in OutdoorPvPSI.
{
    for (auto& capturePoint : _capturePoints)
        if (capturePoint.second->HandleDropFlag(player, id))
            return true;
    return false;
}
References _capturePoints.
HandleGossipOption()
bool OutdoorPvP::HandleGossipOption (Player * player, Creature * creature, uint32 gossipId) virtual
{
    for (auto& capturePoint : _capturePoints)
        if (capturePoint.second->HandleGossipOption(player, creature, id))
            return true;
    return false;
}
References _capturePoints.
HandleKill()
void OutdoorPvP::HandleKill (Player * killer, Unit * killed) virtual
Reimplemented in OutdoorPvPNA.
{
    ASSERT(killer);
    if (Group* group = killer->GetGroup())
    {
        for (GroupReference* itr = group->GetFirstMember(); itr != nullptr; itr = itr->next())
        {
            Player* groupGuy = itr->GetSource();
            if (!groupGuy)
                continue;
            // skip if too far away
            if (!groupGuy->IsAtGroupRewardDistance(killed) && killer != groupGuy)
                continue;
            // creature kills must be notified, even if not inside objective / not outdoor pvp active
            // player kills only count if active and inside objective
            if ((groupGuy->IsOutdoorPvPActive() && IsInsideObjective(groupGuy)) || killed->IsCreature())
            {
                HandleKillImpl(groupGuy, killed);
            }
        }
    }
    else
    {
        // creature kills must be notified, even if not inside objective / not outdoor pvp active
        if ((killer->IsOutdoorPvPActive() && IsInsideObjective(killer)) || killed->IsCreature())
        {
            HandleKillImpl(killer, killed);
        }
    }
}
References ASSERT, Player::GetGroup(), HandleKillImpl(), Player::IsAtGroupRewardDistance(), Object::IsCreature(), IsInsideObjective(), Player::IsOutdoorPvPActive(), and GroupReference::next().
HandleKillImpl()
virtual void OutdoorPvP::HandleKillImpl (Player * , Unit *) inline virtual
Reimplemented in OutdoorPvPHP, OutdoorPvPNA, and OutdoorPvPZM.
{}
Referenced by HandleKill().
HandleOpenGo()
bool OutdoorPvP::HandleOpenGo (Player * player, GameObject * go) virtual
{
    for (auto& capturePoint : _capturePoints)
        if (capturePoint.second->HandleOpenGo(player, go) >= 0)
            return true;
    return false;
}
References _capturePoints.
HandlePlayerEnterZone()
void OutdoorPvP::HandlePlayerEnterZone (Player * player, uint32 zone) protected virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{
    _players[player->GetTeamId()].insert(player->GetGUID());
}
References _players, Object::GetGUID(), and Player::GetTeamId().
Referenced by OutdoorPvPEP::HandlePlayerEnterZone(), OutdoorPvPHP::HandlePlayerEnterZone(), OutdoorPvPNA::HandlePlayerEnterZone(), OutdoorPvPSI::HandlePlayerEnterZone(), OutdoorPvPTF::HandlePlayerEnterZone(), and OutdoorPvPZM::HandlePlayerEnterZone().
HandlePlayerLeaveZone()
void OutdoorPvP::HandlePlayerLeaveZone (Player * player, uint32 zone) protected virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{
    // inform the objectives of the leaving
    for (auto& _capturePoint : _capturePoints)
    {
        _capturePoint.second->HandlePlayerLeave(player);
    }
    // remove the world state information from the player (we can't keep everyone up to date, so leave out those who are not in the concerning zones)
    if (!player->GetSession()->PlayerLogout())
    {
        SendRemoveWorldStates(player);
    }
    _players[player->GetTeamId()].erase(player->GetGUID());
    LOG_DEBUG("outdoorpvp", "OutdoorPvP: Player {} left an outdoorpvp zone", player->GetName());
}
References _capturePoints, _players, Object::GetGUID(), WorldObject::GetName(), Player::GetSession(), Player::GetTeamId(), LOG_DEBUG, WorldSession::PlayerLogout(), and SendRemoveWorldStates().
Referenced by OutdoorPvPEP::HandlePlayerLeaveZone(), OutdoorPvPHP::HandlePlayerLeaveZone(), OutdoorPvPNA::HandlePlayerLeaveZone(), OutdoorPvPSI::HandlePlayerLeaveZone(), OutdoorPvPTF::HandlePlayerLeaveZone(), and OutdoorPvPZM::HandlePlayerLeaveZone().
HandlePlayerResurrects()
void OutdoorPvP::HandlePlayerResurrects (Player * player, uint32 zone) protected virtual
{
}
HasPlayer()
bool OutdoorPvP::HasPlayer (Player const * player) const protected
{
    PlayerSet const& plSet = _players[player->GetTeamId()];
    return plSet.find(player->GetGUID()) != plSet.end();
}
References _players, Object::GetGUID(), and Player::GetTeamId().
IsInsideObjective()
bool OutdoorPvP::IsInsideObjective (Player * player) const
{
    for (auto& capturePoint : _capturePoints)
        if (capturePoint.second->IsInsideObjective(player))
            return true;
    return false;
}
References _capturePoints.
Referenced by HandleKill().
OnCreatureCreate()
void OutdoorPvP::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from ZoneScript.
{
    CreatureScriptPair sp(creature->GetGUID().GetCounter(), creature);
    _creatureScriptStore.insert(sp);
}
References _creatureScriptStore, ObjectGuid::GetCounter(), and Object::GetGUID().
OnCreatureRemove()
void OutdoorPvP::OnCreatureRemove (Creature * creature) override virtual
Reimplemented from ZoneScript.
{
    _creatureScriptStore.erase(creature->GetGUID().GetCounter());
}
References _creatureScriptStore, ObjectGuid::GetCounter(), and Object::GetGUID().
OnGameObjectCreate()
void OutdoorPvP::OnGameObjectCreate (GameObject * go) override virtual
Reimplemented from ZoneScript.
{
    GoScriptPair sp(go->GetGUID().GetCounter(), go);
    _goScriptStore.insert(sp);
    if (go->GetGoType() != GAMEOBJECT_TYPE_CAPTURE_POINT)
    {
        return;
    }
    if (OPvPCapturePoint* cp = GetCapturePoint(go->GetSpawnId()))
    {
        cp->_capturePoint = go;
    }
}
References _goScriptStore, GAMEOBJECT_TYPE_CAPTURE_POINT, GetCapturePoint(), ObjectGuid::GetCounter(), GameObject::GetGoType(), Object::GetGUID(), and GameObject::GetSpawnId().
OnGameObjectRemove()
void OutdoorPvP::OnGameObjectRemove (GameObject * go) override virtual
Reimplemented from ZoneScript.
{
    _goScriptStore.erase(go->GetGUID().GetCounter());
    if (go->GetGoType() != GAMEOBJECT_TYPE_CAPTURE_POINT)
    {
        return;
    }
    if (OPvPCapturePoint* cp = GetCapturePoint(go->GetSpawnId()))
    {
        cp->_capturePoint = nullptr;
    }
}
References _goScriptStore, GAMEOBJECT_TYPE_CAPTURE_POINT, GetCapturePoint(), ObjectGuid::GetCounter(), GameObject::GetGoType(), Object::GetGUID(), and GameObject::GetSpawnId().
RegisterZone()
void OutdoorPvP::RegisterZone (uint32 zoneid) protected
{
    sOutdoorPvPMgr->AddZone(zoneId, this);
}
References sOutdoorPvPMgr.
Referenced by OutdoorPvPEP::SetupOutdoorPvP(), OutdoorPvPGH::SetupOutdoorPvP(), OutdoorPvPHP::SetupOutdoorPvP(), OutdoorPvPNA::SetupOutdoorPvP(), OutdoorPvPSI::SetupOutdoorPvP(), OutdoorPvPTF::SetupOutdoorPvP(), and OutdoorPvPZM::SetupOutdoorPvP().
SendRemoveWorldStates()
virtual void OutdoorPvP::SendRemoveWorldStates (Player *) inline protected virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPGH, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{} // world state stuff
Referenced by HandlePlayerLeaveZone().
SendUpdateWorldState()
void OutdoorPvP::SendUpdateWorldState (uint32 field, uint32 value)
{
    if (_sendUpdate)
        for (auto const& _player : _players)
            for (auto itr : _player)
                if (Player* const player = ObjectAccessor::FindPlayer(itr))
                    player->SendUpdateWorldState(field, value);
}
References _players, _sendUpdate, and ObjectAccessor::FindPlayer().
Referenced by OPvPCapturePointHP::ChangeState(), OPvPCapturePointNA::FactionTakeOver(), OutdoorPvPTF::ResetZoneToTeamControlled(), OutdoorPvPEP::Update(), OutdoorPvPHP::Update(), OPvPCapturePointNA::Update(), OutdoorPvPTF::Update(), OPvPCapturePointNA::UpdateHalaaWorldState(), OPvPCapturePointEP_EWT::UpdateTowerState(), OPvPCapturePointEP_NPT::UpdateTowerState(), OPvPCapturePointEP_CGT::UpdateTowerState(), OPvPCapturePointEP_PWT::UpdateTowerState(), OPvPCapturePointTF::UpdateTowerState(), OPvPCapturePointZM_Beacon::UpdateTowerState(), OPvPCapturePointZM_GraveYard::UpdateTowerState(), OutdoorPvPSI::UpdateWorldState(), and OPvPCapturePointNA::UpdateWyvernRoostWorldState().
SetMapFromZone()
void OutdoorPvP::SetMapFromZone (uint32 zone) protected
{
    AreaTableEntry const* areaTable = sAreaTableStore.LookupEntry(zone);
    ASSERT(areaTable);
    Map* map = sMapMgr->CreateBaseMap(areaTable->mapid);
    ASSERT(!map->Instanceable());
    _map = map;
}
References _map, ASSERT, Map::Instanceable(), AreaTableEntry::mapid, sAreaTableStore, and sMapMgr.
Referenced by OutdoorPvPEP::SetupOutdoorPvP(), OutdoorPvPGH::SetupOutdoorPvP(), OutdoorPvPHP::SetupOutdoorPvP(), OutdoorPvPNA::SetupOutdoorPvP(), OutdoorPvPSI::SetupOutdoorPvP(), OutdoorPvPTF::SetupOutdoorPvP(), and OutdoorPvPZM::SetupOutdoorPvP().
SetupOutdoorPvP()
virtual bool OutdoorPvP::SetupOutdoorPvP () inline virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPGH, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{return true;}
TeamApplyBuff()
void OutdoorPvP::TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2 = 0, Player * sameMapPlr = nullptr)
{
    TeamCastSpell(teamId, (int32)spellId, sameMapPlr);
    TeamCastSpell(teamId == TEAM_ALLIANCE ? TEAM_HORDE : TEAM_ALLIANCE, spellId2 ? -(int32)spellId2 : -(int32)spellId, sameMapPlr);
}
References TEAM_ALLIANCE, TEAM_HORDE, and TeamCastSpell().
Referenced by OPvPCapturePointNA::FactionTakeOver(), OutdoorPvPSI::HandleAreaTrigger(), OPvPCapturePointZM_GraveYard::HandleOpenGo(), OutdoorPvPHP::Update(), and OutdoorPvPTF::Update().
TeamCastSpell()
void OutdoorPvP::TeamCastSpell (TeamId team, int32 spellId, Player * sameMapPlr = nullptr) protected
{
    if (spellId > 0)
    {
        for (auto itr : _players[team])
            if (Player* const player = ObjectAccessor::FindPlayer(itr))
                if (!sameMapPlr || sameMapPlr->FindMap() == player->FindMap())
                    player->CastSpell(player, (uint32)spellId, true);
    }
    else
    {
        for (auto itr : _players[team])
            if (Player* const player = ObjectAccessor::FindPlayer(itr))
                if (!sameMapPlr || sameMapPlr->FindMap() == player->FindMap())
                    player->RemoveAura((uint32) - spellId); // by stack?
    }
}
References _players, WorldObject::FindMap(), and ObjectAccessor::FindPlayer().
Referenced by TeamApplyBuff(), OutdoorPvPHP::Update(), and OutdoorPvPTF::Update().
Update()
bool OutdoorPvP::Update (uint32 diff) virtual
Reimplemented in OutdoorPvPEP, OutdoorPvPHP, OutdoorPvPNA, OutdoorPvPSI, OutdoorPvPTF, and OutdoorPvPZM.
{
    bool objective_changed = false;
    for (auto& capturePoint : _capturePoints)
    {
        if (capturePoint.second->Update(diff))
            objective_changed = true;
    }
    return objective_changed;
}
References _capturePoints.
Referenced by OutdoorPvPEP::Update(), OutdoorPvPHP::Update(), OutdoorPvPTF::Update(), and OutdoorPvPZM::Update().
Friends And Related Function Documentation
OutdoorPvPMgr
friend class OutdoorPvPMgr friend
Member Data Documentation
_capturePoints
OPvPCapturePointMap OutdoorPvP::_capturePoints protected
Referenced by AddCapturePoint(), CanTalkTo(), DeleteSpawns(), OutdoorPvPEP::FillInitialWorldStates(), OutdoorPvPHP::FillInitialWorldStates(), OutdoorPvPTF::FillInitialWorldStates(), OutdoorPvPZM::FillInitialWorldStates(), GetCapturePoint(), HandleCustomSpell(), HandleDropFlag(), HandleGossipOption(), HandleOpenGo(), HandlePlayerLeaveZone(), IsInsideObjective(), OutdoorPvPTF::ResetZoneToTeamControlled(), and Update().
_creatureScriptStore
std::unordered_map<ObjectGuid::LowType, Creature*> OutdoorPvP::_creatureScriptStore protected
Referenced by DeleteSpawns(), OnCreatureCreate(), and OnCreatureRemove().
_goScriptStore
std::unordered_map<ObjectGuid::LowType, GameObject*> OutdoorPvP::_goScriptStore protected
Referenced by DeleteSpawns(), OnGameObjectCreate(), and OnGameObjectRemove().
_map
Map* OutdoorPvP::_map {} protected
Referenced by GetMap(), and SetMapFromZone().
_players
std::array<PlayerSet, 2> OutdoorPvP::_players protected
Referenced by BroadcastPacket(), OutdoorPvPEP::BuffTeams(), HandlePlayerEnterZone(), HandlePlayerLeaveZone(), HasPlayer(), SendUpdateWorldState(), and TeamCastSpell().
_sendUpdate
bool OutdoorPvP::_sendUpdate { true } protected
Referenced by SendUpdateWorldState().
_typeId
uint32 OutdoorPvP::_typeId {} protected
Referenced by GetTypeId(), OutdoorPvPEP::OutdoorPvPEP(), OutdoorPvPGH::OutdoorPvPGH(), OutdoorPvPHP::OutdoorPvPHP(), OutdoorPvPNA::OutdoorPvPNA(), OutdoorPvPSI::OutdoorPvPSI(), OutdoorPvPTF::OutdoorPvPTF(), and OutdoorPvPZM::OutdoorPvPZM().