AzerothCore: achievement_split_personality Class Reference
achievement_split_personality Class Reference
Public Member Functions
achievement_split_personality ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
virtual bool OnCheck (Player *, Unit *, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_split_personality()
achievement_split_personality::achievement_split_personality () inline
                                    : AchievementCriteriaScript("achievement_split_personality")
    {
    }
Member Function Documentation
OnCheck()
bool achievement_split_personality::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
    {
        if (!target)
            return false;
        return target->GetAI()->GetData(target->GetEntry());
    }
References Unit::GetAI(), UnitAI::GetData(), and Object::GetEntry().