AzeorthCore: instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript Struct Reference
instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript Struct Reference
Public Member Functions
instance_sethekk_halls_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
std::string GetSaveData () override
void Load (const char *strIn) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 AnzuEncounter
ObjectGuid m_uiIkissDoorGUID
ObjectGuid _talonKingsCofferGUID
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Constructor & Destructor Documentation
instance_sethekk_halls_InstanceMapScript()
instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::instance_sethekk_halls_InstanceMapScript (Map * map) inline
: InstanceScript(map) {}
Member Function Documentation
GetSaveData()
std::string instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
        {
            OUT_SAVE_INST_DATA;
            std::ostringstream saveStream;
            saveStream << "S H " << AnzuEncounter;
            OUT_SAVE_INST_DATA_COMPLETE;
            return saveStream.str();
        }
References AnzuEncounter, OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Initialize()
void instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            AnzuEncounter = NOT_STARTED;
        }
References AnzuEncounter, and NOT_STARTED.
Load()
void instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::Load (const char * strIn) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!strIn)
            {
                OUT_LOAD_INST_DATA_FAIL;
                return;
            }
            OUT_LOAD_INST_DATA(strIn);
            char dataHead1, dataHead2;
            std::istringstream loadStream(strIn);
            loadStream >> dataHead1 >> dataHead2;
            if (dataHead1 == 'S' && dataHead2 == 'H')
            {
                loadStream >> AnzuEncounter;
                if (AnzuEncounter == IN_PROGRESS)
                    AnzuEncounter = NOT_STARTED;
            }
            OUT_LOAD_INST_DATA_COMPLETE;
        }
References AnzuEncounter, IN_PROGRESS, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            if (creature->GetEntry() == NPC_ANZU || creature->GetEntry() == NPC_VOICE_OF_THE_RAVEN_GOD)
                if (AnzuEncounter >= IN_PROGRESS)
                    creature->DespawnOrUnsummon(1);
        }
References AnzuEncounter, Creature::DespawnOrUnsummon(), Object::GetEntry(), IN_PROGRESS, NPC_ANZU, and NPC_VOICE_OF_THE_RAVEN_GOD.
OnGameObjectCreate()
void instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_IKISS_DOOR:
                    m_uiIkissDoorGUID = go->GetGUID();
                    break;
                case GO_THE_TALON_KINGS_COFFER:
                    _talonKingsCofferGUID = go->GetGUID();
                    break;
            }
        }
References _talonKingsCofferGUID, Object::GetEntry(), Object::GetGUID(), GO_IKISS_DOOR, GO_THE_TALON_KINGS_COFFER, and m_uiIkissDoorGUID.
SetData()
void instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_IKISSDOOREVENT:
                    if (data == DONE)
                    {
                        DoUseDoorOrButton(m_uiIkissDoorGUID, DAY * IN_MILLISECONDS);
                        if (GameObject* coffer = instance->GetGameObject(_talonKingsCofferGUID))
                            coffer->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE | GO_FLAG_INTERACT_COND);
                    }
                    break;
                case TYPE_ANZU_ENCOUNTER:
                    AnzuEncounter = data;
                    SaveToDB();
                    break;
            }
        }
References _talonKingsCofferGUID, AnzuEncounter, DATA_IKISSDOOREVENT, DAY, DONE, InstanceScript::DoUseDoorOrButton(), Map::GetGameObject(), GO_FLAG_INTERACT_COND, GO_FLAG_NOT_SELECTABLE, IN_MILLISECONDS, InstanceScript::instance, m_uiIkissDoorGUID, InstanceScript::SaveToDB(), and TYPE_ANZU_ENCOUNTER.
Member Data Documentation
_talonKingsCofferGUID
ObjectGuid instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::_talonKingsCofferGUID
Referenced by OnGameObjectCreate(), and SetData().
AnzuEncounter
uint32 instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::AnzuEncounter
Referenced by GetSaveData(), Initialize(), Load(), OnCreatureCreate(), and SetData().
m_uiIkissDoorGUID
ObjectGuid instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::m_uiIkissDoorGUID
Referenced by OnGameObjectCreate(), and SetData().