AzerothCore: PvPDifficultyEntry Struct Reference
PvPDifficultyEntry Struct Reference
#include "DBCStructure.h"
Public Member Functions
PvPDifficultyEntry (uint32 mapId, uint32 bracketId, uint32 minLevel, uint32 maxLevel, uint32 difficulty)
BattlegroundBracketId GetBracketId () const
Public Attributes
uint32 mapId
uint32 bracketId
uint32 minLevel
uint32 maxLevel
uint32 difficulty
Detailed Description
Constructor & Destructor Documentation
PvPDifficultyEntry()
PvPDifficultyEntry::PvPDifficultyEntry (uint32 mapId, uint32 bracketId, uint32 minLevel, uint32 maxLevel, uint32 difficulty) inline
: mapId(mapId), bracketId(bracketId), minLevel(minLevel), maxLevel(maxLevel), difficulty(difficulty) {}
Member Function Documentation
GetBracketId()
BattlegroundBracketId PvPDifficultyEntry::GetBracketId () const inline
{ return BattlegroundBracketId(bracketId); }
References bracketId.
Referenced by BattlegroundQueue::AddGroup(), BattlegroundMgr::CreateNewBattleground(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), BattlegroundQueue::SendJoinMessageArenaQueue(), BattlegroundQueue::SendMessageBGQueue(), and Battleground::SetBracket().
Member Data Documentation
bracketId
uint32 PvPDifficultyEntry::bracketId
Referenced by GetBracketId().
difficulty
uint32 PvPDifficultyEntry::difficulty
Referenced by MapInstanced::CreateBattleground().
mapId
uint32 PvPDifficultyEntry::mapId
Referenced by Group::CanJoinBattlegroundQueue().
maxLevel
uint32 PvPDifficultyEntry::maxLevel
Referenced by BattlegroundQueue::BattlegroundQueueAnnouncerUpdate(), GetBattlegroundBracketByLevel(), GetMinPlayersPerTeam(), BattlegroundQueue::SendJoinMessageArenaQueue(), BattlegroundQueue::SendMessageBGQueue(), and Battleground::SetBracket().
minLevel
uint32 PvPDifficultyEntry::minLevel
Referenced by BattlegroundQueue::BattlegroundQueueAnnouncerUpdate(), BattlegroundMgr::CreateNewBattleground(), GetMinPlayersPerTeam(), BattlegroundQueue::SendJoinMessageArenaQueue(), BattlegroundQueue::SendMessageBGQueue(), and Battleground::SetBracket().