AzerothCore: instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript Struct Reference
instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript Struct Reference
Public Member Functions
instance_serpentshrine_cavern_InstanceMapScript (Map *map)
void Initialize () override
bool SetBossState (uint32 type, EncounterState state) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
ObjectGuid GetGuidData (uint32 identifier) const override
void SetData (uint32 type, uint32) override
uint32 GetData (uint32 type) const override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid LadyVashjGUID
ObjectGuid ShieldGeneratorGUID [4]
ObjectGuid LurkerBelowGUID
ObjectGuid LeotherasTheBlindGUID
int32 AliveKeepersCount
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_serpentshrine_cavern_InstanceMapScript()
instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::instance_serpentshrine_cavern_InstanceMapScript (Map * map) inline
                                                                  : InstanceScript(map)
        {
        }
Member Function Documentation
GetData()
uint32 instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == DATA_ALIVE_KEEPERS)
                return AliveKeepersCount;
            return 0;
        }
References AliveKeepersCount, and DATA_ALIVE_KEEPERS.
GetGuidData()
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::GetGuidData (uint32 identifier) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (identifier)
            {
                case NPC_THE_LURKER_BELOW:
                    return LurkerBelowGUID;
                case NPC_LEOTHERAS_THE_BLIND:
                    return LeotherasTheBlindGUID;
                case NPC_LADY_VASHJ:
                    return LadyVashjGUID;
            }
            return ObjectGuid::Empty;
        }
References ObjectGuid::Empty, LadyVashjGUID, LeotherasTheBlindGUID, LurkerBelowGUID, NPC_LADY_VASHJ, NPC_LEOTHERAS_THE_BLIND, and NPC_THE_LURKER_BELOW.
Initialize()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTERS);
            LoadDoorData(doorData);
            AliveKeepersCount = 0;
        }
References AliveKeepersCount, DataHeader, doorData, InstanceScript::LoadDoorData(), MAX_ENCOUNTERS, InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
OnCreatureCreate()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_COILFANG_SHATTERER:
                case NPC_COILFANG_PRIESTESS:
                    if (creature->GetPositionX() > -110.0f && creature->GetPositionX() < 155.0f && creature->GetPositionY() > -610.0f && creature->GetPositionY() < -280.0f)
                        AliveKeepersCount += creature->IsAlive() ? 0 : -1; // SmartAI calls JUST_RESPAWNED in AIInit...
                    break;
                case NPC_THE_LURKER_BELOW:
                    LurkerBelowGUID = creature->GetGUID();
                    break;
                case NPC_LEOTHERAS_THE_BLIND:
                    LeotherasTheBlindGUID = creature->GetGUID();
                    break;
                case NPC_CYCLONE_KARATHRESS:
                    creature->GetMotionMaster()->MoveRandom(50.0f);
                    break;
                case NPC_LADY_VASHJ:
                    LadyVashjGUID = creature->GetGUID();
                    break;
                case NPC_ENCHANTED_ELEMENTAL:
                case NPC_COILFANG_ELITE:
                case NPC_COILFANG_STRIDER:
                case NPC_TAINTED_ELEMENTAL:
                    if (Creature* vashj = instance->GetCreature(LadyVashjGUID))
                        vashj->AI()->JustSummoned(creature);
                    break;
            }
        }
References AliveKeepersCount, Map::GetCreature(), Object::GetEntry(), Object::GetGUID(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), InstanceScript::instance, Unit::IsAlive(), LadyVashjGUID, LeotherasTheBlindGUID, LurkerBelowGUID, MotionMaster::MoveRandom(), NPC_COILFANG_ELITE, NPC_COILFANG_PRIESTESS, NPC_COILFANG_SHATTERER, NPC_COILFANG_STRIDER, NPC_CYCLONE_KARATHRESS, NPC_ENCHANTED_ELEMENTAL, NPC_LADY_VASHJ, NPC_LEOTHERAS_THE_BLIND, NPC_TAINTED_ELEMENTAL, and NPC_THE_LURKER_BELOW.
OnGameObjectCreate()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_LADY_VASHJ_BRIDGE_CONSOLE:
                case GO_COILFANG_BRIDGE1:
                case GO_COILFANG_BRIDGE2:
                case GO_COILFANG_BRIDGE3:
                    AddDoor(go, true);
                    break;
                case GO_SHIELD_GENERATOR1:
                case GO_SHIELD_GENERATOR2:
                case GO_SHIELD_GENERATOR3:
                case GO_SHIELD_GENERATOR4:
                    ShieldGeneratorGUID[go->GetEntry() - GO_SHIELD_GENERATOR1] = go->GetGUID();
                    break;
            }
        }
References InstanceScript::AddDoor(), Object::GetEntry(), Object::GetGUID(), GO_COILFANG_BRIDGE1, GO_COILFANG_BRIDGE2, GO_COILFANG_BRIDGE3, GO_LADY_VASHJ_BRIDGE_CONSOLE, GO_SHIELD_GENERATOR1, GO_SHIELD_GENERATOR2, GO_SHIELD_GENERATOR3, GO_SHIELD_GENERATOR4, and ShieldGeneratorGUID.
OnGameObjectRemove()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_LADY_VASHJ_BRIDGE_CONSOLE:
                case GO_COILFANG_BRIDGE1:
                case GO_COILFANG_BRIDGE2:
                case GO_COILFANG_BRIDGE3:
                    AddDoor(go, false);
                    break;
            }
        }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_COILFANG_BRIDGE1, GO_COILFANG_BRIDGE2, GO_COILFANG_BRIDGE3, and GO_LADY_VASHJ_BRIDGE_CONSOLE.
SetBossState()
bool instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            if (type == DATA_LADY_VASHJ)
                for (uint8 i = 0; i < 4; ++i)
                    if (GameObject* gobject = instance->GetGameObject(ShieldGeneratorGUID[i]))
                        gobject->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
            return true;
        }
References DATA_LADY_VASHJ, Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::instance, InstanceScript::SetBossState(), and ShieldGeneratorGUID.
Referenced by SetData().
SetData()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::SetData (uint32 type, uint32) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_PLATFORM_KEEPER_RESPAWNED:
                    ++AliveKeepersCount;
                    break;
                case DATA_PLATFORM_KEEPER_DIED:
                    --AliveKeepersCount;
                    break;
                case DATA_BRIDGE_ACTIVATED:
                    SetBossState(DATA_BRIDGE_EMERGED, NOT_STARTED);
                    SetBossState(DATA_BRIDGE_EMERGED, DONE);
                    break;
                case DATA_ACTIVATE_SHIELD:
                    if (Creature* vashj = instance->GetCreature(LadyVashjGUID))
                        for (uint8 i = 0; i < 4; ++i)
                            if (GameObject* gobject = instance->GetGameObject(ShieldGeneratorGUID[i]))
{
                                gobject->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                vashj->SummonTrigger(gobject->GetPositionX(), gobject->GetPositionY(), gobject->GetPositionZ(), 0.0f, 0);
                            }
                    break;
            }
        }
References AliveKeepersCount, DATA_ACTIVATE_SHIELD, DATA_BRIDGE_ACTIVATED, DATA_BRIDGE_EMERGED, DATA_PLATFORM_KEEPER_DIED, DATA_PLATFORM_KEEPER_RESPAWNED, DONE, Map::GetCreature(), Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::instance, LadyVashjGUID, NOT_STARTED, SetBossState(), and ShieldGeneratorGUID.
Member Data Documentation
AliveKeepersCount
int32 instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::AliveKeepersCount private
Referenced by GetData(), Initialize(), OnCreatureCreate(), and SetData().
LadyVashjGUID
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::LadyVashjGUID private
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().
LeotherasTheBlindGUID
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::LeotherasTheBlindGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
LurkerBelowGUID
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::LurkerBelowGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
ShieldGeneratorGUID
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::ShieldGeneratorGUID[4] private
Referenced by OnGameObjectCreate(), SetBossState(), and SetData().