AzerothCore: SuckBackEvent Class Reference
SuckBackEvent Class Reference
Public Member Functions
SuckBackEvent (Creature &owner, uint32 action)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature & _owner
uint32 _action
Detailed Description
Constructor & Destructor Documentation
SuckBackEvent()
SuckBackEvent::SuckBackEvent (Creature & owner, uint32 action) inline
: BasicEvent(), _owner(owner), _action(action) { }
Member Function Documentation
Execute()
bool SuckBackEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        if (_owner.IsSummon())
            if (Unit* summoner = _owner.ToTempSummon()->GetSummonerUnit())
            {
                summoner->GetAI()->DoAction(_action);
                _owner.SetStandState(UNIT_STAND_STATE_SUBMERGED);
                _owner.DespawnOrUnsummon(200);
            }
        return true;
    }
References _action, _owner, Creature::DespawnOrUnsummon(), TempSummon::GetSummonerUnit(), Unit::IsSummon(), Unit::SetStandState(), Unit::ToTempSummon(), and UNIT_STAND_STATE_SUBMERGED.
Member Data Documentation
_action
uint32 SuckBackEvent::_action private
Referenced by Execute().
_owner
Creature& SuckBackEvent::_owner private
Referenced by Execute().