AzerothCore: boss_volazj Struct Reference
boss_volazj Struct Reference
Public Member Functions
boss_volazj (Creature *pCreature)
void InitializeAI () override
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void SetData (uint32 type, uint32 value) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Member Functions
uint32 GetPlrInsanityAuraId (uint32 phaseMask) const
void ResetPlayersPhaseMask ()
bool CheckPhaseMinions ()
Private Attributes
uint8 insanityTimes
bool insanityPhase
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_volazj()
boss_volazj::boss_volazj (Creature * pCreature) inline
                                     : BossAI(pCreature, DATA_HERALD_VOLAZJ),
        insanityTimes(0),
        insanityPhase(false)
        { }
Member Function Documentation
CheckPhaseMinions()
bool boss_volazj::CheckPhaseMinions () inline private
    {
        summons.RemoveNotExisting();
        if (summons.empty())
        {
            ResetPlayersPhaseMask();
            return true;
        }
        uint32 phase = 1;
        for (ObjectGuid const& summonGUID : summons)
        {
            if (Creature* summon = ObjectAccessor::GetCreature(*me, summonGUID))
            {
                phase |= summon->GetPhaseMask();
            }
        }
        Map::PlayerList const& players = me->GetMap()->GetPlayers();
        for (auto const& i : players)
        {
            Player* pPlayer = i.GetSource();
            if (pPlayer && !(pPlayer->GetPhaseMask() & phase))
            {
                pPlayer->RemoveAurasDueToSpell(GetPlrInsanityAuraId(pPlayer->GetPhaseMask()));
            }
        }
        return false;
    }
References SummonList::empty(), ObjectAccessor::GetCreature(), WorldObject::GetMap(), WorldObject::GetPhaseMask(), Map::GetPlayers(), GetPlrInsanityAuraId(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SummonList::RemoveNotExisting(), ResetPlayersPhaseMask(), and BossAI::summons.
Referenced by UpdateAI().
DamageTaken()
void boss_volazj::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
    {
        // Do not perform insanity recast if boss is casting Insanity already
        if (me->FindCurrentSpellBySpellId(SPELL_INSANITY))
        {
            return;
        }
        // First insanity
        if (insanityTimes == 0 && me->HealthBelowPctDamaged(66, damage))
        {
            DoCastSelf(SPELL_INSANITY, false);
            ++insanityTimes;
        }
        // Second insanity
        else if (insanityTimes == 1 && me->HealthBelowPctDamaged(33, damage))
        {
            me->InterruptNonMeleeSpells(false);
            DoCastSelf(SPELL_INSANITY, false);
            ++insanityTimes;
        }
    }
References UnitAI::DoCastSelf(), Unit::FindCurrentSpellBySpellId(), Unit::HealthBelowPctDamaged(), insanityTimes, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, and SPELL_INSANITY.
GetPlrInsanityAuraId()
uint32 boss_volazj::GetPlrInsanityAuraId (uint32 phaseMask) const inline private
    {
        switch (phaseMask)
        {
            case 16:
                return SPELL_INSANITY_PHASING_1;
            case 32:
                return SPELL_INSANITY_PHASING_2;
            case 64:
                return SPELL_INSANITY_PHASING_3;
            case 128:
                return SPELL_INSANITY_PHASING_4;
            case 256:
                return SPELL_INSANITY_PHASING_5;
        }
        return 0;
    }
References SPELL_INSANITY_PHASING_1, SPELL_INSANITY_PHASING_2, SPELL_INSANITY_PHASING_3, SPELL_INSANITY_PHASING_4, and SPELL_INSANITY_PHASING_5.
Referenced by CheckPhaseMinions(), and ResetPlayersPhaseMask().
InitializeAI()
void boss_volazj::InitializeAI () inline override virtual
Reimplemented from UnitAI.
    {
        BossAI::InitializeAI();
        // Visible for all players in insanity
        me->SetPhaseMask((1 | 16 | 32 | 64 | 128 | 256), true);
    }
References UnitAI::InitializeAI(), ScriptedAI::me, and Unit::SetPhaseMask().
JustDied()
void boss_volazj::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
    {
        _JustDied();
        me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        me->SetControlled(false, UNIT_STATE_STUNNED);
        ResetPlayersPhaseMask();
        switch (urand(0, 1))
        {
            case 0:
            {
                Talk(SAY_DEATH_1);
                DoCastSelf(SPELL_WHISPER_DEATH_1, true);
                break;
            }
            case 1:
            {
                Talk(SAY_DEATH_2);
                DoCastSelf(SPELL_WHISPER_DEATH_2, true);
                break;
            }
        }
    }
References BossAI::_JustDied(), UnitAI::DoCastSelf(), ScriptedAI::me, Unit::RemoveUnitFlag(), ResetPlayersPhaseMask(), SAY_DEATH_1, SAY_DEATH_2, Unit::SetControlled(), SPELL_WHISPER_DEATH_1, SPELL_WHISPER_DEATH_2, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_STUNNED, and urand().
JustEngagedWith()
void boss_volazj::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        _JustEngagedWith();
        events.ScheduleEvent(EVENT_HERALD_MIND_FLAY, 8s);
        events.ScheduleEvent(EVENT_HERALD_SHADOW, 5s);
        events.ScheduleEvent(EVENT_HERALD_SHIVER, 15s);
        Talk(SAY_AGGRO);
        DoCastSelf(SPELL_WHISPER_AGGRO);
        instance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_QUICK_DEMISE_START_EVENT);
        me->SetInCombatWithZone();
    }
References BossAI::_JustEngagedWith(), ACHIEV_QUICK_DEMISE_START_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, UnitAI::DoCastSelf(), InstanceScript::DoStartTimedAchievement(), EVENT_HERALD_MIND_FLAY, EVENT_HERALD_SHADOW, EVENT_HERALD_SHIVER, BossAI::instance, ScriptedAI::me, SAY_AGGRO, Creature::SetInCombatWithZone(), and SPELL_WHISPER_AGGRO.
KilledUnit()
void boss_volazj::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (victim->IsPlayer())
        {
            switch (urand(0, 2))
            {
                case 0:
                {
                    Talk(SAY_SLAY_1);
                    DoCastSelf(SPELL_WHISPER_SLAY_1);
                    break;
                }
                case 1:
                {
                    Talk(SAY_SLAY_2);
                    DoCastSelf(SPELL_WHISPER_SLAY_2);
                    break;
                }
                case 2:
                {
                    Talk(SAY_SLAY_3);
                    DoCastSelf(SPELL_WHISPER_SLAY_3);
                    break;
                }
            }
        }
    }
References UnitAI::DoCastSelf(), Object::IsPlayer(), SAY_SLAY_1, SAY_SLAY_2, SAY_SLAY_3, SPELL_WHISPER_SLAY_1, SPELL_WHISPER_SLAY_2, SPELL_WHISPER_SLAY_3, and urand().
Reset()
void boss_volazj::Reset () inline override virtual
Reimplemented from BossAI.
    {
        _Reset();
        insanityTimes = 0;
        insanityPhase = false;
        me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        me->SetControlled(false, UNIT_STATE_STUNNED);
        ResetPlayersPhaseMask();
        instance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_QUICK_DEMISE_START_EVENT);
    }
References BossAI::_Reset(), ACHIEV_QUICK_DEMISE_START_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, InstanceScript::DoStopTimedAchievement(), insanityPhase, insanityTimes, BossAI::instance, ScriptedAI::me, Unit::RemoveUnitFlag(), ResetPlayersPhaseMask(), Unit::SetControlled(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_STATE_STUNNED.
ResetPlayersPhaseMask()
void boss_volazj::ResetPlayersPhaseMask () inline private
    {
        Map::PlayerList const& players = me->GetMap()->GetPlayers();
        for (auto const& i : players)
        {
            if (Player* pPlayer = i.GetSource())
            {
                if (uint32 const insanityAura = GetPlrInsanityAuraId(pPlayer->GetPhaseMask()))
                {
                    pPlayer->RemoveAurasDueToSpell(insanityAura);
                }
            }
        }
    }
References WorldObject::GetMap(), Map::GetPlayers(), GetPlrInsanityAuraId(), and ScriptedAI::me.
Referenced by CheckPhaseMinions(), JustDied(), and Reset().
SetData()
void boss_volazj::SetData (uint32 type, uint32 value) inline override virtual
Reimplemented from UnitAI.
    {
        if (type == DATA_SET_INSANITY_PHASE)
        {
            insanityPhase = (value != 0);
        }
    }
References DATA_SET_INSANITY_PHASE, and insanityPhase.
UpdateAI()
void boss_volazj::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
    {
        //Return since we have no target
        if (!UpdateVictim())
        {
            return;
        }
        if (insanityPhase)
        {
            if (!CheckPhaseMinions())
            {
                return;
            }
            insanityPhase = false;
            me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            me->SetControlled(false, UNIT_STATE_STUNNED);
            me->RemoveAurasDueToSpell(INSANITY_VISUAL);
        }
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
        while (uint32 const eventId = events.ExecuteEvent())
        {
            switch (eventId)
            {
                case EVENT_HERALD_MIND_FLAY:
                {
                    DoCastVictim(SPELL_MIND_FLAY, false);
                    events.Repeat(20s);
                    break;
                }
                case EVENT_HERALD_SHADOW:
                {
                    DoCastVictim(SPELL_SHADOW_BOLT_VOLLEY, false);
                    events.Repeat(5s);
                    break;
                }
                case EVENT_HERALD_SHIVER:
                {
                    if (Unit* pTarget = SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true))
                    {
                        DoCast(pTarget, SPELL_SHIVER, false);
                    }
                    events.Repeat(15s);
                    break;
                }
            }
            if (me->HasUnitState(UNIT_STATE_CASTING))
            {
                return;
            }
        }
        DoMeleeAttackIfReady();
    }
References CheckPhaseMinions(), UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EVENT_HERALD_MIND_FLAY, EVENT_HERALD_SHADOW, EVENT_HERALD_SHIVER, Unit::HasUnitState(), INSANITY_VISUAL, insanityPhase, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), Unit::RemoveUnitFlag(), UnitAI::SelectTarget(), Unit::SetControlled(), SPELL_MIND_FLAY, SPELL_SHADOW_BOLT_VOLLEY, SPELL_SHIVER, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_CASTING, UNIT_STATE_STUNNED, and CreatureAI::UpdateVictim().
Member Data Documentation
insanityPhase
bool boss_volazj::insanityPhase private
Referenced by Reset(), SetData(), and UpdateAI().
insanityTimes
uint8 boss_volazj::insanityTimes private
Referenced by DamageTaken(), and Reset().