AzerothCore: MysticBuffetTargetFilter Class Reference
MysticBuffetTargetFilter Class Reference
Public Member Functions
MysticBuffetTargetFilter (Unit *caster)
bool operator() (WorldObject *unit) const
Private Attributes
Unit * _caster
Detailed Description
Constructor & Destructor Documentation
MysticBuffetTargetFilter()
MysticBuffetTargetFilter::MysticBuffetTargetFilter (Unit * caster) inline explicit
: _caster(caster) { }
Member Function Documentation
operator()()
bool MysticBuffetTargetFilter::operator() (WorldObject * unit) const inline
    {
        if (!unit->IsInMap(_caster))
            return true;
        // for standard creatures check full LOS
        if (Creature* c = unit->ToCreature())
            if (!c->IsPet() && c->GetSpawnId())
                return !_caster->IsWithinLOSInMap(unit);
        // for players and pets check only dynamic los (ice block gameobjects)
        float ox, oy, oz;
        _caster->GetPosition(ox, oy, oz);
        DynamicMapTree const& dTree = unit->GetMap()->GetDynamicMapTree();
        return !dTree.isInLineOfSight(unit->GetPositionX(), unit->GetPositionY(), unit->GetPositionZ() + 2.f, ox, oy, oz + 2.f, unit->GetPhaseMask(), VMAP::ModelIgnoreFlags::Nothing);
    }
References _caster, Map::GetDynamicMapTree(), WorldObject::GetMap(), WorldObject::GetPhaseMask(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), DynamicMapTree::isInLineOfSight(), WorldObject::IsInMap(), WorldObject::IsWithinLOSInMap(), VMAP::Nothing, and Object::ToCreature().
Member Data Documentation
_caster
Unit* MysticBuffetTargetFilter::_caster private
Referenced by operator()().