AzerothCore: ADT_file Class Reference
ADT_file Class Reference
#include "adt.h"
Public Member Functions
bool prepareLoadedData () override
ADT_file ()
~ADT_file ()
void free () override
Public Member Functions inherited from FileLoader
virtual bool prepareLoadedData ()
uint8 * GetData ()
uint32 GetDataSize ()
FileLoader ()
~FileLoader ()
bool loadFile (std::string const &filename, bool log=true)
virtual void free ()
virtual bool prepareLoadedData ()
uint8 * GetData ()
uint32 GetDataSize ()
FileLoader ()
~FileLoader ()
bool loadFile (std::string const &filename, bool log=true)
virtual void free ()
Public Attributes
adt_MHDR * a_grid
Public Attributes inherited from FileLoader
file_MVER * version
Detailed Description
Constructor & Destructor Documentation
ADT_file()
ADT_file::ADT_file ()
{
    a_grid = nullptr;
}
References a_grid.
~ADT_file()
ADT_file::~ADT_file ()
{
    free();
}
References free().
Member Function Documentation
free()
void ADT_file::free () override virtual
Reimplemented from FileLoader.
{
    a_grid = nullptr;
    FileLoader::free();
}
References a_grid, and FileLoader::free().
Referenced by ~ADT_file().
prepareLoadedData()
bool ADT_file::prepareLoadedData () override virtual
Reimplemented from FileLoader.
{
    // Check parent
    if (!FileLoader::prepareLoadedData())
        return false;
    // Check and prepare MHDR
    a_grid = (adt_MHDR*)(GetData() + 8 + version->size);
    if (!a_grid->prepareLoadedData())
        return false;
    return true;
}
References a_grid, FileLoader::GetData(), adt_MHDR::prepareLoadedData(), FileLoader::prepareLoadedData(), file_MVER::size, and FileLoader::version.
Member Data Documentation
a_grid
adt_MHDR* ADT_file::a_grid
Referenced by ADT_file(), ConvertADT(), free(), and prepareLoadedData().