AzerothCore: SQLQueryHolderCallback Class Reference
SQLQueryHolderCallback Class Reference
#include "QueryHolder.h"
Public Member Functions
SQLQueryHolderCallback (std::shared_ptr< SQLQueryHolderBase > &&holder, QueryResultHolderFuture &&future)
SQLQueryHolderCallback (SQLQueryHolderCallback &&)=default
SQLQueryHolderCallback & operator= (SQLQueryHolderCallback &&)=default
void AfterComplete (std::function< void(SQLQueryHolderBase const &)> callback) &
bool InvokeIfReady ()
Public Attributes
std::shared_ptr< SQLQueryHolderBase > m_holder
QueryResultHolderFuture m_future
std::function< void(SQLQueryHolderBase const &)> m_callback
Detailed Description
Constructor & Destructor Documentation
SQLQueryHolderCallback() [1/2]
SQLQueryHolderCallback::SQLQueryHolderCallback (std::shared_ptr< SQLQueryHolderBase > && holder, QueryResultHolderFuture && future) inline
        : m_holder(std::move(holder)), m_future(std::move(future)) { }
SQLQueryHolderCallback() [2/2]
SQLQueryHolderCallback::SQLQueryHolderCallback (SQLQueryHolderCallback &&) default
Member Function Documentation
AfterComplete()
void SQLQueryHolderCallback::AfterComplete (std::function< void(SQLQueryHolderBase const &)> callback) & inline
    {
        m_callback = std::move(callback);
    }
Referenced by WorldSession::HandlePlayerLoginOpcode(), WorldSession::InitializeSession(), and Pet::LoadPetFromDB().
InvokeIfReady()
bool SQLQueryHolderCallback::InvokeIfReady ()
{
    if (m_future.valid() && m_future.wait_for(std::chrono::seconds(0)) == std::future_status::ready)
    {
        m_callback(*m_holder);
        return true;
    }
    return false;
}
References m_callback, m_future, and m_holder.
operator=()
SQLQueryHolderCallback & SQLQueryHolderCallback::operator= (SQLQueryHolderCallback &&) default
Member Data Documentation
m_callback
std::function<void(SQLQueryHolderBase const&)> SQLQueryHolderCallback::m_callback
Referenced by InvokeIfReady().
m_future
QueryResultHolderFuture SQLQueryHolderCallback::m_future
Referenced by InvokeIfReady().
m_holder
std::shared_ptr<SQLQueryHolderBase> SQLQueryHolderCallback::m_holder
Referenced by InvokeIfReady().