AzeorthCore: boss_janalai::boss_janalaiAI Struct Reference
boss_janalai::boss_janalaiAI Struct Reference
Public Member Functions
boss_janalaiAI (Creature *creature)
void Reset () override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void EnterCombat (Unit *) override
void DamageDealt (Unit *target, uint32 &damage, DamageEffectType) override
void FireWall ()
void SpawnBombs ()
bool HatchAllEggs (uint32 action)
void Boom ()
void HandleBombSequence ()
void UpdateAI (uint32 diff) override
bool CheckEvadeIfOutOfCombatArea () const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
uint32 FireBreathTimer
uint32 BombTimer
uint32 BombSequenceTimer
uint32 BombCount
uint32 HatcherTimer
uint32 EnrageTimer
bool noeggs
bool enraged
bool isBombing
bool isFlameBreathing
ObjectGuid FireBombGUIDs [40]
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_janalaiAI()
boss_janalai::boss_janalaiAI::boss_janalaiAI (Creature * creature) inline
                                           : ScriptedAI(creature)
        {
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
Boom()
void boss_janalai::boss_janalaiAI::Boom () inline
        {
            std::list<Creature*> templist;
            float x, y, z;
            me->GetPosition(x, y, z);
            Acore::AllCreaturesOfEntryInRange check(me, NPC_FIRE_BOMB, 100);
            Acore::CreatureListSearcher<Acore::AllCreaturesOfEntryInRange> searcher(me, templist, check);
            Cell::VisitGridObjects(me, searcher, me->GetGridActivationRange());
            for (std::list<Creature*>::const_iterator i = templist.begin(); i != templist.end(); ++i)
            {
                (*i)->CastSpell(*i, SPELL_FIRE_BOMB_DAMAGE, true);
                (*i)->RemoveAllAuras();
            }
        }
References WorldObject::GetGridActivationRange(), Position::GetPosition(), ScriptedAI::me, NPC_FIRE_BOMB, SPELL_FIRE_BOMB_DAMAGE, and Cell::VisitGridObjects().
Referenced by HandleBombSequence().
CheckEvadeIfOutOfCombatArea()
bool boss_janalai::boss_janalaiAI::CheckEvadeIfOutOfCombatArea () const inline override virtual
Reimplemented from ScriptedAI.
        {
            return me->GetPositionZ() <= 12.0f;
        }
References Position::GetPositionZ(), and ScriptedAI::me.
DamageDealt()
void boss_janalai::boss_janalaiAI::DamageDealt (Unit * target, uint32 & damage, DamageEffectType) inline override virtual
Reimplemented from UnitAI.
        {
            if (isFlameBreathing)
            {
                if (!me->HasInArc(M_PI / 6, target))
                    damage = 0;
            }
        }
References Position::HasInArc(), isFlameBreathing, and ScriptedAI::me.
EnterCombat()
void boss_janalai::boss_janalaiAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            instance->SetData(DATA_JANALAIEVENT, IN_PROGRESS);
            Talk(SAY_AGGRO);
            //        DoZoneInCombat();
        }
References DATA_JANALAIEVENT, IN_PROGRESS, instance, SAY_AGGRO, and ZoneScript::SetData().
FireWall()
void boss_janalai::boss_janalaiAI::FireWall () inline
        {
            for (uint8 i = 0; i < 4; ++i)
            {
                uint8 WallNum = i == 0 || i == 2 ? 3 : 2;
                for (uint8 j = 0; j < WallNum; j++)
                {
                    Creature* wall = WallNum == 3
                            ? me->SummonCreature(NPC_FIRE_BOMB, FireWallCoords[i][0], FireWallCoords[i][1] + 5 * (j - 1), FireWallCoords[i][2], FireWallCoords[i][3], TEMPSUMMON_TIMED_DESPAWN, 15000)
                            : me->SummonCreature(NPC_FIRE_BOMB, FireWallCoords[i][0] - 2 + 4 * j, FireWallCoords[i][1], FireWallCoords[i][2], FireWallCoords[i][3], TEMPSUMMON_TIMED_DESPAWN, 15000);
                    if (wall)
                    {
                        wall->CastSpell(wall, SPELL_FIRE_WALL, true);
                    }
                }
            }
        }
References Unit::CastSpell(), FireWallCoords, ScriptedAI::me, NPC_FIRE_BOMB, SPELL_FIRE_WALL, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
Referenced by UpdateAI().
HandleBombSequence()
void boss_janalai::boss_janalaiAI::HandleBombSequence () inline
        {
            if (BombCount < 40)
            {
                if (Unit* FireBomb = ObjectAccessor::GetUnit(*me, FireBombGUIDs[BombCount]))
                {
                    FireBomb->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    DoCast(FireBomb, SPELL_FIRE_BOMB_THROW, true);
                    FireBomb->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                }
                ++BombCount;
                if (BombCount == 40)
                {
                    BombSequenceTimer = 5000;
                }
                else BombSequenceTimer = 100;
            }
            else
            {
                Boom();
                isBombing = false;
                BombTimer = urand(20000, 40000);
                me->RemoveAurasDueToSpell(SPELL_FIRE_BOMB_CHANNEL);
                if (EnrageTimer <= 10000)
                    EnrageTimer = 0;
                else
                    EnrageTimer -= 10000;
            }
        }
References BombCount, BombSequenceTimer, BombTimer, Boom(), UnitAI::DoCast(), EnrageTimer, FireBombGUIDs, ObjectAccessor::GetUnit(), isBombing, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SPELL_FIRE_BOMB_CHANNEL, SPELL_FIRE_BOMB_THROW, UNIT_FLAG_NOT_SELECTABLE, and urand().
Referenced by UpdateAI().
HatchAllEggs()
bool boss_janalai::boss_janalaiAI::HatchAllEggs (uint32 action) inline
        {
            std::list<Creature*> templist;
            float x, y, z;
            me->GetPosition(x, y, z);
            Acore::AllCreaturesOfEntryInRange check(me, NPC_EGG, 100);
            Acore::CreatureListSearcher<Acore::AllCreaturesOfEntryInRange> searcher(me, templist, check);
            Cell::VisitGridObjects(me, searcher, me->GetGridActivationRange());
            //LOG_ERROR("scripts", "Eggs {} at middle", templist.size());
            if (templist.empty())
                return false;
            for (std::list<Creature*>::const_iterator i = templist.begin(); i != templist.end(); ++i)
            {
                if (action == 1)
                    (*i)->SetDisplayId(10056);
                else if (action == 2 && (*i)->GetDisplayId() != 11686)
                    (*i)->CastSpell(*i, SPELL_HATCH_EGG, false);
            }
            return true;
        }
References WorldObject::GetGridActivationRange(), Position::GetPosition(), ScriptedAI::me, NPC_EGG, SPELL_HATCH_EGG, and Cell::VisitGridObjects().
Referenced by Reset(), and UpdateAI().
JustDied()
void boss_janalai::boss_janalaiAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_DEATH);
            instance->SetData(DATA_JANALAIEVENT, DONE);
        }
References DATA_JANALAIEVENT, DONE, instance, SAY_DEATH, and ZoneScript::SetData().
KilledUnit()
void boss_janalai::boss_janalaiAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_SLAY);
        }
References SAY_SLAY.
Reset()
void boss_janalai::boss_janalaiAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            instance->SetData(DATA_JANALAIEVENT, NOT_STARTED);
            FireBreathTimer = 8000;
            BombTimer = 30000;
            BombSequenceTimer = 1000;
            BombCount = 0;
            HatcherTimer = 10000;
            EnrageTimer = MINUTE * 5 * IN_MILLISECONDS;
            noeggs = false;
            isBombing = false;
            enraged = false;
            isFlameBreathing = false;
            for (uint8 i = 0; i < 40; ++i)
                FireBombGUIDs[i].Clear();
            HatchAllEggs(1);
        }
References BombCount, BombSequenceTimer, BombTimer, DATA_JANALAIEVENT, enraged, EnrageTimer, FireBombGUIDs, FireBreathTimer, HatchAllEggs(), HatcherTimer, IN_MILLISECONDS, instance, isBombing, isFlameBreathing, MINUTE, noeggs, NOT_STARTED, and ZoneScript::SetData().
SpawnBombs()
void boss_janalai::boss_janalaiAI::SpawnBombs () inline
        {
            float dx, dy;
            for (int i(0); i < 40; ++i)
            {
                dx = float(irand(-area_dx / 2, area_dx / 2));
                dy = float(irand(-area_dy / 2, area_dy / 2));
                Creature* bomb = DoSpawnCreature(NPC_FIRE_BOMB, dx, dy, 0, 0, TEMPSUMMON_TIMED_DESPAWN, 15000);
                if (bomb)
                    FireBombGUIDs[i] = bomb->GetGUID();
            }
            BombCount = 0;
        }
References area_dx, area_dy, BombCount, ScriptedAI::DoSpawnCreature(), FireBombGUIDs, Object::GetGUID(), irand(), NPC_FIRE_BOMB, and TEMPSUMMON_TIMED_DESPAWN.
Referenced by UpdateAI().
UpdateAI()
void boss_janalai::boss_janalaiAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (isFlameBreathing)
            {
                if (!me->IsNonMeleeSpellCast(false))
                    isFlameBreathing = false;
                else
                    return;
            }
            if (isBombing)
            {
                if (BombSequenceTimer <= diff)
                    HandleBombSequence();
                else
                    BombSequenceTimer -= diff;
                return;
            }
            if (!UpdateVictim())
                return;
            //enrage if under 25% hp before 5 min.
            if (!enraged && HealthBelowPct(25))
                EnrageTimer = 0;
            if (EnrageTimer <= diff)
            {
                if (!enraged)
                {
                    DoCast(me, SPELL_ENRAGE, true);
                    enraged = true;
                    EnrageTimer = 300000;
                }
                else
                {
                    Talk(SAY_BERSERK);
                    DoCast(me, SPELL_BERSERK, true);
                    EnrageTimer = 300000;
                }
            }
            else EnrageTimer -= diff;
            if (BombTimer <= diff)
            {
                Talk(SAY_FIRE_BOMBS);
                me->AttackStop();
                me->GetMotionMaster()->Clear();
                me->NearTeleportTo(JanalainPos[0][0], JanalainPos[0][1], JanalainPos[0][2], me->GetOrientation());
                me->StopMovingOnCurrentPos();
                DoCast(me, SPELL_FIRE_BOMB_CHANNEL, false);
                //DoTeleportPlayer(me, JanalainPos[0][0], JanalainPos[0][1], JanalainPos[0][2], 0);
                //DoCast(me, SPELL_TELE_TO_CENTER, true);
                FireWall();
                SpawnBombs();
                isBombing = true;
                BombSequenceTimer = 100;
                //Teleport every Player into the middle
                Map* map = me->GetMap();
                if (!map->IsDungeon())
                    return;
                Map::PlayerList const& PlayerList = map->GetPlayers();
                for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
                    if (Player* i_pl = i->GetSource())
                        if (i_pl->IsAlive())
                            DoTeleportPlayer(i_pl, JanalainPos[0][0] - 5 + rand() % 10, JanalainPos[0][1] - 5 + rand() % 10, JanalainPos[0][2], 0);
                //DoCast(Temp, SPELL_SUMMON_PLAYERS, true) // core bug, spell does not work if too far
                return;
            }
            else BombTimer -= diff;
            if (!noeggs)
            {
                if (HealthBelowPct(35))
                {
                    Talk(SAY_ALL_EGGS);
                    me->AttackStop();
                    me->GetMotionMaster()->Clear();
                    me->NearTeleportTo(JanalainPos[0][0], JanalainPos[0][1], JanalainPos[0][2], me->GetOrientation());
                    me->StopMovingOnCurrentPos();
                    DoCast(me, SPELL_HATCH_ALL, false);
                    HatchAllEggs(2);
                    noeggs = true;
                }
                else if (HatcherTimer <= diff)
                {
                    if (HatchAllEggs(0))
                    {
                        Talk(SAY_SUMMON_HATCHER);
                        me->SummonCreature(NPC_AMANI_HATCHER, hatcherway[0][0][0], hatcherway[0][0][1], hatcherway[0][0][2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 10000);
                        me->SummonCreature(NPC_AMANI_HATCHER, hatcherway[1][0][0], hatcherway[1][0][1], hatcherway[1][0][2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 10000);
                        HatcherTimer = 90000;
                    }
                    else
                        noeggs = true;
                }
                else HatcherTimer -= diff;
            }
            DoMeleeAttackIfReady();
            if (FireBreathTimer <= diff)
            {
                if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
                {
                    me->AttackStop();
                    me->GetMotionMaster()->Clear();
                    DoCast(target, SPELL_FLAME_BREATH, false);
                    me->StopMoving();
                    isFlameBreathing = true;
                }
                FireBreathTimer = 8000;
            }
            else FireBreathTimer -= diff;
        }
References Unit::AttackStop(), MapRefMgr::begin(), BombSequenceTimer, BombTimer, MotionMaster::Clear(), UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoTeleportPlayer(), MapRefMgr::end(), enraged, EnrageTimer, FireBreathTimer, FireWall(), WorldObject::GetMap(), Unit::GetMotionMaster(), Position::GetOrientation(), Map::GetPlayers(), HandleBombSequence(), HatchAllEggs(), HatcherTimer, hatcherway, ScriptedAI::HealthBelowPct(), isBombing, Map::IsDungeon(), isFlameBreathing, Unit::IsNonMeleeSpellCast(), JanalainPos, ScriptedAI::me, Unit::NearTeleportTo(), noeggs, NPC_AMANI_HATCHER, SAY_ALL_EGGS, SAY_BERSERK, SAY_FIRE_BOMBS, SAY_SUMMON_HATCHER, UnitAI::SelectTarget(), SpawnBombs(), SPELL_BERSERK, SPELL_ENRAGE, SPELL_FIRE_BOMB_CHANNEL, SPELL_FLAME_BREATH, SPELL_HATCH_ALL, Unit::StopMoving(), Unit::StopMovingOnCurrentPos(), WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, and CreatureAI::UpdateVictim().
Member Data Documentation
BombCount
uint32 boss_janalai::boss_janalaiAI::BombCount
Referenced by HandleBombSequence(), Reset(), and SpawnBombs().
BombSequenceTimer
uint32 boss_janalai::boss_janalaiAI::BombSequenceTimer
Referenced by HandleBombSequence(), Reset(), and UpdateAI().
BombTimer
uint32 boss_janalai::boss_janalaiAI::BombTimer
Referenced by HandleBombSequence(), Reset(), and UpdateAI().
enraged
bool boss_janalai::boss_janalaiAI::enraged
Referenced by Reset(), and UpdateAI().
EnrageTimer
uint32 boss_janalai::boss_janalaiAI::EnrageTimer
Referenced by HandleBombSequence(), Reset(), and UpdateAI().
FireBombGUIDs
ObjectGuid boss_janalai::boss_janalaiAI::FireBombGUIDs[40]
Referenced by HandleBombSequence(), Reset(), and SpawnBombs().
FireBreathTimer
uint32 boss_janalai::boss_janalaiAI::FireBreathTimer
Referenced by Reset(), and UpdateAI().
HatcherTimer
uint32 boss_janalai::boss_janalaiAI::HatcherTimer
Referenced by Reset(), and UpdateAI().
instance
InstanceScript* boss_janalai::boss_janalaiAI::instance
Referenced by boss_janalaiAI(), EnterCombat(), JustDied(), and Reset().
isBombing
bool boss_janalai::boss_janalaiAI::isBombing
Referenced by HandleBombSequence(), Reset(), and UpdateAI().
isFlameBreathing
bool boss_janalai::boss_janalaiAI::isFlameBreathing
Referenced by DamageDealt(), Reset(), and UpdateAI().
noeggs
bool boss_janalai::boss_janalaiAI::noeggs
Referenced by Reset(), and UpdateAI().