AzerothCore: boss_priestess_delrissa::boss_priestess_delrissaAI Struct Reference
boss_priestess_delrissa::boss_priestess_delrissaAI Struct Reference
Public Member Functions
boss_priestess_delrissaAI (Creature *creature)
void Reset () override
void InitializeAI () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *, Unit *) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void KilledUnit (Unit *victim) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
EventMap events
SummonList summons
uint8 PlayersKilled
uint8 HelpersKilled
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_priestess_delrissaAI()
boss_priestess_delrissa::boss_priestess_delrissaAI::boss_priestess_delrissaAI (Creature * creature) inline
                                                      : ScriptedAI(creature), summons(me)
        {
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
InitializeAI()
void boss_priestess_delrissa::boss_priestess_delrissaAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
        {
            ScriptedAI::InitializeAI();
            std::list<uint32> helpersList;
            for (uint8 i = 0; i < MAX_HELPERS_COUNT; ++i)
                helpersList.push_back(helpersEntries[i]);
            Acore::Containers::RandomResize(helpersList, MAX_ACTIVE_HELPERS);
            uint8 j = 0;
            for (std::list<uint32>::const_iterator itr = helpersList.begin(); itr != helpersList.end(); ++itr, ++j)
                me->SummonCreature(*itr, helpersLocations[j], TEMPSUMMON_MANUAL_DESPAWN, 0);
        }
References helpersEntries, helpersLocations, UnitAI::InitializeAI(), MAX_ACTIVE_HELPERS, MAX_HELPERS_COUNT, ScriptedAI::me, Acore::Containers::RandomResize(), WorldObject::SummonCreature(), and TEMPSUMMON_MANUAL_DESPAWN.
JustDied()
void boss_priestess_delrissa::boss_priestess_delrissaAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_DEATH);
            if (HelpersKilled == MAX_ACTIVE_HELPERS + 1)
                instance->SetData(DATA_DELRISSA_EVENT, DONE);
        }
References DATA_DELRISSA_EVENT, DONE, HelpersKilled, instance, MAX_ACTIVE_HELPERS, SAY_DEATH, and ZoneScript::SetData().
JustEngagedWith()
void boss_priestess_delrissa::boss_priestess_delrissaAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            Talk(SAY_AGGRO);
            summons.DoZoneInCombat();
            instance->SetData(DATA_DELRISSA_EVENT, IN_PROGRESS);
            events.ScheduleEvent(EVENT_SPELL_FLASH_HEAL, 15000);
            events.ScheduleEvent(EVENT_SPELL_RENEW, 10000);
            events.ScheduleEvent(EVENT_SPELL_PW_SHIELD, 2000);
            events.ScheduleEvent(EVENT_SPELL_SW_PAIN, 5000);
            events.ScheduleEvent(EVENT_SPELL_DISPEL, 7500);
            events.ScheduleEvent(EVENT_CHECK_DIST, 5000);
            if (IsHeroic())
                events.ScheduleEvent(EVENT_SPELL_IMMUNITY, 4000);
        }
References DATA_DELRISSA_EVENT, SummonList::DoZoneInCombat(), EVENT_CHECK_DIST, EVENT_SPELL_DISPEL, EVENT_SPELL_FLASH_HEAL, EVENT_SPELL_IMMUNITY, EVENT_SPELL_PW_SHIELD, EVENT_SPELL_RENEW, EVENT_SPELL_SW_PAIN, IN_PROGRESS, instance, ScriptedAI::IsHeroic(), SAY_AGGRO, ZoneScript::SetData(), and summons.
JustSummoned()
void boss_priestess_delrissa::boss_priestess_delrissaAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(summon);
        }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_priestess_delrissa::boss_priestess_delrissaAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->GetTypeId() != TYPEID_PLAYER)
                return;
            if (PlayersKilled < SAY_DEATH)
                Talk(PlayersKilled++);
        }
References Object::GetTypeId(), PlayersKilled, SAY_DEATH, and TYPEID_PLAYER.
Reset()
void boss_priestess_delrissa::boss_priestess_delrissaAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            PlayersKilled = SAY_PLAYER_KILLED;
            HelpersKilled = SAY_HELPER_DIED;
            instance->SetData(DATA_DELRISSA_EVENT, NOT_STARTED);
            summons.Respawn();
            me->SetLootMode(0);
        }
References DATA_DELRISSA_EVENT, HelpersKilled, instance, ScriptedAI::me, NOT_STARTED, PlayersKilled, SummonList::Respawn(), SAY_HELPER_DIED, SAY_PLAYER_KILLED, ZoneScript::SetData(), Creature::SetLootMode(), and summons.
SummonedCreatureDies()
void boss_priestess_delrissa::boss_priestess_delrissaAI::SummonedCreatureDies (Creature * , Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            if (me->IsAlive() && HelpersKilled < SAY_PLAYER_KILLED)
            {
                if (HelpersKilled == MAX_ACTIVE_HELPERS)
                    me->SetLootMode(1);
                Talk(HelpersKilled);
            }
            else if (HelpersKilled == MAX_ACTIVE_HELPERS)
            {
                me->loot.clear();
                me->loot.FillLoot(me->GetCreatureTemplate()->lootid, LootTemplates_Creature, me->GetLootRecipient(), false, false, 1, me);
                instance->SetData(DATA_DELRISSA_EVENT, DONE);
                me->SetDynamicFlag(UNIT_DYNFLAG_LOOTABLE);
            }
            ++HelpersKilled;
        }
References Loot::clear(), DATA_DELRISSA_EVENT, DONE, Loot::FillLoot(), Creature::GetCreatureTemplate(), Creature::GetLootRecipient(), HelpersKilled, instance, Unit::IsAlive(), Creature::loot, CreatureTemplate::lootid, LootTemplates_Creature, MAX_ACTIVE_HELPERS, ScriptedAI::me, SAY_PLAYER_KILLED, ZoneScript::SetData(), Object::SetDynamicFlag(), Creature::SetLootMode(), and UNIT_DYNFLAG_LOOTABLE.
UpdateAI()
void boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_CHECK_DIST:
                    if (me->GetDistance(me->GetHomePosition()) > 75.0f)
                    {
                        EnterEvadeMode(EVADE_REASON_OTHER);
                        return;
                    }
                    events.ScheduleEvent(EVENT_CHECK_DIST, 5000);
                    break;
                case EVENT_SPELL_FLASH_HEAL:
                    if (Unit* target = DoSelectLowestHpFriendly(40.0f, 1000))
                        me->CastSpell(target, SPELL_FLASH_HEAL, false);
                    events.ScheduleEvent(EVENT_SPELL_FLASH_HEAL, 15000);
                    break;
                case EVENT_SPELL_RENEW:
                    if (Unit* target = DoSelectLowestHpFriendly(40.0f, 1000))
                        me->CastSpell(target, DUNGEON_MODE(SPELL_RENEW_N, SPELL_RENEW_H), false);
                    events.ScheduleEvent(EVENT_SPELL_RENEW, 7000);
                    break;
                case EVENT_SPELL_PW_SHIELD:
                    {
                        std::list<Creature*> cList = DoFindFriendlyMissingBuff(40.0f, DUNGEON_MODE(SPELL_POWER_WORD_SHIELD_N, SPELL_POWER_WORD_SHIELD_H));
                        if (Unit* target = Acore::Containers::SelectRandomContainerElement(cList))
                            me->CastSpell(target, DUNGEON_MODE(SPELL_POWER_WORD_SHIELD_N, SPELL_POWER_WORD_SHIELD_H), false);
                        events.ScheduleEvent(EVENT_SPELL_PW_SHIELD, 10000);
                        break;
                    }
                case EVENT_SPELL_DISPEL:
                    {
                        Unit* target = nullptr;
                        switch (urand(0, 2))
{
                            case 0:
                                target = SelectTarget(SelectTargetMethod::Random, 0, 30, true);
                                break;
                            case 1:
                                target = me;
                                break;
                            case 2:
                                target = ObjectAccessor::GetCreature(*me, Acore::Containers::SelectRandomContainerElement(summons));
                                break;
                        }
                        if (target)
                            me->CastSpell(target, SPELL_DISPEL_MAGIC, false);
                        events.ScheduleEvent(EVENT_SPELL_DISPEL, 12000);
                        break;
                    }
                case EVENT_SPELL_IMMUNITY:
                    if (me->HasUnitState(UNIT_STATE_LOST_CONTROL))
                    {
                        me->CastSpell(me, SPELL_MEDALION_OF_IMMUNITY, false);
                        events.ScheduleEvent(EVENT_SPELL_IMMUNITY, 60000);
                    }
                    else
                        events.ScheduleEvent(EVENT_SPELL_IMMUNITY, 1000);
                    break;
                case EVENT_SPELL_SW_PAIN:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 30.0f))
                        me->CastSpell(target, DUNGEON_MODE(SPELL_SHADOW_WORD_PAIN_N, SPELL_SHADOW_WORD_PAIN_H), false);
                    events.ScheduleEvent(EVENT_SPELL_SW_PAIN, 10000);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::CastSpell(), ScriptedAI::DoFindFriendlyMissingBuff(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoSelectLowestHpFriendly(), ScriptedAI::DUNGEON_MODE(), CreatureAI::EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_CHECK_DIST, EVENT_SPELL_DISPEL, EVENT_SPELL_FLASH_HEAL, EVENT_SPELL_IMMUNITY, EVENT_SPELL_PW_SHIELD, EVENT_SPELL_RENEW, EVENT_SPELL_SW_PAIN, ObjectAccessor::GetCreature(), WorldObject::GetDistance(), Creature::GetHomePosition(), Unit::HasUnitState(), ScriptedAI::me, Acore::Containers::SelectRandomContainerElement(), UnitAI::SelectTarget(), SPELL_DISPEL_MAGIC, SPELL_FLASH_HEAL, SPELL_MEDALION_OF_IMMUNITY, SPELL_POWER_WORD_SHIELD_H, SPELL_POWER_WORD_SHIELD_N, SPELL_RENEW_H, SPELL_RENEW_N, SPELL_SHADOW_WORD_PAIN_H, SPELL_SHADOW_WORD_PAIN_N, summons, UNIT_STATE_CASTING, UNIT_STATE_LOST_CONTROL, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap boss_priestess_delrissa::boss_priestess_delrissaAI::events
HelpersKilled
uint8 boss_priestess_delrissa::boss_priestess_delrissaAI::HelpersKilled
Referenced by JustDied(), Reset(), and SummonedCreatureDies().
instance
InstanceScript* boss_priestess_delrissa::boss_priestess_delrissaAI::instance
Referenced by boss_priestess_delrissaAI(), JustDied(), JustEngagedWith(), Reset(), and SummonedCreatureDies().
PlayersKilled
uint8 boss_priestess_delrissa::boss_priestess_delrissaAI::PlayersKilled
Referenced by KilledUnit(), and Reset().
summons
SummonList boss_priestess_delrissa::boss_priestess_delrissaAI::summons
Referenced by JustEngagedWith(), JustSummoned(), Reset(), and UpdateAI().