AzerothCore: Acore::Impl::EnumUtilsImpl::EnumUtils< Enum > Struct Template Reference
Acore::Impl::EnumUtilsImpl::EnumUtils< Enum > Struct Template Reference
#include "SmartEnum.h"
Static Public Member Functions
static std::size_t Count ()
static EnumText ToString (Enum value)
static Enum FromIndex (std::size_t index)
static std::size_t ToIndex (Enum index)
Detailed Description
template<typename Enum>
struct Acore::Impl::EnumUtilsImpl::EnumUtils< Enum >
Member Function Documentation
Count()
template<typename Enum > static std::size_t Acore::Impl::EnumUtilsImpl::EnumUtils< Enum >::Count () static
Referenced by EnumUtils::Count().
FromIndex()
template<typename Enum > static Enum Acore::Impl::EnumUtilsImpl::EnumUtils< Enum >::FromIndex (std::size_t index) static
Referenced by EnumUtils::FromIndex().
ToIndex()
template<typename Enum > static std::size_t Acore::Impl::EnumUtilsImpl::EnumUtils< Enum >::ToIndex (Enum index) static
Referenced by EnumUtils::IsValid(), and EnumUtils::ToIndex().
ToString()
template<typename Enum > static EnumText Acore::Impl::EnumUtilsImpl::EnumUtils< Enum >::ToString (Enum value) static
Referenced by EnumUtils::ToString().