AzeorthCore: inventory_commandscript Class Reference
inventory_commandscript Class Reference
Public Member Functions
inventory_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleInventoryCountCommand (ChatHandler *handler, Optional< PlayerIdentifier > player)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
inventory_commandscript()
inventory_commandscript::inventory_commandscript () inline
: CommandScript("inventory_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable inventory_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable inventoryCommandTable =
        {
            { "count",      HandleInventoryCountCommand,   SEC_MODERATOR, Console::No }
        };
        static ChatCommandTable commandTable =
        {
            { "inventory",  inventoryCommandTable }
        };
        return commandTable;
    }
References HandleInventoryCountCommand(), and SEC_MODERATOR.
HandleInventoryCountCommand()
static bool inventory_commandscript::HandleInventoryCountCommand (ChatHandler * handler, Optional< PlayerIdentifier > player) inline static
    {
        if (!player)
        {
            player = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!player)
        {
            handler->SendSysMessage(LANG_PLAYER_NOT_FOUND);
            handler->SetSentErrorMessage(true);
            return false;
        }
        Player* target = player->GetConnectedPlayer();
        if (!target)
        {
            handler->SendSysMessage(LANG_PLAYER_NOT_FOUND);
            handler->SetSentErrorMessage(true);
            return false;
        }
        std::array<uint32, MAX_ITEM_SUBCLASS_CONTAINER> freeSlotsInBags = { };
        uint32 freeSlotsForBags = 0;
        bool haveFreeSlot = false;
        // Check backpack
        for (uint8 slot = INVENTORY_SLOT_ITEM_START; slot < INVENTORY_SLOT_ITEM_END; ++slot)
        {
            if (!target->GetItemByPos(INVENTORY_SLOT_BAG_0, slot))
            {
                haveFreeSlot = true;
                ++freeSlotsInBags[ITEM_SUBCLASS_CONTAINER];
            }
        }
        // Check bags
        for (uint8 i = INVENTORY_SLOT_BAG_START; i < INVENTORY_SLOT_BAG_END; i++)
        {
            if (Bag* bag = target->GetBagByPos(i))
            {
                if (ItemTemplate const* bagTemplate = bag->GetTemplate())
                {
                    if (bagTemplate->Class == ITEM_CLASS_CONTAINER || bagTemplate->Class == ITEM_CLASS_QUIVER)
                    {
                        haveFreeSlot = true;
                        freeSlotsInBags[bagTemplate->SubClass] += bag->GetFreeSlots();
                    }
                }
            }
            else
            {
                ++freeSlotsForBags;
            }
        }
        std::ostringstream str;
        if (haveFreeSlot)
        {
            str << "Player " << target->GetName() << " have ";
            bool initialize = true;
            for (uint8 i = ITEM_SUBCLASS_CONTAINER; i < MAX_ITEM_SUBCLASS_CONTAINER; ++i)
            {
                if (uint32 freeSlots = freeSlotsInBags[i])
                {
                    std::string bagSpecString = bagSpecsToString[i];
                    if (!initialize)
                    {
                        str << ", ";
                    }
                    str << "|c";
                    str << std::hex << bagSpecsColors[i] << std::dec;
                    str << freeSlots << " in " << bagSpecString << " bags|r";
                    initialize = false;
                }
            }
        }
        else
        {
            str << "Player " << target->GetName() << " does not have free slots in their bags";
        }
        if (freeSlotsForBags)
        {
            str << " and also has " << freeSlotsForBags << " free slots for bags";
        }
        str << ".";
        handler->SendSysMessage(str.str().c_str());
        return true;
    }
References bagSpecsColors, bagSpecsToString, Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Player::GetBagByPos(), Player::GetItemByPos(), WorldObject::GetName(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ITEM_CLASS_CONTAINER, ITEM_CLASS_QUIVER, ITEM_SUBCLASS_CONTAINER, LANG_PLAYER_NOT_FOUND, MAX_ITEM_SUBCLASS_CONTAINER, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().