var classspell__illidan__tear__of__azzinoth__summon__channel_1_1spell__illidan__tear__of__azzinoth__summon__channel___aura_script =
[
    [ "OnPeriodic", "d0/d4e/classspell__illidan__tear__of__azzinoth__summon__channel_1_1spell__illidan__tear__of__azzinoth__summon__channel___aura_script.html#a6acf8994dfb8baff4a86ea746e1805c1", null ],
    [ "PrepareAuraScript", "d0/d4e/classspell__illidan__tear__of__azzinoth__summon__channel_1_1spell__illidan__tear__of__azzinoth__summon__channel___aura_script.html#a7bc4b970e20dfa89f0066c20a2a4405a", null ],
    [ "Register", "d0/d4e/classspell__illidan__tear__of__azzinoth__summon__channel_1_1spell__illidan__tear__of__azzinoth__summon__channel___aura_script.html#ac0ba16b025eb1d96811e9c2a9996a880", null ]
];