AzerothCore: npc_shattrath_daily_quest Struct Reference
npc_shattrath_daily_quest Struct Reference
Public Member Functions
npc_shattrath_daily_quest (Creature *c)
void DoAction (int32 action) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_shattrath_daily_quest()
npc_shattrath_daily_quest::npc_shattrath_daily_quest (Creature * c) inline
: NullCreatureAI(c) {}
Member Function Documentation
DoAction()
void npc_shattrath_daily_quest::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        if (action == ACTION_UPDATE_QUEST_STATUS)
        {
            uint32 creature = me->GetEntry();
            QueryResult result = CharacterDatabase.Query("SELECT `quest_id` FROM `pool_quest_save` WHERE `pool_id` = '{}'", creature == NPC_SHATTRATH_DAILY_H ? POOL_SHATTRATH_DAILY_H : POOL_SHATTRATH_DAILY_N);
            if (result)
            {
                Field *fields = result->Fetch();
                int quest_id = fields[0].Get<int>();
                uint32 templateID = 0;
                if (creature == NPC_SHATTRATH_DAILY_H)
                {
                    switch (quest_id)
                    {
                        case QUEST_H_NAZZAN:
                            templateID = 24410;
                            break;
                        case QUEST_H_KELIDAN:
                            templateID = 24413;
                            break;
                        case QUEST_H_BLADEFIST:
                            templateID = 24414;
                            break;
                        case QUEST_H_QUAG:
                            templateID = 24419;
                            break;
                        case QUEST_H_BLACKSTALKER:
                            templateID = 24420;
                            break;
                        case QUEST_H_WARLORD:
                            templateID = 24421;
                            break;
                        case QUEST_H_IKISS:
                            templateID = 24422;
                            break;
                        case QUEST_H_SHAFFAR:
                            templateID = 24423;
                            break;
                        case QUEST_H_EXARCH:
                            templateID = 24424;
                            break;
                        case QUEST_H_MURMUR:
                            templateID = 24425;
                            break;
                        case QUEST_H_EPOCH:
                            templateID = 24427;
                            break;
                        case QUEST_H_AEONUS:
                            templateID = 24428;
                            break;
                        case QUEST_H_WARP:
                            templateID = 24431;
                            break;
                        case QUEST_H_CALCULATOR:
                            templateID = 21504;
                            break;
                        case QUEST_H_SKYRISS:
                            templateID = 24435;
                            break;
                        case QUEST_H_KAEL:
                            templateID = 24855;
                            break;
                        default:
                            break;
                    }
                }
                if (creature == NPC_SHATTRATH_DAILY_N)
                {
                    switch (quest_id)
                    {
                        case QUEST_N_CENTURIONS:
                            templateID = 24411;
                            break;
                        case QUEST_N_MYRMIDONS:
                            templateID = 24415;
                            break;
                        case QUEST_N_INSTRUCTORS:
                            templateID = 24426;
                            break;
                        case QUEST_N_LORDS:
                            templateID = 24429;
                            break;
                        case QUEST_N_CHANNELERS:
                            templateID = 24430;
                            break;
                        case QUEST_N_DESTROYERS:
                            templateID = 24432;
                            break;
                        case QUEST_N_SENTINELS:
                            templateID = 24434;
                            break;
                        case QUEST_N_SISTERS:
                            templateID = 24854;
                            break;
                        default:
                            break;
                    }
                }
                if (CreatureTemplate const* ci = sObjectMgr->GetCreatureTemplate(templateID))
                {
                    CreatureModel const* model = ObjectMgr::ChooseDisplayId(ci);
                    me->SetDisplayId(model->CreatureDisplayID, model->DisplayScale);
                }
            }
        }
    }
References ACTION_UPDATE_QUEST_STATUS, CharacterDatabase, ObjectMgr::ChooseDisplayId(), CreatureModel::CreatureDisplayID, CreatureModel::DisplayScale, Field::Get(), Object::GetEntry(), CreatureAI::me, NPC_SHATTRATH_DAILY_H, NPC_SHATTRATH_DAILY_N, POOL_SHATTRATH_DAILY_H, POOL_SHATTRATH_DAILY_N, QUEST_H_AEONUS, QUEST_H_BLACKSTALKER, QUEST_H_BLADEFIST, QUEST_H_CALCULATOR, QUEST_H_EPOCH, QUEST_H_EXARCH, QUEST_H_IKISS, QUEST_H_KAEL, QUEST_H_KELIDAN, QUEST_H_MURMUR, QUEST_H_NAZZAN, QUEST_H_QUAG, QUEST_H_SHAFFAR, QUEST_H_SKYRISS, QUEST_H_WARLORD, QUEST_H_WARP, QUEST_N_CENTURIONS, QUEST_N_CHANNELERS, QUEST_N_DESTROYERS, QUEST_N_INSTRUCTORS, QUEST_N_LORDS, QUEST_N_MYRMIDONS, QUEST_N_SENTINELS, QUEST_N_SISTERS, Creature::SetDisplayId(), and sObjectMgr.