AzeorthCore: npc_dark_iron_guzzler Struct Reference
npc_dark_iron_guzzler Struct Reference
Public Member Functions
npc_dark_iron_guzzler (Creature *creature)
void EnterCombat (Unit *) override
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void MovementInform (uint32 type, uint32) override
void FindNextKeg ()
Unit * GetTarget ()
void Reset () override
void SayText ()
void KilledUnit (Unit *who) override
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
Cast Spell.
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
Play sound.
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
Reset Threat.
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
Modify Unit Threat.
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
Teleport player.
void DoTeleportAll (float x, float y, float z, float o)
Teleport all.
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
Set Combat Movement.
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectTargetMethod targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
uint32 timer
ObjectGuid targetGUID
bool attacking
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_dark_iron_guzzler()
npc_dark_iron_guzzler::npc_dark_iron_guzzler (Creature * creature) inline
                                              : ScriptedAI(creature)
    {
        me->SetReactState(REACT_PASSIVE);
        attacking = false;
    }
References attacking, ScriptedAI::me, REACT_PASSIVE, and Creature::SetReactState().
Member Function Documentation
AttackStart()
void npc_dark_iron_guzzler::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
{}
DamageTaken()
void npc_dark_iron_guzzler::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
    {
        damage = 0;
    }
EnterCombat()
void npc_dark_iron_guzzler::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
{}
FindNextKeg()
void npc_dark_iron_guzzler::FindNextKeg () inline
    {
        uint32 entry[3] = {0, 0, 0};
        uint32 shuffled[3] = {0, 0, 0};
        if (me->GetMapId() == 1) // Kalimdor
        {
            entry[0] = NPC_DROHN_KEG;
            entry[1] = NPC_VOODOO_KEG;
            entry[2] = NPC_GORDOK_KEG;
        }
        else// if (me->GetMapId() == 0) // EK
        {
            entry[0] = NPC_THUNDERBREW_KEG;
            entry[1] = NPC_BARLEYBREW_KEG;
            entry[2] = NPC_GORDOK_KEG;
        }
        for (uint8 i = 0; i < 3; ++i)
        {
            uint8 index = 0;
            do
                index = urand(0, 2);
            while (shuffled[index]);
            shuffled[index] = entry[i];
        }
        attacking = false;
        for (uint8 i = 0; i < 3; ++i)
            if (Creature* cr = me->FindNearestCreature(shuffled[i], 100.0f))
            {
                cr->SetWalk(true);
                me->GetMotionMaster()->MoveFollow(cr, 1.0f, cr->GetAngle(me));
                targetGUID = cr->GetGUID();
                return;
            }
        // no kegs found
        me->DisappearAndDie();
    }
References attacking, Creature::DisappearAndDie(), WorldObject::FindNearestCreature(), WorldLocation::GetMapId(), Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MoveFollow(), NPC_BARLEYBREW_KEG, NPC_DROHN_KEG, NPC_GORDOK_KEG, NPC_THUNDERBREW_KEG, NPC_VOODOO_KEG, targetGUID, and urand().
Referenced by Reset(), and UpdateAI().
GetTarget()
Unit * npc_dark_iron_guzzler::GetTarget () inline
{ return ObjectAccessor::GetUnit(*me, targetGUID); }
References ObjectAccessor::GetUnit(), ScriptedAI::me, and targetGUID.
Referenced by MovementInform(), and UpdateAI().
KilledUnit()
void npc_dark_iron_guzzler::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
    {
        who->CastSpell(who, SPELL_REPORT_DEATH, true);
    }
References Unit::CastSpell(), and SPELL_REPORT_DEATH.
MoveInLineOfSight()
void npc_dark_iron_guzzler::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{}
MovementInform()
void npc_dark_iron_guzzler::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type != FOLLOW_MOTION_TYPE)
        {
            return;
        }
        if (Unit* target = GetTarget())
        {
            timer = 0;
            attacking = true;
            me->CastSpell(target, SPELL_ATTACK_KEG, false);
        }
    }
References attacking, Unit::CastSpell(), FOLLOW_MOTION_TYPE, GetTarget(), ScriptedAI::me, SPELL_ATTACK_KEG, and timer.
Reset()
void npc_dark_iron_guzzler::Reset () inline override virtual
Reimplemented from ScriptedAI.
    {
        timer = 0;
        targetGUID.Clear();
        me->SetWalk(true);
        FindNextKeg();
        me->ApplySpellImmune(SPELL_ATTACK_KEG, IMMUNITY_ID, SPELL_ATTACK_KEG, true);
        SayText();
        me->CastSpell(me, SPELL_KNOCKBACK_AURA, true);
    }
References Unit::ApplySpellImmune(), Unit::CastSpell(), ObjectGuid::Clear(), FindNextKeg(), IMMUNITY_ID, ScriptedAI::me, SayText(), Creature::SetWalk(), SPELL_ATTACK_KEG, SPELL_KNOCKBACK_AURA, targetGUID, and timer.
SayText()
void npc_dark_iron_guzzler::SayText () inline
    {
        if (!urand(0, 20))
        {
            switch (urand(0, 4))
            {
                case 0:
                    me->Say("Drink it all boys!", LANG_UNIVERSAL);
                    break;
                case 1:
                    me->Say("DRINK! BRAWL! DRINK! BRAWL!", LANG_UNIVERSAL);
                    break;
                case 2:
                    me->Say("Did someone say, \"Free Brew\"?", LANG_UNIVERSAL);
                    break;
                case 3:
                    me->Say("No one expects the Dark Iron dwarves!", LANG_UNIVERSAL);
                    break;
                case 4:
                    me->Say("It's not a party without some crashers!", LANG_UNIVERSAL);
                    break;
            }
        }
    }
References LANG_UNIVERSAL, ScriptedAI::me, Unit::Say(), and urand().
Referenced by Reset().
SpellHit()
void npc_dark_iron_guzzler::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (me->IsAlive() && spellInfo->Id == SPELL_PLAYER_MUG)
        {
            me->CastSpell(me, SPELL_MUG_BOUNCE_BACK, true);
            Unit::Kill(me, me);
            me->CastSpell(me, SPELL_REPORT_DEATH, true);
        }
    }
References Unit::CastSpell(), SpellInfo::Id, Unit::IsAlive(), Unit::Kill(), ScriptedAI::me, SPELL_MUG_BOUNCE_BACK, SPELL_PLAYER_MUG, and SPELL_REPORT_DEATH.
UpdateAI()
void npc_dark_iron_guzzler::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
    {
        timer += diff;
        if (timer < 2000)
            return;
        timer = 0;
        if (targetGUID)
        {
            Unit* target = GetTarget();
            if (target && target->IsAlive())
            {
                if (attacking)
                {
                    me->CastSpell(target, SPELL_ATTACK_KEG, false);
                }
            }
            else
            {
                FindNextKeg();
            }
        }
    }
References attacking, Unit::CastSpell(), FindNextKeg(), GetTarget(), Unit::IsAlive(), ScriptedAI::me, SPELL_ATTACK_KEG, targetGUID, and timer.
Member Data Documentation
attacking
bool npc_dark_iron_guzzler::attacking
Referenced by FindNextKeg(), MovementInform(), npc_dark_iron_guzzler(), and UpdateAI().
targetGUID
ObjectGuid npc_dark_iron_guzzler::targetGUID
Referenced by FindNextKeg(), GetTarget(), Reset(), and UpdateAI().
timer
uint32 npc_dark_iron_guzzler::timer
Referenced by MovementInform(), Reset(), and UpdateAI().