AzerothCore: spell_yogg_saron_sanity_reduce Class Reference
spell_yogg_saron_sanity_reduce Class Reference
Private Member Functions
PrepareSpellScript (spell_yogg_saron_sanity_reduce)
bool Validate (SpellInfo const *) override
void HandleScriptEffect (SpellEffIndex effIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleScriptEffect()
void spell_yogg_saron_sanity_reduce::HandleScriptEffect (SpellEffIndex effIndex) inline private
    {
        PreventHitDefaultEffect(effIndex);
        Player* target = GetHitPlayer();
        if (!target)
            return;
        uint8 _reduceAmount = 0;
        switch (GetSpellInfo()->Id)
        {
            case SPELL_SARA_PSYCHOSIS_10:
                _reduceAmount = 9;
                break;
            case SPELL_SARA_PSYCHOSIS_25:
                _reduceAmount = 12;
                break;
            case SPELL_MALADY_OF_THE_MIND:
                _reduceAmount = 3;
                break;
            case SPELL_MALADY_OF_THE_MIND_TRIGGER:
                _reduceAmount = 3;
                break;
            case SPELL_BRAIN_LINK_DAMAGE:
                _reduceAmount = 2;
                break;
            case SPELL_LUNATIC_GAZE_TRIGGER:
                _reduceAmount = 2;
                break;
            case SPELL_YS_LUNATIC_GAZE_TRIGGER:
                _reduceAmount = 4;
                break;
            case SPELL_INDUCE_MADNESS:
                // Teleported out of brain
                if (target->GetPositionZ() > 300.0f)
                    return;
                else
                    target->CastSpell(target, SPELL_CANCEL_ILLUSION_AURA, true); // else we are underground, remove illusion aura and teleport outside
                _reduceAmount = 100;
                break;
        }
        if (Aura* aur = target->GetAura(SPELL_SANITY))
        {
            if ((aur->GetStackAmount() - _reduceAmount) <= 20)
                target->CastSpell(target, SPELL_SANITY_SCREEN_EFFECT, true);
            aur->ModStackAmount(-_reduceAmount);
        }
    }
References Unit::CastSpell(), Unit::GetAura(), SpellScript::GetHitPlayer(), Position::GetPositionZ(), SpellScript::GetSpellInfo(), SpellScript::PreventHitDefaultEffect(), SPELL_BRAIN_LINK_DAMAGE, SPELL_CANCEL_ILLUSION_AURA, SPELL_INDUCE_MADNESS, SPELL_LUNATIC_GAZE_TRIGGER, SPELL_MALADY_OF_THE_MIND, SPELL_MALADY_OF_THE_MIND_TRIGGER, SPELL_SANITY, SPELL_SANITY_SCREEN_EFFECT, SPELL_SARA_PSYCHOSIS_10, SPELL_SARA_PSYCHOSIS_25, and SPELL_YS_LUNATIC_GAZE_TRIGGER.
Referenced by Register().
PrepareSpellScript()
spell_yogg_saron_sanity_reduce::PrepareSpellScript (spell_yogg_saron_sanity_reduce) private
Register()
void spell_yogg_saron_sanity_reduce::Register () inline override private virtual
Implements _SpellScript.
    {
        OnEffectHitTarget += SpellEffectFn(spell_yogg_saron_sanity_reduce::HandleScriptEffect, EFFECT_FIRST_FOUND, SPELL_EFFECT_SCRIPT_EFFECT);
    }
References EFFECT_FIRST_FOUND, HandleScriptEffect(), SpellScript::OnEffectHitTarget, SPELL_EFFECT_SCRIPT_EFFECT, and SpellEffectFn.
Validate()
bool spell_yogg_saron_sanity_reduce::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo({ SPELL_CANCEL_ILLUSION_AURA, SPELL_SANITY_SCREEN_EFFECT });
    }
References SPELL_CANCEL_ILLUSION_AURA, SPELL_SANITY_SCREEN_EFFECT, and _SpellScript::ValidateSpellInfo().