AzeorthCore: boss_anetheron::boss_anetheronAI Struct Reference
boss_anetheron::boss_anetheronAI Struct Reference
Public Member Functions
boss_anetheronAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void KilledUnit (Unit *who) override
void WaypointReached (uint32 waypointId) override
void JustDied (Unit *killer) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from hyjal_trashAI
hyjal_trashAI (Creature *creature)
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void DamageTaken (Unit *done_by, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
Cast Spell.
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
Play sound.
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
Reset Threat.
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
Modify Unit Threat.
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
Teleport player.
void DoTeleportAll (float x, float y, float z, float o)
Teleport all.
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
Set Combat Movement.
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectTargetMethod targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
uint32 SwarmTimer
uint32 SleepTimer
uint32 AuraTimer
uint32 InfernoTimer
bool go
Public Attributes inherited from hyjal_trashAI
InstanceScript * instance
bool IsEvent
uint32 Delay
uint32 LastOverronPos
bool IsOverrun
bool SetupOverrun
uint32 OverrunType
uint8 faction
bool useFlyPath
uint32 damageTaken
float DummyTarget [3]
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_anetheronAI()
boss_anetheron::boss_anetheronAI::boss_anetheronAI (Creature * creature) inline
                                             : hyjal_trashAI(creature)
        {
            instance = creature->GetInstanceScript();
            go = false;
        }
References WorldObject::GetInstanceScript(), go, and hyjal_trashAI::instance.
Member Function Documentation
EnterCombat()
void boss_anetheron::boss_anetheronAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (IsEvent)
                instance->SetData(DATA_ANETHERONEVENT, IN_PROGRESS);
            Talk(SAY_ONAGGRO);
        }
References DATA_ANETHERONEVENT, IN_PROGRESS, hyjal_trashAI::instance, hyjal_trashAI::IsEvent, SAY_ONAGGRO, and ZoneScript::SetData().
JustDied()
void boss_anetheron::boss_anetheronAI::JustDied (Unit * killer) inline override virtual
Reimplemented from npc_escortAI.
        {
            hyjal_trashAI::JustDied(killer);
            if (IsEvent)
                instance->SetData(DATA_ANETHERONEVENT, DONE);
            Talk(SAY_ONDEATH);
        }
References DATA_ANETHERONEVENT, DONE, hyjal_trashAI::instance, hyjal_trashAI::IsEvent, hyjal_trashAI::JustDied(), SAY_ONDEATH, and ZoneScript::SetData().
KilledUnit()
void boss_anetheron::boss_anetheronAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (who->GetTypeId() == TYPEID_PLAYER)
                Talk(SAY_ONSLAY);
        }
References Object::GetTypeId(), SAY_ONSLAY, and TYPEID_PLAYER.
Reset()
void boss_anetheron::boss_anetheronAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            damageTaken = 0;
            SwarmTimer = 45000;
            SleepTimer = 60000;
            AuraTimer = 5000;
            InfernoTimer = 45000;
            if (IsEvent)
                instance->SetData(DATA_ANETHERONEVENT, NOT_STARTED);
        }
References AuraTimer, hyjal_trashAI::damageTaken, DATA_ANETHERONEVENT, InfernoTimer, hyjal_trashAI::instance, hyjal_trashAI::IsEvent, NOT_STARTED, ZoneScript::SetData(), SleepTimer, and SwarmTimer.
UpdateAI()
void boss_anetheron::boss_anetheronAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
        {
            if (IsEvent)
            {
                //Must update npc_escortAI
                npc_escortAI::UpdateAI(diff);
                if (!go)
                {
                    go = true;
                    AddWaypoint(0, 4896.08f,    -1576.35f,    1333.65f);
                    AddWaypoint(1, 4898.68f,    -1615.02f,    1329.48f);
                    AddWaypoint(2, 4907.12f,    -1667.08f,    1321.00f);
                    AddWaypoint(3, 4963.18f,    -1699.35f,    1340.51f);
                    AddWaypoint(4, 4989.16f,    -1716.67f,    1335.74f);
                    AddWaypoint(5, 5026.27f,    -1736.89f,    1323.02f);
                    AddWaypoint(6, 5037.77f,    -1770.56f,    1324.36f);
                    AddWaypoint(7, 5067.23f,    -1789.95f,    1321.17f);
                    Start(false, true);
                    SetDespawnAtEnd(false);
                }
            }
            //Return since we have no target
            if (!UpdateVictim())
            {
                return;
            }
            if (SwarmTimer <= diff)
            {
                if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100, true))
                {
                    DoCast(target, SPELL_CARRION_SWARM);
                }
                SwarmTimer = urand(45000, 60000);
                Talk(SAY_SWARM);
            }
            else SwarmTimer -= diff;
            if (SleepTimer <= diff)
            {
                for (uint8 i = 0; i < 3; ++i)
                {
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100, true))
                        target->CastSpell(target, SPELL_SLEEP, true);
                }
                SleepTimer = 60000;
                Talk(SAY_SLEEP);
            }
            else SleepTimer -= diff;
            if (AuraTimer <= diff)
            {
                DoCast(me, SPELL_VAMPIRIC_AURA, true);
                AuraTimer = urand(10000, 20000);
            }
            else AuraTimer -= diff;
            if (InfernoTimer <= diff)
            {
                DoCast(SelectTarget(SelectTargetMethod::Random, 0, 100, true), SPELL_INFERNO);
                InfernoTimer = 45000;
                Talk(SAY_INFERNO);
            }
            else InfernoTimer -= diff;
            DoMeleeAttackIfReady();
        }
References npc_escortAI::AddWaypoint(), AuraTimer, UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), go, InfernoTimer, hyjal_trashAI::IsEvent, ScriptedAI::me, SAY_INFERNO, SAY_SLEEP, SAY_SWARM, UnitAI::SelectTarget(), npc_escortAI::SetDespawnAtEnd(), SleepTimer, SPELL_CARRION_SWARM, SPELL_INFERNO, SPELL_SLEEP, SPELL_VAMPIRIC_AURA, npc_escortAI::Start(), SwarmTimer, npc_escortAI::UpdateAI(), CreatureAI::UpdateVictim(), and urand().
WaypointReached()
void boss_anetheron::boss_anetheronAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
        {
            if (waypointId == 7)
            {
                Unit* target = ObjectAccessor::GetUnit(*me, instance->GetGuidData(DATA_JAINAPROUDMOORE));
                if (target && target->IsAlive())
                    me->AddThreat(target, 0.0f);
            }
        }
References Unit::AddThreat(), DATA_JAINAPROUDMOORE, InstanceScript::GetGuidData(), ObjectAccessor::GetUnit(), hyjal_trashAI::instance, Unit::IsAlive(), and ScriptedAI::me.
Member Data Documentation
AuraTimer
uint32 boss_anetheron::boss_anetheronAI::AuraTimer
Referenced by Reset(), and UpdateAI().
go
bool boss_anetheron::boss_anetheronAI::go
Referenced by boss_anetheronAI(), and UpdateAI().
InfernoTimer
uint32 boss_anetheron::boss_anetheronAI::InfernoTimer
Referenced by Reset(), and UpdateAI().
SleepTimer
uint32 boss_anetheron::boss_anetheronAI::SleepTimer
Referenced by Reset(), and UpdateAI().
SwarmTimer
uint32 boss_anetheron::boss_anetheronAI::SwarmTimer
Referenced by Reset(), and UpdateAI().