AzerothCore: Acore::AnyDeadUnitSpellTargetInRangeCheck Class Reference
Acore::AnyDeadUnitSpellTargetInRangeCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
AnyDeadUnitSpellTargetInRangeCheck (Unit *searchObj, float range, SpellInfo const *spellInfo, SpellTargetCheckTypes check)
bool operator() (Player *u)
bool operator() (Corpse *u)
bool operator() (Creature *u)
template<class NOT_INTERESTED >
bool operator() (NOT_INTERESTED *)
Public Member Functions inherited from Acore::AnyDeadUnitObjectInRangeCheck
AnyDeadUnitObjectInRangeCheck (Unit *searchObj, float range)
bool operator() (Player *u)
bool operator() (Corpse *u)
bool operator() (Creature *u)
template<class NOT_INTERESTED >
bool operator() (NOT_INTERESTED *)
Protected Attributes
SpellInfo const * i_spellInfo
WorldObjectSpellTargetCheck i_check
Protected Attributes inherited from Acore::AnyDeadUnitObjectInRangeCheck
Unit const *const i_searchObj
float i_range
Detailed Description
Constructor & Destructor Documentation
AnyDeadUnitSpellTargetInRangeCheck()
Acore::AnyDeadUnitSpellTargetInRangeCheck::AnyDeadUnitSpellTargetInRangeCheck (Unit * searchObj, float range, SpellInfo const * spellInfo, SpellTargetCheckTypes check) inline
            : AnyDeadUnitObjectInRangeCheck(searchObj, range), i_spellInfo(spellInfo), i_check(searchObj, searchObj, spellInfo, check, nullptr)
        {}
Member Function Documentation
operator()() [1/4]
bool AnyDeadUnitSpellTargetInRangeCheck::operator() (Corpse * u)
{
    return AnyDeadUnitObjectInRangeCheck::operator()(u) && i_check(u);
}
References i_check, and Acore::AnyDeadUnitObjectInRangeCheck::operator()().
operator()() [2/4]
bool AnyDeadUnitSpellTargetInRangeCheck::operator() (Creature * u)
{
    return AnyDeadUnitObjectInRangeCheck::operator()(u) && i_check(u);
}
References i_check, and Acore::AnyDeadUnitObjectInRangeCheck::operator()().
operator()() [3/4]
template<class NOT_INTERESTED > bool Acore::AnyDeadUnitSpellTargetInRangeCheck::operator() (NOT_INTERESTED *) inline
{ return false; }
operator()() [4/4]
bool AnyDeadUnitSpellTargetInRangeCheck::operator() (Player * u)
{
    return AnyDeadUnitObjectInRangeCheck::operator()(u) && i_check(u);
}
References i_check, and Acore::AnyDeadUnitObjectInRangeCheck::operator()().
Member Data Documentation
i_check
WorldObjectSpellTargetCheck Acore::AnyDeadUnitSpellTargetInRangeCheck::i_check protected
Referenced by operator()().
i_spellInfo
SpellInfo const* Acore::AnyDeadUnitSpellTargetInRangeCheck::i_spellInfo protected