AzerothCore: group_commandscript Class Reference
group_commandscript Class Reference
Public Member Functions
group_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleGroupLeaderCommand (ChatHandler *handler, Optional< PlayerIdentifier > target)
static bool HandleGroupDisbandCommand (ChatHandler *handler, Optional< PlayerIdentifier > target)
static bool HandleGroupRemoveCommand (ChatHandler *handler, Optional< PlayerIdentifier > target)
static bool HandleGroupJoinCommand (ChatHandler *handler, std::string const &playerInGroup, std::string const &playerName)
static bool HandleGroupListCommand (ChatHandler *handler, Optional< PlayerIdentifier > target)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
group_commandscript()
group_commandscript::group_commandscript () inline
: CommandScript("group_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable group_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable groupCommandTable =
        {
            { "list",    HandleGroupListCommand,    SEC_GAMEMASTER, Console::Yes },
            { "join",    HandleGroupJoinCommand,    SEC_GAMEMASTER, Console::No },
            { "remove",  HandleGroupRemoveCommand,  SEC_GAMEMASTER, Console::No },
            { "disband", HandleGroupDisbandCommand, SEC_GAMEMASTER, Console::No },
            { "leader",  HandleGroupLeaderCommand,  SEC_GAMEMASTER, Console::No }
        };
        static ChatCommandTable commandTable =
        {
            { "group",  groupCommandTable }
        };
        return commandTable;
    }
References HandleGroupDisbandCommand(), HandleGroupJoinCommand(), HandleGroupLeaderCommand(), HandleGroupListCommand(), HandleGroupRemoveCommand(), and SEC_GAMEMASTER.
HandleGroupDisbandCommand()
static bool group_commandscript::HandleGroupDisbandCommand (ChatHandler * handler, Optional< PlayerIdentifier > target) inline static
    {
        if (!target)
        {
            target = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!target || !target->IsConnected())
        {
            return false;
        }
        Player* player = nullptr;
        Group* group = nullptr;
        ObjectGuid guid;
        if (handler->GetPlayerGroupAndGUIDByName(target->GetName().c_str(), player, group, guid))
        {
            if (group)
            {
                group->Disband();
            }
        }
        return true;
    }
References Group::Disband(), Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), and ChatHandler::GetPlayerGroupAndGUIDByName().
Referenced by GetCommands().
HandleGroupJoinCommand()
static bool group_commandscript::HandleGroupJoinCommand (ChatHandler * handler, std::string const & playerInGroup, std::string const & playerName) inline static
    {
        if (playerInGroup.empty() || playerName.empty())
        {
            return false;
        }
        Player* playerSource = nullptr;
        Group* groupSource = nullptr;
        ObjectGuid guidSource;
        ObjectGuid guidTarget;
        if (handler->GetPlayerGroupAndGUIDByName(playerInGroup.c_str(), playerSource, groupSource, guidSource, true))
        {
            if (groupSource)
            {
                Group* groupTarget = nullptr;
                Player* playerTarget = nullptr;
                if (handler->GetPlayerGroupAndGUIDByName(playerName.c_str(), playerTarget, groupTarget, guidTarget, true))
                {
                    if (!groupTarget && playerTarget->GetGroup() != groupSource)
                    {
                        if (!groupSource->IsFull())
{
                            groupSource->AddMember(playerTarget);
                            groupSource->BroadcastGroupUpdate();
                            handler->PSendSysMessage(LANG_GROUP_PLAYER_JOINED, playerTarget->GetName(), playerSource->GetName());
                            return true;
                        }
                        else
{
                            // group is full
                            handler->PSendSysMessage(LANG_GROUP_FULL);
                            return true;
                        }
                    }
                    else
                    {
                        // group is full or target player already in a group
                        handler->PSendSysMessage(LANG_GROUP_ALREADY_IN_GROUP, playerTarget->GetName());
                        return true;
                    }
                }
            }
            else
            {
                // specified source player is not in a group
                handler->PSendSysMessage(LANG_GROUP_NOT_IN_GROUP, playerSource->GetName());
                return true;
            }
        }
        return true;
    }
References Group::AddMember(), Group::BroadcastGroupUpdate(), Player::GetGroup(), WorldObject::GetName(), ChatHandler::GetPlayerGroupAndGUIDByName(), Group::IsFull(), LANG_GROUP_ALREADY_IN_GROUP, LANG_GROUP_FULL, LANG_GROUP_NOT_IN_GROUP, LANG_GROUP_PLAYER_JOINED, and ChatHandler::PSendSysMessage().
Referenced by GetCommands().
HandleGroupLeaderCommand()
static bool group_commandscript::HandleGroupLeaderCommand (ChatHandler * handler, Optional< PlayerIdentifier > target) inline static
    {
        if (!target)
        {
            target = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!target)
        {
            return false;
        }
        Player* player = nullptr;
        Group* group = nullptr;
        ObjectGuid guid;
        if (handler->GetPlayerGroupAndGUIDByName(target->GetName().c_str(), player, group, guid))
        {
            if (group && group->GetLeaderGUID() != guid)
            {
                group->ChangeLeader(guid);
                group->SendUpdate();
            }
        }
        return true;
    }
References Group::ChangeLeader(), Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Group::GetLeaderGUID(), ChatHandler::GetPlayerGroupAndGUIDByName(), and Group::SendUpdate().
Referenced by GetCommands().
HandleGroupListCommand()
static bool group_commandscript::HandleGroupListCommand (ChatHandler * handler, Optional< PlayerIdentifier > target) inline static
    {
        if (!target)
        {
            target = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!target)
        {
            return false;
        }
        Group* groupTarget = nullptr;
        if (target->IsConnected())
        {
            groupTarget = target->GetConnectedPlayer()->GetGroup();
        }
        if (!groupTarget)
        {
            if (ObjectGuid groupGUID = sCharacterCache->GetCharacterGroupGuidByGuid(target->GetGUID()))
            {
                groupTarget = sGroupMgr->GetGroupByGUID(groupGUID.GetCounter());
            }
        }
        if (!groupTarget)
        {
            handler->PSendSysMessage(LANG_GROUP_NOT_IN_GROUP, target->GetName());
            return true;
        }
        handler->PSendSysMessage(LANG_GROUP_TYPE, (groupTarget->isRaidGroup() ? "Raid" : "Party"), groupTarget->GetMembersCount());
        for (auto const& slot : groupTarget->GetMemberSlots())
        {
            std::string flags;
            if (slot.flags & MEMBER_FLAG_ASSISTANT)
            {
                flags = "Assistant";
            }
            if (slot.flags & MEMBER_FLAG_MAINTANK)
            {
                if (!flags.empty())
                {
                    flags.append(", ");
                }
                flags.append("MainTank");
            }
            if (slot.flags & MEMBER_FLAG_MAINASSIST)
            {
                if (!flags.empty())
                {
                    flags.append(", ");
                }
                flags.append("MainAssist");
            }
            if (flags.empty())
            {
                flags = "None";
            }
        }
        return true;
    }
References Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Group::GetMembersCount(), Group::GetMemberSlots(), Group::isRaidGroup(), LANG_GROUP_NOT_IN_GROUP, LANG_GROUP_TYPE, MEMBER_FLAG_ASSISTANT, MEMBER_FLAG_MAINASSIST, MEMBER_FLAG_MAINTANK, ChatHandler::PSendSysMessage(), sCharacterCache, and sGroupMgr.
Referenced by GetCommands().
HandleGroupRemoveCommand()
static bool group_commandscript::HandleGroupRemoveCommand (ChatHandler * handler, Optional< PlayerIdentifier > target) inline static
    {
        if (!target)
        {
            target = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!target || !target->IsConnected())
        {
            return false;
        }
        Player* player = nullptr;
        Group* group = nullptr;
        ObjectGuid guid;
        if (handler->GetPlayerGroupAndGUIDByName(target->GetName().c_str(), player, group, guid, true))
        {
            if (group)
            {
                group->RemoveMember(guid);
            }
        }
        return true;
    }
References Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), ChatHandler::GetPlayerGroupAndGUIDByName(), and Group::RemoveMember().
Referenced by GetCommands().