AzerothCore: npc_time_rift Struct Reference
npc_time_rift Struct Reference
Public Member Functions
npc_time_rift (Creature *creature)
void Reset () override
void JustSummoned (Creature *creature) override
void DoSummonAtRift (uint32 entry)
void DoSelectSummon ()
void SummonedCreatureDies (Creature *creature, Unit *) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
InstanceScript * _instance
ObjectGuid _riftKeeperGUID
std::vector< uint32 > waveMobs
uint8 waveMobIndex
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_time_rift()
npc_time_rift::npc_time_rift (Creature * creature) inline
                                      : NullCreatureAI(creature)
    {
        _instance = creature->GetInstanceScript();
    }
References _instance, and WorldObject::GetInstanceScript().
Member Function Documentation
DoSelectSummon()
void npc_time_rift::DoSelectSummon () inline
    {
        uint32 entry = waveMobs[waveMobIndex];
        if (entry == NPC_INFINITE_WHELP)
        {
            DoSummonAtRift(entry);
            DoSummonAtRift(entry);
            DoSummonAtRift(entry);
        }
        else
        {
            if (urand(0, 1))
            {
                switch (entry)
                {
                    case NPC_INFINITE_ASSASSIN:
                        entry = NPC_INFINITE_ASSASSIN_2;
                        break;
                    case NPC_INFINITE_CHRONOMANCER:
                        entry = NPC_INFINITE_CHRONOMANCER_2;
                        break;
                    case NPC_INFINITE_EXECUTIONER:
                        entry = NPC_INFINITE_EXECUTIONER_2;
                        break;
                    case NPC_INFINITE_VANQUISHER:
                        entry = NPC_INFINITE_VANQUISHER_2;
                        break;
                    default:
                        break;
                }
            }
            DoSummonAtRift(entry);
        }
        if (++waveMobIndex >= waveMobs.size())
        {
            waveMobIndex = 0;
        }
    }
References DoSummonAtRift(), NPC_INFINITE_ASSASSIN, NPC_INFINITE_ASSASSIN_2, NPC_INFINITE_CHRONOMANCER, NPC_INFINITE_CHRONOMANCER_2, NPC_INFINITE_EXECUTIONER, NPC_INFINITE_EXECUTIONER_2, NPC_INFINITE_VANQUISHER, NPC_INFINITE_VANQUISHER_2, NPC_INFINITE_WHELP, urand(), waveMobIndex, and waveMobs.
Referenced by UpdateAI().
DoSummonAtRift()
void npc_time_rift::DoSummonAtRift (uint32 entry) inline
    {
        Position pos = me->GetNearPosition(10.0f, 2 * M_PI * rand_norm());
        if (Creature* summon = me->SummonCreature(entry, pos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 150000))
        {
            if (Creature* medivh = _instance->GetCreature(DATA_MEDIVH))
            {
                float o = medivh->GetAngle(summon) + frand(-1.0f, 1.0f);
                summon->SetHomePosition(medivh->GetPositionX() + 14.0f * cos(o), medivh->GetPositionY() + 14.0f * std::sin(o), medivh->GetPositionZ(), summon->GetAngle(medivh));
                summon->GetMotionMaster()->MoveTargetedHome(true);
                summon->SetReactState(REACT_DEFENSIVE);
            }
        }
    }
References _instance, DATA_MEDIVH, frand(), Position::GetAngle(), InstanceScript::GetCreature(), WorldObject::GetNearPosition(), CreatureAI::me, rand_norm(), REACT_DEFENSIVE, WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
Referenced by DoSelectSummon().
JustSummoned()
void npc_time_rift::JustSummoned (Creature * creature) inline override virtual
Reimplemented from CreatureAI.
    {
        if (creature->GetEntry() != NPC_AEONUS && _riftKeeperGUID.IsEmpty())
        {
            _riftKeeperGUID = creature->GetGUID();
        }
    }
References _riftKeeperGUID, Object::GetEntry(), Object::GetGUID(), ObjectGuid::IsEmpty(), and NPC_AEONUS.
Reset()
void npc_time_rift::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        uint32 riftNumer = _instance->GetData(DATA_RIFT_NUMBER);
        if (riftNumer < 6)
        {
            waveMobs = firstWave;
        }
        else if (riftNumer < 12)
        {
            waveMobs = secondWave;
        }
        else
        {
            waveMobs = thirdWave;
        }
        waveMobIndex = 0;
        events.ScheduleEvent(EVENT_SUMMON_AT_RIFT, 16s);
        events.ScheduleEvent(EVENT_SUMMON_BOSS, 6s);
    }
References _instance, DATA_RIFT_NUMBER, EVENT_SUMMON_AT_RIFT, EVENT_SUMMON_BOSS, firstWave, ZoneScript::GetData(), secondWave, thirdWave, waveMobIndex, and waveMobs.
SummonedCreatureDies()
void npc_time_rift::SummonedCreatureDies (Creature * creature, Unit *) inline override virtual
Reimplemented from CreatureAI.
    {
        if (creature->GetGUID() == _riftKeeperGUID)
        {
            me->DespawnOrUnsummon(0);
        }
    }
References _riftKeeperGUID, Creature::DespawnOrUnsummon(), Object::GetGUID(), and CreatureAI::me.
UpdateAI()
void npc_time_rift::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
    {
        events.Update(diff);
        switch (events.ExecuteEvent())
        {
            case EVENT_SUMMON_AT_RIFT:
                if (!_instance->GetCreature(DATA_AEONUS))
                {
                    DoSelectSummon();
                    events.ScheduleEvent(EVENT_SUMMON_AT_RIFT, 15000);
                }
                break;
            case EVENT_SUMMON_BOSS:
            {
                int32 entry = 0;
                switch (_instance->GetData(DATA_RIFT_NUMBER))
                {
                    case 6:
                        entry = _instance->GetBossState(DATA_CHRONO_LORD_DEJA) == DONE ? (me->GetMap()->IsHeroic() ? NPC_INFINITE_CHRONO_LORD : -NPC_CHRONO_LORD_DEJA) : NPC_CHRONO_LORD_DEJA;
                        break;
                    case 12:
                        entry = _instance->GetBossState(DATA_TEMPORUS) == DONE ? (me->GetMap()->IsHeroic() ? NPC_INFINITE_TIMEREAVER : -NPC_TEMPORUS) : NPC_TEMPORUS;
                        break;
                    case 18:
                        entry = NPC_AEONUS;
                        break;
                    default:
                        entry = RAND(NPC_RIFT_KEEPER_WARLOCK, NPC_RIFT_KEEPER_MAGE, NPC_RIFT_LORD, NPC_RIFT_LORD_2);
                        break;
                }
                Position pos = me->GetNearPosition(10.0f, 2 * M_PI * rand_norm());
                if (Creature* summon = me->SummonCreature(std::abs(entry), pos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 3 * MINUTE * IN_MILLISECONDS))
                {
                    if (entry < 0)
                    {
                        summon->SetLootMode(0);
                    }
                    if (summon->GetEntry() != NPC_AEONUS)
                    {
                        me->CastSpell(summon, SPELL_RIFT_CHANNEL, false);
                    }
                    if (summon->IsAIEnabled)
                    {
                        summon->AI()->Talk(SAY_RIFT_MOB_SUMMONED);
                    }
                }
            }
        }
    }
References _instance, Unit::CastSpell(), DATA_AEONUS, DATA_CHRONO_LORD_DEJA, DATA_RIFT_NUMBER, DATA_TEMPORUS, DONE, DoSelectSummon(), EVENT_SUMMON_AT_RIFT, EVENT_SUMMON_BOSS, InstanceScript::GetBossState(), InstanceScript::GetCreature(), ZoneScript::GetData(), WorldObject::GetMap(), WorldObject::GetNearPosition(), IN_MILLISECONDS, Map::IsHeroic(), CreatureAI::me, MINUTE, NPC_AEONUS, NPC_CHRONO_LORD_DEJA, NPC_INFINITE_CHRONO_LORD, NPC_INFINITE_TIMEREAVER, NPC_RIFT_KEEPER_MAGE, NPC_RIFT_KEEPER_WARLOCK, NPC_RIFT_LORD, NPC_RIFT_LORD_2, NPC_TEMPORUS, RAND(), rand_norm(), SAY_RIFT_MOB_SUMMONED, SPELL_RIFT_CHANNEL, WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
Member Data Documentation
_events
EventMap npc_time_rift::_events private
_instance
InstanceScript* npc_time_rift::_instance private
Referenced by DoSummonAtRift(), npc_time_rift(), Reset(), and UpdateAI().
_riftKeeperGUID
ObjectGuid npc_time_rift::_riftKeeperGUID private
Referenced by JustSummoned(), and SummonedCreatureDies().
waveMobIndex
uint8 npc_time_rift::waveMobIndex private
Referenced by DoSelectSummon(), and Reset().
waveMobs
std::vector<uint32> npc_time_rift::waveMobs private
Referenced by DoSelectSummon(), and Reset().