AzeorthCore: AsyncAuctionListingMgr Class Reference
AsyncAuctionListingMgr Class Reference
#include "AsyncAuctionListing.h"
Static Public Member Functions
static void Update (uint32 diff)
static uint32 GetDiff ()
static void ResetDiff ()
static bool IsAuctionListingAllowed ()
static void SetAuctionListingAllowed (bool a)
static std::list< AuctionListItemsDelayEvent > & GetList ()
static std::list< AuctionListItemsDelayEvent > & GetTempList ()
static std::mutex & GetLock ()
static std::mutex & GetTempLock ()
Static Private Attributes
static uint32 auctionListingDiff = 0
static bool auctionListingAllowed = false
static std::list< AuctionListItemsDelayEvent > auctionListingList
static std::list< AuctionListItemsDelayEvent > auctionListingListTemp
static std::mutex auctionListingLock
static std::mutex auctionListingTempLock
Detailed Description
Member Function Documentation
GetDiff()
static uint32 AsyncAuctionListingMgr::GetDiff () inline static
{ return auctionListingDiff; }
References auctionListingDiff.
Referenced by AuctionListingRunnable().
GetList()
static std::list< AuctionListItemsDelayEvent > & AsyncAuctionListingMgr::GetList () inline static
{ return auctionListingList; }
References auctionListingList.
Referenced by AuctionListingRunnable().
GetLock()
static std::mutex & AsyncAuctionListingMgr::GetLock () inline static
{ return auctionListingLock; }
References auctionListingLock.
Referenced by AuctionListingRunnable(), and World::Update().
GetTempList()
static std::list< AuctionListItemsDelayEvent > & AsyncAuctionListingMgr::GetTempList () inline static
{ return auctionListingListTemp; }
References auctionListingListTemp.
Referenced by AuctionListingRunnable(), and WorldSession::HandleAuctionListItems().
GetTempLock()
static std::mutex & AsyncAuctionListingMgr::GetTempLock () inline static
{ return auctionListingTempLock; }
References auctionListingTempLock.
Referenced by AuctionListingRunnable(), and WorldSession::HandleAuctionListItems().
IsAuctionListingAllowed()
static bool AsyncAuctionListingMgr::IsAuctionListingAllowed () inline static
{ return auctionListingAllowed; }
References auctionListingAllowed.
Referenced by AuctionListingRunnable(), and AuctionHouseObject::BuildListAuctionItems().
ResetDiff()
static void AsyncAuctionListingMgr::ResetDiff () inline static
{ auctionListingDiff = 0; }
References auctionListingDiff.
Referenced by AuctionListingRunnable().
SetAuctionListingAllowed()
static void AsyncAuctionListingMgr::SetAuctionListingAllowed (bool a) inline static
{ auctionListingAllowed = a; }
References auctionListingAllowed.
Referenced by World::Update().
Update()
static void AsyncAuctionListingMgr::Update (uint32 diff) inline static
{ auctionListingDiff += diff; }
References auctionListingDiff.
Referenced by World::Update().
Member Data Documentation
auctionListingAllowed
bool AsyncAuctionListingMgr::auctionListingAllowed = false static private
Referenced by IsAuctionListingAllowed(), and SetAuctionListingAllowed().
auctionListingDiff
uint32 AsyncAuctionListingMgr::auctionListingDiff = 0 static private
Referenced by GetDiff(), ResetDiff(), and Update().
auctionListingList
std::list< AuctionListItemsDelayEvent > AsyncAuctionListingMgr::auctionListingList static private
Referenced by GetList().
auctionListingListTemp
std::list< AuctionListItemsDelayEvent > AsyncAuctionListingMgr::auctionListingListTemp static private
Referenced by GetTempList().
auctionListingLock
std::mutex AsyncAuctionListingMgr::auctionListingLock static private
Referenced by GetLock().
auctionListingTempLock
std::mutex AsyncAuctionListingMgr::auctionListingTempLock static private
Referenced by GetTempLock().