AzerothCore: azerothcore-wotlk/src/server/scripts/Outland/outland_script_loader.cpp File Reference
outland_script_loader.cpp File Reference
Functions
void AddSC_boss_exarch_maladaar ()
void AddSC_instance_auchenai_crypts ()
void AddSC_boss_shirrak_the_dead_watcher ()
void AddSC_boss_nexusprince_shaffar ()
void AddSC_boss_pandemonius ()
void AddSC_boss_tavarok ()
void AddSC_instance_mana_tombs ()
void AddSC_boss_talon_king_ikiss ()
void AddSC_boss_anzu ()
void AddSC_boss_darkweaver_syth ()
void AddSC_instance_sethekk_halls ()
void AddSC_instance_shadow_labyrinth ()
void AddSC_boss_ambassador_hellmaw ()
void AddSC_boss_blackheart_the_inciter ()
void AddSC_boss_grandmaster_vorpil ()
void AddSC_boss_murmur ()
void AddSC_boss_illidan ()
void AddSC_boss_shade_of_akama ()
void AddSC_boss_supremus ()
void AddSC_boss_gurtogg_bloodboil ()
void AddSC_boss_mother_shahraz ()
void AddSC_boss_reliquary_of_souls ()
void AddSC_boss_teron_gorefiend ()
void AddSC_boss_najentus ()
void AddSC_boss_illidari_council ()
void AddSC_instance_black_temple ()
void AddSC_boss_fathomlord_karathress ()
void AddSC_boss_hydross_the_unstable ()
void AddSC_boss_lady_vashj ()
void AddSC_boss_leotheras_the_blind ()
void AddSC_boss_morogrim_tidewalker ()
void AddSC_instance_serpentshrine_cavern ()
void AddSC_boss_the_lurker_below ()
void AddSC_boss_hydromancer_thespia ()
void AddSC_boss_mekgineer_steamrigger ()
void AddSC_boss_warlord_kalithresh ()
void AddSC_instance_steam_vault ()
void AddSC_underbog ()
void AddSC_boss_hungarfen ()
void AddSC_boss_ghazan ()
void AddSC_boss_swamplord_muselek ()
void AddSC_boss_the_black_stalker ()
void AddSC_instance_the_underbog ()
void AddSC_the_slave_pens ()
void AddSC_boss_ahune ()
void AddSC_boss_mennu_the_betrayer ()
void AddSC_boss_rokmar_the_crackler ()
void AddSC_boss_quagmirran ()
void AddSC_instance_the_slave_pens ()
void AddSC_boss_gruul ()
void AddSC_boss_high_king_maulgar ()
void AddSC_instance_gruuls_lair ()
void AddSC_boss_broggok ()
void AddSC_boss_kelidan_the_breaker ()
void AddSC_boss_the_maker ()
void AddSC_instance_blood_furnace ()
void AddSC_boss_magtheridon ()
void AddSC_instance_magtheridons_lair ()
void AddSC_boss_grand_warlock_nethekurse ()
void AddSC_boss_porung ()
void AddSC_boss_warbringer_omrogg ()
void AddSC_boss_warchief_kargath_bladefist ()
void AddSC_instance_shattered_halls ()
void AddSC_boss_watchkeeper_gargolmar ()
void AddSC_boss_omor_the_unscarred ()
void AddSC_boss_vazruden_the_herald ()
void AddSC_instance_hellfire_ramparts ()
void AddSC_arcatraz ()
void AddSC_boss_harbinger_skyriss ()
void AddSC_boss_wrath_scryer_soccothrates ()
void AddSC_boss_zereketh_the_unbound ()
void AddSC_boss_dalliah_the_doomsayer ()
void AddSC_instance_arcatraz ()
void AddSC_boss_high_botanist_freywinn ()
void AddSC_boss_laj ()
void AddSC_boss_warp_splinter ()
void AddSC_boss_thorngrin_the_tender ()
void AddSC_boss_commander_sarannis ()
void AddSC_instance_the_botanica ()
void AddSC_boss_alar ()
void AddSC_boss_kaelthas ()
void AddSC_boss_void_reaver ()
void AddSC_boss_high_astromancer_solarian ()
void AddSC_instance_the_eye ()
void AddSC_boss_gatewatcher_iron_hand ()
void AddSC_boss_gatewatcher_gyrokill ()
void AddSC_boss_nethermancer_sepethrea ()
void AddSC_boss_pathaleon_the_calculator ()
void AddSC_boss_mechano_lord_capacitus ()
void AddSC_instance_mechanar ()
void AddSC_blades_edge_mountains ()
void AddSC_boss_doomlordkazzak ()
void AddSC_boss_doomwalker ()
void AddSC_hellfire_peninsula ()
void AddSC_nagrand ()
void AddSC_netherstorm ()
void AddSC_shadowmoon_valley ()
void AddSC_shattrath_city ()
void AddSC_terokkar_forest ()
void AddOutlandScripts ()
Function Documentation
AddOutlandScripts()
void AddOutlandScripts ()
{
    AddSC_boss_exarch_maladaar();           //Auchindoun Auchenai Crypts
    AddSC_instance_auchenai_crypts();
    AddSC_boss_shirrak_the_dead_watcher();
    AddSC_boss_nexusprince_shaffar();       //Auchindoun Mana Tombs
    AddSC_boss_pandemonius();
    AddSC_boss_tavarok();
    AddSC_instance_mana_tombs();
    AddSC_boss_talon_king_ikiss();          //Auchindoun Sekketh Halls
    AddSC_boss_anzu();
    AddSC_boss_darkweaver_syth();
    AddSC_instance_sethekk_halls();
    AddSC_instance_shadow_labyrinth();      //Auchindoun Shadow Labyrinth
    AddSC_boss_ambassador_hellmaw();
    AddSC_boss_blackheart_the_inciter();
    AddSC_boss_grandmaster_vorpil();
    AddSC_boss_murmur();
    AddSC_boss_illidan();                   //Black Temple
    AddSC_boss_shade_of_akama();
    AddSC_boss_supremus();
    AddSC_boss_gurtogg_bloodboil();
    AddSC_boss_mother_shahraz();
    AddSC_boss_reliquary_of_souls();
    AddSC_boss_teron_gorefiend();
    AddSC_boss_najentus();
    AddSC_boss_illidari_council();
    AddSC_instance_black_temple();
    AddSC_boss_fathomlord_karathress();     //CR Serpent Shrine Cavern
    AddSC_boss_hydross_the_unstable();
    AddSC_boss_lady_vashj();
    AddSC_boss_leotheras_the_blind();
    AddSC_boss_morogrim_tidewalker();
    AddSC_instance_serpentshrine_cavern();
    AddSC_boss_the_lurker_below();
    AddSC_boss_hydromancer_thespia();       //CR Steam Vault
    AddSC_boss_mekgineer_steamrigger();
    AddSC_boss_warlord_kalithresh();
    AddSC_instance_steam_vault();
    AddSC_underbog();                       //CR Underbog
    AddSC_boss_hungarfen();
    AddSC_boss_ghazan();
    AddSC_boss_swamplord_muselek();
    AddSC_boss_the_black_stalker();
    AddSC_instance_the_underbog();
    AddSC_the_slave_pens();                 //CR The Slave Pens
    AddSC_boss_ahune();
    AddSC_boss_mennu_the_betrayer();
    AddSC_boss_rokmar_the_crackler();
    AddSC_boss_quagmirran();
    AddSC_instance_the_slave_pens();
    AddSC_boss_gruul();                     //Gruul's Lair
    AddSC_boss_high_king_maulgar();
    AddSC_instance_gruuls_lair();
    AddSC_boss_broggok();                   //HC Blood Furnace
    AddSC_boss_kelidan_the_breaker();
    AddSC_boss_the_maker();
    AddSC_instance_blood_furnace();
    AddSC_boss_magtheridon();               //HC Magtheridon's Lair
    AddSC_instance_magtheridons_lair();
    AddSC_boss_grand_warlock_nethekurse();  //HC Shattered Halls
    AddSC_boss_porung();
    AddSC_boss_warbringer_omrogg();
    AddSC_boss_warchief_kargath_bladefist();
    AddSC_instance_shattered_halls();
    AddSC_boss_watchkeeper_gargolmar();     //HC Ramparts
    AddSC_boss_omor_the_unscarred();
    AddSC_boss_vazruden_the_herald();
    AddSC_instance_hellfire_ramparts();
    AddSC_arcatraz();                       //TK Arcatraz
    AddSC_boss_harbinger_skyriss();
    AddSC_boss_wrath_scryer_soccothrates();
    AddSC_boss_zereketh_the_unbound();
    AddSC_boss_dalliah_the_doomsayer();
    AddSC_instance_arcatraz();
    AddSC_boss_high_botanist_freywinn();    //TK Botanica
    AddSC_boss_laj();
    AddSC_boss_warp_splinter();
    AddSC_boss_thorngrin_the_tender();
    AddSC_boss_commander_sarannis();
    AddSC_instance_the_botanica();
    AddSC_boss_alar();                      //TK The Eye
    AddSC_boss_kaelthas();
    AddSC_boss_void_reaver();
    AddSC_boss_high_astromancer_solarian();
    AddSC_instance_the_eye();
    AddSC_boss_gatewatcher_iron_hand();     //TK The Mechanar
    AddSC_boss_gatewatcher_gyrokill();
    AddSC_boss_nethermancer_sepethrea();
    AddSC_boss_pathaleon_the_calculator();
    AddSC_boss_mechano_lord_capacitus();
    AddSC_instance_mechanar();
    AddSC_blades_edge_mountains();
    AddSC_boss_doomlordkazzak();
    AddSC_boss_doomwalker();
    AddSC_hellfire_peninsula();
    AddSC_nagrand();
    AddSC_netherstorm();
    AddSC_shadowmoon_valley();
    AddSC_shattrath_city();
    AddSC_terokkar_forest();
    //AddSC_zangarmarsh();
}
References AddSC_arcatraz(), AddSC_blades_edge_mountains(), AddSC_boss_ahune(), AddSC_boss_alar(), AddSC_boss_ambassador_hellmaw(), AddSC_boss_anzu(), AddSC_boss_blackheart_the_inciter(), AddSC_boss_broggok(), AddSC_boss_commander_sarannis(), AddSC_boss_dalliah_the_doomsayer(), AddSC_boss_darkweaver_syth(), AddSC_boss_doomlordkazzak(), AddSC_boss_doomwalker(), AddSC_boss_exarch_maladaar(), AddSC_boss_fathomlord_karathress(), AddSC_boss_gatewatcher_gyrokill(), AddSC_boss_gatewatcher_iron_hand(), AddSC_boss_ghazan(), AddSC_boss_grand_warlock_nethekurse(), AddSC_boss_grandmaster_vorpil(), AddSC_boss_gruul(), AddSC_boss_gurtogg_bloodboil(), AddSC_boss_harbinger_skyriss(), AddSC_boss_high_astromancer_solarian(), AddSC_boss_high_botanist_freywinn(), AddSC_boss_high_king_maulgar(), AddSC_boss_hungarfen(), AddSC_boss_hydromancer_thespia(), AddSC_boss_hydross_the_unstable(), AddSC_boss_illidan(), AddSC_boss_illidari_council(), AddSC_boss_kaelthas(), AddSC_boss_kelidan_the_breaker(), AddSC_boss_lady_vashj(), AddSC_boss_laj(), AddSC_boss_leotheras_the_blind(), AddSC_boss_magtheridon(), AddSC_boss_mechano_lord_capacitus(), AddSC_boss_mekgineer_steamrigger(), AddSC_boss_mennu_the_betrayer(), AddSC_boss_morogrim_tidewalker(), AddSC_boss_mother_shahraz(), AddSC_boss_murmur(), AddSC_boss_najentus(), AddSC_boss_nethermancer_sepethrea(), AddSC_boss_nexusprince_shaffar(), AddSC_boss_omor_the_unscarred(), AddSC_boss_pandemonius(), AddSC_boss_pathaleon_the_calculator(), AddSC_boss_porung(), AddSC_boss_quagmirran(), AddSC_boss_reliquary_of_souls(), AddSC_boss_rokmar_the_crackler(), AddSC_boss_shade_of_akama(), AddSC_boss_shirrak_the_dead_watcher(), AddSC_boss_supremus(), AddSC_boss_swamplord_muselek(), AddSC_boss_talon_king_ikiss(), AddSC_boss_tavarok(), AddSC_boss_teron_gorefiend(), AddSC_boss_the_black_stalker(), AddSC_boss_the_lurker_below(), AddSC_boss_the_maker(), AddSC_boss_thorngrin_the_tender(), AddSC_boss_vazruden_the_herald(), AddSC_boss_void_reaver(), AddSC_boss_warbringer_omrogg(), AddSC_boss_warchief_kargath_bladefist(), AddSC_boss_warlord_kalithresh(), AddSC_boss_warp_splinter(), AddSC_boss_watchkeeper_gargolmar(), AddSC_boss_wrath_scryer_soccothrates(), AddSC_boss_zereketh_the_unbound(), AddSC_hellfire_peninsula(), AddSC_instance_arcatraz(), AddSC_instance_auchenai_crypts(), AddSC_instance_black_temple(), AddSC_instance_blood_furnace(), AddSC_instance_gruuls_lair(), AddSC_instance_hellfire_ramparts(), AddSC_instance_magtheridons_lair(), AddSC_instance_mana_tombs(), AddSC_instance_mechanar(), AddSC_instance_serpentshrine_cavern(), AddSC_instance_sethekk_halls(), AddSC_instance_shadow_labyrinth(), AddSC_instance_shattered_halls(), AddSC_instance_steam_vault(), AddSC_instance_the_botanica(), AddSC_instance_the_eye(), AddSC_instance_the_slave_pens(), AddSC_instance_the_underbog(), AddSC_nagrand(), AddSC_netherstorm(), AddSC_shadowmoon_valley(), AddSC_shattrath_city(), AddSC_terokkar_forest(), AddSC_the_slave_pens(), and AddSC_underbog().
AddSC_arcatraz()
void AddSC_arcatraz ()
{
    new npc_millhouse_manastorm();
    new npc_warden_mellichar();
    RegisterSpellScript(spell_arcatraz_soul_steal_aura);
}
References RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_blades_edge_mountains()
void AddSC_blades_edge_mountains ()
{
    // Ours
    new npc_deaths_door_fell_cannon_target_bunny();
    new npc_deaths_fel_cannon();
    RegisterSpellScript(spell_npc22275_crystal_prison_aura);
    // Theirs
    new npc_nether_drake();
    new npc_daranelle();
    new npc_simon_bunny();
    new go_simon_cluster();
    new go_apexis_relic();
    new npc_oscillating_frequency_scanner_master_bunny();
    RegisterSpellScript(spell_oscillating_field);
}
References RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_ahune()
void AddSC_boss_ahune ()
{
    RegisterTheSlavePensCreatureAI(boss_ahune);
    RegisterTheSlavePensCreatureAI(npc_frozen_core);
    RegisterTheSlavePensCreatureAI(npc_earthen_ring_flamecaller);
    RegisterTheSlavePensCreatureAI(npc_ahune_bunny);
    RegisterTheSlavePensCreatureAI(npc_ahune_ice_spear_bunny);
    RegisterGameObjectAI(go_ahune_ice_spear);
    RegisterGameObjectAI(go_ahune_ice_stone);
    RegisterSpellScript(spell_ahune_synch_health);
    RegisterSpellScript(spell_summoning_rhyme_aura);
    RegisterSpellScript(spell_summon_ice_spear_delayer);
    RegisterSpellScript(spell_ice_spear_control_aura);
    RegisterSpellScript(spell_ice_spear_target_picker);
    RegisterSpellScript(spell_slippery_floor_periodic);
    RegisterSpellScript(spell_ahune_spanky_hands);
    RegisterSpellScript(spell_ahune_minion_despawner);
    RegisterSpellScript(spell_ice_bombardment_dest_picker);
}
References RegisterGameObjectAI, RegisterSpellScript, and RegisterTheSlavePensCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_alar()
void AddSC_boss_alar ()
{
    RegisterTheEyeAI(boss_alar);
    RegisterSpellScript(spell_alar_flame_quills);
    RegisterSpellScript(spell_alar_ember_blast);
    RegisterSpellScript(spell_alar_dive_bomb);
}
References RegisterSpellScript, and RegisterTheEyeAI.
Referenced by AddOutlandScripts().
AddSC_boss_ambassador_hellmaw()
void AddSC_boss_ambassador_hellmaw ()
{
    RegisterShadowLabyrinthCreatureAI(boss_ambassador_hellmaw);
}
References RegisterShadowLabyrinthCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_anzu()
void AddSC_boss_anzu ()
{
    RegisterSethekkHallsCreatureAI(boss_anzu);
    RegisterSethekkHallsCreatureAI(npc_anzu_spirit);
}
References RegisterSethekkHallsCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_blackheart_the_inciter()
void AddSC_boss_blackheart_the_inciter ()
{
    RegisterShadowLabyrinthCreatureAI(boss_blackheart_the_inciter);
}
References RegisterShadowLabyrinthCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_broggok()
void AddSC_boss_broggok ()
{
    RegisterBloodFurnaceCreatureAI(boss_broggok);
    RegisterSpellScript(spell_broggok_poison_cloud);
    new go_broggok_lever();
}
References RegisterBloodFurnaceCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_commander_sarannis()
void AddSC_boss_commander_sarannis ()
{
    RegisterTheBotanicaCreatureAI(boss_commander_sarannis);
    RegisterSpellScript(spell_commander_sarannis_arcane_devastation);
    RegisterSpellScript(spell_commander_sarannis_summon_reinforcements);
}
References RegisterSpellScript, and RegisterTheBotanicaCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_dalliah_the_doomsayer()
void AddSC_boss_dalliah_the_doomsayer ()
{
    RegisterArcatrazCreatureAI(boss_dalliah_the_doomsayer);
}
References RegisterArcatrazCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_darkweaver_syth()
void AddSC_boss_darkweaver_syth ()
{
    RegisterSethekkHallsCreatureAI(boss_darkweaver_syth);
}
References RegisterSethekkHallsCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_doomlordkazzak()
void AddSC_boss_doomlordkazzak ()
{
    new boss_doomlord_kazzak();
    RegisterSpellScript(spell_mark_of_kazzak_aura);
}
References RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_doomwalker()
void AddSC_boss_doomwalker ()
{
    RegisterCreatureAI(boss_doomwalker);
}
References RegisterCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_exarch_maladaar()
void AddSC_boss_exarch_maladaar ()
{
    RegisterAuchenaiCryptsCreatureAI(boss_exarch_maladaar);
    RegisterAuchenaiCryptsCreatureAI(npc_stolen_soul);
}
References RegisterAuchenaiCryptsCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_fathomlord_karathress()
void AddSC_boss_fathomlord_karathress ()
{
    RegisterSerpentShrineAI(boss_fathomlord_karathress);
    RegisterSerpentShrineAI(boss_fathomguard_sharkkis);
    RegisterSerpentShrineAI(boss_fathomguard_tidalvess);
    RegisterSerpentShrineAI(boss_fathomguard_caribdis);
    RegisterSpellScript(spell_karathress_power_of_tidalvess);
    RegisterSpellScript(spell_karathress_power_of_caribdis);
}
References RegisterSerpentShrineAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_gatewatcher_gyrokill()
void AddSC_boss_gatewatcher_gyrokill ()
{
    RegisterMechanarCreatureAI(boss_gatewatcher_gyrokill);
}
References RegisterMechanarCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_gatewatcher_iron_hand()
void AddSC_boss_gatewatcher_iron_hand ()
{
    RegisterMechanarCreatureAI(boss_gatewatcher_iron_hand);
}
References RegisterMechanarCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_ghazan()
void AddSC_boss_ghazan ()
{
    RegisterUnderbogCreatureAI(boss_ghazan);
    new at_underbog_ghazan();
}
References RegisterUnderbogCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_grand_warlock_nethekurse()
void AddSC_boss_grand_warlock_nethekurse ()
{
    RegisterShatteredHallsCreatureAI(boss_grand_warlock_nethekurse);
    RegisterSpellScript(spell_tsh_shadow_bolt);
    RegisterSpellScript(spell_target_fissures);
    new at_rp_nethekurse();
}
References RegisterShatteredHallsCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_grandmaster_vorpil()
void AddSC_boss_grandmaster_vorpil ()
{
    RegisterShadowLabyrinthCreatureAI(boss_grandmaster_vorpil);
    RegisterShadowLabyrinthCreatureAI(npc_voidtraveler);
}
References RegisterShadowLabyrinthCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_gruul()
void AddSC_boss_gruul ()
{
    RegisterGruulsLairAI(boss_gruul);
    RegisterGruulsLairAI(npc_invisible_tractor_beam_source);
    RegisterSpellScript(spell_gruul_ground_slam);
    RegisterSpellScript(spell_tractor_beam_creator);
    RegisterSpellScript(spell_gruul_ground_slam_trigger);
    RegisterSpellScript(spell_gruul_shatter);
    RegisterSpellScript(spell_gruul_shatter_effect);
}
References RegisterGruulsLairAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_gurtogg_bloodboil()
void AddSC_boss_gurtogg_bloodboil ()
{
    RegisterBlackTempleCreatureAI(boss_gurtogg_bloodboil);
    RegisterSpellScript(spell_gurtogg_bloodboil);
    RegisterSpellScript(spell_gurtogg_eject);
}
References RegisterBlackTempleCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_harbinger_skyriss()
void AddSC_boss_harbinger_skyriss ()
{
    RegisterArcatrazCreatureAI(boss_harbinger_skyriss);
}
References RegisterArcatrazCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_high_astromancer_solarian()
void AddSC_boss_high_astromancer_solarian ()
{
    RegisterTheEyeAI(boss_high_astromancer_solarian);
    RegisterSpellScript(spell_astromancer_wrath_of_the_astromancer);
    RegisterSpellScript(spell_astromancer_solarian_transform);
}
References RegisterSpellScript, and RegisterTheEyeAI.
Referenced by AddOutlandScripts().
AddSC_boss_high_botanist_freywinn()
void AddSC_boss_high_botanist_freywinn ()
{
    RegisterTheBotanicaCreatureAI(boss_high_botanist_freywinn);
}
References RegisterTheBotanicaCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_high_king_maulgar()
void AddSC_boss_high_king_maulgar ()
{
    RegisterGruulsLairAI(boss_high_king_maulgar);
    RegisterGruulsLairAI(boss_kiggler_the_crazed);
    RegisterGruulsLairAI(boss_blindeye_the_seer);
    RegisterGruulsLairAI(boss_olm_the_summoner);
    RegisterGruulsLairAI(boss_krosh_firehand);
}
References RegisterGruulsLairAI.
Referenced by AddOutlandScripts().
AddSC_boss_hungarfen()
void AddSC_boss_hungarfen ()
{
    RegisterUnderbogCreatureAI(boss_hungarfen);
    RegisterUnderbogCreatureAI(npc_underbog_mushroom);
    RegisterSpellScript(spell_spore_cloud);
    RegisterSpellScript(spell_despawn_underbog_mushrooms);
}
References RegisterSpellScript, and RegisterUnderbogCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_hydromancer_thespia()
void AddSC_boss_hydromancer_thespia ()
{
    RegisterSteamvaultCreatureAI(boss_hydromancer_thespia);
}
References RegisterSteamvaultCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_hydross_the_unstable()
void AddSC_boss_hydross_the_unstable ()
{
    RegisterSerpentShrineAI(boss_hydross_the_unstable);
    RegisterSpellScript(spell_hydross_cleansing_field_aura);
    RegisterSpellScript(spell_hydross_cleansing_field_command);
    RegisterSpellScript(spell_hydross_mark_of_hydross);
}
References RegisterSerpentShrineAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_illidan()
void AddSC_boss_illidan ()
{
    RegisterBlackTempleCreatureAI(boss_illidan_stormrage);
    RegisterBlackTempleCreatureAI(npc_maiev_illidan);
    RegisterBlackTempleCreatureAI(npc_akama_illidan);
    RegisterBlackTempleCreatureAI(npc_parasitic_shadowfiend);
    RegisterBlackTempleCreatureAI(npc_blade_of_azzinoth);
    RegisterBlackTempleCreatureAI(npc_flame_of_azzinoth);
    RegisterSpellScript(spell_illidan_draw_soul);
    RegisterSpellScript(spell_illidan_parasitic_shadowfiend_aura);
    RegisterSpellAndAuraScriptPair(spell_illidan_parasitic_shadowfiend_trigger, spell_illidan_parasitic_shadowfiend_trigger_aura);
    RegisterSpellScript(spell_illidan_glaive_throw);
    RegisterSpellScript(spell_illidan_tear_of_azzinoth_summon_channel_aura);
    RegisterSpellAndAuraScriptPair(spell_illidan_shadow_prison, spell_illidan_shadow_prison_aura);
    RegisterSpellScript(spell_illidan_demon_transform1_aura);
    RegisterSpellScript(spell_illidan_demon_transform2_aura);
    RegisterSpellScript(spell_illidan_flame_burst);
    RegisterSpellScript(spell_illidan_found_target);
    RegisterSpellScript(spell_illidan_cage_trap);
    RegisterSpellScript(spell_illidan_cage_trap_stun_aura);
}
References RegisterBlackTempleCreatureAI, RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_illidari_council()
void AddSC_boss_illidari_council ()
{
    RegisterBlackTempleCreatureAI(boss_illidari_council);
    RegisterBlackTempleCreatureAI(boss_gathios_the_shatterer);
    RegisterBlackTempleCreatureAI(boss_lady_malande);
    RegisterBlackTempleCreatureAI(boss_veras_darkshadow);
    RegisterBlackTempleCreatureAI(boss_high_nethermancer_zerevor);
    RegisterSpellScript(spell_illidari_council_balance_of_power_aura);
    RegisterSpellScript(spell_illidari_council_empyreal_balance);
    RegisterSpellScript(spell_illidari_council_empyreal_equivalency);
    RegisterSpellScript(spell_illidari_council_reflective_shield_aura);
    RegisterSpellScript(spell_illidari_council_circle_of_healing);
    RegisterSpellScript(spell_illidari_council_judgement);
    RegisterSpellScript(spell_illidari_council_deadly_strike_aura);
}
References RegisterBlackTempleCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_kaelthas()
void AddSC_boss_kaelthas ()
{
    RegisterTheEyeAI(boss_kaelthas);
    RegisterTheEyeAI(npc_lord_sanguinar);
    RegisterTheEyeAI(npc_capernian);
    RegisterTheEyeAI(npc_telonicus);
    RegisterTheEyeAI(npc_thaladred);
    RegisterSpellScript(spell_kaelthas_remote_toy);
    RegisterSpellScript(spell_kaelthas_summon_weapons);
    RegisterSpellScript(spell_kaelthas_mind_control);
    RegisterSpellScript(spell_kaelthas_burn);
    RegisterSpellScript(spell_kaelthas_flame_strike);
    RegisterSpellScript(spell_kaelthas_gravity_lapse);
    RegisterSpellScript(spell_kaelthas_nether_beam);
    RegisterSpellScript(spell_kaelthas_summon_nether_vapor);
    RegisterSpellScript(spell_kael_pyroblast);
    RegisterSpellScript(spell_kaelthas_remove_enchanted_weapons);
    RegisterSpellScript(spell_kaelthas_kael_explodes);
}
References RegisterSpellScript, and RegisterTheEyeAI.
Referenced by AddOutlandScripts().
AddSC_boss_kelidan_the_breaker()
void AddSC_boss_kelidan_the_breaker ()
{
    RegisterBloodFurnaceCreatureAI(boss_kelidan_the_breaker);
}
References RegisterBloodFurnaceCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_lady_vashj()
void AddSC_boss_lady_vashj ()
{
    RegisterSerpentShrineAI(boss_lady_vashj);
    RegisterSpellScript(spell_lady_vashj_magic_barrier);
    RegisterSpellScript(spell_lady_vashj_remove_tainted_cores);
    RegisterSpellScript(spell_lady_vashj_summon_sporebat);
    RegisterSpellScript(spell_lady_vashj_spore_drop_effect);
    RegisterSpellScript(spell_lady_vashj_summons);
}
References RegisterSerpentShrineAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_laj()
void AddSC_boss_laj ()
{
    RegisterTheBotanicaCreatureAI(boss_laj);
}
References RegisterTheBotanicaCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_leotheras_the_blind()
void AddSC_boss_leotheras_the_blind ()
{
    RegisterSerpentShrineAI(boss_leotheras_the_blind);
    RegisterSerpentShrineAI(npc_inner_demon);
    RegisterSpellScript(spell_leotheras_whirlwind);
    RegisterSpellScript(spell_leotheras_chaos_blast);
    RegisterSpellAndAuraScriptPair(spell_leotheras_insidious_whisper, spell_leotheras_insidious_whisper_aura);
    RegisterSpellScript(spell_leotheras_demon_link);
    RegisterSpellScript(spell_leotheras_clear_consuming_madness);
}
References RegisterSerpentShrineAI, RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_magtheridon()
void AddSC_boss_magtheridon ()
{
    RegisterMagtheridonsLairCreatureAI(boss_magtheridon);
    RegisterMagtheridonsLairCreatureAI(npc_target_trigger);
    RegisterSpellScript(spell_magtheridon_blaze);
    RegisterSpellScript(spell_magtheridon_shadow_grasp);
    RegisterSpellScript(spell_magtheridon_shadow_grasp_visual);
    RegisterSpellScript(spell_magtheridon_quake);
    RegisterSpellScript(spell_magtheridon_debris_target_selector);
    new go_manticron_cube();
}
References RegisterMagtheridonsLairCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_mechano_lord_capacitus()
void AddSC_boss_mechano_lord_capacitus ()
{
    RegisterMechanarCreatureAI(boss_mechano_lord_capacitus);
    RegisterSpellScript(spell_capacitus_polarity_charge);
    RegisterSpellScript(spell_capacitus_polarity_charge_aura);
    RegisterSpellScript(spell_capacitus_polarity_shift);
}
References RegisterMechanarCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_mekgineer_steamrigger()
void AddSC_boss_mekgineer_steamrigger ()
{
    RegisterSteamvaultCreatureAI(boss_mekgineer_steamrigger);
}
References RegisterSteamvaultCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_mennu_the_betrayer()
void AddSC_boss_mennu_the_betrayer ()
{
    RegisterTheSlavePensCreatureAI(boss_mennu_the_betrayer);
}
References RegisterTheSlavePensCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_morogrim_tidewalker()
void AddSC_boss_morogrim_tidewalker ()
{
    RegisterSerpentShrineAI(boss_morogrim_tidewalker);
    RegisterSpellScript(spell_morogrim_tidewalker_watery_grave);
    RegisterSpellScript(spell_morogrim_tidewalker_water_globule_new_target);
}
References RegisterSerpentShrineAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_mother_shahraz()
void AddSC_boss_mother_shahraz ()
{
    RegisterBlackTempleCreatureAI(boss_mother_shahraz);
    RegisterSpellScript(spell_mother_shahraz_random_periodic_aura);
    RegisterSpellScript(spell_mother_shahraz_beam_periodic_aura);
    RegisterSpellScript(spell_mother_shahraz_saber_lash_aura);
    RegisterSpellScript(spell_mother_shahraz_fatal_attraction);
    RegisterSpellScript(spell_mother_shahraz_fatal_attraction_dummy);
}
References RegisterBlackTempleCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_murmur()
void AddSC_boss_murmur ()
{
    RegisterShadowLabyrinthCreatureAI(boss_murmur);
    RegisterSpellScript(spell_murmur_thundering_storm);
    RegisterSpellScript(spell_shockwave_knockback);
    RegisterSpellScript(spell_murmur_sonic_boom_effect);
}
References RegisterShadowLabyrinthCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_najentus()
void AddSC_boss_najentus ()
{
    RegisterBlackTempleCreatureAI(boss_najentus);
    RegisterSpellScript(spell_najentus_needle_spine);
    RegisterSpellScript(spell_najentus_hurl_spine);
    RegisterSpellScript(spell_najentus_remove_spines);
}
References RegisterBlackTempleCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_nethermancer_sepethrea()
void AddSC_boss_nethermancer_sepethrea ()
{
    RegisterMechanarCreatureAI(boss_nethermancer_sepethrea);
    RegisterMechanarCreatureAI(npc_raging_flames);
    RegisterSpellScript(spell_ragin_flames_inferno);
}
References RegisterMechanarCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_nexusprince_shaffar()
void AddSC_boss_nexusprince_shaffar ()
{
    RegisterManaTombsCreatureAI(boss_nexusprince_shaffar);
    RegisterManaTombsCreatureAI(npc_yor);
}
References RegisterManaTombsCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_omor_the_unscarred()
void AddSC_boss_omor_the_unscarred ()
{
    RegisterHellfireRampartsCreatureAI(boss_omor_the_unscarred);
}
References RegisterHellfireRampartsCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_pandemonius()
void AddSC_boss_pandemonius ()
{
    RegisterManaTombsCreatureAI(boss_pandemonius);
}
References RegisterManaTombsCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_pathaleon_the_calculator()
void AddSC_boss_pathaleon_the_calculator ()
{
    RegisterMechanarCreatureAI(boss_pathaleon_the_calculator);
}
References RegisterMechanarCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_porung()
void AddSC_boss_porung ()
{
    RegisterShatteredHallsCreatureAI(boss_porung);
    RegisterShatteredHallsCreatureAI(npc_shattered_hand_scout);
    RegisterSpellScript(spell_tsh_shoot_flame_arrow);
}
References RegisterShatteredHallsCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_quagmirran()
void AddSC_boss_quagmirran ()
{
    RegisterTheSlavePensCreatureAI(boss_quagmirran);
}
References RegisterTheSlavePensCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_reliquary_of_souls()
void AddSC_boss_reliquary_of_souls ()
{
    new boss_reliquary_of_souls();
    new boss_essence_of_suffering();
    new boss_essence_of_desire();
    new boss_essence_of_anger();
    RegisterSpellScript(spell_reliquary_of_souls_aura_of_suffering_aura);
    RegisterSpellAndAuraScriptPair(spell_reliquary_of_souls_fixate, spell_reliquary_of_souls_fixate_aura);
    RegisterSpellScript(spell_reliquary_of_souls_aura_of_desire_aura);
    RegisterSpellScript(spell_reliquary_of_souls_aura_of_anger_aura);
    RegisterSpellScript(spell_reliquary_of_souls_spite_aura);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_rokmar_the_crackler()
void AddSC_boss_rokmar_the_crackler ()
{
    RegisterTheSlavePensCreatureAI(boss_rokmar_the_crackler);
}
References RegisterTheSlavePensCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_shade_of_akama()
void AddSC_boss_shade_of_akama ()
{
    RegisterBlackTempleCreatureAI(boss_shade_of_akama);
    RegisterBlackTempleCreatureAI(npc_akama_shade);
    RegisterBlackTempleCreatureAI(npc_creature_generator_akama);
    RegisterBlackTempleCreatureAI(npc_ashtongue_channeler);
    RegisterBlackTempleCreatureAI(npc_ashtongue_sorcerer);
    RegisterSpellScript(spell_shade_of_akama_shade_soul_channel);
    RegisterSpellScript(spell_shade_of_akama_akama_soul_expel);
}
References RegisterBlackTempleCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_shirrak_the_dead_watcher()
void AddSC_boss_shirrak_the_dead_watcher ()
{
    RegisterAuchenaiCryptsCreatureAI(boss_shirrak_the_dead_watcher);
    RegisterSpellScript(spell_auchenai_possess);
}
References RegisterAuchenaiCryptsCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_supremus()
void AddSC_boss_supremus ()
{
    RegisterBlackTempleCreatureAI(npc_supremus_punch_invisible_stalker);
    RegisterBlackTempleCreatureAI(boss_supremus);
}
References RegisterBlackTempleCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_swamplord_muselek()
void AddSC_boss_swamplord_muselek ()
{
    RegisterUnderbogCreatureAI(boss_swamplord_muselek);
}
References RegisterUnderbogCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_talon_king_ikiss()
void AddSC_boss_talon_king_ikiss ()
{
    RegisterSethekkHallsCreatureAI(boss_talon_king_ikiss);
    RegisterSpellScript(spell_talon_king_ikiss_blink);
}
References RegisterSethekkHallsCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_tavarok()
void AddSC_boss_tavarok ()
{
    RegisterManaTombsCreatureAI(boss_tavarok);
}
References RegisterManaTombsCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_teron_gorefiend()
void AddSC_boss_teron_gorefiend ()
{
    RegisterBlackTempleCreatureAI(boss_teron_gorefiend);
    RegisterBlackTempleCreatureAI(npc_vengeful_spirit);
    RegisterSpellScript(spell_teron_gorefiend_shadow_of_death);
    RegisterSpellScript(spell_teron_gorefiend_spirit_lance);
    RegisterSpellScript(spell_teron_gorefiend_spiritual_vengeance);
    RegisterSpellScript(spell_teron_gorefiend_shadowy_construct);
    RegisterSpellScript(spell_teron_gorefiend_shadow_of_death_remove);
}
References RegisterBlackTempleCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_the_black_stalker()
void AddSC_boss_the_black_stalker ()
{
    RegisterUnderbogCreatureAI(boss_the_black_stalker);
    RegisterSpellScript(spell_the_black_stalker_levitate);
    RegisterSpellScript(spell_the_black_stalker_levitation_pulse);
    RegisterSpellScript(spell_the_black_stalker_someone_grab_me);
    RegisterSpellScript(spell_the_black_stalker_magnetic_pull);
}
References RegisterSpellScript, and RegisterUnderbogCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_the_lurker_below()
void AddSC_boss_the_lurker_below ()
{
    RegisterSerpentShrineAI(boss_the_lurker_below);
    new go_strange_pool();
    RegisterSpellScript(spell_lurker_below_spout);
    RegisterSpellScript(spell_lurker_below_spout_cone);
}
References RegisterSerpentShrineAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_the_maker()
void AddSC_boss_the_maker ()
{
    RegisterBloodFurnaceCreatureAI(boss_the_maker);
}
References RegisterBloodFurnaceCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_thorngrin_the_tender()
void AddSC_boss_thorngrin_the_tender ()
{
    RegisterTheBotanicaCreatureAI(boss_thorngrin_the_tender);
}
References RegisterTheBotanicaCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_vazruden_the_herald()
void AddSC_boss_vazruden_the_herald ()
{
    RegisterHellfireRampartsCreatureAI(boss_vazruden_the_herald);
    RegisterHellfireRampartsCreatureAI(boss_vazruden);
    RegisterHellfireRampartsCreatureAI(boss_nazan);
    RegisterSpellScript(spell_vazruden_fireball);
    RegisterSpellScript(spell_vazruden_call_nazan);
}
References RegisterHellfireRampartsCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_void_reaver()
void AddSC_boss_void_reaver ()
{
    RegisterTheEyeAI(boss_void_reaver);
}
References RegisterTheEyeAI.
Referenced by AddOutlandScripts().
AddSC_boss_warbringer_omrogg()
void AddSC_boss_warbringer_omrogg ()
{
    RegisterShatteredHallsCreatureAI(boss_warbringer_omrogg);
    RegisterSpellScript(spell_burning_maul);
}
References RegisterShatteredHallsCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_warchief_kargath_bladefist()
void AddSC_boss_warchief_kargath_bladefist ()
{
    RegisterShatteredHallsCreatureAI(boss_warchief_kargath_bladefist);
    RegisterShatteredHallsCreatureAI(npc_warchief_portal);
    RegisterSpellScript(spell_blade_dance_targeting);
}
References RegisterShatteredHallsCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_warlord_kalithresh()
void AddSC_boss_warlord_kalithresh ()
{
    RegisterSteamvaultCreatureAI(boss_warlord_kalithresh);
    RegisterSpellScript(spell_warlords_rage);
}
References RegisterSpellScript, and RegisterSteamvaultCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_warp_splinter()
void AddSC_boss_warp_splinter ()
{
    RegisterTheBotanicaCreatureAI(boss_warp_splinter);
}
References RegisterTheBotanicaCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_watchkeeper_gargolmar()
void AddSC_boss_watchkeeper_gargolmar ()
{
    RegisterHellfireRampartsCreatureAI(boss_watchkeeper_gargolmar);
    RegisterSpellScript(spell_gargolmar_retalliation);
}
References RegisterHellfireRampartsCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_boss_wrath_scryer_soccothrates()
void AddSC_boss_wrath_scryer_soccothrates ()
{
    RegisterArcatrazCreatureAI(boss_wrath_scryer_soccothrates);
}
References RegisterArcatrazCreatureAI.
Referenced by AddOutlandScripts().
AddSC_boss_zereketh_the_unbound()
void AddSC_boss_zereketh_the_unbound ()
{
    RegisterArcatrazCreatureAI(boss_zereketh_the_unbound);
}
References RegisterArcatrazCreatureAI.
Referenced by AddOutlandScripts().
AddSC_hellfire_peninsula()
void AddSC_hellfire_peninsula ()
{
    // Ours
    RegisterSpellScript(spell_q10935_the_exorcism_of_colonel_jules);
    // Theirs
    new npc_aeranas();
    new npc_ancestral_wolf();
    new npc_wounded_blood_elf();
    new npc_fel_guard_hound();
    new go_beacon();
    RegisterCreatureAI(npc_magister_aledis);
    RegisterGameObjectAI(go_magtheridons_head);
}
References RegisterCreatureAI, RegisterGameObjectAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_instance_arcatraz()
void AddSC_instance_arcatraz ()
{
    new instance_arcatraz();
}
Referenced by AddOutlandScripts().
AddSC_instance_auchenai_crypts()
void AddSC_instance_auchenai_crypts ()
{
    new instance_auchenai_crypts();
}
Referenced by AddOutlandScripts().
AddSC_instance_black_temple()
void AddSC_instance_black_temple ()
{
    new instance_black_temple();
    RegisterSpellScript(spell_black_template_harpooners_mark_aura);
    RegisterSpellScript(spell_black_template_free_friend);
    RegisterSpellScript(spell_black_temple_curse_of_the_bleakheart_aura);
    RegisterSpellScript(spell_black_temple_skeleton_shot_aura);
    RegisterSpellScript(spell_black_temple_wyvern_sting_aura);
    RegisterSpellScript(spell_black_temple_charge_rage_aura);
    RegisterSpellScript(spell_black_temple_shadow_inferno_aura);
    RegisterSpellScript(spell_black_temple_spell_absorption_aura);
    RegisterSpellScript(spell_black_temple_bloodbolt);
    RegisterSpellScript(spell_black_temple_consuming_strikes_aura);
    RegisterSpellScript(spell_black_temple_curse_of_vitality_aura);
    RegisterSpellScript(spell_black_temple_dementia_aura);
    RegisterSpellScript(spell_black_temple_summon_shadowfiends);
    RegisterSpellScript(spell_black_temple_l5_arcane_charge);
}
References RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_instance_blood_furnace()
void AddSC_instance_blood_furnace ()
{
    new instance_blood_furnace();
}
Referenced by AddOutlandScripts().
AddSC_instance_gruuls_lair()
void AddSC_instance_gruuls_lair ()
{
    new instance_gruuls_lair();
}
Referenced by AddOutlandScripts().
AddSC_instance_hellfire_ramparts()
void AddSC_instance_hellfire_ramparts ()
{
    new instance_hellfire_ramparts();
}
Referenced by AddOutlandScripts().
AddSC_instance_magtheridons_lair()
void AddSC_instance_magtheridons_lair ()
{
    new instance_magtheridons_lair();
}
Referenced by AddOutlandScripts().
AddSC_instance_mana_tombs()
void AddSC_instance_mana_tombs ()
{
    new instance_mana_tombs();
}
Referenced by AddOutlandScripts().
AddSC_instance_mechanar()
void AddSC_instance_mechanar ()
{
    new instance_mechanar();
}
Referenced by AddOutlandScripts().
AddSC_instance_serpentshrine_cavern()
void AddSC_instance_serpentshrine_cavern ()
{
    new instance_serpent_shrine();
    RegisterSpellScript(spell_serpentshrine_cavern_serpentshrine_parasite);
    RegisterSpellAndAuraScriptPair(spell_serpentshrine_cavern_serpentshrine_parasite_trigger, spell_serpentshrine_cavern_serpentshrine_parasite_trigger_aura);
    RegisterSpellScript(spell_serpentshrine_cavern_infection);
    RegisterSpellScript(spell_serpentshrine_cavern_coilfang_water);
    RegisterSerpentShrineAI(npc_rancid_mushroom);
    RegisterSpellScript(spell_rancid_spore_cloud);
}
References RegisterSerpentShrineAI, RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_instance_sethekk_halls()
void AddSC_instance_sethekk_halls ()
{
    new instance_sethekk_halls();
}
Referenced by AddOutlandScripts().
AddSC_instance_shadow_labyrinth()
void AddSC_instance_shadow_labyrinth ()
{
    new instance_shadow_labyrinth();
    RegisterSpellScript(spell_mark_of_malice);
}
References RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_instance_shattered_halls()
void AddSC_instance_shattered_halls ()
{
    new instance_shattered_halls();
    new at_shattered_halls_execution();
}
Referenced by AddOutlandScripts().
AddSC_instance_steam_vault()
void AddSC_instance_steam_vault ()
{
    new go_main_chambers_access_panel();
    new instance_steam_vault();
}
Referenced by AddOutlandScripts().
AddSC_instance_the_botanica()
void AddSC_instance_the_botanica ()
{
    new instance_the_botanica();
    RegisterSpellScript(spell_botanica_call_of_the_falcon_aura);
    RegisterSpellScript(spell_botanica_shift_form_aura);
}
References RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_instance_the_eye()
void AddSC_instance_the_eye ()
{
    new instance_the_eye();
    RegisterSpellScript(spell_the_eye_countercharge_aura);
}
References RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_instance_the_slave_pens()
void AddSC_instance_the_slave_pens ()
{
    new instance_the_slave_pens();
}
Referenced by AddOutlandScripts().
AddSC_instance_the_underbog()
void AddSC_instance_the_underbog ()
{
    new instance_the_underbog();
}
Referenced by AddOutlandScripts().
AddSC_nagrand()
void AddSC_nagrand ()
{
    new npc_maghar_captive();
    new npc_creditmarker_visit_with_ancestors();
    new npc_kurenai_captive();
    new go_warmaul_prison();
}
Referenced by AddOutlandScripts().
AddSC_netherstorm()
void AddSC_netherstorm ()
{
    // Ours
    new npc_captain_saeed();
    // Theirs
    new npc_commander_dawnforge();
    new at_commander_dawnforge();
    new npc_bessy();
    new npc_maxx_a_million_escort();
    RegisterSpellAndAuraScriptPair(spell_q10190_battery_recharging_blaster, spell_q10190_battery_recharging_blaster_aura);
    RegisterSpellScript(spell_challenge_veraku);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_shadowmoon_valley()
void AddSC_shadowmoon_valley ()
{
    // Ours
    RegisterSpellScript(spell_q10612_10613_the_fel_and_the_furious);
    RegisterSpellScript(spell_q10563_q10596_to_legion_hold_aura);
    // Theirs
    RegisterCreatureAI(dragonmaw_race_npc);
    new npc_invis_infernal_caster();
    new npc_infernal_attacker();
    new npc_mature_netherwing_drake();
    RegisterCreatureAI(npc_enslaved_netherwing_drake);
    new npc_dragonmaw_peon();
    new npc_drake_dealer_hurlunk();
    new npcs_flanis_swiftwing_and_kagrosh();
    new npc_karynaku();
    new npc_lord_illidan_stormrage();
    new go_crystal_prison();
    new npc_illidari_spawn();
    new npc_torloth_the_magnificent();
    new npc_enraged_spirit();
    new npc_shadowmoon_tuber_node();
    RegisterCreatureAI(npc_korkron_or_wildhammer);
    RegisterSpellScript(spell_calling_korkron_or_wildhammer);
    RegisterSpellScript(spell_disrupt_summoning_ritual);
}
References npc_lord_illidan_stormrage::npc_lord_illidan_stormrage(), RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_shattrath_city()
void AddSC_shattrath_city ()
{
    new npc_shattrathflaskvendors();
    new npc_zephyr();
    new npc_kservant();
    RegisterCreatureAI(npc_shattrath_daily_quest);
}
References RegisterCreatureAI.
Referenced by AddOutlandScripts().
AddSC_terokkar_forest()
void AddSC_terokkar_forest ()
{
    // Ours
    RegisterSpellAndAuraScriptPair(spell_q10930_big_bone_worm, spell_q10930_big_bone_worm_aura);
    RegisterSpellAndAuraScriptPair(spell_q10929_fumping, spell_q10929_fumping_aura);
    RegisterSpellScript(spell_q10036_torgos);
    RegisterSpellScript(spell_q10923_evil_draws_near_summon);
    RegisterSpellScript(spell_q10923_evil_draws_near_periodic_aura);
    RegisterSpellScript(spell_q10923_evil_draws_near_visual);
    RegisterSpellScript(spell_q10898_skywing);
    // Theirs
    new npc_unkor_the_ruthless();
    new npc_isla_starmane();
    new go_skull_pile();
    new npc_slim();
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddOutlandScripts().
AddSC_the_slave_pens()
void AddSC_the_slave_pens ()
{
    new at_quagmirran_lair();
}
Referenced by AddOutlandScripts().
AddSC_underbog()
void AddSC_underbog ()
{
    RegisterUnderbogCreatureAI(npc_underbat);
    RegisterSpellScript(spell_fungal_decay);
    RegisterSpellScript(spell_allergies);
}
References RegisterSpellScript, and RegisterUnderbogCreatureAI.
Referenced by AddOutlandScripts().