AzerothCore: boss_ouro Struct Reference
boss_ouro Struct Reference
Public Member Functions
boss_ouro (Creature *creature)
bool CanAIAttack (Unit const *victim) const override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void Submerge ()
void CastGroundRupture ()
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
void Emerge ()
void Reset () override
void EnterEvadeMode (EvadeReason) override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Protected Member Functions
bool IsPlayerWithinMeleeRange () const
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
bool _ProccessHealthCheckEvent (uint8 healthPct, uint32 damage, std::function< void()> exec) const
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes
TaskScheduler _scheduler
bool _enraged
uint8 _submergeMelee
bool _submerged
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
TaskScheduler scheduler
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Detailed Description
Constructor & Destructor Documentation
boss_ouro()
boss_ouro::boss_ouro (Creature * creature) inline
                                  : BossAI(creature, DATA_OURO)
    {
        SetCombatMovement(false);
        me->SetControlled(true, UNIT_STATE_ROOT);
        _scheduler.SetValidator([this] { return !me->HasUnitState(UNIT_STATE_CASTING); });
    }
References _scheduler, Unit::HasUnitState(), ScriptedAI::me, ScriptedAI::SetCombatMovement(), Unit::SetControlled(), TaskScheduler::SetValidator(), UNIT_STATE_CASTING, and UNIT_STATE_ROOT.
Member Function Documentation
CanAIAttack()
bool boss_ouro::CanAIAttack (Unit const * victim) const inline override virtual
Reimplemented from UnitAI.
    {
        return me->IsWithinMeleeRange(victim);
    }
References Unit::IsWithinMeleeRange(), and ScriptedAI::me.
CastGroundRupture()
void boss_ouro::CastGroundRupture () inline
    {
        std::list<WorldObject*> targets;
        Acore::AllWorldObjectsInRange checker(me, 10.0f);
        Acore::WorldObjectListSearcher<Acore::AllWorldObjectsInRange> searcher(me, targets, checker);
        Cell::VisitAllObjects(me, searcher, 10.0f);
        for (WorldObject* target : targets)
        {
            if (Unit* unitTarget = target->ToUnit())
            {
                if (unitTarget->IsHostileTo(me))
                    DoCast(unitTarget, SPELL_GROUND_RUPTURE, true);
            }
        }
    }
References UnitAI::DoCast(), ScriptedAI::me, SPELL_GROUND_RUPTURE, Object::ToUnit(), and Cell::VisitAllObjects().
Referenced by Emerge().
DamageTaken()
void boss_ouro::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from BossAI.
    {
        if (me->HealthBelowPctDamaged(20, damage) && !_enraged)
        {
            DoCastSelf(SPELL_BERSERK, true);
            _enraged = true;
            _scheduler.CancelGroup(GROUP_PHASE_TRANSITION);
            _scheduler.Schedule(1s, [this](TaskContext context)
                {
                    if (!IsPlayerWithinMeleeRange())
                        DoSpellAttackToRandomTargetIfReady(SPELL_BOULDER);
                    context.Repeat();
                })
                .Schedule(20s, [this](TaskContext context)
                    {
                        DoCastSelf(SPELL_SUMMON_OURO_MOUNDS, true);
                        context.Repeat();
                    });
        }
    }
References _enraged, _scheduler, TaskScheduler::CancelGroup(), UnitAI::DoCastSelf(), UnitAI::DoSpellAttackToRandomTargetIfReady(), GROUP_PHASE_TRANSITION, Unit::HealthBelowPctDamaged(), IsPlayerWithinMeleeRange(), ScriptedAI::me, TaskContext::Repeat(), TaskScheduler::Schedule(), SPELL_BERSERK, SPELL_BOULDER, and SPELL_SUMMON_OURO_MOUNDS.
Emerge()
void boss_ouro::Emerge () inline
    {
        DoCastSelf(SPELL_BIRTH);
        DoCastSelf(SPELL_SUMMON_SANDWORM_BASE, true);
        me->SetReactState(REACT_AGGRESSIVE);
        CastGroundRupture();
        _scheduler
            .Schedule(20s, GROUP_EMERGED, [this](TaskContext context)
                {
                    if (Unit* target = SelectTarget(SelectTargetMethod::MaxThreat, 0, 0.0f, true))
                    {
                        me->SetTarget(target->GetGUID());
                    }
                    DoCastAOE(SPELL_SAND_BLAST);
                    me->m_Events.AddEventAtOffset([this]()
                    {
                        if (Unit* victim = me->GetVictim())
{
                            me->SetTarget(victim->GetGUID());
                        }
                    }, 3s);
                    context.Repeat();
                })
            .Schedule(22s, GROUP_EMERGED, [this](TaskContext context)
                {
                    DoCastVictim(SPELL_SWEEP);
                    context.Repeat();
                })
            .Schedule(90s, GROUP_PHASE_TRANSITION, [this](TaskContext /*context*/)
                {
                    Submerge();
                })
            .Schedule(3s, GROUP_PHASE_TRANSITION, [this](TaskContext context)
                {
                    if (_enraged)
                        return;
                    if (!IsPlayerWithinMeleeRange() && !_submerged)
                    {
                        if (_submergeMelee < 10)
{
                            _submergeMelee++;
                        }
                        else
{
                            Submerge();
                            _submergeMelee = 0;
                        }
                    }
                    else
                    {
                        _submergeMelee = 0;
                    }
                    if (!_submerged)
                        context.Repeat(1s);
                });
    }
References _enraged, _scheduler, _submerged, _submergeMelee, EventProcessor::AddEventAtOffset(), CastGroundRupture(), UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), Unit::GetVictim(), GROUP_EMERGED, GROUP_PHASE_TRANSITION, IsPlayerWithinMeleeRange(), Unit::m_Events, ScriptedAI::me, REACT_AGGRESSIVE, TaskContext::Repeat(), TaskScheduler::Schedule(), UnitAI::SelectTarget(), Creature::SetReactState(), Creature::SetTarget(), SPELL_BIRTH, SPELL_SAND_BLAST, SPELL_SUMMON_SANDWORM_BASE, SPELL_SWEEP, and Submerge().
Referenced by JustEngagedWith().
EnterEvadeMode()
void boss_ouro::EnterEvadeMode (EvadeReason) inline override virtual
Reimplemented from CreatureAI.
    {
        if (me->GetThreatMgr().GetThreatList().empty())
        {
            DoCastSelf(SPELL_OURO_SUBMERGE_VISUAL);
            me->DespawnOrUnsummon(1000);
            instance->SetBossState(DATA_OURO, FAIL);
            if (GameObject* base = me->FindNearestGameObject(GO_SANDWORM_BASE, 200.f))
                base->DespawnOrUnsummon();
        }
    }
References DATA_OURO, Creature::DespawnOrUnsummon(), UnitAI::DoCastSelf(), FAIL, WorldObject::FindNearestGameObject(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), GO_SANDWORM_BASE, BossAI::instance, ScriptedAI::me, InstanceScript::SetBossState(), and SPELL_OURO_SUBMERGE_VISUAL.
IsPlayerWithinMeleeRange()
bool boss_ouro::IsPlayerWithinMeleeRange () const inline protected
    {
        return me->IsWithinMeleeRange(me->GetVictim());
    }
References Unit::GetVictim(), Unit::IsWithinMeleeRange(), and ScriptedAI::me.
Referenced by DamageTaken(), and Emerge().
JustEngagedWith()
void boss_ouro::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        Emerge();
        BossAI::JustEngagedWith(who);
    }
References Emerge(), and BossAI::JustEngagedWith().
Reset()
void boss_ouro::Reset () inline override virtual
Reimplemented from BossAI.
    {
        instance->SetBossState(DATA_OURO, NOT_STARTED);
        _scheduler.CancelAll();
        _submergeMelee = 0;
        _submerged = false;
        _enraged = false;
    }
References _enraged, _scheduler, _submerged, _submergeMelee, TaskScheduler::CancelAll(), DATA_OURO, BossAI::instance, NOT_STARTED, and InstanceScript::SetBossState().
SpellHitTarget()
void boss_ouro::SpellHitTarget (Unit * target, SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (spellInfo->Id == SPELL_SAND_BLAST && target)
        {
            me->GetThreatMgr().ModifyThreatByPercent(target, -100);
        }
    }
References Unit::GetThreatMgr(), SpellInfo::Id, ScriptedAI::me, ThreatMgr::ModifyThreatByPercent(), and SPELL_SAND_BLAST.
Submerge()
void boss_ouro::Submerge () inline
    {
        if (_enraged || _submerged)
            return;
        me->AttackStop();
        me->SetReactState(REACT_PASSIVE);
        me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
        _submergeMelee = 0;
        _submerged = true;
        DoCastSelf(SPELL_OURO_SUBMERGE_VISUAL);
        _scheduler.CancelGroup(GROUP_EMERGED);
        _scheduler.CancelGroup(GROUP_PHASE_TRANSITION);
        if (GameObject* base = me->FindNearestGameObject(GO_SANDWORM_BASE, 10.f))
        {
            base->Use(me);
            base->DespawnOrUnsummon(6s);
        }
        DoCastSelf(SPELL_SUMMON_OURO_MOUNDS, true);
        // According to sniffs, Ouro uses his mounds to respawn. The health management could be a little scuffed.
        std::list<Creature*> ouroMounds;
        me->GetCreatureListWithEntryInGrid(ouroMounds, NPC_DIRT_MOUND, 200.f);
        if (!ouroMounds.empty()) // This can't be possible, but just to be sure.
        {
            if (Creature* mound = Acore::Containers::SelectRandomContainerElement(ouroMounds))
            {
                mound->AddAura(SPELL_SUMMON_OURO_AURA, mound);
                mound->AI()->SetData(DATA_OURO_HEALTH, me->GetHealth());
            }
        }
        me->DespawnOrUnsummon(1000);
    }
References _enraged, _scheduler, _submerged, _submergeMelee, Unit::AttackStop(), TaskScheduler::CancelGroup(), DATA_OURO_HEALTH, Creature::DespawnOrUnsummon(), UnitAI::DoCastSelf(), WorldObject::FindNearestGameObject(), WorldObject::GetCreatureListWithEntryInGrid(), Unit::GetHealth(), GO_SANDWORM_BASE, GROUP_EMERGED, GROUP_PHASE_TRANSITION, ScriptedAI::me, NPC_DIRT_MOUND, REACT_PASSIVE, Acore::Containers::SelectRandomContainerElement(), Creature::SetReactState(), Unit::SetUnitFlag(), SPELL_OURO_SUBMERGE_VISUAL, SPELL_SUMMON_OURO_AURA, SPELL_SUMMON_OURO_MOUNDS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by Emerge().
UpdateAI()
void boss_ouro::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
    {
        UpdateVictim();
        _scheduler.Update(diff, [this]
            {
                DoMeleeAttackIfReady();
            });
    }
References _scheduler, UnitAI::DoMeleeAttackIfReady(), TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_enraged
bool boss_ouro::_enraged protected
Referenced by DamageTaken(), Emerge(), Reset(), and Submerge().
_scheduler
TaskScheduler boss_ouro::_scheduler protected
Referenced by boss_ouro(), DamageTaken(), Emerge(), Reset(), Submerge(), and UpdateAI().
_submerged
bool boss_ouro::_submerged protected
Referenced by Emerge(), Reset(), and Submerge().
_submergeMelee
uint8 boss_ouro::_submergeMelee protected
Referenced by Emerge(), Reset(), and Submerge().