AzerothCore: PlayerTaxi Class Reference
PlayerTaxi Class Reference
#include "PlayerTaxi.h"
Public Member Functions
PlayerTaxi ()
~PlayerTaxi ()=default
void InitTaxiNodesForLevel (uint32 race, uint32 chrClass, uint8 level)
bool LoadTaxiMask (std::string_view data)
bool IsTaximaskNodeKnown (uint32 nodeidx) const
bool SetTaximaskNode (uint32 nodeidx)
void AppendTaximaskTo (ByteBuffer &data, bool all)
bool LoadTaxiDestinationsFromString (std::string const &values, TeamId teamId)
std::string SaveTaxiDestinationsToString ()
void ClearTaxiDestinations ()
void AddTaxiDestination (uint32 dest)
uint32 GetTaxiSource () const
uint32 GetTaxiDestination () const
uint32 GetCurrentTaxiPath () const
uint32 NextTaxiDestination ()
std::deque< uint32 > const & GetPath () const
bool empty () const
FactionTemplateEntry const * GetFlightMasterFactionTemplate () const
void SetFlightMasterFactionTemplateId (uint32 factionTemplateId)
Private Attributes
TaxiMask m_taximask
std::deque< uint32 > m_TaxiDestinations
uint32 m_flightMasterFactionId
Friends
std::ostringstream & operator<< (std::ostringstream &ss, PlayerTaxi const &taxi)
Detailed Description
Constructor & Destructor Documentation
PlayerTaxi()
PlayerTaxi::PlayerTaxi () inline
: m_flightMasterFactionId(0) { m_taximask.fill(0); }
~PlayerTaxi()
PlayerTaxi::~PlayerTaxi () default
Member Function Documentation
AddTaxiDestination()
void PlayerTaxi::AddTaxiDestination (uint32 dest) inline
{ m_TaxiDestinations.push_back(dest); }
Referenced by Player::ActivateTaxiPathTo(), Player::LoadFromDB(), LoadTaxiDestinationsFromString(), and Player::ProcessDelayedOperations().
AppendTaximaskTo()
void PlayerTaxi::AppendTaximaskTo (ByteBuffer & data, bool all)
{
    if (all)
    {
        for (uint8 i = 0; i < TaxiMaskSize; i++)
            data << uint32(sTaxiNodesMask[i]);              // all existed nodes
    }
    else
    {
        for (uint8 i = 0; i < TaxiMaskSize; i++)
            data << uint32(m_taximask[i]);                  // known nodes
    }
}
References m_taximask, sTaxiNodesMask, and TaxiMaskSize.
Referenced by WorldSession::SendTaxiMenu().
ClearTaxiDestinations()
void PlayerTaxi::ClearTaxiDestinations () inline
{ m_TaxiDestinations.clear(); }
Referenced by Player::ActivateTaxiPathTo(), Player::CleanupAfterTaxiFlight(), Player::ContinueTaxiFlight(), FlightPathMovementGenerator::DoFinalize(), Player::LoadFromDB(), and LoadTaxiDestinationsFromString().
empty()
bool PlayerTaxi::empty () const inline
{ return m_TaxiDestinations.empty(); }
Referenced by FlightPathMovementGenerator::DoFinalize(), and Player::SetEntryPoint().
GetCurrentTaxiPath()
uint32 PlayerTaxi::GetCurrentTaxiPath () const
{
    if (m_TaxiDestinations.size() < 2)
    {
        return 0;
    }
    uint32 path;
    uint32 cost;
    sObjectMgr->GetTaxiPath(m_TaxiDestinations[0], m_TaxiDestinations[1], path, cost);
    return path;
}
References m_TaxiDestinations, and sObjectMgr.
Referenced by Player::ContinueTaxiFlight().
GetFlightMasterFactionTemplate()
FactionTemplateEntry const * PlayerTaxi::GetFlightMasterFactionTemplate () const
{
    return sFactionTemplateStore.LookupEntry(m_flightMasterFactionId);
}
References m_flightMasterFactionId, and sFactionTemplateStore.
Referenced by FlightPathMovementGenerator::LoadPath().
GetPath()
std::deque< uint32 > const & PlayerTaxi::GetPath () const inline
{ return m_TaxiDestinations; }
Referenced by FlightPathMovementGenerator::LoadPath().
GetTaxiDestination()
uint32 PlayerTaxi::GetTaxiDestination () const inline
{ return m_TaxiDestinations.size() < 2 ? 0 : m_TaxiDestinations[1]; }
Referenced by WorldSession::HandleMoveSplineDoneOpcode(), and Player::SetEntryPoint().
GetTaxiSource()
uint32 PlayerTaxi::GetTaxiSource () const inline
{ return m_TaxiDestinations.empty() ? 0 : m_TaxiDestinations.front(); }
Referenced by Player::ContinueTaxiFlight(), LoadTaxiDestinationsFromString(), and Player::SetEntryPoint().
InitTaxiNodesForLevel()
void PlayerTaxi::InitTaxiNodesForLevel (uint32 race, uint32 chrClass, uint8 level)
{
    // class specific initial known nodes
    switch (chrClass)
    {
        case CLASS_DEATH_KNIGHT:
        {
            for (uint8 i = 0; i < TaxiMaskSize; ++i)
                m_taximask[i] |= sOldContinentsNodesMask[i];
            break;
        }
    }
    // race specific initial known nodes: capital and taxi hub masks
    switch (race)
    {
        case RACE_HUMAN:
            SetTaximaskNode(2);
            break;     // Human
        case RACE_ORC:
            SetTaximaskNode(23);
            break;     // Orc
        case RACE_DWARF:
            SetTaximaskNode(6);
            break;     // Dwarf
        case RACE_NIGHTELF:
            SetTaximaskNode(26);
            SetTaximaskNode(27);
            break;     // Night Elf
        case RACE_UNDEAD_PLAYER:
            SetTaximaskNode(11);
            break;// Undead
        case RACE_TAUREN:
            SetTaximaskNode(22);
            break;     // Tauren
        case RACE_GNOME:
            SetTaximaskNode(6);
            break;     // Gnome
        case RACE_TROLL:
            SetTaximaskNode(23);
            break;     // Troll
        case RACE_BLOODELF:
            SetTaximaskNode(82);
            break;     // Blood Elf
        case RACE_DRAENEI:
            SetTaximaskNode(94);
            break;     // Draenei
    }
    // new continent starting masks (It will be accessible only at new map)
    switch (Player::TeamIdForRace(race))
    {
        case TEAM_ALLIANCE:
            SetTaximaskNode(100);
            break;
        case TEAM_HORDE:
            SetTaximaskNode(99);
            break;
        default:
            break;
    }
    // level dependent taxi hubs
    if (level >= 68)
        SetTaximaskNode(213);                               //Shattered Sun Staging Area
}
References CLASS_DEATH_KNIGHT, m_taximask, RACE_BLOODELF, RACE_DRAENEI, RACE_DWARF, RACE_GNOME, RACE_HUMAN, RACE_NIGHTELF, RACE_ORC, RACE_TAUREN, RACE_TROLL, RACE_UNDEAD_PLAYER, SetTaximaskNode(), sOldContinentsNodesMask, TaxiMaskSize, TEAM_ALLIANCE, TEAM_HORDE, and Player::TeamIdForRace().
Referenced by Player::InitTaxiNodesForLevel().
IsTaximaskNodeKnown()
bool PlayerTaxi::IsTaximaskNodeKnown (uint32 nodeidx) const inline
    {
        uint8  field   = uint8((nodeidx - 1) / 32);
        uint32 submask = 1 << ((nodeidx - 1) % 32);
        return (m_taximask[field] & submask) == submask;
    }
Referenced by Player::SendTaxiNodeStatusMultiple(), and WorldSession::SendTaxiStatus().
LoadTaxiDestinationsFromString()
bool PlayerTaxi::LoadTaxiDestinationsFromString (std::string const & values, TeamId teamId)
{
    ClearTaxiDestinations();
    std::vector<std::string_view> tokens = Acore::Tokenize(values, ' ', false);
    auto itr = tokens.begin();
    if (itr != tokens.end())
    {
        if (Optional<uint32> faction = Acore::StringTo<uint32>(*itr))
        {
            m_flightMasterFactionId = *faction;
        }
        else
        {
            return false;
        }
    }
    else
        return false;
    while ((++itr) != tokens.end())
    {
        if (Optional<uint32> node = Acore::StringTo<uint32>(*itr))
        {
            AddTaxiDestination(*node);
        }
        else
        {
            return false;
        }
    }
    if (m_TaxiDestinations.empty())
    {
        return true;
    }
    // Check integrity
    if (m_TaxiDestinations.size() < 2)
    {
        return false;
    }
    for (std::size_t i = 1; i < m_TaxiDestinations.size(); ++i)
    {
        uint32 cost;
        uint32 path;
        sObjectMgr->GetTaxiPath(m_TaxiDestinations[i - 1], m_TaxiDestinations[i], path, cost);
        if (!path)
        {
            return false;
        }
    }
    // can't load taxi path without mount set (quest taxi path?)
    if (!sObjectMgr->GetTaxiMountDisplayId(GetTaxiSource(), teamId, true))
    {
        return false;
    }
    return true;
}
References AddTaxiDestination(), ClearTaxiDestinations(), GetTaxiSource(), m_flightMasterFactionId, m_TaxiDestinations, sObjectMgr, and Acore::Tokenize().
Referenced by Player::LoadFromDB().
LoadTaxiMask()
bool PlayerTaxi::LoadTaxiMask (std::string_view data)
{
    bool warn = false;
    std::vector<std::string_view> tokens = Acore::Tokenize(data, ' ', false);
    for (uint8 index = 0; (index < TaxiMaskSize) && (index < tokens.size()); ++index)
    {
        if (Optional<uint32> mask = Acore::StringTo<uint32>(tokens[index]))
        {
            // load and set bits only for existing taxi nodes
            m_taximask[index] = sTaxiNodesMask[index] & *mask;
            if (m_taximask[index] != *mask)
            {
                warn = true;
            }
        }
        else
        {
            m_taximask[index] = 0;
            warn = true;
        }
    }
    return !warn;
}
References m_taximask, sTaxiNodesMask, TaxiMaskSize, and Acore::Tokenize().
Referenced by Player::LoadFromDB().
NextTaxiDestination()
uint32 PlayerTaxi::NextTaxiDestination () inline
    {
        m_TaxiDestinations.pop_front();
        return GetTaxiDestination();
    }
Referenced by FlightPathMovementGenerator::DoUpdate().
SaveTaxiDestinationsToString()
std::string PlayerTaxi::SaveTaxiDestinationsToString ()
{
    if (m_TaxiDestinations.empty())
    {
        return "";
    }
    ASSERT(m_TaxiDestinations.size() >= 2);
    std::ostringstream ss;
    ss << m_flightMasterFactionId << ' ';
    for (std::size_t i = 0; i < m_TaxiDestinations.size(); ++i)
    {
        ss << m_TaxiDestinations[i] << ' ';
    }
    return ss.str();
}
References ASSERT, m_flightMasterFactionId, and m_TaxiDestinations.
Referenced by Player::_SaveCharacter().
SetFlightMasterFactionTemplateId()
void PlayerTaxi::SetFlightMasterFactionTemplateId (uint32 factionTemplateId) inline
{ m_flightMasterFactionId = factionTemplateId; }
Referenced by Player::ActivateTaxiPathTo().
SetTaximaskNode()
bool PlayerTaxi::SetTaximaskNode (uint32 nodeidx) inline
    {
        uint8  field   = uint8((nodeidx - 1) / 32);
        uint32 submask = 1 << ((nodeidx - 1) % 32);
        if ((m_taximask[field] & submask) != submask)
        {
            m_taximask[field] |= submask;
            return true;
        }
        else
            return false;
    }
Referenced by InitTaxiNodesForLevel().
Friends And Related Function Documentation
operator<<
std::ostringstream & operator<< (std::ostringstream & ss, PlayerTaxi const & taxi) friend
{
    for (uint8 i = 0; i < TaxiMaskSize; ++i)
        ss << taxi.m_taximask[i] << ' ';
    return ss;
}
Member Data Documentation
m_flightMasterFactionId
uint32 PlayerTaxi::m_flightMasterFactionId private
Referenced by GetFlightMasterFactionTemplate(), LoadTaxiDestinationsFromString(), and SaveTaxiDestinationsToString().
m_TaxiDestinations
std::deque<uint32> PlayerTaxi::m_TaxiDestinations private
Referenced by GetCurrentTaxiPath(), LoadTaxiDestinationsFromString(), and SaveTaxiDestinationsToString().
m_taximask
TaxiMask PlayerTaxi::m_taximask private
Referenced by AppendTaximaskTo(), InitTaxiNodesForLevel(), and LoadTaxiMask().