AzerothCore: Acore::WorldObjectSpellTargetCheck Struct Reference
Acore::WorldObjectSpellTargetCheck Struct Reference
#include "Spell.h"
Public Member Functions
WorldObjectSpellTargetCheck (Unit *caster, Unit *referer, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, ConditionList *condList)
~WorldObjectSpellTargetCheck ()
bool operator() (WorldObject *target)
Public Attributes
Unit * _caster
Unit * _referer
SpellInfo const * _spellInfo
SpellTargetCheckTypes _targetSelectionType
ConditionSourceInfo * _condSrcInfo
ConditionList * _condList
Detailed Description
Constructor & Destructor Documentation
WorldObjectSpellTargetCheck()
Acore::WorldObjectSpellTargetCheck::WorldObjectSpellTargetCheck (Unit * caster, Unit * referer, SpellInfo const * spellInfo, SpellTargetCheckTypes selectionType, ConditionList * condList)
                                                                          : _caster(caster), _referer(referer), _spellInfo(spellInfo),
        _targetSelectionType(selectionType), _condList(condList)
    {
        if (condList)
            _condSrcInfo = new ConditionSourceInfo(nullptr, caster);
        else
            _condSrcInfo = nullptr;
    }
References _condSrcInfo.
~WorldObjectSpellTargetCheck()
Acore::WorldObjectSpellTargetCheck::~WorldObjectSpellTargetCheck ()
    {
        if (_condSrcInfo)
            delete _condSrcInfo;
    }
References _condSrcInfo.
Member Function Documentation
operator()()
bool Acore::WorldObjectSpellTargetCheck::operator() (WorldObject * target)
    {
        if (_spellInfo->CheckTarget(_caster, target, true) != SPELL_CAST_OK)
            return false;
        Unit* unitTarget = target->ToUnit();
        if (Corpse* corpseTarget = target->ToCorpse())
        {
            // use ofter for party/assistance checks
            if (Player* owner = ObjectAccessor::FindPlayer(corpseTarget->GetOwnerGUID()))
                unitTarget = owner;
            else
                return false;
        }
        if (unitTarget)
        {
            switch (_targetSelectionType)
            {
                case TARGET_CHECK_ENEMY:
                    if (unitTarget->IsTotem())
                        return false;
                    if (!_caster->_IsValidAttackTarget(unitTarget, _spellInfo))
                        return false;
                    break;
                case TARGET_CHECK_ALLY:
                    if (unitTarget->IsTotem())
                        return false;
                    if (!_caster->_IsValidAssistTarget(unitTarget, _spellInfo))
                        return false;
                    break;
                case TARGET_CHECK_PARTY:
                    if (unitTarget->IsTotem())
                        return false;
                    if (!_caster->_IsValidAssistTarget(unitTarget, _spellInfo))
                        return false;
                    if (!_referer->IsInPartyWith(unitTarget))
                        return false;
                    break;
                case TARGET_CHECK_RAID_CLASS:
                    if (_referer->getClass() != unitTarget->getClass())
                        return false;
                    [[fallthrough]];
                case TARGET_CHECK_RAID:
                    if (unitTarget->IsTotem())
                        return false;
                    if (!_caster->_IsValidAssistTarget(unitTarget, _spellInfo))
                        return false;
                    if (!_referer->IsInRaidWith(unitTarget))
                        return false;
                    break;
                case TARGET_CHECK_CORPSE:
                    if (_caster->IsFriendlyTo(unitTarget))
                        return false;
                    break;
                default:
                    break;
            }
        }
        if (!_condSrcInfo)
            return true;
        _condSrcInfo->mConditionTargets[0] = target;
        return sConditionMgr->IsObjectMeetToConditions(*_condSrcInfo, *_condList);
    }
References _caster, _condList, _condSrcInfo, Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), _referer, _spellInfo, _targetSelectionType, SpellInfo::CheckTarget(), ObjectAccessor::FindPlayer(), Unit::getClass(), Unit::IsFriendlyTo(), Unit::IsInPartyWith(), Unit::IsInRaidWith(), Unit::IsTotem(), ConditionSourceInfo::mConditionTargets, sConditionMgr, SPELL_CAST_OK, TARGET_CHECK_ALLY, TARGET_CHECK_CORPSE, TARGET_CHECK_ENEMY, TARGET_CHECK_PARTY, TARGET_CHECK_RAID, TARGET_CHECK_RAID_CLASS, Object::ToCorpse(), and Object::ToUnit().
Referenced by Acore::WorldObjectSpellAreaTargetCheck::operator()().
Member Data Documentation
_caster
Unit* Acore::WorldObjectSpellTargetCheck::_caster
Referenced by operator()(), Acore::WorldObjectSpellConeTargetCheck::operator()(), and Acore::WorldObjectSpellTrajTargetCheck::operator()().
_condList
ConditionList* Acore::WorldObjectSpellTargetCheck::_condList
Referenced by operator()().
_condSrcInfo
ConditionSourceInfo* Acore::WorldObjectSpellTargetCheck::_condSrcInfo
Referenced by operator()(), WorldObjectSpellTargetCheck(), and ~WorldObjectSpellTargetCheck().
_referer
Unit* Acore::WorldObjectSpellTargetCheck::_referer
Referenced by operator()().
_spellInfo
SpellInfo const* Acore::WorldObjectSpellTargetCheck::_spellInfo
Referenced by operator()(), and Acore::WorldObjectSpellConeTargetCheck::operator()().
_targetSelectionType
SpellTargetCheckTypes Acore::WorldObjectSpellTargetCheck::_targetSelectionType
Referenced by operator()().