AzerothCore: SpellScriptLoader Class Reference
SpellScriptLoader Class Reference
#include "SpellScriptLoader.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual SpellScript * GetSpellScript () const
virtual AuraScript * GetAuraScript () const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Protected Member Functions
SpellScriptLoader (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
SpellScriptLoader()
SpellScriptLoader::SpellScriptLoader (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<SpellScriptLoader>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
GetAuraScript()
virtual AuraScript * SpellScriptLoader::GetAuraScript () const inline virtual
Reimplemented in GenericSpellAndAuraScriptLoader< Ts >.
{ return nullptr; }
Referenced by ScriptMgr::CreateAuraScripts().
GetSpellScript()
virtual SpellScript * SpellScriptLoader::GetSpellScript () const inline virtual
Reimplemented in GenericSpellAndAuraScriptLoader< Ts >, spell_q55_sacred_cleansing, and spell_q11515_fel_siphon_dummy.
{ return nullptr; }
Referenced by ScriptMgr::CreateSpellScripts().
IsDatabaseBound()
bool SpellScriptLoader::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return true; }