AzerothCore: boss_thorim::boss_thorimAI Struct Reference
boss_thorim::boss_thorimAI Struct Reference
Public Member Functions
boss_thorimAI (Creature *pCreature)
void DisableThorim (bool apply)
GameObject * GetThorimObject (uint32 entry)
void JustSummoned (Creature *cr) override
void SpawnAllNPCs ()
void CloseDoors ()
void EnterEvadeMode (EvadeReason why) override
void Reset () override
uint32 GetData (uint32 param) const override
void DoAction (int32 param) override
void KilledUnit (Unit *victim) override
void JustReachedHome () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void DamageTaken (Unit *who, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void SpawnArenaNPCs ()
void SpellHit (Unit *caster, SpellInfo const *spellInfo) override
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
Player * GetArenaPlayer ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
bool _isArenaEmpty
bool _encounterFinished
bool _spawnCommoners
bool _hardMode
bool _isHitAllowed
bool _isAlly
uint8 _trashCounter
InstanceScript * m_pInstance
EventMap events
SummonList summons
bool _hitByLightning
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_thorimAI()
boss_thorim::boss_thorimAI::boss_thorimAI (Creature * pCreature) inline
                                           : ScriptedAI(pCreature), summons(me)
        {
            m_pInstance = pCreature->GetInstanceScript();
            if ((_encounterFinished = (!me->IsAlive())))
                if (m_pInstance)
                    m_pInstance->SetData(TYPE_THORIM, DONE);
        }
References _encounterFinished, DONE, WorldObject::GetInstanceScript(), Unit::IsAlive(), m_pInstance, ScriptedAI::me, ZoneScript::SetData(), and TYPE_THORIM.
Member Function Documentation
CloseDoors()
void boss_thorim::boss_thorimAI::CloseDoors () inline
        {
            GameObject* go;
            if ((go = GetThorimObject(DATA_THORIM_LEVER)))
            {
                go->ReplaceAllGameObjectFlags((GameObjectFlags)48);
                go->SetGoState(GO_STATE_READY);
            }
            if ((go = GetThorimObject(DATA_THORIM_FIRST_DOORS)))
                go->SetGoState(GO_STATE_READY);
            if ((go = GetThorimObject(DATA_THORIM_SECOND_DOORS)))
                go->SetGoState(GO_STATE_READY);
            if ((go = GetThorimObject(DATA_THORIM_FENCE)))
                go->SetGoState(GO_STATE_ACTIVE);
        }
References DATA_THORIM_FENCE, DATA_THORIM_FIRST_DOORS, DATA_THORIM_LEVER, DATA_THORIM_SECOND_DOORS, GetThorimObject(), GO_STATE_ACTIVE, GO_STATE_READY, GameObject::ReplaceAllGameObjectFlags(), and GameObject::SetGoState().
Referenced by Reset().
DamageTaken()
void boss_thorim::boss_thorimAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (who && _isHitAllowed && who->GetPositionZ() > 430 && who->IsPlayer())
            {
                _isHitAllowed = false;
                DisableThorim(false);
                events.SetPhase(EVENT_PHASE_RING);
                events.ScheduleEvent(EVENT_THORIM_UNBALANCING_STRIKE, 8s, 0, EVENT_PHASE_RING);
                events.ScheduleEvent(EVENT_THORIM_LIGHTNING_CHARGE, 12s + 500ms, 0, EVENT_PHASE_RING);
                events.ScheduleEvent(EVENT_THORIM_CHAIN_LIGHTNING, 13s, 0, EVENT_PHASE_RING);
                events.ScheduleEvent(EVENT_THORIM_BERSERK, 5min, 0, EVENT_PHASE_RING);
                me->GetMotionMaster()->MoveChase(me->GetVictim());
                me->GetMotionMaster()->MoveJump(Middle.GetPositionX(), Middle.GetPositionY(), Middle.GetPositionZ(), 20, 20);
                me->RemoveAura(SPELL_SHEATH_OF_LIGHTNING);
                Talk(SAY_JUMPDOWN);
                // Hard Mode
                if (!me->HasAura(62565 /*TOUCH OF DOMINION TRIGGER*/))
                {
                    if (m_pInstance)
                        m_pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, 64980 /*SIFFED ACHIEVEMENT*/);
                    _hardMode = true;
                    EntryCheckPredicate pred(NPC_SIF);
                    summons.DoAction(ACTION_SIF_JOIN_FIGHT, pred);
                }
                DoResetThreatList();
                if (Player* player = GetArenaPlayer())
                    me->AddThreat(player, 1000.0f);
            }
            if (damage >= me->GetHealth())
            {
                damage = 0;
                if (!_encounterFinished)
                {
                    _encounterFinished = true;
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->SetFaction(FACTION_FRIENDLY);
                    me->SetHealth(me->GetMaxHealth());
                    me->CombatStop();
                    me->RemoveAllAuras();
                    events.Reset();
                    DisableThorim(true);
                    Talk(SAY_DEATH);
                    events.SetPhase(EVENT_PHASE_OUTRO);
                    events.ScheduleEvent(EVENT_THORIM_OUTRO1, 2s, 0, EVENT_PHASE_OUTRO);
                    GameObject* go = nullptr;
                    if ((go = GetThorimObject(DATA_THORIM_FENCE)))
                        go->SetGoState(GO_STATE_ACTIVE);
                    uint32 chestId = me->GetMap()->Is25ManRaid() ? GO_THORIM_CHEST_HERO : GO_THORIM_CHEST;
                    if (_hardMode)
                        chestId += 1; // hard mode offset
                    if ((go = me->SummonGameObject(chestId, 2134.73f, -286.32f, 419.51f, 4.65f, 0, 0, 0, 0, 0)))
                    {
                        go->ReplaceAllGameObjectFlags((GameObjectFlags)0);
                        go->SetLootRecipient(me->GetMap());
                    }
                    // Defeat credit
                    if (m_pInstance)
                    {
                        me->CastSpell(me, 64985, true); // credit
                        m_pInstance->SetData(TYPE_THORIM, DONE);
                    }
                }
            }
        }
References _encounterFinished, _hardMode, _isHitAllowed, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACTION_SIF_JOIN_FIGHT, Unit::AddThreat(), Unit::CastSpell(), Unit::CombatStop(), DATA_THORIM_FENCE, DisableThorim(), SummonList::DoAction(), DONE, ScriptedAI::DoResetThreatList(), InstanceScript::DoUpdateAchievementCriteria(), EVENT_PHASE_OUTRO, EVENT_PHASE_RING, EVENT_THORIM_BERSERK, EVENT_THORIM_CHAIN_LIGHTNING, EVENT_THORIM_LIGHTNING_CHARGE, EVENT_THORIM_OUTRO1, EVENT_THORIM_UNBALANCING_STRIKE, FACTION_FRIENDLY, GetArenaPlayer(), Unit::GetHealth(), WorldObject::GetMap(), Unit::GetMaxHealth(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetThorimObject(), Unit::GetVictim(), GO_STATE_ACTIVE, GO_THORIM_CHEST, GO_THORIM_CHEST_HERO, Unit::HasAura(), Map::Is25ManRaid(), Object::IsPlayer(), m_pInstance, ScriptedAI::me, Middle, MotionMaster::MoveChase(), MotionMaster::MoveJump(), NPC_SIF, Unit::RemoveAllAuras(), Unit::RemoveAura(), GameObject::ReplaceAllGameObjectFlags(), SAY_DEATH, SAY_JUMPDOWN, ZoneScript::SetData(), Unit::SetFaction(), GameObject::SetGoState(), Unit::SetHealth(), GameObject::SetLootRecipient(), Unit::SetUnitFlag(), SPELL_SHEATH_OF_LIGHTNING, WorldObject::SummonGameObject(), summons, TYPE_THORIM, and UNIT_FLAG_NON_ATTACKABLE.
DisableThorim()
void boss_thorim::boss_thorimAI::DisableThorim (bool apply) inline
        {
            if (apply)
            {
                me->SetUnitFlag(UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_PACIFIED);
                me->DisableRotate(true);
                me->AddUnitState(UNIT_STATE_ROOT);
            }
            else
            {
                me->RemoveUnitFlag(UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_PACIFIED);
                me->DisableRotate(false);
                me->ClearUnitState(UNIT_STATE_ROOT);
                me->resetAttackTimer(BASE_ATTACK);
            }
        }
References Unit::AddUnitState(), BASE_ATTACK, Unit::ClearUnitState(), Unit::DisableRotate(), ScriptedAI::me, Unit::RemoveUnitFlag(), Unit::resetAttackTimer(), Unit::SetUnitFlag(), UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_PACIFIED, and UNIT_STATE_ROOT.
Referenced by DamageTaken(), EnterEvadeMode(), JustEngagedWith(), and Reset().
DoAction()
void boss_thorim::boss_thorimAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_START_TRASH_DIED)
            {
                _trashCounter++;
                // activate levar
                if (_trashCounter >= 6)
                {
                    if (GameObject* go = GetThorimObject(DATA_THORIM_LEVER))
                        go->RemoveGameObjectFlag((GameObjectFlags)48);
                    events.ScheduleEvent(EVENT_THORIM_AGGRO, 0ms);
                    events.SetPhase(EVENT_PHASE_START);
                    events.ScheduleEvent(EVENT_THORIM_START_PHASE1, 20s);
                    _trashCounter = 0;
                }
            }
            else if (param == ACTION_ALLOW_HIT)
                _isHitAllowed = true;
        }
References _isHitAllowed, _trashCounter, ACTION_ALLOW_HIT, ACTION_START_TRASH_DIED, DATA_THORIM_LEVER, EVENT_PHASE_START, EVENT_THORIM_AGGRO, EVENT_THORIM_START_PHASE1, and GetThorimObject().
EnterEvadeMode()
void boss_thorim::boss_thorimAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            DisableThorim(false);
            CreatureAI::EnterEvadeMode(why);
        }
References DisableThorim(), and CreatureAI::EnterEvadeMode().
GetArenaPlayer()
Player * boss_thorim::boss_thorimAI::GetArenaPlayer () inline
        {
            Map::PlayerList const& pList = me->GetMap()->GetPlayers();
            for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
                if (Player* p = itr->GetSource())
                    if (p->GetPositionX() > 2085 && p->GetPositionX() < 2185 && p->GetPositionY() < -214 && p->GetPositionY() > -305 && p->IsAlive() && p->GetPositionZ() < 425)
                        return p;
            return nullptr;
        }
References MapRefMgr::begin(), MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), and ScriptedAI::me.
Referenced by DamageTaken(), and UpdateAI().
GetData()
uint32 boss_thorim::boss_thorimAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_HIT_BY_LIGHTNING)
                return !_hitByLightning;
            if (param == DATA_LOSE_YOUR_ILLUSION)
                return _hardMode;
            return 0;
        }
References _hardMode, _hitByLightning, DATA_HIT_BY_LIGHTNING, and DATA_LOSE_YOUR_ILLUSION.
GetThorimObject()
GameObject * boss_thorim::boss_thorimAI::GetThorimObject (uint32 entry) inline
        {
            if (m_pInstance)
                return ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(entry));
            return nullptr;
        }
References ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), m_pInstance, and ScriptedAI::me.
Referenced by CloseDoors(), DamageTaken(), DoAction(), and UpdateAI().
JustEngagedWith()
void boss_thorim::boss_thorimAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            if (m_pInstance && !_encounterFinished)
                m_pInstance->SetData(TYPE_THORIM, IN_PROGRESS);
            me->setActive(true);
            DisableThorim(true);
            me->CastSpell(me, SPELL_SHEATH_OF_LIGHTNING, true);
            //me->CastSpell(me, SPELL_TOUCH_OF_DOMINION, true);
        }
References _encounterFinished, Unit::CastSpell(), DisableThorim(), IN_PROGRESS, m_pInstance, ScriptedAI::me, WorldObject::setActive(), ZoneScript::SetData(), SPELL_SHEATH_OF_LIGHTNING, and TYPE_THORIM.
JustReachedHome()
void boss_thorim::boss_thorimAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
{ me->setActive(false); }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_thorim::boss_thorimAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
{ summons.Summon(cr); }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_thorim::boss_thorimAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->IsPlayer())
                Talk(SAY_SLAY);
        }
References Object::IsPlayer(), and SAY_SLAY.
Reset()
void boss_thorim::boss_thorimAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            if (m_pInstance && !_encounterFinished)
                m_pInstance->SetData(TYPE_THORIM, NOT_STARTED);
            events.Reset();
            events.SetPhase(0);
            summons.DespawnAll();
            _trashCounter = 0;
            _isAlly = true;
            _isHitAllowed = false;
            _spawnCommoners = false;
            _hardMode = false;
            _isArenaEmpty = false;
            _hitByLightning = false;
            if (Player* t = SelectTargetFromPlayerList(1000))
                if (t->GetTeamId() == TEAM_HORDE)
                    _isAlly = false;
            SpawnAllNPCs();
            CloseDoors();
            DisableThorim(false);
        }
References _encounterFinished, _hardMode, _hitByLightning, _isAlly, _isArenaEmpty, _isHitAllowed, _spawnCommoners, _trashCounter, CloseDoors(), SummonList::DespawnAll(), DisableThorim(), m_pInstance, NOT_STARTED, ScriptedAI::SelectTargetFromPlayerList(), ZoneScript::SetData(), SpawnAllNPCs(), summons, TEAM_HORDE, and TYPE_THORIM.
SpawnAllNPCs()
void boss_thorim::boss_thorimAI::SpawnAllNPCs () inline
        {
            // Jormungar Behemoth 32882
            me->SummonCreature(NPC_JORMUNGAR_BEHEMOT, 2149.68f, -263.477f, 419.679f, 3.12102f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
            // Captured Mercenary Soldier 32885
            me->SummonCreature(_isAlly ? NPC_CAPTURED_MERCENARY_SOLDIER_ALLY : NPC_CAPTURED_MERCENARY_SOLDIER_HORDE, 2127.24f, -251.309f, 419.793f, 5.89921f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
            me->SummonCreature(_isAlly ? NPC_CAPTURED_MERCENARY_SOLDIER_ALLY : NPC_CAPTURED_MERCENARY_SOLDIER_HORDE, 2120.1f, -258.99f, 419.764f, 6.24828f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
            me->SummonCreature(_isAlly ? NPC_CAPTURED_MERCENARY_SOLDIER_ALLY : NPC_CAPTURED_MERCENARY_SOLDIER_HORDE, 2123.32f, -254.771f, 419.789f, 6.17846f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
            // Captured Mercenary Captain 32908
            me->SummonCreature(_isAlly ? NPC_CAPTURED_MERCENARY_CAPTAIN_ALLY : NPC_CAPTURED_MERCENARY_CAPTAIN_HORDE, 2131.31f, -259.182f, 419.974f, 5.91667f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
            // Dark Rune Acolyte (arena) 32886
            me->SummonCreature(NPC_DARK_RUNE_ACOLYTE_I, 2129.09f, -277.142f, 419.756f, 1.22173f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
            // Iron Ring Guard 32874
            me->SummonCreature(NPC_IRON_RING_GUARD, 2217.69f, -337.394f, 412.177f, 1.23918f);
            me->SummonCreature(NPC_IRON_RING_GUARD, 2218.38f, -297.505f, 412.176f, 1.02974f);
            me->SummonCreature(NPC_IRON_RING_GUARD, 2235.26f, -338.345f, 412.134f, 1.58979f);
            me->SummonCreature(NPC_IRON_RING_GUARD, 2235.07f, -297.985f, 412.134f, 1.61336f);
            // Dark Rune Acolyte (gauntlet) 33110
            me->SummonCreature(NPC_DARK_RUNE_ACOLYTE_G, 2198.29f, -436.92f, 419.985f, 0.261799f);
            me->SummonCreature(NPC_DARK_RUNE_ACOLYTE_G, 2227.58f, -308.303f, 412.134f, 1.59372f);
            me->SummonCreature(NPC_DARK_RUNE_ACOLYTE_G, 2227.47f, -345.375f, 412.134f, 1.56622f);
            // Iron Honor Guard 32875
            me->SummonCreature(NPC_IRON_HONOR_GUARD, 2198.05f, -428.769f, 419.985f, 6.05629f);
            me->SummonCreature(NPC_IRON_HONOR_GUARD, 2220.31f, -436.22f, 412.26f, 1.06465f);
            // Runic Colossus 32872
            me->SummonCreature(NPC_RUNIC_COLOSSUS, 2227.5f, -396.179f, 412.176f, 1.79769f);
            // Ancient Rune Giant 32873
            me->SummonCreature(NPC_ANCIENT_RUNE_GIANT, 2134.57f, -440.318f, 438.331f, 0.226893f);
            // Sif 33196
            me->SummonCreature(NPC_SIF, 2147.86f, -301.2f, 438.246f, 2.488f);
        }
References _isAlly, ScriptedAI::me, NPC_ANCIENT_RUNE_GIANT, NPC_CAPTURED_MERCENARY_CAPTAIN_ALLY, NPC_CAPTURED_MERCENARY_CAPTAIN_HORDE, NPC_CAPTURED_MERCENARY_SOLDIER_ALLY, NPC_CAPTURED_MERCENARY_SOLDIER_HORDE, NPC_DARK_RUNE_ACOLYTE_G, NPC_DARK_RUNE_ACOLYTE_I, NPC_IRON_HONOR_GUARD, NPC_IRON_RING_GUARD, NPC_JORMUNGAR_BEHEMOT, NPC_RUNIC_COLOSSUS, NPC_SIF, WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
Referenced by Reset().
SpawnArenaNPCs()
void boss_thorim::boss_thorimAI::SpawnArenaNPCs () inline
        {
            Creature* cr;
            uint8 rnd;
            if (_spawnCommoners || urand(0, 2))
                _spawnCommoners = !_spawnCommoners;
            for (uint8 i = 0; i < (_spawnCommoners ? 7 : 2); ++i)
            {
                rnd = urand(0, 13);
                if ((cr = me->SummonCreature((_spawnCommoners ? NPC_DARK_RUNE_COMMONER : RollTable[urand(0, 2)]), ArenaNPCs[rnd], TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000)))
                    cr->GetMotionMaster()->MoveJump(
                        Middle.GetPositionX() + urand(19, 24) * cos(Middle.GetAngle(cr)),
                        Middle.GetPositionY() + urand(19, 24) * std::sin(Middle.GetAngle(cr)),
                        Middle.GetPositionZ(), 20, 20);
            }
        }
References _spawnCommoners, ArenaNPCs, Position::GetAngle(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, Middle, MotionMaster::MoveJump(), NPC_DARK_RUNE_COMMONER, RollTable, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
SpellHit()
void boss_thorim::boss_thorimAI::SpellHit (Unit * caster, SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_LIGHTNING_ORB_CHARGER)
            {
                me->SetOrientation(me->GetAngle(caster));
                me->CastSpell(caster, SPELL_LIGHTNING_CHARGE_DAMAGE, true);
                me->CastSpell(me, SPELL_LIGHTNING_CHARGE_BUFF, true);
                events.RescheduleEvent(EVENT_THORIM_LIGHTNING_CHARGE, 10s, 0, EVENT_PHASE_RING);
            }
            else if (spellInfo->Id == SPELL_TELEPORT)
            {
                me->DespawnOrUnsummon();
                m_pInstance->SetData(EVENT_KEEPER_TELEPORTED, DONE);
            }
        }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), DONE, EVENT_KEEPER_TELEPORTED, EVENT_PHASE_RING, EVENT_THORIM_LIGHTNING_CHARGE, Position::GetAngle(), SpellInfo::Id, m_pInstance, ScriptedAI::me, ZoneScript::SetData(), Position::SetOrientation(), SPELL_LIGHTNING_CHARGE_BUFF, SPELL_LIGHTNING_CHARGE_DAMAGE, SPELL_LIGHTNING_ORB_CHARGER, and SPELL_TELEPORT.
SpellHitTarget()
void boss_thorim::boss_thorimAI::SpellHitTarget (Unit * target, SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_LIGHTNING_CHARGE_DAMAGE && target->IsPlayer())
                _hitByLightning = true;
        }
References _hitByLightning, SpellInfo::Id, Object::IsPlayer(), and SPELL_LIGHTNING_CHARGE_DAMAGE.
UpdateAI()
void boss_thorim::boss_thorimAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!_encounterFinished && !UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_THORIM_AGGRO:
                    Talk(SAY_AGGRO_1);
                    events.ScheduleEvent(EVENT_THORIM_AGGRO2, 9s);
                    if (GameObject* go = GetThorimObject(DATA_THORIM_FENCE))
                        go->SetGoState(GO_STATE_READY);
                    break;
                case EVENT_THORIM_AGGRO2:
                    {
                        Talk(SAY_AGGRO_2);
                        EntryCheckPredicate pred(NPC_SIF);
                        summons.DoAction(ACTION_SIF_START_TALK, pred);
                        break;
                    }
                case EVENT_THORIM_START_PHASE1:
                    {
                        events.ScheduleEvent(EVENT_THORIM_STORMHAMMER, 8s, 0, EVENT_PHASE_START);
                        events.ScheduleEvent(EVENT_THORIM_CHARGE_ORB, 14s, 0, EVENT_PHASE_START);
                        events.ScheduleEvent(EVENT_THORIM_FILL_ARENA, 0ms, 0, EVENT_PHASE_START);
                        events.ScheduleEvent(EVENT_THORIM_LIGHTNING_ORB, 5s, 0, EVENT_PHASE_START); // checked every 5 secs if there are players on arena
                        events.ScheduleEvent(EVENT_THORIM_NOT_REACH_IN_TIME, 5min, 0, EVENT_PHASE_START);
                        EntryCheckPredicate pred(NPC_SIF);
                        summons.DoAction(ACTION_SIF_START_DOMINION, pred);
                        break;
                    }
                case EVENT_THORIM_STORMHAMMER:
                    me->CastCustomSpell(SPELL_STORMHAMMER, SPELLVALUE_MAX_TARGETS, 1, me->GetVictim(), false);
                    events.Repeat(16s);
                    break;
                case EVENT_THORIM_CHARGE_ORB:
                    me->CastCustomSpell(SPELL_CHARGE_ORB, SPELLVALUE_MAX_TARGETS, 1, me, false);
                    events.Repeat(16s);
                    break;
                case EVENT_THORIM_LIGHTNING_ORB:
                    {
                        if (GetArenaPlayer())
{
                            // Player found, repeat and return
                            events.Repeat(5s);
                            return;
                        }
                        // No players found
                        Talk(SAY_WIPE);
                        me->SummonCreature(NPC_LIGHTNING_ORB, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                        _isArenaEmpty = true;
                        events.CancelEvent(EVENT_THORIM_NOT_REACH_IN_TIME);
                        break;
                    }
                case EVENT_THORIM_NOT_REACH_IN_TIME:
                    _isArenaEmpty = true;
                    events.CancelEvent(EVENT_THORIM_LIGHTNING_ORB);
                    me->CastSpell(me, SPELL_BERSERK_FRIENDS, true);
                    me->SummonCreature(NPC_LIGHTNING_ORB, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                    break;
                case EVENT_THORIM_FILL_ARENA:
                    SpawnArenaNPCs();
                    events.Repeat(10s);
                    break;
                case EVENT_THORIM_UNBALANCING_STRIKE:
                    me->CastSpell(me->GetVictim(), SPELL_UNBALANCING_STRIKE, false);
                    events.Repeat(20s);
                    break;
                case EVENT_THORIM_LIGHTNING_CHARGE:
                    me->CastSpell(me, SPELL_LIGHTNING_PILLAR_P2, true);
                    break;
                case EVENT_THORIM_CHAIN_LIGHTNING:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
                        me->CastSpell(target, SPELL_CHAIN_LIGHTNING, false);
                    events.Repeat(15s);
                    break;
                case EVENT_THORIM_BERSERK:
                    me->CastSpell(me, SPELL_BERSERK, true);
                    Talk(SAY_BERSERK);
                    break;
                case EVENT_THORIM_OUTRO1:
                    if (_hardMode)
                    {
                        Talk(SAY_END_HARD_1);
                        events.ScheduleEvent(EVENT_THORIM_OUTRO2, 5s, 0, 3);
                        EntryCheckPredicate pred(NPC_SIF);
                        summons.DoAction(ACTION_SIF_TRANSFORM, pred);
                    }
                    else
                    {
                        Talk(SAY_END_NORMAL_1);
                        events.ScheduleEvent(EVENT_THORIM_OUTRO2, 9s, 0, 3);
                    }
                    break;
                case EVENT_THORIM_OUTRO2:
                    if (_hardMode)
                    {
                        Talk(SAY_END_HARD_2);
                        events.ScheduleEvent(EVENT_THORIM_OUTRO3, 12s, 0, 3);
                    }
                    else
                    {
                        Talk(SAY_END_NORMAL_2);
                        events.ScheduleEvent(EVENT_THORIM_OUTRO3, 10s, 0, 3);
                    }
                    break;
                case EVENT_THORIM_OUTRO3:
                    if (_hardMode)
                    {
                        Talk(SAY_END_HARD_3);
                    }
                    else
                    {
                        Talk(SAY_END_NORMAL_3);
                    }
                    // Defeat credit
                    if (m_pInstance)
                        m_pInstance->SetData(TYPE_THORIM, DONE);
                    events.ScheduleEvent(EVENT_THORIM_OUTRO4, 14s, 0, 3);
                    break;
                case EVENT_THORIM_OUTRO4:
                    DoCastSelf(SPELL_TELEPORT);
                    break;
            }
            if (!_encounterFinished)
                DoMeleeAttackIfReady();
        }
References _encounterFinished, _hardMode, _isArenaEmpty, ACTION_SIF_START_DOMINION, ACTION_SIF_START_TALK, ACTION_SIF_TRANSFORM, Unit::CastCustomSpell(), Unit::CastSpell(), DATA_THORIM_FENCE, SummonList::DoAction(), UnitAI::DoCastSelf(), UnitAI::DoMeleeAttackIfReady(), DONE, EVENT_PHASE_START, EVENT_THORIM_AGGRO, EVENT_THORIM_AGGRO2, EVENT_THORIM_BERSERK, EVENT_THORIM_CHAIN_LIGHTNING, EVENT_THORIM_CHARGE_ORB, EVENT_THORIM_FILL_ARENA, EVENT_THORIM_LIGHTNING_CHARGE, EVENT_THORIM_LIGHTNING_ORB, EVENT_THORIM_NOT_REACH_IN_TIME, EVENT_THORIM_OUTRO1, EVENT_THORIM_OUTRO2, EVENT_THORIM_OUTRO3, EVENT_THORIM_OUTRO4, EVENT_THORIM_START_PHASE1, EVENT_THORIM_STORMHAMMER, EVENT_THORIM_UNBALANCING_STRIKE, GetArenaPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetThorimObject(), Unit::GetVictim(), GO_STATE_READY, Unit::HasUnitState(), m_pInstance, ScriptedAI::me, NPC_LIGHTNING_ORB, NPC_SIF, SAY_AGGRO_1, SAY_AGGRO_2, SAY_BERSERK, SAY_END_HARD_1, SAY_END_HARD_2, SAY_END_HARD_3, SAY_END_NORMAL_1, SAY_END_NORMAL_2, SAY_END_NORMAL_3, SAY_WIPE, UnitAI::SelectTarget(), ZoneScript::SetData(), SpawnArenaNPCs(), SPELL_BERSERK, SPELL_BERSERK_FRIENDS, SPELL_CHAIN_LIGHTNING, SPELL_CHARGE_ORB, SPELL_LIGHTNING_PILLAR_P2, SPELL_STORMHAMMER, SPELL_TELEPORT, SPELL_UNBALANCING_STRIKE, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), summons, TYPE_THORIM, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_encounterFinished
bool boss_thorim::boss_thorimAI::_encounterFinished
Referenced by boss_thorimAI(), DamageTaken(), JustEngagedWith(), Reset(), and UpdateAI().
_hardMode
bool boss_thorim::boss_thorimAI::_hardMode
Referenced by DamageTaken(), GetData(), Reset(), and UpdateAI().
_hitByLightning
bool boss_thorim::boss_thorimAI::_hitByLightning
Referenced by GetData(), Reset(), and SpellHitTarget().
_isAlly
bool boss_thorim::boss_thorimAI::_isAlly
Referenced by Reset(), and SpawnAllNPCs().
_isArenaEmpty
bool boss_thorim::boss_thorimAI::_isArenaEmpty
Referenced by Reset(), and UpdateAI().
_isHitAllowed
bool boss_thorim::boss_thorimAI::_isHitAllowed
Referenced by DamageTaken(), DoAction(), and Reset().
_spawnCommoners
bool boss_thorim::boss_thorimAI::_spawnCommoners
Referenced by Reset(), and SpawnArenaNPCs().
_trashCounter
uint8 boss_thorim::boss_thorimAI::_trashCounter
Referenced by DoAction(), and Reset().
events
EventMap boss_thorim::boss_thorimAI::events
m_pInstance
InstanceScript* boss_thorim::boss_thorimAI::m_pInstance
Referenced by boss_thorimAI(), DamageTaken(), GetThorimObject(), JustEngagedWith(), Reset(), SpellHit(), and UpdateAI().
summons
SummonList boss_thorim::boss_thorimAI::summons
Referenced by DamageTaken(), JustSummoned(), Reset(), and UpdateAI().