AzerothCore: WorldObjectScript Class Reference
WorldObjectScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnWorldObjectDestroy (WorldObject *)
This hook called before destroy world object.
virtual void OnWorldObjectCreate (WorldObject *)
This hook called after create world object.
virtual void OnWorldObjectSetMap (WorldObject *, Map *)
This hook called after world object set to map.
virtual void OnWorldObjectResetMap (WorldObject *)
This hook called after world object reset.
virtual void OnWorldObjectUpdate (WorldObject *, uint32)
This hook called after world object update.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
WorldObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
WorldObjectScript()
WorldObjectScript::WorldObjectScript (const char * name) protected
                                                     : ScriptObject(name)
{
    ScriptRegistry<WorldObjectScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
IsDatabaseBound()
bool WorldObjectScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
OnWorldObjectCreate()
virtual void WorldObjectScript::OnWorldObjectCreate (WorldObject *) inline virtual
This hook called after create world object.
Parameters
object Contains information about the WorldObject
{ }
Referenced by ScriptMgr::OnWorldObjectCreate().
OnWorldObjectDestroy()
virtual void WorldObjectScript::OnWorldObjectDestroy (WorldObject *) inline virtual
This hook called before destroy world object.
Parameters
object Contains information about the WorldObject
{ }
Referenced by ScriptMgr::OnWorldObjectDestroy().
OnWorldObjectResetMap()
virtual void WorldObjectScript::OnWorldObjectResetMap (WorldObject *) inline virtual
This hook called after world object reset.
Parameters
object Contains information about the WorldObject
{ }
Referenced by ScriptMgr::OnWorldObjectResetMap().
OnWorldObjectSetMap()
virtual void WorldObjectScript::OnWorldObjectSetMap (WorldObject * , Map *) inline virtual
This hook called after world object set to map.
Parameters
object Contains information about the WorldObject
{ }
Referenced by ScriptMgr::OnWorldObjectSetMap().
OnWorldObjectUpdate()
virtual void WorldObjectScript::OnWorldObjectUpdate (WorldObject * , uint32) inline virtual
This hook called after world object update.
Parameters
object Contains information about the WorldObject
diff Contains information about the diff time
{ }
Referenced by ScriptMgr::OnWorldObjectUpdate().