AzerothCore: Acore::PowerPctOrderPred Class Reference
Acore::PowerPctOrderPred Class Reference
#include "Unit.h"
Public Member Functions
PowerPctOrderPred (Powers power, bool ascending=true)
bool operator() (WorldObject const *objA, WorldObject const *objB) const
bool operator() (Unit const *a, Unit const *b) const
Private Attributes
Powers const _power
bool const _ascending
Detailed Description
Constructor & Destructor Documentation
PowerPctOrderPred()
Acore::PowerPctOrderPred::PowerPctOrderPred (Powers power, bool ascending = true) inline
: _power(power), _ascending(ascending) { }
Member Function Documentation
operator()() [1/2]
bool Acore::PowerPctOrderPred::operator() (Unit const * a, Unit const * b) const inline
        {
            float rA = a->GetMaxPower(_power) ? float(a->GetPower(_power)) / float(a->GetMaxPower(_power)) : 0.0f;
            float rB = b->GetMaxPower(_power) ? float(b->GetPower(_power)) / float(b->GetMaxPower(_power)) : 0.0f;
            return _ascending ? rA < rB : rA > rB;
        }
References _ascending, _power, Unit::GetMaxPower(), and Unit::GetPower().
operator()() [2/2]
bool Acore::PowerPctOrderPred::operator() (WorldObject const * objA, WorldObject const * objB) const inline
        {
            Unit const* a = objA->ToUnit();
            Unit const* b = objB->ToUnit();
            float rA = (a && a->GetMaxPower(_power)) ? float(a->GetPower(_power)) / float(a->GetMaxPower(_power)) : 0.0f;
            float rB = (b && b->GetMaxPower(_power)) ? float(b->GetPower(_power)) / float(b->GetMaxPower(_power)) : 0.0f;
            return _ascending ? rA < rB : rA > rB;
        }
References _ascending, _power, Unit::GetMaxPower(), Unit::GetPower(), and Object::ToUnit().
Member Data Documentation
_ascending
bool const Acore::PowerPctOrderPred::_ascending private
Referenced by operator()().
_power
Powers const Acore::PowerPctOrderPred::_power private
Referenced by operator()().