AzeorthCore: boss_netherspite::boss_netherspiteAI Struct Reference
boss_netherspite::boss_netherspiteAI Struct Reference
Public Member Functions
boss_netherspiteAI (Creature *creature)
bool IsBetween (WorldObject *u1, WorldObject *target, WorldObject *u2)
float dist (float xa, float ya, float xb, float yb)
void Reset () override
void SummonPortals ()
void DestroyPortals ()
void UpdatePortals ()
void SwitchToPortalPhase ()
void SwitchToBanishPhase ()
void HandleDoors (bool open)
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
Cast Spell.
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
Play sound.
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
Reset Threat.
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
Modify Unit Threat.
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
Teleport player.
void DoTeleportAll (float x, float y, float z, float o)
Teleport all.
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
Set Combat Movement.
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectTargetMethod targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
bool PortalPhase
bool Berserk
uint32 PhaseTimer
uint32 VoidZoneTimer
uint32 NetherInfusionTimer
uint32 NetherbreathTimer
uint32 EmpowermentTimer
uint32 PortalTimer
ObjectGuid PortalGUID [3]
ObjectGuid BeamerGUID [3]
ObjectGuid BeamTarget [3]
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_netherspiteAI()
boss_netherspite::boss_netherspiteAI::boss_netherspiteAI (Creature * creature) inline
                                               : ScriptedAI(creature)
        {
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DestroyPortals()
void boss_netherspite::boss_netherspiteAI::DestroyPortals () inline
        {
            for (int i = 0; i < 3; ++i)
            {
                if (Creature* portal = ObjectAccessor::GetCreature(*me, PortalGUID[i]))
                    portal->DisappearAndDie();
                if (Creature* portal = ObjectAccessor::GetCreature(*me, BeamerGUID[i]))
                    portal->DisappearAndDie();
                PortalGUID[i].Clear();
                BeamTarget[i].Clear();
            }
        }
References BeamerGUID, BeamTarget, ObjectGuid::Clear(), ObjectAccessor::GetCreature(), ScriptedAI::me, and PortalGUID.
Referenced by JustDied(), Reset(), and SwitchToBanishPhase().
dist()
float boss_netherspite::boss_netherspiteAI::dist (float xa, float ya, float xb, float yb) inline
        {
            return std::sqrt((xa - xb) * (xa - xb) + (ya - yb) * (ya - yb));
        }
Referenced by IsBetween().
EnterCombat()
void boss_netherspite::boss_netherspiteAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            HandleDoors(false);
            SwitchToPortalPhase();
            DoZoneInCombat();
        }
References CreatureAI::DoZoneInCombat(), HandleDoors(), and SwitchToPortalPhase().
HandleDoors()
void boss_netherspite::boss_netherspiteAI::HandleDoors (bool open) inline
        {
            if (GameObject* Door = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(DATA_GO_MASSIVE_DOOR) ))
                Door->SetGoState(open ? GO_STATE_ACTIVE : GO_STATE_READY);
        }
References DATA_GO_MASSIVE_DOOR, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_STATE_ACTIVE, GO_STATE_READY, instance, and ScriptedAI::me.
Referenced by EnterCombat(), JustDied(), and Reset().
IsBetween()
bool boss_netherspite::boss_netherspiteAI::IsBetween (WorldObject * u1, WorldObject * target, WorldObject * u2) inline
        {
            if (!u1 || !u2 || !target)
                return false;
            float xn, yn, xp, yp, xh, yh;
            xn = u1->GetPositionX();
            yn = u1->GetPositionY();
            xp = u2->GetPositionX();
            yp = u2->GetPositionY();
            xh = target->GetPositionX();
            yh = target->GetPositionY();
            // check if target is between (not checking distance from the beam yet)
            if (dist(xn, yn, xh, yh) >= dist(xn, yn, xp, yp) || dist(xp, yp, xh, yh) >= dist(xn, yn, xp, yp))
                return false;
            // check  distance from the beam
            return (std::abs((xn - xp) * yh + (yp - yn) * xh - xn * yp + xp * yn) / dist(xn, yn, xp, yp) < 1.5f);
        }
References dist(), Position::GetPositionX(), and Position::GetPositionY().
Referenced by UpdatePortals().
JustDied()
void boss_netherspite::boss_netherspiteAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            HandleDoors(true);
            DestroyPortals();
        }
References DestroyPortals(), and HandleDoors().
Reset()
void boss_netherspite::boss_netherspiteAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            Berserk = false;
            NetherInfusionTimer = 540000;
            VoidZoneTimer = 15000;
            NetherbreathTimer = 3000;
            HandleDoors(true);
            DestroyPortals();
        }
References Berserk, DestroyPortals(), HandleDoors(), NetherbreathTimer, NetherInfusionTimer, and VoidZoneTimer.
SummonPortals()
void boss_netherspite::boss_netherspiteAI::SummonPortals () inline
        {
            uint8 r = rand() % 4;
            uint8 pos[3];
            pos[RED_PORTAL] = ((r % 2) ? (r > 1 ? 2 : 1) : 0);
            pos[GREEN_PORTAL] = ((r % 2) ? 0 : (r > 1 ? 2 : 1));
            pos[BLUE_PORTAL] = (r > 1 ? 1 : 2); // Blue Portal not on the left side (0)
            for (int i = 0; i < 3; ++i)
                if (Creature* portal = me->SummonCreature(PortalID[i], PortalCoord[pos[i]][0], PortalCoord[pos[i]][1], PortalCoord[pos[i]][2], 0, TEMPSUMMON_TIMED_DESPAWN, 60000))
                {
                    PortalGUID[i] = portal->GetGUID();
                    portal->AddAura(PortalVisual[i], portal);
                }
        }
References BLUE_PORTAL, GREEN_PORTAL, ScriptedAI::me, PortalCoord, PortalGUID, PortalID, PortalVisual, RED_PORTAL, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
Referenced by SwitchToPortalPhase().
SwitchToBanishPhase()
void boss_netherspite::boss_netherspiteAI::SwitchToBanishPhase () inline
        {
            me->RemoveAurasDueToSpell(SPELL_EMPOWERMENT);
            me->RemoveAurasDueToSpell(SPELL_NETHERBURN_AURA);
            DoCast(me, SPELL_BANISH_VISUAL, true);
            DoCast(me, SPELL_BANISH_ROOT, true);
            DestroyPortals();
            PhaseTimer = 30000;
            PortalPhase = false;
            Talk(EMOTE_PHASE_BANISH);
            for (uint8 i = 0; i < 3; ++i)
                me->RemoveAurasDueToSpell(NetherBuff[i]);
        }
References DestroyPortals(), UnitAI::DoCast(), EMOTE_PHASE_BANISH, ScriptedAI::me, NetherBuff, PhaseTimer, PortalPhase, Unit::RemoveAurasDueToSpell(), SPELL_BANISH_ROOT, SPELL_BANISH_VISUAL, SPELL_EMPOWERMENT, and SPELL_NETHERBURN_AURA.
Referenced by UpdateAI().
SwitchToPortalPhase()
void boss_netherspite::boss_netherspiteAI::SwitchToPortalPhase () inline
        {
            me->RemoveAurasDueToSpell(SPELL_BANISH_ROOT);
            me->RemoveAurasDueToSpell(SPELL_BANISH_VISUAL);
            SummonPortals();
            PhaseTimer = 60000;
            PortalPhase = true;
            PortalTimer = 10000;
            EmpowermentTimer = 10000;
            Talk(EMOTE_PHASE_PORTAL);
        }
References EMOTE_PHASE_PORTAL, EmpowermentTimer, ScriptedAI::me, PhaseTimer, PortalPhase, PortalTimer, Unit::RemoveAurasDueToSpell(), SPELL_BANISH_ROOT, SPELL_BANISH_VISUAL, and SummonPortals().
Referenced by EnterCombat(), and UpdateAI().
UpdateAI()
void boss_netherspite::boss_netherspiteAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            // Void Zone
            if (VoidZoneTimer <= diff)
            {
                DoCast(SelectTarget(SelectTargetMethod::Random, 1, 45, true), SPELL_VOIDZONE, true);
                VoidZoneTimer = 15000;
            }
            else
                VoidZoneTimer -= diff;
            // NetherInfusion Berserk
            if (!Berserk && NetherInfusionTimer <= diff)
            {
                me->AddAura(SPELL_NETHER_INFUSION, me);
                DoCast(me, SPELL_NETHERSPITE_ROAR);
                Berserk = true;
            }
            else
                NetherInfusionTimer -= diff;
            if (PortalPhase) // PORTAL PHASE
            {
                // Distribute beams and buffs
                if (PortalTimer <= diff)
                {
                    UpdatePortals();
                    PortalTimer = 1000;
                }
                else
                    PortalTimer -= diff;
                // Empowerment & Nether Burn
                if (EmpowermentTimer <= diff)
                {
                    DoCast(me, SPELL_EMPOWERMENT);
                    me->AddAura(SPELL_NETHERBURN_AURA, me);
                    EmpowermentTimer = 90000;
                }
                else
                    EmpowermentTimer -= diff;
                if (PhaseTimer <= diff)
                {
                    if (!me->IsNonMeleeSpellCast(false))
                    {
                        SwitchToBanishPhase();
                        return;
                    }
                }
                else
                    PhaseTimer -= diff;
            }
            else // BANISH PHASE
            {
                // Netherbreath
                if (NetherbreathTimer <= diff)
                {
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 40, true))
                        DoCast(target, SPELL_NETHERBREATH);
                    NetherbreathTimer = urand(5000, 7000);
                }
                else
                    NetherbreathTimer -= diff;
                if (PhaseTimer <= diff)
                {
                    if (!me->IsNonMeleeSpellCast(false))
                    {
                        SwitchToPortalPhase();
                        return;
                    }
                }
                else
                    PhaseTimer -= diff;
            }
            DoMeleeAttackIfReady();
        }
References Unit::AddAura(), Berserk, UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), EmpowermentTimer, Unit::IsNonMeleeSpellCast(), ScriptedAI::me, NetherbreathTimer, NetherInfusionTimer, PhaseTimer, PortalPhase, PortalTimer, UnitAI::SelectTarget(), SPELL_EMPOWERMENT, SPELL_NETHER_INFUSION, SPELL_NETHERBREATH, SPELL_NETHERBURN_AURA, SPELL_NETHERSPITE_ROAR, SPELL_VOIDZONE, SwitchToBanishPhase(), SwitchToPortalPhase(), UpdatePortals(), CreatureAI::UpdateVictim(), urand(), and VoidZoneTimer.
UpdatePortals()
void boss_netherspite::boss_netherspiteAI::UpdatePortals () inline
        {
            for (int j = 0; j < 3; ++j) // j = color
                if (Creature* portal = ObjectAccessor::GetCreature(*me, PortalGUID[j]))
                {
                    // the one who's been cast upon before
                    Unit* current = ObjectAccessor::GetUnit(*portal, BeamTarget[j]);
                    // temporary store for the best suitable beam reciever
                    Unit* target = me;
                    if (Map* map = me->GetMap())
                    {
                        Map::PlayerList const& players = map->GetPlayers();
                        // get the best suitable target
                        for (Map::PlayerList::const_iterator i = players.begin(); i != players.end(); ++i)
{
                            Player* p = i->GetSource();
                            if (p && p->IsAlive() // alive
                                    && (!target || target->GetDistance2d(portal) > p->GetDistance2d(portal)) // closer than current best
                                    && !p->HasAura(PlayerDebuff[j]) // not exhausted
                                    && !p->HasAura(PlayerBuff[(j + 1) % 3]) // not on another beam
                                    && !p->HasAura(PlayerBuff[(j + 2) % 3])
                                    && IsBetween(me, p, portal)) // on the beam
                                target = p;
                        }
                    }
                    // buff the target
                    if (target->GetTypeId() == TYPEID_PLAYER)
                        target->AddAura(PlayerBuff[j], target);
                    else
                        target->AddAura(NetherBuff[j], target);
                    // cast visual beam on the chosen target if switched
                    // simple target switching isn't working -> using BeamerGUID to cast (workaround)
                    if (!current || target != current)
                    {
                        BeamTarget[j] = target->GetGUID();
                        // remove currently beaming portal
                        if (Creature* beamer = ObjectAccessor::GetCreature(*portal, BeamerGUID[j]))
{
                            beamer->CastSpell(target, PortalBeam[j], false);
                            beamer->DisappearAndDie();
                            BeamerGUID[j].Clear();
                        }
                        // create new one and start beaming on the target
                        if (Creature* beamer = portal->SummonCreature(PortalID[j], portal->GetPositionX(), portal->GetPositionY(), portal->GetPositionZ(), portal->GetOrientation(), TEMPSUMMON_TIMED_DESPAWN, 60000))
{
                            beamer->CastSpell(target, PortalBeam[j], false);
                            BeamerGUID[j] = beamer->GetGUID();
                        }
                    }
                    // aggro target if Red Beam
                    if (j == RED_PORTAL && me->GetVictim() != target && target->GetTypeId() == TYPEID_PLAYER)
                        me->GetThreatMgr().AddThreat(target, 100000.0f + DoGetThreat(me->GetVictim()));
                }
        }
References Unit::AddAura(), ThreatMgr::AddThreat(), BeamerGUID, BeamTarget, MapRefMgr::begin(), ObjectGuid::Clear(), ScriptedAI::DoGetThreat(), MapRefMgr::end(), ObjectAccessor::GetCreature(), WorldObject::GetDistance2d(), Object::GetGUID(), WorldObject::GetMap(), Unit::GetThreatMgr(), Object::GetTypeId(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::HasAura(), Unit::IsAlive(), IsBetween(), ScriptedAI::me, NetherBuff, PlayerBuff, PlayerDebuff, PortalBeam, PortalGUID, PortalID, RED_PORTAL, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, and TYPEID_PLAYER.
Referenced by UpdateAI().
Member Data Documentation
BeamerGUID
ObjectGuid boss_netherspite::boss_netherspiteAI::BeamerGUID[3]
Referenced by DestroyPortals(), and UpdatePortals().
BeamTarget
ObjectGuid boss_netherspite::boss_netherspiteAI::BeamTarget[3]
Referenced by DestroyPortals(), and UpdatePortals().
Berserk
bool boss_netherspite::boss_netherspiteAI::Berserk
Referenced by Reset(), and UpdateAI().
EmpowermentTimer
uint32 boss_netherspite::boss_netherspiteAI::EmpowermentTimer
Referenced by SwitchToPortalPhase(), and UpdateAI().
instance
InstanceScript* boss_netherspite::boss_netherspiteAI::instance
Referenced by boss_netherspiteAI(), and HandleDoors().
NetherbreathTimer
uint32 boss_netherspite::boss_netherspiteAI::NetherbreathTimer
Referenced by Reset(), and UpdateAI().
NetherInfusionTimer
uint32 boss_netherspite::boss_netherspiteAI::NetherInfusionTimer
Referenced by Reset(), and UpdateAI().
PhaseTimer
uint32 boss_netherspite::boss_netherspiteAI::PhaseTimer
Referenced by SwitchToBanishPhase(), SwitchToPortalPhase(), and UpdateAI().
PortalGUID
ObjectGuid boss_netherspite::boss_netherspiteAI::PortalGUID[3]
Referenced by DestroyPortals(), SummonPortals(), and UpdatePortals().
PortalPhase
bool boss_netherspite::boss_netherspiteAI::PortalPhase
Referenced by SwitchToBanishPhase(), SwitchToPortalPhase(), and UpdateAI().
PortalTimer
uint32 boss_netherspite::boss_netherspiteAI::PortalTimer
Referenced by SwitchToPortalPhase(), and UpdateAI().
VoidZoneTimer
uint32 boss_netherspite::boss_netherspiteAI::VoidZoneTimer
Referenced by Reset(), and UpdateAI().