AzerothCore: boss_julianne Struct Reference
boss_julianne Struct Reference
Public Member Functions
boss_julianne (Creature *creature)
void Reset () override
void DoAction (int32 action) override
void ScheduleCombat ()
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustReachedHome () override
void SpellHit (Unit *, SpellInfo const *Spell) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void EnterEvadeMode (EvadeReason reason) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
uint32 phase
bool isFakingDeath
bool summonedRomulo
bool romuloDied
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Private Attributes
TaskScheduler _scheduler
TaskScheduler _resurrectScheduler
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_julianne()
boss_julianne::boss_julianne (Creature * creature) inline
                                      : ScriptedAI(creature)
    {
        instance = creature->GetInstanceScript();
        isFakingDeath = false;
    }
References WorldObject::GetInstanceScript(), instance, and isFakingDeath.
Member Function Documentation
AttackStart()
void boss_julianne::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
            return;
        ScriptedAI::AttackStart(who);
    }
References ScriptedAI::AttackStart(), Unit::HasUnitFlag(), ScriptedAI::me, and UNIT_FLAG_NON_ATTACKABLE.
DamageTaken()
void boss_julianne::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (damage < me->GetHealth())
        {
            return;
        }
        //anything below only used if incoming damage will kill
        if (phase == PHASE_JULIANNE)
        {
            damage = 0;
            //this means already drinking, so return
            if (isFakingDeath)
            {
                return;
            }
            me->InterruptNonMeleeSpells(true);
            DoCast(me, SPELL_DRINK_POISON);
            me->GetMotionMaster()->Clear();
            isFakingDeath = true;
            return;
        }
        if (phase == PHASE_ROMULO)
        {
            //LOG_ERROR("scripts", "boss_julianneAI: cannot take damage in PHASE_ROMULO, why was i here?");
            damage = 0;
            return;
        }
        if (phase == PHASE_BOTH)
        {
            //if this is true then we have to kill romulo too
            if (romuloDied)
            {
                if (Creature* Romulo = instance->GetCreature(DATA_ROMULO))
                {
                    _scheduler.CancelAll();
                    _resurrectScheduler.CancelAll();
                    Romulo->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    Romulo->GetMotionMaster()->Clear();
                    Romulo->setDeathState(JUST_DIED);
                    Romulo->CombatStop(true);
                    Romulo->GetThreatMgr().ClearAllThreat();
                    Romulo->ReplaceAllDynamicFlags(UNIT_DYNFLAG_LOOTABLE);
                    //this does not seem to really work - the lootable dynamic flags
                }
                return;
            }
            //if not already returned, then romulo is alive and we can pretend die
            if (Creature* Romulo = instance->GetCreature(DATA_ROMULO))
            {
                PretendToDie(me);
                isFakingDeath = true;
                Romulo->AI()->DoAction(ACTION_EARLY_REVIVE);
                _scheduler.Schedule(10050ms, [this](TaskContext)
                {
                    Resurrect(me);
                    isFakingDeath = false;
                });
                damage = 0;
                return;
            }
        }
        //LOG_ERROR("scripts", "boss_julianneAI: DamageTaken reach end of code, that should not happen.");
    }
References _resurrectScheduler, _scheduler, ACTION_EARLY_REVIVE, TaskScheduler::CancelAll(), MotionMaster::Clear(), DATA_ROMULO, UnitAI::DoCast(), InstanceScript::GetCreature(), Unit::GetMotionMaster(), instance, Unit::InterruptNonMeleeSpells(), isFakingDeath, JUST_DIED, ScriptedAI::me, PHASE_BOTH, PHASE_JULIANNE, PHASE_ROMULO, PretendToDie(), Resurrect(), romuloDied, TaskScheduler::Schedule(), SPELL_DRINK_POISON, UNIT_DYNFLAG_LOOTABLE, and UNIT_FLAG_NOT_SELECTABLE.
DoAction()
void boss_julianne::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        switch(action)
        {
            case ACTION_DIED_ANNOUNCE:
                romuloDied = true;
                break;
            case ACTION_EARLY_REVIVE:
                romuloDied = true;
                _resurrectScheduler.Schedule(10s, [this](TaskContext)
                {
                    Talk(SAY_JULIANNE_RESURRECT);
                    romuloDied = false;
                });
                break;
            case ACTION_PHASE_SET:
                phase = PHASE_BOTH;
                isFakingDeath = false;
                break;
            case ACTION_FAKING_DEATH:
                isFakingDeath = false;
                break;
            case ACTION_COMBAT_SCHEDULE:
                ScheduleCombat();
                break;
            case ACTION_DO_RESURRECT:
                _resurrectScheduler.Schedule(1s, [this](TaskContext)
                {
                    if (Creature* Romulo = instance->GetCreature(DATA_ROMULO))
                    {
                        Talk(SAY_JULIANNE_RESURRECT);
                        Resurrect(Romulo);
                        Romulo->AI()->DoAction(ACTION_FAKING_DEATH);
                        romuloDied = false;
                    }
                });
                break;
            case ACTION_CANCEL_COMBAT:
                _scheduler.CancelGroup(GROUP_COMBAT);
                break;
        }
    }
References _resurrectScheduler, _scheduler, ACTION_CANCEL_COMBAT, ACTION_COMBAT_SCHEDULE, ACTION_DIED_ANNOUNCE, ACTION_DO_RESURRECT, ACTION_EARLY_REVIVE, ACTION_FAKING_DEATH, ACTION_PHASE_SET, TaskScheduler::CancelGroup(), DATA_ROMULO, InstanceScript::GetCreature(), GROUP_COMBAT, instance, isFakingDeath, PHASE_BOTH, romuloDied, SAY_JULIANNE_RESURRECT, TaskScheduler::Schedule(), and ScheduleCombat().
EnterEvadeMode()
void boss_julianne::EnterEvadeMode (EvadeReason reason) inline override virtual
Reimplemented from CreatureAI.
    {
        ScriptedAI::EnterEvadeMode(reason);
        if (!me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
        {
            me->DespawnOrUnsummon();
            instance->SetBossState(DATA_OPERA_PERFORMANCE, FAIL);
        }
    }
References DATA_OPERA_PERFORMANCE, Creature::DespawnOrUnsummon(), CreatureAI::EnterEvadeMode(), FAIL, Unit::HasUnitFlag(), instance, ScriptedAI::me, InstanceScript::SetBossState(), and UNIT_FLAG_NON_ATTACKABLE.
JustDied()
void boss_julianne::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        Talk(SAY_JULIANNE_DEATH02);
        instance->SetBossState(DATA_OPERA_PERFORMANCE, DONE);
    }
References DATA_OPERA_PERFORMANCE, DONE, instance, SAY_JULIANNE_DEATH02, and InstanceScript::SetBossState().
JustEngagedWith()
void boss_julianne::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
    {
        ScheduleCombat();
    }
References ScheduleCombat().
JustReachedHome()
void boss_julianne::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
    {
        me->DespawnOrUnsummon();
    }
References Creature::DespawnOrUnsummon(), and ScriptedAI::me.
KilledUnit()
void boss_julianne::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        Talk(SAY_JULIANNE_SLAY);
    }
References SAY_JULIANNE_SLAY.
MoveInLineOfSight()
void boss_julianne::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
    {
        if (me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
            return;
        ScriptedAI::MoveInLineOfSight(who);
    }
References Unit::HasUnitFlag(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), and UNIT_FLAG_NON_ATTACKABLE.
Reset()
void boss_julianne::Reset () inline override virtual
Reimplemented from ScriptedAI.
    {
        phase = PHASE_JULIANNE;
        if (isFakingDeath)
        {
            Resurrect(me);
            isFakingDeath = false;
        }
        summonedRomulo = false;
        romuloDied = false;
        me->SetImmuneToPC(true);
        //intro sequence
        _scheduler.Schedule(1s, [this](TaskContext)
        {
            Talk(SAY_JULIANNE_ENTER);
        }).Schedule(10s, [this](TaskContext)
        {
            Talk(SAY_JULIANNE_AGGRO);
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            me->SetImmuneToPC(false);
            me->SetInCombatWithZone();
        });
    }
References _scheduler, isFakingDeath, ScriptedAI::me, PHASE_JULIANNE, Unit::RemoveUnitFlag(), Resurrect(), romuloDied, SAY_JULIANNE_AGGRO, SAY_JULIANNE_ENTER, TaskScheduler::Schedule(), Unit::SetImmuneToPC(), Creature::SetInCombatWithZone(), summonedRomulo, and UNIT_FLAG_NON_ATTACKABLE.
ScheduleCombat()
void boss_julianne::ScheduleCombat () inline
    {
        _scheduler.Schedule(30s, GROUP_COMBAT, [this](TaskContext context)
        {
            DoCastRandomTarget(SPELL_BLINDING_PASSION);
            context.Repeat(30s, 45s);
        }).Schedule(15s, GROUP_COMBAT, [this](TaskContext context)
        {
            DoCastSelf(SPELL_DEVOTION);
            context.Repeat(15s, 45s);
        }).Schedule(5s, GROUP_COMBAT, [this](TaskContext context)
        {
            DoCastRandomTarget(SPELL_POWERFUL_ATTRACTION);
            context.Repeat(5s, 30s);
        }).Schedule(25s, GROUP_COMBAT, [this](TaskContext context)
        {
            if (urand(0, 1) && summonedRomulo)
            {
                if (Creature* Romulo = instance->GetCreature(DATA_ROMULO))
                {
                    if (Romulo->IsAlive() && !romuloDied)
                    {
                        DoCast(Romulo, SPELL_ETERNAL_AFFECTION);
                    }
                }
            }
            else
            {
                DoCast(me, SPELL_ETERNAL_AFFECTION);
            }
            context.Repeat(45s, 60s);
        });
    }
References _scheduler, DATA_ROMULO, UnitAI::DoCast(), UnitAI::DoCastRandomTarget(), UnitAI::DoCastSelf(), InstanceScript::GetCreature(), GROUP_COMBAT, instance, ScriptedAI::me, TaskContext::Repeat(), romuloDied, TaskScheduler::Schedule(), SPELL_BLINDING_PASSION, SPELL_DEVOTION, SPELL_ETERNAL_AFFECTION, SPELL_POWERFUL_ATTRACTION, summonedRomulo, and urand().
Referenced by DoAction(), and JustEngagedWith().
SpellHit()
void boss_julianne::SpellHit (Unit * , SpellInfo const * Spell) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (Spell->Id == SPELL_DRINK_POISON)
        {
            Talk(SAY_JULIANNE_DEATH01);
            _scheduler.CancelGroup(GROUP_COMBAT);
            _scheduler.Schedule(2500ms, GROUP_RP, [this](TaskContext)
            {
                //will do this 2secs after spell hit. this is time to display visual as expected
                PretendToDie(me);
                phase = PHASE_ROMULO;
                _scheduler.Schedule(10s, GROUP_RP, [this](TaskContext)
                {
                    if (Creature* pRomulo = me->SummonCreature(CREATURE_ROMULO, ROMULO_X, ROMULO_Y, me->GetPositionZ(), 0, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, HOUR * 2 * IN_MILLISECONDS))
                    {
                        pRomulo->AI()->DoAction(ACTION_PHASE_SET);
                        pRomulo->SetInCombatWithZone();
                    }
                    summonedRomulo = true;
                });
            });
        }
    }
References _scheduler, TaskScheduler::CancelGroup(), CREATURE_ROMULO, Position::GetPositionZ(), GROUP_COMBAT, GROUP_RP, HOUR, IN_MILLISECONDS, ScriptedAI::me, PHASE_ROMULO, PretendToDie(), ROMULO_X, ROMULO_Y, SAY_JULIANNE_DEATH01, TaskScheduler::Schedule(), SPELL_DRINK_POISON, WorldObject::SummonCreature(), summonedRomulo, and TEMPSUMMON_TIMED_OR_DEAD_DESPAWN.
UpdateAI()
void boss_julianne::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
    {
        _scheduler.Update(diff);
        _resurrectScheduler.Update(diff);
        if (!UpdateVictim())
        {
            return;
        }
        if (!isFakingDeath)
        {
            DoMeleeAttackIfReady();
        }
    }
References _resurrectScheduler, _scheduler, UnitAI::DoMeleeAttackIfReady(), isFakingDeath, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_resurrectScheduler
TaskScheduler boss_julianne::_resurrectScheduler private
Referenced by DamageTaken(), DoAction(), and UpdateAI().
_scheduler
TaskScheduler boss_julianne::_scheduler private
Referenced by DamageTaken(), DoAction(), Reset(), ScheduleCombat(), SpellHit(), and UpdateAI().
instance
InstanceScript* boss_julianne::instance
Referenced by boss_julianne(), DamageTaken(), DoAction(), EnterEvadeMode(), JustDied(), and ScheduleCombat().
isFakingDeath
bool boss_julianne::isFakingDeath
Referenced by boss_julianne(), DamageTaken(), DoAction(), Reset(), and UpdateAI().
phase
uint32 boss_julianne::phase
romuloDied
bool boss_julianne::romuloDied
Referenced by DamageTaken(), DoAction(), Reset(), and ScheduleCombat().
summonedRomulo
bool boss_julianne::summonedRomulo
Referenced by Reset(), ScheduleCombat(), and SpellHit().