AzerothCore: achievement_commandscript Class Reference
achievement_commandscript Class Reference
Public Member Functions
achievement_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleAchievementAddCommand (ChatHandler *handler, AchievementEntry const *achievementEntry)
static bool HandleAchievementCheckAllCommand (ChatHandler *handler, Optional< PlayerIdentifier > player)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_commandscript()
achievement_commandscript::achievement_commandscript () inline
: CommandScript("achievement_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable achievement_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable achievementCommandTable =
        {
            { "add",      HandleAchievementAddCommand,      SEC_GAMEMASTER,    Console::No },
            { "checkall", HandleAchievementCheckAllCommand, SEC_ADMINISTRATOR, Console::Yes }
        };
        static ChatCommandTable commandTable =
        {
            { "achievement", achievementCommandTable }
        };
        return commandTable;
    }
References HandleAchievementAddCommand(), HandleAchievementCheckAllCommand(), SEC_ADMINISTRATOR, and SEC_GAMEMASTER.
HandleAchievementAddCommand()
static bool achievement_commandscript::HandleAchievementAddCommand (ChatHandler * handler, AchievementEntry const * achievementEntry) inline static
    {
        Player* target = handler->getSelectedPlayer();
        if (!target)
        {
            handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
            handler->SetSentErrorMessage(true);
            return false;
        }
        target->CompletedAchievement(achievementEntry);
        return true;
    }
References Player::CompletedAchievement(), ChatHandler::getSelectedPlayer(), LANG_NO_CHAR_SELECTED, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().
HandleAchievementCheckAllCommand()
static bool achievement_commandscript::HandleAchievementCheckAllCommand (ChatHandler * handler, Optional< PlayerIdentifier > player) inline static
    {
        if (!player)
        {
            player = PlayerIdentifier::FromTarget(handler);
        }
        if (!player)
        {
            handler->SendSysMessage(LANG_PLAYER_NOT_FOUND);
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (player->IsConnected())
        {
            if (Player* target = player->GetConnectedPlayer())
                target->CheckAllAchievementCriteria();
        }
        else
        {
            auto* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_ADD_AT_LOGIN_FLAG);
            stmt->SetData(0, uint16(AT_LOGIN_CHECK_ACHIEVS));
            stmt->SetData(1, player->GetGUID().GetCounter());
            CharacterDatabase.Execute(stmt);
        }
        return true;
    }
References AT_LOGIN_CHECK_ACHIEVS, CHAR_UPD_ADD_AT_LOGIN_FLAG, CharacterDatabase, Acore::ChatCommands::PlayerIdentifier::FromTarget(), LANG_PLAYER_NOT_FOUND, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().