AzerothCore: npc_madrigosa Struct Reference
npc_madrigosa Struct Reference
Public Member Functions
npc_madrigosa (Creature *creature)
void DoAction (int32 param) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
InstanceScript * instance
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_madrigosa()
npc_madrigosa::npc_madrigosa (Creature * creature) inline
                                      : NullCreatureAI(creature)
    {
        instance = creature->GetInstanceScript();
        creature->SetStandState(UNIT_STAND_STATE_DEAD);
        creature->SetDynamicFlag(UNIT_DYNFLAG_DEAD);
        if (instance->IsBossDone(DATA_BRUTALLUS))
            creature->SetVisible(false);
    }
References DATA_BRUTALLUS, WorldObject::GetInstanceScript(), instance, InstanceScript::IsBossDone(), Object::SetDynamicFlag(), Unit::SetStandState(), Unit::SetVisible(), UNIT_DYNFLAG_DEAD, and UNIT_STAND_STATE_DEAD.
Member Function Documentation
DoAction()
void npc_madrigosa::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
    {
        if (param == ACTION_START_EVENT)
        {
            me->SetDisableGravity(true);
            me->SetStandState(UNIT_STAND_STATE_STAND);
            me->RemoveDynamicFlag(UNIT_DYNFLAG_DEAD);
            me->NearTeleportTo(1570.97f, 725.51f, 79.77f, 3.82f);
            events.ScheduleEvent(EVENT_MAD_1, 2000);
        }
        else if (param == ACTION_SPAWN_FELMYST)
            events.ScheduleEvent(EVENT_SPAWN_FELMYST, 60000);
    }
References ACTION_SPAWN_FELMYST, ACTION_START_EVENT, EVENT_MAD_1, EVENT_SPAWN_FELMYST, CreatureAI::me, Unit::NearTeleportTo(), Object::RemoveDynamicFlag(), Creature::SetDisableGravity(), Unit::SetStandState(), UNIT_DYNFLAG_DEAD, and UNIT_STAND_STATE_STAND.
UpdateAI()
void npc_madrigosa::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
    {
        events.Update(diff);
        switch (events.ExecuteEvent())
        {
        case EVENT_MAD_1:
            me->SetVisible(true);
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
            {
                me->SetTarget(brutallus->GetGUID());
                brutallus->SetReactState(REACT_PASSIVE);
                brutallus->setActive(true);
            }
            me->GetMotionMaster()->MovePoint(1, 1477.94f, 643.22f, 21.21f);
            me->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
            events.ScheduleEvent(EVENT_MAD_2, 6000);
            break;
        case EVENT_MAD_2:
            Talk(SAY_MAD_1);
            me->CastSpell(me, SPELL_MADRIGOSA_FREEZE, false);
            events.ScheduleEvent(EVENT_MAD_2_1, 1000);
            break;
        case EVENT_MAD_2_1:
            me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
            me->SetDisableGravity(false);
            me->CastSpell(me, SPELL_MADRIGOSA_FROST_BREATH, false);
            events.ScheduleEvent(EVENT_MAD_3, 7000);
            break;
        case EVENT_MAD_3:
            Talk(SAY_MAD_2);
            events.ScheduleEvent(EVENT_MAD_4, 7000);
            break;
        case EVENT_MAD_4:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
                brutallus->AI()->Talk(YELL_INTRO);
            events.ScheduleEvent(EVENT_MAD_5, 5000);
            break;
        case EVENT_MAD_5:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
            {
                brutallus->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_ATTACK1H);
                me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_ATTACK1H);
            }
            events.ScheduleEvent(EVENT_MAD_6, 10000);
            break;
        case EVENT_MAD_6:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
            {
                brutallus->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
            }
            me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
            me->SetDisableGravity(true);
            events.ScheduleEvent(EVENT_MAD_7, 4000);
            break;
        case EVENT_MAD_7:
            Talk(SAY_MAD_3);
            me->CastSpell(me, SPELL_MADRIGOSA_FROST_BLAST, false);
            events.ScheduleEvent(EVENT_MAD_8, 3000);
            events.ScheduleEvent(EVENT_MAD_8, 5000);
            events.ScheduleEvent(EVENT_MAD_8, 6500);
            events.ScheduleEvent(EVENT_MAD_8, 7500);
            events.ScheduleEvent(EVENT_MAD_8, 8500);
            events.ScheduleEvent(EVENT_MAD_8, 9500);
            events.ScheduleEvent(EVENT_MAD_9, 11000);
            events.ScheduleEvent(EVENT_MAD_8, 12000);
            events.ScheduleEvent(EVENT_MAD_8, 14000);
            break;
        case EVENT_MAD_8:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
                me->CastSpell(brutallus, SPELL_MADRIGOSA_FROSTBOLT, false);
            break;
        case EVENT_MAD_9:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
            {
                brutallus->CastSpell(brutallus, SPELL_BRUTALLUS_FLAME_RING, true);
                brutallus->RemoveAllAuras();
                brutallus->CastSpell(brutallus, SPELL_BRUTALLUS_FEL_FIREBALL, false);
                brutallus->AI()->Talk(YELL_INTRO_BREAK_ICE);
            }
            events.ScheduleEvent(EVENT_MAD_11, 6000);
            break;
            //case EVENT_MAD_10:
        case EVENT_MAD_11:
            me->SetDisableGravity(false);
            me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
            events.ScheduleEvent(EVENT_MAD_13, 2500);
            break;
        case EVENT_MAD_13:
            Talk(SAY_MAD_4);
            me->RemoveAllAuras();
            me->CastSpell(me, SPELL_MADRIGOSA_ENCAPSULATE, false);
            events.ScheduleEvent(EVENT_MAD_14, 2000);
            break;
        case EVENT_MAD_14:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
            {
                brutallus->SetDisableGravity(true);
                brutallus->GetMotionMaster()->MovePoint(0, brutallus->GetPositionX(), brutallus->GetPositionY() - 30.0f, brutallus->GetPositionZ() + 15.0f, false, true);
            }
            events.ScheduleEvent(EVENT_MAD_15, 10000);
            break;
        case EVENT_MAD_15:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
            {
                brutallus->RemoveAllAuras();
                brutallus->SetDisableGravity(false);
                brutallus->GetMotionMaster()->MoveFall();
                brutallus->AI()->Talk(YELL_INTRO_CHARGE);
            }
            events.ScheduleEvent(EVENT_MAD_16, 1400);
            break;
        case EVENT_MAD_16:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
                brutallus->CastSpell(me, SPELL_BRUTALLUS_CHARGE, true);
            events.ScheduleEvent(EVENT_MAD_17, 1200);
            break;
        case EVENT_MAD_17:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
                brutallus->HandleEmoteCommand(EMOTE_ONESHOT_ATTACK1H);
            events.ScheduleEvent(EVENT_MAD_18, 500);
            break;
        case EVENT_MAD_18:
            Talk(SAY_MAD_5);
            me->SetDynamicFlag(UNIT_DYNFLAG_DEAD);
            me->SetStandState(UNIT_STAND_STATE_DEAD);
            events.ScheduleEvent(EVENT_MAD_19, 6000);
            break;
        case EVENT_MAD_19:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
                brutallus->AI()->Talk(YELL_INTRO_KILL_MADRIGOSA);
            events.ScheduleEvent(EVENT_MAD_20, 7000);
            break;
        case EVENT_MAD_20:
            me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            me->SetFaction(FACTION_FRIENDLY);
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
            {
                brutallus->AI()->Talk(YELL_INTRO_TAUNT);
                brutallus->CastSpell(brutallus, SPELL_BRUTALLUS_BREAK_ICE, false);
            }
            events.ScheduleEvent(EVENT_MAD_21, 4000);
            break;
        case EVENT_MAD_21:
            if (Creature* brutallus = instance->GetCreature(DATA_BRUTALLUS))
            {
                brutallus->SetReactState(REACT_AGGRESSIVE);
                brutallus->SetHealth(brutallus->GetMaxHealth());
                brutallus->AI()->EnterEvadeMode();
                brutallus->setActive(false);
            }
            break;
        case EVENT_SPAWN_FELMYST:
            me->DespawnOrUnsummon(1);
            if (Creature* felmyst = instance->GetCreature(DATA_FELMYST))
                felmyst->AI()->DoAction(ACTION_START_EVENT);
            break;
        }
    }
References ACTION_START_EVENT, Unit::AddUnitState(), Unit::CastSpell(), DATA_BRUTALLUS, DATA_FELMYST, Creature::DespawnOrUnsummon(), EMOTE_ONESHOT_ATTACK1H, EMOTE_ONESHOT_LAND, EMOTE_ONESHOT_LIFTOFF, EMOTE_ONESHOT_NONE, EVENT_MAD_1, EVENT_MAD_11, EVENT_MAD_13, EVENT_MAD_14, EVENT_MAD_15, EVENT_MAD_16, EVENT_MAD_17, EVENT_MAD_18, EVENT_MAD_19, EVENT_MAD_2, EVENT_MAD_20, EVENT_MAD_21, EVENT_MAD_2_1, EVENT_MAD_3, EVENT_MAD_4, EVENT_MAD_5, EVENT_MAD_6, EVENT_MAD_7, EVENT_MAD_8, EVENT_MAD_9, EVENT_SPAWN_FELMYST, FACTION_FRIENDLY, InstanceScript::GetCreature(), Unit::GetMotionMaster(), Unit::HandleEmoteCommand(), instance, CreatureAI::me, MotionMaster::MovePoint(), REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAllAuras(), SAY_MAD_1, SAY_MAD_2, SAY_MAD_3, SAY_MAD_4, SAY_MAD_5, Creature::SetDisableGravity(), Object::SetDynamicFlag(), Unit::SetFaction(), Unit::SetStandState(), Creature::SetTarget(), Unit::SetUInt32Value(), Unit::SetUnitFlag(), Unit::SetVisible(), SPELL_BRUTALLUS_BREAK_ICE, SPELL_BRUTALLUS_CHARGE, SPELL_BRUTALLUS_FEL_FIREBALL, SPELL_BRUTALLUS_FLAME_RING, SPELL_MADRIGOSA_ENCAPSULATE, SPELL_MADRIGOSA_FREEZE, SPELL_MADRIGOSA_FROST_BLAST, SPELL_MADRIGOSA_FROST_BREATH, SPELL_MADRIGOSA_FROSTBOLT, UNIT_DYNFLAG_DEAD, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_EMOTESTATE, UNIT_STAND_STATE_DEAD, UNIT_STATE_NO_ENVIRONMENT_UPD, YELL_INTRO, YELL_INTRO_BREAK_ICE, YELL_INTRO_CHARGE, YELL_INTRO_KILL_MADRIGOSA, and YELL_INTRO_TAUNT.
Member Data Documentation
events
EventMap npc_madrigosa::events
instance
InstanceScript* npc_madrigosa::instance
Referenced by npc_madrigosa(), and UpdateAI().