AzerothCore: boss_sartharion::boss_sartharionAI Struct Reference
boss_sartharion::boss_sartharionAI Struct Reference
Public Member Functions
boss_sartharionAI (Creature *pCreature)
void Reset () override
void DoAction (int32 param) override
void JustEngagedWith (Unit *pWho) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 dataOrGuid) const override
void KilledUnit (Unit *pVictim) override
void JustSummoned (Creature *summon) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Member Functions
void SummonStartingTriggers ()
void SummonLavaWaves ()
void SendLavaWaves (bool start)
void RespawnDragons (bool checkCombat)
bool IsTargetInBounds (Unit const *victim) const
Private Attributes
EventMap extraEvents
std::list< uint32 > volcanoBlows
uint8 dragonsCount
uint8 lastLavaSide
bool usedBerserk
bool below11PctReached
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_sartharionAI()
boss_sartharion::boss_sartharionAI::boss_sartharionAI (Creature * pCreature) inline
                                               : BossAI(pCreature, DATA_SARTHARION),
            dragonsCount(0),
            lastLavaSide(LAVA_RIGHT_SIDE),
            usedBerserk(false),
            below11PctReached(false)
        {
        }
Member Function Documentation
DamageTaken()
void boss_sartharion::boss_sartharionAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
        {
            // Temporal hack, by some case some melee spells can bypass this aura damage reduction
            if (me->HasAura(SPELL_GIFT_OF_TWILIGHT_FIRE))
            {
                damage = 0;
                return;
            }
            if (!usedBerserk && me->HealthBelowPctDamaged(30, damage))
            {
                DoCastSelf(SPELL_SARTHARION_BERSERK, true);
                usedBerserk = true;
                return;
            }
            // Soft enrage
            if (!below11PctReached && me->HealthBelowPctDamaged(10, damage))
            {
                summons.RemoveNotExisting();
                if (!summons.empty())
                {
                    for (ObjectGuid const& summonGuid : summons)
                    {
                        Creature* summon = ObjectAccessor::GetCreature(*me, summonGuid);
                        if (summon && summon->GetEntry() == NPC_FIRE_CYCLONE)
{
                            summon->CastSpell(summon, SPELL_CYCLONE_AURA_PERIODIC, true);
                        }
                    }
                }
                Talk(SAY_SARTHARION_BERSERK);
                below11PctReached = true;
            }
        }
References below11PctReached, Unit::CastSpell(), UnitAI::DoCastSelf(), SummonList::empty(), ObjectAccessor::GetCreature(), Object::GetEntry(), Unit::HasAura(), Unit::HealthBelowPctDamaged(), ScriptedAI::me, NPC_FIRE_CYCLONE, SummonList::RemoveNotExisting(), SAY_SARTHARION_BERSERK, SPELL_CYCLONE_AURA_PERIODIC, SPELL_GIFT_OF_TWILIGHT_FIRE, SPELL_SARTHARION_BERSERK, BossAI::summons, and usedBerserk.
DoAction()
void boss_sartharion::boss_sartharionAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_DRAKE_DIED)
            {
                DoCastSelf(SPELL_SARTHARION_TWILIGHT_REVENGE, true);
            }
        }
References ACTION_DRAKE_DIED, UnitAI::DoCastSelf(), and SPELL_SARTHARION_TWILIGHT_REVENGE.
GetData()
uint32 boss_sartharion::boss_sartharionAI::GetData (uint32 dataOrGuid) const inline override virtual
Reimplemented from UnitAI.
        {
            // it means we want dragons count
            if (dataOrGuid == DATA_ACHIEVEMENT_DRAGONS_COUNT)
            {
                return dragonsCount;
            }
            // otherwise it is guid to check if player was hit by lava strike :)
            if (!volcanoBlows.empty() && std::find(volcanoBlows.begin(), volcanoBlows.end(), dataOrGuid) != volcanoBlows.end())
            {
                return 1;
            }
            return 0;
        }
References DATA_ACHIEVEMENT_DRAGONS_COUNT, dragonsCount, and volcanoBlows.
IsTargetInBounds()
bool boss_sartharion::boss_sartharionAI::IsTargetInBounds (Unit const * victim) const inline private
        {
            if (!victim || victim->GetPositionX() < SartharionBoundary[0] || victim->GetPositionX() > SartharionBoundary[1] || victim->GetPositionY() > SartharionBoundary[3])
            {
                return false;
            }
            // Big island handling
            if (victim->GetPositionY() < SartharionBoundary[2])
            {
                return victim->GetDistance(bigIslandMiddlePos) <= 6.0f;
            }
            return true;
        }
References bigIslandMiddlePos, WorldObject::GetDistance(), Position::GetPositionX(), Position::GetPositionY(), and SartharionBoundary.
Referenced by JustEngagedWith(), and UpdateAI().
JustDied()
void boss_sartharion::boss_sartharionAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            RespawnDragons(true);
            _JustDied();
            Talk(SAY_SARTHARION_DEATH);
        }
References BossAI::_JustDied(), RespawnDragons(), and SAY_SARTHARION_DEATH.
JustEngagedWith()
void boss_sartharion::boss_sartharionAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            if (pWho && !IsTargetInBounds(pWho))
            {
                EnterEvadeMode();
                return;
            }
            _JustEngagedWith();
            DoCastSelf(SPELL_SARTHARION_PYROBUFFET, true);
            Talk(SAY_SARTHARION_AGGRO);
            // Combat events
            events.ScheduleEvent(EVENT_SARTHARION_CAST_CLEAVE, 7s);
            events.ScheduleEvent(EVENT_SARTHARION_CAST_FLAME_BREATH, 15s);
            events.ScheduleEvent(EVENT_SARTHARION_CAST_TAIL_LASH, 11s);
            // Extra events
            extraEvents.ScheduleEvent(EVENT_SARTHARION_SUMMON_LAVA, 20s);
            extraEvents.ScheduleEvent(EVENT_SARTHARION_LAVA_STRIKE, 5s);
            extraEvents.ScheduleEvent(EVENT_SARTHARION_BERSERK, 15min);
            extraEvents.ScheduleEvent(EVENT_SARTHARION_BOUNDARY, 250ms);
            // Store dragons
            for (uint8 i = 0; i < MAX_DRAGONS; ++i)
            {
                Creature* dragon = ObjectAccessor::GetCreature(*me, instance->GetGuidData(dragons[i]));
                if (!dragon || !dragon->IsAlive() || instance->GetBossState(dragons[i]) == DONE)
                {
                    continue;
                }
                dragon->SetImmuneToNPC(true);
                dragon->SetFullHealth();
                ++dragonsCount;
                me->AddLootMode(1 << dragonsCount);
                switch (dragons[i])
                {
                    case DATA_TENEBRON:
                    {
                        dragon->CastSpell(dragon, SPELL_POWER_OF_TENEBRON, true);
                        extraEvents.ScheduleEvent(EVENT_SARTHARION_CALL_TENEBRON, 10s);
                        break;
                    }
                    case DATA_SHADRON:
                    {
                        dragon->CastSpell(dragon, SPELL_POWER_OF_SHADRON, true);
                        extraEvents.ScheduleEvent(EVENT_SARTHARION_CALL_SHADRON, 65s);
                        break;
                    }
                    case DATA_VESPERON:
                    {
                        dragon->CastSpell(dragon, SPELL_POWER_OF_VESPERON, true);
                        extraEvents.ScheduleEvent(EVENT_SARTHARION_CALL_VESPERON, 115s);
                        break;
                    }
                }
            }
            if (dragonsCount)
            {
                DoCastSelf(SPELL_WILL_OF_SARTHARION, true);
            }
            me->CallForHelp(500.0f);
        }
References BossAI::_JustEngagedWith(), Creature::AddLootMode(), Creature::CallForHelp(), Unit::CastSpell(), DATA_SHADRON, DATA_TENEBRON, DATA_VESPERON, UnitAI::DoCastSelf(), DONE, dragons, dragonsCount, BossAI::EnterEvadeMode(), EVENT_SARTHARION_BERSERK, EVENT_SARTHARION_BOUNDARY, EVENT_SARTHARION_CALL_SHADRON, EVENT_SARTHARION_CALL_TENEBRON, EVENT_SARTHARION_CALL_VESPERON, EVENT_SARTHARION_CAST_CLEAVE, EVENT_SARTHARION_CAST_FLAME_BREATH, EVENT_SARTHARION_CAST_TAIL_LASH, EVENT_SARTHARION_LAVA_STRIKE, EVENT_SARTHARION_SUMMON_LAVA, extraEvents, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, Unit::IsAlive(), IsTargetInBounds(), MAX_DRAGONS, ScriptedAI::me, SAY_SARTHARION_AGGRO, EventMap::ScheduleEvent(), Unit::SetFullHealth(), Unit::SetImmuneToNPC(), SPELL_POWER_OF_SHADRON, SPELL_POWER_OF_TENEBRON, SPELL_POWER_OF_VESPERON, SPELL_SARTHARION_PYROBUFFET, and SPELL_WILL_OF_SARTHARION.
JustSummoned()
void boss_sartharion::boss_sartharionAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            switch (summon->GetEntry())
            {
                case NPC_FLAME_TSUNAMI:
                {
                    summon->SetSpeed(MOVE_FLIGHT, 1.5f);
                    break;
                }
                case NPC_FIRE_CYCLONE:
                {
                    summon->GetMotionMaster()->MoveRandom(5.0f);
                    break;
                }
            }
            summons.Summon(summon);
        }
References Object::GetEntry(), Unit::GetMotionMaster(), MOVE_FLIGHT, MotionMaster::MoveRandom(), NPC_FIRE_CYCLONE, NPC_FLAME_TSUNAMI, Unit::SetSpeed(), SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_sartharion::boss_sartharionAI::KilledUnit (Unit * pVictim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!urand(0, 2) && pVictim->IsPlayer())
            {
                Talk(SAY_SARTHARION_SLAY);
            }
        }
References Object::IsPlayer(), SAY_SARTHARION_SLAY, and urand().
Reset()
void boss_sartharion::boss_sartharionAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            _Reset();
            extraEvents.Reset();
            RespawnDragons(false);
            SummonStartingTriggers();
            usedBerserk = false;
            below11PctReached = false;
            dragonsCount = 0;
            volcanoBlows.clear();
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_TWILIGHT_SHIFT);
        }
References BossAI::_Reset(), below11PctReached, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), dragonsCount, extraEvents, BossAI::instance, EventMap::Reset(), RespawnDragons(), SPELL_TWILIGHT_SHIFT, SummonStartingTriggers(), usedBerserk, and volcanoBlows.
RespawnDragons()
void boss_sartharion::boss_sartharionAI::RespawnDragons (bool checkCombat) inline private
        {
            for (uint8 i = 0; i < MAX_DRAGONS; ++i)
            {
                if (instance->GetBossState(dragons[i]) == DONE)
                {
                    continue;
                }
                if (Creature* dragon = ObjectAccessor::GetCreature(*me, instance->GetGuidData(dragons[i])))
                {
                    if (checkCombat && dragon->IsInCombat())
                    {
                        continue;
                    }
                    dragon->DespawnOrUnsummon();
                    dragon->SetRespawnTime(5);
                }
            }
            dragonsCount = 0;
        }
References DONE, dragons, dragonsCount, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, MAX_DRAGONS, and ScriptedAI::me.
Referenced by JustDied(), and Reset().
SendLavaWaves()
void boss_sartharion::boss_sartharionAI::SendLavaWaves (bool start) inline private
        {
            if (summons.empty())
            {
                return;
            }
            for (ObjectGuid const& guid : summons)
            {
                Creature* tsunami = ObjectAccessor::GetCreature(*me, guid);
                if (!tsunami || tsunami->GetEntry() != NPC_FLAME_TSUNAMI)
                {
                    continue;
                }
                if (start)
                {
                    tsunami->GetMotionMaster()->MovePoint(0, ((tsunami->GetPositionX() < 3250.0f) ? 3283.44f : 3208.44f), tsunami->GetPositionY(), tsunami->GetPositionZ());
                }
                else
                {
                    tsunami->SetObjectScale(0.1f);
                }
            }
        }
References SummonList::empty(), ObjectAccessor::GetCreature(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, MotionMaster::MovePoint(), NPC_FLAME_TSUNAMI, Creature::SetObjectScale(), and BossAI::summons.
Referenced by UpdateAI().
SetData()
void boss_sartharion::boss_sartharionAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
        {
            if (type == DATA_VOLCANO_BLOWS && data)
            {
                if (!volcanoBlows.empty() && std::find(volcanoBlows.begin(), volcanoBlows.end(), data) != volcanoBlows.end())
                {
                    return;
                }
                volcanoBlows.push_back(data);
            }
        }
References DATA_VOLCANO_BLOWS, and volcanoBlows.
SummonLavaWaves()
void boss_sartharion::boss_sartharionAI::SummonLavaWaves () inline private
        {
            summons.RemoveNotExisting();
            Talk(WHISPER_LAVA_CHURN);
            extraEvents.ScheduleEvent(EVENT_SARTHARION_START_LAVA, 2s);
            extraEvents.ScheduleEvent(EVENT_SARTHARION_FINISH_LAVA, 9s);
            // Send wave from left
            if (lastLavaSide == LAVA_RIGHT_SIDE)
            {
                for (uint8 i = 0; i < MAX_LEFT_LAVA_TSUNAMIS; ++i)
                {
                    me->SummonCreature(NPC_FLAME_TSUNAMI, 3208.44f, 580.0f - (i * 50.0f), 55.8f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 12000);
                }
                lastLavaSide = LAVA_LEFT_SIDE;
            }
            // from right
            else
            {
                for (uint8 i = 0; i < MAX_RIGHT_LAVA_TSUNAMIS; ++i)
                {
                    me->SummonCreature(NPC_FLAME_TSUNAMI, 3283.44f, 555.0f - (i * 50.0f), 55.8f, 3.14f, TEMPSUMMON_TIMED_DESPAWN, 12000);
                }
                lastLavaSide = LAVA_RIGHT_SIDE;
            }
        }
References EVENT_SARTHARION_FINISH_LAVA, EVENT_SARTHARION_START_LAVA, extraEvents, lastLavaSide, LAVA_LEFT_SIDE, LAVA_RIGHT_SIDE, MAX_LEFT_LAVA_TSUNAMIS, MAX_RIGHT_LAVA_TSUNAMIS, ScriptedAI::me, NPC_FLAME_TSUNAMI, SummonList::RemoveNotExisting(), EventMap::ScheduleEvent(), WorldObject::SummonCreature(), BossAI::summons, TEMPSUMMON_TIMED_DESPAWN, and WHISPER_LAVA_CHURN.
Referenced by UpdateAI().
SummonStartingTriggers()
void boss_sartharion::boss_sartharionAI::SummonStartingTriggers () inline private
        {
            for (uint8 i = 0; i < MAX_CYCLONE_COUNT; ++i)
            {
                me->SummonCreature(NPC_FIRE_CYCLONE, CycloneSummonPos[i]);
            }
            for (uint8 i = 0; i < MAX_AREA_TRIGGER_COUNT; ++i)
            {
                me->SummonCreature(NPC_SAFE_AREA_TRIGGER, AreaTriggerSummonPos[i]);
            }
        }
References AreaTriggerSummonPos, CycloneSummonPos, MAX_AREA_TRIGGER_COUNT, MAX_CYCLONE_COUNT, ScriptedAI::me, NPC_FIRE_CYCLONE, NPC_SAFE_AREA_TRIGGER, and WorldObject::SummonCreature().
Referenced by Reset().
UpdateAI()
void boss_sartharion::boss_sartharionAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            if (!UpdateVictim())
            {
                return;
            }
            extraEvents.Update(diff);
            // Special events which needs to be fired immidiately
            while (uint32 const eventId = extraEvents.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_SARTHARION_BOUNDARY:
                    {
                        if (!IsTargetInBounds(me->GetVictim()))
{
                            EnterEvadeMode();
                        }
                        else
{
                            extraEvents.Repeat(250ms);
                        }
                        break;
                    }
                    case EVENT_SARTHARION_SUMMON_LAVA:
                    {
                        if (!urand(0, 3))
{
                            Talk(SAY_SARTHARION_SPECIAL);
                        }
                        SummonLavaWaves();
                        extraEvents.Repeat(25s);
                        return;
                    }
                    case EVENT_SARTHARION_START_LAVA:
                    {
                        SendLavaWaves(true);
                        return;
                    }
                    case EVENT_SARTHARION_FINISH_LAVA:
                    {
                        SendLavaWaves(false);
                        return;
                    }
                    // Handling of Drakes Events
                    // Dragon Calls
                    case EVENT_SARTHARION_CALL_TENEBRON:
                    {
                        Talk(SAY_SARTHARION_CALL_TENEBRON);
                        if (Creature* tenebron = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_TENEBRON)))
{
                            tenebron->AI()->DoAction(ACTION_CALL_DRAGON);
                        }
                        break;
                    }
                    case EVENT_SARTHARION_CALL_SHADRON:
                    {
                        Talk(SAY_SARTHARION_CALL_SHADRON);
                        if (Creature* shadron = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SHADRON)))
{
                            shadron->AI()->DoAction(ACTION_CALL_DRAGON);
                        }
                        break;
                    }
                    case EVENT_SARTHARION_CALL_VESPERON:
                    {
                        Talk(SAY_SARTHARION_CALL_VESPERON);
                        if (Creature* vesperon = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_VESPERON)))
{
                            vesperon->AI()->DoAction(ACTION_CALL_DRAGON);
                        }
                        break;
                    }
                }
            }
            // Handle Sartharion combat abbilities
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
            {
                return;
            }
            while (uint32 const eventId = events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_SARTHARION_CAST_CLEAVE:
                    {
                        DoCastVictim(SPELL_SARTHARION_CLEAVE, false);
                        events.Repeat(10s);
                        break;
                    }
                    case EVENT_SARTHARION_CAST_FLAME_BREATH:
                    {
                        DoCastVictim(SPELL_SARTHARION_FLAME_BREATH, false);
                        events.Repeat(20s);
                        break;
                    }
                    case EVENT_SARTHARION_CAST_TAIL_LASH:
                    {
                        DoCastSelf(SPELL_SARTHARION_TAIL_LASH, false);
                        events.Repeat(18s);
                        break;
                    }
                    case EVENT_SARTHARION_LAVA_STRIKE:
                    {
                        if (!urand(0, 2))
{
                            Talk(SAY_SARTHARION_SPECIAL_4);
                        }
                        summons.RemoveNotExisting();
                        uint8 rand = urand(0, MAX_CYCLONE_COUNT - 1); // 5 - numer of cyclones
                        uint8 iter = 0;
                        if (!summons.empty())
{
                            for (ObjectGuid const& summonGuid : summons)
{
                                Creature* summon = ObjectAccessor::GetCreature(*me, summonGuid);
                                if (summon && summon->GetEntry() == NPC_FIRE_CYCLONE && iter == rand)
{
                                    summon->CastSpell(summon, SPELL_CYCLONE_AURA_PERIODIC, true);
                                    ++iter;
                                }
                            }
                        }
                        events.RepeatEvent((below11PctReached ? urand(1400, 2000) : urand(5000, 20000)));
                        break;
                    }
                    case EVENT_SARTHARION_BERSERK:
                    {
                        summons.DespawnEntry(NPC_SAFE_AREA_TRIGGER);
                        break;
                    }
                }
                if (me->HasUnitState(UNIT_STATE_CASTING))
                {
                    return;
                }
            }
            DoMeleeAttackIfReady();
        }
References ACTION_CALL_DRAGON, below11PctReached, Unit::CastSpell(), DATA_SHADRON, DATA_TENEBRON, DATA_VESPERON, SummonList::DespawnEntry(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), SummonList::empty(), BossAI::EnterEvadeMode(), EVENT_SARTHARION_BERSERK, EVENT_SARTHARION_BOUNDARY, EVENT_SARTHARION_CALL_SHADRON, EVENT_SARTHARION_CALL_TENEBRON, EVENT_SARTHARION_CALL_VESPERON, EVENT_SARTHARION_CAST_CLEAVE, EVENT_SARTHARION_CAST_FLAME_BREATH, EVENT_SARTHARION_CAST_TAIL_LASH, EVENT_SARTHARION_FINISH_LAVA, EVENT_SARTHARION_LAVA_STRIKE, EVENT_SARTHARION_START_LAVA, EVENT_SARTHARION_SUMMON_LAVA, EventMap::ExecuteEvent(), extraEvents, ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), Unit::GetVictim(), Unit::HasUnitState(), BossAI::instance, IsTargetInBounds(), MAX_CYCLONE_COUNT, ScriptedAI::me, NPC_FIRE_CYCLONE, NPC_SAFE_AREA_TRIGGER, SummonList::RemoveNotExisting(), EventMap::Repeat(), SAY_SARTHARION_CALL_SHADRON, SAY_SARTHARION_CALL_TENEBRON, SAY_SARTHARION_CALL_VESPERON, SAY_SARTHARION_SPECIAL, SAY_SARTHARION_SPECIAL_4, SendLavaWaves(), SPELL_CYCLONE_AURA_PERIODIC, SPELL_SARTHARION_CLEAVE, SPELL_SARTHARION_FLAME_BREATH, SPELL_SARTHARION_TAIL_LASH, SummonLavaWaves(), BossAI::summons, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
below11PctReached
bool boss_sartharion::boss_sartharionAI::below11PctReached private
Referenced by DamageTaken(), Reset(), and UpdateAI().
dragonsCount
uint8 boss_sartharion::boss_sartharionAI::dragonsCount private
Referenced by GetData(), JustEngagedWith(), Reset(), and RespawnDragons().
extraEvents
EventMap boss_sartharion::boss_sartharionAI::extraEvents private
Referenced by JustEngagedWith(), Reset(), SummonLavaWaves(), and UpdateAI().
lastLavaSide
uint8 boss_sartharion::boss_sartharionAI::lastLavaSide private
Referenced by SummonLavaWaves().
usedBerserk
bool boss_sartharion::boss_sartharionAI::usedBerserk private
Referenced by DamageTaken(), and Reset().
volcanoBlows
std::list<uint32> boss_sartharion::boss_sartharionAI::volcanoBlows private
Referenced by GetData(), Reset(), and SetData().