AzerothCore: boss_twilight_halion::boss_twilight_halionAI Struct Reference
boss_twilight_halion::boss_twilight_halionAI Struct Reference
Public Member Functions
boss_twilight_halionAI (Creature *creature)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason) override
void KilledUnit (Unit *victim) override
void JustDied (Unit *killer) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
InstanceScript * _instance
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_twilight_halionAI()
boss_twilight_halion::boss_twilight_halionAI::boss_twilight_halionAI (Creature * creature) inline
                                                   : ScriptedAI(creature), _instance(creature->GetInstanceScript())
        {
            Creature* halion = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION));
            if (!halion)
                return;
            halion->AddAura(SPELL_COPY_DAMAGE, me);
            me->AddAura(SPELL_COPY_DAMAGE, halion);
            me->AddAura(SPELL_DUSK_SHROUD, me);
            me->SetHealth(halion->GetHealth());
            me->setActive(true);
        }
References _instance, Unit::AddAura(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetHealth(), ScriptedAI::me, NPC_HALION, WorldObject::setActive(), Unit::SetHealth(), SPELL_COPY_DAMAGE, and SPELL_DUSK_SHROUD.
Member Function Documentation
DamageTaken()
void boss_twilight_halion::boss_twilight_halionAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (!attacker || !me->InSamePhase(attacker))
                return;
            if (Creature* controller = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION_CONTROLLER)))
                controller->AI()->SetData(DATA_TWILIGHT_DAMAGE_TAKEN, damage);
        }
References _instance, DATA_TWILIGHT_DAMAGE_TAKEN, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::InSamePhase(), ScriptedAI::me, and NPC_HALION_CONTROLLER.
EnterEvadeMode()
void boss_twilight_halion::boss_twilight_halionAI::EnterEvadeMode (EvadeReason) inline override virtual
Reimplemented from CreatureAI.
        {
        }
JustDied()
void boss_twilight_halion::boss_twilight_halionAI::JustDied (Unit * killer) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (Creature* halion = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION)))
            {
                // Ensure looting
                if (me->IsDamageEnoughForLootingAndReward())
                    halion->LowerPlayerDamageReq(halion->GetMaxHealth());
                if (killer && halion->IsAlive())
                    Unit::Kill(killer, halion);
            }
            if (Creature* controller = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION_CONTROLLER)))
                if (controller->IsAlive())
                    Unit::Kill(controller, controller);
            _instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
            me->CastSpell(me, SPELL_CLEAR_DEBUFFS, false);
        }
References _instance, Unit::CastSpell(), ENCOUNTER_FRAME_DISENGAGE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::IsAlive(), Creature::IsDamageEnoughForLootingAndReward(), Unit::Kill(), ScriptedAI::me, NPC_HALION, NPC_HALION_CONTROLLER, InstanceScript::SendEncounterUnit(), and SPELL_CLEAR_DEBUFFS.
JustEngagedWith()
void boss_twilight_halion::boss_twilight_halionAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            _events.Reset();
            _events.ScheduleEvent(EVENT_CLEAVE, 8s, 10s);
            _events.ScheduleEvent(EVENT_TAIL_LASH, 10s);
            _events.ScheduleEvent(EVENT_BREATH, 10s, 15s);
            _events.ScheduleEvent(EVENT_SOUL_CONSUMPTION, 20s);
            _events.ScheduleEvent(EVENT_SHADOW_PULSARS, 16s);
            _events.ScheduleEvent(EVENT_SEND_ENCOUNTER_UNIT, 2s);
            _events.ScheduleEvent(EVENT_CHECK_HEALTH, 1s);
            me->SetInCombatWithZone();
        }
References _events, EVENT_BREATH, EVENT_CHECK_HEALTH, EVENT_CLEAVE, EVENT_SEND_ENCOUNTER_UNIT, EVENT_SHADOW_PULSARS, EVENT_SOUL_CONSUMPTION, EVENT_TAIL_LASH, ScriptedAI::me, EventMap::Reset(), EventMap::ScheduleEvent(), and Creature::SetInCombatWithZone().
KilledUnit()
void boss_twilight_halion::boss_twilight_halionAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->IsPlayer() && _events.GetNextEventTime(EVENT_KILL_TALK) == 0)
            {
                Talk(SAY_KILL);
                _events.ScheduleEvent(EVENT_KILL_TALK, 6s);
            }
        }
References _events, EVENT_KILL_TALK, EventMap::GetNextEventTime(), Object::IsPlayer(), SAY_KILL, and EventMap::ScheduleEvent().
Reset()
void boss_twilight_halion::boss_twilight_halionAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _events.Reset();
            me->SetPhaseMask(0x21, true);
            me->SetInCombatWithZone();
            me->SetPhaseMask(0x20, true);
            me->SetReactState(REACT_DEFENSIVE);
        }
References _events, ScriptedAI::me, REACT_DEFENSIVE, EventMap::Reset(), Creature::SetInCombatWithZone(), Unit::SetPhaseMask(), and Creature::SetReactState().
UpdateAI()
void boss_twilight_halion::boss_twilight_halionAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            _events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (_events.ExecuteEvent())
            {
                case EVENT_SEND_ENCOUNTER_UNIT:
                    _instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, me, 2);
                    break;
                case EVENT_CLEAVE:
                    me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                    _events.ScheduleEvent(EVENT_CLEAVE, 8s, 10s);
                    break;
                case EVENT_TAIL_LASH:
                    me->CastSpell(me, SPELL_TAIL_LASH, false);
                    _events.ScheduleEvent(EVENT_TAIL_LASH, 10s);
                    break;
                case EVENT_BREATH:
                    me->CastSpell(me->GetVictim(), SPELL_DARK_BREATH, false);
                    _events.ScheduleEvent(EVENT_BREATH, 10s, 12s);
                    break;
                case EVENT_SOUL_CONSUMPTION:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 1, 100.0f, true, true, SPELL_TWILIGHT_REALM))
                        me->CastSpell(target, SPELL_SOUL_CONSUMPTION, false);
                    _events.ScheduleEvent(EVENT_SOUL_CONSUMPTION, 20s);
                    break;
                case EVENT_CHECK_HEALTH:
                    if (me->HealthBelowPct(50))
                    {
                        me->CastStop();
                        me->CastSpell(me, SPELL_TWILIGHT_DIVISION, false);
                        Talk(SAY_PHASE_THREE);
                        return;
                    }
                    _events.ScheduleEvent(EVENT_CHECK_HEALTH, 1s);
                    break;
                case EVENT_SHADOW_PULSARS:
                    Talk(SAY_SPHERE_PULSE);
                    Talk(EMOTE_WARN_LASER);
                    _events.ScheduleEvent(EVENT_SHADOW_PULSARS, 29s);
                    _events.ScheduleEvent(EVENT_SHADOW_PULSARS_SHOOT, 5s);
                    break;
                case EVENT_SHADOW_PULSARS_SHOOT:
                    if (Creature* orbCarrier = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_ORB_CARRIER)))
                        orbCarrier->AI()->DoAction(ACTION_SHOOT);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References _events, _instance, ACTION_SHOOT, Unit::CastSpell(), Unit::CastStop(), UnitAI::DoMeleeAttackIfReady(), EMOTE_WARN_LASER, ENCOUNTER_FRAME_ENGAGE, EVENT_BREATH, EVENT_CHECK_HEALTH, EVENT_CLEAVE, EVENT_SEND_ENCOUNTER_UNIT, EVENT_SHADOW_PULSARS, EVENT_SHADOW_PULSARS_SHOOT, EVENT_SOUL_CONSUMPTION, EVENT_TAIL_LASH, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetVictim(), Unit::HasUnitState(), Unit::HealthBelowPct(), ScriptedAI::me, NPC_ORB_CARRIER, SAY_PHASE_THREE, SAY_SPHERE_PULSE, EventMap::ScheduleEvent(), UnitAI::SelectTarget(), InstanceScript::SendEncounterUnit(), SPELL_CLEAVE, SPELL_DARK_BREATH, SPELL_SOUL_CONSUMPTION, SPELL_TAIL_LASH, SPELL_TWILIGHT_DIVISION, SPELL_TWILIGHT_REALM, UNIT_STATE_CASTING, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_events
EventMap boss_twilight_halion::boss_twilight_halionAI::_events private
Referenced by JustEngagedWith(), KilledUnit(), Reset(), and UpdateAI().
_instance
InstanceScript* boss_twilight_halion::boss_twilight_halionAI::_instance private
Referenced by boss_twilight_halionAI(), DamageTaken(), JustDied(), and UpdateAI().