AzerothCore: ObjectGridLoader Class Reference
ObjectGridLoader Class Reference
#include "ObjectGridLoader.h"
Public Member Functions
ObjectGridLoader (NGridType &grid, Map *map, const Cell &cell)
void Visit (GameObjectMapType &m)
void Visit (CreatureMapType &m)
void Visit (CorpseMapType &) const
void Visit (DynamicObjectMapType &) const
void LoadN (void)
template<>
void SetObjectCell (Creature *obj, CellCoord const &cellCoord)
template<>
void SetObjectCell (GameObject *obj, CellCoord const &cellCoord)
Static Public Member Functions
template<class T >
static void SetObjectCell (T *obj, CellCoord const &cellCoord)
Private Attributes
Cell i_cell
NGridType & i_grid
Map * i_map
uint32 i_gameObjects
uint32 i_creatures
uint32 i_corpses
Friends
class ObjectWorldLoader
Detailed Description
Constructor & Destructor Documentation
ObjectGridLoader()
ObjectGridLoader::ObjectGridLoader (NGridType & grid, Map * map, const Cell & cell) inline
        : i_cell(cell), i_grid(grid), i_map(map), i_gameObjects(0), i_creatures(0), i_corpses (0)
    {}
Member Function Documentation
LoadN()
void ObjectGridLoader::LoadN (void)
{
    i_gameObjects = 0;
    i_creatures = 0;
    i_corpses = 0;
    i_cell.data.Part.cell_y = 0;
    for (uint32 x = 0; x < MAX_NUMBER_OF_CELLS; ++x)
    {
        i_cell.data.Part.cell_x = x;
        for (uint32 y = 0; y < MAX_NUMBER_OF_CELLS; ++y)
        {
            i_cell.data.Part.cell_y = y;
            //Load creatures and game objects
            {
                TypeContainerVisitor<ObjectGridLoader, GridTypeMapContainer> visitor(*this);
                i_grid.VisitGrid(x, y, visitor);
            }
            //Load corpses (not bones)
            {
                ObjectWorldLoader worker(*this);
                TypeContainerVisitor<ObjectWorldLoader, WorldTypeMapContainer> visitor(worker);
                i_grid.VisitGrid(x, y, visitor);
            }
        }
    }
    LOG_DEBUG("maps", "{} GameObjects, {} Creatures, and {} Corpses/Bones loaded for grid {} on map {}", i_gameObjects, i_creatures, i_corpses, i_grid.GetGridId(), i_map->GetId());
}
References Cell::cell_x, Cell::cell_y, Cell::data, NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::GetGridId(), Map::GetId(), i_cell, i_corpses, i_creatures, i_gameObjects, i_grid, i_map, LOG_DEBUG, MAX_NUMBER_OF_CELLS, Cell::Part, and NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::VisitGrid().
Referenced by Map::EnsureGridLoaded().
SetObjectCell() [1/3]
template<> void ObjectGridLoader::SetObjectCell (Creature * obj, CellCoord const & cellCoord)
{
    Cell cell(cellCoord);
    obj->SetCurrentCell(cell);
}
References MovableMapObject::SetCurrentCell().
SetObjectCell() [2/3]
template<> void ObjectGridLoader::SetObjectCell (GameObject * obj, CellCoord const & cellCoord)
{
    Cell cell(cellCoord);
    obj->SetCurrentCell(cell);
}
References MovableMapObject::SetCurrentCell().
SetObjectCell() [3/3]
template<class T > void ObjectGridLoader::SetObjectCell (T * obj, CellCoord const & cellCoord) static
{
}
Referenced by AddObjectHelper().
Visit() [1/4]
void ObjectGridLoader::Visit (CorpseMapType &) const inline
{}
Visit() [2/4]
void ObjectGridLoader::Visit (CreatureMapType & m)
{
    CellCoord cellCoord = i_cell.GetCellCoord();
    CellObjectGuids const& cell_guids = sObjectMgr->GetCellObjectGuids(i_map->GetId(), i_map->GetSpawnMode(), cellCoord.GetId());
    LoadHelper(cell_guids.creatures, cellCoord, m, i_creatures, i_map);
}
References CellObjectGuids::creatures, Cell::GetCellCoord(), CoordPair< LIMIT >::GetId(), Map::GetId(), Map::GetSpawnMode(), i_cell, i_creatures, i_map, LoadHelper(), and sObjectMgr.
Visit() [3/4]
void ObjectGridLoader::Visit (DynamicObjectMapType &) const inline
{}
Visit() [4/4]
void ObjectGridLoader::Visit (GameObjectMapType & m)
{
    CellCoord cellCoord = i_cell.GetCellCoord();
    CellObjectGuids const& cell_guids = sObjectMgr->GetCellObjectGuids(i_map->GetId(), i_map->GetSpawnMode(), cellCoord.GetId());
    LoadHelper(cell_guids.gameobjects, cellCoord, m, i_gameObjects, i_map);
}
References CellObjectGuids::gameobjects, Cell::GetCellCoord(), CoordPair< LIMIT >::GetId(), Map::GetId(), Map::GetSpawnMode(), i_cell, i_gameObjects, i_map, LoadHelper(), and sObjectMgr.
Friends And Related Function Documentation
ObjectWorldLoader
friend class ObjectWorldLoader friend
Member Data Documentation
i_cell
Cell ObjectGridLoader::i_cell private
Referenced by LoadN(), and Visit().
i_corpses
uint32 ObjectGridLoader::i_corpses private
Referenced by LoadN().
i_creatures
uint32 ObjectGridLoader::i_creatures private
Referenced by LoadN(), and Visit().
i_gameObjects
uint32 ObjectGridLoader::i_gameObjects private
Referenced by LoadN(), and Visit().
i_grid
NGridType& ObjectGridLoader::i_grid private
Referenced by LoadN().
i_map
Map* ObjectGridLoader::i_map private
Referenced by LoadN(), and Visit().