AzerothCore: Vehicle Class Reference
Vehicle Class Reference
#include "Vehicle.h"
Public Member Functions
void Install ()
void Uninstall ()
void Reset (bool evading=false)
void InstallAllAccessories (bool evading)
void ApplyAllImmunities ()
void InstallAccessory (uint32 entry, int8 seatId, bool minion, uint8 type, uint32 summonTime)
Unit * GetBase () const
May be called from scripts.
VehicleEntry const * GetVehicleInfo () const
uint32 GetCreatureEntry () const
bool HasEmptySeat (int8 seatId) const
Unit * GetPassenger (int8 seatId) const
int8 GetNextEmptySeat (int8 seatId, bool next) const
VehicleSeatAddon const * GetSeatAddonForSeatOfPassenger (Unit const *passenger) const
uint8 GetAvailableSeatCount () const
bool AddPassenger (Unit *passenger, int8 seatId=-1)
void EjectPassenger (Unit *passenger, Unit *controller)
void RemovePassenger (Unit *passenger)
void RelocatePassengers ()
void RemoveAllPassengers ()
void Dismiss ()
bool IsVehicleInUse ()
void TeleportVehicle (float x, float y, float z, float ang)
VehicleSeatEntry const * GetSeatForPassenger (Unit const *passenger)
SeatMap::iterator GetSeatIteratorForPassenger (Unit *passenger)
virtual void CalculatePassengerPosition (float &x, float &y, float &z, float *o=nullptr) const =0
This method transforms supplied transport offsets into global coordinates.
virtual void CalculatePassengerOffset (float &x, float &y, float &z, float *o=nullptr) const =0
This method transforms supplied global coordinates into local offsets.
Public Attributes
SeatMap Seats
Protected Member Functions
Vehicle (Unit *unit, VehicleEntry const *vehInfo, uint32 creatureEntry)
~Vehicle () override
Protected Member Functions inherited from TransportBase
TransportBase ()=default
virtual ~TransportBase ()=default
Private Types
enum Status {
STATUS_NONE ,
STATUS_INSTALLED ,
STATUS_UNINSTALLING
}
Private Member Functions
void InitMovementInfoForBase ()
void CalculatePassengerPosition (float &x, float &y, float &z, float *o) const override
This method transforms supplied transport offsets into global coordinates.
void CalculatePassengerOffset (float &x, float &y, float &z, float *o) const override
This method transforms supplied global coordinates into local offsets.
Private Attributes
Unit * _me
VehicleEntry const * _vehicleInfo
uint32 _usableSeatNum
uint32 _creatureEntry
Status _status
Friends
bool Unit::CreateVehicleKit (uint32 id, uint32 creatureEntry)
void Unit::RemoveVehicleKit ()
Additional Inherited Members
Static Protected Member Functions inherited from TransportBase
static void CalculatePassengerPosition (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
static void CalculatePassengerOffset (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
Detailed Description
Member Enumeration Documentation
Status
enum Vehicle::Status private
Enumerator
STATUS_NONE
STATUS_INSTALLED
STATUS_UNINSTALLING
    {
        STATUS_NONE,
        STATUS_INSTALLED,
        STATUS_UNINSTALLING,
    };
Constructor & Destructor Documentation
Vehicle()
Vehicle::Vehicle (Unit * unit, VehicleEntry const * vehInfo, uint32 creatureEntry) protected
                                                                              :
    _me(unit), _vehicleInfo(vehInfo), _usableSeatNum(0), _creatureEntry(creatureEntry), _status(STATUS_NONE)
{
    for (uint32 i = 0; i < MAX_VEHICLE_SEATS; ++i)
    {
        if (uint32 seatId = _vehicleInfo->m_seatID[i])
            if (VehicleSeatEntry const* veSeat = sVehicleSeatStore.LookupEntry(seatId))
            {
                VehicleSeatAddon const* addon = sObjectMgr->GetVehicleSeatAddon(seatId);
                Seats.insert(std::make_pair(i, VehicleSeat(veSeat, addon)));
                if (veSeat->CanEnterOrExit())
                    ++_usableSeatNum;
            }
    }
    // Set or remove correct flags based on available seats. Will overwrite db data (if wrong).
    if (_usableSeatNum)
        _me->SetNpcFlag((_me->IsPlayer() ? UNIT_NPC_FLAG_PLAYER_VEHICLE : UNIT_NPC_FLAG_SPELLCLICK));
    else
        _me->RemoveNpcFlag((_me->IsPlayer() ? UNIT_NPC_FLAG_PLAYER_VEHICLE : UNIT_NPC_FLAG_SPELLCLICK));
    InitMovementInfoForBase();
}
References _me, _usableSeatNum, _vehicleInfo, InitMovementInfoForBase(), Object::IsPlayer(), VehicleEntry::m_seatID, MAX_VEHICLE_SEATS, Unit::RemoveNpcFlag(), Unit::SetNpcFlag(), sObjectMgr, sVehicleSeatStore, UNIT_NPC_FLAG_PLAYER_VEHICLE, and UNIT_NPC_FLAG_SPELLCLICK.
~Vehicle()
Vehicle::~Vehicle () override protected
@Uninstall must be called before this.
{
    ASSERT(_status == STATUS_UNINSTALLING);
    for (SeatMap::const_iterator itr = Seats.begin(); itr != Seats.end(); ++itr)
        if (itr->second.Passenger.Guid)
        {
            if (Unit* unit = ObjectAccessor::GetUnit(*_me, itr->second.Passenger.Guid))
            {
                LOG_FATAL("vehicles", "Vehicle(), unit: {}, entry: {}, typeid: {}, this_entry: {}, this_typeid: {}!", unit->GetName(), unit->GetEntry(), unit->GetTypeId(), _me ? _me->GetEntry() : 0, _me ? _me->GetTypeId() : 0);
                unit->_ExitVehicle();
            }
            else
                LOG_FATAL("vehicles", "Vehicle(), unknown guid!");
        }
}
References _me, _status, ASSERT, Object::GetEntry(), Object::GetTypeId(), ObjectAccessor::GetUnit(), LOG_FATAL, and STATUS_UNINSTALLING.
Member Function Documentation
AddPassenger()
bool Vehicle::AddPassenger (Unit * passenger, int8 seatId = -1)
@Prevent adding passengers when vehicle is uninstalling. (Bad script in OnUninstall/OnRemovePassenger/PassengerBoarded hook.)
{
    if (_status == STATUS_UNINSTALLING)
    {
        LOG_DEBUG("vehicles", "Passenger {}, attempting to board vehicle {} during uninstall! SeatId: {}",
            unit->GetGUID().ToString(), _me->GetGUID().ToString(), (int32)seatId);
        return false;
    }
    if (unit->GetVehicle() != this)
        return false;
    SeatMap::iterator seat;
    if (seatId < 0) // no specific seat requirement
    {
        for (seat = Seats.begin(); seat != Seats.end(); ++seat)
            if (seat->second.IsEmpty() && (seat->second.SeatInfo->CanEnterOrExit() || seat->second.SeatInfo->IsUsableByOverride()))
                break;
        if (seat == Seats.end()) // no available seat
            return false;
    }
    else
    {
        seat = Seats.find(seatId);
        if (seat == Seats.end())
            return false;
        if (!seat->second.IsEmpty())
        {
            if (Unit* passenger = ObjectAccessor::GetUnit(*GetBase(), seat->second.Passenger.Guid))
                passenger->ExitVehicle();
            seat->second.Passenger.Guid.Clear();
        }
        ASSERT(seat->second.IsEmpty());
    }
    if (!seat->second.SeatInfo)
        return false;
    LOG_DEBUG("vehicles", "Unit {} enter vehicle entry {} id {} ({}) seat {}",
        unit->GetName(), _me->GetEntry(), _vehicleInfo->m_ID, _me->GetGUID().ToString(), (int32)seat->first);
    seat->second.Passenger.Guid = unit->GetGUID();
    seat->second.Passenger.IsUnselectable = unit->HasUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
    if (seat->second.SeatInfo->CanEnterOrExit())
    {
        ASSERT(_usableSeatNum);
        --_usableSeatNum;
        if (!_usableSeatNum)
            _me->RemoveNpcFlag(_me->IsPlayer() ? UNIT_NPC_FLAG_PLAYER_VEHICLE : UNIT_NPC_FLAG_SPELLCLICK);
        else
            _me->SetNpcFlag(_me->IsPlayer() ?  UNIT_NPC_FLAG_PLAYER_VEHICLE : UNIT_NPC_FLAG_SPELLCLICK);
    }
    if (!_me || !_me->IsInWorld() || _me->IsDuringRemoveFromWorld())
        return false;
    // Xinef: moved from unit.cpp, if aura passes seatId == -1 (choose automaticly) we wont get appropriate flags
    if (unit->IsPlayer() && !(seat->second.SeatInfo->m_flagsB & VEHICLE_SEAT_FLAG_B_KEEP_PET))
        unit->ToPlayer()->UnsummonPetTemporaryIfAny();
    if (seat->second.SeatInfo->m_flags & VEHICLE_SEAT_FLAG_PASSENGER_NOT_SELECTABLE)
        unit->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
    unit->AddUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT);
    VehicleSeatEntry const* veSeat = seat->second.SeatInfo;
    VehicleSeatAddon const* veSeatAddon = seat->second.SeatAddon;
    float o = veSeatAddon ? veSeatAddon->SeatOrientationOffset : 0.f;
    float x = veSeat->m_attachmentOffsetX;
    float y = veSeat->m_attachmentOffsetY;
    float z = veSeat->m_attachmentOffsetZ;
    unit->m_movementInfo.transport.pos.Relocate(x, y, z, o);
    unit->m_movementInfo.transport.time = 0;
    unit->m_movementInfo.transport.seat = seat->first;
    unit->m_movementInfo.transport.guid = _me->GetGUID();
    // xinef: removed seat->first == 0 check...
    if (_me->IsCreature()
            && unit->IsPlayer()
            && seat->second.SeatInfo->m_flags & VEHICLE_SEAT_FLAG_CAN_CONTROL)
    {
        // Removed try catch + ABORT() here, and make it as simple condition check.
        if (!_me->SetCharmedBy(unit, CHARM_TYPE_VEHICLE))
        {
            // I assume SetCharmedBy should always be true.
            // If not, let's log some debug info.
            LOG_INFO("vehicles", "Crash recovered in Unit::SetCharmedBy(). not null: {}", _me ? 1 : 0);
            if (!_me)
                return false;
            LOG_INFO("vehicles", "Crash recovered in Unit::SetCharmedBy(). Is: {}!", _me->IsInWorld());
            LOG_INFO("vehicles", "Crash recovered in Unit::SetCharmedBy(). Is2: {}!", _me->IsDuringRemoveFromWorld());
            LOG_INFO("vehicles", "Crash recovered in Unit::SetCharmedBy(). Unit {}!", _me->GetName());
            LOG_INFO("vehicles", "Crash recovered in Unit::SetCharmedBy(). typeid: {}!", _me->GetTypeId());
            LOG_INFO("vehicles", "Crash recovered in Unit::SetCharmedBy(). Unit {}, typeid: {}, in world: {}, duringremove: {} has wrong CharmType! Charmer {}, typeid: {}, in world: {}, duringremove: {}.", _me->GetName(), _me->GetTypeId(), _me->IsInWorld(), _me->IsDuringRemoveFromWorld(), unit->GetName(), unit->GetTypeId(), unit->IsInWorld(), unit->IsDuringRemoveFromWorld());
            return false;
        }
    }
    if (_me->IsInWorld())
    {
        unit->SendClearTarget();                                // SMSG_BREAK_TARGET
        unit->SetControlled(true, UNIT_STATE_ROOT);              // SMSG_FORCE_ROOT - In some cases we send SMSG_SPLINE_MOVE_ROOT here (for creatures)
        // also adds MOVEMENTFLAG_ROOT
        Movement::MoveSplineInit init(unit);
        init.DisableTransportPathTransformations();
        init.MoveTo(x, y, z, false, true);
        // Xinef: did not found anything unique in dbc, maybe missed something
        if (veSeat->m_ID == 3566 || veSeat->m_ID == 3567 || veSeat->m_ID == 3568 || veSeat->m_ID == 3570)
        {
            CalculatePassengerPosition(x, y, z, &o);
            init.SetFacing(_me->GetAngle(x, y));
        }
        else
        {
            init.SetFacing(o);
        }
        init.SetTransportEnter();
        init.Launch();
        if (_me->IsCreature())
        {
            if (_me->ToCreature()->IsAIEnabled)
                _me->ToCreature()->AI()->PassengerBoarded(unit, seat->first, true);
        }
    }
    if (GetBase()->IsCreature())
        sScriptMgr->OnAddPassenger(this, unit, seatId);
    // Remove parachute on vehicle switch
    unit->RemoveAurasDueToSpell(VEHICLE_SPELL_PARACHUTE);
    return true;
}
References _me, _status, _usableSeatNum, _vehicleInfo, Unit::AddUnitMovementFlag(), Creature::AI(), ASSERT, CalculatePassengerPosition(), CHARM_TYPE_VEHICLE, Movement::MoveSplineInit::DisableTransportPathTransformations(), Position::GetAngle(), GetBase(), Object::GetEntry(), Object::GetGUID(), WorldObject::GetName(), Object::GetTypeId(), ObjectAccessor::GetUnit(), Unit::GetVehicle(), MovementInfo::TransportInfo::guid, Unit::HasUnitFlag(), Unit::IsAIEnabled, Object::IsCreature(), Unit::IsDuringRemoveFromWorld(), Object::IsInWorld(), Object::IsPlayer(), Movement::MoveSplineInit::Launch(), LOG_DEBUG, LOG_INFO, VehicleSeatEntry::m_attachmentOffsetX, VehicleSeatEntry::m_attachmentOffsetY, VehicleSeatEntry::m_attachmentOffsetZ, VehicleEntry::m_ID, VehicleSeatEntry::m_ID, WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, Movement::MoveSplineInit::MoveTo(), CreatureAI::PassengerBoarded(), MovementInfo::TransportInfo::pos, Position::Relocate(), Unit::RemoveAurasDueToSpell(), Unit::RemoveNpcFlag(), MovementInfo::TransportInfo::seat, VehicleSeatAddon::SeatOrientationOffset, Unit::SendClearTarget(), Unit::SetCharmedBy(), Unit::SetControlled(), Movement::MoveSplineInit::SetFacing(), Unit::SetNpcFlag(), Movement::MoveSplineInit::SetTransportEnter(), Unit::SetUnitFlag(), sScriptMgr, STATUS_UNINSTALLING, MovementInfo::TransportInfo::time, Object::ToCreature(), Object::ToPlayer(), ObjectGuid::ToString(), MovementInfo::transport, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_FLAG_PLAYER_VEHICLE, UNIT_NPC_FLAG_SPELLCLICK, UNIT_STATE_ROOT, Player::UnsummonPetTemporaryIfAny(), VEHICLE_SEAT_FLAG_B_KEEP_PET, VEHICLE_SEAT_FLAG_CAN_CONTROL, VEHICLE_SEAT_FLAG_PASSENGER_NOT_SELECTABLE, and VEHICLE_SPELL_PARACHUTE.
Referenced by Unit::_EnterVehicle(), and Unit::ChangeSeat().
ApplyAllImmunities()
void Vehicle::ApplyAllImmunities ()
{
    // This couldn't be done in DB, because some spells have MECHANIC_NONE
    // Vehicles should be immune on Knockback ...
    //_me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK, true);
    //_me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK_DEST, true);
    // Mechanical units & vehicles ( which are not Bosses, they have own immunities in DB ) should be also immune on healing ( exceptions in switch below )
    if (_me->ToCreature() && _me->ToCreature()->GetCreatureTemplate()->type == CREATURE_TYPE_MECHANICAL && !_me->ToCreature()->isWorldBoss())
    {
        // Heal & dispel ...
        _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL, true);
        _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL_PCT, true);
        _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL_MAX_HEALTH, true); // Xinef
        _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_DISPEL, true);
        _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_PERIODIC_HEAL, true);
        // ... Shield & Immunity grant spells ...
        _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_SCHOOL_IMMUNITY, true);
        //_me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_UNATTACKABLE, true);
        _me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_SHIELD, true);
        _me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_IMMUNE_SHIELD, true);
        if (_me->GetZoneId() == BATTLEFIELD_WG_ZONEID || _me->ToCreature()->GetSpawnId() || (_me->FindMap() && _me->FindMap()->Instanceable()))
            _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_SCHOOL_ABSORB, true);
        // ... Resistance, Split damage, Change stats ...
        _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_DAMAGE_SHIELD, true);
        _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_SPLIT_DAMAGE_PCT, true);
        _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_RESISTANCE, true);
        _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_STAT, true);
        // Taunt
        _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_TAUNT, true);
        _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_ATTACK_ME, true);
    }
    // Different immunities for vehicles goes below
    switch (GetVehicleInfo()->m_ID)
    {
        case 160: //Isle of conquest turret
        case 244: //Wintergrasp turret
        case 510: // Isle of Conquest
        case 452: // Isle of Conquest
        case 543: // Isle of Conquest
            //_me->SetControlled(true, UNIT_STATE_ROOT);
            //me->AddUnitMovementFlag(MOVEMENTFLAG_ROOT);
            //me->SetSpeed(MOVE_TURN_RATE, 0.7f);
            //me->SetSpeed(MOVE_PITCH_RATE, 0.7f);
            //me->m_movementInfo.flags2=59;
            _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_DECREASE_SPEED, true);
            break;
        // Ulduar vehicles, remove immunities used in flame leviathan spells
        case 335:
        case 336:
        case 338:
            _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, false);
            _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_SCHOOL_ABSORB, false);
            break;
        default:
            break;
    }
}
References _me, Unit::ApplySpellImmune(), BATTLEFIELD_WG_ZONEID, CREATURE_TYPE_MECHANICAL, WorldObject::FindMap(), Creature::GetCreatureTemplate(), Creature::GetSpawnId(), GetVehicleInfo(), WorldObject::GetZoneId(), IMMUNITY_EFFECT, IMMUNITY_MECHANIC, IMMUNITY_STATE, Map::Instanceable(), Creature::isWorldBoss(), MECHANIC_IMMUNE_SHIELD, MECHANIC_SHIELD, SPELL_AURA_DAMAGE_SHIELD, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_RESISTANCE, SPELL_AURA_MOD_STAT, SPELL_AURA_MOD_TAUNT, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_SCHOOL_ABSORB, SPELL_AURA_SCHOOL_IMMUNITY, SPELL_AURA_SPLIT_DAMAGE_PCT, SPELL_EFFECT_ATTACK_ME, SPELL_EFFECT_DISPEL, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MAX_HEALTH, SPELL_EFFECT_HEAL_PCT, Object::ToCreature(), and CreatureTemplate::type.
Referenced by Reset().
CalculatePassengerOffset()
void Vehicle::CalculatePassengerOffset (float & x, float & y, float & z, float * o) const inline override private virtual
This method transforms supplied global coordinates into local offsets.
Implements TransportBase.
    {
        TransportBase::CalculatePassengerOffset(x, y, z, o,
                                                GetBase()->GetPositionX(), GetBase()->GetPositionY(),
                                                GetBase()->GetPositionZ(), GetBase()->GetOrientation());
    }
References TransportBase::CalculatePassengerOffset(), and GetBase().
CalculatePassengerPosition()
void Vehicle::CalculatePassengerPosition (float & x, float & y, float & z, float * o) const inline override private virtual
This method transforms supplied transport offsets into global coordinates.
Implements TransportBase.
    {
        TransportBase::CalculatePassengerPosition(x, y, z, o,
                GetBase()->GetPositionX(), GetBase()->GetPositionY(),
                GetBase()->GetPositionZ(), GetBase()->GetOrientation());
    }
References TransportBase::CalculatePassengerPosition(), and GetBase().
Referenced by AddPassenger(), and RelocatePassengers().
Dismiss()
void Vehicle::Dismiss ()
{
    if (!GetBase()->IsCreature())
        return;
    LOG_DEBUG("vehicles", "Vehicle::Dismiss {}", _me->GetGUID().ToString());
    Uninstall();
    GetBase()->ToCreature()->DespawnOrUnsummon();
}
References _me, Creature::DespawnOrUnsummon(), GetBase(), Object::GetGUID(), LOG_DEBUG, Object::ToCreature(), ObjectGuid::ToString(), and Uninstall().
Referenced by Unit::_ExitVehicle(), BattlefieldWG::OnPlayerLeaveWar(), and Player::UpdateAreaDependentAuras().
EjectPassenger()
void Vehicle::EjectPassenger (Unit * passenger, Unit * controller)
GetAvailableSeatCount()
uint8 Vehicle::GetAvailableSeatCount () const
{
    uint8 ret = 0;
    SeatMap::const_iterator itr;
    for (itr = Seats.begin(); itr != Seats.end(); ++itr)
        if (itr->second.IsEmpty() && (itr->second.SeatInfo->CanEnterOrExit() || itr->second.SeatInfo->IsUsableByOverride()))
            ++ret;
    return ret;
}
Referenced by Aura::CanStackWith(), and npc_brunnhildar_prisoner::npc_brunnhildar_prisonerAI::SpellHit().
GetBase()
Unit * Vehicle::GetBase () const inline
May be called from scripts.
{ return _me; }
References _me.
Referenced by Unit::_EnterVehicle(), Unit::_ExitVehicle(), Creature::_IsTargetAcceptable(), Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), AddPassenger(), Unit::BuildMovementPacket(), CalculatePassengerOffset(), CalculatePassengerPosition(), Dismiss(), GetPassenger(), SmartScript::GetTargets(), ObjectMgr::GetVehicleAccessoryList(), Unit::GetVehicleBase(), WorldSession::HandleEjectPassenger(), spell_auto_repair::HandleScript(), Install(), InstallAccessory(), InstallAllAccessories(), IsVehicleInUse(), ScriptMgr::OnAddPassenger(), ScriptMgr::OnInstall(), ScriptMgr::OnInstallAccessory(), ScriptMgr::OnRemovePassenger(), ScriptMgr::OnReset(), ScriptMgr::OnUninstall(), RelocatePassengers(), Reset(), TeleportVehicle(), and Uninstall().
GetCreatureEntry()
uint32 Vehicle::GetCreatureEntry () const inline
{ return _creatureEntry; }
References _creatureEntry.
Referenced by ObjectMgr::GetVehicleAccessoryList(), Unit::HandleSpellClick(), and InstallAccessory().
GetNextEmptySeat()
int8 Vehicle::GetNextEmptySeat (int8 seatId, bool next) const
{
    SeatMap::const_iterator seat = Seats.find(seatId);
    if (seat == Seats.end())
        return -1;
    while (!seat->second.IsEmpty() || (!seat->second.SeatInfo->CanEnterOrExit() && !seat->second.SeatInfo->IsUsableByOverride()))
    {
        if (next)
        {
            ++seat;
            if (seat == Seats.end())
                seat = Seats.begin();
        }
        else
        {
            if (seat == Seats.begin())
                seat = Seats.end();
            --seat;
        }
        if (seat->first == seatId)
            return -1; // no available seat
    }
    return seat->first;
}
Referenced by Unit::ChangeSeat().
GetPassenger()
Unit * Vehicle::GetPassenger (int8 seatId) const
{
    SeatMap::const_iterator seat = Seats.find(seatId);
    if (seat == Seats.end())
        return nullptr;
    return ObjectAccessor::GetUnit(*GetBase(), seat->second.Passenger.Guid);
}
References GetBase(), and ObjectAccessor::GetUnit().
Referenced by boss_xt002::boss_xt002AI::AttachHeart(), Aura::CanStackWith(), spell_demolisher_ride_vehicle::CheckCast(), npc_orb_carrier::npc_orb_carrierAI::DoAction(), boss_skadi_grauf::boss_skadi_graufAI::DoAction(), SmartScript::GetTargets(), spell_switch_infragreen_bomber_station::HandleDummy(), spell_fight_fire_bomber::HandleDummy(), spell_q13280_13283_plant_battle_standard::HandleDummy(), spell_auto_repair::HandleScript(), spell_q12919_gymers_throw::HandleScript(), InstallAccessory(), boss_flame_leviathan_overload_device::boss_flame_leviathan_overload_deviceAI::OnSpellClick(), boss_flame_leviathan_seat::boss_flame_leviathan_seatAI::PassengerBoarded(), boss_skadi_grauf::boss_skadi_graufAI::RemoveSkadi(), Spell::SelectImplicitCasterObjectTargets(), npc_vics_flying_machine::npc_vics_flying_machineAI::SpellHit(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::SpreadFire(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), and npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI().
GetSeatAddonForSeatOfPassenger()
VehicleSeatAddon const * Vehicle::GetSeatAddonForSeatOfPassenger (Unit const * passenger) const
{
    for (SeatMap::const_iterator itr = Seats.begin(); itr != Seats.end(); itr++)
        if (!itr->second.IsEmpty() && itr->second.Passenger.Guid == passenger->GetGUID())
            return itr->second.SeatAddon;
    return nullptr;
}
References Object::GetGUID().
Referenced by Unit::_ExitVehicle().
GetSeatForPassenger()
VehicleSeatEntry const * Vehicle::GetSeatForPassenger (Unit const * passenger)
{
    SeatMap::iterator itr;
    for (itr = Seats.begin(); itr != Seats.end(); ++itr)
        if (itr->second.Passenger.Guid == passenger->GetGUID())
            return itr->second.SeatInfo;
    return nullptr;
}
References Object::GetGUID().
Referenced by Spell::CheckCast(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleEjectPassenger(), and Player::ProcessTerrainStatusUpdate().
GetSeatIteratorForPassenger()
SeatMap::iterator Vehicle::GetSeatIteratorForPassenger (Unit * passenger)
{
    SeatMap::iterator itr;
    for (itr = Seats.begin(); itr != Seats.end(); ++itr)
        if (itr->second.Passenger.Guid == passenger->GetGUID())
            return itr;
    return Seats.end();
}
References Object::GetGUID().
Referenced by spell_switch_infragreen_bomber_station::HandleDummy(), and RemovePassenger().
GetVehicleInfo()
VehicleEntry const * Vehicle::GetVehicleInfo () const inline
{ return _vehicleInfo; }
References _vehicleInfo.
Referenced by Unit::_ExitVehicle(), ApplyAllImmunities(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::CheckAchievementCriteriaMeet(), WorldSession::HandleRequestPartyMemberStatsOpcode(), InitMovementInfoForBase(), and GameObject::IsWithinDistInMap().
HasEmptySeat()
bool Vehicle::HasEmptySeat (int8 seatId) const
{
    SeatMap::const_iterator seat = Seats.find(seatId);
    if (seat == Seats.end())
        return false;
    return seat->second.IsEmpty();
}
Referenced by Unit::ChangeSeat().
InitMovementInfoForBase()
void Vehicle::InitMovementInfoForBase () private
{
    uint32 vehicleFlags = GetVehicleInfo()->m_flags;
    if (vehicleFlags & VEHICLE_FLAG_NO_STRAFE)
        _me->AddExtraUnitMovementFlag(MOVEMENTFLAG2_NO_STRAFE);
    if (vehicleFlags & VEHICLE_FLAG_NO_JUMPING)
        _me->AddExtraUnitMovementFlag(MOVEMENTFLAG2_NO_JUMPING);
    if (vehicleFlags & VEHICLE_FLAG_FULLSPEEDTURNING)
        _me->AddExtraUnitMovementFlag(MOVEMENTFLAG2_FULL_SPEED_TURNING);
    if (vehicleFlags & VEHICLE_FLAG_ALLOW_PITCHING)
        _me->AddExtraUnitMovementFlag(MOVEMENTFLAG2_ALWAYS_ALLOW_PITCHING);
    if (vehicleFlags & VEHICLE_FLAG_FULLSPEEDPITCHING)
        _me->AddExtraUnitMovementFlag(MOVEMENTFLAG2_FULL_SPEED_PITCHING);
}
References _me, Unit::AddExtraUnitMovementFlag(), GetVehicleInfo(), VehicleEntry::m_flags, MOVEMENTFLAG2_ALWAYS_ALLOW_PITCHING, MOVEMENTFLAG2_FULL_SPEED_PITCHING, MOVEMENTFLAG2_FULL_SPEED_TURNING, MOVEMENTFLAG2_NO_JUMPING, MOVEMENTFLAG2_NO_STRAFE, VEHICLE_FLAG_ALLOW_PITCHING, VEHICLE_FLAG_FULLSPEEDPITCHING, VEHICLE_FLAG_FULLSPEEDTURNING, VEHICLE_FLAG_NO_JUMPING, and VEHICLE_FLAG_NO_STRAFE.
Referenced by Vehicle().
Install()
void Vehicle::Install ()
{
    if (_me->IsCreature())
    {
        if (PowerDisplayEntry const* powerDisplay = sPowerDisplayStore.LookupEntry(_vehicleInfo->m_powerDisplayId))
            _me->setPowerType(Powers(powerDisplay->PowerType));
        else if (_me->IsClass(CLASS_ROGUE, CLASS_CONTEXT_ABILITY))
            _me->setPowerType(POWER_ENERGY);
    }
    _status = STATUS_INSTALLED;
    if (GetBase()->IsCreature())
        sScriptMgr->OnInstall(this);
}
References _me, _status, _vehicleInfo, CLASS_CONTEXT_ABILITY, CLASS_ROGUE, GetBase(), Unit::IsClass(), Object::IsCreature(), VehicleEntry::m_powerDisplayId, POWER_ENERGY, Unit::setPowerType(), sPowerDisplayStore, sScriptMgr, and STATUS_INSTALLED.
Referenced by Creature::AddToWorld().
InstallAccessory()
void Vehicle::InstallAccessory (uint32 entry, int8 seatId, bool minion, uint8 type, uint32 summonTime)
@Prevent adding accessories when vehicle is uninstalling. (Bad script in OnUninstall/OnRemovePassenger/PassengerBoarded hook.)
{
    if (_status == STATUS_UNINSTALLING)
    {
        LOG_ERROR("vehicles", "Vehicle {} attempts to install accessory Entry: {} on seat {} with STATUS_UNINSTALLING! "
                       "Check Uninstall/PassengerBoarded script hooks for errors.", _me->GetGUID().ToString(), entry, (int32)seatId);
        return;
    }
    LOG_DEBUG("vehicles", "Vehicle: Installing accessory entry {} on vehicle entry {} (seat:{})", entry, GetCreatureEntry(), seatId);
    if (Unit* passenger = GetPassenger(seatId))
    {
        // already installed
        if (passenger->GetEntry() == entry)
        {
            ASSERT(passenger->IsCreature());
            if (_me->IsCreature())
            {
                if (_me->ToCreature()->IsInEvadeMode() && passenger->ToCreature()->IsAIEnabled)
                    passenger->ToCreature()->AI()->EnterEvadeMode();
                return;
            }
        }
        else
            passenger->ExitVehicle(); // this should not happen
    }
    if (TempSummon* accessory = _me->SummonCreature(entry, *_me, TempSummonType(type), summonTime))
    {
        if (minion)
            accessory->AddUnitTypeMask(UNIT_MASK_ACCESSORY);
        if (!_me->HandleSpellClick(accessory, seatId))
        {
            accessory->UnSummon();
            return;
        }
        if (GetBase()->IsCreature())
            sScriptMgr->OnInstallAccessory(this, accessory);
    }
}
References _me, _status, ASSERT, GetBase(), GetCreatureEntry(), Object::GetGUID(), GetPassenger(), Unit::HandleSpellClick(), Object::IsCreature(), Creature::IsInEvadeMode(), LOG_DEBUG, LOG_ERROR, sScriptMgr, STATUS_UNINSTALLING, WorldObject::SummonCreature(), Object::ToCreature(), ObjectGuid::ToString(), and UNIT_MASK_ACCESSORY.
Referenced by InstallAllAccessories().
InstallAllAccessories()
void Vehicle::InstallAllAccessories (bool evading)
{
    if (GetBase()->IsPlayer() || !evading)
        RemoveAllPassengers();   // We might have aura's saved in the DB with now invalid casters - remove
    VehicleAccessoryList const* accessories = sObjectMgr->GetVehicleAccessoryList(this);
    if (!accessories)
        return;
    for (VehicleAccessoryList::const_iterator itr = accessories->begin(); itr != accessories->end(); ++itr)
        if (!evading || itr->IsMinion)  // only install minions on evade mode
            InstallAccessory(itr->AccessoryEntry, itr->SeatId, itr->IsMinion, itr->SummonedType, itr->SummonTime);
}
References GetBase(), InstallAccessory(), RemoveAllPassengers(), and sObjectMgr.
Referenced by boss_flame_leviathan_seat::boss_flame_leviathan_seatAI::EnterEvadeMode(), Unit::Mount(), Reset(), and npc_hyldsmeet_protodrake::npc_hyldsmeet_protodrakeAI::UpdateAI().
IsVehicleInUse()
bool Vehicle::IsVehicleInUse ()
{
    for (SeatMap::const_iterator itr = Seats.begin(); itr != Seats.end(); ++itr)
        if (Unit* passenger = ObjectAccessor::GetUnit(*GetBase(), itr->second.Passenger.Guid))
        {
            if (passenger->IsPlayer())
                return true;
            else if (passenger->IsCreature() && passenger->GetVehicleKit() && passenger->GetVehicleKit()->IsVehicleInUse())
                return true;
        }
    return false;
}
References GetBase(), and ObjectAccessor::GetUnit().
Referenced by VehicleAI::OnCharmed().
RelocatePassengers()
void Vehicle::RelocatePassengers ()
{
    ASSERT(_me->GetMap());
    std::vector<std::pair<Unit*, Position>> seatRelocation;
    seatRelocation.reserve(Seats.size());
    // not sure that absolute position calculation is correct, it must depend on vehicle pitch angle
    for (auto const& itr : Seats)
    {
        if (Unit* passenger = ObjectAccessor::GetUnit(*GetBase(), itr.second.Passenger.Guid))
        {
            ASSERT(passenger->IsInWorld());
            float px, py, pz, po;
            passenger->m_movementInfo.transport.pos.GetPosition(px, py, pz, po);
            CalculatePassengerPosition(px, py, pz, &po);
            seatRelocation.emplace_back(passenger, Position(px, py, pz, po));
        }
    }
    for (auto const& pair : seatRelocation)
        pair.first->UpdatePosition(pair.second);
}
References _me, ASSERT, CalculatePassengerPosition(), GetBase(), WorldObject::GetMap(), and ObjectAccessor::GetUnit().
Referenced by Map::CreatureRelocation(), Map::PlayerRelocation(), Unit::UpdateHeight(), and Unit::UpdateOrientation().
RemoveAllPassengers()
void Vehicle::RemoveAllPassengers ()
{
    LOG_DEBUG("vehicles", "Vehicle::RemoveAllPassengers. {}", _me->GetGUID().ToString());
    // Passengers always cast an aura with SPELL_AURA_CONTROL_VEHICLE on the vehicle
    // We just remove the aura and the unapply handler will make the target leave the vehicle.
    // We don't need to iterate over Seats
    _me->RemoveAurasByType(SPELL_AURA_CONTROL_VEHICLE);
    // Following the above logic, this assertion should NEVER fail.
    // Even in 'hacky' cases, there should at least be VEHICLE_SPELL_RIDE_HARDCODED on us.
    // SeatMap::const_iterator itr;
    // for (itr = Seats.begin(); itr != Seats.end(); ++itr)
    //    ASSERT(!itr->second.passenger.Guid);
}
References _me, Object::GetGUID(), LOG_DEBUG, Unit::RemoveAurasByType(), SPELL_AURA_CONTROL_VEHICLE, and ObjectGuid::ToString().
Referenced by InstallAllAccessories(), and Uninstall().
RemovePassenger()
void Vehicle::RemovePassenger (Unit * passenger)
{
    if (unit->GetVehicle() != this)
        return;
    SeatMap::iterator seat = GetSeatIteratorForPassenger(unit);
    // it can happen that unit enters vehicle and removes owner passenger
    // then vehicles is dissmised and removes all existing passengers, even the unit (vehicle has aura of unit)
    // but the unit is not on the vehicles seat yet, thus crashing at ASSERT(seat != Seats.end());
    // ASSERT(seat != Seats.end());
    if (seat == Seats.end())
    {
        LOG_ERROR("vehicles", "Vehicle::RemovePassenger: Vehicle entry ({}) id ({}) is dissmised and removed all existing passangers, but the unit ({}) was not on the vehicle!",
            _me->GetEntry(), _vehicleInfo->m_ID, unit->GetName());
        return;
    }
    LOG_DEBUG("vehicles", "Unit {} exit vehicle entry {} id {} ({}) seat {}",
        unit->GetName(), _me->GetEntry(), _vehicleInfo->m_ID, _me->GetGUID().ToString(), (int32)seat->first);
    if (seat->second.SeatInfo->CanEnterOrExit() && ++_usableSeatNum)
        _me->SetNpcFlag((_me->IsPlayer() ? UNIT_NPC_FLAG_PLAYER_VEHICLE : UNIT_NPC_FLAG_SPELLCLICK));
    // Remove UNIT_FLAG_NOT_SELECTABLE if passenger did not have it before entering vehicle
    if (seat->second.SeatInfo->m_flags & VEHICLE_SEAT_FLAG_PASSENGER_NOT_SELECTABLE && !seat->second.Passenger.IsUnselectable)
        unit->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
    seat->second.Passenger.Reset();
    if (_me->IsCreature() && unit->IsPlayer() && seat->second.SeatInfo->m_flags & VEHICLE_SEAT_FLAG_CAN_CONTROL)
        _me->RemoveCharmedBy(unit);
    if (_me->IsInWorld())
    {
        if (!_me->GetTransport())
        {
            unit->RemoveUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT);
            unit->m_movementInfo.transport.Reset();
        }
        else
            unit->m_movementInfo.transport = _me->m_movementInfo.transport;
    }
    // only for flyable vehicles
    if (_me->IsFlying() && !_me->GetInstanceId() && unit->IsPlayer() && !(unit->ToPlayer()->GetDelayedOperations() & DELAYED_VEHICLE_TELEPORT) && _me->GetEntry() != 30275 /*NPC_WILD_WYRM*/)
        _me->CastSpell(unit, VEHICLE_SPELL_PARACHUTE, true);
    if (_me->IsCreature())
        sScriptMgr->OnRemovePassenger(this, unit);
    if (_me->IsCreature() && _me->ToCreature()->IsAIEnabled)
        _me->ToCreature()->AI()->PassengerBoarded(unit, seat->first, false);
}
References _me, _usableSeatNum, _vehicleInfo, Creature::AI(), Unit::CastSpell(), DELAYED_VEHICLE_TELEPORT, Player::GetDelayedOperations(), Object::GetEntry(), Object::GetGUID(), WorldObject::GetInstanceId(), WorldObject::GetName(), GetSeatIteratorForPassenger(), WorldObject::GetTransport(), Unit::GetVehicle(), Unit::IsAIEnabled, Object::IsCreature(), Unit::IsFlying(), Object::IsInWorld(), Object::IsPlayer(), LOG_DEBUG, LOG_ERROR, VehicleEntry::m_ID, WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, CreatureAI::PassengerBoarded(), Unit::RemoveCharmedBy(), Unit::RemoveUnitFlag(), Unit::RemoveUnitMovementFlag(), MovementInfo::TransportInfo::Reset(), Unit::SetNpcFlag(), sScriptMgr, Object::ToCreature(), Object::ToPlayer(), ObjectGuid::ToString(), MovementInfo::transport, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_FLAG_PLAYER_VEHICLE, UNIT_NPC_FLAG_SPELLCLICK, VEHICLE_SEAT_FLAG_CAN_CONTROL, VEHICLE_SEAT_FLAG_PASSENGER_NOT_SELECTABLE, and VEHICLE_SPELL_PARACHUTE.
Referenced by Unit::_ExitVehicle(), and Unit::ChangeSeat().
Reset()
void Vehicle::Reset (bool evading = false)
{
    LOG_DEBUG("vehicles", "Vehicle::Reset: {}", _me->GetGUID().ToString());
    if (_me->IsPlayer())
    {
        if (_usableSeatNum)
            _me->SetNpcFlag(UNIT_NPC_FLAG_PLAYER_VEHICLE);
    }
    else
    {
        ApplyAllImmunities();
        InstallAllAccessories(evading);
        if (_usableSeatNum)
            _me->SetNpcFlag(UNIT_NPC_FLAG_SPELLCLICK);
    }
    if (GetBase()->IsCreature())
        sScriptMgr->OnReset(this);
}
References _me, _usableSeatNum, ApplyAllImmunities(), GetBase(), Object::GetGUID(), InstallAllAccessories(), Object::IsPlayer(), LOG_DEBUG, Unit::SetNpcFlag(), sScriptMgr, ObjectGuid::ToString(), UNIT_NPC_FLAG_PLAYER_VEHICLE, and UNIT_NPC_FLAG_SPELLCLICK.
Referenced by Creature::AIM_Initialize(), CreatureAI::EnterEvadeMode(), Unit::Mount(), and Creature::Update().
TeleportVehicle()
void Vehicle::TeleportVehicle (float x, float y, float z, float ang)
{
    _me->GetMap()->LoadGrid(x, y);
    _me->NearTeleportTo(x, y, z, ang, true);
    for (SeatMap::const_iterator itr = Seats.begin(); itr != Seats.end(); ++itr)
        if (Unit* passenger = ObjectAccessor::GetUnit(*GetBase(), itr->second.Passenger.Guid))
        {
            if (passenger->IsPlayer())
            {
                passenger->ToPlayer()->SetMover(passenger);
                passenger->NearTeleportTo(x, y, z, ang, false, true);
                passenger->ToPlayer()->ScheduleDelayedOperation(DELAYED_VEHICLE_TELEPORT);
            }
            else if (passenger->IsCreature() && passenger->GetVehicleKit())
                passenger->GetVehicleKit()->TeleportVehicle(x, y, z, ang);
        }
}
References _me, DELAYED_VEHICLE_TELEPORT, GetBase(), WorldObject::GetMap(), ObjectAccessor::GetUnit(), Map::LoadGrid(), and Unit::NearTeleportTo().
Referenced by Spell::EffectTeleportUnits().
Uninstall()
void Vehicle::Uninstall ()
@Prevent recursive uninstall call. (Bad script in OnUninstall/OnRemovePassenger/PassengerBoarded hook.)
{
    if (_status == STATUS_UNINSTALLING && !GetBase()->HasUnitTypeMask(UNIT_MASK_MINION))
    {
        LOG_ERROR("vehicles", "Vehicle {} attempts to uninstall, but already has STATUS_UNINSTALLING! "
                       "Check Uninstall/PassengerBoarded script hooks for errors.", _me->GetGUID().ToString());
        return;
    }
    _status = STATUS_UNINSTALLING;
    LOG_DEBUG("vehicles", "Vehicle::Uninstall {}", _me->GetGUID().ToString());
    RemoveAllPassengers();
    if (_me && _me->IsCreature())
    {
        sScriptMgr->OnUninstall(this);
    }
}
References _me, _status, GetBase(), Object::GetGUID(), Object::IsCreature(), LOG_DEBUG, LOG_ERROR, RemoveAllPassengers(), sScriptMgr, STATUS_UNINSTALLING, ObjectGuid::ToString(), and UNIT_MASK_MINION.
Referenced by Unit::_ExitVehicle(), Dismiss(), and Unit::RemoveVehicleKit().
Friends And Related Function Documentation
Unit::CreateVehicleKit
bool Unit::CreateVehicleKit (uint32 id, uint32 creatureEntry) friend
Unit::RemoveVehicleKit
void Unit::RemoveVehicleKit () friend
Member Data Documentation
_creatureEntry
uint32 Vehicle::_creatureEntry private
Referenced by GetCreatureEntry().
_me
Unit* Vehicle::_me private
Referenced by AddPassenger(), ApplyAllImmunities(), Dismiss(), GetBase(), InitMovementInfoForBase(), Install(), InstallAccessory(), RelocatePassengers(), RemoveAllPassengers(), RemovePassenger(), Reset(), TeleportVehicle(), Uninstall(), Vehicle(), and ~Vehicle().
_status
Status Vehicle::_status private
Referenced by AddPassenger(), Install(), InstallAccessory(), Uninstall(), and ~Vehicle().
_usableSeatNum
uint32 Vehicle::_usableSeatNum private
Referenced by AddPassenger(), RemovePassenger(), Reset(), and Vehicle().
_vehicleInfo
VehicleEntry const* Vehicle::_vehicleInfo private
Referenced by AddPassenger(), GetVehicleInfo(), Install(), RemovePassenger(), and Vehicle().
Seats
SeatMap Vehicle::Seats
Referenced by SmartAI::CheckConditions(), spell_switch_infragreen_bomber_station::HandleDummy(), FlameLeviathanPursuedTargetSelector::operator()(), boss_flame_leviathan::boss_flame_leviathanAI::SpellHitTarget(), and npc_wg_siege_machine::npc_wg_siege_machineAI::UpdateAI().