AzerothCore: FlightPathMovementGenerator Class Reference
FlightPathMovementGenerator Class Reference
#include "WaypointMovementGenerator.h"
Classes
struct TaxiNodeChangeInfo
node index where preloading starts
Public Member Functions
FlightPathMovementGenerator (uint32 startNode=0)
void LoadPath (Player *player)
void DoInitialize (Player *)
void DoReset (Player *)
void DoFinalize (Player *)
bool DoUpdate (Player *, uint32)
MovementGeneratorType GetMovementGeneratorType () override
TaxiPathNodeList const & GetPath ()
uint32 GetPathAtMapEnd () const
bool HasArrived () const
void SetCurrentNodeAfterTeleport ()
void SkipCurrentNode ()
void DoEventIfAny (Player *player, TaxiPathNodeEntry const *node, bool departure)
bool GetResetPos (Player *, float &x, float &y, float &z)
void InitEndGridInfo ()
void PreloadEndGrid ()
Public Member Functions inherited from MovementGeneratorMedium< Player, FlightPathMovementGenerator >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual void Initialize (Unit *)=0
virtual void Finalize (Unit *)=0
virtual void Reset (Unit *)=0
virtual bool Update (Unit *, uint32 time_diff)=0
virtual MovementGeneratorType GetMovementGeneratorType ()=0
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual void Pause (uint32)
virtual void Resume (uint32)
virtual bool GetResetPosition (float &, float &, float &)
Public Member Functions inherited from PathMovementBase< Player, TaxiPathNodeList >
PathMovementBase ()
PathMovementBase (TaxiPathNodeList path)
virtual ~PathMovementBase ()
uint32 GetCurrentNode () const
Private Attributes
float _endGridX
float _endGridY
X coord of last node location.
uint32 _endMapId
Y coord of last node location.
uint32 _preloadTargetNode
map Id of last node location
std::deque< TaxiNodeChangeInfo > _pointsForPathSwitch
Additional Inherited Members
Protected Attributes inherited from PathMovementBase< Player, TaxiPathNodeList >
TaxiPathNodeList i_path
uint32 i_currentNode
Detailed Description
FlightPathMovementGenerator generates movement of the player for the paths and hence generates ground and activities for the player.
Constructor & Destructor Documentation
FlightPathMovementGenerator()
FlightPathMovementGenerator::FlightPathMovementGenerator (uint32 startNode = 0) inline explicit
        {
            i_currentNode = startNode;
            _endGridX = 0.0f;
            _endGridY = 0.0f;
            _endMapId = 0;
            _preloadTargetNode = 0;
        }
References _endGridX, _endGridY, _endMapId, _preloadTargetNode, and PathMovementBase< Player, TaxiPathNodeList >::i_currentNode.
Member Function Documentation
DoEventIfAny()
void FlightPathMovementGenerator::DoEventIfAny (Player * player, TaxiPathNodeEntry const * node, bool departure)
{
    if (uint32 eventid = departure ? node->departureEventID : node->arrivalEventID)
    {
        LOG_DEBUG("maps.script", "Taxi {} event {} of node {} of path {} for player {}", departure ? "departure" : "arrival", eventid, node->index, node->path, player->GetName());
        player->GetMap()->ScriptsStart(sEventScripts, eventid, player, player);
    }
}
References TaxiPathNodeEntry::arrivalEventID, TaxiPathNodeEntry::departureEventID, WorldObject::GetMap(), WorldObject::GetName(), TaxiPathNodeEntry::index, LOG_DEBUG, TaxiPathNodeEntry::path, Map::ScriptsStart(), and sEventScripts.
Referenced by DoUpdate().
DoFinalize()
void FlightPathMovementGenerator::DoFinalize (Player * player)
{
    // remove flag to prevent send object build movement packets for flight state and crash (movement generator already not at top of stack)
    player->ClearUnitState(UNIT_STATE_IN_FLIGHT);
    player->m_taxi.ClearTaxiDestinations();
    player->Dismount();
    player->RemoveUnitFlag(UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_TAXI_FLIGHT);
    if (player->m_taxi.empty())
    {
        player->getHostileRefMgr().setOnlineOfflineState(true);
        // update z position to ground and orientation for landing point
        // this prevent cheating with landing  point at lags
        // when client side flight end early in comparison server side
        player->StopMoving();
        // When the player reaches the last flight point, teleport to destination taxi node location
        player->SetFallInformation(GameTime::GetGameTime().count(), player->GetPositionZ());
    }
    player->RemovePlayerFlag(PLAYER_FLAGS_TAXI_BENCHMARK);
}
References PlayerTaxi::ClearTaxiDestinations(), Unit::ClearUnitState(), Unit::Dismount(), PlayerTaxi::empty(), GameTime::GetGameTime(), Unit::getHostileRefMgr(), Position::GetPositionZ(), Player::m_taxi, PLAYER_FLAGS_TAXI_BENCHMARK, Player::RemovePlayerFlag(), Unit::RemoveUnitFlag(), Player::SetFallInformation(), HostileRefMgr::setOnlineOfflineState(), Unit::StopMoving(), UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_TAXI_FLIGHT, and UNIT_STATE_IN_FLIGHT.
DoInitialize()
void FlightPathMovementGenerator::DoInitialize (Player * player)
{
    Reset(player);
    InitEndGridInfo();
}
References InitEndGridInfo(), and MovementGeneratorMedium< Player, FlightPathMovementGenerator >::Reset().
DoReset()
void FlightPathMovementGenerator::DoReset (Player * player)
{
    uint32 end = GetPathAtMapEnd();
    uint32 currentNodeId = GetCurrentNode();
    if (currentNodeId == end)
    {
        LOG_DEBUG("movement.flightpath", "FlightPathMovementGenerator::DoReset: trying to start a flypath from the end point. {}", player->GetGUID().ToString());
        return;
    }
    player->getHostileRefMgr().setOnlineOfflineState(false);
    player->AddUnitState(UNIT_STATE_IN_FLIGHT);
    player->SetUnitFlag(UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_TAXI_FLIGHT);
    Movement::MoveSplineInit init(player);
    // Providing a starting vertex since the taxi paths do not provide such
    init.Path().push_back(G3D::Vector3(player->GetPositionX(), player->GetPositionY(), player->GetPositionZ()));
    for (uint32 i = currentNodeId; i != end; ++i)
    {
        G3D::Vector3 vertice(i_path[i]->x, i_path[i]->y, i_path[i]->z);
        init.Path().push_back(vertice);
    }
    init.SetFirstPointId(GetCurrentNode());
    init.SetFly();
    init.SetVelocity(PLAYER_FLIGHT_SPEED);
    init.Launch();
}
References Unit::AddUnitState(), PathMovementBase< Player, TaxiPathNodeList >::GetCurrentNode(), Object::GetGUID(), Unit::getHostileRefMgr(), GetPathAtMapEnd(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), PathMovementBase< Player, TaxiPathNodeList >::i_path, Movement::MoveSplineInit::Launch(), LOG_DEBUG, Movement::MoveSplineInit::Path(), PLAYER_FLIGHT_SPEED, Movement::MoveSplineInit::SetFirstPointId(), Movement::MoveSplineInit::SetFly(), HostileRefMgr::setOnlineOfflineState(), Unit::SetUnitFlag(), Movement::MoveSplineInit::SetVelocity(), ObjectGuid::ToString(), UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_TAXI_FLIGHT, and UNIT_STATE_IN_FLIGHT.
DoUpdate()
bool FlightPathMovementGenerator::DoUpdate (Player * player, uint32)
{
    // skipping the first spline path point because it's our starting point and not a taxi path point
    uint32 pointId = player->movespline->currentPathIdx() <= 0 ? 0 : player->movespline->currentPathIdx() - 1;
    if (pointId > i_currentNode && i_currentNode < i_path.size() - 1)
    {
        bool departureEvent = true;
        do
        {
            ASSERT(i_currentNode < i_path.size(), "Point Id: {}\n{}", pointId, player->GetGUID().ToString());
            DoEventIfAny(player, i_path[i_currentNode], departureEvent);
            while (!_pointsForPathSwitch.empty() && _pointsForPathSwitch.front().PathIndex <= i_currentNode)
            {
                _pointsForPathSwitch.pop_front();
                player->m_taxi.NextTaxiDestination();
                if (!_pointsForPathSwitch.empty())
                {
                    player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TRAVELLING, _pointsForPathSwitch.front().Cost);
                    player->ModifyMoney(-_pointsForPathSwitch.front().Cost);
                }
            }
            if (pointId == i_currentNode)
            {
                break;
            }
            if (i_currentNode == _preloadTargetNode)
            {
                PreloadEndGrid();
            }
            i_currentNode += departureEvent ? 1 : 0;
            departureEvent = !departureEvent;
        } while (i_currentNode < i_path.size() - 1);
    }
    return i_currentNode < (i_path.size() - 1);
}
References _pointsForPathSwitch, _preloadTargetNode, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TRAVELLING, ASSERT, Movement::MoveSpline::currentPathIdx(), DoEventIfAny(), Object::GetGUID(), PathMovementBase< Player, TaxiPathNodeList >::i_currentNode, PathMovementBase< Player, TaxiPathNodeList >::i_path, Player::m_taxi, Player::ModifyMoney(), Unit::movespline, PlayerTaxi::NextTaxiDestination(), PreloadEndGrid(), ObjectGuid::ToString(), and Player::UpdateAchievementCriteria().
GetMovementGeneratorType()
MovementGeneratorType FlightPathMovementGenerator::GetMovementGeneratorType () inline override virtual
Implements MovementGenerator.
{ return FLIGHT_MOTION_TYPE; }
References FLIGHT_MOTION_TYPE.
GetPath()
TaxiPathNodeList const & FlightPathMovementGenerator::GetPath () inline
{ return i_path; }
References PathMovementBase< Player, TaxiPathNodeList >::i_path.
GetPathAtMapEnd()
uint32 FlightPathMovementGenerator::GetPathAtMapEnd () const
{
    if (i_currentNode >= i_path.size())
    {
        return i_path.size();
    }
    uint32 curMapId = i_path[i_currentNode]->mapid;
    for (uint32 i = i_currentNode; i < i_path.size(); ++i)
    {
        if (i_path[i]->mapid != curMapId)
        {
            return i;
        }
    }
    return i_path.size();
}
References PathMovementBase< Player, TaxiPathNodeList >::i_currentNode, and PathMovementBase< Player, TaxiPathNodeList >::i_path.
Referenced by DoReset().
GetResetPos()
bool FlightPathMovementGenerator::GetResetPos (Player * , float & x, float & y, float & z)
{
    TaxiPathNodeEntry const* node = i_path[i_currentNode];
    x = node->x;
    y = node->y;
    z = node->z;
    return true;
}
References PathMovementBase< Player, TaxiPathNodeList >::i_currentNode, PathMovementBase< Player, TaxiPathNodeList >::i_path, TaxiPathNodeEntry::x, TaxiPathNodeEntry::y, and TaxiPathNodeEntry::z.
HasArrived()
bool FlightPathMovementGenerator::HasArrived () const inline
{ return (i_currentNode >= i_path.size()); }
References PathMovementBase< Player, TaxiPathNodeList >::i_currentNode, and PathMovementBase< Player, TaxiPathNodeList >::i_path.
InitEndGridInfo()
void FlightPathMovementGenerator::InitEndGridInfo ()
Storage to preload flightmaster grid at end of flight. For multi-stop flights, this will be reinitialized for each flightmaster at the end of each spline (or stop) in the flight.
Number of nodes in path.
MapId of last node
{
    uint32 nodeCount = i_path.size();
    _endMapId = i_path[nodeCount - 1]->mapid;
    // pussywizard:
    {
        _preloadTargetNode = nodeCount - 1;
        for (uint8 i = 3; i > 0; --i)
            if (nodeCount >= i && _endMapId == i_path[nodeCount - i]->mapid)
            {
                _preloadTargetNode = nodeCount - i;
                break;
            }
        //_preloadTargetNode = nodeCount - 3; // pussywizard: this can be on other map
    }
    _endGridX = i_path[nodeCount - 1]->x;
    _endGridY = i_path[nodeCount - 1]->y;
}
References _endGridX, _endGridY, _endMapId, _preloadTargetNode, and PathMovementBase< Player, TaxiPathNodeList >::i_path.
Referenced by DoInitialize().
LoadPath()
void FlightPathMovementGenerator::LoadPath (Player * player)
{
    _pointsForPathSwitch.clear();
    std::deque<uint32> const& taxi = player->m_taxi.GetPath();
    float discount = player->GetReputationPriceDiscount(player->m_taxi.GetFlightMasterFactionTemplate());
    for (uint32 src = 0, dst = 1; dst < taxi.size(); src = dst++)
    {
        uint32 path, cost;
        sObjectMgr->GetTaxiPath(taxi[src], taxi[dst], path, cost);
        if (path > sTaxiPathNodesByPath.size())
        {
            return;
        }
        TaxiPathNodeList const& nodes = sTaxiPathNodesByPath[path];
        if (!nodes.empty())
        {
            TaxiPathNodeEntry const* start = nodes[0];
            TaxiPathNodeEntry const* end = nodes[nodes.size() - 1];
            bool passedPreviousSegmentProximityCheck = false;
            for (uint32 i = 0; i < nodes.size(); ++i)
            {
                if (passedPreviousSegmentProximityCheck || !src || i_path.empty() || IsNodeIncludedInShortenedPath(i_path[i_path.size() - 1], nodes[i]))
                {
                    if ((!src || (IsNodeIncludedInShortenedPath(start, nodes[i]) && i >= 2)) &&
                        (dst == taxi.size() - 1 || (IsNodeIncludedInShortenedPath(end, nodes[i]) && i < nodes.size() - 1)))
                    {
                        passedPreviousSegmentProximityCheck = true;
                        i_path.push_back(nodes[i]);
                    }
                }
                else
                {
                    i_path.pop_back();
                    --_pointsForPathSwitch.back().PathIndex;
                }
            }
        }
        _pointsForPathSwitch.push_back({ uint32(i_path.size() - 1), int32(ceil(cost * discount)) });
    }
    // TODO: fixes crash, but can be handled in a better way once we will know how to reproduce it.
    if (GetCurrentNode() >= i_path.size())
    {
        std::string paths;
        std::deque<uint32> const& taxi = player->m_taxi.GetPath();
        for (uint32 src = 0, dst = 1; dst < taxi.size(); src = dst++)
        {
            uint32 path, cost;
            sObjectMgr->GetTaxiPath(taxi[src], taxi[dst], path, cost);
            paths += std::to_string(path) + " ";
        }
        LOG_ERROR("movement.flightpath", "Failed to build correct path for player: {}. Current node: {}, max nodes: {}. Paths: {}. Player pos: {}.", player->GetGUID().ToString(), GetCurrentNode(), i_path.size(), paths, player->GetPosition().ToString());
        // Lets choose the second last element so that a player would still have some flight.
        if (int(i_path.size()) - 2 >= 0)
            i_currentNode = uint32(i_path.size() - 2);
        else
            i_currentNode = uint32(i_path.size() - 1);
    }
}
References _pointsForPathSwitch, PathMovementBase< Player, TaxiPathNodeList >::GetCurrentNode(), PlayerTaxi::GetFlightMasterFactionTemplate(), Object::GetGUID(), PlayerTaxi::GetPath(), Position::GetPosition(), Player::GetReputationPriceDiscount(), PathMovementBase< Player, TaxiPathNodeList >::i_currentNode, PathMovementBase< Player, TaxiPathNodeList >::i_path, IsNodeIncludedInShortenedPath(), LOG_ERROR, Player::m_taxi, sObjectMgr, sTaxiPathNodesByPath, and ObjectGuid::ToString().
Referenced by MotionMaster::MoveTaxiFlight().
PreloadEndGrid()
void FlightPathMovementGenerator::PreloadEndGrid ()
{
    // used to preload the final grid where the flightmaster is
    Map* endMap = sMapMgr->FindBaseNonInstanceMap(_endMapId);
    // Load the grid
    if (endMap)
    {
        LOG_DEBUG("misc", "Preloading grid ({}, {}) for map {} at node index {}/{}", _endGridX, _endGridY, _endMapId, _preloadTargetNode, (uint32)(i_path.size() - 1));
        endMap->LoadGrid(_endGridX, _endGridY);
    }
    else
    {
        LOG_DEBUG("misc", "Unable to determine map to preload flightmaster grid");
    }
}
References _endGridX, _endGridY, _endMapId, _preloadTargetNode, PathMovementBase< Player, TaxiPathNodeList >::i_path, Map::LoadGrid(), LOG_DEBUG, and sMapMgr.
Referenced by DoUpdate().
SetCurrentNodeAfterTeleport()
void FlightPathMovementGenerator::SetCurrentNodeAfterTeleport ()
{
    if (i_path.empty() || i_currentNode >= i_path.size())
    {
        return;
    }
    uint32 map0 = i_path[i_currentNode]->mapid;
    for (std::size_t i = i_currentNode + 1; i < i_path.size(); ++i)
    {
        if (i_path[i]->mapid != map0)
        {
            i_currentNode = i;
            return;
        }
    }
}
References PathMovementBase< Player, TaxiPathNodeList >::i_currentNode, and PathMovementBase< Player, TaxiPathNodeList >::i_path.
SkipCurrentNode()
void FlightPathMovementGenerator::SkipCurrentNode () inline
{ ++i_currentNode; }
References PathMovementBase< Player, TaxiPathNodeList >::i_currentNode.
Member Data Documentation
_endGridX
float FlightPathMovementGenerator::_endGridX private
Referenced by FlightPathMovementGenerator(), InitEndGridInfo(), and PreloadEndGrid().
_endGridY
float FlightPathMovementGenerator::_endGridY private
X coord of last node location.
Referenced by FlightPathMovementGenerator(), InitEndGridInfo(), and PreloadEndGrid().
_endMapId
uint32 FlightPathMovementGenerator::_endMapId private
Y coord of last node location.
Referenced by FlightPathMovementGenerator(), InitEndGridInfo(), and PreloadEndGrid().
_pointsForPathSwitch
std::deque<TaxiNodeChangeInfo> FlightPathMovementGenerator::_pointsForPathSwitch private
Referenced by DoUpdate(), and LoadPath().
_preloadTargetNode
uint32 FlightPathMovementGenerator::_preloadTargetNode private
map Id of last node location
Referenced by DoUpdate(), FlightPathMovementGenerator(), InitEndGridInfo(), and PreloadEndGrid().