AzerothCore: npc_hallows_end_soh Struct Reference
npc_hallows_end_soh Struct Reference
Public Member Functions
npc_hallows_end_soh (Creature *creature)
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void MoveInLineOfSight (Unit *) override
void DoAction (int32 param) override
void GetPosToLand (float &x, float &y, float &z)
void Reset () override
void EnterEvadeMode (EvadeReason) override
uint32 GetData (uint32) const override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void CastFires (bool intial)
void FinishEvent (bool failed)
void MovementInform (uint32 type, uint32 point) override
void JustDied (Unit *) override
void CompleteQuest ()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
uint32 playerCount
uint32 counter
GuidList unitList
int32 pos
TaskScheduler scheduler
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_hallows_end_soh()
npc_hallows_end_soh::npc_hallows_end_soh (Creature * creature) inline
                                            : ScriptedAI(creature)
    {
        pos = 0;
        counter = 0;
        unitList.clear();
        me->CastSpell(me, SPELL_HORSEMAN_MOUNT, true);
        me->SetSpeed(MOVE_WALK, 3.0f, true);
    }
References Unit::CastSpell(), counter, ScriptedAI::me, MOVE_WALK, pos, Unit::SetSpeed(), SPELL_HORSEMAN_MOUNT, and unitList.
Member Function Documentation
CastFires()
void npc_hallows_end_soh::CastFires (bool intial) inline
    {
        std::vector<Unit*> tmpList;
        for (ObjectGuid const& guid : unitList)
        {
            if (Unit* c = ObjectAccessor::GetUnit(*me, guid))
            {
                if (!c->HasPeriodicDummyAura())
                {
                    tmpList.push_back(c);
                }
            }
        }
        if (tmpList.empty())
        {
            return;
        }
        std::list<Player*> players;
        Acore::AnyPlayerInObjectRangeCheck checker(me, 60.f);
        Acore::PlayerListSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(me, players, checker);
        Cell::VisitWorldObjects(me, searcher, 60.f);
        if (players.empty())
        {
            return;
        }
        playerCount = static_cast<uint32>(players.size()) - 1;
        if (!intial)
        {
            float playerRate = std::max(0.f, 0.5f - playerCount * 0.25f);
            // If there are more burning triggers than players, do not cast next fire
            if (tmpList.size() < unitList.size() * playerRate)
            {
                return;
            }
        }
        else
            playerCount += 1;
        uint32 sizeCount = (playerCount / 3) + 1;
        if (intial && playerCount > 0)
        {
            sizeCount += playerCount % 2;
        }
        Acore::Containers::RandomResize(tmpList, sizeCount);
        for (Unit* trigger : tmpList)
            me->CastSpell(trigger, SPELL_START_FIRE, true);
    }
References Unit::CastSpell(), ObjectAccessor::GetUnit(), ScriptedAI::me, playerCount, Acore::Containers::RandomResize(), SPELL_START_FIRE, unitList, and Cell::VisitWorldObjects().
Referenced by UpdateAI().
CompleteQuest()
void npc_hallows_end_soh::CompleteQuest () inline
    {
        float radius = 100.0f;
        std::list<Player*> players;
        Acore::AnyPlayerInObjectRangeCheck checker(me, radius);
        Acore::PlayerListSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(me, players, checker);
        Cell::VisitWorldObjects(me, searcher, radius);
        for (Player* player : players)
        {
            player->AreaExploredOrEventHappens(QUEST_STOP_THE_FIRES_H);
            player->AreaExploredOrEventHappens(QUEST_STOP_THE_FIRES_A);
            player->AreaExploredOrEventHappens(QUEST_LET_THE_FIRES_COME_H);
            player->AreaExploredOrEventHappens(QUEST_LET_THE_FIRES_COME_A);
        }
    }
References ScriptedAI::me, QUEST_LET_THE_FIRES_COME_A, QUEST_LET_THE_FIRES_COME_H, QUEST_STOP_THE_FIRES_A, QUEST_STOP_THE_FIRES_H, and Cell::VisitWorldObjects().
Referenced by JustDied().
DoAction()
void npc_hallows_end_soh::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
    {
        pos = param;
    }
References pos.
EnterEvadeMode()
void npc_hallows_end_soh::EnterEvadeMode (EvadeReason) inline override virtual
Reimplemented from CreatureAI.
    {
        me->DespawnOrUnsummon(1);
    }
References Creature::DespawnOrUnsummon(), and ScriptedAI::me.
FinishEvent()
void npc_hallows_end_soh::FinishEvent (bool failed) inline
    {
        if (failed)
        {
            Talk(TALK_SHADE_FAILED);
            for (ObjectGuid const& guid : unitList)
                if (Unit* c = ObjectAccessor::GetUnit(*me, guid))
                    c->RemoveAllAuras();
            me->DespawnOrUnsummon(1);
        }
        else
        {
            Talk(TALK_SHADE_DEFEATED);
            float x, y, z;
            GetPosToLand(x, y, z);
            me->GetMotionMaster()->Clear();
            me->GetMotionMaster()->MoveIdle();
            me->GetMotionMaster()->MovePoint(8, x, y, z);
        }
    }
References MotionMaster::Clear(), Creature::DespawnOrUnsummon(), Unit::GetMotionMaster(), GetPosToLand(), ObjectAccessor::GetUnit(), ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), TALK_SHADE_DEFEATED, TALK_SHADE_FAILED, and unitList.
Referenced by UpdateAI().
GetData()
uint32 npc_hallows_end_soh::GetData (uint32) const inline override virtual
Reimplemented from UnitAI.
    {
        return playerCount;
    }
References playerCount.
GetPosToLand()
void npc_hallows_end_soh::GetPosToLand (float & x, float & y, float & z) inline
    {
        switch (pos)
        {
            case 235431:
                x = -9445.1f;
                y = 63.27f;
                z = 58.16f;
                break;
            case 235432:
                x = -5616.30f;
                y = -481.89f;
                z = 398.99f;
                break;
            case 235433:
                x = -4198.1f;
                y = -12509.13f;
                z = 46.6f;
                break;
            case 235434:
                x = 360.9f;
                y = -4735.5f;
                z = 11.773f;
                break;
            case 235435:
                x = 2229.4f;
                y = 263.1f;
                z = 36.13f;
                break;
            case 235436:
                x = 9532.9f;
                y = -6833.8f;
                z = 18.5f;
                break;
            default:
                x = 0;
                y = 0;
                z = 0;
                break;
        }
    }
References pos.
Referenced by FinishEvent(), and JustDied().
JustDied()
void npc_hallows_end_soh::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        Talk(TALK_SHADE_DEATH);
        float x, y, z;
        GetPosToLand(x, y, z);
        me->CastSpell(x, y, z, SPELL_SUMMON_LANTERN, true);
        CompleteQuest();
    }
References Unit::CastSpell(), CompleteQuest(), GetPosToLand(), ScriptedAI::me, SPELL_SUMMON_LANTERN, and TALK_SHADE_DEATH.
JustEngagedWith()
void npc_hallows_end_soh::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
    {
        scheduler.Schedule(6s, [this](TaskContext context)
        {
            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 30.f, true))
            {
                me->CastSpell(target, SPELL_HORSEMAN_CONFLAGRATION, false);
                target->CastSpell(target, SPELL_HORSEMAN_CONFLAGRATION_SOUND, true);
                Talk(TALK_SHADE_CONFLAGRATION);
            }
            context.Repeat(12s);
        })
        .Schedule(7s, [this](TaskContext context)
        {
            DoCastVictim(SPELL_HORSEMAN_CLEAVE, true);
            context.Repeat(8s);
        });
    }
References Unit::CastSpell(), UnitAI::DoCastVictim(), ScriptedAI::me, TaskContext::Repeat(), TaskScheduler::Schedule(), scheduler, UnitAI::SelectTarget(), SPELL_HORSEMAN_CLEAVE, SPELL_HORSEMAN_CONFLAGRATION, SPELL_HORSEMAN_CONFLAGRATION_SOUND, and TALK_SHADE_CONFLAGRATION.
MoveInLineOfSight()
void npc_hallows_end_soh::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{}
MovementInform()
void npc_hallows_end_soh::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type == POINT_MOTION_TYPE && point == 8)
        {
            me->RemoveAllAuras();
            me->SetCanFly(false);
            me->SetDisableGravity(false);
            events.ScheduleEvent(4, 2000);
        }
    }
References ScriptedAI::me, POINT_MOTION_TYPE, Unit::RemoveAllAuras(), Creature::SetCanFly(), and Creature::SetDisableGravity().
Reset()
void npc_hallows_end_soh::Reset () inline override virtual
Reimplemented from ScriptedAI.
    {
        playerCount = 0;
        unitList.clear();
        std::list<Creature*> temp;
        me->GetCreaturesWithEntryInRange(temp, 100.0f, NPC_FIRE_TRIGGER);
        for (std::list<Creature*>::const_iterator itr = temp.begin(); itr != temp.end(); ++itr)
        {
            unitList.push_back((*itr)->GetGUID());
        }
        events.ScheduleEvent(1, 3s);
        events.ScheduleEvent(2, 25s);
        events.ScheduleEvent(2, 43s);
        events.ScheduleEvent(3, 63s);
        me->SetReactState(REACT_PASSIVE);
        me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
        me->SetCanFly(true);
        me->SetDisableGravity(true);
    }
References WorldObject::GetCreaturesWithEntryInRange(), ScriptedAI::me, NPC_FIRE_TRIGGER, playerCount, REACT_PASSIVE, Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetReactState(), Unit::SetUnitFlag(), UNIT_FLAG_NON_ATTACKABLE, and unitList.
UpdateAI()
void npc_hallows_end_soh::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
    {
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
            return;
        switch (events.ExecuteEvent())
        {
            case 1:
                Talk(TALK_SHADE_PREPARE);
                break;
            case 2:
                {
                    CastFires(true);
                    break;
                }
            case 3:
                {
                    bool checkBurningTriggers = false;
                    for (ObjectGuid const& guid : unitList)
                        if (Unit* c = ObjectAccessor::GetUnit(*me, guid))
                            if (c->HasPeriodicDummyAura())
{
                                checkBurningTriggers = true;
                                break;
                            }
                    if (!checkBurningTriggers)
                    {
                        FinishEvent(false);
                        return;
                    }
                    counter++;
                    if (counter > 21)
                    {
                        bool failed = false;
                        for (ObjectGuid const& guid : unitList)
                            if (Unit* c = ObjectAccessor::GetUnit(*me, guid))
                                if (c->HasPeriodicDummyAura())
{
                                    failed = true;
                                    break;
                                }
                        FinishEvent(failed);
                        return;
                    }
                    if (counter == 5)
                    {
                        Talk(TALK_SHADE_START_EVENT);
                    }
                    else if (counter == 15)
                    {
                        Talk(TALK_SHADE_MORE_FIRES);
                    }
                    CastFires(false);
                    events.RepeatEvent(15000);
                    break;
                }
                case 4:
                {
                    me->ReplaceAllUnitFlags(UNIT_FLAG_NONE);
                    me->SetReactState(REACT_AGGRESSIVE);
                    if (Unit* target = me->SelectNearestPlayer(30.0f))
                        AttackStart(target);
                    break;
                }
        }
        if (!UpdateVictim())
            return;
        scheduler.Update(diff, [this]
        {
            DoMeleeAttackIfReady();
        });
    }
References ScriptedAI::AttackStart(), CastFires(), counter, UnitAI::DoMeleeAttackIfReady(), FinishEvent(), ObjectAccessor::GetUnit(), Unit::HasUnitState(), ScriptedAI::me, REACT_AGGRESSIVE, Unit::ReplaceAllUnitFlags(), scheduler, WorldObject::SelectNearestPlayer(), Creature::SetReactState(), TALK_SHADE_MORE_FIRES, TALK_SHADE_PREPARE, TALK_SHADE_START_EVENT, UNIT_FLAG_NONE, UNIT_STATE_CASTING, unitList, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
counter
uint32 npc_hallows_end_soh::counter
Referenced by npc_hallows_end_soh(), and UpdateAI().
events
EventMap npc_hallows_end_soh::events
playerCount
uint32 npc_hallows_end_soh::playerCount
Referenced by CastFires(), GetData(), and Reset().
pos
int32 npc_hallows_end_soh::pos
Referenced by DoAction(), GetPosToLand(), and npc_hallows_end_soh().
scheduler
TaskScheduler npc_hallows_end_soh::scheduler
Referenced by JustEngagedWith(), and UpdateAI().
unitList
GuidList npc_hallows_end_soh::unitList
Referenced by CastFires(), FinishEvent(), npc_hallows_end_soh(), Reset(), and UpdateAI().