AzerothCore: User to World Communication
User to World Communication
Files
file Opcodes.h
file WorldSession.cpp
file WorldSession.h
file WorldSocketMgr.h
Namespaces
namespace lfg
namespace WorldPackets
Classes
class OpcodeHandler
class ClientOpcodeHandler
class ServerOpcodeHandler
class OpcodeTable
struct AccountData
class PacketFilter
class MapSessionFilter
class WorldSessionFilter
class CharacterCreateInfo
struct CharacterRenameInfo
struct CharacterCustomizeInfo
struct CharacterFactionChangeInfo
struct PacketCounter
class WorldSession
Player session in the World.
class WorldSocketMgr
Manages all sockets connected to peers and network threads.
Macros
#define NUM_ACCOUNT_DATA_TYPES 8
#define GLOBAL_CACHE_MASK 0x15
#define PER_CHARACTER_CACHE_MASK 0xEA
#define sWorldSocketMgr WorldSocketMgr::Instance()
Typedefs
typedef Opcodes OpcodeClient
typedef Opcodes OpcodeServer
Enumerations
enum Opcodes : uint16 {
CMSG_BOOTME = 0x001 ,
CMSG_DBLOOKUP = 0x002 ,
SMSG_DBLOOKUP = 0x003 ,
CMSG_QUERY_OBJECT_POSITION = 0x004 ,
SMSG_QUERY_OBJECT_POSITION = 0x005 ,
CMSG_QUERY_OBJECT_ROTATION = 0x006 ,
SMSG_QUERY_OBJECT_ROTATION = 0x007 ,
CMSG_WORLD_TELEPORT = 0x008 ,
CMSG_TELEPORT_TO_UNIT = 0x009 ,
CMSG_ZONE_MAP = 0x00A ,
SMSG_ZONE_MAP = 0x00B ,
CMSG_DEBUG_CHANGECELLZONE = 0x00C ,
CMSG_MOVE_CHARACTER_CHEAT = 0x00D ,
SMSG_MOVE_CHARACTER_CHEAT = 0x00E ,
CMSG_RECHARGE = 0x00F ,
CMSG_LEARN_SPELL = 0x010 ,
CMSG_CREATEMONSTER = 0x011 ,
CMSG_DESTROYMONSTER = 0x012 ,
CMSG_CREATEITEM = 0x013 ,
CMSG_CREATEGAMEOBJECT = 0x014 ,
SMSG_CHECK_FOR_BOTS = 0x015 ,
CMSG_MAKEMONSTERATTACKGUID = 0x016 ,
CMSG_BOT_DETECTED2 = 0x017 ,
CMSG_FORCEACTION = 0x018 ,
CMSG_FORCEACTIONONOTHER = 0x019 ,
CMSG_FORCEACTIONSHOW = 0x01A ,
SMSG_FORCEACTIONSHOW = 0x01B ,
CMSG_PETGODMODE = 0x01C ,
SMSG_PETGODMODE = 0x01D ,
SMSG_REFER_A_FRIEND_EXPIRED = 0x01E ,
CMSG_WEATHER_SPEED_CHEAT = 0x01F ,
CMSG_UNDRESSPLAYER = 0x020 ,
CMSG_BEASTMASTER = 0x021 ,
CMSG_GODMODE = 0x022 ,
SMSG_GODMODE = 0x023 ,
CMSG_CHEAT_SETMONEY = 0x024 ,
CMSG_LEVEL_CHEAT = 0x025 ,
CMSG_PET_LEVEL_CHEAT = 0x026 ,
CMSG_SET_WORLDSTATE = 0x027 ,
CMSG_COOLDOWN_CHEAT = 0x028 ,
CMSG_USE_SKILL_CHEAT = 0x029 ,
CMSG_FLAG_QUEST = 0x02A ,
CMSG_FLAG_QUEST_FINISH = 0x02B ,
CMSG_CLEAR_QUEST = 0x02C ,
CMSG_SEND_EVENT = 0x02D ,
CMSG_DEBUG_AISTATE = 0x02E ,
SMSG_DEBUG_AISTATE = 0x02F ,
CMSG_DISABLE_PVP_CHEAT = 0x030 ,
CMSG_ADVANCE_SPAWN_TIME = 0x031 ,
SMSG_DESTRUCTIBLE_BUILDING_DAMAGE = 0x032 ,
CMSG_AUTH_SRP6_BEGIN = 0x033 ,
CMSG_AUTH_SRP6_PROOF = 0x034 ,
CMSG_AUTH_SRP6_RECODE = 0x035 ,
CMSG_CHAR_CREATE = 0x036 ,
CMSG_CHAR_ENUM = 0x037 ,
CMSG_CHAR_DELETE = 0x038 ,
SMSG_AUTH_SRP6_RESPONSE = 0x039 ,
SMSG_CHAR_CREATE = 0x03A ,
SMSG_CHAR_ENUM = 0x03B ,
SMSG_CHAR_DELETE = 0x03C ,
CMSG_PLAYER_LOGIN = 0x03D ,
SMSG_NEW_WORLD = 0x03E ,
SMSG_TRANSFER_PENDING = 0x03F ,
SMSG_TRANSFER_ABORTED = 0x040 ,
SMSG_CHARACTER_LOGIN_FAILED = 0x041 ,
SMSG_LOGIN_SETTIMESPEED = 0x042 ,
SMSG_GAMETIME_UPDATE = 0x043 ,
CMSG_GAMETIME_SET = 0x044 ,
SMSG_GAMETIME_SET = 0x045 ,
CMSG_GAMESPEED_SET = 0x046 ,
SMSG_GAMESPEED_SET = 0x047 ,
CMSG_SERVERTIME = 0x048 ,
SMSG_SERVERTIME = 0x049 ,
CMSG_PLAYER_LOGOUT = 0x04A ,
CMSG_LOGOUT_REQUEST = 0x04B ,
SMSG_LOGOUT_RESPONSE = 0x04C ,
SMSG_LOGOUT_COMPLETE = 0x04D ,
CMSG_LOGOUT_CANCEL = 0x04E ,
SMSG_LOGOUT_CANCEL_ACK = 0x04F ,
CMSG_NAME_QUERY = 0x050 ,
SMSG_NAME_QUERY_RESPONSE = 0x051 ,
CMSG_PET_NAME_QUERY = 0x052 ,
SMSG_PET_NAME_QUERY_RESPONSE = 0x053 ,
CMSG_GUILD_QUERY = 0x054 ,
SMSG_GUILD_QUERY_RESPONSE = 0x055 ,
CMSG_ITEM_QUERY_SINGLE = 0x056 ,
CMSG_ITEM_QUERY_MULTIPLE = 0x057 ,
SMSG_ITEM_QUERY_SINGLE_RESPONSE = 0x058 ,
SMSG_ITEM_QUERY_MULTIPLE_RESPONSE = 0x059 ,
CMSG_PAGE_TEXT_QUERY = 0x05A ,
SMSG_PAGE_TEXT_QUERY_RESPONSE = 0x05B ,
CMSG_QUEST_QUERY = 0x05C ,
SMSG_QUEST_QUERY_RESPONSE = 0x05D ,
CMSG_GAMEOBJECT_QUERY = 0x05E ,
SMSG_GAMEOBJECT_QUERY_RESPONSE = 0x05F ,
CMSG_CREATURE_QUERY = 0x060 ,
SMSG_CREATURE_QUERY_RESPONSE = 0x061 ,
CMSG_WHO = 0x062 ,
SMSG_WHO = 0x063 ,
CMSG_WHOIS = 0x064 ,
SMSG_WHOIS = 0x065 ,
CMSG_CONTACT_LIST = 0x066 ,
SMSG_CONTACT_LIST = 0x067 ,
SMSG_FRIEND_STATUS = 0x068 ,
CMSG_ADD_FRIEND = 0x069 ,
CMSG_DEL_FRIEND = 0x06A ,
CMSG_SET_CONTACT_NOTES = 0x06B ,
CMSG_ADD_IGNORE = 0x06C ,
CMSG_DEL_IGNORE = 0x06D ,
CMSG_GROUP_INVITE = 0x06E ,
SMSG_GROUP_INVITE = 0x06F ,
CMSG_GROUP_CANCEL = 0x070 ,
SMSG_GROUP_CANCEL = 0x071 ,
CMSG_GROUP_ACCEPT = 0x072 ,
CMSG_GROUP_DECLINE = 0x073 ,
SMSG_GROUP_DECLINE = 0x074 ,
CMSG_GROUP_UNINVITE = 0x075 ,
CMSG_GROUP_UNINVITE_GUID = 0x076 ,
SMSG_GROUP_UNINVITE = 0x077 ,
CMSG_GROUP_SET_LEADER = 0x078 ,
SMSG_GROUP_SET_LEADER = 0x079 ,
CMSG_LOOT_METHOD = 0x07A ,
CMSG_GROUP_DISBAND = 0x07B ,
SMSG_GROUP_DESTROYED = 0x07C ,
SMSG_GROUP_LIST = 0x07D ,
SMSG_PARTY_MEMBER_STATS = 0x07E ,
SMSG_PARTY_COMMAND_RESULT = 0x07F ,
UMSG_UPDATE_GROUP_MEMBERS = 0x080 ,
CMSG_GUILD_CREATE = 0x081 ,
CMSG_GUILD_INVITE = 0x082 ,
SMSG_GUILD_INVITE = 0x083 ,
CMSG_GUILD_ACCEPT = 0x084 ,
CMSG_GUILD_DECLINE = 0x085 ,
SMSG_GUILD_DECLINE = 0x086 ,
CMSG_GUILD_INFO = 0x087 ,
SMSG_GUILD_INFO = 0x088 ,
CMSG_GUILD_ROSTER = 0x089 ,
SMSG_GUILD_ROSTER = 0x08A ,
CMSG_GUILD_PROMOTE = 0x08B ,
CMSG_GUILD_DEMOTE = 0x08C ,
CMSG_GUILD_LEAVE = 0x08D ,
CMSG_GUILD_REMOVE = 0x08E ,
CMSG_GUILD_DISBAND = 0x08F ,
CMSG_GUILD_LEADER = 0x090 ,
CMSG_GUILD_MOTD = 0x091 ,
SMSG_GUILD_EVENT = 0x092 ,
SMSG_GUILD_COMMAND_RESULT = 0x093 ,
UMSG_UPDATE_GUILD = 0x094 ,
CMSG_MESSAGECHAT = 0x095 ,
SMSG_MESSAGECHAT = 0x096 ,
CMSG_JOIN_CHANNEL = 0x097 ,
CMSG_LEAVE_CHANNEL = 0x098 ,
SMSG_CHANNEL_NOTIFY = 0x099 ,
CMSG_CHANNEL_LIST = 0x09A ,
SMSG_CHANNEL_LIST = 0x09B ,
CMSG_CHANNEL_PASSWORD = 0x09C ,
CMSG_CHANNEL_SET_OWNER = 0x09D ,
CMSG_CHANNEL_OWNER = 0x09E ,
CMSG_CHANNEL_MODERATOR = 0x09F ,
CMSG_CHANNEL_UNMODERATOR = 0x0A0 ,
CMSG_CHANNEL_MUTE = 0x0A1 ,
CMSG_CHANNEL_UNMUTE = 0x0A2 ,
CMSG_CHANNEL_INVITE = 0x0A3 ,
CMSG_CHANNEL_KICK = 0x0A4 ,
CMSG_CHANNEL_BAN = 0x0A5 ,
CMSG_CHANNEL_UNBAN = 0x0A6 ,
CMSG_CHANNEL_ANNOUNCEMENTS = 0x0A7 ,
CMSG_CHANNEL_MODERATE = 0x0A8 ,
SMSG_UPDATE_OBJECT = 0x0A9 ,
SMSG_DESTROY_OBJECT = 0x0AA ,
CMSG_USE_ITEM = 0x0AB ,
CMSG_OPEN_ITEM = 0x0AC ,
CMSG_READ_ITEM = 0x0AD ,
SMSG_READ_ITEM_OK = 0x0AE ,
SMSG_READ_ITEM_FAILED = 0x0AF ,
SMSG_ITEM_COOLDOWN = 0x0B0 ,
CMSG_GAMEOBJ_USE = 0x0B1 ,
CMSG_DESTROY_ITEMS = 0x0B2 ,
SMSG_GAMEOBJECT_CUSTOM_ANIM = 0x0B3 ,
CMSG_AREATRIGGER = 0x0B4 ,
MSG_MOVE_START_FORWARD = 0x0B5 ,
MSG_MOVE_START_BACKWARD = 0x0B6 ,
MSG_MOVE_STOP = 0x0B7 ,
MSG_MOVE_START_STRAFE_LEFT = 0x0B8 ,
MSG_MOVE_START_STRAFE_RIGHT = 0x0B9 ,
MSG_MOVE_STOP_STRAFE = 0x0BA ,
MSG_MOVE_JUMP = 0x0BB ,
MSG_MOVE_START_TURN_LEFT = 0x0BC ,
MSG_MOVE_START_TURN_RIGHT = 0x0BD ,
MSG_MOVE_STOP_TURN = 0x0BE ,
MSG_MOVE_START_PITCH_UP = 0x0BF ,
MSG_MOVE_START_PITCH_DOWN = 0x0C0 ,
MSG_MOVE_STOP_PITCH = 0x0C1 ,
MSG_MOVE_SET_RUN_MODE = 0x0C2 ,
MSG_MOVE_SET_WALK_MODE = 0x0C3 ,
MSG_MOVE_TOGGLE_LOGGING = 0x0C4 ,
MSG_MOVE_TELEPORT = 0x0C5 ,
MSG_MOVE_TELEPORT_CHEAT = 0x0C6 ,
MSG_MOVE_TELEPORT_ACK = 0x0C7 ,
MSG_MOVE_TOGGLE_FALL_LOGGING = 0x0C8 ,
MSG_MOVE_FALL_LAND = 0x0C9 ,
MSG_MOVE_START_SWIM = 0x0CA ,
MSG_MOVE_STOP_SWIM = 0x0CB ,
MSG_MOVE_SET_RUN_SPEED_CHEAT = 0x0CC ,
MSG_MOVE_SET_RUN_SPEED = 0x0CD ,
MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT = 0x0CE ,
MSG_MOVE_SET_RUN_BACK_SPEED = 0x0CF ,
MSG_MOVE_SET_WALK_SPEED_CHEAT = 0x0D0 ,
MSG_MOVE_SET_WALK_SPEED = 0x0D1 ,
MSG_MOVE_SET_SWIM_SPEED_CHEAT = 0x0D2 ,
MSG_MOVE_SET_SWIM_SPEED = 0x0D3 ,
MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT = 0x0D4 ,
MSG_MOVE_SET_SWIM_BACK_SPEED = 0x0D5 ,
MSG_MOVE_SET_ALL_SPEED_CHEAT = 0x0D6 ,
MSG_MOVE_SET_TURN_RATE_CHEAT = 0x0D7 ,
MSG_MOVE_SET_TURN_RATE = 0x0D8 ,
MSG_MOVE_TOGGLE_COLLISION_CHEAT = 0x0D9 ,
MSG_MOVE_SET_FACING = 0x0DA ,
MSG_MOVE_SET_PITCH = 0x0DB ,
MSG_MOVE_WORLDPORT_ACK = 0x0DC ,
SMSG_MONSTER_MOVE = 0x0DD ,
SMSG_MOVE_WATER_WALK = 0x0DE ,
SMSG_MOVE_LAND_WALK = 0x0DF ,
CMSG_MOVE_CHARM_PORT_CHEAT = 0x0E0 ,
CMSG_MOVE_SET_RAW_POSITION = 0x0E1 ,
SMSG_FORCE_RUN_SPEED_CHANGE = 0x0E2 ,
CMSG_FORCE_RUN_SPEED_CHANGE_ACK = 0x0E3 ,
SMSG_FORCE_RUN_BACK_SPEED_CHANGE = 0x0E4 ,
CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK = 0x0E5 ,
SMSG_FORCE_SWIM_SPEED_CHANGE = 0x0E6 ,
CMSG_FORCE_SWIM_SPEED_CHANGE_ACK = 0x0E7 ,
SMSG_FORCE_MOVE_ROOT = 0x0E8 ,
CMSG_FORCE_MOVE_ROOT_ACK = 0x0E9 ,
SMSG_FORCE_MOVE_UNROOT = 0x0EA ,
CMSG_FORCE_MOVE_UNROOT_ACK = 0x0EB ,
MSG_MOVE_ROOT = 0x0EC ,
MSG_MOVE_UNROOT = 0x0ED ,
MSG_MOVE_HEARTBEAT = 0x0EE ,
SMSG_MOVE_KNOCK_BACK = 0x0EF ,
CMSG_MOVE_KNOCK_BACK_ACK = 0x0F0 ,
MSG_MOVE_KNOCK_BACK = 0x0F1 ,
SMSG_MOVE_FEATHER_FALL = 0x0F2 ,
SMSG_MOVE_NORMAL_FALL = 0x0F3 ,
SMSG_MOVE_SET_HOVER = 0x0F4 ,
SMSG_MOVE_UNSET_HOVER = 0x0F5 ,
CMSG_MOVE_HOVER_ACK = 0x0F6 ,
MSG_MOVE_HOVER = 0x0F7 ,
CMSG_TRIGGER_CINEMATIC_CHEAT = 0x0F8 ,
CMSG_OPENING_CINEMATIC = 0x0F9 ,
SMSG_TRIGGER_CINEMATIC = 0x0FA ,
CMSG_NEXT_CINEMATIC_CAMERA = 0x0FB ,
CMSG_COMPLETE_CINEMATIC = 0x0FC ,
SMSG_TUTORIAL_FLAGS = 0x0FD ,
CMSG_TUTORIAL_FLAG = 0x0FE ,
CMSG_TUTORIAL_CLEAR = 0x0FF ,
CMSG_TUTORIAL_RESET = 0x100 ,
CMSG_STANDSTATECHANGE = 0x101 ,
CMSG_EMOTE = 0x102 ,
SMSG_EMOTE = 0x103 ,
CMSG_TEXT_EMOTE = 0x104 ,
SMSG_TEXT_EMOTE = 0x105 ,
CMSG_AUTOEQUIP_GROUND_ITEM = 0x106 ,
CMSG_AUTOSTORE_GROUND_ITEM = 0x107 ,
CMSG_AUTOSTORE_LOOT_ITEM = 0x108 ,
CMSG_STORE_LOOT_IN_SLOT = 0x109 ,
CMSG_AUTOEQUIP_ITEM = 0x10A ,
CMSG_AUTOSTORE_BAG_ITEM = 0x10B ,
CMSG_SWAP_ITEM = 0x10C ,
CMSG_SWAP_INV_ITEM = 0x10D ,
CMSG_SPLIT_ITEM = 0x10E ,
CMSG_AUTOEQUIP_ITEM_SLOT = 0x10F ,
CMSG_UNCLAIM_LICENSE = 0x110 ,
CMSG_DESTROYITEM = 0x111 ,
SMSG_INVENTORY_CHANGE_FAILURE = 0x112 ,
SMSG_OPEN_CONTAINER = 0x113 ,
CMSG_INSPECT = 0x114 ,
SMSG_INSPECT_RESULTS_UPDATE = 0x115 ,
CMSG_INITIATE_TRADE = 0x116 ,
CMSG_BEGIN_TRADE = 0x117 ,
CMSG_BUSY_TRADE = 0x118 ,
CMSG_IGNORE_TRADE = 0x119 ,
CMSG_ACCEPT_TRADE = 0x11A ,
CMSG_UNACCEPT_TRADE = 0x11B ,
CMSG_CANCEL_TRADE = 0x11C ,
CMSG_SET_TRADE_ITEM = 0x11D ,
CMSG_CLEAR_TRADE_ITEM = 0x11E ,
CMSG_SET_TRADE_GOLD = 0x11F ,
SMSG_TRADE_STATUS = 0x120 ,
SMSG_TRADE_STATUS_EXTENDED = 0x121 ,
SMSG_INITIALIZE_FACTIONS = 0x122 ,
SMSG_SET_FACTION_VISIBLE = 0x123 ,
SMSG_SET_FACTION_STANDING = 0x124 ,
CMSG_SET_FACTION_ATWAR = 0x125 ,
CMSG_SET_FACTION_CHEAT = 0x126 ,
SMSG_SET_PROFICIENCY = 0x127 ,
CMSG_SET_ACTION_BUTTON = 0x128 ,
SMSG_ACTION_BUTTONS = 0x129 ,
SMSG_INITIAL_SPELLS = 0x12A ,
SMSG_LEARNED_SPELL = 0x12B ,
SMSG_SUPERCEDED_SPELL = 0x12C ,
CMSG_NEW_SPELL_SLOT = 0x12D ,
CMSG_CAST_SPELL = 0x12E ,
CMSG_CANCEL_CAST = 0x12F ,
SMSG_CAST_FAILED = 0x130 ,
SMSG_SPELL_START = 0x131 ,
SMSG_SPELL_GO = 0x132 ,
SMSG_SPELL_FAILURE = 0x133 ,
SMSG_SPELL_COOLDOWN = 0x134 ,
SMSG_COOLDOWN_EVENT = 0x135 ,
CMSG_CANCEL_AURA = 0x136 ,
SMSG_EQUIPMENT_SET_SAVED = 0x137 ,
SMSG_PET_CAST_FAILED = 0x138 ,
MSG_CHANNEL_START = 0x139 ,
MSG_CHANNEL_UPDATE = 0x13A ,
CMSG_CANCEL_CHANNELLING = 0x13B ,
SMSG_AI_REACTION = 0x13C ,
CMSG_SET_SELECTION = 0x13D ,
CMSG_DELETEEQUIPMENT_SET = 0x13E ,
CMSG_INSTANCE_LOCK_RESPONSE = 0x13F ,
CMSG_DEBUG_PASSIVE_AURA = 0x140 ,
CMSG_ATTACKSWING = 0x141 ,
CMSG_ATTACKSTOP = 0x142 ,
SMSG_ATTACKSTART = 0x143 ,
SMSG_ATTACKSTOP = 0x144 ,
SMSG_ATTACKSWING_NOTINRANGE = 0x145 ,
SMSG_ATTACKSWING_BADFACING = 0x146 ,
SMSG_INSTANCE_LOCK_WARNING_QUERY = 0x147 ,
SMSG_ATTACKSWING_DEADTARGET = 0x148 ,
SMSG_ATTACKSWING_CANT_ATTACK = 0x149 ,
SMSG_ATTACKERSTATEUPDATE = 0x14A ,
SMSG_BATTLEFIELD_PORT_DENIED = 0x14B ,
CMSG_PERFORM_ACTION_SET = 0x14C ,
SMSG_RESUME_CAST_BAR = 0x14D ,
SMSG_CANCEL_COMBAT = 0x14E ,
SMSG_SPELLBREAKLOG = 0x14F ,
SMSG_SPELLHEALLOG = 0x150 ,
SMSG_SPELLENERGIZELOG = 0x151 ,
SMSG_BREAK_TARGET = 0x152 ,
CMSG_SAVE_PLAYER = 0x153 ,
CMSG_SETDEATHBINDPOINT = 0x154 ,
SMSG_BINDPOINTUPDATE = 0x155 ,
CMSG_GETDEATHBINDZONE = 0x156 ,
SMSG_BINDZONEREPLY = 0x157 ,
SMSG_PLAYERBOUND = 0x158 ,
SMSG_CLIENT_CONTROL_UPDATE = 0x159 ,
CMSG_REPOP_REQUEST = 0x15A ,
SMSG_RESURRECT_REQUEST = 0x15B ,
CMSG_RESURRECT_RESPONSE = 0x15C ,
CMSG_LOOT = 0x15D ,
CMSG_LOOT_MONEY = 0x15E ,
CMSG_LOOT_RELEASE = 0x15F ,
SMSG_LOOT_RESPONSE = 0x160 ,
SMSG_LOOT_RELEASE_RESPONSE = 0x161 ,
SMSG_LOOT_REMOVED = 0x162 ,
SMSG_LOOT_MONEY_NOTIFY = 0x163 ,
SMSG_LOOT_ITEM_NOTIFY = 0x164 ,
SMSG_LOOT_CLEAR_MONEY = 0x165 ,
SMSG_ITEM_PUSH_RESULT = 0x166 ,
SMSG_DUEL_REQUESTED = 0x167 ,
SMSG_DUEL_OUTOFBOUNDS = 0x168 ,
SMSG_DUEL_INBOUNDS = 0x169 ,
SMSG_DUEL_COMPLETE = 0x16A ,
SMSG_DUEL_WINNER = 0x16B ,
CMSG_DUEL_ACCEPTED = 0x16C ,
CMSG_DUEL_CANCELLED = 0x16D ,
SMSG_MOUNTRESULT = 0x16E ,
SMSG_DISMOUNTRESULT = 0x16F ,
SMSG_REMOVED_FROM_PVP_QUEUE = 0x170 ,
CMSG_MOUNTSPECIAL_ANIM = 0x171 ,
SMSG_MOUNTSPECIAL_ANIM = 0x172 ,
SMSG_PET_TAME_FAILURE = 0x173 ,
CMSG_PET_SET_ACTION = 0x174 ,
CMSG_PET_ACTION = 0x175 ,
CMSG_PET_ABANDON = 0x176 ,
CMSG_PET_RENAME = 0x177 ,
SMSG_PET_NAME_INVALID = 0x178 ,
SMSG_PET_SPELLS = 0x179 ,
SMSG_PET_MODE = 0x17A ,
CMSG_GOSSIP_HELLO = 0x17B ,
CMSG_GOSSIP_SELECT_OPTION = 0x17C ,
SMSG_GOSSIP_MESSAGE = 0x17D ,
SMSG_GOSSIP_COMPLETE = 0x17E ,
CMSG_NPC_TEXT_QUERY = 0x17F ,
SMSG_NPC_TEXT_UPDATE = 0x180 ,
SMSG_NPC_WONT_TALK = 0x181 ,
CMSG_QUESTGIVER_STATUS_QUERY = 0x182 ,
SMSG_QUESTGIVER_STATUS = 0x183 ,
CMSG_QUESTGIVER_HELLO = 0x184 ,
SMSG_QUESTGIVER_QUEST_LIST = 0x185 ,
CMSG_QUESTGIVER_QUERY_QUEST = 0x186 ,
CMSG_QUESTGIVER_QUEST_AUTOLAUNCH = 0x187 ,
SMSG_QUESTGIVER_QUEST_DETAILS = 0x188 ,
CMSG_QUESTGIVER_ACCEPT_QUEST = 0x189 ,
CMSG_QUESTGIVER_COMPLETE_QUEST = 0x18A ,
SMSG_QUESTGIVER_REQUEST_ITEMS = 0x18B ,
CMSG_QUESTGIVER_REQUEST_REWARD = 0x18C ,
SMSG_QUESTGIVER_OFFER_REWARD = 0x18D ,
CMSG_QUESTGIVER_CHOOSE_REWARD = 0x18E ,
SMSG_QUESTGIVER_QUEST_INVALID = 0x18F ,
CMSG_QUESTGIVER_CANCEL = 0x190 ,
SMSG_QUESTGIVER_QUEST_COMPLETE = 0x191 ,
SMSG_QUESTGIVER_QUEST_FAILED = 0x192 ,
CMSG_QUESTLOG_SWAP_QUEST = 0x193 ,
CMSG_QUESTLOG_REMOVE_QUEST = 0x194 ,
SMSG_QUESTLOG_FULL = 0x195 ,
SMSG_QUESTUPDATE_FAILED = 0x196 ,
SMSG_QUESTUPDATE_FAILEDTIMER = 0x197 ,
SMSG_QUESTUPDATE_COMPLETE = 0x198 ,
SMSG_QUESTUPDATE_ADD_KILL = 0x199 ,
SMSG_QUESTUPDATE_ADD_ITEM = 0x19A ,
CMSG_QUEST_CONFIRM_ACCEPT = 0x19B ,
SMSG_QUEST_CONFIRM_ACCEPT = 0x19C ,
CMSG_PUSHQUESTTOPARTY = 0x19D ,
CMSG_LIST_INVENTORY = 0x19E ,
SMSG_LIST_INVENTORY = 0x19F ,
CMSG_SELL_ITEM = 0x1A0 ,
SMSG_SELL_ITEM = 0x1A1 ,
CMSG_BUY_ITEM = 0x1A2 ,
CMSG_BUY_ITEM_IN_SLOT = 0x1A3 ,
SMSG_BUY_ITEM = 0x1A4 ,
SMSG_BUY_FAILED = 0x1A5 ,
CMSG_TAXICLEARALLNODES = 0x1A6 ,
CMSG_TAXIENABLEALLNODES = 0x1A7 ,
CMSG_TAXISHOWNODES = 0x1A8 ,
SMSG_SHOWTAXINODES = 0x1A9 ,
CMSG_TAXINODE_STATUS_QUERY = 0x1AA ,
SMSG_TAXINODE_STATUS = 0x1AB ,
CMSG_TAXIQUERYAVAILABLENODES = 0x1AC ,
CMSG_ACTIVATETAXI = 0x1AD ,
SMSG_ACTIVATETAXIREPLY = 0x1AE ,
SMSG_NEW_TAXI_PATH = 0x1AF ,
CMSG_TRAINER_LIST = 0x1B0 ,
SMSG_TRAINER_LIST = 0x1B1 ,
CMSG_TRAINER_BUY_SPELL = 0x1B2 ,
SMSG_TRAINER_BUY_SUCCEEDED = 0x1B3 ,
SMSG_TRAINER_BUY_FAILED = 0x1B4 ,
CMSG_BINDER_ACTIVATE = 0x1B5 ,
SMSG_PLAYERBINDERROR = 0x1B6 ,
CMSG_BANKER_ACTIVATE = 0x1B7 ,
SMSG_SHOW_BANK = 0x1B8 ,
CMSG_BUY_BANK_SLOT = 0x1B9 ,
SMSG_BUY_BANK_SLOT_RESULT = 0x1BA ,
CMSG_PETITION_SHOWLIST = 0x1BB ,
SMSG_PETITION_SHOWLIST = 0x1BC ,
CMSG_PETITION_BUY = 0x1BD ,
CMSG_PETITION_SHOW_SIGNATURES = 0x1BE ,
SMSG_PETITION_SHOW_SIGNATURES = 0x1BF ,
CMSG_PETITION_SIGN = 0x1C0 ,
SMSG_PETITION_SIGN_RESULTS = 0x1C1 ,
MSG_PETITION_DECLINE = 0x1C2 ,
CMSG_OFFER_PETITION = 0x1C3 ,
CMSG_TURN_IN_PETITION = 0x1C4 ,
SMSG_TURN_IN_PETITION_RESULTS = 0x1C5 ,
CMSG_PETITION_QUERY = 0x1C6 ,
SMSG_PETITION_QUERY_RESPONSE = 0x1C7 ,
SMSG_FISH_NOT_HOOKED = 0x1C8 ,
SMSG_FISH_ESCAPED = 0x1C9 ,
CMSG_BUG = 0x1CA ,
SMSG_NOTIFICATION = 0x1CB ,
CMSG_PLAYED_TIME = 0x1CC ,
SMSG_PLAYED_TIME = 0x1CD ,
CMSG_QUERY_TIME = 0x1CE ,
SMSG_QUERY_TIME_RESPONSE = 0x1CF ,
SMSG_LOG_XPGAIN = 0x1D0 ,
SMSG_AURACASTLOG = 0x1D1 ,
CMSG_RECLAIM_CORPSE = 0x1D2 ,
CMSG_WRAP_ITEM = 0x1D3 ,
SMSG_LEVELUP_INFO = 0x1D4 ,
MSG_MINIMAP_PING = 0x1D5 ,
SMSG_RESISTLOG = 0x1D6 ,
SMSG_ENCHANTMENTLOG = 0x1D7 ,
CMSG_SET_SKILL_CHEAT = 0x1D8 ,
SMSG_START_MIRROR_TIMER = 0x1D9 ,
SMSG_PAUSE_MIRROR_TIMER = 0x1DA ,
SMSG_STOP_MIRROR_TIMER = 0x1DB ,
CMSG_PING = 0x1DC ,
SMSG_PONG = 0x1DD ,
SMSG_CLEAR_COOLDOWN = 0x1DE ,
SMSG_GAMEOBJECT_PAGETEXT = 0x1DF ,
CMSG_SET_SHEATHED = 0x1E0 ,
SMSG_COOLDOWN_CHEAT = 0x1E1 ,
SMSG_SPELL_DELAYED = 0x1E2 ,
CMSG_QUEST_POI_QUERY = 0x1E3 ,
SMSG_QUEST_POI_QUERY_RESPONSE = 0x1E4 ,
CMSG_GHOST = 0x1E5 ,
CMSG_GM_INVIS = 0x1E6 ,
SMSG_INVALID_PROMOTION_CODE = 0x1E7 ,
MSG_GM_BIND_OTHER = 0x1E8 ,
MSG_GM_SUMMON = 0x1E9 ,
SMSG_ITEM_TIME_UPDATE = 0x1EA ,
SMSG_ITEM_ENCHANT_TIME_UPDATE = 0x1EB ,
SMSG_AUTH_CHALLENGE = 0x1EC ,
CMSG_AUTH_SESSION = 0x1ED ,
SMSG_AUTH_RESPONSE = 0x1EE ,
MSG_GM_SHOWLABEL = 0x1EF ,
CMSG_PET_CAST_SPELL = 0x1F0 ,
MSG_SAVE_GUILD_EMBLEM = 0x1F1 ,
MSG_TABARDVENDOR_ACTIVATE = 0x1F2 ,
SMSG_PLAY_SPELL_VISUAL = 0x1F3 ,
CMSG_ZONEUPDATE = 0x1F4 ,
SMSG_PARTYKILLLOG = 0x1F5 ,
SMSG_COMPRESSED_UPDATE_OBJECT = 0x1F6 ,
SMSG_PLAY_SPELL_IMPACT = 0x1F7 ,
SMSG_EXPLORATION_EXPERIENCE = 0x1F8 ,
CMSG_GM_SET_SECURITY_GROUP = 0x1F9 ,
CMSG_GM_NUKE = 0x1FA ,
MSG_RANDOM_ROLL = 0x1FB ,
SMSG_ENVIRONMENTAL_DAMAGE_LOG = 0x1FC ,
CMSG_CHANGEPLAYER_DIFFICULTY = 0x1FD ,
SMSG_RWHOIS = 0x1FE ,
SMSG_LFG_PLAYER_REWARD = 0x1FF ,
SMSG_LFG_TELEPORT_DENIED = 0x200 ,
CMSG_UNLEARN_SPELL = 0x201 ,
CMSG_UNLEARN_SKILL = 0x202 ,
SMSG_REMOVED_SPELL = 0x203 ,
CMSG_DECHARGE = 0x204 ,
CMSG_GMTICKET_CREATE = 0x205 ,
SMSG_GMTICKET_CREATE = 0x206 ,
CMSG_GMTICKET_UPDATETEXT = 0x207 ,
SMSG_GMTICKET_UPDATETEXT = 0x208 ,
SMSG_ACCOUNT_DATA_TIMES = 0x209 ,
CMSG_REQUEST_ACCOUNT_DATA = 0x20A ,
CMSG_UPDATE_ACCOUNT_DATA = 0x20B ,
SMSG_UPDATE_ACCOUNT_DATA = 0x20C ,
SMSG_CLEAR_FAR_SIGHT_IMMEDIATE = 0x20D ,
SMSG_CHANGEPLAYER_DIFFICULTY_RESULT = 0x20E ,
CMSG_GM_TEACH = 0x20F ,
CMSG_GM_CREATE_ITEM_TARGET = 0x210 ,
CMSG_GMTICKET_GETTICKET = 0x211 ,
SMSG_GMTICKET_GETTICKET = 0x212 ,
CMSG_UNLEARN_TALENTS = 0x213 ,
SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT = 0x214 ,
SMSG_GAMEOBJECT_DESPAWN_ANIM = 0x215 ,
MSG_CORPSE_QUERY = 0x216 ,
CMSG_GMTICKET_DELETETICKET = 0x217 ,
SMSG_GMTICKET_DELETETICKET = 0x218 ,
SMSG_CHAT_WRONG_FACTION = 0x219 ,
CMSG_GMTICKET_SYSTEMSTATUS = 0x21A ,
SMSG_GMTICKET_SYSTEMSTATUS = 0x21B ,
CMSG_SPIRIT_HEALER_ACTIVATE = 0x21C ,
CMSG_SET_STAT_CHEAT = 0x21D ,
SMSG_QUEST_FORCE_REMOVE = 0x21E ,
CMSG_SKILL_BUY_STEP = 0x21F ,
CMSG_SKILL_BUY_RANK = 0x220 ,
CMSG_XP_CHEAT = 0x221 ,
SMSG_SPIRIT_HEALER_CONFIRM = 0x222 ,
CMSG_CHARACTER_POINT_CHEAT = 0x223 ,
SMSG_GOSSIP_POI = 0x224 ,
CMSG_CHAT_IGNORED = 0x225 ,
CMSG_GM_VISION = 0x226 ,
CMSG_SERVER_COMMAND = 0x227 ,
CMSG_GM_SILENCE = 0x228 ,
CMSG_GM_REVEALTO = 0x229 ,
CMSG_GM_RESURRECT = 0x22A ,
CMSG_GM_SUMMONMOB = 0x22B ,
CMSG_GM_MOVECORPSE = 0x22C ,
CMSG_GM_FREEZE = 0x22D ,
CMSG_GM_UBERINVIS = 0x22E ,
CMSG_GM_REQUEST_PLAYER_INFO = 0x22F ,
SMSG_GM_PLAYER_INFO = 0x230 ,
CMSG_GUILD_RANK = 0x231 ,
CMSG_GUILD_ADD_RANK = 0x232 ,
CMSG_GUILD_DEL_RANK = 0x233 ,
CMSG_GUILD_SET_PUBLIC_NOTE = 0x234 ,
CMSG_GUILD_SET_OFFICER_NOTE = 0x235 ,
SMSG_LOGIN_VERIFY_WORLD = 0x236 ,
CMSG_CLEAR_EXPLORATION = 0x237 ,
CMSG_SEND_MAIL = 0x238 ,
SMSG_SEND_MAIL_RESULT = 0x239 ,
CMSG_GET_MAIL_LIST = 0x23A ,
SMSG_MAIL_LIST_RESULT = 0x23B ,
CMSG_BATTLEFIELD_LIST = 0x23C ,
SMSG_BATTLEFIELD_LIST = 0x23D ,
CMSG_BATTLEFIELD_JOIN = 0x23E ,
SMSG_FORCE_SET_VEHICLE_REC_ID = 0x23F ,
CMSG_SET_VEHICLE_REC_ID_ACK = 0x240 ,
CMSG_TAXICLEARNODE = 0x241 ,
CMSG_TAXIENABLENODE = 0x242 ,
CMSG_ITEM_TEXT_QUERY = 0x243 ,
SMSG_ITEM_TEXT_QUERY_RESPONSE = 0x244 ,
CMSG_MAIL_TAKE_MONEY = 0x245 ,
CMSG_MAIL_TAKE_ITEM = 0x246 ,
CMSG_MAIL_MARK_AS_READ = 0x247 ,
CMSG_MAIL_RETURN_TO_SENDER = 0x248 ,
CMSG_MAIL_DELETE = 0x249 ,
CMSG_MAIL_CREATE_TEXT_ITEM = 0x24A ,
SMSG_SPELLLOGMISS = 0x24B ,
SMSG_SPELLLOGEXECUTE = 0x24C ,
SMSG_DEBUGAURAPROC = 0x24D ,
SMSG_PERIODICAURALOG = 0x24E ,
SMSG_SPELLDAMAGESHIELD = 0x24F ,
SMSG_SPELLNONMELEEDAMAGELOG = 0x250 ,
CMSG_LEARN_TALENT = 0x251 ,
SMSG_RESURRECT_FAILED = 0x252 ,
CMSG_TOGGLE_PVP = 0x253 ,
SMSG_ZONE_UNDER_ATTACK = 0x254 ,
MSG_AUCTION_HELLO = 0x255 ,
CMSG_AUCTION_SELL_ITEM = 0x256 ,
CMSG_AUCTION_REMOVE_ITEM = 0x257 ,
CMSG_AUCTION_LIST_ITEMS = 0x258 ,
CMSG_AUCTION_LIST_OWNER_ITEMS = 0x259 ,
CMSG_AUCTION_PLACE_BID = 0x25A ,
SMSG_AUCTION_COMMAND_RESULT = 0x25B ,
SMSG_AUCTION_LIST_RESULT = 0x25C ,
SMSG_AUCTION_OWNER_LIST_RESULT = 0x25D ,
SMSG_AUCTION_BIDDER_NOTIFICATION = 0x25E ,
SMSG_AUCTION_OWNER_NOTIFICATION = 0x25F ,
SMSG_PROCRESIST = 0x260 ,
SMSG_COMBAT_EVENT_FAILED = 0x261 ,
SMSG_DISPEL_FAILED = 0x262 ,
SMSG_SPELLORDAMAGE_IMMUNE = 0x263 ,
CMSG_AUCTION_LIST_BIDDER_ITEMS = 0x264 ,
SMSG_AUCTION_BIDDER_LIST_RESULT = 0x265 ,
SMSG_SET_FLAT_SPELL_MODIFIER = 0x266 ,
SMSG_SET_PCT_SPELL_MODIFIER = 0x267 ,
CMSG_SET_AMMO = 0x268 ,
SMSG_CORPSE_RECLAIM_DELAY = 0x269 ,
CMSG_SET_ACTIVE_MOVER = 0x26A ,
CMSG_PET_CANCEL_AURA = 0x26B ,
CMSG_PLAYER_AI_CHEAT = 0x26C ,
CMSG_CANCEL_AUTO_REPEAT_SPELL = 0x26D ,
MSG_GM_ACCOUNT_ONLINE = 0x26E ,
MSG_LIST_STABLED_PETS = 0x26F ,
CMSG_STABLE_PET = 0x270 ,
CMSG_UNSTABLE_PET = 0x271 ,
CMSG_BUY_STABLE_SLOT = 0x272 ,
SMSG_STABLE_RESULT = 0x273 ,
CMSG_STABLE_REVIVE_PET = 0x274 ,
CMSG_STABLE_SWAP_PET = 0x275 ,
MSG_QUEST_PUSH_RESULT = 0x276 ,
SMSG_PLAY_MUSIC = 0x277 ,
SMSG_PLAY_OBJECT_SOUND = 0x278 ,
CMSG_REQUEST_PET_INFO = 0x279 ,
CMSG_FAR_SIGHT = 0x27A ,
SMSG_SPELLDISPELLOG = 0x27B ,
SMSG_DAMAGE_CALC_LOG = 0x27C ,
CMSG_ENABLE_DAMAGE_LOG = 0x27D ,
CMSG_GROUP_CHANGE_SUB_GROUP = 0x27E ,
CMSG_REQUEST_PARTY_MEMBER_STATS = 0x27F ,
CMSG_GROUP_SWAP_SUB_GROUP = 0x280 ,
CMSG_RESET_FACTION_CHEAT = 0x281 ,
CMSG_AUTOSTORE_BANK_ITEM = 0x282 ,
CMSG_AUTOBANK_ITEM = 0x283 ,
MSG_QUERY_NEXT_MAIL_TIME = 0x284 ,
SMSG_RECEIVED_MAIL = 0x285 ,
SMSG_RAID_GROUP_ONLY = 0x286 ,
CMSG_SET_DURABILITY_CHEAT = 0x287 ,
CMSG_SET_PVP_RANK_CHEAT = 0x288 ,
CMSG_ADD_PVP_MEDAL_CHEAT = 0x289 ,
CMSG_DEL_PVP_MEDAL_CHEAT = 0x28A ,
CMSG_SET_PVP_TITLE = 0x28B ,
SMSG_PVP_CREDIT = 0x28C ,
SMSG_AUCTION_REMOVED_NOTIFICATION = 0x28D ,
CMSG_GROUP_RAID_CONVERT = 0x28E ,
CMSG_GROUP_ASSISTANT_LEADER = 0x28F ,
CMSG_BUYBACK_ITEM = 0x290 ,
SMSG_CHAT_SERVER_MESSAGE = 0x291 ,
CMSG_SET_SAVED_INSTANCE_EXTEND = 0x292 ,
SMSG_LFG_OFFER_CONTINUE = 0x293 ,
CMSG_TEST_DROP_RATE = 0x294 ,
SMSG_TEST_DROP_RATE_RESULT = 0x295 ,
CMSG_LFG_GET_STATUS = 0x296 ,
SMSG_SHOW_MAILBOX = 0x297 ,
SMSG_RESET_RANGED_COMBAT_TIMER = 0x298 ,
SMSG_CHAT_NOT_IN_PARTY = 0x299 ,
CMSG_GMTICKETSYSTEM_TOGGLE = 0x29A ,
CMSG_CANCEL_GROWTH_AURA = 0x29B ,
SMSG_CANCEL_AUTO_REPEAT = 0x29C ,
SMSG_STANDSTATE_UPDATE = 0x29D ,
SMSG_LOOT_ALL_PASSED = 0x29E ,
SMSG_LOOT_ROLL_WON = 0x29F ,
CMSG_LOOT_ROLL = 0x2A0 ,
SMSG_LOOT_START_ROLL = 0x2A1 ,
SMSG_LOOT_ROLL = 0x2A2 ,
CMSG_LOOT_MASTER_GIVE = 0x2A3 ,
SMSG_LOOT_MASTER_LIST = 0x2A4 ,
SMSG_SET_FORCED_REACTIONS = 0x2A5 ,
SMSG_SPELL_FAILED_OTHER = 0x2A6 ,
SMSG_GAMEOBJECT_RESET_STATE = 0x2A7 ,
CMSG_REPAIR_ITEM = 0x2A8 ,
SMSG_CHAT_PLAYER_NOT_FOUND = 0x2A9 ,
MSG_TALENT_WIPE_CONFIRM = 0x2AA ,
SMSG_SUMMON_REQUEST = 0x2AB ,
CMSG_SUMMON_RESPONSE = 0x2AC ,
MSG_DEV_SHOWLABEL = 0x2AD ,
SMSG_MONSTER_MOVE_TRANSPORT = 0x2AE ,
SMSG_PET_BROKEN = 0x2AF ,
MSG_MOVE_FEATHER_FALL = 0x2B0 ,
MSG_MOVE_WATER_WALK = 0x2B1 ,
CMSG_SERVER_BROADCAST = 0x2B2 ,
CMSG_SELF_RES = 0x2B3 ,
SMSG_FEIGN_DEATH_RESISTED = 0x2B4 ,
CMSG_RUN_SCRIPT = 0x2B5 ,
SMSG_SCRIPT_MESSAGE = 0x2B6 ,
SMSG_DUEL_COUNTDOWN = 0x2B7 ,
SMSG_AREA_TRIGGER_MESSAGE = 0x2B8 ,
CMSG_SHOWING_HELM = 0x2B9 ,
CMSG_SHOWING_CLOAK = 0x2BA ,
SMSG_LFG_ROLE_CHOSEN = 0x2BB ,
SMSG_PLAYER_SKINNED = 0x2BC ,
SMSG_DURABILITY_DAMAGE_DEATH = 0x2BD ,
CMSG_SET_EXPLORATION = 0x2BE ,
CMSG_SET_ACTIONBAR_TOGGLES = 0x2BF ,
UMSG_DELETE_GUILD_CHARTER = 0x2C0 ,
MSG_PETITION_RENAME = 0x2C1 ,
SMSG_INIT_WORLD_STATES = 0x2C2 ,
SMSG_UPDATE_WORLD_STATE = 0x2C3 ,
CMSG_ITEM_NAME_QUERY = 0x2C4 ,
SMSG_ITEM_NAME_QUERY_RESPONSE = 0x2C5 ,
SMSG_PET_ACTION_FEEDBACK = 0x2C6 ,
CMSG_CHAR_RENAME = 0x2C7 ,
SMSG_CHAR_RENAME = 0x2C8 ,
CMSG_MOVE_SPLINE_DONE = 0x2C9 ,
CMSG_MOVE_FALL_RESET = 0x2CA ,
SMSG_INSTANCE_SAVE_CREATED = 0x2CB ,
SMSG_RAID_INSTANCE_INFO = 0x2CC ,
CMSG_REQUEST_RAID_INFO = 0x2CD ,
CMSG_MOVE_TIME_SKIPPED = 0x2CE ,
CMSG_MOVE_FEATHER_FALL_ACK = 0x2CF ,
CMSG_MOVE_WATER_WALK_ACK = 0x2D0 ,
CMSG_MOVE_NOT_ACTIVE_MOVER = 0x2D1 ,
SMSG_PLAY_SOUND = 0x2D2 ,
CMSG_BATTLEFIELD_STATUS = 0x2D3 ,
SMSG_BATTLEFIELD_STATUS = 0x2D4 ,
CMSG_BATTLEFIELD_PORT = 0x2D5 ,
MSG_INSPECT_HONOR_STATS = 0x2D6 ,
CMSG_BATTLEMASTER_HELLO = 0x2D7 ,
CMSG_MOVE_START_SWIM_CHEAT = 0x2D8 ,
CMSG_MOVE_STOP_SWIM_CHEAT = 0x2D9 ,
SMSG_FORCE_WALK_SPEED_CHANGE = 0x2DA ,
CMSG_FORCE_WALK_SPEED_CHANGE_ACK = 0x2DB ,
SMSG_FORCE_SWIM_BACK_SPEED_CHANGE = 0x2DC ,
CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK = 0x2DD ,
SMSG_FORCE_TURN_RATE_CHANGE = 0x2DE ,
CMSG_FORCE_TURN_RATE_CHANGE_ACK = 0x2DF ,
MSG_PVP_LOG_DATA = 0x2E0 ,
CMSG_LEAVE_BATTLEFIELD = 0x2E1 ,
CMSG_AREA_SPIRIT_HEALER_QUERY = 0x2E2 ,
CMSG_AREA_SPIRIT_HEALER_QUEUE = 0x2E3 ,
SMSG_AREA_SPIRIT_HEALER_TIME = 0x2E4 ,
CMSG_GM_UNTEACH = 0x2E5 ,
SMSG_WARDEN_DATA = 0x2E6 ,
CMSG_WARDEN_DATA = 0x2E7 ,
SMSG_GROUP_JOINED_BATTLEGROUND = 0x2E8 ,
MSG_BATTLEGROUND_PLAYER_POSITIONS = 0x2E9 ,
CMSG_PET_STOP_ATTACK = 0x2EA ,
SMSG_BINDER_CONFIRM = 0x2EB ,
SMSG_BATTLEGROUND_PLAYER_JOINED = 0x2EC ,
SMSG_BATTLEGROUND_PLAYER_LEFT = 0x2ED ,
CMSG_BATTLEMASTER_JOIN = 0x2EE ,
SMSG_ADDON_INFO = 0x2EF ,
CMSG_PET_UNLEARN = 0x2F0 ,
SMSG_PET_UNLEARN_CONFIRM = 0x2F1 ,
SMSG_PARTY_MEMBER_STATS_FULL = 0x2F2 ,
CMSG_PET_SPELL_AUTOCAST = 0x2F3 ,
SMSG_WEATHER = 0x2F4 ,
SMSG_PLAY_TIME_WARNING = 0x2F5 ,
SMSG_MINIGAME_SETUP = 0x2F6 ,
SMSG_MINIGAME_STATE = 0x2F7 ,
CMSG_MINIGAME_MOVE = 0x2F8 ,
SMSG_MINIGAME_MOVE_FAILED = 0x2F9 ,
SMSG_RAID_INSTANCE_MESSAGE = 0x2FA ,
SMSG_COMPRESSED_MOVES = 0x2FB ,
CMSG_GUILD_INFO_TEXT = 0x2FC ,
SMSG_CHAT_RESTRICTED = 0x2FD ,
SMSG_SPLINE_SET_RUN_SPEED = 0x2FE ,
SMSG_SPLINE_SET_RUN_BACK_SPEED = 0x2FF ,
SMSG_SPLINE_SET_SWIM_SPEED = 0x300 ,
SMSG_SPLINE_SET_WALK_SPEED = 0x301 ,
SMSG_SPLINE_SET_SWIM_BACK_SPEED = 0x302 ,
SMSG_SPLINE_SET_TURN_RATE = 0x303 ,
SMSG_SPLINE_MOVE_UNROOT = 0x304 ,
SMSG_SPLINE_MOVE_FEATHER_FALL = 0x305 ,
SMSG_SPLINE_MOVE_NORMAL_FALL = 0x306 ,
SMSG_SPLINE_MOVE_SET_HOVER = 0x307 ,
SMSG_SPLINE_MOVE_UNSET_HOVER = 0x308 ,
SMSG_SPLINE_MOVE_WATER_WALK = 0x309 ,
SMSG_SPLINE_MOVE_LAND_WALK = 0x30A ,
SMSG_SPLINE_MOVE_START_SWIM = 0x30B ,
SMSG_SPLINE_MOVE_STOP_SWIM = 0x30C ,
SMSG_SPLINE_MOVE_SET_RUN_MODE = 0x30D ,
SMSG_SPLINE_MOVE_SET_WALK_MODE = 0x30E ,
CMSG_GM_NUKE_ACCOUNT = 0x30F ,
MSG_GM_DESTROY_CORPSE = 0x310 ,
CMSG_GM_DESTROY_ONLINE_CORPSE = 0x311 ,
CMSG_ACTIVATETAXIEXPRESS = 0x312 ,
SMSG_SET_FACTION_ATWAR = 0x313 ,
SMSG_GAMETIMEBIAS_SET = 0x314 ,
CMSG_DEBUG_ACTIONS_START = 0x315 ,
CMSG_DEBUG_ACTIONS_STOP = 0x316 ,
CMSG_SET_FACTION_INACTIVE = 0x317 ,
CMSG_SET_WATCHED_FACTION = 0x318 ,
MSG_MOVE_TIME_SKIPPED = 0x319 ,
SMSG_SPLINE_MOVE_ROOT = 0x31A ,
CMSG_SET_EXPLORATION_ALL = 0x31B ,
SMSG_INVALIDATE_PLAYER = 0x31C ,
CMSG_RESET_INSTANCES = 0x31D ,
SMSG_INSTANCE_RESET = 0x31E ,
SMSG_INSTANCE_RESET_FAILED = 0x31F ,
SMSG_UPDATE_LAST_INSTANCE = 0x320 ,
MSG_RAID_TARGET_UPDATE = 0x321 ,
MSG_RAID_READY_CHECK = 0x322 ,
CMSG_LUA_USAGE = 0x323 ,
SMSG_PET_ACTION_SOUND = 0x324 ,
SMSG_PET_DISMISS_SOUND = 0x325 ,
SMSG_GHOSTEE_GONE = 0x326 ,
CMSG_GM_UPDATE_TICKET_STATUS = 0x327 ,
SMSG_GM_TICKET_STATUS_UPDATE = 0x328 ,
MSG_SET_DUNGEON_DIFFICULTY = 0x329 ,
CMSG_GMSURVEY_SUBMIT = 0x32A ,
SMSG_UPDATE_INSTANCE_OWNERSHIP = 0x32B ,
CMSG_IGNORE_KNOCKBACK_CHEAT = 0x32C ,
SMSG_CHAT_PLAYER_AMBIGUOUS = 0x32D ,
MSG_DELAY_GHOST_TELEPORT = 0x32E ,
SMSG_SPELLINSTAKILLLOG = 0x32F ,
SMSG_SPELL_UPDATE_CHAIN_TARGETS = 0x330 ,
CMSG_CHAT_FILTERED = 0x331 ,
SMSG_EXPECTED_SPAM_RECORDS = 0x332 ,
SMSG_SPELLSTEALLOG = 0x333 ,
CMSG_LOTTERY_QUERY_OBSOLETE = 0x334 ,
SMSG_LOTTERY_QUERY_RESULT_OBSOLETE = 0x335 ,
CMSG_BUY_LOTTERY_TICKET_OBSOLETE = 0x336 ,
SMSG_LOTTERY_RESULT_OBSOLETE = 0x337 ,
SMSG_CHARACTER_PROFILE = 0x338 ,
SMSG_CHARACTER_PROFILE_REALM_CONNECTED = 0x339 ,
SMSG_DEFENSE_MESSAGE = 0x33A ,
SMSG_INSTANCE_DIFFICULTY = 0x33B ,
MSG_GM_RESETINSTANCELIMIT = 0x33C ,
SMSG_MOTD = 0x33D ,
SMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY = 0x33E ,
SMSG_MOVE_UNSET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY = 0x33F ,
CMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY_ACK = 0x340 ,
MSG_MOVE_START_SWIM_CHEAT = 0x341 ,
MSG_MOVE_STOP_SWIM_CHEAT = 0x342 ,
SMSG_MOVE_SET_CAN_FLY = 0x343 ,
SMSG_MOVE_UNSET_CAN_FLY = 0x344 ,
CMSG_MOVE_SET_CAN_FLY_ACK = 0x345 ,
CMSG_MOVE_SET_FLY = 0x346 ,
CMSG_SOCKET_GEMS = 0x347 ,
CMSG_ARENA_TEAM_CREATE = 0x348 ,
SMSG_ARENA_TEAM_COMMAND_RESULT = 0x349 ,
MSG_MOVE_UPDATE_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY = 0x34A ,
CMSG_ARENA_TEAM_QUERY = 0x34B ,
SMSG_ARENA_TEAM_QUERY_RESPONSE = 0x34C ,
CMSG_ARENA_TEAM_ROSTER = 0x34D ,
SMSG_ARENA_TEAM_ROSTER = 0x34E ,
CMSG_ARENA_TEAM_INVITE = 0x34F ,
SMSG_ARENA_TEAM_INVITE = 0x350 ,
CMSG_ARENA_TEAM_ACCEPT = 0x351 ,
CMSG_ARENA_TEAM_DECLINE = 0x352 ,
CMSG_ARENA_TEAM_LEAVE = 0x353 ,
CMSG_ARENA_TEAM_REMOVE = 0x354 ,
CMSG_ARENA_TEAM_DISBAND = 0x355 ,
CMSG_ARENA_TEAM_LEADER = 0x356 ,
SMSG_ARENA_TEAM_EVENT = 0x357 ,
CMSG_BATTLEMASTER_JOIN_ARENA = 0x358 ,
MSG_MOVE_START_ASCEND = 0x359 ,
MSG_MOVE_STOP_ASCEND = 0x35A ,
SMSG_ARENA_TEAM_STATS = 0x35B ,
CMSG_LFG_JOIN = 0x35C ,
CMSG_LFG_LEAVE = 0x35D ,
CMSG_SEARCH_LFG_JOIN = 0x35E ,
CMSG_SEARCH_LFG_LEAVE = 0x35F ,
SMSG_UPDATE_LFG_LIST = 0x360 ,
SMSG_LFG_PROPOSAL_UPDATE = 0x361 ,
CMSG_LFG_PROPOSAL_RESULT = 0x362 ,
SMSG_LFG_ROLE_CHECK_UPDATE = 0x363 ,
SMSG_LFG_JOIN_RESULT = 0x364 ,
SMSG_LFG_QUEUE_STATUS = 0x365 ,
CMSG_SET_LFG_COMMENT = 0x366 ,
SMSG_LFG_UPDATE_PLAYER = 0x367 ,
SMSG_LFG_UPDATE_PARTY = 0x368 ,
SMSG_LFG_UPDATE_SEARCH = 0x369 ,
CMSG_LFG_SET_ROLES = 0x36A ,
CMSG_LFG_SET_NEEDS = 0x36B ,
CMSG_LFG_SET_BOOT_VOTE = 0x36C ,
SMSG_LFG_BOOT_PROPOSAL_UPDATE = 0x36D ,
CMSG_LFD_PLAYER_LOCK_INFO_REQUEST = 0x36E ,
SMSG_LFG_PLAYER_INFO = 0x36F ,
CMSG_LFG_TELEPORT = 0x370 ,
CMSG_LFD_PARTY_LOCK_INFO_REQUEST = 0x371 ,
SMSG_LFG_PARTY_INFO = 0x372 ,
SMSG_TITLE_EARNED = 0x373 ,
CMSG_SET_TITLE = 0x374 ,
CMSG_CANCEL_MOUNT_AURA = 0x375 ,
SMSG_ARENA_ERROR = 0x376 ,
MSG_INSPECT_ARENA_TEAMS = 0x377 ,
SMSG_DEATH_RELEASE_LOC = 0x378 ,
CMSG_CANCEL_TEMP_ENCHANTMENT = 0x379 ,
SMSG_FORCED_DEATH_UPDATE = 0x37A ,
CMSG_CHEAT_SET_HONOR_CURRENCY = 0x37B ,
CMSG_CHEAT_SET_ARENA_CURRENCY = 0x37C ,
MSG_MOVE_SET_FLIGHT_SPEED_CHEAT = 0x37D ,
MSG_MOVE_SET_FLIGHT_SPEED = 0x37E ,
MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT = 0x37F ,
MSG_MOVE_SET_FLIGHT_BACK_SPEED = 0x380 ,
SMSG_FORCE_FLIGHT_SPEED_CHANGE = 0x381 ,
CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK = 0x382 ,
SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE = 0x383 ,
CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK = 0x384 ,
SMSG_SPLINE_SET_FLIGHT_SPEED = 0x385 ,
SMSG_SPLINE_SET_FLIGHT_BACK_SPEED = 0x386 ,
CMSG_MAELSTROM_INVALIDATE_CACHE = 0x387 ,
SMSG_FLIGHT_SPLINE_SYNC = 0x388 ,
CMSG_SET_TAXI_BENCHMARK_MODE = 0x389 ,
SMSG_JOINED_BATTLEGROUND_QUEUE = 0x38A ,
SMSG_REALM_SPLIT = 0x38B ,
CMSG_REALM_SPLIT = 0x38C ,
CMSG_MOVE_CHNG_TRANSPORT = 0x38D ,
MSG_PARTY_ASSIGNMENT = 0x38E ,
SMSG_OFFER_PETITION_ERROR = 0x38F ,
SMSG_TIME_SYNC_REQ = 0x390 ,
CMSG_TIME_SYNC_RESP = 0x391 ,
CMSG_SEND_LOCAL_EVENT = 0x392 ,
CMSG_SEND_GENERAL_TRIGGER = 0x393 ,
CMSG_SEND_COMBAT_TRIGGER = 0x394 ,
CMSG_MAELSTROM_GM_SENT_MAIL = 0x395 ,
SMSG_RESET_FAILED_NOTIFY = 0x396 ,
SMSG_REAL_GROUP_UPDATE = 0x397 ,
SMSG_LFG_DISABLED = 0x398 ,
CMSG_ACTIVE_PVP_CHEAT = 0x399 ,
CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY = 0x39A ,
SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE = 0x39B ,
SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE = 0x39C ,
SMSG_UPDATE_COMBO_POINTS = 0x39D ,
SMSG_VOICE_SESSION_ROSTER_UPDATE = 0x39E ,
SMSG_VOICE_SESSION_LEAVE = 0x39F ,
SMSG_VOICE_SESSION_ADJUST_PRIORITY = 0x3A0 ,
CMSG_VOICE_SET_TALKER_MUTED_REQUEST = 0x3A1 ,
SMSG_VOICE_SET_TALKER_MUTED = 0x3A2 ,
SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE = 0x3A3 ,
SMSG_SET_EXTRA_AURA_INFO_OBSOLETE = 0x3A4 ,
SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE = 0x3A5 ,
SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE = 0x3A6 ,
MSG_MOVE_START_DESCEND = 0x3A7 ,
CMSG_IGNORE_REQUIREMENTS_CHEAT = 0x3A8 ,
SMSG_IGNORE_REQUIREMENTS_CHEAT = 0x3A9 ,
SMSG_SPELL_CHANCE_PROC_LOG = 0x3AA ,
CMSG_MOVE_SET_RUN_SPEED = 0x3AB ,
SMSG_DISMOUNT = 0x3AC ,
MSG_MOVE_UPDATE_CAN_FLY = 0x3AD ,
MSG_RAID_READY_CHECK_CONFIRM = 0x3AE ,
CMSG_VOICE_SESSION_ENABLE = 0x3AF ,
SMSG_VOICE_SESSION_ENABLE = 0x3B0 ,
SMSG_VOICE_PARENTAL_CONTROLS = 0x3B1 ,
CMSG_GM_WHISPER = 0x3B2 ,
SMSG_GM_MESSAGECHAT = 0x3B3 ,
MSG_GM_GEARRATING = 0x3B4 ,
CMSG_COMMENTATOR_ENABLE = 0x3B5 ,
SMSG_COMMENTATOR_STATE_CHANGED = 0x3B6 ,
CMSG_COMMENTATOR_GET_MAP_INFO = 0x3B7 ,
SMSG_COMMENTATOR_MAP_INFO = 0x3B8 ,
CMSG_COMMENTATOR_GET_PLAYER_INFO = 0x3B9 ,
SMSG_COMMENTATOR_GET_PLAYER_INFO = 0x3BA ,
SMSG_COMMENTATOR_PLAYER_INFO = 0x3BB ,
CMSG_COMMENTATOR_ENTER_INSTANCE = 0x3BC ,
CMSG_COMMENTATOR_EXIT_INSTANCE = 0x3BD ,
CMSG_COMMENTATOR_INSTANCE_COMMAND = 0x3BE ,
SMSG_CLEAR_TARGET = 0x3BF ,
CMSG_BOT_DETECTED = 0x3C0 ,
SMSG_CROSSED_INEBRIATION_THRESHOLD = 0x3C1 ,
CMSG_CHEAT_PLAYER_LOGIN = 0x3C2 ,
CMSG_CHEAT_PLAYER_LOOKUP = 0x3C3 ,
SMSG_CHEAT_PLAYER_LOOKUP = 0x3C4 ,
SMSG_KICK_REASON = 0x3C5 ,
MSG_RAID_READY_CHECK_FINISHED = 0x3C6 ,
CMSG_COMPLAIN = 0x3C7 ,
SMSG_COMPLAIN_RESULT = 0x3C8 ,
SMSG_FEATURE_SYSTEM_STATUS = 0x3C9 ,
CMSG_GM_SHOW_COMPLAINTS = 0x3CA ,
CMSG_GM_UNSQUELCH = 0x3CB ,
CMSG_CHANNEL_SILENCE_VOICE = 0x3CC ,
CMSG_CHANNEL_SILENCE_ALL = 0x3CD ,
CMSG_CHANNEL_UNSILENCE_VOICE = 0x3CE ,
CMSG_CHANNEL_UNSILENCE_ALL = 0x3CF ,
CMSG_TARGET_CAST = 0x3D0 ,
CMSG_TARGET_SCRIPT_CAST = 0x3D1 ,
CMSG_CHANNEL_DISPLAY_LIST = 0x3D2 ,
CMSG_SET_ACTIVE_VOICE_CHANNEL = 0x3D3 ,
CMSG_GET_CHANNEL_MEMBER_COUNT = 0x3D4 ,
SMSG_CHANNEL_MEMBER_COUNT = 0x3D5 ,
CMSG_CHANNEL_VOICE_ON = 0x3D6 ,
CMSG_CHANNEL_VOICE_OFF = 0x3D7 ,
CMSG_DEBUG_LIST_TARGETS = 0x3D8 ,
SMSG_DEBUG_LIST_TARGETS = 0x3D9 ,
SMSG_AVAILABLE_VOICE_CHANNEL = 0x3DA ,
CMSG_ADD_VOICE_IGNORE = 0x3DB ,
CMSG_DEL_VOICE_IGNORE = 0x3DC ,
CMSG_PARTY_SILENCE = 0x3DD ,
CMSG_PARTY_UNSILENCE = 0x3DE ,
MSG_NOTIFY_PARTY_SQUELCH = 0x3DF ,
SMSG_COMSAT_RECONNECT_TRY = 0x3E0 ,
SMSG_COMSAT_DISCONNECT = 0x3E1 ,
SMSG_COMSAT_CONNECT_FAIL = 0x3E2 ,
SMSG_VOICE_CHAT_STATUS = 0x3E3 ,
CMSG_REPORT_PVP_AFK = 0x3E4 ,
SMSG_REPORT_PVP_AFK_RESULT = 0x3E5 ,
CMSG_GUILD_BANKER_ACTIVATE = 0x3E6 ,
CMSG_GUILD_BANK_QUERY_TAB = 0x3E7 ,
SMSG_GUILD_BANK_LIST = 0x3E8 ,
CMSG_GUILD_BANK_SWAP_ITEMS = 0x3E9 ,
CMSG_GUILD_BANK_BUY_TAB = 0x3EA ,
CMSG_GUILD_BANK_UPDATE_TAB = 0x3EB ,
CMSG_GUILD_BANK_DEPOSIT_MONEY = 0x3EC ,
CMSG_GUILD_BANK_WITHDRAW_MONEY = 0x3ED ,
MSG_GUILD_BANK_LOG_QUERY = 0x3EE ,
CMSG_SET_CHANNEL_WATCH = 0x3EF ,
SMSG_USERLIST_ADD = 0x3F0 ,
SMSG_USERLIST_REMOVE = 0x3F1 ,
SMSG_USERLIST_UPDATE = 0x3F2 ,
CMSG_CLEAR_CHANNEL_WATCH = 0x3F3 ,
SMSG_INSPECT_TALENT = 0x3F4 ,
SMSG_GOGOGO_OBSOLETE = 0x3F5 ,
SMSG_ECHO_PARTY_SQUELCH = 0x3F6 ,
CMSG_SET_TITLE_SUFFIX = 0x3F7 ,
CMSG_SPELLCLICK = 0x3F8 ,
SMSG_LOOT_LIST = 0x3F9 ,
CMSG_GM_CHARACTER_RESTORE = 0x3FA ,
CMSG_GM_CHARACTER_SAVE = 0x3FB ,
SMSG_VOICESESSION_FULL = 0x3FC ,
MSG_GUILD_PERMISSIONS = 0x3FD ,
MSG_GUILD_BANK_MONEY_WITHDRAWN = 0x3FE ,
MSG_GUILD_EVENT_LOG_QUERY = 0x3FF ,
CMSG_MAELSTROM_RENAME_GUILD = 0x400 ,
CMSG_GET_MIRRORIMAGE_DATA = 0x401 ,
SMSG_MIRRORIMAGE_DATA = 0x402 ,
SMSG_FORCE_DISPLAY_UPDATE = 0x403 ,
SMSG_SPELL_CHANCE_RESIST_PUSHBACK = 0x404 ,
CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT = 0x405 ,
SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT = 0x406 ,
CMSG_KEEP_ALIVE = 0x407 ,
SMSG_RAID_READY_CHECK_ERROR = 0x408 ,
CMSG_OPT_OUT_OF_LOOT = 0x409 ,
MSG_QUERY_GUILD_BANK_TEXT = 0x40A ,
CMSG_SET_GUILD_BANK_TEXT = 0x40B ,
CMSG_SET_GRANTABLE_LEVELS = 0x40C ,
CMSG_GRANT_LEVEL = 0x40D ,
CMSG_REFER_A_FRIEND = 0x40E ,
MSG_GM_CHANGE_ARENA_RATING = 0x40F ,
CMSG_DECLINE_CHANNEL_INVITE = 0x410 ,
SMSG_GROUPACTION_THROTTLED = 0x411 ,
SMSG_OVERRIDE_LIGHT = 0x412 ,
SMSG_TOTEM_CREATED = 0x413 ,
CMSG_TOTEM_DESTROYED = 0x414 ,
CMSG_EXPIRE_RAID_INSTANCE = 0x415 ,
CMSG_NO_SPELL_VARIANCE = 0x416 ,
CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY = 0x417 ,
SMSG_QUESTGIVER_STATUS_MULTIPLE = 0x418 ,
CMSG_SET_PLAYER_DECLINED_NAMES = 0x419 ,
SMSG_SET_PLAYER_DECLINED_NAMES_RESULT = 0x41A ,
CMSG_QUERY_SERVER_BUCK_DATA = 0x41B ,
CMSG_CLEAR_SERVER_BUCK_DATA = 0x41C ,
SMSG_SERVER_BUCK_DATA = 0x41D ,
SMSG_SEND_UNLEARN_SPELLS = 0x41E ,
SMSG_PROPOSE_LEVEL_GRANT = 0x41F ,
CMSG_ACCEPT_LEVEL_GRANT = 0x420 ,
SMSG_REFER_A_FRIEND_FAILURE = 0x421 ,
SMSG_SPLINE_MOVE_SET_FLYING = 0x422 ,
SMSG_SPLINE_MOVE_UNSET_FLYING = 0x423 ,
SMSG_SUMMON_CANCEL = 0x424 ,
CMSG_CHANGE_PERSONAL_ARENA_RATING = 0x425 ,
CMSG_ALTER_APPEARANCE = 0x426 ,
SMSG_ENABLE_BARBER_SHOP = 0x427 ,
SMSG_BARBER_SHOP_RESULT = 0x428 ,
CMSG_CALENDAR_GET_CALENDAR = 0x429 ,
CMSG_CALENDAR_GET_EVENT = 0x42A ,
CMSG_CALENDAR_GUILD_FILTER = 0x42B ,
CMSG_CALENDAR_ARENA_TEAM = 0x42C ,
CMSG_CALENDAR_ADD_EVENT = 0x42D ,
CMSG_CALENDAR_UPDATE_EVENT = 0x42E ,
CMSG_CALENDAR_REMOVE_EVENT = 0x42F ,
CMSG_CALENDAR_COPY_EVENT = 0x430 ,
CMSG_CALENDAR_EVENT_INVITE = 0x431 ,
CMSG_CALENDAR_EVENT_RSVP = 0x432 ,
CMSG_CALENDAR_EVENT_REMOVE_INVITE = 0x433 ,
CMSG_CALENDAR_EVENT_STATUS = 0x434 ,
CMSG_CALENDAR_EVENT_MODERATOR_STATUS = 0x435 ,
SMSG_CALENDAR_SEND_CALENDAR = 0x436 ,
SMSG_CALENDAR_SEND_EVENT = 0x437 ,
SMSG_CALENDAR_FILTER_GUILD = 0x438 ,
SMSG_CALENDAR_ARENA_TEAM = 0x439 ,
SMSG_CALENDAR_EVENT_INVITE = 0x43A ,
SMSG_CALENDAR_EVENT_INVITE_REMOVED = 0x43B ,
SMSG_CALENDAR_EVENT_STATUS = 0x43C ,
SMSG_CALENDAR_COMMAND_RESULT = 0x43D ,
SMSG_CALENDAR_RAID_LOCKOUT_ADDED = 0x43E ,
SMSG_CALENDAR_RAID_LOCKOUT_REMOVED = 0x43F ,
SMSG_CALENDAR_EVENT_INVITE_ALERT = 0x440 ,
SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT = 0x441 ,
SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT = 0x442 ,
SMSG_CALENDAR_EVENT_REMOVED_ALERT = 0x443 ,
SMSG_CALENDAR_EVENT_UPDATED_ALERT = 0x444 ,
SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT = 0x445 ,
CMSG_CALENDAR_COMPLAIN = 0x446 ,
CMSG_CALENDAR_GET_NUM_PENDING = 0x447 ,
SMSG_CALENDAR_SEND_NUM_PENDING = 0x448 ,
CMSG_SAVE_DANCE = 0x449 ,
SMSG_NOTIFY_DANCE = 0x44A ,
CMSG_PLAY_DANCE = 0x44B ,
SMSG_PLAY_DANCE = 0x44C ,
CMSG_LOAD_DANCES = 0x44D ,
CMSG_STOP_DANCE = 0x44E ,
SMSG_STOP_DANCE = 0x44F ,
CMSG_SYNC_DANCE = 0x450 ,
CMSG_DANCE_QUERY = 0x451 ,
SMSG_DANCE_QUERY_RESPONSE = 0x452 ,
SMSG_INVALIDATE_DANCE = 0x453 ,
CMSG_DELETE_DANCE = 0x454 ,
SMSG_LEARNED_DANCE_MOVES = 0x455 ,
CMSG_LEARN_DANCE_MOVE = 0x456 ,
CMSG_UNLEARN_DANCE_MOVE = 0x457 ,
CMSG_SET_RUNE_COUNT = 0x458 ,
CMSG_SET_RUNE_COOLDOWN = 0x459 ,
MSG_MOVE_SET_PITCH_RATE_CHEAT = 0x45A ,
MSG_MOVE_SET_PITCH_RATE = 0x45B ,
SMSG_FORCE_PITCH_RATE_CHANGE = 0x45C ,
CMSG_FORCE_PITCH_RATE_CHANGE_ACK = 0x45D ,
SMSG_SPLINE_SET_PITCH_RATE = 0x45E ,
CMSG_CALENDAR_EVENT_INVITE_NOTES = 0x45F ,
SMSG_CALENDAR_EVENT_INVITE_NOTES = 0x460 ,
SMSG_CALENDAR_EVENT_INVITE_NOTES_ALERT = 0x461 ,
CMSG_UPDATE_MISSILE_TRAJECTORY = 0x462 ,
SMSG_UPDATE_ACCOUNT_DATA_COMPLETE = 0x463 ,
SMSG_TRIGGER_MOVIE = 0x464 ,
CMSG_COMPLETE_MOVIE = 0x465 ,
CMSG_SET_GLYPH_SLOT = 0x466 ,
CMSG_SET_GLYPH = 0x467 ,
SMSG_ACHIEVEMENT_EARNED = 0x468 ,
SMSG_DYNAMIC_DROP_ROLL_RESULT = 0x469 ,
SMSG_CRITERIA_UPDATE = 0x46A ,
CMSG_QUERY_INSPECT_ACHIEVEMENTS = 0x46B ,
SMSG_RESPOND_INSPECT_ACHIEVEMENTS = 0x46C ,
CMSG_DISMISS_CONTROLLED_VEHICLE = 0x46D ,
CMSG_COMPLETE_ACHIEVEMENT_CHEAT = 0x46E ,
SMSG_QUESTUPDATE_ADD_PVP_KILL = 0x46F ,
CMSG_SET_CRITERIA_CHEAT = 0x470 ,
SMSG_CALENDAR_RAID_LOCKOUT_UPDATED = 0x471 ,
CMSG_UNITANIMTIER_CHEAT = 0x472 ,
CMSG_CHAR_CUSTOMIZE = 0x473 ,
SMSG_CHAR_CUSTOMIZE = 0x474 ,
SMSG_PET_RENAMEABLE = 0x475 ,
CMSG_REQUEST_VEHICLE_EXIT = 0x476 ,
CMSG_REQUEST_VEHICLE_PREV_SEAT = 0x477 ,
CMSG_REQUEST_VEHICLE_NEXT_SEAT = 0x478 ,
CMSG_REQUEST_VEHICLE_SWITCH_SEAT = 0x479 ,
CMSG_PET_LEARN_TALENT = 0x47A ,
CMSG_PET_UNLEARN_TALENTS = 0x47B ,
SMSG_SET_PHASE_SHIFT = 0x47C ,
SMSG_ALL_ACHIEVEMENT_DATA = 0x47D ,
CMSG_FORCE_SAY_CHEAT = 0x47E ,
SMSG_HEALTH_UPDATE = 0x47F ,
SMSG_POWER_UPDATE = 0x480 ,
CMSG_GAMEOBJ_REPORT_USE = 0x481 ,
SMSG_HIGHEST_THREAT_UPDATE = 0x482 ,
SMSG_THREAT_UPDATE = 0x483 ,
SMSG_THREAT_REMOVE = 0x484 ,
SMSG_THREAT_CLEAR = 0x485 ,
SMSG_CONVERT_RUNE = 0x486 ,
SMSG_RESYNC_RUNES = 0x487 ,
SMSG_ADD_RUNE_POWER = 0x488 ,
CMSG_START_QUEST = 0x489 ,
CMSG_REMOVE_GLYPH = 0x48A ,
CMSG_DUMP_OBJECTS = 0x48B ,
SMSG_DUMP_OBJECTS_DATA = 0x48C ,
CMSG_DISMISS_CRITTER = 0x48D ,
SMSG_NOTIFY_DEST_LOC_SPELL_CAST = 0x48E ,
CMSG_AUCTION_LIST_PENDING_SALES = 0x48F ,
SMSG_AUCTION_LIST_PENDING_SALES = 0x490 ,
SMSG_MODIFY_COOLDOWN = 0x491 ,
SMSG_PET_UPDATE_COMBO_POINTS = 0x492 ,
CMSG_ENABLETAXI = 0x493 ,
SMSG_PRE_RESURRECT = 0x494 ,
SMSG_AURA_UPDATE_ALL = 0x495 ,
SMSG_AURA_UPDATE = 0x496 ,
CMSG_FLOOD_GRACE_CHEAT = 0x497 ,
SMSG_SERVER_FIRST_ACHIEVEMENT = 0x498 ,
SMSG_PET_LEARNED_SPELL = 0x499 ,
SMSG_PET_UNLEARNED_SPELL = 0x49A ,
CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE = 0x49B ,
CMSG_HEARTH_AND_RESURRECT = 0x49C ,
SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA = 0x49D ,
SMSG_CRITERIA_DELETED = 0x49E ,
SMSG_ACHIEVEMENT_DELETED = 0x49F ,
CMSG_SERVER_INFO_QUERY = 0x4A0 ,
SMSG_SERVER_INFO_RESPONSE = 0x4A1 ,
CMSG_CHECK_LOGIN_CRITERIA = 0x4A2 ,
SMSG_SERVER_BUCK_DATA_START = 0x4A3 ,
CMSG_SET_BREATH = 0x4A4 ,
CMSG_QUERY_VEHICLE_STATUS = 0x4A5 ,
SMSG_BATTLEGROUND_INFO_THROTTLED = 0x4A6 ,
SMSG_PLAYER_VEHICLE_DATA = 0x4A7 ,
CMSG_PLAYER_VEHICLE_ENTER = 0x4A8 ,
CMSG_CONTROLLER_EJECT_PASSENGER = 0x4A9 ,
SMSG_PET_GUIDS = 0x4AA ,
SMSG_CLIENTCACHE_VERSION = 0x4AB ,
CMSG_CHANGE_GDF_ARENA_RATING = 0x4AC ,
CMSG_SET_ARENA_TEAM_RATING_BY_INDEX = 0x4AD ,
CMSG_SET_ARENA_TEAM_WEEKLY_GAMES = 0x4AE ,
CMSG_SET_ARENA_TEAM_SEASON_GAMES = 0x4AF ,
CMSG_SET_ARENA_MEMBER_WEEKLY_GAMES = 0x4B0 ,
CMSG_SET_ARENA_MEMBER_SEASON_GAMES = 0x4B1 ,
SMSG_ITEM_REFUND_INFO_RESPONSE = 0x4B2 ,
CMSG_ITEM_REFUND_INFO = 0x4B3 ,
CMSG_ITEM_REFUND = 0x4B4 ,
SMSG_ITEM_REFUND_RESULT = 0x4B5 ,
CMSG_CORPSE_MAP_POSITION_QUERY = 0x4B6 ,
SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE = 0x4B7 ,
CMSG_UNUSED5 = 0x4B8 ,
CMSG_UNUSED6 = 0x4B9 ,
CMSG_CALENDAR_EVENT_SIGNUP = 0x4BA ,
SMSG_CALENDAR_CLEAR_PENDING_ACTION = 0x4BB ,
SMSG_EQUIPMENT_SET_LIST = 0x4BC ,
CMSG_EQUIPMENT_SET_SAVE = 0x4BD ,
CMSG_UPDATE_PROJECTILE_POSITION = 0x4BE ,
SMSG_SET_PROJECTILE_POSITION = 0x4BF ,
SMSG_TALENTS_INFO = 0x4C0 ,
CMSG_LEARN_PREVIEW_TALENTS = 0x4C1 ,
CMSG_LEARN_PREVIEW_TALENTS_PET = 0x4C2 ,
CMSG_SET_ACTIVE_TALENT_GROUP_OBSOLETE = 0x4C3 ,
CMSG_GM_GRANT_ACHIEVEMENT = 0x4C4 ,
CMSG_GM_REMOVE_ACHIEVEMENT = 0x4C5 ,
CMSG_GM_SET_CRITERIA_FOR_PLAYER = 0x4C6 ,
SMSG_ARENA_UNIT_DESTROYED = 0x4C7 ,
SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED = 0x4C8 ,
CMSG_PROFILEDATA_REQUEST = 0x4C9 ,
SMSG_PROFILEDATA_RESPONSE = 0x4CA ,
CMSG_START_BATTLEFIELD_CHEAT = 0x4CB ,
CMSG_END_BATTLEFIELD_CHEAT = 0x4CC ,
SMSG_MULTIPLE_PACKETS = 0x4CD ,
SMSG_MOVE_GRAVITY_DISABLE = 0x4CE ,
CMSG_MOVE_GRAVITY_DISABLE_ACK = 0x4CF ,
SMSG_MOVE_GRAVITY_ENABLE = 0x4D0 ,
CMSG_MOVE_GRAVITY_ENABLE_ACK = 0x4D1 ,
MSG_MOVE_GRAVITY_CHNG = 0x4D2 ,
SMSG_SPLINE_MOVE_GRAVITY_DISABLE = 0x4D3 ,
SMSG_SPLINE_MOVE_GRAVITY_ENABLE = 0x4D4 ,
CMSG_EQUIPMENT_SET_USE = 0x4D5 ,
SMSG_EQUIPMENT_SET_USE_RESULT = 0x4D6 ,
CMSG_FORCE_ANIM = 0x4D7 ,
SMSG_FORCE_ANIM = 0x4D8 ,
CMSG_CHAR_FACTION_CHANGE = 0x4D9 ,
SMSG_CHAR_FACTION_CHANGE = 0x4DA ,
CMSG_PVP_QUEUE_STATS_REQUEST = 0x4DB ,
SMSG_PVP_QUEUE_STATS = 0x4DC ,
CMSG_SET_PAID_SERVICE_CHEAT = 0x4DD ,
SMSG_BATTLEFIELD_MGR_ENTRY_INVITE = 0x4DE ,
CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE = 0x4DF ,
SMSG_BATTLEFIELD_MGR_ENTERED = 0x4E0 ,
SMSG_BATTLEFIELD_MGR_QUEUE_INVITE = 0x4E1 ,
CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE = 0x4E2 ,
CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST = 0x4E3 ,
SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE = 0x4E4 ,
SMSG_BATTLEFIELD_MGR_EJECT_PENDING = 0x4E5 ,
SMSG_BATTLEFIELD_MGR_EJECTED = 0x4E6 ,
CMSG_BATTLEFIELD_MGR_EXIT_REQUEST = 0x4E7 ,
SMSG_BATTLEFIELD_MGR_STATE_CHANGE = 0x4E8 ,
CMSG_BATTLEFIELD_MANAGER_ADVANCE_STATE = 0x4E9 ,
CMSG_BATTLEFIELD_MANAGER_SET_NEXT_TRANSITION_TIME = 0x4EA ,
MSG_SET_RAID_DIFFICULTY = 0x4EB ,
CMSG_TOGGLE_XP_GAIN = 0x4EC ,
SMSG_TOGGLE_XP_GAIN = 0x4ED ,
SMSG_GMRESPONSE_DB_ERROR = 0x4EE ,
SMSG_GMRESPONSE_RECEIVED = 0x4EF ,
CMSG_GMRESPONSE_RESOLVE = 0x4F0 ,
SMSG_GMRESPONSE_STATUS_UPDATE = 0x4F1 ,
SMSG_GMRESPONSE_CREATE_TICKET = 0x4F2 ,
CMSG_GMRESPONSE_CREATE_TICKET = 0x4F3 ,
CMSG_SERVERINFO = 0x4F4 ,
SMSG_SERVERINFO = 0x4F5 ,
CMSG_WORLD_STATE_UI_TIMER_UPDATE = 0x4F6 ,
SMSG_WORLD_STATE_UI_TIMER_UPDATE = 0x4F7 ,
CMSG_CHAR_RACE_CHANGE = 0x4F8 ,
MSG_VIEW_PHASE_SHIFT = 0x4F9 ,
SMSG_TALENTS_INVOLUNTARILY_RESET = 0x4FA ,
CMSG_DEBUG_SERVER_GEO = 0x4FB ,
SMSG_DEBUG_SERVER_GEO = 0x4FC ,
SMSG_LOOT_SLOT_CHANGED = 0x4FD ,
UMSG_UPDATE_GROUP_INFO = 0x4FE ,
CMSG_READY_FOR_ACCOUNT_DATA_TIMES = 0x4FF ,
CMSG_QUERY_QUESTS_COMPLETED = 0x500 ,
SMSG_QUERY_QUESTS_COMPLETED_RESPONSE = 0x501 ,
CMSG_GM_REPORT_LAG = 0x502 ,
CMSG_AFK_MONITOR_INFO_REQUEST = 0x503 ,
SMSG_AFK_MONITOR_INFO_RESPONSE = 0x504 ,
CMSG_AFK_MONITOR_INFO_CLEAR = 0x505 ,
SMSG_CORPSE_NOT_IN_INSTANCE = 0x506 ,
CMSG_GM_NUKE_CHARACTER = 0x507 ,
CMSG_SET_ALLOW_LOW_LEVEL_RAID1 = 0x508 ,
CMSG_SET_ALLOW_LOW_LEVEL_RAID2 = 0x509 ,
SMSG_CAMERA_SHAKE = 0x50A ,
SMSG_SOCKET_GEMS_RESULT = 0x50B ,
CMSG_SET_CHARACTER_MODEL = 0x50C ,
SMSG_REDIRECT_CLIENT = 0x50D ,
CMSG_REDIRECTION_FAILED = 0x50E ,
SMSG_SUSPEND_COMMS = 0x50F ,
CMSG_SUSPEND_COMMS_ACK = 0x510 ,
SMSG_FORCE_SEND_QUEUED_PACKETS = 0x511 ,
CMSG_REDIRECTION_AUTH_PROOF = 0x512 ,
CMSG_DROP_NEW_CONNECTION = 0x513 ,
SMSG_SEND_ALL_COMBAT_LOG = 0x514 ,
SMSG_OPEN_LFG_DUNGEON_FINDER = 0x515 ,
SMSG_MOVE_SET_COLLISION_HGT = 0x516 ,
CMSG_MOVE_SET_COLLISION_HGT_ACK = 0x517 ,
MSG_MOVE_SET_COLLISION_HGT = 0x518 ,
CMSG_CLEAR_RANDOM_BG_WIN_TIME = 0x519 ,
CMSG_CLEAR_HOLIDAY_BG_WIN_TIME = 0x51A ,
CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND = 0x51B ,
SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT1 = 0x51C ,
SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT2 = 0x51D ,
SMSG_MULTIPLE_MOVES = 0x51E ,
NUM_MSG_TYPES = 0x51F
}
List of Opcodes.
enum OpcodeMisc : uint16 {
NUM_OPCODE_HANDLERS = NUM_MSG_TYPES ,
NULL_OPCODE = 0x0000
}
enum SessionStatus {
STATUS_AUTHED = 0 ,
STATUS_LOGGEDIN ,
STATUS_TRANSFER ,
STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT ,
STATUS_NEVER ,
STATUS_UNHANDLED
}
Player state.
enum PacketProcessing {
PROCESS_INPLACE = 0 ,
PROCESS_THREADUNSAFE ,
PROCESS_THREADSAFE
}
enum AccountDataType {
GLOBAL_CONFIG_CACHE = 0 ,
PER_CHARACTER_CONFIG_CACHE = 1 ,
GLOBAL_BINDINGS_CACHE = 2 ,
PER_CHARACTER_BINDINGS_CACHE = 3 ,
GLOBAL_MACROS_CACHE = 4 ,
PER_CHARACTER_MACROS_CACHE = 5 ,
PER_CHARACTER_LAYOUT_CACHE = 6 ,
PER_CHARACTER_CHAT_CACHE = 7
}
enum PartyOperation {
PARTY_OP_INVITE = 0 ,
PARTY_OP_UNINVITE = 1 ,
PARTY_OP_LEAVE = 2 ,
PARTY_OP_SWAP = 4
}
enum BFLeaveReason {
BF_LEAVE_REASON_CLOSE = 0x00000001 ,
BF_LEAVE_REASON_EXITED = 0x00000008 ,
BF_LEAVE_REASON_LOW_LEVEL = 0x00000010
}
enum ChatRestrictionType {
ERR_CHAT_RESTRICTED = 0 ,
ERR_CHAT_THROTTLED = 1 ,
ERR_USER_SQUELCHED = 2 ,
ERR_YELL_RESTRICTED = 3
}
enum DeclinedNameResult {
DECLINED_NAMES_RESULT_SUCCESS = 0 ,
DECLINED_NAMES_RESULT_ERROR = 1
}
enum CharterTypes {
GUILD_CHARTER_TYPE = 9 ,
ARENA_TEAM_CHARTER_2v2_TYPE = 2 ,
ARENA_TEAM_CHARTER_3v3_TYPE = 3 ,
ARENA_TEAM_CHARTER_5v5_TYPE = 5
}
Functions
OpcodeHandler::OpcodeHandler (char const *name, SessionStatus status)
virtual OpcodeHandler::~OpcodeHandler ()=default
ClientOpcodeHandler::ClientOpcodeHandler (char const *name, SessionStatus status, PacketProcessing processing)
virtual void ClientOpcodeHandler::Call (WorldSession *session, WorldPacket &packet) const =0
ServerOpcodeHandler::ServerOpcodeHandler (char const *name, SessionStatus status)
OpcodeTable::OpcodeTable ()
OpcodeTable::OpcodeTable (OpcodeTable const &)=delete
OpcodeTable & OpcodeTable::operator= (OpcodeTable const &)=delete
OpcodeTable::~OpcodeTable ()
void OpcodeTable::Initialize ()
Correspondence between opcodes and their names.
ClientOpcodeHandler const * OpcodeTable::operator[] (Opcodes index) const
template<typename Handler , Handler HandlerFunction>
void OpcodeTable::ValidateAndSetClientOpcode (OpcodeClient opcode, char const *name, SessionStatus status, PacketProcessing processing)
void OpcodeTable::ValidateAndSetServerOpcode (OpcodeServer opcode, char const *name, SessionStatus status)
std::string GetOpcodeNameForLogging (Opcodes opcode)
Lookup opcode name for human understandable logging.
Variables
char const * OpcodeHandler::Name
SessionStatus OpcodeHandler::Status
PacketProcessing ClientOpcodeHandler::ProcessingPlace
ClientOpcodeHandler * OpcodeTable::_internalTableClient [NUM_OPCODE_HANDLERS]
OpcodeTable opcodeTable
Detailed Description
Macro Definition Documentation
GLOBAL_CACHE_MASK
#define GLOBAL_CACHE_MASK 0x15
#include <azerothcore-wotlk/src/server/game/Server/WorldSession.h>
NUM_ACCOUNT_DATA_TYPES
#define NUM_ACCOUNT_DATA_TYPES 8
#include <azerothcore-wotlk/src/server/game/Server/WorldSession.h>
PER_CHARACTER_CACHE_MASK
#define PER_CHARACTER_CACHE_MASK 0xEA
#include <azerothcore-wotlk/src/server/game/Server/WorldSession.h>
sWorldSocketMgr
#define sWorldSocketMgr WorldSocketMgr::Instance()
#include <azerothcore-wotlk/src/server/game/Server/WorldSocketMgr.h>
Typedef Documentation
OpcodeClient
typedef Opcodes OpcodeClient
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
OpcodeServer
typedef Opcodes OpcodeServer
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
Enumeration Type Documentation
AccountDataType
enum AccountDataType
#include <azerothcore-wotlk/src/server/game/Server/WorldSession.h>
Enumerator
GLOBAL_CONFIG_CACHE
PER_CHARACTER_CONFIG_CACHE
GLOBAL_BINDINGS_CACHE
PER_CHARACTER_BINDINGS_CACHE
GLOBAL_MACROS_CACHE
PER_CHARACTER_MACROS_CACHE
PER_CHARACTER_LAYOUT_CACHE
PER_CHARACTER_CHAT_CACHE
{
    GLOBAL_CONFIG_CACHE             = 0,                    // 0x01 g
    PER_CHARACTER_CONFIG_CACHE      = 1,                    // 0x02 p
    GLOBAL_BINDINGS_CACHE           = 2,                    // 0x04 g
    PER_CHARACTER_BINDINGS_CACHE    = 3,                    // 0x08 p
    GLOBAL_MACROS_CACHE             = 4,                    // 0x10 g
    PER_CHARACTER_MACROS_CACHE      = 5,                    // 0x20 p
    PER_CHARACTER_LAYOUT_CACHE      = 6,                    // 0x40 p
    PER_CHARACTER_CHAT_CACHE        = 7,                    // 0x80 p
};
BFLeaveReason
enum BFLeaveReason
#include <azerothcore-wotlk/src/server/game/Server/WorldSession.h>
Enumerator
BF_LEAVE_REASON_CLOSE
BF_LEAVE_REASON_EXITED
BF_LEAVE_REASON_LOW_LEVEL
{
    BF_LEAVE_REASON_CLOSE     = 0x00000001,
    //BF_LEAVE_REASON_UNK1      = 0x00000002, (not used)
    //BF_LEAVE_REASON_UNK2      = 0x00000004, (not used)
    BF_LEAVE_REASON_EXITED    = 0x00000008,
    BF_LEAVE_REASON_LOW_LEVEL = 0x00000010,
};
CharterTypes
enum CharterTypes
#include <azerothcore-wotlk/src/server/game/Server/WorldSession.h>
Enumerator
GUILD_CHARTER_TYPE
ARENA_TEAM_CHARTER_2v2_TYPE
ARENA_TEAM_CHARTER_3v3_TYPE
ARENA_TEAM_CHARTER_5v5_TYPE
{
    GUILD_CHARTER_TYPE                            = 9,
    ARENA_TEAM_CHARTER_2v2_TYPE                   = 2,
    ARENA_TEAM_CHARTER_3v3_TYPE                   = 3,
    ARENA_TEAM_CHARTER_5v5_TYPE                   = 5
};
ChatRestrictionType
enum ChatRestrictionType
#include <azerothcore-wotlk/src/server/game/Server/WorldSession.h>
Enumerator
ERR_CHAT_RESTRICTED
ERR_CHAT_THROTTLED
ERR_USER_SQUELCHED
ERR_YELL_RESTRICTED
{
    ERR_CHAT_RESTRICTED = 0,
    ERR_CHAT_THROTTLED  = 1,
    ERR_USER_SQUELCHED  = 2,
    ERR_YELL_RESTRICTED = 3
};
DeclinedNameResult
enum DeclinedNameResult
#include <azerothcore-wotlk/src/server/game/Server/WorldSession.h>
Enumerator
DECLINED_NAMES_RESULT_SUCCESS
DECLINED_NAMES_RESULT_ERROR
{
    DECLINED_NAMES_RESULT_SUCCESS = 0,
    DECLINED_NAMES_RESULT_ERROR = 1
};
OpcodeMisc
enum OpcodeMisc : uint16
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
Enumerator
NUM_OPCODE_HANDLERS
NULL_OPCODE
{
    NUM_OPCODE_HANDLERS = NUM_MSG_TYPES,
    NULL_OPCODE = 0x0000
};
Opcodes
enum Opcodes : uint16
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
List of Opcodes.
Enumerator
CMSG_BOOTME
CMSG_DBLOOKUP
SMSG_DBLOOKUP
CMSG_QUERY_OBJECT_POSITION
SMSG_QUERY_OBJECT_POSITION
CMSG_QUERY_OBJECT_ROTATION
SMSG_QUERY_OBJECT_ROTATION
CMSG_WORLD_TELEPORT
CMSG_TELEPORT_TO_UNIT
CMSG_ZONE_MAP
SMSG_ZONE_MAP
CMSG_DEBUG_CHANGECELLZONE
CMSG_MOVE_CHARACTER_CHEAT
SMSG_MOVE_CHARACTER_CHEAT
CMSG_RECHARGE
CMSG_LEARN_SPELL
CMSG_CREATEMONSTER
CMSG_DESTROYMONSTER
CMSG_CREATEITEM
CMSG_CREATEGAMEOBJECT
SMSG_CHECK_FOR_BOTS
CMSG_MAKEMONSTERATTACKGUID
CMSG_BOT_DETECTED2
CMSG_FORCEACTION
CMSG_FORCEACTIONONOTHER
CMSG_FORCEACTIONSHOW
SMSG_FORCEACTIONSHOW
CMSG_PETGODMODE
SMSG_PETGODMODE
SMSG_REFER_A_FRIEND_EXPIRED
CMSG_WEATHER_SPEED_CHEAT
CMSG_UNDRESSPLAYER
CMSG_BEASTMASTER
CMSG_GODMODE
SMSG_GODMODE
CMSG_CHEAT_SETMONEY
CMSG_LEVEL_CHEAT
CMSG_PET_LEVEL_CHEAT
CMSG_SET_WORLDSTATE
CMSG_COOLDOWN_CHEAT
CMSG_USE_SKILL_CHEAT
CMSG_FLAG_QUEST
CMSG_FLAG_QUEST_FINISH
CMSG_CLEAR_QUEST
CMSG_SEND_EVENT
CMSG_DEBUG_AISTATE
SMSG_DEBUG_AISTATE
CMSG_DISABLE_PVP_CHEAT
CMSG_ADVANCE_SPAWN_TIME
SMSG_DESTRUCTIBLE_BUILDING_DAMAGE
CMSG_AUTH_SRP6_BEGIN
CMSG_AUTH_SRP6_PROOF
CMSG_AUTH_SRP6_RECODE
CMSG_CHAR_CREATE
CMSG_CHAR_ENUM
CMSG_CHAR_DELETE
SMSG_AUTH_SRP6_RESPONSE
SMSG_CHAR_CREATE
SMSG_CHAR_ENUM
SMSG_CHAR_DELETE
CMSG_PLAYER_LOGIN
SMSG_NEW_WORLD
SMSG_TRANSFER_PENDING
SMSG_TRANSFER_ABORTED
SMSG_CHARACTER_LOGIN_FAILED
SMSG_LOGIN_SETTIMESPEED
SMSG_GAMETIME_UPDATE
CMSG_GAMETIME_SET
SMSG_GAMETIME_SET
CMSG_GAMESPEED_SET
SMSG_GAMESPEED_SET
CMSG_SERVERTIME
SMSG_SERVERTIME
CMSG_PLAYER_LOGOUT
CMSG_LOGOUT_REQUEST
SMSG_LOGOUT_RESPONSE
SMSG_LOGOUT_COMPLETE
CMSG_LOGOUT_CANCEL
SMSG_LOGOUT_CANCEL_ACK
CMSG_NAME_QUERY
SMSG_NAME_QUERY_RESPONSE
CMSG_PET_NAME_QUERY
SMSG_PET_NAME_QUERY_RESPONSE
CMSG_GUILD_QUERY
SMSG_GUILD_QUERY_RESPONSE
CMSG_ITEM_QUERY_SINGLE
CMSG_ITEM_QUERY_MULTIPLE
SMSG_ITEM_QUERY_SINGLE_RESPONSE
SMSG_ITEM_QUERY_MULTIPLE_RESPONSE
CMSG_PAGE_TEXT_QUERY
SMSG_PAGE_TEXT_QUERY_RESPONSE
CMSG_QUEST_QUERY
SMSG_QUEST_QUERY_RESPONSE
CMSG_GAMEOBJECT_QUERY
SMSG_GAMEOBJECT_QUERY_RESPONSE
CMSG_CREATURE_QUERY
SMSG_CREATURE_QUERY_RESPONSE
CMSG_WHO
SMSG_WHO
CMSG_WHOIS
SMSG_WHOIS
CMSG_CONTACT_LIST
SMSG_CONTACT_LIST
SMSG_FRIEND_STATUS
CMSG_ADD_FRIEND
CMSG_DEL_FRIEND
CMSG_SET_CONTACT_NOTES
CMSG_ADD_IGNORE
CMSG_DEL_IGNORE
CMSG_GROUP_INVITE
SMSG_GROUP_INVITE
CMSG_GROUP_CANCEL
SMSG_GROUP_CANCEL
CMSG_GROUP_ACCEPT
CMSG_GROUP_DECLINE
SMSG_GROUP_DECLINE
CMSG_GROUP_UNINVITE
CMSG_GROUP_UNINVITE_GUID
SMSG_GROUP_UNINVITE
CMSG_GROUP_SET_LEADER
SMSG_GROUP_SET_LEADER
CMSG_LOOT_METHOD
CMSG_GROUP_DISBAND
SMSG_GROUP_DESTROYED
SMSG_GROUP_LIST
SMSG_PARTY_MEMBER_STATS
SMSG_PARTY_COMMAND_RESULT
UMSG_UPDATE_GROUP_MEMBERS
CMSG_GUILD_CREATE
CMSG_GUILD_INVITE
SMSG_GUILD_INVITE
CMSG_GUILD_ACCEPT
CMSG_GUILD_DECLINE
SMSG_GUILD_DECLINE
CMSG_GUILD_INFO
SMSG_GUILD_INFO
CMSG_GUILD_ROSTER
SMSG_GUILD_ROSTER
CMSG_GUILD_PROMOTE
CMSG_GUILD_DEMOTE
CMSG_GUILD_LEAVE
CMSG_GUILD_REMOVE
CMSG_GUILD_DISBAND
CMSG_GUILD_LEADER
CMSG_GUILD_MOTD
SMSG_GUILD_EVENT
SMSG_GUILD_COMMAND_RESULT
UMSG_UPDATE_GUILD
CMSG_MESSAGECHAT
SMSG_MESSAGECHAT
CMSG_JOIN_CHANNEL
CMSG_LEAVE_CHANNEL
SMSG_CHANNEL_NOTIFY
CMSG_CHANNEL_LIST
SMSG_CHANNEL_LIST
CMSG_CHANNEL_PASSWORD
CMSG_CHANNEL_SET_OWNER
CMSG_CHANNEL_OWNER
CMSG_CHANNEL_MODERATOR
CMSG_CHANNEL_UNMODERATOR
CMSG_CHANNEL_MUTE
CMSG_CHANNEL_UNMUTE
CMSG_CHANNEL_INVITE
CMSG_CHANNEL_KICK
CMSG_CHANNEL_BAN
CMSG_CHANNEL_UNBAN
CMSG_CHANNEL_ANNOUNCEMENTS
CMSG_CHANNEL_MODERATE
SMSG_UPDATE_OBJECT
SMSG_DESTROY_OBJECT
CMSG_USE_ITEM
CMSG_OPEN_ITEM
CMSG_READ_ITEM
SMSG_READ_ITEM_OK
SMSG_READ_ITEM_FAILED
SMSG_ITEM_COOLDOWN
CMSG_GAMEOBJ_USE
CMSG_DESTROY_ITEMS
SMSG_GAMEOBJECT_CUSTOM_ANIM
CMSG_AREATRIGGER
MSG_MOVE_START_FORWARD
MSG_MOVE_START_BACKWARD
MSG_MOVE_STOP
MSG_MOVE_START_STRAFE_LEFT
MSG_MOVE_START_STRAFE_RIGHT
MSG_MOVE_STOP_STRAFE
MSG_MOVE_JUMP
MSG_MOVE_START_TURN_LEFT
MSG_MOVE_START_TURN_RIGHT
MSG_MOVE_STOP_TURN
MSG_MOVE_START_PITCH_UP
MSG_MOVE_START_PITCH_DOWN
MSG_MOVE_STOP_PITCH
MSG_MOVE_SET_RUN_MODE
MSG_MOVE_SET_WALK_MODE
MSG_MOVE_TOGGLE_LOGGING
MSG_MOVE_TELEPORT
MSG_MOVE_TELEPORT_CHEAT
MSG_MOVE_TELEPORT_ACK
MSG_MOVE_TOGGLE_FALL_LOGGING
MSG_MOVE_FALL_LAND
MSG_MOVE_START_SWIM
MSG_MOVE_STOP_SWIM
MSG_MOVE_SET_RUN_SPEED_CHEAT
MSG_MOVE_SET_RUN_SPEED
MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT
MSG_MOVE_SET_RUN_BACK_SPEED
MSG_MOVE_SET_WALK_SPEED_CHEAT
MSG_MOVE_SET_WALK_SPEED
MSG_MOVE_SET_SWIM_SPEED_CHEAT
MSG_MOVE_SET_SWIM_SPEED
MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT
MSG_MOVE_SET_SWIM_BACK_SPEED
MSG_MOVE_SET_ALL_SPEED_CHEAT
MSG_MOVE_SET_TURN_RATE_CHEAT
MSG_MOVE_SET_TURN_RATE
MSG_MOVE_TOGGLE_COLLISION_CHEAT
MSG_MOVE_SET_FACING
MSG_MOVE_SET_PITCH
MSG_MOVE_WORLDPORT_ACK
SMSG_MONSTER_MOVE
SMSG_MOVE_WATER_WALK
SMSG_MOVE_LAND_WALK
CMSG_MOVE_CHARM_PORT_CHEAT
CMSG_MOVE_SET_RAW_POSITION
SMSG_FORCE_RUN_SPEED_CHANGE
CMSG_FORCE_RUN_SPEED_CHANGE_ACK
SMSG_FORCE_RUN_BACK_SPEED_CHANGE
CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK
SMSG_FORCE_SWIM_SPEED_CHANGE
CMSG_FORCE_SWIM_SPEED_CHANGE_ACK
SMSG_FORCE_MOVE_ROOT
CMSG_FORCE_MOVE_ROOT_ACK
SMSG_FORCE_MOVE_UNROOT
CMSG_FORCE_MOVE_UNROOT_ACK
MSG_MOVE_ROOT
MSG_MOVE_UNROOT
MSG_MOVE_HEARTBEAT
SMSG_MOVE_KNOCK_BACK
CMSG_MOVE_KNOCK_BACK_ACK
MSG_MOVE_KNOCK_BACK
SMSG_MOVE_FEATHER_FALL
SMSG_MOVE_NORMAL_FALL
SMSG_MOVE_SET_HOVER
SMSG_MOVE_UNSET_HOVER
CMSG_MOVE_HOVER_ACK
MSG_MOVE_HOVER
CMSG_TRIGGER_CINEMATIC_CHEAT
CMSG_OPENING_CINEMATIC
SMSG_TRIGGER_CINEMATIC
CMSG_NEXT_CINEMATIC_CAMERA
CMSG_COMPLETE_CINEMATIC
SMSG_TUTORIAL_FLAGS
CMSG_TUTORIAL_FLAG
CMSG_TUTORIAL_CLEAR
CMSG_TUTORIAL_RESET
CMSG_STANDSTATECHANGE
CMSG_EMOTE
SMSG_EMOTE
CMSG_TEXT_EMOTE
SMSG_TEXT_EMOTE
CMSG_AUTOEQUIP_GROUND_ITEM
CMSG_AUTOSTORE_GROUND_ITEM
CMSG_AUTOSTORE_LOOT_ITEM
CMSG_STORE_LOOT_IN_SLOT
CMSG_AUTOEQUIP_ITEM
CMSG_AUTOSTORE_BAG_ITEM
CMSG_SWAP_ITEM
CMSG_SWAP_INV_ITEM
CMSG_SPLIT_ITEM
CMSG_AUTOEQUIP_ITEM_SLOT
CMSG_UNCLAIM_LICENSE
CMSG_DESTROYITEM
SMSG_INVENTORY_CHANGE_FAILURE
SMSG_OPEN_CONTAINER
CMSG_INSPECT
SMSG_INSPECT_RESULTS_UPDATE
CMSG_INITIATE_TRADE
CMSG_BEGIN_TRADE
CMSG_BUSY_TRADE
CMSG_IGNORE_TRADE
CMSG_ACCEPT_TRADE
CMSG_UNACCEPT_TRADE
CMSG_CANCEL_TRADE
CMSG_SET_TRADE_ITEM
CMSG_CLEAR_TRADE_ITEM
CMSG_SET_TRADE_GOLD
SMSG_TRADE_STATUS
SMSG_TRADE_STATUS_EXTENDED
SMSG_INITIALIZE_FACTIONS
SMSG_SET_FACTION_VISIBLE
SMSG_SET_FACTION_STANDING
CMSG_SET_FACTION_ATWAR
CMSG_SET_FACTION_CHEAT
SMSG_SET_PROFICIENCY
CMSG_SET_ACTION_BUTTON
SMSG_ACTION_BUTTONS
SMSG_INITIAL_SPELLS
SMSG_LEARNED_SPELL
SMSG_SUPERCEDED_SPELL
CMSG_NEW_SPELL_SLOT
CMSG_CAST_SPELL
CMSG_CANCEL_CAST
SMSG_CAST_FAILED
SMSG_SPELL_START
SMSG_SPELL_GO
SMSG_SPELL_FAILURE
SMSG_SPELL_COOLDOWN
SMSG_COOLDOWN_EVENT
CMSG_CANCEL_AURA
SMSG_EQUIPMENT_SET_SAVED
SMSG_PET_CAST_FAILED
MSG_CHANNEL_START
MSG_CHANNEL_UPDATE
CMSG_CANCEL_CHANNELLING
SMSG_AI_REACTION
CMSG_SET_SELECTION
CMSG_DELETEEQUIPMENT_SET
CMSG_INSTANCE_LOCK_RESPONSE
CMSG_DEBUG_PASSIVE_AURA
CMSG_ATTACKSWING
CMSG_ATTACKSTOP
SMSG_ATTACKSTART
SMSG_ATTACKSTOP
SMSG_ATTACKSWING_NOTINRANGE
SMSG_ATTACKSWING_BADFACING
SMSG_INSTANCE_LOCK_WARNING_QUERY
SMSG_ATTACKSWING_DEADTARGET
SMSG_ATTACKSWING_CANT_ATTACK
SMSG_ATTACKERSTATEUPDATE
SMSG_BATTLEFIELD_PORT_DENIED
CMSG_PERFORM_ACTION_SET
SMSG_RESUME_CAST_BAR
SMSG_CANCEL_COMBAT
SMSG_SPELLBREAKLOG
SMSG_SPELLHEALLOG
SMSG_SPELLENERGIZELOG
SMSG_BREAK_TARGET
CMSG_SAVE_PLAYER
CMSG_SETDEATHBINDPOINT
SMSG_BINDPOINTUPDATE
CMSG_GETDEATHBINDZONE
SMSG_BINDZONEREPLY
SMSG_PLAYERBOUND
SMSG_CLIENT_CONTROL_UPDATE
CMSG_REPOP_REQUEST
SMSG_RESURRECT_REQUEST
CMSG_RESURRECT_RESPONSE
CMSG_LOOT
CMSG_LOOT_MONEY
CMSG_LOOT_RELEASE
SMSG_LOOT_RESPONSE
SMSG_LOOT_RELEASE_RESPONSE
SMSG_LOOT_REMOVED
SMSG_LOOT_MONEY_NOTIFY
SMSG_LOOT_ITEM_NOTIFY
SMSG_LOOT_CLEAR_MONEY
SMSG_ITEM_PUSH_RESULT
SMSG_DUEL_REQUESTED
SMSG_DUEL_OUTOFBOUNDS
SMSG_DUEL_INBOUNDS
SMSG_DUEL_COMPLETE
SMSG_DUEL_WINNER
CMSG_DUEL_ACCEPTED
CMSG_DUEL_CANCELLED
SMSG_MOUNTRESULT
SMSG_DISMOUNTRESULT
SMSG_REMOVED_FROM_PVP_QUEUE
CMSG_MOUNTSPECIAL_ANIM
SMSG_MOUNTSPECIAL_ANIM
SMSG_PET_TAME_FAILURE
CMSG_PET_SET_ACTION
CMSG_PET_ACTION
CMSG_PET_ABANDON
CMSG_PET_RENAME
SMSG_PET_NAME_INVALID
SMSG_PET_SPELLS
SMSG_PET_MODE
CMSG_GOSSIP_HELLO
CMSG_GOSSIP_SELECT_OPTION
SMSG_GOSSIP_MESSAGE
SMSG_GOSSIP_COMPLETE
CMSG_NPC_TEXT_QUERY
SMSG_NPC_TEXT_UPDATE
SMSG_NPC_WONT_TALK
CMSG_QUESTGIVER_STATUS_QUERY
SMSG_QUESTGIVER_STATUS
CMSG_QUESTGIVER_HELLO
SMSG_QUESTGIVER_QUEST_LIST
CMSG_QUESTGIVER_QUERY_QUEST
CMSG_QUESTGIVER_QUEST_AUTOLAUNCH
SMSG_QUESTGIVER_QUEST_DETAILS
CMSG_QUESTGIVER_ACCEPT_QUEST
CMSG_QUESTGIVER_COMPLETE_QUEST
SMSG_QUESTGIVER_REQUEST_ITEMS
CMSG_QUESTGIVER_REQUEST_REWARD
SMSG_QUESTGIVER_OFFER_REWARD
CMSG_QUESTGIVER_CHOOSE_REWARD
SMSG_QUESTGIVER_QUEST_INVALID
CMSG_QUESTGIVER_CANCEL
SMSG_QUESTGIVER_QUEST_COMPLETE
SMSG_QUESTGIVER_QUEST_FAILED
CMSG_QUESTLOG_SWAP_QUEST
CMSG_QUESTLOG_REMOVE_QUEST
SMSG_QUESTLOG_FULL
SMSG_QUESTUPDATE_FAILED
SMSG_QUESTUPDATE_FAILEDTIMER
SMSG_QUESTUPDATE_COMPLETE
SMSG_QUESTUPDATE_ADD_KILL
SMSG_QUESTUPDATE_ADD_ITEM
CMSG_QUEST_CONFIRM_ACCEPT
SMSG_QUEST_CONFIRM_ACCEPT
CMSG_PUSHQUESTTOPARTY
CMSG_LIST_INVENTORY
SMSG_LIST_INVENTORY
CMSG_SELL_ITEM
SMSG_SELL_ITEM
CMSG_BUY_ITEM
CMSG_BUY_ITEM_IN_SLOT
SMSG_BUY_ITEM
SMSG_BUY_FAILED
CMSG_TAXICLEARALLNODES
CMSG_TAXIENABLEALLNODES
CMSG_TAXISHOWNODES
SMSG_SHOWTAXINODES
CMSG_TAXINODE_STATUS_QUERY
SMSG_TAXINODE_STATUS
CMSG_TAXIQUERYAVAILABLENODES
CMSG_ACTIVATETAXI
SMSG_ACTIVATETAXIREPLY
SMSG_NEW_TAXI_PATH
CMSG_TRAINER_LIST
SMSG_TRAINER_LIST
CMSG_TRAINER_BUY_SPELL
SMSG_TRAINER_BUY_SUCCEEDED
SMSG_TRAINER_BUY_FAILED
CMSG_BINDER_ACTIVATE
SMSG_PLAYERBINDERROR
CMSG_BANKER_ACTIVATE
SMSG_SHOW_BANK
CMSG_BUY_BANK_SLOT
SMSG_BUY_BANK_SLOT_RESULT
CMSG_PETITION_SHOWLIST
SMSG_PETITION_SHOWLIST
CMSG_PETITION_BUY
CMSG_PETITION_SHOW_SIGNATURES
SMSG_PETITION_SHOW_SIGNATURES
CMSG_PETITION_SIGN
SMSG_PETITION_SIGN_RESULTS
MSG_PETITION_DECLINE
CMSG_OFFER_PETITION
CMSG_TURN_IN_PETITION
SMSG_TURN_IN_PETITION_RESULTS
CMSG_PETITION_QUERY
SMSG_PETITION_QUERY_RESPONSE
SMSG_FISH_NOT_HOOKED
SMSG_FISH_ESCAPED
CMSG_BUG
SMSG_NOTIFICATION
CMSG_PLAYED_TIME
SMSG_PLAYED_TIME
CMSG_QUERY_TIME
SMSG_QUERY_TIME_RESPONSE
SMSG_LOG_XPGAIN
SMSG_AURACASTLOG
CMSG_RECLAIM_CORPSE
CMSG_WRAP_ITEM
SMSG_LEVELUP_INFO
MSG_MINIMAP_PING
SMSG_RESISTLOG
SMSG_ENCHANTMENTLOG
CMSG_SET_SKILL_CHEAT
SMSG_START_MIRROR_TIMER
SMSG_PAUSE_MIRROR_TIMER
SMSG_STOP_MIRROR_TIMER
CMSG_PING
SMSG_PONG
SMSG_CLEAR_COOLDOWN
SMSG_GAMEOBJECT_PAGETEXT
CMSG_SET_SHEATHED
SMSG_COOLDOWN_CHEAT
SMSG_SPELL_DELAYED
CMSG_QUEST_POI_QUERY
SMSG_QUEST_POI_QUERY_RESPONSE
CMSG_GHOST
CMSG_GM_INVIS
SMSG_INVALID_PROMOTION_CODE
MSG_GM_BIND_OTHER
MSG_GM_SUMMON
SMSG_ITEM_TIME_UPDATE
SMSG_ITEM_ENCHANT_TIME_UPDATE
SMSG_AUTH_CHALLENGE
CMSG_AUTH_SESSION
SMSG_AUTH_RESPONSE
MSG_GM_SHOWLABEL
CMSG_PET_CAST_SPELL
MSG_SAVE_GUILD_EMBLEM
MSG_TABARDVENDOR_ACTIVATE
SMSG_PLAY_SPELL_VISUAL
CMSG_ZONEUPDATE
SMSG_PARTYKILLLOG
SMSG_COMPRESSED_UPDATE_OBJECT
SMSG_PLAY_SPELL_IMPACT
SMSG_EXPLORATION_EXPERIENCE
CMSG_GM_SET_SECURITY_GROUP
CMSG_GM_NUKE
MSG_RANDOM_ROLL
SMSG_ENVIRONMENTAL_DAMAGE_LOG
CMSG_CHANGEPLAYER_DIFFICULTY
SMSG_RWHOIS
SMSG_LFG_PLAYER_REWARD
SMSG_LFG_TELEPORT_DENIED
CMSG_UNLEARN_SPELL
CMSG_UNLEARN_SKILL
SMSG_REMOVED_SPELL
CMSG_DECHARGE
CMSG_GMTICKET_CREATE
SMSG_GMTICKET_CREATE
CMSG_GMTICKET_UPDATETEXT
SMSG_GMTICKET_UPDATETEXT
SMSG_ACCOUNT_DATA_TIMES
CMSG_REQUEST_ACCOUNT_DATA
CMSG_UPDATE_ACCOUNT_DATA
SMSG_UPDATE_ACCOUNT_DATA
SMSG_CLEAR_FAR_SIGHT_IMMEDIATE
SMSG_CHANGEPLAYER_DIFFICULTY_RESULT
CMSG_GM_TEACH
CMSG_GM_CREATE_ITEM_TARGET
CMSG_GMTICKET_GETTICKET
SMSG_GMTICKET_GETTICKET
CMSG_UNLEARN_TALENTS
SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT
SMSG_GAMEOBJECT_DESPAWN_ANIM
MSG_CORPSE_QUERY
CMSG_GMTICKET_DELETETICKET
SMSG_GMTICKET_DELETETICKET
SMSG_CHAT_WRONG_FACTION
CMSG_GMTICKET_SYSTEMSTATUS
SMSG_GMTICKET_SYSTEMSTATUS
CMSG_SPIRIT_HEALER_ACTIVATE
CMSG_SET_STAT_CHEAT
SMSG_QUEST_FORCE_REMOVE
CMSG_SKILL_BUY_STEP
CMSG_SKILL_BUY_RANK
CMSG_XP_CHEAT
SMSG_SPIRIT_HEALER_CONFIRM
CMSG_CHARACTER_POINT_CHEAT
SMSG_GOSSIP_POI
CMSG_CHAT_IGNORED
CMSG_GM_VISION
CMSG_SERVER_COMMAND
CMSG_GM_SILENCE
CMSG_GM_REVEALTO
CMSG_GM_RESURRECT
CMSG_GM_SUMMONMOB
CMSG_GM_MOVECORPSE
CMSG_GM_FREEZE
CMSG_GM_UBERINVIS
CMSG_GM_REQUEST_PLAYER_INFO
SMSG_GM_PLAYER_INFO
CMSG_GUILD_RANK
CMSG_GUILD_ADD_RANK
CMSG_GUILD_DEL_RANK
CMSG_GUILD_SET_PUBLIC_NOTE
CMSG_GUILD_SET_OFFICER_NOTE
SMSG_LOGIN_VERIFY_WORLD
CMSG_CLEAR_EXPLORATION
CMSG_SEND_MAIL
SMSG_SEND_MAIL_RESULT
CMSG_GET_MAIL_LIST
SMSG_MAIL_LIST_RESULT
CMSG_BATTLEFIELD_LIST
SMSG_BATTLEFIELD_LIST
CMSG_BATTLEFIELD_JOIN
SMSG_FORCE_SET_VEHICLE_REC_ID
CMSG_SET_VEHICLE_REC_ID_ACK
CMSG_TAXICLEARNODE
CMSG_TAXIENABLENODE
CMSG_ITEM_TEXT_QUERY
SMSG_ITEM_TEXT_QUERY_RESPONSE
CMSG_MAIL_TAKE_MONEY
CMSG_MAIL_TAKE_ITEM
CMSG_MAIL_MARK_AS_READ
CMSG_MAIL_RETURN_TO_SENDER
CMSG_MAIL_DELETE
CMSG_MAIL_CREATE_TEXT_ITEM
SMSG_SPELLLOGMISS
SMSG_SPELLLOGEXECUTE
SMSG_DEBUGAURAPROC
SMSG_PERIODICAURALOG
SMSG_SPELLDAMAGESHIELD
SMSG_SPELLNONMELEEDAMAGELOG
CMSG_LEARN_TALENT
SMSG_RESURRECT_FAILED
CMSG_TOGGLE_PVP
SMSG_ZONE_UNDER_ATTACK
MSG_AUCTION_HELLO
CMSG_AUCTION_SELL_ITEM
CMSG_AUCTION_REMOVE_ITEM
CMSG_AUCTION_LIST_ITEMS
CMSG_AUCTION_LIST_OWNER_ITEMS
CMSG_AUCTION_PLACE_BID
SMSG_AUCTION_COMMAND_RESULT
SMSG_AUCTION_LIST_RESULT
SMSG_AUCTION_OWNER_LIST_RESULT
SMSG_AUCTION_BIDDER_NOTIFICATION
SMSG_AUCTION_OWNER_NOTIFICATION
SMSG_PROCRESIST
SMSG_COMBAT_EVENT_FAILED
SMSG_DISPEL_FAILED
SMSG_SPELLORDAMAGE_IMMUNE
CMSG_AUCTION_LIST_BIDDER_ITEMS
SMSG_AUCTION_BIDDER_LIST_RESULT
SMSG_SET_FLAT_SPELL_MODIFIER
SMSG_SET_PCT_SPELL_MODIFIER
CMSG_SET_AMMO
SMSG_CORPSE_RECLAIM_DELAY
CMSG_SET_ACTIVE_MOVER
CMSG_PET_CANCEL_AURA
CMSG_PLAYER_AI_CHEAT
CMSG_CANCEL_AUTO_REPEAT_SPELL
MSG_GM_ACCOUNT_ONLINE
MSG_LIST_STABLED_PETS
CMSG_STABLE_PET
CMSG_UNSTABLE_PET
CMSG_BUY_STABLE_SLOT
SMSG_STABLE_RESULT
CMSG_STABLE_REVIVE_PET
CMSG_STABLE_SWAP_PET
MSG_QUEST_PUSH_RESULT
SMSG_PLAY_MUSIC
SMSG_PLAY_OBJECT_SOUND
CMSG_REQUEST_PET_INFO
CMSG_FAR_SIGHT
SMSG_SPELLDISPELLOG
SMSG_DAMAGE_CALC_LOG
CMSG_ENABLE_DAMAGE_LOG
CMSG_GROUP_CHANGE_SUB_GROUP
CMSG_REQUEST_PARTY_MEMBER_STATS
CMSG_GROUP_SWAP_SUB_GROUP
CMSG_RESET_FACTION_CHEAT
CMSG_AUTOSTORE_BANK_ITEM
CMSG_AUTOBANK_ITEM
MSG_QUERY_NEXT_MAIL_TIME
SMSG_RECEIVED_MAIL
SMSG_RAID_GROUP_ONLY
CMSG_SET_DURABILITY_CHEAT
CMSG_SET_PVP_RANK_CHEAT
CMSG_ADD_PVP_MEDAL_CHEAT
CMSG_DEL_PVP_MEDAL_CHEAT
CMSG_SET_PVP_TITLE
SMSG_PVP_CREDIT
SMSG_AUCTION_REMOVED_NOTIFICATION
CMSG_GROUP_RAID_CONVERT
CMSG_GROUP_ASSISTANT_LEADER
CMSG_BUYBACK_ITEM
SMSG_CHAT_SERVER_MESSAGE
CMSG_SET_SAVED_INSTANCE_EXTEND
SMSG_LFG_OFFER_CONTINUE
CMSG_TEST_DROP_RATE
SMSG_TEST_DROP_RATE_RESULT
CMSG_LFG_GET_STATUS
SMSG_SHOW_MAILBOX
SMSG_RESET_RANGED_COMBAT_TIMER
SMSG_CHAT_NOT_IN_PARTY
CMSG_GMTICKETSYSTEM_TOGGLE
CMSG_CANCEL_GROWTH_AURA
SMSG_CANCEL_AUTO_REPEAT
SMSG_STANDSTATE_UPDATE
SMSG_LOOT_ALL_PASSED
SMSG_LOOT_ROLL_WON
CMSG_LOOT_ROLL
SMSG_LOOT_START_ROLL
SMSG_LOOT_ROLL
CMSG_LOOT_MASTER_GIVE
SMSG_LOOT_MASTER_LIST
SMSG_SET_FORCED_REACTIONS
SMSG_SPELL_FAILED_OTHER
SMSG_GAMEOBJECT_RESET_STATE
CMSG_REPAIR_ITEM
SMSG_CHAT_PLAYER_NOT_FOUND
MSG_TALENT_WIPE_CONFIRM
SMSG_SUMMON_REQUEST
CMSG_SUMMON_RESPONSE
MSG_DEV_SHOWLABEL
SMSG_MONSTER_MOVE_TRANSPORT
SMSG_PET_BROKEN
MSG_MOVE_FEATHER_FALL
MSG_MOVE_WATER_WALK
CMSG_SERVER_BROADCAST
CMSG_SELF_RES
SMSG_FEIGN_DEATH_RESISTED
CMSG_RUN_SCRIPT
SMSG_SCRIPT_MESSAGE
SMSG_DUEL_COUNTDOWN
SMSG_AREA_TRIGGER_MESSAGE
CMSG_SHOWING_HELM
CMSG_SHOWING_CLOAK
SMSG_LFG_ROLE_CHOSEN
SMSG_PLAYER_SKINNED
SMSG_DURABILITY_DAMAGE_DEATH
CMSG_SET_EXPLORATION
CMSG_SET_ACTIONBAR_TOGGLES
UMSG_DELETE_GUILD_CHARTER
MSG_PETITION_RENAME
SMSG_INIT_WORLD_STATES
SMSG_UPDATE_WORLD_STATE
CMSG_ITEM_NAME_QUERY
SMSG_ITEM_NAME_QUERY_RESPONSE
SMSG_PET_ACTION_FEEDBACK
CMSG_CHAR_RENAME
SMSG_CHAR_RENAME
CMSG_MOVE_SPLINE_DONE
CMSG_MOVE_FALL_RESET
SMSG_INSTANCE_SAVE_CREATED
SMSG_RAID_INSTANCE_INFO
CMSG_REQUEST_RAID_INFO
CMSG_MOVE_TIME_SKIPPED
CMSG_MOVE_FEATHER_FALL_ACK
CMSG_MOVE_WATER_WALK_ACK
CMSG_MOVE_NOT_ACTIVE_MOVER
SMSG_PLAY_SOUND
CMSG_BATTLEFIELD_STATUS
SMSG_BATTLEFIELD_STATUS
CMSG_BATTLEFIELD_PORT
MSG_INSPECT_HONOR_STATS
CMSG_BATTLEMASTER_HELLO
CMSG_MOVE_START_SWIM_CHEAT
CMSG_MOVE_STOP_SWIM_CHEAT
SMSG_FORCE_WALK_SPEED_CHANGE
CMSG_FORCE_WALK_SPEED_CHANGE_ACK
SMSG_FORCE_SWIM_BACK_SPEED_CHANGE
CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK
SMSG_FORCE_TURN_RATE_CHANGE
CMSG_FORCE_TURN_RATE_CHANGE_ACK
MSG_PVP_LOG_DATA
CMSG_LEAVE_BATTLEFIELD
CMSG_AREA_SPIRIT_HEALER_QUERY
CMSG_AREA_SPIRIT_HEALER_QUEUE
SMSG_AREA_SPIRIT_HEALER_TIME
CMSG_GM_UNTEACH
SMSG_WARDEN_DATA
CMSG_WARDEN_DATA
SMSG_GROUP_JOINED_BATTLEGROUND
MSG_BATTLEGROUND_PLAYER_POSITIONS
CMSG_PET_STOP_ATTACK
SMSG_BINDER_CONFIRM
SMSG_BATTLEGROUND_PLAYER_JOINED
SMSG_BATTLEGROUND_PLAYER_LEFT
CMSG_BATTLEMASTER_JOIN
SMSG_ADDON_INFO
CMSG_PET_UNLEARN
SMSG_PET_UNLEARN_CONFIRM
SMSG_PARTY_MEMBER_STATS_FULL
CMSG_PET_SPELL_AUTOCAST
SMSG_WEATHER
SMSG_PLAY_TIME_WARNING
SMSG_MINIGAME_SETUP
SMSG_MINIGAME_STATE
CMSG_MINIGAME_MOVE
SMSG_MINIGAME_MOVE_FAILED
SMSG_RAID_INSTANCE_MESSAGE
SMSG_COMPRESSED_MOVES
CMSG_GUILD_INFO_TEXT
SMSG_CHAT_RESTRICTED
SMSG_SPLINE_SET_RUN_SPEED
SMSG_SPLINE_SET_RUN_BACK_SPEED
SMSG_SPLINE_SET_SWIM_SPEED
SMSG_SPLINE_SET_WALK_SPEED
SMSG_SPLINE_SET_SWIM_BACK_SPEED
SMSG_SPLINE_SET_TURN_RATE
SMSG_SPLINE_MOVE_UNROOT
SMSG_SPLINE_MOVE_FEATHER_FALL
SMSG_SPLINE_MOVE_NORMAL_FALL
SMSG_SPLINE_MOVE_SET_HOVER
SMSG_SPLINE_MOVE_UNSET_HOVER
SMSG_SPLINE_MOVE_WATER_WALK
SMSG_SPLINE_MOVE_LAND_WALK
SMSG_SPLINE_MOVE_START_SWIM
SMSG_SPLINE_MOVE_STOP_SWIM
SMSG_SPLINE_MOVE_SET_RUN_MODE
SMSG_SPLINE_MOVE_SET_WALK_MODE
CMSG_GM_NUKE_ACCOUNT
MSG_GM_DESTROY_CORPSE
CMSG_GM_DESTROY_ONLINE_CORPSE
CMSG_ACTIVATETAXIEXPRESS
SMSG_SET_FACTION_ATWAR
SMSG_GAMETIMEBIAS_SET
CMSG_DEBUG_ACTIONS_START
CMSG_DEBUG_ACTIONS_STOP
CMSG_SET_FACTION_INACTIVE
CMSG_SET_WATCHED_FACTION
MSG_MOVE_TIME_SKIPPED
SMSG_SPLINE_MOVE_ROOT
CMSG_SET_EXPLORATION_ALL
SMSG_INVALIDATE_PLAYER
CMSG_RESET_INSTANCES
SMSG_INSTANCE_RESET
SMSG_INSTANCE_RESET_FAILED
SMSG_UPDATE_LAST_INSTANCE
MSG_RAID_TARGET_UPDATE
MSG_RAID_READY_CHECK
CMSG_LUA_USAGE
SMSG_PET_ACTION_SOUND
SMSG_PET_DISMISS_SOUND
SMSG_GHOSTEE_GONE
CMSG_GM_UPDATE_TICKET_STATUS
SMSG_GM_TICKET_STATUS_UPDATE
MSG_SET_DUNGEON_DIFFICULTY
CMSG_GMSURVEY_SUBMIT
SMSG_UPDATE_INSTANCE_OWNERSHIP
CMSG_IGNORE_KNOCKBACK_CHEAT
SMSG_CHAT_PLAYER_AMBIGUOUS
MSG_DELAY_GHOST_TELEPORT
SMSG_SPELLINSTAKILLLOG
SMSG_SPELL_UPDATE_CHAIN_TARGETS
CMSG_CHAT_FILTERED
SMSG_EXPECTED_SPAM_RECORDS
SMSG_SPELLSTEALLOG
CMSG_LOTTERY_QUERY_OBSOLETE
SMSG_LOTTERY_QUERY_RESULT_OBSOLETE
CMSG_BUY_LOTTERY_TICKET_OBSOLETE
SMSG_LOTTERY_RESULT_OBSOLETE
SMSG_CHARACTER_PROFILE
SMSG_CHARACTER_PROFILE_REALM_CONNECTED
SMSG_DEFENSE_MESSAGE
SMSG_INSTANCE_DIFFICULTY
MSG_GM_RESETINSTANCELIMIT
SMSG_MOTD
SMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY
SMSG_MOVE_UNSET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY
CMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY_ACK
MSG_MOVE_START_SWIM_CHEAT
MSG_MOVE_STOP_SWIM_CHEAT
SMSG_MOVE_SET_CAN_FLY
SMSG_MOVE_UNSET_CAN_FLY
CMSG_MOVE_SET_CAN_FLY_ACK
CMSG_MOVE_SET_FLY
CMSG_SOCKET_GEMS
CMSG_ARENA_TEAM_CREATE
SMSG_ARENA_TEAM_COMMAND_RESULT
MSG_MOVE_UPDATE_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY
CMSG_ARENA_TEAM_QUERY
SMSG_ARENA_TEAM_QUERY_RESPONSE
CMSG_ARENA_TEAM_ROSTER
SMSG_ARENA_TEAM_ROSTER
CMSG_ARENA_TEAM_INVITE
SMSG_ARENA_TEAM_INVITE
CMSG_ARENA_TEAM_ACCEPT
CMSG_ARENA_TEAM_DECLINE
CMSG_ARENA_TEAM_LEAVE
CMSG_ARENA_TEAM_REMOVE
CMSG_ARENA_TEAM_DISBAND
CMSG_ARENA_TEAM_LEADER
SMSG_ARENA_TEAM_EVENT
CMSG_BATTLEMASTER_JOIN_ARENA
MSG_MOVE_START_ASCEND
MSG_MOVE_STOP_ASCEND
SMSG_ARENA_TEAM_STATS
CMSG_LFG_JOIN
CMSG_LFG_LEAVE
CMSG_SEARCH_LFG_JOIN
CMSG_SEARCH_LFG_LEAVE
SMSG_UPDATE_LFG_LIST
SMSG_LFG_PROPOSAL_UPDATE
CMSG_LFG_PROPOSAL_RESULT
SMSG_LFG_ROLE_CHECK_UPDATE
SMSG_LFG_JOIN_RESULT
SMSG_LFG_QUEUE_STATUS
CMSG_SET_LFG_COMMENT
SMSG_LFG_UPDATE_PLAYER
SMSG_LFG_UPDATE_PARTY
SMSG_LFG_UPDATE_SEARCH
CMSG_LFG_SET_ROLES
CMSG_LFG_SET_NEEDS
CMSG_LFG_SET_BOOT_VOTE
SMSG_LFG_BOOT_PROPOSAL_UPDATE
CMSG_LFD_PLAYER_LOCK_INFO_REQUEST
SMSG_LFG_PLAYER_INFO
CMSG_LFG_TELEPORT
CMSG_LFD_PARTY_LOCK_INFO_REQUEST
SMSG_LFG_PARTY_INFO
SMSG_TITLE_EARNED
CMSG_SET_TITLE
CMSG_CANCEL_MOUNT_AURA
SMSG_ARENA_ERROR
MSG_INSPECT_ARENA_TEAMS
SMSG_DEATH_RELEASE_LOC
CMSG_CANCEL_TEMP_ENCHANTMENT
SMSG_FORCED_DEATH_UPDATE
CMSG_CHEAT_SET_HONOR_CURRENCY
CMSG_CHEAT_SET_ARENA_CURRENCY
MSG_MOVE_SET_FLIGHT_SPEED_CHEAT
MSG_MOVE_SET_FLIGHT_SPEED
MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT
MSG_MOVE_SET_FLIGHT_BACK_SPEED
SMSG_FORCE_FLIGHT_SPEED_CHANGE
CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK
SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE
CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK
SMSG_SPLINE_SET_FLIGHT_SPEED
SMSG_SPLINE_SET_FLIGHT_BACK_SPEED
CMSG_MAELSTROM_INVALIDATE_CACHE
SMSG_FLIGHT_SPLINE_SYNC
CMSG_SET_TAXI_BENCHMARK_MODE
SMSG_JOINED_BATTLEGROUND_QUEUE
SMSG_REALM_SPLIT
CMSG_REALM_SPLIT
CMSG_MOVE_CHNG_TRANSPORT
MSG_PARTY_ASSIGNMENT
SMSG_OFFER_PETITION_ERROR
SMSG_TIME_SYNC_REQ
CMSG_TIME_SYNC_RESP
CMSG_SEND_LOCAL_EVENT
CMSG_SEND_GENERAL_TRIGGER
CMSG_SEND_COMBAT_TRIGGER
CMSG_MAELSTROM_GM_SENT_MAIL
SMSG_RESET_FAILED_NOTIFY
SMSG_REAL_GROUP_UPDATE
SMSG_LFG_DISABLED
CMSG_ACTIVE_PVP_CHEAT
CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY
SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE
SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE
SMSG_UPDATE_COMBO_POINTS
SMSG_VOICE_SESSION_ROSTER_UPDATE
SMSG_VOICE_SESSION_LEAVE
SMSG_VOICE_SESSION_ADJUST_PRIORITY
CMSG_VOICE_SET_TALKER_MUTED_REQUEST
SMSG_VOICE_SET_TALKER_MUTED
SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE
SMSG_SET_EXTRA_AURA_INFO_OBSOLETE
SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE
SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE
MSG_MOVE_START_DESCEND
CMSG_IGNORE_REQUIREMENTS_CHEAT
SMSG_IGNORE_REQUIREMENTS_CHEAT
SMSG_SPELL_CHANCE_PROC_LOG
CMSG_MOVE_SET_RUN_SPEED
SMSG_DISMOUNT
MSG_MOVE_UPDATE_CAN_FLY
MSG_RAID_READY_CHECK_CONFIRM
CMSG_VOICE_SESSION_ENABLE
SMSG_VOICE_SESSION_ENABLE
SMSG_VOICE_PARENTAL_CONTROLS
CMSG_GM_WHISPER
SMSG_GM_MESSAGECHAT
MSG_GM_GEARRATING
CMSG_COMMENTATOR_ENABLE
SMSG_COMMENTATOR_STATE_CHANGED
CMSG_COMMENTATOR_GET_MAP_INFO
SMSG_COMMENTATOR_MAP_INFO
CMSG_COMMENTATOR_GET_PLAYER_INFO
SMSG_COMMENTATOR_GET_PLAYER_INFO
SMSG_COMMENTATOR_PLAYER_INFO
CMSG_COMMENTATOR_ENTER_INSTANCE
CMSG_COMMENTATOR_EXIT_INSTANCE
CMSG_COMMENTATOR_INSTANCE_COMMAND
SMSG_CLEAR_TARGET
CMSG_BOT_DETECTED
SMSG_CROSSED_INEBRIATION_THRESHOLD
CMSG_CHEAT_PLAYER_LOGIN
CMSG_CHEAT_PLAYER_LOOKUP
SMSG_CHEAT_PLAYER_LOOKUP
SMSG_KICK_REASON
MSG_RAID_READY_CHECK_FINISHED
CMSG_COMPLAIN
SMSG_COMPLAIN_RESULT
SMSG_FEATURE_SYSTEM_STATUS
CMSG_GM_SHOW_COMPLAINTS
CMSG_GM_UNSQUELCH
CMSG_CHANNEL_SILENCE_VOICE
CMSG_CHANNEL_SILENCE_ALL
CMSG_CHANNEL_UNSILENCE_VOICE
CMSG_CHANNEL_UNSILENCE_ALL
CMSG_TARGET_CAST
CMSG_TARGET_SCRIPT_CAST
CMSG_CHANNEL_DISPLAY_LIST
CMSG_SET_ACTIVE_VOICE_CHANNEL
CMSG_GET_CHANNEL_MEMBER_COUNT
SMSG_CHANNEL_MEMBER_COUNT
CMSG_CHANNEL_VOICE_ON
CMSG_CHANNEL_VOICE_OFF
CMSG_DEBUG_LIST_TARGETS
SMSG_DEBUG_LIST_TARGETS
SMSG_AVAILABLE_VOICE_CHANNEL
CMSG_ADD_VOICE_IGNORE
CMSG_DEL_VOICE_IGNORE
CMSG_PARTY_SILENCE
CMSG_PARTY_UNSILENCE
MSG_NOTIFY_PARTY_SQUELCH
SMSG_COMSAT_RECONNECT_TRY
SMSG_COMSAT_DISCONNECT
SMSG_COMSAT_CONNECT_FAIL
SMSG_VOICE_CHAT_STATUS
CMSG_REPORT_PVP_AFK
SMSG_REPORT_PVP_AFK_RESULT
CMSG_GUILD_BANKER_ACTIVATE
CMSG_GUILD_BANK_QUERY_TAB
SMSG_GUILD_BANK_LIST
CMSG_GUILD_BANK_SWAP_ITEMS
CMSG_GUILD_BANK_BUY_TAB
CMSG_GUILD_BANK_UPDATE_TAB
CMSG_GUILD_BANK_DEPOSIT_MONEY
CMSG_GUILD_BANK_WITHDRAW_MONEY
MSG_GUILD_BANK_LOG_QUERY
CMSG_SET_CHANNEL_WATCH
SMSG_USERLIST_ADD
SMSG_USERLIST_REMOVE
SMSG_USERLIST_UPDATE
CMSG_CLEAR_CHANNEL_WATCH
SMSG_INSPECT_TALENT
SMSG_GOGOGO_OBSOLETE
SMSG_ECHO_PARTY_SQUELCH
CMSG_SET_TITLE_SUFFIX
CMSG_SPELLCLICK
SMSG_LOOT_LIST
CMSG_GM_CHARACTER_RESTORE
CMSG_GM_CHARACTER_SAVE
SMSG_VOICESESSION_FULL
MSG_GUILD_PERMISSIONS
MSG_GUILD_BANK_MONEY_WITHDRAWN
MSG_GUILD_EVENT_LOG_QUERY
CMSG_MAELSTROM_RENAME_GUILD
CMSG_GET_MIRRORIMAGE_DATA
SMSG_MIRRORIMAGE_DATA
SMSG_FORCE_DISPLAY_UPDATE
SMSG_SPELL_CHANCE_RESIST_PUSHBACK
CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT
SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT
CMSG_KEEP_ALIVE
SMSG_RAID_READY_CHECK_ERROR
CMSG_OPT_OUT_OF_LOOT
MSG_QUERY_GUILD_BANK_TEXT
CMSG_SET_GUILD_BANK_TEXT
CMSG_SET_GRANTABLE_LEVELS
CMSG_GRANT_LEVEL
CMSG_REFER_A_FRIEND
MSG_GM_CHANGE_ARENA_RATING
CMSG_DECLINE_CHANNEL_INVITE
SMSG_GROUPACTION_THROTTLED
SMSG_OVERRIDE_LIGHT
SMSG_TOTEM_CREATED
CMSG_TOTEM_DESTROYED
CMSG_EXPIRE_RAID_INSTANCE
CMSG_NO_SPELL_VARIANCE
CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY
SMSG_QUESTGIVER_STATUS_MULTIPLE
CMSG_SET_PLAYER_DECLINED_NAMES
SMSG_SET_PLAYER_DECLINED_NAMES_RESULT
CMSG_QUERY_SERVER_BUCK_DATA
CMSG_CLEAR_SERVER_BUCK_DATA
SMSG_SERVER_BUCK_DATA
SMSG_SEND_UNLEARN_SPELLS
SMSG_PROPOSE_LEVEL_GRANT
CMSG_ACCEPT_LEVEL_GRANT
SMSG_REFER_A_FRIEND_FAILURE
SMSG_SPLINE_MOVE_SET_FLYING
SMSG_SPLINE_MOVE_UNSET_FLYING
SMSG_SUMMON_CANCEL
CMSG_CHANGE_PERSONAL_ARENA_RATING
CMSG_ALTER_APPEARANCE
SMSG_ENABLE_BARBER_SHOP
SMSG_BARBER_SHOP_RESULT
CMSG_CALENDAR_GET_CALENDAR
CMSG_CALENDAR_GET_EVENT
CMSG_CALENDAR_GUILD_FILTER
CMSG_CALENDAR_ARENA_TEAM
CMSG_CALENDAR_ADD_EVENT
CMSG_CALENDAR_UPDATE_EVENT
CMSG_CALENDAR_REMOVE_EVENT
CMSG_CALENDAR_COPY_EVENT
CMSG_CALENDAR_EVENT_INVITE
CMSG_CALENDAR_EVENT_RSVP
CMSG_CALENDAR_EVENT_REMOVE_INVITE
CMSG_CALENDAR_EVENT_STATUS
CMSG_CALENDAR_EVENT_MODERATOR_STATUS
SMSG_CALENDAR_SEND_CALENDAR
SMSG_CALENDAR_SEND_EVENT
SMSG_CALENDAR_FILTER_GUILD
SMSG_CALENDAR_ARENA_TEAM
SMSG_CALENDAR_EVENT_INVITE
SMSG_CALENDAR_EVENT_INVITE_REMOVED
SMSG_CALENDAR_EVENT_STATUS
SMSG_CALENDAR_COMMAND_RESULT
SMSG_CALENDAR_RAID_LOCKOUT_ADDED
SMSG_CALENDAR_RAID_LOCKOUT_REMOVED
SMSG_CALENDAR_EVENT_INVITE_ALERT
SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT
SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT
SMSG_CALENDAR_EVENT_REMOVED_ALERT
SMSG_CALENDAR_EVENT_UPDATED_ALERT
SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT
CMSG_CALENDAR_COMPLAIN
CMSG_CALENDAR_GET_NUM_PENDING
SMSG_CALENDAR_SEND_NUM_PENDING
CMSG_SAVE_DANCE
SMSG_NOTIFY_DANCE
CMSG_PLAY_DANCE
SMSG_PLAY_DANCE
CMSG_LOAD_DANCES
CMSG_STOP_DANCE
SMSG_STOP_DANCE
CMSG_SYNC_DANCE
CMSG_DANCE_QUERY
SMSG_DANCE_QUERY_RESPONSE
SMSG_INVALIDATE_DANCE
CMSG_DELETE_DANCE
SMSG_LEARNED_DANCE_MOVES
CMSG_LEARN_DANCE_MOVE
CMSG_UNLEARN_DANCE_MOVE
CMSG_SET_RUNE_COUNT
CMSG_SET_RUNE_COOLDOWN
MSG_MOVE_SET_PITCH_RATE_CHEAT
MSG_MOVE_SET_PITCH_RATE
SMSG_FORCE_PITCH_RATE_CHANGE
CMSG_FORCE_PITCH_RATE_CHANGE_ACK
SMSG_SPLINE_SET_PITCH_RATE
CMSG_CALENDAR_EVENT_INVITE_NOTES
SMSG_CALENDAR_EVENT_INVITE_NOTES
SMSG_CALENDAR_EVENT_INVITE_NOTES_ALERT
CMSG_UPDATE_MISSILE_TRAJECTORY
SMSG_UPDATE_ACCOUNT_DATA_COMPLETE
SMSG_TRIGGER_MOVIE
CMSG_COMPLETE_MOVIE
CMSG_SET_GLYPH_SLOT
CMSG_SET_GLYPH
SMSG_ACHIEVEMENT_EARNED
SMSG_DYNAMIC_DROP_ROLL_RESULT
SMSG_CRITERIA_UPDATE
CMSG_QUERY_INSPECT_ACHIEVEMENTS
SMSG_RESPOND_INSPECT_ACHIEVEMENTS
CMSG_DISMISS_CONTROLLED_VEHICLE
CMSG_COMPLETE_ACHIEVEMENT_CHEAT
SMSG_QUESTUPDATE_ADD_PVP_KILL
CMSG_SET_CRITERIA_CHEAT
SMSG_CALENDAR_RAID_LOCKOUT_UPDATED
CMSG_UNITANIMTIER_CHEAT
CMSG_CHAR_CUSTOMIZE
SMSG_CHAR_CUSTOMIZE
SMSG_PET_RENAMEABLE
CMSG_REQUEST_VEHICLE_EXIT
CMSG_REQUEST_VEHICLE_PREV_SEAT
CMSG_REQUEST_VEHICLE_NEXT_SEAT
CMSG_REQUEST_VEHICLE_SWITCH_SEAT
CMSG_PET_LEARN_TALENT
CMSG_PET_UNLEARN_TALENTS
SMSG_SET_PHASE_SHIFT
SMSG_ALL_ACHIEVEMENT_DATA
CMSG_FORCE_SAY_CHEAT
SMSG_HEALTH_UPDATE
SMSG_POWER_UPDATE
CMSG_GAMEOBJ_REPORT_USE
SMSG_HIGHEST_THREAT_UPDATE
SMSG_THREAT_UPDATE
SMSG_THREAT_REMOVE
SMSG_THREAT_CLEAR
SMSG_CONVERT_RUNE
SMSG_RESYNC_RUNES
SMSG_ADD_RUNE_POWER
CMSG_START_QUEST
CMSG_REMOVE_GLYPH
CMSG_DUMP_OBJECTS
SMSG_DUMP_OBJECTS_DATA
CMSG_DISMISS_CRITTER
SMSG_NOTIFY_DEST_LOC_SPELL_CAST
CMSG_AUCTION_LIST_PENDING_SALES
SMSG_AUCTION_LIST_PENDING_SALES
SMSG_MODIFY_COOLDOWN
SMSG_PET_UPDATE_COMBO_POINTS
CMSG_ENABLETAXI
SMSG_PRE_RESURRECT
SMSG_AURA_UPDATE_ALL
SMSG_AURA_UPDATE
CMSG_FLOOD_GRACE_CHEAT
SMSG_SERVER_FIRST_ACHIEVEMENT
SMSG_PET_LEARNED_SPELL
SMSG_PET_UNLEARNED_SPELL
CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE
CMSG_HEARTH_AND_RESURRECT
SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA
SMSG_CRITERIA_DELETED
SMSG_ACHIEVEMENT_DELETED
CMSG_SERVER_INFO_QUERY
SMSG_SERVER_INFO_RESPONSE
CMSG_CHECK_LOGIN_CRITERIA
SMSG_SERVER_BUCK_DATA_START
CMSG_SET_BREATH
CMSG_QUERY_VEHICLE_STATUS
SMSG_BATTLEGROUND_INFO_THROTTLED
SMSG_PLAYER_VEHICLE_DATA
CMSG_PLAYER_VEHICLE_ENTER
CMSG_CONTROLLER_EJECT_PASSENGER
SMSG_PET_GUIDS
SMSG_CLIENTCACHE_VERSION
CMSG_CHANGE_GDF_ARENA_RATING
CMSG_SET_ARENA_TEAM_RATING_BY_INDEX
CMSG_SET_ARENA_TEAM_WEEKLY_GAMES
CMSG_SET_ARENA_TEAM_SEASON_GAMES
CMSG_SET_ARENA_MEMBER_WEEKLY_GAMES
CMSG_SET_ARENA_MEMBER_SEASON_GAMES
SMSG_ITEM_REFUND_INFO_RESPONSE
CMSG_ITEM_REFUND_INFO
CMSG_ITEM_REFUND
SMSG_ITEM_REFUND_RESULT
CMSG_CORPSE_MAP_POSITION_QUERY
SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE
CMSG_UNUSED5
CMSG_UNUSED6
CMSG_CALENDAR_EVENT_SIGNUP
SMSG_CALENDAR_CLEAR_PENDING_ACTION
SMSG_EQUIPMENT_SET_LIST
CMSG_EQUIPMENT_SET_SAVE
CMSG_UPDATE_PROJECTILE_POSITION
SMSG_SET_PROJECTILE_POSITION
SMSG_TALENTS_INFO
CMSG_LEARN_PREVIEW_TALENTS
CMSG_LEARN_PREVIEW_TALENTS_PET
CMSG_SET_ACTIVE_TALENT_GROUP_OBSOLETE
CMSG_GM_GRANT_ACHIEVEMENT
CMSG_GM_REMOVE_ACHIEVEMENT
CMSG_GM_SET_CRITERIA_FOR_PLAYER
SMSG_ARENA_UNIT_DESTROYED
SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED
CMSG_PROFILEDATA_REQUEST
SMSG_PROFILEDATA_RESPONSE
CMSG_START_BATTLEFIELD_CHEAT
CMSG_END_BATTLEFIELD_CHEAT
SMSG_MULTIPLE_PACKETS
SMSG_MOVE_GRAVITY_DISABLE
CMSG_MOVE_GRAVITY_DISABLE_ACK
SMSG_MOVE_GRAVITY_ENABLE
CMSG_MOVE_GRAVITY_ENABLE_ACK
MSG_MOVE_GRAVITY_CHNG
SMSG_SPLINE_MOVE_GRAVITY_DISABLE
SMSG_SPLINE_MOVE_GRAVITY_ENABLE
CMSG_EQUIPMENT_SET_USE
SMSG_EQUIPMENT_SET_USE_RESULT
CMSG_FORCE_ANIM
SMSG_FORCE_ANIM
CMSG_CHAR_FACTION_CHANGE
SMSG_CHAR_FACTION_CHANGE
CMSG_PVP_QUEUE_STATS_REQUEST
SMSG_PVP_QUEUE_STATS
CMSG_SET_PAID_SERVICE_CHEAT
SMSG_BATTLEFIELD_MGR_ENTRY_INVITE
CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE
SMSG_BATTLEFIELD_MGR_ENTERED
SMSG_BATTLEFIELD_MGR_QUEUE_INVITE
CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE
CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST
SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE
SMSG_BATTLEFIELD_MGR_EJECT_PENDING
SMSG_BATTLEFIELD_MGR_EJECTED
CMSG_BATTLEFIELD_MGR_EXIT_REQUEST
SMSG_BATTLEFIELD_MGR_STATE_CHANGE
CMSG_BATTLEFIELD_MANAGER_ADVANCE_STATE
CMSG_BATTLEFIELD_MANAGER_SET_NEXT_TRANSITION_TIME
MSG_SET_RAID_DIFFICULTY
CMSG_TOGGLE_XP_GAIN
SMSG_TOGGLE_XP_GAIN
SMSG_GMRESPONSE_DB_ERROR
SMSG_GMRESPONSE_RECEIVED
CMSG_GMRESPONSE_RESOLVE
SMSG_GMRESPONSE_STATUS_UPDATE
SMSG_GMRESPONSE_CREATE_TICKET
CMSG_GMRESPONSE_CREATE_TICKET
CMSG_SERVERINFO
SMSG_SERVERINFO
CMSG_WORLD_STATE_UI_TIMER_UPDATE
SMSG_WORLD_STATE_UI_TIMER_UPDATE
CMSG_CHAR_RACE_CHANGE
MSG_VIEW_PHASE_SHIFT
SMSG_TALENTS_INVOLUNTARILY_RESET
CMSG_DEBUG_SERVER_GEO
SMSG_DEBUG_SERVER_GEO
SMSG_LOOT_SLOT_CHANGED
UMSG_UPDATE_GROUP_INFO
CMSG_READY_FOR_ACCOUNT_DATA_TIMES
CMSG_QUERY_QUESTS_COMPLETED
SMSG_QUERY_QUESTS_COMPLETED_RESPONSE
CMSG_GM_REPORT_LAG
CMSG_AFK_MONITOR_INFO_REQUEST
SMSG_AFK_MONITOR_INFO_RESPONSE
CMSG_AFK_MONITOR_INFO_CLEAR
SMSG_CORPSE_NOT_IN_INSTANCE
CMSG_GM_NUKE_CHARACTER
CMSG_SET_ALLOW_LOW_LEVEL_RAID1
CMSG_SET_ALLOW_LOW_LEVEL_RAID2
SMSG_CAMERA_SHAKE
SMSG_SOCKET_GEMS_RESULT
CMSG_SET_CHARACTER_MODEL
SMSG_REDIRECT_CLIENT
CMSG_REDIRECTION_FAILED
SMSG_SUSPEND_COMMS
CMSG_SUSPEND_COMMS_ACK
SMSG_FORCE_SEND_QUEUED_PACKETS
CMSG_REDIRECTION_AUTH_PROOF
CMSG_DROP_NEW_CONNECTION
SMSG_SEND_ALL_COMBAT_LOG
SMSG_OPEN_LFG_DUNGEON_FINDER
SMSG_MOVE_SET_COLLISION_HGT
CMSG_MOVE_SET_COLLISION_HGT_ACK
MSG_MOVE_SET_COLLISION_HGT
CMSG_CLEAR_RANDOM_BG_WIN_TIME
CMSG_CLEAR_HOLIDAY_BG_WIN_TIME
CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND
SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT1
SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT2
SMSG_MULTIPLE_MOVES
NUM_MSG_TYPES
{
    CMSG_BOOTME                                     = 0x001,
    CMSG_DBLOOKUP                                   = 0x002,
    SMSG_DBLOOKUP                                   = 0x003,
    CMSG_QUERY_OBJECT_POSITION                      = 0x004,
    SMSG_QUERY_OBJECT_POSITION                      = 0x005,
    CMSG_QUERY_OBJECT_ROTATION                      = 0x006,
    SMSG_QUERY_OBJECT_ROTATION                      = 0x007,
    CMSG_WORLD_TELEPORT                             = 0x008,
    CMSG_TELEPORT_TO_UNIT                           = 0x009,
    CMSG_ZONE_MAP                                   = 0x00A,
    SMSG_ZONE_MAP                                   = 0x00B,
    CMSG_DEBUG_CHANGECELLZONE                       = 0x00C,
    CMSG_MOVE_CHARACTER_CHEAT                       = 0x00D,
    SMSG_MOVE_CHARACTER_CHEAT                       = 0x00E,
    CMSG_RECHARGE                                   = 0x00F,
    CMSG_LEARN_SPELL                                = 0x010,
    CMSG_CREATEMONSTER                              = 0x011,
    CMSG_DESTROYMONSTER                             = 0x012,
    CMSG_CREATEITEM                                 = 0x013,
    CMSG_CREATEGAMEOBJECT                           = 0x014,
    SMSG_CHECK_FOR_BOTS                             = 0x015,
    CMSG_MAKEMONSTERATTACKGUID                      = 0x016,
    CMSG_BOT_DETECTED2                              = 0x017,
    CMSG_FORCEACTION                                = 0x018,
    CMSG_FORCEACTIONONOTHER                         = 0x019,
    CMSG_FORCEACTIONSHOW                            = 0x01A,
    SMSG_FORCEACTIONSHOW                            = 0x01B,
    CMSG_PETGODMODE                                 = 0x01C,
    SMSG_PETGODMODE                                 = 0x01D,
    SMSG_REFER_A_FRIEND_EXPIRED                     = 0x01E,
    CMSG_WEATHER_SPEED_CHEAT                        = 0x01F,
    CMSG_UNDRESSPLAYER                              = 0x020,
    CMSG_BEASTMASTER                                = 0x021,
    CMSG_GODMODE                                    = 0x022,
    SMSG_GODMODE                                    = 0x023,
    CMSG_CHEAT_SETMONEY                             = 0x024,
    CMSG_LEVEL_CHEAT                                = 0x025,
    CMSG_PET_LEVEL_CHEAT                            = 0x026,
    CMSG_SET_WORLDSTATE                             = 0x027,
    CMSG_COOLDOWN_CHEAT                             = 0x028,
    CMSG_USE_SKILL_CHEAT                            = 0x029,
    CMSG_FLAG_QUEST                                 = 0x02A,
    CMSG_FLAG_QUEST_FINISH                          = 0x02B,
    CMSG_CLEAR_QUEST                                = 0x02C,
    CMSG_SEND_EVENT                                 = 0x02D,
    CMSG_DEBUG_AISTATE                              = 0x02E,
    SMSG_DEBUG_AISTATE                              = 0x02F,
    CMSG_DISABLE_PVP_CHEAT                          = 0x030,
    CMSG_ADVANCE_SPAWN_TIME                         = 0x031,
    SMSG_DESTRUCTIBLE_BUILDING_DAMAGE               = 0x032,
    CMSG_AUTH_SRP6_BEGIN                            = 0x033,
    CMSG_AUTH_SRP6_PROOF                            = 0x034,
    CMSG_AUTH_SRP6_RECODE                           = 0x035,
    CMSG_CHAR_CREATE                                = 0x036,
    CMSG_CHAR_ENUM                                  = 0x037,
    CMSG_CHAR_DELETE                                = 0x038,
    SMSG_AUTH_SRP6_RESPONSE                         = 0x039,
    SMSG_CHAR_CREATE                                = 0x03A,
    SMSG_CHAR_ENUM                                  = 0x03B,
    SMSG_CHAR_DELETE                                = 0x03C,
    CMSG_PLAYER_LOGIN                               = 0x03D,
    SMSG_NEW_WORLD                                  = 0x03E,
    SMSG_TRANSFER_PENDING                           = 0x03F,
    SMSG_TRANSFER_ABORTED                           = 0x040,
    SMSG_CHARACTER_LOGIN_FAILED                     = 0x041,
    SMSG_LOGIN_SETTIMESPEED                         = 0x042,
    SMSG_GAMETIME_UPDATE                            = 0x043,
    CMSG_GAMETIME_SET                               = 0x044,
    SMSG_GAMETIME_SET                               = 0x045,
    CMSG_GAMESPEED_SET                              = 0x046,
    SMSG_GAMESPEED_SET                              = 0x047,
    CMSG_SERVERTIME                                 = 0x048,
    SMSG_SERVERTIME                                 = 0x049,
    CMSG_PLAYER_LOGOUT                              = 0x04A,
    CMSG_LOGOUT_REQUEST                             = 0x04B,
    SMSG_LOGOUT_RESPONSE                            = 0x04C,
    SMSG_LOGOUT_COMPLETE                            = 0x04D,
    CMSG_LOGOUT_CANCEL                              = 0x04E,
    SMSG_LOGOUT_CANCEL_ACK                          = 0x04F,
    CMSG_NAME_QUERY                                 = 0x050,
    SMSG_NAME_QUERY_RESPONSE                        = 0x051,
    CMSG_PET_NAME_QUERY                             = 0x052,
    SMSG_PET_NAME_QUERY_RESPONSE                    = 0x053,
    CMSG_GUILD_QUERY                                = 0x054,
    SMSG_GUILD_QUERY_RESPONSE                       = 0x055,
    CMSG_ITEM_QUERY_SINGLE                          = 0x056,
    CMSG_ITEM_QUERY_MULTIPLE                        = 0x057,
    SMSG_ITEM_QUERY_SINGLE_RESPONSE                 = 0x058,
    SMSG_ITEM_QUERY_MULTIPLE_RESPONSE               = 0x059,
    CMSG_PAGE_TEXT_QUERY                            = 0x05A,
    SMSG_PAGE_TEXT_QUERY_RESPONSE                   = 0x05B,
    CMSG_QUEST_QUERY                                = 0x05C,
    SMSG_QUEST_QUERY_RESPONSE                       = 0x05D,
    CMSG_GAMEOBJECT_QUERY                           = 0x05E,
    SMSG_GAMEOBJECT_QUERY_RESPONSE                  = 0x05F,
    CMSG_CREATURE_QUERY                             = 0x060,
    SMSG_CREATURE_QUERY_RESPONSE                    = 0x061,
    CMSG_WHO                                        = 0x062,
    SMSG_WHO                                        = 0x063,
    CMSG_WHOIS                                      = 0x064,
    SMSG_WHOIS                                      = 0x065,
    CMSG_CONTACT_LIST                               = 0x066,
    SMSG_CONTACT_LIST                               = 0x067,
    SMSG_FRIEND_STATUS                              = 0x068,
    CMSG_ADD_FRIEND                                 = 0x069,
    CMSG_DEL_FRIEND                                 = 0x06A,
    CMSG_SET_CONTACT_NOTES                          = 0x06B,
    CMSG_ADD_IGNORE                                 = 0x06C,
    CMSG_DEL_IGNORE                                 = 0x06D,
    CMSG_GROUP_INVITE                               = 0x06E,
    SMSG_GROUP_INVITE                               = 0x06F,
    CMSG_GROUP_CANCEL                               = 0x070,
    SMSG_GROUP_CANCEL                               = 0x071,
    CMSG_GROUP_ACCEPT                               = 0x072,
    CMSG_GROUP_DECLINE                              = 0x073,
    SMSG_GROUP_DECLINE                              = 0x074,
    CMSG_GROUP_UNINVITE                             = 0x075,
    CMSG_GROUP_UNINVITE_GUID                        = 0x076,
    SMSG_GROUP_UNINVITE                             = 0x077,
    CMSG_GROUP_SET_LEADER                           = 0x078,
    SMSG_GROUP_SET_LEADER                           = 0x079,
    CMSG_LOOT_METHOD                                = 0x07A,
    CMSG_GROUP_DISBAND                              = 0x07B,
    SMSG_GROUP_DESTROYED                            = 0x07C,
    SMSG_GROUP_LIST                                 = 0x07D,
    SMSG_PARTY_MEMBER_STATS                         = 0x07E,
    SMSG_PARTY_COMMAND_RESULT                       = 0x07F,
    UMSG_UPDATE_GROUP_MEMBERS                       = 0x080,
    CMSG_GUILD_CREATE                               = 0x081,
    CMSG_GUILD_INVITE                               = 0x082,
    SMSG_GUILD_INVITE                               = 0x083,
    CMSG_GUILD_ACCEPT                               = 0x084,
    CMSG_GUILD_DECLINE                              = 0x085,
    SMSG_GUILD_DECLINE                              = 0x086,
    CMSG_GUILD_INFO                                 = 0x087,
    SMSG_GUILD_INFO                                 = 0x088,
    CMSG_GUILD_ROSTER                               = 0x089,
    SMSG_GUILD_ROSTER                               = 0x08A,
    CMSG_GUILD_PROMOTE                              = 0x08B,
    CMSG_GUILD_DEMOTE                               = 0x08C,
    CMSG_GUILD_LEAVE                                = 0x08D,
    CMSG_GUILD_REMOVE                               = 0x08E,
    CMSG_GUILD_DISBAND                              = 0x08F,
    CMSG_GUILD_LEADER                               = 0x090,
    CMSG_GUILD_MOTD                                 = 0x091,
    SMSG_GUILD_EVENT                                = 0x092,
    SMSG_GUILD_COMMAND_RESULT                       = 0x093,
    UMSG_UPDATE_GUILD                               = 0x094,
    CMSG_MESSAGECHAT                                = 0x095,
    SMSG_MESSAGECHAT                                = 0x096,
    CMSG_JOIN_CHANNEL                               = 0x097,
    CMSG_LEAVE_CHANNEL                              = 0x098,
    SMSG_CHANNEL_NOTIFY                             = 0x099,
    CMSG_CHANNEL_LIST                               = 0x09A,
    SMSG_CHANNEL_LIST                               = 0x09B,
    CMSG_CHANNEL_PASSWORD                           = 0x09C,
    CMSG_CHANNEL_SET_OWNER                          = 0x09D,
    CMSG_CHANNEL_OWNER                              = 0x09E,
    CMSG_CHANNEL_MODERATOR                          = 0x09F,
    CMSG_CHANNEL_UNMODERATOR                        = 0x0A0,
    CMSG_CHANNEL_MUTE                               = 0x0A1,
    CMSG_CHANNEL_UNMUTE                             = 0x0A2,
    CMSG_CHANNEL_INVITE                             = 0x0A3,
    CMSG_CHANNEL_KICK                               = 0x0A4,
    CMSG_CHANNEL_BAN                                = 0x0A5,
    CMSG_CHANNEL_UNBAN                              = 0x0A6,
    CMSG_CHANNEL_ANNOUNCEMENTS                      = 0x0A7,
    CMSG_CHANNEL_MODERATE                           = 0x0A8,
    SMSG_UPDATE_OBJECT                              = 0x0A9,
    SMSG_DESTROY_OBJECT                             = 0x0AA,
    CMSG_USE_ITEM                                   = 0x0AB,
    CMSG_OPEN_ITEM                                  = 0x0AC,
    CMSG_READ_ITEM                                  = 0x0AD,
    SMSG_READ_ITEM_OK                               = 0x0AE,
    SMSG_READ_ITEM_FAILED                           = 0x0AF,
    SMSG_ITEM_COOLDOWN                              = 0x0B0,
    CMSG_GAMEOBJ_USE                                = 0x0B1,
    CMSG_DESTROY_ITEMS                              = 0x0B2,
    SMSG_GAMEOBJECT_CUSTOM_ANIM                     = 0x0B3,
    CMSG_AREATRIGGER                                = 0x0B4,
    MSG_MOVE_START_FORWARD                          = 0x0B5,
    MSG_MOVE_START_BACKWARD                         = 0x0B6,
    MSG_MOVE_STOP                                   = 0x0B7,
    MSG_MOVE_START_STRAFE_LEFT                      = 0x0B8,
    MSG_MOVE_START_STRAFE_RIGHT                     = 0x0B9,
    MSG_MOVE_STOP_STRAFE                            = 0x0BA,
    MSG_MOVE_JUMP                                   = 0x0BB,
    MSG_MOVE_START_TURN_LEFT                        = 0x0BC,
    MSG_MOVE_START_TURN_RIGHT                       = 0x0BD,
    MSG_MOVE_STOP_TURN                              = 0x0BE,
    MSG_MOVE_START_PITCH_UP                         = 0x0BF,
    MSG_MOVE_START_PITCH_DOWN                       = 0x0C0,
    MSG_MOVE_STOP_PITCH                             = 0x0C1,
    MSG_MOVE_SET_RUN_MODE                           = 0x0C2,
    MSG_MOVE_SET_WALK_MODE                          = 0x0C3,
    MSG_MOVE_TOGGLE_LOGGING                         = 0x0C4,
    MSG_MOVE_TELEPORT                               = 0x0C5,
    MSG_MOVE_TELEPORT_CHEAT                         = 0x0C6,
    MSG_MOVE_TELEPORT_ACK                           = 0x0C7,
    MSG_MOVE_TOGGLE_FALL_LOGGING                    = 0x0C8,
    MSG_MOVE_FALL_LAND                              = 0x0C9,
    MSG_MOVE_START_SWIM                             = 0x0CA,
    MSG_MOVE_STOP_SWIM                              = 0x0CB,
    MSG_MOVE_SET_RUN_SPEED_CHEAT                    = 0x0CC,
    MSG_MOVE_SET_RUN_SPEED                          = 0x0CD,
    MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT               = 0x0CE,
    MSG_MOVE_SET_RUN_BACK_SPEED                     = 0x0CF,
    MSG_MOVE_SET_WALK_SPEED_CHEAT                   = 0x0D0,
    MSG_MOVE_SET_WALK_SPEED                         = 0x0D1,
    MSG_MOVE_SET_SWIM_SPEED_CHEAT                   = 0x0D2,
    MSG_MOVE_SET_SWIM_SPEED                         = 0x0D3,
    MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT              = 0x0D4,
    MSG_MOVE_SET_SWIM_BACK_SPEED                    = 0x0D5,
    MSG_MOVE_SET_ALL_SPEED_CHEAT                    = 0x0D6,
    MSG_MOVE_SET_TURN_RATE_CHEAT                    = 0x0D7,
    MSG_MOVE_SET_TURN_RATE                          = 0x0D8,
    MSG_MOVE_TOGGLE_COLLISION_CHEAT                 = 0x0D9,
    MSG_MOVE_SET_FACING                             = 0x0DA,
    MSG_MOVE_SET_PITCH                              = 0x0DB,
    MSG_MOVE_WORLDPORT_ACK                          = 0x0DC,
    SMSG_MONSTER_MOVE                               = 0x0DD,
    SMSG_MOVE_WATER_WALK                            = 0x0DE,
    SMSG_MOVE_LAND_WALK                             = 0x0DF,
    CMSG_MOVE_CHARM_PORT_CHEAT                      = 0x0E0,
    CMSG_MOVE_SET_RAW_POSITION                      = 0x0E1,
    SMSG_FORCE_RUN_SPEED_CHANGE                     = 0x0E2,
    CMSG_FORCE_RUN_SPEED_CHANGE_ACK                 = 0x0E3,
    SMSG_FORCE_RUN_BACK_SPEED_CHANGE                = 0x0E4,
    CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK            = 0x0E5,
    SMSG_FORCE_SWIM_SPEED_CHANGE                    = 0x0E6,
    CMSG_FORCE_SWIM_SPEED_CHANGE_ACK                = 0x0E7,
    SMSG_FORCE_MOVE_ROOT                            = 0x0E8,
    CMSG_FORCE_MOVE_ROOT_ACK                        = 0x0E9,
    SMSG_FORCE_MOVE_UNROOT                          = 0x0EA,
    CMSG_FORCE_MOVE_UNROOT_ACK                      = 0x0EB,
    MSG_MOVE_ROOT                                   = 0x0EC,
    MSG_MOVE_UNROOT                                 = 0x0ED,
    MSG_MOVE_HEARTBEAT                              = 0x0EE,
    SMSG_MOVE_KNOCK_BACK                            = 0x0EF,
    CMSG_MOVE_KNOCK_BACK_ACK                        = 0x0F0,
    MSG_MOVE_KNOCK_BACK                             = 0x0F1,
    SMSG_MOVE_FEATHER_FALL                          = 0x0F2,
    SMSG_MOVE_NORMAL_FALL                           = 0x0F3,
    SMSG_MOVE_SET_HOVER                             = 0x0F4,
    SMSG_MOVE_UNSET_HOVER                           = 0x0F5,
    CMSG_MOVE_HOVER_ACK                             = 0x0F6,
    MSG_MOVE_HOVER                                  = 0x0F7,
    CMSG_TRIGGER_CINEMATIC_CHEAT                    = 0x0F8,
    CMSG_OPENING_CINEMATIC                          = 0x0F9,
    SMSG_TRIGGER_CINEMATIC                          = 0x0FA,
    CMSG_NEXT_CINEMATIC_CAMERA                      = 0x0FB,
    CMSG_COMPLETE_CINEMATIC                         = 0x0FC,
    SMSG_TUTORIAL_FLAGS                             = 0x0FD,
    CMSG_TUTORIAL_FLAG                              = 0x0FE,
    CMSG_TUTORIAL_CLEAR                             = 0x0FF,
    CMSG_TUTORIAL_RESET                             = 0x100,
    CMSG_STANDSTATECHANGE                           = 0x101,
    CMSG_EMOTE                                      = 0x102,
    SMSG_EMOTE                                      = 0x103,
    CMSG_TEXT_EMOTE                                 = 0x104,
    SMSG_TEXT_EMOTE                                 = 0x105,
    CMSG_AUTOEQUIP_GROUND_ITEM                      = 0x106,
    CMSG_AUTOSTORE_GROUND_ITEM                      = 0x107,
    CMSG_AUTOSTORE_LOOT_ITEM                        = 0x108,
    CMSG_STORE_LOOT_IN_SLOT                         = 0x109,
    CMSG_AUTOEQUIP_ITEM                             = 0x10A,
    CMSG_AUTOSTORE_BAG_ITEM                         = 0x10B,
    CMSG_SWAP_ITEM                                  = 0x10C,
    CMSG_SWAP_INV_ITEM                              = 0x10D,
    CMSG_SPLIT_ITEM                                 = 0x10E,
    CMSG_AUTOEQUIP_ITEM_SLOT                        = 0x10F,
    CMSG_UNCLAIM_LICENSE                            = 0x110,
    CMSG_DESTROYITEM                                = 0x111,
    SMSG_INVENTORY_CHANGE_FAILURE                   = 0x112,
    SMSG_OPEN_CONTAINER                             = 0x113,
    CMSG_INSPECT                                    = 0x114,
    SMSG_INSPECT_RESULTS_UPDATE                     = 0x115,
    CMSG_INITIATE_TRADE                             = 0x116,
    CMSG_BEGIN_TRADE                                = 0x117,
    CMSG_BUSY_TRADE                                 = 0x118,
    CMSG_IGNORE_TRADE                               = 0x119,
    CMSG_ACCEPT_TRADE                               = 0x11A,
    CMSG_UNACCEPT_TRADE                             = 0x11B,
    CMSG_CANCEL_TRADE                               = 0x11C,
    CMSG_SET_TRADE_ITEM                             = 0x11D,
    CMSG_CLEAR_TRADE_ITEM                           = 0x11E,
    CMSG_SET_TRADE_GOLD                             = 0x11F,
    SMSG_TRADE_STATUS                               = 0x120,
    SMSG_TRADE_STATUS_EXTENDED                      = 0x121,
    SMSG_INITIALIZE_FACTIONS                        = 0x122,
    SMSG_SET_FACTION_VISIBLE                        = 0x123,
    SMSG_SET_FACTION_STANDING                       = 0x124,
    CMSG_SET_FACTION_ATWAR                          = 0x125,
    CMSG_SET_FACTION_CHEAT                          = 0x126,
    SMSG_SET_PROFICIENCY                            = 0x127,
    CMSG_SET_ACTION_BUTTON                          = 0x128,
    SMSG_ACTION_BUTTONS                             = 0x129,
    SMSG_INITIAL_SPELLS                             = 0x12A,
    SMSG_LEARNED_SPELL                              = 0x12B,
    SMSG_SUPERCEDED_SPELL                           = 0x12C,
    CMSG_NEW_SPELL_SLOT                             = 0x12D,
    CMSG_CAST_SPELL                                 = 0x12E,
    CMSG_CANCEL_CAST                                = 0x12F,
    SMSG_CAST_FAILED                                = 0x130,
    SMSG_SPELL_START                                = 0x131,
    SMSG_SPELL_GO                                   = 0x132,
    SMSG_SPELL_FAILURE                              = 0x133,
    SMSG_SPELL_COOLDOWN                             = 0x134,
    SMSG_COOLDOWN_EVENT                             = 0x135,
    CMSG_CANCEL_AURA                                = 0x136,
    SMSG_EQUIPMENT_SET_SAVED                        = 0x137,
    SMSG_PET_CAST_FAILED                            = 0x138,
    MSG_CHANNEL_START                               = 0x139,
    MSG_CHANNEL_UPDATE                              = 0x13A,
    CMSG_CANCEL_CHANNELLING                         = 0x13B,
    SMSG_AI_REACTION                                = 0x13C,
    CMSG_SET_SELECTION                              = 0x13D,
    CMSG_DELETEEQUIPMENT_SET                        = 0x13E,
    CMSG_INSTANCE_LOCK_RESPONSE                     = 0x13F,
    CMSG_DEBUG_PASSIVE_AURA                         = 0x140,
    CMSG_ATTACKSWING                                = 0x141,
    CMSG_ATTACKSTOP                                 = 0x142,
    SMSG_ATTACKSTART                                = 0x143,
    SMSG_ATTACKSTOP                                 = 0x144,
    SMSG_ATTACKSWING_NOTINRANGE                     = 0x145,
    SMSG_ATTACKSWING_BADFACING                      = 0x146,
    SMSG_INSTANCE_LOCK_WARNING_QUERY                = 0x147,
    SMSG_ATTACKSWING_DEADTARGET                     = 0x148,
    SMSG_ATTACKSWING_CANT_ATTACK                    = 0x149,
    SMSG_ATTACKERSTATEUPDATE                        = 0x14A,
    SMSG_BATTLEFIELD_PORT_DENIED                    = 0x14B,
    CMSG_PERFORM_ACTION_SET                         = 0x14C,
    SMSG_RESUME_CAST_BAR                            = 0x14D,
    SMSG_CANCEL_COMBAT                              = 0x14E,
    SMSG_SPELLBREAKLOG                              = 0x14F,
    SMSG_SPELLHEALLOG                               = 0x150,
    SMSG_SPELLENERGIZELOG                           = 0x151,
    SMSG_BREAK_TARGET                               = 0x152,
    CMSG_SAVE_PLAYER                                = 0x153,
    CMSG_SETDEATHBINDPOINT                          = 0x154,
    SMSG_BINDPOINTUPDATE                            = 0x155,
    CMSG_GETDEATHBINDZONE                           = 0x156,
    SMSG_BINDZONEREPLY                              = 0x157,
    SMSG_PLAYERBOUND                                = 0x158,
    SMSG_CLIENT_CONTROL_UPDATE                      = 0x159,
    CMSG_REPOP_REQUEST                              = 0x15A,
    SMSG_RESURRECT_REQUEST                          = 0x15B,
    CMSG_RESURRECT_RESPONSE                         = 0x15C,
    CMSG_LOOT                                       = 0x15D,
    CMSG_LOOT_MONEY                                 = 0x15E,
    CMSG_LOOT_RELEASE                               = 0x15F,
    SMSG_LOOT_RESPONSE                              = 0x160,
    SMSG_LOOT_RELEASE_RESPONSE                      = 0x161,
    SMSG_LOOT_REMOVED                               = 0x162,
    SMSG_LOOT_MONEY_NOTIFY                          = 0x163,
    SMSG_LOOT_ITEM_NOTIFY                           = 0x164,
    SMSG_LOOT_CLEAR_MONEY                           = 0x165,
    SMSG_ITEM_PUSH_RESULT                           = 0x166,
    SMSG_DUEL_REQUESTED                             = 0x167,
    SMSG_DUEL_OUTOFBOUNDS                           = 0x168,
    SMSG_DUEL_INBOUNDS                              = 0x169,
    SMSG_DUEL_COMPLETE                              = 0x16A,
    SMSG_DUEL_WINNER                                = 0x16B,
    CMSG_DUEL_ACCEPTED                              = 0x16C,
    CMSG_DUEL_CANCELLED                             = 0x16D,
    SMSG_MOUNTRESULT                                = 0x16E,
    SMSG_DISMOUNTRESULT                             = 0x16F,
    SMSG_REMOVED_FROM_PVP_QUEUE                     = 0x170,
    CMSG_MOUNTSPECIAL_ANIM                          = 0x171,
    SMSG_MOUNTSPECIAL_ANIM                          = 0x172,
    SMSG_PET_TAME_FAILURE                           = 0x173,
    CMSG_PET_SET_ACTION                             = 0x174,
    CMSG_PET_ACTION                                 = 0x175,
    CMSG_PET_ABANDON                                = 0x176,
    CMSG_PET_RENAME                                 = 0x177,
    SMSG_PET_NAME_INVALID                           = 0x178,
    SMSG_PET_SPELLS                                 = 0x179,
    SMSG_PET_MODE                                   = 0x17A,
    CMSG_GOSSIP_HELLO                               = 0x17B,
    CMSG_GOSSIP_SELECT_OPTION                       = 0x17C,
    SMSG_GOSSIP_MESSAGE                             = 0x17D,
    SMSG_GOSSIP_COMPLETE                            = 0x17E,
    CMSG_NPC_TEXT_QUERY                             = 0x17F,
    SMSG_NPC_TEXT_UPDATE                            = 0x180,
    SMSG_NPC_WONT_TALK                              = 0x181,
    CMSG_QUESTGIVER_STATUS_QUERY                    = 0x182,
    SMSG_QUESTGIVER_STATUS                          = 0x183,
    CMSG_QUESTGIVER_HELLO                           = 0x184,
    SMSG_QUESTGIVER_QUEST_LIST                      = 0x185,
    CMSG_QUESTGIVER_QUERY_QUEST                     = 0x186,
    CMSG_QUESTGIVER_QUEST_AUTOLAUNCH                = 0x187,
    SMSG_QUESTGIVER_QUEST_DETAILS                   = 0x188,
    CMSG_QUESTGIVER_ACCEPT_QUEST                    = 0x189,
    CMSG_QUESTGIVER_COMPLETE_QUEST                  = 0x18A,
    SMSG_QUESTGIVER_REQUEST_ITEMS                   = 0x18B,
    CMSG_QUESTGIVER_REQUEST_REWARD                  = 0x18C,
    SMSG_QUESTGIVER_OFFER_REWARD                    = 0x18D,
    CMSG_QUESTGIVER_CHOOSE_REWARD                   = 0x18E,
    SMSG_QUESTGIVER_QUEST_INVALID                   = 0x18F,
    CMSG_QUESTGIVER_CANCEL                          = 0x190,
    SMSG_QUESTGIVER_QUEST_COMPLETE                  = 0x191,
    SMSG_QUESTGIVER_QUEST_FAILED                    = 0x192,
    CMSG_QUESTLOG_SWAP_QUEST                        = 0x193,
    CMSG_QUESTLOG_REMOVE_QUEST                      = 0x194,
    SMSG_QUESTLOG_FULL                              = 0x195,
    SMSG_QUESTUPDATE_FAILED                         = 0x196,
    SMSG_QUESTUPDATE_FAILEDTIMER                    = 0x197,
    SMSG_QUESTUPDATE_COMPLETE                       = 0x198,
    SMSG_QUESTUPDATE_ADD_KILL                       = 0x199,
    SMSG_QUESTUPDATE_ADD_ITEM                       = 0x19A,
    CMSG_QUEST_CONFIRM_ACCEPT                       = 0x19B,
    SMSG_QUEST_CONFIRM_ACCEPT                       = 0x19C,
    CMSG_PUSHQUESTTOPARTY                           = 0x19D,
    CMSG_LIST_INVENTORY                             = 0x19E,
    SMSG_LIST_INVENTORY                             = 0x19F,
    CMSG_SELL_ITEM                                  = 0x1A0,
    SMSG_SELL_ITEM                                  = 0x1A1,
    CMSG_BUY_ITEM                                   = 0x1A2,
    CMSG_BUY_ITEM_IN_SLOT                           = 0x1A3,
    SMSG_BUY_ITEM                                   = 0x1A4,
    SMSG_BUY_FAILED                                 = 0x1A5,
    CMSG_TAXICLEARALLNODES                          = 0x1A6,
    CMSG_TAXIENABLEALLNODES                         = 0x1A7,
    CMSG_TAXISHOWNODES                              = 0x1A8,
    SMSG_SHOWTAXINODES                              = 0x1A9,
    CMSG_TAXINODE_STATUS_QUERY                      = 0x1AA,
    SMSG_TAXINODE_STATUS                            = 0x1AB,
    CMSG_TAXIQUERYAVAILABLENODES                    = 0x1AC,
    CMSG_ACTIVATETAXI                               = 0x1AD,
    SMSG_ACTIVATETAXIREPLY                          = 0x1AE,
    SMSG_NEW_TAXI_PATH                              = 0x1AF,
    CMSG_TRAINER_LIST                               = 0x1B0,
    SMSG_TRAINER_LIST                               = 0x1B1,
    CMSG_TRAINER_BUY_SPELL                          = 0x1B2,
    SMSG_TRAINER_BUY_SUCCEEDED                      = 0x1B3,
    SMSG_TRAINER_BUY_FAILED                         = 0x1B4,
    CMSG_BINDER_ACTIVATE                            = 0x1B5,
    SMSG_PLAYERBINDERROR                            = 0x1B6,
    CMSG_BANKER_ACTIVATE                            = 0x1B7,
    SMSG_SHOW_BANK                                  = 0x1B8,
    CMSG_BUY_BANK_SLOT                              = 0x1B9,
    SMSG_BUY_BANK_SLOT_RESULT                       = 0x1BA,
    CMSG_PETITION_SHOWLIST                          = 0x1BB,
    SMSG_PETITION_SHOWLIST                          = 0x1BC,
    CMSG_PETITION_BUY                               = 0x1BD,
    CMSG_PETITION_SHOW_SIGNATURES                   = 0x1BE,
    SMSG_PETITION_SHOW_SIGNATURES                   = 0x1BF,
    CMSG_PETITION_SIGN                              = 0x1C0,
    SMSG_PETITION_SIGN_RESULTS                      = 0x1C1,
    MSG_PETITION_DECLINE                            = 0x1C2,
    CMSG_OFFER_PETITION                             = 0x1C3,
    CMSG_TURN_IN_PETITION                           = 0x1C4,
    SMSG_TURN_IN_PETITION_RESULTS                   = 0x1C5,
    CMSG_PETITION_QUERY                             = 0x1C6,
    SMSG_PETITION_QUERY_RESPONSE                    = 0x1C7,
    SMSG_FISH_NOT_HOOKED                            = 0x1C8,
    SMSG_FISH_ESCAPED                               = 0x1C9,
    CMSG_BUG                                        = 0x1CA,
    SMSG_NOTIFICATION                               = 0x1CB,
    CMSG_PLAYED_TIME                                = 0x1CC,
    SMSG_PLAYED_TIME                                = 0x1CD,
    CMSG_QUERY_TIME                                 = 0x1CE,
    SMSG_QUERY_TIME_RESPONSE                        = 0x1CF,
    SMSG_LOG_XPGAIN                                 = 0x1D0,
    SMSG_AURACASTLOG                                = 0x1D1,
    CMSG_RECLAIM_CORPSE                             = 0x1D2,
    CMSG_WRAP_ITEM                                  = 0x1D3,
    SMSG_LEVELUP_INFO                               = 0x1D4,
    MSG_MINIMAP_PING                                = 0x1D5,
    SMSG_RESISTLOG                                  = 0x1D6,
    SMSG_ENCHANTMENTLOG                             = 0x1D7,
    CMSG_SET_SKILL_CHEAT                            = 0x1D8,
    SMSG_START_MIRROR_TIMER                         = 0x1D9,
    SMSG_PAUSE_MIRROR_TIMER                         = 0x1DA,
    SMSG_STOP_MIRROR_TIMER                          = 0x1DB,
    CMSG_PING                                       = 0x1DC,
    SMSG_PONG                                       = 0x1DD,
    SMSG_CLEAR_COOLDOWN                             = 0x1DE,
    SMSG_GAMEOBJECT_PAGETEXT                        = 0x1DF,
    CMSG_SET_SHEATHED                               = 0x1E0,
    SMSG_COOLDOWN_CHEAT                             = 0x1E1,
    SMSG_SPELL_DELAYED                              = 0x1E2,
    CMSG_QUEST_POI_QUERY                            = 0x1E3,
    SMSG_QUEST_POI_QUERY_RESPONSE                   = 0x1E4,
    CMSG_GHOST                                      = 0x1E5,
    CMSG_GM_INVIS                                   = 0x1E6,
    SMSG_INVALID_PROMOTION_CODE                     = 0x1E7,
    MSG_GM_BIND_OTHER                               = 0x1E8,
    MSG_GM_SUMMON                                   = 0x1E9,
    SMSG_ITEM_TIME_UPDATE                           = 0x1EA,
    SMSG_ITEM_ENCHANT_TIME_UPDATE                   = 0x1EB,
    SMSG_AUTH_CHALLENGE                             = 0x1EC,
    CMSG_AUTH_SESSION                               = 0x1ED,
    SMSG_AUTH_RESPONSE                              = 0x1EE,
    MSG_GM_SHOWLABEL                                = 0x1EF,
    CMSG_PET_CAST_SPELL                             = 0x1F0,
    MSG_SAVE_GUILD_EMBLEM                           = 0x1F1,
    MSG_TABARDVENDOR_ACTIVATE                       = 0x1F2,
    SMSG_PLAY_SPELL_VISUAL                          = 0x1F3,
    CMSG_ZONEUPDATE                                 = 0x1F4,
    SMSG_PARTYKILLLOG                               = 0x1F5,
    SMSG_COMPRESSED_UPDATE_OBJECT                   = 0x1F6,
    SMSG_PLAY_SPELL_IMPACT                          = 0x1F7,
    SMSG_EXPLORATION_EXPERIENCE                     = 0x1F8,
    CMSG_GM_SET_SECURITY_GROUP                      = 0x1F9,
    CMSG_GM_NUKE                                    = 0x1FA,
    MSG_RANDOM_ROLL                                 = 0x1FB,
    SMSG_ENVIRONMENTAL_DAMAGE_LOG                   = 0x1FC,
    CMSG_CHANGEPLAYER_DIFFICULTY                    = 0x1FD,
    SMSG_RWHOIS                                     = 0x1FE,
    SMSG_LFG_PLAYER_REWARD                          = 0x1FF, // uint32, uint8, uint32, uint32, uint32, uint32, uint32, uint8, for (uint8) {uint32, uint32, uint32}
    SMSG_LFG_TELEPORT_DENIED                        = 0x200, // uint32 (1, 2, 4, 6;0, 5, 7)
    CMSG_UNLEARN_SPELL                              = 0x201,
    CMSG_UNLEARN_SKILL                              = 0x202,
    SMSG_REMOVED_SPELL                              = 0x203,
    CMSG_DECHARGE                                   = 0x204,
    CMSG_GMTICKET_CREATE                            = 0x205,
    SMSG_GMTICKET_CREATE                            = 0x206,
    CMSG_GMTICKET_UPDATETEXT                        = 0x207,
    SMSG_GMTICKET_UPDATETEXT                        = 0x208,
    SMSG_ACCOUNT_DATA_TIMES                         = 0x209,
    CMSG_REQUEST_ACCOUNT_DATA                       = 0x20A,
    CMSG_UPDATE_ACCOUNT_DATA                        = 0x20B,
    SMSG_UPDATE_ACCOUNT_DATA                        = 0x20C,
    SMSG_CLEAR_FAR_SIGHT_IMMEDIATE                  = 0x20D,
    SMSG_CHANGEPLAYER_DIFFICULTY_RESULT             = 0x20E,
    CMSG_GM_TEACH                                   = 0x20F,
    CMSG_GM_CREATE_ITEM_TARGET                      = 0x210,
    CMSG_GMTICKET_GETTICKET                         = 0x211,
    SMSG_GMTICKET_GETTICKET                         = 0x212,
    CMSG_UNLEARN_TALENTS                            = 0x213,
    SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT             = 0x214,
    SMSG_GAMEOBJECT_DESPAWN_ANIM                    = 0x215,
    MSG_CORPSE_QUERY                                = 0x216,
    CMSG_GMTICKET_DELETETICKET                      = 0x217,
    SMSG_GMTICKET_DELETETICKET                      = 0x218,
    SMSG_CHAT_WRONG_FACTION                         = 0x219,
    CMSG_GMTICKET_SYSTEMSTATUS                      = 0x21A,
    SMSG_GMTICKET_SYSTEMSTATUS                      = 0x21B,
    CMSG_SPIRIT_HEALER_ACTIVATE                     = 0x21C,
    CMSG_SET_STAT_CHEAT                             = 0x21D,
    SMSG_QUEST_FORCE_REMOVE                         = 0x21E, // uint32 questid
    CMSG_SKILL_BUY_STEP                             = 0x21F,
    CMSG_SKILL_BUY_RANK                             = 0x220,
    CMSG_XP_CHEAT                                   = 0x221,
    SMSG_SPIRIT_HEALER_CONFIRM                      = 0x222,
    CMSG_CHARACTER_POINT_CHEAT                      = 0x223,
    SMSG_GOSSIP_POI                                 = 0x224,
    CMSG_CHAT_IGNORED                               = 0x225,
    CMSG_GM_VISION                                  = 0x226,
    CMSG_SERVER_COMMAND                             = 0x227,
    CMSG_GM_SILENCE                                 = 0x228,
    CMSG_GM_REVEALTO                                = 0x229,
    CMSG_GM_RESURRECT                               = 0x22A,
    CMSG_GM_SUMMONMOB                               = 0x22B,
    CMSG_GM_MOVECORPSE                              = 0x22C,
    CMSG_GM_FREEZE                                  = 0x22D,
    CMSG_GM_UBERINVIS                               = 0x22E,
    CMSG_GM_REQUEST_PLAYER_INFO                     = 0x22F,
    SMSG_GM_PLAYER_INFO                             = 0x230,
    CMSG_GUILD_RANK                                 = 0x231,
    CMSG_GUILD_ADD_RANK                             = 0x232,
    CMSG_GUILD_DEL_RANK                             = 0x233,
    CMSG_GUILD_SET_PUBLIC_NOTE                      = 0x234,
    CMSG_GUILD_SET_OFFICER_NOTE                     = 0x235,
    SMSG_LOGIN_VERIFY_WORLD                         = 0x236,
    CMSG_CLEAR_EXPLORATION                          = 0x237,
    CMSG_SEND_MAIL                                  = 0x238,
    SMSG_SEND_MAIL_RESULT                           = 0x239,
    CMSG_GET_MAIL_LIST                              = 0x23A,
    SMSG_MAIL_LIST_RESULT                           = 0x23B,
    CMSG_BATTLEFIELD_LIST                           = 0x23C,
    SMSG_BATTLEFIELD_LIST                           = 0x23D,
    CMSG_BATTLEFIELD_JOIN                           = 0x23E,
    SMSG_FORCE_SET_VEHICLE_REC_ID                   = 0x23F,
    CMSG_SET_VEHICLE_REC_ID_ACK                     = 0x240,
    CMSG_TAXICLEARNODE                              = 0x241,
    CMSG_TAXIENABLENODE                             = 0x242,
    CMSG_ITEM_TEXT_QUERY                            = 0x243,
    SMSG_ITEM_TEXT_QUERY_RESPONSE                   = 0x244,
    CMSG_MAIL_TAKE_MONEY                            = 0x245,
    CMSG_MAIL_TAKE_ITEM                             = 0x246,
    CMSG_MAIL_MARK_AS_READ                          = 0x247,
    CMSG_MAIL_RETURN_TO_SENDER                      = 0x248,
    CMSG_MAIL_DELETE                                = 0x249,
    CMSG_MAIL_CREATE_TEXT_ITEM                      = 0x24A,
    SMSG_SPELLLOGMISS                               = 0x24B,
    SMSG_SPELLLOGEXECUTE                            = 0x24C,
    SMSG_DEBUGAURAPROC                              = 0x24D,
    SMSG_PERIODICAURALOG                            = 0x24E,
    SMSG_SPELLDAMAGESHIELD                          = 0x24F,
    SMSG_SPELLNONMELEEDAMAGELOG                     = 0x250,
    CMSG_LEARN_TALENT                               = 0x251,
    SMSG_RESURRECT_FAILED                           = 0x252,
    CMSG_TOGGLE_PVP                                 = 0x253,
    SMSG_ZONE_UNDER_ATTACK                          = 0x254,
    MSG_AUCTION_HELLO                               = 0x255,
    CMSG_AUCTION_SELL_ITEM                          = 0x256,
    CMSG_AUCTION_REMOVE_ITEM                        = 0x257,
    CMSG_AUCTION_LIST_ITEMS                         = 0x258,
    CMSG_AUCTION_LIST_OWNER_ITEMS                   = 0x259,
    CMSG_AUCTION_PLACE_BID                          = 0x25A,
    SMSG_AUCTION_COMMAND_RESULT                     = 0x25B,
    SMSG_AUCTION_LIST_RESULT                        = 0x25C,
    SMSG_AUCTION_OWNER_LIST_RESULT                  = 0x25D,
    SMSG_AUCTION_BIDDER_NOTIFICATION                = 0x25E,
    SMSG_AUCTION_OWNER_NOTIFICATION                 = 0x25F,
    SMSG_PROCRESIST                                 = 0x260,
    SMSG_COMBAT_EVENT_FAILED                        = 0x261,
    SMSG_DISPEL_FAILED                              = 0x262,
    SMSG_SPELLORDAMAGE_IMMUNE                       = 0x263,
    CMSG_AUCTION_LIST_BIDDER_ITEMS                  = 0x264,
    SMSG_AUCTION_BIDDER_LIST_RESULT                 = 0x265,
    SMSG_SET_FLAT_SPELL_MODIFIER                    = 0x266,
    SMSG_SET_PCT_SPELL_MODIFIER                     = 0x267,
    CMSG_SET_AMMO                                   = 0x268,
    SMSG_CORPSE_RECLAIM_DELAY                       = 0x269,
    CMSG_SET_ACTIVE_MOVER                           = 0x26A,
    CMSG_PET_CANCEL_AURA                            = 0x26B,
    CMSG_PLAYER_AI_CHEAT                            = 0x26C,
    CMSG_CANCEL_AUTO_REPEAT_SPELL                   = 0x26D,
    MSG_GM_ACCOUNT_ONLINE                           = 0x26E,
    MSG_LIST_STABLED_PETS                           = 0x26F,
    CMSG_STABLE_PET                                 = 0x270,
    CMSG_UNSTABLE_PET                               = 0x271,
    CMSG_BUY_STABLE_SLOT                            = 0x272,
    SMSG_STABLE_RESULT                              = 0x273,
    CMSG_STABLE_REVIVE_PET                          = 0x274,
    CMSG_STABLE_SWAP_PET                            = 0x275,
    MSG_QUEST_PUSH_RESULT                           = 0x276,
    SMSG_PLAY_MUSIC                                 = 0x277,
    SMSG_PLAY_OBJECT_SOUND                          = 0x278,
    CMSG_REQUEST_PET_INFO                           = 0x279,
    CMSG_FAR_SIGHT                                  = 0x27A,
    SMSG_SPELLDISPELLOG                             = 0x27B,
    SMSG_DAMAGE_CALC_LOG                            = 0x27C,
    CMSG_ENABLE_DAMAGE_LOG                          = 0x27D,
    CMSG_GROUP_CHANGE_SUB_GROUP                     = 0x27E,
    CMSG_REQUEST_PARTY_MEMBER_STATS                 = 0x27F,
    CMSG_GROUP_SWAP_SUB_GROUP                       = 0x280,
    CMSG_RESET_FACTION_CHEAT                        = 0x281,
    CMSG_AUTOSTORE_BANK_ITEM                        = 0x282,
    CMSG_AUTOBANK_ITEM                              = 0x283,
    MSG_QUERY_NEXT_MAIL_TIME                        = 0x284,
    SMSG_RECEIVED_MAIL                              = 0x285,
    SMSG_RAID_GROUP_ONLY                            = 0x286,
    CMSG_SET_DURABILITY_CHEAT                       = 0x287,
    CMSG_SET_PVP_RANK_CHEAT                         = 0x288,
    CMSG_ADD_PVP_MEDAL_CHEAT                        = 0x289,
    CMSG_DEL_PVP_MEDAL_CHEAT                        = 0x28A,
    CMSG_SET_PVP_TITLE                              = 0x28B,
    SMSG_PVP_CREDIT                                 = 0x28C,
    SMSG_AUCTION_REMOVED_NOTIFICATION               = 0x28D,
    CMSG_GROUP_RAID_CONVERT                         = 0x28E,
    CMSG_GROUP_ASSISTANT_LEADER                     = 0x28F,
    CMSG_BUYBACK_ITEM                               = 0x290,
    SMSG_CHAT_SERVER_MESSAGE                        = 0x291,
    CMSG_SET_SAVED_INSTANCE_EXTEND                  = 0x292,
    SMSG_LFG_OFFER_CONTINUE                         = 0x293,
    CMSG_TEST_DROP_RATE                             = 0x294,
    SMSG_TEST_DROP_RATE_RESULT                      = 0x295,
    CMSG_LFG_GET_STATUS                             = 0x296,
    SMSG_SHOW_MAILBOX                               = 0x297,
    SMSG_RESET_RANGED_COMBAT_TIMER                  = 0x298,
    SMSG_CHAT_NOT_IN_PARTY                          = 0x299, // uint32, errors: ERR_NOT_IN_GROUP (2, 51) and ERR_NOT_IN_RAID (3, 39, 40)
    CMSG_GMTICKETSYSTEM_TOGGLE                      = 0x29A,
    CMSG_CANCEL_GROWTH_AURA                         = 0x29B,
    SMSG_CANCEL_AUTO_REPEAT                         = 0x29C,
    SMSG_STANDSTATE_UPDATE                          = 0x29D,
    SMSG_LOOT_ALL_PASSED                            = 0x29E,
    SMSG_LOOT_ROLL_WON                              = 0x29F,
    CMSG_LOOT_ROLL                                  = 0x2A0,
    SMSG_LOOT_START_ROLL                            = 0x2A1,
    SMSG_LOOT_ROLL                                  = 0x2A2,
    CMSG_LOOT_MASTER_GIVE                           = 0x2A3,
    SMSG_LOOT_MASTER_LIST                           = 0x2A4,
    SMSG_SET_FORCED_REACTIONS                       = 0x2A5,
    SMSG_SPELL_FAILED_OTHER                         = 0x2A6,
    SMSG_GAMEOBJECT_RESET_STATE                     = 0x2A7,
    CMSG_REPAIR_ITEM                                = 0x2A8,
    SMSG_CHAT_PLAYER_NOT_FOUND                      = 0x2A9,
    MSG_TALENT_WIPE_CONFIRM                         = 0x2AA,
    SMSG_SUMMON_REQUEST                             = 0x2AB,
    CMSG_SUMMON_RESPONSE                            = 0x2AC,
    MSG_DEV_SHOWLABEL                               = 0x2AD,
    SMSG_MONSTER_MOVE_TRANSPORT                     = 0x2AE,
    SMSG_PET_BROKEN                                 = 0x2AF,
    MSG_MOVE_FEATHER_FALL                           = 0x2B0,
    MSG_MOVE_WATER_WALK                             = 0x2B1,
    CMSG_SERVER_BROADCAST                           = 0x2B2,
    CMSG_SELF_RES                                   = 0x2B3,
    SMSG_FEIGN_DEATH_RESISTED                       = 0x2B4,
    CMSG_RUN_SCRIPT                                 = 0x2B5,
    SMSG_SCRIPT_MESSAGE                             = 0x2B6,
    SMSG_DUEL_COUNTDOWN                             = 0x2B7,
    SMSG_AREA_TRIGGER_MESSAGE                       = 0x2B8,
    CMSG_SHOWING_HELM                               = 0x2B9,
    CMSG_SHOWING_CLOAK                              = 0x2BA,
    SMSG_LFG_ROLE_CHOSEN                            = 0x2BB,
    SMSG_PLAYER_SKINNED                             = 0x2BC,
    SMSG_DURABILITY_DAMAGE_DEATH                    = 0x2BD,
    CMSG_SET_EXPLORATION                            = 0x2BE,
    CMSG_SET_ACTIONBAR_TOGGLES                      = 0x2BF,
    UMSG_DELETE_GUILD_CHARTER                       = 0x2C0,
    MSG_PETITION_RENAME                             = 0x2C1,
    SMSG_INIT_WORLD_STATES                          = 0x2C2,
    SMSG_UPDATE_WORLD_STATE                         = 0x2C3,
    CMSG_ITEM_NAME_QUERY                            = 0x2C4,
    SMSG_ITEM_NAME_QUERY_RESPONSE                   = 0x2C5,
    SMSG_PET_ACTION_FEEDBACK                        = 0x2C6,
    CMSG_CHAR_RENAME                                = 0x2C7,
    SMSG_CHAR_RENAME                                = 0x2C8,
    CMSG_MOVE_SPLINE_DONE                           = 0x2C9,
    CMSG_MOVE_FALL_RESET                            = 0x2CA,
    SMSG_INSTANCE_SAVE_CREATED                      = 0x2CB,
    SMSG_RAID_INSTANCE_INFO                         = 0x2CC,
    CMSG_REQUEST_RAID_INFO                          = 0x2CD,
    CMSG_MOVE_TIME_SKIPPED                          = 0x2CE,
    CMSG_MOVE_FEATHER_FALL_ACK                      = 0x2CF,
    CMSG_MOVE_WATER_WALK_ACK                        = 0x2D0,
    CMSG_MOVE_NOT_ACTIVE_MOVER                      = 0x2D1,
    SMSG_PLAY_SOUND                                 = 0x2D2,
    CMSG_BATTLEFIELD_STATUS                         = 0x2D3,
    SMSG_BATTLEFIELD_STATUS                         = 0x2D4,
    CMSG_BATTLEFIELD_PORT                           = 0x2D5,
    MSG_INSPECT_HONOR_STATS                         = 0x2D6,
    CMSG_BATTLEMASTER_HELLO                         = 0x2D7,
    CMSG_MOVE_START_SWIM_CHEAT                      = 0x2D8,
    CMSG_MOVE_STOP_SWIM_CHEAT                       = 0x2D9,
    SMSG_FORCE_WALK_SPEED_CHANGE                    = 0x2DA,
    CMSG_FORCE_WALK_SPEED_CHANGE_ACK                = 0x2DB,
    SMSG_FORCE_SWIM_BACK_SPEED_CHANGE               = 0x2DC,
    CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK           = 0x2DD,
    SMSG_FORCE_TURN_RATE_CHANGE                     = 0x2DE,
    CMSG_FORCE_TURN_RATE_CHANGE_ACK                 = 0x2DF,
    MSG_PVP_LOG_DATA                                = 0x2E0,
    CMSG_LEAVE_BATTLEFIELD                          = 0x2E1,
    CMSG_AREA_SPIRIT_HEALER_QUERY                   = 0x2E2,
    CMSG_AREA_SPIRIT_HEALER_QUEUE                   = 0x2E3,
    SMSG_AREA_SPIRIT_HEALER_TIME                    = 0x2E4,
    CMSG_GM_UNTEACH                                 = 0x2E5,
    SMSG_WARDEN_DATA                                = 0x2E6,
    CMSG_WARDEN_DATA                                = 0x2E7,
    SMSG_GROUP_JOINED_BATTLEGROUND                  = 0x2E8,
    MSG_BATTLEGROUND_PLAYER_POSITIONS               = 0x2E9,
    CMSG_PET_STOP_ATTACK                            = 0x2EA,
    SMSG_BINDER_CONFIRM                             = 0x2EB,
    SMSG_BATTLEGROUND_PLAYER_JOINED                 = 0x2EC,
    SMSG_BATTLEGROUND_PLAYER_LEFT                   = 0x2ED,
    CMSG_BATTLEMASTER_JOIN                          = 0x2EE,
    SMSG_ADDON_INFO                                 = 0x2EF,
    CMSG_PET_UNLEARN                                = 0x2F0,    // Deprecated 3.x
    SMSG_PET_UNLEARN_CONFIRM                        = 0x2F1,    // Deprecated 3.x
    SMSG_PARTY_MEMBER_STATS_FULL                    = 0x2F2,
    CMSG_PET_SPELL_AUTOCAST                         = 0x2F3,
    SMSG_WEATHER                                    = 0x2F4,
    SMSG_PLAY_TIME_WARNING                          = 0x2F5,
    SMSG_MINIGAME_SETUP                             = 0x2F6,
    SMSG_MINIGAME_STATE                             = 0x2F7,
    CMSG_MINIGAME_MOVE                              = 0x2F8,
    SMSG_MINIGAME_MOVE_FAILED                       = 0x2F9,
    SMSG_RAID_INSTANCE_MESSAGE                      = 0x2FA,
    SMSG_COMPRESSED_MOVES                           = 0x2FB,
    CMSG_GUILD_INFO_TEXT                            = 0x2FC,
    SMSG_CHAT_RESTRICTED                            = 0x2FD,
    SMSG_SPLINE_SET_RUN_SPEED                       = 0x2FE,
    SMSG_SPLINE_SET_RUN_BACK_SPEED                  = 0x2FF,
    SMSG_SPLINE_SET_SWIM_SPEED                      = 0x300,
    SMSG_SPLINE_SET_WALK_SPEED                      = 0x301,
    SMSG_SPLINE_SET_SWIM_BACK_SPEED                 = 0x302,
    SMSG_SPLINE_SET_TURN_RATE                       = 0x303,
    SMSG_SPLINE_MOVE_UNROOT                         = 0x304,
    SMSG_SPLINE_MOVE_FEATHER_FALL                   = 0x305,
    SMSG_SPLINE_MOVE_NORMAL_FALL                    = 0x306,
    SMSG_SPLINE_MOVE_SET_HOVER                      = 0x307,
    SMSG_SPLINE_MOVE_UNSET_HOVER                    = 0x308,
    SMSG_SPLINE_MOVE_WATER_WALK                     = 0x309,
    SMSG_SPLINE_MOVE_LAND_WALK                      = 0x30A,
    SMSG_SPLINE_MOVE_START_SWIM                     = 0x30B,
    SMSG_SPLINE_MOVE_STOP_SWIM                      = 0x30C,
    SMSG_SPLINE_MOVE_SET_RUN_MODE                   = 0x30D,
    SMSG_SPLINE_MOVE_SET_WALK_MODE                  = 0x30E,
    CMSG_GM_NUKE_ACCOUNT                            = 0x30F,
    MSG_GM_DESTROY_CORPSE                           = 0x310,
    CMSG_GM_DESTROY_ONLINE_CORPSE                   = 0x311,
    CMSG_ACTIVATETAXIEXPRESS                        = 0x312,
    SMSG_SET_FACTION_ATWAR                          = 0x313,
    SMSG_GAMETIMEBIAS_SET                           = 0x314,
    CMSG_DEBUG_ACTIONS_START                        = 0x315,
    CMSG_DEBUG_ACTIONS_STOP                         = 0x316,
    CMSG_SET_FACTION_INACTIVE                       = 0x317,
    CMSG_SET_WATCHED_FACTION                        = 0x318,
    MSG_MOVE_TIME_SKIPPED                           = 0x319,
    SMSG_SPLINE_MOVE_ROOT                           = 0x31A,
    CMSG_SET_EXPLORATION_ALL                        = 0x31B,
    SMSG_INVALIDATE_PLAYER                          = 0x31C,
    CMSG_RESET_INSTANCES                            = 0x31D,
    SMSG_INSTANCE_RESET                             = 0x31E,
    SMSG_INSTANCE_RESET_FAILED                      = 0x31F,
    SMSG_UPDATE_LAST_INSTANCE                       = 0x320,
    MSG_RAID_TARGET_UPDATE                          = 0x321,
    MSG_RAID_READY_CHECK                            = 0x322,
    CMSG_LUA_USAGE                                  = 0x323,
    SMSG_PET_ACTION_SOUND                           = 0x324,
    SMSG_PET_DISMISS_SOUND                          = 0x325,
    SMSG_GHOSTEE_GONE                               = 0x326,
    CMSG_GM_UPDATE_TICKET_STATUS                    = 0x327,
    SMSG_GM_TICKET_STATUS_UPDATE                    = 0x328,
    MSG_SET_DUNGEON_DIFFICULTY                      = 0x329,
    CMSG_GMSURVEY_SUBMIT                            = 0x32A,
    SMSG_UPDATE_INSTANCE_OWNERSHIP                  = 0x32B,
    CMSG_IGNORE_KNOCKBACK_CHEAT                     = 0x32C,
    SMSG_CHAT_PLAYER_AMBIGUOUS                      = 0x32D,
    MSG_DELAY_GHOST_TELEPORT                        = 0x32E,
    SMSG_SPELLINSTAKILLLOG                          = 0x32F,
    SMSG_SPELL_UPDATE_CHAIN_TARGETS                 = 0x330,
    CMSG_CHAT_FILTERED                              = 0x331,
    SMSG_EXPECTED_SPAM_RECORDS                      = 0x332,
    SMSG_SPELLSTEALLOG                              = 0x333,
    CMSG_LOTTERY_QUERY_OBSOLETE                     = 0x334,
    SMSG_LOTTERY_QUERY_RESULT_OBSOLETE              = 0x335,
    CMSG_BUY_LOTTERY_TICKET_OBSOLETE                = 0x336,
    SMSG_LOTTERY_RESULT_OBSOLETE                    = 0x337,
    SMSG_CHARACTER_PROFILE                          = 0x338,
    SMSG_CHARACTER_PROFILE_REALM_CONNECTED          = 0x339,
    SMSG_DEFENSE_MESSAGE                            = 0x33A,
    SMSG_INSTANCE_DIFFICULTY                        = 0x33B,
    MSG_GM_RESETINSTANCELIMIT                       = 0x33C,
    SMSG_MOTD                                       = 0x33D,
    SMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY = 0x33E,
    SMSG_MOVE_UNSET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY = 0x33F,
    CMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY_ACK = 0x340,
    MSG_MOVE_START_SWIM_CHEAT                       = 0x341,
    MSG_MOVE_STOP_SWIM_CHEAT                        = 0x342,
    SMSG_MOVE_SET_CAN_FLY                           = 0x343,
    SMSG_MOVE_UNSET_CAN_FLY                         = 0x344,
    CMSG_MOVE_SET_CAN_FLY_ACK                       = 0x345,
    CMSG_MOVE_SET_FLY                               = 0x346,
    CMSG_SOCKET_GEMS                                = 0x347,
    CMSG_ARENA_TEAM_CREATE                          = 0x348,
    SMSG_ARENA_TEAM_COMMAND_RESULT                  = 0x349,
    MSG_MOVE_UPDATE_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY = 0x34A,
    CMSG_ARENA_TEAM_QUERY                           = 0x34B,
    SMSG_ARENA_TEAM_QUERY_RESPONSE                  = 0x34C,
    CMSG_ARENA_TEAM_ROSTER                          = 0x34D,
    SMSG_ARENA_TEAM_ROSTER                          = 0x34E,
    CMSG_ARENA_TEAM_INVITE                          = 0x34F,
    SMSG_ARENA_TEAM_INVITE                          = 0x350,
    CMSG_ARENA_TEAM_ACCEPT                          = 0x351,
    CMSG_ARENA_TEAM_DECLINE                         = 0x352,
    CMSG_ARENA_TEAM_LEAVE                           = 0x353,
    CMSG_ARENA_TEAM_REMOVE                          = 0x354,
    CMSG_ARENA_TEAM_DISBAND                         = 0x355,
    CMSG_ARENA_TEAM_LEADER                          = 0x356,
    SMSG_ARENA_TEAM_EVENT                           = 0x357,
    CMSG_BATTLEMASTER_JOIN_ARENA                    = 0x358,
    MSG_MOVE_START_ASCEND                           = 0x359,
    MSG_MOVE_STOP_ASCEND                            = 0x35A,
    SMSG_ARENA_TEAM_STATS                           = 0x35B,
    CMSG_LFG_JOIN                                   = 0x35C,
    CMSG_LFG_LEAVE                                  = 0x35D,
    CMSG_SEARCH_LFG_JOIN                            = 0x35E,
    CMSG_SEARCH_LFG_LEAVE                           = 0x35F,
    SMSG_UPDATE_LFG_LIST                            = 0x360,    // uint32, uint32, if (uint8) { uint32 count, for (count) { uint64} }, uint32 count2, uint32, for (count2) { uint64, uint32 flags, if (flags & 0x2) {string}, if (flags & 0x10) {for (3) uint8}, if (flags & 0x80) {uint64, uint32}}, uint32 count3, uint32, for (count3) {uint64, uint32 flags, if (flags & 0x1) {uint8, uint8, uint8, for (3) uint8, uint32, uint32, uint32, uint32, uint32, uint32, float, float, uint32, uint32, uint32, uint32, uint32, float, uint32, uint32, uint32, uint32, uint32, uint32}, if (flags&0x2) string, if (flags&0x4) uint8, if (flags&0x8) uint64, if (flags&0x10) uint8, if (flags&0x20) uint32, if (flags&0x40) uint8, if (flags& 0x80) {uint64, uint32}}
    SMSG_LFG_PROPOSAL_UPDATE                        = 0x361,    // uint32, uint8, uint32, uint32, uint8, for (uint8) {uint32, uint8, uint8, uint8, uint8}
    CMSG_LFG_PROPOSAL_RESULT                        = 0x362,
    SMSG_LFG_ROLE_CHECK_UPDATE                      = 0x363,    // uint32, uint8, for (uint8) uint32, uint8, for (uint8) { uint64, uint8, uint32, uint8, }
    SMSG_LFG_JOIN_RESULT                            = 0x364,    // uint32 unk, uint32, if (unk == 6) { uint8 count, for (count) uint64 }
    SMSG_LFG_QUEUE_STATUS                           = 0x365,    // uint32 dungeon, uint32 lfgtype, uint32, uint32, uint32, uint32, uint8, uint8, uint8, uint8
    CMSG_SET_LFG_COMMENT                            = 0x366,
    SMSG_LFG_UPDATE_PLAYER                          = 0x367,    // uint8, if (uint8) { uint8, uint8, uint8, uint8, if (uint8) for (uint8) uint32, string}
    SMSG_LFG_UPDATE_PARTY                           = 0x368,    // uint8, if (uint8) { uint8, uint8, uint8, for (3) uint8, uint8, if (uint8) for (uint8) uint32, string}
    SMSG_LFG_UPDATE_SEARCH                          = 0x369,    // uint8
    CMSG_LFG_SET_ROLES                              = 0x36A,
    CMSG_LFG_SET_NEEDS                              = 0x36B,
    CMSG_LFG_SET_BOOT_VOTE                          = 0x36C,
    SMSG_LFG_BOOT_PROPOSAL_UPDATE                   = 0x36D,    // uint8, uint8, uint8, uint64, uint32, uint32, uint32, uint32
    CMSG_LFD_PLAYER_LOCK_INFO_REQUEST               = 0x36E,
    SMSG_LFG_PLAYER_INFO                            = 0x36F,    // uint8, for (uint8) { uint32, uint8, uint32, uint32, uint32, uint32, uint8, for (uint8) {uint32, uint32, uint32}}, uint32, for (uint32) {uint32, uint32}
    CMSG_LFG_TELEPORT                               = 0x370,
    CMSG_LFD_PARTY_LOCK_INFO_REQUEST                = 0x371,
    SMSG_LFG_PARTY_INFO                             = 0x372,    // uint8, for (uint8) uint64
    SMSG_TITLE_EARNED                               = 0x373,
    CMSG_SET_TITLE                                  = 0x374,
    CMSG_CANCEL_MOUNT_AURA                          = 0x375,
    SMSG_ARENA_ERROR                                = 0x376,
    MSG_INSPECT_ARENA_TEAMS                         = 0x377,
    SMSG_DEATH_RELEASE_LOC                          = 0x378,
    CMSG_CANCEL_TEMP_ENCHANTMENT                    = 0x379,
    SMSG_FORCED_DEATH_UPDATE                        = 0x37A,
    CMSG_CHEAT_SET_HONOR_CURRENCY                   = 0x37B,
    CMSG_CHEAT_SET_ARENA_CURRENCY                   = 0x37C,
    MSG_MOVE_SET_FLIGHT_SPEED_CHEAT                 = 0x37D,
    MSG_MOVE_SET_FLIGHT_SPEED                       = 0x37E,
    MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT            = 0x37F,
    MSG_MOVE_SET_FLIGHT_BACK_SPEED                  = 0x380,
    SMSG_FORCE_FLIGHT_SPEED_CHANGE                  = 0x381,
    CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK              = 0x382,
    SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE             = 0x383,
    CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK         = 0x384,
    SMSG_SPLINE_SET_FLIGHT_SPEED                    = 0x385,
    SMSG_SPLINE_SET_FLIGHT_BACK_SPEED               = 0x386,
    CMSG_MAELSTROM_INVALIDATE_CACHE                 = 0x387,
    SMSG_FLIGHT_SPLINE_SYNC                         = 0x388,
    CMSG_SET_TAXI_BENCHMARK_MODE                    = 0x389,
    SMSG_JOINED_BATTLEGROUND_QUEUE                  = 0x38A,
    SMSG_REALM_SPLIT                                = 0x38B,
    CMSG_REALM_SPLIT                                = 0x38C,
    CMSG_MOVE_CHNG_TRANSPORT                        = 0x38D,
    MSG_PARTY_ASSIGNMENT                            = 0x38E,
    SMSG_OFFER_PETITION_ERROR                       = 0x38F,
    SMSG_TIME_SYNC_REQ                              = 0x390,
    CMSG_TIME_SYNC_RESP                             = 0x391,
    CMSG_SEND_LOCAL_EVENT                           = 0x392,
    CMSG_SEND_GENERAL_TRIGGER                       = 0x393,
    CMSG_SEND_COMBAT_TRIGGER                        = 0x394,
    CMSG_MAELSTROM_GM_SENT_MAIL                     = 0x395,
    SMSG_RESET_FAILED_NOTIFY                        = 0x396,
    SMSG_REAL_GROUP_UPDATE                          = 0x397,
    SMSG_LFG_DISABLED                               = 0x398,
    CMSG_ACTIVE_PVP_CHEAT                           = 0x399,
    CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY                = 0x39A,
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE       = 0x39B,
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE = 0x39C,
    SMSG_UPDATE_COMBO_POINTS                        = 0x39D,
    SMSG_VOICE_SESSION_ROSTER_UPDATE                = 0x39E,
    SMSG_VOICE_SESSION_LEAVE                        = 0x39F,
    SMSG_VOICE_SESSION_ADJUST_PRIORITY              = 0x3A0,
    CMSG_VOICE_SET_TALKER_MUTED_REQUEST             = 0x3A1,
    SMSG_VOICE_SET_TALKER_MUTED                     = 0x3A2,
    SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE              = 0x3A3,
    SMSG_SET_EXTRA_AURA_INFO_OBSOLETE               = 0x3A4,
    SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE   = 0x3A5,
    SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE             = 0x3A6,
    MSG_MOVE_START_DESCEND                          = 0x3A7,
    CMSG_IGNORE_REQUIREMENTS_CHEAT                  = 0x3A8,
    SMSG_IGNORE_REQUIREMENTS_CHEAT                  = 0x3A9,
    SMSG_SPELL_CHANCE_PROC_LOG                      = 0x3AA,
    CMSG_MOVE_SET_RUN_SPEED                         = 0x3AB,
    SMSG_DISMOUNT                                   = 0x3AC,
    MSG_MOVE_UPDATE_CAN_FLY                         = 0x3AD,
    MSG_RAID_READY_CHECK_CONFIRM                    = 0x3AE,
    CMSG_VOICE_SESSION_ENABLE                       = 0x3AF,
    SMSG_VOICE_SESSION_ENABLE                       = 0x3B0,
    SMSG_VOICE_PARENTAL_CONTROLS                    = 0x3B1,
    CMSG_GM_WHISPER                                 = 0x3B2,
    SMSG_GM_MESSAGECHAT                             = 0x3B3,
    MSG_GM_GEARRATING                               = 0x3B4,
    CMSG_COMMENTATOR_ENABLE                         = 0x3B5,
    SMSG_COMMENTATOR_STATE_CHANGED                  = 0x3B6,
    CMSG_COMMENTATOR_GET_MAP_INFO                   = 0x3B7,
    SMSG_COMMENTATOR_MAP_INFO                       = 0x3B8,
    CMSG_COMMENTATOR_GET_PLAYER_INFO                = 0x3B9,
    SMSG_COMMENTATOR_GET_PLAYER_INFO                = 0x3BA,
    SMSG_COMMENTATOR_PLAYER_INFO                    = 0x3BB,
    CMSG_COMMENTATOR_ENTER_INSTANCE                 = 0x3BC,
    CMSG_COMMENTATOR_EXIT_INSTANCE                  = 0x3BD,
    CMSG_COMMENTATOR_INSTANCE_COMMAND               = 0x3BE,
    SMSG_CLEAR_TARGET                               = 0x3BF,
    CMSG_BOT_DETECTED                               = 0x3C0,
    SMSG_CROSSED_INEBRIATION_THRESHOLD              = 0x3C1,
    CMSG_CHEAT_PLAYER_LOGIN                         = 0x3C2,
    CMSG_CHEAT_PLAYER_LOOKUP                        = 0x3C3,
    SMSG_CHEAT_PLAYER_LOOKUP                        = 0x3C4,
    SMSG_KICK_REASON                                = 0x3C5,
    MSG_RAID_READY_CHECK_FINISHED                   = 0x3C6,
    CMSG_COMPLAIN                                   = 0x3C7,
    SMSG_COMPLAIN_RESULT                            = 0x3C8,
    SMSG_FEATURE_SYSTEM_STATUS                      = 0x3C9,
    CMSG_GM_SHOW_COMPLAINTS                         = 0x3CA,
    CMSG_GM_UNSQUELCH                               = 0x3CB,
    CMSG_CHANNEL_SILENCE_VOICE                      = 0x3CC,
    CMSG_CHANNEL_SILENCE_ALL                        = 0x3CD,
    CMSG_CHANNEL_UNSILENCE_VOICE                    = 0x3CE,
    CMSG_CHANNEL_UNSILENCE_ALL                      = 0x3CF,
    CMSG_TARGET_CAST                                = 0x3D0,
    CMSG_TARGET_SCRIPT_CAST                         = 0x3D1,
    CMSG_CHANNEL_DISPLAY_LIST                       = 0x3D2,
    CMSG_SET_ACTIVE_VOICE_CHANNEL                   = 0x3D3,
    CMSG_GET_CHANNEL_MEMBER_COUNT                   = 0x3D4,
    SMSG_CHANNEL_MEMBER_COUNT                       = 0x3D5,
    CMSG_CHANNEL_VOICE_ON                           = 0x3D6,
    CMSG_CHANNEL_VOICE_OFF                          = 0x3D7,
    CMSG_DEBUG_LIST_TARGETS                         = 0x3D8,
    SMSG_DEBUG_LIST_TARGETS                         = 0x3D9,
    SMSG_AVAILABLE_VOICE_CHANNEL                    = 0x3DA,
    CMSG_ADD_VOICE_IGNORE                           = 0x3DB,
    CMSG_DEL_VOICE_IGNORE                           = 0x3DC,
    CMSG_PARTY_SILENCE                              = 0x3DD,
    CMSG_PARTY_UNSILENCE                            = 0x3DE,
    MSG_NOTIFY_PARTY_SQUELCH                        = 0x3DF,
    SMSG_COMSAT_RECONNECT_TRY                       = 0x3E0,
    SMSG_COMSAT_DISCONNECT                          = 0x3E1,
    SMSG_COMSAT_CONNECT_FAIL                        = 0x3E2,
    SMSG_VOICE_CHAT_STATUS                          = 0x3E3,
    CMSG_REPORT_PVP_AFK                             = 0x3E4,
    SMSG_REPORT_PVP_AFK_RESULT                      = 0x3E5,
    CMSG_GUILD_BANKER_ACTIVATE                      = 0x3E6,
    CMSG_GUILD_BANK_QUERY_TAB                       = 0x3E7,
    SMSG_GUILD_BANK_LIST                            = 0x3E8,
    CMSG_GUILD_BANK_SWAP_ITEMS                      = 0x3E9,
    CMSG_GUILD_BANK_BUY_TAB                         = 0x3EA,
    CMSG_GUILD_BANK_UPDATE_TAB                      = 0x3EB,
    CMSG_GUILD_BANK_DEPOSIT_MONEY                   = 0x3EC,
    CMSG_GUILD_BANK_WITHDRAW_MONEY                  = 0x3ED,
    MSG_GUILD_BANK_LOG_QUERY                        = 0x3EE,
    CMSG_SET_CHANNEL_WATCH                          = 0x3EF,
    SMSG_USERLIST_ADD                               = 0x3F0,
    SMSG_USERLIST_REMOVE                            = 0x3F1,
    SMSG_USERLIST_UPDATE                            = 0x3F2,
    CMSG_CLEAR_CHANNEL_WATCH                        = 0x3F3,
    SMSG_INSPECT_TALENT                             = 0x3F4,
    SMSG_GOGOGO_OBSOLETE                            = 0x3F5,
    SMSG_ECHO_PARTY_SQUELCH                         = 0x3F6,
    CMSG_SET_TITLE_SUFFIX                           = 0x3F7,
    CMSG_SPELLCLICK                                 = 0x3F8,
    SMSG_LOOT_LIST                                  = 0x3F9,
    CMSG_GM_CHARACTER_RESTORE                       = 0x3FA,
    CMSG_GM_CHARACTER_SAVE                          = 0x3FB,
    SMSG_VOICESESSION_FULL                          = 0x3FC,
    MSG_GUILD_PERMISSIONS                           = 0x3FD,
    MSG_GUILD_BANK_MONEY_WITHDRAWN                  = 0x3FE,
    MSG_GUILD_EVENT_LOG_QUERY                       = 0x3FF,
    CMSG_MAELSTROM_RENAME_GUILD                     = 0x400,
    CMSG_GET_MIRRORIMAGE_DATA                       = 0x401,
    SMSG_MIRRORIMAGE_DATA                           = 0x402,
    SMSG_FORCE_DISPLAY_UPDATE                       = 0x403,
    SMSG_SPELL_CHANCE_RESIST_PUSHBACK               = 0x404,
    CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT           = 0x405,
    SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT           = 0x406,
    CMSG_KEEP_ALIVE                                 = 0x407,
    SMSG_RAID_READY_CHECK_ERROR                     = 0x408,
    CMSG_OPT_OUT_OF_LOOT                            = 0x409,
    MSG_QUERY_GUILD_BANK_TEXT                       = 0x40A,
    CMSG_SET_GUILD_BANK_TEXT                        = 0x40B,
    CMSG_SET_GRANTABLE_LEVELS                       = 0x40C,
    CMSG_GRANT_LEVEL                                = 0x40D,
    CMSG_REFER_A_FRIEND                             = 0x40E,
    MSG_GM_CHANGE_ARENA_RATING                      = 0x40F,
    CMSG_DECLINE_CHANNEL_INVITE                     = 0x410,
    SMSG_GROUPACTION_THROTTLED                      = 0x411,
    SMSG_OVERRIDE_LIGHT                             = 0x412, // uint32 defaultMapLight, uint32 overrideLight, uint32 transitionTimeMs
    SMSG_TOTEM_CREATED                              = 0x413,
    CMSG_TOTEM_DESTROYED                            = 0x414,
    CMSG_EXPIRE_RAID_INSTANCE                       = 0x415,
    CMSG_NO_SPELL_VARIANCE                          = 0x416,
    CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY           = 0x417,
    SMSG_QUESTGIVER_STATUS_MULTIPLE                 = 0x418,
    CMSG_SET_PLAYER_DECLINED_NAMES                  = 0x419,
    SMSG_SET_PLAYER_DECLINED_NAMES_RESULT           = 0x41A,
    CMSG_QUERY_SERVER_BUCK_DATA                     = 0x41B,
    CMSG_CLEAR_SERVER_BUCK_DATA                     = 0x41C,
    SMSG_SERVER_BUCK_DATA                           = 0x41D,
    SMSG_SEND_UNLEARN_SPELLS                        = 0x41E,
    SMSG_PROPOSE_LEVEL_GRANT                        = 0x41F,
    CMSG_ACCEPT_LEVEL_GRANT                         = 0x420,
    SMSG_REFER_A_FRIEND_FAILURE                     = 0x421,
    SMSG_SPLINE_MOVE_SET_FLYING                     = 0x422,
    SMSG_SPLINE_MOVE_UNSET_FLYING                   = 0x423,
    SMSG_SUMMON_CANCEL                              = 0x424,
    CMSG_CHANGE_PERSONAL_ARENA_RATING               = 0x425,
    CMSG_ALTER_APPEARANCE                           = 0x426,
    SMSG_ENABLE_BARBER_SHOP                         = 0x427,
    SMSG_BARBER_SHOP_RESULT                         = 0x428,
    CMSG_CALENDAR_GET_CALENDAR                      = 0x429,
    CMSG_CALENDAR_GET_EVENT                         = 0x42A,
    CMSG_CALENDAR_GUILD_FILTER                      = 0x42B,
    CMSG_CALENDAR_ARENA_TEAM                        = 0x42C,
    CMSG_CALENDAR_ADD_EVENT                         = 0x42D,
    CMSG_CALENDAR_UPDATE_EVENT                      = 0x42E,
    CMSG_CALENDAR_REMOVE_EVENT                      = 0x42F,
    CMSG_CALENDAR_COPY_EVENT                        = 0x430,
    CMSG_CALENDAR_EVENT_INVITE                      = 0x431,
    CMSG_CALENDAR_EVENT_RSVP                        = 0x432,
    CMSG_CALENDAR_EVENT_REMOVE_INVITE               = 0x433,
    CMSG_CALENDAR_EVENT_STATUS                      = 0x434,
    CMSG_CALENDAR_EVENT_MODERATOR_STATUS            = 0x435,
    SMSG_CALENDAR_SEND_CALENDAR                     = 0x436,
    SMSG_CALENDAR_SEND_EVENT                        = 0x437,
    SMSG_CALENDAR_FILTER_GUILD                      = 0x438,
    SMSG_CALENDAR_ARENA_TEAM                        = 0x439,
    SMSG_CALENDAR_EVENT_INVITE                      = 0x43A,
    SMSG_CALENDAR_EVENT_INVITE_REMOVED              = 0x43B,
    SMSG_CALENDAR_EVENT_STATUS                      = 0x43C,
    SMSG_CALENDAR_COMMAND_RESULT                    = 0x43D,
    SMSG_CALENDAR_RAID_LOCKOUT_ADDED                = 0x43E,
    SMSG_CALENDAR_RAID_LOCKOUT_REMOVED              = 0x43F,
    SMSG_CALENDAR_EVENT_INVITE_ALERT                = 0x440,
    SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT        = 0x441,
    SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT         = 0x442,
    SMSG_CALENDAR_EVENT_REMOVED_ALERT               = 0x443,
    SMSG_CALENDAR_EVENT_UPDATED_ALERT               = 0x444,
    SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT      = 0x445,
    CMSG_CALENDAR_COMPLAIN                          = 0x446,
    CMSG_CALENDAR_GET_NUM_PENDING                   = 0x447,
    SMSG_CALENDAR_SEND_NUM_PENDING                  = 0x448,
    CMSG_SAVE_DANCE                                 = 0x449,
    SMSG_NOTIFY_DANCE                               = 0x44A,
    CMSG_PLAY_DANCE                                 = 0x44B,
    SMSG_PLAY_DANCE                                 = 0x44C,
    CMSG_LOAD_DANCES                                = 0x44D,
    CMSG_STOP_DANCE                                 = 0x44E,
    SMSG_STOP_DANCE                                 = 0x44F,
    CMSG_SYNC_DANCE                                 = 0x450,
    CMSG_DANCE_QUERY                                = 0x451,
    SMSG_DANCE_QUERY_RESPONSE                       = 0x452,
    SMSG_INVALIDATE_DANCE                           = 0x453,
    CMSG_DELETE_DANCE                               = 0x454,
    SMSG_LEARNED_DANCE_MOVES                        = 0x455,
    CMSG_LEARN_DANCE_MOVE                           = 0x456,
    CMSG_UNLEARN_DANCE_MOVE                         = 0x457,
    CMSG_SET_RUNE_COUNT                             = 0x458,
    CMSG_SET_RUNE_COOLDOWN                          = 0x459,
    MSG_MOVE_SET_PITCH_RATE_CHEAT                   = 0x45A,
    MSG_MOVE_SET_PITCH_RATE                         = 0x45B,
    SMSG_FORCE_PITCH_RATE_CHANGE                    = 0x45C,
    CMSG_FORCE_PITCH_RATE_CHANGE_ACK                = 0x45D,
    SMSG_SPLINE_SET_PITCH_RATE                      = 0x45E,
    CMSG_CALENDAR_EVENT_INVITE_NOTES                = 0x45F,
    SMSG_CALENDAR_EVENT_INVITE_NOTES                = 0x460,
    SMSG_CALENDAR_EVENT_INVITE_NOTES_ALERT          = 0x461,
    CMSG_UPDATE_MISSILE_TRAJECTORY                  = 0x462,
    SMSG_UPDATE_ACCOUNT_DATA_COMPLETE               = 0x463,
    SMSG_TRIGGER_MOVIE                              = 0x464,
    CMSG_COMPLETE_MOVIE                             = 0x465,
    CMSG_SET_GLYPH_SLOT                             = 0x466,
    CMSG_SET_GLYPH                                  = 0x467,
    SMSG_ACHIEVEMENT_EARNED                         = 0x468,
    SMSG_DYNAMIC_DROP_ROLL_RESULT                   = 0x469,
    SMSG_CRITERIA_UPDATE                            = 0x46A,
    CMSG_QUERY_INSPECT_ACHIEVEMENTS                 = 0x46B,
    SMSG_RESPOND_INSPECT_ACHIEVEMENTS               = 0x46C,
    CMSG_DISMISS_CONTROLLED_VEHICLE                 = 0x46D,
    CMSG_COMPLETE_ACHIEVEMENT_CHEAT                 = 0x46E,
    SMSG_QUESTUPDATE_ADD_PVP_KILL                   = 0x46F,
    CMSG_SET_CRITERIA_CHEAT                         = 0x470,
    SMSG_CALENDAR_RAID_LOCKOUT_UPDATED              = 0x471,
    CMSG_UNITANIMTIER_CHEAT                         = 0x472,
    CMSG_CHAR_CUSTOMIZE                             = 0x473,
    SMSG_CHAR_CUSTOMIZE                             = 0x474,
    SMSG_PET_RENAMEABLE                             = 0x475,
    CMSG_REQUEST_VEHICLE_EXIT                       = 0x476,
    CMSG_REQUEST_VEHICLE_PREV_SEAT                  = 0x477,
    CMSG_REQUEST_VEHICLE_NEXT_SEAT                  = 0x478,
    CMSG_REQUEST_VEHICLE_SWITCH_SEAT                = 0x479,
    CMSG_PET_LEARN_TALENT                           = 0x47A,
    CMSG_PET_UNLEARN_TALENTS                        = 0x47B,
    SMSG_SET_PHASE_SHIFT                            = 0x47C,
    SMSG_ALL_ACHIEVEMENT_DATA                       = 0x47D,
    CMSG_FORCE_SAY_CHEAT                            = 0x47E,
    SMSG_HEALTH_UPDATE                              = 0x47F,
    SMSG_POWER_UPDATE                               = 0x480,
    CMSG_GAMEOBJ_REPORT_USE                         = 0x481,
    SMSG_HIGHEST_THREAT_UPDATE                      = 0x482,
    SMSG_THREAT_UPDATE                              = 0x483,
    SMSG_THREAT_REMOVE                              = 0x484,
    SMSG_THREAT_CLEAR                               = 0x485,
    SMSG_CONVERT_RUNE                               = 0x486,
    SMSG_RESYNC_RUNES                               = 0x487,
    SMSG_ADD_RUNE_POWER                             = 0x488,
    CMSG_START_QUEST                                = 0x489,
    CMSG_REMOVE_GLYPH                               = 0x48A,
    CMSG_DUMP_OBJECTS                               = 0x48B,
    SMSG_DUMP_OBJECTS_DATA                          = 0x48C,
    CMSG_DISMISS_CRITTER                            = 0x48D,
    SMSG_NOTIFY_DEST_LOC_SPELL_CAST                 = 0x48E,
    CMSG_AUCTION_LIST_PENDING_SALES                 = 0x48F,
    SMSG_AUCTION_LIST_PENDING_SALES                 = 0x490,
    SMSG_MODIFY_COOLDOWN                            = 0x491,
    SMSG_PET_UPDATE_COMBO_POINTS                    = 0x492,
    CMSG_ENABLETAXI                                 = 0x493,
    SMSG_PRE_RESURRECT                              = 0x494,
    SMSG_AURA_UPDATE_ALL                            = 0x495,
    SMSG_AURA_UPDATE                                = 0x496,
    CMSG_FLOOD_GRACE_CHEAT                          = 0x497,
    SMSG_SERVER_FIRST_ACHIEVEMENT                   = 0x498,
    SMSG_PET_LEARNED_SPELL                          = 0x499,
    SMSG_PET_UNLEARNED_SPELL                        = 0x49A,
    CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE         = 0x49B,
    CMSG_HEARTH_AND_RESURRECT                       = 0x49C,
    SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA       = 0x49D,
    SMSG_CRITERIA_DELETED                           = 0x49E,
    SMSG_ACHIEVEMENT_DELETED                        = 0x49F,
    CMSG_SERVER_INFO_QUERY                          = 0x4A0,
    SMSG_SERVER_INFO_RESPONSE                       = 0x4A1,
    CMSG_CHECK_LOGIN_CRITERIA                       = 0x4A2,
    SMSG_SERVER_BUCK_DATA_START                     = 0x4A3,
    CMSG_SET_BREATH                                 = 0x4A4,
    CMSG_QUERY_VEHICLE_STATUS                       = 0x4A5,
    SMSG_BATTLEGROUND_INFO_THROTTLED                = 0x4A6, // empty, "You can't do that yet"
    SMSG_PLAYER_VEHICLE_DATA                        = 0x4A7, // guid+uint32 (vehicle)
    CMSG_PLAYER_VEHICLE_ENTER                       = 0x4A8, // uint64
    CMSG_CONTROLLER_EJECT_PASSENGER                 = 0x4A9, // uint64
    SMSG_PET_GUIDS                                  = 0x4AA,
    SMSG_CLIENTCACHE_VERSION                        = 0x4AB,
    CMSG_CHANGE_GDF_ARENA_RATING                    = 0x4AC,
    CMSG_SET_ARENA_TEAM_RATING_BY_INDEX             = 0x4AD,
    CMSG_SET_ARENA_TEAM_WEEKLY_GAMES                = 0x4AE,
    CMSG_SET_ARENA_TEAM_SEASON_GAMES                = 0x4AF,
    CMSG_SET_ARENA_MEMBER_WEEKLY_GAMES              = 0x4B0,
    CMSG_SET_ARENA_MEMBER_SEASON_GAMES              = 0x4B1,
    SMSG_ITEM_REFUND_INFO_RESPONSE                  = 0x4B2,
    CMSG_ITEM_REFUND_INFO                           = 0x4B3,
    CMSG_ITEM_REFUND                                = 0x4B4, // lua: ContainerRefundItemPurchase
    SMSG_ITEM_REFUND_RESULT                         = 0x4B5,
    CMSG_CORPSE_MAP_POSITION_QUERY                  = 0x4B6, // uint32
    SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE         = 0x4B7, // 3*float+float
    CMSG_UNUSED5                                    = 0x4B8,
    CMSG_UNUSED6                                    = 0x4B9,
    CMSG_CALENDAR_EVENT_SIGNUP                      = 0x4BA, // uint64
    SMSG_CALENDAR_CLEAR_PENDING_ACTION              = 0x4BB,
    SMSG_EQUIPMENT_SET_LIST                         = 0x4BC, // equipment manager list?
    CMSG_EQUIPMENT_SET_SAVE                         = 0x4BD,
    CMSG_UPDATE_PROJECTILE_POSITION                 = 0x4BE,
    SMSG_SET_PROJECTILE_POSITION                    = 0x4BF,
    SMSG_TALENTS_INFO                               = 0x4C0,
    CMSG_LEARN_PREVIEW_TALENTS                      = 0x4C1,
    CMSG_LEARN_PREVIEW_TALENTS_PET                  = 0x4C2,
    CMSG_SET_ACTIVE_TALENT_GROUP_OBSOLETE           = 0x4C3,
    CMSG_GM_GRANT_ACHIEVEMENT                       = 0x4C4,
    CMSG_GM_REMOVE_ACHIEVEMENT                      = 0x4C5,
    CMSG_GM_SET_CRITERIA_FOR_PLAYER                 = 0x4C6,
    SMSG_ARENA_UNIT_DESTROYED                       = 0x4C7,
    SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED            = 0x4C8, // uint32 "Can't modify arena team while queued or in a match."
    CMSG_PROFILEDATA_REQUEST                        = 0x4C9,
    SMSG_PROFILEDATA_RESPONSE                       = 0x4CA,
    CMSG_START_BATTLEFIELD_CHEAT                    = 0x4CB,
    CMSG_END_BATTLEFIELD_CHEAT                      = 0x4CC,
    SMSG_MULTIPLE_PACKETS                           = 0x4CD,
    SMSG_MOVE_GRAVITY_DISABLE                       = 0x4CE,
    CMSG_MOVE_GRAVITY_DISABLE_ACK                   = 0x4CF,
    SMSG_MOVE_GRAVITY_ENABLE                        = 0x4D0,
    CMSG_MOVE_GRAVITY_ENABLE_ACK                    = 0x4D1,
    MSG_MOVE_GRAVITY_CHNG                           = 0x4D2,
    SMSG_SPLINE_MOVE_GRAVITY_DISABLE                = 0x4D3,
    SMSG_SPLINE_MOVE_GRAVITY_ENABLE                 = 0x4D4,
    CMSG_EQUIPMENT_SET_USE                          = 0x4D5,
    SMSG_EQUIPMENT_SET_USE_RESULT                   = 0x4D6,
    CMSG_FORCE_ANIM                                 = 0x4D7,
    SMSG_FORCE_ANIM                                 = 0x4D8,
    CMSG_CHAR_FACTION_CHANGE                        = 0x4D9,
    SMSG_CHAR_FACTION_CHANGE                        = 0x4DA,
    CMSG_PVP_QUEUE_STATS_REQUEST                    = 0x4DB,
    SMSG_PVP_QUEUE_STATS                            = 0x4DC,
    CMSG_SET_PAID_SERVICE_CHEAT                     = 0x4DD,
    SMSG_BATTLEFIELD_MGR_ENTRY_INVITE               = 0x4DE, // uint32
    CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE      = 0x4DF,
    SMSG_BATTLEFIELD_MGR_ENTERED                    = 0x4E0, // uint32, uint8, uint8
    SMSG_BATTLEFIELD_MGR_QUEUE_INVITE               = 0x4E1, // uint32
    CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE      = 0x4E2,
    CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST              = 0x4E3,
    SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE     = 0x4E4, // uint32, uint8
    SMSG_BATTLEFIELD_MGR_EJECT_PENDING              = 0x4E5, // uint32
    SMSG_BATTLEFIELD_MGR_EJECTED                    = 0x4E6, // uint32, uint32, uint8
    CMSG_BATTLEFIELD_MGR_EXIT_REQUEST               = 0x4E7,
    SMSG_BATTLEFIELD_MGR_STATE_CHANGE               = 0x4E8, // uint32, uint32
    CMSG_BATTLEFIELD_MANAGER_ADVANCE_STATE          = 0x4E9,
    CMSG_BATTLEFIELD_MANAGER_SET_NEXT_TRANSITION_TIME = 0x4EA,
    MSG_SET_RAID_DIFFICULTY                         = 0x4EB,
    CMSG_TOGGLE_XP_GAIN                             = 0x4EC,
    SMSG_TOGGLE_XP_GAIN                             = 0x4ED, // enable/disable XP gain console message
    SMSG_GMRESPONSE_DB_ERROR                        = 0x4EE, // empty
    SMSG_GMRESPONSE_RECEIVED                        = 0x4EF, // uint32, uint32, string[2000], string[4000][4]
    CMSG_GMRESPONSE_RESOLVE                         = 0x4F0,
    SMSG_GMRESPONSE_STATUS_UPDATE                   = 0x4F1, // uint8 (1 - EVENT_GMSURVEY_DISPLAY, 0 - EVENT_UPDATE_TICKET)
    SMSG_GMRESPONSE_CREATE_TICKET                   = 0x4F2,
    CMSG_GMRESPONSE_CREATE_TICKET                   = 0x4F3,
    CMSG_SERVERINFO                                 = 0x4F4,
    SMSG_SERVERINFO                                 = 0x4F5,
    CMSG_WORLD_STATE_UI_TIMER_UPDATE                = 0x4F6,
    SMSG_WORLD_STATE_UI_TIMER_UPDATE                = 0x4F7,
    CMSG_CHAR_RACE_CHANGE                           = 0x4F8,
    MSG_VIEW_PHASE_SHIFT                            = 0x4F9,
    SMSG_TALENTS_INVOLUNTARILY_RESET                = 0x4FA, // uint8
    CMSG_DEBUG_SERVER_GEO                           = 0x4FB,
    SMSG_DEBUG_SERVER_GEO                           = 0x4FC,
    SMSG_LOOT_SLOT_CHANGED                          = 0x4FD,
    UMSG_UPDATE_GROUP_INFO                          = 0x4FE,
    CMSG_READY_FOR_ACCOUNT_DATA_TIMES               = 0x4FF,
    CMSG_QUERY_QUESTS_COMPLETED                     = 0x500,
    SMSG_QUERY_QUESTS_COMPLETED_RESPONSE            = 0x501,
    CMSG_GM_REPORT_LAG                              = 0x502,
    CMSG_AFK_MONITOR_INFO_REQUEST                   = 0x503,
    SMSG_AFK_MONITOR_INFO_RESPONSE                  = 0x504,
    CMSG_AFK_MONITOR_INFO_CLEAR                     = 0x505,
    SMSG_CORPSE_NOT_IN_INSTANCE                     = 0x506,
    CMSG_GM_NUKE_CHARACTER                          = 0x507,
    CMSG_SET_ALLOW_LOW_LEVEL_RAID1                  = 0x508,
    CMSG_SET_ALLOW_LOW_LEVEL_RAID2                  = 0x509,
    SMSG_CAMERA_SHAKE                               = 0x50A, // uint32 SpellEffectCameraShakes.dbc index, uint32
    SMSG_SOCKET_GEMS_RESULT                         = 0x50B,
    CMSG_SET_CHARACTER_MODEL                        = 0x50C,
    SMSG_REDIRECT_CLIENT                            = 0x50D, // uint32 ip, uint16 port, uint32 unk, uint8[20] hash (ip + port, seed=sessionkey)
    CMSG_REDIRECTION_FAILED                         = 0x50E, // something with networking
    SMSG_SUSPEND_COMMS                              = 0x50F,
    CMSG_SUSPEND_COMMS_ACK                          = 0x510,
    SMSG_FORCE_SEND_QUEUED_PACKETS                  = 0x511,
    CMSG_REDIRECTION_AUTH_PROOF                     = 0x512,
    CMSG_DROP_NEW_CONNECTION                        = 0x513,
    SMSG_SEND_ALL_COMBAT_LOG                        = 0x514,
    SMSG_OPEN_LFG_DUNGEON_FINDER                    = 0x515,
    SMSG_MOVE_SET_COLLISION_HGT                     = 0x516,
    CMSG_MOVE_SET_COLLISION_HGT_ACK                 = 0x517,
    MSG_MOVE_SET_COLLISION_HGT                      = 0x518,
    CMSG_CLEAR_RANDOM_BG_WIN_TIME                   = 0x519,
    CMSG_CLEAR_HOLIDAY_BG_WIN_TIME                  = 0x51A,
    CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND         = 0x51B,
    SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT1         = 0x51C,
    SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT2         = 0x51D,
    SMSG_MULTIPLE_MOVES                             = 0x51E, // uncompressed version of SMSG_COMPRESSED_MOVES
    NUM_MSG_TYPES                                   = 0x51F
};
PacketProcessing
enum PacketProcessing
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
Enumerator
PROCESS_INPLACE
PROCESS_THREADUNSAFE
PROCESS_THREADSAFE
{
    PROCESS_INPLACE = 0,                                    //process packet whenever we receive it - mostly for non-handled or non-implemented packets
    PROCESS_THREADUNSAFE,                                   //packet is not thread-safe - process it in World::UpdateSessions()
    PROCESS_THREADSAFE                                      //packet is thread-safe - process it in Map::Update()
};
PartyOperation
enum PartyOperation
#include <azerothcore-wotlk/src/server/game/Server/WorldSession.h>
Enumerator
PARTY_OP_INVITE
PARTY_OP_UNINVITE
PARTY_OP_LEAVE
PARTY_OP_SWAP
{
    PARTY_OP_INVITE = 0,
    PARTY_OP_UNINVITE = 1,
    PARTY_OP_LEAVE = 2,
    PARTY_OP_SWAP = 4
};
SessionStatus
enum SessionStatus
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
Player state.
Enumerator
STATUS_AUTHED
STATUS_LOGGEDIN
STATUS_TRANSFER
STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT
STATUS_NEVER
STATUS_UNHANDLED
{
    STATUS_AUTHED = 0,                                      // Player authenticated (_player == nullptr, m_playerRecentlyLogout = false or will be reset before handler call, m_GUID have garbage)
    STATUS_LOGGEDIN,                                        // Player in game (_player != nullptr, m_GUID == _player->GetGUID(), inWorld())
    STATUS_TRANSFER,                                        // Player transferring to another map (_player != nullptr, m_GUID == _player->GetGUID(), !inWorld())
    STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT,                    // _player != nullptr or _player == nullptr && m_playerRecentlyLogout && m_playerLogout, m_GUID store last _player guid)
    STATUS_NEVER,                                           // Opcode not accepted from client (deprecated or server side only)
    STATUS_UNHANDLED,                                       // Opcode not handled yet
};
Function Documentation
Call()
virtual void ClientOpcodeHandler::Call (WorldSession * session, WorldPacket & packet) const pure virtual
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
Implemented in PacketHandler< PacketClass, HandlerFunction >, and PacketHandler< WorldPacket, HandlerFunction >.
Referenced by WorldSession::Update().
ClientOpcodeHandler()
ClientOpcodeHandler::ClientOpcodeHandler (char const * name, SessionStatus status, PacketProcessing processing) inline
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
        : OpcodeHandler(name, status), ProcessingPlace(processing) { }
GetOpcodeNameForLogging()
std::string GetOpcodeNameForLogging (Opcodes opcode)
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
Lookup opcode name for human understandable logging.
{
    return GetOpcodeNameForLoggingImpl(opcode);
}
References GetOpcodeNameForLoggingImpl().
Referenced by WorldSession::Handle_Deprecated(), WorldSession::Handle_EarlyProccess(), WorldSession::Handle_NULL(), WorldSession::Handle_ServerSide(), WorldSession::HandleForceSpeedChangeAck(), WorldSocket::LogOpcodeText(), WorldSession::LogUnexpectedOpcode(), WorldSession::LogUnprocessedTail(), WorldSocket::ReadDataHandler(), WorldSocket::SendPacketAndLogOpcode(), and WorldSession::Update().
Initialize()
void OpcodeTable::Initialize ()
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
Correspondence between opcodes and their names.
{
#define DEFINE_HANDLER(opcode, status, processing, handler) \
    ValidateAndSetClientOpcode<decltype(handler), handler>(opcode, #opcode, status, processing)
#define DEFINE_SERVER_OPCODE_HANDLER(opcode, status) \
    static_assert(status == STATUS_NEVER || status == STATUS_UNHANDLED, "Invalid status for server opcode"); \
    ValidateAndSetServerOpcode(opcode, #opcode, status)
    /*0x001*/ DEFINE_HANDLER(CMSG_BOOTME,                                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x002*/ DEFINE_HANDLER(CMSG_DBLOOKUP,                                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x003*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DBLOOKUP,                                           STATUS_NEVER);
    /*0x004*/ DEFINE_HANDLER(CMSG_QUERY_OBJECT_POSITION,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x005*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUERY_OBJECT_POSITION,                              STATUS_NEVER);
    /*0x006*/ DEFINE_HANDLER(CMSG_QUERY_OBJECT_ROTATION,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x007*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUERY_OBJECT_ROTATION,                              STATUS_NEVER);
    /*0x008*/ DEFINE_HANDLER(CMSG_WORLD_TELEPORT,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleWorldTeleportOpcode                );
    /*0x009*/ DEFINE_HANDLER(CMSG_TELEPORT_TO_UNIT,                                                 STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x00A*/ DEFINE_HANDLER(CMSG_ZONE_MAP,                                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x00B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ZONE_MAP,                                           STATUS_NEVER);
    /*0x00C*/ DEFINE_HANDLER(CMSG_DEBUG_CHANGECELLZONE,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x00D*/ DEFINE_HANDLER(CMSG_MOVE_CHARACTER_CHEAT,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x00E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_CHARACTER_CHEAT,                               STATUS_NEVER);
    /*0x00F*/ DEFINE_HANDLER(CMSG_RECHARGE,                                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x010*/ DEFINE_HANDLER(CMSG_LEARN_SPELL,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x011*/ DEFINE_HANDLER(CMSG_CREATEMONSTER,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x012*/ DEFINE_HANDLER(CMSG_DESTROYMONSTER,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x013*/ DEFINE_HANDLER(CMSG_CREATEITEM,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x014*/ DEFINE_HANDLER(CMSG_CREATEGAMEOBJECT,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x015*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHECK_FOR_BOTS,                                     STATUS_NEVER);
    /*0x016*/ DEFINE_HANDLER(CMSG_MAKEMONSTERATTACKGUID,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x017*/ DEFINE_HANDLER(CMSG_BOT_DETECTED2,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x018*/ DEFINE_HANDLER(CMSG_FORCEACTION,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x019*/ DEFINE_HANDLER(CMSG_FORCEACTIONONOTHER,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x01A*/ DEFINE_HANDLER(CMSG_FORCEACTIONSHOW,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x01B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCEACTIONSHOW,                                    STATUS_NEVER);
    /*0x01C*/ DEFINE_HANDLER(CMSG_PETGODMODE,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x01D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PETGODMODE,                                         STATUS_NEVER);
    /*0x01E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_REFER_A_FRIEND_EXPIRED,                             STATUS_NEVER);
    /*0x01F*/ DEFINE_HANDLER(CMSG_WEATHER_SPEED_CHEAT,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x020*/ DEFINE_HANDLER(CMSG_UNDRESSPLAYER,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x021*/ DEFINE_HANDLER(CMSG_BEASTMASTER,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x022*/ DEFINE_HANDLER(CMSG_GODMODE,                                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x023*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GODMODE,                                            STATUS_NEVER);
    /*0x024*/ DEFINE_HANDLER(CMSG_CHEAT_SETMONEY,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x025*/ DEFINE_HANDLER(CMSG_LEVEL_CHEAT,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x026*/ DEFINE_HANDLER(CMSG_PET_LEVEL_CHEAT,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x027*/ DEFINE_HANDLER(CMSG_SET_WORLDSTATE,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x028*/ DEFINE_HANDLER(CMSG_COOLDOWN_CHEAT,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x029*/ DEFINE_HANDLER(CMSG_USE_SKILL_CHEAT,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x02A*/ DEFINE_HANDLER(CMSG_FLAG_QUEST,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x02B*/ DEFINE_HANDLER(CMSG_FLAG_QUEST_FINISH,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x02C*/ DEFINE_HANDLER(CMSG_CLEAR_QUEST,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x02D*/ DEFINE_HANDLER(CMSG_SEND_EVENT,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x02E*/ DEFINE_HANDLER(CMSG_DEBUG_AISTATE,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x02F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DEBUG_AISTATE,                                      STATUS_NEVER);
    /*0x030*/ DEFINE_HANDLER(CMSG_DISABLE_PVP_CHEAT,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x031*/ DEFINE_HANDLER(CMSG_ADVANCE_SPAWN_TIME,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x032*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DESTRUCTIBLE_BUILDING_DAMAGE,                       STATUS_NEVER);
    /*0x033*/ DEFINE_HANDLER(CMSG_AUTH_SRP6_BEGIN,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x034*/ DEFINE_HANDLER(CMSG_AUTH_SRP6_PROOF,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x035*/ DEFINE_HANDLER(CMSG_AUTH_SRP6_RECODE,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x036*/ DEFINE_HANDLER(CMSG_CHAR_CREATE,                                                      STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleCharCreateOpcode                   );
    /*0x037*/ DEFINE_HANDLER(CMSG_CHAR_ENUM,                                                        STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleCharEnumOpcode                     );
    /*0x038*/ DEFINE_HANDLER(CMSG_CHAR_DELETE,                                                      STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleCharDeleteOpcode                   );
    /*0x039*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUTH_SRP6_RESPONSE,                                 STATUS_NEVER);
    /*0x03A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAR_CREATE,                                        STATUS_NEVER);
    /*0x03B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAR_ENUM,                                          STATUS_NEVER);
    /*0x03C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAR_DELETE,                                        STATUS_NEVER);
    /*0x03D*/ DEFINE_HANDLER(CMSG_PLAYER_LOGIN,                                                     STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandlePlayerLoginOpcode                  );
    /*0x03E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_NEW_WORLD,                                          STATUS_NEVER);
    /*0x03F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TRANSFER_PENDING,                                   STATUS_NEVER);
    /*0x040*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TRANSFER_ABORTED,                                   STATUS_NEVER);
    /*0x041*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHARACTER_LOGIN_FAILED,                             STATUS_NEVER);
    /*0x042*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOGIN_SETTIMESPEED,                                 STATUS_NEVER);
    /*0x043*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GAMETIME_UPDATE,                                    STATUS_NEVER);
    /*0x044*/ DEFINE_HANDLER(CMSG_GAMETIME_SET,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x045*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GAMETIME_SET,                                       STATUS_NEVER);
    /*0x046*/ DEFINE_HANDLER(CMSG_GAMESPEED_SET,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x047*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GAMESPEED_SET,                                      STATUS_NEVER);
    /*0x048*/ DEFINE_HANDLER(CMSG_SERVERTIME,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x049*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SERVERTIME,                                         STATUS_NEVER);
    /*0x04A*/ DEFINE_HANDLER(CMSG_PLAYER_LOGOUT,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandlePlayerLogoutOpcode                 );
    /*0x04B*/ DEFINE_HANDLER(CMSG_LOGOUT_REQUEST,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLogoutRequestOpcode                );
    /*0x04C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOGOUT_RESPONSE,                                    STATUS_NEVER);
    /*0x04D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOGOUT_COMPLETE,                                    STATUS_NEVER);
    /*0x04E*/ DEFINE_HANDLER(CMSG_LOGOUT_CANCEL,                                                    STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLogoutCancelOpcode);
    /*0x04F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOGOUT_CANCEL_ACK,                                  STATUS_NEVER);
    /*0x050*/ DEFINE_HANDLER(CMSG_NAME_QUERY,                                                       STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleNameQueryOpcode                    );
    /*0x051*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_NAME_QUERY_RESPONSE,                                STATUS_NEVER);
    /*0x052*/ DEFINE_HANDLER(CMSG_PET_NAME_QUERY,                                                   STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandlePetNameQuery                       );
    /*0x053*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_NAME_QUERY_RESPONSE,                            STATUS_NEVER);
    /*0x054*/ DEFINE_HANDLER(CMSG_GUILD_QUERY,                                                      STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildQueryOpcode                   );
    /*0x055*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GUILD_QUERY_RESPONSE,                               STATUS_NEVER);
    /*0x056*/ DEFINE_HANDLER(CMSG_ITEM_QUERY_SINGLE,                                                STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleItemQuerySingleOpcode              );
    /*0x057*/ DEFINE_HANDLER(CMSG_ITEM_QUERY_MULTIPLE,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x058*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ITEM_QUERY_SINGLE_RESPONSE,                         STATUS_NEVER);
    /*0x059*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ITEM_QUERY_MULTIPLE_RESPONSE,                       STATUS_NEVER);
    /*0x05A*/ DEFINE_HANDLER(CMSG_PAGE_TEXT_QUERY,                                                  STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandlePageTextQueryOpcode                );
    /*0x05B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PAGE_TEXT_QUERY_RESPONSE,                           STATUS_NEVER);
    /*0x05C*/ DEFINE_HANDLER(CMSG_QUEST_QUERY,                                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestQueryOpcode                   );
    /*0x05D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUEST_QUERY_RESPONSE,                               STATUS_NEVER);
    /*0x05E*/ DEFINE_HANDLER(CMSG_GAMEOBJECT_QUERY,                                                 STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleGameObjectQueryOpcode              );
    /*0x05F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GAMEOBJECT_QUERY_RESPONSE,                          STATUS_NEVER);
    /*0x060*/ DEFINE_HANDLER(CMSG_CREATURE_QUERY,                                                   STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleCreatureQueryOpcode                );
    /*0x061*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CREATURE_QUERY_RESPONSE,                            STATUS_NEVER);
    /*0x062*/ DEFINE_HANDLER(CMSG_WHO,                                                              STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleWhoOpcode                          );
    /*0x063*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_WHO,                                                STATUS_NEVER);
    /*0x064*/ DEFINE_HANDLER(CMSG_WHOIS,                                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleWhoisOpcode                        );
    /*0x065*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_WHOIS,                                              STATUS_NEVER);
    /*0x066*/ DEFINE_HANDLER(CMSG_CONTACT_LIST,                                                     STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleContactListOpcode                  );
    /*0x067*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CONTACT_LIST,                                       STATUS_NEVER);
    /*0x068*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FRIEND_STATUS,                                      STATUS_NEVER);
    /*0x069*/ DEFINE_HANDLER(CMSG_ADD_FRIEND,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAddFriendOpcode                    );
    /*0x06A*/ DEFINE_HANDLER(CMSG_DEL_FRIEND,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleDelFriendOpcode                    );
    /*0x06B*/ DEFINE_HANDLER(CMSG_SET_CONTACT_NOTES,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetContactNotesOpcode              );
    /*0x06C*/ DEFINE_HANDLER(CMSG_ADD_IGNORE,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAddIgnoreOpcode                    );
    /*0x06D*/ DEFINE_HANDLER(CMSG_DEL_IGNORE,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleDelIgnoreOpcode                    );
    /*0x06E*/ DEFINE_HANDLER(CMSG_GROUP_INVITE,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupInviteOpcode                  );
    /*0x06F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GROUP_INVITE,                                       STATUS_NEVER);
    /*0x070*/ DEFINE_HANDLER(CMSG_GROUP_CANCEL,                                                     STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x071*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GROUP_CANCEL,                                       STATUS_NEVER);
    /*0x072*/ DEFINE_HANDLER(CMSG_GROUP_ACCEPT,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupAcceptOpcode                  );
    /*0x073*/ DEFINE_HANDLER(CMSG_GROUP_DECLINE,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupDeclineOpcode                 );
    /*0x074*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GROUP_DECLINE,                                      STATUS_NEVER);
    /*0x075*/ DEFINE_HANDLER(CMSG_GROUP_UNINVITE,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupUninviteOpcode                );
    /*0x076*/ DEFINE_HANDLER(CMSG_GROUP_UNINVITE_GUID,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupUninviteGuidOpcode            );
    /*0x077*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GROUP_UNINVITE,                                     STATUS_NEVER);
    /*0x078*/ DEFINE_HANDLER(CMSG_GROUP_SET_LEADER,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupSetLeaderOpcode               );
    /*0x079*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GROUP_SET_LEADER,                                   STATUS_NEVER);
    /*0x07A*/ DEFINE_HANDLER(CMSG_LOOT_METHOD,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLootMethodOpcode                   );
    /*0x07B*/ DEFINE_HANDLER(CMSG_GROUP_DISBAND,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupDisbandOpcode                 );
    /*0x07C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GROUP_DESTROYED,                                    STATUS_NEVER);
    /*0x07D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GROUP_LIST,                                         STATUS_NEVER);
    /*0x07E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PARTY_MEMBER_STATS,                                 STATUS_NEVER);
    /*0x07F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PARTY_COMMAND_RESULT,                               STATUS_NEVER);
    /*0x080*/ DEFINE_HANDLER(UMSG_UPDATE_GROUP_MEMBERS,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x081*/ DEFINE_HANDLER(CMSG_GUILD_CREATE,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildCreateOpcode                  );
    /*0x082*/ DEFINE_HANDLER(CMSG_GUILD_INVITE,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildInviteOpcode                  );
    /*0x083*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GUILD_INVITE,                                       STATUS_NEVER);
    /*0x084*/ DEFINE_HANDLER(CMSG_GUILD_ACCEPT,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildAcceptOpcode                  );
    /*0x085*/ DEFINE_HANDLER(CMSG_GUILD_DECLINE,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildDeclineOpcode                 );
    /*0x086*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GUILD_DECLINE,                                      STATUS_NEVER);
    /*0x087*/ DEFINE_HANDLER(CMSG_GUILD_INFO,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildInfoOpcode                    );
    /*0x088*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GUILD_INFO,                                         STATUS_NEVER);
    /*0x089*/ DEFINE_HANDLER(CMSG_GUILD_ROSTER,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildRosterOpcode                  );
    /*0x08A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GUILD_ROSTER,                                       STATUS_NEVER);
    /*0x08B*/ DEFINE_HANDLER(CMSG_GUILD_PROMOTE,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildPromoteOpcode                 );
    /*0x08C*/ DEFINE_HANDLER(CMSG_GUILD_DEMOTE,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildDemoteOpcode                  );
    /*0x08D*/ DEFINE_HANDLER(CMSG_GUILD_LEAVE,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildLeaveOpcode                   );
    /*0x08E*/ DEFINE_HANDLER(CMSG_GUILD_REMOVE,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildRemoveOpcode                  );
    /*0x08F*/ DEFINE_HANDLER(CMSG_GUILD_DISBAND,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildDisbandOpcode                 );
    /*0x090*/ DEFINE_HANDLER(CMSG_GUILD_LEADER,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildLeaderOpcode                  );
    /*0x091*/ DEFINE_HANDLER(CMSG_GUILD_MOTD,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildMOTDOpcode                    );
    /*0x092*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GUILD_EVENT,                                        STATUS_NEVER);
    /*0x093*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GUILD_COMMAND_RESULT,                               STATUS_NEVER);
    /*0x094*/ DEFINE_HANDLER(UMSG_UPDATE_GUILD,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x095*/ DEFINE_HANDLER(CMSG_MESSAGECHAT,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMessagechatOpcode                  );
    /*0x096*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MESSAGECHAT,                                        STATUS_NEVER);
    /*0x097*/ DEFINE_HANDLER(CMSG_JOIN_CHANNEL,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleJoinChannel                        );
    /*0x098*/ DEFINE_HANDLER(CMSG_LEAVE_CHANNEL,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLeaveChannel                       );
    /*0x099*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHANNEL_NOTIFY,                                     STATUS_NEVER);
    /*0x09A*/ DEFINE_HANDLER(CMSG_CHANNEL_LIST,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelList                        );
    /*0x09B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHANNEL_LIST,                                       STATUS_NEVER);
    /*0x09C*/ DEFINE_HANDLER(CMSG_CHANNEL_PASSWORD,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelPassword                    );
    /*0x09D*/ DEFINE_HANDLER(CMSG_CHANNEL_SET_OWNER,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelSetOwner                    );
    /*0x09E*/ DEFINE_HANDLER(CMSG_CHANNEL_OWNER,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelOwner                       );
    /*0x09F*/ DEFINE_HANDLER(CMSG_CHANNEL_MODERATOR,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelModerator                   );
    /*0x0A0*/ DEFINE_HANDLER(CMSG_CHANNEL_UNMODERATOR,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelUnmoderator                 );
    /*0x0A1*/ DEFINE_HANDLER(CMSG_CHANNEL_MUTE,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelMute                        );
    /*0x0A2*/ DEFINE_HANDLER(CMSG_CHANNEL_UNMUTE,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelUnmute                      );
    /*0x0A3*/ DEFINE_HANDLER(CMSG_CHANNEL_INVITE,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelInvite                      );
    /*0x0A4*/ DEFINE_HANDLER(CMSG_CHANNEL_KICK,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelKick                        );
    /*0x0A5*/ DEFINE_HANDLER(CMSG_CHANNEL_BAN,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelBan                         );
    /*0x0A6*/ DEFINE_HANDLER(CMSG_CHANNEL_UNBAN,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelUnban                       );
    /*0x0A7*/ DEFINE_HANDLER(CMSG_CHANNEL_ANNOUNCEMENTS,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelAnnouncements               );
    /*0x0A8*/ DEFINE_HANDLER(CMSG_CHANNEL_MODERATE,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChannelModerateOpcode              );
    /*0x0A9*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_UPDATE_OBJECT,                                      STATUS_NEVER);
    /*0x0AA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DESTROY_OBJECT,                                     STATUS_NEVER);
    /*0x0AB*/ DEFINE_HANDLER(CMSG_USE_ITEM,                                                         STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleUseItemOpcode                      );
    /*0x0AC*/ DEFINE_HANDLER(CMSG_OPEN_ITEM,                                                        STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleOpenItemOpcode                     );
    /*0x0AD*/ DEFINE_HANDLER(CMSG_READ_ITEM,                                                        STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleReadItem                           );
    /*0x0AE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_READ_ITEM_OK,                                       STATUS_NEVER);
    /*0x0AF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_READ_ITEM_FAILED,                                   STATUS_NEVER);
    /*0x0B0*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ITEM_COOLDOWN,                                      STATUS_NEVER);
    /*0x0B1*/ DEFINE_HANDLER(CMSG_GAMEOBJ_USE,                                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleGameObjectUseOpcode                );
    /*0x0B2*/ DEFINE_HANDLER(CMSG_DESTROY_ITEMS,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0B3*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GAMEOBJECT_CUSTOM_ANIM,                             STATUS_NEVER);
    /*0x0B4*/ DEFINE_HANDLER(CMSG_AREATRIGGER,                                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleAreaTriggerOpcode                  );
    /*0x0B5*/ DEFINE_HANDLER(MSG_MOVE_START_FORWARD,                                                STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0B6*/ DEFINE_HANDLER(MSG_MOVE_START_BACKWARD,                                               STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0B7*/ DEFINE_HANDLER(MSG_MOVE_STOP,                                                         STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0B8*/ DEFINE_HANDLER(MSG_MOVE_START_STRAFE_LEFT,                                            STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0B9*/ DEFINE_HANDLER(MSG_MOVE_START_STRAFE_RIGHT,                                           STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0BA*/ DEFINE_HANDLER(MSG_MOVE_STOP_STRAFE,                                                  STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0BB*/ DEFINE_HANDLER(MSG_MOVE_JUMP,                                                         STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0BC*/ DEFINE_HANDLER(MSG_MOVE_START_TURN_LEFT,                                              STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0BD*/ DEFINE_HANDLER(MSG_MOVE_START_TURN_RIGHT,                                             STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0BE*/ DEFINE_HANDLER(MSG_MOVE_STOP_TURN,                                                    STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0BF*/ DEFINE_HANDLER(MSG_MOVE_START_PITCH_UP,                                               STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0C0*/ DEFINE_HANDLER(MSG_MOVE_START_PITCH_DOWN,                                             STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0C1*/ DEFINE_HANDLER(MSG_MOVE_STOP_PITCH,                                                   STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0C2*/ DEFINE_HANDLER(MSG_MOVE_SET_RUN_MODE,                                                 STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0C3*/ DEFINE_HANDLER(MSG_MOVE_SET_WALK_MODE,                                                STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0C4*/ DEFINE_HANDLER(MSG_MOVE_TOGGLE_LOGGING,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0C5*/ DEFINE_HANDLER(MSG_MOVE_TELEPORT,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0C6*/ DEFINE_HANDLER(MSG_MOVE_TELEPORT_CHEAT,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0C7*/ DEFINE_HANDLER(MSG_MOVE_TELEPORT_ACK,                                                 STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMoveTeleportAck                    );
    /*0x0C8*/ DEFINE_HANDLER(MSG_MOVE_TOGGLE_FALL_LOGGING,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0C9*/ DEFINE_HANDLER(MSG_MOVE_FALL_LAND,                                                    STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0CA*/ DEFINE_HANDLER(MSG_MOVE_START_SWIM,                                                   STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0CB*/ DEFINE_HANDLER(MSG_MOVE_STOP_SWIM,                                                    STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0CC*/ DEFINE_HANDLER(MSG_MOVE_SET_RUN_SPEED_CHEAT,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0CD*/ DEFINE_HANDLER(MSG_MOVE_SET_RUN_SPEED,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0CE*/ DEFINE_HANDLER(MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT,                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0CF*/ DEFINE_HANDLER(MSG_MOVE_SET_RUN_BACK_SPEED,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0D0*/ DEFINE_HANDLER(MSG_MOVE_SET_WALK_SPEED_CHEAT,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0D1*/ DEFINE_HANDLER(MSG_MOVE_SET_WALK_SPEED,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0D2*/ DEFINE_HANDLER(MSG_MOVE_SET_SWIM_SPEED_CHEAT,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0D3*/ DEFINE_HANDLER(MSG_MOVE_SET_SWIM_SPEED,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0D4*/ DEFINE_HANDLER(MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT,                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0D5*/ DEFINE_HANDLER(MSG_MOVE_SET_SWIM_BACK_SPEED,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0D6*/ DEFINE_HANDLER(MSG_MOVE_SET_ALL_SPEED_CHEAT,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0D7*/ DEFINE_HANDLER(MSG_MOVE_SET_TURN_RATE_CHEAT,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0D8*/ DEFINE_HANDLER(MSG_MOVE_SET_TURN_RATE,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0D9*/ DEFINE_HANDLER(MSG_MOVE_TOGGLE_COLLISION_CHEAT,                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0DA*/ DEFINE_HANDLER(MSG_MOVE_SET_FACING,                                                   STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0DB*/ DEFINE_HANDLER(MSG_MOVE_SET_PITCH,                                                    STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0DC*/ DEFINE_HANDLER(MSG_MOVE_WORLDPORT_ACK,                                                STATUS_TRANSFER,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMoveWorldportAckOpcode             );
    /*0x0DD*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MONSTER_MOVE,                                       STATUS_NEVER);
    /*0x0DE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_WATER_WALK,                                    STATUS_NEVER);
    /*0x0DF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_LAND_WALK,                                     STATUS_NEVER);
    /*0x0E0*/ DEFINE_HANDLER(CMSG_MOVE_CHARM_PORT_CHEAT,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0E1*/ DEFINE_HANDLER(CMSG_MOVE_SET_RAW_POSITION,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0E2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_RUN_SPEED_CHANGE,                             STATUS_NEVER);
    /*0x0E3*/ DEFINE_HANDLER(CMSG_FORCE_RUN_SPEED_CHANGE_ACK,                                       STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleForceSpeedChangeAck                );
    /*0x0E4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_RUN_BACK_SPEED_CHANGE,                        STATUS_NEVER);
    /*0x0E5*/ DEFINE_HANDLER(CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK,                                  STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleForceSpeedChangeAck                );
    /*0x0E6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_SWIM_SPEED_CHANGE,                            STATUS_NEVER);
    /*0x0E7*/ DEFINE_HANDLER(CMSG_FORCE_SWIM_SPEED_CHANGE_ACK,                                      STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleForceSpeedChangeAck                );
    /*0x0E8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_MOVE_ROOT,                                    STATUS_NEVER);
    /*0x0E9*/ DEFINE_HANDLER(CMSG_FORCE_MOVE_ROOT_ACK,                                              STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMoveRootAck                        );
    /*0x0EA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_MOVE_UNROOT,                                  STATUS_NEVER);
    /*0x0EB*/ DEFINE_HANDLER(CMSG_FORCE_MOVE_UNROOT_ACK,                                            STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMoveUnRootAck                      );
    /*0x0EC*/ DEFINE_HANDLER(MSG_MOVE_ROOT,                                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0ED*/ DEFINE_HANDLER(MSG_MOVE_UNROOT,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0EE*/ DEFINE_HANDLER(MSG_MOVE_HEARTBEAT,                                                    STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x0EF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_KNOCK_BACK,                                    STATUS_NEVER);
    /*0x0F0*/ DEFINE_HANDLER(CMSG_MOVE_KNOCK_BACK_ACK,                                              STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMoveKnockBackAck                   );
    /*0x0F1*/ DEFINE_HANDLER(MSG_MOVE_KNOCK_BACK,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0F2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_FEATHER_FALL,                                  STATUS_NEVER);
    /*0x0F3*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_NORMAL_FALL,                                   STATUS_NEVER);
    /*0x0F4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_SET_HOVER,                                     STATUS_NEVER);
    /*0x0F5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_UNSET_HOVER,                                   STATUS_NEVER);
    /*0x0F6*/ DEFINE_HANDLER(CMSG_MOVE_HOVER_ACK,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMoveHoverAck                       );
    /*0x0F7*/ DEFINE_SERVER_OPCODE_HANDLER(MSG_MOVE_HOVER,                                          STATUS_NEVER);
    /*0x0F8*/ DEFINE_HANDLER(CMSG_TRIGGER_CINEMATIC_CHEAT,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0F9*/ DEFINE_HANDLER(CMSG_OPENING_CINEMATIC,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x0FA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TRIGGER_CINEMATIC,                                  STATUS_NEVER);
    /*0x0FB*/ DEFINE_HANDLER(CMSG_NEXT_CINEMATIC_CAMERA,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleNextCinematicCamera                );
    /*0x0FC*/ DEFINE_HANDLER(CMSG_COMPLETE_CINEMATIC,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCompleteCinematic                  );
    /*0x0FD*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TUTORIAL_FLAGS,                                     STATUS_NEVER);
    /*0x0FE*/ DEFINE_HANDLER(CMSG_TUTORIAL_FLAG,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleTutorialFlag                       );
    /*0x0FF*/ DEFINE_HANDLER(CMSG_TUTORIAL_CLEAR,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleTutorialClear                      );
    /*0x100*/ DEFINE_HANDLER(CMSG_TUTORIAL_RESET,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleTutorialReset                      );
    /*0x101*/ DEFINE_HANDLER(CMSG_STANDSTATECHANGE,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleStandStateChangeOpcode             );
    /*0x102*/ DEFINE_HANDLER(CMSG_EMOTE,                                                            STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleEmoteOpcode                        );
    /*0x103*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_EMOTE,                                              STATUS_NEVER);
    /*0x104*/ DEFINE_HANDLER(CMSG_TEXT_EMOTE,                                                       STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleTextEmoteOpcode                    );
    /*0x105*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TEXT_EMOTE,                                         STATUS_NEVER);
    /*0x106*/ DEFINE_HANDLER(CMSG_AUTOEQUIP_GROUND_ITEM,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x107*/ DEFINE_HANDLER(CMSG_AUTOSTORE_GROUND_ITEM,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x108*/ DEFINE_HANDLER(CMSG_AUTOSTORE_LOOT_ITEM,                                              STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleAutostoreLootItemOpcode            );
    /*0x109*/ DEFINE_HANDLER(CMSG_STORE_LOOT_IN_SLOT,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x10A*/ DEFINE_HANDLER(CMSG_AUTOEQUIP_ITEM,                                                   STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleAutoEquipItemOpcode                );
    /*0x10B*/ DEFINE_HANDLER(CMSG_AUTOSTORE_BAG_ITEM,                                               STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleAutoStoreBagItemOpcode             );
    /*0x10C*/ DEFINE_HANDLER(CMSG_SWAP_ITEM,                                                        STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleSwapItem                           );
    /*0x10D*/ DEFINE_HANDLER(CMSG_SWAP_INV_ITEM,                                                    STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleSwapInvItemOpcode                  );
    /*0x10E*/ DEFINE_HANDLER(CMSG_SPLIT_ITEM,                                                       STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleSplitItemOpcode                    );
    /*0x10F*/ DEFINE_HANDLER(CMSG_AUTOEQUIP_ITEM_SLOT,                                              STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleAutoEquipItemSlotOpcode            );
    /*0x110*/ DEFINE_HANDLER(CMSG_UNCLAIM_LICENSE,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x111*/ DEFINE_HANDLER(CMSG_DESTROYITEM,                                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleDestroyItemOpcode                  );
    /*0x112*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INVENTORY_CHANGE_FAILURE,                           STATUS_NEVER);
    /*0x113*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_OPEN_CONTAINER,                                     STATUS_NEVER);
    /*0x114*/ DEFINE_HANDLER(CMSG_INSPECT,                                                          STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleInspectOpcode                      );
    /*0x115*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INSPECT_RESULTS_UPDATE,                             STATUS_NEVER);
    /*0x116*/ DEFINE_HANDLER(CMSG_INITIATE_TRADE,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleInitiateTradeOpcode                );
    /*0x117*/ DEFINE_HANDLER(CMSG_BEGIN_TRADE,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBeginTradeOpcode                   );
    /*0x118*/ DEFINE_HANDLER(CMSG_BUSY_TRADE,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBusyTradeOpcode                    );
    /*0x119*/ DEFINE_HANDLER(CMSG_IGNORE_TRADE,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleIgnoreTradeOpcode                  );
    /*0x11A*/ DEFINE_HANDLER(CMSG_ACCEPT_TRADE,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAcceptTradeOpcode                  );
    /*0x11B*/ DEFINE_HANDLER(CMSG_UNACCEPT_TRADE,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleUnacceptTradeOpcode                );
    /*0x11C*/ DEFINE_HANDLER(CMSG_CANCEL_TRADE,                                                     STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCancelTradeOpcode);
    /*0x11D*/ DEFINE_HANDLER(CMSG_SET_TRADE_ITEM,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetTradeItemOpcode                 );
    /*0x11E*/ DEFINE_HANDLER(CMSG_CLEAR_TRADE_ITEM,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleClearTradeItemOpcode               );
    /*0x11F*/ DEFINE_HANDLER(CMSG_SET_TRADE_GOLD,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetTradeGoldOpcode                 );
    /*0x120*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TRADE_STATUS,                                       STATUS_NEVER);
    /*0x121*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TRADE_STATUS_EXTENDED,                              STATUS_NEVER);
    /*0x122*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INITIALIZE_FACTIONS,                                STATUS_NEVER);
    /*0x123*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_FACTION_VISIBLE,                                STATUS_NEVER);
    /*0x124*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_FACTION_STANDING,                               STATUS_NEVER);
    /*0x125*/ DEFINE_HANDLER(CMSG_SET_FACTION_ATWAR,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetFactionAtWar                    );
    /*0x126*/ DEFINE_HANDLER(CMSG_SET_FACTION_CHEAT,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetFactionCheat                    );
    /*0x127*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_PROFICIENCY,                                    STATUS_NEVER);
    /*0x128*/ DEFINE_HANDLER(CMSG_SET_ACTION_BUTTON,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetActionButtonOpcode              );
    /*0x129*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ACTION_BUTTONS,                                     STATUS_NEVER);
    /*0x12A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INITIAL_SPELLS,                                     STATUS_NEVER);
    /*0x12B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LEARNED_SPELL,                                      STATUS_NEVER);
    /*0x12C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SUPERCEDED_SPELL,                                   STATUS_NEVER);
    /*0x12D*/ DEFINE_HANDLER(CMSG_NEW_SPELL_SLOT,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x12E*/ DEFINE_HANDLER(CMSG_CAST_SPELL,                                                       STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleCastSpellOpcode                    );
    /*0x12F*/ DEFINE_HANDLER(CMSG_CANCEL_CAST,                                                      STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleCancelCastOpcode                   );
    /*0x130*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CAST_FAILED,                                        STATUS_NEVER);
    /*0x131*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELL_START,                                        STATUS_NEVER);
    /*0x132*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELL_GO,                                           STATUS_NEVER);
    /*0x133*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELL_FAILURE,                                      STATUS_NEVER);
    /*0x134*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELL_COOLDOWN,                                     STATUS_NEVER);
    /*0x135*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COOLDOWN_EVENT,                                     STATUS_NEVER);
    /*0x136*/ DEFINE_HANDLER(CMSG_CANCEL_AURA,                                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleCancelAuraOpcode                   );
    /*0x137*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_EQUIPMENT_SET_SAVED,                                STATUS_NEVER);
    /*0x138*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_CAST_FAILED,                                    STATUS_NEVER);
    /*0x139*/ DEFINE_HANDLER(MSG_CHANNEL_START,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x13A*/ DEFINE_HANDLER(MSG_CHANNEL_UPDATE,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x13B*/ DEFINE_HANDLER(CMSG_CANCEL_CHANNELLING,                                               STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleCancelChanneling                   );
    /*0x13C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AI_REACTION,                                        STATUS_NEVER);
    /*0x13D*/ DEFINE_HANDLER(CMSG_SET_SELECTION,                                                    STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleSetSelectionOpcode                 );
    /*0x13E*/ DEFINE_HANDLER(CMSG_DELETEEQUIPMENT_SET,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleEquipmentSetDelete                 );
    /*0x13F*/ DEFINE_HANDLER(CMSG_INSTANCE_LOCK_RESPONSE,                                           STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleInstanceLockResponse               );
    /*0x140*/ DEFINE_HANDLER(CMSG_DEBUG_PASSIVE_AURA,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x141*/ DEFINE_HANDLER(CMSG_ATTACKSWING,                                                      STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleAttackSwingOpcode                  );
    /*0x142*/ DEFINE_HANDLER(CMSG_ATTACKSTOP,                                                       STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleAttackStopOpcode                   );
    /*0x143*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ATTACKSTART,                                        STATUS_NEVER);
    /*0x144*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ATTACKSTOP,                                         STATUS_NEVER);
    /*0x145*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ATTACKSWING_NOTINRANGE,                             STATUS_NEVER);
    /*0x146*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ATTACKSWING_BADFACING,                              STATUS_NEVER);
    /*0x147*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INSTANCE_LOCK_WARNING_QUERY,                        STATUS_NEVER);
    /*0x148*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ATTACKSWING_DEADTARGET,                             STATUS_NEVER);
    /*0x149*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ATTACKSWING_CANT_ATTACK,                            STATUS_NEVER);
    /*0x14A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ATTACKERSTATEUPDATE,                                STATUS_NEVER);
    /*0x14B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEFIELD_PORT_DENIED,                            STATUS_NEVER);
    /*0x14C*/ DEFINE_HANDLER(CMSG_PERFORM_ACTION_SET,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x14D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RESUME_CAST_BAR,                                    STATUS_NEVER);
    /*0x14E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CANCEL_COMBAT,                                      STATUS_NEVER);
    /*0x14F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLBREAKLOG,                                      STATUS_NEVER);
    /*0x150*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLHEALLOG,                                       STATUS_NEVER);
    /*0x151*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLENERGIZELOG,                                   STATUS_NEVER);
    /*0x152*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BREAK_TARGET,                                       STATUS_NEVER);
    /*0x153*/ DEFINE_HANDLER(CMSG_SAVE_PLAYER,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x154*/ DEFINE_HANDLER(CMSG_SETDEATHBINDPOINT,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x155*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BINDPOINTUPDATE,                                    STATUS_NEVER);
    /*0x156*/ DEFINE_HANDLER(CMSG_GETDEATHBINDZONE,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x157*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BINDZONEREPLY,                                      STATUS_NEVER);
    /*0x158*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAYERBOUND,                                        STATUS_NEVER);
    /*0x159*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CLIENT_CONTROL_UPDATE,                              STATUS_NEVER);
    /*0x15A*/ DEFINE_HANDLER(CMSG_REPOP_REQUEST,                                                    STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleRepopRequestOpcode                 );
    /*0x15B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RESURRECT_REQUEST,                                  STATUS_NEVER);
    /*0x15C*/ DEFINE_HANDLER(CMSG_RESURRECT_RESPONSE,                                               STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleResurrectResponseOpcode            );
    /*0x15D*/ DEFINE_HANDLER(CMSG_LOOT,                                                             STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLootOpcode                         );
    /*0x15E*/ DEFINE_HANDLER(CMSG_LOOT_MONEY,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLootMoneyOpcode                    );
    /*0x15F*/ DEFINE_HANDLER(CMSG_LOOT_RELEASE,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLootReleaseOpcode                  );
    /*0x160*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_RESPONSE,                                      STATUS_NEVER);
    /*0x161*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_RELEASE_RESPONSE,                              STATUS_NEVER);
    /*0x162*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_REMOVED,                                       STATUS_NEVER);
    /*0x163*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_MONEY_NOTIFY,                                  STATUS_NEVER);
    /*0x164*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_ITEM_NOTIFY,                                   STATUS_NEVER);
    /*0x165*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_CLEAR_MONEY,                                   STATUS_NEVER);
    /*0x166*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ITEM_PUSH_RESULT,                                   STATUS_NEVER);
    /*0x167*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DUEL_REQUESTED,                                     STATUS_NEVER);
    /*0x168*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DUEL_OUTOFBOUNDS,                                   STATUS_NEVER);
    /*0x169*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DUEL_INBOUNDS,                                      STATUS_NEVER);
    /*0x16A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DUEL_COMPLETE,                                      STATUS_NEVER);
    /*0x16B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DUEL_WINNER,                                        STATUS_NEVER);
    /*0x16C*/ DEFINE_HANDLER(CMSG_DUEL_ACCEPTED,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleDuelAcceptedOpcode                 );
    /*0x16D*/ DEFINE_HANDLER(CMSG_DUEL_CANCELLED,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleDuelCancelledOpcode                );
    /*0x16E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOUNTRESULT,                                        STATUS_NEVER);
    /*0x16F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DISMOUNTRESULT,                                     STATUS_NEVER);
    /*0x170*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_REMOVED_FROM_PVP_QUEUE,                             STATUS_NEVER);
    /*0x171*/ DEFINE_HANDLER(CMSG_MOUNTSPECIAL_ANIM,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMountSpecialAnimOpcode             );
    /*0x172*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOUNTSPECIAL_ANIM,                                  STATUS_NEVER);
    /*0x173*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_TAME_FAILURE,                                   STATUS_NEVER);
    /*0x174*/ DEFINE_HANDLER(CMSG_PET_SET_ACTION,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandlePetSetAction                       );
    /*0x175*/ DEFINE_HANDLER(CMSG_PET_ACTION,                                                       STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandlePetAction                          );
    /*0x176*/ DEFINE_HANDLER(CMSG_PET_ABANDON,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandlePetAbandon                         );
    /*0x177*/ DEFINE_HANDLER(CMSG_PET_RENAME,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandlePetRename                          );
    /*0x178*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_NAME_INVALID,                                   STATUS_NEVER);
    /*0x179*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_SPELLS,                                         STATUS_NEVER);
    /*0x17A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_MODE,                                           STATUS_NEVER);
    /*0x17B*/ DEFINE_HANDLER(CMSG_GOSSIP_HELLO,                                                     STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleGossipHelloOpcode                  );
    /*0x17C*/ DEFINE_HANDLER(CMSG_GOSSIP_SELECT_OPTION,                                             STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGossipSelectOptionOpcode           );
    /*0x17D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GOSSIP_MESSAGE,                                     STATUS_NEVER);
    /*0x17E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GOSSIP_COMPLETE,                                    STATUS_NEVER);
    /*0x17F*/ DEFINE_HANDLER(CMSG_NPC_TEXT_QUERY,                                                   STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleNpcTextQueryOpcode                 );
    /*0x180*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_NPC_TEXT_UPDATE,                                    STATUS_NEVER);
    /*0x181*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_NPC_WONT_TALK,                                      STATUS_NEVER);
    /*0x182*/ DEFINE_HANDLER(CMSG_QUESTGIVER_STATUS_QUERY,                                          STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleQuestgiverStatusQueryOpcode        );
    /*0x183*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTGIVER_STATUS,                                  STATUS_NEVER);
    /*0x184*/ DEFINE_HANDLER(CMSG_QUESTGIVER_HELLO,                                                 STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestgiverHelloOpcode              );
    /*0x185*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTGIVER_QUEST_LIST,                              STATUS_NEVER);
    /*0x186*/ DEFINE_HANDLER(CMSG_QUESTGIVER_QUERY_QUEST,                                           STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestgiverQueryQuestOpcode         );
    /*0x187*/ DEFINE_HANDLER(CMSG_QUESTGIVER_QUEST_AUTOLAUNCH,                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestgiverQuestAutoLaunch          );
    /*0x188*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTGIVER_QUEST_DETAILS,                           STATUS_NEVER);
    /*0x189*/ DEFINE_HANDLER(CMSG_QUESTGIVER_ACCEPT_QUEST,                                          STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestgiverAcceptQuestOpcode        );
    /*0x18A*/ DEFINE_HANDLER(CMSG_QUESTGIVER_COMPLETE_QUEST,                                        STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestgiverCompleteQuest            );
    /*0x18B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTGIVER_REQUEST_ITEMS,                           STATUS_NEVER);
    /*0x18C*/ DEFINE_HANDLER(CMSG_QUESTGIVER_REQUEST_REWARD,                                        STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestgiverRequestRewardOpcode      );
    /*0x18D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTGIVER_OFFER_REWARD,                            STATUS_NEVER);
    /*0x18E*/ DEFINE_HANDLER(CMSG_QUESTGIVER_CHOOSE_REWARD,                                         STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestgiverChooseRewardOpcode       );
    /*0x18F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTGIVER_QUEST_INVALID,                           STATUS_NEVER);
    /*0x190*/ DEFINE_HANDLER(CMSG_QUESTGIVER_CANCEL,                                                STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestgiverCancel                   );
    /*0x191*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTGIVER_QUEST_COMPLETE,                          STATUS_NEVER);
    /*0x192*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTGIVER_QUEST_FAILED,                            STATUS_NEVER);
    /*0x193*/ DEFINE_HANDLER(CMSG_QUESTLOG_SWAP_QUEST,                                              STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestLogSwapQuest                  );
    /*0x194*/ DEFINE_HANDLER(CMSG_QUESTLOG_REMOVE_QUEST,                                            STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestLogRemoveQuest                );
    /*0x195*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTLOG_FULL,                                      STATUS_NEVER);
    /*0x196*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTUPDATE_FAILED,                                 STATUS_NEVER);
    /*0x197*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTUPDATE_FAILEDTIMER,                            STATUS_NEVER);
    /*0x198*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTUPDATE_COMPLETE,                               STATUS_NEVER);
    /*0x199*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTUPDATE_ADD_KILL,                               STATUS_NEVER);
    /*0x19A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTUPDATE_ADD_ITEM,                               STATUS_NEVER);
    /*0x19B*/ DEFINE_HANDLER(CMSG_QUEST_CONFIRM_ACCEPT,                                             STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleQuestConfirmAccept                 );
    /*0x19C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUEST_CONFIRM_ACCEPT,                               STATUS_NEVER);
    /*0x19D*/ DEFINE_HANDLER(CMSG_PUSHQUESTTOPARTY,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandlePushQuestToParty                   );
    /*0x19E*/ DEFINE_HANDLER(CMSG_LIST_INVENTORY,                                                   STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleListInventoryOpcode                );
    /*0x19F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LIST_INVENTORY,                                     STATUS_NEVER);
    /*0x1A0*/ DEFINE_HANDLER(CMSG_SELL_ITEM,                                                        STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleSellItemOpcode                     );
    /*0x1A1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SELL_ITEM,                                          STATUS_NEVER);
    /*0x1A2*/ DEFINE_HANDLER(CMSG_BUY_ITEM,                                                         STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleBuyItemOpcode                      );
    /*0x1A3*/ DEFINE_HANDLER(CMSG_BUY_ITEM_IN_SLOT,                                                 STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleBuyItemInSlotOpcode                );
    /*0x1A4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BUY_ITEM,                                           STATUS_NEVER);
    /*0x1A5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BUY_FAILED,                                         STATUS_NEVER);
    /*0x1A6*/ DEFINE_HANDLER(CMSG_TAXICLEARALLNODES,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1A7*/ DEFINE_HANDLER(CMSG_TAXIENABLEALLNODES,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1A8*/ DEFINE_HANDLER(CMSG_TAXISHOWNODES,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1A9*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SHOWTAXINODES,                                      STATUS_NEVER);
    /*0x1AA*/ DEFINE_HANDLER(CMSG_TAXINODE_STATUS_QUERY,                                            STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleTaxiNodeStatusQueryOpcode          );
    /*0x1AB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TAXINODE_STATUS,                                    STATUS_NEVER);
    /*0x1AC*/ DEFINE_HANDLER(CMSG_TAXIQUERYAVAILABLENODES,                                          STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleTaxiQueryAvailableNodes            );
    /*0x1AD*/ DEFINE_HANDLER(CMSG_ACTIVATETAXI,                                                     STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleActivateTaxiOpcode                 );
    /*0x1AE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ACTIVATETAXIREPLY,                                  STATUS_NEVER);
    /*0x1AF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_NEW_TAXI_PATH,                                      STATUS_NEVER);
    /*0x1B0*/ DEFINE_HANDLER(CMSG_TRAINER_LIST,                                                     STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleTrainerListOpcode                  );
    /*0x1B1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TRAINER_LIST,                                       STATUS_NEVER);
    /*0x1B2*/ DEFINE_HANDLER(CMSG_TRAINER_BUY_SPELL,                                                STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleTrainerBuySpellOpcode              );
    /*0x1B3*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TRAINER_BUY_SUCCEEDED,                              STATUS_NEVER);
    /*0x1B4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TRAINER_BUY_FAILED,                                 STATUS_NEVER);
    /*0x1B5*/ DEFINE_HANDLER(CMSG_BINDER_ACTIVATE,                                                  STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleBinderActivateOpcode               );
    /*0x1B6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAYERBINDERROR,                                    STATUS_NEVER);
    /*0x1B7*/ DEFINE_HANDLER(CMSG_BANKER_ACTIVATE,                                                  STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleBankerActivateOpcode               );
    /*0x1B8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SHOW_BANK,                                          STATUS_NEVER);
    /*0x1B9*/ DEFINE_HANDLER(CMSG_BUY_BANK_SLOT,                                                    STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleBuyBankSlotOpcode                  );
    /*0x1BA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BUY_BANK_SLOT_RESULT,                               STATUS_NEVER);
    /*0x1BB*/ DEFINE_HANDLER(CMSG_PETITION_SHOWLIST,                                                STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandlePetitionShowListOpcode             );
    /*0x1BC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PETITION_SHOWLIST,                                  STATUS_NEVER);
    /*0x1BD*/ DEFINE_HANDLER(CMSG_PETITION_BUY,                                                     STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandlePetitionBuyOpcode                  );
    /*0x1BE*/ DEFINE_HANDLER(CMSG_PETITION_SHOW_SIGNATURES,                                         STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandlePetitionShowSignOpcode             );
    /*0x1BF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PETITION_SHOW_SIGNATURES,                           STATUS_NEVER);
    /*0x1C0*/ DEFINE_HANDLER(CMSG_PETITION_SIGN,                                                    STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandlePetitionSignOpcode                 );
    /*0x1C1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PETITION_SIGN_RESULTS,                              STATUS_NEVER);
    /*0x1C2*/ DEFINE_HANDLER(MSG_PETITION_DECLINE,                                                  STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandlePetitionDeclineOpcode              );
    /*0x1C3*/ DEFINE_HANDLER(CMSG_OFFER_PETITION,                                                   STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleOfferPetitionOpcode                );
    /*0x1C4*/ DEFINE_HANDLER(CMSG_TURN_IN_PETITION,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleTurnInPetitionOpcode               );
    /*0x1C5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TURN_IN_PETITION_RESULTS,                           STATUS_NEVER);
    /*0x1C6*/ DEFINE_HANDLER(CMSG_PETITION_QUERY,                                                   STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandlePetitionQueryOpcode                );
    /*0x1C7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PETITION_QUERY_RESPONSE,                            STATUS_NEVER);
    /*0x1C8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FISH_NOT_HOOKED,                                    STATUS_NEVER);
    /*0x1C9*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FISH_ESCAPED,                                       STATUS_NEVER);
    /*0x1CA*/ DEFINE_HANDLER(CMSG_BUG,                                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBugOpcode                          );
    /*0x1CB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_NOTIFICATION,                                       STATUS_NEVER);
    /*0x1CC*/ DEFINE_HANDLER(CMSG_PLAYED_TIME,                                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandlePlayedTime                         );
    /*0x1CD*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAYED_TIME,                                        STATUS_NEVER);
    /*0x1CE*/ DEFINE_HANDLER(CMSG_QUERY_TIME,                                                       STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQueryTimeOpcode                    );
    /*0x1CF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUERY_TIME_RESPONSE,                                STATUS_NEVER);
    /*0x1D0*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOG_XPGAIN,                                         STATUS_NEVER);
    /*0x1D1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AURACASTLOG,                                        STATUS_NEVER);
    /*0x1D2*/ DEFINE_HANDLER(CMSG_RECLAIM_CORPSE,                                                   STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleReclaimCorpseOpcode                );
    /*0x1D3*/ DEFINE_HANDLER(CMSG_WRAP_ITEM,                                                        STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleWrapItemOpcode                     );
    /*0x1D4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LEVELUP_INFO,                                       STATUS_NEVER);
    /*0x1D5*/ DEFINE_HANDLER(MSG_MINIMAP_PING,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMinimapPingOpcode                  );
    /*0x1D6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RESISTLOG,                                          STATUS_NEVER);
    /*0x1D7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ENCHANTMENTLOG,                                     STATUS_NEVER);
    /*0x1D8*/ DEFINE_HANDLER(CMSG_SET_SKILL_CHEAT,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1D9*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_START_MIRROR_TIMER,                                 STATUS_NEVER);
    /*0x1DA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PAUSE_MIRROR_TIMER,                                 STATUS_NEVER);
    /*0x1DB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_STOP_MIRROR_TIMER,                                  STATUS_NEVER);
    /*0x1DC*/ DEFINE_HANDLER(CMSG_PING,                                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_EarlyProccess                     );
    /*0x1DD*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PONG,                                               STATUS_NEVER);
    /*0x1DE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CLEAR_COOLDOWN,                                     STATUS_NEVER);
    /*0x1DF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GAMEOBJECT_PAGETEXT,                                STATUS_NEVER);
    /*0x1E0*/ DEFINE_HANDLER(CMSG_SET_SHEATHED,                                                     STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleSetSheathedOpcode                  );
    /*0x1E1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COOLDOWN_CHEAT,                                     STATUS_NEVER);
    /*0x1E2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELL_DELAYED,                                      STATUS_NEVER);
    /*0x1E3*/ DEFINE_HANDLER(CMSG_QUEST_POI_QUERY,                                                  STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQuestPOIQuery                      );
    /*0x1E4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUEST_POI_QUERY_RESPONSE,                           STATUS_NEVER);
    /*0x1E5*/ DEFINE_HANDLER(CMSG_GHOST,                                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1E6*/ DEFINE_HANDLER(CMSG_GM_INVIS,                                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1E7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INVALID_PROMOTION_CODE,                             STATUS_NEVER);
    /*0x1E8*/ DEFINE_HANDLER(MSG_GM_BIND_OTHER,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1E9*/ DEFINE_HANDLER(MSG_GM_SUMMON,                                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1EA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ITEM_TIME_UPDATE,                                   STATUS_NEVER);
    /*0x1EB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ITEM_ENCHANT_TIME_UPDATE,                           STATUS_NEVER);
    /*0x1EC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUTH_CHALLENGE,                                     STATUS_NEVER);
    /*0x1ED*/ DEFINE_HANDLER(CMSG_AUTH_SESSION,                                                     STATUS_NEVER,      PROCESS_THREADUNSAFE,   &WorldSession::Handle_EarlyProccess                     );
    /*0x1EE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUTH_RESPONSE,                                      STATUS_NEVER);
    /*0x1EF*/ DEFINE_HANDLER(MSG_GM_SHOWLABEL,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1F0*/ DEFINE_HANDLER(CMSG_PET_CAST_SPELL,                                                   STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandlePetCastSpellOpcode                 );
    /*0x1F1*/ DEFINE_HANDLER(MSG_SAVE_GUILD_EMBLEM,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSaveGuildEmblemOpcode              );
    /*0x1F2*/ DEFINE_HANDLER(MSG_TABARDVENDOR_ACTIVATE,                                             STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleTabardVendorActivateOpcode         );
    /*0x1F3*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAY_SPELL_VISUAL,                                  STATUS_NEVER);
    /*0x1F4*/ DEFINE_HANDLER(CMSG_ZONEUPDATE,                                                       STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleZoneUpdateOpcode                   );
    /*0x1F5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PARTYKILLLOG,                                       STATUS_NEVER);
    /*0x1F6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMPRESSED_UPDATE_OBJECT,                           STATUS_NEVER);
    /*0x1F7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAY_SPELL_IMPACT,                                  STATUS_NEVER);
    /*0x1F8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_EXPLORATION_EXPERIENCE,                             STATUS_NEVER);
    /*0x1F9*/ DEFINE_HANDLER(CMSG_GM_SET_SECURITY_GROUP,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1FA*/ DEFINE_HANDLER(CMSG_GM_NUKE,                                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1FB*/ DEFINE_HANDLER(MSG_RANDOM_ROLL,                                                       STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleRandomRollOpcode                   );
    /*0x1FC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ENVIRONMENTAL_DAMAGE_LOG,                           STATUS_NEVER);
    /*0x1FD*/ DEFINE_HANDLER(CMSG_CHANGEPLAYER_DIFFICULTY,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x1FE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RWHOIS,                                             STATUS_NEVER);
    /*0x1FF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_PLAYER_REWARD,                                  STATUS_NEVER);
    /*0x200*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_TELEPORT_DENIED,                                STATUS_NEVER);
    /*0x201*/ DEFINE_HANDLER(CMSG_UNLEARN_SPELL,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x202*/ DEFINE_HANDLER(CMSG_UNLEARN_SKILL,                                                    STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleUnlearnSkillOpcode                 );
    /*0x203*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_REMOVED_SPELL,                                      STATUS_NEVER);
    /*0x204*/ DEFINE_HANDLER(CMSG_DECHARGE,                                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x205*/ DEFINE_HANDLER(CMSG_GMTICKET_CREATE,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGMTicketCreateOpcode               );
    /*0x206*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GMTICKET_CREATE,                                    STATUS_NEVER);
    /*0x207*/ DEFINE_HANDLER(CMSG_GMTICKET_UPDATETEXT,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGMTicketUpdateOpcode               );
    /*0x208*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GMTICKET_UPDATETEXT,                                STATUS_NEVER);
    /*0x209*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ACCOUNT_DATA_TIMES,                                 STATUS_NEVER);
    /*0x20A*/ DEFINE_HANDLER(CMSG_REQUEST_ACCOUNT_DATA,                                             STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleRequestAccountData                 );
    /*0x20B*/ DEFINE_HANDLER(CMSG_UPDATE_ACCOUNT_DATA,                                              STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleUpdateAccountData                  );
    /*0x20C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_UPDATE_ACCOUNT_DATA,                                STATUS_NEVER);
    /*0x20D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CLEAR_FAR_SIGHT_IMMEDIATE,                          STATUS_NEVER);
    /*0x20E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHANGEPLAYER_DIFFICULTY_RESULT,                     STATUS_NEVER);
    /*0x20F*/ DEFINE_HANDLER(CMSG_GM_TEACH,                                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x210*/ DEFINE_HANDLER(CMSG_GM_CREATE_ITEM_TARGET,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x211*/ DEFINE_HANDLER(CMSG_GMTICKET_GETTICKET,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGMTicketGetTicketOpcode            );
    /*0x212*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GMTICKET_GETTICKET,                                 STATUS_NEVER);
    /*0x213*/ DEFINE_HANDLER(CMSG_UNLEARN_TALENTS,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x214*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT,                     STATUS_NEVER);
    /*0x215*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GAMEOBJECT_DESPAWN_ANIM,                            STATUS_NEVER);
    /*0x216*/ DEFINE_HANDLER(MSG_CORPSE_QUERY,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCorpseQueryOpcode                  );
    /*0x217*/ DEFINE_HANDLER(CMSG_GMTICKET_DELETETICKET,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGMTicketDeleteOpcode               );
    /*0x218*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GMTICKET_DELETETICKET,                              STATUS_NEVER);
    /*0x219*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAT_WRONG_FACTION,                                 STATUS_NEVER);
    /*0x21A*/ DEFINE_HANDLER(CMSG_GMTICKET_SYSTEMSTATUS,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGMTicketSystemStatusOpcode         );
    /*0x21B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GMTICKET_SYSTEMSTATUS,                              STATUS_NEVER);
    /*0x21C*/ DEFINE_HANDLER(CMSG_SPIRIT_HEALER_ACTIVATE,                                           STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSpiritHealerActivateOpcode         ); // pussywizard: corpse on other map, GetAreaFlag, this involved vmaps, grids and more
    /*0x21D*/ DEFINE_HANDLER(CMSG_SET_STAT_CHEAT,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x21E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUEST_FORCE_REMOVE,                                 STATUS_NEVER);
    /*0x21F*/ DEFINE_HANDLER(CMSG_SKILL_BUY_STEP,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x220*/ DEFINE_HANDLER(CMSG_SKILL_BUY_RANK,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x221*/ DEFINE_HANDLER(CMSG_XP_CHEAT,                                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x222*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPIRIT_HEALER_CONFIRM,                              STATUS_NEVER);
    /*0x223*/ DEFINE_HANDLER(CMSG_CHARACTER_POINT_CHEAT,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x224*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GOSSIP_POI,                                         STATUS_NEVER);
    /*0x225*/ DEFINE_HANDLER(CMSG_CHAT_IGNORED,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleChatIgnoredOpcode                  );
    /*0x226*/ DEFINE_HANDLER(CMSG_GM_VISION,                                                        STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x227*/ DEFINE_HANDLER(CMSG_SERVER_COMMAND,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x228*/ DEFINE_HANDLER(CMSG_GM_SILENCE,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x229*/ DEFINE_HANDLER(CMSG_GM_REVEALTO,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x22A*/ DEFINE_HANDLER(CMSG_GM_RESURRECT,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x22B*/ DEFINE_HANDLER(CMSG_GM_SUMMONMOB,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x22C*/ DEFINE_HANDLER(CMSG_GM_MOVECORPSE,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x22D*/ DEFINE_HANDLER(CMSG_GM_FREEZE,                                                        STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x22E*/ DEFINE_HANDLER(CMSG_GM_UBERINVIS,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x22F*/ DEFINE_HANDLER(CMSG_GM_REQUEST_PLAYER_INFO,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x230*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GM_PLAYER_INFO,                                     STATUS_NEVER);
    /*0x231*/ DEFINE_HANDLER(CMSG_GUILD_RANK,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildRankOpcode                    );
    /*0x232*/ DEFINE_HANDLER(CMSG_GUILD_ADD_RANK,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildAddRankOpcode                 );
    /*0x233*/ DEFINE_HANDLER(CMSG_GUILD_DEL_RANK,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildDelRankOpcode                 );
    /*0x234*/ DEFINE_HANDLER(CMSG_GUILD_SET_PUBLIC_NOTE,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildSetPublicNoteOpcode           );
    /*0x235*/ DEFINE_HANDLER(CMSG_GUILD_SET_OFFICER_NOTE,                                           STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildSetOfficerNoteOpcode          );
    /*0x236*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOGIN_VERIFY_WORLD,                                 STATUS_NEVER);
    /*0x237*/ DEFINE_HANDLER(CMSG_CLEAR_EXPLORATION,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x238*/ DEFINE_HANDLER(CMSG_SEND_MAIL,                                                        STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSendMail                           );
    /*0x239*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SEND_MAIL_RESULT,                                   STATUS_NEVER);
    /*0x23A*/ DEFINE_HANDLER(CMSG_GET_MAIL_LIST,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGetMailList                        );
    /*0x23B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MAIL_LIST_RESULT,                                   STATUS_NEVER);
    /*0x23C*/ DEFINE_HANDLER(CMSG_BATTLEFIELD_LIST,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBattlefieldListOpcode              );
    /*0x23D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEFIELD_LIST,                                   STATUS_NEVER);
    /*0x23E*/ DEFINE_HANDLER(CMSG_BATTLEFIELD_JOIN,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x23F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_SET_VEHICLE_REC_ID,                           STATUS_NEVER);
    /*0x240*/ DEFINE_HANDLER(CMSG_SET_VEHICLE_REC_ID_ACK,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x241*/ DEFINE_HANDLER(CMSG_TAXICLEARNODE,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x242*/ DEFINE_HANDLER(CMSG_TAXIENABLENODE,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x243*/ DEFINE_HANDLER(CMSG_ITEM_TEXT_QUERY,                                                  STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleItemTextQuery                      );
    /*0x244*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ITEM_TEXT_QUERY_RESPONSE,                           STATUS_NEVER);
    /*0x245*/ DEFINE_HANDLER(CMSG_MAIL_TAKE_MONEY,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMailTakeMoney                      );
    /*0x246*/ DEFINE_HANDLER(CMSG_MAIL_TAKE_ITEM,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMailTakeItem                       );
    /*0x247*/ DEFINE_HANDLER(CMSG_MAIL_MARK_AS_READ,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMailMarkAsRead                     );
    /*0x248*/ DEFINE_HANDLER(CMSG_MAIL_RETURN_TO_SENDER,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMailReturnToSender                 );
    /*0x249*/ DEFINE_HANDLER(CMSG_MAIL_DELETE,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMailDelete                         );
    /*0x24A*/ DEFINE_HANDLER(CMSG_MAIL_CREATE_TEXT_ITEM,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMailCreateTextItem                 );
    /*0x24B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLLOGMISS,                                       STATUS_NEVER);
    /*0x24C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLLOGEXECUTE,                                    STATUS_NEVER);
    /*0x24D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DEBUGAURAPROC,                                      STATUS_NEVER);
    /*0x24E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PERIODICAURALOG,                                    STATUS_NEVER);
    /*0x24F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLDAMAGESHIELD,                                  STATUS_NEVER);
    /*0x250*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLNONMELEEDAMAGELOG,                             STATUS_NEVER);
    /*0x251*/ DEFINE_HANDLER(CMSG_LEARN_TALENT,                                                     STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleLearnTalentOpcode                  );
    /*0x252*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RESURRECT_FAILED,                                   STATUS_NEVER);
    /*0x253*/ DEFINE_HANDLER(CMSG_TOGGLE_PVP,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleTogglePvP                          );
    /*0x254*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ZONE_UNDER_ATTACK,                                  STATUS_NEVER);
    /*0x255*/ DEFINE_HANDLER(MSG_AUCTION_HELLO,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAuctionHelloOpcode                 );
    /*0x256*/ DEFINE_HANDLER(CMSG_AUCTION_SELL_ITEM,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAuctionSellItem                    );
    /*0x257*/ DEFINE_HANDLER(CMSG_AUCTION_REMOVE_ITEM,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAuctionRemoveItem                  );
    /*0x258*/ DEFINE_HANDLER(CMSG_AUCTION_LIST_ITEMS,                                               STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleAuctionListItems                   );
    /*0x259*/ DEFINE_HANDLER(CMSG_AUCTION_LIST_OWNER_ITEMS,                                         STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleAuctionListOwnerItems              );
    /*0x25A*/ DEFINE_HANDLER(CMSG_AUCTION_PLACE_BID,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAuctionPlaceBid                    );
    /*0x25B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUCTION_COMMAND_RESULT,                             STATUS_NEVER);
    /*0x25C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUCTION_LIST_RESULT,                                STATUS_NEVER);
    /*0x25D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUCTION_OWNER_LIST_RESULT,                          STATUS_NEVER);
    /*0x25E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUCTION_BIDDER_NOTIFICATION,                        STATUS_NEVER);
    /*0x25F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUCTION_OWNER_NOTIFICATION,                         STATUS_NEVER);
    /*0x260*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PROCRESIST,                                         STATUS_NEVER);
    /*0x261*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMBAT_EVENT_FAILED,                                STATUS_NEVER);
    /*0x262*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DISPEL_FAILED,                                      STATUS_NEVER);
    /*0x263*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLORDAMAGE_IMMUNE,                               STATUS_NEVER);
    /*0x264*/ DEFINE_HANDLER(CMSG_AUCTION_LIST_BIDDER_ITEMS,                                        STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleAuctionListBidderItems             );
    /*0x265*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUCTION_BIDDER_LIST_RESULT,                         STATUS_NEVER);
    /*0x266*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_FLAT_SPELL_MODIFIER,                            STATUS_NEVER);
    /*0x267*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_PCT_SPELL_MODIFIER,                             STATUS_NEVER);
    /*0x268*/ DEFINE_HANDLER(CMSG_SET_AMMO,                                                         STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleSetAmmoOpcode                      );
    /*0x269*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CORPSE_RECLAIM_DELAY,                               STATUS_NEVER);
    /*0x26A*/ DEFINE_HANDLER(CMSG_SET_ACTIVE_MOVER,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetActiveMoverOpcode               );
    /*0x26B*/ DEFINE_HANDLER(CMSG_PET_CANCEL_AURA,                                                  STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandlePetCancelAuraOpcode                );
    /*0x26C*/ DEFINE_HANDLER(CMSG_PLAYER_AI_CHEAT,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x26D*/ DEFINE_HANDLER(CMSG_CANCEL_AUTO_REPEAT_SPELL,                                         STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleCancelAutoRepeatSpellOpcode        );
    /*0x26E*/ DEFINE_HANDLER(MSG_GM_ACCOUNT_ONLINE,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x26F*/ DEFINE_HANDLER(MSG_LIST_STABLED_PETS,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleListStabledPetsOpcode              );
    /*0x270*/ DEFINE_HANDLER(CMSG_STABLE_PET,                                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleStablePet                          );
    /*0x271*/ DEFINE_HANDLER(CMSG_UNSTABLE_PET,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleUnstablePet                        );
    /*0x272*/ DEFINE_HANDLER(CMSG_BUY_STABLE_SLOT,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBuyStableSlot                      );
    /*0x273*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_STABLE_RESULT,                                      STATUS_NEVER);
    /*0x274*/ DEFINE_HANDLER(CMSG_STABLE_REVIVE_PET,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleStableRevivePet                    );
    /*0x275*/ DEFINE_HANDLER(CMSG_STABLE_SWAP_PET,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleStableSwapPet                      );
    /*0x276*/ DEFINE_HANDLER(MSG_QUEST_PUSH_RESULT,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleQuestPushResult                    );
    /*0x277*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAY_MUSIC,                                         STATUS_NEVER);
    /*0x278*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAY_OBJECT_SOUND,                                  STATUS_NEVER);
    /*0x279*/ DEFINE_HANDLER(CMSG_REQUEST_PET_INFO,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleRequestPetInfo                     );
    /*0x27A*/ DEFINE_HANDLER(CMSG_FAR_SIGHT,                                                        STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleFarSightOpcode                     );
    /*0x27B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLDISPELLOG,                                     STATUS_NEVER);
    /*0x27C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DAMAGE_CALC_LOG,                                    STATUS_NEVER);
    /*0x27D*/ DEFINE_HANDLER(CMSG_ENABLE_DAMAGE_LOG,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x27E*/ DEFINE_HANDLER(CMSG_GROUP_CHANGE_SUB_GROUP,                                           STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupChangeSubGroupOpcode          );
    /*0x27F*/ DEFINE_HANDLER(CMSG_REQUEST_PARTY_MEMBER_STATS,                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleRequestPartyMemberStatsOpcode      );
    /*0x280*/ DEFINE_HANDLER(CMSG_GROUP_SWAP_SUB_GROUP,                                             STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupSwapSubGroupOpcode            );
    /*0x281*/ DEFINE_HANDLER(CMSG_RESET_FACTION_CHEAT,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x282*/ DEFINE_HANDLER(CMSG_AUTOSTORE_BANK_ITEM,                                              STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleAutoStoreBankItemOpcode            );
    /*0x283*/ DEFINE_HANDLER(CMSG_AUTOBANK_ITEM,                                                    STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleAutoBankItemOpcode                 );
    /*0x284*/ DEFINE_HANDLER(MSG_QUERY_NEXT_MAIL_TIME,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleQueryNextMailTime                  );
    /*0x285*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RECEIVED_MAIL,                                      STATUS_NEVER);
    /*0x286*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RAID_GROUP_ONLY,                                    STATUS_NEVER);
    /*0x287*/ DEFINE_HANDLER(CMSG_SET_DURABILITY_CHEAT,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x288*/ DEFINE_HANDLER(CMSG_SET_PVP_RANK_CHEAT,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x289*/ DEFINE_HANDLER(CMSG_ADD_PVP_MEDAL_CHEAT,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x28A*/ DEFINE_HANDLER(CMSG_DEL_PVP_MEDAL_CHEAT,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x28B*/ DEFINE_HANDLER(CMSG_SET_PVP_TITLE,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x28C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PVP_CREDIT,                                         STATUS_NEVER);
    /*0x28D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUCTION_REMOVED_NOTIFICATION,                       STATUS_NEVER);
    /*0x28E*/ DEFINE_HANDLER(CMSG_GROUP_RAID_CONVERT,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupRaidConvertOpcode             );
    /*0x28F*/ DEFINE_HANDLER(CMSG_GROUP_ASSISTANT_LEADER,                                           STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGroupAssistantLeaderOpcode         );
    /*0x290*/ DEFINE_HANDLER(CMSG_BUYBACK_ITEM,                                                     STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleBuybackItem                        );
    /*0x291*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAT_SERVER_MESSAGE,                                STATUS_NEVER);
    /*0x292*/ DEFINE_HANDLER(CMSG_SET_SAVED_INSTANCE_EXTEND,                                        STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetSavedInstanceExtend             );
    /*0x293*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_OFFER_CONTINUE,                                 STATUS_NEVER);
    /*0x294*/ DEFINE_HANDLER(CMSG_TEST_DROP_RATE,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x295*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TEST_DROP_RATE_RESULT,                              STATUS_NEVER);
    /*0x296*/ DEFINE_HANDLER(CMSG_LFG_GET_STATUS,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfgGetStatus                       );
    /*0x297*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SHOW_MAILBOX,                                       STATUS_NEVER);
    /*0x298*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RESET_RANGED_COMBAT_TIMER,                          STATUS_NEVER);
    /*0x299*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAT_NOT_IN_PARTY,                                  STATUS_NEVER);
    /*0x29A*/ DEFINE_SERVER_OPCODE_HANDLER(CMSG_GMTICKETSYSTEM_TOGGLE,                              STATUS_NEVER);
    /*0x29B*/ DEFINE_HANDLER(CMSG_CANCEL_GROWTH_AURA,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCancelGrowthAuraOpcode             );
    /*0x29C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CANCEL_AUTO_REPEAT,                                 STATUS_NEVER);
    /*0x29D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_STANDSTATE_UPDATE,                                  STATUS_NEVER);
    /*0x29E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_ALL_PASSED,                                    STATUS_NEVER);
    /*0x29F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_ROLL_WON,                                      STATUS_NEVER);
    /*0x2A0*/ DEFINE_HANDLER(CMSG_LOOT_ROLL,                                                        STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLootRoll                           );
    /*0x2A1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_START_ROLL,                                    STATUS_NEVER);
    /*0x2A2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_ROLL,                                          STATUS_NEVER);
    /*0x2A3*/ DEFINE_HANDLER(CMSG_LOOT_MASTER_GIVE,                                                 STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleLootMasterGiveOpcode               );
    /*0x2A4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_MASTER_LIST,                                   STATUS_NEVER);
    /*0x2A5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_FORCED_REACTIONS,                               STATUS_NEVER);
    /*0x2A6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELL_FAILED_OTHER,                                 STATUS_NEVER);
    /*0x2A7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GAMEOBJECT_RESET_STATE,                             STATUS_NEVER);
    /*0x2A8*/ DEFINE_HANDLER(CMSG_REPAIR_ITEM,                                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleRepairItemOpcode                   );
    /*0x2A9*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAT_PLAYER_NOT_FOUND,                              STATUS_NEVER);
    /*0x2AA*/ DEFINE_HANDLER(MSG_TALENT_WIPE_CONFIRM,                                               STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleTalentWipeConfirmOpcode            );
    /*0x2AB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SUMMON_REQUEST,                                     STATUS_NEVER);
    /*0x2AC*/ DEFINE_HANDLER(CMSG_SUMMON_RESPONSE,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSummonResponseOpcode               );
    /*0x2AD*/ DEFINE_HANDLER(MSG_DEV_SHOWLABEL,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2AE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MONSTER_MOVE_TRANSPORT,                             STATUS_NEVER);
    /*0x2AF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_BROKEN,                                         STATUS_NEVER);
    /*0x2B0*/ DEFINE_HANDLER(MSG_MOVE_FEATHER_FALL,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2B1*/ DEFINE_HANDLER(MSG_MOVE_WATER_WALK,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2B2*/ DEFINE_HANDLER(CMSG_SERVER_BROADCAST,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2B3*/ DEFINE_HANDLER(CMSG_SELF_RES,                                                         STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleSelfResOpcode                      );
    /*0x2B4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FEIGN_DEATH_RESISTED,                               STATUS_NEVER);
    /*0x2B5*/ DEFINE_HANDLER(CMSG_RUN_SCRIPT,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2B6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SCRIPT_MESSAGE,                                     STATUS_NEVER);
    /*0x2B7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DUEL_COUNTDOWN,                                     STATUS_NEVER);
    /*0x2B8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AREA_TRIGGER_MESSAGE,                               STATUS_NEVER);
    /*0x2B9*/ DEFINE_HANDLER(CMSG_SHOWING_HELM,                                                     STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleShowingHelmOpcode                  );
    /*0x2BA*/ DEFINE_HANDLER(CMSG_SHOWING_CLOAK,                                                    STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleShowingCloakOpcode                 );
    /*0x2BB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_ROLE_CHOSEN,                                    STATUS_NEVER);
    /*0x2BC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAYER_SKINNED,                                     STATUS_NEVER);
    /*0x2BD*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DURABILITY_DAMAGE_DEATH,                            STATUS_NEVER);
    /*0x2BE*/ DEFINE_HANDLER(CMSG_SET_EXPLORATION,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2BF*/ DEFINE_HANDLER(CMSG_SET_ACTIONBAR_TOGGLES,                                            STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleSetActionBarToggles                );
    /*0x2C0*/ DEFINE_HANDLER(UMSG_DELETE_GUILD_CHARTER,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2C1*/ DEFINE_HANDLER(MSG_PETITION_RENAME,                                                   STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandlePetitionRenameOpcode               );
    /*0x2C2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INIT_WORLD_STATES,                                  STATUS_NEVER);
    /*0x2C3*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_UPDATE_WORLD_STATE,                                 STATUS_NEVER);
    /*0x2C4*/ DEFINE_HANDLER(CMSG_ITEM_NAME_QUERY,                                                  STATUS_LOGGEDIN,   PROCESS_INPLACE,     &WorldSession::HandleItemNameQueryOpcode                );
    /*0x2C5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ITEM_NAME_QUERY_RESPONSE,                           STATUS_NEVER);
    /*0x2C6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_ACTION_FEEDBACK,                                STATUS_NEVER);
    /*0x2C7*/ DEFINE_HANDLER(CMSG_CHAR_RENAME,                                                      STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleCharRenameOpcode                   );
    /*0x2C8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAR_RENAME,                                        STATUS_NEVER);
    /*0x2C9*/ DEFINE_HANDLER(CMSG_MOVE_SPLINE_DONE,                                                 STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMoveSplineDoneOpcode               );
    /*0x2CA*/ DEFINE_HANDLER(CMSG_MOVE_FALL_RESET,                                                  STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x2CB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INSTANCE_SAVE_CREATED,                              STATUS_NEVER);
    /*0x2CC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RAID_INSTANCE_INFO,                                 STATUS_NEVER);
    /*0x2CD*/ DEFINE_HANDLER(CMSG_REQUEST_RAID_INFO,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleRequestRaidInfoOpcode              );
    /*0x2CE*/ DEFINE_HANDLER(CMSG_MOVE_TIME_SKIPPED,                                                STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMoveTimeSkippedOpcode              );
    /*0x2CF*/ DEFINE_HANDLER(CMSG_MOVE_FEATHER_FALL_ACK,                                            STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleFeatherFallAck                     );
    /*0x2D0*/ DEFINE_HANDLER(CMSG_MOVE_WATER_WALK_ACK,                                              STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMoveWaterWalkAck                   );
    /*0x2D1*/ DEFINE_HANDLER(CMSG_MOVE_NOT_ACTIVE_MOVER,                                            STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMoveNotActiveMover                 );
    /*0x2D2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAY_SOUND,                                         STATUS_NEVER);
    /*0x2D3*/ DEFINE_HANDLER(CMSG_BATTLEFIELD_STATUS,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBattlefieldStatusOpcode            );
    /*0x2D4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEFIELD_STATUS,                                 STATUS_NEVER);
    /*0x2D5*/ DEFINE_HANDLER(CMSG_BATTLEFIELD_PORT,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBattleFieldPortOpcode              );
    /*0x2D6*/ DEFINE_HANDLER(MSG_INSPECT_HONOR_STATS,                                               STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleInspectHonorStatsOpcode            );
    /*0x2D7*/ DEFINE_HANDLER(CMSG_BATTLEMASTER_HELLO,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBattlemasterHelloOpcode            );
    /*0x2D8*/ DEFINE_HANDLER(CMSG_MOVE_START_SWIM_CHEAT,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2D9*/ DEFINE_HANDLER(CMSG_MOVE_STOP_SWIM_CHEAT,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2DA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_WALK_SPEED_CHANGE,                            STATUS_NEVER);
    /*0x2DB*/ DEFINE_HANDLER(CMSG_FORCE_WALK_SPEED_CHANGE_ACK,                                      STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleForceSpeedChangeAck                );
    /*0x2DC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_SWIM_BACK_SPEED_CHANGE,                       STATUS_NEVER);
    /*0x2DD*/ DEFINE_HANDLER(CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK,                                 STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleForceSpeedChangeAck                );
    /*0x2DE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_TURN_RATE_CHANGE,                             STATUS_NEVER);
    /*0x2DF*/ DEFINE_HANDLER(CMSG_FORCE_TURN_RATE_CHANGE_ACK,                                       STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleForceSpeedChangeAck                );
    /*0x2E0*/ DEFINE_HANDLER(MSG_PVP_LOG_DATA,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandlePVPLogDataOpcode                   );
    /*0x2E1*/ DEFINE_HANDLER(CMSG_LEAVE_BATTLEFIELD,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBattlefieldLeaveOpcode             );
    /*0x2E2*/ DEFINE_HANDLER(CMSG_AREA_SPIRIT_HEALER_QUERY,                                         STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAreaSpiritHealerQueryOpcode        );
    /*0x2E3*/ DEFINE_HANDLER(CMSG_AREA_SPIRIT_HEALER_QUEUE,                                         STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAreaSpiritHealerQueueOpcode        );
    /*0x2E4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AREA_SPIRIT_HEALER_TIME,                            STATUS_NEVER);
    /*0x2E5*/ DEFINE_HANDLER(CMSG_GM_UNTEACH,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2E6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_WARDEN_DATA,                                        STATUS_NEVER);
    /*0x2E7*/ DEFINE_HANDLER(CMSG_WARDEN_DATA,                                                      STATUS_AUTHED,     PROCESS_THREADSAFE,     &WorldSession::HandleWardenDataOpcode                   );
    /*0x2E8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GROUP_JOINED_BATTLEGROUND,                          STATUS_NEVER);
    /*0x2E9*/ DEFINE_HANDLER(MSG_BATTLEGROUND_PLAYER_POSITIONS,                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBattlegroundPlayerPositionsOpcode  );
    /*0x2EA*/ DEFINE_HANDLER(CMSG_PET_STOP_ATTACK,                                                  STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandlePetStopAttack                      );
    /*0x2EB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BINDER_CONFIRM,                                     STATUS_NEVER);
    /*0x2EC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEGROUND_PLAYER_JOINED,                         STATUS_NEVER);
    /*0x2ED*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEGROUND_PLAYER_LEFT,                           STATUS_NEVER);
    /*0x2EE*/ DEFINE_HANDLER(CMSG_BATTLEMASTER_JOIN,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBattlemasterJoinOpcode             );
    /*0x2EF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ADDON_INFO,                                         STATUS_NEVER);
    /*0x2F0*/ DEFINE_HANDLER(CMSG_PET_UNLEARN,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2F1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_UNLEARN_CONFIRM,                                STATUS_NEVER);
    /*0x2F2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PARTY_MEMBER_STATS_FULL,                            STATUS_NEVER);
    /*0x2F3*/ DEFINE_HANDLER(CMSG_PET_SPELL_AUTOCAST,                                               STATUS_LOGGEDIN,   PROCESS_INPLACE,     &WorldSession::HandlePetSpellAutocastOpcode             );
    /*0x2F4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_WEATHER,                                            STATUS_NEVER);
    /*0x2F5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAY_TIME_WARNING,                                  STATUS_NEVER);
    /*0x2F6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MINIGAME_SETUP,                                     STATUS_NEVER);
    /*0x2F7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MINIGAME_STATE,                                     STATUS_NEVER);
    /*0x2F8*/ DEFINE_HANDLER(CMSG_MINIGAME_MOVE,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x2F9*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MINIGAME_MOVE_FAILED,                               STATUS_NEVER);
    /*0x2FA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RAID_INSTANCE_MESSAGE,                              STATUS_NEVER);
    /*0x2FB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMPRESSED_MOVES,                                   STATUS_NEVER);
    /*0x2FC*/ DEFINE_HANDLER(CMSG_GUILD_INFO_TEXT,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildChangeInfoTextOpcode          );
    /*0x2FD*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAT_RESTRICTED,                                    STATUS_NEVER);
    /*0x2FE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_SET_RUN_SPEED,                               STATUS_NEVER);
    /*0x2FF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_SET_RUN_BACK_SPEED,                          STATUS_NEVER);
    /*0x300*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_SET_SWIM_SPEED,                              STATUS_NEVER);
    /*0x301*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_SET_WALK_SPEED,                              STATUS_NEVER);
    /*0x302*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_SET_SWIM_BACK_SPEED,                         STATUS_NEVER);
    /*0x303*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_SET_TURN_RATE,                               STATUS_NEVER);
    /*0x304*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_UNROOT,                                 STATUS_NEVER);
    /*0x305*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_FEATHER_FALL,                           STATUS_NEVER);
    /*0x306*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_NORMAL_FALL,                            STATUS_NEVER);
    /*0x307*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_SET_HOVER,                              STATUS_NEVER);
    /*0x308*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_UNSET_HOVER,                            STATUS_NEVER);
    /*0x309*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_WATER_WALK,                             STATUS_NEVER);
    /*0x30A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_LAND_WALK,                              STATUS_NEVER);
    /*0x30B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_START_SWIM,                             STATUS_NEVER);
    /*0x30C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_STOP_SWIM,                              STATUS_NEVER);
    /*0x30D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_SET_RUN_MODE,                           STATUS_NEVER);
    /*0x30E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_SET_WALK_MODE,                          STATUS_NEVER);
    /*0x30F*/ DEFINE_HANDLER(CMSG_GM_NUKE_ACCOUNT,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x310*/ DEFINE_HANDLER(MSG_GM_DESTROY_CORPSE,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x311*/ DEFINE_HANDLER(CMSG_GM_DESTROY_ONLINE_CORPSE,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x312*/ DEFINE_HANDLER(CMSG_ACTIVATETAXIEXPRESS,                                              STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleActivateTaxiExpressOpcode          );
    /*0x313*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_FACTION_ATWAR,                                  STATUS_NEVER);
    /*0x314*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GAMETIMEBIAS_SET,                                   STATUS_NEVER);
    /*0x315*/ DEFINE_HANDLER(CMSG_DEBUG_ACTIONS_START,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x316*/ DEFINE_HANDLER(CMSG_DEBUG_ACTIONS_STOP,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x317*/ DEFINE_HANDLER(CMSG_SET_FACTION_INACTIVE,                                             STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetFactionInactiveOpcode           );
    /*0x318*/ DEFINE_HANDLER(CMSG_SET_WATCHED_FACTION,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetWatchedFactionOpcode            );
    /*0x319*/ DEFINE_HANDLER(MSG_MOVE_TIME_SKIPPED,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x31A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_ROOT,                                   STATUS_NEVER);
    /*0x31B*/ DEFINE_HANDLER(CMSG_SET_EXPLORATION_ALL,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x31C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INVALIDATE_PLAYER,                                  STATUS_NEVER);
    /*0x31D*/ DEFINE_HANDLER(CMSG_RESET_INSTANCES,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleResetInstancesOpcode               );
    /*0x31E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INSTANCE_RESET,                                     STATUS_NEVER);
    /*0x31F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INSTANCE_RESET_FAILED,                              STATUS_NEVER);
    /*0x320*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_UPDATE_LAST_INSTANCE,                               STATUS_NEVER);
    /*0x321*/ DEFINE_HANDLER(MSG_RAID_TARGET_UPDATE,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleRaidTargetUpdateOpcode             );
    /*0x322*/ DEFINE_HANDLER(MSG_RAID_READY_CHECK,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleRaidReadyCheckOpcode               );
    /*0x323*/ DEFINE_HANDLER(CMSG_LUA_USAGE,                                                        STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x324*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_ACTION_SOUND,                                   STATUS_NEVER);
    /*0x325*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_DISMISS_SOUND,                                  STATUS_NEVER);
    /*0x326*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GHOSTEE_GONE,                                       STATUS_NEVER);
    /*0x327*/ DEFINE_HANDLER(CMSG_GM_UPDATE_TICKET_STATUS,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x328*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GM_TICKET_STATUS_UPDATE,                            STATUS_NEVER);
    /*0x329*/ DEFINE_HANDLER(MSG_SET_DUNGEON_DIFFICULTY,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetDungeonDifficultyOpcode         );
    /*0x32A*/ DEFINE_HANDLER(CMSG_GMSURVEY_SUBMIT,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGMSurveySubmit                     );
    /*0x32B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_UPDATE_INSTANCE_OWNERSHIP,                          STATUS_NEVER);
    /*0x32C*/ DEFINE_HANDLER(CMSG_IGNORE_KNOCKBACK_CHEAT,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x32D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAT_PLAYER_AMBIGUOUS,                              STATUS_NEVER);
    /*0x32E*/ DEFINE_HANDLER(MSG_DELAY_GHOST_TELEPORT,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x32F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLINSTAKILLLOG,                                  STATUS_NEVER);
    /*0x330*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELL_UPDATE_CHAIN_TARGETS,                         STATUS_NEVER);
    /*0x331*/ DEFINE_HANDLER(CMSG_CHAT_FILTERED,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x332*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_EXPECTED_SPAM_RECORDS,                              STATUS_NEVER);
    /*0x333*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELLSTEALLOG,                                      STATUS_NEVER);
    /*0x334*/ DEFINE_HANDLER(CMSG_LOTTERY_QUERY_OBSOLETE,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x335*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOTTERY_QUERY_RESULT_OBSOLETE,                      STATUS_NEVER);
    /*0x336*/ DEFINE_HANDLER(CMSG_BUY_LOTTERY_TICKET_OBSOLETE,                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x337*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOTTERY_RESULT_OBSOLETE,                            STATUS_NEVER);
    /*0x338*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHARACTER_PROFILE,                                  STATUS_NEVER);
    /*0x339*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHARACTER_PROFILE_REALM_CONNECTED,                  STATUS_NEVER);
    /*0x33A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DEFENSE_MESSAGE,                                    STATUS_NEVER);
    /*0x33B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INSTANCE_DIFFICULTY,                                STATUS_NEVER);
    /*0x33C*/ DEFINE_HANDLER(MSG_GM_RESETINSTANCELIMIT,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x33D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOTD,                                               STATUS_NEVER);
    /*0x33E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY,       STATUS_NEVER);
    /*0x33F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_UNSET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY,     STATUS_NEVER);
    /*0x340*/ DEFINE_HANDLER(CMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY_ACK,                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x341*/ DEFINE_HANDLER(MSG_MOVE_START_SWIM_CHEAT,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x342*/ DEFINE_HANDLER(MSG_MOVE_STOP_SWIM_CHEAT,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x343*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_SET_CAN_FLY,                                   STATUS_NEVER);
    /*0x344*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_UNSET_CAN_FLY,                                 STATUS_NEVER);
    /*0x345*/ DEFINE_HANDLER(CMSG_MOVE_SET_CAN_FLY_ACK,                                             STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMoveSetCanFlyAckOpcode             );
    /*0x346*/ DEFINE_HANDLER(CMSG_MOVE_SET_FLY,                                                     STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x347*/ DEFINE_HANDLER(CMSG_SOCKET_GEMS,                                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleSocketOpcode                       );
    /*0x348*/ DEFINE_HANDLER(CMSG_ARENA_TEAM_CREATE,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x349*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ARENA_TEAM_COMMAND_RESULT,                          STATUS_NEVER);
    /*0x34A*/ DEFINE_HANDLER(MSG_MOVE_UPDATE_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY,                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x34B*/ DEFINE_HANDLER(CMSG_ARENA_TEAM_QUERY,                                                 STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleArenaTeamQueryOpcode               );
    /*0x34C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ARENA_TEAM_QUERY_RESPONSE,                          STATUS_NEVER);
    /*0x34D*/ DEFINE_HANDLER(CMSG_ARENA_TEAM_ROSTER,                                                STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleArenaTeamRosterOpcode              );
    /*0x34E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ARENA_TEAM_ROSTER,                                  STATUS_NEVER);
    /*0x34F*/ DEFINE_HANDLER(CMSG_ARENA_TEAM_INVITE,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleArenaTeamInviteOpcode              );
    /*0x350*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ARENA_TEAM_INVITE,                                  STATUS_NEVER);
    /*0x351*/ DEFINE_HANDLER(CMSG_ARENA_TEAM_ACCEPT,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleArenaTeamAcceptOpcode              );
    /*0x352*/ DEFINE_HANDLER(CMSG_ARENA_TEAM_DECLINE,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleArenaTeamDeclineOpcode             );
    /*0x353*/ DEFINE_HANDLER(CMSG_ARENA_TEAM_LEAVE,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleArenaTeamLeaveOpcode               );
    /*0x354*/ DEFINE_HANDLER(CMSG_ARENA_TEAM_REMOVE,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleArenaTeamRemoveOpcode              );
    /*0x355*/ DEFINE_HANDLER(CMSG_ARENA_TEAM_DISBAND,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleArenaTeamDisbandOpcode             );
    /*0x356*/ DEFINE_HANDLER(CMSG_ARENA_TEAM_LEADER,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleArenaTeamLeaderOpcode              );
    /*0x357*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ARENA_TEAM_EVENT,                                   STATUS_NEVER);
    /*0x358*/ DEFINE_HANDLER(CMSG_BATTLEMASTER_JOIN_ARENA,                                          STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBattlemasterJoinArena              );
    /*0x359*/ DEFINE_HANDLER(MSG_MOVE_START_ASCEND,                                                 STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x35A*/ DEFINE_HANDLER(MSG_MOVE_STOP_ASCEND,                                                  STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x35B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ARENA_TEAM_STATS,                                   STATUS_NEVER);
    /*0x35C*/ DEFINE_HANDLER(CMSG_LFG_JOIN,                                                         STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfgJoinOpcode                      );
    /*0x35D*/ DEFINE_HANDLER(CMSG_LFG_LEAVE,                                                        STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfgLeaveOpcode                     );
    /*0x35E*/ DEFINE_HANDLER(CMSG_SEARCH_LFG_JOIN,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfrSearchJoinOpcode                );
    /*0x35F*/ DEFINE_HANDLER(CMSG_SEARCH_LFG_LEAVE,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfrSearchLeaveOpcode               );
    /*0x360*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_UPDATE_LFG_LIST,                                    STATUS_NEVER);
    /*0x361*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_PROPOSAL_UPDATE,                                STATUS_NEVER);
    /*0x362*/ DEFINE_HANDLER(CMSG_LFG_PROPOSAL_RESULT,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfgProposalResultOpcode            );
    /*0x363*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_ROLE_CHECK_UPDATE,                              STATUS_NEVER);
    /*0x364*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_JOIN_RESULT,                                    STATUS_NEVER);
    /*0x365*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_QUEUE_STATUS,                                   STATUS_NEVER);
    /*0x366*/ DEFINE_HANDLER(CMSG_SET_LFG_COMMENT,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfgSetCommentOpcode                );
    /*0x367*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_UPDATE_PLAYER,                                  STATUS_NEVER);
    /*0x368*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_UPDATE_PARTY,                                   STATUS_NEVER);
    /*0x369*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_UPDATE_SEARCH,                                  STATUS_NEVER);
    /*0x36A*/ DEFINE_HANDLER(CMSG_LFG_SET_ROLES,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfgSetRolesOpcode                  );
    /*0x36B*/ DEFINE_HANDLER(CMSG_LFG_SET_NEEDS,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x36C*/ DEFINE_HANDLER(CMSG_LFG_SET_BOOT_VOTE,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfgSetBootVoteOpcode               );
    /*0x36D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_BOOT_PROPOSAL_UPDATE,                           STATUS_NEVER);
    /*0x36E*/ DEFINE_HANDLER(CMSG_LFD_PLAYER_LOCK_INFO_REQUEST,                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfgPlayerLockInfoRequestOpcode     );
    /*0x36F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_PLAYER_INFO,                                    STATUS_NEVER);
    /*0x370*/ DEFINE_HANDLER(CMSG_LFG_TELEPORT,                                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfgTeleportOpcode                  );
    /*0x371*/ DEFINE_HANDLER(CMSG_LFD_PARTY_LOCK_INFO_REQUEST,                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleLfgPartyLockInfoRequestOpcode      );
    /*0x372*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_PARTY_INFO,                                     STATUS_NEVER);
    /*0x373*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TITLE_EARNED,                                       STATUS_NEVER);
    /*0x374*/ DEFINE_HANDLER(CMSG_SET_TITLE,                                                        STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleSetTitleOpcode                     );
    /*0x375*/ DEFINE_HANDLER(CMSG_CANCEL_MOUNT_AURA,                                                STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleCancelMountAuraOpcode              );
    /*0x376*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ARENA_ERROR,                                        STATUS_NEVER);
    /*0x377*/ DEFINE_HANDLER(MSG_INSPECT_ARENA_TEAMS,                                               STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleInspectArenaTeamsOpcode            );
    /*0x378*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DEATH_RELEASE_LOC,                                  STATUS_NEVER);
    /*0x379*/ DEFINE_HANDLER(CMSG_CANCEL_TEMP_ENCHANTMENT,                                          STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleCancelTempEnchantmentOpcode        );
    /*0x37A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCED_DEATH_UPDATE,                                STATUS_NEVER);
    /*0x37B*/ DEFINE_HANDLER(CMSG_CHEAT_SET_HONOR_CURRENCY,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x37C*/ DEFINE_HANDLER(CMSG_CHEAT_SET_ARENA_CURRENCY,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x37D*/ DEFINE_HANDLER(MSG_MOVE_SET_FLIGHT_SPEED_CHEAT,                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x37E*/ DEFINE_HANDLER(MSG_MOVE_SET_FLIGHT_SPEED,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x37F*/ DEFINE_HANDLER(MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT,                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x380*/ DEFINE_HANDLER(MSG_MOVE_SET_FLIGHT_BACK_SPEED,                                        STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x381*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_FLIGHT_SPEED_CHANGE,                          STATUS_NEVER);
    /*0x382*/ DEFINE_HANDLER(CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK,                                    STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleForceSpeedChangeAck                );
    /*0x383*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE,                     STATUS_NEVER);
    /*0x384*/ DEFINE_HANDLER(CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK,                               STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleForceSpeedChangeAck                );
    /*0x385*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_SET_FLIGHT_SPEED,                            STATUS_NEVER);
    /*0x386*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_SET_FLIGHT_BACK_SPEED,                       STATUS_NEVER);
    /*0x387*/ DEFINE_HANDLER(CMSG_MAELSTROM_INVALIDATE_CACHE,                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x388*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FLIGHT_SPLINE_SYNC,                                 STATUS_NEVER);
    /*0x389*/ DEFINE_HANDLER(CMSG_SET_TAXI_BENCHMARK_MODE,                                          STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetTaxiBenchmarkOpcode             );
    /*0x38A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_JOINED_BATTLEGROUND_QUEUE,                          STATUS_NEVER);
    /*0x38B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_REALM_SPLIT,                                        STATUS_NEVER);
    /*0x38C*/ DEFINE_HANDLER(CMSG_REALM_SPLIT,                                                      STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleRealmSplitOpcode                   );
    /*0x38D*/ DEFINE_HANDLER(CMSG_MOVE_CHNG_TRANSPORT,                                              STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x38E*/ DEFINE_HANDLER(MSG_PARTY_ASSIGNMENT,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandlePartyAssignmentOpcode              );
    /*0x38F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_OFFER_PETITION_ERROR,                               STATUS_NEVER);
    /*0x390*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TIME_SYNC_REQ,                                      STATUS_NEVER);
    /*0x391*/ DEFINE_HANDLER(CMSG_TIME_SYNC_RESP,                                                   STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleTimeSyncResp                       );
    /*0x392*/ DEFINE_HANDLER(CMSG_SEND_LOCAL_EVENT,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x393*/ DEFINE_HANDLER(CMSG_SEND_GENERAL_TRIGGER,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x394*/ DEFINE_HANDLER(CMSG_SEND_COMBAT_TRIGGER,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x395*/ DEFINE_HANDLER(CMSG_MAELSTROM_GM_SENT_MAIL,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x396*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RESET_FAILED_NOTIFY,                                STATUS_NEVER);
    /*0x397*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_REAL_GROUP_UPDATE,                                  STATUS_NEVER);
    /*0x398*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LFG_DISABLED,                                       STATUS_NEVER);
    /*0x399*/ DEFINE_HANDLER(CMSG_ACTIVE_PVP_CHEAT,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x39A*/ DEFINE_HANDLER(CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY,                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x39B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE,               STATUS_NEVER);
    /*0x39C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE,    STATUS_NEVER);
    /*0x39D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_UPDATE_COMBO_POINTS,                                STATUS_NEVER);
    /*0x39E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_VOICE_SESSION_ROSTER_UPDATE,                        STATUS_NEVER);
    /*0x39F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_VOICE_SESSION_LEAVE,                                STATUS_NEVER);
    /*0x3A0*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_VOICE_SESSION_ADJUST_PRIORITY,                      STATUS_NEVER);
    /*0x3A1*/ DEFINE_HANDLER(CMSG_VOICE_SET_TALKER_MUTED_REQUEST,                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3A2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_VOICE_SET_TALKER_MUTED,                             STATUS_NEVER);
    /*0x3A3*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE,                      STATUS_NEVER);
    /*0x3A4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_EXTRA_AURA_INFO_OBSOLETE,                       STATUS_NEVER);
    /*0x3A5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE,           STATUS_NEVER);
    /*0x3A6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE,                     STATUS_NEVER);
    /*0x3A7*/ DEFINE_HANDLER(MSG_MOVE_START_DESCEND,                                                STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleMovementOpcodes                    );
    /*0x3A8*/ DEFINE_HANDLER(CMSG_IGNORE_REQUIREMENTS_CHEAT,                                        STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3A9*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_IGNORE_REQUIREMENTS_CHEAT,                          STATUS_NEVER);
    /*0x3AA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELL_CHANCE_PROC_LOG,                              STATUS_NEVER);
    /*0x3AB*/ DEFINE_HANDLER(CMSG_MOVE_SET_RUN_SPEED,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3AC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DISMOUNT,                                           STATUS_NEVER);
    /*0x3AD*/ DEFINE_HANDLER(MSG_MOVE_UPDATE_CAN_FLY,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3AE*/ DEFINE_HANDLER(MSG_RAID_READY_CHECK_CONFIRM,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3AF*/ DEFINE_HANDLER(CMSG_VOICE_SESSION_ENABLE,                                             STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleVoiceSessionEnableOpcode           );
    /*0x3B0*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_VOICE_SESSION_ENABLE,                               STATUS_NEVER);
    /*0x3B1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_VOICE_PARENTAL_CONTROLS,                            STATUS_NEVER);
    /*0x3B2*/ DEFINE_HANDLER(CMSG_GM_WHISPER,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3B3*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GM_MESSAGECHAT,                                     STATUS_NEVER);
    /*0x3B4*/ DEFINE_HANDLER(MSG_GM_GEARRATING,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3B5*/ DEFINE_HANDLER(CMSG_COMMENTATOR_ENABLE,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3B6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMMENTATOR_STATE_CHANGED,                          STATUS_NEVER);
    /*0x3B7*/ DEFINE_HANDLER(CMSG_COMMENTATOR_GET_MAP_INFO,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3B8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMMENTATOR_MAP_INFO,                               STATUS_NEVER);
    /*0x3B9*/ DEFINE_HANDLER(CMSG_COMMENTATOR_GET_PLAYER_INFO,                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3BA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMMENTATOR_GET_PLAYER_INFO,                        STATUS_NEVER);
    /*0x3BB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMMENTATOR_PLAYER_INFO,                            STATUS_NEVER);
    /*0x3BC*/ DEFINE_HANDLER(CMSG_COMMENTATOR_ENTER_INSTANCE,                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3BD*/ DEFINE_HANDLER(CMSG_COMMENTATOR_EXIT_INSTANCE,                                        STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3BE*/ DEFINE_HANDLER(CMSG_COMMENTATOR_INSTANCE_COMMAND,                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3BF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CLEAR_TARGET,                                       STATUS_NEVER);
    /*0x3C0*/ DEFINE_HANDLER(CMSG_BOT_DETECTED,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3C1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CROSSED_INEBRIATION_THRESHOLD,                      STATUS_NEVER);
    /*0x3C2*/ DEFINE_HANDLER(CMSG_CHEAT_PLAYER_LOGIN,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3C3*/ DEFINE_HANDLER(CMSG_CHEAT_PLAYER_LOOKUP,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3C4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHEAT_PLAYER_LOOKUP,                                STATUS_NEVER);
    /*0x3C5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_KICK_REASON,                                        STATUS_NEVER);
    /*0x3C6*/ DEFINE_HANDLER(MSG_RAID_READY_CHECK_FINISHED,                                         STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleRaidReadyCheckFinishedOpcode       );
    /*0x3C7*/ DEFINE_HANDLER(CMSG_COMPLAIN,                                                         STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleComplainOpcode                     );
    /*0x3C8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMPLAIN_RESULT,                                    STATUS_NEVER);
    /*0x3C9*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FEATURE_SYSTEM_STATUS,                              STATUS_NEVER);
    /*0x3CA*/ DEFINE_HANDLER(CMSG_GM_SHOW_COMPLAINTS,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3CB*/ DEFINE_HANDLER(CMSG_GM_UNSQUELCH,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3CC*/ DEFINE_HANDLER(CMSG_CHANNEL_SILENCE_VOICE,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3CD*/ DEFINE_HANDLER(CMSG_CHANNEL_SILENCE_ALL,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3CE*/ DEFINE_HANDLER(CMSG_CHANNEL_UNSILENCE_VOICE,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3CF*/ DEFINE_HANDLER(CMSG_CHANNEL_UNSILENCE_ALL,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3D0*/ DEFINE_HANDLER(CMSG_TARGET_CAST,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3D1*/ DEFINE_HANDLER(CMSG_TARGET_SCRIPT_CAST,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3D2*/ DEFINE_HANDLER(CMSG_CHANNEL_DISPLAY_LIST,                                             STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleChannelDisplayListQuery            );
    /*0x3D3*/ DEFINE_HANDLER(CMSG_SET_ACTIVE_VOICE_CHANNEL,                                         STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleSetActiveVoiceChannel              );
    /*0x3D4*/ DEFINE_HANDLER(CMSG_GET_CHANNEL_MEMBER_COUNT,                                         STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleGetChannelMemberCount              );
    /*0x3D5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHANNEL_MEMBER_COUNT,                               STATUS_NEVER);
    /*0x3D6*/ DEFINE_HANDLER(CMSG_CHANNEL_VOICE_ON,                                                 STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleChannelVoiceOnOpcode               );
    /*0x3D7*/ DEFINE_HANDLER(CMSG_CHANNEL_VOICE_OFF,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3D8*/ DEFINE_HANDLER(CMSG_DEBUG_LIST_TARGETS,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3D9*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DEBUG_LIST_TARGETS,                                 STATUS_NEVER);
    /*0x3DA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AVAILABLE_VOICE_CHANNEL,                            STATUS_NEVER);
    /*0x3DB*/ DEFINE_HANDLER(CMSG_ADD_VOICE_IGNORE,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3DC*/ DEFINE_HANDLER(CMSG_DEL_VOICE_IGNORE,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3DD*/ DEFINE_HANDLER(CMSG_PARTY_SILENCE,                                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3DE*/ DEFINE_HANDLER(CMSG_PARTY_UNSILENCE,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3DF*/ DEFINE_HANDLER(MSG_NOTIFY_PARTY_SQUELCH,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3E0*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMSAT_RECONNECT_TRY,                               STATUS_NEVER);
    /*0x3E1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMSAT_DISCONNECT,                                  STATUS_NEVER);
    /*0x3E2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMSAT_CONNECT_FAIL,                                STATUS_NEVER);
    /*0x3E3*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_VOICE_CHAT_STATUS,                                  STATUS_NEVER);
    /*0x3E4*/ DEFINE_HANDLER(CMSG_REPORT_PVP_AFK,                                                   STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleReportPvPAFK                       );
    /*0x3E5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_REPORT_PVP_AFK_RESULT,                              STATUS_NEVER);
    /*0x3E6*/ DEFINE_HANDLER(CMSG_GUILD_BANKER_ACTIVATE,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildBankerActivate                );
    /*0x3E7*/ DEFINE_HANDLER(CMSG_GUILD_BANK_QUERY_TAB,                                             STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildBankQueryTab                  );
    /*0x3E8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GUILD_BANK_LIST,                                    STATUS_NEVER);
    /*0x3E9*/ DEFINE_HANDLER(CMSG_GUILD_BANK_SWAP_ITEMS,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildBankSwapItems                 );
    /*0x3EA*/ DEFINE_HANDLER(CMSG_GUILD_BANK_BUY_TAB,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildBankBuyTab                    );
    /*0x3EB*/ DEFINE_HANDLER(CMSG_GUILD_BANK_UPDATE_TAB,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildBankUpdateTab                 );
    /*0x3EC*/ DEFINE_HANDLER(CMSG_GUILD_BANK_DEPOSIT_MONEY,                                         STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildBankDepositMoney              );
    /*0x3ED*/ DEFINE_HANDLER(CMSG_GUILD_BANK_WITHDRAW_MONEY,                                        STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildBankWithdrawMoney             );
    /*0x3EE*/ DEFINE_HANDLER(MSG_GUILD_BANK_LOG_QUERY,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildBankLogQuery                  );
    /*0x3EF*/ DEFINE_HANDLER(CMSG_SET_CHANNEL_WATCH,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetChannelWatch                    );
    /*0x3F0*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_USERLIST_ADD,                                       STATUS_NEVER);
    /*0x3F1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_USERLIST_REMOVE,                                    STATUS_NEVER);
    /*0x3F2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_USERLIST_UPDATE,                                    STATUS_NEVER);
    /*0x3F3*/ DEFINE_HANDLER(CMSG_CLEAR_CHANNEL_WATCH,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleClearChannelWatch                  );
    /*0x3F4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INSPECT_TALENT,                                     STATUS_NEVER);
    /*0x3F5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GOGOGO_OBSOLETE,                                    STATUS_NEVER);
    /*0x3F6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ECHO_PARTY_SQUELCH,                                 STATUS_NEVER);
    /*0x3F7*/ DEFINE_HANDLER(CMSG_SET_TITLE_SUFFIX,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3F8*/ DEFINE_HANDLER(CMSG_SPELLCLICK,                                                       STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleSpellClick                         );
    /*0x3F9*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_LIST,                                          STATUS_NEVER);
    /*0x3FA*/ DEFINE_HANDLER(CMSG_GM_CHARACTER_RESTORE,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3FB*/ DEFINE_HANDLER(CMSG_GM_CHARACTER_SAVE,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x3FC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_VOICESESSION_FULL,                                  STATUS_NEVER);
    /*0x3FD*/ DEFINE_HANDLER(MSG_GUILD_PERMISSIONS,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildPermissions                   );
    /*0x3FE*/ DEFINE_HANDLER(MSG_GUILD_BANK_MONEY_WITHDRAWN,                                        STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildBankMoneyWithdrawn            );
    /*0x3FF*/ DEFINE_HANDLER(MSG_GUILD_EVENT_LOG_QUERY,                                             STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGuildEventLogQueryOpcode           );
    /*0x400*/ DEFINE_HANDLER(CMSG_MAELSTROM_RENAME_GUILD,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x401*/ DEFINE_HANDLER(CMSG_GET_MIRRORIMAGE_DATA,                                             STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleMirrorImageDataRequest             );
    /*0x402*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MIRRORIMAGE_DATA,                                   STATUS_NEVER);
    /*0x403*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_DISPLAY_UPDATE,                               STATUS_NEVER);
    /*0x404*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPELL_CHANCE_RESIST_PUSHBACK,                       STATUS_NEVER);
    /*0x405*/ DEFINE_HANDLER(CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT,                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x406*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT,                   STATUS_NEVER);
    /*0x407*/ DEFINE_HANDLER(CMSG_KEEP_ALIVE,                                                       STATUS_NEVER,      PROCESS_THREADUNSAFE,   &WorldSession::Handle_EarlyProccess                     );
    /*0x408*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RAID_READY_CHECK_ERROR,                             STATUS_NEVER);
    /*0x409*/ DEFINE_HANDLER(CMSG_OPT_OUT_OF_LOOT,                                                  STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleOptOutOfLootOpcode                 );
    /*0x40A*/ DEFINE_HANDLER(MSG_QUERY_GUILD_BANK_TEXT,                                             STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleQueryGuildBankTabText              );
    /*0x40B*/ DEFINE_HANDLER(CMSG_SET_GUILD_BANK_TEXT,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetGuildBankTabText                );
    /*0x40C*/ DEFINE_HANDLER(CMSG_SET_GRANTABLE_LEVELS,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x40D*/ DEFINE_HANDLER(CMSG_GRANT_LEVEL,                                                      STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGrantLevel                         );
    /*0x40E*/ DEFINE_HANDLER(CMSG_REFER_A_FRIEND,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x40F*/ DEFINE_HANDLER(MSG_GM_CHANGE_ARENA_RATING,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x410*/ DEFINE_HANDLER(CMSG_DECLINE_CHANNEL_INVITE,                                           STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleChannelDeclineInvite               );
    /*0x411*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GROUPACTION_THROTTLED,                              STATUS_NEVER);
    /*0x412*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_OVERRIDE_LIGHT,                                     STATUS_NEVER);
    /*0x413*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TOTEM_CREATED,                                      STATUS_NEVER);
    /*0x414*/ DEFINE_HANDLER(CMSG_TOTEM_DESTROYED,                                                  STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleTotemDestroyed                     );
    /*0x415*/ DEFINE_HANDLER(CMSG_EXPIRE_RAID_INSTANCE,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x416*/ DEFINE_HANDLER(CMSG_NO_SPELL_VARIANCE,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x417*/ DEFINE_HANDLER(CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY,                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleQuestgiverStatusMultipleQuery      );
    /*0x418*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTGIVER_STATUS_MULTIPLE,                         STATUS_NEVER);
    /*0x419*/ DEFINE_HANDLER(CMSG_SET_PLAYER_DECLINED_NAMES,                                        STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleSetPlayerDeclinedNames             );
    /*0x41A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_PLAYER_DECLINED_NAMES_RESULT,                   STATUS_NEVER);
    /*0x41B*/ DEFINE_HANDLER(CMSG_QUERY_SERVER_BUCK_DATA,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x41C*/ DEFINE_HANDLER(CMSG_CLEAR_SERVER_BUCK_DATA,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x41D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SERVER_BUCK_DATA,                                   STATUS_NEVER);
    /*0x41E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SEND_UNLEARN_SPELLS,                                STATUS_NEVER);
    /*0x41F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PROPOSE_LEVEL_GRANT,                                STATUS_NEVER);
    /*0x420*/ DEFINE_HANDLER(CMSG_ACCEPT_LEVEL_GRANT,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAcceptGrantLevel                   );
    /*0x421*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_REFER_A_FRIEND_FAILURE,                             STATUS_NEVER);
    /*0x422*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_SET_FLYING,                             STATUS_NEVER);
    /*0x423*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_UNSET_FLYING,                           STATUS_NEVER);
    /*0x424*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SUMMON_CANCEL,                                      STATUS_NEVER);
    /*0x425*/ DEFINE_HANDLER(CMSG_CHANGE_PERSONAL_ARENA_RATING,                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x426*/ DEFINE_HANDLER(CMSG_ALTER_APPEARANCE,                                                 STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAlterAppearance                    );
    /*0x427*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ENABLE_BARBER_SHOP,                                 STATUS_NEVER);
    /*0x428*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BARBER_SHOP_RESULT,                                 STATUS_NEVER);
    /*0x429*/ DEFINE_HANDLER(CMSG_CALENDAR_GET_CALENDAR,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarGetCalendar                );
    /*0x42A*/ DEFINE_HANDLER(CMSG_CALENDAR_GET_EVENT,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarGetEvent                   );
    /*0x42B*/ DEFINE_HANDLER(CMSG_CALENDAR_GUILD_FILTER,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarGuildFilter                );
    /*0x42C*/ DEFINE_HANDLER(CMSG_CALENDAR_ARENA_TEAM,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarArenaTeam                  );
    /*0x42D*/ DEFINE_HANDLER(CMSG_CALENDAR_ADD_EVENT,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarAddEvent                   );
    /*0x42E*/ DEFINE_HANDLER(CMSG_CALENDAR_UPDATE_EVENT,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarUpdateEvent                );
    /*0x42F*/ DEFINE_HANDLER(CMSG_CALENDAR_REMOVE_EVENT,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarRemoveEvent                );
    /*0x430*/ DEFINE_HANDLER(CMSG_CALENDAR_COPY_EVENT,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarCopyEvent                  );
    /*0x431*/ DEFINE_HANDLER(CMSG_CALENDAR_EVENT_INVITE,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarEventInvite                );
    /*0x432*/ DEFINE_HANDLER(CMSG_CALENDAR_EVENT_RSVP,                                              STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarEventRsvp                  );
    /*0x433*/ DEFINE_HANDLER(CMSG_CALENDAR_EVENT_REMOVE_INVITE,                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarEventRemoveInvite          );
    /*0x434*/ DEFINE_HANDLER(CMSG_CALENDAR_EVENT_STATUS,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarEventStatus                );
    /*0x435*/ DEFINE_HANDLER(CMSG_CALENDAR_EVENT_MODERATOR_STATUS,                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarEventModeratorStatus       );
    /*0x436*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_SEND_CALENDAR,                             STATUS_NEVER);
    /*0x437*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_SEND_EVENT,                                STATUS_NEVER);
    /*0x438*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_FILTER_GUILD,                              STATUS_NEVER);
    /*0x439*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_ARENA_TEAM,                                STATUS_NEVER);
    /*0x43A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_INVITE,                              STATUS_NEVER);
    /*0x43B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_INVITE_REMOVED,                      STATUS_NEVER);
    /*0x43C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_STATUS,                              STATUS_NEVER);
    /*0x43D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_COMMAND_RESULT,                            STATUS_NEVER);
    /*0x43E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_RAID_LOCKOUT_ADDED,                        STATUS_NEVER);
    /*0x43F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_RAID_LOCKOUT_REMOVED,                      STATUS_NEVER);
    /*0x440*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_INVITE_ALERT,                        STATUS_NEVER);
    /*0x441*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT,                STATUS_NEVER);
    /*0x442*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT,                 STATUS_NEVER);
    /*0x443*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_REMOVED_ALERT,                       STATUS_NEVER);
    /*0x444*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_UPDATED_ALERT,                       STATUS_NEVER);
    /*0x445*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT,              STATUS_NEVER);
    /*0x446*/ DEFINE_HANDLER(CMSG_CALENDAR_COMPLAIN,                                                STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarComplain                   );
    /*0x447*/ DEFINE_HANDLER(CMSG_CALENDAR_GET_NUM_PENDING,                                         STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarGetNumPending              );
    /*0x448*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_SEND_NUM_PENDING,                          STATUS_NEVER);
    /*0x449*/ DEFINE_HANDLER(CMSG_SAVE_DANCE,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x44A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_NOTIFY_DANCE,                                       STATUS_NEVER);
    /*0x44B*/ DEFINE_HANDLER(CMSG_PLAY_DANCE,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x44C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAY_DANCE,                                         STATUS_NEVER);
    /*0x44D*/ DEFINE_HANDLER(CMSG_LOAD_DANCES,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x44E*/ DEFINE_HANDLER(CMSG_STOP_DANCE,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x44F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_STOP_DANCE,                                         STATUS_NEVER);
    /*0x450*/ DEFINE_HANDLER(CMSG_SYNC_DANCE,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x451*/ DEFINE_HANDLER(CMSG_DANCE_QUERY,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x452*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DANCE_QUERY_RESPONSE,                               STATUS_NEVER);
    /*0x453*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_INVALIDATE_DANCE,                                   STATUS_NEVER);
    /*0x454*/ DEFINE_HANDLER(CMSG_DELETE_DANCE,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x455*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LEARNED_DANCE_MOVES,                                STATUS_NEVER);
    /*0x456*/ DEFINE_HANDLER(CMSG_LEARN_DANCE_MOVE,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x457*/ DEFINE_HANDLER(CMSG_UNLEARN_DANCE_MOVE,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x458*/ DEFINE_HANDLER(CMSG_SET_RUNE_COUNT,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x459*/ DEFINE_HANDLER(CMSG_SET_RUNE_COOLDOWN,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x45A*/ DEFINE_HANDLER(MSG_MOVE_SET_PITCH_RATE_CHEAT,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x45B*/ DEFINE_HANDLER(MSG_MOVE_SET_PITCH_RATE,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x45C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_PITCH_RATE_CHANGE,                            STATUS_NEVER);
    /*0x45D*/ DEFINE_HANDLER(CMSG_FORCE_PITCH_RATE_CHANGE_ACK,                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x45E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_SET_PITCH_RATE,                              STATUS_NEVER);
    /*0x45F*/ DEFINE_HANDLER(CMSG_CALENDAR_EVENT_INVITE_NOTES,                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x460*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_INVITE_NOTES,                        STATUS_NEVER);
    /*0x461*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_EVENT_INVITE_NOTES_ALERT,                  STATUS_NEVER);
    /*0x462*/ DEFINE_HANDLER(CMSG_UPDATE_MISSILE_TRAJECTORY,                                        STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleUpdateMissileTrajectory            );
    /*0x463*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_UPDATE_ACCOUNT_DATA_COMPLETE,                       STATUS_NEVER);
    /*0x464*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TRIGGER_MOVIE,                                      STATUS_NEVER);
    /*0x465*/ DEFINE_HANDLER(CMSG_COMPLETE_MOVIE,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x466*/ DEFINE_HANDLER(CMSG_SET_GLYPH_SLOT,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x467*/ DEFINE_HANDLER(CMSG_SET_GLYPH,                                                        STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x468*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ACHIEVEMENT_EARNED,                                 STATUS_NEVER);
    /*0x469*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DYNAMIC_DROP_ROLL_RESULT,                           STATUS_NEVER);
    /*0x46A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CRITERIA_UPDATE,                                    STATUS_NEVER);
    /*0x46B*/ DEFINE_HANDLER(CMSG_QUERY_INSPECT_ACHIEVEMENTS,                                       STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQueryInspectAchievements           );
    /*0x46C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RESPOND_INSPECT_ACHIEVEMENTS,                       STATUS_NEVER);
    /*0x46D*/ DEFINE_HANDLER(CMSG_DISMISS_CONTROLLED_VEHICLE,                                       STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleDismissControlledVehicle           );
    /*0x46E*/ DEFINE_HANDLER(CMSG_COMPLETE_ACHIEVEMENT_CHEAT,                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x46F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUESTUPDATE_ADD_PVP_KILL,                           STATUS_NEVER);
    /*0x470*/ DEFINE_HANDLER(CMSG_SET_CRITERIA_CHEAT,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x471*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_RAID_LOCKOUT_UPDATED,                      STATUS_NEVER);
    /*0x472*/ DEFINE_HANDLER(CMSG_UNITANIMTIER_CHEAT,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x473*/ DEFINE_HANDLER(CMSG_CHAR_CUSTOMIZE,                                                   STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleCharCustomize                      );
    /*0x474*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAR_CUSTOMIZE,                                     STATUS_NEVER);
    /*0x475*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_RENAMEABLE,                                     STATUS_NEVER);
    /*0x476*/ DEFINE_HANDLER(CMSG_REQUEST_VEHICLE_EXIT,                                             STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleRequestVehicleExit                 );
    /*0x477*/ DEFINE_HANDLER(CMSG_REQUEST_VEHICLE_PREV_SEAT,                                        STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleChangeSeatsOnControlledVehicle     );
    /*0x478*/ DEFINE_HANDLER(CMSG_REQUEST_VEHICLE_NEXT_SEAT,                                        STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleChangeSeatsOnControlledVehicle     );
    /*0x479*/ DEFINE_HANDLER(CMSG_REQUEST_VEHICLE_SWITCH_SEAT,                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleChangeSeatsOnControlledVehicle     );
    /*0x47A*/ DEFINE_HANDLER(CMSG_PET_LEARN_TALENT,                                                 STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandlePetLearnTalent                     );
    /*0x47B*/ DEFINE_HANDLER(CMSG_PET_UNLEARN_TALENTS,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x47C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_PHASE_SHIFT,                                    STATUS_NEVER);
    /*0x47D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ALL_ACHIEVEMENT_DATA,                               STATUS_NEVER);
    /*0x47E*/ DEFINE_HANDLER(CMSG_FORCE_SAY_CHEAT,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x47F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_HEALTH_UPDATE,                                      STATUS_NEVER);
    /*0x480*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_POWER_UPDATE,                                       STATUS_NEVER);
    /*0x481*/ DEFINE_HANDLER(CMSG_GAMEOBJ_REPORT_USE,                                               STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleGameobjectReportUse                );
    /*0x482*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_HIGHEST_THREAT_UPDATE,                              STATUS_NEVER);
    /*0x483*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_THREAT_UPDATE,                                      STATUS_NEVER);
    /*0x484*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_THREAT_REMOVE,                                      STATUS_NEVER);
    /*0x485*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_THREAT_CLEAR,                                       STATUS_NEVER);
    /*0x486*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CONVERT_RUNE,                                       STATUS_NEVER);
    /*0x487*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_RESYNC_RUNES,                                       STATUS_NEVER);
    /*0x488*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ADD_RUNE_POWER,                                     STATUS_NEVER);
    /*0x489*/ DEFINE_HANDLER(CMSG_START_QUEST,                                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x48A*/ DEFINE_HANDLER(CMSG_REMOVE_GLYPH,                                                     STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleRemoveGlyph                        );
    /*0x48B*/ DEFINE_HANDLER(CMSG_DUMP_OBJECTS,                                                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x48C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DUMP_OBJECTS_DATA,                                  STATUS_NEVER);
    /*0x48D*/ DEFINE_HANDLER(CMSG_DISMISS_CRITTER,                                                  STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleDismissCritter                     );
    /*0x48E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_NOTIFY_DEST_LOC_SPELL_CAST,                         STATUS_NEVER);
    /*0x48F*/ DEFINE_HANDLER(CMSG_AUCTION_LIST_PENDING_SALES,                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleAuctionListPendingSales            );
    /*0x490*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AUCTION_LIST_PENDING_SALES,                         STATUS_NEVER);
    /*0x491*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MODIFY_COOLDOWN,                                    STATUS_NEVER);
    /*0x492*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_UPDATE_COMBO_POINTS,                            STATUS_NEVER);
    /*0x493*/ DEFINE_HANDLER(CMSG_ENABLETAXI,                                                       STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleTaxiQueryAvailableNodes            );
    /*0x494*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PRE_RESURRECT,                                      STATUS_NEVER);
    /*0x495*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AURA_UPDATE_ALL,                                    STATUS_NEVER);
    /*0x496*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AURA_UPDATE,                                        STATUS_NEVER);
    /*0x497*/ DEFINE_HANDLER(CMSG_FLOOD_GRACE_CHEAT,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x498*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SERVER_FIRST_ACHIEVEMENT,                           STATUS_NEVER);
    /*0x499*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_LEARNED_SPELL,                                  STATUS_NEVER);
    /*0x49A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_UNLEARNED_SPELL,                                STATUS_NEVER);
    /*0x49B*/ DEFINE_HANDLER(CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE,                               STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleChangeSeatsOnControlledVehicle     );
    /*0x49C*/ DEFINE_HANDLER(CMSG_HEARTH_AND_RESURRECT,                                             STATUS_LOGGEDIN,   PROCESS_THREADSAFE,     &WorldSession::HandleHearthAndResurrect                 );
    /*0x49D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA,               STATUS_NEVER);
    /*0x49E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CRITERIA_DELETED,                                   STATUS_NEVER);
    /*0x49F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ACHIEVEMENT_DELETED,                                STATUS_NEVER);
    /*0x4A0*/ DEFINE_HANDLER(CMSG_SERVER_INFO_QUERY,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4A1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SERVER_INFO_RESPONSE,                               STATUS_NEVER);
    /*0x4A2*/ DEFINE_HANDLER(CMSG_CHECK_LOGIN_CRITERIA,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4A3*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SERVER_BUCK_DATA_START,                             STATUS_NEVER);
    /*0x4A4*/ DEFINE_HANDLER(CMSG_SET_BREATH,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4A5*/ DEFINE_HANDLER(CMSG_QUERY_VEHICLE_STATUS,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4A6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEGROUND_INFO_THROTTLED,                        STATUS_NEVER);
    /*0x4A7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PLAYER_VEHICLE_DATA,                                STATUS_NEVER);
    /*0x4A8*/ DEFINE_HANDLER(CMSG_PLAYER_VEHICLE_ENTER,                                             STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleEnterPlayerVehicle                 );
    /*0x4A9*/ DEFINE_HANDLER(CMSG_CONTROLLER_EJECT_PASSENGER,                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleEjectPassenger                     );
    /*0x4AA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PET_GUIDS,                                          STATUS_NEVER);
    /*0x4AB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CLIENTCACHE_VERSION,                                STATUS_NEVER);
    /*0x4AC*/ DEFINE_HANDLER(CMSG_CHANGE_GDF_ARENA_RATING,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4AD*/ DEFINE_HANDLER(CMSG_SET_ARENA_TEAM_RATING_BY_INDEX,                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4AE*/ DEFINE_HANDLER(CMSG_SET_ARENA_TEAM_WEEKLY_GAMES,                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4AF*/ DEFINE_HANDLER(CMSG_SET_ARENA_TEAM_SEASON_GAMES,                                      STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4B0*/ DEFINE_HANDLER(CMSG_SET_ARENA_MEMBER_WEEKLY_GAMES,                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4B1*/ DEFINE_HANDLER(CMSG_SET_ARENA_MEMBER_SEASON_GAMES,                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4B2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ITEM_REFUND_INFO_RESPONSE,                          STATUS_NEVER);
    /*0x4B3*/ DEFINE_HANDLER(CMSG_ITEM_REFUND_INFO,                                                 STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleItemRefundInfoRequest              );
    /*0x4B4*/ DEFINE_HANDLER(CMSG_ITEM_REFUND,                                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleItemRefund                         );
    /*0x4B5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ITEM_REFUND_RESULT,                                 STATUS_NEVER);
    /*0x4B6*/ DEFINE_HANDLER(CMSG_CORPSE_MAP_POSITION_QUERY,                                        STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCorpseMapPositionQuery             );
    /*0x4B7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE,                 STATUS_NEVER);
    /*0x4B8*/ DEFINE_HANDLER(CMSG_UNUSED5,                                                          STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::Handle_NULL                              );
    /*0x4B9*/ DEFINE_HANDLER(CMSG_UNUSED6,                                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4BA*/ DEFINE_HANDLER(CMSG_CALENDAR_EVENT_SIGNUP,                                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleCalendarEventSignup                );
    /*0x4BB*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CALENDAR_CLEAR_PENDING_ACTION,                      STATUS_NEVER);
    /*0x4BC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_EQUIPMENT_SET_LIST,                                 STATUS_NEVER);
    /*0x4BD*/ DEFINE_HANDLER(CMSG_EQUIPMENT_SET_SAVE,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleEquipmentSetSave                   );
    /*0x4BE*/ DEFINE_HANDLER(CMSG_UPDATE_PROJECTILE_POSITION,                                       STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleUpdateProjectilePosition           );
    /*0x4BF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SET_PROJECTILE_POSITION,                            STATUS_NEVER);
    /*0x4C0*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TALENTS_INFO,                                       STATUS_NEVER);
    /*0x4C1*/ DEFINE_HANDLER(CMSG_LEARN_PREVIEW_TALENTS,                                            STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleLearnPreviewTalents                );
    /*0x4C2*/ DEFINE_HANDLER(CMSG_LEARN_PREVIEW_TALENTS_PET,                                        STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleLearnPreviewTalentsPet             );
    /*0x4C3*/ DEFINE_HANDLER(CMSG_SET_ACTIVE_TALENT_GROUP_OBSOLETE,                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4C4*/ DEFINE_HANDLER(CMSG_GM_GRANT_ACHIEVEMENT,                                             STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4C5*/ DEFINE_HANDLER(CMSG_GM_REMOVE_ACHIEVEMENT,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4C6*/ DEFINE_HANDLER(CMSG_GM_SET_CRITERIA_FOR_PLAYER,                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4C7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ARENA_UNIT_DESTROYED,                               STATUS_NEVER);
    /*0x4C8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED,                    STATUS_NEVER);
    /*0x4C9*/ DEFINE_HANDLER(CMSG_PROFILEDATA_REQUEST,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4CA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PROFILEDATA_RESPONSE,                               STATUS_NEVER);
    /*0x4CB*/ DEFINE_HANDLER(CMSG_START_BATTLEFIELD_CHEAT,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4CC*/ DEFINE_HANDLER(CMSG_END_BATTLEFIELD_CHEAT,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4CD*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MULTIPLE_PACKETS,                                   STATUS_NEVER);
    /*0x4CE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_GRAVITY_DISABLE,                               STATUS_NEVER);
    /*0x4CF*/ DEFINE_HANDLER(CMSG_MOVE_GRAVITY_DISABLE_ACK,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4D0*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_GRAVITY_ENABLE,                                STATUS_NEVER);
    /*0x4D1*/ DEFINE_HANDLER(CMSG_MOVE_GRAVITY_ENABLE_ACK,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4D2*/ DEFINE_SERVER_OPCODE_HANDLER(MSG_MOVE_GRAVITY_CHNG,                                   STATUS_NEVER);
    /*0x4D3*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_GRAVITY_DISABLE,                        STATUS_NEVER);
    /*0x4D4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SPLINE_MOVE_GRAVITY_ENABLE,                         STATUS_NEVER);
    /*0x4D5*/ DEFINE_HANDLER(CMSG_EQUIPMENT_SET_USE,                                                STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleEquipmentSetUse                    );
    /*0x4D6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_EQUIPMENT_SET_USE_RESULT,                           STATUS_NEVER);
    /*0x4D7*/ DEFINE_HANDLER(CMSG_FORCE_ANIM,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4D8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_ANIM,                                         STATUS_NEVER);
    /*0x4D9*/ DEFINE_HANDLER(CMSG_CHAR_FACTION_CHANGE,                                              STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleCharFactionOrRaceChange            );
    /*0x4DA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CHAR_FACTION_CHANGE,                                STATUS_NEVER);
    /*0x4DB*/ DEFINE_HANDLER(CMSG_PVP_QUEUE_STATS_REQUEST,                                          STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4DC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_PVP_QUEUE_STATS,                                    STATUS_NEVER);
    /*0x4DD*/ DEFINE_HANDLER(CMSG_SET_PAID_SERVICE_CHEAT,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4DE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEFIELD_MGR_ENTRY_INVITE,                       STATUS_NEVER);
    /*0x4DF*/ DEFINE_HANDLER(CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE,                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBfEntryInviteResponse              ); // pussywizard: unsafe, changes groups and much more >_>
    /*0x4E0*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEFIELD_MGR_ENTERED,                            STATUS_NEVER);
    /*0x4E1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEFIELD_MGR_QUEUE_INVITE,                       STATUS_NEVER);
    /*0x4E2*/ DEFINE_HANDLER(CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE,                            STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBfQueueInviteResponse              );
    /*0x4E3*/ DEFINE_HANDLER(CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST,                                    STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4E4*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE,             STATUS_NEVER);
    /*0x4E5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEFIELD_MGR_EJECT_PENDING,                      STATUS_NEVER);
    /*0x4E6*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEFIELD_MGR_EJECTED,                            STATUS_NEVER);
    /*0x4E7*/ DEFINE_HANDLER(CMSG_BATTLEFIELD_MGR_EXIT_REQUEST,                                     STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleBfExitRequest                      );
    /*0x4E8*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_BATTLEFIELD_MGR_STATE_CHANGE,                       STATUS_NEVER);
    /*0x4E9*/ DEFINE_HANDLER(CMSG_BATTLEFIELD_MANAGER_ADVANCE_STATE,                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4EA*/ DEFINE_HANDLER(CMSG_BATTLEFIELD_MANAGER_SET_NEXT_TRANSITION_TIME,                     STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4EB*/ DEFINE_HANDLER(MSG_SET_RAID_DIFFICULTY,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleSetRaidDifficultyOpcode            );
    /*0x4EC*/ DEFINE_HANDLER(CMSG_TOGGLE_XP_GAIN,                                                   STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4ED*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TOGGLE_XP_GAIN,                                     STATUS_NEVER);
    /*0x4EE*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GMRESPONSE_DB_ERROR,                                STATUS_NEVER);
    /*0x4EF*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GMRESPONSE_RECEIVED,                                STATUS_NEVER);
    /*0x4F0*/ DEFINE_HANDLER(CMSG_GMRESPONSE_RESOLVE,                                               STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleGMResponseResolve                  );
    /*0x4F1*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GMRESPONSE_STATUS_UPDATE,                           STATUS_NEVER);
    /*0x4F2*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_GMRESPONSE_CREATE_TICKET,                           STATUS_NEVER);
    /*0x4F3*/ DEFINE_HANDLER(CMSG_GMRESPONSE_CREATE_TICKET,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4F4*/ DEFINE_HANDLER(CMSG_SERVERINFO,                                                       STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4F5*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SERVERINFO,                                         STATUS_NEVER);
    /*0x4F6*/ DEFINE_HANDLER(CMSG_WORLD_STATE_UI_TIMER_UPDATE,                                      STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleWorldStateUITimerUpdate            );
    /*0x4F7*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_WORLD_STATE_UI_TIMER_UPDATE,                        STATUS_NEVER);
    /*0x4F8*/ DEFINE_HANDLER(CMSG_CHAR_RACE_CHANGE,                                                 STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleCharFactionOrRaceChange            );
    /*0x4F9*/ DEFINE_HANDLER(MSG_VIEW_PHASE_SHIFT,                                                  STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4FA*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_TALENTS_INVOLUNTARILY_RESET,                        STATUS_NEVER);
    /*0x4FB*/ DEFINE_HANDLER(CMSG_DEBUG_SERVER_GEO,                                                 STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4FC*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_DEBUG_SERVER_GEO,                                   STATUS_NEVER);
    /*0x4FD*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_LOOT_SLOT_CHANGED,                                  STATUS_NEVER);
    /*0x4FE*/ DEFINE_HANDLER(UMSG_UPDATE_GROUP_INFO,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x4FF*/ DEFINE_HANDLER(CMSG_READY_FOR_ACCOUNT_DATA_TIMES,                                     STATUS_AUTHED,     PROCESS_THREADUNSAFE,   &WorldSession::HandleReadyForAccountDataTimes           );
    /*0x500*/ DEFINE_HANDLER(CMSG_QUERY_QUESTS_COMPLETED,                                           STATUS_LOGGEDIN,   PROCESS_INPLACE,        &WorldSession::HandleQueryQuestsCompleted               );
    /*0x501*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_QUERY_QUESTS_COMPLETED_RESPONSE,                    STATUS_NEVER);
    /*0x502*/ DEFINE_HANDLER(CMSG_GM_REPORT_LAG,                                                    STATUS_LOGGEDIN,   PROCESS_THREADUNSAFE,   &WorldSession::HandleReportLag                          );
    /*0x503*/ DEFINE_HANDLER(CMSG_AFK_MONITOR_INFO_REQUEST,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x504*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_AFK_MONITOR_INFO_RESPONSE,                          STATUS_NEVER);
    /*0x505*/ DEFINE_HANDLER(CMSG_AFK_MONITOR_INFO_CLEAR,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x506*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CORPSE_NOT_IN_INSTANCE,                             STATUS_NEVER);
    /*0x507*/ DEFINE_HANDLER(CMSG_GM_NUKE_CHARACTER,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x508*/ DEFINE_HANDLER(CMSG_SET_ALLOW_LOW_LEVEL_RAID1,                                        STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x509*/ DEFINE_HANDLER(CMSG_SET_ALLOW_LOW_LEVEL_RAID2,                                        STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x50A*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_CAMERA_SHAKE,                                       STATUS_NEVER);
    /*0x50B*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SOCKET_GEMS_RESULT,                                 STATUS_NEVER);
    /*0x50C*/ DEFINE_HANDLER(CMSG_SET_CHARACTER_MODEL,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x50D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_REDIRECT_CLIENT,                                    STATUS_NEVER);
    /*0x50E*/ DEFINE_HANDLER(CMSG_REDIRECTION_FAILED,                                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x50F*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SUSPEND_COMMS,                                      STATUS_NEVER);
    /*0x510*/ DEFINE_HANDLER(CMSG_SUSPEND_COMMS_ACK,                                                STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x511*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_FORCE_SEND_QUEUED_PACKETS,                          STATUS_NEVER);
    /*0x512*/ DEFINE_HANDLER(CMSG_REDIRECTION_AUTH_PROOF,                                           STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x513*/ DEFINE_HANDLER(CMSG_DROP_NEW_CONNECTION,                                              STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x514*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_SEND_ALL_COMBAT_LOG,                                STATUS_NEVER);
    /*0x515*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_OPEN_LFG_DUNGEON_FINDER,                            STATUS_NEVER);
    /*0x516*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_SET_COLLISION_HGT,                             STATUS_NEVER);
    /*0x517*/ DEFINE_HANDLER(CMSG_MOVE_SET_COLLISION_HGT_ACK,                                       STATUS_UNHANDLED,  PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x518*/ DEFINE_HANDLER(MSG_MOVE_SET_COLLISION_HGT,                                            STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x519*/ DEFINE_HANDLER(CMSG_CLEAR_RANDOM_BG_WIN_TIME,                                         STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x51A*/ DEFINE_HANDLER(CMSG_CLEAR_HOLIDAY_BG_WIN_TIME,                                        STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x51B*/ DEFINE_HANDLER(CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND,                               STATUS_NEVER,      PROCESS_INPLACE,        &WorldSession::Handle_NULL                              );
    /*0x51C*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT1,                 STATUS_NEVER);
    /*0x51D*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT2,                 STATUS_NEVER);
    /*0x51E*/ DEFINE_SERVER_OPCODE_HANDLER(SMSG_MULTIPLE_MOVES, STATUS_NEVER);
#undef DEFINE_HANDLER
#undef DEFINE_SERVER_OPCODE_HANDLER
}
References CMSG_ACCEPT_LEVEL_GRANT, CMSG_ACCEPT_TRADE, CMSG_ACTIVATETAXI, CMSG_ACTIVATETAXIEXPRESS, CMSG_ACTIVE_PVP_CHEAT, CMSG_ADD_FRIEND, CMSG_ADD_IGNORE, CMSG_ADD_PVP_MEDAL_CHEAT, CMSG_ADD_VOICE_IGNORE, CMSG_ADVANCE_SPAWN_TIME, CMSG_AFK_MONITOR_INFO_CLEAR, CMSG_AFK_MONITOR_INFO_REQUEST, CMSG_ALTER_APPEARANCE, CMSG_AREA_SPIRIT_HEALER_QUERY, CMSG_AREA_SPIRIT_HEALER_QUEUE, CMSG_AREATRIGGER, CMSG_ARENA_TEAM_ACCEPT, CMSG_ARENA_TEAM_CREATE, CMSG_ARENA_TEAM_DECLINE, CMSG_ARENA_TEAM_DISBAND, CMSG_ARENA_TEAM_INVITE, CMSG_ARENA_TEAM_LEADER, CMSG_ARENA_TEAM_LEAVE, CMSG_ARENA_TEAM_QUERY, CMSG_ARENA_TEAM_REMOVE, CMSG_ARENA_TEAM_ROSTER, CMSG_ATTACKSTOP, CMSG_ATTACKSWING, CMSG_AUCTION_LIST_BIDDER_ITEMS, CMSG_AUCTION_LIST_ITEMS, CMSG_AUCTION_LIST_OWNER_ITEMS, CMSG_AUCTION_LIST_PENDING_SALES, CMSG_AUCTION_PLACE_BID, CMSG_AUCTION_REMOVE_ITEM, CMSG_AUCTION_SELL_ITEM, CMSG_AUTH_SESSION, CMSG_AUTH_SRP6_BEGIN, CMSG_AUTH_SRP6_PROOF, CMSG_AUTH_SRP6_RECODE, CMSG_AUTOBANK_ITEM, CMSG_AUTOEQUIP_GROUND_ITEM, CMSG_AUTOEQUIP_ITEM, CMSG_AUTOEQUIP_ITEM_SLOT, CMSG_AUTOSTORE_BAG_ITEM, CMSG_AUTOSTORE_BANK_ITEM, CMSG_AUTOSTORE_GROUND_ITEM, CMSG_AUTOSTORE_LOOT_ITEM, CMSG_BANKER_ACTIVATE, CMSG_BATTLEFIELD_JOIN, CMSG_BATTLEFIELD_LIST, CMSG_BATTLEFIELD_MANAGER_ADVANCE_STATE, CMSG_BATTLEFIELD_MANAGER_SET_NEXT_TRANSITION_TIME, CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE, CMSG_BATTLEFIELD_MGR_EXIT_REQUEST, CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE, CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST, CMSG_BATTLEFIELD_PORT, CMSG_BATTLEFIELD_STATUS, CMSG_BATTLEMASTER_HELLO, CMSG_BATTLEMASTER_JOIN, CMSG_BATTLEMASTER_JOIN_ARENA, CMSG_BEASTMASTER, CMSG_BEGIN_TRADE, CMSG_BINDER_ACTIVATE, CMSG_BOOTME, CMSG_BOT_DETECTED, CMSG_BOT_DETECTED2, CMSG_BUG, CMSG_BUSY_TRADE, CMSG_BUY_BANK_SLOT, CMSG_BUY_ITEM, CMSG_BUY_ITEM_IN_SLOT, CMSG_BUY_LOTTERY_TICKET_OBSOLETE, CMSG_BUY_STABLE_SLOT, CMSG_BUYBACK_ITEM, CMSG_CALENDAR_ADD_EVENT, CMSG_CALENDAR_ARENA_TEAM, CMSG_CALENDAR_COMPLAIN, CMSG_CALENDAR_COPY_EVENT, CMSG_CALENDAR_EVENT_INVITE, CMSG_CALENDAR_EVENT_INVITE_NOTES, CMSG_CALENDAR_EVENT_MODERATOR_STATUS, CMSG_CALENDAR_EVENT_REMOVE_INVITE, CMSG_CALENDAR_EVENT_RSVP, CMSG_CALENDAR_EVENT_SIGNUP, CMSG_CALENDAR_EVENT_STATUS, CMSG_CALENDAR_GET_CALENDAR, CMSG_CALENDAR_GET_EVENT, CMSG_CALENDAR_GET_NUM_PENDING, CMSG_CALENDAR_GUILD_FILTER, CMSG_CALENDAR_REMOVE_EVENT, CMSG_CALENDAR_UPDATE_EVENT, CMSG_CANCEL_AURA, CMSG_CANCEL_AUTO_REPEAT_SPELL, CMSG_CANCEL_CAST, CMSG_CANCEL_CHANNELLING, CMSG_CANCEL_GROWTH_AURA, CMSG_CANCEL_MOUNT_AURA, CMSG_CANCEL_TEMP_ENCHANTMENT, CMSG_CANCEL_TRADE, CMSG_CAST_SPELL, CMSG_CHANGE_GDF_ARENA_RATING, CMSG_CHANGE_PERSONAL_ARENA_RATING, CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE, CMSG_CHANGEPLAYER_DIFFICULTY, CMSG_CHANNEL_ANNOUNCEMENTS, CMSG_CHANNEL_BAN, CMSG_CHANNEL_DISPLAY_LIST, CMSG_CHANNEL_INVITE, CMSG_CHANNEL_KICK, CMSG_CHANNEL_LIST, CMSG_CHANNEL_MODERATE, CMSG_CHANNEL_MODERATOR, CMSG_CHANNEL_MUTE, CMSG_CHANNEL_OWNER, CMSG_CHANNEL_PASSWORD, CMSG_CHANNEL_SET_OWNER, CMSG_CHANNEL_SILENCE_ALL, CMSG_CHANNEL_SILENCE_VOICE, CMSG_CHANNEL_UNBAN, CMSG_CHANNEL_UNMODERATOR, CMSG_CHANNEL_UNMUTE, CMSG_CHANNEL_UNSILENCE_ALL, CMSG_CHANNEL_UNSILENCE_VOICE, CMSG_CHANNEL_VOICE_OFF, CMSG_CHANNEL_VOICE_ON, CMSG_CHAR_CREATE, CMSG_CHAR_CUSTOMIZE, CMSG_CHAR_DELETE, CMSG_CHAR_ENUM, CMSG_CHAR_FACTION_CHANGE, CMSG_CHAR_RACE_CHANGE, CMSG_CHAR_RENAME, CMSG_CHARACTER_POINT_CHEAT, CMSG_CHAT_FILTERED, CMSG_CHAT_IGNORED, CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY, CMSG_CHEAT_PLAYER_LOGIN, CMSG_CHEAT_PLAYER_LOOKUP, CMSG_CHEAT_SET_ARENA_CURRENCY, CMSG_CHEAT_SET_HONOR_CURRENCY, CMSG_CHEAT_SETMONEY, CMSG_CHECK_LOGIN_CRITERIA, CMSG_CLEAR_CHANNEL_WATCH, CMSG_CLEAR_EXPLORATION, CMSG_CLEAR_HOLIDAY_BG_WIN_TIME, CMSG_CLEAR_QUEST, CMSG_CLEAR_RANDOM_BG_WIN_TIME, CMSG_CLEAR_SERVER_BUCK_DATA, CMSG_CLEAR_TRADE_ITEM, CMSG_COMMENTATOR_ENABLE, CMSG_COMMENTATOR_ENTER_INSTANCE, CMSG_COMMENTATOR_EXIT_INSTANCE, CMSG_COMMENTATOR_GET_MAP_INFO, CMSG_COMMENTATOR_GET_PLAYER_INFO, CMSG_COMMENTATOR_INSTANCE_COMMAND, CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND, CMSG_COMPLAIN, CMSG_COMPLETE_ACHIEVEMENT_CHEAT, CMSG_COMPLETE_CINEMATIC, CMSG_COMPLETE_MOVIE, CMSG_CONTACT_LIST, CMSG_CONTROLLER_EJECT_PASSENGER, CMSG_COOLDOWN_CHEAT, CMSG_CORPSE_MAP_POSITION_QUERY, CMSG_CREATEGAMEOBJECT, CMSG_CREATEITEM, CMSG_CREATEMONSTER, CMSG_CREATURE_QUERY, CMSG_DANCE_QUERY, CMSG_DBLOOKUP, CMSG_DEBUG_ACTIONS_START, CMSG_DEBUG_ACTIONS_STOP, CMSG_DEBUG_AISTATE, CMSG_DEBUG_CHANGECELLZONE, CMSG_DEBUG_LIST_TARGETS, CMSG_DEBUG_PASSIVE_AURA, CMSG_DEBUG_SERVER_GEO, CMSG_DECHARGE, CMSG_DECLINE_CHANNEL_INVITE, CMSG_DEL_FRIEND, CMSG_DEL_IGNORE, CMSG_DEL_PVP_MEDAL_CHEAT, CMSG_DEL_VOICE_IGNORE, CMSG_DELETE_DANCE, CMSG_DELETEEQUIPMENT_SET, CMSG_DESTROY_ITEMS, CMSG_DESTROYITEM, CMSG_DESTROYMONSTER, CMSG_DISABLE_PVP_CHEAT, CMSG_DISMISS_CONTROLLED_VEHICLE, CMSG_DISMISS_CRITTER, CMSG_DROP_NEW_CONNECTION, CMSG_DUEL_ACCEPTED, CMSG_DUEL_CANCELLED, CMSG_DUMP_OBJECTS, CMSG_EMOTE, CMSG_ENABLE_DAMAGE_LOG, CMSG_ENABLETAXI, CMSG_END_BATTLEFIELD_CHEAT, CMSG_EQUIPMENT_SET_SAVE, CMSG_EQUIPMENT_SET_USE, CMSG_EXPIRE_RAID_INSTANCE, CMSG_FAR_SIGHT, CMSG_FLAG_QUEST, CMSG_FLAG_QUEST_FINISH, CMSG_FLOOD_GRACE_CHEAT, CMSG_FORCE_ANIM, CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK, CMSG_FORCE_MOVE_ROOT_ACK, CMSG_FORCE_MOVE_UNROOT_ACK, CMSG_FORCE_PITCH_RATE_CHANGE_ACK, CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_RUN_SPEED_CHANGE_ACK, CMSG_FORCE_SAY_CHEAT, CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_SWIM_SPEED_CHANGE_ACK, CMSG_FORCE_TURN_RATE_CHANGE_ACK, CMSG_FORCE_WALK_SPEED_CHANGE_ACK, CMSG_FORCEACTION, CMSG_FORCEACTIONONOTHER, CMSG_FORCEACTIONSHOW, CMSG_GAMEOBJ_REPORT_USE, CMSG_GAMEOBJ_USE, CMSG_GAMEOBJECT_QUERY, CMSG_GAMESPEED_SET, CMSG_GAMETIME_SET, CMSG_GET_CHANNEL_MEMBER_COUNT, CMSG_GET_MAIL_LIST, CMSG_GET_MIRRORIMAGE_DATA, CMSG_GETDEATHBINDZONE, CMSG_GHOST, CMSG_GM_CHARACTER_RESTORE, CMSG_GM_CHARACTER_SAVE, CMSG_GM_CREATE_ITEM_TARGET, CMSG_GM_DESTROY_ONLINE_CORPSE, CMSG_GM_FREEZE, CMSG_GM_GRANT_ACHIEVEMENT, CMSG_GM_INVIS, CMSG_GM_MOVECORPSE, CMSG_GM_NUKE, CMSG_GM_NUKE_ACCOUNT, CMSG_GM_NUKE_CHARACTER, CMSG_GM_REMOVE_ACHIEVEMENT, CMSG_GM_REPORT_LAG, CMSG_GM_REQUEST_PLAYER_INFO, CMSG_GM_RESURRECT, CMSG_GM_REVEALTO, CMSG_GM_SET_CRITERIA_FOR_PLAYER, CMSG_GM_SET_SECURITY_GROUP, CMSG_GM_SHOW_COMPLAINTS, CMSG_GM_SILENCE, CMSG_GM_SUMMONMOB, CMSG_GM_TEACH, CMSG_GM_UBERINVIS, CMSG_GM_UNSQUELCH, CMSG_GM_UNTEACH, CMSG_GM_UPDATE_TICKET_STATUS, CMSG_GM_VISION, CMSG_GM_WHISPER, CMSG_GMRESPONSE_CREATE_TICKET, CMSG_GMRESPONSE_RESOLVE, CMSG_GMSURVEY_SUBMIT, CMSG_GMTICKET_CREATE, CMSG_GMTICKET_DELETETICKET, CMSG_GMTICKET_GETTICKET, CMSG_GMTICKET_SYSTEMSTATUS, CMSG_GMTICKET_UPDATETEXT, CMSG_GMTICKETSYSTEM_TOGGLE, CMSG_GODMODE, CMSG_GOSSIP_HELLO, CMSG_GOSSIP_SELECT_OPTION, CMSG_GRANT_LEVEL, CMSG_GROUP_ACCEPT, CMSG_GROUP_ASSISTANT_LEADER, CMSG_GROUP_CANCEL, CMSG_GROUP_CHANGE_SUB_GROUP, CMSG_GROUP_DECLINE, CMSG_GROUP_DISBAND, CMSG_GROUP_INVITE, CMSG_GROUP_RAID_CONVERT, CMSG_GROUP_SET_LEADER, CMSG_GROUP_SWAP_SUB_GROUP, CMSG_GROUP_UNINVITE, CMSG_GROUP_UNINVITE_GUID, CMSG_GUILD_ACCEPT, CMSG_GUILD_ADD_RANK, CMSG_GUILD_BANK_BUY_TAB, CMSG_GUILD_BANK_DEPOSIT_MONEY, CMSG_GUILD_BANK_QUERY_TAB, CMSG_GUILD_BANK_SWAP_ITEMS, CMSG_GUILD_BANK_UPDATE_TAB, CMSG_GUILD_BANK_WITHDRAW_MONEY, CMSG_GUILD_BANKER_ACTIVATE, CMSG_GUILD_CREATE, CMSG_GUILD_DECLINE, CMSG_GUILD_DEL_RANK, CMSG_GUILD_DEMOTE, CMSG_GUILD_DISBAND, CMSG_GUILD_INFO, CMSG_GUILD_INFO_TEXT, CMSG_GUILD_INVITE, CMSG_GUILD_LEADER, CMSG_GUILD_LEAVE, CMSG_GUILD_MOTD, CMSG_GUILD_PROMOTE, CMSG_GUILD_QUERY, CMSG_GUILD_RANK, CMSG_GUILD_REMOVE, CMSG_GUILD_ROSTER, CMSG_GUILD_SET_OFFICER_NOTE, CMSG_GUILD_SET_PUBLIC_NOTE, CMSG_HEARTH_AND_RESURRECT, CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT, CMSG_IGNORE_KNOCKBACK_CHEAT, CMSG_IGNORE_REQUIREMENTS_CHEAT, CMSG_IGNORE_TRADE, CMSG_INITIATE_TRADE, CMSG_INSPECT, CMSG_INSTANCE_LOCK_RESPONSE, CMSG_ITEM_NAME_QUERY, CMSG_ITEM_QUERY_MULTIPLE, CMSG_ITEM_QUERY_SINGLE, CMSG_ITEM_REFUND, CMSG_ITEM_REFUND_INFO, CMSG_ITEM_TEXT_QUERY, CMSG_JOIN_CHANNEL, CMSG_KEEP_ALIVE, CMSG_LEARN_DANCE_MOVE, CMSG_LEARN_PREVIEW_TALENTS, CMSG_LEARN_PREVIEW_TALENTS_PET, CMSG_LEARN_SPELL, CMSG_LEARN_TALENT, CMSG_LEAVE_BATTLEFIELD, CMSG_LEAVE_CHANNEL, CMSG_LEVEL_CHEAT, CMSG_LFD_PARTY_LOCK_INFO_REQUEST, CMSG_LFD_PLAYER_LOCK_INFO_REQUEST, CMSG_LFG_GET_STATUS, CMSG_LFG_JOIN, CMSG_LFG_LEAVE, CMSG_LFG_PROPOSAL_RESULT, CMSG_LFG_SET_BOOT_VOTE, CMSG_LFG_SET_NEEDS, CMSG_LFG_SET_ROLES, CMSG_LFG_TELEPORT, CMSG_LIST_INVENTORY, CMSG_LOAD_DANCES, CMSG_LOGOUT_CANCEL, CMSG_LOGOUT_REQUEST, CMSG_LOOT, CMSG_LOOT_MASTER_GIVE, CMSG_LOOT_METHOD, CMSG_LOOT_MONEY, CMSG_LOOT_RELEASE, CMSG_LOOT_ROLL, CMSG_LOTTERY_QUERY_OBSOLETE, CMSG_LUA_USAGE, CMSG_MAELSTROM_GM_SENT_MAIL, CMSG_MAELSTROM_INVALIDATE_CACHE, CMSG_MAELSTROM_RENAME_GUILD, CMSG_MAIL_CREATE_TEXT_ITEM, CMSG_MAIL_DELETE, CMSG_MAIL_MARK_AS_READ, CMSG_MAIL_RETURN_TO_SENDER, CMSG_MAIL_TAKE_ITEM, CMSG_MAIL_TAKE_MONEY, CMSG_MAKEMONSTERATTACKGUID, CMSG_MESSAGECHAT, CMSG_MINIGAME_MOVE, CMSG_MOUNTSPECIAL_ANIM, CMSG_MOVE_CHARACTER_CHEAT, CMSG_MOVE_CHARM_PORT_CHEAT, CMSG_MOVE_CHNG_TRANSPORT, CMSG_MOVE_FALL_RESET, CMSG_MOVE_FEATHER_FALL_ACK, CMSG_MOVE_GRAVITY_DISABLE_ACK, CMSG_MOVE_GRAVITY_ENABLE_ACK, CMSG_MOVE_HOVER_ACK, CMSG_MOVE_KNOCK_BACK_ACK, CMSG_MOVE_NOT_ACTIVE_MOVER, CMSG_MOVE_SET_CAN_FLY_ACK, CMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY_ACK, CMSG_MOVE_SET_COLLISION_HGT_ACK, CMSG_MOVE_SET_FLY, CMSG_MOVE_SET_RAW_POSITION, CMSG_MOVE_SET_RUN_SPEED, CMSG_MOVE_SPLINE_DONE, CMSG_MOVE_START_SWIM_CHEAT, CMSG_MOVE_STOP_SWIM_CHEAT, CMSG_MOVE_TIME_SKIPPED, CMSG_MOVE_WATER_WALK_ACK, CMSG_NAME_QUERY, CMSG_NEW_SPELL_SLOT, CMSG_NEXT_CINEMATIC_CAMERA, CMSG_NO_SPELL_VARIANCE, CMSG_NPC_TEXT_QUERY, CMSG_OFFER_PETITION, CMSG_OPEN_ITEM, CMSG_OPENING_CINEMATIC, CMSG_OPT_OUT_OF_LOOT, CMSG_PAGE_TEXT_QUERY, CMSG_PARTY_SILENCE, CMSG_PARTY_UNSILENCE, CMSG_PERFORM_ACTION_SET, CMSG_PET_ABANDON, CMSG_PET_ACTION, CMSG_PET_CANCEL_AURA, CMSG_PET_CAST_SPELL, CMSG_PET_LEARN_TALENT, CMSG_PET_LEVEL_CHEAT, CMSG_PET_NAME_QUERY, CMSG_PET_RENAME, CMSG_PET_SET_ACTION, CMSG_PET_SPELL_AUTOCAST, CMSG_PET_STOP_ATTACK, CMSG_PET_UNLEARN, CMSG_PET_UNLEARN_TALENTS, CMSG_PETGODMODE, CMSG_PETITION_BUY, CMSG_PETITION_QUERY, CMSG_PETITION_SHOW_SIGNATURES, CMSG_PETITION_SHOWLIST, CMSG_PETITION_SIGN, CMSG_PING, CMSG_PLAY_DANCE, CMSG_PLAYED_TIME, CMSG_PLAYER_AI_CHEAT, CMSG_PLAYER_LOGIN, CMSG_PLAYER_LOGOUT, CMSG_PLAYER_VEHICLE_ENTER, CMSG_PROFILEDATA_REQUEST, CMSG_PUSHQUESTTOPARTY, CMSG_PVP_QUEUE_STATS_REQUEST, CMSG_QUERY_INSPECT_ACHIEVEMENTS, CMSG_QUERY_OBJECT_POSITION, CMSG_QUERY_OBJECT_ROTATION, CMSG_QUERY_QUESTS_COMPLETED, CMSG_QUERY_SERVER_BUCK_DATA, CMSG_QUERY_TIME, CMSG_QUERY_VEHICLE_STATUS, CMSG_QUEST_CONFIRM_ACCEPT, CMSG_QUEST_POI_QUERY, CMSG_QUEST_QUERY, CMSG_QUESTGIVER_ACCEPT_QUEST, CMSG_QUESTGIVER_CANCEL, CMSG_QUESTGIVER_CHOOSE_REWARD, CMSG_QUESTGIVER_COMPLETE_QUEST, CMSG_QUESTGIVER_HELLO, CMSG_QUESTGIVER_QUERY_QUEST, CMSG_QUESTGIVER_QUEST_AUTOLAUNCH, CMSG_QUESTGIVER_REQUEST_REWARD, CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY, CMSG_QUESTGIVER_STATUS_QUERY, CMSG_QUESTLOG_REMOVE_QUEST, CMSG_QUESTLOG_SWAP_QUEST, CMSG_READ_ITEM, CMSG_READY_FOR_ACCOUNT_DATA_TIMES, CMSG_REALM_SPLIT, CMSG_RECHARGE, CMSG_RECLAIM_CORPSE, CMSG_REDIRECTION_AUTH_PROOF, CMSG_REDIRECTION_FAILED, CMSG_REFER_A_FRIEND, CMSG_REMOVE_GLYPH, CMSG_REPAIR_ITEM, CMSG_REPOP_REQUEST, CMSG_REPORT_PVP_AFK, CMSG_REQUEST_ACCOUNT_DATA, CMSG_REQUEST_PARTY_MEMBER_STATS, CMSG_REQUEST_PET_INFO, CMSG_REQUEST_RAID_INFO, CMSG_REQUEST_VEHICLE_EXIT, CMSG_REQUEST_VEHICLE_NEXT_SEAT, CMSG_REQUEST_VEHICLE_PREV_SEAT, CMSG_REQUEST_VEHICLE_SWITCH_SEAT, CMSG_RESET_FACTION_CHEAT, CMSG_RESET_INSTANCES, CMSG_RESURRECT_RESPONSE, CMSG_RUN_SCRIPT, CMSG_SAVE_DANCE, CMSG_SAVE_PLAYER, CMSG_SEARCH_LFG_JOIN, CMSG_SEARCH_LFG_LEAVE, CMSG_SELF_RES, CMSG_SELL_ITEM, CMSG_SEND_COMBAT_TRIGGER, CMSG_SEND_EVENT, CMSG_SEND_GENERAL_TRIGGER, CMSG_SEND_LOCAL_EVENT, CMSG_SEND_MAIL, CMSG_SERVER_BROADCAST, CMSG_SERVER_COMMAND, CMSG_SERVER_INFO_QUERY, CMSG_SERVERINFO, CMSG_SERVERTIME, CMSG_SET_ACTION_BUTTON, CMSG_SET_ACTIONBAR_TOGGLES, CMSG_SET_ACTIVE_MOVER, CMSG_SET_ACTIVE_TALENT_GROUP_OBSOLETE, CMSG_SET_ACTIVE_VOICE_CHANNEL, CMSG_SET_ALLOW_LOW_LEVEL_RAID1, CMSG_SET_ALLOW_LOW_LEVEL_RAID2, CMSG_SET_AMMO, CMSG_SET_ARENA_MEMBER_SEASON_GAMES, CMSG_SET_ARENA_MEMBER_WEEKLY_GAMES, CMSG_SET_ARENA_TEAM_RATING_BY_INDEX, CMSG_SET_ARENA_TEAM_SEASON_GAMES, CMSG_SET_ARENA_TEAM_WEEKLY_GAMES, CMSG_SET_BREATH, CMSG_SET_CHANNEL_WATCH, CMSG_SET_CHARACTER_MODEL, CMSG_SET_CONTACT_NOTES, CMSG_SET_CRITERIA_CHEAT, CMSG_SET_DURABILITY_CHEAT, CMSG_SET_EXPLORATION, CMSG_SET_EXPLORATION_ALL, CMSG_SET_FACTION_ATWAR, CMSG_SET_FACTION_CHEAT, CMSG_SET_FACTION_INACTIVE, CMSG_SET_GLYPH, CMSG_SET_GLYPH_SLOT, CMSG_SET_GRANTABLE_LEVELS, CMSG_SET_GUILD_BANK_TEXT, CMSG_SET_LFG_COMMENT, CMSG_SET_PAID_SERVICE_CHEAT, CMSG_SET_PLAYER_DECLINED_NAMES, CMSG_SET_PVP_RANK_CHEAT, CMSG_SET_PVP_TITLE, CMSG_SET_RUNE_COOLDOWN, CMSG_SET_RUNE_COUNT, CMSG_SET_SAVED_INSTANCE_EXTEND, CMSG_SET_SELECTION, CMSG_SET_SHEATHED, CMSG_SET_SKILL_CHEAT, CMSG_SET_STAT_CHEAT, CMSG_SET_TAXI_BENCHMARK_MODE, CMSG_SET_TITLE, CMSG_SET_TITLE_SUFFIX, CMSG_SET_TRADE_GOLD, CMSG_SET_TRADE_ITEM, CMSG_SET_VEHICLE_REC_ID_ACK, CMSG_SET_WATCHED_FACTION, CMSG_SET_WORLDSTATE, CMSG_SETDEATHBINDPOINT, CMSG_SHOWING_CLOAK, CMSG_SHOWING_HELM, CMSG_SKILL_BUY_RANK, CMSG_SKILL_BUY_STEP, CMSG_SOCKET_GEMS, CMSG_SPELLCLICK, CMSG_SPIRIT_HEALER_ACTIVATE, CMSG_SPLIT_ITEM, CMSG_STABLE_PET, CMSG_STABLE_REVIVE_PET, CMSG_STABLE_SWAP_PET, CMSG_STANDSTATECHANGE, CMSG_START_BATTLEFIELD_CHEAT, CMSG_START_QUEST, CMSG_STOP_DANCE, CMSG_STORE_LOOT_IN_SLOT, CMSG_SUMMON_RESPONSE, CMSG_SUSPEND_COMMS_ACK, CMSG_SWAP_INV_ITEM, CMSG_SWAP_ITEM, CMSG_SYNC_DANCE, CMSG_TARGET_CAST, CMSG_TARGET_SCRIPT_CAST, CMSG_TAXICLEARALLNODES, CMSG_TAXICLEARNODE, CMSG_TAXIENABLEALLNODES, CMSG_TAXIENABLENODE, CMSG_TAXINODE_STATUS_QUERY, CMSG_TAXIQUERYAVAILABLENODES, CMSG_TAXISHOWNODES, CMSG_TELEPORT_TO_UNIT, CMSG_TEST_DROP_RATE, CMSG_TEXT_EMOTE, CMSG_TIME_SYNC_RESP, CMSG_TOGGLE_PVP, CMSG_TOGGLE_XP_GAIN, CMSG_TOTEM_DESTROYED, CMSG_TRAINER_BUY_SPELL, CMSG_TRAINER_LIST, CMSG_TRIGGER_CINEMATIC_CHEAT, CMSG_TURN_IN_PETITION, CMSG_TUTORIAL_CLEAR, CMSG_TUTORIAL_FLAG, CMSG_TUTORIAL_RESET, CMSG_UNACCEPT_TRADE, CMSG_UNCLAIM_LICENSE, CMSG_UNDRESSPLAYER, CMSG_UNITANIMTIER_CHEAT, CMSG_UNLEARN_DANCE_MOVE, CMSG_UNLEARN_SKILL, CMSG_UNLEARN_SPELL, CMSG_UNLEARN_TALENTS, CMSG_UNSTABLE_PET, CMSG_UNUSED5, CMSG_UNUSED6, CMSG_UPDATE_ACCOUNT_DATA, CMSG_UPDATE_MISSILE_TRAJECTORY, CMSG_UPDATE_PROJECTILE_POSITION, CMSG_USE_ITEM, CMSG_USE_SKILL_CHEAT, CMSG_VOICE_SESSION_ENABLE, CMSG_VOICE_SET_TALKER_MUTED_REQUEST, CMSG_WARDEN_DATA, CMSG_WEATHER_SPEED_CHEAT, CMSG_WHO, CMSG_WHOIS, CMSG_WORLD_STATE_UI_TIMER_UPDATE, CMSG_WORLD_TELEPORT, CMSG_WRAP_ITEM, CMSG_XP_CHEAT, CMSG_ZONE_MAP, CMSG_ZONEUPDATE, DEFINE_HANDLER, DEFINE_SERVER_OPCODE_HANDLER, WorldSession::Handle_EarlyProccess(), WorldSession::Handle_NULL(), WorldSession::HandleAcceptGrantLevel(), WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleActivateTaxiExpressOpcode(), WorldSession::HandleActivateTaxiOpcode(), WorldSession::HandleAddFriendOpcode(), WorldSession::HandleAddIgnoreOpcode(), WorldSession::HandleAlterAppearance(), WorldSession::HandleAreaSpiritHealerQueryOpcode(), WorldSession::HandleAreaSpiritHealerQueueOpcode(), WorldSession::HandleAreaTriggerOpcode(), WorldSession::HandleArenaTeamAcceptOpcode(), WorldSession::HandleArenaTeamDeclineOpcode(), WorldSession::HandleArenaTeamDisbandOpcode(), WorldSession::HandleArenaTeamInviteOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamLeaveOpcode(), WorldSession::HandleArenaTeamQueryOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), WorldSession::HandleArenaTeamRosterOpcode(), WorldSession::HandleAttackStopOpcode(), WorldSession::HandleAttackSwingOpcode(), WorldSession::HandleAuctionHelloOpcode(), WorldSession::HandleAuctionListBidderItems(), WorldSession::HandleAuctionListItems(), WorldSession::HandleAuctionListOwnerItems(), WorldSession::HandleAuctionListPendingSales(), WorldSession::HandleAuctionPlaceBid(), WorldSession::HandleAuctionRemoveItem(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleAutoBankItemOpcode(), WorldSession::HandleAutoEquipItemOpcode(), WorldSession::HandleAutoEquipItemSlotOpcode(), WorldSession::HandleAutoStoreBagItemOpcode(), WorldSession::HandleAutoStoreBankItemOpcode(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleBankerActivateOpcode(), WorldSession::HandleBattlefieldLeaveOpcode(), WorldSession::HandleBattlefieldListOpcode(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBattlefieldStatusOpcode(), WorldSession::HandleBattlegroundPlayerPositionsOpcode(), WorldSession::HandleBattlemasterHelloOpcode(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), WorldSession::HandleBeginTradeOpcode(), WorldSession::HandleBfEntryInviteResponse(), WorldSession::HandleBfExitRequest(), WorldSession::HandleBfQueueInviteResponse(), WorldSession::HandleBinderActivateOpcode(), WorldSession::HandleBugOpcode(), WorldSession::HandleBusyTradeOpcode(), WorldSession::HandleBuybackItem(), WorldSession::HandleBuyBankSlotOpcode(), WorldSession::HandleBuyItemInSlotOpcode(), WorldSession::HandleBuyItemOpcode(), WorldSession::HandleBuyStableSlot(), WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCalendarArenaTeam(), WorldSession::HandleCalendarComplain(), WorldSession::HandleCalendarCopyEvent(), WorldSession::HandleCalendarEventInvite(), WorldSession::HandleCalendarEventModeratorStatus(), WorldSession::HandleCalendarEventRemoveInvite(), WorldSession::HandleCalendarEventRsvp(), WorldSession::HandleCalendarEventSignup(), WorldSession::HandleCalendarEventStatus(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleCalendarGetEvent(), WorldSession::HandleCalendarGetNumPending(), WorldSession::HandleCalendarGuildFilter(), WorldSession::HandleCalendarRemoveEvent(), WorldSession::HandleCalendarUpdateEvent(), WorldSession::HandleCancelAuraOpcode(), WorldSession::HandleCancelAutoRepeatSpellOpcode(), WorldSession::HandleCancelCastOpcode(), WorldSession::HandleCancelChanneling(), WorldSession::HandleCancelGrowthAuraOpcode(), WorldSession::HandleCancelMountAuraOpcode(), WorldSession::HandleCancelTempEnchantmentOpcode(), WorldSession::HandleCancelTradeOpcode(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleChannelAnnouncements(), WorldSession::HandleChannelBan(), WorldSession::HandleChannelDeclineInvite(), WorldSession::HandleChannelDisplayListQuery(), WorldSession::HandleChannelInvite(), WorldSession::HandleChannelKick(), WorldSession::HandleChannelList(), WorldSession::HandleChannelModerateOpcode(), WorldSession::HandleChannelModerator(), WorldSession::HandleChannelMute(), WorldSession::HandleChannelOwner(), WorldSession::HandleChannelPassword(), WorldSession::HandleChannelSetOwner(), WorldSession::HandleChannelUnban(), WorldSession::HandleChannelUnmoderator(), WorldSession::HandleChannelUnmute(), WorldSession::HandleChannelVoiceOnOpcode(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomize(), WorldSession::HandleCharDeleteOpcode(), WorldSession::HandleCharEnumOpcode(), WorldSession::HandleCharFactionOrRaceChange(), WorldSession::HandleCharRenameOpcode(), WorldSession::HandleChatIgnoredOpcode(), WorldSession::HandleClearChannelWatch(), WorldSession::HandleClearTradeItemOpcode(), WorldSession::HandleComplainOpcode(), WorldSession::HandleCompleteCinematic(), WorldSession::HandleContactListOpcode(), WorldSession::HandleCorpseMapPositionQuery(), WorldSession::HandleCorpseQueryOpcode(), WorldSession::HandleCreatureQueryOpcode(), WorldSession::HandleDelFriendOpcode(), WorldSession::HandleDelIgnoreOpcode(), WorldSession::HandleDestroyItemOpcode(), WorldSession::HandleDismissControlledVehicle(), WorldSession::HandleDismissCritter(), WorldSession::HandleDuelAcceptedOpcode(), WorldSession::HandleDuelCancelledOpcode(), WorldSession::HandleEjectPassenger(), WorldSession::HandleEmoteOpcode(), WorldSession::HandleEnterPlayerVehicle(), WorldSession::HandleEquipmentSetDelete(), WorldSession::HandleEquipmentSetSave(), WorldSession::HandleEquipmentSetUse(), WorldSession::HandleFarSightOpcode(), WorldSession::HandleFeatherFallAck(), WorldSession::HandleForceSpeedChangeAck(), WorldSession::HandleGameObjectQueryOpcode(), WorldSession::HandleGameobjectReportUse(), WorldSession::HandleGameObjectUseOpcode(), WorldSession::HandleGetChannelMemberCount(), WorldSession::HandleGetMailList(), WorldSession::HandleGMResponseResolve(), WorldSession::HandleGMSurveySubmit(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleGMTicketDeleteOpcode(), WorldSession::HandleGMTicketGetTicketOpcode(), WorldSession::HandleGMTicketSystemStatusOpcode(), WorldSession::HandleGMTicketUpdateOpcode(), WorldSession::HandleGossipHelloOpcode(), WorldSession::HandleGossipSelectOptionOpcode(), WorldSession::HandleGrantLevel(), WorldSession::HandleGroupAcceptOpcode(), WorldSession::HandleGroupAssistantLeaderOpcode(), WorldSession::HandleGroupChangeSubGroupOpcode(), WorldSession::HandleGroupDeclineOpcode(), WorldSession::HandleGroupDisbandOpcode(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGroupRaidConvertOpcode(), WorldSession::HandleGroupSetLeaderOpcode(), WorldSession::HandleGroupSwapSubGroupOpcode(), WorldSession::HandleGroupUninviteGuidOpcode(), WorldSession::HandleGroupUninviteOpcode(), WorldSession::HandleGuildAcceptOpcode(), WorldSession::HandleGuildAddRankOpcode(), WorldSession::HandleGuildBankBuyTab(), WorldSession::HandleGuildBankDepositMoney(), WorldSession::HandleGuildBankerActivate(), WorldSession::HandleGuildBankLogQuery(), WorldSession::HandleGuildBankMoneyWithdrawn(), WorldSession::HandleGuildBankQueryTab(), WorldSession::HandleGuildBankSwapItems(), WorldSession::HandleGuildBankUpdateTab(), WorldSession::HandleGuildBankWithdrawMoney(), WorldSession::HandleGuildChangeInfoTextOpcode(), WorldSession::HandleGuildCreateOpcode(), WorldSession::HandleGuildDeclineOpcode(), WorldSession::HandleGuildDelRankOpcode(), WorldSession::HandleGuildDemoteOpcode(), WorldSession::HandleGuildDisbandOpcode(), WorldSession::HandleGuildEventLogQueryOpcode(), WorldSession::HandleGuildInfoOpcode(), WorldSession::HandleGuildInviteOpcode(), WorldSession::HandleGuildLeaderOpcode(), WorldSession::HandleGuildLeaveOpcode(), WorldSession::HandleGuildMOTDOpcode(), WorldSession::HandleGuildPermissions(), WorldSession::HandleGuildPromoteOpcode(), WorldSession::HandleGuildQueryOpcode(), WorldSession::HandleGuildRankOpcode(), WorldSession::HandleGuildRemoveOpcode(), WorldSession::HandleGuildRosterOpcode(), WorldSession::HandleGuildSetOfficerNoteOpcode(), WorldSession::HandleGuildSetPublicNoteOpcode(), WorldSession::HandleHearthAndResurrect(), WorldSession::HandleIgnoreTradeOpcode(), WorldSession::HandleInitiateTradeOpcode(), WorldSession::HandleInspectArenaTeamsOpcode(), WorldSession::HandleInspectHonorStatsOpcode(), WorldSession::HandleInspectOpcode(), WorldSession::HandleInstanceLockResponse(), WorldSession::HandleItemNameQueryOpcode(), WorldSession::HandleItemQuerySingleOpcode(), WorldSession::HandleItemRefund(), WorldSession::HandleItemRefundInfoRequest(), WorldSession::HandleItemTextQuery(), WorldSession::HandleJoinChannel(), WorldSession::HandleLearnPreviewTalents(), WorldSession::HandleLearnPreviewTalentsPet(), WorldSession::HandleLearnTalentOpcode(), WorldSession::HandleLeaveChannel(), WorldSession::HandleLfgGetStatus(), WorldSession::HandleLfgJoinOpcode(), WorldSession::HandleLfgLeaveOpcode(), WorldSession::HandleLfgPartyLockInfoRequestOpcode(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), WorldSession::HandleLfgProposalResultOpcode(), WorldSession::HandleLfgSetBootVoteOpcode(), WorldSession::HandleLfgSetCommentOpcode(), WorldSession::HandleLfgSetRolesOpcode(), WorldSession::HandleLfgTeleportOpcode(), WorldSession::HandleLfrSearchJoinOpcode(), WorldSession::HandleLfrSearchLeaveOpcode(), WorldSession::HandleListInventoryOpcode(), WorldSession::HandleListStabledPetsOpcode(), WorldSession::HandleLogoutCancelOpcode(), WorldSession::HandleLogoutRequestOpcode(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleLootMethodOpcode(), WorldSession::HandleLootMoneyOpcode(), WorldSession::HandleLootOpcode(), WorldSession::HandleLootReleaseOpcode(), WorldSession::HandleLootRoll(), WorldSession::HandleMailCreateTextItem(), WorldSession::HandleMailDelete(), WorldSession::HandleMailMarkAsRead(), WorldSession::HandleMailReturnToSender(), WorldSession::HandleMailTakeItem(), WorldSession::HandleMailTakeMoney(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleMinimapPingOpcode(), WorldSession::HandleMirrorImageDataRequest(), WorldSession::HandleMountSpecialAnimOpcode(), WorldSession::HandleMoveHoverAck(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveNotActiveMover(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveSetCanFlyAckOpcode(), WorldSession::HandleMoveSplineDoneOpcode(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveTimeSkippedOpcode(), WorldSession::HandleMoveUnRootAck(), WorldSession::HandleMoveWaterWalkAck(), WorldSession::HandleMoveWorldportAckOpcode(), WorldSession::HandleNameQueryOpcode(), WorldSession::HandleNextCinematicCamera(), WorldSession::HandleNpcTextQueryOpcode(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandleOptOutOfLootOpcode(), WorldSession::HandlePageTextQueryOpcode(), WorldSession::HandlePartyAssignmentOpcode(), WorldSession::HandlePetAbandon(), WorldSession::HandlePetAction(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionDeclineOpcode(), WorldSession::HandlePetitionQueryOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetitionShowListOpcode(), WorldSession::HandlePetitionShowSignOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandlePetLearnTalent(), WorldSession::HandlePetNameQuery(), WorldSession::HandlePetRename(), WorldSession::HandlePetSetAction(), WorldSession::HandlePetSpellAutocastOpcode(), WorldSession::HandlePetStopAttack(), WorldSession::HandlePlayedTime(), WorldSession::HandlePlayerLoginOpcode(), WorldSession::HandlePlayerLogoutOpcode(), WorldSession::HandlePushQuestToParty(), WorldSession::HandlePVPLogDataOpcode(), WorldSession::HandleQueryGuildBankTabText(), WorldSession::HandleQueryInspectAchievements(), WorldSession::HandleQueryNextMailTime(), WorldSession::HandleQueryQuestsCompleted(), WorldSession::HandleQueryTimeOpcode(), WorldSession::HandleQuestConfirmAccept(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestgiverCancel(), WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverCompleteQuest(), WorldSession::HandleQuestgiverHelloOpcode(), WorldSession::HandleQuestgiverQueryQuestOpcode(), WorldSession::HandleQuestgiverQuestAutoLaunch(), WorldSession::HandleQuestgiverRequestRewardOpcode(), WorldSession::HandleQuestgiverStatusMultipleQuery(), WorldSession::HandleQuestgiverStatusQueryOpcode(), WorldSession::HandleQuestLogRemoveQuest(), WorldSession::HandleQuestLogSwapQuest(), WorldSession::HandleQuestPOIQuery(), WorldSession::HandleQuestPushResult(), WorldSession::HandleQuestQueryOpcode(), WorldSession::HandleRaidReadyCheckFinishedOpcode(), WorldSession::HandleRaidReadyCheckOpcode(), WorldSession::HandleRaidTargetUpdateOpcode(), WorldSession::HandleRandomRollOpcode(), WorldSession::HandleReadItem(), WorldSession::HandleReadyForAccountDataTimes(), WorldSession::HandleRealmSplitOpcode(), WorldSession::HandleReclaimCorpseOpcode(), WorldSession::HandleRemoveGlyph(), WorldSession::HandleRepairItemOpcode(), WorldSession::HandleRepopRequestOpcode(), WorldSession::HandleReportLag(), WorldSession::HandleReportPvPAFK(), WorldSession::HandleRequestAccountData(), WorldSession::HandleRequestPartyMemberStatsOpcode(), WorldSession::HandleRequestPetInfo(), WorldSession::HandleRequestRaidInfoOpcode(), WorldSession::HandleRequestVehicleExit(), WorldSession::HandleResetInstancesOpcode(), WorldSession::HandleResurrectResponseOpcode(), WorldSession::HandleSaveGuildEmblemOpcode(), WorldSession::HandleSelfResOpcode(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleSetActionBarToggles(), WorldSession::HandleSetActionButtonOpcode(), WorldSession::HandleSetActiveMoverOpcode(), WorldSession::HandleSetActiveVoiceChannel(), WorldSession::HandleSetAmmoOpcode(), WorldSession::HandleSetChannelWatch(), WorldSession::HandleSetContactNotesOpcode(), WorldSession::HandleSetDungeonDifficultyOpcode(), WorldSession::HandleSetFactionAtWar(), WorldSession::HandleSetFactionCheat(), WorldSession::HandleSetFactionInactiveOpcode(), WorldSession::HandleSetGuildBankTabText(), WorldSession::HandleSetPlayerDeclinedNames(), WorldSession::HandleSetRaidDifficultyOpcode(), WorldSession::HandleSetSavedInstanceExtend(), WorldSession::HandleSetSelectionOpcode(), WorldSession::HandleSetSheathedOpcode(), WorldSession::HandleSetTaxiBenchmarkOpcode(), WorldSession::HandleSetTitleOpcode(), WorldSession::HandleSetTradeGoldOpcode(), WorldSession::HandleSetTradeItemOpcode(), WorldSession::HandleSetWatchedFactionOpcode(), WorldSession::HandleShowingCloakOpcode(), WorldSession::HandleShowingHelmOpcode(), WorldSession::HandleSocketOpcode(), WorldSession::HandleSpellClick(), WorldSession::HandleSpiritHealerActivateOpcode(), WorldSession::HandleSplitItemOpcode(), WorldSession::HandleStablePet(), WorldSession::HandleStableRevivePet(), WorldSession::HandleStableSwapPet(), WorldSession::HandleStandStateChangeOpcode(), WorldSession::HandleSummonResponseOpcode(), WorldSession::HandleSwapInvItemOpcode(), WorldSession::HandleSwapItem(), WorldSession::HandleTabardVendorActivateOpcode(), WorldSession::HandleTalentWipeConfirmOpcode(), WorldSession::HandleTaxiNodeStatusQueryOpcode(), WorldSession::HandleTaxiQueryAvailableNodes(), WorldSession::HandleTextEmoteOpcode(), WorldSession::HandleTimeSyncResp(), WorldSession::HandleTogglePvP(), WorldSession::HandleTotemDestroyed(), WorldSession::HandleTrainerBuySpellOpcode(), WorldSession::HandleTrainerListOpcode(), WorldSession::HandleTurnInPetitionOpcode(), WorldSession::HandleTutorialClear(), WorldSession::HandleTutorialFlag(), WorldSession::HandleTutorialReset(), WorldSession::HandleUnacceptTradeOpcode(), WorldSession::HandleUnlearnSkillOpcode(), WorldSession::HandleUnstablePet(), WorldSession::HandleUpdateAccountData(), WorldSession::HandleUpdateMissileTrajectory(), WorldSession::HandleUpdateProjectilePosition(), WorldSession::HandleUseItemOpcode(), WorldSession::HandleVoiceSessionEnableOpcode(), WorldSession::HandleWardenDataOpcode(), WorldSession::HandleWhoisOpcode(), WorldSession::HandleWhoOpcode(), WorldSession::HandleWorldStateUITimerUpdate(), WorldSession::HandleWorldTeleportOpcode(), WorldSession::HandleWrapItemOpcode(), WorldSession::HandleZoneUpdateOpcode(), MSG_AUCTION_HELLO, MSG_BATTLEGROUND_PLAYER_POSITIONS, MSG_CHANNEL_START, MSG_CHANNEL_UPDATE, MSG_CORPSE_QUERY, MSG_DELAY_GHOST_TELEPORT, MSG_DEV_SHOWLABEL, MSG_GM_ACCOUNT_ONLINE, MSG_GM_BIND_OTHER, MSG_GM_CHANGE_ARENA_RATING, MSG_GM_DESTROY_CORPSE, MSG_GM_GEARRATING, MSG_GM_RESETINSTANCELIMIT, MSG_GM_SHOWLABEL, MSG_GM_SUMMON, MSG_GUILD_BANK_LOG_QUERY, MSG_GUILD_BANK_MONEY_WITHDRAWN, MSG_GUILD_EVENT_LOG_QUERY, MSG_GUILD_PERMISSIONS, MSG_INSPECT_ARENA_TEAMS, MSG_INSPECT_HONOR_STATS, MSG_LIST_STABLED_PETS, MSG_MINIMAP_PING, MSG_MOVE_FALL_LAND, MSG_MOVE_FEATHER_FALL, MSG_MOVE_GRAVITY_CHNG, MSG_MOVE_HEARTBEAT, MSG_MOVE_HOVER, MSG_MOVE_JUMP, MSG_MOVE_KNOCK_BACK, MSG_MOVE_ROOT, MSG_MOVE_SET_ALL_SPEED_CHEAT, MSG_MOVE_SET_COLLISION_HGT, MSG_MOVE_SET_FACING, MSG_MOVE_SET_FLIGHT_BACK_SPEED, MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT, MSG_MOVE_SET_FLIGHT_SPEED, MSG_MOVE_SET_FLIGHT_SPEED_CHEAT, MSG_MOVE_SET_PITCH, MSG_MOVE_SET_PITCH_RATE, MSG_MOVE_SET_PITCH_RATE_CHEAT, MSG_MOVE_SET_RUN_BACK_SPEED, MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT, MSG_MOVE_SET_RUN_MODE, MSG_MOVE_SET_RUN_SPEED, MSG_MOVE_SET_RUN_SPEED_CHEAT, MSG_MOVE_SET_SWIM_BACK_SPEED, MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT, MSG_MOVE_SET_SWIM_SPEED, MSG_MOVE_SET_SWIM_SPEED_CHEAT, MSG_MOVE_SET_TURN_RATE, MSG_MOVE_SET_TURN_RATE_CHEAT, MSG_MOVE_SET_WALK_MODE, MSG_MOVE_SET_WALK_SPEED, MSG_MOVE_SET_WALK_SPEED_CHEAT, MSG_MOVE_START_ASCEND, MSG_MOVE_START_BACKWARD, MSG_MOVE_START_DESCEND, MSG_MOVE_START_FORWARD, MSG_MOVE_START_PITCH_DOWN, MSG_MOVE_START_PITCH_UP, MSG_MOVE_START_STRAFE_LEFT, MSG_MOVE_START_STRAFE_RIGHT, MSG_MOVE_START_SWIM, MSG_MOVE_START_SWIM_CHEAT, MSG_MOVE_START_TURN_LEFT, MSG_MOVE_START_TURN_RIGHT, MSG_MOVE_STOP, MSG_MOVE_STOP_ASCEND, MSG_MOVE_STOP_PITCH, MSG_MOVE_STOP_STRAFE, MSG_MOVE_STOP_SWIM, MSG_MOVE_STOP_SWIM_CHEAT, MSG_MOVE_STOP_TURN, MSG_MOVE_TELEPORT, MSG_MOVE_TELEPORT_ACK, MSG_MOVE_TELEPORT_CHEAT, MSG_MOVE_TIME_SKIPPED, MSG_MOVE_TOGGLE_COLLISION_CHEAT, MSG_MOVE_TOGGLE_FALL_LOGGING, MSG_MOVE_TOGGLE_LOGGING, MSG_MOVE_UNROOT, MSG_MOVE_UPDATE_CAN_FLY, MSG_MOVE_UPDATE_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY, MSG_MOVE_WATER_WALK, MSG_MOVE_WORLDPORT_ACK, MSG_NOTIFY_PARTY_SQUELCH, MSG_PARTY_ASSIGNMENT, MSG_PETITION_DECLINE, MSG_PETITION_RENAME, MSG_PVP_LOG_DATA, MSG_QUERY_GUILD_BANK_TEXT, MSG_QUERY_NEXT_MAIL_TIME, MSG_QUEST_PUSH_RESULT, MSG_RAID_READY_CHECK, MSG_RAID_READY_CHECK_CONFIRM, MSG_RAID_READY_CHECK_FINISHED, MSG_RAID_TARGET_UPDATE, MSG_RANDOM_ROLL, MSG_SAVE_GUILD_EMBLEM, MSG_SET_DUNGEON_DIFFICULTY, MSG_SET_RAID_DIFFICULTY, MSG_TABARDVENDOR_ACTIVATE, MSG_TALENT_WIPE_CONFIRM, MSG_VIEW_PHASE_SHIFT, PROCESS_INPLACE, PROCESS_THREADSAFE, PROCESS_THREADUNSAFE, SMSG_ACCOUNT_DATA_TIMES, SMSG_ACHIEVEMENT_DELETED, SMSG_ACHIEVEMENT_EARNED, SMSG_ACTION_BUTTONS, SMSG_ACTIVATETAXIREPLY, SMSG_ADD_RUNE_POWER, SMSG_ADDON_INFO, SMSG_AFK_MONITOR_INFO_RESPONSE, SMSG_AI_REACTION, SMSG_ALL_ACHIEVEMENT_DATA, SMSG_AREA_SPIRIT_HEALER_TIME, SMSG_AREA_TRIGGER_MESSAGE, SMSG_ARENA_ERROR, SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED, SMSG_ARENA_TEAM_COMMAND_RESULT, SMSG_ARENA_TEAM_EVENT, SMSG_ARENA_TEAM_INVITE, SMSG_ARENA_TEAM_QUERY_RESPONSE, SMSG_ARENA_TEAM_ROSTER, SMSG_ARENA_TEAM_STATS, SMSG_ARENA_UNIT_DESTROYED, SMSG_ATTACKERSTATEUPDATE, SMSG_ATTACKSTART, SMSG_ATTACKSTOP, SMSG_ATTACKSWING_BADFACING, SMSG_ATTACKSWING_CANT_ATTACK, SMSG_ATTACKSWING_DEADTARGET, SMSG_ATTACKSWING_NOTINRANGE, SMSG_AUCTION_BIDDER_LIST_RESULT, SMSG_AUCTION_BIDDER_NOTIFICATION, SMSG_AUCTION_COMMAND_RESULT, SMSG_AUCTION_LIST_PENDING_SALES, SMSG_AUCTION_LIST_RESULT, SMSG_AUCTION_OWNER_LIST_RESULT, SMSG_AUCTION_OWNER_NOTIFICATION, SMSG_AUCTION_REMOVED_NOTIFICATION, SMSG_AURA_UPDATE, SMSG_AURA_UPDATE_ALL, SMSG_AURACASTLOG, SMSG_AUTH_CHALLENGE, SMSG_AUTH_RESPONSE, SMSG_AUTH_SRP6_RESPONSE, SMSG_AVAILABLE_VOICE_CHANNEL, SMSG_BARBER_SHOP_RESULT, SMSG_BATTLEFIELD_LIST, SMSG_BATTLEFIELD_MGR_EJECT_PENDING, SMSG_BATTLEFIELD_MGR_EJECTED, SMSG_BATTLEFIELD_MGR_ENTERED, SMSG_BATTLEFIELD_MGR_ENTRY_INVITE, SMSG_BATTLEFIELD_MGR_QUEUE_INVITE, SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE, SMSG_BATTLEFIELD_MGR_STATE_CHANGE, SMSG_BATTLEFIELD_PORT_DENIED, SMSG_BATTLEFIELD_STATUS, SMSG_BATTLEGROUND_INFO_THROTTLED, SMSG_BATTLEGROUND_PLAYER_JOINED, SMSG_BATTLEGROUND_PLAYER_LEFT, SMSG_BINDER_CONFIRM, SMSG_BINDPOINTUPDATE, SMSG_BINDZONEREPLY, SMSG_BREAK_TARGET, SMSG_BUY_BANK_SLOT_RESULT, SMSG_BUY_FAILED, SMSG_BUY_ITEM, SMSG_CALENDAR_ARENA_TEAM, SMSG_CALENDAR_CLEAR_PENDING_ACTION, SMSG_CALENDAR_COMMAND_RESULT, SMSG_CALENDAR_EVENT_INVITE, SMSG_CALENDAR_EVENT_INVITE_ALERT, SMSG_CALENDAR_EVENT_INVITE_NOTES, SMSG_CALENDAR_EVENT_INVITE_NOTES_ALERT, SMSG_CALENDAR_EVENT_INVITE_REMOVED, SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT, SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT, SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT, SMSG_CALENDAR_EVENT_REMOVED_ALERT, SMSG_CALENDAR_EVENT_STATUS, SMSG_CALENDAR_EVENT_UPDATED_ALERT, SMSG_CALENDAR_FILTER_GUILD, SMSG_CALENDAR_RAID_LOCKOUT_ADDED, SMSG_CALENDAR_RAID_LOCKOUT_REMOVED, SMSG_CALENDAR_RAID_LOCKOUT_UPDATED, SMSG_CALENDAR_SEND_CALENDAR, SMSG_CALENDAR_SEND_EVENT, SMSG_CALENDAR_SEND_NUM_PENDING, SMSG_CAMERA_SHAKE, SMSG_CANCEL_AUTO_REPEAT, SMSG_CANCEL_COMBAT, SMSG_CAST_FAILED, SMSG_CHANGEPLAYER_DIFFICULTY_RESULT, SMSG_CHANNEL_LIST, SMSG_CHANNEL_MEMBER_COUNT, SMSG_CHANNEL_NOTIFY, SMSG_CHAR_CREATE, SMSG_CHAR_CUSTOMIZE, SMSG_CHAR_DELETE, SMSG_CHAR_ENUM, SMSG_CHAR_FACTION_CHANGE, SMSG_CHAR_RENAME, SMSG_CHARACTER_LOGIN_FAILED, SMSG_CHARACTER_PROFILE, SMSG_CHARACTER_PROFILE_REALM_CONNECTED, SMSG_CHAT_NOT_IN_PARTY, SMSG_CHAT_PLAYER_AMBIGUOUS, SMSG_CHAT_PLAYER_NOT_FOUND, SMSG_CHAT_RESTRICTED, SMSG_CHAT_SERVER_MESSAGE, SMSG_CHAT_WRONG_FACTION, SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE, SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE, SMSG_CHEAT_PLAYER_LOOKUP, SMSG_CHECK_FOR_BOTS, SMSG_CLEAR_COOLDOWN, SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE, SMSG_CLEAR_FAR_SIGHT_IMMEDIATE, SMSG_CLEAR_TARGET, SMSG_CLIENT_CONTROL_UPDATE, SMSG_CLIENTCACHE_VERSION, SMSG_COMBAT_EVENT_FAILED, SMSG_COMMENTATOR_GET_PLAYER_INFO, SMSG_COMMENTATOR_MAP_INFO, SMSG_COMMENTATOR_PLAYER_INFO, SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT1, SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT2, SMSG_COMMENTATOR_STATE_CHANGED, SMSG_COMPLAIN_RESULT, SMSG_COMPRESSED_MOVES, SMSG_COMPRESSED_UPDATE_OBJECT, SMSG_COMSAT_CONNECT_FAIL, SMSG_COMSAT_DISCONNECT, SMSG_COMSAT_RECONNECT_TRY, SMSG_CONTACT_LIST, SMSG_CONVERT_RUNE, SMSG_COOLDOWN_CHEAT, SMSG_COOLDOWN_EVENT, SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE, SMSG_CORPSE_NOT_IN_INSTANCE, SMSG_CORPSE_RECLAIM_DELAY, SMSG_CREATURE_QUERY_RESPONSE, SMSG_CRITERIA_DELETED, SMSG_CRITERIA_UPDATE, SMSG_CROSSED_INEBRIATION_THRESHOLD, SMSG_DAMAGE_CALC_LOG, SMSG_DANCE_QUERY_RESPONSE, SMSG_DBLOOKUP, SMSG_DEATH_RELEASE_LOC, SMSG_DEBUG_AISTATE, SMSG_DEBUG_LIST_TARGETS, SMSG_DEBUG_SERVER_GEO, SMSG_DEBUGAURAPROC, SMSG_DEFENSE_MESSAGE, SMSG_DESTROY_OBJECT, SMSG_DESTRUCTIBLE_BUILDING_DAMAGE, SMSG_DISMOUNT, SMSG_DISMOUNTRESULT, SMSG_DISPEL_FAILED, SMSG_DUEL_COMPLETE, SMSG_DUEL_COUNTDOWN, SMSG_DUEL_INBOUNDS, SMSG_DUEL_OUTOFBOUNDS, SMSG_DUEL_REQUESTED, SMSG_DUEL_WINNER, SMSG_DUMP_OBJECTS_DATA, SMSG_DURABILITY_DAMAGE_DEATH, SMSG_DYNAMIC_DROP_ROLL_RESULT, SMSG_ECHO_PARTY_SQUELCH, SMSG_EMOTE, SMSG_ENABLE_BARBER_SHOP, SMSG_ENCHANTMENTLOG, SMSG_ENVIRONMENTAL_DAMAGE_LOG, SMSG_EQUIPMENT_SET_LIST, SMSG_EQUIPMENT_SET_SAVED, SMSG_EQUIPMENT_SET_USE_RESULT, SMSG_EXPECTED_SPAM_RECORDS, SMSG_EXPLORATION_EXPERIENCE, SMSG_FEATURE_SYSTEM_STATUS, SMSG_FEIGN_DEATH_RESISTED, SMSG_FISH_ESCAPED, SMSG_FISH_NOT_HOOKED, SMSG_FLIGHT_SPLINE_SYNC, SMSG_FORCE_ANIM, SMSG_FORCE_DISPLAY_UPDATE, SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE, SMSG_FORCE_FLIGHT_SPEED_CHANGE, SMSG_FORCE_MOVE_ROOT, SMSG_FORCE_MOVE_UNROOT, SMSG_FORCE_PITCH_RATE_CHANGE, SMSG_FORCE_RUN_BACK_SPEED_CHANGE, SMSG_FORCE_RUN_SPEED_CHANGE, SMSG_FORCE_SEND_QUEUED_PACKETS, SMSG_FORCE_SET_VEHICLE_REC_ID, SMSG_FORCE_SWIM_BACK_SPEED_CHANGE, SMSG_FORCE_SWIM_SPEED_CHANGE, SMSG_FORCE_TURN_RATE_CHANGE, SMSG_FORCE_WALK_SPEED_CHANGE, SMSG_FORCEACTIONSHOW, SMSG_FORCED_DEATH_UPDATE, SMSG_FRIEND_STATUS, SMSG_GAMEOBJECT_CUSTOM_ANIM, SMSG_GAMEOBJECT_DESPAWN_ANIM, SMSG_GAMEOBJECT_PAGETEXT, SMSG_GAMEOBJECT_QUERY_RESPONSE, SMSG_GAMEOBJECT_RESET_STATE, SMSG_GAMESPEED_SET, SMSG_GAMETIME_SET, SMSG_GAMETIME_UPDATE, SMSG_GAMETIMEBIAS_SET, SMSG_GHOSTEE_GONE, SMSG_GM_MESSAGECHAT, SMSG_GM_PLAYER_INFO, SMSG_GM_TICKET_STATUS_UPDATE, SMSG_GMRESPONSE_CREATE_TICKET, SMSG_GMRESPONSE_DB_ERROR, SMSG_GMRESPONSE_RECEIVED, SMSG_GMRESPONSE_STATUS_UPDATE, SMSG_GMTICKET_CREATE, SMSG_GMTICKET_DELETETICKET, SMSG_GMTICKET_GETTICKET, SMSG_GMTICKET_SYSTEMSTATUS, SMSG_GMTICKET_UPDATETEXT, SMSG_GODMODE, SMSG_GOGOGO_OBSOLETE, SMSG_GOSSIP_COMPLETE, SMSG_GOSSIP_MESSAGE, SMSG_GOSSIP_POI, SMSG_GROUP_CANCEL, SMSG_GROUP_DECLINE, SMSG_GROUP_DESTROYED, SMSG_GROUP_INVITE, SMSG_GROUP_JOINED_BATTLEGROUND, SMSG_GROUP_LIST, SMSG_GROUP_SET_LEADER, SMSG_GROUP_UNINVITE, SMSG_GROUPACTION_THROTTLED, SMSG_GUILD_BANK_LIST, SMSG_GUILD_COMMAND_RESULT, SMSG_GUILD_DECLINE, SMSG_GUILD_EVENT, SMSG_GUILD_INFO, SMSG_GUILD_INVITE, SMSG_GUILD_QUERY_RESPONSE, SMSG_GUILD_ROSTER, SMSG_HEALTH_UPDATE, SMSG_HIGHEST_THREAT_UPDATE, SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT, SMSG_IGNORE_REQUIREMENTS_CHEAT, SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE, SMSG_INIT_WORLD_STATES, SMSG_INITIAL_SPELLS, SMSG_INITIALIZE_FACTIONS, SMSG_INSPECT_RESULTS_UPDATE, SMSG_INSPECT_TALENT, SMSG_INSTANCE_DIFFICULTY, SMSG_INSTANCE_LOCK_WARNING_QUERY, SMSG_INSTANCE_RESET, SMSG_INSTANCE_RESET_FAILED, SMSG_INSTANCE_SAVE_CREATED, SMSG_INVALID_PROMOTION_CODE, SMSG_INVALIDATE_DANCE, SMSG_INVALIDATE_PLAYER, SMSG_INVENTORY_CHANGE_FAILURE, SMSG_ITEM_COOLDOWN, SMSG_ITEM_ENCHANT_TIME_UPDATE, SMSG_ITEM_NAME_QUERY_RESPONSE, SMSG_ITEM_PUSH_RESULT, SMSG_ITEM_QUERY_MULTIPLE_RESPONSE, SMSG_ITEM_QUERY_SINGLE_RESPONSE, SMSG_ITEM_REFUND_INFO_RESPONSE, SMSG_ITEM_REFUND_RESULT, SMSG_ITEM_TEXT_QUERY_RESPONSE, SMSG_ITEM_TIME_UPDATE, SMSG_JOINED_BATTLEGROUND_QUEUE, SMSG_KICK_REASON, SMSG_LEARNED_DANCE_MOVES, SMSG_LEARNED_SPELL, SMSG_LEVELUP_INFO, SMSG_LFG_BOOT_PROPOSAL_UPDATE, SMSG_LFG_DISABLED, SMSG_LFG_JOIN_RESULT, SMSG_LFG_OFFER_CONTINUE, SMSG_LFG_PARTY_INFO, SMSG_LFG_PLAYER_INFO, SMSG_LFG_PLAYER_REWARD, SMSG_LFG_PROPOSAL_UPDATE, SMSG_LFG_QUEUE_STATUS, SMSG_LFG_ROLE_CHECK_UPDATE, SMSG_LFG_ROLE_CHOSEN, SMSG_LFG_TELEPORT_DENIED, SMSG_LFG_UPDATE_PARTY, SMSG_LFG_UPDATE_PLAYER, SMSG_LFG_UPDATE_SEARCH, SMSG_LIST_INVENTORY, SMSG_LOG_XPGAIN, SMSG_LOGIN_SETTIMESPEED, SMSG_LOGIN_VERIFY_WORLD, SMSG_LOGOUT_CANCEL_ACK, SMSG_LOGOUT_COMPLETE, SMSG_LOGOUT_RESPONSE, SMSG_LOOT_ALL_PASSED, SMSG_LOOT_CLEAR_MONEY, SMSG_LOOT_ITEM_NOTIFY, SMSG_LOOT_LIST, SMSG_LOOT_MASTER_LIST, SMSG_LOOT_MONEY_NOTIFY, SMSG_LOOT_RELEASE_RESPONSE, SMSG_LOOT_REMOVED, SMSG_LOOT_RESPONSE, SMSG_LOOT_ROLL, SMSG_LOOT_ROLL_WON, SMSG_LOOT_SLOT_CHANGED, SMSG_LOOT_START_ROLL, SMSG_LOTTERY_QUERY_RESULT_OBSOLETE, SMSG_LOTTERY_RESULT_OBSOLETE, SMSG_MAIL_LIST_RESULT, SMSG_MESSAGECHAT, SMSG_MINIGAME_MOVE_FAILED, SMSG_MINIGAME_SETUP, SMSG_MINIGAME_STATE, SMSG_MIRRORIMAGE_DATA, SMSG_MODIFY_COOLDOWN, SMSG_MONSTER_MOVE, SMSG_MONSTER_MOVE_TRANSPORT, SMSG_MOTD, SMSG_MOUNTRESULT, SMSG_MOUNTSPECIAL_ANIM, SMSG_MOVE_CHARACTER_CHEAT, SMSG_MOVE_FEATHER_FALL, SMSG_MOVE_GRAVITY_DISABLE, SMSG_MOVE_GRAVITY_ENABLE, SMSG_MOVE_KNOCK_BACK, SMSG_MOVE_LAND_WALK, SMSG_MOVE_NORMAL_FALL, SMSG_MOVE_SET_CAN_FLY, SMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY, SMSG_MOVE_SET_COLLISION_HGT, SMSG_MOVE_SET_HOVER, SMSG_MOVE_UNSET_CAN_FLY, SMSG_MOVE_UNSET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY, SMSG_MOVE_UNSET_HOVER, SMSG_MOVE_WATER_WALK, SMSG_MULTIPLE_MOVES, SMSG_MULTIPLE_PACKETS, SMSG_NAME_QUERY_RESPONSE, SMSG_NEW_TAXI_PATH, SMSG_NEW_WORLD, SMSG_NOTIFICATION, SMSG_NOTIFY_DANCE, SMSG_NOTIFY_DEST_LOC_SPELL_CAST, SMSG_NPC_TEXT_UPDATE, SMSG_NPC_WONT_TALK, SMSG_OFFER_PETITION_ERROR, SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA, SMSG_OPEN_CONTAINER, SMSG_OPEN_LFG_DUNGEON_FINDER, SMSG_OVERRIDE_LIGHT, SMSG_PAGE_TEXT_QUERY_RESPONSE, SMSG_PARTY_COMMAND_RESULT, SMSG_PARTY_MEMBER_STATS, SMSG_PARTY_MEMBER_STATS_FULL, SMSG_PARTYKILLLOG, SMSG_PAUSE_MIRROR_TIMER, SMSG_PERIODICAURALOG, SMSG_PET_ACTION_FEEDBACK, SMSG_PET_ACTION_SOUND, SMSG_PET_BROKEN, SMSG_PET_CAST_FAILED, SMSG_PET_DISMISS_SOUND, SMSG_PET_GUIDS, SMSG_PET_LEARNED_SPELL, SMSG_PET_MODE, SMSG_PET_NAME_INVALID, SMSG_PET_NAME_QUERY_RESPONSE, SMSG_PET_RENAMEABLE, SMSG_PET_SPELLS, SMSG_PET_TAME_FAILURE, SMSG_PET_UNLEARN_CONFIRM, SMSG_PET_UNLEARNED_SPELL, SMSG_PET_UPDATE_COMBO_POINTS, SMSG_PETGODMODE, SMSG_PETITION_QUERY_RESPONSE, SMSG_PETITION_SHOW_SIGNATURES, SMSG_PETITION_SHOWLIST, SMSG_PETITION_SIGN_RESULTS, SMSG_PLAY_DANCE, SMSG_PLAY_MUSIC, SMSG_PLAY_OBJECT_SOUND, SMSG_PLAY_SOUND, SMSG_PLAY_SPELL_IMPACT, SMSG_PLAY_SPELL_VISUAL, SMSG_PLAY_TIME_WARNING, SMSG_PLAYED_TIME, SMSG_PLAYER_SKINNED, SMSG_PLAYER_VEHICLE_DATA, SMSG_PLAYERBINDERROR, SMSG_PLAYERBOUND, SMSG_PONG, SMSG_POWER_UPDATE, SMSG_PRE_RESURRECT, SMSG_PROCRESIST, SMSG_PROFILEDATA_RESPONSE, SMSG_PROPOSE_LEVEL_GRANT, SMSG_PVP_CREDIT, SMSG_PVP_QUEUE_STATS, SMSG_QUERY_OBJECT_POSITION, SMSG_QUERY_OBJECT_ROTATION, SMSG_QUERY_QUESTS_COMPLETED_RESPONSE, SMSG_QUERY_TIME_RESPONSE, SMSG_QUEST_CONFIRM_ACCEPT, SMSG_QUEST_FORCE_REMOVE, SMSG_QUEST_POI_QUERY_RESPONSE, SMSG_QUEST_QUERY_RESPONSE, SMSG_QUESTGIVER_OFFER_REWARD, SMSG_QUESTGIVER_QUEST_COMPLETE, SMSG_QUESTGIVER_QUEST_DETAILS, SMSG_QUESTGIVER_QUEST_FAILED, SMSG_QUESTGIVER_QUEST_INVALID, SMSG_QUESTGIVER_QUEST_LIST, SMSG_QUESTGIVER_REQUEST_ITEMS, SMSG_QUESTGIVER_STATUS, SMSG_QUESTGIVER_STATUS_MULTIPLE, SMSG_QUESTLOG_FULL, SMSG_QUESTUPDATE_ADD_ITEM, SMSG_QUESTUPDATE_ADD_KILL, SMSG_QUESTUPDATE_ADD_PVP_KILL, SMSG_QUESTUPDATE_COMPLETE, SMSG_QUESTUPDATE_FAILED, SMSG_QUESTUPDATE_FAILEDTIMER, SMSG_RAID_GROUP_ONLY, SMSG_RAID_INSTANCE_INFO, SMSG_RAID_INSTANCE_MESSAGE, SMSG_RAID_READY_CHECK_ERROR, SMSG_READ_ITEM_FAILED, SMSG_READ_ITEM_OK, SMSG_REAL_GROUP_UPDATE, SMSG_REALM_SPLIT, SMSG_RECEIVED_MAIL, SMSG_REDIRECT_CLIENT, SMSG_REFER_A_FRIEND_EXPIRED, SMSG_REFER_A_FRIEND_FAILURE, SMSG_REMOVED_FROM_PVP_QUEUE, SMSG_REMOVED_SPELL, SMSG_REPORT_PVP_AFK_RESULT, SMSG_RESET_FAILED_NOTIFY, SMSG_RESET_RANGED_COMBAT_TIMER, SMSG_RESISTLOG, SMSG_RESPOND_INSPECT_ACHIEVEMENTS, SMSG_RESUME_CAST_BAR, SMSG_RESURRECT_FAILED, SMSG_RESURRECT_REQUEST, SMSG_RESYNC_RUNES, SMSG_RWHOIS, SMSG_SCRIPT_MESSAGE, SMSG_SELL_ITEM, SMSG_SEND_ALL_COMBAT_LOG, SMSG_SEND_MAIL_RESULT, SMSG_SEND_UNLEARN_SPELLS, SMSG_SERVER_BUCK_DATA, SMSG_SERVER_BUCK_DATA_START, SMSG_SERVER_FIRST_ACHIEVEMENT, SMSG_SERVER_INFO_RESPONSE, SMSG_SERVERINFO, SMSG_SERVERTIME, SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE, SMSG_SET_EXTRA_AURA_INFO_OBSOLETE, SMSG_SET_FACTION_ATWAR, SMSG_SET_FACTION_STANDING, SMSG_SET_FACTION_VISIBLE, SMSG_SET_FLAT_SPELL_MODIFIER, SMSG_SET_FORCED_REACTIONS, SMSG_SET_PCT_SPELL_MODIFIER, SMSG_SET_PHASE_SHIFT, SMSG_SET_PLAYER_DECLINED_NAMES_RESULT, SMSG_SET_PROFICIENCY, SMSG_SET_PROJECTILE_POSITION, SMSG_SHOW_BANK, SMSG_SHOW_MAILBOX, SMSG_SHOWTAXINODES, SMSG_SOCKET_GEMS_RESULT, SMSG_SPELL_CHANCE_PROC_LOG, SMSG_SPELL_CHANCE_RESIST_PUSHBACK, SMSG_SPELL_COOLDOWN, SMSG_SPELL_DELAYED, SMSG_SPELL_FAILED_OTHER, SMSG_SPELL_FAILURE, SMSG_SPELL_GO, SMSG_SPELL_START, SMSG_SPELL_UPDATE_CHAIN_TARGETS, SMSG_SPELLBREAKLOG, SMSG_SPELLDAMAGESHIELD, SMSG_SPELLDISPELLOG, SMSG_SPELLENERGIZELOG, SMSG_SPELLHEALLOG, SMSG_SPELLINSTAKILLLOG, SMSG_SPELLLOGEXECUTE, SMSG_SPELLLOGMISS, SMSG_SPELLNONMELEEDAMAGELOG, SMSG_SPELLORDAMAGE_IMMUNE, SMSG_SPELLSTEALLOG, SMSG_SPIRIT_HEALER_CONFIRM, SMSG_SPLINE_MOVE_FEATHER_FALL, SMSG_SPLINE_MOVE_GRAVITY_DISABLE, SMSG_SPLINE_MOVE_GRAVITY_ENABLE, SMSG_SPLINE_MOVE_LAND_WALK, SMSG_SPLINE_MOVE_NORMAL_FALL, SMSG_SPLINE_MOVE_ROOT, SMSG_SPLINE_MOVE_SET_FLYING, SMSG_SPLINE_MOVE_SET_HOVER, SMSG_SPLINE_MOVE_SET_RUN_MODE, SMSG_SPLINE_MOVE_SET_WALK_MODE, SMSG_SPLINE_MOVE_START_SWIM, SMSG_SPLINE_MOVE_STOP_SWIM, SMSG_SPLINE_MOVE_UNROOT, SMSG_SPLINE_MOVE_UNSET_FLYING, SMSG_SPLINE_MOVE_UNSET_HOVER, SMSG_SPLINE_MOVE_WATER_WALK, SMSG_SPLINE_SET_FLIGHT_BACK_SPEED, SMSG_SPLINE_SET_FLIGHT_SPEED, SMSG_SPLINE_SET_PITCH_RATE, SMSG_SPLINE_SET_RUN_BACK_SPEED, SMSG_SPLINE_SET_RUN_SPEED, SMSG_SPLINE_SET_SWIM_BACK_SPEED, SMSG_SPLINE_SET_SWIM_SPEED, SMSG_SPLINE_SET_TURN_RATE, SMSG_SPLINE_SET_WALK_SPEED, SMSG_STABLE_RESULT, SMSG_STANDSTATE_UPDATE, SMSG_START_MIRROR_TIMER, SMSG_STOP_DANCE, SMSG_STOP_MIRROR_TIMER, SMSG_SUMMON_CANCEL, SMSG_SUMMON_REQUEST, SMSG_SUPERCEDED_SPELL, SMSG_SUSPEND_COMMS, SMSG_TALENTS_INFO, SMSG_TALENTS_INVOLUNTARILY_RESET, SMSG_TAXINODE_STATUS, SMSG_TEST_DROP_RATE_RESULT, SMSG_TEXT_EMOTE, SMSG_THREAT_CLEAR, SMSG_THREAT_REMOVE, SMSG_THREAT_UPDATE, SMSG_TIME_SYNC_REQ, SMSG_TITLE_EARNED, SMSG_TOGGLE_XP_GAIN, SMSG_TOTEM_CREATED, SMSG_TRADE_STATUS, SMSG_TRADE_STATUS_EXTENDED, SMSG_TRAINER_BUY_FAILED, SMSG_TRAINER_BUY_SUCCEEDED, SMSG_TRAINER_LIST, SMSG_TRANSFER_ABORTED, SMSG_TRANSFER_PENDING, SMSG_TRIGGER_CINEMATIC, SMSG_TRIGGER_MOVIE, SMSG_TURN_IN_PETITION_RESULTS, SMSG_TUTORIAL_FLAGS, SMSG_UPDATE_ACCOUNT_DATA, SMSG_UPDATE_ACCOUNT_DATA_COMPLETE, SMSG_UPDATE_COMBO_POINTS, SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT, SMSG_UPDATE_INSTANCE_OWNERSHIP, SMSG_UPDATE_LAST_INSTANCE, SMSG_UPDATE_LFG_LIST, SMSG_UPDATE_OBJECT, SMSG_UPDATE_WORLD_STATE, SMSG_USERLIST_ADD, SMSG_USERLIST_REMOVE, SMSG_USERLIST_UPDATE, SMSG_VOICE_CHAT_STATUS, SMSG_VOICE_PARENTAL_CONTROLS, SMSG_VOICE_SESSION_ADJUST_PRIORITY, SMSG_VOICE_SESSION_ENABLE, SMSG_VOICE_SESSION_LEAVE, SMSG_VOICE_SESSION_ROSTER_UPDATE, SMSG_VOICE_SET_TALKER_MUTED, SMSG_VOICESESSION_FULL, SMSG_WARDEN_DATA, SMSG_WEATHER, SMSG_WHO, SMSG_WHOIS, SMSG_WORLD_STATE_UI_TIMER_UPDATE, SMSG_ZONE_MAP, SMSG_ZONE_UNDER_ATTACK, STATUS_AUTHED, STATUS_LOGGEDIN, STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT, STATUS_NEVER, STATUS_TRANSFER, STATUS_UNHANDLED, UMSG_DELETE_GUILD_CHARTER, UMSG_UPDATE_GROUP_INFO, UMSG_UPDATE_GROUP_MEMBERS, and UMSG_UPDATE_GUILD.
Referenced by World::SetInitialWorldSettings().
OpcodeHandler()
OpcodeHandler::OpcodeHandler (char const * name, SessionStatus status) inline
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
: Name(name), Status(status) { }
OpcodeTable() [1/2]
OpcodeTable::OpcodeTable ()
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
{
    memset(_internalTableClient, 0, sizeof(_internalTableClient));
}
References OpcodeTable::_internalTableClient.
OpcodeTable() [2/2]
OpcodeTable::OpcodeTable (OpcodeTable const &) delete
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
operator=()
OpcodeTable & OpcodeTable::operator= (OpcodeTable const &) delete
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
operator[]()
ClientOpcodeHandler const * OpcodeTable::operator[] (Opcodes index) const inline
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
    {
        return _internalTableClient[index];
    }
References OpcodeTable::_internalTableClient.
ServerOpcodeHandler()
ServerOpcodeHandler::ServerOpcodeHandler (char const * name, SessionStatus status) inline
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
        : OpcodeHandler(name, status) { }
ValidateAndSetClientOpcode()
template<typename Handler , Handler HandlerFunction> void OpcodeTable::ValidateAndSetClientOpcode (OpcodeClient opcode, char const * name, SessionStatus status, PacketProcessing processing) private
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
{
    if (uint32(opcode) == NULL_OPCODE)
    {
        LOG_ERROR("network", "Opcode {} does not have a value", name);
        return;
    }
    if (uint32(opcode) >= NUM_OPCODE_HANDLERS)
    {
        LOG_ERROR("network", "Tried to set handler for an invalid opcode {}", uint32(opcode));
        return;
    }
    if (_internalTableClient[opcode] != nullptr)
    {
        LOG_ERROR("network", "Tried to override client handler of {} with {} (opcode {})", opcodeTable[opcode]->Name, name, uint32(opcode));
        return;
    }
    _internalTableClient[opcode] = new PacketHandler<typename get_packet_class<Handler>::type, HandlerFunction>(name, status, processing);
}
References OpcodeTable::_internalTableClient, LOG_ERROR, NULL_OPCODE, NUM_OPCODE_HANDLERS, and opcodeTable.
ValidateAndSetServerOpcode()
void OpcodeTable::ValidateAndSetServerOpcode (OpcodeServer opcode, char const * name, SessionStatus status) private
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
{
    if (uint32(opcode) == NULL_OPCODE)
    {
        LOG_ERROR("network", "Opcode {} does not have a value", name);
        return;
    }
    if (uint32(opcode) >= NUM_OPCODE_HANDLERS)
    {
        LOG_ERROR("network", "Tried to set handler for an invalid opcode {}", uint32(opcode));
        return;
    }
    if (_internalTableClient[opcode] != nullptr)
    {
        LOG_ERROR("network", "Tried to override server handler of {} with {} (opcode {})", opcodeTable[opcode]->Name, name, uint32(opcode));
        return;
    }
    _internalTableClient[opcode] = new PacketHandler<WorldPacket, &WorldSession::Handle_ServerSide>(name, status, PROCESS_INPLACE);
}
References OpcodeTable::_internalTableClient, LOG_ERROR, NULL_OPCODE, NUM_OPCODE_HANDLERS, opcodeTable, and PROCESS_INPLACE.
~OpcodeHandler()
virtual OpcodeHandler::~OpcodeHandler () virtual default
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
~OpcodeTable()
OpcodeTable::~OpcodeTable ()
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
{
    for (uint16 i = 0; i < NUM_OPCODE_HANDLERS; ++i)
        delete _internalTableClient[i];
}
References OpcodeTable::_internalTableClient, and NUM_OPCODE_HANDLERS.
Variable Documentation
_internalTableClient
ClientOpcodeHandler* OpcodeTable::_internalTableClient[NUM_OPCODE_HANDLERS] private
Referenced by OpcodeTable::OpcodeTable(), OpcodeTable::operator[](), OpcodeTable::ValidateAndSetClientOpcode(), OpcodeTable::ValidateAndSetServerOpcode(), and OpcodeTable::~OpcodeTable().
Name
char const* OpcodeHandler::Name
Referenced by WorldSession::Update().
opcodeTable
OpcodeTable opcodeTable extern
#include <azerothcore-wotlk/src/server/game/Server/Protocol/Opcodes.h>
Referenced by WorldSession::DosProtection::EvaluateOpcode(), GetOpcodeNameForLoggingImpl(), MapSessionFilter::Process(), WorldSessionFilter::Process(), WorldSocket::ReadDataHandler(), World::SetInitialWorldSettings(), WorldSession::Update(), OpcodeTable::ValidateAndSetClientOpcode(), and OpcodeTable::ValidateAndSetServerOpcode().
ProcessingPlace
PacketProcessing ClientOpcodeHandler::ProcessingPlace
Referenced by MapSessionFilter::Process(), and WorldSessionFilter::Process().
Status
SessionStatus OpcodeHandler::Status
Referenced by WorldSession::Update().