AzeorthCore: BossAI Class Reference
BossAI Class Reference
#include "ScriptedCreature.h"
Public Member Functions
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Protected Member Functions
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes
EventMap events
SummonList summons
TaskScheduler scheduler
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Private Attributes
uint32 const _bossId
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Detailed Description
Constructor & Destructor Documentation
BossAI()
BossAI::BossAI (Creature * creature, uint32 bossId)
                                                : ScriptedAI(creature),
    instance(creature->GetInstanceScript()),
    summons(creature),
    _bossId(bossId)
{
    if (instance)
        SetBoundary(instance->GetBossBoundary(bossId));
}
References InstanceScript::GetBossBoundary(), instance, and CreatureAI::SetBoundary().
~BossAI()
BossAI::~BossAI () inline override
{}
Member Function Documentation
_EnterCombat()
void BossAI::_EnterCombat () protected
{
    me->setActive(true);
    DoZoneInCombat();
    ScheduleTasks();
    if (instance)
    {
        // bosses do not respawn, check only on enter combat
        if (!instance->CheckRequiredBosses(_bossId))
        {
            EnterEvadeMode();
            return;
        }
        instance->SetBossState(_bossId, IN_PROGRESS);
    }
}
References _bossId, InstanceScript::CheckRequiredBosses(), CreatureAI::DoZoneInCombat(), CreatureAI::EnterEvadeMode(), IN_PROGRESS, instance, ScriptedAI::me, ScheduleTasks(), WorldObject::setActive(), and InstanceScript::SetBossState().
Referenced by boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent(), EnterCombat(), boss_anubshiah::boss_anubshiahAI::EnterCombat(), boss_eviscerator::boss_evisceratorAI::EnterCombat(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::EnterCombat(), boss_grizzle::boss_grizzleAI::EnterCombat(), boss_hedrum::boss_hedrumAI::EnterCombat(), boss_magmus::boss_magmusAI::EnterCombat(), boss_moira_bronzebeardAI::EnterCombat(), boss_high_priestess_thaurissanAI::EnterCombat(), boss_okthor::boss_okthorAI::EnterCombat(), boss_drakkisath::boss_drakkisathAI::EnterCombat(), boss_gyth::boss_gythAI::EnterCombat(), boss_halycon::boss_halyconAI::EnterCombat(), boss_highlord_omokk::boss_highlordomokkAI::EnterCombat(), boss_mor_grayhoof::EnterCombat(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::EnterCombat(), boss_rend_blackhand::boss_rend_blackhandAI::EnterCombat(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::EnterCombat(), boss_the_beast::boss_thebeastAI::EnterCombat(), boss_urok_doomhowl::boss_urok_doomhowlAI::EnterCombat(), boss_warmaster_voone::boss_warmastervooneAI::EnterCombat(), boss_razorgore::boss_razorgoreAI::EnterCombat(), boss_baron_geddon::boss_baron_geddonAI::EnterCombat(), boss_garr::boss_garrAI::EnterCombat(), boss_gehennas::boss_gehennasAI::EnterCombat(), boss_lucifron::boss_lucifronAI::EnterCombat(), boss_magmadar::boss_magmadarAI::EnterCombat(), boss_majordomo::boss_majordomoAI::EnterCombat(), boss_ragnaros::boss_ragnarosAI::EnterCombat(), boss_shazzrah::boss_shazzrahAI::EnterCombat(), boss_sulfuron::boss_sulfuronAI::EnterCombat(), boss_jarien::EnterCombat(), boss_sothos::EnterCombat(), boss_arlokk::boss_arlokkAI::EnterCombat(), boss_gahzranka::boss_gahzrankaAI::EnterCombat(), boss_grilek::boss_grilekAI::EnterCombat(), boss_hakkar::boss_hakkarAI::EnterCombat(), boss_hazzarah::EnterCombat(), boss_mandokir::boss_mandokirAI::EnterCombat(), boss_renataki::boss_renatakiAI::EnterCombat(), boss_thekal::boss_thekalAI::EnterCombat(), boss_venoxis::boss_venoxisAI::EnterCombat(), boss_wushoolay::boss_wushoolayAI::EnterCombat(), boss_isalien::EnterCombat(), boss_skeram::EnterCombat(), boss_elder_nadox::EnterCombat(), boss_volazj::EnterCombat(), boss_jedoga_shadowseeker::EnterCombat(), boss_taldaram::EnterCombat(), boss_sister_svalna::boss_sister_svalnaAI::EnterCombat(), boss_gruul::boss_gruulAI::EnterCombat(), boss_high_king_maulgar::boss_high_king_maulgarAI::EnterCombat(), boss_magtheridon::boss_magtheridonAI::EnterCombat(), boss_warbringer_omrogg::boss_warbringer_omroggAI::EnterCombat(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::EnterCombat(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::EnterCombat(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::EnterCombat(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::EnterCombat(), boss_commander_sarannis::boss_commander_sarannisAI::EnterCombat(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::EnterCombat(), boss_laj::boss_lajAI::EnterCombat(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::EnterCombat(), boss_warp_splinter::boss_warp_splinterAI::EnterCombat(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::EnterCombat(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI::EnterCombat(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::EnterCombat(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::EnterCombat(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), boss_jeklik::PathEndReached(), and boss_anub_arak::boss_anub_arakAI::UpdateAI().
_JustDied()
void BossAI::_JustDied () protected
{
    events.Reset();
    scheduler.CancelAll();
    summons.DespawnAll();
    if (instance)
    {
        instance->SetBossState(_bossId, DONE);
        instance->SaveToDB();
    }
}
References _bossId, TaskScheduler::CancelAll(), SummonList::DespawnAll(), DONE, instance, InstanceScript::SaveToDB(), scheduler, InstanceScript::SetBossState(), and summons.
Referenced by boss_high_king_maulgar::boss_high_king_maulgarAI::DoAction(), JustDied(), boss_halycon::boss_halyconAI::JustDied(), boss_highlord_omokk::boss_highlordomokkAI::JustDied(), boss_mor_grayhoof::JustDied(), boss_quartermaster_zigris::JustDied(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::JustDied(), boss_broodlord::boss_broodlordAI::JustDied(), boss_nefarian::JustDied(), boss_razorgore::boss_razorgoreAI::JustDied(), boss_ragnaros::boss_ragnarosAI::JustDied(), boss_akilzon::boss_akilzonAI::JustDied(), boss_arlokk::boss_arlokkAI::JustDied(), boss_gahzranka::boss_gahzrankaAI::JustDied(), boss_hakkar::boss_hakkarAI::JustDied(), boss_jeklik::JustDied(), boss_thekal::boss_thekalAI::JustDied(), boss_venoxis::boss_venoxisAI::JustDied(), boss_isalien::JustDied(), boss_moam::JustDied(), boss_rajaxx::JustDied(), boss_sartura::JustDied(), boss_skeram::JustDied(), boss_amanitar::JustDied(), boss_elder_nadox::JustDied(), boss_volazj::JustDied(), boss_jedoga_shadowseeker::JustDied(), boss_taldaram::JustDied(), boss_sartharion::boss_sartharionAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_festergut::boss_festergutAI::JustDied(), boss_lord_marrowgar::JustDied(), boss_professor_putricide::boss_professor_putricideAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), boss_sindragosa::boss_sindragosaAI::JustDied(), boss_the_lich_king::boss_the_lich_kingAI::JustDied(), boss_sister_svalna::boss_sister_svalnaAI::JustDied(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustDied(), boss_gruul::boss_gruulAI::JustDied(), boss_high_king_maulgar::boss_high_king_maulgarAI::JustDied(), boss_magtheridon::boss_magtheridonAI::JustDied(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::JustDied(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustDied(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::JustDied(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::JustDied(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::JustDied(), boss_commander_sarannis::boss_commander_sarannisAI::JustDied(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::JustDied(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::JustDied(), boss_warp_splinter::boss_warp_splinterAI::JustDied(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::JustDied(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI::JustDied(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::JustDied(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::JustDied(), boss_jarien::JustDied(), boss_sothos::JustDied(), and boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied().
_JustReachedHome()
void BossAI::_JustReachedHome () inline protected
{ me->setActive(false); }
References ScriptedAI::me, and WorldObject::setActive().
Referenced by JustReachedHome(), boss_majordomo::boss_majordomoAI::JustReachedHome(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustReachedHome(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustReachedHome(), boss_festergut::boss_festergutAI::JustReachedHome(), boss_lord_marrowgar::JustReachedHome(), boss_professor_putricide::boss_professor_putricideAI::JustReachedHome(), boss_rotface::boss_rotfaceAI::JustReachedHome(), boss_sindragosa::boss_sindragosaAI::JustReachedHome(), boss_the_lich_king::boss_the_lich_kingAI::JustReachedHome(), and npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustReachedHome().
_Reset()
void BossAI::_Reset () protected
{
    if (!me->IsAlive())
        return;
    me->ResetLootMode();
    events.Reset();
    scheduler.CancelAll();
    summons.DespawnAll();
    if (instance)
        instance->SetBossState(_bossId, NOT_STARTED);
}
References _bossId, TaskScheduler::CancelAll(), SummonList::DespawnAll(), instance, Unit::IsAlive(), ScriptedAI::me, NOT_STARTED, Creature::ResetLootMode(), scheduler, InstanceScript::SetBossState(), and summons.
Referenced by Reset(), boss_magmus::boss_magmusAI::Reset(), boss_halycon::boss_halyconAI::Reset(), boss_highlord_omokk::boss_highlordomokkAI::Reset(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::Reset(), boss_quartermaster_zigris::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::Reset(), boss_the_beast::boss_thebeastAI::Reset(), boss_chromaggus::boss_chromaggusAI::Reset(), boss_victor_nefarius::boss_victor_nefariusAI::Reset(), boss_nefarian::Reset(), boss_razorgore::boss_razorgoreAI::Reset(), boss_vaelastrasz::boss_vaelAI::Reset(), boss_baron_geddon::boss_baron_geddonAI::Reset(), boss_garr::boss_garrAI::Reset(), boss_golemagg::boss_golemaggAI::Reset(), boss_ragnaros::boss_ragnarosAI::Reset(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::Reset(), boss_apothecary_hummel::boss_apothecary_hummelAI::Reset(), boss_jarien::Reset(), boss_sothos::Reset(), boss_akilzon::boss_akilzonAI::Reset(), boss_arlokk::boss_arlokkAI::Reset(), boss_gahzranka::boss_gahzrankaAI::Reset(), boss_hakkar::boss_hakkarAI::Reset(), boss_jeklik::Reset(), boss_renataki::boss_renatakiAI::Reset(), boss_thekal::boss_thekalAI::Reset(), boss_venoxis::boss_venoxisAI::Reset(), boss_isalien::Reset(), boss_moam::Reset(), boss_sartura::Reset(), boss_skeram::Reset(), boss_amanitar::Reset(), boss_elder_nadox::Reset(), boss_volazj::Reset(), boss_jedoga_shadowseeker::Reset(), boss_taldaram::Reset(), boss_sartharion::boss_sartharionAI::Reset(), boss_sartharion_dragonAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), boss_festergut::boss_festergutAI::Reset(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::Reset(), boss_lord_marrowgar::Reset(), boss_professor_putricide::boss_professor_putricideAI::Reset(), boss_rotface::boss_rotfaceAI::Reset(), boss_sindragosa::boss_sindragosaAI::Reset(), boss_the_lich_king::boss_the_lich_kingAI::Reset(), boss_sister_svalna::boss_sister_svalnaAI::Reset(), boss_gruul::boss_gruulAI::Reset(), boss_high_king_maulgar::boss_high_king_maulgarAI::Reset(), boss_magtheridon::boss_magtheridonAI::Reset(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::Reset(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::Reset(), boss_commander_sarannis::boss_commander_sarannisAI::Reset(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::Reset(), boss_laj::boss_lajAI::Reset(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::Reset(), and boss_warp_splinter::boss_warp_splinterAI::Reset().
CanRespawn()
bool BossAI::CanRespawn () override virtual
Reimplemented from CreatureAI.
{
    if (instance)
    {
        if (instance->GetBossState(_bossId) == DONE)
        {
            return false;
        }
    }
    return true;
}
References _bossId, DONE, InstanceScript::GetBossState(), and instance.
EnterCombat()
void BossAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_sartharion_dragonAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_anubshiah::boss_anubshiahAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_eviscerator::boss_evisceratorAI, boss_gorosh_the_dervish::boss_gorosh_the_dervishAI, boss_grizzle::boss_grizzleAI, boss_hedrum::boss_hedrumAI, boss_magmus::boss_magmusAI, boss_moira_bronzebeardAI, boss_high_priestess_thaurissanAI, boss_okthor::boss_okthorAI, boss_drakkisath::boss_drakkisathAI, boss_gyth::boss_gythAI, boss_halycon::boss_halyconAI, boss_highlord_omokk::boss_highlordomokkAI, boss_mor_grayhoof, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_the_beast::boss_thebeastAI, boss_urok_doomhowl::boss_urok_doomhowlAI, boss_warmaster_voone::boss_warmastervooneAI, boss_nefarian, boss_razorgore::boss_razorgoreAI, boss_baron_geddon::boss_baron_geddonAI, boss_garr::boss_garrAI, boss_gehennas::boss_gehennasAI, boss_lucifron::boss_lucifronAI, boss_magmadar::boss_magmadarAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_shazzrah::boss_shazzrahAI, boss_sulfuron::boss_sulfuronAI, boss_servant_quarters, boss_shade_of_aran::boss_aranAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_baroness_anastari::boss_baroness_anastariAI, boss_jarien, boss_sothos, boss_akilzon::boss_akilzonAI, boss_arlokk::boss_arlokkAI, boss_gahzranka::boss_gahzrankaAI, boss_grilek::boss_grilekAI, boss_hakkar::boss_hakkarAI, boss_hazzarah, boss_jeklik, boss_mandokir::boss_mandokirAI, boss_renataki::boss_renatakiAI, boss_thekal::boss_thekalAI, boss_venoxis::boss_venoxisAI, boss_wushoolay::boss_wushoolayAI, boss_archimonde::boss_archimondeAI, boss_isalien, boss_rajaxx, boss_cthun, boss_skeram, boss_amanitar, boss_elder_nadox, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, boss_lord_marrowgar, boss_sister_svalna::boss_sister_svalnaAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_gruul::boss_gruulAI, boss_high_king_maulgar::boss_high_king_maulgarAI, boss_magtheridon::boss_magtheridonAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_warbringer_omrogg::boss_warbringer_omroggAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_zereketh_the_unbound::boss_zereketh_the_unboundAI, boss_commander_sarannis::boss_commander_sarannisAI, boss_high_botanist_freywinn::boss_high_botanist_freywinnAI, boss_laj::boss_lajAI, boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI, boss_warp_splinter::boss_warp_splinterAI, boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI, boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI, boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI, boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI, boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI, boss_ayamiss, boss_sartharion::boss_sartharionAI, boss_the_lich_king::boss_the_lich_kingAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_chromaggus::boss_chromaggusAI, boss_flamegor::boss_flamegorAI, boss_vaelastrasz::boss_vaelAI, boss_sindragosa::boss_sindragosaAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_quartermaster_zigris, boss_broodlord::boss_broodlordAI, boss_ebonroc::boss_ebonrocAI, boss_firemaw::boss_firemawAI, boss_curator::boss_curatorAI, boss_maiden_of_virtue, boss_midnight::boss_midnightAI, boss_moroes, boss_brutallus::boss_brutallusAI, boss_sacrolash::boss_sacrolashAI, boss_alythess::boss_alythessAI, boss_felmyst::boss_felmystAI, boss_kalecgos::boss_kalecgosAI, boss_muru::boss_muruAI, boss_jindo, boss_marli, boss_onyxia, boss_buru, boss_moam, boss_ossirian, boss_kri, boss_vem, boss_yauj, boss_eye_of_cthun, boss_fankriss, boss_huhuran, boss_ouro, boss_sartura, boss_twinemperorsAI, boss_veknilash, boss_veklor, boss_viscidus, boss_krik_thir::boss_krik_thirAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_dred::boss_dredAI, boss_novos::boss_novosAI, boss_tharon_ja::boss_tharon_jaAI, boss_trollgore::boss_trollgoreAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_moorabi::boss_moorabiAI, boss_slad_ran::boss_slad_ranAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_four_horsemen::boss_four_horsemenAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, boss_grobbulus::boss_grobbulusAI, boss_heigan::boss_heiganAI, boss_kelthuzad::boss_kelthuzadAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_noth::boss_nothAI, boss_patchwerk::boss_patchwerkAI, boss_razuvious::boss_razuviousAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_anomalus::boss_anomalusAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_keristrasza::boss_keristraszaAI, boss_magus_telestra::boss_magus_telestraAI, boss_ormorok::boss_ormorokAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_mother_shahraz::boss_shahrazAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_supremus::boss_supremusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_najentus::boss_najentusAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_lady_vashj::boss_lady_vashjAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_ghazan, boss_hungarfen, boss_the_black_stalker, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI, boss_alar::boss_alarAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_kaelthas::boss_kaelthasAI, and boss_void_reaver::boss_void_reaverAI.
{ _EnterCombat(); }
References _EnterCombat().
Referenced by boss_ayamiss::EnterCombat(), boss_chromaggus::boss_chromaggusAI::EnterCombat(), boss_flamegor::boss_flamegorAI::EnterCombat(), boss_vaelastrasz::boss_vaelAI::EnterCombat(), boss_lord_valthalak::boss_lord_valthalakAI::EnterCombat(), boss_quartermaster_zigris::EnterCombat(), boss_broodlord::boss_broodlordAI::EnterCombat(), boss_ebonroc::boss_ebonrocAI::EnterCombat(), boss_firemaw::boss_firemawAI::EnterCombat(), boss_curator::boss_curatorAI::EnterCombat(), boss_maiden_of_virtue::EnterCombat(), boss_midnight::boss_midnightAI::EnterCombat(), boss_moroes::EnterCombat(), boss_brutallus::boss_brutallusAI::EnterCombat(), boss_sacrolash::boss_sacrolashAI::EnterCombat(), boss_alythess::boss_alythessAI::EnterCombat(), boss_felmyst::boss_felmystAI::EnterCombat(), boss_kalecgos::boss_kalecgosAI::EnterCombat(), boss_muru::boss_muruAI::EnterCombat(), boss_jindo::EnterCombat(), boss_marli::EnterCombat(), boss_onyxia::EnterCombat(), boss_buru::EnterCombat(), boss_moam::EnterCombat(), boss_ossirian::EnterCombat(), boss_eye_of_cthun::EnterCombat(), boss_fankriss::EnterCombat(), boss_huhuran::EnterCombat(), boss_ouro::EnterCombat(), boss_sartura::EnterCombat(), boss_twinemperorsAI::EnterCombat(), boss_viscidus::EnterCombat(), boss_krik_thir::boss_krik_thirAI::EnterCombat(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::EnterCombat(), boss_general_zarithrian::boss_general_zarithrianAI::EnterCombat(), boss_halion::boss_halionAI::EnterCombat(), boss_saviana_ragefire::boss_saviana_ragefireAI::EnterCombat(), boss_dred::boss_dredAI::EnterCombat(), boss_novos::boss_novosAI::EnterCombat(), boss_tharon_ja::boss_tharon_jaAI::EnterCombat(), boss_drakkari_colossus::boss_drakkari_colossusAI::EnterCombat(), boss_eck::boss_eckAI::EnterCombat(), boss_gal_darah::boss_gal_darahAI::EnterCombat(), boss_moorabi::boss_moorabiAI::EnterCombat(), boss_slad_ran::boss_slad_ranAI::EnterCombat(), boss_anubrekhan::boss_anubrekhanAI::EnterCombat(), boss_faerlina::boss_faerlinaAI::EnterCombat(), boss_four_horsemen::boss_four_horsemenAI::EnterCombat(), boss_gluth::boss_gluthAI::EnterCombat(), boss_gothik::boss_gothikAI::EnterCombat(), boss_grobbulus::boss_grobbulusAI::EnterCombat(), boss_heigan::boss_heiganAI::EnterCombat(), boss_kelthuzad::boss_kelthuzadAI::EnterCombat(), boss_loatheb::boss_loathebAI::EnterCombat(), boss_maexxna::boss_maexxnaAI::EnterCombat(), boss_noth::boss_nothAI::EnterCombat(), boss_patchwerk::boss_patchwerkAI::EnterCombat(), boss_razuvious::boss_razuviousAI::EnterCombat(), boss_sapphiron::boss_sapphironAI::EnterCombat(), boss_thaddius::boss_thaddiusAI::EnterCombat(), boss_anomalus::boss_anomalusAI::EnterCombat(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::EnterCombat(), boss_keristrasza::boss_keristraszaAI::EnterCombat(), boss_magus_telestra::boss_magus_telestraAI::EnterCombat(), boss_ormorok::boss_ormorokAI::EnterCombat(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::EnterCombat(), boss_illidan_stormrage::boss_illidan_stormrageAI::EnterCombat(), boss_mother_shahraz::boss_shahrazAI::EnterCombat(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::EnterCombat(), boss_shade_of_akama::boss_shade_of_akamaAI::EnterCombat(), boss_supremus::boss_supremusAI::EnterCombat(), boss_teron_gorefiend::boss_teron_gorefiendAI::EnterCombat(), boss_najentus::boss_najentusAI::EnterCombat(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::EnterCombat(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::EnterCombat(), boss_lady_vashj::boss_lady_vashjAI::EnterCombat(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::EnterCombat(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::EnterCombat(), boss_ghazan::EnterCombat(), boss_hungarfen::EnterCombat(), boss_the_black_stalker::EnterCombat(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::EnterCombat(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::EnterCombat(), boss_alar::boss_alarAI::EnterCombat(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::EnterCombat(), boss_kaelthas::boss_kaelthasAI::EnterCombat(), boss_void_reaver::boss_void_reaverAI::EnterCombat(), and boss_bug_trio::EnterCombatWithTrio().
ExecuteEvent()
virtual void BossAI::ExecuteEvent (uint32) inline virtual
Reimplemented in boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_warmaster_voone::boss_warmastervooneAI, boss_baron_geddon::boss_baron_geddonAI, boss_gehennas::boss_gehennasAI, boss_lucifron::boss_lucifronAI, boss_magmadar::boss_magmadarAI, boss_shazzrah::boss_shazzrahAI, boss_sulfuron::boss_sulfuronAI, boss_amanitar, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_sartharion_shadron::boss_sartharion_shadronAI, and boss_sartharion_vesperon::boss_sartharion_vesperonAI.
{ }
Referenced by boss_sartharion_dragonAI::UpdateAI(), and UpdateAI().
JustDied()
void BossAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_gyth::boss_gythAI, boss_halycon::boss_halyconAI, boss_highlord_omokk::boss_highlordomokkAI, boss_mor_grayhoof, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_quartermaster_zigris, boss_rend_blackhand::boss_rend_blackhandAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_broodlord::boss_broodlordAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_nefarian, boss_razorgore::boss_razorgoreAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_servant_quarters, boss_shade_of_aran::boss_aranAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_apothecary_hummel::boss_apothecary_hummelAI, boss_baroness_anastari::boss_baroness_anastariAI, boss_sacrolash::boss_sacrolashAI, boss_alythess::boss_alythessAI, boss_akilzon::boss_akilzonAI, boss_arlokk::boss_arlokkAI, boss_gahzranka::boss_gahzrankaAI, boss_hakkar::boss_hakkarAI, boss_jeklik, boss_mandokir::boss_mandokirAI, boss_thekal::boss_thekalAI, boss_venoxis::boss_venoxisAI, boss_archimonde::boss_archimondeAI, boss_isalien, boss_moam, boss_rajaxx, boss_eye_of_cthun, boss_sartura, boss_skeram, boss_viscidus, boss_amanitar, boss_elder_nadox, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_sartharion::boss_sartharionAI, boss_sartharion_dragonAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_lord_marrowgar, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_sindragosa::boss_sindragosaAI, boss_the_lich_king::boss_the_lich_kingAI, boss_sister_svalna::boss_sister_svalnaAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_gruul::boss_gruulAI, boss_high_king_maulgar::boss_high_king_maulgarAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_magtheridon::boss_magtheridonAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_warbringer_omrogg::boss_warbringer_omroggAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_zereketh_the_unbound::boss_zereketh_the_unboundAI, boss_commander_sarannis::boss_commander_sarannisAI, boss_high_botanist_freywinn::boss_high_botanist_freywinnAI, boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI, boss_warp_splinter::boss_warp_splinterAI, boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI, boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI, boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI, boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI, boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_curator::boss_curatorAI, boss_maiden_of_virtue, boss_moroes, boss_jarien, boss_sothos, boss_brutallus::boss_brutallusAI, boss_felmyst::boss_felmystAI, boss_kalecgos::boss_kalecgosAI, boss_marli, boss_ayamiss, boss_buru, boss_kurinnaxx, boss_bug_trio, boss_cthun, boss_twinemperorsAI, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, boss_krik_thir::boss_krik_thirAI, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_novos::boss_novosAI, boss_tharon_ja::boss_tharon_jaAI, boss_trollgore::boss_trollgoreAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_moorabi::boss_moorabiAI, boss_slad_ran::boss_slad_ranAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_four_horsemen::boss_four_horsemenAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, boss_grobbulus::boss_grobbulusAI, boss_heigan::boss_heiganAI, boss_kelthuzad::boss_kelthuzadAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_noth::boss_nothAI, boss_patchwerk::boss_patchwerkAI, boss_razuvious::boss_razuviousAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_anomalus::boss_anomalusAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_keristrasza::boss_keristraszaAI, boss_magus_telestra::boss_magus_telestraAI, boss_ormorok::boss_ormorokAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_mother_shahraz::boss_shahrazAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_supremus::boss_supremusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_najentus::boss_najentusAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_lady_vashj::boss_lady_vashjAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI, boss_alar::boss_alarAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_kaelthas::boss_kaelthasAI, and boss_void_reaver::boss_void_reaverAI.
{ _JustDied(); }
References _JustDied().
Referenced by boss_lord_valthalak::boss_lord_valthalakAI::JustDied(), boss_curator::boss_curatorAI::JustDied(), boss_maiden_of_virtue::JustDied(), boss_moroes::JustDied(), boss_brutallus::boss_brutallusAI::JustDied(), boss_felmyst::boss_felmystAI::JustDied(), boss_kalecgos::boss_kalecgosAI::JustDied(), boss_marli::JustDied(), boss_ayamiss::JustDied(), boss_buru::JustDied(), boss_kurinnaxx::JustDied(), boss_bug_trio::JustDied(), boss_cthun::JustDied(), boss_twinemperorsAI::JustDied(), boss_anub_arak::boss_anub_arakAI::JustDied(), boss_hadronox::boss_hadronoxAI::JustDied(), boss_krik_thir::boss_krik_thirAI::JustDied(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustDied(), boss_general_zarithrian::boss_general_zarithrianAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustDied(), boss_novos::boss_novosAI::JustDied(), boss_tharon_ja::boss_tharon_jaAI::JustDied(), boss_trollgore::boss_trollgoreAI::JustDied(), boss_eck::boss_eckAI::JustDied(), boss_gal_darah::boss_gal_darahAI::JustDied(), boss_moorabi::boss_moorabiAI::JustDied(), boss_slad_ran::boss_slad_ranAI::JustDied(), boss_anubrekhan::boss_anubrekhanAI::JustDied(), boss_faerlina::boss_faerlinaAI::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), boss_gluth::boss_gluthAI::JustDied(), boss_gothik::boss_gothikAI::JustDied(), boss_grobbulus::boss_grobbulusAI::JustDied(), boss_heigan::boss_heiganAI::JustDied(), boss_kelthuzad::boss_kelthuzadAI::JustDied(), boss_loatheb::boss_loathebAI::JustDied(), boss_maexxna::boss_maexxnaAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_patchwerk::boss_patchwerkAI::JustDied(), boss_razuvious::boss_razuviousAI::JustDied(), boss_sapphiron::boss_sapphironAI::JustDied(), boss_thaddius::boss_thaddiusAI::JustDied(), boss_anomalus::boss_anomalusAI::JustDied(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::JustDied(), boss_keristrasza::boss_keristraszaAI::JustDied(), boss_magus_telestra::boss_magus_telestraAI::JustDied(), boss_ormorok::boss_ormorokAI::JustDied(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::JustDied(), boss_mother_shahraz::boss_shahrazAI::JustDied(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustDied(), boss_shade_of_akama::boss_shade_of_akamaAI::JustDied(), boss_supremus::boss_supremusAI::JustDied(), boss_teron_gorefiend::boss_teron_gorefiendAI::JustDied(), boss_najentus::boss_najentusAI::JustDied(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustDied(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustDied(), boss_lady_vashj::boss_lady_vashjAI::JustDied(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustDied(), boss_the_lurker_below::boss_the_lurker_belowAI::JustDied(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::JustDied(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::JustDied(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::JustDied(), boss_alar::boss_alarAI::JustDied(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::JustDied(), boss_kaelthas::boss_kaelthasAI::JustDied(), and boss_void_reaver::boss_void_reaverAI::JustDied().
JustReachedHome()
void BossAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Reimplemented in boss_victor_nefarius::boss_victor_nefariusAI, boss_majordomo::boss_majordomoAI, boss_moroes, boss_kalecgos::boss_kalecgosAI, boss_arlokk::boss_arlokkAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_halion::boss_halionAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_gal_darah::boss_gal_darahAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_lord_marrowgar, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_sindragosa::boss_sindragosaAI, boss_the_lich_king::boss_the_lich_kingAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_ghazan, and boss_alar::boss_alarAI.
{ _JustReachedHome(); }
References _JustReachedHome().
Referenced by boss_moroes::JustReachedHome(), boss_kalecgos::boss_kalecgosAI::JustReachedHome(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustReachedHome(), boss_halion::boss_halionAI::JustReachedHome(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustReachedHome(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustReachedHome(), boss_gal_darah::boss_gal_darahAI::JustReachedHome(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustReachedHome(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustReachedHome(), boss_ghazan::JustReachedHome(), and boss_alar::boss_alarAI::JustReachedHome().
JustSummoned()
void BossAI::JustSummoned (Creature * summon) override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_grobbulus::boss_grobbulusAI, boss_kelthuzad::boss_kelthuzadAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_razuvious::boss_razuviousAI, boss_thaddius::boss_thaddiusAI, boss_ossirian, boss_skeram, boss_gyth::boss_gythAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_razorgore::boss_razorgoreAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_curator::boss_curatorAI, boss_midnight::boss_midnightAI, boss_apothecary_hummel::boss_apothecary_hummelAI, boss_sacrolash::boss_sacrolashAI, boss_felmyst::boss_felmystAI, boss_muru::boss_muruAI, boss_hazzarah, boss_jindo, boss_isalien, boss_onyxia, boss_eye_of_cthun, boss_amanitar, boss_jedoga_shadowseeker, boss_taldaram, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, boss_krik_thir::boss_krik_thirAI, boss_sartharion::boss_sartharionAI, boss_sartharion_dragonAI, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_novos::boss_novosAI, boss_trollgore::boss_trollgoreAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_gal_darah::boss_gal_darahAI, boss_slad_ran::boss_slad_ranAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_sindragosa::boss_sindragosaAI, boss_the_lich_king::boss_the_lich_kingAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, boss_noth::boss_nothAI, boss_anomalus::boss_anomalusAI, boss_magus_telestra::boss_magus_telestraAI, boss_ormorok::boss_ormorokAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_supremus::boss_supremusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_lady_vashj::boss_lady_vashjAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_the_black_stalker, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_alar::boss_alarAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_kaelthas::boss_kaelthasAI, boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI, boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI, boss_vaelastrasz::boss_vaelAI, boss_archimonde::boss_archimondeAI, boss_warbringer_omrogg::boss_warbringer_omroggAI, and boss_ayamiss.
{
    summons.Summon(summon);
    if (me->IsEngaged())
        DoZoneInCombat(summon);
}
References CreatureAI::DoZoneInCombat(), Unit::IsEngaged(), ScriptedAI::me, SummonList::Summon(), and summons.
Referenced by boss_skeram::JustSummoned(), boss_victor_nefarius::boss_victor_nefariusAI::JustSummoned(), boss_ragnaros::boss_ragnarosAI::JustSummoned(), boss_jindo::JustSummoned(), boss_sartharion_dragonAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), and boss_the_black_stalker::JustSummoned().
Reset()
void BossAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_magmus::boss_magmusAI, boss_gyth::boss_gythAI, boss_halycon::boss_halyconAI, boss_highlord_omokk::boss_highlordomokkAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_mor_grayhoof, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_quartermaster_zigris, boss_rend_blackhand::boss_rend_blackhandAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_the_beast::boss_thebeastAI, boss_chromaggus::boss_chromaggusAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_nefarian, boss_razorgore::boss_razorgoreAI, boss_vaelastrasz::boss_vaelAI, boss_baron_geddon::boss_baron_geddonAI, boss_garr::boss_garrAI, boss_golemagg::boss_golemaggAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_curator::boss_curatorAI, boss_midnight::boss_midnightAI, boss_moroes, boss_servant_quarters, boss_shade_of_aran::boss_aranAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_apothecary_hummel::boss_apothecary_hummelAI, boss_baroness_anastari::boss_baroness_anastariAI, boss_jarien, boss_sothos, boss_brutallus::boss_brutallusAI, boss_sacrolash::boss_sacrolashAI, boss_alythess::boss_alythessAI, boss_felmyst::boss_felmystAI, boss_kalecgos::boss_kalecgosAI, boss_muru::boss_muruAI, boss_akilzon::boss_akilzonAI, boss_arlokk::boss_arlokkAI, boss_gahzranka::boss_gahzrankaAI, boss_grilek::boss_grilekAI, boss_hakkar::boss_hakkarAI, boss_jeklik, boss_mandokir::boss_mandokirAI, boss_marli, boss_renataki::boss_renatakiAI, boss_thekal::boss_thekalAI, boss_venoxis::boss_venoxisAI, boss_archimonde::boss_archimondeAI, boss_isalien, boss_onyxia, boss_ayamiss, boss_kurinnaxx, boss_moam, boss_ossirian, boss_bug_trio, boss_eye_of_cthun, boss_cthun, boss_fankriss, boss_huhuran, boss_ouro, boss_sartura, boss_skeram, boss_viscidus, boss_amanitar, boss_elder_nadox, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, boss_krik_thir::boss_krik_thirAI, boss_sartharion::boss_sartharionAI, boss_sartharion_dragonAI, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_sartharion_shadron::boss_sartharion_shadronAI, boss_sartharion_vesperon::boss_sartharion_vesperonAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_dred::boss_dredAI, boss_novos::boss_novosAI, boss_tharon_ja::boss_tharon_jaAI, boss_trollgore::boss_trollgoreAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_moorabi::boss_moorabiAI, boss_slad_ran::boss_slad_ranAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_lord_marrowgar, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_sindragosa::boss_sindragosaAI, boss_the_lich_king::boss_the_lich_kingAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_sister_svalna::boss_sister_svalnaAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_four_horsemen::boss_four_horsemenAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, boss_grobbulus::boss_grobbulusAI, boss_heigan::boss_heiganAI, boss_kelthuzad::boss_kelthuzadAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_noth::boss_nothAI, boss_patchwerk::boss_patchwerkAI, boss_razuvious::boss_razuviousAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_anomalus::boss_anomalusAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_keristrasza::boss_keristraszaAI, boss_magus_telestra::boss_magus_telestraAI, boss_ormorok::boss_ormorokAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_mother_shahraz::boss_shahrazAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_supremus::boss_supremusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_najentus::boss_najentusAI, boss_illidari_council::boss_illidari_councilAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_lady_vashj::boss_lady_vashjAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_ghazan, boss_hungarfen, boss_gruul::boss_gruulAI, boss_high_king_maulgar::boss_high_king_maulgarAI, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI, boss_magtheridon::boss_magtheridonAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_commander_sarannis::boss_commander_sarannisAI, boss_high_botanist_freywinn::boss_high_botanist_freywinnAI, boss_laj::boss_lajAI, boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI, boss_warp_splinter::boss_warp_splinterAI, boss_alar::boss_alarAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_kaelthas::boss_kaelthasAI, and boss_void_reaver::boss_void_reaverAI.
{ _Reset(); }
References _Reset().
Referenced by boss_jindo::EnterEvadeMode(), boss_lord_valthalak::boss_lord_valthalakAI::Reset(), boss_curator::boss_curatorAI::Reset(), boss_midnight::boss_midnightAI::Reset(), boss_moroes::Reset(), boss_brutallus::boss_brutallusAI::Reset(), boss_sacrolash::boss_sacrolashAI::Reset(), boss_alythess::boss_alythessAI::Reset(), boss_felmyst::boss_felmystAI::Reset(), boss_kalecgos::boss_kalecgosAI::Reset(), boss_muru::boss_muruAI::Reset(), boss_grilek::boss_grilekAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), boss_marli::Reset(), boss_onyxia::Reset(), boss_ayamiss::Reset(), boss_kurinnaxx::Reset(), boss_ossirian::Reset(), boss_bug_trio::Reset(), boss_eye_of_cthun::Reset(), boss_cthun::Reset(), boss_fankriss::Reset(), boss_huhuran::Reset(), boss_viscidus::Reset(), boss_anub_arak::boss_anub_arakAI::Reset(), boss_hadronox::boss_hadronoxAI::Reset(), boss_krik_thir::boss_krik_thirAI::Reset(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::Reset(), boss_general_zarithrian::boss_general_zarithrianAI::Reset(), boss_halion::boss_halionAI::Reset(), boss_saviana_ragefire::boss_saviana_ragefireAI::Reset(), boss_dred::boss_dredAI::Reset(), boss_novos::boss_novosAI::Reset(), boss_tharon_ja::boss_tharon_jaAI::Reset(), boss_trollgore::boss_trollgoreAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), boss_eck::boss_eckAI::Reset(), boss_gal_darah::boss_gal_darahAI::Reset(), boss_moorabi::boss_moorabiAI::Reset(), boss_slad_ran::boss_slad_ranAI::Reset(), boss_anubrekhan::boss_anubrekhanAI::Reset(), boss_faerlina::boss_faerlinaAI::Reset(), boss_four_horsemen::boss_four_horsemenAI::Reset(), boss_gluth::boss_gluthAI::Reset(), boss_gothik::boss_gothikAI::Reset(), boss_grobbulus::boss_grobbulusAI::Reset(), boss_heigan::boss_heiganAI::Reset(), boss_kelthuzad::boss_kelthuzadAI::Reset(), boss_loatheb::boss_loathebAI::Reset(), boss_maexxna::boss_maexxnaAI::Reset(), boss_noth::boss_nothAI::Reset(), boss_patchwerk::boss_patchwerkAI::Reset(), boss_razuvious::boss_razuviousAI::Reset(), boss_sapphiron::boss_sapphironAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_anomalus::boss_anomalusAI::Reset(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::Reset(), boss_keristrasza::boss_keristraszaAI::Reset(), boss_magus_telestra::boss_magus_telestraAI::Reset(), boss_ormorok::boss_ormorokAI::Reset(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::Reset(), boss_illidan_stormrage::boss_illidan_stormrageAI::Reset(), boss_mother_shahraz::boss_shahrazAI::Reset(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::Reset(), boss_shade_of_akama::boss_shade_of_akamaAI::Reset(), boss_supremus::boss_supremusAI::Reset(), boss_teron_gorefiend::boss_teron_gorefiendAI::Reset(), boss_najentus::boss_najentusAI::Reset(), boss_illidari_council::boss_illidari_councilAI::Reset(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::Reset(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::Reset(), boss_lady_vashj::boss_lady_vashjAI::Reset(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::Reset(), boss_the_lurker_below::boss_the_lurker_belowAI::Reset(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::Reset(), boss_ghazan::Reset(), boss_hungarfen::Reset(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::Reset(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::Reset(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::Reset(), boss_alar::boss_alarAI::Reset(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::Reset(), boss_kaelthas::boss_kaelthasAI::Reset(), and boss_void_reaver::boss_void_reaverAI::Reset().
ScheduleTasks()
virtual void BossAI::ScheduleTasks () inline virtual
Reimplemented in boss_ayamiss, and boss_cthun.
{ }
Referenced by _EnterCombat().
SummonedCreatureDespawn()
void BossAI::SummonedCreatureDespawn (Creature * summon) override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_anubrekhan::boss_anubrekhanAI, boss_gothik::boss_gothikAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_ossirian, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_sindragosa::boss_sindragosaAI, boss_grobbulus::boss_grobbulusAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_supremus::boss_supremusAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, and boss_vazruden_the_herald::boss_vazruden_the_heraldAI.
{
    summons.Despawn(summon);
}
References SummonList::Despawn(), and summons.
Referenced by boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn(), and boss_sindragosa::boss_sindragosaAI::SummonedCreatureDespawn().
SummonedCreatureDespawnAll()
void BossAI::SummonedCreatureDespawnAll () override virtual
Reimplemented from CreatureAI.
{
    summons.DespawnAll();
}
References SummonList::DespawnAll(), and summons.
TeleportCheaters()
void BossAI::TeleportCheaters () protected
{
    float x, y, z;
    me->GetPosition(x, y, z);
    ThreatContainer::StorageType threatList = me->GetThreatMgr().GetThreatList();
    for (ThreatContainer::StorageType::const_iterator itr = threatList.begin(); itr != threatList.end(); ++itr)
        if (Unit* target = (*itr)->getTarget())
            if (target->GetTypeId() == TYPEID_PLAYER && !IsInBoundary(target))
                target->NearTeleportTo(x, y, z, 0);
}
References Position::GetPosition(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), CreatureAI::IsInBoundary(), ScriptedAI::me, and TYPEID_PLAYER.
UpdateAI()
void BossAI::UpdateAI (uint32 diff) override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_sartharion_dragonAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_anubshiah::boss_anubshiahAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_eviscerator::boss_evisceratorAI, boss_gorosh_the_dervish::boss_gorosh_the_dervishAI, boss_grizzle::boss_grizzleAI, boss_hedrum::boss_hedrumAI, boss_magmus::boss_magmusAI, boss_moira_bronzebeardAI, boss_high_priestess_thaurissanAI, boss_okthor::boss_okthorAI, boss_drakkisath::boss_drakkisathAI, boss_gyth::boss_gythAI, boss_halycon::boss_halyconAI, boss_highlord_omokk::boss_highlordomokkAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_mor_grayhoof, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_quartermaster_zigris, boss_rend_blackhand::boss_rend_blackhandAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_the_beast::boss_thebeastAI, boss_urok_doomhowl::boss_urok_doomhowlAI, boss_broodlord::boss_broodlordAI, boss_chromaggus::boss_chromaggusAI, boss_ebonroc::boss_ebonrocAI, boss_firemaw::boss_firemawAI, boss_flamegor::boss_flamegorAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_nefarian, boss_razorgore::boss_razorgoreAI, boss_vaelastrasz::boss_vaelAI, boss_garr::boss_garrAI, boss_golemagg::boss_golemaggAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_curator::boss_curatorAI, boss_maiden_of_virtue, boss_midnight::boss_midnightAI, boss_moroes, boss_servant_quarters, boss_shade_of_aran::boss_aranAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_apothecary_hummel::boss_apothecary_hummelAI, boss_baroness_anastari::boss_baroness_anastariAI, boss_jarien, boss_sothos, boss_brutallus::boss_brutallusAI, boss_sacrolash::boss_sacrolashAI, boss_alythess::boss_alythessAI, boss_felmyst::boss_felmystAI, boss_kalecgos::boss_kalecgosAI, boss_muru::boss_muruAI, boss_akilzon::boss_akilzonAI, boss_arlokk::boss_arlokkAI, boss_gahzranka::boss_gahzrankaAI, boss_grilek::boss_grilekAI, boss_hakkar::boss_hakkarAI, boss_hazzarah, boss_jeklik, boss_jindo, boss_mandokir::boss_mandokirAI, boss_marli, boss_renataki::boss_renatakiAI, boss_thekal::boss_thekalAI, boss_venoxis::boss_venoxisAI, boss_wushoolay::boss_wushoolayAI, boss_archimonde::boss_archimondeAI, boss_isalien, boss_onyxia, boss_ayamiss, boss_buru, boss_kurinnaxx, boss_moam, boss_ossirian, boss_rajaxx, boss_bug_trio, boss_eye_of_cthun, boss_cthun, boss_fankriss, boss_huhuran, boss_ouro, boss_sartura, boss_skeram, boss_twinemperorsAI, boss_viscidus, boss_elder_nadox, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, boss_krik_thir::boss_krik_thirAI, boss_sartharion::boss_sartharionAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_dred::boss_dredAI, boss_novos::boss_novosAI, boss_tharon_ja::boss_tharon_jaAI, boss_trollgore::boss_trollgoreAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_moorabi::boss_moorabiAI, boss_slad_ran::boss_slad_ranAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_lord_marrowgar, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_sindragosa::boss_sindragosaAI, boss_the_lich_king::boss_the_lich_kingAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_sister_svalna::boss_sister_svalnaAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_four_horsemen::boss_four_horsemenAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, boss_grobbulus::boss_grobbulusAI, boss_heigan::boss_heiganAI, boss_kelthuzad::boss_kelthuzadAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_noth::boss_nothAI, boss_patchwerk::boss_patchwerkAI, boss_razuvious::boss_razuviousAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_anomalus::boss_anomalusAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_keristrasza::boss_keristraszaAI, boss_magus_telestra::boss_magus_telestraAI, boss_ormorok::boss_ormorokAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_mother_shahraz::boss_shahrazAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_supremus::boss_supremusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_najentus::boss_najentusAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_lady_vashj::boss_lady_vashjAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_ghazan, boss_hungarfen, boss_the_black_stalker, boss_gruul::boss_gruulAI, boss_high_king_maulgar::boss_high_king_maulgarAI, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI, boss_magtheridon::boss_magtheridonAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_warbringer_omrogg::boss_warbringer_omroggAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_zereketh_the_unbound::boss_zereketh_the_unboundAI, boss_commander_sarannis::boss_commander_sarannisAI, boss_high_botanist_freywinn::boss_high_botanist_freywinnAI, boss_laj::boss_lajAI, boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI, boss_warp_splinter::boss_warp_splinterAI, boss_alar::boss_alarAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_kaelthas::boss_kaelthasAI, boss_void_reaver::boss_void_reaverAI, boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI, boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI, boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI, boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI, boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI, boss_illidari_council::boss_illidari_councilAI, and boss_vazruden_the_herald::boss_vazruden_the_heraldAI.
{
    if (!UpdateVictim())
    {
        return;
    }
    events.Update(diff);
    if (me->HasUnitState(UNIT_STATE_CASTING))
    {
        return;
    }
    while (uint32 const eventId = events.ExecuteEvent())
    {
        ExecuteEvent(eventId);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
    }
    DoMeleeAttackIfReady();
}
References UnitAI::DoMeleeAttackIfReady(), ExecuteEvent(), Unit::HasUnitState(), ScriptedAI::me, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_bossId
uint32 const BossAI::_bossId private
Referenced by _EnterCombat(), _JustDied(), _Reset(), and CanRespawn().
events
EventMap BossAI::events protected
instance
InstanceScript* const BossAI::instance
Referenced by _EnterCombat(), _JustDied(), _Reset(), boss_hakkar::boss_hakkarAI::ApplyHakkarPowerStacks(), boss_professor_putricide::boss_professor_putricideAI::AttackStart(), boss_felmyst::boss_felmystAI::boss_felmystAI(), boss_prince_valanar_icc::boss_prince_valanarAI::boss_prince_valanarAI(), boss_victor_nefarius::boss_victor_nefariusAI::boss_victor_nefariusAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::boss_wrath_scryer_soccothratesAI(), BossAI(), boss_majordomo::boss_majordomoAI::CanAIAttack(), boss_keristrasza::boss_keristraszaAI::CanRemovePrison(), CanRespawn(), boss_moira_bronzebeardAI::CastOnEmperorIfPossible(), boss_prince_valanar_icc::boss_prince_valanarAI::CheckRoom(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::CleanAuras(), boss_sartharion_dragonAI::ClearInstance(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ClearInstance(), boss_kalecgos::boss_kalecgosAI::ClearPlayerAuras(), boss_prince_valanar_icc::boss_prince_valanarAI::DamageDealt(), boss_sindragosa::boss_sindragosaAI::DamageTaken(), boss_buru::DamageTaken(), boss_halion::boss_halionAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken(), boss_bug_trio::DamageTaken(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), boss_taldaram::DoAction(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), boss_kalecgos::boss_kalecgosAI::DoAction(), boss_onyxia::DoAction(), boss_hadronox::boss_hadronoxAI::DoAction(), boss_illidari_council::boss_illidari_councilAI::DoAction(), boss_razorgore::boss_razorgoreAI::DoChangePhase(), boss_sartharion_dragonAI::EnterCombat(), boss_magmus::boss_magmusAI::EnterCombat(), boss_razorgore::boss_razorgoreAI::EnterCombat(), boss_shade_of_aran::boss_aranAI::EnterCombat(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::EnterCombat(), boss_akilzon::boss_akilzonAI::EnterCombat(), boss_hakkar::boss_hakkarAI::EnterCombat(), boss_volazj::EnterCombat(), boss_anub_arak::boss_anub_arakAI::EnterCombat(), boss_lord_marrowgar::EnterCombat(), boss_sister_svalna::boss_sister_svalnaAI::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), boss_the_lich_king::boss_the_lich_kingAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), boss_sacrolash::boss_sacrolashAI::EnterCombat(), boss_alythess::boss_alythessAI::EnterCombat(), boss_onyxia::EnterCombat(), boss_buru::EnterCombat(), boss_halion::boss_halionAI::EnterCombat(), boss_trollgore::boss_trollgoreAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), boss_bug_trio::EnterCombatWithTrio(), boss_gyth::boss_gythAI::EnterEvadeMode(), boss_rend_blackhand::boss_rend_blackhandAI::EnterEvadeMode(), boss_sacrolash::boss_sacrolashAI::EnterEvadeMode(), boss_alythess::boss_alythessAI::EnterEvadeMode(), boss_buru::EnterEvadeMode(), boss_amanitar::EnterEvadeMode(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterEvadeMode(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterEvadeMode(), boss_festergut::boss_festergutAI::EnterEvadeMode(), boss_rotface::boss_rotfaceAI::EnterEvadeMode(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), boss_illidan_stormrage::boss_illidan_stormrageAI::EnterEvadeMode(), boss_ouro::EnterEvadeMode(), boss_bug_trio::EvadeAllBosses(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_twinemperorsAI::GetTwin(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::GoToMinchar(), boss_urok_doomhowl::boss_urok_doomhowlAI::InitializeAI(), boss_majordomo::boss_majordomoAI::InitializeAI(), boss_taldaram::InitializeAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::InitializeAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::InitializeAI(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::JustDied(), boss_gyth::boss_gythAI::JustDied(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::JustDied(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::JustDied(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::JustDied(), boss_victor_nefarius::boss_victor_nefariusAI::JustDied(), boss_razorgore::boss_razorgoreAI::JustDied(), boss_shade_of_aran::boss_aranAI::JustDied(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::JustDied(), boss_apothecary_hummel::boss_apothecary_hummelAI::JustDied(), boss_baroness_anastari::boss_baroness_anastariAI::JustDied(), boss_sacrolash::boss_sacrolashAI::JustDied(), boss_alythess::boss_alythessAI::JustDied(), boss_akilzon::boss_akilzonAI::JustDied(), boss_mandokir::boss_mandokirAI::JustDied(), boss_thekal::boss_thekalAI::JustDied(), boss_rajaxx::JustDied(), boss_eye_of_cthun::JustDied(), boss_viscidus::JustDied(), boss_amanitar::JustDied(), boss_sartharion_dragonAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_festergut::boss_festergutAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), boss_sindragosa::boss_sindragosaAI::JustDied(), boss_sister_svalna::boss_sister_svalnaAI::JustDied(), boss_high_king_maulgar::boss_high_king_maulgarAI::JustDied(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::JustDied(), boss_warbringer_omrogg::boss_warbringer_omroggAI::JustDied(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustDied(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::JustDied(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::JustDied(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustDied(), boss_lord_valthalak::boss_lord_valthalakAI::JustDied(), boss_moroes::JustDied(), boss_brutallus::boss_brutallusAI::JustDied(), boss_felmyst::boss_felmystAI::JustDied(), boss_buru::JustDied(), boss_kurinnaxx::JustDied(), boss_bug_trio::JustDied(), boss_cthun::JustDied(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_novos::boss_novosAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_shade_of_akama::boss_shade_of_akamaAI::JustDied(), boss_majordomo::boss_majordomoAI::JustReachedHome(), boss_arlokk::boss_arlokkAI::JustReachedHome(), boss_halion::boss_halionAI::JustReachedHome(), boss_prince_valanar_icc::boss_prince_valanarAI::JustReachedHome(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustReachedHome(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustReachedHome(), boss_festergut::boss_festergutAI::JustReachedHome(), boss_lord_marrowgar::JustReachedHome(), boss_professor_putricide::boss_professor_putricideAI::JustReachedHome(), boss_rotface::boss_rotfaceAI::JustReachedHome(), boss_sindragosa::boss_sindragosaAI::JustReachedHome(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustReachedHome(), boss_eye_of_cthun::JustSummoned(), boss_sartharion_dragonAI::JustSummoned(), boss_mandokir::boss_mandokirAI::KilledUnit(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), boss_mandokir::boss_mandokirAI::MovementInform(), boss_bug_trio::MovementInform(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::MovementInform(), boss_professor_putricide::boss_professor_putricideAI::MovementInform(), boss_lady_vashj::boss_lady_vashjAI::MovementInform(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::OpenDoors(), boss_kaelthas::boss_kaelthasAI::PrepareAdvisors(), boss_magmus::boss_magmusAI::Reset(), boss_gyth::boss_gythAI::Reset(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_razorgore::boss_razorgoreAI::Reset(), boss_majordomo::boss_majordomoAI::Reset(), boss_servant_quarters::Reset(), boss_shade_of_aran::boss_aranAI::Reset(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::Reset(), boss_baroness_anastari::boss_baroness_anastariAI::Reset(), boss_felmyst::boss_felmystAI::Reset(), boss_akilzon::boss_akilzonAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), boss_thekal::boss_thekalAI::Reset(), boss_onyxia::Reset(), boss_bug_trio::Reset(), boss_eye_of_cthun::Reset(), boss_ouro::Reset(), boss_volazj::Reset(), boss_anub_arak::boss_anub_arakAI::Reset(), boss_sartharion::boss_sartharionAI::Reset(), boss_sartharion_dragonAI::Reset(), boss_general_zarithrian::boss_general_zarithrianAI::Reset(), boss_novos::boss_novosAI::Reset(), boss_prince_valanar_icc::boss_prince_valanarAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), boss_lord_marrowgar::Reset(), boss_professor_putricide::boss_professor_putricideAI::Reset(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), boss_sartharion::boss_sartharionAI::RespawnDragons(), boss_thekal::boss_thekalAI::ReviveZealot(), boss_ayamiss::ScheduleTasks(), boss_cthun::ScheduleTasks(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SetData(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SetGate(), boss_kaelthas::boss_kaelthasAI::SetRoomState(), boss_victor_nefarius::boss_victor_nefariusAI::sGossipSelect(), boss_onyxia::SpellHitTarget(), boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::SummonedCreatureDies(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP1(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_servant_quarters::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), and boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateRunes().
scheduler
TaskScheduler BossAI::scheduler protected
Referenced by _JustDied(), _Reset(), boss_ayamiss::DamageTaken(), boss_ayamiss::MovementInform(), boss_ayamiss::Reset(), boss_eye_of_cthun::Reset(), boss_cthun::Reset(), boss_eye_of_cthun::ScheduleTask(), boss_ayamiss::ScheduleTasks(), boss_cthun::ScheduleTasks(), boss_cthun::SummonedCreatureDies(), boss_ayamiss::UpdateAI(), and boss_cthun::UpdateAI().
summons
SummonList BossAI::summons protected
Referenced by _JustDied(), _Reset(), boss_volazj::CheckPhaseMinions(), boss_sartharion_dragonAI::ClearInstance(), boss_sartharion::boss_sartharionAI::DamageTaken(), boss_illidan_stormrage::boss_illidan_stormrageAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_victor_nefarius::boss_victor_nefariusAI::DoAction(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), boss_taldaram::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), boss_drakkari_colossus::boss_drakkari_colossusAI::DoAction(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), boss_illidan_stormrage::boss_illidan_stormrageAI::EnterCombat(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_krik_thir::boss_krik_thirAI::GetData(), boss_professor_putricide::boss_professor_putricideAI::GetData(), boss_warbringer_omrogg::boss_warbringer_omroggAI::GetLeftHead(), boss_moroes::GetRandomGuest(), boss_warbringer_omrogg::boss_warbringer_omroggAI::GetRightHead(), boss_moroes::InitializeGuests(), boss_sacrolash::boss_sacrolashAI::JustDied(), boss_alythess::boss_alythessAI::JustDied(), boss_viscidus::JustDied(), boss_sartharion_dragonAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustDied(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustDied(), boss_ossirian::JustSummoned(), JustSummoned(), boss_gyth::boss_gythAI::JustSummoned(), boss_rend_blackhand::boss_rend_blackhandAI::JustSummoned(), boss_razorgore::boss_razorgoreAI::JustSummoned(), boss_curator::boss_curatorAI::JustSummoned(), boss_midnight::boss_midnightAI::JustSummoned(), boss_apothecary_hummel::boss_apothecary_hummelAI::JustSummoned(), boss_sacrolash::boss_sacrolashAI::JustSummoned(), boss_felmyst::boss_felmystAI::JustSummoned(), boss_muru::boss_muruAI::JustSummoned(), boss_hazzarah::JustSummoned(), boss_isalien::JustSummoned(), boss_onyxia::JustSummoned(), boss_eye_of_cthun::JustSummoned(), boss_amanitar::JustSummoned(), boss_jedoga_shadowseeker::JustSummoned(), boss_taldaram::JustSummoned(), boss_anub_arak::boss_anub_arakAI::JustSummoned(), boss_hadronox::boss_hadronoxAI::JustSummoned(), boss_krik_thir::boss_krik_thirAI::JustSummoned(), boss_sartharion::boss_sartharionAI::JustSummoned(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustSummoned(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustSummoned(), boss_general_zarithrian::boss_general_zarithrianAI::JustSummoned(), boss_halion::boss_halionAI::JustSummoned(), boss_novos::boss_novosAI::JustSummoned(), boss_trollgore::boss_trollgoreAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_slad_ran::boss_slad_ranAI::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_professor_putricide::boss_professor_putricideAI::JustSummoned(), boss_rotface::boss_rotfaceAI::JustSummoned(), boss_sindragosa::boss_sindragosaAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_anomalus::boss_anomalusAI::JustSummoned(), boss_magus_telestra::boss_magus_telestraAI::JustSummoned(), boss_ormorok::boss_ormorokAI::JustSummoned(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::JustSummoned(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustSummoned(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustSummoned(), boss_supremus::boss_supremusAI::JustSummoned(), boss_teron_gorefiend::boss_teron_gorefiendAI::JustSummoned(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustSummoned(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustSummoned(), boss_lady_vashj::boss_lady_vashjAI::JustSummoned(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustSummoned(), boss_the_lurker_below::boss_the_lurker_belowAI::JustSummoned(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::JustSummoned(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::JustSummoned(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::JustSummoned(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::JustSummoned(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustSummoned(), npc_warden_mellichar::npc_warden_mellicharAI::JustSummoned(), boss_alar::boss_alarAI::JustSummoned(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::JustSummoned(), boss_kaelthas::boss_kaelthasAI::JustSummoned(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::JustSummoned(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustSummoned(), boss_warbringer_omrogg::boss_warbringer_omroggAI::JustSummoned(), boss_ayamiss::JustSummoned(), boss_midnight::boss_midnightAI::KilledUnit(), boss_illidan_stormrage::boss_illidan_stormrageAI::MovementInform(), boss_jedoga_shadowseeker::MovementInform(), boss_the_lich_king::boss_the_lich_kingAI::MovementInform(), boss_kaelthas::boss_kaelthasAI::PrepareAdvisors(), boss_gyth::boss_gythAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_razorgore::boss_razorgoreAI::Reset(), boss_majordomo::boss_majordomoAI::Reset(), boss_apothecary_hummel::boss_apothecary_hummelAI::Reset(), boss_isalien::Reset(), boss_hadronox::boss_hadronoxAI::Reset(), boss_prince_valanar_icc::boss_prince_valanarAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset(), boss_the_lurker_below::boss_the_lurker_belowAI::Reset(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SetData(), boss_kaelthas::boss_kaelthasAI::SetData(), boss_the_lich_king::boss_the_lich_kingAI::SpellHitTarget(), boss_taldaram::SpellHitTarget(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonChannelers(), boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn(), SummonedCreatureDespawn(), boss_ossirian::SummonedCreatureDespawn(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDespawn(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::SummonedCreatureDespawn(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonedCreatureDespawn(), boss_illidan_stormrage::boss_illidan_stormrageAI::SummonedCreatureDespawn(), boss_supremus::boss_supremusAI::SummonedCreatureDespawn(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::SummonedCreatureDespawn(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDespawn(), SummonedCreatureDespawnAll(), boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDies(), boss_moam::SummonedCreatureDies(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), boss_victor_nefarius::boss_victor_nefariusAI::SummonedCreatureDies(), boss_ragnaros::boss_ragnarosAI::SummonedCreatureDies(), boss_midnight::boss_midnightAI::SummonedCreatureDies(), boss_hazzarah::SummonedCreatureDies(), boss_krik_thir::boss_krik_thirAI::SummonedCreatureDies(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDies(), boss_illidan_stormrage::boss_illidan_stormrageAI::SummonedCreatureDies(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::SummonedCreatureDies(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::SummonedCreatureDies(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonedCreatureDies(), boss_the_black_stalker::SummonedCreatureDies(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDies(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::SummonedCreatureDies(), boss_kaelthas::boss_kaelthasAI::SummonedCreatureDies(), boss_viscidus::SummonedCreatureDies(), boss_jedoga_shadowseeker::SummonedCreatureDies(), boss_sartharion::boss_sartharionAI::SummonLavaWaves(), boss_midnight::boss_midnightAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::UpdateAI(), and boss_vazruden_the_herald::boss_vazruden_the_heraldAI::UpdateAI().