AzerothCore: npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI Struct Reference
npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI Struct Reference
Public Member Functions
npc_overlord_drakuru_betrayalAI (Creature *creature)
void EnterEvadeMode (EvadeReason why) override
void Reset () override
void MoveInLineOfSight (Unit *who) override
void JustSummoned (Creature *cr) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
SummonList summons
ObjectGuid playerGUID
ObjectGuid lichGUID
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_overlord_drakuru_betrayalAI()
npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::npc_overlord_drakuru_betrayalAI (Creature * creature) inline
                                                            : ScriptedAI(creature), summons(me)
        {
        }
Member Function Documentation
DamageTaken()
void npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (damage >= me->GetHealth() && !me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
            {
                damage = 0;
                me->RemoveAllAuras();
                me->CombatStop();
                me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->SetFaction(FACTION_FRIENDLY);
                events.Reset();
                events.ScheduleEvent(EVENT_BETRAYAL_4, 1s);
            }
        }
References Unit::CombatStop(), EVENT_BETRAYAL_4, FACTION_FRIENDLY, Unit::GetHealth(), Unit::HasUnitFlag(), ScriptedAI::me, Unit::RemoveAllAuras(), Unit::SetFaction(), Unit::SetUnitFlag(), and UNIT_FLAG_NON_ATTACKABLE.
EnterEvadeMode()
void npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            if (playerGUID)
                if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
                    if (player->IsWithinDistInMap(me, 80))
                        return;
            me->SetFaction(FACTION_UNDEAD_SCOURGE);
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            ScriptedAI::EnterEvadeMode(why);
        }
References CreatureAI::EnterEvadeMode(), FACTION_UNDEAD_SCOURGE, ObjectAccessor::GetPlayer(), ScriptedAI::me, playerGUID, Unit::RemoveUnitFlag(), Unit::SetFaction(), and UNIT_FLAG_NON_ATTACKABLE.
Referenced by MoveInLineOfSight(), and UpdateAI().
JustEngagedWith()
void npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            Talk(SAY_DRAKURU_3);
            events.ScheduleEvent(EVENT_BETRAYAL_SHADOW_BOLT, 2s);
            events.ScheduleEvent(EVENT_BETRAYAL_CRYSTAL, 5s);
            events.ScheduleEvent(EVENT_BETRAYAL_COMBAT_TALK, 20s);
        }
References EVENT_BETRAYAL_COMBAT_TALK, EVENT_BETRAYAL_CRYSTAL, EVENT_BETRAYAL_SHADOW_BOLT, and SAY_DRAKURU_3.
JustSummoned()
void npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(cr);
            if (cr->GetEntry() == NPC_BLIGHTBLOOD_TROLL)
                cr->CastSpell(cr, SPELL_TELEPORT_EFFECT, true);
            else
            {
                me->SetFacingToObject(cr);
                lichGUID = cr->GetGUID();
                float o = me->GetAngle(cr);
                cr->GetMotionMaster()->MovePoint(0, me->GetPositionX() + cos(o) * 6.0f, me->GetPositionY() + std::sin(o) * 6.0f, me->GetPositionZ());
            }
        }
References Unit::CastSpell(), Position::GetAngle(), Object::GetEntry(), Object::GetGUID(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), lichGUID, ScriptedAI::me, MotionMaster::MovePoint(), NPC_BLIGHTBLOOD_TROLL, Unit::SetFacingToObject(), SPELL_TELEPORT_EFFECT, SummonList::Summon(), and summons.
MoveInLineOfSight()
void npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
        {
            if (who->IsPlayer())
            {
                if (playerGUID)
                {
                    if (who->GetGUID() != playerGUID)
                    {
                        Player* player = ObjectAccessor::GetPlayer(*me, playerGUID);
                        if (player && player->IsWithinDistInMap(me, 80))
                            who->ToPlayer()->NearTeleportTo(6143.76f, -1969.7f, 417.57f, 2.08f);
                        else
{
                            EnterEvadeMode(EVADE_REASON_OTHER);
                            return;
                        }
                    }
                    else
                        ScriptedAI::MoveInLineOfSight(who);
                }
                else if (who->ToPlayer()->GetQuestStatus(QUEST_BETRAYAL) == QUEST_STATUS_INCOMPLETE && who->HasAura(SPELL_SCOURGE_DISGUISE))
                {
                    me->SetVisible(true);
                    playerGUID = who->GetGUID();
                    events.ScheduleEvent(EVENT_BETRAYAL_1, 5s);
                }
            }
            else
                ScriptedAI::MoveInLineOfSight(who);
        }
References EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_BETRAYAL_1, Object::GetGUID(), ObjectAccessor::GetPlayer(), Player::GetQuestStatus(), Unit::HasAura(), Object::IsPlayer(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), Unit::NearTeleportTo(), playerGUID, QUEST_BETRAYAL, QUEST_STATUS_INCOMPLETE, Unit::SetVisible(), SPELL_SCOURGE_DISGUISE, and Object::ToPlayer().
Reset()
void npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Reset();
            summons.DespawnAll();
            playerGUID.Clear();
            lichGUID.Clear();
            me->SetFaction(FACTION_UNDEAD_SCOURGE);
            me->SetVisible(false);
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
        }
References ObjectGuid::Clear(), SummonList::DespawnAll(), FACTION_UNDEAD_SCOURGE, lichGUID, ScriptedAI::me, playerGUID, Unit::RemoveUnitFlag(), Unit::SetFaction(), Unit::SetVisible(), summons, and UNIT_FLAG_NON_ATTACKABLE.
SpellHit()
void npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_TOUCH_OF_DEATH)
            {
                me->CastSpell(me, SPELL_DRAKURU_DEATH, true);
                me->CastSpell(me, SPELL_SUMMON_SKULL, true);
            }
        }
References Unit::CastSpell(), SpellInfo::Id, ScriptedAI::me, SPELL_DRAKURU_DEATH, SPELL_SUMMON_SKULL, and SPELL_TOUCH_OF_DEATH.
SpellHitTarget()
void npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::SpellHitTarget (Unit * target, SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_THROW_PORTAL_CRYSTAL)
                if (Aura* aura = target->AddAura(SPELL_ARTHAS_PORTAL, target))
                    aura->SetDuration(48000);
        }
References Unit::AddAura(), SpellInfo::Id, SPELL_ARTHAS_PORTAL, and SPELL_THROW_PORTAL_CRYSTAL.
UpdateAI()
void npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_BETRAYAL_1:
                    Talk(SAY_DRAKURU_0);
                    events.ScheduleEvent(EVENT_BETRAYAL_2, 5s);
                    break;
                case EVENT_BETRAYAL_2:
                    me->SummonCreature(NPC_BLIGHTBLOOD_TROLL, 6184.1f, -1969.9f, 586.76f, 4.5f);
                    me->SummonCreature(NPC_BLIGHTBLOOD_TROLL, 6222.9f, -2026.5f, 586.76f, 2.9f);
                    me->SummonCreature(NPC_BLIGHTBLOOD_TROLL, 6166.2f, -2065.4f, 586.76f, 1.4f);
                    me->SummonCreature(NPC_BLIGHTBLOOD_TROLL, 6127.5f, -2008.7f, 586.76f, 0.0f);
                    events.ScheduleEvent(EVENT_BETRAYAL_3, 5s);
                    break;
                case EVENT_BETRAYAL_3:
                    Talk(SAY_DRAKURU_1);
                    Talk(SAY_DRAKURU_2);
                    if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
                        player->CastSpell(player, SPELL_SCOURGE_DISGUISE_EXPIRING, true);
                    if (Aura* aur = me->AddAura(SPELL_BLIGHT_FOG, me))
                        aur->SetDuration(22000);
                    break;
                case EVENT_BETRAYAL_4:
                    Talk(SAY_DRAKURU_5);
                    events.ScheduleEvent(EVENT_BETRAYAL_5, 6s);
                    break;
                case EVENT_BETRAYAL_5:
                    Talk(SAY_DRAKURU_6);
                    me->CastSpell(me, SPELL_THROW_PORTAL_CRYSTAL, true);
                    events.ScheduleEvent(EVENT_BETRAYAL_6, 8s);
                    break;
                case EVENT_BETRAYAL_6:
                    me->SummonCreature(NPC_LICH_KING, 6142.9f, -2011.6f, 590.86f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 41000);
                    events.ScheduleEvent(EVENT_BETRAYAL_7, 8s);
                    break;
                case EVENT_BETRAYAL_7:
                    Talk(SAY_DRAKURU_7);
                    events.ScheduleEvent(EVENT_BETRAYAL_8, 5s);
                    break;
                case EVENT_BETRAYAL_8:
                    if (Creature* lich = ObjectAccessor::GetCreature(*me, lichGUID))
                        lich->AI()->Talk(SAY_LICH_7);
                    events.ScheduleEvent(EVENT_BETRAYAL_9, 6s);
                    break;
                case EVENT_BETRAYAL_9:
                    if (Creature* lich = ObjectAccessor::GetCreature(*me, lichGUID))
                    {
                        lich->AI()->Talk(SAY_LICH_8);
                        lich->CastSpell(me, SPELL_TOUCH_OF_DEATH, false);
                    }
                    events.ScheduleEvent(EVENT_BETRAYAL_10, 4s);
                    break;
                case EVENT_BETRAYAL_10:
                    me->SetVisible(false);
                    if (Creature* lich = ObjectAccessor::GetCreature(*me, lichGUID))
                        lich->AI()->Talk(SAY_LICH_9);
                    events.ScheduleEvent(EVENT_BETRAYAL_11, 4s);
                    break;
                case EVENT_BETRAYAL_11:
                    if (Creature* lich = ObjectAccessor::GetCreature(*me, lichGUID))
                        lich->AI()->Talk(SAY_LICH_10);
                    events.ScheduleEvent(EVENT_BETRAYAL_12, 6s);
                    break;
                case EVENT_BETRAYAL_12:
                    if (Creature* lich = ObjectAccessor::GetCreature(*me, lichGUID))
                        lich->AI()->Talk(SAY_LICH_11);
                    events.ScheduleEvent(EVENT_BETRAYAL_13, 3s);
                    break;
                case EVENT_BETRAYAL_13:
                    if (Creature* lich = ObjectAccessor::GetCreature(*me, lichGUID))
                    {
                        lich->AI()->Talk(SAY_LICH_12);
                        lich->GetMotionMaster()->MovePoint(0, 6143.8f, -2011.5f, 590.9f);
                    }
                    events.ScheduleEvent(EVENT_BETRAYAL_14, 7s);
                    break;
                case EVENT_BETRAYAL_14:
                    playerGUID.Clear();
                    EnterEvadeMode(EVADE_REASON_OTHER);
                    break;
            }
            if (me->GetFaction() == FACTION_FRIENDLY || me->HasUnitState(UNIT_STATE_CASTING | UNIT_STATE_STUNNED))
                return;
            if (!UpdateVictim())
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_BETRAYAL_SHADOW_BOLT:
                    if (!me->IsWithinMeleeRange(me->GetVictim()))
                        me->CastSpell(me->GetVictim(), SPELL_SHADOW_BOLT, false);
                    events.Repeat(2s);
                    break;
                case EVENT_BETRAYAL_CRYSTAL:
                    if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
                        me->CastSpell(player, SPELL_THROW_BRIGHT_CRYSTAL, true);
                    events.Repeat(6s, 15s);
                    break;
                case EVENT_BETRAYAL_COMBAT_TALK:
                    Talk(SAY_DRAKURU_4);
                    events.Repeat(20s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::AddAura(), Unit::CastSpell(), ObjectGuid::Clear(), UnitAI::DoMeleeAttackIfReady(), EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_BETRAYAL_1, EVENT_BETRAYAL_10, EVENT_BETRAYAL_11, EVENT_BETRAYAL_12, EVENT_BETRAYAL_13, EVENT_BETRAYAL_14, EVENT_BETRAYAL_2, EVENT_BETRAYAL_3, EVENT_BETRAYAL_4, EVENT_BETRAYAL_5, EVENT_BETRAYAL_6, EVENT_BETRAYAL_7, EVENT_BETRAYAL_8, EVENT_BETRAYAL_9, EVENT_BETRAYAL_COMBAT_TALK, EVENT_BETRAYAL_CRYSTAL, EVENT_BETRAYAL_SHADOW_BOLT, FACTION_FRIENDLY, ObjectAccessor::GetCreature(), Unit::GetFaction(), ObjectAccessor::GetPlayer(), Unit::GetVictim(), Unit::HasUnitState(), Unit::IsWithinMeleeRange(), lichGUID, ScriptedAI::me, NPC_BLIGHTBLOOD_TROLL, NPC_LICH_KING, playerGUID, SAY_DRAKURU_0, SAY_DRAKURU_1, SAY_DRAKURU_2, SAY_DRAKURU_4, SAY_DRAKURU_5, SAY_DRAKURU_6, SAY_DRAKURU_7, SAY_LICH_10, SAY_LICH_11, SAY_LICH_12, SAY_LICH_7, SAY_LICH_8, SAY_LICH_9, Unit::SetVisible(), SPELL_BLIGHT_FOG, SPELL_SCOURGE_DISGUISE_EXPIRING, SPELL_SHADOW_BOLT, SPELL_THROW_BRIGHT_CRYSTAL, SPELL_THROW_PORTAL_CRYSTAL, SPELL_TOUCH_OF_DEATH, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, UNIT_STATE_STUNNED, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::events
lichGUID
ObjectGuid npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::lichGUID
Referenced by JustSummoned(), Reset(), and UpdateAI().
playerGUID
ObjectGuid npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::playerGUID
Referenced by EnterEvadeMode(), MoveInLineOfSight(), Reset(), and UpdateAI().
summons
SummonList npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::summons
Referenced by JustSummoned(), and Reset().