AzerothCore: AreaTrigger_at_scent_larkorwi Class Reference
AreaTrigger_at_scent_larkorwi Class Reference
Public Member Functions
AreaTrigger_at_scent_larkorwi ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
AreaTrigger_at_scent_larkorwi()
AreaTrigger_at_scent_larkorwi::AreaTrigger_at_scent_larkorwi () inline
        : AreaTriggerScript("at_scent_larkorwi")
    {
    }
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_scent_larkorwi::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (!player->isDead() && player->GetQuestStatus(QUEST_SCENT_OF_LARKORWI) == QUEST_STATUS_INCOMPLETE)
        {
            if (!player->FindNearestCreature(NPC_LARKORWI_MATE, 15))
                player->SummonCreature(NPC_LARKORWI_MATE, player->GetPositionX() + 5, player->GetPositionY(), player->GetPositionZ(), 3.3f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 100000);
        }
        return false;
    }
References WorldObject::FindNearestCreature(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Player::GetQuestStatus(), Unit::isDead(), NPC_LARKORWI_MATE, QUEST_SCENT_OF_LARKORWI, QUEST_STATUS_INCOMPLETE, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.