AzerothCore: go_celestial_planetarium_access::go_celestial_planetarium_accessAI Struct Reference
go_celestial_planetarium_access::go_celestial_planetarium_accessAI Struct Reference
Public Member Functions
go_celestial_planetarium_accessAI (GameObject *go)
bool GossipHello (Player *player, bool) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Public Attributes
EventMap events
bool _locked
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_celestial_planetarium_accessAI()
go_celestial_planetarium_access::go_celestial_planetarium_accessAI::go_celestial_planetarium_accessAI (GameObject * go) inline
                                                          : GameObjectAI(go)
        {
            _locked = false;
        }
References _locked.
Member Function Documentation
GossipHello()
bool go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello (Player * player, bool) inline override virtual
Reimplemented from GameObjectAI.
        {
            bool hasKey = true;
            if (LockEntry const* lock = sLockStore.LookupEntry(me->GetGOInfo()->goober.lockId))
            {
                hasKey = false;
                for (uint32 i = 0; i < MAX_LOCK_CASE; ++i)
                {
                    if (!lock->Index[i])
                        continue;
                    if (player->HasItemCount(lock->Index[i]))
                    {
                        hasKey = true;
                        break;
                    }
                }
            }
            if (!hasKey)
                return false;
            if (_locked)
                return false;
            _locked = true;
            // Start Algalon event
            me->SetGameObjectFlag(GO_FLAG_IN_USE);
            events.ScheduleEvent(EVENT_DESPAWN_CONSOLE, 5000ms);
            if (Creature* brann = me->SummonCreature(NPC_BRANN_BRONZBEARD_ALG, BrannIntroSpawnPos))
                brann->AI()->DoAction(ACTION_START_INTRO);
            if (InstanceScript* instance = me->GetInstanceScript())
            {
                instance->SetData(DATA_ALGALON_SUMMON_STATE, 1);
                if (GameObject* sigil = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_DOODAD_UL_SIGILDOOR_01)))
                    sigil->SetGoState(GO_STATE_ACTIVE);
                if (GameObject* sigil = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_DOODAD_UL_SIGILDOOR_02)))
                    sigil->SetGoState(GO_STATE_ACTIVE);
                if (Map* map = player->GetMap())
                {
                    if (InstanceMap* instanceMap = map->ToInstanceMap())
                    {
                        instanceMap->PermBindAllPlayers();
                    }
                }
            }
            return false;
        }
References _locked, ACTION_START_INTRO, BrannIntroSpawnPos, DATA_ALGALON_SUMMON_STATE, EVENT_DESPAWN_CONSOLE, ObjectAccessor::GetGameObject(), GameObject::GetGOInfo(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), GO_DOODAD_UL_SIGILDOOR_01, GO_DOODAD_UL_SIGILDOOR_02, GO_FLAG_IN_USE, GO_STATE_ACTIVE, GameObjectTemplate::goober, Player::HasItemCount(), GameObjectTemplate::lockId, MAX_LOCK_CASE, GameObjectAI::me, NPC_BRANN_BRONZBEARD_ALG, GameObject::SetGameObjectFlag(), sLockStore, WorldObject::SummonCreature(), and Map::ToInstanceMap().
UpdateAI()
void go_celestial_planetarium_access::go_celestial_planetarium_accessAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from GameObjectAI.
        {
            if (events.Empty())
                return;
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_DESPAWN_CONSOLE:
                    me->Delete();
                    break;
            }
        }
References GameObject::Delete(), EVENT_DESPAWN_CONSOLE, and GameObjectAI::me.
Member Data Documentation
_locked
bool go_celestial_planetarium_access::go_celestial_planetarium_accessAI::_locked
Referenced by go_celestial_planetarium_accessAI(), and GossipHello().
events
EventMap go_celestial_planetarium_access::go_celestial_planetarium_accessAI::events