AzerothCore: npc_akama_illidan Struct Reference
npc_akama_illidan Struct Reference
Public Member Functions
npc_akama_illidan (Creature *creature)
void Reset () override
void sGossipSelect (Player *player, uint32, uint32) override
void DoAction (int32 param) override
void MovementInform (uint32 type, uint32 id) override
void PathEndReached (uint32 pathId) override
void JustReachedHome () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void KilledUnit (Unit *victim) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
InstanceScript * instance
SummonList summons
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_akama_illidan()
npc_akama_illidan::npc_akama_illidan (Creature * creature) inline
                                          : ScriptedAI(creature), summons(me)
    {
        instance = creature->GetInstanceScript();
    }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DamageTaken()
void npc_akama_illidan::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
    {
        if (damage >= me->GetHealth())
            damage = me->GetHealth() - 1;
    }
References Unit::GetHealth(), and ScriptedAI::me.
DoAction()
void npc_akama_illidan::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
    {
        switch (param)
        {
            case ACTION_ILLIDARI_COUNCIL_DONE:
            {
                me->NearTeleportTo(AkamaIllidariCouncilTeleport);
                me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                me->GetMotionMaster()->MovePath(PATH_AKAMA_ILLIDARI_COUNCIL_1, false);
            }
            break;
            case ACTION_AKAMA_MINIONS:
            {
                EnterEvadeMode(EVADE_REASON_OTHER);
            }
            break;
            case ACTION_AKAMA_ENDING:
            {
                if (me->IsEngaged())
                {
                    summons.DespawnAll();
                    me->SetReactState(REACT_PASSIVE);
                    me->SetControlled(false, UNIT_STATE_ROOT);
                }
                else
                {
                    me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    me->GetMotionMaster()->MovePoint(POINT_ILLIDAN_DEFEATED_1, IllidanDefeated);
                }
            }
            break;
            case ACTION_AKAMA_MAIEV_DESPAWN:
            {
                Talk(SAY_AKAMA_LIGHT);
                me->m_Events.AddEventAtOffset([&] {
                    me->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                }, 3490ms);
                me->m_Events.AddEventAtOffset([&] {
                    me->SetRespawnDelay(WEEK);
                    DoCastSelf(SPELL_AKAMA_DESPAWN);
                }, 8340ms); // 4850ms
                me->m_Events.AddEventAtOffset([&] {
                    me->DespawnOnEvade();
                }, 8740ms);
            }
            break;
        }
    }
References ACTION_AKAMA_ENDING, ACTION_AKAMA_MAIEV_DESPAWN, ACTION_AKAMA_MINIONS, ACTION_ILLIDARI_COUNCIL_DONE, EventProcessor::AddEventAtOffset(), AkamaIllidariCouncilTeleport, SummonList::DespawnAll(), Creature::DespawnOnEvade(), UnitAI::DoCastSelf(), EMOTE_ONESHOT_SALUTE, CreatureAI::EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, Unit::GetMotionMaster(), Unit::HandleEmoteCommand(), IllidanDefeated, Unit::IsEngaged(), WorldObject::m_Events, ScriptedAI::me, MotionMaster::MovePath(), MotionMaster::MovePoint(), Unit::NearTeleportTo(), PATH_AKAMA_ILLIDARI_COUNCIL_1, POINT_ILLIDAN_DEFEATED_1, REACT_PASSIVE, Unit::RemoveNpcFlag(), SAY_AKAMA_LIGHT, Unit::SetControlled(), Creature::SetReactState(), Creature::SetRespawnDelay(), SPELL_AKAMA_DESPAWN, summons, UNIT_NPC_FLAG_GOSSIP, UNIT_STATE_ROOT, and WEEK.
JustEngagedWith()
void npc_akama_illidan::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
    {
        ScheduleTimedEvent(12s, 18s, [&] {
            DoCastVictim(SPELL_CHAIN_LIGHTNING);
        }, 16s, 24s);
        ScheduleTimedEvent(5s, 10s, [&] {
            if (me->HealthBelowPct(20))
                DoCastSelf(SPELL_HEALING_POTION);
        }, 5s, 10s);
    }
References UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), Unit::HealthBelowPct(), ScriptedAI::me, ScriptedAI::ScheduleTimedEvent(), SPELL_CHAIN_LIGHTNING, and SPELL_HEALING_POTION.
JustReachedHome()
void npc_akama_illidan::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
    {
        // Minions Event
        if (instance->GetBossState(DATA_ILLIDAN_STORMRAGE) == IN_PROGRESS && !instance->GetCreature(DATA_ILLIDAN_STORMRAGE)->HasAura(SPELL_DEATH))
        {
            me->SetReactState(REACT_PASSIVE);
            me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
            me->m_Events.AddEventAtOffset([&] {
                Talk(SAY_AKAMA_MINIONS);
            }, 6700ms);
            me->m_Events.AddEventAtOffset([&] {
                me->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
            }, 9530ms); // 2830ms
            me->m_Events.AddEventAtOffset([&] {
                me->GetMotionMaster()->MovePath(PATH_AKAMA_MINIONS, false);
            }, 14400ms); // 4870ms
        }
    }
References EventProcessor::AddEventAtOffset(), DATA_ILLIDAN_STORMRAGE, EMOTE_ONESHOT_EXCLAMATION, EMOTE_STATE_READY1H, InstanceScript::GetBossState(), InstanceScript::GetCreature(), Unit::GetMotionMaster(), Unit::HandleEmoteCommand(), Unit::HasAura(), IN_PROGRESS, instance, WorldObject::m_Events, ScriptedAI::me, MotionMaster::MovePath(), PATH_AKAMA_MINIONS, REACT_PASSIVE, Unit::RemoveNpcFlag(), SAY_AKAMA_MINIONS, Creature::SetReactState(), Unit::SetUInt32Value(), SPELL_DEATH, UNIT_NPC_EMOTESTATE, and UNIT_NPC_FLAG_GOSSIP.
JustSummoned()
void npc_akama_illidan::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
    {
        summons.Summon(summon);
        summon->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
        if (summon->GetEntry() == NPC_ILLIDARI_ELITE)
        {
            me->AddThreat(summon, 1000000.0f);
            summon->AddThreat(me, 1000000.0f);
            summon->AI()->AttackStart(me);
            AttackStart(summon);
        }
    }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), ScriptedAI::AttackStart(), Object::GetEntry(), ScriptedAI::me, NPC_ILLIDARI_ELITE, Unit::ReplaceAllNpcFlags(), SummonList::Summon(), summons, and UNIT_NPC_FLAG_NONE.
KilledUnit()
void npc_akama_illidan::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (victim->GetEntry() == NPC_ILLIDARI_ELITE)
            me->SummonCreature(NPC_ILLIDARI_ELITE, IllidariMinionPos[urand(0, 9)], TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 1200);
    }
References Object::GetEntry(), IllidariMinionPos, ScriptedAI::me, NPC_ILLIDARI_ELITE, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, and urand().
MovementInform()
void npc_akama_illidan::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type == POINT_MOTION_TYPE)
        {
            switch (id)
            {
                case POINT_FACE_ILLIDAN:
                {
                    if (Creature* illidan = instance->GetCreature(DATA_ILLIDAN_STORMRAGE))
                    {
                        me->SetFacingToObject(illidan);
                        illidan->AI()->DoAction(ACTION_START_EVENT);
                        me->SetHomePosition(me->GetPosition());
                    }
                    me->m_Events.AddEventAtOffset([&] {
                        Talk(SAY_AKAMA_FREE);
                    }, 15400ms);
                    me->m_Events.AddEventAtOffset([&] {
                        me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    }, 19440ms); // 4040ms
                    me->m_Events.AddEventAtOffset([&] {
                        me->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                    }, 23080ms); // 3640ms
                    me->m_Events.AddEventAtOffset([&] {
                        Talk(SAY_AKAMA_TIME_HAS_COME);
                    }, 33840ms); // 10760ms
                    me->m_Events.AddEventAtOffset([&] {
                        me->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                        me->SetSheath(SHEATH_STATE_MELEE);
                    }, 35210ms); // 1370ms
                    me->m_Events.AddEventAtOffset([&] {
                        me->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                        me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                    }, 37640ms); // 2430ms
                }
                break;
                case POINT_ILLIDAN_DEFEATED_1:
                {
                    me->SetWalk(true);
                    if (Creature* illidan = instance->GetCreature(DATA_ILLIDAN_STORMRAGE))
                    {
                        float x, y, z;
                        me->GetNearPoint(illidan, x, y, z, 15.f, 0, me->GetAngle(illidan));
                        me->GetMotionMaster()->MovePoint(POINT_ILLIDAN_DEFEATED_2, x, y, z);  // Maiev starts Akama's Ending scene
                    }
                }
                break;
            }
        }
        else if (type == WAYPOINT_MOTION_TYPE)
        {
            if (me->GetCurrentWaypointID() == PATH_AKAMA_MINIONS)
                if (id == 2)
                    DoCastSelf(SPELL_AKAMA_TELEPORT);
        }
    }
References ACTION_START_EVENT, EventProcessor::AddEventAtOffset(), DATA_ILLIDAN_STORMRAGE, UnitAI::DoCastSelf(), EMOTE_ONESHOT_ROAR, EMOTE_ONESHOT_SALUTE, EMOTE_ONESHOT_TALK, EMOTE_STATE_READY1H, Position::GetAngle(), InstanceScript::GetCreature(), Creature::GetCurrentWaypointID(), Unit::GetMotionMaster(), WorldObject::GetNearPoint(), Position::GetPosition(), Unit::HandleEmoteCommand(), instance, WorldObject::m_Events, ScriptedAI::me, MotionMaster::MovePoint(), PATH_AKAMA_MINIONS, POINT_FACE_ILLIDAN, POINT_ILLIDAN_DEFEATED_1, POINT_ILLIDAN_DEFEATED_2, POINT_MOTION_TYPE, SAY_AKAMA_FREE, SAY_AKAMA_TIME_HAS_COME, Unit::SetFacingToObject(), Creature::SetHomePosition(), Unit::SetSheath(), Unit::SetUInt32Value(), Creature::SetWalk(), SHEATH_STATE_MELEE, SPELL_AKAMA_TELEPORT, UNIT_NPC_EMOTESTATE, and WAYPOINT_MOTION_TYPE.
PathEndReached()
void npc_akama_illidan::PathEndReached (uint32 pathId) inline override virtual
Reimplemented from CreatureAI.
    {
        switch (pathId)
        {
            // Talk to Open Door
            case PATH_AKAMA_ILLIDARI_COUNCIL_1:
            {
                me->m_Events.AddEventAtOffset([&] {
                    Talk(SAY_AKAMA_COUNCIL_1);
                }, 200ms);
                me->m_Events.AddEventAtOffset([&] {
                    Talk(SAY_AKAMA_COUNCIL_2);
                    me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                }, 8000ms); // 7800ms
            }
            break;
            // Reached Door
            case PATH_AKAMA_ILLIDARI_COUNCIL_2:
            {
                me->m_Events.AddEventAtOffset([&] {
                    Talk(SAY_AKAMA_DOOR);
                }, 4600ms);
                me->m_Events.AddEventAtOffset([&] {
                    DoCastSelf(SPELL_AKAMA_DOOR_FAIL);
                }, 8120ms); // 3520ms
                me->m_Events.AddEventAtOffset([&] {
                    Talk(SAY_AKAMA_ALONE);
                }, 17860ms); // 9740ms
                me->m_Events.AddEventAtOffset([&] {
                    me->SummonCreature(NPC_SPIRIT_OF_UDALO, SpiritUdaloPos, TEMPSUMMON_TIMED_DESPAWN, 60000);
                    me->SummonCreature(NPC_SPIRIT_OF_OLUM, SpiritOlumPos, TEMPSUMMON_TIMED_DESPAWN, 60000);
                }, 23930ms); // 6070ms
                me->m_Events.AddEventAtOffset([&] {
                    if (Creature* udalo = me->FindNearestCreature(NPC_SPIRIT_OF_UDALO, 15.0f))
                        udalo->AI()->Talk(SAY_UDALO);
                }, 25190ms); // 1260ms
                me->m_Events.AddEventAtOffset([&] {
                    if (Creature* olum = me->FindNearestCreature(NPC_SPIRIT_OF_OLUM, 15.0f))
                        olum->AI()->Talk(SAY_OLUM);
                }, 31370ms); // 6180ms
                me->m_Events.AddEventAtOffset([&] {
                    DoCastSelf(SPELL_AKAMA_DOOR_OPEN);
                    if (Creature* udalo = me->FindNearestCreature(NPC_SPIRIT_OF_UDALO, 15.0f))
                        udalo->AI()->DoCastSelf(SPELL_DEATHSWORN_DOOR_OPEN);
                    if (Creature* olum = me->FindNearestCreature(NPC_SPIRIT_OF_OLUM, 15.0f))
                        olum->AI()->DoCastSelf(SPELL_DEATHSWORN_DOOR_OPEN);
                }, 39710ms); // 8340ms
                me->m_Events.AddEventAtOffset([&] {
                    if (Creature* door = me->FindNearestCreature(NPC_ILLIDAN_DOOR_TRIGGER, 15.0f))
                        door->AI()->DoCastSelf(SPELL_ARCANE_EXPLOSION_VIS);
                }, 50660ms); // 10950ms
                me->m_Events.AddEventAtOffset([&] {
                    me->InterruptNonMeleeSpells(false);
                    if (Creature* udalo = me->FindNearestCreature(NPC_SPIRIT_OF_UDALO, 15.0f))
                        udalo->InterruptNonMeleeSpells(false);
                    if (Creature* olum = me->FindNearestCreature(NPC_SPIRIT_OF_OLUM, 15.0f))
                        olum->InterruptNonMeleeSpells(false);
                    instance->SetBossState(DATA_AKAMA_ILLIDAN, NOT_STARTED);
                    instance->SetBossState(DATA_AKAMA_ILLIDAN, DONE);
                }, 50680ms); // 20ms
                me->m_Events.AddEventAtOffset([&] {
                    Talk(SAY_AKAMA_SALUTE);
                }, 56955ms); // 6275ms
                me->m_Events.AddEventAtOffset([&] {
                    me->GetMotionMaster()->MovePath(PATH_AKAMA_ILLIDARI_COUNCIL_3, false);
                }, 64030ms); // 7075ms
            }
            break;
            // Talk to Initiate Fight
            case PATH_AKAMA_ILLIDARI_COUNCIL_3:
            {
                Talk(SAY_AKAMA_BETRAYER);
                me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            }
            break;
            case PATH_AKAMA_MINIONS:
            {
                me->SetControlled(true, UNIT_STATE_ROOT);
                me->SetReactState(REACT_AGGRESSIVE);
                for (int i = 0; i < 10; ++i)
                    me->SummonCreature(NPC_ILLIDARI_ELITE, IllidariMinionPos[i], TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 1200);
            }
            break;
        }
    }
References EventProcessor::AddEventAtOffset(), DATA_AKAMA_ILLIDAN, UnitAI::DoCastSelf(), DONE, WorldObject::FindNearestCreature(), Unit::GetMotionMaster(), IllidariMinionPos, instance, Unit::InterruptNonMeleeSpells(), WorldObject::m_Events, ScriptedAI::me, MotionMaster::MovePath(), NOT_STARTED, NPC_ILLIDAN_DOOR_TRIGGER, NPC_ILLIDARI_ELITE, NPC_SPIRIT_OF_OLUM, NPC_SPIRIT_OF_UDALO, PATH_AKAMA_ILLIDARI_COUNCIL_1, PATH_AKAMA_ILLIDARI_COUNCIL_2, PATH_AKAMA_ILLIDARI_COUNCIL_3, PATH_AKAMA_MINIONS, REACT_AGGRESSIVE, SAY_AKAMA_ALONE, SAY_AKAMA_BETRAYER, SAY_AKAMA_COUNCIL_1, SAY_AKAMA_COUNCIL_2, SAY_AKAMA_DOOR, SAY_AKAMA_SALUTE, SAY_OLUM, SAY_UDALO, InstanceScript::SetBossState(), Unit::SetControlled(), Unit::SetNpcFlag(), Creature::SetReactState(), SPELL_AKAMA_DOOR_FAIL, SPELL_AKAMA_DOOR_OPEN, SPELL_ARCANE_EXPLOSION_VIS, SPELL_DEATHSWORN_DOOR_OPEN, SpiritOlumPos, SpiritUdaloPos, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, UNIT_NPC_FLAG_GOSSIP, and UNIT_STATE_ROOT.
Reset()
void npc_akama_illidan::Reset () inline override virtual
Reimplemented from ScriptedAI.
    {
        scheduler.CancelAll();
        me->m_Events.KillAllEvents(false);
        me->SetReactState(REACT_AGGRESSIVE);
        if (instance->GetBossState(DATA_ILLIDAN_STORMRAGE) == DONE)
            me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
        else
            me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
        me->setActive(false);
        summons.DespawnAll();
        DoCastSelf(SPELL_REDUCED_THREAT, true);
        me->SetControlled(false, UNIT_STATE_ROOT);
    }
References TaskScheduler::CancelAll(), DATA_ILLIDAN_STORMRAGE, SummonList::DespawnAll(), UnitAI::DoCastSelf(), DONE, InstanceScript::GetBossState(), instance, EventProcessor::KillAllEvents(), WorldObject::m_Events, ScriptedAI::me, REACT_AGGRESSIVE, Unit::RemoveNpcFlag(), CreatureAI::scheduler, WorldObject::setActive(), Unit::SetControlled(), Unit::SetNpcFlag(), Creature::SetReactState(), SPELL_REDUCED_THREAT, summons, UNIT_NPC_FLAG_GOSSIP, and UNIT_STATE_ROOT.
sGossipSelect()
void npc_akama_illidan::sGossipSelect (Player * player, uint32 , uint32) inline override virtual
Reimplemented from UnitAI.
    {
        CloseGossipMenuFor(player);
        me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
        me->setActive(true);
        if (instance->GetBossState(DATA_AKAMA_ILLIDAN) != DONE)
        {
            me->GetMotionMaster()->MovePath(PATH_AKAMA_ILLIDARI_COUNCIL_2, false);
        }
        else
        {
            me->SetSheath(SHEATH_STATE_UNARMED);
            me->GetMotionMaster()->MovePoint(POINT_FACE_ILLIDAN, FaceIllidan);
        }
    }
References CloseGossipMenuFor(), DATA_AKAMA_ILLIDAN, DONE, FaceIllidan, InstanceScript::GetBossState(), Unit::GetMotionMaster(), instance, ScriptedAI::me, MotionMaster::MovePath(), MotionMaster::MovePoint(), PATH_AKAMA_ILLIDARI_COUNCIL_2, POINT_FACE_ILLIDAN, Unit::ReplaceAllNpcFlags(), WorldObject::setActive(), Unit::SetSheath(), SHEATH_STATE_UNARMED, and UNIT_NPC_FLAG_NONE.
SummonedCreatureDies()
void npc_akama_illidan::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
    {
        summons.Despawn(summon);
    }
References SummonList::Despawn(), and summons.
UpdateAI()
void npc_akama_illidan::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
    {
        scheduler.Update(diff);
        if (!UpdateVictim())
            return;
        DoMeleeAttackIfReady();
    }
References UnitAI::DoMeleeAttackIfReady(), CreatureAI::scheduler, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
instance
InstanceScript* npc_akama_illidan::instance private
Referenced by JustReachedHome(), MovementInform(), npc_akama_illidan(), PathEndReached(), Reset(), and sGossipSelect().
summons
SummonList npc_akama_illidan::summons private
Referenced by DoAction(), JustSummoned(), Reset(), and SummonedCreatureDies().