AzeorthCore: go_commandscript Class Reference
go_commandscript Class Reference
Public Member Functions
go_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool DoTeleport (ChatHandler *handler, Position pos, uint32 mapId=MAPID_INVALID)
static bool HandleGoCreatureCIdCommand (ChatHandler *handler, Variant< Hyperlink< creature_entry >, uint32 > cId)
static bool HandleGoCreatureSpawnIdCommand (ChatHandler *handler, Variant< Hyperlink< creature >, ObjectGuid::LowType > spawnId)
static bool HandleGoGameObjectSpawnIdCommand (ChatHandler *handler, uint32 spawnId)
static bool HandleGoGameObjectGOIdCommand (ChatHandler *handler, uint32 goId)
static bool HandleGoGraveyardCommand (ChatHandler *handler, uint32 gyId)
static bool HandleGoGridCommand (ChatHandler *handler, float gridX, float gridY, Optional< uint32 > oMapId)
static bool HandleGoTaxinodeCommand (ChatHandler *handler, Variant< Hyperlink< taxinode >, uint32 > nodeId)
static bool HandleGoTriggerCommand (ChatHandler *handler, Variant< Hyperlink< areatrigger >, uint32 > areaTriggerId)
static bool HandleGoZoneXYCommand (ChatHandler *handler, float x, float y, Optional< Variant< Hyperlink< area >, uint32 > > areaIdArg)
static bool HandleGoXYZCommand (ChatHandler *handler, float x, float y, Optional< float > z, Optional< uint32 > id, Optional< float > o)
static bool HandleGoTicketCommand (ChatHandler *handler, uint32 ticketId)
static bool HandleGoQuestCommand (ChatHandler *handler, std::string_view type, Quest const *quest)
static CreatureData const * GetCreatureData (ChatHandler *handler, uint32 entry)
static GameObjectData const * GetGameObjectData (ChatHandler *handler, uint32 entry)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
go_commandscript()
go_commandscript::go_commandscript () inline
: CommandScript("go_commandscript") { }
Member Function Documentation
DoTeleport()
static bool go_commandscript::DoTeleport (ChatHandler * handler, Position pos, uint32 mapId = MAPID_INVALID) inline static
    {
        Player* player = handler->GetSession()->GetPlayer();
        if (mapId == MAPID_INVALID)
            mapId = player->GetMapId();
        if (!MapMgr::IsValidMapCoord(mapId, pos) || sObjectMgr->IsTransportMap(mapId))
        {
            handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, pos.GetPositionX(), pos.GetPositionY(), mapId);
            handler->SetSentErrorMessage(true);
            return false;
        }
        // stop flight if need
        if (player->IsInFlight())
        {
            player->GetMotionMaster()->MovementExpired();
            player->CleanupAfterTaxiFlight();
        }
        // save only in non-flight case
        else
            player->SaveRecallPosition();
        player->TeleportTo({ mapId, pos });
        return true;
    }
References Player::CleanupAfterTaxiFlight(), WorldLocation::GetMapId(), Unit::GetMotionMaster(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), ChatHandler::GetSession(), Unit::IsInFlight(), MapMgr::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, MAPID_INVALID, MotionMaster::MovementExpired(), ChatHandler::PSendSysMessage(), Player::SaveRecallPosition(), ChatHandler::SetSentErrorMessage(), sObjectMgr, and Player::TeleportTo().
Referenced by HandleGoCreatureCIdCommand(), HandleGoCreatureSpawnIdCommand(), HandleGoGameObjectGOIdCommand(), HandleGoGameObjectSpawnIdCommand(), HandleGoQuestCommand(), HandleGoTaxinodeCommand(), HandleGoTriggerCommand(), and HandleGoXYZCommand().
GetCommands()
ChatCommandTable go_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable goCommandTable =
        {
            { "creature",      HandleGoCreatureSpawnIdCommand,   SEC_MODERATOR,  Console::No },
            { "creature id",   HandleGoCreatureCIdCommand,       SEC_MODERATOR,  Console::No },
            { "gameobject",    HandleGoGameObjectSpawnIdCommand, SEC_MODERATOR,  Console::No },
            { "gameobject id", HandleGoGameObjectGOIdCommand,    SEC_MODERATOR,  Console::No },
            { "graveyard",     HandleGoGraveyardCommand,         SEC_MODERATOR,  Console::No },
            { "grid",          HandleGoGridCommand,              SEC_MODERATOR,  Console::No },
            { "taxinode",      HandleGoTaxinodeCommand,          SEC_MODERATOR,  Console::No },
            { "trigger",       HandleGoTriggerCommand,           SEC_MODERATOR,  Console::No },
            { "zonexy",        HandleGoZoneXYCommand,            SEC_MODERATOR,  Console::No },
            { "xyz",           HandleGoXYZCommand,               SEC_MODERATOR,  Console::No },
            { "ticket",        HandleGoTicketCommand,            SEC_GAMEMASTER, Console::No },
            { "quest",         HandleGoQuestCommand,             SEC_MODERATOR,  Console::No },
        };
        static ChatCommandTable commandTable =
        {
            { "go", goCommandTable }
        };
        return commandTable;
    }
References HandleGoCreatureCIdCommand(), HandleGoCreatureSpawnIdCommand(), HandleGoGameObjectGOIdCommand(), HandleGoGameObjectSpawnIdCommand(), HandleGoGraveyardCommand(), HandleGoGridCommand(), HandleGoQuestCommand(), HandleGoTaxinodeCommand(), HandleGoTicketCommand(), HandleGoTriggerCommand(), HandleGoXYZCommand(), HandleGoZoneXYCommand(), SEC_GAMEMASTER, and SEC_MODERATOR.
GetCreatureData()
static CreatureData const * go_commandscript::GetCreatureData (ChatHandler * handler, uint32 entry) inline static
    {
        CreatureData const* spawnpoint = nullptr;
        for (auto const& pair : sObjectMgr->GetAllCreatureData())
        {
            if (pair.second.id1 != entry)
            {
                continue;
            }
            if (!spawnpoint)
            {
                spawnpoint = &pair.second;
            }
            else
            {
                handler->SendSysMessage(LANG_COMMAND_GOCREATMULTIPLE);
                break;
            }
        }
        return spawnpoint;
    }
References LANG_COMMAND_GOCREATMULTIPLE, ChatHandler::SendSysMessage(), and sObjectMgr.
Referenced by HandleGoCreatureCIdCommand(), and HandleGoQuestCommand().
GetGameObjectData()
static GameObjectData const * go_commandscript::GetGameObjectData (ChatHandler * handler, uint32 entry) inline static
    {
        GameObjectData const* spawnpoint = nullptr;
        for (auto const& pair : sObjectMgr->GetAllGOData())
        {
            if (pair.second.id != entry)
            {
                continue;
            }
            if (!spawnpoint)
            {
                spawnpoint = &pair.second;
            }
            else
            {
                handler->SendSysMessage(LANG_COMMAND_GOCREATMULTIPLE);
                break;
            }
        }
        return spawnpoint;
    }
References LANG_COMMAND_GOCREATMULTIPLE, ChatHandler::SendSysMessage(), and sObjectMgr.
Referenced by HandleGoGameObjectGOIdCommand(), and HandleGoQuestCommand().
HandleGoCreatureCIdCommand()
static bool go_commandscript::HandleGoCreatureCIdCommand (ChatHandler * handler, Variant< Hyperlink< creature_entry >, uint32 > cId) inline static
    {
        CreatureData const* spawnpoint = GetCreatureData(handler, *cId);
        if (!spawnpoint)
        {
            handler->SendSysMessage(LANG_COMMAND_GOCREATNOTFOUND);
            handler->SetSentErrorMessage(true);
            return false;
        }
        return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
    }
References DoTeleport(), GetCreatureData(), LANG_COMMAND_GOCREATNOTFOUND, CreatureData::mapid, CreatureData::posX, CreatureData::posY, CreatureData::posZ, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().
HandleGoCreatureSpawnIdCommand()
static bool go_commandscript::HandleGoCreatureSpawnIdCommand (ChatHandler * handler, Variant< Hyperlink< creature >, ObjectGuid::LowType > spawnId) inline static
    {
        CreatureData const* spawnpoint = sObjectMgr->GetCreatureData(spawnId);
        if (!spawnpoint)
        {
            handler->SendSysMessage(LANG_COMMAND_GOCREATNOTFOUND);
            handler->SetSentErrorMessage(true);
            return false;
        }
        return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
    }
References DoTeleport(), LANG_COMMAND_GOCREATNOTFOUND, CreatureData::mapid, CreatureData::posX, CreatureData::posY, CreatureData::posZ, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleGoGameObjectGOIdCommand()
static bool go_commandscript::HandleGoGameObjectGOIdCommand (ChatHandler * handler, uint32 goId) inline static
    {
        GameObjectData const* spawnpoint = GetGameObjectData(handler, goId);
        if (!spawnpoint)
        {
            handler->SendSysMessage(LANG_COMMAND_GOOBJNOTFOUND);
            handler->SetSentErrorMessage(true);
            return false;
        }
        return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
    }
References DoTeleport(), GetGameObjectData(), LANG_COMMAND_GOOBJNOTFOUND, GameObjectData::mapid, GameObjectData::posX, GameObjectData::posY, GameObjectData::posZ, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().
HandleGoGameObjectSpawnIdCommand()
static bool go_commandscript::HandleGoGameObjectSpawnIdCommand (ChatHandler * handler, uint32 spawnId) inline static
    {
        GameObjectData const* spawnpoint = sObjectMgr->GetGOData(spawnId);
        if (!spawnpoint)
        {
            handler->SendSysMessage(LANG_COMMAND_GOOBJNOTFOUND);
            handler->SetSentErrorMessage(true);
            return false;
        }
        return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
    }
References DoTeleport(), LANG_COMMAND_GOOBJNOTFOUND, GameObjectData::mapid, GameObjectData::posX, GameObjectData::posY, GameObjectData::posZ, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleGoGraveyardCommand()
static bool go_commandscript::HandleGoGraveyardCommand (ChatHandler * handler, uint32 gyId) inline static
    {
        GraveyardStruct const* gy = sGraveyard->GetGraveyard(gyId);
        if (!gy)
        {
            handler->PSendSysMessage(LANG_COMMAND_GRAVEYARDNOEXIST, gyId);
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (!MapMgr::IsValidMapCoord(gy->Map, gy->x, gy->y, gy->z))
        {
            handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, gy->x, gy->y, gy->Map);
            handler->SetSentErrorMessage(true);
            return false;
        }
        Player* player = handler->GetSession()->GetPlayer();
        // stop flight if need
        if (player->IsInFlight())
        {
            player->GetMotionMaster()->MovementExpired();
            player->CleanupAfterTaxiFlight();
        }
        // save only in non-flight case
        else
            player->SaveRecallPosition();
        player->TeleportTo(gy->Map, gy->x, gy->y, gy->z, player->GetOrientation());
        return true;
    }
References Player::CleanupAfterTaxiFlight(), Unit::GetMotionMaster(), Position::GetOrientation(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Unit::IsInFlight(), MapMgr::IsValidMapCoord(), LANG_COMMAND_GRAVEYARDNOEXIST, LANG_INVALID_TARGET_COORD, GraveyardStruct::Map, MotionMaster::MovementExpired(), ChatHandler::PSendSysMessage(), Player::SaveRecallPosition(), ChatHandler::SetSentErrorMessage(), sGraveyard, Player::TeleportTo(), GraveyardStruct::x, GraveyardStruct::y, and GraveyardStruct::z.
Referenced by GetCommands().
HandleGoGridCommand()
static bool go_commandscript::HandleGoGridCommand (ChatHandler * handler, float gridX, float gridY, Optional< uint32 > oMapId) inline static
    {
        Player* player = handler->GetSession()->GetPlayer();
        uint32 mapId = oMapId.value_or(player->GetMapId());
        // center of grid
        float x = (gridX - CENTER_GRID_ID + 0.5f) * SIZE_OF_GRIDS;
        float y = (gridY - CENTER_GRID_ID + 0.5f) * SIZE_OF_GRIDS;
        if (!MapMgr::IsValidMapCoord(mapId, x, y))
        {
            handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, x, y, mapId);
            handler->SetSentErrorMessage(true);
            return false;
        }
        // stop flight if need
        if (player->IsInFlight())
        {
            player->GetMotionMaster()->MovementExpired();
            player->CleanupAfterTaxiFlight();
        }
        // save only in non-flight case
        else
            player->SaveRecallPosition();
        Map const* map = sMapMgr->CreateBaseMap(mapId);
        float z = std::max(map->GetHeight(x, y, MAX_HEIGHT), map->GetWaterLevel(x, y));
        player->TeleportTo(mapId, x, y, z, player->GetOrientation());
        return true;
    }
References CENTER_GRID_ID, Player::CleanupAfterTaxiFlight(), Map::GetHeight(), WorldLocation::GetMapId(), Unit::GetMotionMaster(), Position::GetOrientation(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Map::GetWaterLevel(), Unit::IsInFlight(), MapMgr::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, MAX_HEIGHT, MotionMaster::MovementExpired(), ChatHandler::PSendSysMessage(), Player::SaveRecallPosition(), ChatHandler::SetSentErrorMessage(), SIZE_OF_GRIDS, sMapMgr, and Player::TeleportTo().
Referenced by GetCommands().
HandleGoQuestCommand()
static bool go_commandscript::HandleGoQuestCommand (ChatHandler * handler, std::string_view type, Quest const * quest) inline static
    {
        uint32 entry = quest->GetQuestId();
        if (type == "starter")
        {
            QuestRelations* qr = sObjectMgr->GetCreatureQuestRelationMap();
            for (auto itr = qr->begin(); itr != qr->end(); ++itr)
            {
                if (itr->second == entry)
                {
                    CreatureData const* spawnpoint = GetCreatureData(handler, itr->first);
                    if (!spawnpoint)
                    {
                        handler->SendSysMessage(LANG_COMMAND_GOCREATNOTFOUND);
                        handler->SetSentErrorMessage(true);
                        return false;
                    }
                    // We've found a creature, teleport to it.
                    return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
                }
            }
            qr = sObjectMgr->GetGOQuestRelationMap();
            for (auto itr = qr->begin(); itr != qr->end(); ++itr)
            {
                if (itr->second == entry)
                {
                    GameObjectData const* spawnpoint = GetGameObjectData(handler, itr->first);
                    if (!spawnpoint)
                    {
                        handler->SendSysMessage(LANG_COMMAND_GOOBJNOTFOUND);
                        handler->SetSentErrorMessage(true);
                        return false;
                    }
                    return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
                }
            }
        }
        else if (type == "ender")
        {
            QuestRelations* qr = sObjectMgr->GetCreatureQuestInvolvedRelationMap();
            for (auto itr = qr->begin(); itr != qr->end(); ++itr)
            {
                if (itr->second == entry)
                {
                    CreatureData const* spawnpoint = GetCreatureData(handler, itr->first);
                    if (!spawnpoint)
                    {
                        handler->SendSysMessage(LANG_COMMAND_GOCREATNOTFOUND);
                        handler->SetSentErrorMessage(true);
                        return false;
                    }
                    // We've found a creature, teleport to it.
                    return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
                }
            }
            qr = sObjectMgr->GetGOQuestInvolvedRelationMap();
            for (auto itr = qr->begin(); itr != qr->end(); ++itr)
            {
                if (itr->second == entry)
                {
                    GameObjectData const* spawnpoint = GetGameObjectData(handler, itr->first);
                    if (!spawnpoint)
                    {
                        handler->SendSysMessage(LANG_COMMAND_GOOBJNOTFOUND);
                        handler->SetSentErrorMessage(true);
                        return false;
                    }
                    return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
                }
            }
        }
        else
        {
            handler->SendSysMessage(LANG_CMD_GOQUEST_INVALID_SYNTAX);
            handler->SetSentErrorMessage(true);
            return false;
        }
        return false;
    }
References DoTeleport(), GetCreatureData(), GetGameObjectData(), Quest::GetQuestId(), LANG_CMD_GOQUEST_INVALID_SYNTAX, LANG_COMMAND_GOCREATNOTFOUND, LANG_COMMAND_GOOBJNOTFOUND, CreatureData::mapid, GameObjectData::mapid, CreatureData::posX, GameObjectData::posX, CreatureData::posY, GameObjectData::posY, CreatureData::posZ, GameObjectData::posZ, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
Referenced by GetCommands().
HandleGoTaxinodeCommand()
static bool go_commandscript::HandleGoTaxinodeCommand (ChatHandler * handler, Variant< Hyperlink< taxinode >, uint32 > nodeId) inline static
    {
        TaxiNodesEntry const* node = sTaxiNodesStore.LookupEntry(nodeId);
        if (!node)
        {
            handler->PSendSysMessage(LANG_COMMAND_GOTAXINODENOTFOUND, uint32(nodeId));
            handler->SetSentErrorMessage(true);
            return false;
        }
        return DoTeleport(handler, { node->x, node->y, node->z }, node->map_id);
    }
References DoTeleport(), LANG_COMMAND_GOTAXINODENOTFOUND, TaxiNodesEntry::map_id, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), sTaxiNodesStore, TaxiNodesEntry::x, TaxiNodesEntry::y, and TaxiNodesEntry::z.
Referenced by GetCommands().
HandleGoTicketCommand()
static bool go_commandscript::HandleGoTicketCommand (ChatHandler * handler, uint32 ticketId) inline static
    {
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket)
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        Player* player = handler->GetSession()->GetPlayer();
        // stop flight if need
        if (player->IsInFlight())
        {
            player->GetMotionMaster()->MovementExpired();
            player->CleanupAfterTaxiFlight();
        }
        // save only in non-flight case
        else
            player->SaveRecallPosition();
        ticket->TeleportTo(player);
        return true;
    }
References Player::CleanupAfterTaxiFlight(), Unit::GetMotionMaster(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Unit::IsInFlight(), LANG_COMMAND_TICKETNOTEXIST, MotionMaster::MovementExpired(), Player::SaveRecallPosition(), ChatHandler::SendSysMessage(), sTicketMgr, and GmTicket::TeleportTo().
Referenced by GetCommands().
HandleGoTriggerCommand()
static bool go_commandscript::HandleGoTriggerCommand (ChatHandler * handler, Variant< Hyperlink< areatrigger >, uint32 > areaTriggerId) inline static
    {
        AreaTrigger const* at = sObjectMgr->GetAreaTrigger(areaTriggerId);
        if (!at)
        {
            handler->PSendSysMessage(LANG_COMMAND_GOAREATRNOTFOUND, uint32(areaTriggerId));
            handler->SetSentErrorMessage(true);
            return false;
        }
        return DoTeleport(handler, { at->x, at->y, at->z }, at->map);
    }
References DoTeleport(), LANG_COMMAND_GOAREATRNOTFOUND, AreaTrigger::map, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), sObjectMgr, AreaTrigger::x, AreaTrigger::y, and AreaTrigger::z.
Referenced by GetCommands().
HandleGoXYZCommand()
static bool go_commandscript::HandleGoXYZCommand (ChatHandler * handler, float x, float y, Optional< float > z, Optional< uint32 > id, Optional< float > o) inline static
    {
        Player* player = handler->GetSession()->GetPlayer();
        uint32 mapId = id.value_or(player->GetMapId());
        if (z)
        {
            if (!MapMgr::IsValidMapCoord(mapId, x, y, *z))
            {
                handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, x, y, mapId);
                handler->SetSentErrorMessage(true);
                return false;
            }
        }
        else
        {
            if (!MapMgr::IsValidMapCoord(mapId, x, y))
            {
                handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, x, y, mapId);
                handler->SetSentErrorMessage(true);
                return false;
            }
            Map const* map = sMapMgr->CreateBaseMap(mapId);
            z = std::max(map->GetHeight(x, y, MAX_HEIGHT), map->GetWaterLevel(x, y));
        }
        return DoTeleport(handler, { x, y, *z, o.value_or(0.0f) }, mapId);
    }
References DoTeleport(), Map::GetHeight(), WorldLocation::GetMapId(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Map::GetWaterLevel(), MapMgr::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, MAX_HEIGHT, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), and sMapMgr.
Referenced by GetCommands().
HandleGoZoneXYCommand()
static bool go_commandscript::HandleGoZoneXYCommand (ChatHandler * handler, float x, float y, Optional< Variant< Hyperlink< area >, uint32 > > areaIdArg) inline static
    {
        Player* player = handler->GetSession()->GetPlayer();
        uint32 areaId = areaIdArg ? *areaIdArg : player->GetZoneId();
        AreaTableEntry const* areaEntry = sAreaTableStore.LookupEntry(areaId);
        if (x < 0 || x > 100 || y < 0 || y > 100 || !areaEntry)
        {
            handler->PSendSysMessage(LANG_INVALID_ZONE_COORD, x, y, areaId);
            handler->SetSentErrorMessage(true);
            return false;
        }
        // update to parent zone if exist (client map show only zones without parents)
        AreaTableEntry const* zoneEntry = areaEntry->zone ? sAreaTableStore.LookupEntry(areaEntry->zone) : areaEntry;
                ASSERT(zoneEntry);
        Map const* map = sMapMgr->CreateBaseMap(zoneEntry->mapid);
        if (map->Instanceable())
        {
            handler->PSendSysMessage(LANG_INVALID_ZONE_MAP, areaEntry->ID, areaEntry->area_name[handler->GetSessionDbcLocale()], map->GetId(), map->GetMapName());
            handler->SetSentErrorMessage(true);
            return false;
        }
        Zone2MapCoordinates(x, y, zoneEntry->ID);
        if (!MapMgr::IsValidMapCoord(zoneEntry->mapid, x, y))
        {
            handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, x, y, zoneEntry->mapid);
            handler->SetSentErrorMessage(true);
            return false;
        }
        // stop flight if need
        if (player->IsInFlight())
        {
            player->GetMotionMaster()->MovementExpired();
            player->CleanupAfterTaxiFlight();
        }
        // save only in non-flight case
        else
            player->SaveRecallPosition();
        float z = std::max(map->GetHeight(x, y, MAX_HEIGHT), map->GetWaterLevel(x, y));
        player->TeleportTo(zoneEntry->mapid, x, y, z, player->GetOrientation());
        return true;
    }
References AreaTableEntry::area_name, ASSERT, Player::CleanupAfterTaxiFlight(), Map::GetHeight(), Map::GetId(), Map::GetMapName(), Unit::GetMotionMaster(), Position::GetOrientation(), WorldSession::GetPlayer(), ChatHandler::GetSession(), ChatHandler::GetSessionDbcLocale(), Map::GetWaterLevel(), WorldObject::GetZoneId(), AreaTableEntry::ID, Map::Instanceable(), Unit::IsInFlight(), MapMgr::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, LANG_INVALID_ZONE_COORD, LANG_INVALID_ZONE_MAP, AreaTableEntry::mapid, MAX_HEIGHT, MotionMaster::MovementExpired(), ChatHandler::PSendSysMessage(), sAreaTableStore, Player::SaveRecallPosition(), ChatHandler::SetSentErrorMessage(), sMapMgr, Player::TeleportTo(), AreaTableEntry::zone, and Zone2MapCoordinates().
Referenced by GetCommands().