AzeorthCore: boss_varos::boss_varosAI Struct Reference
boss_varos::boss_varosAI Struct Reference
Public Member Functions
boss_varosAI (Creature *c)
void Reset () override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void EnterEvadeMode (EvadeReason why) override
void MoveInLineOfSight (Unit *) override
void JustSummoned (Creature *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
float ZapAngle
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_varosAI()
boss_varos::boss_varosAI::boss_varosAI (Creature * c) inline
                                  : ScriptedAI(c)
        {
            pInstance = c->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
EnterCombat()
void boss_varos::boss_varosAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_AGGRO);
            if (pInstance)
                pInstance->SetData(DATA_VAROS, IN_PROGRESS);
            me->SetInCombatWithZone();
            events.RescheduleEvent(EVENT_AMPLIFY_MAGIC, urand(5000, 10000));
            events.RescheduleEvent(EVENT_CALL_AZURE_RING_CAPTAIN_1, 5000);
            events.RescheduleEvent(EVENT_ENERGIZE_CORES_THIN, 0);
        }
References DATA_VAROS, EVENT_AMPLIFY_MAGIC, EVENT_CALL_AZURE_RING_CAPTAIN_1, EVENT_ENERGIZE_CORES_THIN, IN_PROGRESS, ScriptedAI::me, pInstance, SAY_AGGRO, ZoneScript::SetData(), Creature::SetInCombatWithZone(), and urand().
EnterEvadeMode()
void boss_varos::boss_varosAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            me->SetControlled(false, UNIT_STATE_ROOT);
            me->DisableRotate(false);
            ScriptedAI::EnterEvadeMode(why);
        }
References Unit::DisableRotate(), CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
JustDied()
void boss_varos::boss_varosAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_DEATH);
            if (pInstance)
            {
                pInstance->SetData(DATA_VAROS, DONE);
                pInstance->instance->SummonCreature(NPC_IMAGE_OF_BELGARISTRASZ, *me);
            }
        }
References DATA_VAROS, DONE, InstanceScript::instance, ScriptedAI::me, NPC_IMAGE_OF_BELGARISTRASZ, pInstance, SAY_DEATH, ZoneScript::SetData(), and Map::SummonCreature().
JustSummoned()
void boss_varos::boss_varosAI::JustSummoned (Creature *) inline override virtual
Reimplemented from ScriptedAI.
{}
MoveInLineOfSight()
void boss_varos::boss_varosAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{}
Reset()
void boss_varos::boss_varosAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            if (pInstance)
            {
                pInstance->SetData(DATA_VAROS, NOT_STARTED);
                if( pInstance->GetData(DATA_CC_COUNT) < 10 )
                {
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->CastSpell(me, 50053, true);
                }
                else
                {
                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->InterruptNonMeleeSpells(false);
                    me->RemoveAura(50053);
                }
            }
            events.Reset();
            ZapAngle = 6.20f;
            me->ApplySpellImmune(0, IMMUNITY_ID, 49838, true);
            me->SetControlled(false, UNIT_STATE_ROOT);
            me->DisableRotate(false);
        }
References Unit::ApplySpellImmune(), Unit::CastSpell(), DATA_CC_COUNT, DATA_VAROS, Unit::DisableRotate(), ZoneScript::GetData(), IMMUNITY_ID, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, NOT_STARTED, pInstance, Unit::RemoveAura(), Unit::RemoveUnitFlag(), Unit::SetControlled(), ZoneScript::SetData(), Unit::SetUnitFlag(), UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_ROOT, and ZapAngle.
UpdateAI()
void boss_varos::boss_varosAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if( !UpdateVictim() )
                return;
            events.Update(diff);
            if( me->HasUnitState(UNIT_STATE_CASTING) )
                return;
            DoMeleeAttackIfReady();
            switch( events.ExecuteEvent() )
            {
                case 0:
                    break;
                case EVENT_AMPLIFY_MAGIC:
                    {
                        if( Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 50.0f, true) )
                            me->CastSpell(target, SPELL_AMPLIFY_MAGIC, false);
                        events.RepeatEvent(urand(17500, 22500));
                    }
                    break;
                case EVENT_CALL_AZURE_RING_CAPTAIN_1:
                case EVENT_CALL_AZURE_RING_CAPTAIN_2:
                case EVENT_CALL_AZURE_RING_CAPTAIN_3:
                case EVENT_CALL_AZURE_RING_CAPTAIN_4:
                    {
                        Talk(SAY_AZURE);
                        Talk(SAY_AZURE_EMOTE);
                        switch( events.ExecuteEvent() )
{
                            case EVENT_CALL_AZURE_RING_CAPTAIN_1:
                                me->CastSpell(me, SPELL_CALL_AZURE_RING_CAPTAIN_1, true);
                                events.ScheduleEvent(EVENT_CALL_AZURE_RING_CAPTAIN_2, 16000);
                                break;
                            case EVENT_CALL_AZURE_RING_CAPTAIN_2:
                                me->CastSpell(me, SPELL_CALL_AZURE_RING_CAPTAIN_2, true);
                                events.ScheduleEvent(EVENT_CALL_AZURE_RING_CAPTAIN_3, 16000);
                                break;
                            case EVENT_CALL_AZURE_RING_CAPTAIN_3:
                                me->CastSpell(me, SPELL_CALL_AZURE_RING_CAPTAIN_3, true);
                                events.ScheduleEvent(EVENT_CALL_AZURE_RING_CAPTAIN_4, 16000);
                                break;
                            case EVENT_CALL_AZURE_RING_CAPTAIN_4:
                                me->CastSpell(me, SPELL_CALL_AZURE_RING_CAPTAIN_4, true);
                                events.ScheduleEvent(EVENT_CALL_AZURE_RING_CAPTAIN_1, 16000);
                                break;
                        }
                        if( Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100.0f, true) )
{
                            if( Creature* trigger = me->SummonCreature(NPC_ARCANE_BEAM, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN, 13000) )
{
                                if( Creature* c = me->FindNearestCreature(NPC_AZURE_RING_CAPTAIN, 500.0f, true) )
                                    c->CastSpell(trigger, SPELL_ARCANE_BEAM_VISUAL, true);
                                trigger->GetMotionMaster()->MoveChase(target, 0.1f);
                                trigger->CastSpell(me, SPELL_ARCANE_BEAM_PERIODIC_DAMAGE, true);
                            }
                        }
                    }
                    break;
                case EVENT_ENERGIZE_CORES_THIN:
                    {
                        me->SetControlled(false, UNIT_STATE_ROOT);
                        me->DisableRotate(false);
                        me->SetOrientation(ZapAngle);
                        me->CastSpell(me, SPELL_ENERGIZE_CORES_THIN, true);
                        events.ScheduleEvent(EVENT_ENERGIZE_CORES_DAMAGE, 4500);
                    }
                    break;
                case EVENT_ENERGIZE_CORES_DAMAGE:
                    {
                        me->SetOrientation(ZapAngle);
                        me->DisableRotate(true);
                        me->DisableSpline();
                        me->SetFacingTo(ZapAngle);
                        me->SetControlled(true, UNIT_STATE_ROOT);
                        me->CastSpell((Unit*)nullptr, SPELL_ENERGIZE_CORES, false);
                        ZapAngle += M_PI / 2;
                        if( ZapAngle >= 2 * M_PI )
                            ZapAngle -= 2 * M_PI;
                        events.ScheduleEvent(EVENT_ENERGIZE_CORES_THIN, 2000);
                    }
                    break;
            }
        }
References Unit::CastSpell(), Unit::DisableRotate(), Unit::DisableSpline(), UnitAI::DoMeleeAttackIfReady(), EVENT_AMPLIFY_MAGIC, EVENT_CALL_AZURE_RING_CAPTAIN_1, EVENT_CALL_AZURE_RING_CAPTAIN_2, EVENT_CALL_AZURE_RING_CAPTAIN_3, EVENT_CALL_AZURE_RING_CAPTAIN_4, EVENT_ENERGIZE_CORES_DAMAGE, EVENT_ENERGIZE_CORES_THIN, WorldObject::FindNearestCreature(), Unit::HasUnitState(), ScriptedAI::me, NPC_ARCANE_BEAM, NPC_AZURE_RING_CAPTAIN, SAY_AZURE, SAY_AZURE_EMOTE, UnitAI::SelectTarget(), Unit::SetControlled(), Unit::SetFacingTo(), Position::SetOrientation(), SPELL_AMPLIFY_MAGIC, SPELL_ARCANE_BEAM_PERIODIC_DAMAGE, SPELL_ARCANE_BEAM_VISUAL, SPELL_CALL_AZURE_RING_CAPTAIN_1, SPELL_CALL_AZURE_RING_CAPTAIN_2, SPELL_CALL_AZURE_RING_CAPTAIN_3, SPELL_CALL_AZURE_RING_CAPTAIN_4, SPELL_ENERGIZE_CORES, SPELL_ENERGIZE_CORES_THIN, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, UNIT_STATE_ROOT, CreatureAI::UpdateVictim(), urand(), and ZapAngle.
Member Data Documentation
events
EventMap boss_varos::boss_varosAI::events
pInstance
InstanceScript* boss_varos::boss_varosAI::pInstance
Referenced by boss_varosAI(), EnterCombat(), JustDied(), and Reset().
ZapAngle
float boss_varos::boss_varosAI::ZapAngle
Referenced by Reset(), and UpdateAI().