AzerothCore: azerothcore-wotlk/src/server/scripts/Commands/cs_lfg.cpp File Reference
cs_lfg.cpp File Reference
#include "Chat.h"
#include "CommandScript.h"
#include "Group.h"
#include "LFGMgr.h"
#include "Language.h"
#include "Player.h"
Classes
class lfg_commandscript
Functions
void GetPlayerInfo (ChatHandler *handler, Player *player)
void AddSC_lfg_commandscript ()
Function Documentation
AddSC_lfg_commandscript()
void AddSC_lfg_commandscript ()
{
    new lfg_commandscript();
}
Referenced by AddCommandsScripts().
GetPlayerInfo()
void GetPlayerInfo (ChatHandler * handler, Player * player)
{
    if (!player)
        return;
    ObjectGuid guid = player->GetGUID();
    lfg::LfgDungeonSet dungeons = sLFGMgr->GetSelectedDungeons(guid);
    std::string const& state = lfg::GetStateString(sLFGMgr->GetState(guid));
    handler->PSendSysMessage(LANG_LFG_PLAYER_INFO, player->GetName(),
                             state, uint8(dungeons.size()), lfg::ConcatenateDungeons(dungeons),
                             lfg::GetRolesString(sLFGMgr->GetRoles(guid)), sLFGMgr->GetComment(guid));
}
References lfg::ConcatenateDungeons(), Object::GetGUID(), WorldObject::GetName(), lfg::GetRolesString(), lfg::GetStateString(), LANG_LFG_PLAYER_INFO, ChatHandler::PSendSysMessage(), and sLFGMgr.
Referenced by lfg_commandscript::HandleLfgGroupInfoCommand(), and lfg_commandscript::HandleLfgPlayerInfoCommand().