AzerothCore: achievement_resilient_victory Class Reference
achievement_resilient_victory Class Reference
Public Member Functions
achievement_resilient_victory ()
bool OnCheck (Player *source, Unit *, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
virtual bool OnCheck (Player *, Unit *, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_resilient_victory()
achievement_resilient_victory::achievement_resilient_victory () inline
: AchievementCriteriaScript("achievement_resilient_victory") { }
Member Function Documentation
OnCheck()
bool achievement_resilient_victory::OnCheck (Player * source, Unit * , uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
    {
        Battleground* bg = source->GetBattleground();
        return bg && bg->GetBgTypeID(true) == BATTLEGROUND_AB && bg->ToBattlegroundAB()->IsTeamScores500Disadvantage(source->GetTeamId());
    }
References BATTLEGROUND_AB, Player::GetBattleground(), Battleground::GetBgTypeID(), Player::GetTeamId(), BattlegroundAB::IsTeamScores500Disadvantage(), and Battleground::ToBattlegroundAB().