AzerothCore: npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI Struct Reference
npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI Struct Reference
Public Member Functions
npc_highlord_tirion_fordringAI (Creature *creature)
void Reset () override
void SetData (uint32 type, uint32 data) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
InstanceScript *const _instance
ObjectGuid _theLichKing
ObjectGuid _bolvarFordragon
ObjectGuid _factionNPC
uint16 _damnedKills
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_highlord_tirion_fordringAI()
npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::npc_highlord_tirion_fordringAI (Creature * creature) inline
                                                           : ScriptedAI(creature), _instance(creature->GetInstanceScript())
        {
        }
Member Function Documentation
Reset()
void npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _events.Reset();
            _theLichKing.Clear();
            _bolvarFordragon.Clear();
            _factionNPC.Clear();
            _damnedKills = 0;
        }
References _bolvarFordragon, _damnedKills, _events, _factionNPC, _theLichKing, ObjectGuid::Clear(), and EventMap::Reset().
SetData()
void npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
        {
            if (type == DATA_DAMNED_KILLS && data == 1)
            {
                if (++_damnedKills == 2)
                {
                    if (Creature* theLichKing = me->FindNearestCreature(NPC_THE_LICH_KING_LH, 150.0f))
                    {
                        if (Creature* bolvarFordragon = me->FindNearestCreature(NPC_HIGHLORD_BOLVAR_FORDRAGON_LH, 150.0f))
{
                            if (Creature* factionNPC = me->FindNearestCreature(_instance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE ? NPC_HIGH_OVERLORD_SAURFANG_DUMMY : NPC_MURADIN_BRONZEBEARD_DUMMY, 50.0f))
{
                                me->setActive(true);
                                _theLichKing = theLichKing->GetGUID();
                                theLichKing->setActive(true);
                                _bolvarFordragon = bolvarFordragon->GetGUID();
                                bolvarFordragon->setActive(true);
                                _factionNPC = factionNPC->GetGUID();
                                factionNPC->setActive(true);
                            }
                        }
                    }
                    if (!_bolvarFordragon || !_theLichKing || !_factionNPC)
                        return;
                    Talk(SAY_TIRION_INTRO_1);
                    _events.ScheduleEvent(EVENT_TIRION_INTRO_2, 4s);
                    _events.ScheduleEvent(EVENT_TIRION_INTRO_3, 14s);
                    _events.ScheduleEvent(EVENT_TIRION_INTRO_4, 18s);
                    _events.ScheduleEvent(EVENT_TIRION_INTRO_5, 31s);
                    _events.ScheduleEvent(EVENT_LK_INTRO_1, 35s);
                    _events.ScheduleEvent(EVENT_TIRION_INTRO_6, 49s);
                    _events.ScheduleEvent(EVENT_LK_INTRO_2, 58s);
                    _events.ScheduleEvent(EVENT_LK_INTRO_3, 74s);
                    _events.ScheduleEvent(EVENT_LK_INTRO_4, 86s); // sound last 21 seconds (five more)
                    _events.ScheduleEvent(EVENT_BOLVAR_INTRO_1, 107s);
                    _events.ScheduleEvent(EVENT_LK_INTRO_5, 113s);
                    if (_instance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE)
                    {
                        _events.ScheduleEvent(EVENT_SAURFANG_INTRO_1, 125s);
                        _events.ScheduleEvent(EVENT_TIRION_INTRO_H_7, 134s);
                        _events.ScheduleEvent(EVENT_SAURFANG_INTRO_2, 144s);
                        _events.ScheduleEvent(EVENT_SAURFANG_INTRO_3, 155s);
                        _events.ScheduleEvent(EVENT_SAURFANG_INTRO_4, 167s);
                        _events.ScheduleEvent(EVENT_SAURFANG_RUN, 175s);
                    }
                    else
                    {
                        _events.ScheduleEvent(EVENT_MURADIN_INTRO_1, 125s);
                        _events.ScheduleEvent(EVENT_MURADIN_INTRO_2, 129s);
                        _events.ScheduleEvent(EVENT_MURADIN_INTRO_3, 132s);
                        _events.ScheduleEvent(EVENT_TIRION_INTRO_A_7, 141s);
                        _events.ScheduleEvent(EVENT_MURADIN_INTRO_4, 149s);
                        _events.ScheduleEvent(EVENT_MURADIN_INTRO_5, 156s);
                        _events.ScheduleEvent(EVENT_MURADIN_RUN, 162s);
                    }
                }
            }
        }
References _bolvarFordragon, _damnedKills, _events, _factionNPC, _instance, _theLichKing, DATA_DAMNED_KILLS, DATA_TEAMID_IN_INSTANCE, EVENT_BOLVAR_INTRO_1, EVENT_LK_INTRO_1, EVENT_LK_INTRO_2, EVENT_LK_INTRO_3, EVENT_LK_INTRO_4, EVENT_LK_INTRO_5, EVENT_MURADIN_INTRO_1, EVENT_MURADIN_INTRO_2, EVENT_MURADIN_INTRO_3, EVENT_MURADIN_INTRO_4, EVENT_MURADIN_INTRO_5, EVENT_MURADIN_RUN, EVENT_SAURFANG_INTRO_1, EVENT_SAURFANG_INTRO_2, EVENT_SAURFANG_INTRO_3, EVENT_SAURFANG_INTRO_4, EVENT_SAURFANG_RUN, EVENT_TIRION_INTRO_2, EVENT_TIRION_INTRO_3, EVENT_TIRION_INTRO_4, EVENT_TIRION_INTRO_5, EVENT_TIRION_INTRO_6, EVENT_TIRION_INTRO_A_7, EVENT_TIRION_INTRO_H_7, WorldObject::FindNearestCreature(), ZoneScript::GetData(), ScriptedAI::me, NPC_HIGH_OVERLORD_SAURFANG_DUMMY, NPC_HIGHLORD_BOLVAR_FORDRAGON_LH, NPC_MURADIN_BRONZEBEARD_DUMMY, NPC_THE_LICH_KING_LH, SAY_TIRION_INTRO_1, EventMap::ScheduleEvent(), WorldObject::setActive(), and TEAM_HORDE.
UpdateAI()
void npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (_damnedKills != 2)
                return;
            _events.Update(diff);
            while (uint32 eventId = _events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_TIRION_INTRO_2:
                        me->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
                        break;
                    case EVENT_TIRION_INTRO_3:
                        Talk(SAY_TIRION_INTRO_2);
                        break;
                    case EVENT_TIRION_INTRO_4:
                        me->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
                        break;
                    case EVENT_TIRION_INTRO_5:
                        Talk(SAY_TIRION_INTRO_3);
                        break;
                    case EVENT_LK_INTRO_1:
                        me->HandleEmoteCommand(EMOTE_ONESHOT_POINT_NO_SHEATHE);
                        if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _theLichKing))
                            theLichKing->AI()->Talk(SAY_LK_INTRO_1);
                        break;
                    case EVENT_TIRION_INTRO_6:
                        Talk(SAY_TIRION_INTRO_4);
                        break;
                    case EVENT_LK_INTRO_2:
                        if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _theLichKing))
                            theLichKing->AI()->Talk(SAY_LK_INTRO_2);
                        break;
                    case EVENT_LK_INTRO_3:
                        if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _theLichKing))
                            theLichKing->AI()->Talk(SAY_LK_INTRO_3);
                        break;
                    case EVENT_LK_INTRO_4:
                        if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _theLichKing))
                            theLichKing->AI()->Talk(SAY_LK_INTRO_4);
                        break;
                    case EVENT_BOLVAR_INTRO_1:
                        if (Creature* bolvarFordragon = ObjectAccessor::GetCreature(*me, _bolvarFordragon))
{
                            bolvarFordragon->AI()->Talk(SAY_BOLVAR_INTRO_1);
                            bolvarFordragon->setActive(false);
                        }
                        break;
                    case EVENT_LK_INTRO_5:
                        if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _theLichKing))
{
                            theLichKing->AI()->Talk(SAY_LK_INTRO_5);
                            theLichKing->setActive(false);
                        }
                        break;
                    case EVENT_SAURFANG_INTRO_1:
                        if (Creature* saurfang = ObjectAccessor::GetCreature(*me, _factionNPC))
                            saurfang->AI()->Talk(SAY_SAURFANG_INTRO_1);
                        break;
                    case EVENT_TIRION_INTRO_H_7:
                        Talk(SAY_TIRION_INTRO_H_5);
                        break;
                    case EVENT_SAURFANG_INTRO_2:
                        if (Creature* saurfang = ObjectAccessor::GetCreature(*me, _factionNPC))
                            saurfang->AI()->Talk(SAY_SAURFANG_INTRO_2);
                        break;
                    case EVENT_SAURFANG_INTRO_3:
                        if (Creature* saurfang = ObjectAccessor::GetCreature(*me, _factionNPC))
                            saurfang->AI()->Talk(SAY_SAURFANG_INTRO_3);
                        break;
                    case EVENT_SAURFANG_INTRO_4:
                        if (Creature* saurfang = ObjectAccessor::GetCreature(*me, _factionNPC))
                            saurfang->AI()->Talk(SAY_SAURFANG_INTRO_4);
                        break;
                    case EVENT_MURADIN_RUN:
                    case EVENT_SAURFANG_RUN:
                        if (Creature* factionNPC = ObjectAccessor::GetCreature(*me, _factionNPC))
{
                            factionNPC->GetMotionMaster()->MovePath(factionNPC->GetSpawnId() * 10, false);
                            factionNPC->DespawnOrUnsummon(46500);
                            std::list<Creature*> followers;
                            factionNPC->GetCreaturesWithEntryInRange(followers, 30, _instance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE ? NPC_KOR_KRON_GENERAL : NPC_ALLIANCE_COMMANDER);
                            for (Creature* follower : followers)
{
                                follower->DespawnOrUnsummon(46500);
                            }
                        }
                        me->setActive(false);
                        _damnedKills = 3;
                        break;
                    case EVENT_MURADIN_INTRO_1:
                        if (Creature* muradin = ObjectAccessor::GetCreature(*me, _factionNPC))
                            muradin->AI()->Talk(SAY_MURADIN_INTRO_1);
                        break;
                    case EVENT_MURADIN_INTRO_2:
                        if (Creature* muradin = ObjectAccessor::GetCreature(*me, _factionNPC))
                            muradin->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                        break;
                    case EVENT_MURADIN_INTRO_3:
                        if (Creature* muradin = ObjectAccessor::GetCreature(*me, _factionNPC))
                            muradin->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
                        break;
                    case EVENT_TIRION_INTRO_A_7:
                        Talk(SAY_TIRION_INTRO_A_5);
                        break;
                    case EVENT_MURADIN_INTRO_4:
                        if (Creature* muradin = ObjectAccessor::GetCreature(*me, _factionNPC))
                            muradin->AI()->Talk(SAY_MURADIN_INTRO_2);
                        break;
                    case EVENT_MURADIN_INTRO_5:
                        if (Creature* muradin = ObjectAccessor::GetCreature(*me, _factionNPC))
                            muradin->AI()->Talk(SAY_MURADIN_INTRO_3);
                        break;
                    default:
                        break;
                }
            }
        }
References _bolvarFordragon, _damnedKills, _events, _factionNPC, _instance, _theLichKing, DATA_TEAMID_IN_INSTANCE, EMOTE_ONESHOT_EXCLAMATION, EMOTE_ONESHOT_POINT_NO_SHEATHE, EMOTE_ONESHOT_TALK, EVENT_BOLVAR_INTRO_1, EVENT_LK_INTRO_1, EVENT_LK_INTRO_2, EVENT_LK_INTRO_3, EVENT_LK_INTRO_4, EVENT_LK_INTRO_5, EVENT_MURADIN_INTRO_1, EVENT_MURADIN_INTRO_2, EVENT_MURADIN_INTRO_3, EVENT_MURADIN_INTRO_4, EVENT_MURADIN_INTRO_5, EVENT_MURADIN_RUN, EVENT_SAURFANG_INTRO_1, EVENT_SAURFANG_INTRO_2, EVENT_SAURFANG_INTRO_3, EVENT_SAURFANG_INTRO_4, EVENT_SAURFANG_RUN, EVENT_TIRION_INTRO_2, EVENT_TIRION_INTRO_3, EVENT_TIRION_INTRO_4, EVENT_TIRION_INTRO_5, EVENT_TIRION_INTRO_6, EVENT_TIRION_INTRO_A_7, EVENT_TIRION_INTRO_H_7, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), ZoneScript::GetData(), Unit::HandleEmoteCommand(), ScriptedAI::me, NPC_ALLIANCE_COMMANDER, NPC_KOR_KRON_GENERAL, SAY_BOLVAR_INTRO_1, SAY_LK_INTRO_1, SAY_LK_INTRO_2, SAY_LK_INTRO_3, SAY_LK_INTRO_4, SAY_LK_INTRO_5, SAY_MURADIN_INTRO_1, SAY_MURADIN_INTRO_2, SAY_MURADIN_INTRO_3, SAY_SAURFANG_INTRO_1, SAY_SAURFANG_INTRO_2, SAY_SAURFANG_INTRO_3, SAY_SAURFANG_INTRO_4, SAY_TIRION_INTRO_2, SAY_TIRION_INTRO_3, SAY_TIRION_INTRO_4, SAY_TIRION_INTRO_A_5, SAY_TIRION_INTRO_H_5, WorldObject::setActive(), TEAM_HORDE, and EventMap::Update().
Member Data Documentation
_bolvarFordragon
ObjectGuid npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::_bolvarFordragon private
Referenced by Reset(), SetData(), and UpdateAI().
_damnedKills
uint16 npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::_damnedKills private
Referenced by Reset(), SetData(), and UpdateAI().
_events
EventMap npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::_events private
Referenced by Reset(), SetData(), and UpdateAI().
_factionNPC
ObjectGuid npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::_factionNPC private
Referenced by Reset(), SetData(), and UpdateAI().
_instance
InstanceScript* const npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::_instance private
Referenced by SetData(), and UpdateAI().
_theLichKing
ObjectGuid npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::_theLichKing private
Referenced by Reset(), SetData(), and UpdateAI().