AzeorthCore: spell_gen_clone_weapon_aura Class Reference
spell_gen_clone_weapon_aura Class Reference
Private Member Functions
PrepareAuraScript (spell_gen_clone_weapon_aura)
bool Validate (SpellInfo const *) override
bool Load () override
void OnApply (AuraEffect const *, AuraEffectHandleModes)
void OnRemove (AuraEffect const *, AuraEffectHandleModes)
void Register () override
Private Attributes
uint32 prevItem
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< CheckProcHandler > DoCheckAfterProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
Load()
bool spell_gen_clone_weapon_aura::Load () inline override private virtual
Reimplemented from _SpellScript.
    {
        prevItem = 0;
        return true;
    }
References prevItem.
OnApply()
void spell_gen_clone_weapon_aura::OnApply (AuraEffect const * , AuraEffectHandleModes) inline private
    {
        Unit* caster = GetCaster();
        Unit* target = GetTarget();
        if (!caster)
            return;
        switch (GetSpellInfo()->Id)
        {
            case SPELL_COPY_WEAPON_AURA:
            case SPELL_COPY_WEAPON_2_AURA:
            case SPELL_COPY_WEAPON_3_AURA:
                {
                    prevItem = target->GetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID);
                    if (Player* player = caster->ToPlayer())
                    {
                        if (Item* mainItem = player->GetItemByPos(INVENTORY_SLOT_BAG_0, EQUIPMENT_SLOT_MAINHAND))
                            target->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID, mainItem->GetEntry());
                    }
                    else
                        target->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID, caster->GetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID));
                    break;
                }
            case SPELL_COPY_OFFHAND_AURA:
            case SPELL_COPY_OFFHAND_2_AURA:
                {
                    prevItem = target->GetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1);
                    if (Player* player = caster->ToPlayer())
                    {
                        if (Item* offItem = player->GetItemByPos(INVENTORY_SLOT_BAG_0, EQUIPMENT_SLOT_OFFHAND))
                            target->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, offItem->GetEntry());
                    }
                    else
                        target->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, caster->GetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1));
                    break;
                }
            case SPELL_COPY_RANGED_AURA:
                {
                    prevItem = target->GetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 2);
                    if (Player* player = caster->ToPlayer())
                    {
                        if (Item* rangedItem = player->GetItemByPos(INVENTORY_SLOT_BAG_0, EQUIPMENT_SLOT_RANGED))
                            target->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 2, rangedItem->GetEntry());
                    }
                    else
                        target->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 2, caster->GetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 2));
                    break;
                }
            default:
                break;
        }
    }
References EQUIPMENT_SLOT_MAINHAND, EQUIPMENT_SLOT_OFFHAND, EQUIPMENT_SLOT_RANGED, AuraScript::GetCaster(), AuraScript::GetSpellInfo(), AuraScript::GetTarget(), Object::GetUInt32Value(), INVENTORY_SLOT_BAG_0, prevItem, Object::SetUInt32Value(), SPELL_COPY_OFFHAND_2_AURA, SPELL_COPY_OFFHAND_AURA, SPELL_COPY_RANGED_AURA, SPELL_COPY_WEAPON_2_AURA, SPELL_COPY_WEAPON_3_AURA, SPELL_COPY_WEAPON_AURA, Object::ToPlayer(), and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by Register().
OnRemove()
void spell_gen_clone_weapon_aura::OnRemove (AuraEffect const * , AuraEffectHandleModes) inline private
    {
        Unit* target = GetTarget();
        switch (GetSpellInfo()->Id)
        {
            case SPELL_COPY_WEAPON_AURA:
            case SPELL_COPY_WEAPON_2_AURA:
            case SPELL_COPY_WEAPON_3_AURA:
                target->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID, prevItem);
                break;
            case SPELL_COPY_OFFHAND_AURA:
            case SPELL_COPY_OFFHAND_2_AURA:
                target->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, prevItem);
                break;
            case SPELL_COPY_RANGED_AURA:
                target->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 2, prevItem);
                break;
            default:
                break;
        }
    }
References AuraScript::GetSpellInfo(), AuraScript::GetTarget(), prevItem, Object::SetUInt32Value(), SPELL_COPY_OFFHAND_2_AURA, SPELL_COPY_OFFHAND_AURA, SPELL_COPY_RANGED_AURA, SPELL_COPY_WEAPON_2_AURA, SPELL_COPY_WEAPON_3_AURA, SPELL_COPY_WEAPON_AURA, and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by Register().
PrepareAuraScript()
spell_gen_clone_weapon_aura::PrepareAuraScript (spell_gen_clone_weapon_aura) private
Register()
void spell_gen_clone_weapon_aura::Register () inline override private virtual
Implements _SpellScript.
    {
        OnEffectApply += AuraEffectApplyFn(spell_gen_clone_weapon_aura::OnApply, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
        OnEffectRemove += AuraEffectRemoveFn(spell_gen_clone_weapon_aura::OnRemove, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
    }
References AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK, AuraEffectApplyFn, AuraEffectRemoveFn, EFFECT_0, OnApply(), AuraScript::OnEffectApply, AuraScript::OnEffectRemove, OnRemove(), and SPELL_AURA_PERIODIC_DUMMY.
Validate()
bool spell_gen_clone_weapon_aura::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo(
            {
                SPELL_COPY_WEAPON_AURA,
                SPELL_COPY_WEAPON_2_AURA,
                SPELL_COPY_WEAPON_3_AURA,
                SPELL_COPY_OFFHAND_AURA,
                SPELL_COPY_OFFHAND_2_AURA,
                SPELL_COPY_RANGED_AURA
            });
    }
References SPELL_COPY_OFFHAND_2_AURA, SPELL_COPY_OFFHAND_AURA, SPELL_COPY_RANGED_AURA, SPELL_COPY_WEAPON_2_AURA, SPELL_COPY_WEAPON_3_AURA, SPELL_COPY_WEAPON_AURA, and _SpellScript::ValidateSpellInfo().
Member Data Documentation
prevItem
uint32 spell_gen_clone_weapon_aura::prevItem private
Referenced by Load(), OnApply(), and OnRemove().