AzerothCore: MovableMapObject Class Reference
MovableMapObject Class Reference
#include "Object.h"
Protected Member Functions
MovableMapObject ()=default
Private Member Functions
Cell const & GetCurrentCell () const
void SetCurrentCell (Cell const &cell)
Private Attributes
Cell _currentCell
MapObjectCellMoveState _moveState {MAP_OBJECT_CELL_MOVE_NONE}
Friends
class Map
class ObjectGridLoader
template<class T >
class RandomMovementGenerator
Detailed Description
Constructor & Destructor Documentation
MovableMapObject()
MovableMapObject::MovableMapObject () protected default
Member Function Documentation
GetCurrentCell()
Cell const & MovableMapObject::GetCurrentCell () const inline private
{ return _currentCell; }
References _currentCell.
Referenced by Map::CreatureRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), and Map::MoveAllGameObjectsInMoveList().
SetCurrentCell()
void MovableMapObject::SetCurrentCell (Cell const & cell) inline private
{ _currentCell = cell; }
References _currentCell.
Referenced by Map::AddToGrid(), and ObjectGridLoader::SetObjectCell().
Friends And Related Function Documentation
Map
friend class Map friend
ObjectGridLoader
friend class ObjectGridLoader friend
RandomMovementGenerator
template<class T > friend class RandomMovementGenerator friend
Member Data Documentation
_currentCell
Cell MovableMapObject::_currentCell private
Referenced by GetCurrentCell(), and SetCurrentCell().
_moveState
MapObjectCellMoveState MovableMapObject::_moveState {MAP_OBJECT_CELL_MOVE_NONE} private
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), Map::AddCreatureToMoveList(), Map::AddDynamicObjectToMoveList(), Map::AddGameObjectToMoveList(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), Map::RemoveCreatureFromMoveList(), Map::RemoveDynamicObjectFromMoveList(), and Map::RemoveGameObjectFromMoveList().