AzerothCore: boss_jedoga_shadowseeker Struct Reference
boss_jedoga_shadowseeker Struct Reference
Public Member Functions
boss_jedoga_shadowseeker (Creature *pCreature)
void MoveInLineOfSight (Unit *) override
void Reset () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *killer) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void DoAction (int32 action) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void KilledUnit (Unit *who) override
void JustDied (Unit *) override
void MovementInform (uint32 type, uint32 pointId) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
uint32 GetData (uint32 type) const override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Member Functions
void ReschedulleCombatEvents ()
void DespawnOOCSummons ()
Private Attributes
GuidList oocSummons
GuidList oocTriggers
ObjectGuid sacraficeTarget_GUID
uint32 sayPreachTimer
bool combatSummonsSummoned
bool ritualTriggered
bool volunteerWork
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_jedoga_shadowseeker()
boss_jedoga_shadowseeker::boss_jedoga_shadowseeker (Creature * pCreature) inline
                                                  : BossAI(pCreature, DATA_JEDOGA_SHADOWSEEKER),
        sayPreachTimer(120000),
        combatSummonsSummoned(false),
        ritualTriggered(false),
        volunteerWork(true)
    { }
Member Function Documentation
DamageTaken()
void boss_jedoga_shadowseeker::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
    {
        if (!ritualTriggered && me->HealthBelowPctDamaged(55, damage) && events.IsInPhase(PHASE_NORMAL))
        {
            me->SetCombatMovement(false);
            me->InterruptNonMeleeSpells(false);
            me->AttackStop();
            me->SetReactState(REACT_PASSIVE);
            me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
            events.SetPhase(PHASE_RITUAL);
            events.ScheduleEvent(EVENT_JEDOGA_PREPARE_RITUAL, 1s, 0, PHASE_RITUAL);
            ritualTriggered = true;
            return;
        }
        if (events.IsInPhase(PHASE_RITUAL))
        {
            damage = 0;
        }
    }
References Unit::AttackStop(), EVENT_JEDOGA_PREPARE_RITUAL, Unit::HealthBelowPctDamaged(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, PHASE_NORMAL, PHASE_RITUAL, REACT_PASSIVE, ritualTriggered, Creature::SetCombatMovement(), Creature::SetReactState(), Unit::SetUnitFlag(), UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
DespawnOOCSummons()
void boss_jedoga_shadowseeker::DespawnOOCSummons () inline private
    {
        if (!oocTriggers.empty())
        {
            for (ObjectGuid const& guid : oocTriggers)
            {
                if (Creature* summon = ObjectAccessor::GetCreature(*me, guid))
                {
                    summon->DespawnOrUnsummon();
                }
            }
            oocTriggers.clear();
        }
        if (!oocSummons.empty())
        {
            for (ObjectGuid const& guid : oocSummons)
            {
                if (Creature* summon = ObjectAccessor::GetCreature(*me, guid))
                {
                    summon->DespawnOrUnsummon();
                }
            }
            oocSummons.clear();
        }
    }
References ObjectAccessor::GetCreature(), ScriptedAI::me, oocSummons, and oocTriggers.
Referenced by JustDied(), Reset(), and SummonedCreatureDies().
DoAction()
void boss_jedoga_shadowseeker::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        if (action == ACTION_SACRAFICE)
        {
            if (Creature* target = ObjectAccessor::GetCreature(*me, sacraficeTarget_GUID))
            {
                Unit::Kill(me, target);
            }
        }
    }
References ACTION_SACRAFICE, ObjectAccessor::GetCreature(), Unit::Kill(), ScriptedAI::me, and sacraficeTarget_GUID.
GetData()
uint32 boss_jedoga_shadowseeker::GetData (uint32 type) const inline override virtual
Reimplemented from UnitAI.
    {
        if (type == DATA_VOLUNTEER_WORK)
        {
            return volunteerWork ? 1 : 0;
        }
        return 0;
    }
References DATA_VOLUNTEER_WORK, and volunteerWork.
JustDied()
void boss_jedoga_shadowseeker::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
    {
        _JustDied();
        DespawnOOCSummons();
        Talk(SAY_DEATH);
    }
References BossAI::_JustDied(), DespawnOOCSummons(), and SAY_DEATH.
JustEngagedWith()
void boss_jedoga_shadowseeker::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        _JustEngagedWith();
        Talk(SAY_AGGRO);
        ReschedulleCombatEvents();
    }
References BossAI::_JustEngagedWith(), ReschedulleCombatEvents(), and SAY_AGGRO.
JustSummoned()
void boss_jedoga_shadowseeker::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
    {
        if (summon->GetEntry() == NPC_JEDOGA_CONTROLLER)
        {
            summons.Summon(summon);
        }
    }
References Object::GetEntry(), NPC_JEDOGA_CONTROLLER, SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_jedoga_shadowseeker::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (!who->IsPlayer())
        {
            return;
        }
        Talk(SAY_SLAY);
    }
References Object::IsPlayer(), and SAY_SLAY.
MoveInLineOfSight()
void boss_jedoga_shadowseeker::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{}
MovementInform()
void boss_jedoga_shadowseeker::MovementInform (uint32 type, uint32 pointId) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (!(type == POINT_MOTION_TYPE || type == EFFECT_MOTION_TYPE))
        {
            return;
        }
        switch (pointId)
        {
            case POINT_DOWN:
            {
                me->ClearUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
                ReschedulleCombatEvents();
                me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                me->SetImmuneToAll(false);
                me->SetReactState(REACT_AGGRESSIVE);
                me->RemoveAurasDueToSpell(SPELL_SPHERE_VISUAL);
                me->RemoveAurasDueToSpell(SPELL_LIGHTNING_BOLTS);
                me->RemoveAurasDueToSpell(SPELL_HOVER_FALL);
                me->SetCombatMovement(true);
                me->SetDisableGravity(false);
                me->SetHover(false);
                me->SetInCombatWithZone();
                if (Unit* victim = me->GetVictim())
                {
                    me->StopMoving();
                    AttackStart(victim);
                }
                break;
            }
            case POINT_UP:
            {
                me->SetFacingTo(5.66f);
                if (!summons.empty())
                {
                    sacraficeTarget_GUID = Acore::Containers::SelectRandomContainerElement(summons);
                    if (ObjectAccessor::GetCreature(*me, sacraficeTarget_GUID))
                    {
                        events.ScheduleEvent(EVENT_JEDGA_START_RITUAL, 3s, 0, PHASE_RITUAL);
                    }
                    // Something failed, let players continue but do not grant achievement
                    else
                    {
                        volunteerWork = false;
                        me->GetMotionMaster()->Clear();
                        DoCastSelf(SPELL_HOVER_FALL);
                        me->GetMotionMaster()->MovePoint(POINT_DOWN, JedogaPosition[1], false);
                    }
                }
                break;
            }
            case POINT_RITUAL:
            {
                me->SetFacingTo(5.66f);
                DoCastSelf(SPELL_HOVER_FALL);
                events.ScheduleEvent(EVENT_JEDOGA_MOVE_UP, 1s, 0, PHASE_RITUAL);
                break;
            }
            case POINT_INITIAL:
            {
                me->SetFacingTo(5.66f);
                DoCastSelf(SPELL_SPHERE_VISUAL, true);
                DoCastSelf(SPELL_LIGHTNING_BOLTS, true);
                if (!oocTriggers.empty())
                {
                    for (ObjectGuid const& guid : oocTriggers)
                    {
                        if (Creature* trigger = ObjectAccessor::GetCreature(*me, guid))
{
                            trigger->CastSpell(nullptr, SPELL_BEAM_VISUAL_JEDOGA);
                        }
                    }
                }
                break;
            }
        }
    }
References ScriptedAI::AttackStart(), MotionMaster::Clear(), Unit::ClearUnitState(), UnitAI::DoCastSelf(), EFFECT_MOTION_TYPE, SummonList::empty(), EVENT_JEDGA_START_RITUAL, EVENT_JEDOGA_MOVE_UP, ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), Unit::GetVictim(), JedogaPosition, ScriptedAI::me, MotionMaster::MovePoint(), oocTriggers, PHASE_RITUAL, POINT_DOWN, POINT_INITIAL, POINT_MOTION_TYPE, POINT_RITUAL, POINT_UP, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Unit::RemoveUnitFlag(), ReschedulleCombatEvents(), sacraficeTarget_GUID, Acore::Containers::SelectRandomContainerElement(), Creature::SetCombatMovement(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Creature::SetHover(), Unit::SetImmuneToAll(), Creature::SetInCombatWithZone(), Creature::SetReactState(), SPELL_BEAM_VISUAL_JEDOGA, SPELL_HOVER_FALL, SPELL_LIGHTNING_BOLTS, SPELL_SPHERE_VISUAL, Unit::StopMoving(), BossAI::summons, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_NO_ENVIRONMENT_UPD, and volunteerWork.
ReschedulleCombatEvents()
void boss_jedoga_shadowseeker::ReschedulleCombatEvents () inline private
    {
        events.SetPhase(PHASE_NORMAL);
        events.RescheduleEvent(EVENT_JEDOGA_CYCLONE, 3s, 0, PHASE_NORMAL);
        events.RescheduleEvent(EVENT_JEDOGA_LIGHTNING_BOLT, 7s, 0, PHASE_NORMAL);
        events.RescheduleEvent(EVENT_JEDOGA_THUNDERSHOCK, 12s, 0, PHASE_NORMAL);
    }
References EVENT_JEDOGA_CYCLONE, EVENT_JEDOGA_LIGHTNING_BOLT, EVENT_JEDOGA_THUNDERSHOCK, and PHASE_NORMAL.
Referenced by JustEngagedWith(), and MovementInform().
Reset()
void boss_jedoga_shadowseeker::Reset () inline override virtual
Reimplemented from BossAI.
    {
        me->SetReactState(REACT_PASSIVE);
        me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
        me->SetImmuneToAll(true);
        me->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
        me->SetDisableGravity(true);
        me->SetHover(true);
        me->GetMotionMaster()->MovePoint(POINT_INITIAL, JedogaPosition[0], false);
        _Reset();
        events.SetPhase(PHASE_NORMAL);
        DespawnOOCSummons();
        std::list<TempSummon*> tempOOCSummons;
        me->SummonCreatureGroup(SUMMON_GROUP_OOC, &tempOOCSummons);
        if (!tempOOCSummons.empty())
        {
            for (TempSummon* summon : tempOOCSummons)
            {
                if (summon)
                {
                    summon->ApplySpellImmune(0, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, false);
                    summon->ApplySpellImmune(0, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_MAGIC, false);
                    summon->RemoveAurasDueToSpell(SPELL_WHITE_SPHERE);
                    summon->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                    summon->SetStandState(UNIT_STAND_STATE_KNEEL);
                    oocSummons.push_back(summon->GetGUID());
                }
            }
        }
        tempOOCSummons.clear();
        me->SummonCreatureGroup(SUMMON_GROUP_OOC_TRIGGERS, &tempOOCSummons);
        if (!tempOOCSummons.empty())
        {
            for (TempSummon* trigger : tempOOCSummons)
            {
                if (trigger)
                {
                    oocTriggers.push_back(trigger->GetGUID());
                }
            }
        }
        sacraficeTarget_GUID.Clear();
        sayPreachTimer = 120000;
        ritualTriggered = false;
        volunteerWork = true;
        combatSummonsSummoned = false;
    }
References BossAI::_Reset(), Unit::AddUnitState(), ObjectGuid::Clear(), combatSummonsSummoned, DespawnOOCSummons(), Unit::GetMotionMaster(), IMMUNITY_DAMAGE, JedogaPosition, ScriptedAI::me, MotionMaster::MovePoint(), oocSummons, oocTriggers, PHASE_NORMAL, POINT_INITIAL, REACT_PASSIVE, ritualTriggered, sacraficeTarget_GUID, sayPreachTimer, Creature::SetDisableGravity(), Creature::SetHover(), Unit::SetImmuneToAll(), Creature::SetReactState(), Unit::SetUnitFlag(), SPELL_SCHOOL_MASK_MAGIC, SPELL_SCHOOL_MASK_NORMAL, SPELL_WHITE_SPHERE, SUMMON_GROUP_OOC, SUMMON_GROUP_OOC_TRIGGERS, WorldObject::SummonCreatureGroup(), UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STAND_STATE_KNEEL, UNIT_STATE_NO_ENVIRONMENT_UPD, and volunteerWork.
SummonedCreatureDies()
void boss_jedoga_shadowseeker::SummonedCreatureDies (Creature * summon, Unit * killer) inline override virtual
Reimplemented from CreatureAI.
    {
        switch (summon->GetEntry())
        {
            case NPC_TWILIGHT_INITIATE:
            {
                GuidList::iterator itr = std::find(oocSummons.begin(), oocSummons.end(), summon->GetGUID());
                if (itr == oocSummons.end())
                {
                    break;
                }
                oocSummons.erase(itr);
                if (!oocSummons.empty())
                {
                    break;
                }
                DespawnOOCSummons();
                DoCastSelf(SPELL_HOVER_FALL);
                me->GetMotionMaster()->MoveIdle();
                me->GetMotionMaster()->MovePoint(POINT_DOWN, JedogaPosition[1], false);
                if (!combatSummonsSummoned)
                {
                    summons.DespawnEntry(NPC_TWILIGHT_VOLUNTEER);
                    for (uint8 i = 0; i < MAX_COMBAT_INITIATES; ++i)
                    {
                        if (TempSummon* summon = me->SummonCreature(NPC_TWILIGHT_VOLUNTEER, VolunteerSpotPositions[i][0], TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000))
{
                            summon->GetMotionMaster()->MovePoint(POINT_INITIAL, VolunteerSpotPositions[i][1]);
                            summon->SetReactState(REACT_PASSIVE);
                            summon->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                            summon->SetImmuneToAll(true);
                            summons.Summon(summon);
                        }
                    }
                    combatSummonsSummoned = true;
                }
                break;
            }
            case NPC_TWILIGHT_VOLUNTEER:
            {
                if (sacraficeTarget_GUID && summon->GetGUID() != sacraficeTarget_GUID)
                {
                    break;
                }
                if (killer != me && killer->GetGUID() != sacraficeTarget_GUID)
                {
                    volunteerWork = false;
                }
                else
                {
                    DoCastSelf(SPELL_GIFT_OF_THE_HERALD, true);
                }
                events.ScheduleEvent(EVENT_JEDOGA_MOVE_DOWN, 1s, 0, PHASE_RITUAL);
                break;
            }
        }
        summons.Despawn(summon);
    }
References combatSummonsSummoned, SummonList::Despawn(), SummonList::DespawnEntry(), DespawnOOCSummons(), UnitAI::DoCastSelf(), EVENT_JEDOGA_MOVE_DOWN, Object::GetEntry(), Object::GetGUID(), Unit::GetMotionMaster(), JedogaPosition, MAX_COMBAT_INITIATES, ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), NPC_TWILIGHT_INITIATE, NPC_TWILIGHT_VOLUNTEER, oocSummons, PHASE_RITUAL, POINT_DOWN, POINT_INITIAL, REACT_PASSIVE, sacraficeTarget_GUID, Unit::SetImmuneToAll(), Creature::SetReactState(), Unit::SetUnitFlag(), SPELL_GIFT_OF_THE_HERALD, SPELL_HOVER_FALL, SummonList::Summon(), WorldObject::SummonCreature(), BossAI::summons, TEMPSUMMON_CORPSE_TIMED_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, VolunteerSpotPositions, and volunteerWork.
UpdateAI()
void boss_jedoga_shadowseeker::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
    {
        if (!UpdateVictim())
        {
            if (instance->GetBossState(DATA_PRINCE_TALDARAM) == DONE)
            {
                if (sayPreachTimer <= diff)
                {
                    Talk(SAY_PREACHING);
                    sayPreachTimer = 120000;    // 2 min
                }
                else
                {
                    sayPreachTimer -= diff;
                }
            }
            return;
        }
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
        while (uint32 const eventId = events.ExecuteEvent())
        {
            switch (eventId)
            {
                // Normal phase
                case EVENT_JEDOGA_CYCLONE:
                {
                    DoCastSelf(DUNGEON_MODE(SPELL_CYCLONE_STRIKE, SPELL_CYCLONE_STRIKE_H), false);
                    events.Repeat(10s, 14s);
                    break;
                }
                case EVENT_JEDOGA_LIGHTNING_BOLT:
                {
                    if (Unit* pTarget = SelectTarget(SelectTargetMethod::Random, 0, 100, true))
                    {
                        DoCast(pTarget, DUNGEON_MODE(SPELL_LIGHTNING_BOLT, SPELL_LIGHTNING_BOLT_H), false);
                    }
                    events.Repeat(11s, 15s);
                    break;
                }
                case EVENT_JEDOGA_THUNDERSHOCK:
                {
                    if (Unit* pTarget = SelectTarget(SelectTargetMethod::Random, 0, 100, true))
                    {
                        DoCast(pTarget, DUNGEON_MODE(SPELL_THUNDERSHOCK, SPELL_THUNDERSHOCK_H), false);
                    }
                    events.Repeat(16s, 22s);
                    break;
                }
                // Ritual phase
                case EVENT_JEDOGA_PREPARE_RITUAL:
                {
                    me->GetMotionMaster()->Clear(true);
                    me->GetMotionMaster()->MovePoint(POINT_RITUAL, JedogaPosition[1]);
                    break;
                }
                case EVENT_JEDOGA_MOVE_UP:
                {
                    me->GetMotionMaster()->Clear(true);
                    me->SetDisableGravity(true);
                    me->SetHover(true);
                    me->GetMotionMaster()->MoveTakeoff(POINT_UP, JedogaPosition[0], 7.0f);
                    break;
                }
                case EVENT_JEDOGA_MOVE_DOWN:
                {
                    summons.DespawnEntry(NPC_JEDOGA_CONTROLLER);
                    DoCastSelf(SPELL_HOVER_FALL);
                    me->GetMotionMaster()->Clear();
                    me->GetMotionMaster()->MovePoint(POINT_DOWN, JedogaPosition[1], false);
                    break;
                }
                case EVENT_JEDGA_START_RITUAL:
                {
                    sacraficeTarget_GUID = Acore::Containers::SelectRandomContainerElement(summons);
                    if (Creature* volunteer = ObjectAccessor::GetCreature(*me, sacraficeTarget_GUID))
                    {
                        Talk(SAY_SACRIFICE_1);
                        sacraficeTarget_GUID = volunteer->GetGUID();
                        volunteer->AI()->DoAction(ACTION_RITUAL_BEGIN);
                    }
                    break;
                }
            }
        }
        DoMeleeAttackIfReady();
    }
References ACTION_RITUAL_BEGIN, MotionMaster::Clear(), DATA_PRINCE_TALDARAM, SummonList::DespawnEntry(), UnitAI::DoCast(), UnitAI::DoCastSelf(), UnitAI::DoMeleeAttackIfReady(), DONE, ScriptedAI::DUNGEON_MODE(), EVENT_JEDGA_START_RITUAL, EVENT_JEDOGA_CYCLONE, EVENT_JEDOGA_LIGHTNING_BOLT, EVENT_JEDOGA_MOVE_DOWN, EVENT_JEDOGA_MOVE_UP, EVENT_JEDOGA_PREPARE_RITUAL, EVENT_JEDOGA_THUNDERSHOCK, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), Unit::HasUnitState(), BossAI::instance, JedogaPosition, ScriptedAI::me, MotionMaster::MovePoint(), MotionMaster::MoveTakeoff(), NPC_JEDOGA_CONTROLLER, POINT_DOWN, POINT_RITUAL, POINT_UP, sacraficeTarget_GUID, SAY_PREACHING, SAY_SACRIFICE_1, sayPreachTimer, Acore::Containers::SelectRandomContainerElement(), UnitAI::SelectTarget(), Creature::SetDisableGravity(), Creature::SetHover(), SPELL_CYCLONE_STRIKE, SPELL_CYCLONE_STRIKE_H, SPELL_HOVER_FALL, SPELL_LIGHTNING_BOLT, SPELL_LIGHTNING_BOLT_H, SPELL_THUNDERSHOCK, SPELL_THUNDERSHOCK_H, BossAI::summons, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
combatSummonsSummoned
bool boss_jedoga_shadowseeker::combatSummonsSummoned private
Referenced by Reset(), and SummonedCreatureDies().
oocSummons
GuidList boss_jedoga_shadowseeker::oocSummons private
Referenced by DespawnOOCSummons(), Reset(), and SummonedCreatureDies().
oocTriggers
GuidList boss_jedoga_shadowseeker::oocTriggers private
Referenced by DespawnOOCSummons(), MovementInform(), and Reset().
ritualTriggered
bool boss_jedoga_shadowseeker::ritualTriggered private
Referenced by DamageTaken(), and Reset().
sacraficeTarget_GUID
ObjectGuid boss_jedoga_shadowseeker::sacraficeTarget_GUID private
Referenced by DoAction(), MovementInform(), Reset(), SummonedCreatureDies(), and UpdateAI().
sayPreachTimer
uint32 boss_jedoga_shadowseeker::sayPreachTimer private
Referenced by Reset(), and UpdateAI().
volunteerWork
bool boss_jedoga_shadowseeker::volunteerWork private
Referenced by GetData(), MovementInform(), Reset(), and SummonedCreatureDies().