AzerothCore: ScriptObject Class Reference
ScriptObject Class Reference
#include "ScriptMgr.h"
Public Member Functions
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Private Attributes
const std::string _name
Friends
class ScriptMgr
Detailed Description
Constructor & Destructor Documentation
ScriptObject()
ScriptObject::ScriptObject (const char * name) inline protected
        : _name(std::string(name))
    {
    }
~ScriptObject()
virtual ScriptObject::~ScriptObject () protected virtual default
Member Function Documentation
checkValidity()
virtual void ScriptObject::checkValidity () inline virtual
Reimplemented in WorldMapScript, InstanceMapScript, and BattlegroundMapScript.
{ }
GetName()
const std::string & ScriptObject::GetName () const inline
{ return _name; }
References _name.
Referenced by ScriptMgr::CreateAuraScripts(), and ScriptMgr::CreateSpellScripts().
isAfterLoadScript()
virtual bool ScriptObject::isAfterLoadScript () const inline virtual
Reimplemented in WorldMapScript, and BattlegroundMapScript.
{ return IsDatabaseBound(); }
References IsDatabaseBound().
IsDatabaseBound()
virtual bool ScriptObject::IsDatabaseBound () const inline virtual
Reimplemented in SpellScriptLoader, InstanceMapScript, ItemScript, CreatureScript, GameObjectScript, AreaTriggerScript, BattlegroundScript, OutdoorPvPScript, WeatherScript, ConditionScript, TransportScript, AchievementCriteriaScript, GuildScript, GroupScript, BGScript, ArenaTeamScript, SpellSC, AchievementScript, PetScript, ArenaScript, MiscScript, CommandSC, DatabaseScript, WorldObjectScript, and LootScript.
{ return false; }
Referenced by isAfterLoadScript().
Friends And Related Function Documentation
ScriptMgr
friend class ScriptMgr friend
Member Data Documentation
_name
const std::string ScriptObject::_name private
Referenced by GetName().