AzerothCore: spell_item_brewfest_mount_transformation Class Reference
spell_item_brewfest_mount_transformation Class Reference
Private Member Functions
PrepareSpellScript (spell_item_brewfest_mount_transformation)
bool Validate (SpellInfo const *) override
void HandleDummy (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleDummy()
void spell_item_brewfest_mount_transformation::HandleDummy (SpellEffIndex) inline private
    {
        Player* caster = GetCaster()->ToPlayer();
        if (!caster)
        {
            return;
        }
        if (caster->HasAuraType(SPELL_AURA_MOUNTED))
        {
            caster->RemoveAurasByType(SPELL_AURA_MOUNTED);
            uint32 spell_id;
            switch (GetSpellInfo()->Id)
            {
            case SPELL_BREWFEST_MOUNT_TRANSFORM:
                if (caster->GetSpeedRate(MOVE_RUN) >= 2.0f)
                    spell_id = caster->GetTeamId() == TEAM_ALLIANCE ? SPELL_MOUNT_RAM_100 : SPELL_MOUNT_KODO_100;
                else
                    spell_id = caster->GetTeamId() == TEAM_ALLIANCE ? SPELL_MOUNT_RAM_60 : SPELL_MOUNT_KODO_60;
                break;
            case SPELL_BREWFEST_MOUNT_TRANSFORM_REVERSE:
                if (caster->GetSpeedRate(MOVE_RUN) >= 2.0f)
                    spell_id = caster->GetTeamId() == TEAM_HORDE ? SPELL_MOUNT_RAM_100 : SPELL_MOUNT_KODO_100;
                else
                    spell_id = caster->GetTeamId() == TEAM_HORDE ? SPELL_MOUNT_RAM_60 : SPELL_MOUNT_KODO_60;
                break;
            default:
                return;
            }
            caster->CastSpell(caster, spell_id, true);
        }
    }
References Unit::CastSpell(), SpellScript::GetCaster(), Unit::GetSpeedRate(), SpellScript::GetSpellInfo(), Player::GetTeamId(), Unit::HasAuraType(), MOVE_RUN, Unit::RemoveAurasByType(), SPELL_AURA_MOUNTED, SPELL_BREWFEST_MOUNT_TRANSFORM, SPELL_BREWFEST_MOUNT_TRANSFORM_REVERSE, SPELL_MOUNT_KODO_100, SPELL_MOUNT_KODO_60, SPELL_MOUNT_RAM_100, SPELL_MOUNT_RAM_60, TEAM_ALLIANCE, TEAM_HORDE, and Object::ToPlayer().
Referenced by Register().
PrepareSpellScript()
spell_item_brewfest_mount_transformation::PrepareSpellScript (spell_item_brewfest_mount_transformation) private
Register()
void spell_item_brewfest_mount_transformation::Register () inline override private virtual
Implements _SpellScript.
    {
        OnEffectHitTarget += SpellEffectFn(spell_item_brewfest_mount_transformation::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
References EFFECT_0, HandleDummy(), SpellScript::OnEffectHitTarget, SPELL_EFFECT_DUMMY, and SpellEffectFn.
Validate()
bool spell_item_brewfest_mount_transformation::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo(
            {
                SPELL_MOUNT_RAM_100,
                SPELL_MOUNT_RAM_60,
                SPELL_MOUNT_KODO_100,
                SPELL_MOUNT_KODO_60
            });
    }
References SPELL_MOUNT_KODO_100, SPELL_MOUNT_KODO_60, SPELL_MOUNT_RAM_100, SPELL_MOUNT_RAM_60, and _SpellScript::ValidateSpellInfo().