AzerothCore: SpellTargetSelector Struct Reference
SpellTargetSelector Struct Reference
#include "UnitAI.h"
Public Member Functions
SpellTargetSelector (Unit *caster, uint32 spellId)
bool operator() (Unit const *target) const
Private Attributes
Unit const * _caster
SpellInfo const * _spellInfo
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Todo:
: Add more checks from Spell::CheckCast
Constructor & Destructor Documentation
SpellTargetSelector()
SpellTargetSelector::SpellTargetSelector (Unit * caster, uint32 spellId)
                                                                     :
    _caster(caster), _spellInfo(sSpellMgr->GetSpellForDifficultyFromSpell(sSpellMgr->GetSpellInfo(spellId), caster))
{
    ASSERT(_spellInfo);
}
References _spellInfo, and ASSERT.
Member Function Documentation
operator()()
bool SpellTargetSelector::operator() (Unit const * target) const
{
    if (!target)
        return false;
    if (_spellInfo->CheckTarget(_caster, target) != SPELL_CAST_OK)
        return false;
    // copypasta from Spell::CheckRange
    uint32 range_type = _spellInfo->RangeEntry ? _spellInfo->RangeEntry->Flags : 0;
    float max_range = _caster->GetSpellMaxRangeForTarget(target, _spellInfo);
    float min_range = _caster->GetSpellMinRangeForTarget(target, _spellInfo);
    if (target && target != _caster)
    {
        if (range_type == SPELL_RANGE_MELEE)
        {
            // Because of lag, we can not check too strictly here.
            if (!_caster->IsWithinMeleeRange(target, max_range))
                return false;
        }
        else if (!_caster->IsWithinCombatRange(target, max_range))
            return false;
        if (range_type == SPELL_RANGE_RANGED)
        {
            if (_caster->IsWithinMeleeRange(target))
                return false;
        }
        else if (min_range && _caster->IsWithinCombatRange(target, min_range)) // skip this check if min_range = 0
            return false;
    }
    return true;
}
References _caster, _spellInfo, SpellInfo::CheckTarget(), SpellRangeEntry::Flags, Unit::GetSpellMaxRangeForTarget(), Unit::GetSpellMinRangeForTarget(), Unit::IsWithinCombatRange(), Unit::IsWithinMeleeRange(), SpellInfo::RangeEntry, SPELL_CAST_OK, SPELL_RANGE_MELEE, and SPELL_RANGE_RANGED.
Member Data Documentation
_caster
Unit const* SpellTargetSelector::_caster private
Referenced by operator()().
_spellInfo
SpellInfo const* SpellTargetSelector::_spellInfo private
Referenced by operator()(), and SpellTargetSelector().