AzerothCore: npc_ulduar_expedition_commander Class Reference
npc_ulduar_expedition_commander Class Reference
Classes
struct npc_ulduar_expedition_commanderAI
Public Member Functions
npc_ulduar_expedition_commander ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_ulduar_expedition_commander()
npc_ulduar_expedition_commander::npc_ulduar_expedition_commander () inline
: CreatureScript("npc_ulduar_expedition_commander") { }
Member Function Documentation
GetAI()
CreatureAI * npc_ulduar_expedition_commander::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return GetUlduarAI<npc_ulduar_expedition_commanderAI>(creature);
    }
OnGossipHello()
bool npc_ulduar_expedition_commander::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (!player || !creature)
            return true;
        InstanceScript* instance = creature->GetInstanceScript();
        if (!instance)
            return true;
        if (instance->GetData(TYPE_RAZORSCALE) == DONE)
            return true;
        Creature* razorscale = ObjectAccessor::GetCreature(*creature, instance->GetGuidData(TYPE_RAZORSCALE));
        if (!razorscale || razorscale->IsInCombat())
            return true;
        AddGossipItemFor(player, GOSSIP_MENU_START_ENCOUNTER, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
        SendGossipMenuFor(player, NPC_TEXT_COMMANDER, creature);
        return true;
    }
References AddGossipItemFor(), DONE, ObjectAccessor::GetCreature(), ZoneScript::GetData(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, GOSSIP_MENU_START_ENCOUNTER, GOSSIP_SENDER_MAIN, Unit::IsInCombat(), NPC_TEXT_COMMANDER, SendGossipMenuFor(), and TYPE_RAZORSCALE.
OnGossipSelect()
bool npc_ulduar_expedition_commander::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
    {
        if (!player || !creature)
            return true;
        if (uiAction == GOSSIP_ACTION_INFO_DEF + 1)
        {
            InstanceScript* instance = creature->GetInstanceScript();
            if (!instance || instance->GetData(TYPE_RAZORSCALE) == DONE)
                return true;
            Creature* razorscale = ObjectAccessor::GetCreature(*creature, instance->GetGuidData(TYPE_RAZORSCALE));
            if (razorscale && !razorscale->IsInCombat())
            {
                // Do not show gossip icon if encounter is in progress
                creature->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                // reset npcs NPC_HARPOON_FIRE_STATE
                for (uint8 i = 0; i < 4; ++i)
                    if (Creature* hfs = ObjectAccessor::GetCreature(*creature, instance->GetGuidData(DATA_HARPOON_FIRE_STATE_1 + i)))
                        hfs->AI()->SetData(1, 0);
                if (razorscale->AI())
                {
                    razorscale->AI()->AttackStart(player);
                    razorscale->GetMotionMaster()->MoveIdle();
                    razorscale->GetMotionMaster()->MovePoint(POINT_RAZORSCALE_INIT, 588.0f, -178.0f, 490.0f, false, false);
                }
            }
        }
        player->PlayerTalkClass->SendCloseGossip();
        return true;
    }
References Creature::AI(), UnitAI::AttackStart(), DATA_HARPOON_FIRE_STATE_1, DONE, ObjectAccessor::GetCreature(), ZoneScript::GetData(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), Unit::GetMotionMaster(), GOSSIP_ACTION_INFO_DEF, Unit::IsInCombat(), MotionMaster::MoveIdle(), MotionMaster::MovePoint(), Player::PlayerTalkClass, POINT_RAZORSCALE_INIT, Unit::RemoveNpcFlag(), PlayerMenu::SendCloseGossip(), TYPE_RAZORSCALE, and UNIT_NPC_FLAG_GOSSIP.