AzerothCore: boss_onyxia Struct Reference
boss_onyxia Struct Reference
Public Member Functions
boss_onyxia (Creature *pCreature)
void Initialize ()
void SetPhase (uint8 ph)
void Reset () override
void DoAction (int32 param) override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void MovementInform (uint32 type, uint32 id) override
void HandleWhelpSpam (const uint32 diff)
bool CheckInRoom () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint8 Phase
int8 CurrentWP
bool whelpSpam
uint8 whelpCount
int32 whelpSpamTimer
bool bManyWhelpsAvailable
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_onyxia()
boss_onyxia::boss_onyxia (Creature * pCreature) inline
                                     : BossAI(pCreature, DATA_ONYXIA)
    {
        Initialize();
    }
References Initialize().
Member Function Documentation
CheckInRoom()
bool boss_onyxia::CheckInRoom () inline override virtual
Reimplemented from CreatureAI.
    {
        if (me->GetDistance2d(me->GetHomePosition().GetPositionX(), me->GetHomePosition().GetPositionY()) > 95.0f)
        {
            Talk(SAY_EVADE);
            EnterEvadeMode();
            return false;
        }
        return true;
    }
References BossAI::EnterEvadeMode(), WorldObject::GetDistance2d(), Creature::GetHomePosition(), ScriptedAI::me, and SAY_EVADE.
Referenced by UpdateAI().
DamageTaken()
void boss_onyxia::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
    {
        if (me->HealthBelowPctDamaged(65, damage) && Phase == PHASE_GROUNDED)
        {
            SetPhase(PHASE_AIRPHASE);
        }
        else if (me->HealthBelowPctDamaged(40, damage) && Phase == PHASE_AIRPHASE)
        {
            me->InterruptNonMeleeSpells(false);
            SetPhase(PHASE_LANDED);
        }
    }
References Unit::HealthBelowPctDamaged(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, PHASE_AIRPHASE, PHASE_GROUNDED, PHASE_LANDED, and SetPhase().
DoAction()
void boss_onyxia::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
    {
        switch (param)
        {
            case -1:
                if (bManyWhelpsAvailable)
                {
                    instance->SetData(DATA_WHELP_SUMMONED, 1);
                }
                break;
        }
    }
References bManyWhelpsAvailable, DATA_WHELP_SUMMONED, BossAI::instance, and ZoneScript::SetData().
HandleWhelpSpam()
void boss_onyxia::HandleWhelpSpam (const uint32 diff) inline
    {
        if (whelpSpam)
        {
            if (whelpCount < 40)
            {
                whelpSpamTimer -= diff;
                if (whelpSpamTimer <= 0)
                {
                    float angle = rand_norm() * 2 * M_PI;
                    float dist  = rand_norm() * 4.0f;
                    me->CastSpell(-33.18f + cos(angle) * dist, -258.80f + std::sin(angle) * dist, -89.0f, 17646, true);
                    me->CastSpell(-32.535f + cos(angle) * dist, -170.190f + std::sin(angle) * dist, -89.0f, 17646, true);
                    whelpCount += 2;
                    whelpSpamTimer += 600;
                }
            }
            else
            {
                whelpSpam      = false;
                whelpCount     = 0;
                whelpSpamTimer = 0;
            }
        }
    }
References Unit::CastSpell(), ScriptedAI::me, rand_norm(), whelpCount, whelpSpam, and whelpSpamTimer.
Referenced by UpdateAI().
Initialize()
void boss_onyxia::Initialize () inline
    {
        CurrentWP = 0;
        whelpSpam = false;
        whelpCount = 0;
        whelpSpamTimer = 0;
        bManyWhelpsAvailable = false;
    }
References bManyWhelpsAvailable, CurrentWP, whelpCount, whelpSpam, and whelpSpamTimer.
Referenced by boss_onyxia(), and Reset().
JustEngagedWith()
void boss_onyxia::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        Talk(SAY_AGGRO);
        SetPhase(PHASE_GROUNDED);
        instance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_TIMED_START_EVENT); // just in case at reset some players already left the instance
        instance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_TIMED_START_EVENT);
        BossAI::JustEngagedWith(who);
        me->SummonCreature(NPC_ONYXIAN_LAIR_GUARD, -167.837936f, -200.549332f, -66.343231f, 5.598287f, TEMPSUMMON_MANUAL_DESPAWN);
    }
References ACHIEV_TIMED_START_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, InstanceScript::DoStartTimedAchievement(), InstanceScript::DoStopTimedAchievement(), BossAI::instance, BossAI::JustEngagedWith(), ScriptedAI::me, NPC_ONYXIAN_LAIR_GUARD, PHASE_GROUNDED, SAY_AGGRO, SetPhase(), WorldObject::SummonCreature(), and TEMPSUMMON_MANUAL_DESPAWN.
JustSummoned()
void boss_onyxia::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
    {
        summons.Summon(summon);
        if (summon->GetEntry() != NPC_ONYXIAN_WHELP && summon->GetEntry() != NPC_ONYXIAN_LAIR_GUARD)
        {
            return;
        }
        if (summon->GetEntry() == NPC_ONYXIAN_LAIR_GUARD && Phase < PHASE_AIRPHASE)
        {
            return;
        }
        if (Unit* target = summon->SelectNearestTarget(300.0f))
        {
            summon->AI()->AttackStart(target);
            DoZoneInCombat(summon);
        }
    }
References Creature::AI(), UnitAI::AttackStart(), CreatureAI::DoZoneInCombat(), Object::GetEntry(), NPC_ONYXIAN_LAIR_GUARD, NPC_ONYXIAN_WHELP, PHASE_AIRPHASE, Creature::SelectNearestTarget(), SummonList::Summon(), and BossAI::summons.
MovementInform()
void boss_onyxia::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type != POINT_MOTION_TYPE && type != EFFECT_MOTION_TYPE)
        {
            return;
        }
        if (id < 9)
        {
            if (id > 0 && Phase == PHASE_AIRPHASE)
            {
                me->SetFacingTo(OnyxiaMoveData[id].o);
                me->SetSpeed(MOVE_RUN, 1.6f, false);
                CurrentWP = id;
                events.ScheduleEvent(EVENT_SPELL_FIREBALL_FIRST, 1000);
            }
        }
        else
        {
            switch (id)
            {
                case 10:
                    me->SetFacingTo(OnyxiaMoveData[0].o);
                    events.ScheduleEvent(EVENT_LIFTOFF, 0);
                    break;
                case 11:
                    me->SetFacingTo(OnyxiaMoveData[1].o);
                    events.ScheduleEvent(EVENT_FLY_S_TO_N, 0);
                    break;
                case 12:
                    me->SetFacingTo(OnyxiaMoveData[1].o);
                    events.ScheduleEvent(EVENT_LAND, 0);
                    break;
                case 13:
                    me->SetCanFly(false);
                    me->SetDisableGravity(false);
                    me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run, false);
                    events.ScheduleEvent(EVENT_PHASE_3_ATTACK, 0);
                    break;
            }
        }
    }
References CurrentWP, EFFECT_MOTION_TYPE, EVENT_FLY_S_TO_N, EVENT_LAND, EVENT_LIFTOFF, EVENT_PHASE_3_ATTACK, EVENT_SPELL_FIREBALL_FIRST, Creature::GetCreatureTemplate(), ScriptedAI::me, MOVE_RUN, OnyxiaMoveData, PHASE_AIRPHASE, POINT_MOTION_TYPE, Creature::SetCanFly(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Unit::SetSpeed(), and CreatureTemplate::speed_run.
Reset()
void boss_onyxia::Reset () inline override virtual
Reimplemented from BossAI.
    {
        Initialize();
        SetPhase(PHASE_NONE);
        me->SetReactState(REACT_AGGRESSIVE);
        me->SetCanFly(false);
        me->SetDisableGravity(false);
        me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run, false);
        instance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_TIMED_START_EVENT);
        BossAI::Reset();
    }
References ACHIEV_TIMED_START_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, InstanceScript::DoStopTimedAchievement(), Creature::GetCreatureTemplate(), Initialize(), BossAI::instance, ScriptedAI::me, MOVE_RUN, PHASE_NONE, REACT_AGGRESSIVE, BossAI::Reset(), Creature::SetCanFly(), Creature::SetDisableGravity(), SetPhase(), Creature::SetReactState(), Unit::SetSpeed(), and CreatureTemplate::speed_run.
SetPhase()
void boss_onyxia::SetPhase (uint8 ph) inline
    {
        events.Reset();
        Phase = ph;
        switch (ph)
        {
            case PHASE_GROUNDED:
                events.ScheduleEvent(EVENT_SPELL_WINGBUFFET, urand(10000, 20000));
                events.ScheduleEvent(EVENT_SPELL_FLAMEBREATH, urand(10000, 20000));
                events.ScheduleEvent(EVENT_SPELL_TAILSWEEP, urand(15000, 20000));
                events.ScheduleEvent(EVENT_SPELL_CLEAVE, urand(2000, 5000));
                break;
            case PHASE_AIRPHASE:
                events.ScheduleEvent(EVENT_START_PHASE_2, 0);
                break;
            case PHASE_LANDED:
                events.ScheduleEvent(EVENT_START_PHASE_3, 5000);
                break;
        }
    }
References EVENT_SPELL_CLEAVE, EVENT_SPELL_FLAMEBREATH, EVENT_SPELL_TAILSWEEP, EVENT_SPELL_WINGBUFFET, EVENT_START_PHASE_2, EVENT_START_PHASE_3, PHASE_AIRPHASE, PHASE_GROUNDED, PHASE_LANDED, and urand().
Referenced by DamageTaken(), JustEngagedWith(), and Reset().
SpellHitTarget()
void boss_onyxia::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (target->IsPlayer() && spell->DurationEntry && spell->DurationEntry->ID == 328 && spell->Effects[EFFECT_1].TargetA.GetTarget() == 1 && (spell->Effects[EFFECT_1].Amplitude == 50 || spell->Effects[EFFECT_1].Amplitude == 215)) // Deep Breath
        {
            instance->SetData(DATA_DEEP_BREATH_FAILED, 1);
        }
    }
References DATA_DEEP_BREATH_FAILED, SpellInfo::DurationEntry, EFFECT_1, SpellInfo::Effects, SpellDurationEntry::ID, BossAI::instance, Object::IsPlayer(), and ZoneScript::SetData().
UpdateAI()
void boss_onyxia::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
    {
        if (!UpdateVictim() || !CheckInRoom())
        {
            return;
        }
        events.Update(diff);
        HandleWhelpSpam(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
        DoMeleeAttackIfReady();
        switch (events.ExecuteEvent())
        {
            case EVENT_SPELL_WINGBUFFET:
            {
                DoCastAOE(SPELL_WINGBUFFET);
                events.RepeatEvent(urand(15000, 30000));
                break;
            }
            case EVENT_SPELL_FLAMEBREATH:
            {
                DoCastAOE(SPELL_FLAMEBREATH);
                events.RepeatEvent(urand(10000, 20000));
                break;
            }
            case EVENT_SPELL_TAILSWEEP:
            {
                DoCastAOE(SPELL_TAILSWEEP);
                events.RepeatEvent(urand(15000, 20000));
                break;
            }
            case EVENT_SPELL_CLEAVE:
            {
                DoCastVictim(SPELL_CLEAVE);
                events.RepeatEvent(urand(2000, 5000));
                break;
            }
            case EVENT_START_PHASE_2:
            {
                me->AttackStop();
                me->SetReactState(REACT_PASSIVE);
                me->StopMoving();
                DoResetThreatList();
                me->GetMotionMaster()->MovePoint(10, OnyxiaMoveData[0].x, OnyxiaMoveData[0].y, OnyxiaMoveData[0].z);
                break;
            }
            case EVENT_LIFTOFF:
            {
                Talk(SAY_PHASE_2_TRANS);
                me->SendMeleeAttackStop(me->GetVictim());
                me->GetMotionMaster()->MoveIdle();
                me->DisableSpline();
                me->SetCanFly(true);
                me->SetDisableGravity(true);
                me->SetOrientation(OnyxiaMoveData[0].o);
                me->SendMovementFlagUpdate();
                me->GetMotionMaster()->MoveTakeoff(11, OnyxiaMoveData[1].x + 1.0f, OnyxiaMoveData[1].y, OnyxiaMoveData[1].z, 12.0f);
                bManyWhelpsAvailable = true;
                events.RescheduleEvent(EVENT_END_MANY_WHELPS_TIME, 10000);
                break;
            }
            case EVENT_END_MANY_WHELPS_TIME:
                bManyWhelpsAvailable = false;
                break;
            case EVENT_FLY_S_TO_N:
            {
                me->SetSpeed(MOVE_RUN, 2.95f, false);
                me->GetMotionMaster()->MovePoint(5, OnyxiaMoveData[5].x, OnyxiaMoveData[5].y, OnyxiaMoveData[5].z);
                whelpSpam = true;
                events.ScheduleEvent(EVENT_WHELP_SPAM, 90000);
                events.ScheduleEvent(EVENT_SUMMON_LAIR_GUARD, 30000);
                break;
            }
            case EVENT_SUMMON_LAIR_GUARD:
            {
                me->CastSpell(-101.654f, -214.491f, -80.70f, SPELL_SUMMON_LAIR_GUARD, true);
                events.RepeatEvent(30000);
                break;
            }
            case EVENT_WHELP_SPAM:
            {
                whelpSpam = true;
                events.RepeatEvent(90000);
                break;
            }
            case EVENT_LAND:
            {
                Talk(SAY_PHASE_3_TRANS);
                me->SendMeleeAttackStop(me->GetVictim());
                me->GetMotionMaster()->MoveLand(13, OnyxiaMoveData[0].x + 1.0f, OnyxiaMoveData[0].y, OnyxiaMoveData[0].z, 12.0f);
                DoResetThreatList();
                break;
            }
            case EVENT_SPELL_FIREBALL_FIRST:
            {
                if (Unit* v = SelectTarget(SelectTargetMethod::Random, 0, 200.0f, true))
                {
                    me->SetFacingToObject(v);
                    DoCast(v, SPELL_FIREBALL);
                }
                events.ScheduleEvent(EVENT_SPELL_FIREBALL_SECOND, 4000);
                break;
            }
            case EVENT_SPELL_FIREBALL_SECOND:
            {
                if (Unit* v = SelectTarget(SelectTargetMethod::Random, 0, 200.0f, true))
                {
                    me->SetFacingToObject(v);
                    DoCast(v, SPELL_FIREBALL);
                }
                uint8 rand = urand(0, 99);
                if (rand < 33)
                {
                    events.ScheduleEvent(EVENT_PHASE_2_STEP_CW, 4000);
                }
                else if (rand < 66)
                {
                    events.ScheduleEvent(EVENT_PHASE_2_STEP_ACW, 4000);
                }
                else
                {
                    events.ScheduleEvent(EVENT_PHASE_2_STEP_ACROSS, 4000);
                }
                break;
            }
            case EVENT_PHASE_2_STEP_CW:
            {
                uint8 newWP = CurrentWP + 1;
                if (newWP > 8)
                {
                    newWP = 1;
                }
                me->GetMotionMaster()->MovePoint(newWP, OnyxiaMoveData[newWP].x, OnyxiaMoveData[newWP].y, OnyxiaMoveData[newWP].z);
                break;
            }
            case EVENT_PHASE_2_STEP_ACW:
            {
                uint8 newWP = CurrentWP - 1;
                if (newWP < 1)
                {
                    newWP = 8;
                }
                me->GetMotionMaster()->MovePoint(newWP, OnyxiaMoveData[newWP].x, OnyxiaMoveData[newWP].y, OnyxiaMoveData[newWP].z);
                break;
            }
            case EVENT_PHASE_2_STEP_ACROSS:
            {
                Talk(EMOTE_BREATH);
                me->SetFacingTo(OnyxiaMoveData[CurrentWP].o);
                DoCastAOE(OnyxiaMoveData[CurrentWP].spellId);
                events.ScheduleEvent(EVENT_SPELL_BREATH, 8250);
                break;
            }
            case EVENT_SPELL_BREATH:
            {
                uint8 newWP = OnyxiaMoveData[CurrentWP].DestId;
                me->SetSpeed(MOVE_RUN, 2.95f, false);
                me->GetMotionMaster()->MovePoint(newWP, OnyxiaMoveData[newWP].x, OnyxiaMoveData[newWP].y, OnyxiaMoveData[newWP].z);
                break;
            }
            case EVENT_START_PHASE_3:
            {
                me->SetSpeed(MOVE_RUN, 2.95f, false);
                me->GetMotionMaster()->MovePoint(12, OnyxiaMoveData[1].x, OnyxiaMoveData[1].y, OnyxiaMoveData[1].z);
                break;
            }
            case EVENT_PHASE_3_ATTACK:
            {
                me->SetReactState(REACT_AGGRESSIVE);
                if (Unit* target = SelectTarget(SelectTargetMethod::MaxThreat, 0, 0, false))
                {
                    AttackStart(target);
                }
                DoCastAOE(SPELL_BELLOWINGROAR);
                events.ScheduleEvent(EVENT_ERUPTION, 0);
                events.ScheduleEvent(EVENT_SPELL_WINGBUFFET, urand(10000, 20000));
                events.ScheduleEvent(EVENT_SPELL_FLAMEBREATH, urand(10000, 20000));
                events.ScheduleEvent(EVENT_SPELL_TAILSWEEP, urand(15000, 20000));
                events.ScheduleEvent(EVENT_SPELL_CLEAVE, urand(2000, 5000));
                events.ScheduleEvent(EVENT_SPELL_BELLOWINGROAR, 15000);
                events.ScheduleEvent(EVENT_SUMMON_WHELP, 10000);
                break;
            }
            case EVENT_SPELL_BELLOWINGROAR:
            {
                DoCastAOE(SPELL_BELLOWINGROAR);
                events.RepeatEvent(22000);
                events.ScheduleEvent(EVENT_ERUPTION, 0);
                break;
            }
            case EVENT_ERUPTION:
            {
                if (Creature* trigger = me->SummonCreature(12758, *me, TEMPSUMMON_TIMED_DESPAWN, 1000))
                {
                    trigger->CastSpell(trigger, 17731, false);
                }
                break;
            }
            case EVENT_SUMMON_WHELP:
            {
                float angle = rand_norm() * 2 * M_PI;
                float dist  = rand_norm() * 4.0f;
                me->CastSpell(-33.18f + cos(angle) * dist, -258.80f + std::sin(angle) * dist, -89.0f, 17646, true);
                me->CastSpell(-32.535f + cos(angle) * dist, -170.190f + std::sin(angle) * dist, -89.0f, 17646, true);
                events.RepeatEvent(30000);
                break;
            }
        }
    }
References ScriptedAI::AttackStart(), Unit::AttackStop(), bManyWhelpsAvailable, Unit::CastSpell(), CheckInRoom(), CurrentWP, sOnyxMove::DestId, Unit::DisableSpline(), UnitAI::DoCast(), UnitAI::DoCastAOE(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreatList(), EMOTE_BREATH, EVENT_END_MANY_WHELPS_TIME, EVENT_ERUPTION, EVENT_FLY_S_TO_N, EVENT_LAND, EVENT_LIFTOFF, EVENT_PHASE_2_STEP_ACROSS, EVENT_PHASE_2_STEP_ACW, EVENT_PHASE_2_STEP_CW, EVENT_PHASE_3_ATTACK, EVENT_SPELL_BELLOWINGROAR, EVENT_SPELL_BREATH, EVENT_SPELL_CLEAVE, EVENT_SPELL_FIREBALL_FIRST, EVENT_SPELL_FIREBALL_SECOND, EVENT_SPELL_FLAMEBREATH, EVENT_SPELL_TAILSWEEP, EVENT_SPELL_WINGBUFFET, EVENT_START_PHASE_2, EVENT_START_PHASE_3, EVENT_SUMMON_LAIR_GUARD, EVENT_SUMMON_WHELP, EVENT_WHELP_SPAM, Unit::GetMotionMaster(), Unit::GetVictim(), HandleWhelpSpam(), Unit::HasUnitState(), ScriptedAI::me, MOVE_RUN, MotionMaster::MoveIdle(), MotionMaster::MoveLand(), MotionMaster::MovePoint(), MotionMaster::MoveTakeoff(), OnyxiaMoveData, rand_norm(), REACT_AGGRESSIVE, REACT_PASSIVE, SAY_PHASE_2_TRANS, SAY_PHASE_3_TRANS, UnitAI::SelectTarget(), Unit::SendMeleeAttackStop(), Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Position::SetOrientation(), Creature::SetReactState(), Unit::SetSpeed(), SPELL_BELLOWINGROAR, SPELL_CLEAVE, SPELL_FIREBALL, SPELL_FLAMEBREATH, SPELL_SUMMON_LAIR_GUARD, SPELL_TAILSWEEP, SPELL_WINGBUFFET, Unit::StopMoving(), WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), urand(), and whelpSpam.
Member Data Documentation
bManyWhelpsAvailable
bool boss_onyxia::bManyWhelpsAvailable private
Referenced by DoAction(), Initialize(), and UpdateAI().
CurrentWP
int8 boss_onyxia::CurrentWP private
Referenced by Initialize(), MovementInform(), and UpdateAI().
Phase
uint8 boss_onyxia::Phase private
whelpCount
uint8 boss_onyxia::whelpCount private
Referenced by HandleWhelpSpam(), and Initialize().
whelpSpam
bool boss_onyxia::whelpSpam private
Referenced by HandleWhelpSpam(), Initialize(), and UpdateAI().
whelpSpamTimer
int32 boss_onyxia::whelpSpamTimer private
Referenced by HandleWhelpSpam(), and Initialize().