AzeorthCore: boss_doomwalker::boss_doomwalkerAI Struct Reference
boss_doomwalker::boss_doomwalkerAI Struct Reference
Public Member Functions
boss_doomwalkerAI (Creature *creature)
void Reset () override
void KilledUnit (Unit *victim) override
void JustDied (Unit *) override
void EnterCombat (Unit *) override
void MoveInLineOfSight (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
bool _inEnrage
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_doomwalkerAI()
boss_doomwalker::boss_doomwalkerAI::boss_doomwalkerAI (Creature * creature) inline
                                              : ScriptedAI(creature)
        {
        }
Member Function Documentation
EnterCombat()
void boss_doomwalker::boss_doomwalkerAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_AGGRO);
        }
References SAY_AGGRO.
JustDied()
void boss_doomwalker::boss_doomwalkerAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_DEATH);
        }
References SAY_DEATH.
KilledUnit()
void boss_doomwalker::boss_doomwalkerAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            victim->CastSpell(victim, SPELL_MARK_DEATH, 0);
            if (urand(0, 4))
                return;
            Talk(SAY_SLAY);
        }
References Unit::CastSpell(), SAY_SLAY, SPELL_MARK_DEATH, and urand().
MoveInLineOfSight()
void boss_doomwalker::boss_doomwalkerAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
        {
            if (who && who->GetTypeId() == TYPEID_PLAYER && me->IsValidAttackTarget(who))
                if (who->HasAura(SPELL_MARK_DEATH) && !who->HasAura(27827)) // Spirit of Redemption
                    who->CastSpell(who, SPELL_AURA_DEATH, 1);
        }
References Unit::CastSpell(), Object::GetTypeId(), Unit::HasAura(), Unit::IsValidAttackTarget(), ScriptedAI::me, SPELL_AURA_DEATH, SPELL_MARK_DEATH, and TYPEID_PLAYER.
Reset()
void boss_doomwalker::boss_doomwalkerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _events.Reset();
            _events.ScheduleEvent(EVENT_ENRAGE, 0);
            _events.ScheduleEvent(EVENT_ARMOR, urand(5000, 13000));
            _events.ScheduleEvent(EVENT_CHAIN, urand(10000, 30000));
            _events.ScheduleEvent(EVENT_QUAKE, urand(25000, 35000));
            _events.ScheduleEvent(EVENT_OVERRUN, urand(30000, 45000));
            _inEnrage = false;
        }
References _events, _inEnrage, EVENT_ARMOR, EVENT_CHAIN, EVENT_ENRAGE, EVENT_OVERRUN, EVENT_QUAKE, EventMap::Reset(), EventMap::ScheduleEvent(), and urand().
UpdateAI()
void boss_doomwalker::boss_doomwalkerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            _events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            while (uint32 eventId = _events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_ENRAGE:
                        if (!HealthAbovePct(20))
{
                            DoCast(me, SPELL_ENRAGE);
                            _events.ScheduleEvent(EVENT_ENRAGE, 6000);
                            _inEnrage = true;
                        }
                        break;
                    case EVENT_OVERRUN:
                        Talk(SAY_OVERRUN);
                        DoCastVictim(SPELL_OVERRUN);
                        _events.ScheduleEvent(EVENT_OVERRUN, urand(25000, 40000));
                        break;
                    case EVENT_QUAKE:
                        if (urand(0, 1))
                            return;
                        Talk(SAY_EARTHQUAKE);
                        //remove enrage before casting earthquake because enrage + earthquake = 16000dmg over 8sec and all dead
                        if (_inEnrage)
                            me->RemoveAurasDueToSpell(SPELL_ENRAGE);
                        DoCast(me, SPELL_EARTHQUAKE);
                        _events.ScheduleEvent(EVENT_QUAKE, urand(30000, 55000));
                        break;
                    case EVENT_CHAIN:
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 1, 0.0f, true))
                            DoCast(target, SPELL_CHAIN_LIGHTNING);
                        _events.ScheduleEvent(EVENT_CHAIN, urand(7000, 27000));
                        break;
                    case EVENT_ARMOR:
                        DoCastVictim(SPELL_SUNDER_ARMOR);
                        _events.ScheduleEvent(EVENT_ARMOR, urand(10000, 25000));
                        break;
                    default:
                        break;
                }
            }
            DoMeleeAttackIfReady();
        }
References _events, _inEnrage, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EVENT_ARMOR, EVENT_CHAIN, EVENT_ENRAGE, EVENT_OVERRUN, EVENT_QUAKE, EventMap::ExecuteEvent(), Unit::HasUnitState(), ScriptedAI::HealthAbovePct(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SAY_EARTHQUAKE, SAY_OVERRUN, EventMap::ScheduleEvent(), UnitAI::SelectTarget(), SPELL_CHAIN_LIGHTNING, SPELL_EARTHQUAKE, SPELL_ENRAGE, SPELL_OVERRUN, SPELL_SUNDER_ARMOR, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_events
EventMap boss_doomwalker::boss_doomwalkerAI::_events private
Referenced by Reset(), and UpdateAI().
_inEnrage
bool boss_doomwalker::boss_doomwalkerAI::_inEnrage private
Referenced by Reset(), and UpdateAI().