AzerothCore: boss_four_horsemen::boss_four_horsemenAI Struct Reference
boss_four_horsemen::boss_four_horsemenAI Struct Reference
Public Member Functions
boss_four_horsemenAI (Creature *c)
void MoveToCorner ()
bool IsInRoom ()
void Reset () override
void MovementInform (uint32 type, uint32 id) override
void AttackStart (Unit *who) override
void KilledUnit (Unit *who) override
void JustDied (Unit *killer) override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
InstanceScript * pInstance
uint8 currentWaypoint {}
uint8 movementPhase {}
uint8 horsemanId
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_four_horsemenAI()
boss_four_horsemen::boss_four_horsemenAI::boss_four_horsemenAI (Creature * c) inline explicit
                                                   : BossAI(c, BOSS_HORSEMAN)
        {
            pInstance = me->GetInstanceScript();
            switch (me->GetEntry())
            {
                case NPC_SIR_ZELIEK:
                    horsemanId = HORSEMAN_ZELIEK;
                    break;
                case NPC_LADY_BLAUMEUX:
                    horsemanId = HORSEMAN_BLAUMEUX;
                    break;
                case NPC_BARON_RIVENDARE:
                    horsemanId = HORSEMAN_RIVENDARE;
                    break;
                case NPC_THANE_KORTHAZZ:
                    horsemanId = HORSEMAN_KORTHAZZ;
                    break;
            }
        }
References Object::GetEntry(), WorldObject::GetInstanceScript(), HORSEMAN_BLAUMEUX, HORSEMAN_KORTHAZZ, HORSEMAN_RIVENDARE, HORSEMAN_ZELIEK, horsemanId, ScriptedAI::me, NPC_BARON_RIVENDARE, NPC_LADY_BLAUMEUX, NPC_SIR_ZELIEK, NPC_THANE_KORTHAZZ, and pInstance.
Member Function Documentation
AttackStart()
void boss_four_horsemen::boss_four_horsemenAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (movementPhase == MOVE_PHASE_FINISHED)
            {
                if (me->GetEntry() == NPC_LADY_BLAUMEUX || me->GetEntry() == NPC_SIR_ZELIEK)
                {
                    me->Attack(who, false);
                }
                else
                {
                    ScriptedAI::AttackStart(who);
                }
            }
        }
References Unit::Attack(), ScriptedAI::AttackStart(), Object::GetEntry(), ScriptedAI::me, MOVE_PHASE_FINISHED, movementPhase, NPC_LADY_BLAUMEUX, and NPC_SIR_ZELIEK.
Referenced by UpdateAI().
IsInRoom()
bool boss_four_horsemen::boss_four_horsemenAI::IsInRoom () inline
        {
            if (me->GetExactDist(2535.1f, -2968.7f, 241.3f) > 100.0f)
            {
                EnterEvadeMode();
                return false;
            }
            return true;
        }
References BossAI::EnterEvadeMode(), Position::GetExactDist(), and ScriptedAI::me.
Referenced by UpdateAI().
JustDied()
void boss_four_horsemen::boss_four_horsemenAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
        {
            BossAI::JustDied(killer);
            if (pInstance)
            {
                if (pInstance->GetBossState(BOSS_HORSEMAN) == DONE)
                {
                    if (!me->GetMap()->GetPlayers().IsEmpty())
                    {
                        if (Player* player = me->GetMap()->GetPlayers().getFirst()->GetSource())
{
                            if (GameObject* chest = player->SummonGameObject(RAID_MODE(GO_HORSEMEN_CHEST_10, GO_HORSEMEN_CHEST_25), 2514.8f, -2944.9f, 245.55f, 5.51f, 0, 0, 0, 0, 0))
{
                                chest->SetLootRecipient(me);
                            }
                        }
                    }
                    if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_HORSEMEN_GATE)))
                    {
                        go->SetGoState(GO_STATE_ACTIVE);
                    }
                }
            }
            Talk(SAY_DEATH);
        }
References BOSS_HORSEMAN, DATA_HORSEMEN_GATE, DONE, InstanceScript::GetBossState(), MapRefMgr::getFirst(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), GO_HORSEMEN_CHEST_10, GO_HORSEMEN_CHEST_25, GO_STATE_ACTIVE, LinkedListHead::IsEmpty(), BossAI::JustDied(), ScriptedAI::me, pInstance, ScriptedAI::RAID_MODE(), SAY_DEATH, and WorldObject::SummonGameObject().
JustEngagedWith()
void boss_four_horsemen::boss_four_horsemenAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            BossAI::JustEngagedWith(who);
            if (movementPhase == MOVE_PHASE_NONE)
            {
                Talk(SAY_AGGRO);
                me->SetReactState(REACT_PASSIVE);
                movementPhase = MOVE_PHASE_STARTED;
                me->SetSpeed(MOVE_RUN, me->GetSpeedRate(MOVE_RUN), true);
                MoveToCorner();
            }
            if (pInstance)
            {
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_HORSEMEN_GATE)))
                {
                    go->SetGoState(GO_STATE_READY);
                }
            }
        }
References DATA_HORSEMEN_GATE, Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetSpeedRate(), GO_STATE_READY, BossAI::JustEngagedWith(), ScriptedAI::me, MOVE_PHASE_NONE, MOVE_PHASE_STARTED, MOVE_RUN, movementPhase, MoveToCorner(), pInstance, REACT_PASSIVE, SAY_AGGRO, Creature::SetReactState(), and Unit::SetSpeed().
KilledUnit()
void boss_four_horsemen::boss_four_horsemenAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!who->IsPlayer())
                return;
            Talk(SAY_SLAY);
            if (pInstance)
            {
                pInstance->SetData(DATA_IMMORTAL_FAIL, 0);
            }
        }
References DATA_IMMORTAL_FAIL, Object::IsPlayer(), pInstance, SAY_SLAY, and ZoneScript::SetData().
MovementInform()
void boss_four_horsemen::boss_four_horsemenAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type != POINT_MOTION_TYPE)
                return;
            // final waypoint
            if (id % 3 == 2)
            {
                movementPhase = MOVE_PHASE_FINISHED;
                me->SetReactState(REACT_AGGRESSIVE);
                me->SetInCombatWithZone();
                if (!UpdateVictim())
                {
                    EnterEvadeMode();
                    return;
                }
                if (me->GetEntry() == NPC_LADY_BLAUMEUX || me->GetEntry() == NPC_SIR_ZELIEK)
                {
                    me->GetMotionMaster()->Clear(false);
                    me->GetMotionMaster()->MoveIdle();
                }
                return;
            }
            currentWaypoint = id + 1;
        }
References MotionMaster::Clear(), currentWaypoint, BossAI::EnterEvadeMode(), Object::GetEntry(), Unit::GetMotionMaster(), ScriptedAI::me, MOVE_PHASE_FINISHED, MotionMaster::MoveIdle(), movementPhase, NPC_LADY_BLAUMEUX, NPC_SIR_ZELIEK, POINT_MOTION_TYPE, REACT_AGGRESSIVE, Creature::SetInCombatWithZone(), Creature::SetReactState(), and CreatureAI::UpdateVictim().
MoveToCorner()
void boss_four_horsemen::boss_four_horsemenAI::MoveToCorner () inline
        {
            switch (me->GetEntry())
            {
                case NPC_THANE_KORTHAZZ:
                    currentWaypoint = 0;
                    break;
                case NPC_LADY_BLAUMEUX:
                    currentWaypoint = 3;
                    break;
                case NPC_BARON_RIVENDARE:
                    currentWaypoint = 6;
                    break;
                case NPC_SIR_ZELIEK:
                    currentWaypoint = 9;
                    break;
            }
            me->GetMotionMaster()->MovePoint(currentWaypoint, WaypointPositions[currentWaypoint]);
        }
References currentWaypoint, Object::GetEntry(), Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MovePoint(), NPC_BARON_RIVENDARE, NPC_LADY_BLAUMEUX, NPC_SIR_ZELIEK, NPC_THANE_KORTHAZZ, and WaypointPositions.
Referenced by JustEngagedWith().
Reset()
void boss_four_horsemen::boss_four_horsemenAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            BossAI::Reset();
            me->SetPosition(me->GetHomePosition());
            movementPhase = MOVE_PHASE_NONE;
            currentWaypoint = 0;
            me->SetReactState(REACT_AGGRESSIVE);
            events.Reset();
            events.RescheduleEvent(EVENT_MARK_CAST, 24s);
            events.RescheduleEvent(EVENT_BERSERK, 10min);
            if ((me->GetEntry() != NPC_LADY_BLAUMEUX && me->GetEntry() != NPC_SIR_ZELIEK))
            {
                events.RescheduleEvent(EVENT_PRIMARY_SPELL, 10s, 15s);
            }
            else
            {
                events.RescheduleEvent(EVENT_SECONDARY_SPELL, 15s);
            }
            if (pInstance)
            {
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_HORSEMEN_GATE)))
                {
                    if (pInstance->GetBossState(BOSS_GOTHIK) == DONE)
                    {
                        go->SetGoState(GO_STATE_ACTIVE);
                    }
                }
            }
        }
References BOSS_GOTHIK, currentWaypoint, DATA_HORSEMEN_GATE, DONE, EVENT_BERSERK, EVENT_MARK_CAST, EVENT_PRIMARY_SPELL, EVENT_SECONDARY_SPELL, InstanceScript::GetBossState(), Object::GetEntry(), Map::GetGameObject(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), WorldObject::GetMap(), GO_STATE_ACTIVE, ScriptedAI::me, MOVE_PHASE_NONE, movementPhase, NPC_LADY_BLAUMEUX, NPC_SIR_ZELIEK, pInstance, REACT_AGGRESSIVE, BossAI::Reset(), Creature::SetPosition(), and Creature::SetReactState().
UpdateAI()
void boss_four_horsemen::boss_four_horsemenAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            if (movementPhase == MOVE_PHASE_STARTED && currentWaypoint)
            {
                me->GetMotionMaster()->MovePoint(currentWaypoint, WaypointPositions[currentWaypoint]);
                currentWaypoint = 0;
            }
            if (!IsInRoom())
                return;
            if (movementPhase < MOVE_PHASE_FINISHED || !UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_MARK_CAST:
                    me->CastSpell(me, TABLE_SPELL_MARK[horsemanId], false);
                    events.Repeat((me->GetEntry() == NPC_LADY_BLAUMEUX || me->GetEntry() == NPC_SIR_ZELIEK) ? 15s : 12s);
                    return;
                case EVENT_BERSERK:
                    Talk(SAY_SPECIAL);
                    me->CastSpell(me, SPELL_BERSERK, true);
                    return;
                case EVENT_PRIMARY_SPELL:
                    Talk(SAY_TAUNT);
                    me->CastSpell(me->GetVictim(), RAID_MODE(TABLE_SPELL_PRIMARY_10[horsemanId], TABLE_SPELL_PRIMARY_25[horsemanId]), false);
                    events.Repeat(15s);
                    return;
                case EVENT_SECONDARY_SPELL:
                    me->CastSpell(me->GetVictim(), RAID_MODE(TABLE_SPELL_SECONDARY_10[horsemanId], TABLE_SPELL_SECONDARY_25[horsemanId]), false);
                    events.Repeat(15s);
                    return;
            }
            if (me->GetEntry() == NPC_LADY_BLAUMEUX || me->GetEntry() == NPC_SIR_ZELIEK)
            {
                if (Unit* pTarget = me->SelectNearestPlayer(300.0f))
                {
                    if (pTarget && me->IsValidAttackTarget(pTarget))
                    {
                        AttackStart(pTarget);
                    }
                }
                if (me->IsWithinDistInMap(me->GetVictim(), 45.0f) && me->IsValidAttackTarget(me->GetVictim()))
                {
                    DoCastVictim(RAID_MODE(TABLE_SPELL_PRIMARY_10[horsemanId], TABLE_SPELL_PRIMARY_25[horsemanId]));
                }
                else if (!me->IsWithinDistInMap(me->GetVictim(), 45.0f) || !me->IsValidAttackTarget(me->GetVictim()))
                {
                    DoCastAOE(TABLE_SPELL_PUNISH[horsemanId]);
                    Talk(EMOTE_RAGECAST);
                }
            }
            else
            {
                DoMeleeAttackIfReady();
            }
        }
References AttackStart(), Unit::CastSpell(), currentWaypoint, UnitAI::DoCastAOE(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EMOTE_RAGECAST, EVENT_BERSERK, EVENT_MARK_CAST, EVENT_PRIMARY_SPELL, EVENT_SECONDARY_SPELL, Object::GetEntry(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HasUnitState(), horsemanId, IsInRoom(), Unit::IsValidAttackTarget(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, MOVE_PHASE_FINISHED, MOVE_PHASE_STARTED, movementPhase, MotionMaster::MovePoint(), NPC_LADY_BLAUMEUX, NPC_SIR_ZELIEK, ScriptedAI::RAID_MODE(), SAY_SPECIAL, SAY_TAUNT, WorldObject::SelectNearestPlayer(), SPELL_BERSERK, TABLE_SPELL_MARK, TABLE_SPELL_PRIMARY_10, TABLE_SPELL_PRIMARY_25, TABLE_SPELL_PUNISH, TABLE_SPELL_SECONDARY_10, TABLE_SPELL_SECONDARY_25, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and WaypointPositions.
Member Data Documentation
currentWaypoint
uint8 boss_four_horsemen::boss_four_horsemenAI::currentWaypoint {}
Referenced by MovementInform(), MoveToCorner(), Reset(), and UpdateAI().
events
EventMap boss_four_horsemen::boss_four_horsemenAI::events
horsemanId
uint8 boss_four_horsemen::boss_four_horsemenAI::horsemanId
Referenced by boss_four_horsemenAI(), and UpdateAI().
movementPhase
uint8 boss_four_horsemen::boss_four_horsemenAI::movementPhase {}
Referenced by AttackStart(), JustEngagedWith(), MovementInform(), Reset(), and UpdateAI().
pInstance
InstanceScript* boss_four_horsemen::boss_four_horsemenAI::pInstance
Referenced by boss_four_horsemenAI(), JustDied(), JustEngagedWith(), KilledUnit(), and Reset().