AzerothCore: npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI Struct Reference
npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI Struct Reference
Public Member Functions
npc_ulduar_leviathan_mkiiAI (Creature *pCreature)
void Reset () override
void SetData (uint32 id, uint32 value) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void KilledUnit (Unit *who) override
void EnterEvadeMode (EvadeReason why) override
void PassengerBoarded (Unit *p, int8, bool apply) override
== Fields =======================================
Unit * GetS3 ()
void SpellHit (Unit *, SpellInfo const *spell) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
bool bIsEvading
uint8 Phase
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_ulduar_leviathan_mkiiAI()
npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::npc_ulduar_leviathan_mkiiAI (Creature * pCreature) inline
                                                         : ScriptedAI(pCreature)
        {
            pInstance = me->GetInstanceScript();
            bIsEvading = false;
        }
References bIsEvading, WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
DamageTaken()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (damage >= me->GetHealth() || me->GetHealth() < 15000)
            {
                damage = 0;
                if (me->GetReactState() == REACT_PASSIVE)
                    return;
                me->SetReactState(REACT_PASSIVE);
                if (Phase == 1)
                {
                    if (!me->HasUnitFlag(UNIT_FLAG_NOT_SELECTABLE))
                    {
                        me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        me->GetMotionMaster()->Clear();
                        me->AttackStop();
                        me->SetReactState(REACT_PASSIVE);
                        SetData(1, 0);
                        me->InterruptNonMeleeSpells(false);
                        me->RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE);
                        if (Unit* cannon = GetS3())
                            cannon->ExitVehicle();
                        me->GetMotionMaster()->MoveCharge(2795.076f, 2598.616f, 364.32f, 21.0f);
                        if (Creature* c = GetMimiron())
                            c->AI()->SetData(0, 1);
                    }
                }
                else if (Phase == 4)
                {
                    if (!me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
                    {
                        me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                        me->InterruptNonMeleeSpells(false);
                        me->RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE);
                        me->CastSpell(me, SPELL_SELF_REPAIR, false);
                        if (Creature* c = GetMimiron())
{
                            if (c->AI()->GetData(1))
                                me->CastSpell(me, SPELL_EMERGENCY_MODE, true);
                            if (c->AI()->GetData(2))
                                me->CastSpell(me, SPELL_BERSERK, true);
                            c->AI()->SetData(0, 4);
                        }
                    }
                }
            }
        }
References Unit::AttackStop(), Unit::CastSpell(), MotionMaster::Clear(), Unit::GetHealth(), GetMimiron, Unit::GetMotionMaster(), Creature::GetReactState(), GetS3(), Unit::HasUnitFlag(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, MotionMaster::MoveCharge(), REACT_PASSIVE, Unit::RemoveAllAurasExceptType(), SetData(), Creature::SetReactState(), Unit::SetUnitFlag(), SPELL_AURA_CONTROL_VEHICLE, SPELL_BERSERK, SPELL_EMERGENCY_MODE, SPELL_SELF_REPAIR, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
EnterEvadeMode()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            if (bIsEvading)
                return;
            bIsEvading = true;
            me->RemoveAllAuras();
            me->ExitVehicle();
            ScriptedAI::EnterEvadeMode();
            if (Creature* mimiron = GetMimiron())
                mimiron->AI()->EnterEvadeMode(why);
            bIsEvading = false;
        }
References bIsEvading, CreatureAI::EnterEvadeMode(), Unit::ExitVehicle(), GetMimiron, ScriptedAI::me, and Unit::RemoveAllAuras().
GetS3()
Unit * npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::GetS3 () inline
        {
            if (Vehicle* vk = me->GetVehicleKit())
                if (Unit* cannon = vk->GetPassenger(3))
                    return cannon;
            return 0;
        }
References Unit::GetVehicleKit(), and ScriptedAI::me.
Referenced by DamageTaken(), Reset(), and UpdateAI().
KilledUnit()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (who->IsPlayer())
                if (Creature* c = GetMimiron())
                {
                    if (Phase == 1)
                    {
                        c->AI()->Talk(SAY_MKII_SLAY);
                    }
                    else
                    {
                        c->AI()->Talk(SAY_V07TRON_SLAY);
                    }
                }
        }
References GetMimiron, Object::IsPlayer(), SAY_MKII_SLAY, and SAY_V07TRON_SLAY.
MoveInLineOfSight()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{}
PassengerBoarded()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
        {
            if (p->GetEntry() == NPC_LEVIATHAN_MKII_CANNON && !apply)
            {
                Unit::Kill(p, p);
                p->ToCreature()->DespawnOrUnsummon(6000);
            }
        }
References Creature::DespawnOrUnsummon(), Object::GetEntry(), Unit::Kill(), NPC_LEVIATHAN_MKII_CANNON, and Object::ToCreature().
Reset()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            Phase = 0;
            if (Unit* c = GetS3())
                c->ExitVehicle(); // this should never happen!
            if (Creature* c = me->SummonCreature(NPC_LEVIATHAN_MKII_CANNON, *me, TEMPSUMMON_MANUAL_DESPAWN))
                c->EnterVehicle(me, 3);
            me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            me->SetReactState(REACT_AGGRESSIVE);
            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
            events.Reset();
        }
References EMOTE_ONESHOT_NONE, GetS3(), ScriptedAI::me, NPC_LEVIATHAN_MKII_CANNON, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Creature::SetReactState(), Unit::SetUInt32Value(), Unit::SetUnitFlag(), WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and UNIT_NPC_EMOTESTATE.
SetData()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::SetData (uint32 id, uint32 value) inline override virtual
Reimplemented from UnitAI.
        {
            if (id == 1) // setting phase to start fighting
            {
                switch (value)
                {
                    case 0:
                        Phase = 0;
                        events.Reset();
                        break;
                    case 1:
                        Phase = 1;
                        me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        if (Unit* target = SelectTargetFromPlayerList(75.0f))
                            AttackStart(target);
                        DoZoneInCombat();
                        events.Reset();
                        events.ScheduleEvent(EVENT_SPELL_NAPALM_SHELL, 3s);
                        events.ScheduleEvent(EVENT_SPELL_PLASMA_BLAST, 10s);
                        events.ScheduleEvent(EVENT_SPELL_SHOCK_BLAST, 20s);
                        events.ScheduleEvent(EVENT_PROXIMITY_MINES_1, 6s);
                        if (Creature* c = GetMimiron())
                            if (c->AI()->GetData(1))
                                events.ScheduleEvent(EVENT_FLAME_SUPPRESSION_50000, 60s);
                        break;
                    case 4:
                        me->SetReactState(REACT_AGGRESSIVE);
                        DoResetThreatList();
                        Phase = 4;
                        me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        if (Unit* target = SelectTargetFromPlayerList(75.0f))
                            AttackStart(target);
                        DoZoneInCombat();
                        events.Reset();
                        events.ScheduleEvent(EVENT_SPELL_SHOCK_BLAST, 20s);
                        events.ScheduleEvent(EVENT_PROXIMITY_MINES_1, 6s);
                        break;
                }
            }
        }
References ScriptedAI::AttackStart(), ScriptedAI::DoResetThreatList(), CreatureAI::DoZoneInCombat(), EVENT_FLAME_SUPPRESSION_50000, EVENT_PROXIMITY_MINES_1, EVENT_SPELL_NAPALM_SHELL, EVENT_SPELL_PLASMA_BLAST, EVENT_SPELL_SHOCK_BLAST, GetMimiron, ScriptedAI::me, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), ScriptedAI::SelectTargetFromPlayerList(), Creature::SetReactState(), and UNIT_FLAG_NOT_SELECTABLE.
Referenced by DamageTaken().
SpellHit()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spell->Id == SPELL_SELF_REPAIR)
            {
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->SetReactState(REACT_AGGRESSIVE);
            }
        }
References SpellInfo::Id, ScriptedAI::me, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Creature::SetReactState(), SPELL_SELF_REPAIR, and UNIT_FLAG_NON_ATTACKABLE.
UpdateAI()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (!me->HasUnitState(UNIT_STATE_CASTING))
                DoMeleeAttackIfReady();
            Unit* cannon = GetS3();
            if (!cannon || cannon->HasUnitState(UNIT_STATE_CASTING) || me->HasUnitState(UNIT_STATE_CASTING) || me->HasSilenceAura())
                return;
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_SPELL_NAPALM_SHELL:
                    {
                        Player* pTarget = nullptr;
                        std::vector<Player*> pList;
                        Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                        for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                            if (Player* plr = itr->GetSource())
                                if (plr->IsAlive() && plr->GetDistance2d(me) > 15.0f )
                                    pList.push_back(plr);
                        if (!pList.empty())
                            pTarget = pList[urand(0, pList.size() - 1)];
                        else
                            pTarget = (Player*)SelectTarget(SelectTargetMethod::Random, 0, 100.0f, true);
                        if (pTarget)
                            cannon->CastSpell(pTarget, SPELL_NAPALM_SHELL, false);
                        events.Repeat(14s);
                    }
                    break;
                case EVENT_SPELL_PLASMA_BLAST:
                    if (Unit* victim = me->GetVictim())
                    {
                        Talk(EMOTE_PLASMA_BLAST);
                        cannon->CastSpell(victim, SPELL_PLASMA_BLAST, false);
                    }
                    events.Repeat(22s);
                    break;
                case EVENT_SPELL_SHOCK_BLAST:
                    me->CastSpell(me->GetVictim(), SPELL_SHOCK_BLAST, false);
                    events.Repeat(30s);
                    events.ScheduleEvent(EVENT_PROXIMITY_MINES_1, 8s);
                    break;
                case EVENT_PROXIMITY_MINES_1:
                    for (uint8 i = 0; i < 10; ++i)
                    {
                        me->CastSpell(me, SPELL_SUMMON_PROXIMITY_MINE, true);
                    }
                    break;
                case EVENT_FLAME_SUPPRESSION_50000:
                    me->CastSpell(me, SPELL_FLAME_SUPPRESSANT_50000yd, false);
                    break;
            }
        }
References MapRefMgr::begin(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EMOTE_PLASMA_BLAST, MapRefMgr::end(), EVENT_FLAME_SUPPRESSION_50000, EVENT_PROXIMITY_MINES_1, EVENT_SPELL_NAPALM_SHELL, EVENT_SPELL_PLASMA_BLAST, EVENT_SPELL_SHOCK_BLAST, WorldObject::GetMap(), Map::GetPlayers(), GetS3(), Unit::GetVictim(), Unit::HasSilenceAura(), Unit::HasUnitState(), ScriptedAI::me, UnitAI::SelectTarget(), SPELL_FLAME_SUPPRESSANT_50000yd, SPELL_NAPALM_SHELL, SPELL_PLASMA_BLAST, SPELL_SHOCK_BLAST, SPELL_SUMMON_PROXIMITY_MINE, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
bIsEvading
bool npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::bIsEvading
Referenced by EnterEvadeMode(), and npc_ulduar_leviathan_mkiiAI().
events
EventMap npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::events
Phase
uint8 npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::Phase
pInstance
InstanceScript* npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::pInstance
Referenced by npc_ulduar_leviathan_mkiiAI().