AzerothCore: instance_zulgurub::instance_zulgurub_InstanceMapScript Struct Reference
instance_zulgurub::instance_zulgurub_InstanceMapScript Struct Reference
Public Member Functions
instance_zulgurub_InstanceMapScript (Map *map)
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
ObjectGuid GetGuidData (uint32 uiData) const override
uint32 GetData (uint32 type) const override
void RemoveHakkarPowerStack ()
bool SetBossState (uint32 type, EncounterState state) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid _jindoTheHexxerGUID
ObjectGuid _vilebranchSpeakerGUID
ObjectGuid _arlokkGUID
ObjectGuid _goGongOfBethekkGUID
ObjectGuid _hakkarGUID
ObjectGuid _gahzrankaGUID
ObjectGuid _edgeOfMadnessGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_zulgurub_InstanceMapScript()
instance_zulgurub::instance_zulgurub_InstanceMapScript::instance_zulgurub_InstanceMapScript (Map * map) inline
                                                      : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(EncounterCount);
            LoadDoorData(doorData);
            LoadObjectData(creatureData, nullptr);
        }
References creatureData, DataHeader, doorData, EncounterCount, InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
GetData()
uint32 instance_zulgurub::instance_zulgurub_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == DATA_GAHZRANKA)
            {
                return _gahzrankaGUID || GetBossState(DATA_GAHZRANKA) == DONE;
            }
            return 0;
        }
References _gahzrankaGUID, DATA_GAHZRANKA, DONE, and InstanceScript::GetBossState().
GetGuidData()
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::GetGuidData (uint32 uiData) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (uiData)
            {
                case DATA_JINDO:
                    return _jindoTheHexxerGUID;
                case NPC_ARLOKK:
                    return _arlokkGUID;
                case GO_GONG_OF_BETHEKK:
                    return _goGongOfBethekkGUID;
                case DATA_HAKKAR:
                    return _hakkarGUID;
                case DATA_EDGE_OF_MADNESS:
                    return _edgeOfMadnessGUID;
            }
            return ObjectGuid::Empty;
        }
References _arlokkGUID, _edgeOfMadnessGUID, _goGongOfBethekkGUID, _hakkarGUID, _jindoTheHexxerGUID, DATA_EDGE_OF_MADNESS, DATA_HAKKAR, DATA_JINDO, ObjectGuid::Empty, GO_GONG_OF_BETHEKK, and NPC_ARLOKK.
OnCreatureCreate()
void instance_zulgurub::instance_zulgurub_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            InstanceScript::OnCreatureCreate(creature);
            switch (creature->GetEntry())
            {
                case NPC_JINDO_THE_HEXXER:
                    _jindoTheHexxerGUID = creature->GetGUID();
                    break;
                case NPC_VILEBRANCH_SPEAKER:
                    _vilebranchSpeakerGUID = creature->GetGUID();
                    break;
                case NPC_ARLOKK:
                    _arlokkGUID = creature->GetGUID();
                    break;
                case NPC_HAKKAR:
                    _hakkarGUID = creature->GetGUID();
                    break;
                case NPC_SPAWN_OF_MARLI:
                    if (Creature* marli = GetCreature(DATA_MARLI))
                    {
                        marli->AI()->JustSummoned(creature);
                    }
                    break;
                case NPC_GAHZRANKA:
                    _gahzrankaGUID = creature->GetGUID();
                    break;
                case NPC_GRILEK:
                case NPC_HAZZARAH:
                case NPC_RENATAKI:
                case NPC_WUSHOOLAY:
                    _edgeOfMadnessGUID = creature->GetGUID();
                    break;
                default:
                    break;
            }
        }
References _arlokkGUID, _edgeOfMadnessGUID, _gahzrankaGUID, _hakkarGUID, _jindoTheHexxerGUID, _vilebranchSpeakerGUID, DATA_MARLI, InstanceScript::GetCreature(), Object::GetEntry(), Object::GetGUID(), NPC_ARLOKK, NPC_GAHZRANKA, NPC_GRILEK, NPC_HAKKAR, NPC_HAZZARAH, NPC_JINDO_THE_HEXXER, NPC_RENATAKI, NPC_SPAWN_OF_MARLI, NPC_VILEBRANCH_SPEAKER, NPC_WUSHOOLAY, and InstanceScript::OnCreatureCreate().
OnGameObjectCreate()
void instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            InstanceScript::OnGameObjectCreate(go);
            switch (go->GetEntry())
            {
                case GO_GONG_OF_BETHEKK:
                    _goGongOfBethekkGUID = go->GetGUID();
                    if (GetBossState(DATA_ARLOKK) == DONE)
                        go->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    else
                        go->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    break;
                default:
                    break;
            }
        }
References _goGongOfBethekkGUID, DATA_ARLOKK, DONE, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_FLAG_NOT_SELECTABLE, GO_GONG_OF_BETHEKK, InstanceScript::OnGameObjectCreate(), GameObject::RemoveGameObjectFlag(), and GameObject::SetGameObjectFlag().
RemoveHakkarPowerStack()
void instance_zulgurub::instance_zulgurub_InstanceMapScript::RemoveHakkarPowerStack () inline
        {
            if (Creature* hakkar = instance->GetCreature(_hakkarGUID))
            {
                hakkar->CastSpell(hakkar, SPELL_HAKKAR_POWER_DOWN, true);
            }
        }
References _hakkarGUID, Map::GetCreature(), InstanceScript::instance, and SPELL_HAKKAR_POWER_DOWN.
Referenced by SetBossState().
SetBossState()
bool instance_zulgurub::instance_zulgurub_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            switch (type)
            {
                case DATA_JEKLIK:
                case DATA_VENOXIS:
                case DATA_MARLI:
                case DATA_ARLOKK:
                case DATA_THEKAL:
                    if (state == DONE)
                        RemoveHakkarPowerStack();
                    break;
                default:
                    break;
            }
            return true;
        }
References DATA_ARLOKK, DATA_JEKLIK, DATA_MARLI, DATA_THEKAL, DATA_VENOXIS, DONE, RemoveHakkarPowerStack(), and InstanceScript::SetBossState().
Member Data Documentation
_arlokkGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_arlokkGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
_edgeOfMadnessGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_edgeOfMadnessGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
_gahzrankaGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_gahzrankaGUID private
Referenced by GetData(), and OnCreatureCreate().
_goGongOfBethekkGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_goGongOfBethekkGUID private
Referenced by GetGuidData(), and OnGameObjectCreate().
_hakkarGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_hakkarGUID private
Referenced by GetGuidData(), OnCreatureCreate(), and RemoveHakkarPowerStack().
_jindoTheHexxerGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_jindoTheHexxerGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
_vilebranchSpeakerGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_vilebranchSpeakerGUID private
Referenced by OnCreatureCreate().