AzerothCore: ArenaScore Struct Reference
ArenaScore Struct Reference
#include "ArenaScore.h"
Protected Member Functions
ArenaScore (ObjectGuid playerGuid, TeamId team)
void AppendToPacket (WorldPacket &data) final
void BuildObjectivesBlock (WorldPacket &data) final
std::string ToString () const override
Protected Member Functions inherited from BattlegroundScore
BattlegroundScore (ObjectGuid playerGuid)
virtual ~BattlegroundScore ()=default
virtual void UpdateScore (uint32 type, uint32 value)
virtual void AppendToPacket (WorldPacket &data)
virtual void BuildObjectivesBlock (WorldPacket &)=0
virtual std::string ToString () const
uint32 GetKillingBlows () const
uint32 GetDeaths () const
uint32 GetHonorableKills () const
uint32 GetBonusHonor () const
uint32 GetDamageDone () const
uint32 GetHealingDone () const
virtual uint32 GetAttr1 () const
virtual uint32 GetAttr2 () const
virtual uint32 GetAttr3 () const
virtual uint32 GetAttr4 () const
virtual uint32 GetAttr5 () const
Protected Attributes
uint8 PvPTeamId
Protected Attributes inherited from BattlegroundScore
ObjectGuid PlayerGuid
uint32 KillingBlows = 0
uint32 Deaths = 0
uint32 HonorableKills = 0
uint32 BonusHonor = 0
uint32 DamageDone = 0
uint32 HealingDone = 0
Friends
class Arena
Detailed Description
Constructor & Destructor Documentation
ArenaScore()
ArenaScore::ArenaScore (ObjectGuid playerGuid, TeamId team) inline protected
                                                   :
        BattlegroundScore(playerGuid), PvPTeamId(team == TEAM_ALLIANCE ? PVP_TEAM_ALLIANCE : PVP_TEAM_HORDE) { }
Member Function Documentation
AppendToPacket()
void ArenaScore::AppendToPacket (WorldPacket & data) final protected virtual
Reimplemented from BattlegroundScore.
{
    data << PlayerGuid;
    data << uint32(KillingBlows);
    data << uint8(PvPTeamId);
    data << uint32(DamageDone);
    data << uint32(HealingDone);
    BuildObjectivesBlock(data);
}
References BuildObjectivesBlock(), BattlegroundScore::DamageDone, BattlegroundScore::HealingDone, BattlegroundScore::KillingBlows, and BattlegroundScore::PlayerGuid.
BuildObjectivesBlock()
void ArenaScore::BuildObjectivesBlock (WorldPacket & data) final protected virtual
Implements BattlegroundScore.
{
    data << uint32(0); // Objectives Count
}
Referenced by AppendToPacket().
ToString()
std::string ArenaScore::ToString () const inline override protected virtual
Reimplemented from BattlegroundScore.
    {
        return Acore::StringFormat("Damage done: {}, Healing done: {}, Killing blows: {}", DamageDone, HealingDone, KillingBlows);
    }
References Acore::StringFormat().
Friends And Related Function Documentation
Arena
friend class Arena friend
Member Data Documentation
PvPTeamId
uint8 ArenaScore::PvPTeamId protected