AzerothCore: disable_commandscript Class Reference
disable_commandscript Class Reference
Public Member Functions
disable_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleAddDisables (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment, uint8 disableType)
static bool HandleAddDisableSpellCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableQuestCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableMapCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableBattlegroundCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableAchievementCriteriaCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableOutdoorPvPCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableVmapCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleRemoveDisables (ChatHandler *handler, uint32 entry, uint8 disableType)
static bool HandleRemoveDisableSpellCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableQuestCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableMapCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableBattlegroundCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableAchievementCriteriaCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableOutdoorPvPCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableVmapCommand (ChatHandler *handler, uint32 entry)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
disable_commandscript()
disable_commandscript::disable_commandscript () inline
: CommandScript("disable_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable disable_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable removeDisableCommandTable =
        {
            { "spell",        HandleRemoveDisableSpellCommand,        SEC_ADMINISTRATOR, Console::Yes },
            { "quest",        HandleRemoveDisableQuestCommand,        SEC_ADMINISTRATOR, Console::Yes },
            { "map",          HandleRemoveDisableMapCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "battleground", HandleRemoveDisableBattlegroundCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "outdoorpvp",   HandleRemoveDisableOutdoorPvPCommand,   SEC_ADMINISTRATOR, Console::Yes },
            { "vmap",         HandleRemoveDisableVmapCommand,         SEC_ADMINISTRATOR, Console::Yes }
        };
        static ChatCommandTable addDisableCommandTable =
        {
            { "spell",        HandleAddDisableSpellCommand,           SEC_ADMINISTRATOR, Console::Yes },
            { "quest",        HandleAddDisableQuestCommand,           SEC_ADMINISTRATOR, Console::Yes },
            { "map",          HandleAddDisableMapCommand,             SEC_ADMINISTRATOR, Console::Yes },
            { "battleground", HandleAddDisableBattlegroundCommand,    SEC_ADMINISTRATOR, Console::Yes },
            { "outdoorpvp",   HandleAddDisableOutdoorPvPCommand,      SEC_ADMINISTRATOR, Console::Yes },
            { "vmap",         HandleAddDisableVmapCommand,            SEC_ADMINISTRATOR, Console::Yes }
        };
        static ChatCommandTable disableCommandTable =
        {
            { "add",    addDisableCommandTable },
            { "remove", removeDisableCommandTable }
        };
        static ChatCommandTable commandTable =
        {
            { "disable", disableCommandTable }
        };
        return commandTable;
    }
References HandleAddDisableBattlegroundCommand(), HandleAddDisableMapCommand(), HandleAddDisableOutdoorPvPCommand(), HandleAddDisableQuestCommand(), HandleAddDisableSpellCommand(), HandleAddDisableVmapCommand(), HandleRemoveDisableBattlegroundCommand(), HandleRemoveDisableMapCommand(), HandleRemoveDisableOutdoorPvPCommand(), HandleRemoveDisableQuestCommand(), HandleRemoveDisableSpellCommand(), HandleRemoveDisableVmapCommand(), and SEC_ADMINISTRATOR.
HandleAddDisableAchievementCriteriaCommand()
static bool disable_commandscript::HandleAddDisableAchievementCriteriaCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
    {
        return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_ACHIEVEMENT_CRITERIA);
    }
References DISABLE_TYPE_ACHIEVEMENT_CRITERIA, and HandleAddDisables().
HandleAddDisableBattlegroundCommand()
static bool disable_commandscript::HandleAddDisableBattlegroundCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
    {
        return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_BATTLEGROUND);
    }
References DISABLE_TYPE_BATTLEGROUND, and HandleAddDisables().
Referenced by GetCommands().
HandleAddDisableMapCommand()
static bool disable_commandscript::HandleAddDisableMapCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
    {
        return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_MAP);
    }
References DISABLE_TYPE_MAP, and HandleAddDisables().
Referenced by GetCommands().
HandleAddDisableOutdoorPvPCommand()
static bool disable_commandscript::HandleAddDisableOutdoorPvPCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
    {
        HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_OUTDOORPVP);
        return true;
    }
References DISABLE_TYPE_OUTDOORPVP, and HandleAddDisables().
Referenced by GetCommands().
HandleAddDisableQuestCommand()
static bool disable_commandscript::HandleAddDisableQuestCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
    {
        return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_QUEST);
    }
References DISABLE_TYPE_QUEST, and HandleAddDisables().
Referenced by GetCommands().
HandleAddDisables()
static bool disable_commandscript::HandleAddDisables (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment, uint8 disableType) inline static
    {
        std::string disableTypeStr = "";
        switch (disableType)
        {
            case DISABLE_TYPE_SPELL:
                {
                    if (!sSpellMgr->GetSpellInfo(entry))
                    {
                        handler->SendErrorMessage(LANG_COMMAND_NOSPELLFOUND);
                        return false;
                    }
                    disableTypeStr = "spell";
                    break;
                }
            case DISABLE_TYPE_QUEST:
                {
                    if (!sObjectMgr->GetQuestTemplate(entry))
                    {
                        handler->SendErrorMessage(LANG_COMMAND_QUEST_NOTFOUND, entry);
                        return false;
                    }
                    disableTypeStr = "quest";
                    break;
                }
            case DISABLE_TYPE_MAP:
                {
                    if (!sMapStore.LookupEntry(entry))
                    {
                        handler->SendErrorMessage(LANG_COMMAND_NOMAPFOUND);
                        return false;
                    }
                    disableTypeStr = "map";
                    break;
                }
            case DISABLE_TYPE_BATTLEGROUND:
                {
                    if (!sBattlemasterListStore.LookupEntry(entry))
                    {
                        handler->SendErrorMessage(LANG_COMMAND_NO_BATTLEGROUND_FOUND);
                        return false;
                    }
                    disableTypeStr = "battleground";
                    break;
                }
            case DISABLE_TYPE_OUTDOORPVP:
                {
                    if (entry > MAX_OUTDOORPVP_TYPES)
                    {
                        handler->SendErrorMessage(LANG_COMMAND_NO_OUTDOOR_PVP_FORUND);
                        return false;
                    }
                    disableTypeStr = "outdoorpvp";
                    break;
                }
            case DISABLE_TYPE_VMAP:
                {
                    if (!sMapStore.LookupEntry(entry))
                    {
                        handler->SendErrorMessage(LANG_COMMAND_NOMAPFOUND);
                        return false;
                    }
                    disableTypeStr = "vmap";
                    break;
                }
            default:
                break;
        }
        WorldDatabasePreparedStatement* stmt = nullptr;
        stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_DISABLES);
        stmt->SetData(0, entry);
        stmt->SetData(1, disableType);
        PreparedQueryResult result = WorldDatabase.Query(stmt);
        if (result)
        {
            handler->SendErrorMessage("This {} (Id: {}) is already disabled.", disableTypeStr, entry);
            return false;
        }
        stmt = WorldDatabase.GetPreparedStatement(WORLD_INS_DISABLES);
        stmt->SetData(0, entry);
        stmt->SetData(1, disableType);
        stmt->SetData(2, flags);
        stmt->SetData(3, disableComment);
        WorldDatabase.Execute(stmt);
        handler->PSendSysMessage("Add Disabled {} (Id: {}) for reason {}", disableTypeStr, entry, disableComment);
        return true;
    }
References DISABLE_TYPE_BATTLEGROUND, DISABLE_TYPE_MAP, DISABLE_TYPE_OUTDOORPVP, DISABLE_TYPE_QUEST, DISABLE_TYPE_SPELL, DISABLE_TYPE_VMAP, LANG_COMMAND_NO_BATTLEGROUND_FOUND, LANG_COMMAND_NO_OUTDOOR_PVP_FORUND, LANG_COMMAND_NOMAPFOUND, LANG_COMMAND_NOSPELLFOUND, LANG_COMMAND_QUEST_NOTFOUND, MAX_OUTDOORPVP_TYPES, ChatHandler::PSendSysMessage(), sBattlemasterListStore, ChatHandler::SendErrorMessage(), PreparedStatementBase::SetData(), sMapStore, sObjectMgr, sSpellMgr, WORLD_INS_DISABLES, WORLD_SEL_DISABLES, and WorldDatabase.
Referenced by HandleAddDisableAchievementCriteriaCommand(), HandleAddDisableBattlegroundCommand(), HandleAddDisableMapCommand(), HandleAddDisableOutdoorPvPCommand(), HandleAddDisableQuestCommand(), HandleAddDisableSpellCommand(), and HandleAddDisableVmapCommand().
HandleAddDisableSpellCommand()
static bool disable_commandscript::HandleAddDisableSpellCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
    {
        return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_SPELL);
    }
References DISABLE_TYPE_SPELL, and HandleAddDisables().
Referenced by GetCommands().
HandleAddDisableVmapCommand()
static bool disable_commandscript::HandleAddDisableVmapCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
    {
        return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_VMAP);
    }
References DISABLE_TYPE_VMAP, and HandleAddDisables().
Referenced by GetCommands().
HandleRemoveDisableAchievementCriteriaCommand()
static bool disable_commandscript::HandleRemoveDisableAchievementCriteriaCommand (ChatHandler * handler, uint32 entry) inline static
    {
        return HandleRemoveDisables(handler, entry, DISABLE_TYPE_ACHIEVEMENT_CRITERIA);
    }
References DISABLE_TYPE_ACHIEVEMENT_CRITERIA, and HandleRemoveDisables().
HandleRemoveDisableBattlegroundCommand()
static bool disable_commandscript::HandleRemoveDisableBattlegroundCommand (ChatHandler * handler, uint32 entry) inline static
    {
        return HandleRemoveDisables(handler, entry, DISABLE_TYPE_BATTLEGROUND);
    }
References DISABLE_TYPE_BATTLEGROUND, and HandleRemoveDisables().
Referenced by GetCommands().
HandleRemoveDisableMapCommand()
static bool disable_commandscript::HandleRemoveDisableMapCommand (ChatHandler * handler, uint32 entry) inline static
    {
        return HandleRemoveDisables(handler, entry, DISABLE_TYPE_MAP);
    }
References DISABLE_TYPE_MAP, and HandleRemoveDisables().
Referenced by GetCommands().
HandleRemoveDisableOutdoorPvPCommand()
static bool disable_commandscript::HandleRemoveDisableOutdoorPvPCommand (ChatHandler * handler, uint32 entry) inline static
    {
        return HandleRemoveDisables(handler, entry, DISABLE_TYPE_OUTDOORPVP);
    }
References DISABLE_TYPE_OUTDOORPVP, and HandleRemoveDisables().
Referenced by GetCommands().
HandleRemoveDisableQuestCommand()
static bool disable_commandscript::HandleRemoveDisableQuestCommand (ChatHandler * handler, uint32 entry) inline static
    {
        return HandleRemoveDisables(handler, entry, DISABLE_TYPE_QUEST);
    }
References DISABLE_TYPE_QUEST, and HandleRemoveDisables().
Referenced by GetCommands().
HandleRemoveDisables()
static bool disable_commandscript::HandleRemoveDisables (ChatHandler * handler, uint32 entry, uint8 disableType) inline static
    {
        std::string disableTypeStr = "";
        switch (disableType)
        {
            case DISABLE_TYPE_SPELL:
                disableTypeStr = "spell";
                break;
            case DISABLE_TYPE_QUEST:
                disableTypeStr = "quest";
                break;
            case DISABLE_TYPE_MAP:
                disableTypeStr = "map";
                break;
            case DISABLE_TYPE_BATTLEGROUND:
                disableTypeStr = "battleground";
                break;
            case DISABLE_TYPE_ACHIEVEMENT_CRITERIA:
                disableTypeStr = "achievement criteria";
                break;
            case DISABLE_TYPE_OUTDOORPVP:
                disableTypeStr = "outdoorpvp";
                break;
            case DISABLE_TYPE_VMAP:
                disableTypeStr = "vmap";
                break;
        }
        WorldDatabasePreparedStatement* stmt = nullptr;
        stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_DISABLES);
        stmt->SetData(0, entry);
        stmt->SetData(1, disableType);
        PreparedQueryResult result = WorldDatabase.Query(stmt);
        if (!result)
        {
            handler->SendErrorMessage("This {} (Id: {}) is not disabled.", disableTypeStr, entry);
            return false;
        }
        stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_DISABLES);
        stmt->SetData(0, entry);
        stmt->SetData(1, disableType);
        WorldDatabase.Execute(stmt);
        handler->PSendSysMessage("Remove Disabled {} (Id: {})", disableTypeStr, entry);
        return true;
    }
References DISABLE_TYPE_ACHIEVEMENT_CRITERIA, DISABLE_TYPE_BATTLEGROUND, DISABLE_TYPE_MAP, DISABLE_TYPE_OUTDOORPVP, DISABLE_TYPE_QUEST, DISABLE_TYPE_SPELL, DISABLE_TYPE_VMAP, ChatHandler::PSendSysMessage(), ChatHandler::SendErrorMessage(), PreparedStatementBase::SetData(), WORLD_DEL_DISABLES, WORLD_SEL_DISABLES, and WorldDatabase.
Referenced by HandleRemoveDisableAchievementCriteriaCommand(), HandleRemoveDisableBattlegroundCommand(), HandleRemoveDisableMapCommand(), HandleRemoveDisableOutdoorPvPCommand(), HandleRemoveDisableQuestCommand(), HandleRemoveDisableSpellCommand(), and HandleRemoveDisableVmapCommand().
HandleRemoveDisableSpellCommand()
static bool disable_commandscript::HandleRemoveDisableSpellCommand (ChatHandler * handler, uint32 entry) inline static
    {
        return HandleRemoveDisables(handler, entry, DISABLE_TYPE_SPELL);
    }
References DISABLE_TYPE_SPELL, and HandleRemoveDisables().
Referenced by GetCommands().
HandleRemoveDisableVmapCommand()
static bool disable_commandscript::HandleRemoveDisableVmapCommand (ChatHandler * handler, uint32 entry) inline static
    {
        return HandleRemoveDisables(handler, entry, DISABLE_TYPE_VMAP);
    }
References DISABLE_TYPE_VMAP, and HandleRemoveDisables().
Referenced by GetCommands().