AzerothCore: NecroticPlagueTargetCheck Class Reference
NecroticPlagueTargetCheck Class Reference
Public Member Functions
NecroticPlagueTargetCheck (Unit const *obj, uint32 notAura1, uint32 notAura2)
bool operator() (Unit *unit) const
Private Attributes
Unit const * _sourceObj
uint32 _notAura1
uint32 _notAura2
Detailed Description
Constructor & Destructor Documentation
NecroticPlagueTargetCheck()
NecroticPlagueTargetCheck::NecroticPlagueTargetCheck (Unit const * obj, uint32 notAura1, uint32 notAura2) inline
: _sourceObj(obj), _notAura1(notAura1), _notAura2(notAura2) {}
Member Function Documentation
operator()()
bool NecroticPlagueTargetCheck::operator() (Unit * unit) const inline
    {
        if (!unit || !unit->IsPlayer() || unit == _sourceObj || _sourceObj->GetVictim() == unit || !unit->isTargetableForAttack())
            return false;
        if (unit->HasAura(SPELL_PLAGUE_AVOIDANCE) || unit->HasAura(SPELL_BOSS_HITTIN_YA_AURA) || unit->HasAura(_notAura1) || unit->HasAura(_notAura2))
            return false;
        if (!_sourceObj->IsWithinLOSInMap(unit))
            return false;
        return true;
    }
References _notAura1, _notAura2, _sourceObj, Unit::GetVictim(), Unit::HasAura(), Object::IsPlayer(), Unit::isTargetableForAttack(), WorldObject::IsWithinLOSInMap(), SPELL_BOSS_HITTIN_YA_AURA, and SPELL_PLAGUE_AVOIDANCE.
Member Data Documentation
_notAura1
uint32 NecroticPlagueTargetCheck::_notAura1 private
Referenced by operator()().
_notAura2
uint32 NecroticPlagueTargetCheck::_notAura2 private
Referenced by operator()().
_sourceObj
Unit const* NecroticPlagueTargetCheck::_sourceObj private
Referenced by operator()().