AzeorthCore: SpellScript Class Reference
SpellScript Class Reference
#include "SpellScript.h"
Classes
class BeforeHitHandler
class CastHandler
class CheckCastHandler
class DestinationTargetSelectHandler
class EffectHandler
class HitHandler
class ObjectAreaTargetSelectHandler
class ObjectTargetSelectHandler
class TargetHook
Public Member Functions
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Public Attributes
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Private Attributes
Spell * m_spell
uint8 m_hitPreventEffectMask
uint8 m_hitPreventDefaultEffectMask
Additional Inherited Members
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
_FinishScriptCall()
void SpellScript::_FinishScriptCall ()
{
    m_currentScriptState = SPELL_SCRIPT_STATE_NONE;
}
References _SpellScript::m_currentScriptState, and SPELL_SCRIPT_STATE_NONE.
Referenced by _Load().
_InitHit()
void SpellScript::_InitHit ()
{
    m_hitPreventEffectMask = 0;
    m_hitPreventDefaultEffectMask = 0;
}
References m_hitPreventDefaultEffectMask, and m_hitPreventEffectMask.
_IsDefaultEffectPrevented()
bool SpellScript::_IsDefaultEffectPrevented (SpellEffIndex effIndex) inline
{ return m_hitPreventDefaultEffectMask & (1 << effIndex); }
References m_hitPreventDefaultEffectMask.
_IsEffectPrevented()
bool SpellScript::_IsEffectPrevented (SpellEffIndex effIndex) inline
{ return m_hitPreventEffectMask & (1 << effIndex); }
References m_hitPreventEffectMask.
_Load()
bool SpellScript::_Load (Spell * spell)
{
    m_spell = spell;
    _PrepareScriptCall((SpellScriptHookType)SPELL_SCRIPT_STATE_LOADING);
    bool load = Load();
    _FinishScriptCall();
    return load;
}
References _FinishScriptCall(), _PrepareScriptCall(), _SpellScript::Load(), m_spell, and SPELL_SCRIPT_STATE_LOADING.
_PrepareScriptCall()
void SpellScript::_PrepareScriptCall (SpellScriptHookType hookType)
{
    m_currentScriptState = hookType;
}
References _SpellScript::m_currentScriptState.
Referenced by _Load().
_Validate()
bool SpellScript::_Validate (SpellInfo const * entry) override virtual
Reimplemented from _SpellScript.
{
    for (std::list<EffectHandler>::iterator itr = OnEffectLaunch.begin(); itr != OnEffectLaunch.end(); ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectLaunch` of SpellScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectHandler>::iterator itr = OnEffectLaunchTarget.begin(); itr != OnEffectLaunchTarget.end(); ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectLaunchTarget` of SpellScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectHandler>::iterator itr = OnEffectHit.begin(); itr != OnEffectHit.end(); ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectHit` of SpellScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectHandler>::iterator itr = OnEffectHitTarget.begin(); itr != OnEffectHitTarget.end(); ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<ObjectAreaTargetSelectHandler>::iterator itr = OnObjectAreaTargetSelect.begin(); itr != OnObjectAreaTargetSelect.end(); ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<ObjectTargetSelectHandler>::iterator itr = OnObjectTargetSelect.begin(); itr != OnObjectTargetSelect.end(); ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnObjectTargetSelect` of SpellScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<DestinationTargetSelectHandler>::iterator itr = OnDestinationTargetSelect.begin(); itr != OnDestinationTargetSelect.end(); ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnDestinationTargetSelect` of SpellScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    return _SpellScript::_Validate(entry);
}
References _SpellScript::_Validate(), SpellInfo::Id, LOG_ERROR, _SpellScript::m_scriptName, OnDestinationTargetSelect, OnEffectHit, OnEffectHitTarget, OnEffectLaunch, OnEffectLaunchTarget, OnObjectAreaTargetSelect, and OnObjectTargetSelect.
Referenced by ObjectMgr::ValidateSpellScripts().
Cancel()
void SpellScript::Cancel ()
{
    m_spell->cancel();
}
References Spell::cancel(), and m_spell.
Referenced by spell_mark_of_the_faceless_drainhealth::spell_mark_of_the_faceless_drainhealth_SpellScript::FilterTargets().
CreateItem()
void SpellScript::CreateItem (uint32 effIndex, uint32 itemId)
{
    m_spell->DoCreateItem(effIndex, itemId);
}
References Spell::DoCreateItem(), and m_spell.
Referenced by spell_gen_upper_deck_create_foam_sword::HandleScript(), and spell_warl_create_healthstone::HandleScriptEffect().
FinishCast()
void SpellScript::FinishCast (SpellCastResult result)
{
    m_spell->SendCastResult(result);
    m_spell->finish(result == SPELL_CAST_OK);
}
References Spell::finish(), m_spell, Spell::SendCastResult(), and SPELL_CAST_OK.
Referenced by spell_dk_corpse_explosion::CheckTargets(), spell_brewfest_apple_trap::FilterTargets(), spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::FilterTargets(), spell_dru_t10_restoration_4p_bonus::FilterTargets(), spell_rog_killing_spree::spell_rog_killing_spree_SpellScript::FilterTargets(), and spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::SelectTarget().
GetCaster()
Unit * SpellScript::GetCaster ()
{
    return m_spell->GetCaster();
}
References Spell::GetCaster(), and m_spell.
Referenced by spell_oculus_shock_lance::spell_oculus_shock_lance_SpellScript::CalcDamage(), spell_krystallus_shatter_effect::spell_krystallus_shatter_effect_SpellScript::CalculateDamage(), spell_gruul_shatter_effect::spell_gruul_shatter_effect_SpellScript::CalculateDamage(), spell_item_wraith_scythe_drain_life::CalculateDamage(), spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::CalculateDamage(), spell_loken_pulsing_shockwave::spell_loken_pulsing_shockwave_SpellScript::CalculateDamage(), spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript::ChangeDamageAndGrow(), spell_quest_dragonmaw_race_generic::ChangeDest(), spell_eredar_twins_handle_touch::spell_eredar_twins_handle_touch_SpellScript::CheckCast(), spell_kalecgos_spectral_realm_dummy::spell_kalecgos_spectral_realm_dummy_SpellScript::CheckCast(), spell_brewfest_toss_mug::CheckCast(), spell_midsummer_fling_torch::CheckCast(), spell_yogg_saron_in_the_maws_of_the_old_god::spell_yogg_saron_in_the_maws_of_the_old_god_SpellScript::CheckCast(), spell_q12237_rescue_villager::CheckCast(), spell_q12237_drop_off_villager::CheckCast(), spell_wintergrasp_water::spell_wintergrasp_water_SpellScript::CheckCast(), spell_dk_death_coil::CheckCast(), spell_dk_death_grip::CheckCast(), spell_dk_death_pact::CheckCast(), spell_dru_savage_roar::CheckCast(), spell_dru_survival_instincts::CheckCast(), spell_hun_check_pet_los::CheckCast(), spell_hun_pet_heart_of_the_phoenix::CheckCast(), spell_hun_disengage::CheckCast(), spell_hun_tame_beast::CheckCast(), spell_hun_bestial_wrath::CheckCast(), spell_item_rocket_boots::CheckCast(), spell_item_snowman::CheckCast(), spell_mage_ice_barrier::CheckCast(), spell_pal_holy_shock::CheckCast(), spell_pal_lay_on_hands::CheckCast(), spell_pal_righteous_defense::CheckCast(), spell_pri_penance::CheckCast(), spell_pri_power_word_shield::CheckCast(), spell_q9452_cast_net::CheckCast(), spell_q4735_collect_rookery_egg::CheckCast(), spell_rog_killing_spree::spell_rog_killing_spree_SpellScript::CheckCast(), spell_rog_pickpocket::CheckCast(), spell_sha_spirit_walk::CheckCast(), spell_warl_ritual_of_summoning::CheckCast(), spell_warl_create_healthstone::CheckCast(), spell_warl_life_tap::CheckCast(), spell_dk_death_gate::CheckClass(), spell_baltharus_enervating_brand_trigger::spell_baltharus_enervating_brand_trigger_SpellScript::CheckDistance(), spell_igb_cannon_blast::spell_igb_cannon_blast_SpellScript::CheckEnergy(), spell_sha_fire_nova::CheckFireTotem(), spell_gen_cannibalize::CheckIfCorpseNear(), spell_hun_pet_carrion_feeder::CheckIfCorpseNear(), spell_gen_summon_tournament_mount::CheckIfLanceEquiped(), spell_gen_proc_above_75::CheckLevel(), spell_q4735_collect_rookery_egg::CheckQuest(), spell_dk_raise_dead::CheckReagents(), spell_item_gift_of_the_harvester::spell_item_gift_of_the_harvester_SpellScript::CheckRequirement(), spell_ooze_zap::spell_ooze_zap_SpellScript::CheckRequirement(), spell_call_wintergarde_gryphon::CheckRequirement(), spell_renew_skirmisher::CheckRequirement(), spell_gen_profession_research::CheckRequirement(), spell_item_book_of_glyph_mastery::CheckRequirement(), spell_item_demon_broiled_surprise::CheckRequirement(), spell_q12943_shadow_vault_decree::CheckRequirement(), spell_q13369_fate_up_against_your_will::CheckRequirement(), spell_q11010_q11102_q11023_q11008_check_fly_mount::CheckRequirement(), spell_gen_vehicle_scaling::CheckSeat(), spell_item_map_of_the_geyser_fields::CheckSinkholes(), spell_q11117_catch_the_wild_wolpertinger::CheckTarget(), spell_q11670_it_was_the_orcs_honest::CheckTarget(), spell_rotface_unstable_ooze_explosion::spell_rotface_unstable_ooze_explosion_SpellScript::CheckTarget(), spell_dk_corpse_explosion::CheckTarget(), spell_the_lich_king_shadow_trap_periodic::spell_the_lich_king_shadow_trap_periodic_SpellScript::CheckTargetCount(), spell_the_lich_king_vile_spirit_damage_target_search::spell_the_lich_king_vile_spirit_damage_target_search_SpellScript::CheckTargetCount(), spell_the_lich_king_ice_burst_target_search::spell_the_lich_king_ice_burst_target_search_SpellScript::CheckTargetCount(), spell_algalon_big_bang::spell_algalon_big_bang_SpellScript::CheckTargets(), spell_dk_corpse_explosion::CheckTargets(), spell_dk_raise_dead::CheckTargets(), spell_dk_rune_tap_party::CheckTargets(), spell_dk_raise_dead::ConsumeReagents(), spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript::CorrectRange(), spell_ruby_sanctum_rallying_shout::spell_ruby_sanctum_rallying_shout_SpellScript::CountAllies(), spell_frost_giant_death_plague::spell_frost_giant_death_plague_SpellScript::CountTargets(), spell_igb_rocket_artillery_explosion::spell_igb_rocket_artillery_explosion_SpellScript::DamageGunship(), spell_hun_masters_call::DoCheckCast(), spell_putricide_regurgitated_ooze::spell_putricide_regurgitated_ooze_SpellScript::ExtraEffect(), spell_dk_death_pact::FilterTargets(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::FilterTargets(), spell_kalecgos_spectral_blast_dummy::spell_kalecgos_spectral_blast_dummy_SpellScript::FilterTargets(), spell_kiljaeden_sinister_reflection_clone::spell_kiljaeden_sinister_reflection_clone_SpellScript::FilterTargets(), spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript::FilterTargets(), spell_gahzranka_slam::FilterTargets(), spell_chain_burn::FilterTargets(), spell_brewfest_toss_mug::FilterTargets(), spell_send_mug_target_picker::FilterTargets(), spell_aq_shadow_storm::FilterTargets(), spell_cthun_dark_glare::FilterTargets(), spell_huhuran_poison_bolt::FilterTargets(), spell_energize_aoe::spell_energize_aoe_SpellScript::FilterTargets(), spell_eadric_radiance::spell_eadric_radiance_SpellScript::FilterTargets(), spell_bronjahm_soulstorm_targeting::spell_bronjahm_soulstorm_targeting_SpellScript::FilterTargets(), spell_garfrost_permafrost::spell_garfrost_permafrost_SpellScript::FilterTargets(), spell_blood_queen_pact_of_the_darkfallen::spell_blood_queen_pact_of_the_darkfallen_SpellScript::FilterTargets(), spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::FilterTargets(), spell_blood_queen_swarming_shadows_floor_dmg::spell_blood_queen_swarming_shadows_floor_dmg_SpellScript::FilterTargets(), spell_deathbringer_boiling_blood::spell_deathbringer_boiling_blood_SpellScript::FilterTargets(), spell_igb_teleport_players_on_victory::spell_igb_teleport_players_on_victory_SpellScript::FilterTargets(), spell_igb_burning_pitch_selector::spell_igb_burning_pitch_selector_SpellScript::FilterTargets(), spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::FilterTargets(), spell_rotface_mutated_infection::spell_rotface_mutated_infection_SpellScript::FilterTargets(), spell_sindragosa_mystic_buffet::spell_sindragosa_mystic_buffet_SpellScript::FilterTargets(), spell_the_lich_king_quake::spell_the_lich_king_quake_SpellScript::FilterTargets(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript::FilterTargets(), spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript::FilterTargets(), spell_grobbulus_poison::spell_grobbulus_poison_SpellScript::FilterTargets(), spell_kelthuzad_frost_blast::spell_kelthuzad_frost_blast_SpellScript::FilterTargets(), spell_sapphiron_frost_explosion::spell_sapphiron_frost_explosion_SpellScript::FilterTargets(), spell_eoe_ph3_surge_of_power::spell_eoe_ph3_surge_of_power_SpellScript::FilterTargets(), spell_yogg_saron_lunatic_gaze::spell_yogg_saron_lunatic_gaze_SpellScript::FilterTargets(), spell_gurtogg_bloodboil::spell_gurtogg_bloodboil_SpellScript::FilterTargets(), spell_reliquary_of_souls_fixate::spell_reliquary_of_souls_fixate_SpellScript::FilterTargets(), spell_lurker_below_spout_cone::spell_lurker_below_spout_cone_SpellScript::FilterTargets(), spell_dru_t10_restoration_4p_bonus::FilterTargets(), spell_dru_wild_growth::FilterTargets(), spell_gen_select_target_count::FilterTargets(), spell_pri_circle_of_healing::FilterTargets(), spell_pri_divine_hymn::FilterTargets(), spell_pri_hymn_of_hope::FilterTargets(), spell_rog_killing_spree::spell_rog_killing_spree_SpellScript::FilterTargets(), spell_blood_queen_pact_of_the_darkfallen_dmg_target::spell_blood_queen_pact_of_the_darkfallen_dmg_SpellScript::FilterTargets(), spell_sindragosa_unchained_magic::spell_sindragosa_unchained_magic_SpellScript::FilterTargets(), spell_the_lich_king_restore_soul::spell_the_lich_king_restore_soul_SpellScript::FilterTargets(), spell_leotheras_insidious_whisper::spell_leotheras_insidious_whisper_SpellScript::FilterTargets(), spell_pri_mind_sear::FilterTargets(), spell_warr_improved_spell_reflection_trigger::FilterTargets(), spell_deathbringer_blood_nova_targeting::spell_deathbringer_blood_nova_targeting_SpellScript::FilterTargetsInitial(), spell_putricide_mutated_transformation_dmg::spell_putricide_mutated_transformation_dmg_SpellScript::FilterTargetsInitial(), spell_ulduar_stone_grip_cast_target::spell_ulduar_stone_grip_cast_target_SpellScript::FilterTargetsInitial(), spell_dk_raise_dead::GetGhoulSpellId(), spell_q9452_cast_net::HandleActiveObject(), spell_q4735_collect_rookery_egg::HandleActiveObject(), spell_mt_phoenix_burn::spell_mt_phoenix_burn_SpellScript::HandleAfterCast(), spell_apothecary_lingering_fumes::HandleAfterCast(), spell_cataclysm_breath::spell_cataclysm_breath_SpellScript::HandleAfterCast(), spell_herald_volzaj_insanity::HandleAfterCast(), spell_thaddius_polarity_shift::spell_thaddius_polarity_shift_SpellScript::HandleAfterCast(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::HandleAfterCast(), spell_dk_chains_of_ice::HandleAfterCast(), spell_dru_berserk::HandleAfterCast(), spell_mage_arcane_blast::HandleAfterCast(), spell_q13086_last_line_of_defence::HandleAfterCast(), spell_sha_totem_of_wrath::HandleAfterCast(), spell_brewfest_fill_keg::HandleAfterHit(), spell_brewfest_unfill_keg::HandleAfterHit(), spell_gen_leeching_swarm_dmg::spell_gen_leeching_swarm_dmg_SpellScript::HandleAfterHit(), spell_saronite_vapors_damage::spell_saronite_vapors_damage_SpellScript::HandleAfterHit(), spell_dk_blood_boil::HandleAfterHit(), spell_dk_scourge_strike::HandleAfterHit(), spell_rog_deadly_poison::HandleAfterHit(), spell_azjol_nerub_pound::HandleApplyAura(), spell_galdarah_impaling_charge::spell_galdarah_impaling_charge_SpellScript::HandleApplyAura(), spell_warl_banish::HandleBanish(), spell_dk_death_grip::HandleBaseDummy(), spell_kaelthas_resurrection::spell_kaelthas_resurrection_SpellScript::HandleBeforeCast(), spell_brewfest_toss_mug::HandleBeforeHit(), spell_rog_deadly_poison::HandleBeforeHit(), spell_gen_charmed_unit_spell_cooldown::HandleCast(), spell_rotface_unstable_ooze_explosion_init::spell_rotface_unstable_ooze_explosion_init_SpellScript::HandleCast(), spell_commander_sarannis_summon_reinforcements::spell_commander_sarannis_summon_reinforcements_SpellScript::HandleCast(), spell_gen_mounted_charge::HandleChargeEffect(), spell_dk_corpse_explosion::HandleCorpseExplosion(), spell_pri_shadow_word_death::HandleDamage(), spell_warr_bloodthirst::HandleDamage(), spell_dk_corpse_explosion::HandleDamage(), spell_dk_ghoul_explode::HandleDamage(), spell_freezing_circle::HandleDamage(), spell_four_horsemen_consumption::HandleDamageCalc(), spell_oculus_touch_the_nightmare::spell_oculus_touch_the_nightmare_SpellScript::HandleDamageCalc(), spell_pet_dk_gargoyle_strike::HandleDamageCalc(), spell_gordunni_trap::spell_gordunni_trap_SpellScript::HandleDummy(), spell_icc_shattered_bones::spell_icc_shattered_bones_SpellScript::HandleDummy(), spell_corrupted_totems::HandleDummy(), spell_moroes_vanish::spell_moroes_vanish_SpellScript::HandleDummy(), spell_karazhan_blink::spell_karazhan_blink_SpellScript::HandleDummy(), spell_midsummer_juggling_torch::HandleDummy(), spell_ooze_zap::spell_ooze_zap_SpellScript::HandleDummy(), spell_ooze_zap_channel_end::spell_ooze_zap_channel_end_SpellScript::HandleDummy(), spell_saviana_conflagration_init::spell_saviana_conflagration_init_SpellScript::HandleDummy(), spell_igb_burning_pitch_selector::spell_igb_burning_pitch_selector_SpellScript::HandleDummy(), spell_igb_burning_pitch::spell_igb_burning_pitch_SpellScript::HandleDummy(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::HandleDummy(), spell_switch_infragreen_bomber_station::spell_switch_infragreen_bomber_station_SpellScript::HandleDummy(), spell_q13007_iron_colossus::spell_q13007_iron_colossus_SpellScript::HandleDummy(), spell_illidan_found_target::spell_illidan_found_target_SpellScript::HandleDummy(), spell_leotheras_chaos_blast::spell_leotheras_chaos_blast_SpellScript::HandleDummy(), spell_morogrim_tidewalker_watery_grave::spell_morogrim_tidewalker_watery_grave_SpellScript::HandleDummy(), spell_morogrim_tidewalker_water_globule_new_target::spell_morogrim_tidewalker_water_globule_new_target_SpellScript::HandleDummy(), spell_q10935_the_exorcism_of_colonel_jules::spell_q10935_the_exorcism_of_colonel_jules_SpellScript::HandleDummy(), spell_gen_hate_to_zero::HandleDummy(), spell_gen_focused_bursts::HandleDummy(), spell_gen_oracle_wolvar_reputation::HandleDummy(), spell_gen_despawn_self::HandleDummy(), spell_item_lil_xt::HandleDummy(), spell_sha_healing_stream_totem::HandleDummy(), spell_shadowblink::HandleDummy(), spell_spawn_drakonid::HandleDummy(), spell_magmadar_lava_bomb::spell_magmadar_lava_bomb_SpellScript::HandleDummy(), spell_send_mug_target_picker::HandleDummy(), spell_hallows_end_candy::HandleDummy(), spell_hallows_end_bucket_lands::HandleDummy(), spell_pilgrims_bounty_pass_generic::HandleDummy(), spell_pilgrims_bounty_feast_on_generic::HandleDummy(), spell_mana_burn_area::HandleDummy(), spell_aggro_drones::HandleDummy(), spell_voljin_war_drums::spell_voljin_war_drums_SpellScript::HandleDummy(), spell_voodoo::spell_voodoo_SpellScript::HandleDummy(), spell_ahn_kahet_swarmer_aura::HandleDummy(), spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::HandleDummy(), spell_halion_meteor_strike_targeting::spell_halion_meteor_strike_targeting_SpellScript::HandleDummy(), spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::HandleDummy(), spell_dred_raptor_call::spell_dred_raptor_call_SpellScript::HandleDummy(), spell_pos_slave_trigger_closest::spell_pos_slave_trigger_closestSpellScript::HandleDummy(), spell_pos_rimefang_frost_nova::spell_pos_rimefang_frost_novaSpellScript::HandleDummy(), spell_drakkari_colossus_emerge::spell_drakkari_colossus_emerge_SpellScript::HandleDummy(), spell_drakkari_colossus_surge::spell_drakkari_colossus_surge_SpellScript::HandleDummy(), spell_putricide_ooze_eruption_searcher::spell_putricide_ooze_eruption_searcher_SpellScript::HandleDummy(), spell_thaddius_polarity_shift::spell_thaddius_polarity_shift_SpellScript::HandleDummy(), spell_voa_flaming_cinder::spell_voa_flaming_cinder_SpellScript::HandleDummy(), spell_q12096_q12092_dummy::spell_q12096_q12092_dummy_SpellScript::HandleDummy(), spell_vehicle_warhead_fuse::spell_vehicle_warhead_fuse_SpellScript::HandleDummy(), spell_warhead_detonate::spell_warhead_detonate_SpellScript::HandleDummy(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_najentus_needle_spine::spell_najentus_needle_spine_SpellScript::HandleDummy(), spell_capacitus_polarity_shift::spell_capacitus_polarity_shift_SpellScript::HandleDummy(), spell_dk_raise_ally::HandleDummy(), spell_dk_death_coil::HandleDummy(), spell_dk_death_grip::HandleDummy(), spell_dk_death_strike::HandleDummy(), spell_dk_scourge_strike::HandleDummy(), spell_dru_starfall_dummy::HandleDummy(), spell_gen_cannibalize::HandleDummy(), spell_gen_dummy_trigger::HandleDummy(), spell_gen_gadgetzan_transporter_backfire::HandleDummy(), spell_gen_gnomish_transporter::HandleDummy(), spell_hun_last_stand_pet::HandleDummy(), spell_hun_masters_call::HandleDummy(), spell_hun_readiness::HandleDummy(), spell_hun_scatter_shot::HandleDummy(), spell_hun_pet_carrion_feeder::HandleDummy(), spell_item_gnomish_universal_remote::HandleDummy(), spell_item_gnomish_shrink_ray::HandleDummy(), spell_item_trigger_spell::HandleDummy(), spell_item_deviate_fish::HandleDummy(), spell_item_flask_of_the_north::HandleDummy(), spell_item_gnomish_death_ray::HandleDummy(), spell_item_make_a_wish::HandleDummy(), spell_item_mingos_fortune_generator::HandleDummy(), spell_item_net_o_matic::HandleDummy(), spell_item_noggenfogger_elixir::HandleDummy(), spell_item_savory_deviate_delight::HandleDummy(), spell_item_six_demon_bag::HandleDummy(), spell_item_underbelly_elixir::HandleDummy(), spell_item_vanquished_clutches::HandleDummy(), spell_item_purify_helboar_meat::HandleDummy(), spell_item_crystal_prison_dummy_dnd::HandleDummy(), spell_item_reindeer_transformation::HandleDummy(), spell_item_nigh_invulnerability::HandleDummy(), spell_item_poultryizer::HandleDummy(), spell_item_socrethars_stone::HandleDummy(), spell_item_demon_broiled_surprise::HandleDummy(), spell_item_complete_raptor_capture::HandleDummy(), spell_item_brewfest_mount_transformation::HandleDummy(), spell_item_nitro_boots::HandleDummy(), spell_item_teach_language::HandleDummy(), spell_item_rocket_boots::HandleDummy(), spell_item_pygmy_oil::HandleDummy(), spell_item_unusual_compass::HandleDummy(), spell_item_chicken_cover::HandleDummy(), spell_item_refocus::HandleDummy(), spell_item_greatmothers_soulcatcher::HandleDummy(), spell_item_goblin_bomb::HandleDummy(), spell_mage_cold_snap::HandleDummy(), spell_mage_polymorph_cast_visual::HandleDummy(), spell_mage_summon_water_elemental::HandleDummy(), spell_pal_blessing_of_faith::HandleDummy(), spell_pal_divine_storm_dummy::HandleDummy(), spell_pal_holy_shock::HandleDummy(), spell_pal_judgement_of_command::HandleDummy(), spell_pri_penance::HandleDummy(), spell_q10714_on_spirits_wings::HandleDummy(), spell_q11520_discovering_your_roots::HandleDummy(), spell_generic_quest_update_entry_SpellScript::HandleDummy(), spell_q5206_test_fetid_skull::HandleDummy(), spell_q6124_6129_apply_salve::HandleDummy(), spell_q11396_11399_scourging_crystal_controller::HandleDummy(), spell_q11587_arcane_prisoner_rescue::HandleDummy(), spell_q11730_ultrasonic_screwdriver::HandleDummy(), spell_q12634_despawn_fruit_tosser::HandleDummy(), spell_q12683_take_sputum_sample::HandleDummy(), spell_q12937_relief_for_the_fallen::HandleDummy(), spell_q12659_ahunaes_knife::HandleDummy(), spell_q9874_liquid_fire::HandleDummy(), spell_q13280_13283_plant_battle_standard::HandleDummy(), spell_q9452_cast_net::HandleDummy(), spell_q12277_wintergarde_mine_explosion::HandleDummy(), spell_q12066_bunny_kill_credit::HandleDummy(), spell_q11010_q11102_q11023_choose_loc::HandleDummy(), spell_q13291_q13292_q13239_q13261_frostbrood_skytalon_grab_decoy::HandleDummy(), spell_q12308_escape_from_silverbrook::HandleDummy(), spell_q12641_death_comes_from_on_high::HandleDummy(), spell_rog_killing_spree::spell_rog_killing_spree_SpellScript::HandleDummy(), spell_rog_preparation::HandleDummy(), spell_rog_shiv::HandleDummy(), spell_sha_ancestral_awakening_proc::HandleDummy(), spell_sha_cleansing_totem_pulse::HandleDummy(), spell_sha_fire_nova::HandleDummy(), spell_sha_lava_lash::HandleDummy(), spell_sha_mana_spring_totem::HandleDummy(), spell_sha_mana_tide_totem::HandleDummy(), spell_warl_ritual_of_doom_effect::HandleDummy(), spell_warl_soulshatter::HandleDummy(), spell_warl_life_tap::HandleDummy(), spell_warr_last_stand::HandleDummy(), spell_warr_deep_wounds::HandleDummy(), spell_warr_charge::HandleDummy(), spell_warr_slam::HandleDummy(), spell_warr_concussion_blow::HandleDummy(), spell_warr_bloodthirst::HandleDummy(), spell_yogg_saron_destabilization_matrix::spell_yogg_saron_destabilization_matrix_SpellScript::HandleDummyEffect(), spell_yogg_saron_titanic_storm::spell_yogg_saron_titanic_storm_SpellScript::HandleDummyEffect(), spell_yogg_saron_insane_periodic_trigger::spell_yogg_saron_insane_periodic_trigger_SpellScript::HandleDummyEffect(), spell_q11117_catch_the_wild_wolpertinger::HandleDummyEffect(), spell_svala_ritual_strike::spell_svala_ritual_strike_SpellScript::HandleDummyEffect(), spell_image_of_drakuru_reagent_check::HandleDummyEffect(), spell_herald_volzaj_insanity::HandleDummyEffect(), spell_egg_explosion::HandleDummyHitTarget(), spell_icc_yd_summon_undead::spell_icc_yd_summon_undead_SpellScript::HandleDummyLaunch(), spell_warr_execute::HandleEffect(), spell_axe_flurry::HandleEffect(), spell_q11719_bloodspore_ruination_45997::spell_q11719_bloodspore_ruination_45997_SpellScript::HandleEffect(), spell_item_elixir_of_shadows::HandleEffect(), spell_warr_overpower::HandleEffect(), spell_dream_fog_sleep::spell_dream_fog_sleep_SpellScript::HandleEffect(), spell_pri_pain_and_suffering_proc::HandleEffectScriptEffect(), spell_icc_sprit_alarm::spell_icc_sprit_alarm_SpellScript::HandleEvent(), spell_icc_geist_alarm::spell_icc_geist_alarm_SpellScript::HandleEvent(), spell_midsummer_fling_torch::HandleFinish(), spell_midsummer_juggling_torch::HandleFinish(), spell_wintergrasp_rp_gg::spell_wintergrasp_rp_gg_SpellScript::HandleFinish(), spell_the_flag_of_ownership::HandleFinish(), spell_hun_volley_trigger::HandleFinish(), spell_q12014_steady_as_a_rock::HandleFinish(), spell_q5056_summon_shy_rotam::HandleFinish(), spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript::HandleForceCast(), spell_dreamwalker_summon_suppresser_effect::spell_dreamwalker_summon_suppresser_effect_SpellScript::HandleForceCast(), spell_alar_ember_blast::spell_alar_ember_blast_SpellScript::HandleForceCast(), spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript::HandleForcedCast(), spell_ioc_bomb_blast_criteria::spell_ioc_bomb_blast_criteria_SpellScript::HandleGameObjectDamage(), spell_item_crazy_alchemists_potion::HandleHeal(), spell_item_runic_healing_injector::HandleHeal(), spell_sha_chain_heal::HandleHeal(), spell_warr_bloodthirst_heal::HandleHeal(), spell_summon_ragnaros::spell_summon_ragnaros_SpellScript::HandleHit(), spell_hate_to_zero::spell_hate_to_zero_SpellScript::HandleHit(), spell_assembly_meltdown::spell_assembly_meltdown_SpellScript::HandleInstaKill(), spell_item_toxic_wasteling::HandleJump(), spell_dru_typhoon::HandleKnockBack(), spell_mage_blast_wave::HandleKnockBack(), spell_sha_thunderstorm::HandleKnockBack(), spell_q12690_burst_at_the_seams::HandleKnockBack(), spell_hatch_eggs::HandleObjectAreaTargetSelect(), spell_gen_haunted::HandleOnEffectHit(), spell_item_summon_argent_knight::HandleOnEffectHit(), spell_egg_event::spell_egg_eventSpellScript::HandleOnHit(), spell_hakkar_power_down::HandleOnHit(), spell_random_aggro::HandleOnHit(), spell_delusions_of_jindo::HandleOnHit(), spell_enveloping_webs::HandleOnHit(), spell_arcane_vacuum::HandleOnHit(), spell_mark_of_frost_freeze::HandleOnHit(), spell_explode_trigger::HandleOnHit(), spell_voa_lightning_nova::spell_voa_lightning_nova_SpellScript::HandleOnHit(), spell_class_call_handler::HandleOnHitRogue(), spell_zulfarrak_unlocking::spell_zulfarrak_unlocking_SpellScript::HandleOpenLock(), spell_entropius_black_hole_effect::spell_entropius_black_hole_effect_SpellScript::HandlePull(), spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript::HandlePull(), spell_dk_raise_dead::HandleRaiseDead(), spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::HandleSchoolDamage(), spell_gen_mine_sweeper::HandleSchoolDMG(), spell_warl_shadowflame::HandleSchoolDMG(), spell_ragnaros_lava_burst_randomizer::HandleScript(), spell_ragnaros_summon_sons_of_flame::HandleScript(), spell_pvp_trinket_wotf_shared_cd::HandleScript(), spell_gen_bandage::HandleScript(), spell_pal_lay_on_hands::HandleScript(), spell_kormok_summon_bone_mages::HandleScript(), spell_kormok_summon_bone_minions::HandleScript(), spell_midsummer_fling_torch::HandleScript(), spell_energize_aoe::spell_energize_aoe_SpellScript::HandleScript(), spell_saviana_conflagration_throwback::spell_saviana_conflagration_throwback_SpellScript::HandleScript(), spell_taldaram_glittering_sparks::spell_taldaram_glittering_sparks_SpellScript::HandleScript(), spell_taldaram_summon_flame_ball::spell_taldaram_summon_flame_ball_SpellScript::HandleScript(), spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::HandleScript(), spell_igb_rocket_artillery::spell_igb_rocket_artillery_SpellScript::HandleScript(), spell_putricide_unstable_experiment::spell_putricide_unstable_experiment_SpellScript::HandleScript(), spell_putricide_clear_aura_effect_value::spell_putricide_clear_aura_effect_value_SpellScript::HandleScript(), spell_sindragosa_icy_grip::spell_sindragosa_icy_grip_SpellScript::HandleScript(), spell_frostwarden_handler_focus_fire::spell_frostwarden_handler_focus_fire_SpellScript::HandleScript(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::HandleScript(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::HandleScript(), spell_archavon_rock_shards::spell_archavon_rock_shards_SpellScript::HandleScript(), spell_gen_create_lance::HandleScript(), spell_item_defibrillate::HandleScript(), spell_item_scroll_of_recall::HandleScript(), spell_gen_elemental_shield::HandleScript(), spell_gen_brood_power::HandleScript(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::HandleScript(), spell_apothecary_lingering_fumes::HandleScript(), spell_apothecary_validate_area::HandleScript(), spell_blight_worm_ingest::spell_blight_worm_ingest_SpellScript::HandleScript(), spell_hallows_end_trick::HandleScript(), spell_hallows_end_put_costume::HandleScript(), spell_hallows_end_trick_or_treat::HandleScript(), spell_winter_veil_mistletoe::HandleScript(), spell_ayamiss_swarmer_teleport_trigger::HandleScript(), spell_ayamiss_swarmer_swarm::HandleScript(), spell_ayamiss_swarmer_start_loop::HandleScript(), spell_gen_ayamiss_swarmer_loop::HandleScript(), spell_moam_mana_drain_filter::HandleScript(), spell_moam_summon_mana_fiends::HandleScript(), spell_drain_mana::HandleScript(), spell_prince_taldaram_conjure_flame_sphere::HandleScript(), spell_mistress_kiss_area::spell_mistress_kiss_area_SpellScript::HandleScript(), spell_novos_summon_minions::spell_novos_summon_minions_SpellScript::HandleScript(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::HandleScript(), spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::HandleScript(), spell_putricide_choking_gas_bomb::spell_putricide_choking_gas_bomb_SpellScript::HandleScript(), spell_rotface_little_ooze_combine::spell_rotface_little_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_combine::spell_rotface_large_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_buff_combine::spell_rotface_large_ooze_buff_combine_SpellScript::HandleScript(), spell_the_lich_king_cast_back_to_caster::spell_the_lich_king_cast_back_to_caster_SpellScript::HandleScript(), spell_xt002_gravity_bomb_damage::spell_xt002_gravity_bomb_damage_SpellScript::HandleScript(), spell_yogg_saron_target_selectors::spell_yogg_saron_target_selectors_SpellScript::HandleScript(), spell_q12237_rescue_villager::HandleScript(), spell_shredder_delivery::spell_shredder_delivery_SpellScript::HandleScript(), spell_the_black_stalker_levitation_pulse::HandleScript(), spell_the_black_stalker_someone_grab_me::HandleScript(), spell_the_flag_of_ownership::HandleScript(), spell_gen_pet_summoned::HandleScript(), spell_gen_elune_candle::HandleScript(), spell_gen_divine_storm_cd_reset::HandleScript(), spell_gen_profession_research::HandleScript(), spell_gen_dalaran_disguise::HandleScript(), spell_gen_ds_flush_knockback::HandleScript(), spell_hun_pet_heart_of_the_phoenix::HandleScript(), spell_item_dimensional_ripper_area52::HandleScript(), spell_item_book_of_glyph_mastery::HandleScript(), spell_item_eggnog::HandleScript(), spell_item_worn_troll_dice::HandleScript(), spell_q12805_lifeblood_dummy::HandleScript(), spell_q12735_song_of_cleansing::HandleScript(), spell_q13011_bear_flank_master::HandleScript(), spell_q12690_burst_at_the_seams::HandleScript(), spell_q12619_emblazon_runeblade_effect::HandleScript(), spell_q12919_gymers_grab::HandleScript(), spell_q12919_gymers_throw::HandleScript(), spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript::HandleScript2(), spell_q11670_it_was_the_orcs_honest::HandleScriptEffect(), spell_q12641_death_comes_from_on_high_summon_ghouls::spell_q12641_death_comes_from_on_high_summon_ghouls_SpellScript::HandleScriptEffect(), spell_felmyst_fog_of_corruption::spell_felmyst_fog_of_corruption_SpellScript::HandleScriptEffect(), spell_kalecgos_spectral_realm_dummy::spell_kalecgos_spectral_realm_dummy_SpellScript::HandleScriptEffect(), spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript::HandleScriptEffect(), spell_vem_knockback::HandleScriptEffect(), spell_azjol_nerub_fixate::spell_azjol_nerub_fixate_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame_bonestorm::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_gurtogg_eject::spell_gurtogg_eject_SpellScript::HandleScriptEffect(), spell_illidan_draw_soul::spell_illidan_draw_soul_SpellScript::HandleScriptEffect(), spell_illidan_cage_trap::spell_illidan_cage_trap_SpellScript::HandleScriptEffect(), spell_black_temple_bloodbolt::spell_black_temple_bloodbolt_SpellScript::HandleScriptEffect(), spell_lady_vashj_summon_sporebat::spell_lady_vashj_summon_sporebat_SpellScript::HandleScriptEffect(), spell_lady_vashj_spore_drop_effect::spell_lady_vashj_spore_drop_effect_SpellScript::HandleScriptEffect(), spell_leotheras_whirlwind::spell_leotheras_whirlwind_SpellScript::HandleScriptEffect(), spell_leotheras_clear_consuming_madness::spell_leotheras_clear_consuming_madness_SpellScript::HandleScriptEffect(), spell_kaelthas_summon_weapons::spell_kaelthas_summon_weapons_SpellScript::HandleScriptEffect(), spell_kaelthas_gravity_lapse::spell_kaelthas_gravity_lapse_SpellScript::HandleScriptEffect(), spell_kaelthas_nether_beam::spell_kaelthas_nether_beam_SpellScript::HandleScriptEffect(), spell_kaelthas_summon_nether_vapor::spell_kaelthas_summon_nether_vapor_SpellScript::HandleScriptEffect(), spell_gen_fixate::HandleScriptEffect(), spell_gen_knock_away::HandleScriptEffect(), spell_gen_throw_back::HandleScriptEffect(), spell_gen_clone::HandleScriptEffect(), spell_gen_clone_weapon::HandleScriptEffect(), spell_gen_break_shield::HandleScriptEffect(), spell_gen_mounted_charge::HandleScriptEffect(), spell_gen_throw_shield::HandleScriptEffect(), spell_item_sleepy_willy::HandleScriptEffect(), spell_item_lil_xt::HandleScriptEffect(), spell_item_feast::HandleScriptEffect(), spell_q12779_an_end_to_all_things::HandleScriptEffect(), spell_blood_siphon::HandleScriptEffect(), spell_brewfest_toss_mug::HandleScriptEffect(), spell_direbrew_summon_mole_machine_target_picker::HandleScriptEffect(), spell_request_second_mug::HandleScriptEffect(), spell_winter_veil_racer_slam_hit::HandleScriptEffect(), spell_volazj_whisper::HandleScriptEffect(), spell_novos_despawn_crystal_handler::spell_novos_despawn_crystal_handler_SpellScript::HandleScriptEffect(), spell_trollgore_consume::spell_trollgore_consume_SpellScript::HandleScriptEffect(), spell_trollgore_invader_taunt::spell_trollgore_invader_taunt_SpellScript::HandleScriptEffect(), spell_dtk_summon_random_drakkari::spell_dtk_summon_random_drakkari_SpellScript::HandleScriptEffect(), spell_drakkari_colossus_face_me::spell_drakkari_colossus_face_me_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_gluth_decimate::spell_gluth_decimate_SpellScript::HandleScriptEffect(), spell_arcane_chains_character_force_cast::spell_arcane_chains_character_force_cast_SpellScript::HandleScriptEffect(), spell_deliver_gryphon::HandleScriptEffect(), spell_q12611_deathbolt::HandleScriptEffect(), spell_illidari_council_judgement::spell_illidari_council_judgement_SpellScript::HandleScriptEffect(), spell_gruul_ground_slam::spell_gruul_ground_slam_SpellScript::HandleScriptEffect(), spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript::HandleScriptEffect(), spell_dk_pestilence::HandleScriptEffect(), spell_dru_glyph_of_starfire::HandleScriptEffect(), spell_gen_tournament_duel::HandleScriptEffect(), spell_hun_chimera_shot::HandleScriptEffect(), spell_item_mirrens_drinking_hat::HandleScriptEffect(), spell_pal_guarded_by_the_light::HandleScriptEffect(), spell_pal_judgement::HandleScriptEffect(), spell_pri_lightwell::HandleScriptEffect(), spell_q10720_the_smallest_creature::HandleScriptEffect(), spell_q12943_shadow_vault_decree::HandleScriptEffect(), spell_q1846_bending_shinbone::HandleScriptEffect(), spell_q14112_14145_chum_the_water::HandleScriptEffect(), spell_warl_demonic_empowerment::HandleScriptEffect(), spell_warl_everlasting_affliction::HandleScriptEffect(), spell_temple_of_atal_hakkar_awaken_the_soulflayer::spell_temple_of_atal_hakkar_awaken_the_soulflayer_SpellScript::HandleSendEvent(), spell_q12478_frostmourne_cavern::spell_q12478_frostmourne_cavern_SpellScript::HandleSendEvent(), spell_q12620_the_lifewarden_wrath::spell_q12620_the_lifewarden_wrath_SpellScript::HandleSendEvent(), spell_uldaman_sub_boss_agro_keepers::spell_uldaman_sub_boss_agro_keepers_SpellScript::HandleSendEvent(), spell_uldaman_boss_agro_archaedas::spell_uldaman_boss_agro_archaedas_SpellScript::HandleSendEvent(), spell_the_lich_king_quake::spell_the_lich_king_quake_SpellScript::HandleSendEvent(), spell_q10036_torgos::spell_q10036_torgos_SpellScript::HandleSendEvent(), spell_q10923_evil_draws_near_summon::spell_q10923_evil_draws_near_summon_SpellScript::HandleSendEvent(), spell_sindragosa_icy_grip_jump::spell_sindragosa_icy_grip_jump_SpellScript::HandleSpecial(), spell_marrowgar_bone_spike_graveyard::spell_marrowgar_bone_spike_graveyard_SpellScript::HandleSpikes(), spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::HandleSummon(), spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript::HandleSummon(), spell_item_summon_or_dismiss::HandleSummon(), spell_item_draenic_pale_ale::HandleSummon(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::HandleTargets(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleTargets(), spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::HandleTeleportUnits(), spell_trigger_spell_from_caster::spell_trigger_spell_from_caster_SpellScript::HandleTrigger(), spell_rimefang_icy_blast::spell_rimefang_icy_blast_SpellScript::HandleTriggerMissile(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), spell_pal_righteous_defense::HandleTriggerSpellHit(), spell_gahzranka_slam::HandleWipeThreat(), spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Land(), spell_ioc_launch::spell_ioc_launch_SpellScript::Launch(), spell_threatening_gaze_charge::LaunchHit(), spell_mandokir_charge::LaunchHit(), spell_hate_to_zero::spell_hate_to_zero_SpellScript::Load(), spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript::Load(), spell_ayamiss_swarmer_swarm::Load(), spell_ayamiss_swarmer_start_loop::Load(), spell_gen_ayamiss_swarmer_loop::Load(), spell_herald_volzaj_insanity::Load(), spell_volazj_whisper::Load(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript::Load(), spell_taldaram_summon_flame_ball::spell_taldaram_summon_flame_ball_SpellScript::Load(), spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::Load(), spell_deathbringer_boiling_blood::spell_deathbringer_boiling_blood_SpellScript::Load(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::Load(), spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::Load(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::Load(), spell_igb_teleport_players_on_victory::spell_igb_teleport_players_on_victory_SpellScript::Load(), spell_igb_cannon_blast::spell_igb_cannon_blast_SpellScript::Load(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::Load(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::Load(), spell_the_lich_king_quake::spell_the_lich_king_quake_SpellScript::Load(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::Load(), spell_the_lich_king_restore_soul::spell_the_lich_king_restore_soul_SpellScript::Load(), spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript::Load(), spell_dreamwalker_summon_suppresser_effect::spell_dreamwalker_summon_suppresser_effect_SpellScript::Load(), spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript::Load(), spell_eoe_ph3_surge_of_power::spell_eoe_ph3_surge_of_power_SpellScript::Load(), spell_ulduar_stone_grip_cast_target::spell_ulduar_stone_grip_cast_target_SpellScript::Load(), spell_shredder_delivery::spell_shredder_delivery_SpellScript::Load(), spell_illidan_cage_trap::spell_illidan_cage_trap_SpellScript::Load(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::Load(), spell_kaelthas_kael_phase_two::spell_kaelthas_kael_phase_two_SpellScript::Load(), spell_dk_blood_boil::Load(), spell_dk_raise_dead::Load(), spell_dru_t10_restoration_4p_bonus::Load(), spell_gen_pet_summoned::Load(), spell_pvp_trinket_wotf_shared_cd::Load(), spell_gen_divine_storm_cd_reset::Load(), spell_gen_profession_research::Load(), spell_gen_oracle_wolvar_reputation::Load(), spell_gen_despawn_self::Load(), spell_hun_readiness::Load(), spell_hun_scatter_shot::Load(), spell_hun_pet_heart_of_the_phoenix::Load(), spell_hun_pet_carrion_feeder::Load(), spell_item_feast::Load(), spell_item_deviate_fish::Load(), spell_item_make_a_wish::Load(), spell_item_noggenfogger_elixir::Load(), spell_item_savory_deviate_delight::Load(), spell_item_scroll_of_recall::Load(), spell_item_dimensional_ripper_area52::Load(), spell_item_underbelly_elixir::Load(), spell_item_book_of_glyph_mastery::Load(), spell_item_ashbringer::Load(), spell_item_purify_helboar_meat::Load(), spell_item_socrethars_stone::Load(), spell_item_demon_broiled_surprise::Load(), spell_item_teach_language::Load(), spell_item_rocket_boots::Load(), spell_item_runic_healing_injector::Load(), spell_item_chicken_cover::Load(), spell_item_worn_troll_dice::Load(), spell_mage_cold_snap::Load(), spell_pal_divine_storm::Load(), spell_pri_lightwell::Load(), spell_pri_penance::Load(), spell_q5206_test_fetid_skull::Load(), spell_q6124_6129_apply_salve::Load(), spell_q11730_ultrasonic_screwdriver::Load(), spell_q12937_relief_for_the_fallen::Load(), spell_q12659_ahunaes_knife::Load(), spell_q9874_liquid_fire::Load(), spell_q12805_lifeblood_dummy::Load(), spell_q9452_cast_net::Load(), spell_q13011_bear_flank_master::Load(), spell_q12690_burst_at_the_seams::Load(), spell_rog_deadly_poison::Load(), spell_rog_preparation::Load(), spell_rog_shiv::Load(), spell_warl_life_tap::Load(), spell_gen_random_target32::ModDest(), spell_gen_basic_campfire::ModDest(), spell_q12308_escape_from_silverbrook_summon_worgen::ModDest(), spell_rotface_mutated_infection::spell_rotface_mutated_infection_SpellScript::NotifyTargets(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::OnCast(), spell_item_ashbringer::OnDummyEffect(), spell_blackrock_spire_call_of_vaelastrasz::OnEffect(), spell_bh_cleanse_quel_delar::spell_bh_cleanse_quel_delar_SpellScript::OnEffect(), spell_pagles_point_cast::OnEffect(), spell_item_linken_boomerang::OnEffectLaunchTargetDisarm(), spell_item_linken_boomerang::OnEffectLaunchTargetStun(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript::Phase(), spell_anti_air_rocket_bomber::spell_anti_air_rocket_bomber_SpellScript::PrepareSpellScript(), spell_charge_shield_bomber::spell_charge_shield_bomber_SpellScript::PrepareSpellScript(), spell_fight_fire_bomber::spell_fight_fire_bomber_SpellScript::PrepareSpellScript(), spell_gen_grow_flower_patch::PrepareSpellScript(), spell_gen_mod_radius_by_caster_scale::PrepareSpellScript(), spell_gen_spectator_cheer_trigger::PrepareSpellScript(), spell_gen_use_spell_base_level_check::PrepareSpellScript(), spell_gen_vendor_bark_trigger::PrepareSpellScript(), spell_hodir_shatter_chest::spell_hodir_shatter_chestSpellScript::PrepareSpellScript(), spell_item_mind_amplify_dish::PrepareSpellScript(), spell_item_oracle_ablutions::PrepareSpellScript(), spell_item_titanium_seal_of_dalaran::PrepareSpellScript(), spell_q11198_take_down_tethyr::PrepareSpellScript(), spell_q11653_youre_not_so_big_now::PrepareSpellScript(), spell_q13369_fate_up_against_your_will::PrepareSpellScript(), spell_sha_lava_lash::PrepareSpellScript(), spell_bronjahm_magic_bane::spell_bronjahm_magic_bane_SpellScript::RecalculateDamage(), spell_marrowgar_bone_storm::spell_marrowgar_bone_storm_SpellScript::RecalculateDamage(), spell_wg_reduce_damage_by_distance::spell_wg_reduce_damage_by_distance_SpellScript::RecalculateDamage(), spell_pet_gen_valkyr_guardian_smite::RecalculateDamage(), spell_dk_death_and_decay::RecalculateDamage(), spell_dk_rune_of_the_fallen_crusader::RecalculateDamage(), spell_quest_dragonmaw_race_generic::RelocateDest(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::RelocateDest(), spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::RemoveEnergy(), spell_gen_replenishment::RemoveInvalidTargets(), spell_halion_twilight_cutter::spell_halion_twilight_cutter_SpellScript::RemoveNotBetween(), spell_putricide_slime_puddle::spell_putricide_slime_puddle_SpellScript::ScaleRange(), spell_valanar_kinetic_bomb_summon::spell_valanar_kinetic_bomb_summon_SpellScript::SelectDest(), spell_putricide_slime_puddle_spawn::spell_putricide_slime_puddle_spawn_SpellScript::SelectDest(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::SelectDest(), spell_tsh_shadow_bolt::spell_tsh_shadow_bolt_SpellScript::SelectRandomPlayer(), spell_igb_rocket_artillery::spell_igb_rocket_artillery_SpellScript::SelectRandomTarget(), spell_igb_explosion::spell_igb_explosion_SpellScript::SelectTarget(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::SelectTarget(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::SelectTarget(), spell_putricide_eat_ooze::spell_putricide_eat_ooze_SpellScript::SelectTarget(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::SelectTarget(), spell_xt002_gravity_bomb_aura::spell_xt002_gravity_bomb_aura_SpellScript::SelectTarget(), spell_xt002_searing_light_spawn_life_spark::spell_xt002_searing_light_spawn_life_spark_SpellScript::SelectTarget(), spell_murmur_thundering_storm::spell_murmur_thundering_storm_SpellScript::SelectTarget(), spell_kaelthas_mind_control::spell_kaelthas_mind_control_SpellScript::SelectTarget(), spell_gen_rallying_cry_of_the_dragonslayer::SelectTarget(), spell_gen_adals_song_of_battle::SelectTarget(), spell_item_fetch_ball::SelectTarget(), spell_warr_slam::SendMiss(), spell_warr_execute::SendMiss(), spell_azjol_nerub_impale_summon::SetDest(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::SetDest(), spell_q10898_skywing::spell_q10898_skywing_SpellScript::SetDest(), spell_dk_summon_gargoyle::SetDest(), spell_item_dragon_kite_summon_lightning_bunny::SetDest(), spell_item_recall::SetDest(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::StartAttack(), spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::StoreEnergy(), spell_dk_ghoul_explode::Suicide(), spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::TeleportPlayer(), spell_the_lich_king_life_siphon::spell_the_lich_king_life_siphon_SpellScript::TriggerHeal(), spell_pal_divine_storm::TriggerHeal(), spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::TriggerWipe(), and spell_warr_victory_rush::VictoryRushHit().
GetCastItem()
Item * SpellScript::GetCastItem ()
{
    return m_spell->m_CastItem;
}
References Spell::m_CastItem, and m_spell.
Referenced by spell_gen_allow_cast_from_item_only::CheckRequirement(), spell_brewfest_fill_keg::HandleAfterHit(), spell_brewfest_unfill_keg::HandleAfterHit(), spell_rog_deadly_poison::HandleAfterHit(), spell_item_trigger_spell::HandleDummy(), spell_item_six_demon_bag::HandleDummy(), spell_item_underbelly_elixir::HandleDummy(), spell_item_nigh_invulnerability::HandleDummy(), spell_item_poultryizer::HandleDummy(), spell_item_nitro_boots::HandleDummy(), spell_item_goblin_bomb::HandleDummy(), spell_q6124_6129_apply_salve::HandleDummy(), spell_q11396_11399_scourging_crystal_controller::HandleDummy(), spell_q11730_ultrasonic_screwdriver::HandleDummy(), spell_pvp_trinket_wotf_shared_cd::HandleScript(), spell_item_defibrillate::HandleScript(), spell_item_eggnog::HandleScript(), spell_item_nitro_boots::Load(), spell_q11730_ultrasonic_screwdriver::Load(), and spell_rog_deadly_poison::Load().
GetEffectValue()
int32 SpellScript::GetEffectValue () const
{
    if (!IsInEffectHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::GetEffectValue was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return 0;
    }
    return m_spell->damage;
}
References Spell::damage, IsInEffectHook(), LOG_ERROR, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and m_spell.
Referenced by spell_gen_eject_passenger::EjectPassenger(), spell_warr_bloodthirst::HandleDamage(), spell_dk_corpse_explosion::HandleDamage(), spell_ooze_zap::spell_ooze_zap_SpellScript::HandleDummy(), spell_igb_burning_pitch_selector::spell_igb_burning_pitch_selector_SpellScript::HandleDummy(), spell_igb_burning_pitch::spell_igb_burning_pitch_SpellScript::HandleDummy(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::HandleDummy(), spell_mage_burnout_trigger::HandleDummy(), spell_sha_healing_stream_totem::HandleDummy(), spell_deathbringer_blood_link::spell_deathbringer_blood_link_SpellScript::HandleDummy(), spell_dk_raise_ally::HandleDummy(), spell_dk_death_coil::HandleDummy(), spell_dk_scourge_strike::HandleDummy(), spell_dru_starfall_dummy::HandleDummy(), spell_gen_dummy_trigger::HandleDummy(), spell_hun_masters_call::HandleDummy(), spell_pal_divine_storm_dummy::HandleDummy(), spell_pal_judgement_of_command::HandleDummy(), spell_sha_ancestral_awakening_proc::HandleDummy(), spell_sha_lava_lash::HandleDummy(), spell_sha_mana_spring_totem::HandleDummy(), spell_sha_mana_tide_totem::HandleDummy(), spell_warl_ritual_of_doom_effect::HandleDummy(), spell_warl_life_tap::HandleDummy(), spell_warr_last_stand::HandleDummy(), spell_warr_deep_wounds::HandleDummy(), spell_warr_charge::HandleDummy(), spell_warr_slam::HandleDummy(), spell_warr_concussion_blow::HandleDummy(), spell_warr_bloodthirst::HandleDummy(), spell_warr_execute::HandleEffect(), spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript::HandleForcedCast(), spell_pri_prayer_of_mending_heal::HandleHeal(), spell_icc_harvest_blight_specimen::spell_icc_harvest_blight_specimen_SpellScript::HandleQuestComplete(), spell_energize_aoe::spell_energize_aoe_SpellScript::HandleScript(), spell_saviana_conflagration_throwback::spell_saviana_conflagration_throwback_SpellScript::HandleScript(), spell_taldaram_glittering_sparks::spell_taldaram_glittering_sparks_SpellScript::HandleScript(), spell_igb_rocket_artillery::spell_igb_rocket_artillery_SpellScript::HandleScript(), spell_putricide_clear_aura_effect_value::spell_putricide_clear_aura_effect_value_SpellScript::HandleScript(), spell_frostwarden_handler_focus_fire::spell_frostwarden_handler_focus_fire_SpellScript::HandleScript(), spell_the_lich_king_jump_remove_aura::spell_the_lich_king_jump_SpellScript::HandleScript(), spell_the_lich_king_raging_spirit::spell_the_lich_king_raging_spirit_SpellScript::HandleScript(), spell_the_lich_king_summon_spirit_bomb::spell_the_lich_king_summon_spirit_bomb_SpellScript::HandleScript(), spell_icc_harvest_blight_specimen::spell_icc_harvest_blight_specimen_SpellScript::HandleScript(), spell_wintergrasp_force_building::spell_wintergrasp_force_building_SpellScript::HandleScript(), spell_dk_death_gate::HandleScript(), spell_mistress_kiss_area::spell_mistress_kiss_area_SpellScript::HandleScript(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::HandleScript(), spell_putricide_eat_ooze::spell_putricide_eat_ooze_SpellScript::HandleScript(), spell_the_lich_king_cast_back_to_caster::spell_the_lich_king_cast_back_to_caster_SpellScript::HandleScript(), spell_stinky_precious_decimate::spell_stinky_precious_decimate_SpellScript::HandleScript(), spell_yogg_saron_target_selectors::spell_yogg_saron_target_selectors_SpellScript::HandleScript(), spell_q12237_rescue_villager::HandleScript(), spell_q12805_lifeblood_dummy::HandleScript(), spell_q12619_emblazon_runeblade_effect::HandleScript(), spell_azjol_nerub_fixate::spell_azjol_nerub_fixate_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame_bonestorm::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_black_temple_bloodbolt::spell_black_temple_bloodbolt_SpellScript::HandleScriptEffect(), spell_gen_fixate::HandleScriptEffect(), spell_gen_throw_back::HandleScriptEffect(), spell_gen_clone::HandleScriptEffect(), spell_gen_clone_weapon::HandleScriptEffect(), spell_gen_throw_shield::HandleScriptEffect(), spell_item_sleepy_willy::HandleScriptEffect(), spell_item_lil_xt::HandleScriptEffect(), spell_q12698_the_gift_that_keeps_on_giving::spell_q12698_the_gift_that_keeps_on_giving_SpellScript::HandleScriptEffect(), spell_q12779_an_end_to_all_things::HandleScriptEffect(), spell_trollgore_invader_taunt::spell_trollgore_invader_taunt_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_item_draenic_pale_ale::HandleSummon(), spell_charge_shield_bomber::spell_charge_shield_bomber_SpellScript::PrepareSpellScript(), spell_q11198_take_down_tethyr::PrepareSpellScript(), and spell_q13369_fate_up_against_your_will::PrepareSpellScript().
GetExplTargetDest()
WorldLocation const * SpellScript::GetExplTargetDest ()
{
    if (m_spell->m_targets.HasDst())
        return m_spell->m_targets.GetDstPos();
    return nullptr;
}
References SpellCastTargets::GetDstPos(), SpellCastTargets::HasDst(), m_spell, and Spell::m_targets.
Referenced by spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::CalculateDamage(), spell_valanar_kinetic_bomb::spell_valanar_kinetic_bomb_SpellScript::ChangeSummonPos(), spell_onslaught_or_call_bone_gryphon::spell_onslaught_or_call_bone_gryphon_SpellScript::ChangeSummonPos(), spell_rotface_unstable_ooze_explosion::spell_rotface_unstable_ooze_explosion_SpellScript::CheckTarget(), spell_q13086_last_line_of_defence::HandleAfterCast(), spell_dk_death_grip::HandleDummy(), spell_midsummer_fling_torch::HandleFinish(), spell_midsummer_juggling_torch::HandleFinish(), spell_wintergrasp_rp_gg::spell_wintergrasp_rp_gg_SpellScript::HandleFinish(), spell_rimefang_icy_blast::spell_rimefang_icy_blast_SpellScript::HandleTriggerMissile(), spell_ioc_launch::spell_ioc_launch_SpellScript::Launch(), spell_the_lich_king_teleport_to_frostmourne_hc::spell_the_lich_king_teleport_to_frostmourne_hc_SpellScript::ModDest(), spell_the_lich_king_summon_into_air::spell_the_lich_king_summon_into_air_SpellScript::ModDestHeight(), spell_the_lich_king_vile_spirits_visual::spell_the_lich_king_vile_spirits_visual_SpellScript::ModDestHeight(), spell_halion_summon_exit_portals::spell_halion_summon_exit_portals_SpellScript::OnSummon(), spell_anti_air_rocket_bomber::spell_anti_air_rocket_bomber_SpellScript::PrepareSpellScript(), spell_algalon_cosmic_smash_damage::spell_algalon_cosmic_smash_damage_SpellScript::RecalculateDamage(), spell_wg_reduce_damage_by_distance::spell_wg_reduce_damage_by_distance_SpellScript::RecalculateDamage(), spell_icc_soul_missile::spell_icc_soul_missile_SpellScript::RelocateDest(), spell_gen_relocaste_dest::RelocateDest(), spell_valanar_kinetic_bomb_summon::spell_valanar_kinetic_bomb_summon_SpellScript::SelectDest(), spell_putricide_slime_puddle_spawn::spell_putricide_slime_puddle_spawn_SpellScript::SelectDest(), and spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::SelectDest().
GetExplTargetGObj()
GameObject * SpellScript::GetExplTargetGObj ()
{
    return m_spell->m_targets.GetGOTarget();
}
References SpellCastTargets::GetGOTarget(), m_spell, and Spell::m_targets.
GetExplTargetItem()
Item * SpellScript::GetExplTargetItem ()
{
    return m_spell->m_targets.GetItemTarget();
}
References SpellCastTargets::GetItemTarget(), m_spell, and Spell::m_targets.
GetExplTargetUnit()
Unit * SpellScript::GetExplTargetUnit ()
{
    return m_spell->m_targets.GetUnitTarget();
}
References SpellCastTargets::GetUnitTarget(), m_spell, and Spell::m_targets.
Referenced by spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::CheckCast(), spell_dk_death_coil::CheckCast(), spell_dk_death_grip::CheckCast(), spell_gen_bandage::CheckCast(), spell_hun_tame_beast::CheckCast(), spell_pal_holy_shock::CheckCast(), spell_pal_lay_on_hands::CheckCast(), spell_pal_righteous_defense::CheckCast(), spell_pri_penance::CheckCast(), spell_pri_power_word_shield::CheckCast(), spell_q11065_wrangle_some_aether_rays::CheckCast(), spell_rog_pickpocket::CheckCast(), spell_brewfest_relay_race_force_cast::CheckItem(), spell_ooze_zap::spell_ooze_zap_SpellScript::CheckRequirement(), spell_putricide_mutation_init::spell_putricide_mutation_init_SpellScript::CheckRequirement(), spell_gen_disabled_above_level::CheckRequirement(), spell_gen_arcane_charge::CheckRequirement(), spell_putricide_mutation_init::spell_putricide_mutation_init_SpellScript::CheckRequirementInternal(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::CheckTarget(), spell_pal_hand_of_sacrifice::CheckTarget(), spell_hun_masters_call::DoCheckCast(), spell_mark_of_the_faceless_drainhealth::spell_mark_of_the_faceless_drainhealth_SpellScript::FilterTargets(), spell_dru_starfall_aoe::FilterTargets(), spell_dru_t10_restoration_4p_bonus::FilterTargets(), spell_cataclysm_breath::spell_cataclysm_breath_SpellScript::HandleAfterCast(), spell_dk_chains_of_ice::HandleAfterCast(), spell_dk_death_grip::HandleBaseDummy(), and spell_dk_pestilence::HandleScriptEffect().
GetExplTargetWorldObject()
WorldObject * SpellScript::GetExplTargetWorldObject ()
{
    return m_spell->m_targets.GetObjectTarget();
}
References SpellCastTargets::GetObjectTarget(), m_spell, and Spell::m_targets.
Referenced by spell_warr_intimidating_shout::FilterTargets().
GetHitAura()
Aura * SpellScript::GetHitAura ()
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::GetHitAura was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return nullptr;
    }
    if (!m_spell->m_spellAura)
        return nullptr;
    if (m_spell->m_spellAura->IsRemoved())
        return nullptr;
    return m_spell->m_spellAura;
}
References IsInTargetHook(), Aura::IsRemoved(), LOG_ERROR, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, m_spell, and Spell::m_spellAura.
Referenced by spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript::AddMissingStack(), spell_warl_haunt::HandleAfterHit(), spell_gen_mount::HandleMount(), spell_gen_bonked::HandleScript(), spell_taldaram_ball_of_inferno_flame::spell_taldaram_ball_of_inferno_flame_SpellScript::ModAuraStack(), and spell_deathbringer_blood_power::spell_deathbringer_blood_power_SpellScript::ModAuraValue().
GetHitCreature()
Creature * SpellScript::GetHitCreature ()
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::GetHitCreature was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return nullptr;
    }
    if (m_spell->unitTarget)
        return m_spell->unitTarget->ToCreature();
    else
        return nullptr;
}
References IsInTargetHook(), LOG_ERROR, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, m_spell, Object::ToCreature(), and Spell::unitTarget.
Referenced by spell_the_lich_king_trigger_vile_spirit::spell_the_lich_king_trigger_vile_spirit_SpellScript::ActivateSpirit(), spell_dk_death_grip::EntryCheck(), spell_serpentshrine_cavern_serpentshrine_parasite_trigger::spell_serpentshrine_cavern_serpentshrine_parasite_trigger_SpellScript::HandleApplyAura(), spell_dk_death_grip::HandleBaseDummy(), spell_q10935_the_exorcism_of_colonel_jules::spell_q10935_the_exorcism_of_colonel_jules_SpellScript::HandleDummy(), spell_item_lil_xt::HandleDummy(), spell_aggro_drones::HandleDummy(), spell_q12096_q12092_dummy::spell_q12096_q12092_dummy_SpellScript::HandleDummy(), spell_q12096_q12092_bark::spell_q12096_q12092_bark_SpellScript::HandleDummy(), spell_item_shimmering_vessel::HandleDummy(), spell_item_crystal_prison_dummy_dnd::HandleDummy(), spell_item_complete_raptor_capture::HandleDummy(), spell_item_impale_leviroth::HandleDummy(), spell_item_muisek_vessel::HandleDummy(), spell_q10714_on_spirits_wings::HandleDummy(), spell_generic_quest_update_entry_SpellScript::HandleDummy(), spell_q6124_6129_apply_salve::HandleDummy(), spell_q11396_11399_scourging_crystal_controller::HandleDummy(), spell_q11730_ultrasonic_screwdriver::HandleDummy(), spell_q12459_seeds_of_natures_wrath::HandleDummy(), spell_q12937_relief_for_the_fallen::HandleDummy(), spell_symbol_of_life_dummy::HandleDummy(), spell_q12659_ahunaes_knife::HandleDummy(), spell_q9874_liquid_fire::HandleDummy(), spell_q12277_wintergarde_mine_explosion::HandleDummy(), spell_q12066_bunny_kill_credit::HandleDummy(), spell_q13291_q13292_q13239_q13261_frostbrood_skytalon_grab_decoy::HandleDummy(), spell_q12641_death_comes_from_on_high::HandleDummy(), spell_algalon_trigger_3_adds::spell_algalon_trigger_3_adds_SpellScript::HandleDummyEffect(), spell_halion_twilight_mending::spell_halion_twilight_mending_SpellScript::HandleHealPct(), spell_q12726_song_of_wind_and_water::spell_q12726_song_of_wind_and_water_SpellScript::HandleHealPct(), spell_item_toxic_wasteling::HandleJump(), spell_q12690_burst_at_the_seams::HandleKnockBack(), spell_the_lich_king_jump::spell_the_lich_king_jump_SpellScript::HandleScript(), spell_svalna_remove_spear::spell_svalna_remove_spear_SpellScript::HandleScript(), spell_putricide_eat_ooze::spell_putricide_eat_ooze_SpellScript::HandleScript(), spell_rotface_little_ooze_combine::spell_rotface_little_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_combine::spell_rotface_large_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_buff_combine::spell_rotface_large_ooze_buff_combine_SpellScript::HandleScript(), spell_q12805_lifeblood_dummy::HandleScript(), spell_q12919_gymers_grab::HandleScript(), spell_illidan_parasitic_shadowfiend_trigger::spell_illidan_parasitic_shadowfiend_trigger_SpellScript::HandleScriptEffect(), spell_illidan_cage_trap::spell_illidan_cage_trap_SpellScript::HandleScriptEffect(), spell_item_sleepy_willy::HandleScriptEffect(), spell_item_lil_xt::HandleScriptEffect(), spell_death_knight_initiate_visual::HandleScriptEffect(), spell_winter_veil_racer_slam_hit::HandleScriptEffect(), spell_warl_demonic_empowerment::HandleScriptEffect(), and spell_valanar_kinetic_bomb_knockback::spell_valanar_kinetic_bomb_knockback_SpellScript::KnockIntoAir().
GetHitDamage()
int32 SpellScript::GetHitDamage ()
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::GetHitDamage was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return 0;
    }
    return m_spell->m_damage;
}
References IsInTargetHook(), LOG_ERROR, Spell::m_damage, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and m_spell.
Referenced by spell_blood_council_shadow_prison_damage::spell_blood_council_shadow_prison_SpellScript::AddExtraDamage(), spell_oculus_shock_lance::spell_oculus_shock_lance_SpellScript::CalcDamage(), spell_krystallus_shatter_effect::spell_krystallus_shatter_effect_SpellScript::CalculateDamage(), spell_gruul_shatter_effect::spell_gruul_shatter_effect_SpellScript::CalculateDamage(), spell_item_wraith_scythe_drain_life::CalculateDamage(), spell_loken_pulsing_shockwave::spell_loken_pulsing_shockwave_SpellScript::CalculateDamage(), spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript::ChangeDamageAndGrow(), spell_gen_leeching_swarm_dmg::spell_gen_leeching_swarm_dmg_SpellScript::HandleAfterHit(), spell_saronite_vapors_damage::spell_saronite_vapors_damage_SpellScript::HandleAfterHit(), spell_dk_scourge_strike::HandleAfterHit(), spell_warl_haunt::HandleAfterHit(), spell_pri_shadow_word_death::HandleDamage(), spell_sha_lava_lash::HandleDummy(), spell_voa_lightning_nova::spell_voa_lightning_nova_SpellScript::HandleOnHit(), spell_xt002_gravity_bomb_damage::spell_xt002_gravity_bomb_damage_SpellScript::HandleScript(), spell_bronjahm_magic_bane::spell_bronjahm_magic_bane_SpellScript::RecalculateDamage(), spell_marrowgar_bone_storm::spell_marrowgar_bone_storm_SpellScript::RecalculateDamage(), spell_algalon_cosmic_smash_damage::spell_algalon_cosmic_smash_damage_SpellScript::RecalculateDamage(), spell_xt002_tympanic_tantrum::spell_xt002_tympanic_tantrum_SpellScript::RecalculateDamage(), spell_wg_reduce_damage_by_distance::spell_wg_reduce_damage_by_distance_SpellScript::RecalculateDamage(), spell_pet_gen_valkyr_guardian_smite::RecalculateDamage(), spell_dk_death_and_decay::RecalculateDamage(), spell_gen_reduced_above_60::RecalculateDamage(), spell_gen_count_pct_from_max_hp::RecalculateDamage(), spell_marrowgar_bone_slice::spell_marrowgar_bone_slice_SpellScript::SplitDamage(), spell_the_lich_king_life_siphon::spell_the_lich_king_life_siphon_SpellScript::TriggerHeal(), and spell_pal_divine_storm::TriggerHeal().
GetHitDest()
WorldLocation * SpellScript::GetHitDest ()
{
    if (!IsInEffectHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::GetHitDest was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return nullptr;
    }
    return m_spell->destTarget;
}
References Spell::destTarget, IsInEffectHook(), LOG_ERROR, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and m_spell.
Referenced by spell_valanar_kinetic_bomb::spell_valanar_kinetic_bomb_SpellScript::ChangeSummonPos(), spell_onslaught_or_call_bone_gryphon::spell_onslaught_or_call_bone_gryphon_SpellScript::ChangeSummonPos(), spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript::HandleSummon(), spell_the_lich_king_teleport_to_frostmourne_hc::spell_the_lich_king_teleport_to_frostmourne_hc_SpellScript::ModDest(), spell_the_lich_king_summon_into_air::spell_the_lich_king_summon_into_air_SpellScript::ModDestHeight(), spell_halion_summon_exit_portals::spell_halion_summon_exit_portals_SpellScript::OnSummon(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::RelocateDest(), and spell_igb_teleport_to_enemy_ship::spell_igb_teleport_to_enemy_ship_SpellScript::RelocateTransportOffset().
GetHitGObj()
GameObject * SpellScript::GetHitGObj ()
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::GetHitGObj was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return nullptr;
    }
    return m_spell->gameObjTarget;
}
References Spell::gameObjTarget, IsInTargetHook(), LOG_ERROR, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and m_spell.
Referenced by spell_gen_seaforium_blast::AchievementCredit(), spell_madrigosa_activate_barrier::spell_madrigosa_activate_barrier_SpellScript::HandleActivateObject(), spell_madrigosa_deactivate_barrier::spell_madrigosa_deactivate_barrier_SpellScript::HandleActivateObject(), spell_item_light_lamp::HandleActivateObject(), spell_q9452_cast_net::HandleActiveObject(), spell_egg_event::spell_egg_eventSpellScript::HandleOnHit(), spell_zulfarrak_unlocking::spell_zulfarrak_unlocking_SpellScript::HandleOpenLock(), and spell_item_freeze_rookery_egg::HandleOpenObject().
GetHitHeal()
int32 SpellScript::GetHitHeal ()
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::GetHitHeal was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return 0;
    }
    return m_spell->m_healing;
}
References IsInTargetHook(), LOG_ERROR, Spell::m_healing, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and m_spell.
Referenced by spell_item_runic_healing_injector::HandleHeal(), and spell_sha_chain_heal::HandleHeal().
GetHitItem()
Item * SpellScript::GetHitItem ()
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::GetHitItem was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return nullptr;
    }
    return m_spell->itemTarget;
}
References IsInTargetHook(), Spell::itemTarget, LOG_ERROR, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and m_spell.
Referenced by spell_q1846_bending_shinbone::HandleScriptEffect().
GetHitPlayer()
Player * SpellScript::GetHitPlayer ()
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::GetHitPlayer was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return nullptr;
    }
    if (m_spell->unitTarget)
        return m_spell->unitTarget->ToPlayer();
    else
        return nullptr;
}
References IsInTargetHook(), LOG_ERROR, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, m_spell, Object::ToPlayer(), and Spell::unitTarget.
Referenced by spell_eredar_twins_apply_dark_touched::spell_eredar_twins_apply_dark_touched_SpellScript::HandleApplyTouch(), spell_eredar_twins_apply_flame_touched::spell_eredar_twins_apply_flame_touched_SpellScript::HandleApplyTouch(), spell_midsummer_juggling_torch::HandleDummy(), spell_hallows_end_candy::HandleDummy(), spell_hallows_end_bucket_lands::HandleDummy(), spell_midsummer_torch_catch::HandleDummy(), spell_warhead_detonate::spell_warhead_detonate_SpellScript::HandleDummy(), spell_dk_raise_ally::HandleDummy(), spell_q11010_q11102_q11023_aggro_check::HandleDummy(), spell_yogg_saron_insane_periodic_trigger::spell_yogg_saron_insane_periodic_trigger_SpellScript::HandleDummyEffect(), spell_oscillating_field::spell_oscillating_field_SpellScript::HandleEffect(), spell_warr_overpower::HandleEffect(), spell_sindragosa_frost_breath::spell_sindragosa_frost_breath_SpellScript::HandleInfusion(), spell_ulduar_squeezed_lifeless::spell_ulduar_squeezed_lifeless_SpellScript::HandleInstaKill(), spell_gen_mount::HandleMount(), spell_gen_mine_sweeper::HandleSchoolDMG(), spell_midsummer_fling_torch::HandleScript(), spell_the_lich_king_play_movie::spell_the_lich_king_play_movie_SpellScript::HandleScript(), spell_wintergrasp_portal::spell_wintergrasp_portal_SpellScript::HandleScript(), spell_gen_create_lance::HandleScript(), spell_gen_upper_deck_create_foam_sword::HandleScript(), spell_item_piccolo_of_the_flaming_fire::HandleScript(), spell_q10041_q10040_who_are_they::HandleScript(), spell_warr_vigilance_trigger::HandleScript(), spell_hallows_end_trick::HandleScript(), spell_hallows_end_put_costume::HandleScript(), spell_hallows_end_trick_or_treat::HandleScript(), spell_hallows_end_tricky_treat::HandleScript(), spell_winter_veil_mistletoe::HandleScript(), spell_ioc_launch::spell_ioc_launch_SpellScript::HandleScript(), spell_gen_5000_gold::HandleScript(), spell_the_flag_of_ownership::HandleScript(), spell_gen_dalaran_disguise::HandleScript(), spell_gen_bonked::HandleScript(), spell_q13011_bear_flank_master::HandleScript(), spell_kiljaeden_power_of_the_blue_flight::spell_kiljaeden_power_of_the_blue_flight_SpellScript::HandleScriptEffect(), spell_yogg_saron_sanity_reduce::spell_yogg_saron_sanity_reduce_SpellScript::HandleScriptEffect(), spell_lady_vashj_remove_tainted_cores::spell_lady_vashj_remove_tainted_cores_SpellScript::HandleScriptEffect(), spell_kaelthas_gravity_lapse::spell_kaelthas_gravity_lapse_SpellScript::HandleScriptEffect(), spell_razelikh_teleport_group::spell_razelikh_teleport_group_SpellScript::HandleScriptEffect(), spell_blood_siphon::HandleScriptEffect(), spell_pilgrims_bounty_turkey_tracker::HandleScriptEffect(), spell_winter_wondervolt_trap::HandleScriptEffect(), spell_volazj_whisper::HandleScriptEffect(), spell_gen_mine_sweeper::HandleScriptEffect(), spell_gen_tournament_duel::HandleScriptEffect(), spell_ioc_launch::spell_ioc_launch_SpellScript::Launch(), spell_item_branns_communicator::PrepareSpellScript(), and spell_algalon_supermassive_fail::spell_algalon_supermassive_fail_SpellScript::RecalculateDamage().
GetHitUnit()
Unit * SpellScript::GetHitUnit ()
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::GetHitUnit was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return nullptr;
    }
    return m_spell->unitTarget;
}
References IsInTargetHook(), LOG_ERROR, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, m_spell, and Spell::unitTarget.
Referenced by spell_blood_council_shadow_prison_damage::spell_blood_council_shadow_prison_SpellScript::AddExtraDamage(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript::AddMissingStack(), spell_sha_bloodlust::ApplyDebuff(), spell_sha_heroism::ApplyDebuff(), spell_oculus_shock_lance::spell_oculus_shock_lance_SpellScript::CalcDamage(), spell_krystallus_shatter_effect::spell_krystallus_shatter_effect_SpellScript::CalculateDamage(), spell_gruul_shatter_effect::spell_gruul_shatter_effect_SpellScript::CalculateDamage(), spell_item_wraith_scythe_drain_life::CalculateDamage(), spell_loken_pulsing_shockwave::spell_loken_pulsing_shockwave_SpellScript::CalculateDamage(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript::CheckAura(), spell_baltharus_enervating_brand_trigger::spell_baltharus_enervating_brand_trigger_SpellScript::CheckDistance(), spell_gen_eject_passenger::EjectPassenger(), spell_saronite_vapors_damage::spell_saronite_vapors_damage_SpellScript::HandleAfterHit(), spell_dk_blood_boil::HandleAfterHit(), spell_pri_mana_burn::HandleAfterHit(), spell_rog_deadly_poison::HandleAfterHit(), spell_azjol_nerub_pound::HandleApplyAura(), spell_galdarah_impaling_charge::spell_galdarah_impaling_charge_SpellScript::HandleApplyAura(), spell_warr_intervene::HandleApplyAura(), spell_warl_banish::HandleBanish(), spell_dk_death_grip::HandleBaseDummy(), spell_brewfest_toss_mug::HandleBeforeHit(), spell_rog_deadly_poison::HandleBeforeHit(), spell_rotface_unstable_ooze_explosion_init::spell_rotface_unstable_ooze_explosion_init_SpellScript::HandleCast(), spell_gen_mounted_charge::HandleChargeEffect(), spell_dk_corpse_explosion::HandleCorpseExplosion(), spell_warr_bloodthirst::HandleDamage(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleDamage(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::HandleDamage(), spell_rajaxx_thundercrash::HandleDamageCalc(), spell_moroes_vanish::spell_moroes_vanish_SpellScript::HandleDummy(), spell_karazhan_blink::spell_karazhan_blink_SpellScript::HandleDummy(), spell_kalecgos_spectral_blast_dummy::spell_kalecgos_spectral_blast_dummy_SpellScript::HandleDummy(), spell_ooze_zap::spell_ooze_zap_SpellScript::HandleDummy(), spell_ooze_zap_channel_end::spell_ooze_zap_channel_end_SpellScript::HandleDummy(), spell_saviana_conflagration_init::spell_saviana_conflagration_init_SpellScript::HandleDummy(), spell_igb_burning_pitch_selector::spell_igb_burning_pitch_selector_SpellScript::HandleDummy(), spell_igb_burning_pitch::spell_igb_burning_pitch_SpellScript::HandleDummy(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::HandleDummy(), spell_illidan_glaive_throw::spell_illidan_glaive_throw_SpellScript::HandleDummy(), spell_illidan_found_target::spell_illidan_found_target_SpellScript::HandleDummy(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::HandleDummy(), spell_leotheras_chaos_blast::spell_leotheras_chaos_blast_SpellScript::HandleDummy(), spell_morogrim_tidewalker_watery_grave::spell_morogrim_tidewalker_watery_grave_SpellScript::HandleDummy(), spell_morogrim_tidewalker_water_globule_new_target::spell_morogrim_tidewalker_water_globule_new_target_SpellScript::HandleDummy(), spell_gen_hate_to_zero::HandleDummy(), spell_gen_focused_bursts::HandleDummy(), spell_item_powerful_anti_venom::HandleDummy(), spell_item_strong_anti_venom::HandleDummy(), spell_item_anti_venom::HandleDummy(), spell_mage_burnout_trigger::HandleDummy(), spell_sha_healing_stream_totem::HandleDummy(), spell_magmadar_lava_bomb::spell_magmadar_lava_bomb_SpellScript::HandleDummy(), spell_send_mug_target_picker::HandleDummy(), spell_hallows_end_bucket_lands::HandleDummy(), spell_pilgrims_bounty_pass_generic::HandleDummy(), spell_mana_burn_area::HandleDummy(), spell_voljin_war_drums::spell_voljin_war_drums_SpellScript::HandleDummy(), spell_voodoo::spell_voodoo_SpellScript::HandleDummy(), spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::HandleDummy(), spell_halion_meteor_strike_targeting::spell_halion_meteor_strike_targeting_SpellScript::HandleDummy(), spell_pos_slave_trigger_closest::spell_pos_slave_trigger_closestSpellScript::HandleDummy(), spell_pos_rimefang_frost_nova::spell_pos_rimefang_frost_novaSpellScript::HandleDummy(), spell_drakkari_colossus_surge::spell_drakkari_colossus_surge_SpellScript::HandleDummy(), spell_deathbringer_blood_link::spell_deathbringer_blood_link_SpellScript::HandleDummy(), spell_putricide_ooze_eruption_searcher::spell_putricide_ooze_eruption_searcher_SpellScript::HandleDummy(), spell_thaddius_polarity_shift::spell_thaddius_polarity_shift_SpellScript::HandleDummy(), spell_voa_flaming_cinder::spell_voa_flaming_cinder_SpellScript::HandleDummy(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_mother_shahraz_fatal_attraction_dummy::spell_mother_shahraz_fatal_attraction_dummy_SpellScript::HandleDummy(), spell_najentus_needle_spine::spell_najentus_needle_spine_SpellScript::HandleDummy(), spell_capacitus_polarity_shift::spell_capacitus_polarity_shift_SpellScript::HandleDummy(), spell_dk_death_coil::HandleDummy(), spell_dk_death_grip::HandleDummy(), spell_dk_death_strike::HandleDummy(), spell_dk_scourge_strike::HandleDummy(), spell_dru_starfall_dummy::HandleDummy(), spell_gen_dummy_trigger::HandleDummy(), spell_gen_spirit_healer_res::HandleDummy(), spell_hun_masters_call::HandleDummy(), spell_item_gnomish_universal_remote::HandleDummy(), spell_item_gnomish_shrink_ray::HandleDummy(), spell_item_net_o_matic::HandleDummy(), spell_item_six_demon_bag::HandleDummy(), spell_item_poultryizer::HandleDummy(), spell_item_chicken_cover::HandleDummy(), spell_item_greatmothers_soulcatcher::HandleDummy(), spell_pal_blessing_of_faith::HandleDummy(), spell_pal_divine_storm_dummy::HandleDummy(), spell_pal_holy_shock::HandleDummy(), spell_pal_judgement_of_command::HandleDummy(), spell_pri_penance::HandleDummy(), spell_q11396_11399_scourging_crystal_controller_dummy::HandleDummy(), spell_q11587_arcane_prisoner_rescue::HandleDummy(), spell_rog_killing_spree::spell_rog_killing_spree_SpellScript::HandleDummy(), spell_rog_shiv::HandleDummy(), spell_sha_ancestral_awakening_proc::HandleDummy(), spell_sha_cleansing_totem_pulse::HandleDummy(), spell_sha_mana_spring_totem::HandleDummy(), spell_sha_mana_tide_totem::HandleDummy(), spell_warl_soulshatter::HandleDummy(), spell_warl_life_tap::HandleDummy(), spell_warr_deep_wounds::HandleDummy(), spell_warr_slam::HandleDummy(), spell_yogg_saron_destabilization_matrix::spell_yogg_saron_destabilization_matrix_SpellScript::HandleDummyEffect(), spell_yogg_saron_titanic_storm::spell_yogg_saron_titanic_storm_SpellScript::HandleDummyEffect(), spell_brewfest_apple_trap::HandleDummyEffect(), spell_brewfest_add_mug::HandleDummyEffect(), spell_svala_ritual_strike::spell_svala_ritual_strike_SpellScript::HandleDummyEffect(), spell_egg_explosion::HandleDummyHitTarget(), spell_warr_execute::HandleEffect(), spell_mark_of_nature::spell_mark_of_nature_SpellScript::HandleEffect(), spell_axe_flurry::HandleEffect(), spell_dream_fog_sleep::spell_dream_fog_sleep_SpellScript::HandleEffect(), spell_bwl_shadowflame::spell_bwl_shadowflame_SpellScript::HandleEffectScriptEffect(), spell_pri_pain_and_suffering_proc::HandleEffectScriptEffect(), spell_halion_blazing_aura::spell_halion_blazing_aura_SpellScript::HandleForceCast(), spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript::HandleForceCast(), spell_dreamwalker_summon_suppresser_effect::spell_dreamwalker_summon_suppresser_effect_SpellScript::HandleForceCast(), spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript::HandleForcedCast(), spell_sha_chain_heal::HandleHeal(), spell_garr_frenzy::spell_garr_frenzy_SpellScript::HandleHit(), spell_red_sky_effect::spell_red_sky_effect_SpellScript::HandleHit(), spell_finger_of_death::spell_finger_of_death_SpellScript::HandleHit(), spell_hand_of_death::spell_hand_of_death_SpellScript::HandleHit(), spell_item_massive_seaforium_charge::HandleItemRemove(), spell_chapter5_rebuke::spell_chapter5_rebuke_SpellScript::HandleLeapBack(), spell_random_aggro::HandleOnHit(), spell_enveloping_webs::HandleOnHit(), spell_arcane_vacuum::HandleOnHit(), spell_mark_of_frost_freeze::HandleOnHit(), spell_mutate_explode_bug::HandleOnHit(), spell_summon_toxin_slime::HandleOnHit(), spell_voa_lightning_nova::spell_voa_lightning_nova_SpellScript::HandleOnHit(), spell_warr_mocking_blow::HandleOnHit(), spell_class_call_handler::HandleOnHitRogue(), spell_class_call_handler::HandleOnHitWarlock(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::HandlePresence(), spell_item_magic_dust::HandlePreventAura(), spell_entropius_black_hole_effect::spell_entropius_black_hole_effect_SpellScript::HandlePull(), spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript::HandlePull(), spell_icc_harvest_blight_specimen::spell_icc_harvest_blight_specimen_SpellScript::HandleQuestComplete(), spell_dk_raise_dead::HandleRaiseDead(), spell_kiljaeden_flame_dart::spell_kiljaeden_flame_dart_SpellScript::HandleSchoolDamage(), spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::HandleSchoolDamage(), spell_najentus_hurl_spine::spell_najentus_hurl_spine_SpellScript::HandleSchoolDamage(), spell_warl_shadowflame::HandleSchoolDMG(), spell_gen_bandage::HandleScript(), spell_pal_lay_on_hands::HandleScript(), spell_eredar_twins_blaze::spell_eredar_twins_blaze_SpellScript::HandleScript(), spell_item_create_heart_candy::HandleScript(), spell_saviana_conflagration_throwback::spell_saviana_conflagration_throwback_SpellScript::HandleScript(), spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::HandleScript(), spell_blood_queen_presence_of_the_darkfallen::spell_blood_queen_presence_of_the_darkfallen_SpellScript::HandleScript(), spell_igb_rocket_artillery::spell_igb_rocket_artillery_SpellScript::HandleScript(), spell_putricide_clear_aura_effect_value::spell_putricide_clear_aura_effect_value_SpellScript::HandleScript(), spell_sindragosa_icy_grip::spell_sindragosa_icy_grip_SpellScript::HandleScript(), spell_frostwarden_handler_focus_fire::spell_frostwarden_handler_focus_fire_SpellScript::HandleScript(), spell_the_lich_king_jump::spell_the_lich_king_jump_SpellScript::HandleScript(), spell_the_lich_king_jump_remove_aura::spell_the_lich_king_jump_SpellScript::HandleScript(), spell_the_lich_king_raging_spirit::spell_the_lich_king_raging_spirit_SpellScript::HandleScript(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::HandleScript(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::HandleScript(), spell_the_lich_king_summon_spirit_bomb::spell_the_lich_king_summon_spirit_bomb_SpellScript::HandleScript(), spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript::HandleScript(), spell_dreamwalker_twisted_nightmares::spell_dreamwalker_twisted_nightmares_SpellScript::HandleScript(), spell_icc_harvest_blight_specimen::spell_icc_harvest_blight_specimen_SpellScript::HandleScript(), spell_archavon_rock_shards::spell_archavon_rock_shards_SpellScript::HandleScript(), spell_q24545_aod_special::spell_q24545_aod_special_SpellScript::HandleScript(), spell_wintergrasp_force_building::spell_wintergrasp_force_building_SpellScript::HandleScript(), spell_dk_death_gate::HandleScript(), spell_gen_netherbloom::HandleScript(), spell_gen_nightmare_vine::HandleScript(), spell_warr_shattering_throw::HandleScript(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::HandleScript(), spell_apothecary_lingering_fumes::HandleScript(), spell_apothecary_validate_area::HandleScript(), spell_apothecary_throw_cologne::HandleScript(), spell_apothecary_throw_perfume::HandleScript(), spell_blight_worm_ingest::spell_blight_worm_ingest_SpellScript::HandleScript(), spell_moam_mana_drain_filter::HandleScript(), spell_drain_mana::HandleScript(), spell_mistress_kiss_area::spell_mistress_kiss_area_SpellScript::HandleScript(), spell_tharon_ja_clear_gift_of_tharon_ja::spell_tharon_ja_clear_gift_of_tharon_ja_SpellScript::HandleScript(), spell_festergut_gastric_bloat::spell_festergut_gastric_bloat_SpellScript::HandleScript(), spell_putricide_slime_puddle::spell_putricide_slime_puddle_SpellScript::HandleScript(), spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::HandleScript(), spell_the_lich_king_cast_back_to_caster::spell_the_lich_king_cast_back_to_caster_SpellScript::HandleScript(), spell_frost_giant_death_plague::spell_frost_giant_death_plague_SpellScript::HandleScript(), spell_stinky_precious_decimate::spell_stinky_precious_decimate_SpellScript::HandleScript(), spell_krystallus_shatter::spell_krystallus_shatter_SpellScript::HandleScript(), spell_ignis_grab_initial::spell_ignis_grab_initial_SpellScript::HandleScript(), spell_xt002_gravity_bomb_damage::spell_xt002_gravity_bomb_damage_SpellScript::HandleScript(), spell_yogg_saron_target_selectors::spell_yogg_saron_target_selectors_SpellScript::HandleScript(), spell_q12237_rescue_villager::HandleScript(), spell_shango_tracks::spell_shango_tracks_SpellScript::HandleScript(), spell_despawn_underbog_mushrooms::HandleScript(), spell_the_black_stalker_levitate::HandleScript(), spell_the_black_stalker_someone_grab_me::HandleScript(), spell_the_black_stalker_magnetic_pull::HandleScript(), spell_gen_clear_debuffs::HandleScript(), spell_gen_remove_flight_auras::HandleScript(), spell_gen_elune_candle::HandleScript(), spell_gen_teleporting::HandleScript(), spell_gen_ds_flush_knockback::HandleScript(), spell_item_brittle_armor::HandleScript(), spell_item_mercurial_shield::HandleScript(), spell_item_eggnog::HandleScript(), spell_item_worn_troll_dice::HandleScript(), spell_q12274_a_fall_from_grace_costume::HandleScript(), spell_q12641_death_comes_from_on_high_summon_ghouls::spell_q12641_death_comes_from_on_high_summon_ghouls_SpellScript::HandleScriptEffect(), spell_brutallus_burn::spell_brutallus_burn_SpellScript::HandleScriptEffect(), spell_felmyst_fog_of_corruption::spell_felmyst_fog_of_corruption_SpellScript::HandleScriptEffect(), spell_kiljaeden_sinister_reflection::spell_kiljaeden_sinister_reflection_SpellScript::HandleScriptEffect(), spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript::HandleScriptEffect(), spell_batrider_bomb::HandleScriptEffect(), spell_vem_knockback::HandleScriptEffect(), spell_azjol_nerub_fixate::spell_azjol_nerub_fixate_SpellScript::HandleScriptEffect(), spell_yogg_saron_empowering_shadows::spell_yogg_saron_empowering_shadows_SpellScript::HandleScriptEffect(), spell_gurtogg_eject::spell_gurtogg_eject_SpellScript::HandleScriptEffect(), spell_illidan_draw_soul::spell_illidan_draw_soul_SpellScript::HandleScriptEffect(), spell_illidan_flame_burst::spell_illidan_flame_burst_SpellScript::HandleScriptEffect(), spell_black_template_free_friend::spell_black_template_free_friend_SpellScript::HandleScriptEffect(), spell_black_temple_bloodbolt::spell_black_temple_bloodbolt_SpellScript::HandleScriptEffect(), spell_lady_vashj_spore_drop_effect::spell_lady_vashj_spore_drop_effect_SpellScript::HandleScriptEffect(), spell_leotheras_clear_consuming_madness::spell_leotheras_clear_consuming_madness_SpellScript::HandleScriptEffect(), spell_tsh_shoot_flame_arrow::spell_tsh_shoot_flame_arrow_SpellScript::HandleScriptEffect(), spell_gen_fixate::HandleScriptEffect(), spell_gen_knock_away::HandleScriptEffect(), spell_gen_throw_back::HandleScriptEffect(), spell_gen_clone::HandleScriptEffect(), spell_gen_clone_weapon::HandleScriptEffect(), spell_gen_break_shield::HandleScriptEffect(), spell_gen_mounted_charge::HandleScriptEffect(), spell_gen_throw_shield::HandleScriptEffect(), spell_warl_create_healthstone::HandleScriptEffect(), spell_q12698_the_gift_that_keeps_on_giving::spell_q12698_the_gift_that_keeps_on_giving_SpellScript::HandleScriptEffect(), spell_q12779_an_end_to_all_things::HandleScriptEffect(), spell_brewfest_toss_mug::HandleScriptEffect(), spell_direbrew_summon_mole_machine_target_picker::HandleScriptEffect(), spell_request_second_mug::HandleScriptEffect(), spell_pilgrims_bounty_food::HandleScriptEffect(), spell_winter_veil_shoot_air_rifle::HandleScriptEffect(), spell_halion_clear_debuffs::spell_halion_clear_debuffs_SpellScript::HandleScriptEffect(), spell_novos_despawn_crystal_handler::spell_novos_despawn_crystal_handler_SpellScript::HandleScriptEffect(), spell_trollgore_consume::spell_trollgore_consume_SpellScript::HandleScriptEffect(), spell_trollgore_invader_taunt::spell_trollgore_invader_taunt_SpellScript::HandleScriptEffect(), spell_drakkari_colossus_face_me::spell_drakkari_colossus_face_me_SpellScript::HandleScriptEffect(), spell_galdarah_transform::spell_galdarah_transform_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_gluth_decimate::spell_gluth_decimate_SpellScript::HandleScriptEffect(), spell_arcane_chains_character_force_cast::spell_arcane_chains_character_force_cast_SpellScript::HandleScriptEffect(), spell_q12611_deathbolt::HandleScriptEffect(), spell_q12823_remove_collapsing_cave_aura::HandleScriptEffect(), spell_illidari_council_judgement::spell_illidari_council_judgement_SpellScript::HandleScriptEffect(), spell_gruul_ground_slam::spell_gruul_ground_slam_SpellScript::HandleScriptEffect(), spell_gruul_shatter::spell_gruul_shatter_SpellScript::HandleScriptEffect(), spell_vazruden_fireball::spell_vazruden_fireball_SpellScript::HandleScriptEffect(), spell_vazruden_call_nazan::spell_vazruden_call_nazan_SpellScript::HandleScriptEffect(), spell_magtheridon_blaze::spell_magtheridon_blaze_SpellScript::HandleScriptEffect(), spell_dk_pestilence::HandleScriptEffect(), spell_dru_glyph_of_starfire::HandleScriptEffect(), spell_gen_tournament_duel::HandleScriptEffect(), spell_gen_remove_impairing_auras::HandleScriptEffect(), spell_hun_chimera_shot::HandleScriptEffect(), spell_hun_invigoration::HandleScriptEffect(), spell_hun_masters_call::HandleScriptEffect(), spell_item_goblin_weather_machine::HandleScriptEffect(), spell_pal_judgement::HandleScriptEffect(), spell_pri_lightwell::HandleScriptEffect(), spell_q11026_a11051_banish_the_demons::HandleScriptEffect(), spell_q10720_the_smallest_creature::HandleScriptEffect(), spell_q10769_dissension_amongst_the_ranks::HandleScriptEffect(), spell_warl_everlasting_affliction::HandleScriptEffect(), spell_sindragosa_icy_grip_jump::spell_sindragosa_icy_grip_jump_SpellScript::HandleSpecial(), spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::HandleTeleportUnits(), spell_trigger_spell_from_caster::spell_trigger_spell_from_caster_SpellScript::HandleTrigger(), spell_pal_righteous_defense::HandleTriggerSpellHit(), spell_gahzranka_slam::HandleWipeThreat(), spell_threatening_gaze_charge::LaunchHit(), spell_mandokir_charge::LaunchHit(), spell_rotface_mutated_infection::spell_rotface_mutated_infection_SpellScript::NotifyTargets(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::OnCast(), spell_item_linken_boomerang::OnEffectLaunchTargetDisarm(), spell_item_linken_boomerang::OnEffectLaunchTargetStun(), spell_dru_tiger_s_fury::OnHit(), spell_item_direbrew_remote::PrepareSpellScript(), spell_item_mind_amplify_dish::PrepareSpellScript(), spell_item_runescroll_of_fortitude::PrepareSpellScript(), spell_item_toy_train_set::PrepareSpellScript(), spell_q11198_take_down_tethyr::PrepareSpellScript(), spell_q11653_youre_not_so_big_now::PrepareSpellScript(), spell_bronjahm_magic_bane::spell_bronjahm_magic_bane_SpellScript::RecalculateDamage(), spell_marrowgar_bone_storm::spell_marrowgar_bone_storm_SpellScript::RecalculateDamage(), spell_algalon_cosmic_smash_damage::spell_algalon_cosmic_smash_damage_SpellScript::RecalculateDamage(), spell_xt002_tympanic_tantrum::spell_xt002_tympanic_tantrum_SpellScript::RecalculateDamage(), spell_wg_reduce_damage_by_distance::spell_wg_reduce_damage_by_distance_SpellScript::RecalculateDamage(), spell_murmur_sonic_boom_effect::spell_murmur_sonic_boom_effect_SpellScript::RecalculateDamage(), spell_pet_gen_valkyr_guardian_smite::RecalculateDamage(), spell_dk_death_and_decay::RecalculateDamage(), spell_gen_reduced_above_60::RecalculateDamage(), spell_gen_count_pct_from_max_hp::RecalculateDamage(), spell_igb_teleport_to_enemy_ship::spell_igb_teleport_to_enemy_ship_SpellScript::RelocateTransportOffset(), spell_igb_below_zero::spell_igb_below_zero_SpellScript::RemovePassengers(), spell_gen_eject_all_passengers::RemoveVehicleAuras(), spell_warr_slam::SendMiss(), spell_warr_execute::SendMiss(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::StartAttack(), spell_dk_ghoul_explode::Suicide(), spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::TeleportPlayer(), spell_the_lich_king_life_siphon::spell_the_lich_king_life_siphon_SpellScript::TriggerHeal(), spell_pal_divine_storm::TriggerHeal(), and spell_warr_victory_rush::VictoryRushHit().
GetOriginalCaster()
Unit * SpellScript::GetOriginalCaster ()
{
    return m_spell->GetOriginalCaster();
}
References Spell::GetOriginalCaster(), and m_spell.
Referenced by spell_gen_seaforium_blast::AchievementCredit(), spell_baltharus_enervating_brand_trigger::spell_baltharus_enervating_brand_trigger_SpellScript::CheckDistance(), spell_sha_healing_stream_totem::HandleDummy(), spell_gen_spirit_healer_res::HandleDummy(), spell_sha_cleansing_totem_pulse::HandleDummy(), spell_sha_mana_spring_totem::HandleDummy(), spell_sha_mana_tide_totem::HandleDummy(), spell_warr_execute::HandleEffect(), spell_pri_prayer_of_mending_heal::HandleHeal(), spell_q12698_the_gift_that_keeps_on_giving::spell_q12698_the_gift_that_keeps_on_giving_SpellScript::HandleScriptEffect(), spell_winter_veil_shoot_air_rifle::HandleScriptEffect(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript::HandleSummon(), spell_gen_seaforium_blast::Load(), and spell_gen_spirit_healer_res::Load().
GetSpell()
Spell * SpellScript::GetSpell () inline
{ return m_spell; }
References m_spell.
Referenced by spell_dk_raise_dead::CheckCast(), spell_dk_raise_dead::CheckTargets(), spell_ruby_sanctum_rallying_shout::spell_ruby_sanctum_rallying_shout_SpellScript::CountAllies(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::HandleAfterCast(), spell_dk_chains_of_ice::HandleAfterCast(), spell_brewfest_fill_keg::HandleAfterHit(), spell_brewfest_unfill_keg::HandleAfterHit(), spell_dk_corpse_explosion::HandleDamage(), spell_mage_burnout_trigger::HandleDummy(), spell_pvp_trinket_wotf_shared_cd::HandleScript(), spell_item_draenic_pale_ale::HandleSummon(), spell_ioc_launch::spell_ioc_launch_SpellScript::Launch(), spell_gen_mod_radius_by_caster_scale::PrepareSpellScript(), spell_pet_gen_valkyr_guardian_smite::RecalculateDamage(), spell_dk_rune_of_the_fallen_crusader::RecalculateDamage(), spell_quest_dragonmaw_race_generic::RelocateDest(), and spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::SetDest().
GetSpellInfo()
SpellInfo const * SpellScript::GetSpellInfo ()
{
    return m_spell->GetSpellInfo();
}
References Spell::GetSpellInfo(), and m_spell.
Referenced by spell_blood_council_shadow_prison_damage::spell_blood_council_shadow_prison_SpellScript::AddExtraDamage(), spell_krystallus_shatter_effect::spell_krystallus_shatter_effect_SpellScript::CalculateDamage(), spell_gruul_shatter_effect::spell_gruul_shatter_effect_SpellScript::CalculateDamage(), spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::CalculateDamage(), spell_quest_dragonmaw_race_generic::ChangeDest(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript::CheckAura(), spell_eredar_twins_handle_touch::spell_eredar_twins_handle_touch_SpellScript::CheckCast(), spell_q12237_rescue_villager::CheckCast(), spell_q12237_drop_off_villager::CheckCast(), spell_mage_ice_barrier::CheckCast(), spell_pri_power_word_shield::CheckCast(), spell_rog_pickpocket::CheckCast(), spell_sha_spirit_walk::CheckCast(), spell_warl_create_healthstone::CheckCast(), spell_warl_life_tap::CheckCast(), spell_sha_fire_nova::CheckFireTotem(), spell_gen_cannibalize::CheckIfCorpseNear(), spell_hun_pet_carrion_feeder::CheckIfCorpseNear(), spell_brewfest_relay_race_force_cast::CheckItem(), spell_ooze_zap::spell_ooze_zap_SpellScript::CheckRequirement(), spell_putricide_mutation_init::spell_putricide_mutation_init_SpellScript::CheckRequirement(), spell_gen_profession_research::CheckRequirement(), spell_item_book_of_glyph_mastery::CheckRequirement(), spell_q11670_it_was_the_orcs_honest::CheckTarget(), spell_rotface_unstable_ooze_explosion::spell_rotface_unstable_ooze_explosion_SpellScript::CheckTarget(), spell_marrowgar_bone_slice::spell_marrowgar_bone_slice_SpellScript::CountTargets(), spell_class_call_handler::FilterTargets(), spell_huhuran_poison_bolt::FilterTargets(), spell_energize_aoe::spell_energize_aoe_SpellScript::FilterTargets(), spell_blood_queen_swarming_shadows_floor_dmg::spell_blood_queen_swarming_shadows_floor_dmg_SpellScript::FilterTargets(), spell_deathbringer_boiling_blood::spell_deathbringer_boiling_blood_SpellScript::FilterTargets(), spell_rotface_mutated_infection::spell_rotface_mutated_infection_SpellScript::FilterTargets(), spell_q24545_aod_special::spell_q24545_aod_special_SpellScript::FilterTargets(), spell_pal_glyph_of_holy_light::FilterTargets(), spell_sindragosa_ice_tomb::spell_sindragosa_ice_tomb_SpellScript::FilterTargets(), spell_ulduar_stone_grip_cast_target::spell_ulduar_stone_grip_cast_target_SpellScript::FilterTargetsInitial(), spell_dk_raise_dead::GetGhoulSpellId(), spell_warl_banish::HandleBanish(), spell_gen_charmed_unit_spell_cooldown::HandleCast(), spell_gen_mounted_charge::HandleChargeEffect(), spell_warr_bloodthirst::HandleDamage(), spell_dk_corpse_explosion::HandleDamage(), spell_dk_ghoul_explode::HandleDamage(), spell_gordunni_trap::spell_gordunni_trap_SpellScript::HandleDummy(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::HandleDummy(), spell_switch_infragreen_bomber_station::spell_switch_infragreen_bomber_station_SpellScript::HandleDummy(), spell_q13007_iron_colossus::spell_q13007_iron_colossus_SpellScript::HandleDummy(), spell_gen_focused_bursts::HandleDummy(), spell_gen_oracle_wolvar_reputation::HandleDummy(), spell_gen_despawn_self::HandleDummy(), spell_q13086_last_line_of_defence::HandleDummy(), spell_pilgrims_bounty_pass_generic::HandleDummy(), spell_pilgrims_bounty_feast_on_generic::HandleDummy(), spell_dk_death_strike::HandleDummy(), spell_item_brewfest_mount_transformation::HandleDummy(), spell_pal_holy_shock::HandleDummy(), spell_pri_penance::HandleDummy(), spell_q12683_take_sputum_sample::HandleDummy(), spell_sha_fire_nova::HandleDummy(), spell_warr_deep_wounds::HandleDummy(), spell_warr_execute::HandleEffect(), spell_icc_sprit_alarm::spell_icc_sprit_alarm_SpellScript::HandleEvent(), spell_midsummer_fling_torch::HandleFinish(), spell_the_flag_of_ownership::HandleFinish(), spell_halion_blazing_aura::spell_halion_blazing_aura_SpellScript::HandleForceCast(), spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript::HandleForceCast(), spell_dreamwalker_summon_suppresser_effect::spell_dreamwalker_summon_suppresser_effect_SpellScript::HandleForceCast(), spell_ioc_bomb_blast_criteria::spell_ioc_bomb_blast_criteria_SpellScript::HandleGameObjectDamage(), spell_hatch_eggs::HandleObjectAreaTargetSelect(), spell_warr_mocking_blow::HandleOnHit(), spell_entropius_black_hole_effect::spell_entropius_black_hole_effect_SpellScript::HandlePull(), spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript::HandlePull(), spell_dk_raise_dead::HandleRaiseDead(), spell_warl_shadowflame::HandleSchoolDMG(), spell_pvp_trinket_wotf_shared_cd::HandleScript(), spell_pal_lay_on_hands::HandleScript(), spell_blood_queen_presence_of_the_darkfallen::spell_blood_queen_presence_of_the_darkfallen_SpellScript::HandleScript(), spell_putricide_unstable_experiment::spell_putricide_unstable_experiment_SpellScript::HandleScript(), spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript::HandleScript(), spell_dreamwalker_twisted_nightmares::spell_dreamwalker_twisted_nightmares_SpellScript::HandleScript(), spell_q24545_aod_special::spell_q24545_aod_special_SpellScript::HandleScript(), spell_item_scroll_of_recall::HandleScript(), spell_festergut_gastric_bloat::spell_festergut_gastric_bloat_SpellScript::HandleScript(), spell_putricide_choking_gas_bomb::spell_putricide_choking_gas_bomb_SpellScript::HandleScript(), spell_shango_tracks::spell_shango_tracks_SpellScript::HandleScript(), spell_gen_profession_research::HandleScript(), spell_gen_dalaran_disguise::HandleScript(), spell_item_book_of_glyph_mastery::HandleScript(), spell_q11670_it_was_the_orcs_honest::HandleScriptEffect(), spell_yogg_saron_sanity_reduce::spell_yogg_saron_sanity_reduce_SpellScript::HandleScriptEffect(), spell_gen_break_shield::HandleScriptEffect(), spell_gen_mounted_charge::HandleScriptEffect(), spell_item_feast::HandleScriptEffect(), spell_warl_create_healthstone::HandleScriptEffect(), spell_winter_veil_shoot_air_rifle::HandleScriptEffect(), spell_volazj_whisper::HandleScriptEffect(), spell_halion_clear_debuffs::spell_halion_clear_debuffs_SpellScript::HandleScriptEffect(), spell_gen_mine_sweeper::HandleScriptEffect(), spell_sindragosa_icy_grip_jump::spell_sindragosa_icy_grip_jump_SpellScript::HandleSpecial(), spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::HandleSummon(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript::HandleSummon(), spell_item_summon_or_dismiss::HandleSummon(), spell_item_draenic_pale_ale::HandleSummon(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::HandleTargets(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleTargets(), spell_mage_arcane_blast::HandleTriggerSpell(), spell_threatening_gaze_charge::LaunchHit(), spell_taldaram_summon_flame_ball::spell_taldaram_summon_flame_ball_SpellScript::Load(), spell_pal_divine_storm::Load(), spell_taldaram_ball_of_inferno_flame::spell_taldaram_ball_of_inferno_flame_SpellScript::ModAuraStack(), spell_gen_random_target32::ModDest(), spell_q12308_escape_from_silverbrook_summon_worgen::ModDest(), spell_the_lich_king_summon_into_air::spell_the_lich_king_summon_into_air_SpellScript::ModDestHeight(), spell_halion_summon_exit_portals::spell_halion_summon_exit_portals_SpellScript::OnSummon(), spell_anti_air_rocket_bomber::spell_anti_air_rocket_bomber_SpellScript::PrepareSpellScript(), spell_gen_use_spell_base_level_check::PrepareSpellScript(), spell_item_mind_amplify_dish::PrepareSpellScript(), spell_algalon_supermassive_fail::spell_algalon_supermassive_fail_SpellScript::RecalculateDamage(), spell_wg_reduce_damage_by_distance::spell_wg_reduce_damage_by_distance_SpellScript::RecalculateDamage(), spell_dk_death_and_decay::RecalculateDamage(), and spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::SelectTarget().
GetSpellValue()
SpellValue const * SpellScript::GetSpellValue ()
{
    return m_spell->m_spellValue;
}
References m_spell, and Spell::m_spellValue.
Referenced by spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript::AddMissingStack(), spell_pal_divine_storm_dummy::CountTargets(), spell_gurtogg_bloodboil::spell_gurtogg_bloodboil_SpellScript::FilterTargets(), spell_pal_seal_of_command::FilterTargets(), spell_warr_improved_spell_reflection_trigger::FilterTargets(), and spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::HandleSummon().
GetTriggeringSpell()
SpellInfo const * SpellScript::GetTriggeringSpell ()
{
    return m_spell->m_triggeredByAuraSpell.spellInfo;
}
References m_spell, Spell::m_triggeredByAuraSpell, and TriggeredByAuraSpellData::spellInfo.
Referenced by spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleDamage(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::HandleDamage(), spell_sha_healing_stream_totem::HandleDummy(), spell_dru_starfall_dummy::HandleDummy(), spell_gen_dummy_trigger::HandleDummy(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::HandleTargets(), and spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleTargets().
IsInCheckCastHook()
bool SpellScript::IsInCheckCastHook () const
{
    return m_currentScriptState == SPELL_SCRIPT_HOOK_CHECK_CAST;
}
References _SpellScript::m_currentScriptState, and SPELL_SCRIPT_HOOK_CHECK_CAST.
Referenced by SetCustomCastResultMessage().
IsInEffectHook()
bool SpellScript::IsInEffectHook () const
{
    return (m_currentScriptState >= SPELL_SCRIPT_HOOK_EFFECT_LAUNCH && m_currentScriptState <= SPELL_SCRIPT_HOOK_EFFECT_HIT_TARGET);
}
References _SpellScript::m_currentScriptState, SPELL_SCRIPT_HOOK_EFFECT_HIT_TARGET, and SPELL_SCRIPT_HOOK_EFFECT_LAUNCH.
Referenced by GetEffectValue(), GetHitDest(), PreventHitDefaultEffect(), PreventHitEffect(), and SetEffectValue().
IsInHitPhase()
bool SpellScript::IsInHitPhase () const
{
    return (m_currentScriptState >= HOOK_SPELL_HIT_START && m_currentScriptState < HOOK_SPELL_HIT_END);
}
References HOOK_SPELL_HIT_END, HOOK_SPELL_HIT_START, and _SpellScript::m_currentScriptState.
Referenced by PreventHitDefaultEffect(), and PreventHitEffect().
IsInTargetHook()
bool SpellScript::IsInTargetHook () const
{
    switch (m_currentScriptState)
    {
        case SPELL_SCRIPT_HOOK_EFFECT_LAUNCH_TARGET:
        case SPELL_SCRIPT_HOOK_EFFECT_HIT_TARGET:
        case SPELL_SCRIPT_HOOK_BEFORE_HIT:
        case SPELL_SCRIPT_HOOK_HIT:
        case SPELL_SCRIPT_HOOK_AFTER_HIT:
            return true;
    }
    return false;
}
References _SpellScript::m_currentScriptState, SPELL_SCRIPT_HOOK_AFTER_HIT, SPELL_SCRIPT_HOOK_BEFORE_HIT, SPELL_SCRIPT_HOOK_EFFECT_HIT_TARGET, SPELL_SCRIPT_HOOK_EFFECT_LAUNCH_TARGET, and SPELL_SCRIPT_HOOK_HIT.
Referenced by GetHitAura(), GetHitCreature(), GetHitDamage(), GetHitGObj(), GetHitHeal(), GetHitItem(), GetHitPlayer(), GetHitUnit(), PreventHitAura(), SetHitDamage(), and SetHitHeal().
PreventHitAura()
void SpellScript::PreventHitAura ()
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::PreventHitAura was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return;
    }
    if (m_spell->m_spellAura)
        m_spell->m_spellAura->Remove();
}
References IsInTargetHook(), LOG_ERROR, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, m_spell, Spell::m_spellAura, and Aura::Remove().
Referenced by spell_gen_mount::HandleMount(), and spell_item_magic_dust::HandlePreventAura().
PreventHitDamage()
void SpellScript::PreventHitDamage () inline
{ SetHitDamage(0); }
References SetHitDamage().
Referenced by spell_red_sky_effect::spell_red_sky_effect_SpellScript::HandleHit(), spell_finger_of_death::spell_finger_of_death_SpellScript::HandleHit(), and spell_hand_of_death::spell_hand_of_death_SpellScript::HandleHit().
PreventHitDefaultEffect()
void SpellScript::PreventHitDefaultEffect (SpellEffIndex effIndex)
{
    if (!IsInHitPhase() && !IsInEffectHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::PreventHitDefaultEffect was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return;
    }
    m_hitPreventDefaultEffectMask |= 1 << effIndex;
}
References IsInEffectHook(), IsInHitPhase(), LOG_ERROR, m_hitPreventDefaultEffectMask, _SpellScript::m_scriptName, and _SpellScript::m_scriptSpellId.
Referenced by spell_quest_dragonmaw_race_generic::ChangeDest(), spell_rotface_unstable_ooze_explosion::spell_rotface_unstable_ooze_explosion_SpellScript::CheckTarget(), spell_madrigosa_activate_barrier::spell_madrigosa_activate_barrier_SpellScript::HandleActivateObject(), spell_madrigosa_deactivate_barrier::spell_madrigosa_deactivate_barrier_SpellScript::HandleActivateObject(), spell_item_light_lamp::HandleActivateObject(), spell_q9452_cast_net::HandleActiveObject(), spell_serpentshrine_cavern_serpentshrine_parasite_trigger::spell_serpentshrine_cavern_serpentshrine_parasite_trigger_SpellScript::HandleApplyAura(), spell_corrupted_totems::HandleDummy(), spell_moroes_vanish::spell_moroes_vanish_SpellScript::HandleDummy(), spell_karazhan_blink::spell_karazhan_blink_SpellScript::HandleDummy(), spell_kalecgos_spectral_blast_dummy::spell_kalecgos_spectral_blast_dummy_SpellScript::HandleDummy(), spell_midsummer_juggling_torch::HandleDummy(), spell_ooze_zap::spell_ooze_zap_SpellScript::HandleDummy(), spell_ooze_zap_channel_end::spell_ooze_zap_channel_end_SpellScript::HandleDummy(), spell_saviana_conflagration_init::spell_saviana_conflagration_init_SpellScript::HandleDummy(), spell_igb_burning_pitch_selector::spell_igb_burning_pitch_selector_SpellScript::HandleDummy(), spell_igb_burning_pitch::spell_igb_burning_pitch_SpellScript::HandleDummy(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::HandleDummy(), spell_switch_infragreen_bomber_station::spell_switch_infragreen_bomber_station_SpellScript::HandleDummy(), spell_q13007_iron_colossus::spell_q13007_iron_colossus_SpellScript::HandleDummy(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::HandleDummy(), spell_leotheras_chaos_blast::spell_leotheras_chaos_blast_SpellScript::HandleDummy(), spell_morogrim_tidewalker_watery_grave::spell_morogrim_tidewalker_watery_grave_SpellScript::HandleDummy(), spell_morogrim_tidewalker_water_globule_new_target::spell_morogrim_tidewalker_water_globule_new_target_SpellScript::HandleDummy(), spell_q10935_the_exorcism_of_colonel_jules::spell_q10935_the_exorcism_of_colonel_jules_SpellScript::HandleDummy(), spell_gen_hate_to_zero::HandleDummy(), spell_gen_focused_bursts::HandleDummy(), spell_item_lil_xt::HandleDummy(), spell_item_powerful_anti_venom::HandleDummy(), spell_item_strong_anti_venom::HandleDummy(), spell_item_anti_venom::HandleDummy(), spell_mage_burnout_trigger::HandleDummy(), spell_deathbringer_blood_link::spell_deathbringer_blood_link_SpellScript::HandleDummy(), spell_algalon_trigger_3_adds::spell_algalon_trigger_3_adds_SpellScript::HandleDummyEffect(), spell_yogg_saron_destabilization_matrix::spell_yogg_saron_destabilization_matrix_SpellScript::HandleDummyEffect(), spell_yogg_saron_titanic_storm::spell_yogg_saron_titanic_storm_SpellScript::HandleDummyEffect(), spell_yogg_saron_insane_periodic_trigger::spell_yogg_saron_insane_periodic_trigger_SpellScript::HandleDummyEffect(), spell_mark_of_nature::spell_mark_of_nature_SpellScript::HandleEffect(), spell_icc_sprit_alarm::spell_icc_sprit_alarm_SpellScript::HandleEvent(), spell_icc_geist_alarm::spell_icc_geist_alarm_SpellScript::HandleEvent(), spell_halion_blazing_aura::spell_halion_blazing_aura_SpellScript::HandleForceCast(), spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript::HandleForceCast(), spell_dreamwalker_summon_suppresser_effect::spell_dreamwalker_summon_suppresser_effect_SpellScript::HandleForceCast(), spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript::HandleForcedCast(), spell_item_toxic_wasteling::HandleJump(), spell_dru_typhoon::HandleKnockBack(), spell_mage_blast_wave::HandleKnockBack(), spell_sha_thunderstorm::HandleKnockBack(), spell_gen_mount::HandleMount(), spell_gen_haunted::HandleOnEffectHit(), spell_item_summon_argent_knight::HandleOnEffectHit(), spell_item_freeze_rookery_egg::HandleOpenObject(), spell_entropius_black_hole_effect::spell_entropius_black_hole_effect_SpellScript::HandlePull(), spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript::HandlePull(), spell_kormok_summon_bone_mages::HandleScript(), spell_kormok_summon_bone_minions::HandleScript(), spell_eredar_twins_blaze::spell_eredar_twins_blaze_SpellScript::HandleScript(), spell_item_create_heart_candy::HandleScript(), spell_midsummer_fling_torch::HandleScript(), spell_energize_aoe::spell_energize_aoe_SpellScript::HandleScript(), spell_saviana_conflagration_throwback::spell_saviana_conflagration_throwback_SpellScript::HandleScript(), spell_taldaram_glittering_sparks::spell_taldaram_glittering_sparks_SpellScript::HandleScript(), spell_taldaram_summon_flame_ball::spell_taldaram_summon_flame_ball_SpellScript::HandleScript(), spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::HandleScript(), spell_blood_queen_presence_of_the_darkfallen::spell_blood_queen_presence_of_the_darkfallen_SpellScript::HandleScript(), spell_igb_rocket_artillery::spell_igb_rocket_artillery_SpellScript::HandleScript(), spell_putricide_unstable_experiment::spell_putricide_unstable_experiment_SpellScript::HandleScript(), spell_putricide_clear_aura_effect_value::spell_putricide_clear_aura_effect_value_SpellScript::HandleScript(), spell_sindragosa_icy_grip::spell_sindragosa_icy_grip_SpellScript::HandleScript(), spell_frostwarden_handler_focus_fire::spell_frostwarden_handler_focus_fire_SpellScript::HandleScript(), spell_the_lich_king_jump::spell_the_lich_king_jump_SpellScript::HandleScript(), spell_the_lich_king_jump_remove_aura::spell_the_lich_king_jump_SpellScript::HandleScript(), spell_the_lich_king_play_movie::spell_the_lich_king_play_movie_SpellScript::HandleScript(), spell_the_lich_king_raging_spirit::spell_the_lich_king_raging_spirit_SpellScript::HandleScript(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::HandleScript(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::HandleScript(), spell_the_lich_king_summon_spirit_bomb::spell_the_lich_king_summon_spirit_bomb_SpellScript::HandleScript(), spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript::HandleScript(), spell_dreamwalker_twisted_nightmares::spell_dreamwalker_twisted_nightmares_SpellScript::HandleScript(), spell_icc_harvest_blight_specimen::spell_icc_harvest_blight_specimen_SpellScript::HandleScript(), spell_svalna_remove_spear::spell_svalna_remove_spear_SpellScript::HandleScript(), spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript::HandleScript(), spell_archavon_rock_shards::spell_archavon_rock_shards_SpellScript::HandleScript(), spell_q24545_aod_special::spell_q24545_aod_special_SpellScript::HandleScript(), spell_wintergrasp_force_building::spell_wintergrasp_force_building_SpellScript::HandleScript(), spell_wintergrasp_portal::spell_wintergrasp_portal_SpellScript::HandleScript(), spell_dk_death_gate::HandleScript(), spell_gen_create_lance::HandleScript(), spell_gen_netherbloom::HandleScript(), spell_gen_nightmare_vine::HandleScript(), spell_item_defibrillate::HandleScript(), spell_item_piccolo_of_the_flaming_fire::HandleScript(), spell_item_scroll_of_recall::HandleScript(), spell_q10041_q10040_who_are_they::HandleScript(), spell_warr_shattering_throw::HandleScript(), spell_warr_vigilance_trigger::HandleScript(), spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript::HandleScript2(), spell_brutallus_burn::spell_brutallus_burn_SpellScript::HandleScriptEffect(), spell_felmyst_fog_of_corruption::spell_felmyst_fog_of_corruption_SpellScript::HandleScriptEffect(), spell_kalecgos_spectral_realm_dummy::spell_kalecgos_spectral_realm_dummy_SpellScript::HandleScriptEffect(), spell_kiljaeden_sinister_reflection::spell_kiljaeden_sinister_reflection_SpellScript::HandleScriptEffect(), spell_kiljaeden_power_of_the_blue_flight::spell_kiljaeden_power_of_the_blue_flight_SpellScript::HandleScriptEffect(), spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript::HandleScriptEffect(), spell_batrider_bomb::HandleScriptEffect(), spell_vem_knockback::HandleScriptEffect(), spell_azjol_nerub_fixate::spell_azjol_nerub_fixate_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame_bonestorm::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_yogg_saron_sanity_reduce::spell_yogg_saron_sanity_reduce_SpellScript::HandleScriptEffect(), spell_yogg_saron_empowering_shadows::spell_yogg_saron_empowering_shadows_SpellScript::HandleScriptEffect(), spell_illidan_draw_soul::spell_illidan_draw_soul_SpellScript::HandleScriptEffect(), spell_illidan_parasitic_shadowfiend_trigger::spell_illidan_parasitic_shadowfiend_trigger_SpellScript::HandleScriptEffect(), spell_black_template_free_friend::spell_black_template_free_friend_SpellScript::HandleScriptEffect(), spell_lady_vashj_remove_tainted_cores::spell_lady_vashj_remove_tainted_cores_SpellScript::HandleScriptEffect(), spell_lady_vashj_summon_sporebat::spell_lady_vashj_summon_sporebat_SpellScript::HandleScriptEffect(), spell_lady_vashj_spore_drop_effect::spell_lady_vashj_spore_drop_effect_SpellScript::HandleScriptEffect(), spell_leotheras_whirlwind::spell_leotheras_whirlwind_SpellScript::HandleScriptEffect(), spell_leotheras_clear_consuming_madness::spell_leotheras_clear_consuming_madness_SpellScript::HandleScriptEffect(), spell_tsh_shoot_flame_arrow::spell_tsh_shoot_flame_arrow_SpellScript::HandleScriptEffect(), spell_gen_fixate::HandleScriptEffect(), spell_gen_knock_away::HandleScriptEffect(), spell_gen_throw_back::HandleScriptEffect(), spell_gen_clone::HandleScriptEffect(), spell_gen_clone_weapon::HandleScriptEffect(), spell_gen_throw_shield::HandleScriptEffect(), spell_item_sleepy_willy::HandleScriptEffect(), spell_item_toxic_wasteling::HandleScriptEffect(), spell_item_lil_xt::HandleScriptEffect(), spell_item_feast::HandleScriptEffect(), spell_temple_of_atal_hakkar_awaken_the_soulflayer::spell_temple_of_atal_hakkar_awaken_the_soulflayer_SpellScript::HandleSendEvent(), spell_q12478_frostmourne_cavern::spell_q12478_frostmourne_cavern_SpellScript::HandleSendEvent(), spell_q12620_the_lifewarden_wrath::spell_q12620_the_lifewarden_wrath_SpellScript::HandleSendEvent(), spell_sindragosa_icy_grip_jump::spell_sindragosa_icy_grip_jump_SpellScript::HandleSpecial(), spell_marrowgar_bone_spike_graveyard::spell_marrowgar_bone_spike_graveyard_SpellScript::HandleSpikes(), spell_zulfarrak_summon_zulfarrak_zombies::spell_zulfarrak_summon_zulfarrak_zombies_SpellScript::HandleSummon(), spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::HandleSummon(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), spell_item_summon_or_dismiss::HandleSummon(), spell_item_draenic_pale_ale::HandleSummon(), spell_rimefang_icy_blast::spell_rimefang_icy_blast_SpellScript::HandleTriggerMissile(), spell_gnomeregan_radiation_bolt::spell_gnomeregan_radiation_bolt_SpellScript::HandleTriggerSpell(), spell_mage_arcane_blast::HandleTriggerSpell(), spell_pal_righteous_defense::HandleTriggerSpellHit(), spell_pal_righteous_defense::HandleTriggerSpellLaunch(), spell_item_ashbringer::OnDummyEffect(), spell_item_linken_boomerang::OnEffectHitTargetDisarm(), spell_item_linken_boomerang::OnEffectHitTargetStun(), spell_item_linken_boomerang::OnEffectLaunchTargetDisarm(), spell_item_linken_boomerang::OnEffectLaunchTargetStun(), spell_anti_air_rocket_bomber::spell_anti_air_rocket_bomber_SpellScript::PrepareSpellScript(), spell_charge_shield_bomber::spell_charge_shield_bomber_SpellScript::PrepareSpellScript(), spell_fight_fire_bomber::spell_fight_fire_bomber_SpellScript::PrepareSpellScript(), spell_hodir_shatter_chest::spell_hodir_shatter_chestSpellScript::PrepareSpellScript(), spell_item_branns_communicator::PrepareSpellScript(), spell_item_direbrew_remote::PrepareSpellScript(), spell_item_mind_amplify_dish::PrepareSpellScript(), spell_item_oracle_ablutions::PrepareSpellScript(), spell_item_runescroll_of_fortitude::PrepareSpellScript(), spell_item_titanium_seal_of_dalaran::PrepareSpellScript(), spell_item_toy_train_set::PrepareSpellScript(), spell_q11198_take_down_tethyr::PrepareSpellScript(), spell_q11653_youre_not_so_big_now::PrepareSpellScript(), spell_q13369_fate_up_against_your_will::PrepareSpellScript(), spell_threatening_gaze_charge::PrepareSpellScript(), and PreventHitEffect().
PreventHitEffect()
void SpellScript::PreventHitEffect (SpellEffIndex effIndex)
{
    if (!IsInHitPhase() && !IsInEffectHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::PreventHitEffect was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return;
    }
    m_hitPreventEffectMask |= 1 << effIndex;
    PreventHitDefaultEffect(effIndex);
}
References IsInEffectHook(), IsInHitPhase(), LOG_ERROR, m_hitPreventEffectMask, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and PreventHitDefaultEffect().
Referenced by spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::CalculateDamage(), spell_rotface_unstable_ooze_explosion_init::spell_rotface_unstable_ooze_explosion_init_SpellScript::HandleCast(), spell_illidan_glaive_throw::spell_illidan_glaive_throw_SpellScript::HandleDummy(), spell_illidan_found_target::spell_illidan_found_target_SpellScript::HandleDummy(), spell_q13086_last_line_of_defence::HandleDummy(), spell_alar_ember_blast::spell_alar_ember_blast_SpellScript::HandleForceCast(), spell_chapter5_rebuke::spell_chapter5_rebuke_SpellScript::HandleLeapBack(), spell_q12641_death_comes_from_on_high_summon_ghouls::spell_q12641_death_comes_from_on_high_summon_ghouls_SpellScript::HandleScriptEffect(), spell_gurtogg_eject::spell_gurtogg_eject_SpellScript::HandleScriptEffect(), spell_illidan_flame_burst::spell_illidan_flame_burst_SpellScript::HandleScriptEffect(), spell_illidan_cage_trap::spell_illidan_cage_trap_SpellScript::HandleScriptEffect(), spell_black_temple_bloodbolt::spell_black_temple_bloodbolt_SpellScript::HandleScriptEffect(), spell_kaelthas_summon_weapons::spell_kaelthas_summon_weapons_SpellScript::HandleScriptEffect(), spell_kaelthas_gravity_lapse::spell_kaelthas_gravity_lapse_SpellScript::HandleScriptEffect(), spell_kaelthas_nether_beam::spell_kaelthas_nether_beam_SpellScript::HandleScriptEffect(), spell_kaelthas_summon_nether_vapor::spell_kaelthas_summon_nether_vapor_SpellScript::HandleScriptEffect(), spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript::HandleSummon(), and spell_winter_veil_racer_rocket_slam::HandleTriggerSpell().
PreventHitHeal()
void SpellScript::PreventHitHeal () inline
{ SetHitHeal(0); }
References SetHitHeal().
SetCustomCastResultMessage()
void SpellScript::SetCustomCastResultMessage (SpellCustomErrors result)
{
    if (!IsInCheckCastHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::SetCustomCastResultMessage was called while spell not in check cast phase!", m_scriptName->c_str(), m_scriptSpellId);
        return;
    }
    m_spell->m_customError = result;
}
References IsInCheckCastHook(), LOG_ERROR, Spell::m_customError, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and m_spell.
Referenced by spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::CheckCast(), spell_hun_check_pet_los::CheckCast(), spell_hun_bestial_wrath::CheckCast(), spell_dk_death_gate::CheckClass(), spell_sha_fire_nova::CheckFireTotem(), spell_gen_summon_tournament_mount::CheckIfLanceEquiped(), spell_item_gift_of_the_harvester::spell_item_gift_of_the_harvester_SpellScript::CheckRequirement(), spell_gen_profession_research::CheckRequirement(), spell_item_book_of_glyph_mastery::CheckRequirement(), spell_item_map_of_the_geyser_fields::CheckSinkholes(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::CheckTarget(), and spell_q11670_it_was_the_orcs_honest::CheckTarget().
SetEffectValue()
void SpellScript::SetEffectValue (int32 value)
{
    if (!IsInEffectHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::SetEffectValue was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return;
    }
    m_spell->damage = value;
}
References Spell::damage, IsInEffectHook(), LOG_ERROR, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and m_spell.
Referenced by spell_dk_ghoul_explode::HandleDamage(), spell_pet_dk_gargoyle_strike::HandleDamageCalc(), spell_pri_prayer_of_mending_heal::HandleHeal(), spell_warr_bloodthirst_heal::HandleHeal(), and spell_dk_bloodworms::HandleSummon().
SetExplTargetDest()
void SpellScript::SetExplTargetDest (WorldLocation & loc)
{
    m_spell->m_targets.SetDst(loc);
}
References m_spell, Spell::m_targets, and SpellCastTargets::SetDst().
Referenced by spell_valanar_kinetic_bomb::spell_valanar_kinetic_bomb_SpellScript::ChangeSummonPos(), spell_onslaught_or_call_bone_gryphon::spell_onslaught_or_call_bone_gryphon_SpellScript::ChangeSummonPos(), spell_brewfest_toss_mug::CheckCast(), spell_brewfest_toss_mug::HandleBeforeHit(), and spell_halion_summon_exit_portals::spell_halion_summon_exit_portals_SpellScript::OnSummon().
SetHitDamage()
void SpellScript::SetHitDamage (int32 damage)
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::SetHitDamage was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return;
    }
    m_spell->m_damage = damage;
}
References IsInTargetHook(), LOG_ERROR, Spell::m_damage, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and m_spell.
Referenced by spell_blood_council_shadow_prison_damage::spell_blood_council_shadow_prison_SpellScript::AddExtraDamage(), spell_oculus_shock_lance::spell_oculus_shock_lance_SpellScript::CalcDamage(), spell_krystallus_shatter_effect::spell_krystallus_shatter_effect_SpellScript::CalculateDamage(), spell_gruul_shatter_effect::spell_gruul_shatter_effect_SpellScript::CalculateDamage(), spell_item_wraith_scythe_drain_life::CalculateDamage(), spell_loken_pulsing_shockwave::spell_loken_pulsing_shockwave_SpellScript::CalculateDamage(), spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript::ChangeDamageAndGrow(), spell_warr_bloodthirst::HandleDamage(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleDamage(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::HandleDamage(), spell_freezing_circle::HandleDamage(), spell_rajaxx_thundercrash::HandleDamageCalc(), spell_four_horsemen_consumption::HandleDamageCalc(), spell_oculus_touch_the_nightmare::spell_oculus_touch_the_nightmare_SpellScript::HandleDamageCalc(), spell_sha_lava_lash::HandleDummy(), spell_warr_concussion_blow::HandleDummy(), spell_voa_lightning_nova::spell_voa_lightning_nova_SpellScript::HandleOnHit(), spell_warr_mocking_blow::HandleOnHit(), PreventHitDamage(), spell_bronjahm_magic_bane::spell_bronjahm_magic_bane_SpellScript::RecalculateDamage(), spell_marrowgar_bone_storm::spell_marrowgar_bone_storm_SpellScript::RecalculateDamage(), spell_algalon_cosmic_smash_damage::spell_algalon_cosmic_smash_damage_SpellScript::RecalculateDamage(), spell_xt002_tympanic_tantrum::spell_xt002_tympanic_tantrum_SpellScript::RecalculateDamage(), spell_wg_reduce_damage_by_distance::spell_wg_reduce_damage_by_distance_SpellScript::RecalculateDamage(), spell_murmur_sonic_boom_effect::spell_murmur_sonic_boom_effect_SpellScript::RecalculateDamage(), spell_dk_death_and_decay::RecalculateDamage(), spell_gen_reduced_above_60::RecalculateDamage(), spell_gen_count_pct_from_max_hp::RecalculateDamage(), and spell_marrowgar_bone_slice::spell_marrowgar_bone_slice_SpellScript::SplitDamage().
SetHitHeal()
void SpellScript::SetHitHeal (int32 heal)
{
    if (!IsInTargetHook())
    {
        LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}`: function SpellScript::SetHitHeal was called, but function has no effect in current hook!", m_scriptName->c_str(), m_scriptSpellId);
        return;
    }
    m_spell->m_healing = heal;
}
References IsInTargetHook(), LOG_ERROR, Spell::m_healing, _SpellScript::m_scriptName, _SpellScript::m_scriptSpellId, and m_spell.
Referenced by spell_item_runic_healing_injector::HandleHeal(), spell_sha_chain_heal::HandleHeal(), and PreventHitHeal().
Member Data Documentation
AfterCast
HookList<CastHandler> SpellScript::AfterCast
Referenced by spell_summon_ragnaros::spell_summon_ragnaros_SpellScript::Register(), spell_ragnaros_lava_burst_randomizer::Register(), spell_ragnaros_summon_sons_of_flame::Register(), spell_mt_phoenix_burn::spell_mt_phoenix_burn_SpellScript::Register(), spell_apothecary_lingering_fumes::Register(), spell_cataclysm_breath::spell_cataclysm_breath_SpellScript::Register(), spell_midsummer_fling_torch::Register(), spell_midsummer_juggling_torch::Register(), spell_herald_volzaj_insanity::Register(), spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::Register(), spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::Register(), spell_icc_shattered_bones::spell_icc_shattered_bones_SpellScript::Register(), spell_thaddius_polarity_shift::spell_thaddius_polarity_shift_SpellScript::Register(), spell_algalon_big_bang::spell_algalon_big_bang_SpellScript::Register(), spell_wintergrasp_rp_gg::spell_wintergrasp_rp_gg_SpellScript::Register(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::Register(), spell_dk_chains_of_ice::Register(), spell_dru_berserk::Register(), spell_the_flag_of_ownership::Register(), spell_pvp_trinket_wotf_shared_cd::Register(), spell_hun_volley_trigger::Register(), spell_mage_arcane_blast::Register(), spell_q12014_steady_as_a_rock::Register(), spell_q13086_last_line_of_defence::Register(), spell_q5056_summon_shy_rotam::Register(), and spell_sha_totem_of_wrath::Register().
AfterHit
HookList<HitHandler> SpellScript::AfterHit
Referenced by spell_eredar_twins_apply_dark_touched::spell_eredar_twins_apply_dark_touched_SpellScript::Register(), spell_eredar_twins_apply_flame_touched::spell_eredar_twins_apply_flame_touched_SpellScript::Register(), spell_brewfest_fill_keg::Register(), spell_brewfest_unfill_keg::Register(), spell_ruby_sanctum_rallying_shout::spell_ruby_sanctum_rallying_shout_SpellScript::Register(), spell_gen_leeching_swarm_dmg::spell_gen_leeching_swarm_dmg_SpellScript::Register(), spell_taldaram_ball_of_inferno_flame::spell_taldaram_ball_of_inferno_flame_SpellScript::Register(), spell_deathbringer_blood_power::spell_deathbringer_blood_power_SpellScript::Register(), spell_igb_cannon_blast::spell_igb_cannon_blast_SpellScript::Register(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::Register(), spell_rotface_mutated_infection::spell_rotface_mutated_infection_SpellScript::Register(), spell_sindragosa_frost_breath::spell_sindragosa_frost_breath_SpellScript::Register(), spell_the_lich_king_life_siphon::spell_the_lich_king_life_siphon_SpellScript::Register(), spell_trigger_spell_from_caster::spell_trigger_spell_from_caster_SpellScript::Register(), spell_ioc_launch::spell_ioc_launch_SpellScript::Register(), spell_saronite_vapors_damage::spell_saronite_vapors_damage_SpellScript::Register(), spell_dk_blood_boil::Register(), spell_dk_scourge_strike::Register(), spell_dru_tiger_s_fury::Register(), spell_gen_bandage::Register(), spell_gen_eject_all_passengers::Register(), spell_pal_divine_storm::Register(), spell_pal_lay_on_hands::Register(), spell_pri_mana_burn::Register(), spell_q11670_it_was_the_orcs_honest::Register(), spell_rog_deadly_poison::Register(), spell_sha_bloodlust::Register(), spell_sha_heroism::Register(), spell_warl_haunt::Register(), and spell_warr_victory_rush::Register().
BeforeCast
HookList<CastHandler> SpellScript::BeforeCast
Referenced by spell_valanar_kinetic_bomb_summon::spell_valanar_kinetic_bomb_summon_SpellScript::Register(), spell_putricide_slime_puddle_spawn::spell_putricide_slime_puddle_spawn_SpellScript::Register(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::Register(), and spell_kaelthas_resurrection::spell_kaelthas_resurrection_SpellScript::Register().
BeforeHit
HookList<BeforeHitHandler> SpellScript::BeforeHit
Referenced by spell_brewfest_toss_mug::Register(), spell_valanar_kinetic_bomb_knockback::spell_valanar_kinetic_bomb_knockback_SpellScript::Register(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::Register(), spell_igb_below_zero::spell_igb_below_zero_SpellScript::Register(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript::Register(), spell_rog_deadly_poison::Register(), spell_warl_banish::Register(), spell_warr_slam::Register(), and spell_warr_execute::Register().
m_hitPreventDefaultEffectMask
uint8 SpellScript::m_hitPreventDefaultEffectMask private
Referenced by _InitHit(), _IsDefaultEffectPrevented(), and PreventHitDefaultEffect().
m_hitPreventEffectMask
uint8 SpellScript::m_hitPreventEffectMask private
Referenced by _InitHit(), _IsEffectPrevented(), and PreventHitEffect().
m_spell
Spell* SpellScript::m_spell private
Referenced by _Load(), Cancel(), CreateItem(), FinishCast(), GetCaster(), GetCastItem(), GetEffectValue(), GetExplTargetDest(), GetExplTargetGObj(), GetExplTargetItem(), GetExplTargetUnit(), GetExplTargetWorldObject(), GetHitAura(), GetHitCreature(), GetHitDamage(), GetHitDest(), GetHitGObj(), GetHitHeal(), GetHitItem(), GetHitPlayer(), GetHitUnit(), GetOriginalCaster(), GetSpell(), GetSpellInfo(), GetSpellValue(), GetTriggeringSpell(), PreventHitAura(), SetCustomCastResultMessage(), SetEffectValue(), SetExplTargetDest(), SetHitDamage(), and SetHitHeal().
OnCast
HookList<CastHandler> SpellScript::OnCast
Referenced by spell_gordunni_trap::spell_gordunni_trap_SpellScript::Register(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::Register(), spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::Register(), spell_icc_soul_missile::spell_icc_soul_missile_SpellScript::Register(), spell_dk_raise_dead::Register(), spell_gen_relocaste_dest::Register(), and spell_gen_charmed_unit_spell_cooldown::Register().
OnCheckCast
HookList<CheckCastHandler> SpellScript::OnCheckCast
Referenced by spell_item_gift_of_the_harvester::spell_item_gift_of_the_harvester_SpellScript::Register(), spell_eredar_twins_handle_touch::spell_eredar_twins_handle_touch_SpellScript::Register(), spell_kalecgos_spectral_realm_dummy::spell_kalecgos_spectral_realm_dummy_SpellScript::Register(), spell_q11117_catch_the_wild_wolpertinger::Register(), spell_brewfest_toss_mug::Register(), spell_brewfest_relay_race_force_cast::Register(), spell_midsummer_fling_torch::Register(), spell_ooze_zap::spell_ooze_zap_SpellScript::Register(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::Register(), spell_putricide_mutation_init::spell_putricide_mutation_init_SpellScript::Register(), spell_yogg_saron_in_the_maws_of_the_old_god::spell_yogg_saron_in_the_maws_of_the_old_god_SpellScript::Register(), spell_q12237_rescue_villager::Register(), spell_q12237_drop_off_villager::Register(), spell_call_wintergarde_gryphon::Register(), spell_renew_skirmisher::Register(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::Register(), spell_wintergrasp_water::spell_wintergrasp_water_SpellScript::Register(), spell_dk_death_coil::Register(), spell_dk_death_gate::Register(), spell_dk_death_grip::Register(), spell_dk_death_pact::Register(), spell_dk_raise_dead::Register(), spell_dru_savage_roar::Register(), spell_dru_survival_instincts::Register(), spell_gen_disabled_above_level::Register(), spell_gen_grow_flower_patch::Register(), spell_gen_use_spell_base_level_check::Register(), spell_gen_proc_above_75::Register(), spell_gen_cannibalize::Register(), spell_gen_profession_research::Register(), spell_gen_allow_cast_from_item_only::Register(), spell_gen_vehicle_scaling::Register(), spell_gen_summon_tournament_mount::Register(), spell_gen_bandage::Register(), spell_gen_arcane_charge::Register(), spell_hun_check_pet_los::Register(), spell_hun_masters_call::Register(), spell_hun_pet_heart_of_the_phoenix::Register(), spell_hun_pet_carrion_feeder::Register(), spell_hun_disengage::Register(), spell_hun_tame_beast::Register(), spell_hun_bestial_wrath::Register(), spell_item_book_of_glyph_mastery::Register(), spell_item_map_of_the_geyser_fields::Register(), spell_item_demon_broiled_surprise::Register(), spell_item_rocket_boots::Register(), spell_item_snowman::Register(), spell_mage_ice_barrier::Register(), spell_pal_hand_of_sacrifice::Register(), spell_pal_holy_shock::Register(), spell_pal_lay_on_hands::Register(), spell_pal_righteous_defense::Register(), spell_pri_penance::Register(), spell_pri_power_word_shield::Register(), spell_q11065_wrangle_some_aether_rays::Register(), spell_q12943_shadow_vault_decree::Register(), spell_quest_dragonmaw_race_generic::Register(), spell_q11670_it_was_the_orcs_honest::Register(), spell_q13369_fate_up_against_your_will::Register(), spell_q9452_cast_net::Register(), spell_q11010_q11102_q11023_q11008_check_fly_mount::Register(), spell_q4735_collect_rookery_egg::Register(), spell_rog_killing_spree::spell_rog_killing_spree_SpellScript::Register(), spell_rog_pickpocket::Register(), spell_sha_spirit_walk::Register(), spell_sha_fire_nova::Register(), spell_warl_ritual_of_summoning::Register(), spell_warl_create_healthstone::Register(), and spell_warl_life_tap::Register().
OnDestinationTargetSelect
HookList<DestinationTargetSelectHandler> SpellScript::OnDestinationTargetSelect
Referenced by _Validate(), spell_kiljaeden_armageddon_missile::spell_kiljaeden_armageddon_missile_SpellScript::Register(), spell_random_lightning_visual_effect::Register(), spell_prince_taldaram_flame_sphere_summon::Register(), spell_azjol_nerub_impale_summon::Register(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::Register(), spell_oculus_call_ruby_emerald_amber_drake::spell_oculus_call_ruby_emerald_amber_drake_SpellScript::Register(), spell_call_wintergarde_gryphon::Register(), spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::Register(), spell_shade_of_akama_akama_soul_expel::spell_shade_of_akama_akama_soul_expel_SpellScript::Register(), spell_q10930_big_bone_worm::spell_q10930_big_bone_worm_SpellScript::Register(), spell_q10929_fumping::spell_q10929_fumping_SpellScript::Register(), spell_q10923_evil_draws_near_visual::spell_q10923_evil_draws_near_visual_SpellScript::Register(), spell_q10898_skywing::spell_q10898_skywing_SpellScript::Register(), spell_dk_summon_gargoyle::Register(), spell_gen_random_target32::Register(), spell_gen_basic_campfire::Register(), spell_item_dragon_kite_summon_lightning_bunny::Register(), spell_item_recall::Register(), spell_q12661_q12669_q12676_q12677_q12713_summon_stefan::Register(), spell_q13291_q13292_q13239_q13261_armored_decoy_summon_skytalon::Register(), and spell_q12308_escape_from_silverbrook_summon_worgen::Register().
OnEffectHit
HookList<EffectHandler> SpellScript::OnEffectHit
Referenced by _Validate(), spell_gnomeregan_radiation_bolt::spell_gnomeregan_radiation_bolt_SpellScript::Register(), spell_temple_of_atal_hakkar_awaken_the_soulflayer::spell_temple_of_atal_hakkar_awaken_the_soulflayer_SpellScript::Register(), spell_zulfarrak_summon_zulfarrak_zombies::spell_zulfarrak_summon_zulfarrak_zombies_SpellScript::Register(), spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::Register(), spell_valanar_kinetic_bomb::spell_valanar_kinetic_bomb_SpellScript::Register(), spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::Register(), spell_igb_rocket_artillery_explosion::spell_igb_rocket_artillery_explosion_SpellScript::Register(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::Register(), spell_rotface_unstable_ooze_explosion::spell_rotface_unstable_ooze_explosion_SpellScript::Register(), spell_rimefang_icy_blast::spell_rimefang_icy_blast_SpellScript::Register(), spell_the_lich_king_quake::spell_the_lich_king_quake_SpellScript::Register(), spell_the_lich_king_summon_into_air::spell_the_lich_king_summon_into_air_SpellScript::Register(), spell_the_lich_king_teleport_to_frostmourne_hc::spell_the_lich_king_teleport_to_frostmourne_hc_SpellScript::Register(), spell_icc_sprit_alarm::spell_icc_sprit_alarm_SpellScript::Register(), spell_icc_geist_alarm::spell_icc_geist_alarm_SpellScript::Register(), spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Register(), spell_hodir_shatter_chest::spell_hodir_shatter_chestSpellScript::Register(), spell_q11719_bloodspore_ruination_45997::spell_q11719_bloodspore_ruination_45997_SpellScript::Register(), spell_q12478_frostmourne_cavern::spell_q12478_frostmourne_cavern_SpellScript::Register(), spell_onslaught_or_call_bone_gryphon::spell_onslaught_or_call_bone_gryphon_SpellScript::Register(), spell_q12620_the_lifewarden_wrath::spell_q12620_the_lifewarden_wrath_SpellScript::Register(), spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript::Register(), spell_the_black_stalker_levitation_pulse::Register(), spell_dk_bloodworms::Register(), spell_gen_haunted::Register(), spell_gen_cannibalize::Register(), spell_gen_oracle_wolvar_reputation::Register(), spell_hun_pet_carrion_feeder::Register(), spell_item_summon_or_dismiss::Register(), spell_item_draenic_pale_ale::Register(), spell_item_summon_argent_knight::Register(), spell_item_trigger_spell::Register(), spell_item_deviate_fish::Register(), spell_item_flask_of_the_north::Register(), spell_item_make_a_wish::Register(), spell_item_mingos_fortune_generator::Register(), spell_item_noggenfogger_elixir::Register(), spell_item_savory_deviate_delight::Register(), spell_item_underbelly_elixir::Register(), spell_item_vanquished_clutches::Register(), spell_item_ashbringer::Register(), spell_item_goblin_bomb::Register(), spell_mage_cold_snap::Register(), spell_mage_summon_water_elemental::Register(), spell_quest_dragonmaw_race_generic::Register(), spell_q5206_test_fetid_skull::Register(), spell_q12634_despawn_fruit_tosser::Register(), spell_q12683_take_sputum_sample::Register(), spell_q13280_13283_plant_battle_standard::Register(), spell_q9452_cast_net::Register(), spell_q11010_q11102_q11023_choose_loc::Register(), spell_q12308_escape_from_silverbrook::Register(), spell_q12619_emblazon_runeblade_effect::Register(), spell_q4735_collect_rookery_egg::Register(), spell_warl_ritual_of_doom_effect::Register(), spell_warr_last_stand::Register(), and spell_warr_bloodthirst::Register().
OnEffectHitTarget
HookList<EffectHandler> SpellScript::OnEffectHitTarget
Referenced by _Validate(), spell_gen_elemental_shield::Register(), spell_gen_brood_power::Register(), spell_corrupted_totems::Register(), spell_shadowblink::Register(), spell_spawn_drakonid::Register(), spell_bwl_shadowflame::spell_bwl_shadowflame_SpellScript::Register(), spell_garr_frenzy::spell_garr_frenzy_SpellScript::Register(), spell_magmadar_lava_bomb::spell_magmadar_lava_bomb_SpellScript::Register(), spell_hate_to_zero::spell_hate_to_zero_SpellScript::Register(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::Register(), spell_moroes_vanish::spell_moroes_vanish_SpellScript::Register(), spell_karazhan_blink::spell_karazhan_blink_SpellScript::Register(), spell_q12641_death_comes_from_on_high_summon_ghouls::spell_q12641_death_comes_from_on_high_summon_ghouls_SpellScript::Register(), spell_q12698_the_gift_that_keeps_on_giving::spell_q12698_the_gift_that_keeps_on_giving_SpellScript::Register(), spell_death_knight_initiate_visual::Register(), spell_q12779_an_end_to_all_things::Register(), spell_kormok_summon_bone_mages::Register(), spell_kormok_summon_bone_minions::Register(), spell_apothecary_lingering_fumes::Register(), spell_apothecary_validate_area::Register(), spell_apothecary_throw_cologne::Register(), spell_apothecary_throw_perfume::Register(), spell_madrigosa_activate_barrier::spell_madrigosa_activate_barrier_SpellScript::Register(), spell_madrigosa_deactivate_barrier::spell_madrigosa_deactivate_barrier_SpellScript::Register(), spell_brutallus_burn::spell_brutallus_burn_SpellScript::Register(), spell_eredar_twins_blaze::spell_eredar_twins_blaze_SpellScript::Register(), spell_felmyst_fog_of_corruption::spell_felmyst_fog_of_corruption_SpellScript::Register(), spell_kalecgos_spectral_blast_dummy::spell_kalecgos_spectral_blast_dummy_SpellScript::Register(), spell_kalecgos_spectral_realm_dummy::spell_kalecgos_spectral_realm_dummy_SpellScript::Register(), spell_kiljaeden_sinister_reflection::spell_kiljaeden_sinister_reflection_SpellScript::Register(), spell_kiljaeden_flame_dart::spell_kiljaeden_flame_dart_SpellScript::Register(), spell_kiljaeden_power_of_the_blue_flight::spell_kiljaeden_power_of_the_blue_flight_SpellScript::Register(), spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript::Register(), spell_entropius_black_hole_effect::spell_entropius_black_hole_effect_SpellScript::Register(), spell_razelikh_teleport_group::spell_razelikh_teleport_group_SpellScript::Register(), spell_blight_worm_ingest::spell_blight_worm_ingest_SpellScript::Register(), spell_gahzranka_slam::Register(), spell_blood_siphon::Register(), spell_batrider_bomb::Register(), spell_mandokir_charge::Register(), spell_threatening_gaze_charge::Register(), spell_axe_flurry::Register(), spell_brewfest_apple_trap::Register(), spell_q11117_catch_the_wild_wolpertinger::Register(), spell_brewfest_toss_mug::Register(), spell_brewfest_add_mug::Register(), spell_direbrew_summon_mole_machine_target_picker::Register(), spell_send_mug_target_picker::Register(), spell_request_second_mug::Register(), spell_hallows_end_trick::Register(), spell_hallows_end_put_costume::Register(), spell_hallows_end_trick_or_treat::Register(), spell_hallows_end_candy::Register(), spell_hallows_end_tricky_treat::Register(), spell_hallows_end_bucket_lands::Register(), spell_item_create_heart_candy::Register(), spell_midsummer_fling_torch::Register(), spell_midsummer_juggling_torch::Register(), spell_midsummer_torch_catch::Register(), spell_pilgrims_bounty_pass_generic::Register(), spell_pilgrims_bounty_feast_on_generic::Register(), spell_pilgrims_bounty_turkey_tracker::Register(), spell_pilgrims_bounty_food::Register(), spell_winter_veil_mistletoe::Register(), spell_winter_wondervolt_trap::Register(), spell_winter_veil_racer_slam_hit::Register(), spell_winter_veil_shoot_air_rifle::Register(), spell_red_sky_effect::spell_red_sky_effect_SpellScript::Register(), spell_finger_of_death::spell_finger_of_death_SpellScript::Register(), spell_hand_of_death::spell_hand_of_death_SpellScript::Register(), spell_ayamiss_swarmer_teleport_trigger::Register(), spell_ayamiss_swarmer_swarm::Register(), spell_ayamiss_swarmer_start_loop::Register(), spell_gen_ayamiss_swarmer_loop::Register(), spell_egg_explosion::Register(), spell_moam_mana_drain_filter::Register(), spell_moam_summon_mana_fiends::Register(), spell_rajaxx_thundercrash::Register(), spell_drain_mana::Register(), spell_vem_knockback::Register(), spell_mana_burn_area::Register(), spell_aggro_drones::Register(), spell_voljin_war_drums::spell_voljin_war_drums_SpellScript::Register(), spell_voodoo::spell_voodoo_SpellScript::Register(), spell_ooze_zap::spell_ooze_zap_SpellScript::Register(), spell_ooze_zap_channel_end::spell_ooze_zap_channel_end_SpellScript::Register(), spell_energize_aoe::spell_energize_aoe_SpellScript::Register(), spell_zulfarrak_unlocking::spell_zulfarrak_unlocking_SpellScript::Register(), spell_ahn_kahet_swarmer_aura::Register(), spell_volazj_whisper::Register(), spell_prince_taldaram_conjure_flame_sphere::Register(), spell_azjol_nerub_pound::Register(), spell_azjol_nerub_fixate::spell_azjol_nerub_fixate_SpellScript::Register(), spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::Register(), spell_halion_meteor_strike_targeting::spell_halion_meteor_strike_targeting_SpellScript::Register(), spell_halion_blazing_aura::spell_halion_blazing_aura_SpellScript::Register(), spell_halion_clear_debuffs::spell_halion_clear_debuffs_SpellScript::Register(), spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::Register(), spell_halion_twilight_mending::spell_halion_twilight_mending_SpellScript::Register(), spell_saviana_conflagration_init::spell_saviana_conflagration_init_SpellScript::Register(), spell_saviana_conflagration_throwback::spell_saviana_conflagration_throwback_SpellScript::Register(), spell_mistress_kiss_area::spell_mistress_kiss_area_SpellScript::Register(), spell_dred_raptor_call::spell_dred_raptor_call_SpellScript::Register(), spell_novos_despawn_crystal_handler::spell_novos_despawn_crystal_handler_SpellScript::Register(), spell_novos_summon_minions::spell_novos_summon_minions_SpellScript::Register(), spell_tharon_ja_clear_gift_of_tharon_ja::spell_tharon_ja_clear_gift_of_tharon_ja_SpellScript::Register(), spell_trollgore_consume::spell_trollgore_consume_SpellScript::Register(), spell_trollgore_invader_taunt::spell_trollgore_invader_taunt_SpellScript::Register(), spell_dtk_summon_random_drakkari::spell_dtk_summon_random_drakkari_SpellScript::Register(), spell_pos_slave_trigger_closest::spell_pos_slave_trigger_closestSpellScript::Register(), spell_pos_rimefang_frost_nova::spell_pos_rimefang_frost_novaSpellScript::Register(), spell_drakkari_colossus_emerge::spell_drakkari_colossus_emerge_SpellScript::Register(), spell_drakkari_colossus_surge::spell_drakkari_colossus_surge_SpellScript::Register(), spell_drakkari_colossus_face_me::spell_drakkari_colossus_face_me_SpellScript::Register(), spell_galdarah_impaling_charge::spell_galdarah_impaling_charge_SpellScript::Register(), spell_galdarah_transform::spell_galdarah_transform_SpellScript::Register(), spell_taldaram_glittering_sparks::spell_taldaram_glittering_sparks_SpellScript::Register(), spell_taldaram_summon_flame_ball::spell_taldaram_summon_flame_ball_SpellScript::Register(), spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::Register(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::Register(), spell_blood_queen_presence_of_the_darkfallen::spell_blood_queen_presence_of_the_darkfallen_SpellScript::Register(), spell_deathbringer_blood_link::spell_deathbringer_blood_link_SpellScript::Register(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::Register(), spell_festergut_gastric_bloat::spell_festergut_gastric_bloat_SpellScript::Register(), spell_igb_teleport_to_enemy_ship::spell_igb_teleport_to_enemy_ship_SpellScript::Register(), spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::Register(), spell_igb_burning_pitch_selector::spell_igb_burning_pitch_selector_SpellScript::Register(), spell_igb_burning_pitch::spell_igb_burning_pitch_SpellScript::Register(), spell_igb_rocket_artillery::spell_igb_rocket_artillery_SpellScript::Register(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::Register(), spell_marrowgar_bone_spike_graveyard::spell_marrowgar_bone_spike_graveyard_SpellScript::Register(), spell_marrowgar_coldflame_bonestorm::spell_marrowgar_coldflame_SpellScript::Register(), spell_putricide_slime_puddle::spell_putricide_slime_puddle_SpellScript::Register(), spell_putricide_unstable_experiment::spell_putricide_unstable_experiment_SpellScript::Register(), spell_putricide_ooze_eruption_searcher::spell_putricide_ooze_eruption_searcher_SpellScript::Register(), spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::Register(), spell_putricide_choking_gas_bomb::spell_putricide_choking_gas_bomb_SpellScript::Register(), spell_putricide_clear_aura_effect_value::spell_putricide_clear_aura_effect_value_SpellScript::Register(), spell_putricide_eat_ooze::spell_putricide_eat_ooze_SpellScript::Register(), spell_putricide_regurgitated_ooze::spell_putricide_regurgitated_ooze_SpellScript::Register(), spell_rotface_little_ooze_combine::spell_rotface_little_ooze_combine_SpellScript::Register(), spell_rotface_large_ooze_combine::spell_rotface_large_ooze_combine_SpellScript::Register(), spell_rotface_large_ooze_buff_combine::spell_rotface_large_ooze_buff_combine_SpellScript::Register(), spell_rotface_unstable_ooze_explosion_init::spell_rotface_unstable_ooze_explosion_init_SpellScript::Register(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::Register(), spell_sindragosa_icy_grip::spell_sindragosa_icy_grip_SpellScript::Register(), spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript::Register(), spell_frostwarden_handler_focus_fire::spell_frostwarden_handler_focus_fire_SpellScript::Register(), spell_the_lich_king_jump::spell_the_lich_king_jump_SpellScript::Register(), spell_the_lich_king_jump_remove_aura::spell_the_lich_king_jump_SpellScript::Register(), spell_the_lich_king_play_movie::spell_the_lich_king_play_movie_SpellScript::Register(), spell_the_lich_king_raging_spirit::spell_the_lich_king_raging_spirit_SpellScript::Register(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::Register(), spell_the_lich_king_cast_back_to_caster::spell_the_lich_king_cast_back_to_caster_SpellScript::Register(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::Register(), spell_the_lich_king_summon_spirit_bomb::spell_the_lich_king_summon_spirit_bomb_SpellScript::Register(), spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript::Register(), spell_dreamwalker_twisted_nightmares::spell_dreamwalker_twisted_nightmares_SpellScript::Register(), spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript::Register(), spell_dreamwalker_summon_suppresser_effect::spell_dreamwalker_summon_suppresser_effect_SpellScript::Register(), spell_frost_giant_death_plague::spell_frost_giant_death_plague_SpellScript::Register(), spell_icc_harvest_blight_specimen::spell_icc_harvest_blight_specimen_SpellScript::Register(), spell_svalna_remove_spear::spell_svalna_remove_spear_SpellScript::Register(), spell_stinky_precious_decimate::spell_stinky_precious_decimate_SpellScript::Register(), spell_ioc_bomb_blast_criteria::spell_ioc_bomb_blast_criteria_SpellScript::Register(), spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript::Register(), spell_ioc_launch::spell_ioc_launch_SpellScript::Register(), spell_four_horsemen_consumption::Register(), spell_gluth_decimate::spell_gluth_decimate_SpellScript::Register(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::Register(), spell_thaddius_polarity_shift::spell_thaddius_polarity_shift_SpellScript::Register(), spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript::Register(), spell_oculus_touch_the_nightmare::spell_oculus_touch_the_nightmare_SpellScript::Register(), spell_loken_pulsing_shockwave::spell_loken_pulsing_shockwave_SpellScript::Register(), spell_krystallus_shatter::spell_krystallus_shatter_SpellScript::Register(), spell_algalon_trigger_3_adds::spell_algalon_trigger_3_adds_SpellScript::Register(), spell_assembly_meltdown::spell_assembly_meltdown_SpellScript::Register(), spell_ignis_grab_initial::spell_ignis_grab_initial_SpellScript::Register(), spell_ulduar_squeezed_lifeless::spell_ulduar_squeezed_lifeless_SpellScript::Register(), spell_xt002_gravity_bomb_damage::spell_xt002_gravity_bomb_damage_SpellScript::Register(), spell_yogg_saron_destabilization_matrix::spell_yogg_saron_destabilization_matrix_SpellScript::Register(), spell_yogg_saron_titanic_storm::spell_yogg_saron_titanic_storm_SpellScript::Register(), spell_yogg_saron_insane_periodic_trigger::spell_yogg_saron_insane_periodic_trigger_SpellScript::Register(), spell_yogg_saron_sanity_reduce::spell_yogg_saron_sanity_reduce_SpellScript::Register(), spell_yogg_saron_empowering_shadows::spell_yogg_saron_empowering_shadows_SpellScript::Register(), spell_yogg_saron_target_selectors::spell_yogg_saron_target_selectors_SpellScript::Register(), spell_svala_ritual_strike::spell_svala_ritual_strike_SpellScript::Register(), spell_archavon_rock_shards::spell_archavon_rock_shards_SpellScript::Register(), spell_voa_flaming_cinder::spell_voa_flaming_cinder_SpellScript::Register(), spell_arcane_chains_character_force_cast::spell_arcane_chains_character_force_cast_SpellScript::Register(), spell_q12237_rescue_villager::Register(), spell_q24545_aod_special::spell_q24545_aod_special_SpellScript::Register(), spell_q12096_q12092_dummy::spell_q12096_q12092_dummy_SpellScript::Register(), spell_q12096_q12092_bark::spell_q12096_q12092_bark_SpellScript::Register(), spell_shredder_delivery::spell_shredder_delivery_SpellScript::Register(), spell_vehicle_warhead_fuse::spell_vehicle_warhead_fuse_SpellScript::Register(), spell_warhead_detonate::spell_warhead_detonate_SpellScript::Register(), spell_switch_infragreen_bomber_station::spell_switch_infragreen_bomber_station_SpellScript::Register(), spell_charge_shield_bomber::spell_charge_shield_bomber_SpellScript::Register(), spell_fight_fire_bomber::spell_fight_fire_bomber_SpellScript::Register(), spell_deliver_gryphon::Register(), spell_q12726_song_of_wind_and_water::spell_q12726_song_of_wind_and_water_SpellScript::Register(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::Register(), spell_shango_tracks::spell_shango_tracks_SpellScript::Register(), spell_q12611_deathbolt::Register(), spell_q13007_iron_colossus::spell_q13007_iron_colossus_SpellScript::Register(), spell_q12823_remove_collapsing_cave_aura::Register(), spell_wintergrasp_force_building::spell_wintergrasp_force_building_SpellScript::Register(), spell_wintergrasp_portal::spell_wintergrasp_portal_SpellScript::Register(), spell_gurtogg_eject::spell_gurtogg_eject_SpellScript::Register(), spell_illidan_draw_soul::spell_illidan_draw_soul_SpellScript::Register(), spell_illidan_parasitic_shadowfiend_trigger::spell_illidan_parasitic_shadowfiend_trigger_SpellScript::Register(), spell_illidan_glaive_throw::spell_illidan_glaive_throw_SpellScript::Register(), spell_illidan_flame_burst::spell_illidan_flame_burst_SpellScript::Register(), spell_illidan_found_target::spell_illidan_found_target_SpellScript::Register(), spell_illidan_cage_trap::spell_illidan_cage_trap_SpellScript::Register(), spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::Register(), spell_mother_shahraz_fatal_attraction_dummy::spell_mother_shahraz_fatal_attraction_dummy_SpellScript::Register(), spell_najentus_needle_spine::spell_najentus_needle_spine_SpellScript::Register(), spell_najentus_hurl_spine::spell_najentus_hurl_spine_SpellScript::Register(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::Register(), spell_illidari_council_judgement::spell_illidari_council_judgement_SpellScript::Register(), spell_black_template_free_friend::spell_black_template_free_friend_SpellScript::Register(), spell_black_temple_bloodbolt::spell_black_temple_bloodbolt_SpellScript::Register(), spell_lady_vashj_remove_tainted_cores::spell_lady_vashj_remove_tainted_cores_SpellScript::Register(), spell_lady_vashj_summon_sporebat::spell_lady_vashj_summon_sporebat_SpellScript::Register(), spell_lady_vashj_spore_drop_effect::spell_lady_vashj_spore_drop_effect_SpellScript::Register(), spell_leotheras_whirlwind::spell_leotheras_whirlwind_SpellScript::Register(), spell_leotheras_chaos_blast::spell_leotheras_chaos_blast_SpellScript::Register(), spell_leotheras_clear_consuming_madness::spell_leotheras_clear_consuming_madness_SpellScript::Register(), spell_morogrim_tidewalker_watery_grave::spell_morogrim_tidewalker_watery_grave_SpellScript::Register(), spell_morogrim_tidewalker_water_globule_new_target::spell_morogrim_tidewalker_water_globule_new_target_SpellScript::Register(), spell_serpentshrine_cavern_serpentshrine_parasite_trigger::spell_serpentshrine_cavern_serpentshrine_parasite_trigger_SpellScript::Register(), spell_despawn_underbog_mushrooms::Register(), spell_the_black_stalker_levitate::Register(), spell_the_black_stalker_someone_grab_me::Register(), spell_the_black_stalker_magnetic_pull::Register(), spell_gruul_ground_slam::spell_gruul_ground_slam_SpellScript::Register(), spell_gruul_shatter::spell_gruul_shatter_SpellScript::Register(), spell_vazruden_fireball::spell_vazruden_fireball_SpellScript::Register(), spell_vazruden_call_nazan::spell_vazruden_call_nazan_SpellScript::Register(), spell_magtheridon_blaze::spell_magtheridon_blaze_SpellScript::Register(), spell_tsh_shoot_flame_arrow::spell_tsh_shoot_flame_arrow_SpellScript::Register(), spell_commander_sarannis_summon_reinforcements::spell_commander_sarannis_summon_reinforcements_SpellScript::Register(), spell_alar_ember_blast::spell_alar_ember_blast_SpellScript::Register(), spell_kaelthas_summon_weapons::spell_kaelthas_summon_weapons_SpellScript::Register(), spell_kaelthas_gravity_lapse::spell_kaelthas_gravity_lapse_SpellScript::Register(), spell_kaelthas_nether_beam::spell_kaelthas_nether_beam_SpellScript::Register(), spell_kaelthas_summon_nether_vapor::spell_kaelthas_summon_nether_vapor_SpellScript::Register(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::Register(), spell_capacitus_polarity_shift::spell_capacitus_polarity_shift_SpellScript::Register(), spell_oscillating_field::spell_oscillating_field_SpellScript::Register(), spell_q10935_the_exorcism_of_colonel_jules::spell_q10935_the_exorcism_of_colonel_jules_SpellScript::Register(), spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript::Register(), spell_pet_dk_gargoyle_strike::Register(), spell_dk_raise_ally::Register(), spell_dk_corpse_explosion::Register(), spell_dk_death_coil::Register(), spell_dk_death_gate::Register(), spell_dk_death_grip::Register(), spell_dk_death_strike::Register(), spell_dk_ghoul_explode::Register(), spell_dk_pestilence::Register(), spell_dk_raise_dead::Register(), spell_dk_scourge_strike::Register(), spell_dru_glyph_of_starfire::Register(), spell_dru_starfall_dummy::Register(), spell_dru_typhoon::Register(), spell_gen_5000_gold::Register(), spell_the_flag_of_ownership::Register(), spell_gen_mine_sweeper::Register(), spell_gen_fixate::Register(), spell_gen_knock_away::Register(), spell_gen_hate_to_zero::Register(), spell_gen_focused_bursts::Register(), spell_gen_throw_back::Register(), spell_gen_clear_debuffs::Register(), spell_gen_create_lance::Register(), spell_gen_netherbloom::Register(), spell_gen_nightmare_vine::Register(), spell_gen_pet_summoned::Register(), spell_gen_remove_flight_auras::Register(), spell_gen_elune_candle::Register(), spell_gen_teleporting::Register(), spell_gen_divine_storm_cd_reset::Register(), spell_gen_profession_research::Register(), spell_gen_clone::Register(), spell_gen_clone_weapon::Register(), spell_gen_seaforium_blast::Register(), spell_gen_dummy_trigger::Register(), spell_gen_spirit_healer_res::Register(), spell_gen_gadgetzan_transporter_backfire::Register(), spell_gen_gnomish_transporter::Register(), spell_gen_dalaran_disguise::Register(), spell_gen_break_shield::Register(), spell_gen_mounted_charge::Register(), spell_gen_throw_shield::Register(), spell_gen_tournament_duel::Register(), spell_gen_ds_flush_knockback::Register(), spell_gen_despawn_self::Register(), spell_gen_mount::Register(), spell_gen_upper_deck_create_foam_sword::Register(), spell_gen_bonked::Register(), spell_gen_spectator_cheer_trigger::Register(), spell_gen_vendor_bark_trigger::Register(), spell_gen_eject_passenger::Register(), spell_gen_remove_impairing_auras::Register(), spell_freezing_circle::Register(), spell_hun_chimera_shot::Register(), spell_hun_invigoration::Register(), spell_hun_last_stand_pet::Register(), spell_hun_masters_call::Register(), spell_hun_readiness::Register(), spell_hun_scatter_shot::Register(), spell_hun_pet_heart_of_the_phoenix::Register(), spell_item_massive_seaforium_charge::Register(), spell_item_titanium_seal_of_dalaran::Register(), spell_item_mind_amplify_dish::Register(), spell_item_runescroll_of_fortitude::Register(), spell_item_branns_communicator::Register(), spell_item_magic_dust::Register(), spell_item_toy_train_set::Register(), spell_item_sleepy_willy::Register(), spell_item_toxic_wasteling::Register(), spell_item_lil_xt::Register(), spell_item_crazy_alchemists_potion::Register(), spell_item_feast::Register(), spell_item_gnomish_universal_remote::Register(), spell_item_powerful_anti_venom::Register(), spell_item_strong_anti_venom::Register(), spell_item_anti_venom::Register(), spell_item_gnomish_shrink_ray::Register(), spell_item_goblin_weather_machine::Register(), spell_item_light_lamp::Register(), spell_item_oracle_ablutions::Register(), spell_item_direbrew_remote::Register(), spell_item_brittle_armor::Register(), spell_item_defibrillate::Register(), spell_item_gnomish_death_ray::Register(), spell_item_mercurial_shield::Register(), spell_item_net_o_matic::Register(), spell_item_piccolo_of_the_flaming_fire::Register(), spell_item_scroll_of_recall::Register(), spell_item_dimensional_ripper_area52::Register(), spell_item_six_demon_bag::Register(), spell_item_book_of_glyph_mastery::Register(), spell_item_shimmering_vessel::Register(), spell_item_purify_helboar_meat::Register(), spell_item_crystal_prison_dummy_dnd::Register(), spell_item_reindeer_transformation::Register(), spell_item_nigh_invulnerability::Register(), spell_item_poultryizer::Register(), spell_item_socrethars_stone::Register(), spell_item_demon_broiled_surprise::Register(), spell_item_complete_raptor_capture::Register(), spell_item_impale_leviroth::Register(), spell_item_brewfest_mount_transformation::Register(), spell_item_nitro_boots::Register(), spell_item_teach_language::Register(), spell_item_rocket_boots::Register(), spell_item_runic_healing_injector::Register(), spell_item_pygmy_oil::Register(), spell_item_unusual_compass::Register(), spell_item_chicken_cover::Register(), spell_item_refocus::Register(), spell_item_muisek_vessel::Register(), spell_item_greatmothers_soulcatcher::Register(), spell_item_eggnog::Register(), spell_item_linken_boomerang::Register(), spell_item_mirrens_drinking_hat::Register(), spell_item_freeze_rookery_egg::Register(), spell_item_elixir_of_shadows::Register(), spell_item_worn_troll_dice::Register(), spell_mage_burnout_trigger::Register(), spell_mage_blast_wave::Register(), spell_mage_polymorph_cast_visual::Register(), spell_pal_blessing_of_faith::Register(), spell_pal_divine_storm_dummy::Register(), spell_pal_guarded_by_the_light::Register(), spell_pal_holy_shock::Register(), spell_pal_judgement::Register(), spell_pal_judgement_of_command::Register(), spell_pal_righteous_defense::Register(), spell_pri_lightwell::Register(), spell_pri_pain_and_suffering_proc::Register(), spell_pri_penance::Register(), spell_image_of_drakuru_reagent_check::Register(), spell_q11026_a11051_banish_the_demons::Register(), spell_q10714_on_spirits_wings::Register(), spell_q10720_the_smallest_creature::Register(), spell_q12943_shadow_vault_decree::Register(), spell_q10769_dissension_amongst_the_ranks::Register(), spell_q11520_discovering_your_roots::Register(), spell_q12274_a_fall_from_grace_costume::Register(), spell_q13369_fate_up_against_your_will::Register(), spell_q11198_take_down_tethyr::Register(), spell_q11653_youre_not_so_big_now::Register(), spell_generic_quest_update_entry_SpellScript::Register(), spell_q1846_bending_shinbone::Register(), spell_q6124_6129_apply_salve::Register(), spell_q11396_11399_scourging_crystal_controller::Register(), spell_q11396_11399_scourging_crystal_controller_dummy::Register(), spell_q11587_arcane_prisoner_rescue::Register(), spell_q11730_ultrasonic_screwdriver::Register(), spell_q12459_seeds_of_natures_wrath::Register(), spell_q12937_relief_for_the_fallen::Register(), spell_q10041_q10040_who_are_they::Register(), spell_symbol_of_life_dummy::Register(), spell_q12659_ahunaes_knife::Register(), spell_q9874_liquid_fire::Register(), spell_q12805_lifeblood_dummy::Register(), spell_q14112_14145_chum_the_water::Register(), spell_q9452_cast_net::Register(), spell_q12277_wintergarde_mine_explosion::Register(), spell_q12066_bunny_kill_credit::Register(), spell_q12735_song_of_cleansing::Register(), spell_q11010_q11102_q11023_aggro_check::Register(), spell_q13291_q13292_q13239_q13261_frostbrood_skytalon_grab_decoy::Register(), spell_q13011_bear_flank_master::Register(), spell_q12690_burst_at_the_seams::Register(), spell_q12641_death_comes_from_on_high::Register(), spell_q12919_gymers_grab::Register(), spell_q12919_gymers_throw::Register(), spell_rog_killing_spree::spell_rog_killing_spree_SpellScript::Register(), spell_rog_preparation::Register(), spell_rog_shiv::Register(), spell_sha_ancestral_awakening_proc::Register(), spell_sha_chain_heal::Register(), spell_sha_cleansing_totem_pulse::Register(), spell_sha_fire_nova::Register(), spell_sha_healing_stream_totem::Register(), spell_sha_lava_lash::Register(), spell_sha_mana_spring_totem::Register(), spell_sha_mana_tide_totem::Register(), spell_sha_thunderstorm::Register(), spell_warl_shadowflame::Register(), spell_warl_demonic_empowerment::Register(), spell_warl_create_healthstone::Register(), spell_warl_everlasting_affliction::Register(), spell_warl_soulshatter::Register(), spell_warl_life_tap::Register(), spell_warr_intervene::Register(), spell_warr_deep_wounds::Register(), spell_warr_charge::Register(), spell_warr_slam::Register(), spell_warr_execute::Register(), spell_warr_concussion_blow::Register(), spell_warr_bloodthirst::Register(), spell_warr_overpower::Register(), spell_warr_shattering_throw::Register(), spell_warr_vigilance_trigger::Register(), spell_dream_fog_sleep::spell_dream_fog_sleep_SpellScript::Register(), and spell_mark_of_nature::spell_mark_of_nature_SpellScript::Register().
OnEffectLaunch
HookList<EffectHandler> SpellScript::OnEffectLaunch
Referenced by _Validate(), spell_blackrock_spire_call_of_vaelastrasz::Register(), spell_uldaman_sub_boss_agro_keepers::spell_uldaman_sub_boss_agro_keepers_SpellScript::Register(), spell_uldaman_boss_agro_archaedas::spell_uldaman_boss_agro_archaedas_SpellScript::Register(), spell_bh_cleanse_quel_delar::spell_bh_cleanse_quel_delar_SpellScript::Register(), spell_winter_veil_racer_rocket_slam::Register(), spell_halion_summon_exit_portals::spell_halion_summon_exit_portals_SpellScript::Register(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::Register(), spell_the_lich_king_vile_spirits_visual::spell_the_lich_king_vile_spirits_visual_SpellScript::Register(), spell_icc_yd_summon_undead::spell_icc_yd_summon_undead_SpellScript::Register(), spell_anti_air_rocket_bomber::spell_anti_air_rocket_bomber_SpellScript::Register(), spell_q10036_torgos::spell_q10036_torgos_SpellScript::Register(), spell_q10923_evil_draws_near_summon::spell_q10923_evil_draws_near_summon_SpellScript::Register(), spell_mage_arcane_blast::Register(), and spell_q13086_last_line_of_defence::Register().
OnEffectLaunchTarget
HookList<EffectHandler> SpellScript::OnEffectLaunchTarget
Referenced by _Validate(), spell_class_call_handler::Register(), spell_chapter5_rebuke::spell_chapter5_rebuke_SpellScript::Register(), spell_threatening_gaze_charge::Register(), spell_sindragosa_icy_grip_jump::spell_sindragosa_icy_grip_jump_SpellScript::Register(), spell_dk_ghoul_explode::Register(), spell_item_toxic_wasteling::Register(), spell_item_linken_boomerang::Register(), spell_mage_arcane_blast::Register(), spell_pal_righteous_defense::Register(), spell_pri_prayer_of_mending_heal::Register(), and spell_warr_bloodthirst_heal::Register().
OnHit
HookList<HitHandler> SpellScript::OnHit
Referenced by spell_class_call_handler::Register(), spell_egg_event::spell_egg_eventSpellScript::Register(), spell_hakkar_power_down::Register(), spell_random_aggro::Register(), spell_delusions_of_jindo::Register(), spell_enveloping_webs::Register(), spell_arcane_vacuum::Register(), spell_mark_of_frost_freeze::Register(), spell_mutate_explode_bug::Register(), spell_explode_trigger::Register(), spell_summon_toxin_slime::Register(), spell_baltharus_enervating_brand_trigger::spell_baltharus_enervating_brand_trigger_SpellScript::Register(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript::Register(), spell_bronjahm_magic_bane::spell_bronjahm_magic_bane_SpellScript::Register(), spell_blood_council_shadow_prison_damage::spell_blood_council_shadow_prison_SpellScript::Register(), spell_marrowgar_bone_storm::spell_marrowgar_bone_storm_SpellScript::Register(), spell_marrowgar_bone_slice::spell_marrowgar_bone_slice_SpellScript::Register(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript::Register(), spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript::Register(), spell_the_lich_king_trigger_vile_spirit::spell_the_lich_king_trigger_vile_spirit_SpellScript::Register(), spell_oculus_shock_lance::spell_oculus_shock_lance_SpellScript::Register(), spell_krystallus_shatter_effect::spell_krystallus_shatter_effect_SpellScript::Register(), spell_algalon_cosmic_smash_damage::spell_algalon_cosmic_smash_damage_SpellScript::Register(), spell_algalon_supermassive_fail::spell_algalon_supermassive_fail_SpellScript::Register(), spell_xt002_tympanic_tantrum::spell_xt002_tympanic_tantrum_SpellScript::Register(), spell_voa_lightning_nova::spell_voa_lightning_nova_SpellScript::Register(), spell_wg_reduce_damage_by_distance::spell_wg_reduce_damage_by_distance_SpellScript::Register(), spell_murmur_sonic_boom_effect::spell_murmur_sonic_boom_effect_SpellScript::Register(), spell_gruul_shatter_effect::spell_gruul_shatter_effect_SpellScript::Register(), spell_pet_gen_valkyr_guardian_smite::Register(), spell_dk_death_and_decay::Register(), spell_dk_rune_of_the_fallen_crusader::Register(), spell_gen_reduced_above_60::Register(), spell_gen_count_pct_from_max_hp::Register(), spell_item_wraith_scythe_drain_life::Register(), spell_pri_shadow_word_death::Register(), and spell_warr_mocking_blow::Register().
OnObjectAreaTargetSelect
HookList<ObjectAreaTargetSelectHandler> SpellScript::OnObjectAreaTargetSelect
Referenced by _Validate(), spell_suppression_aura::Register(), spell_class_call_handler::Register(), spell_class_call_polymorph::Register(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::Register(), spell_apothecary_validate_area::Register(), spell_felmyst_open_brutallus_back_doors::spell_felmyst_open_brutallus_back_doors_SpellScript::Register(), spell_kalecgos_spectral_blast_dummy::spell_kalecgos_spectral_blast_dummy_SpellScript::Register(), spell_kiljaeden_sinister_reflection::spell_kiljaeden_sinister_reflection_SpellScript::Register(), spell_kiljaeden_sinister_reflection_clone::spell_kiljaeden_sinister_reflection_clone_SpellScript::Register(), spell_kiljaeden_dragon_breath::spell_kiljaeden_dragon_breath_SpellScript::Register(), spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript::Register(), spell_gahzranka_slam::Register(), spell_blood_siphon::Register(), spell_chain_burn::Register(), spell_hatch_eggs::Register(), spell_axe_flurry::Register(), spell_brewfest_apple_trap::Register(), spell_brewfest_toss_mug::Register(), spell_send_mug_target_picker::Register(), spell_mark_of_kazrogal::spell_mark_of_kazrogal_SpellScript::Register(), spell_moam_mana_drain_filter::Register(), spell_crystal_weakness::Register(), spell_aq_shadow_storm::Register(), spell_vem_vengeance::Register(), spell_cthun_dark_glare::Register(), spell_huhuran_poison_bolt::Register(), spell_skeram_arcane_explosion::Register(), spell_mutate_explode_bug::Register(), spell_energize_aoe::spell_energize_aoe_SpellScript::Register(), spell_ahn_kahet_swarmer_aura::Register(), spell_herald_volzaj_insanity::Register(), spell_halion_twilight_cutter::spell_halion_twilight_cutter_SpellScript::Register(), spell_eadric_radiance::spell_eadric_radiance_SpellScript::Register(), spell_toc5_light_rain::spell_toc5_light_rain_SpellScript::Register(), spell_mistress_kiss_area::spell_mistress_kiss_area_SpellScript::Register(), spell_bronjahm_soulstorm_targeting::spell_bronjahm_soulstorm_targeting_SpellScript::Register(), spell_garfrost_permafrost::spell_garfrost_permafrost_SpellScript::Register(), spell_blood_queen_pact_of_the_darkfallen::spell_blood_queen_pact_of_the_darkfallen_SpellScript::Register(), spell_blood_queen_pact_of_the_darkfallen_dmg_target::spell_blood_queen_pact_of_the_darkfallen_dmg_SpellScript::Register(), spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::Register(), spell_blood_queen_swarming_shadows_floor_dmg::spell_blood_queen_swarming_shadows_floor_dmg_SpellScript::Register(), spell_deathbringer_blood_nova_targeting::spell_deathbringer_blood_nova_targeting_SpellScript::Register(), spell_deathbringer_boiling_blood::spell_deathbringer_boiling_blood_SpellScript::Register(), spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::Register(), spell_igb_explosion::spell_igb_explosion_SpellScript::Register(), spell_igb_teleport_players_on_victory::spell_igb_teleport_players_on_victory_SpellScript::Register(), spell_igb_burning_pitch_selector::spell_igb_burning_pitch_selector_SpellScript::Register(), spell_igb_rocket_artillery::spell_igb_rocket_artillery_SpellScript::Register(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::Register(), spell_marrowgar_bone_slice::spell_marrowgar_bone_slice_SpellScript::Register(), spell_putricide_slime_puddle::spell_putricide_slime_puddle_SpellScript::Register(), spell_putricide_tear_gas_effect::spell_putricide_tear_gas_effect_SpellScript::Register(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::Register(), spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::Register(), spell_putricide_mutated_transformation_dmg::spell_putricide_mutated_transformation_dmg_SpellScript::Register(), spell_putricide_eat_ooze::spell_putricide_eat_ooze_SpellScript::Register(), spell_rotface_mutated_infection::spell_rotface_mutated_infection_SpellScript::Register(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::Register(), spell_sindragosa_unchained_magic::spell_sindragosa_unchained_magic_SpellScript::Register(), spell_sindragosa_ice_tomb_filter::spell_sindragosa_ice_tomb_filter_SpellScript::Register(), spell_sindragosa_ice_tomb::spell_sindragosa_ice_tomb_SpellScript::Register(), spell_sindragosa_mystic_buffet::spell_sindragosa_mystic_buffet_SpellScript::Register(), spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript::Register(), spell_the_lich_king_quake::spell_the_lich_king_quake_SpellScript::Register(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript::Register(), spell_the_lich_king_shadow_trap_periodic::spell_the_lich_king_shadow_trap_periodic_SpellScript::Register(), spell_the_lich_king_ice_burst_target_search::spell_the_lich_king_ice_burst_target_search_SpellScript::Register(), spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript::Register(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::Register(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::Register(), spell_the_lich_king_vile_spirit_damage_target_search::spell_the_lich_king_vile_spirit_damage_target_search_SpellScript::Register(), spell_the_lich_king_restore_soul::spell_the_lich_king_restore_soul_SpellScript::Register(), spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript::Register(), spell_frost_giant_death_plague::spell_frost_giant_death_plague_SpellScript::Register(), spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Register(), spell_gothik_shadow_bolt_volley::spell_gothik_shadow_bolt_volley_SpellScript::Register(), spell_grobbulus_poison::spell_grobbulus_poison_SpellScript::Register(), spell_kelthuzad_frost_blast::spell_kelthuzad_frost_blast_SpellScript::Register(), spell_sapphiron_frost_explosion::spell_sapphiron_frost_explosion_SpellScript::Register(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::Register(), spell_eoe_ph3_surge_of_power::spell_eoe_ph3_surge_of_power_SpellScript::Register(), spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript::Register(), spell_algalon_trigger_3_adds::spell_algalon_trigger_3_adds_SpellScript::Register(), spell_algalon_big_bang::spell_algalon_big_bang_SpellScript::Register(), spell_auriaya_sentinel_blast::spell_auriaya_sentinel_blast_SpellScript::Register(), spell_mark_of_the_faceless_drainhealth::spell_mark_of_the_faceless_drainhealth_SpellScript::Register(), spell_hodir_periodic_icicle::spell_hodir_periodic_icicle_SpellScript::Register(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_SpellScript::Register(), spell_ulduar_stone_grip_cast_target::spell_ulduar_stone_grip_cast_target_SpellScript::Register(), spell_kologarn_stone_shout::spell_kologarn_stone_shout_SpellScript::Register(), spell_xt002_tympanic_tantrum::spell_xt002_tympanic_tantrum_SpellScript::Register(), spell_xt002_gravity_bomb_aura::spell_xt002_gravity_bomb_aura_SpellScript::Register(), spell_xt002_searing_light_spawn_life_spark::spell_xt002_searing_light_spawn_life_spark_SpellScript::Register(), spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_SpellScript::Register(), spell_yogg_saron_destabilization_matrix::spell_yogg_saron_destabilization_matrix_SpellScript::Register(), spell_yogg_saron_titanic_storm::spell_yogg_saron_titanic_storm_SpellScript::Register(), spell_yogg_saron_lunatic_gaze::spell_yogg_saron_lunatic_gaze_SpellScript::Register(), spell_yogg_saron_insane_periodic_trigger::spell_yogg_saron_insane_periodic_trigger_SpellScript::Register(), spell_q24545_aod_special::spell_q24545_aod_special_SpellScript::Register(), spell_murmur_thundering_storm::spell_murmur_thundering_storm_SpellScript::Register(), spell_gurtogg_bloodboil::spell_gurtogg_bloodboil_SpellScript::Register(), spell_illidan_shadow_prison::spell_illidan_shadow_prison_SpellScript::Register(), spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::Register(), spell_reliquary_of_souls_fixate::spell_reliquary_of_souls_fixate_SpellScript::Register(), spell_leotheras_insidious_whisper::spell_leotheras_insidious_whisper_SpellScript::Register(), spell_lurker_below_spout_cone::spell_lurker_below_spout_cone_SpellScript::Register(), spell_morogrim_tidewalker_water_globule_new_target::spell_morogrim_tidewalker_water_globule_new_target_SpellScript::Register(), spell_tsh_shoot_flame_arrow::spell_tsh_shoot_flame_arrow_SpellScript::Register(), spell_kaelthas_mind_control::spell_kaelthas_mind_control_SpellScript::Register(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::Register(), spell_dk_wandering_plague::Register(), spell_dk_aotd_taunt::Register(), spell_dk_corpse_explosion::Register(), spell_dk_death_pact::Register(), spell_dk_raise_dead::Register(), spell_dk_rune_tap_party::Register(), spell_dru_starfall_aoe::Register(), spell_dru_starfall_dummy::Register(), spell_dru_t10_restoration_4p_bonus::Register(), spell_dru_wild_growth::Register(), spell_the_flag_of_ownership::Register(), spell_gen_rallying_cry_of_the_dragonslayer::Register(), spell_gen_adals_song_of_battle::Register(), spell_gen_select_target_count::Register(), spell_gen_replenishment::Register(), spell_hun_volley_trigger::Register(), spell_item_sleepy_willy::Register(), spell_item_fetch_ball::Register(), spell_item_echoes_of_light::Register(), spell_pal_seal_of_command::Register(), spell_pal_divine_storm_dummy::Register(), spell_pal_glyph_of_holy_light::Register(), spell_pri_circle_of_healing::Register(), spell_pri_divine_hymn::Register(), spell_pri_hymn_of_hope::Register(), spell_pri_mind_sear::Register(), spell_rog_killing_spree::spell_rog_killing_spree_SpellScript::Register(), spell_sha_ancestral_awakening_proc::Register(), spell_sha_bloodlust::Register(), spell_sha_earthen_power::Register(), spell_sha_heroism::Register(), spell_warr_improved_spell_reflection_trigger::Register(), spell_warr_intimidating_shout::Register(), spell_dream_fog_sleep::spell_dream_fog_sleep_SpellScript::Register(), and spell_mark_of_nature::spell_mark_of_nature_SpellScript::Register().
OnObjectTargetSelect
HookList<ObjectTargetSelectHandler> SpellScript::OnObjectTargetSelect
Referenced by _Validate(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::Register(), spell_tsh_shadow_bolt::spell_tsh_shadow_bolt_SpellScript::Register(), spell_dk_corpse_explosion::Register(), and spell_dk_raise_dead::Register().