AzeorthCore: SmartGameObjectAI Class Reference
SmartGameObjectAI Class Reference
#include "SmartAI.h"
Public Member Functions
SmartGameObjectAI (GameObject *g)
~SmartGameObjectAI () override
void UpdateAI (uint32 diff) override
void InitializeAI () override
void Reset () override
SmartScript * GetScript ()
bool GossipHello (Player *player, bool reportUse) override
bool GossipSelect (Player *player, uint32 sender, uint32 action) override
bool GossipSelectCode (Player *, uint32, uint32, const char *) override
bool QuestAccept (Player *player, Quest const *quest) override
bool QuestReward (Player *player, Quest const *quest, uint32 opt) override
void Destroyed (Player *player, uint32 eventId) override
void SetData (uint32 id, uint32 value) override
void SetScript9 (SmartScriptHolder &e, uint32 entry, Unit *invoker)
void OnGameEvent (bool start, uint16 eventId) override
void OnStateChanged (uint32 state, Unit *unit) override
void EventInform (uint32 eventId) override
void SpellHit (Unit *unit, SpellInfo const *spellInfo) override
void JustSummoned (Creature *creature) override
void SummonedCreatureDespawn (Creature *unit) override
void SummonedCreatureDies (Creature *summon, Unit *killer) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
Static Public Member Functions
static int32 Permissible (GameObject const *)
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes
SmartScript mScript
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
SmartGameObjectAI()
SmartGameObjectAI::SmartGameObjectAI (GameObject * g) inline
: GameObjectAI(g) {}
~SmartGameObjectAI()
SmartGameObjectAI::~SmartGameObjectAI () inline override
{}
Member Function Documentation
Destroyed()
void SmartGameObjectAI::Destroyed (Player * player, uint32 eventId) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_DEATH, player, eventId, 0, false, nullptr, me);
}
References GetScript(), GameObjectAI::me, SmartScript::ProcessEventsFor(), and SMART_EVENT_DEATH.
EventInform()
void SmartGameObjectAI::EventInform (uint32 eventId) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_GO_EVENT_INFORM, nullptr, eventId);
}
References GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_GO_EVENT_INFORM.
GetScript()
SmartScript * SmartGameObjectAI::GetScript () inline
{ return &mScript; }
References mScript.
Referenced by Destroyed(), EventInform(), GossipHello(), GossipSelect(), InitializeAI(), JustSummoned(), OnGameEvent(), OnStateChanged(), QuestAccept(), QuestReward(), Reset(), SetData(), SetScript9(), SpellHit(), SummonedCreatureDespawn(), SummonedCreatureDies(), and UpdateAI().
GossipHello()
bool SmartGameObjectAI::GossipHello (Player * player, bool reportUse) override virtual
Reimplemented from GameObjectAI.
{
    LOG_DEBUG("sql.sql", "SmartGameObjectAI::GossipHello");
    GetScript()->ProcessEventsFor(SMART_EVENT_GOSSIP_HELLO, player, (uint32)reportUse, 0, false, nullptr, me);
    return false;
}
References GetScript(), LOG_DEBUG, GameObjectAI::me, SmartScript::ProcessEventsFor(), and SMART_EVENT_GOSSIP_HELLO.
GossipSelect()
bool SmartGameObjectAI::GossipSelect (Player * player, uint32 sender, uint32 action) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_GOSSIP_SELECT, player, sender, action, false, nullptr, me);
    return false;
}
References GetScript(), GameObjectAI::me, SmartScript::ProcessEventsFor(), and SMART_EVENT_GOSSIP_SELECT.
GossipSelectCode()
bool SmartGameObjectAI::GossipSelectCode (Player * , uint32 , uint32 , const char *) override virtual
Reimplemented from GameObjectAI.
{
    return false;
}
InitializeAI()
void SmartGameObjectAI::InitializeAI () override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->OnInitialize(me);
    // Xinef: do not call respawn event if go is not spawned
    if (me->isSpawned())
        GetScript()->ProcessEventsFor(SMART_EVENT_RESPAWN);
    //Reset();
}
References GetScript(), GameObject::isSpawned(), GameObjectAI::me, SmartScript::OnInitialize(), SmartScript::ProcessEventsFor(), and SMART_EVENT_RESPAWN.
JustSummoned()
void SmartGameObjectAI::JustSummoned (Creature * creature) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_SUMMONED_UNIT, creature);
}
References GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_SUMMONED_UNIT.
OnGameEvent()
void SmartGameObjectAI::OnGameEvent (bool start, uint16 eventId) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(start ? SMART_EVENT_GAME_EVENT_START : SMART_EVENT_GAME_EVENT_END, nullptr, eventId);
}
References GetScript(), SmartScript::ProcessEventsFor(), SMART_EVENT_GAME_EVENT_END, and SMART_EVENT_GAME_EVENT_START.
OnStateChanged()
void SmartGameObjectAI::OnStateChanged (uint32 state, Unit * unit) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_GO_STATE_CHANGED, unit, state);
}
References GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_GO_STATE_CHANGED.
Permissible()
static int32 SmartGameObjectAI::Permissible (GameObject const *) inline static
{ return PERMIT_BASE_NO; }
References PERMIT_BASE_NO.
QuestAccept()
bool SmartGameObjectAI::QuestAccept (Player * player, Quest const * quest) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_ACCEPTED_QUEST, player, quest->GetQuestId(), 0, false, nullptr, me);
    return false;
}
References Quest::GetQuestId(), GetScript(), GameObjectAI::me, SmartScript::ProcessEventsFor(), and SMART_EVENT_ACCEPTED_QUEST.
QuestReward()
bool SmartGameObjectAI::QuestReward (Player * player, Quest const * quest, uint32 opt) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_REWARD_QUEST, player, quest->GetQuestId(), opt, false, nullptr, me);
    return false;
}
References Quest::GetQuestId(), GetScript(), GameObjectAI::me, SmartScript::ProcessEventsFor(), and SMART_EVENT_REWARD_QUEST.
Reset()
void SmartGameObjectAI::Reset () override virtual
Reimplemented from GameObjectAI.
{
    // Xinef: call respawn event on reset
    GetScript()->ProcessEventsFor(SMART_EVENT_RESPAWN);
    GetScript()->OnReset();
}
References GetScript(), SmartScript::OnReset(), SmartScript::ProcessEventsFor(), and SMART_EVENT_RESPAWN.
SetData()
void SmartGameObjectAI::SetData (uint32 id, uint32 value) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_DATA_SET, nullptr, id, value);
}
References GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_DATA_SET.
SetScript9()
void SmartGameObjectAI::SetScript9 (SmartScriptHolder & e, uint32 entry, Unit * invoker)
{
    if (invoker)
        GetScript()->mLastInvoker = invoker->GetGUID();
    GetScript()->SetScript9(e, entry);
}
References Object::GetGUID(), GetScript(), SmartScript::mLastInvoker, and SmartScript::SetScript9().
SpellHit()
void SmartGameObjectAI::SpellHit (Unit * unit, SpellInfo const * spellInfo) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_SPELLHIT, unit, 0, 0, false, spellInfo);
}
References GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_SPELLHIT.
SummonedCreatureDespawn()
void SmartGameObjectAI::SummonedCreatureDespawn (Creature * unit) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_SUMMON_DESPAWNED, unit, unit->GetEntry());
}
References Object::GetEntry(), GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_SUMMON_DESPAWNED.
SummonedCreatureDies()
void SmartGameObjectAI::SummonedCreatureDies (Creature * summon, Unit * killer) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->ProcessEventsFor(SMART_EVENT_SUMMONED_UNIT_DIES, summon);
}
References GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_SUMMONED_UNIT_DIES.
UpdateAI()
void SmartGameObjectAI::UpdateAI (uint32 diff) override virtual
Reimplemented from GameObjectAI.
{
    GetScript()->OnUpdate(diff);
}
References GetScript(), and SmartScript::OnUpdate().
Member Data Documentation
mScript
SmartScript SmartGameObjectAI::mScript protected
Referenced by GetScript().