AzerothCore: Position Struct Reference
Position Struct Reference
#include "Position.h"
Classes
struct PositionXYStreamer
struct PositionXYZOStreamer
struct PositionXYZStreamer
Public Member Functions
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
Position (Position &&)=default
Position & operator= (const Position &)=default
Position & operator= (Position &&)=default
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (Position const *pos, float width) const
std::string ToString () const
Static Public Member Functions
static float NormalizeOrientation (float o)
Public Attributes
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Detailed Description
Constructor & Destructor Documentation
Position() [1/3]
Position::Position (float x = 0, float y = 0, float z = 0, float o = 0) inline
            : m_positionX(x), m_positionY(y), m_positionZ(z), m_orientation(NormalizeOrientation(o)) { }
Position() [2/3]
Position::Position (Position const & loc) inline
{ Relocate(loc); }
References Relocate().
Position() [3/3]
Position::Position (Position &&) default
Member Function Documentation
GetAbsoluteAngle() [1/3]
float Position::GetAbsoluteAngle (float x, float y) const inline
    {
        return NormalizeOrientation(std::atan2(
                static_cast<float>(y - m_positionY),
                static_cast<float>(x - m_positionX))
        );
    }
References m_positionX, m_positionY, and NormalizeOrientation().
Referenced by Spell::EffectTeleUnitsFaceCaster(), Spell::SummonGuardian(), and CinematicMgr::UpdateCinematicLocation().
GetAbsoluteAngle() [2/3]
float Position::GetAbsoluteAngle (Position const & pos) const inline
{ return GetAbsoluteAngle(pos.m_positionX, pos.m_positionY); }
References GetAbsoluteAngle(), m_positionX, and m_positionY.
Referenced by GetAbsoluteAngle().
GetAbsoluteAngle() [3/3]
float Position::GetAbsoluteAngle (Position const * pos) const inline
{ return GetAbsoluteAngle(*pos); }
References GetAbsoluteAngle().
Referenced by GetAbsoluteAngle().
GetAngle() [1/2]
float Position::GetAngle (const Position * pos) const
{
    if (!obj)
        return 0;
    return GetAngle(obj->GetPositionX(), obj->GetPositionY());
}
References GetAngle(), GetPositionX(), and GetPositionY().
Referenced by Unit::_ExitVehicle(), Vehicle::AddPassenger(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::AttackStart(), npc_argent_captainAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_hover_disk::npc_hover_diskAI::DoAction(), npc_maiev_illidan::DoAction(), npc_time_rift::DoSummonAtRift(), ChaseMovementGenerator< T >::DoUpdate(), Spell::EffectDistract(), GetAngle(), WorldObject::GetChargeContactPoint(), WorldObject::GetContactPoint(), WorldObject::GetHitSpherePointFor(), Unit::GetMeleeAttackPoint(), FleeingMovementGenerator< T >::GetPoint(), Unit::GetRandomContactPoint(), GetRelativeAngle(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), npc_commandscript::HandleNpcAddFormationCommand(), spell_dk_dancing_rune_weapon::HandleProc(), spell_marrowgar_coldflame::HandleScriptEffect(), HasInArc(), boss_aeonus::IsSummonedBy(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), npc_akama_shade::JustSummoned(), MotionMaster::MoveBackwards(), MotionMaster::MoveForwards(), npc_twilight_volunteer::MovementInform(), boss_illidan_stormrage::MovementInform(), npc_akama_illidan::MovementInform(), boss_lady_vashj::MovementInform(), boss_icehowl::boss_icehowlAI::MovementInform(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), go_ethereum_prison::OnGossipHello(), go_ethereum_stasis::OnGossipHello(), go_hive_pod::OnGossipHello(), SmartScript::ProcessAction(), boss_illidan_stormrage::ScheduleAbilities(), boss_magtheridon::ScheduleCombatEvents(), spell_blood_council_summon_shadow_resonance::SetDest(), Unit::SetFacingToObject(), Unit::SetInFront(), boss_thorim::boss_thorimAI::SpawnArenaNPCs(), boss_thorim::boss_thorimAI::SpellHit(), boss_devourer_of_souls::boss_devourer_of_soulsAI::SpellHitTarget(), CreatureAI::TriggerAlert(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_taldaram_flamesphere::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), npc_nexus_lord::npc_nexus_lordAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), boss_thorim_sif::boss_thorim_sifAI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_pet_gen_plump_turkey::UpdateAI(), and Spell::UpdateChanneledTargetList().
GetAngle() [2/2]
float Position::GetAngle (float x, float y) const
{
    return getAngle(GetPositionX(), GetPositionY(), x, y);
}
References getAngle(), GetPositionX(), and GetPositionY().
GetExactDist() [1/3]
float Position::GetExactDist (float x, float y, float z) const inline
{ return std::sqrt(GetExactDistSq(x, y, z)); }
References GetExactDistSq().
Referenced by PetAI::_needToStop(), Spell::CalculateDelayMomentForDst(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::CanAIAttack(), npc_icc_severed_essence::npc_icc_severed_essenceAI::CanAIAttack(), WorldObject::CanDetectStealthOf(), spell_dk_death_grip::CheckCast(), boss_sindragosa::boss_sindragosaAI::DoAction(), npc_spinestalker::npc_spinestalkerAI::DoAction(), npc_rimefang::npc_rimefangAI::DoAction(), Spell::EffectTeleportUnits(), WorldObject::GetDistance(), WorldObject::GetHitSpherePointFor(), misc_commandscript::HandleGetDistanceCommand(), SpellCastTargets::HasDstChannel(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::InitWaypoint(), GameObject::IsAtInteractDistance(), boss_four_horsemen::boss_four_horsemenAI::IsInRoom(), boss_loatheb::boss_loathebAI::IsInRoom(), boss_maexxna::boss_maexxnaAI::IsInRoom(), boss_noth::boss_nothAI::IsInRoom(), boss_sapphiron::boss_sapphironAI::IsInRoom(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), CreatureGroup::LeaderMoveTo(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), BoneStormMoveTargetSelector::operator()(), LastPhaseIceTombTargetSelector::operator()(), ShadowTrapLKTargetSelector::operator()(), NonTankLKTargetSelector::operator()(), DefileTargetSelector::operator()(), UnboundPlagueTargetSelector::operator()(), boss_faction_championsAI::SelectEnemyCaster(), Spell::SelectImplicitTrajTargets(), boss_gluth::boss_gluthAI::SelectPlayerInRoom(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::SetData(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::setphase(), npc_amanishi_tempest::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_frostsworn_general::boss_frostsworn_generalAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), and CreatureAI::UpdateVictim().
GetExactDist() [2/3]
float Position::GetExactDist (Position const & pos) const inline
{ return GetExactDist(pos.m_positionX, pos.m_positionY, pos.m_positionZ); }
References GetExactDist(), m_positionX, m_positionY, and m_positionZ.
Referenced by GetExactDist().
GetExactDist() [3/3]
float Position::GetExactDist (Position const * pos) const inline
{ return GetExactDist(*pos); }
References GetExactDist().
Referenced by GetExactDist().
GetExactDist2d() [1/3]
float Position::GetExactDist2d (const float x, const float y) const inline
{ return std::sqrt(GetExactDist2dSq(x, y)); }
References GetExactDist2dSq().
Referenced by boss_bug_trio::CheckInRoom(), boss_viscidus::CheckInRoom(), Spell::EffectJump(), Spell::EffectJumpDest(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), CorruptTriggers::Execute(), spell_aq_shadow_storm::FilterTargets(), spell_lady_vashj_summons::FilterTargets(), npc_arthas_teleport_visual::GetAI(), SpellCastTargets::GetDist2d(), WorldObject::GetDistance2d(), WorldObject::GetFirstCollisionPosition(), Unit::GetMeleeAttackPoint(), npc_echo_of_medivh::GetPiece(), BattlegroundRV::GetPillarIdForPos(), misc_commandscript::HandleGetDistanceCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), spell_sindragosa_icy_grip_jump::HandleSpecial(), HasInLine(), boss_algalon_the_observer::boss_algalon_the_observerAI::IsInRoom(), boss_warchief_kargath_bladefist::IsInRoom(), Unit::JumpTo(), boss_archimonde::JustEngagedWith(), boss_professor_putricide::boss_professor_putricideAI::JustEngagedWith(), spell_ioc_launch::Launch(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MoveInLineOfSight(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), boss_kologarn::boss_kologarnAI::MoveInLineOfSight(), npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI::MoveInLineOfSight(), npc_ulduar_snow_mound::MoveInLineOfSight(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), Acore::AllWorldObjectsInExactRange::operator()(), spell_marrowgar_bone_storm::RecalculateDamage(), Spell::SelectImplicitTrajTargets(), spell_blood_council_summon_shadow_resonance::SetDest(), spell_mother_shahraz_fatal_attraction::SetDest(), npc_doomfire_spirit::TryTeleportInDirection(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), and npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI().
GetExactDist2d() [2/3]
float Position::GetExactDist2d (Position const & pos) const inline
{ return GetExactDist2d(pos.m_positionX, pos.m_positionY); }
References GetExactDist2d(), m_positionX, and m_positionY.
Referenced by GetExactDist2d().
GetExactDist2d() [3/3]
float Position::GetExactDist2d (Position const * pos) const inline
{ return GetExactDist2d(*pos); }
References GetExactDist2d().
Referenced by GetExactDist2d().
GetExactDist2dSq() [1/3]
float Position::GetExactDist2dSq (const float x, const float y) const inline
    {
        float dx = x - m_positionX;
        float dy = y - m_positionY;
        return dx*dx + dy*dy;
    }
References m_positionX, and m_positionY.
Referenced by boss_professor_putricide::boss_professor_putricideAI::CanAIAttack(), HostileRefMgr::deleteReferencesOutOfRange(), SlaveRunEvent::Execute(), GetExactDist2d(), GetExactDistSq(), HasInArc(), WorldObject::IsInBetween(), IsInDist2d(), IsValidPlatformTarget(), boss_lord_marrowgar::MoveInLineOfSight(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::MoveInLineOfSight(), npc_putricide_oozeAI::UpdateAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::UpdateAI(), Acore::MessageDistDeliverer::Visit(), and Acore::MessageDistDelivererToHostile::Visit().
GetExactDist2dSq() [2/3]
float Position::GetExactDist2dSq (Position const & pos) const inline
{ return GetExactDist2dSq(pos.m_positionX, pos.m_positionY); }
References GetExactDist2dSq(), m_positionX, and m_positionY.
Referenced by GetExactDist2dSq().
GetExactDist2dSq() [3/3]
float Position::GetExactDist2dSq (Position const * pos) const inline
{ return GetExactDist2dSq(*pos); }
References GetExactDist2dSq().
Referenced by GetExactDist2dSq().
GetExactDistSq() [1/3]
float Position::GetExactDistSq (float x, float y, float z) const inline
    {
        float dz = z - m_positionZ;
        return GetExactDist2dSq(x, y) + dz*dz;
    }
References GetExactDist2dSq(), and m_positionZ.
Referenced by Battleground::_CheckSafePositions(), RandomMovementGenerator< T >::_setRandomLocation(), npc_lk_wicked_spirit::npc_lk_wicked_spiritAI::CanAIAttack(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::CanAIAttack(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), WorldObject::GetClosePoint(), GetExactDist(), WorldObject::GetFirstCollisionPosition(), Unit::GetRandomContactPoint(), spell_vehicle_throw_passenger::HandleScript(), GameObject::IsAtInteractDistance(), IsInDist(), boss_anubarak_trial::boss_anubarak_trialAI::MoveInLineOfSight(), MMapTargetData::PosChanged(), FollowMovementGenerator< T >::PositionOkay(), and Acore::MessageDistDeliverer::Visit().
GetExactDistSq() [2/3]
float Position::GetExactDistSq (Position const & pos) const inline
{ return GetExactDistSq(pos.m_positionX, pos.m_positionY, pos.m_positionZ); }
References GetExactDistSq(), m_positionX, m_positionY, and m_positionZ.
Referenced by GetExactDistSq().
GetExactDistSq() [3/3]
float Position::GetExactDistSq (Position const * pos) const inline
{ return GetExactDistSq(*pos); }
References GetExactDistSq().
Referenced by GetExactDistSq().
GetOrientation()
float Position::GetOrientation () const inline
{ return m_orientation; }
References m_orientation.
Referenced by Battleground::_CheckSafePositions(), Unit::_ExitVehicle(), Player::_SaveCharacter(), Player::_SaveEntryPoint(), Player::ActivateTaxiPathTo(), boss_loatheb::boss_loathebAI::boss_loathebAI(), Unit::BuildMovementPacket(), Object::BuildMovementUpdate(), Transport::CalculatePassengerOffset(), Transport::CalculatePassengerPosition(), BattlegroundSA::CaptureGraveyard(), Unit::CastSpell(), Map::ConvertCorpseToBones(), Corpse::Create(), GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), MotionTransport::CreateNPCPassenger(), boss_ick::boss_ickAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), boss_viscidus::DamageTaken(), boss_taldaram::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), npc_argent_captainAI::DoAction(), BattlegroundIC::DoAction(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), npc_ranshalla::npc_ranshallaAI::DoSummonPriestess(), ScriptedAI::DoTeleportPlayer(), FollowMovementGenerator< T >::DoUpdate(), Spell::EffectDuel(), Spell::EffectLeap(), Spell::EffectPullTowards(), Spell::EffectResurrectPet(), Spell::EffectStuck(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode(), BattlegroundIC::EventPlayerClickedOnFlag(), FixOrientation::Execute(), UtherBatteredHiltEvent::Execute(), IceTombSummonEvent::Execute(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), Creature::FocusTarget(), WorldObject::GetClosePoint(), GameObjectModelOwnerImpl::GetOrientation(), GetPositionOffsetTo(), WorldObject::GetRandomPoint(), GameObject::GetRespawnPosition(), Creature::GetRespawnPosition(), WorldObject::GetStationaryO(), GameObject::GetStationaryO(), WorldObject::GetTransOffsetO(), WorldObject::GetVoidClosePoint(), WorldLocation::GetWorldLocation(), misc_commandscript::HandleAppearCommand(), BattlegroundBE::HandleAreaTrigger(), BattlegroundDS::HandleAreaTrigger(), BattlegroundNA::HandleAreaTrigger(), BattlegroundRL::HandleAreaTrigger(), BattlegroundRV::HandleAreaTrigger(), HandleBothDead(), BattlegroundIC::HandleCapturedNodes(), debug_commandscript::HandleDebugSpawnVehicleCommand(), OutdoorPvPSI::HandleDropFlag(), spell_q12014_steady_as_a_rock::HandleFinish(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), go_commandscript::HandleGoGraveyardCommand(), go_commandscript::HandleGoGridCommand(), go_commandscript::HandleGoXYZCommand(), go_commandscript::HandleGoZoneXYCommand(), misc_commandscript::HandleGPSCommand(), misc_commandscript::HandleGroupSummonCommand(), WorldSession::HandleHearthAndResurrect(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcMoveCommand(), spell_class_call_handler::HandleOnHitRogue(), spell_shadow_bolt_whirl::HandlePeriodic(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), BattlegroundBE::HandlePlayerUnderMap(), BattlegroundNA::HandlePlayerUnderMap(), BattlegroundRL::HandlePlayerUnderMap(), spell_q9847_a_spirit_ally::HandleSendEvent(), ArenaSpectator::HandleSpectatorSpectateCommand(), spell_item_draenic_pale_ale::HandleSummon(), misc_commandscript::HandleSummonCommand(), tele_commandscript::HandleTeleAddCommand(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), misc_commandscript::HandleUnstuckCommand(), debug_commandscript::HandleWPGPSCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), spell_q11065_wrangle_some_aether_rays_aura::if(), npc_partygoer::Initialize(), npc_tharnarian::npc_tharnarianAI::Initialize(), npc_pet_mage_mirror_image::InitializeAI(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), GameObject::IsInRange(), MapMgr::IsValidMapCoord(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle(), IsWithinBox(), Unit::JumpTo(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), npc_webbed_creature::npc_webbed_creatureAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_mandokir::boss_mandokirAI::JustEngagedWith(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), boss_ingvar_the_plunderer::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), Movement::MoveSplineInit::Launch(), CreatureGroup::LeaderMoveTo(), Player::LoadFromDB(), Pet::LoadPetFromDB(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), boss_captain_skarloc::MovementInform(), boss_professor_putricide::boss_professor_putricideAI::MovementInform(), boss_malygos::boss_malygosAI::MovementInform(), npc_spinestalker::npc_spinestalkerAI::MovementInform(), npc_rimefang::npc_rimefangAI::MovementInform(), npc_omen::npc_omenAI::MovementInform(), gunship_npc_AI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), npc_gunship_mage::npc_gunship_mageAI::MovementInform(), npc_escortAI::MovementInform(), MotionMaster::MovePoint(), SmartAI::MovepointReached(), WorldObject::MovePosition(), WorldObject::MovePositionToFirstCollision(), Unit::NearTeleportTo(), npc_ball_of_flame::npc_ball_of_flameAI::npc_ball_of_flameAI(), npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI::npc_ulduar_magnetic_coreAI(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), go_inconspicuous_mine_car::OnGossipHello(), npc_vh_sinclari::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), spell_lurker_below_spout::OnPeriodic(), at_icc_saurfang_portal::OnTrigger(), npc_hover_disk::npc_hover_diskAI::PassengerBoarded(), BattlegroundIC::PostUpdateImpl(), PredictPosition(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), BfGraveyard::RelocateDeadPlayers(), Battleground::RelocateDeadPlayers(), RelocateOffset(), RelocatePolarOffset(), npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons(), Map::RemoveAllPlayers(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), Player::RepopAtGraveyard(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::Reposition(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::Reset(), npc_crusade_recruit::npc_crusade_recruitAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), Player::ResurectUsingRequestData(), Player::SavePositionInDB(), Player::SaveRecallPosition(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), boss_nightbane::ScheduleFly(), Map::ScriptsProcess(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitTrajTargets(), npc_midsummer_torch_target::SelectPosition(), PassengerController::SelectSpawnPoint(), WorldSession::SendSpiritResurrect(), Unit::SendTeleportPacket(), BattlegroundMgr::SendToBattleground(), Player::SetClientControl(), instance_stratholme::instance_stratholme_InstanceMapScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), spell_spawn_blood_pool::SetDest(), Player::SetEntryPoint(), Unit::SetInCombatState(), GameObject::SetLocalRotation(), npc_escortAI::SetNextWaypoint(), Creature::SetPosition(), GameObject::SetPosition(), boss_kelthuzad::boss_kelthuzadAI::SpawnHelpers(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), boss_majordomo::boss_majordomoAI::SpellHit(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), npc_nerubian_burrower::npc_nerubian_burrowerAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_cyanigosa::boss_cyanigosaAI::SpellHitTarget(), WaypointMovementGenerator< Creature >::StartMove(), Movement::MoveSplineInit::Stop(), Unit::StopMovingOnCurrentPos(), Map::SummonCreature(), WorldObject::SummonCreature(), Map::SummonGameObject(), Player::SummonIfPossible(), go_wind_stone::go_wind_stoneAI::SummonNPC(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), Player::TeleportTo(), Player::TeleportToEntryPoint(), BattlegroundRV::TeleportUnitToNewZ(), npc_doomfire_spirit::TryTeleportInDirection(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), RotateMovementGenerator::Update(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), npc_dark_iron_attack_generator::UpdateAI(), npc_winterfin_playmate::UpdateAI(), npc_snowfall_glade_playmate::UpdateAI(), npc_the_biggest_tree::UpdateAI(), npc_high_oracle_soo_roo::UpdateAI(), npc_elder_kekek::UpdateAI(), npc_the_etymidian::UpdateAI(), npc_alexstraza_the_lifebinder::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_frost_sphere::npc_frost_sphereAI::UpdateAI(), boss_jormungarAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_coldflame::npc_coldflameAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_minigob_manabonk::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), CinematicMgr::UpdateCinematicLocation(), Player::UpdatePosition(), Unit::UpdatePosition(), and GameObject::Use().
GetPosition() [1/4]
Position Position::GetPosition () const inline
{ return *this; }
Referenced by WorldObject::GetFirstCollisionPosition(), WorldObject::GetNearPosition(), WorldObject::GetRandomNearPosition(), WorldObject::IsWithinLOS(), WorldObject::IsWithinLOSInMap(), and Player::TeleportTo().
GetPosition() [2/4]
void Position::GetPosition (float & x, float & y) const inline
    {
        x = m_positionX;
        y = m_positionY;
    }
References m_positionX, and m_positionY.
Referenced by Battleground::_CheckSafePositions(), Unit::_ExitVehicle(), MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::AttackStart(), spell_igb_incinerating_blast::CalculateDamage(), PathGenerator::CalculatePath(), Spell::CheckCast(), spell_rotface_unstable_ooze_explosion::CheckTarget(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::ChromieWhisper(), boss_isalien::DamageTaken(), MotionTransport::DelayedTeleportTransport(), ChaseMovementGenerator< T >::DoUpdate(), FollowMovementGenerator< T >::DoUpdate(), Spell::EffectChargeDest(), Spell::EffectJumpDest(), Spell::EffectKnockBack(), Spell::EffectLeap(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPlayer(), Spell::EffectSummonRaFFriend(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), npc_giant_claw_tentacle::Emerge(), FollowerAI::EnterEvadeMode(), DelayedMovementEvent::Execute(), IceTombSummonEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), BattlegroundAV::GetClosestGraveyard(), BattlegroundSA::GetClosestGraveyard(), Creature::GetHomePosition(), WorldObject::GetRandomPoint(), Creature::GetTransportHomePosition(), spell_apothecary_lingering_fumes::HandleAfterCast(), WorldSession::HandleBattlemasterHelloOpcode(), spell_rotface_unstable_ooze_explosion_init::HandleCast(), spell_midsummer_summon_ahune_lieutenant::HandleDummy(), spell_herald_volzaj_insanity::HandleDummyEffect(), gobject_commandscript::HandleGameObjectMoveCommand(), WorldSession::HandleGossipHelloOpcode(), mmaps_commandscript::HandleMmapLocCommand(), mmaps_commandscript::HandleMmapPathCommand(), WorldSession::HandleQuestgiverHelloOpcode(), spell_vehicle_throw_passenger::HandleScript(), spell_ice_bombardment_dest_picker::HandleScriptEffect(), WorldSession::HandleSetRaidDifficultyOpcode(), spell_halion_damage_aoe_summon::HandleSummon(), spell_putricide_mutated_transformation::HandleSummon(), BfWGGameObjectBuilding::Init(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::IsSummonedBy(), npc_oculus_drake::npc_oculus_drakeAI::IsSummonedBy(), npc_wintergarde_gryphon::IsSummonedBy(), npc_korkron_or_wildhammer::IsSummonedBy(), WorldObject::IsWithinLOSInMap(), boss_jarien::JustDied(), boss_sothos::JustDied(), boss_akilzon::JustEngagedWith(), boss_sacrolash::JustEngagedWith(), boss_hexlord_malacrass::JustEngagedWith(), boss_lady_vashj::JustSummoned(), FlightPathMovementGenerator::LoadPath(), MotionMaster::MoveBackwards(), MotionMaster::MoveForwards(), boss_nalorakk::MoveInLineOfSight(), MotionMaster::MoveKnockbackFrom(), MotionMaster::MoveLand(), npc_akama_illidan::MovementInform(), npc_akama_shade::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), boss_ghazan::MovementInform(), SmartAI::MovepointReached(), MotionMaster::MoveTakeoff(), npc_zulaman_hostage::OnGossipSelect(), at_icc_saurfang_portal::OnTrigger(), MysticBuffetTargetFilter::operator()(), operator<<(), npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded(), boss_nefarian::PathEndReached(), PredictPosition(), SmartScript::ProcessAction(), readCamera(), spell_igb_teleport_to_enemy_ship::RelocateTransportOffset(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::Reset(), npc_kinetic_bomb::npc_kinetic_bombAI::Reset(), boss_kologarn_pit_kill_bunny::Reset(), boss_nightbane::ScheduleFly(), Spell::SelectImplicitCasterDestTargets(), WorldSession::SendListInventory(), gunship_npc_AI::SetData(), Player::SetHomebind(), NPCStaveQuestAI::SetHomePosition(), FleeingMovementGenerator< T >::SetTargetLocation(), BattlefieldWG::SetupBattlefield(), boss_malchezaar::SpawnInfernal(), boss_alar::SpawnPhoenixes(), boss_veklor::SpellHit(), npc_forest_frog::SpellHit(), npc_enslaved_netherwing_drake::SpellHit(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), boss_lethon::boss_lethonAI::SpellHitTarget(), dragonmaw_race_npc::StartRaceAttacks(), boss_akilzon::SummonEagles(), boss_amanitar::SummonedCreatureDies(), npc_coren_direbrew::SummonSister(), BossAI::TeleportCheaters(), spell_midsummer_fling_torch::ThrowNextTorch(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), npc_minigob_manabonk::UpdateAI(), npc_wintergarde_gryphon::UpdateAI(), StaticTransport::UpdatePassengerPositions(), and MotionTransport::UpdatePassengerPositions().
GetPosition() [3/4]
void Position::GetPosition (float & x, float & y, float & z) const inline
    {
        x = m_positionX;
        y = m_positionY;
        z = m_positionZ;
    }
References m_positionX, m_positionY, and m_positionZ.
GetPosition() [4/4]
void Position::GetPosition (float & x, float & y, float & z, float & o) const inline
    {
        x = m_positionX;
        y = m_positionY;
        z = m_positionZ;
        o = m_orientation;
    }
References m_orientation, m_positionX, m_positionY, and m_positionZ.
GetPositionOffsetTo()
void Position::GetPositionOffsetTo (const Position & endPos, Position & retOffset) const
{
    float dx = endPos.GetPositionX() - GetPositionX();
    float dy = endPos.GetPositionY() - GetPositionY();
    retOffset.m_positionX = dx * cos(GetOrientation()) + dy * std::sin(GetOrientation());
    retOffset.m_positionY = dy * cos(GetOrientation()) - dx * std::sin(GetOrientation());
    retOffset.m_positionZ = endPos.GetPositionZ() - GetPositionZ();
    retOffset.m_orientation = endPos.GetOrientation() - GetOrientation();
}
References GetOrientation(), GetPositionX(), GetPositionY(), GetPositionZ(), m_orientation, m_positionX, m_positionY, and m_positionZ.
Referenced by SpellDestination::Relocate().
GetPositionWithOffset()
Position Position::GetPositionWithOffset (Position const & offset) const
GetPositionX()
float Position::GetPositionX () const inline
{ return m_positionX; }
References m_positionX.
Referenced by Battleground::_CheckSafePositions(), Unit::_ExitVehicle(), WorldObject::_IsWithinDist(), GameObject::_IsWithinDist(), Player::_SaveCharacter(), Player::_SaveEntryPoint(), RandomMovementGenerator< T >::_setRandomLocation(), Spell::AddGOTarget(), Map::AddPlayerToMap(), Map::AddToMap(), WorldObject::AddToWorld(), Spell::AddUnitTarget(), TotemAI::AttackStart(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::AttackStart(), CinematicMgr::BeginCinematic(), boss_loatheb::boss_loathebAI::boss_loathebAI(), Unit::BuildMovementPacket(), WorldSession::BuildPartyMemberStatsChangedPacket(), Transport::CalculatePassengerOffset(), Transport::CalculatePassengerPosition(), boss_lord_marrowgar::CanAIAttack(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::CanAIAttack(), boss_selin_fireheart::CanAIAttack(), Map::CanReachPositionAndGetValidCoords(), GameObject::CastSpell(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), boss_shade_of_aran::CheckAranInRoom(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Spell::CheckEffectTarget(), boss_general_zarithrian::boss_general_zarithrianAI::CheckEvadeIfOutOfCombatArea(), boss_freya::boss_freyaAI::CheckEvadeIfOutOfCombatArea(), boss_supremus::CheckEvadeIfOutOfCombatArea(), boss_gothik::boss_gothikAI::CheckGroupSplitted(), boss_moroes::CheckGuestsInRoom(), BattlegroundRV::CheckPositionForUnit(), Spell::CheckSpellFocus(), boss_alar::ConstructWaypointsAndMove(), Player::ContinueTaxiFlight(), Map::ConvertCorpseToBones(), Creature::Create(), Corpse::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), npc_frost_sphere::npc_frost_sphereAI::DamageTaken(), boss_ick::boss_ickAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), boss_viscidus::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken(), BattlegroundSA::DefendersPortalTeleport(), boss_alar::DeterminePhoenixPosition(), boss_nightbane::DoAction(), npc_hyjal_gargoyle::DoAction(), npc_hyjal_frost_wyrm::DoAction(), npc_thrall_warchief::npc_thrall_warchiefAI::DoAction(), boss_taldaram::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), boss_professor_putricide::boss_professor_putricideAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_power_spark::npc_power_sparkAI::DoAction(), npc_hover_disk::npc_hover_diskAI::DoAction(), BattlegroundIC::DoAction(), boss_maexxna::boss_maexxnaAI::DoCastWebWrap(), Creature::DoFleeToGetAssistance(), tele_commandscript::DoNameTeleport(), FlightPathMovementGenerator::DoReset(), ScriptedAI::DoSpawnCreature(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), go_commandscript::DoTeleport(), ScriptedAI::DoTeleportPlayer(), Spell::EffectBind(), Spell::EffectChargeDest(), Spell::EffectDuel(), Spell::EffectLeap(), Spell::EffectPullTowards(), Spell::EffectResurrect(), Spell::EffectResurrectNew(), Spell::EffectStuck(), Spell::EffectTeleUnitsFaceCaster(), Spell::EffectTransmitted(), npc_giant_claw_tentacle::Emerge(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::EnsureGridLoaded(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::EnsureGridLoaded(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode(), BattlegroundIC::EventPlayerClickedOnFlag(), CastArmageddon::Execute(), UtherBatteredHiltEvent::Execute(), IceTombSummonEvent::Execute(), Unit::ExecuteDelayedUnitRelocationEvent(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_kaelthas::ExecuteMiddleEvent(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), GetAngle(), MapMgr::GetAreaId(), WorldObject::GetChargeContactPoint(), WorldObject::GetClosePoint(), BattlegroundAB::GetClosestGraveyard(), BattlegroundEY::GetClosestGraveyard(), BattlegroundIC::GetClosestGraveyard(), Graveyard::GetClosestGraveyard(), WorldObject::GetContactPoint(), WorldObject::GetCreaturesWithEntryInRange(), WorldObject::GetDistanceOrder(), WorldObject::GetFirstCollisionPosition(), WorldObject::GetFloorZ(), WorldObject::GetHitSpherePointFor(), WorldObject::GetNearPoint(), WorldObject::GetNearPoint2D(), boss_volkhan::boss_volkhanAI::GetNextPos(), GameObjectModelOwnerImpl::GetPosition(), GetPositionOffsetTo(), Unit::GetRandomContactPoint(), GameObject::GetRespawnPosition(), Creature::GetRespawnPosition(), GetSinCos(), WorldObject::GetStationaryX(), GameObject::GetStationaryX(), WorldObject::GetTransOffsetX(), MapMgr::GetZoneId(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), WorldSession::HandleBattlegroundPlayerPositionsOpcode(), HandleBothDead(), BattlegroundIC::HandleCapturedNodes(), WorldSession::HandleCharFactionOrRaceChangeCallback(), misc_commandscript::HandleComeToMeCommand(), WorldSession::HandleCorpseQueryOpcode(), debug_commandscript::HandleDebugSendOpcodeCommand(), OutdoorPvPSI::HandleDropFlag(), spell_moroes_vanish::HandleDummy(), spell_anti_air_rocket_bomber::HandleDummy(), spell_warhead_detonate::HandleDummy(), spell_q12589_shoot_rjr::HandleDummy(), spell_dk_death_grip::HandleDummy(), spell_midsummer_torch_quest::HandleEffectApply(), spell_hodir_flash_freeze_aura::HandleEffectPeriodic(), spell_q12014_steady_as_a_rock::HandleFinish(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), misc_commandscript::HandleGPSCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), mmaps_commandscript::HandleMmapLocCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), spell_class_call_handler::HandleOnHitRogue(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), spell_entropius_black_hole_effect::HandlePull(), spell_boss_magus_telestra_gravity_well::HandlePull(), WorldSession::HandleRequestPartyMemberStatsOpcode(), misc_commandscript::HandleRespawnAllCommand(), spell_dreamwalker_summon_portal::HandleScript(), spell_marrowgar_coldflame_bonestorm::HandleScriptEffect(), spell_winter_veil_racer_slam_hit::HandleScriptEffect(), spell_marrowgar_coldflame::HandleScriptEffect(), spell_ice_bombardment_dest_picker::HandleScriptEffect(), spell_q10612_10613_the_fel_and_the_furious::HandleScriptEffect(), spell_sindragosa_icy_grip_jump::HandleSpecial(), ArenaSpectator::HandleSpectatorSpectateCommand(), misc_commandscript::HandleSummonCommand(), tele_commandscript::HandleTeleAddCommand(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), debug_commandscript::HandleWPGPSCommand(), wp_commandscript::HandleWpModifyCommand(), HasInLine(), spell_q11065_wrangle_some_aether_rays_aura::if(), boss_captain_skarloc::InitializeAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::InitializeAI(), boss_sapphiron::boss_sapphironAI::InitializeAI(), npc_preparations_for_war_vehicle::InitializeAI(), go_magtheridons_head::InitializeAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::InitWaypoint(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), GameObject::IsAtInteractDistance(), boss_netherspite::IsBetween(), WorldObject::IsInBetween(), GameObject::IsInRange(), WorldObject::IsInRange(), WorldObject::IsInRange2d(), WorldObject::IsInRange3d(), boss_gothik::boss_gothikAI::IsInRoom(), ScriptedAI::IsInRoom(), boss_heigan::boss_heiganAI::IsInRoom(), WorldObject::IsInWintergrasp(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::IsSummonedBy(), boss_sartharion::boss_sartharionAI::IsTargetInBounds(), MapMgr::IsValidMapCoord(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle(), RectangleBoundary::IsWithinBoundaryArea(), CircleBoundary::IsWithinBoundaryArea(), EllipseBoundary::IsWithinBoundaryArea(), TriangleBoundary::IsWithinBoundaryArea(), ParallelogramBoundary::IsWithinBoundaryArea(), IsWithinBox(), Unit::IsWithinCombatRange(), WorldObject::IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), Unit::IsWithinRange(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::JustDied(), npc_enraged_spirit::npc_enraged_spiritAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_mandokir::boss_mandokirAI::JustEngagedWith(), boss_vem::JustEngagedWith(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::JustSummoned(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), boss_ingvar_the_plunderer::JustSummoned(), boss_kiljaeden::JustSummoned(), npc_kalecgos_kj::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), spell_svalna_revive_champion::Land(), Movement::MoveSplineInit::Launch(), spell_ioc_launch::Launch(), CreatureGroup::LeaderMoveTo(), Corpse::LoadCorpseFromDB(), Player::LoadFromDB(), Pet::LoadPetFromDB(), LogCommandUsage(), spell_gen_basic_campfire::ModDest(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), MotionMaster::MoveCircleTarget(), MotionMaster::MoveFall(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), npc_hol_monument::npc_hol_monumentAI::MoveInLineOfSight(), npc_brann_radio::npc_brann_radioAI::MoveInLineOfSight(), npc_ulduar_snow_mound::MoveInLineOfSight(), MotionMaster::MoveKnockbackFrom(), boss_malygos::boss_malygosAI::MovementInform(), npc_enslaved_proto_drake::MovementInform(), boss_vazruden_the_herald::MovementInform(), npc_omen::npc_omenAI::MovementInform(), npc_escortAI::MovementInform(), npc_hor_leader_second::npc_hor_leader_secondAI::MoveToNextStopPoint(), Unit::NearTeleportTo(), npc_ball_of_flame::npc_ball_of_flameAI::npc_ball_of_flameAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::npc_icc_vengeful_fleshreaperAI(), npc_medivh_bm::npc_medivh_bm(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::npc_ulduar_flames_initialAI(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnCreatureCreate(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectRemove(), go_ethereum_prison::OnGossipHello(), go_ethereum_stasis::OnGossipHello(), go_hive_pod::OnGossipHello(), go_veil_skith_cage::OnGossipHello(), npc_vekjik::OnGossipSelect(), npc_vh_sinclari::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnPlayerEnter(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter(), BattlefieldWG::OnPlayerEnterZone(), go_magtheridons_head::OnStateChanged(), at_sindragosa_lair::OnTrigger(), at_icc_saurfang_portal::OnTrigger(), AreaTrigger_at_scent_larkorwi::OnTrigger(), at_malfurion_stormrage::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), Acore::AnyPlayerExactPositionInGameObjectRangeCheck::operator()(), BoneStormMoveTargetSelector::operator()(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), IgbArtilleryCheck::operator()(), MysticBuffetTargetFilter::operator()(), npc_vehicle_d16_propelled_delivery::npc_vehicle_d16_propelled_deliveryAI::PassengerBoarded(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), npc_vics_flying_machine::npc_vics_flying_machineAI::PassengerBoarded(), npc_hover_disk::npc_hover_diskAI::PassengerBoarded(), spell_halion_twilight_phasing::Phase(), Map::PlayerRelocation(), BattlegroundIC::PostUpdateImpl(), npc_dark_iron_attack_generator::PrepareEvent(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), readCamera(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), RelocateOffset(), RelocatePolarOffset(), npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons(), Player::RepopAtGraveyard(), boss_malchezaar::Reset(), npc_kiljaeden_controller::Reset(), npc_brewfest_super_brew_trigger::Reset(), boss_archimonde::Reset(), boss_ossirian::Reset(), boss_anubarak_trial::boss_anubarak_trialAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), npc_crystal_spike::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), boss_freya_nature_bomb::boss_freya_nature_bombAI::Reset(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::Reset(), npc_firework::npc_fireworkAI::Reset(), Player::SavePositionInDB(), Player::SaveRecallPosition(), CharmInfo::SaveStayPosition(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), boss_felmyst::ScheduleFlightAbilities(), boss_felmyst::ScheduleFlightSequence(), boss_nightbane::ScheduleFly(), Spell::SearchTargets(), Spell::SelectImplicitCasterDestTargets(), npc_midsummer_torch_target::SelectPosition(), PassengerController::SelectSpawnPoint(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), WorldSession::SendLearnNewTaxiNode(), Unit::SendMonsterMove(), WorldSession::SendTaxiMenu(), Player::SendTaxiNodeStatusMultiple(), WorldSession::SendTaxiStatus(), Unit::SendTeleportPacket(), BattlegroundMgr::SendToBattleground(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), instance_stratholme::instance_stratholme_InstanceMapScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), npc_argent_soldier::npc_argent_soldierAI::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::SetData(), spell_blood_council_summon_shadow_resonance::SetDest(), spell_mother_shahraz_fatal_attraction::SetDest(), spell_dk_summon_gargoyle::SetDest(), spell_spawn_blood_pool::SetDest(), Player::SetEntryPoint(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Unit::SetHover(), Unit::SetInCombatState(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::setphase(), Creature::SetPosition(), GameObject::SetPosition(), FleeingMovementGenerator< T >::SetTargetLocation(), PathGenerator::ShortenPathUntilDist(), boss_thorim::boss_thorimAI::SpawnArenaNPCs(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnClouds(), boss_skadi_grauf::boss_skadi_graufAI::SpawnHelpers(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), boss_ossirian::SpawnNextCrystal(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SpawnPyramidWave(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnTentacle(), boss_freya::boss_freyaAI::SpawnWave(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), boss_majordomo::boss_majordomoAI::SpellHit(), boss_headless_horseman_pumpkin::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), npc_nerubian_burrower::npc_nerubian_burrowerAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_freya::boss_freyaAI::SpellHitTarget(), boss_cyanigosa::boss_cyanigosaAI::SpellHitTarget(), npc_chesspiece::SpellHitTarget(), boss_grobbulus::boss_grobbulusAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_ionar::boss_ionarAI::Split(), boss_janalai::StartBombing(), boss_felmyst::StartIntro(), Movement::MoveSplineInit::Stop(), Unit::StopMovingOnCurrentPos(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::StorePrisoner(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), boss_anzu::SummonBroods(), Map::SummonCreature(), npc_ravenclaw_apparition::npc_ravenclaw_apparitionAI::SummonCrowd(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SummonDeathOrbs(), boss_sjonnir::boss_sjonnirAI::SummonDwarfes(), npc_kiljaeden_controller::SummonedCreatureDies(), Map::SummonGameObject(), Spell::SummonGuardian(), boss_yoggsaron::boss_yoggsaronAI::SummonImmortalGuardian(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::SummonInfernal(), go_wind_stone::go_wind_stoneAI::SummonNPC(), Player::SummonPet(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), Map::SwitchGridContainers(), Player::TeleportTo(), BattlegroundRV::TeleportUnitToNewZ(), spell_midsummer_fling_torch::ThrowNextTorch(), CreatureAI::TriggerAlert(), npc_doomfire_spirit::TryTeleportInDirection(), MotionTransport::Update(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), Creature::Update(), Player::Update(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), npc_dark_iron_attack_generator::UpdateAI(), npc_dark_iron_attack_mole_machine::UpdateAI(), npc_winterfin_playmate::UpdateAI(), npc_snowfall_glade_playmate::UpdateAI(), npc_the_biggest_tree::UpdateAI(), npc_high_oracle_soo_roo::UpdateAI(), npc_elder_kekek::UpdateAI(), npc_the_etymidian::UpdateAI(), npc_alexstraza_the_lifebinder::UpdateAI(), npc_pilgrims_bounty_chair::UpdateAI(), npc_medivh_bm::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), boss_elder_nadox::UpdateAI(), npc_taldaram_flamesphere::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), npc_frost_sphere::npc_frost_sphereAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), npc_coldflame::npc_coldflameAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), boss_ormorok::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_ingvar_the_plunderer::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_minigob_manabonk::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), Player::UpdateAreaDependentAuras(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), PathGenerator::UpdateFilter(), Unit::UpdateHeight(), Player::UpdatePosition(), Unit::UpdatePosition(), WorldObject::UpdatePositionData(), GameObject::Use(), Cell::Visit(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), Map::VisitNearbyCellsOf(), Map::VisitNearbyCellsOfPlayer(), Cell::VisitWorldObjects(), npc_barnes::npc_barnesAI::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), and npc_emily::npc_emilyAI::WaypointReached().
GetPositionY()
float Position::GetPositionY () const inline
{ return m_positionY; }
References m_positionY.
Referenced by Battleground::_CheckSafePositions(), Unit::_ExitVehicle(), WorldObject::_IsWithinDist(), GameObject::_IsWithinDist(), Player::_SaveCharacter(), Player::_SaveEntryPoint(), RandomMovementGenerator< T >::_setRandomLocation(), Spell::AddGOTarget(), Map::AddPlayerToMap(), Map::AddToMap(), WorldObject::AddToWorld(), Spell::AddUnitTarget(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::AddWaypoints(), TotemAI::AttackStart(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::AttackStart(), CinematicMgr::BeginCinematic(), boss_loatheb::boss_loathebAI::boss_loathebAI(), Unit::BuildMovementPacket(), WorldSession::BuildPartyMemberStatsChangedPacket(), Transport::CalculatePassengerOffset(), Transport::CalculatePassengerPosition(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::CanAIAttack(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::CanAIAttack(), npc_igb_ship_crew::npc_igb_ship_crewAI::CanAIAttack(), npc_gunship_boarding_addAI::CanAIAttack(), boss_professor_putricide::boss_professor_putricideAI::CanAIAttack(), npc_crok_scourgebane::npc_crok_scourgebaneAI::CanAIAttack(), npc_argent_captainAI::CanAIAttack(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::CanAIAttack(), Map::CanReachPositionAndGetValidCoords(), GameObject::CastSpell(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), boss_shade_of_aran::CheckAranInRoom(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Spell::CheckEffectTarget(), boss_supremus::CheckEvadeIfOutOfCombatArea(), boss_gothik::boss_gothikAI::CheckGroupSplitted(), boss_moroes::CheckGuestsInRoom(), BattlegroundRV::CheckPositionForUnit(), Spell::CheckSpellFocus(), boss_alar::ConstructWaypointsAndMove(), Player::ContinueTaxiFlight(), Map::ConvertCorpseToBones(), Creature::Create(), Corpse::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), npc_frost_sphere::npc_frost_sphereAI::DamageTaken(), boss_ick::boss_ickAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), boss_viscidus::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken(), boss_alar::DeterminePhoenixPosition(), boss_nightbane::DoAction(), npc_thrall_warchief::npc_thrall_warchiefAI::DoAction(), boss_taldaram::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), boss_professor_putricide::boss_professor_putricideAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_power_spark::npc_power_sparkAI::DoAction(), npc_hover_disk::npc_hover_diskAI::DoAction(), npc_creature_generator_akama::DoAction(), BattlegroundIC::DoAction(), boss_maexxna::boss_maexxnaAI::DoCastWebWrap(), Creature::DoFleeToGetAssistance(), tele_commandscript::DoNameTeleport(), FlightPathMovementGenerator::DoReset(), ScriptedAI::DoSpawnCreature(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), go_commandscript::DoTeleport(), ScriptedAI::DoTeleportPlayer(), Spell::EffectBind(), Spell::EffectChargeDest(), Spell::EffectDuel(), Spell::EffectLeap(), Spell::EffectPullTowards(), Spell::EffectResurrect(), Spell::EffectResurrectNew(), Spell::EffectStuck(), Spell::EffectTeleUnitsFaceCaster(), Spell::EffectTransmitted(), npc_giant_claw_tentacle::Emerge(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::EnsureGridLoaded(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::EnsureGridLoaded(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode(), BattlegroundIC::EventPlayerClickedOnFlag(), CastArmageddon::Execute(), UtherBatteredHiltEvent::Execute(), IceTombSummonEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_kaelthas::ExecuteMiddleEvent(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), GetAngle(), MapMgr::GetAreaId(), WorldObject::GetChargeContactPoint(), WorldObject::GetClosePoint(), BattlegroundAB::GetClosestGraveyard(), BattlegroundEY::GetClosestGraveyard(), BattlegroundIC::GetClosestGraveyard(), Graveyard::GetClosestGraveyard(), WorldObject::GetContactPoint(), WorldObject::GetCreaturesWithEntryInRange(), WorldObject::GetDistanceOrder(), WorldObject::GetFirstCollisionPosition(), WorldObject::GetFloorZ(), WorldObject::GetHitSpherePointFor(), WorldObject::GetNearPoint(), WorldObject::GetNearPoint2D(), boss_volkhan::boss_volkhanAI::GetNextPos(), GameObjectModelOwnerImpl::GetPosition(), GetPositionOffsetTo(), Unit::GetRandomContactPoint(), GameObject::GetRespawnPosition(), Creature::GetRespawnPosition(), GetSinCos(), WorldObject::GetStationaryY(), GameObject::GetStationaryY(), WorldObject::GetTransOffsetY(), MapMgr::GetZoneId(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), WorldSession::HandleBattlegroundPlayerPositionsOpcode(), HandleBothDead(), BattlegroundIC::HandleCapturedNodes(), WorldSession::HandleCharFactionOrRaceChangeCallback(), misc_commandscript::HandleComeToMeCommand(), WorldSession::HandleCorpseQueryOpcode(), debug_commandscript::HandleDebugSendOpcodeCommand(), OutdoorPvPSI::HandleDropFlag(), spell_moroes_vanish::HandleDummy(), spell_anti_air_rocket_bomber::HandleDummy(), spell_warhead_detonate::HandleDummy(), spell_q12589_shoot_rjr::HandleDummy(), spell_dk_death_grip::HandleDummy(), spell_midsummer_torch_quest::HandleEffectApply(), spell_hodir_flash_freeze_aura::HandleEffectPeriodic(), spell_q12014_steady_as_a_rock::HandleFinish(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), misc_commandscript::HandleGPSCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), mmaps_commandscript::HandleMmapLocCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), spell_class_call_handler::HandleOnHitRogue(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), spell_entropius_black_hole_effect::HandlePull(), spell_boss_magus_telestra_gravity_well::HandlePull(), WorldSession::HandleRequestPartyMemberStatsOpcode(), misc_commandscript::HandleRespawnAllCommand(), spell_dreamwalker_summon_portal::HandleScript(), spell_marrowgar_coldflame_bonestorm::HandleScriptEffect(), spell_winter_veil_racer_slam_hit::HandleScriptEffect(), spell_marrowgar_coldflame::HandleScriptEffect(), spell_ice_bombardment_dest_picker::HandleScriptEffect(), spell_q10612_10613_the_fel_and_the_furious::HandleScriptEffect(), spell_sindragosa_icy_grip_jump::HandleSpecial(), ArenaSpectator::HandleSpectatorSpectateCommand(), misc_commandscript::HandleSummonCommand(), tele_commandscript::HandleTeleAddCommand(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), debug_commandscript::HandleWPGPSCommand(), wp_commandscript::HandleWpModifyCommand(), HasInLine(), spell_q11065_wrangle_some_aether_rays_aura::if(), boss_captain_skarloc::InitializeAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::InitializeAI(), boss_sapphiron::boss_sapphironAI::InitializeAI(), npc_preparations_for_war_vehicle::InitializeAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::InitWaypoint(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), GameObject::IsAtInteractDistance(), boss_netherspite::IsBetween(), Unit::isInAccessiblePlaceFor(), WorldObject::IsInBetween(), GameObject::IsInRange(), WorldObject::IsInRange(), WorldObject::IsInRange2d(), WorldObject::IsInRange3d(), boss_gothik::boss_gothikAI::IsInRoom(), ScriptedAI::IsInRoom(), boss_heigan::boss_heiganAI::IsInRoom(), WorldObject::IsInWintergrasp(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::IsSummonedBy(), boss_sartharion::boss_sartharionAI::IsTargetInBounds(), MapMgr::IsValidMapCoord(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle(), RectangleBoundary::IsWithinBoundaryArea(), CircleBoundary::IsWithinBoundaryArea(), EllipseBoundary::IsWithinBoundaryArea(), TriangleBoundary::IsWithinBoundaryArea(), ParallelogramBoundary::IsWithinBoundaryArea(), IsWithinBox(), Unit::IsWithinCombatRange(), WorldObject::IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), Unit::IsWithinRange(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::JustDied(), npc_enraged_spirit::npc_enraged_spiritAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_mandokir::boss_mandokirAI::JustEngagedWith(), boss_vem::JustEngagedWith(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::JustSummoned(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), boss_ingvar_the_plunderer::JustSummoned(), boss_kiljaeden::JustSummoned(), npc_kalecgos_kj::JustSummoned(), boss_janalai::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), spell_svalna_revive_champion::Land(), Movement::MoveSplineInit::Launch(), spell_ioc_launch::Launch(), CreatureGroup::LeaderMoveTo(), Corpse::LoadCorpseFromDB(), Player::LoadFromDB(), Pet::LoadPetFromDB(), LogCommandUsage(), spell_gen_basic_campfire::ModDest(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), MotionMaster::MoveCircleTarget(), MotionMaster::MoveFall(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), npc_hol_monument::npc_hol_monumentAI::MoveInLineOfSight(), npc_ulduar_snow_mound::MoveInLineOfSight(), MotionMaster::MoveKnockbackFrom(), boss_malygos::boss_malygosAI::MovementInform(), npc_enslaved_proto_drake::MovementInform(), boss_vazruden_the_herald::MovementInform(), npc_omen::npc_omenAI::MovementInform(), npc_escortAI::MovementInform(), npc_hor_leader_second::npc_hor_leader_secondAI::MoveToNextStopPoint(), Unit::NearTeleportTo(), npc_ball_of_flame::npc_ball_of_flameAI::npc_ball_of_flameAI(), npc_medivh_bm::npc_medivh_bm(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::npc_ulduar_flames_initialAI(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectRemove(), go_ethereum_prison::OnGossipHello(), go_ethereum_stasis::OnGossipHello(), go_hive_pod::OnGossipHello(), go_veil_skith_cage::OnGossipHello(), npc_vekjik::OnGossipSelect(), npc_vh_sinclari::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnPlayerEnter(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter(), BattlefieldWG::OnPlayerEnterZone(), at_sindragosa_lair::OnTrigger(), at_icc_saurfang_portal::OnTrigger(), AreaTrigger_at_scent_larkorwi::OnTrigger(), at_malfurion_stormrage::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), Acore::AnyPlayerExactPositionInGameObjectRangeCheck::operator()(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), IgbArtilleryCheck::operator()(), MysticBuffetTargetFilter::operator()(), npc_vehicle_d16_propelled_delivery::npc_vehicle_d16_propelled_deliveryAI::PassengerBoarded(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), npc_vics_flying_machine::npc_vics_flying_machineAI::PassengerBoarded(), npc_hover_disk::npc_hover_diskAI::PassengerBoarded(), spell_halion_twilight_phasing::Phase(), Map::PlayerRelocation(), BattlegroundIC::PostUpdateImpl(), npc_dark_iron_attack_generator::PrepareEvent(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), readCamera(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), RelocateOffset(), RelocatePolarOffset(), npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons(), Player::RepopAtGraveyard(), boss_malchezaar::Reset(), boss_kalec::Reset(), npc_kiljaeden_controller::Reset(), npc_janalai_hatcher::Reset(), npc_zulian_prowler::npc_zulian_prowlerAI::Reset(), npc_brewfest_super_brew_trigger::Reset(), boss_archimonde::Reset(), boss_ossirian::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), npc_crystal_spike::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), boss_freya_nature_bomb::boss_freya_nature_bombAI::Reset(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::Reset(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::Reset(), npc_firework::npc_fireworkAI::Reset(), Player::SavePositionInDB(), Player::SaveRecallPosition(), CharmInfo::SaveStayPosition(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), boss_felmyst::ScheduleFlightAbilities(), boss_felmyst::ScheduleFlightSequence(), boss_nightbane::ScheduleFly(), Spell::SearchTargets(), Spell::SelectImplicitCasterDestTargets(), boss_skadi_grauf::boss_skadi_graufAI::SelectNextPos(), npc_midsummer_torch_target::SelectPosition(), npc_gothik_trigger::npc_gothik_triggerAI::SelectRandomSkullPile(), PassengerController::SelectSpawnPoint(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), WorldSession::SendLearnNewTaxiNode(), Unit::SendMonsterMove(), WorldSession::SendTaxiMenu(), Player::SendTaxiNodeStatusMultiple(), WorldSession::SendTaxiStatus(), Unit::SendTeleportPacket(), BattlegroundMgr::SendToBattleground(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), instance_stratholme::instance_stratholme_InstanceMapScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::SetData(), spell_blood_council_summon_shadow_resonance::SetDest(), spell_mother_shahraz_fatal_attraction::SetDest(), spell_dk_summon_gargoyle::SetDest(), spell_spawn_blood_pool::SetDest(), Player::SetEntryPoint(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Unit::SetHover(), Unit::SetInCombatState(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::setphase(), Creature::SetPosition(), GameObject::SetPosition(), FleeingMovementGenerator< T >::SetTargetLocation(), PathGenerator::ShortenPathUntilDist(), boss_thorim::boss_thorimAI::SpawnArenaNPCs(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnClouds(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), boss_ossirian::SpawnNextCrystal(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SpawnPyramidWave(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnTentacle(), boss_freya::boss_freyaAI::SpawnWave(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), boss_majordomo::boss_majordomoAI::SpellHit(), boss_headless_horseman_pumpkin::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), npc_nerubian_burrower::npc_nerubian_burrowerAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_freya::boss_freyaAI::SpellHitTarget(), boss_cyanigosa::boss_cyanigosaAI::SpellHitTarget(), npc_chesspiece::SpellHitTarget(), boss_grobbulus::boss_grobbulusAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_ionar::boss_ionarAI::Split(), boss_janalai::StartBombing(), boss_felmyst::StartIntro(), Movement::MoveSplineInit::Stop(), Unit::StopMovingOnCurrentPos(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::StorePrisoner(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), boss_anzu::SummonBroods(), Map::SummonCreature(), npc_ravenclaw_apparition::npc_ravenclaw_apparitionAI::SummonCrowd(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SummonDeathOrbs(), boss_sjonnir::boss_sjonnirAI::SummonDwarfes(), npc_kiljaeden_controller::SummonedCreatureDies(), Map::SummonGameObject(), Spell::SummonGuardian(), boss_yoggsaron::boss_yoggsaronAI::SummonImmortalGuardian(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::SummonInfernal(), go_wind_stone::go_wind_stoneAI::SummonNPC(), Player::SummonPet(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), Map::SwitchGridContainers(), Player::TeleportTo(), BattlegroundRV::TeleportUnitToNewZ(), spell_midsummer_fling_torch::ThrowNextTorch(), CreatureAI::TriggerAlert(), npc_doomfire_spirit::TryTeleportInDirection(), MotionTransport::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), Creature::Update(), Player::Update(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), npc_forest_frog::UpdateAI(), npc_dark_iron_attack_generator::UpdateAI(), npc_dark_iron_attack_mole_machine::UpdateAI(), npc_winterfin_playmate::UpdateAI(), npc_snowfall_glade_playmate::UpdateAI(), npc_the_biggest_tree::UpdateAI(), npc_high_oracle_soo_roo::UpdateAI(), npc_elder_kekek::UpdateAI(), npc_the_etymidian::UpdateAI(), npc_alexstraza_the_lifebinder::UpdateAI(), npc_pilgrims_bounty_chair::UpdateAI(), npc_medivh_bm::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), boss_elder_nadox::UpdateAI(), npc_taldaram_flamesphere::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), npc_frost_sphere::npc_frost_sphereAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), npc_coldflame::npc_coldflameAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), boss_ormorok::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_ingvar_the_plunderer::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_minigob_manabonk::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_wounded_skirmisher::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), PathGenerator::UpdateFilter(), Unit::UpdateHeight(), Player::UpdatePosition(), Unit::UpdatePosition(), WorldObject::UpdatePositionData(), GameObject::Use(), Cell::Visit(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), Map::VisitNearbyCellsOf(), Map::VisitNearbyCellsOfPlayer(), Cell::VisitWorldObjects(), npc_barnes::npc_barnesAI::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), and npc_emily::npc_emilyAI::WaypointReached().
GetPositionZ()
float Position::GetPositionZ () const inline
{ return m_positionZ; }
References m_positionZ.
Referenced by Battleground::_CheckSafePositions(), Unit::_ExitVehicle(), WorldObject::_IsWithinDist(), GameObject::_IsWithinDist(), Player::_SaveCharacter(), Player::_SaveEntryPoint(), RandomMovementGenerator< T >::_setRandomLocation(), Spell::AddGOTarget(), WorldObject::AddToWorld(), Spell::AddUnitTarget(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::AttackStart(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::AttackStart(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::AttackStart(), boss_loatheb::boss_loathebAI::boss_loathebAI(), Unit::BuildMovementPacket(), Transport::CalculatePassengerOffset(), Transport::CalculatePassengerPosition(), boss_kalecgos::CanAIAttack(), boss_sathrovarr::CanAIAttack(), boss_devourer_of_souls::boss_devourer_of_soulsAI::CanAIAttack(), npc_igb_ship_crew::npc_igb_ship_crewAI::CanAIAttack(), npc_gunship_boarding_addAI::CanAIAttack(), boss_professor_putricide::boss_professor_putricideAI::CanAIAttack(), npc_icc_spire_frostwyrm::CanAIAttack(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::CanAIAttack(), boss_attumen::CanMeleeHit(), boss_midnight::CanMeleeHit(), Map::CanReachPositionAndGetValidCoords(), GameObject::CastSpell(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Spell::CheckEffectTarget(), boss_hakkar::boss_hakkarAI::CheckInRoom(), BattlegroundRV::CheckPositionForUnit(), boss_isle_of_conquest::boss_isle_of_conquestAI::CheckRageBuff(), boss_alar::ConstructWaypointsAndMove(), Player::ContinueTaxiFlight(), Map::ConvertCorpseToBones(), Creature::Create(), Corpse::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), MotionTransport::CreateNPCPassenger(), boss_ick::boss_ickAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), boss_razorscale::boss_razorscaleAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), npc_ice_tomb::npc_ice_tombAI::DamageTaken(), boss_viscidus::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken(), boss_nightbane::DoAction(), npc_kinetic_bomb::npc_kinetic_bombAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), boss_professor_putricide::boss_professor_putricideAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), npc_power_spark::npc_power_sparkAI::DoAction(), npc_hover_disk::npc_hover_diskAI::DoAction(), BattlegroundIC::DoAction(), FlightPathMovementGenerator::DoFinalize(), Creature::DoFleeToGetAssistance(), FlightPathMovementGenerator::DoReset(), ScriptedAI::DoSpawnCreature(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), ScriptedAI::DoTeleportPlayer(), Spell::EffectBind(), Spell::EffectCharge(), Spell::EffectChargeDest(), Spell::EffectDuel(), Spell::EffectLeap(), Spell::EffectLeapBack(), Spell::EffectPullTowards(), Spell::EffectResurrect(), Spell::EffectResurrectNew(), Spell::EffectStuck(), Spell::EffectSummonType(), Spell::EffectTeleUnitsFaceCaster(), Spell::EffectTransmitted(), npc_giant_claw_tentacle::Emerge(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode(), BattlegroundIC::EventPlayerClickedOnFlag(), CastArmageddon::Execute(), UtherBatteredHiltEvent::Execute(), IceTombSummonEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_kaelthas::ExecuteMiddleEvent(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), MapMgr::GetAreaId(), WorldObject::GetChargeContactPoint(), WorldObject::GetClosePoint(), BattlegroundEY::GetClosestGraveyard(), Graveyard::GetClosestGraveyard(), WorldObject::GetContactPoint(), WorldObject::GetDistanceOrder(), WorldObject::GetDistanceZ(), WorldObject::GetFloorZ(), WorldObject::GetHitSpherePointFor(), WorldObject::GetNearPoint(), GameObjectModelOwnerImpl::GetPosition(), GetPositionOffsetTo(), Unit::GetRandomContactPoint(), GameObject::GetRespawnPosition(), Creature::GetRespawnPosition(), WorldObject::GetStationaryZ(), GameObject::GetStationaryZ(), WorldObject::GetTransOffsetZ(), MapMgr::GetZoneId(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), AuraEffect::HandleAuraFeatherFall(), HandleBothDead(), BattlegroundIC::HandleCapturedNodes(), WorldSession::HandleCharFactionOrRaceChangeCallback(), misc_commandscript::HandleComeToMeCommand(), WorldSession::HandleCorpseQueryOpcode(), debug_commandscript::HandleDebugSendOpcodeCommand(), OutdoorPvPSI::HandleDropFlag(), spell_moroes_vanish::HandleDummy(), spell_anti_air_rocket_bomber::HandleDummy(), spell_q12589_shoot_rjr::HandleDummy(), spell_dk_death_grip::HandleDummy(), spell_item_underbelly_elixir::HandleDummy(), spell_midsummer_torch_quest::HandleEffectApply(), spell_z_check_aura::HandleEffectApply(), spell_hodir_flash_freeze_aura::HandleEffectPeriodic(), Player::HandleFall(), spell_q12014_steady_as_a_rock::HandleFinish(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), misc_commandscript::HandleGPSCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), spell_class_call_handler::HandleOnHitRogue(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), spell_entropius_black_hole_effect::HandlePull(), spell_boss_magus_telestra_gravity_well::HandlePull(), spell_dreamwalker_summon_portal::HandleScript(), spell_marrowgar_coldflame_bonestorm::HandleScriptEffect(), spell_yogg_saron_sanity_reduce::HandleScriptEffect(), spell_winter_veil_racer_slam_hit::HandleScriptEffect(), spell_marrowgar_coldflame::HandleScriptEffect(), spell_ice_bombardment_dest_picker::HandleScriptEffect(), spell_q10612_10613_the_fel_and_the_furious::HandleScriptEffect(), spell_sindragosa_icy_grip_jump::HandleSpecial(), ArenaSpectator::HandleSpectatorSpectateCommand(), misc_commandscript::HandleSummonCommand(), tele_commandscript::HandleTeleAddCommand(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), debug_commandscript::HandleWPGPSCommand(), wp_commandscript::HandleWpModifyCommand(), spell_q11065_wrangle_some_aether_rays_aura::if(), boss_captain_skarloc::InitializeAI(), boss_sapphiron::boss_sapphironAI::InitializeAI(), npc_preparations_for_war_vehicle::InitializeAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::InitWaypoint(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), GameObject::IsAtInteractDistance(), Player::IsFalling(), SpellArea::IsFitToRequirements(), Unit::isInAccessiblePlaceFor(), GameObject::IsInRange(), WorldObject::IsInRange(), WorldObject::IsInRange3d(), boss_algalon_the_observer::boss_algalon_the_observerAI::IsInRoom(), PathGenerator::IsInvalidDestinationZ(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::IsSummonedBy(), MapMgr::IsValidMapCoord(), IsValidPlatformTarget(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle(), ZRangeBoundary::IsWithinBoundaryArea(), IsWithinBox(), Unit::IsWithinCombatRange(), WorldObject::IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), Unit::IsWithinRange(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::JustDied(), npc_enraged_spirit::npc_enraged_spiritAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_akilzon::JustEngagedWith(), boss_mandokir::boss_mandokirAI::JustEngagedWith(), boss_vem::JustEngagedWith(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), boss_ingvar_the_plunderer::JustSummoned(), boss_kiljaeden::JustSummoned(), npc_kalecgos_kj::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), spell_svalna_revive_champion::Land(), Movement::MoveSplineInit::Launch(), spell_ioc_launch::Launch(), Player::LoadFromDB(), LogCommandUsage(), spell_gen_basic_campfire::ModDest(), MotionMaster::MoveCircleTarget(), MotionMaster::MoveFall(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::MoveInLineOfSight(), boss_eye_of_cthun::MoveInLineOfSight(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), boss_krik_thir::boss_krik_thirAI::MoveInLineOfSight(), npc_brann_radio::npc_brann_radioAI::MoveInLineOfSight(), npc_ulduar_snow_mound::MoveInLineOfSight(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), npc_shattered_hand_scout::MoveInLineOfSight(), MotionMaster::MoveKnockbackFrom(), boss_malygos::boss_malygosAI::MovementInform(), npc_hover_disk::npc_hover_diskAI::MovementInform(), npc_enslaved_proto_drake::MovementInform(), boss_vazruden_the_herald::MovementInform(), npc_omen::npc_omenAI::MovementInform(), npc_escortAI::MovementInform(), npc_concentrated_ball::npc_concentrated_ballAI::MoveToNextPoint(), npc_hor_leader_second::npc_hor_leader_secondAI::MoveToNextStopPoint(), Unit::NearTeleportTo(), npc_ball_of_flame::npc_ball_of_flameAI::npc_ball_of_flameAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::npc_icc_vengeful_fleshreaperAI(), npc_medivh_bm::npc_medivh_bm(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnCreatureCreate(), instance_zulaman::instance_zulaman_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), go_ethereum_prison::OnGossipHello(), go_ethereum_stasis::OnGossipHello(), go_hive_pod::OnGossipHello(), go_veil_skith_cage::OnGossipHello(), npc_vh_sinclari::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), spell_yogg_saron_brain_link_aura::OnPeriodic(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter(), at_icc_saurfang_portal::OnTrigger(), AreaTrigger_at_scent_larkorwi::OnTrigger(), at_malfurion_stormrage::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), RotfaceHeightCheck::operator()(), Acore::AnyPlayerExactPositionInGameObjectRangeCheck::operator()(), NotInStomachSelector::operator()(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), SpectralBlastCheck::operator()(), IgbArtilleryCheck::operator()(), MysticBuffetTargetFilter::operator()(), HeightDifferenceCheck::operator()(), npc_vehicle_d16_propelled_delivery::npc_vehicle_d16_propelled_deliveryAI::PassengerBoarded(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), npc_vics_flying_machine::npc_vics_flying_machineAI::PassengerBoarded(), spell_halion_twilight_phasing::Phase(), BattlegroundIC::PostUpdateImpl(), npc_dark_iron_attack_generator::PrepareEvent(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), RelocateOffset(), RelocatePolarOffset(), npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons(), Player::RepopAtGraveyard(), boss_malchezaar::Reset(), npc_kiljaeden_controller::Reset(), boss_mandokir::boss_mandokirAI::Reset(), npc_brewfest_super_brew_trigger::Reset(), boss_archimonde::Reset(), boss_ossirian::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), npc_crystal_spike::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), boss_freya_nature_bomb::boss_freya_nature_bombAI::Reset(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::Reset(), npc_dancing_flames::npc_dancing_flamesAI::Reset(), Player::SavePositionInDB(), Player::SaveRecallPosition(), CharmInfo::SaveStayPosition(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), boss_felmyst::ScheduleFlightAbilities(), boss_felmyst::ScheduleFlightSequence(), boss_nightbane::ScheduleFly(), Spell::SelectImplicitCasterDestTargets(), boss_gluth::boss_gluthAI::SelectPlayerInRoom(), npc_midsummer_torch_target::SelectPosition(), npc_gothik_trigger::npc_gothik_triggerAI::SelectRandomSkullPile(), PassengerController::SelectSpawnPoint(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), WorldSession::SendLearnNewTaxiNode(), Unit::SendMonsterMove(), WorldSession::SendTaxiMenu(), Player::SendTaxiNodeStatusMultiple(), WorldSession::SendTaxiStatus(), Unit::SendTeleportPacket(), BattlegroundMgr::SendToBattleground(), Player::SetCanFly(), Creature::SetCanFly(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), instance_stratholme::instance_stratholme_InstanceMapScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::SetData(), spell_blood_council_summon_shadow_resonance::SetDest(), spell_mother_shahraz_fatal_attraction::SetDest(), spell_dk_summon_gargoyle::SetDest(), spell_spawn_blood_pool::SetDest(), Player::SetEntryPoint(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Unit::SetHover(), Unit::SetInCombatState(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::setphase(), Creature::SetPosition(), GameObject::SetPosition(), FleeingMovementGenerator< T >::SetTargetLocation(), PathGenerator::ShortenPathUntilDist(), boss_thorim::boss_thorimAI::SpawnArenaNPCs(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), boss_ossirian::SpawnNextCrystal(), boss_freya::boss_freyaAI::SpawnWave(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), boss_julianne::SpellHit(), boss_majordomo::boss_majordomoAI::SpellHit(), boss_headless_horseman_pumpkin::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), npc_nerubian_burrower::npc_nerubian_burrowerAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_freya::boss_freyaAI::SpellHitTarget(), boss_cyanigosa::boss_cyanigosaAI::SpellHitTarget(), npc_chesspiece::SpellHitTarget(), boss_grobbulus::boss_grobbulusAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_ionar::boss_ionarAI::Split(), boss_janalai::StartBombing(), boss_felmyst::StartIntro(), dragonmaw_race_npc::StartRaceAttacks(), Movement::MoveSplineInit::Stop(), Unit::StopMovingOnCurrentPos(), boss_anzu::SummonBroods(), Map::SummonCreature(), SummonCroneIfReady(), npc_ravenclaw_apparition::npc_ravenclaw_apparitionAI::SummonCrowd(), boss_sjonnir::boss_sjonnirAI::SummonDwarfes(), npc_kiljaeden_controller::SummonedCreatureDies(), Map::SummonGameObject(), go_wind_stone::go_wind_stoneAI::SummonNPC(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), Player::TeleportTo(), spell_midsummer_fling_torch::ThrowNextTorch(), npc_doomfire_spirit::TryTeleportInDirection(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), Creature::Update(), Player::Update(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_dark_iron_attack_generator::UpdateAI(), npc_dark_iron_attack_mole_machine::UpdateAI(), npc_winterfin_playmate::UpdateAI(), npc_snowfall_glade_playmate::UpdateAI(), npc_the_biggest_tree::UpdateAI(), npc_high_oracle_soo_roo::UpdateAI(), npc_elder_kekek::UpdateAI(), npc_the_etymidian::UpdateAI(), npc_alexstraza_the_lifebinder::UpdateAI(), npc_pilgrims_bounty_chair::UpdateAI(), npc_medivh_bm::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), boss_elder_nadox::UpdateAI(), npc_taldaram_flamesphere::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), npc_putricide_oozeAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), boss_ormorok::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_ingvar_the_plunderer::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_minigob_manabonk::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), Player::UpdateFallInformationIfNeed(), PathGenerator::UpdateFilter(), Creature::UpdateMovementFlags(), Player::UpdatePosition(), Unit::UpdatePosition(), WorldObject::UpdatePositionData(), GameObject::Use(), npc_barnes::npc_barnesAI::WaypointReached(), npc_scarlet_miner::npc_scarlet_minerAI::WaypointReached(), and npc_emily::npc_emilyAI::WaypointReached().
GetRelativeAngle() [1/2]
float Position::GetRelativeAngle (const Position * pos) const inline
    {
        return NormalizeOrientation(GetAngle(pos) - m_orientation);
    }
References GetAngle(), m_orientation, and NormalizeOrientation().
Referenced by Spell::EffectCharge(), Spell::EffectChargeDest(), HasInLine(), MotionMaster::MoveKnockbackFrom(), ChaseMovementGenerator< T >::PositionOkay(), and Spell::SelectImplicitTrajTargets().
GetRelativeAngle() [2/2]
float Position::GetRelativeAngle (float x, float y) const inline
{ return NormalizeOrientation(GetAngle(x, y) - m_orientation); }
References GetAngle(), m_orientation, and NormalizeOrientation().
GetSinCos()
void Position::GetSinCos (float x, float y, float & vsin, float & vcos) const
{
    float dx = GetPositionX() - x;
    float dy = GetPositionY() - y;
    if (std::fabs(dx) < 0.001f && std::fabs(dy) < 0.001f)
    {
        float angle = (float)rand_norm() * static_cast<float>(2 * M_PI);
        vcos = std::cos(angle);
        vsin = std::sin(angle);
    }
    else
    {
        float dist = sqrt((dx * dx) + (dy * dy));
        vcos = dx / dist;
        vsin = dy / dist;
    }
}
References GetPositionX(), GetPositionY(), and rand_norm().
Referenced by Unit::KnockbackFrom().
HasInArc()
bool Position::HasInArc (float arcangle, const Position * pos, float targetRadius = 0.0f) const
{
    // always have self in arc
    if (obj == this)
        return true;
    // move arc to range 0.. 2*pi
    arc = Position::NormalizeOrientation(arc);
    float angle = GetAngle(obj);
    angle -= m_orientation;
    // move angle to range -pi ... +pi
    angle = Position::NormalizeOrientation(angle);
    if (angle > M_PI)
        angle -= 2.0f * M_PI;
    float lborder = -1 * (arc / 2.0f);                      // in range -pi..0
    float rborder = (arc / 2.0f);                           // in range 0..pi
    // pussywizard: take into consideration target size
    if (targetRadius > 0.0f)
    {
        float distSq = GetExactDist2dSq(obj);
        // pussywizard: at least a part of target's model is in every direction
        if (distSq < targetRadius * targetRadius)
            return true;
        float angularRadius = 2.0f * atan(targetRadius / (2.0f * sqrt(distSq)));
        lborder -= angularRadius;
        rborder += angularRadius;
    }
    return (angle >= lborder) && (angle <= rborder);
}
References GetAngle(), GetExactDist2dSq(), m_orientation, and NormalizeOrientation().
Referenced by WorldObject::CanDetectStealthOf(), Spell::CheckRange(), boss_janalai::DamageDealt(), Unit::DealMeleeDamage(), npc_echo_of_medivh::GetPiece(), Unit::HandleDummyAuraProc(), HasInLine(), WorldObject::isInBack(), Unit::isInBackInMap(), WorldObject::isInFront(), Unit::isInFrontInMap(), Unit::isSpellBlocked(), npc_underbat::JustEngagedWith(), boss_kagani_nightstrike::JustEngagedWith(), Unit::MagicSpellHitResult(), Unit::MeleeSpellHitResult(), Unit::RollMeleeOutcomeAgainst(), boss_romulo::ScheduleCombat(), boss_nightbane::ScheduleGround(), Spell::SearchChainTargets(), Player::Update(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), and PetAI::UpdateAI().
HasInLine()
bool Position::HasInLine (Position const * pos, float width) const
{
    if (!HasInArc(float(M_PI), pos))
        return false;
    float angle = GetRelativeAngle(pos);
    return std::fabs(std::sin(angle)) * GetExactDist2d(pos->GetPositionX(), pos->GetPositionY()) < width;
}
References GetExactDist2d(), GetPositionX(), GetPositionY(), GetRelativeAngle(), and HasInArc().
Referenced by spell_brewfest_toss_mug::FilterTargets(), spell_cthun_dark_glare::FilterTargets(), spell_lurker_below_spout_cone::FilterTargets(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), Acore::WorldObjectSpellConeTargetCheck::operator()(), and Acore::WorldObjectSpellTrajTargetCheck::operator()().
IsInDist() [1/2]
bool Position::IsInDist (const Position * pos, float dist) const inline
    {
        return GetExactDistSq(pos) < dist * dist;
    }
References GetExactDistSq().
IsInDist() [2/2]
bool Position::IsInDist (float x, float y, float z, float dist) const inline
    {
        return GetExactDistSq(x, y, z) < dist * dist;
    }
References GetExactDistSq().
Referenced by Creature::CanCreatureAttack(), WorldObject::IsWithinDist3d(), and Creature::Update().
IsInDist2d() [1/2]
bool Position::IsInDist2d (const Position * pos, float dist) const inline
    {
        return GetExactDist2dSq(pos) < dist * dist;
    }
References GetExactDist2dSq().
IsInDist2d() [2/2]
bool Position::IsInDist2d (float x, float y, float dist) const inline
    {
        return GetExactDist2dSq(x, y) < dist * dist;
    }
References GetExactDist2dSq().
Referenced by Creature::CanCreatureAttack(), and WorldObject::IsWithinDist2d().
IsPositionValid()
bool Position::IsPositionValid () const
{
    return Acore::IsValidMapCoord(m_positionX, m_positionY, m_positionZ, m_orientation);
}
References Acore::IsValidMapCoord(), m_orientation, m_positionX, m_positionY, and m_positionZ.
Referenced by CinematicMgr::BeginCinematic(), Creature::Create(), Corpse::Create(), GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtCreature(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateMoTrans(), MotionTransport::CreateNPCPassenger(), Unit::ExecuteDelayedUnitRelocationEvent(), WorldSession::HandleMovementOpcodes(), npc_simone::npc_simoneAI::JustDied(), Corpse::LoadCorpseFromDB(), Player::LoadFromDB(), Pet::LoadPetFromDB(), NPCStaveQuestAI::SetHomePosition(), Player::SummonPet(), Player::Update(), CinematicMgr::UpdateCinematicLocation(), Map::VisitNearbyCellsOf(), and Map::VisitNearbyCellsOfPlayer().
IsWithinBox()
bool Position::IsWithinBox (const Position & center, float xradius, float yradius, float zradius) const
{
    // rotate the WorldObject position instead of rotating the whole cube, that way we can make a simplified
    // is-in-cube check and we have to calculate only one point instead of 4
    // 2PI = 360*, keep in mind that ingame orientation is counter-clockwise
    double rotation = 2 * M_PI - center.GetOrientation();
    double sinVal = std::sin(rotation);
    double cosVal = std::cos(rotation);
    float BoxDistX = GetPositionX() - center.GetPositionX();
    float BoxDistY = GetPositionY() - center.GetPositionY();
    float rotX = float(center.GetPositionX() + BoxDistX * cosVal - BoxDistY * sinVal);
    float rotY = float(center.GetPositionY() + BoxDistY * cosVal + BoxDistX * sinVal);
    // box edges are parallel to coordiante axis, so we can treat every dimension independently :D
    float dz = GetPositionZ() - center.GetPositionZ();
    float dx = rotX - center.GetPositionX();
    float dy = rotY - center.GetPositionY();
    if ((std::fabs(dx) > xradius) ||
        (std::fabs(dy) > yradius) ||
        (std::fabs(dz) > zradius))
    {
        return false;
    }
    return true;
}
References GetOrientation(), GetPositionX(), GetPositionY(), and GetPositionZ().
Referenced by Player::IsInAreaTriggerRadius().
NormalizeOrientation()
static float Position::NormalizeOrientation (float o) inline static
    {
        // fmod only supports positive numbers. Thus we have
        // to emulate negative numbers
        if (o < 0)
        {
            float mod = o * -1;
            mod = std::fmod(mod, 2.0f * static_cast<float>(M_PI));
            mod = -mod + 2.0f * static_cast<float>(M_PI);
            return mod;
        }
        return std::fmod(o, 2.0f * static_cast<float>(M_PI));
    }
Referenced by TransportBase::CalculatePassengerOffset(), TransportBase::CalculatePassengerPosition(), GameObject::Create(), StaticTransport::Create(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction(), boss_archimonde::DoCastDoomFire(), TransportMgr::GeneratePath(), GetAbsoluteAngle(), GetRelativeAngle(), spell_mimiron_p3wx2_laser_barrage_aura::HandleEffectPeriodic(), HasInArc(), CreatureGroup::LeaderMoveTo(), ChaseAngle::LowerBound(), spell_lurker_below_spout::OnPeriodic(), StaticTransport::RelocateToProgress(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), ToAbsoluteAngle(), npc_doomfire_spirit::TryTeleportInDirection(), MotionTransport::Update(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), and ChaseAngle::UpperBound().
operator G3D::Vector3()
Position::operator G3D::Vector3 () const inline
    {
        return { m_positionX, m_positionY, m_positionZ };
    }
References m_positionX, m_positionY, and m_positionZ.
operator!=()
bool Position::operator!= (Position const & a) inline
    {
        return !(operator==(a));
    }
References operator==().
operator=() [1/2]
Position & Position::operator= (const Position &) default
operator=() [2/2]
Position & Position::operator= (Position &&) default
operator==()
bool Position::operator== (Position const & a) const
{
    return (G3D::fuzzyEq(a.m_positionX, m_positionX) &&
            G3D::fuzzyEq(a.m_positionY, m_positionY) &&
            G3D::fuzzyEq(a.m_positionZ, m_positionZ) &&
            G3D::fuzzyEq(a.m_orientation, m_orientation));
}
References m_orientation, m_positionX, m_positionY, and m_positionZ.
Referenced by operator!=().
PositionXYZOStream()
Position::PositionXYZOStreamer Position::PositionXYZOStream () inline
    {
        return PositionXYZOStreamer(*this);
    }
Referenced by WorldSession::ReadMovementInfo(), Player::TeleportTo(), and WorldSession::WriteMovementInfo().
PositionXYZStream()
Position::PositionXYZStreamer Position::PositionXYZStream () inline
    {
        return PositionXYZStreamer(*this);
    }
Referenced by SpellCastTargets::Read(), and SpellCastTargets::Write().
Relocate() [1/5]
void Position::Relocate (const Position & pos) inline
    {
        m_positionX = pos.m_positionX;
        m_positionY = pos.m_positionY;
        m_positionZ = pos.m_positionZ;
        m_orientation = pos.m_orientation;
    }
References m_orientation, m_positionX, m_positionY, and m_positionZ.
Relocate() [2/5]
void Position::Relocate (const Position * pos) inline
    {
        m_positionX = pos->m_positionX;
        m_positionY = pos->m_positionY;
        m_positionZ = pos->m_positionZ;
        m_orientation = pos->m_orientation;
    }
References m_orientation, m_positionX, m_positionY, and m_positionZ.
Relocate() [3/5]
void Position::Relocate (float x, float y) inline
    {
        m_positionX = x;
        m_positionY = y;
    }
References m_positionX, and m_positionY.
Referenced by Unit::_ExitVehicle(), Vehicle::AddPassenger(), MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), Map::ConvertCorpseToBones(), Player::Create(), Creature::Create(), Corpse::Create(), GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateMoTrans(), MotionTransport::CreateNPCPassenger(), Map::CreatureRelocation(), boss_ick::boss_ickAI::DamageTaken(), MotionTransport::DelayedTeleportTransport(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::DoSummonGrandChampion(), Map::DynamicObjectRelocation(), Spell::EffectPullTowards(), Spell::EffectResurrectPet(), npc_midsummer_torch_target::FillPositions(), GameObject::GameObject(), Map::GameObjectRelocation(), Unit::GetMeleeAttackPoint(), WorldLocation::GetWorldLocation(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveWorldportAck(), AuraEffect::HandlePhase(), spell_entropius_black_hole_effect::HandlePull(), spell_boss_magus_telestra_gravity_well::HandlePull(), WorldSession::HandleSetRaidDifficultyOpcode(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), WorldSession::HandleUpdateMissileTrajectory(), WorldSession::HandleUpdateProjectilePosition(), Corpse::LoadCorpseFromDB(), Creature::LoadCreatureFromDB(), Player::LoadFromDB(), Pet::LoadPetFromDB(), ObjectMgr::LoadTempSummons(), MMapTargetData::MMapTargetData(), MovementInfo::MovementInfo(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), WorldObject::MovePosition(), WorldObject::MovePositionToFirstCollision(), operator>>(), Map::PlayerRelocation(), Position(), RandomMovementGenerator< T >::RandomMovementGenerator(), SpellCastTargets::Read(), readCamera(), SpellDestination::Relocate(), spell_igb_teleport_to_enemy_ship::RelocateTransportOffset(), Creature::RemoveCorpse(), MotionTransport::RemovePassenger(), StaticTransport::RemovePassenger(), MovementInfo::TransportInfo::Reset(), Creature::Respawn(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitTrajTargets(), npc_midsummer_torch_target::SelectPosition(), Unit::SendTeleportPacket(), spell_blood_council_summon_shadow_resonance::SetDest(), Creature::SetHomePosition(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetPositionTraps(), Creature::SetTransportHomePosition(), BattlefieldWG::SetupBattlefield(), npc_taldaram_flamesphere::SetVictimPos(), SpellDestination::SpellDestination(), WorldObject::SummonCreature(), Player::SummonPet(), Player::TeleportTo(), Unit::Unit(), SpellCastTargets::Update(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), CinematicMgr::UpdateCinematicLocation(), Unit::UpdateHeight(), Spell::UpdatePointers(), MotionTransport::UpdatePosition(), Player::UpdateVisibilityForPlayer(), and WorldLocation::WorldRelocate().
Relocate() [4/5]
void Position::Relocate (float x, float y, float z) inline
    {
        m_positionX = x;
        m_positionY = y;
        m_positionZ = z;
    }
References m_positionX, m_positionY, and m_positionZ.
Relocate() [5/5]
void Position::Relocate (float x, float y, float z, float orientation) inline
    {
        m_positionX = x;
        m_positionY = y;
        m_positionZ = z;
        m_orientation = orientation;
    }
References m_orientation, m_positionX, m_positionY, and m_positionZ.
RelocateOffset()
void Position::RelocateOffset (const Position & offset)
{
    m_positionX = GetPositionX() + (offset.GetPositionX() * std::cos(GetOrientation()) + offset.GetPositionY() * std::sin(GetOrientation() + M_PI));
    m_positionY = GetPositionY() + (offset.GetPositionY() * std::cos(GetOrientation()) + offset.GetPositionX() * std::sin(GetOrientation()));
    m_positionZ = GetPositionZ() + offset.GetPositionZ();
    m_orientation = GetOrientation() + offset.GetOrientation();
}
References GetOrientation(), GetPositionX(), GetPositionY(), GetPositionZ(), m_orientation, m_positionX, m_positionY, and m_positionZ.
Referenced by Unit::_ExitVehicle(), spell_valanar_kinetic_bomb::ChangeSummonPos(), spell_onslaught_or_call_bone_gryphon::ChangeSummonPos(), spell_the_lich_king_teleport_to_frostmourne_hc::ModDest(), spell_the_lich_king_summon_into_air::ModDestHeight(), spell_halion_summon_exit_portals::OnSummon(), npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded(), SpellDestination::Relocate(), spell_igb_gunship_fall_teleport::RelocateDest(), SpellDestination::RelocateOffset(), spell_valanar_kinetic_bomb_summon::SelectDest(), SpellCastTargets::Update(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), npc_wintergarde_gryphon::UpdateAI(), and Spell::UpdatePointers().
RelocatePolarOffset()
void Position::RelocatePolarOffset (float angle, float dist, float z = 0.0f)
{
    SetOrientation(GetOrientation() + angle);
    m_positionX = GetPositionX() + dist * std::cos(GetOrientation());
    m_positionY = GetPositionY() + dist * std::sin(GetOrientation());
    m_positionZ = GetPositionZ() + z;
}
References GetOrientation(), GetPositionX(), GetPositionY(), GetPositionZ(), m_positionX, m_positionY, m_positionZ, and SetOrientation().
Referenced by spell_midsummer_fling_torch::ThrowNextTorch().
SetOrientation()
void Position::SetOrientation (float orientation) inline
    {
        m_orientation = orientation;
    }
References m_orientation.
Referenced by Unit::_ExitVehicle(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), boss_illidan_stormrage::DoAction(), gobject_commandscript::HandleGameObjectMoveCommand(), WorldSession::HandleMovementOpcodes(), spell_shadow_bolt_whirl::HandlePeriodic(), spell_dk_dancing_rune_weapon::HandleProc(), spell_marrowgar_coldflame_bonestorm::HandleScriptEffect(), spell_marrowgar_coldflame::HandleScriptEffect(), boss_alar::JustEngagedWith(), boss_halion::boss_halionAI::JustSummoned(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), npc_earthen_ring_flamecaller::MovementInform(), boss_volkhan::boss_volkhanAI::MovementInform(), boss_razorscale::boss_razorscaleAI::MovementInform(), boss_lady_vashj::MovementInform(), npc_hor_lich_king::npc_hor_lich_kingAI::MovementInform(), WorldObject::MovePosition(), WorldObject::MovePositionToFirstCollision(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded(), SmartScript::ProcessAction(), readCamera(), RelocatePolarOffset(), boss_magtheridon::ScheduleCombatEvents(), PassengerController::SelectSpawnPoint(), Player::SetClientControl(), npc_alexstraza_the_lifebinder::SetData(), Unit::SetInFront(), boss_thorim::boss_thorimAI::SpellHit(), boss_devourer_of_souls::boss_devourer_of_soulsAI::SpellHitTarget(), spell_midsummer_fling_torch::ThrowNextTorch(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_alexstraza_the_lifebinder::UpdateAI(), boss_onyxia::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_wintergarde_gryphon::UpdateAI(), Unit::UpdateOrientation(), Unit::UpdateSplinePosition(), and npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::WaypointReached().
ToAbsoluteAngle()
float Position::ToAbsoluteAngle (float relAngle) const inline
{ return NormalizeOrientation(relAngle + m_orientation); }
References m_orientation, and NormalizeOrientation().
Referenced by ChaseMovementGenerator< T >::DoUpdate(), and FollowMovementGenerator< T >::DoUpdate().
ToString()
std::string Position::ToString () const
{
    std::stringstream sstr;
    sstr << "X: " << m_positionX << " Y: " << m_positionY << " Z: " << m_positionZ << " O: " << m_orientation;
    return sstr.str();
}
References m_orientation, m_positionX, m_positionY, and m_positionZ.
Referenced by Player::_addSpell(), Pet::_LoadAuras(), Player::_LoadAuras(), Player::_LoadDailyQuestStatus(), Player::_LoadInventory(), Player::_LoadItem(), Player::_LoadMonthlyQuestStatus(), Player::_LoadPetStable(), Player::_LoadQuestStatus(), Player::_LoadSeasonalQuestStatus(), Player::_LoadSkills(), Player::_LoadSpellCooldowns(), Player::_LoadWeeklyQuestStatus(), Player::_SaveInventory(), Player::addActionButton(), WorldObject::AddObjectToRemoveList(), Unit::AttackerStateUpdate(), Player::BuildPlayerRepop(), Player::CanBankItem(), Unit::CastCustomSpell(), Player::CastItemCombatSpell(), Unit::CastSpell(), Player::CheckAreaExploreAndOutdoor(), Player::ContinueTaxiFlight(), Pet::CreateBaseAtCreature(), Unit::DelayOwnedAuras(), Creature::DeleteFromDB(), Player::DuelComplete(), Player::EnvironmentalDamage(), WorldLocation::GetDebugInfo(), Player::GetGameObjectIfCanInteractWith(), Player::InitDisplayIds(), Player::LearnCustomSpells(), Player::learnSpell(), Corpse::LoadCorpseFromDB(), Creature::LoadCreaturesAddon(), Player::LoadFromDB(), Pet::LoadPetFromDB(), Player::OnGossipSelect(), MovementInfo::OutDebug(), SpellCastTargets::OutDebug(), Unit::OutDebugInfo(), Player::removeActionButton(), Unit::RemoveCharmedBy(), GameObject::RemoveFromOwner(), Creature::Respawn(), Player::SendActionButtons(), Player::SendItemRetrievalMail(), Unit::SendMeleeAttackStop(), BattlegroundMgr::SendToBattleground(), Unit::SetCharm(), Unit::SetCharmedBy(), Player::setDeathState(), Player::SetMover(), Player::StopCastingCharm(), Player::TeleportTo(), Creature::Update(), Player::Update(), Player::UpdateHomebindTime(), GameObject::Use(), and WorldObject::~WorldObject().
Member Data Documentation
m_orientation
float Position::m_orientation = 0
Referenced by GetOrientation(), GetPosition(), GetPositionOffsetTo(), GetRelativeAngle(), HasInArc(), IsPositionValid(), at_orb_of_command::OnTrigger(), at_naxxramas_hub_portal::OnTrigger(), operator==(), Relocate(), RelocateOffset(), PassengerController::SelectSpawnPoint(), SetOrientation(), Battlefield::SpawnCreature(), ToAbsoluteAngle(), and ToString().
m_positionX
float Position::m_positionX = 0
Referenced by WorldObject::_IsWithinDist(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::AttackStart(), CinematicMgr::BeginCinematic(), npc_chained_spirit::DoAction(), boss_bug_trio::DoFinalSpell(), npc_ranshalla::npc_ranshallaAI::DoSummonPriestess(), Spell::EffectCharge(), Spell::EffectChargeDest(), IceTombSummonEvent::Execute(), GetAbsoluteAngle(), GetExactDist(), GetExactDist2d(), GetExactDist2dSq(), GetExactDistSq(), GetPosition(), GetPositionOffsetTo(), GetPositionX(), WorldObject::GetRandomPoint(), WorldLocation::GetWorldLocation(), spell_item_draenic_pale_ale::HandleSummon(), IsPositionValid(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), MotionMaster::MoveBackwards(), MotionMaster::MoveForwards(), MotionMaster::MoveJump(), MotionMaster::MovePoint(), WorldObject::MovePosition(), WorldObject::MovePositionToFirstCollision(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), spell_blackrock_spire_call_of_vaelastrasz::OnEffect(), spell_halion_summon_exit_portals::OnSummon(), at_orb_of_command::OnTrigger(), at_naxxramas_hub_portal::OnTrigger(), operator G3D::Vector3(), operator==(), PredictPosition(), SmartScript::ProcessAction(), Relocate(), RelocateOffset(), RelocatePolarOffset(), Spell::SelectImplicitTrajTargets(), PassengerController::SelectSpawnPoint(), spell_mother_shahraz_fatal_attraction::SetDest(), Battlefield::SpawnCreature(), ToString(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), CinematicMgr::UpdateCinematicLocation(), and Unit::UpdateSplinePosition().
m_positionY
float Position::m_positionY = 0
Referenced by WorldObject::_IsWithinDist(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::AttackStart(), CinematicMgr::BeginCinematic(), npc_chained_spirit::DoAction(), boss_bug_trio::DoFinalSpell(), npc_ranshalla::npc_ranshallaAI::DoSummonPriestess(), Spell::EffectCharge(), Spell::EffectChargeDest(), IceTombSummonEvent::Execute(), GetAbsoluteAngle(), GetExactDist(), GetExactDist2d(), GetExactDist2dSq(), GetExactDistSq(), GetPosition(), GetPositionOffsetTo(), GetPositionY(), WorldObject::GetRandomPoint(), WorldLocation::GetWorldLocation(), spell_item_draenic_pale_ale::HandleSummon(), IsPositionValid(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), MotionMaster::MoveBackwards(), MotionMaster::MoveForwards(), MotionMaster::MoveJump(), MotionMaster::MovePoint(), WorldObject::MovePosition(), WorldObject::MovePositionToFirstCollision(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), spell_blackrock_spire_call_of_vaelastrasz::OnEffect(), spell_halion_summon_exit_portals::OnSummon(), at_orb_of_command::OnTrigger(), at_naxxramas_hub_portal::OnTrigger(), operator G3D::Vector3(), operator==(), PredictPosition(), SmartScript::ProcessAction(), Relocate(), RelocateOffset(), RelocatePolarOffset(), Spell::SelectImplicitTrajTargets(), PassengerController::SelectSpawnPoint(), spell_mother_shahraz_fatal_attraction::SetDest(), Battlefield::SpawnCreature(), ToString(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), CinematicMgr::UpdateCinematicLocation(), and Unit::UpdateSplinePosition().
m_positionZ
float Position::m_positionZ = 0
Referenced by WorldObject::_IsWithinDist(), CinematicMgr::BeginCinematic(), Creature::Create(), boss_ick::boss_ickAI::DamageTaken(), npc_ice_tomb::npc_ice_tombAI::DamageTaken(), npc_chained_spirit::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), boss_bug_trio::DoFinalSpell(), CreatureAI::DoSummonFlyer(), npc_ranshalla::npc_ranshallaAI::DoSummonPriestess(), Spell::EffectCharge(), Spell::EffectChargeDest(), Spell::EffectSummonType(), IceTombSummonEvent::Execute(), GetExactDist(), GetExactDistSq(), GetPosition(), GetPositionOffsetTo(), GetPositionZ(), WorldObject::GetRandomPoint(), WorldLocation::GetWorldLocation(), spell_dk_death_grip::HandleDummy(), spell_boss_magus_telestra_gravity_well::HandlePull(), spell_item_draenic_pale_ale::HandleSummon(), IsPositionValid(), npc_coldflame::npc_coldflameAI::IsSummonedBy(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), spell_svalna_revive_champion::Land(), spell_gen_basic_campfire::ModDest(), MotionMaster::MoveBackwards(), MotionMaster::MoveForwards(), MotionMaster::MoveJump(), MotionMaster::MovePoint(), WorldObject::MovePosition(), WorldObject::MovePositionToFirstCollision(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), at_orb_of_command::OnTrigger(), at_naxxramas_hub_portal::OnTrigger(), operator G3D::Vector3(), operator==(), SmartScript::ProcessAction(), Relocate(), spell_igb_gunship_fall_teleport::RelocateDest(), RelocateOffset(), RelocatePolarOffset(), Spell::SelectImplicitTrajTargets(), PassengerController::SelectSpawnPoint(), spell_prince_taldaram_flame_sphere_summon::SetDest(), spell_azjol_nerub_impale_summon::SetDest(), spell_dk_summon_gargoyle::SetDest(), Battlefield::SpawnCreature(), dragonmaw_race_npc::StartRaceAttacks(), BattlegroundRV::TeleportUnitToNewZ(), ToString(), npc_coldflame::npc_coldflameAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), CinematicMgr::UpdateCinematicLocation(), and Unit::UpdateSplinePosition().