AzerothCore: PetitionMgr Class Reference
PetitionMgr Class Reference
#include "PetitionMgr.h"
Public Member Functions
void LoadPetitions ()
void LoadSignatures ()
void AddPetition (ObjectGuid petitionGUID, ObjectGuid ownerGuid, std::string const &name, uint8 type)
void RemovePetition (ObjectGuid petitionGUID)
void RemovePetitionByOwnerAndType (ObjectGuid ownerGuid, uint8 type)
Petition const * GetPetition (ObjectGuid petitionGUID) const
Petition const * GetPetitionByOwnerWithType (ObjectGuid ownerGuid, uint8 type) const
PetitionContainer * GetPetitionStore ()
void AddSignature (ObjectGuid petitionGUID, uint32 accountId, ObjectGuid playerGuid)
void RemoveSignaturesByPlayer (ObjectGuid playerGuid)
void RemoveSignaturesByPlayerAndType (ObjectGuid playerGuid, uint8 type)
Signatures const * GetSignature (ObjectGuid petitionGUID) const
SignatureContainer * GetSignatureStore ()
Static Public Member Functions
static PetitionMgr * instance ()
Protected Attributes
PetitionContainer PetitionStore
SignatureContainer SignatureStore
Private Member Functions
PetitionMgr ()
~PetitionMgr ()
Detailed Description
Constructor & Destructor Documentation
PetitionMgr()
PetitionMgr::PetitionMgr () private
{
}
~PetitionMgr()
PetitionMgr::~PetitionMgr () private
{
}
Member Function Documentation
AddPetition()
void PetitionMgr::AddPetition (ObjectGuid petitionGUID, ObjectGuid ownerGuid, std::string const & name, uint8 type)
{
    Petition& p = PetitionStore[petitionGUID];
    p.petitionGuid = petitionGUID;
    p.ownerGuid = ownerGuid;
    p.petitionName = name;
    p.petitionType = type;
    Signatures& s = SignatureStore[petitionGUID];
    s.petitionGuid = petitionGUID;
    s.signatureMap.clear();
}
References Petition::ownerGuid, Petition::petitionGuid, Signatures::petitionGuid, Petition::petitionName, PetitionStore, Petition::petitionType, Signatures::signatureMap, and SignatureStore.
Referenced by LoadPetitions().
AddSignature()
void PetitionMgr::AddSignature (ObjectGuid petitionGUID, uint32 accountId, ObjectGuid playerGuid)
{
    Signatures& s = SignatureStore[petitionGUID];
    s.signatureMap[playerGuid] = accountId;
}
References Signatures::signatureMap, and SignatureStore.
Referenced by LoadSignatures().
GetPetition()
Petition const * PetitionMgr::GetPetition (ObjectGuid petitionGUID) const
{
    PetitionContainer::const_iterator itr = PetitionStore.find(petitionGUID);
    if (itr != PetitionStore.end())
        return &itr->second;
    return nullptr;
}
References PetitionStore.
GetPetitionByOwnerWithType()
Petition const * PetitionMgr::GetPetitionByOwnerWithType (ObjectGuid ownerGuid, uint8 type) const
{
    for (PetitionContainer::const_iterator itr = PetitionStore.begin(); itr != PetitionStore.end(); ++itr)
        if (itr->second.ownerGuid == ownerGuid && itr->second.petitionType == type)
            return &itr->second;
    return nullptr;
}
References PetitionStore.
GetPetitionStore()
PetitionContainer * PetitionMgr::GetPetitionStore () inline
{ return &PetitionStore; }
References PetitionStore.
GetSignature()
Signatures const * PetitionMgr::GetSignature (ObjectGuid petitionGUID) const
{
    SignatureContainer::const_iterator itr = SignatureStore.find(petitionGUID);
    if (itr != SignatureStore.end())
        return &itr->second;
    return nullptr;
}
References SignatureStore.
GetSignatureStore()
SignatureContainer * PetitionMgr::GetSignatureStore () inline
{ return &SignatureStore; }
References SignatureStore.
instance()
PetitionMgr * PetitionMgr::instance () static
{
    static PetitionMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadPetitions()
void PetitionMgr::LoadPetitions ()
{
    uint32 oldMSTime = getMSTime();
    PetitionStore.clear();
    QueryResult result = CharacterDatabase.Query("SELECT ownerguid, petitionguid, name, type FROM petition");
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 Petitions!");
        LOG_INFO("server.loading", " ");
        return;
    }
    uint32 count = 0;
    do
    {
        Field* fields = result->Fetch();
        AddPetition(ObjectGuid::Create<HighGuid::Item>(fields[1].Get<uint32>()), ObjectGuid::Create<HighGuid::Player>(fields[0].Get<uint32>()), fields[2].Get<std::string>(), fields[3].Get<uint8>());
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} Petitions in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References AddPetition(), CharacterDatabase, getMSTime(), GetMSTimeDiffToNow(), LOG_INFO, LOG_WARN, and PetitionStore.
LoadSignatures()
void PetitionMgr::LoadSignatures ()
{
    uint32 oldMSTime = getMSTime();
    SignatureStore.clear();
    QueryResult result = CharacterDatabase.Query("SELECT petitionguid, playerguid, player_account FROM petition_sign");
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 Petition signs!");
        LOG_INFO("server.loading", " ");
        return;
    }
    uint32 count = 0;
    do
    {
        Field* fields = result->Fetch();
        AddSignature(ObjectGuid::Create<HighGuid::Item>(fields[0].Get<uint32>()), fields[2].Get<uint32>(), ObjectGuid::Create<HighGuid::Player>(fields[1].Get<uint32>()));
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} Petition signs in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References AddSignature(), CharacterDatabase, getMSTime(), GetMSTimeDiffToNow(), LOG_INFO, LOG_WARN, and SignatureStore.
RemovePetition()
void PetitionMgr::RemovePetition (ObjectGuid petitionGUID)
{
    PetitionStore.erase(petitionGUID);
    // remove signatures
    SignatureStore.erase(petitionGUID);
}
References PetitionStore, and SignatureStore.
RemovePetitionByOwnerAndType()
void PetitionMgr::RemovePetitionByOwnerAndType (ObjectGuid ownerGuid, uint8 type)
{
    for (PetitionContainer::iterator itr = PetitionStore.begin(); itr != PetitionStore.end();)
    {
        if (itr->second.ownerGuid == ownerGuid && (!type || type == itr->second.petitionType))
        {
            // Remove invalid charter item
            if (type == itr->second.petitionType)
            {
                if (Player* owner = ObjectAccessor::FindConnectedPlayer(ownerGuid))
                {
                    if (Item* item = owner->GetItemByGuid(itr->first))
                    {
                        owner->DestroyItem(item->GetBagSlot(), item->GetSlot(), true);
                    }
                }
            }
            // remove signatures
            SignatureStore.erase(itr->first);
            PetitionStore.erase(itr++);
        }
        else
            ++itr;
    }
}
References ObjectAccessor::FindConnectedPlayer(), PetitionStore, and SignatureStore.
RemoveSignaturesByPlayer()
void PetitionMgr::RemoveSignaturesByPlayer (ObjectGuid playerGuid)
{
    for (SignatureContainer::iterator itr = SignatureStore.begin(); itr != SignatureStore.end(); ++itr)
    {
        SignatureMap::iterator signItr = itr->second.signatureMap.find(playerGuid);
        if (signItr != itr->second.signatureMap.end())
            itr->second.signatureMap.erase(signItr);
    }
}
References SignatureStore.
RemoveSignaturesByPlayerAndType()
void PetitionMgr::RemoveSignaturesByPlayerAndType (ObjectGuid playerGuid, uint8 type)
{
    for (SignatureContainer::iterator itr = SignatureStore.begin(); itr != SignatureStore.end(); ++itr)
    {
        Petition const* petition = sPetitionMgr->GetPetition(itr->first);
        if (!petition || petition->petitionType != type)
            continue;
        SignatureMap::iterator signItr = itr->second.signatureMap.find(playerGuid);
        if (signItr != itr->second.signatureMap.end())
            itr->second.signatureMap.erase(signItr);
    }
}
References Petition::petitionType, SignatureStore, and sPetitionMgr.
Member Data Documentation
PetitionStore
PetitionContainer PetitionMgr::PetitionStore protected
Referenced by AddPetition(), GetPetition(), GetPetitionByOwnerWithType(), GetPetitionStore(), LoadPetitions(), RemovePetition(), and RemovePetitionByOwnerAndType().
SignatureStore
SignatureContainer PetitionMgr::SignatureStore protected
Referenced by AddPetition(), AddSignature(), GetSignature(), GetSignatureStore(), LoadSignatures(), RemovePetition(), RemovePetitionByOwnerAndType(), RemoveSignaturesByPlayer(), and RemoveSignaturesByPlayerAndType().