AzerothCore: azerothcore-wotlk/src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp File Reference
instance_naxxramas.cpp File Reference
#include "AreaTriggerScript.h"
#include "CellImpl.h"
#include "CreatureScript.h"
#include "GridNotifiers.h"
#include "GridNotifiersImpl.h"
#include "InstanceMapScript.h"
#include "PassiveAI.h"
#include "ScriptedCreature.h"
#include "naxxramas.h"
Classes
class instance_naxxramas
struct instance_naxxramas::instance_naxxramas_InstanceMapScript
class boss_naxxramas_misc
struct boss_naxxramas_misc::boss_naxxramas_miscAI
class at_naxxramas_hub_portal
Functions
uint8 GetEruptionSection (float x, float y)
void AddSC_instance_naxxramas ()
Variables
const float HeiganPos [2] = {2796, -3707}
const float HeiganEruptionSlope [3]
DoorData const doorData []
ObjectData const creatureData []
ObjectData const gameObjectData []
const Position sapphironEntryTP = { 3498.300049f, -5349.490234f, 144.968002f, 1.3698910f }
Function Documentation
AddSC_instance_naxxramas()
void AddSC_instance_naxxramas ()
{
    new instance_naxxramas();
    new boss_naxxramas_misc();
    new at_naxxramas_hub_portal();
}
Referenced by AddNorthrendScripts().
GetEruptionSection()
uint8 GetEruptionSection (float x, float y) inline
{
    y -= HeiganPos[1];
    if (y < 1.0f)
        return 0;
    x -= HeiganPos[0];
    if (x > -1.0f)
        return 3;
    float slope = y / x;
    for (uint32 i = 0; i < 3; ++i)
    {
        if (slope > HeiganEruptionSlope[i])
            return i;
    }
    return 3;
}
References HeiganEruptionSlope, and HeiganPos.
Referenced by instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), and instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectRemove().
Variable Documentation
creatureData
ObjectData const creatureData[]
Initial value:
=
{
    { NPC_RAZUVIOUS, DATA_RAZUVIOUS },
    { 0,             0              }
}
Referenced by instance_naxxramas::instance_naxxramas_InstanceMapScript::instance_naxxramas_InstanceMapScript().
doorData
DoorData const doorData[]
Initial value:
=
{
    { GO_ANUB_GATE,     BOSS_ANUB,       DOOR_TYPE_ROOM    },
    { 0,                0,               DOOR_TYPE_ROOM    },
}
Referenced by instance_naxxramas::instance_naxxramas_InstanceMapScript::instance_naxxramas_InstanceMapScript().
gameObjectData
ObjectData const gameObjectData[]
Initial value:
=
{
    { 0,             0              }
}
Referenced by instance_naxxramas::instance_naxxramas_InstanceMapScript::instance_naxxramas_InstanceMapScript().
HeiganEruptionSlope
const float HeiganEruptionSlope[3]
Initial value:
=
{
    (-3685 - HeiganPos[1]) / (2724 - HeiganPos[0]),
    (-3647 - HeiganPos[1]) / (2749 - HeiganPos[0]),
    (-3637 - HeiganPos[1]) / (2771 - HeiganPos[0]),
}
Referenced by GetEruptionSection().
HeiganPos
const float HeiganPos[2] = {2796, -3707}
Referenced by GetEruptionSection().
sapphironEntryTP
const Position sapphironEntryTP = { 3498.300049f, -5349.490234f, 144.968002f, 1.3698910f }
Referenced by at_naxxramas_hub_portal::OnTrigger().