AzerothCore: ActionButton Struct Reference
ActionButton Struct Reference
#include "Player.h"
Public Member Functions
ActionButton ()=default
ActionButtonType GetType () const
uint32 GetAction () const
void SetActionAndType (uint32 action, ActionButtonType type)
Public Attributes
uint32 packedData {0}
ActionButtonUpdateState uState {ACTIONBUTTON_NEW}
Detailed Description
Constructor & Destructor Documentation
ActionButton()
ActionButton::ActionButton () default
Member Function Documentation
GetAction()
uint32 ActionButton::GetAction () const inline
{ return ACTION_BUTTON_ACTION(packedData); }
References ACTION_BUTTON_ACTION, and packedData.
Referenced by Spell::EffectCastButtons().
GetType()
ActionButtonType ActionButton::GetType () const inline
{ return ActionButtonType(ACTION_BUTTON_TYPE(packedData)); }
References ACTION_BUTTON_TYPE, and packedData.
Referenced by Spell::EffectCastButtons().
SetActionAndType()
void ActionButton::SetActionAndType (uint32 action, ActionButtonType type) inline
    {
        uint32 newData = action | (uint32(type) << 24);
        if (newData != packedData || uState == ACTIONBUTTON_DELETED)
        {
            packedData = newData;
            if (uState != ACTIONBUTTON_NEW)
                uState = ACTIONBUTTON_CHANGED;
        }
    }
References ACTIONBUTTON_CHANGED, ACTIONBUTTON_DELETED, ACTIONBUTTON_NEW, packedData, and uState.
Referenced by Player::addActionButton().
Member Data Documentation
packedData
uint32 ActionButton::packedData {0}
Referenced by GetAction(), GetType(), and SetActionAndType().
uState
ActionButtonUpdateState ActionButton::uState {ACTIONBUTTON_NEW}
Referenced by SetActionAndType().