AzerothCore: npc_hor_leader::npc_hor_leaderAI Struct Reference
npc_hor_leader::npc_hor_leaderAI Struct Reference
Public Member Functions
npc_hor_leaderAI (Creature *creature)
void Reset () override
void DoAction (int32 actionId) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
bool first
bool shortver
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_hor_leaderAI()
npc_hor_leader::npc_hor_leaderAI::npc_hor_leaderAI (Creature * creature) inline
                                             : NullCreatureAI(creature)
        {
            pInstance = me->GetInstanceScript();
            if (!pInstance)
                me->IsAIEnabled = false;
            first = (pInstance && !pInstance->GetData(DATA_INTRO));
        }
References DATA_INTRO, first, ZoneScript::GetData(), WorldObject::GetInstanceScript(), Unit::IsAIEnabled, CreatureAI::me, and pInstance.
Member Function Documentation
DoAction()
void npc_hor_leader::npc_hor_leaderAI::DoAction (int32 actionId) inline override virtual
Reimplemented from UnitAI.
        {
            switch (actionId)
            {
                case ACTION_START_INTRO:
                    events.ScheduleEvent(EVENT_START_INTRO, 0ms);
                    break;
                case ACTION_SKIP_INTRO:
                    events.ScheduleEvent(EVENT_SKIP_INTRO, 0ms);
                    break;
            }
        }
References ACTION_SKIP_INTRO, ACTION_START_INTRO, EVENT_SKIP_INTRO, and EVENT_START_INTRO.
Reset()
void npc_hor_leader::npc_hor_leaderAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            shortver = false;
            events.Reset();
            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
            if (first)
            {
                first = false;
                events.ScheduleEvent(EVENT_PRE_INTRO_1, 10s);
                events.ScheduleEvent(EVENT_PRE_INTRO_2, 11s);
                events.ScheduleEvent(EVENT_EMOTE_LEADER_1, 16s);
                events.ScheduleEvent(EVENT_TALK_LEADER_1, 16s);
                events.ScheduleEvent(EVENT_PRE_INTRO_3, 19s);
            }
        }
References EMOTE_ONESHOT_NONE, EVENT_EMOTE_LEADER_1, EVENT_PRE_INTRO_1, EVENT_PRE_INTRO_2, EVENT_PRE_INTRO_3, EVENT_TALK_LEADER_1, first, CreatureAI::me, Unit::SetUInt32Value(), shortver, and UNIT_NPC_EMOTESTATE.
UpdateAI()
void npc_hor_leader::npc_hor_leaderAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
            case EVENT_PRE_INTRO_1:
                if (pInstance)
                {
                    me->SetSheath(SHEATH_STATE_MELEE);
                    me->SetVisible(true);
                }
                break;
            case EVENT_PRE_INTRO_2:
                if (me->GetEntry() == NPC_JAINA_PART1)
                {
                    Talk(SAY_JAINA_INTRO_1);
                }
                    me->GetMotionMaster()->MovePoint(0, SpawnPos);
                break;
            case EVENT_TALK_LEADER_1:
                me->SetSheath(SHEATH_STATE_UNARMED);
                Talk(me->GetEntry() == NPC_JAINA_PART1 ? SAY_JAINA_INTRO_2 : SAY_SYLVANAS_INTRO_1);
                break;
            case EVENT_EMOTE_LEADER_1:
                me->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
                break;
            case EVENT_PRE_INTRO_3:
                me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                me->SetSheath(SHEATH_STATE_MELEE);
                break;
            case EVENT_START_INTRO:
                shortver = false;
                me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                me->GetMotionMaster()->MovePoint(0, MoveThronePos);
                if (Creature* pLoralen = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                {
                    pLoralen->LoadEquipment(true);
                    pLoralen->SetVisible(true);
                    pLoralen->SetWalk(true);
                    pLoralen->GetMotionMaster()->MovePoint(0, LoralenMidleFollowPos);
                }
                // Begining of intro is differents between factions as the speech sequence and timers are differents.
                if (me->GetEntry() == NPC_JAINA_PART1)
                {
                    events.ScheduleEvent(EVENT_INTRO_A2_1, 10s);
                }
                else
                {
                    events.ScheduleEvent(EVENT_INTRO_H2_2, 9s);
                    events.ScheduleEvent(EVENT_LORALEN_MOVE_1, 24s);
                    events.ScheduleEvent(EVENT_LORALEN_MOVE_2, 32s);
                }
                break;
            case EVENT_SKIP_INTRO:
                shortver = true;
                me->SetUInt32Value(UNIT_NPC_EMOTESTATE, (me->GetEntry() == NPC_JAINA_PART1 ? EMOTE_STATE_READY2H : EMOTE_STATE_READY1H));
                me->GetMotionMaster()->MovePoint(0, MoveThronePos);
                if (Creature* pLoralen = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                {
                    pLoralen->GetMotionMaster()->MovePoint(0, LoralenFollowPos);
                }
                events.ScheduleEvent(EVENT_INTRO_LK_1, 0ms);
                break;
                // A2 Intro Events
            case EVENT_INTRO_A2_1:
                Talk(SAY_JAINA_INTRO_3);
                events.ScheduleEvent(EVENT_INTRO_A2_2, 5s);
                break;
            case EVENT_INTRO_A2_2:
                Talk(SAY_JAINA_INTRO_4);
                events.ScheduleEvent(EVENT_INTRO_A2_3, 10s);
                break;
            case EVENT_INTRO_A2_3:
                pInstance->HandleGameObject(pInstance->GetGuidData(GO_FROSTMOURNE), true);
                me->CastSpell(me, SPELL_FROSTMOURNE_SPAWN_SOUND, true);
                //me->CastSpell(me, SPELL_ARCANE_CAST_VISUAL, false);// the sniff is missing from the alliance
                events.ScheduleEvent(EVENT_INTRO_A2_4, 10s);
                break;
            case EVENT_INTRO_A2_4:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                    pUther->SetVisible(true);
                    if (Aura* a = pUther->AddAura(SPELL_SHADOWMOURNE_VISUAL, pUther))
                        a->SetDuration(8000);
                }
                events.ScheduleEvent(EVENT_INTRO_A2_5, 2s);
                break;
            case EVENT_INTRO_A2_5:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->AI()->Talk(SAY_UTHER_INTRO_A2_1);
                    events.ScheduleEvent(EVENT_INTRO_A2_6, 3s);
                }
                break;
            case EVENT_INTRO_A2_6:
                Talk(SAY_JAINA_INTRO_5);
                events.ScheduleEvent(EVENT_INTRO_A2_7, 6s);
                break;
            case EVENT_INTRO_A2_7:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->AI()->Talk(SAY_UTHER_INTRO_A2_2);
                }
                events.ScheduleEvent(EVENT_INTRO_A2_8, 6500ms);
                break;
            case EVENT_INTRO_A2_8:
                Talk(SAY_JAINA_INTRO_6);
                events.ScheduleEvent(EVENT_INTRO_A2_9, 2s);
                break;
            case EVENT_INTRO_A2_9:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->AI()->Talk(SAY_UTHER_INTRO_A2_3);
                }
                events.ScheduleEvent(EVENT_INTRO_A2_10, 9s);
                break;
            case EVENT_INTRO_A2_10:
                Talk(SAY_JAINA_INTRO_7);
                events.ScheduleEvent(EVENT_INTRO_A2_11, 5s);
                break;
            case EVENT_INTRO_A2_11:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->AI()->Talk(SAY_UTHER_INTRO_A2_4);
                }
                events.ScheduleEvent(EVENT_INTRO_A2_12, 11s);
                break;
            case EVENT_INTRO_A2_12:
                Talk(SAY_JAINA_INTRO_8);
                events.ScheduleEvent(EVENT_INTRO_A2_13, 4s);
                break;
            case EVENT_INTRO_A2_13:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->AI()->Talk(SAY_UTHER_INTRO_A2_5);
                }
                events.ScheduleEvent(EVENT_INTRO_A2_14, 12s + 500ms);
                break;
            case EVENT_INTRO_A2_14:
                Talk(SAY_JAINA_INTRO_9);
                events.ScheduleEvent(EVENT_INTRO_A2_15, 10s);
                break;
            case EVENT_INTRO_A2_15:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->AI()->Talk(SAY_UTHER_INTRO_A2_6);
                }
                events.ScheduleEvent(EVENT_INTRO_A2_16, 24s);
                break;
            case EVENT_INTRO_A2_16:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                    pUther->AI()->Talk(SAY_UTHER_INTRO_A2_7);
                events.ScheduleEvent(EVENT_INTRO_A2_17, 4s);
                break;
            case EVENT_INTRO_A2_17:
                Talk(SAY_JAINA_INTRO_10);
                events.ScheduleEvent(EVENT_INTRO_A2_18, 2s);
                break;
            case EVENT_INTRO_A2_18:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    pUther->AI()->Talk(SAY_UTHER_INTRO_A2_8);
                }
                events.ScheduleEvent(EVENT_INTRO_A2_19, 11s);
                break;
            case EVENT_INTRO_A2_19:
                Talk(SAY_JAINA_INTRO_11);
                events.ScheduleEvent(EVENT_INTRO_LK_1, 2s);
                break;
                // H2 Intro Events
            case EVENT_LORALEN_MOVE_1:
                if (Creature* pLoralen = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                {
                    pLoralen->GetMotionMaster()->MovePoint(0, LoralenFollowPos);
                }
                break;
            case EVENT_LORALEN_MOVE_2:
                if (Creature* pLoralen = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                {
                    pLoralen->HandleEmoteCommand(EMOTE_ONESHOT_KNEEL);
                }
                break;
            case EVENT_INTRO_H2_2:
                me->SetSheath(SHEATH_STATE_UNARMED);
                me->HandleEmoteCommand(EMOTE_ONESHOT_QUESTION);
                Talk(SAY_SYLVANAS_INTRO_2);
                events.ScheduleEvent(EVENT_INTRO_H2_2_1, 7s + 500ms);
                break;
            case EVENT_INTRO_H2_2_1:
                me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                Talk(SAY_SYLVANAS_INTRO_3);
                events.ScheduleEvent(EVENT_INTRO_H2_3, 2s);
                break;
            case EVENT_INTRO_H2_3:
                me->CastSpell(me, SPELL_SUMMON_SOULS, false);
                events.ScheduleEvent(EVENT_INTRO_H2_3_1, 5s);
                break;
            case EVENT_INTRO_H2_3_1:
                me->CastSpell(me, SPELL_FROSTMOURNE_SPAWN_SOUND, false);
                pInstance->HandleGameObject(pInstance->GetGuidData(GO_FROSTMOURNE), true);
                events.ScheduleEvent(EVENT_INTRO_H2_3_2, 3s);
                break;
            case EVENT_INTRO_H2_3_2:
                me->RemoveAurasDueToSpell(SPELL_SUMMON_SOULS);
                events.ScheduleEvent(EVENT_INTRO_H2_4, 2s);
                break;
            case EVENT_INTRO_H2_4:
                if (Creature* pUther = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->SetVisible(true);
                    if (Aura* a = pUther->AddAura(SPELL_SHADOWMOURNE_VISUAL, pUther))
                    {
                        a->SetDuration(8000);
                    }
                }
                events.ScheduleEvent(EVENT_INTRO_H2_5, 7s);
                break;
            case EVENT_INTRO_H2_5:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    pUther->AI()->Talk(SAY_UTHER_INTRO_H2_1);
                }
                events.ScheduleEvent(EVENT_INTRO_H2_6, 11s);
                break;
            case EVENT_INTRO_H2_6:
                me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                Talk(SAY_SYLVANAS_INTRO_4);
                events.ScheduleEvent(EVENT_INTRO_H2_7, 2s + 500ms);
                break;
            case EVENT_INTRO_H2_7:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    pUther->AI()->Talk(SAY_UTHER_INTRO_H2_2);
                }
                events.ScheduleEvent(EVENT_INTRO_H2_8, 9s);//
                break;
            case EVENT_INTRO_H2_8:
                me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                Talk(SAY_SYLVANAS_INTRO_5);
                events.ScheduleEvent(EVENT_INTRO_H2_9, 5s);
                break;
            case EVENT_INTRO_H2_9:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    pUther->AI()->Talk(SAY_UTHER_INTRO_H2_3);
                }
                events.ScheduleEvent(EVENT_INTRO_H2_10, 20s);
                break;
            case EVENT_INTRO_H2_10:
                me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                Talk(SAY_SYLVANAS_INTRO_6);
                events.ScheduleEvent(EVENT_INTRO_H2_11, 3s);
                break;
            case EVENT_INTRO_H2_11:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    pUther->AI()->Talk(SAY_UTHER_INTRO_H2_4);
                }
                events.ScheduleEvent(EVENT_INTRO_H2_12, 21s + 500ms);
                break;
            case EVENT_INTRO_H2_12:
                me->HandleEmoteCommand(EMOTE_ONESHOT_QUESTION);
                Talk(SAY_SYLVANAS_INTRO_7);
                events.ScheduleEvent(EVENT_INTRO_H2_13, 3s + 500ms);
                break;
            case EVENT_INTRO_H2_13:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    pUther->AI()->Talk(SAY_UTHER_INTRO_H2_5);
                }
                events.ScheduleEvent(EVENT_INTRO_H2_14, 12s + 500ms);
                break;
            case EVENT_INTRO_H2_14:
                if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                {
                    pUther->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    pUther->AI()->Talk(SAY_UTHER_INTRO_H2_6);
                }
                events.ScheduleEvent(EVENT_INTRO_H2_15, 8s);
                break;
            case EVENT_INTRO_H2_15:
                me->HandleEmoteCommand(EMOTE_ONESHOT_QUESTION);
                Talk(SAY_SYLVANAS_INTRO_8);
                events.ScheduleEvent(EVENT_INTRO_LK_1, 2s);
                break;
                // Remaining Intro Events common for both faction
            case EVENT_INTRO_LK_1:
                if (Creature* pLichKing = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                {
                    pInstance->HandleGameObject(pInstance->GetGuidData(GO_ARTHAS_DOOR), true);
                    pLichKing->SetVisible(true);
                    pLichKing->GetMotionMaster()->MovePoint(0, LichKingMoveMidlelThronePos, false);
                }
                if (!shortver)
                    if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                    {
                        pUther->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
                        if (me->GetEntry() == NPC_JAINA_PART1)
                            pUther->AI()->Talk(SAY_UTHER_INTRO_A2_9);
                        else
                            pUther->AI()->Talk(SAY_UTHER_INTRO_H2_7);
                    }
                events.ScheduleEvent(EVENT_INTRO_LK_1_1, 9s);
                events.ScheduleEvent(EVENT_INTRO_LK_1_2, 3s);
                events.ScheduleEvent(EVENT_INTRO_LK_1_3, 6s);
                events.ScheduleEvent(EVENT_INTRO_LK_2, 12s);
                break;
            case EVENT_INTRO_LK_1_1:
                if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                {
                    pLichKing->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
                    pLichKing->AI()->Talk(SAY_LK_INTRO_1);
                }
                break;
            case EVENT_INTRO_LK_1_2:
                if (!shortver)
                    if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                    {
                        pUther->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_COWER);
                        pUther->SetFacingTo(0.89f);
                    }
                break;
            case EVENT_INTRO_LK_1_3:
                pInstance->HandleGameObject(pInstance->GetGuidData(GO_ARTHAS_DOOR), false);
                break;
            case EVENT_INTRO_LK_2:
                if (!shortver)
                    if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                    {
                        pLichKing->SetVisible(true);
                        pLichKing->GetMotionMaster()->MovePoint(0, LichKingMoveThronePos, false);
                    }
                events.ScheduleEvent(EVENT_INTRO_LK_2_1, 1s);
                break;
            case EVENT_INTRO_LK_2_1:
                if (!shortver)
                    if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                    {
                        pUther->SendPlaySpellVisual(SPELL_UTHER_DESPAWN);
                        pUther->CastSpell(pUther, SPELL_UTHER_DESPAWN, true);
                    }
                events.ScheduleEvent(EVENT_INTRO_LK_3, 2s);
                break;
            case EVENT_INTRO_LK_3:
                if (!shortver)
                    if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                    {
                        pUther->SetVisible(false);
                    }
                events.ScheduleEvent(EVENT_INTRO_LK_4, 6s);
                break;
            case EVENT_INTRO_LK_4:
                if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                {
                    pLichKing->HandleEmoteCommand(EMOTE_ONESHOT_QUESTION);
                    pLichKing->AI()->Talk(SAY_LK_INTRO_2);
                }
                events.ScheduleEvent(EVENT_INTRO_LK_4_2, 10s);
                break;
            case EVENT_INTRO_LK_4_2:
                if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                {
                    pLichKing->LoadEquipment(1, true);
                    pLichKing->SendMovementFlagUpdate();
                    pLichKing->CastSpell(pLichKing, SPELL_FROSTMOURNE_EQUIP, false);
                    pInstance->HandleGameObject(pInstance->GetGuidData(GO_FROSTMOURNE), false);
                    events.ScheduleEvent(EVENT_INTRO_LK_4_3, 1750);
                }
                events.ScheduleEvent(EVENT_INTRO_LK_5, 6s);
                break;
            case EVENT_INTRO_LK_4_3:
                if (GameObject* go = pInstance->instance->GetGameObject(pInstance->GetGuidData(GO_FROSTMOURNE)))
                    go->SetPhaseMask(2, true);
                break;
            case EVENT_INTRO_LK_5:
                if (Creature* pFalric = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_FALRIC)))
                {
                    pFalric->UpdatePosition(5274.9f, 2039.2f, 709.319f, 5.4619f, true);
                    pFalric->StopMovingOnCurrentPos();
                    pFalric->SetVisible(true);
                    if (pFalric->IsAlive())
                    {
                        pFalric->GetMotionMaster()->MovePoint(0, FalricMovePos);
                        if (Aura* a = pFalric->AddAura(SPELL_SHADOWMOURNE_VISUAL, pFalric))
                            a->SetDuration(8000);
                    }
                }
                if (Creature* pMarwyn = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_MARWYN)))
                {
                    pMarwyn->UpdatePosition(5343.77f, 1973.86f, 709.319f, 2.35173f, true);
                    pMarwyn->StopMovingOnCurrentPos();
                    pMarwyn->SetVisible(true);
                    if (pMarwyn->IsAlive())
                    {
                        pMarwyn->GetMotionMaster()->MovePoint(0, MarwynMovePos);
                        if (Aura* a = pMarwyn->AddAura(SPELL_SHADOWMOURNE_VISUAL, pMarwyn))
                            a->SetDuration(8000);
                    }
                }
                events.ScheduleEvent(EVENT_INTRO_LK_5_1, 0s);
                events.ScheduleEvent(EVENT_INTRO_LK_5_2, 7s);
                events.ScheduleEvent(EVENT_INTRO_LK_5_3, 0s);
                events.ScheduleEvent(EVENT_INTRO_LK_6, 11s);
                break;
            case EVENT_INTRO_LK_5_1:
                if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                {
                    pLichKing->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    pLichKing->AI()->Talk(SAY_LK_INTRO_3);
                }
                break;
            case EVENT_INTRO_LK_5_2:
                if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                {
                    pLichKing->GetMotionMaster()->MovePoint(0, LichKingMoveAwayPos, false);
                }
                break;
            case EVENT_INTRO_LK_5_3:
                me->SetSpeed(MOVE_RUN, 1.6);
                me->SetSheath(SHEATH_STATE_MELEE);
                me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_READY1H);
                if (Creature* pLoralen = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                {
                    pLoralen->SetSheath(SHEATH_STATE_MELEE);
                    pLoralen->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_READY1H);
                    pLoralen->SetWalk(false);
                    pLoralen->LoadEquipment(true);
                }
                break;
            case EVENT_INTRO_LK_6:
                if (Creature* pFalric = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_FALRIC)))
                {
                    pFalric->HandleEmoteCommand(EMOTE_ONESHOT_BOW);
                    pFalric->AI()->Talk(SAY_FALRIC_INTRO_1);
                }
                events.ScheduleEvent(EVENT_INTRO_LK_7, 2s);
                break;
            case EVENT_INTRO_LK_7:
                if (Creature* pMarwyn = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_MARWYN)))
                {
                    pMarwyn->HandleEmoteCommand(EMOTE_ONESHOT_BOW);
                    pMarwyn->AI()->Talk(SAY_MARWYN_INTRO_1);
                }
                events.ScheduleEvent(EVENT_INTRO_LK_8, 3s);
                break;
            case EVENT_INTRO_LK_8:
                if (Creature* pFalric = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_FALRIC)))
                {
                    pFalric->AI()->Talk(SAY_FALRIC_INTRO_2);
                    pInstance->SetData(ACTION_SHOW_TRASH, 1);
                    pInstance->HandleGameObject(pInstance->GetGuidData(GO_ARTHAS_DOOR), true);
                }
                events.ScheduleEvent(EVENT_INTRO_LK_9, 6s);
                break;
            case EVENT_INTRO_LK_9:
                if (me->GetEntry() == NPC_JAINA_PART1)
                {
                    Talk(SAY_JAINA_INTRO_END);
                }
                else
                {
                    Talk(SAY_SYLVANAS_INTRO_END);
                    me->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
                    me->GetMotionMaster()->MovePoint(0, LichKingMoveAwayPos, false);
                }
                if (Creature* pLoralen = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                {
                    pLoralen->GetMotionMaster()->MovePoint(0, LoralenFollowLk1, false);
                }
                events.ScheduleEvent(EVENT_INTRO_LK_10, 1s + 500ms);
                break;
            case EVENT_INTRO_LK_10:
                if (Creature* pLoralen = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                {
                    pLoralen->GetMotionMaster()->MovePoint(0, LoralenFollowLk2, false);
                }
                events.ScheduleEvent(EVENT_INTRO_LK_11, 2s);
                break;
            case EVENT_INTRO_LK_11:
                if (Creature* pLoralen = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                {
                    pLoralen->GetMotionMaster()->MovePoint(0, LoralenFollowLk3, false);
                }
                events.ScheduleEvent(EVENT_INTRO_LK_12, 5s + 500ms);
                break;
            case EVENT_INTRO_LK_12:
                if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                {
                    pLichKing->SetVisible(false);
                }
                if (Creature* pLoralen = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                {
                    pLoralen->GetMotionMaster()->MovePoint(0, LoralenFollowLkFinal, false);
                }
                events.ScheduleEvent(EVENT_INTRO_LK_13, 2s);
                    break;
                case EVENT_INTRO_LK_13:
                    me->SetVisible(false);
                    events.ScheduleEvent(EVENT_INTRO_END, 2s +500ms);
                    break;
                case EVENT_INTRO_END:
                    pInstance->HandleGameObject(pInstance->GetGuidData(GO_ARTHAS_DOOR), false);
                    pInstance->HandleGameObject(pInstance->GetGuidData(GO_FRONT_DOOR), false);
                    events.ScheduleEvent(EVENT_INTRO_END_SET, 3s);
                    break;
                case EVENT_INTRO_END_SET:
                    if (Creature* pLoralen = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                    {
                        pLoralen->UpdatePosition(5369.71289f, 2083.6330f, 707.695129f, 0.188739f, true);
                        pLoralen->StopMovingOnCurrentPos();
                        pLoralen->SetVisible(true);
                        pLoralen->KillSelf(pLoralen);
                    }
                    pInstance->SetData(DATA_INTRO, DONE);
                    break;
            }
        }
References ACTION_SHOW_TRASH, Unit::CastSpell(), DATA_FALRIC, DATA_INTRO, DATA_MARWYN, DONE, EMOTE_ONESHOT_BOW, EMOTE_ONESHOT_EXCLAMATION, EMOTE_ONESHOT_KNEEL, EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_QUESTION, EMOTE_ONESHOT_READY1H, EMOTE_ONESHOT_TALK, EMOTE_STATE_COWER, EMOTE_STATE_READY1H, EMOTE_STATE_READY2H, EVENT_EMOTE_LEADER_1, EVENT_INTRO_A2_1, EVENT_INTRO_A2_10, EVENT_INTRO_A2_11, EVENT_INTRO_A2_12, EVENT_INTRO_A2_13, EVENT_INTRO_A2_14, EVENT_INTRO_A2_15, EVENT_INTRO_A2_16, EVENT_INTRO_A2_17, EVENT_INTRO_A2_18, EVENT_INTRO_A2_19, EVENT_INTRO_A2_2, EVENT_INTRO_A2_3, EVENT_INTRO_A2_4, EVENT_INTRO_A2_5, EVENT_INTRO_A2_6, EVENT_INTRO_A2_7, EVENT_INTRO_A2_8, EVENT_INTRO_A2_9, EVENT_INTRO_END, EVENT_INTRO_END_SET, EVENT_INTRO_H2_10, EVENT_INTRO_H2_11, EVENT_INTRO_H2_12, EVENT_INTRO_H2_13, EVENT_INTRO_H2_14, EVENT_INTRO_H2_15, EVENT_INTRO_H2_2, EVENT_INTRO_H2_2_1, EVENT_INTRO_H2_3, EVENT_INTRO_H2_3_1, EVENT_INTRO_H2_3_2, EVENT_INTRO_H2_4, EVENT_INTRO_H2_5, EVENT_INTRO_H2_6, EVENT_INTRO_H2_7, EVENT_INTRO_H2_8, EVENT_INTRO_H2_9, EVENT_INTRO_LK_1, EVENT_INTRO_LK_10, EVENT_INTRO_LK_11, EVENT_INTRO_LK_12, EVENT_INTRO_LK_13, EVENT_INTRO_LK_1_1, EVENT_INTRO_LK_1_2, EVENT_INTRO_LK_1_3, EVENT_INTRO_LK_2, EVENT_INTRO_LK_2_1, EVENT_INTRO_LK_3, EVENT_INTRO_LK_4, EVENT_INTRO_LK_4_2, EVENT_INTRO_LK_4_3, EVENT_INTRO_LK_5, EVENT_INTRO_LK_5_1, EVENT_INTRO_LK_5_2, EVENT_INTRO_LK_5_3, EVENT_INTRO_LK_6, EVENT_INTRO_LK_7, EVENT_INTRO_LK_8, EVENT_INTRO_LK_9, EVENT_LORALEN_MOVE_1, EVENT_LORALEN_MOVE_2, EVENT_PRE_INTRO_1, EVENT_PRE_INTRO_2, EVENT_PRE_INTRO_3, EVENT_SKIP_INTRO, EVENT_START_INTRO, EVENT_TALK_LEADER_1, FalricMovePos, Map::GetCreature(), ObjectAccessor::GetCreature(), Object::GetEntry(), Map::GetGameObject(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), GO_ARTHAS_DOOR, GO_FRONT_DOOR, GO_FROSTMOURNE, Unit::HandleEmoteCommand(), InstanceScript::HandleGameObject(), InstanceScript::instance, LichKingMoveAwayPos, LichKingMoveMidlelThronePos, LichKingMoveThronePos, LoralenFollowLk1, LoralenFollowLk2, LoralenFollowLk3, LoralenFollowLkFinal, LoralenFollowPos, LoralenMidleFollowPos, MarwynMovePos, CreatureAI::me, MOVE_RUN, MotionMaster::MovePoint(), MoveThronePos, NPC_DARK_RANGER_LORALEN, NPC_JAINA_PART1, NPC_LICH_KING_EVENT, NPC_UTHER, pInstance, Unit::RemoveAurasDueToSpell(), SAY_FALRIC_INTRO_1, SAY_FALRIC_INTRO_2, SAY_JAINA_INTRO_1, SAY_JAINA_INTRO_10, SAY_JAINA_INTRO_11, SAY_JAINA_INTRO_2, SAY_JAINA_INTRO_3, SAY_JAINA_INTRO_4, SAY_JAINA_INTRO_5, SAY_JAINA_INTRO_6, SAY_JAINA_INTRO_7, SAY_JAINA_INTRO_8, SAY_JAINA_INTRO_9, SAY_JAINA_INTRO_END, SAY_LK_INTRO_1, SAY_LK_INTRO_2, SAY_LK_INTRO_3, SAY_MARWYN_INTRO_1, SAY_SYLVANAS_INTRO_1, SAY_SYLVANAS_INTRO_2, SAY_SYLVANAS_INTRO_3, SAY_SYLVANAS_INTRO_4, SAY_SYLVANAS_INTRO_5, SAY_SYLVANAS_INTRO_6, SAY_SYLVANAS_INTRO_7, SAY_SYLVANAS_INTRO_8, SAY_SYLVANAS_INTRO_END, SAY_UTHER_INTRO_A2_1, SAY_UTHER_INTRO_A2_2, SAY_UTHER_INTRO_A2_3, SAY_UTHER_INTRO_A2_4, SAY_UTHER_INTRO_A2_5, SAY_UTHER_INTRO_A2_6, SAY_UTHER_INTRO_A2_7, SAY_UTHER_INTRO_A2_8, SAY_UTHER_INTRO_A2_9, SAY_UTHER_INTRO_H2_1, SAY_UTHER_INTRO_H2_2, SAY_UTHER_INTRO_H2_3, SAY_UTHER_INTRO_H2_4, SAY_UTHER_INTRO_H2_5, SAY_UTHER_INTRO_H2_6, SAY_UTHER_INTRO_H2_7, ZoneScript::SetData(), Unit::SetNpcFlag(), Unit::SetSheath(), Unit::SetSpeed(), Unit::SetUInt32Value(), Unit::SetVisible(), SHEATH_STATE_MELEE, SHEATH_STATE_UNARMED, shortver, SpawnPos, SPELL_FROSTMOURNE_EQUIP, SPELL_FROSTMOURNE_SPAWN_SOUND, SPELL_SHADOWMOURNE_VISUAL, SPELL_SUMMON_SOULS, SPELL_UTHER_DESPAWN, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAG_QUESTGIVER.
Member Data Documentation
events
EventMap npc_hor_leader::npc_hor_leaderAI::events
first
bool npc_hor_leader::npc_hor_leaderAI::first
Referenced by npc_hor_leaderAI(), and Reset().
pInstance
InstanceScript* npc_hor_leader::npc_hor_leaderAI::pInstance
Referenced by npc_hor_leaderAI(), and UpdateAI().
shortver
bool npc_hor_leader::npc_hor_leaderAI::shortver
Referenced by Reset(), and UpdateAI().