AzerothCore: npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI Struct Reference
npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI Struct Reference
Public Member Functions
npc_vaelastrasz_the_redAI (Creature *creature)
void IsSummonedBy (WorldObject *summoner) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
ObjectGuid _victorGUID
bool _combatEnabled
EventMap _events2
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_vaelastrasz_the_redAI()
npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::npc_vaelastrasz_the_redAI (Creature * creature) inline
: CreatureAI(creature) { }
Member Function Documentation
IsSummonedBy()
void npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::IsSummonedBy (WorldObject * summoner) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!summoner)
            {
                return;
            }
            _combatEnabled = false;
            me->CastSpell(me, SPELL_VAELAN_SPAWNS, false);
            me->SetFacingToObject(summoner);
            Talk(SAY_RED_SUMMONED);
            if (Creature* victor = me->FindNearestCreature(NPC_LORD_VICTOR_NEFARIUS, 100.0f))
            {
                _victorGUID = victor->GetGUID();
            }
            events.ScheduleEvent(EVENT_RED_1_TALK_BEFORE_TRANSFORM, 3s);
        }
References _combatEnabled, _victorGUID, Unit::CastSpell(), EVENT_RED_1_TALK_BEFORE_TRANSFORM, WorldObject::FindNearestCreature(), CreatureAI::me, NPC_LORD_VICTOR_NEFARIUS, SAY_RED_SUMMONED, Unit::SetFacingToObject(), and SPELL_VAELAN_SPAWNS.
UpdateAI()
void npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
        {
            events.Update(diff);
            while (uint32 eventId = events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_RED_1_TALK_BEFORE_TRANSFORM:
                        Talk(SAY_RED_BEFORE_TRANSFORM);
                        events.ScheduleEvent(EVENT_RED_2_TRANSFORM, 2s);
                        break;
                    case EVENT_RED_2_TRANSFORM:
                        me->CastSpell(me, SPELL_TOUCH_OF_VAELASTRASZ, false);
                        me->SetEntry(NPC_VAELASTRASZ_UBRS);
                        me->SetDisplayId(MODEL_VAELASTRASZ_UBRS);
                        events.ScheduleEvent(EVENT_VAEL_TALK_SUMMON, 1s);
                        events.ScheduleEvent(EVENT_VAEL_1_START_COMBAT, 5s);
                        break;
                    case EVENT_VAEL_TALK_SUMMON:
                        Talk(SAY_VAEL_SUMMONED);
                        break;
                    case EVENT_VAEL_1_START_COMBAT:
                        _combatEnabled = true;
                        me->SetImmuneToNPC(false);
                        if (Creature* gyth = me->FindNearestCreature(NPC_GYTH, 100.0f, true))
{
                            me->AddThreat(gyth, 1000000.f);
                            me->AI()->AttackStart(gyth);
                        }
                        if (Creature* rend = me->FindNearestCreature(NPC_WARCHIEF_REND_BLACKHAND, 100.0f, true))
{
                            if (!rend->IsImmuneToNPC() && rend->isTargetableForAttack())
{
                                me->AddThreat(rend, 100000.f);
                                if (!me->FindNearestCreature(NPC_GYTH, 100.0f, true))
{
                                    me->AI()->AttackStart(rend);
                                }
                            }
                        }
                        _events2.ScheduleEvent(EVENT_FLAME_BREATH, 5s);
                        events.ScheduleEvent(EVENT_NEFARIUS_TALK_1, 500ms);
                        break;
                    case EVENT_NEFARIUS_TALK_1:
                        if (Creature* victor = ObjectAccessor::GetCreature(*me, _victorGUID))
{
                            victor->GetMotionMaster()->Clear(); // stop pacing
                            victor->GetMotionMaster()->MoveIdle();
                            victor->StopMovingOnCurrentPos();
                            victor->SetFacingToObject(me);
                            victor->AI()->Talk(SAY_NEFARIUS_15);
                        }
                        events.ScheduleEvent(EVENT_NEFARIUS_TALK_2, 6s);
                        break;
                    case EVENT_NEFARIUS_TALK_2:
                        if (Creature* victor = ObjectAccessor::GetCreature(*me, _victorGUID))
{
                            victor->SetFacingToObject(me);
                            victor->AI()->Talk(SAY_NEFARIUS_16);
                        }
                        events.ScheduleEvent(EVENT_NEFARIUS_TALK_3, 5s);
                        break;
                    case EVENT_NEFARIUS_TALK_3:
                        if (Creature* victor = ObjectAccessor::GetCreature(*me, _victorGUID))
{
                            victor->SetFacingToObject(me);
                            victor->AI()->Talk(SAY_NEFARIUS_17);
                        }
                        events.ScheduleEvent(EVENT_NEFARIUS_CORRUPTION, 5s);
                        break;
                    case EVENT_NEFARIUS_CORRUPTION:
                        _combatEnabled = false;
                        me->AttackStop();
                        me->RemoveAllAuras();
                        me->StopMovingOnCurrentPos();
                        me->SetFaction(FACTION_FRIENDLY);
                        if (Creature* victor = ObjectAccessor::GetCreature(*me, _victorGUID))
{
                            victor->SetFacingToObject(me);
                            victor->CastSpell(me, SPELL_NEFARIUS_CORRUPTION, TRIGGERED_CAST_DIRECTLY);
                        }
                        events.ScheduleEvent(EVENT_VAEL_2_TRANSFORM, 1s);
                        break;
                    case EVENT_VAEL_2_TRANSFORM:
                        Talk(SAY_VAEL_STOP_COMBAT);
                        me->SetDisplayId(MODEL_VAELASTRASZ_THE_RED);
                        events.ScheduleEvent(EVENT_VAEL_3_DESPAWN, 500ms);
                        break;
                    case EVENT_VAEL_3_DESPAWN:
                        DoCast(me, SPELL_VAELASTRASZ_SPAWN);
                        me->DespawnOrUnsummon(1500);
                        break;
                    default:
                        break;
                }
            }
            if (!_combatEnabled || !UpdateVictim() || me->HasUnitState(UNIT_STATE_CASTING))
            {
                return;
            }
            _events2.Update(diff);
            switch (_events2.ExecuteEvent())
            {
                case EVENT_FLAME_BREATH:
                    me->CastSpell(me, SPELL_FLAMEBREATH, false);
                    break;
                default:
                    break;
            }
            DoMeleeAttackIfReady();
            return;
        }
References _combatEnabled, _events2, _victorGUID, Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), Unit::AttackStop(), Unit::CastSpell(), Creature::DespawnOrUnsummon(), UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), EVENT_FLAME_BREATH, EVENT_NEFARIUS_CORRUPTION, EVENT_NEFARIUS_TALK_1, EVENT_NEFARIUS_TALK_2, EVENT_NEFARIUS_TALK_3, EVENT_RED_1_TALK_BEFORE_TRANSFORM, EVENT_RED_2_TRANSFORM, EVENT_VAEL_1_START_COMBAT, EVENT_VAEL_2_TRANSFORM, EVENT_VAEL_3_DESPAWN, EVENT_VAEL_TALK_SUMMON, EventMap::ExecuteEvent(), FACTION_FRIENDLY, WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), Unit::HasUnitState(), CreatureAI::me, MODEL_VAELASTRASZ_THE_RED, MODEL_VAELASTRASZ_UBRS, NPC_GYTH, NPC_VAELASTRASZ_UBRS, NPC_WARCHIEF_REND_BLACKHAND, Unit::RemoveAllAuras(), SAY_NEFARIUS_15, SAY_NEFARIUS_16, SAY_NEFARIUS_17, SAY_RED_BEFORE_TRANSFORM, SAY_VAEL_STOP_COMBAT, SAY_VAEL_SUMMONED, EventMap::ScheduleEvent(), Creature::SetDisplayId(), Object::SetEntry(), Unit::SetFaction(), Unit::SetImmuneToNPC(), SPELL_FLAMEBREATH, SPELL_NEFARIUS_CORRUPTION, SPELL_TOUCH_OF_VAELASTRASZ, SPELL_VAELASTRASZ_SPAWN, Unit::StopMovingOnCurrentPos(), TRIGGERED_CAST_DIRECTLY, UNIT_STATE_CASTING, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_combatEnabled
bool npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::_combatEnabled private
Referenced by IsSummonedBy(), and UpdateAI().
_events2
EventMap npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::_events2 private
Referenced by UpdateAI().
_victorGUID
ObjectGuid npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::_victorGUID private
Referenced by IsSummonedBy(), and UpdateAI().