AzerothCore: adt_MCNK Class Reference
adt_MCNK Class Reference
#include "adt.h"
Public Member Functions
bool prepareLoadedData ()
adt_MCVT * getMCVT ()
adt_MCLQ * getMCLQ ()
Public Attributes
uint32 size
uint32 flags
uint32 ix
uint32 iy
uint32 nLayers
uint32 nDoodadRefs
uint32 offsMCVT
uint32 offsMCNR
uint32 offsMCLY
uint32 offsMCRF
uint32 offsMCAL
uint32 sizeMCAL
uint32 offsMCSH
uint32 sizeMCSH
uint32 areaid
uint32 nMapObjRefs
uint32 holes
uint16 s [2]
uint32 data1
uint32 data2
uint32 data3
uint32 predTex
uint32 nEffectDoodad
uint32 offsMCSE
uint32 nSndEmitters
uint32 offsMCLQ
uint32 sizeMCLQ
float zpos
float xpos
float ypos
uint32 offsMCCV
uint32 props
uint32 effectId
uint32 fcc
char fcc_txt [4]
Private Attributes
union {
uint32 fcc
char fcc_txt [4]
};
Detailed Description
Member Function Documentation
getMCLQ()
adt_MCLQ * adt_MCNK::getMCLQ () inline
    {
        if (offsMCLQ)
            return (adt_MCLQ*)((uint8*)this + offsMCLQ);
        return nullptr;
    }
References offsMCLQ.
Referenced by ConvertADT(), and prepareLoadedData().
getMCVT()
adt_MCVT * adt_MCNK::getMCVT () inline
    {
        if (offsMCVT)
            return (adt_MCVT*)((uint8*)this + offsMCVT);
        return nullptr;
    }
References offsMCVT.
Referenced by ConvertADT(), and prepareLoadedData().
prepareLoadedData()
bool adt_MCNK::prepareLoadedData ()
{
    if (fcc != MCNKMagic.fcc)
        return false;
    // Check height map
    if (offsMCVT && !getMCVT()->prepareLoadedData())
        return false;
    // Check liquid data
    if (offsMCLQ && !getMCLQ()->prepareLoadedData())
        return false;
    return true;
}
References fcc, u_map_fcc::fcc, getMCLQ(), getMCVT(), MCNKMagic, offsMCLQ, offsMCVT, and prepareLoadedData().
Referenced by prepareLoadedData().
Member Data Documentation
union { ... } adt_MCNK::@381
areaid
uint32 adt_MCNK::areaid
Referenced by ConvertADT().
data1
uint32 adt_MCNK::data1
data2
uint32 adt_MCNK::data2
data3
uint32 adt_MCNK::data3
effectId
uint32 adt_MCNK::effectId
fcc
uint32 adt_MCNK::fcc
Referenced by prepareLoadedData().
fcc_txt
char adt_MCNK::fcc_txt[4]
flags
uint32 adt_MCNK::flags
Referenced by ConvertADT().
holes
uint32 adt_MCNK::holes
Referenced by ConvertADT().
ix
uint32 adt_MCNK::ix
iy
uint32 adt_MCNK::iy
nDoodadRefs
uint32 adt_MCNK::nDoodadRefs
nEffectDoodad
uint32 adt_MCNK::nEffectDoodad
nLayers
uint32 adt_MCNK::nLayers
nMapObjRefs
uint32 adt_MCNK::nMapObjRefs
nSndEmitters
uint32 adt_MCNK::nSndEmitters
offsMCAL
uint32 adt_MCNK::offsMCAL
offsMCCV
uint32 adt_MCNK::offsMCCV
offsMCLQ
uint32 adt_MCNK::offsMCLQ
Referenced by getMCLQ(), and prepareLoadedData().
offsMCLY
uint32 adt_MCNK::offsMCLY
offsMCNR
uint32 adt_MCNK::offsMCNR
offsMCRF
uint32 adt_MCNK::offsMCRF
offsMCSE
uint32 adt_MCNK::offsMCSE
offsMCSH
uint32 adt_MCNK::offsMCSH
offsMCVT
uint32 adt_MCNK::offsMCVT
Referenced by getMCVT(), and prepareLoadedData().
predTex
uint32 adt_MCNK::predTex
props
uint32 adt_MCNK::props
s
uint16 adt_MCNK::s[2]
size
uint32 adt_MCNK::size
sizeMCAL
uint32 adt_MCNK::sizeMCAL
sizeMCLQ
uint32 adt_MCNK::sizeMCLQ
Referenced by ConvertADT().
sizeMCSH
uint32 adt_MCNK::sizeMCSH
xpos
float adt_MCNK::xpos
ypos
float adt_MCNK::ypos
Referenced by ConvertADT().
zpos
float adt_MCNK::zpos