AzerothCore: npc_steward_of_time Class Reference
npc_steward_of_time Class Reference
Public Member Functions
npc_steward_of_time ()
bool OnQuestAccept (Player *player, Creature *, Quest const *quest) override
bool OnGossipSelect (Player *player, Creature *, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_steward_of_time()
npc_steward_of_time::npc_steward_of_time () inline
: CreatureScript("npc_steward_of_time") { }
Member Function Documentation
OnGossipHello()
bool npc_steward_of_time::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (creature->IsQuestGiver())
        {
            player->PrepareQuestMenu(creature->GetGUID());
        }
        if (player->GetQuestStatus(10279) == QUEST_STATUS_INCOMPLETE || player->GetQuestRewardStatus(10279))
        {
            AddGossipItemFor(player, 8072, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
            SendGossipMenuFor(player, 9978, creature->GetGUID());
        }
        else
        {
            SendGossipMenuFor(player, 9977, creature->GetGUID());
        }
        return true;
    }
References AddGossipItemFor(), Object::GetGUID(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, Unit::IsQuestGiver(), Player::PrepareQuestMenu(), QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_steward_of_time::OnGossipSelect (Player * player, Creature * , uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
    {
        ClearGossipMenuFor(player);
        if (action == GOSSIP_ACTION_INFO_DEF + 1)
            player->CastSpell(player, 34891, true);               //(Flight through Caverns)
        return true;
    }
References Unit::CastSpell(), ClearGossipMenuFor(), and GOSSIP_ACTION_INFO_DEF.
OnQuestAccept()
bool npc_steward_of_time::OnQuestAccept (Player * player, Creature * , Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
    {
        if (quest->GetQuestId() == 10279)                      //Quest: To The Master's Lair
            player->CastSpell(player, 34891, true);               //(Flight through Caverns)
        return false;
    }
References Unit::CastSpell(), and Quest::GetQuestId().