var classspell__illidan__parasitic__shadowfiend__trigger_1_1spell__illidan__parasitic__shadowfiend__trigger___spell_script =
[
    [ "HandleScriptEffect", "dc/d0f/classspell__illidan__parasitic__shadowfiend__trigger_1_1spell__illidan__parasitic__shadowfiend__trigger___spell_script.html#aa962c61dc8d8c70488a049ee68f28f3d", null ],
    [ "PrepareSpellScript", "dc/d0f/classspell__illidan__parasitic__shadowfiend__trigger_1_1spell__illidan__parasitic__shadowfiend__trigger___spell_script.html#a30d953f2abce98fd1c6c20d9b68bad22", null ],
    [ "Register", "dc/d0f/classspell__illidan__parasitic__shadowfiend__trigger_1_1spell__illidan__parasitic__shadowfiend__trigger___spell_script.html#a1a8373a27d9b868392308c1bedb7c403", null ]
];