AzerothCore: boss_ragnaros::boss_ragnarosAI Struct Reference
boss_ragnaros::boss_ragnarosAI Struct Reference
Public Member Functions
boss_ragnarosAI (Creature *creature)
void Reset () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void DoAction (int32 action) override
void JustSummoned (Creature *summon) override
void SetGUID (ObjectGuid guid, int32 index) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void AttackStart (Unit *target) override
void EnterEvadeMode (EvadeReason why) override
bool CanAIAttack (Unit const *victim) const override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Member Functions
void HandleEmerge ()
void ScheduleCombatEvents ()
bool IsVictimWithinMeleeRange () const
Private Attributes
EventMap extraEvents
bool _isIntroDone
bool _hasYelledMagmaBurst
bool _processingMagmaBurst
bool _hasSubmergedOnce
bool _isKnockbackEmoteAllowed
GuidSet _lavaBurstGUIDS
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_ragnarosAI()
boss_ragnaros::boss_ragnarosAI::boss_ragnarosAI (Creature * creature) inline
                                            : BossAI(creature, DATA_RAGNAROS),
            _isIntroDone(false),
            _hasYelledMagmaBurst(false),
            _processingMagmaBurst(false),
            _hasSubmergedOnce(false),
            _isKnockbackEmoteAllowed(true)
        {
        }
Member Function Documentation
AttackStart()
void boss_ragnaros::boss_ragnarosAI::AttackStart (Unit * target) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (target && me->Attack(target, true))
            {
                DoStartNoMovement(target);
            }
        }
References Unit::Attack(), ScriptedAI::DoStartNoMovement(), and ScriptedAI::me.
Referenced by HandleEmerge().
CanAIAttack()
bool boss_ragnaros::boss_ragnarosAI::CanAIAttack (Unit const * victim) const inline override virtual
Reimplemented from UnitAI.
        {
            return me->IsWithinMeleeRange(victim);
        }
References Unit::IsWithinMeleeRange(), and ScriptedAI::me.
DamageTaken()
void boss_ragnaros::boss_ragnarosAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
        {
            if (events.IsInPhase(PHASE_SUBMERGED) && damage >= me->GetHealth())
            {
                damage = 0;
            }
        }
References Unit::GetHealth(), ScriptedAI::me, and PHASE_SUBMERGED.
DoAction()
void boss_ragnaros::boss_ragnarosAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == ACTION_FINISH_RAGNAROS_INTRO)
            {
                extraEvents.SetPhase(PHASE_INTRO);
                extraEvents.ScheduleEvent(EVENT_INTRO_SAY, 5s, 0, PHASE_INTRO);
            }
        }
References ACTION_FINISH_RAGNAROS_INTRO, EVENT_INTRO_SAY, extraEvents, PHASE_INTRO, EventMap::ScheduleEvent(), and EventMap::SetPhase().
EnterEvadeMode()
void boss_ragnaros::boss_ragnarosAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from BossAI.
        {
            if (!me->GetThreatMgr().GetThreatList().empty())
            {
                if (!_processingMagmaBurst)
                {
                    // Boss try to evade, but still got some targets on threat list - it means that none of these targets are in melee range - cast magma blast
                    _processingMagmaBurst = true;
                    events.ScheduleEvent(EVENT_MAGMA_BLAST, 4s, PHASE_EMERGED, PHASE_EMERGED);
                }
            }
            else
            {
                BossAI::EnterEvadeMode(why);
            }
        }
References _processingMagmaBurst, BossAI::EnterEvadeMode(), EVENT_MAGMA_BLAST, ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), ScriptedAI::me, and PHASE_EMERGED.
HandleEmerge()
void boss_ragnaros::boss_ragnarosAI::HandleEmerge () inline private
        {
            if (events.IsInPhase(PHASE_EMERGED))
            {
                return;
            }
            events.SetPhase(PHASE_EMERGED);
            ScheduleCombatEvents();
            extraEvents.CancelEventGroup(PHASE_SUBMERGED);
            extraEvents.SetPhase(PHASE_EMERGED);
            me->SetReactState(REACT_AGGRESSIVE);
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE|UNIT_FLAG_NOT_SELECTABLE);
            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, 0);
            me->HandleEmoteCommand(EMOTE_ONESHOT_EMERGE);
            me->RemoveAurasDueToSpell(SPELL_RAGNA_SUBMERGE_VISUAL);
            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true))
            {
                AttackStart(target);
            }
        }
References AttackStart(), EventMap::CancelEventGroup(), EMOTE_ONESHOT_EMERGE, extraEvents, Unit::HandleEmoteCommand(), ScriptedAI::me, PHASE_EMERGED, PHASE_SUBMERGED, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Unit::RemoveUnitFlag(), ScheduleCombatEvents(), UnitAI::SelectTarget(), EventMap::SetPhase(), Creature::SetReactState(), Unit::SetUInt32Value(), SPELL_RAGNA_SUBMERGE_VISUAL, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and UNIT_NPC_EMOTESTATE.
Referenced by SummonedCreatureDies(), and UpdateAI().
IsVictimWithinMeleeRange()
bool boss_ragnaros::boss_ragnarosAI::IsVictimWithinMeleeRange () const inline private
        {
            return me->GetVictim() && me->IsWithinMeleeRange(me->GetVictim());
        }
References Unit::GetVictim(), Unit::IsWithinMeleeRange(), and ScriptedAI::me.
Referenced by UpdateAI().
JustDied()
void boss_ragnaros::boss_ragnarosAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            _JustDied();
            extraEvents.Reset();
            me->SetFacingTo(DEATH_ORIENTATION);
        }
References BossAI::_JustDied(), DEATH_ORIENTATION, extraEvents, ScriptedAI::me, EventMap::Reset(), and Unit::SetFacingTo().
JustEngagedWith()
void boss_ragnaros::boss_ragnarosAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            _JustEngagedWith();
            events.SetPhase(PHASE_EMERGED);
            ScheduleCombatEvents();
        }
References BossAI::_JustEngagedWith(), PHASE_EMERGED, and ScheduleCombatEvents().
JustSummoned()
void boss_ragnaros::boss_ragnarosAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            BossAI::JustSummoned(summon);
            if (summon->GetEntry() == NPC_FLAME_OF_RAGNAROS)
            {
                summon->CastSpell((Unit*)nullptr, SPELL_INTENSE_HEAT, true, nullptr, nullptr, me->GetGUID());
            }
            else if (summon->GetEntry() == NPC_SON_OF_FLAME)
            {
                DoZoneInCombat(summon);
            }
        }
References Unit::CastSpell(), CreatureAI::DoZoneInCombat(), Object::GetEntry(), Object::GetGUID(), BossAI::JustSummoned(), ScriptedAI::me, NPC_FLAME_OF_RAGNAROS, NPC_SON_OF_FLAME, and SPELL_INTENSE_HEAT.
KilledUnit()
void boss_ragnaros::boss_ragnarosAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (roll_chance_i(25) && victim->IsPlayer())
            {
                Talk(SAY_KILL);
            }
        }
References Object::IsPlayer(), roll_chance_i(), and SAY_KILL.
Reset()
void boss_ragnaros::boss_ragnarosAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            _Reset();
            // Never reset intro events!
            if (_isIntroDone && !(extraEvents.GetPhaseMask() & (1 << (PHASE_INTRO - 1))))
            {
                extraEvents.Reset();
                extraEvents.SetPhase(PHASE_EMERGED);
                me->SetReactState(REACT_AGGRESSIVE);
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE|UNIT_FLAG_NOT_SELECTABLE);
                me->SetImmuneToAll(false);
                me->SetUInt32Value(UNIT_NPC_EMOTESTATE, 0);
                me->HandleEmoteCommand(EMOTE_ONESHOT_EMERGE);
            }
            _hasYelledMagmaBurst = false;
            _processingMagmaBurst = false;
            _hasSubmergedOnce = false;
            _isKnockbackEmoteAllowed = true;
            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, 0);
            me->SetControlled(true, UNIT_STATE_ROOT);
            _lavaBurstGUIDS.clear();
        }
References _hasSubmergedOnce, _hasYelledMagmaBurst, _isIntroDone, _isKnockbackEmoteAllowed, _lavaBurstGUIDS, _processingMagmaBurst, BossAI::_Reset(), EMOTE_ONESHOT_EMERGE, extraEvents, EventMap::GetPhaseMask(), Unit::HandleEmoteCommand(), ScriptedAI::me, PHASE_EMERGED, PHASE_INTRO, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), EventMap::Reset(), Unit::SetControlled(), Unit::SetImmuneToAll(), EventMap::SetPhase(), Creature::SetReactState(), Unit::SetUInt32Value(), UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_EMOTESTATE, and UNIT_STATE_ROOT.
ScheduleCombatEvents()
void boss_ragnaros::boss_ragnarosAI::ScheduleCombatEvents () inline private
        {
            events.RescheduleEvent(EVENT_ERUPTION, 15s, PHASE_EMERGED, PHASE_EMERGED);
            events.RescheduleEvent(EVENT_WRATH_OF_RAGNAROS, 30s, PHASE_EMERGED, PHASE_EMERGED);
            events.RescheduleEvent(EVENT_HAND_OF_RAGNAROS, 25s, PHASE_EMERGED, PHASE_EMERGED);
            events.RescheduleEvent(EVENT_LAVA_BURST, 10s, PHASE_EMERGED, PHASE_EMERGED);
            events.RescheduleEvent(EVENT_SUBMERGE, 180s, PHASE_EMERGED, PHASE_EMERGED);
            events.RescheduleEvent(EVENT_MIGHT_OF_RAGNAROS, 11s, PHASE_EMERGED, PHASE_EMERGED);
        }
References EVENT_ERUPTION, EVENT_HAND_OF_RAGNAROS, EVENT_LAVA_BURST, EVENT_MIGHT_OF_RAGNAROS, EVENT_SUBMERGE, EVENT_WRATH_OF_RAGNAROS, and PHASE_EMERGED.
Referenced by HandleEmerge(), and JustEngagedWith().
SetGUID()
void boss_ragnaros::boss_ragnarosAI::SetGUID (ObjectGuid guid, int32 index) inline override virtual
Reimplemented from UnitAI.
        {
            if (index == GO_LAVA_BURST)
            {
                if (_lavaBurstGUIDS.empty())
                {
                    extraEvents.ScheduleEvent(EVENT_LAVA_BURST_TRIGGER, 1);
                }
                _lavaBurstGUIDS.insert(guid);
            }
        }
References _lavaBurstGUIDS, EVENT_LAVA_BURST_TRIGGER, extraEvents, GO_LAVA_BURST, and EventMap::ScheduleEvent().
SummonedCreatureDies()
void boss_ragnaros::boss_ragnarosAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            summons.Despawn(summon);
            if (events.IsInPhase(PHASE_SUBMERGED) && !summons.HasEntry(NPC_SON_OF_FLAME))
            {
                HandleEmerge();
            }
        }
References SummonList::Despawn(), HandleEmerge(), SummonList::HasEntry(), NPC_SON_OF_FLAME, PHASE_SUBMERGED, and BossAI::summons.
UpdateAI()
void boss_ragnaros::boss_ragnarosAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            if (!extraEvents.Empty())
            {
                extraEvents.Update(diff);
                while (uint32 const eventId = extraEvents.ExecuteEvent())
                {
                    switch (eventId)
                    {
                        // Intro events
                        case EVENT_INTRO_SAY:
{
                            Talk(SAY_ARRIVAL5_RAG);
                            extraEvents.ScheduleEvent(EVENT_INTRO_MAKE_ATTACKABLE, 2500ms, 0, PHASE_INTRO);
                            break;
                        }
                        case EVENT_INTRO_MAKE_ATTACKABLE:
{
                            _isIntroDone = true;
                            extraEvents.SetPhase(PHASE_EMERGED);
                            me->RemoveAurasDueToSpell(SPELL_RAGNAROS_SUBMERGE_EFFECT);
                            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            me->SetImmuneToAll(false);
                            me->SetReactState(REACT_AGGRESSIVE);
                            DoZoneInCombat();
                            break;
                        }
                        // Submerge events
                        case EVENT_EMERGE:
{
                            HandleEmerge();
                            break;
                        }
                        case EVENT_RESET_KNOCKBACK_EMOTE:
{
                            _isKnockbackEmoteAllowed = true;
                            break;
                        }
                        case EVENT_LAVA_BURST_TRIGGER:
{
                            if (!_lavaBurstGUIDS.empty())
{
                                ObjectGuid lavaBurstGUID = Acore::Containers::SelectRandomContainerElement(_lavaBurstGUIDS);
                                if (GameObject* go = ObjectAccessor::GetGameObject(*me, lavaBurstGUID))
{
                                    go->CastSpell(nullptr, SPELL_LAVA_BURST_TRAP);
                                    go->SendCustomAnim(0);
                                }
                                _lavaBurstGUIDS.erase(lavaBurstGUID);
                                extraEvents.RepeatEvent(1000);
                            }
                            else
{
                                events.RescheduleEvent(EVENT_LAVA_BURST, 10s, PHASE_EMERGED, PHASE_EMERGED);
                            }
                            break;
                        }
                    }
                }
            }
            if (!UpdateVictim())
            {
                if (!_processingMagmaBurst)
                {
                    return;
                }
            }
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
            {
                return;
            }
            // Base combat events - (mainly emerge phase)
            while (uint32 const eventId = events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_WRATH_OF_RAGNAROS:
                    {
                        DoCastVictim(SPELL_WRATH_OF_RAGNAROS);
                        if (urand(0, 1))
{
                            Talk(SAY_WRATH);
                        }
                        events.RepeatEvent(25000);
                        break;
                    }
                    case EVENT_HAND_OF_RAGNAROS:
                    {
                        DoCastSelf(SPELL_HAND_OF_RAGNAROS);
                        if (_isKnockbackEmoteAllowed)
{
                            Talk(SAY_KNOCKBACK);
                            _isKnockbackEmoteAllowed = false;
                            extraEvents.RescheduleEvent(EVENT_RESET_KNOCKBACK_EMOTE, 5s);
                        }
                        events.RepeatEvent(20000);
                        break;
                    }
                    case EVENT_LAVA_BURST:
                    {
                        DoCastAOE(SPELL_LAVA_BURST);
                        break;
                    }
                    case EVENT_MAGMA_BLAST:
                    {
                        _processingMagmaBurst = false;
                        if (!IsVictimWithinMeleeRange())
{
                            DoCastRandomTarget(SPELL_MAGMA_BLAST);
                            if (!_hasYelledMagmaBurst)
{
                                Talk(SAY_MAGMABURST);
                                _hasYelledMagmaBurst = true;
                            }
                        }
                        break;
                    }
                    case EVENT_MIGHT_OF_RAGNAROS:
                    {
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, [](Unit const* target)
{
                            return target->IsPlayer() && target->getPowerType() == POWER_MANA;
                        }))
{
                            if (me->CastSpell(target, SPELL_MIGHT_OF_RAGNAROS) == SPELL_CAST_OK && _isKnockbackEmoteAllowed)
{
                                Talk(SAY_KNOCKBACK, me);
                                _isKnockbackEmoteAllowed = false;
                                extraEvents.RescheduleEvent(EVENT_RESET_KNOCKBACK_EMOTE, 5s);
                            }
                        }
                        events.RepeatEvent(urand(11000, 30000));
                        break;
                    }
                    case EVENT_SUBMERGE:
                    {
                        events.CancelEventGroup(PHASE_EMERGED);
                        events.SetPhase(PHASE_SUBMERGED);
                        extraEvents.SetPhase(PHASE_SUBMERGED);
                        me->SetReactState(REACT_PASSIVE);
                        me->InterruptNonMeleeSpells(false);
                        me->AttackStop();
                        DoResetThreatList();
                        me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                        me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_SUBMERGED);
                        DoCastSelf(SPELL_RAGNA_SUBMERGE_VISUAL, true);
                        //me->HandleEmoteCommand(EMOTE_ONESHOT_SUBMERGE);
                        Talk(_hasSubmergedOnce ? SAY_REINFORCEMENTS2 : SAY_REINFORCEMENTS1);
                        DoCastAOE(SPELL_SUMMON_SONS_FLAME);
                        if (!_hasSubmergedOnce)
{
                            _hasSubmergedOnce = true;
                        }
                        extraEvents.ScheduleEvent(EVENT_EMERGE, 90s, PHASE_SUBMERGED, PHASE_SUBMERGED);
                        break;
                    }
                }
                if (me->HasUnitState(UNIT_STATE_CASTING))
                {
                    return;
                }
            }
            DoMeleeAttackIfReady();
        }
References _hasSubmergedOnce, _hasYelledMagmaBurst, _isIntroDone, _isKnockbackEmoteAllowed, _lavaBurstGUIDS, _processingMagmaBurst, Unit::AttackStop(), Unit::CastSpell(), UnitAI::DoCastAOE(), UnitAI::DoCastRandomTarget(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreatList(), CreatureAI::DoZoneInCombat(), EMOTE_STATE_SUBMERGED, EventMap::Empty(), EVENT_EMERGE, EVENT_HAND_OF_RAGNAROS, EVENT_INTRO_MAKE_ATTACKABLE, EVENT_INTRO_SAY, EVENT_LAVA_BURST, EVENT_LAVA_BURST_TRIGGER, EVENT_MAGMA_BLAST, EVENT_MIGHT_OF_RAGNAROS, EVENT_RESET_KNOCKBACK_EMOTE, EVENT_SUBMERGE, EVENT_WRATH_OF_RAGNAROS, EventMap::ExecuteEvent(), extraEvents, ObjectAccessor::GetGameObject(), Unit::getPowerType(), HandleEmerge(), Unit::HasUnitState(), Unit::InterruptNonMeleeSpells(), Object::IsPlayer(), IsVictimWithinMeleeRange(), ScriptedAI::me, PHASE_EMERGED, PHASE_INTRO, PHASE_SUBMERGED, POWER_MANA, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), Unit::RemoveUnitFlag(), EventMap::RepeatEvent(), EventMap::RescheduleEvent(), SAY_ARRIVAL5_RAG, SAY_KNOCKBACK, SAY_MAGMABURST, SAY_REINFORCEMENTS1, SAY_REINFORCEMENTS2, SAY_WRATH, EventMap::ScheduleEvent(), Acore::Containers::SelectRandomContainerElement(), UnitAI::SelectTarget(), Unit::SetImmuneToAll(), EventMap::SetPhase(), Creature::SetReactState(), Unit::SetUInt32Value(), Unit::SetUnitFlag(), SPELL_CAST_OK, SPELL_HAND_OF_RAGNAROS, SPELL_LAVA_BURST, SPELL_LAVA_BURST_TRAP, SPELL_MAGMA_BLAST, SPELL_MIGHT_OF_RAGNAROS, SPELL_RAGNA_SUBMERGE_VISUAL, SPELL_RAGNAROS_SUBMERGE_EFFECT, SPELL_SUMMON_SONS_FLAME, SPELL_WRATH_OF_RAGNAROS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_EMOTESTATE, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_hasSubmergedOnce
bool boss_ragnaros::boss_ragnarosAI::_hasSubmergedOnce private
Referenced by Reset(), and UpdateAI().
_hasYelledMagmaBurst
bool boss_ragnaros::boss_ragnarosAI::_hasYelledMagmaBurst private
Referenced by Reset(), and UpdateAI().
_isIntroDone
bool boss_ragnaros::boss_ragnarosAI::_isIntroDone private
Referenced by Reset(), and UpdateAI().
_isKnockbackEmoteAllowed
bool boss_ragnaros::boss_ragnarosAI::_isKnockbackEmoteAllowed private
Referenced by Reset(), and UpdateAI().
_lavaBurstGUIDS
GuidSet boss_ragnaros::boss_ragnarosAI::_lavaBurstGUIDS private
Referenced by Reset(), SetGUID(), and UpdateAI().
_processingMagmaBurst
bool boss_ragnaros::boss_ragnarosAI::_processingMagmaBurst private
Referenced by EnterEvadeMode(), Reset(), and UpdateAI().
extraEvents
EventMap boss_ragnaros::boss_ragnarosAI::extraEvents private
Referenced by DoAction(), HandleEmerge(), JustDied(), Reset(), SetGUID(), and UpdateAI().