AzerothCore: GameObjectModelOwnerImpl Class Reference
GameObjectModelOwnerImpl Class Reference
Public Member Functions
GameObjectModelOwnerImpl (GameObject *owner)
bool IsSpawned () const override
uint32 GetDisplayId () const override
uint32 GetPhaseMask () const override
G3D::Vector3 GetPosition () const override
float GetOrientation () const override
float GetScale () const override
void DebugVisualizeCorner (G3D::Vector3 const &corner) const override
Public Member Functions inherited from GameObjectModelOwnerBase
virtual ~GameObjectModelOwnerBase ()=default
virtual bool IsSpawned () const =0
virtual uint32 GetDisplayId () const =0
virtual uint32 GetPhaseMask () const =0
virtual G3D::Vector3 GetPosition () const =0
virtual float GetOrientation () const =0
virtual float GetScale () const =0
virtual void DebugVisualizeCorner (G3D::Vector3 const &) const =0
Private Attributes
GameObject * _owner
Detailed Description
Constructor & Destructor Documentation
GameObjectModelOwnerImpl()
GameObjectModelOwnerImpl::GameObjectModelOwnerImpl (GameObject * owner) inline explicit
: _owner(owner) { }
Member Function Documentation
DebugVisualizeCorner()
void GameObjectModelOwnerImpl::DebugVisualizeCorner (G3D::Vector3 const & corner) const inline override virtual
Implements GameObjectModelOwnerBase.
{ const_cast<GameObject*>(_owner)->SummonCreature(1, corner.x, corner.y, corner.z, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 10000); }
References _owner, and TEMPSUMMON_TIMED_DESPAWN.
GetDisplayId()
uint32 GameObjectModelOwnerImpl::GetDisplayId () const inline override virtual
Implements GameObjectModelOwnerBase.
{ return _owner->GetDisplayId(); }
References _owner, and GameObject::GetDisplayId().
GetOrientation()
float GameObjectModelOwnerImpl::GetOrientation () const inline override virtual
Implements GameObjectModelOwnerBase.
{ return _owner->GetOrientation(); }
References _owner, and Position::GetOrientation().
GetPhaseMask()
uint32 GameObjectModelOwnerImpl::GetPhaseMask () const inline override virtual
Implements GameObjectModelOwnerBase.
{ return (_owner->GetGoState() == GO_STATE_READY || _owner->IsTransport()) ? _owner->GetPhaseMask() : 0; }
References _owner, GameObject::GetGoState(), WorldObject::GetPhaseMask(), GO_STATE_READY, and GameObject::IsTransport().
GetPosition()
G3D::Vector3 GameObjectModelOwnerImpl::GetPosition () const inline override virtual
Implements GameObjectModelOwnerBase.
{ return G3D::Vector3(_owner->GetPositionX(), _owner->GetPositionY(), _owner->GetPositionZ()); }
References _owner, Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
GetScale()
float GameObjectModelOwnerImpl::GetScale () const inline override virtual
Implements GameObjectModelOwnerBase.
{ return _owner->GetObjectScale(); }
References _owner, and Object::GetObjectScale().
IsSpawned()
bool GameObjectModelOwnerImpl::IsSpawned () const inline override virtual
Implements GameObjectModelOwnerBase.
{ return _owner->isSpawned(); }
References _owner, and GameObject::isSpawned().
Member Data Documentation
_owner
GameObject* GameObjectModelOwnerImpl::_owner private
Referenced by DebugVisualizeCorner(), GetDisplayId(), GetOrientation(), GetPhaseMask(), GetPosition(), GetScale(), and IsSpawned().