AzerothCore: instance_the_eye::instance_the_eye_InstanceMapScript Struct Reference
instance_the_eye::instance_the_eye_InstanceMapScript Struct Reference
Public Member Functions
instance_the_eye_InstanceMapScript (Map *map)
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *gobject) override
ObjectGuid GetGuidData (uint32 identifier) const override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
ObjectGuid ThaladredTheDarkenerGUID
ObjectGuid LordSanguinarGUID
ObjectGuid GrandAstromancerCapernianGUID
ObjectGuid MasterEngineerTelonicusGUID
ObjectGuid AlarGUID
ObjectGuid KaelthasGUID
ObjectGuid BridgeWindowGUID
ObjectGuid KaelStateRightGUID
ObjectGuid KaelStateLeftGUID
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_the_eye_InstanceMapScript()
instance_the_eye::instance_the_eye_InstanceMapScript::instance_the_eye_InstanceMapScript (Map * map) inline
                                                     : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTER);
            LoadObjectData(creatureData, gameObjectData);
            LoadDoorData(doorData);
            LoadBossBoundaries(boundaries);
        }
References boundaries, creatureData, DataHeader, doorData, gameObjectData, InstanceScript::LoadBossBoundaries(), InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), MAX_ENCOUNTER, InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
GetGuidData()
ObjectGuid instance_the_eye::instance_the_eye_InstanceMapScript::GetGuidData (uint32 identifier) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (identifier)
            {
                case GO_BRIDGE_WINDOW:
                    return BridgeWindowGUID;
                case GO_KAEL_STATUE_RIGHT:
                    return KaelStateRightGUID;
                case GO_KAEL_STATUE_LEFT:
                    return KaelStateLeftGUID;
                case NPC_ALAR:
                    return AlarGUID;
                case NPC_KAELTHAS:
                    return KaelthasGUID;
            }
            return ObjectGuid::Empty;
        }
References AlarGUID, BridgeWindowGUID, ObjectGuid::Empty, GO_BRIDGE_WINDOW, GO_KAEL_STATUE_LEFT, GO_KAEL_STATUE_RIGHT, KaelStateLeftGUID, KaelStateRightGUID, KaelthasGUID, NPC_ALAR, and NPC_KAELTHAS.
OnCreatureCreate()
void instance_the_eye::instance_the_eye_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_ALAR:
                    AlarGUID = creature->GetGUID();
                    break;
                case NPC_KAELTHAS:
                    KaelthasGUID = creature->GetGUID();
                    break;
                case NPC_THALADRED:
                    ThaladredTheDarkenerGUID = creature->GetGUID();
                    break;
                case NPC_TELONICUS:
                    MasterEngineerTelonicusGUID = creature->GetGUID();
                    break;
                case NPC_CAPERNIAN:
                    GrandAstromancerCapernianGUID = creature->GetGUID();
                    break;
                case NPC_LORD_SANGUINAR:
                    LordSanguinarGUID = creature->GetGUID();
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References AlarGUID, Object::GetEntry(), Object::GetGUID(), GrandAstromancerCapernianGUID, KaelthasGUID, LordSanguinarGUID, MasterEngineerTelonicusGUID, NPC_ALAR, NPC_CAPERNIAN, NPC_KAELTHAS, NPC_LORD_SANGUINAR, NPC_TELONICUS, NPC_THALADRED, InstanceScript::OnCreatureCreate(), and ThaladredTheDarkenerGUID.
OnGameObjectCreate()
void instance_the_eye::instance_the_eye_InstanceMapScript::OnGameObjectCreate (GameObject * gobject) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (gobject->GetEntry())
            {
                case GO_BRIDGE_WINDOW:
                    BridgeWindowGUID = gobject->GetGUID();
                    break;
                case GO_KAEL_STATUE_RIGHT:
                    KaelStateRightGUID = gobject->GetGUID();
                    break;
                case GO_KAEL_STATUE_LEFT:
                    KaelStateLeftGUID = gobject->GetGUID();
                    break;
            }
            InstanceScript::OnGameObjectCreate(gobject);
        }
References BridgeWindowGUID, Object::GetEntry(), Object::GetGUID(), GO_BRIDGE_WINDOW, GO_KAEL_STATUE_LEFT, GO_KAEL_STATUE_RIGHT, KaelStateLeftGUID, KaelStateRightGUID, and InstanceScript::OnGameObjectCreate().
Member Data Documentation
AlarGUID
ObjectGuid instance_the_eye::instance_the_eye_InstanceMapScript::AlarGUID
Referenced by GetGuidData(), and OnCreatureCreate().
BridgeWindowGUID
ObjectGuid instance_the_eye::instance_the_eye_InstanceMapScript::BridgeWindowGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GrandAstromancerCapernianGUID
ObjectGuid instance_the_eye::instance_the_eye_InstanceMapScript::GrandAstromancerCapernianGUID
Referenced by OnCreatureCreate().
KaelStateLeftGUID
ObjectGuid instance_the_eye::instance_the_eye_InstanceMapScript::KaelStateLeftGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
KaelStateRightGUID
ObjectGuid instance_the_eye::instance_the_eye_InstanceMapScript::KaelStateRightGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
KaelthasGUID
ObjectGuid instance_the_eye::instance_the_eye_InstanceMapScript::KaelthasGUID
Referenced by GetGuidData(), and OnCreatureCreate().
LordSanguinarGUID
ObjectGuid instance_the_eye::instance_the_eye_InstanceMapScript::LordSanguinarGUID
Referenced by OnCreatureCreate().
MasterEngineerTelonicusGUID
ObjectGuid instance_the_eye::instance_the_eye_InstanceMapScript::MasterEngineerTelonicusGUID
Referenced by OnCreatureCreate().
ThaladredTheDarkenerGUID
ObjectGuid instance_the_eye::instance_the_eye_InstanceMapScript::ThaladredTheDarkenerGUID
Referenced by OnCreatureCreate().