AzerothCore: ParallelogramBoundary Class Reference
ParallelogramBoundary Class Reference
#include "AreaBoundary.h"
Public Member Functions
ParallelogramBoundary (Position const &cornerA, Position const &cornerB, Position const &cornerD, bool isInverted=false)
Public Member Functions inherited from AreaBoundary
bool IsWithinBoundary (Position const *pos) const
bool IsWithinBoundary (Position const &pos) const
virtual ~AreaBoundary ()
Protected Member Functions
bool IsWithinBoundaryArea (Position const *pos) const override
Protected Member Functions inherited from AreaBoundary
AreaBoundary (bool isInverted)
virtual bool IsWithinBoundaryArea (Position const *pos) const =0
Private Attributes
DoublePosition const _a
DoublePosition const _b
DoublePosition const _d
DoublePosition const _c
double const _abx
double const _dax
double const _aby
double const _day
Detailed Description
Constructor & Destructor Documentation
ParallelogramBoundary()
ParallelogramBoundary::ParallelogramBoundary (Position const & cornerA, Position const & cornerB, Position const & cornerD, bool isInverted = false)
                                                                                                                                       :
    AreaBoundary(isInverted), _a(cornerA), _b(cornerB), _d(cornerD), _c(DoublePosition(_d.GetDoublePositionX() + (_b.GetDoublePositionX() - _a.GetDoublePositionX()), _d.GetDoublePositionY() + (_b.GetDoublePositionY() - _a.GetDoublePositionY()))), _abx(_b.GetDoublePositionX() - _a.GetDoublePositionX()), _dax(_a.GetDoublePositionX() - _d.GetDoublePositionX()), _aby(_b.GetDoublePositionY() - _a.GetDoublePositionY()), _day(_a.GetDoublePositionY() - _d.GetDoublePositionY()) { }
Member Function Documentation
IsWithinBoundaryArea()
bool ParallelogramBoundary::IsWithinBoundaryArea (Position const * pos) const override protected virtual
Implements AreaBoundary.
{
    // half-plane signs
    bool sign1 = ((-_b.GetDoublePositionX() + pos->GetPositionX()) * _aby - (-_b.GetDoublePositionY() + pos->GetPositionY()) * _abx) < 0;
    bool sign2 = ((-_a.GetDoublePositionX() + pos->GetPositionX()) * _day - (-_a.GetDoublePositionY() + pos->GetPositionY()) * _dax) < 0;
    bool sign3 = ((-_d.GetDoublePositionY() + pos->GetPositionY()) * _abx - (-_d.GetDoublePositionX() + pos->GetPositionX()) * _aby) < 0; // AB = -CD
    bool sign4 = ((-_c.GetDoublePositionY() + pos->GetPositionY()) * _dax - (-_c.GetDoublePositionX() + pos->GetPositionX()) * _day) < 0; // DA = -BC
    // if all signs are equal, the point is inside
    return ((sign1 == sign2) && (sign2 == sign3) && (sign3 == sign4));
}
References _a, _abx, _aby, _b, _c, _d, _dax, _day, AreaBoundary::DoublePosition::GetDoublePositionX(), AreaBoundary::DoublePosition::GetDoublePositionY(), Position::GetPositionX(), and Position::GetPositionY().
Member Data Documentation
_a
DoublePosition const ParallelogramBoundary::_a private
Referenced by IsWithinBoundaryArea().
_abx
double const ParallelogramBoundary::_abx private
Referenced by IsWithinBoundaryArea().
_aby
double const ParallelogramBoundary::_aby private
Referenced by IsWithinBoundaryArea().
_b
DoublePosition const ParallelogramBoundary::_b private
Referenced by IsWithinBoundaryArea().
_c
DoublePosition const ParallelogramBoundary::_c private
Referenced by IsWithinBoundaryArea().
_d
DoublePosition const ParallelogramBoundary::_d private
Referenced by IsWithinBoundaryArea().
_dax
double const ParallelogramBoundary::_dax private
Referenced by IsWithinBoundaryArea().
_day
double const ParallelogramBoundary::_day private
Referenced by IsWithinBoundaryArea().