AzerothCore: npc_cameron Struct Reference
npc_cameron Struct Reference
Public Member Functions
npc_cameron (Creature *creature)
void MoveTheChildren ()
void PathEndReached (uint32 pathId) override
void sOnGameEvent (bool start, uint16 eventId) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Static Public Member Functions
static uint32 SoundPicker ()
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Private Attributes
EventMap _events
bool _started
GuidVector _childrenGUIDs
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_cameron()
npc_cameron::npc_cameron (Creature * creature) inline
                                    : ScriptedAI(creature)
    {
        _started = false;
    }
References _started.
Member Function Documentation
MoveTheChildren()
void npc_cameron::MoveTheChildren () inline
    {
        std::vector<Position> MovePosPositions =
        {
            { -9373.521f, -67.71767f, 69.201965f, 1.117011f },
            { -9374.94f, -62.51654f, 69.201965f, 5.201081f },
            { -9371.013f, -71.20811f, 69.201965f, 1.937315f },
            { -9368.419f, -66.47543f, 69.201965f, 3.141593f },
            { -9372.376f, -65.49946f, 69.201965f, 4.206244f },
            { -9377.477f, -67.8297f, 69.201965f, 0.296706f }
        };
        Acore::Containers::RandomShuffle(MovePosPositions);
        // first we break formation because children will need to move on their own now
        for (auto& guid : _childrenGUIDs)
            if (Creature* child = ObjectAccessor::GetCreature(*me, guid))
                if (child->GetFormation())
                    child->GetFormation()->RemoveMember(child);
        // Move each child to an random position
        for (uint32 i = 0; i < _childrenGUIDs.size(); ++i)
        {
            if (Creature* children = ObjectAccessor::GetCreature(*me, _childrenGUIDs[i]))
            {
                children->SetWalk(true);
                children->GetMotionMaster()->MovePoint(0, MovePosPositions[i], true, MovePosPositions[i].GetOrientation());
            }
        }
        me->SetWalk(true);
        me->GetMotionMaster()->MovePoint(0, MovePosPositions.back(), true, MovePosPositions.back().GetOrientation());
    }
References _childrenGUIDs, ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MovePoint(), Acore::Containers::RandomShuffle(), and Creature::SetWalk().
Referenced by PathEndReached().
PathEndReached()
void npc_cameron::PathEndReached (uint32 pathId) inline override virtual
Reimplemented from CreatureAI.
    {
        switch (pathId)
        {
            case STORMWIND_PATH:
            {
                _events.ScheduleEvent(EVENT_RANDOM_MOVEMENT, 2s);
                _events.ScheduleEvent(EVENT_WP_START_GOLDSHIRE, 11min);
                break;
            }
            case GOLDSHIRE_PATH:
            {
                _events.ScheduleEvent(EVENT_RANDOM_MOVEMENT, 2s);
                _events.ScheduleEvent(EVENT_WP_START_WOODS, 15min);
                break;
            }
            case WOODS_PATH:
            {
                _events.ScheduleEvent(EVENT_RANDOM_MOVEMENT, 2s);
                _events.ScheduleEvent(EVENT_WP_START_HOUSE, 6min); // 6 minutes
                _events.ScheduleEvent(EVENT_WP_START_LISA, 362s);
                break;
            }
            case HOUSE_PATH:
            {
                // Move childeren at last point
                MoveTheChildren();
                // After 30 seconds a random sound should play
                _events.ScheduleEvent(EVENT_PLAY_SOUNDS, 30s);
                break;
            }
        }
    }
References _events, EVENT_PLAY_SOUNDS, EVENT_RANDOM_MOVEMENT, EVENT_WP_START_GOLDSHIRE, EVENT_WP_START_HOUSE, EVENT_WP_START_LISA, EVENT_WP_START_WOODS, GOLDSHIRE_PATH, HOUSE_PATH, MoveTheChildren(), EventMap::ScheduleEvent(), STORMWIND_PATH, and WOODS_PATH.
sOnGameEvent()
void npc_cameron::sOnGameEvent (bool start, uint16 eventId) inline override virtual
Reimplemented from UnitAI.
    {
        if (start && eventId == GAME_EVENT_CHILDREN_OF_GOLDSHIRE)
        {
            // Start event at 7 am
            // Begin pathing
            _events.ScheduleEvent(EVENT_BEGIN_EVENT, 2s);
            _started = true;
        }
        else if (!start && eventId == GAME_EVENT_CHILDREN_OF_GOLDSHIRE)
        {
            // Reset event at 8 am
            _started = false;
            _events.Reset();
        }
    }
References _events, _started, EVENT_BEGIN_EVENT, GAME_EVENT_CHILDREN_OF_GOLDSHIRE, EventMap::Reset(), and EventMap::ScheduleEvent().
SoundPicker()
static uint32 npc_cameron::SoundPicker () inline static
    {
        return RAND(
            BANSHEE_DEATH,
            BANSHEEPREAGGRO,
            CTHUN_YOU_WILL_DIE,
            CTHUN_DEATH_IS_CLOSE,
            HUMAN_FEMALE_EMOTE_CRY,
            GHOSTDEATH
        );
    }
References BANSHEE_DEATH, BANSHEEPREAGGRO, CTHUN_DEATH_IS_CLOSE, CTHUN_YOU_WILL_DIE, GHOSTDEATH, HUMAN_FEMALE_EMOTE_CRY, and RAND().
Referenced by UpdateAI().
UpdateAI()
void npc_cameron::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
    {
        if (!_started)
            return;
        _events.Update(diff);
        while (uint32 eventId = _events.ExecuteEvent())
        {
            switch (eventId)
            {
            case EVENT_WP_START_GOLDSHIRE:
                me->GetMotionMaster()->MovePath(GOLDSHIRE_PATH, false);
                break;
            case EVENT_WP_START_WOODS:
                me->GetMotionMaster()->MovePath(WOODS_PATH, false);
                break;
            case EVENT_WP_START_HOUSE:
                me->GetMotionMaster()->MovePath(HOUSE_PATH, false);
                break;
            case EVENT_WP_START_LISA:
                for (uint32 i = 0; i < _childrenGUIDs.size(); ++i)
                {
                    if (Creature* lisa = ObjectAccessor::GetCreature(*me, _childrenGUIDs[i]))
                    {
                        if (lisa->GetEntry() == NPC_LISA)
{
                            lisa->GetMotionMaster()->MovePath(LISA_PATH, false);
                            break;
                        }
                    }
                }
                break;
            case EVENT_PLAY_SOUNDS:
                me->PlayDistanceSound(SoundPicker());
                break;
            case EVENT_BEGIN_EVENT:
            {
                _childrenGUIDs.clear();
                // Get all childeren's guid's.
                if (Creature* dana = me->FindNearestCreature(NPC_DANA, 25.0f))
                    _childrenGUIDs.push_back(dana->GetGUID());
                if (Creature* john = me->FindNearestCreature(NPC_JOHN, 25.0f))
                    _childrenGUIDs.push_back(john->GetGUID());
                if (Creature* lisa = me->FindNearestCreature(NPC_LISA, 25.0f))
                    _childrenGUIDs.push_back(lisa->GetGUID());
                if (Creature* aaron = me->FindNearestCreature(NPC_AARON, 25.0f))
                    _childrenGUIDs.push_back(aaron->GetGUID());
                if (Creature* jose = me->FindNearestCreature(NPC_JOSE, 25.0f))
                    _childrenGUIDs.push_back(jose->GetGUID());
                // If Formation was disbanded, remake.
                if (!me->GetFormation()->IsFormed())
                    for (auto& guid : _childrenGUIDs)
                        if (Creature* child = ObjectAccessor::GetCreature(*me, guid))
                            child->SearchFormation();
                // Start movement
                me->GetMotionMaster()->MovePath(STORMWIND_PATH, false);
                break;
            }
            case EVENT_RANDOM_MOVEMENT:
            {
                me->GetMotionMaster()->MoveRandom(10.0f);
                break;
            }
            default:
                break;
            }
        }
    }
References _childrenGUIDs, _events, _started, EVENT_BEGIN_EVENT, EVENT_PLAY_SOUNDS, EVENT_RANDOM_MOVEMENT, EVENT_WP_START_GOLDSHIRE, EVENT_WP_START_HOUSE, EVENT_WP_START_LISA, EVENT_WP_START_WOODS, EventMap::ExecuteEvent(), WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), Creature::GetFormation(), Unit::GetMotionMaster(), GOLDSHIRE_PATH, HOUSE_PATH, CreatureGroup::IsFormed(), LISA_PATH, ScriptedAI::me, MotionMaster::MovePath(), MotionMaster::MoveRandom(), NPC_AARON, NPC_DANA, NPC_JOHN, NPC_JOSE, NPC_LISA, WorldObject::PlayDistanceSound(), SoundPicker(), STORMWIND_PATH, EventMap::Update(), and WOODS_PATH.
Member Data Documentation
_childrenGUIDs
GuidVector npc_cameron::_childrenGUIDs private
Referenced by MoveTheChildren(), and UpdateAI().
_events
EventMap npc_cameron::_events private
Referenced by PathEndReached(), sOnGameEvent(), and UpdateAI().
_started
bool npc_cameron::_started private
Referenced by npc_cameron(), sOnGameEvent(), and UpdateAI().