AzerothCore: boss_yoggsaron::boss_yoggsaronAI Struct Reference
boss_yoggsaron::boss_yoggsaronAI Struct Reference
Public Member Functions
boss_yoggsaronAI (Creature *pCreature)
void AttackStart (Unit *) override
void JustSummoned (Creature *cr) override
void SummonImmortalGuardian ()
void JustDied (Unit *) override
void DoAction (int32 param) override
uint32 GetData (uint32 param) const override
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
bool _thirdPhase
bool _usedInsane
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_yoggsaronAI()
boss_yoggsaron::boss_yoggsaronAI::boss_yoggsaronAI (Creature * pCreature) inline
                                              : ScriptedAI(pCreature), summons(pCreature)
        {
            m_pInstance = me->GetInstanceScript();
            _thirdPhase = false;
            _usedInsane = false;
            summons.DespawnAll();
            events.Reset();
            uint8 _count = 4;
            me->SetLootMode(31); // 1 + 2 + 4 + 8 + 16, remove with watchers addition
            if (m_pInstance)
            {
                for (uint8 i = 0; i < 4; ++i)
                    if (m_pInstance->GetData(TYPE_WATCHERS) & (1 << i))
                    {
                        me->RemoveLootMode(1 << _count);
                        --_count;
                    }
            }
        }
References _thirdPhase, _usedInsane, SummonList::DespawnAll(), ZoneScript::GetData(), WorldObject::GetInstanceScript(), m_pInstance, ScriptedAI::me, Creature::RemoveLootMode(), Creature::SetLootMode(), summons, and TYPE_WATCHERS.
Member Function Documentation
AttackStart()
void boss_yoggsaron::boss_yoggsaronAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
{ }
DoAction()
void boss_yoggsaron::boss_yoggsaronAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_DESPAWN_ADDS)
                summons.DespawnAll();
            else if (param == ACTION_YOGG_SARON_APPEAR)
            {
                me->SetVisible(true);
                me->CastSpell(me, SPELL_SHADOW_BARRIER, true);
                me->CastSpell(me, SPELL_KNOCK_AWAY, true);
                me->HandleEmoteCommand(EMOTE_ONESHOT_EMERGE);
                me->SetInCombatWithZone();
                me->SetUnitFlag(UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_PACIFIED);
            }
            else if (param == ACTION_YOGG_SARON_START_YELL)
            {
                Talk(SAY_YOGG_SARON_SPAWN);
            }
            else if (param == ACTION_YOGG_SARON_OPEN_PORTAL_YELL)
            {
                Talk(SAY_YOGG_SARON_MADNESS);
                Talk(EMOTE_YOGG_SARON_MADNESS);
            }
            else if (param == ACTION_YOGG_SARON_START_P3)
            {
                me->SetHealth(me->GetMaxHealth() * 0.3f);
                me->LowerPlayerDamageReq(me->GetMaxHealth() * 0.7f);
                me->RemoveAura(SPELL_SHADOW_BARRIER);
                events.ScheduleEvent(EVENT_YS_LUNATIC_GAZE, 7000);
                events.ScheduleEvent(EVENT_YS_SHADOW_BEACON, 20000);
                events.ScheduleEvent(EVENT_YS_SUMMON_GUARDIAN, 0);
                _thirdPhase = true;
                Talk(SAY_YOGG_SARON_PHASE_3);
            }
            else if (param == ACTION_YOGG_SARON_HARD_MODE)
            {
                events.ScheduleEvent(EVENT_YS_DEAFENING_ROAR, 50000);
            }
            else if (param == ACTION_YOGG_SARON_SHADOW_BEACON)
            {
                events.RescheduleEvent(EVENT_YS_SHADOW_BEACON, 40000);
            }
            else if (param == ACTION_REMOVE_STUN)
            {
                me->RemoveAura(SPELL_SHATTERED_ILLUSION);
                me->SetControlled(true, UNIT_STATE_ROOT);
            }
            else if (param == ACTION_FAILED_DRIVE_ME_CRAZY)
                _usedInsane = true;
        }
References _thirdPhase, _usedInsane, ACTION_DESPAWN_ADDS, ACTION_FAILED_DRIVE_ME_CRAZY, ACTION_REMOVE_STUN, ACTION_YOGG_SARON_APPEAR, ACTION_YOGG_SARON_HARD_MODE, ACTION_YOGG_SARON_OPEN_PORTAL_YELL, ACTION_YOGG_SARON_SHADOW_BEACON, ACTION_YOGG_SARON_START_P3, ACTION_YOGG_SARON_START_YELL, Unit::CastSpell(), SummonList::DespawnAll(), EMOTE_ONESHOT_EMERGE, EMOTE_YOGG_SARON_MADNESS, EVENT_YS_DEAFENING_ROAR, EVENT_YS_LUNATIC_GAZE, EVENT_YS_SHADOW_BEACON, EVENT_YS_SUMMON_GUARDIAN, Unit::GetMaxHealth(), Unit::HandleEmoteCommand(), Creature::LowerPlayerDamageReq(), ScriptedAI::me, Unit::RemoveAura(), SAY_YOGG_SARON_MADNESS, SAY_YOGG_SARON_PHASE_3, SAY_YOGG_SARON_SPAWN, Unit::SetControlled(), Unit::SetHealth(), Creature::SetInCombatWithZone(), Unit::SetUnitFlag(), Unit::SetVisible(), SPELL_KNOCK_AWAY, SPELL_SHADOW_BARRIER, SPELL_SHATTERED_ILLUSION, summons, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_PACIFIED, and UNIT_STATE_ROOT.
GetData()
uint32 boss_yoggsaron::boss_yoggsaronAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_GET_DRIVE_ME_CRAZY)
                return !_usedInsane;
            return 0;
        }
References _usedInsane, and DATA_GET_DRIVE_ME_CRAZY.
JustDied()
void boss_yoggsaron::boss_yoggsaronAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.DespawnAll();
            events.Reset();
            Talk(SAY_YOGG_SARON_DEATH);
            if (m_pInstance)
            {
                m_pInstance->SetData(TYPE_YOGGSARON, DONE);
                if (Creature* sara = ObjectAccessor::GetCreature(*me, m_pInstance->GetGuidData(NPC_SARA)))
                    sara->AI()->DoAction(ACTION_YOGG_SARON_DEATH);
                if (GameObject* go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_YOGG_SARON_DOORS)))
                    go->SetGoState(GO_STATE_ACTIVE);
            }
            Map::PlayerList const& pList = me->GetMap()->GetPlayers();
            for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
            {
                itr->GetSource()->RemoveAura(SPELL_SANITY);
                itr->GetSource()->RemoveAura(SPELL_INSANE1);
                itr->GetSource()->RemoveAura(SPELL_INSANE2);
            }
        }
References ACTION_YOGG_SARON_DEATH, MapRefMgr::begin(), SummonList::DespawnAll(), DONE, MapRefMgr::end(), ObjectAccessor::GetCreature(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Map::GetPlayers(), GO_STATE_ACTIVE, GO_YOGG_SARON_DOORS, m_pInstance, ScriptedAI::me, NPC_SARA, SAY_YOGG_SARON_DEATH, ZoneScript::SetData(), SPELL_INSANE1, SPELL_INSANE2, SPELL_SANITY, summons, and TYPE_YOGGSARON.
JustSummoned()
void boss_yoggsaron::boss_yoggsaronAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
{ summons.Summon(cr); }
References SummonList::Summon(), and summons.
SpellHit()
void boss_yoggsaron::boss_yoggsaronAI::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_IN_THE_MAWS_OF_THE_OLD_GOD)
                me->AddLootMode(32);
        }
References Creature::AddLootMode(), SpellInfo::Id, ScriptedAI::me, and SPELL_IN_THE_MAWS_OF_THE_OLD_GOD.
SummonImmortalGuardian()
void boss_yoggsaron::boss_yoggsaronAI::SummonImmortalGuardian () inline
        {
            uint32 dist = urand(38, 48);
            float o = rand_norm() * M_PI * 2;
            float Zplus = (dist - 38) / 6.5f;
            me->SummonCreature(NPC_IMMORTAL_GUARDIAN, me->GetPositionX() + dist * cos(o), me->GetPositionY() + dist * std::sin(o), 327.2 + Zplus, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
        }
References Position::GetPositionX(), Position::GetPositionY(), ScriptedAI::me, NPC_IMMORTAL_GUARDIAN, rand_norm(), WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_yoggsaron::boss_yoggsaronAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!_thirdPhase)
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_YS_LUNATIC_GAZE:
                    me->PlayDirectSound(YS_P3_LUNATIC_GAZE);
                    me->CastSpell(me, SPELL_LUNATIC_GAZE_YS, true);
                    events.Repeat(12s);
                    break;
                case EVENT_YS_DEAFENING_ROAR:
                    Talk(SAY_YOGG_SARON_DEAFENING_ROAR);
                    Talk(EMOTE_YOGG_SARON_DEAFENING_ROAR);
                    me->CastSpell(me, SPELL_DEAFENING_ROAR, false);
                    events.Repeat(50s);
                    break;
                case EVENT_YS_SHADOW_BEACON:
                    events.Repeat(5s);
                    Talk(EMOTE_YOGG_SARON_EMPOWERING_SHADOWS);
                    me->CastCustomSpell(SPELL_SHADOW_BEACON, SPELLVALUE_MAX_TARGETS, RAID_MODE(1, 3), me, false);
                    break;
                case EVENT_YS_SUMMON_GUARDIAN:
                    SummonImmortalGuardian();
                    events.Repeat(10s);
                    break;
            }
        }
References _thirdPhase, Unit::CastCustomSpell(), Unit::CastSpell(), EMOTE_YOGG_SARON_DEAFENING_ROAR, EMOTE_YOGG_SARON_EMPOWERING_SHADOWS, EVENT_YS_DEAFENING_ROAR, EVENT_YS_LUNATIC_GAZE, EVENT_YS_SHADOW_BEACON, EVENT_YS_SUMMON_GUARDIAN, Unit::HasUnitState(), ScriptedAI::me, WorldObject::PlayDirectSound(), ScriptedAI::RAID_MODE(), SAY_YOGG_SARON_DEAFENING_ROAR, SPELL_DEAFENING_ROAR, SPELL_LUNATIC_GAZE_YS, SPELL_SHADOW_BEACON, SPELLVALUE_MAX_TARGETS, SummonImmortalGuardian(), UNIT_STATE_CASTING, and YS_P3_LUNATIC_GAZE.
Member Data Documentation
_thirdPhase
bool boss_yoggsaron::boss_yoggsaronAI::_thirdPhase
Referenced by boss_yoggsaronAI(), DoAction(), and UpdateAI().
_usedInsane
bool boss_yoggsaron::boss_yoggsaronAI::_usedInsane
Referenced by boss_yoggsaronAI(), DoAction(), and GetData().
events
EventMap boss_yoggsaron::boss_yoggsaronAI::events
m_pInstance
InstanceScript* boss_yoggsaron::boss_yoggsaronAI::m_pInstance
Referenced by boss_yoggsaronAI(), and JustDied().
summons
SummonList boss_yoggsaron::boss_yoggsaronAI::summons
Referenced by boss_yoggsaronAI(), DoAction(), JustDied(), and JustSummoned().