AzerothCore: npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI Struct Reference
npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI Struct Reference
Public Member Functions
npc_pet_dk_ebon_gargoyleAI (Creature *creature)
void MovementInform (uint32 type, uint32 point) override
void InitializeAI () override
void MySelectNextTarget ()
void AttackStart (Unit *who) override
void RemoveTargetAura ()
void Reset () override
void FlyAway ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
ObjectGuid _targetGUID
uint32 _despawnTimer
uint32 _selectionTimer
uint32 _initialCastTimer
bool _despawning
bool _initialSelection
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_pet_dk_ebon_gargoyleAI()
npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::npc_pet_dk_ebon_gargoyleAI (Creature * creature) inline
                                                       : ScriptedAI(creature)
        {
            _despawnTimer = 36000; // 30 secs + 4 fly out + 2 initial attack timer
            _despawning = false;
            _initialSelection = true;
            _targetGUID.Clear();
        }
References _despawning, _despawnTimer, _initialSelection, _targetGUID, and ObjectGuid::Clear().
Member Function Documentation
AttackStart()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            RemoveTargetAura();
            _targetGUID = who->GetGUID();
            me->AddAura(SPELL_DK_SUMMON_GARGOYLE_1, who);
            ScriptedAI::AttackStart(who);
        }
References _targetGUID, Unit::AddAura(), ScriptedAI::AttackStart(), Object::GetGUID(), ScriptedAI::me, RemoveTargetAura(), and SPELL_DK_SUMMON_GARGOYLE_1.
FlyAway()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway () inline
        {
            RemoveTargetAura();
            // Stop Fighting
            me->CombatStop(true);
            me->ApplyModFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, true);
            // Sanctuary
            me->CastSpell(me, SPELL_DK_SANCTUARY, true);
            me->SetReactState(REACT_PASSIVE);
            me->SetSpeed(MOVE_FLIGHT, 1.0f, true);
            me->SetSpeed(MOVE_RUN, 1.0f, true);
            float x = me->GetPositionX() + 20 * cos(me->GetOrientation());
            float y = me->GetPositionY() + 20 * std::sin(me->GetOrientation());
            float z = me->GetPositionZ() + 40;
            me->DisableSpline();
            me->GetMotionMaster()->Clear(false);
            me->GetMotionMaster()->MoveCharge(x, y, z, 7.0f, 1);
            me->SetCanFly(true);
            me->SetDisableGravity(true);
            _despawning = true;
        }
References _despawning, Object::ApplyModFlag(), Unit::CastSpell(), MotionMaster::Clear(), Unit::CombatStop(), Unit::DisableSpline(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, MOVE_FLIGHT, MOVE_RUN, MotionMaster::MoveCharge(), REACT_PASSIVE, RemoveTargetAura(), Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetReactState(), Unit::SetSpeed(), SPELL_DK_SANCTUARY, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
Referenced by UpdateAI().
InitializeAI()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
        {
            ScriptedAI::InitializeAI();
            Unit* owner = me->GetOwner();
            if (!owner)
                return;
            // Xinef: Night of the Dead avoidance
            if (Aura* aur = me->GetAura(SPELL_DK_NIGHT_OF_THE_DEAD))
                if (AuraEffect* aurEff = owner->GetAuraEffect(SPELL_AURA_ADD_FLAT_MODIFIER, SPELLFAMILY_DEATHKNIGHT, 2718, 0))
                {
                    if (aur->GetEffect(0))
                    {
                        aur->GetEffect(0)->SetAmount(-aurEff->GetSpellInfo()->Effects[EFFECT_2].CalcValue());
                    }
                }
            me->SetCanFly(true);
            me->SetDisableGravity(true);
            float tz = me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), true, MAX_FALL_DISTANCE);
            me->GetMotionMaster()->MoveCharge(me->GetPositionX(), me->GetPositionY(), tz, 7.0f, 1);
            me->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
            _selectionTimer = 2000;
            _initialCastTimer = 0;
        }
References _initialCastTimer, _selectionTimer, Unit::AddUnitState(), EFFECT_2, Unit::GetAura(), Unit::GetAuraEffect(), WorldObject::GetMapHeight(), Unit::GetMotionMaster(), Unit::GetOwner(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), UnitAI::InitializeAI(), MAX_FALL_DISTANCE, ScriptedAI::me, MotionMaster::MoveCharge(), Creature::SetCanFly(), Creature::SetDisableGravity(), SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_DK_NIGHT_OF_THE_DEAD, SPELLFAMILY_DEATHKNIGHT, and UNIT_STATE_NO_ENVIRONMENT_UPD.
MovementInform()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type == POINT_MOTION_TYPE && point == 1)
            {
                me->SetCanFly(false);
                me->SetDisableGravity(false);
            }
        }
References ScriptedAI::me, POINT_MOTION_TYPE, Creature::SetCanFly(), and Creature::SetDisableGravity().
MySelectNextTarget()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::MySelectNextTarget () inline
        {
            Unit* owner = me->GetOwner();
            if (owner && owner->IsPlayer() && (!me->GetVictim() || me->GetVictim()->IsImmunedToSpell(sSpellMgr->GetSpellInfo(51963)) || !me->IsValidAttackTarget(me->GetVictim()) || !owner->CanSeeOrDetect(me->GetVictim())))
            {
                Unit* selection = owner->ToPlayer()->GetSelectedUnit();
                if (selection && selection != me->GetVictim() && me->IsValidAttackTarget(selection))
                {
                    me->GetMotionMaster()->Clear(false);
                    SetGazeOn(selection);
                }
                else if (!me->GetVictim() || !owner->CanSeeOrDetect(me->GetVictim()))
                {
                    me->CombatStop(true);
                    me->GetMotionMaster()->Clear(false);
                    me->GetMotionMaster()->MoveFollow(owner, PET_FOLLOW_DIST, 0.0f);
                    RemoveTargetAura();
                }
            }
        }
References WorldObject::CanSeeOrDetect(), MotionMaster::Clear(), Unit::CombatStop(), Unit::GetMotionMaster(), Unit::GetOwner(), Player::GetSelectedUnit(), Unit::GetVictim(), Unit::IsImmunedToSpell(), Object::IsPlayer(), Unit::IsValidAttackTarget(), ScriptedAI::me, MotionMaster::MoveFollow(), PET_FOLLOW_DIST, RemoveTargetAura(), CreatureAI::SetGazeOn(), sSpellMgr, and Object::ToPlayer().
Referenced by Reset(), and UpdateAI().
RemoveTargetAura()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::RemoveTargetAura () inline
        {
            if (Unit* target = ObjectAccessor::GetUnit(*me, _targetGUID))
                target->RemoveAura(SPELL_DK_SUMMON_GARGOYLE_1, me->GetGUID());
        }
References _targetGUID, Object::GetGUID(), ObjectAccessor::GetUnit(), ScriptedAI::me, and SPELL_DK_SUMMON_GARGOYLE_1.
Referenced by AttackStart(), FlyAway(), and MySelectNextTarget().
Reset()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _selectionTimer = 0;
            me->SetReactState(REACT_PASSIVE);
            MySelectNextTarget();
        }
References _selectionTimer, ScriptedAI::me, MySelectNextTarget(), REACT_PASSIVE, and Creature::SetReactState().
UpdateAI()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (_initialSelection)
            {
                _initialSelection = false;
                // Find victim of Summon Gargoyle spell
                std::list<Unit*> targets;
                Acore::AnyUnfriendlyUnitInObjectRangeCheck u_check(me, me, 50.0f);
                Acore::UnitListSearcher<Acore::AnyUnfriendlyUnitInObjectRangeCheck> searcher(me, targets, u_check);
                Cell::VisitAllObjects(me, searcher, 50.0f);
                for (std::list<Unit*>::const_iterator iter = targets.begin(); iter != targets.end(); ++iter)
                    if ((*iter)->GetAura(SPELL_DK_SUMMON_GARGOYLE_1, me->GetOwnerGUID()))
                    {
                        (*iter)->RemoveAura(SPELL_DK_SUMMON_GARGOYLE_1, me->GetOwnerGUID());
                        SetGazeOn(*iter);
                        _targetGUID = (*iter)->GetGUID();
                        break;
                    }
            }
            if (_despawnTimer > 4000)
            {
                _despawnTimer -= diff;
                if (!UpdateVictimWithGaze())
                {
                    MySelectNextTarget();
                    return;
                }
                _initialCastTimer += diff;
                _selectionTimer += diff;
                if (_selectionTimer >= 1000)
                {
                    MySelectNextTarget();
                    _selectionTimer = 0;
                }
                if (_initialCastTimer >= 2000 && !me->HasUnitState(UNIT_STATE_CASTING | UNIT_STATE_LOST_CONTROL) && me->GetMotionMaster()->GetMotionSlotType(MOTION_SLOT_CONTROLLED) == NULL_MOTION_TYPE)
                    me->CastSpell(me->GetVictim(), 51963, false);
            }
            else
            {
                if (!_despawning)
                    FlyAway();
                if (_despawnTimer > diff)
                    _despawnTimer -= diff;
                else
                    me->DespawnOrUnsummon();
            }
        }
References _despawning, _despawnTimer, _initialCastTimer, _initialSelection, _selectionTimer, _targetGUID, Unit::CastSpell(), Creature::DespawnOrUnsummon(), FlyAway(), Unit::GetMotionMaster(), MotionMaster::GetMotionSlotType(), Unit::GetOwnerGUID(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, MOTION_SLOT_CONTROLLED, MySelectNextTarget(), NULL_MOTION_TYPE, CreatureAI::SetGazeOn(), SPELL_DK_SUMMON_GARGOYLE_1, UNIT_STATE_CASTING, UNIT_STATE_LOST_CONTROL, CreatureAI::UpdateVictimWithGaze(), and Cell::VisitAllObjects().
Member Data Documentation
_despawning
bool npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_despawning private
Referenced by FlyAway(), npc_pet_dk_ebon_gargoyleAI(), and UpdateAI().
_despawnTimer
uint32 npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_despawnTimer private
Referenced by npc_pet_dk_ebon_gargoyleAI(), and UpdateAI().
_initialCastTimer
uint32 npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_initialCastTimer private
Referenced by InitializeAI(), and UpdateAI().
_initialSelection
bool npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_initialSelection private
Referenced by npc_pet_dk_ebon_gargoyleAI(), and UpdateAI().
_selectionTimer
uint32 npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_selectionTimer private
Referenced by InitializeAI(), Reset(), and UpdateAI().
_targetGUID
ObjectGuid npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_targetGUID private
Referenced by AttackStart(), npc_pet_dk_ebon_gargoyleAI(), RemoveTargetAura(), and UpdateAI().