AzerothCore: instance_black_temple::instance_black_temple_InstanceMapScript Struct Reference
instance_black_temple::instance_black_temple_InstanceMapScript Struct Reference
Public Member Functions
instance_black_temple_InstanceMapScript (Map *map)
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
bool SetBossState (uint32 type, EncounterState state) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
GuidSet ashtongueGUIDs
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_black_temple_InstanceMapScript()
instance_black_temple::instance_black_temple_InstanceMapScript::instance_black_temple_InstanceMapScript (Map * map) inline
                                                          : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTERS);
            LoadDoorData(doorData);
            LoadBossBoundaries(boundaries);
            LoadObjectData(creatureData, nullptr);
            LoadSummonData(summonData);
            ashtongueGUIDs.clear();
        }
References ashtongueGUIDs, boundaries, creatureData, DataHeader, doorData, InstanceScript::LoadBossBoundaries(), InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), InstanceScript::LoadSummonData(), MAX_ENCOUNTERS, InstanceScript::SetBossNumber(), InstanceScript::SetHeaders(), and summonData.
Member Function Documentation
OnCreatureCreate()
void instance_black_temple::instance_black_temple_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_ANGERED_SOUL_FRAGMENT:
                case NPC_HUNGERING_SOUL_FRAGMENT:
                case NPC_SUFFERING_SOUL_FRAGMENT:
                    creature->SetCorpseDelay(5);
                    break;
                case NPC_ASHTONGUE_BATTLELORD:
                case NPC_ASHTONGUE_MYSTIC:
                case NPC_ASHTONGUE_STORMCALLER:
                case NPC_ASHTONGUE_PRIMALIST:
                case NPC_ASHTONGUE_FERAL_SPIRIT:
                case NPC_ASHTONGUE_STALKER:
                case NPC_STORM_FURY:
                    if (GetBossState(DATA_SHADE_OF_AKAMA) == DONE)
                        creature->SetFaction(FACTION_ASHTONGUE_DEATHSWORN);
                    else
                        ashtongueGUIDs.insert(creature->GetGUID());
                    break;
                default:
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References ashtongueGUIDs, DATA_SHADE_OF_AKAMA, DONE, FACTION_ASHTONGUE_DEATHSWORN, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), NPC_ANGERED_SOUL_FRAGMENT, NPC_ASHTONGUE_BATTLELORD, NPC_ASHTONGUE_FERAL_SPIRIT, NPC_ASHTONGUE_MYSTIC, NPC_ASHTONGUE_PRIMALIST, NPC_ASHTONGUE_STALKER, NPC_ASHTONGUE_STORMCALLER, NPC_HUNGERING_SOUL_FRAGMENT, NPC_STORM_FURY, NPC_SUFFERING_SOUL_FRAGMENT, InstanceScript::OnCreatureCreate(), Creature::SetCorpseDelay(), and Unit::SetFaction().
OnGameObjectCreate()
void instance_black_temple::instance_black_temple_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            // If created after Illidari Council is done, then skip Akama's event. Used for crashes/reset
            if (go->GetEntry() == GO_ILLIDAN_GATE)
            {
                if (GetBossState(DATA_ILLIDARI_COUNCIL) == DONE)
                {
                    SetBossState(DATA_AKAMA_ILLIDAN, DONE);
                    HandleGameObject(ObjectGuid::Empty, true, go);
                }
            }
            InstanceScript::OnGameObjectCreate(go);
        }
References DATA_AKAMA_ILLIDAN, DATA_ILLIDARI_COUNCIL, DONE, ObjectGuid::Empty, InstanceScript::GetBossState(), Object::GetEntry(), GO_ILLIDAN_GATE, InstanceScript::HandleGameObject(), InstanceScript::OnGameObjectCreate(), and SetBossState().
SetBossState()
bool instance_black_temple::instance_black_temple_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            if (state == DONE)
            {
                switch (type)
                {
                    case DATA_HIGH_WARLORD_NAJENTUS:
                        if (Creature* trigger = GetCreature(DATA_BLACK_TEMPLE_TRIGGER))
                            trigger->AI()->Talk(EMOTE_NAJENTUS_DEFEATED);
                        break;
                    case DATA_SHADE_OF_AKAMA:
                        for (ObjectGuid const& guid : ashtongueGUIDs)
                            if (Creature* ashtongue = instance->GetCreature(guid))
                                ashtongue->SetFaction(FACTION_ASHTONGUE_DEATHSWORN);
                        [[fallthrough]];
                    case DATA_TERON_GOREFIEND:
                    case DATA_GURTOGG_BLOODBOIL:
                    case DATA_RELIQUARY_OF_SOULS:
                        if (AllBossesDone({ DATA_SHADE_OF_AKAMA, DATA_TERON_GOREFIEND, DATA_GURTOGG_BLOODBOIL, DATA_RELIQUARY_OF_SOULS }))
                            if (Creature* trigger = GetCreature(DATA_BLACK_TEMPLE_TRIGGER))
                                trigger->AI()->Talk(EMOTE_LOWER_TEMPLE_DEFEATED);
                        break;
                    case DATA_ILLIDARI_COUNCIL:
                        if (Creature* akama = GetCreature(DATA_AKAMA_ILLIDAN))
                            akama->AI()->DoAction(0);
                        break;
                    default:
                        break;
                }
            }
            return true;
        }
References InstanceScript::AllBossesDone(), ashtongueGUIDs, DATA_AKAMA_ILLIDAN, DATA_BLACK_TEMPLE_TRIGGER, DATA_GURTOGG_BLOODBOIL, DATA_HIGH_WARLORD_NAJENTUS, DATA_ILLIDARI_COUNCIL, DATA_RELIQUARY_OF_SOULS, DATA_SHADE_OF_AKAMA, DATA_TERON_GOREFIEND, DONE, EMOTE_LOWER_TEMPLE_DEFEATED, EMOTE_NAJENTUS_DEFEATED, FACTION_ASHTONGUE_DEATHSWORN, Map::GetCreature(), InstanceScript::GetCreature(), InstanceScript::instance, and InstanceScript::SetBossState().
Referenced by OnGameObjectCreate().
Member Data Documentation
ashtongueGUIDs
GuidSet instance_black_temple::instance_black_temple_InstanceMapScript::ashtongueGUIDs protected
Referenced by instance_black_temple_InstanceMapScript(), OnCreatureCreate(), and SetBossState().