AzeorthCore: instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript Struct Reference
instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript Struct Reference
Public Member Functions
instance_shadow_labyrinth_InstanceMapScript (Map *map)
void Initialize () override
bool IsEncounterInProgress () const override
void OnGameObjectCreate (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void SetData (uint32 type, uint32 uiData) override
uint32 GetData (uint32 type) const override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
ObjectGuid m_uiHellmawGUID
ObjectGuid m_uiRefectoryDoorGUID
ObjectGuid m_uiScreamingHallDoorGUID
uint32 m_uiFelOverseerCount
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Constructor & Destructor Documentation
instance_shadow_labyrinth_InstanceMapScript()
instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::instance_shadow_labyrinth_InstanceMapScript (Map * map) inline
: InstanceScript(map) {}
Member Function Documentation
GetData()
uint32 instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == TYPE_OVERSEER)
                return m_auiEncounter[0];
            return 0;
        }
References m_auiEncounter, and TYPE_OVERSEER.
GetSaveData()
std::string instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
        {
            std::ostringstream saveStream;
            saveStream << "S L " << m_auiEncounter[0] << ' ' << m_auiEncounter[1] << ' '
                       << m_auiEncounter[2] << ' ' << m_auiEncounter[3] << ' ' << m_auiEncounter[4];
            return saveStream.str();
        }
References m_auiEncounter.
Initialize()
void instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
            m_uiFelOverseerCount = 0;
        }
References m_auiEncounter, and m_uiFelOverseerCount.
IsEncounterInProgress()
bool instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                if (m_auiEncounter[i] == IN_PROGRESS)
                    return true;
            return false;
        }
References IN_PROGRESS, m_auiEncounter, and MAX_ENCOUNTER.
Load()
void instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!in)
            {
                OUT_LOAD_INST_DATA_FAIL;
                return;
            }
            OUT_LOAD_INST_DATA(in);
            char dataHead1, dataHead2;
            std::istringstream loadStream(in);
            loadStream >> dataHead1 >> dataHead2;
            if (dataHead1 == 'S' && dataHead2 == 'L')
            {
                for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                {
                    loadStream >> m_auiEncounter[i];
                    if (m_auiEncounter[i] == IN_PROGRESS)
                        m_auiEncounter[i] = NOT_STARTED;
                }
            }
            OUT_LOAD_INST_DATA_COMPLETE;
        }
References IN_PROGRESS, m_auiEncounter, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_FEL_OVERSEER:
                    if (creature->IsAlive())
                        ++m_uiFelOverseerCount;
                    break;
                case NPC_HELLMAW:
                    m_uiHellmawGUID = creature->GetGUID();
                    break;
            }
        }
References Object::GetEntry(), Object::GetGUID(), Unit::IsAlive(), m_uiFelOverseerCount, m_uiHellmawGUID, NPC_FEL_OVERSEER, and NPC_HELLMAW.
OnGameObjectCreate()
void instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case REFECTORY_DOOR:
                    m_uiRefectoryDoorGUID = go->GetGUID();
                    if (m_auiEncounter[DATA_BLACKHEARTTHEINCITEREVENT] == DONE)
                        go->SetGoState(GO_STATE_ACTIVE);
                    break;
                case SCREAMING_HALL_DOOR:
                    m_uiScreamingHallDoorGUID = go->GetGUID();
                    if (m_auiEncounter[DATA_GRANDMASTERVORPILEVENT] == DONE)
                        go->SetGoState(GO_STATE_ACTIVE);
                    break;
            }
        }
References DATA_BLACKHEARTTHEINCITEREVENT, DATA_GRANDMASTERVORPILEVENT, DONE, Object::GetEntry(), Object::GetGUID(), GO_STATE_ACTIVE, m_auiEncounter, m_uiRefectoryDoorGUID, m_uiScreamingHallDoorGUID, REFECTORY_DOOR, SCREAMING_HALL_DOOR, and GameObject::SetGoState().
SetData()
void instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::SetData (uint32 type, uint32 uiData) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case TYPE_OVERSEER:
                    if (!--m_uiFelOverseerCount)
                    {
                        m_auiEncounter[type] = DONE;
                        if (Creature* cr = instance->GetCreature(m_uiHellmawGUID))
                            cr->AI()->DoAction(1);
                    }
                    break;
                case DATA_BLACKHEARTTHEINCITEREVENT:
                    if (uiData == DONE)
                        DoUseDoorOrButton(m_uiRefectoryDoorGUID);
                    m_auiEncounter[type] = uiData;
                    break;
                case DATA_GRANDMASTERVORPILEVENT:
                    if (uiData == DONE)
                        DoUseDoorOrButton(m_uiScreamingHallDoorGUID);
                    m_auiEncounter[type] = uiData;
                    break;
                case DATA_MURMUREVENT:
                case TYPE_HELLMAW:
                    m_auiEncounter[type] = uiData;
                    break;
            }
            if (uiData == DONE)
                SaveToDB();
        }
References DATA_BLACKHEARTTHEINCITEREVENT, DATA_GRANDMASTERVORPILEVENT, DATA_MURMUREVENT, DONE, InstanceScript::DoUseDoorOrButton(), Map::GetCreature(), InstanceScript::instance, m_auiEncounter, m_uiFelOverseerCount, m_uiHellmawGUID, m_uiRefectoryDoorGUID, m_uiScreamingHallDoorGUID, InstanceScript::SaveToDB(), TYPE_HELLMAW, and TYPE_OVERSEER.
Member Data Documentation
m_auiEncounter
uint32 instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::m_auiEncounter[MAX_ENCOUNTER]
Referenced by GetData(), GetSaveData(), Initialize(), IsEncounterInProgress(), Load(), OnGameObjectCreate(), and SetData().
m_uiFelOverseerCount
uint32 instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::m_uiFelOverseerCount
Referenced by Initialize(), OnCreatureCreate(), and SetData().
m_uiHellmawGUID
ObjectGuid instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::m_uiHellmawGUID
Referenced by OnCreatureCreate(), and SetData().
m_uiRefectoryDoorGUID
ObjectGuid instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::m_uiRefectoryDoorGUID
Referenced by OnGameObjectCreate(), and SetData().
m_uiScreamingHallDoorGUID
ObjectGuid instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::m_uiScreamingHallDoorGUID
Referenced by OnGameObjectCreate(), and SetData().