AzerothCore: npc_stable_master::npc_stable_masterAI Struct Reference
npc_stable_master::npc_stable_masterAI Struct Reference
Public Member Functions
npc_stable_masterAI (Creature *creature)
void sGossipSelect (Player *player, uint32 menuId, uint32 gossipListId) override
Public Member Functions inherited from SmartAI
~SmartAI () override
SmartAI (Creature *c)
bool IsAIControlled () const
void StartPath (bool run=false, uint32 path=0, bool repeat=false, Unit *invoker=nullptr)
bool LoadPath (uint32 entry)
void PausePath (uint32 delay, bool forced=false)
void StopPath (uint32 DespawnTime=0, uint32 quest=0, bool fail=false)
void EndPath (bool fail=false)
void ResumePath ()
WayPoint * GetNextWayPoint ()
void GenerateWayPointArray (Movement::PointsArray *points)
bool HasEscortState (uint32 uiEscortState)
void AddEscortState (uint32 uiEscortState)
bool IsEscorted () override
void RemoveEscortState (uint32 uiEscortState)
void SetAutoAttack (bool on)
void SetCombatMove (bool on, float chaseRange=0.0f)
bool CanCombatMove ()
void SetFollow (Unit *target, float dist=0.0f, float angle=0.0f, uint32 credit=0, uint32 end=0, uint32 creditType=0, bool aliveState=true)
void StopFollow (bool complete)
void MoveAway (float distance)
void SetScript9 (SmartScriptHolder &e, uint32 entry, WorldObject *invoker)
SmartScript * GetScript ()
bool IsEscortInvokerInRange ()
void JustRespawned () override
void JustReachedHome () override
void JustEngagedWith (Unit *enemy) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *killer) override
void KilledUnit (Unit *victim) override
void JustSummoned (Creature *creature) override
void SummonedCreatureDies (Creature *summon, Unit *killer) override
void SummonedCreatureEvade (Creature *summon) override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void SpellHit (Unit *unit, SpellInfo const *spellInfo) override
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
void DamageTaken (Unit *done_by, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void HealReceived (Unit *doneBy, uint32 &addhealth) override
Called when the creature receives heal.
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ReceiveEmote (Player *player, uint32 textEmote) override
void MovementInform (uint32 MovementType, uint32 Data) override
void IsSummonedBy (WorldObject *summoner) override
void DamageDealt (Unit *doneTo, uint32 &damage, DamageEffectType damagetyp) override
Called at any Damage to any victim (before damage apply)
void SummonedCreatureDespawn (Creature *unit) override
void CorpseRemoved (uint32 &respawnDelay) override
== Triggered Actions Requested ==================
void PassengerBoarded (Unit *who, int8 seatId, bool apply) override
== Fields =======================================
void InitializeAI () override
void OnCharmed (bool apply) override
Called when unit is charmed.
bool CanAIAttack (Unit const *who) const override
void DoAction (int32 param=0) override
uint32 GetData (uint32 id=0) const override
void SetData (uint32 id, uint32 value) override
void SetData (uint32 id, uint32 value, WorldObject *invoker)
void SetGUID (ObjectGuid guid, int32 id=0) override
ObjectGuid GetGUID (int32 id=0) const override
void MovepointReached (uint32 id)
void SetRun (bool run=true)
void SetFly (bool fly=true)
void SetSwim (bool swim=true)
void SetEvadeDisabled (bool disable=true)
void SetInvincibilityHpLevel (uint32 level)
void sGossipHello (Player *player) override
void sGossipSelect (Player *player, uint32 sender, uint32 action) override
void sGossipSelectCode (Player *player, uint32 sender, uint32 action, const char *code) override
void sQuestAccept (Player *player, Quest const *quest) override
void sQuestReward (Player *player, Quest const *quest, uint32 opt) override
void sOnGameEvent (bool start, uint16 eventId) override
void SetDespawnTime (uint32 t)
void StartDespawn ()
void OnSpellClick (Unit *clicker, bool &result) override
void PathEndReached (uint32 pathId) override
bool CanRespawn () override
void SetCanRespawn (bool canSpawn)
void SetWPPauseTimer (uint32 time)
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from SmartAI
static int32 Permissible (Creature const *)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from SmartAI
uint32 mEscortQuestID
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_stable_masterAI()
npc_stable_master::npc_stable_masterAI::npc_stable_masterAI (Creature * creature) inline
: SmartAI(creature) { }
Member Function Documentation
sGossipSelect()
void npc_stable_master::npc_stable_masterAI::sGossipSelect (Player * player, uint32 menuId, uint32 gossipListId) inline override virtual
Reimplemented from SmartAI.
        {
            SmartAI::sGossipSelect(player, menuId, gossipListId);
            if (menuId != STABLE_MASTER_GOSSIP_SUB_MENU)
                return;
            switch (gossipListId)
            {
                case 0:
                    player->CastSpell(player, SPELL_MINIWING, false);
                    break;
                case 1:
                    player->CastSpell(player, SPELL_JUBLING, false);
                    break;
                case 2:
                    player->CastSpell(player, SPELL_DARTER, false);
                    break;
                case 3:
                    player->CastSpell(player, SPELL_WORG, false);
                    break;
                case 4:
                    player->CastSpell(player, SPELL_SMOLDERWEB, false);
                    break;
                case 5:
                    player->CastSpell(player, SPELL_CHIKEN, false);
                    break;
                case 6:
                    player->CastSpell(player, SPELL_WOLPERTINGER, false);
                    break;
                default:
                    return;
            }
            player->PlayerTalkClass->SendCloseGossip();
        }
References Unit::CastSpell(), Player::PlayerTalkClass, PlayerMenu::SendCloseGossip(), SmartAI::sGossipSelect(), SPELL_CHIKEN, SPELL_DARTER, SPELL_JUBLING, SPELL_MINIWING, SPELL_SMOLDERWEB, SPELL_WOLPERTINGER, SPELL_WORG, and STABLE_MASTER_GOSSIP_SUB_MENU.