AzeorthCore: AchievementScript Class Reference
AchievementScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void SetRealmCompleted (AchievementEntry const *)
virtual bool IsCompletedCriteria (AchievementMgr *, AchievementCriteriaEntry const *, AchievementEntry const *, CriteriaProgress const *)
virtual bool IsRealmCompleted (AchievementGlobalMgr const *, AchievementEntry const *, SystemTimePoint)
virtual void OnBeforeCheckCriteria (AchievementMgr *, AchievementCriteriaEntryList const *)
virtual bool CanCheckCriteria (AchievementMgr *, AchievementCriteriaEntry const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
AchievementScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
AchievementScript()
AchievementScript::AchievementScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<AchievementScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanCheckCriteria()
virtual bool AchievementScript::CanCheckCriteria (AchievementMgr * , AchievementCriteriaEntry const *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanCheckCriteria().
IsCompletedCriteria()
virtual bool AchievementScript::IsCompletedCriteria (AchievementMgr * , AchievementCriteriaEntry const * , AchievementEntry const * , CriteriaProgress const *) inline virtual
{ return true; }
Referenced by ScriptMgr::IsCompletedCriteria().
IsDatabaseBound()
bool AchievementScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
IsRealmCompleted()
virtual bool AchievementScript::IsRealmCompleted (AchievementGlobalMgr const * , AchievementEntry const * , SystemTimePoint) inline virtual
{ return true; }
Referenced by ScriptMgr::IsRealmCompleted().
OnBeforeCheckCriteria()
virtual void AchievementScript::OnBeforeCheckCriteria (AchievementMgr * , AchievementCriteriaEntryList const *) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeCheckCriteria().
SetRealmCompleted()
virtual void AchievementScript::SetRealmCompleted (AchievementEntry const *) inline virtual
{ }
Referenced by ScriptMgr::SetRealmCompleted().