AzerothCore: npc_still_at_it_trigger::npc_still_at_it_triggerAI Struct Reference
npc_still_at_it_trigger::npc_still_at_it_triggerAI Struct Reference
Public Member Functions
npc_still_at_it_triggerAI (Creature *pCreature)
Creature * GetManus ()
void Reset () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void Start ()
void CheckAction (uint8 a, ObjectGuid guid)
void SpellHit (Unit *caster, SpellInfo const *spellInfo) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
bool running
bool success
ObjectGuid playerGUID
ObjectGuid thunderbrewGUID
int32 tensecstimer
int32 timer
uint8 stepcount
uint8 currentstep
uint8 expectedaction
uint8 playeraction
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_still_at_it_triggerAI()
npc_still_at_it_trigger::npc_still_at_it_triggerAI::npc_still_at_it_triggerAI (Creature * pCreature) inline
: NullCreatureAI(pCreature) {}
Member Function Documentation
CheckAction()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::CheckAction (uint8 a, ObjectGuid guid) inline
        {
            if (guid != playerGUID)
                return;
            if (a == expectedaction)
            {
                currentstep++;
                if (Creature* th = ObjectAccessor::GetCreature(*me, thunderbrewGUID))
                    th->HandleEmoteCommand(EMOTE_ONESHOT_CHEER_NO_SHEATHE);
                GetManus()->AI()->Talk(SAY_MANUS_WELL_DONE);
                if (currentstep >= stepcount)
                {
                    GetManus()->AI()->Talk(SAY_MANUS_WELL_DONE);
                    success = true;
                    timer = 3000;
                }
                else
                {
                    expectedaction = 0;
                    timer = 3000;
                }
            }
            else
            {
                GetManus()->AI()->Talk(SAY_MANUS_FAILED);
                Reset();
            }
        }
References Creature::AI(), currentstep, EMOTE_ONESHOT_CHEER_NO_SHEATHE, expectedaction, ObjectAccessor::GetCreature(), GetManus(), CreatureAI::me, playerGUID, Reset(), SAY_MANUS_FAILED, SAY_MANUS_WELL_DONE, stepcount, success, CreatureAI::Talk(), thunderbrewGUID, and timer.
Referenced by SpellHit().
DamageTaken()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
        {
            damage = 0;
        }
GetManus()
Creature * npc_still_at_it_trigger::npc_still_at_it_triggerAI::GetManus () inline
{return ObjectAccessor::GetCreature(*me, thunderbrewGUID);}
References ObjectAccessor::GetCreature(), CreatureAI::me, and thunderbrewGUID.
Referenced by CheckAction(), Start(), and UpdateAI().
Reset()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            running = false;
            success = false;
            playerGUID.Clear();
            thunderbrewGUID.Clear();
            tensecstimer = 0;
            timer = 0;
            stepcount = 0;
            currentstep = 0;
            expectedaction = 0;
            playeraction = 0;
        }
References ObjectGuid::Clear(), currentstep, expectedaction, playeraction, playerGUID, running, stepcount, success, tensecstimer, thunderbrewGUID, and timer.
Referenced by CheckAction(), and UpdateAI().
SpellHit()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::SpellHit (Unit * caster, SpellInfo const * spellInfo) inline override virtual
Reimplemented from CreatureAI.
        {
            if (running)
            {
                uint8 a = 0;
                switch (spellInfo->Id)
                {
                    case 51931:
                        a = 4;
                        break;
                    case 51932:
                        a = 3;
                        break;
                    case 51933:
                        a = 5;
                        break;
                }
                CheckAction(a, caster->GetGUID());
            }
        }
References CheckAction(), and running.
Start()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::Start () inline
        {
            timer = 5000;
            running = true;
            stepcount = urand(5, 10);
            GetManus()->AI()->Talk(SAY_MANUS_START);
        }
References Creature::AI(), GetManus(), running, SAY_MANUS_START, stepcount, CreatureAI::Talk(), timer, and urand().
UpdateAI()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
        {
            if (running)
            {
                if (timer)
                {
                    timer -= diff;
                    if (timer < 0)
                        timer = 0;
                }
                else if (success)
                {
                    GetManus()->AI()->Talk(SAY_MANUS_END);
                    me->SummonGameObject(190643, 5546.55f, 5768.0f, -78.03f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0);
                    Reset();
                }
                else if (expectedaction != 0) // didn't make it in 10 seconds
                {
                    GetManus()->AI()->Talk(SAY_MANUS_FAILED);
                    Reset();
                }
                else // it's time to rand next move
                {
                    expectedaction = urand(1, 5);
                    switch (expectedaction)
                    {
                        case 1:
                            GetManus()->AI()->Talk(SAY_MANUS_PRESSUE);
                            break;
                        case 2:
                            GetManus()->AI()->Talk(SAY_MANUS_HEAT);
                            break;
                        case 3:
                            GetManus()->AI()->Talk(SAY_MANUS_BANANA);
                            break;
                        case 4:
                            GetManus()->AI()->Talk(SAY_MANUS_ORANGE);
                            break;
                        case 5:
                            GetManus()->AI()->Talk(SAY_MANUS_PAPAYA);
                            break;
                    }
                    timer = 10000;
                }
            }
        }
References Creature::AI(), expectedaction, GetManus(), CreatureAI::me, Reset(), running, SAY_MANUS_BANANA, SAY_MANUS_END, SAY_MANUS_FAILED, SAY_MANUS_HEAT, SAY_MANUS_ORANGE, SAY_MANUS_PAPAYA, SAY_MANUS_PRESSUE, success, WorldObject::SummonGameObject(), CreatureAI::Talk(), timer, and urand().
Member Data Documentation
currentstep
uint8 npc_still_at_it_trigger::npc_still_at_it_triggerAI::currentstep
Referenced by CheckAction(), and Reset().
expectedaction
uint8 npc_still_at_it_trigger::npc_still_at_it_triggerAI::expectedaction
Referenced by CheckAction(), Reset(), and UpdateAI().
playeraction
uint8 npc_still_at_it_trigger::npc_still_at_it_triggerAI::playeraction
Referenced by Reset().
playerGUID
ObjectGuid npc_still_at_it_trigger::npc_still_at_it_triggerAI::playerGUID
Referenced by CheckAction(), and Reset().
running
bool npc_still_at_it_trigger::npc_still_at_it_triggerAI::running
Referenced by Reset(), SpellHit(), Start(), and UpdateAI().
stepcount
uint8 npc_still_at_it_trigger::npc_still_at_it_triggerAI::stepcount
Referenced by CheckAction(), Reset(), and Start().
success
bool npc_still_at_it_trigger::npc_still_at_it_triggerAI::success
Referenced by CheckAction(), Reset(), and UpdateAI().
tensecstimer
int32 npc_still_at_it_trigger::npc_still_at_it_triggerAI::tensecstimer
Referenced by Reset().
thunderbrewGUID
ObjectGuid npc_still_at_it_trigger::npc_still_at_it_triggerAI::thunderbrewGUID
Referenced by CheckAction(), GetManus(), and Reset().
timer
int32 npc_still_at_it_trigger::npc_still_at_it_triggerAI::timer
Referenced by CheckAction(), Reset(), Start(), and UpdateAI().