AzerothCore: spell_oculus_rider_aura Class Reference
spell_oculus_rider_aura Class Reference
Private Member Functions
PrepareAuraScript (spell_oculus_rider_aura)
bool Validate (SpellInfo const *) override
void HandleOnEffectApply (AuraEffect const *aurEff, AuraEffectHandleModes)
void HandleOnEffectRemove (AuraEffect const *, AuraEffectHandleModes)
void Register () override
Private Attributes
ObjectGuid _drakeGUID
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleOnEffectApply()
void spell_oculus_rider_aura::HandleOnEffectApply (AuraEffect const * aurEff, AuraEffectHandleModes) inline private
    {
        Unit* caster = GetCaster();
        if (!caster)
            return;
        Creature* drake = caster->GetVehicleCreatureBase();
        if (!drake)
            return;
        switch (aurEff->GetEffIndex())
        {
            case EFFECT_1:
                _drakeGUID = drake->GetGUID();
                caster->AddAura(SPELL_DRAKE_FLAG_VISUAL, caster);
                caster->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                caster->RemoveAurasByType(SPELL_AURA_MOD_SHAPESHIFT);
                drake->CastSpell(drake, SPELL_SOAR_TRIGGER);
                if (drake->GetEntry() == NPC_RUBY_DRAKE)
                    drake->CastSpell(drake, SPELL_RUBY_EVASIVE_AURA);
                break;
            case EFFECT_2:
                caster->AddAura(SPELL_SCALE_STATS, drake);
                PreventDefaultAction();
                break;
        }
    }
References _drakeGUID, Unit::AddAura(), Unit::CastSpell(), EFFECT_1, EFFECT_2, AuraScript::GetCaster(), AuraEffect::GetEffIndex(), Object::GetEntry(), Object::GetGUID(), Unit::GetVehicleCreatureBase(), NPC_RUBY_DRAKE, AuraScript::PreventDefaultAction(), Unit::RemoveAurasByType(), Unit::SetUnitFlag(), SPELL_AURA_MOD_SHAPESHIFT, SPELL_DRAKE_FLAG_VISUAL, SPELL_RUBY_EVASIVE_AURA, SPELL_SCALE_STATS, SPELL_SOAR_TRIGGER, and UNIT_FLAG_NON_ATTACKABLE.
Referenced by Register().
HandleOnEffectRemove()
void spell_oculus_rider_aura::HandleOnEffectRemove (AuraEffect const * , AuraEffectHandleModes) inline private
    {
        Unit* caster = GetCaster();
        if (!caster)
            return;
        Creature* drake = ObjectAccessor::GetCreature(*caster, _drakeGUID);
        if (drake)
        {
            drake->RemoveUnitFlag(UNIT_FLAG_POSSESSED);
            drake->RemoveAurasDueToSpell(GetId());
            drake->RemoveAurasDueToSpell(SPELL_SOAR_TRIGGER);
            drake->RemoveAurasDueToSpell(SPELL_RUBY_EVASIVE_AURA);
        }
        caster->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
        caster->RemoveAurasDueToSpell(SPELL_DRAKE_FLAG_VISUAL);
    }
References _drakeGUID, AuraScript::GetCaster(), ObjectAccessor::GetCreature(), AuraScript::GetId(), Unit::RemoveAurasDueToSpell(), Unit::RemoveUnitFlag(), SPELL_DRAKE_FLAG_VISUAL, SPELL_RUBY_EVASIVE_AURA, SPELL_SOAR_TRIGGER, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_POSSESSED.
Referenced by Register().
PrepareAuraScript()
spell_oculus_rider_aura::PrepareAuraScript (spell_oculus_rider_aura) private
Register()
void spell_oculus_rider_aura::Register () inline override private virtual
Implements _SpellScript.
    {
        OnEffectApply += AuraEffectApplyFn(spell_oculus_rider_aura::HandleOnEffectApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
        OnEffectApply += AuraEffectApplyFn(spell_oculus_rider_aura::HandleOnEffectApply, EFFECT_2, SPELL_AURA_LINKED, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
        OnEffectRemove += AuraEffectRemoveFn(spell_oculus_rider_aura::HandleOnEffectRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
    }
References AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK, AuraEffectApplyFn, AuraEffectRemoveFn, EFFECT_1, EFFECT_2, HandleOnEffectApply(), HandleOnEffectRemove(), AuraScript::OnEffectApply, AuraScript::OnEffectRemove, SPELL_AURA_DUMMY, and SPELL_AURA_LINKED.
Validate()
bool spell_oculus_rider_aura::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo({ SPELL_SOAR_TRIGGER, SPELL_RUBY_EVASIVE_AURA, SPELL_DRAKE_FLAG_VISUAL });
    }
References SPELL_DRAKE_FLAG_VISUAL, SPELL_RUBY_EVASIVE_AURA, SPELL_SOAR_TRIGGER, and _SpellScript::ValidateSpellInfo().
Member Data Documentation
_drakeGUID
ObjectGuid spell_oculus_rider_aura::_drakeGUID private
Referenced by HandleOnEffectApply(), and HandleOnEffectRemove().