AzerothCore: BattlegroundScore Struct Reference
BattlegroundScore Struct Reference abstract
#include "BattlegroundScore.h"
Protected Member Functions
BattlegroundScore (ObjectGuid playerGuid)
virtual ~BattlegroundScore ()=default
virtual void UpdateScore (uint32 type, uint32 value)
virtual void AppendToPacket (WorldPacket &data)
virtual void BuildObjectivesBlock (WorldPacket &)=0
virtual std::string ToString () const
uint32 GetKillingBlows () const
uint32 GetDeaths () const
uint32 GetHonorableKills () const
uint32 GetBonusHonor () const
uint32 GetDamageDone () const
uint32 GetHealingDone () const
virtual uint32 GetAttr1 () const
virtual uint32 GetAttr2 () const
virtual uint32 GetAttr3 () const
virtual uint32 GetAttr4 () const
virtual uint32 GetAttr5 () const
Protected Attributes
ObjectGuid PlayerGuid
uint32 KillingBlows = 0
uint32 Deaths = 0
uint32 HonorableKills = 0
uint32 BonusHonor = 0
uint32 DamageDone = 0
uint32 HealingDone = 0
Friends
class Arena
class Battleground
Detailed Description
Constructor & Destructor Documentation
BattlegroundScore()
BattlegroundScore::BattlegroundScore (ObjectGuid playerGuid) inline protected
: PlayerGuid(playerGuid) { }
~BattlegroundScore()
virtual BattlegroundScore::~BattlegroundScore () protected virtual default
Member Function Documentation
AppendToPacket()
void BattlegroundScore::AppendToPacket (WorldPacket & data) protected virtual
Reimplemented in ArenaScore.
{
    data << PlayerGuid;
    data << uint32(KillingBlows);
    data << uint32(HonorableKills);
    data << uint32(Deaths);
    data << uint32(BonusHonor);
    data << uint32(DamageDone);
    data << uint32(HealingDone);
    BuildObjectivesBlock(data);
}
References BonusHonor, BuildObjectivesBlock(), DamageDone, Deaths, HealingDone, HonorableKills, KillingBlows, and PlayerGuid.
BuildObjectivesBlock()
virtual void BattlegroundScore::BuildObjectivesBlock (WorldPacket &) protected pure virtual
Implemented in ArenaScore, BattlegroundABScore, BattlegroundAVScore, BattlegroundEYScore, BattlegroundICScore, BattlegroundSAScore, and BattlegroundWGScore.
Referenced by AppendToPacket().
GetAttr1()
virtual uint32 BattlegroundScore::GetAttr1 () const inline protected virtual
Reimplemented in BattlegroundAVScore, BattlegroundABScore, BattlegroundEYScore, BattlegroundICScore, BattlegroundSAScore, and BattlegroundWGScore.
{ return 0; }
GetAttr2()
virtual uint32 BattlegroundScore::GetAttr2 () const inline protected virtual
Reimplemented in BattlegroundAVScore, BattlegroundABScore, BattlegroundICScore, BattlegroundSAScore, and BattlegroundWGScore.
{ return 0; }
GetAttr3()
virtual uint32 BattlegroundScore::GetAttr3 () const inline protected virtual
Reimplemented in BattlegroundAVScore.
{ return 0; }
GetAttr4()
virtual uint32 BattlegroundScore::GetAttr4 () const inline protected virtual
Reimplemented in BattlegroundAVScore.
{ return 0; }
GetAttr5()
virtual uint32 BattlegroundScore::GetAttr5 () const inline protected virtual
Reimplemented in BattlegroundAVScore.
{ return 0; }
GetBonusHonor()
uint32 BattlegroundScore::GetBonusHonor () const inline protected
{ return BonusHonor; }
GetDamageDone()
uint32 BattlegroundScore::GetDamageDone () const inline protected
{ return DamageDone; }
GetDeaths()
uint32 BattlegroundScore::GetDeaths () const inline protected
{ return Deaths; }
GetHealingDone()
uint32 BattlegroundScore::GetHealingDone () const inline protected
{ return HealingDone; }
GetHonorableKills()
uint32 BattlegroundScore::GetHonorableKills () const inline protected
{ return HonorableKills; }
GetKillingBlows()
uint32 BattlegroundScore::GetKillingBlows () const inline protected
{ return KillingBlows; }
ToString()
virtual std::string BattlegroundScore::ToString () const inline protected virtual
Reimplemented in ArenaScore.
{ return ""; }
UpdateScore()
virtual void BattlegroundScore::UpdateScore (uint32 type, uint32 value) inline protected virtual
Reimplemented in BattlegroundABScore, BattlegroundAVScore, BattlegroundEYScore, BattlegroundICScore, BattlegroundSAScore, and BattlegroundWGScore.
    {
        switch (type)
        {
            case SCORE_KILLING_BLOWS:   // Killing blows
                KillingBlows += value;
                break;
            case SCORE_DEATHS:          // Deaths
                Deaths += value;
                break;
            case SCORE_HONORABLE_KILLS: // Honorable kills
                HonorableKills += value;
                break;
            case SCORE_BONUS_HONOR:     // Honor bonus
                BonusHonor += value;
                break;
            case SCORE_DAMAGE_DONE:     // Damage Done
                DamageDone += value;
                break;
            case SCORE_HEALING_DONE:    // Healing Done
                HealingDone += value;
                break;
            default:
                ABORT("Not implemented Battleground score type!");
                break;
        }
    }
References ABORT, SCORE_BONUS_HONOR, SCORE_DAMAGE_DONE, SCORE_DEATHS, SCORE_HEALING_DONE, SCORE_HONORABLE_KILLS, and SCORE_KILLING_BLOWS.
Referenced by BattlegroundABScore::UpdateScore(), BattlegroundAVScore::UpdateScore(), BattlegroundEYScore::UpdateScore(), BattlegroundICScore::UpdateScore(), BattlegroundSAScore::UpdateScore(), and BattlegroundWGScore::UpdateScore().
Friends And Related Function Documentation
Arena
friend class Arena friend
Battleground
friend class Battleground friend
Member Data Documentation
BonusHonor
uint32 BattlegroundScore::BonusHonor = 0 protected
Referenced by AppendToPacket().
DamageDone
uint32 BattlegroundScore::DamageDone = 0 protected
Referenced by AppendToPacket(), and ArenaScore::AppendToPacket().
Deaths
uint32 BattlegroundScore::Deaths = 0 protected
Referenced by AppendToPacket().
HealingDone
uint32 BattlegroundScore::HealingDone = 0 protected
Referenced by AppendToPacket(), and ArenaScore::AppendToPacket().
HonorableKills
uint32 BattlegroundScore::HonorableKills = 0 protected
Referenced by AppendToPacket().
KillingBlows
uint32 BattlegroundScore::KillingBlows = 0 protected
Referenced by AppendToPacket(), and ArenaScore::AppendToPacket().
PlayerGuid
ObjectGuid BattlegroundScore::PlayerGuid protected
Referenced by AppendToPacket(), and ArenaScore::AppendToPacket().