AzerothCore: npc_vortex_ride::npc_vortex_rideAI Struct Reference
npc_vortex_ride::npc_vortex_rideAI Struct Reference
Public Member Functions
npc_vortex_rideAI (Creature *pCreature)
void PassengerBoarded (Unit *pass, int8, bool apply) override
== Fields =======================================
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void AttackStart (Unit *) override
void MoveInLineOfSight (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
uint32 timer
uint32 despawnTimer
bool bUpdatedFlying
float VORTEX_RADIUS
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from VehicleAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_vortex_rideAI()
npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI (Creature * pCreature) inline
                                               : VehicleAI(pCreature)
        {
            VORTEX_RADIUS = urand(22, 28);
            float h = urand(15, 30);
            float angle = CenterPos.GetAngle(me);
            Position pos;
            pos.m_positionX = CenterPos.GetPositionX() + VORTEX_RADIUS * cos(angle);
            pos.m_positionY = CenterPos.GetPositionY() + VORTEX_RADIUS * std::sin(angle);
            pos.m_positionZ = CenterPos.GetPositionZ() + h;
            pos.SetOrientation(pos.GetAngle(&CenterPos));
            me->SetPosition(pos);
            timer = 0;
            despawnTimer = 9500;
            bUpdatedFlying = false;
        }
References bUpdatedFlying, CenterPos, despawnTimer, Position::GetAngle(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Position::m_positionX, Position::m_positionY, Position::m_positionZ, CreatureAI::me, Position::SetOrientation(), Creature::SetPosition(), timer, urand(), and VORTEX_RADIUS.
Member Function Documentation
AttackStart()
void npc_vortex_ride::npc_vortex_rideAI::AttackStart (Unit *) inline override virtual
Reimplemented from VehicleAI.
{}
DamageTaken()
void npc_vortex_ride::npc_vortex_rideAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
{ damage = 0; }
MoveInLineOfSight()
void npc_vortex_ride::npc_vortex_rideAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from VehicleAI.
{}
PassengerBoarded()
void npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
        {
            if (pass && !apply && pass->IsPlayer())
            {
                Player* plr = pass->ToPlayer();
                float speed = plr->GetDistance(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()) / (1.0f * 0.001f);
                plr->MonsterMoveWithSpeed(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), speed);
                plr->RemoveAura(SPELL_FREEZE_ANIM);
                plr->SetDisableGravity(false, true);
                plr->SetGuidValue(PLAYER_FARSIGHT, ObjectGuid::Empty);
                sScriptMgr->AnticheatSetCanFlybyServer(plr, false);
                sScriptMgr->AnticheatSetUnderACKmount(plr);
            }
        }
References ObjectGuid::Empty, WorldObject::GetDistance(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::IsPlayer(), CreatureAI::me, Unit::MonsterMoveWithSpeed(), PLAYER_FARSIGHT, Unit::RemoveAura(), Player::SetDisableGravity(), Object::SetGuidValue(), SPELL_FREEZE_ANIM, sScriptMgr, and Object::ToPlayer().
UpdateAI()
void npc_vortex_ride::npc_vortex_rideAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from VehicleAI.
        {
            /*      here: if player has some aura that should make him exit vehicle (eg. ice block) -> exit
                    or make it another way (dunno how)                                                          */
            if (despawnTimer <= diff)
            {
                despawnTimer = 0;
                me->UpdatePosition(CenterPos.GetPositionX(), CenterPos.GetPositionY(), CenterPos.GetPositionZ() + 18.0f, 0.0f, true);
                me->StopMovingOnCurrentPos();
                if (Vehicle* vehicle = me->GetVehicleKit())
                    vehicle->RemoveAllPassengers();
                me->DespawnOrUnsummon();
                return;
            }
            else
                despawnTimer -= diff;
            if (timer <= diff)
            {
                float angle = CenterPos.GetAngle(me);
                float newangle = angle + 2 * M_PI / ((float)VORTEX_TRAVEL_TIME / VORTEX_DEFAULT_DIFF);
                if (newangle >= 2 * M_PI)
                    newangle -= 2 * M_PI;
                float newx = CenterPos.GetPositionX() + VORTEX_RADIUS * cos(newangle);
                float newy = CenterPos.GetPositionY() + VORTEX_RADIUS * std::sin(newangle);
                float arcangle = me->GetAngle(newx, newy);
                float dist = 2 * me->GetDistance2d(newx, newy);
                if (me->GetVehicleKit()) if (Unit* pass = me->GetVehicleKit()->GetPassenger(0)) if (Player* plr = pass->ToPlayer())
{
                            if (!bUpdatedFlying && timer)
{
                                bUpdatedFlying = true;
                                plr->SetDisableGravity(true, true);
                                sScriptMgr->AnticheatSetCanFlybyServer(plr, true);
                                sScriptMgr->AnticheatSetUnderACKmount(plr);
                            }
                            plr->SendMonsterMove(me->GetPositionX() + dist * cos(arcangle), me->GetPositionY() + dist * std::sin(arcangle), me->GetPositionZ(), VORTEX_DEFAULT_DIFF * 2, SPLINEFLAG_FLYING);
                            me->Relocate(newx, newy);
                        }
                timer = (diff - timer <= VORTEX_DEFAULT_DIFF) ? VORTEX_DEFAULT_DIFF - (diff - timer) : 0;
            }
            else
                timer -= diff;
        }
References bUpdatedFlying, CenterPos, Creature::DespawnOrUnsummon(), despawnTimer, Position::GetAngle(), WorldObject::GetDistance2d(), Vehicle::GetPassenger(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicleKit(), CreatureAI::me, Position::Relocate(), SPLINEFLAG_FLYING, sScriptMgr, Unit::StopMovingOnCurrentPos(), timer, Object::ToPlayer(), Unit::UpdatePosition(), VORTEX_DEFAULT_DIFF, VORTEX_RADIUS, and VORTEX_TRAVEL_TIME.
Member Data Documentation
bUpdatedFlying
bool npc_vortex_ride::npc_vortex_rideAI::bUpdatedFlying
Referenced by npc_vortex_rideAI(), and UpdateAI().
despawnTimer
uint32 npc_vortex_ride::npc_vortex_rideAI::despawnTimer
Referenced by npc_vortex_rideAI(), and UpdateAI().
timer
uint32 npc_vortex_ride::npc_vortex_rideAI::timer
Referenced by npc_vortex_rideAI(), and UpdateAI().
VORTEX_RADIUS
float npc_vortex_ride::npc_vortex_rideAI::VORTEX_RADIUS
Referenced by npc_vortex_rideAI(), and UpdateAI().