AzerothCore: azerothcore-wotlk/src/server/game/Instances/InstanceScript.cpp File Reference
InstanceScript.cpp File Reference
#include "InstanceScript.h"
#include "Chat.h"
#include "Creature.h"
#include "DatabaseEnv.h"
#include "GameObject.h"
#include "Group.h"
#include "InstanceSaveMgr.h"
#include "LFGMgr.h"
#include "Log.h"
#include "Map.h"
#include "Opcodes.h"
#include "Pet.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "Spell.h"
#include "WorldSession.h"
Functions
bool InstanceHasScript (WorldObject const *obj, char const *scriptName)
Function Documentation
InstanceHasScript()
bool InstanceHasScript (WorldObject const * obj, char const * scriptName)
{
    if (InstanceMap* instance = obj->GetMap()->ToInstanceMap())
    {
        return instance->GetScriptName() == scriptName;
    }
    return false;
}
References WorldObject::GetMap(), and Map::ToInstanceMap().
Referenced by GetInstanceAI().