AzerothCore: MapScript< TMap > Class Template Reference
MapScript< TMap > Class Template Reference
#include "ScriptObject.h"
Public Member Functions
void checkMap ()
MapEntry const * GetEntry ()
virtual void OnCreate (TMap *)
virtual void OnDestroy (TMap *)
virtual void OnLoadGridMap (TMap *, GridMap *, uint32, uint32)
virtual void OnUnloadGridMap (TMap *, GridMap *, uint32, uint32)
virtual void OnPlayerEnter (TMap *, Player *)
virtual void OnPlayerLeave (TMap *, Player *)
void OnUpdate (TMap *, uint32) override
virtual void OnUpdate (TMap *, uint32)
Protected Member Functions
MapScript (uint32 mapId)
Protected Member Functions inherited from UpdatableScript< TMap >
UpdatableScript ()=default
Private Attributes
MapEntry const * _mapEntry
uint32 _mapId
Detailed Description
template<class TMap>
class MapScript< TMap >
Constructor & Destructor Documentation
MapScript()
template<class TMap > MapScript< TMap >::MapScript (uint32 mapId) inline explicit protected
: _mapId(mapId) { }
Member Function Documentation
checkMap()
template<class TMap > void MapScript< TMap >::checkMap
{
    _mapEntry = sMapStore.LookupEntry(_mapId);
    if (!_mapEntry)
        LOG_ERROR("maps.script", "Invalid MapScript for {}; no such map ID.", _mapId);
}
References LOG_ERROR, and sMapStore.
GetEntry()
template<class TMap > MapEntry const * MapScript< TMap >::GetEntry () inline
{ return _mapEntry; }
References MapScript< TMap >::_mapEntry.
OnCreate()
template<class TMap > virtual void MapScript< TMap >::OnCreate (TMap *) inline virtual
{ }
Referenced by ScriptMgr::OnCreateMap().
OnDestroy()
template<class TMap > virtual void MapScript< TMap >::OnDestroy (TMap *) inline virtual
{ }
Referenced by ScriptMgr::OnDestroyMap().
OnLoadGridMap()
template<class TMap > virtual void MapScript< TMap >::OnLoadGridMap (TMap * , GridMap * , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnLoadGridMap().
OnPlayerEnter()
template<class TMap > virtual void MapScript< TMap >::OnPlayerEnter (TMap * , Player *) inline virtual
{ }
OnPlayerLeave()
template<class TMap > virtual void MapScript< TMap >::OnPlayerLeave (TMap * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerLeaveMap().
OnUnloadGridMap()
template<class TMap > virtual void MapScript< TMap >::OnUnloadGridMap (TMap * , GridMap * , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnUnloadGridMap().
OnUpdate()
template<class TMap > void MapScript< TMap >::OnUpdate (TMap * , uint32) inline override virtual
Reimplemented from UpdatableScript< TMap >.
{ }
Referenced by ScriptMgr::OnMapUpdate().
Member Data Documentation
_mapEntry
template<class TMap > MapEntry const* MapScript< TMap >::_mapEntry private
Referenced by MapScript< TMap >::GetEntry().
_mapId
template<class TMap > uint32 MapScript< TMap >::_mapId private