AzerothCore: GuildScript Class Reference
GuildScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnAddMember (Guild *, Player *, uint8 &)
virtual void OnRemoveMember (Guild *, Player *, bool, bool)
virtual void OnMOTDChanged (Guild *, const std::string &)
virtual void OnInfoChanged (Guild *, const std::string &)
virtual void OnCreate (Guild *, Player *, const std::string &)
virtual void OnDisband (Guild *)
virtual void OnMemberWitdrawMoney (Guild *, Player *, uint32 &, bool)
virtual void OnMemberDepositMoney (Guild *, Player *, uint32 &)
virtual void OnItemMove (Guild *, Player *, Item *, bool, uint8, uint8, bool, uint8, uint8)
virtual void OnEvent (Guild *, uint8, ObjectGuid::LowType, ObjectGuid::LowType, uint8)
virtual void OnBankEvent (Guild *, uint8, uint8, ObjectGuid::LowType, uint32, uint16, uint8)
virtual bool CanGuildSendBankList (Guild const *, WorldSession *, uint8, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
GuildScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
GuildScript()
GuildScript::GuildScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<GuildScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanGuildSendBankList()
virtual bool GuildScript::CanGuildSendBankList (Guild const * , WorldSession * , uint8 , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::CanGuildSendBankList().
IsDatabaseBound()
bool GuildScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
OnAddMember()
virtual void GuildScript::OnAddMember (Guild * , Player * , uint8 &) inline virtual
{ }
Referenced by ScriptMgr::OnGuildAddMember().
OnBankEvent()
virtual void GuildScript::OnBankEvent (Guild * , uint8 , uint8 , ObjectGuid::LowType , uint32 , uint16 , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnGuildBankEvent().
OnCreate()
virtual void GuildScript::OnCreate (Guild * , Player * , const std::string &) inline virtual
{ }
Referenced by ScriptMgr::OnGuildCreate().
OnDisband()
virtual void GuildScript::OnDisband (Guild *) inline virtual
{ }
Referenced by ScriptMgr::OnGuildDisband().
OnEvent()
virtual void GuildScript::OnEvent (Guild * , uint8 , ObjectGuid::LowType , ObjectGuid::LowType , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnGuildEvent().
OnInfoChanged()
virtual void GuildScript::OnInfoChanged (Guild * , const std::string &) inline virtual
{ }
Referenced by ScriptMgr::OnGuildInfoChanged().
OnItemMove()
virtual void GuildScript::OnItemMove (Guild * , Player * , Item * , bool , uint8 , uint8 , bool , uint8 , uint8) inline virtual
                                                      { }
Referenced by ScriptMgr::OnGuildItemMove().
OnMemberDepositMoney()
virtual void GuildScript::OnMemberDepositMoney (Guild * , Player * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnGuildMemberDepositMoney().
OnMemberWitdrawMoney()
virtual void GuildScript::OnMemberWitdrawMoney (Guild * , Player * , uint32 & , bool) inline virtual
{ }
Referenced by ScriptMgr::OnGuildMemberWitdrawMoney().
OnMOTDChanged()
virtual void GuildScript::OnMOTDChanged (Guild * , const std::string &) inline virtual
{ }
Referenced by ScriptMgr::OnGuildMOTDChanged().
OnRemoveMember()
virtual void GuildScript::OnRemoveMember (Guild * , Player * , bool , bool) inline virtual
{ }
Referenced by ScriptMgr::OnGuildRemoveMember().