AzerothCore: server_commandscript Class Reference
server_commandscript Class Reference
Public Member Functions
server_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleServerCorpsesCommand (ChatHandler *)
static bool HandleServerDebugCommand (ChatHandler *handler)
static bool HandleServerInfoCommand (ChatHandler *handler)
static bool HandleServerMotdCommand (ChatHandler *handler)
static bool HandleServerShutDownCancelCommand (ChatHandler *)
static bool HandleServerShutDownCommand (ChatHandler *handler, std::string time, Optional< int32 > exitCode, Tail reason)
static bool HandleServerRestartCommand (ChatHandler *handler, std::string time, Optional< int32 > exitCode, Tail reason)
static bool HandleServerIdleRestartCommand (ChatHandler *handler, std::string time, Optional< int32 > exitCode, Tail reason)
static bool HandleServerIdleShutDownCommand (ChatHandler *handler, std::string time, Optional< int32 > exitCode, Tail reason)
static bool HandleServerExitCommand (ChatHandler *handler)
static bool HandleServerSetMotdCommand (ChatHandler *handler, Optional< int32 > realmId, Optional< std::string > locale, Tail motd)
static bool HandleServerSetClosedCommand (ChatHandler *handler, Optional< std::string > args)
static bool HandleServerSetLogLevelCommand (ChatHandler *, bool isLogger, std::string const &name, int32 level)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
server_commandscript()
server_commandscript::server_commandscript () inline
: CommandScript("server_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable server_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable serverIdleRestartCommandTable =
        {
            { "cancel",       HandleServerShutDownCancelCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "",             HandleServerIdleRestartCommand,    SEC_CONSOLE,       Console::Yes }
        };
        static ChatCommandTable serverIdleShutdownCommandTable =
        {
            { "cancel",       HandleServerShutDownCancelCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "",             HandleServerIdleShutDownCommand,   SEC_CONSOLE,       Console::Yes }
        };
        static ChatCommandTable serverRestartCommandTable =
        {
            { "cancel",       HandleServerShutDownCancelCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "",             HandleServerRestartCommand,        SEC_ADMINISTRATOR, Console::Yes }
        };
        static ChatCommandTable serverShutdownCommandTable =
        {
            { "cancel",       HandleServerShutDownCancelCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "",             HandleServerShutDownCommand,       SEC_ADMINISTRATOR, Console::Yes }
        };
        static ChatCommandTable serverSetCommandTable =
        {
            { "loglevel",     HandleServerSetLogLevelCommand,    SEC_CONSOLE,       Console::Yes },
            { "motd",         HandleServerSetMotdCommand,        SEC_ADMINISTRATOR, Console::Yes },
            { "closed",       HandleServerSetClosedCommand,      SEC_CONSOLE,       Console::Yes },
        };
        static ChatCommandTable serverCommandTable =
        {
            { "corpses",      HandleServerCorpsesCommand,        SEC_GAMEMASTER,    Console::Yes },
            { "debug",        HandleServerDebugCommand,          SEC_ADMINISTRATOR, Console::Yes },
            { "exit",         HandleServerExitCommand,           SEC_CONSOLE,       Console::Yes },
            { "idlerestart",  serverIdleRestartCommandTable },
            { "idleshutdown", serverIdleShutdownCommandTable },
            { "info",         HandleServerInfoCommand,           SEC_PLAYER,        Console::Yes },
            { "motd",         HandleServerMotdCommand,           SEC_PLAYER,        Console::Yes },
            { "restart",      serverRestartCommandTable },
            { "shutdown",     serverShutdownCommandTable },
            { "set",          serverSetCommandTable }
        };
        static ChatCommandTable commandTable =
        {
            { "server", serverCommandTable }
        };
        return commandTable;
    }
References HandleServerCorpsesCommand(), HandleServerDebugCommand(), HandleServerExitCommand(), HandleServerIdleRestartCommand(), HandleServerIdleShutDownCommand(), HandleServerInfoCommand(), HandleServerMotdCommand(), HandleServerRestartCommand(), HandleServerSetClosedCommand(), HandleServerSetLogLevelCommand(), HandleServerSetMotdCommand(), HandleServerShutDownCancelCommand(), HandleServerShutDownCommand(), SEC_ADMINISTRATOR, SEC_CONSOLE, SEC_GAMEMASTER, and SEC_PLAYER.
HandleServerCorpsesCommand()
static bool server_commandscript::HandleServerCorpsesCommand (ChatHandler *) inline static
    {
        sWorld->RemoveOldCorpses();
        return true;
    }
References sWorld.
Referenced by GetCommands().
HandleServerDebugCommand()
static bool server_commandscript::HandleServerDebugCommand (ChatHandler * handler) inline static
    {
        uint16 worldPort = uint16(sWorld->getIntConfig(CONFIG_PORT_WORLD));
        std::string dbPortOutput;
        {
            uint16 dbPort = 0;
            if (QueryResult res = LoginDatabase.Query("SELECT port FROM realmlist WHERE id = {}", realm.Id.Realm))
                dbPort = (*res)[0].Get<uint16>();
            if (dbPort)
                dbPortOutput = Acore::StringFormat("Realmlist (Realm Id: {}) configured in port {}", realm.Id.Realm, dbPort);
            else
                dbPortOutput = Acore::StringFormat("Realm Id: {} not found in `realmlist` table. Please check your setup", realm.Id.Realm);
        }
        HandleServerInfoCommand(handler);
        handler->PSendSysMessage("Using SSL version: {} (library: {})", OPENSSL_VERSION_TEXT, OpenSSL_version(OPENSSL_VERSION));
        handler->PSendSysMessage("Using Boost version: {}.{}.{}", BOOST_VERSION / 100000, BOOST_VERSION / 100 % 1000, BOOST_VERSION % 100);
        handler->PSendSysMessage("Using CMake version: {}", GitRevision::GetCMakeVersion());
        handler->PSendSysMessage("Using MySQL version: {}", MySQL::GetLibraryVersion());
        handler->PSendSysMessage("Found MySQL Executable: {}", GitRevision::GetMySQLExecutable());
        handler->PSendSysMessage("Compiled on: {}", GitRevision::GetHostOSVersion());
        handler->PSendSysMessage("Worldserver listening connections on port {}", worldPort);
        handler->PSendSysMessage("{}", dbPortOutput);
        bool vmapIndoorCheck = sWorld->getBoolConfig(CONFIG_VMAP_INDOOR_CHECK);
        bool vmapLOSCheck = VMAP::VMapFactory::createOrGetVMapMgr()->isLineOfSightCalcEnabled();
        bool vmapHeightCheck = VMAP::VMapFactory::createOrGetVMapMgr()->isHeightCalcEnabled();
        bool mmapEnabled = sWorld->getBoolConfig(CONFIG_ENABLE_MMAPS);
        std::string dataDir = sWorld->GetDataPath();
        std::vector<std::string> subDirs;
        subDirs.emplace_back("maps");
        if (vmapIndoorCheck || vmapLOSCheck || vmapHeightCheck)
        {
            handler->PSendSysMessage("VMAPs status: Enabled. LineOfSight: {}, getHeight: {}, indoorCheck: {}", vmapLOSCheck, vmapHeightCheck, vmapIndoorCheck);
            subDirs.emplace_back("vmaps");
        }
        else
            handler->SendSysMessage("VMAPs status: Disabled");
        if (mmapEnabled)
        {
            handler->SendSysMessage("MMAPs status: Enabled");
            subDirs.emplace_back("mmaps");
        }
        else
            handler->SendSysMessage("MMAPs status: Disabled");
        for (std::string const& subDir : subDirs)
        {
            std::filesystem::path mapPath(dataDir);
            mapPath /= subDir;
            if (!std::filesystem::exists(mapPath))
            {
                handler->PSendSysMessage("{} directory doesn't exist!. Using path: {}", subDir, mapPath.generic_string());
                continue;
            }
            auto end = std::filesystem::directory_iterator();
            std::size_t folderSize = std::accumulate(std::filesystem::directory_iterator(mapPath), end, std::size_t(0), [](std::size_t val, std::filesystem::path const& mapFile)
            {
                if (std::filesystem::is_regular_file(mapFile))
                    val += std::filesystem::file_size(mapFile);
                return val;
            });
            handler->PSendSysMessage("{} directory located in {}. Total size: {} bytes", subDir, mapPath.generic_string(), folderSize);
        }
        LocaleConstant defaultLocale = sWorld->GetDefaultDbcLocale();
        uint32 availableLocalesMask = (1 << defaultLocale);
        for (uint8 i = 0; i < TOTAL_LOCALES; ++i)
        {
            LocaleConstant locale = static_cast<LocaleConstant>(i);
            if (locale == defaultLocale)
                continue;
            if (sWorld->GetAvailableDbcLocale(locale) != defaultLocale)
                availableLocalesMask |= (1 << locale);
        }
        std::string availableLocales;
        for (uint8 i = 0; i < TOTAL_LOCALES; ++i)
        {
            if (!(availableLocalesMask & (1 << i)))
                continue;
            availableLocales += localeNames[i];
            if (i != TOTAL_LOCALES - 1)
                availableLocales += " ";
        }
        handler->PSendSysMessage("Default DBC locale: {}.\nAll available DBC locales: {}", localeNames[defaultLocale], availableLocales);
        handler->PSendSysMessage("Using World DB: {}", sWorld->GetDBVersion());
        std::string lldb = "No updates found!";
        if (QueryResult resL = LoginDatabase.Query("SELECT name FROM updates ORDER BY name DESC LIMIT 1"))
        {
            Field* fields = resL->Fetch();
            lldb = fields[0].Get<std::string>();
        }
        std::string lcdb = "No updates found!";
        if (QueryResult resC = CharacterDatabase.Query("SELECT name FROM updates ORDER BY name DESC LIMIT 1"))
        {
            Field* fields = resC->Fetch();
            lcdb = fields[0].Get<std::string>();
        }
        std::string lwdb = "No updates found!";
        if (QueryResult resW = WorldDatabase.Query("SELECT name FROM updates ORDER BY name DESC LIMIT 1"))
        {
            Field* fields = resW->Fetch();
            lwdb = fields[0].Get<std::string>();
        }
        handler->PSendSysMessage("Latest LoginDatabase update: {}", lldb);
        handler->PSendSysMessage("Latest CharacterDatabase update: {}", lcdb);
        handler->PSendSysMessage("Latest WorldDatabase update: {}", lwdb);
        handler->PSendSysMessage("LoginDatabase queue size: {}", LoginDatabase.QueueSize());
        handler->PSendSysMessage("CharacterDatabase queue size: {}", CharacterDatabase.QueueSize());
        handler->PSendSysMessage("WorldDatabase queue size: {}", WorldDatabase.QueueSize());
        if (Acore::Module::GetEnableModulesList().empty())
            handler->PSendSysMessage("No modules are enabled");
        else
            handler->PSendSysMessage("List of enabled modules:");
        for (auto const& modName : Acore::Module::GetEnableModulesList())
        {
            handler->PSendSysMessage("|- {}", modName);
        }
        return true;
    }
References CharacterDatabase, CONFIG_ENABLE_MMAPS, CONFIG_PORT_WORLD, CONFIG_VMAP_INDOOR_CHECK, VMAP::VMapFactory::createOrGetVMapMgr(), Field::Get(), GitRevision::GetCMakeVersion(), Acore::Module::GetEnableModulesList(), GitRevision::GetHostOSVersion(), MySQL::GetLibraryVersion(), GitRevision::GetMySQLExecutable(), HandleServerInfoCommand(), Realm::Id, VMAP::IVMapMgr::isHeightCalcEnabled(), VMAP::IVMapMgr::isLineOfSightCalcEnabled(), localeNames, LoginDatabase, ChatHandler::PSendSysMessage(), realm, RealmHandle::Realm, ChatHandler::SendSysMessage(), Acore::StringFormat(), sWorld, TOTAL_LOCALES, and WorldDatabase.
Referenced by GetCommands().
HandleServerExitCommand()
static bool server_commandscript::HandleServerExitCommand (ChatHandler * handler) inline static
    {
        handler->SendSysMessage(LANG_COMMAND_EXIT);
        World::StopNow(SHUTDOWN_EXIT_CODE);
        return true;
    }
References LANG_COMMAND_EXIT, ChatHandler::SendSysMessage(), SHUTDOWN_EXIT_CODE, and World::StopNow().
Referenced by GetCommands().
HandleServerIdleRestartCommand()
static bool server_commandscript::HandleServerIdleRestartCommand (ChatHandler * handler, std::string time, Optional< int32 > exitCode, Tail reason) inline static
    {
        std::wstring wReason   = std::wstring();
        std::string  strReason = std::string();
        if (time.empty())
        {
            return false;
        }
        if (Acore::StringTo<int32>(time).value_or(0) < 0)
        {
            handler->SendErrorMessage(LANG_BAD_VALUE);
            return false;
        }
        if (!reason.empty())
        {
            if (!Utf8toWStr(reason, wReason))
            {
                return false;
            }
            if (!WStrToUtf8(wReason, strReason))
            {
                return false;
            }
        }
        int32 delay = TimeStringToSecs(time);
        if (delay <= 0)
        {
            delay = Acore::StringTo<int32>(time).value_or(0);
        }
        if (delay <= 0)
        {
            handler->SendErrorMessage(LANG_BAD_VALUE);
            return false;
        }
        if (exitCode && *exitCode >= 0 && *exitCode <= 125)
        {
            sWorld->ShutdownServ(delay, SHUTDOWN_MASK_RESTART | SHUTDOWN_MASK_IDLE, *exitCode);
        }
        else
        {
            sWorld->ShutdownServ(delay, SHUTDOWN_MASK_RESTART | SHUTDOWN_MASK_IDLE, RESTART_EXIT_CODE, strReason);
        }
        return true;
    }
References LANG_BAD_VALUE, RESTART_EXIT_CODE, ChatHandler::SendErrorMessage(), SHUTDOWN_MASK_IDLE, SHUTDOWN_MASK_RESTART, sWorld, TimeStringToSecs(), Utf8toWStr(), and WStrToUtf8().
Referenced by GetCommands().
HandleServerIdleShutDownCommand()
static bool server_commandscript::HandleServerIdleShutDownCommand (ChatHandler * handler, std::string time, Optional< int32 > exitCode, Tail reason) inline static
    {
        std::wstring wReason   = std::wstring();
        std::string  strReason = std::string();
        if (time.empty())
        {
            return false;
        }
        if (Acore::StringTo<int32>(time).value_or(0) < 0)
        {
            handler->SendErrorMessage(LANG_BAD_VALUE);
            return false;
        }
        if (!reason.empty())
        {
            if (!Utf8toWStr(reason, wReason))
            {
                return false;
            }
            if (!WStrToUtf8(wReason, strReason))
            {
                return false;
            }
        }
        int32 delay = TimeStringToSecs(time);
        if (delay <= 0)
        {
            delay = Acore::StringTo<int32>(time).value_or(0);
        }
        if (delay <= 0)
        {
            handler->SendErrorMessage(LANG_BAD_VALUE);
            return false;
        }
        if (exitCode && *exitCode >= 0 && *exitCode <= 125)
        {
            sWorld->ShutdownServ(delay, SHUTDOWN_MASK_IDLE, *exitCode);
        }
        else
        {
            sWorld->ShutdownServ(delay, SHUTDOWN_MASK_IDLE, SHUTDOWN_EXIT_CODE, strReason);
        }
        return true;
    }
References LANG_BAD_VALUE, ChatHandler::SendErrorMessage(), SHUTDOWN_EXIT_CODE, SHUTDOWN_MASK_IDLE, sWorld, TimeStringToSecs(), Utf8toWStr(), and WStrToUtf8().
Referenced by GetCommands().
HandleServerInfoCommand()
static bool server_commandscript::HandleServerInfoCommand (ChatHandler * handler) inline static
Can't use sWorld->ShutdownMsg here in case of console command
    {
        std::string realmName = sWorld->GetRealmName();
        uint32 playerCount = sWorld->GetPlayerCount();
        uint32 activeSessionCount = sWorld->GetActiveSessionCount();
        uint32 queuedSessionCount = sWorld->GetQueuedSessionCount();
        uint32 connPeak = sWorld->GetMaxActiveSessionCount();
        handler->PSendSysMessage("{}", GitRevision::GetFullVersion());
        if (!queuedSessionCount)
            handler->PSendSysMessage("Connected players: {}. Characters in world: {}.", activeSessionCount, playerCount);
        else
            handler->PSendSysMessage("Connected players: {}. Characters in world: {}. Queue: {}.", activeSessionCount, playerCount, queuedSessionCount);
        handler->PSendSysMessage("Connection peak: {}.", connPeak);
        handler->PSendSysMessage(LANG_UPTIME, secsToTimeString(GameTime::GetUptime().count()));
        handler->PSendSysMessage("Update time diff: {}ms. Last {} diffs summary:", sWorldUpdateTime.GetLastUpdateTime(), sWorldUpdateTime.GetDatasetSize());
        handler->PSendSysMessage("|- Mean: {}ms", sWorldUpdateTime.GetAverageUpdateTime());
        handler->PSendSysMessage("|- Median: {}ms", sWorldUpdateTime.GetPercentile(50));
        handler->PSendSysMessage("|- Percentiles (95, 99, max): {}ms, {}ms, {}ms",
                                 sWorldUpdateTime.GetPercentile(95),
                                 sWorldUpdateTime.GetPercentile(99),
                                 sWorldUpdateTime.GetPercentile(100));
        if (sWorld->IsShuttingDown())
            handler->PSendSysMessage(LANG_SHUTDOWN_TIMELEFT, secsToTimeString(sWorld->GetShutDownTimeLeft()).append("."));
        return true;
    }
References UpdateTime::GetAverageUpdateTime(), UpdateTime::GetDatasetSize(), GitRevision::GetFullVersion(), UpdateTime::GetLastUpdateTime(), UpdateTime::GetPercentile(), GameTime::GetUptime(), LANG_SHUTDOWN_TIMELEFT, LANG_UPTIME, ChatHandler::PSendSysMessage(), secsToTimeString(), sWorld, and sWorldUpdateTime.
Referenced by GetCommands(), and HandleServerDebugCommand().
HandleServerMotdCommand()
static bool server_commandscript::HandleServerMotdCommand (ChatHandler * handler) inline static
    {
        LocaleConstant localeConstant = DEFAULT_LOCALE;
        if (Player* player = handler->GetPlayer())
            localeConstant = player->GetSession()->GetSessionDbLocaleIndex();
        handler->PSendSysMessage(LANG_MOTD_CURRENT, sMotdMgr->GetMotd(localeConstant));
        return true;
    }
References DEFAULT_LOCALE, ChatHandler::GetPlayer(), LANG_MOTD_CURRENT, ChatHandler::PSendSysMessage(), and sMotdMgr.
Referenced by GetCommands().
HandleServerRestartCommand()
static bool server_commandscript::HandleServerRestartCommand (ChatHandler * handler, std::string time, Optional< int32 > exitCode, Tail reason) inline static
    {
        std::wstring wReason = std::wstring();
        std::string strReason    = std::string();
        if (time.empty())
        {
            return false;
        }
        if (Acore::StringTo<int32>(time).value_or(0) < 0)
        {
            handler->SendErrorMessage(LANG_BAD_VALUE);
            return false;
        }
        if (!reason.empty())
        {
            if (!Utf8toWStr(reason, wReason))
            {
                return false;
            }
            if (!WStrToUtf8(wReason, strReason))
            {
                return false;
            }
        }
        int32 delay = TimeStringToSecs(time);
        if (delay <= 0)
        {
            delay = Acore::StringTo<int32>(time).value_or(0);
        }
        if (delay <= 0)
        {
            handler->SendErrorMessage(LANG_BAD_VALUE);
            return false;
        }
        if (exitCode && *exitCode >= 0 && *exitCode <= 125)
        {
            sWorld->ShutdownServ(delay, SHUTDOWN_MASK_RESTART, *exitCode);
        }
        else
        {
            sWorld->ShutdownServ(delay, SHUTDOWN_MASK_RESTART, RESTART_EXIT_CODE, strReason);
        }
        return true;
    }
References LANG_BAD_VALUE, RESTART_EXIT_CODE, ChatHandler::SendErrorMessage(), SHUTDOWN_MASK_RESTART, sWorld, TimeStringToSecs(), Utf8toWStr(), and WStrToUtf8().
Referenced by GetCommands().
HandleServerSetClosedCommand()
static bool server_commandscript::HandleServerSetClosedCommand (ChatHandler * handler, Optional< std::string > args) inline static
    {
        if (StringStartsWith("on", *args))
        {
            handler->SendSysMessage(LANG_WORLD_CLOSED);
            sWorld->SetClosed(true);
            return true;
        }
        else if (StringStartsWith("off", *args))
        {
            handler->SendSysMessage(LANG_WORLD_OPENED);
            sWorld->SetClosed(false);
            return true;
        }
        handler->SendErrorMessage(LANG_USE_BOL);
        return false;
    }
References LANG_USE_BOL, LANG_WORLD_CLOSED, LANG_WORLD_OPENED, ChatHandler::SendErrorMessage(), ChatHandler::SendSysMessage(), StringStartsWith(), and sWorld.
Referenced by GetCommands().
HandleServerSetLogLevelCommand()
static bool server_commandscript::HandleServerSetLogLevelCommand (ChatHandler * , bool isLogger, std::string const & name, int32 level) inline static
    {
        sLog->SetLogLevel(name, level, isLogger);
        return true;
    }
References sLog.
Referenced by GetCommands().
HandleServerSetMotdCommand()
static bool server_commandscript::HandleServerSetMotdCommand (ChatHandler * handler, Optional< int32 > realmId, Optional< std::string > locale, Tail motd) inline static
    {
        std::wstring wMotd = std::wstring();
        std::string strMotd = std::string();
        // Default realmId to the current realm if not provided
        if (!realmId)
            realmId = static_cast<int32>(realm.Id.Realm);
        if (motd.empty())
            return false;
        // Convert Tail (motd) to std::string
        std::ostringstream motdStream;
        motdStream << motd;
        std::string motdString = motdStream.str(); // Convert Tail to std::string
        // Determine the locale; default to "enUS" if not provided
        LocaleConstant localeConstant = DEFAULT_LOCALE;
        if (locale.has_value())
        {
            if (sMotdMgr->IsValidLocale(locale.value()))
            {
                localeConstant = GetLocaleByName(locale.value());
            }
            else
            {
                motdStream.str("");
                motdStream << locale.value() << " " << motd;
                motdString = motdStream.str();
                localeConstant = DEFAULT_LOCALE;
                locale = GetNameByLocaleConstant(localeConstant);
            }
        }
        else
        {
            // Set to default locale string
            localeConstant = DEFAULT_LOCALE;
            locale = GetNameByLocaleConstant(localeConstant);
        }
        // Convert the concatenated motdString to UTF-8 and ensure encoding consistency
        if (!Utf8toWStr(motdString, wMotd))
            return false;
        if (!WStrToUtf8(wMotd, strMotd))
            return false;
        // Start a transaction for the database operations
        LoginDatabaseTransaction trans = LoginDatabase.BeginTransaction();
        if (localeConstant == DEFAULT_LOCALE)
        {
            // Insert or update in the main motd table for enUS
            LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_MOTD);
            stmt->SetData(0, realmId.value());  // realmId for insertion
            stmt->SetData(1, strMotd);          // motd text for insertion
            stmt->SetData(2, strMotd);          // motd text for ON DUPLICATE KEY UPDATE
            trans->Append(stmt);
        }
        else
        {
            // Insert or update in the motd_localized table for other locales
            LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_MOTD_LOCALE);
            stmt->SetData(0, realmId.value());  // realmId for insertion
            stmt->SetData(1, locale.value());           // locale for insertion
            stmt->SetData(2, strMotd);          // motd text for insertion
            stmt->SetData(3, strMotd);          // motd text for ON DUPLICATE KEY UPDATE
            trans->Append(stmt);
        }
        // Commit the transaction & update db
        LoginDatabase.CommitTransaction(trans);
        // Update the in-memory maps for the current realm. Otherwise, do not update
        if (realmId == -1 || realmId == static_cast<int32>(realm.Id.Realm))
            sMotdMgr->SetMotd(strMotd, localeConstant);
        handler->PSendSysMessage(LANG_MOTD_NEW, realmId.value(), locale.value(), strMotd);
        return true;
    }
References DEFAULT_LOCALE, GetLocaleByName(), GetNameByLocaleConstant(), Realm::Id, LANG_MOTD_NEW, LOGIN_INS_MOTD, LOGIN_INS_MOTD_LOCALE, LoginDatabase, ChatHandler::PSendSysMessage(), realm, RealmHandle::Realm, PreparedStatementBase::SetData(), sMotdMgr, Utf8toWStr(), and WStrToUtf8().
Referenced by GetCommands().
HandleServerShutDownCancelCommand()
static bool server_commandscript::HandleServerShutDownCancelCommand (ChatHandler *) inline static
    {
        sWorld->ShutdownCancel();
        return true;
    }
References sWorld.
Referenced by GetCommands().
HandleServerShutDownCommand()
static bool server_commandscript::HandleServerShutDownCommand (ChatHandler * handler, std::string time, Optional< int32 > exitCode, Tail reason) inline static
    {
        std::wstring wReason   = std::wstring();
        std::string  strReason = std::string();
        if (time.empty())
        {
            return false;
        }
        if (Acore::StringTo<int32>(time).value_or(0) < 0)
        {
            handler->SendErrorMessage(LANG_BAD_VALUE);
            return false;
        }
        if (!reason.empty())
        {
            if (!Utf8toWStr(reason, wReason))
            {
                return false;
            }
            if (!WStrToUtf8(wReason, strReason))
            {
                return false;
            }
        }
        int32 delay = TimeStringToSecs(time);
        if (delay <= 0)
        {
            delay = Acore::StringTo<int32>(time).value_or(0);
        }
        if (delay <= 0)
        {
            handler->SendErrorMessage(LANG_BAD_VALUE);
            return false;
        }
        if (exitCode && *exitCode >= 0 && *exitCode <= 125)
        {
            sWorld->ShutdownServ(delay, 0, *exitCode);
        }
        else
        {
            sWorld->ShutdownServ(delay, 0, SHUTDOWN_EXIT_CODE, strReason);
        }
        return true;
    }
References LANG_BAD_VALUE, ChatHandler::SendErrorMessage(), SHUTDOWN_EXIT_CODE, sWorld, TimeStringToSecs(), Utf8toWStr(), and WStrToUtf8().
Referenced by GetCommands().