AzerothCore: Acore::NearestAttackableNoTotemUnitInObjectRangeCheck Class Reference
Acore::NearestAttackableNoTotemUnitInObjectRangeCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
NearestAttackableNoTotemUnitInObjectRangeCheck (WorldObject const *obj, Unit const *owner, float range)
bool operator() (Unit *u)
Private Attributes
WorldObject const * i_obj
Unit const * i_owner
float i_range
Detailed Description
Constructor & Destructor Documentation
NearestAttackableNoTotemUnitInObjectRangeCheck()
Acore::NearestAttackableNoTotemUnitInObjectRangeCheck::NearestAttackableNoTotemUnitInObjectRangeCheck (WorldObject const * obj, Unit const * owner, float range) inline
: i_obj(obj), i_owner(owner), i_range(range) {}
Member Function Documentation
operator()()
bool Acore::NearestAttackableNoTotemUnitInObjectRangeCheck::operator() (Unit * u) inline
        {
            if (!u->IsAlive())
            {
                return false;
            }
            if (u->GetCreatureType() == CREATURE_TYPE_NON_COMBAT_PET)
            {
                return false;
            }
            if (u->IsCreature() && u->ToCreature()->IsTotem())
            {
                return false;
            }
            if (!u->isTargetableForAttack(false, i_owner))
            {
                return false;
            }
            uint32 losChecks = LINEOFSIGHT_ALL_CHECKS;
            Optional<float> collisionHeight = { };
            if (i_obj->IsGameObject())
            {
                losChecks &= ~LINEOFSIGHT_CHECK_GOBJECT_M2;
                collisionHeight = i_owner->GetCollisionHeight();
            }
            if (!i_obj->IsWithinDistInMap(u, i_range) || !i_owner->IsValidAttackTarget(u) ||
                !i_obj->IsWithinLOSInMap(u, VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks(losChecks), collisionHeight))
            {
                return false;
            }
            return true;
        }
References CREATURE_TYPE_NON_COMBAT_PET, Unit::GetCollisionHeight(), Unit::GetCreatureType(), i_obj, i_owner, i_range, Unit::IsAlive(), Object::IsCreature(), Object::IsGameObject(), Unit::isTargetableForAttack(), Unit::IsTotem(), Unit::IsValidAttackTarget(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), LINEOFSIGHT_ALL_CHECKS, VMAP::Nothing, and Object::ToCreature().
Member Data Documentation
i_obj
WorldObject const* Acore::NearestAttackableNoTotemUnitInObjectRangeCheck::i_obj private
Referenced by operator()().
i_owner
Unit const* Acore::NearestAttackableNoTotemUnitInObjectRangeCheck::i_owner private
Referenced by operator()().
i_range
float Acore::NearestAttackableNoTotemUnitInObjectRangeCheck::i_range private
Referenced by operator()().