AzerothCore: go_magtheridons_head Struct Reference
go_magtheridons_head Struct Reference
Public Member Functions
go_magtheridons_head (GameObject *gameObject)
void InitializeAI () override
void OnStateChanged (uint32 state, Unit *) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_magtheridons_head()
go_magtheridons_head::go_magtheridons_head (GameObject * gameObject) inline
: GameObjectAI(gameObject) { }
Member Function Documentation
InitializeAI()
void go_magtheridons_head::InitializeAI () inline override virtual
Reimplemented from GameObjectAI.
    {
        me->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE); // spawn head on spike
        me->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
        sWorldState->HandleExternalEvent(WORLD_STATE_CUSTOM_EVENT_ON_MAGTHERIDON_HEAD_SPAWN, me->GetPositionX() > 0.f ? TEAM_HORDE : TEAM_ALLIANCE);
    }
References Position::GetPositionX(), GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE_ALTERNATIVE, GameObjectAI::me, GameObject::SetGameObjectFlag(), GameObject::SetGoState(), sWorldState, TEAM_ALLIANCE, TEAM_HORDE, and WORLD_STATE_CUSTOM_EVENT_ON_MAGTHERIDON_HEAD_SPAWN.
OnStateChanged()
void go_magtheridons_head::OnStateChanged (uint32 state, Unit *) inline override virtual
Reimplemented from GameObjectAI.
    {
        if (state == GO_JUST_DEACTIVATED)
        {
            sWorldState->HandleExternalEvent(WORLD_STATE_CUSTOM_EVENT_ON_MAGTHERIDON_HEAD_DESPAWN, me->GetPositionX() > 0.f ? TEAM_HORDE : TEAM_ALLIANCE);
        }
    }
References Position::GetPositionX(), GO_JUST_DEACTIVATED, GameObjectAI::me, sWorldState, TEAM_ALLIANCE, TEAM_HORDE, and WORLD_STATE_CUSTOM_EVENT_ON_MAGTHERIDON_HEAD_DESPAWN.