AzeorthCore: npc_frostbrood_skytalon::npc_frostbrood_skytalonAI Struct Reference
npc_frostbrood_skytalon::npc_frostbrood_skytalonAI Struct Reference
Public Member Functions
npc_frostbrood_skytalonAI (Creature *creature)
void IsSummonedBy (Unit *summoner) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
void SpellHit (Unit *, SpellInfo const *spell) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectTargetMethod targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from VehicleAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_frostbrood_skytalonAI()
npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::npc_frostbrood_skytalonAI (Creature * creature) inline
: VehicleAI(creature) { }
Member Function Documentation
IsSummonedBy()
void npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::IsSummonedBy (Unit * summoner) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!summoner)
                return;
            me->GetMotionMaster()->MovePoint(POINT_GRAB_DECOY, summoner->GetPositionX(), summoner->GetPositionY(), summoner->GetPositionZ() + 3.0f);
        }
References Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), CreatureAI::me, MotionMaster::MovePoint(), and POINT_GRAB_DECOY.
MovementInform()
void npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
        {
            if (type != POINT_MOTION_TYPE)
                return;
            if (id == POINT_GRAB_DECOY)
                if (TempSummon* summon = me->ToTempSummon())
                    if (Unit* summoner = summon->GetSummonerUnit())
                        DoCast(summoner, SPELL_GRAB);
        }
References UnitAI::DoCast(), CreatureAI::me, POINT_GRAB_DECOY, POINT_MOTION_TYPE, SPELL_GRAB, and Unit::ToTempSummon().
SpellHit()
void npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
        {
            switch (spell->Id)
            {
                case SPELL_EXPLOSION:
                    DoCast(me, SPELL_IMMOLATION);
                    break;
                case SPELL_RIDE:
                    DoCastAOE(SPELL_PING_BUNNY);
                    events.ScheduleEvent(EVENT_FLY_AWAY, 100);
                    break;
            }
        }
References UnitAI::DoCast(), UnitAI::DoCastAOE(), EVENT_FLY_AWAY, SpellInfo::Id, CreatureAI::me, SPELL_EXPLOSION, SPELL_IMMOLATION, SPELL_PING_BUNNY, and SPELL_RIDE.
UpdateAI()
void npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from VehicleAI.
        {
            VehicleAI::UpdateAI(diff);
            events.Update(diff);
            while (uint32 eventId = events.ExecuteEvent())
            {
                if (eventId == EVENT_FLY_AWAY)
                {
                    Position randomPosOnRadius;
                    randomPosOnRadius.m_positionZ = (me->GetPositionZ() + 40.0f);
                    me->GetNearPoint2D(randomPosOnRadius.m_positionX, randomPosOnRadius.m_positionY, 40.0f, me->GetAngle(me));
                    me->GetMotionMaster()->MovePoint(POINT_FLY_AWAY, randomPosOnRadius);
                }
            }
        }
References EVENT_FLY_AWAY, Position::GetAngle(), Unit::GetMotionMaster(), WorldObject::GetNearPoint2D(), Position::GetPositionZ(), Position::m_positionX, Position::m_positionY, Position::m_positionZ, CreatureAI::me, MotionMaster::MovePoint(), POINT_FLY_AWAY, and VehicleAI::UpdateAI().
Member Data Documentation
events
EventMap npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::events