AzerothCore: npc_boss_gothik_minion::npc_boss_gothik_minionAI Struct Reference
npc_boss_gothik_minion::npc_boss_gothik_minionAI Struct Reference
Public Member Functions
npc_boss_gothik_minionAI (Creature *c)
bool IsOnSameSide (Unit const *who) const
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from CombatAI
CombatAI (Creature *c)
void InitializeAI () override
void Reset () override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void JustDied (Unit *killer) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
bool livingSide
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CombatAI
static int32 Permissible (Creature const *)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CombatAI
EventMap events
SpellVct spells
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_boss_gothik_minionAI()
npc_boss_gothik_minion::npc_boss_gothik_minionAI::npc_boss_gothik_minionAI (Creature * c) inline explicit
                                                       : CombatAI(c)
        {
            livingSide = IN_LIVE_SIDE(me);
        }
References IN_LIVE_SIDE, livingSide, and CreatureAI::me.
Member Function Documentation
IsOnSameSide()
bool npc_boss_gothik_minion::npc_boss_gothik_minionAI::IsOnSameSide (Unit const * who) const inline
{ return livingSide == IN_LIVE_SIDE(who); }
References IN_LIVE_SIDE, and livingSide.
JustDied()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::JustDied (Unit *) inline override virtual
Reimplemented from CombatAI.
        {
            switch (me->GetEntry())
            {
                case NPC_LIVING_TRAINEE:
                    DoCastAOE(SPELL_ANCHOR_1_TRAINEE, true);
                    break;
                case NPC_LIVING_KNIGHT:
                    DoCastAOE(SPELL_ANCHOR_1_DK, true);
                    break;
                case NPC_LIVING_RIDER:
                    DoCastAOE(SPELL_ANCHOR_1_RIDER, true);
                    break;
            }
        }
References UnitAI::DoCastAOE(), Object::GetEntry(), CreatureAI::me, NPC_LIVING_KNIGHT, NPC_LIVING_RIDER, NPC_LIVING_TRAINEE, SPELL_ANCHOR_1_DK, SPELL_ANCHOR_1_RIDER, and SPELL_ANCHOR_1_TRAINEE.
JustEngagedWith()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::JustEngagedWith (Unit * who) inline override virtual
Called for reaction when initially engaged.
Parameters
who Who 'me' Engaged combat with
Reimplemented from CombatAI.
        {
            switch (me->GetEntry())
            {
                case NPC_LIVING_TRAINEE:
                    events.ScheduleEvent(EVENT_DEATH_PLAGUE, 3s);
                    break;
                case NPC_DEAD_TRAINEE:
                    events.ScheduleEvent(EVENT_ARCANE_EXPLOSION, 2500ms);
                    break;
                case NPC_LIVING_KNIGHT:
                    events.ScheduleEvent(EVENT_SHADOW_MARK, 3s);
                    break;
                case NPC_DEAD_KNIGHT:
                    events.ScheduleEvent(EVENT_WHIRLWIND, 2s);
                    break;
                case NPC_LIVING_RIDER:
                    events.ScheduleEvent(EVENT_SHADOW_BOLT_VOLLEY, 3s);
                    break;
                case NPC_DEAD_RIDER:
                    events.ScheduleEvent(EVENT_DRAIN_LIFE, 2000ms, 3500ms);
                    events.ScheduleEvent(EVENT_UNHOLY_FRENZY, 5s, 9s);
                    break;
                case NPC_DEAD_HORSE:
                    events.ScheduleEvent(EVENT_STOMP, 2s, 5s);
                    break;
            }
        }
References EVENT_ARCANE_EXPLOSION, EVENT_DEATH_PLAGUE, EVENT_DRAIN_LIFE, EVENT_SHADOW_BOLT_VOLLEY, EVENT_SHADOW_MARK, EVENT_STOMP, EVENT_UNHOLY_FRENZY, EVENT_WHIRLWIND, Object::GetEntry(), CreatureAI::me, NPC_DEAD_HORSE, NPC_DEAD_KNIGHT, NPC_DEAD_RIDER, NPC_DEAD_TRAINEE, NPC_LIVING_KNIGHT, NPC_LIVING_RIDER, and NPC_LIVING_TRAINEE.
KilledUnit()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from CreatureAI.
        {
            if (who->IsPlayer() && me->GetInstanceScript())
            {
                me->GetInstanceScript()->SetData(DATA_IMMORTAL_FAIL, 0);
            }
        }
References DATA_IMMORTAL_FAIL, WorldObject::GetInstanceScript(), Object::IsPlayer(), CreatureAI::me, and ZoneScript::SetData().
Reset()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::Reset () inline override virtual
Reimplemented from CombatAI.
        {
            me->SetReactState(REACT_AGGRESSIVE);
            me->SetNoCallAssistance(false);
            events.Reset();
        }
References CreatureAI::me, REACT_AGGRESSIVE, Creature::SetNoCallAssistance(), and Creature::SetReactState().
UpdateAI()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from CombatAI.
        {
            events.Update(diff);
            if (me->GetUnitState() == UNIT_STATE_CASTING)
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_DEATH_PLAGUE:
                    me->CastSpell(me->GetVictim(), SPELL_DEATH_PLAGUE, false);
                    events.Repeat(4s, 7s);
                    break;
                case EVENT_ARCANE_EXPLOSION:
                    if (Unit* victim = me->GetVictim())
                    {
                        if (victim->IsWithinDist(me, 20))
{
                            me->CastSpell(victim, SPELL_ARCANE_EXPLOSION, false);
                        }
                    }
                    events.Repeat(2500ms);
                    break;
                case EVENT_SHADOW_MARK:
                    if (Unit* victim = me->GetVictim())
                    {
                        if (victim->IsWithinDist(me, 10))
{
                            me->CastSpell(victim, SPELL_SHADOW_MARK, false);
                        }
                    }
                    events.Repeat(5s, 7s);
                    break;
                case EVENT_WHIRLWIND:
                    if (Unit* victim = me->GetVictim())
                    {
                        if (victim->IsWithinDist(me, 10))
{
                            me->CastSpell(victim, SPELL_WHIRLWIND, false);
                        }
                    }
                    events.Repeat(4s, 6s);
                    break;
                case EVENT_SHADOW_BOLT_VOLLEY:
                    me->CastSpell(me->GetVictim(), SPELL_SHADOW_BOLT_VOLLEY, false);
                    events.Repeat(5s);
                    break;
                case EVENT_DRAIN_LIFE:
                    if (Unit* victim = me->GetVictim())
                    {
                        if (victim->IsWithinDist(me, 20))
{
                            me->CastSpell(victim, SPELL_DRAIN_LIFE, false);
                        }
                    }
                    events.Repeat(8s, 12s);
                    break;
                case EVENT_UNHOLY_FRENZY:
                    me->AddAura(SPELL_UNHOLY_FRENZY, me);
                    events.Repeat(15s, 17s);
                    break;
                case EVENT_STOMP:
                    if (Unit* victim = me->GetVictim())
                    {
                        if (victim->IsWithinDist(me, 10))
{
                            me->CastSpell(victim, SPELL_STOMP, false);
                        }
                    }
                    events.Repeat(4s, 9s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::AddAura(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_ARCANE_EXPLOSION, EVENT_DEATH_PLAGUE, EVENT_DRAIN_LIFE, EVENT_SHADOW_BOLT_VOLLEY, EVENT_SHADOW_MARK, EVENT_STOMP, EVENT_UNHOLY_FRENZY, EVENT_WHIRLWIND, Unit::GetUnitState(), Unit::GetVictim(), CreatureAI::me, SPELL_ARCANE_EXPLOSION, SPELL_DEATH_PLAGUE, SPELL_DRAIN_LIFE, SPELL_SHADOW_BOLT_VOLLEY, SPELL_SHADOW_MARK, SPELL_STOMP, SPELL_UNHOLY_FRENZY, SPELL_WHIRLWIND, and UNIT_STATE_CASTING.
Member Data Documentation
events
EventMap npc_boss_gothik_minion::npc_boss_gothik_minionAI::events
livingSide
bool npc_boss_gothik_minion::npc_boss_gothik_minionAI::livingSide
Referenced by IsOnSameSide(), and npc_boss_gothik_minionAI().