AzerothCore: BattlegroundDS Class Reference
BattlegroundDS Class Reference
#include "BattlegroundDS.h"
Public Member Functions
BattlegroundDS ()
void StartingEventCloseDoors () override
void StartingEventOpenDoors () override
void HandleAreaTrigger (Player *player, uint32 trigger) override
bool SetupBattleground () override
void FillInitialWorldStates (WorldPacket &d) override
bool HandlePlayerUnderMap (Player *player) override
Public Member Functions inherited from Battleground
Battleground ()
virtual ~Battleground ()
void Update (uint32 diff)
virtual bool SetupBattleground ()
virtual void Init ()
virtual void StartingEventCloseDoors ()
virtual void StartingEventOpenDoors ()
virtual void ResetBGSubclass ()
virtual void DestroyGate (Player *, GameObject *)
virtual bool AllNodesConrolledByTeam (TeamId) const
void StartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
std::string GetName () const
BattlegroundTypeId GetBgTypeID (bool GetRandom=false) const
BattlegroundBracketId GetBracketId () const
uint32 GetInstanceID () const
BattlegroundStatus GetStatus () const
uint32 GetClientInstanceID () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetLastResurrectTime () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
bool isTemplate () const
bool isMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
uint8 GetArenaType () const
PvPTeamId GetWinner () const
uint32 GetScriptId () const
uint32 GetBonusHonorFromKill (uint32 kills) const
void SpiritOfCompetitionEvent (PvPTeamId winnerTeamId) const
bool IsRandom ()
void SetName (std::string_view name)
void SetBgTypeID (BattlegroundTypeId TypeID)
void SetRandomTypeID (BattlegroundTypeId TypeID)
void SetBracket (PvPDifficultyEntry const *bracketEntry)
void SetInstanceID (uint32 InstanceID)
void SetStatus (BattlegroundStatus Status)
void SetClientInstanceID (uint32 InstanceID)
void SetStartTime (uint32 Time)
void SetEndTime (uint32 Time)
void SetLastResurrectTime (uint32 Time)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (uint8 type)
void SetArenaorBGType (bool _isArena)
void SetWinner (PvPTeamId winner)
void SetScriptId (uint32 scriptId)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int32 diff)
void SetStartDelayTime (int32 Time)
void SetMaxPlayersPerTeam (uint32 MaxPlayers)
void SetMinPlayersPerTeam (uint32 MinPlayers)
void AddToBGFreeSlotQueue ()
void RemoveFromBGFreeSlotQueue ()
void DecreaseInvitedCount (TeamId teamId)
void IncreaseInvitedCount (TeamId teamId)
uint32 GetInvitedCount (TeamId teamId) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (TeamId teamId) const
uint32 GetMaxFreeSlots () const
void AddSpectator (Player *p)
void RemoveSpectator (Player *p)
bool HaveSpectators ()
const SpectatorList & GetSpectators () const
void AddToBeTeleported (ObjectGuid spectator, ObjectGuid participant)
void RemoveToBeTeleported (ObjectGuid spectator)
void SpectatorsSendPacket (WorldPacket &data)
bool isArena () const
bool isBattleground () const
bool isRated () const
BattlegroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
void ReadyMarkerClicked (Player *p)
BattlegroundScoreMap const * GetPlayerScores () const
std::size_t GetPlayerScoresSize () const
uint32 GetReviveQueueSize () const
void AddPlayerToResurrectQueue (ObjectGuid npc_guid, ObjectGuid player_guid)
void RemovePlayerFromResurrectQueue (Player *player)
void RelocateDeadPlayers (ObjectGuid queueIndex)
Relocate all players in ReviveQueue to the closest graveyard.
void StartBattleground ()
GameObject * GetBGObject (uint32 type)
Creature * GetBGCreature (uint32 type)
void SetMapId (uint32 MapID)
uint32 GetMapId () const
void SetBgMap (BattlegroundMap *map)
BattlegroundMap * GetBgMap () const
BattlegroundMap * FindBgMap () const
void SetTeamStartPosition (TeamId teamId, Position const &pos)
Position const * GetTeamStartPosition (TeamId teamId) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
virtual void FillInitialWorldStates (WorldPacket &)
void SendPacketToTeam (TeamId teamId, WorldPacket const *packet, Player *sender=nullptr, bool self=true)
void SendPacketToAll (WorldPacket const *packet)
void YellToAll (Creature *creature, const char *text, uint32 language)
void SendChatMessage (Creature *source, uint8 textId, WorldObject *target=nullptr)
void SendBroadcastText (uint32 id, ChatMsg msgType, WorldObject const *target=nullptr)
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToAll (uint32 soundId)
void CastSpellOnTeam (uint32 spellId, TeamId teamId)
void RemoveAuraOnTeam (uint32 spellId, TeamId teamId)
void RewardHonorToTeam (uint32 honor, TeamId teamId)
void RewardReputationToTeam (uint32 factionId, uint32 reputation, TeamId teamId)
uint32 GetRealRepFactionForPlayer (uint32 factionId, Player *player)
void UpdateWorldState (uint32 variable, uint32 value)
void EndBattleground (PvPTeamId winnerTeamId)
virtual void EndBattleground (TeamId winnerTeamId)
void BlockMovement (Player *player)
Group * GetBgRaid (TeamId teamId) const
void SetBgRaid (TeamId teamId, Group *bg_raid)
void BuildPvPLogDataPacket (WorldPacket &data)
virtual bool UpdatePlayerScore (Player *player, uint32 type, uint32 value, bool doAddHonor=true)
uint32 GetPlayersCountByTeam (TeamId teamId) const
uint32 GetAlivePlayersCountByTeam (TeamId teamId) const
void UpdatePlayersCountByTeam (TeamId teamId, bool remove)
virtual void CheckWinConditions ()
void SetArenaTeamIdForTeam (TeamId teamId, uint32 ArenaTeamId)
uint32 GetArenaTeamIdForTeam (TeamId teamId) const
void SetArenaMatchmakerRating (TeamId teamId, uint32 MMR)
uint32 GetArenaMatchmakerRating (TeamId teamId) const
virtual void HandleAreaTrigger (Player *, uint32)
virtual void HandleKillPlayer (Player *player, Player *killer)
virtual void HandleKillUnit (Creature *, Player *)
virtual void EventPlayerDroppedFlag (Player *)
virtual void EventPlayerClickedOnFlag (Player *, GameObject *)
virtual void EventPlayerDamagedGO (Player *, GameObject *, uint32)
virtual void EventPlayerUsedGO (Player *, GameObject *)
virtual void DoAction (uint32, ObjectGuid)
virtual void HandlePlayerResurrect (Player *)
virtual GraveyardStruct const * GetClosestGraveyard (Player *player)
virtual void AddPlayer (Player *player)
void AddOrSetPlayerToCorrectBgGroup (Player *player, TeamId teamId)
virtual void RemovePlayerAtLeave (Player *player)
void HandleTriggerBuff (GameObject *gameObject)
void SetHoliday (bool is_holiday)
void SpawnBGObject (uint32 type, uint32 respawntime, uint32 forceRespawnDelay=0)
bool AddObject (uint32 type, uint32 entry, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime=0, GOState goState=GO_STATE_READY)
Creature * AddCreature (uint32 entry, uint32 type, float x, float y, float z, float o, uint32 respawntime=0, MotionTransport *transport=nullptr)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool AddSpiritGuide (uint32 type, float x, float y, float z, float o, TeamId teamId)
int32 GetObjectType (ObjectGuid guid)
void DoorOpen (uint32 type)
void DoorClose (uint32 type)
const char * GetAcoreString (int32 entry)
virtual bool HandlePlayerUnderMap (Player *)
bool IsPlayerInBattleground (ObjectGuid guid) const
bool ToBeDeleted () const
void RewardXPAtKill (Player *killer, Player *victim)
virtual ObjectGuid GetFlagPickerGUID (TeamId=TEAM_NEUTRAL) const
virtual void SetDroppedFlagGUID (ObjectGuid, TeamId=TEAM_NEUTRAL)
uint32 GetTeamScore (TeamId teamId) const
virtual TeamId GetPrematureWinner ()
uint8 GetUniqueBracketId () const
BattlegroundAV * ToBattlegroundAV ()
BattlegroundAV const * ToBattlegroundAV () const
BattlegroundWS * ToBattlegroundWS ()
BattlegroundWS const * ToBattlegroundWS () const
BattlegroundAB * ToBattlegroundAB ()
BattlegroundAB const * ToBattlegroundAB () const
BattlegroundNA * ToBattlegroundNA ()
BattlegroundNA const * ToBattlegroundNA () const
BattlegroundBE * ToBattlegroundBE ()
BattlegroundBE const * ToBattlegroundBE () const
BattlegroundEY * ToBattlegroundEY ()
BattlegroundEY const * ToBattlegroundEY () const
BattlegroundRL * ToBattlegroundRL ()
BattlegroundRL const * ToBattlegroundRL () const
BattlegroundSA * ToBattlegroundSA ()
BattlegroundSA const * ToBattlegroundSA () const
BattlegroundDS * ToBattlegroundDS ()
BattlegroundDS const * ToBattlegroundDS () const
BattlegroundRV * ToBattlegroundRV ()
BattlegroundRV const * ToBattlegroundRV () const
BattlegroundIC * ToBattlegroundIC ()
BattlegroundIC const * ToBattlegroundIC () const
Private Member Functions
void PostUpdateImpl (uint32 diff) override
Post-update hook.
Private Attributes
uint32 _pipeKnockBackTimer
uint8 _pipeKnockBackCount
EventMap _events
Additional Inherited Members
Public Types inherited from Battleground
typedef std::set< Player * > SpectatorList
typedef std::map< ObjectGuid, ObjectGuid > ToBeTeleportedMap
typedef std::map< ObjectGuid, Player * > BattlegroundPlayerMap
typedef std::unordered_map< ObjectGuid::LowType, BattlegroundScore * > BattlegroundScoreMap
typedef std::unordered_map< ObjectGuid, ArenaLogEntryData > ArenaLogEntryDataMap
typedef GuidVector BGObjects
typedef GuidVector BGCreatures
Static Public Member Functions inherited from Battleground
static TeamId GetOtherTeamId (TeamId teamId)
Public Attributes inherited from Battleground
GuidSet readyMarkerClickedSet
ArenaLogEntryDataMap ArenaLogEntries
BGObjects BgObjects
BGCreatures BgCreatures
Protected Member Functions inherited from Arena
Arena ()
void AddPlayer (Player *player) override
void RemovePlayer (Player *) override
void FillInitialWorldStates (WorldPacket &data) override
void UpdateArenaWorldState ()
void HandleKillPlayer (Player *player, Player *killer) override
Protected Member Functions inherited from Battleground
void EndNow ()
void PlayerAddedToBGCheckIfBGIsRunning (Player *player)
void _ProcessResurrect (uint32 diff)
void _ProcessProgress (uint32 diff)
void _ProcessLeave (uint32 diff)
void _ProcessJoin (uint32 diff)
void _CheckSafePositions (uint32 diff)
virtual void RemovePlayer (Player *)
Protected Attributes inherited from Battleground
BattlegroundScoreMap PlayerScores
BattlegroundPlayerMap m_Players
std::map< ObjectGuid, GuidVector > m_ReviveQueue
uint8 m_Events
BattlegroundStartTimeIntervals StartDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 StartMessageIds [BG_STARTING_EVENT_COUNT]
bool m_BuffChange
bool m_IsRandom
BGHonorMode m_HonorMode
int32 m_TeamScores [PVP_TEAMS_COUNT]
ArenaTeamScore _arenaTeamScores [PVP_TEAMS_COUNT]
uint32 m_UpdateTimer
EventProcessor _reviveEvents
Detailed Description
Constructor & Destructor Documentation
BattlegroundDS()
BattlegroundDS::BattlegroundDS ()
{
    BgObjects.resize(BG_DS_OBJECT_MAX);
    BgCreatures.resize(BG_DS_NPC_MAX);
    _pipeKnockBackTimer = 0;
    _pipeKnockBackCount = 0;
}
References _pipeKnockBackCount, _pipeKnockBackTimer, BG_DS_NPC_MAX, BG_DS_OBJECT_MAX, Battleground::BgCreatures, and Battleground::BgObjects.
Member Function Documentation
FillInitialWorldStates()
void BattlegroundDS::FillInitialWorldStates (WorldPacket & d) override virtual
Reimplemented from Arena.
{
    data << uint32(3610) << uint32(1);                                              // 9 show
    Arena::FillInitialWorldStates(data);
}
References Arena::FillInitialWorldStates().
HandleAreaTrigger()
void BattlegroundDS::HandleAreaTrigger (Player * player, uint32 trigger) override virtual
Reimplemented from Battleground.
{
    if (GetStatus() != STATUS_IN_PROGRESS)
        return;
    switch (trigger)
    {
        case 5347:
        case 5348:
            // Remove effects of Demonic Circle Summon
            if (player->HasAura(SPELL_WARL_DEMONIC_CIRCLE))
                player->RemoveAurasDueToSpell(SPELL_WARL_DEMONIC_CIRCLE);
            // Someone has get back into the pipes and the knockback has already been performed,
            // so we reset the knockback count for kicking the player again into the arena.
            if (_pipeKnockBackCount >= BG_DS_PIPE_KNOCKBACK_TOTAL_COUNT)
                _pipeKnockBackCount = 0;
            break;
        // OUTSIDE OF ARENA, TELEPORT!
        case 5328:
            player->NearTeleportTo(1290.44f, 744.96f, 3.16f, 1.6f);
            break;
        case 5329:
            player->NearTeleportTo(1292.6f, 837.07f, 3.161f, 4.7f);
            break;
        case 5330:
            player->NearTeleportTo(1250.68f, 790.86f, 3.16f, 0.0f);
            break;
        case 5331:
            player->NearTeleportTo(1332.50f, 790.9f, 3.16f, 3.14f);
            break;
        case 5326: // -10
        case 5343: // -40
        case 5344: // -60
            player->NearTeleportTo(1330.0f, 800.0f, 3.16f, player->GetOrientation());
            break;
        /*default:
            Battleground::HandleAreaTrigger(player, trigger);
            break;*/
    }
}
References _pipeKnockBackCount, BG_DS_PIPE_KNOCKBACK_TOTAL_COUNT, Position::GetOrientation(), Battleground::GetStatus(), Unit::HasAura(), Unit::NearTeleportTo(), Unit::RemoveAurasDueToSpell(), SPELL_WARL_DEMONIC_CIRCLE, and STATUS_IN_PROGRESS.
HandlePlayerUnderMap()
bool BattlegroundDS::HandlePlayerUnderMap (Player * player) override virtual
Reimplemented from Battleground.
{
    player->NearTeleportTo(1299.046f, 784.825f, 9.338f, 2.422f);
    return true;
}
References Unit::NearTeleportTo().
PostUpdateImpl()
void BattlegroundDS::PostUpdateImpl (uint32) override private virtual
Post-update hook.
Will be called after battleground update has passed. May be used to implement custom update effects in subclasses.
Parameters
diff a time difference between two worldserver update loops in milliseconds.
See also
Update(), PreUpdateImpl().
Reimplemented from Battleground.
{
    if (GetStatus() != STATUS_IN_PROGRESS)
        return;
    _events.Update(diff);
    while (uint32 eventId = _events.ExecuteEvent())
    {
        switch (eventId)
        {
        case BG_DS_EVENT_WATERFALL_WARNING:
            // Add the water
            DoorClose(BG_DS_OBJECT_WATER_2);
            _events.ScheduleEvent(BG_DS_EVENT_WATERFALL_ON, BG_DS_WATERFALL_WARNING_DURATION);
            break;
        case BG_DS_EVENT_WATERFALL_ON:
            // Active collision and start knockback timer
            DoorClose(BG_DS_OBJECT_WATER_1);
            _events.ScheduleEvent(BG_DS_EVENT_WATERFALL_OFF, BG_DS_WATERFALL_DURATION);
            _events.ScheduleEvent(BG_DS_EVENT_WATERFALL_KNOCKBACK, BG_DS_WATERFALL_KNOCKBACK_TIMER);
            break;
        case BG_DS_EVENT_WATERFALL_OFF:
            // Remove collision and water
            DoorOpen(BG_DS_OBJECT_WATER_1);
            DoorOpen(BG_DS_OBJECT_WATER_2);
            _events.CancelEvent(BG_DS_EVENT_WATERFALL_KNOCKBACK);
            _events.ScheduleEvent(BG_DS_EVENT_WATERFALL_WARNING, BG_DS_WATERFALL_TIMER_MIN, BG_DS_WATERFALL_TIMER_MAX);
            break;
        case BG_DS_EVENT_WATERFALL_KNOCKBACK:
            // Repeat knockback while the waterfall still active
            if (Creature* waterSpout = GetBGCreature(BG_DS_NPC_WATERFALL_KNOCKBACK))
                waterSpout->CastSpell(waterSpout, BG_DS_SPELL_WATER_SPOUT, true);
            _events.ScheduleEvent(eventId, BG_DS_WATERFALL_KNOCKBACK_TIMER);
            break;
        case BG_DS_EVENT_PIPE_KNOCKBACK:
            for (uint32 i = BG_DS_NPC_PIPE_KNOCKBACK_1; i <= BG_DS_NPC_PIPE_KNOCKBACK_2; ++i)
                if (Creature* waterSpout = GetBGCreature(i))
                    waterSpout->CastSpell(waterSpout, BG_DS_SPELL_FLUSH, true);
            break;
        }
    }
    if (_pipeKnockBackCount < BG_DS_PIPE_KNOCKBACK_TOTAL_COUNT)
    {
        if (_pipeKnockBackTimer < diff)
        {
            for (uint32 i = BG_DS_NPC_PIPE_KNOCKBACK_1; i <= BG_DS_NPC_PIPE_KNOCKBACK_2; ++i)
                if (Creature* waterSpout = GetBGCreature(i))
                    waterSpout->CastSpell(waterSpout, BG_DS_SPELL_FLUSH, true);
            ++_pipeKnockBackCount;
            _pipeKnockBackTimer = BG_DS_PIPE_KNOCKBACK_DELAY;
        }
        else
            _pipeKnockBackTimer -= diff;
    }
}
References _events, _pipeKnockBackCount, _pipeKnockBackTimer, BG_DS_EVENT_PIPE_KNOCKBACK, BG_DS_EVENT_WATERFALL_KNOCKBACK, BG_DS_EVENT_WATERFALL_OFF, BG_DS_EVENT_WATERFALL_ON, BG_DS_EVENT_WATERFALL_WARNING, BG_DS_NPC_PIPE_KNOCKBACK_1, BG_DS_NPC_PIPE_KNOCKBACK_2, BG_DS_NPC_WATERFALL_KNOCKBACK, BG_DS_OBJECT_WATER_1, BG_DS_OBJECT_WATER_2, BG_DS_PIPE_KNOCKBACK_DELAY, BG_DS_PIPE_KNOCKBACK_TOTAL_COUNT, BG_DS_SPELL_FLUSH, BG_DS_SPELL_WATER_SPOUT, BG_DS_WATERFALL_DURATION, BG_DS_WATERFALL_KNOCKBACK_TIMER, BG_DS_WATERFALL_TIMER_MAX, BG_DS_WATERFALL_TIMER_MIN, BG_DS_WATERFALL_WARNING_DURATION, EventMap::CancelEvent(), Battleground::DoorClose(), Battleground::DoorOpen(), EventMap::ExecuteEvent(), Battleground::GetBGCreature(), Battleground::GetStatus(), EventMap::ScheduleEvent(), STATUS_IN_PROGRESS, and EventMap::Update().
SetupBattleground()
bool BattlegroundDS::SetupBattleground () override virtual
Reimplemented from Battleground.
{
    // gates
    if (!AddObject(BG_DS_OBJECT_DOOR_1, BG_DS_OBJECT_TYPE_DOOR_1, 1350.95f, 817.2f, 20.8096f, 3.15f, 0, 0, 0.99627f, 0.0862864f, RESPAWN_IMMEDIATELY)
            || !AddObject(BG_DS_OBJECT_DOOR_2, BG_DS_OBJECT_TYPE_DOOR_2, 1232.65f, 764.913f, 20.0729f, 6.3f, 0, 0, 0.0310211f, -0.999519f, RESPAWN_IMMEDIATELY)
            // water
            || !AddObject(BG_DS_OBJECT_WATER_1, BG_DS_OBJECT_TYPE_WATER_1, 1291.56f, 790.837f, 7.1f, 3.14238f, 0, 0, 0.694215f, -0.719768f, 120)
            || !AddObject(BG_DS_OBJECT_WATER_2, BG_DS_OBJECT_TYPE_WATER_2, 1291.56f, 790.837f, 7.1f, 3.14238f, 0, 0, 0.694215f, -0.719768f, 120)
            // buffs
            || !AddObject(BG_DS_OBJECT_BUFF_1, BG_DS_OBJECT_TYPE_BUFF_1, 1291.7f, 813.424f, 7.11472f, 4.64562f, 0, 0, 0.730314f, -0.683111f, 120)
            || !AddObject(BG_DS_OBJECT_BUFF_2, BG_DS_OBJECT_TYPE_BUFF_2, 1291.7f, 768.911f, 7.11472f, 1.55194f, 0, 0, 0.700409f, 0.713742f, 120)
            // knockback creatures
            || !AddCreature(BG_DS_NPC_TYPE_WATER_SPOUT, BG_DS_NPC_WATERFALL_KNOCKBACK, 1291.76f, 791.02f, 7.115f, 3.054326f, RESPAWN_IMMEDIATELY)
            || !AddCreature(BG_DS_NPC_TYPE_WATER_SPOUT, BG_DS_NPC_PIPE_KNOCKBACK_1, 1369.977f, 817.2882f, 16.08718f, 3.106686f, RESPAWN_IMMEDIATELY)
            || !AddCreature(BG_DS_NPC_TYPE_WATER_SPOUT, BG_DS_NPC_PIPE_KNOCKBACK_2, 1212.833f, 765.3871f, 16.09484f, 0.0f, RESPAWN_IMMEDIATELY)
            // Arena Ready Marker
            || !AddObject(BG_DS_OBJECT_READY_MARKER_1, ARENA_READY_MARKER_ENTRY, 1229.44f, 759.35f, 17.89f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 300)
            || !AddObject(BG_DS_OBJECT_READY_MARKER_2, ARENA_READY_MARKER_ENTRY, 1352.90f, 822.77f, 17.96f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 300))
    {
        LOG_ERROR("sql.sql", "BatteGroundDS: Failed to spawn some object!");
        return false;
    }
    return true;
}
References Battleground::AddCreature(), Battleground::AddObject(), ARENA_READY_MARKER_ENTRY, BG_DS_NPC_PIPE_KNOCKBACK_1, BG_DS_NPC_PIPE_KNOCKBACK_2, BG_DS_NPC_TYPE_WATER_SPOUT, BG_DS_NPC_WATERFALL_KNOCKBACK, BG_DS_OBJECT_BUFF_1, BG_DS_OBJECT_BUFF_2, BG_DS_OBJECT_DOOR_1, BG_DS_OBJECT_DOOR_2, BG_DS_OBJECT_READY_MARKER_1, BG_DS_OBJECT_READY_MARKER_2, BG_DS_OBJECT_TYPE_BUFF_1, BG_DS_OBJECT_TYPE_BUFF_2, BG_DS_OBJECT_TYPE_DOOR_1, BG_DS_OBJECT_TYPE_DOOR_2, BG_DS_OBJECT_TYPE_WATER_1, BG_DS_OBJECT_TYPE_WATER_2, BG_DS_OBJECT_WATER_1, BG_DS_OBJECT_WATER_2, LOG_ERROR, and RESPAWN_IMMEDIATELY.
StartingEventCloseDoors()
void BattlegroundDS::StartingEventCloseDoors () override virtual
Reimplemented from Battleground.
{
    for (uint32 i = BG_DS_OBJECT_DOOR_1; i <= BG_DS_OBJECT_DOOR_2; ++i)
        SpawnBGObject(i, RESPAWN_IMMEDIATELY);
}
References BG_DS_OBJECT_DOOR_1, BG_DS_OBJECT_DOOR_2, RESPAWN_IMMEDIATELY, and Battleground::SpawnBGObject().
StartingEventOpenDoors()
void BattlegroundDS::StartingEventOpenDoors () override virtual
Reimplemented from Battleground.
{
    for (uint32 i = BG_DS_OBJECT_DOOR_1; i <= BG_DS_OBJECT_DOOR_2; ++i)
        DoorOpen(i);
    for (uint32 i = BG_DS_OBJECT_BUFF_1; i <= BG_DS_OBJECT_BUFF_2; ++i)
        SpawnBGObject(i, 90);
    _events.ScheduleEvent(BG_DS_EVENT_WATERFALL_WARNING, BG_DS_WATERFALL_TIMER_MIN, BG_DS_WATERFALL_TIMER_MAX);
    //for (uint8 i = 0; i < BG_DS_PIPE_KNOCKBACK_TOTAL_COUNT; ++i)
    //    _events.ScheduleEvent(BG_DS_EVENT_PIPE_KNOCKBACK, BG_DS_PIPE_KNOCKBACK_FIRST_DELAY + i * BG_DS_PIPE_KNOCKBACK_DELAY);
    _pipeKnockBackCount = 0;
    _pipeKnockBackTimer = BG_DS_PIPE_KNOCKBACK_FIRST_DELAY;
    SpawnBGObject(BG_DS_OBJECT_WATER_2, RESPAWN_IMMEDIATELY);
    DoorOpen(BG_DS_OBJECT_WATER_2);
    // Turn off collision
    if (GameObject* gob = GetBgMap()->GetGameObject(BgObjects[BG_DS_OBJECT_WATER_1]))
        gob->SetGoState(GO_STATE_ACTIVE);
    // Remove effects of Demonic Circle Summon
    for (BattlegroundPlayerMap::const_iterator itr = GetPlayers().begin(); itr != GetPlayers().end(); ++itr)
        if (itr->second->HasAura(48018))
            itr->second->RemoveAurasDueToSpell(48018);
}
References _events, _pipeKnockBackCount, _pipeKnockBackTimer, BG_DS_EVENT_WATERFALL_WARNING, BG_DS_OBJECT_BUFF_1, BG_DS_OBJECT_BUFF_2, BG_DS_OBJECT_DOOR_1, BG_DS_OBJECT_DOOR_2, BG_DS_OBJECT_WATER_1, BG_DS_OBJECT_WATER_2, BG_DS_PIPE_KNOCKBACK_FIRST_DELAY, BG_DS_WATERFALL_TIMER_MAX, BG_DS_WATERFALL_TIMER_MIN, Battleground::BgObjects, Battleground::DoorOpen(), Battleground::GetBgMap(), Battleground::GetPlayers(), GO_STATE_ACTIVE, RESPAWN_IMMEDIATELY, EventMap::ScheduleEvent(), and Battleground::SpawnBGObject().
Member Data Documentation
_events
EventMap BattlegroundDS::_events private
Referenced by PostUpdateImpl(), and StartingEventOpenDoors().
_pipeKnockBackCount
uint8 BattlegroundDS::_pipeKnockBackCount private
Referenced by BattlegroundDS(), HandleAreaTrigger(), PostUpdateImpl(), and StartingEventOpenDoors().
_pipeKnockBackTimer
uint32 BattlegroundDS::_pipeKnockBackTimer private
Referenced by BattlegroundDS(), PostUpdateImpl(), and StartingEventOpenDoors().