AzerothCore: GuildBankRightsAndSlots Class Reference
GuildBankRightsAndSlots Class Reference
#include "Guild.h"
Public Member Functions
GuildBankRightsAndSlots ()
GuildBankRightsAndSlots (uint8 _tabId)
GuildBankRightsAndSlots (uint8 _tabId, uint8 _rights, uint32 _slots)
void SetGuildMasterValues ()
void SetTabId (uint8 _tabId)
void SetSlots (uint32 _slots)
void SetRights (uint8 _rights)
uint8 GetTabId () const
uint32 GetSlots () const
uint8 GetRights () const
Private Attributes
uint8 tabId
uint8 rights
uint32 slots
Detailed Description
Constructor & Destructor Documentation
GuildBankRightsAndSlots() [1/3]
GuildBankRightsAndSlots::GuildBankRightsAndSlots () inline
: tabId(TAB_UNDEFINED), rights(0), slots(0) { }
GuildBankRightsAndSlots() [2/3]
GuildBankRightsAndSlots::GuildBankRightsAndSlots (uint8 _tabId) inline
: tabId(_tabId), rights(0), slots(0) { }
GuildBankRightsAndSlots() [3/3]
GuildBankRightsAndSlots::GuildBankRightsAndSlots (uint8 _tabId, uint8 _rights, uint32 _slots) inline
: tabId(_tabId), rights(_rights), slots(_slots) { }
Member Function Documentation
GetRights()
uint8 GuildBankRightsAndSlots::GetRights () const inline
{ return rights; }
References rights.
Referenced by Guild::RankInfo::CreateMissingTabsIfNeeded(), and Guild::RankInfo::SetBankTabSlotsAndRights().
GetSlots()
uint32 GuildBankRightsAndSlots::GetSlots () const inline
{ return slots; }
References slots.
Referenced by Guild::RankInfo::CreateMissingTabsIfNeeded(), and Guild::RankInfo::SetBankTabSlotsAndRights().
GetTabId()
uint8 GuildBankRightsAndSlots::GetTabId () const inline
{ return tabId; }
References tabId.
Referenced by Guild::_SetRankBankTabRightsAndSlots(), Guild::RankInfo::CreateMissingTabsIfNeeded(), and Guild::RankInfo::SetBankTabSlotsAndRights().
SetGuildMasterValues()
void GuildBankRightsAndSlots::SetGuildMasterValues () inline
    {
        rights = GUILD_BANK_RIGHT_FULL;
        slots = uint32(GUILD_WITHDRAW_SLOT_UNLIMITED);
    }
References GUILD_BANK_RIGHT_FULL, GUILD_WITHDRAW_SLOT_UNLIMITED, rights, and slots.
Referenced by Guild::RankInfo::CreateMissingTabsIfNeeded(), and Guild::RankInfo::SetBankTabSlotsAndRights().
SetRights()
void GuildBankRightsAndSlots::SetRights (uint8 _rights) inline
{ rights = _rights; }
References rights.
SetSlots()
void GuildBankRightsAndSlots::SetSlots (uint32 _slots) inline
{ slots = _slots; }
References slots.
SetTabId()
void GuildBankRightsAndSlots::SetTabId (uint8 _tabId) inline
{ tabId = _tabId; }
References tabId.
Referenced by Guild::RankInfo::CreateMissingTabsIfNeeded().
Member Data Documentation
rights
uint8 GuildBankRightsAndSlots::rights private
Referenced by GetRights(), SetGuildMasterValues(), and SetRights().
slots
uint32 GuildBankRightsAndSlots::slots private
Referenced by GetSlots(), SetGuildMasterValues(), and SetSlots().
tabId
uint8 GuildBankRightsAndSlots::tabId private
Referenced by GetTabId(), and SetTabId().