AzerothCore: AuthSocketMgr Class Reference
AuthSocketMgr Class Reference
#include "AuthSocketMgr.h"
Public Member Functions
bool StartNetwork (Acore::Asio::IoContext &ioContext, std::string const &bindIp, uint16 port, int threadCount=1) override
Public Member Functions inherited from SocketMgr< AuthSession >
virtual ~SocketMgr ()
virtual bool StartNetwork (Acore::Asio::IoContext &ioContext, std::string const &bindIp, uint16 port, int threadCount)
virtual void StopNetwork ()
void Wait ()
virtual void OnSocketOpen (tcp::socket &&sock, uint32 threadIndex)
int32 GetNetworkThreadCount () const
uint32 SelectThreadWithMinConnections () const
std::pair< tcp::socket *, uint32 > GetSocketForAccept ()
Static Public Member Functions
static AuthSocketMgr & Instance ()
Protected Member Functions
NetworkThread< AuthSession > * CreateThreads () const override
Protected Member Functions inherited from SocketMgr< AuthSession >
SocketMgr ()=default
virtual NetworkThread< AuthSession > * CreateThreads () const=0
Static Protected Member Functions
static void OnSocketAccept (tcp::socket &&sock, uint32 threadIndex)
Private Types
typedef SocketMgr< AuthSession > BaseSocketMgr
Additional Inherited Members
Protected Attributes inherited from SocketMgr< AuthSession >
std::unique_ptr< AsyncAcceptor > _acceptor
std::unique_ptr< NetworkThread< AuthSession >[]> _threads
int32 _threadCount
Detailed Description
Member Typedef Documentation
BaseSocketMgr
typedef SocketMgr<AuthSession> AuthSocketMgr::BaseSocketMgr private
Member Function Documentation
CreateThreads()
NetworkThread< AuthSession > * AuthSocketMgr::CreateThreads () const inline override protected virtual
Implements SocketMgr< AuthSession >.
    {
        NetworkThread<AuthSession>* threads = new NetworkThread<AuthSession>[1];
        bool proxyProtocolEnabled = sConfigMgr->GetOption<bool>("EnableProxyProtocol", false, true);
        if (proxyProtocolEnabled)
            threads[0].EnableProxyProtocol();
        return threads;
    }
References NetworkThread< SocketType >::EnableProxyProtocol(), and sConfigMgr.
Instance()
static AuthSocketMgr & AuthSocketMgr::Instance () inline static
    {
        static AuthSocketMgr instance;
        return instance;
    }
Referenced by OnSocketAccept().
OnSocketAccept()
static void AuthSocketMgr::OnSocketAccept (tcp::socket && sock, uint32 threadIndex) inline static protected
    {
        Instance().OnSocketOpen(std::forward<tcp::socket>(sock), threadIndex);
    }
References Instance(), and SocketMgr< SocketType >::OnSocketOpen().
Referenced by StartNetwork().
StartNetwork()
bool AuthSocketMgr::StartNetwork (Acore::Asio::IoContext & ioContext, std::string const & bindIp, uint16 port, int threadCount = 1) inline override virtual
Reimplemented from SocketMgr< AuthSession >.
    {
        if (!BaseSocketMgr::StartNetwork(ioContext, bindIp, port, threadCount))
            return false;
        _acceptor->AsyncAcceptWithCallback<&AuthSocketMgr::OnSocketAccept>();
        return true;
    }
References SocketMgr< AuthSession >::_acceptor, OnSocketAccept(), and SocketMgr< AuthSession >::StartNetwork().