AzerothCore: instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript Struct Reference
instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript Struct Reference
Public Member Functions
instance_trial_of_the_crusader_InstanceMapScript (Map *pMap)
void SpawnAnubArak ()
bool IsValidDedicatedInsanityItem (ItemTemplate const *item)
void DoCheckDedicatedInsanity ()
void OnUnitDeath (Unit *u) override
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 type) const override
void Update (uint32 diff) override
void OnPlayerEnter (Player *plr) override
bool DoNeedCleanup (Player *ignoredPlayer=nullptr)
void InstanceCleanup (bool fromFailed=false)
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
bool CLEANED
uint32 EncounterStatus
uint32 InstanceProgress
uint32 AttemptsLeft
TeamId TeamIdInInstance
uint8 Counter
uint8 northrendBeastsMask
uint32 AchievementTimer
bool bDedicatedInsanity
bool bSwitcher
bool bNooneDied
std::string str_data
EventMap events
ObjectGuid NPC_BarrettGUID
ObjectGuid NPC_TirionGUID
ObjectGuid NPC_FizzlebangGUID
ObjectGuid NPC_GarroshGUID
ObjectGuid NPC_VarianGUID
ObjectGuid NPC_GormokGUID
ObjectGuid NPC_DreadscaleGUID
ObjectGuid NPC_AcidmawGUID
ObjectGuid NPC_IcehowlGUID
ObjectGuid NPC_JaraxxusGUID
GuidVector NPC_ChampionGUIDs
ObjectGuid NPC_LightbaneGUID
ObjectGuid NPC_DarkbaneGUID
ObjectGuid NPC_LichKingGUID
ObjectGuid NPC_AnubarakGUID
ObjectGuid NPC_PurpleGroundGUID
ObjectGuid NPC_PortalGUID
ObjectGuid GO_MainGateGUID
ObjectGuid GO_EnterGateGUID
ObjectGuid GO_WebDoorGUID
ObjectGuid GO_FloorGUID
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_trial_of_the_crusader_InstanceMapScript()
instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::instance_trial_of_the_crusader_InstanceMapScript (Map * pMap) inline
                                                                    : InstanceScript(pMap)
        {
            SetHeaders(DataHeader);
            Initialize();
        }
References DataHeader, Initialize(), and InstanceScript::SetHeaders().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case ACHIEV_CRITERIA_UPPER_BACK_PAIN_10_N:
                case ACHIEV_CRITERIA_UPPER_BACK_PAIN_10_H:
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                    {
                        std::list<Creature*> L;
                        uint8 count = 0;
                        c->GetCreaturesWithEntryInRange(L, 200.0f, 34800); // find all snobolds
                        for( std::list<Creature*>::const_iterator itr = L.begin(); itr != L.end(); ++itr )
                            if ((*itr)->GetVehicle())
                                ++count;
                        return (count >= 2);
                    }
                    break;
                case ACHIEV_CRITERIA_UPPER_BACK_PAIN_25_N:
                case ACHIEV_CRITERIA_UPPER_BACK_PAIN_25_H:
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                    {
                        std::list<Creature*> L;
                        uint8 count = 0;
                        c->GetCreaturesWithEntryInRange(L, 200.0f, 34800); // find all snobolds
                        for( std::list<Creature*>::const_iterator itr = L.begin(); itr != L.end(); ++itr )
                            if ((*itr)->GetVehicle())
                                ++count;
                        return (count >= 4);
                    }
                    break;
                case ACHIEV_CRITERIA_THREE_SIXTY_PAIN_SPIKE_10_N:
                case ACHIEV_CRITERIA_THREE_SIXTY_PAIN_SPIKE_10_H:
                case ACHIEV_CRITERIA_THREE_SIXTY_PAIN_SPIKE_25_N:
                case ACHIEV_CRITERIA_THREE_SIXTY_PAIN_SPIKE_25_H:
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                    {
                        std::list<Creature*> L;
                        uint8 count = 0;
                        c->GetCreaturesWithEntryInRange(L, 200.0f, 34826); // find all mistress of pain
                        for( std::list<Creature*>::const_iterator itr = L.begin(); itr != L.end(); ++itr )
                            if ((*itr)->IsAlive())
                                ++count;
                        return (count >= 2);
                    }
                    break;
                case ACHIEV_CRITERIA_A_TRIBUTE_TO_SKILL_10_PLAYER:
                case ACHIEV_CRITERIA_A_TRIBUTE_TO_SKILL_25_PLAYER:
                    return AttemptsLeft >= 25;
                case ACHIEV_CRITERIA_A_TRIBUTE_TO_MAD_SKILL_10_PLAYER:
                case ACHIEV_CRITERIA_A_TRIBUTE_TO_MAD_SKILL_25_PLAYER:
                    return AttemptsLeft >= 45;
                case ACHIEV_CRITERIA_A_TRIBUTE_TO_INSANITY_10_PLAYER:
                case ACHIEV_CRITERIA_A_TRIBUTE_TO_INSANITY_25_PLAYER:
                case ACHIEV_CRITERIA_REALM_FIRST_GRAND_CRUSADER:
                    return AttemptsLeft == 50;
                case ACHIEV_CRITERIA_A_TRIBUTE_TO_IMMORTALITY_HORDE:
                case ACHIEV_CRITERIA_A_TRIBUTE_TO_IMMORTALITY_ALLIANCE:
                    return AttemptsLeft == 50 && bNooneDied;
                case ACHIEV_CRITERIA_A_TRIBUTE_TO_DEDICATED_INSANITY:
                    return AttemptsLeft == 50 && bDedicatedInsanity;
            }
            return false;
        }
References ACHIEV_CRITERIA_A_TRIBUTE_TO_DEDICATED_INSANITY, ACHIEV_CRITERIA_A_TRIBUTE_TO_IMMORTALITY_ALLIANCE, ACHIEV_CRITERIA_A_TRIBUTE_TO_IMMORTALITY_HORDE, ACHIEV_CRITERIA_A_TRIBUTE_TO_INSANITY_10_PLAYER, ACHIEV_CRITERIA_A_TRIBUTE_TO_INSANITY_25_PLAYER, ACHIEV_CRITERIA_A_TRIBUTE_TO_MAD_SKILL_10_PLAYER, ACHIEV_CRITERIA_A_TRIBUTE_TO_MAD_SKILL_25_PLAYER, ACHIEV_CRITERIA_A_TRIBUTE_TO_SKILL_10_PLAYER, ACHIEV_CRITERIA_A_TRIBUTE_TO_SKILL_25_PLAYER, ACHIEV_CRITERIA_REALM_FIRST_GRAND_CRUSADER, ACHIEV_CRITERIA_THREE_SIXTY_PAIN_SPIKE_10_H, ACHIEV_CRITERIA_THREE_SIXTY_PAIN_SPIKE_10_N, ACHIEV_CRITERIA_THREE_SIXTY_PAIN_SPIKE_25_H, ACHIEV_CRITERIA_THREE_SIXTY_PAIN_SPIKE_25_N, ACHIEV_CRITERIA_UPPER_BACK_PAIN_10_H, ACHIEV_CRITERIA_UPPER_BACK_PAIN_10_N, ACHIEV_CRITERIA_UPPER_BACK_PAIN_25_H, ACHIEV_CRITERIA_UPPER_BACK_PAIN_25_N, AttemptsLeft, bDedicatedInsanity, bNooneDied, Map::GetCreature(), InstanceScript::instance, and NPC_BarrettGUID.
DoCheckDedicatedInsanity()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::DoCheckDedicatedInsanity () inline
        {
            if (!bDedicatedInsanity || AttemptsLeft < 50 || instance->GetDifficulty() != RAID_DIFFICULTY_10MAN_HEROIC)
                return;
            if (validDedicatedInsanityItems.empty())
            {
                for (uint32 i = 0; i < dIIc; ++i)
                    validDedicatedInsanityItems[dedicatedInsanityItems[i]] = true;
            }
            Map::PlayerList const& pl = instance->GetPlayers();
            for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                if (Player* plr = itr->GetSource())
                    if (!plr->IsGameMaster() && plr->IsInCombat() /*performance*/)
                    {
                        for (uint8 i = EQUIPMENT_SLOT_START; i < EQUIPMENT_SLOT_END; ++i) // loop through equipped items
                            if (Item* item = plr->GetItemByPos(INVENTORY_SLOT_BAG_0, i))
                                if (!IsValidDedicatedInsanityItem(item->GetTemplate()))
{
                                    bDedicatedInsanity = false;
                                    SaveToDB();
                                    return;
                                }
                    }
        }
References bDedicatedInsanity, MapRefMgr::begin(), dedicatedInsanityItems, dIIc, MapRefMgr::end(), EQUIPMENT_SLOT_END, EQUIPMENT_SLOT_START, Map::GetPlayers(), InstanceScript::instance, INVENTORY_SLOT_BAG_0, IsValidDedicatedInsanityItem(), RAID_DIFFICULTY_10MAN_HEROIC, InstanceScript::SaveToDB(), and validDedicatedInsanityItems.
Referenced by Update().
DoNeedCleanup()
bool instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::DoNeedCleanup (Player * ignoredPlayer = nullptr) inline
        {
            uint8 aliveCount = 0;
            for (auto const& itr: instance->GetPlayers())
            {
                if (Player* plr = itr.GetSource())
                {
                    if (plr != ignoredPlayer && plr->IsAlive() && !plr->IsGameMaster())
                    {
                        ++aliveCount;
                    }
                }
            }
            bool need = aliveCount == 0;
            if (!need && CLEANED)
            {
                CLEANED = false;
            }
            return need;
        }
References CLEANED, Map::GetPlayers(), and InstanceScript::instance.
Referenced by OnPlayerEnter(), and Update().
GetData()
uint32 instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case TYPE_INSTANCE_PROGRESS:
                    return InstanceProgress;
            }
            return 0;
        }
References InstanceProgress, and TYPE_INSTANCE_PROGRESS.
GetGuidData()
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case TYPE_GORMOK:
                    return NPC_GormokGUID;
                case TYPE_DREADSCALE:
                    return NPC_DreadscaleGUID;
                case TYPE_ACIDMAW:
                    return NPC_AcidmawGUID;
                case NPC_DARKBANE:
                    return NPC_DarkbaneGUID;
                case NPC_LIGHTBANE:
                    return NPC_LightbaneGUID;
                case TYPE_ANUBARAK:
                    return NPC_AnubarakGUID;
            }
            return ObjectGuid::Empty;
        }
References ObjectGuid::Empty, NPC_AcidmawGUID, NPC_AnubarakGUID, NPC_DARKBANE, NPC_DarkbaneGUID, NPC_DreadscaleGUID, NPC_GormokGUID, NPC_LIGHTBANE, NPC_LightbaneGUID, TYPE_ACIDMAW, TYPE_ANUBARAK, TYPE_DREADSCALE, and TYPE_GORMOK.
Initialize()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            CLEANED = false;
            EncounterStatus = NOT_STARTED;
            InstanceProgress = INSTANCE_PROGRESS_INITIAL;
            AttemptsLeft = 50;
            TeamIdInInstance = TEAM_NEUTRAL;
            Counter = 0;
            northrendBeastsMask = 0;
            AchievementTimer = 0;
            bDedicatedInsanity = true;
            bSwitcher = false;
            bNooneDied = true;
            events.Reset();
            events.RescheduleEvent(EVENT_CHECK_PLAYERS, 0);
            NPC_ChampionGUIDs.clear();
        }
References AchievementTimer, AttemptsLeft, bDedicatedInsanity, bNooneDied, bSwitcher, CLEANED, Counter, EncounterStatus, EVENT_CHECK_PLAYERS, INSTANCE_PROGRESS_INITIAL, InstanceProgress, northrendBeastsMask, NOT_STARTED, NPC_ChampionGUIDs, TEAM_NEUTRAL, and TeamIdInInstance.
Referenced by instance_trial_of_the_crusader_InstanceMapScript().
InstanceCleanup()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup (bool fromFailed = false) inline
        {
            if (CLEANED)
                return;
            CLEANED = true;
            switch (InstanceProgress)
            {
                case INSTANCE_PROGRESS_INITIAL:
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                        c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    break;
                case INSTANCE_PROGRESS_INTRO_DONE:
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                        c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    if (Creature* c = instance->GetCreature(NPC_GormokGUID))
                    {
                        c->AI()->DoAction(-1); // despawn summons
                        c->DespawnOrUnsummon();
                    }
                    NPC_GormokGUID.Clear();
                    if (Creature* c = instance->GetCreature(NPC_AcidmawGUID))
                        c->DespawnOrUnsummon();
                    NPC_AcidmawGUID.Clear();
                    if (Creature* c = instance->GetCreature(NPC_DreadscaleGUID))
                        c->DespawnOrUnsummon();
                    NPC_DreadscaleGUID.Clear();
                    if (Creature* c = instance->GetCreature(NPC_IcehowlGUID))
                        c->DespawnOrUnsummon();
                    NPC_IcehowlGUID.Clear();
                    northrendBeastsMask = 0;
                    break;
                case INSTANCE_PROGRESS_BEASTS_DEAD:
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                        c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    if (Creature* c = instance->GetCreature(NPC_FizzlebangGUID))
                        c->DespawnOrUnsummon();
                    NPC_FizzlebangGUID.Clear();
                    if (Creature* c = instance->GetCreature(NPC_JaraxxusGUID))
                        c->DespawnOrUnsummon();
                    NPC_JaraxxusGUID.Clear();
                    if (Creature* c = instance->GetCreature(NPC_PurpleGroundGUID))
                        c->DespawnOrUnsummon();
                    NPC_PurpleGroundGUID.Clear();
                    if (Creature* c = instance->GetCreature(NPC_PortalGUID))
                        c->DespawnOrUnsummon();
                    NPC_PortalGUID.Clear();
                    break;
                case INSTANCE_PROGRESS_JARAXXUS_INTRO_DONE:
                    if (Creature* c = instance->GetCreature(NPC_JaraxxusGUID))
                        c->DespawnOrUnsummon();
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                    {
                        c->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        if (Creature* jaraxxus = c->SummonCreature(NPC_JARAXXUS, Locs[LOC_CENTER].GetPositionX(), Locs[LOC_CENTER].GetPositionY(), Locs[LOC_CENTER].GetPositionZ(), Locs[LOC_CENTER].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 630000000))
{
                            jaraxxus->CastSpell(jaraxxus, 67924, true);
                            jaraxxus->SetReactState(REACT_AGGRESSIVE);
                            jaraxxus->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            jaraxxus->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                        }
                    }
                    break;
                case INSTANCE_PROGRESS_JARAXXUS_DEAD:
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                        c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    for (ObjectGuid const& guid : NPC_ChampionGUIDs)
                        if (Creature* c = instance->GetCreature(guid))
                            c->DespawnOrUnsummon();
                    NPC_ChampionGUIDs.clear();
                    break;
                case INSTANCE_PROGRESS_FACTION_CHAMPIONS_DEAD:
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                        c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    if (Creature* c = instance->GetCreature(NPC_DarkbaneGUID))
                    {
                        c->AI()->DoAction(-1);
                        c->DespawnOrUnsummon();
                    }
                    NPC_DarkbaneGUID.Clear();
                    if (Creature* c = instance->GetCreature(NPC_LightbaneGUID))
                    {
                        c->AI()->DoAction(-1);
                        c->DespawnOrUnsummon();
                    }
                    NPC_LightbaneGUID.Clear();
                    break;
                case INSTANCE_PROGRESS_VALKYR_DEAD:
                case INSTANCE_PROGRESS_ANUB_ARAK:
                    /*if (GameObject* floor = instance->GetGameObject(GO_FloorGUID))
                        floor->SetDestructibleState(GO_DESTRUCTIBLE_REBUILDING, nullptr, true);*/
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                    {
                        if (InstanceProgress == INSTANCE_PROGRESS_ANUB_ARAK)
{
                            c->SetVisible(false);
                            c->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        }
                        else
{
                            c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                            c->SetVisible(true);
                            c->SetFacingTo(c->GetOrientation());
                        }
                        if (Creature* t = c->FindNearestCreature(NPC_WORLD_TRIGGER, 500.0f, true))
                            t->DespawnOrUnsummon();
                    }
                    if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
                        c->DespawnOrUnsummon();
                    NPC_LichKingGUID.Clear();
                    if (Creature* c = instance->GetCreature(NPC_AnubarakGUID))
                    {
                        c->AI()->DoAction(-1);
                        c->DespawnOrUnsummon();
                    }
                    NPC_AnubarakGUID.Clear();
                    break;
                case INSTANCE_PROGRESS_DONE:
                    if (GameObject* floor = instance->GetGameObject(GO_FloorGUID))
                        floor->SetDestructibleState(GO_DESTRUCTIBLE_REBUILDING, nullptr, true);
                    if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                    {
                        c->SetVisible(false);
                        c->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    }
                    break;
            }
            if (instance->IsHeroic() && AttemptsLeft > 0 && !fromFailed && EncounterStatus == IN_PROGRESS)
            {
                --AttemptsLeft;
                Map::PlayerList const& pl = instance->GetPlayers();
                for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                    if (Player* plr = itr->GetSource())
                        plr->SendUpdateWorldState(UPDATE_STATE_UI_COUNT, AttemptsLeft);
            }
            if (instance->IsHeroic() && AttemptsLeft == 0 )
                if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                    c->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            HandleGameObject(GO_MainGateGUID, false);
            HandleGameObject(GO_EnterGateGUID, true);
            HandleGameObject(GO_WebDoorGUID, true);
            Counter = 0;
            EncounterStatus = NOT_STARTED;
            events.Reset();
            events.RescheduleEvent(EVENT_CHECK_PLAYERS, 5s);
        }
References AttemptsLeft, MapRefMgr::begin(), CLEANED, ObjectGuid::Clear(), Counter, EncounterStatus, MapRefMgr::end(), EVENT_CHECK_PLAYERS, WorldObject::FindNearestCreature(), Map::GetCreature(), Map::GetGameObject(), Position::GetOrientation(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_DESTRUCTIBLE_REBUILDING, GO_EnterGateGUID, GO_FloorGUID, GO_MainGateGUID, GO_WebDoorGUID, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, INSTANCE_PROGRESS_ANUB_ARAK, INSTANCE_PROGRESS_BEASTS_DEAD, INSTANCE_PROGRESS_DONE, INSTANCE_PROGRESS_FACTION_CHAMPIONS_DEAD, INSTANCE_PROGRESS_INITIAL, INSTANCE_PROGRESS_INTRO_DONE, INSTANCE_PROGRESS_JARAXXUS_DEAD, INSTANCE_PROGRESS_JARAXXUS_INTRO_DONE, INSTANCE_PROGRESS_VALKYR_DEAD, InstanceProgress, Map::IsHeroic(), LOC_CENTER, Locs, MOVEMENTFLAG_WALKING, northrendBeastsMask, NOT_STARTED, NPC_AcidmawGUID, NPC_AnubarakGUID, NPC_BarrettGUID, NPC_ChampionGUIDs, NPC_DarkbaneGUID, NPC_DreadscaleGUID, NPC_FizzlebangGUID, NPC_GormokGUID, NPC_IcehowlGUID, NPC_JARAXXUS, NPC_JaraxxusGUID, NPC_LichKingGUID, NPC_LightbaneGUID, NPC_PortalGUID, NPC_PurpleGroundGUID, NPC_WORLD_TRIGGER, REACT_AGGRESSIVE, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_FLAG_GOSSIP, and UPDATE_STATE_UI_COUNT.
Referenced by OnPlayerEnter(), SetData(), and Update().
IsEncounterInProgress()
bool instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            Map::PlayerList const& pl = instance->GetPlayers();
            for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                if (Player* plr = itr->GetSource())
                    if (plr->IsAlive() && !plr->IsGameMaster())
                        return EncounterStatus == IN_PROGRESS; // found alive player
            if (EncounterStatus != NOT_STARTED)
                *(const_cast<uint32*>(&EncounterStatus)) = NOT_STARTED;
            return false;
        }
References MapRefMgr::begin(), EncounterStatus, MapRefMgr::end(), Map::GetPlayers(), IN_PROGRESS, InstanceScript::instance, and NOT_STARTED.
IsValidDedicatedInsanityItem()
bool instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::IsValidDedicatedInsanityItem (ItemTemplate const * item) inline
        {
            if (!item) // should not happen, but checked in GetAverageItemLevel()
                return true;
            if (item->ItemLevel < 245)
                return true;
            if (item->ItemId == 46017) // Val'anyr, Hammer of Ancient Kings - exception, too powerful
                return false;
            if (item->ItemLevel == 245 && item->Bonding == BIND_WHEN_EQUIPPED) // this also includes items crafted from patterns obtained in ToC 10 norm/hc
                return true;
            if (validDedicatedInsanityItems.find(item->ItemId) != validDedicatedInsanityItems.end()) // list of items dropping from ToC 10 norm/hc and also items ilevel 245 buyable for emblems of triumph
                return true;
            return false;
        }
References BIND_WHEN_EQUIPPED, ItemTemplate::Bonding, ItemTemplate::ItemId, ItemTemplate::ItemLevel, and validDedicatedInsanityItems.
Referenced by DoCheckDedicatedInsanity().
OnCreatureCreate()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_BARRENT:
                    NPC_BarrettGUID = creature->GetGUID();
                    break;
                case NPC_TIRION:
                    NPC_TirionGUID = creature->GetGUID();
                    break;
                case NPC_GARROSH:
                    NPC_GarroshGUID = creature->GetGUID();
                    break;
                case NPC_VARIAN:
                    NPC_VarianGUID = creature->GetGUID();
                    break;
                case NPC_FIZZLEBANG:
                    NPC_FizzlebangGUID = creature->GetGUID();
                    break;
                case NPC_GORMOK:
                    NPC_GormokGUID = creature->GetGUID();
                    break;
                case NPC_DREADSCALE:
                    NPC_DreadscaleGUID = creature->GetGUID();
                    break;
                case NPC_ACIDMAW:
                    NPC_AcidmawGUID = creature->GetGUID();
                    break;
                case NPC_ICEHOWL:
                    NPC_IcehowlGUID = creature->GetGUID();
                    break;
                case NPC_JARAXXUS:
                    NPC_JaraxxusGUID = creature->GetGUID();
                    break;
                case NPC_LIGHTBANE:
                    NPC_LightbaneGUID = creature->GetGUID();
                    break;
                case NPC_DARKBANE:
                    NPC_DarkbaneGUID = creature->GetGUID();
                    break;
                case NPC_LICH_KING:
                    NPC_LichKingGUID = creature->GetGUID();
                    break;
                case NPC_ANUBARAK:
                    NPC_AnubarakGUID = creature->GetGUID();
                    break;
            }
        }
References Object::GetEntry(), Object::GetGUID(), NPC_ACIDMAW, NPC_AcidmawGUID, NPC_ANUBARAK, NPC_AnubarakGUID, NPC_BARRENT, NPC_BarrettGUID, NPC_DARKBANE, NPC_DarkbaneGUID, NPC_DREADSCALE, NPC_DreadscaleGUID, NPC_FIZZLEBANG, NPC_FizzlebangGUID, NPC_GARROSH, NPC_GarroshGUID, NPC_GORMOK, NPC_GormokGUID, NPC_ICEHOWL, NPC_IcehowlGUID, NPC_JARAXXUS, NPC_JaraxxusGUID, NPC_LICH_KING, NPC_LichKingGUID, NPC_LIGHTBANE, NPC_LightbaneGUID, NPC_TIRION, NPC_TirionGUID, NPC_VARIAN, and NPC_VarianGUID.
OnGameObjectCreate()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_MAIN_GATE_DOOR:
                    GO_MainGateGUID = go->GetGUID();
                    HandleGameObject(GO_MainGateGUID, false, go);
                    break;
                case GO_WEB_DOOR:
                    GO_WebDoorGUID = go->GetGUID();
                    HandleGameObject(GO_WebDoorGUID, true, go);
                    break;
                case GO_ARGENT_COLISEUM_FLOOR:
                    GO_FloorGUID = go->GetGUID();
                    if (InstanceProgress == INSTANCE_PROGRESS_ANUB_ARAK)
                        go->SetDestructibleState(GO_DESTRUCTIBLE_DAMAGED);
                    break;
                case GO_SOUTH_PORTCULLIS:
                case GO_NORTH_PORTCULLIS:
                    HandleGameObject(go->GetGUID(), false, go);
                    break;
                case GO_EAST_PORTCULLIS:
                    HandleGameObject(go->GetGUID(), true, go);
                    GO_EnterGateGUID = go->GetGUID();
                    break;
            }
        }
References Object::GetEntry(), Object::GetGUID(), GO_ARGENT_COLISEUM_FLOOR, GO_DESTRUCTIBLE_DAMAGED, GO_EAST_PORTCULLIS, GO_EnterGateGUID, GO_FloorGUID, GO_MAIN_GATE_DOOR, GO_MainGateGUID, GO_NORTH_PORTCULLIS, GO_SOUTH_PORTCULLIS, GO_WEB_DOOR, GO_WebDoorGUID, InstanceScript::HandleGameObject(), INSTANCE_PROGRESS_ANUB_ARAK, InstanceProgress, and GameObject::SetDestructibleState().
OnPlayerEnter()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnPlayerEnter (Player * plr) inline override virtual
Reimplemented from InstanceScript.
        {
            if (instance->IsHeroic())
            {
                plr->SendUpdateWorldState(UPDATE_STATE_UI_SHOW, 1);
                plr->SendUpdateWorldState(UPDATE_STATE_UI_COUNT, AttemptsLeft);
            }
            else
                plr->SendUpdateWorldState(UPDATE_STATE_UI_SHOW, 0);
            if (DoNeedCleanup(plr))
            {
                InstanceCleanup();
            }
            // if missing spawn anub'arak
            SpawnAnubArak();
            events.RescheduleEvent(EVENT_CHECK_PLAYERS, 5s);
        }
References AttemptsLeft, DoNeedCleanup(), EVENT_CHECK_PLAYERS, InstanceScript::instance, InstanceCleanup(), Map::IsHeroic(), Player::SendUpdateWorldState(), SpawnAnubArak(), UPDATE_STATE_UI_COUNT, and UPDATE_STATE_UI_SHOW.
OnUnitDeath()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnUnitDeath (Unit * u) inline override virtual
Reimplemented from ZoneScript.
        {
            if (bNooneDied && u->IsPlayer())
            {
                bNooneDied = false;
                SaveToDB();
            }
        }
References bNooneDied, Object::IsPlayer(), and InstanceScript::SaveToDB().
ReadSaveDataMore()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> InstanceProgress;
            if (instance->IsHeroic())
            {
                data >> AttemptsLeft;
                uint32 temp = 0;
                data >> temp;
                bDedicatedInsanity = !!temp;
                data >> temp;
                bNooneDied = !!temp;
            }
        }
References AttemptsLeft, bDedicatedInsanity, bNooneDied, InstanceScript::instance, InstanceProgress, and Map::IsHeroic().
SetData()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case TYPE_FAILED:
                    // - some scene here?
                    if (instance->IsHeroic() && !CLEANED )
                    {
                        if (AttemptsLeft > 0)
                            --AttemptsLeft;
                        Map::PlayerList const& pl = instance->GetPlayers();
                        for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                            if (Player* plr = itr->GetSource())
                                plr->SendUpdateWorldState(UPDATE_STATE_UI_COUNT, AttemptsLeft);
                    }
                    InstanceCleanup(true);
                    SaveToDB();
                    break;
                case TYPE_ANNOUNCER_GOSSIP_SELECT:
                    if (instance->IsHeroic() && AttemptsLeft == 0 )
                        break;
                    switch (InstanceProgress)
                    {
                        case INSTANCE_PROGRESS_INITIAL:
                            events.RescheduleEvent(EVENT_SCENE_001, 0);
                            break;
                        case INSTANCE_PROGRESS_INTRO_DONE:
                            events.RescheduleEvent(EVENT_SCENE_004, 0);
                            break;
                        case INSTANCE_PROGRESS_BEASTS_DEAD:
                            events.RescheduleEvent(EVENT_SCENE_101, 0);
                            break;
                        case INSTANCE_PROGRESS_JARAXXUS_DEAD:
                            events.RescheduleEvent(EVENT_SCENE_201, 0);
                            break;
                        case INSTANCE_PROGRESS_FACTION_CHAMPIONS_DEAD:
                            events.RescheduleEvent(EVENT_SCENE_301, 0);
                            break;
                        case INSTANCE_PROGRESS_VALKYR_DEAD:
                            events.RescheduleEvent(EVENT_SCENE_401, 0);
                            break;
                    }
                    break;
                case TYPE_GORMOK:
                    if (data == DONE)
                    {
                        if (Creature* trigger = instance->SummonCreature(WORLD_TRIGGER, Locs[LOC_CENTER], nullptr, 25000))
{
                            trigger->SetDisplayId(11686);
                            trigger->ReplaceAllUnitFlags(UNIT_FLAG_NOT_SELECTABLE);
                            trigger->SetFaction(FACTION_MONSTER);
                            trigger->SetInCombatWithZone();
                        }
                        EncounterStatus = IN_PROGRESS;
                        northrendBeastsMask |= 1;
                        if ((northrendBeastsMask & 7) == 7)
                            SetData(TYPE_NORTHREND_BEASTS_ALL, DONE);
                        else if ((northrendBeastsMask & 16) == 0)
                            events.RescheduleEvent(EVENT_SCENE_005, 2500);
                    }
                    break;
                case TYPE_JORMUNGAR:
                    if (data == DONE)
                    {
                        if (++Counter == 2)
{
                            if (Creature* trigger = instance->SummonCreature(WORLD_TRIGGER, Locs[LOC_CENTER], nullptr, 25000))
{
                                trigger->SetDisplayId(11686);
                                trigger->ReplaceAllUnitFlags(UNIT_FLAG_NOT_SELECTABLE);
                                trigger->SetFaction(FACTION_MONSTER);
                                trigger->SetInCombatWithZone();
                            }
                            if (Creature* c = instance->GetCreature(NPC_AcidmawGUID))
                                c->DespawnOrUnsummon(10000);
                            if (Creature* c = instance->GetCreature(NPC_DreadscaleGUID))
                                c->DespawnOrUnsummon(10000);
                            if (AchievementTimer + 10 >= GameTime::GetGameTime().count())
                                DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, SPELL_JORMUNGAR_ACHIEV);
                            AchievementTimer = 0;
                            EncounterStatus = IN_PROGRESS;
                            northrendBeastsMask |= 2;
                            if ((northrendBeastsMask & 7) == 7)
                                SetData(TYPE_NORTHREND_BEASTS_ALL, DONE);
                            else if ((northrendBeastsMask & 32) == 0)
{
                                Counter = 0;
                                events.RescheduleEvent(EVENT_SCENE_006, 2500);
                            }
                        }
                        else // first one died, start timer for achievement
{
                            AchievementTimer = GameTime::GetGameTime().count();
                        }
                    }
                    else
                        AchievementTimer = 0;
                    break;
                case TYPE_ICEHOWL:
                    if (data == DONE)
                    {
                        northrendBeastsMask |= 4;
                        if ((northrendBeastsMask & 7) == 7)
                            SetData(TYPE_NORTHREND_BEASTS_ALL, DONE);
                    }
                    break;
                case TYPE_NORTHREND_BEASTS_ALL:
                    if (data == DONE)
                    {
                        northrendBeastsMask = 0;
                        EncounterStatus = NOT_STARTED;
                        InstanceProgress = INSTANCE_PROGRESS_BEASTS_DEAD;
                        HandleGameObject(GO_EnterGateGUID, true);
                        events.CancelEvent(EVENT_NORTHREND_BEASTS_ENRAGE);
                        events.RescheduleEvent(EVENT_SCENE_BEASTS_DONE, 2500);
                        SaveToDB();
                    }
                    break;
                case TYPE_JARAXXUS:
                    EncounterStatus = data == IN_PROGRESS ? IN_PROGRESS : NOT_STARTED;
                    if (data == IN_PROGRESS)
                        HandleGameObject(GO_EnterGateGUID, false);
                    else if (data == DONE)
                    {
                        HandleGameObject(GO_EnterGateGUID, true);
                        InstanceProgress = INSTANCE_PROGRESS_JARAXXUS_DEAD;
                        events.RescheduleEvent(EVENT_SCENE_110, 2500);
                        SaveToDB();
                    }
                    break;
                case TYPE_FACTION_CHAMPIONS:
                    if (data == DONE)
                    {
                        if (++Counter >= NPC_ChampionGUIDs.size())
{
                            if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                                c->CastSpell(c, SPELL_FACTION_CHAMPIONS_KILL_CREDIT, true);
                            Counter = 0;
                            EncounterStatus = NOT_STARTED;
                            InstanceProgress = INSTANCE_PROGRESS_FACTION_CHAMPIONS_DEAD;
                            events.RescheduleEvent(EVENT_SCENE_FACTION_CHAMPIONS_DEAD, 2500);
                            for (ObjectGuid const& guid : NPC_ChampionGUIDs)
                                if (Creature* c = instance->GetCreature(guid))
                                    c->DespawnOrUnsummon(15000);
                            NPC_ChampionGUIDs.clear();
                            if (Creature* c = instance->GetCreature(NPC_TirionGUID))
{
                                uint32 cacheEntry = 0;
                                switch (instance->GetDifficulty())
{
                                    case RAID_DIFFICULTY_10MAN_NORMAL:
                                        cacheEntry = GO_CRUSADERS_CACHE_10;
                                        break;
                                    case RAID_DIFFICULTY_25MAN_NORMAL:
                                        cacheEntry = GO_CRUSADERS_CACHE_25;
                                        break;
                                    case RAID_DIFFICULTY_10MAN_HEROIC:
                                        cacheEntry = GO_CRUSADERS_CACHE_10_H;
                                        break;
                                    case RAID_DIFFICULTY_25MAN_HEROIC:
                                        cacheEntry = GO_CRUSADERS_CACHE_25_H;
                                        break;
                                }
                                if (GameObject* go = c->SummonGameObject(cacheEntry, Locs[LOC_CENTER].GetPositionX(), Locs[LOC_CENTER].GetPositionY(), Locs[LOC_CENTER].GetPositionZ(), Locs[LOC_CENTER].GetOrientation(), 0.0f, 0.0f, 0.0f, 0.0f, 630000000))
{
                                    go->SetLootRecipient(instance);
                                }
                            }
                            HandleGameObject(GO_EnterGateGUID, true);
                            if (AchievementTimer + 60 >= GameTime::GetGameTime().count())
                                DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, SPELL_RESILIENCE_WILL_FIX_IT_CREDIT);
                            AchievementTimer = 0;
                            SaveToDB();
                        }
                        else if (Counter == 1)
                            AchievementTimer = GameTime::GetGameTime().count();
                    }
                    break;
                case TYPE_FACTION_CHAMPIONS_START:
                    {
                        EncounterStatus = IN_PROGRESS;
                        AchievementTimer = 0;
                        for (ObjectGuid const& guid : NPC_ChampionGUIDs)
                            if (Creature* c = instance->GetCreature(guid))
                                if (!c->IsInCombat())
                                    if (Unit* target = c->SelectNearestTarget(200.0f))
                                        c->AI()->AttackStart(target);
                    }
                    break;
                case TYPE_FACTION_CHAMPIONS_PLAYER_DIED:
                    if (urand(0, 2) == 0 )
                    {
                        if (TeamIdInInstance == TEAM_HORDE)
{
                            if (Creature* pTemp = instance->GetCreature(NPC_VarianGUID))
                                pTemp->AI()->Talk(SAY_VARIAN_KILL_HORDE_PLAYER_1);
                        }
                        else if (Creature* pTemp = instance->GetCreature(NPC_GarroshGUID))
                            pTemp->AI()->Talk(SAY_GARROSH_KILL_ALLIANCE_PLAYER_1);
                    }
                    break;
                case TYPE_VALKYR:
                    if (data == DONE && ++Counter >= 2)
                    {
                        Counter = 0;
                        EncounterStatus = NOT_STARTED;
                        InstanceProgress = INSTANCE_PROGRESS_VALKYR_DEAD;
                        DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, 34497, 1); // Lightbane
                        DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, 34496, 1); // Darkbane
                        events.RescheduleEvent(EVENT_SCENE_VALKYR_DEAD, 2500);
                        HandleGameObject(GO_EnterGateGUID, true);
                        SaveToDB();
                    }
                    break;
                case TYPE_ANUBARAK:
                    if (data == IN_PROGRESS)
                    {
                        EncounterStatus = IN_PROGRESS;
                        HandleGameObject(GO_WebDoorGUID, false);
                    }
                    else if (data == DONE)
                    {
                        Counter = 0;
                        EncounterStatus = NOT_STARTED;
                        InstanceProgress = INSTANCE_PROGRESS_DONE;
                        HandleGameObject(GO_EnterGateGUID, true);
                        HandleGameObject(GO_WebDoorGUID, true);
                        SaveToDB();
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
{
                            c->UpdatePosition(Locs[LOC_TIRION_FINAL], true);
                            c->StopMovingOnCurrentPos();
                            c->SetFacingTo(Locs[LOC_TIRION_FINAL].GetOrientation());
                            events.RescheduleEvent(EVENT_SCENE_501, 20000);
                        }
                        if (GameObject* floor = instance->GetGameObject(GO_FloorGUID))
                            floor->SetDestructibleState(GO_DESTRUCTIBLE_REBUILDING, nullptr, true);
                    }
                    break;
            }
        }
References ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, AchievementTimer, AttemptsLeft, MapRefMgr::begin(), CLEANED, Counter, DONE, InstanceScript::DoUpdateAchievementCriteria(), EncounterStatus, MapRefMgr::end(), EVENT_NORTHREND_BEASTS_ENRAGE, EVENT_SCENE_001, EVENT_SCENE_004, EVENT_SCENE_005, EVENT_SCENE_006, EVENT_SCENE_101, EVENT_SCENE_110, EVENT_SCENE_201, EVENT_SCENE_301, EVENT_SCENE_401, EVENT_SCENE_501, EVENT_SCENE_BEASTS_DONE, EVENT_SCENE_FACTION_CHAMPIONS_DEAD, EVENT_SCENE_VALKYR_DEAD, FACTION_MONSTER, Map::GetCreature(), Map::GetDifficulty(), Map::GetGameObject(), GameTime::GetGameTime(), Position::GetOrientation(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_CRUSADERS_CACHE_10, GO_CRUSADERS_CACHE_10_H, GO_CRUSADERS_CACHE_25, GO_CRUSADERS_CACHE_25_H, GO_DESTRUCTIBLE_REBUILDING, GO_EnterGateGUID, GO_FloorGUID, GO_WebDoorGUID, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, INSTANCE_PROGRESS_BEASTS_DEAD, INSTANCE_PROGRESS_DONE, INSTANCE_PROGRESS_FACTION_CHAMPIONS_DEAD, INSTANCE_PROGRESS_INITIAL, INSTANCE_PROGRESS_INTRO_DONE, INSTANCE_PROGRESS_JARAXXUS_DEAD, INSTANCE_PROGRESS_VALKYR_DEAD, InstanceCleanup(), InstanceProgress, Map::IsHeroic(), LOC_CENTER, LOC_TIRION_FINAL, Locs, northrendBeastsMask, NOT_STARTED, NPC_AcidmawGUID, NPC_ChampionGUIDs, NPC_DreadscaleGUID, NPC_GarroshGUID, NPC_TirionGUID, NPC_VarianGUID, RAID_DIFFICULTY_10MAN_HEROIC, RAID_DIFFICULTY_10MAN_NORMAL, RAID_DIFFICULTY_25MAN_HEROIC, RAID_DIFFICULTY_25MAN_NORMAL, InstanceScript::SaveToDB(), SAY_GARROSH_KILL_ALLIANCE_PLAYER_1, SAY_VARIAN_KILL_HORDE_PLAYER_1, SetData(), SPELL_FACTION_CHAMPIONS_KILL_CREDIT, SPELL_JORMUNGAR_ACHIEV, SPELL_RESILIENCE_WILL_FIX_IT_CREDIT, Map::SummonCreature(), WorldObject::SummonGameObject(), TEAM_HORDE, TeamIdInInstance, TYPE_ANNOUNCER_GOSSIP_SELECT, TYPE_ANUBARAK, TYPE_FACTION_CHAMPIONS, TYPE_FACTION_CHAMPIONS_PLAYER_DIED, TYPE_FACTION_CHAMPIONS_START, TYPE_FAILED, TYPE_GORMOK, TYPE_ICEHOWL, TYPE_JARAXXUS, TYPE_JORMUNGAR, TYPE_NORTHREND_BEASTS_ALL, TYPE_VALKYR, UNIT_FLAG_NOT_SELECTABLE, UPDATE_STATE_UI_COUNT, urand(), and WORLD_TRIGGER.
Referenced by SetData().
SpawnAnubArak()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SpawnAnubArak () inline
        {
            if (InstanceProgress == INSTANCE_PROGRESS_ANUB_ARAK)
            {
                if (Creature* barrett = instance->GetCreature(NPC_BarrettGUID))
                {
                    barrett->SetVisible(false);
                    if (AttemptsLeft)
                        if (!ObjectAccessor::GetCreature(*barrett, NPC_AnubarakGUID))
                            barrett->SummonCreature(NPC_ANUBARAK, Locs[LOC_ANUB].GetPositionX(), Locs[LOC_ANUB].GetPositionY(), Locs[LOC_ANUB].GetPositionZ(), Locs[LOC_ANUB].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 630000000);
                }
                // move corpses
                const ObjectGuid npcs[4] = { NPC_IcehowlGUID, NPC_JaraxxusGUID, NPC_LightbaneGUID, NPC_DarkbaneGUID };
                for (ObjectGuid const& i : npcs)
                {
                    if (Creature* c = instance->GetCreature(i))
                    {
                        if (c->GetGUID() == NPC_IcehowlGUID)
                            c->UpdatePosition(626.57f, 162.8f, 140.25f, 4.44f, true);
                        else if (c->GetGUID() == NPC_JaraxxusGUID)
                            c->UpdatePosition(603.92f, 102.61f, 141.85f, 1.4f, true);
                        else if (c->GetGUID() == NPC_LightbaneGUID)
                            c->UpdatePosition(634.58f, 147.16f, 140.5f, 3.02f, true);
                        else if (c->GetGUID() == NPC_DarkbaneGUID)
                            c->UpdatePosition(630.88f, 131.39f, 140.8f, 3.02f, true);
                        c->StopMovingOnCurrentPos();
                        c->DestroyForNearbyPlayers();
                    }
                }
            }
        }
References AttemptsLeft, Map::GetCreature(), ObjectAccessor::GetCreature(), InstanceScript::instance, INSTANCE_PROGRESS_ANUB_ARAK, InstanceProgress, LOC_ANUB, Locs, NPC_ANUBARAK, NPC_AnubarakGUID, NPC_BarrettGUID, NPC_DarkbaneGUID, NPC_IcehowlGUID, NPC_JaraxxusGUID, NPC_LightbaneGUID, and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
Referenced by OnPlayerEnter(), and Update().
Update()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_CHECK_PLAYERS:
                    {
                        if (bSwitcher) // used to double the check interval
                            DoCheckDedicatedInsanity();
                        bSwitcher = !bSwitcher;
                        if (DoNeedCleanup())
{
                            InstanceCleanup();
                        }
                        events.Repeat(5s);
                    }
                    break;
                case EVENT_OPEN_GATE:
                    {
                        HandleGameObject(GO_MainGateGUID, true);
                        break;
                    }
                case EVENT_CLOSE_GATE:
                    {
                        HandleGameObject(GO_MainGateGUID, false);
                    }
                    break;
                case EVENT_SCENE_001:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_0_01);
                        events.RescheduleEvent(EVENT_SCENE_002, 22000);
                    }
                    break;
                case EVENT_SCENE_002:
                    {
                        if (Creature* c = instance->GetCreature(NPC_VarianGUID))
                            c->AI()->Talk(SAY_STAGE_0_03a);
                        events.RescheduleEvent(EVENT_SCENE_003, 5000);
                    }
                    break;
                case EVENT_SCENE_003:
                    {
                        if (Creature* c = instance->GetCreature(NPC_GarroshGUID))
                            c->AI()->Talk(SAY_STAGE_0_03h);
                        events.RescheduleEvent(EVENT_SCENE_004, 8000);
                    }
                    break;
                case EVENT_SCENE_004:
                    {
                        InstanceProgress = INSTANCE_PROGRESS_INTRO_DONE;
                        EncounterStatus = IN_PROGRESS;
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_0_02);
                        HandleGameObject(GO_MainGateGUID, true);
                        HandleGameObject(GO_EnterGateGUID, false);
                        events.RescheduleEvent(EVENT_SUMMON_GORMOK, 1000);
                        if (instance->IsHeroic())
{
                            events.RescheduleEvent(EVENT_SCENE_005, 150000);
                            events.RescheduleEvent(EVENT_SCENE_006, 340000);
                            events.RescheduleEvent(EVENT_NORTHREND_BEASTS_ENRAGE, 520000);
                        }
                    }
                    break;
                case EVENT_NORTHREND_BEASTS_ENRAGE:
                    if (Creature* c = instance->GetCreature(NPC_GormokGUID))
                        if (c->IsAlive())
                            c->CastSpell(c, 26662, true);
                    if (Creature* c = instance->GetCreature(NPC_AcidmawGUID))
                        if (c->IsAlive())
                            c->CastSpell(c, 26662, true);
                    if (Creature* c = instance->GetCreature(NPC_DreadscaleGUID))
                        if (c->IsAlive())
                            c->CastSpell(c, 26662, true);
                    if (Creature* c = instance->GetCreature(NPC_IcehowlGUID))
                        if (c->IsAlive())
                            c->CastSpell(c, 26662, true);
                    break;
                case EVENT_SUMMON_GORMOK:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            if (Creature* gormok = c->SummonCreature(NPC_GORMOK, Locs[LOC_BEHIND_GATE].GetPositionX(), Locs[LOC_BEHIND_GATE].GetPositionY(), Locs[LOC_BEHIND_GATE].GetPositionZ(), Locs[LOC_BEHIND_GATE].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30000))
                                gormok->GetMotionMaster()->MovePoint(0, Locs[LOC_GATE_FRONT].GetPositionX(), Locs[LOC_GATE_FRONT].GetPositionY(), Locs[LOC_GATE_FRONT].GetPositionZ());
                        events.RescheduleEvent(EVENT_GORMOK_ATTACK, 10000);
                        events.RescheduleEvent(EVENT_CLOSE_GATE, 6000);
                    }
                    break;
                case EVENT_GORMOK_ATTACK:
                    {
                        northrendBeastsMask = 0;
                        if (Creature* c = instance->GetCreature(NPC_GormokGUID))
{
                            c->SetReactState(REACT_AGGRESSIVE);
                            c->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                            if (Unit* target = c->SelectNearestTarget(200.0f))
{
                                c->AI()->AttackStart(target);
                                c->AI()->DoZoneInCombat();
                            }
                        }
                        break;
                    }
                case EVENT_SCENE_005:
                    {
                        northrendBeastsMask |= 16;
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_0_04);
                        events.RescheduleEvent(EVENT_OPEN_GATE, 3000);
                        events.RescheduleEvent(EVENT_SUMMON_ACIDMAW_AND_DREADSCALE, 4000);
                        break;
                    }
                case EVENT_SUMMON_ACIDMAW_AND_DREADSCALE:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
{
                            if (Creature* dreadscale = c->SummonCreature(NPC_DREADSCALE, Locs[LOC_BEHIND_GATE].GetPositionX(), Locs[LOC_BEHIND_GATE].GetPositionY(), Locs[LOC_BEHIND_GATE].GetPositionZ(), Locs[LOC_BEHIND_GATE].GetOrientation(), TEMPSUMMON_MANUAL_DESPAWN))
                                dreadscale->GetMotionMaster()->MovePoint(0, Locs[LOC_BEHIND_GATE].GetPositionX(), Locs[LOC_BEHIND_GATE].GetPositionY() - 25.0f, Locs[LOC_BEHIND_GATE].GetPositionZ());
                            if (Creature* acidmaw = c->SummonCreature(NPC_ACIDMAW, Locs[LOC_ACIDMAW].GetPositionX(), Locs[LOC_ACIDMAW].GetPositionY(), Locs[LOC_ACIDMAW].GetPositionZ(), Locs[LOC_ACIDMAW].GetOrientation(), TEMPSUMMON_MANUAL_DESPAWN))
                                acidmaw->AddAura(53421, acidmaw);
                        }
                        events.RescheduleEvent(EVENT_SCENE_005_2, 4000);
                        break;
                    }
                case EVENT_SCENE_005_2:
                    {
                        if (Creature* dreadscale = instance->GetCreature(NPC_DreadscaleGUID))
                            dreadscale->GetMotionMaster()->MovePoint(0, Locs[LOC_DREADSCALE].GetPositionX(), Locs[LOC_DREADSCALE].GetPositionY(), Locs[LOC_DREADSCALE].GetPositionZ());
                        events.RescheduleEvent(EVENT_ACIDMAW_AND_DREADSCALE_ATTACK, 7000);
                        break;
                    }
                case EVENT_ACIDMAW_AND_DREADSCALE_ATTACK:
                    {
                        HandleGameObject(GO_MainGateGUID, false);
                        if (Creature* c = instance->GetCreature(NPC_DreadscaleGUID))
{
                            c->SetReactState(REACT_AGGRESSIVE);
                            c->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                            if (Unit* target = c->SelectNearestTarget(200.0f))
{
                                c->AI()->AttackStart(target);
                                c->AI()->DoZoneInCombat();
                            }
                        }
                        if (Creature* c = instance->GetCreature(NPC_AcidmawGUID))
{
                            c->SetReactState(REACT_AGGRESSIVE);
                            c->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                            if (Unit* target = c->SelectNearestTarget(200.0f))
{
                                c->RemoveAura(53421);
                                c->CastSpell(c, 66947, false);
                                c->AI()->AttackStart(target);
                                c->AI()->DoZoneInCombat();
                            }
                        }
                        break;
                    }
                case EVENT_SCENE_006:
                    {
                        northrendBeastsMask |= 32;
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_0_05);
                        events.RescheduleEvent(EVENT_OPEN_GATE, 2000);
                        events.RescheduleEvent(EVENT_SUMMON_ICEHOWL, 3000);
                        break;
                    }
                case EVENT_SUMMON_ICEHOWL:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            if (Creature* icehowl = c->SummonCreature(NPC_ICEHOWL, Locs[LOC_BEHIND_GATE].GetPositionX(), Locs[LOC_BEHIND_GATE].GetPositionY(), Locs[LOC_BEHIND_GATE].GetPositionZ(), Locs[LOC_BEHIND_GATE].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 630000000))
                                icehowl->GetMotionMaster()->MovePoint(0, Locs[LOC_GATE_FRONT].GetPositionX(), Locs[LOC_GATE_FRONT].GetPositionY(), Locs[LOC_GATE_FRONT].GetPositionZ());
                        events.RescheduleEvent(EVENT_ICEHOWL_ATTACK, 10000);
                        events.RescheduleEvent(EVENT_CLOSE_GATE, 6000);
                        break;
                    }
                case EVENT_ICEHOWL_ATTACK:
                    {
                        if (Creature* c = instance->GetCreature(NPC_IcehowlGUID))
{
                            c->SetReactState(REACT_AGGRESSIVE);
                            c->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                            if (Unit* target = c->SelectNearestTarget(200.0f))
{
                                c->AI()->AttackStart(target);
                                c->AI()->DoZoneInCombat();
                            }
                        }
                        break;
                    }
                case EVENT_SCENE_BEASTS_DONE:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_0_06);
                        if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                            c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        break;
                    }
                case EVENT_SCENE_101:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
{
                            HandleGameObject(GO_MainGateGUID, true);
                            c->AI()->Talk(SAY_STAGE_1_01);
                            if (Creature* fizzlebang = c->SummonCreature(NPC_FIZZLEBANG, Locs[LOC_BEHIND_GATE].GetPositionX(), Locs[LOC_BEHIND_GATE].GetPositionY(), Locs[LOC_BEHIND_GATE].GetPositionZ(), Locs[LOC_BEHIND_GATE].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 300000))
{
                                fizzlebang->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                fizzlebang->GetMotionMaster()->MovePoint(0, Locs[LOC_BEHIND_GATE].GetPositionX(), Locs[LOC_BEHIND_GATE].GetPositionY() - 65.0f, Locs[LOC_BEHIND_GATE].GetPositionZ() - 1.0f);
                            }
                            events.RescheduleEvent(EVENT_SCENE_102, 20000);
                            // move Icehowl to side, can't remove corpse because of loot!
                            if (Creature* icehowl = instance->GetCreature(NPC_IcehowlGUID))
{
                                icehowl->UpdatePosition(513.19f, 139.48f, 395.22f, 3 * M_PI / 2, true);
                                icehowl->StopMovingOnCurrentPos();
                                icehowl->DestroyForNearbyPlayers();
                            }
                        }
                        break;
                    }
                case EVENT_SCENE_102:
                    {
                        HandleGameObject(GO_MainGateGUID, false);
                        if (Creature* c = instance->GetCreature(NPC_FizzlebangGUID))
                            c->AI()->Talk(SAY_STAGE_1_02);
                        events.RescheduleEvent(EVENT_SCENE_103, 11000);
                        break;
                    }
                case EVENT_SCENE_103:
                    {
                        if (Creature* c = instance->GetCreature(NPC_FizzlebangGUID))
{
                            c->AI()->Talk(SAY_STAGE_1_03);
                            c->HandleEmoteCommand(EMOTE_STATE_SPELL_PRECAST);
                            if (Creature* trigger = c->SummonCreature(NPC_PURPLE_GROUND, Locs[LOC_CENTER].GetPositionX(), Locs[LOC_CENTER].GetPositionY(), Locs[LOC_CENTER].GetPositionZ(), Locs[LOC_CENTER].GetOrientation(), TEMPSUMMON_MANUAL_DESPAWN))
                                NPC_PurpleGroundGUID = trigger->GetGUID();
                        }
                        events.RescheduleEvent(EVENT_SCENE_104, 5000);
                        break;
                    }
                case EVENT_SCENE_104:
                    {
                        if (Creature* c = instance->GetCreature(NPC_FizzlebangGUID))
{
                            if (Creature* portal = c->SummonCreature(NPC_WORLD_TRIGGER, Locs[LOC_CENTER].GetPositionX(), Locs[LOC_CENTER].GetPositionY(), Locs[LOC_CENTER].GetPositionZ(), Locs[LOC_CENTER].GetOrientation(), TEMPSUMMON_MANUAL_DESPAWN))
{
                                NPC_PortalGUID = portal->GetGUID();
                                portal->SetObjectScale(3.0f);
                                portal->SetReactState(REACT_PASSIVE);
                                portal->CastSpell(portal, SPELL_WILFRED_PORTAL, true);
                            }
                            c->HandleEmoteCommand(EMOTE_STATE_SPELL_PRECAST);
                        }
                        events.RescheduleEvent(EVENT_SUMMON_JARAXXUS, 5000);
                        break;
                    }
                case EVENT_SUMMON_JARAXXUS:
                    {
                        if (Creature* c = instance->GetCreature(NPC_FizzlebangGUID))
{
                            if (Creature* jaraxxus = c->SummonCreature(NPC_JARAXXUS, Locs[LOC_CENTER].GetPositionX(), Locs[LOC_CENTER].GetPositionY(), Locs[LOC_CENTER].GetPositionZ(), Locs[LOC_CENTER].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 630000000))
                                jaraxxus->GetMotionMaster()->MovePoint(0, Locs[LOC_CENTER].GetPositionX(), Locs[LOC_CENTER].GetPositionY() - 10.0f, Locs[LOC_CENTER].GetPositionZ());
                            c->HandleEmoteCommand(EMOTE_STATE_NONE);
                            c->AI()->Talk(SAY_STAGE_1_04);
                        }
                        events.RescheduleEvent(EVENT_SCENE_105, 3000);
                        break;
                    }
                case EVENT_SCENE_105:
                    {
                        if (Creature* c = instance->GetCreature(NPC_JaraxxusGUID))
                            c->SetFacingTo(M_PI / 2);
                        if (Creature* c = instance->GetCreature(NPC_PurpleGroundGUID))
                            c->DespawnOrUnsummon();
                        NPC_PurpleGroundGUID.Clear();
                        if (Creature* c = instance->GetCreature(NPC_PortalGUID))
                            c->DespawnOrUnsummon();
                        NPC_PortalGUID.Clear();
                        events.RescheduleEvent(EVENT_SCENE_106, 10000);
                        break;
                    }
                case EVENT_SCENE_106:
                    {
                        if (Creature* c = instance->GetCreature(NPC_JaraxxusGUID))
                            c->AI()->Talk(SAY_STAGE_1_05);
                        events.RescheduleEvent(EVENT_SCENE_107, 5000);
                        break;
                    }
                case EVENT_SCENE_107:
                    {
                        if (Creature* c = instance->GetCreature(NPC_FizzlebangGUID))
                            c->AI()->Talk(SAY_STAGE_1_06);
                        events.RescheduleEvent(EVENT_SCENE_108, 800);
                        break;
                    }
                case EVENT_SCENE_108:
                    {
                        if (Creature* c = instance->GetCreature(NPC_JaraxxusGUID))
{
                            c->AI()->Talk(SAY_STAGE_1_06_1);
                            if (Creature* f = instance->GetCreature(NPC_FizzlebangGUID))
{
                                c->CastSpell(f, 67888, true);
                                Unit::Kill(f, f);
                            }
                        }
                        events.RescheduleEvent(EVENT_SCENE_109, 5000);
                        break;
                    }
                case EVENT_SCENE_109:
                    {
                        if (Creature* c = instance->GetCreature(NPC_JaraxxusGUID))
                            c->SetFacingTo(3 * M_PI / 2);
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_1_07);
                        events.RescheduleEvent(EVENT_JARAXXUS_ATTACK, 6000);
                        break;
                    }
                case EVENT_JARAXXUS_ATTACK:
                    {
                        InstanceProgress = INSTANCE_PROGRESS_JARAXXUS_INTRO_DONE;
                        if (Creature* c = instance->GetCreature(NPC_JaraxxusGUID))
{
                            c->SetReactState(REACT_AGGRESSIVE);
                            c->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                            if (Unit* target = c->SelectNearestTarget(200.0f))
{
                                c->AI()->AttackStart(target);
                                c->AI()->DoZoneInCombat();
                            }
                        }
                        break;
                    }
                case EVENT_SCENE_110:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_1_08);
                        events.RescheduleEvent(EVENT_SCENE_111, 18000);
                        break;
                    }
                case EVENT_SCENE_111:
                    {
                        if (Creature* c = instance->GetCreature(NPC_GarroshGUID))
                            c->AI()->Talk(SAY_STAGE_1_09);
                        events.RescheduleEvent(EVENT_SCENE_112, 9000);
                        break;
                    }
                case EVENT_SCENE_112:
                    {
                        if (Creature* c = instance->GetCreature(NPC_VarianGUID))
                            c->AI()->Talk(SAY_STAGE_1_10);
                        events.RescheduleEvent(EVENT_SCENE_113, 5000);
                        break;
                    }
                case EVENT_SCENE_113:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_1_11);
                        if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                            c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        break;
                    }
                case EVENT_SCENE_201:
                    {
                        // move Jaraxxus to side, can't remove corpse because of loot!
                        if (Creature* jaraxxus = instance->GetCreature(NPC_JaraxxusGUID))
{
                            jaraxxus->UpdatePosition(613.83f, 139.5f, 395.22f, 3 * M_PI / 2, true);
                            jaraxxus->StopMovingOnCurrentPos();
                            jaraxxus->DestroyForNearbyPlayers();
                        }
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_2_01);
                        events.RescheduleEvent(EVENT_SCENE_202, 9000);
                        break;
                    }
                case EVENT_SCENE_202:
                    {
                        Map::PlayerList const& pl = instance->GetPlayers();
                        for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                            if (Player* plr = itr->GetSource())
                                if (!plr->IsGameMaster())
{
                                    TeamIdInInstance = plr->GetTeamId();
                                    break;
                                }
                        if (TeamIdInInstance == TEAM_ALLIANCE)
{
                            if (Creature* c = instance->GetCreature(NPC_GarroshGUID))
                                c->AI()->Talk(SAY_STAGE_2_02h);
                            events.RescheduleEvent(EVENT_SCENE_203, 15000);
                        }
                        else
{
                            if (Creature* c = instance->GetCreature(NPC_VarianGUID))
                                c->AI()->Talk(SAY_STAGE_2_02a);
                            events.RescheduleEvent(EVENT_SCENE_203, 18000);
                        }
                        break;
                    }
                case EVENT_SCENE_203:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_2_03);
                        events.RescheduleEvent(EVENT_SCENE_204, 5000);
                        break;
                    }
                case EVENT_SCENE_204:
                    {
                        if (TeamIdInInstance == TEAM_ALLIANCE)
{
                            if (Creature* c = instance->GetCreature(NPC_GarroshGUID))
                                c->AI()->Talk(SAY_STAGE_2_04h);
                            events.RescheduleEvent(EVENT_SCENE_205, 6000);
                        }
                        else
{
                            if (Creature* c = instance->GetCreature(NPC_VarianGUID))
                                c->AI()->Talk(SAY_STAGE_2_04a);
                            events.RescheduleEvent(EVENT_SCENE_205, 5000);
                        }
                        events.RescheduleEvent(EVENT_SUMMON_CHAMPIONS, 2500);
                        break;
                    }
                case EVENT_SCENE_205:
                    {
                        if (Creature* c = instance->GetCreature(TeamIdInInstance == TEAM_ALLIANCE ? NPC_VarianGUID : NPC_GarroshGUID))
                            c->AI()->Talk(TeamIdInInstance == TEAM_ALLIANCE ? SAY_STAGE_2_05a : SAY_STAGE_2_05h);
                        break;
                    }
                case EVENT_SUMMON_CHAMPIONS:
                    {
                        std::vector<uint32> vHealerEntries;
                        vHealerEntries.push_back(TeamIdInInstance == TEAM_ALLIANCE ? NPC_HORDE_DRUID_RESTORATION : NPC_ALLIANCE_DRUID_RESTORATION);
                        vHealerEntries.push_back(TeamIdInInstance == TEAM_ALLIANCE ? NPC_HORDE_PALADIN_HOLY : NPC_ALLIANCE_PALADIN_HOLY);
                        vHealerEntries.push_back(TeamIdInInstance == TEAM_ALLIANCE ? NPC_HORDE_PRIEST_DISCIPLINE : NPC_ALLIANCE_PRIEST_DISCIPLINE);
                        vHealerEntries.push_back(TeamIdInInstance == TEAM_ALLIANCE ? NPC_HORDE_SHAMAN_RESTORATION : NPC_ALLIANCE_SHAMAN_RESTORATION);
                        std::vector<uint32> vOtherEntries;
                        vOtherEntries.push_back(TeamIdInInstance == TEAM_ALLIANCE ? NPC_HORDE_DEATH_KNIGHT : NPC_ALLIANCE_DEATH_KNIGHT);
                        vOtherEntries.push_back(TeamIdInInstance == TEAM_ALLIANCE ? NPC_HORDE_HUNTER : NPC_ALLIANCE_HUNTER);
                        vOtherEntries.push_back(TeamIdInInstance == TEAM_ALLIANCE ? NPC_HORDE_MAGE : NPC_ALLIANCE_MAGE);
                        vOtherEntries.push_back(TeamIdInInstance == TEAM_ALLIANCE ? NPC_HORDE_ROGUE : NPC_ALLIANCE_ROGUE);
                        vOtherEntries.push_back(TeamIdInInstance == TEAM_ALLIANCE ? NPC_HORDE_WARLOCK : NPC_ALLIANCE_WARLOCK);
                        vOtherEntries.push_back(TeamIdInInstance == TEAM_ALLIANCE ? NPC_HORDE_WARRIOR : NPC_ALLIANCE_WARRIOR);
                        uint8 healersSubtracted = 2;
                        if (instance->GetSpawnMode() == RAID_DIFFICULTY_25MAN_NORMAL || instance->GetSpawnMode() == RAID_DIFFICULTY_25MAN_HEROIC )
                            healersSubtracted = 1;
                        for( uint8 i = 0; i < healersSubtracted; ++i )
{
                            uint8 pos = urand(0, vHealerEntries.size() - 1);
                            switch (vHealerEntries[pos])
{
                                case NPC_ALLIANCE_DRUID_RESTORATION:
                                    vOtherEntries.push_back(NPC_ALLIANCE_DRUID_BALANCE);
                                    break;
                                case NPC_HORDE_DRUID_RESTORATION:
                                    vOtherEntries.push_back(NPC_HORDE_DRUID_BALANCE);
                                    break;
                                case NPC_ALLIANCE_PALADIN_HOLY:
                                    vOtherEntries.push_back(NPC_ALLIANCE_PALADIN_RETRIBUTION);
                                    break;
                                case NPC_HORDE_PALADIN_HOLY:
                                    vOtherEntries.push_back(NPC_HORDE_PALADIN_RETRIBUTION);
                                    break;
                                case NPC_ALLIANCE_PRIEST_DISCIPLINE:
                                    vOtherEntries.push_back(NPC_ALLIANCE_PRIEST_SHADOW);
                                    break;
                                case NPC_HORDE_PRIEST_DISCIPLINE:
                                    vOtherEntries.push_back(NPC_HORDE_PRIEST_SHADOW);
                                    break;
                                case NPC_ALLIANCE_SHAMAN_RESTORATION:
                                    vOtherEntries.push_back(NPC_ALLIANCE_SHAMAN_ENHANCEMENT);
                                    break;
                                case NPC_HORDE_SHAMAN_RESTORATION:
                                    vOtherEntries.push_back(NPC_HORDE_SHAMAN_ENHANCEMENT);
                                    break;
                            }
                            vHealerEntries.erase(vHealerEntries.begin() + pos);
                        }
                        if (instance->GetSpawnMode() == RAID_DIFFICULTY_10MAN_NORMAL || instance->GetSpawnMode() == RAID_DIFFICULTY_10MAN_HEROIC )
                            for( uint8 i = 0; i < 4; ++i )
                                vOtherEntries.erase(vOtherEntries.begin() + urand(0, vOtherEntries.size() - 1));
                        for( std::vector<uint32>::iterator itr = vHealerEntries.begin(); itr != vHealerEntries.end(); ++itr )
                            vOtherEntries.push_back(*itr);
                        uint8 pos2 = 10;
                        for( std::vector<uint32>::iterator itr = vOtherEntries.begin(); itr != vOtherEntries.end(); ++itr )
{
                            if (Creature* pTemp = instance->SummonCreature(*itr, FactionChampionLoc[urand(0, 4) + (TeamIdInInstance == TEAM_ALLIANCE ? 0 : 5)]))
{
                                NPC_ChampionGUIDs.push_back(pTemp->GetGUID());
                                pTemp->SetHomePosition((TeamIdInInstance == TEAM_ALLIANCE ? FactionChampionLoc[pos2].GetPositionX() : (Locs[LOC_CENTER].GetPositionX() * 2 - FactionChampionLoc[pos2].GetPositionX())), FactionChampionLoc[pos2].GetPositionY(), FactionChampionLoc[pos2].GetPositionZ(), 0.0f);
                                pTemp->GetMotionMaster()->MoveJump((TeamIdInInstance == TEAM_ALLIANCE ? FactionChampionLoc[pos2].GetPositionX() : (Locs[LOC_CENTER].GetPositionX() * 2 - FactionChampionLoc[pos2].GetPositionX())), FactionChampionLoc[pos2].GetPositionY(), FactionChampionLoc[pos2].GetPositionZ(), 20.0f, 20.0f);
                            }
                            ++pos2;
                        }
                        HandleGameObject(GO_EnterGateGUID, false);
                        events.RescheduleEvent(EVENT_CHAMPIONS_ATTACK, 4000);
                        break;
                    }
                case EVENT_CHAMPIONS_ATTACK:
                    {
                        for (ObjectGuid const& guid : NPC_ChampionGUIDs)
                            if (Creature* c = instance->GetCreature(guid))
{
                                c->SetReactState(REACT_AGGRESSIVE);
                                c->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                                c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                //if (Unit* target = c->SelectNearestTarget(200.0f))
                                //  c->AI()->AttackStart(target);
                            }
                        Map::PlayerList const& pl = instance->GetPlayers();
                        for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                            itr->GetSource()->AddToNotify(NOTIFY_AI_RELOCATION);
                        EncounterStatus = IN_PROGRESS;
                        break;
                    }
                case EVENT_SCENE_FACTION_CHAMPIONS_DEAD:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_2_06);
                        if (Creature* c = instance->GetCreature(NPC_BarrettGUID))
                            c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        break;
                    }
                case EVENT_SCENE_301:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_3_01);
                        events.RescheduleEvent(EVENT_SCENE_302, 13000);
                        break;
                    }
                case EVENT_SCENE_302:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_3_02);
                        events.RescheduleEvent(EVENT_SCENE_303, 3000);
                        break;
                    }
                case EVENT_SCENE_303:
                    {
                        HandleGameObject(GO_EnterGateGUID, false);
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
{
                            HandleGameObject(GO_MainGateGUID, true);
                            if (Creature* t = c->SummonCreature(NPC_LIGHTBANE, Locs[LOC_VALKYR_RIGHT].GetPositionX(), Locs[LOC_VALKYR_RIGHT].GetPositionY(), Locs[LOC_VALKYR_RIGHT].GetPositionZ(), Locs[LOC_VALKYR_RIGHT].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 630000000))
                                t->GetMotionMaster()->MovePoint(0, Locs[LOC_VALKYR_DEST_RIGHT].GetPositionX(), Locs[LOC_VALKYR_DEST_RIGHT].GetPositionY(), Locs[LOC_VALKYR_DEST_RIGHT].GetPositionZ());
                            if (Creature* t = c->SummonCreature(NPC_DARKBANE, Locs[LOC_VALKYR_LEFT].GetPositionX(), Locs[LOC_VALKYR_LEFT].GetPositionY(), Locs[LOC_VALKYR_LEFT].GetPositionZ(), Locs[LOC_VALKYR_LEFT].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 630000000))
                                t->GetMotionMaster()->MovePoint(0, Locs[LOC_VALKYR_DEST_LEFT].GetPositionX(), Locs[LOC_VALKYR_DEST_LEFT].GetPositionY(), Locs[LOC_VALKYR_DEST_LEFT].GetPositionZ());
                        }
                        events.RescheduleEvent(EVENT_SCENE_304, 6250);
                        break;
                    }
                case EVENT_SCENE_304:
                    {
                        HandleGameObject(GO_MainGateGUID, false);
                        EncounterStatus = IN_PROGRESS;
                        if (Creature* c = instance->GetCreature(NPC_LightbaneGUID))
                            c->GetMotionMaster()->MovePoint(0, Locs[LOC_VALKYR_DEST_2_RIGHT].GetPositionX(), Locs[LOC_VALKYR_DEST_2_RIGHT].GetPositionY(), Locs[LOC_VALKYR_DEST_2_RIGHT].GetPositionZ());
                        if (Creature* c = instance->GetCreature(NPC_DarkbaneGUID))
                            c->GetMotionMaster()->MovePoint(0, Locs[LOC_VALKYR_DEST_2_LEFT].GetPositionX(), Locs[LOC_VALKYR_DEST_2_LEFT].GetPositionY(), Locs[LOC_VALKYR_DEST_2_LEFT].GetPositionZ());
                        events.RescheduleEvent(EVENT_VALKYRIES_ATTACK, 3250);
                        break;
                    }
                case EVENT_VALKYRIES_ATTACK:
                    {
                        if (Creature* c = instance->GetCreature(NPC_LightbaneGUID))
{
                            c->SetReactState(REACT_AGGRESSIVE);
                            c->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            /*if (Unit* target = c->SelectNearestTarget(200.0f))
{
                                c->AI()->AttackStart(target);
                                c->AI()->DoZoneInCombat();
                            }*/
                        }
                        if (Creature* c = instance->GetCreature(NPC_DarkbaneGUID))
{
                            c->SetReactState(REACT_AGGRESSIVE);
                            c->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            /*if (Unit* target = c->SelectNearestTarget(200.0f))
{
                                c->AI()->AttackStart(target);
                                c->AI()->DoZoneInCombat();
                            }*/
                        }
                        break;
                    }
                case EVENT_SCENE_VALKYR_DEAD:
                    {
                        if (TeamIdInInstance == TEAM_NEUTRAL)
{
                            Map::PlayerList const& pl = instance->GetPlayers();
                            for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                                if (Player* plr = itr->GetSource())
                                    if (!plr->IsGameMaster())
{
                                        TeamIdInInstance = plr->GetTeamId();
                                        break;
                                    }
                        }
                        if (Creature* c = instance->GetCreature(TeamIdInInstance == TEAM_ALLIANCE ? NPC_VarianGUID : NPC_GarroshGUID))
                            c->AI()->Talk((TeamIdInInstance == TEAM_ALLIANCE ? SAY_STAGE_3_03a : SAY_STAGE_3_03h));
                        events.RescheduleEvent(EVENT_SCENE_401, 60000);
                        break;
                    }
                case EVENT_SCENE_401:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_4_01);
                        events.RescheduleEvent(EVENT_SCENE_402, 20000);
                        break;
                    }
                case EVENT_SCENE_402:
                    {
                        HandleGameObject(GO_EnterGateGUID, false);
                        EncounterStatus = IN_PROGRESS;
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            if (Creature* t = c->SummonCreature(NPC_LICH_KING, Locs[LOC_ARTHAS_PORTAL]))
{
                                t->SetReactState(REACT_PASSIVE);
                                t->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                t->SetDisplayId(11686);
                                t->AI()->Talk(SAY_STAGE_4_02);
                                t->SetVisible(false);
                            }
                        events.RescheduleEvent(EVENT_SCENE_403, 2000);
                        break;
                    }
                case EVENT_SCENE_403:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            if (Creature* t = c->SummonCreature(NPC_WORLD_TRIGGER, Locs[LOC_ARTHAS_PORTAL], TEMPSUMMON_TIMED_DESPAWN, 60000))
{
                                t->SetReactState(REACT_PASSIVE);
                                t->CastSpell(t, 51807, true);
                            }
                        events.RescheduleEvent(EVENT_SCENE_404, 2000);
                        break;
                    }
                case EVENT_SCENE_404:
                    {
                        if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
{
                            c->SetDisplayId(c->GetNativeDisplayId());
                            c->SetVisible(true);
                            c->GetMotionMaster()->MovePoint(0, Locs[LOC_ARTHAS]);
                        }
                        events.RescheduleEvent(EVENT_SCENE_405, 3000);
                        break;
                    }
                case EVENT_SCENE_405:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
                            c->AI()->Talk(SAY_STAGE_4_03);
                        events.RescheduleEvent(EVENT_SCENE_406, 7000);
                        break;
                    }
                case EVENT_SCENE_406:
                    {
                        if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
{
                            c->AI()->Talk(SAY_STAGE_4_04);
                            c->HandleEmoteCommand(EMOTE_ONESHOT_LAUGH);
                        }
                        events.RescheduleEvent(EVENT_SCENE_406_2, 2500);
                        events.RescheduleEvent(EVENT_SCENE_407, 12000);
                        break;
                    }
                case EVENT_SCENE_406_2:
                    {
                        if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
{
                            c->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_TALK);
                        }
                        break;
                    }
                case EVENT_SCENE_407:
                    {
                        if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
                            c->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
                        events.RescheduleEvent(EVENT_SCENE_408, 4000);
                        break;
                    }
                case EVENT_SCENE_408:
                    {
                        if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
{
                            c->HandleEmoteCommand(EMOTE_ONESHOT_KNEEL);
                        }
                        events.RescheduleEvent(EVENT_SCENE_409, 1500);
                        break;
                    }
                case EVENT_SCENE_409:
                    {
                        if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
{
                            if (GameObject* floor = instance->GetGameObject(GO_FloorGUID))
                                floor->SetDestructibleState(GO_DESTRUCTIBLE_DAMAGED);//floor->ModifyHealth(-10000000, c);
                            c->CastSpell((Unit*)nullptr, 68193, true);
                            c->SetVisible(false);
                            c->SetDisplayId(11686);
                            if (Creature* t = c->FindNearestCreature(NPC_WORLD_TRIGGER, 500.0f, true))
                                t->DespawnOrUnsummon();
                            InstanceProgress = INSTANCE_PROGRESS_ANUB_ARAK;
                            SpawnAnubArak();
                        }
                        events.RescheduleEvent(EVENT_SCENE_410, 2000);
                        break;
                    }
                case EVENT_SCENE_410:
                    {
                        if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
{
                            c->SetVisible(true);
                            c->AI()->Talk(SAY_STAGE_4_05);
                            c->DespawnOrUnsummon(0);
                        }
                        break;
                    }
                case EVENT_SCENE_501:
                    {
                        if (Creature* c = instance->GetCreature(NPC_TirionGUID))
{
                            c->AI()->Talk(SAY_STAGE_4_06);
                            c->SummonCreature(NPC_ARGENT_MAGE, Locs[LOC_MAGE].GetPositionX(), Locs[LOC_MAGE].GetPositionY(), Locs[LOC_MAGE].GetPositionZ(), Locs[LOC_MAGE].GetOrientation());
                            c->SummonGameObject(195682, 668.15f, 134.57f, 142.12f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 630000000);
                        }
                        events.RescheduleEvent(EVENT_SCENE_502, 20000);
                        break;
                    }
                case EVENT_SCENE_502:
                    {
                        if (instance->IsHeroic())
{
                            uint32 tributeChest = 0;
                            if (instance->GetSpawnMode() == RAID_DIFFICULTY_10MAN_HEROIC )
{
                                if (AttemptsLeft >= 50)
                                    tributeChest = GO_TRIBUTE_CHEST_10H_99;
                                else if (AttemptsLeft >= 45)
                                    tributeChest = GO_TRIBUTE_CHEST_10H_50;
                                else if (AttemptsLeft >= 25)
                                    tributeChest = GO_TRIBUTE_CHEST_10H_45;
                                else
                                    tributeChest = GO_TRIBUTE_CHEST_10H_25;
                            }
                            else if (instance->GetSpawnMode() == RAID_DIFFICULTY_25MAN_HEROIC )
{
                                if (AttemptsLeft >= 50)
                                    tributeChest = GO_TRIBUTE_CHEST_25H_99;
                                else if (AttemptsLeft >= 45)
                                    tributeChest = GO_TRIBUTE_CHEST_25H_50;
                                else if (AttemptsLeft >= 25)
                                    tributeChest = GO_TRIBUTE_CHEST_25H_45;
                                else
                                    tributeChest = GO_TRIBUTE_CHEST_25H_25;
                            }
                            if (tributeChest)
                                if (Creature* c = instance->GetCreature(NPC_TirionGUID))
{
                                    c->AI()->Talk(SAY_STAGE_4_07);
                                    if (GameObject* chest = c->SummonGameObject(tributeChest, 665.12f, 143.78f, 142.12f, 0.0f, 0, 0, 0, 0, 90000000))
{
                                        chest->SetRespawnTime(chest->GetRespawnDelay());
                                        chest->SetLootRecipient(instance);
                                    }
                                }
                        }
                        break;
                    }
            }
        }
References AttemptsLeft, MapRefMgr::begin(), bSwitcher, ObjectGuid::Clear(), DoCheckDedicatedInsanity(), DoNeedCleanup(), EMOTE_ONESHOT_EXCLAMATION, EMOTE_ONESHOT_KNEEL, EMOTE_ONESHOT_LAUGH, EMOTE_STATE_NONE, EMOTE_STATE_SPELL_PRECAST, EMOTE_STATE_TALK, EncounterStatus, MapRefMgr::end(), EVENT_ACIDMAW_AND_DREADSCALE_ATTACK, EVENT_CHAMPIONS_ATTACK, EVENT_CHECK_PLAYERS, EVENT_CLOSE_GATE, EVENT_GORMOK_ATTACK, EVENT_ICEHOWL_ATTACK, EVENT_JARAXXUS_ATTACK, EVENT_NORTHREND_BEASTS_ENRAGE, EVENT_OPEN_GATE, EVENT_SCENE_001, EVENT_SCENE_002, EVENT_SCENE_003, EVENT_SCENE_004, EVENT_SCENE_005, EVENT_SCENE_005_2, EVENT_SCENE_006, EVENT_SCENE_101, EVENT_SCENE_102, EVENT_SCENE_103, EVENT_SCENE_104, EVENT_SCENE_105, EVENT_SCENE_106, EVENT_SCENE_107, EVENT_SCENE_108, EVENT_SCENE_109, EVENT_SCENE_110, EVENT_SCENE_111, EVENT_SCENE_112, EVENT_SCENE_113, EVENT_SCENE_201, EVENT_SCENE_202, EVENT_SCENE_203, EVENT_SCENE_204, EVENT_SCENE_205, EVENT_SCENE_301, EVENT_SCENE_302, EVENT_SCENE_303, EVENT_SCENE_304, EVENT_SCENE_401, EVENT_SCENE_402, EVENT_SCENE_403, EVENT_SCENE_404, EVENT_SCENE_405, EVENT_SCENE_406, EVENT_SCENE_406_2, EVENT_SCENE_407, EVENT_SCENE_408, EVENT_SCENE_409, EVENT_SCENE_410, EVENT_SCENE_501, EVENT_SCENE_502, EVENT_SCENE_BEASTS_DONE, EVENT_SCENE_FACTION_CHAMPIONS_DEAD, EVENT_SCENE_VALKYR_DEAD, EVENT_SUMMON_ACIDMAW_AND_DREADSCALE, EVENT_SUMMON_CHAMPIONS, EVENT_SUMMON_GORMOK, EVENT_SUMMON_ICEHOWL, EVENT_SUMMON_JARAXXUS, EVENT_VALKYRIES_ATTACK, FactionChampionLoc, WorldObject::FindNearestCreature(), Map::GetCreature(), Map::GetGameObject(), Position::GetOrientation(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Map::GetSpawnMode(), GO_DESTRUCTIBLE_DAMAGED, GO_EnterGateGUID, GO_FloorGUID, GO_MainGateGUID, GO_TRIBUTE_CHEST_10H_25, GO_TRIBUTE_CHEST_10H_45, GO_TRIBUTE_CHEST_10H_50, GO_TRIBUTE_CHEST_10H_99, GO_TRIBUTE_CHEST_25H_25, GO_TRIBUTE_CHEST_25H_45, GO_TRIBUTE_CHEST_25H_50, GO_TRIBUTE_CHEST_25H_99, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, INSTANCE_PROGRESS_ANUB_ARAK, INSTANCE_PROGRESS_INTRO_DONE, INSTANCE_PROGRESS_JARAXXUS_INTRO_DONE, InstanceCleanup(), InstanceProgress, Map::IsHeroic(), Unit::Kill(), LOC_ACIDMAW, LOC_ARTHAS, LOC_ARTHAS_PORTAL, LOC_BEHIND_GATE, LOC_CENTER, LOC_DREADSCALE, LOC_GATE_FRONT, LOC_MAGE, LOC_VALKYR_DEST_2_LEFT, LOC_VALKYR_DEST_2_RIGHT, LOC_VALKYR_DEST_LEFT, LOC_VALKYR_DEST_RIGHT, LOC_VALKYR_LEFT, LOC_VALKYR_RIGHT, Locs, MOVEMENTFLAG_WALKING, northrendBeastsMask, NOTIFY_AI_RELOCATION, NPC_ACIDMAW, NPC_AcidmawGUID, NPC_ALLIANCE_DEATH_KNIGHT, NPC_ALLIANCE_DRUID_BALANCE, NPC_ALLIANCE_DRUID_RESTORATION, NPC_ALLIANCE_HUNTER, NPC_ALLIANCE_MAGE, NPC_ALLIANCE_PALADIN_HOLY, NPC_ALLIANCE_PALADIN_RETRIBUTION, NPC_ALLIANCE_PRIEST_DISCIPLINE, NPC_ALLIANCE_PRIEST_SHADOW, NPC_ALLIANCE_ROGUE, NPC_ALLIANCE_SHAMAN_ENHANCEMENT, NPC_ALLIANCE_SHAMAN_RESTORATION, NPC_ALLIANCE_WARLOCK, NPC_ALLIANCE_WARRIOR, NPC_ARGENT_MAGE, NPC_BarrettGUID, NPC_ChampionGUIDs, NPC_DARKBANE, NPC_DarkbaneGUID, NPC_DREADSCALE, NPC_DreadscaleGUID, NPC_FIZZLEBANG, NPC_FizzlebangGUID, NPC_GarroshGUID, NPC_GORMOK, NPC_GormokGUID, NPC_HORDE_DEATH_KNIGHT, NPC_HORDE_DRUID_BALANCE, NPC_HORDE_DRUID_RESTORATION, NPC_HORDE_HUNTER, NPC_HORDE_MAGE, NPC_HORDE_PALADIN_HOLY, NPC_HORDE_PALADIN_RETRIBUTION, NPC_HORDE_PRIEST_DISCIPLINE, NPC_HORDE_PRIEST_SHADOW, NPC_HORDE_ROGUE, NPC_HORDE_SHAMAN_ENHANCEMENT, NPC_HORDE_SHAMAN_RESTORATION, NPC_HORDE_WARLOCK, NPC_HORDE_WARRIOR, NPC_ICEHOWL, NPC_IcehowlGUID, NPC_JARAXXUS, NPC_JaraxxusGUID, NPC_LICH_KING, NPC_LichKingGUID, NPC_LIGHTBANE, NPC_LightbaneGUID, NPC_PortalGUID, NPC_PURPLE_GROUND, NPC_PurpleGroundGUID, NPC_TirionGUID, NPC_VarianGUID, NPC_WORLD_TRIGGER, RAID_DIFFICULTY_10MAN_HEROIC, RAID_DIFFICULTY_10MAN_NORMAL, RAID_DIFFICULTY_25MAN_HEROIC, RAID_DIFFICULTY_25MAN_NORMAL, REACT_AGGRESSIVE, REACT_PASSIVE, SAY_STAGE_0_01, SAY_STAGE_0_02, SAY_STAGE_0_03a, SAY_STAGE_0_03h, SAY_STAGE_0_04, SAY_STAGE_0_05, SAY_STAGE_0_06, SAY_STAGE_1_01, SAY_STAGE_1_02, SAY_STAGE_1_03, SAY_STAGE_1_04, SAY_STAGE_1_05, SAY_STAGE_1_06, SAY_STAGE_1_06_1, SAY_STAGE_1_07, SAY_STAGE_1_08, SAY_STAGE_1_09, SAY_STAGE_1_10, SAY_STAGE_1_11, SAY_STAGE_2_01, SAY_STAGE_2_02a, SAY_STAGE_2_02h, SAY_STAGE_2_03, SAY_STAGE_2_04a, SAY_STAGE_2_04h, SAY_STAGE_2_05a, SAY_STAGE_2_05h, SAY_STAGE_2_06, SAY_STAGE_3_01, SAY_STAGE_3_02, SAY_STAGE_3_03a, SAY_STAGE_3_03h, SAY_STAGE_4_01, SAY_STAGE_4_02, SAY_STAGE_4_03, SAY_STAGE_4_04, SAY_STAGE_4_05, SAY_STAGE_4_06, SAY_STAGE_4_07, SpawnAnubArak(), SPELL_WILFRED_PORTAL, Map::SummonCreature(), WorldObject::SummonCreature(), WorldObject::SummonGameObject(), TEAM_ALLIANCE, TEAM_NEUTRAL, TeamIdInInstance, TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, and urand().
WriteSaveDataMore()
void instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << InstanceProgress;
            if (instance->IsHeroic())
            {
                data << ' '
                    << AttemptsLeft << ' '
                    << (bDedicatedInsanity ? 1 : 0) << ' '
                    << (bNooneDied ? 1 : 0);
            }
        }
References AttemptsLeft, bDedicatedInsanity, bNooneDied, InstanceScript::instance, InstanceProgress, and Map::IsHeroic().
Member Data Documentation
AchievementTimer
uint32 instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::AchievementTimer
Referenced by Initialize(), and SetData().
AttemptsLeft
uint32 instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::AttemptsLeft
Referenced by CheckAchievementCriteriaMeet(), Initialize(), InstanceCleanup(), OnPlayerEnter(), ReadSaveDataMore(), SetData(), SpawnAnubArak(), Update(), and WriteSaveDataMore().
bDedicatedInsanity
bool instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::bDedicatedInsanity
Referenced by CheckAchievementCriteriaMeet(), DoCheckDedicatedInsanity(), Initialize(), ReadSaveDataMore(), and WriteSaveDataMore().
bNooneDied
bool instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::bNooneDied
Referenced by CheckAchievementCriteriaMeet(), Initialize(), OnUnitDeath(), ReadSaveDataMore(), and WriteSaveDataMore().
bSwitcher
bool instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::bSwitcher
Referenced by Initialize(), and Update().
CLEANED
bool instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::CLEANED
Referenced by DoNeedCleanup(), Initialize(), InstanceCleanup(), and SetData().
Counter
uint8 instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Counter
Referenced by Initialize(), InstanceCleanup(), and SetData().
EncounterStatus
uint32 instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::EncounterStatus
Referenced by Initialize(), InstanceCleanup(), IsEncounterInProgress(), SetData(), and Update().
events
EventMap instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::events
GO_EnterGateGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::GO_EnterGateGUID
Referenced by InstanceCleanup(), OnGameObjectCreate(), SetData(), and Update().
GO_FloorGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::GO_FloorGUID
Referenced by InstanceCleanup(), OnGameObjectCreate(), SetData(), and Update().
GO_MainGateGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::GO_MainGateGUID
Referenced by InstanceCleanup(), OnGameObjectCreate(), and Update().
GO_WebDoorGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::GO_WebDoorGUID
Referenced by InstanceCleanup(), OnGameObjectCreate(), and SetData().
InstanceProgress
uint32 instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceProgress
Referenced by GetData(), Initialize(), InstanceCleanup(), OnGameObjectCreate(), ReadSaveDataMore(), SetData(), SpawnAnubArak(), Update(), and WriteSaveDataMore().
northrendBeastsMask
uint8 instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::northrendBeastsMask
Referenced by Initialize(), InstanceCleanup(), SetData(), and Update().
NPC_AcidmawGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_AcidmawGUID
Referenced by GetGuidData(), InstanceCleanup(), OnCreatureCreate(), SetData(), and Update().
NPC_AnubarakGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_AnubarakGUID
Referenced by GetGuidData(), InstanceCleanup(), OnCreatureCreate(), and SpawnAnubArak().
NPC_BarrettGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_BarrettGUID
Referenced by CheckAchievementCriteriaMeet(), InstanceCleanup(), OnCreatureCreate(), SpawnAnubArak(), and Update().
NPC_ChampionGUIDs
GuidVector instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_ChampionGUIDs
Referenced by Initialize(), InstanceCleanup(), SetData(), and Update().
NPC_DarkbaneGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_DarkbaneGUID
Referenced by GetGuidData(), InstanceCleanup(), OnCreatureCreate(), SpawnAnubArak(), and Update().
NPC_DreadscaleGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_DreadscaleGUID
Referenced by GetGuidData(), InstanceCleanup(), OnCreatureCreate(), SetData(), and Update().
NPC_FizzlebangGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_FizzlebangGUID
Referenced by InstanceCleanup(), OnCreatureCreate(), and Update().
NPC_GarroshGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_GarroshGUID
Referenced by OnCreatureCreate(), SetData(), and Update().
NPC_GormokGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_GormokGUID
Referenced by GetGuidData(), InstanceCleanup(), OnCreatureCreate(), and Update().
NPC_IcehowlGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_IcehowlGUID
Referenced by InstanceCleanup(), OnCreatureCreate(), SpawnAnubArak(), and Update().
NPC_JaraxxusGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_JaraxxusGUID
Referenced by InstanceCleanup(), OnCreatureCreate(), SpawnAnubArak(), and Update().
NPC_LichKingGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_LichKingGUID
Referenced by InstanceCleanup(), OnCreatureCreate(), and Update().
NPC_LightbaneGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_LightbaneGUID
Referenced by GetGuidData(), InstanceCleanup(), OnCreatureCreate(), SpawnAnubArak(), and Update().
NPC_PortalGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_PortalGUID
Referenced by InstanceCleanup(), and Update().
NPC_PurpleGroundGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_PurpleGroundGUID
Referenced by InstanceCleanup(), and Update().
NPC_TirionGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_TirionGUID
Referenced by OnCreatureCreate(), SetData(), and Update().
NPC_VarianGUID
ObjectGuid instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::NPC_VarianGUID
Referenced by OnCreatureCreate(), SetData(), and Update().
str_data
std::string instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::str_data
TeamIdInInstance
TeamId instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::TeamIdInInstance
Referenced by Initialize(), SetData(), and Update().