AzerothCore: boss_hexlord_malacrass::boss_hex_lord_malacrassAI Struct Reference
boss_hexlord_malacrass::boss_hex_lord_malacrassAI Struct Reference
Public Member Functions
boss_hex_lord_malacrassAI (Creature *creature)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void SelectAddEntry ()
void SpawnAdds ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void UseAbility ()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
ObjectGuid AddGUID [4]
uint32 AddEntry [4]
ObjectGuid PlayerGUID
uint32 SpiritBolts_Timer
uint32 DrainPower_Timer
uint32 SiphonSoul_Timer
uint32 PlayerAbility_Timer
uint32 CheckAddState_Timer
uint32 ResetTimer
uint32 PlayerClass
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_hex_lord_malacrassAI()
boss_hexlord_malacrass::boss_hex_lord_malacrassAI::boss_hex_lord_malacrassAI (Creature * creature) inline
                                                      : ScriptedAI(creature)
        {
            instance = creature->GetInstanceScript();
            SelectAddEntry();
        }
References WorldObject::GetInstanceScript(), instance, and SelectAddEntry().
Member Function Documentation
JustDied()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            instance->SetData(DATA_HEXLORDEVENT, DONE);
            Talk(SAY_DEATH);
            for (uint8 i = 0; i < 4; ++i)
            {
                Unit* Temp = ObjectAccessor::GetUnit(*me, AddGUID[i]);
                if (Temp && Temp->IsAlive())
                    Unit::DealDamage(Temp, Temp, Temp->GetHealth(), nullptr, DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, nullptr, false);
            }
        }
References AddGUID, DATA_HEXLORDEVENT, Unit::DealDamage(), DIRECT_DAMAGE, DONE, Unit::GetHealth(), ObjectAccessor::GetUnit(), instance, Unit::IsAlive(), ScriptedAI::me, SAY_DEATH, ZoneScript::SetData(), and SPELL_SCHOOL_MASK_NORMAL.
JustEngagedWith()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            instance->SetData(DATA_HEXLORDEVENT, IN_PROGRESS);
            DoZoneInCombat();
            Talk(SAY_AGGRO);
            for (uint8 i = 0; i < 4; ++i)
            {
                Creature* creature = ObjectAccessor::GetCreature(*me, AddGUID[i]);
                if (creature && creature->IsAlive())
                    creature->AI()->AttackStart(me->GetVictim());
                else
                {
                    EnterEvadeMode();
                    break;
                }
            }
        }
References AddGUID, Creature::AI(), UnitAI::AttackStart(), DATA_HEXLORDEVENT, CreatureAI::DoZoneInCombat(), CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), Unit::GetVictim(), IN_PROGRESS, instance, Unit::IsAlive(), ScriptedAI::me, SAY_AGGRO, and ZoneScript::SetData().
KilledUnit()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            switch (urand(0, 1))
            {
                case 0:
                    Talk(SAY_KILL_ONE);
                    break;
                case 1:
                    Talk(SAY_KILL_TWO);
                    break;
            }
        }
References SAY_KILL_ONE, SAY_KILL_TWO, and urand().
Reset()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            instance->SetData(DATA_HEXLORDEVENT, NOT_STARTED);
            SpiritBolts_Timer = 20000;
            DrainPower_Timer = 60000;
            SiphonSoul_Timer = 100000;
            PlayerAbility_Timer = 99999;
            CheckAddState_Timer = 5000;
            ResetTimer = 5000;
            SpawnAdds();
        }
References CheckAddState_Timer, DATA_HEXLORDEVENT, DrainPower_Timer, instance, NOT_STARTED, PlayerAbility_Timer, ResetTimer, ZoneScript::SetData(), SiphonSoul_Timer, SpawnAdds(), and SpiritBolts_Timer.
SelectAddEntry()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SelectAddEntry () inline
        {
            std::vector<uint32> AddList;
            for (uint8 i = 0; i < 8; ++i)
                AddList.push_back(AddEntryList[i]);
            while (AddList.size() > 4)
                AddList.erase(AddList.begin() + rand() % AddList.size());
            uint8 i = 0;
            for (std::vector<uint32>::const_iterator itr = AddList.begin(); itr != AddList.end(); ++itr, ++i)
                AddEntry[i] = *itr;
        }
References AddEntry, and AddEntryList.
Referenced by boss_hex_lord_malacrassAI().
SpawnAdds()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpawnAdds () inline
        {
            for (uint8 i = 0; i < 4; ++i)
            {
                Creature* creature = (ObjectAccessor::GetCreature((*me), AddGUID[i]));
                if (!creature || !creature->IsAlive())
                {
                    if (creature) creature->setDeathState(DeathState::Dead);
                    creature = me->SummonCreature(AddEntry[i], Pos_X[i], POS_Y, POS_Z, ORIENT, TEMPSUMMON_DEAD_DESPAWN, 0);
                    if (creature) AddGUID[i] = creature->GetGUID();
                }
                else
                {
                    creature->AI()->EnterEvadeMode();
                    creature->SetPosition(Pos_X[i], POS_Y, POS_Z, ORIENT);
                    creature->StopMovingOnCurrentPos();
                }
            }
        }
References AddEntry, AddGUID, Creature::AI(), CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), Object::GetGUID(), Unit::IsAlive(), ScriptedAI::me, ORIENT, Pos_X, POS_Y, POS_Z, Creature::setDeathState(), Creature::SetPosition(), Unit::StopMovingOnCurrentPos(), WorldObject::SummonCreature(), and TEMPSUMMON_DEAD_DESPAWN.
Referenced by Reset().
UpdateAI()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            if (ResetTimer <= diff)
            {
                if (me->IsWithinDist3d(119.223f, 1035.45f, 29.4481f, 10))
                {
                    EnterEvadeMode();
                    return;
                }
                ResetTimer = 5000;
            }
            else ResetTimer -= diff;
            if (CheckAddState_Timer <= diff)
            {
                for (uint8 i = 0; i < 4; ++i)
                    if (Creature* temp = ObjectAccessor::GetCreature(*me, AddGUID[i]))
                        if (temp->IsAlive() && !temp->GetVictim())
                            temp->AI()->AttackStart(me->GetVictim());
                CheckAddState_Timer = 5000;
            }
            else CheckAddState_Timer -= diff;
            if (DrainPower_Timer <= diff)
            {
                DoCast(me, SPELL_DRAIN_POWER, true);
                Talk(SAY_DRAIN_POWER);
                DrainPower_Timer = urand(40000, 55000);    // must cast in 60 sec, or buff/debuff will disappear
            }
            else DrainPower_Timer -= diff;
            if (SpiritBolts_Timer <= diff)
            {
                if (DrainPower_Timer < 12000)    // channel 10 sec
                    SpiritBolts_Timer = 13000;   // cast drain power first
                else
                {
                    DoCast(me, SPELL_SPIRIT_BOLTS, false);
                    Talk(SAY_SPIRIT_BOLTS);
                    SpiritBolts_Timer = 40000;
                    SiphonSoul_Timer = 10000;    // ready to drain
                    PlayerAbility_Timer = 99999;
                }
            }
            else SpiritBolts_Timer -= diff;
            if (SiphonSoul_Timer <= diff)
            {
                Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 70, true);
                Unit* trigger = DoSpawnCreature(NPC_TEMP_TRIGGER, 0, 0, 0, 0, TEMPSUMMON_TIMED_DESPAWN, 30000);
                if (!target || !trigger)
                {
                    EnterEvadeMode();
                    return;
                }
                else
                {
                    trigger->SetDisplayId(11686);
                    trigger->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    trigger->CastSpell(target, SPELL_SIPHON_SOUL, true);
                    trigger->GetMotionMaster()->MoveChase(me);
                    //DoCast(target, SPELL_SIPHON_SOUL, true);
                    //me->SetGuidValue(UNIT_FIELD_CHANNEL_OBJECT, target->GetGUID());
                    //me->SetUInt32Value(UNIT_CHANNEL_SPELL, SPELL_SIPHON_SOUL);
                    PlayerGUID = target->GetGUID();
                    PlayerAbility_Timer = urand(8000, 10000);
                    PlayerClass = target->getClass() - 1;
                    if (target->IsClass(CLASS_DRUID))
                        PlayerClass = CLASS_DRUID;
                    else if (target->IsClass(CLASS_PRIEST) && target->HasSpell(15473))
                        PlayerClass = CLASS_PRIEST; // shadow priest
                    SiphonSoul_Timer = 99999;   // buff lasts 30 sec
                }
            }
            else SiphonSoul_Timer -= diff;
            if (PlayerAbility_Timer <= diff)
            {
                //Unit* target = ObjectAccessor::GetUnit(*me, PlayerGUID);
                //if (target && target->IsAlive())
                //{
                UseAbility();
                PlayerAbility_Timer = urand(8000, 10000);
                //}
            }
            else PlayerAbility_Timer -= diff;
            DoMeleeAttackIfReady();
        }
References AddGUID, Unit::CastSpell(), CheckAddState_Timer, CLASS_DRUID, CLASS_PRIEST, UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoSpawnCreature(), DrainPower_Timer, CreatureAI::EnterEvadeMode(), Unit::getClass(), ObjectAccessor::GetCreature(), Object::GetGUID(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HasSpell(), Unit::IsClass(), WorldObject::IsWithinDist3d(), ScriptedAI::me, MotionMaster::MoveChase(), NPC_TEMP_TRIGGER, PlayerAbility_Timer, PlayerClass, PlayerGUID, ResetTimer, SAY_DRAIN_POWER, SAY_SPIRIT_BOLTS, UnitAI::SelectTarget(), Unit::SetDisplayId(), Unit::SetUnitFlag(), SiphonSoul_Timer, SPELL_DRAIN_POWER, SPELL_SIPHON_SOUL, SPELL_SPIRIT_BOLTS, SpiritBolts_Timer, TEMPSUMMON_TIMED_DESPAWN, UNIT_FLAG_NOT_SELECTABLE, CreatureAI::UpdateVictim(), urand(), and UseAbility().
UseAbility()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UseAbility () inline
        {
            uint8 random = urand(0, 2);
            Unit* target = nullptr;
            switch (PlayerAbility[PlayerClass][random].target)
            {
                case ABILITY_TARGET_SELF:
                    target = me;
                    break;
                case ABILITY_TARGET_VICTIM:
                    target = me->GetVictim();
                    break;
                case ABILITY_TARGET_ENEMY:
                default:
                    target = SelectTarget(SelectTargetMethod::Random, 0, 100, true);
                    break;
                case ABILITY_TARGET_HEAL:
                    target = DoSelectLowestHpFriendly(50, 0);
                    break;
                case ABILITY_TARGET_BUFF:
                    {
                        std::list<Creature*> templist = DoFindFriendlyMissingBuff(50, PlayerAbility[PlayerClass][random].spell);
                        if (!templist.empty())
                            target = *(templist.begin());
                    }
                    break;
            }
            if (target)
                DoCast(target, PlayerAbility[PlayerClass][random].spell, false);
        }
References ABILITY_TARGET_BUFF, ABILITY_TARGET_ENEMY, ABILITY_TARGET_HEAL, ABILITY_TARGET_SELF, ABILITY_TARGET_VICTIM, UnitAI::DoCast(), ScriptedAI::DoFindFriendlyMissingBuff(), ScriptedAI::DoSelectLowestHpFriendly(), Unit::GetVictim(), ScriptedAI::me, PlayerAbility, PlayerClass, UnitAI::SelectTarget(), and urand().
Referenced by UpdateAI().
Member Data Documentation
AddEntry
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::AddEntry[4]
Referenced by SelectAddEntry(), and SpawnAdds().
AddGUID
ObjectGuid boss_hexlord_malacrass::boss_hex_lord_malacrassAI::AddGUID[4]
Referenced by JustDied(), JustEngagedWith(), SpawnAdds(), and UpdateAI().
CheckAddState_Timer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::CheckAddState_Timer
Referenced by Reset(), and UpdateAI().
DrainPower_Timer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::DrainPower_Timer
Referenced by Reset(), and UpdateAI().
instance
InstanceScript* boss_hexlord_malacrass::boss_hex_lord_malacrassAI::instance
Referenced by boss_hex_lord_malacrassAI(), JustDied(), JustEngagedWith(), and Reset().
PlayerAbility_Timer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::PlayerAbility_Timer
Referenced by Reset(), and UpdateAI().
PlayerClass
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::PlayerClass
Referenced by UpdateAI(), and UseAbility().
PlayerGUID
ObjectGuid boss_hexlord_malacrass::boss_hex_lord_malacrassAI::PlayerGUID
Referenced by UpdateAI().
ResetTimer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::ResetTimer
Referenced by Reset(), and UpdateAI().
SiphonSoul_Timer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SiphonSoul_Timer
Referenced by Reset(), and UpdateAI().
SpiritBolts_Timer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpiritBolts_Timer
Referenced by Reset(), and UpdateAI().