AzerothCore: boss_nightbane Struct Reference
boss_nightbane Struct Reference
Public Member Functions
boss_nightbane (Creature *creature)
void Reset () override
void JustReachedHome () override
void EnterEvadeMode (EvadeReason why) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damageEffectType, SpellSchoolMask spellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void DoAction (int32 action) override
void ScheduleGround ()
void ScheduleFly ()
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void PathEndReached (uint32 pathId) override
void MovementInform (uint32 type, uint32 id) override
void JustSummoned (Creature *summon) override
void TriggerHealthTakeOff ()
void FlyToClosestPreFlyWayPoint ()
void ScheduleLand ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint8 _phase
uint8 _airPhasesCompleted
uint8 _triggerCountTakeOffWhileFlying
TaskScheduler _skeletonscheduler
uint8 _skeletonCount
uint8 _skeletonSpawnCounter
Position _skeletonSpawnPos
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_nightbane()
boss_nightbane::boss_nightbane (Creature * creature) inline
                                       : BossAI(creature, DATA_NIGHTBANE)
    {
        _skeletonCount = 5;
    }
References _skeletonCount.
Member Function Documentation
AttackStart()
void boss_nightbane::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (_phase == PHASE_GROUND)
            ScriptedAI::AttackStart(who);
    }
References _phase, ScriptedAI::AttackStart(), and PHASE_GROUND.
DamageTaken()
void boss_nightbane::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
    {
        if (_airPhasesCompleted < 3)
        {
            if (damage >= me->GetHealth())
            {
                damage = me->GetHealth() - 1;
            }
        }
        BossAI::DamageTaken(attacker, damage, damageEffectType, spellSchoolMask);
    }
References _airPhasesCompleted, BossAI::DamageTaken(), Unit::GetHealth(), and ScriptedAI::me.
DoAction()
void boss_nightbane::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        if (action == ACTION_START_INTRO)
        {
            me->GetMap()->LoadGrid(-11260.0f, -1771.0f); // load grid at far end of intro path
            me->GetMap()->SetVisibilityRange(DEFAULT_VISIBILITY_INSTANCE + 100.0f); // see nightbane
            me->AddUnitState(UNIT_STATE_IGNORE_PATHFINDING);
            _phase = PHASE_INTRO;
            Talk(EMOTE_SUMMON);
            scheduler.Schedule(2s, [this](TaskContext /*context*/)
            {
                me->SetStandState(UNIT_STAND_STATE_STAND);
                me->SetDisableGravity(true);
                me->GetMotionMaster()->MoveTakeoff(POINT_INTRO_TAKE_OFF, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 10.0f, 13.99879f);
            }).Schedule(4s, [this](TaskContext /*context*/)
            {
                me->GetMotionMaster()->MovePath(me->GetEntry()*10, false);
            });
        }
     }
References _phase, ACTION_START_INTRO, Unit::AddUnitState(), DEFAULT_VISIBILITY_INSTANCE, EMOTE_SUMMON, Object::GetEntry(), WorldObject::GetMap(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Map::LoadGrid(), ScriptedAI::me, PHASE_INTRO, POINT_INTRO_TAKE_OFF, TaskScheduler::Schedule(), CreatureAI::scheduler, Creature::SetDisableGravity(), Unit::SetStandState(), Map::SetVisibilityRange(), UNIT_STAND_STATE_STAND, and UNIT_STATE_IGNORE_PATHFINDING.
EnterEvadeMode()
void boss_nightbane::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from BossAI.
    {
        me->SetHomePosition(homePos);
        me->SetCanFly(true);
        me->SetDisableGravity(true);
        me->SendMovementFlagUpdate();
        BossAI::EnterEvadeMode(why);
    }
References BossAI::EnterEvadeMode(), homePos, ScriptedAI::me, Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), and Creature::SetHomePosition().
Referenced by PathEndReached().
FlyToClosestPreFlyWayPoint()
void boss_nightbane::FlyToClosestPreFlyWayPoint () inline
    {
        Position closestWP = preFlyPos;
        if (me->GetDistance(preFlyEastPos) < me->GetDistance(closestWP))
            closestWP = preFlyEastPos;
        if (me->GetDistance(preFlySouthPos) < me->GetDistance(closestWP))
            closestWP = preFlySouthPos;
        if (me->GetDistance(preFlyWestPos) < me->GetDistance(closestWP))
            closestWP = preFlyWestPos;
        me->GetMotionMaster()->Clear(false);
        if (closestWP == preFlyPos)
            me->GetMotionMaster()->MovePoint(POINT_PRE_FLY, closestWP);
        else if (closestWP == preFlyEastPos)
            me->GetMotionMaster()->MovePoint(POINT_PRE_FLY_EAST, closestWP);
        else if (closestWP == preFlySouthPos)
            me->GetMotionMaster()->MovePoint(POINT_PRE_FLY_SOUTH, closestWP);
        else if (closestWP == preFlyWestPos)
            me->GetMotionMaster()->MovePoint(POINT_PRE_FLY_WEST, closestWP);
    }
References MotionMaster::Clear(), WorldObject::GetDistance(), Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MovePoint(), POINT_PRE_FLY, POINT_PRE_FLY_EAST, POINT_PRE_FLY_SOUTH, POINT_PRE_FLY_WEST, preFlyEastPos, preFlyPos, preFlySouthPos, and preFlyWestPos.
Referenced by TriggerHealthTakeOff().
JustEngagedWith()
void boss_nightbane::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        BossAI::JustEngagedWith(who);
        Talk(YELL_AGGRO);
        ScheduleGround();
    }
References BossAI::JustEngagedWith(), ScheduleGround(), and YELL_AGGRO.
JustReachedHome()
void boss_nightbane::JustReachedHome () inline override virtual
Reimplemented from BossAI.
    {
        BossAI::JustReachedHome();
        me->DespawnOnEvade();
    }
References Creature::DespawnOnEvade(), BossAI::JustReachedHome(), and ScriptedAI::me.
JustSummoned()
void boss_nightbane::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
    {
        summon->AI()->AttackStart(me->GetVictim());
        summons.Summon(summon);
    }
References Creature::AI(), UnitAI::AttackStart(), Unit::GetVictim(), ScriptedAI::me, SummonList::Summon(), and BossAI::summons.
MoveInLineOfSight()
void boss_nightbane::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
    {
        if (_phase == PHASE_GROUND)
            ScriptedAI::MoveInLineOfSight(who);
    }
References _phase, CreatureAI::MoveInLineOfSight(), and PHASE_GROUND.
MovementInform()
void boss_nightbane::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type != POINT_MOTION_TYPE)
            return;
        switch (id)
        {
            case POINT_INTRO_TAKE_OFF:
                break;
            case POINT_INTRO_LAND:
                DoStartMovement(me->GetVictim());
                break;
            case POINT_PRE_FLY_EAST:
                scheduler.Schedule(0s, [this](TaskContext /*context*/)
                {
                    me->GetMotionMaster()->MovePoint(POINT_PRE_FLY_SOUTH, preFlySouthPos);
                });
                break;
            case POINT_PRE_FLY_SOUTH:
            case POINT_PRE_FLY_WEST:
                scheduler.Schedule(0s, [this](TaskContext /*context*/)
                {
                    me->GetMotionMaster()->MovePoint(POINT_PRE_FLY, preFlyPos);
                });
                break;
            case POINT_PRE_FLY:
                scheduler.Schedule(0s, [this](TaskContext /*context*/)
                {
                    me->GetMotionMaster()->MovePoint(POINT_FLY, flyPos);
                });
                break;
            case POINT_FLY:
                _phase = PHASE_FLY;
                Talk(EMOTE_BREATH);
                ScheduleFly();
                ScheduleLand();
                break;
            case POINT_LANDING_PRE:
                scheduler.Schedule(0s, [this](TaskContext /*context*/)
                {
                    me->GetMotionMaster()->MovePoint(POINT_LANDING_WEST, preFlyWestPos);
                });
                break;
            case POINT_LANDING_WEST:
                if (_triggerCountTakeOffWhileFlying > 0)
                {
                    _airPhasesCompleted++;
                    _triggerCountTakeOffWhileFlying--;
                    scheduler.Schedule(0s, [this](TaskContext /*context*/)
                    {
                        me->GetMotionMaster()->MovePoint(POINT_PRE_FLY, preFlyPos);
                    });
                }
                else
                {
                    scheduler.Schedule(0s, [this](TaskContext /*context*/)
                    {
                        me->GetMotionMaster()->MovePath(me->GetEntry()*10+1, false);
                    });
                }
                break;
            case POINT_LAND:
                DoStartMovement(me->GetVictim());
                break;
        }
    }
References _airPhasesCompleted, _phase, _triggerCountTakeOffWhileFlying, ScriptedAI::DoStartMovement(), EMOTE_BREATH, flyPos, Object::GetEntry(), Unit::GetMotionMaster(), Unit::GetVictim(), ScriptedAI::me, PHASE_FLY, POINT_FLY, POINT_INTRO_LAND, POINT_INTRO_TAKE_OFF, POINT_LAND, POINT_LANDING_PRE, POINT_LANDING_WEST, POINT_MOTION_TYPE, POINT_PRE_FLY, POINT_PRE_FLY_EAST, POINT_PRE_FLY_SOUTH, POINT_PRE_FLY_WEST, preFlyPos, preFlySouthPos, preFlyWestPos, TaskScheduler::Schedule(), ScheduleFly(), ScheduleLand(), and CreatureAI::scheduler.
PathEndReached()
void boss_nightbane::PathEndReached (uint32 pathId) inline override virtual
Reimplemented from CreatureAI.
    {
        BossAI::PathEndReached(pathId);
        if (pathId == me->GetEntry()*10) // intro
        {
            me->GetMap()->SetVisibilityRange(DEFAULT_VISIBILITY_INSTANCE); // restore visibility
            scheduler.Schedule(0s, [this](TaskContext /*context*/)
            {
                me->ClearUnitState(UNIT_STATE_IGNORE_PATHFINDING);
                me->GetMotionMaster()->MovePoint(POINT_INTRO_LAND, introLandPos);
            }).Schedule(3s, [this](TaskContext /*context*/)
            {
                me->SetDisableGravity(false);
                me->SetCanFly(false);
                me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_IMMUNE_TO_PC);
                _phase = PHASE_GROUND;
                me->SetReactState(REACT_AGGRESSIVE);
                me->SetInCombatWithZone();
            }).Schedule(8s, [this](TaskContext /*context*/)
            {
                if (!SelectTargetFromPlayerList(45.0f))
                {
                    EnterEvadeMode(EVADE_REASON_NO_HOSTILES);
                }
            });
        }
        else if (pathId == me->GetEntry()*10+1) // landing
        {
            _airPhasesCompleted++;
            if (_triggerCountTakeOffWhileFlying > 0)
            {
                _triggerCountTakeOffWhileFlying--;
                scheduler.Schedule(0s, [this](TaskContext /*context*/)
                {
                    me->GetMotionMaster()->MovePoint(POINT_PRE_FLY_SOUTH, preFlySouthPos);
                });
            }
            else
            {
                scheduler.Schedule(0s, [this](TaskContext /*context*/)
                {
                    DoResetThreatList();
                    me->GetMotionMaster()->MovePoint(POINT_LAND, landPos);
                    me->SetDisableGravity(false);
                    me->SetCanFly(false);
                    me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                    _phase = PHASE_GROUND;
                    ScheduleGround();
                });
            }
        }
    }
References _airPhasesCompleted, _phase, _triggerCountTakeOffWhileFlying, Unit::ClearUnitState(), DEFAULT_VISIBILITY_INSTANCE, ScriptedAI::DoResetThreatList(), EMOTE_ONESHOT_LAND, EnterEvadeMode(), CreatureAI::EVADE_REASON_NO_HOSTILES, Object::GetEntry(), WorldObject::GetMap(), Unit::GetMotionMaster(), Unit::HandleEmoteCommand(), introLandPos, landPos, ScriptedAI::me, MotionMaster::MovePoint(), CreatureAI::PathEndReached(), PHASE_GROUND, POINT_INTRO_LAND, POINT_LAND, POINT_PRE_FLY_SOUTH, preFlySouthPos, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), TaskScheduler::Schedule(), ScheduleGround(), CreatureAI::scheduler, ScriptedAI::SelectTargetFromPlayerList(), Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetInCombatWithZone(), Creature::SetReactState(), Map::SetVisibilityRange(), UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and UNIT_STATE_IGNORE_PATHFINDING.
Reset()
void boss_nightbane::Reset () inline override virtual
Reimplemented from BossAI.
    {
        BossAI::Reset();
        _skeletonscheduler.CancelAll();
        _triggerCountTakeOffWhileFlying = 0;
        _airPhasesCompleted = 0;
        me->SetSpeed(MOVE_RUN, 2.0f);
        me->SetCanFly(true);
        me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
        me->SetReactState(REACT_PASSIVE);
        ScheduleHealthCheckEvent({ 75, 50, 25 }, [&]{
            TriggerHealthTakeOff();
        });
    }
References _airPhasesCompleted, _skeletonscheduler, _triggerCountTakeOffWhileFlying, TaskScheduler::CancelAll(), ScriptedAI::me, MOVE_RUN, REACT_PASSIVE, BossAI::Reset(), BossAI::ScheduleHealthCheckEvent(), Creature::SetCanFly(), Creature::SetReactState(), Unit::SetSpeed(), Unit::SetUnitFlag(), TriggerHealthTakeOff(), and UNIT_FLAG_NON_ATTACKABLE.
ScheduleFly()
void boss_nightbane::ScheduleFly () inline
    {
        _skeletonSpawnCounter = 0;
        scheduler.Schedule(2s, GROUP_AIR, [this](TaskContext /*context*/)
        {
            DoResetThreatList();
            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100.0f))
            {
                _skeletonSpawnPos = target->GetPosition();
                me->SetFacingTo(_skeletonSpawnPos.GetOrientation());
                me->CastSpell(_skeletonSpawnPos.GetPositionX(), _skeletonSpawnPos.GetPositionY(), _skeletonSpawnPos.GetPositionZ(), SPELL_RAIN_OF_BONES, true);
                _skeletonscheduler.Schedule(50ms, [this](TaskContext context)
                {
                    //spawns skeletons every 2 seconds until skeletonCount is reached
                    if (_skeletonSpawnCounter < _skeletonCount)
                    {
                        me->CastSpell(_skeletonSpawnPos.GetPositionX(), _skeletonSpawnPos.GetPositionY(), _skeletonSpawnPos.GetPositionZ(), SPELL_SUMMON_SKELETON, true);
                        _skeletonSpawnCounter++;
                        context.Repeat(2s);
                    }
                });
            }
        }).Schedule(15s, GROUP_AIR, [this](TaskContext context)
        {
            if (Unit* target = SelectTarget(SelectTargetMethod::Random))
            {
                DoCast(target, SPELL_SMOKING_BLAST_T);
            }
            context.Repeat(6s);
        }).Schedule(15500ms, GROUP_AIR, [this](TaskContext context)
        {
            me->SetFacingToObject(me->GetVictim());
            DoCastVictim(SPELL_SMOKING_BLAST);
            context.Repeat(1500ms);
        }).Schedule(20s, GROUP_AIR, [this](TaskContext /*context*/)
        {
            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100.0f, true))
            {
                DoCast(target, SPELL_DISTRACTING_ASH);
            }
        }).Schedule(14s, GROUP_AIR, [this](TaskContext context)
        {
            if (SelectTarget(SelectTargetMethod::MinDistance, 0, -40.0f, true))
            {
                DoCastAOE(SPELL_FIREBALL_BARRAGE);
            }
            context.Repeat(3s);
        });
    }
References _skeletonCount, _skeletonscheduler, _skeletonSpawnCounter, _skeletonSpawnPos, Unit::CastSpell(), UnitAI::DoCast(), UnitAI::DoCastAOE(), UnitAI::DoCastVictim(), ScriptedAI::DoResetThreatList(), Position::GetOrientation(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), GROUP_AIR, ScriptedAI::me, TaskContext::Repeat(), TaskScheduler::Schedule(), CreatureAI::scheduler, UnitAI::SelectTarget(), Unit::SetFacingTo(), Unit::SetFacingToObject(), SPELL_DISTRACTING_ASH, SPELL_FIREBALL_BARRAGE, SPELL_RAIN_OF_BONES, SPELL_SMOKING_BLAST, SPELL_SMOKING_BLAST_T, and SPELL_SUMMON_SKELETON.
Referenced by MovementInform().
ScheduleGround()
void boss_nightbane::ScheduleGround () inline
    {
        scheduler.Schedule(18s, 25s, GROUP_GROUND, [this](TaskContext context)
        {
            DoCastRandomTarget(SPELL_CHARRED_EARTH, 0, 100.0f, true);
            context.Repeat(20s);
        }).Schedule(25s, 35s, GROUP_GROUND, [this](TaskContext context)
        {
            DoCastVictim(SPELL_SMOLDERING_BREATH);
            context.Repeat(20s);
        }).Schedule(45s, GROUP_GROUND, [this](TaskContext context)
        {
            DoCastAOE(SPELL_BELLOWING_ROAR);
            context.Repeat(32s, 40s);
        }).Schedule(12s, GROUP_GROUND, [this](TaskContext context)
        {
            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100.0f, true))
            {
                if (!me->HasInArc(M_PI, target))
                {
                    DoCast(target, SPELL_TAIL_SWEEP);
                }
            }
            context.Repeat(15s);
        }).Schedule(5s, GROUP_GROUND, [this](TaskContext context)
        {
            DoCastVictim(SPELL_CLEAVE);
            context.Repeat(6s, 12s);
        }).Schedule(25s, GROUP_GROUND, [this](TaskContext context)
        {
            if (SelectTarget(SelectTargetMethod::MinDistance, 0, -40.0f, true))
            {
                DoCastAOE(SPELL_FIREBALL_BARRAGE);
            }
            context.Repeat(3s);
        });
    }
References UnitAI::DoCast(), UnitAI::DoCastAOE(), UnitAI::DoCastRandomTarget(), UnitAI::DoCastVictim(), GROUP_GROUND, Position::HasInArc(), ScriptedAI::me, TaskContext::Repeat(), TaskScheduler::Schedule(), CreatureAI::scheduler, UnitAI::SelectTarget(), SPELL_BELLOWING_ROAR, SPELL_CHARRED_EARTH, SPELL_CLEAVE, SPELL_FIREBALL_BARRAGE, SPELL_SMOLDERING_BREATH, and SPELL_TAIL_SWEEP.
Referenced by JustEngagedWith(), and PathEndReached().
ScheduleLand()
void boss_nightbane::ScheduleLand () inline
    {
        scheduler.Schedule(35s, GROUP_LAND, [this](TaskContext) /*context*/
        {
            Talk(YELL_LAND_PHASE);
            scheduler.CancelGroup(GROUP_AIR);
            _phase = PHASE_TRANSITION;
            me->GetMotionMaster()->Clear(false);
            me->GetMotionMaster()->MovePoint(POINT_LANDING_PRE, preFlyPos);
        });
    }
References _phase, TaskScheduler::CancelGroup(), MotionMaster::Clear(), Unit::GetMotionMaster(), GROUP_AIR, GROUP_LAND, ScriptedAI::me, MotionMaster::MovePoint(), PHASE_TRANSITION, POINT_LANDING_PRE, preFlyPos, TaskScheduler::Schedule(), CreatureAI::scheduler, and YELL_LAND_PHASE.
Referenced by MovementInform().
TriggerHealthTakeOff()
void boss_nightbane::TriggerHealthTakeOff () inline
    {
        if (_phase != PHASE_GROUND)
        {
            _triggerCountTakeOffWhileFlying++;
            return;
        }
        _phase = PHASE_TRANSITION;
        Talk(YELL_AIR_PHASE);
        scheduler.CancelGroup(GROUP_GROUND);
        me->InterruptSpell(CURRENT_GENERIC_SPELL);
        me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
        me->SetDisableGravity(true);
        me->SetCanFly(true);
        me->SendMovementFlagUpdate();
        me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
        FlyToClosestPreFlyWayPoint();
    }
References _phase, _triggerCountTakeOffWhileFlying, TaskScheduler::CancelGroup(), CURRENT_GENERIC_SPELL, EMOTE_ONESHOT_LIFTOFF, FlyToClosestPreFlyWayPoint(), GROUP_GROUND, Unit::HandleEmoteCommand(), Unit::InterruptSpell(), ScriptedAI::me, PHASE_GROUND, PHASE_TRANSITION, CreatureAI::scheduler, Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), and YELL_AIR_PHASE.
Referenced by Reset().
UpdateAI()
void boss_nightbane::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
    {
        scheduler.Update(diff);
        _skeletonscheduler.Update(diff);
        if (!UpdateVictim())
            return;
        if (_phase == PHASE_GROUND)
        {
            DoMeleeAttackIfReady();
        }
    }
References _phase, _skeletonscheduler, UnitAI::DoMeleeAttackIfReady(), PHASE_GROUND, CreatureAI::scheduler, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_airPhasesCompleted
uint8 boss_nightbane::_airPhasesCompleted private
Referenced by DamageTaken(), MovementInform(), PathEndReached(), and Reset().
_phase
uint8 boss_nightbane::_phase private
Referenced by AttackStart(), DoAction(), MoveInLineOfSight(), MovementInform(), PathEndReached(), ScheduleLand(), TriggerHealthTakeOff(), and UpdateAI().
_skeletonCount
uint8 boss_nightbane::_skeletonCount private
Referenced by boss_nightbane(), and ScheduleFly().
_skeletonscheduler
TaskScheduler boss_nightbane::_skeletonscheduler private
Referenced by Reset(), ScheduleFly(), and UpdateAI().
_skeletonSpawnCounter
uint8 boss_nightbane::_skeletonSpawnCounter private
Referenced by ScheduleFly().
_skeletonSpawnPos
Position boss_nightbane::_skeletonSpawnPos private
Referenced by ScheduleFly().
_triggerCountTakeOffWhileFlying
uint8 boss_nightbane::_triggerCountTakeOffWhileFlying private
Referenced by MovementInform(), PathEndReached(), Reset(), and TriggerHealthTakeOff().