AzerothCore: instance_karazhan::instance_karazhan_InstanceMapScript Struct Reference
instance_karazhan::instance_karazhan_InstanceMapScript Struct Reference
Public Member Functions
instance_karazhan_InstanceMapScript (Map *map)
void OnCreatureCreate (Creature *creature) override
void OnUnitDeath (Unit *unit) override
void SetData (uint32 type, uint32 data) override
bool SetBossState (uint32 type, EncounterState state) override
void SetGuidData (uint32 type, ObjectGuid data) override
void OnGameObjectCreate (GameObject *go) override
uint32 GetData (uint32 type) const override
void DoAction (int32 actionId) override
ObjectGuid GetGuidData (uint32 data) const override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 OperaEvent
uint32 OzDeathCount
uint32 OptionalBossCount
uint32 _chessTeam
uint32 _chessGamePhase
uint32 _chessEvent
ObjectGuid m_uiCurtainGUID
ObjectGuid m_uiStageDoorLeftGUID
ObjectGuid m_uiStageDoorRightGUID
ObjectGuid m_uiKilrekGUID
ObjectGuid m_uiTerestianGUID
ObjectGuid m_uiMoroesGUID
ObjectGuid m_uiNightBaneGUID
ObjectGuid m_uiLibraryDoor
ObjectGuid m_uiMassiveDoor
ObjectGuid m_uiGamesmansDoor
ObjectGuid m_uiGamesmansExitDoor
ObjectGuid ImageGUID
ObjectGuid DustCoveredChest
ObjectGuid m_uiRelayGUID
ObjectGuid _barnesGUID
ObjectGuid _echoOfMedivhGUID
GuidVector _operaDecorations [EVENT_RAJ]
GuidSet _chessPiecesGUID
GuidSet _medivhCheatFiresGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_karazhan_InstanceMapScript()
instance_karazhan::instance_karazhan_InstanceMapScript::instance_karazhan_InstanceMapScript (Map * map) inline
                                                      : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(EncounterCount);
            LoadObjectData(creatureData, gameObjectData);
            LoadDoorData(doorData);
            // 1 - OZ, 2 - HOOD, 3 - RAJ, this never gets altered.
            OperaEvent = urand(EVENT_OZ, EVENT_RAJ);
            OzDeathCount = 0;
            OptionalBossCount = 0;
            _chessTeam = TEAM_NEUTRAL;
            _chessGamePhase = CHESS_PHASE_NOT_STARTED;
            _chessEvent = NOT_STARTED;
        }
References _chessEvent, _chessGamePhase, _chessTeam, CHESS_PHASE_NOT_STARTED, creatureData, DataHeader, doorData, EncounterCount, EVENT_OZ, EVENT_RAJ, gameObjectData, InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), NOT_STARTED, OperaEvent, OptionalBossCount, OzDeathCount, InstanceScript::SetBossNumber(), InstanceScript::SetHeaders(), TEAM_NEUTRAL, and urand().
Member Function Documentation
DoAction()
void instance_karazhan::instance_karazhan_InstanceMapScript::DoAction (int32 actionId) inline override virtual
Reimplemented from InstanceScript.
        {
            if (actionId == ACTION_SCHEDULE_RAJ_CHECK)
            {
                scheduler.Schedule(10s, [this](TaskContext)
                {
                    Creature* julliane = GetCreature(DATA_JULIANNE);
                    Creature* romulo = GetCreature(DATA_ROMULO);
                    if (julliane && romulo)
                    {
                        if (julliane->HasUnitFlag(UNIT_FLAG_NOT_SELECTABLE)
                            && romulo->HasUnitFlag(UNIT_FLAG_NOT_SELECTABLE))
{
                            julliane->KillSelf();
                            julliane->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                            romulo->KillSelf();
                            romulo->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        }
                        else
{
                            if (romulo->HasUnitFlag(UNIT_FLAG_NOT_SELECTABLE))
{
                                julliane->AI()->DoAction(ACTION_RESS_ROMULO);
                            }
                            if (julliane->HasUnitFlag(UNIT_FLAG_NOT_SELECTABLE))
{
                                julliane->AI()->DoAction(ACTION_DO_RESURRECT);
                            }
                        }
                    }
                });
            }
        }
References ACTION_DO_RESURRECT, ACTION_RESS_ROMULO, ACTION_SCHEDULE_RAJ_CHECK, Creature::AI(), DATA_JULIANNE, DATA_ROMULO, UnitAI::DoAction(), InstanceScript::GetCreature(), Unit::HasUnitFlag(), Unit::KillSelf(), Unit::RemoveUnitFlag(), TaskScheduler::Schedule(), InstanceScript::scheduler, and UNIT_FLAG_NOT_SELECTABLE.
GetData()
uint32 instance_karazhan::instance_karazhan_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_OPERA_PERFORMANCE:
                    return OperaEvent;
                case DATA_OPERA_OZ_DEATHCOUNT:
                    return OzDeathCount;
                case CHESS_EVENT_TEAM:
                    return _chessTeam;
                case DATA_CHESS_GAME_PHASE:
                    return _chessGamePhase;
                case DATA_CHESS_EVENT:
                    return _chessEvent;
            }
            return 0;
        }
References _chessEvent, _chessGamePhase, _chessTeam, CHESS_EVENT_TEAM, DATA_CHESS_EVENT, DATA_CHESS_GAME_PHASE, DATA_OPERA_OZ_DEATHCOUNT, DATA_OPERA_PERFORMANCE, OperaEvent, and OzDeathCount.
GetGuidData()
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (data)
            {
                case DATA_KILREK:
                    return m_uiKilrekGUID;
                case DATA_TERESTIAN:
                    return m_uiTerestianGUID;
                case DATA_MOROES:
                    return m_uiMoroesGUID;
                case DATA_GO_STAGEDOORLEFT:
                    return m_uiStageDoorLeftGUID;
                case DATA_GO_STAGEDOORRIGHT:
                    return m_uiStageDoorRightGUID;
                case DATA_GO_CURTAINS:
                    return m_uiCurtainGUID;
                case DATA_GO_LIBRARY_DOOR:
                    return m_uiLibraryDoor;
                case DATA_GO_MASSIVE_DOOR:
                    return m_uiMassiveDoor;
                case DATA_GO_GAME_DOOR:
                    return m_uiGamesmansDoor;
                case DATA_GO_GAME_EXIT_DOOR:
                    return m_uiGamesmansExitDoor;
                case DATA_IMAGE_OF_MEDIVH:
                    return ImageGUID;
                case DATA_NIGHTBANE:
                    return m_uiNightBaneGUID;
                case DATA_ECHO_OF_MEDIVH:
                    return _echoOfMedivhGUID;
                case DATA_DUST_COVERED_CHEST:
                    return DustCoveredChest;
            }
            return ObjectGuid::Empty;
        }
References _echoOfMedivhGUID, DATA_DUST_COVERED_CHEST, DATA_ECHO_OF_MEDIVH, DATA_GO_CURTAINS, DATA_GO_GAME_DOOR, DATA_GO_GAME_EXIT_DOOR, DATA_GO_LIBRARY_DOOR, DATA_GO_MASSIVE_DOOR, DATA_GO_STAGEDOORLEFT, DATA_GO_STAGEDOORRIGHT, DATA_IMAGE_OF_MEDIVH, DATA_KILREK, DATA_MOROES, DATA_NIGHTBANE, DATA_TERESTIAN, DustCoveredChest, ObjectGuid::Empty, ImageGUID, m_uiCurtainGUID, m_uiGamesmansDoor, m_uiGamesmansExitDoor, m_uiKilrekGUID, m_uiLibraryDoor, m_uiMassiveDoor, m_uiMoroesGUID, m_uiNightBaneGUID, m_uiStageDoorLeftGUID, m_uiStageDoorRightGUID, and m_uiTerestianGUID.
OnCreatureCreate()
void instance_karazhan::instance_karazhan_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_KILREK:
                    m_uiKilrekGUID = creature->GetGUID();
                    break;
                case NPC_TERESTIAN_ILLHOOF:
                    m_uiTerestianGUID = creature->GetGUID();
                    break;
                case NPC_MOROES:
                    m_uiMoroesGUID = creature->GetGUID();
                    break;
                case NPC_NIGHTBANE:
                    m_uiNightBaneGUID = creature->GetGUID();
                    break;
                case NPC_RELAY:
                    m_uiRelayGUID = creature->GetGUID();
                    break;
                case NPC_BARNES:
                    _barnesGUID = creature->GetGUID();
                    if (GetBossState(DATA_OPERA_PERFORMANCE) != DONE && !creature->IsAlive())
                    {
                        creature->Respawn(true);
                    }
                    break;
                case NPC_PAWN_H:
                case NPC_KNIGHT_H:
                case NPC_QUEEN_H:
                case NPC_BISHOP_H:
                case NPC_ROOK_H:
                case NPC_KING_H:
                case NPC_PAWN_A:
                case NPC_KNIGHT_A:
                case NPC_QUEEN_A:
                case NPC_BISHOP_A:
                case NPC_ROOK_A:
                case NPC_KING_A:
                    _chessPiecesGUID.insert(creature->GetGUID());
                    creature->SetHealth(creature->GetMaxHealth());
                    break;
                case NPC_CHESS_EVENT_MEDIVH_CHEAT_FIRES:
                    _medivhCheatFiresGUID.insert(creature->GetGUID());
                    break;
                case NPC_ECHO_OF_MEDIVH:
                    _echoOfMedivhGUID = creature->GetGUID();
                    break;
                case NPC_FIENDISH_IMP:
                    if (Creature* terestrian = GetCreature(DATA_TERESTIAN))
                    {
                        if (terestrian->AI())
{
                            terestrian->AI()->JustSummoned(creature);
                            creature->SetInCombatWithZone();
                        }
                    }
                    break;
                default:
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References _barnesGUID, _chessPiecesGUID, _echoOfMedivhGUID, _medivhCheatFiresGUID, DATA_OPERA_PERFORMANCE, DATA_TERESTIAN, DONE, InstanceScript::GetBossState(), InstanceScript::GetCreature(), Object::GetEntry(), Object::GetGUID(), Unit::GetMaxHealth(), Unit::IsAlive(), m_uiKilrekGUID, m_uiMoroesGUID, m_uiNightBaneGUID, m_uiRelayGUID, m_uiTerestianGUID, NPC_BARNES, NPC_BISHOP_A, NPC_BISHOP_H, NPC_CHESS_EVENT_MEDIVH_CHEAT_FIRES, NPC_ECHO_OF_MEDIVH, NPC_FIENDISH_IMP, NPC_KILREK, NPC_KING_A, NPC_KING_H, NPC_KNIGHT_A, NPC_KNIGHT_H, NPC_MOROES, NPC_NIGHTBANE, NPC_PAWN_A, NPC_PAWN_H, NPC_QUEEN_A, NPC_QUEEN_H, NPC_RELAY, NPC_ROOK_A, NPC_ROOK_H, NPC_TERESTIAN_ILLHOOF, InstanceScript::OnCreatureCreate(), Creature::Respawn(), Unit::SetHealth(), and Creature::SetInCombatWithZone().
OnGameObjectCreate()
void instance_karazhan::instance_karazhan_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_STAGE_CURTAIN:
                    m_uiCurtainGUID = go->GetGUID();
                    break;
                case GO_STAGE_DOOR_LEFT:
                    m_uiStageDoorLeftGUID = go->GetGUID();
                    if (GetBossState(DATA_OPERA_PERFORMANCE) == DONE)
                        go->SetGoState(GO_STATE_ACTIVE);
                    break;
                case GO_STAGE_DOOR_RIGHT:
                    m_uiStageDoorRightGUID = go->GetGUID();
                    if (GetBossState(DATA_OPERA_PERFORMANCE) == DONE)
                        go->SetGoState(GO_STATE_ACTIVE);
                    break;
                case GO_PRIVATE_LIBRARY_DOOR:
                    m_uiLibraryDoor = go->GetGUID();
                    break;
                case GO_MASSIVE_DOOR:
                    m_uiMassiveDoor = go->GetGUID();
                    if (GetBossState(DATA_ARAN) != IN_PROGRESS)
                        go->SetGameObjectFlag(GO_FLAG_LOCKED);
                    else
                        go->RemoveGameObjectFlag(GO_FLAG_LOCKED);
                    break;
                case GO_GAMESMAN_HALL_DOOR:
                    m_uiGamesmansDoor = go->GetGUID();
                    break;
                case GO_GAMESMAN_HALL_EXIT_DOOR:
                    m_uiGamesmansExitDoor = go->GetGUID();
                    break;
                case GO_SIDE_ENTRANCE_DOOR:
                    if (GetBossState(DATA_OPERA_PERFORMANCE) == DONE)
                        go->RemoveGameObjectFlag(GO_FLAG_LOCKED);
                    else
                        go->SetGameObjectFlag(GO_FLAG_LOCKED);
                    break;
                case GO_DUST_COVERED_CHEST:
                    DustCoveredChest = go->GetGUID();
                    break;
                case GO_OZ_BACKDROP:
                case GO_OZ_HAY:
                    _operaDecorations[EVENT_OZ - 1].push_back(go->GetGUID());
                    break;
                case GO_HOOD_BACKDROP:
                case GO_HOOD_TREE:
                case GO_HOOD_HOUSE:
                    _operaDecorations[EVENT_HOOD - 1].push_back(go->GetGUID());
                    break;
                case GO_RAJ_BACKDROP:
                case GO_RAJ_MOON:
                case GO_RAJ_BALCONY:
                    _operaDecorations[EVENT_RAJ - 1].push_back(go->GetGUID());
                    break;
                default:
                    break;
            }
            InstanceScript::OnGameObjectCreate(go);
        }
References _operaDecorations, DATA_ARAN, DATA_OPERA_PERFORMANCE, DONE, DustCoveredChest, EVENT_HOOD, EVENT_OZ, EVENT_RAJ, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_DUST_COVERED_CHEST, GO_FLAG_LOCKED, GO_GAMESMAN_HALL_DOOR, GO_GAMESMAN_HALL_EXIT_DOOR, GO_HOOD_BACKDROP, GO_HOOD_HOUSE, GO_HOOD_TREE, GO_MASSIVE_DOOR, GO_OZ_BACKDROP, GO_OZ_HAY, GO_PRIVATE_LIBRARY_DOOR, GO_RAJ_BACKDROP, GO_RAJ_BALCONY, GO_RAJ_MOON, GO_SIDE_ENTRANCE_DOOR, GO_STAGE_CURTAIN, GO_STAGE_DOOR_LEFT, GO_STAGE_DOOR_RIGHT, GO_STATE_ACTIVE, IN_PROGRESS, m_uiCurtainGUID, m_uiGamesmansDoor, m_uiGamesmansExitDoor, m_uiLibraryDoor, m_uiMassiveDoor, m_uiStageDoorLeftGUID, m_uiStageDoorRightGUID, InstanceScript::OnGameObjectCreate(), GameObject::RemoveGameObjectFlag(), GameObject::SetGameObjectFlag(), and GameObject::SetGoState().
OnUnitDeath()
void instance_karazhan::instance_karazhan_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            Creature* creature = unit->ToCreature();
            if (!creature)
                return;
            switch (creature->GetEntry())
            {
                case NPC_COLDMIST_WIDOW:
                case NPC_COLDMIST_STALKER:
                case NPC_SHADOWBAT:
                case NPC_VAMPIRIC_SHADOWBAT:
                case NPC_GREATER_SHADOWBAT:
                case NPC_PHASE_HOUND:
                case NPC_DREADBEAST:
                case NPC_SHADOWBEAST:
                    if (GetBossState(DATA_OPTIONAL_BOSS) == TO_BE_DECIDED)
                    {
                        ++OptionalBossCount;
                        if (OptionalBossCount == OPTIONAL_BOSS_REQUIRED_DEATH_COUNT)
{
                            switch (urand(NPC_HYAKISS_THE_LURKER, NPC_ROKAD_THE_RAVAGER))
{
                                case NPC_HYAKISS_THE_LURKER:
                                    instance->SummonCreature(NPC_HYAKISS_THE_LURKER, OptionalSpawn[0]);
                                    break;
                                case NPC_SHADIKITH_THE_GLIDER:
                                    instance->SummonCreature(NPC_SHADIKITH_THE_GLIDER, OptionalSpawn[1]);
                                    break;
                                case NPC_ROKAD_THE_RAVAGER:
                                    instance->SummonCreature(NPC_ROKAD_THE_RAVAGER, OptionalSpawn[2]);
                                    break;
                            }
                        }
                    }
                    break;
                case NPC_HYAKISS_THE_LURKER:
                case NPC_SHADIKITH_THE_GLIDER:
                case NPC_ROKAD_THE_RAVAGER:
                    SetBossState(DATA_OPTIONAL_BOSS, DONE);
                    instance->ToInstanceMap()->PermBindAllPlayers();
                    break;
                default:
                    break;
            }
        }
References DATA_OPTIONAL_BOSS, DONE, InstanceScript::GetBossState(), Object::GetEntry(), InstanceScript::instance, NPC_COLDMIST_STALKER, NPC_COLDMIST_WIDOW, NPC_DREADBEAST, NPC_GREATER_SHADOWBAT, NPC_HYAKISS_THE_LURKER, NPC_PHASE_HOUND, NPC_ROKAD_THE_RAVAGER, NPC_SHADIKITH_THE_GLIDER, NPC_SHADOWBAT, NPC_SHADOWBEAST, NPC_VAMPIRIC_SHADOWBAT, OPTIONAL_BOSS_REQUIRED_DEATH_COUNT, OptionalBossCount, OptionalSpawn, InstanceMap::PermBindAllPlayers(), SetBossState(), Map::SummonCreature(), TO_BE_DECIDED, Object::ToCreature(), Map::ToInstanceMap(), and urand().
SetBossState()
bool instance_karazhan::instance_karazhan_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            switch (type)
            {
                case DATA_OPERA_PERFORMANCE:
                    if (state == DONE)
                    {
                        HandleGameObject(m_uiStageDoorLeftGUID, true);
                        HandleGameObject(m_uiStageDoorRightGUID, true);
                        instance->UpdateEncounterState(ENCOUNTER_CREDIT_KILL_CREATURE, 16812, nullptr);
                    }
                    else if (state == FAIL)
                    {
                        HandleGameObject(m_uiStageDoorLeftGUID, true);
                        HandleGameObject(m_uiStageDoorRightGUID, false);
                        HandleGameObject(m_uiCurtainGUID, false);
                        DoRespawnCreature(_barnesGUID, true);
                    }
                    break;
                default:
                    break;
            }
            return true;
        }
References _barnesGUID, DATA_OPERA_PERFORMANCE, DONE, InstanceScript::DoRespawnCreature(), ENCOUNTER_CREDIT_KILL_CREATURE, FAIL, InstanceScript::HandleGameObject(), InstanceScript::instance, m_uiCurtainGUID, m_uiStageDoorLeftGUID, m_uiStageDoorRightGUID, InstanceScript::SetBossState(), and Map::UpdateEncounterState().
Referenced by OnUnitDeath().
SetData()
void instance_karazhan::instance_karazhan_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_OPERA_OZ_DEATHCOUNT:
                    if (data == SPECIAL)
                        ++OzDeathCount;
                    else if (data == IN_PROGRESS)
                        OzDeathCount = 0;
                    break;
                case DATA_SPAWN_OPERA_DECORATIONS:
                {
                    for (ObjectGuid const& guid : _operaDecorations[data - 1])
                    {
                        DoRespawnGameObject(guid, DAY);
                    }
                    break;
                }
                case DATA_CHESS_EVENT:
                {
                    _chessEvent = data;
                    switch (data)
                    {
                        case IN_PROGRESS:
                        case SPECIAL:
{
                            DoCastSpellOnPlayers(SPELL_GAME_IN_SESSION);
                            for (ObjectGuid const& chessPieceGUID : _chessPiecesGUID)
{
                                if (Creature* piece = instance->GetCreature(chessPieceGUID))
{
                                    if (_chessTeam == TEAM_ALLIANCE)
{
                                        if (piece->GetFaction() == CHESS_FACTION_ALLIANCE)
{
                                            piece->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                                        }
                                    }
                                    else if (_chessTeam == TEAM_HORDE)
{
                                        if (piece->GetFaction() == CHESS_FACTION_HORDE)
{
                                            piece->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                                        }
                                    }
                                    else
{
                                        piece->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                                    }
                                }
                            }
                            break;
                        case DONE:
                            HandleGameObject(m_uiGamesmansExitDoor, true);
                            instance->ToInstanceMap()->PermBindAllPlayers();
                            break;
                        }
                        default:
                            DoRemoveAurasDueToSpellOnPlayers(SPELL_GAME_IN_SESSION);
                            break;
                    }
                    break;
                }
                case CHESS_EVENT_TEAM:
                    _chessTeam = data;
                    break;
                case DATA_CHESS_REINIT_PIECES:
                    for (ObjectGuid const& chessPieceGUID : _chessPiecesGUID)
                    {
                        if (Creature* piece = instance->GetCreature(chessPieceGUID))
{
                            piece->RemoveAllAuras();
                            piece->setDeathState(DeathState::JustRespawned);
                            piece->SetHealth(piece->GetMaxHealth());
                            float x, y, z, o;
                            piece->GetHomePosition(x, y, z, o);
                            piece->NearTeleportTo(x, y, z, o);
                            piece->AI()->DoAction(ACTION_CHESS_PIECE_RESET_ORIENTATION);
                            piece->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                            piece->AI()->Reset();
                        }
                    }
                    for (ObjectGuid const& medivhCheatFireGUID : _medivhCheatFiresGUID)
                    {
                        if (Creature* fire = instance->GetCreature(medivhCheatFireGUID))
{
                            fire->DespawnOrUnsummon();
                        }
                    }
                    _medivhCheatFiresGUID.clear();
                    break;
                case DATA_CHESS_GAME_PHASE:
                    _chessGamePhase = data;
                    break;
                default:
                    break;
            }
        }
References _chessEvent, _chessGamePhase, _chessPiecesGUID, _chessTeam, _medivhCheatFiresGUID, _operaDecorations, ACTION_CHESS_PIECE_RESET_ORIENTATION, CHESS_EVENT_TEAM, CHESS_FACTION_ALLIANCE, CHESS_FACTION_HORDE, DATA_CHESS_EVENT, DATA_CHESS_GAME_PHASE, DATA_CHESS_REINIT_PIECES, DATA_OPERA_OZ_DEATHCOUNT, DATA_SPAWN_OPERA_DECORATIONS, DAY, InstanceScript::DoCastSpellOnPlayers(), DONE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), InstanceScript::DoRespawnGameObject(), Map::GetCreature(), InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, m_uiGamesmansExitDoor, OzDeathCount, InstanceMap::PermBindAllPlayers(), SPECIAL, SPELL_GAME_IN_SESSION, TEAM_ALLIANCE, TEAM_HORDE, Map::ToInstanceMap(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_NPC_FLAG_GOSSIP.
SetGuidData()
void instance_karazhan::instance_karazhan_InstanceMapScript::SetGuidData (uint32 type, ObjectGuid data) inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == DATA_IMAGE_OF_MEDIVH)
                ImageGUID = data;
        }
References DATA_IMAGE_OF_MEDIVH, and ImageGUID.
Member Data Documentation
_barnesGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::_barnesGUID private
Referenced by OnCreatureCreate(), and SetBossState().
_chessEvent
uint32 instance_karazhan::instance_karazhan_InstanceMapScript::_chessEvent private
Referenced by GetData(), instance_karazhan_InstanceMapScript(), and SetData().
_chessGamePhase
uint32 instance_karazhan::instance_karazhan_InstanceMapScript::_chessGamePhase private
Referenced by GetData(), instance_karazhan_InstanceMapScript(), and SetData().
_chessPiecesGUID
GuidSet instance_karazhan::instance_karazhan_InstanceMapScript::_chessPiecesGUID private
Referenced by OnCreatureCreate(), and SetData().
_chessTeam
uint32 instance_karazhan::instance_karazhan_InstanceMapScript::_chessTeam private
Referenced by GetData(), instance_karazhan_InstanceMapScript(), and SetData().
_echoOfMedivhGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::_echoOfMedivhGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
_medivhCheatFiresGUID
GuidSet instance_karazhan::instance_karazhan_InstanceMapScript::_medivhCheatFiresGUID private
Referenced by OnCreatureCreate(), and SetData().
_operaDecorations
GuidVector instance_karazhan::instance_karazhan_InstanceMapScript::_operaDecorations[EVENT_RAJ] private
Referenced by OnGameObjectCreate(), and SetData().
DustCoveredChest
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::DustCoveredChest private
Referenced by GetGuidData(), and OnGameObjectCreate().
ImageGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::ImageGUID private
Referenced by GetGuidData(), and SetGuidData().
m_uiCurtainGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiCurtainGUID private
Referenced by GetGuidData(), OnGameObjectCreate(), and SetBossState().
m_uiGamesmansDoor
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiGamesmansDoor private
Referenced by GetGuidData(), and OnGameObjectCreate().
m_uiGamesmansExitDoor
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiGamesmansExitDoor private
Referenced by GetGuidData(), OnGameObjectCreate(), and SetData().
m_uiKilrekGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiKilrekGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiLibraryDoor
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiLibraryDoor private
Referenced by GetGuidData(), and OnGameObjectCreate().
m_uiMassiveDoor
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiMassiveDoor private
Referenced by GetGuidData(), and OnGameObjectCreate().
m_uiMoroesGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiMoroesGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiNightBaneGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiNightBaneGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiRelayGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiRelayGUID private
Referenced by OnCreatureCreate().
m_uiStageDoorLeftGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiStageDoorLeftGUID private
Referenced by GetGuidData(), OnGameObjectCreate(), and SetBossState().
m_uiStageDoorRightGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiStageDoorRightGUID private
Referenced by GetGuidData(), OnGameObjectCreate(), and SetBossState().
m_uiTerestianGUID
ObjectGuid instance_karazhan::instance_karazhan_InstanceMapScript::m_uiTerestianGUID private
Referenced by GetGuidData(), and OnCreatureCreate().
OperaEvent
uint32 instance_karazhan::instance_karazhan_InstanceMapScript::OperaEvent private
Referenced by GetData(), and instance_karazhan_InstanceMapScript().
OptionalBossCount
uint32 instance_karazhan::instance_karazhan_InstanceMapScript::OptionalBossCount private
Referenced by instance_karazhan_InstanceMapScript(), and OnUnitDeath().
OzDeathCount
uint32 instance_karazhan::instance_karazhan_InstanceMapScript::OzDeathCount private
Referenced by GetData(), instance_karazhan_InstanceMapScript(), and SetData().