AzerothCore: OutdoorPvPZM Class Reference
OutdoorPvPZM Class Reference
#include "OutdoorPvPZM.h"
Public Member Functions
OutdoorPvPZM ()
bool SetupOutdoorPvP () override
void HandlePlayerEnterZone (Player *player, uint32 zone) override
void HandlePlayerLeaveZone (Player *player, uint32 zone) override
bool Update (uint32 diff) override
void FillInitialWorldStates (WorldPacket &data) override
void SendRemoveWorldStates (Player *player) override
void HandleKillImpl (Player *player, Unit *killed) override
uint32 GetAllianceTowersControlled () const
void SetAllianceTowersControlled (uint32 count)
uint32 GetHordeTowersControlled () const
void SetHordeTowersControlled (uint32 count)
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()=default
~OutdoorPvP () override
void DeleteSpawns ()
virtual void FillInitialWorldStates (WorldPacket &)
virtual bool HandleAreaTrigger (Player *player, uint32 trigger)
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual bool HandleOpenGo (Player *player, GameObject *go)
virtual bool SetupOutdoorPvP ()
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SendUpdateWorldState (uint32 field, uint32 value)
virtual bool Update (uint32 diff)
virtual void HandleKill (Player *killer, Unit *killed)
virtual void HandleKillImpl (Player *, Unit *)
bool IsInsideObjective (Player *player) const
virtual void AwardKillBonus (Player *)
uint32 GetTypeId () const
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipId)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
void TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2=0, Player *sameMapPlr=nullptr)
Map * GetMap () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
OPvPCapturePointZM_GraveYard * m_GraveYard
uint32 m_AllianceTowersControlled
uint32 m_HordeTowersControlled
Additional Inherited Members
Public Types inherited from OutdoorPvP
typedef std::map< ObjectGuid::LowType, OPvPCapturePoint * > OPvPCapturePointMap
typedef std::pair< ObjectGuid::LowType, GameObject * > GoScriptPair
typedef std::pair< ObjectGuid::LowType, Creature * > CreatureScriptPair
Protected Member Functions inherited from OutdoorPvP
void BroadcastPacket (WorldPacket &data) const
virtual void SendRemoveWorldStates (Player *)
virtual void HandlePlayerEnterZone (Player *player, uint32 zone)
virtual void HandlePlayerLeaveZone (Player *player, uint32 zone)
virtual void HandlePlayerResurrects (Player *player, uint32 zone)
void AddCapturePoint (OPvPCapturePoint *cp)
OPvPCapturePoint * GetCapturePoint (ObjectGuid::LowType spawnId) const
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player const *player) const
void TeamCastSpell (TeamId team, int32 spellId, Player *sameMapPlr=nullptr)
void SetMapFromZone (uint32 zone)
Protected Attributes inherited from OutdoorPvP
OPvPCapturePointMap _capturePoints
std::array< PlayerSet, 2 > _players
uint32 _typeId {}
bool _sendUpdate { true }
Map * _map {}
std::unordered_map< ObjectGuid::LowType, GameObject * > _goScriptStore
std::unordered_map< ObjectGuid::LowType, Creature * > _creatureScriptStore
Detailed Description
Constructor & Destructor Documentation
OutdoorPvPZM()
OutdoorPvPZM::OutdoorPvPZM ()
{
    _typeId = OUTDOOR_PVP_ZM;
    m_GraveYard = nullptr;
    m_AllianceTowersControlled = 0;
    m_HordeTowersControlled = 0;
}
References OutdoorPvP::_typeId, m_AllianceTowersControlled, m_GraveYard, m_HordeTowersControlled, and OUTDOOR_PVP_ZM.
Member Function Documentation
FillInitialWorldStates()
void OutdoorPvPZM::FillInitialWorldStates (WorldPacket & data) override virtual
Reimplemented from OutdoorPvP.
{
    data << ZM_WORLDSTATE_UNK_1 << uint32(1);
    for (OPvPCapturePointMap::iterator itr = _capturePoints.begin(); itr != _capturePoints.end(); ++itr)
    {
        itr->second->FillInitialWorldStates(data);
    }
}
References OutdoorPvP::_capturePoints, and ZM_WORLDSTATE_UNK_1.
GetAllianceTowersControlled()
uint32 OutdoorPvPZM::GetAllianceTowersControlled () const
{
    return m_AllianceTowersControlled;
}
References m_AllianceTowersControlled.
GetHordeTowersControlled()
uint32 OutdoorPvPZM::GetHordeTowersControlled () const
{
    return m_HordeTowersControlled;
}
References m_HordeTowersControlled.
HandleKillImpl()
void OutdoorPvPZM::HandleKillImpl (Player * player, Unit * killed) override virtual
Reimplemented from OutdoorPvP.
{
    if (!killed->IsPlayer())
        return;
    if (player->GetTeamId() == TEAM_ALLIANCE && killed->ToPlayer()->GetTeamId() != TEAM_ALLIANCE)
        player->CastSpell(player, ZM_AlliancePlayerKillReward, true);
    else if (player->GetTeamId() == TEAM_HORDE && killed->ToPlayer()->GetTeamId() != TEAM_HORDE)
        player->CastSpell(player, ZM_HordePlayerKillReward, true);
}
References Unit::CastSpell(), Player::GetTeamId(), Object::IsPlayer(), TEAM_ALLIANCE, TEAM_HORDE, Object::ToPlayer(), ZM_AlliancePlayerKillReward, and ZM_HordePlayerKillReward.
HandlePlayerEnterZone()
void OutdoorPvPZM::HandlePlayerEnterZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
{
    if (player->GetTeamId() == TEAM_ALLIANCE)
    {
        if (m_GraveYard->GetGraveYardState() & ZM_GRAVEYARD_A)
            player->CastSpell(player, ZM_CAPTURE_BUFF, true);
    }
    else
    {
        if (m_GraveYard->GetGraveYardState() & ZM_GRAVEYARD_H)
            player->CastSpell(player, ZM_CAPTURE_BUFF, true);
    }
    OutdoorPvP::HandlePlayerEnterZone(player, zone);
}
References Unit::CastSpell(), OPvPCapturePointZM_GraveYard::GetGraveYardState(), Player::GetTeamId(), OutdoorPvP::HandlePlayerEnterZone(), m_GraveYard, TEAM_ALLIANCE, ZM_CAPTURE_BUFF, ZM_GRAVEYARD_A, and ZM_GRAVEYARD_H.
HandlePlayerLeaveZone()
void OutdoorPvPZM::HandlePlayerLeaveZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
{
    // remove buffs
    player->RemoveAurasDueToSpell(ZM_CAPTURE_BUFF);
    // remove flag
    player->RemoveAurasDueToSpell(ZM_BATTLE_STANDARD_A);
    player->RemoveAurasDueToSpell(ZM_BATTLE_STANDARD_H);
    OutdoorPvP::HandlePlayerLeaveZone(player, zone);
}
References OutdoorPvP::HandlePlayerLeaveZone(), Unit::RemoveAurasDueToSpell(), ZM_BATTLE_STANDARD_A, ZM_BATTLE_STANDARD_H, and ZM_CAPTURE_BUFF.
SendRemoveWorldStates()
void OutdoorPvPZM::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
{
    player->SendUpdateWorldState(ZM_UI_TOWER_SLIDER_N_W, 0);
    player->SendUpdateWorldState(ZM_UI_TOWER_SLIDER_POS_W, 0);
    player->SendUpdateWorldState(ZM_UI_TOWER_SLIDER_DISPLAY_W, 0);
    player->SendUpdateWorldState(ZM_UI_TOWER_SLIDER_N_E, 0);
    player->SendUpdateWorldState(ZM_UI_TOWER_SLIDER_POS_E, 0);
    player->SendUpdateWorldState(ZM_UI_TOWER_SLIDER_DISPLAY_E, 0);
    player->SendUpdateWorldState(ZM_WORLDSTATE_UNK_1, 1);
    player->SendUpdateWorldState(ZM_UI_TOWER_EAST_N, 0);
    player->SendUpdateWorldState(ZM_UI_TOWER_EAST_H, 0);
    player->SendUpdateWorldState(ZM_UI_TOWER_EAST_A, 0);
    player->SendUpdateWorldState(ZM_UI_TOWER_WEST_N, 0);
    player->SendUpdateWorldState(ZM_UI_TOWER_WEST_H, 0);
    player->SendUpdateWorldState(ZM_UI_TOWER_WEST_A, 0);
    player->SendUpdateWorldState(ZM_MAP_TOWER_EAST_N, 0);
    player->SendUpdateWorldState(ZM_MAP_TOWER_EAST_H, 0);
    player->SendUpdateWorldState(ZM_MAP_TOWER_EAST_A, 0);
    player->SendUpdateWorldState(ZM_MAP_GRAVEYARD_H, 0);
    player->SendUpdateWorldState(ZM_MAP_GRAVEYARD_A, 0);
    player->SendUpdateWorldState(ZM_MAP_GRAVEYARD_N, 0);
    player->SendUpdateWorldState(ZM_MAP_TOWER_WEST_N, 0);
    player->SendUpdateWorldState(ZM_MAP_TOWER_WEST_H, 0);
    player->SendUpdateWorldState(ZM_MAP_TOWER_WEST_A, 0);
    player->SendUpdateWorldState(ZM_MAP_HORDE_FLAG_READY, 0);
    player->SendUpdateWorldState(ZM_MAP_HORDE_FLAG_NOT_READY, 0);
    player->SendUpdateWorldState(ZM_MAP_ALLIANCE_FLAG_NOT_READY, 0);
    player->SendUpdateWorldState(ZM_MAP_ALLIANCE_FLAG_READY, 0);
}
References Player::SendUpdateWorldState(), ZM_MAP_ALLIANCE_FLAG_NOT_READY, ZM_MAP_ALLIANCE_FLAG_READY, ZM_MAP_GRAVEYARD_A, ZM_MAP_GRAVEYARD_H, ZM_MAP_GRAVEYARD_N, ZM_MAP_HORDE_FLAG_NOT_READY, ZM_MAP_HORDE_FLAG_READY, ZM_MAP_TOWER_EAST_A, ZM_MAP_TOWER_EAST_H, ZM_MAP_TOWER_EAST_N, ZM_MAP_TOWER_WEST_A, ZM_MAP_TOWER_WEST_H, ZM_MAP_TOWER_WEST_N, ZM_UI_TOWER_EAST_A, ZM_UI_TOWER_EAST_H, ZM_UI_TOWER_EAST_N, ZM_UI_TOWER_SLIDER_DISPLAY_E, ZM_UI_TOWER_SLIDER_DISPLAY_W, ZM_UI_TOWER_SLIDER_N_E, ZM_UI_TOWER_SLIDER_N_W, ZM_UI_TOWER_SLIDER_POS_E, ZM_UI_TOWER_SLIDER_POS_W, ZM_UI_TOWER_WEST_A, ZM_UI_TOWER_WEST_H, ZM_UI_TOWER_WEST_N, and ZM_WORLDSTATE_UNK_1.
SetAllianceTowersControlled()
void OutdoorPvPZM::SetAllianceTowersControlled (uint32 count)
{
    m_AllianceTowersControlled = count;
}
References m_AllianceTowersControlled.
SetHordeTowersControlled()
void OutdoorPvPZM::SetHordeTowersControlled (uint32 count)
{
    m_HordeTowersControlled = count;
}
References m_HordeTowersControlled.
SetupOutdoorPvP()
bool OutdoorPvPZM::SetupOutdoorPvP () override virtual
Reimplemented from OutdoorPvP.
{
    m_AllianceTowersControlled = 0;
    m_HordeTowersControlled = 0;
    // add the zones affected by the pvp buff
    for (uint8 i = 0; i < OutdoorPvPZMBuffZonesNum; ++i)
        RegisterZone(OutdoorPvPZMBuffZones[i]);
    SetMapFromZone(OutdoorPvPZMBuffZones[0]);
    AddCapturePoint(new OPvPCapturePointZM_Beacon(this, ZM_BEACON_WEST));
    AddCapturePoint(new OPvPCapturePointZM_Beacon(this, ZM_BEACON_EAST));
    m_GraveYard = new OPvPCapturePointZM_GraveYard(this);
    AddCapturePoint(m_GraveYard); // though the update function isn't used, the handleusego is!
    return true;
}
References OutdoorPvP::AddCapturePoint(), m_AllianceTowersControlled, m_GraveYard, m_HordeTowersControlled, OutdoorPvPZMBuffZones, OutdoorPvPZMBuffZonesNum, OutdoorPvP::RegisterZone(), OutdoorPvP::SetMapFromZone(), ZM_BEACON_EAST, and ZM_BEACON_WEST.
Update()
bool OutdoorPvPZM::Update (uint32 diff) override virtual
Reimplemented from OutdoorPvP.
{
    bool changed = OutdoorPvP::Update(diff);
    if (changed)
    {
        if (m_AllianceTowersControlled == ZM_NUM_BEACONS)
            m_GraveYard->SetBeaconState(TEAM_ALLIANCE);
        else if (m_HordeTowersControlled == ZM_NUM_BEACONS)
            m_GraveYard->SetBeaconState(TEAM_HORDE);
        else
            m_GraveYard->SetBeaconState(TEAM_NEUTRAL);
    }
    return changed;
}
References m_AllianceTowersControlled, m_GraveYard, m_HordeTowersControlled, OPvPCapturePointZM_GraveYard::SetBeaconState(), TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, OutdoorPvP::Update(), and ZM_NUM_BEACONS.
Member Data Documentation
m_AllianceTowersControlled
uint32 OutdoorPvPZM::m_AllianceTowersControlled private
Referenced by GetAllianceTowersControlled(), OutdoorPvPZM(), SetAllianceTowersControlled(), SetupOutdoorPvP(), and Update().
m_GraveYard
OPvPCapturePointZM_GraveYard* OutdoorPvPZM::m_GraveYard private
Referenced by HandlePlayerEnterZone(), OutdoorPvPZM(), SetupOutdoorPvP(), and Update().
m_HordeTowersControlled
uint32 OutdoorPvPZM::m_HordeTowersControlled private
Referenced by GetHordeTowersControlled(), OutdoorPvPZM(), SetHordeTowersControlled(), SetupOutdoorPvP(), and Update().