AzerothCore: boss_paletress::boss_paletressAI Struct Reference
boss_paletress::boss_paletressAI Struct Reference
Public Member Functions
boss_paletressAI (Creature *pCreature)
void Reset () override
void MovementInform (uint32 type, uint32 id) override
void KilledUnit (Unit *who) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void DoAction (int32 param) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonMemory ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
bool summoned
ObjectGuid MemoryGUID
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_paletressAI()
boss_paletress::boss_paletressAI::boss_paletressAI (Creature * pCreature) inline
                                              : ScriptedAI(pCreature)
        {
            pInstance = pCreature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
DamageTaken()
void boss_paletress::boss_paletressAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            //if (me->HasAura(SPELL_SHIELD))
            //  return;
            if (damage >= me->GetHealth())
            {
                damage = me->GetHealth() - 1;
                if (me->GetFaction() != FACTION_FRIENDLY)
                {
                    me->CastSpell((Unit*)nullptr, 68574, true); // achievements
                    me->SetFaction(FACTION_FRIENDLY);
                    events.Reset();
                    Talk(SAY_PALETRESS_DEFEATED);
                    me->GetThreatMgr().clearReferences();
                    me->SetRegeneratingHealth(false);
                    _EnterEvadeMode();
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->SetImmuneToAll(true);
                    if (pInstance)
                    {
                        pInstance->SetData(BOSS_ARGENT_CHALLENGE, DONE);
                        pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, 68206);
                    }
                }
            }
        }
References CreatureAI::_EnterEvadeMode(), ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, BOSS_ARGENT_CHALLENGE, Unit::CastSpell(), ThreatMgr::clearReferences(), DONE, InstanceScript::DoUpdateAchievementCriteria(), FACTION_FRIENDLY, Unit::GetFaction(), Unit::GetHealth(), Unit::GetThreatMgr(), ScriptedAI::me, pInstance, SAY_PALETRESS_DEFEATED, ZoneScript::SetData(), Unit::SetFaction(), Unit::SetImmuneToAll(), Creature::SetRegeneratingHealth(), Unit::SetUnitFlag(), and UNIT_FLAG_NON_ATTACKABLE.
DoAction()
void boss_paletress::boss_paletressAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == 1)
            {
                MemoryGUID.Clear();
                me->RemoveAura(SPELL_SHIELD);
                Talk(SAY_PALETRESS_MEMORY_DEATH);
            }
            else if (param == (-1))
            {
                if (MemoryGUID)
                    if (Creature* memory = ObjectAccessor::GetCreature(*me, MemoryGUID))
                    {
                        memory->DespawnOrUnsummon();
                        MemoryGUID.Clear();
                    }
            }
        }
References ObjectGuid::Clear(), ObjectAccessor::GetCreature(), ScriptedAI::me, MemoryGUID, Unit::RemoveAura(), SAY_PALETRESS_MEMORY_DEATH, and SPELL_SHIELD.
JustEngagedWith()
void boss_paletress::boss_paletressAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            events.Reset();
            events.ScheduleEvent(EVENT_SPELL_HOLY_FIRE, 9s, 12s);
            events.ScheduleEvent(EVENT_SPELL_SMITE, 2s, 3s);
            me->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
            Talk(SAY_PALETRESS_AGGRO);
            if (pInstance)
                pInstance->SetData(BOSS_ARGENT_CHALLENGE, IN_PROGRESS);
        }
References BOSS_ARGENT_CHALLENGE, EVENT_SPELL_HOLY_FIRE, EVENT_SPELL_SMITE, IN_PROGRESS, ScriptedAI::me, MOVEMENTFLAG_WALKING, pInstance, Unit::RemoveUnitMovementFlag(), SAY_PALETRESS_AGGRO, and ZoneScript::SetData().
JustSummoned()
void boss_paletress::boss_paletressAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (pInstance)
                pInstance->SetData(DATA_MEMORY_ENTRY, summon->GetEntry());
            MemoryGUID = summon->GetGUID();
        }
References DATA_MEMORY_ENTRY, Object::GetEntry(), Object::GetGUID(), MemoryGUID, pInstance, and ZoneScript::SetData().
KilledUnit()
void boss_paletress::boss_paletressAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (who->IsPlayer())
            {
                Talk(SAY_PALETRESS_KILL_PLAYER);
            }
        }
References Object::IsPlayer(), and SAY_PALETRESS_KILL_PLAYER.
MovementInform()
void boss_paletress::boss_paletressAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type == POINT_MOTION_TYPE && id == 1)
                me->SetFacingTo(3 * M_PI / 2);
        }
References ScriptedAI::me, POINT_MOTION_TYPE, and Unit::SetFacingTo().
Reset()
void boss_paletress::boss_paletressAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Reset();
            summoned = false;
            if (MemoryGUID)
            {
                if (Creature* memory = ObjectAccessor::GetCreature(*me, MemoryGUID))
                    memory->DespawnOrUnsummon();
                MemoryGUID.Clear();
            }
            me->SetReactState(REACT_PASSIVE);
            if (pInstance)
                pInstance->SetData(BOSS_ARGENT_CHALLENGE, NOT_STARTED);
        }
References BOSS_ARGENT_CHALLENGE, ObjectGuid::Clear(), ObjectAccessor::GetCreature(), ScriptedAI::me, MemoryGUID, NOT_STARTED, pInstance, REACT_PASSIVE, ZoneScript::SetData(), Creature::SetReactState(), and summoned.
SummonMemory()
void boss_paletress::boss_paletressAI::SummonMemory () inline
        {
            uint8 uiRandom = urand(0, 25);
            uint32 uiSpells[26] = {66704, 66705, 66706, 66707, 66709, 66710, 66711, 66712, 66713, 66714, 66715, 66708, 66708, 66691, 66692, 66694, 66695, 66696, 66697, 66698, 66699, 66700, 66701, 66702, 66703, 66543};
            me->CastSpell(me, uiSpells[uiRandom], true);
        }
References Unit::CastSpell(), ScriptedAI::me, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_paletress::boss_paletressAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (!summoned && HealthBelowPct(25))
            {
                me->InterruptNonMeleeSpells(true);
                Talk(SAY_PALETRESS_MEMORY_SUMMON);
                me->CastSpell((Unit*)nullptr, SPELL_HOLY_NOVA, false);
                me->CastSpell(me, SPELL_SHIELD, false);
                me->CastSpell((Unit*)nullptr, SPELL_SUMMON_MEMORY, false);
                SummonMemory();
                me->CastSpell((Unit*)nullptr, SPELL_CONFESS, false);
                events.ScheduleEvent(EVENT_SPELL_RENEW, 6s, 8s);
                summoned = true;
                return;
            }
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_SPELL_SMITE:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 50.0f, true))
                        me->CastSpell(target, SPELL_SMITE, false);
                    events.Repeat(3s, 4s);
                    break;
                case EVENT_SPELL_HOLY_FIRE:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 30.0f, true))
                        me->CastSpell(target, SPELL_HOLY_FIRE, false);
                    events.Repeat(9s, 12s);
                    break;
                case EVENT_SPELL_RENEW:
                    if (!MemoryGUID)
                    {
                        break;
                    }
                    if (urand(0, 1))
                        me->CastSpell(me, SPELL_RENEW, false);
                    else if (Creature* memory = ObjectAccessor::GetCreature(*me, MemoryGUID))
                        if (memory->IsAlive())
                            me->CastSpell(memory, SPELL_RENEW, false);
                    events.Repeat(15s, 17s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_SPELL_HOLY_FIRE, EVENT_SPELL_RENEW, EVENT_SPELL_SMITE, ObjectAccessor::GetCreature(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, MemoryGUID, SAY_PALETRESS_MEMORY_SUMMON, UnitAI::SelectTarget(), SPELL_CONFESS, SPELL_HOLY_FIRE, SPELL_HOLY_NOVA, SPELL_RENEW, SPELL_SHIELD, SPELL_SMITE, SPELL_SUMMON_MEMORY, summoned, SummonMemory(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap boss_paletress::boss_paletressAI::events
MemoryGUID
ObjectGuid boss_paletress::boss_paletressAI::MemoryGUID
Referenced by DoAction(), JustSummoned(), Reset(), and UpdateAI().
pInstance
InstanceScript* boss_paletress::boss_paletressAI::pInstance
Referenced by boss_paletressAI(), DamageTaken(), JustEngagedWith(), JustSummoned(), and Reset().
summoned
bool boss_paletress::boss_paletressAI::summoned
Referenced by Reset(), and UpdateAI().