AzerothCore: PlayerNameMapHolder Namespace Reference
PlayerNameMapHolder Namespace Reference
Typedefs
typedef std::unordered_map< std::string, Player * > MapType
Functions
void Insert (Player *p)
void Remove (Player *p)
void RemoveByName (std::string const &name)
Player * Find (std::string const &name)
Variables
static MapType PlayerNameMap
Typedef Documentation
MapType
typedef std::unordered_map<std::string, Player*> PlayerNameMapHolder::MapType
Function Documentation
Find()
Player * PlayerNameMapHolder::Find (std::string const & name)
    {
        std::string charName(name);
        if (!normalizePlayerName(charName))
            return nullptr;
        auto itr = PlayerNameMap.find(charName);
        return (itr != PlayerNameMap.end()) ? itr->second : nullptr;
    }
References normalizePlayerName(), and PlayerNameMap.
Referenced by ObjectAccessor::FindPlayerByName().
Insert()
void PlayerNameMapHolder::Insert (Player * p)
    {
        PlayerNameMap[p->GetName()] = p;
    }
References WorldObject::GetName(), and PlayerNameMap.
Referenced by ObjectAccessor::AddObject(), and ObjectAccessor::UpdatePlayerNameMapReference().
Remove()
void PlayerNameMapHolder::Remove (Player * p)
    {
        PlayerNameMap.erase(p->GetName());
    }
References WorldObject::GetName(), and PlayerNameMap.
Referenced by ObjectAccessor::RemoveObject().
RemoveByName()
void PlayerNameMapHolder::RemoveByName (std::string const & name)
    {
        PlayerNameMap.erase(name);
    }
References PlayerNameMap, and RemoveByName().
Referenced by RemoveByName(), and ObjectAccessor::UpdatePlayerNameMapReference().
Variable Documentation
PlayerNameMap
MapType PlayerNameMapHolder::PlayerNameMap static
Referenced by Find(), Insert(), Remove(), and RemoveByName().