AzerothCore: UtherBatteredHiltEvent Class Reference
UtherBatteredHiltEvent Class Reference
Public Member Functions
UtherBatteredHiltEvent (Creature &owner, uint8 eventId)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature & _owner
uint8 _eventId
Detailed Description
Constructor & Destructor Documentation
UtherBatteredHiltEvent()
UtherBatteredHiltEvent::UtherBatteredHiltEvent (Creature & owner, uint8 eventId) inline
: _owner(owner), _eventId(eventId) { }
Member Function Documentation
Execute()
bool UtherBatteredHiltEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        switch (_eventId)
        {
            case 1:
                _owner.UpdatePosition(5300.53f, 1987.80f, 707.70f, 3.89f, true);
                _owner.StopMovingOnCurrentPos();
                _owner.GetMotionMaster()->Clear();
                _owner.SetVisible(true);
                _owner.NearTeleportTo(5300.53f, 1987.80f, 707.70f, 3.89f);
                _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, 2), _owner.m_Events.CalculateTime(1000));
                break;
            case 2:
                _owner.AI()->Talk(SAY_BATTERED_HILT_HALT);
                break;
            case 3:
                _owner.CastSpell((Unit*)nullptr, SPELL_SUMMON_EVIL_QUEL, true);
                _owner.AI()->Talk(SAY_BATTERED_HILT_REALIZE);
                if (InstanceScript* instance = _owner.GetInstanceScript())
                    instance->SetData(DATA_BATTERED_HILT, 4);
                if (Creature* quel = _owner.FindNearestCreature(NPC_QUEL_DELAR, 50))
                {
                    quel->AI()->Talk(EMOTE_QUEL_SPAWN);
                }
                _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, 4), _owner.m_Events.CalculateTime(3500));
                break;
            case 4:
                _owner.SetWalk(false);
                _owner.GetMotionMaster()->MovePoint(0, 5337.53f, 1981.21f, 709.32f);
                _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, 5), _owner.m_Events.CalculateTime(6000));
                break;
            case 5:
                _owner.SetFacingTo(2.82f);
                _owner.SetStandState(UNIT_STAND_STATE_KNEEL);
                break;
            case 6:
                if (InstanceScript* instance = _owner.GetInstanceScript())
                    instance->SetData(DATA_BATTERED_HILT, 6);
                _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, 7), _owner.m_Events.CalculateTime(2000));
                break;
            case 7:
                if (InstanceScript* instance = _owner.GetInstanceScript())
                {
                    instance->SetData(DATA_BATTERED_HILT, 7);
                }
                if (Creature* quel = _owner.FindNearestCreature(NPC_QUEL_DELAR, 50))
                {
                    quel->AI()->Talk(EMOTE_QUEL_PREPARE);
                }
                _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, 8), _owner.m_Events.CalculateTime(4000));
                break;
            case 8:
                _owner.SetReactState(REACT_AGGRESSIVE);
                _owner.SetImmuneToAll(false);
                if (InstanceScript* instance = _owner.GetInstanceScript())
                    instance->SetData(DATA_BATTERED_HILT, 8);
                break;
            case 9:
                _owner.AI()->Talk(SAY_BATTERED_HILT_OUTRO1);
                _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, _eventId + 1), _owner.m_Events.CalculateTime(11000));
                break;
            case 10:
                _owner.AI()->Talk(SAY_BATTERED_HILT_OUTRO2);
                _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, _eventId + 1), _owner.m_Events.CalculateTime(7500));
                break;
            case 11:
                _owner.AI()->Talk(SAY_BATTERED_HILT_OUTRO3);
                _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, _eventId + 1), _owner.m_Events.CalculateTime(8000));
                break;
            case 12:
                _owner.AI()->Talk(SAY_BATTERED_HILT_OUTRO4);
                _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, _eventId + 1), _owner.m_Events.CalculateTime(5000));
                break;
            case 13:
                _owner.CastSpell((Unit*)nullptr, 73036, true);
                _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, _eventId + 1), _owner.m_Events.CalculateTime(3000));
                break;
            case 14:
                {
                    Position homePos = _owner.GetHomePosition();
                    _owner.SetReactState(REACT_PASSIVE);
                    _owner.SetImmuneToAll(true);
                    _owner.SetVisible(false);
                    _owner.UpdatePosition(homePos.GetPositionX(), homePos.GetPositionY(), homePos.GetPositionZ(), homePos.GetOrientation(), true);
                    _owner.StopMovingOnCurrentPos();
                    _owner.GetMotionMaster()->Clear();
                    if (InstanceScript* instance = _owner.GetInstanceScript())
                        instance->SetData(DATA_BATTERED_HILT, 9);
                }
                break;
        }
        return true;
    }
References _eventId, _owner, EventProcessor::AddEvent(), Creature::AI(), EventProcessor::CalculateTime(), Unit::CastSpell(), MotionMaster::Clear(), DATA_BATTERED_HILT, EMOTE_QUEL_PREPARE, EMOTE_QUEL_SPAWN, WorldObject::FindNearestCreature(), Creature::GetHomePosition(), WorldObject::GetInstanceScript(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), homePos, Unit::m_Events, MotionMaster::MovePoint(), Unit::NearTeleportTo(), NPC_QUEL_DELAR, REACT_AGGRESSIVE, REACT_PASSIVE, SAY_BATTERED_HILT_HALT, SAY_BATTERED_HILT_OUTRO1, SAY_BATTERED_HILT_OUTRO2, SAY_BATTERED_HILT_OUTRO3, SAY_BATTERED_HILT_OUTRO4, SAY_BATTERED_HILT_REALIZE, Unit::SetFacingTo(), Unit::SetImmuneToAll(), Creature::SetReactState(), Unit::SetStandState(), Unit::SetVisible(), Creature::SetWalk(), SPELL_SUMMON_EVIL_QUEL, Unit::StopMovingOnCurrentPos(), CreatureAI::Talk(), UNIT_STAND_STATE_KNEEL, and Unit::UpdatePosition().
Member Data Documentation
_eventId
uint8 UtherBatteredHiltEvent::_eventId private
Referenced by Execute().
_owner
Creature& UtherBatteredHiltEvent::_owner private
Referenced by Execute().