AzeorthCore: instance_arcatraz::instance_arcatraz_InstanceMapScript Struct Reference
instance_arcatraz::instance_arcatraz_InstanceMapScript Struct Reference
Public Member Functions
instance_arcatraz_InstanceMapScript (Map *map)
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32) const override
ObjectGuid GetGuidData (uint32 data) const override
bool SetBossState (uint32 type, EncounterState state) override
std::string GetSaveData () override
void Load (char const *str) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
ObjectGuid DalliahGUID
ObjectGuid SoccothratesGUID
ObjectGuid StasisPodGUIDs [5]
ObjectGuid MellicharGUID
ObjectGuid WardensShieldGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Constructor & Destructor Documentation
instance_arcatraz_InstanceMapScript()
instance_arcatraz::instance_arcatraz_InstanceMapScript::instance_arcatraz_InstanceMapScript (Map * map) inline
                                                      : InstanceScript(map)
        {
            SetBossNumber(MAX_ENCOUTER);
            LoadDoorData(doorData);
        }
References doorData, InstanceScript::LoadDoorData(), MAX_ENCOUTER, and InstanceScript::SetBossNumber().
Member Function Documentation
GetData()
uint32 instance_arcatraz::instance_arcatraz_InstanceMapScript::GetData (uint32) const inline override virtual
Reimplemented from ZoneScript.
        {
            return 0;
        }
GetGuidData()
ObjectGuid instance_arcatraz::instance_arcatraz_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (data)
            {
                case DATA_DALLIAH:
                    return DalliahGUID;
                case DATA_SOCCOTHRATES:
                    return SoccothratesGUID;
                case DATA_WARDENS_SHIELD:
                    return WardensShieldGUID;
            }
            return ObjectGuid::Empty;
        }
References DalliahGUID, DATA_DALLIAH, DATA_SOCCOTHRATES, DATA_WARDENS_SHIELD, ObjectGuid::Empty, SoccothratesGUID, and WardensShieldGUID.
GetSaveData()
std::string instance_arcatraz::instance_arcatraz_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
        {
            OUT_SAVE_INST_DATA;
            std::ostringstream saveStream;
            saveStream << "A Z " << GetBossSaveData();
            OUT_SAVE_INST_DATA_COMPLETE;
            return saveStream.str();
        }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Load()
void instance_arcatraz::instance_arcatraz_InstanceMapScript::Load (char const * str) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!str)
            {
                OUT_LOAD_INST_DATA_FAIL;
                return;
            }
            OUT_LOAD_INST_DATA(str);
            char dataHead1, dataHead2;
            std::istringstream loadStream(str);
            loadStream >> dataHead1 >> dataHead2;
            if (dataHead1 == 'A' && dataHead2 == 'Z')
            {
                for (uint32 i = 0; i < MAX_ENCOUTER; ++i)
                {
                    uint32 tmpState;
                    loadStream >> tmpState;
                    if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                        tmpState = NOT_STARTED;
                    SetBossState(i, EncounterState(tmpState));
                }
            }
            else
                OUT_LOAD_INST_DATA_FAIL;
            OUT_LOAD_INST_DATA_COMPLETE;
        }
References IN_PROGRESS, MAX_ENCOUTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_arcatraz::instance_arcatraz_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_DALLIAH:
                    DalliahGUID = creature->GetGUID();
                    break;
                case NPC_SOCCOTHRATES:
                    SoccothratesGUID = creature->GetGUID();
                    break;
                case NPC_MELLICHAR:
                    MellicharGUID = creature->GetGUID();
                    break;
            }
        }
References DalliahGUID, Object::GetEntry(), Object::GetGUID(), MellicharGUID, NPC_DALLIAH, NPC_MELLICHAR, NPC_SOCCOTHRATES, and SoccothratesGUID.
OnGameObjectCreate()
void instance_arcatraz::instance_arcatraz_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_CONTAINMENT_CORE_SECURITY_FIELD_ALPHA:
                case GO_CONTAINMENT_CORE_SECURITY_FIELD_BETA:
                    AddDoor(go, true);
                    break;
                case GO_STASIS_POD_ALPHA:
                    StasisPodGUIDs[0] = go->GetGUID();
                    break;
                case GO_STASIS_POD_BETA:
                    StasisPodGUIDs[1] = go->GetGUID();
                    break;
                case GO_STASIS_POD_DELTA:
                    StasisPodGUIDs[2] = go->GetGUID();
                    break;
                case GO_STASIS_POD_GAMMA:
                    StasisPodGUIDs[3] = go->GetGUID();
                    break;
                case GO_STASIS_POD_OMEGA:
                    StasisPodGUIDs[4] = go->GetGUID();
                    break;
                case GO_WARDENS_SHIELD:
                    WardensShieldGUID = go->GetGUID();
                    break;
                default:
                    break;
            }
        }
References InstanceScript::AddDoor(), Object::GetEntry(), Object::GetGUID(), GO_CONTAINMENT_CORE_SECURITY_FIELD_ALPHA, GO_CONTAINMENT_CORE_SECURITY_FIELD_BETA, GO_STASIS_POD_ALPHA, GO_STASIS_POD_BETA, GO_STASIS_POD_DELTA, GO_STASIS_POD_GAMMA, GO_STASIS_POD_OMEGA, GO_WARDENS_SHIELD, StasisPodGUIDs, and WardensShieldGUID.
OnGameObjectRemove()
void instance_arcatraz::instance_arcatraz_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_CONTAINMENT_CORE_SECURITY_FIELD_ALPHA:
                case GO_CONTAINMENT_CORE_SECURITY_FIELD_BETA:
                    AddDoor(go, false);
                    break;
                default:
                    break;
            }
        }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_CONTAINMENT_CORE_SECURITY_FIELD_ALPHA, and GO_CONTAINMENT_CORE_SECURITY_FIELD_BETA.
SetBossState()
bool instance_arcatraz::instance_arcatraz_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            if (type == DATA_WARDEN_MELLICHAR && state == NOT_STARTED)
            {
                SetData(DATA_WARDEN_1, NOT_STARTED);
                SetData(DATA_WARDEN_2, NOT_STARTED);
                SetData(DATA_WARDEN_3, NOT_STARTED);
                SetData(DATA_WARDEN_4, NOT_STARTED);
                SetData(DATA_WARDEN_5, NOT_STARTED);
                HandleGameObject(WardensShieldGUID, true);
            }
            return true;
        }
References DATA_WARDEN_1, DATA_WARDEN_2, DATA_WARDEN_3, DATA_WARDEN_4, DATA_WARDEN_5, DATA_WARDEN_MELLICHAR, InstanceScript::HandleGameObject(), NOT_STARTED, InstanceScript::SetBossState(), SetData(), and WardensShieldGUID.
Referenced by Load().
SetData()
void instance_arcatraz::instance_arcatraz_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_WARDEN_1:
                case DATA_WARDEN_2:
                case DATA_WARDEN_3:
                case DATA_WARDEN_4:
                case DATA_WARDEN_5:
                    if (data < FAIL)
                        HandleGameObject(StasisPodGUIDs[type - DATA_WARDEN_1], data == IN_PROGRESS);
                    if (Creature* warden = instance->GetCreature(MellicharGUID))
                        warden->AI()->SetData(type, data);
                    break;
            }
        }
References DATA_WARDEN_1, DATA_WARDEN_2, DATA_WARDEN_3, DATA_WARDEN_4, DATA_WARDEN_5, FAIL, Map::GetCreature(), InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, MellicharGUID, and StasisPodGUIDs.
Referenced by SetBossState().
Member Data Documentation
DalliahGUID
ObjectGuid instance_arcatraz::instance_arcatraz_InstanceMapScript::DalliahGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
MellicharGUID
ObjectGuid instance_arcatraz::instance_arcatraz_InstanceMapScript::MellicharGUID protected
Referenced by OnCreatureCreate(), and SetData().
SoccothratesGUID
ObjectGuid instance_arcatraz::instance_arcatraz_InstanceMapScript::SoccothratesGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
StasisPodGUIDs
ObjectGuid instance_arcatraz::instance_arcatraz_InstanceMapScript::StasisPodGUIDs[5] protected
Referenced by OnGameObjectCreate(), and SetData().
WardensShieldGUID
ObjectGuid instance_arcatraz::instance_arcatraz_InstanceMapScript::WardensShieldGUID protected
Referenced by GetGuidData(), OnGameObjectCreate(), and SetBossState().