AzerothCore: Acore::GameObjectListSearcher< Check > Struct Template Reference
Acore::GameObjectListSearcher< Check > Struct Template Reference
#include "GridNotifiers.h"
Public Member Functions
template<typename Container >
GameObjectListSearcher (WorldObject const *searcher, Container &container, Check &check)
void Visit (GameObjectMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_phaseMask
Check & i_check
Additional Inherited Members
Protected Member Functions inherited from Acore::ContainerInserter< GameObject * >
ContainerInserter (T &ref_)
void Insert (GameObject * type)
Detailed Description
template<class Check>
struct Acore::GameObjectListSearcher< Check >
Constructor & Destructor Documentation
GameObjectListSearcher()
template<class Check > template<typename Container > Acore::GameObjectListSearcher< Check >::GameObjectListSearcher (WorldObject const * searcher, Container & container, Check & check) inline
                : ContainerInserter<GameObject*>(container),
                  i_phaseMask(searcher->GetPhaseMask()), i_check(check) { }
Member Function Documentation
Visit() [1/2]
template<class Check > void Acore::GameObjectListSearcher< Check >::Visit (GameObjectMapType & m)
{
    for (GameObjectMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
        if (itr->GetSource()->InSamePhase(i_phaseMask))
            if (i_check(itr->GetSource()))
                Insert(itr->GetSource());
}
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and Acore::Insert().
Visit() [2/2]
template<class Check > template<class NOT_INTERESTED > void Acore::GameObjectListSearcher< Check >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
{}
Member Data Documentation
i_check
template<class Check > Check& Acore::GameObjectListSearcher< Check >::i_check
i_phaseMask
template<class Check > uint32 Acore::GameObjectListSearcher< Check >::i_phaseMask