AzerothCore: npc_halion_controller::npc_halion_controllerAI Struct Reference
npc_halion_controller::npc_halion_controllerAI Struct Reference
Public Member Functions
npc_halion_controllerAI (Creature *creature)
void Reset () override
void SetData (uint32 id, uint32 value) override
void DoAction (int32 action) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Member Functions
void UpdateCorporeality ()
Private Attributes
EventMap _events
InstanceScript * _instance
uint8 _corporeality
uint32 _materialDamage
uint32 _twilightDamage
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_halion_controllerAI()
npc_halion_controller::npc_halion_controllerAI::npc_halion_controllerAI (Creature * creature) inline
                                                    : NullCreatureAI(creature), _instance(creature->GetInstanceScript())
        {
        }
Member Function Documentation
DoAction()
void npc_halion_controller::npc_halion_controllerAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == ACTION_INTRO_HALION)
                _events.ScheduleEvent(EVENT_START_INTRO, 2s);
            else if (action == ACTION_CHECK_CORPOREALITY)
            {
                _materialDamage = 1;
                _twilightDamage = 1;
                _corporeality = 5;
                _events.ScheduleEvent(EVENT_CHECK_CORPOREALITY, 7s);
            }
            else if (action == ACTION_RESET_ENCOUNTER)
            {
                _events.Reset();
                _materialDamage = 1;
                _twilightDamage = 1;
                _corporeality = 5;
            }
        }
References _corporeality, _events, _materialDamage, _twilightDamage, ACTION_CHECK_CORPOREALITY, ACTION_INTRO_HALION, ACTION_RESET_ENCOUNTER, EVENT_CHECK_CORPOREALITY, EVENT_START_INTRO, EventMap::Reset(), and EventMap::ScheduleEvent().
Referenced by UpdateCorporeality().
Reset()
void npc_halion_controller::npc_halion_controllerAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            _events.Reset();
        }
References _events, and EventMap::Reset().
SetData()
void npc_halion_controller::npc_halion_controllerAI::SetData (uint32 id, uint32 value) inline override virtual
Reimplemented from UnitAI.
        {
            if (_events.GetNextEventTime(EVENT_CHECK_CORPOREALITY) == 0)
                return;
            if (id == DATA_MATERIAL_DAMAGE_TAKEN)
                _materialDamage += value;
            else
                _twilightDamage += value;
        }
References _events, _materialDamage, _twilightDamage, DATA_MATERIAL_DAMAGE_TAKEN, EVENT_CHECK_CORPOREALITY, and EventMap::GetNextEventTime().
UpdateAI()
void npc_halion_controller::npc_halion_controllerAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
        {
            _events.Update(diff);
            switch (_events.ExecuteEvent())
            {
                // Intro
                case EVENT_START_INTRO:
                    me->CastSpell(me, SPELL_COSMETIC_FIRE_PILLAR, false);
                    _events.ScheduleEvent(EVENT_INTRO_PROGRESS_1, 5s);
                    break;
                case EVENT_INTRO_PROGRESS_1:
                    _instance->SetBossState(DATA_HALION_INTRO1, NOT_STARTED);
                    _instance->SetBossState(DATA_HALION_INTRO1, DONE);
                    _events.ScheduleEvent(EVENT_INTRO_PROGRESS_2, 5s);
                    break;
                case EVENT_INTRO_PROGRESS_2:
                    _instance->SetBossState(DATA_HALION_INTRO2, NOT_STARTED);
                    _instance->SetBossState(DATA_HALION_INTRO2, DONE);
                    _events.ScheduleEvent(EVENT_INTRO_PROGRESS_3, 4s);
                    break;
                case EVENT_INTRO_PROGRESS_3:
                    _instance->SetBossState(DATA_HALION_INTRO_DONE, NOT_STARTED);
                    _instance->SetBossState(DATA_HALION_INTRO_DONE, DONE);
                    me->CastSpell(me, SPELL_FIERY_EXPLOSION, false);
                    _events.ScheduleEvent(EVENT_INTRO_PROGRESS_4, 500ms);
                    break;
                case EVENT_INTRO_PROGRESS_4:
                    if (Creature* halion = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION)))
                    {
                        halion->SetVisible(true);
                        halion->SetReactState(REACT_AGGRESSIVE);
                        halion->AI()->Talk(SAY_INTRO);
                    }
                    break;
                case EVENT_TWILIGHT_MENDING:
                    me->CastSpell((Unit*)nullptr, SPELL_TWILIGHT_MENDING, true);
                    break;
                case EVENT_CHECK_CORPOREALITY:
                    UpdateCorporeality();
                    _events.ScheduleEvent(EVENT_CHECK_CORPOREALITY, 10s);
                    break;
            }
        }
References _events, _instance, Unit::CastSpell(), DATA_HALION_INTRO1, DATA_HALION_INTRO2, DATA_HALION_INTRO_DONE, DONE, EVENT_CHECK_CORPOREALITY, EVENT_INTRO_PROGRESS_1, EVENT_INTRO_PROGRESS_2, EVENT_INTRO_PROGRESS_3, EVENT_INTRO_PROGRESS_4, EVENT_START_INTRO, EVENT_TWILIGHT_MENDING, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), CreatureAI::me, NOT_STARTED, NPC_HALION, REACT_AGGRESSIVE, SAY_INTRO, EventMap::ScheduleEvent(), InstanceScript::SetBossState(), SPELL_COSMETIC_FIRE_PILLAR, SPELL_FIERY_EXPLOSION, SPELL_TWILIGHT_MENDING, EventMap::Update(), and UpdateCorporeality().
UpdateCorporeality()
void npc_halion_controller::npc_halion_controllerAI::UpdateCorporeality () inline private
        {
            if (!_instance->IsEncounterInProgress())
            {
                DoAction(ACTION_RESET_ENCOUNTER);
                return;
            }
            uint8 oldValue = _corporeality;
            float damageRatio = float(_materialDamage) / float(_twilightDamage);
            if (_twilightDamage == 1 || _materialDamage == 1)
                _events.ScheduleEvent(EVENT_TWILIGHT_MENDING, 4s);
            _twilightDamage = 1;
            _materialDamage = 1;
            CorporealityEvent action = CORPOREALITY_NONE;
            if (damageRatio < 0.98f)
                action = CORPOREALITY_INCREASE;
            else if (1.02f < damageRatio)
                action = CORPOREALITY_DECREASE;
            else
                return;
            switch (action)
            {
                case CORPOREALITY_INCREASE:
                    {
                        if (_corporeality == (MAX_CORPOREALITY_STATE - 1))
                            return;
                        ++_corporeality;
                        break;
                    }
                case CORPOREALITY_DECREASE:
                    {
                        if (_corporeality == 0)
                            return;
                        --_corporeality;
                        break;
                    }
                default:
                    break;
            }
            _instance->DoUpdateWorldState(WORLDSTATE_CORPOREALITY_MATERIAL, _corporeality * 10);
            _instance->DoUpdateWorldState(WORLDSTATE_CORPOREALITY_TWILIGHT, 100 - _corporeality * 10);
            if (Creature* twilightHalion = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_TWILIGHT_HALION)))
            {
                twilightHalion->RemoveAurasDueToSpell(_corporealityReference[MAX_CORPOREALITY_STATE - 1 - oldValue]);
                twilightHalion->CastSpell(twilightHalion, _corporealityReference[MAX_CORPOREALITY_STATE - 1 - _corporeality], true);
                twilightHalion->AI()->Talk(oldValue < _corporeality ? EMOTE_CORPOREALITY_TOT : EMOTE_CORPOREALITY_TIT);
            }
            if (Creature* halion = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION)))
            {
                halion->RemoveAurasDueToSpell(_corporealityReference[oldValue]);
                halion->CastSpell(halion, _corporealityReference[_corporeality], true);
                halion->AI()->Talk(oldValue > _corporeality ? EMOTE_CORPOREALITY_POT : EMOTE_CORPOREALITY_PIP);
            }
        }
References _corporeality, _corporealityReference, _events, _instance, _materialDamage, _twilightDamage, ACTION_RESET_ENCOUNTER, CORPOREALITY_DECREASE, CORPOREALITY_INCREASE, CORPOREALITY_NONE, DoAction(), InstanceScript::DoUpdateWorldState(), EMOTE_CORPOREALITY_PIP, EMOTE_CORPOREALITY_POT, EMOTE_CORPOREALITY_TIT, EMOTE_CORPOREALITY_TOT, EVENT_TWILIGHT_MENDING, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), InstanceScript::IsEncounterInProgress(), MAX_CORPOREALITY_STATE, CreatureAI::me, NPC_HALION, NPC_TWILIGHT_HALION, EventMap::ScheduleEvent(), WORLDSTATE_CORPOREALITY_MATERIAL, and WORLDSTATE_CORPOREALITY_TWILIGHT.
Referenced by UpdateAI().
Member Data Documentation
_corporeality
uint8 npc_halion_controller::npc_halion_controllerAI::_corporeality private
Referenced by DoAction(), and UpdateCorporeality().
_events
EventMap npc_halion_controller::npc_halion_controllerAI::_events private
Referenced by DoAction(), Reset(), SetData(), UpdateAI(), and UpdateCorporeality().
_instance
InstanceScript* npc_halion_controller::npc_halion_controllerAI::_instance private
Referenced by UpdateAI(), and UpdateCorporeality().
_materialDamage
uint32 npc_halion_controller::npc_halion_controllerAI::_materialDamage private
Referenced by DoAction(), SetData(), and UpdateCorporeality().
_twilightDamage
uint32 npc_halion_controller::npc_halion_controllerAI::_twilightDamage private
Referenced by DoAction(), SetData(), and UpdateCorporeality().