AzeorthCore: instance_black_temple::instance_black_temple_InstanceMapScript Struct Reference
instance_black_temple::instance_black_temple_InstanceMapScript Struct Reference
Public Member Functions
instance_black_temple_InstanceMapScript (Map *map)
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetGuidData (uint32 type) const override
bool SetBossState (uint32 type, EncounterState state) override
std::string GetSaveData () override
void Load (char const *str) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
ObjectGuid ShadeOfAkamaGUID
ObjectGuid AkamaShadeGUID
ObjectGuid TeronGorefiendGUID
ObjectGuid ReliquaryGUID
GuidList ashtongueGUIDs
ObjectGuid GathiosTheShattererGUID
ObjectGuid HighNethermancerZerevorGUID
ObjectGuid LadyMalandeGUID
ObjectGuid VerasDarkshadowGUID
ObjectGuid IllidariCouncilGUID
ObjectGuid AkamaGUID
ObjectGuid IllidanStormrageGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Constructor & Destructor Documentation
instance_black_temple_InstanceMapScript()
instance_black_temple::instance_black_temple_InstanceMapScript::instance_black_temple_InstanceMapScript (Map * map) inline
                                                          : InstanceScript(map)
        {
            SetBossNumber(MAX_ENCOUNTERS);
            LoadDoorData(doorData);
            LoadBossBoundaries(boundaries);
            ashtongueGUIDs.clear();
        }
References ashtongueGUIDs, boundaries, doorData, InstanceScript::LoadBossBoundaries(), InstanceScript::LoadDoorData(), MAX_ENCOUNTERS, and InstanceScript::SetBossNumber().
Member Function Documentation
GetGuidData()
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case NPC_SHADE_OF_AKAMA:
                    return ShadeOfAkamaGUID;
                case NPC_AKAMA_SHADE:
                    return AkamaShadeGUID;
                case NPC_GATHIOS_THE_SHATTERER:
                    return GathiosTheShattererGUID;
                case NPC_HIGH_NETHERMANCER_ZEREVOR:
                    return HighNethermancerZerevorGUID;
                case NPC_LADY_MALANDE:
                    return LadyMalandeGUID;
                case NPC_VERAS_DARKSHADOW:
                    return VerasDarkshadowGUID;
                case NPC_ILLIDARI_COUNCIL:
                    return IllidariCouncilGUID;
                case NPC_AKAMA:
                    return AkamaGUID;
                case NPC_ILLIDAN_STORMRAGE:
                    return IllidanStormrageGUID;
            }
            return ObjectGuid::Empty;
        }
References AkamaGUID, AkamaShadeGUID, ObjectGuid::Empty, GathiosTheShattererGUID, HighNethermancerZerevorGUID, IllidanStormrageGUID, IllidariCouncilGUID, LadyMalandeGUID, NPC_AKAMA, NPC_AKAMA_SHADE, NPC_GATHIOS_THE_SHATTERER, NPC_HIGH_NETHERMANCER_ZEREVOR, NPC_ILLIDAN_STORMRAGE, NPC_ILLIDARI_COUNCIL, NPC_LADY_MALANDE, NPC_SHADE_OF_AKAMA, NPC_VERAS_DARKSHADOW, ShadeOfAkamaGUID, and VerasDarkshadowGUID.
GetSaveData()
std::string instance_black_temple::instance_black_temple_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
        {
            OUT_SAVE_INST_DATA;
            std::ostringstream saveStream;
            saveStream << "B T " << GetBossSaveData();
            OUT_SAVE_INST_DATA_COMPLETE;
            return saveStream.str();
        }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Load()
void instance_black_temple::instance_black_temple_InstanceMapScript::Load (char const * str) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!str)
            {
                OUT_LOAD_INST_DATA_FAIL;
                return;
            }
            OUT_LOAD_INST_DATA(str);
            char dataHead1, dataHead2;
            std::istringstream loadStream(str);
            loadStream >> dataHead1 >> dataHead2;
            if (dataHead1 == 'B' && dataHead2 == 'T')
            {
                for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                {
                    uint32 tmpState;
                    loadStream >> tmpState;
                    if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                        tmpState = NOT_STARTED;
                    SetBossState(i, EncounterState(tmpState));
                }
            }
            else
                OUT_LOAD_INST_DATA_FAIL;
            OUT_LOAD_INST_DATA_COMPLETE;
        }
References IN_PROGRESS, MAX_ENCOUNTERS, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_black_temple::instance_black_temple_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_SHADE_OF_AKAMA:
                    ShadeOfAkamaGUID = creature->GetGUID();
                    break;
                case NPC_AKAMA_SHADE:
                    AkamaShadeGUID = creature->GetGUID();
                    break;
                case NPC_TERON_GOREFIEND:
                    TeronGorefiendGUID = creature->GetGUID();
                    break;
                case NPC_RELIQUARY_OF_THE_LOST:
                    ReliquaryGUID = creature->GetGUID();
                    break;
                case NPC_GATHIOS_THE_SHATTERER:
                    GathiosTheShattererGUID = creature->GetGUID();
                    break;
                case NPC_HIGH_NETHERMANCER_ZEREVOR:
                    HighNethermancerZerevorGUID = creature->GetGUID();
                    break;
                case NPC_LADY_MALANDE:
                    LadyMalandeGUID = creature->GetGUID();
                    break;
                case NPC_VERAS_DARKSHADOW:
                    VerasDarkshadowGUID = creature->GetGUID();
                    break;
                case NPC_ILLIDARI_COUNCIL:
                    IllidariCouncilGUID = creature->GetGUID();
                    break;
                case NPC_AKAMA:
                    AkamaGUID = creature->GetGUID();
                    break;
                case NPC_ILLIDAN_STORMRAGE:
                    IllidanStormrageGUID = creature->GetGUID();
                    break;
                case NPC_VENGEFUL_SPIRIT:
                case NPC_SHADOWY_CONSTRUCT:
                    if (Creature* teron = instance->GetCreature(TeronGorefiendGUID))
                        teron->AI()->JustSummoned(creature);
                    break;
                case NPC_ENSLAVED_SOUL:
                    if (Creature* reliquary = instance->GetCreature(ReliquaryGUID))
                        reliquary->AI()->JustSummoned(creature);
                    break;
                case NPC_PARASITIC_SHADOWFIEND:
                case NPC_BLADE_OF_AZZINOTH:
                case NPC_FLAME_OF_AZZINOTH:
                    if (Creature* illidan = instance->GetCreature(IllidanStormrageGUID))
                        illidan->AI()->JustSummoned(creature);
                    break;
                case NPC_ANGERED_SOUL_FRAGMENT:
                case NPC_HUNGERING_SOUL_FRAGMENT:
                case NPC_SUFFERING_SOUL_FRAGMENT:
                    creature->SetCorpseDelay(5);
                    break;
            }
            if (creature->GetName().find("Ashtongue") != std::string::npos || creature->GetEntry() == NPC_STORM_FURY)
            {
                ashtongueGUIDs.push_back(creature->GetGUID());
                if (GetBossState(DATA_SHADE_OF_AKAMA) == DONE)
                    creature->SetFaction(FACTION_ASHTONGUE_DEATHSWORN);
            }
        }
References AkamaGUID, AkamaShadeGUID, ashtongueGUIDs, DATA_SHADE_OF_AKAMA, DONE, FACTION_ASHTONGUE_DEATHSWORN, GathiosTheShattererGUID, InstanceScript::GetBossState(), Map::GetCreature(), Object::GetEntry(), Object::GetGUID(), WorldObject::GetName(), HighNethermancerZerevorGUID, IllidanStormrageGUID, IllidariCouncilGUID, InstanceScript::instance, LadyMalandeGUID, NPC_AKAMA, NPC_AKAMA_SHADE, NPC_ANGERED_SOUL_FRAGMENT, NPC_BLADE_OF_AZZINOTH, NPC_ENSLAVED_SOUL, NPC_FLAME_OF_AZZINOTH, NPC_GATHIOS_THE_SHATTERER, NPC_HIGH_NETHERMANCER_ZEREVOR, NPC_HUNGERING_SOUL_FRAGMENT, NPC_ILLIDAN_STORMRAGE, NPC_ILLIDARI_COUNCIL, NPC_LADY_MALANDE, NPC_PARASITIC_SHADOWFIEND, NPC_RELIQUARY_OF_THE_LOST, NPC_SHADE_OF_AKAMA, NPC_SHADOWY_CONSTRUCT, NPC_STORM_FURY, NPC_SUFFERING_SOUL_FRAGMENT, NPC_TERON_GOREFIEND, NPC_VENGEFUL_SPIRIT, NPC_VERAS_DARKSHADOW, ReliquaryGUID, Creature::SetCorpseDelay(), Unit::SetFaction(), ShadeOfAkamaGUID, TeronGorefiendGUID, and VerasDarkshadowGUID.
OnGameObjectCreate()
void instance_black_temple::instance_black_temple_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_NAJENTUS_GATE:
                case GO_SUPREMUS_GATE:
                case GO_SHADE_OF_AKAMA_DOOR:
                case GO_TERON_DOOR_1:
                case GO_TERON_DOOR_2:
                case GO_GURTOGG_DOOR:
                case GO_TEMPLE_DOOR:
                case GO_MOTHER_SHAHRAZ_DOOR:
                case GO_COUNCIL_DOOR_1:
                case GO_COUNCIL_DOOR_2:
                case GO_ILLIDAN_GATE:
                case GO_ILLIDAN_DOOR_R:
                case GO_ILLIDAN_DOOR_L:
                    AddDoor(go, true);
                    break;
            }
        }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_COUNCIL_DOOR_1, GO_COUNCIL_DOOR_2, GO_GURTOGG_DOOR, GO_ILLIDAN_DOOR_L, GO_ILLIDAN_DOOR_R, GO_ILLIDAN_GATE, GO_MOTHER_SHAHRAZ_DOOR, GO_NAJENTUS_GATE, GO_SHADE_OF_AKAMA_DOOR, GO_SUPREMUS_GATE, GO_TEMPLE_DOOR, GO_TERON_DOOR_1, and GO_TERON_DOOR_2.
OnGameObjectRemove()
void instance_black_temple::instance_black_temple_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_NAJENTUS_GATE:
                case GO_SUPREMUS_GATE:
                case GO_SHADE_OF_AKAMA_DOOR:
                case GO_TERON_DOOR_1:
                case GO_TERON_DOOR_2:
                case GO_GURTOGG_DOOR:
                case GO_TEMPLE_DOOR:
                case GO_MOTHER_SHAHRAZ_DOOR:
                case GO_COUNCIL_DOOR_1:
                case GO_COUNCIL_DOOR_2:
                case GO_ILLIDAN_GATE:
                case GO_ILLIDAN_DOOR_R:
                case GO_ILLIDAN_DOOR_L:
                    AddDoor(go, false);
                    break;
            }
        }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_COUNCIL_DOOR_1, GO_COUNCIL_DOOR_2, GO_GURTOGG_DOOR, GO_ILLIDAN_DOOR_L, GO_ILLIDAN_DOOR_R, GO_ILLIDAN_GATE, GO_MOTHER_SHAHRAZ_DOOR, GO_NAJENTUS_GATE, GO_SHADE_OF_AKAMA_DOOR, GO_SUPREMUS_GATE, GO_TEMPLE_DOOR, GO_TERON_DOOR_1, and GO_TERON_DOOR_2.
SetBossState()
bool instance_black_temple::instance_black_temple_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            if (type == DATA_SHADE_OF_AKAMA && state == DONE)
            {
                for (ObjectGuid const& guid : ashtongueGUIDs)
                    if (Creature* ashtongue = instance->GetCreature(guid))
                        ashtongue->SetFaction(FACTION_ASHTONGUE_DEATHSWORN);
            }
            else if (type == DATA_ILLIDARI_COUNCIL && state == DONE)
            {
                if (Creature* akama = instance->GetCreature(AkamaGUID))
                    akama->SetVisible(true);
            }
            return true;
        }
References AkamaGUID, ashtongueGUIDs, DATA_ILLIDARI_COUNCIL, DATA_SHADE_OF_AKAMA, DONE, FACTION_ASHTONGUE_DEATHSWORN, Map::GetCreature(), InstanceScript::instance, and InstanceScript::SetBossState().
Referenced by Load().
Member Data Documentation
AkamaGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::AkamaGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), and SetBossState().
AkamaShadeGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::AkamaShadeGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
ashtongueGUIDs
GuidList instance_black_temple::instance_black_temple_InstanceMapScript::ashtongueGUIDs protected
Referenced by instance_black_temple_InstanceMapScript(), OnCreatureCreate(), and SetBossState().
GathiosTheShattererGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::GathiosTheShattererGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
HighNethermancerZerevorGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::HighNethermancerZerevorGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
IllidanStormrageGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::IllidanStormrageGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
IllidariCouncilGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::IllidariCouncilGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
LadyMalandeGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::LadyMalandeGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
ReliquaryGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::ReliquaryGUID protected
Referenced by OnCreatureCreate().
ShadeOfAkamaGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::ShadeOfAkamaGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
TeronGorefiendGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::TeronGorefiendGUID protected
Referenced by OnCreatureCreate().
VerasDarkshadowGUID
ObjectGuid instance_black_temple::instance_black_temple_InstanceMapScript::VerasDarkshadowGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().