AzerothCore: Reference< TO, FROM > Class Template Reference
Reference< TO, FROM > Class Template Reference abstract
#include "Reference.h"
Public Member Functions
Reference ()
virtual ~Reference ()=default
void link (TO *toObj, FROM *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< TO, FROM > * next ()
Reference< TO, FROM > const * next () const
Reference< TO, FROM > * prev ()
Reference< TO, FROM > const * prev () const
Reference< TO, FROM > * nocheck_next ()
Reference< TO, FROM > const * nocheck_next () const
Reference< TO, FROM > * nocheck_prev ()
Reference< TO, FROM > const * nocheck_prev () const
TO * operator-> () const
TO * getTarget () const
FROM * GetSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()=default
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Protected Member Functions
virtual void targetObjectBuildLink ()=0
virtual void targetObjectDestroyLink ()=0
virtual void sourceObjectDestroyLink ()=0
Private Attributes
TO * iRefTo
FROM * iRefFrom
Detailed Description
template<class TO, class FROM>
class Reference< TO, FROM >
Constructor & Destructor Documentation
Reference()
template<class TO , class FROM > Reference< TO, FROM >::Reference () inline
{ iRefTo = nullptr; iRefFrom = nullptr; }
References Reference< TO, FROM >::iRefFrom, and Reference< TO, FROM >::iRefTo.
~Reference()
template<class TO , class FROM > virtual Reference< TO, FROM >::~Reference () virtual default
Member Function Documentation
GetSource()
template<class TO , class FROM > FROM * Reference< TO, FROM >::GetSource () const inline
{ return iRefFrom; }
References Reference< TO, FROM >::iRefFrom.
Referenced by Group::CanJoinBattlegroundQueue(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::ChromieWhisper(), HostileRefMgr::deleteReference(), HostileRefMgr::deleteReferences(), HostileRefMgr::deleteReferencesForFaction(), HostileRefMgr::deleteReferencesOutOfRange(), npc_arthas::npc_arthasAI::DoAction(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::GetCreatureEntry(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetCreatureEntry(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetGameObjectEntry(), debug_commandscript::HandleDebugHostileRefListCommand(), npc_pet_mage_mirror_image::InitializeAI(), boss_apothecary_hummel::boss_apothecary_hummelAI::JustDied(), npc_coren_direbrew::JustDied(), boss_headless_horseman::JustDied(), boss_ahune::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnCreatureCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), HostileRefMgr::setOnlineOfflineState(), Unit::SetPhaseMask(), HostileRefMgr::threatAssist(), Map::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), npc_arthas::npc_arthasAI::UpdateAI(), and HostileRefMgr::UpdateVisibility().
getTarget()
template<class TO , class FROM > TO * Reference< TO, FROM >::getTarget () const inline
{ return iRefTo; }
References Reference< TO, FROM >::iRefTo.
Referenced by InstanceMap::CannotEnter(), BattlegroundMap::CannotEnter(), Player::GetGroup(), ThreatMgr::getHostileTarget(), Player::GetOriginalGroup(), ChaseMovementGenerator< T >::GetTarget(), FollowMovementGenerator< T >::GetTarget(), and ThreatContainer::SelectNextVictim().
invalidate()
template<class TO , class FROM > void Reference< TO, FROM >::invalidate () inline
    {
        sourceObjectDestroyLink();
        delink();
        iRefTo = nullptr;
    }
References LinkedListElement::delink(), Reference< TO, FROM >::iRefTo, and Reference< TO, FROM >::sourceObjectDestroyLink().
isValid()
template<class TO , class FROM > bool Reference< TO, FROM >::isValid () const inline
    {
        return iRefTo != nullptr;
    }
References Reference< TO, FROM >::iRefTo.
Referenced by Group::CountTheRoll(), GridObject< T >::IsInGrid(), and Reference< TO, FROM >::link().
link()
template<class TO , class FROM > void Reference< TO, FROM >::link (TO * toObj, FROM * fromObj) inline
    {
        ASSERT(fromObj);                                // fromObj MUST not be nullptr
        if (isValid())
        {
            unlink();
        }
        if (toObj != nullptr)
        {
            iRefTo = toObj;
            iRefFrom = fromObj;
            targetObjectBuildLink();
        }
    }
References ASSERT, Reference< TO, FROM >::iRefFrom, Reference< TO, FROM >::iRefTo, Reference< TO, FROM >::isValid(), Reference< TO, FROM >::targetObjectBuildLink(), and Reference< TO, FROM >::unlink().
Referenced by GridObject< T >::AddToGrid(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::link(), Player::RemoveFromBattlegroundOrBattlefieldRaid(), Player::SetBattlegroundOrBattlefieldRaid(), Player::SetGroup(), Player::SetMap(), Player::SetOriginalGroup(), and TargetedMovementGeneratorBase::TargetedMovementGeneratorBase().
next() [1/2]
template<class TO , class FROM > Reference< TO, FROM > * Reference< TO, FROM >::next () inline
{ return ((Reference<TO, FROM>*) LinkedListElement::next()); }
References LinkedListElement::next().
Referenced by GroupReference::next(), and MapReference::next().
next() [2/2]
template<class TO , class FROM > Reference< TO, FROM > const * Reference< TO, FROM >::next () const inline
{ return ((Reference<TO, FROM> const*) LinkedListElement::next()); }
References LinkedListElement::next().
nocheck_next() [1/2]
template<class TO , class FROM > Reference< TO, FROM > * Reference< TO, FROM >::nocheck_next () inline
{ return ((Reference<TO, FROM>*) LinkedListElement::nocheck_next()); }
References LinkedListElement::nocheck_next().
nocheck_next() [2/2]
template<class TO , class FROM > Reference< TO, FROM > const * Reference< TO, FROM >::nocheck_next () const inline
{ return ((Reference<TO, FROM> const*) LinkedListElement::nocheck_next()); }
References LinkedListElement::nocheck_next().
nocheck_prev() [1/2]
template<class TO , class FROM > Reference< TO, FROM > * Reference< TO, FROM >::nocheck_prev () inline
{ return ((Reference<TO, FROM>*) LinkedListElement::nocheck_prev()); }
References LinkedListElement::nocheck_prev().
Referenced by MapReference::nocheck_prev(), and MapReference::nockeck_prev().
nocheck_prev() [2/2]
template<class TO , class FROM > Reference< TO, FROM > const * Reference< TO, FROM >::nocheck_prev () const inline
{ return ((Reference<TO, FROM> const*) LinkedListElement::nocheck_prev()); }
References LinkedListElement::nocheck_prev().
operator->()
template<class TO , class FROM > TO * Reference< TO, FROM >::operator-> () const inline
{ return iRefTo; }
References Reference< TO, FROM >::iRefTo.
prev() [1/2]
template<class TO , class FROM > Reference< TO, FROM > * Reference< TO, FROM >::prev () inline
{ return ((Reference<TO, FROM>*) LinkedListElement::prev()); }
References LinkedListElement::prev().
prev() [2/2]
template<class TO , class FROM > Reference< TO, FROM > const * Reference< TO, FROM >::prev () const inline
{ return ((Reference<TO, FROM> const*) LinkedListElement::prev()); }
References LinkedListElement::prev().
sourceObjectDestroyLink()
template<class TO , class FROM > virtual void Reference< TO, FROM >::sourceObjectDestroyLink () protected pure virtual
Implemented in HostileReference, GridReference< OBJECT >, GridReference< Corpse >, GridReference< Creature >, GridReference< DynamicObject >, GridReference< GameObject >, GridReference< Player >, GridReference< T >, GridReference< NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > >, GroupReference, LootValidatorRef, MapReference, and FollowerReference.
Referenced by Reference< TO, FROM >::invalidate().
targetObjectBuildLink()
template<class TO , class FROM > virtual void Reference< TO, FROM >::targetObjectBuildLink () protected pure virtual
Implemented in Roll, HostileReference, GridReference< OBJECT >, GridReference< Corpse >, GridReference< Creature >, GridReference< DynamicObject >, GridReference< GameObject >, GridReference< Player >, GridReference< T >, GridReference< NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > >, GroupReference, MapReference, and FollowerReference.
Referenced by Reference< TO, FROM >::link().
targetObjectDestroyLink()
template<class TO , class FROM > virtual void Reference< TO, FROM >::targetObjectDestroyLink () protected pure virtual
Implemented in HostileReference, GridReference< OBJECT >, GridReference< Corpse >, GridReference< Creature >, GridReference< DynamicObject >, GridReference< GameObject >, GridReference< Player >, GridReference< T >, GridReference< NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > >, GroupReference, LootValidatorRef, MapReference, and FollowerReference.
Referenced by Reference< TO, FROM >::unlink().
unlink()
template<class TO , class FROM > void Reference< TO, FROM >::unlink () inline
    {
        targetObjectDestroyLink();
        delink();
        iRefTo = nullptr;
        iRefFrom = nullptr;
    }
References LinkedListElement::delink(), Reference< TO, FROM >::iRefFrom, Reference< TO, FROM >::iRefTo, and Reference< TO, FROM >::targetObjectDestroyLink().
Referenced by Reference< TO, FROM >::link(), Player::RemoveFromBattlegroundOrBattlefieldRaid(), GridObject< T >::RemoveFromGrid(), Player::ResetMap(), Player::SetBattlegroundOrBattlefieldRaid(), Player::SetGroup(), and Player::SetOriginalGroup().
Member Data Documentation
iRefFrom
template<class TO , class FROM > FROM* Reference< TO, FROM >::iRefFrom private
Referenced by Reference< TO, FROM >::GetSource(), Reference< TO, FROM >::link(), Reference< TO, FROM >::Reference(), and Reference< TO, FROM >::unlink().
iRefTo
template<class TO , class FROM > TO* Reference< TO, FROM >::iRefTo private
Referenced by Reference< TO, FROM >::getTarget(), Reference< TO, FROM >::invalidate(), Reference< TO, FROM >::isValid(), Reference< TO, FROM >::link(), Reference< TO, FROM >::operator->(), Reference< TO, FROM >::Reference(), and Reference< TO, FROM >::unlink().