AzerothCore: NetworkThread< SocketType > Class Template Reference
NetworkThread< SocketType > Class Template Reference
#include "NetworkThread.h"
Public Member Functions
NetworkThread ()
virtual ~NetworkThread ()
void Stop ()
bool Start ()
void Wait ()
int32 GetConnectionCount () const
virtual void AddSocket (std::shared_ptr< SocketType > sock)
tcp::socket * GetSocketForAccept ()
Protected Member Functions
virtual void SocketAdded (std::shared_ptr< SocketType >)
virtual void SocketRemoved (std::shared_ptr< SocketType >)
void AddNewSockets ()
void Run ()
void Update ()
Private Types
typedef std::vector< std::shared_ptr< SocketType > > SocketContainer
Private Attributes
std::atomic< int32 > _connections
std::atomic< bool > _stopped
std::thread * _thread
SocketContainer _sockets
std::mutex _newSocketsLock
SocketContainer _newSockets
Acore::Asio::IoContext _ioContext
tcp::socket _acceptSocket
Acore::Asio::DeadlineTimer _updateTimer
Detailed Description
template<class SocketType>
class NetworkThread< SocketType >
Member Typedef Documentation
SocketContainer
template<class SocketType > typedef std::vector<std::shared_ptr<SocketType> > NetworkThread< SocketType >::SocketContainer private
Constructor & Destructor Documentation
NetworkThread()
template<class SocketType > NetworkThread< SocketType >::NetworkThread () inline
                    : _connections(0), _stopped(false), _thread(nullptr), _ioContext(1),
        _acceptSocket(_ioContext), _updateTimer(_ioContext) { }
~NetworkThread()
template<class SocketType > virtual NetworkThread< SocketType >::~NetworkThread () inline virtual
    {
        Stop();
        if (_thread)
        {
            Wait();
            delete _thread;
        }
    }
References NetworkThread< SocketType >::_thread, NetworkThread< SocketType >::Stop(), and NetworkThread< SocketType >::Wait().
Member Function Documentation
AddNewSockets()
template<class SocketType > void NetworkThread< SocketType >::AddNewSockets () inline protected
    {
        std::lock_guard<std::mutex> lock(_newSocketsLock);
        if (_newSockets.empty())
            return;
        for (std::shared_ptr<SocketType> sock : _newSockets)
        {
            if (!sock->IsOpen())
            {
                SocketRemoved(sock);
                --_connections;
            }
            else
                _sockets.push_back(sock);
        }
        _newSockets.clear();
    }
References NetworkThread< SocketType >::_connections, NetworkThread< SocketType >::_newSockets, NetworkThread< SocketType >::_newSocketsLock, NetworkThread< SocketType >::_sockets, and NetworkThread< SocketType >::SocketRemoved().
Referenced by NetworkThread< SocketType >::Update().
AddSocket()
template<class SocketType > virtual void NetworkThread< SocketType >::AddSocket (std::shared_ptr< SocketType > sock) inline virtual
    {
        std::lock_guard<std::mutex> lock(_newSocketsLock);
        ++_connections;
        _newSockets.push_back(sock);
        SocketAdded(sock);
    }
References NetworkThread< SocketType >::_connections, NetworkThread< SocketType >::_newSockets, NetworkThread< SocketType >::_newSocketsLock, and NetworkThread< SocketType >::SocketAdded().
GetConnectionCount()
template<class SocketType > int32 NetworkThread< SocketType >::GetConnectionCount () const inline
    {
        return _connections;
    }
References NetworkThread< SocketType >::_connections.
GetSocketForAccept()
template<class SocketType > tcp::socket * NetworkThread< SocketType >::GetSocketForAccept () inline
{ return &_acceptSocket; }
References NetworkThread< SocketType >::_acceptSocket.
Run()
template<class SocketType > void NetworkThread< SocketType >::Run () inline protected
    {
        LOG_DEBUG("misc", "Network Thread Starting");
        _updateTimer.expires_from_now(boost::posix_time::milliseconds(10));
        _updateTimer.async_wait(std::bind(&NetworkThread<SocketType>::Update, this));
        _ioContext.run();
        LOG_DEBUG("misc", "Network Thread exits");
        _newSockets.clear();
        _sockets.clear();
    }
References NetworkThread< SocketType >::_ioContext, NetworkThread< SocketType >::_newSockets, NetworkThread< SocketType >::_sockets, NetworkThread< SocketType >::_updateTimer, LOG_DEBUG, and Acore::Asio::IoContext::run().
Referenced by NetworkThread< SocketType >::Start().
SocketAdded()
template<class SocketType > virtual void NetworkThread< SocketType >::SocketAdded (std::shared_ptr< SocketType >) inline protected virtual
Reimplemented in WorldSocketThread.
{ }
Referenced by NetworkThread< SocketType >::AddSocket().
SocketRemoved()
template<class SocketType > virtual void NetworkThread< SocketType >::SocketRemoved (std::shared_ptr< SocketType >) inline protected virtual
Reimplemented in WorldSocketThread.
{ }
Referenced by NetworkThread< SocketType >::AddNewSockets().
Start()
template<class SocketType > bool NetworkThread< SocketType >::Start () inline
    {
        if (_thread)
            return false;
        _thread = new std::thread(&NetworkThread::Run, this);
        return true;
    }
References NetworkThread< SocketType >::_thread, and NetworkThread< SocketType >::Run().
Stop()
template<class SocketType > void NetworkThread< SocketType >::Stop () inline
    {
        _stopped = true;
        _ioContext.stop();
    }
References NetworkThread< SocketType >::_ioContext, NetworkThread< SocketType >::_stopped, and Acore::Asio::IoContext::stop().
Referenced by NetworkThread< SocketType >::~NetworkThread().
Update()
template<class SocketType > void NetworkThread< SocketType >::Update () inline protected
    {
        if (_stopped)
            return;
        _updateTimer.expires_from_now(boost::posix_time::milliseconds(10));
        _updateTimer.async_wait(std::bind(&NetworkThread<SocketType>::Update, this));
        AddNewSockets();
        _sockets.erase(std::remove_if(_sockets.begin(), _sockets.end(), [this](std::shared_ptr<SocketType> sock)
        {
            if (!sock->Update())
            {
                if (sock->IsOpen())
                    sock->CloseSocket();
                this->SocketRemoved(sock);
                --this->_connections;
                return true;
            }
            return false;
        }), _sockets.end());
    }
References NetworkThread< SocketType >::_sockets, NetworkThread< SocketType >::_stopped, NetworkThread< SocketType >::_updateTimer, and NetworkThread< SocketType >::AddNewSockets().
Wait()
template<class SocketType > void NetworkThread< SocketType >::Wait () inline
    {
        ASSERT(_thread);
        _thread->join();
        delete _thread;
        _thread = nullptr;
    }
References NetworkThread< SocketType >::_thread, and ASSERT.
Referenced by NetworkThread< SocketType >::~NetworkThread().
Member Data Documentation
_acceptSocket
template<class SocketType > tcp::socket NetworkThread< SocketType >::_acceptSocket private
Referenced by NetworkThread< SocketType >::GetSocketForAccept().
_connections
template<class SocketType > std::atomic<int32> NetworkThread< SocketType >::_connections private
Referenced by NetworkThread< SocketType >::AddNewSockets(), NetworkThread< SocketType >::AddSocket(), and NetworkThread< SocketType >::GetConnectionCount().
_ioContext
template<class SocketType > Acore::Asio::IoContext NetworkThread< SocketType >::_ioContext private
Referenced by NetworkThread< SocketType >::Run(), and NetworkThread< SocketType >::Stop().
_newSockets
template<class SocketType > SocketContainer NetworkThread< SocketType >::_newSockets private
Referenced by NetworkThread< SocketType >::AddNewSockets(), NetworkThread< SocketType >::AddSocket(), and NetworkThread< SocketType >::Run().
_newSocketsLock
template<class SocketType > std::mutex NetworkThread< SocketType >::_newSocketsLock private
Referenced by NetworkThread< SocketType >::AddNewSockets(), and NetworkThread< SocketType >::AddSocket().
_sockets
template<class SocketType > SocketContainer NetworkThread< SocketType >::_sockets private
Referenced by NetworkThread< SocketType >::AddNewSockets(), NetworkThread< SocketType >::Run(), and NetworkThread< SocketType >::Update().
_stopped
template<class SocketType > std::atomic<bool> NetworkThread< SocketType >::_stopped private
Referenced by NetworkThread< SocketType >::Stop(), and NetworkThread< SocketType >::Update().
_thread
template<class SocketType > std::thread* NetworkThread< SocketType >::_thread private
Referenced by NetworkThread< SocketType >::Start(), NetworkThread< SocketType >::Wait(), and NetworkThread< SocketType >::~NetworkThread().
_updateTimer
template<class SocketType > Acore::Asio::DeadlineTimer NetworkThread< SocketType >::_updateTimer private
Referenced by NetworkThread< SocketType >::Run(), and NetworkThread< SocketType >::Update().