AzerothCore: spell_dk_raise_ally Class Reference
spell_dk_raise_ally Class Reference
Private Member Functions
PrepareSpellScript (spell_dk_raise_ally)
SpellCastResult CheckCast ()
void HandleDummy (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
CheckCast()
SpellCastResult spell_dk_raise_ally::CheckCast () inline private
    {
        Player* unitTarget = GetHitPlayer();
        if (!unitTarget)
            return SPELL_FAILED_BAD_TARGETS;
        if (unitTarget->IsAlive()) // not discovered attributeEx5?
            return SPELL_FAILED_TARGET_NOT_DEAD;
        return SPELL_CAST_OK;
    }
References SpellScript::GetHitPlayer(), Unit::IsAlive(), SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, and SPELL_FAILED_TARGET_NOT_DEAD.
Referenced by Register().
HandleDummy()
void spell_dk_raise_ally::HandleDummy (SpellEffIndex) inline private
    {
        if (Player* unitTarget = GetHitPlayer())
        {
            unitTarget->CastSpell(unitTarget, GetEffectValue(), true);
            if (Unit* ghoul = unitTarget->GetCharm())
            {
                //health, mana, armor and resistance
                PetLevelInfo const* pInfo = sObjectMgr->GetPetLevelInfo(ghoul->GetEntry(), ghoul->GetLevel());
                if (pInfo)                                      // exist in DB
                {
                    ghoul->SetCreateHealth(pInfo->health);
                    ghoul->SetModifierValue(UNIT_MOD_HEALTH, BASE_VALUE, pInfo->health);
                    ghoul->SetModifierValue(UNIT_MOD_ARMOR, BASE_VALUE, float(pInfo->armor));
                    for (uint8 stat = 0; stat < MAX_STATS; ++stat)
                        ghoul->SetCreateStat(Stats(stat), float(pInfo->stats[stat]));
                }
                ghoul->SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(ghoul->GetLevel() - (ghoul->GetLevel() / 4)));
                ghoul->SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(ghoul->GetLevel() + (ghoul->GetLevel() / 4)));
                // Avoidance, Night of the Dead
                if (Aura* aur = ghoul->AddAura(62137, ghoul))
                    if (AuraEffect* aurEff = GetCaster()->GetAuraEffect(SPELL_AURA_ADD_FLAT_MODIFIER, SPELLFAMILY_DEATHKNIGHT, 2718, 0))
                        if (aur->GetEffect(0))
                            aur->GetEffect(0)->SetAmount(-aurEff->GetSpellInfo()->Effects[EFFECT_2].CalcValue());
                // Hit / Expertise scalling, warlock / hunter pets have this by default
                ghoul->AddAura(SPELL_HUNTER_PET_SCALING_04, ghoul);
                // DK Ghoul haste refresh
                float val = (GetCaster()->m_modAttackSpeedPct[BASE_ATTACK] - 1.0f) * 100.0f;
                ghoul->m_modAttackSpeedPct[BASE_ATTACK] = GetCaster()->m_modAttackSpeedPct[BASE_ATTACK];
                ghoul->SetFloatValue(UNIT_FIELD_BASEATTACKTIME, 2000.0f);
                ghoul->ApplyPercentModFloatValue(UNIT_FIELD_BASEATTACKTIME, val, true); // we want to reduce attack time
                // Strength + Stamina
                for (uint8 i = STAT_STRENGTH; i <= STAT_STAMINA; ++i)
                {
                    Stats stat = Stats(i);
                    if (stat != STAT_STRENGTH && stat != STAT_STAMINA)
                        continue;
                    float value = 0.0f;
                    float mod = (stat == STAT_STAMINA ? 0.3f : 0.7f);
                    // Check just if owner has Ravenous Dead since it's effect is not an aura
                    AuraEffect const* aurEff = GetCaster()->GetAuraEffect(SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, SPELLFAMILY_DEATHKNIGHT, 3010, 0);
                    if (aurEff)
                    {
                        SpellInfo const* spellInfo = aurEff->GetSpellInfo();                                                 // Then get the SpellProto and add the dummy effect value
                        AddPct(mod, spellInfo->Effects[EFFECT_1].CalcValue());                                              // Ravenous Dead edits the original scale
                    }
                    // Glyph of the Ghoul
                    aurEff = GetCaster()->GetAuraEffect(SPELL_DK_GLYPH_OF_THE_GHOUL, EFFECT_0);
                    if (aurEff)
                        mod += CalculatePct(1.0f, aurEff->GetAmount());                                                    // Glyph of the Ghoul adds a flat value to the scale mod
                    value = float(GetCaster()->GetStat(stat)) * mod;
                    value = ghoul->GetTotalStatValue(stat, value);
                    ghoul->SetStat(stat, int32(value));
                    ghoul->ApplyStatBuffMod(stat, value, true);
                }
                // Attack Power
                ghoul->SetModifierValue(UNIT_MOD_ATTACK_POWER, BASE_VALUE, 589 + ghoul->GetStat(STAT_STRENGTH) + ghoul->GetStat(STAT_AGILITY));
                ghoul->SetInt32Value(UNIT_FIELD_ATTACK_POWER, (int32)ghoul->GetModifierValue(UNIT_MOD_ATTACK_POWER, BASE_VALUE) * ghoul->GetModifierValue(UNIT_MOD_ATTACK_POWER, BASE_PCT));
                ghoul->SetInt32Value(UNIT_FIELD_ATTACK_POWER_MODS, (int32)ghoul->GetModifierValue(UNIT_MOD_ATTACK_POWER, TOTAL_VALUE));
                ghoul->SetFloatValue(UNIT_FIELD_ATTACK_POWER_MULTIPLIER, ghoul->GetModifierValue(UNIT_MOD_ATTACK_POWER, TOTAL_PCT) - 1.0f);
                // Health
                ghoul->SetModifierValue(UNIT_MOD_HEALTH, TOTAL_VALUE, (ghoul->GetStat(STAT_STAMINA) - ghoul->GetCreateStat(STAT_STAMINA)) * 10.0f);
                // Power Energy
                ghoul->SetModifierValue(UnitMods(UNIT_MOD_POWER_START + static_cast<uint8>(POWER_ENERGY)), BASE_VALUE, ghoul->GetCreatePowers(POWER_ENERGY));
                ghoul->UpdateAllStats();
                ghoul->SetFullHealth();
                // Aura Immunities
                ghoul->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_MELEE_RANGED_HASTE, true, SPELL_BLOCK_TYPE_POSITIVE);
                ghoul->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MELEE_SLOW, true, SPELL_BLOCK_TYPE_POSITIVE);
                ghoul->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_STAT, true, SPELL_BLOCK_TYPE_POSITIVE);
                ghoul->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, true, SPELL_BLOCK_TYPE_POSITIVE);
                ghoul->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_ATTACK_POWER, true, SPELL_BLOCK_TYPE_POSITIVE);
                ghoul->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_ATTACK_POWER_PCT, true, SPELL_BLOCK_TYPE_POSITIVE);
            }
        }
    }
References AddPct(), PetLevelInfo::armor, BASE_ATTACK, BASE_PCT, BASE_VALUE, CalculatePct(), EFFECT_0, EFFECT_1, EFFECT_2, SpellInfo::Effects, AuraEffect::GetAmount(), Unit::GetAuraEffect(), SpellScript::GetCaster(), Unit::GetCharm(), SpellScript::GetEffectValue(), SpellScript::GetHitPlayer(), AuraEffect::GetSpellInfo(), PetLevelInfo::health, IMMUNITY_STATE, Unit::m_modAttackSpeedPct, MAX_STATS, MAXDAMAGE, MINDAMAGE, POWER_ENERGY, sObjectMgr, SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_AURA_MELEE_SLOW, SPELL_AURA_MOD_ATTACK_POWER, SPELL_AURA_MOD_ATTACK_POWER_PCT, SPELL_AURA_MOD_MELEE_RANGED_HASTE, SPELL_AURA_MOD_STAT, SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, SPELL_BLOCK_TYPE_POSITIVE, SPELL_DK_GLYPH_OF_THE_GHOUL, SPELL_HUNTER_PET_SCALING_04, SPELLFAMILY_DEATHKNIGHT, STAT_AGILITY, STAT_STAMINA, STAT_STRENGTH, PetLevelInfo::stats, TOTAL_PCT, TOTAL_VALUE, UNIT_FIELD_ATTACK_POWER, UNIT_FIELD_ATTACK_POWER_MODS, UNIT_FIELD_ATTACK_POWER_MULTIPLIER, UNIT_FIELD_BASEATTACKTIME, UNIT_MOD_ARMOR, UNIT_MOD_ATTACK_POWER, UNIT_MOD_HEALTH, and UNIT_MOD_POWER_START.
Referenced by Register().
PrepareSpellScript()
spell_dk_raise_ally::PrepareSpellScript (spell_dk_raise_ally) private
Register()
void spell_dk_raise_ally::Register () inline override private virtual
Implements _SpellScript.
    {
        OnCheckCast += SpellCheckCastFn(spell_dk_raise_ally::CheckCast);
        OnEffectHitTarget += SpellEffectFn(spell_dk_raise_ally::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
References CheckCast(), EFFECT_0, HandleDummy(), SpellScript::OnCheckCast, SpellScript::OnEffectHitTarget, SPELL_EFFECT_DUMMY, SpellCheckCastFn, and SpellEffectFn.