AzerothCore: Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck Class Reference
Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
AnyUnfriendlyNoTotemUnitInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range)
bool operator() (Unit *u)
Private Attributes
WorldObject const * i_obj
Unit const * i_funit
float i_range
Detailed Description
Constructor & Destructor Documentation
AnyUnfriendlyNoTotemUnitInObjectRangeCheck()
Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::AnyUnfriendlyNoTotemUnitInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range) inline
: i_obj(obj), i_funit(funit), i_range(range) {}
Member Function Documentation
operator()()
bool Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::operator() (Unit * u) inline
        {
            if (!u->IsAlive())
                return false;
            if (u->GetCreatureType() == CREATURE_TYPE_NON_COMBAT_PET)
                return false;
            if (u->IsCreature() && (u->ToCreature()->IsTotem() || u->ToCreature()->IsTrigger() || u->ToCreature()->IsAvoidingAOE())) // pussywizard: added IsAvoidingAOE()
                return false;
            if (!u->isTargetableForAttack(false, i_funit))
                return false;
            return i_obj->IsWithinDistInMap(u, i_range) && !i_funit->IsFriendlyTo(u);
        }
References CREATURE_TYPE_NON_COMBAT_PET, Unit::GetCreatureType(), i_funit, i_obj, i_range, Unit::IsAlive(), Creature::IsAvoidingAOE(), Object::IsCreature(), Unit::IsFriendlyTo(), Unit::isTargetableForAttack(), Unit::IsTotem(), Creature::IsTrigger(), WorldObject::IsWithinDistInMap(), and Object::ToCreature().
Member Data Documentation
i_funit
Unit const* Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::i_funit private
Referenced by operator()().
i_obj
WorldObject const* Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::i_obj private
Referenced by operator()().
i_range
float Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::i_range private
Referenced by operator()().