AzerothCore: instance_zulaman::instance_zulaman_InstanceMapScript Struct Reference
instance_zulaman::instance_zulaman_InstanceMapScript Struct Reference
Public Member Functions
instance_zulaman_InstanceMapScript (Map *map)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SummonHostage (uint8 num)
void CheckInstanceStatus ()
std::string GetSaveData () override
void Load (const char *load) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
void Update (uint32 diff) override
ObjectGuid GetGuidData (uint32 type) const override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
ObjectGuid HarkorsSatchelGUID
ObjectGuid TanzarsTrunkGUID
ObjectGuid AshlisBagGUID
ObjectGuid KrazsPackageGUID
ObjectGuid StrangeGongGUID
ObjectGuid HarrisonJonesGUID
ObjectGuid HexLordGateGUID
ObjectGuid ZulJinGateGUID
ObjectGuid MassiveGateGUID
ObjectGuid AkilzonDoorGUID
ObjectGuid ZulJinDoorGUID
ObjectGuid HalazziDoorGUID
uint32 QuestTimer
uint16 BossKilled
uint16 QuestMinute
uint16 ChestLooted
uint32 m_auiEncounter [MAX_ENCOUNTER]
uint32 RandVendor [RAND_VENDOR]
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_zulaman_InstanceMapScript()
instance_zulaman::instance_zulaman_InstanceMapScript::instance_zulaman_InstanceMapScript (Map * map) inline
: InstanceScript(map) {}
Member Function Documentation
CheckInstanceStatus()
void instance_zulaman::instance_zulaman_InstanceMapScript::CheckInstanceStatus () inline
        {
            if (BossKilled >= DATA_HALAZZIEVENT)
                HandleGameObject(HexLordGateGUID, true);
            if (BossKilled >= DATA_HEXLORDEVENT)
                HandleGameObject(ZulJinGateGUID, true);
        }
References BossKilled, DATA_HALAZZIEVENT, DATA_HEXLORDEVENT, InstanceScript::HandleGameObject(), HexLordGateGUID, and ZulJinGateGUID.
Referenced by OnGameObjectCreate(), and SetData().
GetData()
uint32 instance_zulaman::instance_zulaman_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_GONGEVENT:
                    return m_auiEncounter[DATA_GONGEVENT];
                case DATA_NALORAKKEVENT:
                    return m_auiEncounter[DATA_NALORAKKEVENT];
                case DATA_AKILZONEVENT:
                    return m_auiEncounter[DATA_AKILZONEVENT];
                case DATA_JANALAIEVENT:
                    return m_auiEncounter[DATA_JANALAIEVENT];
                case DATA_HALAZZIEVENT:
                    return m_auiEncounter[DATA_HALAZZIEVENT];
                case DATA_HEXLORDEVENT:
                    return m_auiEncounter[DATA_HEXLORDEVENT];
                case DATA_ZULJINEVENT:
                    return m_auiEncounter[DATA_ZULJINEVENT];
                case DATA_CHESTLOOTED:
                    return ChestLooted;
                case TYPE_RAND_VENDOR_1:
                    return RandVendor[0];
                case TYPE_RAND_VENDOR_2:
                    return RandVendor[1];
                default:
                    return 0;
            }
        }
References ChestLooted, DATA_AKILZONEVENT, DATA_CHESTLOOTED, DATA_GONGEVENT, DATA_HALAZZIEVENT, DATA_HEXLORDEVENT, DATA_JANALAIEVENT, DATA_NALORAKKEVENT, DATA_ZULJINEVENT, m_auiEncounter, RandVendor, TYPE_RAND_VENDOR_1, and TYPE_RAND_VENDOR_2.
GetGuidData()
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case GO_STRANGE_GONG:
                    return StrangeGongGUID;
                case GO_MASSIVE_GATE:
                    return MassiveGateGUID;
            }
            return ObjectGuid::Empty;
        }
References ObjectGuid::Empty, GO_MASSIVE_GATE, GO_STRANGE_GONG, MassiveGateGUID, and StrangeGongGUID.
GetSaveData()
std::string instance_zulaman::instance_zulaman_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
        {
            OUT_SAVE_INST_DATA;
            std::ostringstream ss;
            ss << "S " << BossKilled << ' ' << ChestLooted << ' ' << QuestMinute;
            OUT_SAVE_INST_DATA_COMPLETE;
            return ss.str();
        }
References BossKilled, ChestLooted, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, and QuestMinute.
Initialize()
void instance_zulaman::instance_zulaman_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetHeaders(DataHeader);
            LoadObjectData(creatureData, gameObjectData);
            memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
            QuestTimer = 0;
            QuestMinute = 0;
            BossKilled = 0;
            ChestLooted = 0;
            for (uint8 i = 0; i < RAND_VENDOR; ++i)
                RandVendor[i] = NOT_STARTED;
            m_auiEncounter[DATA_GONGEVENT] = NOT_STARTED;
        }
References BossKilled, ChestLooted, creatureData, DATA_GONGEVENT, DataHeader, gameObjectData, InstanceScript::LoadObjectData(), m_auiEncounter, NOT_STARTED, QuestMinute, QuestTimer, RAND_VENDOR, RandVendor, and InstanceScript::SetHeaders().
IsEncounterInProgress()
bool instance_zulaman::instance_zulaman_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                if (m_auiEncounter[i] == IN_PROGRESS)
                    return true;
            return false;
        }
References IN_PROGRESS, m_auiEncounter, and MAX_ENCOUNTER.
Load()
void instance_zulaman::instance_zulaman_InstanceMapScript::Load (const char * load) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!load)
                return;
            std::istringstream ss(load);
            char dataHead; // S
            uint16 data1, data2, data3;
            ss >> dataHead >> data1 >> data2 >> data3;
            if (dataHead == 'S')
            {
                BossKilled = data1;
                ChestLooted = data2;
                QuestMinute = data3;
            }
            else
            {
                LOG_ERROR("misc", "Zul'aman: corrupted save data.");
            }
        }
References BossKilled, ChestLooted, LOG_ERROR, and QuestMinute.
OnCreatureCreate()
void instance_zulaman::instance_zulaman_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_HARRISON_JONES:
                    HarrisonJonesGUID = creature->GetGUID();
                    break;
                case NPC_JANALAI:
                case NPC_ZULJIN:
                case NPC_HEXLORD:
                case NPC_HALAZZI:
                case NPC_NALORAKK:
                default:
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References Object::GetEntry(), Object::GetGUID(), HarrisonJonesGUID, NPC_HALAZZI, NPC_HARRISON_JONES, NPC_HEXLORD, NPC_JANALAI, NPC_NALORAKK, NPC_ZULJIN, and InstanceScript::OnCreatureCreate().
OnGameObjectCreate()
void instance_zulaman::instance_zulaman_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_DOOR_HALAZZI:
                    HalazziDoorGUID = go->GetGUID();
                    break;
                case GO_GATE_ZULJIN:
                    ZulJinGateGUID = go->GetGUID();
                    break;
                case GO_GATE_HEXLORD:
                    HexLordGateGUID = go->GetGUID();
                    break;
                case GO_MASSIVE_GATE:
                    MassiveGateGUID = go->GetGUID();
                    break;
                case GO_DOOR_AKILZON:
                    AkilzonDoorGUID = go->GetGUID();
                    break;
                case GO_DOOR_ZULJIN:
                    ZulJinDoorGUID = go->GetGUID();
                    break;
                case GO_HARKORS_SATCHEL:
                    HarkorsSatchelGUID = go->GetGUID();
                    break;
                case GO_TANZARS_TRUNK:
                    TanzarsTrunkGUID = go->GetGUID();
                    break;
                case GO_ASHLIS_BAG:
                    AshlisBagGUID = go->GetGUID();
                    break;
                case GO_KRAZS_PACKAGE:
                    KrazsPackageGUID = go->GetGUID();
                    break;
                case GO_STRANGE_GONG:
                    StrangeGongGUID = go->GetGUID();
                    break;
                default:
                    break;
            }
            CheckInstanceStatus();
        }
References AkilzonDoorGUID, AshlisBagGUID, CheckInstanceStatus(), Object::GetEntry(), Object::GetGUID(), GO_ASHLIS_BAG, GO_DOOR_AKILZON, GO_DOOR_HALAZZI, GO_DOOR_ZULJIN, GO_GATE_HEXLORD, GO_GATE_ZULJIN, GO_HARKORS_SATCHEL, GO_KRAZS_PACKAGE, GO_MASSIVE_GATE, GO_STRANGE_GONG, GO_TANZARS_TRUNK, HalazziDoorGUID, HarkorsSatchelGUID, HexLordGateGUID, KrazsPackageGUID, MassiveGateGUID, StrangeGongGUID, TanzarsTrunkGUID, ZulJinDoorGUID, and ZulJinGateGUID.
OnPlayerEnter()
void instance_zulaman::instance_zulaman_InstanceMapScript::OnPlayerEnter (Player *) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!HarrisonJonesGUID)
                instance->SummonCreature(NPC_HARRISON_JONES, HarrisonJonesLoc);
        }
References HarrisonJonesGUID, HarrisonJonesLoc, InstanceScript::instance, NPC_HARRISON_JONES, and Map::SummonCreature().
SetData()
void instance_zulaman::instance_zulaman_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_GONGEVENT:
                    m_auiEncounter[DATA_GONGEVENT] = data;
                    if (data == IN_PROGRESS)
                        SaveToDB();
                    else if (data == DONE)
                        QuestMinute = 21;
                    break;
                case DATA_NALORAKKEVENT:
                    m_auiEncounter[DATA_NALORAKKEVENT] = data;
                    if (data == DONE)
                    {
                        if (QuestMinute)
{
                            QuestMinute += 15;
                            DoUpdateWorldState(WORLDSTATE_TIME_TO_SACRIFICE, QuestMinute);
                        }
                        SummonHostage(0);
                        SaveToDB();
                    }
                    break;
                case DATA_AKILZONEVENT:
                    m_auiEncounter[DATA_AKILZONEVENT] = data;
                    HandleGameObject(AkilzonDoorGUID, data != IN_PROGRESS);
                    if (data == DONE)
                    {
                        if (QuestMinute)
{
                            QuestMinute += 10;
                            DoUpdateWorldState(WORLDSTATE_TIME_TO_SACRIFICE, QuestMinute);
                        }
                        SummonHostage(1);
                        SaveToDB();
                    }
                    break;
                case DATA_JANALAIEVENT:
                    m_auiEncounter[DATA_JANALAIEVENT] = data;
                    if (data == DONE)
                        SummonHostage(2);
                    SaveToDB();
                    break;
                case DATA_HALAZZIEVENT:
                    m_auiEncounter[DATA_HALAZZIEVENT] = data;
                    HandleGameObject(HalazziDoorGUID, data != IN_PROGRESS);
                    if (data == DONE) SummonHostage(3);
                    SaveToDB();
                    break;
                case DATA_HEXLORDEVENT:
                    m_auiEncounter[DATA_HEXLORDEVENT] = data;
                    if (data == IN_PROGRESS)
                        HandleGameObject(HexLordGateGUID, false);
                    else if (data == NOT_STARTED)
                        CheckInstanceStatus();
                    SaveToDB();
                    break;
                case DATA_ZULJINEVENT:
                    m_auiEncounter[DATA_ZULJINEVENT] = data;
                    HandleGameObject(ZulJinDoorGUID, data != IN_PROGRESS);
                    SaveToDB();
                    break;
                case DATA_CHESTLOOTED:
                    ++ChestLooted;
                    SaveToDB();
                    break;
                case TYPE_RAND_VENDOR_1:
                    RandVendor[0] = data;
                    break;
                case TYPE_RAND_VENDOR_2:
                    RandVendor[1] = data;
                    break;
            }
            if (data == DONE)
            {
                ++BossKilled;
                if (QuestMinute && BossKilled >= DATA_HALAZZIEVENT)
                {
                    QuestMinute = 0;
                    DoUpdateWorldState(WORLDSTATE_SHOW_TIMER, 0);
                }
                CheckInstanceStatus();
                SaveToDB();
            }
        }
References AkilzonDoorGUID, BossKilled, CheckInstanceStatus(), ChestLooted, DATA_AKILZONEVENT, DATA_CHESTLOOTED, DATA_GONGEVENT, DATA_HALAZZIEVENT, DATA_HEXLORDEVENT, DATA_JANALAIEVENT, DATA_NALORAKKEVENT, DATA_ZULJINEVENT, DONE, InstanceScript::DoUpdateWorldState(), HalazziDoorGUID, InstanceScript::HandleGameObject(), HexLordGateGUID, IN_PROGRESS, m_auiEncounter, NOT_STARTED, QuestMinute, RandVendor, InstanceScript::SaveToDB(), SummonHostage(), TYPE_RAND_VENDOR_1, TYPE_RAND_VENDOR_2, WORLDSTATE_SHOW_TIMER, WORLDSTATE_TIME_TO_SACRIFICE, and ZulJinDoorGUID.
SummonHostage()
void instance_zulaman::instance_zulaman_InstanceMapScript::SummonHostage (uint8 num) inline
        {
            if (!QuestMinute)
                return;
            Map::PlayerList const& PlayerList = instance->GetPlayers();
            if (PlayerList.IsEmpty())
                return;
            Map::PlayerList::const_iterator i = PlayerList.begin();
            if (Player* i_pl = i->GetSource())
            {
                if (Unit* Hostage = i_pl->SummonCreature(HostageInfo[num].npc, HostageInfo[num].x, HostageInfo[num].y, HostageInfo[num].z, HostageInfo[num].o, TEMPSUMMON_DEAD_DESPAWN, 0))
                {
                    Hostage->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    Hostage->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                }
            }
        }
References MapRefMgr::begin(), Map::GetPlayers(), HostageInfo, InstanceScript::instance, LinkedListHead::IsEmpty(), SHostageInfo::npc, SHostageInfo::o, QuestMinute, WorldObject::SummonCreature(), TEMPSUMMON_DEAD_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_FLAG_GOSSIP, SHostageInfo::x, SHostageInfo::y, and SHostageInfo::z.
Referenced by SetData().
Update()
void instance_zulaman::instance_zulaman_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            if (QuestMinute)
            {
                if (QuestTimer <= diff)
                {
                    QuestMinute--;
                    SaveToDB();
                    QuestTimer += 60000;
                    if (QuestMinute)
                    {
                        DoUpdateWorldState(WORLDSTATE_SHOW_TIMER, 1);
                        DoUpdateWorldState(WORLDSTATE_TIME_TO_SACRIFICE, QuestMinute);
                    }
                    else DoUpdateWorldState(WORLDSTATE_SHOW_TIMER, 0);
                }
                QuestTimer -= diff;
            }
        }
References InstanceScript::DoUpdateWorldState(), QuestMinute, QuestTimer, InstanceScript::SaveToDB(), WORLDSTATE_SHOW_TIMER, and WORLDSTATE_TIME_TO_SACRIFICE.
Member Data Documentation
AkilzonDoorGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::AkilzonDoorGUID
Referenced by OnGameObjectCreate(), and SetData().
AshlisBagGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::AshlisBagGUID
Referenced by OnGameObjectCreate().
BossKilled
uint16 instance_zulaman::instance_zulaman_InstanceMapScript::BossKilled
Referenced by CheckInstanceStatus(), GetSaveData(), Initialize(), Load(), and SetData().
ChestLooted
uint16 instance_zulaman::instance_zulaman_InstanceMapScript::ChestLooted
Referenced by GetData(), GetSaveData(), Initialize(), Load(), and SetData().
HalazziDoorGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::HalazziDoorGUID
Referenced by OnGameObjectCreate(), and SetData().
HarkorsSatchelGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::HarkorsSatchelGUID
Referenced by OnGameObjectCreate().
HarrisonJonesGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::HarrisonJonesGUID
Referenced by OnCreatureCreate(), and OnPlayerEnter().
HexLordGateGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::HexLordGateGUID
Referenced by CheckInstanceStatus(), OnGameObjectCreate(), and SetData().
KrazsPackageGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::KrazsPackageGUID
Referenced by OnGameObjectCreate().
m_auiEncounter
uint32 instance_zulaman::instance_zulaman_InstanceMapScript::m_auiEncounter[MAX_ENCOUNTER]
Referenced by GetData(), Initialize(), IsEncounterInProgress(), and SetData().
MassiveGateGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::MassiveGateGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
QuestMinute
uint16 instance_zulaman::instance_zulaman_InstanceMapScript::QuestMinute
Referenced by GetSaveData(), Initialize(), Load(), SetData(), SummonHostage(), and Update().
QuestTimer
uint32 instance_zulaman::instance_zulaman_InstanceMapScript::QuestTimer
Referenced by Initialize(), and Update().
RandVendor
uint32 instance_zulaman::instance_zulaman_InstanceMapScript::RandVendor[RAND_VENDOR]
Referenced by GetData(), Initialize(), and SetData().
StrangeGongGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::StrangeGongGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
TanzarsTrunkGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::TanzarsTrunkGUID
Referenced by OnGameObjectCreate().
ZulJinDoorGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::ZulJinDoorGUID
Referenced by OnGameObjectCreate(), and SetData().
ZulJinGateGUID
ObjectGuid instance_zulaman::instance_zulaman_InstanceMapScript::ZulJinGateGUID
Referenced by CheckInstanceStatus(), and OnGameObjectCreate().