AzerothCore: AreaBoundary Class Reference
AreaBoundary Class Reference abstract
#include "AreaBoundary.h"
Classes
struct DoublePosition
Public Member Functions
bool IsWithinBoundary (Position const *pos) const
bool IsWithinBoundary (Position const &pos) const
virtual ~AreaBoundary ()
Protected Member Functions
AreaBoundary (bool isInverted)
virtual bool IsWithinBoundaryArea (Position const *pos) const =0
Private Attributes
bool _isInvertedBoundary
Detailed Description
Constructor & Destructor Documentation
~AreaBoundary()
virtual AreaBoundary::~AreaBoundary () inline virtual
{ }
AreaBoundary()
AreaBoundary::AreaBoundary (bool isInverted) inline explicit protected
: _isInvertedBoundary(isInverted) { }
Member Function Documentation
IsWithinBoundary() [1/2]
bool AreaBoundary::IsWithinBoundary (Position const & pos) const inline
{ return IsWithinBoundary(&pos); }
References IsWithinBoundary().
Referenced by IsWithinBoundary().
IsWithinBoundary() [2/2]
bool AreaBoundary::IsWithinBoundary (Position const * pos) const inline
{ return pos && (IsWithinBoundaryArea(pos) != _isInvertedBoundary); }
Referenced by BoundaryUnionBoundary::IsWithinBoundaryArea(), BoundaryIntersectBoundary::IsWithinBoundaryArea(), and boss_kologarn_pit_kill_bunny::Reset().
IsWithinBoundaryArea()
virtual bool AreaBoundary::IsWithinBoundaryArea (Position const * pos) const protected pure virtual
Implemented in RectangleBoundary, CircleBoundary, EllipseBoundary, TriangleBoundary, ParallelogramBoundary, ZRangeBoundary, BoundaryUnionBoundary, and BoundaryIntersectBoundary.
Member Data Documentation
_isInvertedBoundary
bool AreaBoundary::_isInvertedBoundary private