AzerothCore: boss_arlokk::boss_arlokkAI Struct Reference
boss_arlokk::boss_arlokkAI Struct Reference
Public Member Functions
boss_arlokkAI (Creature *creature)
void Reset () override
void JustDied (Unit *) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustReachedHome () override
void EnterEvadeMode (EvadeReason why) override
void SetData (uint32 id, uint32) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint8 _summonCountA
uint8 _summonCountB
ObjectGuid _triggersSideAGUID [5]
ObjectGuid _triggersSideBGUID [5]
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
bool _ProccessHealthCheckEvent (uint8 healthPct, uint32 damage, std::function< void()> exec) const
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
TaskScheduler scheduler
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_arlokkAI()
boss_arlokk::boss_arlokkAI::boss_arlokkAI (Creature * creature) inline
: BossAI(creature, DATA_ARLOKK) { }
Member Function Documentation
EnterEvadeMode()
void boss_arlokk::boss_arlokkAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            BossAI::EnterEvadeMode(why);
            std::list<Creature*> panthers;
            GetCreatureListWithEntryInGrid(panthers, me, NPC_ZULIAN_PROWLER, 200.f);
            for (auto const& panther : panthers)
                panther->DespawnOrUnsummon();
        }
References CreatureAI::EnterEvadeMode(), GetCreatureListWithEntryInGrid(), ScriptedAI::me, and NPC_ZULIAN_PROWLER.
JustDied()
void boss_arlokk::boss_arlokkAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            _JustDied();
            Talk(SAY_DEATH);
        }
References BossAI::_JustDied(), and SAY_DEATH.
JustEngagedWith()
void boss_arlokk::boss_arlokkAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            _JustEngagedWith();
            events.ScheduleEvent(EVENT_SHADOW_WORD_PAIN, 7s, 9s, 0, PHASE_ONE);
            events.ScheduleEvent(EVENT_GOUGE, 12s, 15s, 0, PHASE_ONE);
            events.ScheduleEvent(EVENT_SUMMON_PROWLERS, 6s, 0, PHASE_ALL);
            events.ScheduleEvent(EVENT_MARK_OF_ARLOKK, 9s, 11s, 0, PHASE_ALL);
            events.ScheduleEvent(EVENT_TRANSFORM, 30s, 0, PHASE_ONE);
            Talk(SAY_AGGRO);
            // Sets up list of Panther spawners to cast on
            std::list<Creature*> triggerList;
            GetCreatureListWithEntryInGrid(triggerList, me, NPC_PANTHER_TRIGGER, 100.0f);
            if (!triggerList.empty())
            {
                uint8 sideA = 0;
                uint8 sideB = 0;
                for (auto const& trigger : triggerList)
                {
                    if (trigger->GetPositionY() < -1625.0f)
                    {
                        _triggersSideAGUID[sideA] = trigger->GetGUID();
                        ++sideA;
                    }
                    else
                    {
                        _triggersSideBGUID[sideB] = trigger->GetGUID();
                        ++sideB;
                    }
                }
            }
        }
References BossAI::_JustEngagedWith(), _triggersSideAGUID, _triggersSideBGUID, EVENT_GOUGE, EVENT_MARK_OF_ARLOKK, EVENT_SHADOW_WORD_PAIN, EVENT_SUMMON_PROWLERS, EVENT_TRANSFORM, GetCreatureListWithEntryInGrid(), ScriptedAI::me, NPC_PANTHER_TRIGGER, PHASE_ALL, PHASE_ONE, and SAY_AGGRO.
JustReachedHome()
void boss_arlokk::boss_arlokkAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
        {
            if (GameObject* object = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_GONG_OF_BETHEKK)))
                object->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
            me->DespawnOrUnsummon();
        }
References Creature::DespawnOrUnsummon(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_FLAG_NOT_SELECTABLE, GO_GONG_OF_BETHEKK, BossAI::instance, and ScriptedAI::me.
Reset()
void boss_arlokk::boss_arlokkAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            if (events.IsInPhase(PHASE_TWO))
                me->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_PCT, 35.0f, false); // hack
            _Reset();
            _summonCountA = 0;
            _summonCountB = 0;
            me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(WEAPON_DAGGER));
            me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, uint32(WEAPON_DAGGER));
            me->SetWalk(false);
            me->SetHomePosition(PosMoveOnSpawn[0]);
            me->GetMotionMaster()->MoveTargetedHome();
        }
References BossAI::_Reset(), _summonCountA, _summonCountB, Unit::GetMotionMaster(), Unit::HandleStatModifier(), ScriptedAI::me, MotionMaster::MoveTargetedHome(), PHASE_TWO, PosMoveOnSpawn, Creature::SetHomePosition(), Object::SetUInt32Value(), Creature::SetWalk(), TOTAL_PCT, UNIT_MOD_DAMAGE_MAINHAND, UNIT_VIRTUAL_ITEM_SLOT_ID, and WEAPON_DAGGER.
SetData()
void boss_arlokk::boss_arlokkAI::SetData (uint32 id, uint32) inline override virtual
Reimplemented from UnitAI.
        {
            if (id == 1)
                --_summonCountA;
            else if (id == 2)
                --_summonCountB;
        }
References _summonCountA, and _summonCountB.
UpdateAI()
void boss_arlokk::boss_arlokkAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            while (uint32 eventId = events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_SHADOW_WORD_PAIN:
                        DoCastVictim(SPELL_SHADOW_WORD_PAIN, true);
                        events.ScheduleEvent(EVENT_SHADOW_WORD_PAIN, 5s, 7s, 0, PHASE_ONE);
                        break;
                    case EVENT_GOUGE:
                        DoCastVictim(SPELL_GOUGE, true);
                        break;
                    case EVENT_SUMMON_PROWLERS:
                        if (_summonCountA < MAX_PROWLERS_PER_SIDE)
{
                            if (Unit* trigger = ObjectAccessor::GetUnit(*me, _triggersSideAGUID[urand(0, 4)]))
{
                                trigger->CastSpell(trigger, SPELL_SUMMON_PROWLER);
                                ++_summonCountA;
                            }
                        }
                        if (_summonCountB < MAX_PROWLERS_PER_SIDE)
{
                            if (Unit* trigger = ObjectAccessor::GetUnit(*me, _triggersSideBGUID[urand(0, 4)]))
{
                                trigger->CastSpell(trigger, SPELL_SUMMON_PROWLER);
                                ++_summonCountB;
                            }
                        }
                        events.ScheduleEvent(EVENT_SUMMON_PROWLERS, 6s, 0, PHASE_ALL);
                        break;
                    case EVENT_MARK_OF_ARLOKK:
{
                            Unit* target = SelectTarget(SelectTargetMethod::MaxThreat, urand(1, 3), 0.0f, false, true, -SPELL_MARK_OF_ARLOKK);
                            if (!target)
                                target = me->GetVictim();
                            if (target)
{
                                DoCast(target, SPELL_MARK_OF_ARLOKK, true);
                                Talk(SAY_FEAST_PROWLER, target);
                            }
                            events.ScheduleEvent(EVENT_MARK_OF_ARLOKK, 120s, 130s);
                            break;
                        }
                    case EVENT_TRANSFORM:
{
                            DoCastSelf(SPELL_PANTHER_TRANSFORM); // SPELL_AURA_TRANSFORM
                            me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(EQUIP_UNEQUIP));
                            me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, uint32(EQUIP_UNEQUIP));
                            me->AttackStop();
                            DoResetThreatList();
                            me->SetReactState(REACT_PASSIVE);
                            me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                            DoCastSelf(SPELL_VANISH_VISUAL);
                            DoCastSelf(SPELL_VANISH);
                            events.ScheduleEvent(EVENT_VANISH, 1s, 0, PHASE_ONE);
                            break;
                        }
                    case EVENT_VANISH:
                        DoCastSelf(SPELL_SUPER_INVIS);
                        me->SetWalk(false);
                        me->GetMotionMaster()->MovePoint(0, frand(-11551.0f, -11508.0f), frand(-1638.0f, -1617.0f), me->GetPositionZ());
                        events.ScheduleEvent(EVENT_VANISH_2, 9s, 0, PHASE_ONE);
                        break;
                    case EVENT_VANISH_2:
                        DoCastSelf(SPELL_VANISH);
                        DoCastSelf(SPELL_SUPER_INVIS);
                        events.ScheduleEvent(EVENT_VISIBLE, 41s, 47s, 0, PHASE_ONE);
                        break;
                    case EVENT_VISIBLE:
                        me->SetReactState(REACT_AGGRESSIVE);
                        me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
                            AttackStart(target);
                        me->RemoveAura(SPELL_SUPER_INVIS);
                        me->RemoveAura(SPELL_VANISH);
                        events.ScheduleEvent(EVENT_RAVAGE, 10s, 14s, 0, PHASE_TWO);
                        events.ScheduleEvent(EVENT_TRANSFORM_BACK, 30s, 40s, 0, PHASE_TWO);
                        events.SetPhase(PHASE_TWO);
                        me->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_PCT, 35.0f, true); // hack
                        break;
                    case EVENT_RAVAGE:
                        DoCastVictim(SPELL_RAVAGE, true);
                        events.ScheduleEvent(EVENT_RAVAGE, 10s, 14s, 0, PHASE_TWO);
                        break;
                    case EVENT_TRANSFORM_BACK:
{
                            me->RemoveAura(SPELL_PANTHER_TRANSFORM); // SPELL_AURA_TRANSFORM
                            DoCast(me, SPELL_VANISH_VISUAL);
                            me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(WEAPON_DAGGER));
                            me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, uint32(WEAPON_DAGGER));
                            me->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_PCT, 35.0f, false); // hack
                            events.ScheduleEvent(EVENT_SHADOW_WORD_PAIN, 4s, 7s, 0, PHASE_ONE);
                            events.ScheduleEvent(EVENT_GOUGE, 12s, 15s, 0, PHASE_ONE);
                            events.ScheduleEvent(EVENT_TRANSFORM, 30s, 0, PHASE_ONE);
                            events.SetPhase(PHASE_ONE);
                            break;
                        }
                    default:
                        break;
                }
            }
            DoMeleeAttackIfReady();
        }
References _summonCountA, _summonCountB, _triggersSideAGUID, _triggersSideBGUID, ScriptedAI::AttackStart(), Unit::AttackStop(), UnitAI::DoCast(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreatList(), EQUIP_UNEQUIP, EVENT_GOUGE, EVENT_MARK_OF_ARLOKK, EVENT_RAVAGE, EVENT_SHADOW_WORD_PAIN, EVENT_SUMMON_PROWLERS, EVENT_TRANSFORM, EVENT_TRANSFORM_BACK, EVENT_VANISH, EVENT_VANISH_2, EVENT_VISIBLE, frand(), Unit::GetMotionMaster(), Position::GetPositionZ(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::HandleStatModifier(), Unit::HasUnitState(), MAX_PROWLERS_PER_SIDE, ScriptedAI::me, MotionMaster::MovePoint(), PHASE_ALL, PHASE_ONE, PHASE_TWO, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAura(), Unit::RemoveUnitFlag(), SAY_FEAST_PROWLER, UnitAI::SelectTarget(), Creature::SetReactState(), Object::SetUInt32Value(), Unit::SetUnitFlag(), Creature::SetWalk(), SPELL_GOUGE, SPELL_MARK_OF_ARLOKK, SPELL_PANTHER_TRANSFORM, SPELL_RAVAGE, SPELL_SHADOW_WORD_PAIN, SPELL_SUMMON_PROWLER, SPELL_SUPER_INVIS, SPELL_VANISH, SPELL_VANISH_VISUAL, TOTAL_PCT, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_MOD_DAMAGE_MAINHAND, UNIT_STATE_CASTING, UNIT_VIRTUAL_ITEM_SLOT_ID, CreatureAI::UpdateVictim(), urand(), and WEAPON_DAGGER.
Member Data Documentation
_summonCountA
uint8 boss_arlokk::boss_arlokkAI::_summonCountA private
Referenced by Reset(), SetData(), and UpdateAI().
_summonCountB
uint8 boss_arlokk::boss_arlokkAI::_summonCountB private
Referenced by Reset(), SetData(), and UpdateAI().
_triggersSideAGUID
ObjectGuid boss_arlokk::boss_arlokkAI::_triggersSideAGUID[5] private
Referenced by JustEngagedWith(), and UpdateAI().
_triggersSideBGUID
ObjectGuid boss_arlokk::boss_arlokkAI::_triggersSideBGUID[5] private
Referenced by JustEngagedWith(), and UpdateAI().