AzerothCore: cast_commandscript Class Reference
cast_commandscript Class Reference
Public Member Functions
cast_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool CheckSpellCastResult (ChatHandler *handler, SpellCastResult result)
static bool CheckSpellExistsAndIsValid (ChatHandler *handler, SpellInfo const *spell)
static Optional< TriggerCastFlags > GetTriggerFlags (Optional< std::string > triggeredStr)
static bool HandleCastCommand (ChatHandler *handler, SpellInfo const *spell, Optional< std::string > triggeredStr)
static bool HandleCastBackCommand (ChatHandler *handler, SpellInfo const *spell, Optional< std::string > triggeredStr)
static bool HandleCastDistCommand (ChatHandler *handler, SpellInfo const *spell, float dist, Optional< std::string > triggeredStr)
static bool HandleCastSelfCommand (ChatHandler *handler, SpellInfo const *spell, Optional< std::string > triggeredStr)
static bool HandleCastTargetCommad (ChatHandler *handler, SpellInfo const *spell, Optional< std::string > triggeredStr)
static bool HandleCastDestCommand (ChatHandler *handler, SpellInfo const *spell, float x, float y, float z, Optional< std::string > triggeredStr)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
cast_commandscript()
cast_commandscript::cast_commandscript () inline
: CommandScript("cast_commandscript") { }
Member Function Documentation
CheckSpellCastResult()
static bool cast_commandscript::CheckSpellCastResult (ChatHandler * handler, SpellCastResult result) inline static
    {
        if (result != SPELL_CAST_OK)
        {
            handler->PSendSysMessage(LANG_CMD_CAST_ERROR_CODE, EnumUtils::ToTitle(SpellCastResult(result)), result);
            return false;
        }
        return true;
    }
References LANG_CMD_CAST_ERROR_CODE, ChatHandler::PSendSysMessage(), SPELL_CAST_OK, and EnumUtils::ToTitle().
Referenced by HandleCastBackCommand(), HandleCastCommand(), HandleCastDestCommand(), HandleCastDistCommand(), HandleCastSelfCommand(), and HandleCastTargetCommad().
CheckSpellExistsAndIsValid()
static bool cast_commandscript::CheckSpellExistsAndIsValid (ChatHandler * handler, SpellInfo const * spell) inline static
    {
        if (!spell)
        {
            handler->SendErrorMessage(LANG_COMMAND_NOSPELLFOUND);
            return false;
        }
        if (!SpellMgr::IsSpellValid(spell))
        {
            handler->SendErrorMessage(LANG_COMMAND_SPELL_BROKEN, spell->Id);
            return false;
        }
        return true;
    }
References SpellInfo::Id, SpellMgr::IsSpellValid(), LANG_COMMAND_NOSPELLFOUND, LANG_COMMAND_SPELL_BROKEN, and ChatHandler::SendErrorMessage().
Referenced by HandleCastBackCommand(), HandleCastCommand(), HandleCastDestCommand(), HandleCastDistCommand(), HandleCastSelfCommand(), and HandleCastTargetCommad().
GetCommands()
ChatCommandTable cast_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable castCommandTable =
        {
            { "back",   HandleCastBackCommand,  SEC_GAMEMASTER, Console::No },
            { "dist",   HandleCastDistCommand,  SEC_GAMEMASTER, Console::No },
            { "self",   HandleCastSelfCommand,  SEC_GAMEMASTER, Console::No },
            { "target", HandleCastTargetCommad, SEC_GAMEMASTER, Console::No },
            { "dest",   HandleCastDestCommand,  SEC_GAMEMASTER, Console::No },
            { "",       HandleCastCommand,      SEC_GAMEMASTER, Console::No }
        };
        static ChatCommandTable commandTable =
        {
            { "cast", castCommandTable }
        };
        return commandTable;
    }
References HandleCastBackCommand(), HandleCastCommand(), HandleCastDestCommand(), HandleCastDistCommand(), HandleCastSelfCommand(), HandleCastTargetCommad(), and SEC_GAMEMASTER.
GetTriggerFlags()
static Optional< TriggerCastFlags > cast_commandscript::GetTriggerFlags (Optional< std::string > triggeredStr) inline static
    {
        if (triggeredStr)
        {
            if (StringStartsWith("triggered", *triggeredStr)) // check if "triggered" starts with *triggeredStr (e.g. "trig", "trigger", etc.)
                return TRIGGERED_FULL_DEBUG_MASK;
            else
                return std::nullopt;
        }
        return TRIGGERED_NONE;
    }
References StringStartsWith(), TRIGGERED_FULL_DEBUG_MASK, and TRIGGERED_NONE.
Referenced by HandleCastBackCommand(), HandleCastCommand(), HandleCastDestCommand(), HandleCastDistCommand(), HandleCastSelfCommand(), and HandleCastTargetCommad().
HandleCastBackCommand()
static bool cast_commandscript::HandleCastBackCommand (ChatHandler * handler, SpellInfo const * spell, Optional< std::string > triggeredStr) inline static
    {
        Creature* caster = handler->getSelectedCreature();
        if (!caster)
        {
            handler->SendErrorMessage(LANG_SELECT_CHAR_OR_CREATURE);
            return false;
        }
        if (!CheckSpellExistsAndIsValid(handler, spell))
            return false;
        Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
        if (!triggerFlags)
            return false;
        if (!CheckSpellCastResult(handler, caster->CastSpell(handler->GetSession()->GetPlayer(), spell->Id, *triggerFlags)))
        {
            handler->SetSentErrorMessage(true);
            return false;
        }
        return true;
    }
References Unit::CastSpell(), CheckSpellCastResult(), CheckSpellExistsAndIsValid(), WorldSession::GetPlayer(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), GetTriggerFlags(), SpellInfo::Id, LANG_SELECT_CHAR_OR_CREATURE, ChatHandler::SendErrorMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().
HandleCastCommand()
static bool cast_commandscript::HandleCastCommand (ChatHandler * handler, SpellInfo const * spell, Optional< std::string > triggeredStr) inline static
    {
        Unit* target = handler->getSelectedUnit();
        if (!target)
        {
            handler->SendErrorMessage(LANG_SELECT_CHAR_OR_CREATURE);
            return false;
        }
        if (!CheckSpellExistsAndIsValid(handler, spell))
            return false;
        Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
        if (!triggerFlags)
            return false;
        if (!CheckSpellCastResult(handler, handler->GetSession()->GetPlayer()->CastSpell(target, spell->Id, *triggerFlags)))
        {
            handler->SetSentErrorMessage(true);
            return false;
        }
        return true;
    }
References Unit::CastSpell(), CheckSpellCastResult(), CheckSpellExistsAndIsValid(), WorldSession::GetPlayer(), ChatHandler::getSelectedUnit(), ChatHandler::GetSession(), GetTriggerFlags(), SpellInfo::Id, LANG_SELECT_CHAR_OR_CREATURE, ChatHandler::SendErrorMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().
HandleCastDestCommand()
static bool cast_commandscript::HandleCastDestCommand (ChatHandler * handler, SpellInfo const * spell, float x, float y, float z, Optional< std::string > triggeredStr) inline static
    {
        Unit* caster = handler->getSelectedUnit();
        if (!caster)
        {
            handler->SendErrorMessage(LANG_SELECT_CHAR_OR_CREATURE);
            return false;
        }
        if (!CheckSpellExistsAndIsValid(handler, spell))
            return false;
        Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
        if (!triggerFlags)
            return false;
        if (!CheckSpellCastResult(handler, caster->CastSpell(x, y, z, spell->Id, *triggerFlags)))
        {
            handler->SetSentErrorMessage(true);
            return false;
        }
        return true;
    }
References Unit::CastSpell(), CheckSpellCastResult(), CheckSpellExistsAndIsValid(), ChatHandler::getSelectedUnit(), GetTriggerFlags(), SpellInfo::Id, LANG_SELECT_CHAR_OR_CREATURE, ChatHandler::SendErrorMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().
HandleCastDistCommand()
static bool cast_commandscript::HandleCastDistCommand (ChatHandler * handler, SpellInfo const * spell, float dist, Optional< std::string > triggeredStr) inline static
    {
        if (!CheckSpellExistsAndIsValid(handler, spell))
            return false;
        Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
        if (!triggerFlags)
            return false;
        float x, y, z;
        handler->GetSession()->GetPlayer()->GetClosePoint(x, y, z, dist);
        if (!CheckSpellCastResult(handler, handler->GetSession()->GetPlayer()->CastSpell(x, y, z, spell->Id, *triggerFlags)))
        {
            handler->SetSentErrorMessage(true);
            return false;
        }
        return true;
    }
References Unit::CastSpell(), CheckSpellCastResult(), CheckSpellExistsAndIsValid(), WorldObject::GetClosePoint(), WorldSession::GetPlayer(), ChatHandler::GetSession(), GetTriggerFlags(), SpellInfo::Id, and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().
HandleCastSelfCommand()
static bool cast_commandscript::HandleCastSelfCommand (ChatHandler * handler, SpellInfo const * spell, Optional< std::string > triggeredStr) inline static
    {
        Unit* target = handler->getSelectedUnit();
        if (!target)
        {
            handler->SendErrorMessage(LANG_SELECT_CHAR_OR_CREATURE);
            return false;
        }
        if (!CheckSpellExistsAndIsValid(handler, spell))
            return false;
        Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
        if (!triggerFlags)
            return false;
        if (!CheckSpellCastResult(handler, target->CastSpell(target, spell->Id, *triggerFlags)))
        {
            handler->SetSentErrorMessage(true);
            return false;
        }
        return true;
    }
References Unit::CastSpell(), CheckSpellCastResult(), CheckSpellExistsAndIsValid(), ChatHandler::getSelectedUnit(), GetTriggerFlags(), SpellInfo::Id, LANG_SELECT_CHAR_OR_CREATURE, ChatHandler::SendErrorMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().
HandleCastTargetCommad()
static bool cast_commandscript::HandleCastTargetCommad (ChatHandler * handler, SpellInfo const * spell, Optional< std::string > triggeredStr) inline static
    {
        Creature* caster = handler->getSelectedCreature();
        if (!caster)
        {
            handler->SendErrorMessage(LANG_SELECT_CHAR_OR_CREATURE);
            return false;
        }
        if (!caster->GetVictim())
        {
            handler->SendErrorMessage(LANG_SELECTED_TARGET_NOT_HAVE_VICTIM);
            return false;
        }
        if (!CheckSpellExistsAndIsValid(handler, spell))
            return false;
        Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
        if (!triggerFlags)
            return false;
        if (!CheckSpellCastResult(handler, caster->CastSpell(caster->GetVictim(), spell->Id, *triggerFlags)))
        {
            handler->SetSentErrorMessage(true);
            return false;
        }
        return true;
    }
References Unit::CastSpell(), CheckSpellCastResult(), CheckSpellExistsAndIsValid(), ChatHandler::getSelectedCreature(), GetTriggerFlags(), Unit::GetVictim(), SpellInfo::Id, LANG_SELECT_CHAR_OR_CREATURE, LANG_SELECTED_TARGET_NOT_HAVE_VICTIM, ChatHandler::SendErrorMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().