AzerothCore: instance_hyjal::instance_mount_hyjal_InstanceMapScript Struct Reference
instance_hyjal::instance_mount_hyjal_InstanceMapScript Struct Reference
Public Member Functions
instance_mount_hyjal_InstanceMapScript (Map *map)
void Initialize () override
void OnGameObjectCreate (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnUnitDeath (Unit *unit) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
void ScheduleWaves (Milliseconds, uint8 startWaves, uint8 maxWaves, Milliseconds timerptr[])
void Update (uint32 diff) override
void OnPlayerInWaterStateUpdate (Player *player, bool inWater) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
int32 trash
uint8 _currentWave
uint8 _bossWave
uint8 _retreat
GuidSet _encounterNPCs
GuidSet _summonedNPCs
GuidSet _baseAlliance
GuidSet _baseHorde
GuidVector _infernalTargets
GuidSet _baseNightElf
GuidSet _ancientGemAlliance
GuidSet _ancientGemHorde
GuidSet _roaringFlameAlliance
GuidSet _roaringFlameHorde
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_mount_hyjal_InstanceMapScript()
instance_hyjal::instance_mount_hyjal_InstanceMapScript::instance_mount_hyjal_InstanceMapScript (Map * map) inline
                                                         : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(EncounterCount);
            LoadDoorData(doorData);
            LoadObjectData(creatureData, nullptr);
        }
References creatureData, DataHeader, doorData, EncounterCount, InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
GetData()
uint32 instance_hyjal::instance_mount_hyjal_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
            case DATA_WAVE_STATUS:
                return _currentWave;
                break;
            case DATA_BOSS_WAVE:
                return _bossWave;
            }
            return 0;
        }
References DATA_BOSS_WAVE, and DATA_WAVE_STATUS.
Initialize()
void instance_hyjal::instance_mount_hyjal_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            _bossWave = TO_BE_DECIDED;
            _retreat = 0;
            trash = 0;
            _currentWave = 0;
            _encounterNPCs.clear();
            _summonedNPCs.clear();
            _baseAlliance.clear();
            _baseHorde.clear();
            _infernalTargets.clear();
            _baseNightElf.clear();
            _roaringFlameAlliance.clear();
            _roaringFlameHorde.clear();
            _ancientGemAlliance.clear();
            _ancientGemHorde.clear();
        }
References _ancientGemAlliance, _ancientGemHorde, _baseAlliance, _baseHorde, _baseNightElf, _bossWave, _currentWave, _encounterNPCs, _infernalTargets, _retreat, _roaringFlameAlliance, _roaringFlameHorde, _summonedNPCs, TO_BE_DECIDED, and trash.
OnCreatureCreate()
void instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                    // Alliance base
                case NPC_ALLIANCE_PEASANT:
                case NPC_ALLIANCE_KNIGHT:
                case NPC_ALLIANCE_FOOTMAN:
                case NPC_ALLIANCE_RIFLEMAN:
                case NPC_ALLIANCE_PRIEST:
                case NPC_ALLIANCE_SORCERESS:
                case NPC_JAINA:
                    _baseAlliance.insert(creature->GetGUID());
                    break;
                    // Horde base
                case NPC_HORDE_HEADHUNTER:
                case NPC_HORDE_SHAMAN:
                case NPC_HORDE_GRUNT:
                case NPC_HORDE_HEALING_WARD:
                case NPC_TAUREN_WARRIOR:
                case NPC_HORDE_WITCH_DOCTOR:
                case NPC_HORDE_PEON:
                case NPC_THRALL:
                    _baseHorde.insert(creature->GetGUID());
                    break;
                    // Elf base
                case NPC_DRUID_OF_THE_TALON:
                case NPC_DRUID_OF_THE_CLAW:
                case NPC_NELF_ANCIENT_PROT:
                case NPC_NELF_ANCIENT_OF_LORE:
                case NPC_NELF_ANCIENT_OF_WAR:
                case NPC_NELF_ARCHER:
                case NPC_NELF_HUNTRESS:
                case NPC_DRYAD:
                case NPC_TYRANDE:
                    _baseNightElf.insert(creature->GetGUID());
                    break;
                case NPC_INFERNAL_TARGET:
                    _infernalTargets.push_back(creature->GetGUID());
                    break;
                case NPC_WINTERCHILL:
                case NPC_ANETHERON:
                case NPC_KAZROGAL:
                case NPC_AZGALOR:
                case NPC_NECRO:
                case NPC_ABOMI:
                case NPC_GHOUL:
                case NPC_BANSH:
                case NPC_CRYPT:
                case NPC_STALK:
                case NPC_GARGO:
                case NPC_FROST:
                case NPC_INFER:
                    if (_bossWave != TO_BE_DECIDED)
                        creature->AI()->DoAction(_bossWave);
                    else if (_retreat)
                        creature->AI()->DoAction(_retreat);
                    if (creature->IsSummon() && _bossWave != TO_BE_DECIDED)
                    {
                        DoUpdateWorldState(WORLD_STATE_ENEMYCOUNT, ++trash);    // Update the instance wave count on new trash spawn
                        _encounterNPCs.insert(creature->GetGUID());             // Used for despawning on wipe
                    }
                    break;
                case NPC_TOWERING_INFERNAL:
                case NPC_LESSER_DOOMGUARD:
                case NPC_DIRE_WOLF:
                case NPC_GUARDIAN_ELEMENTAL:
                    if (creature->IsSummon())
                    {
                        _summonedNPCs.insert(creature->GetGUID());
                    }
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References _baseAlliance, _baseHorde, _baseNightElf, _bossWave, _encounterNPCs, _infernalTargets, _retreat, _summonedNPCs, Creature::AI(), UnitAI::DoAction(), InstanceScript::DoUpdateWorldState(), Object::GetEntry(), Object::GetGUID(), Unit::IsSummon(), NPC_ABOMI, NPC_ALLIANCE_FOOTMAN, NPC_ALLIANCE_KNIGHT, NPC_ALLIANCE_PEASANT, NPC_ALLIANCE_PRIEST, NPC_ALLIANCE_RIFLEMAN, NPC_ALLIANCE_SORCERESS, NPC_ANETHERON, NPC_AZGALOR, NPC_BANSH, NPC_CRYPT, NPC_DIRE_WOLF, NPC_DRUID_OF_THE_CLAW, NPC_DRUID_OF_THE_TALON, NPC_DRYAD, NPC_FROST, NPC_GARGO, NPC_GHOUL, NPC_GUARDIAN_ELEMENTAL, NPC_HORDE_GRUNT, NPC_HORDE_HEADHUNTER, NPC_HORDE_HEALING_WARD, NPC_HORDE_PEON, NPC_HORDE_SHAMAN, NPC_HORDE_WITCH_DOCTOR, NPC_INFER, NPC_INFERNAL_TARGET, NPC_JAINA, NPC_KAZROGAL, NPC_LESSER_DOOMGUARD, NPC_NECRO, NPC_NELF_ANCIENT_OF_LORE, NPC_NELF_ANCIENT_OF_WAR, NPC_NELF_ANCIENT_PROT, NPC_NELF_ARCHER, NPC_NELF_HUNTRESS, NPC_STALK, NPC_TAUREN_WARRIOR, NPC_THRALL, NPC_TOWERING_INFERNAL, NPC_TYRANDE, NPC_WINTERCHILL, InstanceScript::OnCreatureCreate(), TO_BE_DECIDED, trash, and WORLD_STATE_ENEMYCOUNT.
OnGameObjectCreate()
void instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_ANCIENT_GEM:
                    if (go->GetPositionY() > -2500.f)
                        _ancientGemAlliance.insert(go->GetGUID());
                    else
                        _ancientGemHorde.insert(go->GetGUID());
                    go->DespawnOrUnsummon();
                    break;
                case GO_FLAME:
                    if (go->GetPositionX() < 5360.f)
                        _roaringFlameAlliance.insert(go->GetGUID());
                    else
                        _roaringFlameHorde.insert(go->GetGUID());
                    go->DespawnOrUnsummon();
                    break;
            }
            InstanceScript::OnGameObjectCreate(go);
        }
References _ancientGemAlliance, _ancientGemHorde, _roaringFlameAlliance, _roaringFlameHorde, GameObject::DespawnOrUnsummon(), Object::GetEntry(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), GO_ANCIENT_GEM, GO_FLAME, and InstanceScript::OnGameObjectCreate().
OnPlayerInWaterStateUpdate()
void instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnPlayerInWaterStateUpdate (Player * player, bool inWater) inline override virtual
Reimplemented from InstanceScript.
        {
            if (inWater && player->GetAreaId() == AREA_NORDRASSIL)
            {
                player->CastSpell(player, SPELL_ETERNAL_SILENCE, true);
            }
        }
References AREA_NORDRASSIL, Unit::CastSpell(), WorldObject::GetAreaId(), and SPELL_ETERNAL_SILENCE.
OnUnitDeath()
void instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            InstanceScript::OnUnitDeath(unit);
            if (Creature* creature = unit->ToCreature())
            {
                switch (creature->GetEntry())
                {
                    case NPC_NECRO:
                    case NPC_ABOMI:
                    case NPC_GHOUL:
                    case NPC_BANSH:
                    case NPC_CRYPT:
                    case NPC_GARGO:
                    case NPC_FROST:
                    case NPC_INFER:
                    case NPC_STALK:
                        if (creature->IsSummon())
{
                            if (_bossWave != TO_BE_DECIDED)
{
                                DoUpdateWorldState(WORLD_STATE_ENEMYCOUNT, --trash);    // Update the instance wave count on new trash death
                                _encounterNPCs.erase(creature->GetGUID());    // Used for despawning on wipe
                                if (trash == 0) // It can reach negatives if trash spawned after a retreat are killed, it shouldn't affect anything. Also happens on retail
                                    SetData(DATA_SPAWN_WAVES, 1);
                            }
                        }
                        break;
                    case NPC_TOWERING_INFERNAL:
                    case NPC_LESSER_DOOMGUARD:
                    case NPC_DIRE_WOLF:
                    case NPC_GUARDIAN_ELEMENTAL:
                        _summonedNPCs.erase(creature->GetGUID());
                        break;
                    case NPC_WINTERCHILL:
                    case NPC_ANETHERON:
                    case NPC_KAZROGAL:
                    case NPC_AZGALOR:
                        if (Creature* jaina = GetCreature(DATA_JAINA))
                            jaina->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        if (Creature* thrall = GetCreature(DATA_THRALL))
                            thrall->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        SetData(DATA_RESET_WAVES, 1);
                        break;
                }
            }
            else if (unit->IsPlayer() && GetBossState(DATA_ARCHIMONDE) == IN_PROGRESS)
            {
                if (Creature* archimonde = GetCreature(DATA_ARCHIMONDE))
                    archimonde->AI()->SetGUID(unit->GetGUID(), GUID_GAIN_SOUL_CHARGE_PLAYER);
            }
        }
References _bossWave, _encounterNPCs, _summonedNPCs, DATA_ARCHIMONDE, DATA_JAINA, DATA_RESET_WAVES, DATA_SPAWN_WAVES, DATA_THRALL, InstanceScript::DoUpdateWorldState(), InstanceScript::GetBossState(), InstanceScript::GetCreature(), Object::GetGUID(), GUID_GAIN_SOUL_CHARGE_PLAYER, IN_PROGRESS, Object::IsPlayer(), NPC_ABOMI, NPC_ANETHERON, NPC_AZGALOR, NPC_BANSH, NPC_CRYPT, NPC_DIRE_WOLF, NPC_FROST, NPC_GARGO, NPC_GHOUL, NPC_GUARDIAN_ELEMENTAL, NPC_INFER, NPC_KAZROGAL, NPC_LESSER_DOOMGUARD, NPC_NECRO, NPC_STALK, NPC_TOWERING_INFERNAL, NPC_WINTERCHILL, ZoneScript::OnUnitDeath(), SetData(), TO_BE_DECIDED, Object::ToCreature(), trash, UNIT_NPC_FLAG_GOSSIP, and WORLD_STATE_ENEMYCOUNT.
ScheduleWaves()
void instance_hyjal::instance_mount_hyjal_InstanceMapScript::ScheduleWaves (Milliseconds , uint8 startWaves, uint8 maxWaves, Milliseconds timerptr[]) inline
        {
            // No overlapping!
            scheduler.CancelGroup(CONTEXT_GROUP_WAVES);
            trash = 0;    // Reset counter here to avoid resetting the counter from scheduled waves. Required because creatures killed for RP events counts towards the kill counter as well, confirmed in Retail.
            scheduler.Schedule(1ms, [this, startWaves, maxWaves, timerptr](TaskContext context)
                {
                    // If all waves reached, cancel scheduling new ones
                    if (_currentWave >= maxWaves)
                        return;
                    instance->SummonCreatureGroup(startWaves + _currentWave);   // _currentWave should be 0 when this function is first called
                    // Check if it's time to summon Infernals
                    if (GetBossState(DATA_KAZROGAL) == DONE && GetBossState(DATA_AZGALOR) != DONE)
                    {
                        switch (_currentWave + 1)
{
                        case 3:
                        case 4:
                        case 7:
                            SetData(DATA_SPAWN_INFERNALS, 1);
                            break;
                        default:
                            break;
                        }
                    }
                    context.Repeat(timerptr[_currentWave]);
                    if (++_currentWave < maxWaves && _bossWave != TO_BE_DECIDED)
                    {
                        DoUpdateWorldState(WORLD_STATE_WAVES, _currentWave);
                        DoUpdateWorldState(WORLD_STATE_ENEMY, 1);
                    }
                    context.SetGroup(CONTEXT_GROUP_WAVES);
                });
        }
References CONTEXT_GROUP_WAVES, DATA_AZGALOR, DATA_KAZROGAL, DATA_SPAWN_INFERNALS, DONE, TaskContext::Repeat(), TaskContext::SetGroup(), TO_BE_DECIDED, WORLD_STATE_ENEMY, and WORLD_STATE_WAVES.
Referenced by SetData().
SetData()
void instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_ALLIANCE_RETREAT:
                    _bossWave = TO_BE_DECIDED;
                    _retreat = DATA_ALLIANCE_RETREAT;
                    // Spawn Ancient Gems
                    for (ObjectGuid const& guid : _ancientGemAlliance)
                        if (GameObject* gem = instance->GetGameObject(guid))
                            gem->Respawn();
                    // Move all alliance NPCs near Jaina (only happens in this base, not Horde's)
                    if (Creature* jaina = GetCreature(DATA_JAINA))
                    {
                        for (ObjectGuid const& guid : _baseAlliance)
{
                            if (Creature* creature = instance->GetCreature(guid))
{
                                if (creature->IsAlive())
{
                                    float x, y, z;
                                    jaina->GetNearPoint(creature, x, y, z, 10.f, 0, jaina->GetAngle(creature));
                                    creature->SetWalk(true);
                                    creature->GetMotionMaster()->MovePoint(1, x, y, z);
                                }
                            }
                        }
                    }
                    // Despawn all alliance NPCs
                    scheduler.Schedule(21000ms, [this](TaskContext)
{
                            for (ObjectGuid const& guid : _baseAlliance)
                                if (Creature* creature = instance->GetCreature(guid))
                                    creature->DespawnOrUnsummon();
                            // Spawn Roaring Flame after a delay
                            scheduler.Schedule(30s, [this](TaskContext)
{
                                    for (ObjectGuid const& guid : _roaringFlameAlliance)
{
                                        if (GameObject* flame = instance->GetGameObject(guid))
                                            flame->Respawn();
                                    }
                                });
                        });
                    // Spawn Overrun waves
                    ScheduleWaves(1ms, START_WAVE_ALLIANCE_RETREAT, MAX_WAVES_RETREAT, hyjalRetreatTimers[0]);
                    SaveToDB();
                    break;
                case DATA_HORDE_RETREAT:
                    _bossWave = TO_BE_DECIDED;
                    _retreat = DATA_HORDE_RETREAT;
                    for (ObjectGuid const& guid : _ancientGemHorde)
                    {
                        if (GameObject* gem = instance->GetGameObject(guid))
                            gem->Respawn();
                    }
                    if (Creature* jaina = GetCreature(DATA_JAINA))
                    {
                        for (ObjectGuid const& guid : _baseHorde)
{
                            if (Creature* creature = instance->GetCreature(guid))
{
                                if (creature->IsAlive())
{
                                    float x, y, z;
                                    jaina->GetNearPoint(creature, x, y, z, 10.f, 0, jaina->GetAngle(creature));
                                    creature->SetWalk(true);
                                    creature->GetMotionMaster()->MovePoint(1, x, y, z);
                                }
                            }
                        }
                    }
                    scheduler.Schedule(21000ms, [this](TaskContext)
{
                            for (ObjectGuid const& guid : _baseHorde)
                                if (Creature* creature = instance->GetCreature(guid))
                                    creature->DespawnOrUnsummon();
                            scheduler.Schedule(30s, [this](TaskContext)
{
                                    for (ObjectGuid const& guid : _roaringFlameHorde)
                                        if (GameObject* flame = instance->GetGameObject(guid))
                                            flame->Respawn();
                                });
                        });
                    ScheduleWaves(1ms, START_WAVE_HORDE_RETREAT, MAX_WAVES_RETREAT, hyjalRetreatTimers[1]);
                    SaveToDB();
                    break;
                case DATA_SPAWN_WAVES:
                    _retreat = 0;
                    if (GetBossState(DATA_WINTERCHILL) != DONE)
                    {
                        if (_bossWave == TO_BE_DECIDED)
                            for (ObjectGuid const& guid : _baseAlliance)
                                if (Creature* creature = instance->GetCreature(guid))
                                    creature->Respawn();
                        _bossWave = DATA_WINTERCHILL;
                        ScheduleWaves(1ms, START_WAVE_WINTERCHILL, MAX_WAVES_STANDARD, hyjalWaveTimers[DATA_WINTERCHILL]);
                    }
                    else if (GetBossState(DATA_ANETHERON) != DONE)
                    {
                        if (_bossWave == TO_BE_DECIDED)
                            for (ObjectGuid const& guid : _baseAlliance)
                                if (Creature* creature = instance->GetCreature(guid))
                                    creature->Respawn();
                        _bossWave = DATA_ANETHERON;
                        ScheduleWaves(1ms, START_WAVE_ANETHERON, MAX_WAVES_STANDARD, hyjalWaveTimers[DATA_ANETHERON]);
                    }
                    else if (GetBossState(DATA_KAZROGAL) != DONE)
                    {
                        if (_bossWave == TO_BE_DECIDED)
                            for (ObjectGuid const& guid : _baseHorde)
                                if (Creature* creature = instance->GetCreature(guid))
                                    creature->Respawn();
                        _bossWave = DATA_KAZROGAL;
                        ScheduleWaves(1ms, START_WAVE_KAZROGAL, MAX_WAVES_STANDARD, hyjalWaveTimers[DATA_KAZROGAL]);
                    }
                    else if (GetBossState(DATA_AZGALOR) != DONE)
                    {
                        if (_bossWave == TO_BE_DECIDED)
                            for (ObjectGuid const& guid : _baseHorde)
                                if (Creature* creature = instance->GetCreature(guid))
                                    creature->Respawn();
                        _bossWave = DATA_AZGALOR;
                        ScheduleWaves(1ms, START_WAVE_AZGALOR, MAX_WAVES_STANDARD, hyjalWaveTimers[DATA_AZGALOR]);
                    }
                    else if (GetBossState(DATA_ARCHIMONDE) != DONE)
                    {
                        _bossWave = DATA_ARCHIMONDE;
                        ScheduleWaves(1ms, START_WAVE_NIGHT_ELF, MAX_WAVES_NIGHT_ELF, hyjalNightElfWaveTimers[0]);
                    }
                    if (_bossWave != TO_BE_DECIDED)
                    {
                        DoUpdateWorldState(WORLD_STATE_WAVES, 0);
                        scheduler.Schedule(30s, [this](TaskContext context)
{
                            if (IsEncounterInProgress())
{
                                // Reset the instance if its empty.
                                // This is necessary because bosses get stuck fighting unreachable mobs.
                                // Remove this when we are sure pathing no longer causes this.
                                if (!instance->GetPlayersCountExceptGMs())
                                    SetData(DATA_RESET_ALLIANCE, 0);
                                else
                                    context.Repeat();
                            }
                        });
                    }
                    break;
                case DATA_SPAWN_INFERNALS:
                {
                    uint8 doubleInfernalCount = 2;
                    // Uses SmartAI
                    for (ObjectGuid const& guid : _infernalTargets)
                    {
                        if (Creature* target = instance->GetCreature(guid))
{
                            if (doubleInfernalCount > 0)
{
                                target->AI()->SetData(DATA_SPAWN_INFERNALS, 2); // Spawns 2 infernals, as there are only 6 spawns, some summon 2
                                doubleInfernalCount--;
                            }
                            else
                                target->AI()->SetData(DATA_SPAWN_INFERNALS, 1);
                        }
                    }
                }
                    break;
                case DATA_RESET_NIGHT_ELF:
                    if (Creature* archimonde = GetCreature(DATA_ARCHIMONDE))
                        archimonde->DespawnOrUnsummon(0s, 300s);
                    [[fallthrough]];
                case DATA_RESET_ALLIANCE:
                case DATA_RESET_HORDE:
                    if (GetBossState(DATA_ANETHERON) != DONE)
                    {
                        for (ObjectGuid const& guid : _baseAlliance)
                            if (Creature* creature = instance->GetCreature(guid))
                                creature->DespawnOrUnsummon(0s, 300s);
                    }
                    if (GetBossState(DATA_AZGALOR) != DONE)
                    {
                        for (ObjectGuid const& guid : _baseHorde)
                            if (Creature* creature = instance->GetCreature(guid))
                                creature->DespawnOrUnsummon(0s, 300s);
                    }
                    for (ObjectGuid const& guid : _baseNightElf)
                        if (Creature* creature = instance->GetCreature(guid))
                            creature->DespawnOrUnsummon(0s, 300s);
                    for (ObjectGuid const& guid : _encounterNPCs)
                        if (Creature* creature = instance->GetCreature(guid))
                            creature->DespawnOrUnsummon();
                    // also force despawn boss summons
                    for (ObjectGuid const& guid : _summonedNPCs)
                        if (Creature* creature = instance->GetCreature(guid))
                            creature->DespawnOrUnsummon();
                    if (_bossWave != TO_BE_DECIDED && (GetBossState(_bossWave) != DONE))
                        SetBossState(_bossWave, NOT_STARTED);
                    SetData(DATA_RESET_WAVES, 0);
                    break;
                case DATA_RESET_WAVES:
                    scheduler.CancelGroup(CONTEXT_GROUP_WAVES);
                    _encounterNPCs.clear();
                    _summonedNPCs.clear();
                    _currentWave = 0;
                    trash = 0;
                    _bossWave = TO_BE_DECIDED;
                    _retreat = 0;
                    DoUpdateWorldState(WORLD_STATE_WAVES, _currentWave);
                    DoUpdateWorldState(WORLD_STATE_ENEMY, trash);
                    DoUpdateWorldState(WORLD_STATE_ENEMYCOUNT, trash);
                    break;
            }
            if (data == DONE)
            {
                SaveToDB();
            }
        }
References _ancientGemAlliance, _ancientGemHorde, _baseAlliance, _baseHorde, _baseNightElf, _bossWave, _currentWave, _encounterNPCs, _infernalTargets, _retreat, _summonedNPCs, TaskScheduler::CancelGroup(), CONTEXT_GROUP_WAVES, DATA_ALLIANCE_RETREAT, DATA_ANETHERON, DATA_ARCHIMONDE, DATA_AZGALOR, DATA_HORDE_RETREAT, DATA_JAINA, DATA_KAZROGAL, DATA_RESET_ALLIANCE, DATA_RESET_HORDE, DATA_RESET_NIGHT_ELF, DATA_RESET_WAVES, DATA_SPAWN_INFERNALS, DATA_SPAWN_WAVES, DATA_WINTERCHILL, DONE, InstanceScript::DoUpdateWorldState(), InstanceScript::GetBossState(), Map::GetCreature(), InstanceScript::GetCreature(), Map::GetGameObject(), Map::GetPlayersCountExceptGMs(), hyjalNightElfWaveTimers, hyjalRetreatTimers, hyjalWaveTimers, InstanceScript::instance, InstanceScript::IsEncounterInProgress(), MAX_WAVES_NIGHT_ELF, MAX_WAVES_RETREAT, MAX_WAVES_STANDARD, NOT_STARTED, TaskContext::Repeat(), InstanceScript::SaveToDB(), TaskScheduler::Schedule(), InstanceScript::scheduler, ScheduleWaves(), InstanceScript::SetBossState(), SetData(), START_WAVE_ALLIANCE_RETREAT, START_WAVE_ANETHERON, START_WAVE_AZGALOR, START_WAVE_HORDE_RETREAT, START_WAVE_KAZROGAL, START_WAVE_NIGHT_ELF, START_WAVE_WINTERCHILL, TO_BE_DECIDED, trash, WORLD_STATE_ENEMY, WORLD_STATE_ENEMYCOUNT, and WORLD_STATE_WAVES.
Referenced by OnUnitDeath(), and SetData().
Update()
void instance_hyjal::instance_mount_hyjal_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            scheduler.Update(diff);
        }
Member Data Documentation
_ancientGemAlliance
GuidSet instance_hyjal::instance_mount_hyjal_InstanceMapScript::_ancientGemAlliance protected
Referenced by Initialize(), OnGameObjectCreate(), and SetData().
_ancientGemHorde
GuidSet instance_hyjal::instance_mount_hyjal_InstanceMapScript::_ancientGemHorde protected
Referenced by Initialize(), OnGameObjectCreate(), and SetData().
_baseAlliance
GuidSet instance_hyjal::instance_mount_hyjal_InstanceMapScript::_baseAlliance protected
Referenced by Initialize(), OnCreatureCreate(), and SetData().
_baseHorde
GuidSet instance_hyjal::instance_mount_hyjal_InstanceMapScript::_baseHorde protected
Referenced by Initialize(), OnCreatureCreate(), and SetData().
_baseNightElf
GuidSet instance_hyjal::instance_mount_hyjal_InstanceMapScript::_baseNightElf protected
Referenced by Initialize(), OnCreatureCreate(), and SetData().
_bossWave
uint8 instance_hyjal::instance_mount_hyjal_InstanceMapScript::_bossWave protected
Referenced by Initialize(), OnCreatureCreate(), OnUnitDeath(), and SetData().
_currentWave
uint8 instance_hyjal::instance_mount_hyjal_InstanceMapScript::_currentWave protected
Referenced by Initialize(), and SetData().
_encounterNPCs
GuidSet instance_hyjal::instance_mount_hyjal_InstanceMapScript::_encounterNPCs protected
Referenced by Initialize(), OnCreatureCreate(), OnUnitDeath(), and SetData().
_infernalTargets
GuidVector instance_hyjal::instance_mount_hyjal_InstanceMapScript::_infernalTargets protected
Referenced by Initialize(), OnCreatureCreate(), and SetData().
_retreat
uint8 instance_hyjal::instance_mount_hyjal_InstanceMapScript::_retreat protected
Referenced by Initialize(), OnCreatureCreate(), and SetData().
_roaringFlameAlliance
GuidSet instance_hyjal::instance_mount_hyjal_InstanceMapScript::_roaringFlameAlliance protected
Referenced by Initialize(), and OnGameObjectCreate().
_roaringFlameHorde
GuidSet instance_hyjal::instance_mount_hyjal_InstanceMapScript::_roaringFlameHorde protected
Referenced by Initialize(), and OnGameObjectCreate().
_summonedNPCs
GuidSet instance_hyjal::instance_mount_hyjal_InstanceMapScript::_summonedNPCs protected
Referenced by Initialize(), OnCreatureCreate(), OnUnitDeath(), and SetData().
trash
int32 instance_hyjal::instance_mount_hyjal_InstanceMapScript::trash protected
Referenced by Initialize(), OnCreatureCreate(), OnUnitDeath(), and SetData().