AzerothCore: ReflectEvent Class Reference
ReflectEvent Class Reference
#include "Spell.h"
Public Member Functions
ReflectEvent (Unit *caster, ObjectGuid targetGUID, SpellInfo const *spellInfo)
bool Execute (uint64 e_time, uint32 p_time) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Protected Attributes
Unit * _caster
ObjectGuid _targetGUID
SpellInfo const * _spellInfo
Detailed Description
Constructor & Destructor Documentation
ReflectEvent()
ReflectEvent::ReflectEvent (Unit * caster, ObjectGuid targetGUID, SpellInfo const * spellInfo) inline
: _caster(caster), _targetGUID(targetGUID), _spellInfo(spellInfo) { }
Member Function Documentation
Execute()
bool ReflectEvent::Execute (uint64 e_time, uint32 p_time) override virtual
Reimplemented from BasicEvent.
{
    Unit* target = ObjectAccessor::GetUnit(*_caster, _targetGUID);
    if (target && _caster->IsInMap(target))
        Unit::ProcDamageAndSpell(_caster, target, PROC_FLAG_NONE, PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_NEG, PROC_EX_REFLECT, 1, BASE_ATTACK, _spellInfo);
    return true;
}
References _caster, _spellInfo, _targetGUID, BASE_ATTACK, ObjectAccessor::GetUnit(), WorldObject::IsInMap(), PROC_EX_REFLECT, PROC_FLAG_NONE, PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_NEG, and Unit::ProcDamageAndSpell().
Member Data Documentation
_caster
Unit* ReflectEvent::_caster protected
Referenced by Execute().
_spellInfo
SpellInfo const* ReflectEvent::_spellInfo protected
Referenced by Execute().
_targetGUID
ObjectGuid ReflectEvent::_targetGUID protected
Referenced by Execute().