AzerothCore: boss_victor_nefarius::boss_victor_nefariusAI Struct Reference
boss_victor_nefarius::boss_victor_nefariusAI Struct Reference
Public Member Functions
boss_victor_nefariusAI (Creature *creature)
void Initialize ()
void Reset () override
void JustReachedHome () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void DoAction (int32 action) override
void JustDied (Unit *) override
void BeginEvent ()
void SetData (uint32 type, uint32 data) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void sGossipSelect (Player *player, uint32 sender, uint32 action) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint32 KilledAdds
uint32 _nefarianRightTunnel
uint32 _nefarianLeftTunnel
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_victor_nefariusAI()
boss_victor_nefarius::boss_victor_nefariusAI::boss_victor_nefariusAI (Creature * creature) inline
                                                   : BossAI(creature, DATA_NEFARIAN)
        {
            Initialize();
            _nefarianLeftTunnel = instance->GetData(DATA_NEFARIAN_LEFT_TUNNEL);
            _nefarianRightTunnel = instance->GetData(DATA_NEFARIAN_RIGHT_TUNNEL);
            if (!_nefarianLeftTunnel || !_nefarianRightTunnel)
            {
                // Victor Nefarius weekly mechanic drakonid spawn
                // Pick 2 drakonids and keep them for the whole save duration (the drakonids can't be repeated).
                std::vector<uint32> nefarianDrakonidSpawners = { NPC_BLACK_SPAWNER, NPC_BLUE_SPAWNER, NPC_BRONZE_SPAWNER, NPC_GREEN_SPAWNER, NPC_RED_SPAWNER };
                Acore::Containers::RandomResize(nefarianDrakonidSpawners, 2);
                _nefarianRightTunnel = nefarianDrakonidSpawners[0];
                _nefarianLeftTunnel = nefarianDrakonidSpawners[1];
                // save it to instance
                instance->SetData(DATA_NEFARIAN_LEFT_TUNNEL, _nefarianLeftTunnel);
                instance->SetData(DATA_NEFARIAN_RIGHT_TUNNEL, _nefarianRightTunnel);
            }
        }
References _nefarianLeftTunnel, _nefarianRightTunnel, DATA_NEFARIAN_LEFT_TUNNEL, DATA_NEFARIAN_RIGHT_TUNNEL, ZoneScript::GetData(), Initialize(), BossAI::instance, NPC_BLACK_SPAWNER, NPC_BLUE_SPAWNER, NPC_BRONZE_SPAWNER, NPC_GREEN_SPAWNER, NPC_RED_SPAWNER, Acore::Containers::RandomResize(), and ZoneScript::SetData().
Member Function Documentation
BeginEvent()
void boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent () inline
        {
            _JustEngagedWith();
            Talk(SAY_GAMESBEGIN_2);
            DoCast(me, SPELL_NEFARIANS_BARRIER);
            me->SetCombatMovement(false);
            me->SetImmuneToPC(false);
            AttackStart(SelectTarget(SelectTargetMethod::Random, 0, 200.f, true));
            events.ScheduleEvent(EVENT_SHADOWBLINK, 500ms);
            events.ScheduleEvent(EVENT_SHADOW_BOLT, 3s);
            events.ScheduleEvent(EVENT_SHADOW_BOLT_VOLLEY, 13s, 15s);
            events.ScheduleEvent(EVENT_FEAR, 10s, 20s);
            events.ScheduleEvent(EVENT_SILENCE, 20s, 25s);
            events.ScheduleEvent(EVENT_MIND_CONTROL, 30s, 35s);
            events.ScheduleEvent(EVENT_SPAWN_ADDS, 10s);
        }
References BossAI::_JustEngagedWith(), ScriptedAI::AttackStart(), UnitAI::DoCast(), EVENT_FEAR, EVENT_MIND_CONTROL, EVENT_SHADOW_BOLT, EVENT_SHADOW_BOLT_VOLLEY, EVENT_SHADOWBLINK, EVENT_SILENCE, EVENT_SPAWN_ADDS, ScriptedAI::me, SAY_GAMESBEGIN_2, UnitAI::SelectTarget(), Creature::SetCombatMovement(), Unit::SetImmuneToPC(), and SPELL_NEFARIANS_BARRIER.
Referenced by UpdateAI().
DoAction()
void boss_victor_nefarius::boss_victor_nefariusAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == ACTION_RESET)
            {
                me->RemoveAura(SPELL_ROOT_SELF);
                summons.DespawnAll();
            }
            if (action == ACTION_ADD_KILLED)
            {
                KilledAdds++;
                if (KilledAdds == MAX_DRAKONID_KILLED)
                {
                    if (Creature* nefarian = me->SummonCreature(NPC_NEFARIAN, NefarianSpawn))
                    {
                        nefarian->setActive(true);
                        nefarian->SetCanFly(true);
                        nefarian->SetDisableGravity(true);
                        nefarian->GetMotionMaster()->MovePath(NEFARIAN_PATH, false);
                    }
                    events.Reset();
                    DoCastSelf(SPELL_ROOT_SELF, true);
                    me->SetVisible(false);
                    // Stop spawning adds
                    EntryCheckPredicate pred(_nefarianRightTunnel);
                    summons.DoAction(ACTION_SPAWNER_STOP, pred);
                    EntryCheckPredicate pred2(_nefarianLeftTunnel);
                    summons.DoAction(ACTION_SPAWNER_STOP, pred2);
                }
            }
        }
References _nefarianLeftTunnel, _nefarianRightTunnel, ACTION_ADD_KILLED, ACTION_RESET, ACTION_SPAWNER_STOP, SummonList::DespawnAll(), SummonList::DoAction(), UnitAI::DoCastSelf(), KilledAdds, MAX_DRAKONID_KILLED, ScriptedAI::me, NEFARIAN_PATH, NefarianSpawn, NPC_NEFARIAN, Unit::RemoveAura(), Unit::SetVisible(), SPELL_ROOT_SELF, WorldObject::SummonCreature(), and BossAI::summons.
Initialize()
void boss_victor_nefarius::boss_victor_nefariusAI::Initialize () inline
        {
            KilledAdds = 0;
        }
References KilledAdds.
Referenced by boss_victor_nefariusAI(), and Reset().
JustDied()
void boss_victor_nefarius::boss_victor_nefariusAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            instance->SetBossState(DATA_NEFARIAN, DONE);
            instance->SaveToDB();
        }
References DATA_NEFARIAN, DONE, BossAI::instance, InstanceScript::SaveToDB(), and InstanceScript::SetBossState().
JustReachedHome()
void boss_victor_nefarius::boss_victor_nefariusAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
        {
            Reset();
        }
References Reset().
JustSummoned()
void boss_victor_nefarius::boss_victor_nefariusAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            if (summon->GetEntry() != NPC_NEFARIAN)
            {
                BossAI::JustSummoned(summon);
            }
        }
References Object::GetEntry(), BossAI::JustSummoned(), and NPC_NEFARIAN.
Reset()
void boss_victor_nefarius::boss_victor_nefariusAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            Initialize();
            if (me->GetMapId() == 469)
            {
                if (Creature* nefarian = me->FindNearestCreature(NPC_NEFARIAN, 1000.0f, true))
                {
                    // Nefarian is spawned and he didn't finish his intro path yet, despawn it manually.
                    if (nefarian->GetMotionMaster()->GetCurrentMovementGeneratorType() == MovementGeneratorType::WAYPOINT_MOTION_TYPE)
                    {
                        nefarian->DespawnOrUnsummon();
                    }
                    std::list<GameObject*> drakonidBones;
                    me->GetGameObjectListWithEntryInGrid(drakonidBones, GO_DRAKONID_BONES, DEFAULT_VISIBILITY_INSTANCE);
                    for (auto const& bones : drakonidBones)
                    {
                        bones->DespawnOrUnsummon();
                    }
                }
                else
                {
                    _Reset();
                }
                me->SetVisible(true);
                me->SetPhaseMask(1, true);
                me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                me->SetFaction(FACTION_FRIENDLY);
                me->SetStandState(UNIT_STAND_STATE_SIT_HIGH_CHAIR);
                me->RemoveAura(SPELL_NEFARIANS_BARRIER);
                me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            }
        }
References BossAI::_Reset(), DEFAULT_VISIBILITY_INSTANCE, FACTION_FRIENDLY, WorldObject::FindNearestCreature(), WorldObject::GetGameObjectListWithEntryInGrid(), WorldLocation::GetMapId(), GO_DRAKONID_BONES, Initialize(), ScriptedAI::me, NPC_NEFARIAN, Unit::RemoveAura(), Unit::RemoveUnitFlag(), Unit::SetFaction(), Unit::SetNpcFlag(), Unit::SetPhaseMask(), Unit::SetStandState(), Unit::SetVisible(), SPELL_NEFARIANS_BARRIER, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_FLAG_GOSSIP, and UNIT_STAND_STATE_SIT_HIGH_CHAIR.
Referenced by JustReachedHome().
SetData()
void boss_victor_nefarius::boss_victor_nefariusAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
        {
            if (type == 1 && data == 1)
            {
                me->StopMoving();
                events.ScheduleEvent(EVENT_PATH_2, 9s);
            }
            if (type == 1 && data == 2)
                events.ScheduleEvent(EVENT_SUCCESS_1, 5s);
        }
References EVENT_PATH_2, EVENT_SUCCESS_1, ScriptedAI::me, and Unit::StopMoving().
sGossipSelect()
void boss_victor_nefarius::boss_victor_nefariusAI::sGossipSelect (Player * player, uint32 sender, uint32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (sender == GOSSIP_ID && action == GOSSIP_OPTION_ID)
            {
                // pussywizard:
                InstanceScript* instance = player->GetInstanceScript();
                if (!instance || instance->GetBossState(DATA_NEFARIAN) == DONE)
                    return;
                CloseGossipMenuFor(player);
                Talk(SAY_GAMESBEGIN_1);
                events.ScheduleEvent(EVENT_START_EVENT, 4s);
                me->SetFaction(FACTION_DRAGONFLIGHT_BLACK);
                me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                me->SetStandState(UNIT_STAND_STATE_STAND);
                me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                me->SetImmuneToPC(true);
            }
        }
References CloseGossipMenuFor(), DATA_NEFARIAN, DONE, EVENT_START_EVENT, FACTION_DRAGONFLIGHT_BLACK, InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), GOSSIP_ID, GOSSIP_OPTION_ID, BossAI::instance, ScriptedAI::me, Unit::RemoveNpcFlag(), SAY_GAMESBEGIN_1, Unit::SetFaction(), Unit::SetImmuneToPC(), Unit::SetStandState(), Unit::SetUnitFlag(), UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_FLAG_GOSSIP, and UNIT_STAND_STATE_STAND.
SummonedCreatureDies()
void boss_victor_nefarius::boss_victor_nefariusAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            if (summon->GetEntry() == NPC_NEFARIAN)
            {
                summons.DespawnEntry(_nefarianLeftTunnel);
                summons.DespawnEntry(_nefarianRightTunnel);
                me->KillSelf();
            }
        }
References _nefarianLeftTunnel, _nefarianRightTunnel, SummonList::DespawnEntry(), Object::GetEntry(), Unit::KillSelf(), ScriptedAI::me, NPC_NEFARIAN, and BossAI::summons.
UpdateAI()
void boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            if (!UpdateVictim())
            {
                events.Update(diff);
                while (uint32 eventId = events.ExecuteEvent())
                {
                    switch (eventId)
                    {
                        case EVENT_PATH_2:
                            me->GetMotionMaster()->MovePath(NEFARIUS_PATH_2, false);
                            events.ScheduleEvent(EVENT_CHAOS_1, 7s);
                            break;
                        case EVENT_CHAOS_1:
                            if (Creature* gyth = me->FindNearestCreature(NPC_GYTH, 75.0f, true))
{
                                me->SetFacingToObject(gyth);
                                Talk(SAY_CHAOS_SPELL);
                            }
                            events.ScheduleEvent(EVENT_CHAOS_2, 2s);
                            break;
                        case EVENT_CHAOS_2:
                            DoCast(SPELL_CHROMATIC_CHAOS);
                            me->SetFacingTo(1.570796f);
                            break;
                        case EVENT_SUCCESS_1:
                            if (Unit* player = me->SelectNearestPlayer(60.0f))
{
                                me->SetFacingToObject(player);
                                Talk(SAY_SUCCESS);
                                if (GameObject* portcullis1 = me->FindNearestGameObject(GO_PORTCULLIS_ACTIVE, 65.0f))
                                    portcullis1->SetGoState(GO_STATE_ACTIVE);
                                if (GameObject* portcullis2 = me->FindNearestGameObject(GO_PORTCULLIS_TOBOSSROOMS, 80.0f))
                                    portcullis2->SetGoState(GO_STATE_ACTIVE);
                            }
                            events.ScheduleEvent(EVENT_SUCCESS_2, 4s);
                            break;
                        case EVENT_SUCCESS_2:
                            DoCast(me, SPELL_VAELASTRASZZ_SPAWN);
                            me->DespawnOrUnsummon(1000);
                            break;
                        case EVENT_PATH_3:
                            me->GetMotionMaster()->MovePath(NEFARIUS_PATH_3, false);
                            break;
                        case EVENT_START_EVENT:
                            BeginEvent();
                            break;
                        default:
                            break;
                    }
                }
                return;
            }
            // Only do this if we haven't spawned nefarian yet
            if (UpdateVictim() && KilledAdds <= MAX_DRAKONID_KILLED)
            {
                events.Update(diff);
                if (me->HasUnitState(UNIT_STATE_CASTING))
                    return;
                while (uint32 eventId = events.ExecuteEvent())
                {
                    switch (eventId)
                    {
                        case EVENT_SHADOW_BOLT:
                            DoCastRandomTarget(SPELL_SHADOWBOLT, 0, 150.f);
                            events.ScheduleEvent(EVENT_SHADOW_BOLT, 2s, 4s);
                            break;
                        case EVENT_SHADOW_BOLT_VOLLEY:
                            DoCastAOE(SPELL_SHADOWBOLT_VOLLEY);
                            events.ScheduleEvent(EVENT_SHADOW_BOLT_VOLLEY, 19s, 25s);
                            break;
                        case EVENT_FEAR:
                            DoCastRandomTarget(SPELL_FEAR, 0, 40.0f);
                            events.ScheduleEvent(EVENT_FEAR, 10s, 20s);
                            break;
                        case EVENT_SILENCE:
                            DoCastRandomTarget(SPELL_SILENCE, 0, 150.f);
                            events.ScheduleEvent(EVENT_SILENCE, 14s,23s);
                            break;
                        case EVENT_MIND_CONTROL:
                            DoCastRandomTarget(SPELL_SHADOW_COMMAND, 0, 40.0f);
                            events.ScheduleEvent(EVENT_MIND_CONTROL, 24s, 30s);
                            break;
                        case EVENT_SHADOWBLINK:
                            DoCastSelf(SPELL_SHADOWBLINK);
                            events.ScheduleEvent(EVENT_SHADOWBLINK, 30s, 40s);
                            break;
                        case EVENT_SPAWN_ADDS:
                            // Spawn the spawners.
                            me->SummonCreature(_nefarianLeftTunnel, spawnerPositions[0]);
                            me->SummonCreature(_nefarianRightTunnel, spawnerPositions[1]);
                            break;
                    }
                    if (me->HasUnitState(UNIT_STATE_CASTING))
                        return;
                }
            }
        }
References _nefarianLeftTunnel, _nefarianRightTunnel, BeginEvent(), Creature::DespawnOrUnsummon(), UnitAI::DoCast(), UnitAI::DoCastAOE(), UnitAI::DoCastRandomTarget(), UnitAI::DoCastSelf(), EVENT_CHAOS_1, EVENT_CHAOS_2, EVENT_FEAR, EVENT_MIND_CONTROL, EVENT_PATH_2, EVENT_PATH_3, EVENT_SHADOW_BOLT, EVENT_SHADOW_BOLT_VOLLEY, EVENT_SHADOWBLINK, EVENT_SILENCE, EVENT_SPAWN_ADDS, EVENT_START_EVENT, EVENT_SUCCESS_1, EVENT_SUCCESS_2, WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), Unit::GetMotionMaster(), GO_PORTCULLIS_ACTIVE, GO_PORTCULLIS_TOBOSSROOMS, GO_STATE_ACTIVE, Unit::HasUnitState(), KilledAdds, MAX_DRAKONID_KILLED, ScriptedAI::me, MotionMaster::MovePath(), NEFARIUS_PATH_2, NEFARIUS_PATH_3, NPC_GYTH, SAY_CHAOS_SPELL, SAY_SUCCESS, WorldObject::SelectNearestPlayer(), Unit::SetFacingTo(), Unit::SetFacingToObject(), spawnerPositions, SPELL_CHROMATIC_CHAOS, SPELL_FEAR, SPELL_SHADOW_COMMAND, SPELL_SHADOWBLINK, SPELL_SHADOWBOLT, SPELL_SHADOWBOLT_VOLLEY, SPELL_SILENCE, SPELL_VAELASTRASZZ_SPAWN, WorldObject::SummonCreature(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_nefarianLeftTunnel
uint32 boss_victor_nefarius::boss_victor_nefariusAI::_nefarianLeftTunnel private
Referenced by boss_victor_nefariusAI(), DoAction(), SummonedCreatureDies(), and UpdateAI().
_nefarianRightTunnel
uint32 boss_victor_nefarius::boss_victor_nefariusAI::_nefarianRightTunnel private
Referenced by boss_victor_nefariusAI(), DoAction(), SummonedCreatureDies(), and UpdateAI().
KilledAdds
uint32 boss_victor_nefarius::boss_victor_nefariusAI::KilledAdds private
Referenced by DoAction(), Initialize(), and UpdateAI().