AzerothCore: spell_rog_cheat_death Class Reference
spell_rog_cheat_death Class Reference
Private Member Functions
PrepareAuraScript (spell_rog_cheat_death)
bool Validate (SpellInfo const *) override
bool Load () override
void CalculateAmount (AuraEffect const *, int32 &amount, bool &)
void Absorb (AuraEffect *, DamageInfo &dmgInfo, uint32 &absorbAmount)
void Register () override
Private Attributes
uint32 absorbChance
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
Absorb()
void spell_rog_cheat_death::Absorb (AuraEffect * , DamageInfo & dmgInfo, uint32 & absorbAmount) inline private
    {
        Player* target = GetTarget()->ToPlayer();
        if (dmgInfo.GetDamage() < target->GetHealth() || target->HasSpellCooldown(SPELL_ROGUE_CHEAT_DEATH_COOLDOWN) || !roll_chance_i(absorbChance))
            return;
        target->CastSpell(target, SPELL_ROGUE_CHEAT_DEATH_COOLDOWN, true);
        target->CastSpell(target, SPELL_ROGUE_CHEATING_DEATH, true);
        target->AddSpellCooldown(SPELL_ROGUE_CHEAT_DEATH_COOLDOWN, 0, MINUTE * IN_MILLISECONDS);
        uint32 health10 = target->CountPctFromMaxHealth(10);
        // hp > 10% - absorb hp till 10%
        if (target->GetHealth() > health10)
            absorbAmount = dmgInfo.GetDamage() - target->GetHealth() + health10;
        // hp lower than 10% - absorb everything
        else
            absorbAmount = dmgInfo.GetDamage();
    }
References absorbChance, Player::AddSpellCooldown(), Unit::CastSpell(), Unit::CountPctFromMaxHealth(), DamageInfo::GetDamage(), Unit::GetHealth(), AuraScript::GetTarget(), Player::HasSpellCooldown(), IN_MILLISECONDS, MINUTE, roll_chance_i(), SPELL_ROGUE_CHEAT_DEATH_COOLDOWN, SPELL_ROGUE_CHEATING_DEATH, and Object::ToPlayer().
Referenced by Register().
CalculateAmount()
void spell_rog_cheat_death::CalculateAmount (AuraEffect const * , int32 & amount, bool &) inline private
    {
        // Set absorbtion amount to unlimited
        amount = -1;
    }
Referenced by Register().
Load()
bool spell_rog_cheat_death::Load () inline override private virtual
Reimplemented from _SpellScript.
    {
        absorbChance = GetSpellInfo()->Effects[EFFECT_0].CalcValue();
        return GetUnitOwner()->ToPlayer();
    }
References absorbChance, EFFECT_0, SpellInfo::Effects, AuraScript::GetSpellInfo(), AuraScript::GetUnitOwner(), and Object::ToPlayer().
PrepareAuraScript()
spell_rog_cheat_death::PrepareAuraScript (spell_rog_cheat_death) private
Register()
void spell_rog_cheat_death::Register () inline override private virtual
Implements _SpellScript.
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_rog_cheat_death::CalculateAmount, EFFECT_0, SPELL_AURA_SCHOOL_ABSORB);
        OnEffectAbsorb += AuraEffectAbsorbFn(spell_rog_cheat_death::Absorb, EFFECT_0);
    }
References Absorb(), AuraEffectAbsorbFn, AuraEffectCalcAmountFn, CalculateAmount(), AuraScript::DoEffectCalcAmount, EFFECT_0, AuraScript::OnEffectAbsorb, and SPELL_AURA_SCHOOL_ABSORB.
Validate()
bool spell_rog_cheat_death::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo({ SPELL_ROGUE_CHEAT_DEATH_COOLDOWN, SPELL_ROGUE_CHEATING_DEATH });
    }
References SPELL_ROGUE_CHEAT_DEATH_COOLDOWN, SPELL_ROGUE_CHEATING_DEATH, and _SpellScript::ValidateSpellInfo().
Member Data Documentation
absorbChance
uint32 spell_rog_cheat_death::absorbChance private
Referenced by Absorb(), and Load().