AzerothCore: ShadowTrapLKTargetSelector Struct Reference
ShadowTrapLKTargetSelector Struct Reference
Public Member Functions
ShadowTrapLKTargetSelector (Creature *source, bool playerOnly=true, bool reqLOS=false, float maxDist=0.0f)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
bool _playerOnly
bool _reqLOS
float _maxDist
Detailed Description
Constructor & Destructor Documentation
ShadowTrapLKTargetSelector()
ShadowTrapLKTargetSelector::ShadowTrapLKTargetSelector (Creature * source, bool playerOnly = true, bool reqLOS = false, float maxDist = 0.0f) inline
: _source(source), _playerOnly(playerOnly), _reqLOS(reqLOS), _maxDist(maxDist) { }
Member Function Documentation
operator()()
bool ShadowTrapLKTargetSelector::operator() (Unit const * target) const inline
    {
        if (!target)
            return false;
        if (!target->IsAlive())
            return false;
        if (_playerOnly && !target->IsPlayer())
            return false;
        if (_maxDist && _source->GetExactDist(target) > _maxDist)
            return false;
        if (_reqLOS && !_source->IsWithinLOSInMap(target))
            return false;
        return true;
    }
References _maxDist, _playerOnly, _reqLOS, _source, Position::GetExactDist(), Unit::IsAlive(), Object::IsPlayer(), and WorldObject::IsWithinLOSInMap().
Member Data Documentation
_maxDist
float ShadowTrapLKTargetSelector::_maxDist private
Referenced by operator()().
_playerOnly
bool ShadowTrapLKTargetSelector::_playerOnly private
Referenced by operator()().
_reqLOS
bool ShadowTrapLKTargetSelector::_reqLOS private
Referenced by operator()().
_source
Creature const* ShadowTrapLKTargetSelector::_source private
Referenced by operator()().