AzerothCore: AreaTrigger_at_sholazar_waygate Class Reference
AreaTrigger_at_sholazar_waygate Class Reference
Public Member Functions
AreaTrigger_at_sholazar_waygate ()
bool OnTrigger (Player *player, AreaTrigger const *trigger) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
AreaTrigger_at_sholazar_waygate()
AreaTrigger_at_sholazar_waygate::AreaTrigger_at_sholazar_waygate () inline
: AreaTriggerScript("at_sholazar_waygate") { }
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_sholazar_waygate::OnTrigger (Player * player, AreaTrigger const * trigger) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (!player->isDead() && (player->GetQuestStatus(QUEST_MEETING_A_GREAT_ONE) != QUEST_STATUS_NONE ||
                                  (player->GetQuestStatus(QUEST_THE_MAKERS_OVERLOOK) == QUEST_STATUS_REWARDED && player->GetQuestStatus(QUEST_THE_MAKERS_PERCH) == QUEST_STATUS_REWARDED)))
        {
            switch (trigger->entry)
            {
                case AT_SHOLAZAR:
                    player->CastSpell(player, SPELL_SHOLAZAR_TO_UNGORO_TELEPORT, true);
                    break;
                case AT_UNGORO:
                    player->CastSpell(player, SPELL_UNGORO_TO_SHOLAZAR_TELEPORT, true);
                    break;
            }
        }
        return false;
    }
References AT_SHOLAZAR, AT_UNGORO, Unit::CastSpell(), AreaTrigger::entry, Player::GetQuestStatus(), Unit::isDead(), QUEST_MEETING_A_GREAT_ONE, QUEST_STATUS_NONE, QUEST_STATUS_REWARDED, QUEST_THE_MAKERS_OVERLOOK, QUEST_THE_MAKERS_PERCH, SPELL_SHOLAZAR_TO_UNGORO_TELEPORT, and SPELL_UNGORO_TO_SHOLAZAR_TELEPORT.