AzerothCore: SafeUnitPointer Class Reference
SafeUnitPointer Class Reference
#include "UnitUtils.h"
Public Member Functions
SafeUnitPointer (Unit *defVal)
SafeUnitPointer (const SafeUnitPointer &)
void Initialize (Unit *defVal)
~SafeUnitPointer ()
void SetPointedTo (Unit *u)
void UnitDeleted ()
Unit * operator-> () const
void operator= (Unit *u)
operator Unit * () const
Private Attributes
Unit * ptr
Unit * defaultValue
Detailed Description
Constructor & Destructor Documentation
SafeUnitPointer() [1/2]
SafeUnitPointer::SafeUnitPointer (Unit * defVal) inline explicit
: ptr(defVal), defaultValue(defVal) {}
SafeUnitPointer() [2/2]
SafeUnitPointer::SafeUnitPointer (const SafeUnitPointer &) inline
{ ABORT(); }
References ABORT.
~SafeUnitPointer()
SafeUnitPointer::~SafeUnitPointer ()
{
    if (ptr != defaultValue && ptr) ptr->RemovePointedBy(this);
    ptr = defaultValue;
}
References defaultValue, ptr, and Unit::RemovePointedBy().
Member Function Documentation
Initialize()
void SafeUnitPointer::Initialize (Unit * defVal) inline
{ defaultValue = defVal; ptr = defVal; }
References defaultValue, and ptr.
Referenced by Player::Player().
operator Unit *()
SafeUnitPointer::operator Unit * () const inline
{ return ptr; }
References ptr.
operator->()
Unit * SafeUnitPointer::operator-> () const inline
{ return ptr; }
References ptr.
operator=()
void SafeUnitPointer::operator= (Unit * u) inline
{ SetPointedTo(u); }
References SetPointedTo().
SetPointedTo()
void SafeUnitPointer::SetPointedTo (Unit * u)
{
    if (ptr != defaultValue && ptr) ptr->RemovePointedBy(this);
    ptr = u;
    if (ptr != defaultValue && ptr) ptr->AddPointedBy(this);
}
References Unit::AddPointedBy(), defaultValue, ptr, and Unit::RemovePointedBy().
Referenced by operator=().
UnitDeleted()
void SafeUnitPointer::UnitDeleted ()
{
    LOG_INFO("misc", "SafeUnitPointer::UnitDeleted !!!");
    if (defaultValue)
    {
        if (Player* p = defaultValue->ToPlayer())
        {
            LOG_INFO("misc", "SafeUnitPointer::UnitDeleted (A1) - {}, {}, {}, {}, {}, {}, {}, {}",
                p->GetGUID().ToString(), p->GetMapId(), p->GetInstanceId(), p->FindMap()->GetId(), p->IsInWorld() ? 1 : 0, p->IsDuringRemoveFromWorld() ? 1 : 0, p->IsBeingTeleported() ? 1 : 0, p->isBeingLoaded() ? 1 : 0);
            if (ptr)
                LOG_INFO("misc", "SafeUnitPointer::UnitDeleted (A2)");
            p->GetSession()->KickPlayer("Unit deleted");
        }
    }
    else if (ptr)
        LOG_INFO("misc", "SafeUnitPointer::UnitDeleted (B1)");
    ptr = defaultValue;
}
References defaultValue, LOG_INFO, ptr, and Object::ToPlayer().
Member Data Documentation
defaultValue
Unit* SafeUnitPointer::defaultValue private
Referenced by Initialize(), SetPointedTo(), UnitDeleted(), and ~SafeUnitPointer().
ptr
Unit* SafeUnitPointer::ptr private
Referenced by Initialize(), operator Unit *(), operator->(), SetPointedTo(), UnitDeleted(), and ~SafeUnitPointer().