AzerothCore: TimeTrackerSmall Struct Reference
TimeTrackerSmall Struct Reference
#include "Timer.h"
Public Member Functions
TimeTrackerSmall (int32 expiry=0)
void Update (int32 diff)
bool Passed () const
void Reset (int32 interval)
int32 GetExpiry () const
Private Attributes
int32 i_expiryTime
Detailed Description
Constructor & Destructor Documentation
TimeTrackerSmall()
TimeTrackerSmall::TimeTrackerSmall (int32 expiry = 0) inline
        : i_expiryTime(expiry)
    {
    }
Member Function Documentation
GetExpiry()
int32 TimeTrackerSmall::GetExpiry () const inline
    {
        return i_expiryTime;
    }
References i_expiryTime.
Passed()
bool TimeTrackerSmall::Passed () const inline
    {
        return i_expiryTime <= 0;
    }
References i_expiryTime.
Referenced by MotionTransport::Update(), and DynTreeImpl::update().
Reset()
void TimeTrackerSmall::Reset (int32 interval) inline
    {
        i_expiryTime = interval;
    }
References i_expiryTime.
Referenced by MotionTransport::Update(), and DynTreeImpl::update().
Update()
void TimeTrackerSmall::Update (int32 diff) inline
    {
        i_expiryTime -= diff;
    }
References i_expiryTime.
Referenced by MotionTransport::Update(), and DynTreeImpl::update().
Member Data Documentation
i_expiryTime
int32 TimeTrackerSmall::i_expiryTime private
Referenced by GetExpiry(), Passed(), Reset(), and Update().