AzerothCore: npc_harrison_jones::npc_harrison_jonesAI Struct Reference
npc_harrison_jones::npc_harrison_jonesAI Struct Reference
Public Member Functions
npc_harrison_jonesAI (Creature *creature)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void sGossipSelect (Player *player, uint32 sender, uint32 action) override
void SpellHit (Unit *, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
uint8 _gongEvent
uint32 _gongTimer
ObjectGuid uiTargetGUID
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_harrison_jonesAI()
npc_harrison_jones::npc_harrison_jonesAI::npc_harrison_jonesAI (Creature * creature) inline
                                                 : ScriptedAI(creature)
        {
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
JustEngagedWith()
void npc_harrison_jones::npc_harrison_jonesAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
{ }
Reset()
void npc_harrison_jones::npc_harrison_jonesAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _gongEvent = 0;
            _gongTimer = 0;
            uiTargetGUID.Clear();
        }
References _gongEvent, _gongTimer, ObjectGuid::Clear(), and uiTargetGUID.
sGossipSelect()
void npc_harrison_jones::npc_harrison_jonesAI::sGossipSelect (Player * player, uint32 sender, uint32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (me->GetCreatureTemplate()->GossipMenuId == sender && !action)
            {
                CloseGossipMenuFor(player);
                me->SetFacingToObject(player);
                me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                Talk(SAY_HARRISON_0);
                _gongEvent = GONG_EVENT_1;
                _gongTimer = 4000;
            }
        }
References _gongEvent, _gongTimer, CloseGossipMenuFor(), Creature::GetCreatureTemplate(), GONG_EVENT_1, CreatureTemplate::GossipMenuId, ScriptedAI::me, Unit::RemoveNpcFlag(), SAY_HARRISON_0, Unit::SetFacingToObject(), and UNIT_NPC_FLAG_GOSSIP.
SpellHit()
void npc_harrison_jones::npc_harrison_jonesAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spell->Id == SPELL_COSMETIC_SPEAR_THROW)
            {
                me->RemoveAllAuras();
                me->SetEntry(NPC_HARRISON_JONES_2);
                me->SetDisplayId(MODEL_HARRISON_JONES_2);
                me->SetTarget();
                me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_DEAD);
                me->SetDynamicFlag(UNIT_DYNFLAG_DEAD);
                instance->SetData(DATA_GONGEVENT, DONE);
            }
        }
References DATA_GONGEVENT, DONE, SpellInfo::Id, instance, ScriptedAI::me, MODEL_HARRISON_JONES_2, NPC_HARRISON_JONES_2, Unit::RemoveAllAuras(), Object::SetByteValue(), ZoneScript::SetData(), Creature::SetDisplayId(), Object::SetDynamicFlag(), Object::SetEntry(), Creature::SetTarget(), SPELL_COSMETIC_SPEAR_THROW, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_DYNFLAG_DEAD, UNIT_FIELD_BYTES_1, and UNIT_STAND_STATE_DEAD.
UpdateAI()
void npc_harrison_jones::npc_harrison_jonesAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (_gongEvent)
            {
                if (_gongTimer <= diff)
                {
                    switch (_gongEvent)
                    {
                        case GONG_EVENT_1:
                            me->GetMotionMaster()->MovePath(HARRISON_MOVE_1, false);
                            _gongEvent = GONG_EVENT_2;
                            _gongTimer = 12000;
                            break;
                        case GONG_EVENT_2:
                            me->SetFacingTo(6.235659f);
                            Talk(SAY_HARRISON_1);
                            DoCast(me, SPELL_BANGING_THE_GONG);
                            me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(WEAPON_MACE));
                            me->SetSheath(SHEATH_STATE_MELEE);
                            _gongEvent = GONG_EVENT_3;
                            _gongTimer = 4000;
                            break;
                        case GONG_EVENT_3:
                            if (GameObject* gong = me->GetMap()->GetGameObject(instance->GetGuidData(GO_STRANGE_GONG)))
                                gong->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                            _gongEvent = GONG_EVENT_4;
                            _gongTimer = 105000;
                            break;
                        case GONG_EVENT_4:
                            me->RemoveAura(SPELL_BANGING_THE_GONG);
                            if (GameObject* gong = me->GetMap()->GetGameObject(instance->GetGuidData(GO_STRANGE_GONG)))
                                gong->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                            // trigger or gong will need to be scripted to set IN_PROGRESS after enough hits.
                            // This is temp workaround.
                            instance->SetData(DATA_GONGEVENT, IN_PROGRESS); // to be removed.
                            if (instance->GetData(DATA_GONGEVENT) == IN_PROGRESS)
{
                                // Players are Now Saved to instance at SPECIAL (Player should be notified?)
                                me->GetMotionMaster()->MovePath(HARRISON_MOVE_2, false);
                                _gongEvent = GONG_EVENT_5;
                                _gongTimer = 5000;
                            }
                            else
{
                                _gongTimer = 1000;
                                _gongEvent = GONG_EVENT_9;
                            }
                            break;
                        case GONG_EVENT_5:
                            me->SetEntry(NPC_HARRISON_JONES_1);
                            me->SetDisplayId(MODEL_HARRISON_JONES_1);
                            Talk(SAY_HARRISON_2);
                            _gongTimer = 12000;
                            _gongEvent = GONG_EVENT_6;
                            break;
                        case GONG_EVENT_6:
                            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_USE_STANDING);
                            Talk(SAY_HARRISON_3);
                            _gongTimer = 7000;
                            _gongEvent = GONG_EVENT_7;
                            break;
                        case GONG_EVENT_7:
                            if (!uiTargetGUID)
{
                                std::list<Creature*> targetList;
                                GetCreatureListWithEntryInGrid(targetList, me, NPC_AMANISHI_GUARDIAN, 26.0f);
                                if (!targetList.empty())
{
                                    for (std::list<Creature*>::const_iterator itr = targetList.begin(); itr != targetList.end(); ++itr)
{
                                        if (Creature* ptarget = *itr)
{
                                            if (ptarget->GetPositionX() > 120)
{
                                                ptarget->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(WEAPON_SPEAR));
                                                ptarget->SetImmuneToPC(true);
                                                ptarget->SetReactState(REACT_PASSIVE);
                                                ptarget->AI()->SetData(0, 1);
                                            }
                                            else
{
                                                ptarget->SetImmuneToPC(true);
                                                ptarget->SetReactState(REACT_PASSIVE);
                                                ptarget->AI()->SetData(0, 2);
                                            }
                                        }
                                    }
                                }
                            }
                            if (GameObject* gate = me->GetMap()->GetGameObject(instance->GetGuidData(GO_MASSIVE_GATE)))
                                gate->SetGoState(GO_STATE_ACTIVE);
                            _gongTimer = 2000;
                            _gongEvent = GONG_EVENT_8;
                            break;
                        case GONG_EVENT_8:
                            DoCast(me, SPELL_STEALTH);
                            me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(0));
                            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                            me->GetMotionMaster()->MovePath(HARRISON_MOVE_3, false);
                            _gongTimer = 1000;
                            _gongEvent = 0;
                            break;
                        case GONG_EVENT_9:
                            me->GetMotionMaster()->MovePoint(0, 120.687f, 1674.0f, 42.0217f);
                            _gongTimer = 12000;
                            _gongEvent = GONG_EVENT_10;
                            break;
                        case GONG_EVENT_10:
                            me->SetFacingTo(1.59044f);
                            _gongEvent = 11;
                            _gongTimer = 6000;
                            break;
                        case GONG_EVENT_11:
                            me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                            instance->SetData(DATA_GONGEVENT, NOT_STARTED);
                            _gongEvent = 0;
                            _gongTimer = 1000;
                            break;
                    }
                }
                else
                    _gongTimer -= diff;
            }
        }
References _gongEvent, _gongTimer, DATA_GONGEVENT, UnitAI::DoCast(), EMOTE_ONESHOT_NONE, EMOTE_STATE_USE_STANDING, GetCreatureListWithEntryInGrid(), ZoneScript::GetData(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetMotionMaster(), GO_FLAG_NOT_SELECTABLE, GO_MASSIVE_GATE, GO_STATE_ACTIVE, GO_STRANGE_GONG, GONG_EVENT_1, GONG_EVENT_10, GONG_EVENT_11, GONG_EVENT_2, GONG_EVENT_3, GONG_EVENT_4, GONG_EVENT_5, GONG_EVENT_6, GONG_EVENT_7, GONG_EVENT_8, GONG_EVENT_9, HARRISON_MOVE_1, HARRISON_MOVE_2, HARRISON_MOVE_3, IN_PROGRESS, instance, ScriptedAI::me, MODEL_HARRISON_JONES_1, MotionMaster::MovePath(), MotionMaster::MovePoint(), NOT_STARTED, NPC_AMANISHI_GUARDIAN, NPC_HARRISON_JONES_1, REACT_PASSIVE, Unit::RemoveAura(), SAY_HARRISON_1, SAY_HARRISON_2, SAY_HARRISON_3, ZoneScript::SetData(), Creature::SetDisplayId(), Object::SetEntry(), Unit::SetFacingTo(), Unit::SetNpcFlag(), Unit::SetSheath(), Unit::SetUInt32Value(), SHEATH_STATE_MELEE, SPELL_BANGING_THE_GONG, SPELL_STEALTH, uiTargetGUID, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_VIRTUAL_ITEM_SLOT_ID, WEAPON_MACE, and WEAPON_SPEAR.
Member Data Documentation
_gongEvent
uint8 npc_harrison_jones::npc_harrison_jonesAI::_gongEvent
Referenced by Reset(), sGossipSelect(), and UpdateAI().
_gongTimer
uint32 npc_harrison_jones::npc_harrison_jonesAI::_gongTimer
Referenced by Reset(), sGossipSelect(), and UpdateAI().
instance
InstanceScript* npc_harrison_jones::npc_harrison_jonesAI::instance
Referenced by npc_harrison_jonesAI(), SpellHit(), and UpdateAI().
uiTargetGUID
ObjectGuid npc_harrison_jones::npc_harrison_jonesAI::uiTargetGUID
Referenced by Reset(), and UpdateAI().