AzerothCore: azerothcore-wotlk/src/common/Collision/Models/GameObjectModel.cpp File Reference
GameObjectModel.cpp File Reference
#include "GameObjectModel.h"
#include "Log.h"
#include "MapTree.h"
#include "ModelInstance.h"
#include "Timer.h"
#include "VMapDefinitions.h"
#include "VMapFactory.h"
#include "VMapMgr2.h"
#include "WorldModel.h"
Classes
struct GameobjectModelData
Typedefs
typedef std::unordered_map< uint32, GameobjectModelData > ModelList
Functions
void LoadGameObjectModelList (std::string const &dataPath)
Variables
ModelList model_list
Typedef Documentation
ModelList
typedef std::unordered_map<uint32, GameobjectModelData> ModelList
Function Documentation
LoadGameObjectModelList()
void LoadGameObjectModelList (std::string const & dataPath)
{
    uint32 oldMSTime = getMSTime();
    FILE* model_list_file = fopen((dataPath + "vmaps/" + VMAP::GAMEOBJECT_MODELS).c_str(), "rb");
    if (!model_list_file)
    {
        LOG_ERROR("maps", "Unable to open '{}' file.", VMAP::GAMEOBJECT_MODELS);
        return;
    }
    char magic[8];
    if (fread(magic, 1, 8, model_list_file) != 8 || memcmp(magic, VMAP::VMAP_MAGIC, 8) != 0)
    {
        LOG_ERROR("maps", "File '{}' has wrong header, expected {}.", VMAP::GAMEOBJECT_MODELS, VMAP::VMAP_MAGIC);
        fclose(model_list_file);
        return;
    }
    uint32 name_length, displayId;
    uint8 isWmo;
    char buff[500];
    while (true)
    {
        Vector3 v1, v2;
        if (fread(&displayId, sizeof(uint32), 1, model_list_file) != 1)
            if (feof(model_list_file))  // EOF flag is only set after failed reading attempt
            {
                break;
            }
        if (fread(&isWmo, sizeof(uint8), 1, model_list_file) != 1
                || fread(&name_length, sizeof(uint32), 1, model_list_file) != 1
                || name_length >= sizeof(buff)
                || fread(&buff, sizeof(char), name_length, model_list_file) != name_length
                || fread(&v1, sizeof(Vector3), 1, model_list_file) != 1
                || fread(&v2, sizeof(Vector3), 1, model_list_file) != 1)
        {
            LOG_ERROR("maps", "File '{}' seems to be corrupted!", VMAP::GAMEOBJECT_MODELS);
            fclose(model_list_file);
            break;
        }
        if (v1.isNaN() || v2.isNaN())
        {
            LOG_ERROR("maps", "File '{}' Model '{}' has invalid v1{} v2{} values!",
                      VMAP::GAMEOBJECT_MODELS, std::string(buff, name_length), v1.toString(), v2.toString());
            continue;
        }
        model_list.emplace(std::piecewise_construct, std::forward_as_tuple(displayId), std::forward_as_tuple(&buff[0], name_length, v1, v2, isWmo != 0));
    }
    fclose(model_list_file);
    LOG_INFO("server.loading", ">> Loaded {} GameObject Models in {} ms", uint32(model_list.size()), GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References VMAP::GAMEOBJECT_MODELS, getMSTime(), GetMSTimeDiffToNow(), LOG_ERROR, LOG_INFO, model_list, and VMAP::VMAP_MAGIC.
Referenced by World::SetInitialWorldSettings().
Variable Documentation
model_list
ModelList model_list
Referenced by VMAP::TileAssembler::exportGameobjectModels(), ExtractGameobjectModels(), GameObjectModel::initialize(), LoadGameObjectModelList(), and GameObjectModel::UpdatePosition().