AzerothCore: boss_bjarngrim::boss_bjarngrimAI Struct Reference
boss_bjarngrim::boss_bjarngrimAI Struct Reference
Public Member Functions
boss_bjarngrimAI (Creature *creature)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void KilledUnit (Unit *victim) override
void JustDied (Unit *) override
void RemoveStanceAura (uint8 stance)
void RollStance (uint8 stance, uint8 force=0)
void WaypointReached (uint32 Point) override
void UpdateEscortAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
uint8 m_uiStance
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_bjarngrimAI()
boss_bjarngrim::boss_bjarngrimAI::boss_bjarngrimAI (Creature * creature) inline
                                             : npc_escortAI(creature), summons(creature)
        {
            m_pInstance = creature->GetInstanceScript();
            // Init waypoints
            AddWaypoint(1, 1262.18f, 99.3f, 33.5f, 0);
            AddWaypoint(2, 1281.6f, 99.5f, 33.5f, 0);
            AddWaypoint(3, 1311.7f, 99.4f, 40.1f, 0);
            AddWaypoint(4, 1332.5f, 99.7f, 40.18f, 0);
            AddWaypoint(5, 1311.7f, 99.4f, 40.1f, 0);
            AddWaypoint(6, 1281.6f, 99.5f, 33.5f, 0);
            AddWaypoint(7, 1262.18f, 99.3f, 33.5f, 0);
            AddWaypoint(8, 1262, -26.9f, 33.5f, 0);
            AddWaypoint(9, 1281.2f, -26.8f, 33.5f, 0);
            AddWaypoint(10, 1311.3f, -26.9f, 40.03f, 0);
            AddWaypoint(11, 1332, -26.6f, 40.18f, 0);
            AddWaypoint(12, 1311.3f, -26.9f, 40.03f, 0);
            AddWaypoint(13, 1281.2f, -26.8f, 33.5f, 0);
            AddWaypoint(14, 1262, -26.9f, 33.5f, 0);
            Start(true, false, ObjectGuid::Empty, nullptr, false, true);
        }
References npc_escortAI::AddWaypoint(), ObjectGuid::Empty, WorldObject::GetInstanceScript(), m_pInstance, and npc_escortAI::Start().
Member Function Documentation
JustDied()
void boss_bjarngrim::boss_bjarngrimAI::JustDied (Unit *) inline override virtual
Reimplemented from npc_escortAI.
        {
            Talk(SAY_DEATH);
            if (m_pInstance)
                m_pInstance->SetData(TYPE_BJARNGRIM, DONE);
        }
References DONE, m_pInstance, SAY_DEATH, ZoneScript::SetData(), and TYPE_BJARNGRIM.
JustEngagedWith()
void boss_bjarngrim::boss_bjarngrimAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            me->SetInCombatWithZone();
            Talk(SAY_AGGRO);
            events.ScheduleEvent(EVENT_BJARNGRIM_CHANGE_STANCE, 20s, 0);
            // DEFENSIVE STANCE
            events.ScheduleEvent(EVENT_BJARNGRIM_REFLECTION, 8s, STANCE_DEFENSIVE);
            events.ScheduleEvent(EVENT_BJARNGRIM_PUMMEL, 5s, STANCE_DEFENSIVE);
            events.ScheduleEvent(EVENT_BJARNGRIM_KNOCK, 16s, STANCE_DEFENSIVE);
            events.ScheduleEvent(EVENT_BJARNGRIM_IRONFORM, 12s, STANCE_DEFENSIVE);
            // BERSERKER STANCE
            events.ScheduleEvent(EVENT_BJARNGRIM_MORTAL_STRIKE, 24s, STANCE_BERSERKER);
            events.ScheduleEvent(EVENT_BJARNGRIM_WHIRLWIND, 26s, STANCE_BERSERKER);
            // BATTLE STANCE
            events.ScheduleEvent(EVENT_BJARNGRIM_INTERCEPT, 23s, STANCE_BATTLE);
            events.ScheduleEvent(EVENT_BJARNGRIM_CLEAVE, 25s, STANCE_BATTLE);
            events.ScheduleEvent(EVENT_BJARNGRIM_SLAM, 30s, STANCE_BATTLE);
            if (m_pInstance)
            {
                m_pInstance->SetData(TYPE_BJARNGRIM, IN_PROGRESS);
                m_pInstance->SetData(DATA_BJARNGRIM_ACHIEVEMENT, me->HasAura(SPELL_TEMPORARY_ELECTRICAL_CHARGE));
            }
        }
References DATA_BJARNGRIM_ACHIEVEMENT, EVENT_BJARNGRIM_CHANGE_STANCE, EVENT_BJARNGRIM_CLEAVE, EVENT_BJARNGRIM_INTERCEPT, EVENT_BJARNGRIM_IRONFORM, EVENT_BJARNGRIM_KNOCK, EVENT_BJARNGRIM_MORTAL_STRIKE, EVENT_BJARNGRIM_PUMMEL, EVENT_BJARNGRIM_REFLECTION, EVENT_BJARNGRIM_SLAM, EVENT_BJARNGRIM_WHIRLWIND, Unit::HasAura(), IN_PROGRESS, m_pInstance, ScriptedAI::me, SAY_AGGRO, ZoneScript::SetData(), Creature::SetInCombatWithZone(), SPELL_TEMPORARY_ELECTRICAL_CHARGE, STANCE_BATTLE, STANCE_BERSERKER, STANCE_DEFENSIVE, and TYPE_BJARNGRIM.
KilledUnit()
void boss_bjarngrim::boss_bjarngrimAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!victim->IsPlayer())
                return;
            Talk(SAY_SLAY);
        }
References Object::IsPlayer(), and SAY_SLAY.
RemoveStanceAura()
void boss_bjarngrim::boss_bjarngrimAI::RemoveStanceAura (uint8 stance) inline
        {
            switch (stance)
            {
                case STANCE_DEFENSIVE:
                    me->RemoveAura(SPELL_DEFENSIVE_STANCE);
                    me->RemoveAura(SPELL_DEFENSIVE_AURA);
                    break;
                case STANCE_BERSERKER:
                    me->RemoveAura(SPELL_BERSERKER_STANCE);
                    me->RemoveAura(SPELL_BERSERKER_AURA);
                    break;
                case STANCE_BATTLE:
                    me->RemoveAura(SPELL_BATTLE_STANCE);
                    me->RemoveAura(SPELL_BATTLE_AURA);
                    break;
            }
        }
References ScriptedAI::me, Unit::RemoveAura(), SPELL_BATTLE_AURA, SPELL_BATTLE_STANCE, SPELL_BERSERKER_AURA, SPELL_BERSERKER_STANCE, SPELL_DEFENSIVE_AURA, SPELL_DEFENSIVE_STANCE, STANCE_BATTLE, STANCE_BERSERKER, and STANCE_DEFENSIVE.
Referenced by UpdateEscortAI().
Reset()
void boss_bjarngrim::boss_bjarngrimAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Reset();
            summons.DespawnAll();
            for (uint8 i = 0; i < 2; ++i)
                if (Creature* dwarf = me->SummonCreature(NPC_STORMFORGED_LIEUTENANT, me->GetPositionX() + urand(4, 12), me->GetPositionY() + urand(4, 12), me->GetPositionZ()))
                {
                    dwarf->GetMotionMaster()->MoveFollow(me, 3, rand_norm() * 2 * 3.14f);
                    summons.Summon(dwarf);
                }
            me->RemoveAllAuras();
            me->CastSpell(me, SPELL_TEMPORARY_ELECTRICAL_CHARGE, true);
            RollStance(0, STANCE_DEFENSIVE);
            if (m_pInstance)
                m_pInstance->SetData(TYPE_BJARNGRIM, NOT_STARTED);
        }
References Unit::CastSpell(), SummonList::DespawnAll(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), m_pInstance, ScriptedAI::me, NOT_STARTED, NPC_STORMFORGED_LIEUTENANT, rand_norm(), Unit::RemoveAllAuras(), RollStance(), ZoneScript::SetData(), SPELL_TEMPORARY_ELECTRICAL_CHARGE, STANCE_DEFENSIVE, SummonList::Summon(), WorldObject::SummonCreature(), summons, TYPE_BJARNGRIM, and urand().
Referenced by UpdateEscortAI().
RollStance()
void boss_bjarngrim::boss_bjarngrimAI::RollStance (uint8 stance, uint8 force = 0) inline
        {
            if (urand(0, 1))
                stance = (++stance == 4 ? 1 : stance);
            else
                stance = (--stance == 0 ? 3 : stance);
            if (force)
                stance = force;
            switch (stance)
            {
                case STANCE_DEFENSIVE:
                    Talk(SAY_DEFENSIVE_STANCE);
                    me->CastSpell(me, SPELL_DEFENSIVE_STANCE, true);
                    me->CastSpell(me, SPELL_DEFENSIVE_AURA, true);
                    events.DelayEvents(20000, STANCE_BERSERKER);
                    events.DelayEvents(20000, STANCE_BATTLE);
                    SetEquipmentSlots(false, EQUIP_SWORD, EQUIP_SHIELD, EQUIP_NO_CHANGE);
                    break;
                case STANCE_BERSERKER:
                    Talk(SAY_BERSERKER_STANCE);
                    me->CastSpell(me, SPELL_BERSERKER_STANCE, true);
                    me->CastSpell(me, SPELL_BERSERKER_AURA, true);
                    events.DelayEvents(20000, STANCE_DEFENSIVE);
                    events.DelayEvents(20000, STANCE_BATTLE);
                    SetEquipmentSlots(false, EQUIP_SWORD, EQUIP_SWORD, EQUIP_NO_CHANGE);
                    break;
                case STANCE_BATTLE:
                    Talk(SAY_BATTLE_STANCE);
                    me->CastSpell(me, SPELL_BATTLE_STANCE, true);
                    me->CastSpell(me, SPELL_BATTLE_AURA, true);
                    events.DelayEvents(20000, STANCE_BERSERKER);
                    events.DelayEvents(20000, STANCE_DEFENSIVE);
                    SetEquipmentSlots(false, EQUIP_MACE, EQUIP_UNEQUIP, EQUIP_NO_CHANGE);
                    break;
            }
            m_uiStance = stance;
        }
References Unit::CastSpell(), EQUIP_MACE, EQUIP_NO_CHANGE, EQUIP_SHIELD, EQUIP_SWORD, EQUIP_UNEQUIP, m_uiStance, ScriptedAI::me, SAY_BATTLE_STANCE, SAY_BERSERKER_STANCE, SAY_DEFENSIVE_STANCE, ScriptedAI::SetEquipmentSlots(), SPELL_BATTLE_AURA, SPELL_BATTLE_STANCE, SPELL_BERSERKER_AURA, SPELL_BERSERKER_STANCE, SPELL_DEFENSIVE_AURA, SPELL_DEFENSIVE_STANCE, STANCE_BATTLE, STANCE_BERSERKER, STANCE_DEFENSIVE, and urand().
Referenced by Reset(), and UpdateEscortAI().
UpdateEscortAI()
void boss_bjarngrim::boss_bjarngrimAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
        {
            if (!me->IsInCombat())
                return;
            // Return since we have no target
            if (!UpdateVictim())
            {
                Reset();
                return;
            }
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_BJARNGRIM_CHANGE_STANCE:
                    // roll new stance
                    RemoveStanceAura(m_uiStance);
                    RollStance(m_uiStance);
                    events.Repeat(20s);
                    break;
                case EVENT_BJARNGRIM_REFLECTION:
                    me->CastSpell(me, SPELL_BJARNGRIM_REFLETION, true);
                    events.Repeat(8s, 9s);
                    break;
                case EVENT_BJARNGRIM_PUMMEL:
                    me->CastSpell(me->GetVictim(), SPELL_PUMMEL, false);
                    events.Repeat(10s, 11s);
                    break;
                case EVENT_BJARNGRIM_KNOCK:
                    me->CastSpell(me, SPELL_KNOCK_AWAY, false);
                    events.Repeat(20s, 21s);
                    break;
                case EVENT_BJARNGRIM_IRONFORM:
                    me->CastSpell(me, SPELL_IRONFORM, true);
                    events.Repeat(18s, 23s);
                    break;
                case EVENT_BJARNGRIM_MORTAL_STRIKE:
                    me->CastSpell(me->GetVictim(), SPELL_MORTAL_STRIKE, false);
                    events.Repeat(10s);
                    break;
                case EVENT_BJARNGRIM_WHIRLWIND:
                    me->CastSpell(me, SPELL_WHIRLWIND, true);
                    events.Repeat(25s);
                    break;
                case EVENT_BJARNGRIM_INTERCEPT:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random))
                        me->CastSpell(target, SPELL_INTERCEPT, true);
                    events.Repeat(30s);
                    break;
                case EVENT_BJARNGRIM_CLEAVE:
                    me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                    events.Repeat(25s);
                    break;
                case EVENT_BJARNGRIM_SLAM:
                    me->CastSpell(me->GetVictim(), SPELL_SLAM, false);
                    events.Repeat(10s, 12s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_BJARNGRIM_CHANGE_STANCE, EVENT_BJARNGRIM_CLEAVE, EVENT_BJARNGRIM_INTERCEPT, EVENT_BJARNGRIM_IRONFORM, EVENT_BJARNGRIM_KNOCK, EVENT_BJARNGRIM_MORTAL_STRIKE, EVENT_BJARNGRIM_PUMMEL, EVENT_BJARNGRIM_REFLECTION, EVENT_BJARNGRIM_SLAM, EVENT_BJARNGRIM_WHIRLWIND, Unit::GetVictim(), Unit::HasUnitState(), Unit::IsInCombat(), m_uiStance, ScriptedAI::me, RemoveStanceAura(), Reset(), RollStance(), UnitAI::SelectTarget(), SPELL_BJARNGRIM_REFLETION, SPELL_CLEAVE, SPELL_INTERCEPT, SPELL_IRONFORM, SPELL_KNOCK_AWAY, SPELL_MORTAL_STRIKE, SPELL_PUMMEL, SPELL_SLAM, SPELL_WHIRLWIND, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
WaypointReached()
void boss_bjarngrim::boss_bjarngrimAI::WaypointReached (uint32 Point) inline override virtual
Implements npc_escortAI.
        {
            if (Point == 1 || Point == 8)
                me->CastSpell(me, SPELL_TEMPORARY_ELECTRICAL_CHARGE, true);
            else if (Point == 7 || Point == 14)
                me->RemoveAura(SPELL_TEMPORARY_ELECTRICAL_CHARGE);
        }
References Unit::CastSpell(), ScriptedAI::me, Unit::RemoveAura(), and SPELL_TEMPORARY_ELECTRICAL_CHARGE.
Member Data Documentation
events
EventMap boss_bjarngrim::boss_bjarngrimAI::events
m_pInstance
InstanceScript* boss_bjarngrim::boss_bjarngrimAI::m_pInstance
Referenced by boss_bjarngrimAI(), JustDied(), JustEngagedWith(), and Reset().
m_uiStance
uint8 boss_bjarngrim::boss_bjarngrimAI::m_uiStance
Referenced by RollStance(), and UpdateEscortAI().
summons
SummonList boss_bjarngrim::boss_bjarngrimAI::summons
Referenced by Reset().