AzeorthCore: AllItemScript Class Reference
AllItemScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
virtual bool CanItemQuestAccept (Player *, Item *, Quest const *)
virtual bool CanItemUse (Player *, Item *, SpellCastTargets const &)
virtual bool CanItemRemove (Player *, Item *)
virtual bool CanItemExpire (Player *, ItemTemplate const *)
virtual void OnItemGossipSelect (Player *, Item *, uint32, uint32)
virtual void OnItemGossipSelectCode (Player *, Item *, uint32, uint32, const char *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
AllItemScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
AllItemScript()
AllItemScript::AllItemScript (const char * name) protected
                                             : ScriptObject(name)
{
    ScriptRegistry<AllItemScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanItemExpire()
virtual bool AllItemScript::CanItemExpire (Player * , ItemTemplate const *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnItemExpire().
CanItemQuestAccept()
virtual bool AllItemScript::CanItemQuestAccept (Player * , Item * , Quest const *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnQuestAccept().
CanItemRemove()
virtual bool AllItemScript::CanItemRemove (Player * , Item *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnItemRemove().
CanItemUse()
virtual bool AllItemScript::CanItemUse (Player * , Item * , SpellCastTargets const &) inline virtual
{ return false; }
Referenced by ScriptMgr::OnItemUse().
OnItemGossipSelect()
virtual void AllItemScript::OnItemGossipSelect (Player * , Item * , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnGossipSelect().
OnItemGossipSelectCode()
virtual void AllItemScript::OnItemGossipSelectCode (Player * , Item * , uint32 , uint32 , const char *) inline virtual
{ }
Referenced by ScriptMgr::OnGossipSelectCode().