AzerothCore: FrostwingVrykulSearcher Class Reference
FrostwingVrykulSearcher Class Reference
Public Member Functions
FrostwingVrykulSearcher (Creature const *source, float range)
bool operator() (Unit *unit)
Private Attributes
Creature const * _source
float _range
Detailed Description
Constructor & Destructor Documentation
FrostwingVrykulSearcher()
FrostwingVrykulSearcher::FrostwingVrykulSearcher (Creature const * source, float range) inline
: _source(source), _range(range) {}
Member Function Documentation
operator()()
bool FrostwingVrykulSearcher::operator() (Unit * unit) inline
    {
        if (!unit->IsAlive())
            return false;
        switch (unit->GetEntry())
        {
            case NPC_YMIRJAR_BATTLE_MAIDEN:
            case NPC_YMIRJAR_DEATHBRINGER:
            case NPC_YMIRJAR_FROSTBINDER:
            case NPC_YMIRJAR_HUNTRESS:
            case NPC_YMIRJAR_WARLORD:
                break;
            default:
                return false;
        }
        if (!unit->IsWithinDist(_source, _range, false))
            return false;
        return true;
    }
References _range, _source, Object::GetEntry(), Unit::IsAlive(), WorldObject::IsWithinDist(), NPC_YMIRJAR_BATTLE_MAIDEN, NPC_YMIRJAR_DEATHBRINGER, NPC_YMIRJAR_FROSTBINDER, NPC_YMIRJAR_HUNTRESS, and NPC_YMIRJAR_WARLORD.
Member Data Documentation
_range
float FrostwingVrykulSearcher::_range private
Referenced by operator()().
_source
Creature const* FrostwingVrykulSearcher::_source private
Referenced by operator()().