AzerothCore: spell_pal_judgement Class Reference
spell_pal_judgement Class Reference
Public Member Functions
spell_pal_judgement (uint32 spellId)
bool Validate (SpellInfo const *) override
void HandleScriptEffect (SpellEffIndex)
uint32 SealApplication (uint32 correspondingSpellId)
void Register () override
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Private Member Functions
PrepareSpellScript (spell_pal_judgement)
Private Attributes
uint32 const _spellId
Additional Inherited Members
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Constructor & Destructor Documentation
spell_pal_judgement()
spell_pal_judgement::spell_pal_judgement (uint32 spellId) inline
: SpellScript(), _spellId(spellId) { }
Member Function Documentation
HandleScriptEffect()
void spell_pal_judgement::HandleScriptEffect (SpellEffIndex) inline
    {
        uint32 spellId2 = SPELL_PALADIN_JUDGEMENT_DAMAGE;
        // some seals have SPELL_AURA_DUMMY in EFFECT_2
        Unit::AuraEffectList const& auras = GetCaster()->GetAuraEffectsByType(SPELL_AURA_DUMMY);
        for (Unit::AuraEffectList::const_iterator i = auras.begin(); i != auras.end(); ++i)
        {
            if ((*i)->GetSpellInfo()->GetSpellSpecific() == SPELL_SPECIFIC_SEAL && (*i)->GetEffIndex() == EFFECT_2)
                if (sSpellMgr->GetSpellInfo((*i)->GetAmount()))
                {
                    spellId2 = (*i)->GetAmount();
                    break;
                }
        }
        GetCaster()->CastSpell(GetHitUnit(), _spellId, true);
        GetCaster()->CastSpell(GetHitUnit(), spellId2, true);
        // Tier 5 Holy - 2 Set
        if (GetCaster()->HasAura(SPELL_IMPROVED_JUDGEMENT))
        {
            GetCaster()->CastSpell(GetCaster(), SPELL_IMPROVED_JUDGEMENT_ENERGIZE, true);
        }
        // Judgement of the Just
        if (GetCaster()->GetAuraEffect(SPELL_AURA_ADD_FLAT_MODIFIER, SPELLFAMILY_PALADIN, 3015, 0))
        {
            if (GetCaster()->CastSpell(GetHitUnit(), SPELL_JUDGEMENTS_OF_THE_JUST, true) && (spellId2 == SPELL_JUDGEMENT_OF_VENGEANCE_EFFECT || spellId2 == SPELL_JUDGEMENT_OF_CORRUPTION_EFFECT))
            {
                //hidden effect only cast when spellcast of judgements of the just is succesful
                GetCaster()->CastSpell(GetHitUnit(), SealApplication(spellId2), true); //add hidden seal apply effect for vengeance and corruption
            }
        }
    }
References _spellId, Unit::CastSpell(), EFFECT_2, Unit::GetAuraEffectsByType(), SpellScript::GetCaster(), SpellScript::GetHitUnit(), SealApplication(), SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_AURA_DUMMY, SPELL_IMPROVED_JUDGEMENT, SPELL_IMPROVED_JUDGEMENT_ENERGIZE, SPELL_JUDGEMENT_OF_CORRUPTION_EFFECT, SPELL_JUDGEMENT_OF_VENGEANCE_EFFECT, SPELL_JUDGEMENTS_OF_THE_JUST, SPELL_PALADIN_JUDGEMENT_DAMAGE, SPELL_SPECIFIC_SEAL, SPELLFAMILY_PALADIN, and sSpellMgr.
Referenced by Register().
PrepareSpellScript()
spell_pal_judgement::PrepareSpellScript (spell_pal_judgement) private
Register()
void spell_pal_judgement::Register () inline override virtual
Implements _SpellScript.
    {
        OnEffectHitTarget += SpellEffectFn(spell_pal_judgement::HandleScriptEffect, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
    }
References EFFECT_0, HandleScriptEffect(), SpellScript::OnEffectHitTarget, SPELL_EFFECT_SCRIPT_EFFECT, and SpellEffectFn.
SealApplication()
uint32 spell_pal_judgement::SealApplication (uint32 correspondingSpellId) inline
    {
        switch (correspondingSpellId)
        {
            case SPELL_JUDGEMENT_OF_VENGEANCE_EFFECT:
                return SPELL_HOLY_VENGEANCE;
            case SPELL_JUDGEMENT_OF_CORRUPTION_EFFECT:
                return SPELL_BLOOD_CORRUPTION;
            default:
                return 0;
        }
    }
References SPELL_BLOOD_CORRUPTION, SPELL_HOLY_VENGEANCE, SPELL_JUDGEMENT_OF_CORRUPTION_EFFECT, and SPELL_JUDGEMENT_OF_VENGEANCE_EFFECT.
Referenced by HandleScriptEffect().
Validate()
bool spell_pal_judgement::Validate (SpellInfo const *) inline override virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo({ SPELL_PALADIN_JUDGEMENT_DAMAGE, _spellId });
    }
References _spellId, SPELL_PALADIN_JUDGEMENT_DAMAGE, and _SpellScript::ValidateSpellInfo().
Member Data Documentation
_spellId
uint32 const spell_pal_judgement::_spellId private
Referenced by HandleScriptEffect(), and Validate().