AzerothCore: npc_bessy Class Reference
npc_bessy Class Reference
Classes
struct npc_bessyAI
Public Member Functions
npc_bessy ()
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_bessy()
npc_bessy::npc_bessy () inline
: CreatureScript("npc_bessy") { }
Member Function Documentation
GetAI()
CreatureAI * npc_bessy::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return new npc_bessyAI(creature);
    }
OnQuestAccept()
bool npc_bessy::OnQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
    {
        if (quest->GetQuestId() == Q_ALMABTRIEB)
        {
            creature->SetFaction(FACTION_ESCORTEE_N_NEUTRAL_PASSIVE);
            creature->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            creature->AI()->Talk(SAY_BESSY_0);
            CAST_AI(npc_escortAI, (creature->AI()))->Start(true, false, player->GetGUID());
        }
        return true;
    }
References Creature::AI(), CAST_AI, FACTION_ESCORTEE_N_NEUTRAL_PASSIVE, Object::GetGUID(), Quest::GetQuestId(), Q_ALMABTRIEB, Unit::RemoveUnitFlag(), SAY_BESSY_0, Unit::SetFaction(), CreatureAI::Talk(), and UNIT_FLAG_NON_ATTACKABLE.