AzerothCore: Acore::NearestHostileUnitCheck Class Reference
Acore::NearestHostileUnitCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
NearestHostileUnitCheck (Creature const *creature, float dist=0, bool playerOnly=false)
bool operator() (Unit *u)
Private Member Functions
NearestHostileUnitCheck (NearestHostileUnitCheck const &)
Private Attributes
Creature const * me
float m_range
bool i_playerOnly
Detailed Description
Constructor & Destructor Documentation
NearestHostileUnitCheck() [1/2]
Acore::NearestHostileUnitCheck::NearestHostileUnitCheck (Creature const * creature, float dist = 0, bool playerOnly = false) inline explicit
                                                                                                            : me(creature), i_playerOnly(playerOnly)
        {
            m_range = (dist == 0 ? 9999 : dist);
        }
References m_range.
NearestHostileUnitCheck() [2/2]
Acore::NearestHostileUnitCheck::NearestHostileUnitCheck (NearestHostileUnitCheck const &) private
Member Function Documentation
operator()()
bool Acore::NearestHostileUnitCheck::operator() (Unit * u) inline
        {
            if (!me->IsWithinDistInMap(u, m_range, true, false))
                return false;
            if (!me->IsValidAttackTarget(u))
                return false;
            if (i_playerOnly && !u->IsPlayer())
                return false;
            m_range = me->GetDistance(u);   // use found unit range as new range limit for next check
            return true;
        }
References WorldObject::GetDistance(), i_playerOnly, Object::IsPlayer(), Unit::IsValidAttackTarget(), WorldObject::IsWithinDistInMap(), m_range, and me.
Member Data Documentation
i_playerOnly
bool Acore::NearestHostileUnitCheck::i_playerOnly private
Referenced by operator()().
m_range
float Acore::NearestHostileUnitCheck::m_range private
Referenced by NearestHostileUnitCheck(), and operator()().
me
Creature const* Acore::NearestHostileUnitCheck::me private
Referenced by operator()().