AzerothCore: azerothcore-wotlk/src/server/game/Entities/Object/ObjectGuid.h File Reference
ObjectGuid.h File Reference
#include "ByteBuffer.h"
#include "Define.h"
#include <deque>
#include <functional>
#include <list>
#include <set>
#include <unordered_set>
#include <vector>
Classes
struct ObjectGuidTraits< high >
struct PackedGuidReader
class ObjectGuid
class PackedGuid
class ObjectGuidGeneratorBase
class ObjectGuidGenerator< high >
struct std::hash< ObjectGuid >
Namespaces
namespace std
Macros
#define NUM_CLIENT_OBJECT_TYPES 8
#define GUID_TRAIT_GLOBAL(highguid)
#define GUID_TRAIT_MAP_SPECIFIC(highguid)
#define PACKED_GUID_MIN_BUFFER_SIZE 9
Typedefs
typedef std::set< ObjectGuid > GuidSet
typedef std::list< ObjectGuid > GuidList
typedef std::deque< ObjectGuid > GuidDeque
typedef std::vector< ObjectGuid > GuidVector
typedef std::unordered_set< ObjectGuid > GuidUnorderedSet
Enumerations
enum TypeID {
TYPEID_OBJECT = 0 ,
TYPEID_ITEM = 1 ,
TYPEID_CONTAINER = 2 ,
TYPEID_UNIT = 3 ,
TYPEID_PLAYER = 4 ,
TYPEID_GAMEOBJECT = 5 ,
TYPEID_DYNAMICOBJECT = 6 ,
TYPEID_CORPSE = 7
}
enum TypeMask {
TYPEMASK_OBJECT = 0x0001 ,
TYPEMASK_ITEM = 0x0002 ,
TYPEMASK_CONTAINER = 0x0006 ,
TYPEMASK_UNIT = 0x0008 ,
TYPEMASK_PLAYER = 0x0010 ,
TYPEMASK_GAMEOBJECT = 0x0020 ,
TYPEMASK_DYNAMICOBJECT = 0x0040 ,
TYPEMASK_CORPSE = 0x0080 ,
TYPEMASK_SEER = TYPEMASK_PLAYER | TYPEMASK_UNIT | TYPEMASK_DYNAMICOBJECT
}
enum class HighGuid {
Item = 0x4000 ,
Container = 0x4000 ,
Player = 0x0000 ,
GameObject = 0xF110 ,
Transport = 0xF120 ,
Unit = 0xF130 ,
Pet = 0xF140 ,
Vehicle = 0xF150 ,
DynamicObject = 0xF100 ,
Corpse = 0xF101 ,
Mo_Transport = 0x1FC0 ,
Instance = 0x1F40 ,
Group = 0x1F50
}
Functions
ByteBuffer & operator<< (ByteBuffer &buf, ObjectGuid const &guid)
ByteBuffer & operator>> (ByteBuffer &buf, ObjectGuid &guid)
ByteBuffer & operator<< (ByteBuffer &buf, PackedGuid const &guid)
ByteBuffer & operator>> (ByteBuffer &buf, PackedGuidReader const &guid)
Macro Definition Documentation
GUID_TRAIT_GLOBAL
#define GUID_TRAIT_GLOBAL (highguid)
Value:
    template<> struct ObjectGuidTraits<highguid> \
    { \
        static bool const Global = true; \
        static bool const MapSpecific = false; \
    };
GUID_TRAIT_MAP_SPECIFIC
#define GUID_TRAIT_MAP_SPECIFIC (highguid)
Value:
    template<> struct ObjectGuidTraits<highguid> \
    { \
        static bool const Global = false; \
        static bool const MapSpecific = true; \
    };
NUM_CLIENT_OBJECT_TYPES
#define NUM_CLIENT_OBJECT_TYPES 8
PACKED_GUID_MIN_BUFFER_SIZE
#define PACKED_GUID_MIN_BUFFER_SIZE 9
Typedef Documentation
GuidDeque
typedef std::deque<ObjectGuid> GuidDeque
GuidList
typedef std::list<ObjectGuid> GuidList
GuidSet
typedef std::set<ObjectGuid> GuidSet
GuidUnorderedSet
typedef std::unordered_set<ObjectGuid> GuidUnorderedSet
GuidVector
typedef std::vector<ObjectGuid> GuidVector
Enumeration Type Documentation
HighGuid
enum class HighGuid strong
Enumerator
Item
Container
Player
GameObject
Transport
Unit
Pet
Vehicle
DynamicObject
Corpse
Mo_Transport
Instance
Group
{
    Item           = 0x4000,                      // blizz 4000
    Container      = 0x4000,                      // blizz 4000
    Player         = 0x0000,                      // blizz 0000
    GameObject     = 0xF110,                      // blizz F110
    Transport      = 0xF120,                      // blizz F120 (for GAMEOBJECT_TYPE_TRANSPORT)
    Unit           = 0xF130,                      // blizz F130
    Pet            = 0xF140,                      // blizz F140
    Vehicle        = 0xF150,                      // blizz F550
    DynamicObject  = 0xF100,                      // blizz F100
    Corpse         = 0xF101,                      // blizz F100
    Mo_Transport   = 0x1FC0,                      // blizz 1FC0 (for GAMEOBJECT_TYPE_MO_TRANSPORT)
    Instance       = 0x1F40,                      // blizz 1F40
    Group          = 0x1F50,
};
TypeID
enum TypeID
Enumerator
TYPEID_OBJECT
TYPEID_ITEM
TYPEID_CONTAINER
TYPEID_UNIT
TYPEID_PLAYER
TYPEID_GAMEOBJECT
TYPEID_DYNAMICOBJECT
TYPEID_CORPSE
{
    TYPEID_OBJECT        = 0,
    TYPEID_ITEM          = 1,
    TYPEID_CONTAINER     = 2,
    TYPEID_UNIT          = 3,
    TYPEID_PLAYER        = 4,
    TYPEID_GAMEOBJECT    = 5,
    TYPEID_DYNAMICOBJECT = 6,
    TYPEID_CORPSE        = 7
};
TypeMask
enum TypeMask
Enumerator
TYPEMASK_OBJECT
TYPEMASK_ITEM
TYPEMASK_CONTAINER
TYPEMASK_UNIT
TYPEMASK_PLAYER
TYPEMASK_GAMEOBJECT
TYPEMASK_DYNAMICOBJECT
TYPEMASK_CORPSE
TYPEMASK_SEER
{
    TYPEMASK_OBJECT         = 0x0001,
    TYPEMASK_ITEM           = 0x0002,
    TYPEMASK_CONTAINER      = 0x0006,             // TYPEMASK_ITEM | 0x0004
    TYPEMASK_UNIT           = 0x0008,             // creature
    TYPEMASK_PLAYER         = 0x0010,
    TYPEMASK_GAMEOBJECT     = 0x0020,
    TYPEMASK_DYNAMICOBJECT  = 0x0040,
    TYPEMASK_CORPSE         = 0x0080,
    TYPEMASK_SEER           = TYPEMASK_PLAYER | TYPEMASK_UNIT | TYPEMASK_DYNAMICOBJECT
};
Function Documentation
operator<<() [1/2]
ByteBuffer & operator<< (ByteBuffer & buf, ObjectGuid const & guid)
{
    buf << uint64(guid.GetRawValue());
    return buf;
}
References ObjectGuid::GetRawValue().
Referenced by ByteBuffer::operator<<().
operator<<() [2/2]
ByteBuffer & operator<< (ByteBuffer & buf, PackedGuid const & guid)
{
    buf.append(guid._packedGuid);
    return buf;
}
operator>>() [1/2]
ByteBuffer & operator>> (ByteBuffer & buf, ObjectGuid & guid)
{
    guid.Set(buf.read<uint64>());
    return buf;
}
References ByteBuffer::read(), and ObjectGuid::Set().
operator>>() [2/2]
ByteBuffer & operator>> (ByteBuffer & buf, PackedGuidReader const & guid)
{
    buf.readPackGUID(reinterpret_cast<uint64&>(guid.Guid));
    return buf;
}
References PackedGuidReader::Guid, and ByteBuffer::readPackGUID().