AzerothCore: UpdateData Class Reference
UpdateData Class Reference
#include "UpdateData.h"
Public Member Functions
UpdateData ()
void AddOutOfRangeGUID (ObjectGuid guid)
void AddUpdateBlock (const ByteBuffer &block)
void AddUpdateBlock (const UpdateData &block)
bool BuildPacket (WorldPacket &packet)
bool HasData () const
void Clear ()
Protected Attributes
uint32 m_blockCount
GuidVector m_outOfRangeGUIDs
ByteBuffer m_data
Detailed Description
Constructor & Destructor Documentation
UpdateData()
UpdateData::UpdateData ()
                       : m_blockCount(0)
{
    m_outOfRangeGUIDs.reserve(15);
}
References m_outOfRangeGUIDs.
Member Function Documentation
AddOutOfRangeGUID()
void UpdateData::AddOutOfRangeGUID (ObjectGuid guid)
{
    m_outOfRangeGUIDs.push_back(guid);
}
References m_outOfRangeGUIDs.
Referenced by Object::BuildOutOfRangeUpdateBlock(), Map::SendRemoveTransports(), and Acore::VisibleNotifier::SendToSelf().
AddUpdateBlock() [1/2]
void UpdateData::AddUpdateBlock (const ByteBuffer & block)
{
    m_data.append(block);
    ++m_blockCount;
}
References ByteBuffer::append(), m_blockCount, and m_data.
Referenced by Object::BuildCreateUpdateBlockForPlayer(), Object::BuildMovementUpdateBlock(), and Object::BuildValuesUpdateBlockForPlayer().
AddUpdateBlock() [2/2]
void UpdateData::AddUpdateBlock (const UpdateData & block)
{
    m_data.append(block.m_data);
    m_blockCount += block.m_blockCount;
}
References ByteBuffer::append(), m_blockCount, and m_data.
BuildPacket()
bool UpdateData::BuildPacket (WorldPacket & packet)
{
    ASSERT(packet.empty());
    packet.reserve(4 + (m_outOfRangeGUIDs.empty() ? 0 : 1 + 4 + 9 * m_outOfRangeGUIDs.size()) + m_data.wpos());
    packet << (uint32) (!m_outOfRangeGUIDs.empty() ? m_blockCount + 1 : m_blockCount);
    if (!m_outOfRangeGUIDs.empty())
    {
        packet << (uint8) UPDATETYPE_OUT_OF_RANGE_OBJECTS;
        packet << (uint32) m_outOfRangeGUIDs.size();
        for (ObjectGuid const& guid : m_outOfRangeGUIDs)
            packet << guid.WriteAsPacked();
    }
    packet.append(m_data);
    packet.SetOpcode(SMSG_UPDATE_OBJECT);
    return true;
}
References ByteBuffer::append(), ASSERT, ByteBuffer::empty(), m_blockCount, m_data, m_outOfRangeGUIDs, ByteBuffer::reserve(), WorldPacket::SetOpcode(), SMSG_UPDATE_OBJECT, UPDATETYPE_OUT_OF_RANGE_OBJECTS, and ByteBuffer::wpos().
Referenced by Group::AddMember(), Map::AddToMap(), spell_madrigosa_activate_barrier::HandleActivateObject(), spell_madrigosa_deactivate_barrier::HandleActivateObject(), spell_pri_lightwell_renew::HandleUpdateSpellclick(), Map::RemoveFromMap(), Map::SendInitSelf(), Map::SendInitTransports(), Map::SendRemoveTransports(), Acore::VisibleNotifier::SendToSelf(), BattlegroundSA::SendTransportInit(), BattlegroundSA::SendTransportsRemove(), Object::SendUpdateToPlayer(), Unit::SetOwnerGUID(), BattlegroundSA::StartShips(), GameObject::Update(), Player::UpdateForQuestWorldObjects(), and Player::UpdateTriggerVisibility().
Clear()
void UpdateData::Clear ()
{
    m_data.clear();
    m_outOfRangeGUIDs.clear();
    m_blockCount = 0;
}
References ByteBuffer::clear(), m_blockCount, m_data, and m_outOfRangeGUIDs.
Referenced by Map::SendInitSelf().
HasData()
bool UpdateData::HasData () const inline
{ return m_blockCount > 0 || !m_outOfRangeGUIDs.empty(); }
References m_blockCount, and m_outOfRangeGUIDs.
Referenced by Group::AddMember(), Acore::VisibleNotifier::SendToSelf(), and Player::UpdateTriggerVisibility().
Member Data Documentation
m_blockCount
uint32 UpdateData::m_blockCount protected
Referenced by AddUpdateBlock(), BuildPacket(), Clear(), and HasData().
m_data
ByteBuffer UpdateData::m_data protected
Referenced by AddUpdateBlock(), BuildPacket(), and Clear().
m_outOfRangeGUIDs
GuidVector UpdateData::m_outOfRangeGUIDs protected
Referenced by AddOutOfRangeGUID(), BuildPacket(), Clear(), HasData(), and UpdateData().