AzerothCore: azerothcore-wotlk/src/tools/vmap4_extractor/adtfile.h File Reference
adtfile.h File Reference
#include "model.h"
#include "mpq_libmpq04.h"
#include "wmo.h"
Classes
struct ADT::MDDF
struct ADT::MODF
class ADTFile
Namespaces
namespace ADT
Functions
const char * GetPlainName (const char *FileName)
char * GetPlainName (char *FileName)
char * GetExtension (char *FileName)
void fixnamen (char *name, std::size_t len)
void fixname2 (char *name, std::size_t len)
Function Documentation
fixname2()
void fixname2 (char * name, std::size_t len)
{
    if (len < 3)
        return;
    for (std::size_t i = 0; i < len - 3; i++)
        if (name[i] == ' ')
            name[i] = '_';
}
Referenced by ExtractGameobjectModels(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), ADTFile::init(), WDTFile::init(), and WMORoot::open().
fixnamen()
void fixnamen (char * name, std::size_t len)
{
    if (len < 3)
        return;
    for (std::size_t i = 0; i < len - 3; i++)
    {
        if (i > 0 && name[i] >= 'A' && name[i] <= 'Z' && isalpha(name[i - 1]))
            name[i] |= 0x20;
        else if ((i == 0 || !isalpha(name[i - 1])) && name[i] >= 'a' && name[i] <= 'z')
            name[i] &= ~0x20;
    }
    //extension in lowercase
    for (std::size_t i = len - 3; i < len; i++)
        name[i] |= 0x20;
}
Referenced by ExtractGameobjectModels(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), ADTFile::init(), WDTFile::init(), and WMORoot::open().
GetExtension()
char * GetExtension (char * FileName)
{
    if (char* szTemp = strrchr(FileName, '.'))
        return szTemp;
    return nullptr;
}
Referenced by ExtractGameobjectModels().
GetPlainName() [1/2]
char * GetPlainName (char * FileName)
{
    char* szTemp;
    if ((szTemp = strrchr(FileName, '\\')) != nullptr)
        FileName = szTemp + 1;
    return FileName;
}
GetPlainName() [2/2]
const char * GetPlainName (const char * FileName)
{
    const char* szTemp;
    if ((szTemp = strrchr(FileName, '\\')) != nullptr)
        FileName = szTemp + 1;
    return FileName;
}
Referenced by ExtractGameobjectModels(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), ADTFile::init(), and WMORoot::open().