AzerothCore: boss_malchezaar Struct Reference
boss_malchezaar Struct Reference
Public Member Functions
boss_malchezaar (Creature *creature)
void Initialize ()
void clearweapons ()
void Reset () override
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void EnfeebleHealthEffect ()
void EnfeebleResetHealth ()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint32 _phase
std::map< ObjectGuid, uint32 > _enfeebleTargets
std::vector< InfernalPoint * > positions
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
bool _ProccessHealthCheckEvent (uint8 healthPct, uint32 damage, std::function< void()> exec) const
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
TaskScheduler scheduler
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_malchezaar()
boss_malchezaar::boss_malchezaar (Creature * creature) inline
: BossAI(creature, DATA_MALCHEZZAR) { }
Member Function Documentation
clearweapons()
void boss_malchezaar::clearweapons () inline
    {
        SetEquipmentSlots(false, EQUIP_UNEQUIP, EQUIP_UNEQUIP, EQUIP_NO_CHANGE);
        me->SetCanDualWield(false);
    }
References EQUIP_NO_CHANGE, EQUIP_UNEQUIP, ScriptedAI::me, Creature::SetCanDualWield(), and ScriptedAI::SetEquipmentSlots().
Referenced by DamageTaken(), and Initialize().
DamageTaken()
void boss_malchezaar::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from BossAI.
    {
        if (me->HealthBelowPctDamaged(60, damage) && _phase == PHASE_ONE)
        {
            me->InterruptNonMeleeSpells(false);
            _phase = 2;
            DoCastSelf( SPELL_EQUIP_AXES);
            Talk(SAY_AXE_TOSS1);
            DoCastSelf( SPELL_THRASH_AURA, true);
            SetEquipmentSlots(false, EQUIP_ID_AXE, EQUIP_ID_AXE, EQUIP_NO_CHANGE);
            me->SetCanDualWield(true);
            me->SetAttackTime(OFF_ATTACK, (me->GetAttackTime(BASE_ATTACK) * 150) / 100);
            scheduler.Schedule(5s, 10s, [this](TaskContext context)
            {
                DoCastVictim(SPELL_SUNDER_ARMOR);
                context.Repeat();
            });
            scheduler.CancelGroup(GROUP_SHADOW_WORD_PAIN);
        }
        else if (me->HealthBelowPctDamaged(30, damage) && _phase == PHASE_TWO)
        {
            me->RemoveAurasDueToSpell(SPELL_THRASH_AURA);
            Talk(SAY_AXE_TOSS2);
            _phase = PHASE_THREE;
            clearweapons();
            me->SummonCreature(NPC_MALCHEZARS_AXE, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 10000);
            scheduler.Schedule(20s, 30s, [this](TaskContext context)
            {
                DoCastRandomTarget(SPELL_AMPLIFY_DAMAGE, 1);
                context.Repeat();
            }).Schedule(20s, [this](TaskContext context)
            {
                DoCastRandomTarget(SPELL_SHADOW_WORD_PAIN);
                context.SetGroup(GROUP_SHADOW_WORD_PAIN);
                context.Repeat();
            });;
        }
    }
References _phase, BASE_ATTACK, TaskScheduler::CancelGroup(), clearweapons(), UnitAI::DoCastRandomTarget(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), EQUIP_ID_AXE, EQUIP_NO_CHANGE, Unit::GetAttackTime(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GROUP_SHADOW_WORD_PAIN, Unit::HealthBelowPctDamaged(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, NPC_MALCHEZARS_AXE, OFF_ATTACK, PHASE_ONE, PHASE_THREE, PHASE_TWO, Unit::RemoveAurasDueToSpell(), TaskContext::Repeat(), SAY_AXE_TOSS1, SAY_AXE_TOSS2, TaskScheduler::Schedule(), BossAI::scheduler, Unit::SetAttackTime(), Creature::SetCanDualWield(), ScriptedAI::SetEquipmentSlots(), TaskContext::SetGroup(), SPELL_AMPLIFY_DAMAGE, SPELL_EQUIP_AXES, SPELL_SHADOW_WORD_PAIN, SPELL_SUNDER_ARMOR, SPELL_THRASH_AURA, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
EnfeebleHealthEffect()
void boss_malchezaar::EnfeebleHealthEffect () inline
    {
        std::list<Unit*> targetList;
        SelectTargetList(targetList, 5, SelectTargetMethod::Random, 1, [&](Unit* u) { return u->IsAlive() && u->IsPlayer(); });
        if (targetList.empty())
            return;
        for (auto const& target : targetList)
        {
            if (target)
            {
                _enfeebleTargets[target->GetGUID()] = target->GetHealth();
                me->CastSpell(target, SPELL_ENFEEBLE, true);
                target->SetHealth(1);
            }
        }
    }
References _enfeebleTargets, Unit::CastSpell(), Unit::IsAlive(), Object::IsPlayer(), ScriptedAI::me, UnitAI::SelectTargetList(), and SPELL_ENFEEBLE.
Referenced by JustEngagedWith().
EnfeebleResetHealth()
void boss_malchezaar::EnfeebleResetHealth () inline
    {
        for (auto targets : _enfeebleTargets)
        {
            if (Unit* target = ObjectAccessor::GetUnit(*me, targets.first))
            {
                if (target->IsAlive())
                {
                    target->SetHealth(targets.second);
                }
            }
        }
    }
References _enfeebleTargets, ObjectAccessor::GetUnit(), and ScriptedAI::me.
Referenced by JustEngagedWith().
Initialize()
void boss_malchezaar::Initialize () inline
    {
        _phase = 1;
        clearweapons();
        positions.clear();
        instance->HandleGameObject(instance->GetGuidData(DATA_GO_NETHER_DOOR), true);
    }
References _phase, clearweapons(), DATA_GO_NETHER_DOOR, InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), BossAI::instance, and positions.
Referenced by Reset().
JustDied()
void boss_malchezaar::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
    {
        _JustDied();
        Talk(SAY_DEATH);
        instance->HandleGameObject(instance->GetGuidData(DATA_GO_NETHER_DOOR), true);
    }
References BossAI::_JustDied(), DATA_GO_NETHER_DOOR, InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), BossAI::instance, and SAY_DEATH.
JustEngagedWith()
void boss_malchezaar::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        Talk(SAY_AGGRO);
        _JustEngagedWith();
        instance->HandleGameObject(instance->GetGuidData(DATA_GO_NETHER_DOOR), false);
        scheduler.Schedule(30s, [this](TaskContext context)
        {
            EnfeebleHealthEffect();
            scheduler.Schedule(9s, [this](TaskContext)
            {
                EnfeebleResetHealth();
            });
            context.SetGroup(GROUP_ENFEEBLE);
            scheduler.DelayGroup(GROUP_SHADOW_NOVA, 5s);
            context.Repeat();
        }).Schedule(35500ms, [this](TaskContext context)
        {
            DoCastAOE(SPELL_SHADOW_NOVA);
            context.SetGroup(GROUP_SHADOW_NOVA);
            context.Repeat();
        }).Schedule(40s, [this](TaskContext context)
        {
            Position pos =  me->GetRandomNearPosition(40.0);;
            if (Creature* RELAY = me->FindNearestCreature(NPC_RELAY, 100.0f))
            {
                if (Creature* infernal = RELAY->SummonCreature(NPC_NETHERSPITE_INFERNAL, pos, TEMPSUMMON_TIMED_DESPAWN, 180000))
                {
                    infernal->SetDisplayId(INFERNAL_MODEL_INVISIBLE);
                    infernal->SetFaction(me->GetFaction());
                    infernal->SetControlled(true, UNIT_STATE_ROOT);
                    RELAY->AI()->DoCast(infernal, SPELL_INFERNAL_RELAY);
                    summons.Summon(infernal);
                }
            }
            context.Repeat(_phase == PHASE_THREE ? 15s : 45s);
            Talk(SAY_SUMMON);
        }).Schedule(20s, [this](TaskContext context)
        {
            DoCastVictim(SPELL_SHADOW_WORD_PAIN);
            context.SetGroup(GROUP_SHADOW_WORD_PAIN);
            context.Repeat();
        });
    }
References BossAI::_JustEngagedWith(), _phase, DATA_GO_NETHER_DOOR, TaskScheduler::DelayGroup(), UnitAI::DoCastAOE(), UnitAI::DoCastVictim(), EnfeebleHealthEffect(), EnfeebleResetHealth(), WorldObject::FindNearestCreature(), Unit::GetFaction(), InstanceScript::GetGuidData(), WorldObject::GetRandomNearPosition(), GROUP_ENFEEBLE, GROUP_SHADOW_NOVA, GROUP_SHADOW_WORD_PAIN, InstanceScript::HandleGameObject(), INFERNAL_MODEL_INVISIBLE, BossAI::instance, ScriptedAI::me, NPC_NETHERSPITE_INFERNAL, NPC_RELAY, PHASE_THREE, TaskContext::Repeat(), SAY_AGGRO, SAY_SUMMON, TaskScheduler::Schedule(), BossAI::scheduler, TaskContext::SetGroup(), SPELL_INFERNAL_RELAY, SPELL_SHADOW_NOVA, SPELL_SHADOW_WORD_PAIN, SummonList::Summon(), WorldObject::SummonCreature(), BossAI::summons, TEMPSUMMON_TIMED_DESPAWN, and UNIT_STATE_ROOT.
KilledUnit()
void boss_malchezaar::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        Talk(SAY_SLAY);
    }
References SAY_SLAY.
Reset()
void boss_malchezaar::Reset () inline override virtual
Reimplemented from BossAI.
    {
        Initialize();
        _Reset();
    }
References BossAI::_Reset(), and Initialize().
Member Data Documentation
_enfeebleTargets
std::map<ObjectGuid, uint32> boss_malchezaar::_enfeebleTargets private
Referenced by EnfeebleHealthEffect(), and EnfeebleResetHealth().
_phase
uint32 boss_malchezaar::_phase private
Referenced by DamageTaken(), Initialize(), and JustEngagedWith().
positions
std::vector<InfernalPoint*> boss_malchezaar::positions private
Referenced by Initialize().