AzerothCore: npc_toc5_player_vehicle::npc_toc5_player_vehicleAI Struct Reference
npc_toc5_player_vehicle::npc_toc5_player_vehicleAI Struct Reference
Public Member Functions
npc_toc5_player_vehicleAI (Creature *pCreature)
void Reset () override
void OnCharmed (bool apply) override
void PassengerBoarded (Unit *who, int8, bool apply) override
== Fields =======================================
void MoveInLineOfSight (Unit *) override
void UpdateAI (uint32 diff) override
void AttackStart (Unit *) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
ConditionList conditions
uint16 m_ConditionsTimer
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_toc5_player_vehicleAI()
npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::npc_toc5_player_vehicleAI (Creature * pCreature) inline
                                                       : NullCreatureAI(pCreature)
        {
            conditions = sConditionMgr->GetConditionsForNotGroupedEntry(CONDITION_SOURCE_TYPE_CREATURE_TEMPLATE_VEHICLE, me->GetEntry());
            m_ConditionsTimer = 1000;
        }
References CONDITION_SOURCE_TYPE_CREATURE_TEMPLATE_VEHICLE, conditions, Object::GetEntry(), m_ConditionsTimer, CreatureAI::me, and sConditionMgr.
Member Function Documentation
AttackStart()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::AttackStart (Unit *) inline override virtual
Reimplemented from NullCreatureAI.
{}
JustEngagedWith()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from CreatureAI.
{}
MoveInLineOfSight()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from NullCreatureAI.
{}
OnCharmed()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::OnCharmed (bool apply) inline override virtual
Reimplemented from NullCreatureAI.
        {
            if (me->IsDuringRemoveFromWorld())
                return;
            if( apply )
            {
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->SetSpeed(MOVE_RUN, 2.0f, false);
                me->CastSpell(me, SPELL_TRAMPLE_AURA, true);
            }
            else
            {
                me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->StopMoving();
                me->RemoveAura(SPELL_TRAMPLE_AURA);
            }
        }
References Unit::CastSpell(), Unit::IsDuringRemoveFromWorld(), CreatureAI::me, MOVE_RUN, Unit::RemoveAura(), Unit::RemoveUnitFlag(), Unit::SetSpeed(), Unit::SetUnitFlag(), SPELL_TRAMPLE_AURA, Unit::StopMoving(), and UNIT_FLAG_NON_ATTACKABLE.
PassengerBoarded()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
        {
            if (me->IsDuringRemoveFromWorld())
                return;
            if( !apply )
            {
                me->RemoveAura(SPELL_PLAYER_VEHICLE_DEFEND);
                who->RemoveAura(SPELL_PLAYER_VEHICLE_DEFEND);
                for (uint8 i = 0; i < 3; ++i)
                    who->RemoveAura(SPELL_SHIELD_LEVEL_1_VISUAL + i);
            }
        }
References Unit::IsDuringRemoveFromWorld(), CreatureAI::me, Unit::RemoveAura(), SPELL_PLAYER_VEHICLE_DEFEND, and SPELL_SHIELD_LEVEL_1_VISUAL.
Reset()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            me->SetReactState(REACT_PASSIVE);
            me->getHostileRefMgr().setOnlineOfflineState(false);
        }
References Unit::getHostileRefMgr(), CreatureAI::me, REACT_PASSIVE, HostileRefMgr::setOnlineOfflineState(), and Creature::SetReactState().
UpdateAI()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
        {
            if (m_ConditionsTimer <= diff)
            {
                if (!conditions.empty())
                    if (Unit* passenger = me->GetVehicleKit()->GetPassenger(0))
                        if (!sConditionMgr->IsObjectMeetToConditions(passenger, me, conditions))
                            passenger->ExitVehicle();
                m_ConditionsTimer = VEHICLE_CONDITION_CHECK_TIME;
            }
            else
                m_ConditionsTimer -= diff;
        }
References conditions, Vehicle::GetPassenger(), Unit::GetVehicleKit(), m_ConditionsTimer, CreatureAI::me, sConditionMgr, and VEHICLE_CONDITION_CHECK_TIME.
Member Data Documentation
conditions
ConditionList npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::conditions
Referenced by npc_toc5_player_vehicleAI(), and UpdateAI().
m_ConditionsTimer
uint16 npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::m_ConditionsTimer
Referenced by npc_toc5_player_vehicleAI(), and UpdateAI().