document.write(`
  <a id="Item:CanBeTraded" class="fn" href="../Item/CanBeTraded.html">CanBeTraded</a>
  <a id="Item:ClearEnchantment" class="fn" href="../Item/ClearEnchantment.html">ClearEnchantment</a>
  <a id="Item:GetAllowableClass" class="fn" href="../Item/GetAllowableClass.html">GetAllowableClass</a>
  <a id="Item:GetAllowableRace" class="fn" href="../Item/GetAllowableRace.html">GetAllowableRace</a>
  <a id="Item:GetBagSize" class="fn" href="../Item/GetBagSize.html">GetBagSize</a>
  <a id="Item:GetBagSlot" class="fn" href="../Item/GetBagSlot.html">GetBagSlot</a>
  <a id="Item:GetBuyCount" class="fn" href="../Item/GetBuyCount.html">GetBuyCount</a>
  <a id="Item:GetBuyPrice" class="fn" href="../Item/GetBuyPrice.html">GetBuyPrice</a>
  <a id="Item:GetClass" class="fn" href="../Item/GetClass.html">GetClass</a>
  <a id="Item:GetCount" class="fn" href="../Item/GetCount.html">GetCount</a>
  <a id="Item:GetDisplayId" class="fn" href="../Item/GetDisplayId.html">GetDisplayId</a>
  <a id="Item:GetEnchantmentId" class="fn" href="../Item/GetEnchantmentId.html">GetEnchantmentId</a>
  <a id="Item:GetInventoryType" class="fn" href="../Item/GetInventoryType.html">GetInventoryType</a>
  <a id="Item:GetItemLevel" class="fn" href="../Item/GetItemLevel.html">GetItemLevel</a>
  <a id="Item:GetItemLink" class="fn" href="../Item/GetItemLink.html">GetItemLink</a>
  <a id="Item:GetItemSet" class="fn" href="../Item/GetItemSet.html">GetItemSet</a>
  <a id="Item:GetItemTemplate" class="fn" href="../Item/GetItemTemplate.html">GetItemTemplate</a>
  <a id="Item:GetMaxStackCount" class="fn" href="../Item/GetMaxStackCount.html">GetMaxStackCount</a>
  <a id="Item:GetName" class="fn" href="../Item/GetName.html">GetName</a>
  <a id="Item:GetOwner" class="fn" href="../Item/GetOwner.html">GetOwner</a>
  <a id="Item:GetOwnerGUID" class="fn" href="../Item/GetOwnerGUID.html">GetOwnerGUID</a>
  <a id="Item:GetQuality" class="fn" href="../Item/GetQuality.html">GetQuality</a>
  <a id="Item:GetRandomProperty" class="fn" href="../Item/GetRandomProperty.html">GetRandomProperty</a>
  <a id="Item:GetRandomSuffix" class="fn" href="../Item/GetRandomSuffix.html">GetRandomSuffix</a>
  <a id="Item:GetRequiredLevel" class="fn" href="../Item/GetRequiredLevel.html">GetRequiredLevel</a>
  <a id="Item:GetSellPrice" class="fn" href="../Item/GetSellPrice.html">GetSellPrice</a>
  <a id="Item:GetSlot" class="fn" href="../Item/GetSlot.html">GetSlot</a>
  <a id="Item:GetSpellId" class="fn" href="../Item/GetSpellId.html">GetSpellId</a>
  <a id="Item:GetSpellTrigger" class="fn" href="../Item/GetSpellTrigger.html">GetSpellTrigger</a>
  <a id="Item:GetStatsCount" class="fn" href="../Item/GetStatsCount.html">GetStatsCount</a>
  <a id="Item:GetSubClass" class="fn" href="../Item/GetSubClass.html">GetSubClass</a>
  <a id="Item:HasQuest" class="fn" href="../Item/HasQuest.html">HasQuest</a>
  <a id="Item:IsArmorVellum" class="fn" href="../Item/IsArmorVellum.html">IsArmorVellum</a>
  <a id="Item:IsBag" class="fn" href="../Item/IsBag.html">IsBag</a>
  <a id="Item:IsBoundAccountWide" class="fn" href="../Item/IsBoundAccountWide.html">IsBoundAccountWide</a>
  <a id="Item:IsBoundByEnchant" class="fn" href="../Item/IsBoundByEnchant.html">IsBoundByEnchant</a>
  <a id="Item:IsBroken" class="fn" href="../Item/IsBroken.html">IsBroken</a>
  <a id="Item:IsConjuredConsumable" class="fn" href="../Item/IsConjuredConsumable.html">IsConjuredConsumable</a>
  <a id="Item:IsCurrencyToken" class="fn" href="../Item/IsCurrencyToken.html">IsCurrencyToken</a>
  <a id="Item:IsEquipped" class="fn" href="../Item/IsEquipped.html">IsEquipped</a>
  <a id="Item:IsInBag" class="fn" href="../Item/IsInBag.html">IsInBag</a>
  <a id="Item:IsInTrade" class="fn" href="../Item/IsInTrade.html">IsInTrade</a>
  <a id="Item:IsLocked" class="fn" href="../Item/IsLocked.html">IsLocked</a>
  <a id="Item:IsNotBoundToPlayer" class="fn" href="../Item/IsNotBoundToPlayer.html">IsNotBoundToPlayer</a>
  <a id="Item:IsNotEmptyBag" class="fn" href="../Item/IsNotEmptyBag.html">IsNotEmptyBag</a>
  <a id="Item:IsPotion" class="fn" href="../Item/IsPotion.html">IsPotion</a>
  <a id="Item:IsSoulBound" class="fn" href="../Item/IsSoulBound.html">IsSoulBound</a>
  <a id="Item:IsWeaponVellum" class="fn" href="../Item/IsWeaponVellum.html">IsWeaponVellum</a>
  <a id="Item:SaveToDB" class="fn" href="../Item/SaveToDB.html">SaveToDB</a>
  <a id="Item:SetBinding" class="fn" href="../Item/SetBinding.html">SetBinding</a>
  <a id="Item:SetCount" class="fn" href="../Item/SetCount.html">SetCount</a>
  <a id="Item:SetEnchantment" class="fn" href="../Item/SetEnchantment.html">SetEnchantment</a>
  <a id="Item:SetOwner" class="fn" href="../Item/SetOwner.html">SetOwner</a>
`);