AzerothCore: WorldUpdateTime Class Reference
WorldUpdateTime Class Reference
#include "UpdateTime.h"
Public Member Functions
WorldUpdateTime ()
void LoadFromConfig ()
void SetRecordUpdateTimeInterval (Milliseconds t)
void RecordUpdateTime (Milliseconds gameTimeMs, uint32 diff, uint32 sessionCount)
void RecordUpdateTimeDuration (std::string const &text)
Public Member Functions inherited from UpdateTime
uint32 GetAverageUpdateTime () const
uint32 GetTimeWeightedAverageUpdateTime () const
uint32 GetMaxUpdateTime () const
uint32 GetMaxUpdateTimeOfCurrentTable () const
uint32 GetLastUpdateTime () const
uint32 GetDatasetSize () const
uint32 GetPercentile (uint8 p)
void UpdateWithDiff (uint32 diff)
void RecordUpdateTimeReset ()
Private Attributes
Milliseconds _recordUpdateTimeInverval
Milliseconds _recordUpdateTimeMin
Milliseconds _lastRecordTime
Additional Inherited Members
Protected Member Functions inherited from UpdateTime
UpdateTime ()
void SortUpdateTimeDataTable ()
Detailed Description
Constructor & Destructor Documentation
WorldUpdateTime()
WorldUpdateTime::WorldUpdateTime () inline
: UpdateTime(), _recordUpdateTimeInverval(0), _recordUpdateTimeMin(0), _lastRecordTime(0) { }
Member Function Documentation
LoadFromConfig()
void WorldUpdateTime::LoadFromConfig ()
{
    _recordUpdateTimeInverval = Milliseconds(sConfigMgr->GetOption<uint32>("RecordUpdateTimeDiffInterval", 300000));
    _recordUpdateTimeMin = Milliseconds(sConfigMgr->GetOption<uint32>("MinRecordUpdateTimeDiff", 100));
}
References _recordUpdateTimeInverval, _recordUpdateTimeMin, and sConfigMgr.
Referenced by World::LoadConfigSettings().
RecordUpdateTime()
void WorldUpdateTime::RecordUpdateTime (Milliseconds gameTimeMs, uint32 diff, uint32 sessionCount)
{
    if (_recordUpdateTimeInverval > 0s && diff > _recordUpdateTimeMin.count())
    {
        if (GetMSTimeDiff(_lastRecordTime, gameTimeMs) > _recordUpdateTimeInverval)
        {
            LOG_INFO("time.update", "Update time diff: {}ms with {} players online", GetLastUpdateTime(), sessionCount);
            LOG_INFO("time.update", "Last {} diffs summary:", GetDatasetSize());
            LOG_INFO("time.update", "|- Mean: {}ms", GetAverageUpdateTime());
            LOG_INFO("time.update", "|- Median: {}ms", GetPercentile(50));
            LOG_INFO("time.update", "|- Percentiles (95, 99, max): {}ms, {}ms, {}ms", GetPercentile(95), GetPercentile(99), GetPercentile(100));
            _lastRecordTime = gameTimeMs;
        }
    }
}
References _lastRecordTime, _recordUpdateTimeInverval, _recordUpdateTimeMin, UpdateTime::GetAverageUpdateTime(), UpdateTime::GetDatasetSize(), UpdateTime::GetLastUpdateTime(), GetMSTimeDiff(), UpdateTime::GetPercentile(), and LOG_INFO.
Referenced by World::Update().
RecordUpdateTimeDuration()
void WorldUpdateTime::RecordUpdateTimeDuration (std::string const & text)
SetRecordUpdateTimeInterval()
void WorldUpdateTime::SetRecordUpdateTimeInterval (Milliseconds t)
{
    _recordUpdateTimeInverval = t;
}
References _recordUpdateTimeInverval.
Member Data Documentation
_lastRecordTime
Milliseconds WorldUpdateTime::_lastRecordTime private
Referenced by RecordUpdateTime().
_recordUpdateTimeInverval
Milliseconds WorldUpdateTime::_recordUpdateTimeInverval private
Referenced by LoadFromConfig(), RecordUpdateTime(), and SetRecordUpdateTimeInterval().
_recordUpdateTimeMin
Milliseconds WorldUpdateTime::_recordUpdateTimeMin private
Referenced by LoadFromConfig(), and RecordUpdateTime().