AzerothCore: boss_gothik::boss_gothikAI Struct Reference
boss_gothik::boss_gothikAI Struct Reference
Public Member Functions
boss_gothikAI (Creature *c)
bool IsInRoom ()
void Reset () override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *cr) override
void KilledUnit (Unit *who) override
void JustDied (Unit *killer) override
void SummonHelpers (uint32 entry)
bool CheckGroupSplitted ()
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
SummonList summons
InstanceScript * pInstance
bool secondPhase {}
bool gateOpened {}
uint8 waveCount {}
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_gothikAI()
boss_gothik::boss_gothikAI::boss_gothikAI (Creature * c) inline explicit
                                            : BossAI(c, BOSS_GOTHIK), summons(me)
        {
            pInstance = me->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
CheckGroupSplitted()
bool boss_gothik::boss_gothikAI::CheckGroupSplitted () inline
        {
            Map::PlayerList const& PlayerList = me->GetMap()->GetPlayers();
            if (!PlayerList.IsEmpty())
            {
                bool checklife = false;
                bool checkdead = false;
                for (auto const& i : PlayerList)
                {
                    Player* player = i.GetSource();
                    if (player->IsAlive() &&
                        player->GetPositionX() <= POS_X_NORTH &&
                        player->GetPositionX() >= POS_X_SOUTH &&
                        player->GetPositionY() <= POS_Y_GATE &&
                        player->GetPositionY() >= POS_Y_EAST)
{
                            checklife = true;
                        }
                    else if (player->IsAlive() &&
                             player->GetPositionX() <= POS_X_NORTH &&
                             player->GetPositionX() >= POS_X_SOUTH &&
                             player->GetPositionY() >= POS_Y_GATE &&
                             player->GetPositionY() <= POS_Y_WEST)
{
                                 checkdead = true;
                             }
                    if (checklife && checkdead)
                        return true;
                }
            }
            return false;
        }
References WorldObject::GetMap(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Unit::IsAlive(), LinkedListHead::IsEmpty(), ScriptedAI::me, POS_X_NORTH, POS_X_SOUTH, POS_Y_EAST, POS_Y_GATE, and POS_Y_WEST.
Referenced by UpdateAI().
DamageTaken()
void boss_gothik::boss_gothikAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
        {
            if (!secondPhase)
            {
                damage = 0;
            }
        }
References secondPhase.
IsInRoom()
bool boss_gothik::boss_gothikAI::IsInRoom () inline
        {
            if (me->GetPositionX() > 2767 || me->GetPositionX() < 2618 || me->GetPositionY() > -3285 || me->GetPositionY() < -3435)
            {
                EnterEvadeMode();
                return false;
            }
            return true;
        }
References BossAI::EnterEvadeMode(), Position::GetPositionX(), Position::GetPositionY(), and ScriptedAI::me.
Referenced by UpdateAI().
JustDied()
void boss_gothik::boss_gothikAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
        {
            BossAI::JustDied(killer);
            Talk(SAY_DEATH);
            summons.DespawnAll();
            if (pInstance)
            {
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_ENTER_GATE)))
                {
                    go->SetGoState(GO_STATE_ACTIVE);
                }
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_INNER_GATE)))
                {
                    go->SetGoState(GO_STATE_ACTIVE);
                }
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_EXIT_GATE)))
                {
                    go->SetGoState(GO_STATE_ACTIVE);
                }
            }
        }
References DATA_GOTHIK_ENTER_GATE, DATA_GOTHIK_EXIT_GATE, DATA_GOTHIK_INNER_GATE, SummonList::DespawnAll(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_ACTIVE, BossAI::JustDied(), ScriptedAI::me, pInstance, SAY_DEATH, and summons.
JustEngagedWith()
void boss_gothik::boss_gothikAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            BossAI::JustEngagedWith(who);
            me->SetInCombatWithZone();
            Talk(SAY_INTRO_1);
            events.ScheduleEvent(EVENT_INTRO_2, 4s);
            events.ScheduleEvent(EVENT_INTRO_3, 9s);
            events.ScheduleEvent(EVENT_INTRO_4, 14s);
            me->SetUnitFlag(UNIT_FLAG_DISABLE_MOVE);
            events.ScheduleEvent(EVENT_SUMMON_ADDS, 30s);
            events.ScheduleEvent(EVENT_CHECK_PLAYERS, 2min);
            if (pInstance)
            {
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_ENTER_GATE)))
                {
                    go->SetGoState(GO_STATE_READY);
                }
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_INNER_GATE)))
                {
                    go->SetGoState(GO_STATE_READY);
                }
            }
        }
References DATA_GOTHIK_ENTER_GATE, DATA_GOTHIK_INNER_GATE, EVENT_CHECK_PLAYERS, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_INTRO_4, EVENT_SUMMON_ADDS, Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_READY, BossAI::JustEngagedWith(), ScriptedAI::me, pInstance, SAY_INTRO_1, Creature::SetInCombatWithZone(), Unit::SetUnitFlag(), and UNIT_FLAG_DISABLE_MOVE.
JustSummoned()
void boss_gothik::boss_gothikAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            summons.Summon(summon);
            // If central gate is open, attack any one
            if (gateOpened)
            {
                if (Unit* target = SelectTarget(SelectTargetMethod::MinDistance, 0, 200.0f))
                {
                    summon->AI()->AttackStart(target);
                    summon->SetInCombatWithZone();
                    summon->SetReactState(REACT_AGGRESSIVE);
                    summon->CallForHelp(150.0f);
                }
            }
            // Else look for a random target on the side the summoned NPC is
            else
            {
                Map::PlayerList const& pList = me->GetMap()->GetPlayers();
                std::vector<Player*> tList;
                for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
                {
                    if (!me->IsWithinDistInMap(itr->GetSource(), 200.0f, true, false) || !itr->GetSource()->IsAlive() || itr->GetSource()->IsGameMaster())
                    {
                        continue;
                    }
                    if (IN_LIVE_SIDE(itr->GetSource()) != IN_LIVE_SIDE(summon))
                    {
                        continue;
                    }
                    tList.push_back(itr->GetSource());
                }
                if (!tList.empty())
                {
                    Player* target = tList[urand(0, tList.size() - 1)];
                    summon->AI()->AttackStart(target);
                    summon->SetInCombatWithZone();
                    summon->SetReactState(REACT_AGGRESSIVE);
                    summon->CallForHelp(150.0f);
                }
            }
        }
References Creature::AI(), UnitAI::AttackStart(), MapRefMgr::begin(), Creature::CallForHelp(), MapRefMgr::end(), gateOpened, WorldObject::GetMap(), Map::GetPlayers(), IN_LIVE_SIDE, WorldObject::IsWithinDistInMap(), ScriptedAI::me, REACT_AGGRESSIVE, UnitAI::SelectTarget(), Creature::SetInCombatWithZone(), Creature::SetReactState(), SummonList::Summon(), summons, and urand().
KilledUnit()
void boss_gothik::boss_gothikAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!who->IsPlayer())
                return;
            Talk(SAY_KILL);
            if (pInstance)
            {
                pInstance->SetData(DATA_IMMORTAL_FAIL, 0);
            }
        }
References DATA_IMMORTAL_FAIL, Object::IsPlayer(), pInstance, SAY_KILL, and ZoneScript::SetData().
Reset()
void boss_gothik::boss_gothikAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            BossAI::Reset();
            events.Reset();
            summons.DespawnAll();
            me->RemoveUnitFlag(UNIT_FLAG_DISABLE_MOVE);
            me->SetImmuneToPC(false);
            me->SetReactState(REACT_PASSIVE);
            secondPhase = false;
            gateOpened = false;
            waveCount = 0;
            me->NearTeleportTo(2642.139f, -3386.959f, 285.492f, 6.265f);
            if (pInstance)
            {
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_ENTER_GATE)))
                {
                    go->SetGoState(GO_STATE_ACTIVE);
                }
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_INNER_GATE)))
                {
                    go->SetGoState(GO_STATE_ACTIVE);
                }
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_EXIT_GATE)))
                {
                    go->SetGoState(GO_STATE_READY);
                }
            }
        }
References DATA_GOTHIK_ENTER_GATE, DATA_GOTHIK_EXIT_GATE, DATA_GOTHIK_INNER_GATE, SummonList::DespawnAll(), gateOpened, Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_ACTIVE, GO_STATE_READY, ScriptedAI::me, Unit::NearTeleportTo(), pInstance, REACT_PASSIVE, Unit::RemoveUnitFlag(), BossAI::Reset(), secondPhase, Unit::SetImmuneToPC(), Creature::SetReactState(), summons, UNIT_FLAG_DISABLE_MOVE, and waveCount.
SummonedCreatureDespawn()
void boss_gothik::boss_gothikAI::SummonedCreatureDespawn (Creature * cr) inline override virtual
Reimplemented from BossAI.
        {
            summons.Despawn(cr);
        }
References SummonList::Despawn(), and summons.
SummonHelpers()
void boss_gothik::boss_gothikAI::SummonHelpers (uint32 entry) inline
        {
            switch (entry)
            {
                case NPC_LIVING_TRAINEE:
                    me->SummonCreature(NPC_LIVING_TRAINEE, PosSummonLiving[0].GetPositionX(), PosSummonLiving[0].GetPositionY(), PosSummonLiving[0].GetPositionZ(), PosSummonLiving[0].GetOrientation());
                    me->SummonCreature(NPC_LIVING_TRAINEE, PosSummonLiving[1].GetPositionX(), PosSummonLiving[1].GetPositionY(), PosSummonLiving[1].GetPositionZ(), PosSummonLiving[1].GetOrientation());
                    if (Is25ManRaid())
                    {
                        me->SummonCreature(NPC_LIVING_TRAINEE, PosSummonLiving[2].GetPositionX(), PosSummonLiving[2].GetPositionY(), PosSummonLiving[2].GetPositionZ(), PosSummonLiving[2].GetOrientation());
                    }
                    break;
                case NPC_LIVING_KNIGHT:
                    me->SummonCreature(NPC_LIVING_KNIGHT, PosSummonLiving[3].GetPositionX(), PosSummonLiving[3].GetPositionY(), PosSummonLiving[3].GetPositionZ(), PosSummonLiving[3].GetOrientation());
                    if (Is25ManRaid())
                    {
                        me->SummonCreature(NPC_LIVING_KNIGHT, PosSummonLiving[5].GetPositionX(), PosSummonLiving[5].GetPositionY(), PosSummonLiving[5].GetPositionZ(), PosSummonLiving[5].GetOrientation());
                    }
                    break;
                case NPC_LIVING_RIDER:
                    me->SummonCreature(NPC_LIVING_RIDER, PosSummonLiving[4].GetPositionX(), PosSummonLiving[4].GetPositionY(), PosSummonLiving[4].GetPositionZ(), PosSummonLiving[4].GetOrientation());
                    break;
            }
        }
References ScriptedAI::Is25ManRaid(), ScriptedAI::me, NPC_LIVING_KNIGHT, NPC_LIVING_RIDER, NPC_LIVING_TRAINEE, PosSummonLiving, and WorldObject::SummonCreature().
Referenced by UpdateAI().
UpdateAI()
void boss_gothik::boss_gothikAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            if (!IsInRoom())
                return;
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_INTRO_2:
                    Talk(SAY_INTRO_2);
                    break;
                case EVENT_INTRO_3:
                    Talk(SAY_INTRO_3);
                    break;
                case EVENT_INTRO_4:
                    Talk(SAY_INTRO_4);
                    break;
                case EVENT_SHADOW_BOLT:
                    me->CastSpell(me->GetVictim(), RAID_MODE(SPELL_SHADOW_BOLT_10, SPELL_SHADOW_BOLT_25), false);
                    events.Repeat(1s);
                    break;
                case EVENT_HARVEST_SOUL:
                    me->CastSpell(me, SPELL_HARVEST_SOUL, false);
                    events.Repeat(15s);
                    break;
                case EVENT_TELEPORT:
                    me->AttackStop();
                    if (IN_LIVE_SIDE(me))
                    {
                        me->CastSpell(me, SPELL_TELEPORT_DEAD, false);
                    }
                    else
                    {
                        me->CastSpell(me, SPELL_TELEPORT_LIVE, false);
                    }
                    me->GetThreatMgr().resetAggro(NotOnSameSide(me));
                    if (Unit* pTarget = SelectTarget(SelectTargetMethod::MaxDistance, 0))
                    {
                        me->GetThreatMgr().AddThreat(pTarget, 100.0f);
                        AttackStart(pTarget);
                    }
                    events.Repeat(20s);
                    break;
                case EVENT_CHECK_HEALTH:
                    if (me->HealthBelowPct(30) && pInstance)
                    {
                        if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_INNER_GATE)))
{
                            go->SetGoState(GO_STATE_ACTIVE);
                        }
                        events.CancelEvent(EVENT_TELEPORT);
                        break;
                    }
                    events.Repeat(1s);
                    break;
                case EVENT_SUMMON_ADDS:
                    if (gothikWaves[waveCount][0])
                    {
                        SummonHelpers(gothikWaves[waveCount][0]);
                        events.RepeatEvent(gothikWaves[waveCount][1]);
                    }
                    else
                    {
                        secondPhase = true;
                        Talk(SAY_PHASE_TWO);
                        Talk(EMOTE_PHASE_TWO);
                        me->CastSpell(me, SPELL_TELEPORT_LIVE, false);
                        me->SetReactState(REACT_AGGRESSIVE);
                        me->RemoveUnitFlag(UNIT_FLAG_DISABLE_MOVE);
                        me->SetImmuneToPC(false);
                        me->RemoveAllAuras();
                        events.ScheduleEvent(EVENT_SHADOW_BOLT, 1s);
                        events.ScheduleEvent(EVENT_HARVEST_SOUL, 5s, 15s);
                        events.ScheduleEvent(EVENT_TELEPORT, 20s);
                        events.ScheduleEvent(EVENT_CHECK_HEALTH, 1s);
                    }
                    waveCount++;
                    break;
                case EVENT_CHECK_PLAYERS:
                    if (!CheckGroupSplitted())
                    {
                        if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_INNER_GATE)))
{
                            go->SetGoState(GO_STATE_ACTIVE);
                        }
                        gateOpened = true;
                        Talk(EMOTE_GATE_OPENED);
                    }
                    break;
            }
            DoMeleeAttackIfReady();
        }
References ThreatMgr::AddThreat(), ScriptedAI::AttackStart(), Unit::AttackStop(), Unit::CastSpell(), CheckGroupSplitted(), DATA_GOTHIK_INNER_GATE, UnitAI::DoMeleeAttackIfReady(), EMOTE_GATE_OPENED, EMOTE_PHASE_TWO, EVENT_CHECK_HEALTH, EVENT_CHECK_PLAYERS, EVENT_HARVEST_SOUL, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_INTRO_4, EVENT_SHADOW_BOLT, EVENT_SUMMON_ADDS, EVENT_TELEPORT, gateOpened, Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetThreatMgr(), Unit::GetVictim(), GO_STATE_ACTIVE, gothikWaves, Unit::HasUnitState(), Unit::HealthBelowPct(), IN_LIVE_SIDE, IsInRoom(), ScriptedAI::me, pInstance, ScriptedAI::RAID_MODE(), REACT_AGGRESSIVE, Unit::RemoveAllAuras(), Unit::RemoveUnitFlag(), ThreatMgr::resetAggro(), SAY_INTRO_2, SAY_INTRO_3, SAY_INTRO_4, SAY_PHASE_TWO, secondPhase, UnitAI::SelectTarget(), Unit::SetImmuneToPC(), Creature::SetReactState(), SPELL_HARVEST_SOUL, SPELL_SHADOW_BOLT_10, SPELL_SHADOW_BOLT_25, SPELL_TELEPORT_DEAD, SPELL_TELEPORT_LIVE, SummonHelpers(), UNIT_FLAG_DISABLE_MOVE, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and waveCount.
Member Data Documentation
events
EventMap boss_gothik::boss_gothikAI::events
gateOpened
bool boss_gothik::boss_gothikAI::gateOpened {}
Referenced by JustSummoned(), Reset(), and UpdateAI().
pInstance
InstanceScript* boss_gothik::boss_gothikAI::pInstance
Referenced by boss_gothikAI(), JustDied(), JustEngagedWith(), KilledUnit(), Reset(), and UpdateAI().
secondPhase
bool boss_gothik::boss_gothikAI::secondPhase {}
Referenced by DamageTaken(), Reset(), and UpdateAI().
summons
SummonList boss_gothik::boss_gothikAI::summons
Referenced by JustDied(), JustSummoned(), Reset(), and SummonedCreatureDespawn().
waveCount
uint8 boss_gothik::boss_gothikAI::waveCount {}
Referenced by Reset(), and UpdateAI().