AzerothCore: OPvPCapturePointHP Class Reference
OPvPCapturePointHP Class Reference
#include "OutdoorPvPHP.h"
Public Member Functions
OPvPCapturePointHP (OutdoorPvP *pvp, OutdoorPvPHPTowerType type)
void ChangeState () override
void SendChangePhase () override
void FillInitialWorldStates (WorldPacket &data) override
bool HandlePlayerEnter (Player *player) override
void HandlePlayerLeave (Player *player) override
Public Member Functions inherited from OPvPCapturePoint
OPvPCapturePoint (OutdoorPvP *pvp)
virtual ~OPvPCapturePoint ()=default
virtual void FillInitialWorldStates (WorldPacket &)
void SendUpdateWorldState (uint32 field, uint32 value)
void SendObjectiveComplete (uint32 id, ObjectGuid guid=ObjectGuid::Empty)
virtual bool HandlePlayerEnter (Player *player)
virtual void HandlePlayerLeave (Player *player)
bool IsInsideObjective (Player *player) const
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual int32 HandleOpenGo (Player *player, GameObject *go)
virtual bool Update (uint32 diff)
virtual void ChangeState ()=0
virtual void ChangeTeam (TeamId)
virtual void SendChangePhase ()
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipId)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual void DeleteSpawns ()
void AddGO (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
void AddCre (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
bool SetCapturePointData (uint32 entry, uint32 map, float x, float y, float z, float o=0, float rotation0=0, float rotation1=0, float rotation2=0, float rotation3=0)
void SetSlider (float slider)
float GetSlider () const
Private Attributes
OutdoorPvPHPTowerType m_TowerType
Additional Inherited Members
Public Attributes inherited from OPvPCapturePoint
ObjectGuid::LowType m_capturePointSpawnId {}
GameObject * _capturePoint {}
Protected Member Functions inherited from OPvPCapturePoint
bool AddObject (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3)
bool AddCreature (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, uint32 spawntimeDelay=0)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool DelCapturePoint ()
Protected Attributes inherited from OPvPCapturePoint
std::array< PlayerSet, 2 > _activePlayers
float _maxValue {}
float _minValue {}
float _maxSpeed {}
float _value {}
TeamId _team { TEAM_NEUTRAL }
ObjectiveStates _oldState { OBJECTIVESTATE_NEUTRAL }
ObjectiveStates _state { OBJECTIVESTATE_NEUTRAL }
uint32 _neutralValuePct {}
OutdoorPvP * _pvp {}
std::unordered_map< uint32, ObjectGuid::LowType > _objects
std::unordered_map< uint32, ObjectGuid::LowType > _creatures
std::unordered_map< ObjectGuid::LowType, uint32 > _objectTypes
std::unordered_map< ObjectGuid::LowType, uint32 > _creatureTypes
Detailed Description
Constructor & Destructor Documentation
OPvPCapturePointHP()
OPvPCapturePointHP::OPvPCapturePointHP (OutdoorPvP * pvp, OutdoorPvPHPTowerType type)
    : OPvPCapturePoint(pvp), m_TowerType(type)
{
    SetCapturePointData(HPCapturePoints[type].entry,
                        HPCapturePoints[type].map,
                        HPCapturePoints[type].x,
                        HPCapturePoints[type].y,
                        HPCapturePoints[type].z,
                        HPCapturePoints[type].o,
                        HPCapturePoints[type].rot0,
                        HPCapturePoints[type].rot1,
                        HPCapturePoints[type].rot2,
                        HPCapturePoints[type].rot3);
    AddObject(type,
              HPTowerFlags[type].entry,
              HPTowerFlags[type].map,
              HPTowerFlags[type].x,
              HPTowerFlags[type].y,
              HPTowerFlags[type].z,
              HPTowerFlags[type].o,
              HPTowerFlags[type].rot0,
              HPTowerFlags[type].rot1,
              HPTowerFlags[type].rot2,
              HPTowerFlags[type].rot3);
}
References OPvPCapturePoint::AddObject(), HPCapturePoints, HPTowerFlags, and OPvPCapturePoint::SetCapturePointData().
Member Function Documentation
ChangeState()
void OPvPCapturePointHP::ChangeState () override virtual
Implements OPvPCapturePoint.
{
    uint32 field = 0;
    switch (_oldState)
    {
        case OBJECTIVESTATE_NEUTRAL:
            field = HP_MAP_N[m_TowerType];
            break;
        case OBJECTIVESTATE_ALLIANCE:
            field = HP_MAP_A[m_TowerType];
            if (uint32 alliance_towers = ((OutdoorPvPHP*)_pvp)->GetAllianceTowersControlled())
                ((OutdoorPvPHP*)_pvp)->SetAllianceTowersControlled(--alliance_towers);
            sWorld->SendZoneText(OutdoorPvPHPBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(HP_LANG_LOSE_A[m_TowerType]));
            break;
        case OBJECTIVESTATE_HORDE:
            field = HP_MAP_H[m_TowerType];
            if (uint32 horde_towers = ((OutdoorPvPHP*)_pvp)->GetHordeTowersControlled())
                ((OutdoorPvPHP*)_pvp)->SetHordeTowersControlled(--horde_towers);
            sWorld->SendZoneText(OutdoorPvPHPBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(HP_LANG_LOSE_H[m_TowerType]));
            break;
        case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
            field = HP_MAP_N[m_TowerType];
            break;
        case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
            field = HP_MAP_N[m_TowerType];
            break;
        case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
            field = HP_MAP_A[m_TowerType];
            break;
        case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
            field = HP_MAP_H[m_TowerType];
            break;
    }
    // send world state update
    if (field)
    {
        _pvp->SendUpdateWorldState(field, 0);
        field = 0;
    }
    uint32 artkit = 21;
    uint32 artkit2 = HP_TowerArtKit_N[m_TowerType];
    switch (_state)
    {
        case OBJECTIVESTATE_NEUTRAL:
            field = HP_MAP_N[m_TowerType];
            break;
        case OBJECTIVESTATE_ALLIANCE:
            {
                field = HP_MAP_A[m_TowerType];
                artkit = 2;
                artkit2 = HP_TowerArtKit_A[m_TowerType];
                uint32 alliance_towers = ((OutdoorPvPHP*)_pvp)->GetAllianceTowersControlled();
                if (alliance_towers < 3)
                    ((OutdoorPvPHP*)_pvp)->SetAllianceTowersControlled(++alliance_towers);
                sWorld->SendZoneText(OutdoorPvPHPBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(HP_LANG_CAPTURE_A[m_TowerType]));
                break;
            }
        case OBJECTIVESTATE_HORDE:
            {
                field = HP_MAP_H[m_TowerType];
                artkit = 1;
                artkit2 = HP_TowerArtKit_H[m_TowerType];
                uint32 horde_towers = ((OutdoorPvPHP*)_pvp)->GetHordeTowersControlled();
                if (horde_towers < 3)
                    ((OutdoorPvPHP*)_pvp)->SetHordeTowersControlled(++horde_towers);
                sWorld->SendZoneText(OutdoorPvPHPBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(HP_LANG_CAPTURE_H[m_TowerType]));
                break;
            }
        case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
        case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
        case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
        case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
            field = HP_MAP_N[m_TowerType];
            break;
    }
    Map* map = sMapMgr->FindMap(530, 0);
    auto bounds = map->GetGameObjectBySpawnIdStore().equal_range(m_capturePointSpawnId);
    for (auto itr = bounds.first; itr != bounds.second; ++itr)
        itr->second->SetGoArtKit(artkit);
    bounds = map->GetGameObjectBySpawnIdStore().equal_range(_objects[m_TowerType]);
    for (auto itr = bounds.first; itr != bounds.second; ++itr)
        itr->second->SetGoArtKit(artkit2);
    // send world state update
    if (field)
        _pvp->SendUpdateWorldState(field, 1);
    // complete quest objective
    if (_state == OBJECTIVESTATE_ALLIANCE || _state == OBJECTIVESTATE_HORDE)
        SendObjectiveComplete(HP_CREDITMARKER[m_TowerType]);
}
References OPvPCapturePoint::_objects, OPvPCapturePoint::_oldState, OPvPCapturePoint::_pvp, OPvPCapturePoint::_state, Map::GetGameObjectBySpawnIdStore(), HP_CREDITMARKER, HP_LANG_CAPTURE_A, HP_LANG_CAPTURE_H, HP_LANG_LOSE_A, HP_LANG_LOSE_H, HP_MAP_A, HP_MAP_H, HP_MAP_N, HP_TowerArtKit_A, HP_TowerArtKit_H, HP_TowerArtKit_N, OPvPCapturePoint::m_capturePointSpawnId, m_TowerType, OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL, OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE, OutdoorPvPHPBuffZones, OPvPCapturePoint::SendObjectiveComplete(), OutdoorPvP::SendUpdateWorldState(), sMapMgr, sObjectMgr, and sWorld.
FillInitialWorldStates()
void OPvPCapturePointHP::FillInitialWorldStates (WorldPacket & data) override virtual
Reimplemented from OPvPCapturePoint.
{
    switch (_state)
    {
        case OBJECTIVESTATE_ALLIANCE:
        case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
            data << uint32(HP_MAP_N[m_TowerType]) << uint32(0);
            data << uint32(HP_MAP_A[m_TowerType]) << uint32(1);
            data << uint32(HP_MAP_H[m_TowerType]) << uint32(0);
            break;
        case OBJECTIVESTATE_HORDE:
        case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
            data << uint32(HP_MAP_N[m_TowerType]) << uint32(0);
            data << uint32(HP_MAP_A[m_TowerType]) << uint32(0);
            data << uint32(HP_MAP_H[m_TowerType]) << uint32(1);
            break;
        case OBJECTIVESTATE_NEUTRAL:
        case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
        case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
        default:
            data << uint32(HP_MAP_N[m_TowerType]) << uint32(1);
            data << uint32(HP_MAP_A[m_TowerType]) << uint32(0);
            data << uint32(HP_MAP_H[m_TowerType]) << uint32(0);
            break;
    }
}
References OPvPCapturePoint::_state, HP_MAP_A, HP_MAP_H, HP_MAP_N, m_TowerType, OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL, OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE, and OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE.
HandlePlayerEnter()
bool OPvPCapturePointHP::HandlePlayerEnter (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
{
    if (OPvPCapturePoint::HandlePlayerEnter(player))
    {
        player->SendUpdateWorldState(HP_UI_TOWER_SLIDER_DISPLAY, 1);
        uint32 phase = (uint32)ceil((_value + _maxValue) / (2 * _maxValue) * 100.0f);
        player->SendUpdateWorldState(HP_UI_TOWER_SLIDER_POS, phase);
        player->SendUpdateWorldState(HP_UI_TOWER_SLIDER_N, _neutralValuePct);
        return true;
    }
    return false;
}
References OPvPCapturePoint::_maxValue, OPvPCapturePoint::_neutralValuePct, OPvPCapturePoint::_value, OPvPCapturePoint::HandlePlayerEnter(), HP_UI_TOWER_SLIDER_DISPLAY, HP_UI_TOWER_SLIDER_N, HP_UI_TOWER_SLIDER_POS, and Player::SendUpdateWorldState().
HandlePlayerLeave()
void OPvPCapturePointHP::HandlePlayerLeave (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
{
    player->SendUpdateWorldState(HP_UI_TOWER_SLIDER_DISPLAY, 0);
    OPvPCapturePoint::HandlePlayerLeave(player);
}
References OPvPCapturePoint::HandlePlayerLeave(), HP_UI_TOWER_SLIDER_DISPLAY, and Player::SendUpdateWorldState().
SendChangePhase()
void OPvPCapturePointHP::SendChangePhase () override virtual
Reimplemented from OPvPCapturePoint.
{
    SendUpdateWorldState(HP_UI_TOWER_SLIDER_N, _neutralValuePct);
    // send these updates to only the ones in this objective
    uint32 phase = (uint32)ceil((_value + _maxValue) / (2 * _maxValue) * 100.0f);
    SendUpdateWorldState(HP_UI_TOWER_SLIDER_POS, phase);
    // send this too, sometimes the slider disappears, dunno why :(
    SendUpdateWorldState(HP_UI_TOWER_SLIDER_DISPLAY, 1);
}
References OPvPCapturePoint::_maxValue, OPvPCapturePoint::_neutralValuePct, OPvPCapturePoint::_value, HP_UI_TOWER_SLIDER_DISPLAY, HP_UI_TOWER_SLIDER_N, HP_UI_TOWER_SLIDER_POS, and OPvPCapturePoint::SendUpdateWorldState().
Member Data Documentation
m_TowerType
OutdoorPvPHPTowerType OPvPCapturePointHP::m_TowerType private
Referenced by ChangeState(), and FillInitialWorldStates().