AzerothCore: at_naxxramas_hub_portal Class Reference
at_naxxramas_hub_portal Class Reference
Public Member Functions
at_naxxramas_hub_portal ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
at_naxxramas_hub_portal()
at_naxxramas_hub_portal::at_naxxramas_hub_portal () inline
: AreaTriggerScript("at_naxxramas_hub_portal") { }
Member Function Documentation
OnTrigger()
bool at_naxxramas_hub_portal::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (player->IsAlive() && !player->IsInCombat())
        {
            if (InstanceScript *instance = player->GetInstanceScript())
            {
                bool AreAllWingsCleared = instance->GetBossState(BOSS_MAEXXNA) == DONE
                    && (instance->GetBossState(BOSS_LOATHEB) == DONE)
                    && (instance->GetBossState(BOSS_THADDIUS) == DONE)
                    && (instance->GetBossState(BOSS_HORSEMAN) == DONE);
                if (AreAllWingsCleared)
                {
                    player->TeleportTo(533, sapphironEntryTP.m_positionX, sapphironEntryTP.m_positionY, sapphironEntryTP.m_positionZ, sapphironEntryTP.m_orientation);
                    return true;
                }
            }
        }
        return false;
    }
References BOSS_HORSEMAN, BOSS_LOATHEB, BOSS_MAEXXNA, BOSS_THADDIUS, DONE, WorldObject::GetInstanceScript(), Unit::IsAlive(), Unit::IsInCombat(), Position::m_orientation, Position::m_positionX, Position::m_positionY, Position::m_positionZ, sapphironEntryTP, and Player::TeleportTo().