AzerothCore: boss_taldaram Struct Reference
boss_taldaram Struct Reference
Public Member Functions
boss_taldaram (Creature *pCreature)
void InitializeAI () override
void Reset () override
void DoAction (int32 action) override
void MovementInform (uint32 type, uint32 id) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void SpellHitTarget (Unit *, SpellInfo const *spellInfo) override
void JustSummoned (Creature *summon) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Member Functions
void ScheduleCombatEvents ()
Private Attributes
Position victimSperePos
ObjectGuid vanishTarget_GUID
uint32 vanishDamage
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_taldaram()
boss_taldaram::boss_taldaram (Creature * pCreature) inline
                                       : BossAI(pCreature, DATA_PRINCE_TALDARAM),
        vanishDamage(0)
    {
    }
Member Function Documentation
DamageTaken()
void boss_taldaram::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
    {
        if (vanishTarget_GUID)
        {
            if (me->FindCurrentSpellBySpellId(SPELL_EMBRACE_OF_THE_VAMPYR))
            {
                vanishDamage += damage;
                if (vanishDamage >= DUNGEON_MODE<uint32>(MAX_EMBRACE_DMG, MAX_EMBRACE_DMG_H))
                {
                    ScheduleCombatEvents();
                    me->CastStop();
                    vanishTarget_GUID.Clear();
                    vanishDamage = 0;
                }
            }
        }
    }
References Unit::CastStop(), ObjectGuid::Clear(), Unit::FindCurrentSpellBySpellId(), MAX_EMBRACE_DMG, MAX_EMBRACE_DMG_H, ScriptedAI::me, ScheduleCombatEvents(), SPELL_EMBRACE_OF_THE_VAMPYR, vanishDamage, and vanishTarget_GUID.
DoAction()
void boss_taldaram::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        if (action == ACTION_REMOVE_PRISON || action == ACTION_REMOVE_PRISON_AT_RESET)
        {
            me->SetHomePosition(me->GetPositionX(), me->GetPositionY(), DATA_GROUND_POSITION_Z, me->GetOrientation());
            instance->HandleGameObject(instance->GetGuidData(DATA_PRINCE_TALDARAM_PLATFORM), true);
            if (action == ACTION_REMOVE_PRISON)
            {
                DoCastSelf(SPELL_HOVER_FALL);
                me->GetMotionMaster()->Clear();
                me->GetMotionMaster()->MoveLand(POINT_LAND, me->GetHomePosition(), 8.0f);
                Talk(SAY_REMOVE_PRISON);
            }
            // Teleport instantly
            else
            {
                me->SetDisableGravity(false);
                me->SetHover(false);
                me->RemoveAllAuras();
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE| UNIT_FLAG_NOT_SELECTABLE);
                me->SetImmuneToAll(false);
                me->UpdatePosition(me->GetHomePosition(), true);
            }
            summons.DespawnEntry(NPC_JEDOGA_CONTROLLER);
        }
    }
References ACTION_REMOVE_PRISON, ACTION_REMOVE_PRISON_AT_RESET, MotionMaster::Clear(), DATA_GROUND_POSITION_Z, DATA_PRINCE_TALDARAM_PLATFORM, SummonList::DespawnEntry(), UnitAI::DoCastSelf(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), InstanceScript::HandleGameObject(), BossAI::instance, ScriptedAI::me, MotionMaster::MoveLand(), NPC_JEDOGA_CONTROLLER, POINT_LAND, Unit::RemoveAllAuras(), Unit::RemoveUnitFlag(), SAY_REMOVE_PRISON, Creature::SetDisableGravity(), Creature::SetHomePosition(), Creature::SetHover(), Unit::SetImmuneToAll(), SPELL_HOVER_FALL, BossAI::summons, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and Unit::UpdatePosition().
Referenced by InitializeAI().
InitializeAI()
void boss_taldaram::InitializeAI () inline override virtual
Reimplemented from UnitAI.
    {
        BossAI::InitializeAI();
        // Event not started
        if (instance->GetPersistentData(DATA_TELDRAM_SPHERE1) != DONE || instance->GetPersistentData(DATA_TELDRAM_SPHERE2) != DONE)
        {
            me->SetImmuneToAll(true);
            me->SetDisableGravity(true);
            me->SetHover(true);
            if (!me->HasAura(SPELL_BEAM_VISUAL))
            {
                DoCastSelf(SPELL_BEAM_VISUAL, true);
            }
            me->SummonCreatureGroup(SUMMON_GROUP_TRIGGERS);
            return;
        }
        if (instance->GetPersistentData(DATA_TELDRAM_SPHERE1) == DONE && instance->GetPersistentData(DATA_TELDRAM_SPHERE2) == DONE)
        {
            DoAction(ACTION_REMOVE_PRISON_AT_RESET);
        }
    }
References ACTION_REMOVE_PRISON_AT_RESET, DATA_TELDRAM_SPHERE1, DATA_TELDRAM_SPHERE2, DoAction(), UnitAI::DoCastSelf(), DONE, InstanceScript::GetPersistentData(), Unit::HasAura(), UnitAI::InitializeAI(), BossAI::instance, ScriptedAI::me, Creature::SetDisableGravity(), Creature::SetHover(), Unit::SetImmuneToAll(), SPELL_BEAM_VISUAL, SUMMON_GROUP_TRIGGERS, and WorldObject::SummonCreatureGroup().
JustDied()
void boss_taldaram::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
    {
        _JustDied();
        Talk(SAY_DEATH);
    }
References BossAI::_JustDied(), and SAY_DEATH.
JustEngagedWith()
void boss_taldaram::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        _JustEngagedWith();
        Talk(SAY_AGGRO);
        ScheduleCombatEvents();
        me->RemoveAllAuras();
        me->InterruptNonMeleeSpells(true);
    }
References BossAI::_JustEngagedWith(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, Unit::RemoveAllAuras(), SAY_AGGRO, and ScheduleCombatEvents().
JustSummoned()
void boss_taldaram::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
    {
        summons.Summon(summon);
        switch (summon->GetEntry())
        {
            case NPC_FLAME_SPHERE_1:
            case NPC_FLAME_SPHERE_2:
            case NPC_FLAME_SPHERE_3:
            {
                if (npc_taldaram_flamesphere* summonAI = dynamic_cast<npc_taldaram_flamesphere*>(summon->AI()))
                {
                    summonAI->SetVictimPos(victimSperePos);
                }
                break;
            }
            case NPC_JEDOGA_CONTROLLER:
            {
                summon->CastSpell(nullptr, SPELL_BEAM_VISUAL);
                break;
            }
        }
    }
References Creature::AI(), Unit::CastSpell(), Object::GetEntry(), NPC_FLAME_SPHERE_1, NPC_FLAME_SPHERE_2, NPC_FLAME_SPHERE_3, NPC_JEDOGA_CONTROLLER, SPELL_BEAM_VISUAL, SummonList::Summon(), BossAI::summons, and victimSperePos.
KilledUnit()
void boss_taldaram::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (!victim->IsPlayer())
        {
            return;
        }
        Talk(SAY_SLAY);
        if (vanishTarget_GUID && victim->GetGUID() == vanishTarget_GUID)
        {
            vanishTarget_GUID.Clear();
            vanishDamage = 0;
        }
    }
References ObjectGuid::Clear(), Object::GetGUID(), Object::IsPlayer(), SAY_SLAY, vanishDamage, and vanishTarget_GUID.
MovementInform()
void boss_taldaram::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type == EFFECT_MOTION_TYPE && id == POINT_LAND)
        {
            me->SetDisableGravity(false);
            me->SetHover(false);
            me->RemoveAllAuras();
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE| UNIT_FLAG_NOT_SELECTABLE);
            me->SetImmuneToAll(false);
        }
    }
References EFFECT_MOTION_TYPE, ScriptedAI::me, POINT_LAND, Unit::RemoveAllAuras(), Unit::RemoveUnitFlag(), Creature::SetDisableGravity(), Creature::SetHover(), Unit::SetImmuneToAll(), UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
Reset()
void boss_taldaram::Reset () inline override virtual
Reimplemented from BossAI.
    {
        _Reset();
        vanishDamage = 0;
        vanishTarget_GUID.Clear();
    }
References BossAI::_Reset(), ObjectGuid::Clear(), vanishDamage, and vanishTarget_GUID.
ScheduleCombatEvents()
void boss_taldaram::ScheduleCombatEvents () inline private
    {
        events.Reset();
        events.RescheduleEvent(EVENT_PRINCE_FLAME_SPHERES, 10s);
        events.RescheduleEvent(EVENT_PRINCE_BLOODTHIRST, 10s);
        vanishTarget_GUID.Clear();
        vanishDamage = 0;
    }
References ObjectGuid::Clear(), EVENT_PRINCE_BLOODTHIRST, EVENT_PRINCE_FLAME_SPHERES, vanishDamage, and vanishTarget_GUID.
Referenced by DamageTaken(), JustEngagedWith(), and UpdateAI().
SpellHitTarget()
void boss_taldaram::SpellHitTarget (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (spellInfo->Id == SPELL_CONJURE_FLAME_SPHERE)
        {
            summons.DoAction(ACTION_SPHERE);
        }
    }
References ACTION_SPHERE, SummonList::DoAction(), SpellInfo::Id, SPELL_CONJURE_FLAME_SPHERE, and BossAI::summons.
UpdateAI()
void boss_taldaram::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
    {
        if (!UpdateVictim())
        {
            return;
        }
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
        while (uint32 const eventId = events.ExecuteEvent())
        {
            switch (eventId)
            {
                case EVENT_PRINCE_BLOODTHIRST:
                {
                    DoCastSelf(SPELL_BLOODTHIRST);
                    events.Repeat(10s);
                    break;
                }
                case EVENT_PRINCE_FLAME_SPHERES:
                {
                    if (Unit* victim = me->GetVictim())
                    {
                        DoCast(victim, SPELL_CONJURE_FLAME_SPHERE);
                        victimSperePos = *victim;
                    }
                    if (!events.GetNextEventTime(EVENT_PRINCE_VANISH))
                    {
                        events.RescheduleEvent(EVENT_PRINCE_VANISH, 14s);
                    }
                    else
                    {
                        // Make sure that Vanish won't get triggered at same time as sphere summon
                        events.DelayEvents(4s);
                    }
                    events.Repeat(15s);
                    break;
                }
                case EVENT_PRINCE_VANISH:
                {
                    //Count alive players
                    uint8 count = 0;
                    std::list<HostileReference*> const t_list = me->GetThreatMgr().GetThreatList();
                    if (!t_list.empty())
                    {
                        for (HostileReference const* reference : t_list)
{
                            if (reference)
{
                                Unit const* pTarget = ObjectAccessor::GetUnit(*me, reference->getUnitGuid());
                                if (pTarget && pTarget->IsPlayer() && pTarget->IsAlive())
{
                                    ++count;
                                }
                            }
                        }
                    }
                    // He only vanishes if there are 3 or more alive players
                    if (count > 2)
                    {
                        Talk(SAY_VANISH);
                        DoCastSelf(SPELL_VANISH, false);
                        if (Unit* pEmbraceTarget = SelectTarget(SelectTargetMethod::Random, 0, 100, true))
{
                            vanishTarget_GUID = pEmbraceTarget->GetGUID();
                        }
                        events.CancelEvent(EVENT_PRINCE_FLAME_SPHERES);
                        events.CancelEvent(EVENT_PRINCE_BLOODTHIRST);
                        events.ScheduleEvent(EVENT_PRINCE_VANISH_RUN, 2499ms);
                    }
                    break;
                }
                case EVENT_PRINCE_VANISH_RUN:
                {
                    if (Unit* _vanishTarget = ObjectAccessor::GetUnit(*me, vanishTarget_GUID))
                    {
                        vanishDamage = 0;
                        DoCast(_vanishTarget, SPELL_SHADOWSTEP);
                        me->CastSpell(_vanishTarget, SPELL_EMBRACE_OF_THE_VAMPYR, false);
                        me->RemoveAura(SPELL_VANISH);
                    }
                    events.ScheduleEvent(EVENT_PRINCE_RESCHEDULE, 20s);
                    break;
                }
                case EVENT_PRINCE_RESCHEDULE:
                {
                    ScheduleCombatEvents();
                    break;
                }
            }
            if (me->HasUnitState(UNIT_STATE_CASTING))
            {
                return;
            }
        }
        if (me->IsVisible())
        {
            DoMeleeAttackIfReady();
        }
    }
References Unit::CastSpell(), UnitAI::DoCast(), UnitAI::DoCastSelf(), UnitAI::DoMeleeAttackIfReady(), EVENT_PRINCE_BLOODTHIRST, EVENT_PRINCE_FLAME_SPHERES, EVENT_PRINCE_RESCHEDULE, EVENT_PRINCE_VANISH, EVENT_PRINCE_VANISH_RUN, ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::HasUnitState(), Unit::IsAlive(), Object::IsPlayer(), Unit::IsVisible(), ScriptedAI::me, Unit::RemoveAura(), SAY_VANISH, ScheduleCombatEvents(), UnitAI::SelectTarget(), SPELL_BLOODTHIRST, SPELL_CONJURE_FLAME_SPHERE, SPELL_EMBRACE_OF_THE_VAMPYR, SPELL_SHADOWSTEP, SPELL_VANISH, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), vanishDamage, vanishTarget_GUID, and victimSperePos.
Member Data Documentation
vanishDamage
uint32 boss_taldaram::vanishDamage private
Referenced by DamageTaken(), KilledUnit(), Reset(), ScheduleCombatEvents(), and UpdateAI().
vanishTarget_GUID
ObjectGuid boss_taldaram::vanishTarget_GUID private
Referenced by DamageTaken(), KilledUnit(), Reset(), ScheduleCombatEvents(), and UpdateAI().
victimSperePos
Position boss_taldaram::victimSperePos private
Referenced by JustSummoned(), and UpdateAI().