AzerothCore: Guild::RankInfo Class Reference
Guild::RankInfo Class Reference
Public Member Functions
RankInfo ()
RankInfo (uint32 guildId)
RankInfo (uint32 guildId, uint8 rankId, std::string_view name, uint32 rights, uint32 money)
void LoadFromDB (Field *fields)
void SaveToDB (CharacterDatabaseTransaction trans) const
uint8 GetId () const
std::string const & GetName () const
void SetName (std::string_view name)
uint32 GetRights () const
void SetRights (uint32 rights)
int32 GetBankMoneyPerDay () const
void SetBankMoneyPerDay (uint32 money)
int8 GetBankTabRights (uint8 tabId) const
int32 GetBankTabSlotsPerDay (uint8 tabId) const
void SetBankTabSlotsAndRights (GuildBankRightsAndSlots rightsAndSlots, bool saveToDB)
void CreateMissingTabsIfNeeded (uint8 ranks, CharacterDatabaseTransaction trans, bool logOnCreate=false)
Private Attributes
uint32 m_guildId
uint8 m_rankId
std::string m_name
uint32 m_rights
uint32 m_bankMoneyPerDay
std::array< GuildBankRightsAndSlots, GUILD_BANK_MAX_TABS > m_bankTabRightsAndSlots = {}
Detailed Description
Constructor & Destructor Documentation
RankInfo() [1/3]
Guild::RankInfo::RankInfo () inline
: m_guildId(0), m_rankId(GUILD_RANK_NONE), m_rights(GR_RIGHT_EMPTY), m_bankMoneyPerDay(0) { }
RankInfo() [2/3]
Guild::RankInfo::RankInfo (uint32 guildId) inline
: m_guildId(guildId), m_rankId(GUILD_RANK_NONE), m_rights(GR_RIGHT_EMPTY), m_bankMoneyPerDay(0) { }
RankInfo() [3/3]
Guild::RankInfo::RankInfo (uint32 guildId, uint8 rankId, std::string_view name, uint32 rights, uint32 money) inline
                                                                                                 :
            m_guildId(guildId), m_rankId(rankId), m_name(name), m_rights(rights),
            m_bankMoneyPerDay(rankId != GR_GUILDMASTER ? money : GUILD_WITHDRAW_MONEY_UNLIMITED) { }
Member Function Documentation
CreateMissingTabsIfNeeded()
void Guild::RankInfo::CreateMissingTabsIfNeeded (uint8 ranks, CharacterDatabaseTransaction trans, bool logOnCreate = false)
{
    for (uint8 i = 0; i < tabs; ++i)
    {
        GuildBankRightsAndSlots& rightsAndSlots = m_bankTabRightsAndSlots[i];
        if (rightsAndSlots.GetTabId() == i)
            continue;
        rightsAndSlots.SetTabId(i);
        if (m_rankId == GR_GUILDMASTER)
            rightsAndSlots.SetGuildMasterValues();
        if (logOnCreate)
            LOG_ERROR("guild", "Guild {} has broken Tab {} for rank {}. Created default tab.", m_guildId, i, m_rankId);
        CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_BANK_RIGHT);
        stmt->SetData(0, m_guildId);
        stmt->SetData(1, i);
        stmt->SetData(2, m_rankId);
        stmt->SetData(3, rightsAndSlots.GetRights());
        stmt->SetData(4, rightsAndSlots.GetSlots());
        trans->Append(stmt);
    }
}
References CHAR_INS_GUILD_BANK_RIGHT, CharacterDatabase, GuildBankRightsAndSlots::GetRights(), GuildBankRightsAndSlots::GetSlots(), GuildBankRightsAndSlots::GetTabId(), GR_GUILDMASTER, LOG_ERROR, PreparedStatementBase::SetData(), GuildBankRightsAndSlots::SetGuildMasterValues(), and GuildBankRightsAndSlots::SetTabId().
Referenced by Guild::_CreateRank(), and Guild::Validate().
GetBankMoneyPerDay()
int32 Guild::RankInfo::GetBankMoneyPerDay () const inline
{ return m_bankMoneyPerDay; }
References m_bankMoneyPerDay.
GetBankTabRights()
int8 Guild::RankInfo::GetBankTabRights (uint8 tabId) const inline
        {
            return tabId < GUILD_BANK_MAX_TABS ? m_bankTabRightsAndSlots[tabId].GetRights() : 0;
        }
References GUILD_BANK_MAX_TABS, and m_bankTabRightsAndSlots.
GetBankTabSlotsPerDay()
int32 Guild::RankInfo::GetBankTabSlotsPerDay (uint8 tabId) const inline
        {
            return tabId < GUILD_BANK_MAX_TABS ? m_bankTabRightsAndSlots[tabId].GetSlots() : 0;
        }
References GUILD_BANK_MAX_TABS, and m_bankTabRightsAndSlots.
GetId()
uint8 Guild::RankInfo::GetId () const inline
{ return m_rankId; }
References m_rankId.
Referenced by Guild::Validate().
GetName()
std::string const & Guild::RankInfo::GetName () const inline
{ return m_name; }
References m_name.
GetRights()
uint32 Guild::RankInfo::GetRights () const inline
{ return m_rights; }
References m_rights.
LoadFromDB()
void Guild::RankInfo::LoadFromDB (Field * fields)
{
    m_rankId            = fields[1].Get<uint8>();
    m_name              = fields[2].Get<std::string>();
    m_rights            = fields[3].Get<uint32>();
    m_bankMoneyPerDay   = fields[4].Get<uint32>();
    if (m_rankId == GR_GUILDMASTER)                     // Prevent loss of leader rights
        m_rights |= GR_RIGHT_ALL;
}
References Field::Get(), GR_GUILDMASTER, GR_RIGHT_ALL, and Guild::m_name.
Referenced by Guild::LoadRankFromDB().
SaveToDB()
void Guild::RankInfo::SaveToDB (CharacterDatabaseTransaction trans) const
{
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_RANK);
    stmt->SetData(0, m_guildId);
    stmt->SetData (1, m_rankId);
    stmt->SetData(2, m_name);
    stmt->SetData(3, m_rights);
    stmt->SetData(4, m_bankMoneyPerDay);
    CharacterDatabase.ExecuteOrAppend(trans, stmt);
}
References CHAR_INS_GUILD_RANK, CharacterDatabase, Guild::m_name, and PreparedStatementBase::SetData().
Referenced by Guild::_CreateRank().
SetBankMoneyPerDay()
void Guild::RankInfo::SetBankMoneyPerDay (uint32 money)
{
    if (m_rankId == GR_GUILDMASTER)                     // Prevent loss of leader rights
        money = uint32(GUILD_WITHDRAW_MONEY_UNLIMITED);
    if (m_bankMoneyPerDay == money)
        return;
    m_bankMoneyPerDay = money;
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_RANK_BANK_MONEY);
    stmt->SetData(0, money);
    stmt->SetData (1, m_rankId);
    stmt->SetData(2, m_guildId);
    CharacterDatabase.Execute(stmt);
}
References CHAR_UPD_GUILD_RANK_BANK_MONEY, CharacterDatabase, GR_GUILDMASTER, GUILD_WITHDRAW_MONEY_UNLIMITED, and PreparedStatementBase::SetData().
SetBankTabSlotsAndRights()
void Guild::RankInfo::SetBankTabSlotsAndRights (GuildBankRightsAndSlots rightsAndSlots, bool saveToDB)
{
    if (m_rankId == GR_GUILDMASTER)                     // Prevent loss of leader rights
        rightsAndSlots.SetGuildMasterValues();
    GuildBankRightsAndSlots& guildBR = m_bankTabRightsAndSlots[rightsAndSlots.GetTabId()];
    guildBR = rightsAndSlots;
    if (saveToDB)
    {
        CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_BANK_RIGHT);
        stmt->SetData(0, m_guildId);
        stmt->SetData (1, guildBR.GetTabId());
        stmt->SetData (2, m_rankId);
        stmt->SetData (3, guildBR.GetRights());
        stmt->SetData(4, guildBR.GetSlots());
        CharacterDatabase.Execute(stmt);
    }
}
References CHAR_INS_GUILD_BANK_RIGHT, CharacterDatabase, GuildBankRightsAndSlots::GetRights(), GuildBankRightsAndSlots::GetSlots(), GuildBankRightsAndSlots::GetTabId(), GR_GUILDMASTER, PreparedStatementBase::SetData(), and GuildBankRightsAndSlots::SetGuildMasterValues().
SetName()
void Guild::RankInfo::SetName (std::string_view name)
{
    if (m_name == name)
        return;
    m_name = name;
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_RANK_NAME);
    stmt->SetData(0, m_name);
    stmt->SetData (1, m_rankId);
    stmt->SetData(2, m_guildId);
    CharacterDatabase.Execute(stmt);
}
References CHAR_UPD_GUILD_RANK_NAME, CharacterDatabase, Guild::m_name, and PreparedStatementBase::SetData().
SetRights()
void Guild::RankInfo::SetRights (uint32 rights)
{
    if (m_rankId == GR_GUILDMASTER)                     // Prevent loss of leader rights
        rights = GR_RIGHT_ALL;
    if (m_rights == rights)
        return;
    m_rights = rights;
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_RANK_RIGHTS);
    stmt->SetData(0, m_rights);
    stmt->SetData (1, m_rankId);
    stmt->SetData(2, m_guildId);
    CharacterDatabase.Execute(stmt);
}
References CHAR_UPD_GUILD_RANK_RIGHTS, CharacterDatabase, GR_GUILDMASTER, GR_RIGHT_ALL, and PreparedStatementBase::SetData().
Member Data Documentation
m_bankMoneyPerDay
uint32 Guild::RankInfo::m_bankMoneyPerDay private
Referenced by GetBankMoneyPerDay().
m_bankTabRightsAndSlots
std::array<GuildBankRightsAndSlots, GUILD_BANK_MAX_TABS> Guild::RankInfo::m_bankTabRightsAndSlots = {} private
Referenced by GetBankTabRights(), and GetBankTabSlotsPerDay().
m_guildId
uint32 Guild::RankInfo::m_guildId private
m_name
std::string Guild::RankInfo::m_name private
Referenced by GetName().
m_rankId
uint8 Guild::RankInfo::m_rankId private
Referenced by GetId().
m_rights
uint32 Guild::RankInfo::m_rights private
Referenced by GetRights().