AzerothCore: RedirectThreatInfo Struct Reference
RedirectThreatInfo Struct Reference
#include "ThreatMgr.h"
Public Member Functions
RedirectThreatInfo ()=default
ObjectGuid GetTargetGUID () const
uint32 GetThreatPct () const
void Set (ObjectGuid guid, uint32 pct)
void ModifyThreatPct (int32 amount)
Public Attributes
ObjectGuid _targetGUID
uint32 _threatPct { 0 }
Detailed Description
Constructor & Destructor Documentation
RedirectThreatInfo()
RedirectThreatInfo::RedirectThreatInfo () default
Member Function Documentation
GetTargetGUID()
ObjectGuid RedirectThreatInfo::GetTargetGUID () const inline
{ return _targetGUID; }
References _targetGUID.
Referenced by Unit::GetRedirectThreatTarget().
GetThreatPct()
uint32 RedirectThreatInfo::GetThreatPct () const inline
{ return _threatPct; }
References _threatPct.
Referenced by Unit::GetRedirectThreatPercent().
ModifyThreatPct()
void RedirectThreatInfo::ModifyThreatPct (int32 amount) inline
    {
        amount += _threatPct;
        _threatPct = uint32(std::max(0, amount));
    }
References _threatPct.
Referenced by Unit::ModifyRedirectThreat().
Set()
void RedirectThreatInfo::Set (ObjectGuid guid, uint32 pct) inline
    {
        _targetGUID = guid;
        _threatPct = pct;
    }
References _targetGUID, and _threatPct.
Referenced by Unit::SetRedirectThreat().
Member Data Documentation
_targetGUID
ObjectGuid RedirectThreatInfo::_targetGUID
Referenced by GetTargetGUID(), and Set().
_threatPct
uint32 RedirectThreatInfo::_threatPct { 0 }
Referenced by GetThreatPct(), ModifyThreatPct(), and Set().