AzerothCore: WorldSession::DosProtection Class Reference
WorldSession::DosProtection Class Reference
#include "WorldSession.h"
Public Member Functions
DosProtection (WorldSession *s)
bool EvaluateOpcode (WorldPacket &p, time_t time) const
Protected Types
enum Policy {
POLICY_LOG ,
POLICY_KICK ,
POLICY_BAN
}
Protected Member Functions
uint32 GetMaxPacketCounterAllowed (uint16 opcode) const
Protected Attributes
WorldSession * Session
Private Types
typedef std::unordered_map< uint16, PacketCounter > PacketThrottlingMap
Private Member Functions
DosProtection (DosProtection const &right)=delete
DosProtection & operator= (DosProtection const &right)=delete
Private Attributes
Policy _policy
PacketThrottlingMap _PacketThrottlingMap
Friends
class World
Detailed Description
Member Typedef Documentation
PacketThrottlingMap
typedef std::unordered_map<uint16, PacketCounter> WorldSession::DosProtection::PacketThrottlingMap private
Member Enumeration Documentation
Policy
enum WorldSession::DosProtection::Policy protected
Enumerator
POLICY_LOG
POLICY_KICK
POLICY_BAN
        {
            POLICY_LOG,
            POLICY_KICK,
            POLICY_BAN
        };
Constructor & Destructor Documentation
DosProtection() [1/2]
WorldSession::DosProtection::DosProtection (WorldSession * s)
                                                        :
    Session(s), _policy((Policy)sWorld->getIntConfig(CONFIG_PACKET_SPOOF_POLICY)) { }
DosProtection() [2/2]
WorldSession::DosProtection::DosProtection (DosProtection const & right) private delete
Member Function Documentation
EvaluateOpcode()
bool WorldSession::DosProtection::EvaluateOpcode (WorldPacket & p, time_t time) const
{
    uint32 maxPacketCounterAllowed = GetMaxPacketCounterAllowed(p.GetOpcode());
    // Return true if there no limit for the opcode
    if (!maxPacketCounterAllowed)
        return true;
    PacketCounter& packetCounter = _PacketThrottlingMap[p.GetOpcode()];
    if (packetCounter.lastReceiveTime != time)
    {
        packetCounter.lastReceiveTime = time;
        packetCounter.amountCounter = 0;
    }
    // Check if player is flooding some packets
    if (++packetCounter.amountCounter <= maxPacketCounterAllowed)
        return true;
    LOG_WARN("network", "AntiDOS: Account {}, IP: {}, Ping: {}, Character: {}, flooding packet (opc: {} (0x{:X}), count: {})",
        Session->GetAccountId(), Session->GetRemoteAddress(), Session->GetLatency(), Session->GetPlayerName(),
        opcodeTable[static_cast<OpcodeClient>(p.GetOpcode())]->Name, p.GetOpcode(), packetCounter.amountCounter);
    switch (_policy)
    {
        case POLICY_LOG:
            return true;
        case POLICY_KICK:
            {
                LOG_INFO("network", "AntiDOS: Player {} kicked!", Session->GetPlayerName());
                Session->KickPlayer();
                return false;
            }
        case POLICY_BAN:
            {
                uint32 bm = sWorld->getIntConfig(CONFIG_PACKET_SPOOF_BANMODE);
                uint32 duration = sWorld->getIntConfig(CONFIG_PACKET_SPOOF_BANDURATION); // in seconds
                std::string nameOrIp = "";
                switch (bm)
                {
                    case 0: // Ban account
                        (void)AccountMgr::GetName(Session->GetAccountId(), nameOrIp);
                        sBan->BanAccount(nameOrIp, std::to_string(duration), "DOS (Packet Flooding/Spoofing", "Server: AutoDOS");
                        break;
                    case 1: // Ban ip
                        nameOrIp = Session->GetRemoteAddress();
                        sBan->BanIP(nameOrIp, std::to_string(duration), "DOS (Packet Flooding/Spoofing", "Server: AutoDOS");
                        break;
                }
                LOG_INFO("network", "AntiDOS: Player automatically banned for {} seconds.", duration);
                return false;
            }
        default: // invalid policy
            return true;
    }
}
References _PacketThrottlingMap, _policy, PacketCounter::amountCounter, CONFIG_PACKET_SPOOF_BANDURATION, CONFIG_PACKET_SPOOF_BANMODE, WorldSession::GetAccountId(), WorldSession::GetLatency(), GetMaxPacketCounterAllowed(), AccountMgr::GetName(), WorldPacket::GetOpcode(), WorldSession::GetPlayerName(), WorldSession::GetRemoteAddress(), WorldSession::KickPlayer(), PacketCounter::lastReceiveTime, LOG_INFO, LOG_WARN, opcodeTable, POLICY_BAN, POLICY_KICK, POLICY_LOG, sBan, Session, and sWorld.
Referenced by WorldSession::Update().
GetMaxPacketCounterAllowed()
uint32 WorldSession::DosProtection::GetMaxPacketCounterAllowed (uint16 opcode) const protected
{
    uint32 maxPacketCounterAllowed;
    switch (opcode)
    {
        // CPU usage sending 2000 packets/second on a 3.70 GHz 4 cores on Win x64
        //                                              [% CPU mysqld]   [%CPU worldserver RelWithDebInfo]
        case CMSG_PLAYER_LOGIN:                         //   0               0.5
        case CMSG_NAME_QUERY:                           //   0               1
        case CMSG_PET_NAME_QUERY:                       //   0               1
        case CMSG_NPC_TEXT_QUERY:                       //   0               1
        case CMSG_ATTACKSTOP:                           //   0               1
        case CMSG_QUERY_QUESTS_COMPLETED:               //   0               1
        case CMSG_QUERY_TIME:                           //   0               1
        case CMSG_CORPSE_MAP_POSITION_QUERY:            //   0               1
        case CMSG_MOVE_TIME_SKIPPED:                    //   0               1
        case MSG_QUERY_NEXT_MAIL_TIME:                  //   0               1
        case CMSG_SET_SHEATHED:                         //   0               1
        case MSG_RAID_TARGET_UPDATE:                    //   0               1
        case CMSG_PLAYER_LOGOUT:                        //   0               1
        case CMSG_LOGOUT_REQUEST:                       //   0               1
        case CMSG_PET_RENAME:                           //   0               1
        case CMSG_QUESTGIVER_CANCEL:                    //   0               1
        case CMSG_QUESTGIVER_REQUEST_REWARD:            //   0               1
        case CMSG_COMPLETE_CINEMATIC:                   //   0               1
        case CMSG_BANKER_ACTIVATE:                      //   0               1
        case CMSG_BUY_BANK_SLOT:                        //   0               1
        case CMSG_OPT_OUT_OF_LOOT:                      //   0               1
        case CMSG_DUEL_ACCEPTED:                        //   0               1
        case CMSG_DUEL_CANCELLED:                       //   0               1
        case CMSG_CALENDAR_COMPLAIN:                    //   0               1
        case CMSG_QUEST_QUERY:                          //   0               1.5
        case CMSG_ITEM_QUERY_SINGLE:                    //   0               1.5
        case CMSG_ITEM_NAME_QUERY:                      //   0               1.5
        case CMSG_GAMEOBJECT_QUERY:                     //   0               1.5
        case CMSG_CREATURE_QUERY:                       //   0               1.5
        case CMSG_QUESTGIVER_STATUS_QUERY:              //   0               1.5
        case CMSG_GUILD_QUERY:                          //   0               1.5
        case CMSG_ARENA_TEAM_QUERY:                     //   0               1.5
        case CMSG_TAXINODE_STATUS_QUERY:                //   0               1.5
        case CMSG_TAXIQUERYAVAILABLENODES:              //   0               1.5
        case CMSG_QUESTGIVER_QUERY_QUEST:               //   0               1.5
        case CMSG_PAGE_TEXT_QUERY:                      //   0               1.5
        case MSG_QUERY_GUILD_BANK_TEXT:                 //   0               1.5
        case MSG_CORPSE_QUERY:                          //   0               1.5
        case MSG_MOVE_SET_FACING:                       //   0               1.5
        case CMSG_REQUEST_PARTY_MEMBER_STATS:           //   0               1.5
        case CMSG_QUESTGIVER_COMPLETE_QUEST:            //   0               1.5
        case CMSG_SET_ACTION_BUTTON:                    //   0               1.5
        case CMSG_RESET_INSTANCES:                      //   0               1.5
        case CMSG_HEARTH_AND_RESURRECT:                 //   0               1.5
        case CMSG_TOGGLE_PVP:                           //   0               1.5
        case CMSG_PET_ABANDON:                          //   0               1.5
        case CMSG_ACTIVATETAXIEXPRESS:                  //   0               1.5
        case CMSG_ACTIVATETAXI:                         //   0               1.5
        case CMSG_SELF_RES:                             //   0               1.5
        case CMSG_UNLEARN_SKILL:                        //   0               1.5
        case CMSG_EQUIPMENT_SET_SAVE:                   //   0               1.5
        case CMSG_DELETEEQUIPMENT_SET:                  //   0               1.5
        case CMSG_DISMISS_CRITTER:                      //   0               1.5
        case CMSG_REPOP_REQUEST:                        //   0               1.5
        case CMSG_GROUP_INVITE:                         //   0               1.5
        case CMSG_GROUP_DECLINE:                        //   0               1.5
        case CMSG_GROUP_ACCEPT:                         //   0               1.5
        case CMSG_GROUP_UNINVITE_GUID:                  //   0               1.5
        case CMSG_GROUP_UNINVITE:                       //   0               1.5
        case CMSG_GROUP_DISBAND:                        //   0               1.5
        case CMSG_BATTLEMASTER_JOIN_ARENA:              //   0               1.5
        case CMSG_LEAVE_BATTLEFIELD:                    //   0               1.5
        case MSG_GUILD_BANK_LOG_QUERY:                  //   0               2
        case CMSG_LOGOUT_CANCEL:                        //   0               2
        case CMSG_REALM_SPLIT:                          //   0               2
        case CMSG_ALTER_APPEARANCE:                     //   0               2
        case CMSG_QUEST_CONFIRM_ACCEPT:                 //   0               2
        case MSG_GUILD_EVENT_LOG_QUERY:                 //   0               2.5
        case CMSG_READY_FOR_ACCOUNT_DATA_TIMES:         //   0               2.5
        case CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY:     //   0               2.5
        case CMSG_BEGIN_TRADE:                          //   0               2.5
        case CMSG_INITIATE_TRADE:                       //   0               3
        case CMSG_MESSAGECHAT:                          //   0               3.5
        case CMSG_INSPECT:                              //   0               3.5
        case CMSG_AREA_SPIRIT_HEALER_QUERY:             // not profiled
        case CMSG_STANDSTATECHANGE:                     // not profiled
        case MSG_RANDOM_ROLL:                           // not profiled
        case CMSG_TIME_SYNC_RESP:                       // not profiled
        case CMSG_TRAINER_BUY_SPELL:                    // not profiled
        case CMSG_FORCE_SWIM_SPEED_CHANGE_ACK:          // not profiled
        case CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK:     // not profiled
        case CMSG_FORCE_RUN_SPEED_CHANGE_ACK:           // not profiled
        case CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK:      // not profiled
        case CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK:        // not profiled
        case CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK:   // not profiled
        case CMSG_FORCE_WALK_SPEED_CHANGE_ACK:          // not profiled
        case CMSG_FORCE_TURN_RATE_CHANGE_ACK:           // not profiled
        case CMSG_FORCE_PITCH_RATE_CHANGE_ACK:          // not profiled
            {
                // "0" is a magic number meaning there's no limit for the opcode.
                // All the opcodes above must cause little CPU usage and no sync/async database queries at all
                maxPacketCounterAllowed = 0;
                break;
            }
        case CMSG_QUESTGIVER_ACCEPT_QUEST:              //   0               4
        case CMSG_QUESTLOG_REMOVE_QUEST:                //   0               4
        case CMSG_QUESTGIVER_CHOOSE_REWARD:             //   0               4
        case CMSG_CONTACT_LIST:                         //   0               5
        case CMSG_LEARN_PREVIEW_TALENTS:                //   0               6
        case CMSG_AUTOBANK_ITEM:                        //   0               6
        case CMSG_AUTOSTORE_BANK_ITEM:                  //   0               6
        case CMSG_WHO:                                  //   0               7
        case CMSG_PLAYER_VEHICLE_ENTER:                 //   0               8
        case CMSG_LEARN_PREVIEW_TALENTS_PET:            // not profiled
        case MSG_MOVE_HEARTBEAT:
            {
                maxPacketCounterAllowed = 200;
                break;
            }
        case CMSG_GUILD_SET_PUBLIC_NOTE:                //   1               2         1 async db query
        case CMSG_GUILD_SET_OFFICER_NOTE:               //   1               2         1 async db query
        case CMSG_SET_CONTACT_NOTES:                    //   1               2.5       1 async db query
        case CMSG_CALENDAR_GET_CALENDAR:                //   0               1.5       medium upload bandwidth usage
        case CMSG_GUILD_BANK_QUERY_TAB:                 //   0               3.5       medium upload bandwidth usage
        case CMSG_QUERY_INSPECT_ACHIEVEMENTS:           //   0              13         high upload bandwidth usage
        case CMSG_GAMEOBJ_REPORT_USE:                   // not profiled
        case CMSG_GAMEOBJ_USE:                          // not profiled
        case MSG_PETITION_DECLINE:                      // not profiled
            {
                maxPacketCounterAllowed = 50;
                break;
            }
        case CMSG_QUEST_POI_QUERY:                      //   0              25         very high upload bandwidth usage
            {
                maxPacketCounterAllowed = MAX_QUEST_LOG_SIZE;
                break;
            }
        case CMSG_GM_REPORT_LAG:                        //   1               3         1 async db query
        case CMSG_SPELLCLICK:                           // not profiled
        case CMSG_REMOVE_GLYPH:                         // not profiled
        case CMSG_DISMISS_CONTROLLED_VEHICLE:           // not profiled
            {
                maxPacketCounterAllowed = 20;
                break;
            }
        case CMSG_PETITION_SIGN:                        //   9               4         2 sync 1 async db queries
        case CMSG_TURN_IN_PETITION:                     //   8               5.5       2 sync db query
        case CMSG_GROUP_CHANGE_SUB_GROUP:               //   6               5         1 sync 1 async db queries
        case CMSG_PETITION_QUERY:                       //   4               3.5       1 sync db query
        case CMSG_CHAR_RACE_CHANGE:                     //   5               4         1 sync db query
        case CMSG_CHAR_CUSTOMIZE:                       //   5               5         1 sync db query
        case CMSG_CHAR_FACTION_CHANGE:                  //   5               5         1 sync db query
        case CMSG_CHAR_DELETE:                          //   4               4         1 sync db query
        case CMSG_DEL_FRIEND:                           //   7               5         1 async db query
        case CMSG_ADD_FRIEND:                           //   6               4         1 async db query
        case CMSG_CHAR_RENAME:                          //   5               3         1 async db query
        case CMSG_GMSURVEY_SUBMIT:                      //   2               3         1 async db query
        case CMSG_BUG:                                  //   1               1         1 async db query
        case CMSG_GROUP_SET_LEADER:                     //   1               2         1 async db query
        case CMSG_GROUP_RAID_CONVERT:                   //   1               5         1 async db query
        case CMSG_GROUP_ASSISTANT_LEADER:               //   1               2         1 async db query
        case CMSG_PETITION_BUY:                         // not profiled                1 sync 1 async db queries
        case CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE:   // not profiled
        case CMSG_REQUEST_VEHICLE_PREV_SEAT:            // not profiled
        case CMSG_REQUEST_VEHICLE_NEXT_SEAT:            // not profiled
        case CMSG_REQUEST_VEHICLE_SWITCH_SEAT:          // not profiled
        case CMSG_REQUEST_VEHICLE_EXIT:                 // not profiled
        case CMSG_CONTROLLER_EJECT_PASSENGER:           // not profiled
        case CMSG_ITEM_REFUND:                          // not profiled
        case CMSG_SOCKET_GEMS:                          // not profiled
        case CMSG_WRAP_ITEM:                            // not profiled
        case CMSG_REPORT_PVP_AFK:                       // not profiled
            {
                maxPacketCounterAllowed = 10;
                break;
            }
        case CMSG_CHAR_CREATE:                          //   7               5         3 async db queries
        case CMSG_CHAR_ENUM:                            //  22               3         2 async db queries
        case CMSG_GMTICKET_CREATE:                      //   1              25         1 async db query
        case CMSG_GMTICKET_UPDATETEXT:                  //   0              15         1 async db query
        case CMSG_GMTICKET_DELETETICKET:                //   1              25         1 async db query
        case CMSG_GMRESPONSE_RESOLVE:                   //   1              25         1 async db query
        case CMSG_CALENDAR_ADD_EVENT:                   //  21              10         2 async db query
        case CMSG_CALENDAR_UPDATE_EVENT:                // not profiled
        case CMSG_CALENDAR_REMOVE_EVENT:                // not profiled
        case CMSG_CALENDAR_COPY_EVENT:                  // not profiled
        case CMSG_CALENDAR_EVENT_INVITE:                // not profiled
        case CMSG_CALENDAR_EVENT_SIGNUP:                // not profiled
        case CMSG_CALENDAR_EVENT_RSVP:                  // not profiled
        case CMSG_CALENDAR_EVENT_REMOVE_INVITE:         // not profiled
        case CMSG_CALENDAR_EVENT_MODERATOR_STATUS:      // not profiled
        case CMSG_ARENA_TEAM_INVITE:                    // not profiled
        case CMSG_ARENA_TEAM_ACCEPT:                    // not profiled
        case CMSG_ARENA_TEAM_DECLINE:                   // not profiled
        case CMSG_ARENA_TEAM_LEAVE:                     // not profiled
        case CMSG_ARENA_TEAM_DISBAND:                   // not profiled
        case CMSG_ARENA_TEAM_REMOVE:                    // not profiled
        case CMSG_ARENA_TEAM_LEADER:                    // not profiled
        case CMSG_LOOT_METHOD:                          // not profiled
        case CMSG_GUILD_INVITE:                         // not profiled
        case CMSG_GUILD_ACCEPT:                         // not profiled
        case CMSG_GUILD_DECLINE:                        // not profiled
        case CMSG_GUILD_LEAVE:                          // not profiled
        case CMSG_GUILD_DISBAND:                        // not profiled
        case CMSG_GUILD_LEADER:                         // not profiled
        case CMSG_GUILD_MOTD:                           // not profiled
        case CMSG_GUILD_RANK:                           // not profiled
        case CMSG_GUILD_ADD_RANK:                       // not profiled
        case CMSG_GUILD_DEL_RANK:                       // not profiled
        case CMSG_GUILD_INFO_TEXT:                      // not profiled
        case CMSG_GUILD_BANK_DEPOSIT_MONEY:             // not profiled
        case CMSG_GUILD_BANK_WITHDRAW_MONEY:            // not profiled
        case CMSG_GUILD_BANK_BUY_TAB:                   // not profiled
        case CMSG_GUILD_BANK_UPDATE_TAB:                // not profiled
        case CMSG_SET_GUILD_BANK_TEXT:                  // not profiled
        case MSG_SAVE_GUILD_EMBLEM:                     // not profiled
        case MSG_PETITION_RENAME:                       // not profiled
        case MSG_TALENT_WIPE_CONFIRM:                   // not profiled
        case MSG_SET_DUNGEON_DIFFICULTY:                // not profiled
        case MSG_SET_RAID_DIFFICULTY:                   // not profiled
        case MSG_PARTY_ASSIGNMENT:                      // not profiled
        case MSG_RAID_READY_CHECK:                      // not profiled
            {
                maxPacketCounterAllowed = 3;
                break;
            }
        case CMSG_ITEM_REFUND_INFO:                     // not profiled
            {
                maxPacketCounterAllowed = PLAYER_SLOTS_COUNT;
                break;
            }
        default:
            {
                maxPacketCounterAllowed = 100;
                break;
            }
    }
    return maxPacketCounterAllowed;
}
References CMSG_ACTIVATETAXI, CMSG_ACTIVATETAXIEXPRESS, CMSG_ADD_FRIEND, CMSG_ALTER_APPEARANCE, CMSG_AREA_SPIRIT_HEALER_QUERY, CMSG_ARENA_TEAM_ACCEPT, CMSG_ARENA_TEAM_DECLINE, CMSG_ARENA_TEAM_DISBAND, CMSG_ARENA_TEAM_INVITE, CMSG_ARENA_TEAM_LEADER, CMSG_ARENA_TEAM_LEAVE, CMSG_ARENA_TEAM_QUERY, CMSG_ARENA_TEAM_REMOVE, CMSG_ATTACKSTOP, CMSG_AUTOBANK_ITEM, CMSG_AUTOSTORE_BANK_ITEM, CMSG_BANKER_ACTIVATE, CMSG_BATTLEMASTER_JOIN_ARENA, CMSG_BEGIN_TRADE, CMSG_BUG, CMSG_BUY_BANK_SLOT, CMSG_CALENDAR_ADD_EVENT, CMSG_CALENDAR_COMPLAIN, CMSG_CALENDAR_COPY_EVENT, CMSG_CALENDAR_EVENT_INVITE, CMSG_CALENDAR_EVENT_MODERATOR_STATUS, CMSG_CALENDAR_EVENT_REMOVE_INVITE, CMSG_CALENDAR_EVENT_RSVP, CMSG_CALENDAR_EVENT_SIGNUP, CMSG_CALENDAR_GET_CALENDAR, CMSG_CALENDAR_REMOVE_EVENT, CMSG_CALENDAR_UPDATE_EVENT, CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE, CMSG_CHAR_CREATE, CMSG_CHAR_CUSTOMIZE, CMSG_CHAR_DELETE, CMSG_CHAR_ENUM, CMSG_CHAR_FACTION_CHANGE, CMSG_CHAR_RACE_CHANGE, CMSG_CHAR_RENAME, CMSG_COMPLETE_CINEMATIC, CMSG_CONTACT_LIST, CMSG_CONTROLLER_EJECT_PASSENGER, CMSG_CORPSE_MAP_POSITION_QUERY, CMSG_CREATURE_QUERY, CMSG_DEL_FRIEND, CMSG_DELETEEQUIPMENT_SET, CMSG_DISMISS_CONTROLLED_VEHICLE, CMSG_DISMISS_CRITTER, CMSG_DUEL_ACCEPTED, CMSG_DUEL_CANCELLED, CMSG_EQUIPMENT_SET_SAVE, CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK, CMSG_FORCE_PITCH_RATE_CHANGE_ACK, CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_RUN_SPEED_CHANGE_ACK, CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_SWIM_SPEED_CHANGE_ACK, CMSG_FORCE_TURN_RATE_CHANGE_ACK, CMSG_FORCE_WALK_SPEED_CHANGE_ACK, CMSG_GAMEOBJ_REPORT_USE, CMSG_GAMEOBJ_USE, CMSG_GAMEOBJECT_QUERY, CMSG_GM_REPORT_LAG, CMSG_GMRESPONSE_RESOLVE, CMSG_GMSURVEY_SUBMIT, CMSG_GMTICKET_CREATE, CMSG_GMTICKET_DELETETICKET, CMSG_GMTICKET_UPDATETEXT, CMSG_GROUP_ACCEPT, CMSG_GROUP_ASSISTANT_LEADER, CMSG_GROUP_CHANGE_SUB_GROUP, CMSG_GROUP_DECLINE, CMSG_GROUP_DISBAND, CMSG_GROUP_INVITE, CMSG_GROUP_RAID_CONVERT, CMSG_GROUP_SET_LEADER, CMSG_GROUP_UNINVITE, CMSG_GROUP_UNINVITE_GUID, CMSG_GUILD_ACCEPT, CMSG_GUILD_ADD_RANK, CMSG_GUILD_BANK_BUY_TAB, CMSG_GUILD_BANK_DEPOSIT_MONEY, CMSG_GUILD_BANK_QUERY_TAB, CMSG_GUILD_BANK_UPDATE_TAB, CMSG_GUILD_BANK_WITHDRAW_MONEY, CMSG_GUILD_DECLINE, CMSG_GUILD_DEL_RANK, CMSG_GUILD_DISBAND, CMSG_GUILD_INFO_TEXT, CMSG_GUILD_INVITE, CMSG_GUILD_LEADER, CMSG_GUILD_LEAVE, CMSG_GUILD_MOTD, CMSG_GUILD_QUERY, CMSG_GUILD_RANK, CMSG_GUILD_SET_OFFICER_NOTE, CMSG_GUILD_SET_PUBLIC_NOTE, CMSG_HEARTH_AND_RESURRECT, CMSG_INITIATE_TRADE, CMSG_INSPECT, CMSG_ITEM_NAME_QUERY, CMSG_ITEM_QUERY_SINGLE, CMSG_ITEM_REFUND, CMSG_ITEM_REFUND_INFO, CMSG_LEARN_PREVIEW_TALENTS, CMSG_LEARN_PREVIEW_TALENTS_PET, CMSG_LEAVE_BATTLEFIELD, CMSG_LOGOUT_CANCEL, CMSG_LOGOUT_REQUEST, CMSG_LOOT_METHOD, CMSG_MESSAGECHAT, CMSG_MOVE_TIME_SKIPPED, CMSG_NAME_QUERY, CMSG_NPC_TEXT_QUERY, CMSG_OPT_OUT_OF_LOOT, CMSG_PAGE_TEXT_QUERY, CMSG_PET_ABANDON, CMSG_PET_NAME_QUERY, CMSG_PET_RENAME, CMSG_PETITION_BUY, CMSG_PETITION_QUERY, CMSG_PETITION_SIGN, CMSG_PLAYER_LOGIN, CMSG_PLAYER_LOGOUT, CMSG_PLAYER_VEHICLE_ENTER, CMSG_QUERY_INSPECT_ACHIEVEMENTS, CMSG_QUERY_QUESTS_COMPLETED, CMSG_QUERY_TIME, CMSG_QUEST_CONFIRM_ACCEPT, CMSG_QUEST_POI_QUERY, CMSG_QUEST_QUERY, CMSG_QUESTGIVER_ACCEPT_QUEST, CMSG_QUESTGIVER_CANCEL, CMSG_QUESTGIVER_CHOOSE_REWARD, CMSG_QUESTGIVER_COMPLETE_QUEST, CMSG_QUESTGIVER_QUERY_QUEST, CMSG_QUESTGIVER_REQUEST_REWARD, CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY, CMSG_QUESTGIVER_STATUS_QUERY, CMSG_QUESTLOG_REMOVE_QUEST, CMSG_READY_FOR_ACCOUNT_DATA_TIMES, CMSG_REALM_SPLIT, CMSG_REMOVE_GLYPH, CMSG_REPOP_REQUEST, CMSG_REPORT_PVP_AFK, CMSG_REQUEST_PARTY_MEMBER_STATS, CMSG_REQUEST_VEHICLE_EXIT, CMSG_REQUEST_VEHICLE_NEXT_SEAT, CMSG_REQUEST_VEHICLE_PREV_SEAT, CMSG_REQUEST_VEHICLE_SWITCH_SEAT, CMSG_RESET_INSTANCES, CMSG_SELF_RES, CMSG_SET_ACTION_BUTTON, CMSG_SET_CONTACT_NOTES, CMSG_SET_GUILD_BANK_TEXT, CMSG_SET_SHEATHED, CMSG_SOCKET_GEMS, CMSG_SPELLCLICK, CMSG_STANDSTATECHANGE, CMSG_TAXINODE_STATUS_QUERY, CMSG_TAXIQUERYAVAILABLENODES, CMSG_TIME_SYNC_RESP, CMSG_TOGGLE_PVP, CMSG_TRAINER_BUY_SPELL, CMSG_TURN_IN_PETITION, CMSG_UNLEARN_SKILL, CMSG_WHO, CMSG_WRAP_ITEM, MAX_QUEST_LOG_SIZE, MSG_CORPSE_QUERY, MSG_GUILD_BANK_LOG_QUERY, MSG_GUILD_EVENT_LOG_QUERY, MSG_MOVE_HEARTBEAT, MSG_MOVE_SET_FACING, MSG_PARTY_ASSIGNMENT, MSG_PETITION_DECLINE, MSG_PETITION_RENAME, MSG_QUERY_GUILD_BANK_TEXT, MSG_QUERY_NEXT_MAIL_TIME, MSG_RAID_READY_CHECK, MSG_RAID_TARGET_UPDATE, MSG_RANDOM_ROLL, MSG_SAVE_GUILD_EMBLEM, MSG_SET_DUNGEON_DIFFICULTY, MSG_SET_RAID_DIFFICULTY, MSG_TALENT_WIPE_CONFIRM, and PLAYER_SLOTS_COUNT.
Referenced by EvaluateOpcode().
operator=()
DosProtection & WorldSession::DosProtection::operator= (DosProtection const & right) private delete
Friends And Related Function Documentation
World
friend class World friend
Member Data Documentation
_PacketThrottlingMap
PacketThrottlingMap WorldSession::DosProtection::_PacketThrottlingMap mutable private
Referenced by EvaluateOpcode().
_policy
Policy WorldSession::DosProtection::_policy private
Referenced by EvaluateOpcode().
Session
WorldSession* WorldSession::DosProtection::Session protected
Referenced by EvaluateOpcode().