AzerothCore: boss_hodir::boss_hodirAI Struct Reference
boss_hodir::boss_hodirAI Struct Reference
Public Member Functions
boss_hodirAI (Creature *pCreature)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void DoAction (int action) override
void SmallIcicles (bool enable)
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void SpellHit (Unit *, SpellInfo const *spellInfo) override
Creature * GetHelper (uint8 index)
void SpawnHelpers ()
void KilledUnit (Unit *who) override
void JustSummoned (Creature *s) override
void SummonedCreatureDespawn (Creature *s) override
bool CanAIAttack (Unit const *t) const override
void SetData (uint32 id, uint32 value) override
uint32 GetData (uint32 id) const override
void MoveInLineOfSight (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
ObjectGuid Helpers [8]
bool berserk { false }
bool bAchievCheese { true }
bool bAchievGettingCold { true }
bool bAchievCacheRare { true }
bool bAchievCoolestFriends { true }
uint16 addSpawnTimer { 0 }
const Position ENTRANCE_DOOR { 1999.160034f, -297.792999f, 431.960999f, 0 }
const Position EXIT_DOOR { 1999.709961f, -166.259003f, 432.822998f, 0 }
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_hodirAI()
boss_hodir::boss_hodirAI::boss_hodirAI (Creature * pCreature) inline
                                          : ScriptedAI(pCreature), summons(me)
        {
            pInstance = pCreature->GetInstanceScript();
            if (!me->IsAlive())
                if (pInstance)
                    pInstance->SetData(TYPE_HODIR, DONE);
        }
References DONE, WorldObject::GetInstanceScript(), Unit::IsAlive(), ScriptedAI::me, pInstance, ZoneScript::SetData(), and TYPE_HODIR.
Member Function Documentation
CanAIAttack()
bool boss_hodir::boss_hodirAI::CanAIAttack (Unit const * t) const inline override virtual
Reimplemented from UnitAI.
        {
            if (t->IsPlayer())
                return !t->HasAura(SPELL_FLASH_FREEZE_TRAPPED_PLAYER);
            else if (t->IsCreature())
                return !t->HasAura(SPELL_FLASH_FREEZE_TRAPPED_NPC);
            return true;
        }
References Unit::HasAura(), Object::IsCreature(), Object::IsPlayer(), SPELL_FLASH_FREEZE_TRAPPED_NPC, and SPELL_FLASH_FREEZE_TRAPPED_PLAYER.
DamageTaken()
void boss_hodir::boss_hodirAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (damage >= me->GetHealth() || me->GetHealth() < 150000)
            {
                damage = 0;
                me->SetReactState(REACT_PASSIVE);
                if (!me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
                {
                    if (pInstance)
                    {
                        pInstance->SetData(TYPE_HODIR, DONE);
                        me->CastSpell(me, 64899, true); // credit
                        pInstance->DoRemoveAurasDueToSpellOnPlayers(SPELL_BITING_COLD_PLAYER_AURA);
                    }
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->SetFaction(FACTION_FRIENDLY);
                    me->GetMotionMaster()->Clear();
                    me->AttackStop();
                    me->CombatStop();
                    me->InterruptNonMeleeSpells(true);
                    me->RemoveAllAuras();
                    events.Reset();
                    summons.DespawnAll();
                    if (GameObject* d = me->FindNearestGameObject(GO_HODIR_FROZEN_DOOR, 250.0f))
                    {
                        if (d->GetGoState() != GO_STATE_ACTIVE )
{
                            d->SetLootState(GO_READY);
                            d->UseDoorOrButton(0, false);
                        }
                    }
                    if (GameObject* d = me->FindNearestGameObject(GO_HODIR_DOOR, 250.0f))
                    {
                        if (d->GetGoState() != GO_STATE_ACTIVE )
{
                            d->SetLootState(GO_READY);
                            d->UseDoorOrButton(0, false);
                        }
                    }
                    if (GameObject* go = me->FindNearestGameObject(GO_HODIR_FRONTDOOR, 300.0f))
                    {
                        go->SetGoState(GO_STATE_ACTIVE);
                    }
                    Talk(TEXT_DEATH);
                    scheduler.Schedule(14s, [this](TaskContext /*context*/)
                    {
                        DoCastSelf(SPELL_TELEPORT);
                    });
                }
            }
        }
References Unit::AttackStop(), Unit::CastSpell(), MotionMaster::Clear(), Unit::CombatStop(), SummonList::DespawnAll(), UnitAI::DoCastSelf(), DONE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), FACTION_FRIENDLY, WorldObject::FindNearestGameObject(), Unit::GetHealth(), Unit::GetMotionMaster(), GO_HODIR_DOOR, GO_HODIR_FRONTDOOR, GO_HODIR_FROZEN_DOOR, GO_READY, GO_STATE_ACTIVE, Unit::HasUnitFlag(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, pInstance, REACT_PASSIVE, Unit::RemoveAllAuras(), TaskScheduler::Schedule(), CreatureAI::scheduler, ZoneScript::SetData(), Unit::SetFaction(), Creature::SetReactState(), Unit::SetUnitFlag(), SPELL_BITING_COLD_PLAYER_AURA, SPELL_TELEPORT, summons, TEXT_DEATH, TYPE_HODIR, and UNIT_FLAG_NON_ATTACKABLE.
DoAction()
void boss_hodir::boss_hodirAI::DoAction (int action) inline override
        {
            if (action)
            {
                switch (action)
                {
                    case EVENT_FAIL_HM:
                        if (pInstance)
{
                            if (GameObject* go = pInstance->instance->GetGameObject(pInstance->GetGuidData(GO_HODIR_CHEST_HARD)))
{
                                go->SetGoState(GO_STATE_ACTIVE);
                                events.ScheduleEvent(EVENT_DESPAWN_CHEST, 3s);
                            }
                        }
                        break;
                }
            }
        }
References EVENT_DESPAWN_CHEST, EVENT_FAIL_HM, Map::GetGameObject(), InstanceScript::GetGuidData(), GO_HODIR_CHEST_HARD, GO_STATE_ACTIVE, InstanceScript::instance, and pInstance.
GetData()
uint32 boss_hodir::boss_hodirAI::GetData (uint32 id) const inline override virtual
Reimplemented from UnitAI.
        {
            switch (id)
            {
                case 1:
                    return (bAchievCheese ? 1 : 0);
                case 2:
                    return (bAchievGettingCold ? 1 : 0);
                case 3:
                    return (bAchievCacheRare ? 1 : 0);
                case 4:
                    return (bAchievCoolestFriends ? 1 : 0);
            }
            return 0;
        }
References bAchievCacheRare, bAchievCheese, bAchievCoolestFriends, and bAchievGettingCold.
GetHelper()
Creature * boss_hodir::boss_hodirAI::GetHelper (uint8 index) inline
        {
            return Helpers[index] ? ObjectAccessor::GetCreature(*me, Helpers[index]) : nullptr;
        }
References ObjectAccessor::GetCreature(), Helpers, and ScriptedAI::me.
JustEngagedWith()
void boss_hodir::boss_hodirAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            me->CastSpell(me, SPELL_BITING_COLD_BOSS_AURA, true);
            SmallIcicles(true);
            events.Reset();
            events.ScheduleEvent(EVENT_FLASH_FREEZE, 48s, 49s);
            events.ScheduleEvent(EVENT_FREEZE, 17s, 20s);
            events.ScheduleEvent(EVENT_BERSERK, 8min);
            events.ScheduleEvent(EVENT_HARD_MODE_MISSED, 3min);
            Talk(TEXT_AGGRO);
            if (pInstance && pInstance->GetData(TYPE_HODIR) != DONE)
            {
                pInstance->SetData(TYPE_HODIR, IN_PROGRESS);
            }
            if (GameObject* go = me->FindNearestGameObject(GO_HODIR_FRONTDOOR, 300.0f))
            {
                go->SetGoState(GO_STATE_READY);
            }
        }
References Unit::CastSpell(), DONE, EVENT_BERSERK, EVENT_FLASH_FREEZE, EVENT_FREEZE, EVENT_HARD_MODE_MISSED, WorldObject::FindNearestGameObject(), ZoneScript::GetData(), GO_HODIR_FRONTDOOR, GO_STATE_READY, IN_PROGRESS, ScriptedAI::me, pInstance, ZoneScript::SetData(), SmallIcicles(), SPELL_BITING_COLD_BOSS_AURA, TEXT_AGGRO, and TYPE_HODIR.
JustSummoned()
void boss_hodir::boss_hodirAI::JustSummoned (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(s);
        }
References SummonList::Summon(), and summons.
Referenced by SpawnHelpers().
KilledUnit()
void boss_hodir::boss_hodirAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (who->IsPlayer())
                Talk(TEXT_SLAY);
        }
References Object::IsPlayer(), and TEXT_SLAY.
MoveInLineOfSight()
void boss_hodir::boss_hodirAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{}
Reset()
void boss_hodir::boss_hodirAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Reset();
            summons.DespawnAll();
            berserk = false;
            bAchievCheese = true;
            bAchievGettingCold = true;
            bAchievCacheRare = true;
            bAchievCoolestFriends = true;
            me->SetSheath(SHEATH_STATE_MELEE);
            // Reset the spells cast after wipe
            me->RemoveAllAuras();
            pInstance->DoRemoveAurasDueToSpellOnPlayers(SPELL_BITING_COLD_PLAYER_AURA);
            if (pInstance && pInstance->GetData(TYPE_HODIR) != DONE)
            {
                pInstance->SetData(TYPE_HODIR, NOT_STARTED);
            }
            if (GameObject* go = me->FindNearestGameObject(GO_HODIR_FRONTDOOR, 900.0f))
            {
                go->SetGoState(GO_STATE_ACTIVE);
            }
            // Reset helpers
            if (!summons.size())
                SpawnHelpers();
        }
References bAchievCacheRare, bAchievCheese, bAchievCoolestFriends, bAchievGettingCold, berserk, SummonList::DespawnAll(), DONE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), WorldObject::FindNearestGameObject(), ZoneScript::GetData(), GO_HODIR_FRONTDOOR, GO_STATE_ACTIVE, ScriptedAI::me, NOT_STARTED, pInstance, Unit::RemoveAllAuras(), ZoneScript::SetData(), Unit::SetSheath(), SHEATH_STATE_MELEE, SummonList::size(), SpawnHelpers(), SPELL_BITING_COLD_PLAYER_AURA, summons, and TYPE_HODIR.
SetData()
void boss_hodir::boss_hodirAI::SetData (uint32 id, uint32 value) inline override virtual
Reimplemented from UnitAI.
        {
            if (value)
                switch (id)
                {
                    case 1:
                        bAchievCheese = false;
                        break;
                    case 2:
                        bAchievGettingCold = false;
                        break;
                    case 4:
                        bAchievCoolestFriends = false;
                        break;
                }
        }
References bAchievCheese, bAchievCoolestFriends, and bAchievGettingCold.
SmallIcicles()
void boss_hodir::boss_hodirAI::SmallIcicles (bool enable) inline
        {
            if (enable)
                me->CastSpell(me, SPELL_ICICLE_BOSS_AURA, true);
            else
                me->RemoveAura(SPELL_ICICLE_BOSS_AURA);
        }
References Unit::CastSpell(), ScriptedAI::me, Unit::RemoveAura(), and SPELL_ICICLE_BOSS_AURA.
Referenced by JustEngagedWith(), and UpdateAI().
SpawnHelpers()
void boss_hodir::boss_hodirAI::SpawnHelpers () inline
        {
            char faction = 'A';
            if (hhd[0][0].id)
            {
                Map::PlayerList const& cl = me->GetMap()->GetPlayers();
                for (Map::PlayerList::const_iterator itr = cl.begin(); itr != cl.end(); ++itr)
                    if (!itr->GetSource()->IsGameMaster())
                    {
                        faction = (itr->GetSource()->GetTeamId() == TEAM_ALLIANCE ? 'A' : 'H');
                        break;
                    }
            }
            uint8 cnt = 0;
            if (faction)
                for( uint8 k = 0; k < 4; ++k )
                {
                    if ((faction == 'A' && ( k > 1 || (k == 1 && RAID_MODE(1, 0)))) ||
                            (faction == 'H' && ( k < 2 || (k == 3 && RAID_MODE(1, 0)))))
                        continue;
                    for( uint8 i = 0; i < 4; ++i )
                    {
                        if (!hhd[k][i].id)
                            continue;
                        if (Creature* h_p = me->SummonCreature(hhd[k][i].id, hhd[k][i].x, hhd[k][i].y, 432.69f, M_PI / 2))
{
                            h_p->SetFaction(1665);
                            if (cnt < 8)
                                Helpers[cnt++] = h_p->GetGUID();
                            if (Creature* c = h_p->SummonCreature(NPC_FLASH_FREEZE_NPC, h_p->GetPositionX(), h_p->GetPositionY(), h_p->GetPositionZ(), 0.0f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000))
{
                                c->CastSpell(h_p, SPELL_FLASH_FREEZE_TRAPPED_NPC, true);
                                JustSummoned(c);
                            }
                        }
                    }
                }
        }
References MapRefMgr::begin(), MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), Helpers, hhd, HodirHelperData::id, JustSummoned(), ScriptedAI::me, NPC_FLASH_FREEZE_NPC, ScriptedAI::RAID_MODE(), SPELL_FLASH_FREEZE_TRAPPED_NPC, WorldObject::SummonCreature(), TEAM_ALLIANCE, TEMPSUMMON_CORPSE_TIMED_DESPAWN, HodirHelperData::x, and HodirHelperData::y.
Referenced by Reset().
SpellHit()
void boss_hodir::boss_hodirAI::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_TELEPORT)
            {
                me->DespawnOrUnsummon();
                pInstance->SetData(EVENT_KEEPER_TELEPORTED, DONE);
            }
        }
References Creature::DespawnOrUnsummon(), DONE, EVENT_KEEPER_TELEPORTED, SpellInfo::Id, ScriptedAI::me, pInstance, ZoneScript::SetData(), and SPELL_TELEPORT.
SpellHitTarget()
void boss_hodir::boss_hodirAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            switch (spell->Id)
            {
                case SPELL_ICICLE_TBBA:
                    me->CastSpell(target, SPELL_ICICLE_VISUAL_UNPACKED, true);
                    break;
                case SPELL_FLASH_FREEZE_VISUAL:
                    {
                        std::list<Creature*> fires;
                        me->GetCreaturesWithEntryInRange(fires, 200.0f, NPC_TOASTY_FIRE);
                        for (std::list<Creature*>::iterator itr = fires.begin(); itr != fires.end(); ++itr)
                            (*itr)->AI()->DoAction(1); // remove it
                    }
                    break;
            }
        }
References Unit::CastSpell(), WorldObject::GetCreaturesWithEntryInRange(), SpellInfo::Id, ScriptedAI::me, NPC_TOASTY_FIRE, SPELL_FLASH_FREEZE_VISUAL, SPELL_ICICLE_TBBA, and SPELL_ICICLE_VISUAL_UNPACKED.
SummonedCreatureDespawn()
void boss_hodir::boss_hodirAI::SummonedCreatureDespawn (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Despawn(s);
        }
References SummonList::Despawn(), and summons.
UpdateAI()
void boss_hodir::boss_hodirAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            scheduler.Update(diff);
            if (me->GetPositionY() <= ENTRANCE_DOOR.GetPositionY() || me->GetPositionY() >= EXIT_DOOR.GetPositionY())
            {
                boss_hodirAI::EnterEvadeMode();
                return;
            }
            if (!UpdateVictim())
            {
                if (me->IsInCombat())
                {
                    Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                    for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                        itr->GetSource()->CastSpell(itr->GetSource(), SPELL_FLASH_FREEZE_INSTAKILL, true);
                    EnterEvadeMode();
                }
                return;
            }
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_BERSERK:
                    {
                        berserk = true;
                        me->CastSpell(me, SPELL_BERSERK, true);
                        Talk(TEXT_BERSERK);
                    }
                    break;
                case EVENT_HARD_MODE_MISSED:
                    {
                        Talk(TEXT_HM_MISS);
                        bAchievCacheRare = false;
                        if (pInstance)
{
                            if (GameObject* go = pInstance->instance->GetGameObject(pInstance->GetGuidData(GO_HODIR_CHEST_HARD)))
{
                                me->CastSpell(go, SPELL_SHATTER_CHEST, false);
                            }
                        }
                    }
                    break;
                case EVENT_DESPAWN_CHEST:
                    if (pInstance && pInstance->GetData(TYPE_HODIR) != DONE)
                        pInstance->SetData(TYPE_HODIR_HM_FAIL, 0);
                    break;
                case EVENT_FLASH_FREEZE:
                    {
                        std::list<Unit*> targets;
                        Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                        for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                            targets.push_back(itr->GetSource());
                        targets.remove_if(Acore::ObjectTypeIdCheck(TYPEID_PLAYER, false));
                        targets.remove_if(Acore::UnitAuraCheck(true, SPELL_FLASH_FREEZE_TRAPPED_PLAYER));
                        Acore::Containers::RandomResize(targets, (RAID_MODE(2,3)));
                        for (std::list<Unit*>::const_iterator itr = targets.begin(); itr != targets.end(); ++itr)
{
                            float prevZ = (*itr)->GetPositionZ();
                            (*itr)->m_positionZ = 432.7f;
                            (*itr)->CastSpell((*itr), SPELL_ICICLE_VISUAL_PACKED, true);
                            (*itr)->m_positionZ = prevZ;
                        }
                        me->CastSpell((Unit*)nullptr, SPELL_FLASH_FREEZE_CAST, false);
                        me->PlayDirectSound(SOUND_HODIR_FLASH_FREEZE, 0);
                        Talk(TEXT_FLASH_FREEZE);
                        Talk(TEXT_EMOTE_FREEZE);
                        SmallIcicles(false);
                        events.ScheduleEvent(EVENT_FLASH_FREEZE, 48s, 49s);
                        events.ScheduleEvent(EVENT_SMALL_ICICLES_ENABLE, Is25ManRaid() ? 12s : 24s);
                        events.ScheduleEvent(EVENT_FROZEN_BLOWS, 15s);
                        events.RescheduleEvent(EVENT_FREEZE, 17s, 20s);
                    }
                    break;
                case EVENT_SMALL_ICICLES_ENABLE:
                    {
                        SmallIcicles(true);
                    }
                    break;
                case EVENT_FROZEN_BLOWS:
                    {
                        Talk(TEXT_EMOTE_BLOW);
                        Talk(TEXT_STALACTITE);
                        me->CastSpell(me, Is25ManRaid()? SPELL_FROZEN_BLOWS_25 : SPELL_FROZEN_BLOWS_10, true);
                    }
                    break;
                case EVENT_FREEZE:
                    if (Player* plr = SelectTargetFromPlayerList(50.0f, SPELL_FLASH_FREEZE_TRAPPED_PLAYER))
                    {
                        me->CastSpell(plr, SPELL_FREEZE, false);
                    }
                    else if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 50.0f, true))
                    {
                        me->CastSpell(target, SPELL_FREEZE, false);
                    }
                    events.RescheduleEvent(EVENT_FREEZE, 17s, 20s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References bAchievCacheRare, MapRefMgr::begin(), berserk, Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), DONE, MapRefMgr::end(), CreatureAI::EnterEvadeMode(), ENTRANCE_DOOR, EVENT_BERSERK, EVENT_DESPAWN_CHEST, EVENT_FLASH_FREEZE, EVENT_FREEZE, EVENT_FROZEN_BLOWS, EVENT_HARD_MODE_MISSED, EVENT_SMALL_ICICLES_ENABLE, EXIT_DOOR, ZoneScript::GetData(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Map::GetPlayers(), Position::GetPositionY(), GO_HODIR_CHEST_HARD, Unit::HasUnitState(), InstanceScript::instance, ScriptedAI::Is25ManRaid(), Unit::IsInCombat(), ScriptedAI::me, pInstance, WorldObject::PlayDirectSound(), ScriptedAI::RAID_MODE(), Acore::Containers::RandomResize(), CreatureAI::scheduler, UnitAI::SelectTarget(), ScriptedAI::SelectTargetFromPlayerList(), ZoneScript::SetData(), SmallIcicles(), SOUND_HODIR_FLASH_FREEZE, SPELL_BERSERK, SPELL_FLASH_FREEZE_CAST, SPELL_FLASH_FREEZE_INSTAKILL, SPELL_FLASH_FREEZE_TRAPPED_PLAYER, SPELL_FREEZE, SPELL_FROZEN_BLOWS_10, SPELL_FROZEN_BLOWS_25, SPELL_ICICLE_VISUAL_PACKED, SPELL_SHATTER_CHEST, TEXT_BERSERK, TEXT_EMOTE_BLOW, TEXT_EMOTE_FREEZE, TEXT_FLASH_FREEZE, TEXT_HM_MISS, TEXT_STALACTITE, TYPE_HODIR, TYPE_HODIR_HM_FAIL, TYPEID_PLAYER, UNIT_STATE_CASTING, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
addSpawnTimer
uint16 boss_hodir::boss_hodirAI::addSpawnTimer { 0 }
bAchievCacheRare
bool boss_hodir::boss_hodirAI::bAchievCacheRare { true }
Referenced by GetData(), Reset(), and UpdateAI().
bAchievCheese
bool boss_hodir::boss_hodirAI::bAchievCheese { true }
Referenced by GetData(), Reset(), and SetData().
bAchievCoolestFriends
bool boss_hodir::boss_hodirAI::bAchievCoolestFriends { true }
Referenced by GetData(), Reset(), and SetData().
bAchievGettingCold
bool boss_hodir::boss_hodirAI::bAchievGettingCold { true }
Referenced by GetData(), Reset(), and SetData().
berserk
bool boss_hodir::boss_hodirAI::berserk { false }
Referenced by Reset(), and UpdateAI().
ENTRANCE_DOOR
const Position boss_hodir::boss_hodirAI::ENTRANCE_DOOR { 1999.160034f, -297.792999f, 431.960999f, 0 }
Referenced by UpdateAI().
events
EventMap boss_hodir::boss_hodirAI::events
EXIT_DOOR
const Position boss_hodir::boss_hodirAI::EXIT_DOOR { 1999.709961f, -166.259003f, 432.822998f, 0 }
Referenced by UpdateAI().
Helpers
ObjectGuid boss_hodir::boss_hodirAI::Helpers[8]
Referenced by GetHelper(), and SpawnHelpers().
pInstance
InstanceScript* boss_hodir::boss_hodirAI::pInstance
Referenced by boss_hodirAI(), DamageTaken(), DoAction(), JustEngagedWith(), Reset(), SpellHit(), and UpdateAI().
summons
SummonList boss_hodir::boss_hodirAI::summons
Referenced by DamageTaken(), JustSummoned(), Reset(), and SummonedCreatureDespawn().