AzerothCore: instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript Struct Reference
instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript Struct Reference
Public Member Functions
instance_sunwell_plateau_InstanceMapScript (Map *map)
void OnPlayerEnter (Player *player) override
Player const * GetPlayerInMap () const
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetGuidData (uint32 id) const override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
ObjectGuid KalecgosDragonGUID
ObjectGuid SathrovarrGUID
ObjectGuid BrutallusGUID
ObjectGuid MadrigosaGUID
ObjectGuid FelmystGUID
ObjectGuid AlythessGUID
ObjectGuid SacrolashGUID
ObjectGuid MuruGUID
ObjectGuid KilJaedenGUID
ObjectGuid KilJaedenControllerGUID
ObjectGuid AnveenaGUID
ObjectGuid KalecgosKjGUID
ObjectGuid IceBarrierGUID
ObjectGuid blueFlightOrbGUID [4]
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_sunwell_plateau_InstanceMapScript()
instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::instance_sunwell_plateau_InstanceMapScript (Map * map) inline
                                                             : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTERS);
            LoadDoorData(doorData);
        }
References DataHeader, doorData, InstanceScript::LoadDoorData(), MAX_ENCOUNTERS, InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
GetGuidData()
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::GetGuidData (uint32 id) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (id)
            {
                case NPC_KALECGOS:
                    return KalecgosDragonGUID;
                case NPC_SATHROVARR:
                    return SathrovarrGUID;
                case NPC_BRUTALLUS:
                    return BrutallusGUID;
                case NPC_MADRIGOSA:
                    return MadrigosaGUID;
                case NPC_FELMYST:
                    return FelmystGUID;
                case NPC_GRAND_WARLOCK_ALYTHESS:
                    return AlythessGUID;
                case NPC_LADY_SACROLASH:
                    return SacrolashGUID;
                case NPC_MURU:
                    return MuruGUID;
                case NPC_ANVEENA:
                    return AnveenaGUID;
                case NPC_KALECGOS_KJ:
                    return KalecgosKjGUID;
                case NPC_KILJAEDEN_CONTROLLER:
                    return KilJaedenControllerGUID;
                case NPC_KILJAEDEN:
                    return KilJaedenGUID;
                // Orbs
                case DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_1:
                case DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_2:
                case DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_3:
                case DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_4:
                    return blueFlightOrbGUID[id - DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_1];
            }
            return ObjectGuid::Empty;
        }
References AlythessGUID, AnveenaGUID, blueFlightOrbGUID, BrutallusGUID, DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_1, DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_2, DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_3, DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_4, ObjectGuid::Empty, FelmystGUID, KalecgosDragonGUID, KalecgosKjGUID, KilJaedenControllerGUID, KilJaedenGUID, MadrigosaGUID, MuruGUID, NPC_ANVEENA, NPC_BRUTALLUS, NPC_FELMYST, NPC_GRAND_WARLOCK_ALYTHESS, NPC_KALECGOS, NPC_KALECGOS_KJ, NPC_KILJAEDEN, NPC_KILJAEDEN_CONTROLLER, NPC_LADY_SACROLASH, NPC_MADRIGOSA, NPC_MURU, NPC_SATHROVARR, SacrolashGUID, and SathrovarrGUID.
GetPlayerInMap()
Player const * instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::GetPlayerInMap () const inline
        {
            Map::PlayerList const& players = instance->GetPlayers();
            if (!players.IsEmpty())
            {
                for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                {
                    Player* player = itr->GetSource();
                    if (player && !player->HasAura(45839))
                        return player;
                }
            }
            //else
            //    LOG_DEBUG("scripts", "Instance Sunwell Plateau: GetPlayerInMap, but PlayerList is empty!");
            return nullptr;
        }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), Unit::HasAura(), InstanceScript::instance, and LinkedListHead::IsEmpty().
OnCreatureCreate()
void instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            if (creature->GetSpawnId() > 0 || !creature->GetOwnerGUID().IsPlayer())
                creature->CastSpell(creature, SPELL_SUNWELL_RADIANCE, true);
            switch (creature->GetEntry())
            {
                case NPC_KALECGOS:
                    KalecgosDragonGUID = creature->GetGUID();
                    break;
                case NPC_SATHROVARR:
                    SathrovarrGUID = creature->GetGUID();
                    break;
                case NPC_BRUTALLUS:
                    BrutallusGUID = creature->GetGUID();
                    break;
                case NPC_MADRIGOSA:
                    MadrigosaGUID = creature->GetGUID();
                    break;
                case NPC_FELMYST:
                    FelmystGUID = creature->GetGUID();
                    break;
                case NPC_GRAND_WARLOCK_ALYTHESS:
                    AlythessGUID = creature->GetGUID();
                    break;
                case NPC_LADY_SACROLASH:
                    SacrolashGUID = creature->GetGUID();
                    break;
                case NPC_MURU:
                    MuruGUID = creature->GetGUID();
                    break;
                case NPC_KILJAEDEN:
                    KilJaedenGUID = creature->GetGUID();
                    break;
                case NPC_KILJAEDEN_CONTROLLER:
                    KilJaedenControllerGUID = creature->GetGUID();
                    break;
                case NPC_ANVEENA:
                    AnveenaGUID = creature->GetGUID();
                    break;
                case NPC_KALECGOS_KJ:
                    KalecgosKjGUID = creature->GetGUID();
                    break;
                // Xinef: Felmyst encounter
                case NPC_DEMONIC_VAPOR_TRAIL:
                case NPC_UNYIELDING_DEAD:
                    if (Creature* felmyst = instance->GetCreature(FelmystGUID))
                        felmyst->AI()->JustSummoned(creature);
                    break;
                // Xinef: M'uru encounter
                case NPC_DARKNESS:
                case NPC_VOID_SENTINEL:
                case NPC_VOID_SPAWN:
                    if (Creature* muru = instance->GetCreature(MuruGUID))
                        muru->AI()->JustSummoned(creature);
                    break;
                // Xinef: Kil'jaeden encounter
                case NPC_FELFIRE_PORTAL:
                case NPC_VOLATILE_FELFIRE_FIEND:
                case NPC_SHIELD_ORB:
                case NPC_SINISTER_REFLECTION:
                    if (Creature* kiljaedenC = instance->GetCreature(KilJaedenControllerGUID))
                        kiljaedenC->AI()->JustSummoned(creature);
                    break;
                default:
                    break;
            }
        }
References AlythessGUID, AnveenaGUID, BrutallusGUID, Unit::CastSpell(), FelmystGUID, Map::GetCreature(), Object::GetEntry(), Object::GetGUID(), Unit::GetOwnerGUID(), Creature::GetSpawnId(), InstanceScript::instance, ObjectGuid::IsPlayer(), KalecgosDragonGUID, KalecgosKjGUID, KilJaedenControllerGUID, KilJaedenGUID, MadrigosaGUID, MuruGUID, NPC_ANVEENA, NPC_BRUTALLUS, NPC_DARKNESS, NPC_DEMONIC_VAPOR_TRAIL, NPC_FELFIRE_PORTAL, NPC_FELMYST, NPC_GRAND_WARLOCK_ALYTHESS, NPC_KALECGOS, NPC_KALECGOS_KJ, NPC_KILJAEDEN, NPC_KILJAEDEN_CONTROLLER, NPC_LADY_SACROLASH, NPC_MADRIGOSA, NPC_MURU, NPC_SATHROVARR, NPC_SHIELD_ORB, NPC_SINISTER_REFLECTION, NPC_UNYIELDING_DEAD, NPC_VOID_SENTINEL, NPC_VOID_SPAWN, NPC_VOLATILE_FELFIRE_FIEND, SacrolashGUID, SathrovarrGUID, and SPELL_SUNWELL_RADIANCE.
OnGameObjectCreate()
void instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_FORCE_FIELD:
                case GO_BOSS_COLLISION_1:
                case GO_BOSS_COLLISION_2:
                case GO_FIRE_BARRIER:
                case GO_MURUS_GATE_1:
                case GO_MURUS_GATE_2:
                    AddDoor(go);
                    break;
                case GO_ICE_BARRIER:
                    IceBarrierGUID = go->GetGUID();
                    go->setActive(true);
                    break;
                case GO_ORB_OF_THE_BLUE_DRAGONFLIGHT1:
                    blueFlightOrbGUID[0] = go->GetGUID();
                    break;
                case GO_ORB_OF_THE_BLUE_DRAGONFLIGHT2:
                    blueFlightOrbGUID[1] = go->GetGUID();
                    break;
                case GO_ORB_OF_THE_BLUE_DRAGONFLIGHT3:
                    blueFlightOrbGUID[2] = go->GetGUID();
                    break;
                case GO_ORB_OF_THE_BLUE_DRAGONFLIGHT4:
                    blueFlightOrbGUID[3] = go->GetGUID();
                    break;
                default:
                    break;
            }
        }
References InstanceScript::AddDoor(), blueFlightOrbGUID, Object::GetEntry(), Object::GetGUID(), GO_BOSS_COLLISION_1, GO_BOSS_COLLISION_2, GO_FIRE_BARRIER, GO_FORCE_FIELD, GO_ICE_BARRIER, GO_MURUS_GATE_1, GO_MURUS_GATE_2, GO_ORB_OF_THE_BLUE_DRAGONFLIGHT1, GO_ORB_OF_THE_BLUE_DRAGONFLIGHT2, GO_ORB_OF_THE_BLUE_DRAGONFLIGHT3, GO_ORB_OF_THE_BLUE_DRAGONFLIGHT4, IceBarrierGUID, and WorldObject::setActive().
OnGameObjectRemove()
void instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_FIRE_BARRIER:
                case GO_MURUS_GATE_1:
                case GO_MURUS_GATE_2:
                case GO_BOSS_COLLISION_1:
                case GO_BOSS_COLLISION_2:
                case GO_FORCE_FIELD:
                    RemoveDoor(go);
                    break;
                default:
                    break;
            }
        }
References Object::GetEntry(), GO_BOSS_COLLISION_1, GO_BOSS_COLLISION_2, GO_FIRE_BARRIER, GO_FORCE_FIELD, GO_MURUS_GATE_1, GO_MURUS_GATE_2, and InstanceScript::RemoveDoor().
OnPlayerEnter()
void instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
        {
            instance->LoadGrid(1477.94f, 643.22f);
            instance->LoadGrid(1641.45f, 988.08f);
            if (GameObject* gobj = instance->GetGameObject(IceBarrierGUID))
                gobj->SendUpdateToPlayer(player);
        }
References Map::GetGameObject(), IceBarrierGUID, InstanceScript::instance, and Map::LoadGrid().
Member Data Documentation
AlythessGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::AlythessGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
AnveenaGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::AnveenaGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
blueFlightOrbGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::blueFlightOrbGUID[4] protected
Referenced by GetGuidData(), and OnGameObjectCreate().
BrutallusGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::BrutallusGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
FelmystGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::FelmystGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
IceBarrierGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::IceBarrierGUID protected
Referenced by OnGameObjectCreate(), and OnPlayerEnter().
KalecgosDragonGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::KalecgosDragonGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
KalecgosKjGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::KalecgosKjGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
KilJaedenControllerGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::KilJaedenControllerGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
KilJaedenGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::KilJaedenGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
MadrigosaGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::MadrigosaGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
MuruGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::MuruGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
SacrolashGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::SacrolashGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
SathrovarrGUID
ObjectGuid instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::SathrovarrGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().