AzerothCore: boss_stormcaller_brundir::boss_stormcaller_brundirAI Struct Reference
boss_stormcaller_brundir::boss_stormcaller_brundirAI Struct Reference
Public Member Functions
boss_stormcaller_brundirAI (Creature *c)
void Reset () override
void JustReachedHome () override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void UpdatePhase ()
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void SpellHitTarget (Unit *, SpellInfo const *spellInfo) override
uint32 GetData (uint32 param) const override
void MovementInform (uint32 type, uint32 point) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
InstanceScript * pInstance
uint32 _phase
ObjectGuid _flyTargetGUID
uint32 _channelTimer
bool _stunnedAchievement
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_stormcaller_brundirAI()
boss_stormcaller_brundir::boss_stormcaller_brundirAI::boss_stormcaller_brundirAI (Creature * c) inline
                                                : ScriptedAI(c)
        {
            pInstance = c->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
GetData()
uint32 boss_stormcaller_brundir::boss_stormcaller_brundirAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_BRUNDIR)
                return _stunnedAchievement;
            return 0;
        }
References _stunnedAchievement, and DATA_BRUNDIR.
JustDied()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!pInstance)
                return;
            me->NearTeleportTo(me->GetPositionX(), me->GetPositionY(), 427.5, me->GetOrientation());
            if (IsEncounterComplete(pInstance, me))
            {
                pInstance->SetData(TYPE_ASSEMBLY, DONE);
                me->CastSpell(me, 65195, true); // credit
                Talk(SAY_BRUNDIR_ENCOUNTER_DEFEATED);
            }
            else
            {
                RestoreAssemblyHealth(pInstance->GetGuidData(DATA_STEELBREAKER), pInstance->GetGuidData(DATA_MOLGEIM), me);
                me->CastSpell(me, SPELL_SUPERCHARGE, true);
                Talk(SAY_BRUNDIR_DEATH);
            }
        }
References Unit::CastSpell(), DATA_MOLGEIM, DATA_STEELBREAKER, DONE, InstanceScript::GetGuidData(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), IsEncounterComplete(), ScriptedAI::me, Unit::NearTeleportTo(), pInstance, RestoreAssemblyHealth(), SAY_BRUNDIR_DEATH, SAY_BRUNDIR_ENCOUNTER_DEFEATED, ZoneScript::SetData(), SPELL_SUPERCHARGE, and TYPE_ASSEMBLY.
JustEngagedWith()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            me->InterruptNonMeleeSpells(false);
            me->setActive(true);
            me->SetInCombatWithZone();
            events.ScheduleEvent(EVENT_ENRAGE, 15min);
            UpdatePhase();
            if (!pInstance)
                return;
            for (uint8 i = 0; i < 3; ++i)
                if (Creature* boss = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_STEELBREAKER + i)))
                    if (!boss->IsInCombat())
                        boss->AI()->AttackStart(who);
        }
References DATA_STEELBREAKER, EVENT_ENRAGE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, pInstance, WorldObject::setActive(), Creature::SetInCombatWithZone(), and UpdatePhase().
JustReachedHome()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
        {
            me->setActive(false);
            me->RemoveAllAuras();
        }
References ScriptedAI::me, Unit::RemoveAllAuras(), and WorldObject::setActive().
KilledUnit()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!who->IsPlayer() || urand(0, 2))
                return;
            Talk(SAY_BRUNDIR_SLAY);
        }
References Object::IsPlayer(), SAY_BRUNDIR_SLAY, and urand().
MovementInform()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type == POINT_MOTION_TYPE && point == POINT_CHANNEL_STEELBREAKER)
                me->CastSpell(me, SPELL_LIGHTNING_CHANNEL_PRE, true);
        }
References Unit::CastSpell(), ScriptedAI::me, POINT_CHANNEL_STEELBREAKER, POINT_MOTION_TYPE, and SPELL_LIGHTNING_CHANNEL_PRE.
Reset()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            me->SetLootMode(0);
            RespawnAssemblyOfIron(pInstance, me);
            _channelTimer = 0;
            _phase = 0;
            _flyTargetGUID.Clear();
            _stunnedAchievement = true;
            events.Reset();
            me->SetDisableGravity(false);
            me->SetRegeneratingHealth(true);
            me->SetReactState(REACT_AGGRESSIVE);
            if (pInstance)
                pInstance->SetData(TYPE_ASSEMBLY, NOT_STARTED);
        }
References _channelTimer, _flyTargetGUID, _phase, _stunnedAchievement, ObjectGuid::Clear(), ScriptedAI::me, NOT_STARTED, pInstance, REACT_AGGRESSIVE, RespawnAssemblyOfIron(), ZoneScript::SetData(), Creature::SetDisableGravity(), Creature::SetLootMode(), Creature::SetReactState(), Creature::SetRegeneratingHealth(), and TYPE_ASSEMBLY.
SpellHit()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_SUPERCHARGE)
                UpdatePhase();
        }
References SpellInfo::Id, SPELL_SUPERCHARGE, and UpdatePhase().
SpellHitTarget()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::SpellHitTarget (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_CHAIN_LIGHTNING || spellInfo->Id == uint32(RAID_MODE(61916, 63482))) // Lightning Whirl triggered
                _stunnedAchievement = false;
        }
References _stunnedAchievement, SpellInfo::Id, ScriptedAI::RAID_MODE(), and SPELL_CHAIN_LIGHTNING.
UpdateAI()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!me->IsInCombat() && me->GetReactState() == REACT_AGGRESSIVE)
            {
                _channelTimer += diff;
                if (_channelTimer >= 10000)
                {
                    _channelTimer = 0;
                    float o = urand(0, 5) * M_PI / 3.0f;
                    me->InterruptNonMeleeSpells(false);
                    me->GetMotionMaster()->MovePoint(POINT_CHANNEL_STEELBREAKER, 1587.18f + 10.0f * cos(o), 121.02f + 10.0f * std::sin(o), 427.3f);
                }
            }
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_CHAIN_LIGHTNING:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
                        me->CastSpell(target, SPELL_CHAIN_LIGHTNING, false);
                    events.Repeat(9s, 17s);
                    break;
                case EVENT_OVERLOAD:
                    Talk(EMOTE_BRUNDIR_OVERLOAD);
                    me->CastSpell(me, SPELL_OVERLOAD, true);
                    events.RescheduleEvent(EVENT_OVERLOAD, 25s, 40s);
                    break;
                case EVENT_LIGHTNING_WHIRL:
                    Talk(SAY_BRUNDIR_SPECIAL);
                    me->CastSpell(me, SPELL_LIGHTNING_WHIRL, true);
                    events.Repeat(10s, 25s);
                    break;
                case EVENT_LIGHTNING_TENDRILS:
                    {
                        // Reschedule old
                        events.Repeat(35s);
                        events.DelayEvents(18s);
                        Talk(SAY_BRUNDIR_FLIGHT);
                        Unit* oldVictim = me->GetVictim();
                        _flyTargetGUID = oldVictim->GetGUID();
                        me->SetRegeneratingHealth(false);
                        me->SetDisableGravity(true);
                        me->SetHover(true);
                        me->CombatStop();
                        me->StopMoving();
                        me->SetReactState(REACT_PASSIVE);
                        me->SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
                        me->SetUnitFlag(UNIT_FLAG_STUNNED);
                        me->CastSpell(me, SPELL_LIGHTNING_TENDRILS, true);
                        me->CastSpell(me, 61883, true);
                        events.ScheduleEvent(EVENT_LIGHTNING_LAND, 16s);
                        events.ScheduleEvent(EVENT_LIGHTNING_FLIGHT, 1s);
                        break;
                    }
                case EVENT_LIGHTNING_LAND:
                    {
                        float speed = me->GetDistance(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()) / (1000.0f * 0.001f);
                        me->MonsterMoveWithSpeed(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), speed);
                        events.ScheduleEvent(EVENT_LAND_LAND, 1s);
                        break;
                    }
                case EVENT_LAND_LAND:
                    me->SetCanFly(false);
                    me->SetHover(false);
                    me->SetReactState(REACT_AGGRESSIVE);
                    me->SetDisableGravity(false);
                    if (Unit* flyTarget = ObjectAccessor::GetUnit(*me, _flyTargetGUID))
                    {
                        me->Attack(flyTarget, false);
                    }
                    me->SetRegeneratingHealth(true);
                    _flyTargetGUID.Clear();
                    me->RemoveAura(SPELL_LIGHTNING_TENDRILS);
                    me->RemoveAura(61883);
                    DoResetThreatList();
                    events.CancelEvent(EVENT_LIGHTNING_FLIGHT);
                    break;
                case EVENT_ENRAGE:
                    Talk(SAY_BRUNDIR_BERSERK);
                    me->CastSpell(me, SPELL_BERSERK, true);
                    break;
                case EVENT_LIGHTNING_FLIGHT:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true))
                    {
                        me->GetMotionMaster()->MovePoint(0, *target);
                    }
                    events.ScheduleEvent(EVENT_LIGHTNING_FLIGHT, 6s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References _channelTimer, _flyTargetGUID, Unit::Attack(), Unit::CastSpell(), ObjectGuid::Clear(), Unit::CombatStop(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreatList(), EMOTE_BRUNDIR_OVERLOAD, ObjectGuid::Empty, EVENT_CHAIN_LIGHTNING, EVENT_ENRAGE, EVENT_LAND_LAND, EVENT_LIGHTNING_FLIGHT, EVENT_LIGHTNING_LAND, EVENT_LIGHTNING_TENDRILS, EVENT_LIGHTNING_WHIRL, EVENT_OVERLOAD, WorldObject::GetDistance(), Object::GetGUID(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Creature::GetReactState(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::HasUnitState(), Unit::InterruptNonMeleeSpells(), Unit::IsInCombat(), ScriptedAI::me, Unit::MonsterMoveWithSpeed(), MotionMaster::MovePoint(), POINT_CHANNEL_STEELBREAKER, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAura(), SAY_BRUNDIR_BERSERK, SAY_BRUNDIR_FLIGHT, SAY_BRUNDIR_SPECIAL, UnitAI::SelectTarget(), Creature::SetCanFly(), Creature::SetDisableGravity(), Object::SetGuidValue(), Creature::SetHover(), Creature::SetReactState(), Creature::SetRegeneratingHealth(), Unit::SetUnitFlag(), SPELL_BERSERK, SPELL_CHAIN_LIGHTNING, SPELL_LIGHTNING_TENDRILS, SPELL_LIGHTNING_WHIRL, SPELL_OVERLOAD, Unit::StopMoving(), UNIT_FIELD_TARGET, UNIT_FLAG_STUNNED, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
UpdatePhase()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdatePhase () inline
        {
            if (_phase >= 3)
                return;
            ++_phase;
            switch (_phase)
            {
                case 1:
                    events.RescheduleEvent(EVENT_CHAIN_LIGHTNING, 9s, 17s);
                    events.RescheduleEvent(EVENT_OVERLOAD, 25s, 40s);
                    break;
                case 2:
                    events.RescheduleEvent(EVENT_LIGHTNING_WHIRL, 20s, 40s);
                    break;
                case 3:
                    me->ResetLootMode();
                    me->CastSpell(me, SPELL_STORMSHIELD, true);
                    events.RescheduleEvent(EVENT_LIGHTNING_TENDRILS, 15s, 16s);
                    break;
            }
        }
References _phase, Unit::CastSpell(), EVENT_CHAIN_LIGHTNING, EVENT_LIGHTNING_TENDRILS, EVENT_LIGHTNING_WHIRL, EVENT_OVERLOAD, ScriptedAI::me, Creature::ResetLootMode(), and SPELL_STORMSHIELD.
Referenced by JustEngagedWith(), and SpellHit().
Member Data Documentation
_channelTimer
uint32 boss_stormcaller_brundir::boss_stormcaller_brundirAI::_channelTimer
Referenced by Reset(), and UpdateAI().
_flyTargetGUID
ObjectGuid boss_stormcaller_brundir::boss_stormcaller_brundirAI::_flyTargetGUID
Referenced by Reset(), and UpdateAI().
_phase
uint32 boss_stormcaller_brundir::boss_stormcaller_brundirAI::_phase
Referenced by Reset(), and UpdatePhase().
_stunnedAchievement
bool boss_stormcaller_brundir::boss_stormcaller_brundirAI::_stunnedAchievement
Referenced by GetData(), Reset(), and SpellHitTarget().
events
EventMap boss_stormcaller_brundir::boss_stormcaller_brundirAI::events
pInstance
InstanceScript* boss_stormcaller_brundir::boss_stormcaller_brundirAI::pInstance
Referenced by boss_stormcaller_brundirAI(), JustDied(), JustEngagedWith(), and Reset().