AzerothCore: AuctionHouseObject Class Reference
AuctionHouseObject Class Reference
#include "AuctionHouseMgr.h"
Public Types
typedef std::map< uint32, AuctionEntry * > AuctionEntryMap
Public Member Functions
AuctionHouseObject ()
~AuctionHouseObject ()
uint32 Getcount () const
AuctionEntryMap::iterator GetAuctionsBegin ()
AuctionEntryMap::iterator GetAuctionsEnd ()
AuctionEntryMap const & GetAuctions ()
AuctionEntry * GetAuction (uint32 id) const
void AddAuction (AuctionEntry *auction)
bool RemoveAuction (AuctionEntry *auction)
void Update ()
Private Attributes
AuctionEntryMap _auctionsMap
AuctionEntryMap::const_iterator _next
Detailed Description
Member Typedef Documentation
AuctionEntryMap
typedef std::map<uint32, AuctionEntry*> AuctionHouseObject::AuctionEntryMap
Constructor & Destructor Documentation
AuctionHouseObject()
AuctionHouseObject::AuctionHouseObject () inline
{ _next = _auctionsMap.begin(); }
References _auctionsMap, and _next.
~AuctionHouseObject()
AuctionHouseObject::~AuctionHouseObject () inline
    {
        for (auto& itr : _auctionsMap)
            delete itr.second;
    }
References _auctionsMap.
Member Function Documentation
AddAuction()
void AuctionHouseObject::AddAuction (AuctionEntry * auction)
{
    ASSERT(auction);
    _auctionsMap[auction->Id] = auction;
    sAuctionMgr->GetAuctionHouseSearcher()->AddAuction(auction);
    sScriptMgr->OnAuctionAdd(this, auction);
}
References _auctionsMap, ASSERT, AuctionEntry::Id, sAuctionMgr, and sScriptMgr.
Referenced by WorldSession::HandleAuctionSellItem(), and AuctionHouseMgr::LoadAuctions().
GetAuction()
AuctionEntry * AuctionHouseObject::GetAuction (uint32 id) const inline
    {
        AuctionEntryMap::const_iterator itr = _auctionsMap.find(id);
        return itr != _auctionsMap.end() ? itr->second : nullptr;
    }
References _auctionsMap.
Referenced by WorldSession::HandleAuctionPlaceBid(), and WorldSession::HandleAuctionRemoveItem().
GetAuctions()
AuctionEntryMap const & AuctionHouseObject::GetAuctions () inline
{ return _auctionsMap; }
References _auctionsMap.
Referenced by WorldSession::HandleCharFactionOrRaceChangeCallback().
GetAuctionsBegin()
AuctionEntryMap::iterator AuctionHouseObject::GetAuctionsBegin () inline
{ return _auctionsMap.begin(); }
References _auctionsMap.
GetAuctionsEnd()
AuctionEntryMap::iterator AuctionHouseObject::GetAuctionsEnd () inline
{ return _auctionsMap.end(); }
References _auctionsMap.
Getcount()
uint32 AuctionHouseObject::Getcount () const inline
{ return _auctionsMap.size(); }
References _auctionsMap.
RemoveAuction()
bool AuctionHouseObject::RemoveAuction (AuctionEntry * auction)
{
    bool wasInMap = !!_auctionsMap.erase(auction->Id);
    sAuctionMgr->GetAuctionHouseSearcher()->RemoveAuction(auction);
    sScriptMgr->OnAuctionRemove(this, auction);
    // we need to delete the entry, it is not referenced any more
    delete auction;
    auction = nullptr;
    return wasInMap;
}
References _auctionsMap, AuctionEntry::Id, sAuctionMgr, and sScriptMgr.
Referenced by WorldSession::HandleAuctionPlaceBid(), WorldSession::HandleAuctionRemoveItem(), and Update().
Update()
void AuctionHouseObject::Update ()
Handle expired auctions
Either cancel the auction if there was no bidder
Or perform the transaction
In any case clear the auction
{
    time_t checkTime = GameTime::GetGameTime().count() + 60;
    // If storage is empty, no need to update. next == nullptr in this case.
    if (_auctionsMap.empty())
        return;
    CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
    for (AuctionEntryMap::iterator itr, iter = _auctionsMap.begin(); iter != _auctionsMap.end(); )
    {
        itr = iter++;
        AuctionEntry* auction = (*itr).second;
        if (auction->expire_time > checkTime)
            continue;
        if (!auction->bidder)
        {
            sAuctionMgr->SendAuctionExpiredMail(auction, trans);
            sScriptMgr->OnAuctionExpire(this, auction);
        }
        else
        {
            //we should send an "item sold" message if the seller is online
            //we send the item to the winner
            //we send the money to the seller
            sAuctionMgr->SendAuctionSuccessfulMail(auction, trans);
            sAuctionMgr->SendAuctionWonMail(auction, trans);
            sScriptMgr->OnAuctionSuccessful(this, auction);
        }
        auction->DeleteFromDB(trans);
        sAuctionMgr->RemoveAItem(auction->item_guid);
        RemoveAuction(auction);
    }
    CharacterDatabase.CommitTransaction(trans);
}
References _auctionsMap, AuctionEntry::bidder, CharacterDatabase, AuctionEntry::DeleteFromDB(), AuctionEntry::expire_time, GameTime::GetGameTime(), AuctionEntry::item_guid, RemoveAuction(), sAuctionMgr, and sScriptMgr.
Referenced by AuctionHouseMgr::Update().
Member Data Documentation
_auctionsMap
AuctionEntryMap AuctionHouseObject::_auctionsMap private
Referenced by AddAuction(), AuctionHouseObject(), GetAuction(), GetAuctions(), GetAuctionsBegin(), GetAuctionsEnd(), Getcount(), RemoveAuction(), Update(), and ~AuctionHouseObject().
_next
AuctionEntryMap::const_iterator AuctionHouseObject::_next private
Referenced by AuctionHouseObject().