AzerothCore: npc_pet_mage_mirror_image Struct Reference
npc_pet_mage_mirror_image Struct Reference
Public Member Functions
npc_pet_mage_mirror_image (Creature *creature)
void InitializeAI () override
void EnterEvadeMode (EvadeReason) override
void MySelectNextTarget ()
void Reset () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from CasterAI
CasterAI (Creature *c)
void InitializeAI () override
void AttackStart (Unit *victim) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
Public Member Functions inherited from CombatAI
CombatAI (Creature *c)
void InitializeAI () override
void Reset () override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void JustDied (Unit *killer) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
uint32 selectionTimer
ObjectGuid _ebonGargoyleGUID
uint32 checktarget
uint32 dist = urand(1, 5)
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CombatAI
static int32 Permissible (Creature const *)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CombatAI
EventMap events
SpellVct spells
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_pet_mage_mirror_image()
npc_pet_mage_mirror_image::npc_pet_mage_mirror_image (Creature * creature) inline
: CasterAI(creature) { }
Member Function Documentation
EnterEvadeMode()
void npc_pet_mage_mirror_image::EnterEvadeMode (EvadeReason) inline override virtual
Reimplemented from CreatureAI.
    {
        if (me->IsInEvadeMode() || !me->IsAlive())
            return;
        Unit* owner = me->GetCharmerOrOwner();
        me->CombatStop(true);
        if (owner && !me->HasUnitState(UNIT_STATE_FOLLOW))
        {
            me->GetMotionMaster()->Clear(false);
            me->GetMotionMaster()->MoveFollow(owner, PET_FOLLOW_DIST, me->GetFollowAngle(), MOTION_SLOT_ACTIVE);
        }
    }
References MotionMaster::Clear(), Unit::CombatStop(), Unit::GetCharmerOrOwner(), Unit::GetFollowAngle(), Unit::GetMotionMaster(), Unit::HasUnitState(), Unit::IsAlive(), Creature::IsInEvadeMode(), CreatureAI::me, MOTION_SLOT_ACTIVE, MotionMaster::MoveFollow(), PET_FOLLOW_DIST, and UNIT_STATE_FOLLOW.
Referenced by MySelectNextTarget().
InitializeAI()
void npc_pet_mage_mirror_image::InitializeAI () inline override virtual
Reimplemented from CasterAI.
    {
        CasterAI::InitializeAI();
        Unit* owner = me->GetOwner();
        if (!owner)
            return;
        // Clone Me!
        owner->CastSpell(me, SPELL_MAGE_CLONE_ME, true);
        // xinef: Glyph of Mirror Image (4th copy)
        float angle = 0.0f;
        switch (me->GetUInt32Value(UNIT_CREATED_BY_SPELL))
        {
            case SPELL_SUMMON_MIRROR_IMAGE1:
                angle = 0.5f * M_PI;
                break;
            case SPELL_SUMMON_MIRROR_IMAGE2:
                angle = M_PI;
                break;
            case SPELL_SUMMON_MIRROR_IMAGE3:
                angle = 1.5f * M_PI;
                break;
        }
        ((Minion*)me)->SetFollowAngle(angle);
        if (owner->IsInCombat())
            me->NearTeleportTo(me->GetPositionX() + cos(angle)*dist, me->GetPositionY() + std::sin(angle)*dist, me->GetPositionZ(), me->GetOrientation(), false, false, false, false);
        else
            me->GetMotionMaster()->MoveFollow(owner, PET_FOLLOW_DIST, me->GetFollowAngle(), MOTION_SLOT_ACTIVE);
        me->SetReactState(REACT_DEFENSIVE);
        // Xinef: Inherit Master's Threat List (not yet implemented)
        //owner->CastSpell((Unit*)nullptr, SPELL_MAGE_MASTERS_THREAT_LIST, true);
        HostileReference* ref = owner->getHostileRefMgr().getFirst();
        while (ref)
        {
            if (Unit* unit = ref->GetSource()->GetOwner())
                unit->AddThreat(me, ref->GetThreat() - ref->getTempThreatModifier());
            ref = ref->next();
        }
        _ebonGargoyleGUID.Clear();
        // Xinef: copy caster auras
        Unit::VisibleAuraMap const* visibleAuraMap = owner->GetVisibleAuras();
        for (Unit::VisibleAuraMap::const_iterator itr = visibleAuraMap->begin(); itr != visibleAuraMap->end(); ++itr)
            if (Aura* visAura = itr->second->GetBase())
            {
                // Ebon Gargoyle
                if (visAura->GetId() == 49206 && me->GetUInt32Value(UNIT_CREATED_BY_SPELL) == SPELL_SUMMON_MIRROR_IMAGE1)
                {
                    if (Unit* gargoyle = visAura->GetCaster())
                        _ebonGargoyleGUID = gargoyle->GetGUID();
                    continue;
                }
                SpellScriptsBounds bounds = sObjectMgr->GetSpellScriptsBounds(visAura->GetId());
                if (bounds.first != bounds.second)
                    continue;
                std::vector<int32> const* spellTriggered = sSpellMgr->GetSpellLinked(visAura->GetId() + SPELL_LINK_AURA);
                if (!spellTriggered || !spellTriggered->empty())
                    continue;
                if (Aura* newAura = me->AddAura(visAura->GetId(), me))
                    newAura->SetDuration(visAura->GetDuration());
            }
        me->m_Events.AddEvent(new DeathEvent(*me), me->m_Events.CalculateTime(29500));
    }
References _ebonGargoyleGUID, Unit::AddAura(), EventProcessor::AddEvent(), HostileReference::AddThreat(), EventProcessor::CalculateTime(), Unit::CastSpell(), ObjectGuid::Clear(), dist, HostileRefMgr::getFirst(), Unit::GetFollowAngle(), Unit::getHostileRefMgr(), Unit::GetMotionMaster(), Position::GetOrientation(), ThreatMgr::GetOwner(), Unit::GetOwner(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Reference< TO, FROM >::GetSource(), HostileReference::getTempThreatModifier(), HostileReference::GetThreat(), Object::GetUInt32Value(), Unit::GetVisibleAuras(), CasterAI::InitializeAI(), Unit::IsInCombat(), Unit::m_Events, CreatureAI::me, MOTION_SLOT_ACTIVE, MotionMaster::MoveFollow(), Unit::NearTeleportTo(), HostileReference::next(), PET_FOLLOW_DIST, REACT_DEFENSIVE, Creature::SetReactState(), sObjectMgr, SPELL_LINK_AURA, SPELL_MAGE_CLONE_ME, SPELL_SUMMON_MIRROR_IMAGE1, SPELL_SUMMON_MIRROR_IMAGE2, SPELL_SUMMON_MIRROR_IMAGE3, sSpellMgr, and UNIT_CREATED_BY_SPELL.
MySelectNextTarget()
void npc_pet_mage_mirror_image::MySelectNextTarget () inline
    {
        if (_ebonGargoyleGUID)
        {
            Unit* gargoyle = ObjectAccessor::GetUnit(*me, _ebonGargoyleGUID);
            if (gargoyle && gargoyle->GetAI())
                gargoyle->GetAI()->AttackStart(me);
            _ebonGargoyleGUID.Clear();
        }
        Unit* owner = me->GetOwner();
        if (owner && owner->IsPlayer())
        {
            Unit* selection = owner->ToPlayer()->GetSelectedUnit();
            if (selection)
            {
                me->GetThreatMgr().ResetAllThreat();
                me->AddThreat(selection, 1000000.0f);
                if (owner->IsInCombat())
                    AttackStart(selection);
            }
            if (!owner->IsInCombat() && !me->GetVictim())
                EnterEvadeMode(EVADE_REASON_OTHER);
        }
    }
References _ebonGargoyleGUID, Unit::AddThreat(), UnitAI::AttackStart(), CasterAI::AttackStart(), ObjectGuid::Clear(), EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, Unit::GetAI(), Unit::GetOwner(), Player::GetSelectedUnit(), Unit::GetThreatMgr(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::IsInCombat(), Object::IsPlayer(), CreatureAI::me, ThreatMgr::ResetAllThreat(), and Object::ToPlayer().
Referenced by UpdateAI().
Reset()
void npc_pet_mage_mirror_image::Reset () inline override virtual
Reimplemented from CombatAI.
    {
        selectionTimer = 0;
        checktarget = 0;
    }
References checktarget, and selectionTimer.
UpdateAI()
void npc_pet_mage_mirror_image::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from CasterAI.
    {
        events.Update(diff);
        if (events.GetTimer() < 1200)
            return;
        if (!me->IsInCombat() || !me->GetVictim())
        {
            MySelectNextTarget();
            return;
        }
        checktarget += diff;
        if (checktarget >= 1000)
        {
            if (me->GetVictim()->HasBreakableByDamageCrowdControlAura() || !me->GetVictim()->IsAlive())
            {
                MySelectNextTarget();
                me->InterruptNonMeleeSpells(true); // Stop casting if target is CC or not Alive.
                return;
            }
        }
        if (me->HasUnitState(UNIT_STATE_CASTING))
            return;
        if (uint32 spellId = events.ExecuteEvent())
        {
            events.RescheduleEvent(spellId, spellId == 59637 ? 6500 : 2500);
            me->CastSpell(me->GetVictim(), spellId, false);
        }
    }
References Unit::CastSpell(), checktarget, Unit::GetVictim(), Unit::HasBreakableByDamageCrowdControlAura(), Unit::HasUnitState(), Unit::InterruptNonMeleeSpells(), Unit::IsAlive(), Unit::IsInCombat(), CreatureAI::me, MySelectNextTarget(), and UNIT_STATE_CASTING.
Member Data Documentation
_ebonGargoyleGUID
ObjectGuid npc_pet_mage_mirror_image::_ebonGargoyleGUID
Referenced by InitializeAI(), and MySelectNextTarget().
checktarget
uint32 npc_pet_mage_mirror_image::checktarget
Referenced by Reset(), and UpdateAI().
dist
uint32 npc_pet_mage_mirror_image::dist = urand(1, 5)
Referenced by InitializeAI().
selectionTimer
uint32 npc_pet_mage_mirror_image::selectionTimer
Referenced by Reset().