AzerothCore: StoneGripTargetSelector Class Reference
StoneGripTargetSelector Class Reference
Public Member Functions
StoneGripTargetSelector (Creature *me, Unit const *victim)
bool operator() (WorldObject *target) const
Private Attributes
Creature * _me
Unit const * _victim
Detailed Description
Constructor & Destructor Documentation
StoneGripTargetSelector()
StoneGripTargetSelector::StoneGripTargetSelector (Creature * me, Unit const * victim) inline
: _me(me), _victim(victim) {}
Member Function Documentation
operator()()
bool StoneGripTargetSelector::operator() (WorldObject * target) const inline
    {
        if (target == _victim && _me->GetThreatMgr().GetThreatListSize() > 1)
            return true;
        if (target->GetTypeId() != TYPEID_PLAYER)
            return true;
        return false;
    }
References _me, _victim, ThreatMgr::GetThreatListSize(), Unit::GetThreatMgr(), Object::GetTypeId(), and TYPEID_PLAYER.
Member Data Documentation
_me
Creature* StoneGripTargetSelector::_me private
Referenced by operator()().
_victim
Unit const* StoneGripTargetSelector::_victim private
Referenced by operator()().