AzerothCore: CharacterCache Class Reference
CharacterCache Class Reference
#include "CharacterCache.h"
Public Member Functions
CharacterCache () noexcept=default
~CharacterCache () noexcept=default
void LoadCharacterCacheStorage ()
Loads several pieces of information on server startup with the GUID There is no further database query necessary. These are a number of methods that work into the calling function.
void RefreshCacheEntry (uint32 lowGuid)
void AddCharacterCacheEntry (ObjectGuid const &guid, uint32 accountId, std::string const &name, uint8 gender, uint8 race, uint8 playerClass, uint8 level)
void DeleteCharacterCacheEntry (ObjectGuid const &guid, std::string const &name)
void UpdateCharacterData (ObjectGuid const &guid, std::string const &name, Optional< uint8 > gender={}, Optional< uint8 > race={})
void UpdateCharacterLevel (ObjectGuid const &guid, uint8 level)
void UpdateCharacterAccountId (ObjectGuid const &guid, uint32 accountId)
void UpdateCharacterGuildId (ObjectGuid const &guid, ObjectGuid::LowType guildId)
void UpdateCharacterArenaTeamId (ObjectGuid const &guid, uint8 slot, uint32 arenaTeamId)
void UpdateCharacterMailCount (ObjectGuid const &guid, int8 count, bool update=false)
void DecreaseCharacterMailCount (ObjectGuid const &guid)
void IncreaseCharacterMailCount (ObjectGuid const &guid)
bool HasCharacterCacheEntry (ObjectGuid const &guid) const
CharacterCacheEntry const * GetCharacterCacheByGuid (ObjectGuid const &guid) const
CharacterCacheEntry const * GetCharacterCacheByName (std::string const &name) const
void UpdateCharacterGroup (ObjectGuid const &guid, ObjectGuid groupGUID)
void ClearCharacterGroup (ObjectGuid const &guid)
ObjectGuid GetCharacterGuidByName (std::string const &name) const
bool GetCharacterNameByGuid (ObjectGuid guid, std::string &name) const
uint32 GetCharacterTeamByGuid (ObjectGuid guid) const
uint32 GetCharacterAccountIdByGuid (ObjectGuid guid) const
uint32 GetCharacterAccountIdByName (std::string const &name) const
uint8 GetCharacterLevelByGuid (ObjectGuid guid) const
ObjectGuid::LowType GetCharacterGuildIdByGuid (ObjectGuid guid) const
uint32 GetCharacterArenaTeamIdByGuid (ObjectGuid guid, uint8 type) const
ObjectGuid GetCharacterGroupGuidByGuid (ObjectGuid guid) const
Static Public Member Functions
static CharacterCache * instance ()
Detailed Description
Constructor & Destructor Documentation
CharacterCache()
CharacterCache::CharacterCache () default noexcept
~CharacterCache()
CharacterCache::~CharacterCache () default noexcept
Member Function Documentation
AddCharacterCacheEntry()
void CharacterCache::AddCharacterCacheEntry (ObjectGuid const & guid, uint32 accountId, std::string const & name, uint8 gender, uint8 race, uint8 playerClass, uint8 level)
{
    CharacterCacheEntry& data = _characterCacheStore[guid];
    data.Guid = guid;
    data.Name = name;
    data.AccountId = accountId;
    data.Race = race;
    data.Sex = gender;
    data.Class = playerClass;
    data.Level = level;
    data.GuildId = 0;                           // Will be set in guild loading or guild setting
    for (uint8 i = 0; i < MAX_ARENA_SLOT; ++i)
    {
        data.ArenaTeamId[i] = 0; // Will be set in arena teams loading
    }
    // Fill Name to Guid Store
    _characterCacheByNameStore[name] = &data;
}
References CharacterCacheEntry::AccountId, CharacterCacheEntry::ArenaTeamId, CharacterCacheEntry::Class, CharacterCacheEntry::Guid, CharacterCacheEntry::GuildId, CharacterCacheEntry::Level, MAX_ARENA_SLOT, CharacterCacheEntry::Name, CharacterCacheEntry::Race, and CharacterCacheEntry::Sex.
Referenced by LoadCharacterCacheStorage(), and RefreshCacheEntry().
ClearCharacterGroup()
void CharacterCache::ClearCharacterGroup (ObjectGuid const & guid) inline
{ UpdateCharacterGroup(guid, ObjectGuid::Empty); };
References ObjectGuid::Empty.
DecreaseCharacterMailCount()
void CharacterCache::DecreaseCharacterMailCount (ObjectGuid const & guid) inline
{ UpdateCharacterMailCount(guid, -1); };
DeleteCharacterCacheEntry()
void CharacterCache::DeleteCharacterCacheEntry (ObjectGuid const & guid, std::string const & name)
{
    _characterCacheStore.erase(guid);
    _characterCacheByNameStore.erase(name);
}
Referenced by RefreshCacheEntry().
GetCharacterAccountIdByGuid()
uint32 CharacterCache::GetCharacterAccountIdByGuid (ObjectGuid guid) const
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return 0;
    }
    return itr->second.AccountId;
}
GetCharacterAccountIdByName()
uint32 CharacterCache::GetCharacterAccountIdByName (std::string const & name) const
{
    auto itr = _characterCacheByNameStore.find(name);
    if (itr != _characterCacheByNameStore.end())
    {
        return itr->second->AccountId;
    }
    return 0;
}
GetCharacterArenaTeamIdByGuid()
uint32 CharacterCache::GetCharacterArenaTeamIdByGuid (ObjectGuid guid, uint8 type) const
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return 0;
    }
    return itr->second.ArenaTeamId[type];
}
GetCharacterCacheByGuid()
CharacterCacheEntry const * CharacterCache::GetCharacterCacheByGuid (ObjectGuid const & guid) const
{
    auto itr = _characterCacheStore.find(guid);
    if (itr != _characterCacheStore.end())
    {
        return &itr->second;
    }
    return nullptr;
}
GetCharacterCacheByName()
CharacterCacheEntry const * CharacterCache::GetCharacterCacheByName (std::string const & name) const
{
    auto itr = _characterCacheByNameStore.find(name);
    if (itr != _characterCacheByNameStore.end())
    {
        return itr->second;
    }
    return nullptr;
}
GetCharacterGroupGuidByGuid()
ObjectGuid CharacterCache::GetCharacterGroupGuidByGuid (ObjectGuid guid) const
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return ObjectGuid::Empty;
    }
    return itr->second.GroupGuid;
}
References ObjectGuid::Empty.
GetCharacterGuidByName()
ObjectGuid CharacterCache::GetCharacterGuidByName (std::string const & name) const
{
    auto itr = _characterCacheByNameStore.find(name);
    if (itr != _characterCacheByNameStore.end())
    {
        return itr->second->Guid;
    }
    return ObjectGuid::Empty;
}
References ObjectGuid::Empty.
GetCharacterGuildIdByGuid()
ObjectGuid::LowType CharacterCache::GetCharacterGuildIdByGuid (ObjectGuid guid) const
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return 0;
    }
    return itr->second.GuildId;
}
GetCharacterLevelByGuid()
uint8 CharacterCache::GetCharacterLevelByGuid (ObjectGuid guid) const
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return 0;
    }
    return itr->second.Level;
}
GetCharacterNameByGuid()
bool CharacterCache::GetCharacterNameByGuid (ObjectGuid guid, std::string & name) const
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return false;
    }
    name = itr->second.Name;
    return true;
}
GetCharacterTeamByGuid()
uint32 CharacterCache::GetCharacterTeamByGuid (ObjectGuid guid) const
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return 0;
    }
    return Player::TeamIdForRace(itr->second.Race);
}
References Player::TeamIdForRace().
HasCharacterCacheEntry()
bool CharacterCache::HasCharacterCacheEntry (ObjectGuid const & guid) const
{
    return _characterCacheStore.find(guid) != _characterCacheStore.end();
}
IncreaseCharacterMailCount()
void CharacterCache::IncreaseCharacterMailCount (ObjectGuid const & guid) inline
{ UpdateCharacterMailCount(guid, 1); };
instance()
CharacterCache * CharacterCache::instance () static
{
    static CharacterCache instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadCharacterCacheStorage()
void CharacterCache::LoadCharacterCacheStorage ()
Loads several pieces of information on server startup with the GUID There is no further database query necessary. These are a number of methods that work into the calling function.
Parameters
guid Requires a guid to call
Returns
Name, Gender, Race, Class and Level of player character Example Usage:
CharacterCacheEntry const* characterInfo = sCharacterCache->GetCharacterCacheByGuid(GUID);
if (!characterInfo)
    return;
std::string playerName = characterInfo->Name;
uint8 playerGender = characterInfo->Sex;
uint8 playerRace = characterInfo->Race;
uint8 playerClass = characterInfo->Class;
uint8 playerLevel = characterInfo->Level;
{
    _characterCacheStore.clear();
    uint32 oldMSTime = getMSTime();
    QueryResult result = CharacterDatabase.Query("SELECT guid, name, account, race, gender, class, level FROM characters");
    if (!result)
    {
        LOG_INFO("server.loading", "No character name data loaded, empty query!");
        return;
    }
    do
    {
        Field* fields = result->Fetch();
        AddCharacterCacheEntry(ObjectGuid::Create<HighGuid::Player>(fields[0].Get<uint32>()) /*guid*/, fields[2].Get<uint32>() /*account*/, fields[1].Get<std::string>() /*name*/,
            fields[4].Get<uint8>() /*gender*/, fields[3].Get<uint8>() /*race*/, fields[5].Get<uint8>() /*class*/, fields[6].Get<uint8>() /*level*/);
    } while (result->NextRow());
    QueryResult mailCountResult = CharacterDatabase.Query("SELECT receiver, COUNT(receiver) FROM mail GROUP BY receiver");
    if (mailCountResult)
    {
        do
        {
            Field* fields = mailCountResult->Fetch();
            UpdateCharacterMailCount(ObjectGuid(HighGuid::Player, fields[0].Get<uint32>()), static_cast<int8>(fields[1].Get<uint64>()), true);
        } while (mailCountResult->NextRow());
    }
    LOG_INFO("server.loading", ">> Loaded Character Infos For {} Characters in {} ms", _characterCacheStore.size(), GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References AddCharacterCacheEntry(), CharacterDatabase, getMSTime(), GetMSTimeDiffToNow(), LOG_INFO, and UpdateCharacterMailCount().
RefreshCacheEntry()
void CharacterCache::RefreshCacheEntry (uint32 lowGuid)
{
    QueryResult result = CharacterDatabase.Query("SELECT guid, name, account, race, gender, class, level FROM characters WHERE guid = {}", lowGuid);
    if (!result)
    {
        return;
    }
    do
    {
        Field* fields = result->Fetch();
        DeleteCharacterCacheEntry(ObjectGuid::Create<HighGuid::Player>(lowGuid), fields[1].Get<std::string>());
        AddCharacterCacheEntry(ObjectGuid::Create<HighGuid::Player>(fields[0].Get<uint32>()) /*guid*/, fields[2].Get<uint32>() /*account*/, fields[1].Get<std::string>() /*name*/, fields[4].Get<uint8>() /*gender*/, fields[3].Get<uint8>() /*race*/, fields[5].Get<uint8>() /*class*/, fields[6].Get<uint8>() /*level*/);
    } while (result->NextRow());
    QueryResult mailCountResult = CharacterDatabase.Query("SELECT receiver, COUNT(receiver) FROM mail WHERE receiver = {} GROUP BY receiver", lowGuid);
    if (mailCountResult)
    {
        do
        {
            Field* fields = mailCountResult->Fetch();
            UpdateCharacterMailCount(ObjectGuid(HighGuid::Player, fields[0].Get<uint32>()), static_cast<int8>(fields[1].Get<uint64>()), true);
        } while (mailCountResult->NextRow());
    }
}
References AddCharacterCacheEntry(), CharacterDatabase, DeleteCharacterCacheEntry(), and UpdateCharacterMailCount().
UpdateCharacterAccountId()
void CharacterCache::UpdateCharacterAccountId (ObjectGuid const & guid, uint32 accountId)
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return;
    }
    itr->second.AccountId = accountId;
}
UpdateCharacterArenaTeamId()
void CharacterCache::UpdateCharacterArenaTeamId (ObjectGuid const & guid, uint8 slot, uint32 arenaTeamId)
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return;
    }
    itr->second.ArenaTeamId[slot] = arenaTeamId;
}
UpdateCharacterData()
void CharacterCache::UpdateCharacterData (ObjectGuid const & guid, std::string const & name, Optional< uint8 > gender = {}, Optional< uint8 > race = {})
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
        return;
    std::string oldName = itr->second.Name;
    itr->second.Name = name;
    if (gender)
    {
        itr->second.Sex = *gender;
    }
    if (race)
    {
        itr->second.Race = *race;
    }
    //WorldPackets::Misc::InvalidatePlayer packet(guid);
    //sWorld->SendGlobalMessage(packet.Write());
    // Correct name -> pointer storage
    _characterCacheByNameStore.erase(oldName);
    _characterCacheByNameStore[name] = &itr->second;
}
UpdateCharacterGroup()
void CharacterCache::UpdateCharacterGroup (ObjectGuid const & guid, ObjectGuid groupGUID)
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return;
    }
    itr->second.GroupGuid = groupGUID;
}
UpdateCharacterGuildId()
void CharacterCache::UpdateCharacterGuildId (ObjectGuid const & guid, ObjectGuid::LowType guildId)
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return;
    }
    itr->second.GuildId = guildId;
}
UpdateCharacterLevel()
void CharacterCache::UpdateCharacterLevel (ObjectGuid const & guid, uint8 level)
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return;
    }
    itr->second.Level = level;
}
UpdateCharacterMailCount()
void CharacterCache::UpdateCharacterMailCount (ObjectGuid const & guid, int8 count, bool update = false)
{
    auto itr = _characterCacheStore.find(guid);
    if (itr == _characterCacheStore.end())
    {
        return;
    }
    if (update)
    {
        itr->second.MailCount = count;
        return;
    }
    // Let's be safe and prevent overflow
    if (!itr->second.MailCount && count < 0)
    {
        return;
    }
    itr->second.MailCount += count;
}
Referenced by LoadCharacterCacheStorage(), and RefreshCacheEntry().