AzerothCore: NonTankLKTargetSelector Struct Reference
NonTankLKTargetSelector Struct Reference
Public Member Functions
NonTankLKTargetSelector (Creature *source, bool playerOnly=true, bool reqLOS=false, float maxDist=0.0f, uint32 exclude1=0, uint32 exclude2=0)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
bool _playerOnly
bool _reqLOS
float _maxDist
uint32 _exclude1
uint32 _exclude2
Detailed Description
Constructor & Destructor Documentation
NonTankLKTargetSelector()
NonTankLKTargetSelector::NonTankLKTargetSelector (Creature * source, bool playerOnly = true, bool reqLOS = false, float maxDist = 0.0f, uint32 exclude1 = 0, uint32 exclude2 = 0) inline
: _source(source), _playerOnly(playerOnly), _reqLOS(reqLOS), _maxDist(maxDist), _exclude1(exclude1), _exclude2(exclude2) { }
Member Function Documentation
operator()()
bool NonTankLKTargetSelector::operator() (Unit const * target) const inline
    {
        if (!target)
            return false;
        if (!target->IsAlive())
            return false;
        if (_playerOnly && target->GetTypeId() != TYPEID_PLAYER)
            return false;
        if (target == _source->GetVictim())
            return false;
        if (target->HasAura(SPELL_BOSS_HITTIN_YA_AURA))
            return false;
        if (_maxDist && _source->GetExactDist(target) > _maxDist)
            return false;
        if ((_exclude1 && target->HasAura(_exclude1)) || (_exclude2 && target->HasAura(_exclude2)))
            return false;
        if (_reqLOS && !_source->IsWithinLOSInMap(target))
            return false;
        return true;
    }
References _exclude1, _exclude2, _maxDist, _playerOnly, _reqLOS, _source, Position::GetExactDist(), Object::GetTypeId(), Unit::GetVictim(), Unit::HasAura(), Unit::IsAlive(), WorldObject::IsWithinLOSInMap(), SPELL_BOSS_HITTIN_YA_AURA, and TYPEID_PLAYER.
Member Data Documentation
_exclude1
uint32 NonTankLKTargetSelector::_exclude1 private
Referenced by operator()().
_exclude2
uint32 NonTankLKTargetSelector::_exclude2 private
Referenced by operator()().
_maxDist
float NonTankLKTargetSelector::_maxDist private
Referenced by operator()().
_playerOnly
bool NonTankLKTargetSelector::_playerOnly private
Referenced by operator()().
_reqLOS
bool NonTankLKTargetSelector::_reqLOS private
Referenced by operator()().
_source
Creature const* NonTankLKTargetSelector::_source private
Referenced by operator()().