AzerothCore: spell_sha_feral_spirit_scaling Class Reference
spell_sha_feral_spirit_scaling Class Reference
Private Member Functions
PrepareAuraScript (spell_sha_feral_spirit_scaling)
void CalculateResistanceAmount (AuraEffect const *aurEff, int32 &amount, bool &)
void CalculateStatAmount (AuraEffect const *aurEff, int32 &amount, bool &)
void CalculateAPAmount (AuraEffect const *, int32 &amount, bool &)
void CalculateSPAmount (AuraEffect const *, int32 &amount, bool &)
void HandleEffectApply (AuraEffect const *aurEff, AuraEffectHandleModes)
void CalcPeriodic (AuraEffect const *, bool &isPeriodic, int32 &amplitude)
void HandlePeriodic (AuraEffect const *aurEff)
void Register () override
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
CalcPeriodic()
void spell_sha_feral_spirit_scaling::CalcPeriodic (AuraEffect const * , bool & isPeriodic, int32 & amplitude) inline private
    {
        isPeriodic = true;
        amplitude = 1 * IN_MILLISECONDS;
    }
References IN_MILLISECONDS.
Referenced by Register().
CalculateAPAmount()
void spell_sha_feral_spirit_scaling::CalculateAPAmount (AuraEffect const * , int32 & amount, bool &) inline private
    {
        // xinef: by default feral spirit inherits 30% of AP
        if (Unit* owner = GetUnitOwner()->GetOwner())
        {
            int32 modifier = 30;
            if (AuraEffect const* gofsEff = owner->GetAuraEffect(SPELL_SHAMAN_GLYPH_OF_FERAL_SPIRIT, EFFECT_0))
                modifier += gofsEff->GetAmount();
            amount = CalculatePct(std::max<int32>(0, owner->GetTotalAttackPowerValue(BASE_ATTACK)), modifier);
        }
    }
References BASE_ATTACK, CalculatePct(), EFFECT_0, AuraScript::GetOwner(), AuraScript::GetUnitOwner(), and SPELL_SHAMAN_GLYPH_OF_FERAL_SPIRIT.
Referenced by Register().
CalculateResistanceAmount()
void spell_sha_feral_spirit_scaling::CalculateResistanceAmount (AuraEffect const * aurEff, int32 & amount, bool &) inline private
    {
        // xinef: feral spirit inherits 40% of resistance from owner and 35% of armor
        if (Unit* owner = GetUnitOwner()->GetOwner())
        {
            SpellSchoolMask schoolMask = SpellSchoolMask(aurEff->GetSpellInfo()->Effects[aurEff->GetEffIndex()].MiscValue);
            int32 modifier = schoolMask == SPELL_SCHOOL_MASK_NORMAL ? 35 : 40;
            amount = CalculatePct(std::max<int32>(0, owner->GetResistance(schoolMask)), modifier);
        }
    }
References CalculatePct(), SpellInfo::Effects, AuraEffect::GetEffIndex(), AuraScript::GetOwner(), AuraEffect::GetSpellInfo(), AuraScript::GetUnitOwner(), and SPELL_SCHOOL_MASK_NORMAL.
Referenced by Register().
CalculateSPAmount()
void spell_sha_feral_spirit_scaling::CalculateSPAmount (AuraEffect const * , int32 & amount, bool &) inline private
    {
        // xinef: by default feral spirit inherits 30% of AP as SP
        if (Unit* owner = GetUnitOwner()->GetOwner())
        {
            int32 modifier = 30;
            if (AuraEffect const* gofsEff = owner->GetAuraEffect(SPELL_SHAMAN_GLYPH_OF_FERAL_SPIRIT, EFFECT_0))
                modifier += gofsEff->GetAmount();
            amount = CalculatePct(std::max<int32>(0, owner->GetTotalAttackPowerValue(BASE_ATTACK)), modifier);
            // xinef: Update appropriate player field
            if (owner->IsPlayer())
                owner->SetUInt32Value(PLAYER_PET_SPELL_POWER, (uint32)amount);
        }
    }
References BASE_ATTACK, CalculatePct(), EFFECT_0, AuraScript::GetOwner(), AuraScript::GetUnitOwner(), PLAYER_PET_SPELL_POWER, and SPELL_SHAMAN_GLYPH_OF_FERAL_SPIRIT.
Referenced by Register().
CalculateStatAmount()
void spell_sha_feral_spirit_scaling::CalculateStatAmount (AuraEffect const * aurEff, int32 & amount, bool &) inline private
    {
        // xinef: by default feral spirit inherits 30% of stamina
        if (Unit* owner = GetUnitOwner()->GetOwner())
        {
            Stats stat = Stats(aurEff->GetSpellInfo()->Effects[aurEff->GetEffIndex()].MiscValue);
            amount = CalculatePct(std::max<int32>(0, owner->GetStat(stat)), 30);
        }
    }
References CalculatePct(), SpellInfo::Effects, AuraEffect::GetEffIndex(), AuraScript::GetOwner(), AuraEffect::GetSpellInfo(), and AuraScript::GetUnitOwner().
Referenced by Register().
HandleEffectApply()
void spell_sha_feral_spirit_scaling::HandleEffectApply (AuraEffect const * aurEff, AuraEffectHandleModes) inline private
    {
        GetUnitOwner()->ApplySpellImmune(0, IMMUNITY_STATE, aurEff->GetAuraType(), true, SPELL_BLOCK_TYPE_POSITIVE);
        if (aurEff->GetAuraType() == SPELL_AURA_MOD_ATTACK_POWER)
            GetUnitOwner()->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_ATTACK_POWER_PCT, true, SPELL_BLOCK_TYPE_POSITIVE);
        else if (aurEff->GetAuraType() == SPELL_AURA_MOD_STAT)
            GetUnitOwner()->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, true, SPELL_BLOCK_TYPE_POSITIVE);
    }
References Unit::ApplySpellImmune(), AuraEffect::GetAuraType(), AuraScript::GetUnitOwner(), IMMUNITY_STATE, SPELL_AURA_MOD_ATTACK_POWER, SPELL_AURA_MOD_ATTACK_POWER_PCT, SPELL_AURA_MOD_STAT, SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, and SPELL_BLOCK_TYPE_POSITIVE.
Referenced by Register().
HandlePeriodic()
void spell_sha_feral_spirit_scaling::HandlePeriodic (AuraEffect const * aurEff) inline private
    {
        PreventDefaultAction();
        if (aurEff->GetAuraType() == SPELL_AURA_MOD_STAT && (aurEff->GetMiscValue() == STAT_STAMINA || aurEff->GetMiscValue() == STAT_INTELLECT))
        {
            int32 currentAmount = aurEff->GetAmount();
            int32 newAmount = GetEffect(aurEff->GetEffIndex())->CalculateAmount(GetCaster());
            if (newAmount != currentAmount)
            {
                if (aurEff->GetMiscValue() == STAT_STAMINA)
                {
                    uint32 actStat = GetUnitOwner()->GetHealth();
                    GetEffect(aurEff->GetEffIndex())->ChangeAmount(newAmount, false);
                    GetUnitOwner()->SetHealth(std::min<uint32>(GetUnitOwner()->GetMaxHealth(), actStat));
                }
                else
                {
                    uint32 actStat = GetUnitOwner()->GetPower(POWER_MANA);
                    GetEffect(aurEff->GetEffIndex())->ChangeAmount(newAmount, false);
                    GetUnitOwner()->SetPower(POWER_MANA, std::min<uint32>(GetUnitOwner()->GetMaxPower(POWER_MANA), actStat));
                }
            }
        }
        else
            GetEffect(aurEff->GetEffIndex())->RecalculateAmount();
    }
References AuraEffect::CalculateAmount(), AuraEffect::ChangeAmount(), AuraEffect::GetAmount(), AuraEffect::GetAuraType(), AuraScript::GetCaster(), AuraScript::GetEffect(), AuraEffect::GetEffIndex(), Unit::GetHealth(), AuraEffect::GetMiscValue(), Unit::GetPower(), AuraScript::GetUnitOwner(), POWER_MANA, AuraScript::PreventDefaultAction(), AuraEffect::RecalculateAmount(), Unit::SetHealth(), Unit::SetPower(), SPELL_AURA_MOD_STAT, STAT_INTELLECT, and STAT_STAMINA.
Referenced by Register().
PrepareAuraScript()
spell_sha_feral_spirit_scaling::PrepareAuraScript (spell_sha_feral_spirit_scaling) private
Register()
void spell_sha_feral_spirit_scaling::Register () inline override private virtual
Implements _SpellScript.
    {
        if (m_scriptSpellId == 35675)
            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_sha_feral_spirit_scaling::CalculateResistanceAmount, EFFECT_ALL, SPELL_AURA_MOD_RESISTANCE);
        if (m_scriptSpellId == 35674)
        {
            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_sha_feral_spirit_scaling::CalculateStatAmount, EFFECT_ALL, SPELL_AURA_MOD_STAT);
            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_sha_feral_spirit_scaling::CalculateAPAmount, EFFECT_ALL, SPELL_AURA_MOD_ATTACK_POWER);
            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_sha_feral_spirit_scaling::CalculateSPAmount, EFFECT_ALL, SPELL_AURA_MOD_DAMAGE_DONE);
        }
        OnEffectApply += AuraEffectApplyFn(spell_sha_feral_spirit_scaling::HandleEffectApply, EFFECT_ALL, SPELL_AURA_ANY, AURA_EFFECT_HANDLE_REAL);
        DoEffectCalcPeriodic += AuraEffectCalcPeriodicFn(spell_sha_feral_spirit_scaling::CalcPeriodic, EFFECT_ALL, SPELL_AURA_ANY);
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_sha_feral_spirit_scaling::HandlePeriodic, EFFECT_ALL, SPELL_AURA_ANY);
    }
References AURA_EFFECT_HANDLE_REAL, AuraEffectApplyFn, AuraEffectCalcAmountFn, AuraEffectCalcPeriodicFn, AuraEffectPeriodicFn, CalcPeriodic(), CalculateAPAmount(), CalculateResistanceAmount(), CalculateSPAmount(), CalculateStatAmount(), AuraScript::DoEffectCalcAmount, AuraScript::DoEffectCalcPeriodic, EFFECT_ALL, HandleEffectApply(), HandlePeriodic(), _SpellScript::m_scriptSpellId, AuraScript::OnEffectApply, AuraScript::OnEffectPeriodic, SPELL_AURA_ANY, SPELL_AURA_MOD_ATTACK_POWER, SPELL_AURA_MOD_DAMAGE_DONE, SPELL_AURA_MOD_RESISTANCE, and SPELL_AURA_MOD_STAT.