AzerothCore: ArenaTeamMgr Class Reference
ArenaTeamMgr Class Reference
#include "ArenaTeamMgr.h"
Public Types
typedef std::unordered_map< uint32, ArenaTeam * > ArenaTeamContainer
Public Member Functions
ArenaTeam * GetArenaTeamById (uint32 arenaTeamId) const
ArenaTeam * GetArenaTeamByName (std::string const &arenaTeamName) const
ArenaTeam * GetArenaTeamByCaptain (ObjectGuid guid) const
ArenaTeam * GetArenaTeamByName (std::string const &arenaTeamName, const uint32 type) const
ArenaTeam * GetArenaTeamByCaptain (ObjectGuid guid, const uint32 type) const
void LoadArenaTeams ()
void AddArenaTeam (ArenaTeam *arenaTeam)
void RemoveArenaTeam (uint32 Id)
ArenaTeamContainer::iterator GetArenaTeamMapBegin ()
ArenaTeamContainer::iterator GetArenaTeamMapEnd ()
ArenaTeamContainer & GetArenaTeams ()
void DistributeArenaPoints ()
uint32 GenerateArenaTeamId ()
void SetNextArenaTeamId (uint32 Id)
uint32 GetNextArenaLogId ()
void SetLastArenaLogId (uint32 id)
uint32 GenerateTempArenaTeamId ()
Static Public Member Functions
static ArenaTeamMgr * instance ()
Protected Attributes
uint32 NextArenaTeamId
uint32 NextTempArenaTeamId
ArenaTeamContainer ArenaTeamStore
uint32 LastArenaLogId
Private Member Functions
ArenaTeamMgr ()
~ArenaTeamMgr ()
Detailed Description
Member Typedef Documentation
ArenaTeamContainer
typedef std::unordered_map<uint32, ArenaTeam*> ArenaTeamMgr::ArenaTeamContainer
Constructor & Destructor Documentation
ArenaTeamMgr()
ArenaTeamMgr::ArenaTeamMgr () private
{
    NextArenaTeamId = 1;
    LastArenaLogId = 0;
    NextTempArenaTeamId = 0xFFF00000;
}
References LastArenaLogId, NextArenaTeamId, and NextTempArenaTeamId.
~ArenaTeamMgr()
ArenaTeamMgr::~ArenaTeamMgr () private
{
    for (ArenaTeamContainer::iterator itr = ArenaTeamStore.begin(); itr != ArenaTeamStore.end(); ++itr)
        delete itr->second;
}
References ArenaTeamStore.
Member Function Documentation
AddArenaTeam()
void ArenaTeamMgr::AddArenaTeam (ArenaTeam * arenaTeam)
{
    ArenaTeamStore[arenaTeam->GetId()] = arenaTeam;
}
References ArenaTeamStore, and ArenaTeam::GetId().
Referenced by LoadArenaTeams().
DistributeArenaPoints()
void ArenaTeamMgr::DistributeArenaPoints ()
{
    // Used to distribute arena points based on last week's stats
    ChatHandler(nullptr).SendWorldText(LANG_DIST_ARENA_POINTS_START);
    ChatHandler(nullptr).SendWorldText(LANG_DIST_ARENA_POINTS_ONLINE_START);
    // Temporary structure for storing maximum points to add values for all players
    std::map<ObjectGuid, uint32> PlayerPoints;
    // At first update all points for all team members
    for (ArenaTeamContainer::iterator teamItr = GetArenaTeamMapBegin(); teamItr != GetArenaTeamMapEnd(); ++teamItr)
        if (ArenaTeam* at = teamItr->second)
        {
            at->UpdateArenaPointsHelper(PlayerPoints);
            sScriptMgr->OnBeforeUpdateArenaPoints(at, PlayerPoints);
        }
    CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
    CharacterDatabasePreparedStatement* stmt;
    // Cycle that gives points to all players
    for (std::map<ObjectGuid, uint32>::iterator playerItr = PlayerPoints.begin(); playerItr != PlayerPoints.end(); ++playerItr)
    {
        // Add points to player if online
        if (Player* player = ObjectAccessor::FindPlayer(playerItr->first))
            player->ModifyArenaPoints(playerItr->second, trans);
        else    // Update database
        {
            stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_CHAR_ARENA_POINTS);
            stmt->SetData(0, playerItr->second);
            stmt->SetData(1, playerItr->first.GetCounter());
            trans->Append(stmt);
        }
    }
    CharacterDatabase.CommitTransaction(trans);
    PlayerPoints.clear();
    ChatHandler(nullptr).SendWorldText(LANG_DIST_ARENA_POINTS_ONLINE_END);
    ChatHandler(nullptr).SendWorldText(LANG_DIST_ARENA_POINTS_TEAM_START);
    for (ArenaTeamContainer::iterator titr = GetArenaTeamMapBegin(); titr != GetArenaTeamMapEnd(); ++titr)
    {
        if (ArenaTeam* at = titr->second)
        {
            if (at->FinishWeek())
                at->SaveToDB(true);
            at->NotifyStatsChanged();
        }
    }
    ChatHandler(nullptr).SendWorldText(LANG_DIST_ARENA_POINTS_TEAM_END);
    ChatHandler(nullptr).SendWorldText(LANG_DIST_ARENA_POINTS_END);
}
References CHAR_UPD_CHAR_ARENA_POINTS, CharacterDatabase, ObjectAccessor::FindPlayer(), GetArenaTeamMapBegin(), GetArenaTeamMapEnd(), LANG_DIST_ARENA_POINTS_END, LANG_DIST_ARENA_POINTS_ONLINE_END, LANG_DIST_ARENA_POINTS_ONLINE_START, LANG_DIST_ARENA_POINTS_START, LANG_DIST_ARENA_POINTS_TEAM_END, LANG_DIST_ARENA_POINTS_TEAM_START, ChatHandler::SendWorldText(), PreparedStatementBase::SetData(), and sScriptMgr.
GenerateArenaTeamId()
uint32 ArenaTeamMgr::GenerateArenaTeamId ()
{
    if (NextArenaTeamId >= MAX_ARENA_TEAM_ID)
    {
        LOG_ERROR("bg.arena", "Arena team ids overflow!! Can't continue, shutting down server. ");
        World::StopNow(ERROR_EXIT_CODE);
    }
    return NextArenaTeamId++;
}
References ERROR_EXIT_CODE, LOG_ERROR, MAX_ARENA_TEAM_ID, NextArenaTeamId, and World::StopNow().
GenerateTempArenaTeamId()
uint32 ArenaTeamMgr::GenerateTempArenaTeamId ()
{
    if (NextTempArenaTeamId >= MAX_TEMP_ARENA_TEAM_ID)
        NextTempArenaTeamId = MAX_ARENA_TEAM_ID;
    return NextTempArenaTeamId++;
}
References MAX_ARENA_TEAM_ID, MAX_TEMP_ARENA_TEAM_ID, and NextTempArenaTeamId.
GetArenaTeamByCaptain() [1/2]
ArenaTeam * ArenaTeamMgr::GetArenaTeamByCaptain (ObjectGuid guid) const
{
    for (ArenaTeamContainer::const_iterator itr = ArenaTeamStore.begin(); itr != ArenaTeamStore.end(); ++itr)
    {
        if (itr->second->GetCaptain() == guid)
        {
            return itr->second;
        }
    }
    return nullptr;
}
References ArenaTeamStore.
GetArenaTeamByCaptain() [2/2]
ArenaTeam * ArenaTeamMgr::GetArenaTeamByCaptain (ObjectGuid guid, const uint32 type) const
{
    for (ArenaTeamContainer::const_iterator itr = ArenaTeamStore.begin(); itr != ArenaTeamStore.end(); ++itr)
    {
        if (itr->second->GetCaptain() == guid && itr->second->GetType() == type)
        {
            return itr->second;
        }
    }
    return nullptr;
}
References ArenaTeamStore.
GetArenaTeamById()
ArenaTeam * ArenaTeamMgr::GetArenaTeamById (uint32 arenaTeamId) const
{
    ArenaTeamContainer::const_iterator itr = ArenaTeamStore.find(arenaTeamId);
    if (itr != ArenaTeamStore.end())
        return itr->second;
    return nullptr;
}
References ArenaTeamStore.
GetArenaTeamByName() [1/2]
ArenaTeam * ArenaTeamMgr::GetArenaTeamByName (std::string const & arenaTeamName) const
{
    std::string search = arenaTeamName;
    std::transform(search.begin(), search.end(), search.begin(), ::toupper);
    for (ArenaTeamContainer::const_iterator itr = ArenaTeamStore.begin(); itr != ArenaTeamStore.end(); ++itr)
    {
        std::string teamName = itr->second->GetName();
        std::transform(teamName.begin(), teamName.end(), teamName.begin(), ::toupper);
        if (search == teamName)
        {
            return itr->second;
        }
    }
    return nullptr;
}
References ArenaTeamStore.
GetArenaTeamByName() [2/2]
ArenaTeam * ArenaTeamMgr::GetArenaTeamByName (std::string const & arenaTeamName, const uint32 type) const
{
    std::string search = arenaTeamName;
    std::transform(search.begin(), search.end(), search.begin(), ::toupper);
    for (auto itr = ArenaTeamStore.begin(); itr != ArenaTeamStore.end(); ++itr)
    {
        if (itr->second->GetType() != type)
        {
            continue;
        }
        std::string teamName = itr->second->GetName();
        std::transform(teamName.begin(), teamName.end(), teamName.begin(), ::toupper);
        if (search == teamName)
        {
            return itr->second;
        }
    }
    return nullptr;
}
References ArenaTeamStore.
GetArenaTeamMapBegin()
ArenaTeamContainer::iterator ArenaTeamMgr::GetArenaTeamMapBegin () inline
{ return ArenaTeamStore.begin(); }
References ArenaTeamStore.
Referenced by DistributeArenaPoints().
GetArenaTeamMapEnd()
ArenaTeamContainer::iterator ArenaTeamMgr::GetArenaTeamMapEnd () inline
{ return ArenaTeamStore.end(); }
References ArenaTeamStore.
Referenced by DistributeArenaPoints().
GetArenaTeams()
ArenaTeamContainer & ArenaTeamMgr::GetArenaTeams () inline
{ return ArenaTeamStore; }
References ArenaTeamStore.
GetNextArenaLogId()
uint32 ArenaTeamMgr::GetNextArenaLogId () inline
{ return ++LastArenaLogId; }
References LastArenaLogId.
instance()
ArenaTeamMgr * ArenaTeamMgr::instance () static
{
    static ArenaTeamMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadArenaTeams()
void ArenaTeamMgr::LoadArenaTeams ()
{
    uint32 oldMSTime = getMSTime();
    // Clean out the trash before loading anything
    CharacterDatabase.Execute("DELETE FROM arena_team_member WHERE arenaTeamId NOT IN (SELECT arenaTeamId FROM arena_team)");       // One-time query
    //                                                        0        1         2         3          4              5            6            7           8
    QueryResult result = CharacterDatabase.Query("SELECT arenaTeamId, name, captainGuid, type, backgroundColor, emblemStyle, emblemColor, borderStyle, borderColor, "
                         //      9        10        11         12           13        14
                         "rating, weekGames, weekWins, seasonGames, seasonWins, `rank` FROM arena_team ORDER BY arenaTeamId ASC");
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 arena teams. DB table `arena_team` is empty!");
        LOG_INFO("server.loading", " ");
        return;
    }
    QueryResult result2 = CharacterDatabase.Query(
                              //              0              1           2             3              4                 5          6     7          8                  9      10
                              "SELECT arenaTeamId, atm.guid, atm.weekGames, atm.weekWins, atm.seasonGames, atm.seasonWins, c.name, class, personalRating, matchMakerRating, maxMMR FROM arena_team_member atm"
                              " INNER JOIN arena_team ate USING (arenaTeamId)"
                              " LEFT JOIN characters AS c ON atm.guid = c.guid"
                              " LEFT JOIN character_arena_stats AS cas ON c.guid = cas.guid AND (cas.slot = 0 AND ate.type = 2 OR cas.slot = 1 AND ate.type = 3 OR cas.slot = 2 AND ate.type = 5)"
                              " ORDER BY atm.arenateamid ASC");
    uint32 count = 0;
    do
    {
        ArenaTeam* newArenaTeam = new ArenaTeam;
        if (!newArenaTeam->LoadArenaTeamFromDB(result) || !newArenaTeam->LoadMembersFromDB(result2))
        {
            newArenaTeam->Disband(nullptr);
            delete newArenaTeam;
            continue;
        }
        AddArenaTeam(newArenaTeam);
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} arena teams in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References AddArenaTeam(), CharacterDatabase, ArenaTeam::Disband(), getMSTime(), GetMSTimeDiffToNow(), ArenaTeam::LoadArenaTeamFromDB(), ArenaTeam::LoadMembersFromDB(), LOG_INFO, and LOG_WARN.
RemoveArenaTeam()
void ArenaTeamMgr::RemoveArenaTeam (uint32 Id)
{
    ArenaTeamStore.erase(arenaTeamId);
}
References ArenaTeamStore.
SetLastArenaLogId()
void ArenaTeamMgr::SetLastArenaLogId (uint32 id) inline
{ LastArenaLogId = id; }
References LastArenaLogId.
SetNextArenaTeamId()
void ArenaTeamMgr::SetNextArenaTeamId (uint32 Id) inline
{ NextArenaTeamId = Id; }
References NextArenaTeamId.
Member Data Documentation
ArenaTeamStore
ArenaTeamContainer ArenaTeamMgr::ArenaTeamStore protected
Referenced by AddArenaTeam(), GetArenaTeamByCaptain(), GetArenaTeamById(), GetArenaTeamByName(), GetArenaTeamMapBegin(), GetArenaTeamMapEnd(), GetArenaTeams(), RemoveArenaTeam(), and ~ArenaTeamMgr().
LastArenaLogId
uint32 ArenaTeamMgr::LastArenaLogId protected
Referenced by ArenaTeamMgr(), GetNextArenaLogId(), and SetLastArenaLogId().
NextArenaTeamId
uint32 ArenaTeamMgr::NextArenaTeamId protected
Referenced by ArenaTeamMgr(), GenerateArenaTeamId(), and SetNextArenaTeamId().
NextTempArenaTeamId
uint32 ArenaTeamMgr::NextTempArenaTeamId protected
Referenced by ArenaTeamMgr(), and GenerateTempArenaTeamId().