AzerothCore: spell_gen_model_visible Class Reference
spell_gen_model_visible Class Reference
Public Member Functions
PrepareAuraScript (spell_gen_model_visible) bool Load() override
void HandleEffectApply (AuraEffect const *, AuraEffectHandleModes)
void HandleEffectRemove (AuraEffect const *, AuraEffectHandleModes)
void Register () override
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Private Attributes
std::array< uint32, 3 > _itemId = { {0, 0, 0} }
uint32 _modelId
bool _hasFlag
Additional Inherited Members
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleEffectApply()
void spell_gen_model_visible::HandleEffectApply (AuraEffect const * , AuraEffectHandleModes) inline
    {
        _modelId = GetUnitOwner()->GetDisplayId();
        _hasFlag = GetUnitOwner()->HasUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        for (uint8 i = 0; i < 3; ++i)
            _itemId.at(i) = GetUnitOwner()->GetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + i);
        GetUnitOwner()->SetDisplayId(11686);
        GetUnitOwner()->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        for (uint8 i = 0; i < 3; ++i)
            GetUnitOwner()->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + i, 0);
    }
References _hasFlag, _itemId, _modelId, Unit::GetDisplayId(), Object::GetUInt32Value(), AuraScript::GetUnitOwner(), Unit::HasUnitFlag(), Unit::SetDisplayId(), Unit::SetUInt32Value(), Unit::SetUnitFlag(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by Register().
HandleEffectRemove()
void spell_gen_model_visible::HandleEffectRemove (AuraEffect const * , AuraEffectHandleModes) inline
    {
        GetUnitOwner()->SetDisplayId(_modelId);
        if (!_hasFlag)
            GetUnitOwner()->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        for (uint8 i = 0; i < 3; ++i)
            GetUnitOwner()->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + i, _itemId.at(i));
    }
References _hasFlag, _itemId, _modelId, AuraScript::GetUnitOwner(), Unit::RemoveUnitFlag(), Unit::SetDisplayId(), Unit::SetUInt32Value(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by Register().
PrepareAuraScript()
spell_gen_model_visible::PrepareAuraScript (spell_gen_model_visible) inline override
    {
        _modelId = 0;
        _hasFlag = false;
        return true;
    }
References _hasFlag, and _modelId.
Register()
void spell_gen_model_visible::Register () inline override virtual
Implements _SpellScript.
    {
        OnEffectApply += AuraEffectApplyFn(spell_gen_model_visible::HandleEffectApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        OnEffectRemove += AuraEffectRemoveFn(spell_gen_model_visible::HandleEffectRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
References AURA_EFFECT_HANDLE_REAL, AuraEffectApplyFn, AuraEffectRemoveFn, EFFECT_0, HandleEffectApply(), HandleEffectRemove(), AuraScript::OnEffectApply, AuraScript::OnEffectRemove, and SPELL_AURA_DUMMY.
Member Data Documentation
_hasFlag
bool spell_gen_model_visible::_hasFlag private
Referenced by HandleEffectApply(), HandleEffectRemove(), and PrepareAuraScript().
_itemId
std::array<uint32, 3> spell_gen_model_visible::_itemId = { {0, 0, 0} } private
Referenced by HandleEffectApply(), and HandleEffectRemove().
_modelId
uint32 spell_gen_model_visible::_modelId private
Referenced by HandleEffectApply(), HandleEffectRemove(), and PrepareAuraScript().