AzerothCore: boss_ossirian Struct Reference
boss_ossirian Struct Reference
Public Member Functions
boss_ossirian (Creature *creature)
void InitializeAI () override
void Reset () override
void JustSummoned (Creature *creature) override
void SpellHit (Unit *, SpellInfo const *spell) override
void SetGUID (ObjectGuid guid, int32 action) override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void SummonedCreatureDespawn (Creature *summon) override
void KilledUnit (Unit *) override
void SpawnNextCrystal (uint8 count=1)
void MoveInLineOfSight (Unit *who) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Protected Attributes
uint8 _crystalIterator
ObjectGuid _firstCrystalGUID
bool _saidIntro
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Detailed Description
Constructor & Destructor Documentation
boss_ossirian()
boss_ossirian::boss_ossirian (Creature * creature) inline
                                      : BossAI(creature, DATA_OSSIRIAN)
    {
        _saidIntro = false;
    }
References _saidIntro.
Member Function Documentation
InitializeAI()
void boss_ossirian::InitializeAI () inline override virtual
Reimplemented from UnitAI.
    {
        Reset();
    }
References Reset().
JustEngagedWith()
void boss_ossirian::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        BossAI::JustEngagedWith(who);
        events.Reset();
        events.ScheduleEvent(EVENT_SPEEDUP, 10s);
        events.ScheduleEvent(EVENT_SILENCE, 30s);
        events.ScheduleEvent(EVENT_CYCLONE, 20s);
        events.ScheduleEvent(EVENT_STOMP, 30s);
        DoCastSelf(SPELL_STRENGTH_OF_OSSIRIAN);
        Talk(SAY_AGGRO);
        Map* map = me->GetMap();
        if (!map->IsDungeon())
            return;
        WorldPackets::Misc::Weather weather(WEATHER_STATE_HEAVY_SANDSTORM, 1.0f);
        map->SendToPlayers(weather.Write());
        SpawnNextCrystal(3);
        std::list<uint32> pathIds = { 1446800, 1446790 };
        for (Position pos : VortexPositions)
        {
            if (Creature* vortex = me->SummonCreature(NPC_SAND_VORTEX, pos))
            {
                vortex->GetMotionMaster()->MovePath(pathIds.front(), true);
                pathIds.reverse();
            }
        }
    }
References UnitAI::DoCastSelf(), EVENT_CYCLONE, EVENT_SILENCE, EVENT_SPEEDUP, EVENT_STOMP, WorldObject::GetMap(), Map::IsDungeon(), BossAI::JustEngagedWith(), ScriptedAI::me, NPC_SAND_VORTEX, SAY_AGGRO, Map::SendToPlayers(), SpawnNextCrystal(), SPELL_STRENGTH_OF_OSSIRIAN, WorldObject::SummonCreature(), VortexPositions, WEATHER_STATE_HEAVY_SANDSTORM, and WorldPackets::Misc::Weather::Write().
JustSummoned()
void boss_ossirian::JustSummoned (Creature * creature) inline override virtual
Reimplemented from BossAI.
    {
        summons.Summon(creature);
    }
References SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_ossirian::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        Talk(SAY_SLAY);
    }
References SAY_SLAY.
MoveInLineOfSight()
void boss_ossirian::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
    {
        if (!_saidIntro)
        {
            Talk(SAY_INTRO);
            _saidIntro = true;
        }
        BossAI::MoveInLineOfSight(who);
    }
References _saidIntro, CreatureAI::MoveInLineOfSight(), and SAY_INTRO.
Reset()
void boss_ossirian::Reset () inline override virtual
Reimplemented from BossAI.
    {
        BossAI::Reset();
        _crystalIterator = urand(1, NUM_CRYSTALS - 1);
        if (!ObjectAccessor::GetGameObject(*me, _firstCrystalGUID))
        {
            if (Creature* trigger = me->GetMap()->SummonCreature(NPC_OSSIRIAN_TRIGGER, CrystalCoordinates[0]))
            {
                if (GameObject* crystal = me->SummonGameObject(GO_OSSIRIAN_CRYSTAL,
                    CrystalCoordinates[0].GetPositionX(),
                    CrystalCoordinates[0].GetPositionY(),
                    CrystalCoordinates[0].GetPositionZ(),
                    0, 0, 0, 0, 0, uint32(-1)))
                {
                    _firstCrystalGUID = crystal->GetGUID();
                    crystal->SetOwnerGUID(ObjectGuid::Empty);
                    crystal->RemoveGameObjectFlag(GO_FLAG_IN_USE);
                    crystal->AI()->SetGUID(trigger->GetGUID(), GUID_TRIGGER_PAIR);
                }
            }
        }
    }
References _crystalIterator, _firstCrystalGUID, CrystalCoordinates, ObjectGuid::Empty, ObjectAccessor::GetGameObject(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_FLAG_IN_USE, GO_OSSIRIAN_CRYSTAL, GUID_TRIGGER_PAIR, ScriptedAI::me, NPC_OSSIRIAN_TRIGGER, NUM_CRYSTALS, BossAI::Reset(), Map::SummonCreature(), WorldObject::SummonGameObject(), and urand().
Referenced by InitializeAI().
SetGUID()
void boss_ossirian::SetGUID (ObjectGuid guid, int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        if (action == ACTION_TRIGGER_WEAKNESS && guid != _firstCrystalGUID)
        {
            SpawnNextCrystal();
        }
    }
References _firstCrystalGUID, ACTION_TRIGGER_WEAKNESS, and SpawnNextCrystal().
SpawnNextCrystal()
void boss_ossirian::SpawnNextCrystal (uint8 count = 1) inline
    {
        for (uint8 i = 0; i < count; ++i)
        {
            if (_crystalIterator == NUM_CRYSTALS)
                _crystalIterator = 1;
            if (Creature* trigger = me->SummonCreature(NPC_OSSIRIAN_TRIGGER, CrystalCoordinates[_crystalIterator]))
            {
                if (GameObject* crystal = trigger->SummonGameObject(GO_OSSIRIAN_CRYSTAL,
                    CrystalCoordinates[_crystalIterator].GetPositionX(),
                    CrystalCoordinates[_crystalIterator].GetPositionY(),
                    CrystalCoordinates[_crystalIterator].GetPositionZ(),
                    0, 0, 0, 0, 0, uint32(-1)))
                {
                    ++_crystalIterator;
                    crystal->SetOwnerGUID(ObjectGuid::Empty);
                    crystal->RemoveGameObjectFlag(GO_FLAG_IN_USE);
                    crystal->AI()->SetGUID(trigger->GetGUID(), GUID_TRIGGER_PAIR);
                }
            }
        }
    }
References _crystalIterator, CrystalCoordinates, ObjectGuid::Empty, Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_FLAG_IN_USE, GO_OSSIRIAN_CRYSTAL, GUID_TRIGGER_PAIR, ScriptedAI::me, NPC_OSSIRIAN_TRIGGER, NUM_CRYSTALS, WorldObject::SummonCreature(), and WorldObject::SummonGameObject().
Referenced by JustEngagedWith(), and SetGUID().
SpellHit()
void boss_ossirian::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
    {
        for (uint32 weakness : spellWeakness)
        {
            if (spell->Id == weakness)
            {
                me->RemoveAurasDueToSpell(SPELL_STRENGTH_OF_OSSIRIAN);
            }
        }
    }
References SpellInfo::Id, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SPELL_STRENGTH_OF_OSSIRIAN, and spellWeakness.
SummonedCreatureDespawn()
void boss_ossirian::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from BossAI.
    {
        summons.Despawn(summon);
        if (summon->GetEntry() == NPC_OSSIRIAN_TRIGGER)
        {
            if (GameObject* crystal = GetClosestGameObjectWithEntry(summon, GO_OSSIRIAN_CRYSTAL, 5.0f))
            {
                crystal->Delete();
            }
        }
    }
References SummonList::Despawn(), GetClosestGameObjectWithEntry(), Object::GetEntry(), GO_OSSIRIAN_CRYSTAL, NPC_OSSIRIAN_TRIGGER, and BossAI::summons.
UpdateAI()
void boss_ossirian::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
    {
        if (!UpdateVictim())
            return;
        events.Update(diff);
        bool applySupreme = true;
        if (me->HasAura(SPELL_STRENGTH_OF_OSSIRIAN))
        {
            applySupreme = false;
        }
        else
        {
            for (uint32 weakness : spellWeakness)
            {
                if (me->HasAura(weakness))
                {
                    applySupreme = false;
                    break;
                }
            }
        }
        if (applySupreme)
        {
            DoCastSelf(SPELL_STRENGTH_OF_OSSIRIAN);
            Talk(SAY_SUPREME);
        }
        while (uint32 eventId = events.ExecuteEvent())
        {
            switch (eventId)
            {
                case EVENT_SPEEDUP:
                    DoCastSelf(SPELL_SPEED_BURST);
                    break;
                case EVENT_SILENCE:
                    DoCastAOE(SPELL_CURSE_OF_TONGUES);
                    events.ScheduleEvent(EVENT_SILENCE, 20s, 30s);
                    break;
                case EVENT_CYCLONE:
                    DoCastVictim(SPELL_ENVELOPING_WINDS);
                    events.ScheduleEvent(EVENT_CYCLONE, 20s);
                    break;
                case EVENT_STOMP:
                    DoCastAOE(SPELL_WAR_STOMP);
                    events.ScheduleEvent(EVENT_STOMP, 30s);
                    break;
                default:
                    break;
            }
        }
        DoMeleeAttackIfReady();
    }
References UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EVENT_CYCLONE, EVENT_SILENCE, EVENT_SPEEDUP, EVENT_STOMP, Unit::HasAura(), ScriptedAI::me, SAY_SUPREME, SPELL_CURSE_OF_TONGUES, SPELL_ENVELOPING_WINDS, SPELL_SPEED_BURST, SPELL_STRENGTH_OF_OSSIRIAN, SPELL_WAR_STOMP, spellWeakness, and CreatureAI::UpdateVictim().
Member Data Documentation
_crystalIterator
uint8 boss_ossirian::_crystalIterator protected
Referenced by Reset(), and SpawnNextCrystal().
_firstCrystalGUID
ObjectGuid boss_ossirian::_firstCrystalGUID protected
Referenced by Reset(), and SetGUID().
_saidIntro
bool boss_ossirian::_saidIntro protected
Referenced by boss_ossirian(), and MoveInLineOfSight().