AzerothCore: boss_thorim_arena_npcs::boss_thorim_arena_npcsAI Struct Reference
boss_thorim_arena_npcs::boss_thorim_arena_npcsAI Struct Reference
Public Member Functions
boss_thorim_arena_npcsAI (Creature *pCreature)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
bool CanAIAttack (Unit const *target) const override
bool SelectT ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
bool _isCaster
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_thorim_arena_npcsAI()
boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::boss_thorim_arena_npcsAI (Creature * pCreature) inline
: ScriptedAI(pCreature) { }
Member Function Documentation
CanAIAttack()
bool boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
        {
            return target->GetPositionX() < 2180 && target->GetPositionZ() < 425;
        }
References Position::GetPositionX(), and Position::GetPositionZ().
JustEngagedWith()
void boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            if (me->GetEntry() == NPC_DARK_RUNE_WARBRINGER)
            {
                events.ScheduleEvent(EVENT_DR_WARBRINGER_RS, 8s);
            }
            else if (me->GetEntry() == NPC_DARK_RUNE_EVOKER)
            {
                events.ScheduleEvent(EVENT_DR_EVOKER_RL, 2500ms);
                events.ScheduleEvent(EVENT_DR_EVOKER_RM, 4s);
                events.ScheduleEvent(EVENT_DR_EVOKER_RS, 10s);
            }
            else if (me->GetEntry() == NPC_DARK_RUNE_CHAMPION)
            {
                events.ScheduleEvent(EVENT_DR_CHAMPION_WH, 6s);
                events.ScheduleEvent(EVENT_DR_CHAMPION_CH, 12s);
                events.ScheduleEvent(EVENT_DR_CHAMPION_MS, 8s);
            }
            else if (me->GetEntry() == NPC_DARK_RUNE_COMMONER)
            {
                events.ScheduleEvent(EVENT_DR_COMMONER_LB, 5s);
                events.ScheduleEvent(EVENT_DR_COMMONER_PM, 6s);
            }
        }
References EVENT_DR_CHAMPION_CH, EVENT_DR_CHAMPION_MS, EVENT_DR_CHAMPION_WH, EVENT_DR_COMMONER_LB, EVENT_DR_COMMONER_PM, EVENT_DR_EVOKER_RL, EVENT_DR_EVOKER_RM, EVENT_DR_EVOKER_RS, EVENT_DR_WARBRINGER_RS, Object::GetEntry(), ScriptedAI::me, NPC_DARK_RUNE_CHAMPION, NPC_DARK_RUNE_COMMONER, NPC_DARK_RUNE_EVOKER, and NPC_DARK_RUNE_WARBRINGER.
Reset()
void boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _isCaster = (me->GetEntry() == NPC_DARK_RUNE_EVOKER);
            events.Reset();
            if (me->GetEntry() == NPC_DARK_RUNE_WARBRINGER)
                me->CastSpell(me, SPELL_AURA_OF_CELERITY, true);
        }
References _isCaster, Unit::CastSpell(), Object::GetEntry(), ScriptedAI::me, NPC_DARK_RUNE_EVOKER, NPC_DARK_RUNE_WARBRINGER, and SPELL_AURA_OF_CELERITY.
SelectT()
bool boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT () inline
        {
            Player* target = nullptr;
            Map::PlayerList const& pList = me->GetMap()->GetPlayers();
            uint8 num = urand(0, pList.getSize() - 1);
            uint8 count = 0;
            for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr, ++count)
            {
                if (itr->GetSource()->GetPositionX() > 2180 || !itr->GetSource()->IsAlive() || itr->GetSource()->GetPositionZ() > 425)
                    continue;
                if (count <= num || !target)
                    target = itr->GetSource();
                else
                    break;
            }
            if (target)
            {
                AttackStart(target);
                me->AddThreat(target, 500.0f);
                if (me->GetEntry() == NPC_DARK_RUNE_EVOKER && urand(0, 1))
                    me->CastSpell(me, SPELL_RUNIC_SHIELD, false);
                else if (me->GetEntry() == NPC_DARK_RUNE_CHAMPION && !urand(0, 2))
                    me->CastSpell(target, SPELL_CHARGE, false);
                return true;
            }
            return false;
        }
References Unit::AddThreat(), ScriptedAI::AttackStart(), MapRefMgr::begin(), Unit::CastSpell(), MapRefMgr::end(), Object::GetEntry(), WorldObject::GetMap(), Map::GetPlayers(), LinkedListHead::getSize(), ScriptedAI::me, NPC_DARK_RUNE_CHAMPION, NPC_DARK_RUNE_EVOKER, SPELL_CHARGE, SPELL_RUNIC_SHIELD, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim() && !SelectT())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_DR_WARBRINGER_RS:
                    me->CastSpell(me->GetVictim(), SPELL_RUNIC_STRIKE, false);
                    events.Repeat(8s);
                    break;
                case EVENT_DR_EVOKER_RL:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
                        me->CastSpell(target, SPELL_RUNIC_LIGHTNING, false);
                    events.Repeat(2500ms);
                    break;
                case EVENT_DR_EVOKER_RM:
                    if (Unit* target = DoSelectLowestHpFriendly(40.0f, 15))
                        me->CastSpell(target, SPELL_RUNIC_MENDING, false);
                    else
                        me->CastSpell(me, SPELL_RUNIC_MENDING, false);
                    events.Repeat(4s);
                    break;
                case EVENT_DR_EVOKER_RS:
                    me->CastSpell(me, SPELL_RUNIC_SHIELD, false);
                    events.Repeat(10s);
                    break;
                case EVENT_DR_CHAMPION_CH:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
                        me->CastSpell(target, SPELL_CHARGE, false);
                    events.Repeat(12s);
                    break;
                case EVENT_DR_CHAMPION_WH:
                    if (!me->HasUnitFlag(UNIT_FLAG_DISARMED))
                        me->CastSpell(me, SPELL_WHIRLWIND, false);
                    events.Repeat(6s);
                    break;
                case EVENT_DR_CHAMPION_MS:
                    me->CastSpell(me->GetVictim(), SPELL_MORTAL_STRIKE, false);
                    events.Repeat(8s);
                    break;
                case EVENT_DR_COMMONER_LB:
                    me->CastSpell(me->GetVictim(), SPELL_LOW_BLOW, false);
                    events.Repeat(5s);
                    break;
                case EVENT_DR_COMMONER_PM:
                    me->CastSpell(me->GetVictim(), SPELL_PUMMEL, false);
                    events.Repeat(6s);
                    break;
            }
            if (!_isCaster || (me->GetPower(POWER_MANA) * 100 / me->GetMaxPower(POWER_MANA) < 10))
                DoMeleeAttackIfReady();
        }
References _isCaster, Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoSelectLowestHpFriendly(), EVENT_DR_CHAMPION_CH, EVENT_DR_CHAMPION_MS, EVENT_DR_CHAMPION_WH, EVENT_DR_COMMONER_LB, EVENT_DR_COMMONER_PM, EVENT_DR_EVOKER_RL, EVENT_DR_EVOKER_RM, EVENT_DR_EVOKER_RS, EVENT_DR_WARBRINGER_RS, Unit::GetMaxPower(), Unit::GetPower(), Unit::GetVictim(), Unit::HasUnitFlag(), Unit::HasUnitState(), ScriptedAI::me, POWER_MANA, SelectT(), UnitAI::SelectTarget(), SPELL_CHARGE, SPELL_LOW_BLOW, SPELL_MORTAL_STRIKE, SPELL_PUMMEL, SPELL_RUNIC_LIGHTNING, SPELL_RUNIC_MENDING, SPELL_RUNIC_SHIELD, SPELL_RUNIC_STRIKE, SPELL_WHIRLWIND, UNIT_FLAG_DISARMED, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_isCaster
bool boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::_isCaster
Referenced by Reset(), and UpdateAI().
events
EventMap boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::events