AzerothCore: Acore::Crypto Namespace Reference
Acore::Crypto Namespace Reference
Classes
class AES
class ARC4
struct Argon2
struct Constants
class SRP6
struct TOTP
Typedefs
using MD5 = Acore::Impl::GenericHash< EVP_md5, Constants::MD5_DIGEST_LENGTH_BYTES >
using SHA1 = Acore::Impl::GenericHash< EVP_sha1, Constants::SHA1_DIGEST_LENGTH_BYTES >
using SHA256 = Acore::Impl::GenericHash< EVP_sha256, Constants::SHA256_DIGEST_LENGTH_BYTES >
using HMAC_SHA1 = Acore::Impl::GenericHMAC< EVP_sha1, Constants::SHA1_DIGEST_LENGTH_BYTES >
using HMAC_SHA256 = Acore::Impl::GenericHMAC< EVP_sha256, Constants::SHA256_DIGEST_LENGTH_BYTES >
Functions
template<typename Cipher >
void AEEncryptWithRandomIV (std::vector< uint8 > &data, typename Cipher::Key const &key)
template<typename Cipher >
void AEEncryptWithRandomIV (std::vector< uint8 > &data, BigNumber const &key)
template<typename Cipher >
bool AEDecrypt (std::vector< uint8 > &data, typename Cipher::Key const &key)
template<typename Cipher >
bool AEDecrypt (std::vector< uint8 > &data, BigNumber const &key)
AC_COMMON_API void GetRandomBytes (uint8 *buf, std::size_t len)
template<typename Container >
void GetRandomBytes (Container &c)
template<std::size_t S>
std::array< uint8, S > GetRandomBytes ()
Typedef Documentation
HMAC_SHA1
using Acore::Crypto::HMAC_SHA1 = typedef Acore::Impl::GenericHMAC<EVP_sha1, Constants::SHA1_DIGEST_LENGTH_BYTES>
HMAC_SHA256
using Acore::Crypto::HMAC_SHA256 = typedef Acore::Impl::GenericHMAC<EVP_sha256, Constants::SHA256_DIGEST_LENGTH_BYTES>
MD5
using Acore::Crypto::MD5 = typedef Acore::Impl::GenericHash<EVP_md5, Constants::MD5_DIGEST_LENGTH_BYTES>
SHA1
using Acore::Crypto::SHA1 = typedef Acore::Impl::GenericHash<EVP_sha1, Constants::SHA1_DIGEST_LENGTH_BYTES>
SHA256
using Acore::Crypto::SHA256 = typedef Acore::Impl::GenericHash<EVP_sha256, Constants::SHA256_DIGEST_LENGTH_BYTES>
Function Documentation
AEDecrypt() [1/2]
template<typename Cipher > bool Acore::Crypto::AEDecrypt (std::vector< uint8 > & data, BigNumber const & key)
    {
        return AEDecrypt<Cipher>(data, key.ToByteArray<Cipher::KEY_SIZE_BYTES>());
    }
References BigNumber::ToByteArray().
AEDecrypt() [2/2]
template<typename Cipher > bool Acore::Crypto::AEDecrypt (std::vector< uint8 > & data, typename Cipher::Key const & key)
    {
        using IV = typename Cipher::IV;
        using Tag = typename Cipher::Tag;
        // extract trailing IV and tag
        IV iv;
        Tag tag;
        Acore::Impl::CryptoGenericsImpl::SplitFromBack(data, tag);
        Acore::Impl::CryptoGenericsImpl::SplitFromBack(data, iv);
        // decrypt data
        Cipher cipher(false);
        cipher.Init(key);
        return cipher.Process(iv, data.data(), data.size(), tag);
    }
References Acore::Impl::CryptoGenericsImpl::SplitFromBack().
AEEncryptWithRandomIV() [1/2]
template<typename Cipher > void Acore::Crypto::AEEncryptWithRandomIV (std::vector< uint8 > & data, BigNumber const & key)
    {
        AEEncryptWithRandomIV<Cipher>(data, key.ToByteArray<Cipher::KEY_SIZE_BYTES>());
    }
References BigNumber::ToByteArray().
AEEncryptWithRandomIV() [2/2]
template<typename Cipher > void Acore::Crypto::AEEncryptWithRandomIV (std::vector< uint8 > & data, typename Cipher::Key const & key)
    {
        using IV = typename Cipher::IV;
        using Tag = typename Cipher::Tag;
        // select random IV
        IV iv = Acore::Impl::CryptoGenericsImpl::GenerateRandomIV<Cipher>();
        Tag tag;
        // encrypt data
        Cipher cipher(true);
        cipher.Init(key);
        bool success = cipher.Process(iv, data.data(), data.size(), tag);
        ASSERT(success);
        // append trailing IV and tag
        Acore::Impl::CryptoGenericsImpl::AppendToBack(data, iv);
        Acore::Impl::CryptoGenericsImpl::AppendToBack(data, tag);
    }
References Acore::Impl::CryptoGenericsImpl::AppendToBack(), and ASSERT.
GetRandomBytes() [1/3]
template<std::size_t S> std::array< uint8, S > Acore::Crypto::GetRandomBytes ()
    {
        std::array<uint8, S> arr;
        GetRandomBytes(arr);
        return arr;
    }
References GetRandomBytes().
Referenced by Acore::Impl::CryptoGenericsImpl::GenerateRandomIV(), GetRandomBytes(), account_commandscript::HandleAccount2FASetupCommand(), Acore::Crypto::SRP6::MakeRegistrationData(), AuthSession::ReconnectChallengeCallback(), and WorldSocket::WorldSocket().
GetRandomBytes() [2/3]
template<typename Container > void Acore::Crypto::GetRandomBytes (Container & c)
    {
        GetRandomBytes(std::data(c), std::size(c));
    }
References GetRandomBytes().
GetRandomBytes() [3/3]
void Acore::Crypto::GetRandomBytes (uint8 * buf, std::size_t len)
{
    int result = RAND_bytes(buf, len);
    ASSERT(result == 1, "Not enough randomness in OpenSSL's entropy pool. What in the world are you running on?");
}
References ASSERT.