AzeorthCore: kaylaan_the_lost::kaylaan_the_lostAI Struct Reference
kaylaan_the_lost::kaylaan_the_lostAI Struct Reference
Public Member Functions
kaylaan_the_lostAI (Creature *creature)
void EnterCombat (Unit *) override
void ResetDeathblowEvent (bool event_over)
void KilledUnit (Unit *victim) override
void MovementInform (uint32 type, uint32 point) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap _events
bool first_waypath_done = false
bool second_waypath_done = false
bool adyen_dead = false
bool karja_dead = false
bool orelis_dead = false
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
kaylaan_the_lostAI()
kaylaan_the_lost::kaylaan_the_lostAI::kaylaan_the_lostAI (Creature * creature) inline
: ScriptedAI(creature) { }
Member Function Documentation
EnterCombat()
void kaylaan_the_lost::kaylaan_the_lostAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            _events.ScheduleEvent(EVENT_SPELL_BURNING_LIGHT, 2000);
            _events.ScheduleEvent(EVENT_SPELL_CONSECRATION, 3000);
        }
References _events, EVENT_SPELL_BURNING_LIGHT, EVENT_SPELL_CONSECRATION, and EventMap::ScheduleEvent().
KilledUnit()
void kaylaan_the_lost::kaylaan_the_lostAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            switch (victim->GetEntry())
            {
                case ADYEN_THE_LIGHTBRINGER:
                    adyen_dead = true;
                    break;
                case ANCHORITE_KARJA:
                    karja_dead = true;
                    break;
                case EXARCH_ORELIS:
                    orelis_dead = true;
                    break;
            }
            if (adyen_dead && karja_dead && orelis_dead)
                ResetDeathblowEvent(true);
        }
References adyen_dead, ADYEN_THE_LIGHTBRINGER, ANCHORITE_KARJA, EXARCH_ORELIS, Object::GetEntry(), karja_dead, orelis_dead, and ResetDeathblowEvent().
MovementInform()
void kaylaan_the_lost::kaylaan_the_lostAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type != POINT_MOTION_TYPE)
            {
                if (point == 4)
                {
                    // First waypath complete
                    me->SetStandState(UNIT_STAND_STATE_KNEEL);
                    if (Creature* socrethar = me->FindNearestCreature(SOCRETHAR, 30.0f, true))
                        socrethar->AI()->DoAction(EVENT_ADYEN_SAY_3);
                    first_waypath_done = true;
                }
                else if (point == 0)
                {
                    if (first_waypath_done)
                    {
                        if (!second_waypath_done)
{
                            // Second waypath complete
                            me->SetHomePosition(me->GetPosition());
                            if (Creature* adyen = me->FindNearestCreature(ADYEN_THE_LIGHTBRINGER, 30.0f, true))
                                me->SetOrientation(adyen->GetPositionX());
                            if (Creature* socrethar = me->FindNearestCreature(SOCRETHAR, 30.0f, true))
{
                                socrethar->AI()->DoAction(EVENT_KAYLAAN_SAY_1);
                                second_waypath_done = true;
                            }
                        }
                    }
                }
            }
        }
References ADYEN_THE_LIGHTBRINGER, EVENT_ADYEN_SAY_3, EVENT_KAYLAAN_SAY_1, WorldObject::FindNearestCreature(), first_waypath_done, Position::GetPosition(), ScriptedAI::me, POINT_MOTION_TYPE, second_waypath_done, Creature::SetHomePosition(), Position::SetOrientation(), Unit::SetStandState(), SOCRETHAR, and UNIT_STAND_STATE_KNEEL.
ResetDeathblowEvent()
void kaylaan_the_lost::kaylaan_the_lostAI::ResetDeathblowEvent (bool event_over) inline
        {
            me->RemoveAurasDueToSpell(POWER_OF_THE_LEGION);
            me->GetMotionMaster()->MoveTargetedHome();
            // Get socrethar AI so we can reset the event
            if (event_over)
            {
                if (Unit* socrethar = me->FindNearestCreature(SOCRETHAR, 100.0f, true))
                    socrethar->GetAI()->DoAction(RESET_DEATHBLOW_EVENT);
                karja_dead  = false;
                orelis_dead = false;
                adyen_dead  = false;
                me->DespawnOrUnsummon(5000); // Despawn in 5 seconds to reset event
            }
        }
References adyen_dead, Creature::DespawnOrUnsummon(), UnitAI::DoAction(), WorldObject::FindNearestCreature(), socrethar::GetAI(), Unit::GetMotionMaster(), karja_dead, ScriptedAI::me, MotionMaster::MoveTargetedHome(), orelis_dead, POWER_OF_THE_LEGION, Unit::RemoveAurasDueToSpell(), RESET_DEATHBLOW_EVENT, and SOCRETHAR.
Referenced by KilledUnit().
UpdateAI()
void kaylaan_the_lost::kaylaan_the_lostAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            _events.Update(diff);
            if (me->GetHealthPct() <= 30)
                if (Creature* socrethar = me->FindNearestCreature(SOCRETHAR, 200.0f, true))
                    socrethar->AI()->DoAction(EVENT_END_ALDOR_FIGHT);
            switch (_events.ExecuteEvent())
            {
                case EVENT_SPELL_BURNING_LIGHT:
                    me->CastSpell(me->GetVictim(), BURNING_LIGHT, false);
                    _events.ScheduleEvent(EVENT_SPELL_BURNING_LIGHT, 4000);
                    break;
                case EVENT_SPELL_CONSECRATION:
                    me->CastSpell(me->GetVictim(), CONSECRATION, false);
                    _events.ScheduleEvent(EVENT_SPELL_CONSECRATION, 14000);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References _events, BURNING_LIGHT, Unit::CastSpell(), CONSECRATION, UnitAI::DoMeleeAttackIfReady(), EVENT_END_ALDOR_FIGHT, EVENT_SPELL_BURNING_LIGHT, EVENT_SPELL_CONSECRATION, EventMap::ExecuteEvent(), WorldObject::FindNearestCreature(), Unit::GetHealthPct(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, EventMap::ScheduleEvent(), SOCRETHAR, UNIT_STATE_CASTING, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_events
EventMap kaylaan_the_lost::kaylaan_the_lostAI::_events
Referenced by EnterCombat(), and UpdateAI().
adyen_dead
bool kaylaan_the_lost::kaylaan_the_lostAI::adyen_dead = false
Referenced by KilledUnit(), and ResetDeathblowEvent().
first_waypath_done
bool kaylaan_the_lost::kaylaan_the_lostAI::first_waypath_done = false
Referenced by MovementInform().
karja_dead
bool kaylaan_the_lost::kaylaan_the_lostAI::karja_dead = false
Referenced by KilledUnit(), and ResetDeathblowEvent().
orelis_dead
bool kaylaan_the_lost::kaylaan_the_lostAI::orelis_dead = false
Referenced by KilledUnit(), and ResetDeathblowEvent().
second_waypath_done
bool kaylaan_the_lost::kaylaan_the_lostAI::second_waypath_done = false
Referenced by MovementInform().