AzerothCore: ResetEncounterEvent Class Reference
ResetEncounterEvent Class Reference
Public Member Functions
ResetEncounterEvent (Unit *caster, uint32 spellId, ObjectGuid otherTransport)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Unit * _caster
uint32 _spellId
ObjectGuid _otherTransport
Detailed Description
Constructor & Destructor Documentation
ResetEncounterEvent()
ResetEncounterEvent::ResetEncounterEvent (Unit * caster, uint32 spellId, ObjectGuid otherTransport) inline
: _caster(caster), _spellId(spellId), _otherTransport(otherTransport) { }
Member Function Documentation
Execute()
bool ResetEncounterEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        _caster->CastSpell(_caster, _spellId, true);
        _caster->GetTransport()->ToMotionTransport()->UnloadNonStaticPassengers();
        _caster->GetTransport()->AddObjectToRemoveList();
        if (Transport* transport = ObjectAccessor::GetTransport(*_caster, _otherTransport))
        {
            transport->ToMotionTransport()->UnloadNonStaticPassengers();
            transport->AddObjectToRemoveList();
        }
        return true;
    }
References _caster, _otherTransport, _spellId, WorldObject::AddObjectToRemoveList(), Unit::CastSpell(), WorldObject::GetTransport(), ObjectAccessor::GetTransport(), GameObject::ToMotionTransport(), and MotionTransport::UnloadNonStaticPassengers().
Member Data Documentation
_caster
Unit* ResetEncounterEvent::_caster private
Referenced by Execute().
_otherTransport
ObjectGuid ResetEncounterEvent::_otherTransport private
Referenced by Execute().
_spellId
uint32 ResetEncounterEvent::_spellId private
Referenced by Execute().