AzerothCore: azerothcore-wotlk/src/common/Utilities/Timer.h File Reference
Timer.h File Reference
#include "Common.h"
#include "Duration.h"
Classes
struct IntervalTimer
struct TimeTracker
struct TimeTrackerSmall
struct PeriodicTimer
Namespaces
namespace Acore
namespace Acore::Time
Enumerations
enum class TimeFormat : uint8 {
FullText ,
ShortText ,
Numeric
}
enum class TimeOutput : uint8 {
Days ,
Hours ,
Minutes ,
Seconds ,
Milliseconds ,
Microseconds
}
Functions
template<class T >
AC_COMMON_API uint32 Acore::Time::TimeStringTo (std::string_view timeString)
template<class T >
AC_COMMON_API std::string Acore::Time::ToTimeString (uint64 durationTime, TimeOutput timeOutput=TimeOutput::Seconds, TimeFormat timeFormat=TimeFormat::ShortText)
template<class T >
AC_COMMON_API std::string Acore::Time::ToTimeString (std::string_view durationTime, TimeOutput timeOutput=TimeOutput::Seconds, TimeFormat timeFormat=TimeFormat::ShortText)
AC_COMMON_API std::string Acore::Time::ToTimeString (Microseconds durationTime, TimeOutput timeOutput=TimeOutput::Seconds, TimeFormat timeFormat=TimeFormat::ShortText)
AC_COMMON_API time_t Acore::Time::LocalTimeToUTCTime (time_t time)
AC_COMMON_API time_t Acore::Time::GetLocalHourTimestamp (time_t time, uint8 hour, bool onlyAfterTime=true)
AC_COMMON_API std::tm Acore::Time::TimeBreakdown (time_t t=0)
AC_COMMON_API std::string Acore::Time::TimeToTimestampStr (Seconds time=0s, std::string_view fmt={})
AC_COMMON_API std::string Acore::Time::TimeToHumanReadable (Seconds time=0s, std::string_view fmt={})
AC_COMMON_API time_t Acore::Time::GetNextTimeWithDayAndHour (int8 dayOfWeek, int8 hour)
AC_COMMON_API time_t Acore::Time::GetNextTimeWithMonthAndHour (int8 month, int8 hour)
AC_COMMON_API uint32 Acore::Time::GetSeconds (Seconds time=0s)
AC_COMMON_API uint32 Acore::Time::GetMinutes (Seconds time=0s)
AC_COMMON_API uint32 Acore::Time::GetHours (Seconds time=0s)
AC_COMMON_API uint32 Acore::Time::GetDayInWeek (Seconds time=0s)
AC_COMMON_API uint32 Acore::Time::GetDayInMonth (Seconds time=0s)
AC_COMMON_API uint32 Acore::Time::GetDayInYear (Seconds time=0s)
AC_COMMON_API uint32 Acore::Time::GetMonth (Seconds time=0s)
AC_COMMON_API uint32 Acore::Time::GetYear (Seconds time=0s)
AC_COMMON_API struct tm * localtime_r (time_t const *time, struct tm *result)
TimePoint GetApplicationStartTime ()
Milliseconds GetTimeMS ()
Milliseconds GetMSTimeDiff (Milliseconds oldMSTime, Milliseconds newMSTime)
uint32 getMSTime ()
uint32 getMSTimeDiff (uint32 oldMSTime, uint32 newMSTime)
uint32 getMSTimeDiff (uint32 oldMSTime, TimePoint newTime)
uint32 GetMSTimeDiffToNow (uint32 oldMSTime)
Milliseconds GetMSTimeDiffToNow (Milliseconds oldMSTime)
Seconds GetEpochTime ()
Enumeration Type Documentation
TimeFormat
enum class TimeFormat : uint8 strong
Enumerator
FullText
ShortText
Numeric
{
    FullText,  // 1 Days 2 Hours 3 Minutes 4 Seconds 5 Milliseconds
    ShortText, // 1d 2h 3m 4s 5ms
    Numeric    // 1:2:3:4:5
};
TimeOutput
enum class TimeOutput : uint8 strong
Enumerator
Days
Hours
Minutes
Seconds
Milliseconds
Microseconds
{
    Days,         // 1d
    Hours,        // 1d 2h
    Minutes,      // 1d 2h 3m
    Seconds,      // 1d 2h 3m 4s
    Milliseconds, // 1d 2h 3m 4s 5ms
    Microseconds  // 1d 2h 3m 4s 5ms 6us
};
Function Documentation
GetApplicationStartTime()
TimePoint GetApplicationStartTime () inline
{
    using namespace std::chrono;
    static const TimePoint ApplicationStartTime = steady_clock::now();
    return ApplicationStartTime;
}
Referenced by getMSTime(), getMSTimeDiff(), and GetTimeMS().
GetEpochTime()
Seconds GetEpochTime () inline
{
    using namespace std::chrono;
    return duration_cast<Seconds>(system_clock::now().time_since_epoch());
}
Referenced by Acore::Time::GetDayInMonth(), Acore::Time::GetDayInWeek(), Acore::Time::GetDayInYear(), Acore::Time::GetHours(), Acore::Time::GetMinutes(), Acore::Time::GetMonth(), Acore::Time::GetSeconds(), Log::GetTimestampStr(), Acore::Time::GetYear(), AppenderFile::OpenFile(), SFMTRand::SFMTRand(), Acore::Time::TimeBreakdown(), GameTime::UpdateGameTimers(), and Acore::Crypto::TOTP::ValidateToken().
getMSTime()
uint32 getMSTime () inline
{
    using namespace std::chrono;
    return uint32(duration_cast<milliseconds>(steady_clock::now() - GetApplicationStartTime()).count());
}
References GetApplicationStartTime().
Referenced by MySQLConnection::_Query(), DisableMgr::CheckQuestDisables(), CharacterDatabaseCleaner::CleanDatabase(), MySQLConnection::Execute(), GetMSTimeDiffToNow(), Player::GetSpellCooldownDelay(), mmaps_commandscript::HandleMmapTestArea(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveUnRootAck(), FreezeDetector::Handler(), ArenaSpectator::HandleResetCommand(), Player::HasSpellCooldown(), Player::HasSpellItemCooldown(), PacketLog::Initialize(), PlayerDump::InitializeTables(), OutdoorPvPMgr::InitOutdoorPvP(), WaypointMgr::Load(), ObjectMgr::LoadAccessRequirements(), AchievementGlobalMgr::LoadAchievementCriteriaData(), AchievementGlobalMgr::LoadAchievementCriteriaList(), AchievementGlobalMgr::LoadAchievementReferenceList(), ObjectMgr::LoadAcoreStrings(), ObjectMgr::LoadAreaTriggers(), ObjectMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ArenaTeamMgr::LoadArenaTeams(), AuctionHouseMgr::LoadAuctionItems(), AuctionHouseMgr::LoadAuctions(), AutobroadcastMgr::LoadAutobroadcasts(), BattlegroundMgr::LoadBattlegroundTemplates(), BattlegroundMgr::LoadBattleMastersEntry(), ObjectMgr::LoadBroadcastTextLocales(), ObjectMgr::LoadBroadcastTexts(), ChannelMgr::LoadChannelRights(), ChannelMgr::LoadChannels(), CharacterCache::LoadCharacterCacheStorage(), AchievementGlobalMgr::LoadCompletedAchievements(), ConditionMgr::LoadConditions(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureClassLevelStats(), FormationMgr::LoadCreatureFormations(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatureMovementOverrides(), ObjectMgr::LoadCreatureQuestItems(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureTemplateAddons(), ObjectMgr::LoadCreatureTemplateModels(), ObjectMgr::LoadCreatureTemplateResistances(), ObjectMgr::LoadCreatureTemplates(), ObjectMgr::LoadCreatureTemplateSpells(), CreatureTextMgr::LoadCreatureTextLocales(), CreatureTextMgr::LoadCreatureTexts(), ScriptMgr::LoadDatabase(), DisableMgr::LoadDisables(), SpellMgr::LoadEnchantCustomAttr(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFactionChangeAchievements(), ObjectMgr::LoadFactionChangeItems(), ObjectMgr::LoadFactionChangeQuests(), ObjectMgr::LoadFactionChangeReputations(), ObjectMgr::LoadFactionChangeSpells(), ObjectMgr::LoadFactionChangeTitles(), ObjectMgr::LoadFishingBaseSkillLevel(), AddonMgr::LoadFromDB(), SmartWaypointMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolMgr::LoadFromDB(), ObjectMgr::LoadGameObjectAddons(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGameObjectLocales(), LoadGameObjectModelList(), ObjectMgr::LoadGameObjectQuestItems(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGameObjectTemplate(), ObjectMgr::LoadGameObjectTemplateAddons(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipText(), Graveyard::LoadGraveyardFromDB(), Graveyard::LoadGraveyardZones(), GroupMgr::LoadGroups(), GuildMgr::LoadGuilds(), GameEventMgr::LoadHolidayDates(), ObjectMgr::LoadInstanceEncounters(), InstanceSaveMgr::LoadInstances(), ObjectMgr::LoadInstanceTemplate(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemSetNameLocales(), ObjectMgr::LoadItemSetNames(), ObjectMgr::LoadItemTemplates(), lfg::LFGMgr::LoadLFGDungeons(), ObjectMgr::LoadLinkedRespawn(), LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Fishing(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Item(), LoadLootTemplates_Mail(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Player(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Reference(), LoadLootTemplates_Skinning(), LoadLootTemplates_Spell(), LoadM2Cameras(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadMailServerTemplates(), ObjectMgr::LoadModuleStrings(), ObjectMgr::LoadModuleStringsLocale(), MotdMgr::LoadMotd(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadNpcTextLocales(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPageTexts(), SpellMgr::LoadPetDefaultSpells(), PetitionMgr::LoadPetitions(), ObjectMgr::LoadPetLevelInfo(), SpellMgr::LoadPetLevelupSpellMap(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPetNamesLocales(), ObjectMgr::LoadPetNumber(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadProfanityNamesFromDB(), ObjectMgr::LoadProfanityNamesFromDBC(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestGreetings(), ObjectMgr::LoadQuestGreetingsLocales(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestMoneyRewards(), ObjectMgr::LoadQuestOfferRewardLocale(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRelationsHelper(), ObjectMgr::LoadQuestRequestItemsLocale(), ObjectMgr::LoadQuests(), LoadRandomEnchantmentsTable(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayerNamesDB(), ObjectMgr::LoadReservedPlayerNamesDBC(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), lfg::LFGMgr::LoadRewards(), ObjectMgr::LoadScriptNames(), ObjectMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), PetitionMgr::LoadSignatures(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), SpellMgr::LoadSkillLineAbilityMap(), LoadSkillPerfectItemTable(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellCooldownOverrides(), SpellMgr::LoadSpellEnchantProcData(), SpellMgr::LoadSpellGroups(), SpellMgr::LoadSpellGroupStackRules(), SpellMgr::LoadSpellInfoCorrections(), SpellMgr::LoadSpellInfoCustomAttributes(), SpellMgr::LoadSpellInfoStore(), SpellMgr::LoadSpellLearnSkills(), SpellMgr::LoadSpellLinked(), SpellMgr::LoadSpellMixology(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), SpellMgr::LoadSpellRanks(), SpellMgr::LoadSpellRequired(), ObjectMgr::LoadSpellScriptNames(), SpellMgr::LoadSpellSpecificAndAuraState(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), LootItemStorage::LoadStorageFromDB(), TicketMgr::LoadSurveys(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTempSummons(), TicketMgr::LoadTickets(), ObjectMgr::LoadTrainerSpell(), TransportMgr::LoadTransportTemplates(), ObjectMgr::LoadVehicleAccessories(), ObjectMgr::LoadVehicleSeatAddon(), ObjectMgr::LoadVehicleTemplateAccessories(), ObjectMgr::LoadVendors(), WeatherMgr::LoadWeatherData(), World::LoadWorldStates(), PacketLog::LogPacket(), main(), ObjectMgr::ReturnOrDeleteOldMails(), WorldSession::SendTimeSync(), World::SetInitialWorldSettings(), TransportMgr::SpawnContinentTransports(), Player::Update(), ObjectMgr::ValidateSpellScripts(), and WorldUpdateLoop().
GetMSTimeDiff()
Milliseconds GetMSTimeDiff (Milliseconds oldMSTime, Milliseconds newMSTime) inline
{
    if (oldMSTime > newMSTime)
    {
        return oldMSTime - newMSTime;
    }
    else
    {
        return newMSTime - oldMSTime;
    }
}
Referenced by AuctionHouseObject::BuildListAuctionItems(), GetMSTimeDiffToNow(), WorldSession::HandleAuctionListItems(), WorldSession::HandleAuctionListOwnerItems(), WorldUpdateTime::RecordUpdateTime(), and lfg::LFGMgr::UpdateRaidBrowser().
getMSTimeDiff() [1/2]
uint32 getMSTimeDiff (uint32 oldMSTime, TimePoint newTime) inline
{
    using namespace std::chrono;
    uint32 newMSTime = uint32(duration_cast<milliseconds>(newTime - GetApplicationStartTime()).count());
    return getMSTimeDiff(oldMSTime, newMSTime);
}
References GetApplicationStartTime(), and getMSTimeDiff().
getMSTimeDiff() [2/2]
uint32 getMSTimeDiff (uint32 oldMSTime, uint32 newMSTime) inline
{
    // getMSTime() have limited data range and this is case when it overflow in this tick
    if (oldMSTime > newMSTime)
    {
        return (0xFFFFFFFF - oldMSTime) + newMSTime;
    }
    else
    {
        return newMSTime - oldMSTime;
    }
}
Referenced by MySQLConnection::_Query(), WorldObject::AddToNotify(), MySQLConnection::Execute(), Unit::GetDiminishing(), getMSTimeDiff(), GetMSTimeDiffToNow(), WorldSession::HandleBattlefieldStatusOpcode(), spell_mimiron_p3wx2_laser_barrage_aura::HandleEffectPeriodic(), mmaps_commandscript::HandleMmapTestArea(), FreezeDetector::Handler(), ArenaSpectator::HandleResetCommand(), WorldSession::HandleTimeSyncResp(), GlobalCooldownMgr::HasGlobalCooldown(), Unit::IsUnderLastManaUseEffect(), BattlegroundQueue::PlayerInvitedToBGUpdateAverageWaitTime(), boss_ignis::boss_ignisAI::SetData(), and WorldUpdateLoop().
GetMSTimeDiffToNow() [1/2]
Milliseconds GetMSTimeDiffToNow (Milliseconds oldMSTime) inline
{
    return GetMSTimeDiff(oldMSTime, GetTimeMS());
}
References GetMSTimeDiff(), and GetTimeMS().
GetMSTimeDiffToNow() [2/2]
uint32 GetMSTimeDiffToNow (uint32 oldMSTime) inline
{
    return getMSTimeDiff(oldMSTime, getMSTime());
}
References getMSTime(), and getMSTimeDiff().
Referenced by DisableMgr::CheckQuestDisables(), CharacterDatabaseCleaner::CleanDatabase(), TransactionTask::Execute(), TransactionWithResultTask::Execute(), PlayerDump::InitializeTables(), OutdoorPvPMgr::InitOutdoorPvP(), WaypointMgr::Load(), ObjectMgr::LoadAccessRequirements(), AchievementGlobalMgr::LoadAchievementCriteriaData(), AchievementGlobalMgr::LoadAchievementCriteriaList(), AchievementGlobalMgr::LoadAchievementReferenceList(), ObjectMgr::LoadAcoreStrings(), ObjectMgr::LoadAreaTriggers(), ObjectMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ArenaTeamMgr::LoadArenaTeams(), AuctionHouseMgr::LoadAuctionItems(), AuctionHouseMgr::LoadAuctions(), AutobroadcastMgr::LoadAutobroadcasts(), BattlegroundMgr::LoadBattlegroundTemplates(), BattlegroundMgr::LoadBattleMastersEntry(), ObjectMgr::LoadBroadcastTextLocales(), ObjectMgr::LoadBroadcastTexts(), ChannelMgr::LoadChannelRights(), ChannelMgr::LoadChannels(), CharacterCache::LoadCharacterCacheStorage(), AchievementGlobalMgr::LoadCompletedAchievements(), ConditionMgr::LoadConditions(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureClassLevelStats(), FormationMgr::LoadCreatureFormations(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatureMovementOverrides(), ObjectMgr::LoadCreatureQuestItems(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureTemplateAddons(), ObjectMgr::LoadCreatureTemplateModels(), ObjectMgr::LoadCreatureTemplateResistances(), ObjectMgr::LoadCreatureTemplates(), ObjectMgr::LoadCreatureTemplateSpells(), CreatureTextMgr::LoadCreatureTextLocales(), CreatureTextMgr::LoadCreatureTexts(), ScriptMgr::LoadDatabase(), DisableMgr::LoadDisables(), SpellMgr::LoadEnchantCustomAttr(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFactionChangeAchievements(), ObjectMgr::LoadFactionChangeItems(), ObjectMgr::LoadFactionChangeQuests(), ObjectMgr::LoadFactionChangeReputations(), ObjectMgr::LoadFactionChangeSpells(), ObjectMgr::LoadFactionChangeTitles(), ObjectMgr::LoadFishingBaseSkillLevel(), AddonMgr::LoadFromDB(), SmartWaypointMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolMgr::LoadFromDB(), ObjectMgr::LoadGameObjectAddons(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGameObjectLocales(), LoadGameObjectModelList(), ObjectMgr::LoadGameObjectQuestItems(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGameObjectTemplate(), ObjectMgr::LoadGameObjectTemplateAddons(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipText(), Graveyard::LoadGraveyardFromDB(), Graveyard::LoadGraveyardZones(), GroupMgr::LoadGroups(), GuildMgr::LoadGuilds(), GameEventMgr::LoadHolidayDates(), ObjectMgr::LoadInstanceEncounters(), InstanceSaveMgr::LoadInstances(), ObjectMgr::LoadInstanceTemplate(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemSetNameLocales(), ObjectMgr::LoadItemSetNames(), ObjectMgr::LoadItemTemplates(), lfg::LFGMgr::LoadLFGDungeons(), ObjectMgr::LoadLinkedRespawn(), LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Fishing(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Item(), LoadLootTemplates_Mail(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Player(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Reference(), LoadLootTemplates_Skinning(), LoadLootTemplates_Spell(), LoadM2Cameras(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadMailServerTemplates(), ObjectMgr::LoadModuleStrings(), ObjectMgr::LoadModuleStringsLocale(), MotdMgr::LoadMotd(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadNpcTextLocales(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPageTexts(), SpellMgr::LoadPetDefaultSpells(), PetitionMgr::LoadPetitions(), ObjectMgr::LoadPetLevelInfo(), SpellMgr::LoadPetLevelupSpellMap(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPetNamesLocales(), ObjectMgr::LoadPetNumber(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadProfanityNamesFromDB(), ObjectMgr::LoadProfanityNamesFromDBC(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestGreetings(), ObjectMgr::LoadQuestGreetingsLocales(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestMoneyRewards(), ObjectMgr::LoadQuestOfferRewardLocale(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRelationsHelper(), ObjectMgr::LoadQuestRequestItemsLocale(), ObjectMgr::LoadQuests(), LoadRandomEnchantmentsTable(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayerNamesDB(), ObjectMgr::LoadReservedPlayerNamesDBC(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), lfg::LFGMgr::LoadRewards(), ObjectMgr::LoadScriptNames(), ObjectMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), PetitionMgr::LoadSignatures(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), SpellMgr::LoadSkillLineAbilityMap(), LoadSkillPerfectItemTable(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellCooldownOverrides(), SpellMgr::LoadSpellEnchantProcData(), SpellMgr::LoadSpellGroups(), SpellMgr::LoadSpellGroupStackRules(), SpellMgr::LoadSpellInfoCorrections(), SpellMgr::LoadSpellInfoCustomAttributes(), SpellMgr::LoadSpellInfoStore(), SpellMgr::LoadSpellLearnSkills(), SpellMgr::LoadSpellLinked(), SpellMgr::LoadSpellMixology(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), SpellMgr::LoadSpellRanks(), SpellMgr::LoadSpellRequired(), ObjectMgr::LoadSpellScriptNames(), SpellMgr::LoadSpellSpecificAndAuraState(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), LootItemStorage::LoadStorageFromDB(), TicketMgr::LoadSurveys(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTempSummons(), TicketMgr::LoadTickets(), ObjectMgr::LoadTrainerSpell(), TransportMgr::LoadTransportTemplates(), ObjectMgr::LoadVehicleAccessories(), ObjectMgr::LoadVehicleSeatAddon(), ObjectMgr::LoadVehicleTemplateAccessories(), ObjectMgr::LoadVendors(), WeatherMgr::LoadWeatherData(), World::LoadWorldStates(), main(), ObjectMgr::ReturnOrDeleteOldMails(), World::SetInitialWorldSettings(), TransportMgr::SpawnContinentTransports(), Player::Update(), and ObjectMgr::ValidateSpellScripts().
GetTimeMS()
Milliseconds GetTimeMS () inline
{
    using namespace std::chrono;
    return duration_cast<milliseconds>(steady_clock::now() - GetApplicationStartTime());
}
References GetApplicationStartTime().
Referenced by AuctionHouseObject::BuildListAuctionItems(), TransactionTask::Execute(), TransactionWithResultTask::Execute(), GetMSTimeDiffToNow(), UpdateTime::RecordUpdateTimeReset(), GameTime::UpdateGameTimers(), and lfg::LFGMgr::UpdateRaidBrowser().
localtime_r()
AC_COMMON_API struct tm * localtime_r (time_t const * time, struct tm * result)
{
    localtime_s(result, time);
    return result;
}
Referenced by guild_commandscript::HandleGuildInfoCommand(), and Acore::Time::TimeBreakdown().