AzerothCore: spell_brewfest_main_ram_buff Class Reference
spell_brewfest_main_ram_buff Class Reference
Private Member Functions
PrepareAuraScript (spell_brewfest_main_ram_buff) uint8 privateLevel
bool Load () override
void HandleEffectPeriodic (AuraEffect const *aurEff)
void HandleEffectRemove (AuraEffect const *, AuraEffectHandleModes)
void Register () override
Private Attributes
uint32 questTick
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleEffectPeriodic()
void spell_brewfest_main_ram_buff::HandleEffectPeriodic (AuraEffect const * aurEff) inline private
    {
        Unit* caster = GetCaster();
        if (!caster || !caster->IsMounted() || !caster->ToPlayer())
            return;
        if (caster->GetMountID() != RACING_RAM_MODEL)
            return;
        Aura* aur = caster->GetAura(42924);
        if (!aur)
        {
            caster->CastSpell(caster, 42924, true);
            return;
        }
        // Check if exhausted
        if (caster->GetAura(SPELL_RAM_EXHAUSTED))
        {
            if (privateLevel)
            {
                caster->RemoveAurasDueToSpell(SPELL_CANTER);
                caster->RemoveAurasDueToSpell(SPELL_GALLOP);
            }
            aur->SetStackAmount(1);
            return;
        }
        uint32 stack = aur->GetStackAmount();
        uint8 mode = 0;
        switch (privateLevel)
        {
            case 0:
                if (stack > 1)
                {
                    questTick = 0;
                    caster->CastSpell(caster, SPELL_TROT, true);
                    privateLevel++;
                    mode = 1; // unapply
                    break;
                }
                // just walking, fatiuge handling
                if (Aura* fatigueAura = caster->GetAura(SPELL_RAM_FATIGUE))
                {
                    fatigueAura->ModStackAmount(-4);
                }
                break;
            case 1:
                // One click to maintain speed, more to increase
                if (stack < 2)
                {
                    caster->RemoveAurasDueToSpell(SPELL_TROT);
                    questTick = 0;
                    privateLevel--;
                    mode = 2; // apply
                }
                else if (stack > 2)
                {
                    questTick = 0;
                    caster->CastSpell(caster, SPELL_CANTER, true);
                    privateLevel++;
                }
                else if (questTick++ > 3)
                    caster->ToPlayer()->KilledMonsterCredit(CREDIT_TROT);
                break;
            case 2:
                // Two - three clicks to maintains speed, less to decrease, more to increase
                if (stack < 3)
                {
                    caster->CastSpell(caster, SPELL_TROT, true);
                    privateLevel--;
                    questTick = 0;
                }
                else if (stack > 4)
                {
                    caster->CastSpell(caster, SPELL_GALLOP, true);
                    privateLevel++;
                    questTick = 0;
                }
                else if (questTick++ > 3)
                    caster->ToPlayer()->KilledMonsterCredit(CREDIT_CANTER);
                break;
            case 3:
                // Four or more clicks to maintains speed, less to decrease
                if (stack < 5)
                {
                    caster->CastSpell(caster, SPELL_CANTER, true);
                    privateLevel--;
                    questTick = 0;
                }
                else if (questTick++ > 3)
                    caster->ToPlayer()->KilledMonsterCredit(CREDIT_GALLOP);
                break;
        }
        // Set to base amount
        aur->SetStackAmount(1);
        // apply/unapply effect 1
        if (mode)
            if (Aura* base = aurEff->GetBase())
                if (AuraEffect* aEff = base->GetEffect(EFFECT_0))
                {
                    aEff->SetAmount(mode == 1 ? 0 : -50);
                    caster->UpdateSpeed(MOVE_RUN, true);
                }
    }
References Unit::CastSpell(), CREDIT_CANTER, CREDIT_GALLOP, CREDIT_TROT, EFFECT_0, Unit::GetAura(), AuraEffect::GetBase(), AuraScript::GetCaster(), Unit::GetMountID(), Aura::GetStackAmount(), Unit::IsMounted(), Player::KilledMonsterCredit(), MOVE_RUN, questTick, RACING_RAM_MODEL, Unit::RemoveAurasDueToSpell(), Aura::SetStackAmount(), SPELL_CANTER, SPELL_GALLOP, SPELL_RAM_EXHAUSTED, SPELL_RAM_FATIGUE, SPELL_TROT, Object::ToPlayer(), and Unit::UpdateSpeed().
Referenced by Register().
HandleEffectRemove()
void spell_brewfest_main_ram_buff::HandleEffectRemove (AuraEffect const * , AuraEffectHandleModes) inline private
    {
        if (Unit* target = GetTarget())
            target->RemoveAurasDueToSpell(SPELL_RAM_FATIGUE);
    }
References AuraScript::GetTarget(), and SPELL_RAM_FATIGUE.
Referenced by Register().
Load()
bool spell_brewfest_main_ram_buff::Load () inline override private virtual
Reimplemented from _SpellScript.
    {
        questTick = 0;
        privateLevel = 0;
        return true;
    }
References questTick.
PrepareAuraScript()
spell_brewfest_main_ram_buff::PrepareAuraScript (spell_brewfest_main_ram_buff) private
Register()
void spell_brewfest_main_ram_buff::Register () inline override private virtual
Implements _SpellScript.
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_brewfest_main_ram_buff::HandleEffectPeriodic, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY);
        OnEffectRemove += AuraEffectRemoveFn(spell_brewfest_main_ram_buff::HandleEffectRemove, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
References AURA_EFFECT_HANDLE_REAL, AuraEffectPeriodicFn, AuraEffectRemoveFn, EFFECT_1, HandleEffectPeriodic(), HandleEffectRemove(), AuraScript::OnEffectPeriodic, AuraScript::OnEffectRemove, and SPELL_AURA_PERIODIC_DUMMY.
Member Data Documentation
questTick
uint32 spell_brewfest_main_ram_buff::questTick private
Referenced by HandleEffectPeriodic(), and Load().