AzerothCore: boss_rend_blackhand::boss_rend_blackhandAI Struct Reference
boss_rend_blackhand::boss_rend_blackhandAI Struct Reference
Public Member Functions
boss_rend_blackhandAI (Creature *creature)
void Reset () override
void SummonedCreatureDies (Creature *, Unit *) override
void JustSummoned (Creature *summon) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why) override
void IsSummonedBy (WorldObject *) override
void JustDied (Unit *) override
void SummonedCreatureDespawn (Creature *creature) override
void SetData (uint32 type, uint32 data) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void SummonWave ()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
bool gythEvent
uint8 _currentWave
ObjectGuid victorGUID
ObjectGuid waveDoorGUID
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_rend_blackhandAI()
boss_rend_blackhand::boss_rend_blackhandAI::boss_rend_blackhandAI (Creature * creature) inline
: BossAI(creature, DATA_WARCHIEF_REND_BLACKHAND) { }
Member Function Documentation
EnterEvadeMode()
void boss_rend_blackhand::boss_rend_blackhandAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from BossAI.
        {
            instance->SetBossState(DATA_WARCHIEF_REND_BLACKHAND, FAIL);
            instance->SetBossState(DATA_GYTH, FAIL);
            BossAI::EnterEvadeMode(why);
            me->DespawnOrUnsummon();
        }
References DATA_GYTH, DATA_WARCHIEF_REND_BLACKHAND, Creature::DespawnOrUnsummon(), BossAI::EnterEvadeMode(), FAIL, BossAI::instance, ScriptedAI::me, and InstanceScript::SetBossState().
IsSummonedBy()
void boss_rend_blackhand::boss_rend_blackhandAI::IsSummonedBy (WorldObject *) inline override virtual
Reimplemented from CreatureAI.
        {
            Talk(EMOTE_BLACKHAND_DISMOUNT);
        }
References EMOTE_BLACKHAND_DISMOUNT.
JustDied()
void boss_rend_blackhand::boss_rend_blackhandAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            _JustDied();
            if (Creature* victor = me->FindNearestCreature(NPC_LORD_VICTOR_NEFARIUS, 75.0f, true))
                victor->AI()->SetData(1, 2);
            if (GameObject* exitDoor = me->GetMap()->GetGameObject(instance->GetGuidData(GO_GYTH_ENTRY_DOOR)))
                exitDoor->SetGoState(GO_STATE_ACTIVE);
            instance->SetBossState(DATA_WARCHIEF_REND_BLACKHAND, DONE);
        }
References BossAI::_JustDied(), DATA_WARCHIEF_REND_BLACKHAND, DONE, WorldObject::FindNearestCreature(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_GYTH_ENTRY_DOOR, GO_STATE_ACTIVE, BossAI::instance, ScriptedAI::me, NPC_LORD_VICTOR_NEFARIUS, and InstanceScript::SetBossState().
JustEngagedWith()
void boss_rend_blackhand::boss_rend_blackhandAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            _JustEngagedWith();
            events.ScheduleEvent(EVENT_WHIRLWIND, 13s, 15s);
            events.ScheduleEvent(EVENT_CLEAVE, 15s, 17s);
            events.ScheduleEvent(EVENT_MORTAL_STRIKE, 17s, 19s);
        }
References BossAI::_JustEngagedWith(), EVENT_CLEAVE, EVENT_MORTAL_STRIKE, and EVENT_WHIRLWIND.
JustSummoned()
void boss_rend_blackhand::boss_rend_blackhandAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            summons.Summon(summon);
            if (summon->GetEntry() == NPC_GYTH)
            {
                me->DespawnOrUnsummon();
                return;
            }
            summon->AI()->DoZoneInCombat(nullptr, 100.0f);
        }
References Creature::AI(), Creature::DespawnOrUnsummon(), CreatureAI::DoZoneInCombat(), Object::GetEntry(), ScriptedAI::me, NPC_GYTH, SummonList::Summon(), and BossAI::summons.
MovementInform()
void boss_rend_blackhand::boss_rend_blackhandAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type == WAYPOINT_MOTION_TYPE)
            {
                switch (id)
                {
                    case 5:
                        events.ScheduleEvent(EVENT_TELEPORT_1, 2s);
                        break;
                }
            }
        }
References EVENT_TELEPORT_1, and WAYPOINT_MOTION_TYPE.
Reset()
void boss_rend_blackhand::boss_rend_blackhandAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            _Reset();
            if (instance->GetBossState(DATA_GYTH) == IN_PROGRESS)
            {
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_PREPARATION);
                me->SetImmuneToAll(false);
                return;
            }
            me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_PREPARATION);
            me->SetImmuneToAll(true);
            gythEvent = false;
            victorGUID.Clear();
            waveDoorGUID.Clear();
            _currentWave = 0;
            summons.DespawnAll();
            if (Creature* victor = me->FindNearestCreature(NPC_LORD_VICTOR_NEFARIUS, 5.0f, true))
                victor->Respawn(true);
            if (GameObject* exitDoor = me->GetMap()->GetGameObject(instance->GetGuidData(GO_GYTH_ENTRY_DOOR)))
                exitDoor->SetGoState(GO_STATE_ACTIVE);
            instance->SetBossState(DATA_WARCHIEF_REND_BLACKHAND, NOT_STARTED);
        }
References _currentWave, BossAI::_Reset(), ObjectGuid::Clear(), DATA_GYTH, DATA_WARCHIEF_REND_BLACKHAND, SummonList::DespawnAll(), WorldObject::FindNearestCreature(), InstanceScript::GetBossState(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_GYTH_ENTRY_DOOR, GO_STATE_ACTIVE, gythEvent, IN_PROGRESS, BossAI::instance, ScriptedAI::me, NOT_STARTED, NPC_LORD_VICTOR_NEFARIUS, Unit::RemoveUnitFlag(), InstanceScript::SetBossState(), Unit::SetImmuneToAll(), Unit::SetUnitFlag(), BossAI::summons, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_PREPARATION, victorGUID, and waveDoorGUID.
SetData()
void boss_rend_blackhand::boss_rend_blackhandAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
        {
            if (type == AREATRIGGER && data == AREATRIGGER_BLACKROCK_STADIUM)
            {
                if (!gythEvent)
                {
                    gythEvent = true;
                    if (Creature* victor = me->FindNearestCreature(NPC_LORD_VICTOR_NEFARIUS, 5.0f))
                    {
                        if (!victor->IsAlive())
{
                            victor->Respawn(true);
                        }
                        victorGUID = victor->GetGUID();
                    }
                    if (GameObject* portcullis = me->FindNearestGameObject(GO_DR_PORTCULLIS, 50.0f))
                        waveDoorGUID = portcullis->GetGUID();
                    events.ScheduleEvent(EVENT_TURN_TO_PLAYER, 0);
                    events.ScheduleEvent(EVENT_START_1, 1s);
                }
            }
        }
References AREATRIGGER, AREATRIGGER_BLACKROCK_STADIUM, EVENT_START_1, EVENT_TURN_TO_PLAYER, WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), GO_DR_PORTCULLIS, gythEvent, ScriptedAI::me, NPC_LORD_VICTOR_NEFARIUS, victorGUID, and waveDoorGUID.
SummonedCreatureDespawn()
void boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn (Creature * creature) inline override virtual
Reimplemented from BossAI.
        {
            if (creature->IsAlive() && !summons.IsAnyCreatureInCombat())
            {
                instance->SetBossState(DATA_WARCHIEF_REND_BLACKHAND, FAIL);
            }
            BossAI::SummonedCreatureDespawn(creature);
        }
References DATA_WARCHIEF_REND_BLACKHAND, FAIL, BossAI::instance, Unit::IsAlive(), SummonList::IsAnyCreatureInCombat(), InstanceScript::SetBossState(), BossAI::SummonedCreatureDespawn(), and BossAI::summons.
SummonedCreatureDies()
void boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDies (Creature * , Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!summons.IsAnyCreatureAlive())
            {
                events.ScheduleEvent(EVENT_WAVES_TEXT_1 + _currentWave, 10s);
            }
        }
References _currentWave, EVENT_WAVES_TEXT_1, SummonList::IsAnyCreatureAlive(), and BossAI::summons.
SummonWave()
void boss_rend_blackhand::boss_rend_blackhandAI::SummonWave () inline
        {
            me->SummonCreatureGroup(_currentWave);
            if (GameObject* waveDoor = me->GetMap()->GetGameObject(waveDoorGUID))
            {
                waveDoor->UseDoorOrButton();
            }
            ++_currentWave;
        }
References _currentWave, Map::GetGameObject(), WorldObject::GetMap(), ScriptedAI::me, WorldObject::SummonCreatureGroup(), and waveDoorGUID.
Referenced by UpdateAI().
UpdateAI()
void boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            if (gythEvent)
            {
                events.Update(diff);
                while (uint32 eventId = events.ExecuteEvent())
                {
                    switch (eventId)
                    {
                        case EVENT_START_1:
                            instance->SetBossState(DATA_WARCHIEF_REND_BLACKHAND, IN_PROGRESS);
                            instance->SetData(DATA_VAELASTRASZ, NOT_STARTED);
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->AI()->Talk(SAY_NEFARIUS_0);
                            if (GameObject* door2 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_GYTH_ENTRY_DOOR)))
                                door2->SetGoState(GO_STATE_READY);
                            events.ScheduleEvent(EVENT_START_2, 4s);
                            break;
                        case EVENT_START_2:
                            events.ScheduleEvent(EVENT_TURN_TO_PLAYER, 0);
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->HandleEmoteCommand(EMOTE_ONESHOT_POINT);
                            events.ScheduleEvent(EVENT_START_3, 4s);
                            break;
                        case EVENT_START_3:
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->AI()->Talk(SAY_NEFARIUS_1);
                            events.ScheduleEvent(EVENT_SPAWN_WAVE, 2s);
                            events.ScheduleEvent(EVENT_TURN_TO_REND, 4s);
                            break;
                        case EVENT_TURN_TO_REND:
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
{
                                victor->SetFacingToObject(me);
                                victor->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                            }
                            break;
                        case EVENT_TURN_TO_PLAYER:
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                if (Unit* player = victor->SelectNearestPlayer(60.0f))
                                    victor->SetFacingToObject(player);
                            break;
                        case EVENT_TURN_TO_FACING_1:
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->SetFacingTo(1.518436f);
                            break;
                        case EVENT_TURN_TO_FACING_2:
                            me->SetFacingTo(1.658063f);
                            break;
                        case EVENT_TURN_TO_FACING_3:
                            me->SetFacingTo(1.500983f);
                            break;
                        case EVENT_WAVES_EMOTE_1:
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->HandleEmoteCommand(EMOTE_ONESHOT_QUESTION);
                            break;
                        case EVENT_WAVES_EMOTE_2:
                            me->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                            break;
                        case EVENT_WAVES_TEXT_1:
                            events.ScheduleEvent(EVENT_TURN_TO_PLAYER, 0ms);
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->AI()->Talk(SAY_NEFARIUS_2);
                            me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                            events.ScheduleEvent(EVENT_TURN_TO_FACING_1, 4s);
                            events.ScheduleEvent(EVENT_WAVES_EMOTE_1, 5s);
                            events.ScheduleEvent(EVENT_SPAWN_WAVE, 3s);
                            break;
                        case EVENT_WAVES_TEXT_2:
                            events.ScheduleEvent(EVENT_TURN_TO_PLAYER, 0);
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->AI()->Talk(SAY_NEFARIUS_3);
                            events.ScheduleEvent(EVENT_TURN_TO_FACING_1, 4s);
                            events.ScheduleEvent(EVENT_SPAWN_WAVE, 3s);
                            break;
                        case EVENT_WAVES_TEXT_3:
                            events.ScheduleEvent(EVENT_TURN_TO_PLAYER, 0);
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->AI()->Talk(SAY_NEFARIUS_4);
                            events.ScheduleEvent(EVENT_TURN_TO_FACING_1, 4s);
                            events.ScheduleEvent(EVENT_SPAWN_WAVE, 3s);
                            break;
                        case EVENT_WAVES_TEXT_4:
                            Talk(SAY_BLACKHAND_1);
                            events.ScheduleEvent(EVENT_WAVES_EMOTE_2, 4s);
                            events.ScheduleEvent(EVENT_TURN_TO_FACING_3, 8s);
                            events.ScheduleEvent(EVENT_SPAWN_WAVE, 3s);
                            break;
                        case EVENT_WAVES_TEXT_5:
                            events.ScheduleEvent(EVENT_TURN_TO_PLAYER, 0);
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->AI()->Talk(SAY_NEFARIUS_5);
                            events.ScheduleEvent(EVENT_TURN_TO_FACING_1, 4s);
                            events.ScheduleEvent(EVENT_SPAWN_WAVE, 3s);
                            break;
                        case EVENT_WAVES_COMPLETE_TEXT_1:
                            events.ScheduleEvent(EVENT_TURN_TO_PLAYER, 0);
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->AI()->Talk(SAY_NEFARIUS_6);
                            events.ScheduleEvent(EVENT_TURN_TO_FACING_1, 4s);
                            events.ScheduleEvent(EVENT_WAVES_COMPLETE_TEXT_2, 13s);
                            break;
                        case EVENT_WAVES_COMPLETE_TEXT_2:
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->AI()->Talk(SAY_NEFARIUS_7);
                            Talk(SAY_BLACKHAND_2);
                            events.ScheduleEvent(EVENT_PATH_REND, 1s);
                            events.ScheduleEvent(EVENT_WAVES_COMPLETE_TEXT_3, 4s);
                            break;
                        case EVENT_WAVES_COMPLETE_TEXT_3:
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->AI()->Talk(SAY_NEFARIUS_8);
                            events.ScheduleEvent(EVENT_PATH_NEFARIUS, 1s);
                            events.ScheduleEvent(EVENT_PATH_REND, 1s);
                            break;
                        case EVENT_PATH_NEFARIUS:
                            if (Creature* victor = ObjectAccessor::GetCreature(*me, victorGUID))
                                victor->GetMotionMaster()->MovePath(NEFARIUS_PATH_1, true);
                            break;
                        case EVENT_PATH_REND:
                            me->GetMotionMaster()->MovePath(REND_PATH_1, false);
                            break;
                        case EVENT_TELEPORT_1:
                            me->NearTeleportTo(194.2993f, -474.0814f, 121.4505f, -0.01225555f);
                            events.ScheduleEvent(EVENT_TELEPORT_2, 13s);
                            break;
                        case EVENT_TELEPORT_2:
                            me->NearTeleportTo(216.485f, -434.93f, 110.888f, -0.01225555f);
                            me->SummonCreature(NPC_GYTH, 211.762f, -397.5885f, 111.1817f, 4.747295f);
                            break;
                        case EVENT_SPAWN_WAVE:
                            SummonWave();
                            break;
                        default:
                            break;
                    }
                }
            }
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            while (uint32 eventId = events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_WHIRLWIND:
                        DoCast(SPELL_WHIRLWIND);
                        events.ScheduleEvent(EVENT_WHIRLWIND, 13s, 18s);
                        break;
                    case EVENT_CLEAVE:
                        DoCastVictim(SPELL_CLEAVE);
                        events.ScheduleEvent(EVENT_CLEAVE, 10s, 14s);
                        break;
                    case EVENT_MORTAL_STRIKE:
                        DoCastVictim(SPELL_MORTAL_STRIKE);
                        events.ScheduleEvent(EVENT_MORTAL_STRIKE, 14s, 18s);
                        break;
                }
            }
            DoMeleeAttackIfReady();
        }
References DATA_VAELASTRASZ, DATA_WARCHIEF_REND_BLACKHAND, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_POINT, EMOTE_ONESHOT_QUESTION, EMOTE_ONESHOT_ROAR, EMOTE_ONESHOT_TALK, EVENT_CLEAVE, EVENT_MORTAL_STRIKE, EVENT_PATH_NEFARIUS, EVENT_PATH_REND, EVENT_SPAWN_WAVE, EVENT_START_1, EVENT_START_2, EVENT_START_3, EVENT_TELEPORT_1, EVENT_TELEPORT_2, EVENT_TURN_TO_FACING_1, EVENT_TURN_TO_FACING_2, EVENT_TURN_TO_FACING_3, EVENT_TURN_TO_PLAYER, EVENT_TURN_TO_REND, EVENT_WAVES_COMPLETE_TEXT_1, EVENT_WAVES_COMPLETE_TEXT_2, EVENT_WAVES_COMPLETE_TEXT_3, EVENT_WAVES_EMOTE_1, EVENT_WAVES_EMOTE_2, EVENT_WAVES_TEXT_1, EVENT_WAVES_TEXT_2, EVENT_WAVES_TEXT_3, EVENT_WAVES_TEXT_4, EVENT_WAVES_TEXT_5, EVENT_WHIRLWIND, ObjectAccessor::GetCreature(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetMotionMaster(), GO_GYTH_ENTRY_DOOR, GO_STATE_READY, gythEvent, Unit::HandleEmoteCommand(), Unit::HasUnitState(), IN_PROGRESS, BossAI::instance, ScriptedAI::me, MotionMaster::MovePath(), Unit::NearTeleportTo(), NEFARIUS_PATH_1, NOT_STARTED, NPC_GYTH, REND_PATH_1, SAY_BLACKHAND_1, SAY_BLACKHAND_2, SAY_NEFARIUS_0, SAY_NEFARIUS_1, SAY_NEFARIUS_2, SAY_NEFARIUS_3, SAY_NEFARIUS_4, SAY_NEFARIUS_5, SAY_NEFARIUS_6, SAY_NEFARIUS_7, SAY_NEFARIUS_8, WorldObject::SelectNearestPlayer(), InstanceScript::SetBossState(), ZoneScript::SetData(), Unit::SetFacingTo(), SPELL_CLEAVE, SPELL_MORTAL_STRIKE, SPELL_WHIRLWIND, WorldObject::SummonCreature(), SummonWave(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and victorGUID.
Member Data Documentation
_currentWave
uint8 boss_rend_blackhand::boss_rend_blackhandAI::_currentWave private
Referenced by Reset(), SummonedCreatureDies(), and SummonWave().
gythEvent
bool boss_rend_blackhand::boss_rend_blackhandAI::gythEvent private
Referenced by Reset(), SetData(), and UpdateAI().
victorGUID
ObjectGuid boss_rend_blackhand::boss_rend_blackhandAI::victorGUID private
Referenced by Reset(), SetData(), and UpdateAI().
waveDoorGUID
ObjectGuid boss_rend_blackhand::boss_rend_blackhandAI::waveDoorGUID private
Referenced by Reset(), SetData(), and SummonWave().