AzerothCore: npc_akama_illidan::npc_akama_illidanAI Struct Reference
npc_akama_illidan::npc_akama_illidanAI Struct Reference
Public Member Functions
npc_akama_illidanAI (Creature *creature)
void DoAction (int32 param) override
void Reset () override
void sGossipSelect (Player *player, uint32, uint32) override
void PathEndReached (uint32 pathId) override
void JustSummoned (Creature *summon) override
void WaypointReached (uint32 pointId) override
void MoveInLineOfSight (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateEscortAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
virtual void HealDone (Unit *, uint32 &)
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap events
SummonList summons
InstanceScript * instance
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_akama_illidanAI()
npc_akama_illidan::npc_akama_illidanAI::npc_akama_illidanAI (Creature * creature) inline
                                                : npc_escortAI(creature), summons(me)
        {
            instance = creature->GetInstanceScript();
            if (instance->GetBossState(DATA_AKAMA_ILLIDAN) == DONE)
            {
                me->GetMap()->LoadGrid(751.664f, 238.933f);
                me->SetHomePosition(751.664f, 238.933f, 353.106f, 2.18f);
                me->NearTeleportTo(751.664f, 238.933f, 353.106f, 2.18f);
            }
        }
References DATA_AKAMA_ILLIDAN, DONE, InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), instance, Map::LoadGrid(), ScriptedAI::me, Unit::NearTeleportTo(), and Creature::SetHomePosition().
Member Function Documentation
DamageTaken()
void npc_akama_illidan::npc_akama_illidanAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (damage >= me->GetHealth())
                damage = 0;
        }
References Unit::GetHealth(), and ScriptedAI::me.
DoAction()
void npc_akama_illidan::npc_akama_illidanAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_FIGHT_MINIONS)
            {
                me->CombatStop(true);
                events.ScheduleEvent(EVENT_AKAMA_SUMMON_ILLIDARI, 8000);
                events.ScheduleEvent(EVENT_AKAMA_SPELL_CHAIN, 7000);
                events.ScheduleEvent(EVENT_AKAMA_HEALTH, 1000);
                me->GetMotionMaster()->MoveCharge(741.97f, 358.74f, 353.0f, 10.0f, POINT_FIGHT_MINIONS);
                Talk(SAY_AKAMA_LEAVE);
            }
            else if (param == ACTION_ILLIDAN_DEAD)
            {
                events.Reset();
                summons.DespawnAll();
                me->CombatStop(true);
            }
            else if (param == ACTION_ILLIDARI_COUNCIL_DONE)
            {
                me->NearTeleportTo(AkamaTeleport);
                me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                me->GetMotionMaster()->MovePath(PATH_AKAMA_ILLIDARI_COUNCIL_1, false);
            }
        }
References ACTION_FIGHT_MINIONS, ACTION_ILLIDAN_DEAD, ACTION_ILLIDARI_COUNCIL_DONE, AkamaTeleport, Unit::CombatStop(), SummonList::DespawnAll(), EVENT_AKAMA_HEALTH, EVENT_AKAMA_SPELL_CHAIN, EVENT_AKAMA_SUMMON_ILLIDARI, Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MoveCharge(), MotionMaster::MovePath(), Unit::NearTeleportTo(), PATH_AKAMA_ILLIDARI_COUNCIL_1, POINT_FIGHT_MINIONS, Unit::RemoveNpcFlag(), SAY_AKAMA_LEAVE, summons, and UNIT_NPC_FLAG_GOSSIP.
JustSummoned()
void npc_akama_illidan::npc_akama_illidanAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(summon);
            summon->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
            if (summon->GetEntry() == NPC_ILLIDARI_ELITE)
            {
                me->AddThreat(summon, 1000000.0f);
                summon->AddThreat(me, 1000000.0f);
                summon->AI()->AttackStart(me);
                AttackStart(summon);
            }
        }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), npc_escortAI::AttackStart(), Object::GetEntry(), ScriptedAI::me, NPC_ILLIDARI_ELITE, Unit::ReplaceAllNpcFlags(), SummonList::Summon(), summons, and UNIT_NPC_FLAG_NONE.
MoveInLineOfSight()
void npc_akama_illidan::npc_akama_illidanAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from npc_escortAI.
{ }
PathEndReached()
void npc_akama_illidan::npc_akama_illidanAI::PathEndReached (uint32 pathId) inline override virtual
Reimplemented from CreatureAI.
        {
            if (pathId == PATH_AKAMA_ILLIDARI_COUNCIL_1)
            {
                ScheduleUniqueTimedEvent(200ms, [&]
                {
                    Talk(SAY_AKAMA_COUNCIL_1);
                }, 1);
                ScheduleUniqueTimedEvent(7800ms, [&]
                {
                    Talk(SAY_AKAMA_COUNCIL_2);
                    me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                }, 2);
            }
        }
References ScriptedAI::me, PATH_AKAMA_ILLIDARI_COUNCIL_1, SAY_AKAMA_COUNCIL_1, SAY_AKAMA_COUNCIL_2, ScriptedAI::ScheduleUniqueTimedEvent(), Unit::SetNpcFlag(), and UNIT_NPC_FLAG_GOSSIP.
Reset()
void npc_akama_illidan::npc_akama_illidanAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            me->SetReactState(REACT_AGGRESSIVE);
            me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            me->setActive(false);
            events.Reset();
            summons.DespawnAll();
        }
References SummonList::DespawnAll(), ScriptedAI::me, REACT_AGGRESSIVE, WorldObject::setActive(), Unit::SetNpcFlag(), Creature::SetReactState(), summons, and UNIT_NPC_FLAG_GOSSIP.
sGossipSelect()
void npc_akama_illidan::npc_akama_illidanAI::sGossipSelect (Player * player, uint32 , uint32) inline override virtual
Reimplemented from UnitAI.
        {
            CloseGossipMenuFor(player);
            me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
            me->setActive(true);
            if (instance->GetBossState(DATA_AKAMA_ILLIDAN) != DONE)
            {
                me->SetReactState(REACT_PASSIVE);
                Start(false, true);
                SetDespawnAtEnd(false);
            }
            else
            {
                me->GetMotionMaster()->MovePoint(POINT_ILLIDAN, 744.45f, 304.84f, 353.0f);
                events.Reset();
                events.ScheduleEvent(EVENT_AKAMA_SCENE_20, 5000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_21, 8000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_22, 10000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_23, 23000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_24, 34000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_25, 41000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_26, 46000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_27, 49000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_28, 49200);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_29, 52000);
            }
        }
References CloseGossipMenuFor(), DATA_AKAMA_ILLIDAN, DONE, EVENT_AKAMA_SCENE_20, EVENT_AKAMA_SCENE_21, EVENT_AKAMA_SCENE_22, EVENT_AKAMA_SCENE_23, EVENT_AKAMA_SCENE_24, EVENT_AKAMA_SCENE_25, EVENT_AKAMA_SCENE_26, EVENT_AKAMA_SCENE_27, EVENT_AKAMA_SCENE_28, EVENT_AKAMA_SCENE_29, InstanceScript::GetBossState(), Unit::GetMotionMaster(), instance, ScriptedAI::me, MotionMaster::MovePoint(), POINT_ILLIDAN, REACT_PASSIVE, Unit::ReplaceAllNpcFlags(), WorldObject::setActive(), npc_escortAI::SetDespawnAtEnd(), Creature::SetReactState(), npc_escortAI::Start(), and UNIT_NPC_FLAG_NONE.
UpdateEscortAI()
void npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
        {
            scheduler.Update(diff);
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_AKAMA_SCENE_1:
                    me->SetFacingTo(0.0f);
                    break;
                case EVENT_AKAMA_SCENE_2:
                    Talk(SAY_AKAMA_DOORS);
                    break;
                case EVENT_AKAMA_SCENE_3:
                    me->CastSpell(me, SPELL_AKAMA_DOOR_FAIL, false);
                    break;
                case EVENT_AKAMA_SCENE_4:
                    Talk(SAY_AKAMA_FAIL);
                    break;
                case EVENT_AKAMA_SCENE_5:
                    me->SummonCreature(NPC_SPIRIT_OF_UDALO, me->GetPositionX() - 5.0f, me->GetPositionY() + 8.0f, me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000);
                    me->SummonCreature(NPC_SPIRIT_OF_OLUM, me->GetPositionX() - 5.0f, me->GetPositionY() - 8.0f, me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000);
                    break;
                case EVENT_AKAMA_SCENE_6:
                    if (Creature* udalo = me->FindNearestCreature(NPC_SPIRIT_OF_UDALO, 15.0f))
                        udalo->AI()->Talk(SAY_UDALO);
                    break;
                case EVENT_AKAMA_SCENE_7:
                    if (Creature* olum = me->FindNearestCreature(NPC_SPIRIT_OF_OLUM, 15.0f))
                        olum->AI()->Talk(SAY_OLUM);
                    break;
                case EVENT_AKAMA_SCENE_8:
                    me->CastSpell(me, SPELL_AKAMA_DOOR_OPEN, false);
                    if (Creature* olum = me->FindNearestCreature(NPC_SPIRIT_OF_OLUM, 15.0f))
                        olum->CastSpell(olum, SPELL_AKAMA_DOOR_OPEN, false);
                    if (Creature* udalo = me->FindNearestCreature(NPC_SPIRIT_OF_UDALO, 15.0f))
                        udalo->CastSpell(udalo, SPELL_AKAMA_DOOR_OPEN, false);
                    break;
                case EVENT_AKAMA_SCENE_9:
                    instance->SetBossState(DATA_AKAMA_ILLIDAN, NOT_STARTED);
                    instance->SetBossState(DATA_AKAMA_ILLIDAN, DONE);
                    break;
                case EVENT_AKAMA_SCENE_10:
                    Talk(SAY_AKAMA_BEWARE);
                    break;
                case EVENT_AKAMA_SCENE_11:
                    SetEscortPaused(false);
                    break;
                case EVENT_AKAMA_SCENE_20:
                    if (Creature* illidan = instance->GetCreature(DATA_ILLIDAN_STORMRAGE))
                        illidan->SetStandState(UNIT_STAND_STATE_STAND);
                    break;
                case EVENT_AKAMA_SCENE_21:
                    me->SetFacingTo(M_PI);
                    break;
                case EVENT_AKAMA_SCENE_22:
                    if (Creature* illidan = instance->GetCreature(DATA_ILLIDAN_STORMRAGE))
                        illidan->AI()->Talk(SAY_ILLIDAN_AKAMA1);
                    break;
                case EVENT_AKAMA_SCENE_23:
                    Talk(SAY_AKAMA_ILLIDAN1);
                    break;
                case EVENT_AKAMA_SCENE_24:
                    if (Creature* illidan = instance->GetCreature(DATA_ILLIDAN_STORMRAGE))
                        illidan->AI()->Talk(SAY_ILLIDAN_AKAMA2);
                    break;
                case EVENT_AKAMA_SCENE_25:
                    Talk(SAY_AKAMA_ILLIDAN2);
                    break;
                case EVENT_AKAMA_SCENE_26:
                    if (Creature* illidan = instance->GetCreature(DATA_ILLIDAN_STORMRAGE))
                        illidan->AI()->Talk(SAY_ILLIDAN_AKAMA3);
                    break;
                case EVENT_AKAMA_SCENE_27:
                    if (Creature* illidan = instance->GetCreature(DATA_ILLIDAN_STORMRAGE))
                        illidan->LoadEquipment(1, true);
                    break;
                case EVENT_AKAMA_SCENE_28:
                    if (Creature* illidan = instance->GetCreature(DATA_ILLIDAN_STORMRAGE))
                        illidan->HandleEmoteCommand(EMOTE_ONESHOT_TALK_NO_SHEATHE);
                    break;
                case EVENT_AKAMA_SCENE_29:
                    if (Creature* illidan = instance->GetCreature(DATA_ILLIDAN_STORMRAGE))
                    {
                        illidan->SetImmuneToAll(false);
                        illidan->SetInCombatWithZone();
                        AttackStart(illidan);
                    }
                    break;
                case EVENT_AKAMA_SUMMON_ILLIDARI:
                    me->SummonCreature(NPC_ILLIDARI_ELITE, 742.55f, 359.12f, 353.0f, 4.35f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30000);
                    events.ScheduleEvent(EVENT_AKAMA_SUMMON_ILLIDARI, urand(2000, 6000));
                    break;
                case EVENT_AKAMA_SPELL_CHAIN:
                    if (me->GetVictim())
                        me->CastSpell(me->GetVictim(), SPELL_CHAIN_LIGHTNING, false);
                    events.ScheduleEvent(EVENT_AKAMA_SPELL_CHAIN, 20000);
                    break;
                case EVENT_AKAMA_HEALTH:
                    if (me->HealthBelowPct(20))
                        me->CastSpell(me, SPELL_HEALING_POTION, false);
                    events.ScheduleEvent(EVENT_AKAMA_HEALTH, 1000);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References npc_escortAI::AttackStart(), Unit::CastSpell(), DATA_AKAMA_ILLIDAN, DATA_ILLIDAN_STORMRAGE, UnitAI::DoMeleeAttackIfReady(), DONE, EMOTE_ONESHOT_TALK_NO_SHEATHE, EVENT_AKAMA_HEALTH, EVENT_AKAMA_SCENE_1, EVENT_AKAMA_SCENE_10, EVENT_AKAMA_SCENE_11, EVENT_AKAMA_SCENE_2, EVENT_AKAMA_SCENE_20, EVENT_AKAMA_SCENE_21, EVENT_AKAMA_SCENE_22, EVENT_AKAMA_SCENE_23, EVENT_AKAMA_SCENE_24, EVENT_AKAMA_SCENE_25, EVENT_AKAMA_SCENE_26, EVENT_AKAMA_SCENE_27, EVENT_AKAMA_SCENE_28, EVENT_AKAMA_SCENE_29, EVENT_AKAMA_SCENE_3, EVENT_AKAMA_SCENE_4, EVENT_AKAMA_SCENE_5, EVENT_AKAMA_SCENE_6, EVENT_AKAMA_SCENE_7, EVENT_AKAMA_SCENE_8, EVENT_AKAMA_SCENE_9, EVENT_AKAMA_SPELL_CHAIN, EVENT_AKAMA_SUMMON_ILLIDARI, WorldObject::FindNearestCreature(), InstanceScript::GetCreature(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HealthBelowPct(), instance, ScriptedAI::me, NOT_STARTED, NPC_ILLIDARI_ELITE, NPC_SPIRIT_OF_OLUM, NPC_SPIRIT_OF_UDALO, SAY_AKAMA_BEWARE, SAY_AKAMA_DOORS, SAY_AKAMA_FAIL, SAY_AKAMA_ILLIDAN1, SAY_AKAMA_ILLIDAN2, SAY_ILLIDAN_AKAMA1, SAY_ILLIDAN_AKAMA2, SAY_ILLIDAN_AKAMA3, SAY_OLUM, SAY_UDALO, CreatureAI::scheduler, InstanceScript::SetBossState(), npc_escortAI::SetEscortPaused(), Unit::SetFacingTo(), SPELL_AKAMA_DOOR_FAIL, SPELL_AKAMA_DOOR_OPEN, SPELL_CHAIN_LIGHTNING, SPELL_HEALING_POTION, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_STAND_STATE_STAND, TaskScheduler::Update(), and urand().
WaypointReached()
void npc_akama_illidan::npc_akama_illidanAI::WaypointReached (uint32 pointId) inline override virtual
Implements npc_escortAI.
        {
            if (pointId == POINT_DOORS)
            {
                SetEscortPaused(true);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_1, 0);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_2, 4000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_3, 7000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_4, 17000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_5, 23000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_6, 25000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_7, 31000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_8, 40000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_9, 54000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_10, 57000);
                events.ScheduleEvent(EVENT_AKAMA_SCENE_11, 62000);
            }
            else if (pointId == POINT_ILLIDAN)
            {
                me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_GOSSIP);
                me->setActive(false);
                me->SetReactState(REACT_AGGRESSIVE);
            }
        }
References EVENT_AKAMA_SCENE_1, EVENT_AKAMA_SCENE_10, EVENT_AKAMA_SCENE_11, EVENT_AKAMA_SCENE_2, EVENT_AKAMA_SCENE_3, EVENT_AKAMA_SCENE_4, EVENT_AKAMA_SCENE_5, EVENT_AKAMA_SCENE_6, EVENT_AKAMA_SCENE_7, EVENT_AKAMA_SCENE_8, EVENT_AKAMA_SCENE_9, ScriptedAI::me, POINT_DOORS, POINT_ILLIDAN, REACT_AGGRESSIVE, Unit::ReplaceAllNpcFlags(), WorldObject::setActive(), npc_escortAI::SetEscortPaused(), Creature::SetReactState(), and UNIT_NPC_FLAG_GOSSIP.
Member Data Documentation
events
EventMap npc_akama_illidan::npc_akama_illidanAI::events private
instance
InstanceScript* npc_akama_illidan::npc_akama_illidanAI::instance private
Referenced by npc_akama_illidanAI(), sGossipSelect(), and UpdateEscortAI().
summons
SummonList npc_akama_illidan::npc_akama_illidanAI::summons private
Referenced by DoAction(), JustSummoned(), and Reset().