AzerothCore: npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI Struct Reference
npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI Struct Reference
Public Member Functions
npc_brann_bronzebeard_algalonAI (Creature *creature)
void DoAction (int32 action) override
void MovementInform (uint32 movementType, uint32 pointId) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
uint32 _currentPoint
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_brann_bronzebeard_algalonAI()
npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::npc_brann_bronzebeard_algalonAI (Creature * creature) inline
                                                            : CreatureAI(creature)
        {
        }
Member Function Documentation
DoAction()
void npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            switch (action)
            {
                case ACTION_START_INTRO:
                    me->SetWalk(false);
                    _currentPoint = 0;
                    events.Reset();
                    events.ScheduleEvent(EVENT_BRANN_MOVE_INTRO, 1ms);
                    break;
                case ACTION_FINISH_INTRO:
                    Talk(SAY_BRANN_ALGALON_INTRO_2);
                    events.ScheduleEvent(EVENT_BRANN_MOVE_INTRO, 1ms);
                    break;
                case ACTION_OUTRO:
                    me->GetMotionMaster()->MovePoint(POINT_BRANN_OUTRO, BrannOutroPos[1]);
                    events.ScheduleEvent(EVENT_BRANN_OUTRO_1, 87s + 500ms);
                    events.ScheduleEvent(EVENT_BRANN_OUTRO_2, 116s + 500ms);
                    break;
            }
        }
References _currentPoint, ACTION_FINISH_INTRO, ACTION_OUTRO, ACTION_START_INTRO, BrannOutroPos, EVENT_BRANN_MOVE_INTRO, EVENT_BRANN_OUTRO_1, EVENT_BRANN_OUTRO_2, Unit::GetMotionMaster(), CreatureAI::me, MotionMaster::MovePoint(), POINT_BRANN_OUTRO, SAY_BRANN_ALGALON_INTRO_2, and Creature::SetWalk().
MovementInform()
void npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::MovementInform (uint32 movementType, uint32 pointId) inline override virtual
Reimplemented from CreatureAI.
        {
            if (movementType != POINT_MOTION_TYPE)
                return;
            uint32 delay = 1;
            _currentPoint = pointId + 1;
            switch (pointId)
            {
                case 2:
                    delay = 8000;
                    me->SetWalk(true);
                    break;
                case 6:
                    me->SetFacingTo(4.6156f);
                    me->SetWalk(false);
                    Talk(SAY_BRANN_ALGALON_INTRO_1);
                    events.ScheduleEvent(EVENT_SUMMON_ALGALON, 7500ms);
                    return;
                case 10:
                    me->DespawnOrUnsummon(1);
                    return;
                case POINT_BRANN_OUTRO:
                case POINT_BRANN_OUTRO_END:
                    return;
            }
            events.ScheduleEvent(EVENT_BRANN_MOVE_INTRO, delay);
        }
References _currentPoint, Creature::DespawnOrUnsummon(), EVENT_BRANN_MOVE_INTRO, EVENT_SUMMON_ALGALON, CreatureAI::me, POINT_BRANN_OUTRO, POINT_BRANN_OUTRO_END, POINT_MOTION_TYPE, SAY_BRANN_ALGALON_INTRO_1, Unit::SetFacingTo(), and Creature::SetWalk().
UpdateAI()
void npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI (uint32 diff) inline override virtual
Implements UnitAI.
        {
            UpdateVictim();
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_BRANN_MOVE_INTRO:
                    if (_currentPoint < MAX_BRANN_WAYPOINTS_INTRO)
                        me->GetMotionMaster()->MovePoint(_currentPoint, BrannIntroWaypoint[_currentPoint]);
                    break;
                case EVENT_SUMMON_ALGALON:
                    if (me->GetInstanceScript() && !me->GetInstanceScript()->GetGuidData(TYPE_ALGALON))
                        if (Creature* algalon = me->GetMap()->SummonCreature(NPC_ALGALON, AlgalonSummonPos))
                            algalon->AI()->DoAction(ACTION_START_INTRO);
                    break;
                case EVENT_BRANN_OUTRO_1:
                    Talk(SAY_BRANN_ALGALON_OUTRO);
                    break;
                case EVENT_BRANN_OUTRO_2:
                    me->GetMotionMaster()->MovePoint(POINT_BRANN_OUTRO_END, BrannOutroPos[2]);
                    break;
            }
        }
References _currentPoint, ACTION_START_INTRO, AlgalonSummonPos, BrannIntroWaypoint, BrannOutroPos, EVENT_BRANN_MOVE_INTRO, EVENT_BRANN_OUTRO_1, EVENT_BRANN_OUTRO_2, EVENT_SUMMON_ALGALON, InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), Unit::GetMotionMaster(), MAX_BRANN_WAYPOINTS_INTRO, CreatureAI::me, MotionMaster::MovePoint(), NPC_ALGALON, POINT_BRANN_OUTRO_END, SAY_BRANN_ALGALON_OUTRO, Map::SummonCreature(), TYPE_ALGALON, and CreatureAI::UpdateVictim().
Member Data Documentation
_currentPoint
uint32 npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::_currentPoint
Referenced by DoAction(), MovementInform(), and UpdateAI().
events
EventMap npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::events