AzerothCore: spell_switch_infragreen_bomber_station Class Reference
spell_switch_infragreen_bomber_station Class Reference
Private Member Functions
PrepareSpellScript (spell_switch_infragreen_bomber_station)
uint8 GetSeatNumber (uint32 spellId)
void HandleDummy (SpellEffIndex effIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
GetSeatNumber()
uint8 spell_switch_infragreen_bomber_station::GetSeatNumber (uint32 spellId) inline private
    {
        if (spellId == SPELL_ENGINEERING)
            return 2;
        else if (spellId == SPELL_ANTI_AIR_TURRET)
            return 1;
        else
            return 0;
    }
References SPELL_ANTI_AIR_TURRET, and SPELL_ENGINEERING.
Referenced by HandleDummy().
HandleDummy()
void spell_switch_infragreen_bomber_station::HandleDummy (SpellEffIndex effIndex) inline private
    {
        PreventHitDefaultEffect(effIndex);
        Vehicle* kit = GetCaster()->GetVehicle();
        Unit* charmer = GetCaster()->GetCharmer(); // Player controlling station
        if (!kit || !charmer)
            return;
        uint8 seatNumber = GetSeatNumber(GetSpellInfo()->Id);
        SeatMap::iterator itr = kit->GetSeatIteratorForPassenger(GetCaster());
        if (itr == kit->Seats.end())
            return;
        // Xinef: Same seat, no change required
        if (seatNumber == itr->first)
            return;
        if (Unit* station = kit->GetPassenger(seatNumber))
            station->HandleSpellClick(charmer, 0);
    }
References SpellScript::GetCaster(), Unit::GetCharmer(), Vehicle::GetPassenger(), Vehicle::GetSeatIteratorForPassenger(), GetSeatNumber(), SpellScript::GetSpellInfo(), Unit::GetVehicle(), SpellScript::PreventHitDefaultEffect(), and Vehicle::Seats.
Referenced by Register().
PrepareSpellScript()
spell_switch_infragreen_bomber_station::PrepareSpellScript (spell_switch_infragreen_bomber_station) private
Register()
void spell_switch_infragreen_bomber_station::Register () inline override private virtual
Implements _SpellScript.
    {
        OnEffectHitTarget += SpellEffectFn(spell_switch_infragreen_bomber_station::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
References EFFECT_0, HandleDummy(), SpellScript::OnEffectHitTarget, SPELL_EFFECT_DUMMY, and SpellEffectFn.