AzerothCore: boss_ingvar_the_plunderer Struct Reference
boss_ingvar_the_plunderer Struct Reference
Public Member Functions
boss_ingvar_the_plunderer (Creature *c)
void Reset () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustSummoned (Creature *s) override
void KilledUnit (Unit *) override
void FeignDeath (bool apply)
void JustDied (Unit *) override
void EnterEvadeMode (EvadeReason why) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
ObjectGuid ValkyrGUID
ObjectGuid ThrowGUID
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_ingvar_the_plunderer()
boss_ingvar_the_plunderer::boss_ingvar_the_plunderer (Creature * c) inline
                                           : ScriptedAI(c), summons(me)
    {
        pInstance = c->GetInstanceScript();
    }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
DamageTaken()
void boss_ingvar_the_plunderer::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
    {
        if (me->GetDisplayId() == DISPLAYID_DEFAULT && damage >= me->GetHealth())
        {
            damage = 0;
            me->InterruptNonMeleeSpells(true);
            me->RemoveAllAuras();
            me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            me->SetControlled(false, UNIT_STATE_ROOT);
            me->DisableRotate(false);
            me->GetMotionMaster()->MovementExpired();
            me->GetMotionMaster()->MoveIdle();
            me->StopMoving();
            FeignDeath(true);
            events.Reset();
            events.RescheduleEvent(EVENT_START_RESURRECTION, 1s);
            events.RescheduleEvent(EVENT_YELL_DEAD_1, 0ms);
        }
    }
References Unit::DisableRotate(), DISPLAYID_DEFAULT, EVENT_START_RESURRECTION, EVENT_YELL_DEAD_1, FeignDeath(), Unit::GetDisplayId(), Unit::GetHealth(), Unit::GetMotionMaster(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovementExpired(), Unit::RemoveAllAuras(), Unit::SetControlled(), Unit::SetUnitFlag(), Unit::StopMoving(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_STATE_ROOT.
EnterEvadeMode()
void boss_ingvar_the_plunderer::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
    {
        me->SetControlled(false, UNIT_STATE_ROOT);
        me->DisableRotate(false);
        ScriptedAI::EnterEvadeMode(why);
    }
References Unit::DisableRotate(), CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
FeignDeath()
void boss_ingvar_the_plunderer::FeignDeath (bool apply) inline
    {
        if (apply)
        {
            me->SetStandState(UNIT_STAND_STATE_DEAD);
            me->SetUnitFlag(UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT);
            me->SetUnitFlag2(UNIT_FLAG2_FEIGN_DEATH);
            me->SetDynamicFlag(UNIT_DYNFLAG_DEAD);
        }
        else
        {
            me->SetStandState(UNIT_STAND_STATE_STAND);
            me->RemoveUnitFlag(UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT);
            me->RemoveUnitFlag2(UNIT_FLAG2_FEIGN_DEATH);
            me->RemoveDynamicFlag(UNIT_DYNFLAG_DEAD);
        }
    }
References ScriptedAI::me, Object::RemoveDynamicFlag(), Unit::RemoveUnitFlag(), Unit::RemoveUnitFlag2(), Object::SetDynamicFlag(), Unit::SetStandState(), Unit::SetUnitFlag(), Unit::SetUnitFlag2(), UNIT_DYNFLAG_DEAD, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT, UNIT_STAND_STATE_DEAD, and UNIT_STAND_STATE_STAND.
Referenced by DamageTaken(), Reset(), and UpdateAI().
JustDied()
void boss_ingvar_the_plunderer::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        events.Reset();
        summons.DespawnAll();
        Talk(YELL_DEAD_2);
        if (pInstance)
        {
            pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, NPC_INGVAR_UNDEAD, 1); // undead entry needed for achievements
            pInstance->SetData(DATA_INGVAR, DONE);
        }
    }
References ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, DATA_INGVAR, SummonList::DespawnAll(), DONE, InstanceScript::DoUpdateAchievementCriteria(), NPC_INGVAR_UNDEAD, pInstance, ZoneScript::SetData(), summons, and YELL_DEAD_2.
JustEngagedWith()
void boss_ingvar_the_plunderer::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
    {
        events.Reset();
        // schedule Phase 1 abilities
        events.RescheduleEvent(EVENT_SPELL_ROAR, 15s);
        events.RescheduleEvent(EVENT_SPELL_CLEAVE_OR_WOE_STRIKE, 2s);
        events.RescheduleEvent(EVENT_SPELL_SMASH, 5s);
        events.RescheduleEvent(EVENT_SPELL_ENRAGE_OR_SHADOW_AXE, 10s);
        Talk(YELL_AGGRO_1);
        me->LowerPlayerDamageReq(me->GetMaxHealth());
        if (pInstance)
            pInstance->SetData(DATA_INGVAR, IN_PROGRESS);
    }
References DATA_INGVAR, EVENT_SPELL_CLEAVE_OR_WOE_STRIKE, EVENT_SPELL_ENRAGE_OR_SHADOW_AXE, EVENT_SPELL_ROAR, EVENT_SPELL_SMASH, Unit::GetMaxHealth(), IN_PROGRESS, Creature::LowerPlayerDamageReq(), ScriptedAI::me, pInstance, ZoneScript::SetData(), and YELL_AGGRO_1.
JustSummoned()
void boss_ingvar_the_plunderer::JustSummoned (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
    {
        summons.Summon(s);
        if (s->GetEntry() == NPC_ANNHYLDE)
        {
            ValkyrGUID = s->GetGUID();
            s->SetCanFly(true);
            s->SetDisableGravity(true);
            s->SetPosition(s->GetPositionX(), s->GetPositionY(), s->GetPositionZ() + 35.0f, s->GetOrientation());
            s->SetFacingTo(s->GetOrientation());
        }
        else if (s->GetEntry() == NPC_THROW)
        {
            ThrowGUID = s->GetGUID();
            if (Unit* t = SelectTarget(SelectTargetMethod::Random, 0, 70.0f, true))
                s->GetMotionMaster()->MovePoint(0, t->GetPositionX(), t->GetPositionY(), t->GetPositionZ());
        }
    }
References Object::GetEntry(), Object::GetGUID(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), MotionMaster::MovePoint(), NPC_ANNHYLDE, NPC_THROW, UnitAI::SelectTarget(), Creature::SetCanFly(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Creature::SetPosition(), SummonList::Summon(), summons, ThrowGUID, and ValkyrGUID.
KilledUnit()
void boss_ingvar_the_plunderer::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (me->GetDisplayId() == DISPLAYID_DEFAULT)
            Talk(YELL_KILL_2);
        else
            Talk(YELL_KILL_1);
    }
References DISPLAYID_DEFAULT, Unit::GetDisplayId(), ScriptedAI::me, YELL_KILL_1, and YELL_KILL_2.
Reset()
void boss_ingvar_the_plunderer::Reset () inline override virtual
Reimplemented from ScriptedAI.
    {
        ValkyrGUID.Clear();
        ThrowGUID.Clear();
        events.Reset();
        summons.DespawnAll();
        me->SetDisplayId(DISPLAYID_DEFAULT);
        me->LoadEquipment(1);
        FeignDeath(false);
        me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        me->SetControlled(false, UNIT_STATE_ROOT);
        me->DisableRotate(false);
        if (pInstance)
            pInstance->SetData(DATA_INGVAR, NOT_STARTED);
    }
References ObjectGuid::Clear(), DATA_INGVAR, SummonList::DespawnAll(), Unit::DisableRotate(), DISPLAYID_DEFAULT, FeignDeath(), Creature::LoadEquipment(), ScriptedAI::me, NOT_STARTED, pInstance, Unit::RemoveUnitFlag(), Unit::SetControlled(), ZoneScript::SetData(), Creature::SetDisplayId(), summons, ThrowGUID, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_ROOT, and ValkyrGUID.
UpdateAI()
void boss_ingvar_the_plunderer::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
    {
        if (!UpdateVictim())
            return;
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
            return;
        switch (events.ExecuteEvent())
        {
        case 0:
            break;
        case EVENT_YELL_DEAD_1:
            Talk(YELL_DEAD_1);
            break;
        case EVENT_START_RESURRECTION:
            me->CastSpell(me, SPELL_SUMMON_VALKYR, true);
            events.RescheduleEvent(EVENT_VALKYR_BEAM, 7s);
            events.RescheduleEvent(EVENT_VALKYR_MOVE, 1ms);
            events.RescheduleEvent(EVENT_ANNHYLDE_YELL, 3s);
            break;
        case EVENT_VALKYR_MOVE:
            if (Creature* s = ObjectAccessor::GetCreature(*me, ValkyrGUID))
                s->GetMotionMaster()->MovePoint(1, s->GetPositionX(), s->GetPositionY(), s->GetPositionZ() - 15.0f);
            break;
        case EVENT_ANNHYLDE_YELL:
            if (Creature* s = ObjectAccessor::GetCreature(*me, ValkyrGUID))
                s->AI()->Talk(YELL_ANHYLDE_2);
            break;
        case EVENT_VALKYR_BEAM:
            me->RemoveAura(SPELL_SUMMON_VALKYR);
            if (Creature* c = ObjectAccessor::GetCreature(*me, ValkyrGUID))
                c->CastSpell(me, SPELL_RESURRECTION_BEAM, false);
            events.RescheduleEvent(EVENT_RESURRECTION_BALL, 4s);
            break;
        case EVENT_RESURRECTION_BALL:
            me->CastSpell(me, SPELL_RESURRECTION_BALL, true);
            events.RescheduleEvent(EVENT_RESURRECTION_HEAL, 4s);
            break;
        case EVENT_RESURRECTION_HEAL:
            me->RemoveAura(SPELL_RESURRECTION_BALL);
            me->CastSpell(me, SPELL_RESURRECTION_HEAL, true);
            FeignDeath(false);
            events.RescheduleEvent(EVENT_MORPH_TO_UNDEAD, 3s);
            break;
        case EVENT_MORPH_TO_UNDEAD:
            me->CastSpell(me, SPELL_INGVAR_TRANSFORM, true);
            events.RescheduleEvent(EVENT_START_PHASE_2, 1s);
            break;
        case EVENT_START_PHASE_2:
            if (Creature* c = ObjectAccessor::GetCreature(*me, ValkyrGUID))
            {
                c->DespawnOrUnsummon();
                summons.DespawnAll();
            }
            me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            AttackStart(me->GetVictim());
            me->GetMotionMaster()->MoveChase(me->GetVictim());
            Talk(YELL_AGGRO_2);
            // schedule Phase 2 abilities
            events.RescheduleEvent(EVENT_SPELL_ROAR, 15s);
            events.RescheduleEvent(EVENT_SPELL_CLEAVE_OR_WOE_STRIKE, 2s);
            events.RescheduleEvent(EVENT_SPELL_SMASH, 5s);
            events.RescheduleEvent(EVENT_SPELL_ENRAGE_OR_SHADOW_AXE, 10s);
            break;
            // ABILITIES HERE:
        case EVENT_UNROOT:
            me->SetControlled(false, UNIT_STATE_ROOT);
            me->DisableRotate(false);
            break;
        case EVENT_SPELL_ROAR:
            Talk(EMOTE_ROAR);
            me->_AddCreatureSpellCooldown(SPELL_STAGGERING_ROAR, 0, 0);
            me->_AddCreatureSpellCooldown(SPELL_DREADFUL_ROAR, 0, 0);
            if (me->GetDisplayId() == DISPLAYID_DEFAULT)
                me->CastSpell((Unit*)nullptr, SPELL_STAGGERING_ROAR, false);
            else
                me->CastSpell((Unit*)nullptr, SPELL_DREADFUL_ROAR, false);
            events.Repeat(15s, 20s);
            break;
        case EVENT_SPELL_CLEAVE_OR_WOE_STRIKE:
            if (me->GetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID) == 0)
            {
                events.Repeat(3s);
                break;
            }
            if (me->GetDisplayId() == DISPLAYID_DEFAULT)
                me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
            else
                me->CastSpell(me->GetVictim(), SPELL_WOE_STRIKE, false);
            events.Repeat(3s, 7s);
            break;
        case EVENT_SPELL_SMASH:
            if (me->GetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID) == 0)
            {
                events.Repeat(3s);
                break;
            }
            me->SetControlled(true, UNIT_STATE_ROOT);
            me->DisableRotate(true);
            me->SendMovementFlagUpdate();
            if (me->GetDisplayId() == DISPLAYID_DEFAULT)
                me->CastSpell((Unit*)nullptr, SPELL_SMASH, false);
            else
                me->CastSpell((Unit*)nullptr, SPELL_DARK_SMASH, false);
            events.Repeat(9s, 11s);
            events.RescheduleEvent(EVENT_UNROOT, 3750ms);
            break;
        case EVENT_SPELL_ENRAGE_OR_SHADOW_AXE:
            if (me->GetDisplayId() == DISPLAYID_DEFAULT)
            {
                me->CastSpell(me, SPELL_ENRAGE, false);
                events.Repeat(10s);
            }
            else
            {
                me->CastSpell((Unit*)nullptr, SPELL_SHADOW_AXE, true);
                SetEquipmentSlots(false, EQUIP_UNEQUIP, EQUIP_NO_CHANGE, EQUIP_NO_CHANGE);
                events.Repeat(35s);
                events.RescheduleEvent(EVENT_AXE_RETURN, 10s);
            }
            break;
        case EVENT_AXE_RETURN:
            if (Creature* c = ObjectAccessor::GetCreature(*me, ThrowGUID))
                c->GetMotionMaster()->MoveCharge(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
            events.RescheduleEvent(EVENT_AXE_PICKUP, 1500ms);
            break;
        case EVENT_AXE_PICKUP:
            if (Creature* c = ObjectAccessor::GetCreature(*me, ThrowGUID))
            {
                c->DestroyForNearbyPlayers();
                c->DespawnOrUnsummon();
                summons.DespawnAll();
            }
            ThrowGUID.Clear();
            SetEquipmentSlots(true);
            break;
        }
        if (!me->HasUnitFlag(UNIT_FLAG_NOT_SELECTABLE))
            DoMeleeAttackIfReady();
    }
References Creature::_AddCreatureSpellCooldown(), ScriptedAI::AttackStart(), Unit::CastSpell(), ObjectGuid::Clear(), SummonList::DespawnAll(), Unit::DisableRotate(), DISPLAYID_DEFAULT, UnitAI::DoMeleeAttackIfReady(), EMOTE_ROAR, EQUIP_NO_CHANGE, EQUIP_UNEQUIP, EVENT_ANNHYLDE_YELL, EVENT_AXE_PICKUP, EVENT_AXE_RETURN, EVENT_MORPH_TO_UNDEAD, EVENT_RESURRECTION_BALL, EVENT_RESURRECTION_HEAL, EVENT_SPELL_CLEAVE_OR_WOE_STRIKE, EVENT_SPELL_ENRAGE_OR_SHADOW_AXE, EVENT_SPELL_ROAR, EVENT_SPELL_SMASH, EVENT_START_PHASE_2, EVENT_START_RESURRECTION, EVENT_UNROOT, EVENT_VALKYR_BEAM, EVENT_VALKYR_MOVE, EVENT_YELL_DEAD_1, FeignDeath(), ObjectAccessor::GetCreature(), Unit::GetDisplayId(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::GetUInt32Value(), Unit::GetVictim(), Unit::HasUnitFlag(), Unit::HasUnitState(), ScriptedAI::me, MotionMaster::MoveChase(), Unit::RemoveAura(), Unit::RemoveUnitFlag(), Unit::SendMovementFlagUpdate(), Unit::SetControlled(), ScriptedAI::SetEquipmentSlots(), SPELL_CLEAVE, SPELL_DARK_SMASH, SPELL_DREADFUL_ROAR, SPELL_ENRAGE, SPELL_INGVAR_TRANSFORM, SPELL_RESURRECTION_BALL, SPELL_RESURRECTION_BEAM, SPELL_RESURRECTION_HEAL, SPELL_SHADOW_AXE, SPELL_SMASH, SPELL_STAGGERING_ROAR, SPELL_SUMMON_VALKYR, SPELL_WOE_STRIKE, summons, ThrowGUID, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_CASTING, UNIT_STATE_ROOT, UNIT_VIRTUAL_ITEM_SLOT_ID, CreatureAI::UpdateVictim(), ValkyrGUID, YELL_AGGRO_2, YELL_ANHYLDE_2, and YELL_DEAD_1.
Member Data Documentation
events
EventMap boss_ingvar_the_plunderer::events
pInstance
InstanceScript* boss_ingvar_the_plunderer::pInstance
Referenced by boss_ingvar_the_plunderer(), JustDied(), JustEngagedWith(), and Reset().
summons
SummonList boss_ingvar_the_plunderer::summons
Referenced by JustDied(), JustSummoned(), Reset(), and UpdateAI().
ThrowGUID
ObjectGuid boss_ingvar_the_plunderer::ThrowGUID
Referenced by JustSummoned(), Reset(), and UpdateAI().
ValkyrGUID
ObjectGuid boss_ingvar_the_plunderer::ValkyrGUID
Referenced by JustSummoned(), Reset(), and UpdateAI().