AzerothCore: instance_forge_of_souls::instance_forge_of_souls_InstanceScript Struct Reference
instance_forge_of_souls::instance_forge_of_souls_InstanceScript Struct Reference
Public Member Functions
instance_forge_of_souls_InstanceScript (Map *map)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *) override
void OnCreatureCreate (Creature *creature) override
void HandleOutro ()
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 type) const override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
TeamId teamIdInInstance
std::string str_data
ObjectGuid NPC_BronjahmGUID
ObjectGuid NPC_DevourerGUID
ObjectGuid NPC_LeaderFirstGUID
ObjectGuid NPC_LeaderSecondGUID
ObjectGuid NPC_GuardFirstGUID
ObjectGuid NPC_GuardSecondGUID
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_forge_of_souls_InstanceScript()
instance_forge_of_souls::instance_forge_of_souls_InstanceScript::instance_forge_of_souls_InstanceScript (Map * map) inline
                                                         : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            LoadBossBoundaries(boundaries);
        }
References boundaries, DataHeader, InstanceScript::LoadBossBoundaries(), and InstanceScript::SetHeaders().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_forge_of_souls::instance_forge_of_souls_InstanceScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case 12752: // Soul Power
                    if (Creature* c = instance->GetCreature(NPC_BronjahmGUID))
                    {
                        std::list<Creature*> L;
                        uint8 count = 0;
                        c->GetCreaturesWithEntryInRange(L, 200.0f, 36535); // find all Corrupted Soul Fragment (36535)
                        for( std::list<Creature*>::const_iterator itr = L.begin(); itr != L.end(); ++itr )
                            if ((*itr)->IsAlive())
                                ++count;
                        return (count >= 4);
                    }
                    break;
                case 12976:
                    if (Creature* c = instance->GetCreature(NPC_DevourerGUID))
                        return (bool)c->AI()->GetData(1);
                    break;
            }
            return false;
        }
References Map::GetCreature(), InstanceScript::instance, NPC_BronjahmGUID, and NPC_DevourerGUID.
GetGuidData()
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case DATA_BRONJAHM:
                    return NPC_BronjahmGUID;
            }
            return ObjectGuid::Empty;
        }
References DATA_BRONJAHM, ObjectGuid::Empty, and NPC_BronjahmGUID.
HandleOutro()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::HandleOutro () inline
        {
            if (!NPC_LeaderSecondGUID || !instance->GetCreature(NPC_LeaderSecondGUID))
                if (Creature* leader = instance->SummonCreature(NPC_SYLVANAS_PART2, outroSpawnPoint))
                    if (Creature* boss = instance->GetCreature(NPC_DevourerGUID))
                    {
                        float angle = boss->GetAngle(leader);
                        leader->GetMotionMaster()->MovePoint(1, boss->GetPositionX() + 10.0f * cos(angle), boss->GetPositionY() + 10.0f * std::sin(angle), boss->GetPositionZ());
                    }
            for (int8 i = 0; outroPositions[i].entry[teamIdInInstance] != 0; ++i)
                if (Creature* summon = instance->SummonCreature(outroPositions[i].entry[teamIdInInstance], outroPositions[i].startPosition))
                    summon->GetMotionMaster()->MovePath(outroPositions[i].pathId, false);
        }
References outroPosition::entry, Map::GetCreature(), InstanceScript::instance, NPC_DevourerGUID, NPC_LeaderSecondGUID, NPC_SYLVANAS_PART2, outroPositions, outroSpawnPoint, outroPosition::startPosition, Map::SummonCreature(), and teamIdInInstance.
Referenced by SetData().
Initialize()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
            teamIdInInstance = TEAM_NEUTRAL;
        }
References m_auiEncounter, TEAM_NEUTRAL, and teamIdInInstance.
IsEncounterInProgress()
bool instance_forge_of_souls::instance_forge_of_souls_InstanceScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                if (m_auiEncounter[i] == IN_PROGRESS) return true;
            return false;
        }
References IN_PROGRESS, m_auiEncounter, and MAX_ENCOUNTER.
OnCreatureCreate()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            if (teamIdInInstance == TEAM_NEUTRAL)
            {
                Map::PlayerList const& players = instance->GetPlayers();
                if (!players.IsEmpty())
                    if (Player* player = players.begin()->GetSource())
                        teamIdInInstance = player->GetTeamId();
            }
            switch (creature->GetEntry())
            {
                case NPC_BRONJAHM:
                    NPC_BronjahmGUID = creature->GetGUID();
                    break;
                case NPC_DEVOURER:
                    NPC_DevourerGUID = creature->GetGUID();
                    break;
                case NPC_SYLVANAS_PART1:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_JAINA_PART1);
                    NPC_LeaderFirstGUID = creature->GetGUID();
                    if (m_auiEncounter[0] == DONE && m_auiEncounter[1] == DONE)
                        creature->SetVisible(false);
                    break;
                case NPC_SYLVANAS_PART2:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_JAINA_PART2);
                    NPC_LeaderSecondGUID = creature->GetGUID();
                    break;
                case NPC_LORALEN:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_ELANDRA);
                    if (!NPC_GuardFirstGUID)
                    {
                        NPC_GuardFirstGUID = creature->GetGUID();
                        if (m_auiEncounter[0] == DONE && m_auiEncounter[1] == DONE)
                            creature->SetVisible(false);
                    }
                    break;
                case NPC_KALIRA:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_KORELN);
                    if (!NPC_GuardSecondGUID)
                    {
                        NPC_GuardSecondGUID = creature->GetGUID();
                        if (m_auiEncounter[0] == DONE && m_auiEncounter[1] == DONE)
                            creature->SetVisible(false);
                    }
                    break;
            }
        }
References MapRefMgr::begin(), DONE, Object::GetEntry(), Object::GetGUID(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), InstanceScript::instance, LinkedListHead::IsEmpty(), m_auiEncounter, NPC_BRONJAHM, NPC_BronjahmGUID, NPC_DEVOURER, NPC_DevourerGUID, NPC_ELANDRA, NPC_GuardFirstGUID, NPC_GuardSecondGUID, NPC_JAINA_PART1, NPC_JAINA_PART2, NPC_KALIRA, NPC_KORELN, NPC_LeaderFirstGUID, NPC_LeaderSecondGUID, NPC_LORALEN, NPC_SYLVANAS_PART1, NPC_SYLVANAS_PART2, Unit::SetVisible(), TEAM_ALLIANCE, TEAM_NEUTRAL, teamIdInInstance, and Creature::UpdateEntry().
OnPlayerEnter()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnPlayerEnter (Player *) inline override virtual
Reimplemented from InstanceScript.
        {
            // this will happen only after crash and loading the instance from db
            if (m_auiEncounter[0] == DONE && m_auiEncounter[1] == DONE && (!NPC_LeaderSecondGUID || !instance->GetCreature(NPC_LeaderSecondGUID)))
            {
                Position pos = {5658.15f, 2502.564f, 708.83f, 0.885207f};
                instance->SummonCreature(NPC_SYLVANAS_PART2, pos);
            }
        }
References DONE, Map::GetCreature(), InstanceScript::instance, m_auiEncounter, NPC_LeaderSecondGUID, NPC_SYLVANAS_PART2, and Map::SummonCreature().
ReadSaveDataMore()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> m_auiEncounter[0];
            data >> m_auiEncounter[1];
        }
References m_auiEncounter.
SetData()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_BRONJAHM:
                    m_auiEncounter[type] = data;
                    break;
                case DATA_DEVOURER:
                    m_auiEncounter[type] = data;
                    if (m_auiEncounter[0] == DONE && m_auiEncounter[1] == DONE)
                        HandleOutro();
                    break;
            }
            if (data == DONE)
                SaveToDB();
        }
References DATA_BRONJAHM, DATA_DEVOURER, DONE, HandleOutro(), m_auiEncounter, and InstanceScript::SaveToDB().
WriteSaveDataMore()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << m_auiEncounter[0] << ' ' << m_auiEncounter[1];
        }
References m_auiEncounter.
Member Data Documentation
m_auiEncounter
uint32 instance_forge_of_souls::instance_forge_of_souls_InstanceScript::m_auiEncounter[MAX_ENCOUNTER]
Referenced by Initialize(), IsEncounterInProgress(), OnCreatureCreate(), OnPlayerEnter(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
NPC_BronjahmGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_BronjahmGUID
Referenced by CheckAchievementCriteriaMeet(), GetGuidData(), and OnCreatureCreate().
NPC_DevourerGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_DevourerGUID
Referenced by CheckAchievementCriteriaMeet(), HandleOutro(), and OnCreatureCreate().
NPC_GuardFirstGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_GuardFirstGUID
Referenced by OnCreatureCreate().
NPC_GuardSecondGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_GuardSecondGUID
Referenced by OnCreatureCreate().
NPC_LeaderFirstGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_LeaderFirstGUID
Referenced by OnCreatureCreate().
NPC_LeaderSecondGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_LeaderSecondGUID
Referenced by HandleOutro(), OnCreatureCreate(), and OnPlayerEnter().
str_data
std::string instance_forge_of_souls::instance_forge_of_souls_InstanceScript::str_data
teamIdInInstance
TeamId instance_forge_of_souls::instance_forge_of_souls_InstanceScript::teamIdInInstance
Referenced by HandleOutro(), Initialize(), and OnCreatureCreate().