AzerothCore: instance_nexus::instance_nexus_InstanceMapScript Struct Reference
instance_nexus::instance_nexus_InstanceMapScript Struct Reference
Public Member Functions
instance_nexus_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *gameObject) override
void OnGameObjectRemove (GameObject *gameObject) override
void SetData (uint32 type, uint32) override
bool SetBossState (uint32 id, EncounterState state) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_nexus_InstanceMapScript()
instance_nexus::instance_nexus_InstanceMapScript::instance_nexus_InstanceMapScript (Map * map) inline
: InstanceScript(map) {}
Member Function Documentation
Initialize()
void instance_nexus::instance_nexus_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTERS);
            LoadDoorData(doorData);
        }
References DataHeader, doorData, InstanceScript::LoadDoorData(), MAX_ENCOUNTERS, InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
OnCreatureCreate()
void instance_nexus::instance_nexus_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            Map::PlayerList const& players = instance->GetPlayers();
            TeamId TeamIdInInstance = TEAM_NEUTRAL;
            if (!players.IsEmpty())
                if (Player* pPlayer = players.begin()->GetSource())
                    TeamIdInInstance = pPlayer->GetTeamId();
            switch (creature->GetEntry())
            {
                case NPC_ALLIANCE_RANGER:
                    creature->SetFaction(FACTION_MONSTER_2);
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_HORDE_RANGER);
                    break;
                case NPC_ALLIANCE_BERSERKER:
                    creature->SetFaction(FACTION_MONSTER_2);
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_HORDE_BERSERKER);
                    break;
                case NPC_ALLIANCE_COMMANDER:
                    creature->SetFaction(FACTION_MONSTER_2);
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_HORDE_COMMANDER);
                    break;
                case NPC_ALLIANCE_CLERIC:
                    creature->SetFaction(FACTION_MONSTER_2);
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_HORDE_CLERIC);
                    break;
                case NPC_COMMANDER_STOUTBEARD:
                    creature->SetFaction(FACTION_MONSTER_2);
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_COMMANDER_KOLURG);
                    break;
            }
        }
References MapRefMgr::begin(), FACTION_MONSTER_2, Object::GetEntry(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), InstanceScript::instance, LinkedListHead::IsEmpty(), NPC_ALLIANCE_BERSERKER, NPC_ALLIANCE_CLERIC, NPC_ALLIANCE_COMMANDER, NPC_ALLIANCE_RANGER, NPC_COMMANDER_KOLURG, NPC_COMMANDER_STOUTBEARD, NPC_HORDE_BERSERKER, NPC_HORDE_CLERIC, NPC_HORDE_COMMANDER, NPC_HORDE_RANGER, Unit::SetFaction(), TEAM_ALLIANCE, TEAM_NEUTRAL, and Creature::UpdateEntry().
OnGameObjectCreate()
void instance_nexus::instance_nexus_InstanceMapScript::OnGameObjectCreate (GameObject * gameObject) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (gameObject->GetEntry())
            {
                case GO_TELESTRA_SPHERE:
                    if (GetBossState(DATA_TELESTRA_ORB) != DONE && GetBossState(DATA_MAGUS_TELESTRA_EVENT) == DONE)
                        gameObject->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    AddDoor(gameObject);
                    break;
                case GO_ANOMALUS_SPHERE:
                    if (GetBossState(DATA_ANOMALUS_ORB) != DONE && GetBossState(DATA_ANOMALUS_EVENT) == DONE)
                        gameObject->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    AddDoor(gameObject);
                    break;
                case GO_ORMOROK_SPHERE:
                    if (GetBossState(DATA_ORMOROK_ORB) != DONE && GetBossState(DATA_ORMOROK_EVENT) == DONE)
                        gameObject->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    AddDoor(gameObject);
                    break;
            }
        }
References InstanceScript::AddDoor(), DATA_ANOMALUS_EVENT, DATA_ANOMALUS_ORB, DATA_MAGUS_TELESTRA_EVENT, DATA_ORMOROK_EVENT, DATA_ORMOROK_ORB, DATA_TELESTRA_ORB, DONE, InstanceScript::GetBossState(), Object::GetEntry(), GO_ANOMALUS_SPHERE, GO_FLAG_NOT_SELECTABLE, GO_ORMOROK_SPHERE, GO_TELESTRA_SPHERE, and GameObject::RemoveGameObjectFlag().
OnGameObjectRemove()
void instance_nexus::instance_nexus_InstanceMapScript::OnGameObjectRemove (GameObject * gameObject) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (gameObject->GetEntry())
            {
                case GO_TELESTRA_SPHERE:
                case GO_ANOMALUS_SPHERE:
                case GO_ORMOROK_SPHERE:
                    RemoveDoor(gameObject);
                    break;
            }
        }
References Object::GetEntry(), GO_ANOMALUS_SPHERE, GO_ORMOROK_SPHERE, GO_TELESTRA_SPHERE, and InstanceScript::RemoveDoor().
SetBossState()
bool instance_nexus::instance_nexus_InstanceMapScript::SetBossState (uint32 id, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(id, state))
                return false;
            if (state != DONE || id > DATA_ORMOROK_EVENT)
                return true;
            BossInfo const* bossInfo = GetBossInfo(id + DATA_TELESTRA_ORB);
            for (DoorSet::const_iterator i = bossInfo->door[DOOR_TYPE_PASSAGE].begin(); i != bossInfo->door[DOOR_TYPE_PASSAGE].end(); ++i)
                (*i)->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
            return true;
        }
References DATA_ORMOROK_EVENT, DATA_TELESTRA_ORB, DONE, BossInfo::door, DOOR_TYPE_PASSAGE, InstanceScript::GetBossInfo(), GO_FLAG_NOT_SELECTABLE, and InstanceScript::SetBossState().
Referenced by SetData().
SetData()
void instance_nexus::instance_nexus_InstanceMapScript::SetData (uint32 type, uint32) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case GO_TELESTRA_SPHERE:
                    SetBossState(DATA_TELESTRA_ORB, NOT_STARTED);
                    SetBossState(DATA_TELESTRA_ORB, DONE);
                    break;
                case GO_ANOMALUS_SPHERE:
                    SetBossState(DATA_ANOMALUS_ORB, NOT_STARTED);
                    SetBossState(DATA_ANOMALUS_ORB, DONE);
                    break;
                case GO_ORMOROK_SPHERE:
                    SetBossState(DATA_ORMOROK_ORB, NOT_STARTED);
                    SetBossState(DATA_ORMOROK_ORB, DONE);
                    break;
            }
        }
References DATA_ANOMALUS_ORB, DATA_ORMOROK_ORB, DATA_TELESTRA_ORB, DONE, GO_ANOMALUS_SPHERE, GO_ORMOROK_SPHERE, GO_TELESTRA_SPHERE, NOT_STARTED, and SetBossState().