AzerothCore: boss_nightbane Struct Reference
boss_nightbane Struct Reference
Public Member Functions
boss_nightbane (Creature *creature)
void Reset () override
void HandleTerraceDoors (bool open)
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void ScheduleGround ()
void ScheduleFly ()
void AttackStart (Unit *who) override
void JustDied (Unit *) override
void MoveInLineOfSight (Unit *who) override
void MovementInform (uint32 type, uint32 id) override
void JustSummoned (Creature *summon) override
void DoCastOnFarAwayPlayers (uint32 spellid, bool triggered, float tresholddistance)
void TakeOff ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint32 Phase
TaskScheduler _skeletonscheduler
bool _intro
bool _flying
bool _movement
uint32 MovePhase
uint8 _skeletonCount
uint8 _skeletonSpawnCounter
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
bool _ProccessHealthCheckEvent (uint8 healthPct, uint32 damage, std::function< void()> exec) const
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
TaskScheduler scheduler
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_nightbane()
boss_nightbane::boss_nightbane (Creature * creature) inline
                                       : BossAI(creature, DATA_NIGHTBANE)
    {
        _intro = true;
        _skeletonCount = 5;
        scheduler.SetValidator([this]
        {
            return !me->HasUnitState(UNIT_STATE_CASTING);
        });
    }
References _intro, _skeletonCount, Unit::HasUnitState(), ScriptedAI::me, BossAI::scheduler, TaskScheduler::SetValidator(), and UNIT_STATE_CASTING.
Member Function Documentation
AttackStart()
void boss_nightbane::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (!_intro && !_flying)
            ScriptedAI::AttackStart(who);
    }
References _flying, _intro, and ScriptedAI::AttackStart().
DoCastOnFarAwayPlayers()
void boss_nightbane::DoCastOnFarAwayPlayers (uint32 spellid, bool triggered, float tresholddistance) inline
    {
        //resembles DoCastToAllHostilePlayers a bit/lot
        ThreatContainer::StorageType targets = me->GetThreatMgr().GetThreatList();
        for (ThreatContainer::StorageType::const_iterator itr = targets.begin(); itr != targets.end(); ++itr)
        {
            if (Unit* unit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid()))
            {
                if (unit->IsPlayer() && !unit->IsWithinDist(me, tresholddistance, false))
                {
                    me->CastSpell(unit, spellid, triggered);
                }
            }
        }
    }
References Unit::CastSpell(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), ObjectAccessor::GetUnit(), and ScriptedAI::me.
Referenced by ScheduleFly().
HandleTerraceDoors()
void boss_nightbane::HandleTerraceDoors (bool open) inline
    {
        if (instance)
        {
            instance->HandleGameObject(instance->GetGuidData(DATA_MASTERS_TERRACE_DOOR_1), open);
            instance->HandleGameObject(instance->GetGuidData(DATA_MASTERS_TERRACE_DOOR_2), open);
        }
    }
References DATA_MASTERS_TERRACE_DOOR_1, DATA_MASTERS_TERRACE_DOOR_2, InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), and BossAI::instance.
Referenced by JustDied(), JustEngagedWith(), and Reset().
JustDied()
void boss_nightbane::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
    {
        if (instance)
            instance->SetData(DATA_NIGHTBANE, DONE);
        HandleTerraceDoors(true);
    }
References DATA_NIGHTBANE, DONE, HandleTerraceDoors(), BossAI::instance, and ZoneScript::SetData().
JustEngagedWith()
void boss_nightbane::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        _JustEngagedWith();
        if (instance)
            instance->SetData(DATA_NIGHTBANE, IN_PROGRESS);
        HandleTerraceDoors(false);
        Talk(YELL_AGGRO);
        ScheduleGround();
    }
References BossAI::_JustEngagedWith(), DATA_NIGHTBANE, HandleTerraceDoors(), IN_PROGRESS, BossAI::instance, ScheduleGround(), ZoneScript::SetData(), and YELL_AGGRO.
JustSummoned()
void boss_nightbane::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
    {
        summon->AI()->AttackStart(me->GetVictim());
        summons.Summon(summon);
    }
References Creature::AI(), UnitAI::AttackStart(), Unit::GetVictim(), ScriptedAI::me, SummonList::Summon(), and BossAI::summons.
MoveInLineOfSight()
void boss_nightbane::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
    {
        if (!_intro && !_flying)
            ScriptedAI::MoveInLineOfSight(who);
    }
References _flying, _intro, and CreatureAI::MoveInLineOfSight().
MovementInform()
void boss_nightbane::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type != POINT_MOTION_TYPE)
            return;
        if (_intro)
        {
            if (id >= 8)
            {
                _intro = false;
                //me->SetHomePosition(IntroWay[7][0], IntroWay[7][1], IntroWay[7][2], 0);
                //doesn't need home position because we have to "despawn" boss on reset
                me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                me->SetInCombatWithZone();
                return;
            }
            MovePhase = id + 1;
            return;
        }
        if (_flying)
        {
            if (id == 0)
            {
                Talk(EMOTE_BREATH);
                _flying = false;
                Phase = 2;
                return;
            }
            if (id < 8)
                MovePhase = id + 1;
            else
            {
                Phase = 1;
                _flying = false;
                _movement = true;
                return;
            }
        }
    }
References _flying, _intro, _movement, EMOTE_BREATH, ScriptedAI::me, MovePhase, POINT_MOTION_TYPE, Unit::RemoveUnitFlag(), Creature::SetInCombatWithZone(), and UNIT_FLAG_NOT_SELECTABLE.
Reset()
void boss_nightbane::Reset () inline override virtual
Reimplemented from BossAI.
    {
        BossAI::Reset();
        _skeletonscheduler.CancelAll();
        Phase = 1;
        MovePhase = 0;
        me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        me->SetSpeed(MOVE_RUN, 2.0f);
        me->SetDisableGravity(_intro);
        me->SetWalk(false);
        me->setActive(true);
        if (instance)
        {
            if (instance->GetData(DATA_NIGHTBANE) == DONE)
                me->DisappearAndDie();
            else
                instance->SetData(DATA_NIGHTBANE, NOT_STARTED);
        }
        HandleTerraceDoors(true);
        _flying = false;
        _movement = false;
        if (!_intro)
        {
            //when boss is reset and we're past the intro
            //cannot despawn, but have to move to a location where he normally is
            //me->SetHomePosition(IntroWay[7][0], IntroWay[7][1], IntroWay[7][2], 0);
            Position preSpawnPosis = me->GetHomePosition();
            me->NearTeleportTo(preSpawnPosis);
            instance->SetData(DATA_NIGHTBANE, NOT_STARTED);
            _intro = true;
            Phase = 1;
            MovePhase = 0;
        }
        ScheduleHealthCheckEvent({25, 50, 70}, [&]{
            TakeOff();
        });
    }
References _flying, _intro, _movement, _skeletonscheduler, TaskScheduler::CancelAll(), DATA_NIGHTBANE, Creature::DisappearAndDie(), DONE, ZoneScript::GetData(), Creature::GetHomePosition(), HandleTerraceDoors(), BossAI::instance, ScriptedAI::me, MOVE_RUN, MovePhase, Unit::NearTeleportTo(), NOT_STARTED, BossAI::Reset(), BossAI::ScheduleHealthCheckEvent(), WorldObject::setActive(), ZoneScript::SetData(), Creature::SetDisableGravity(), Unit::SetSpeed(), Unit::SetUnitFlag(), Creature::SetWalk(), TakeOff(), and UNIT_FLAG_NOT_SELECTABLE.
ScheduleFly()
void boss_nightbane::ScheduleFly () inline
                       {
        _skeletonSpawnCounter = 0;
        scheduler.Schedule(2s, GROUP_FLYING, [this](TaskContext)
        {
            DoCastVictim(SPELL_RAIN_OF_BONES);
            _skeletonscheduler.Schedule(50ms, [this](TaskContext context)
            {
                //spawns skeletons every second until skeletonCount is reached
                if(_skeletonSpawnCounter < _skeletonCount)
                {
                    DoCastVictim(SPELL_SUMMON_SKELETON, true);
                    _skeletonSpawnCounter++;
                    context.Repeat(2s);
                }
            });
        }).Schedule(20s, GROUP_FLYING, [this](TaskContext context)
        {
            DoCastRandomTarget(SPELL_DISTRACTING_ASH);
            context.Repeat(2s); //timer wrong?
        }).Schedule(25s, GROUP_FLYING, [this](TaskContext context)
        {
            //5 seconds added due to double trigger?
            //trigger for timer in original + in rain of bones
            //timers need some investigation
            DoCastVictim(SPELL_SMOKING_BLAST);
            context.Repeat(1500ms); //timer wrong?
        }).Schedule(13s, GROUP_FLYING, [this](TaskContext context)
        {
            DoCastOnFarAwayPlayers(SPELL_FIREBALL_BARRAGE, false, 80.0f);
            context.Repeat(20s);
        });
    }
References _skeletonCount, _skeletonscheduler, _skeletonSpawnCounter, DoCastOnFarAwayPlayers(), UnitAI::DoCastRandomTarget(), UnitAI::DoCastVictim(), GROUP_FLYING, TaskContext::Repeat(), TaskScheduler::Schedule(), BossAI::scheduler, SPELL_DISTRACTING_ASH, SPELL_FIREBALL_BARRAGE, SPELL_RAIN_OF_BONES, SPELL_SMOKING_BLAST, and SPELL_SUMMON_SKELETON.
Referenced by TakeOff().
ScheduleGround()
void boss_nightbane::ScheduleGround () inline
{
        scheduler.Schedule(30s, GROUP_GROUND, [this](TaskContext context)
        {
            DoCastAOE(SPELL_BELLOWING_ROAR);
            context.Repeat(30s, 40s);
        }).Schedule(15s, GROUP_GROUND, [this](TaskContext context)
        {
            DoCastRandomTarget(SPELL_CHARRED_EARTH, 0, 100.0f, true);
            context.Repeat(20s);
        }).Schedule(10s, GROUP_GROUND, [this](TaskContext context)
        {
            DoCastVictim(SPELL_SMOLDERING_BREATH);
            context.Repeat(20s);
        }).Schedule(12s, GROUP_GROUND, [this](TaskContext context)
        {
            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100, true))
            {
                if (!me->HasInArc(M_PI, target))
                {
                    DoCast(target, SPELL_TAIL_SWEEP);
                }
            }
            context.Repeat(15s);
        }).Schedule(14s, GROUP_GROUND, [this](TaskContext context)
        {
            DoCastRandomTarget(SPELL_SEARING_CINDERS);
            context.Repeat(10s);
        });
    }
References UnitAI::DoCast(), UnitAI::DoCastAOE(), UnitAI::DoCastRandomTarget(), UnitAI::DoCastVictim(), GROUP_GROUND, Position::HasInArc(), ScriptedAI::me, TaskContext::Repeat(), TaskScheduler::Schedule(), BossAI::scheduler, UnitAI::SelectTarget(), SPELL_BELLOWING_ROAR, SPELL_CHARRED_EARTH, SPELL_SEARING_CINDERS, SPELL_SMOLDERING_BREATH, and SPELL_TAIL_SWEEP.
Referenced by JustEngagedWith(), and TakeOff().
TakeOff()
void boss_nightbane::TakeOff () inline
    {
        Talk(YELL_FLY_PHASE);
        scheduler.CancelGroup(GROUP_GROUND);
        me->InterruptSpell(CURRENT_GENERIC_SPELL);
        me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
        me->SetDisableGravity(true);
        me->GetMotionMaster()->Clear(false);
        me->GetMotionMaster()->MovePoint(0, IntroWay[2][0], IntroWay[2][1], IntroWay[2][2]);
        _flying = true;
        ScheduleFly();
        //handle landing again
        scheduler.Schedule(45s, 60s, [this](TaskContext)
        {
            Talk(YELL_LAND_PHASE);
            me->GetMotionMaster()->Clear(false);
            me->GetMotionMaster()->MovePoint(3, IntroWay[3][0], IntroWay[3][1], IntroWay[3][2]);
            _flying = true;
            scheduler.CancelGroup(GROUP_FLYING);
            scheduler.Schedule(2s, [this](TaskContext)
            {
                ScheduleGround();
            });
        });
    }
References _flying, TaskScheduler::CancelGroup(), MotionMaster::Clear(), CURRENT_GENERIC_SPELL, EMOTE_ONESHOT_LIFTOFF, Unit::GetMotionMaster(), GROUP_FLYING, GROUP_GROUND, Unit::HandleEmoteCommand(), Unit::InterruptSpell(), IntroWay, ScriptedAI::me, MotionMaster::MovePoint(), TaskScheduler::Schedule(), ScheduleFly(), ScheduleGround(), BossAI::scheduler, Creature::SetDisableGravity(), YELL_FLY_PHASE, and YELL_LAND_PHASE.
Referenced by Reset().
UpdateAI()
void boss_nightbane::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
    {
        if (_intro)
        {
            if (MovePhase)
            {
                if (MovePhase >= 7)
                {
                    me->SetDisableGravity(false);
                    me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                    me->GetMotionMaster()->MovePoint(8, IntroWay[7][0], IntroWay[7][1], IntroWay[7][2]);
                }
                else
                {
                    me->GetMotionMaster()->MovePoint(MovePhase, IntroWay[MovePhase][0], IntroWay[MovePhase][1], IntroWay[MovePhase][2]);
                }
                MovePhase = 0;
            }
            return;
        }
        if (_flying && MovePhase)
        {
            if (MovePhase >= 7)
            {
                me->SetDisableGravity(false);
                me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                me->GetMotionMaster()->MovePoint(8, IntroWay[7][0], IntroWay[7][1], IntroWay[7][2]);
            }
            else
                me->GetMotionMaster()->MovePoint(MovePhase, IntroWay[MovePhase][0], IntroWay[MovePhase][1], IntroWay[MovePhase][2]);
            MovePhase = 0;
        }
        if (!UpdateVictim())
            return;
        if (_flying)
            return;
        scheduler.Update(diff);
        _skeletonscheduler.Update(diff);
        //  Phase 1 "GROUND FIGHT"
        if (Phase == 1)
        {
            if (_movement)
            {
                DoStartMovement(me->GetVictim());
                _movement = false;
            }
            DoMeleeAttackIfReady();
        }
    }
References _flying, _intro, _movement, _skeletonscheduler, UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoStartMovement(), EMOTE_ONESHOT_LAND, Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HandleEmoteCommand(), IntroWay, ScriptedAI::me, MovePhase, MotionMaster::MovePoint(), BossAI::scheduler, Creature::SetDisableGravity(), TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_flying
bool boss_nightbane::_flying private
Referenced by AttackStart(), MoveInLineOfSight(), MovementInform(), Reset(), TakeOff(), and UpdateAI().
_intro
bool boss_nightbane::_intro private
Referenced by AttackStart(), boss_nightbane(), MoveInLineOfSight(), MovementInform(), Reset(), and UpdateAI().
_movement
bool boss_nightbane::_movement private
Referenced by MovementInform(), Reset(), and UpdateAI().
_skeletonCount
uint8 boss_nightbane::_skeletonCount private
Referenced by boss_nightbane(), and ScheduleFly().
_skeletonscheduler
TaskScheduler boss_nightbane::_skeletonscheduler private
Referenced by Reset(), ScheduleFly(), and UpdateAI().
_skeletonSpawnCounter
uint8 boss_nightbane::_skeletonSpawnCounter private
Referenced by ScheduleFly().
MovePhase
uint32 boss_nightbane::MovePhase private
Referenced by MovementInform(), Reset(), and UpdateAI().
Phase
uint32 boss_nightbane::Phase private