AzerothCore: spell_dk_improved_unholy_presence Class Reference
spell_dk_improved_unholy_presence Class Reference
Private Member Functions
PrepareAuraScript (spell_dk_improved_unholy_presence)
bool Validate (SpellInfo const *) override
void HandleEffectApply (AuraEffect const *aurEff, AuraEffectHandleModes)
void HandleEffectRemove (AuraEffect const *, AuraEffectHandleModes)
void Register () override
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleEffectApply()
void spell_dk_improved_unholy_presence::HandleEffectApply (AuraEffect const * aurEff, AuraEffectHandleModes) inline private
    {
        Unit* target = GetTarget();
        if (target->HasAura(SPELL_DK_UNHOLY_PRESENCE) && !target->HasAura(SPELL_DK_IMPROVED_UNHOLY_PRESENCE_TRIGGERED))
        {
            // Not listed as any effect, only base points set in dbc
            int32 basePoints = GetSpellInfo()->Effects[EFFECT_1].CalcValue();
            target->CastCustomSpell(target, SPELL_DK_IMPROVED_UNHOLY_PRESENCE_TRIGGERED, &basePoints, &basePoints, &basePoints, true, nullptr, aurEff);
        }
        if ((target->HasAura(SPELL_DK_BLOOD_PRESENCE) || target->HasAura(SPELL_DK_FROST_PRESENCE)) && !target->HasAura(SPELL_DK_UNHOLY_PRESENCE_TRIGGERED))
            target->CastCustomSpell(SPELL_DK_UNHOLY_PRESENCE_TRIGGERED, SPELLVALUE_BASE_POINT0, aurEff->GetAmount(), target, true, nullptr, aurEff);
    }
References Unit::CastCustomSpell(), EFFECT_1, SpellInfo::Effects, AuraEffect::GetAmount(), AuraScript::GetSpellInfo(), AuraScript::GetTarget(), Unit::HasAura(), SPELL_DK_BLOOD_PRESENCE, SPELL_DK_FROST_PRESENCE, SPELL_DK_IMPROVED_UNHOLY_PRESENCE_TRIGGERED, SPELL_DK_UNHOLY_PRESENCE, SPELL_DK_UNHOLY_PRESENCE_TRIGGERED, and SPELLVALUE_BASE_POINT0.
Referenced by Register().
HandleEffectRemove()
void spell_dk_improved_unholy_presence::HandleEffectRemove (AuraEffect const * , AuraEffectHandleModes) inline private
    {
        Unit* target = GetTarget();
        target->RemoveAura(SPELL_DK_IMPROVED_UNHOLY_PRESENCE_TRIGGERED);
        if (!target->HasAura(SPELL_DK_UNHOLY_PRESENCE))
            target->RemoveAura(SPELL_DK_UNHOLY_PRESENCE_TRIGGERED);
    }
References AuraScript::GetTarget(), Unit::HasAura(), Unit::RemoveAura(), SPELL_DK_IMPROVED_UNHOLY_PRESENCE_TRIGGERED, SPELL_DK_UNHOLY_PRESENCE, and SPELL_DK_UNHOLY_PRESENCE_TRIGGERED.
Referenced by Register().
PrepareAuraScript()
spell_dk_improved_unholy_presence::PrepareAuraScript (spell_dk_improved_unholy_presence) private
Register()
void spell_dk_improved_unholy_presence::Register () inline override private virtual
Implements _SpellScript.
    {
        AfterEffectApply += AuraEffectApplyFn(spell_dk_improved_unholy_presence::HandleEffectApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_dk_improved_unholy_presence::HandleEffectRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
References AuraScript::AfterEffectApply, AuraScript::AfterEffectRemove, AURA_EFFECT_HANDLE_REAL, AuraEffectApplyFn, AuraEffectRemoveFn, EFFECT_0, HandleEffectApply(), HandleEffectRemove(), and SPELL_AURA_DUMMY.
Validate()
bool spell_dk_improved_unholy_presence::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo(
            {
                SPELL_DK_BLOOD_PRESENCE,
                SPELL_DK_FROST_PRESENCE,
                SPELL_DK_UNHOLY_PRESENCE,
                SPELL_DK_IMPROVED_UNHOLY_PRESENCE_TRIGGERED,
                SPELL_DK_UNHOLY_PRESENCE_TRIGGERED
            });
    }
References SPELL_DK_BLOOD_PRESENCE, SPELL_DK_FROST_PRESENCE, SPELL_DK_IMPROVED_UNHOLY_PRESENCE_TRIGGERED, SPELL_DK_UNHOLY_PRESENCE, SPELL_DK_UNHOLY_PRESENCE_TRIGGERED, and _SpellScript::ValidateSpellInfo().