AzerothCore: SpectralBlastCheck Class Reference
SpectralBlastCheck Class Reference
Public Member Functions
SpectralBlastCheck (Unit *victim)
bool operator() (WorldObject *unit)
Private Attributes
Unit * _victim
Detailed Description
Constructor & Destructor Documentation
SpectralBlastCheck()
SpectralBlastCheck::SpectralBlastCheck (Unit * victim) inline
: _victim(victim) { }
Member Function Documentation
operator()()
bool SpectralBlastCheck::operator() (WorldObject * unit) inline
    {
        return unit->GetPositionZ() < 50.0f || unit->ToUnit()->HasAura(SPELL_SPECTRAL_EXHAUSTION) || unit->GetGUID() == _victim->GetGUID();
    }
References _victim, Object::GetGUID(), Position::GetPositionZ(), Unit::HasAura(), SPELL_SPECTRAL_EXHAUSTION, and Object::ToUnit().
Member Data Documentation
_victim
Unit* SpectralBlastCheck::_victim private
Referenced by operator()().