AzerothCore: boss_sindragosa::boss_sindragosaAI Struct Reference
boss_sindragosa::boss_sindragosaAI Struct Reference
Public Member Functions
boss_sindragosaAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
bool CanAIAttack (Unit const *target) const override
void EnterEvadeMode (EvadeReason why) override
void KilledUnit (Unit *victim) override
void DoAction (int32 action) override
uint32 GetData (uint32 type) const override
void MovementInform (uint32 type, uint32 point) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint8 _bombCount
uint8 _mysticBuffetStack
bool _isBelow20Pct
bool _isThirdPhase
bool _isInAirPhase
bool _isLanding
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_sindragosaAI()
boss_sindragosa::boss_sindragosaAI::boss_sindragosaAI (Creature * creature) inline
                                              : BossAI(creature, DATA_SINDRAGOSA)
        {
            me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_HASTE_SPELLS, true);
        }
References Unit::ApplySpellImmune(), IMMUNITY_STATE, ScriptedAI::me, and SPELL_AURA_HASTE_SPELLS.
Member Function Documentation
CanAIAttack()
bool boss_sindragosa::boss_sindragosaAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
        {
            return me->IsVisible() && target->GetEntry() != NPC_CROK_SCOURGEBANE;
        }
References Object::GetEntry(), Unit::IsVisible(), ScriptedAI::me, and NPC_CROK_SCOURGEBANE.
DamageTaken()
void boss_sindragosa::boss_sindragosaAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
        {
            if (!damage || me->IsInEvadeMode())
                return;
            if (!_isThirdPhase)
            {
                if (!HealthAbovePct(35))
                {
                    _isThirdPhase = true;
                    events.CancelEvent(EVENT_AIR_PHASE);
                    events.ScheduleEvent(EVENT_THIRD_PHASE_CHECK, 1s);
                }
            }
            else if (!_isBelow20Pct)
            {
                if (!HealthAbovePct(20))
                {
                    _isBelow20Pct = true;
                    if (instance->GetData(DATA_WEEKLY_QUEST_ID) == QUEST_RESPITE_FOR_A_TORMENTED_SOUL_10)
                        Talk(EMOTE_WEAKENING);
                }
            }
        }
References _isBelow20Pct, _isThirdPhase, DATA_WEEKLY_QUEST_ID, EMOTE_WEAKENING, EVENT_AIR_PHASE, EVENT_THIRD_PHASE_CHECK, ZoneScript::GetData(), ScriptedAI::HealthAbovePct(), BossAI::instance, Creature::IsInEvadeMode(), ScriptedAI::me, and QUEST_RESPITE_FOR_A_TORMENTED_SOUL_10.
DoAction()
void boss_sindragosa::boss_sindragosaAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == ACTION_START_FROSTWYRM && !_isLanding)
            {
                _isLanding = true;
                if (TempSummon* summon = me->ToTempSummon())
                    summon->SetTempSummonType(TEMPSUMMON_DEAD_DESPAWN);
                if (me->isDead())
                    return;
                me->setActive(true);
                me->SetDisableGravity(true);
                me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->SetSpeed(MOVE_RUN, 4.28571f);
                float moveTime = me->GetExactDist(&SindragosaFlyInPos) / (me->GetSpeed(MOVE_RUN) * 0.001f);
                me->m_Events.AddEvent(new FrostwyrmLandEvent(*me, SindragosaLandPos), me->m_Events.CalculateTime(uint64(moveTime) + 250));
                me->GetMotionMaster()->MovePoint(POINT_FROSTWYRM_FLY_IN, SindragosaFlyInPos);
                if (!instance->GetData(DATA_SINDRAGOSA_INTRO))
                {
                    DoCastAOE(SPELL_SINDRAGOSA_S_FURY);
                }
            }
        }
References _isLanding, ACTION_START_FROSTWYRM, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), DATA_SINDRAGOSA_INTRO, UnitAI::DoCastAOE(), ZoneScript::GetData(), Position::GetExactDist(), Unit::GetMotionMaster(), Unit::GetSpeed(), BossAI::instance, Unit::isDead(), Unit::m_Events, ScriptedAI::me, MOVE_RUN, MotionMaster::MovePoint(), POINT_FROSTWYRM_FLY_IN, WorldObject::setActive(), Creature::SetDisableGravity(), Unit::SetSpeed(), Unit::SetUnitFlag(), SindragosaFlyInPos, SindragosaLandPos, SPELL_SINDRAGOSA_S_FURY, TEMPSUMMON_DEAD_DESPAWN, Unit::ToTempSummon(), and UNIT_FLAG_NON_ATTACKABLE.
EnterEvadeMode()
void boss_sindragosa::boss_sindragosaAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from BossAI.
        {
            instance->SetBossState(DATA_SINDRAGOSA, FAIL);
            BossAI::EnterEvadeMode(why);
        }
References DATA_SINDRAGOSA, BossAI::EnterEvadeMode(), FAIL, BossAI::instance, and InstanceScript::SetBossState().
Referenced by JustEngagedWith().
GetData()
uint32 boss_sindragosa::boss_sindragosaAI::GetData (uint32 type) const inline override virtual
Reimplemented from UnitAI.
        {
            if (type == DATA_MYSTIC_BUFFET_STACK)
                return _mysticBuffetStack;
            return 0xFFFFFFFF;
        }
References _mysticBuffetStack, and DATA_MYSTIC_BUFFET_STACK.
JustDied()
void boss_sindragosa::boss_sindragosaAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            _JustDied();
            Talk(SAY_DEATH);
            if (Is25ManRaid() && me->HasAura(SPELL_SHADOWS_FATE))
                DoCastAOE(SPELL_FROST_INFUSION_CREDIT, true);
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_FROST_BEACON);
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_ICE_TOMB_TARGET);
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_ICE_TOMB_DUMMY);
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_ICE_TOMB_UNTARGETABLE);
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_ICE_TOMB_DAMAGE);
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_ASPHYXIATION);
        }
References BossAI::_JustDied(), UnitAI::DoCastAOE(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), Unit::HasAura(), BossAI::instance, ScriptedAI::Is25ManRaid(), ScriptedAI::me, SAY_DEATH, SPELL_ASPHYXIATION, SPELL_FROST_BEACON, SPELL_FROST_INFUSION_CREDIT, SPELL_ICE_TOMB_DAMAGE, SPELL_ICE_TOMB_DUMMY, SPELL_ICE_TOMB_TARGET, SPELL_ICE_TOMB_UNTARGETABLE, and SPELL_SHADOWS_FATE.
JustEngagedWith()
void boss_sindragosa::boss_sindragosaAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            if (!instance->CheckRequiredBosses(DATA_SINDRAGOSA, who->ToPlayer()) || !me->IsVisible())
            {
                EnterEvadeMode(EVADE_REASON_OTHER);
                instance->DoCastSpellOnPlayers(LIGHT_S_HAMMER_TELEPORT);
                return;
            }
            _isBelow20Pct = false;
            _isThirdPhase = false;
            _bombCount = 0;
            _mysticBuffetStack = 0;
            summons.DespawnAll();
            events.Reset();
            events.ScheduleEvent(EVENT_BERSERK, 10min);
            events.ScheduleEvent(EVENT_AIR_PHASE, 50s);
            events.ScheduleEvent(EVENT_CLEAVE, 10s, EVENT_GROUP_LAND_PHASE);
            events.ScheduleEvent(EVENT_TAIL_SMASH, 20s, EVENT_GROUP_LAND_PHASE);
            events.ScheduleEvent(EVENT_FROST_BREATH, 8s, 12s, EVENT_GROUP_LAND_PHASE);
            events.ScheduleEvent(EVENT_UNCHAINED_MAGIC, 9s, 14s, EVENT_GROUP_LAND_PHASE);
            events.ScheduleEvent(EVENT_ICY_GRIP, 33s + 500ms, EVENT_GROUP_LAND_PHASE);
            me->setActive(true);
            me->SetInCombatWithZone();
            instance->SetBossState(DATA_SINDRAGOSA, IN_PROGRESS);
            me->CastSpell(me, SPELL_FROST_AURA, true);
            me->CastSpell(me, SPELL_PERMAEATING_CHILL, true);
            Talk(SAY_AGGRO);
        }
References _bombCount, _isBelow20Pct, _isThirdPhase, _mysticBuffetStack, Unit::CastSpell(), InstanceScript::CheckRequiredBosses(), DATA_SINDRAGOSA, SummonList::DespawnAll(), InstanceScript::DoCastSpellOnPlayers(), EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_AIR_PHASE, EVENT_BERSERK, EVENT_CLEAVE, EVENT_FROST_BREATH, EVENT_GROUP_LAND_PHASE, EVENT_ICY_GRIP, EVENT_TAIL_SMASH, EVENT_UNCHAINED_MAGIC, IN_PROGRESS, BossAI::instance, Unit::IsVisible(), LIGHT_S_HAMMER_TELEPORT, ScriptedAI::me, SAY_AGGRO, WorldObject::setActive(), InstanceScript::SetBossState(), Creature::SetInCombatWithZone(), SPELL_FROST_AURA, SPELL_PERMAEATING_CHILL, BossAI::summons, and Object::ToPlayer().
JustSummoned()
void boss_sindragosa::boss_sindragosaAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            summons.Summon(summon);
            if (summon->GetEntry() == NPC_FROST_BOMB)
                summon->m_Events.AddEvent(new FrostBombExplosion(summon, me->GetGUID()), summon->m_Events.CalculateTime(5500));
        }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Object::GetEntry(), Object::GetGUID(), Unit::m_Events, ScriptedAI::me, NPC_FROST_BOMB, SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_sindragosa::boss_sindragosaAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->IsPlayer())
                Talk(SAY_KILL);
        }
References Object::IsPlayer(), and SAY_KILL.
MoveInLineOfSight()
void boss_sindragosa::boss_sindragosaAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!me->HasUnitMovementFlag(MOVEMENTFLAG_CAN_FLY))
                BossAI::MoveInLineOfSight(who);
        }
References Unit::HasUnitMovementFlag(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), and MOVEMENTFLAG_CAN_FLY.
MovementInform()
void boss_sindragosa::boss_sindragosaAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type != POINT_MOTION_TYPE && type != EFFECT_MOTION_TYPE)
                return;
            switch (point)
            {
                case POINT_FROSTWYRM_LAND:
                    me->setActive(false);
                    me->SetDisableGravity(false);
                    me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run);
                    me->SetHomePosition(SindragosaLandPos);
                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    // Sindragosa enters combat as soon as she lands
                    me->SetInCombatWithZone();
                    break;
                case POINT_TAKEOFF:
                    events.ScheduleEvent(EVENT_AIR_MOVEMENT, 0ms);
                    break;
                case POINT_AIR_PHASE:
                    me->CastCustomSpell(SPELL_ICE_TOMB_TARGET, SPELLVALUE_MAX_TARGETS, RAID_MODE<int32>(2, 5, 2, 6), nullptr);
                    me->SetFacingTo(float(M_PI));
                    events.ScheduleEvent(EVENT_AIR_MOVEMENT_FAR, 0ms); // won't be processed during cast time anyway, so 0
                    events.ScheduleEvent(EVENT_FROST_BOMB, 7s);
                    _bombCount = 0;
                    break;
                case POINT_AIR_PHASE_FAR:
                    me->SetFacingTo(float(M_PI));
                    break;
                case POINT_LAND:
                    events.ScheduleEvent(EVENT_LAND_GROUND, 0ms);
                    break;
                case POINT_LAND_GROUND:
                    {
                        _isInAirPhase = false;
                        me->SetDisableGravity(false);
                        me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run);
                        me->SetReactState(REACT_AGGRESSIVE);
                        if (Unit* target = me->SelectVictim())
                            AttackStart(target);
                        break;
                    }
                default:
                    break;
            }
        }
References _bombCount, _isInAirPhase, ScriptedAI::AttackStart(), Unit::CastCustomSpell(), EFFECT_MOTION_TYPE, EVENT_AIR_MOVEMENT, EVENT_AIR_MOVEMENT_FAR, EVENT_FROST_BOMB, EVENT_LAND_GROUND, Creature::GetCreatureTemplate(), ScriptedAI::me, MOVE_RUN, POINT_AIR_PHASE, POINT_AIR_PHASE_FAR, POINT_FROSTWYRM_LAND, POINT_LAND, POINT_LAND_GROUND, POINT_MOTION_TYPE, POINT_TAKEOFF, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Creature::SelectVictim(), WorldObject::setActive(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Creature::SetHomePosition(), Creature::SetInCombatWithZone(), Creature::SetReactState(), Unit::SetSpeed(), SindragosaLandPos, CreatureTemplate::speed_run, SPELL_ICE_TOMB_TARGET, SPELLVALUE_MAX_TARGETS, and UNIT_FLAG_NON_ATTACKABLE.
Reset()
void boss_sindragosa::boss_sindragosaAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            _isBelow20Pct = false;
            _isThirdPhase = false;
            _isLanding = false;
            _bombCount = 0;
            _mysticBuffetStack = 0;
            _Reset();
            me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run);
            me->SetReactState(REACT_AGGRESSIVE);
            me->CastSpell(me, SPELL_TANK_MARKER, true);
        }
References _bombCount, _isBelow20Pct, _isLanding, _isThirdPhase, _mysticBuffetStack, BossAI::_Reset(), Unit::CastSpell(), Creature::GetCreatureTemplate(), ScriptedAI::me, MOVE_RUN, REACT_AGGRESSIVE, Creature::SetReactState(), Unit::SetSpeed(), CreatureTemplate::speed_run, and SPELL_TANK_MARKER.
SpellHitTarget()
void boss_sindragosa::boss_sindragosaAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (target->IsPlayer())
                if (uint32 spellId = sSpellMgr->GetSpellIdForDifficulty(70127, me))
                    if (spellId == spell->Id)
                        if (Aura const* mysticBuffet = target->GetAura(spell->Id))
                            _mysticBuffetStack = std::max<uint8>(_mysticBuffetStack, mysticBuffet->GetStackAmount());
        }
References _mysticBuffetStack, Unit::GetAura(), SpellInfo::Id, Object::IsPlayer(), ScriptedAI::me, and sSpellMgr.
SummonedCreatureDespawn()
void boss_sindragosa::boss_sindragosaAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            BossAI::SummonedCreatureDespawn(summon);
            if (summon->GetEntry() == NPC_ICE_TOMB)
                summon->AI()->JustDied(summon);
        }
References Creature::AI(), Object::GetEntry(), CreatureAI::JustDied(), NPC_ICE_TOMB, and BossAI::SummonedCreatureDespawn().
UpdateAI()
void boss_sindragosa::boss_sindragosaAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_BERSERK:
                    Talk(EMOTE_BERSERK_RAID);
                    Talk(SAY_BERSERK);
                    me->CastSpell(me, SPELL_BERSERK, true);
                    break;
                case EVENT_CLEAVE:
                    me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                    events.ScheduleEvent(EVENT_CLEAVE, 10s, 15s, EVENT_GROUP_LAND_PHASE);
                    break;
                case EVENT_TAIL_SMASH:
                    me->DisableRotate(true);
                    me->SetControlled(true, UNIT_STATE_ROOT);
                    me->SendMovementFlagUpdate();
                    me->CastSpell(me->GetVictim(), SPELL_TAIL_SMASH, false);
                    events.DelayEventsToMax(1, 0);
                    events.ScheduleEvent(EVENT_UNROOT, 0ms);
                    events.ScheduleEvent(EVENT_TAIL_SMASH, 22s, 27s, EVENT_GROUP_LAND_PHASE);
                    break;
                case EVENT_FROST_BREATH:
                    me->DisableRotate(true);
                    me->SetControlled(true, UNIT_STATE_ROOT);
                    me->SendMovementFlagUpdate();
                    me->CastSpell(me->GetVictim(), _isThirdPhase ? SPELL_FROST_BREATH_P2 : SPELL_FROST_BREATH_P1, false);
                    events.DelayEventsToMax(1, 0);
                    events.ScheduleEvent(EVENT_UNROOT, 0ms);
                    events.ScheduleEvent(EVENT_FROST_BREATH, 20s, 25s, EVENT_GROUP_LAND_PHASE);
                    break;
                case EVENT_UNROOT:
                    me->DisableRotate(false);
                    me->SetControlled(false, UNIT_STATE_ROOT);
                    break;
                case EVENT_UNCHAINED_MAGIC:
                    Talk(SAY_UNCHAINED_MAGIC);
                    me->CastSpell((Unit*)nullptr, SPELL_UNCHAINED_MAGIC, false);
                    events.ScheduleEvent(EVENT_UNCHAINED_MAGIC, 30s, 35s, EVENT_GROUP_LAND_PHASE);
                    break;
                case EVENT_ICY_GRIP:
                    me->CastSpell((Unit*)nullptr, SPELL_ICY_GRIP, false);
                    events.DelayEventsToMax(1001, 0);
                    events.ScheduleEvent(EVENT_BLISTERING_COLD, 1s, EVENT_GROUP_LAND_PHASE);
                    if (uint32 evTime = events.GetNextEventTime(EVENT_ICE_TOMB))
                        if (events.GetTimer() > evTime || evTime - events.GetTimer() < 7000)
                            events.RescheduleEvent(EVENT_ICE_TOMB, 7s);
                    break;
                case EVENT_BLISTERING_COLD:
                    Talk(EMOTE_WARN_BLISTERING_COLD);
                    me->CastSpell(me, SPELL_BLISTERING_COLD, false);
                    events.ScheduleEvent(EVENT_BLISTERING_COLD_YELL, 5s, EVENT_GROUP_LAND_PHASE);
                    if (_isThirdPhase)
                        events.RescheduleEvent(EVENT_ICY_GRIP, 65s, 70s);
                    break;
                case EVENT_BLISTERING_COLD_YELL:
                    Talk(SAY_BLISTERING_COLD);
                    break;
                // AIR PHASE EVENTS BELOW:
                case EVENT_AIR_PHASE:
                    // pussywizard: unroot may be scheduled after this event cos of events (time must be unique)
                    if (me->HasUnitState(UNIT_STATE_ROOT))
                    {
                        events.CancelEvent(EVENT_UNROOT);
                        me->DisableRotate(false);
                        me->SetControlled(false, UNIT_STATE_ROOT);
                    }
                    _isInAirPhase = true;
                    Talk(SAY_AIR_PHASE);
                    me->SetReactState(REACT_PASSIVE);
                    me->SetSpeed(MOVE_RUN, 4.28571f);
                    me->SendMeleeAttackStop(me->GetVictim());
                    me->AttackStop();
                    me->GetMotionMaster()->MoveIdle();
                    me->StopMoving();
                    me->SetDisableGravity(true);
                    me->GetMotionMaster()->MoveTakeoff(POINT_TAKEOFF, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 20.0f, 10.0f);
                    events.CancelEventGroup(EVENT_GROUP_LAND_PHASE);
                    events.ScheduleEvent(EVENT_AIR_PHASE, 110s);
                    break;
                case EVENT_AIR_MOVEMENT:
                    me->GetMotionMaster()->MovePoint(POINT_AIR_PHASE, SindragosaAirPos);
                    break;
                case EVENT_AIR_MOVEMENT_FAR:
                    me->GetMotionMaster()->MovePoint(POINT_AIR_PHASE_FAR, SindragosaAirPosFar);
                    break;
                case EVENT_FROST_BOMB:
                    {
                        ++_bombCount;
                        float destX, destY, destZ;
                        std::list<GameObject*> gl;
                        me->GetGameObjectListWithEntryInGrid(gl, GO_ICE_BLOCK, SIZE_OF_GRIDS);
                        uint8 triesLeft = 10;
                        do
{
                            destX = float(rand_norm()) * 75.0f + 4350.0f;
                            destY = float(rand_norm()) * 75.0f + 2450.0f;
                            destZ = 205.0f; // random number close to ground, get exact in next call
                            me->UpdateGroundPositionZ(destX, destY, destZ);
                            bool ok = true;
                            for (std::list<GameObject*>::const_iterator itr = gl.begin(); itr != gl.end(); ++itr)
                                if ((*itr)->GetExactDist2dSq(destX, destY) < 3.0f * 3.0f)
{
                                    ok = false;
                                    break;
                                }
                            if (ok)
                                break;
                        } while (--triesLeft);
                        me->CastSpell(destX, destY, destZ, SPELL_FROST_BOMB_TRIGGER, false);
                        if (_bombCount >= 4)
                            events.ScheduleEvent(EVENT_LAND, 5500ms);
                        else
                            events.ScheduleEvent(EVENT_FROST_BOMB, 6s);
                        break;
                    }
                case EVENT_LAND:
                    me->GetMotionMaster()->MovePoint(POINT_LAND, SindragosaFlyInPos);
                    break;
                case EVENT_LAND_GROUND:
                    events.ScheduleEvent(EVENT_CLEAVE, 13s, 15s, EVENT_GROUP_LAND_PHASE);
                    events.ScheduleEvent(EVENT_TAIL_SMASH, 19s, 23s, EVENT_GROUP_LAND_PHASE);
                    events.ScheduleEvent(EVENT_FROST_BREATH, 7s, 10s, EVENT_GROUP_LAND_PHASE);
                    events.ScheduleEvent(EVENT_UNCHAINED_MAGIC, 12s, 17s, EVENT_GROUP_LAND_PHASE);
                    events.ScheduleEvent(EVENT_ICY_GRIP, 35s, 40s, EVENT_GROUP_LAND_PHASE);
                    me->GetMotionMaster()->MoveLand(POINT_LAND_GROUND, SindragosaLandPos, 10.0f);
                    break;
                case EVENT_THIRD_PHASE_CHECK:
                    if (!_isInAirPhase)
                    {
                        Talk(SAY_PHASE_2);
                        events.ScheduleEvent(EVENT_ICE_TOMB, 7s, 10s);
                        events.RescheduleEvent(EVENT_ICY_GRIP, 35s, 40s, EVENT_GROUP_LAND_PHASE);
                        me->CastSpell(me, SPELL_MYSTIC_BUFFET, true);
                    }
                    else
                        events.ScheduleEvent(EVENT_THIRD_PHASE_CHECK, 5s);
                    break;
                case EVENT_ICE_TOMB:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, LastPhaseIceTombTargetSelector(me)))
                    {
                        Talk(EMOTE_WARN_FROZEN_ORB, target);
                        me->CastSpell(target, SPELL_ICE_TOMB_DUMMY, true);
                        me->CastSpell(target, SPELL_FROST_BEACON, true);
                        if (uint32 evTime = events.GetNextEventTime(EVENT_ICY_GRIP))
                            if (events.GetTimer() > evTime || evTime - events.GetTimer() < 8000)
                                events.RescheduleEvent(EVENT_ICY_GRIP, 8s, EVENT_GROUP_LAND_PHASE);
                    }
                    events.ScheduleEvent(EVENT_ICE_TOMB, 18s, 22s);
                    break;
                default:
                    break;
            }
            if (me->GetVictim() && me->IsWithinMeleeRange(me->GetVictim()) && me->GetMotionMaster()->GetCurrentMovementGeneratorType() != POINT_MOTION_TYPE && !me->IsWithinLOSInMap(me->GetVictim()))
                me->GetMotionMaster()->MoveCharge(me->GetVictim()->GetPositionX(), me->GetVictim()->GetPositionY(), me->GetVictim()->GetPositionZ(), me->GetSpeed(MOVE_RUN), POINT_CHASE_VICTIM);
            DoMeleeAttackIfReady();
        }
References _bombCount, _isInAirPhase, _isThirdPhase, Unit::AttackStop(), Unit::CastSpell(), Unit::DisableRotate(), UnitAI::DoMeleeAttackIfReady(), EMOTE_BERSERK_RAID, EMOTE_WARN_BLISTERING_COLD, EMOTE_WARN_FROZEN_ORB, EVENT_AIR_MOVEMENT, EVENT_AIR_MOVEMENT_FAR, EVENT_AIR_PHASE, EVENT_BERSERK, EVENT_BLISTERING_COLD, EVENT_BLISTERING_COLD_YELL, EVENT_CLEAVE, EVENT_FROST_BOMB, EVENT_FROST_BREATH, EVENT_GROUP_LAND_PHASE, EVENT_ICE_TOMB, EVENT_ICY_GRIP, EVENT_LAND, EVENT_LAND_GROUND, EVENT_TAIL_SMASH, EVENT_THIRD_PHASE_CHECK, EVENT_UNCHAINED_MAGIC, EVENT_UNROOT, MotionMaster::GetCurrentMovementGeneratorType(), WorldObject::GetGameObjectListWithEntryInGrid(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetSpeed(), Unit::GetVictim(), GO_ICE_BLOCK, Unit::HasUnitState(), WorldObject::IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), ScriptedAI::me, MOVE_RUN, MotionMaster::MoveCharge(), MotionMaster::MoveIdle(), MotionMaster::MoveLand(), MotionMaster::MovePoint(), MotionMaster::MoveTakeoff(), POINT_AIR_PHASE, POINT_AIR_PHASE_FAR, POINT_CHASE_VICTIM, POINT_LAND, POINT_LAND_GROUND, POINT_MOTION_TYPE, POINT_TAKEOFF, rand_norm(), REACT_PASSIVE, SAY_AIR_PHASE, SAY_BERSERK, SAY_BLISTERING_COLD, SAY_PHASE_2, SAY_UNCHAINED_MAGIC, UnitAI::SelectTarget(), Unit::SendMeleeAttackStop(), Unit::SendMovementFlagUpdate(), Unit::SetControlled(), Creature::SetDisableGravity(), Creature::SetReactState(), Unit::SetSpeed(), SindragosaAirPos, SindragosaAirPosFar, SindragosaFlyInPos, SindragosaLandPos, SIZE_OF_GRIDS, SPELL_BERSERK, SPELL_BLISTERING_COLD, SPELL_CLEAVE, SPELL_FROST_BEACON, SPELL_FROST_BOMB_TRIGGER, SPELL_FROST_BREATH_P1, SPELL_FROST_BREATH_P2, SPELL_ICE_TOMB_DUMMY, SPELL_ICY_GRIP, SPELL_MYSTIC_BUFFET, SPELL_TAIL_SMASH, SPELL_UNCHAINED_MAGIC, Unit::StopMoving(), UNIT_STATE_CASTING, UNIT_STATE_ROOT, WorldObject::UpdateGroundPositionZ(), and CreatureAI::UpdateVictim().
Member Data Documentation
_bombCount
uint8 boss_sindragosa::boss_sindragosaAI::_bombCount private
Referenced by JustEngagedWith(), MovementInform(), Reset(), and UpdateAI().
_isBelow20Pct
bool boss_sindragosa::boss_sindragosaAI::_isBelow20Pct private
Referenced by DamageTaken(), JustEngagedWith(), and Reset().
_isInAirPhase
bool boss_sindragosa::boss_sindragosaAI::_isInAirPhase private
Referenced by MovementInform(), and UpdateAI().
_isLanding
bool boss_sindragosa::boss_sindragosaAI::_isLanding private
Referenced by DoAction(), and Reset().
_isThirdPhase
bool boss_sindragosa::boss_sindragosaAI::_isThirdPhase private
Referenced by DamageTaken(), JustEngagedWith(), Reset(), and UpdateAI().
_mysticBuffetStack
uint8 boss_sindragosa::boss_sindragosaAI::_mysticBuffetStack private
Referenced by GetData(), JustEngagedWith(), Reset(), and SpellHitTarget().