AzerothCore: OnlyOnceAreaTriggerScript Class Reference
OnlyOnceAreaTriggerScript Class Reference abstract
#include "AreaTriggerScript.h"
Public Member Functions
bool OnTrigger (Player *, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Protected Member Functions
virtual bool _OnTrigger (Player *, AreaTrigger const *)=0
void ResetAreaTriggerDone (InstanceScript *, uint32)
void ResetAreaTriggerDone (Player const *, AreaTrigger const *)
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Private Member Functions
AreaTriggerScript (const char *name)
Detailed Description
Member Function Documentation
_OnTrigger()
virtual bool OnlyOnceAreaTriggerScript::_OnTrigger (Player * , AreaTrigger const *) protected pure virtual
Implemented in at_karazhan_side_entrance, at_sunwell_madrigosa, at_sunwell_eredar_twins, at_rp_nethekurse, at_icc_spire_frostwyrm, at_zulgurub_entrance_speech, at_zulgurub_bridge_speech, at_zulgurub_temple_speech, at_zulgurub_bloodfire_pit_speech, at_zulgurub_edge_of_madness_speech, at_twin_emperors, and at_underbog_ghazan.
Referenced by OnTrigger().
AreaTriggerScript()
AreaTriggerScript::AreaTriggerScript (const char * name) private
    : ScriptObject(name)
{
    ScriptRegistry<AreaTriggerScript>::AddScript(this);
}
OnTrigger()
bool OnlyOnceAreaTriggerScript::OnTrigger (Player * player, AreaTrigger const * trigger) override virtual
Reimplemented from AreaTriggerScript.
{
    uint32 const triggerId = trigger->entry;
    if (InstanceScript* instance = player->GetInstanceScript())
    {
        if (instance->IsAreaTriggerDone(triggerId))
        {
            return true;
        }
        else
        {
            instance->MarkAreaTriggerDone(triggerId);
        }
    }
    return _OnTrigger(player, trigger);
}
References _OnTrigger(), AreaTrigger::entry, and WorldObject::GetInstanceScript().
ResetAreaTriggerDone() [1/2]
void OnlyOnceAreaTriggerScript::ResetAreaTriggerDone (InstanceScript * script, uint32 triggerId) protected
{
    script->ResetAreaTriggerDone(triggerId);
}
References InstanceScript::ResetAreaTriggerDone().
Referenced by ResetAreaTriggerDone().
ResetAreaTriggerDone() [2/2]
void OnlyOnceAreaTriggerScript::ResetAreaTriggerDone (Player const * player, AreaTrigger const * trigger) protected
{
    if (InstanceScript* instance = player->GetInstanceScript())
    {
        ResetAreaTriggerDone(instance, trigger->entry);
    }
}
References AreaTrigger::entry, WorldObject::GetInstanceScript(), and ResetAreaTriggerDone().