AzeorthCore: boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI Struct Reference
boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI Struct Reference
Public Member Functions
boss_shirrak_the_dead_watcherAI (Creature *creature)
void EnterEvadeMode (EvadeReason why) override
void Reset () override
void EnterCombat (Unit *) override
void JustSummoned (Creature *summon) override
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
uint8 getStackCount (float dist)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
Cast Spell.
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
Play sound.
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
Reset Threat.
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
Modify Unit Threat.
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
Teleport player.
void DoTeleportAll (float x, float y, float z, float o)
Teleport all.
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
Set Combat Movement.
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectTargetMethod targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
ObjectGuid focusGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_shirrak_the_dead_watcherAI()
boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::boss_shirrak_the_dead_watcherAI (Creature * creature) inline
                                                            : ScriptedAI(creature)
        {
        }
Member Function Documentation
EnterCombat()
void boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            events.ScheduleEvent(EVENT_SPELL_INHIBIT_MAGIC, 0);
            events.ScheduleEvent(EVENT_SPELL_ATTRACT_MAGIC, 28000);
            events.ScheduleEvent(EVENT_SPELL_CARNIVOROUS, 10000);
            events.ScheduleEvent(EVENT_SPELL_FOCUS_FIRE, 17000);
        }
References EVENT_SPELL_ATTRACT_MAGIC, EVENT_SPELL_CARNIVOROUS, EVENT_SPELL_FOCUS_FIRE, and EVENT_SPELL_INHIBIT_MAGIC.
EnterEvadeMode()
void boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            me->SetControlled(false, UNIT_STATE_ROOT);
            ScriptedAI::EnterEvadeMode(why);
        }
References CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
getStackCount()
uint8 boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::getStackCount (float dist) inline
        {
            if (dist < 15)
                return 4;
            if (dist < 25)
                return 3;
            if (dist < 35)
                return 2;
            return 1;
        }
Referenced by UpdateAI().
JustSummoned()
void boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            summon->CastSpell(summon, SPELL_FOCUS_FIRE_VISUAL, true);
        }
References Unit::CastSpell(), and SPELL_FOCUS_FIRE_VISUAL.
Reset()
void boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Reset();
            focusGUID.Clear();
            me->SetControlled(false, UNIT_STATE_ROOT);
        }
References ObjectGuid::Clear(), focusGUID, ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
SpellHitTarget()
void boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::SpellHitTarget (Unit * target, SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_FOCUS_CAST)
                target->CastSpell(target, DUNGEON_MODE(SPELL_FIERY_BLAST_N, SPELL_FIERY_BLAST_H), false);
        }
References Unit::CastSpell(), ScriptedAI::DUNGEON_MODE(), SpellInfo::Id, SPELL_FIERY_BLAST_H, SPELL_FIERY_BLAST_N, and SPELL_FOCUS_CAST.
UpdateAI()
void boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Update(diff);
            uint32 eventId = events.ExecuteEvent();
            if (eventId == EVENT_SPELL_INHIBIT_MAGIC)
            {
                Map::PlayerList const& PlayerList = me->GetMap()->GetPlayers();
                for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
                    if (Player* player = i->GetSource())
                    {
                        float dist = me->GetDistance(player);
                        if (player->IsAlive() && dist < 45.0f)
{
                            Aura* aura = player->GetAura(SPELL_INHIBIT_MAGIC);
                            if (!aura)
                                aura = me->AddAura(SPELL_INHIBIT_MAGIC, player);
                            else
                                aura->RefreshDuration();
                            if (aura)
                                aura->SetStackAmount(getStackCount(dist));
                        }
                        else
                            player->RemoveAurasDueToSpell(SPELL_INHIBIT_MAGIC);
                    }
                events.RepeatEvent(3000);
                return;
            }
            if (!UpdateVictim())
                return;
            switch (eventId)
            {
                case EVENT_SPELL_ATTRACT_MAGIC:
                    me->CastSpell(me, SPELL_ATTRACT_MAGIC, false);
                    events.RepeatEvent(30000);
                    events.RescheduleEvent(EVENT_SPELL_CARNIVOROUS, 1500);
                    break;
                case EVENT_SPELL_CARNIVOROUS:
                    me->CastSpell(me, DUNGEON_MODE(SPELL_CARNIVOROUS_BITE_N, SPELL_CARNIVOROUS_BITE_H), false);
                    events.RepeatEvent(10000);
                    break;
                case EVENT_SPELL_FOCUS_FIRE:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 60.0f, true))
                    {
                        if (Creature* cr = me->SummonCreature(ENTRY_FOCUS_FIRE, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN, 7000))
                            focusGUID = cr->GetGUID();
                        Talk(EMOTE_FOCUSED, target);
                    }
                    events.RepeatEvent(urand(15000, 20000));
                    events.ScheduleEvent(EVENT_SPELL_FOCUS_FIRE_2, 3000);
                    events.ScheduleEvent(EVENT_SPELL_FOCUS_FIRE_2, 3500);
                    events.ScheduleEvent(EVENT_SPELL_FOCUS_FIRE_2, 4000);
                    events.ScheduleEvent(EVENT_SPELL_FOCUS_FIRE_3, 5000);
                    me->SetControlled(true, UNIT_STATE_ROOT);
                    break;
                case EVENT_SPELL_FOCUS_FIRE_2:
                    if (Unit* flare = ObjectAccessor::GetCreature(*me, focusGUID))
                        me->CastSpell(flare, SPELL_FOCUS_CAST, true);
                    break;
                case EVENT_SPELL_FOCUS_FIRE_3:
                    me->SetControlled(false, UNIT_STATE_ROOT);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::AddAura(), MapRefMgr::begin(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DUNGEON_MODE(), EMOTE_FOCUSED, MapRefMgr::end(), ENTRY_FOCUS_FIRE, EVENT_SPELL_ATTRACT_MAGIC, EVENT_SPELL_CARNIVOROUS, EVENT_SPELL_FOCUS_FIRE, EVENT_SPELL_FOCUS_FIRE_2, EVENT_SPELL_FOCUS_FIRE_3, EVENT_SPELL_INHIBIT_MAGIC, focusGUID, ObjectAccessor::GetCreature(), WorldObject::GetDistance(), WorldObject::GetMap(), Map::GetPlayers(), getStackCount(), ScriptedAI::me, Aura::RefreshDuration(), UnitAI::SelectTarget(), Unit::SetControlled(), Aura::SetStackAmount(), SPELL_ATTRACT_MAGIC, SPELL_CARNIVOROUS_BITE_H, SPELL_CARNIVOROUS_BITE_N, SPELL_FOCUS_CAST, SPELL_INHIBIT_MAGIC, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_ROOT, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::events
focusGUID
ObjectGuid boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::focusGUID
Referenced by Reset(), and UpdateAI().