AzerothCore: npc_medivh_bm Struct Reference
npc_medivh_bm Struct Reference
Public Member Functions
npc_medivh_bm (Creature *creature)
void Reset () override
void JustSummoned (Creature *summon) override
void MoveInLineOfSight (Unit *who) override
void AttackStart (Unit *) override
void DoAction (int32 param) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
void SummonOrcs (float x, float y, uint32 duration, uint32 homeTime, bool first)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
InstanceScript * _instance
EventMap _events
Movement::PointsArray _groundArray
Movement::PointsArray _airArray
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_medivh_bm()
npc_medivh_bm::npc_medivh_bm (Creature * creature) inline
                                      : ScriptedAI(creature)
    {
        _instance = creature->GetInstanceScript();
        _groundArray.clear();
        _airArray.clear();
        _groundArray.push_back(G3D::Vector3(creature->GetPositionX() + 8.0f, creature->GetPositionY(), creature->GetPositionZ()));
        _airArray.push_back(G3D::Vector3(creature->GetPositionX(), creature->GetPositionY(), creature->GetPositionZ()));
        for (uint8 i = 0; i < 10; ++i)
        {
            _groundArray.push_back(G3D::Vector3(creature->GetPositionX() + 8.0f * cos(2.0f * M_PI * i / 10.0f), creature->GetPositionY() + 8.0f * std::sin(2.0f * M_PI * i / 10.0f), creature->GetPositionZ()));
        }
        for (uint8 i = 0; i < 40; ++i)
        {
            _airArray.push_back(G3D::Vector3(creature->GetPositionX() + i * 0.25f * cos(2.0f * M_PI * i / 10.0f), creature->GetPositionY() + i * 0.25f * std::sin(2.0f * M_PI * i / 10.0f), creature->GetPositionZ() + i / 4.0f));
        }
        for (uint8 i = 40; i < 80; ++i)
        {
            _airArray.push_back(G3D::Vector3(creature->GetPositionX() + 10.0f * cos(2.0f * M_PI * i / 10.0f), creature->GetPositionY() + 10.0f * std::sin(2.0f * M_PI * i / 10.0f), creature->GetPositionZ() + i / 4.0f));
        }
    }
References _airArray, _groundArray, _instance, WorldObject::GetInstanceScript(), Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
Member Function Documentation
AttackStart()
void npc_medivh_bm::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
{ }
DoAction()
void npc_medivh_bm::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
    {
        if (param == ACTION_OUTRO)
        {
            events.Reset();
            events.ScheduleEvent(EVENT_OUTRO_1, 4000);
            me->InterruptNonMeleeSpells(true);
            me->SummonGameObject(GO_DARK_PORTAL, -2086.0f, 7125.6215f, 30.5f, 6.148f, 0.0f, 0.0f, 0.0f, 0.0f, 0);
        }
    }
References ACTION_OUTRO, EVENT_OUTRO_1, GO_DARK_PORTAL, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, and WorldObject::SummonGameObject().
JustDied()
void npc_medivh_bm::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        me->SetRespawnTime(DAY);
        events.Reset();
    }
References DAY, ScriptedAI::me, and Creature::SetRespawnTime().
JustSummoned()
void npc_medivh_bm::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (summon->GetEntry() == NPC_DP_CRYSTAL_STALKER)
        {
            summon->DespawnOrUnsummon(25000);
            summon->CastSpell(summon, RAND(SPELL_BANISH_PURPLE, SPELL_BANISH_GREEN), true);
            summon->GetMotionMaster()->MoveSplinePath(&_airArray);
        }
        else if (summon->GetEntry() == NPC_DP_EMITTER_STALKER)
        {
            summon->CastSpell(summon, SPELL_BLACK_CRYSTAL, true);
            Movement::MoveSplineInit init(summon);
            init.MovebyPath(_groundArray);
            init.SetCyclic();
            init.Launch();
        }
    }
References _airArray, _groundArray, Unit::CastSpell(), Creature::DespawnOrUnsummon(), Object::GetEntry(), Unit::GetMotionMaster(), Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MovebyPath(), MotionMaster::MoveSplinePath(), NPC_DP_CRYSTAL_STALKER, NPC_DP_EMITTER_STALKER, RAND(), Movement::MoveSplineInit::SetCyclic(), SPELL_BANISH_GREEN, SPELL_BANISH_PURPLE, and SPELL_BLACK_CRYSTAL.
MoveInLineOfSight()
void npc_medivh_bm::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
    {
        if (!events.Empty() || _instance->GetBossState(DATA_AEONUS) == DONE)
        {
            return;
        }
        if (who->GetTypeId() == TYPEID_PLAYER && me->IsWithinDistInMap(who, 20.0f))
        {
            Talk(SAY_MEDIVH_ENTER);
            _instance->SetData(DATA_MEDIVH, 1);
            me->CastSpell(me, SPELL_MEDIVH_CHANNEL, false);
            events.ScheduleEvent(EVENT_CHECK_HEALTH_75, 500);
            events.ScheduleEvent(EVENT_CHECK_HEALTH_50, 500);
            events.ScheduleEvent(EVENT_CHECK_HEALTH_25, 500);
            events.ScheduleEvent(EVENT_SUMMON_CRYSTAL, 2000);
            events.ScheduleEvent(EVENT_SUMMON_CRYSTAL, 4000);
            events.ScheduleEvent(EVENT_SUMMON_CRYSTAL, 6000);
            events.ScheduleEvent(EVENT_SUMMON_FLYING_CRYSTAL, 8000);
        }
    }
References _instance, Unit::CastSpell(), DATA_AEONUS, DATA_MEDIVH, DONE, EVENT_CHECK_HEALTH_25, EVENT_CHECK_HEALTH_50, EVENT_CHECK_HEALTH_75, EVENT_SUMMON_CRYSTAL, EVENT_SUMMON_FLYING_CRYSTAL, InstanceScript::GetBossState(), Object::GetTypeId(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, SAY_MEDIVH_ENTER, ZoneScript::SetData(), SPELL_MEDIVH_CHANNEL, and TYPEID_PLAYER.
Reset()
void npc_medivh_bm::Reset () inline override virtual
Reimplemented from ScriptedAI.
    {
        events.Reset();
        me->CastSpell(me, SPELL_MANA_SHIELD, true);
        if (_instance->GetBossState(DATA_AEONUS) != DONE)
        {
            me->CastSpell(me, SPELL_MEDIVH_CHANNEL, false);
        }
        me->SetImmuneToNPC(false);
    }
References _instance, Unit::CastSpell(), DATA_AEONUS, DONE, InstanceScript::GetBossState(), ScriptedAI::me, Unit::SetImmuneToNPC(), SPELL_MANA_SHIELD, and SPELL_MEDIVH_CHANNEL.
SummonOrcs()
void npc_medivh_bm::SummonOrcs (float x, float y, uint32 duration, uint32 homeTime, bool first) inline
    {
        for (uint8 i = 0; i < 6; ++i)
        {
            if (Creature* cr = me->SummonCreature(NPC_SHADOW_COUNCIL_ENFORCER, -2091.731f, 7133.083f - 3.0f * i, 34.589f, 0.0f))
            {
                cr->GetMotionMaster()->MovePoint(0, (first && i == 3) ? x + 2.0f : x, cr->GetPositionY() + y, cr->GetMapHeight(x, cr->GetPositionY() + y, cr->GetPositionZ(), true));
                cr->m_Events.AddEvent(new NpcRunToHome(*cr), cr->m_Events.CalculateTime(homeTime + urand(0, 2000)));
                cr->DespawnOrUnsummon(duration + urand(0, 2000));
            }
        }
    }
References ScriptedAI::me, NPC_SHADOW_COUNCIL_ENFORCER, WorldObject::SummonCreature(), and urand().
Referenced by UpdateAI().
UpdateAI()
void npc_medivh_bm::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
    {
        events.Update(diff);
        switch (uint32 eventId = events.ExecuteEvent())
        {
            case EVENT_CHECK_HEALTH_25:
            case EVENT_CHECK_HEALTH_50:
            case EVENT_CHECK_HEALTH_75:
                if (_instance->GetData(DATA_SHIELD_PERCENT) <= eventId * 25)
                {
                    Talk(eventId + 1);
                    break;
                }
                events.ScheduleEvent(eventId, 500);
                break;
            case EVENT_SUMMON_CRYSTAL:
                me->SummonCreature(NPC_DP_EMITTER_STALKER, me->GetPositionX() + 8.0f, me->GetPositionY(), me->GetPositionZ());
                break;
            case EVENT_SUMMON_FLYING_CRYSTAL:
                me->CastSpell(me, SPELL_PORTAL_CRYSTALS, true);
                events.ScheduleEvent(EVENT_SUMMON_FLYING_CRYSTAL, 1000);
                break;
            case EVENT_OUTRO_1:
                me->SetFacingTo(6.21f);
                Talk(SAY_MEDIVH_WIN);
                events.ScheduleEvent(EVENT_OUTRO_2, 17000);
                break;
            case EVENT_OUTRO_2:
                me->SetFacingTo(3.07f);
                events.ScheduleEvent(EVENT_OUTRO_3, 2000);
                break;
            case EVENT_OUTRO_3:
                SummonOrcs(-2046.158f, -3.0f, 37000, 30000, true);
                events.ScheduleEvent(EVENT_OUTRO_4, 2000);
                break;
            case EVENT_OUTRO_4:
                SummonOrcs(-2055.97f, -2.0f, 33000, 28000, false);
                events.ScheduleEvent(EVENT_OUTRO_5, 2000);
                break;
            case EVENT_OUTRO_5:
                SummonOrcs(-2064.0f, -1.5f, 29000, 26000, false);
                events.ScheduleEvent(EVENT_OUTRO_6, 2000);
                break;
            case EVENT_OUTRO_6:
                SummonOrcs(-2074.35f, -0.1f, 26000, 24000, false);
                events.ScheduleEvent(EVENT_OUTRO_7, 7000);
                break;
            case EVENT_OUTRO_7:
                Talk(SAY_MEDIVH_ORCS_ENTER);
                events.ScheduleEvent(EVENT_OUTRO_8, 7000);
                break;
            case EVENT_OUTRO_8:
                if (Creature* cr = me->FindNearestCreature(NPC_SHADOW_COUNCIL_ENFORCER, 20.0f))
                {
                    cr->SetFacingTo(3.07f);
                    cr->AI()->Talk(SAY_MEDIVH_ORCS_ANSWER);
                }
                break;
        }
    }
References _instance, Unit::CastSpell(), DATA_SHIELD_PERCENT, EVENT_CHECK_HEALTH_25, EVENT_CHECK_HEALTH_50, EVENT_CHECK_HEALTH_75, EVENT_OUTRO_1, EVENT_OUTRO_2, EVENT_OUTRO_3, EVENT_OUTRO_4, EVENT_OUTRO_5, EVENT_OUTRO_6, EVENT_OUTRO_7, EVENT_OUTRO_8, EVENT_SUMMON_CRYSTAL, EVENT_SUMMON_FLYING_CRYSTAL, WorldObject::FindNearestCreature(), ZoneScript::GetData(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, NPC_DP_EMITTER_STALKER, NPC_SHADOW_COUNCIL_ENFORCER, SAY_MEDIVH_ORCS_ANSWER, SAY_MEDIVH_ORCS_ENTER, SAY_MEDIVH_WIN, Unit::SetFacingTo(), SPELL_PORTAL_CRYSTALS, WorldObject::SummonCreature(), and SummonOrcs().
Member Data Documentation
_airArray
Movement::PointsArray npc_medivh_bm::_airArray private
Referenced by JustSummoned(), and npc_medivh_bm().
_events
EventMap npc_medivh_bm::_events private
_groundArray
Movement::PointsArray npc_medivh_bm::_groundArray private
Referenced by JustSummoned(), and npc_medivh_bm().
_instance
InstanceScript* npc_medivh_bm::_instance private
Referenced by MoveInLineOfSight(), npc_medivh_bm(), Reset(), and UpdateAI().