AzerothCore: Acore::NearestHostileUnitInAttackDistanceCheck Class Reference
Acore::NearestHostileUnitInAttackDistanceCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
NearestHostileUnitInAttackDistanceCheck (Creature const *creature, float dist)
bool operator() (Unit *u)
Private Member Functions
NearestHostileUnitInAttackDistanceCheck (NearestHostileUnitInAttackDistanceCheck const &)
Private Attributes
Creature const * me
float m_range
Detailed Description
Constructor & Destructor Documentation
NearestHostileUnitInAttackDistanceCheck() [1/2]
Acore::NearestHostileUnitInAttackDistanceCheck::NearestHostileUnitInAttackDistanceCheck (Creature const * creature, float dist) inline explicit
: me(creature), m_range(dist) {}
NearestHostileUnitInAttackDistanceCheck() [2/2]
Acore::NearestHostileUnitInAttackDistanceCheck::NearestHostileUnitInAttackDistanceCheck (NearestHostileUnitInAttackDistanceCheck const &) private
Member Function Documentation
operator()()
bool Acore::NearestHostileUnitInAttackDistanceCheck::operator() (Unit * u) inline
        {
            if (!me->IsWithinDistInMap(u, m_range, true, false))
                return false;
            if (!me->CanStartAttack(u))
                return false;
            m_range = me->GetDistance(u);   // use found unit range as new range limit for next check
            return true;
        }
References Creature::CanStartAttack(), WorldObject::GetDistance(), WorldObject::IsWithinDistInMap(), m_range, and me.
Member Data Documentation
m_range
float Acore::NearestHostileUnitInAttackDistanceCheck::m_range private
Referenced by operator()().
me
Creature const* Acore::NearestHostileUnitInAttackDistanceCheck::me private
Referenced by operator()().