AzerothCore: npc_millhouse_manastorm::npc_millhouse_manastormAI Struct Reference
npc_millhouse_manastorm::npc_millhouse_manastormAI Struct Reference
Public Member Functions
npc_millhouse_manastormAI (Creature *creature)
void InitializeAI () override
void Reset () override
void AttackStart (Unit *who) override
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
EventMap events
EventMap events2
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_millhouse_manastormAI()
npc_millhouse_manastorm::npc_millhouse_manastormAI::npc_millhouse_manastormAI (Creature * creature) inline
                                                      : ScriptedAI(creature)
        {
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
AttackStart()
void npc_millhouse_manastorm::npc_millhouse_manastormAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (who && me->Attack(who, true))
                me->GetMotionMaster()->MoveChase(who, 20.0f);
        }
References Unit::Attack(), Unit::GetMotionMaster(), ScriptedAI::me, and MotionMaster::MoveChase().
Referenced by UpdateAI().
InitializeAI()
void npc_millhouse_manastorm::npc_millhouse_manastormAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
        {
            ScriptedAI::InitializeAI();
            me->SetReactState(REACT_PASSIVE);
            me->SetImmuneToAll(true);
            events2.Reset();
            events2.ScheduleEvent(EVENT_TELEPORT_VISUAL, 0);
            events2.ScheduleEvent(EVENT_MILLHOUSE_INTRO1, 3000);
        }
References EVENT_MILLHOUSE_INTRO1, EVENT_TELEPORT_VISUAL, events2, UnitAI::InitializeAI(), ScriptedAI::me, REACT_PASSIVE, EventMap::Reset(), EventMap::ScheduleEvent(), Unit::SetImmuneToAll(), and Creature::SetReactState().
JustDied()
void npc_millhouse_manastorm::npc_millhouse_manastormAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_DEATH);
        }
References SAY_DEATH.
JustEngagedWith()
void npc_millhouse_manastorm::npc_millhouse_manastormAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            events.ScheduleEvent(EVENT_MILL_CHECK_HEALTH, 1000);
            events.ScheduleEvent(EVENT_MILL_PYROBLAST, 30000);
            events.ScheduleEvent(EVENT_MILL_BASE_SPELL, 2000);
            events.ScheduleEvent(EVENT_MILL_ICEBLOCK, 1000);
        }
References EVENT_MILL_BASE_SPELL, EVENT_MILL_CHECK_HEALTH, EVENT_MILL_ICEBLOCK, and EVENT_MILL_PYROBLAST.
KilledUnit()
void npc_millhouse_manastorm::npc_millhouse_manastormAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_KILL);
        }
References SAY_KILL.
Reset()
void npc_millhouse_manastorm::npc_millhouse_manastormAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            events.Reset();
        }
UpdateAI()
void npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            events2.Update(diff);
            switch (events2.ExecuteEvent())
            {
                case EVENT_TELEPORT_VISUAL:
                    me->CastSpell(me, SPELL_TELEPORT_VISUAL, true);
                    break;
                case EVENT_MILLHOUSE_INTRO1:
                    Talk(SAY_INTRO_1);
                    events2.ScheduleEvent(EVENT_MILLHOUSE_INTRO2, 18000);
                    break;
                case EVENT_MILLHOUSE_INTRO2:
                    Talk(SAY_INTRO_2);
                    events2.ScheduleEvent(EVENT_MILLHOUSE_INTRO3, 8000);
                    break;
                case EVENT_MILLHOUSE_INTRO3:
                    Talk(SAY_INTRO_3);
                    events2.ScheduleEvent(EVENT_MILLHOUSE_INTRO4, 6000);
                    break;
                case EVENT_MILLHOUSE_INTRO4:
                    Talk(SAY_INTRO_4);
                    events2.ScheduleEvent(EVENT_MILLHOUSE_INTRO5, 8000);
                    break;
                case EVENT_MILLHOUSE_INTRO5:
                    Talk(SAY_WATER);
                    me->CastSpell(me, SPELL_CONJURE_WATER, false);
                    events2.ScheduleEvent(EVENT_MILLHOUSE_INTRO6, 7000);
                    break;
                case EVENT_MILLHOUSE_INTRO6:
                    Talk(SAY_BUFFS);
                    me->CastSpell(me, SPELL_ICE_ARMOR, false);
                    events2.ScheduleEvent(EVENT_MILLHOUSE_INTRO7, 7000);
                    break;
                case EVENT_MILLHOUSE_INTRO7:
                    Talk(SAY_DRINK);
                    me->CastSpell(me, SPELL_ARCANE_INTELLECT, false);
                    events2.ScheduleEvent(EVENT_MILLHOUSE_INTRO8, 7000);
                    break;
                case EVENT_MILLHOUSE_INTRO8:
                    Talk(SAY_READY);
                    me->GetMotionMaster()->MovePoint(1, 445.82f, -158.38f, 43.067f);
                    events2.ScheduleEvent(EVENT_MILLHOUSE_INTRO9, 5000);
                    break;
                case EVENT_MILLHOUSE_INTRO9:
                    me->SetFacingTo(M_PI * 1.5f);
                    me->SetHomePosition(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), M_PI * 1.5f);
                    me->SetImmuneToAll(false);
                    me->SetReactState(REACT_AGGRESSIVE);
                    events2.ScheduleEvent(EVENT_SEARCH_FIGHT, 1000);
                    break;
                case EVENT_SEARCH_FIGHT:
                    if (!me->IsInCombat() && !me->IsInEvadeMode())
                        if (Unit* target = me->SelectNearbyTarget(nullptr, 30.0f))
                            AttackStart(target);
                    events2.ScheduleEvent(EVENT_SEARCH_FIGHT, 1000);
                    break;
            }
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_MILL_CHECK_HEALTH:
                    if (HealthBelowPct(20))
                    {
                        Talk(SAY_LOWHP);
                        break;
                    }
                    events.ScheduleEvent(EVENT_MILL_CHECK_HEALTH, 1000);
                    break;
                case EVENT_MILL_PYROBLAST:
                    Talk(SAY_PYRO);
                    me->CastSpell(me->GetVictim(), SPELL_PYROBLAST, false);
                    events.ScheduleEvent(EVENT_MILL_PYROBLAST, 30000);
                    break;
                case EVENT_MILL_ICEBLOCK:
                    if (me->GetDistance(me->GetVictim()) < 5.0f)
                    {
                        Talk(SAY_ICEBLOCK);
                        me->CastSpell(me, SPELL_ICEBLOCK, true);
                        break;
                    }
                    events.ScheduleEvent(EVENT_MILL_ICEBLOCK, 1000);
                    break;
                case EVENT_MILL_BASE_SPELL:
                    switch (RAND(SPELL_FIREBALL, SPELL_ARCANE_MISSILES, SPELL_FROSTBOLT))
                    {
                        case SPELL_FIREBALL:
                            me->CastSpell(me->GetVictim(), SPELL_FIREBALL, false);
                            events.ScheduleEvent(EVENT_MILL_BASE_SPELL, 4000);
                            break;
                        case SPELL_ARCANE_MISSILES:
                            me->CastSpell(me->GetVictim(), SPELL_ARCANE_MISSILES, false);
                            events.ScheduleEvent(EVENT_MILL_BASE_SPELL, 9000);
                            break;
                        case SPELL_FROSTBOLT:
                            me->CastSpell(me->GetVictim(), SPELL_FROSTBOLT, false);
                            events.ScheduleEvent(EVENT_MILL_BASE_SPELL, 4000);
                            break;
                        default:
                            break;
                    }
                    break;
            }
            DoMeleeAttackIfReady();
        }
References AttackStart(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_MILL_BASE_SPELL, EVENT_MILL_CHECK_HEALTH, EVENT_MILL_ICEBLOCK, EVENT_MILL_PYROBLAST, EVENT_MILLHOUSE_INTRO1, EVENT_MILLHOUSE_INTRO2, EVENT_MILLHOUSE_INTRO3, EVENT_MILLHOUSE_INTRO4, EVENT_MILLHOUSE_INTRO5, EVENT_MILLHOUSE_INTRO6, EVENT_MILLHOUSE_INTRO7, EVENT_MILLHOUSE_INTRO8, EVENT_MILLHOUSE_INTRO9, EVENT_SEARCH_FIGHT, EVENT_TELEPORT_VISUAL, events2, EventMap::ExecuteEvent(), WorldObject::GetDistance(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), Unit::IsInCombat(), Creature::IsInEvadeMode(), ScriptedAI::me, MotionMaster::MovePoint(), RAND(), REACT_AGGRESSIVE, SAY_BUFFS, SAY_DRINK, SAY_ICEBLOCK, SAY_INTRO_1, SAY_INTRO_2, SAY_INTRO_3, SAY_INTRO_4, SAY_LOWHP, SAY_PYRO, SAY_READY, SAY_WATER, EventMap::ScheduleEvent(), Unit::SelectNearbyTarget(), Unit::SetFacingTo(), Creature::SetHomePosition(), Unit::SetImmuneToAll(), Creature::SetReactState(), SPELL_ARCANE_INTELLECT, SPELL_ARCANE_MISSILES, SPELL_CONJURE_WATER, SPELL_FIREBALL, SPELL_FROSTBOLT, SPELL_ICE_ARMOR, SPELL_ICEBLOCK, SPELL_PYROBLAST, SPELL_TELEPORT_VISUAL, UNIT_STATE_CASTING, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap npc_millhouse_manastorm::npc_millhouse_manastormAI::events
events2
EventMap npc_millhouse_manastorm::npc_millhouse_manastormAI::events2
Referenced by InitializeAI(), and UpdateAI().
instance
InstanceScript* npc_millhouse_manastorm::npc_millhouse_manastormAI::instance
Referenced by npc_millhouse_manastormAI().