AzerothCore: Acore::UnitLastSearcher< Check > Struct Template Reference
Acore::UnitLastSearcher< Check > Struct Template Reference
#include "GridNotifiers.h"
Public Member Functions
UnitLastSearcher (WorldObject const *searcher, Unit *&result, Check &check)
void Visit (CreatureMapType &m)
void Visit (PlayerMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_phaseMask
Unit *& i_object
Check & i_check
Detailed Description
template<class Check>
struct Acore::UnitLastSearcher< Check >
Constructor & Destructor Documentation
UnitLastSearcher()
template<class Check > Acore::UnitLastSearcher< Check >::UnitLastSearcher (WorldObject const * searcher, Unit *& result, Check & check) inline
            : i_phaseMask(searcher->GetPhaseMask()), i_object(result), i_check(check) {}
Member Function Documentation
Visit() [1/3]
template<class Check > void Acore::UnitLastSearcher< Check >::Visit (CreatureMapType & m)
{
    for (CreatureMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
    {
        if (!itr->GetSource()->InSamePhase(i_phaseMask))
            continue;
        if (i_check(itr->GetSource()))
            i_object = itr->GetSource();
    }
}
References GridRefMgr< OBJECT >::begin(), and GridRefMgr< OBJECT >::end().
Visit() [2/3]
template<class Check > template<class NOT_INTERESTED > void Acore::UnitLastSearcher< Check >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
{}
Visit() [3/3]
template<class Check > void Acore::UnitLastSearcher< Check >::Visit (PlayerMapType & m)
{
    for (PlayerMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
    {
        if (!itr->GetSource()->InSamePhase(i_phaseMask))
            continue;
        if (i_check(itr->GetSource()))
            i_object = itr->GetSource();
    }
}
References GridRefMgr< OBJECT >::begin(), and GridRefMgr< OBJECT >::end().
Member Data Documentation
i_check
template<class Check > Check& Acore::UnitLastSearcher< Check >::i_check
i_object
template<class Check > Unit*& Acore::UnitLastSearcher< Check >::i_object
i_phaseMask
template<class Check > uint32 Acore::UnitLastSearcher< Check >::i_phaseMask