AzerothCore: Acore::MostHPMissingInRange Class Reference
Acore::MostHPMissingInRange Class Reference
#include "GridNotifiers.h"
Public Member Functions
MostHPMissingInRange (Unit const *obj, float range, uint32 hp)
bool operator() (Unit *u)
Private Attributes
Unit const * i_obj
float i_range
uint32 i_hp
Detailed Description
Constructor & Destructor Documentation
MostHPMissingInRange()
Acore::MostHPMissingInRange::MostHPMissingInRange (Unit const * obj, float range, uint32 hp) inline
: i_obj(obj), i_range(range), i_hp(hp) {}
Member Function Documentation
operator()()
bool Acore::MostHPMissingInRange::operator() (Unit * u) inline
        {
            if (u->IsAlive() && u->IsInCombat() && !i_obj->IsHostileTo(u) && i_obj->IsWithinDistInMap(u, i_range) && u->GetMaxHealth() - u->GetHealth() > i_hp)
            {
                i_hp = u->GetMaxHealth() - u->GetHealth();
                return true;
            }
            return false;
        }
References Unit::GetHealth(), Unit::GetMaxHealth(), i_hp, i_obj, i_range, Unit::IsAlive(), Unit::IsHostileTo(), Unit::IsInCombat(), and WorldObject::IsWithinDistInMap().
Member Data Documentation
i_hp
uint32 Acore::MostHPMissingInRange::i_hp private
Referenced by operator()().
i_obj
Unit const* Acore::MostHPMissingInRange::i_obj private
Referenced by operator()().
i_range
float Acore::MostHPMissingInRange::i_range private
Referenced by operator()().