AzerothCore: MapEntry Struct Reference
MapEntry Struct Reference
#include "DBCStructure.h"
Public Member Functions
uint32 Expansion () const
bool IsDungeon () const
bool IsNonRaidDungeon () const
bool Instanceable () const
bool IsRaid () const
bool IsBattleground () const
bool IsBattleArena () const
bool IsBattlegroundOrArena () const
bool IsWorldMap () const
bool GetEntrancePos (int32 &mapid, float &x, float &y) const
bool IsContinent () const
bool IsDynamicDifficultyMap () const
Public Attributes
uint32 MapID
uint32 map_type
uint32 Flags
char const * name [16]
uint32 linked_zone
uint32 multimap_id
int32 entrance_map
float entrance_x
float entrance_y
uint32 expansionID
uint32 maxPlayers
Detailed Description
Member Function Documentation
Expansion()
uint32 MapEntry::Expansion () const inline
{ return expansionID; }
References expansionID.
Referenced by GetContentLevelsForMapAndZone(), Player::LoadFromDB(), and Player::TeleportTo().
GetEntrancePos()
bool MapEntry::GetEntrancePos (int32 & mapid, float & x, float & y) const inline
    {
        if (entrance_map < 0)
            return false;
        mapid = entrance_map;
        x = entrance_x;
        y = entrance_y;
        return true;
    }
References entrance_map, entrance_x, and entrance_y.
Referenced by Map::GetEntrancePos().
Instanceable()
bool MapEntry::Instanceable () const inline
{ return map_type == MAP_INSTANCE || map_type == MAP_RAID || map_type == MAP_BATTLEGROUND || map_type == MAP_ARENA; }
References MAP_ARENA, MAP_BATTLEGROUND, MAP_INSTANCE, MAP_RAID, and map_type.
Referenced by InstanceSaveMgr::_ResetOrWarnAll(), MapMgr::CreateBaseMap(), misc_commandscript::HandleSkirmishCommand(), Map::Instanceable(), Player::LoadFromDB(), ObjectMgr::LoadLinkedRespawn(), ObjectMgr::SetCreatureLinkedRespawn(), World::SetInitialWorldSettings(), and Player::TeleportTo().
IsBattleArena()
bool MapEntry::IsBattleArena () const inline
{ return map_type == MAP_ARENA; }
References MAP_ARENA, and map_type.
Referenced by SpellInfo::CheckLocation(), Map::IsBattleArena(), and Player::TeleportTo().
IsBattleground()
bool MapEntry::IsBattleground () const inline
{ return map_type == MAP_BATTLEGROUND; }
References MAP_BATTLEGROUND, and map_type.
Referenced by SpellInfo::CheckLocation(), and Map::IsBattleground().
IsBattlegroundOrArena()
bool MapEntry::IsBattlegroundOrArena () const inline
{ return map_type == MAP_BATTLEGROUND || map_type == MAP_ARENA; }
References MAP_ARENA, MAP_BATTLEGROUND, and map_type.
Referenced by Graveyard::GetClosestGraveyard(), WorldSession::HandleMoveWorldportAck(), tele_commandscript::HandleTeleCommand(), tele_commandscript::HandleTeleGroupCommand(), Map::IsBattlegroundOrArena(), Player::LoadFromDB(), and Player::TeleportTo().
IsContinent()
bool MapEntry::IsContinent () const inline
    {
        return MapID == 0 || MapID == 1 || MapID == 530 || MapID == 571;
    }
References MapID.
IsDungeon()
bool MapEntry::IsDungeon () const inline
{ return map_type == MAP_INSTANCE || map_type == MAP_RAID; }
References MAP_INSTANCE, MAP_RAID, and map_type.
Referenced by Spell::CheckCast(), ObjectMgr::GetGoBackTrigger(), WorldSession::HandleMoveWorldportAck(), DisableMgr::IsDisabledFor(), Map::IsDungeon(), MapMgr::IsValidMAP(), ObjectMgr::LoadCreatures(), Player::LoadFromDB(), lfg::LFGPlayerScript::OnBindToInstance(), and MapMgr::PlayerCannotEnter().
IsDynamicDifficultyMap()
bool MapEntry::IsDynamicDifficultyMap () const inline
{ return Flags & MAP_FLAG_DYNAMIC_DIFFICULTY; }
References Flags, and MAP_FLAG_DYNAMIC_DIFFICULTY.
IsNonRaidDungeon()
bool MapEntry::IsNonRaidDungeon () const inline
{ return map_type == MAP_INSTANCE; }
References MAP_INSTANCE, and map_type.
Referenced by Map::IsNonRaidDungeon(), Player::LoadFromDB(), and MapMgr::PlayerCannotEnter().
IsRaid()
bool MapEntry::IsRaid () const inline
{ return map_type == MAP_RAID; }
References MAP_RAID, and map_type.
Referenced by InstanceSaveMgr::AddInstanceSave(), SpellInfo::CheckLocation(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandleSetSavedInstanceExtend(), lfg::LFGMgr::InitializeLockedDungeons(), DisableMgr::IsDisabledFor(), Map::IsRaid(), ObjectMgr::LoadCreatures(), Player::LoadFromDB(), MapMgr::PlayerCannotEnter(), Player::ResetInstances(), Group::ResetInstances(), and Player::Satisfy().
IsWorldMap()
bool MapEntry::IsWorldMap () const inline
{ return map_type == MAP_COMMON; }
References MAP_COMMON, and map_type.
Referenced by Map::IsWorldMap().
Member Data Documentation
entrance_map
int32 MapEntry::entrance_map
Referenced by Graveyard::GetClosestGraveyard(), GetEntrancePos(), and ObjectMgr::GetGoBackTrigger().
entrance_x
float MapEntry::entrance_x
Referenced by Graveyard::GetClosestGraveyard(), and GetEntrancePos().
entrance_y
float MapEntry::entrance_y
Referenced by Graveyard::GetClosestGraveyard(), and GetEntrancePos().
expansionID
uint32 MapEntry::expansionID
Referenced by Expansion().
Flags
uint32 MapEntry::Flags
Referenced by IsDynamicDifficultyMap().
linked_zone
uint32 MapEntry::linked_zone
Referenced by Map::GetAreaId(), and Map::GetFullTerrainStatusForPosition().
map_type
uint32 MapEntry::map_type
Referenced by InstanceSaveMgr::AddInstanceSave(), InstanceSave::GetResetTimeForDB(), Instanceable(), IsBattleArena(), IsBattleground(), IsBattlegroundOrArena(), DisableMgr::IsDisabledFor(), IsDungeon(), IsNonRaidDungeon(), IsRaid(), IsWorldMap(), DisableMgr::LoadDisables(), and Pet::setDeathState().
MapID
uint32 MapEntry::MapID
Referenced by Map::GetId(), WorldSession::HandleMoveWorldportAck(), IsContinent(), MapMgr::PlayerCannotEnter(), and World::SetInitialWorldSettings().
maxPlayers
uint32 MapEntry::maxPlayers
Referenced by InstanceMap::GetMaxPlayers().
multimap_id
uint32 MapEntry::multimap_id
name
char const* MapEntry::name[16]
Referenced by Map::GetMapName(), misc_commandscript::HandleGPSCommand(), misc_commandscript::HandlePInfoCommand(), and MapMgr::PlayerCannotEnter().