AzeorthCore: anonymous_namespace{AllMapScript.cpp} Namespace Reference
anonymous_namespace{AllMapScript.cpp} Namespace Reference
Functions
template<class ScriptName >
void ForeachMaps (Map *map, std::function< void(ScriptName *)> executeHook)
template<>
void ForeachMaps (Map *map, std::function< void(WorldMapScript *)> executeHook)
template<>
void ForeachMaps (Map *map, std::function< void(InstanceMapScript *)> executeHook)
template<>
void ForeachMaps (Map *map, std::function< void(BattlegroundMapScript *)> executeHook)
Function Documentation
ForeachMaps() [1/4]
template<> void anonymous_namespace{AllMapScript.cpp}::ForeachMaps (Map * map, std::function< void(BattlegroundMapScript *)> executeHook) inline
    {
        auto mapEntry = map->GetEntry();
        if (!mapEntry)
        {
            return;
        }
        if (!mapEntry->IsBattleground())
        {
            return;
        }
        if (ScriptRegistry<BattlegroundMapScript>::ScriptPointerList.empty())
        {
            return;
        }
        for (auto const& [scriptID, script] : ScriptRegistry<BattlegroundMapScript>::ScriptPointerList)
        {
            MapEntry const* mapEntry = script->GetEntry();
            if (!mapEntry)
            {
                continue;
            }
            if (mapEntry->MapID != map->GetId())
            {
                continue;
            }
            executeHook(script);
            return;
        }
    }
References Map::GetEntry(), Map::GetId(), and MapEntry::MapID.
ForeachMaps() [2/4]
template<> void anonymous_namespace{AllMapScript.cpp}::ForeachMaps (Map * map, std::function< void(InstanceMapScript *)> executeHook) inline
    {
        auto mapEntry = map->GetEntry();
        if (!mapEntry)
        {
            return;
        }
        if (!mapEntry->IsDungeon())
        {
            return;
        }
        if (ScriptRegistry<InstanceMapScript>::ScriptPointerList.empty())
        {
            return;
        }
        for (auto const& [scriptID, script] : ScriptRegistry<InstanceMapScript>::ScriptPointerList)
        {
            MapEntry const* mapEntry = script->GetEntry();
            if (!mapEntry)
            {
                continue;
            }
            if (mapEntry->MapID != map->GetId())
            {
                continue;
            }
            executeHook(script);
            return;
        }
    }
References Map::GetEntry(), Map::GetId(), and MapEntry::MapID.
ForeachMaps() [3/4]
template<class ScriptName > void anonymous_namespace{AllMapScript.cpp}::ForeachMaps (Map * map, std::function< void(ScriptName *)> executeHook) inline
    {
        static_assert(Acore::dependant_false_v<ScriptName>, "Unsupported type used for ForeachMaps");
    }
ForeachMaps() [4/4]
template<> void anonymous_namespace{AllMapScript.cpp}::ForeachMaps (Map * map, std::function< void(WorldMapScript *)> executeHook) inline
    {
        auto mapEntry = map->GetEntry();
        if (!mapEntry)
        {
            return;
        }
        if (!mapEntry->IsWorldMap())
        {
            return;
        }
        if (ScriptRegistry<WorldMapScript>::ScriptPointerList.empty())
        {
            return;
        }
        for (auto const& [scriptID, script] : ScriptRegistry<WorldMapScript>::ScriptPointerList)
        {
            MapEntry const* mapEntry = script->GetEntry();
            if (!mapEntry)
            {
                continue;
            }
            if (mapEntry->MapID != map->GetId())
            {
                continue;
            }
            executeHook(script);
            return;
        }
    }
References Map::GetEntry(), Map::GetId(), and MapEntry::MapID.