AzerothCore: go_palehoof_sphere Class Reference
go_palehoof_sphere Class Reference
Public Member Functions
go_palehoof_sphere ()
bool OnGossipHello (Player *, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, GameObject *)
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnModifyHealth (GameObject *, Unit *, int32 &, SpellInfo const *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
go_palehoof_sphere()
go_palehoof_sphere::go_palehoof_sphere () inline
: GameObjectScript("go_palehoof_sphere") { }
Member Function Documentation
OnGossipHello()
bool go_palehoof_sphere::OnGossipHello (Player * , GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
    {
        InstanceScript* pInstance = go->GetInstanceScript();
        Creature* pPalehoof = ObjectAccessor::GetCreature(*go, pInstance ? pInstance->GetGuidData(DATA_GORTOK_PALEHOOF) : ObjectGuid::Empty);
        if (pPalehoof && pPalehoof->IsAlive())
        {
            // maybe these are hacks :(
            go->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
            go->SetGoState(GO_STATE_ACTIVE);
            pPalehoof->AI()->DoAction(ACTION_START_EVENT);
        }
        return true;
    }
References ACTION_START_EVENT, Creature::AI(), DATA_GORTOK_PALEHOOF, UnitAI::DoAction(), ObjectGuid::Empty, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, Unit::IsAlive(), GameObject::SetGameObjectFlag(), and GameObject::SetGoState().