AzeorthCore: npc_muglash::npc_muglashAI Struct Reference
npc_muglash::npc_muglashAI Struct Reference
Public Member Functions
npc_muglashAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void JustSummoned (Creature *summoned) override
void sQuestAccept (Player *player, Quest const *quest) override
void WaypointReached (uint32 waypointId) override
void DoWaveSummon ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
bool _isBrazierExtinguished
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Private Attributes
uint32 eventTimer
uint8 waveId
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_muglashAI()
npc_muglash::npc_muglashAI::npc_muglashAI (Creature * creature) inline
: npc_escortAI(creature) { }
Member Function Documentation
DoWaveSummon()
void npc_muglash::npc_muglashAI::DoWaveSummon () inline
        {
            switch (waveId)
            {
                case 1:
                    me->SummonCreature(NPC_WRATH_RIDER,     FirstNagaCoord[0], TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);
                    me->SummonCreature(NPC_WRATH_SORCERESS, FirstNagaCoord[1], TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);
                    me->SummonCreature(NPC_WRATH_RAZORTAIL, FirstNagaCoord[2], TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);
                    break;
                case 2:
                    me->SummonCreature(NPC_WRATH_PRIESTESS, SecondNagaCoord[0], TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);
                    me->SummonCreature(NPC_WRATH_MYRMIDON,  SecondNagaCoord[1], TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);
                    me->SummonCreature(NPC_WRATH_SEAWITCH,  SecondNagaCoord[2], TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);
                    break;
                case 3:
                    me->SummonCreature(NPC_VORSHA, VorshaCoord, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);
                    break;
                case 4:
                    SetEscortPaused(false);
                    Talk(SAY_MUG_DONE);
                    break;
            }
        }
References FirstNagaCoord, ScriptedAI::me, NPC_VORSHA, NPC_WRATH_MYRMIDON, NPC_WRATH_PRIESTESS, NPC_WRATH_RAZORTAIL, NPC_WRATH_RIDER, NPC_WRATH_SEAWITCH, NPC_WRATH_SORCERESS, SAY_MUG_DONE, SecondNagaCoord, npc_escortAI::SetEscortPaused(), WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, VorshaCoord, and waveId.
Referenced by UpdateAI().
EnterCombat()
void npc_muglash::npc_muglashAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (Player* player = GetPlayerForEscort())
                if (HasEscortState(STATE_ESCORT_PAUSED))
                {
                    if (urand(0, 1))
                        Talk(SAY_MUG_ON_GUARD, player);
                    return;
                }
        }
References npc_escortAI::GetPlayerForEscort(), npc_escortAI::HasEscortState(), SAY_MUG_ON_GUARD, STATE_ESCORT_PAUSED, and urand().
JustDied()
void npc_muglash::npc_muglashAI::JustDied (Unit *) inline override virtual
Reimplemented from npc_escortAI.
        {
            if (HasEscortState(STATE_ESCORT_ESCORTING))
                if (Player* player = GetPlayerForEscort())
                    player->FailQuest(QUEST_VORSHA);
        }
References npc_escortAI::GetPlayerForEscort(), npc_escortAI::HasEscortState(), QUEST_VORSHA, and STATE_ESCORT_ESCORTING.
JustSummoned()
void npc_muglash::npc_muglashAI::JustSummoned (Creature * summoned) inline override virtual
Reimplemented from ScriptedAI.
        {
            summoned->AI()->AttackStart(me);
        }
References Creature::AI(), UnitAI::AttackStart(), and ScriptedAI::me.
Reset()
void npc_muglash::npc_muglashAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            eventTimer = 10000;
            waveId = 0;
            _isBrazierExtinguished = false;
        }
References _isBrazierExtinguished, eventTimer, and waveId.
sQuestAccept()
void npc_muglash::npc_muglashAI::sQuestAccept (Player * player, Quest const * quest) inline override virtual
Reimplemented from UnitAI.
        {
            if (quest->GetQuestId() == QUEST_VORSHA)
            {
                Talk(SAY_MUG_START1);
                me->SetFaction(FACTION_ESCORTEE_N_NEUTRAL_PASSIVE);
                npc_escortAI::Start(true, false, player->GetGUID());
            }
        }
References FACTION_ESCORTEE_N_NEUTRAL_PASSIVE, Object::GetGUID(), Quest::GetQuestId(), ScriptedAI::me, QUEST_VORSHA, SAY_MUG_START1, Unit::SetFaction(), and npc_escortAI::Start().
UpdateAI()
void npc_muglash::npc_muglashAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
        {
            npc_escortAI::UpdateAI(diff);
            if (!me->GetVictim())
            {
                if (HasEscortState(STATE_ESCORT_PAUSED) && _isBrazierExtinguished)
                {
                    if (eventTimer < diff)
                    {
                        ++waveId;
                        DoWaveSummon();
                        eventTimer = 10000;
                    }
                    else
                        eventTimer -= diff;
                }
                return;
            }
            DoMeleeAttackIfReady();
        }
References _isBrazierExtinguished, UnitAI::DoMeleeAttackIfReady(), DoWaveSummon(), eventTimer, Unit::GetVictim(), npc_escortAI::HasEscortState(), ScriptedAI::me, STATE_ESCORT_PAUSED, npc_escortAI::UpdateAI(), and waveId.
WaypointReached()
void npc_muglash::npc_muglashAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
        {
            if (Player* player = GetPlayerForEscort())
            {
                switch (waypointId)
                {
                    case 0:
                        Talk(SAY_MUG_START2, player);
                        break;
                    case 24:
                        Talk(SAY_MUG_BRAZIER, player);
                        if (GameObject* go = GetClosestGameObjectWithEntry(me, GO_NAGA_BRAZIER, INTERACTION_DISTANCE * 2))
{
                            go->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                            SetEscortPaused(true);
                        }
                        break;
                    case 25:
                        Talk(SAY_MUG_GRATITUDE);
                        player->GroupEventHappens(QUEST_VORSHA, me);
                        break;
                    case 26:
                        Talk(SAY_MUG_PATROL);
                        break;
                    case 27:
                        Talk(SAY_MUG_RETURN);
                        break;
                }
            }
        }
References GetClosestGameObjectWithEntry(), npc_escortAI::GetPlayerForEscort(), GO_FLAG_NOT_SELECTABLE, GO_NAGA_BRAZIER, INTERACTION_DISTANCE, ScriptedAI::me, QUEST_VORSHA, SAY_MUG_BRAZIER, SAY_MUG_GRATITUDE, SAY_MUG_PATROL, SAY_MUG_RETURN, SAY_MUG_START2, and npc_escortAI::SetEscortPaused().
Member Data Documentation
_isBrazierExtinguished
bool npc_muglash::npc_muglashAI::_isBrazierExtinguished
Referenced by Reset(), and UpdateAI().
eventTimer
uint32 npc_muglash::npc_muglashAI::eventTimer private
Referenced by Reset(), and UpdateAI().
waveId
uint8 npc_muglash::npc_muglashAI::waveId private
Referenced by DoWaveSummon(), Reset(), and UpdateAI().