AzerothCore: Acore::LocalizedPacketDo< Builder > Class Template Reference
Acore::LocalizedPacketDo< Builder > Class Template Reference
#include "GridNotifiers.h"
Public Member Functions
LocalizedPacketDo (Builder &builder)
~LocalizedPacketDo ()
void operator() (Player *p)
Private Attributes
Builder & i_builder
std::vector< WorldPacket * > i_data_cache
Detailed Description
template<class Builder>
class Acore::LocalizedPacketDo< Builder >
Constructor & Destructor Documentation
LocalizedPacketDo()
template<class Builder > Acore::LocalizedPacketDo< Builder >::LocalizedPacketDo (Builder & builder) inline explicit
: i_builder(builder) {}
~LocalizedPacketDo()
template<class Builder > Acore::LocalizedPacketDo< Builder >::~LocalizedPacketDo () inline
        {
            for (std::size_t i = 0; i < i_data_cache.size(); ++i)
                delete i_data_cache[i];
        }
References Acore::LocalizedPacketDo< Builder >::i_data_cache.
Member Function Documentation
operator()()
template<class Builder > void Acore::LocalizedPacketDo< Builder >::operator() (Player * p)
{
    LocaleConstant loc_idx = p->GetSession()->GetSessionDbLocaleIndex();
    uint32 cache_idx = loc_idx + 1;
    WorldPacket* data;
    // create if not cached yet
    if (i_data_cache.size() < cache_idx + 1 || !i_data_cache[cache_idx])
    {
        if (i_data_cache.size() < cache_idx + 1)
            i_data_cache.resize(cache_idx + 1);
        data = new WorldPacket();
        i_builder(*data, loc_idx);
        i_data_cache[cache_idx] = data;
    }
    else
        data = i_data_cache[cache_idx];
    p->SendDirectMessage(data);
}
References Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), ByteBuffer::resize(), and Player::SendDirectMessage().
Member Data Documentation
i_builder
template<class Builder > Builder& Acore::LocalizedPacketDo< Builder >::i_builder private
i_data_cache
template<class Builder > std::vector<WorldPacket*> Acore::LocalizedPacketDo< Builder >::i_data_cache private
Referenced by Acore::LocalizedPacketDo< Builder >::~LocalizedPacketDo().