AzerothCore: BattleExperienceEvent Class Reference
BattleExperienceEvent Class Reference
Public Member Functions
BattleExperienceEvent (Creature *creature)
bool Execute (uint64 timer, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Static Public Attributes
static uint32 const ExperiencedSpells [5] = { 0, SPELL_EXPERIENCED, SPELL_VETERAN, SPELL_ELITE, SPELL_ADDS_BERSERK }
static uint32 const ExperiencedTimes [5] = { 100000, 70000, 60000, 90000, 0 }
Private Attributes
Creature * _creature
int32 _level
Detailed Description
Constructor & Destructor Documentation
BattleExperienceEvent()
BattleExperienceEvent::BattleExperienceEvent (Creature * creature) inline
: _creature(creature), _level(0) { }
Member Function Documentation
Execute()
bool BattleExperienceEvent::Execute (uint64 timer, uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        if (!_creature->IsAlive())
            return true;
        _creature->RemoveAurasDueToSpell(ExperiencedSpells[_level]);
        ++_level;
        _creature->CastSpell(_creature, ExperiencedSpells[_level], true);
        if (_level < (_creature->GetMap()->IsHeroic() ? 4 : 3))
        {
            _creature->m_Events.AddEvent(this, timer + ExperiencedTimes[_level]);
            return false;
        }
        return true;
    }
References _creature, _level, EventProcessor::AddEvent(), Unit::CastSpell(), ExperiencedSpells, ExperiencedTimes, WorldObject::GetMap(), Unit::IsAlive(), Map::IsHeroic(), Unit::m_Events, and Unit::RemoveAurasDueToSpell().
Member Data Documentation
_creature
Creature* BattleExperienceEvent::_creature private
Referenced by Execute().
_level
int32 BattleExperienceEvent::_level private
Referenced by Execute().
ExperiencedSpells
uint32 const BattleExperienceEvent::ExperiencedSpells = { 0, SPELL_EXPERIENCED, SPELL_VETERAN, SPELL_ELITE, SPELL_ADDS_BERSERK } static
Referenced by Execute().
ExperiencedTimes
uint32 const BattleExperienceEvent::ExperiencedTimes = { 100000, 70000, 60000, 90000, 0 } static
Referenced by Execute(), gunship_npc_AI::MovementInform(), and npc_gunship_boarding_addAI::MovementInform().