AzerothCore: npc_xt002_boombot::npc_xt002_boombotAI Struct Reference
npc_xt002_boombot::npc_xt002_boombotAI Struct Reference
Public Member Functions
npc_xt002_boombotAI (Creature *pCreature)
void Reset () override
void Explode ()
void JustDied (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void MovementInform (uint32 type, uint32) override
void UpdateAI (uint32) override
Public Member Functions inherited from PassiveAI
PassiveAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
bool _locked
bool _boomed
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from PassiveAI
static int32 Permissible (Creature const *)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_xt002_boombotAI()
npc_xt002_boombot::npc_xt002_boombotAI::npc_xt002_boombotAI (Creature * pCreature) inline
: PassiveAI(pCreature) { }
Member Function Documentation
DamageTaken()
void npc_xt002_boombot::npc_xt002_boombotAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
        {
            if (_boomed)
                damage = 0;
            if (me->HealthBelowPctDamaged(50, damage) && !_boomed)
            {
                damage = 0;
                Explode();
            }
        }
References _boomed, Explode(), Unit::HealthBelowPctDamaged(), and CreatureAI::me.
Explode()
void npc_xt002_boombot::npc_xt002_boombotAI::Explode () inline
        {
            if (_boomed)
                return;
            _boomed = true; // Prevent recursive calls
            WorldPacket data(SMSG_SPELLINSTAKILLLOG, 8 + 8 + 4);
            data << me->GetGUID();
            data << me->GetGUID();
            data << uint32(SPELL_BOOM);
            me->SendMessageToSet(&data, false);
            me->KillSelf();
            // Visual only seems to work if the instant kill event is delayed or the spell itself is delayed
            // Casting done from player and caster source has the same targetinfo flags,
            // so that can't be the issue
            // See BoomEvent class
            // Schedule 1s delayed
            me->m_Events.AddEvent(new BoomEvent(me), me->m_Events.CalculateTime(1 * IN_MILLISECONDS));
        }
References _boomed, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Object::GetGUID(), IN_MILLISECONDS, Unit::KillSelf(), Unit::m_Events, CreatureAI::me, WorldObject::SendMessageToSet(), SMSG_SPELLINSTAKILLLOG, and SPELL_BOOM.
Referenced by DamageTaken().
JustDied()
void npc_xt002_boombot::npc_xt002_boombotAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            me->m_Events.AddEvent(new BoomEvent(me), me->m_Events.CalculateTime(1 * IN_MILLISECONDS));
        }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), IN_MILLISECONDS, Unit::m_Events, and CreatureAI::me.
MovementInform()
void npc_xt002_boombot::npc_xt002_boombotAI::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from CreatureAI.
        {
            if (type == POINT_MOTION_TYPE)
            {
                _locked = false;
                return;
            }
            // we reached the target :)
            //if (type == FOLLOW_MOTION_TYPE)
            //  _kill = true;
        }
References _locked, and POINT_MOTION_TYPE.
Reset()
void npc_xt002_boombot::npc_xt002_boombotAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            me->StopMoving();
            _locked = true;
            _boomed = false;
            me->SetUnitMovementFlags(MOVEMENTFLAG_WALKING);
            if (me->GetInstanceScript())
                if (Creature* pXT002 = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(TYPE_XT002)))
                {
                    if (pXT002->GetPositionZ() > 411.0f) // he is on stairs... idiot cryness protection
                        me->GetMotionMaster()->MovePoint(0, 884.028931f, -14.593809f, 409.786987f);
                    else
                        _locked = false;
                }
        }
References _boomed, _locked, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), Unit::GetMotionMaster(), CreatureAI::me, MOVEMENTFLAG_WALKING, MotionMaster::MovePoint(), Unit::SetUnitMovementFlags(), Unit::StopMoving(), and TYPE_XT002.
UpdateAI()
void npc_xt002_boombot::npc_xt002_boombotAI::UpdateAI (uint32) inline override virtual
Reimplemented from PassiveAI.
        {
            if (!_locked)
            {
                if (me->GetInstanceScript())
                    if (Creature* pXT002 = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(TYPE_XT002)))
                    {
                        me->GetMotionMaster()->MoveFollow(pXT002, 0.0f, 0.0f);
                        _locked = true;
                    }
            }
        }
References _locked, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), Unit::GetMotionMaster(), CreatureAI::me, MotionMaster::MoveFollow(), and TYPE_XT002.
Member Data Documentation
_boomed
bool npc_xt002_boombot::npc_xt002_boombotAI::_boomed
Referenced by DamageTaken(), Explode(), and Reset().
_locked
bool npc_xt002_boombot::npc_xt002_boombotAI::_locked
Referenced by MovementInform(), Reset(), and UpdateAI().