AzerothCore: BattlefieldMgr Class Reference
BattlefieldMgr Class Reference
#include "BattlefieldMgr.h"
Public Types
typedef std::vector< Battlefield * > BattlefieldSet
typedef std::map< uint32, Battlefield * > BattlefieldMap
Public Member Functions
BattlefieldMgr ()
~BattlefieldMgr ()
void InitBattlefield ()
void HandlePlayerEnterZone (Player *player, uint32 areaflag)
void HandlePlayerLeaveZone (Player *player, uint32 areaflag)
void HandlePlayerResurrects (Player *player, uint32 areaflag)
Battlefield * GetBattlefieldToZoneId (uint32 zoneid)
Battlefield * GetBattlefieldByBattleId (uint32 battleid)
ZoneScript * GetZoneScript (uint32 zoneId)
void AddZone (uint32 zoneid, Battlefield *handle)
void Update (uint32 diff)
void HandleGossipOption (Player *player, ObjectGuid guid, uint32 gossipid)
bool CanTalkTo (Player *player, Creature *creature, GossipMenuItems gso)
void HandleDropFlag (Player *player, uint32 spellId)
Static Public Member Functions
static BattlefieldMgr * instance ()
Private Attributes
BattlefieldSet m_BattlefieldSet
BattlefieldMap m_BattlefieldMap
uint32 m_UpdateTimer
Detailed Description
Member Typedef Documentation
BattlefieldMap
typedef std::map< uint32 , Battlefield* > BattlefieldMgr::BattlefieldMap
BattlefieldSet
typedef std::vector< Battlefield* > BattlefieldMgr::BattlefieldSet
Constructor & Destructor Documentation
BattlefieldMgr()
BattlefieldMgr::BattlefieldMgr ()
{
    m_UpdateTimer = 0;
    //LOG_DEBUG("bg.battlefield", "Instantiating BattlefieldMgr");
}
References m_UpdateTimer.
~BattlefieldMgr()
BattlefieldMgr::~BattlefieldMgr ()
{
    //LOG_DEBUG("bg.battlefield", "Deleting BattlefieldMgr");
    for (BattlefieldSet::iterator itr = m_BattlefieldSet.begin(); itr != m_BattlefieldSet.end(); ++itr)
        delete *itr;
}
References m_BattlefieldSet.
Member Function Documentation
AddZone()
void BattlefieldMgr::AddZone (uint32 zoneid, Battlefield * handle)
{
    m_BattlefieldMap[zoneid] = handle;
}
References m_BattlefieldMap.
CanTalkTo()
bool BattlefieldMgr::CanTalkTo (Player * player, Creature * creature, GossipMenuItems gso)
GetBattlefieldByBattleId()
Battlefield * BattlefieldMgr::GetBattlefieldByBattleId (uint32 battleid)
{
    for (BattlefieldSet::iterator itr = m_BattlefieldSet.begin(); itr != m_BattlefieldSet.end(); ++itr)
    {
        if ((*itr)->GetBattleId() == battleid)
            return (*itr);
    }
    return nullptr;
}
References m_BattlefieldSet.
GetBattlefieldToZoneId()
Battlefield * BattlefieldMgr::GetBattlefieldToZoneId (uint32 zoneid)
{
    BattlefieldMap::iterator itr = m_BattlefieldMap.find(zoneid);
    if (itr == m_BattlefieldMap.end())
    {
        // no handle for this zone, return
        return nullptr;
    }
    if (!itr->second->IsEnabled())
        return nullptr;
    return itr->second;
}
References m_BattlefieldMap.
GetZoneScript()
ZoneScript * BattlefieldMgr::GetZoneScript (uint32 zoneId)
{
    BattlefieldMap::iterator itr = m_BattlefieldMap.find(zoneId);
    if (itr != m_BattlefieldMap.end())
        return itr->second;
    else
        return nullptr;
}
References m_BattlefieldMap.
HandleDropFlag()
void BattlefieldMgr::HandleDropFlag (Player * player, uint32 spellId)
HandleGossipOption()
void BattlefieldMgr::HandleGossipOption (Player * player, ObjectGuid guid, uint32 gossipid)
HandlePlayerEnterZone()
void BattlefieldMgr::HandlePlayerEnterZone (Player * player, uint32 areaflag)
{
    BattlefieldMap::iterator itr = m_BattlefieldMap.find(zoneid);
    if (itr == m_BattlefieldMap.end())
        return;
    if (itr->second->HasPlayer(player) || !itr->second->IsEnabled())
        return;
    itr->second->HandlePlayerEnterZone(player, zoneid);
    LOG_DEBUG("bg.battlefield", "Player {} entered outdoorpvp id {}", player->GetGUID().ToString(), itr->second->GetTypeId());
}
References Object::GetGUID(), LOG_DEBUG, m_BattlefieldMap, and ObjectGuid::ToString().
HandlePlayerLeaveZone()
void BattlefieldMgr::HandlePlayerLeaveZone (Player * player, uint32 areaflag)
{
    BattlefieldMap::iterator itr = m_BattlefieldMap.find(zoneid);
    if (itr == m_BattlefieldMap.end())
        return;
    // teleport: remove once in removefromworld, once in updatezone
    if (!itr->second->HasPlayer(player))
        return;
    itr->second->HandlePlayerLeaveZone(player, zoneid);
    LOG_DEBUG("bg.battlefield", "Player {} left outdoorpvp id {}", player->GetGUID().ToString(), itr->second->GetTypeId());
}
References Object::GetGUID(), LOG_DEBUG, m_BattlefieldMap, and ObjectGuid::ToString().
HandlePlayerResurrects()
void BattlefieldMgr::HandlePlayerResurrects (Player * player, uint32 areaflag)
InitBattlefield()
void BattlefieldMgr::InitBattlefield ()
{
    if (sWorld->getIntConfig(CONFIG_WINTERGRASP_ENABLE) == 2)
    {
        LOG_INFO("server.loading", "Battlefield: Wintergrasp is disabled.");
        LOG_INFO("server.loading", " ");
        return;
    }
    Battlefield* pBf = new BattlefieldWG;
    // respawn, init variables
    if (!pBf->SetupBattlefield())
    {
        LOG_ERROR("server.loading", "Battlefield: Wintergrasp init failed.");
        LOG_INFO("server.loading", " ");
        delete pBf;
    }
    else
    {
        m_BattlefieldSet.push_back(pBf);
        LOG_INFO("server.loading", "Battlefield: Wintergrasp successfully initiated.");
        LOG_INFO("server.loading", " ");
    }
    /* For Cataclysm: Tol Barad
       pBf = new BattlefieldTB;
       // respawn, init variables
       if (!pBf->SetupBattlefield())
       {
       LOG_DEBUG("bg.battlefield", "Battlefield : Tol Barad init failed.");
       delete pBf;
       }
       else
       {
       m_BattlefieldSet.push_back(pBf);
       LOG_DEBUG("bg.battlefield", "Battlefield : Tol Barad successfully initiated.");
       } */
}
References CONFIG_WINTERGRASP_ENABLE, LOG_ERROR, LOG_INFO, m_BattlefieldSet, Battlefield::SetupBattlefield(), and sWorld.
instance()
BattlefieldMgr * BattlefieldMgr::instance () static
{
    static BattlefieldMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
Update()
void BattlefieldMgr::Update (uint32 diff)
{
    m_UpdateTimer += diff;
    if (m_UpdateTimer > BATTLEFIELD_OBJECTIVE_UPDATE_INTERVAL)
    {
        for (BattlefieldSet::iterator itr = m_BattlefieldSet.begin(); itr != m_BattlefieldSet.end(); ++itr)
            //if ((*itr)->IsEnabled())
            (*itr)->Update(m_UpdateTimer);
        m_UpdateTimer = 0;
    }
}
References BATTLEFIELD_OBJECTIVE_UPDATE_INTERVAL, m_BattlefieldSet, and m_UpdateTimer.
Member Data Documentation
m_BattlefieldMap
BattlefieldMap BattlefieldMgr::m_BattlefieldMap private
Referenced by AddZone(), GetBattlefieldToZoneId(), GetZoneScript(), HandlePlayerEnterZone(), and HandlePlayerLeaveZone().
m_BattlefieldSet
BattlefieldSet BattlefieldMgr::m_BattlefieldSet private
Referenced by GetBattlefieldByBattleId(), InitBattlefield(), Update(), and ~BattlefieldMgr().
m_UpdateTimer
uint32 BattlefieldMgr::m_UpdateTimer private
Referenced by BattlefieldMgr(), and Update().