AzerothCore: FollowerReference Class Reference
FollowerReference Class Reference
#include "FollowerReference.h"
Protected Member Functions
void targetObjectBuildLink () override
void targetObjectDestroyLink () override
void sourceObjectDestroyLink () override
virtual void targetObjectBuildLink ()=0
virtual void targetObjectDestroyLink ()=0
virtual void sourceObjectDestroyLink ()=0
Additional Inherited Members
Public Member Functions inherited from Reference< Unit, TargetedMovementGeneratorBase >
Reference ()
virtual ~Reference ()=default
void link (Unit *toObj, TargetedMovementGeneratorBase *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< Unit, TargetedMovementGeneratorBase > * next ()
Reference< Unit, TargetedMovementGeneratorBase > const * next () const
Reference< Unit, TargetedMovementGeneratorBase > * prev ()
Reference< Unit, TargetedMovementGeneratorBase > const * prev () const
Reference< Unit, TargetedMovementGeneratorBase > * nocheck_next ()
Reference< Unit, TargetedMovementGeneratorBase > const * nocheck_next () const
Reference< Unit, TargetedMovementGeneratorBase > * nocheck_prev ()
Reference< Unit, TargetedMovementGeneratorBase > const * nocheck_prev () const
Unit * operator-> () const
Unit * getTarget () const
TargetedMovementGeneratorBase * GetSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()=default
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Detailed Description
Member Function Documentation
sourceObjectDestroyLink()
void FollowerReference::sourceObjectDestroyLink () override protected virtual
Implements Reference< Unit, TargetedMovementGeneratorBase >.
{
    GetSource()->stopFollowing();
}
References Reference< Unit, TargetedMovementGeneratorBase >::GetSource(), and TargetedMovementGeneratorBase::stopFollowing().
targetObjectBuildLink()
void FollowerReference::targetObjectBuildLink () override protected virtual
Implements Reference< Unit, TargetedMovementGeneratorBase >.
{
    getTarget()->addFollower(this);
}
References Unit::addFollower(), and Reference< Unit, TargetedMovementGeneratorBase >::getTarget().
targetObjectDestroyLink()
void FollowerReference::targetObjectDestroyLink () override protected virtual
Implements Reference< Unit, TargetedMovementGeneratorBase >.
{
    getTarget()->removeFollower(this);
}
References Reference< Unit, TargetedMovementGeneratorBase >::getTarget(), and Unit::removeFollower().