AzerothCore: OPvPCapturePointTF Class Reference
OPvPCapturePointTF Class Reference
#include "OutdoorPvPTF.h"
Public Member Functions
OPvPCapturePointTF (OutdoorPvP *pvp, OutdoorPvPTF_TowerType type)
bool Update (uint32 diff) override
void ChangeState () override
void SendChangePhase () override
void FillInitialWorldStates (WorldPacket &data) override
bool HandlePlayerEnter (Player *player) override
void HandlePlayerLeave (Player *player) override
void ResetToTeamControlled (TeamId team)
void UpdateTowerState ()
Public Member Functions inherited from OPvPCapturePoint
OPvPCapturePoint (OutdoorPvP *pvp)
virtual ~OPvPCapturePoint ()=default
virtual void FillInitialWorldStates (WorldPacket &)
void SendUpdateWorldState (uint32 field, uint32 value)
void SendObjectiveComplete (uint32 id, ObjectGuid guid=ObjectGuid::Empty)
virtual bool HandlePlayerEnter (Player *player)
virtual void HandlePlayerLeave (Player *player)
bool IsInsideObjective (Player *player) const
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual int32 HandleOpenGo (Player *player, GameObject *go)
virtual bool Update (uint32 diff)
virtual void ChangeState ()=0
virtual void ChangeTeam (TeamId)
virtual void SendChangePhase ()
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipId)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual void DeleteSpawns ()
void AddGO (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
void AddCre (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
bool SetCapturePointData (uint32 entry, uint32 map, float x, float y, float z, float o=0, float rotation0=0, float rotation1=0, float rotation2=0, float rotation3=0)
void SetSlider (float slider)
float GetSlider () const
Protected Attributes
OutdoorPvPTF_TowerType m_TowerType
uint32 m_TowerState
Protected Attributes inherited from OPvPCapturePoint
std::array< PlayerSet, 2 > _activePlayers
float _maxValue {}
float _minValue {}
float _maxSpeed {}
float _value {}
TeamId _team { TEAM_NEUTRAL }
ObjectiveStates _oldState { OBJECTIVESTATE_NEUTRAL }
ObjectiveStates _state { OBJECTIVESTATE_NEUTRAL }
uint32 _neutralValuePct {}
OutdoorPvP * _pvp {}
std::unordered_map< uint32, ObjectGuid::LowType > _objects
std::unordered_map< uint32, ObjectGuid::LowType > _creatures
std::unordered_map< ObjectGuid::LowType, uint32 > _objectTypes
std::unordered_map< ObjectGuid::LowType, uint32 > _creatureTypes
Additional Inherited Members
Public Attributes inherited from OPvPCapturePoint
ObjectGuid::LowType m_capturePointSpawnId {}
GameObject * _capturePoint {}
Protected Member Functions inherited from OPvPCapturePoint
bool AddObject (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3)
bool AddCreature (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, uint32 spawntimeDelay=0)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool DelCapturePoint ()
Detailed Description
Constructor & Destructor Documentation
OPvPCapturePointTF()
OPvPCapturePointTF::OPvPCapturePointTF (OutdoorPvP * pvp, OutdoorPvPTF_TowerType type)
    : OPvPCapturePoint(pvp), m_TowerType(type), m_TowerState(TF_TOWERSTATE_N)
{
    SetCapturePointData(TFCapturePoints[type].entry, TFCapturePoints[type].map, TFCapturePoints[type].x, TFCapturePoints[type].y, TFCapturePoints[type].z, TFCapturePoints[type].o, TFCapturePoints[type].rot0, TFCapturePoints[type].rot1, TFCapturePoints[type].rot2, TFCapturePoints[type].rot3);
}
References OPvPCapturePoint::SetCapturePointData(), and TFCapturePoints.
Member Function Documentation
ChangeState()
void OPvPCapturePointTF::ChangeState () override virtual
Implements OPvPCapturePoint.
{
    // if changing from controlling alliance to horde
    if (_oldState == OBJECTIVESTATE_ALLIANCE)
    {
        if (uint32 alliance_towers = ((OutdoorPvPTF*)_pvp)->GetAllianceTowersControlled())
            ((OutdoorPvPTF*)_pvp)->SetAllianceTowersControlled(--alliance_towers);
        sWorld->SendZoneText(OutdoorPvPTFBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_TF_LOSE_A));
    }
    // if changing from controlling horde to alliance
    else if (_oldState == OBJECTIVESTATE_HORDE)
    {
        if (uint32 horde_towers = ((OutdoorPvPTF*)_pvp)->GetHordeTowersControlled())
            ((OutdoorPvPTF*)_pvp)->SetHordeTowersControlled(--horde_towers);
        sWorld->SendZoneText(OutdoorPvPTFBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_TF_LOSE_H));
    }
    uint32 artkit = 21;
    switch (_state)
    {
        case OBJECTIVESTATE_ALLIANCE:
            {
                m_TowerState = TF_TOWERSTATE_A;
                artkit = 2;
                uint32 alliance_towers = ((OutdoorPvPTF*)_pvp)->GetAllianceTowersControlled();
                if (alliance_towers < TF_TOWER_NUM)
                    ((OutdoorPvPTF*)_pvp)->SetAllianceTowersControlled(++alliance_towers);
                sWorld->SendZoneText(OutdoorPvPTFBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_TF_CAPTURE_A));
                for (PlayerSet::iterator itr = _activePlayers[0].begin(); itr != _activePlayers[0].end(); ++itr)
                    if (Player* player = ObjectAccessor::FindPlayer(*itr))
                        player->AreaExploredOrEventHappens(TF_ALLY_QUEST);
                break;
            }
        case OBJECTIVESTATE_HORDE:
            {
                m_TowerState = TF_TOWERSTATE_H;
                artkit = 1;
                uint32 horde_towers = ((OutdoorPvPTF*)_pvp)->GetHordeTowersControlled();
                if (horde_towers < TF_TOWER_NUM)
                    ((OutdoorPvPTF*)_pvp)->SetHordeTowersControlled(++horde_towers);
                sWorld->SendZoneText(OutdoorPvPTFBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_TF_CAPTURE_H));
                for (PlayerSet::iterator itr = _activePlayers[1].begin(); itr != _activePlayers[1].end(); ++itr)
                    if (Player* player = ObjectAccessor::FindPlayer(*itr))
                        player->AreaExploredOrEventHappens(TF_HORDE_QUEST);
                break;
            }
        case OBJECTIVESTATE_NEUTRAL:
        case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
        case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
        case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
        case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
            m_TowerState = TF_TOWERSTATE_N;
            break;
    }
    auto bounds = sMapMgr->FindMap(530, 0)->GetGameObjectBySpawnIdStore().equal_range(m_capturePointSpawnId);
    for (auto itr = bounds.first; itr != bounds.second; ++itr)
        itr->second->SetGoArtKit(artkit);
    UpdateTowerState();
}
References OPvPCapturePoint::_activePlayers, OPvPCapturePoint::_oldState, OPvPCapturePoint::_pvp, OPvPCapturePoint::_state, ObjectAccessor::FindPlayer(), LANG_OPVP_TF_CAPTURE_A, LANG_OPVP_TF_CAPTURE_H, LANG_OPVP_TF_LOSE_A, LANG_OPVP_TF_LOSE_H, OPvPCapturePoint::m_capturePointSpawnId, m_TowerState, OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL, OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE, OutdoorPvPTFBuffZones, sMapMgr, sObjectMgr, sWorld, TF_ALLY_QUEST, TF_HORDE_QUEST, TF_TOWER_NUM, TF_TOWERSTATE_A, TF_TOWERSTATE_H, TF_TOWERSTATE_N, and UpdateTowerState().
Referenced by ResetToTeamControlled().
FillInitialWorldStates()
void OPvPCapturePointTF::FillInitialWorldStates (WorldPacket & data) override virtual
Reimplemented from OPvPCapturePoint.
{
    data << uint32(TFTowerWorldStates[m_TowerType].n) << uint32(bool(m_TowerState & TF_TOWERSTATE_N));
    data << uint32(TFTowerWorldStates[m_TowerType].h) << uint32(bool(m_TowerState & TF_TOWERSTATE_H));
    data << uint32(TFTowerWorldStates[m_TowerType].a) << uint32(bool(m_TowerState & TF_TOWERSTATE_A));
}
References m_TowerState, m_TowerType, TF_TOWERSTATE_A, TF_TOWERSTATE_H, TF_TOWERSTATE_N, and TFTowerWorldStates.
HandlePlayerEnter()
bool OPvPCapturePointTF::HandlePlayerEnter (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
{
    if (OPvPCapturePoint::HandlePlayerEnter(player))
    {
        player->SendUpdateWorldState(TF_UI_TOWER_SLIDER_DISPLAY, 1);
        uint32 phase = (uint32)ceil((_value + _maxValue) / (2 * _maxValue) * 100.0f);
        player->SendUpdateWorldState(TF_UI_TOWER_SLIDER_POS, phase);
        player->SendUpdateWorldState(TF_UI_TOWER_SLIDER_N, _neutralValuePct);
        return true;
    }
    return false;
}
References OPvPCapturePoint::_maxValue, OPvPCapturePoint::_neutralValuePct, OPvPCapturePoint::_value, OPvPCapturePoint::HandlePlayerEnter(), Player::SendUpdateWorldState(), TF_UI_TOWER_SLIDER_DISPLAY, TF_UI_TOWER_SLIDER_N, and TF_UI_TOWER_SLIDER_POS.
HandlePlayerLeave()
void OPvPCapturePointTF::HandlePlayerLeave (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
{
    player->SendUpdateWorldState(TF_UI_TOWER_SLIDER_DISPLAY, 0);
    OPvPCapturePoint::HandlePlayerLeave(player);
}
References OPvPCapturePoint::HandlePlayerLeave(), Player::SendUpdateWorldState(), and TF_UI_TOWER_SLIDER_DISPLAY.
ResetToTeamControlled()
void OPvPCapturePointTF::ResetToTeamControlled (TeamId team)
{
    switch (team)
    {
    case TEAM_HORDE:
        _state = OBJECTIVESTATE_HORDE;
        _oldState = OBJECTIVESTATE_HORDE;
        _team = TEAM_HORDE;
        break;
    case TEAM_ALLIANCE:
        _state = OBJECTIVESTATE_ALLIANCE;
        _oldState = OBJECTIVESTATE_ALLIANCE;
        _team = TEAM_ALLIANCE;
        break;
    case TEAM_NEUTRAL:
        _state = OBJECTIVESTATE_NEUTRAL;
        _oldState = OBJECTIVESTATE_NEUTRAL;
        _team = TEAM_NEUTRAL;
        break;
    }
    _value = 0.0f;
    ChangeState();
    SendChangePhase();
}
References OPvPCapturePoint::_oldState, OPvPCapturePoint::_state, OPvPCapturePoint::_team, OPvPCapturePoint::_value, ChangeState(), OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_NEUTRAL, SendChangePhase(), TEAM_ALLIANCE, TEAM_HORDE, and TEAM_NEUTRAL.
SendChangePhase()
void OPvPCapturePointTF::SendChangePhase () override virtual
Reimplemented from OPvPCapturePoint.
{
    // send this too, sometimes the slider disappears, dunno why :(
    SendUpdateWorldState(TF_UI_TOWER_SLIDER_DISPLAY, 1);
    // send these updates to only the ones in this objective
    uint32 phase = (uint32)ceil((_value + _maxValue) / (2 * _maxValue) * 100.0f);
    SendUpdateWorldState(TF_UI_TOWER_SLIDER_POS, phase);
    // send this too, sometimes it resets :S
    SendUpdateWorldState(TF_UI_TOWER_SLIDER_N, _neutralValuePct);
}
References OPvPCapturePoint::_maxValue, OPvPCapturePoint::_neutralValuePct, OPvPCapturePoint::_value, OPvPCapturePoint::SendUpdateWorldState(), TF_UI_TOWER_SLIDER_DISPLAY, TF_UI_TOWER_SLIDER_N, and TF_UI_TOWER_SLIDER_POS.
Referenced by ResetToTeamControlled().
Update()
bool OPvPCapturePointTF::Update (uint32 diff) override virtual
Reimplemented from OPvPCapturePoint.
{
    // can update even in locked state if gathers the controlling faction
    bool canupdate = ((((OutdoorPvPTF*)_pvp)->GetAllianceTowersControlled() > 0) && _activePlayers[0].size() > _activePlayers[1].size()) ||
                     ((((OutdoorPvPTF*)_pvp)->GetHordeTowersControlled() > 0) && _activePlayers[0].size() < _activePlayers[1].size());
    // if gathers the other faction, then only update if the pvp is unlocked
    canupdate = canupdate || !((OutdoorPvPTF*)_pvp)->IsLocked();
    return canupdate && OPvPCapturePoint::Update(diff);
}
References OPvPCapturePoint::_activePlayers, OPvPCapturePoint::_pvp, and OPvPCapturePoint::Update().
UpdateTowerState()
void OPvPCapturePointTF::UpdateTowerState ()
{
    _pvp->SendUpdateWorldState(uint32(TFTowerWorldStates[m_TowerType].n), uint32(bool(m_TowerState & TF_TOWERSTATE_N)));
    _pvp->SendUpdateWorldState(uint32(TFTowerWorldStates[m_TowerType].h), uint32(bool(m_TowerState & TF_TOWERSTATE_H)));
    _pvp->SendUpdateWorldState(uint32(TFTowerWorldStates[m_TowerType].a), uint32(bool(m_TowerState & TF_TOWERSTATE_A)));
}
References OPvPCapturePoint::_pvp, m_TowerState, m_TowerType, OutdoorPvP::SendUpdateWorldState(), TF_TOWERSTATE_A, TF_TOWERSTATE_H, TF_TOWERSTATE_N, and TFTowerWorldStates.
Referenced by ChangeState().
Member Data Documentation
m_TowerState
uint32 OPvPCapturePointTF::m_TowerState protected
Referenced by ChangeState(), FillInitialWorldStates(), and UpdateTowerState().
m_TowerType
OutdoorPvPTF_TowerType OPvPCapturePointTF::m_TowerType protected
Referenced by FillInitialWorldStates(), and UpdateTowerState().