AzeorthCore: spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript Class Reference
spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_sartharion_lava_strike_SpellScript)
bool Load () override
void HandleDummy (SpellEffIndex)
void HandleSchoolDamage (SpellEffIndex)
void Register () override
Private Attributes
bool spawned
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleDummy()
void spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::HandleDummy (SpellEffIndex) inline private
        {
            if (!GetCaster() || !GetHitUnit())
                return;
            GetCaster()->CastSpell(GetHitUnit()->GetPositionX(), GetHitUnit()->GetPositionY(), GetHitUnit()->GetPositionZ(), SPELL_LAVA_STRIKE_DUMMY_TRIGGER, true);
        }
References Unit::CastSpell(), SpellScript::GetCaster(), SpellScript::GetHitUnit(), and SPELL_LAVA_STRIKE_DUMMY_TRIGGER.
Referenced by Register().
HandleSchoolDamage()
void spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::HandleSchoolDamage (SpellEffIndex) inline private
        {
            if (!GetCaster() || !GetHitUnit() || spawned)
            {
                return;
            }
            if (InstanceScript* pInstance = GetCaster()->GetInstanceScript())
            {
                if (Creature* sarth = ObjectAccessor::GetCreature(*GetHitUnit(), pInstance->GetGuidData(DATA_SARTHARION)))
                {
                    sarth->AI()->SetData(DATA_VOLCANO_BLOWS, GetHitUnit()->GetGUID().GetCounter());
                    sarth->CastSpell(GetHitUnit(), SPELL_LAVA_STRIKE_SUMMON, true);
                    spawned = true;
                }
            }
        }
References DATA_SARTHARION, DATA_VOLCANO_BLOWS, SpellScript::GetCaster(), ObjectAccessor::GetCreature(), SpellScript::GetHitUnit(), spawned, and SPELL_LAVA_STRIKE_SUMMON.
Referenced by Register().
Load()
bool spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::Load () inline override private virtual
Reimplemented from _SpellScript.
        {
            spawned = false;
            return true;
        }
References spawned.
PrepareSpellScript()
spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::PrepareSpellScript (spell_sartharion_lava_strike_SpellScript) private
Register()
void spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::Register () inline override private virtual
Implements _SpellScript.
        {
            if (m_scriptSpellId == 57578) // Dummy lava strike
            {
                OnEffectHitTarget += SpellEffectFn(spell_sartharion_lava_strike_SpellScript::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
            }
            else
            {
                OnEffectHitTarget += SpellEffectFn(spell_sartharion_lava_strike_SpellScript::HandleSchoolDamage, EFFECT_0, SPELL_EFFECT_SCHOOL_DAMAGE);
            }
        }
References EFFECT_0, HandleDummy(), HandleSchoolDamage(), _SpellScript::m_scriptSpellId, SpellScript::OnEffectHitTarget, SPELL_EFFECT_DUMMY, SPELL_EFFECT_SCHOOL_DAMAGE, and SpellEffectFn.
Member Data Documentation
spawned
bool spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::spawned private
Referenced by HandleSchoolDamage(), and Load().