AzeorthCore: WorldObject Class Reference
WorldObject Class Reference
#include "Object.h"
Public Member Functions
~WorldObject () override
virtual void Update (uint32)
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void AddToWorld () override
void RemoveFromWorld () override
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, WorldObject const *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle)
Position GetNearPosition (float dist, float angle)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius)
void GetContactPoint (WorldObject const *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (WorldObject const *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
virtual float GetCombatReach () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
virtual void SetPhaseMask (uint32 newPhaseMask, bool update)
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
virtual std::string const & GetNameForLocaleIdx (LocaleConstant) const
float GetDistance (WorldObject const *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (WorldObject const *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (WorldObject const *obj) const
bool IsSelfOrInSameMap (WorldObject const *obj) const
bool IsInMap (WorldObject const *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinLOS (float x, float y, float z, VMAP::ModelIgnoreFlags ignoreFlags=VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, VMAP::ModelIgnoreFlags ignoreFlags=VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS, Optional< float > collisionHeight={ }) const
Position GetHitSpherePointFor (Position const &dest, Optional< float > collisionHeight={ }) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z, Optional< float > collisionHeight={ }) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (WorldObject const *obj1, WorldObject const *obj2, float size=0) const
virtual void CleanupsBeforeDelete (bool finalCleanup=true)
virtual void SendMessageToSet (WorldPacket const *data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const *data, float dist, bool, bool includeMargin=false, Player const *skipped_rcvr=nullptr) const
virtual void SendMessageToSet (WorldPacket const *data, Player const *skipped_rcvr) const
virtual uint8 getLevelForTarget (WorldObject const *) const
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void SendObjectDeSpawnAnim (ObjectGuid guid)
virtual void SaveRespawnTime ()
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (WorldObject const *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true, GOSummonType summonType=GO_SUMMON_TIMED_OR_CORPSE_DESPAWN)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
void DestroyForNearbyPlayers ()
virtual void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false)
void BuildUpdate (UpdateDataMapType &data_map, UpdatePlayerSet &player_set) override
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
bool IsFarVisible () const
bool IsVisibilityOverridden () const
void SetVisibilityDistanceOverride (VisibilityDistanceType type)
void SetWorldObject (bool apply)
bool IsPermanentWorldObject () const
bool IsWorldObject () const
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
virtual ObjectGuid GetTransGUID () const
void SetTransport (Transport *t)
virtual float GetStationaryX () const
virtual float GetStationaryY () const
virtual float GetStationaryZ () const
virtual float GetStationaryO () const
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
virtual float GetCollisionHeight () const
virtual float GetCollisionWidth () const
virtual float GetCollisionRadius () const
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
std::string GetDebugInfo () const override
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
virtual void AddToWorld ()
virtual void RemoveFromWorld ()
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
virtual void SetObjectScale (float scale)
virtual uint32 GetDynamicFlags () const
bool HasDynamicFlag (uint32 flag) const
virtual void SetDynamicFlag (uint32 flag)
virtual void RemoveDynamicFlag (uint32 flag)
virtual void ReplaceAllDynamicFlags (uint32 flag)
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
virtual bool hasQuest (uint32) const
virtual bool hasInvolvedQuest (uint32) const
virtual void BuildUpdate (UpdateDataMapType &, UpdatePlayerSet &)
void BuildFieldsUpdate (Player *, UpdateDataMapType &) const
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
Creature * ToCreature ()
Creature const * ToCreature () const
Unit * ToUnit ()
Unit const * ToUnit () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
virtual std::string GetDebugInfo () const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
std::string GetDebugInfo () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
Position (Position &&)=default
Position & operator= (const Position &)=default
Position & operator= (Position &&)=default
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (Position const *pos, float width) const
std::string ToString () const
Public Attributes
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
ElunaEventProcessor * elunaEvents
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Protected Member Functions
WorldObject (bool isWorldObject)
virtual void ProcessPositionDataChanged (PositionFullTerrainStatus const &data)
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsNeverVisible () const
virtual bool IsAlwaysVisibleFor (WorldObject const *) const
virtual bool IsInvisibleDueToDespawn () const
virtual bool IsAlwaysDetectableFor (WorldObject const *) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
bool _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
virtual void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, Player *target) const
virtual void AddToObjectUpdate ()=0
virtual void RemoveFromObjectUpdate ()=0
void AddToObjectUpdateIfNeeded ()
Protected Attributes
std::string m_name
bool m_isActive
bool m_isFarVisible
Optional< float > m_visibilityDistanceOverride
const bool m_isWorldObject
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Private Member Functions
virtual bool _IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D, bool useBoundingRadius=true) const
bool CanNeverSee (WorldObject const *obj) const
virtual bool CanAlwaysSee (WorldObject const *) const
bool CanDetect (WorldObject const *obj, bool ignoreStealth, bool checkClient, bool checkAlert=false) const
bool CanDetectInvisibilityOf (WorldObject const *obj) const
bool CanDetectStealthOf (WorldObject const *obj, bool checkAlert=false) const
Private Attributes
Map * m_currMap
uint32 m_InstanceId
uint32 m_phaseMask
bool m_useCombinedPhases
uint16 m_notifyflags
uint16 m_executed_notifies
GuidUnorderedSet _allowedLooters
Additional Inherited Members
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Detailed Description
Constructor & Destructor Documentation
WorldObject()
WorldObject::WorldObject (bool isWorldObject) explicit protected
                                           : WorldLocation(),
    LastUsedScriptID(0), m_name(""), m_isActive(false), m_visibilityDistanceOverride(), m_isWorldObject(isWorldObject), m_zoneScript(nullptr),
    _zoneId(0), _areaId(0), _floorZ(INVALID_HEIGHT), _outdoors(false), _liquidData(), _updatePositionData(false), m_transport(nullptr),
    m_currMap(nullptr), m_InstanceId(0), m_phaseMask(PHASEMASK_NORMAL), m_useCombinedPhases(true), m_notifyflags(0), m_executed_notifies(0)
{
    m_serverSideVisibility.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_ALIVE | GHOST_VISIBILITY_GHOST);
    m_serverSideVisibilityDetect.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_ALIVE);
    sScriptMgr->OnWorldObjectCreate(this);
}
References GHOST_VISIBILITY_ALIVE, GHOST_VISIBILITY_GHOST, m_serverSideVisibility, m_serverSideVisibilityDetect, SERVERSIDE_VISIBILITY_GHOST, FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::SetValue(), and sScriptMgr.
~WorldObject()
WorldObject::~WorldObject () override
{
    sScriptMgr->OnWorldObjectDestroy(this);
    // this may happen because there are many !create/delete
    if (IsWorldObject() && m_currMap)
    {
        if (GetTypeId() == TYPEID_CORPSE)
        {
            LOG_FATAL("entities.object", "Object::~Object Corpse {}, type={} deleted but still in map!!", GetGUID().ToString(), ((Corpse*)this)->GetType());
            ABORT();
        }
        ResetMap();
    }
}
References ABORT, Object::GetGUID(), Object::GetTypeId(), IsWorldObject(), LOG_FATAL, m_currMap, ResetMap(), sScriptMgr, Position::ToString(), and TYPEID_CORPSE.
Member Function Documentation
_Create()
void WorldObject::_Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
{
    Object::_Create(guidlow, 0, guidhigh);
    SetPhaseMask(phaseMask, false);
}
References Object::_Create(), and SetPhaseMask().
Referenced by Corpse::Create(), and DynamicObject::CreateDynamicObject().
_IsWithinDist()
bool WorldObject::_IsWithinDist (WorldObject const * obj, float dist2compare, bool is3D, bool useBoundingRadius = true) const private virtual
Reimplemented in GameObject.
{
    float sizefactor = useBoundingRadius ? GetObjectSize() + obj->GetObjectSize() : 0.0f;
    float maxdist = dist2compare + sizefactor;
    if (m_transport && obj->GetTransport() &&  obj->GetTransport()->GetGUID() == m_transport->GetGUID())
    {
        float dtx = m_movementInfo.transport.pos.m_positionX - obj->m_movementInfo.transport.pos.m_positionX;
        float dty = m_movementInfo.transport.pos.m_positionY - obj->m_movementInfo.transport.pos.m_positionY;
        float disttsq = dtx * dtx + dty * dty;
        if (is3D)
        {
            float dtz = m_movementInfo.transport.pos.m_positionZ - obj->m_movementInfo.transport.pos.m_positionZ;
            disttsq += dtz * dtz;
        }
        return disttsq < (maxdist * maxdist);
    }
    float dx = GetPositionX() - obj->GetPositionX();
    float dy = GetPositionY() - obj->GetPositionY();
    float distsq = dx * dx + dy * dy;
    if (is3D)
    {
        float dz = GetPositionZ() - obj->GetPositionZ();
        distsq += dz * dz;
    }
    return distsq < maxdist * maxdist;
}
References Object::GetGUID(), GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetTransport(), m_movementInfo, Position::m_positionX, Position::m_positionY, Position::m_positionZ, m_transport, MovementInfo::TransportInfo::pos, and MovementInfo::transport.
Referenced by IsWithinDist(), and IsWithinDistInMap().
AddAllowedLooter()
void WorldObject::AddAllowedLooter (ObjectGuid guid)
{
    _allowedLooters.insert(guid);
}
References _allowedLooters.
Referenced by GameObject::SetLootRecipient(), and Creature::SetLootRecipient().
AddObjectToRemoveList()
void WorldObject::AddObjectToRemoveList ()
{
    ASSERT(m_uint32Values);
    Map* map = FindMap();
    if (!map)
    {
        LOG_ERROR("entities.object", "Object {} at attempt add to move list not have valid map (Id: {}).", GetGUID().ToString(), GetMapId());
        return;
    }
    map->AddObjectToRemoveList(this);
}
References Map::AddObjectToRemoveList(), ASSERT, FindMap(), Object::GetGUID(), WorldLocation::GetMapId(), LOG_ERROR, Object::m_uint32Values, and Position::ToString().
Referenced by MotionTransport::DelayedTeleportTransport(), OPvPCapturePoint::DelCreature(), GameObject::Delete(), PoolGroup< T >::Despawn1Object(), CinematicMgr::EndCinematic(), ResetEncounterEvent::Execute(), npc_commandscript::HandleNpcDeleteCommand(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), DynamicObject::Remove(), Player::RemovePet(), MotionTransport::UnloadStaticPassengers(), TempSummon::UnSummon(), and Totem::UnSummon().
AddToNotify()
void WorldObject::AddToNotify (uint16 f)
{
    if (!(m_notifyflags & f))
        if (Unit* u = ToUnit())
        {
            if (f & NOTIFY_VISIBILITY_CHANGED)
            {
                uint32 EVENT_VISIBILITY_DELAY = u->FindMap() ? DynamicVisibilityMgr::GetVisibilityNotifyDelay(u->FindMap()->GetEntry()->map_type) : 1000;
                uint32 diff = getMSTimeDiff(u->m_last_notify_mstime, GameTime::GetGameTimeMS().count());
                if (diff >= EVENT_VISIBILITY_DELAY / 2)
                    EVENT_VISIBILITY_DELAY /= 2;
                else
                    EVENT_VISIBILITY_DELAY -= diff;
                u->m_delayed_unit_relocation_timer = EVENT_VISIBILITY_DELAY;
                u->m_last_notify_mstime = GameTime::GetGameTimeMS().count() + EVENT_VISIBILITY_DELAY - 1;
            }
            else if (f & NOTIFY_AI_RELOCATION)
            {
                u->m_delayed_unit_ai_notify_timer = u->FindMap() ? DynamicVisibilityMgr::GetAINotifyDelay(u->FindMap()->GetEntry()->map_type) : 500;
            }
            m_notifyflags |= f;
        }
}
References DynamicVisibilityMgr::GetAINotifyDelay(), GameTime::GetGameTimeMS(), getMSTimeDiff(), DynamicVisibilityMgr::GetVisibilityNotifyDelay(), m_notifyflags, NOTIFY_AI_RELOCATION, NOTIFY_VISIBILITY_CHANGED, and Object::ToUnit().
Referenced by Unit::ExecuteDelayedUnitRelocationEvent(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), Unit::SetContestedPvP(), Player::UpdateObjectVisibility(), and Unit::UpdateObjectVisibility().
AddToObjectUpdate()
void WorldObject::AddToObjectUpdate () override virtual
Implements Object.
{
    GetMap()->AddUpdateObject(this);
}
References Map::AddUpdateObject(), and GetMap().
AddToWorld()
void WorldObject::AddToWorld () override virtual
Reimplemented from Object.
Reimplemented in Pet, Player, and Unit.
{
    Object::AddToWorld();
    GetMap()->GetZoneAndAreaId(GetPhaseMask(), _zoneId, _areaId, GetPositionX(), GetPositionY(), GetPositionZ());
}
References _areaId, _zoneId, Object::AddToWorld(), GetMap(), GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), and Map::GetZoneAndAreaId().
Referenced by DynamicObject::AddToWorld(), GameObject::AddToWorld(), and Unit::AddToWorld().
BuildUpdate()
void WorldObject::BuildUpdate (UpdateDataMapType & data_map, UpdatePlayerSet & player_set) override virtual
Reimplemented from Object.
Reimplemented in MotionTransport, and StaticTransport.
{
    WorldObjectChangeAccumulator notifier(*this, data_map, player_set);
    //we must build packets for all visible players
    Cell::VisitWorldObjects(this, notifier, GetVisibilityRange());
    ClearUpdateMask(false);
}
References Object::ClearUpdateMask(), GetVisibilityRange(), and Cell::VisitWorldObjects().
CanAlwaysSee()
virtual bool WorldObject::CanAlwaysSee (WorldObject const *) const inline private virtual
Reimplemented in Creature, and Player.
{ return false; }
Referenced by CanSeeOrDetect().
CanDetect()
bool WorldObject::CanDetect (WorldObject const * obj, bool ignoreStealth, bool checkClient, bool checkAlert = false) const private
{
    WorldObject const* seer = this;
    // Pets don't have detection, they use the detection of their masters
    if (Unit const* thisUnit = ToUnit())
        if (Unit* controller = thisUnit->GetCharmerOrOwner())
            seer = controller;
    if (obj->IsAlwaysDetectableFor(seer) || GetEntry() == WORLD_TRIGGER) // xinef: World Trigger can detect all objects, used for wild gameobjects without owner!
        return true;
    if (!ignoreStealth)
    {
        if (!seer->CanDetectInvisibilityOf(obj)) // xinef: added ignoreStealth, allow AoE spells to hit invisible targets!
            return false;
        if (!seer->CanDetectStealthOf(obj, checkAlert))
        {
            // xinef: ignore units players have at client, this cant be cheated!
            if (checkClient)
            {
                if (GetTypeId() != TYPEID_PLAYER || !ToPlayer()->HaveAtClient(obj))
                    return false;
            }
            else
                return false;
        }
    }
    return true;
}
References CanDetectInvisibilityOf(), CanDetectStealthOf(), Unit::GetCharmerOrOwner(), Object::GetEntry(), Object::GetTypeId(), IsAlwaysDetectableFor(), Object::ToPlayer(), Object::ToUnit(), TYPEID_PLAYER, and WORLD_TRIGGER.
Referenced by CanSeeOrDetect().
CanDetectInvisibilityOf()
bool WorldObject::CanDetectInvisibilityOf (WorldObject const * obj) const private
{
    uint32 mask = obj->m_invisibility.GetFlags() & m_invisibilityDetect.GetFlags();
    // xinef: include invisible flags of caster in the mask, 2 invisible objects should be able to detect eachother
    mask |= obj->m_invisibility.GetFlags() & m_invisibility.GetFlags();
    // Check for not detected types
    if (mask != obj->m_invisibility.GetFlags())
        return false;
    // It isn't possible in invisibility to detect something that can't detect the invisible object
    // (it's at least true for spell: 66)
    // It seems like that only Units are affected by this check (couldn't see arena doors with preparation invisibility)
    if (obj->ToUnit())
    {
        uint32 objMask = m_invisibility.GetFlags() & obj->m_invisibilityDetect.GetFlags();
        // xinef: include invisible flags of caster in the mask, 2 invisible objects should be able to detect eachother
        objMask |= m_invisibility.GetFlags() & obj->m_invisibility.GetFlags();
        if (objMask != m_invisibility.GetFlags())
            return false;
    }
    for (uint32 i = 0; i < TOTAL_INVISIBILITY_TYPES; ++i)
    {
        if (!(mask & (1 << i)))
            continue;
        // xinef: visible for the same invisibility type:
        if (m_invisibility.GetValue(InvisibilityType(i)) && obj->m_invisibility.GetValue(InvisibilityType(i)))
            continue;
        int32 objInvisibilityValue = obj->m_invisibility.GetValue(InvisibilityType(i));
        int32 ownInvisibilityDetectValue = m_invisibilityDetect.GetValue(InvisibilityType(i));
        // Too low value to detect
        if (ownInvisibilityDetectValue < objInvisibilityValue)
            return false;
    }
    return true;
}
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetFlags(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetValue(), m_invisibility, m_invisibilityDetect, TOTAL_INVISIBILITY_TYPES, and Object::ToUnit().
Referenced by CanDetect().
CanDetectStealthOf()
bool WorldObject::CanDetectStealthOf (WorldObject const * obj, bool checkAlert = false) const private
{
    // Combat reach is the minimal distance (both in front and behind),
    //   and it is also used in the range calculation.
    // One stealth point increases the visibility range by 0.3 yard.
    if (!obj->m_stealth.GetFlags())
        return true;
    // dead players shouldnt be able to detect stealth on arenas
    if (isType(TYPEMASK_PLAYER))
        if (!ToPlayer()->IsAlive())
            return false;
    float distance = GetExactDist(obj);
    float combatReach = 0.0f;
    if (isType(TYPEMASK_UNIT))
        combatReach = ((Unit*)this)->GetCombatReach();
    if (distance < combatReach)
        return true;
    if (!HasInArc(M_PI, obj))
        return false;
    for (uint32 i = 0; i < TOTAL_STEALTH_TYPES; ++i)
    {
        if (!(obj->m_stealth.GetFlags() & (1 << i)))
            continue;
        if (isType(TYPEMASK_UNIT))
            if (((Unit*)this)->HasAuraTypeWithMiscvalue(SPELL_AURA_DETECT_STEALTH, i))
                return true;
        // Starting points
        int32 detectionValue = 30;
        // Level difference: 5 point / level, starting from level 1.
        // There may be spells for this and the starting points too, but
        // not in the DBCs of the client.
        detectionValue += int32(getLevelForTarget(obj) - 1) * 5;
        // Apply modifiers
        detectionValue += m_stealthDetect.GetValue(StealthType(i));
        if (obj->isType(TYPEMASK_GAMEOBJECT))
        {
            detectionValue += 30; // pussywizard: increase detection range for gameobjects (ie. traps)
            if (Unit* owner = ((GameObject*)obj)->GetOwner())
                detectionValue -= int32(owner->getLevelForTarget(this) - 1) * 5;
        }
        detectionValue -= obj->m_stealth.GetValue(StealthType(i));
        // Calculate max distance
        float visibilityRange = float(detectionValue) * 0.3f + combatReach;
        Unit const* unit = ToUnit();
        // If this unit is an NPC then player detect range doesn't apply
        if (unit && unit->GetTypeId() == TYPEID_PLAYER && visibilityRange > MAX_PLAYER_STEALTH_DETECT_RANGE)
            visibilityRange = MAX_PLAYER_STEALTH_DETECT_RANGE;
        if (checkAlert)
            visibilityRange += (visibilityRange * 0.08f) + 1.5f;
        Unit const* targetUnit = obj->ToUnit();
        // If checking for alert, and creature's visibility range is greater than aggro distance, No alert
        if (checkAlert && unit && unit->ToCreature() && visibilityRange >= unit->ToCreature()->GetAttackDistance(targetUnit) + unit->ToCreature()->m_CombatDistance)
            return false;
        if (distance > visibilityRange)
            return false;
    }
    return true;
}
References Creature::GetAttackDistance(), Position::GetExactDist(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetFlags(), getLevelForTarget(), Object::GetTypeId(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetValue(), Position::HasInArc(), Object::isType(), Creature::m_CombatDistance, m_stealth, m_stealthDetect, MAX_PLAYER_STEALTH_DETECT_RANGE, SPELL_AURA_DETECT_STEALTH, Object::ToCreature(), Object::ToPlayer(), TOTAL_STEALTH_TYPES, Object::ToUnit(), TYPEID_PLAYER, TYPEMASK_GAMEOBJECT, TYPEMASK_PLAYER, and TYPEMASK_UNIT.
Referenced by CanDetect().
CanNeverSee()
bool WorldObject::CanNeverSee (WorldObject const * obj) const private
{
    if (GetTypeId() == TYPEID_UNIT && obj->GetTypeId() == TYPEID_UNIT)
        return GetMap() != obj->GetMap() || (!InSamePhase(obj) && ToUnit()->GetVehicleBase() != obj && this != obj->ToUnit()->GetVehicleBase());
    return GetMap() != obj->GetMap() || !InSamePhase(obj);
}
References GetMap(), Object::GetTypeId(), Unit::GetVehicleBase(), InSamePhase(), Object::ToUnit(), and TYPEID_UNIT.
Referenced by CanSeeOrDetect().
CanSeeOrDetect()
bool WorldObject::CanSeeOrDetect (WorldObject const * obj, bool ignoreStealth = false, bool distanceCheck = false, bool checkAlert = false) const
{
    if (this == obj)
        return true;
    if (obj->IsNeverVisible() || CanNeverSee(obj))
        return false;
    if (obj->IsAlwaysVisibleFor(this) || CanAlwaysSee(obj))
        return true;
    // Creature scripts
    if (Creature const* cObj = obj->ToCreature())
    {
        if (Player const* player = this->ToPlayer())
        {
            if (cObj->IsAIEnabled && !cObj->AI()->CanBeSeen(player))
            {
                return false;
            }
            ConditionList conditions = sConditionMgr->GetConditionsForNotGroupedEntry(CONDITION_SOURCE_TYPE_CREATURE_VISIBILITY, cObj->GetEntry());
            if (!sConditionMgr->IsObjectMeetToConditions((WorldObject*)this, conditions))
            {
                return false;
            }
        }
    }
    // Gameobject scripts
    if (GameObject const* goObj = obj->ToGameObject())
        if (this->ToPlayer() && !goObj->AI()->CanBeSeen(this->ToPlayer()))
            return false;
    // pussywizard: arena spectator
    if (obj->GetTypeId() == TYPEID_PLAYER)
        if (((Player const*)obj)->IsSpectator() && ((Player const*)obj)->FindMap()->IsBattleArena())
            return false;
    bool corpseVisibility = false;
    if (distanceCheck)
    {
        bool corpseCheck = false;
        WorldObject const* viewpoint = this;
        if (Player const* thisPlayer = ToPlayer())
        {
            if (thisPlayer->isDead() && thisPlayer->GetHealth() > 0 && // Cheap way to check for ghost state
                    !(obj->m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GHOST) & m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GHOST) & GHOST_VISIBILITY_GHOST))
            {
                if (Corpse* corpse = thisPlayer->GetCorpse())
                {
                    corpseCheck = true;
                    if (corpse->IsWithinDist(thisPlayer, GetSightRange(obj), false))
                        if (corpse->IsWithinDist(obj, GetSightRange(obj), false))
                            corpseVisibility = true;
                }
            }
            // our additional checks
            if (Unit const* target = obj->ToUnit())
            {
                // xinef: don't allow to detect vehicle accessory if you can't see vehicle base!
                if (Unit const* vehicle = target->GetVehicleBase())
                    if (!thisPlayer->HaveAtClient(vehicle))
                        return false;
                // pussywizard: during arena preparation, don't allow to detect pets if can't see its owner (spoils enemy arena frames)
                if (target->IsPet() && target->GetOwnerGUID() && target->FindMap()->IsBattleArena() && GetGUID() != target->GetOwnerGUID())
                    if (BattlegroundMap* bgmap = target->FindMap()->ToBattlegroundMap())
                        if (Battleground* bg = bgmap->GetBG())
                            if (bg->GetStatus() < STATUS_IN_PROGRESS && !thisPlayer->HaveAtClient(target->GetOwnerGUID()))
                                return false;
            }
            if (thisPlayer->GetViewpoint())
                viewpoint = thisPlayer->GetViewpoint();
            if (thisPlayer->GetFarSightDistance() && !thisPlayer->isInFront(obj))
            {
                return false;
            }
        }
        // Xinef: check reversely obj vs viewpoint, object could be a gameObject which overrides _IsWithinDist function to include gameobject size
        if (!corpseCheck && !viewpoint->IsWithinDist(obj, GetSightRange(obj), true))
            return false;
    }
    // GM visibility off or hidden NPC
    if (!obj->m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GM))
    {
        // Stop checking other things for GMs
        if (m_serverSideVisibilityDetect.GetValue(SERVERSIDE_VISIBILITY_GM))
            return true;
    }
    else
        return m_serverSideVisibilityDetect.GetValue(SERVERSIDE_VISIBILITY_GM) >= obj->m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GM);
    // Ghost players, Spirit Healers, and some other NPCs
    if (!corpseVisibility && !(obj->m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GHOST) & m_serverSideVisibilityDetect.GetValue(SERVERSIDE_VISIBILITY_GHOST)))
    {
        // Alive players can see dead players in some cases, but other objects can't do that
        if (Player const* thisPlayer = ToPlayer())
        {
            if (Player const* objPlayer = obj->ToPlayer())
            {
                if (thisPlayer->GetTeamId() != objPlayer->GetTeamId() || !thisPlayer->IsGroupVisibleFor(objPlayer))
                    return false;
            }
            else
                return false;
        }
        else
            return false;
    }
    if (obj->IsInvisibleDueToDespawn())
        return false;
    // pussywizard: arena spectator
    if (this->GetTypeId() == TYPEID_PLAYER)
        if (((Player const*)this)->IsSpectator() && ((Player const*)this)->FindMap()->IsBattleArena() && (obj->m_invisibility.GetFlags() || obj->m_stealth.GetFlags()))
            return false;
    if (!CanDetect(obj, ignoreStealth, !distanceCheck, checkAlert))
        return false;
    return true;
}
References CanAlwaysSee(), CanDetect(), CanNeverSee(), CONDITION_SOURCE_TYPE_CREATURE_VISIBILITY, FindMap(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetFlags(), Object::GetGUID(), GetSightRange(), Object::GetTypeId(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetValue(), Unit::GetVehicleBase(), GHOST_VISIBILITY_GHOST, IsAlwaysVisibleFor(), IsInvisibleDueToDespawn(), IsNeverVisible(), IsWithinDist(), m_invisibility, m_serverSideVisibility, m_serverSideVisibilityDetect, m_stealth, sConditionMgr, SERVERSIDE_VISIBILITY_GHOST, SERVERSIDE_VISIBILITY_GM, STATUS_IN_PROGRESS, Map::ToBattlegroundMap(), Object::ToCreature(), Object::ToGameObject(), Object::ToPlayer(), Object::ToUnit(), and TYPEID_PLAYER.
Referenced by Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), Creature::CanAssistTo(), SpellInfo::CheckTarget(), CreatureUnitRelocationWorker(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::MoveInLineOfSight(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::MySelectNextTarget(), Acore::NearestAttackableUnitInObjectRangeCheck::operator()(), Acore::NearestVisibleDetectableContestedGuardUnitCheck::operator()(), Acore::VisibleNotifier::SendToSelf(), TotemAI::UpdateAI(), and Player::UpdateVisibilityOf().
CleanupsBeforeDelete()
void WorldObject::CleanupsBeforeDelete (bool finalCleanup = true) virtual
Reimplemented in DynamicObject, GameObject, Player, MotionTransport, StaticTransport, and Unit.
{
    if (IsInWorld())
        RemoveFromWorld();
}
References Object::IsInWorld(), and RemoveFromWorld().
Referenced by Map::AddObjectToRemoveList(), and DynamicObject::CleanupsBeforeDelete().
ClearZoneScript()
void WorldObject::ClearZoneScript ()
{
    m_zoneScript = nullptr;
}
References m_zoneScript.
DestroyForNearbyPlayers()
void WorldObject::DestroyForNearbyPlayers ()
Todo:
: this is for puppet
{
    if (!IsInWorld())
        return;
    std::list<Player*> targets;
    Acore::AnyPlayerInObjectRangeCheck check(this, GetVisibilityRange() + VISIBILITY_COMPENSATION, false);
    Acore::PlayerListSearcherWithSharedVision<Acore::AnyPlayerInObjectRangeCheck> searcher(this, targets, check);
    Cell::VisitWorldObjects(this, searcher, GetVisibilityRange());
    for (std::list<Player*>::const_iterator iter = targets.begin(); iter != targets.end(); ++iter)
    {
        Player* player = (*iter);
        if (player == this)
            continue;
        if (!player->HaveAtClient(this))
            continue;
        if (isType(TYPEMASK_UNIT) && ((Unit*)this)->GetCharmerGUID() == player->GetGUID())
            continue;
        DestroyForPlayer(player);
        player->m_clientGUIDs.erase(GetGUID());
    }
}
References Object::DestroyForPlayer(), Object::GetGUID(), GetVisibilityRange(), Player::HaveAtClient(), Object::IsInWorld(), Object::isType(), Player::m_clientGUIDs, TYPEMASK_UNIT, VISIBILITY_COMPENSATION, and Cell::VisitWorldObjects().
Referenced by Creature::DisappearAndDie(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), Creature::RemoveCorpse(), Map::RemoveCorpse(), RemoveFromWorld(), Map::RemovePlayerFromMap(), boss_urom::boss_uromAI::SpellHit(), GameObject::Update(), and go_witherbark_totem_bundle::go_witherbark_totem_bundleAI::UpdateAI().
FindMap()
Map * WorldObject::FindMap () const inline
{ return m_currMap; }
References m_currMap.
Referenced by Player::_AddSpellCooldown(), Group::_cancelHomebindIfInstance(), Group::_homebindIfInstance(), Player::_SaveCharacter(), HomeMovementGenerator< Creature >::_setTargetLocation(), FormationMgr::AddCreatureToGroup(), AddObjectToRemoveList(), Pet::AddToWorld(), Vehicle::ApplyAllImmunities(), Unit::BuildValuesUpdate(), Spell::cancel(), CanSeeOrDetect(), Spell::CheckCast(), Group::CountTheRoll(), Spell::DoAllEffectOnTarget(), ScriptedAI::DoPlayMusic(), Spell::EffectPersistentAA(), AuraMunchingQueue::Execute(), EoEDrakeEnterVehicleEvent::Execute(), Spell::finish(), lfg::LFGMgr::FinishDungeon(), spell_dk_scourge_strike::HandleAfterHit(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandleEnterPlayerVehicle(), WorldSession::HandlePlayerLoginOpcode(), spell_dk_blood_caked_blade::HandleProc(), ArenaSpectator::HandleResetCommand(), spell_temple_of_atal_hakkar_awaken_the_soulflayer::spell_temple_of_atal_hakkar_awaken_the_soulflayer_SpellScript::HandleSendEvent(), WorldSession::HandleSetDungeonDifficultyOpcode(), WorldSession::HandleSetRaidDifficultyOpcode(), misc_commandscript::HandleSkirmishCommand(), spectator_commandscript::HandleSpectatorLeaveCommand(), ArenaSpectator::HandleSpectatorSpectateCommand(), ArenaSpectator::HandleSpectatorWatchCommand(), Unit::HandleSpellClick(), IsInMap(), GameObject::IsInstanceGameobject(), boss_headless_horseman::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), Player::LoadFromDB(), Pet::LoadPetFromDB(), LogCommandUsage(), WorldSession::LogoutPlayer(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), Player::NeedSendSpectatorData(), achievement_once_bitten_twice_shy::OnCheck(), spell_blood_queen_pact_of_the_darkfallen_dmg::spell_blood_queen_pact_of_the_darkfallen_dmg_AuraScript::PeriodicTick(), SmartScript::ProcessAction(), FormationMgr::RemoveCreatureFromGroup(), Player::RemovePet(), Player::ResetInstances(), KillRewarder::Reward(), Spell::SendChannelStart(), Player::SendClearCooldown(), Spell::SendSpellStart(), setActive(), Player::setDeathState(), Unit::SetHealth(), Unit::SetMaxHealth(), Unit::SetMaxPower(), Player::SetMover(), Unit::SetPower(), Unit::setPowerType(), Player::SetSelection(), SetZoneScript(), SummonCreature(), Player::SummonPet(), OutdoorPvP::TeamCastSpell(), Map::Update(), Player::Update(), and Unit::Update().
FindNearestCreature()
Creature * WorldObject::FindNearestCreature (uint32 entry, float range, bool alive = true) const
{
    Creature* creature = nullptr;
    Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck checker(*this, entry, alive, range);
    Acore::CreatureLastSearcher<Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck> searcher(this, creature, checker);
    Cell::VisitAllObjects(this, searcher, range);
    return creature;
}
References Cell::VisitAllObjects().
Referenced by npc_thrall_bfu::npc_thrall_bfuAI::ActivateValimathrasPortal(), npc_mograine::npc_mograineAI::AshbringerEvent(), npc_commander_dawnforge::npc_commander_dawnforgeAI::CanStartEvent(), spell_renew_skirmisher::CheckRequirement(), spell_item_demon_broiled_surprise::CheckRequirement(), spell_q12943_shadow_vault_decree::CheckRequirement(), spell_item_map_of_the_geyser_fields::CheckSinkholes(), npc_q24545_lich_king::npc_q24545_lich_kingAI::CleanAll(), boss_grand_champion::boss_grand_championAI::DamageTaken(), npc_gunship::npc_gunshipAI::DamageTaken(), npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_jarien::DoAction(), boss_sothos::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::EnterCombat(), boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat(), boss_eregos::boss_eregosAI::EnterCombat(), boss_razorscale::boss_razorscaleAI::EnterCombat(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::EnterCombat(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::EnterCombat(), boss_thaddius_summon::boss_thaddius_summonAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), npc_sindragosa_trash::npc_sindragosa_trashAI::EnterCombat(), boss_razuvious_minion::boss_razuvious_minionAI::EnterCombat(), DelayedCastMincharEvent::Execute(), npc_dark_iron_guzzler::FindNextKeg(), npc_dark_iron_attack_generator::FinishAttackDueToWin(), npc_dark_iron_attack_generator::FinishEventDueToLoss(), GetClosestCreatureWithEntry(), socrethar::socretharAI::GetCreature(), npc_dark_iron_attack_generator::GetRandomBartender(), npc_razzashi_cobra_venoxis::npc_razzashi_cobra_venoxis_AI::GetVenoxis(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), HandleBothDead(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_valanar_kinetic_bomb::spell_valanar_kinetic_bomb_AuraScript::HandleDummyTick(), spell_q11719_bloodspore_ruination_45997::spell_q11719_bloodspore_ruination_45997_SpellScript::HandleEffect(), spell_gen_haunted_aura::HandleOnEffectRemove(), aura_class_call_siphon_blessing::HandlePeriodic(), spell_brewfest_toss_mug::HandleScriptEffect(), spell_q12943_shadow_vault_decree::HandleScriptEffect(), spell_q12620_the_lifewarden_wrath::spell_q12620_the_lifewarden_wrath_SpellScript::HandleSendEvent(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::HideNozdormu(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::IsSummonedBy(), npc_oculus_drake::npc_oculus_drakeAI::IsSummonedBy(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_malchezaar::boss_malchezaarAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), gunship_npc_AI::JustDied(), npc_q24545_vegard::npc_q24545_vegardAI::JustDied(), npc_enraged_spirit::npc_enraged_spiritAI::JustDied(), boss_jarien::JustDied(), boss_sothos::JustDied(), boss_cthun::JustDied(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::MoveInLineOfSight(), npc_cw_area_trigger::npc_cw_area_triggerAI::MoveInLineOfSight(), npc_black_knight_graveyard::npc_black_knight_graveyardAI::MoveInLineOfSight(), npc_daranelle::npc_daranelleAI::MoveInLineOfSight(), deathblow_to_the_legion_trigger::deathblow_to_the_legion_triggerAI::MoveInLineOfSight(), npc_sentinel_leader::MovementInform(), npc_sentinel_infiltrator::MovementInform(), adyen_the_lightbringer::adyen_the_lightbringerAI::MovementInform(), kaylaan_the_lost::kaylaan_the_lostAI::MovementInform(), npc_ishanah::ishanahAI::MovementInform(), boss_ymiron::boss_ymironAI::MovementInform(), npc_attracted_reef_bull::npc_attracted_reef_bullAI::MovementInform(), spell_q12987_read_pronouncement::OnApply(), go_ulduar_tower::OnDestroyed(), spell_bh_cleanse_quel_delar::spell_bh_cleanse_quel_delar_SpellScript::OnEffect(), go_gong_of_bethekk::OnGossipHello(), go_resonite_cask::OnGossipHello(), go_duskwither_spire_power_source::OnGossipHello(), go_blackened_urn::OnGossipHello(), go_acherus_soul_prison::OnGossipHello(), go_ravager_cage::OnGossipHello(), go_bristlelimb_cage::OnGossipHello(), go_panther_cage::OnGossipHello(), go_the_pearl_of_the_depths::OnGossipHello(), go_pressure_valve::OnGossipHello(), go_brazier::OnGossipHello(), go_finklestein_cauldron::OnGossipHello(), go_scourge_enclosure::OnGossipHello(), go_ahune_ice_stone::OnGossipHello(), go_simon_cluster::OnGossipHello(), go_corkis_prison::OnGossipHello(), go_warmaul_prison::OnGossipHello(), go_scourge_cage::OnGossipHello(), go_arcane_prison::OnGossipHello(), go_jotunheim_cage::OnGossipHello(), go_dragonflayer_cage::OnGossipHello(), go_hive_pod::OnGossipHello(), go_mistwhisper_treasure::OnGossipHello(), adyen_the_lightbringer::OnGossipSelect(), npc_mcmanus::OnGossipSelect(), go_ahune_ice_stone::OnGossipSelect(), npc_mikhail::OnQuestAccept(), npc_tyrion::OnQuestAccept(), go_crystal_prison::OnQuestAccept(), go_crystalline_tear::OnQuestAccept(), go_loosely_turned_soil::OnQuestReward(), spell_item_instant_statue::OnRemove(), at_cthun_stomach_exit::OnTrigger(), at_icc_spire_frostwyrm::OnTrigger(), at_q24545_frostmourne_cavern::OnTrigger(), AreaTrigger_at_scent_larkorwi::OnTrigger(), AreaTrigger_at_nats_landing::OnTrigger(), AreaTrigger_at_sentry_point::OnTrigger(), AreaTrigger_at_brewfest::OnTrigger(), at_blackrock_stadium::OnTrigger(), near_scarshield_infiltrator::OnTrigger(), at_scarshield_infiltrator::OnTrigger(), at_malfurion_stormrage::OnTrigger(), at_commander_dawnforge::OnTrigger(), item_incendiary_explosives::OnUse(), item_captured_frog::OnUse(), spell_quest_test_flight_charging::PerformKick(), spell_midsummer_ribbon_pole::PrepareAuraScript(), spell_pursuing_spikes::spell_pursuing_spikesAuraScript::PrepareAuraScript(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_victor_nefarius::boss_victor_nefariusAI::Reset(), boss_nefarian::Reset(), boss_jarien::Reset(), boss_sothos::Reset(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::Reset(), boss_eye_of_cthun::Reset(), boss_festergut::boss_festergutAI::Reset(), boss_thaddius_summon::boss_thaddius_summonAI::Reset(), npc_freya_ward::npc_freya_wardAI::Reset(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::Reset(), npc_amberpine_woodsman::npc_amberpine_woodsmanAI::Reset(), kaylaan_the_lost::kaylaan_the_lostAI::ResetDeathblowEvent(), boss_rend_blackhand::boss_rend_blackhandAI::SetData(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::SetData(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetData(), npc_shandy_dalaran::npc_shandy_dalaranAI::SetData(), npc_tharnarian::npc_tharnarianAI::SetGUID(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::ShowNozdormu(), npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI::SpellHit(), boss_thorim_pillar::boss_thorim_pillarAI::SpellHit(), npc_living_constellation::npc_living_constellationAI::SpellHit(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::SpellHit(), npc_greengill_slave::npc_greengill_slaveAI::SpellHit(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::SpreadFlame(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::StoreTargets(), boss_malchezaar::boss_malchezaarAI::SummonInfernal(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), go_bear_trap::go_bear_trapAI::UpdateAI(), SmartAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::UpdateAI(), npc_cameron::UpdateAI(), npc_eastvale_peasent::UpdateAI(), npc_sentinel_leader::UpdateAI(), npc_sentinel_infiltrator::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_alexstraza_the_lifebinder::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_medivh_bm::npc_medivh_bmAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_giant_spotlight::npc_giant_spotlightAI::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), boss_elder_nadox::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), npc_freya_ward::npc_freya_wardAI::UpdateAI(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::UpdateAI(), boss_kologarn::boss_kologarnAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::UpdateAI(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::UpdateAI(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::UpdateAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_thassarian::npc_thassarianAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_lord_arete::npc_lord_areteAI::UpdateAI(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_drakuru_shackles::npc_drakuru_shacklesAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::UpdateAI(), npc_naga_distiller::npc_naga_distillerAI::UpdateAI(), npc_fel_guard_hound::npc_fel_guard_houndAI::UpdateAI(), adyen_the_lightbringer::adyen_the_lightbringerAI::UpdateAI(), exarch_orelis::exarch_orelisAI::UpdateAI(), kaylaan_the_lost::kaylaan_the_lostAI::UpdateAI(), npc_captain_saeed::npc_captain_saeedAI::UpdateAI(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::UpdateAI(), npc_spring_rabbit::npc_spring_rabbitAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), npc_ranger_lilatha::WaypointReached(), npc_deathstalker_erland::npc_deathstalker_erlandAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_magwin::npc_magwinAI::WaypointReached(), npc_apothecary_hanes::npc_Apothecary_HanesAI::WaypointReached(), and npc_bessy::npc_bessyAI::WaypointReached().
FindNearestGameObject()
GameObject * WorldObject::FindNearestGameObject (uint32 entry, float range, bool onlySpawned = false) const
{
    GameObject* go = nullptr;
    Acore::NearestGameObjectEntryInObjectRangeCheck checker(*this, entry, range, onlySpawned);
    Acore::GameObjectLastSearcher<Acore::NearestGameObjectEntryInObjectRangeCheck> searcher(this, go, checker);
    Cell::VisitGridObjects(this, searcher, range);
    return go;
}
References Cell::VisitGridObjects().
Referenced by spell_q9452_cast_net::CheckCast(), npc_q24545_lich_king::npc_q24545_lich_kingAI::CleanAll(), boss_mimiron::boss_mimironAI::CloseDoorAndButton(), boss_hodir::boss_hodirAI::DamageTaken(), npc_ulduar_toasty_fire::npc_ulduar_toasty_fireAI::DoAction(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction(), Spell::EffectScriptEffect(), boss_hodir::boss_hodirAI::EnterCombat(), boss_ouro::EnterEvadeMode(), npc_dirt_mound::EnterEvadeMode(), GetClosestGameObjectWithEntry(), spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::HandleDummy(), boss_vezax::boss_vezaxAI::JustDied(), boss_kologarn::boss_kologarnAI::JustDied(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustDied(), npc_andorhal_tower::npc_andorhal_towerAI::MoveInLineOfSight(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), npc_pos_leader_second::npc_pos_leader_secondAI::MovementInform(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::MovementInform(), go_thorim_lever::OnGossipHello(), npc_natrualist_bite::OnGossipSelect(), npc_lurgglbr::OnQuestAccept(), npc_simon_bunny::npc_simon_bunnyAI::PrepareClusters(), instance_stratholme::instance_stratholme_InstanceMapScript::ProcessSlaughterEvent(), npc_ranger_lilatha::Reset(), npc_stillpine_capitive::npc_stillpine_capitiveAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_hodir::boss_hodirAI::Reset(), boss_mimiron::boss_mimironAI::ResetGameObjects(), npc_simon_bunny::npc_simon_bunnyAI::ResetNode(), npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI::SetData(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), boss_rend_blackhand::boss_rend_blackhandAI::SetData(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetData(), npc_simon_bunny::npc_simon_bunnyAI::SetUpPreGame(), npc_crate_helper::npc_crate_helperAI::SpellHit(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::SpellHit(), npc_rinji::npc_rinjiAI::sQuestAccept(), npc_simon_bunny::npc_simon_bunnyAI::StartGame(), boss_ouro::Submerge(), npc_grimstone::npc_grimstoneAI::SummonBoss(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::TurnRunes(), boss_gyth::boss_gythAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_scarlet_courier::npc_scarlet_courierAI::UpdateAI(), npc_partygoer::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_giant_spotlight::npc_giant_spotlightAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_pet_gen_plump_turkey::UpdateAI(), npc_tallhorn_stag::npc_tallhorn_stagAI::UpdateAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_ranger_lilatha::WaypointReached(), and npc_isla_starmane::npc_isla_starmaneAI::WaypointReached().
FindNearestGameObjectOfType()
GameObject * WorldObject::FindNearestGameObjectOfType (GameobjectTypes type, float range) const
{
    GameObject* go = nullptr;
    Acore::NearestGameObjectTypeInObjectRangeCheck checker(*this, type, range);
    Acore::GameObjectLastSearcher<Acore::NearestGameObjectTypeInObjectRangeCheck> searcher(this, go, checker);
    Cell::VisitGridObjects(this, searcher, range);
    return go;
}
References Cell::VisitGridObjects().
Referenced by Map::GetTransportForPos(), and WorldSession::HandleAlterAppearance().
GetAllowedLooters()
GuidUnorderedSet const & WorldObject::GetAllowedLooters () const
{
    return _allowedLooters;
}
References _allowedLooters.
Referenced by GameObject::SetLootRecipient().
GetAreaId()
uint32 WorldObject::GetAreaId () const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    return _areaId;
}
References _areaId, _updatePositionData, and UpdatePositionData().
Referenced by Player::AddQuest(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Player::CompleteQuest(), ScriptedAI::DoPlayMusic(), Spell::EffectBind(), Spell::EffectDuel(), npc_gilthares::npc_giltharesAI::EnterCombat(), npc_costumed_orphan_matron::GetInitXYZ(), go_bells::go_bellsAI::go_bellsAI(), spell_item_socrethars_stone::HandleDummy(), WorldSession::HandleHearthAndResurrect(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandlePlayerLoginFromDB(), spell_gen_teleporting::HandleScript(), spell_q12735_song_of_cleansing::HandleScript(), Player::IncompleteQuest(), DisableMgr::IsDisabledFor(), SpellArea::IsFitToRequirements(), LogCommandUsage(), npc_the_scourge_cauldron::npc_the_scourge_cauldronAI::MoveInLineOfSight(), npc_guardian_pavilion::npc_guardian_pavilionAI::MoveInLineOfSight(), achievement_tilted::OnCheck(), BattlefieldWG::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnPlayerAreaUpdate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnUnitDeath(), item_petrov_cluster_bombs::OnUse(), item_only_for_flight::OnUse(), FlameLeviathanPursuedTargetSelector::operator()(), SmartScript::ProcessAction(), Player::RemoveActiveQuest(), Player::RepopAtGraveyard(), Player::RewardHonor(), Player::RewardQuest(), CreatureTextMgr::SendChatPacket(), CreatureTextMgr::SendNonChatPacket(), Creature::SendZoneUnderAttackMessage(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), and lfg::LFGMgr::UpdateRaidBrowser().
GetChargeContactPoint()
void WorldObject::GetChargeContactPoint (WorldObject const * obj, float & x, float & y, float & z, float distance2d = CONTACT_DISTANCE) const
{
    // angle to face `obj` to `this` using distance includes size of `obj`
    GetNearPoint(obj, x, y, z, obj->GetObjectSize(), distance2d, GetAngle(obj));
    if (std::fabs(this->GetPositionZ() - z) > 3.0f || !IsWithinLOS(x, y, z))
    {
        x = this->GetPositionX();
        y = this->GetPositionY();
        z = this->GetPositionZ();
        obj->UpdateGroundPositionZ(x, y, z);
    }
}
References Position::GetAngle(), GetNearPoint(), GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), IsWithinLOS(), and UpdateGroundPositionZ().
GetClosePoint()
bool WorldObject::GetClosePoint (float & x, float & y, float & z, float size, float distance2d = 0, float angle = 0, WorldObject const * forWho = nullptr, bool force = false) const
{
    // angle calculated from current orientation
    GetNearPoint(forWho, x, y, z, size, distance2d, GetOrientation() + angle);
    if (std::fabs(this->GetPositionZ() - z) > 3.0f || !IsWithinLOS(x, y, z))
    {
        x = this->GetPositionX();
        y = this->GetPositionY();
        z = this->GetPositionZ();
        if (forWho)
            if (Unit const* u = forWho->ToUnit())
                u->UpdateAllowedPositionZ(x, y, z);
    }
    float maxDist = GetObjectSize() + size + distance2d + 1.0f;
    if (GetExactDistSq(x, y, z) >= maxDist * maxDist)
    {
        if (force)
        {
            x = this->GetPositionX();
            y = this->GetPositionY();
            z = this->GetPositionZ();
            return true;
        }
        return false;
    }
    return true;
}
References Position::GetExactDistSq(), GetNearPoint(), GetObjectSize(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), IsWithinLOS(), and Object::ToUnit().
Referenced by Spell::EffectResurrectPet(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectTransmitted(), cast_commandscript::HandleCastDistCommand(), debug_commandscript::HandleDebugSpawnVehicleCommand(), misc_commandscript::HandleGroupSummonCommand(), spell_item_draenic_pale_ale::HandleSummon(), misc_commandscript::HandleSummonCommand(), Pet::LoadPetFromDB(), MotionMaster::MoveJumpTo(), SmartScript::ProcessAction(), npc_released_offspring_harkoa::npc_released_offspring_harkoaAI::Reset(), boss_selin_fireheart::boss_selin_fireheartAI::SelectNearestCrystal(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::SpellHit(), SummonCreature(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), and npc_toc_dk::npc_toc_dkAI::UpdateAI().
GetCollisionHeight()
virtual float WorldObject::GetCollisionHeight () const inline virtual
Reimplemented in Unit.
{ return 0.0f; }
Referenced by PathGenerator::BuildPolyPath(), Map::CanReachPositionAndGetValidCoords(), Map::CheckCollisionAndGetValidCoords(), GetFloorZ(), GetHitSpherePointFor(), GetMapHeight(), GetMapWaterOrGroundLevel(), GetMinHeightInWater(), PathGenerator::GetNavTerrain(), GetNearPoint(), Map::HasEnoughWater(), PathGenerator::IsSwimmableSegment(), PathGenerator::IsWalkableClimb(), IsWithinLOS(), IsWithinLOSInMap(), PathGenerator::ShortenPathUntilDist(), and UpdatePositionData().
GetCollisionRadius()
virtual float WorldObject::GetCollisionRadius () const inline virtual
Reimplemented in Unit.
{ return GetObjectSize() / 2; }
References GetObjectSize().
GetCollisionWidth()
virtual float WorldObject::GetCollisionWidth () const inline virtual
Reimplemented in Unit.
{ return GetObjectSize(); }
References GetObjectSize().
Referenced by GetMinHeightInWater().
GetCombatReach()
virtual float WorldObject::GetCombatReach () const inline virtual
Reimplemented in Unit.
{ return 0.0f; } // overridden (only) in Unit
Referenced by GetHitSpherePointFor(), GetNearPoint2D(), and Cell::Visit().
GetContactPoint()
void WorldObject::GetContactPoint (WorldObject const * obj, float & x, float & y, float & z, float distance2d = CONTACT_DISTANCE) const
{
    // angle to face `obj` to `this` using distance includes size of `obj`
    GetNearPoint(obj, x, y, z, obj->GetObjectSize(), distance2d, GetAngle(obj));
    // Exclude gameobjects from LoS calculations
    if (std::fabs(this->GetPositionZ() - z) > 3.0f || (GetTypeId() != TYPEID_GAMEOBJECT && !IsWithinLOS(x, y, z)))
    {
        x = this->GetPositionX();
        y = this->GetPositionY();
        z = this->GetPositionZ();
        obj->UpdateAllowedPositionZ(x, y, z);
    }
}
References Position::GetAngle(), GetNearPoint(), GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::GetTypeId(), IsWithinLOS(), TYPEID_GAMEOBJECT, and UpdateAllowedPositionZ().
Referenced by npc_unworthy_initiate::npc_unworthy_initiateAI::EventStart(), and Unit::JumpTo().
GetCreatureListWithEntryInGrid()
void WorldObject::GetCreatureListWithEntryInGrid (std::list< Creature * > & lList, uint32 uiEntry, float fMaxSearchRange) const
{
    Acore::AllCreaturesOfEntryInRange check(this, entry, maxSearchRange);
    Acore::CreatureListSearcher<Acore::AllCreaturesOfEntryInRange> searcher(this, creatureList, check);
    Cell::VisitGridObjects(this, searcher, maxSearchRange);
}
References Cell::VisitGridObjects().
Referenced by npc_anubisath_sentinel::aqsentinelAI::AddSentinelsNear(), boss_nefarian::DamageTaken(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::DoGuardsDisappearAndDie(), npc_lava_spawn::EnterCombat(), boss_elder_nadox::EnterCombat(), spell_the_lich_king_restore_soul::spell_the_lich_king_restore_soul_SpellScript::FilterTargets(), boss_the_beast::boss_thebeastAI::FindNearbyOrcs(), GetCreatureListWithEntryInGrid(), spell_apothecary_lingering_fumes::HandleAfterCast(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), spell_q12243_fire_upon_the_waters::spell_q12243_fire_upon_the_waters_AuraScript::HandleApplyEffect(), BattlegroundIC::HandleCapturedNodes(), BattlegroundIC::HandleContestedNodes(), spell_warhead_detonate::spell_warhead_detonate_SpellScript::HandleDummy(), spell_icc_sprit_alarm::spell_icc_sprit_alarm_SpellScript::HandleEvent(), spell_q12243_fire_upon_the_waters::spell_q12243_fire_upon_the_waters_AuraScript::HandleRemoveEffect(), spell_q12620_the_lifewarden_wrath::spell_q12620_the_lifewarden_wrath_SpellScript::HandleSendEvent(), boss_twilight_corrupter::InitializeAI(), boss_rajaxx::JustDied(), instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript::OnPlayerAreaUpdate(), instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript::OnPlayerEnter(), SmartScript::ProcessEvent(), boss_jaraxxus::boss_jaraxxusAI::Reset(), boss_venoxis::boss_venoxisAI::SetCombatCombras(), boss_ouro::Submerge(), npc_thrall_bfu::npc_thrall_bfuAI::SummonedCreatureDies(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), and npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI().
GetCreaturesWithEntryInRange()
void WorldObject::GetCreaturesWithEntryInRange (std::list< Creature * > & creatureList, float radius, uint32 entry)
{
    CellCoord pair(Acore::ComputeCellCoord(this->GetPositionX(), this->GetPositionY()));
    Cell cell(pair);
    cell.SetNoCreate();
    Acore::AllCreaturesOfEntryInRange check(this, entry, radius);
    Acore::CreatureListSearcher<Acore::AllCreaturesOfEntryInRange> searcher(this, creatureList, check);
    TypeContainerVisitor<Acore::CreatureListSearcher<Acore::AllCreaturesOfEntryInRange>, WorldTypeMapContainer> world_visitor(searcher);
    cell.Visit(pair, world_visitor, *(this->GetMap()), *this, radius);
    TypeContainerVisitor<Acore::CreatureListSearcher<Acore::AllCreaturesOfEntryInRange>, GridTypeMapContainer> grid_visitor(searcher);
    cell.Visit(pair, grid_visitor, *(this->GetMap()), *this, radius);
}
References Acore::ComputeCellCoord(), GetMap(), Position::GetPositionX(), Position::GetPositionY(), Cell::SetNoCreate(), and Cell::Visit().
Referenced by boss_kelthuzad_minion::boss_kelthuzad_minionAI::AttackStart(), spell_midsummer_fling_torch::CheckCast(), boss_ignis::boss_ignisAI::EnterCombat(), boss_razorscale::boss_razorscaleAI::EnterCombat(), CorruptTriggers::Execute(), FixOrientation::Execute(), spell_black_template_harpooners_mark::spell_black_template_harpooners_mark_AuraScript::HandleEffectApply(), spell_botanica_call_of_the_falcon::spell_botanica_call_of_the_falcon_AuraScript::HandleEffectApply(), spell_mc_play_dead::spell_mc_play_dead_AuraScript::HandleEffectRemove(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), boss_headless_horseman::JustDied(), boss_ignis::boss_ignisAI::JustDied(), npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned(), boss_buru::ManipulateEggs(), spell_dreamwalker_summon_suppresser::spell_dreamwalker_summon_suppresser_AuraScript::PeriodicTick(), boss_grobbulus::boss_grobbulusAI::PullChamberAdds(), npc_hallows_end_soh::Reset(), npc_captain_saeed::npc_captain_saeedAI::SetGUID(), boss_hodir::boss_hodirAI::SpellHitTarget(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::UpdateAI(), and npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI().
GetDeadCreatureListInGrid()
void WorldObject::GetDeadCreatureListInGrid (std::list< Creature * > & lList, float maxSearchRange, bool alive = false) const
{
    Acore::AllDeadCreaturesInRange check(this, maxSearchRange, alive);
    Acore::CreatureListSearcher<Acore::AllDeadCreaturesInRange> searcher(this, creaturedeadList, check);
    Cell::VisitGridObjects(this, searcher, maxSearchRange);
}
References Cell::VisitGridObjects().
Referenced by GetDeadCreatureListInGrid().
GetDebugInfo()
std::string WorldObject::GetDebugInfo () const override virtual
Reimplemented from Object.
Reimplemented in Pet, Player, MotionTransport, and Unit.
{
    std::stringstream sstr;
    sstr << WorldLocation::GetDebugInfo() << "\n"
        << Object::GetDebugInfo() << "\n"
        << "Name: " << GetName();
    return sstr.str();
}
References Object::GetDebugInfo(), WorldLocation::GetDebugInfo(), and GetName().
Referenced by Aura::GetDebugInfo(), GameObject::GetDebugInfo(), and Unit::GetDebugInfo().
GetDistance() [1/3]
float WorldObject::GetDistance (const Position & pos) const
{
    float d = GetExactDist(&pos) - GetObjectSize();
    return d > 0.0f ? d : 0.0f;
}
References Position::GetExactDist(), and GetObjectSize().
GetDistance() [2/3]
float WorldObject::GetDistance (float x, float y, float z) const
{
    float d = GetExactDist(x, y, z) - GetObjectSize();
    return d > 0.0f ? d : 0.0f;
}
References Position::GetExactDist(), and GetObjectSize().
GetDistance() [3/3]
float WorldObject::GetDistance (WorldObject const * obj) const
{
    float d = GetExactDist(obj) - GetObjectSize() - obj->GetObjectSize();
    return d > 0.0f ? d : 0.0f;
}
References Position::GetExactDist(), and GetObjectSize().
Referenced by Spell::AddGOTarget(), Spell::AddUnitTarget(), boss_hadronox::boss_hadronoxAI::AnyPlayerValid(), boss_urom::boss_uromAI::AttackStart(), Spell::CheckCast(), boss_teron_gorefiend::boss_teron_gorefiendAI::CheckEvadeIfOutOfCombatArea(), boss_isle_of_conquest::boss_isle_of_conquestAI::CheckRageBuff(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::DamageTaken(), Spell::EffectChargeDest(), Spell::EffectPullTowards(), boss_sapphiron::boss_sapphironAI::EnterCombatSelfFunction(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), Unit::GetMagicHitRedirectTarget(), boss_urom::boss_uromAI::GetPhaseByCurrentPosition(), FleeingMovementGenerator< T >::GetPoint(), npc_wild_wyrm::npc_wild_wyrmAI::GetValidPlayer(), OutdoorPvPSI::HandleDropFlag(), Unit::HandleDummyAuraProc(), spell_image_of_drakuru_reagent_check::HandleDummyEffect(), spell_herald_volzaj_insanity::HandleDummyEffect(), spell_egg_explosion::HandleDummyHitTarget(), misc_commandscript::HandleGetDistanceCommand(), spell_garr_separation_nexiety::spell_garr_separation_nexiety_AuraScript::HandlePeriodic(), spell_majordomo_separation_nexiety::spell_majordomo_separation_nexiety_AuraScript::HandlePeriodic(), spell_entropius_black_hole_effect::spell_entropius_black_hole_effect_SpellScript::HandlePull(), spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript::HandlePull(), spell_gen_ds_flush_knockback::HandleScript(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), Player::IsAtGroupRewardDistance(), Player::IsAtRecruitAFriendDistance(), SmartAI::IsEscortInvokerInRange(), Player::IsInAreaTriggerRadius(), boss_sartharion::boss_sartharionAI::IsTargetInBounds(), boss_hadronox::boss_hadronoxAI::JustSummoned(), boss_gal_darah::boss_gal_darahAI::JustSummoned(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustSummoned(), Condition::Meets(), npc_brewfest_keg_thrower::MoveInLineOfSight(), npc_brewfest_keg_reciver::MoveInLineOfSight(), npc_brewfest_bark_trigger::MoveInLineOfSight(), npc_love_in_air_supply_sentry::MoveInLineOfSight(), npc_love_in_air_snivel::MoveInLineOfSight(), boss_kelthuzad::boss_kelthuzadAI::MoveInLineOfSight(), npc_black_knight_graveyard::npc_black_knight_graveyardAI::MoveInLineOfSight(), npc_captain_saeed::npc_captain_saeedAI::MoveInLineOfSight(), spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_AuraScript::OnPeriodic(), Acore::NearestAssistCreatureInCreatureRangeCheck::operator()(), Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::operator()(), Acore::NearestGameObjectFishingHole::operator()(), Acore::NearestGameObjectCheck::operator()(), Acore::NearestGameObjectEntryInObjectRangeCheck::operator()(), Acore::NearestGameObjectTypeInObjectRangeCheck::operator()(), Acore::NearestPlayerInObjectRangeCheck::operator()(), Acore::NearestAttackableUnitInObjectRangeCheck::operator()(), Acore::NearestHostileUnitCheck::operator()(), Acore::NearestHostileUnitInAttackDistanceCheck::operator()(), ManaVoidSelector::operator()(), Acore::WorldObjectSpellNearbyTargetCheck::operator()(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), spell_quest_test_flight_charging::PerformKick(), Creature::reachWithSpellAttack(), Creature::reachWithSpellCure(), Map::ScriptsProcess(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::SelectCorruptionTarget(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::SetData(), spell_midsummer_fling_torch::ThrowNextTorch(), Pet::Update(), boss_broodlord::boss_broodlordAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), npc_kernobee::npc_kernobeeAI::UpdateAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::UpdateAI(), npc_dark_nucleus::npc_dark_nucleusAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::UpdateAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), boss_volkhan::boss_volkhanAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::UpdateAI(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::UpdateAI(), boss_xevozz::boss_xevozzAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_supremus::boss_supremusAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_pet_gen_target_following_bomb::UpdateAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::UpdateAI(), Player::UpdateCharmedAI(), and brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI().
GetDistance2d() [1/2]
float WorldObject::GetDistance2d (float x, float y) const
{
    float d = GetExactDist2d(x, y) - GetObjectSize();
    return d > 0.0f ? d : 0.0f;
}
References Position::GetExactDist2d(), and GetObjectSize().
GetDistance2d() [2/2]
float WorldObject::GetDistance2d (WorldObject const * obj) const
{
    float d = GetExactDist2d(obj) - GetObjectSize() - obj->GetObjectSize();
    return d > 0.0f ? d : 0.0f;
}
References Position::GetExactDist2d(), and GetObjectSize().
Referenced by spell_krystallus_shatter_effect::spell_krystallus_shatter_effect_SpellScript::CalculateDamage(), spell_gruul_shatter_effect::spell_gruul_shatter_effect_SpellScript::CalculateDamage(), spell_loken_pulsing_shockwave::spell_loken_pulsing_shockwave_SpellScript::CalculateDamage(), npc_cork_gizelton::npc_cork_gizeltonAI::CheckCaravan(), spell_baltharus_enervating_brand_trigger::spell_baltharus_enervating_brand_trigger_SpellScript::CheckDistance(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::CheckEvadeIfOutOfCombatArea(), boss_void_reaver::boss_void_reaverAI::CheckEvadeIfOutOfCombatArea(), boss_onyxia::CheckInRoom(), npc_argent_captainAI::DoAction(), boss_faction_championsAI::EnemiesInRange(), BattlegroundAB::EventPlayerClickedOnFlag(), BfGraveyard::GetDistance(), npc_spiritual_insight::npc_spiritual_insightAI::GetSpeachId(), GetVelocity(), spell_shadowblink::HandleDummy(), misc_commandscript::HandleGetDistanceCommand(), boss_aeonus::boss_aeonusAI::JustReachedHome(), npc_scarlet_guard::npc_scarlet_guardAI::MoveInLineOfSight(), npc_mograine::npc_mograineAI::MoveInLineOfSight(), npc_fairbanks::npc_fairbanksAI::MoveInLineOfSight(), npc_winterfin_playmate::MoveInLineOfSight(), npc_snowfall_glade_playmate::MoveInLineOfSight(), npc_the_biggest_tree::MoveInLineOfSight(), npc_high_oracle_soo_roo::MoveInLineOfSight(), npc_elder_kekek::MoveInLineOfSight(), npc_the_etymidian::MoveInLineOfSight(), npc_alexstraza_the_lifebinder::MoveInLineOfSight(), npc_cw_area_trigger::npc_cw_area_triggerAI::MoveInLineOfSight(), npc_grizzlemaw_cw_trigger::npc_grizzlemaw_cw_triggerAI::MoveInLineOfSight(), npc_hol_monument::npc_hol_monumentAI::MoveInLineOfSight(), npc_jungle_punch_target::npc_jungle_punch_targetAI::MoveInLineOfSight(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::MoveInLineOfSight(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnCreatureCreate(), spell_algalon_cosmic_smash_damage::spell_algalon_cosmic_smash_damage_SpellScript::RecalculateDamage(), boss_priestess_lackey_commonAI::RecalculateThreat(), boss_faction_championsAI::RecalculateThreat(), RevivePlayer(), Player::TeleportTo(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), npc_water_elemental::npc_water_elementalAI::UpdateAI(), boss_balinda::boss_balindaAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_hedrum::boss_hedrumAI::UpdateAI(), boss_okthor::boss_okthorAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI(), npc_singularity::npc_singularityAI::UpdateAI(), npc_eris_hevenfire::npc_eris_hevenfireAI::UpdateAI(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), npc_preparations_for_war_vehicle::UpdateAI(), npc_boneguard_footman::npc_boneguard_footmanAI::UpdateAI(), npc_pet_gen_fetch_ball::UpdateAI(), npc_demonic_vapor::npc_demonic_vaporAI::UpdateAI(), BattlefieldWG::UpdatedDestroyedTowerCount(), boss_netherspite::boss_netherspiteAI::UpdatePortals(), and GameObject::Use().
GetDistanceOrder()
bool WorldObject::GetDistanceOrder (WorldObject const * obj1, WorldObject const * obj2, bool is3D = true) const
{
    float dx1 = GetPositionX() - obj1->GetPositionX();
    float dy1 = GetPositionY() - obj1->GetPositionY();
    float distsq1 = dx1 * dx1 + dy1 * dy1;
    if (is3D)
    {
        float dz1 = GetPositionZ() - obj1->GetPositionZ();
        distsq1 += dz1 * dz1;
    }
    float dx2 = GetPositionX() - obj2->GetPositionX();
    float dy2 = GetPositionY() - obj2->GetPositionY();
    float distsq2 = dx2 * dx2 + dy2 * dy2;
    if (is3D)
    {
        float dz2 = GetPositionZ() - obj2->GetPositionZ();
        distsq2 += dz2 * dz2;
    }
    return distsq1 < distsq2;
}
References Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
Referenced by Acore::ObjectDistanceOrderPred::operator()(), Spell::SearchChainTargets(), and boss_selin_fireheart::boss_selin_fireheartAI::SelectNearestCrystal().
GetDistanceZ()
float WorldObject::GetDistanceZ (WorldObject const * obj) const
{
    float dz = std::fabs(GetPositionZ() - obj->GetPositionZ());
    float sizefactor = GetObjectSize() + obj->GetObjectSize();
    float dist = dz - sizefactor;
    return (dist > 0 ? dist : 0);
}
References GetObjectSize(), and Position::GetPositionZ().
Referenced by Creature::CanStartAttack(), and npc_pet_hunter_snake_trap::MoveInLineOfSight().
GetFirstCollisionPosition() [1/3]
Position WorldObject::GetFirstCollisionPosition (float destX, float destY, float destZ)
{
    Position pos = GetPosition();
    auto distance = GetExactDistSq(destX,destY,destZ);
    auto dx = destX - pos.GetPositionX();
    auto dy = destY - pos.GetPositionY();
    auto ang = std::atan2(dy, dx);
    ang = (ang >= 0) ? ang : 2 * M_PI + ang;
    MovePositionToFirstCollision(pos, distance, ang);
    return pos;
}
References Position::GetExactDistSq(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), and MovePositionToFirstCollision().
GetFirstCollisionPosition() [2/3]
Position WorldObject::GetFirstCollisionPosition (float dist, float angle)
{
    Position pos = GetPosition();
    MovePositionToFirstCollision(pos, dist, angle);
    return pos;
}
References Position::GetPosition(), and MovePositionToFirstCollision().
GetFirstCollisionPosition() [3/3]
Position WorldObject::GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
{
    auto dx = destX - startX;
    auto dy = destY - startY;
    auto ang = std::atan2(dy, dx);
    ang = (ang >= 0) ? ang : 2 * M_PI + ang;
    Position pos = Position(startX, startY, startZ, ang);
    auto distance = pos.GetExactDist2d(destX,destY);
    MovePositionToFirstCollision(pos, distance, ang);
    return pos;
}
References Position::GetExactDist2d(), and MovePositionToFirstCollision().
Referenced by Spell::EffectCharge(), Spell::EffectChargeDest(), spell_class_call_handler::HandleOnHitRogue(), and npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI().
GetFloorZ()
float WorldObject::GetFloorZ () const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    if (!IsInWorld())
        return _floorZ;
    return std::max<float>(_floorZ, GetMap()->GetGameObjectFloor(GetPhaseMask(), GetPositionX(), GetPositionY(), GetPositionZ() + std::max(GetCollisionHeight(), Z_OFFSET_FIND_HEIGHT)));
}
References _floorZ, _updatePositionData, GetCollisionHeight(), GetMap(), GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::IsInWorld(), UpdatePositionData(), and Z_OFFSET_FIND_HEIGHT.
Referenced by npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), Unit::SetHover(), and Creature::UpdateMovementFlags().
GetGameObjectListWithEntryInGrid()
void WorldObject::GetGameObjectListWithEntryInGrid (std::list< GameObject * > & lList, uint32 uiEntry, float fMaxSearchRange) const
{
    Acore::AllGameObjectsWithEntryInRange check(this, entry, maxSearchRange);
    Acore::GameObjectListSearcher<Acore::AllGameObjectsWithEntryInRange> searcher(this, gameobjectList, check);
    Cell::VisitGridObjects(this, searcher, maxSearchRange);
}
References Cell::VisitGridObjects().
Referenced by npc_midsummer_torch_target::FillPositions(), GetGameObjectListWithEntryInGrid(), spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript::HandleScriptEffect(), SmartScript::ProcessEvent(), boss_marli::Reset(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), and boss_sindragosa::boss_sindragosaAI::UpdateAI().
GetGridActivationRange()
float WorldObject::GetGridActivationRange () const
{
    if (ToPlayer())
    {
        if (ToPlayer()->GetCinematicMgr()->IsOnCinematic())
        {
            return DEFAULT_VISIBILITY_INSTANCE;
        }
        return IsInWintergrasp() ? VISIBILITY_DIST_WINTERGRASP : GetMap()->GetVisibilityRange();
    }
    else if (ToCreature())
    {
        return ToCreature()->m_SightDistance;
    }
    else if (((GetTypeId() == TYPEID_GAMEOBJECT && ToGameObject()->IsTransport()) || GetTypeId() == TYPEID_DYNAMICOBJECT) && isActiveObject())
    {
        return GetMap()->GetVisibilityRange();
    }
    return 0.0f;
}
References DEFAULT_VISIBILITY_INSTANCE, GetMap(), Object::GetTypeId(), Map::GetVisibilityRange(), isActiveObject(), IsInWintergrasp(), Creature::m_SightDistance, Object::ToCreature(), Object::ToGameObject(), Object::ToPlayer(), TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, and VISIBILITY_DIST_WINTERGRASP.
Referenced by boss_janalai::boss_janalaiAI::Boom(), hyjalAI::DoOverrun(), misc_commandscript::HandleRespawnAllCommand(), boss_janalai::boss_janalaiAI::HatchAllEggs(), npc_janalai_hatcher::npc_janalai_hatcherAI::HatchEggs(), hyjalAI::HideNearPos(), boss_nalorakk::boss_nalorakkAI::ResetMobs(), hyjalAI::RespawnNearPos(), boss_nalorakk::boss_nalorakkAI::SendAttacker(), Map::Update(), Map::VisitNearbyCellsOf(), and hyjalAI::WaypointReached().
GetHitSpherePointFor() [1/2]
void WorldObject::GetHitSpherePointFor (Position const & dest, float & x, float & y, float & z, Optional< float > collisionHeight = { }) const
{
    Position pos = GetHitSpherePointFor(dest, collisionHeight);
    x = pos.GetPositionX();
    y = pos.GetPositionY();
    z = pos.GetPositionZ();
}
References GetHitSpherePointFor(), Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
GetHitSpherePointFor() [2/2]
Position WorldObject::GetHitSpherePointFor (Position const & dest, Optional< float > collisionHeight = { }) const
{
    G3D::Vector3 vThis(GetPositionX(), GetPositionY(), GetPositionZ() + (collisionHeight ? *collisionHeight : GetCollisionHeight()));
    G3D::Vector3 vObj(dest.GetPositionX(), dest.GetPositionY(), dest.GetPositionZ());
    G3D::Vector3 contactPoint = vThis + (vObj - vThis).directionOrZero() * std::min(dest.GetExactDist(this), GetCombatReach());
    return Position(contactPoint.x, contactPoint.y, contactPoint.z, GetAngle(contactPoint.x, contactPoint.y));
}
References Position::GetAngle(), GetCollisionHeight(), GetCombatReach(), Position::GetExactDist(), Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
Referenced by GetHitSpherePointFor(), IsWithinLOS(), IsWithinLOSInMap(), and PathGenerator::ShortenPathUntilDist().
GetInstanceId()
uint32 WorldObject::GetInstanceId () const inline
{ return m_InstanceId; }
References m_InstanceId.
Referenced by Group::_cancelHomebindIfInstance(), Player::_SaveCharacter(), FormationMgr::AddCreatureToGroup(), Map::AddObjectToRemoveList(), Map::AddObjectToSwitchList(), Creature::Create(), Group::Disband(), RandomMovementGenerator< T >::DoInitialize(), GameObject::FindStateSavedOnInstance(), Player::GetNextQuest(), GameObject::GetStateSavedOnInstance(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleInstanceLockResponse(), mmaps_commandscript::HandleMmapLoadedTilesCommand(), mmaps_commandscript::HandleMmapLocCommand(), npc_commandscript::HandleNpcInfoCommand(), Player::IsAtRecruitAFriendDistance(), Unit::Kill(), CreatureGroup::MemberEngagingTarget(), PathGenerator::PathGenerator(), Player::PrepareQuestMenu(), FormationMgr::RemoveCreatureFromGroup(), Vehicle::RemovePassenger(), GameObject::SaveInstanceData(), Corpse::SaveToDB(), Player::SetMover(), Player::Update(), and GameObject::UpdateInstanceData().
GetInstanceScript()
InstanceScript * WorldObject::GetInstanceScript () const
{
    Map* map = GetMap();
    return map->IsDungeon() ? map->ToInstanceMap()->GetInstanceScript() : nullptr;
}
References InstanceMap::GetInstanceScript(), GetMap(), Map::IsDungeon(), and Map::ToInstanceMap().
Referenced by CreatureAI::_EnterEvadeMode(), at_zulgurub_entrance_speech::_OnTrigger(), at_zulgurub_bridge_speech::_OnTrigger(), at_zulgurub_temple_speech::_OnTrigger(), at_zulgurub_bloodfire_pit_speech::_OnTrigger(), at_zulgurub_edge_of_madness_speech::_OnTrigger(), at_twin_emperors::_OnTrigger(), Pet::AddToWorld(), boss_aeonus::boss_aeonusAI::boss_aeonusAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::boss_algalon_the_observerAI(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::boss_ambassador_hellmawAI(), boss_anetheron::boss_anetheronAI::boss_anetheronAI(), boss_anubarak_trial::boss_anubarak_trialAI::boss_anubarak_trialAI(), boss_anubrekhan::boss_anubrekhanAI::boss_anubrekhanAI(), boss_archavon::boss_archavonAI::boss_archavonAI(), boss_archimonde::boss_archimondeAI::boss_archimondeAI(), boss_auriaya::boss_auriayaAI::boss_auriayaAI(), boss_azgalor::boss_azgalorAI::boss_azgalorAI(), boss_bigbadwolf::boss_bigbadwolfAI::boss_bigbadwolfAI(), boss_bjarngrim::boss_bjarngrimAI::boss_bjarngrimAI(), boss_black_knight::boss_black_knightAI::boss_black_knightAI(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::boss_blackheart_the_inciterAI(), boss_blindeye_the_seer::boss_blindeye_the_seerAI::boss_blindeye_the_seerAI(), boss_broggok::boss_broggokAI::boss_broggokAI(), boss_bronjahm::boss_bronjahmAI::boss_bronjahmAI(), boss_crone::boss_croneAI::boss_croneAI(), boss_cyanigosa::boss_cyanigosaAI::boss_cyanigosaAI(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::boss_dalronn_the_controllerAI(), boss_devourer_of_souls::boss_devourer_of_soulsAI::boss_devourer_of_soulsAI(), boss_doomrel::boss_doomrelAI::boss_doomrelAI(), boss_dorothee::boss_dorotheeAI::boss_dorotheeAI(), boss_drakos::boss_drakosAI::boss_drakosAI(), boss_eadric::boss_eadricAI::boss_eadricAI(), boss_emalon::boss_emalonAI::boss_emalonAI(), boss_eregos::boss_eregosAI::boss_eregosAI(), boss_erekem::boss_erekemAI::boss_erekemAI(), boss_faction_championsAI::boss_faction_championsAI(), boss_faerlina::boss_faerlinaAI::boss_faerlinaAI(), boss_falric::boss_falricAI::boss_falricAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::boss_felblood_kaelthasAI(), boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::boss_flame_leviathan_defense_turretAI(), boss_flame_leviathan::boss_flame_leviathanAI::boss_flame_leviathanAI(), boss_four_horsemen::boss_four_horsemenAI::boss_four_horsemenAI(), boss_freya_summons::boss_freya_summonsAI::boss_freya_summonsAI(), boss_freya::boss_freyaAI::boss_freyaAI(), boss_frostsworn_general::boss_frostsworn_generalAI::boss_frostsworn_generalAI(), boss_garfrost::boss_garfrostAI::boss_garfrostAI(), boss_gluth::boss_gluthAI::boss_gluthAI(), boss_gormok::boss_gormokAI::boss_gormokAI(), boss_gothik::boss_gothikAI::boss_gothikAI(), boss_grand_champion::boss_grand_championAI::boss_grand_championAI(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::boss_grandmaster_vorpilAI(), boss_grobbulus::boss_grobbulusAI::boss_grobbulusAI(), boss_halazzi::boss_halazziAI::boss_halazziAI(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::boss_harbinger_skyrissAI(), boss_heigan::boss_heiganAI::boss_heiganAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::boss_hex_lord_malacrassAI(), boss_hexlord_addAI::boss_hexlord_addAI(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::boss_high_inquisitor_whitemaneAI(), boss_hodir::boss_hodirAI::boss_hodirAI(), boss_icehowl::boss_icehowlAI::boss_icehowlAI(), boss_ichoron::boss_ichoronAI::boss_ichoronAI(), boss_ick::boss_ickAI::boss_ickAI(), boss_illidari_council_memberAI::boss_illidari_council_memberAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::boss_ingvar_the_plundererAI(), boss_ionar::boss_ionarAI::boss_ionarAI(), boss_janalai::boss_janalaiAI::boss_janalaiAI(), boss_jaraxxus::boss_jaraxxusAI::boss_jaraxxusAI(), boss_jormungarAI::boss_jormungarAI(), boss_julianne::boss_julianneAI::boss_julianneAI(), boss_kazrogal::boss_kazrogalAI::boss_kazrogalAI(), boss_keleseth::boss_kelesethAI::boss_kelesethAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::boss_kelidan_the_breakerAI(), boss_kelthuzad::boss_kelthuzadAI::boss_kelthuzadAI(), boss_kiggler_the_crazed::boss_kiggler_the_crazedAI::boss_kiggler_the_crazedAI(), boss_kiljaeden::boss_kiljaedenAI::boss_kiljaedenAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::boss_kirtonos_the_heraldAI(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::boss_kologarn_eyebeamAI(), boss_kologarn::boss_kologarnAI::boss_kologarnAI(), boss_koralon::boss_koralonAI::boss_koralonAI(), boss_krick::boss_krickAI::boss_krickAI(), boss_krosh_firehand::boss_krosh_firehandAI::boss_krosh_firehandAI(), boss_krystallus::boss_krystallusAI::boss_krystallusAI(), boss_lavanthor::boss_lavanthorAI::boss_lavanthorAI(), boss_loatheb::boss_loathebAI::boss_loathebAI(), boss_loken::boss_lokenAI::boss_lokenAI(), boss_maexxna::boss_maexxnaAI::boss_maexxnaAI(), boss_maiden_of_grief::boss_maiden_of_griefAI::boss_maiden_of_griefAI(), boss_malchezaar::boss_malchezaarAI::boss_malchezaarAI(), boss_malygos::boss_malygosAI::boss_malygosAI(), boss_marwyn::boss_marwynAI::boss_marwynAI(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::boss_mekgineer_steamriggerAI(), boss_mimiron::boss_mimironAI::boss_mimironAI(), boss_moragg::boss_moraggAI::boss_moraggAI(), boss_moroes::boss_moroesAI::boss_moroesAI(), boss_murmur::boss_murmurAI::boss_murmurAI(), boss_nalorakk::boss_nalorakkAI::boss_nalorakkAI(), boss_netherspite::boss_netherspiteAI::boss_netherspiteAI(), boss_nightbane::boss_nightbaneAI::boss_nightbaneAI(), boss_noth::boss_nothAI::boss_nothAI(), boss_olm_the_summoner::boss_olm_the_summonerAI::boss_olm_the_summonerAI(), boss_palehoof::boss_palehoofAI::boss_palehoofAI(), boss_paletress::boss_paletressAI::boss_paletressAI(), boss_patchwerk::boss_patchwerkAI::boss_patchwerkAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::boss_priestess_delrissaAI(), boss_priestess_lackey_commonAI::boss_priestess_lackey_commonAI(), boss_rage_winterchill::boss_rage_winterchillAI::boss_rage_winterchillAI(), boss_razorscale::boss_razorscaleAI::boss_razorscaleAI(), boss_razuvious::boss_razuviousAI::boss_razuviousAI(), boss_roar::boss_roarAI::boss_roarAI(), boss_romulo::boss_romuloAI::boss_romuloAI(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::boss_runemaster_molgeimAI(), boss_sapphiron::boss_sapphironAI::boss_sapphironAI(), boss_sathrovarr::boss_sathrovarrAI::boss_sathrovarrAI(), boss_selin_fireheart::boss_selin_fireheartAI::boss_selin_fireheartAI(), boss_sjonnir::boss_sjonnirAI::boss_sjonnirAI(), boss_skadi_grauf::boss_skadi_graufAI::boss_skadi_graufAI(), boss_skadi::boss_skadiAI::boss_skadiAI(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::boss_skarvald_the_constructorAI(), boss_steelbreaker::boss_steelbreakerAI::boss_steelbreakerAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::boss_stormcaller_brundirAI(), boss_strawman::boss_strawmanAI::boss_strawmanAI(), boss_svala::boss_svalaAI::boss_svalaAI(), boss_terestian_illhoof::boss_terestianAI::boss_terestianAI(), boss_thaddius_summon::boss_thaddius_summonAI::boss_thaddius_summonAI(), boss_thaddius::boss_thaddiusAI::boss_thaddiusAI(), boss_the_maker::boss_the_makerAI::boss_the_makerAI(), boss_hydromancer_thespia::boss_thespiaAI::boss_thespiaAI(), boss_thorim::boss_thorimAI::boss_thorimAI(), boss_tinhead::boss_tinheadAI::boss_tinheadAI(), boss_toravon::boss_toravonAI::boss_toravonAI(), boss_twin_valkyrAI::boss_twin_valkyrAI(), boss_tyrannus::boss_tyrannusAI::boss_tyrannusAI(), boss_urom::boss_uromAI::boss_uromAI(), boss_varos::boss_varosAI::boss_varosAI(), boss_vexallus::boss_vexallusAI::boss_vexallusAI(), boss_vezax::boss_vezaxAI::boss_vezaxAI(), boss_volkhan::boss_volkhanAI::boss_volkhanAI(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::boss_warlord_kalithreshAI(), boss_xevozz::boss_xevozzAI::boss_xevozzAI(), boss_xt002::boss_xt002AI::boss_xt002AI(), boss_ymiron::boss_ymironAI::boss_ymironAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::boss_yoggsaron_saraAI(), boss_yoggsaron::boss_yoggsaronAI::boss_yoggsaronAI(), boss_zuljin::boss_zuljinAI::boss_zuljinAI(), boss_zuramat::boss_zuramatAI::boss_zuramatAI(), brann_bronzebeard::brann_bronzebeardAI::brann_bronzebeardAI(), spell_serpentshrine_cavern_coilfang_water::spell_serpentshrine_cavern_coilfang_water_AuraScript::CalcPeriodic(), spell_igb_rocket_pack_useable::spell_igb_rocket_pack_useable_AuraScript::CheckAreaTarget(), Spell::CheckCast(), spell_putricide_mutation_init::spell_putricide_mutation_init_SpellScript::CheckRequirementInternal(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::DamageDealt(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::DamageTaken(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::DamageTaken(), boss_mal_ganis::boss_mal_ganisAI::DamageTaken(), boss_kologarn_arms::boss_kologarn_armsAI::DamageTaken(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DamageTaken(), boss_thorim_sif::boss_thorim_sifAI::DoAction(), npc_xt002_heart::npc_xt002_heartAI::DoAction(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction(), Spell::EffectSanctuary(), Spell::EffectSendEvent(), npc_crystalline_frayer::npc_crystalline_frayerAI::EnterCombat(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::EnterCombat(), boss_ignis::boss_ignisAI::EnterCombat(), boss_anzu::boss_anzuAI::EnterCombat(), boss_entropius::boss_entropiusAI::EnterEvadeMode(), npc_ghostly_priest::npc_ghostly_priestAI::EnterEvadeMode(), npc_phantom_mage::npc_phantom_mageAI::EnterEvadeMode(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::EnterEvadeMode(), npc_spectral_footman::npc_spectral_footmanAI::EnterEvadeMode(), npc_tortured_rifleman::npc_tortured_riflemanAI::EnterEvadeMode(), SendEncounterUnit::Execute(), UtherBatteredHiltEvent::Execute(), startFollow::Execute(), spell_igb_teleport_players_on_victory::spell_igb_teleport_players_on_victory_SpellScript::FilterTargets(), npc_jaina_proudmoore::GetAI(), npc_thrall::GetAI(), npc_tyrande_whisperwind::GetAI(), npc_shadowmoon_channeler::npc_shadowmoon_channelerAI::GetKelidan(), go_brazier_of_madness::GossipHello(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleDamage(), spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::HandleDummy(), spell_teron_gorefiend_shadow_of_death::spell_teron_gorefiend_shadow_of_death_AuraScript::HandleEffectRemove(), AuraEffect::HandleFeignDeath(), spell_hadronox_summon_periodic::spell_hadronox_summon_periodic_AuraScript::HandlePeriodic(), spell_serpentshrine_cavern_coilfang_water::spell_serpentshrine_cavern_coilfang_water_AuraScript::HandlePeriodic(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::HandleScript(), spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::HandleScript(), spell_auto_repair::spell_auto_repair_SpellScript::HandleScript(), spell_temple_of_atal_hakkar_awaken_the_soulflayer::spell_temple_of_atal_hakkar_awaken_the_soulflayer_SpellScript::HandleSendEvent(), spell_uldaman_boss_agro_archaedas::spell_uldaman_boss_agro_archaedas_SpellScript::HandleSendEvent(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), hyjal_trashAI::hyjal_trashAI(), hyjalAI::hyjalAI(), npc_toxic_slime::InitializeAI(), SmartAI::IsEscortInvokerInRange(), npc_living_inferno::npc_living_infernoAI::IsSummonedBy(), npc_kinetic_bomb::npc_kinetic_bombAI::IsSummonedBy(), npc_putricide_oozeAI::IsSummonedBy(), boss_kalec::boss_kalecAI::JustDied(), boss_entropius::boss_entropiusAI::JustDied(), boss_infinite_corruptor::boss_infinite_corruptorAI::JustDied(), boss_captain_skarloc::boss_captain_skarlocAI::JustDied(), boss_lieutenant_drake::boss_lieutenant_drakeAI::JustDied(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::JustDied(), boss_temporus::boss_temporusAI::JustDied(), npc_hor_raging_ghoul::npc_hor_raging_ghoulAI::JustDied(), npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI::JustDied(), npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI::JustDied(), npc_stinky_icc::npc_stinky_iccAI::JustDied(), npc_precious_icc::npc_precious_iccAI::JustDied(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::JustDied(), boss_naxxramas_misc::boss_naxxramas_miscAI::JustDied(), boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::JustDied(), boss_ignis::boss_ignisAI::JustDied(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::JustDied(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::JustDied(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::JustDied(), npc_xt002_heart::npc_xt002_heartAI::JustDied(), boss_talon_king_ikiss::boss_talon_king_ikissAI::JustDied(), boss_anzu::boss_anzuAI::JustDied(), boss_epoch_hunter::boss_epoch_hunterAI::JustDied(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::JustDied(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::JustDied(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::JustDied(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::JustDied(), npc_frost_tomb::npc_frost_tombAI::JustDied(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::JustSummoned(), npc_frozen_orb_stalker::npc_frozen_orb_stalkerAI::JustSummoned(), boss_captain_skarloc::boss_captain_skarlocAI::JustSummoned(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::JustSummoned(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::KilledUnit(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::KilledUnit(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::KilledUnit(), boss_razuvious_minion::boss_razuvious_minionAI::KilledUnit(), spell_igb_rocket_pack_useable::spell_igb_rocket_pack_useable_AuraScript::Load(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::Load(), spell_igb_teleport_players_on_victory::spell_igb_teleport_players_on_victory_SpellScript::Load(), spell_the_lich_king_quake::spell_the_lich_king_quake_SpellScript::Load(), spell_the_lich_king_harvest_soul::spell_the_lich_king_harvest_soul_AuraScript::Load(), spell_the_lich_king_restore_soul::spell_the_lich_king_restore_soul_SpellScript::Load(), spell_dreamwalker_nightmare_cloud::spell_dreamwalker_nightmare_cloud_AuraScript::Load(), npc_ouro_spawner::MoveInLineOfSight(), npc_announcer_toc5::npc_announcer_toc5AI::MovementInform(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::MovementInform(), npc_abomination::npc_abominationAI::npc_abominationAI(), npc_akama_illidan::npc_akama_illidanAI::npc_akama_illidanAI(), npc_akama_shade::npc_akamaAI::npc_akamaAI(), npc_ancient_wisp::npc_ancient_wispAI::npc_ancient_wispAI(), npc_argent_soldier::npc_argent_soldierAI::npc_argent_soldierAI(), npc_arthas::npc_arthasAI::npc_arthasAI(), npc_azure_saboteur::npc_azure_saboteurAI::npc_azure_saboteurAI(), npc_banshee::npc_bansheeAI::npc_bansheeAI(), npc_barnes::npc_barnesAI::npc_barnesAI(), npc_belnistrasz::npc_belnistraszAI::npc_belnistraszAI(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::npc_black_knight_ghoulAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::npc_blood_queen_lana_thelAI(), npc_buru_egg::npc_buru_egg(), npc_chained_spirit::npc_chained_spirit(), npc_creature_generator_akama::npc_creature_generator_akamaAI::npc_creature_generator_akamaAI(), npc_crypt_fiend::npc_crypt_fiendAI::npc_crypt_fiendAI(), npc_dirt_mound::npc_dirt_mound(), npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI::npc_dragonflayer_forge_masterAI(), npc_erekem_guard::npc_erekem_guardAI::npc_erekem_guardAI(), npc_fel_stalker::npc_fel_stalkerAI::npc_fel_stalkerAI(), npc_ferocious_rhino::npc_ferocious_rhinoAI::npc_ferocious_rhinoAI(), npc_forest_frog::npc_forest_frogAI::npc_forest_frogAI(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::npc_fos_corrupted_soul_fragmentAI(), npc_frenzied_worgen::npc_frenzied_worgenAI::npc_frenzied_worgenAI(), npc_frost_tomb::npc_frost_tombAI::npc_frost_tombAI(), npc_frost_wyrm::npc_frost_wyrmAI::npc_frost_wyrmAI(), npc_gargoyle::npc_gargoyleAI::npc_gargoyleAI(), npc_general_andorov::npc_general_andorov(), npc_ghoul::npc_ghoulAI::npc_ghoulAI(), npc_giant_infernal::npc_giant_infernalAI::npc_giant_infernalAI(), npc_grimstone::npc_grimstoneAI::npc_grimstoneAI(), npc_harrison_jones::npc_harrison_jonesAI::npc_harrison_jonesAI(), npc_healing_ward::npc_healing_ward(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::npc_high_overlord_saurfangAI(), npc_hive_zara_larva::npc_hive_zara_larva(), npc_hor_leader_second::npc_hor_leader_secondAI::npc_hor_leader_secondAI(), npc_hor_leader::npc_hor_leaderAI::npc_hor_leaderAI(), npc_hor_lich_king::npc_hor_lich_kingAI::npc_hor_lich_kingAI(), npc_hover_disk::npc_hover_diskAI::npc_hover_diskAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::npc_icc_gauntlet_controllerAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::npc_icc_putricades_trapAI(), npc_ichor_globule::npc_ichor_globuleAI::npc_ichor_globuleAI(), npc_image_of_medivh::npc_image_of_medivhAI::npc_image_of_medivhAI(), npc_janalai_hatcher::npc_janalai_hatcherAI::npc_janalai_hatcherAI(), npc_janalai_hatchling::npc_janalai_hatchlingAI::npc_janalai_hatchlingAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::npc_kalecgos_kjAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::npc_kiljaeden_controllerAI(), npc_kilrek::npc_kilrekAI::npc_kilrekAI(), npc_lesser_doomguard::npc_lesser_doomguardAI::npc_lesser_doomguardAI(), npc_madrigosa::npc_madrigosaAI::npc_madrigosaAI(), npc_massive_jormungar::npc_massive_jormungarAI::npc_massive_jormungarAI(), npc_medivh_bm::npc_medivh_bmAI::npc_medivh_bmAI(), npc_memory::npc_memoryAI::npc_memoryAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::npc_millhouse_manastormAI(), npc_mograine::npc_mograineAI::npc_mograineAI(), npc_molten_golem::npc_molten_golemAI::npc_molten_golemAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::npc_muradin_bronzebeard_iccAI(), npc_naga_distiller::npc_naga_distillerAI::npc_naga_distillerAI(), npc_necromancer::npc_necromancerAI::npc_necromancerAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::npc_nerubian_burrowerAI(), npc_nexus_lord::npc_nexus_lordAI::npc_nexus_lordAI(), npc_oculus_drake::npc_oculus_drakeAI::npc_oculus_drakeAI(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::npc_oculus_drakegiverAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::npc_pos_after_first_bossAI(), npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI::npc_pos_collapsing_icicleAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::npc_pos_deathwhisper_necrolyteAI(), npc_pos_icicle_trigger::npc_pos_icicle_triggerAI::npc_pos_icicle_triggerAI(), npc_pos_leader_second::npc_pos_leader_secondAI::npc_pos_leader_secondAI(), npc_pos_leader::npc_pos_leaderAI::npc_pos_leaderAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::npc_pos_martin_or_gorkun_secondAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::npc_pos_tyrannus_eventsAI(), npc_power_spark::npc_power_sparkAI::npc_power_sparkAI(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::npc_ravenous_furbolgAI(), npc_risen_guardian::npc_risen_guardianAI::npc_risen_guardianAI(), npc_rocknot::npc_rocknotAI::npc_rocknotAI(), npc_scholomance_occultist::npc_scholomance_occultistAI::npc_scholomance_occultistAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::npc_scion_of_eternityAI(), npc_sergeant_bly::npc_sergeant_blyAI::npc_sergeant_blyAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::npc_sindragosa_trashAI(), npc_snobold_vassal::npc_snobold_vassalAI::npc_snobold_vassalAI(), npc_taretha::npc_tarethaAI::npc_tarethaAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::npc_thrall_old_hillsbradAI(), npc_time_rift::npc_time_riftAI::npc_time_riftAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::npc_toc5_grand_champion_minionAI(), npc_towering_infernal::npc_towering_infernalAI::npc_towering_infernalAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::npc_ulduar_aerial_command_unitAI(), npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI::npc_ulduar_expedition_commanderAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::npc_ulduar_expedition_engineerAI(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::npc_ulduar_flash_freezeAI(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::npc_ulduar_harpoonfirestateAI(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::npc_ulduar_hodir_druidAI(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::npc_ulduar_hodir_mageAI(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::npc_ulduar_hodir_priestAI(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::npc_ulduar_hodir_shamanAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::npc_ulduar_leviathan_mkiiAI(), npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI::npc_ulduar_magnetic_coreAI(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::npc_ulduar_saronite_animusAI(), npc_ulduar_saronite_vapors::npc_ulduar_saronite_vaporsAI::npc_ulduar_saronite_vaporsAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::npc_ulduar_vx001AI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::npc_vh_teleportation_portalAI(), npc_vh_void_sentry::npc_vh_void_sentryAI::npc_vh_void_sentryAI(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::npc_vrykul_skeletonAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::npc_weegli_blastfuseAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::npc_zealot_lorkhanAI(), npc_zealot_zath::npc_zealot_zathAI::npc_zealot_zathAI(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::OnCast(), achievement_cant_do_that_while_stunned::OnCheck(), achievement_auriaya_crazy_cat_lady::OnCheck(), achievement_auriaya_nine_lives::OnCheck(), achievement_kologarn_looks_could_kill::OnCheck(), achievement_kologarn_rubble_and_roll::OnCheck(), achievement_kologarn_with_open_arms::OnCheck(), achievement_xt002_nerf_engineering::OnCheck(), achievement_xt002_nerf_gravity_bombs::OnCheck(), achievement_flame_leviathan_unbroken::OnCheck(), achievement_thorim_stand_in_the_lightning::OnCheck(), achievement_thorim_lose_your_illusion::OnCheck(), achievement_yogg_saron_darkness::OnCheck(), achievement_yogg_saron_he_waits_dreaming::OnCheck(), go_shadowforge_brazier::OnGossipHello(), go_gong_of_bethekk::OnGossipHello(), go_call_tram::OnGossipHello(), go_palehoof_sphere::OnGossipHello(), go_vh_activation_crystal::OnGossipHello(), go_main_chambers_access_panel::OnGossipHello(), go_broggok_lever::OnGossipHello(), npc_barnes::OnGossipHello(), npc_arthas::OnGossipHello(), npc_cos_chromie_middle::OnGossipHello(), npc_thrall_old_hillsbrad::OnGossipHello(), npc_announcer_toc5::OnGossipHello(), npc_announcer_toc10::OnGossipHello(), npc_hor_leader::OnGossipHello(), npc_high_overlord_saurfang_icc::OnGossipHello(), npc_muradin_bronzebeard_icc::OnGossipHello(), npc_alchemist_adrianna::OnGossipHello(), npc_oculus_drakegiver::OnGossipHello(), brann_bronzebeard::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipHello(), npc_vh_sinclari::OnGossipHello(), go_orb_of_domination::OnGossipHello(), go_blackened_urn::OnGossipHello(), icecrown_citadel_teleport::OnGossipHello(), go_ulduar_do_not_push_this_button::OnGossipHello(), go_strange_pool::OnGossipHello(), go_ulduar_pure_saronite_deposit::OnGossipHello(), go_prince_taldaram_sphere::OnGossipHello(), go_harpoon_canon::OnGossipHello(), go_the_focusing_iris::OnGossipHello(), go_ulduar_working_harpoon::OnGossipHello(), boss_gloomrel::OnGossipSelect(), boss_doomrel::OnGossipSelect(), npc_zulaman_hostage::OnGossipSelect(), npc_high_overlord_saurfang_icc::OnGossipSelect(), npc_muradin_bronzebeard_icc::OnGossipSelect(), npc_ulduar_keeper::OnGossipSelect(), npc_announcer_toc5::OnGossipSelect(), npc_announcer_toc10::OnGossipSelect(), npc_hor_leader::OnGossipSelect(), npc_ulduar_expedition_commander::OnGossipSelect(), npc_vh_sinclari::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), npc_cos_chromie_middle::OnGossipSelect(), npc_thrall_old_hillsbrad::OnGossipSelect(), npc_hor_leader_second::OnGossipSelect(), npc_icc_buff_switcher::OnGossipSelect(), go_father_flame::OnLootStateChanged(), npc_cos_chromie_start::OnQuestAccept(), npc_cos_chromie_middle::OnQuestAccept(), npc_rocknot::OnQuestReward(), spell_blood_queen_frenzied_bloodthirst::spell_blood_queen_frenzied_bloodthirst_AuraScript::OnRemove(), OnlyOnceAreaTriggerScript::OnTrigger(), at_trigger_the_beast_movement::OnTrigger(), at_the_beast_room::OnTrigger(), AreaTrigger_at_sunwell_madrigosa::OnTrigger(), AreaTrigger_at_sunwell_eredar_twins::OnTrigger(), at_cthun_stomach_exit::OnTrigger(), at_cthun_center::OnTrigger(), at_baltharus_plateau::OnTrigger(), at_hor_battered_hilt_start::OnTrigger(), at_hor_battered_hilt_throw::OnTrigger(), at_lady_deathwhisper_entrance::OnTrigger(), at_sindragosa_lair::OnTrigger(), at_icc_saurfang_portal::OnTrigger(), at_icc_shutdown_traps::OnTrigger(), at_icc_start_blood_quickening::OnTrigger(), at_icc_start_frostwing_gauntlet::OnTrigger(), at_icc_gauntlet_event::OnTrigger(), at_icc_putricide_trap::OnTrigger(), at_frozen_throne_teleport::OnTrigger(), at_thaddius_entrance::OnTrigger(), at_naxxramas_hub_portal::OnTrigger(), at_shattered_halls_execution::OnTrigger(), at_ring_of_law::OnTrigger(), at_dragonspire_hall::OnTrigger(), at_blackrock_stadium::OnTrigger(), at_malfurion_stormrage::OnTrigger(), at_battleguard_sartura::OnTrigger(), at_hor_shadow_throne::OnTrigger(), at_tyrannus_event_starter::OnTrigger(), ValithriaDespawner::operator()(), prince_axes::prince_axesAI::prince_axesAI(), SmartScript::ProcessAction(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::RelocateDest(), boss_infinite_corruptor::boss_infinite_corruptorAI::Reset(), go_sand_trap::Reset(), npc_xerestrasza::npc_xerestraszaAI::Reset(), npc_announcer_toc5::npc_announcer_toc5AI::Reset(), boss_ignis::boss_ignisAI::Reset(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::Reset(), npc_xt002_boombot::npc_xt002_boombotAI::Reset(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Reset(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Reset(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Reset(), boss_anzu::boss_anzuAI::Reset(), npc_steamrigger_mechanic::npc_steamrigger_mechanicAI::Reset(), OnlyOnceAreaTriggerScript::ResetAreaTriggerDone(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::SelectTarget(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::SelectTransport(), Player::SendInitWorldStates(), Player::SendLoot(), Unit::setDeathState(), boss_victor_nefarius::boss_victor_nefariusAI::sGossipSelect(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::SpellHit(), npc_living_constellation::npc_living_constellationAI::SpellHit(), npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI::SpellHitTarget(), npc_ulduar_rocket_strike_trigger::npc_ulduar_rocket_strike_triggerAI::SpellHitTarget(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::SpellHitTarget(), TriggerBurningPitch(), boss_kalec::boss_kalecAI::UpdateAI(), boss_sathrovarr::boss_sathrovarrAI::UpdateAI(), npc_bone_spike::npc_bone_spikeAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::UpdateAI(), npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), boss_yoggsaron_keeper::boss_yoggsaron_keeperAI::UpdateAI(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::UpdateAI(), npc_xt002_boombot::npc_xt002_boombotAI::UpdateAI(), Player::UpdateArea(), Map::UpdateEncounterState(), violet_hold_trashAI::violet_hold_trashAI(), and npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::WaypointReached().
getLevelForTarget()
virtual uint8 WorldObject::getLevelForTarget (WorldObject const *) const inline virtual
Reimplemented in Unit, Creature, and GameObject.
{ return 1; }
Referenced by CanDetectStealthOf().
GetLiquidData()
LiquidData const & WorldObject::GetLiquidData () const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    return _liquidData;
}
References _liquidData, _updatePositionData, and UpdatePositionData().
Referenced by Unit::isInAccessiblePlaceFor(), Unit::IsInWater(), Unit::IsUnderWater(), Unit::ProcessTerrainStatusUpdate(), Player::ProcessTerrainStatusUpdate(), and Creature::UpdateMovementFlags().
GetMap()
Map * WorldObject::GetMap () const inline
{ ASSERT(m_currMap); return m_currMap; }
References ASSERT, and m_currMap.
Referenced by Map::_FindGameObject(), at_zulgurub_entrance_speech::_OnTrigger(), at_zulgurub_bridge_speech::_OnTrigger(), at_zulgurub_temple_speech::_OnTrigger(), at_zulgurub_bloodfire_pit_speech::_OnTrigger(), at_zulgurub_edge_of_madness_speech::_OnTrigger(), Battleground::_ProcessResurrect(), RandomMovementGenerator< T >::_setRandomLocation(), boss_sjonnir::boss_sjonnirAI::ActivatePipe(), Map::AddPlayerToMap(), AddToObjectUpdate(), GameObject::AddToSkillupList(), Corpse::AddToWorld(), Creature::AddToWorld(), DynamicObject::AddToWorld(), GameObject::AddToWorld(), AddToWorld(), Pet::AddToWorld(), boss_hadronox::boss_hadronoxAI::AnyPlayerValid(), npc_ritual_channeler::npc_ritual_channelerAI::AttackStart(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::AttackStart(), boss_drekthar::boss_drektharAI::AttackStart(), boss_vanndar::boss_vanndarAI::AttackStart(), CinematicMgr::BeginCinematic(), boss_flame_leviathan::boss_flame_leviathanAI::BindPlayers(), DynamicObject::BindToCaster(), Player::BuildPlayerRepop(), PathGenerator::BuildPolyPath(), MotionTransport::BuildUpdate(), StaticTransport::BuildUpdate(), spell_svala_ritual_strike::spell_svala_ritual_strike_AuraScript::CalculateAmount(), Creature::CanCreatureAttack(), Unit::CanHaveThreatList(), CanNeverSee(), Creature::CanPeriodicallyCallForAssistance(), Player::CanRollForItemInLFG(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), Spell::CheckCast(), Map::CheckCollisionAndGetValidCoords(), Player::CheckDuelDistance(), Spell::CheckEffectTarget(), spell_sha_fire_nova::CheckFireTotem(), boss_gothik::boss_gothikAI::CheckGroupSplitted(), Player::CheckInstanceLoginValid(), boss_volazj::CheckPhaseMinions(), boss_skadi_grauf::boss_skadi_graufAI::CheckPlayers(), BattlegroundRV::CheckPositionForUnit(), Spell::CheckSpellFocus(), Creature::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), Player::CreateCorpse(), DynamicObject::CreateDynamicObject(), Creature::CreateFromProto(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), Player::CreatePet(), TransportMgr::CreateTransport(), boss_eregos::boss_eregosAI::DamageTaken(), boss_eadric::boss_eadricAI::DamageTaken(), boss_ick::boss_ickAI::DamageTaken(), boss_freya::boss_freyaAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), MotionTransport::DelayedTeleportTransport(), Creature::DeleteFromDB(), GameObject::DeleteFromDB(), boss_twin_valkyrAI::DoAction(), boss_ayamiss::DoAction(), npc_thrall_warchief::npc_thrall_warchiefAI::DoAction(), npc_orb_carrier::npc_orb_carrierAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), npc_arthas::npc_arthasAI::DoAction(), npc_molten_golem::npc_molten_golemAI::DoAction(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DoAction(), Spell::DoAllEffectOnTarget(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoCheckHeraldOfTheTitans(), MotionTransport::DoEventIfAny(), FlightPathMovementGenerator::DoEventIfAny(), WorldSession::DoLootRelease(), ScriptedAI::DoPlayMusic(), ScriptedAI::DoTeleportAll(), boss_icehowl::boss_icehowlAI::DoTrampleIfValid(), CreatureAI::DoZoneInCombat(), Player::DuelComplete(), DynObjAura::DynObjAura(), Spell::EffectAddFarsight(), Spell::EffectCreateTamedPet(), Spell::EffectDestroyAllTotems(), Spell::EffectDuel(), Spell::EffectDummy(), Spell::EffectPersistentAA(), Spell::EffectScriptEffect(), Spell::EffectSendEvent(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTameCreature(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat(), boss_loken::boss_lokenAI::EnterCombat(), boss_krystallus::boss_krystallusAI::EnterCombat(), boss_sjonnir::boss_sjonnirAI::EnterCombat(), boss_thaddius_summon::boss_thaddius_summonAI::EnterCombat(), boss_ossirian::EnterCombat(), boss_anubrekhan::boss_anubrekhanAI::EnterCombat(), boss_faerlina::boss_faerlinaAI::EnterCombat(), boss_four_horsemen::boss_four_horsemenAI::EnterCombat(), boss_gothik::boss_gothikAI::EnterCombat(), boss_heigan::boss_heiganAI::EnterCombat(), boss_kelthuzad::boss_kelthuzadAI::EnterCombat(), boss_loatheb::boss_loathebAI::EnterCombat(), boss_maexxna::boss_maexxnaAI::EnterCombat(), boss_noth::boss_nothAI::EnterCombat(), boss_sapphiron::boss_sapphironAI::EnterCombatSelfFunction(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::EnterEvadeMode(), boss_drekthar::boss_drektharAI::EnterEvadeMode(), boss_vanndar::boss_vanndarAI::EnterEvadeMode(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterEvadeMode(), boss_sindragosa::boss_sindragosaAI::EnterEvadeMode(), boss_malygos::boss_malygosAI::EnterEvadeMode(), BattleExperienceEvent::Execute(), SmartScript::FillScript(), SmartScript::FindCreatureNear(), SmartScript::FindGameObjectNear(), Acore::XP::Gain(), boss_thorim::boss_thorimAI::GetArenaPlayer(), Player::GetCorpse(), ObjectAccessor::GetCorpse(), ObjectAccessor::GetCreature(), ChatHandler::GetCreatureFromPlayerMapByDbGuid(), GetCreaturesWithEntryInRange(), ObjectAccessor::GetDynamicObject(), GetFloorZ(), ObjectAccessor::GetGameObject(), Player::GetGameObjectIfCanInteractWith(), GetGridActivationRange(), GetInstanceScript(), GetMapHeight(), GetMapWaterOrGroundLevel(), Unit::GetMeleeAttackPoint(), PathGenerator::GetNavTerrain(), Player::GetNextQuest(), ChatHandler::GetObjectFromPlayerMapByDbGuid(), ObjectAccessor::GetPet(), ObjectAccessor::GetPlayer(), GetSightRange(), npc_ranshalla::npc_ranshallaAI::GetSpeakerByEntry(), SpellMgr::GetSpellIdForDifficulty(), ObjectAccessor::GetTransport(), GetVisibilityRange(), misc_commandscript::HandleAppearCommand(), WorldSession::HandleAreaSpiritHealerQueryOpcode(), WorldSession::HandleAreaSpiritHealerQueueOpcode(), WorldSession::HandleAreaTriggerOpcode(), AuraEffect::HandleAuraDummy(), Unit::HandleAuraProc(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleBattlemasterHelloOpcode(), WorldSession::HandleBattlemasterJoinArena(), spell_four_horsemen_consumption::HandleDamageCalc(), debug_commandscript::HandleDebugSpawnVehicleCommand(), OutdoorPvPSI::HandleDropFlag(), spell_item_nitro_boots::HandleDummy(), spell_sha_fire_nova::HandleDummy(), spell_teron_gorefiend_shadowy_construct::spell_teron_gorefiend_shadowy_construct_AuraScript::HandleEffectApply(), AuraEffect::HandleFeignDeath(), gobject_commandscript::HandleGameObjectAddCommand(), WorldSession::HandleGameobjectReportUse(), WorldSession::HandleGossipSelectOptionOpcode(), misc_commandscript::HandleGroupSummonCommand(), instance_commandscript::HandleInstanceSaveDataCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleLootMoneyOpcode(), AuraEffect::HandleModInvisibility(), AuraEffect::HandleModPossessPet(), AuraEffect::HandleModStealth(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_AuraScript::HandleOnEffectApply(), WorldSession::HandlePetAction(), WorldSession::HandlePetActionHelper(), AuraEffect::HandlePhase(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), AuraEffect::HandlePreventResurrection(), spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript::HandleScript(), spell_archavon_rock_shards::spell_archavon_rock_shards_SpellScript::HandleScript(), spell_prince_taldaram_conjure_flame_sphere::HandleScript(), WorldSession::HandleSetDungeonDifficultyOpcode(), WorldSession::HandleSetRaidDifficultyOpcode(), misc_commandscript::HandleSkirmishCommand(), spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::HandleSummon(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript::HandleSummon(), misc_commandscript::HandleSummonCommand(), WorldSession::HandleTotemDestroyed(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), Player::HasQuestForGO(), Player::HasQuestForItem(), hyjalAI::HideNearPos(), boss_ichoron::boss_ichoronAI::IchoronDoCastToAllHostilePlayers(), Creature::InitEntry(), TempSummon::InitStats(), Player::inRandomLfgDungeon(), InstanceHasScript(), boss_halion::boss_halionAI::IsAnyPlayerValid(), Player::IsAtGroupRewardDistance(), Unit::isAttackingPlayer(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::IsHeroic(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsHeroic(), Unit::isInAccessiblePlaceFor(), PathGenerator::IsSwimmableSegment(), IsVampire(), IsWithinLOS(), IsWithinLOSInMap(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_apothecary_hummel::boss_apothecary_hummelAI::JustDied(), npc_coren_direbrew::JustDied(), boss_headless_horseman::JustDied(), boss_azuregos::boss_azuregosAI::JustDied(), npc_frost_wyrm::npc_frost_wyrmAI::JustDied(), boss_rajaxx::JustDied(), boss_skeram::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), boss_sjonnir::boss_sjonnirAI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::JustDied(), npc_gargoyle::npc_gargoyleAI::JustDied(), boss_kurinnaxx::JustDied(), boss_faerlina::boss_faerlinaAI::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), boss_gothik::boss_gothikAI::JustDied(), boss_kelthuzad::boss_kelthuzadAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_thaddius::boss_thaddiusAI::JustDied(), boss_alar::boss_alarAI::JustDied(), npc_tirion_fordring_tft::npc_tirion_fordringAI::JustReachedHome(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), Unit::Kill(), Player::KilledMonsterCredit(), Player::KilledPlayerCredit(), spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Land(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::LapseAction(), spell_the_lich_king_vile_spirits::spell_the_lich_king_vile_spirits_AuraScript::Load(), Creature::LoadCreatureFromDB(), GameObject::LoadGameObjectFromDB(), Pet::LoadPetFromDB(), MotionTransport::LoadStaticPassengers(), WorldSession::LogoutPlayer(), AchievementCriteriaData::Meets(), MotionMaster::MoveBackwards(), MotionMaster::MoveFall(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), npc_tirion_fordring_tft::npc_tirion_fordringAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), boss_malygos::boss_malygosAI::MovementInform(), boss_the_lich_king::boss_the_lich_kingAI::MovementInform(), MovePositionToFirstCollision(), npc_image_of_medivh::npc_image_of_medivhAI::NextStep(), npc_akama_illidan::npc_akama_illidanAI::npc_akama_illidanAI(), npc_frost_sphere::npc_frost_sphereAI::npc_frost_sphereAI(), WaypointMovementGenerator< Creature >::OnArrived(), achievement_once_bitten_twice_shy::OnCheck(), npc_essence_of_twin::OnGossipHello(), go_violet_hold_gate_lever::OnGossipHello(), lfg::LFGPlayerScript::OnMapChanged(), spell_illidan_tear_of_azzinoth_summon_channel::spell_illidan_tear_of_azzinoth_summon_channel_AuraScript::OnPeriodic(), at_ancient_leaf::OnTrigger(), at_sindragosa_lair::OnTrigger(), at_icc_saurfang_portal::OnTrigger(), AreaTrigger_at_celestial_planetarium_enterance::OnTrigger(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::OpenDoors(), MysticBuffetTargetFilter::operator()(), Unit::PetSpellFail(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript::Phase(), spell_valkyr_touch::spell_valkyr_touchAuraScript::PrepareAuraScript(), Player::PrepareQuestMenu(), SmartScript::ProcessAction(), GameObject::Refresh(), Vehicle::RelocatePassengers(), Player::RemovedInsignia(), RemoveFromObjectUpdate(), Corpse::RemoveFromWorld(), Creature::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), Pet::RemoveFromWorld(), boss_krystallus::boss_krystallusAI::RemoveStonedEffect(), boss_sartharion_dragonAI::RemoveTwilightPortal(), Player::RepopAtGraveyard(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_azuregos::boss_azuregosAI::Reset(), boss_ossirian::Reset(), npc_tirion_fordring_tft::npc_tirion_fordringAI::Reset(), npc_raging_spirit::npc_raging_spiritAI::Reset(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset(), boss_anubrekhan::boss_anubrekhanAI::Reset(), boss_faerlina::boss_faerlinaAI::Reset(), boss_four_horsemen::boss_four_horsemenAI::Reset(), boss_gothik::boss_gothikAI::Reset(), boss_heigan::boss_heiganAI::Reset(), boss_kelthuzad::boss_kelthuzadAI::Reset(), boss_loatheb::boss_loathebAI::Reset(), boss_maexxna::boss_maexxnaAI::Reset(), boss_noth::boss_nothAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), Player::ResetMap(), boss_nalorakk::boss_nalorakkAI::ResetMobs(), boss_volazj::ResetPlayersPhaseMask(), GameObject::Respawn(), Creature::Respawn(), hyjalAI::RespawnNearPos(), Player::RewardQuest(), Player::RewardReputation(), Creature::SaveRespawnTime(), GameObject::SaveRespawnTime(), ScriptedAI::ScriptedAI(), Map::ScriptsProcess(), Spell::SearchTargets(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::SelectCorruptionTarget(), Spell::SelectImplicitCasterDestTargets(), boss_gluth::boss_gluthAI::SelectPlayerInRoom(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT(), spell_gen_rallying_cry_of_the_dragonslayer::SelectTarget(), spell_gen_adals_song_of_battle::SelectTarget(), ScriptedAI::SelectTargetFromPlayerList(), npc_minigob_manabonk::npc_minigob_manabonkAI::SelectTargetInDalaran(), boss_nalorakk::boss_nalorakkAI::SendAttacker(), CreatureTextMgr::SendChatPacket(), Player::SendInitialPacketsAfterAddToMap(), Player::SendInitialPacketsBeforeAddToMap(), Player::SendLoot(), CreatureTextMgr::SendNonChatPacket(), SendPacketToPlayers(), Player::SendQuestGiverStatusMultiple(), Acore::VisibleNotifier::SendToSelf(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SendUpdateWorldState(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::SetData(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SetData(), Creature::setDeathState(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), GameObject::SetDestructibleState(), Player::SetEntryPoint(), npc_gunship::npc_gunshipAI::SetGUID(), Creature::SetLootRecipient(), Unit::SetPhaseMask(), Creature::SetPosition(), GameObject::SetPosition(), boss_akilzon::boss_akilzonAI::SetWeather(), SetWorldObject(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), PathGenerator::ShortenPathUntilDist(), Player::SpawnCorpseBones(), boss_skadi_grauf::boss_skadi_graufAI::SpawnFlameTriggers(), boss_hodir::boss_hodirAI::SpawnHelpers(), boss_jaraxxus::boss_jaraxxusAI::SpellHit(), boss_the_lich_king::boss_the_lich_kingAI::SpellHitTarget(), boss_skadi_grauf::boss_skadi_graufAI::SpellHitTarget(), boss_ionar::boss_ionarAI::Split(), Player::StoreRaidMapDifficulty(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), npc_varian_wrynn::npc_varian_wrynnAI::SummonedCreatureDies(), npc_thrall_bfu::npc_thrall_bfuAI::SummonedCreatureDies(), SummonGameObject(), Spell::SummonGuardian(), Player::SummonPet(), boss_rend_blackhand::boss_rend_blackhandAI::SummonWave(), brann_bronzebeard::brann_bronzebeardAI::SwitchHeadVisaul(), lfg::LFGMgr::TeleportPlayer(), Player::TeleportTo(), MotionTransport::TeleportTransport(), Vehicle::TeleportVehicle(), Unit::UnsummonAllTotems(), Pet::Update(), MotionTransport::Update(), DynamicObject::Update(), GameObject::Update(), Creature::Update(), Player::Update(), AchievementMgr::UpdateAchievementCriteria(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_nefarian::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), npc_barnes::npc_barnesAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI(), npc_singularity::npc_singularityAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), npc_forest_frog::npc_forest_frogAI::UpdateAI(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_cthun::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_addAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::UpdateAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::UpdateAI(), boss_heigan::boss_heiganAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::UpdateAI(), npc_alexstrasza::npc_alexstraszaAI::UpdateAI(), boss_keristrasza::boss_keristraszaAI::UpdateAI(), npc_stormforged_lieutenant::npc_stormforged_lieutenantAI::UpdateAI(), boss_ionar::boss_ionarAI::UpdateAI(), boss_loken::boss_lokenAI::UpdateAI(), boss_volkhan::boss_volkhanAI::UpdateAI(), npc_molten_golem::npc_molten_golemAI::UpdateAI(), npc_hol_monument::npc_hol_monumentAI::UpdateAI(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_lifebinder::boss_freya_lifebinderAI::UpdateAI(), boss_freya_nature_bomb::boss_freya_nature_bombAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_preparations_for_war_vehicle::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::UpdateAI(), npc_pet_gen_plump_turkey::UpdateAI(), npc_demonic_vapor::npc_demonic_vaporAI::UpdateAI(), UpdateAllowedPositionZ(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), GameObject::UpdateModel(), GameObject::UpdateModelPosition(), StaticTransport::UpdatePassengerPositions(), MotionTransport::UpdatePassengerPositions(), boss_netherspite::boss_netherspiteAI::UpdatePortals(), Unit::UpdatePosition(), MotionTransport::UpdatePosition(), StaticTransport::UpdatePosition(), UpdatePositionData(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateRunes(), Player::UpdateTriggerVisibility(), GameObject::Use(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), Cell::VisitWorldObjects(), npc_ranshalla::npc_ranshallaAI::WaypointReached(), npc_grimstone::npc_grimstoneAI::WaypointReached(), npc_thrall_bfu::npc_thrall_bfuAI::WaypointReached(), and npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached().
GetMapHeight()
float WorldObject::GetMapHeight (float x, float y, float z, bool vmap = true, float distanceToSearch = 50.0f) const
{
    if (z != MAX_HEIGHT)
        z += std::max(GetCollisionHeight(), Z_OFFSET_FIND_HEIGHT);
    return GetMap()->GetHeight(GetPhaseMask(), x, y, z, vmap, distanceToSearch);
}
References GetCollisionHeight(), Map::GetHeight(), GetMap(), GetPhaseMask(), MAX_HEIGHT, and Z_OFFSET_FIND_HEIGHT.
Referenced by Unit::_ExitVehicle(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), MotionMaster::MoveFall(), MovePosition(), IgbArtilleryCheck::operator()(), npc_kinetic_bomb::npc_kinetic_bombAI::Reset(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::Reset(), Spell::SelectImplicitCasterDestTargets(), spell_azjol_nerub_impale_summon::SetDest(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), boss_freya::boss_freyaAI::SpawnWave(), boss_felmyst::boss_felmystAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), UpdateAllowedPositionZ(), and UpdateGroundPositionZ().
GetMapWaterOrGroundLevel()
float WorldObject::GetMapWaterOrGroundLevel (float x, float y, float z, float * ground = nullptr) const
{
    return GetMap()->GetWaterOrGroundLevel(GetPhaseMask(), x, y, z, ground,
        isType(TYPEMASK_UNIT) ? !static_cast<Unit const*>(this)->HasAuraType(SPELL_AURA_WATER_WALK) : false,
        std::max(GetCollisionHeight(),  Z_OFFSET_FIND_HEIGHT));
}
References GetCollisionHeight(), GetMap(), GetPhaseMask(), Map::GetWaterOrGroundLevel(), Object::isType(), SPELL_AURA_WATER_WALK, TYPEMASK_UNIT, and Z_OFFSET_FIND_HEIGHT.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), and UpdateAllowedPositionZ().
GetMinHeightInWater()
float WorldObject::GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
Returns
float
{
    // have a fun with Archimedes' formula
    auto height = GetCollisionHeight();
    auto width = GetCollisionWidth();
    auto weight = getWeight(height, width, 1040); // avg human specific weight
    auto heightOutOfWater = getOutOfWater(width, weight, 10202) * 4.0f; // avg human density
    auto heightInWater = height - heightOutOfWater;
    return (height > heightInWater ? heightInWater : (height - (height / 3)));
}
References GetCollisionHeight(), GetCollisionWidth(), getOutOfWater(), and getWeight().
Referenced by Map::HasEnoughWater(), and UpdateAllowedPositionZ().
GetName()
std::string const & WorldObject::GetName () const inline
{ return m_name; }
References m_name.
Referenced by Player::_LoadHomeBind(), Player::_LoadInventory(), Player::_LoadItem(), Player::_LoadMailedItem(), Player::_LoadQuestStatus(), Player::_SaveCharacter(), Player::_SaveInventory(), Guild::_SendBankList(), Group::AddLeaderInvite(), Guild::AddMember(), ArenaTeam::AddMember(), Group::AddMember(), Vehicle::AddPassenger(), Battleground::AddPlayer(), InstanceMap::AddPlayerToMap(), Group::BroadcastGroupUpdate(), WorldSession::BuildPartyMemberStatsChangedPacket(), Player::BuildPlayerRepop(), Player::BuyItemFromVendorSlot(), Player::CanBankItem(), InstanceMap::CannotEnter(), WorldSession::CanOpenMailBox(), Player::CastItemCombatSpell(), Group::ChangeLeader(), Player::CheckAreaExploreAndOutdoor(), Corpse::Create(), Group::Create(), Guild::Create(), TransportMgr::CreateTransport(), FlightPathMovementGenerator::DoEventIfAny(), Player::DuelComplete(), Spell::EffectScriptEffect(), Player::EnvironmentalDamage(), ChatHandler::extractPlayerTarget(), Pet::FillPetInfo(), GetDebugInfo(), Unit::GetFactionTemplateEntry(), Player::GetGameObjectIfCanInteractWith(), Creature::GetNameForLocaleIdx(), GameObject::GetNameForLocaleIdx(), ChatHandler::GetNameLink(), WorldSession::GetPlayerInfo(), GetPlayerInfo(), Player::GetPlayerName(), WorldSession::GetPlayerName(), ReputationMgr::GetReputation(), GmTicket::GmTicket(), WorldSession::HandleAcceptTradeOpcode(), account_commandscript::HandleAccountCreateCommand(), spell_rog_deadly_poison::HandleAfterHit(), WorldSession::HandleAreaTriggerOpcode(), WorldSession::HandleArenaTeamAcceptOpcode(), WorldSession::HandleArenaTeamInviteOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamLeaveOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleBattlefieldListOpcode(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBattlemasterJoinArena(), debug_commandscript::HandleDebugGetLootRecipientCommand(), debug_commandscript::HandleDebugHostileRefListCommand(), debug_commandscript::HandleDebugLoSCommand(), debug_commandscript::HandleDebugSendOpcodeCommand(), debug_commandscript::HandleDebugThreatListCommand(), deserter_commandscript::HandleDeserterAdd(), WorldSession::HandleDuelAcceptedOpcode(), WorldSession::HandleFarSightOpcode(), WorldSession::HandleForceSpeedChangeAck(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), WorldSession::HandleGrantLevel(), WorldSession::HandleGroupDeclineOpcode(), WorldSession::HandleGroupInviteOpcode(), group_commandscript::HandleGroupJoinCommand(), WorldSession::HandleInstanceLockResponse(), inventory_commandscript::HandleInventoryCountCommand(), Guild::HandleInviteMember(), Guild::HandleLeaveMember(), lookup_commandscript::HandleLookupTitleCommand(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleMailTakeItem(), Guild::HandleMemberDepositMoney(), Guild::HandleMemberLogout(), Guild::HandleMemberWithdrawMoney(), WorldSession::HandleMessagechatOpcode(), mmaps_commandscript::HandleMmapPathCommand(), misc_commandscript::HandleMovegensCommand(), npc_commandscript::HandleNpcFollowCommand(), npc_commandscript::HandleNpcSetDataCommand(), npc_commandscript::HandleNpcUnFollowCommand(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionSignOpcode(), OutdoorPvP::HandlePlayerLeaveZone(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverCompleteQuest(), Guild::HandleRemoveMember(), WorldSession::HandleReportPvPAFK(), WorldSession::HandleRequestPartyMemberStatsOpcode(), ArenaSpectator::HandleResetCommand(), spell_the_flag_of_ownership::HandleScript(), WorldSession::HandleSendMail(), WorldSession::HandleSetActionButtonOpcode(), Guild::HandleSetLeader(), misc_commandscript::HandleSkirmishCommand(), misc_commandscript::HandleSummonCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), WorldSession::HandleTurnInPetitionOpcode(), Guild::HandleUpdateMemberRank(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), PlayerNameMapHolder::Insert(), Channel::Invite(), BattlegroundQueue::InviteGroupToBG(), Player::IsActionButtonDataValid(), ReputationMgr::IsAtWar(), lfg::LFGMgr::JoinLfg(), WorldSession::KickPlayer(), Player::LearnCustomSpells(), Player::LoadFromDB(), WaypointMovementGenerator< Creature >::LoadPath(), LogCommandUsage(), WorldSession::LogoutPlayer(), MotionMaster::MoveTaxiFlight(), ChatLogScript::OnChat(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_black_temple::instance_black_temple_InstanceMapScript::OnCreatureCreate(), lfg::LFGPlayerScript::OnMapChanged(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), Unit::OutDebugInfo(), MapMgr::PlayerCannotEnter(), SmartScript::ProcessAction(), PlayerNameMapHolder::Remove(), Map::RemoveAllPlayers(), Player::RemoveFromWorld(), Vehicle::RemovePassenger(), Creature::Respawn(), Pet::SavePetToDB(), AchievementMgr::SendAchievementEarned(), CreatureTextMgr::SendChat(), Guild::SendLoginInfo(), Spell::SendLoot(), WorldSession::SendPetNameQuery(), BattlegroundMgr::SendToBattleground(), Unit::SetCharm(), Player::setDeathState(), Player::SetEquipmentSet(), Channel::SetMode(), CreatureTextMgr::SetRepeatId(), Guild::Member::SetStats(), Player::SetViewpoint(), boss_grand_champion::boss_grand_championAI::SpellHit(), FollowerAI::StartFollow(), Player::StopCastingCharm(), Player::TeleportTo(), Channel::UnBan(), Pet::Update(), Player::Update(), boss_archavon::boss_archavonAI::UpdateAI(), Player::UpdateHomebindTime(), GameObject::Use(), and Player::Whisper().
GetNameForLocaleIdx()
virtual std::string const & WorldObject::GetNameForLocaleIdx (LocaleConstant) const inline virtual
Reimplemented in Creature, and GameObject.
{ return m_name; }
References m_name.
Referenced by ChatHandler::BuildChatPacket(), Acore::EmoteChatBuilder::operator()(), and Spell::SendResurrectRequest().
GetNearPoint()
void WorldObject::GetNearPoint (WorldObject const * searcher, float & x, float & y, float & z, float searcher_size, float distance2d, float absAngle, float controlZ = 0, Position const * startPos = nullptr) const
{
    GetNearPoint2D(x, y, distance2d + searcher_size, absAngle, startPos);
    z = GetPositionZ();
    if (searcher)
    {
        if (Unit const* unit = searcher->ToUnit(); Unit const* target = ToUnit())
        {
            if (unit && target && unit->IsInWater() && target->IsInWater())
            {
                // if the searcher is in water
                // we have no ground so we can
                // set the target height to the
                // z-coord to keep the searcher
                // at the correct height (face to face)
                z += GetCollisionHeight() - unit->GetCollisionHeight();
            }
        }
        searcher->UpdateAllowedPositionZ(x, y, z);
    }
    else
    {
        UpdateAllowedPositionZ(x, y, z);
    }
    // if detection disabled, return first point
    if (!sWorld->getBoolConfig(CONFIG_DETECT_POS_COLLISION))
        return;
    // return if the point is already in LoS
    if (!controlZ && IsWithinLOS(x, y, z))
        return;
    // remember first point
    float first_x = x;
    float first_y = y;
    float first_z = z;
    // loop in a circle to look for a point in LoS using small steps
    for (float angle = float(M_PI) / 8; angle < float(M_PI) * 2; angle += float(M_PI) / 8)
    {
        GetNearPoint2D(x, y, distance2d + searcher_size, absAngle + angle, startPos);
        z = GetPositionZ();
        UpdateAllowedPositionZ(x, y, z);
        if (controlZ && fabsf(GetPositionZ() - z) > controlZ)
            continue;
        if (IsWithinLOS(x, y, z))
            return;
    }
    // still not in LoS, give up and return first position found
    if (startPos)
    {
        x = searcher->GetPositionX();
        y = searcher->GetPositionY();
        z = searcher->GetPositionZ();
    }
    else
    {
        x = first_x;
        y = first_y;
        z = first_z;
    }
}
References CONFIG_DETECT_POS_COLLISION, GetCollisionHeight(), Unit::GetCollisionHeight(), GetNearPoint2D(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::IsInWater(), IsWithinLOS(), sWorld, Object::ToUnit(), and UpdateAllowedPositionZ().
Referenced by ChaseMovementGenerator< T >::DoUpdate(), GetChargeContactPoint(), GetClosePoint(), GetContactPoint(), Unit::GetMeleeAttackPoint(), Unit::GetRandomContactPoint(), GetVoidClosePoint(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::InitializeAI(), Spell::SelectImplicitCasterDestTargets(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), and hyjalAI::WaypointReached().
GetNearPoint2D() [1/2]
void WorldObject::GetNearPoint2D (float & x, float & y, float distance, float absAngle, Position const * startPos = nullptr) const
{
    GetNearPoint2D(nullptr, x, y, distance2d, absAngle, startPos);
}
References GetNearPoint2D().
GetNearPoint2D() [2/2]
void WorldObject::GetNearPoint2D (WorldObject const * searcher, float & x, float & y, float distance, float absAngle, Position const * startPos = nullptr) const
{
    float effectiveReach = GetCombatReach();
    if (searcher)
    {
        effectiveReach += searcher->GetCombatReach();
        if (this != searcher)
        {
            float myHover = 0.0f, searcherHover = 0.0f;
            if (Unit const* unit = ToUnit())
                myHover = unit->GetHoverHeight();
            if (Unit const* searchUnit = searcher->ToUnit())
                searcherHover = searchUnit->GetHoverHeight();
            float hoverDelta = myHover - searcherHover;
            if (hoverDelta != 0.0f)
                effectiveReach = std::sqrt(std::max(effectiveReach * effectiveReach - hoverDelta * hoverDelta, 0.0f));
        }
    }
    float positionX = startPos ? startPos->GetPositionX() : GetPositionX();
    float positionY = startPos ? startPos->GetPositionY() : GetPositionY();
    x = positionX + (effectiveReach + distance2d) * std::cos(absAngle);
    y = positionY + (effectiveReach + distance2d) * std::sin(absAngle);
    Acore::NormalizeMapCoord(x);
    Acore::NormalizeMapCoord(y);
}
References GetCombatReach(), Unit::GetHoverHeight(), Position::GetPositionX(), Position::GetPositionY(), Acore::NormalizeMapCoord(), and Object::ToUnit().
Referenced by GetNearPoint(), GetNearPoint2D(), and npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI().
GetNearPosition()
Position WorldObject::GetNearPosition (float dist, float angle)
{
    Position pos = GetPosition();
    MovePosition(pos, dist, angle);
    return pos;
}
References Position::GetPosition(), and MovePosition.
Referenced by boss_headless_horseman::DamageTaken(), npc_time_rift::npc_time_riftAI::DoSummonAtRift(), npc_simone::npc_simoneAI::JustDied(), spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Land(), spell_gen_random_target32::ModDest(), spell_q12308_escape_from_silverbrook_summon_worgen::ModDest(), npc_simone::npc_simoneAI::RespawnPet(), npc_stillpine_capitive::npc_stillpine_capitiveAI::StartMoving(), and instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SummonPortalKeeper().
GetNotifyFlags()
uint16 WorldObject::GetNotifyFlags () const inline
{ return m_notifyflags; }
References m_notifyflags.
GetObjectSize()
float WorldObject::GetObjectSize () const
{
    return (m_valuesCount > UNIT_FIELD_COMBATREACH) ? m_floatValues[UNIT_FIELD_COMBATREACH] : DEFAULT_WORLD_OBJECT_SIZE * GetObjectScale();
}
References DEFAULT_WORLD_OBJECT_SIZE, Object::GetObjectScale(), Object::m_floatValues, Object::m_valuesCount, and UNIT_FIELD_COMBATREACH.
Referenced by _IsWithinDist(), GameObject::_IsWithinDist(), Creature::CanCreatureAttack(), Spell::EffectSummonPet(), GetChargeContactPoint(), GetClosePoint(), GetCollisionRadius(), GetCollisionWidth(), Unit::GetCollisionWidth(), GetContactPoint(), GetDistance(), GetDistance2d(), GetDistanceZ(), Unit::GetMeleeAttackPoint(), misc_commandscript::HandleGroupSummonCommand(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), IsInBetween(), IsInRange(), IsInRange2d(), IsInRange3d(), IsWithinDist2d(), IsWithinDist3d(), MotionMaster::MoveJumpTo(), Acore::WorldObjectSpellConeTargetCheck::operator()(), Acore::WorldObjectSpellTrajTargetCheck::operator()(), SmartScript::ProcessAction(), npc_released_offspring_harkoa::npc_released_offspring_harkoaAI::Reset(), boss_selin_fireheart::boss_selin_fireheartAI::SelectNearestCrystal(), Player::SendMessageToSetInRange(), SendMessageToSetInRange(), GameObject::SendMessageToSetInRange(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::SpellHit(), SummonCreature(), and npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI().
GetPhaseMask()
uint32 WorldObject::GetPhaseMask () const inline
{ return m_phaseMask; }
References m_phaseMask.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), AddToWorld(), PathGenerator::BuildPolyPath(), Map::CheckCollisionAndGetValidCoords(), boss_volazj::CheckPhaseMinions(), BattlegroundRV::CheckPositionForUnit(), Map::ConvertCorpseToBones(), Creature::Create(), Corpse::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), DynamicObject::CreateDynamicObject(), Spell::EffectDuel(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), GameObject::EnableCollision(), GetFloorZ(), GetMapHeight(), GetMapWaterOrGroundLevel(), PathGenerator::GetNavTerrain(), GameObjectModelOwnerImpl::GetPhaseMask(), Player::GetPhaseMaskForSpawn(), debug_commandscript::HandleDebugSpawnVehicleCommand(), OutdoorPvPSI::HandleDropFlag(), gobject_commandscript::HandleGameObjectInfoCommand(), gobject_commandscript::HandleGameObjectNearCommand(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMovementOpcodes(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcNearCommand(), misc_commandscript::HandlePInfoCommand(), Map::HasEnoughWater(), InSamePhase(), PathGenerator::IsSwimmableSegment(), IsWithinLOS(), IsWithinLOSInMap(), npc_frost_wyrm::npc_frost_wyrmAI::JustDied(), npc_gargoyle::npc_gargoyleAI::JustDied(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::JustSummoned(), spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Land(), Creature::LoadCreatureFromDB(), Pet::LoadPetFromDB(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnGameObjectCreate(), at_q24545_frostmourne_cavern::OnTrigger(), IgbArtilleryCheck::operator()(), MysticBuffetTargetFilter::operator()(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), Spell::SelectImplicitCasterDestTargets(), Creature::setDeathState(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), Unit::SetPhaseMask(), PathGenerator::ShortenPathUntilDist(), Map::SummonCreature(), SummonGameObject(), Player::SummonPet(), SummonTrigger(), Creature::Update(), UpdateAllowedPositionZ(), and UpdatePositionData().
GetRandomNearPosition()
Position WorldObject::GetRandomNearPosition (float radius)
{
    Position pos = GetPosition();
    MovePosition(pos, radius * (float) rand_norm(), (float) rand_norm() * static_cast<float>(2 * M_PI));
    return pos;
}
References Position::GetPosition(), MovePosition, and rand_norm().
Referenced by CreatureAI::DoSummon(), CreatureAI::DoSummonFlyer(), boss_malchezaar::boss_malchezaarAI::SummonInfernal(), npc_doomfire_targetting::npc_doomfire_targettingAI::UpdateAI(), npc_minigob_manabonk::npc_minigob_manabonkAI::UpdateAI(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::UpdateAI(), and npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::UpdateAI().
GetRandomPoint() [1/2]
Position WorldObject::GetRandomPoint (const Position & srcPos, float distance) const
{
    float x, y, z;
    GetRandomPoint(srcPos, distance, x, y, z);
    return Position(x, y, z, GetOrientation());
}
References Position::GetOrientation(), and GetRandomPoint().
GetRandomPoint() [2/2]
void WorldObject::GetRandomPoint (const Position & srcPos, float distance, float & rand_x, float & rand_y, float & rand_z) const
{
    if (!distance)
    {
        pos.GetPosition(rand_x, rand_y, rand_z);
        return;
    }
    // angle to face `obj` to `this`
    float angle = (float)rand_norm() * static_cast<float>(2 * M_PI);
    float new_dist = (float)rand_norm() * static_cast<float>(distance);
    rand_x = pos.m_positionX + new_dist * cos(angle);
    rand_y = pos.m_positionY + new_dist * std::sin(angle);
    rand_z = pos.m_positionZ;
    Acore::NormalizeMapCoord(rand_x);
    Acore::NormalizeMapCoord(rand_y);
    UpdateGroundPositionZ(rand_x, rand_y, rand_z);            // update to LOS height if available
}
References Position::GetPosition(), Position::m_positionX, Position::m_positionY, Position::m_positionZ, Acore::NormalizeMapCoord(), rand_norm(), and UpdateGroundPositionZ().
Referenced by boss_isalien::DamageTaken(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), Spell::EffectSummonType(), OrcMoveEvent::Execute(), GetRandomPoint(), SmartScript::ProcessAction(), Spell::SummonGuardian(), and boss_fankriss::SummonHatchlingWaves().
GetSightRange()
float WorldObject::GetSightRange (WorldObject const * target = nullptr) const virtual
Reimplemented in Player.
{
    if (ToUnit())
    {
        if (ToPlayer())
        {
            if (target)
            {
                if (target->IsVisibilityOverridden() && target->GetTypeId() == TYPEID_UNIT)
                {
                    return *target->m_visibilityDistanceOverride;
                }
                else if (target->GetTypeId() == TYPEID_GAMEOBJECT)
                {
                    if (IsInWintergrasp() && target->IsInWintergrasp())
                    {
                        return VISIBILITY_DIST_WINTERGRASP + VISIBILITY_INC_FOR_GOBJECTS;
                    }
                    else if (target->IsVisibilityOverridden())
                    {
                        return *target->m_visibilityDistanceOverride;
                    }
                    else if (ToPlayer()->GetCinematicMgr()->IsOnCinematic())
                    {
                        return DEFAULT_VISIBILITY_INSTANCE;
                    }
                    else
                    {
                        return GetMap()->GetVisibilityRange() + VISIBILITY_INC_FOR_GOBJECTS;
                    }
                }
                return IsInWintergrasp() && target->IsInWintergrasp() ? VISIBILITY_DIST_WINTERGRASP : GetMap()->GetVisibilityRange();
            }
            return IsInWintergrasp() ? VISIBILITY_DIST_WINTERGRASP : GetMap()->GetVisibilityRange();
        }
        else if (ToCreature())
        {
            return ToCreature()->m_SightDistance;
        }
        else
        {
            return SIGHT_RANGE_UNIT;
        }
    }
    if (ToDynObject() && isActiveObject())
    {
        return GetMap()->GetVisibilityRange();
    }
    return 0.0f;
}
References DEFAULT_VISIBILITY_INSTANCE, GetMap(), Object::GetTypeId(), Map::GetVisibilityRange(), isActiveObject(), IsInWintergrasp(), IsVisibilityOverridden(), Creature::m_SightDistance, m_visibilityDistanceOverride, SIGHT_RANGE_UNIT, Object::ToCreature(), Object::ToDynObject(), Object::ToPlayer(), Object::ToUnit(), TYPEID_GAMEOBJECT, TYPEID_UNIT, VISIBILITY_DIST_WINTERGRASP, and VISIBILITY_INC_FOR_GOBJECTS.
Referenced by CanSeeOrDetect(), and Player::GetSightRange().
GetStationaryO()
virtual float WorldObject::GetStationaryO () const inline virtual
Reimplemented in GameObject.
{ return GetOrientation(); }
References Position::GetOrientation().
GetStationaryX()
virtual float WorldObject::GetStationaryX () const inline virtual
Reimplemented in GameObject.
{ return GetPositionX(); }
References Position::GetPositionX().
GetStationaryY()
virtual float WorldObject::GetStationaryY () const inline virtual
Reimplemented in GameObject.
{ return GetPositionY(); }
References Position::GetPositionY().
GetStationaryZ()
virtual float WorldObject::GetStationaryZ () const inline virtual
Reimplemented in GameObject.
{ return GetPositionZ(); }
References Position::GetPositionZ().
GetTransGUID()
ObjectGuid WorldObject::GetTransGUID () const virtual
Reimplemented in Unit.
{
    if (GetTransport())
        return GetTransport()->GetGUID();
    return ObjectGuid::Empty;
}
References ObjectGuid::Empty, Object::GetGUID(), and GetTransport().
Referenced by IgbTeleportOnVictoryCheck::operator()(), and SpellDestination::SpellDestination().
GetTransOffsetO()
float WorldObject::GetTransOffsetO () const inline
{ return m_movementInfo.transport.pos.GetOrientation(); }
References Position::GetOrientation(), m_movementInfo, MovementInfo::TransportInfo::pos, and MovementInfo::transport.
Referenced by Player::_SaveCharacter(), Unit::BuildMovementPacket(), npc_commandscript::HandleNpcAddCommand(), SpellCastTargets::Read(), Creature::SaveToDB(), and SpellDestination::SpellDestination().
GetTransOffsetX()
float WorldObject::GetTransOffsetX () const inline
{ return m_movementInfo.transport.pos.GetPositionX(); }
References Position::GetPositionX(), m_movementInfo, MovementInfo::TransportInfo::pos, and MovementInfo::transport.
Referenced by Player::_SaveCharacter(), Unit::BuildMovementPacket(), npc_commandscript::HandleNpcAddCommand(), SpellCastTargets::Read(), Creature::SaveToDB(), and SpellDestination::SpellDestination().
GetTransOffsetY()
float WorldObject::GetTransOffsetY () const inline
{ return m_movementInfo.transport.pos.GetPositionY(); }
References Position::GetPositionY(), m_movementInfo, MovementInfo::TransportInfo::pos, and MovementInfo::transport.
Referenced by Player::_SaveCharacter(), Unit::BuildMovementPacket(), npc_commandscript::HandleNpcAddCommand(), SpellCastTargets::Read(), Creature::SaveToDB(), and SpellDestination::SpellDestination().
GetTransOffsetZ()
float WorldObject::GetTransOffsetZ () const inline
{ return m_movementInfo.transport.pos.GetPositionZ(); }
References Position::GetPositionZ(), m_movementInfo, MovementInfo::TransportInfo::pos, and MovementInfo::transport.
Referenced by Player::_SaveCharacter(), Unit::BuildMovementPacket(), npc_commandscript::HandleNpcAddCommand(), SpellCastTargets::Read(), Creature::SaveToDB(), and SpellDestination::SpellDestination().
GetTransport()
Transport * WorldObject::GetTransport () const inline
{ return m_transport; }
References m_transport.
Referenced by _IsWithinDist(), Player::_SaveCharacter(), MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), Unit::BuildMovementPacket(), Object::BuildMovementUpdate(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::CanAIAttack(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::CanAIAttack(), npc_igb_ship_crew::npc_igb_ship_crewAI::CanAIAttack(), npc_gunship_boarding_addAI::CanAIAttack(), npc_gunship_gunner::npc_gunship_gunnerAI::CanAIAttack(), DynamicObject::CleanupsBeforeDelete(), GameObject::CleanupsBeforeDelete(), Unit::CleanupsBeforeDelete(), npc_gunship::npc_gunshipAI::DamageTaken(), DelayedMovementEvent::Execute(), ResetEncounterEvent::Execute(), npc_gunship::GetAI(), Unit::GetDirectTransport(), Creature::GetRespawnPosition(), GetTransGUID(), Unit::GetTransGUID(), GameObject::GetWorldRotation(), WorldSession::HandleForceSpeedChangeAck(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), WorldSession::HandlePlayerLoginFromDB(), Unit::isInAccessiblePlaceFor(), npc_gunship::npc_gunshipAI::JustDied(), Player::KillPlayer(), npc_gunship_boarding_addAI::MovementInform(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::npc_high_overlord_saurfang_igbAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::npc_muradin_bronzebeard_igbAI(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), item_petrov_cluster_bombs::OnUse(), IgbExplosionCheck::operator()(), BurningPitchFilterCheck::operator()(), IgbArtilleryCheck::operator()(), Player::ProcessTerrainStatusUpdate(), spell_igb_teleport_to_enemy_ship::spell_igb_teleport_to_enemy_ship_SpellScript::RelocateTransportOffset(), Creature::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), Vehicle::RemovePassenger(), Creature::SaveToDB(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::SelectTransport(), Map::SendInitSelf(), Map::SendInitTransports(), Map::SendRemoveTransports(), Acore::VisibleNotifier::SendToSelf(), Unit::SetCharmedBy(), gunship_npc_AI::SetData(), Movement::MoveSplineInit::SetFacing(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), WaypointMovementGenerator< Creature >::StartMove(), Map::SummonCreature(), Player::TeleportTo(), Creature::Update(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), and UpdateAllowedPositionZ().
GetTransSeat()
int8 WorldObject::GetTransSeat () const inline
{ return m_movementInfo.transport.seat; }
References m_movementInfo, MovementInfo::TransportInfo::seat, and MovementInfo::transport.
Referenced by Unit::_EnterVehicle(), Unit::BuildMovementPacket(), Unit::ChangeSeat(), Movement::MoveSplineInit::Launch(), and Movement::MoveSplineInit::Stop().
GetTransTime()
uint32 WorldObject::GetTransTime () const inline
{ return m_movementInfo.transport.time; }
References m_movementInfo, MovementInfo::TransportInfo::time, and MovementInfo::transport.
Referenced by Unit::BuildMovementPacket().
GetVisibilityRange()
float WorldObject::GetVisibilityRange () const
{
    if (IsVisibilityOverridden() && GetTypeId() == TYPEID_UNIT)
    {
        return *m_visibilityDistanceOverride;
    }
    else if (GetTypeId() == TYPEID_GAMEOBJECT)
    {
        {
            if (IsInWintergrasp())
            {
                return VISIBILITY_DIST_WINTERGRASP + VISIBILITY_INC_FOR_GOBJECTS;
            }
            else if (IsVisibilityOverridden())
            {
                return *m_visibilityDistanceOverride;
            }
            else
            {
                return GetMap()->GetVisibilityRange() + VISIBILITY_INC_FOR_GOBJECTS;
            }
        }
    }
    else
        return IsInWintergrasp() ? VISIBILITY_DIST_WINTERGRASP : GetMap()->GetVisibilityRange();
}
References GetMap(), Object::GetTypeId(), Map::GetVisibilityRange(), IsInWintergrasp(), IsVisibilityOverridden(), m_visibilityDistanceOverride, TYPEID_GAMEOBJECT, TYPEID_UNIT, VISIBILITY_DIST_WINTERGRASP, and VISIBILITY_INC_FOR_GOBJECTS.
Referenced by PetAI::_needToStop(), BuildUpdate(), Creature::CanCreatureAttack(), Spell::CheckCast(), Spell::CheckSpellFocus(), DestroyForNearbyPlayers(), Spell::EffectForceDeselect(), Spell::EffectSanctuary(), AuraEffect::HandleFeignDeath(), SendMessageToSet(), Player::SendMessageToSet(), Player::TeleportTo(), Pet::Update(), Creature::Update(), Player::Update(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), and UpdateObjectVisibility().
GetVoidClosePoint()
void WorldObject::GetVoidClosePoint (float & x, float & y, float & z, float size, float distance2d = 0, float relAngle = 0, float controlZ = 0) const
{
    // angle calculated from current orientation
    GetNearPoint(nullptr, x, y, z, size, distance2d, GetOrientation() + relAngle, controlZ);
}
References GetNearPoint(), and Position::GetOrientation().
GetZoneAndAreaId()
void WorldObject::GetZoneAndAreaId (uint32 & zoneid, uint32 & areaid) const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    zoneid = _zoneId;
    areaid = _areaId;
}
References _areaId, _updatePositionData, _zoneId, and UpdatePositionData().
Referenced by Spell::CheckCast(), Graveyard::GetClosestGraveyard(), GameObject::GetFishLoot(), GameObject::GetFishLootJunk(), Aura::HandleAuraSpecificMods(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandlePlayerLoginToCharInWorld(), AchievementCriteriaData::Meets(), Player::ResurrectPlayer(), Player::SendInitialPacketsAfterAddToMap(), Player::SendQuestUpdate(), Player::Update(), Player::UpdatePosition(), and GameObject::Use().
GetZoneId()
uint32 WorldObject::GetZoneId () const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    return _zoneId;
}
References _updatePositionData, _zoneId, and UpdatePositionData().
Referenced by Player::_LoadInventory(), Player::_SaveCharacter(), Player::AddQuest(), Vehicle::ApplyAllImmunities(), WorldSession::BuildPartyMemberStatsChangedPacket(), Spell::CheckCast(), Player::CompleteQuest(), ScriptedAI::DoPlayMusic(), Spell::EffectSummonPlayer(), Spell::EffectSummonRaFFriend(), World::FindPlayerInZone(), Acore::XP::Gain(), SocialMgr::GetFriendInfo(), Player::GetOutdoorPvP(), Player::GiveXP(), go_bells::go_bellsAI::go_bellsAI(), WorldSession::HandleAreaSpiritHealerQueryOpcode(), WorldSession::HandleAreaSpiritHealerQueueOpcode(), AuraEffect::HandleAuraDummy(), WorldSession::HandleBfEntryInviteResponse(), misc_commandscript::HandleChangeWeather(), go_commandscript::HandleGoZoneXYCommand(), WorldSession::HandleHearthAndResurrect(), misc_commandscript::HandleLinkGraveCommand(), WorldSession::HandleMoveTeleportAck(), misc_commandscript::HandleNearGraveCommand(), spell_wintergrasp_hide_small_elementals::spell_wintergrasp_hide_small_elementals_AuraScript::HandlePeriodicDummy(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandleRequestPartyMemberStatsOpcode(), misc_commandscript::HandleSummonCommand(), Player::IncompleteQuest(), SpellArea::IsFitToRequirements(), boss_azuregos::boss_azuregosAI::JustDied(), Unit::Kill(), Player::KilledPlayerCredit(), LogCommandUsage(), WorldSession::LogoutPlayer(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnPlayerAreaUpdate(), item_petrov_cluster_bombs::OnUse(), item_only_for_flight::OnUse(), SmartScript::ProcessAction(), Player::RemoveActiveQuest(), Player::RemovedInsignia(), Player::RepopAtGraveyard(), boss_azuregos::boss_azuregosAI::Reset(), Player::RewardQuest(), CreatureTextMgr::SendChatPacket(), CreatureTextMgr::SendNonChatPacket(), Map::SendZoneDynamicInfo(), Guild::Member::SetStats(), and SetZoneScript().
GetZoneScript()
ZoneScript * WorldObject::GetZoneScript () const inline
{ return m_zoneScript; }
References m_zoneScript.
Referenced by CreatureAI::_EnterEvadeMode(), Creature::AddToWorld(), Creature::CreateFromProto(), Spell::EffectSendEvent(), Creature::RemoveFromWorld(), and Unit::setDeathState().
HasAllowedLooter()
bool WorldObject::HasAllowedLooter (ObjectGuid guid) const
{
    if (_allowedLooters.empty())
    {
        return true;
    }
    return _allowedLooters.find(guid) != _allowedLooters.end();
}
References _allowedLooters.
Referenced by Player::IsAtLootRewardDistance(), and GameObject::IsLootAllowedFor().
InSamePhase() [1/2]
bool WorldObject::InSamePhase (uint32 phasemask) const inline
{ return m_useCombinedPhases ? GetPhaseMask() & phasemask : GetPhaseMask() == phasemask; }
References GetPhaseMask(), and m_useCombinedPhases.
InSamePhase() [2/2]
bool WorldObject::InSamePhase (WorldObject const * obj) const inline
{ return InSamePhase(obj->GetPhaseMask()); }
References GetPhaseMask(), and InSamePhase().
Referenced by Unit::Attack(), CanNeverSee(), boss_halion::boss_halionAI::DamageTaken(), boss_twilight_halion::boss_twilight_halionAI::DamageTaken(), InSamePhase(), IsValidCombatTarget(), ThreatCalcHelper::isValidProcess(), Unit::IsWithinCombatRange(), GameObject::IsWithinDistInMap(), IsWithinDistInMap(), Unit::IsWithinMeleeRange(), Unit::IsWithinRange(), Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::operator()(), Acore::AllWorldObjectsInRange::operator()(), Unit::SetPhaseMask(), Acore::MessageDistDeliverer::Visit(), and Acore::MessageDistDelivererToHostile::Visit().
isActiveObject()
bool WorldObject::isActiveObject () const inline
{ return m_isActive; }
References m_isActive.
Referenced by AddObjectHelper(), Map::AddToMap(), boss_hadronox::boss_hadronoxAI::CheckEvadeIfOutOfCombatArea(), npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken(), HostileRefMgr::deleteReferencesOutOfRange(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), boss_illidari_council::boss_illidari_councilAI::DoAction(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::EnterEvadeMode(), boss_hadronox::boss_hadronoxAI::GetData(), GetGridActivationRange(), GetSightRange(), Map::RemoveFromMap(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SetData(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SummonedCreatureDespawn(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), and boss_illidari_council::boss_illidari_councilAI::UpdateAI().
IsAlwaysDetectableFor()
virtual bool WorldObject::IsAlwaysDetectableFor (WorldObject const *) const inline protected virtual
Reimplemented in Creature, Player, and Unit.
{ return false; }
Referenced by CanDetect(), and Unit::IsAlwaysDetectableFor().
IsAlwaysVisibleFor()
virtual bool WorldObject::IsAlwaysVisibleFor (WorldObject const *) const inline protected virtual
Reimplemented in GameObject, and Unit.
{ return false; }
Referenced by CanSeeOrDetect(), GameObject::IsAlwaysVisibleFor(), and Unit::IsAlwaysVisibleFor().
IsFarVisible()
bool WorldObject::IsFarVisible () const inline
{ return m_isFarVisible; }
References m_isFarVisible.
isInBack()
bool WorldObject::isInBack (WorldObject const * target, float arc = M_PI) const
{
    return !HasInArc(2 * M_PI - arc, target);
}
References Position::HasInArc().
Referenced by Acore::WorldObjectSpellConeTargetCheck::operator()().
IsInBetween()
bool WorldObject::IsInBetween (WorldObject const * obj1, WorldObject const * obj2, float size = 0) const
{
    if (!obj1 || !obj2)
        return false;
    if (!size)
        size = GetObjectSize() / 2;
    float pdist = obj1->GetExactDist2dSq(obj2) + size / 2.0f;
    if (GetExactDist2dSq(obj1) >= pdist || GetExactDist2dSq(obj2) >= pdist)
        return false;
    if (G3D::fuzzyEq(obj1->GetPositionX(), obj2->GetPositionX()))
        return GetPositionX() >= obj1->GetPositionX() - size && GetPositionX() <= obj1->GetPositionX() + size;
    float A = (obj2->GetPositionY() - obj1->GetPositionY()) / (obj2->GetPositionX() - obj1->GetPositionX());
    float B = -1;
    float C = obj1->GetPositionY() - A * obj1->GetPositionX();
    float dist = std::fabs(A * GetPositionX() + B * GetPositionY() + C) / std::sqrt(A * A + B * B);
    return dist <= size;
}
References Position::GetExactDist2dSq(), GetObjectSize(), Position::GetPositionX(), and Position::GetPositionY().
Referenced by TwilightCutterSelector::operator()().
isInFront()
bool WorldObject::isInFront (WorldObject const * target, float arc = M_PI) const
{
    return HasInArc(arc, target);
}
References Position::HasInArc().
Referenced by spell_dk_death_coil::CheckCast(), spell_pal_holy_shock::CheckCast(), spell_pri_penance::CheckCast(), spell_warr_retaliation::CheckProc(), and Acore::WorldObjectSpellConeTargetCheck::operator()().
IsInMap()
bool WorldObject::IsInMap (WorldObject const * obj) const
{
    if (obj)
    {
        return IsInWorld() && obj->IsInWorld() && (FindMap() == obj->FindMap());
    }
    return false;
}
References FindMap(), and Object::IsInWorld().
Referenced by Unit::Attack(), Creature::CanCreatureAttack(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::DamageTaken(), SmartAI::EndPath(), ReflectEvent::Execute(), Unit::GetPartyMembers(), Player::GetsRecruitAFriendBonus(), WorldSession::HandlePushQuestToParty(), Unit::HandleSpellClick(), Player::IsAtGroupRewardDistance(), SmartAI::IsEscortInvokerInRange(), IsSelfOrInSameMap(), ThreatCalcHelper::isValidProcess(), Unit::IsWithinCombatRange(), GameObject::IsWithinDistInMap(), IsWithinDistInMap(), IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), Unit::IsWithinRange(), Unit::Kill(), MysticBuffetTargetFilter::operator()(), KillRewarder::Reward(), Acore::VisibleNotifier::SendToSelf(), Totem::UnSummon(), PetAI::UpdateAllies(), and Group::UpdatePlayerOutOfRange().
IsInRange()
bool WorldObject::IsInRange (WorldObject const * obj, float minRange, float maxRange, bool is3D = true) const
{
    float dx = GetPositionX() - obj->GetPositionX();
    float dy = GetPositionY() - obj->GetPositionY();
    float distsq = dx * dx + dy * dy;
    if (is3D)
    {
        float dz = GetPositionZ() - obj->GetPositionZ();
        distsq += dz * dz;
    }
    float sizefactor = GetObjectSize() + obj->GetObjectSize();
    // check only for real range
    if (minRange > 0.0f)
    {
        float mindist = minRange + sizefactor;
        if (distsq < mindist * mindist)
            return false;
    }
    float maxdist = maxRange + sizefactor;
    return distsq < maxdist * maxdist;
}
References GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
Referenced by SmartScript::GetTargets(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), npc_shay_leafrunner::npc_shay_leafrunnerAI::MoveInLineOfSight(), HammerOfJusticeSelector::operator()(), SmartScript::ProcessEvent(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), and boss_grand_champion::boss_grand_championAI::UpdateAI().
IsInRange2d()
bool WorldObject::IsInRange2d (float x, float y, float minRange, float maxRange) const
{
    float dx = GetPositionX() - x;
    float dy = GetPositionY() - y;
    float distsq = dx * dx + dy * dy;
    float sizefactor = GetObjectSize();
    // check only for real range
    if (minRange > 0.0f)
    {
        float mindist = minRange + sizefactor;
        if (distsq < mindist * mindist)
            return false;
    }
    float maxdist = maxRange + sizefactor;
    return distsq < maxdist * maxdist;
}
References GetObjectSize(), Position::GetPositionX(), and Position::GetPositionY().
IsInRange3d()
bool WorldObject::IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
{
    float dx = GetPositionX() - x;
    float dy = GetPositionY() - y;
    float dz = GetPositionZ() - z;
    float distsq = dx * dx + dy * dy + dz * dz;
    float sizefactor = GetObjectSize();
    // check only for real range
    if (minRange > 0.0f)
    {
        float mindist = minRange + sizefactor;
        if (distsq < mindist * mindist)
            return false;
    }
    float maxdist = maxRange + sizefactor;
    return distsq < maxdist * maxdist;
}
References GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
IsInvisibleDueToDespawn()
virtual bool WorldObject::IsInvisibleDueToDespawn () const inline protected virtual
Reimplemented in Creature, and GameObject.
{ return false; }
Referenced by CanSeeOrDetect(), Creature::IsInvisibleDueToDespawn(), and GameObject::IsInvisibleDueToDespawn().
IsInWintergrasp()
bool WorldObject::IsInWintergrasp () const inline
    {
        return GetMapId() == 571 && GetPositionX() > 3733.33331f && GetPositionX() < 5866.66663f && GetPositionY() > 1599.99999f && GetPositionY() < 4799.99997f;
    }
References WorldLocation::GetMapId(), Position::GetPositionX(), and Position::GetPositionY().
Referenced by GetGridActivationRange(), GetSightRange(), and GetVisibilityRange().
isNeedNotify()
bool WorldObject::isNeedNotify (uint16 f) const inline
{ return m_notifyflags & f;}
References m_notifyflags.
Referenced by Acore::AIRelocationNotifier::Visit(), and Acore::CreatureRelocationNotifier::Visit().
IsNeverVisible()
virtual bool WorldObject::IsNeverVisible () const inline protected virtual
Reimplemented in GameObject, and Player.
{ return !IsInWorld(); }
References Object::IsInWorld().
Referenced by CanSeeOrDetect(), GameObject::IsNeverVisible(), and Player::IsNeverVisible().
IsOutdoors()
bool WorldObject::IsOutdoors () const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    return _outdoors;
}
References _outdoors, _updatePositionData, and UpdatePositionData().
Referenced by Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), and misc_commandscript::HandleGPSCommand().
IsPermanentWorldObject()
bool WorldObject::IsPermanentWorldObject () const inline
{ return m_isWorldObject; }
References m_isWorldObject.
Referenced by Map::RemoveAllObjectsInRemoveList(), and Map::SwitchGridContainers().
IsSelfOrInSameMap()
bool WorldObject::IsSelfOrInSameMap (WorldObject const * obj) const
{
    if (this == obj)
    {
        return true;
    }
    return IsInMap(obj);
}
References IsInMap().
Referenced by Aura::UpdateTargetMap().
IsVisibilityOverridden()
bool WorldObject::IsVisibilityOverridden () const inline
{ return m_visibilityDistanceOverride.has_value(); }
References m_visibilityDistanceOverride.
Referenced by GetSightRange(), GetVisibilityRange(), and Acore::VisibleNotifier::Visit().
IsWithinDist()
bool WorldObject::IsWithinDist (WorldObject const * obj, float dist2compare, bool is3D = true, bool useBoundingRadius = true) const
{
    return obj && _IsWithinDist(obj, dist2compare, is3D, useBoundingRadius);
}
References _IsWithinDist().
Referenced by Unit::CalcAbsorbResist(), Creature::CanCreatureAttack(), CanSeeOrDetect(), Creature::CanStartAttack(), npc_cork_gizelton::npc_cork_gizeltonAI::CheckPlayer(), boss_twinemperorsAI::EnterCombat(), boss_akilzon::boss_akilzonAI::HandleStormSequence(), CreatureAI::MoveInLineOfSight(), npc_brew_bubble::MoveInLineOfSight(), npc_a_special_surprise::npc_a_special_surpriseAI::MoveInLineOfSight(), npc_towering_infernal::npc_towering_infernalAI::MoveInLineOfSight(), npc_lesser_doomguard::npc_lesser_doomguardAI::MoveInLineOfSight(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::operator()(), Acore::AllGameObjectsWithEntryInRange::operator()(), Acore::PlayerAtMinimumRangeAway::operator()(), Acore::AllCreaturesOfEntryInRange::operator()(), FrostwingVrykulSearcher::operator()(), Acore::AllWorldObjectsInRange::operator()(), Spell::SearchChainTargets(), npc_daphne_stilwell::npc_daphne_stilwellAI::Update(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_frost_wyrm::npc_frost_wyrmAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_yor::npc_yorAI::UpdateAI(), npc_voidtraveler::npc_voidtravelerAI::UpdateAI(), npc_ichor_globule::npc_ichor_globuleAI::UpdateAI(), and Group::UpdatePlayerOutOfRange().
IsWithinDist2d() [1/2]
bool WorldObject::IsWithinDist2d (const Position * pos, float dist) const
{
    return IsInDist2d(pos, dist + GetObjectSize());
}
References GetObjectSize(), and Position::IsInDist2d().
IsWithinDist2d() [2/2]
bool WorldObject::IsWithinDist2d (float x, float y, float dist) const
{
    return IsInDist2d(x, y, dist + GetObjectSize());
}
References GetObjectSize(), and Position::IsInDist2d().
Referenced by npc_hivezara_stinger::EnterCombat(), npc_vekniss_stinger::EnterCombat(), spell_vehicle_throw_passenger::spell_vehicle_throw_passenger_SpellScript::HandleScript(), boss_eye_of_cthun::MoveInLineOfSight(), BattlefieldWG::OnCreatureCreate(), boss_shade_of_aran::boss_aranAI::UpdateAI(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
IsWithinDist3d() [1/2]
bool WorldObject::IsWithinDist3d (const Position * pos, float dist) const
{
    return IsInDist(pos, dist + GetObjectSize());
}
References GetObjectSize(), and Position::IsInDist().
IsWithinDist3d() [2/2]
bool WorldObject::IsWithinDist3d (float x, float y, float z, float dist) const
{
    return IsInDist(x, y, z, dist + GetObjectSize());
}
References GetObjectSize(), and Position::IsInDist().
Referenced by Spell::CheckRange(), GameObject::IsInRange(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), Player::TeleportTo(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), npc_power_spark::npc_power_sparkAI::UpdateAI(), and boss_the_black_stalker::boss_the_black_stalkerAI::UpdateAI().
IsWithinDistInMap()
bool WorldObject::IsWithinDistInMap (WorldObject const * obj, float dist2compare, bool is3D = true, bool useBoundingRadius = true) const
{
    return obj && IsInMap(obj) && InSamePhase(obj) && _IsWithinDist(obj, dist2compare, is3D, useBoundingRadius);
}
References _IsWithinDist(), InSamePhase(), and IsInMap().
Referenced by npc_escortAI::AssistPlayerInCombatAgainst(), FollowerAI::AssistPlayerInCombatAgainst(), SmartAI::AssistPlayerInCombatAgainst(), Creature::CanStartAttack(), Player::CheckDuelDistance(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::CheckEventFail(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::CheckEventFail(), spell_sha_fire_nova::CheckFireTotem(), WorldSession::DoLootRelease(), CreatureAI::DoZoneInCombat(), BattlegroundEY::EventPlayerClickedOnFlag(), BattlegroundWS::EventPlayerClickedOnFlag(), BattlegroundAB::EventPlayerClickedOnFlag(), FollowerAI::GetLeaderForFollower(), Player::GetNextRandomRaidMember(), Unit::GetNextRandomRaidMemberOrPet(), Player::GetNPCIfCanInteractWith(), Unit::HandleAuraRaidProcFromChargeWithValue(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleInitiateTradeOpcode(), WorldSession::HandleLootMoneyOpcode(), AuraEffect::HandleModPossessPet(), WorldSession::HandleReclaimCorpseOpcode(), Unit::isInBackInMap(), Unit::isInFrontInMap(), npc_escortAI::IsPlayerOrGroupInRange(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::MoveInLineOfSight(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), boss_nalorakk::boss_nalorakkAI::MoveInLineOfSight(), alliance_rifleman::alliance_riflemanAI::MoveInLineOfSight(), boss_aeonus::boss_aeonusAI::MoveInLineOfSight(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::MoveInLineOfSight(), boss_temporus::boss_temporusAI::MoveInLineOfSight(), npc_medivh_bm::npc_medivh_bmAI::MoveInLineOfSight(), npc_general_andorov::MoveInLineOfSight(), npc_ouro_spawner::MoveInLineOfSight(), npc_depth_charge::npc_depth_chargeAI::MoveInLineOfSight(), npc_draenei_survivor::npc_draenei_survivorAI::MoveInLineOfSight(), npc_kerlonian::npc_kerlonianAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_custodian_of_time::npc_custodian_of_timeAI::MoveInLineOfSight(), npc_tooga::npc_toogaAI::MoveInLineOfSight(), npc_twiggy_flathead::npc_twiggy_flatheadAI::MoveInLineOfSight(), npc_ringo::npc_ringoAI::MoveInLineOfSight(), boss_gluth::boss_gluthAI::MoveInLineOfSight(), npc_khunok_the_behemoth::npc_khunok_the_behemothAI::MoveInLineOfSight(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::MoveInLineOfSight(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::MoveInLineOfSight(), boss_exarch_maladaar::boss_exarch_maladaarAI::MoveInLineOfSight(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::MoveInLineOfSight(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::MoveInLineOfSight(), npc_daranelle::npc_daranelleAI::MoveInLineOfSight(), npc_ancestral_wolf::npc_ancestral_wolfAI::MoveInLineOfSight(), npc_pet_hunter_snake_trap::MoveInLineOfSight(), npc_air_force_bots::npc_air_force_botsAI::MoveInLineOfSight(), Acore::CallOfHelpCreatureInRangeDo::operator()(), Acore::AnyAssistCreatureInRangeCheck::operator()(), Acore::NearestAssistCreatureInCreatureRangeCheck::operator()(), Acore::NearestGameObjectFishingHole::operator()(), Acore::NearestGameObjectCheck::operator()(), Acore::NearestGameObjectEntryInObjectRangeCheck::operator()(), Acore::NearestGameObjectTypeInObjectRangeCheck::operator()(), Acore::AnyDeadUnitObjectInRangeCheck::operator()(), Acore::AnyPlayerInObjectRangeCheck::operator()(), Acore::NearestPlayerInObjectRangeCheck::operator()(), Acore::MostHPMissingInRange::operator()(), Acore::MostHPPercentMissingInRange::operator()(), Acore::FriendlyCCedInRange::operator()(), Acore::FriendlyMissingBuffInRange::operator()(), Acore::AnyUnfriendlyUnitInObjectRangeCheck::operator()(), Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::operator()(), Acore::NearestAttackableNoTotemUnitInObjectRangeCheck::operator()(), Acore::AnyFriendlyUnitInObjectRangeCheck::operator()(), Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::operator()(), Acore::AnyGroupedUnitInObjectRangeCheck::operator()(), Acore::AnyUnitInObjectRangeCheck::operator()(), Acore::NearestAttackableUnitInObjectRangeCheck::operator()(), Acore::AnyAoETargetUnitInObjectRangeCheck::operator()(), Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck::operator()(), Acore::NearestHostileUnitCheck::operator()(), Acore::NearestHostileUnitInAttackDistanceCheck::operator()(), Acore::MostHPMissingGroupInRange::operator()(), Acore::AllDeadCreaturesInRange::operator()(), Acore::AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck::operator()(), SmartScript::ProcessEvent(), npc_lake_frog::npc_lake_frogAI::ReceiveEmote(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), boss_nalorakk::boss_nalorakkAI::ResetMobs(), Map::ScriptsProcess(), ScriptedAI::SelectSpell(), ScriptedAI::SelectTargetFromPlayerList(), boss_nalorakk::boss_nalorakkAI::SendAttacker(), Player::SendLoot(), npc_corrupted_totem::SetAura(), Pet::Update(), Creature::Update(), Player::Update(), TotemAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_halazzi::boss_halazziAI::UpdateAI(), boss_alyson_antille::boss_alyson_antilleAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), alliance_rifleman::alliance_riflemanAI::UpdateAI(), npc_steamrigger_mechanic::npc_steamrigger_mechanicAI::UpdateAI(), FollowerAI::UpdateAI(), Spell::UpdateChanneledTargetList(), and Player::UpdatePosition().
IsWithinLOS()
bool WorldObject::IsWithinLOS (float x, float y, float z, VMAP::ModelIgnoreFlags ignoreFlags = VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks = LINEOFSIGHT_ALL_CHECKS) const
{
    if (IsInWorld())
    {
        oz += GetCollisionHeight();
        float x, y, z;
        if (GetTypeId() == TYPEID_PLAYER)
        {
            GetPosition(x, y, z);
            z += GetCollisionHeight();
        }
        else
        {
            GetHitSpherePointFor({ ox, oy, oz }, x, y, z);
        }
        return GetMap()->isInLineOfSight(x, y, z, ox, oy, oz, GetPhaseMask(), checks, ignoreFlags);
    }
    return true;
}
References GetCollisionHeight(), GetHitSpherePointFor(), GetMap(), GetPhaseMask(), Position::GetPosition(), Object::GetTypeId(), Map::isInLineOfSight(), Object::IsInWorld(), and TYPEID_PLAYER.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), Spell::CheckCast(), Spell::CheckEffectTarget(), boss_ick::boss_ickAI::DamageTaken(), Spell::EffectChargeDest(), boss_vem::EnterCombat(), GetChargeContactPoint(), GetClosePoint(), GetContactPoint(), GetNearPoint(), Unit::GetRandomContactPoint(), spell_marrowgar_coldflame_bonestorm::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), Spell::SelectImplicitCasterDestTargets(), npc_coldflame::npc_coldflameAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), and boss_mimiron::boss_mimironAI::UpdateAI().
IsWithinLOSInMap()
bool WorldObject::IsWithinLOSInMap (WorldObject const * obj, VMAP::ModelIgnoreFlags ignoreFlags = VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks = LINEOFSIGHT_ALL_CHECKS, Optional< float > collisionHeight = { }) const
{
   if (!IsInMap(obj))
        return false;
    float ox, oy, oz;
    if (obj->GetTypeId() == TYPEID_PLAYER)
    {
        obj->GetPosition(ox, oy, oz);
        oz += obj->GetCollisionHeight();
    }
    else
        obj->GetHitSpherePointFor({ GetPositionX(), GetPositionY(), GetPositionZ() + (collisionHeight ? *collisionHeight : GetCollisionHeight()) }, ox, oy, oz);
    float x, y, z;
    if (GetTypeId() == TYPEID_PLAYER)
    {
        GetPosition(x, y, z);
        z += GetCollisionHeight();
    }
    else
        GetHitSpherePointFor({ obj->GetPositionX(), obj->GetPositionY(), obj->GetPositionZ() + obj->GetCollisionHeight() }, x, y, z, collisionHeight);
    return GetMap()->isInLineOfSight(x, y, z, ox, oy, oz, GetPhaseMask(), checks, ignoreFlags);
}
References GetCollisionHeight(), GetHitSpherePointFor(), GetMap(), GetPhaseMask(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::GetTypeId(), Map::isInLineOfSight(), IsInMap(), and TYPEID_PLAYER.
Referenced by npc_escortAI::AssistPlayerInCombatAgainst(), FollowerAI::AssistPlayerInCombatAgainst(), SmartAI::AssistPlayerInCombatAgainst(), Unit::AttackerStateUpdate(), Unit::CalcAbsorbResist(), Creature::CanStartAttack(), Spell::CheckCast(), Spell::CheckEffectTarget(), spell_hun_masters_call::DoCheckCast(), DynObjAura::FillTargetMap(), debug_commandscript::HandleDebugLoSCommand(), WorldSession::HandlePetActionHelper(), boss_halion::boss_halionAI::IsAnyPlayerValid(), boss_eye_of_cthun::MoveInLineOfSight(), Acore::CallOfHelpCreatureInRangeDo::operator()(), Acore::AnyAssistCreatureInRangeCheck::operator()(), Acore::NearestAssistCreatureInCreatureRangeCheck::operator()(), Acore::NearestAttackableNoTotemUnitInObjectRangeCheck::operator()(), NecroticPlagueTargetCheck::operator()(), FarthestTargetSelector::operator()(), ShadowTrapLKTargetSelector::operator()(), NonTankLKTargetSelector::operator()(), DefileTargetSelector::operator()(), MysticBuffetTargetFilter::operator()(), SmartScript::ProcessEvent(), Spell::SearchChainTargets(), Unit::SelectNearbyNoTotemTarget(), Unit::SelectNearbyTarget(), ScriptedAI::SelectTargetFromPlayerList(), CreatureAI::TriggerAlert(), Pet::Update(), boss_quartermaster_zigris::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), and boss_the_lich_king::boss_the_lich_kingAI::UpdateAI().
IsWorldObject()
bool WorldObject::IsWorldObject () const
{
    if (m_isWorldObject)
        return true;
    if (ToCreature() && ToCreature()->m_isTempWorldObject)
        return true;
    return false;
}
References m_isWorldObject, and Object::ToCreature().
Referenced by Map::AddToGrid(), DynamicObject::CreateDynamicObject(), ResetMap(), SetMap(), Map::~Map(), and ~WorldObject().
MovePosition()
void WorldObject::MovePosition (Position & pos, float dist, float angle)
{
    angle += GetOrientation();
    float destx, desty, destz, ground, floor;
    destx = pos.m_positionX + dist * cos(angle);
    desty = pos.m_positionY + dist * std::sin(angle);
    // Prevent invalid coordinates here, position is unchanged
    if (!Acore::IsValidMapCoord(destx, desty))
    {
        LOG_FATAL("entities.object", "WorldObject::MovePosition invalid coordinates X: {} and Y: {} were passed!", destx, desty);
        return;
    }
    ground = GetMapHeight(destx, desty, MAX_HEIGHT);
    floor = GetMapHeight(destx, desty, pos.m_positionZ);
    destz = std::fabs(ground - pos.m_positionZ) <= std::fabs(floor - pos.m_positionZ) ? ground : floor;
    float step = dist / 10.0f;
    for (uint8 j = 0; j < 10; ++j)
    {
        // do not allow too big z changes
        if (std::fabs(pos.m_positionZ - destz) > 6.0f)
        {
            destx -= step * cos(angle);
            desty -= step * std::sin(angle);
            ground = GetMapHeight(destx, desty, MAX_HEIGHT);
            floor = GetMapHeight(destx, desty, pos.m_positionZ);
            destz = std::fabs(ground - pos.m_positionZ) <= std::fabs(floor - pos.m_positionZ) ? ground : floor;
        }
        // we have correct destz now
        else
        {
            pos.Relocate(destx, desty, destz);
            break;
        }
    }
    Acore::NormalizeMapCoord(pos.m_positionX);
    Acore::NormalizeMapCoord(pos.m_positionY);
    UpdateGroundPositionZ(pos.m_positionX, pos.m_positionY, pos.m_positionZ);
    pos.SetOrientation(GetOrientation());
}
References GetMapHeight(), Position::GetOrientation(), Acore::IsValidMapCoord(), LOG_FATAL, Position::m_positionX, Position::m_positionY, Position::m_positionZ, MAX_HEIGHT, Acore::NormalizeMapCoord(), Position::Relocate(), Position::SetOrientation(), and UpdateGroundPositionZ().
Referenced by Spell::SelectImplicitDestDestTargets().
MovePositionToFirstCollision()
void WorldObject::MovePositionToFirstCollision (Position & pos, float dist, float angle)
{
    angle += GetOrientation();
    float destx, desty, destz;
    destx = pos.m_positionX + dist * cos(angle);
    desty = pos.m_positionY + dist * std::sin(angle);
    destz = pos.m_positionZ;
    if (!GetMap()->CheckCollisionAndGetValidCoords(this, pos.m_positionX, pos.m_positionY, pos.m_positionZ, destx, desty, destz, false))
        return;
    pos.SetOrientation(GetOrientation());
    pos.Relocate(destx, desty, destz);
}
References GetMap(), Position::GetOrientation(), Position::m_positionX, Position::m_positionY, Position::m_positionZ, Position::Relocate(), and Position::SetOrientation().
Referenced by FollowMovementGenerator< T >::DoUpdate(), Spell::EffectStuck(), VehicleDespawnEvent::Execute(), GetFirstCollisionPosition(), spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript::HandlePull(), MotionMaster::MoveKnockbackFrom(), Spell::SelectImplicitCasterDestTargets(), and Spell::SelectImplicitTargetDestTargets().
NotifyExecuted()
bool WorldObject::NotifyExecuted (uint16 f) const inline
{ return m_executed_notifies & f;}
References m_executed_notifies.
PlayDirectMusic()
void WorldObject::PlayDirectMusic (uint32 music_id, Player * target = nullptr)
{
    if (target)
    {
        target->SendDirectMessage(WorldPackets::Misc::PlayMusic(music_id).Write());
    }
    else
    {
        SendMessageToSet(WorldPackets::Misc::PlayMusic(music_id).Write(), true);
    }
}
References Player::SendDirectMessage(), and SendMessageToSet().
Referenced by debug_commandscript::HandleDebugPlayMusicCommand(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), and go_midsummer_music::go_midsummer_musicAI::UpdateAI().
PlayDirectSound()
void WorldObject::PlayDirectSound (uint32 sound_id, Player * target = nullptr)
{
    if (target)
        target->SendDirectMessage(WorldPackets::Misc::Playsound(sound_id).Write());
    else
        SendMessageToSet(WorldPackets::Misc::Playsound(sound_id).Write(), true);
}
References Player::SendDirectMessage(), and SendMessageToSet().
Referenced by boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), boss_yoggsaron::boss_yoggsaronAI::DoAction(), ScriptedAI::DoPlaySoundToSet(), Spell::EffectPlaySound(), AuraEffect::HandleAuraDummy(), debug_commandscript::HandleDebugPlaySoundCommand(), spell_yogg_saron_insane_periodic_trigger::spell_yogg_saron_insane_periodic_trigger_SpellScript::HandleDummyEffect(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InitFight(), boss_headless_horseman::JustDied(), boss_the_lich_king::boss_the_lich_kingAI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), boss_palehoof::boss_palehoofAI::JustDied(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustDied(), boss_headless_horseman::KilledUnit(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::KilledUnit(), spell_item_ashbringer::OnDummyEffect(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpellSounds(), go_bells::go_bellsAI::UpdateAI(), npc_eastvale_peasent::UpdateAI(), boss_headless_horseman::UpdateAI(), boss_headless_horseman_head::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_yoggsaron::boss_yoggsaronAI::UpdateAI(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::UpdateAI(), and brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI().
PlayDistanceSound()
void WorldObject::PlayDistanceSound (uint32 sound_id, Player * target = nullptr)
{
    if (target)
        target->SendDirectMessage(WorldPackets::Misc::PlayObjectSound(GetGUID(), sound_id).Write());
    else
        SendMessageToSet(WorldPackets::Misc::PlayObjectSound(GetGUID(), sound_id).Write(), true);
}
References Object::GetGUID(), Player::SendDirectMessage(), and SendMessageToSet().
Referenced by AuraEffect::HandleAuraDummy(), debug_commandscript::HandleDebugPlaySoundCommand(), and npc_cameron::UpdateAI().
ProcessPositionDataChanged()
void WorldObject::ProcessPositionDataChanged (PositionFullTerrainStatus const & data) protected virtual
Reimplemented in Unit.
{
    _zoneId = _areaId = data.areaId;
    if (AreaTableEntry const* area = sAreaTableStore.LookupEntry(_areaId))
        if (area->zone)
            _zoneId = area->zone;
    _outdoors   = data.outdoors;
    _floorZ     = data.floorZ;
    _liquidData = data.liquidInfo;
}
References _areaId, _floorZ, _liquidData, _outdoors, _zoneId, PositionFullTerrainStatus::areaId, PositionFullTerrainStatus::floorZ, PositionFullTerrainStatus::liquidInfo, PositionFullTerrainStatus::outdoors, and sAreaTableStore.
Referenced by Unit::ProcessPositionDataChanged(), and UpdatePositionData().
RemoveFromNotify()
void WorldObject::RemoveFromNotify (uint16 f) inline
{ m_notifyflags &= ~f; }
References m_notifyflags.
Referenced by Unit::ExecuteDelayedUnitAINotifyEvent(), Unit::ExecuteDelayedUnitRelocationEvent(), and Player::Update().
RemoveFromObjectUpdate()
void WorldObject::RemoveFromObjectUpdate () override virtual
Implements Object.
{
    GetMap()->RemoveUpdateObject(this);
}
References GetMap(), and Map::RemoveUpdateObject().
RemoveFromWorld()
void WorldObject::RemoveFromWorld () override virtual
Reimplemented from Object.
Reimplemented in Pet, Player, and Unit.
{
    if (!IsInWorld())
        return;
    DestroyForNearbyPlayers();
    Object::RemoveFromWorld();
}
References DestroyForNearbyPlayers(), Object::IsInWorld(), and Object::RemoveFromWorld().
Referenced by CleanupsBeforeDelete(), Corpse::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), Unit::RemoveFromWorld(), and Map::~Map().
ResetAllNotifies()
void WorldObject::ResetAllNotifies () inline
{ m_notifyflags = 0; m_executed_notifies = 0; }
References m_executed_notifies, and m_notifyflags.
ResetAllowedLooters()
void WorldObject::ResetAllowedLooters ()
{
    _allowedLooters.clear();
}
References _allowedLooters.
Referenced by GameObject::SetLootRecipient(), and Creature::SetLootRecipient().
ResetMap()
void WorldObject::ResetMap () virtual
Reimplemented in Player.
{
    ASSERT(m_currMap);
    ASSERT(!IsInWorld());
    if (IsWorldObject())
    {
        m_currMap->RemoveWorldObject(this);
    }
    sScriptMgr->OnWorldObjectResetMap(this);
    m_currMap = nullptr;
    //maybe not for corpse
    //m_mapId = 0;
    //m_InstanceId = 0;
}
References ASSERT, Object::IsInWorld(), IsWorldObject(), m_currMap, Map::RemoveWorldObject(), and sScriptMgr.
Referenced by Map::RemoveCorpse(), Map::RemoveFromMap(), Player::ResetMap(), Map::UnloadAll(), Map::~Map(), and ~WorldObject().
SaveRespawnTime()
virtual void WorldObject::SaveRespawnTime () inline virtual
Reimplemented in Creature, and GameObject.
{}
SelectNearestPlayer()
Player * WorldObject::SelectNearestPlayer (float distance = 0) const
{
    Player* target = nullptr;
    Acore::NearestPlayerInObjectRangeCheck checker(this, distance);
    Acore::PlayerLastSearcher<Acore::NearestPlayerInObjectRangeCheck> searcher(this, target, checker);
    Cell::VisitWorldObjects(this, searcher, distance);
    return target;
}
References Cell::VisitWorldObjects().
Referenced by boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::DoAction(), SmartScript::GetTargets(), npc_big_ooze::npc_big_oozeAI::IsSummonedBy(), npc_hor_lich_king::npc_hor_lich_kingAI::JustSummoned(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustSummoned(), npc_hover_disk::npc_hover_diskAI::MovementInform(), npc_omen::npc_omenAI::MovementInform(), npc_gunship_mage::npc_gunship_mageAI::MovementInform(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::npc_pos_martin_or_gorkun_secondAI(), spell_valkyr_ball_periodic_dummy::spell_valkyr_ball_periodic_dummyAuraScript::PrepareAuraScript(), boss_headless_horseman_pumpkin::Reset(), npc_ahnqiraji_critter::Reset(), npc_cork_gizelton::npc_cork_gizeltonAI::SetData(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::SetData(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SetData(), npc_argent_captainAI::SpellHit(), boss_headless_horseman_head::SpellHit(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::TombOfSevenEvent(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), npc_hallows_end_soh::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_amanitar_mushrooms::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), npc_big_ooze::npc_big_oozeAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::UpdateAI(), npc_hor_raging_ghoul::npc_hor_raging_ghoulAI::UpdateAI(), and npc_grimstone::npc_grimstoneAI::UpdateEscortAI().
SendMessageToSet() [1/2]
virtual void WorldObject::SendMessageToSet (WorldPacket const * data, bool self) const inline virtual
Reimplemented in Player.
{ if (IsInWorld()) SendMessageToSetInRange(data, GetVisibilityRange(), self, true); } // pussywizard!
References GetVisibilityRange(), Object::IsInWorld(), and SendMessageToSetInRange().
Referenced by Unit::_ExitVehicle(), AuraApplication::ClientUpdate(), Unit::DealMeleeDamage(), Spell::Delayed(), Unit::Dismount(), Spell::EffectDispel(), Spell::EffectInstaKill(), Spell::EffectStealBeneficialBuff(), npc_xt002_boombot::npc_xt002_boombotAI::Explode(), AuraEffect::HandleAuraSetVehicle(), Unit::HandleEmoteCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveUnRootAck(), WorldSession::HandleUpdateProjectilePosition(), npc_gunship::npc_gunshipAI::JustDied(), Movement::MoveSplineInit::Launch(), Unit::Mount(), boss_volkhan::boss_volkhanAI::MovementInform(), PlayDirectMusic(), PlayDirectSound(), PlayDistanceSound(), Unit::SendAttackStateUpdate(), Unit::SendChangeCurrentVictimOpcode(), Spell::SendChannelStart(), Spell::SendChannelUpdate(), Unit::SendClearTarget(), Unit::SendClearThreatListOpcode(), GameObject::SendCustomAnim(), Unit::SendEnergizeSpellLog(), Unit::SendHealSpellLog(), Spell::SendInterrupted(), Spell::SendLogExecute(), Unit::SendMeleeAttackStart(), Unit::SendMeleeAttackStop(), Unit::SendMonsterMove(), Unit::SendMovementFlagUpdate(), SendObjectDeSpawnAnim(), Unit::SendPeriodicAuraLog(), SendPlayMusic(), Unit::SendPlaySpellImpact(), Unit::SendPlaySpellVisual(), Unit::SendRemoveFromThreatListOpcode(), Unit::SendSpellDamageImmune(), Unit::SendSpellDamageResist(), Spell::SendSpellGo(), Unit::SendSpellMiss(), Unit::SendSpellNonMeleeDamageLog(), Spell::SendSpellStart(), Unit::SendTeleportPacket(), Unit::SendThreatListUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetFeatherFall(), Creature::SetHover(), Unit::SetPower(), Unit::SetRooted(), Unit::SetSpeed(), Creature::SetSwim(), Creature::SetWalk(), Creature::SetWaterWalking(), Movement::MoveSplineInit::Stop(), and boss_svala::boss_svalaAI::UpdateAI().
SendMessageToSet() [2/2]
virtual void WorldObject::SendMessageToSet (WorldPacket const * data, Player const * skipped_rcvr) const inline virtual
Reimplemented in Player.
{ if (IsInWorld()) SendMessageToSetInRange(data, GetVisibilityRange(), false, true, skipped_rcvr); } // pussywizard!
References GetVisibilityRange(), Object::IsInWorld(), and SendMessageToSetInRange().
SendMessageToSetInRange()
void WorldObject::SendMessageToSetInRange (WorldPacket const * data, float dist, bool , bool includeMargin = false, Player const * skipped_rcvr = nullptr) const virtual
Reimplemented in Player, and GameObject.
{
    dist += GetObjectSize();
    if (includeMargin)
        dist += VISIBILITY_COMPENSATION; // pussywizard: to ensure everyone receives all important packets
    Acore::MessageDistDeliverer notifier(this, data, dist, false, skipped_rcvr);
    Cell::VisitWorldObjects(this, notifier, dist);
}
References GetObjectSize(), VISIBILITY_COMPENSATION, and Cell::VisitWorldObjects().
Referenced by boss_yoggsaron_sara::boss_yoggsaron_saraAI::DoAction(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Playsound(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Playsound(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Playsound(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Say(), SendMessageToSet(), and CreatureTextMgr::SendNonChatPacket().
SendObjectDeSpawnAnim()
void WorldObject::SendObjectDeSpawnAnim (ObjectGuid guid)
{
    WorldPacket data(SMSG_GAMEOBJECT_DESPAWN_ANIM, 8);
    data << guid;
    SendMessageToSet(&data, true);
}
References SendMessageToSet(), and SMSG_GAMEOBJECT_DESPAWN_ANIM.
Referenced by GameObject::Delete(), GameObject::DespawnOrUnsummon(), DynamicObject::Remove(), and GameObject::Update().
SendPlayMusic()
void WorldObject::SendPlayMusic (uint32 Music, bool OnlySelf)
{
    WorldPacket data(SMSG_PLAY_MUSIC, 4);
    data << Music;
    if (OnlySelf && GetTypeId() == TYPEID_PLAYER)
        this->ToPlayer()->GetSession()->SendPacket(&data);
    else
        SendMessageToSet(&data, true); // ToSelf ignored in this case
}
References Player::GetSession(), Object::GetTypeId(), SendMessageToSet(), WorldSession::SendPacket(), SMSG_PLAY_MUSIC, Object::ToPlayer(), and TYPEID_PLAYER.
setActive()
void WorldObject::setActive (bool isActiveObject)
{
    if (m_isActive == on)
        return;
    if (GetTypeId() == TYPEID_PLAYER)
        return;
    m_isActive = on;
    if (on && !IsInWorld())
        return;
    Map* map = FindMap();
    if (!map)
        return;
    if (on)
    {
        if (GetTypeId() == TYPEID_UNIT)
            map->AddToActive(this->ToCreature());
        else if (GetTypeId() == TYPEID_DYNAMICOBJECT)
            map->AddToActive((DynamicObject*)this);
        else if (GetTypeId() == TYPEID_GAMEOBJECT)
            map->AddToActive((GameObject*)this);
    }
    else
    {
        if (GetTypeId() == TYPEID_UNIT)
            map->RemoveFromActive(this->ToCreature());
        else if (GetTypeId() == TYPEID_DYNAMICOBJECT)
            map->RemoveFromActive((DynamicObject*)this);
        else if (GetTypeId() == TYPEID_GAMEOBJECT)
            map->RemoveFromActive((GameObject*)this);
    }
}
References Map::AddToActive(), FindMap(), Object::GetTypeId(), Object::IsInWorld(), m_isActive, Map::RemoveFromActive(), Object::ToCreature(), TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by BossAI::_EnterCombat(), BossAI::_JustReachedHome(), Unit::AddPlayerToVision(), CinematicMgr::BeginCinematic(), boss_twilight_halion::boss_twilight_halionAI::boss_twilight_halionAI(), StaticTransport::Create(), DynamicObject::CreateDynamicObject(), TransportMgr::CreateTransport(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::DamageTaken(), npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::DoAction(), boss_krick::boss_krickAI::DoAction(), npc_xerestrasza::npc_xerestraszaAI::DoAction(), boss_sindragosa::boss_sindragosaAI::DoAction(), npc_spinestalker::npc_spinestalkerAI::DoAction(), npc_rimefang::npc_rimefangAI::DoAction(), npc_terenas_menethil::npc_terenas_menethilAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), boss_sister_svalna::boss_sister_svalnaAI::DoAction(), boss_hadronox::boss_hadronoxAI::DoAction(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::DoAction(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction(), boss_illidari_council::boss_illidari_councilAI::DoAction(), hyjalAI::DoOverrun(), boss_sartharion_dragonAI::EnterCombat(), boss_servant_quarters::boss_servant_quartersAI::EnterCombat(), boss_anubarak_trial::boss_anubarak_trialAI::EnterCombat(), boss_jaraxxus::boss_jaraxxusAI::EnterCombat(), boss_gormok::boss_gormokAI::EnterCombat(), boss_jormungarAI::EnterCombat(), boss_icehowl::boss_icehowlAI::EnterCombat(), boss_twin_valkyrAI::EnterCombat(), npc_stinky_icc::npc_stinky_iccAI::EnterCombat(), boss_lord_marrowgar::EnterCombat(), npc_precious_icc::npc_precious_iccAI::EnterCombat(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::EnterCombat(), boss_algalon_the_observer::boss_algalon_the_observerAI::EnterCombat(), boss_auriaya::boss_auriayaAI::EnterCombat(), boss_flame_leviathan::boss_flame_leviathanAI::EnterCombat(), boss_freya::boss_freyaAI::EnterCombat(), boss_vezax::boss_vezaxAI::EnterCombat(), boss_ignis::boss_ignisAI::EnterCombat(), boss_kologarn::boss_kologarnAI::EnterCombat(), boss_mimiron::boss_mimironAI::EnterCombat(), boss_thorim::boss_thorimAI::EnterCombat(), boss_xt002::boss_xt002AI::EnterCombat(), boss_the_lich_king::boss_the_lich_kingAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), boss_trollgore::boss_trollgoreAI::EnterCombat(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), boss_steelbreaker::boss_steelbreakerAI::EnterCombat(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::EnterCombat(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::EnterCombat(), boss_kologarn::boss_kologarnAI::EnterEvadeMode(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode(), ValithriaDespawner::Execute(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InitFight(), npc_cork_gizelton::npc_cork_gizeltonAI::Initialize(), boss_razorscale::boss_razorscaleAI::InitializeAI(), npc_lord_arete::npc_lord_areteAI::InitializeAI(), Totem::InitSummon(), npc_warden_mellichar::npc_warden_mellicharAI::JustDied(), boss_anubarak_trial::boss_anubarak_trialAI::JustReachedHome(), boss_jaraxxus::boss_jaraxxusAI::JustReachedHome(), boss_gormok::boss_gormokAI::JustReachedHome(), boss_jormungarAI::JustReachedHome(), boss_icehowl::boss_icehowlAI::JustReachedHome(), boss_twin_valkyrAI::JustReachedHome(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustReachedHome(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustReachedHome(), boss_prince_valanar_icc::boss_prince_valanarAI::JustReachedHome(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::JustReachedHome(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustReachedHome(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::JustReachedHome(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustReachedHome(), boss_steelbreaker::boss_steelbreakerAI::JustReachedHome(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::JustReachedHome(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustReachedHome(), boss_auriaya::boss_auriayaAI::JustReachedHome(), boss_flame_leviathan::boss_flame_leviathanAI::JustReachedHome(), boss_freya::boss_freyaAI::JustReachedHome(), boss_vezax::boss_vezaxAI::JustReachedHome(), boss_ignis::boss_ignisAI::JustReachedHome(), boss_mimiron::boss_mimironAI::JustReachedHome(), boss_thorim::boss_thorimAI::JustReachedHome(), boss_xt002::boss_xt002AI::JustReachedHome(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustRespawned(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::JustSummoned(), Creature::LoadCreaturesAddon(), boss_krik_thir::boss_krik_thirAI::MoveInLineOfSight(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::MovementInform(), boss_sindragosa::boss_sindragosaAI::MovementInform(), npc_spinestalker::npc_spinestalkerAI::MovementInform(), npc_rimefang::npc_rimefangAI::MovementInform(), npc_minigob_manabonk::npc_minigob_manabonkAI::npc_minigob_manabonkAI(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::npc_time_lost_proto_drakeAI(), npc_wg_spirit_guide::npc_wg_spirit_guideAI::npc_wg_spirit_guideAI(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnGameObjectCreate(), npc_koltira_deathweaver::OnQuestAccept(), Unit::RemovePlayerFromVision(), boss_nightbane::boss_nightbaneAI::Reset(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::Reset(), hyjalAI::Reset(), npc_q24545_lich_king::npc_q24545_lich_kingAI::Reset(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::Reset(), npc_akama_illidan::npc_akama_illidanAI::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), boss_svala::boss_svalaAI::SetData(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::SetData(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SetData(), npc_pos_leader::npc_pos_leaderAI::SetData(), Creature::setDeathState(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetGUID(), BattlegroundIC::SetupBattleground(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), npc_akama_illidan::npc_akama_illidanAI::sGossipSelect(), Battlefield::SpawnCreature(), Battlefield::SpawnGameObject(), hyjalAI::SummonCreature(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDies(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_xerestrasza::npc_xerestraszaAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), and npc_akama_illidan::npc_akama_illidanAI::WaypointReached().
SetAllowedLooters()
void WorldObject::SetAllowedLooters (GuidUnorderedSet const looters)
{
    _allowedLooters = looters;
}
References _allowedLooters.
Referenced by GameObject::SetLootRecipient().
SetLocationInstanceId()
void WorldObject::SetLocationInstanceId (uint32 _instanceId) inline protected
{ m_InstanceId = _instanceId; }
References m_InstanceId.
Referenced by Corpse::LoadCorpseFromDB().
SetLocationMapId()
void WorldObject::SetLocationMapId (uint32 _mapId) inline protected
{ m_mapId = _mapId; }
References WorldLocation::m_mapId.
Referenced by Corpse::LoadCorpseFromDB().
SetMap()
void WorldObject::SetMap (Map * map) virtual
Reimplemented in Player.
{
    ASSERT(map);
    ASSERT(!IsInWorld());
    if (m_currMap == map) // command add npc: first create, than loadfromdb
    {
        return;
    }
    if (m_currMap)
    {
        LOG_FATAL("entities.object", "WorldObject::SetMap: obj {} new map {} {}, old map {} {}", (uint32)GetTypeId(), map->GetId(), map->GetInstanceId(), m_currMap->GetId(), m_currMap->GetInstanceId());
        ABORT();
    }
    m_currMap = map;
    m_mapId = map->GetId();
    m_InstanceId = map->GetInstanceId();
    sScriptMgr->OnWorldObjectSetMap(this, map);
    if (IsWorldObject())
        m_currMap->AddWorldObject(this);
}
References ABORT, Map::AddWorldObject(), ASSERT, Map::GetId(), Map::GetInstanceId(), Object::GetTypeId(), Object::IsInWorld(), IsWorldObject(), LOG_FATAL, m_currMap, m_InstanceId, WorldLocation::m_mapId, and sScriptMgr.
Referenced by Map::AddCorpse(), Pet::Create(), Creature::Create(), GameObject::Create(), StaticTransport::Create(), DynamicObject::CreateDynamicObject(), TransportMgr::CreateTransport(), MotionTransport::DelayedTeleportTransport(), and Player::SetMap().
SetName()
void WorldObject::SetName (std::string const & newname) inline
{ m_name = newname; }
References m_name.
Referenced by npc_mograine::npc_mograineAI::AshbringerEvent(), GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), MotionTransport::CreateMoTrans(), Spell::EffectSummonPet(), WorldSession::HandlePetRename(), Creature::InitEntry(), Pet::LoadPetFromDB(), and Player::SummonPet().
SetNotified()
void WorldObject::SetNotified (uint16 f) inline
{ m_executed_notifies |= f;}
References m_executed_notifies.
SetPhaseMask()
void WorldObject::SetPhaseMask (uint32 newPhaseMask, bool update) virtual
Reimplemented in GameObject, and Unit.
{
    sScriptMgr->OnBeforeWorldObjectSetPhaseMask(this, m_phaseMask, newPhaseMask, m_useCombinedPhases, update);
    m_phaseMask = newPhaseMask;
    if (update && IsInWorld())
        UpdateObjectVisibility();
}
References Object::IsInWorld(), m_phaseMask, m_useCombinedPhases, sScriptMgr, and UpdateObjectVisibility().
Referenced by _Create(), Map::ConvertCorpseToBones(), Corpse::LoadCorpseFromDB(), GameObject::SetPhaseMask(), and Unit::SetPhaseMask().
SetPositionDataUpdate()
void WorldObject::SetPositionDataUpdate ()
{
    _updatePositionData = true;
    // Calls immediately for charmed units
    if (GetTypeId() == TYPEID_UNIT && ToUnit()->IsCharmedOwnedByPlayerOrPlayer())
        UpdatePositionData();
}
References _updatePositionData, Object::GetTypeId(), Object::ToUnit(), TYPEID_UNIT, and UpdatePositionData().
Referenced by Map::DynamicObjectRelocation(), and Map::GameObjectRelocation().
SetTransport()
void WorldObject::SetTransport (Transport * t) inline
{ m_transport = t; }
References m_transport.
Referenced by MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), DynamicObject::CleanupsBeforeDelete(), GameObject::CleanupsBeforeDelete(), MotionTransport::CleanupsBeforeDelete(), StaticTransport::CleanupsBeforeDelete(), Unit::CleanupsBeforeDelete(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), MotionTransport::RemovePassenger(), and StaticTransport::RemovePassenger().
SetVisibilityDistanceOverride()
void WorldObject::SetVisibilityDistanceOverride (VisibilityDistanceType type)
{
    ASSERT(type < VisibilityDistanceType::Max);
    if (GetTypeId() == TYPEID_PLAYER)
    {
        return;
    }
    m_visibilityDistanceOverride = VisibilityDistances[AsUnderlyingType(type)];
}
References ASSERT, AsUnderlyingType(), Object::GetTypeId(), m_visibilityDistanceOverride, TYPEID_PLAYER, and VisibilityDistances.
Referenced by GameObject::Create(), Totem::InitSummon(), and Creature::LoadCreaturesAddon().
SetWorldObject()
void WorldObject::SetWorldObject (bool apply)
{
    if (!IsInWorld())
        return;
    GetMap()->AddObjectToSwitchList(this, on);
}
References Map::AddObjectToSwitchList(), GetMap(), and Object::IsInWorld().
Referenced by Unit::AddPlayerToVision(), and Unit::RemovePlayerFromVision().
SetZoneScript()
void WorldObject::SetZoneScript ()
{
    if (Map* map = FindMap())
    {
        if (InstanceMap* instanceMap = map->ToInstanceMap())
            m_zoneScript = reinterpret_cast<ZoneScript*>(instanceMap->GetInstanceScript());
        else if (!map->IsBattlegroundOrArena())
        {
            uint32 zoneId = GetZoneId();
            if (Battlefield* bf = sBattlefieldMgr->GetBattlefieldToZoneId(zoneId))
                m_zoneScript = bf;
            else
                m_zoneScript = sOutdoorPvPMgr->GetZoneScript(zoneId);
        }
    }
}
References FindMap(), GetZoneId(), m_zoneScript, sBattlefieldMgr, sOutdoorPvPMgr, and Map::ToInstanceMap().
Referenced by GameObject::Create(), StaticTransport::Create(), and Creature::CreateFromProto().
SummonCreature() [1/2]
TempSummon * WorldObject::SummonCreature (uint32 id, const Position & pos, TempSummonType spwtype = TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime = 0, uint32 vehId = 0, SummonPropertiesEntry const * properties = nullptr) const
{
    if (Map* map = FindMap())
    {
        if (TempSummon* summon = map->SummonCreature(entry, pos, properties, duration, (WorldObject*) this))
        {
            summon->SetTempSummonType(spwtype);
            return summon;
        }
    }
    return nullptr;
}
References FindMap(), TempSummon::SetTempSummonType(), and SummonCreature().
Referenced by Battleground::AddCreature(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::AddPortals(), npc_mograine::npc_mograineAI::AshbringerEvent(), boss_xt002::boss_xt002AI::AttachHeart(), boss_kologarn::boss_kologarnAI::AttachLeftArm(), boss_kologarn::boss_kologarnAI::AttachRightArm(), CinematicMgr::BeginCinematic(), boss_eydis::boss_eydisAI::boss_eydisAI(), boss_fjola::boss_fjolaAI::boss_fjolaAI(), spell_quest_dragonmaw_race_generic::ChangeDest(), boss_headless_horseman::DamageTaken(), boss_algalon_the_observer::boss_algalon_the_observerAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::DoAction(), boss_victor_nefarius::boss_victor_nefariusAI::DoAction(), npc_thrall_warchief::npc_thrall_warchiefAI::DoAction(), boss_cthun::DoAction(), npc_costumed_orphan_matron::DoAction(), npc_arthas::npc_arthasAI::DoAction(), boss_palehoof::boss_palehoofAI::DoAction(), boss_bug_trio::DoFinalSpell(), hyjalAI::DoOverrun(), npc_rinji::npc_rinjiAI::DoSpawnAmbush(), npc_lakota_windsong::npc_lakota_windsongAI::DoSpawnBandits(), ScriptedAI::DoSpawnCreature(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), npc_paoka_swiftmountain::npc_paoka_swiftmountainAI::DoSpawnWyvern(), CreatureAI::DoSummon(), npc_time_rift::npc_time_riftAI::DoSummonAtRift(), CreatureAI::DoSummonFlyer(), npc_ranshalla::npc_ranshallaAI::DoSummonPriestess(), npc_muglash::npc_muglashAI::DoWaveSummon(), Spell::EffectDummy(), Spell::EffectSummonType(), npc_giant_claw_tentacle::Emerge(), boss_mandokir::boss_mandokirAI::EnterCombat(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::EnterCombat(), boss_anubarak_trial::boss_anubarak_trialAI::EnterCombat(), boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat(), boss_warbringer_omrogg::boss_warbringer_omroggAI::EnterCombat(), boss_onyxia::EnterCombat(), boss_ossirian::EnterCombat(), boss_novos::boss_novosAI::EnterCombat(), DelayedSummonEvent::Execute(), IceTombSummonEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::FinishFight(), boss_janalai::boss_janalaiAI::FireWall(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), go_brazier_of_madness::GossipHello(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello(), spell_rotface_unstable_ooze_explosion_init::spell_rotface_unstable_ooze_explosion_init_SpellScript::HandleCast(), spell_commander_sarannis_summon_reinforcements::spell_commander_sarannis_summon_reinforcements_SpellScript::HandleCast(), debug_commandscript::HandleDebugSpawnVehicleCommand(), spell_dred_raptor_call::spell_dred_raptor_call_SpellScript::HandleDummy(), spell_q11010_q11102_q11023_choose_loc::HandleDummy(), spell_herald_volzaj_insanity::HandleDummyEffect(), spell_midsummer_torch_quest::HandleEffectApply(), spell_gen_haunted_aura::HandleEffectPeriodic(), spell_dtk_raise_dead::spell_dtk_raise_dead_AuraScript::HandleEffectRemove(), spell_icc_geist_alarm::spell_icc_geist_alarm_SpellScript::HandleEvent(), mmaps_commandscript::HandleMmapPathCommand(), npc_commandscript::HandleNpcAddTempSpawnCommand(), spell_gen_haunted::HandleOnEffectHit(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), spell_kaelthas_summon_nether_vapor::spell_kaelthas_summon_nether_vapor_SpellScript::HandleScriptEffect(), spell_q12478_frostmourne_cavern::spell_q12478_frostmourne_cavern_SpellScript::HandleSendEvent(), spell_item_draenic_pale_ale::HandleSummon(), spell_q11322_q11317_the_cleansing::if(), boss_priestess_delrissa::boss_priestess_delrissaAI::InitializeAI(), npc_general_andorov::InitializeAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::InitializeAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::InitializeAI(), boss_prince_valanar_icc::boss_prince_valanarAI::InitializeAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::InitializeAI(), brann_bronzebeard::brann_bronzebeardAI::InitializeEvent(), boss_moroes::boss_moroesAI::InitializeGuests(), Vehicle::InstallAccessory(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::InstanceCleanup(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), boss_halycon::boss_halyconAI::JustDied(), boss_naxxramas_misc::boss_naxxramas_miscAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), boss_exarch_maladaar::boss_exarch_maladaarAI::JustDied(), boss_jarien::JustDied(), boss_sothos::JustDied(), boss_felmyst::boss_felmystAI::JustDied(), npc_webbed_creature::npc_webbed_creatureAI::JustDied(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustDied(), boss_halion::boss_halionAI::JustSummoned(), npc_the_scourge_cauldron::npc_the_scourge_cauldronAI::MoveInLineOfSight(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), npc_black_knight_graveyard::npc_black_knight_graveyardAI::MoveInLineOfSight(), deathblow_to_the_legion_trigger::deathblow_to_the_legion_triggerAI::MoveInLineOfSight(), boss_captain_skarloc::boss_captain_skarlocAI::MovementInform(), npc_twilight_volunteer::MovementInform(), boss_malygos::boss_malygosAI::MovementInform(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::MovementInform(), boss_flame_leviathan_safety_container::boss_flame_leviathan_safety_containerAI::MovementInform(), npc_claw_tentacle::npc_claw_tentacle(), npc_eye_tentacle::npc_eye_tentacle(), npc_giant_claw_tentacle::npc_giant_claw_tentacle(), npc_giant_eye_tentacle::npc_giant_eye_tentacle(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::npc_ulduar_flames_initialAI(), npc_vh_void_sentry::npc_vh_void_sentryAI::npc_vh_void_sentryAI(), go_gong_of_bethekk::OnGossipHello(), go_resonite_cask::OnGossipHello(), go_inconspicuous_mine_car::OnGossipHello(), go_southfury_moonstone::OnGossipHello(), go_ethereum_prison::OnGossipHello(), go_ethereum_stasis::OnGossipHello(), go_sacred_fire_of_life::OnGossipHello(), go_arcane_prison::OnGossipHello(), go_hive_pod::OnGossipHello(), go_mistwhisper_treasure::OnGossipHello(), npc_grandmother::OnGossipSelect(), npc_natrualist_bite::OnGossipSelect(), go_ahune_ice_stone::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::OnPlayerEnter(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter(), npc_maghar_captive::OnQuestAccept(), npc_karynaku::OnQuestAccept(), go_crystalline_tear::OnQuestAccept(), go_loosely_turned_soil::OnQuestReward(), spell_xt002_gravity_bomb_aura::spell_xt002_gravity_bomb_aura_AuraScript::OnRemove(), AreaTrigger_at_scent_larkorwi::OnTrigger(), AreaTrigger_at_nats_landing::OnTrigger(), AreaTrigger_at_sentry_point::OnTrigger(), AreaTrigger_at_area_52_entrance::OnTrigger(), at_malfurion_stormrage::OnTrigger(), at_twilight_grove::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), item_nether_wraith_beacon::OnUse(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript(), spell_hor_gunship_cannon_fire::spell_hor_gunship_cannon_fireAuraScript::PrepareAuraScript(), spell_ignis_scorch::spell_ignis_scorch_AuraScript::PrepareAuraScript(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareChamberIllusion(), npc_barnes::npc_barnesAI::PrepareEncounter(), npc_dark_iron_attack_generator::PrepareEvent(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareIceCrownIllusion(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareStormwindIllusion(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::PrepareSummons(), SmartScript::ProcessAction(), boss_flame_leviathan::boss_flame_leviathanAI::RadioSay(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), boss_majordomo::boss_majordomoAI::Reset(), npc_image_of_medivh::npc_image_of_medivhAI::Reset(), boss_garaxxas::boss_garaxxasAI::Reset(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::Reset(), npc_coren_direbrew::Reset(), boss_infinite_corruptor::boss_infinite_corruptorAI::Reset(), boss_hadronox::boss_hadronoxAI::Reset(), boss_krik_thir::boss_krik_thirAI::Reset(), boss_anubarak_trial::boss_anubarak_trialAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::Reset(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::Reset(), boss_skadi::boss_skadiAI::Reset(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::Reset(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::Reset(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::Reset(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), npc_firework::npc_fireworkAI::Reset(), boss_emalon::boss_emalonAI::ResetSummons(), hyjalAI::Retreat(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SaveKeepers(), boss_cthun::ScheduleTasks(), boss_svala::boss_svalaAI::SetData(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::SetData(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::SetGUID(), npc_kurenai_captive::npc_kurenai_captiveAI::SetGUID(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpawnAdds(), boss_zuljin::boss_zuljinAI::SpawnAdds(), boss_thorim::boss_thorimAI::SpawnAllNPCs(), boss_thorim::boss_thorimAI::SpawnArenaNPCs(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnClouds(), boss_venoxis::boss_venoxisAI::SpawnCobras(), boss_selin_fireheart::boss_selin_fireheartAI::SpawnCrystals(), boss_skadi_grauf::boss_skadi_graufAI::SpawnFlameTriggers(), boss_kelthuzad::boss_kelthuzadAI::SpawnHelpers(), boss_razuvious::boss_razuviousAI::SpawnHelpers(), boss_hodir::boss_hodirAI::SpawnHelpers(), boss_skadi_grauf::boss_skadi_graufAI::SpawnHelpers(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SpawnMobsInRoom(), boss_ossirian::SpawnNextCrystal(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnTentacle(), npc_arthas::npc_arthasAI::SpawnTimeRift(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::spawnVoidTraveler(), boss_freya::boss_freyaAI::SpawnWave(), npc_grimstone::npc_grimstoneAI::SpawnWave(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), npc_thrall_bfu::npc_thrall_bfuAI::SpawnWave(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnWeels(), boss_urom::boss_uromAI::SpellHit(), boss_headless_horseman_pumpkin::SpellHit(), boss_gothik::boss_gothikAI::SpellHit(), boss_sister_svalna::boss_sister_svalnaAI::SpellHitTarget(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::SpellHitTarget(), boss_freya::boss_freyaAI::SpellHitTarget(), boss_lethon::boss_lethonAI::SpellHitTarget(), boss_grobbulus::boss_grobbulusAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_ionar::boss_ionarAI::Split(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::SpreadFlame(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::Summon(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::SummonAcolyte(), npc_eris_hevenfire::npc_eris_hevenfireAI::SummonArchers(), boss_malchezaar::boss_malchezaarAI::SummonAxes(), npc_grimstone::npc_grimstoneAI::SummonBoss(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), boss_anzu::boss_anzuAI::SummonBroods(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonChannelers(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::SummonChannelers(), hyjalAI::SummonCreature(), SummonCreature(), SummonCreatureGroup(), PassengerController::SummonCreatures(), brann_bronzebeard::brann_bronzebeardAI::SummonCreatures(), pyrewood_ambush::pyrewood_ambushAI::SummonCreatureWithRandomTarget(), SummonCroneIfReady(), boss_anubrekhan::boss_anubrekhanAI::SummonCryptGuards(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SummonDeathOrbs(), boss_archimonde::boss_archimondeAI::SummonDoomfire(), boss_sjonnir::boss_sjonnirAI::SummonDwarfes(), boss_cthun::SummonedCreatureDies(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::SummonedCreatureDies(), boss_jedoga_shadowseeker::SummonedCreatureDies(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonFrostwardens(), npc_air_force_bots::npc_air_force_botsAI::SummonGuard(), boss_fankriss::SummonHatchlingWaves(), boss_kelthuzad::boss_kelthuzadAI::SummonHelper(), boss_noth::boss_nothAI::SummonHelper(), npc_cork_gizelton::npc_cork_gizeltonAI::SummonHelpers(), boss_faerlina::boss_faerlinaAI::SummonHelpers(), boss_anub_arak::boss_anub_arakAI::SummonHelpers(), boss_gothik::boss_gothikAI::SummonHelpers(), instance_zulaman::instance_zulaman_InstanceMapScript::SummonHostage(), boss_yoggsaron::boss_yoggsaronAI::SummonImmortalGuardian(), boss_malchezaar::boss_malchezaarAI::SummonInfernal(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::SummonInfernal(), boss_sartharion::boss_sartharionAI::SummonLavaWaves(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::SummonMechanics(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::SummonMinions(), boss_amanitar::SummonMushroom(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::SummonNextWave(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::SummonNextWave(), go_wind_stone::go_wind_stoneAI::SummonNPC(), npc_medivh_bm::npc_medivh_bmAI::SummonOrcs(), npc_eris_hevenfire::npc_eris_hevenfireAI::SummonPeasants(), npc_xt002_heart::npc_xt002_heartAI::SummonPiles(), boss_netherspite::boss_netherspiteAI::SummonPortals(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::summonPortals(), npc_coren_direbrew::SummonSister(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonSpiders(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::SummonSpirits(), boss_sartharion::boss_sartharionAI::SummonStartingTriggers(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), boss_dorothee::boss_dorotheeAI::SummonTito(), SummonTrigger(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), boss_balinda::boss_balindaAI::UpdateAI(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), boss_julianne::boss_julianneAI::UpdateAI(), npc_scarlet_cannon::npc_scarlet_cannonAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), boss_jeklik::UpdateAI(), npc_dark_iron_attack_generator::UpdateAI(), npc_dark_iron_attack_mole_machine::UpdateAI(), npc_pilgrims_bounty_chair::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_medivh_bm::npc_medivh_bmAI::UpdateAI(), boss_onyxia::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_phantom_mage::npc_phantom_mageAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), boss_slad_ran::boss_slad_ranAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), boss_anubrekhan::boss_anubrekhanAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_naxxramas_misc::boss_naxxramas_miscAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), npc_hodirs_fury::npc_hodirs_furyAI::UpdateAI(), npc_mimirons_inferno::npc_mimirons_infernoAI::UpdateAI(), npc_thorims_hammer::npc_thorims_hammerAI::UpdateAI(), npc_storm_beacon_spawn::npc_storm_beacon_spawnAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_sif::boss_thorim_sifAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_keleseth::boss_kelesethAI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), boss_toravon::boss_toravonAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_archmage_landalock::npc_archmage_landalockAI::UpdateAI(), npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), boss_exarch_maladaar::boss_exarch_maladaarAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::UpdateAI(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), npc_commander_dawnforge::npc_commander_dawnforgeAI::UpdateAI(), npc_doctor::npc_doctorAI::UpdateAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::UpdateAI(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::UpdateEscortAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), boss_netherspite::boss_netherspiteAI::UpdatePortals(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::WaypointReached(), npc_arthas::npc_arthasAI::WaypointReached(), npc_barnes::npc_barnesAI::WaypointReached(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::WaypointReached(), npc_ranger_lilatha::WaypointReached(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::WaypointReached(), npc_daphne_stilwell::npc_daphne_stilwellAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), npc_kaya_flathoof::npc_kaya_flathoofAI::WaypointReached(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::WaypointReached(), npc_ame::npc_ameAI::WaypointReached(), npc_emily::npc_emilyAI::WaypointReached(), npc_maghar_captive::npc_maghar_captiveAI::WaypointReached(), npc_kurenai_captive::npc_kurenai_captiveAI::WaypointReached(), and npc_bessy::npc_bessyAI::WaypointReached().
SummonCreature() [2/2]
TempSummon * WorldObject::SummonCreature (uint32 id, float x, float y, float z, float ang = 0, TempSummonType spwtype = TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime = 0, SummonPropertiesEntry const * properties = nullptr)
{
    if (!x && !y && !z)
    {
        GetClosePoint(x, y, z, GetObjectSize());
        ang = GetOrientation();
    }
    Position pos;
    pos.Relocate(x, y, z, ang);
    return SummonCreature(id, pos, spwtype, despwtime, 0, properties);
}
References GetClosePoint(), GetObjectSize(), Position::GetOrientation(), Position::Relocate(), and SummonCreature().
SummonCreatureGroup()
void WorldObject::SummonCreatureGroup (uint8 group, std::list< TempSummon * > * list = nullptr)
Summons group of creatures. Should be called only by instances of Creature and GameObject classes.
Parameters
group Id of group to summon.
list List to store pointers to summoned creatures.
{
    ASSERT((GetTypeId() == TYPEID_GAMEOBJECT || GetTypeId() == TYPEID_UNIT) && "Only GOs and creatures can summon npc groups!");
    std::vector<TempSummonData> const* data = sObjectMgr->GetSummonGroup(GetEntry(), GetTypeId() == TYPEID_GAMEOBJECT ? SUMMONER_TYPE_GAMEOBJECT : SUMMONER_TYPE_CREATURE, group);
    if (!data)
        return;
    for (std::vector<TempSummonData>::const_iterator itr = data->begin(); itr != data->end(); ++itr)
        if (TempSummon* summon = SummonCreature(itr->entry, itr->pos, itr->type, itr->time))
            if (list)
                list->push_back(summon);
}
References ASSERT, Object::GetEntry(), Object::GetTypeId(), sObjectMgr, SummonCreature(), SUMMONER_TYPE_CREATURE, SUMMONER_TYPE_GAMEOBJECT, TYPEID_GAMEOBJECT, and TYPEID_UNIT.
Referenced by boss_eye_of_cthun::DoAction(), boss_majordomo::boss_majordomoAI::InitializeAI(), boss_taldaram::InitializeAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustRespawned(), boss_apothecary_hummel::boss_apothecary_hummelAI::Reset(), boss_jedoga_shadowseeker::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::SummonWave(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), and npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI().
SummonGameObject()
GameObject * WorldObject::SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport = true, GOSummonType summonType = GO_SUMMON_TIMED_OR_CORPSE_DESPAWN)
{
    if (!IsInWorld())
        return nullptr;
    GameObjectTemplate const* goinfo = sObjectMgr->GetGameObjectTemplate(entry);
    if (!goinfo)
    {
        LOG_ERROR("sql.sql", "Gameobject template {} not found in database!", entry);
        return nullptr;
    }
    Map* map = GetMap();
    GameObject* go = sObjectMgr->IsGameObjectStaticTransport(entry) ? new StaticTransport() : new GameObject();
    if (!go->Create(map->GenerateLowGuid<HighGuid::GameObject>(), entry, map, GetPhaseMask(), x, y, z, ang, G3D::Quat(rotation0, rotation1, rotation2, rotation3), 100, GO_STATE_READY))
    {
        delete go;
        return nullptr;
    }
    go->SetRespawnTime(respawnTime);
    // Xinef: if gameobject is temporary, set custom spellid
    if (respawnTime)
        go->SetSpellId(1);
    if (GetTypeId() == TYPEID_PLAYER || (GetTypeId() == TYPEID_UNIT && summonType == GO_SUMMON_TIMED_OR_CORPSE_DESPAWN)) //not sure how to handle this
        ToUnit()->AddGameObject(go);
    else
        go->SetSpawnedByDefault(false);
    map->AddToMap(go, checkTransport);
    return go;
}
References Unit::AddGameObject(), Map::AddToMap(), GameObject::Create(), Map::GenerateLowGuid(), GetMap(), GetPhaseMask(), Object::GetTypeId(), GO_STATE_READY, GO_SUMMON_TIMED_OR_CORPSE_DESPAWN, Object::IsInWorld(), LOG_ERROR, GameObject::SetRespawnTime(), GameObject::SetSpawnedByDefault(), GameObject::SetSpellId(), sObjectMgr, Object::ToUnit(), TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by boss_freya::boss_freyaAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::DoAction(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::DoAction(), npc_medivh_bm::npc_medivh_bmAI::DoAction(), hyjalAI::DoOverrun(), IceTombSummonEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), HandleBothDead(), spell_gordunni_trap::spell_gordunni_trap_SpellScript::HandleDummy(), spell_item_crystal_prison_dummy_dnd::HandleDummy(), spell_q12014_steady_as_a_rock::HandleFinish(), gobject_commandscript::HandleGameObjectAddTempCommand(), boss_sapphiron::boss_sapphironAI::InitializeAI(), boss_eregos::boss_eregosAI::JustDied(), boss_kologarn::boss_kologarnAI::JustDied(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), npc_midsummer_bonfire::npc_midsummer_bonfire(), spell_pagles_point_cast::OnEffect(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), npc_zulaman_hostage::OnGossipSelect(), spell_silithyst::OnRemove(), SmartScript::ProcessAction(), npc_brewfest_super_brew_trigger::Reset(), boss_ossirian::Reset(), npc_crystal_spike::npc_crystal_spikeAI::Reset(), boss_freya_nature_bomb::boss_freya_nature_bombAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), boss_ossirian::SpawnNextCrystal(), hyjalAI::SpawnVeins(), npc_thrall_bfu::npc_thrall_bfuAI::SpawnWave(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_dark_iron_attack_mole_machine::UpdateAI(), hyjalAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), npc_alexstrasza::npc_alexstraszaAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::UpdateAI(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), and npc_engineer_helice::npc_engineer_heliceAI::WaypointReached().
SummonTrigger()
Creature * WorldObject::SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel = false, CreatureAI *(*)(Creature *) GetAI = nullptr)
{
    TempSummonType summonType = (duration == 0) ? TEMPSUMMON_DEAD_DESPAWN : TEMPSUMMON_TIMED_DESPAWN;
    Creature* summon = SummonCreature(WORLD_TRIGGER, x, y, z, ang, summonType, duration);
    if (!summon)
        return nullptr;
    //summon->SetName(GetName());
    if (setLevel && (GetTypeId() == TYPEID_PLAYER || GetTypeId() == TYPEID_UNIT))
    {
        summon->SetFaction(((Unit*)this)->GetFaction());
        summon->SetLevel(((Unit*)this)->getLevel());
    }
    // Xinef: correctly set phase mask in case of gameobjects
    summon->SetPhaseMask(GetPhaseMask(), false);
    if (GetAI)
        summon->AIM_Initialize(GetAI(summon));
    return summon;
}
References Creature::AIM_Initialize(), GetPhaseMask(), Object::GetTypeId(), Unit::SetFaction(), Unit::SetLevel(), Unit::SetPhaseMask(), SummonCreature(), TEMPSUMMON_DEAD_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, TYPEID_PLAYER, TYPEID_UNIT, and WORLD_TRIGGER.
Referenced by GameObject::CastSpell(), boss_kiljaeden::boss_kiljaedenAI::EmpowerOrb(), spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript::HandleScriptEffect(), boss_akilzon::boss_akilzonAI::HandleStormSequence(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), SmartScript::ProcessAction(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Say(), Map::ScriptsProcess(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_headless_horseman::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), go_flames::go_flamesAI::UpdateAI(), and go_heat::go_heatAI::UpdateAI().
Update()
void WorldObject::Update (uint32 time_diff) virtual
Reimplemented in Pet, MotionTransport, StaticTransport, DynamicObject, GameObject, Creature, TempSummon, Puppet, Player, Totem, and Unit.
{
    sScriptMgr->OnWorldObjectUpdate(this, time_diff);
}
References sScriptMgr.
UpdateAllowedPositionZ()
void WorldObject::UpdateAllowedPositionZ (float x, float y, float & z, float * groundZ = nullptr) const
{
    if (GetTransport())
    {
        if (groundZ)
            *groundZ = z;
        return;
    }
    if (Unit const* unit = ToUnit())
    {
        if (!unit->CanFly())
        {
            Creature const* c = unit->ToCreature();
            bool canSwim = c ? c->CanSwim() : true;
            float ground_z = z;
            float max_z;
            if (canSwim)
                max_z = GetMapWaterOrGroundLevel(x, y, z, &ground_z);
            else
                max_z = ground_z = GetMapHeight(x, y, z);
            if (max_z > INVALID_HEIGHT)
            {
                if (canSwim && unit->GetMap()->IsInWater(unit->GetPhaseMask(), x, y, max_z - Z_OFFSET_FIND_HEIGHT, unit->GetCollisionHeight()))
                {
                    // do not allow creatures to walk on
                    // water level while swimming
                    max_z = std::max(max_z - GetMinHeightInWater(), ground_z);
                }
                else
                {
                    // hovering units cannot go below their hover height
                    float hoverOffset = unit->GetHoverHeight();
                    max_z += hoverOffset;
                    ground_z += hoverOffset;
                }
                if (z > max_z)
                    z = max_z;
                else if (z < ground_z)
                    z = ground_z;
            }
            if (groundZ)
                *groundZ = ground_z;
        }
        else
        {
            float ground_z = GetMapHeight(x, y, z) + unit->GetHoverHeight();
            if (z < ground_z)
                z = ground_z;
            if (groundZ)
               *groundZ = ground_z;
        }
    }
    else
    {
        float ground_z = GetMapHeight(x, y, z);
        if (ground_z > INVALID_HEIGHT)
            z = ground_z;
        if (groundZ)
            *groundZ = ground_z;
    }
}
References Unit::CanFly(), Creature::CanSwim(), Unit::GetCollisionHeight(), Unit::GetHoverHeight(), GetMap(), GetMapHeight(), GetMapWaterOrGroundLevel(), GetMinHeightInWater(), GetPhaseMask(), GetTransport(), INVALID_HEIGHT, Map::IsInWater(), Object::ToCreature(), Object::ToUnit(), and Z_OFFSET_FIND_HEIGHT.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), Map::CheckCollisionAndGetValidCoords(), GetContactPoint(), GetNearPoint(), Unit::GetRandomContactPoint(), PathGenerator::NormalizePath(), CharmInfo::SaveStayPosition(), spell_valanar_kinetic_bomb_summon::spell_valanar_kinetic_bomb_summon_SpellScript::SelectDest(), Unit::SetHover(), and WaypointMovementGenerator< Creature >::StartMove().
UpdateGroundPositionZ()
void WorldObject::UpdateGroundPositionZ (float x, float y, float & z) const
{
    float new_z = GetMapHeight(x, y, z);
    if (new_z > INVALID_HEIGHT)
        z = new_z + (isType(TYPEMASK_UNIT) ? static_cast<Unit const*>(this)->GetHoverHeight() : 0.0f);
}
References GetMapHeight(), INVALID_HEIGHT, Object::isType(), and TYPEMASK_UNIT.
Referenced by IceTombSummonEvent::Execute(), GetChargeContactPoint(), GetRandomPoint(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::IsSummonedBy(), CreatureGroup::LeaderMoveTo(), MovePosition(), spell_putricide_slime_puddle_spawn::spell_putricide_slime_puddle_spawn_SpellScript::SelectDest(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::SelectDest(), and boss_sindragosa::boss_sindragosaAI::UpdateAI().
UpdateObjectVisibility()
void WorldObject::UpdateObjectVisibility (bool forced = true, bool fromUpdate = false) virtual
Reimplemented in Player, and Unit.
{
    //updates object's visibility for nearby players
    Acore::VisibleChangesNotifier notifier(*this);
    Cell::VisitWorldObjects(this, notifier, GetVisibilityRange());
}
References GetVisibilityRange(), and Cell::VisitWorldObjects().
Referenced by Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), SetPhaseMask(), GameObject::SetRespawnTime(), GameObject::Update(), and Unit::UpdateObjectVisibility().
UpdatePositionData()
void WorldObject::UpdatePositionData ()
{
    _updatePositionData = false;
    PositionFullTerrainStatus data;
    GetMap()->GetFullTerrainStatusForPosition(GetPhaseMask(), GetPositionX(), GetPositionY(), GetPositionZ(), GetCollisionHeight(), data);
    ProcessPositionDataChanged(data);
}
References _updatePositionData, GetCollisionHeight(), Map::GetFullTerrainStatusForPosition(), GetMap(), GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), and ProcessPositionDataChanged().
Referenced by Map::ConvertCorpseToBones(), GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), Player::CreateCorpse(), DynamicObject::CreateDynamicObject(), Map::CreatureRelocation(), GetAreaId(), GetFloorZ(), GetLiquidData(), GetZoneAndAreaId(), GetZoneId(), WorldSession::HandleMoveWorldportAck(), IsOutdoors(), Map::LoadCorpseData(), Player::LoadFromDB(), Pet::LoadPetFromDB(), Map::PlayerRelocation(), and SetPositionDataUpdate().
Member Data Documentation
_allowedLooters
GuidUnorderedSet WorldObject::_allowedLooters private
Referenced by AddAllowedLooter(), GetAllowedLooters(), HasAllowedLooter(), ResetAllowedLooters(), and SetAllowedLooters().
_areaId
uint32 WorldObject::_areaId protected
Referenced by AddToWorld(), GetAreaId(), GetZoneAndAreaId(), and ProcessPositionDataChanged().
_floorZ
float WorldObject::_floorZ protected
Referenced by GetFloorZ(), and ProcessPositionDataChanged().
_liquidData
LiquidData WorldObject::_liquidData protected
Referenced by GetLiquidData(), and ProcessPositionDataChanged().
_outdoors
bool WorldObject::_outdoors protected
Referenced by IsOutdoors(), and ProcessPositionDataChanged().
_updatePositionData
bool WorldObject::_updatePositionData protected
Referenced by GetAreaId(), GetFloorZ(), GetLiquidData(), GetZoneAndAreaId(), GetZoneId(), IsOutdoors(), SetPositionDataUpdate(), and UpdatePositionData().
_zoneId
uint32 WorldObject::_zoneId protected
Referenced by AddToWorld(), GetZoneAndAreaId(), GetZoneId(), and ProcessPositionDataChanged().
elunaEvents
ElunaEventProcessor* WorldObject::elunaEvents
LastUsedScriptID
uint32 WorldObject::LastUsedScriptID
Referenced by Creature::Create(), GameObject::Create(), StaticTransport::Create(), WorldSession::HandleGossipSelectOptionOpcode(), and instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate().
m_currMap
Map* WorldObject::m_currMap private
Referenced by FindMap(), GetMap(), ResetMap(), SetMap(), and ~WorldObject().
m_executed_notifies
uint16 WorldObject::m_executed_notifies private
Referenced by NotifyExecuted(), ResetAllNotifies(), and SetNotified().
m_InstanceId
uint32 WorldObject::m_InstanceId private
Referenced by GetInstanceId(), SetLocationInstanceId(), and SetMap().
m_invisibility
FlaggedValuesArray32<int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES> WorldObject::m_invisibility
Referenced by CanDetectInvisibilityOf(), CanSeeOrDetect(), GameObject::Create(), StaticTransport::Create(), AuraEffect::HandleModInvisibility(), and spell_alar_ember_blast_death::spell_alar_ember_blast_death_AuraScript::OnApply().
m_invisibilityDetect
FlaggedValuesArray32<int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES> WorldObject::m_invisibilityDetect
Referenced by CanDetectInvisibilityOf(), AuraEffect::HandleAuraModFakeInebriation(), AuraEffect::HandleModInvisibilityDetect(), and Player::SetDrunkValue().
m_isActive
bool WorldObject::m_isActive protected
Referenced by isActiveObject(), Player::Player(), and setActive().
m_isFarVisible
bool WorldObject::m_isFarVisible protected
Referenced by IsFarVisible().
m_isWorldObject
const bool WorldObject::m_isWorldObject protected
Referenced by IsPermanentWorldObject(), and IsWorldObject().
m_movementInfo
MovementInfo WorldObject::m_movementInfo
Referenced by _IsWithinDist(), Unit::AddExtraUnitMovementFlag(), Vehicle::AddPassenger(), MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), Unit::AddUnitMovementFlag(), Unit::BuildMovementPacket(), Object::BuildMovementUpdate(), WorldSession::BuildPartyMemberStatsChangedPacket(), Player::CanFly(), DynamicObject::CleanupsBeforeDelete(), GameObject::CleanupsBeforeDelete(), MotionTransport::CleanupsBeforeDelete(), StaticTransport::CleanupsBeforeDelete(), Unit::CleanupsBeforeDelete(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), MotionTransport::DelayedTeleportTransport(), Unit::DisableSpline(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), Unit::GetExtraUnitMovementFlags(), GetTransOffsetO(), GetTransOffsetX(), GetTransOffsetY(), GetTransOffsetZ(), GetTransSeat(), GetTransTime(), Unit::GetUnitMovementFlags(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleDismissControlledVehicle(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveNotActiveMover(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveSetCanFlyAckOpcode(), WorldSession::HandleMoveTimeSkippedOpcode(), WorldSession::HandleMoveUnRootAck(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandleRequestPartyMemberStatsOpcode(), Unit::HasExtraUnitMovementFlag(), Unit::HasUnitMovementFlag(), Unit::IsFalling(), Unit::IsFlying(), Creature::IsFreeToMove(), Unit::IsHovering(), Unit::IsLevitating(), Unit::isMoving(), Unit::isSwimming(), Unit::isTurning(), Unit::IsWalking(), Movement::MoveSplineInit::Launch(), Player::LoadFromDB(), MotionMaster::MoveFall(), Movement::MoveSplineInit::MoveSplineInit(), FollowMovementGenerator< T >::PositionOkay(), PredictPosition(), spell_igb_teleport_to_enemy_ship::spell_igb_teleport_to_enemy_ship_SpellScript::RelocateTransportOffset(), Unit::RemoveExtraUnitMovementFlag(), Vehicle::RemovePassenger(), MotionTransport::RemovePassenger(), StaticTransport::RemovePassenger(), Unit::RemoveUnitMovementFlag(), Unit::SetExtraUnitMovementFlags(), Unit::SetUnitMovementFlags(), Movement::MoveSplineInit::Stop(), Player::TeleportTo(), StaticTransport::UpdatePassengerPositions(), MotionTransport::UpdatePassengerPositions(), and Unit::UpdateSplinePosition().
m_name
std::string WorldObject::m_name protected
Referenced by Player::_LoadGlyphAuras(), Player::Create(), GetName(), GetNameForLocaleIdx(), Player::LoadFromDB(), Pet::Pet(), Player::SaveToDB(), and SetName().
m_notifyflags
uint16 WorldObject::m_notifyflags private
Referenced by AddToNotify(), GetNotifyFlags(), isNeedNotify(), RemoveFromNotify(), and ResetAllNotifies().
m_phaseMask
uint32 WorldObject::m_phaseMask private
Referenced by GetPhaseMask(), and SetPhaseMask().
m_serverSideVisibility
FlaggedValuesArray32<int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES> WorldObject::m_serverSideVisibility
Referenced by CanSeeOrDetect(), Creature::Create(), AuraEffect::HandleAuraGhost(), Unit::IsVisible(), Player::SetGMVisible(), Player::SetServerSideVisibility(), Unit::SetVisible(), Unit::Unit(), and WorldObject().
m_serverSideVisibilityDetect
FlaggedValuesArray32<int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES> WorldObject::m_serverSideVisibilityDetect
Referenced by CanSeeOrDetect(), Creature::Create(), AuraEffect::HandleAuraGhost(), Player::SetGameMaster(), Player::SetServerSideVisibilityDetect(), and WorldObject().
m_stealth
FlaggedValuesArray32<int32, uint32, StealthType, TOTAL_STEALTH_TYPES> WorldObject::m_stealth
Referenced by CanDetectStealthOf(), CanSeeOrDetect(), GameObject::Create(), AuraEffect::HandleModStealth(), and AuraEffect::HandleModStealthLevel().
m_stealthDetect
FlaggedValuesArray32<int32, uint32, StealthType, TOTAL_STEALTH_TYPES> WorldObject::m_stealthDetect
Referenced by CanDetectStealthOf(), and AuraEffect::HandleModStealthDetect().
m_transport
Transport* WorldObject::m_transport protected
Referenced by _IsWithinDist(), GetTransport(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandlePlayerLoginFromDB(), Player::LoadFromDB(), SetTransport(), and Player::TeleportTo().
m_useCombinedPhases
bool WorldObject::m_useCombinedPhases private
Referenced by InSamePhase(), and SetPhaseMask().
m_visibilityDistanceOverride
Optional<float> WorldObject::m_visibilityDistanceOverride protected
Referenced by GetSightRange(), GetVisibilityRange(), IsVisibilityOverridden(), and SetVisibilityDistanceOverride().
m_zoneScript
ZoneScript* WorldObject::m_zoneScript protected
Referenced by GameObject::AddToWorld(), ClearZoneScript(), GameObject::Create(), StaticTransport::Create(), TransportMgr::CreateTransport(), GameObject::EventInform(), GetZoneScript(), GameObject::RemoveFromWorld(), and SetZoneScript().