AzerothCore: npc_kalecgos_kj Struct Reference
npc_kalecgos_kj Struct Reference
Public Member Functions
npc_kalecgos_kj (Creature *creature)
void Reset () override
void DoAction (int32 param) override
void JustSummoned (Creature *summon) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
InstanceScript * instance
SummonList summons
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_kalecgos_kj()
npc_kalecgos_kj::npc_kalecgos_kj (Creature * creature) inline
                                        : NullCreatureAI(creature), summons(me)
    {
        instance = creature->GetInstanceScript();
    }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DoAction()
void npc_kalecgos_kj::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
    {
        if (param == ACTION_START_POST_EVENT)
        {
            me->SetCanFly(false);
            me->SetDisableGravity(false);
            me->CastSpell(me, SPELL_TELEPORT_AND_TRANSFORM, true);
            events.ScheduleEvent(EVENT_SCENE_01, 35000);
        }
    }
References ACTION_START_POST_EVENT, Unit::CastSpell(), EVENT_SCENE_01, CreatureAI::me, Creature::SetCanFly(), Creature::SetDisableGravity(), and SPELL_TELEPORT_AND_TRANSFORM.
JustSummoned()
void npc_kalecgos_kj::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
    {
        summons.Summon(summon);
        if (summon->GetEntry() == NPC_SHATTERED_SUN_RIFTWAKER)
        {
            summon->CastSpell(summon, SPELL_TELEPORT_VISUAL, true);
            Movement::MoveSplineInit init(summon);
            if (summons.size() == 1)
            {
                init.MoveTo(1727.08f, 656.82f, 28.37f, false, true);
                init.SetFacing(5.14f);
            }
            else
            {
                init.MoveTo(1738.84f, 627.32f, 28.26f, false, true);
                init.SetFacing(2.0f);
            }
            init.Launch();
        }
        else if (summon->GetEntry() == NPC_SHATTRATH_PORTAL_DUMMY)
        {
            if (Creature* riftwaker = summon->FindNearestCreature(NPC_SHATTERED_SUN_RIFTWAKER, 10.0f))
                riftwaker->CastSpell(summon, SPELL_OPEN_PORTAL_FROM_SHATTRATH, false);
            summon->SetWalk(true);
            summon->GetMotionMaster()->MovePoint(0, summon->GetPositionX(), summon->GetPositionY(), summon->GetPositionZ() + 30.0f, false, true);
        }
        else if (summon->GetEntry() == NPC_INERT_PORTAL)
            summon->CastSpell(summon, SPELL_BOSS_ARCANE_PORTAL_STATE, true);
        else if (summon->GetEntry() == NPC_SHATTERED_SUN_SOLDIER)
            summon->CastSpell(summon, SPELL_TELEPORT_VISUAL, true);
        else if (summon->GetEntry() == NPC_LADY_LIADRIN)
        {
            summon->CastSpell(summon, SPELL_TELEPORT_VISUAL, true);
            summon->SetWalk(true);
        }
        else if (summon->GetEntry() == NPC_PROPHET_VELEN)
        {
            summon->CastSpell(summon, SPELL_TELEPORT_VISUAL, true);
            summon->SetWalk(true);
            summon->GetMotionMaster()->MovePoint(0, 1710.15f, 639.23f, 27.311f, false, true);
        }
        else if (summon->GetEntry() == NPC_THE_CORE_OF_ENTROPIUS)
            summon->GetMotionMaster()->MovePoint(0, summon->GetPositionX(), summon->GetPositionY(), 30.0f);
    }
References Unit::CastSpell(), WorldObject::FindNearestCreature(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Movement::MoveSplineInit::Launch(), MotionMaster::MovePoint(), Movement::MoveSplineInit::MoveTo(), NPC_INERT_PORTAL, NPC_LADY_LIADRIN, NPC_PROPHET_VELEN, NPC_SHATTERED_SUN_RIFTWAKER, NPC_SHATTERED_SUN_SOLDIER, NPC_SHATTRATH_PORTAL_DUMMY, NPC_THE_CORE_OF_ENTROPIUS, Movement::MoveSplineInit::SetFacing(), Creature::SetWalk(), SummonList::size(), SPELL_BOSS_ARCANE_PORTAL_STATE, SPELL_OPEN_PORTAL_FROM_SHATTRATH, SPELL_TELEPORT_VISUAL, SummonList::Summon(), and summons.
Reset()
void npc_kalecgos_kj::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        events.Reset();
        summons.DespawnAll();
    }
References SummonList::DespawnAll(), and summons.
UpdateAI()
void npc_kalecgos_kj::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
    {
        events.Update(diff);
        switch (uint32 eventId = events.ExecuteEvent())
        {
        case EVENT_SCENE_01:
            Talk(SAY_KALECGOS_GOODBYE);
            events.ScheduleEvent(eventId + 1, 15000);
            break;
        case EVENT_SCENE_02:
            me->SummonCreature(NPC_SHATTERED_SUN_RIFTWAKER, 1688.42f, 641.82f, 27.60f, 0.67f);
            me->SummonCreature(NPC_SHATTERED_SUN_RIFTWAKER, 1712.58f, 616.29f, 27.78f, 0.76f);
            events.ScheduleEvent(eventId + 1, 6000);
            break;
        case EVENT_SCENE_03:
            me->SummonCreature(NPC_SHATTRATH_PORTAL_DUMMY, 1727.08f + cos(5.14f), 656.82f + std::sin(5.14f), 28.37f + 2.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 10000);
            me->SummonCreature(NPC_SHATTRATH_PORTAL_DUMMY, 1738.84f + cos(2.0f), 627.32f + std::sin(2.0f), 28.26f + 2.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 10000);
            events.ScheduleEvent(eventId + 1, 11000);
            break;
        case EVENT_SCENE_04:
            me->SummonCreature(NPC_INERT_PORTAL, 1734.96f, 642.43f, 28.06f, 3.49f);
            events.ScheduleEvent(eventId + 1, 4000);
            break;
        case EVENT_SCENE_05:
            if (Creature* first = me->SummonCreature(NPC_SHATTERED_SUN_SOLDIER, 1729.48f, 640.49f, 28.06f, 3.49f))
            {
                first->m_Events.AddEvent(new MoveDelayed(first, 1718.70f, 607.78f, 28.06f, 2.323f), first->m_Events.CalculateTime(5000));
                first->m_Events.AddEvent(new FixOrientation(first), first->m_Events.CalculateTime(12000));
                for (uint8 i = 0; i < 9; ++i)
                    if (Creature* follower = me->SummonCreature(NPC_SHATTERED_SUN_SOLDIER, 1729.48f + 5 * cos(i * 2.0f * M_PI / 9), 640.49f + 5 * std::sin(i * 2.0f * M_PI / 9), 28.06f, 3.49f))
                        follower->GetMotionMaster()->MoveFollow(first, 3.0f, follower->GetAngle(first));
            }
            events.ScheduleEvent(eventId + 1, 10000);
            break;
        case EVENT_SCENE_06:
            if (Creature* first = me->SummonCreature(NPC_SHATTERED_SUN_SOLDIER, 1729.48f, 640.49f, 28.06f, 3.49f))
            {
                first->m_Events.AddEvent(new MoveDelayed(first, 1678.69f, 649.27f, 28.06f, 5.46f), first->m_Events.CalculateTime(5000));
                first->m_Events.AddEvent(new FixOrientation(first), first->m_Events.CalculateTime(14500));
                for (uint8 i = 0; i < 9; ++i)
                    if (Creature* follower = me->SummonCreature(NPC_SHATTERED_SUN_SOLDIER, 1729.48f + 5 * cos(i * 2.0f * M_PI / 9), 640.49f + 5 * std::sin(i * 2.0f * M_PI / 9), 28.06f, 3.49f))
                        follower->GetMotionMaster()->MoveFollow(first, 3.0f, follower->GetAngle(first));
            }
            events.ScheduleEvent(eventId + 1, 12000);
            break;
        case EVENT_SCENE_07:
            me->SummonCreature(NPC_LADY_LIADRIN, 1719.87f, 644.265f, 28.06f, 3.83f);
            me->SummonCreature(NPC_PROPHET_VELEN, 1717.97f, 646.44f, 28.06f, 3.94f);
            events.ScheduleEvent(eventId + 1, 7000);
            break;
        case EVENT_SCENE_08:
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
                velen->AI()->Talk(SAY_VELEN_01);
            events.ScheduleEvent(eventId + 1, 25000);
            break;
        case EVENT_SCENE_09:
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
                velen->AI()->Talk(SAY_VELEN_02);
            events.ScheduleEvent(eventId + 1, 14500);
            break;
        case EVENT_SCENE_10:
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
                velen->AI()->Talk(SAY_VELEN_03);
            events.ScheduleEvent(eventId + 1, 12500);
            break;
        case EVENT_SCENE_11:
            me->SummonCreature(NPC_THE_CORE_OF_ENTROPIUS, 1698.86f, 628.73f, 92.83f, 0.0f);
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
                velen->CastSpell(velen, SPELL_CALL_ENTROPIUS, false);
            events.ScheduleEvent(eventId + 1, 8000);
            break;
        case EVENT_SCENE_12:
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
            {
                velen->InterruptNonMeleeSpells(false);
                velen->AI()->Talk(SAY_VELEN_04);
            }
            events.ScheduleEvent(eventId + 1, 20000);
            break;
        case EVENT_SCENE_13:
            if (Creature* liadrin = summons.GetCreatureWithEntry(NPC_LADY_LIADRIN))
                liadrin->GetMotionMaster()->MovePoint(0, 1711.28f, 637.29f, 27.29f);
            events.ScheduleEvent(eventId + 1, 6000);
            break;
        case EVENT_SCENE_14:
            if (Creature* liadrin = summons.GetCreatureWithEntry(NPC_LADY_LIADRIN))
                liadrin->AI()->Talk(SAY_LIADRIN_01);
            events.ScheduleEvent(eventId + 1, 10000);
            break;
        case EVENT_SCENE_15:
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
                velen->AI()->Talk(SAY_VELEN_05);
            events.ScheduleEvent(eventId + 1, 14000);
            break;
        case EVENT_SCENE_16:
            if (Creature* liadrin = summons.GetCreatureWithEntry(NPC_LADY_LIADRIN))
                liadrin->AI()->Talk(SAY_LIADRIN_02);
            events.ScheduleEvent(eventId + 1, 2000);
            break;
        case EVENT_SCENE_17:
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
                velen->AI()->Talk(SAY_VELEN_06);
            events.ScheduleEvent(eventId + 1, 3000);
            break;
        case EVENT_SCENE_18:
            if (Creature* core = summons.GetCreatureWithEntry(NPC_THE_CORE_OF_ENTROPIUS))
            {
                core->RemoveAllAuras();
                core->CastSpell(core, SPELL_BLAZE_TO_LIGHT, true);
            }
            events.ScheduleEvent(eventId + 1, 8000);
            break;
        case EVENT_SCENE_19:
            if (Creature* core = summons.GetCreatureWithEntry(NPC_THE_CORE_OF_ENTROPIUS))
            {
                core->SetObjectScale(0.75f);
                core->GetMotionMaster()->MovePoint(0, core->GetPositionX(), core->GetPositionY(), 28.0f);
            }
            events.ScheduleEvent(eventId + 1, 2000);
            break;
        case EVENT_SCENE_20:
            if (Creature* core = summons.GetCreatureWithEntry(NPC_THE_CORE_OF_ENTROPIUS))
                core->CastSpell(core, SPELL_SUNWELL_IGNITION, true);
            events.ScheduleEvent(eventId + 1, 3000);
            break;
        case EVENT_SCENE_21:
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
                velen->AI()->Talk(SAY_VELEN_07);
            events.ScheduleEvent(eventId + 1, 15000);
            break;
        case EVENT_SCENE_22:
            if (Creature* liadrin = summons.GetCreatureWithEntry(NPC_LADY_LIADRIN))
                liadrin->AI()->Talk(SAY_LIADRIN_03);
            events.ScheduleEvent(eventId + 1, 20000);
            break;
        case EVENT_SCENE_23:
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
                velen->AI()->Talk(SAY_VELEN_08);
            if (Creature* liadrin = summons.GetCreatureWithEntry(NPC_LADY_LIADRIN))
                liadrin->SetStandState(UNIT_STAND_STATE_KNEEL);
            events.ScheduleEvent(eventId + 1, 8000);
            break;
        case EVENT_SCENE_24:
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
                velen->AI()->Talk(SAY_VELEN_09);
            events.ScheduleEvent(eventId + 1, 5000);
            break;
        case EVENT_SCENE_25:
            if (Creature* velen = summons.GetCreatureWithEntry(NPC_PROPHET_VELEN))
            {
                velen->GetMotionMaster()->MovePoint(0, 1739.38f, 643.79f, 28.06f);
                velen->DespawnOrUnsummon(5000);
            }
            events.ScheduleEvent(eventId + 1, 3000);
            break;
        case EVENT_SCENE_26:
            for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                    if (summon->GetEntry() == NPC_SHATTERED_SUN_SOLDIER)
                    {
                        summon->GetMotionMaster()->MovePoint(0, 1739.38f, 643.79f, 28.06f);
                        summon->DespawnOrUnsummon(summon->GetExactDist2d(1734.96f, 642.43f) * 100);
                    }
            events.ScheduleEvent(eventId + 1, 7000);
            break;
        case EVENT_SCENE_27:
            me->setActive(false);
            summons.DespawnEntry(NPC_INERT_PORTAL);
            summons.DespawnEntry(NPC_SHATTERED_SUN_RIFTWAKER);
            break;
        }
    }
References SummonList::begin(), Unit::CastSpell(), SummonList::DespawnEntry(), SummonList::end(), EVENT_SCENE_01, EVENT_SCENE_02, EVENT_SCENE_03, EVENT_SCENE_04, EVENT_SCENE_05, EVENT_SCENE_06, EVENT_SCENE_07, EVENT_SCENE_08, EVENT_SCENE_09, EVENT_SCENE_10, EVENT_SCENE_11, EVENT_SCENE_12, EVENT_SCENE_13, EVENT_SCENE_14, EVENT_SCENE_15, EVENT_SCENE_16, EVENT_SCENE_17, EVENT_SCENE_18, EVENT_SCENE_19, EVENT_SCENE_20, EVENT_SCENE_21, EVENT_SCENE_22, EVENT_SCENE_23, EVENT_SCENE_24, EVENT_SCENE_25, EVENT_SCENE_26, EVENT_SCENE_27, ObjectAccessor::GetCreature(), SummonList::GetCreatureWithEntry(), CreatureAI::me, NPC_INERT_PORTAL, NPC_LADY_LIADRIN, NPC_PROPHET_VELEN, NPC_SHATTERED_SUN_RIFTWAKER, NPC_SHATTERED_SUN_SOLDIER, NPC_SHATTRATH_PORTAL_DUMMY, NPC_THE_CORE_OF_ENTROPIUS, SAY_KALECGOS_GOODBYE, SAY_LIADRIN_01, SAY_LIADRIN_02, SAY_LIADRIN_03, SAY_VELEN_01, SAY_VELEN_02, SAY_VELEN_03, SAY_VELEN_04, SAY_VELEN_05, SAY_VELEN_06, SAY_VELEN_07, SAY_VELEN_08, SAY_VELEN_09, WorldObject::setActive(), SPELL_BLAZE_TO_LIGHT, SPELL_CALL_ENTROPIUS, SPELL_SUNWELL_IGNITION, WorldObject::SummonCreature(), summons, TEMPSUMMON_TIMED_DESPAWN, and UNIT_STAND_STATE_KNEEL.
Member Data Documentation
events
EventMap npc_kalecgos_kj::events
instance
InstanceScript* npc_kalecgos_kj::instance
Referenced by npc_kalecgos_kj().
summons
SummonList npc_kalecgos_kj::summons
Referenced by JustSummoned(), Reset(), and UpdateAI().