AzerothCore: Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > > Struct Template Reference
Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > > Struct Template Reference
#include "ChatCommandArgs.h"
Public Types
using V = std::variant< Ts... >
Static Public Member Functions
template<std::size_t I>
static ChatCommandResult TryAtIndex (Acore::ChatCommands::Variant< Ts... > &val, ChatHandler const *handler, std::string_view args)
static ChatCommandResult TryConsume (Acore::ChatCommands::Variant< Ts... > &val, ChatHandler const *handler, std::string_view args)
Static Public Attributes
static constexpr std::size_t N = std::variant_size_v<V>
Detailed Description
template<typename... Ts>
struct Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >
Member Typedef Documentation
V
template<typename... Ts> using Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::V = std::variant<Ts...>
Member Function Documentation
TryAtIndex()
template<typename... Ts> template<std::size_t I> static ChatCommandResult Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryAtIndex (Acore::ChatCommands::Variant< Ts... > & val, ChatHandler const * handler, std::string_view args) inline static
        {
            if constexpr (I < N)
            {
                ChatCommandResult thisResult = ArgInfo<std::variant_alternative_t<I, V>>::TryConsume(val.template emplace<I>(), handler, args);
                if (thisResult)
                    return thisResult;
                else
                {
                    ChatCommandResult nestedResult = TryAtIndex<I + 1>(val, handler, args);
                    if (nestedResult || !thisResult.HasErrorMessage())
                        return nestedResult;
                    if (!nestedResult.HasErrorMessage())
                        return thisResult;
                    if (StringStartsWith(nestedResult.GetErrorMessage(), "\""))
                        return Acore::StringFormat("\"{}\"\n{} {}", thisResult.GetErrorMessage(), GetAcoreString(handler, LANG_CMDPARSER_OR), nestedResult.GetErrorMessage());
                    else
                        return Acore::StringFormat("\"{}\"\n{} \"{}\"", thisResult.GetErrorMessage(), GetAcoreString(handler, LANG_CMDPARSER_OR), nestedResult.GetErrorMessage());
                }
            }
            else
                return std::nullopt;
        }
References Acore::Impl::ChatCommands::GetAcoreString(), Acore::Impl::ChatCommands::ChatCommandResult::GetErrorMessage(), Acore::Impl::ChatCommands::ChatCommandResult::HasErrorMessage(), LANG_CMDPARSER_OR, Acore::StringFormat(), and StringStartsWith().
TryConsume()
template<typename... Ts> static ChatCommandResult Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryConsume (Acore::ChatCommands::Variant< Ts... > & val, ChatHandler const * handler, std::string_view args) inline static
        {
            ChatCommandResult result = TryAtIndex<0>(val, handler, args);
            if (result.HasErrorMessage() && (result.GetErrorMessage().find('\n') != std::string::npos))
                return Acore::StringFormat("{} {}", GetAcoreString(handler, LANG_CMDPARSER_EITHER), result.GetErrorMessage());
            return result;
        }
References Acore::Impl::ChatCommands::GetAcoreString(), Acore::Impl::ChatCommands::ChatCommandResult::GetErrorMessage(), Acore::Impl::ChatCommands::ChatCommandResult::HasErrorMessage(), LANG_CMDPARSER_EITHER, and Acore::StringFormat().
Member Data Documentation
N
template<typename... Ts> constexpr std::size_t Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::N = std::variant_size_v<V> static constexpr