AzeorthCore: instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript Struct Reference
instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript Struct Reference
Public Member Functions
instance_blackfathom_deeps_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnUnitDeath (Unit *unit) override
void OnGameObjectCreate (GameObject *gameobject) override
void SetData (uint32 type, uint32 data) override
std::string GetSaveData () override
void Load (const char *in) override
bool IsFireEventDone ()
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 _encounters [MAX_ENCOUNTERS]
ObjectGuid _akumaiPortalGUID
uint8 _requiredDeaths
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Constructor & Destructor Documentation
instance_blackfathom_deeps_InstanceMapScript()
instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::instance_blackfathom_deeps_InstanceMapScript (Map * map) inline
: InstanceScript(map) { }
Member Function Documentation
GetSaveData()
std::string instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
        {
            std::ostringstream saveStream;
            saveStream << "B L " << _encounters[0] << ' ' << _encounters[1] << ' ' << _encounters[2] << ' ' << _encounters[3] << ' ' << _encounters[4] << ' ' << _encounters[5];
            return saveStream.str();
        }
References _encounters.
Initialize()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            memset(&_encounters, 0, sizeof(_encounters));
            _requiredDeaths = 0;
        }
References _encounters, and _requiredDeaths.
IsFireEventDone()
bool instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::IsFireEventDone () inline
        {
            return _encounters[TYPE_FIRE1] == DONE && _encounters[TYPE_FIRE2] == DONE && _encounters[TYPE_FIRE3] == DONE && _encounters[TYPE_FIRE4] == DONE;
        }
References _encounters, DONE, TYPE_FIRE1, TYPE_FIRE2, TYPE_FIRE3, and TYPE_FIRE4.
Referenced by OnGameObjectCreate(), and OnUnitDeath().
Load()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!in)
                return;
            char dataHead1, dataHead2;
            std::istringstream loadStream(in);
            loadStream >> dataHead1 >> dataHead2;
            if (dataHead1 == 'B' && dataHead2 == 'L')
            {
                for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                {
                    loadStream >> _encounters[i];
                    if (_encounters[i] == IN_PROGRESS)
                        _encounters[i] = NOT_STARTED;
                }
            }
        }
References _encounters, IN_PROGRESS, MAX_ENCOUNTERS, and NOT_STARTED.
OnCreatureCreate()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            if (creature->IsSummon() && (creature->GetEntry() == NPC_BARBED_CRUSTACEAN || creature->GetEntry() == NPC_AKU_MAI_SERVANT ||
                                         creature->GetEntry() == NPC_MURKSHALLOW_SOFTSHELL || creature->GetEntry() == NPC_AKU_MAI_SNAPJAW))
                ++_requiredDeaths;
        }
References _requiredDeaths, Object::GetEntry(), Unit::IsSummon(), NPC_AKU_MAI_SERVANT, NPC_AKU_MAI_SNAPJAW, NPC_BARBED_CRUSTACEAN, and NPC_MURKSHALLOW_SOFTSHELL.
OnGameObjectCreate()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnGameObjectCreate (GameObject * gameobject) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (gameobject->GetEntry())
            {
                case GO_FIRE_OF_AKU_MAI_1:
                case GO_FIRE_OF_AKU_MAI_2:
                case GO_FIRE_OF_AKU_MAI_3:
                case GO_FIRE_OF_AKU_MAI_4:
                    if (_encounters[TYPE_AKU_MAI_EVENT] == DONE)
                    {
                        gameobject->SetGameObjectFlag(GO_FLAG_IN_USE);
                        gameobject->SetGoState(GO_STATE_ACTIVE);
                    }
                    break;
                case GO_SHRINE_OF_GELIHAST:
                    if (_encounters[TYPE_GELIHAST] == DONE)
                        gameobject->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    break;
                case GO_ALTAR_OF_THE_DEEPS:
                    if (_encounters[TYPE_AKU_MAI] == DONE)
                        gameobject->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    break;
                case GO_AKU_MAI_DOOR:
                    if (IsFireEventDone() && _encounters[TYPE_AKU_MAI_EVENT] == DONE)
                        HandleGameObject(ObjectGuid::Empty, true, gameobject);
                    _akumaiPortalGUID = gameobject->GetGUID();
                    break;
            }
        }
References _akumaiPortalGUID, _encounters, DONE, ObjectGuid::Empty, Object::GetEntry(), Object::GetGUID(), GO_AKU_MAI_DOOR, GO_ALTAR_OF_THE_DEEPS, GO_FIRE_OF_AKU_MAI_1, GO_FIRE_OF_AKU_MAI_2, GO_FIRE_OF_AKU_MAI_3, GO_FIRE_OF_AKU_MAI_4, GO_FLAG_IN_USE, GO_FLAG_NOT_SELECTABLE, GO_SHRINE_OF_GELIHAST, GO_STATE_ACTIVE, InstanceScript::HandleGameObject(), IsFireEventDone(), GameObject::RemoveGameObjectFlag(), GameObject::SetGameObjectFlag(), GameObject::SetGoState(), TYPE_AKU_MAI, TYPE_AKU_MAI_EVENT, and TYPE_GELIHAST.
OnUnitDeath()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            if (unit->IsSummon() && (unit->GetEntry() == NPC_BARBED_CRUSTACEAN || unit->GetEntry() == NPC_AKU_MAI_SERVANT ||
                                     unit->GetEntry() == NPC_MURKSHALLOW_SOFTSHELL || unit->GetEntry() == NPC_AKU_MAI_SNAPJAW))
            {
                if (--_requiredDeaths == 0)
                {
                    if (IsFireEventDone())
                    {
                        HandleGameObject(_akumaiPortalGUID, true);
                        _encounters[TYPE_AKU_MAI_EVENT] = DONE;
                    }
                }
            }
        }
References _akumaiPortalGUID, _encounters, _requiredDeaths, DONE, Object::GetEntry(), InstanceScript::HandleGameObject(), IsFireEventDone(), Unit::IsSummon(), NPC_AKU_MAI_SERVANT, NPC_AKU_MAI_SNAPJAW, NPC_BARBED_CRUSTACEAN, NPC_MURKSHALLOW_SOFTSHELL, and TYPE_AKU_MAI_EVENT.
SetData()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case TYPE_GELIHAST:
                case TYPE_FIRE1:
                case TYPE_FIRE2:
                case TYPE_FIRE3:
                case TYPE_FIRE4:
                case TYPE_AKU_MAI:
                case TYPE_AKU_MAI_EVENT:
                    _encounters[type] = data;
                    break;
            }
            if (data == DONE)
                SaveToDB();
        }
References _encounters, DONE, InstanceScript::SaveToDB(), TYPE_AKU_MAI, TYPE_AKU_MAI_EVENT, TYPE_FIRE1, TYPE_FIRE2, TYPE_FIRE3, TYPE_FIRE4, and TYPE_GELIHAST.
Member Data Documentation
_akumaiPortalGUID
ObjectGuid instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::_akumaiPortalGUID private
Referenced by OnGameObjectCreate(), and OnUnitDeath().
_encounters
uint32 instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::_encounters[MAX_ENCOUNTERS] private
Referenced by GetSaveData(), Initialize(), IsFireEventDone(), Load(), OnGameObjectCreate(), OnUnitDeath(), and SetData().
_requiredDeaths
uint8 instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::_requiredDeaths private
Referenced by Initialize(), OnCreatureCreate(), and OnUnitDeath().