AzerothCore: QuestMenu Class Reference
QuestMenu Class Reference
#include "GossipDef.h"
Public Member Functions
uint8 GetMenuItemCount () const
bool Empty () const
QuestMenuItem const & GetItem (uint16 index) const
AddMenuItem
Adds a localized gossip menu item from db by menu id and menu item id.
Parameters
menuId Gossip menu id.
menuItemId Gossip menu item id.
sender Identifier of the current menu.
action Custom action given to OnGossipHello.
boxMoney Custom price for pop-up box. If > 0, it will replace DB value.
QuestMenu ()
~QuestMenu ()
void AddMenuItem (uint32 QuestId, uint8 Icon)
void ClearMenu ()
bool HasItem (uint32 questId) const
Private Attributes
QuestMenuItemList _questMenuItems
Detailed Description
Constructor & Destructor Documentation
QuestMenu()
QuestMenu::QuestMenu ()
{
    _questMenuItems.reserve(16);                                   // can be set for max from most often sizes to speedup push_back and less memory use
}
References _questMenuItems.
~QuestMenu()
QuestMenu::~QuestMenu ()
{
    ClearMenu();
}
References ClearMenu().
Member Function Documentation
AddMenuItem()
void QuestMenu::AddMenuItem (uint32 QuestId, uint8 Icon)
{
    if (!sObjectMgr->GetQuestTemplate(QuestId))
        return;
    ASSERT(_questMenuItems.size() <= GOSSIP_MAX_MENU_ITEMS);
    QuestMenuItem questMenuItem;
    questMenuItem.QuestId        = QuestId;
    questMenuItem.QuestIcon      = Icon;
    _questMenuItems.push_back(questMenuItem);
}
References _questMenuItems, ASSERT, GOSSIP_MAX_MENU_ITEMS, QuestMenuItem::QuestIcon, QuestMenuItem::QuestId, and sObjectMgr.
Referenced by npc_wg_quest_giver::OnGossipHello(), Player::PrepareQuestMenu(), and npc_costumed_orphan_matron::sGossipHello().
ClearMenu()
void QuestMenu::ClearMenu ()
{
    _questMenuItems.clear();
}
References _questMenuItems.
Referenced by PlayerMenu::ClearMenus(), npc_wg_quest_giver::OnGossipHello(), npc_elder_clearwater::OnGossipHello(), Player::PrepareQuestMenu(), npc_costumed_orphan_matron::sGossipHello(), and ~QuestMenu().
Empty()
bool QuestMenu::Empty () const inline
    {
        return _questMenuItems.empty();
    }
References _questMenuItems.
Referenced by PlayerMenu::Empty(), Player::SendPreparedGossip(), and Player::SendPreparedQuest().
GetItem()
QuestMenuItem const & QuestMenu::GetItem (uint16 index) const inline
    {
        return _questMenuItems[index];
    }
References _questMenuItems.
Referenced by PlayerMenu::SendGossipMenu(), Player::SendPreparedQuest(), and PlayerMenu::SendQuestGiverQuestList().
GetMenuItemCount()
uint8 QuestMenu::GetMenuItemCount () const inline
    {
        return _questMenuItems.size();
    }
References _questMenuItems.
Referenced by PlayerMenu::SendGossipMenu(), Player::SendPreparedQuest(), and PlayerMenu::SendQuestGiverQuestList().
HasItem()
bool QuestMenu::HasItem (uint32 questId) const
{
    for (QuestMenuItemList::const_iterator i = _questMenuItems.begin(); i != _questMenuItems.end(); ++i)
        if (i->QuestId == questId)
            return true;
    return false;
}
References _questMenuItems.
Member Data Documentation
_questMenuItems
QuestMenuItemList QuestMenu::_questMenuItems private
Referenced by AddMenuItem(), ClearMenu(), Empty(), GetItem(), GetMenuItemCount(), HasItem(), and QuestMenu().