AzerothCore: at_icc_start_frostwing_gauntlet Class Reference
at_icc_start_frostwing_gauntlet Class Reference
Public Member Functions
at_icc_start_frostwing_gauntlet ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
at_icc_start_frostwing_gauntlet()
at_icc_start_frostwing_gauntlet::at_icc_start_frostwing_gauntlet () inline
: AreaTriggerScript("at_icc_start_frostwing_gauntlet") { }
Member Function Documentation
OnTrigger()
bool at_icc_start_frostwing_gauntlet::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (InstanceScript* instance = player->GetInstanceScript())
            if (instance->GetBossState(DATA_SISTER_SVALNA) != DONE)
                if (Creature* crok = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_CROK_SCOURGEBANE)))
                {
                    if (!crok->IsAlive())
                    {
                        FrostwingGauntletRespawner respawner;
                        Acore::CreatureWorker<FrostwingGauntletRespawner> worker(crok, respawner);
                        Cell::VisitGridObjects(crok, worker, 333.0f);
                        return true;
                    }
                    else
                        crok->AI()->DoAction(ACTION_START_GAUNTLET);
                }
        return true;
    }
References ACTION_START_GAUNTLET, DATA_CROK_SCOURGEBANE, DATA_SISTER_SVALNA, DONE, ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), and Cell::VisitGridObjects().