AzerothCore: at_twilight_grove Class Reference
at_twilight_grove Class Reference
Public Member Functions
at_twilight_grove ()
bool OnTrigger (Player *player, const AreaTrigger *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
virtual bool OnTrigger (Player *, AreaTrigger const *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
at_twilight_grove()
at_twilight_grove::at_twilight_grove () inline
: AreaTriggerScript("at_twilight_grove") { }
Member Function Documentation
OnTrigger()
bool at_twilight_grove::OnTrigger (Player * player, const AreaTrigger *) inline override virtual
Reimplemented from AreaTriggerScript.
    {
        if (player->HasQuestForItem(ITEM_FRAGMENT) && !player->HasItemCount(ITEM_FRAGMENT))
            player->SummonCreature(NPC_TWILIGHT_CORRUPTER, -10328.16f, -489.57f, 49.95f, 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 240000);
        return false;
    };
References Player::HasItemCount(), Player::HasQuestForItem(), ITEM_FRAGMENT, NPC_TWILIGHT_CORRUPTER, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.