AzerothCore: boss_elder_nadox Struct Reference
boss_elder_nadox Struct Reference
Public Member Functions
boss_elder_nadox (Creature *creature)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void SummonedCreatureDies (Creature *summon, Unit *) override
void KilledUnit (Unit *victim) override
void JustDied (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
uint32 GetData (uint32 type) const override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Member Functions
void SummonHelpers (bool swarm)
Private Attributes
GuidList swarmEggs
GuidList guardianEggs
ObjectGuid previousSwarmEgg_GUID
bool guardianSummoned
bool respectYourElders
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_elder_nadox()
boss_elder_nadox::boss_elder_nadox (Creature * creature) inline
                                         : BossAI(creature, DATA_ELDER_NADOX),
        guardianSummoned(false),
        respectYourElders(true)
    {
    }
Member Function Documentation
DamageTaken()
void boss_elder_nadox::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
    {
        if (!guardianSummoned && me->HealthBelowPctDamaged(55, damage))
        {
            SummonHelpers(false);
            guardianSummoned = true;
        }
    }
References guardianSummoned, Unit::HealthBelowPctDamaged(), ScriptedAI::me, and SummonHelpers().
GetData()
uint32 boss_elder_nadox::GetData (uint32 type) const inline override virtual
Reimplemented from UnitAI.
    {
        if (type == DATA_RESPECT_YOUR_ELDERS)
        {
            return respectYourElders ? 1 : 0;
        }
        return 0;
    }
References DATA_RESPECT_YOUR_ELDERS, and respectYourElders.
JustDied()
void boss_elder_nadox::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
    {
        _JustDied();
        Talk(SAY_DEATH);
    }
References BossAI::_JustDied(), and SAY_DEATH.
JustEngagedWith()
void boss_elder_nadox::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        _JustEngagedWith();
        Talk(SAY_AGGRO);
        events.ScheduleEvent(EVENT_SWARMER, 10s);
        events.ScheduleEvent(EVENT_CHECK_HOME, 2s);
        events.ScheduleEvent(EVENT_PLAGUE, 5s, 8s);
        if (IsHeroic())
        {
            events.ScheduleEvent(EVENT_BROOD_RAGE, 5s);
        }
        // Cache eggs
        std::list<Creature*> eggs;
        // Swarm eggs
        me->GetCreatureListWithEntryInGrid(eggs, NPC_AHNKAHAR_SWARM_EGG, 250.0f);
        if (!eggs.empty())
        {
            for (Creature* const egg : eggs)
            {
                if (egg)
                {
                    swarmEggs.push_back(egg->GetGUID());
                }
            }
        }
        eggs.clear();
            // Guardian eggs
        me->GetCreatureListWithEntryInGrid(eggs, NPC_AHNKAHAR_GUARDIAN_EGG, 250.0f);
        if (!eggs.empty())
        {
            for (Creature* const egg : eggs)
            {
                if (egg)
                {
                    guardianEggs.push_back(egg->GetGUID());
                }
            }
        }
    }
References BossAI::_JustEngagedWith(), EVENT_BROOD_RAGE, EVENT_CHECK_HOME, EVENT_PLAGUE, EVENT_SWARMER, WorldObject::GetCreatureListWithEntryInGrid(), guardianEggs, ScriptedAI::IsHeroic(), ScriptedAI::me, NPC_AHNKAHAR_GUARDIAN_EGG, NPC_AHNKAHAR_SWARM_EGG, SAY_AGGRO, and swarmEggs.
KilledUnit()
void boss_elder_nadox::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (victim->IsPlayer())
        {
            Talk(SAY_SLAY);
        }
    }
References Object::IsPlayer(), and SAY_SLAY.
Reset()
void boss_elder_nadox::Reset () inline override virtual
Reimplemented from BossAI.
    {
        _Reset();
        // Clear eggs data
        swarmEggs.clear();
        guardianEggs.clear();
        previousSwarmEgg_GUID.Clear();
        guardianSummoned = false;
        respectYourElders = true;
    }
References BossAI::_Reset(), ObjectGuid::Clear(), guardianEggs, guardianSummoned, previousSwarmEgg_GUID, respectYourElders, and swarmEggs.
SummonedCreatureDies()
void boss_elder_nadox::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
    {
        if (summon->GetEntry() == NPC_AHNKAHAR_GUARDIAN)
        {
            respectYourElders = false;
        }
    }
References Object::GetEntry(), NPC_AHNKAHAR_GUARDIAN, and respectYourElders.
SummonHelpers()
void boss_elder_nadox::SummonHelpers (bool swarm) inline private
    {
        if (swarm)
        {
            if (swarmEggs.empty())
            {
                return;
            }
            // Make a copy of guid list
            GuidList swarmEggs2 = swarmEggs;
            // Remove previous egg
            if (previousSwarmEgg_GUID)
            {
                std::list<ObjectGuid>::iterator itr = std::find(swarmEggs2.begin(), swarmEggs2.end(), previousSwarmEgg_GUID);
                if (itr != swarmEggs2.end())
                {
                    swarmEggs2.erase(itr);
                }
            }
            if (swarmEggs2.empty())
            {
                return;
            }
            previousSwarmEgg_GUID = Acore::Containers::SelectRandomContainerElement(swarmEggs2);
            if (Creature* egg = ObjectAccessor::GetCreature(*me, previousSwarmEgg_GUID))
            {
                egg->CastSpell(egg, SPELL_SUMMON_SWARMERS, true, nullptr, nullptr, me->GetGUID());
            }
            if (roll_chance_f(33))
            {
                Talk(SAY_EGG_SAC);
            }
        }
        else
        {
            if (guardianEggs.empty())
            {
                return;
            }
            ObjectGuid const& guardianEggGUID = Acore::Containers::SelectRandomContainerElement(guardianEggs);
            if (Creature* egg = ObjectAccessor::GetCreature(*me, guardianEggGUID))
            {
                egg->CastSpell(egg, SPELL_SUMMON_SWARM_GUARD, true, nullptr, nullptr, me->GetGUID());
            }
            Talk(EMOTE_HATCHES, me);
            if (roll_chance_f(33))
            {
                Talk(SAY_EGG_SAC);
            }
        }
    }
References EMOTE_HATCHES, ObjectAccessor::GetCreature(), Object::GetGUID(), guardianEggs, ScriptedAI::me, previousSwarmEgg_GUID, roll_chance_f(), SAY_EGG_SAC, Acore::Containers::SelectRandomContainerElement(), SPELL_SUMMON_SWARM_GUARD, SPELL_SUMMON_SWARMERS, and swarmEggs.
Referenced by DamageTaken(), and UpdateAI().
UpdateAI()
void boss_elder_nadox::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
    {
        if (!UpdateVictim())
        {
            return;
        }
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
        while (uint32 const eventId = events.ExecuteEvent())
        {
            switch (eventId)
            {
                case EVENT_BROOD_RAGE:
                {
                    if (Creature* pSwarmer = me->FindNearestCreature(NPC_AHNKAHAR_SWARMER, 40, true))
                        DoCast(pSwarmer, SPELL_BROOD_RAGE_H, true);
                    events.Repeat(10s);
                    break;
                }
                case EVENT_PLAGUE:
                {
                    DoCastVictim(SPELL_BROOD_PLAGUE, false);
                    events.Repeat(12s, 17s);
                    break;
                }
                case EVENT_SWARMER:
                {
                    SummonHelpers(true);
                    events.Repeat(10s);
                    break;
                }
                case EVENT_CHECK_HOME:
                {
                    if (!me->HasAura(SPELL_ENRAGE) && (me->GetPositionZ() < 24.0f || !me->GetHomePosition().IsInDist(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 110.0f)))
                    {
                        DoCastSelf(SPELL_ENRAGE, true);
                    }
                    break;
                }
            }
        }
        DoMeleeAttackIfReady();
    }
References UnitAI::DoCast(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EVENT_BROOD_RAGE, EVENT_CHECK_HOME, EVENT_PLAGUE, EVENT_SWARMER, WorldObject::FindNearestCreature(), Creature::GetHomePosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::HasAura(), Unit::HasUnitState(), ScriptedAI::me, NPC_AHNKAHAR_SWARMER, SPELL_BROOD_PLAGUE, SPELL_BROOD_RAGE_H, SPELL_ENRAGE, SummonHelpers(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
guardianEggs
GuidList boss_elder_nadox::guardianEggs private
Referenced by JustEngagedWith(), Reset(), and SummonHelpers().
guardianSummoned
bool boss_elder_nadox::guardianSummoned private
Referenced by DamageTaken(), and Reset().
previousSwarmEgg_GUID
ObjectGuid boss_elder_nadox::previousSwarmEgg_GUID private
Referenced by Reset(), and SummonHelpers().
respectYourElders
bool boss_elder_nadox::respectYourElders private
Referenced by GetData(), Reset(), and SummonedCreatureDies().
swarmEggs
GuidList boss_elder_nadox::swarmEggs private
Referenced by JustEngagedWith(), Reset(), and SummonHelpers().