AzerothCore: WretchedGhoulCleaner Class Reference
WretchedGhoulCleaner Class Reference
Public Member Functions
void operator() (Creature *creature)
Detailed Description
Member Function Documentation
operator()()
void WretchedGhoulCleaner::operator() (Creature * creature) inline
    {
        if (creature->GetEntry() == NPC_SAC_WRETCHED_GHOUL && creature->GetDisplayId() != 11686 && creature->IsAlive())
            Unit::Kill(creature, creature);
    }
References Unit::GetDisplayId(), Object::GetEntry(), Unit::IsAlive(), Unit::Kill(), and NPC_SAC_WRETCHED_GHOUL.