AzerothCore: instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript Struct Reference
instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript Struct Reference
Public Member Functions
instance_shadow_labyrinth_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnUnitDeath (Unit *unit) override
uint32 GetData (uint32 type) const override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 _ritualistsAliveCount
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_shadow_labyrinth_InstanceMapScript()
instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::instance_shadow_labyrinth_InstanceMapScript (Map * map) inline
                                                              : InstanceScript(map)
        {
            SetBossNumber(EncounterCount);
            SetPersistentDataCount(PersistentDataCount);
            LoadDoorData(doorData);
            LoadObjectData(creatureData, nullptr);
        }
References creatureData, doorData, EncounterCount, InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), PersistentDataCount, InstanceScript::SetBossNumber(), and InstanceScript::SetPersistentDataCount().
Member Function Documentation
GetData()
uint32 instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == TYPE_RITUALISTS)
                return GetPersistentData(TYPE_RITUALISTS);
            return 0;
        }
References InstanceScript::GetPersistentData(), and TYPE_RITUALISTS.
Initialize()
void instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            _ritualistsAliveCount = 0;
        }
References _ritualistsAliveCount.
OnCreatureCreate()
void instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            InstanceScript::OnCreatureCreate(creature);
            if (creature->GetEntry() == NPC_CABAL_RITUALIST)
            {
                if (creature->IsAlive())
                {
                    ++_ritualistsAliveCount;
                }
            }
        }
References _ritualistsAliveCount, Object::GetEntry(), Unit::IsAlive(), NPC_CABAL_RITUALIST, and InstanceScript::OnCreatureCreate().
OnUnitDeath()
void instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            InstanceScript::OnUnitDeath(unit);
            if (unit->GetEntry() == NPC_CABAL_RITUALIST)
            {
                if (!--_ritualistsAliveCount)
                {
                    StorePersistentData(TYPE_RITUALISTS, DONE);
                    if (Creature* hellmaw = GetCreature(TYPE_HELLMAW))
                    {
                        hellmaw->AI()->DoAction(1);
                    }
                }
            }
        }
References _ritualistsAliveCount, DONE, InstanceScript::GetCreature(), Object::GetEntry(), NPC_CABAL_RITUALIST, ZoneScript::OnUnitDeath(), InstanceScript::StorePersistentData(), TYPE_HELLMAW, and TYPE_RITUALISTS.
Member Data Documentation
_ritualistsAliveCount
uint32 instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::_ritualistsAliveCount
Referenced by Initialize(), OnCreatureCreate(), and OnUnitDeath().