AzerothCore: boss_kalecgos::boss_kalecgosAI Struct Reference
boss_kalecgos::boss_kalecgosAI Struct Reference
Public Member Functions
boss_kalecgosAI (Creature *creature)
bool CanAIAttack (Unit const *target) const override
void JustReachedHome () override
void Reset () override
void ClearPlayerAuras () const
void DoAction (int32 param) override
void JustDied (Unit *killer) override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void KilledUnit (Unit *victim) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
bool sathBanished
EventMap events2
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_kalecgosAI()
boss_kalecgos::boss_kalecgosAI::boss_kalecgosAI (Creature * creature) inline
                                            : BossAI(creature, DATA_KALECGOS)
        {
        }
Member Function Documentation
CanAIAttack()
bool boss_kalecgos::boss_kalecgosAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
        {
            return target->GetPositionZ() > 50.0f;
        }
References Position::GetPositionZ().
ClearPlayerAuras()
void boss_kalecgos::boss_kalecgosAI::ClearPlayerAuras () const inline
        {
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_CURSE_OF_BOUNDLESS_AGONY);
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_CURSE_OF_BOUNDLESS_AGONY_PLR);
            instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_SPECTRAL_REALM);
        }
References InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), BossAI::instance, SPELL_CURSE_OF_BOUNDLESS_AGONY, SPELL_CURSE_OF_BOUNDLESS_AGONY_PLR, and SPELL_SPECTRAL_REALM.
Referenced by DoAction(), and Reset().
DamageTaken()
void boss_kalecgos::boss_kalecgosAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
        {
            if (damage >= me->GetHealth() && attacker != me)
                damage = 0;
        }
References Unit::GetHealth(), and ScriptedAI::me.
DoAction()
void boss_kalecgos::boss_kalecgosAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_ENRAGE || param == ACTION_ENRAGE_OTHER)
            {
                Talk(param == ACTION_ENRAGE ? SAY_KALEC_ENRAGE_SATH : SAY_SATH_ENRAGE_ME);
                me->CastSpell(me, SPELL_CRAZED_RAGE, true);
                events.CancelEvent(EVENT_CHECK_HEALTH);
                return;
            }
            else if (param == ACTION_BANISH)
            {
                me->CastSpell(me, SPELL_BANISH, true);
                events.Reset();
            }
            else if (param == ACTION_SATH_BANISH)
                sathBanished = true;
            else if (param == ACTION_KALEC_DIED)
            {
                events.Reset();
                events2.ScheduleEvent(EVENT_TALK_BAD_1, 0);
                ClearPlayerAuras();
                return;
            }
            if (me->HasAura(SPELL_BANISH) && sathBanished)
            {
                events.Reset();
                events2.ScheduleEvent(EVENT_TALK_GOOD_1, 1000);
                ClearPlayerAuras();
                if (Creature* Sath = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SATHROVARR)))
                {
                    Sath->RemoveAllAuras();
                    Sath->GetMotionMaster()->MovementExpired();
                    Sath->SetReactState(REACT_PASSIVE);
                    Sath->NearTeleportTo(1696.20f, 915.0f, DRAGON_REALM_Z, Sath->GetOrientation());
                }
            }
        }
References ACTION_BANISH, ACTION_ENRAGE, ACTION_ENRAGE_OTHER, ACTION_KALEC_DIED, ACTION_SATH_BANISH, Unit::CastSpell(), ClearPlayerAuras(), DRAGON_REALM_Z, EVENT_CHECK_HEALTH, EVENT_TALK_BAD_1, EVENT_TALK_GOOD_1, events2, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::HasAura(), BossAI::instance, ScriptedAI::me, NPC_SATHROVARR, REACT_PASSIVE, sathBanished, SAY_KALEC_ENRAGE_SATH, SAY_SATH_ENRAGE_ME, EventMap::ScheduleEvent(), SPELL_BANISH, and SPELL_CRAZED_RAGE.
Referenced by UpdateAI().
JustDied()
void boss_kalecgos::boss_kalecgosAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
        {
            BossAI::JustDied(killer);
        }
References BossAI::JustDied().
JustEngagedWith()
void boss_kalecgos::boss_kalecgosAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            BossAI::JustEngagedWith(who);
            events.ScheduleEvent(EVENT_ARCANE_BUFFET, 6000);
            events.ScheduleEvent(EVENT_FROST_BREATH, 15000);
            events.ScheduleEvent(EVENT_WILD_MAGIC, 10000);
            events.ScheduleEvent(EVENT_TAIL_LASH, 25000);
            events.ScheduleEvent(EVENT_SPECTRAL_BLAST, 20000);
            events.ScheduleEvent(EVENT_CHECK_POS, 5000);
            events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
            events.ScheduleEvent(EVENT_CHECK_HEALTH2, 1000);
            events.ScheduleEvent(EVENT_SPAWN_SPECTRALS, 16000);
            me->SetStandState(UNIT_STAND_STATE_STAND);
            Talk(SAY_EVIL_AGGRO);
        }
References EVENT_ARCANE_BUFFET, EVENT_CHECK_HEALTH, EVENT_CHECK_HEALTH2, EVENT_CHECK_POS, EVENT_FROST_BREATH, EVENT_SPAWN_SPECTRALS, EVENT_SPECTRAL_BLAST, EVENT_TAIL_LASH, EVENT_WILD_MAGIC, BossAI::JustEngagedWith(), ScriptedAI::me, SAY_EVIL_AGGRO, Unit::SetStandState(), and UNIT_STAND_STATE_STAND.
JustReachedHome()
void boss_kalecgos::boss_kalecgosAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
        {
            BossAI::JustReachedHome();
            me->SetVisible(true);
        }
References BossAI::JustReachedHome(), ScriptedAI::me, and Unit::SetVisible().
KilledUnit()
void boss_kalecgos::boss_kalecgosAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->IsPlayer() && roll_chance_i(50))
                Talk(SAY_EVIL_SLAY);
        }
References Object::IsPlayer(), roll_chance_i(), and SAY_EVIL_SLAY.
Reset()
void boss_kalecgos::boss_kalecgosAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            BossAI::Reset();
            me->SetHealth(me->GetMaxHealth());
            me->SetStandState(UNIT_STAND_STATE_SLEEP);
            me->SetDisableGravity(false);
            me->SetReactState(REACT_AGGRESSIVE);
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
            events2.Reset();
            sathBanished = false;
            ClearPlayerAuras();
        }
References ClearPlayerAuras(), events2, Unit::GetMaxHealth(), ScriptedAI::me, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), EventMap::Reset(), BossAI::Reset(), sathBanished, Creature::SetDisableGravity(), Unit::SetHealth(), Creature::SetReactState(), Unit::SetStandState(), UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_SLEEP.
UpdateAI()
void boss_kalecgos::boss_kalecgosAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            events2.Update(diff);
            switch (events2.ExecuteEvent())
            {
                case EVENT_TALK_GOOD_1:
                    me->SetRegeneratingHealth(false);
                    me->RemoveAllAuras();
                    me->SetReactState(REACT_PASSIVE);
                    me->CombatStop();
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->SetFaction(FACTION_FRIENDLY);
                    events2.ScheduleEvent(EVENT_TALK_GOOD_2, 1000);
                    break;
                case EVENT_TALK_GOOD_2:
                    if (Creature* Sath = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SATHROVARR)))
                    {
                        summons.Despawn(Sath);
                        Unit::Kill(me, Sath);
                    }
                    events2.ScheduleEvent(EVENT_TALK_GOOD_3, 8000);
                    break;
                case EVENT_TALK_GOOD_3:
                    Talk(SAY_GOOD_PLRWIN);
                    events2.ScheduleEvent(EVENT_TALK_GOOD_4, 10000);
                    break;
                case EVENT_TALK_GOOD_4:
                    me->SetDisableGravity(true);
                    me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                    events2.ScheduleEvent(EVENT_TALK_GOOD_5, 10000);
                    break;
                case EVENT_TALK_GOOD_5:
                    me->SetVisible(false);
                    me->KillSelf();
                    break;
                case EVENT_TALK_BAD_1:
                    me->SetReactState(REACT_PASSIVE);
                    me->CombatStop();
                    me->RemoveAllAuras();
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    Talk(SAY_EVIL_ENRAGE);
                    events2.ScheduleEvent(EVENT_TALK_BAD_2, 3000);
                    break;
                case EVENT_TALK_BAD_2:
                    me->SetDisableGravity(true);
                    me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                    events2.ScheduleEvent(EVENT_TALK_BAD_3, 15000);
                    break;
                case EVENT_TALK_BAD_3:
                    me->SetVisible(false);
                    EnterEvadeMode();
                    break;
            }
            if (!events2.Empty())
                return;
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_SPAWN_SPECTRALS:
                    me->SummonCreature(NPC_KALEC, 1702.21f, 931.7f, -74.56f, 5.07f, TEMPSUMMON_MANUAL_DESPAWN);
                    me->SummonCreature(NPC_SATHROVARR, 1704.62f, 927.78f, -73.9f, 2.0f, TEMPSUMMON_MANUAL_DESPAWN);
                    break;
                case EVENT_ARCANE_BUFFET:
                    me->CastSpell(me, SPELL_ARCANE_BUFFET, false);
                    events.ScheduleEvent(EVENT_ARCANE_BUFFET, 8000);
                    break;
                case EVENT_FROST_BREATH:
                    me->CastSpell(me->GetVictim(), SPELL_FROST_BREATH, false);
                    events.ScheduleEvent(EVENT_FROST_BREATH, 15000);
                    break;
                case EVENT_TAIL_LASH:
                    me->CastSpell(me->GetVictim(), SPELL_TAIL_LASH, false);
                    events.ScheduleEvent(EVENT_TAIL_LASH, 15000);
                    break;
                case EVENT_WILD_MAGIC:
                    me->CastCustomSpell(RAND(44978, 45001, 45002, 45004, 45006, 45010), SPELLVALUE_MAX_TARGETS, 1, me, false);
                    events.ScheduleEvent(EVENT_WILD_MAGIC, 20000);
                    break;
                case EVENT_SPECTRAL_BLAST:
                    me->CastSpell(me, SPELL_SPECTRAL_BLAST, false);
                    events.ScheduleEvent(EVENT_SPECTRAL_BLAST, urand(15000, 25000));
                    break;
                case EVENT_CHECK_POS:
                    if (me->GetDistance(me->GetHomePosition()) > 50.0f)
                    {
                        EnterEvadeMode();
                        return;
                    }
                    events.ScheduleEvent(EVENT_CHECK_POS, 5000);
                    break;
                case EVENT_CHECK_HEALTH:
                    if (me->HealthBelowPct(10))
                    {
                        if (Creature* Sath = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SATHROVARR)))
                            Sath->AI()->DoAction(ACTION_ENRAGE_OTHER);
                        DoAction(ACTION_ENRAGE);
                        break;
                    }
                    events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
                    break;
                case EVENT_CHECK_HEALTH2:
                    if (me->HealthBelowPct(1))
                    {
                        DoAction(ACTION_BANISH);
                        break;
                    }
                    events.ScheduleEvent(EVENT_CHECK_HEALTH2, 1000);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References ACTION_BANISH, ACTION_ENRAGE, ACTION_ENRAGE_OTHER, Unit::CastCustomSpell(), Unit::CastSpell(), Unit::CombatStop(), SummonList::Despawn(), DoAction(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_LIFTOFF, EventMap::Empty(), BossAI::EnterEvadeMode(), EVENT_ARCANE_BUFFET, EVENT_CHECK_HEALTH, EVENT_CHECK_HEALTH2, EVENT_CHECK_POS, EVENT_FROST_BREATH, EVENT_SPAWN_SPECTRALS, EVENT_SPECTRAL_BLAST, EVENT_TAIL_LASH, EVENT_TALK_BAD_1, EVENT_TALK_BAD_2, EVENT_TALK_BAD_3, EVENT_TALK_GOOD_1, EVENT_TALK_GOOD_2, EVENT_TALK_GOOD_3, EVENT_TALK_GOOD_4, EVENT_TALK_GOOD_5, EVENT_WILD_MAGIC, events2, EventMap::ExecuteEvent(), FACTION_FRIENDLY, ObjectAccessor::GetCreature(), WorldObject::GetDistance(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), Unit::GetVictim(), Unit::HandleEmoteCommand(), Unit::HasUnitState(), Unit::HealthBelowPct(), BossAI::instance, Unit::Kill(), Unit::KillSelf(), ScriptedAI::me, NPC_KALEC, NPC_SATHROVARR, RAND(), REACT_PASSIVE, Unit::RemoveAllAuras(), SAY_EVIL_ENRAGE, SAY_GOOD_PLRWIN, EventMap::ScheduleEvent(), Creature::SetDisableGravity(), Unit::SetFaction(), Creature::SetReactState(), Creature::SetRegeneratingHealth(), Unit::SetUnitFlag(), Unit::SetVisible(), SPELL_ARCANE_BUFFET, SPELL_FROST_BREATH, SPELL_SPECTRAL_BLAST, SPELL_TAIL_LASH, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), BossAI::summons, TEMPSUMMON_MANUAL_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events2
EventMap boss_kalecgos::boss_kalecgosAI::events2
Referenced by DoAction(), Reset(), and UpdateAI().
sathBanished
bool boss_kalecgos::boss_kalecgosAI::sathBanished
Referenced by DoAction(), and Reset().