AzerothCore: npc_akama_shade::npc_akamaAI Struct Reference
npc_akama_shade::npc_akamaAI Struct Reference
Public Member Functions
npc_akamaAI (Creature *creature)
void Reset () override
void MovementInform (uint32 type, uint32 point) override
void DoAction (int32 param) override
void JustDied (Unit *) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustSummoned (Creature *summon) override
void UpdateAI (uint32 diff) override
void sGossipSelect (Player *player, uint32, uint32 action) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
EventMap events
EventMap events2
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_akamaAI()
npc_akama_shade::npc_akamaAI::npc_akamaAI (Creature * creature) inline
                                        : ScriptedAI(creature), summons(me)
        {
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DoAction()
void npc_akama_shade::npc_akamaAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_SHADE_DIED)
                events2.ScheduleEvent(EVENT_AKAMA_SCENE0, 1000);
        }
References ACTION_SHADE_DIED, EVENT_AKAMA_SCENE0, events2, and EventMap::ScheduleEvent().
JustDied()
void npc_akama_shade::npc_akamaAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (Creature* shade = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SHADE_OF_AKAMA)))
                shade->AI()->DoAction(ACTION_AKAMA_DIED);
        }
References ACTION_AKAMA_DIED, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), instance, ScriptedAI::me, and NPC_SHADE_OF_AKAMA.
JustEngagedWith()
void npc_akama_shade::npc_akamaAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            events.ScheduleEvent(EVENT_SPELL_CHAIN_LIGHTNING, 2000);
            events.ScheduleEvent(EVENT_SPELL_DESTRUCTIVE_POISON, 5000);
        }
References EVENT_SPELL_CHAIN_LIGHTNING, and EVENT_SPELL_DESTRUCTIVE_POISON.
JustSummoned()
void npc_akama_shade::npc_akamaAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            float dist = frand(30.0f, 32.0f);
            summon->SetWalk(true);
            summon->GetMotionMaster()->MovePoint(POINT_START, summon->GetPositionX() + dist * cos(summon->GetOrientation()), summon->GetPositionY() + dist * std::sin(summon->GetOrientation()), summon->GetPositionZ(), false);
            summons.Summon(summon);
        }
References frand(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), MotionMaster::MovePoint(), POINT_START, Creature::SetWalk(), SummonList::Summon(), and summons.
MovementInform()
void npc_akama_shade::npc_akamaAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type != POINT_MOTION_TYPE || point != POINT_CHANNEL_SOUL)
                return;
            me->SetFacingTo(0.0f);
            events2.ScheduleEvent(EVENT_AKAMA_SCENE1, 1000);
            events2.ScheduleEvent(EVENT_AKAMA_SCENE2, 16500);
            events2.ScheduleEvent(EVENT_AKAMA_SCENE3, 17500);
            events2.ScheduleEvent(EVENT_AKAMA_SCENE4, 27000);
            events2.ScheduleEvent(EVENT_AKAMA_SCENE5, 37000);
            events2.ScheduleEvent(EVENT_AKAMA_SCENE6, 51000);
            events2.ScheduleEvent(EVENT_AKAMA_SCENE7, 56000);
        }
References EVENT_AKAMA_SCENE1, EVENT_AKAMA_SCENE2, EVENT_AKAMA_SCENE3, EVENT_AKAMA_SCENE4, EVENT_AKAMA_SCENE5, EVENT_AKAMA_SCENE6, EVENT_AKAMA_SCENE7, events2, ScriptedAI::me, POINT_CHANNEL_SOUL, POINT_MOTION_TYPE, EventMap::ScheduleEvent(), and Unit::SetFacingTo().
Reset()
void npc_akama_shade::npc_akamaAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            if (instance->GetBossState(DATA_SHADE_OF_AKAMA) == DONE)
            {
                me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                return;
            }
            me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            me->CastSpell(me, SPELL_STEALTH, true);
            events.Reset();
            events2.Reset();
        }
References Unit::CastSpell(), DATA_SHADE_OF_AKAMA, DONE, events2, InstanceScript::GetBossState(), instance, ScriptedAI::me, Unit::RemoveNpcFlag(), EventMap::Reset(), Unit::SetNpcFlag(), SPELL_STEALTH, and UNIT_NPC_FLAG_GOSSIP.
sGossipSelect()
void npc_akama_shade::npc_akamaAI::sGossipSelect (Player * player, uint32 , uint32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == 0)
            {
                CloseGossipMenuFor(player);
                me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                events2.ScheduleEvent(EVENT_AKAMA_START_ENCOUNTER, 0);
            }
        }
References CloseGossipMenuFor(), EVENT_AKAMA_START_ENCOUNTER, events2, ScriptedAI::me, Unit::RemoveNpcFlag(), EventMap::ScheduleEvent(), and UNIT_NPC_FLAG_GOSSIP.
UpdateAI()
void npc_akama_shade::npc_akamaAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            events2.Update(diff);
            switch (events2.ExecuteEvent())
            {
                case EVENT_AKAMA_START_ENCOUNTER:
                    me->RemoveAura(SPELL_STEALTH);
                    me->SetWalk(true);
                    me->GetMotionMaster()->MovePoint(POINT_START, 517.4877f, 400.7993f, 112.7837f, false);
                    events2.ScheduleEvent(EVENT_AKAMA_START_CHANNEL, 11000);
                    break;
                case EVENT_AKAMA_START_CHANNEL:
                    me->CastSpell(me, SPELL_AKAMA_SOUL_CHANNEL, false);
                    if (Creature* shade = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SHADE_OF_AKAMA)))
                    {
                        shade->AI()->AttackStart(me);
                        shade->GetMotionMaster()->Clear();
                        shade->AI()->DoAction(ACTION_START_ENCOUNTER);
                    }
                    break;
                case EVENT_AKAMA_SCENE0:
                    me->SetWalk(true);
                    me->GetMotionMaster()->MovePoint(POINT_CHANNEL_SOUL, 467.0f, 400.7993f, 118.537f);
                    break;
                case EVENT_AKAMA_SCENE1:
                    me->CastSpell(me, SPELL_AKAMA_SOUL_RETRIEVE, true);
                    break;
                case EVENT_AKAMA_SCENE2:
                    Talk(SAY_BROKEN_FREE_0);
                    break;
                case EVENT_AKAMA_SCENE3:
                    me->SummonCreatureGroup(SUMMON_GROUP_BROKENS);
                    break;
                case EVENT_AKAMA_SCENE4:
                    Talk(SAY_BROKEN_FREE_1);
                    break;
                case EVENT_AKAMA_SCENE5:
                    for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                        if (Creature* broken = ObjectAccessor::GetCreature(*me, *itr))
                            broken->SetStandState(UNIT_STAND_STATE_KNEEL);
                    Talk(SAY_BROKEN_FREE_2);
                    break;
                case EVENT_AKAMA_SCENE6:
                    if (Creature* broken = summons.GetCreatureWithEntry(NPC_ASHTONGUE_BROKEN))
                        broken->AI()->Talk(SAY_BROKEN_S1);
                    break;
                case EVENT_AKAMA_SCENE7:
                    for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                        if (Creature* broken = ObjectAccessor::GetCreature(*me, *itr))
                            broken->AI()->Talk(SAY_BROKEN_S2);
                    break;
            }
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_SPELL_CHAIN_LIGHTNING:
                    me->CastSpell(me->GetVictim(), SPELL_CHAIN_LIGHTNING, false);
                    events.ScheduleEvent(EVENT_SPELL_CHAIN_LIGHTNING, urand(10000, 15000));
                    break;
                case EVENT_SPELL_DESTRUCTIVE_POISON:
                    me->CastSpell(me, SPELL_DESTRUCTIVE_POISON, false);
                    events.ScheduleEvent(EVENT_SPELL_DESTRUCTIVE_POISON, urand(4000, 5000));
                    break;
            }
            DoMeleeAttackIfReady();
        }
References ACTION_START_ENCOUNTER, SummonList::begin(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), SummonList::end(), EVENT_AKAMA_SCENE0, EVENT_AKAMA_SCENE1, EVENT_AKAMA_SCENE2, EVENT_AKAMA_SCENE3, EVENT_AKAMA_SCENE4, EVENT_AKAMA_SCENE5, EVENT_AKAMA_SCENE6, EVENT_AKAMA_SCENE7, EVENT_AKAMA_START_CHANNEL, EVENT_AKAMA_START_ENCOUNTER, EVENT_SPELL_CHAIN_LIGHTNING, EVENT_SPELL_DESTRUCTIVE_POISON, events2, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), SummonList::GetCreatureWithEntry(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HasUnitState(), instance, ScriptedAI::me, MotionMaster::MovePoint(), NPC_ASHTONGUE_BROKEN, NPC_SHADE_OF_AKAMA, POINT_CHANNEL_SOUL, POINT_START, Unit::RemoveAura(), SAY_BROKEN_FREE_0, SAY_BROKEN_FREE_1, SAY_BROKEN_FREE_2, SAY_BROKEN_S1, SAY_BROKEN_S2, EventMap::ScheduleEvent(), Creature::SetWalk(), SPELL_AKAMA_SOUL_CHANNEL, SPELL_AKAMA_SOUL_RETRIEVE, SPELL_CHAIN_LIGHTNING, SPELL_DESTRUCTIVE_POISON, SPELL_STEALTH, SUMMON_GROUP_BROKENS, WorldObject::SummonCreatureGroup(), summons, UNIT_STAND_STATE_KNEEL, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap npc_akama_shade::npc_akamaAI::events
events2
EventMap npc_akama_shade::npc_akamaAI::events2
Referenced by DoAction(), MovementInform(), Reset(), sGossipSelect(), and UpdateAI().
instance
InstanceScript* npc_akama_shade::npc_akamaAI::instance
Referenced by JustDied(), npc_akamaAI(), Reset(), and UpdateAI().
summons
SummonList npc_akama_shade::npc_akamaAI::summons
Referenced by JustSummoned(), and UpdateAI().