AzerothCore: GameEventMgr Class Reference
GameEventMgr Class Reference
#include "GameEventMgr.h"
Public Types
typedef std::set< uint16 > ActiveEvents
typedef std::vector< GameEventData > GameEventDataMap
Public Member Functions
ActiveEvents const & GetActiveEventList () const
GameEventDataMap const & GetEventMap () const
bool CheckOneGameEvent (uint16 entry) const
uint32 NextCheck (uint16 entry) const
void LoadFromDB ()
void LoadHolidayDates ()
uint32 Update ()
bool IsActiveEvent (uint16 event_id)
uint32 StartSystem ()
void Initialize ()
void StartArenaSeason ()
void StartInternalEvent (uint16 event_id)
bool StartEvent (uint16 event_id, bool overwrite=false)
void StopEvent (uint16 event_id, bool overwrite=false)
void HandleQuestComplete (uint32 quest_id)
uint32 GetNPCFlag (Creature *cr)
void LoadEventVendors ()
uint32 GetHolidayEventId (uint32 holidayId) const
Static Public Member Functions
static GameEventMgr * instance ()
Public Attributes
GameEventGuidMap mGameEventCreatureGuids
GameEventGuidMap mGameEventGameobjectGuids
std::vector< uint32 > modifiedHolidays
Private Types
typedef std::list< ObjectGuid::LowType > GuidLowList
typedef std::list< uint32 > IdList
typedef std::vector< GuidLowList > GameEventGuidMap
typedef std::vector< IdList > GameEventIdMap
typedef std::pair< ObjectGuid::LowType, ModelEquip > ModelEquipPair
typedef std::list< ModelEquipPair > ModelEquipList
typedef std::vector< ModelEquipList > GameEventModelEquipMap
typedef std::pair< uint32, uint32 > QuestRelation
typedef std::list< QuestRelation > QuestRelList
typedef std::vector< QuestRelList > GameEventQuestMap
typedef std::list< NPCVendorEntry > NPCVendorList
typedef std::vector< NPCVendorList > GameEventNPCVendorMap
typedef std::map< uint32, GameEventQuestToEventConditionNum > QuestIdToEventConditionMap
typedef std::pair< ObjectGuid::LowType, uint32 > GuidNPCFlagPair
typedef std::list< GuidNPCFlagPair > NPCFlagList
typedef std::vector< NPCFlagList > GameEventNPCFlagMap
typedef std::vector< uint32 > GameEventBitmask
typedef std::unordered_map< uint32, std::vector< uint32 > > GameEventSeasonalQuestsMap
Private Member Functions
GameEventMgr ()
~GameEventMgr ()=default
void SendWorldStateUpdate (Player *player, uint16 event_id)
void AddActiveEvent (uint16 event_id)
void RemoveActiveEvent (uint16 event_id)
void ApplyNewEvent (uint16 event_id)
void UnApplyEvent (uint16 event_id)
void GameEventSpawn (int16 event_id)
void GameEventUnspawn (int16 event_id)
void ChangeEquipOrModel (int16 event_id, bool activate)
void UpdateEventQuests (uint16 event_id, bool activate)
void UpdateWorldStates (uint16 event_id, bool Activate)
void UpdateEventNPCFlags (uint16 event_id)
void UpdateEventNPCVendor (uint16 event_id, bool activate)
void UpdateBattlegroundSettings ()
void RunSmartAIScripts (uint16 event_id, bool activate)
bool CheckOneGameEventConditions (uint16 event_id)
Runs SMART_EVENT_GAME_EVENT_START/_END SAI.
void SaveWorldEventStateToDB (uint16 event_id)
bool hasCreatureQuestActiveEventExcept (uint32 quest_id, uint16 event_id)
bool hasGameObjectQuestActiveEventExcept (uint32 quest_id, uint16 event_id)
bool hasCreatureActiveEventExcept (ObjectGuid::LowType creature_guid, uint16 event_id)
bool hasGameObjectActiveEventExcept (ObjectGuid::LowType go_guid, uint16 event_id)
void SetHolidayEventTime (GameEventData &event)
Private Attributes
GameEventQuestMap mGameEventCreatureQuests
GameEventQuestMap mGameEventGameObjectQuests
GameEventNPCVendorMap mGameEventVendors
GameEventModelEquipMap mGameEventModelEquip
GameEventIdMap mGameEventPoolIds
GameEventDataMap mGameEvent
GameEventBitmask mGameEventBattlegroundHolidays
QuestIdToEventConditionMap mQuestToEventConditions
GameEventNPCFlagMap mGameEventNPCFlags
ActiveEvents m_ActiveEvents
bool isSystemInit
GameEventSeasonalQuestsMap _gameEventSeasonalQuestsMap
Detailed Description
Member Typedef Documentation
ActiveEvents
typedef std::set<uint16> GameEventMgr::ActiveEvents
GameEventBitmask
typedef std::vector<uint32> GameEventMgr::GameEventBitmask private
GameEventDataMap
typedef std::vector<GameEventData> GameEventMgr::GameEventDataMap
GameEventGuidMap
typedef std::vector<GuidLowList> GameEventMgr::GameEventGuidMap private
GameEventIdMap
typedef std::vector<IdList> GameEventMgr::GameEventIdMap private
GameEventModelEquipMap
typedef std::vector<ModelEquipList> GameEventMgr::GameEventModelEquipMap private
GameEventNPCFlagMap
typedef std::vector<NPCFlagList> GameEventMgr::GameEventNPCFlagMap private
GameEventNPCVendorMap
typedef std::vector<NPCVendorList> GameEventMgr::GameEventNPCVendorMap private
GameEventQuestMap
typedef std::vector<QuestRelList> GameEventMgr::GameEventQuestMap private
GameEventSeasonalQuestsMap
typedef std::unordered_map<uint32, std::vector<uint32> > GameEventMgr::GameEventSeasonalQuestsMap private
GuidLowList
typedef std::list<ObjectGuid::LowType> GameEventMgr::GuidLowList private
GuidNPCFlagPair
typedef std::pair<ObjectGuid::LowType , uint32 > GameEventMgr::GuidNPCFlagPair private
IdList
typedef std::list<uint32> GameEventMgr::IdList private
ModelEquipList
typedef std::list<ModelEquipPair> GameEventMgr::ModelEquipList private
ModelEquipPair
typedef std::pair<ObjectGuid::LowType, ModelEquip> GameEventMgr::ModelEquipPair private
NPCFlagList
typedef std::list<GuidNPCFlagPair> GameEventMgr::NPCFlagList private
NPCVendorList
typedef std::list<NPCVendorEntry> GameEventMgr::NPCVendorList private
QuestIdToEventConditionMap
typedef std::map<uint32 , GameEventQuestToEventConditionNum> GameEventMgr::QuestIdToEventConditionMap private
QuestRelation
typedef std::pair<uint32, uint32> GameEventMgr::QuestRelation private
QuestRelList
typedef std::list<QuestRelation> GameEventMgr::QuestRelList private
Constructor & Destructor Documentation
GameEventMgr()
GameEventMgr::GameEventMgr () private
                           : isSystemInit(false)
{
}
~GameEventMgr()
GameEventMgr::~GameEventMgr () private default
Member Function Documentation
AddActiveEvent()
void GameEventMgr::AddActiveEvent (uint16 event_id) inline private
{ m_ActiveEvents.insert(event_id); }
References m_ActiveEvents.
Referenced by StartEvent().
ApplyNewEvent()
void GameEventMgr::ApplyNewEvent (uint16 event_id) private
Run SAI scripts with SMART_EVENT_GAME_EVENT_START
{
    uint8 announce = mGameEvent[event_id].announce;
    if (announce == 1 || (announce == 2 && sWorld->getIntConfig(CONFIG_EVENT_ANNOUNCE)))
        ChatHandler(nullptr).SendWorldText(LANG_EVENTMESSAGE, mGameEvent[event_id].description);
    LOG_DEBUG("gameevent", "GameEvent {} \"{}\" started.", event_id, mGameEvent[event_id].description);
    // spawn positive event tagget objects
    GameEventSpawn(event_id);
    // un-spawn negative event tagged objects
    int16 event_nid = (-1) * event_id;
    GameEventUnspawn(event_nid);
    // Change equipement or model
    ChangeEquipOrModel(event_id, true);
    // Add quests that are events only to non event npc
    UpdateEventQuests(event_id, true);
    UpdateWorldStates(event_id, true);
    // update npcflags in this event
    UpdateEventNPCFlags(event_id);
    // add vendor items
    UpdateEventNPCVendor(event_id, true);
    // update bg holiday
    UpdateBattlegroundSettings();
    RunSmartAIScripts(event_id, true);
    // If event's worldstate is 0, it means the event hasn't been started yet. In that case, reset seasonal quests.
    // When event ends (if it expires or if it's stopped via commands) worldstate will be set to 0 again, ready for another seasonal quest reset.
    if (sWorld->getWorldState(event_id) == 0)
    {
        sWorld->ResetEventSeasonalQuests(event_id);
    }
}
References ChangeEquipOrModel(), CONFIG_EVENT_ANNOUNCE, GameEventSpawn(), GameEventUnspawn(), LANG_EVENTMESSAGE, LOG_DEBUG, mGameEvent, RunSmartAIScripts(), ChatHandler::SendWorldText(), sWorld, UpdateBattlegroundSettings(), UpdateEventNPCFlags(), UpdateEventNPCVendor(), UpdateEventQuests(), and UpdateWorldStates().
Referenced by StartEvent().
ChangeEquipOrModel()
void GameEventMgr::ChangeEquipOrModel (int16 event_id, bool activate) private
{
    for (ModelEquipList::iterator itr = mGameEventModelEquip[event_id].begin(); itr != mGameEventModelEquip[event_id].end(); ++itr)
    {
        // Remove the creature from grid
        CreatureData const* data = sObjectMgr->GetCreatureData(itr->first);
        if (!data)
            continue;
        // Update if spawned
        sMapMgr->DoForAllMapsWithMapId(data->mapid, [&itr, activate](Map* map)
        {
            auto creatureBounds = map->GetCreatureBySpawnIdStore().equal_range(itr->first);
            for (auto itr2 = creatureBounds.first; itr2 != creatureBounds.second; ++itr2)
            {
                Creature* creature = itr2->second;
                if (activate)
                {
                    itr->second.equipement_id_prev = creature->GetCurrentEquipmentId();
                    itr->second.modelid_prev = creature->GetDisplayId();
                    creature->LoadEquipment(itr->second.equipment_id, true);
                    if (itr->second.modelid > 0 && itr->second.modelid_prev != itr->second.modelid && sObjectMgr->GetCreatureModelInfo(itr->second.modelid))
                    {
                        creature->SetDisplayId(itr->second.modelid);
                        creature->SetNativeDisplayId(itr->second.modelid);
                    }
                }
                else
                {
                    creature->LoadEquipment(itr->second.equipement_id_prev, true);
                    if (itr->second.modelid_prev > 0 && itr->second.modelid_prev != itr->second.modelid && sObjectMgr->GetCreatureModelInfo(itr->second.modelid_prev))
                    {
                        creature->SetDisplayId(itr->second.modelid_prev);
                        creature->SetNativeDisplayId(itr->second.modelid_prev);
                    }
                }
            }
        });
        // now last step: put in data
        // just to have write access to it
        CreatureData& data2 = sObjectMgr->NewOrExistCreatureData(itr->first);
        if (activate)
        {
            itr->second.modelid_prev = data2.displayid;
            itr->second.equipement_id_prev = data2.equipmentId;
            data2.displayid = itr->second.modelid;
            data2.equipmentId = itr->second.equipment_id;
        }
        else
        {
            data2.displayid = itr->second.modelid_prev;
            data2.equipmentId = itr->second.equipement_id_prev;
        }
    }
}
References CreatureData::displayid, CreatureData::equipmentId, CreatureData::mapid, mGameEventModelEquip, sMapMgr, and sObjectMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
CheckOneGameEvent()
bool GameEventMgr::CheckOneGameEvent (uint16 entry) const
{
    switch (mGameEvent[entry].state)
    {
        default:
        case GAMEEVENT_NORMAL:
            {
                time_t currenttime = GameTime::GetGameTime().count();
                // Get the event information
                return mGameEvent[entry].start < currenttime
                       && currenttime < mGameEvent[entry].end
                       && (currenttime - mGameEvent[entry].start) % (mGameEvent[entry].occurence * MINUTE) < mGameEvent[entry].length * MINUTE;
            }
        // if the state is conditions or nextphase, then the event should be active
        case GAMEEVENT_WORLD_CONDITIONS:
        case GAMEEVENT_WORLD_NEXTPHASE:
            return true;
        // finished world events are inactive
        case GAMEEVENT_WORLD_FINISHED:
        case GAMEEVENT_INTERNAL:
            return false;
        // if inactive world event, check the prerequisite events
        case GAMEEVENT_WORLD_INACTIVE:
            {
                time_t currenttime = GameTime::GetGameTime().count();
                for (std::set<uint16>::const_iterator itr = mGameEvent[entry].prerequisite_events.begin(); itr != mGameEvent[entry].prerequisite_events.end(); ++itr)
                {
                    if ((mGameEvent[*itr].state != GAMEEVENT_WORLD_NEXTPHASE && mGameEvent[*itr].state != GAMEEVENT_WORLD_FINISHED) ||   // if prereq not in nextphase or finished state, then can't start this one
                            mGameEvent[*itr].nextstart > currenttime)               // if not in nextphase state for long enough, can't start this one
                        return false;
                }
                // all prerequisite events are met
                // but if there are no prerequisites, this can be only activated through gm command
                return !(mGameEvent[entry].prerequisite_events.empty());
            }
    }
}
References GAMEEVENT_INTERNAL, GAMEEVENT_NORMAL, GAMEEVENT_WORLD_CONDITIONS, GAMEEVENT_WORLD_FINISHED, GAMEEVENT_WORLD_INACTIVE, GAMEEVENT_WORLD_NEXTPHASE, GameTime::GetGameTime(), mGameEvent, and MINUTE.
Referenced by Update().
CheckOneGameEventConditions()
bool GameEventMgr::CheckOneGameEventConditions (uint16 event_id) private
Runs SMART_EVENT_GAME_EVENT_START/_END SAI.
{
    for (GameEventConditionMap::const_iterator itr = mGameEvent[event_id].conditions.begin(); itr != mGameEvent[event_id].conditions.end(); ++itr)
        if (itr->second.done < itr->second.reqNum)
            // return false if a condition doesn't match
            return false;
    // set the phase
    mGameEvent[event_id].state = GAMEEVENT_WORLD_NEXTPHASE;
    // set the followup events' start time
    if (!mGameEvent[event_id].nextstart)
    {
        time_t currenttime = GameTime::GetGameTime().count();
        mGameEvent[event_id].nextstart = currenttime + mGameEvent[event_id].length * 60;
    }
    return true;
}
References GAMEEVENT_WORLD_NEXTPHASE, GameTime::GetGameTime(), and mGameEvent.
Referenced by HandleQuestComplete(), StartEvent(), and Update().
GameEventSpawn()
void GameEventMgr::GameEventSpawn (int16 event_id) private
{
    int32 internal_event_id = mGameEvent.size() + event_id - 1;
    if (internal_event_id < 0 || internal_event_id >= int32(mGameEventCreatureGuids.size()))
    {
        LOG_ERROR("gameevent", "GameEventMgr::GameEventSpawn attempt access to out of range mGameEventCreatureGuids element {} (size: {})",
                       internal_event_id, mGameEventCreatureGuids.size());
        return;
    }
    for (GuidLowList::iterator itr = mGameEventCreatureGuids[internal_event_id].begin(); itr != mGameEventCreatureGuids[internal_event_id].end(); ++itr)
    {
        // Add to correct cell
        if (CreatureData const* data = sObjectMgr->GetCreatureData(*itr))
        {
            sObjectMgr->AddCreatureToGrid(*itr, data);
            // Spawn if necessary (loaded grids only)
            Map* map = sMapMgr->CreateBaseMap(data->mapid);
            // We use spawn coords to spawn
            if (!map->Instanceable() && map->IsGridLoaded(data->posX, data->posY))
            {
                Creature* creature = new Creature;
                if (!creature->LoadCreatureFromDB(*itr, map))
                    delete creature;
            }
        }
    }
    if (internal_event_id >= int32(mGameEventGameobjectGuids.size()))
    {
        LOG_ERROR("gameevent", "GameEventMgr::GameEventSpawn attempt access to out of range mGameEventGameobjectGuids element {} (size: {})",
                       internal_event_id, mGameEventGameobjectGuids.size());
        return;
    }
    for (GuidLowList::iterator itr = mGameEventGameobjectGuids[internal_event_id].begin(); itr != mGameEventGameobjectGuids[internal_event_id].end(); ++itr)
    {
        // Add to correct cell
        if (GameObjectData const* data = sObjectMgr->GetGameObjectData(*itr))
        {
            sObjectMgr->AddGameobjectToGrid(*itr, data);
            // Spawn if necessary (loaded grids only)
            // this base map checked as non-instanced and then only existed
            Map* map = sMapMgr->CreateBaseMap(data->mapid);
            // We use current coords to unspawn, not spawn coords since creature can have changed grid
            if (!map->Instanceable() && map->IsGridLoaded(data->posX, data->posY))
            {
                GameObject* pGameobject = sObjectMgr->IsGameObjectStaticTransport(data->id) ? new StaticTransport() : new GameObject();
                //TODO: find out when it is add to map
                if (!pGameobject->LoadGameObjectFromDB(*itr, map, false))
                    delete pGameobject;
                else
                {
                    if (pGameobject->isSpawnedByDefault())
                        map->AddToMap(pGameobject);
                }
            }
        }
    }
    if (internal_event_id >= int32(mGameEventPoolIds.size()))
    {
        LOG_ERROR("gameevent", "GameEventMgr::GameEventSpawn attempt access to out of range mGameEventPoolIds element {} (size: {})",
                       internal_event_id, mGameEventPoolIds.size());
        return;
    }
    for (IdList::iterator itr = mGameEventPoolIds[internal_event_id].begin(); itr != mGameEventPoolIds[internal_event_id].end(); ++itr)
        sPoolMgr->SpawnPool(*itr);
}
References Map::AddToMap(), Map::Instanceable(), Map::IsGridLoaded(), GameObject::isSpawnedByDefault(), Creature::LoadCreatureFromDB(), GameObject::LoadGameObjectFromDB(), LOG_ERROR, mGameEvent, mGameEventCreatureGuids, mGameEventGameobjectGuids, mGameEventPoolIds, sMapMgr, sObjectMgr, and sPoolMgr.
Referenced by ApplyNewEvent(), UnApplyEvent(), and Update().
GameEventUnspawn()
void GameEventMgr::GameEventUnspawn (int16 event_id) private
{
    int32 internal_event_id = mGameEvent.size() + event_id - 1;
    if (internal_event_id < 0 || internal_event_id >= int32(mGameEventCreatureGuids.size()))
    {
        LOG_ERROR("gameevent", "GameEventMgr::GameEventUnspawn attempt access to out of range mGameEventCreatureGuids element {} (size: {})",
                       internal_event_id, mGameEventCreatureGuids.size());
        return;
    }
    for (GuidLowList::iterator itr = mGameEventCreatureGuids[internal_event_id].begin(); itr != mGameEventCreatureGuids[internal_event_id].end(); ++itr)
    {
        // check if it's needed by another event, if so, don't remove
        if (event_id > 0 && hasCreatureActiveEventExcept(*itr, event_id))
            continue;
        // Remove the creature from grid
        if (CreatureData const* data = sObjectMgr->GetCreatureData(*itr))
        {
            sObjectMgr->RemoveCreatureFromGrid(*itr, data);
            sMapMgr->DoForAllMapsWithMapId(data->mapid, [&itr](Map* map)
            {
                auto creatureBounds = map->GetCreatureBySpawnIdStore().equal_range(*itr);
                for (auto itr2 = creatureBounds.first; itr2 != creatureBounds.second;)
                {
                    Creature* creature = itr2->second;
                    ++itr2;
                    creature->AddObjectToRemoveList();
                }
            });
        }
    }
    if (internal_event_id >= int32(mGameEventGameobjectGuids.size()))
    {
        LOG_ERROR("gameevent", "GameEventMgr::GameEventUnspawn attempt access to out of range mGameEventGameobjectGuids element {} (size: {})",
                       internal_event_id, mGameEventGameobjectGuids.size());
        return;
    }
    for (GuidLowList::iterator itr = mGameEventGameobjectGuids[internal_event_id].begin(); itr != mGameEventGameobjectGuids[internal_event_id].end(); ++itr)
    {
        // check if it's needed by another event, if so, don't remove
        if (event_id > 0 && hasGameObjectActiveEventExcept(*itr, event_id))
            continue;
        // Remove the gameobject from grid
        if (GameObjectData const* data = sObjectMgr->GetGameObjectData(*itr))
        {
            sObjectMgr->RemoveGameobjectFromGrid(*itr, data);
            sMapMgr->DoForAllMapsWithMapId(data->mapid, [&itr](Map* map)
            {
                auto gameobjectBounds = map->GetGameObjectBySpawnIdStore().equal_range(*itr);
                for (auto itr2 = gameobjectBounds.first; itr2 != gameobjectBounds.second;)
                {
                    GameObject* go = itr2->second;
                    ++itr2;
                    go->AddObjectToRemoveList();
                }
            });
        }
    }
    if (internal_event_id >= int32(mGameEventPoolIds.size()))
    {
        LOG_ERROR("gameevent", "GameEventMgr::GameEventUnspawn attempt access to out of range mGameEventPoolIds element {} (size: {})", internal_event_id, mGameEventPoolIds.size());
        return;
    }
    for (IdList::iterator itr = mGameEventPoolIds[internal_event_id].begin(); itr != mGameEventPoolIds[internal_event_id].end(); ++itr)
    {
        sPoolMgr->DespawnPool(*itr);
    }
}
References hasCreatureActiveEventExcept(), LOG_ERROR, mGameEvent, mGameEventCreatureGuids, sMapMgr, and sObjectMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
GetActiveEventList()
ActiveEvents const & GameEventMgr::GetActiveEventList () const inline
{ return m_ActiveEvents; }
References m_ActiveEvents.
GetEventMap()
GameEventDataMap const & GameEventMgr::GetEventMap () const inline
{ return mGameEvent; }
References mGameEvent.
GetHolidayEventId()
uint32 GameEventMgr::GetHolidayEventId (uint32 holidayId) const
{
    auto const& events = sGameEventMgr->GetEventMap();
    for (auto const& eventEntry : events)
    {
        if (eventEntry.holiday_id == holidayId)
        {
            return eventEntry.eventId;
        }
    }
    return 0;
}
References sGameEventMgr.
GetNPCFlag()
uint32 GameEventMgr::GetNPCFlag (Creature * cr)
{
    uint32 mask = 0;
    ObjectGuid::LowType spawnId = cr->GetSpawnId();
    for (ActiveEvents::iterator e_itr = m_ActiveEvents.begin(); e_itr != m_ActiveEvents.end(); ++e_itr)
    {
        for (NPCFlagList::iterator itr = mGameEventNPCFlags[*e_itr].begin(); itr != mGameEventNPCFlags[*e_itr].end(); ++ itr)
            if (itr->first == spawnId)
                mask |= itr->second;
    }
    return mask;
}
References Creature::GetSpawnId(), m_ActiveEvents, and mGameEventNPCFlags.
HandleQuestComplete()
void GameEventMgr::HandleQuestComplete (uint32 quest_id)
{
    // translate the quest to event and condition
    QuestIdToEventConditionMap::iterator itr = mQuestToEventConditions.find(quest_id);
    // quest is registered
    if (itr != mQuestToEventConditions.end())
    {
        uint16 event_id = itr->second.event_id;
        uint32 condition = itr->second.condition;
        float num = itr->second.num;
        // the event is not active, so return, don't increase condition finishes
        if (!IsActiveEvent(event_id))
            return;
        // not in correct phase, return
        if (mGameEvent[event_id].state != GAMEEVENT_WORLD_CONDITIONS)
            return;
        GameEventConditionMap::iterator citr = mGameEvent[event_id].conditions.find(condition);
        // condition is registered
        if (citr != mGameEvent[event_id].conditions.end())
        {
            // increase the done count, only if less then the req
            if (citr->second.done < citr->second.reqNum)
            {
                citr->second.done += num;
                // check max limit
                if (citr->second.done > citr->second.reqNum)
                    citr->second.done = citr->second.reqNum;
                // save the change to db
                CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
                CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GAME_EVENT_CONDITION_SAVE);
                stmt->SetData(0, uint8(event_id));
                stmt->SetData(1, condition);
                trans->Append(stmt);
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GAME_EVENT_CONDITION_SAVE);
                stmt->SetData(0, uint8(event_id));
                stmt->SetData(1, condition);
                stmt->SetData(2, citr->second.done);
                trans->Append(stmt);
                CharacterDatabase.CommitTransaction(trans);
                // check if all conditions are met, if so, update the event state
                if (CheckOneGameEventConditions(event_id))
                {
                    // changed, save to DB the gameevent state
                    SaveWorldEventStateToDB(event_id);
                    // force update events to set timer
                    sWorld->ForceGameEventUpdate();
                }
            }
        }
    }
}
References CHAR_DEL_GAME_EVENT_CONDITION_SAVE, CHAR_INS_GAME_EVENT_CONDITION_SAVE, CharacterDatabase, CheckOneGameEventConditions(), GAMEEVENT_WORLD_CONDITIONS, IsActiveEvent(), mGameEvent, mQuestToEventConditions, SaveWorldEventStateToDB(), PreparedStatementBase::SetData(), and sWorld.
hasCreatureActiveEventExcept()
bool GameEventMgr::hasCreatureActiveEventExcept (ObjectGuid::LowType creature_guid, uint16 event_id) private
{
    for (ActiveEvents::iterator e_itr = m_ActiveEvents.begin(); e_itr != m_ActiveEvents.end(); ++e_itr)
    {
        if ((*e_itr) != event_id)
        {
            int32 internal_event_id = mGameEvent.size() + (*e_itr) - 1;
            for (GuidLowList::iterator itr = mGameEventCreatureGuids[internal_event_id].begin(); itr != mGameEventCreatureGuids[internal_event_id].end(); ++ itr)
                if (*itr == creature_guid)
                    return true;
        }
    }
    return false;
}
References m_ActiveEvents, mGameEvent, and mGameEventCreatureGuids.
Referenced by GameEventUnspawn().
hasCreatureQuestActiveEventExcept()
bool GameEventMgr::hasCreatureQuestActiveEventExcept (uint32 quest_id, uint16 event_id) private
{
    for (ActiveEvents::iterator e_itr = m_ActiveEvents.begin(); e_itr != m_ActiveEvents.end(); ++e_itr)
    {
        if ((*e_itr) != event_id)
            for (QuestRelList::iterator itr = mGameEventCreatureQuests[*e_itr].begin();
                    itr != mGameEventCreatureQuests[*e_itr].end();
                    ++ itr)
                if (itr->second == quest_id)
                    return true;
    }
    return false;
}
References m_ActiveEvents, and mGameEventCreatureQuests.
Referenced by UpdateEventQuests().
hasGameObjectActiveEventExcept()
bool GameEventMgr::hasGameObjectActiveEventExcept (ObjectGuid::LowType go_guid, uint16 event_id) private
{
    for (ActiveEvents::iterator e_itr = m_ActiveEvents.begin(); e_itr != m_ActiveEvents.end(); ++e_itr)
    {
        if ((*e_itr) != event_id)
        {
            int32 internal_event_id = mGameEvent.size() + (*e_itr) - 1;
            for (GuidLowList::iterator itr = mGameEventGameobjectGuids[internal_event_id].begin(); itr != mGameEventGameobjectGuids[internal_event_id].end(); ++ itr)
                if (*itr == go_guid)
                    return true;
        }
    }
    return false;
}
References m_ActiveEvents, mGameEvent, and mGameEventGameobjectGuids.
hasGameObjectQuestActiveEventExcept()
bool GameEventMgr::hasGameObjectQuestActiveEventExcept (uint32 quest_id, uint16 event_id) private
{
    for (ActiveEvents::iterator e_itr = m_ActiveEvents.begin(); e_itr != m_ActiveEvents.end(); ++e_itr)
    {
        if ((*e_itr) != event_id)
            for (QuestRelList::iterator itr = mGameEventGameObjectQuests[*e_itr].begin();
                    itr != mGameEventGameObjectQuests[*e_itr].end();
                    ++ itr)
                if (itr->second == quest_id)
                    return true;
    }
    return false;
}
References m_ActiveEvents, and mGameEventGameObjectQuests.
Referenced by UpdateEventQuests().
Initialize()
void GameEventMgr::Initialize ()
{
    QueryResult result = WorldDatabase.Query("SELECT MAX(eventEntry) FROM game_event");
    if (result)
    {
        Field* fields = result->Fetch();
        uint32 maxEventId = fields[0].Get<uint8>();
        // Id starts with 1 and vector with 0, thus increment
        maxEventId++;
        mGameEvent.resize(maxEventId);
        mGameEventCreatureGuids.resize(maxEventId * 2 - 1);
        mGameEventGameobjectGuids.resize(maxEventId * 2 - 1);
        mGameEventCreatureQuests.resize(maxEventId);
        mGameEventGameObjectQuests.resize(maxEventId);
        mGameEventVendors.resize(maxEventId);
        mGameEventBattlegroundHolidays.resize(maxEventId, 0);
        mGameEventPoolIds.resize(maxEventId * 2 - 1);
        mGameEventNPCFlags.resize(maxEventId);
        mGameEventModelEquip.resize(maxEventId);
    }
}
References Field::Get(), mGameEvent, mGameEventBattlegroundHolidays, mGameEventCreatureGuids, mGameEventCreatureQuests, mGameEventGameobjectGuids, mGameEventGameObjectQuests, mGameEventModelEquip, mGameEventNPCFlags, mGameEventPoolIds, mGameEventVendors, and WorldDatabase.
instance()
GameEventMgr * GameEventMgr::instance () static
{
    static GameEventMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
IsActiveEvent()
bool GameEventMgr::IsActiveEvent (uint16 event_id) inline
{ return (m_ActiveEvents.find(event_id) != m_ActiveEvents.end()); }
References m_ActiveEvents.
Referenced by HandleQuestComplete(), StartEvent(), StopEvent(), and Update().
LoadEventVendors()
void GameEventMgr::LoadEventVendors ()
{
    uint32 oldMSTime = getMSTime();
    WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_GAME_EVENT_NPC_VENDOR);
    PreparedQueryResult result = WorldDatabase.Query(stmt);
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 Vendor Additions In Game Events. DB Table `game_event_npc_vendor` Is Empty.");
        LOG_INFO("server.loading", " ");
        return;
    }
    uint32 count = 0;
    std::unordered_set<uint8> processedEvents;
    do
    {
        Field* fields = result->Fetch();
        uint8 eventId = fields[0].Get<uint8>();
        ObjectGuid::LowType guid = fields[1].Get<uint32>();
        if (eventId >= mGameEventVendors.size())
        {
            LOG_ERROR("sql.sql", "Table `game_event_npc_vendor` has invalid eventEntry ({}) for GUID ({}), skipped.", eventId, guid);
            continue;
        }
        // Clear existing vendors for this event only once
        if (processedEvents.find(eventId) == processedEvents.end())
        {
            // Remove vendor items from in-memory data
            for (auto& entry : mGameEventVendors[eventId])
            {
                sObjectMgr->RemoveVendorItem(entry.entry, entry.item, false);
            }
            mGameEventVendors[eventId].clear();
            processedEvents.insert(eventId);
        }
        NPCVendorList& vendors = mGameEventVendors[eventId];
        NPCVendorEntry newEntry;
        newEntry.item = fields[2].Get<uint32>();
        newEntry.maxcount = fields[3].Get<uint32>();
        newEntry.incrtime = fields[4].Get<uint32>();
        newEntry.ExtendedCost = fields[5].Get<uint32>();
        // Get the event NPC flag for validity check
        uint32 event_npc_flag = 0;
        NPCFlagList& flist = mGameEventNPCFlags[eventId];
        for (NPCFlagList::const_iterator itr = flist.begin(); itr != flist.end(); ++itr)
        {
            if (itr->first == guid)
            {
                event_npc_flag = itr->second;
                break;
            }
        }
        // Get creature entry
        newEntry.entry = 0;
        if (CreatureData const* data = sObjectMgr->GetCreatureData(guid))
            newEntry.entry = data->id1;
        // Validate vendor item
        if (!sObjectMgr->IsVendorItemValid(newEntry.entry, newEntry.item, newEntry.maxcount, newEntry.incrtime, newEntry.ExtendedCost, nullptr, nullptr, event_npc_flag))
        {
            LOG_ERROR("sql.sql", "Table `game_event_npc_vendor` has invalid item ({}) for guid ({}) for event ({}), skipped.",
                newEntry.item, newEntry.entry, eventId);
            continue;
        }
        // Add the item to the vendor if event is active
        if (IsEventActive(eventId))
            sObjectMgr->AddVendorItem(newEntry.entry, newEntry.item, newEntry.maxcount, newEntry.incrtime, newEntry.ExtendedCost, false);
        vendors.push_back(newEntry);
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} Vendor Additions In Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References NPCVendorEntry::entry, NPCVendorEntry::ExtendedCost, Field::Get(), getMSTime(), GetMSTimeDiffToNow(), NPCVendorEntry::incrtime, IsEventActive(), NPCVendorEntry::item, LOG_ERROR, LOG_INFO, LOG_WARN, NPCVendorEntry::maxcount, mGameEventNPCFlags, mGameEventVendors, sObjectMgr, WORLD_SEL_GAME_EVENT_NPC_VENDOR, and WorldDatabase.
Referenced by LoadFromDB().
LoadFromDB()
void GameEventMgr::LoadFromDB ()
Todo:
: Change to uint8
{
    {
        uint32 oldMSTime = getMSTime();
        //                                                    1                 2                           3                  4        5        6          7             8            9          10
        QueryResult result = WorldDatabase.Query("SELECT eventEntry, UNIX_TIMESTAMP(start_time), UNIX_TIMESTAMP(end_time), occurence, length, holiday, holidayStage, description, world_event, announce FROM game_event");
        if (!result)
        {
            mGameEvent.clear();
            LOG_WARN("server.loading", ">> Loaded 0 game events. DB table `game_event` is empty.");
            LOG_INFO("server.loading", " ");
            return;
        }
        uint32 count = 0;
        do
        {
            Field* fields = result->Fetch();
            uint8 event_id = fields[0].Get<uint8>();
            if (event_id == 0)
            {
                LOG_ERROR("sql.sql", "`game_event` game event entry 0 is reserved and can't be used.");
                continue;
            }
            GameEventData& pGameEvent = mGameEvent[event_id];
            pGameEvent.eventId      = fields[0].Get<uint32>();
            uint64 starttime        = fields[1].Get<uint64>();
            pGameEvent.start        = time_t(starttime);
            uint64 endtime          = fields[2].Get<uint64>();
            if (fields[2].IsNull())
                endtime             = GameTime::GetGameTime().count() + 63072000; // add 2 years to current date
            pGameEvent.end          = time_t(endtime);
            pGameEvent.occurence    = fields[3].Get<uint64>();
            pGameEvent.length       = fields[4].Get<uint64>();
            pGameEvent.holiday_id   = HolidayIds(fields[5].Get<uint32>());
            pGameEvent.holidayStage = fields[6].Get<uint8>();
            pGameEvent.description  = fields[7].Get<std::string>();
            pGameEvent.state        = (GameEventState)(fields[8].Get<uint8>());
            pGameEvent.announce     = fields[9].Get<uint8>();
            pGameEvent.nextstart    = 0;
            ++count;
            if (pGameEvent.length == 0 && pGameEvent.state == GAMEEVENT_NORMAL)                            // length>0 is validity check
            {
                LOG_ERROR("sql.sql", "`game_event` game event id ({}) isn't a world event and has length = 0, thus it can't be used.", event_id);
                continue;
            }
            if (pGameEvent.holiday_id != HOLIDAY_NONE)
            {
                if (!sHolidaysStore.LookupEntry(pGameEvent.holiday_id))
                {
                    LOG_ERROR("sql.sql", "`game_event` game event id ({}) have not existed holiday id {}.", event_id, pGameEvent.holiday_id);
                    pGameEvent.holiday_id = HOLIDAY_NONE;
                }
                SetHolidayEventTime(pGameEvent);
            }
        } while (result->NextRow());
        LOG_INFO("server.loading", ">> Loaded {} Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
        LOG_INFO("server.loading", " ");
    }
    LOG_INFO("server.loading", "Loading Game Event Saves Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                       0       1        2
        QueryResult result = CharacterDatabase.Query("SELECT eventEntry, state, next_start FROM game_event_save");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 Game Event Saves In Game Events. DB Table `game_event_save` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                uint8 event_id = fields[0].Get<uint8>();
                if (event_id >= mGameEvent.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_save` game event entry ({}) is out of range compared to max event entry in `game_event`", event_id);
                    continue;
                }
                if (mGameEvent[event_id].state != GAMEEVENT_NORMAL && mGameEvent[event_id].state != GAMEEVENT_INTERNAL)
                {
                    mGameEvent[event_id].state = (GameEventState)(fields[1].Get<uint8>());
                    mGameEvent[event_id].nextstart    = time_t(fields[2].Get<uint32>());
                }
                else
                {
                    LOG_ERROR("sql.sql", "game_event_save includes event save for non-worldevent id {}", event_id);
                    continue;
                }
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Game Event Saves In Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event Prerequisite Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                   0             1
        QueryResult result = WorldDatabase.Query("SELECT eventEntry, prerequisite_event FROM game_event_prerequisite");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 Game Rvent Prerequisites in Game Events. DB Table `game_event_prerequisite` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                uint16 event_id = fields[0].Get<uint8>();
                if (event_id >= mGameEvent.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_prerequisite` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                if (mGameEvent[event_id].state != GAMEEVENT_NORMAL && mGameEvent[event_id].state != GAMEEVENT_INTERNAL)
                {
                    uint16 prerequisite_event = fields[1].Get<uint32>();
                    if (prerequisite_event >= mGameEvent.size())
                    {
                        LOG_ERROR("sql.sql", "`game_event_prerequisite` game event prerequisite id ({}) is out of range compared to max event id in `game_event`", prerequisite_event);
                        continue;
                    }
                    mGameEvent[event_id].prerequisite_events.insert(prerequisite_event);
                }
                else
                {
                    LOG_ERROR("sql.sql", "game_event_prerequisiste includes event entry for non-worldevent id {}", event_id);
                    continue;
                }
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} game event prerequisites in Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event Creature Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                 0        1
        QueryResult result = WorldDatabase.Query("SELECT guid, eventEntry FROM game_event_creature");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 creatures in game events. DB table `game_event_creature` is empty");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                ObjectGuid::LowType guid = fields[0].Get<uint32>();
                int16 event_id = fields[1].Get<int8>();
                CreatureData const* data = sObjectMgr->GetCreatureData(guid);
                if (!data)
                {
                    LOG_ERROR("sql.sql", "`game_event_creature` contains creature (GUID: {}) not found in `creature` table.", guid);
                    continue;
                }
                int32 internal_event_id = mGameEvent.size() + event_id - 1;
                if (internal_event_id < 0 || internal_event_id >= int32(mGameEventCreatureGuids.size()))
                {
                    LOG_ERROR("sql.sql", "`game_event_creature` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                GuidLowList& crelist = mGameEventCreatureGuids[internal_event_id];
                crelist.push_back(guid);
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Creatures In Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event GO Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                0         1
        QueryResult result = WorldDatabase.Query("SELECT guid, eventEntry FROM game_event_gameobject");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 gameobjects in game events. DB table `game_event_gameobject` is empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                ObjectGuid::LowType guid = fields[0].Get<uint32>();
                int16 event_id = fields[1].Get<int8>();
                int32 internal_event_id = mGameEvent.size() + event_id - 1;
                GameObjectData const* data = sObjectMgr->GetGameObjectData(guid);
                if (!data)
                {
                    LOG_ERROR("sql.sql", "`game_event_gameobject` contains gameobject (GUID: {}) not found in `gameobject` table.", guid);
                    continue;
                }
                if (internal_event_id < 0 || internal_event_id >= int32(mGameEventGameobjectGuids.size()))
                {
                    LOG_ERROR("sql.sql", "`game_event_gameobject` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                GuidLowList& golist = mGameEventGameobjectGuids[internal_event_id];
                golist.push_back(guid);
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Gameobjects In Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event Model/Equipment Change Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                     0              1             2            3                         4                               5                                 6
        QueryResult result = WorldDatabase.Query("SELECT creature.guid, creature.id1, creature.id2, creature.id3, game_event_model_equip.eventEntry, game_event_model_equip.modelid, game_event_model_equip.equipment_id "
                             "FROM creature JOIN game_event_model_equip ON creature.guid=game_event_model_equip.guid");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 Model/Equipment Changes In Game Events. DB Table `game_event_model_equip` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                ObjectGuid::LowType guid = fields[0].Get<uint32>();
                uint32 entry = fields[1].Get<uint32>();
                uint32 entry2 = fields[2].Get<uint32>();
                uint32 entry3 = fields[3].Get<uint32>();
                uint16 event_id = fields[4].Get<uint8>();
                if (event_id >= mGameEventModelEquip.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_model_equip` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                ModelEquipList& equiplist = mGameEventModelEquip[event_id];
                ModelEquip newModelEquipSet;
                newModelEquipSet.modelid = fields[5].Get<uint32>();
                newModelEquipSet.equipment_id = fields[6].Get<uint8>();
                newModelEquipSet.equipement_id_prev = 0;
                newModelEquipSet.modelid_prev = 0;
                if (newModelEquipSet.equipment_id > 0)
                {
                    int8 equipId = static_cast<int8>(newModelEquipSet.equipment_id);
                    if ((!sObjectMgr->GetEquipmentInfo(entry, equipId)) || (entry2 && !sObjectMgr->GetEquipmentInfo(entry2, equipId)) || (entry3 && !sObjectMgr->GetEquipmentInfo(entry3, equipId)))
                    {
                        LOG_ERROR("sql.sql", "Table `game_event_model_equip` have creature (Guid: {}) with equipment_id {} not found in table `creature_equip_template`, set to no equipment.",
                                         guid, newModelEquipSet.equipment_id);
                        continue;
                    }
                }
                equiplist.push_back(std::pair<ObjectGuid::LowType, ModelEquip>(guid, newModelEquipSet));
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Model/Equipment Changes In Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event Quest Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                               0     1      2
        QueryResult result = WorldDatabase.Query("SELECT id, quest, eventEntry FROM game_event_creature_quest");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 Quests Additions In Game Events. DB Table `game_event_creature_quest` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                uint32 id       = fields[0].Get<uint32>();
                uint32 quest    = fields[1].Get<uint32>();
                uint16 event_id = fields[2].Get<uint8>();
                if (event_id >= mGameEventCreatureQuests.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_creature_quest` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                QuestRelList& questlist = mGameEventCreatureQuests[event_id];
                questlist.push_back(QuestRelation(id, quest));
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Quests Additions In Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event GO Quest Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                               0     1      2
        QueryResult result = WorldDatabase.Query("SELECT id, quest, eventEntry FROM game_event_gameobject_quest");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 go Quests Additions In Game Events. DB Table `game_event_gameobject_quest` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                uint32 id       = fields[0].Get<uint32>();
                uint32 quest    = fields[1].Get<uint32>();
                uint16 event_id = fields[2].Get<uint8>();
                if (event_id >= mGameEventGameObjectQuests.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_gameobject_quest` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                QuestRelList& questlist = mGameEventGameObjectQuests[event_id];
                questlist.push_back(QuestRelation(id, quest));
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Quests Additions In Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event Quest Condition Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                 0       1         2             3
        QueryResult result = WorldDatabase.Query("SELECT quest, eventEntry, condition_id, num FROM game_event_quest_condition");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 quest event Conditions In Game Events. DB Table `game_event_quest_condition` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                uint32 quest     = fields[0].Get<uint32>();
                uint16 event_id  = fields[1].Get<uint8>();
                uint32 condition = fields[2].Get<uint32>();
                float num       = fields[3].Get<float>();
                if (event_id >= mGameEvent.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_quest_condition` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                mQuestToEventConditions[quest].event_id = event_id;
                mQuestToEventConditions[quest].condition = condition;
                mQuestToEventConditions[quest].num = num;
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} quest event conditions in Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event Condition Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                  0          1            2             3                      4
        QueryResult result = WorldDatabase.Query("SELECT eventEntry, condition_id, req_num, max_world_state_field, done_world_state_field FROM game_event_condition");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 Conditions In Game Events. DB table `game_event_condition` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                uint16 event_id  = fields[0].Get<uint8>();
                uint32 condition = fields[1].Get<uint32>();
                if (event_id >= mGameEvent.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_condition` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                mGameEvent[event_id].conditions[condition].reqNum = fields[2].Get<float>();
                mGameEvent[event_id].conditions[condition].done = 0;
                mGameEvent[event_id].conditions[condition].max_world_state = fields[3].Get<uint16>();
                mGameEvent[event_id].conditions[condition].done_world_state = fields[4].Get<uint16>();
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} conditions in Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event Condition Save Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                      0           1         2
        QueryResult result = CharacterDatabase.Query("SELECT eventEntry, condition_id, done FROM game_event_condition_save");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 Condition Saves In Game Events. DB Table `game_event_condition_save` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                uint16 event_id  = fields[0].Get<uint8>();
                uint32 condition = fields[1].Get<uint32>();
                if (event_id >= mGameEvent.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_condition_save` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                GameEventConditionMap::iterator itr = mGameEvent[event_id].conditions.find(condition);
                if (itr != mGameEvent[event_id].conditions.end())
                {
                    itr->second.done = fields[2].Get<float>();
                }
                else
                {
                    LOG_ERROR("sql.sql", "game_event_condition_save contains not present condition evt id {} cond id {}", event_id, condition);
                    continue;
                }
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Condition Saves In Game Events In {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event NPCflag Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                0       1        2
        QueryResult result = WorldDatabase.Query("SELECT guid, eventEntry, npcflag FROM game_event_npcflag");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 Npcflags In Game Events. DB Table `game_event_npcflag` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                ObjectGuid::LowType guid = fields[0].Get<uint32>();
                uint16 event_id = fields[1].Get<uint8>();
                uint32 npcflag = fields[2].Get<uint32>();
                if (event_id >= mGameEvent.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_npcflag` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                mGameEventNPCFlags[event_id].push_back(GuidNPCFlagPair(guid, npcflag));
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Npcflags In Game Events In {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event Seasonal Quest Relations...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                  0          1
        QueryResult result = WorldDatabase.Query("SELECT questId, eventEntry FROM game_event_seasonal_questrelation");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 Seasonal Quests Additions In Game Events. DB Table `game_event_seasonal_questrelation` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                uint32 questId  = fields[0].Get<uint32>();
                uint32 eventEntry = fields[1].Get<uint32>();
                Quest* questTemplate = const_cast<Quest*>(sObjectMgr->GetQuestTemplate(questId));
                if (!questTemplate)
                {
                    LOG_ERROR("sql.sql", "`game_event_seasonal_questrelation` quest id ({}) does not exist in `quest_template`", questId);
                    continue;
                }
                if (eventEntry >= mGameEvent.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_seasonal_questrelation` event id ({}) is out of range compared to max event in `game_event`", eventEntry);
                    continue;
                }
                questTemplate->SetEventIdForQuest((uint16)eventEntry);
                _gameEventSeasonalQuestsMap[eventEntry].push_back(questId);
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Quests Additions In Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event Vendor Additions Data...");
    LoadEventVendors();
    LOG_INFO("server.loading", "Loading Game Event Battleground Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                   0         1
        QueryResult result = WorldDatabase.Query("SELECT eventEntry, bgflag FROM game_event_battleground_holiday");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 Battleground Holidays In Game Events. DB table `game_event_battleground_holiday` is empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                uint16 event_id = fields[0].Get<uint8>();
                if (event_id >= mGameEvent.size())
                {
                    LOG_ERROR("sql.sql", "`game_event_battleground_holiday` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                mGameEventBattlegroundHolidays[event_id] = fields[1].Get<uint32>();
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Battleground Holidays In Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
    LOG_INFO("server.loading", "Loading Game Event Pool Data...");
    {
        uint32 oldMSTime = getMSTime();
        //                                                               0                         1
        QueryResult result = WorldDatabase.Query("SELECT pool_template.entry, game_event_pool.eventEntry FROM pool_template"
                             " JOIN game_event_pool ON pool_template.entry = game_event_pool.pool_entry");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 Pools For Game Events. DB Table `game_event_pool` Is Empty.");
            LOG_INFO("server.loading", " ");
        }
        else
        {
            uint32 count = 0;
            do
            {
                Field* fields = result->Fetch();
                uint32 entry   = fields[0].Get<uint32>();
                int16 event_id = fields[1].Get<int8>();
                int32 internal_event_id = mGameEvent.size() + event_id - 1;
                if (internal_event_id < 0 || internal_event_id >= int32(mGameEventPoolIds.size()))
                {
                    LOG_ERROR("sql.sql", "`game_event_pool` game event id ({}) is out of range compared to max event id in `game_event`", event_id);
                    continue;
                }
                if (!sPoolMgr->CheckPool(entry))
                {
                    LOG_ERROR("sql.sql", "Pool Id ({}) has all creatures or gameobjects with explicit chance sum <>100 and no equal chance defined. The pool system cannot pick one to spawn.", entry);
                    continue;
                }
                IdList& poollist = mGameEventPoolIds[internal_event_id];
                poollist.push_back(entry);
                ++count;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} Pools For Game Events in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
}
References _gameEventSeasonalQuestsMap, GameEventData::announce, CharacterDatabase, GameEventData::description, GameEventData::end, ModelEquip::equipement_id_prev, ModelEquip::equipment_id, GameEventData::eventId, GAMEEVENT_INTERNAL, GAMEEVENT_NORMAL, Field::Get(), GameTime::GetGameTime(), getMSTime(), GetMSTimeDiffToNow(), GameEventData::holiday_id, HOLIDAY_NONE, GameEventData::holidayStage, GameEventData::length, LoadEventVendors(), LOG_ERROR, LOG_INFO, LOG_WARN, mGameEvent, mGameEventBattlegroundHolidays, mGameEventCreatureGuids, mGameEventCreatureQuests, mGameEventGameobjectGuids, mGameEventGameObjectQuests, mGameEventModelEquip, mGameEventNPCFlags, mGameEventPoolIds, ModelEquip::modelid, ModelEquip::modelid_prev, mQuestToEventConditions, GameEventData::nextstart, GameEventData::occurence, SetHolidayEventTime(), sHolidaysStore, sObjectMgr, sPoolMgr, GameEventData::start, GameEventData::state, and WorldDatabase.
LoadHolidayDates()
void GameEventMgr::LoadHolidayDates ()
{
    uint32 oldMSTime = getMSTime();
    //                                               0   1        2           3
    QueryResult result = WorldDatabase.Query("SELECT id, date_id, date_value, holiday_duration FROM holiday_dates");
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 holiday dates. DB table `holiday_dates` is empty.");
        return;
    }
    uint32 count = 0;
    do
    {
        Field* fields = result->Fetch();
        uint32 holidayId = fields[0].Get<uint32>();
        HolidaysEntry* entry = const_cast<HolidaysEntry*>(sHolidaysStore.LookupEntry(holidayId));
        if (!entry)
        {
            LOG_ERROR("sql.sql", "holiday_dates entry has invalid holiday id {}.", holidayId);
            continue;
        }
        uint8 dateId = fields[1].Get<uint8>();
        if (dateId >= MAX_HOLIDAY_DATES)
        {
            LOG_ERROR("sql.sql", "holiday_dates entry has out of range date_id {}.", dateId);
            continue;
        }
        entry->Date[dateId] = fields[2].Get<uint32>();
        if (uint32 duration = fields[3].Get<uint32>())
            entry->Duration[0] = duration;
        auto itr = std::lower_bound(modifiedHolidays.begin(), modifiedHolidays.end(), entry->Id);
        if (itr == modifiedHolidays.end() || *itr != entry->Id)
        {
            modifiedHolidays.insert(itr, entry->Id);
        }
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} Holiday Dates in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
}
References Field::Get(), getMSTime(), GetMSTimeDiffToNow(), LOG_ERROR, LOG_INFO, LOG_WARN, MAX_HOLIDAY_DATES, modifiedHolidays, sHolidaysStore, and WorldDatabase.
NextCheck()
uint32 GameEventMgr::NextCheck (uint16 entry) const
{
    time_t currenttime = GameTime::GetGameTime().count();
    // for NEXTPHASE state world events, return the delay to start the next event, so the followup event will be checked correctly
    if ((mGameEvent[entry].state == GAMEEVENT_WORLD_NEXTPHASE || mGameEvent[entry].state == GAMEEVENT_WORLD_FINISHED) && mGameEvent[entry].nextstart >= currenttime)
        return uint32(mGameEvent[entry].nextstart - currenttime);
    // for CONDITIONS state world events, return the length of the wait period, so if the conditions are met, this check will be called again to set the timer as NEXTPHASE event
    if (mGameEvent[entry].state == GAMEEVENT_WORLD_CONDITIONS)
    {
        if (mGameEvent[entry].length)
            return mGameEvent[entry].length * 60;
        else
            return max_ge_check_delay;
    }
    // outdated event: we return max
    if (currenttime > mGameEvent[entry].end)
        return max_ge_check_delay;
    // never started event, we return delay before start
    if (mGameEvent[entry].start > currenttime)
        return uint32(mGameEvent[entry].start - currenttime);
    uint32 delay;
    // in event, we return the end of it
    if ((((currenttime - mGameEvent[entry].start) % (mGameEvent[entry].occurence * 60)) < (mGameEvent[entry].length * 60)))
        // we return the delay before it ends
        delay = (mGameEvent[entry].length * MINUTE) - ((currenttime - mGameEvent[entry].start) % (mGameEvent[entry].occurence * MINUTE));
    else                                                    // not in window, we return the delay before next start
        delay = (mGameEvent[entry].occurence * MINUTE) - ((currenttime - mGameEvent[entry].start) % (mGameEvent[entry].occurence * MINUTE));
    // In case the end is before next check
    if (mGameEvent[entry].end  < time_t(currenttime + delay))
        return uint32(mGameEvent[entry].end - currenttime);
    else
        return delay;
}
References GAMEEVENT_WORLD_CONDITIONS, GAMEEVENT_WORLD_FINISHED, GAMEEVENT_WORLD_NEXTPHASE, GameTime::GetGameTime(), max_ge_check_delay, mGameEvent, and MINUTE.
Referenced by Update().
RemoveActiveEvent()
void GameEventMgr::RemoveActiveEvent (uint16 event_id) inline private
{ m_ActiveEvents.erase(event_id); }
References m_ActiveEvents.
Referenced by StopEvent().
RunSmartAIScripts()
void GameEventMgr::RunSmartAIScripts (uint16 event_id, bool activate) private
Iterate over every supported source type (creature and gameobject) Not entirely sure how this will affect units in non-loaded grids.
{
    sMapMgr->DoForAllMaps([event_id, activate](Map* map)
    {
        GameEventAIHookWorker worker(event_id, activate);
        TypeContainerVisitor<GameEventAIHookWorker, MapStoredObjectTypesContainer> visitor(worker);
        visitor.Visit(map->GetObjectsStore());
    });
}
References Map::GetObjectsStore(), sMapMgr, and TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::Visit().
Referenced by ApplyNewEvent(), and UnApplyEvent().
SaveWorldEventStateToDB()
void GameEventMgr::SaveWorldEventStateToDB (uint16 event_id) private
{
    CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GAME_EVENT_SAVE);
    stmt->SetData(0, uint8(event_id));
    trans->Append(stmt);
    stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GAME_EVENT_SAVE);
    stmt->SetData(0, uint8(event_id));
    stmt->SetData(1, mGameEvent[event_id].state);
    stmt->SetData(2, mGameEvent[event_id].nextstart ? uint32(mGameEvent[event_id].nextstart) : 0);
    trans->Append(stmt);
    CharacterDatabase.CommitTransaction(trans);
}
References CHAR_DEL_GAME_EVENT_SAVE, CHAR_INS_GAME_EVENT_SAVE, CharacterDatabase, mGameEvent, and PreparedStatementBase::SetData().
Referenced by HandleQuestComplete(), StartEvent(), and Update().
SendWorldStateUpdate()
void GameEventMgr::SendWorldStateUpdate (Player * player, uint16 event_id) private
{
    GameEventConditionMap::const_iterator itr;
    for (itr = mGameEvent[event_id].conditions.begin(); itr != mGameEvent[event_id].conditions.end(); ++itr)
    {
        if (itr->second.done_world_state)
            player->SendUpdateWorldState(itr->second.done_world_state, (uint32)(itr->second.done));
        if (itr->second.max_world_state)
            player->SendUpdateWorldState(itr->second.max_world_state, (uint32)(itr->second.reqNum));
    }
}
References mGameEvent, and Player::SendUpdateWorldState().
SetHolidayEventTime()
void GameEventMgr::SetHolidayEventTime (GameEventData & event) private
{
    if (!event.holidayStage) // Ignore holiday
        return;
    const HolidaysEntry* holiday = sHolidaysStore.LookupEntry(event.holiday_id);
    if (!holiday->Date[0] || !holiday->Duration[0]) // Invalid definitions
    {
        LOG_ERROR("sql.sql", "Missing date or duration for holiday {}.", event.holiday_id);
        return;
    }
    uint8 stageIndex = event.holidayStage - 1;
    event.length = holiday->Duration[stageIndex] * HOUR / MINUTE;
    time_t stageOffset = 0;
    for (uint8 i = 0; i < stageIndex; ++i)
    {
        stageOffset += holiday->Duration[i] * HOUR;
    }
    switch (holiday->CalendarFilterType)
    {
        case -1: // Yearly
            event.occurence = YEAR / MINUTE; // Not all too useful
            break;
        case 0: // Weekly
            event.occurence = WEEK / MINUTE;
            break;
        case 1: // Defined dates only (Darkmoon Faire)
            break;
        case 2: // Only used for looping events (Call to Arms)
            break;
    }
    if (holiday->Looping)
    {
        event.occurence = 0;
        for (uint8 i = 0; i < MAX_HOLIDAY_DURATIONS && holiday->Duration[i]; ++i)
        {
            event.occurence += holiday->Duration[i] * HOUR / MINUTE;
        }
    }
    bool singleDate = ((holiday->Date[0] >> 24) & 0x1F) == 31; // Events with fixed date within year have - 1
    time_t curTime = GameTime::GetGameTime().count();
    for (uint8 i = 0; i < MAX_HOLIDAY_DATES && holiday->Date[i]; ++i)
    {
        uint32 date = holiday->Date[i];
        tm timeInfo;
        if (singleDate)
        {
            timeInfo = Acore::Time::TimeBreakdown(curTime);
            timeInfo.tm_year -= 1; // First try last year (event active through New Year)
        }
        else
        {
            timeInfo.tm_year = ((date >> 24) & 0x1F) + 100;
        }
        timeInfo.tm_mon = (date >> 20) & 0xF;
        timeInfo.tm_mday = ((date >> 14) & 0x3F) + 1;
        timeInfo.tm_hour = (date >> 6) & 0x1F;
        timeInfo.tm_min = date & 0x3F;
        timeInfo.tm_sec = 0;
        timeInfo.tm_isdst = -1;
        // try to get next start time (skip past dates)
        time_t startTime = mktime(&timeInfo);
        if (curTime < startTime + event.length * MINUTE)
        {
            event.start = startTime + stageOffset;
            break;
        }
        else if (singleDate)
        {
            tm tmCopy = Acore::Time::TimeBreakdown(curTime);
            int year = tmCopy.tm_year; // This year
            tmCopy = timeInfo;
            tmCopy.tm_year = year;
            event.start = mktime(&tmCopy) + stageOffset;
            break;
        }
        else
        {
            // date is due and not a singleDate event, try with next DBC date (modified by holiday_dates)
            // if none is found we don't modify start date and use the one in game_event
        }
    }
}
References HolidaysEntry::CalendarFilterType, HolidaysEntry::Date, HolidaysEntry::Duration, GameTime::GetGameTime(), GameEventData::holiday_id, GameEventData::holidayStage, HOUR, GameEventData::length, LOG_ERROR, HolidaysEntry::Looping, MAX_HOLIDAY_DATES, MAX_HOLIDAY_DURATIONS, MINUTE, sHolidaysStore, Acore::Time::TimeBreakdown(), WEEK, and YEAR.
Referenced by LoadFromDB().
StartArenaSeason()
void GameEventMgr::StartArenaSeason ()
{
    uint8 season = sWorld->getIntConfig(CONFIG_ARENA_SEASON_ID);
    QueryResult result = WorldDatabase.Query("SELECT eventEntry FROM game_event_arena_seasons WHERE season = '{}'", season);
    if (!result)
    {
        LOG_ERROR("gameevent", "ArenaSeason ({}) must be an existant Arena Season", season);
        return;
    }
    Field* fields = result->Fetch();
    uint16 eventId = fields[0].Get<uint8>();
    if (eventId >= mGameEvent.size())
    {
        LOG_ERROR("gameevent", "EventEntry {} for ArenaSeason ({}) does not exists", eventId, season);
        return;
    }
    StartEvent(eventId, true);
    LOG_INFO("server.loading", "Arena Season {} started...", season);
    LOG_INFO("server.loading", " ");
}
References CONFIG_ARENA_SEASON_ID, Field::Get(), LOG_ERROR, LOG_INFO, mGameEvent, StartEvent(), sWorld, and WorldDatabase.
StartEvent()
bool GameEventMgr::StartEvent (uint16 event_id, bool overwrite = false)
{
    if (DisableMgr::IsDisabledFor(DISABLE_TYPE_GAME_EVENT, event_id, nullptr) && !overwrite)
    {
        return false;
    }
    GameEventData& data = mGameEvent[event_id];
    if (data.state == GAMEEVENT_NORMAL || data.state == GAMEEVENT_INTERNAL)
    {
        AddActiveEvent(event_id);
        ApplyNewEvent(event_id);
        if (overwrite)
        {
            mGameEvent[event_id].start = GameTime::GetGameTime().count();
            if (data.end <= data.start)
                data.end = data.start + data.length;
        }
        if (IsActiveEvent(event_id))
            sScriptMgr->OnGameEventStart(event_id);
        // When event is started, set its worldstate to current time
        auto itr = _gameEventSeasonalQuestsMap.find(event_id);
        if (itr != _gameEventSeasonalQuestsMap.end() && !itr->second.empty())
        {
            sWorld->setWorldState(event_id, GameTime::GetGameTime().count());
        }
        return false;
    }
    else
    {
        if (data.state == GAMEEVENT_WORLD_INACTIVE)
            // set to conditions phase
            data.state = GAMEEVENT_WORLD_CONDITIONS;
        // add to active events
        AddActiveEvent(event_id);
        // add spawns
        ApplyNewEvent(event_id);
        // check if can go to next state
        bool conditions_met = CheckOneGameEventConditions(event_id);
        // save to db
        SaveWorldEventStateToDB(event_id);
        // force game event update to set the update timer if conditions were met from a command
        // this update is needed to possibly start events dependent on the started one
        // or to scedule another update where the next event will be started
        if (overwrite && conditions_met)
            sWorld->ForceGameEventUpdate();
        if (IsActiveEvent(event_id))
            sScriptMgr->OnGameEventStart(event_id);
        return conditions_met;
    }
}
References _gameEventSeasonalQuestsMap, AddActiveEvent(), ApplyNewEvent(), CheckOneGameEventConditions(), DISABLE_TYPE_GAME_EVENT, GameEventData::end, GAMEEVENT_INTERNAL, GAMEEVENT_NORMAL, GAMEEVENT_WORLD_CONDITIONS, GAMEEVENT_WORLD_INACTIVE, GameTime::GetGameTime(), IsActiveEvent(), DisableMgr::IsDisabledFor(), GameEventData::length, mGameEvent, SaveWorldEventStateToDB(), sScriptMgr, GameEventData::start, GameEventData::state, and sWorld.
Referenced by StartArenaSeason(), StartInternalEvent(), and Update().
StartInternalEvent()
void GameEventMgr::StartInternalEvent (uint16 event_id)
{
    if (event_id < 1 || event_id >= mGameEvent.size())
        return;
    if (!mGameEvent[event_id].isValid())
        return;
    if (m_ActiveEvents.find(event_id) != m_ActiveEvents.end())
        return;
    StartEvent(event_id);
}
References m_ActiveEvents, mGameEvent, and StartEvent().
StartSystem()
uint32 GameEventMgr::StartSystem ()
{
    m_ActiveEvents.clear();
    uint32 delay = Update();
    isSystemInit = true;
    return delay;
}
References isSystemInit, m_ActiveEvents, and Update().
StopEvent()
void GameEventMgr::StopEvent (uint16 event_id, bool overwrite = false)
{
    GameEventData& data = mGameEvent[event_id];
    bool serverwide_evt = data.state != GAMEEVENT_NORMAL && data.state != GAMEEVENT_INTERNAL;
    RemoveActiveEvent(event_id);
    UnApplyEvent(event_id);
     // When event is stopped, clean up its worldstate
    sWorld->setWorldState(event_id, 0);
    if (overwrite && !serverwide_evt)
    {
        data.start = GameTime::GetGameTime().count() - data.length * MINUTE;
        if (data.end <= data.start)
            data.end = data.start + data.length;
    }
    else if (serverwide_evt)
    {
        // if finished world event, then only gm command can stop it
        if (overwrite || data.state != GAMEEVENT_WORLD_FINISHED)
        {
            // reset conditions
            data.nextstart = 0;
            data.state = GAMEEVENT_WORLD_INACTIVE;
            GameEventConditionMap::iterator itr;
            for (itr = data.conditions.begin(); itr != data.conditions.end(); ++itr)
                itr->second.done = 0;
            CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
            CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_ALL_GAME_EVENT_CONDITION_SAVE);
            stmt->SetData(0, uint8(event_id));
            trans->Append(stmt);
            stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GAME_EVENT_SAVE);
            stmt->SetData(0, uint8(event_id));
            trans->Append(stmt);
            CharacterDatabase.CommitTransaction(trans);
        }
    }
    if (!IsActiveEvent(event_id))
        sScriptMgr->OnGameEventStop(event_id);
}
References CHAR_DEL_ALL_GAME_EVENT_CONDITION_SAVE, CHAR_DEL_GAME_EVENT_SAVE, CharacterDatabase, GameEventData::conditions, GameEventData::end, GAMEEVENT_INTERNAL, GAMEEVENT_NORMAL, GAMEEVENT_WORLD_FINISHED, GAMEEVENT_WORLD_INACTIVE, GameTime::GetGameTime(), IsActiveEvent(), GameEventData::length, mGameEvent, MINUTE, GameEventData::nextstart, RemoveActiveEvent(), PreparedStatementBase::SetData(), sScriptMgr, GameEventData::start, GameEventData::state, sWorld, and UnApplyEvent().
Referenced by Update().
UnApplyEvent()
void GameEventMgr::UnApplyEvent (uint16 event_id) private
Run SAI scripts with SMART_EVENT_GAME_EVENT_END
{
    LOG_DEBUG("gameevent", "GameEvent {} \"{}\" removed.", event_id, mGameEvent[event_id].description);
    RunSmartAIScripts(event_id, false);
    // un-spawn positive event tagged objects
    GameEventUnspawn(event_id);
    // spawn negative event tagget objects
    int16 event_nid = (-1) * event_id;
    GameEventSpawn(event_nid);
    // restore equipment or model
    ChangeEquipOrModel(event_id, false);
    // Remove quests that are events only to non event npc
    UpdateEventQuests(event_id, false);
    UpdateWorldStates(event_id, false);
    // update npcflags in this event
    UpdateEventNPCFlags(event_id);
    // remove vendor items
    UpdateEventNPCVendor(event_id, false);
    // update bg holiday
    UpdateBattlegroundSettings();
}
References ChangeEquipOrModel(), GameEventSpawn(), GameEventUnspawn(), LOG_DEBUG, mGameEvent, RunSmartAIScripts(), UpdateBattlegroundSettings(), UpdateEventNPCFlags(), UpdateEventNPCVendor(), UpdateEventQuests(), and UpdateWorldStates().
Referenced by StopEvent().
Update()
uint32 GameEventMgr::Update ()
{
    time_t currenttime = GameTime::GetGameTime().count();
    uint32 nextEventDelay = max_ge_check_delay;             // 1 day
    uint32 calcDelay;
    std::set<uint16> activate, deactivate;
    for (uint16 itr = 1; itr < mGameEvent.size(); ++itr)
    {
        // must do the activating first, and after that the deactivating
        // so first queue it
        //LOG_ERROR("sql.sql", "Checking event {}", itr);
        sScriptMgr->OnGameEventCheck(itr);
        if (CheckOneGameEvent(itr))
        {
            // if the world event is in NEXTPHASE state, and the time has passed to finish this event, then do so
            if (mGameEvent[itr].state == GAMEEVENT_WORLD_NEXTPHASE && mGameEvent[itr].nextstart <= currenttime)
            {
                // set this event to finished, null the nextstart time
                mGameEvent[itr].state = GAMEEVENT_WORLD_FINISHED;
                mGameEvent[itr].nextstart = 0;
                // save the state of this gameevent
                SaveWorldEventStateToDB(itr);
                // queue for deactivation
                if (IsActiveEvent(itr))
                    deactivate.insert(itr);
                // go to next event, this no longer needs an event update timer
                continue;
            }
            else if (mGameEvent[itr].state == GAMEEVENT_WORLD_CONDITIONS && CheckOneGameEventConditions(itr))
                // changed, save to DB the gameevent state, will be updated in next update cycle
                SaveWorldEventStateToDB(itr);
            // queue for activation
            if (!IsActiveEvent(itr))
                activate.insert(itr);
        }
        else
        {
            // If event is inactive, periodically clean up its worldstate
            sWorld->setWorldState(itr, 0);
            if (IsActiveEvent(itr))
            {
                // Xinef: do not deactivate internal events on whim
                if (mGameEvent[itr].state != GAMEEVENT_INTERNAL)
                    deactivate.insert(itr);
            }
            else
            {
                if (!isSystemInit)
                {
                    int16 event_nid = (-1) * (itr);
                    // spawn all negative ones for this event
                    GameEventSpawn(event_nid);
                }
            }
        }
        calcDelay = NextCheck(itr);
        if (calcDelay < nextEventDelay)
            nextEventDelay = calcDelay;
    }
    // now activate the queue
    // a now activated event can contain a spawn of a to-be-deactivated one
    // following the activate - deactivate order, deactivating the first event later will leave the spawn in (wont disappear then reappear clientside)
    for (std::set<uint16>::iterator itr = activate.begin(); itr != activate.end(); ++itr)
        // start the event
        // returns true the started event completed
        // in that case, initiate next update in 1 second
        if (StartEvent(*itr))
            nextEventDelay = 0;
    for (std::set<uint16>::iterator itr = deactivate.begin(); itr != deactivate.end(); ++itr)
        StopEvent(*itr);
    LOG_DEBUG("gameevent", "Next game event check in {} seconds.", nextEventDelay + 1);
    return (nextEventDelay + 1) * IN_MILLISECONDS;           // Add 1 second to be sure event has started/stopped at next call
}
References CheckOneGameEvent(), CheckOneGameEventConditions(), GAMEEVENT_INTERNAL, GAMEEVENT_WORLD_CONDITIONS, GAMEEVENT_WORLD_FINISHED, GAMEEVENT_WORLD_NEXTPHASE, GameEventSpawn(), GameTime::GetGameTime(), IN_MILLISECONDS, IsActiveEvent(), isSystemInit, LOG_DEBUG, max_ge_check_delay, mGameEvent, NextCheck(), SaveWorldEventStateToDB(), sScriptMgr, StartEvent(), StopEvent(), and sWorld.
Referenced by StartSystem().
UpdateBattlegroundSettings()
void GameEventMgr::UpdateBattlegroundSettings () private
{
    uint32 mask = 0;
    for (ActiveEvents::const_iterator itr = m_ActiveEvents.begin(); itr != m_ActiveEvents.end(); ++itr)
        mask |= mGameEventBattlegroundHolidays[*itr];
    sBattlegroundMgr->SetHolidayWeekends(mask);
}
References m_ActiveEvents, mGameEventBattlegroundHolidays, and sBattlegroundMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
UpdateEventNPCFlags()
void GameEventMgr::UpdateEventNPCFlags (uint16 event_id) private
{
    std::unordered_map<uint32, std::unordered_set<ObjectGuid::LowType>> creaturesByMap;
    // go through the creatures whose npcflags are changed in the event
    for (NPCFlagList::iterator itr = mGameEventNPCFlags[event_id].begin(); itr != mGameEventNPCFlags[event_id].end(); ++itr)
    {
        // get the creature data from the low guid to get the entry, to be able to find out the whole guid
        if (CreatureData const* data = sObjectMgr->GetCreatureData(itr->first))
            creaturesByMap[data->mapid].insert(itr->first);
    }
    for (auto const& p : creaturesByMap)
    {
        sMapMgr->DoForAllMapsWithMapId(p.first, [this, &p](Map* map)
        {
            for (auto& spawnId : p.second)
            {
                auto creatureBounds = map->GetCreatureBySpawnIdStore().equal_range(spawnId);
                for (auto itr = creatureBounds.first; itr != creatureBounds.second; ++itr)
                {
                    Creature* creature = itr->second;
                    uint32 npcflag = GetNPCFlag(creature);
                    if (CreatureTemplate const* creatureTemplate = creature->GetCreatureTemplate())
                        npcflag |= creatureTemplate->npcflag;
                    creature->ReplaceAllNpcFlags(NPCFlags(npcflag));
                    // reset gossip options, since the flag change might have added / removed some
                    //cr->ResetGossipOptions();
                }
            }
        });
    }
}
References mGameEventNPCFlags, sMapMgr, and sObjectMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
UpdateEventNPCVendor()
void GameEventMgr::UpdateEventNPCVendor (uint16 event_id, bool activate) private
{
    for (NPCVendorList::iterator itr = mGameEventVendors[event_id].begin(); itr != mGameEventVendors[event_id].end(); ++itr)
    {
        if (activate)
            sObjectMgr->AddVendorItem(itr->entry, itr->item, itr->maxcount, itr->incrtime, itr->ExtendedCost, false);
        else
            sObjectMgr->RemoveVendorItem(itr->entry, itr->item, false);
    }
}
References mGameEventVendors, and sObjectMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
UpdateEventQuests()
void GameEventMgr::UpdateEventQuests (uint16 event_id, bool activate) private
{
    QuestRelList::iterator itr;
    for (itr = mGameEventCreatureQuests[event_id].begin(); itr != mGameEventCreatureQuests[event_id].end(); ++itr)
    {
        QuestRelations* CreatureQuestMap = sObjectMgr->GetCreatureQuestRelationMap();
        if (activate)                                           // Add the pair(id, quest) to the multimap
            CreatureQuestMap->insert(QuestRelations::value_type(itr->first, itr->second));
        else
        {
            if (!hasCreatureQuestActiveEventExcept(itr->second, event_id))
            {
                // Remove the pair(id, quest) from the multimap
                QuestRelations::iterator qitr = CreatureQuestMap->find(itr->first);
                if (qitr == CreatureQuestMap->end())
                    continue;
                QuestRelations::iterator lastElement = CreatureQuestMap->upper_bound(itr->first);
                for (; qitr != lastElement; ++qitr)
                {
                    if (qitr->second == itr->second)
                    {
                        CreatureQuestMap->erase(qitr);          // iterator is now no more valid
                        break;                                  // but we can exit loop since the element is found
                    }
                }
            }
        }
    }
    for (itr = mGameEventGameObjectQuests[event_id].begin(); itr != mGameEventGameObjectQuests[event_id].end(); ++itr)
    {
        QuestRelations* GameObjectQuestMap = sObjectMgr->GetGOQuestRelationMap();
        if (activate)                                           // Add the pair(id, quest) to the multimap
            GameObjectQuestMap->insert(QuestRelations::value_type(itr->first, itr->second));
        else
        {
            if (!hasGameObjectQuestActiveEventExcept(itr->second, event_id))
            {
                // Remove the pair(id, quest) from the multimap
                QuestRelations::iterator qitr = GameObjectQuestMap->find(itr->first);
                if (qitr == GameObjectQuestMap->end())
                    continue;
                QuestRelations::iterator lastElement = GameObjectQuestMap->upper_bound(itr->first);
                for (; qitr != lastElement; ++qitr)
                {
                    if (qitr->second == itr->second)
                    {
                        GameObjectQuestMap->erase(qitr);        // iterator is now no more valid
                        break;                                  // but we can exit loop since the element is found
                    }
                }
            }
        }
    }
}
References hasCreatureQuestActiveEventExcept(), hasGameObjectQuestActiveEventExcept(), mGameEventCreatureQuests, mGameEventGameObjectQuests, and sObjectMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
UpdateWorldStates()
void GameEventMgr::UpdateWorldStates (uint16 event_id, bool Activate) private
{
    GameEventData const& event = mGameEvent[event_id];
    if (event.holiday_id != HOLIDAY_NONE)
    {
        BattlegroundTypeId bgTypeId = BattlegroundMgr::WeekendHolidayIdToBGType(event.holiday_id);
        if (bgTypeId != BATTLEGROUND_TYPE_NONE)
        {
            BattlemasterListEntry const* bl = sBattlemasterListStore.LookupEntry(bgTypeId);
            if (bl && bl->HolidayWorldStateId)
            {
                WorldPackets::WorldState::UpdateWorldState worldstate;
                worldstate.VariableID = bl->HolidayWorldStateId;
                worldstate.Value = Activate ? 1 : 0;
                sWorld->SendGlobalMessage(worldstate.Write());
            }
        }
    }
}
References BATTLEGROUND_TYPE_NONE, HOLIDAY_NONE, BattlemasterListEntry::HolidayWorldStateId, mGameEvent, sBattlemasterListStore, sWorld, WorldPackets::WorldState::UpdateWorldState::Value, WorldPackets::WorldState::UpdateWorldState::VariableID, BattlegroundMgr::WeekendHolidayIdToBGType(), and WorldPackets::WorldState::UpdateWorldState::Write().
Referenced by ApplyNewEvent(), and UnApplyEvent().
Member Data Documentation
_gameEventSeasonalQuestsMap
GameEventSeasonalQuestsMap GameEventMgr::_gameEventSeasonalQuestsMap private
Referenced by LoadFromDB(), and StartEvent().
isSystemInit
bool GameEventMgr::isSystemInit private
Referenced by StartSystem(), and Update().
m_ActiveEvents
ActiveEvents GameEventMgr::m_ActiveEvents private
Referenced by AddActiveEvent(), GetActiveEventList(), GetNPCFlag(), hasCreatureActiveEventExcept(), hasCreatureQuestActiveEventExcept(), hasGameObjectActiveEventExcept(), hasGameObjectQuestActiveEventExcept(), IsActiveEvent(), RemoveActiveEvent(), StartInternalEvent(), StartSystem(), and UpdateBattlegroundSettings().
mGameEvent
GameEventDataMap GameEventMgr::mGameEvent private
Referenced by ApplyNewEvent(), CheckOneGameEvent(), CheckOneGameEventConditions(), GameEventSpawn(), GameEventUnspawn(), GetEventMap(), HandleQuestComplete(), hasCreatureActiveEventExcept(), hasGameObjectActiveEventExcept(), Initialize(), LoadFromDB(), NextCheck(), SaveWorldEventStateToDB(), SendWorldStateUpdate(), StartArenaSeason(), StartEvent(), StartInternalEvent(), StopEvent(), UnApplyEvent(), Update(), and UpdateWorldStates().
mGameEventBattlegroundHolidays
GameEventBitmask GameEventMgr::mGameEventBattlegroundHolidays private
Referenced by Initialize(), LoadFromDB(), and UpdateBattlegroundSettings().
mGameEventCreatureGuids
GameEventGuidMap GameEventMgr::mGameEventCreatureGuids
Referenced by GameEventSpawn(), GameEventUnspawn(), hasCreatureActiveEventExcept(), Initialize(), and LoadFromDB().
mGameEventCreatureQuests
GameEventQuestMap GameEventMgr::mGameEventCreatureQuests private
Referenced by hasCreatureQuestActiveEventExcept(), Initialize(), LoadFromDB(), and UpdateEventQuests().
mGameEventGameobjectGuids
GameEventGuidMap GameEventMgr::mGameEventGameobjectGuids
Referenced by GameEventSpawn(), hasGameObjectActiveEventExcept(), Initialize(), and LoadFromDB().
mGameEventGameObjectQuests
GameEventQuestMap GameEventMgr::mGameEventGameObjectQuests private
Referenced by hasGameObjectQuestActiveEventExcept(), Initialize(), LoadFromDB(), and UpdateEventQuests().
mGameEventModelEquip
GameEventModelEquipMap GameEventMgr::mGameEventModelEquip private
Referenced by ChangeEquipOrModel(), Initialize(), and LoadFromDB().
mGameEventNPCFlags
GameEventNPCFlagMap GameEventMgr::mGameEventNPCFlags private
Referenced by GetNPCFlag(), Initialize(), LoadEventVendors(), LoadFromDB(), and UpdateEventNPCFlags().
mGameEventPoolIds
GameEventIdMap GameEventMgr::mGameEventPoolIds private
Referenced by GameEventSpawn(), Initialize(), and LoadFromDB().
mGameEventVendors
GameEventNPCVendorMap GameEventMgr::mGameEventVendors private
Referenced by Initialize(), LoadEventVendors(), and UpdateEventNPCVendor().
modifiedHolidays
std::vector<uint32> GameEventMgr::modifiedHolidays
Referenced by LoadHolidayDates().
mQuestToEventConditions
QuestIdToEventConditionMap GameEventMgr::mQuestToEventConditions private
Referenced by HandleQuestComplete(), and LoadFromDB().