AzerothCore: Appender Class Reference
Appender Class Reference abstract
#include "Appender.h"
Public Member Functions
Appender (uint8 _id, std::string const &name, LogLevel level=LOG_LEVEL_DISABLED, AppenderFlags flags=APPENDER_FLAGS_NONE)
virtual ~Appender ()
uint8 getId () const
std::string const & getName () const
virtual AppenderType getType () const =0
LogLevel getLogLevel () const
AppenderFlags getFlags () const
void setLogLevel (LogLevel)
void write (LogMessage *message)
virtual void setRealmId (uint32)
Static Public Member Functions
static char const * getLogLevelString (LogLevel level)
Private Member Functions
virtual void _write (LogMessage const *)=0
Private Attributes
uint8 id
std::string name
LogLevel level
AppenderFlags flags
Detailed Description
Constructor & Destructor Documentation
Appender()
Appender::Appender (uint8 _id, std::string const & name, LogLevel level = LOG_LEVEL_DISABLED, AppenderFlags flags = APPENDER_FLAGS_NONE)
                                                                                              :
    id(_id), name(_name), level(_level), flags(_flags) { }
~Appender()
Appender::~Appender () virtual
{ }
Member Function Documentation
_write()
virtual void Appender::_write (LogMessage const *) private pure virtual
Implemented in AppenderConsole, AppenderFile, and AppenderDB.
Referenced by write().
getFlags()
AppenderFlags Appender::getFlags () const
{
    return flags;
}
References flags.
getId()
uint8 Appender::getId () const
{
    return id;
}
References id.
Referenced by Log::CreateAppenderFromConfig(), and Log::ReadLoggersFromConfig().
getLogLevel()
LogLevel Appender::getLogLevel () const
{
    return level;
}
References level.
getLogLevelString()
char const * Appender::getLogLevelString (LogLevel level) static
{
    switch (level)
    {
        case LOG_LEVEL_FATAL:
            return "FATAL";
        case LOG_LEVEL_ERROR:
            return "ERROR";
        case LOG_LEVEL_WARN:
            return "WARN";
        case LOG_LEVEL_INFO:
            return "INFO";
        case LOG_LEVEL_DEBUG:
            return "DEBUG";
        case LOG_LEVEL_TRACE:
            return "TRACE";
        default:
            return "DISABLED";
    }
}
References level, LOG_LEVEL_DEBUG, LOG_LEVEL_ERROR, LOG_LEVEL_FATAL, LOG_LEVEL_INFO, LOG_LEVEL_TRACE, and LOG_LEVEL_WARN.
Referenced by write().
getName()
std::string const & Appender::getName () const
{
    return name;
}
References name.
getType()
virtual AppenderType Appender::getType () const pure virtual
Implemented in AppenderConsole, AppenderFile, and AppenderDB.
setLogLevel()
void Appender::setLogLevel (LogLevel _level)
{
    level = _level;
}
References level.
Referenced by Log::SetLogLevel().
setRealmId()
virtual void Appender::setRealmId (uint32) inline virtual
Reimplemented in AppenderDB.
{ }
write()
void Appender::write (LogMessage * message)
{
    if (!level || level < message->level)
    {
        return;
    }
    std::ostringstream ss;
    if (flags & APPENDER_FLAGS_PREFIX_TIMESTAMP)
    {
        ss << message->getTimeStr() << ' ';
    }
    if (flags & APPENDER_FLAGS_PREFIX_LOGLEVEL)
    {
        ss << Acore::StringFormat("%-5s ", Appender::getLogLevelString(message->level));
    }
    if (flags & APPENDER_FLAGS_PREFIX_LOGFILTERTYPE)
    {
        ss << '[' << message->type << "] ";
    }
    message->prefix = ss.str();
    _write(message);
}
References _write(), APPENDER_FLAGS_PREFIX_LOGFILTERTYPE, APPENDER_FLAGS_PREFIX_LOGLEVEL, APPENDER_FLAGS_PREFIX_TIMESTAMP, flags, getLogLevelString(), LogMessage::getTimeStr(), level, LogMessage::level, LogMessage::prefix, Acore::StringFormat(), and LogMessage::type.
Member Data Documentation
flags
AppenderFlags Appender::flags private
Referenced by AppenderFile::AppenderFile(), getFlags(), and write().
id
uint8 Appender::id private
Referenced by getId().
level
LogLevel Appender::level private
Referenced by getLogLevel(), getLogLevelString(), setLogLevel(), and write().
name
std::string Appender::name private
Referenced by AppenderConsole::AppenderConsole(), AppenderFile::AppenderFile(), getName(), and AppenderConsole::InitColors().