AzerothCore: boss_shade_of_aran Struct Reference
boss_shade_of_aran Struct Reference
Public Member Functions
boss_shade_of_aran (Creature *creature)
void Reset () override
bool CheckAranInRoom ()
void SetGUID (ObjectGuid guid, int32 id) override
void AttackStart (Unit *who) override
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void DamageTaken (Unit *doneBy, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void OnPowerUpdate (Powers, int32, int32, uint32 currentPower) override
Called when the creature power updates.
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
TaskScheduler _drinkScheduler
uint32 _currentNormalSpell
uint32 _lastSuperSpell
bool _drinking
bool _hasDrunk
bool _atieshReaction
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_shade_of_aran()
boss_shade_of_aran::boss_shade_of_aran (Creature * creature) inline
: BossAI(creature, DATA_ARAN), _atieshReaction(false) { }
Member Function Documentation
AttackStart()
void boss_shade_of_aran::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (who && who->isTargetableForAttack() && me->GetReactState() != REACT_PASSIVE)
        {
            if (me->Attack(who, false))
            {
                me->GetMotionMaster()->MoveChase(who, 45.0f, 0);
                me->AddThreat(who, 0.0f);
            }
        }
    }
References Unit::AddThreat(), Unit::Attack(), Unit::GetMotionMaster(), Creature::GetReactState(), Unit::isTargetableForAttack(), ScriptedAI::me, MotionMaster::MoveChase(), and REACT_PASSIVE.
CheckAranInRoom()
bool boss_shade_of_aran::CheckAranInRoom () inline
    {
        return me->GetDistance2d(roomCenter.GetPositionX(), roomCenter.GetPositionY()) < 45.0f;
    }
References WorldObject::GetDistance2d(), Position::GetPositionX(), Position::GetPositionY(), ScriptedAI::me, and roomCenter.
DamageTaken()
void boss_shade_of_aran::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
    {
        BossAI::DamageTaken(doneBy, damage, damagetype, damageSchoolMask);
        if ((damagetype == DIRECT_DAMAGE || damagetype == SPELL_DIRECT_DAMAGE) && _drinking && me->GetReactState() == REACT_PASSIVE)
        {
            me->RemoveAurasDueToSpell(SPELL_DRINK);
            me->SetStandState(UNIT_STAND_STATE_STAND);
            me->SetReactState(REACT_AGGRESSIVE);
            me->SetPower(POWER_MANA, me->GetMaxPower(POWER_MANA) - 32000);
            _drinkScheduler.CancelGroup(GROUP_DRINKING);
            _drinkScheduler.Schedule(1s, [this](TaskContext)
            {
                DoCastSelf(SPELL_AOE_PYROBLAST, false);
                _drinking = false;
            });
        }
    }
References _drinking, _drinkScheduler, TaskScheduler::CancelGroup(), BossAI::DamageTaken(), DIRECT_DAMAGE, UnitAI::DoCastSelf(), Unit::GetMaxPower(), Creature::GetReactState(), GROUP_DRINKING, ScriptedAI::me, POWER_MANA, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), TaskScheduler::Schedule(), Unit::SetPower(), Creature::SetReactState(), Unit::SetStandState(), SPELL_AOE_PYROBLAST, SPELL_DIRECT_DAMAGE, SPELL_DRINK, and UNIT_STAND_STATE_STAND.
JustDied()
void boss_shade_of_aran::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
    {
        Talk(SAY_DEATH);
        _JustDied();
        if (GameObject* libraryDoor = instance->instance->GetGameObject(instance->GetGuidData(DATA_GO_LIBRARY_DOOR)))
        {
            libraryDoor->SetGoState(GO_STATE_ACTIVE);
            libraryDoor->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
        }
    }
References BossAI::_JustDied(), DATA_GO_LIBRARY_DOOR, Map::GetGameObject(), InstanceScript::GetGuidData(), GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, BossAI::instance, InstanceScript::instance, and SAY_DEATH.
JustEngagedWith()
void boss_shade_of_aran::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        _JustEngagedWith();
        Talk(SAY_AGGRO);
        //handle timed closing door
        scheduler.Schedule(15s, [this](TaskContext)
        {
            if (GameObject* libraryDoor = instance->instance->GetGameObject(instance->GetGuidData(DATA_GO_LIBRARY_DOOR)))
            {
                libraryDoor->SetGoState(GO_STATE_READY);
                libraryDoor->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
            }
        }).Schedule(1s, [this](TaskContext context)
        {
            if (!_drinking)
            {
                if (me->IsNonMeleeSpellCast(false))
                {
                    return;
                }
                std::list<uint32> normalSpells = { SPELL_ARCANE_MISSILE, SPELL_FIREBALL, SPELL_FROSTBOLT };
                normalSpells.remove_if([&](uint32 spell) -> bool { return !me->CanCastSpell(spell); });
                if (!normalSpells.empty())
                {
                    // If we are able to cast spells, cast them.
                    _currentNormalSpell = Acore::Containers::SelectRandomContainerElement(normalSpells);
                    DoCastRandomTarget(_currentNormalSpell, 0, 100.0f);
                    if (me->GetVictim())
                    {
                        me->GetMotionMaster()->MoveChase(me->GetVictim(), 45.0f);
                    }
                }
                else
                {
                    // Otherwise, chase in melee range for auto attacks (and drink mana potion, if needed).
                    me->SetWalk(false);
                    me->ResumeChasingVictim();
                    if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(_currentNormalSpell))
                    {
                        if (int32(me->GetPower(POWER_MANA)) < spellInfo->CalcPowerCost(me, (SpellSchoolMask)spellInfo->SchoolMask))
{
                            DoCastSelf(SPELL_POTION);
                        }
                    }
                }
            }
            context.Repeat(2s);
        }).Schedule(5s, [this](TaskContext context)
        {
            if (!_drinking)
            {
                urand(0, 1) ? DoCastSelf(SPELL_AOE_CS) : DoCastRandomTarget(SPELL_CHAINSOFICE);
            }
            context.Repeat(5s, 20s);
        }).Schedule(6s, [this](TaskContext context)
        {
            if (!_drinking)
            {
                me->ClearProhibitedSpellTimers();
                DoCastSelf(SPELL_BLINK_CENTER, true);
                std::vector<uint32> superSpells = { SPELL_SUMMON_BLIZZARD, SPELL_AEXPLOSION, SPELL_FLAME_WREATH };
                // Workaround for SelectRandomContainerElementIf
                std::vector<uint32> allowedSpells;
                std::copy_if(superSpells.begin(), superSpells.end(), std::back_inserter(allowedSpells), [&](uint32 superSpell) -> bool { return superSpell != _lastSuperSpell; });
                _lastSuperSpell = allowedSpells[urand(0, allowedSpells.size() - 1)];
                //  SelectRandomContainerElementIf produces unexpected output. Reintroduce when issue is resolved:
                //  Sample results:
                //       Selected Super Spell: 3722304989
                //       superSpells elements : 29969 29973 30004
                //  _lastSuperSpell = Acore::Containers::SelectRandomContainerElementIf(superSpells, [&](uint32 superSpell) -> bool { return superSpell != _lastSuperSpell; });
                me->InterruptNonMeleeSpells(true); // Super spell should have prio over normal spells
                switch (_lastSuperSpell)
                {
                    case SPELL_AEXPLOSION:
                        Talk(SAY_EXPLOSION);
                        Talk(EMOTE_ARCANE_EXPLOSION);
                        DoCastSelf(SPELL_PLAYERPULL, true);
                        DoCastSelf(SPELL_MASSSLOW, true);
                        break;
                    case SPELL_FLAME_WREATH:
                        Talk(SAY_FLAMEWREATH);
                        break;
                    case SPELL_SUMMON_BLIZZARD:
                        Talk(SAY_BLIZZARD);
                        break;
                }
                DoCastAOE(_lastSuperSpell);
            }
            context.Repeat(35s, 40s);
        }).Schedule(12min, [this](TaskContext context)
        {
            for (uint32 i = 0; i < 5; ++i)
            {
                if (Creature* unit = me->SummonCreature(NPC_SHADOW_OF_ARAN, 0.0f, 0.0f, 0.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 5000))
                {
                    unit->Attack(me->GetVictim(), true);
                    unit->SetFaction(me->GetFaction());
                }
            }
            Talk(SAY_TIMEOVER);
            context.Repeat(1min);
        });
    }
References _currentNormalSpell, _drinking, BossAI::_JustEngagedWith(), DATA_GO_LIBRARY_DOOR, Map::GetGameObject(), InstanceScript::GetGuidData(), BossAI::instance, InstanceScript::instance, Unit::IsNonMeleeSpellCast(), ScriptedAI::me, Creature::ResumeChasingVictim(), SAY_AGGRO, TaskScheduler::Schedule(), CreatureAI::scheduler, Creature::SetWalk(), and sSpellMgr.
KilledUnit()
void boss_shade_of_aran::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        Talk(SAY_KILL);
    }
References SAY_KILL.
OnPowerUpdate()
void boss_shade_of_aran::OnPowerUpdate (Powers , int32 , int32 , uint32) inline override virtual
Called when the creature power updates.
Reimplemented from UnitAI.
    {
        // Should drink at 10%, need 10% mana for mass polymorph
        if (!_hasDrunk && me->GetMaxPower(POWER_MANA) && (currentPower * 100 / me->GetMaxPower(POWER_MANA)) < 13.5)
        {
            _hasDrunk = true;
            me->SetReactState(REACT_PASSIVE);
            // Start drinking after conjuring drinks
            _drinkScheduler.Schedule(0s, GROUP_DRINKING, [this](TaskContext)
            {
                me->InterruptNonMeleeSpells(true);
                me->RemoveAurasDueToSpell(SPELL_ARCANE_MISSILE);
                Talk(SAY_DRINK);
                DoCastAOE(SPELL_MASS_POLY);
                // If we set drinking earlier it will break when someone attacks aran while casting poly
                _drinking = true;
            }).Schedule(3s, GROUP_DRINKING, [this](TaskContext)
            {
                DoCastSelf(SPELL_CONJURE);
            }).Schedule(6s, GROUP_DRINKING, [this](TaskContext)
            {
                me->SetStandState(UNIT_STAND_STATE_SIT);
                DoCastSelf(SPELL_DRINK);
            }).Schedule(12s, GROUP_DRINKING, [this](TaskContext)
            {
                me->SetStandState(UNIT_STAND_STATE_STAND);
                me->SetReactState(REACT_AGGRESSIVE);
                me->SetPower(POWER_MANA, me->GetMaxPower(POWER_MANA) - 32000);
                DoCastSelf(SPELL_AOE_PYROBLAST);
                _drinkScheduler.CancelGroup(GROUP_DRINKING);
                _drinking = false;
            });
        }
    }
References _drinking, _drinkScheduler, _hasDrunk, TaskScheduler::CancelGroup(), UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), Unit::GetMaxPower(), GROUP_DRINKING, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, POWER_MANA, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), SAY_DRINK, TaskScheduler::Schedule(), Unit::SetPower(), Creature::SetReactState(), Unit::SetStandState(), SPELL_AOE_PYROBLAST, SPELL_ARCANE_MISSILE, SPELL_CONJURE, SPELL_DRINK, SPELL_MASS_POLY, UNIT_STAND_STATE_SIT, and UNIT_STAND_STATE_STAND.
Reset()
void boss_shade_of_aran::Reset () inline override virtual
Reimplemented from BossAI.
    {
        BossAI::Reset();
        // Reset the mana of the boss fully before resetting drinking
        // If this was omitted, the boss would start drinking on reset if the mana was low on a wipe
        me->SetPower(POWER_MANA, me->GetMaxPower(POWER_MANA));
        _drinkScheduler.CancelAll();
        _lastSuperSpell = 0;
        _currentNormalSpell = 0;
        _drinking = false;
        _hasDrunk = false;
        for (auto spell : immuneSpells)
            me->ApplySpellImmune(0, IMMUNITY_ID, spell, true);
        if (GameObject* libraryDoor = instance->instance->GetGameObject(instance->GetGuidData(DATA_GO_LIBRARY_DOOR)))
        {
            libraryDoor->SetGoState(GO_STATE_ACTIVE);
            libraryDoor->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
        }
        ScheduleHealthCheckEvent(40, [&]{
            Talk(SAY_ELEMENTALS);
            std::vector<uint32> elementalSpells = { SPELL_SUMMON_WELEMENTAL_1, SPELL_SUMMON_WELEMENTAL_2, SPELL_SUMMON_WELEMENTAL_3, SPELL_SUMMON_WELEMENTAL_4 };
            for (auto const& spell : elementalSpells)
            {
                DoCastAOE(spell, true);
            }
        });
    }
References _currentNormalSpell, _drinking, _drinkScheduler, _hasDrunk, _lastSuperSpell, Unit::ApplySpellImmune(), TaskScheduler::CancelAll(), DATA_GO_LIBRARY_DOOR, UnitAI::DoCastAOE(), Map::GetGameObject(), InstanceScript::GetGuidData(), Unit::GetMaxPower(), GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, immuneSpells, IMMUNITY_ID, BossAI::instance, InstanceScript::instance, ScriptedAI::me, POWER_MANA, BossAI::Reset(), SAY_ELEMENTALS, BossAI::ScheduleHealthCheckEvent(), Unit::SetPower(), SPELL_SUMMON_WELEMENTAL_1, SPELL_SUMMON_WELEMENTAL_2, SPELL_SUMMON_WELEMENTAL_3, and SPELL_SUMMON_WELEMENTAL_4.
SetGUID()
void boss_shade_of_aran::SetGUID (ObjectGuid guid, int32 id) inline override virtual
Reimplemented from UnitAI.
    {
        if (id == ACTION_ATIESH_REACT && !_atieshReaction)
        {
            Talk(SAY_ATIESH);
            _atieshReaction = true;
            if (Unit* atieshOwner = ObjectAccessor::GetUnit(*me, guid))
            {
                me->PauseMovement(3000);
                me->SetFacingToObject(atieshOwner);
            }
        }
    }
References _atieshReaction, ACTION_ATIESH_REACT, ObjectAccessor::GetUnit(), ScriptedAI::me, Unit::PauseMovement(), SAY_ATIESH, and Unit::SetFacingToObject().
UpdateAI()
void boss_shade_of_aran::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
    {
        scheduler.Update(diff);
        _drinkScheduler.Update(diff);
        if (!UpdateVictim())
            return;
        if (!CheckAranInRoom())
        {
            EnterEvadeMode();
            return;
        }
        if (!_drinking)
            DoMeleeAttackIfReady();
    }
Member Data Documentation
_atieshReaction
bool boss_shade_of_aran::_atieshReaction private
Referenced by SetGUID().
_currentNormalSpell
uint32 boss_shade_of_aran::_currentNormalSpell private
Referenced by JustEngagedWith(), and Reset().
_drinking
bool boss_shade_of_aran::_drinking private
Referenced by DamageTaken(), JustEngagedWith(), OnPowerUpdate(), and Reset().
_drinkScheduler
TaskScheduler boss_shade_of_aran::_drinkScheduler private
Referenced by DamageTaken(), OnPowerUpdate(), and Reset().
_hasDrunk
bool boss_shade_of_aran::_hasDrunk private
Referenced by OnPowerUpdate(), and Reset().
_lastSuperSpell
uint32 boss_shade_of_aran::_lastSuperSpell private
Referenced by Reset().