AzerothCore: boss_kelthuzad::boss_kelthuzadAI Struct Reference
boss_kelthuzad::boss_kelthuzadAI Struct Reference
Public Member Functions
boss_kelthuzadAI (Creature *c)
float NormalizeOrientation (float o)
void SpawnHelpers ()
void SummonHelper (uint32 entry, uint32 count)
void Reset () override
void EnterEvadeMode (EvadeReason why) override
void KilledUnit (Unit *who) override
void JustDied (Unit *killer) override
void MoveInLineOfSight (Unit *who) override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void JustSummoned (Creature *cr) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
SummonList summons
InstanceScript * pInstance
bool _justSpawned
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_kelthuzadAI()
boss_kelthuzad::boss_kelthuzadAI::boss_kelthuzadAI (Creature * c) inline explicit
                                               : BossAI(c, BOSS_KELTHUZAD), summons(me)
        {
            pInstance = me->GetInstanceScript();
            _justSpawned = true;
        }
References _justSpawned, WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
EnterEvadeMode()
void boss_kelthuzad::boss_kelthuzadAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from BossAI.
        {
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_DISABLE_MOVE);
            ScriptedAI::EnterEvadeMode(why);
        }
References CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::RemoveUnitFlag(), UNIT_FLAG_DISABLE_MOVE, and UNIT_FLAG_NON_ATTACKABLE.
JustDied()
void boss_kelthuzad::boss_kelthuzadAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
        {
            BossAI::JustDied(killer);
            summons.DoAction(ACTION_GUARDIANS_OFF);
            if (Creature* guardian = summons.GetCreatureWithEntry(NPC_GUARDIAN_OF_ICECROWN))
            {
                guardian->AI()->Talk(EMOTE_GUARDIAN_FLEE);
            }
            Talk(SAY_DEATH);
            if (pInstance)
            {
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_GATE)))
                {
                    go->SetGoState(GO_STATE_ACTIVE);
                }
            }
        }
References ACTION_GUARDIANS_OFF, DATA_KELTHUZAD_GATE, SummonList::DoAction(), EMOTE_GUARDIAN_FLEE, SummonList::GetCreatureWithEntry(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_ACTIVE, BossAI::JustDied(), ScriptedAI::me, NPC_GUARDIAN_OF_ICECROWN, pInstance, SAY_DEATH, and summons.
JustEngagedWith()
void boss_kelthuzad::boss_kelthuzadAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            BossAI::JustEngagedWith(who);
            Talk(SAY_SUMMON_MINIONS);
            me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_DISABLE_MOVE);
            me->RemoveAllAttackers();
            me->SetTarget();
            me->SetReactState(REACT_PASSIVE);
            me->CastSpell(me, SPELL_KELTHUZAD_CHANNEL, false);
            events.ScheduleEvent(EVENT_SPAWN_POOL, 5s);
            events.ScheduleEvent(EVENT_SUMMON_SOLDIER, 6400ms);
            events.ScheduleEvent(EVENT_SUMMON_UNSTOPPABLE_ABOMINATION, 10s);
            events.ScheduleEvent(EVENT_SUMMON_SOUL_WEAVER, 12s);
            events.ScheduleEvent(EVENT_PHASE_2, 228s);
            events.ScheduleEvent(EVENT_ENRAGE, 15min);
            if (pInstance)
            {
                if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_FLOOR)))
                {
                    events.ScheduleEvent(EVENT_FLOOR_CHANGE, 15s);
                    go->SetGoState(GO_STATE_ACTIVE);
                }
            }
            if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_GATE)))
            {
                go->SetGoState(GO_STATE_READY);
            }
        }
References Unit::CastSpell(), DATA_KELTHUZAD_FLOOR, DATA_KELTHUZAD_GATE, EVENT_ENRAGE, EVENT_FLOOR_CHANGE, EVENT_PHASE_2, EVENT_SPAWN_POOL, EVENT_SUMMON_SOLDIER, EVENT_SUMMON_SOUL_WEAVER, EVENT_SUMMON_UNSTOPPABLE_ABOMINATION, Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_ACTIVE, GO_STATE_READY, BossAI::JustEngagedWith(), ScriptedAI::me, pInstance, REACT_PASSIVE, Unit::RemoveAllAttackers(), SAY_SUMMON_MINIONS, Creature::SetReactState(), Creature::SetTarget(), Unit::SetUnitFlag(), SPELL_KELTHUZAD_CHANNEL, UNIT_FLAG_DISABLE_MOVE, and UNIT_FLAG_NON_ATTACKABLE.
JustSummoned()
void boss_kelthuzad::boss_kelthuzadAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from BossAI.
        {
            summons.Summon(cr);
            if (!cr->IsInCombat())
            {
                cr->GetMotionMaster()->MoveRandom(5);
            }
            if (cr->GetEntry() == NPC_GUARDIAN_OF_ICECROWN)
            {
                cr->SetHomePosition(cr->GetPositionX(), cr->GetPositionY(), cr->GetPositionZ(), cr->GetOrientation());
            }
        }
References Object::GetEntry(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::IsInCombat(), MotionMaster::MoveRandom(), NPC_GUARDIAN_OF_ICECROWN, Creature::SetHomePosition(), SummonList::Summon(), and summons.
KilledUnit()
void boss_kelthuzad::boss_kelthuzadAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!who->IsPlayer())
                return;
            Talk(SAY_SLAY);
            if (pInstance)
            {
                pInstance->SetData(DATA_IMMORTAL_FAIL, 0);
            }
        }
References DATA_IMMORTAL_FAIL, Object::IsPlayer(), pInstance, SAY_SLAY, and ZoneScript::SetData().
MoveInLineOfSight()
void boss_kelthuzad::boss_kelthuzadAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!me->IsInCombat() && who->IsPlayer() && who->IsAlive() && me->GetDistance(who) <= 50.0f)
                AttackStart(who);
        }
References ScriptedAI::AttackStart(), WorldObject::GetDistance(), Unit::IsAlive(), Unit::IsInCombat(), Object::IsPlayer(), and ScriptedAI::me.
NormalizeOrientation()
float boss_kelthuzad::boss_kelthuzadAI::NormalizeOrientation (float o) inline
        {
            return std::fmod(o, 2.0f * static_cast<float>(M_PI)); // Only positive values will be passed
        }
Reset()
void boss_kelthuzad::boss_kelthuzadAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            BossAI::Reset();
            events.Reset();
            summons.DespawnAll();
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_DISABLE_MOVE);
            me->SetReactState(REACT_AGGRESSIVE);
            if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_FLOOR)))
            {
                go->SetPhaseMask(1, true);
                go->SetGoState(GO_STATE_READY);
            }
            if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_GATE)))
            {
                if (!_justSpawned) // Don't open the door if we just spawned and are still doing the conversation
                {
                    go->SetGoState(GO_STATE_ACTIVE);
                }
            }
            _justSpawned = false;
            if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_PORTAL_1)))
            {
                go->SetGoState(GO_STATE_READY);
            }
            if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_PORTAL_2)))
            {
                go->SetGoState(GO_STATE_READY);
            }
            if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_PORTAL_3)))
            {
                go->SetGoState(GO_STATE_READY);
            }
            if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_PORTAL_4)))
            {
                go->SetGoState(GO_STATE_READY);
            }
        }
References _justSpawned, DATA_KELTHUZAD_FLOOR, DATA_KELTHUZAD_GATE, DATA_KELTHUZAD_PORTAL_1, DATA_KELTHUZAD_PORTAL_2, DATA_KELTHUZAD_PORTAL_3, DATA_KELTHUZAD_PORTAL_4, SummonList::DespawnAll(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_ACTIVE, GO_STATE_READY, ScriptedAI::me, pInstance, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), BossAI::Reset(), Creature::SetReactState(), summons, UNIT_FLAG_DISABLE_MOVE, and UNIT_FLAG_NON_ATTACKABLE.
SpawnHelpers()
void boss_kelthuzad::boss_kelthuzadAI::SpawnHelpers () inline
        {
            // spawn at gate
            me->SummonCreature(NPC_UNSTOPPABLE_ABOMINATION, 3656.19f, -5093.78f, 143.33f, 6.08, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000);// abo center
            me->SummonCreature(NPC_UNSTOPPABLE_ABOMINATION, 3657.94f, -5087.68f, 143.60f, 6.08, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000);// abo left
            me->SummonCreature(NPC_UNSTOPPABLE_ABOMINATION, 3655.48f, -5100.05f, 143.53f, 6.08, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000);// abo right
            me->SummonCreature(NPC_SOUL_WEAVER, 3651.73f, -5092.62f, 143.38f, 6.05, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000); // soul behind
            me->SummonCreature(NPC_SOLDIER_OF_THE_FROZEN_WASTES, 3660.17f, -5092.45f, 143.37f, 6.07, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000); // ske front left
            me->SummonCreature(NPC_SOLDIER_OF_THE_FROZEN_WASTES, 3659.39f, -5096.21f, 143.29f, 6.07, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000); // ske front right
            me->SummonCreature(NPC_SOLDIER_OF_THE_FROZEN_WASTES, 3659.29f, -5090.19f, 143.48f, 6.07, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000); // ske left left
            me->SummonCreature(NPC_SOLDIER_OF_THE_FROZEN_WASTES, 3657.43f, -5098.03f, 143.41f, 6.07, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000); // ske right right
            me->SummonCreature(NPC_SOLDIER_OF_THE_FROZEN_WASTES, 3654.36f, -5090.51f, 143.48f, 6.09, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000); // ske behind left
            me->SummonCreature(NPC_SOLDIER_OF_THE_FROZEN_WASTES, 3653.35f, -5095.91f, 143.41f, 6.09, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000); // ske right right
            // 6 rooms, 8 soldiers, 3 abominations and 1 weaver in each room | middle positions in table starts from 6
            for (uint8 i = 6; i < 12; ++i)
            {
                for (uint8 j = 0; j < 8; ++j)
                {
                    float angle = M_PI * 2 / 8 * j;
                    me->SummonCreature(NPC_SOLDIER_OF_THE_FROZEN_WASTES, SummonGroups[i].GetPositionX() + 6 * cos(angle), SummonGroups[i].GetPositionY() + 6 * std::sin(angle), SummonGroups[i].GetPositionZ(), SummonGroups[i].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000);
                }
            }
            for (uint8 i = 6; i < 12; ++i)
            {
                for (uint8 j = 1; j < 4; ++j)
                {
                    float dist = j == 2 ? 0.0f : 8.0f; // second in middle
                    float angle = SummonGroups[i].GetOrientation() + M_PI * 2 / 4 * j;
                    me->SummonCreature(NPC_UNSTOPPABLE_ABOMINATION, SummonGroups[i].GetPositionX() + dist * cos(angle), SummonGroups[i].GetPositionY() + dist * std::sin(angle), SummonGroups[i].GetPositionZ(), SummonGroups[i].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000);
                }
            }
            for (uint8 i = 6; i < 12; ++i)
            {
                for (uint8 j = 0; j < 1; ++j)
                {
                    float angle = SummonGroups[i].GetOrientation() + M_PI;
                    me->SummonCreature(NPC_SOUL_WEAVER, SummonGroups[i].GetPositionX() + 6 * cos(angle), SummonGroups[i].GetPositionY() + 6 * std::sin(angle), SummonGroups[i].GetPositionZ() + 0.5f, SummonGroups[i].GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000);
                }
            }
        }
References Position::GetOrientation(), ScriptedAI::me, NPC_SOLDIER_OF_THE_FROZEN_WASTES, NPC_SOUL_WEAVER, NPC_UNSTOPPABLE_ABOMINATION, WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
Referenced by UpdateAI().
SummonHelper()
void boss_kelthuzad::boss_kelthuzadAI::SummonHelper (uint32 entry, uint32 count) inline
        {
            for (uint8 i = 0; i < count; ++i)
            {
                if (Creature* cr = me->SummonCreature(entry, SpawnPool[urand(0, 6)], TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000))
                {
                    if (Unit* target = SelectTargetFromPlayerList(100.0f))
                    {
                        cr->AI()->DoAction(ACTION_CALL_HELP_OFF);
                        cr->AI()->AttackStart(target);
                    }
                }
            }
        }
References ACTION_CALL_HELP_OFF, ScriptedAI::me, ScriptedAI::SelectTargetFromPlayerList(), SpawnPool, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_kelthuzad::boss_kelthuzadAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (!me->HasAura(SPELL_KELTHUZAD_CHANNEL))
            {
                if (me->HasUnitState(UNIT_STATE_CASTING))
                    return;
            }
            switch (events.ExecuteEvent())
            {
                case EVENT_FLOOR_CHANGE:
                    if (pInstance)
                    {
                        if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_FLOOR)))
{
                            events.ScheduleEvent(EVENT_FLOOR_CHANGE, 15s);
                            go->SetGoState(GO_STATE_READY);
                            go->SetPhaseMask(2, true);
                        }
                    }
                    break;
                case EVENT_SPAWN_POOL:
                    SpawnHelpers();
                    break;
                case EVENT_SUMMON_SOLDIER:
                    SummonHelper(NPC_SOLDIER_OF_THE_FROZEN_WASTES, 1);
                    events.Repeat(3100ms);
                    break;
                case EVENT_SUMMON_UNSTOPPABLE_ABOMINATION:
                    SummonHelper(NPC_UNSTOPPABLE_ABOMINATION, 1);
                    events.Repeat(18s + 500ms);
                    break;
                case EVENT_SUMMON_SOUL_WEAVER:
                    SummonHelper(NPC_SOUL_WEAVER, 1);
                    events.Repeat(30s);
                    break;
                case EVENT_PHASE_2:
                    Talk(EMOTE_PHASE_TWO);
                    Talk(SAY_AGGRO);
                    events.Reset();
                    summons.DoAction(ACTION_SECOND_PHASE);
                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_DISABLE_MOVE);
                    me->GetMotionMaster()->MoveChase(me->GetVictim());
                    me->RemoveAura(SPELL_KELTHUZAD_CHANNEL);
                    me->SetReactState(REACT_AGGRESSIVE);
                    events.ScheduleEvent(EVENT_FROST_BOLT_SINGLE, 2s, 10s);
                    events.ScheduleEvent(EVENT_FROST_BOLT_MULTI, 15s, 30s);
                    events.ScheduleEvent(EVENT_DETONATE_MANA, 30s);
                    events.ScheduleEvent(EVENT_PHASE_3, 1s);
                    events.ScheduleEvent(EVENT_SHADOW_FISSURE, 25s);
                    events.ScheduleEvent(EVENT_FROST_BLAST, 45s);
                    if (Is25ManRaid())
                    {
                        events.ScheduleEvent(EVENT_CHAINS, 90s);
                    }
                    break;
                case EVENT_ENRAGE:
                    me->CastSpell(me, SPELL_BERSERK, true);
                    break;
                case EVENT_FROST_BOLT_SINGLE:
                    me->CastSpell(me->GetVictim(), RAID_MODE(SPELL_FROST_BOLT_SINGLE_10, SPELL_FROST_BOLT_SINGLE_25), false);
                    events.Repeat(2s, 10s);
                    break;
                case EVENT_FROST_BOLT_MULTI:
                    me->CastSpell(me, RAID_MODE(SPELL_FROST_BOLT_MULTI_10, SPELL_FROST_BOLT_MULTI_25), false);
                    events.Repeat(15s, 30s);
                    break;
                case EVENT_SHADOW_FISSURE:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100.0f, true))
                    {
                        me->CastSpell(target, SPELL_SHADOW_FISURE, false);
                    }
                    events.Repeat(25s);
                    break;
                case EVENT_FROST_BLAST:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, RAID_MODE(1, 0), 0, true))
                    {
                        me->CastSpell(target, SPELL_FROST_BLAST, false);
                    }
                    Talk(SAY_FROST_BLAST);
                    events.Repeat(45s);
                    break;
                case EVENT_CHAINS:
                    for (uint8 i = 0; i < 3; ++i)
                    {
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 1, 200, true, true, -SPELL_CHAINS_OF_KELTHUZAD))
{
                            me->CastSpell(target, SPELL_CHAINS_OF_KELTHUZAD, true);
                        }
                    }
                    Talk(SAY_CHAIN);
                    events.Repeat(90s);
                    break;
                case EVENT_DETONATE_MANA:
                    {
                        std::vector<Unit*> unitList;
                        ThreatContainer::StorageType const& threatList = me->GetThreatMgr().GetThreatList();
                        for (auto itr : threatList)
{
                            if (itr->getTarget()->IsPlayer()
                                    && itr->getTarget()->getPowerType() == POWER_MANA
                                    && itr->getTarget()->GetPower(POWER_MANA))
{
                                        unitList.push_back(itr->getTarget());
                                    }
                        }
                        if (!unitList.empty())
{
                            auto itr = unitList.begin();
                            advance(itr, urand(0, unitList.size() - 1));
                            me->CastSpell(*itr, SPELL_DETONATE_MANA, false);
                            Talk(SAY_SPECIAL);
                        }
                        events.Repeat(30s);
                        break;
                    }
                case EVENT_PHASE_3:
                    if (me->HealthBelowPct(45))
                    {
                        Talk(SAY_REQUEST_AID);
                        events.DelayEvents(5500ms);
                        events.ScheduleEvent(EVENT_P3_LICH_KING_SAY, 5s);
                        if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_PORTAL_1)))
{
                            go->SetGoState(GO_STATE_ACTIVE);
                        }
                        if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_PORTAL_2)))
{
                            go->SetGoState(GO_STATE_ACTIVE);
                        }
                        if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_PORTAL_3)))
{
                            go->SetGoState(GO_STATE_ACTIVE);
                        }
                        if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_KELTHUZAD_PORTAL_4)))
{
                            go->SetGoState(GO_STATE_ACTIVE);
                        }
                        break;
                    }
                    events.Repeat(1s);
                    break;
                case EVENT_P3_LICH_KING_SAY:
                    if (pInstance)
                    {
                        if (Creature* cr = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_LICH_KING_BOSS)))
{
                            cr->AI()->Talk(SAY_ANSWER_REQUEST);
                        }
                    }
                    for (uint8 i = 0 ; i < RAID_MODE(2, 4); ++i)
                    {
                        events.ScheduleEvent(EVENT_SUMMON_GUARDIAN_OF_ICECROWN, 10000 + (i * 5000));
                    }
                    break;
                case EVENT_SUMMON_GUARDIAN_OF_ICECROWN:
                    if (Creature* cr = me->SummonCreature(NPC_GUARDIAN_OF_ICECROWN, SpawnPool[RAND(0, 1, 3, 4)]))
                    {
                        cr->AI()->Talk(EMOTE_GUARDIAN_APPEAR);
                        cr->AI()->AttackStart(me->GetVictim());
                    }
                    break;
            }
            if (!me->HasUnitFlag(UNIT_FLAG_DISABLE_MOVE))
                DoMeleeAttackIfReady();
        }
References ACTION_SECOND_PHASE, Unit::CastSpell(), DATA_KELTHUZAD_FLOOR, DATA_KELTHUZAD_PORTAL_1, DATA_KELTHUZAD_PORTAL_2, DATA_KELTHUZAD_PORTAL_3, DATA_KELTHUZAD_PORTAL_4, DATA_LICH_KING_BOSS, SummonList::DoAction(), UnitAI::DoMeleeAttackIfReady(), EMOTE_GUARDIAN_APPEAR, EMOTE_PHASE_TWO, EVENT_CHAINS, EVENT_DETONATE_MANA, EVENT_ENRAGE, EVENT_FLOOR_CHANGE, EVENT_FROST_BLAST, EVENT_FROST_BOLT_MULTI, EVENT_FROST_BOLT_SINGLE, EVENT_P3_LICH_KING_SAY, EVENT_PHASE_2, EVENT_PHASE_3, EVENT_SHADOW_FISSURE, EVENT_SPAWN_POOL, EVENT_SUMMON_GUARDIAN_OF_ICECROWN, EVENT_SUMMON_SOLDIER, EVENT_SUMMON_SOUL_WEAVER, EVENT_SUMMON_UNSTOPPABLE_ABOMINATION, ObjectAccessor::GetCreature(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetMotionMaster(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), Unit::GetVictim(), GO_STATE_ACTIVE, GO_STATE_READY, Unit::HasAura(), Unit::HasUnitFlag(), Unit::HasUnitState(), Unit::HealthBelowPct(), ScriptedAI::Is25ManRaid(), ScriptedAI::me, MotionMaster::MoveChase(), NPC_GUARDIAN_OF_ICECROWN, NPC_SOLDIER_OF_THE_FROZEN_WASTES, NPC_SOUL_WEAVER, NPC_UNSTOPPABLE_ABOMINATION, pInstance, POWER_MANA, ScriptedAI::RAID_MODE(), RAND(), REACT_AGGRESSIVE, Unit::RemoveAura(), Unit::RemoveUnitFlag(), SAY_AGGRO, SAY_ANSWER_REQUEST, SAY_CHAIN, SAY_FROST_BLAST, SAY_REQUEST_AID, SAY_SPECIAL, UnitAI::SelectTarget(), Creature::SetReactState(), SpawnHelpers(), SpawnPool, SPELL_BERSERK, SPELL_CHAINS_OF_KELTHUZAD, SPELL_DETONATE_MANA, SPELL_FROST_BLAST, SPELL_FROST_BOLT_MULTI_10, SPELL_FROST_BOLT_MULTI_25, SPELL_FROST_BOLT_SINGLE_10, SPELL_FROST_BOLT_SINGLE_25, SPELL_KELTHUZAD_CHANNEL, SPELL_SHADOW_FISURE, WorldObject::SummonCreature(), SummonHelper(), summons, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_justSpawned
bool boss_kelthuzad::boss_kelthuzadAI::_justSpawned
Referenced by boss_kelthuzadAI(), and Reset().
events
EventMap boss_kelthuzad::boss_kelthuzadAI::events
pInstance
InstanceScript* boss_kelthuzad::boss_kelthuzadAI::pInstance
Referenced by boss_kelthuzadAI(), JustDied(), JustEngagedWith(), KilledUnit(), Reset(), and UpdateAI().
summons
SummonList boss_kelthuzad::boss_kelthuzadAI::summons
Referenced by JustDied(), JustSummoned(), Reset(), and UpdateAI().