AzerothCore: Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck Class Reference
Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
AnyFriendlyNotSelfUnitInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range, bool playerOnly=false)
bool operator() (Unit *u)
Private Attributes
WorldObject const * i_obj
Unit const * i_funit
float i_range
bool i_playerOnly
Detailed Description
Constructor & Destructor Documentation
AnyFriendlyNotSelfUnitInObjectRangeCheck()
Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::AnyFriendlyNotSelfUnitInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range, bool playerOnly = false) inline
: i_obj(obj), i_funit(funit), i_range(range), i_playerOnly(playerOnly) {}
Member Function Documentation
operator()()
bool Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::operator() (Unit * u) inline
        {
            if (u != i_obj && u->IsAlive() && i_obj->IsWithinDistInMap(u, i_range) && i_funit->IsFriendlyTo(u) && (!i_playerOnly || u->IsPlayer()))
                return true;
            else
                return false;
        }
References i_funit, i_obj, i_playerOnly, i_range, Unit::IsAlive(), Unit::IsFriendlyTo(), Object::IsPlayer(), and WorldObject::IsWithinDistInMap().
Member Data Documentation
i_funit
Unit const* Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::i_funit private
Referenced by operator()().
i_obj
WorldObject const* Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::i_obj private
Referenced by operator()().
i_playerOnly
bool Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::i_playerOnly private
Referenced by operator()().
i_range
float Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::i_range private
Referenced by operator()().