AzeorthCore: npc_salsalabim Class Reference
npc_salsalabim Class Reference
Classes
struct npc_salsalabimAI
Public Member Functions
npc_salsalabim ()
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_salsalabim()
npc_salsalabim::npc_salsalabim () inline
: CreatureScript("npc_salsalabim") { }
Member Function Documentation
GetAI()
CreatureAI * npc_salsalabim::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return new npc_salsalabimAI(creature);
    }
OnGossipHello()
bool npc_salsalabim::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (player->GetQuestStatus(QUEST_10004) == QUEST_STATUS_INCOMPLETE)
        {
            creature->SetFaction(FACTION_DEMON);
            creature->AI()->AttackStart(player);
        }
        else
        {
            if (creature->IsQuestGiver())
                player->PrepareQuestMenu(creature->GetGUID());
            SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
        }
        return true;
    }
References Creature::AI(), UnitAI::AttackStart(), FACTION_DEMON, Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), Unit::IsQuestGiver(), Player::PrepareQuestMenu(), QUEST_10004, QUEST_STATUS_INCOMPLETE, SendGossipMenuFor(), and Unit::SetFaction().