AzerothCore: npc_coren_direbrew Struct Reference
npc_coren_direbrew Struct Reference
Public Member Functions
npc_coren_direbrew (Creature *creature)
void sGossipSelect (Player *player, uint32 menuId, uint32 gossipListId) override
bool CanBeSeen (Player const *player) override
void Reset () override
void MoveInLineOfSight (Unit *who) override
void JustSummoned (Creature *creature) override
void DoAction (int32 action) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void SummonedCreatureDies (Creature *summon, Unit *) override
void JustDied (Unit *) override
void SummonSister (uint32 entry)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
SummonList _summons
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_coren_direbrew()
npc_coren_direbrew::npc_coren_direbrew (Creature * creature) inline
: ScriptedAI(creature), _summons(me) {}
Member Function Documentation
CanBeSeen()
bool npc_coren_direbrew::CanBeSeen (Player const * player) inline override virtual
Reimplemented from CreatureAI.
    {
        if (player->IsGameMaster())
        {
            return true;
        }
        Group const* group = player->GetGroup();
        return group && sLFGMgr->GetDungeon(group->GetGUID()) == lfg::LFG_DUNGEON_COREN_DIREBREW;
    }
References Player::GetGroup(), Group::GetGUID(), Player::IsGameMaster(), lfg::LFG_DUNGEON_COREN_DIREBREW, and sLFGMgr.
DamageTaken()
void npc_coren_direbrew::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
    {
        if (me->HealthBelowPctDamaged(66, damage) && _events.IsInPhase(PHASE_ONE))
        {
            _events.SetPhase(PHASE_TWO);
            SummonSister(NPC_ILSA_DIREBREW);
        }
        else if (me->HealthBelowPctDamaged(33, damage) && _events.IsInPhase(PHASE_TWO))
        {
            _events.SetPhase(PHASE_THREE);
            SummonSister(NPC_URSULA_DIREBREW);
        }
    }
References _events, Unit::HealthBelowPctDamaged(), EventMap::IsInPhase(), ScriptedAI::me, NPC_ILSA_DIREBREW, NPC_URSULA_DIREBREW, PHASE_ONE, PHASE_THREE, PHASE_TWO, EventMap::SetPhase(), and SummonSister().
DoAction()
void npc_coren_direbrew::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        if (action == ACTION_START_FIGHT)
        {
            _events.SetPhase(PHASE_ONE);
            me->SetImmuneToPC(false);
            me->SetFaction(FACTION_GOBLIN_DARK_IRON_BAR_PATRON);
            DoZoneInCombat();
            EntryCheckPredicate pred(NPC_ANTAGONIST);
            _summons.DoAction(ACTION_ANTAGONIST_HOSTILE, pred);
            _events.ScheduleEvent(EVENT_SUMMON_MOLE_MACHINE, 15s);
            _events.ScheduleEvent(EVENT_DIREBREW_DISARM, 20s);
        }
    }
References _events, _summons, ACTION_ANTAGONIST_HOSTILE, ACTION_START_FIGHT, SummonList::DoAction(), CreatureAI::DoZoneInCombat(), EVENT_DIREBREW_DISARM, EVENT_SUMMON_MOLE_MACHINE, FACTION_GOBLIN_DARK_IRON_BAR_PATRON, ScriptedAI::me, NPC_ANTAGONIST, PHASE_ONE, EventMap::ScheduleEvent(), Unit::SetFaction(), Unit::SetImmuneToPC(), and EventMap::SetPhase().
Referenced by sGossipSelect().
JustDied()
void npc_coren_direbrew::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        _events.Reset();
        _summons.DespawnAll();
        Map::PlayerList const& players = me->GetMap()->GetPlayers();
        if (!players.IsEmpty())
        {
            if (Group* group = players.begin()->GetSource()->GetGroup())
            {
                if (group->isLFGGroup())
                {
                    sLFGMgr->FinishDungeon(group->GetGUID(), 287, me->GetMap());
                }
            }
        }
    }
References _events, _summons, MapRefMgr::begin(), SummonList::DespawnAll(), Player::GetGroup(), WorldObject::GetMap(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), LinkedListHead::IsEmpty(), ScriptedAI::me, EventMap::Reset(), and sLFGMgr.
JustSummoned()
void npc_coren_direbrew::JustSummoned (Creature * creature) inline override virtual
Reimplemented from ScriptedAI.
    {
        _summons.Summon(creature);
    }
References _summons, and SummonList::Summon().
MoveInLineOfSight()
void npc_coren_direbrew::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
    {
        if (!_events.IsInPhase(PHASE_ALL) || !who->IsPlayer())
        {
            return;
        }
        _events.SetPhase(PHASE_INTRO);
        _events.ScheduleEvent(EVENT_INTRO_1, 6s, 0, PHASE_INTRO);
        Talk(SAY_INTRO);
    }
References _events, EVENT_INTRO_1, EventMap::IsInPhase(), Object::IsPlayer(), PHASE_ALL, PHASE_INTRO, SAY_INTRO, EventMap::ScheduleEvent(), and EventMap::SetPhase().
Reset()
void npc_coren_direbrew::Reset () inline override virtual
Reimplemented from ScriptedAI.
    {
        _events.Reset();
        _summons.DespawnAll();
        me->SetImmuneToPC(true);
        me->SetFaction(FACTION_FRIENDLY);
        _events.SetPhase(PHASE_ALL);
        for (uint8 i = 0; i < MAX_ANTAGONISTS; ++i)
        {
            me->SummonCreature(NPC_ANTAGONIST, AntagonistPos[i], TEMPSUMMON_DEAD_DESPAWN);
        }
        std::list<GameObject*> machines;
        GetGameObjectListWithEntryInGrid(machines, me, GO_MACHINE_SUMMONER, 60.f);
        for (GameObject* go : machines)
        {
            go->Delete();
        }
    }
References _events, _summons, AntagonistPos, SummonList::DespawnAll(), FACTION_FRIENDLY, GetGameObjectListWithEntryInGrid(), GO_MACHINE_SUMMONER, MAX_ANTAGONISTS, ScriptedAI::me, NPC_ANTAGONIST, PHASE_ALL, EventMap::Reset(), Unit::SetFaction(), Unit::SetImmuneToPC(), EventMap::SetPhase(), WorldObject::SummonCreature(), and TEMPSUMMON_DEAD_DESPAWN.
sGossipSelect()
void npc_coren_direbrew::sGossipSelect (Player * player, uint32 menuId, uint32 gossipListId) inline override virtual
Reimplemented from UnitAI.
    {
        if (menuId != GOSSIP_ID)
        {
            return;
        }
        if (gossipListId == GOSSIP_OPTION_FIGHT)
        {
            Talk(SAY_INSULT, player);
            DoAction(ACTION_START_FIGHT);
        }
        else if (gossipListId == GOSSIP_OPTION_APOLOGIZE)
        {
            CloseGossipMenuFor(player);
        }
    }
References ACTION_START_FIGHT, CloseGossipMenuFor(), DoAction(), GOSSIP_ID, GOSSIP_OPTION_APOLOGIZE, GOSSIP_OPTION_FIGHT, and SAY_INSULT.
SummonedCreatureDies()
void npc_coren_direbrew::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
    {
        if (summon->GetEntry() == NPC_ILSA_DIREBREW)
        {
            _events.ScheduleEvent(EVENT_RESPAWN_ILSA, 1s);
        }
        else if (summon->GetEntry() == NPC_URSULA_DIREBREW)
        {
            _events.ScheduleEvent(EVENT_RESPAWN_URSULA, 1s);
        }
    }
References _events, EVENT_RESPAWN_ILSA, EVENT_RESPAWN_URSULA, Object::GetEntry(), NPC_ILSA_DIREBREW, NPC_URSULA_DIREBREW, and EventMap::ScheduleEvent().
SummonSister()
void npc_coren_direbrew::SummonSister (uint32 entry) inline
    {
        if (Creature* sister = me->SummonCreature(entry, me->GetPosition(), TEMPSUMMON_DEAD_DESPAWN))
        {
            DoZoneInCombat(sister);
        }
    }
References CreatureAI::DoZoneInCombat(), Position::GetPosition(), ScriptedAI::me, WorldObject::SummonCreature(), and TEMPSUMMON_DEAD_DESPAWN.
Referenced by DamageTaken(), and UpdateAI().
UpdateAI()
void npc_coren_direbrew::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
    {
        if (!UpdateVictim() && !_events.IsInPhase(PHASE_INTRO))
        {
            return;
        }
        _events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
        while (uint32 eventId = _events.ExecuteEvent())
        {
            switch (eventId)
            {
                case EVENT_INTRO_1:
                    Talk(SAY_INTRO1);
                    _events.ScheduleEvent(EVENT_INTRO_2, 4s, 0, PHASE_INTRO);
                    break;
                case EVENT_INTRO_2:
                {
                    EntryCheckPredicate pred(NPC_ANTAGONIST);
                    _summons.DoAction(ACTION_ANTAGONIST_SAY_1, pred);
                    _events.ScheduleEvent(EVENT_INTRO_3, 3s, 0, PHASE_INTRO);
                    break;
                }
                case EVENT_INTRO_3:
                {
                    Talk(SAY_INTRO2);
                    EntryCheckPredicate pred(NPC_ANTAGONIST);
                    _summons.DoAction(ACTION_ANTAGONIST_SAY_2, pred);
                    break;
                }
                case EVENT_RESPAWN_ILSA:
                    SummonSister(NPC_ILSA_DIREBREW);
                    break;
                case EVENT_RESPAWN_URSULA:
                    SummonSister(NPC_URSULA_DIREBREW);
                    break;
                case EVENT_SUMMON_MOLE_MACHINE:
                {
                    me->CastCustomSpell(SPELL_MOLE_MACHINE_TARGET_PICKER, SPELLVALUE_MAX_TARGETS, 1, nullptr, true);
                    _events.RepeatEvent(15 * IN_MILLISECONDS);
                    break;
                }
                case EVENT_DIREBREW_DISARM:
                    DoCastSelf(SPELL_DIREBREW_DISARM_PRE_CAST, true);
                    _events.RepeatEvent(20 * IN_MILLISECONDS);
                    break;
                default:
                    break;
            }
            if (me->HasUnitState(UNIT_STATE_CASTING))
            {
                return;
            }
        }
        DoMeleeAttackIfReady();
    }
References _events, _summons, ACTION_ANTAGONIST_SAY_1, ACTION_ANTAGONIST_SAY_2, Unit::CastCustomSpell(), SummonList::DoAction(), UnitAI::DoCastSelf(), UnitAI::DoMeleeAttackIfReady(), EVENT_DIREBREW_DISARM, EVENT_INTRO_1, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_RESPAWN_ILSA, EVENT_RESPAWN_URSULA, EVENT_SUMMON_MOLE_MACHINE, EventMap::ExecuteEvent(), Unit::HasUnitState(), IN_MILLISECONDS, EventMap::IsInPhase(), ScriptedAI::me, NPC_ANTAGONIST, NPC_ILSA_DIREBREW, NPC_URSULA_DIREBREW, PHASE_INTRO, EventMap::RepeatEvent(), SAY_INTRO1, SAY_INTRO2, EventMap::ScheduleEvent(), SPELL_DIREBREW_DISARM_PRE_CAST, SPELL_MOLE_MACHINE_TARGET_PICKER, SPELLVALUE_MAX_TARGETS, SummonSister(), UNIT_STATE_CASTING, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_events
EventMap npc_coren_direbrew::_events private
Referenced by DamageTaken(), DoAction(), JustDied(), MoveInLineOfSight(), Reset(), SummonedCreatureDies(), and UpdateAI().
_summons
SummonList npc_coren_direbrew::_summons private
Referenced by DoAction(), JustDied(), JustSummoned(), Reset(), and UpdateAI().