AzerothCore: anonymous_namespace{BattlegroundSpamProtect.cpp} Namespace Reference
anonymous_namespace{BattlegroundSpamProtect.cpp} Namespace Reference
Functions
void AddTime (ObjectGuid guid)
uint32 GetTime (ObjectGuid guid)
bool IsCorrectDelay (ObjectGuid guid)
Variables
std::unordered_map< ObjectGuid, uint32 > _players
Function Documentation
AddTime()
void anonymous_namespace{BattlegroundSpamProtect.cpp}::AddTime (ObjectGuid guid)
    {
        _players.insert_or_assign(guid, GameTime::GetGameTime().count());
    }
References _players, and GameTime::GetGameTime().
GetTime()
uint32 anonymous_namespace{BattlegroundSpamProtect.cpp}::GetTime (ObjectGuid guid)
    {
        auto const& itr = _players.find(guid);
        if (itr != _players.end())
        {
            return itr->second;
        }
        return 0;
    }
References _players.
Referenced by IsCorrectDelay().
IsCorrectDelay()
bool anonymous_namespace{BattlegroundSpamProtect.cpp}::IsCorrectDelay (ObjectGuid guid)
    {
        // Skip if spam time < 30 secs (default)
        return GameTime::GetGameTime().count() - GetTime(guid) >= sWorld->getIntConfig(CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_SPAM_DELAY);
    }
References CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_SPAM_DELAY, GameTime::GetGameTime(), GetTime(), and sWorld.
Variable Documentation
_players
std::unordered_map<ObjectGuid , uint32 > anonymous_namespace{BattlegroundSpamProtect.cpp}::_players
Referenced by AddTime(), and GetTime().