AzerothCore: Acore::AnyDeadUnitObjectInRangeCheck Class Reference
Acore::AnyDeadUnitObjectInRangeCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
AnyDeadUnitObjectInRangeCheck (Unit *searchObj, float range)
bool operator() (Player *u)
bool operator() (Corpse *u)
bool operator() (Creature *u)
template<class NOT_INTERESTED >
bool operator() (NOT_INTERESTED *)
Protected Attributes
Unit const *const i_searchObj
float i_range
Detailed Description
Constructor & Destructor Documentation
AnyDeadUnitObjectInRangeCheck()
Acore::AnyDeadUnitObjectInRangeCheck::AnyDeadUnitObjectInRangeCheck (Unit * searchObj, float range) inline
: i_searchObj(searchObj), i_range(range) {}
Member Function Documentation
operator()() [1/4]
bool AnyDeadUnitObjectInRangeCheck::operator() (Corpse * u)
{
    return u->GetType() != CORPSE_BONES && i_searchObj->IsWithinDistInMap(u, i_range);
}
References CORPSE_BONES, Corpse::GetType(), i_range, i_searchObj, and WorldObject::IsWithinDistInMap().
operator()() [2/4]
bool AnyDeadUnitObjectInRangeCheck::operator() (Creature * u)
{
    return !u->IsAlive() && i_searchObj->IsWithinDistInMap(u, i_range);
}
References i_range, i_searchObj, Unit::IsAlive(), and WorldObject::IsWithinDistInMap().
operator()() [3/4]
template<class NOT_INTERESTED > bool Acore::AnyDeadUnitObjectInRangeCheck::operator() (NOT_INTERESTED *) inline
{ return false; }
operator()() [4/4]
bool AnyDeadUnitObjectInRangeCheck::operator() (Player * u)
{
    return !u->IsAlive() && !u->HasGhostAura() && i_searchObj->IsWithinDistInMap(u, i_range);
}
References Unit::HasGhostAura(), i_range, i_searchObj, Unit::IsAlive(), and WorldObject::IsWithinDistInMap().
Referenced by Acore::AnyDeadUnitSpellTargetInRangeCheck::operator()().
Member Data Documentation
i_range
float Acore::AnyDeadUnitObjectInRangeCheck::i_range protected
Referenced by operator()().
i_searchObj
Unit const* const Acore::AnyDeadUnitObjectInRangeCheck::i_searchObj protected
Referenced by operator()().