AzerothCore: DynamicTreeIntersectionCallback Struct Reference
DynamicTreeIntersectionCallback Struct Reference
Public Member Functions
DynamicTreeIntersectionCallback (uint32 phasemask, VMAP::ModelIgnoreFlags ignoreFlags)
bool operator() (const G3D::Ray &r, const GameObjectModel &obj, float &distance, bool stopAtFirstHit)
bool didHit () const
Private Attributes
bool _didHit
uint32 _phaseMask
VMAP::ModelIgnoreFlags _ignoreFlags
Detailed Description
Constructor & Destructor Documentation
DynamicTreeIntersectionCallback()
DynamicTreeIntersectionCallback::DynamicTreeIntersectionCallback (uint32 phasemask, VMAP::ModelIgnoreFlags ignoreFlags) inline
                                                                                        :
        _didHit(false), _phaseMask(phasemask), _ignoreFlags(ignoreFlags) { }
Member Function Documentation
didHit()
bool DynamicTreeIntersectionCallback::didHit () const inline
    {
        return _didHit;
    }
References _didHit.
Referenced by DynamicMapTree::getHeight(), DynamicMapTree::GetIntersectionTime(), and DynamicMapTree::isInLineOfSight().
operator()()
bool DynamicTreeIntersectionCallback::operator() (const G3D::Ray & r, const GameObjectModel & obj, float & distance, bool stopAtFirstHit) inline
    {
        bool result = obj.intersectRay(r, distance, stopAtFirstHit, _phaseMask, _ignoreFlags);
        if (result)
        {
            _didHit = result;
        }
        return result;
    }
References _didHit, _ignoreFlags, _phaseMask, and GameObjectModel::intersectRay().
Member Data Documentation
_didHit
bool DynamicTreeIntersectionCallback::_didHit private
Referenced by didHit(), and operator()().
_ignoreFlags
VMAP::ModelIgnoreFlags DynamicTreeIntersectionCallback::_ignoreFlags private
Referenced by operator()().
_phaseMask
uint32 DynamicTreeIntersectionCallback::_phaseMask private
Referenced by operator()().