AzerothCore: instance_gundrak::instance_gundrak_InstanceMapScript Struct Reference
instance_gundrak::instance_gundrak_InstanceMapScript Struct Reference
Public Member Functions
instance_gundrak_InstanceMapScript (Map *map)
void Initialize () override
void OnGameObjectCreate (GameObject *gameobject) override
void OnGameObjectRemove (GameObject *gameobject) override
void SetData (uint32 type, uint32) override
bool SetBossState (uint32 type, EncounterState state) override
void Update (uint32 diff) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
ObjectGuid _sladRanAltarGUID
ObjectGuid _moorabiAltarGUID
ObjectGuid _drakkariAltarGUID
ObjectGuid _bridgeGUIDs [6]
uint32 _keysInCount
uint32 _activateTimer
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_gundrak_InstanceMapScript()
instance_gundrak::instance_gundrak_InstanceMapScript::instance_gundrak_InstanceMapScript (Map * map) inline
                                                     : InstanceScript(map)
        {
            SetHeaders(DataHeader);
        }
References DataHeader, and InstanceScript::SetHeaders().
Member Function Documentation
Initialize()
void instance_gundrak::instance_gundrak_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetBossNumber(MAX_ENCOUNTERS);
            LoadDoorData(doorData);
            _keysInCount = 0;
            _activateTimer = 0;
        }
References _activateTimer, _keysInCount, doorData, InstanceScript::LoadDoorData(), MAX_ENCOUNTERS, and InstanceScript::SetBossNumber().
OnGameObjectCreate()
void instance_gundrak::instance_gundrak_InstanceMapScript::OnGameObjectCreate (GameObject * gameobject) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (gameobject->GetEntry())
            {
                case GO_ALTAR_OF_SLAD_RAN:
                    _sladRanAltarGUID = gameobject->GetGUID();
                    gameobject->SetGoState(GetBossState(DATA_SLAD_RAN) == DONE ? GO_STATE_ACTIVE : GO_STATE_READY);
                    break;
                case GO_ALTAR_OF_DRAKKARI:
                    _drakkariAltarGUID = gameobject->GetGUID();
                    gameobject->SetGoState(GetBossState(DATA_DRAKKARI_COLOSSUS) == DONE ? GO_STATE_ACTIVE : GO_STATE_READY);
                    break;
                case GO_ALTAR_OF_MOORABI:
                    _moorabiAltarGUID = gameobject->GetGUID();
                    gameobject->SetGoState(GetBossState(DATA_MOORABI) == DONE ? GO_STATE_ACTIVE : GO_STATE_READY);
                    break;
                case GO_STATUE_OF_SLAD_RAN:
                    _bridgeGUIDs[0] = gameobject->GetGUID();
                    gameobject->SetGoState(_keysInCount == 3 ? GO_STATE_ACTIVE_ALTERNATIVE : (GetBossState(DATA_SLAD_RAN) == DONE ? GO_STATE_READY : GO_STATE_ACTIVE));
                    break;
                case GO_STATUE_OF_DRAKKARI:
                    _bridgeGUIDs[1] = gameobject->GetGUID();
                    gameobject->SetGoState(_keysInCount == 3 ? GO_STATE_ACTIVE_ALTERNATIVE : (GetBossState(DATA_DRAKKARI_COLOSSUS) == DONE ? GO_STATE_READY : GO_STATE_ACTIVE));
                    break;
                case GO_STATUE_OF_MOORABI:
                    _bridgeGUIDs[2] = gameobject->GetGUID();
                    gameobject->SetGoState(_keysInCount == 3 ? GO_STATE_ACTIVE_ALTERNATIVE : (GetBossState(DATA_MOORABI) == DONE ? GO_STATE_READY : GO_STATE_ACTIVE));
                    break;
                case GO_STATUE_OF_GAL_DARAH:
                    _bridgeGUIDs[3] = gameobject->GetGUID();
                    gameobject->SetGoState(_keysInCount == 3 ? GO_STATE_ACTIVE_ALTERNATIVE : GO_STATE_READY);
                    break;
                case GO_GUNDRAK_COLLISION:
                    _bridgeGUIDs[4] = gameobject->GetGUID();
                    gameobject->SetGoState(_keysInCount == 3 ? GO_STATE_ACTIVE_ALTERNATIVE : GO_STATE_READY);
                    break;
                case GO_GUNDRAK_BRIDGE:
                    _bridgeGUIDs[5] = gameobject->GetGUID();
                    gameobject->SetGoState(GO_STATE_READY);
                    break;
                case GO_ECK_DOORS:
                case GO_ECK_UNDERWATER_GATE:
                case GO_GAL_DARAH_DOORS0:
                case GO_GAL_DARAH_DOORS1:
                case GO_GAL_DARAH_DOORS2:
                    AddDoor(gameobject);
                    break;
            }
        }
References _bridgeGUIDs, _drakkariAltarGUID, _keysInCount, _moorabiAltarGUID, _sladRanAltarGUID, InstanceScript::AddDoor(), DATA_DRAKKARI_COLOSSUS, DATA_MOORABI, DATA_SLAD_RAN, DONE, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_ALTAR_OF_DRAKKARI, GO_ALTAR_OF_MOORABI, GO_ALTAR_OF_SLAD_RAN, GO_ECK_DOORS, GO_ECK_UNDERWATER_GATE, GO_GAL_DARAH_DOORS0, GO_GAL_DARAH_DOORS1, GO_GAL_DARAH_DOORS2, GO_GUNDRAK_BRIDGE, GO_GUNDRAK_COLLISION, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, GO_STATUE_OF_DRAKKARI, GO_STATUE_OF_GAL_DARAH, GO_STATUE_OF_MOORABI, GO_STATUE_OF_SLAD_RAN, and GameObject::SetGoState().
OnGameObjectRemove()
void instance_gundrak::instance_gundrak_InstanceMapScript::OnGameObjectRemove (GameObject * gameobject) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (gameobject->GetEntry())
            {
                case GO_ECK_DOORS:
                case GO_ECK_UNDERWATER_GATE:
                case GO_GAL_DARAH_DOORS0:
                case GO_GAL_DARAH_DOORS1:
                case GO_GAL_DARAH_DOORS2:
                    RemoveDoor(gameobject);
                    break;
            }
        }
References Object::GetEntry(), GO_ECK_DOORS, GO_ECK_UNDERWATER_GATE, GO_GAL_DARAH_DOORS0, GO_GAL_DARAH_DOORS1, GO_GAL_DARAH_DOORS2, and InstanceScript::RemoveDoor().
SetBossState()
bool instance_gundrak::instance_gundrak_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
            {
                if (state == DONE && (type == DATA_SLAD_RAN || type == DATA_MOORABI || type == DATA_DRAKKARI_COLOSSUS))
                    ++_keysInCount;
                return false;
            }
            if (state != DONE)
                return true;
            switch (type)
            {
                case DATA_SLAD_RAN:
                    if (GameObject* altar = instance->GetGameObject(_sladRanAltarGUID))
                        altar->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    break;
                case DATA_MOORABI:
                    if (GameObject* altar = instance->GetGameObject(_moorabiAltarGUID))
                        altar->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    break;
                case DATA_DRAKKARI_COLOSSUS:
                    if (GameObject* altar = instance->GetGameObject(_drakkariAltarGUID))
                        altar->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    break;
                case DATA_ECK_THE_FEROCIOUS_INIT:
                    {
                        Position pos = {1624.70f, 891.43f, 95.08f, 1.2f};
                        if (instance->IsHeroic())
                            instance->SummonCreature(NPC_ECK_THE_FEROCIOUS, pos);
                        break;
                    }
            }
            return true;
        }
References _drakkariAltarGUID, _keysInCount, _moorabiAltarGUID, _sladRanAltarGUID, DATA_DRAKKARI_COLOSSUS, DATA_ECK_THE_FEROCIOUS_INIT, DATA_MOORABI, DATA_SLAD_RAN, DONE, Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::instance, Map::IsHeroic(), NPC_ECK_THE_FEROCIOUS, InstanceScript::SetBossState(), and Map::SummonCreature().
Referenced by SetData().
SetData()
void instance_gundrak::instance_gundrak_InstanceMapScript::SetData (uint32 type, uint32) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case NPC_ECK_THE_FEROCIOUS:
                    if (GetBossState(DATA_ECK_THE_FEROCIOUS_INIT) != DONE)
                    {
                        SetBossState(DATA_ECK_THE_FEROCIOUS_INIT, NOT_STARTED);
                        SetBossState(DATA_ECK_THE_FEROCIOUS_INIT, DONE);
                    }
                    break;
                case GO_ALTAR_OF_SLAD_RAN:
                    if (GameObject* statue = instance->GetGameObject(_bridgeGUIDs[0]))
                        statue->SetGoState(GO_STATE_READY);
                    break;
                case GO_ALTAR_OF_DRAKKARI:
                    if (GameObject* statue = instance->GetGameObject(_bridgeGUIDs[1]))
                        statue->SetGoState(GO_STATE_READY);
                    break;
                case GO_ALTAR_OF_MOORABI:
                    if (GameObject* statue = instance->GetGameObject(_bridgeGUIDs[2]))
                        statue->SetGoState(GO_STATE_READY);
                    break;
            }
            if (type >= GO_ALTAR_OF_SLAD_RAN)
            {
                for (uint8 i = 0; i < 3; ++i)
                    if (GameObject* statue = instance->GetGameObject(_bridgeGUIDs[i]))
                        if (statue->GetGoState() != GO_STATE_READY)
                            return;
                _activateTimer = 1;
            }
        }
References _activateTimer, _bridgeGUIDs, DATA_ECK_THE_FEROCIOUS_INIT, DONE, InstanceScript::GetBossState(), Map::GetGameObject(), GO_ALTAR_OF_DRAKKARI, GO_ALTAR_OF_MOORABI, GO_ALTAR_OF_SLAD_RAN, GO_STATE_READY, InstanceScript::instance, NOT_STARTED, NPC_ECK_THE_FEROCIOUS, and SetBossState().
Update()
void instance_gundrak::instance_gundrak_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!_activateTimer)
                return;
            _activateTimer += diff;
            if (_activateTimer >= 5000)
            {
                _activateTimer = 0;
                for (uint8 i = 0; i < 5; ++i)
                    if (GameObject* go = instance->GetGameObject(_bridgeGUIDs[i]))
                        go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
            }
        }
References _activateTimer, _bridgeGUIDs, Map::GetGameObject(), GO_STATE_ACTIVE_ALTERNATIVE, and InstanceScript::instance.
Member Data Documentation
_activateTimer
uint32 instance_gundrak::instance_gundrak_InstanceMapScript::_activateTimer
Referenced by Initialize(), SetData(), and Update().
_bridgeGUIDs
ObjectGuid instance_gundrak::instance_gundrak_InstanceMapScript::_bridgeGUIDs[6]
Referenced by OnGameObjectCreate(), SetData(), and Update().
_drakkariAltarGUID
ObjectGuid instance_gundrak::instance_gundrak_InstanceMapScript::_drakkariAltarGUID
Referenced by OnGameObjectCreate(), and SetBossState().
_keysInCount
uint32 instance_gundrak::instance_gundrak_InstanceMapScript::_keysInCount
Referenced by Initialize(), OnGameObjectCreate(), and SetBossState().
_moorabiAltarGUID
ObjectGuid instance_gundrak::instance_gundrak_InstanceMapScript::_moorabiAltarGUID
Referenced by OnGameObjectCreate(), and SetBossState().
_sladRanAltarGUID
ObjectGuid instance_gundrak::instance_gundrak_InstanceMapScript::_sladRanAltarGUID
Referenced by OnGameObjectCreate(), and SetBossState().