AzerothCore: ItemPosCount Struct Reference
ItemPosCount Struct Reference
#include "Player.h"
Public Member Functions
ItemPosCount (uint16 _pos, uint32 _count)
bool isContainedIn (std::vector< ItemPosCount > const &vec) const
Public Attributes
uint16 pos
uint32 count
Detailed Description
Constructor & Destructor Documentation
ItemPosCount()
ItemPosCount::ItemPosCount (uint16 _pos, uint32 _count) inline
: pos(_pos), count(_count) {}
Member Function Documentation
isContainedIn()
bool ItemPosCount::isContainedIn (std::vector< ItemPosCount > const & vec) const
{
    for (ItemPosCountVec::const_iterator itr = vec.begin(); itr != vec.end(); ++itr)
        if (itr->pos == pos)
            return true;
    return false;
}
References pos.
Referenced by Guild::BankMoveItemData::_ReserveSpace(), Player::CanStoreItem_InBag(), Player::CanStoreItem_InInventorySlots(), and Player::CanStoreItem_InSpecificSlot().
Member Data Documentation
count
uint32 ItemPosCount::count
Referenced by Guild::BankMoveItemData::_StoreItem().
pos
uint16 ItemPosCount::pos
Referenced by Guild::BankMoveItemData::_StoreItem(), and isContainedIn().