AzerothCore: MotionTransport Class Reference
MotionTransport Class Reference
#include "Transport.h"
Public Member Functions
~MotionTransport () override
bool CreateMoTrans (ObjectGuid::LowType guidlow, uint32 entry, uint32 mapid, float x, float y, float z, float ang, uint32 animprogress)
void CleanupsBeforeDelete (bool finalCleanup=true) override
void BuildUpdate (UpdateDataMapType &data_map, UpdatePlayerSet &) override
void Update (uint32 diff) override
void DelayedUpdate (uint32 diff)
void UpdatePosition (float x, float y, float z, float o)
void AddPassenger (WorldObject *passenger, bool withAll=false) override
void RemovePassenger (WorldObject *passenger, bool withAll=false) override
Creature * CreateNPCPassenger (ObjectGuid::LowType guid, CreatureData const *data)
GameObject * CreateGOPassenger (ObjectGuid::LowType guid, GameObjectData const *data)
void LoadStaticPassengers ()
PassengerSet const & GetStaticPassengers () const
void UnloadStaticPassengers ()
void UnloadNonStaticPassengers ()
void SetPassengersLoaded (bool loaded)
bool PassengersLoaded () const
KeyFrameVec const & GetKeyFrames () const
void EnableMovement (bool enabled)
TransportTemplate const * GetTransportTemplate () const
uint32 GetPeriod () const
void SetPeriod (uint32 period)
std::string GetDebugInfo () const override
Public Member Functions inherited from Transport
Transport ()
void CalculatePassengerPosition (float &x, float &y, float &z, float *o=nullptr) const override
This method transforms supplied transport offsets into global coordinates.
void CalculatePassengerOffset (float &x, float &y, float &z, float *o=nullptr) const override
This method transforms supplied global coordinates into local offsets.
virtual void AddPassenger (WorldObject *passenger, bool withAll=false)=0
virtual void RemovePassenger (WorldObject *passenger, bool withAll=false)=0
PassengerSet const & GetPassengers () const
uint32 GetPathProgress () const
void SetPathProgress (uint32 val)
Public Member Functions inherited from GameObject
GameObject ()
~GameObject () override
void BuildValuesUpdate (uint8 updateType, ByteBuffer *data, Player *target) override
void AddToWorld () override
void RemoveFromWorld () override
void CleanupsBeforeDelete (bool finalCleanup=true) override
uint32 GetDynamicFlags () const override
void ReplaceAllDynamicFlags (uint32 flag) override
virtual bool Create (ObjectGuid::LowType guidlow, uint32 name_id, Map *map, uint32 phaseMask, float x, float y, float z, float ang, G3D::Quat const &rotation, uint32 animprogress, GOState go_state, uint32 artKit=0)
void Update (uint32 p_time) override
GameObjectTemplate const * GetGOInfo () const
GameObjectTemplateAddon const * GetTemplateAddon () const
GameObjectData const * GetGameObjectData () const
GameObjectValue const * GetGOValue () const
bool IsTransport () const
bool IsDestructibleBuilding () const
ObjectGuid::LowType GetSpawnId () const
void SetLocalRotationAngles (float z_rot, float y_rot, float x_rot)
void SetLocalRotation (G3D::Quat const &rot)
void SetTransportPathRotation (float qx, float qy, float qz, float qw)
G3D::Quat const & GetLocalRotation () const
int64 GetPackedLocalRotation () const
G3D::Quat GetWorldRotation () const
std::string const & GetNameForLocaleIdx (LocaleConstant locale_idx) const override
void SaveToDB (bool saveAddon=false)
void SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask, bool saveAddon=false)
bool LoadFromDB (ObjectGuid::LowType guid, Map *map)
bool LoadGameObjectFromDB (ObjectGuid::LowType guid, Map *map, bool addToMap=true)
void DeleteFromDB ()
void SetOwnerGUID (ObjectGuid owner)
ObjectGuid GetOwnerGUID () const
Unit * GetOwner () const
void SetSpellId (uint32 id)
uint32 GetSpellId () const
time_t GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (int32 respawn)
void SetRespawnDelay (int32 respawn)
void Respawn ()
bool isSpawned () const
bool isSpawnedByDefault () const
void SetSpawnedByDefault (bool b)
uint32 GetRespawnDelay () const
void Refresh ()
void DespawnOrUnsummon (Milliseconds delay=0ms, Seconds forcedRespawnTime=0s)
void Delete ()
void GetFishLoot (Loot *loot, Player *loot_owner)
void GetFishLootJunk (Loot *loot, Player *loot_owner)
GameobjectTypes GetGoType () const
void SetGoType (GameobjectTypes type)
GOState GetGoState () const
void SetGoState (GOState state)
uint8 GetGoArtKit () const
void SetGoArtKit (uint8 artkit)
uint8 GetGoAnimProgress () const
void SetGoAnimProgress (uint8 animprogress)
void SetPhaseMask (uint32 newPhaseMask, bool update) override
void EnableCollision (bool enable)
GameObjectFlags GetGameObjectFlags () const
bool HasGameObjectFlag (GameObjectFlags flags) const
void SetGameObjectFlag (GameObjectFlags flags)
void RemoveGameObjectFlag (GameObjectFlags flags)
void ReplaceAllGameObjectFlags (GameObjectFlags flags)
void Use (Unit *user)
LootState getLootState () const
void SetLootState (LootState s, Unit *unit=nullptr)
uint16 GetLootMode () const
bool HasLootMode (uint16 lootMode) const
void SetLootMode (uint16 lootMode)
void AddLootMode (uint16 lootMode)
void RemoveLootMode (uint16 lootMode)
void ResetLootMode ()
void AddToSkillupList (ObjectGuid playerGuid)
bool IsInSkillupList (ObjectGuid playerGuid) const
void AddUniqueUse (Player *player)
void AddUse ()
uint32 GetUseCount () const
uint32 GetUniqueUseCount () const
void SaveRespawnTime () override
void SaveRespawnTime (uint32 forceDelay)
Player * GetLootRecipient () const
Group * GetLootRecipientGroup () const
void SetLootRecipient (Creature *creature)
void SetLootRecipient (Map *map)
bool IsLootAllowedFor (Player const *player) const
bool HasLootRecipient () const
void SetLootGenerationTime ()
uint32 GetLootGenerationTime () const
GameObject * GetLinkedTrap ()
void SetLinkedTrap (GameObject *linkedTrap)
bool hasQuest (uint32 quest_id) const override
bool hasInvolvedQuest (uint32 quest_id) const override
bool ActivateToQuest (Player *target) const
void UseDoorOrButton (uint32 time_to_restore=0, bool alternative=false, Unit *user=nullptr)
void ResetDoorOrButton ()
void TriggeringLinkedGameObject (uint32 trapEntry, Unit *target)
bool IsNeverVisible () const override
bool IsAlwaysVisibleFor (WorldObject const *seer) const override
bool IsInvisibleDueToDespawn () const override
uint8 getLevelForTarget (WorldObject const *target) const override
GameObject * LookupFishingHoleAround (float range)
void CastSpell (Unit *target, uint32 spell)
void SendCustomAnim (uint32 anim)
bool IsInRange (float x, float y, float z, float radius) const
void ModifyHealth (int32 change, Unit *attackerOrHealer=nullptr, uint32 spellId=0)
void SetDestructibleBuildingModifyState (bool allow)
void SetDestructibleState (GameObjectDestructibleState state, Player *eventInvoker=nullptr, bool setHealth=false)
GameObjectDestructibleState GetDestructibleState () const
void EventInform (uint32 eventId)
virtual uint32 GetScriptId () const
GameObjectAI * AI () const
std::string const & GetAIName () const
void SetDisplayId (uint32 displayid)
uint32 GetDisplayId () const
void GetRespawnPosition (float &x, float &y, float &z, float *ori=nullptr) const
void SetPosition (float x, float y, float z, float o)
void SetPosition (const Position &pos)
bool IsStaticTransport () const
bool IsMotionTransport () const
Transport * ToTransport ()
Transport const * ToTransport () const
StaticTransport * ToStaticTransport ()
StaticTransport const * ToStaticTransport () const
MotionTransport * ToMotionTransport ()
MotionTransport const * ToMotionTransport () const
float GetStationaryX () const override
float GetStationaryY () const override
float GetStationaryZ () const override
float GetStationaryO () const override
float GetInteractionDistance () const
void UpdateModelPosition ()
bool IsAtInteractDistance (Position const &pos, float radius) const
bool IsAtInteractDistance (Player const *player, SpellInfo const *spell=nullptr) const
bool IsWithinDistInMap (Player const *player) const
SpellInfo const * GetSpellForLock (Player const *player) const
bool ValidateGameobjectType () const
bool IsInstanceGameobject () const
uint8 GameobjectStateToInt (GOState *state) const
bool IsAllowedToSaveToDB () const
void AllowSaveToDB (bool enable)
void SaveStateToDB ()
std::string GetDebugInfo () const override
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
Public Member Functions inherited from WorldObject
~WorldObject () override
virtual void Update (uint32)
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void AddToWorld () override
void RemoveFromWorld () override
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, WorldObject const *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle, bool disableWarning=false)
Position GetNearPosition (float dist, float angle, bool disableWarning=false)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius, bool disableWarning=false)
void GetContactPoint (WorldObject const *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (WorldObject const *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
virtual float GetCombatReach () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
virtual void SetPhaseMask (uint32 newPhaseMask, bool update)
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
virtual std::string const & GetNameForLocaleIdx (LocaleConstant) const
float GetDistance (WorldObject const *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (WorldObject const *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (WorldObject const *obj) const
bool IsSelfOrInSameMap (WorldObject const *obj) const
bool IsInMap (WorldObject const *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinLOS (float x, float y, float z, VMAP::ModelIgnoreFlags ignoreFlags=VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, VMAP::ModelIgnoreFlags ignoreFlags=VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
Position GetHitSpherePointFor (Position const &dest, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (WorldObject const *obj1, WorldObject const *obj2, float size=0) const
virtual void CleanupsBeforeDelete (bool finalCleanup=true)
virtual void SendMessageToSet (WorldPacket const *data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const *data, float dist, bool self) const
virtual void SendMessageToSet (WorldPacket const *data, Player const *skipped_rcvr) const
virtual uint8 getLevelForTarget (WorldObject const *) const
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayRadiusSound (uint32 sound_id, float radius)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void PlayRadiusMusic (uint32 music_id, float radius)
void SendObjectDeSpawnAnim (ObjectGuid guid)
virtual void SaveRespawnTime ()
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (WorldObject const *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr, bool visibleBySummonerOnly=false) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr, bool visibleBySummonerOnly=false)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true, GOSummonType summonType=GO_SUMMON_TIMED_OR_CORPSE_DESPAWN)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
void DestroyForNearbyPlayers ()
virtual void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false)
void BuildUpdate (UpdateDataMapType &data_map, UpdatePlayerSet &player_set) override
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
bool IsFarVisible () const
bool IsVisibilityOverridden () const
void SetVisibilityDistanceOverride (VisibilityDistanceType type)
void SetWorldObject (bool apply)
bool IsPermanentWorldObject () const
bool IsWorldObject () const
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
virtual ObjectGuid GetTransGUID () const
void SetTransport (Transport *t)
virtual float GetStationaryX () const
virtual float GetStationaryY () const
virtual float GetStationaryZ () const
virtual float GetStationaryO () const
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
virtual float GetCollisionHeight () const
virtual float GetCollisionWidth () const
virtual float GetCollisionRadius () const
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
void RemoveAllowedLooter (ObjectGuid guid)
std::string GetDebugInfo () const override
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
virtual void AddToWorld ()
virtual void RemoveFromWorld ()
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
virtual void SetObjectScale (float scale)
virtual uint32 GetDynamicFlags () const
bool HasDynamicFlag (uint32 flag) const
virtual void SetDynamicFlag (uint32 flag)
virtual void RemoveDynamicFlag (uint32 flag)
virtual void ReplaceAllDynamicFlags (uint32 flag)
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target)
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target)
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
virtual bool hasQuest (uint32) const
virtual bool hasInvolvedQuest (uint32) const
virtual void BuildUpdate (UpdateDataMapType &, UpdatePlayerSet &)
void BuildFieldsUpdate (Player *, UpdateDataMapType &)
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
bool IsCreature () const
Creature * ToCreature ()
Creature const * ToCreature () const
bool IsUnit () const
Unit * ToUnit ()
Unit const * ToUnit () const
bool IsGameObject () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
bool IsCorpse () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
bool IsDynamicObject () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
bool IsItem () const
virtual std::string GetDebugInfo () const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
std::string GetDebugInfo () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
Position (Position &&)=default
Position & operator= (const Position &)=default
Position & operator= (Position &&)=default
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (Position const *pos, float width) const
std::string ToString () const
Public Member Functions inherited from GridObject< GameObject >
bool IsInGrid () const
void AddToGrid (GridRefMgr< GameObject > &m)
void RemoveFromGrid ()
virtual void CalculatePassengerPosition (float &x, float &y, float &z, float *o=nullptr) const =0
This method transforms supplied transport offsets into global coordinates.
virtual void CalculatePassengerOffset (float &x, float &y, float &z, float *o=nullptr) const =0
This method transforms supplied global coordinates into local offsets.
Private Member Functions
MotionTransport ()
void MoveToNextWaypoint ()
float CalculateSegmentPos (float perc)
bool TeleportTransport (uint32 newMapid, float x, float y, float z, float o)
void DelayedTeleportTransport ()
void UpdatePassengerPositions (PassengerSet &passengers)
void DoEventIfAny (KeyFrame const &node, bool departure)
bool IsMoving () const
Helpers to know if stop frame was reached.
void SetMoving (bool val)
Private Attributes
TransportTemplate const * _transportInfo
KeyFrameVec::const_iterator _currentFrame
KeyFrameVec::const_iterator _nextFrame
TimeTrackerSmall _positionChangeTimer
bool _isMoving
bool _pendingStop
bool _triggeredArrivalEvent
These are needed to properly control events triggering only once for each frame.
bool _triggeredDepartureEvent
PassengerSet _staticPassengers
std::mutex Lock
bool _passengersLoaded
bool _delayedTeleport
Friends
MotionTransport * TransportMgr::CreateTransport (uint32, ObjectGuid::LowType, Map *)
Additional Inherited Members
Public Types inherited from Transport
typedef std::set< WorldObject * > PassengerSet
Static Public Member Functions inherited from GameObject
static void SetGoArtKit (uint8 artkit, GameObject *go, ObjectGuid::LowType lowguid=0)
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Public Attributes inherited from GameObject
Loot loot
uint32 m_groupLootTimer
uint32 lootingGroupLowGUID
GameObjectModel * m_model
Public Attributes inherited from WorldObject
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
ElunaEventProcessor * elunaEvents
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Static Public Attributes inherited from GameObject
static std::unordered_map< int, goEventFlag > gameObjectToEventFlag = { }
Protected Types inherited from GameObject
typedef std::map< uint32, ObjectGuid > ChairSlotAndUser
Protected Member Functions inherited from GameObject
bool AIM_Initialize ()
GameObjectModel * CreateModel ()
void UpdateModel ()
Protected Member Functions inherited from WorldObject
WorldObject (bool isWorldObject)
virtual void ProcessPositionDataChanged (PositionFullTerrainStatus const &data)
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsNeverVisible () const
virtual bool IsAlwaysVisibleFor (WorldObject const *) const
virtual bool IsInvisibleDueToDespawn () const
virtual bool IsAlwaysDetectableFor (WorldObject const *) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
bool _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
virtual void BuildValuesUpdate (uint8 updateType, ByteBuffer *data, Player *target)
virtual void AddToObjectUpdate ()=0
virtual void RemoveFromObjectUpdate ()=0
void AddToObjectUpdateIfNeeded ()
Protected Member Functions inherited from MovableMapObject
MovableMapObject ()=default
Protected Member Functions inherited from TransportBase
TransportBase ()=default
virtual ~TransportBase ()=default
Static Protected Member Functions inherited from TransportBase
static void CalculatePassengerPosition (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
static void CalculatePassengerOffset (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
Protected Attributes inherited from Transport
PassengerSet _passengers
Protected Attributes inherited from GameObject
uint32 m_spellId
time_t m_respawnTime
uint32 m_respawnDelayTime
uint32 m_despawnDelay
Seconds m_despawnRespawnTime
Seconds m_restockTime
LootState m_lootState
bool m_spawnedByDefault
uint32 m_cooldownTime
std::unordered_map< ObjectGuid, int32 > m_SkillupList
ObjectGuid m_ritualOwnerGUID
GuidSet m_unique_users
uint32 m_usetimes
ChairSlotAndUser ChairListSlots
ObjectGuid::LowType m_spawnId
For new or temporary gameobjects is 0 for saved it is lowguid.
GameObjectTemplate const * m_goInfo
GameObjectData const * m_goData
GameObjectValue m_goValue
bool m_allowModifyDestructibleBuilding
int64 m_packedRotation
G3D::Quat m_localRotation
Position m_stationaryPosition
ObjectGuid m_lootRecipient
ObjectGuid::LowType m_lootRecipientGroup
uint16 m_LootMode
uint32 m_lootGenerationTime
ObjectGuid m_linkedTrap
ObjectGuid _lootStateUnitGUID
Protected Attributes inherited from WorldObject
std::string m_name
bool m_isActive
bool m_isFarVisible
Optional< float > m_visibilityDistanceOverride
const bool m_isWorldObject
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Detailed Description
Constructor & Destructor Documentation
MotionTransport()
MotionTransport::MotionTransport () private
                                 : Transport(), _transportInfo(nullptr), _isMoving(true), _pendingStop(false), _triggeredArrivalEvent(false), _triggeredDepartureEvent(false), _passengersLoaded(false), _delayedTeleport(false)
{
    m_updateFlag = UPDATEFLAG_TRANSPORT | UPDATEFLAG_LOWGUID | UPDATEFLAG_STATIONARY_POSITION | UPDATEFLAG_ROTATION;
}
References Object::m_updateFlag, UPDATEFLAG_LOWGUID, UPDATEFLAG_ROTATION, UPDATEFLAG_STATIONARY_POSITION, and UPDATEFLAG_TRANSPORT.
~MotionTransport()
MotionTransport::~MotionTransport () override
{
    HashMapHolder<MotionTransport>::Remove(this);
    ASSERT(_passengers.empty());
    UnloadStaticPassengers();
}
References Transport::_passengers, ASSERT, HashMapHolder< T >::Remove(), and UnloadStaticPassengers().
Member Function Documentation
AddPassenger()
void MotionTransport::AddPassenger (WorldObject * passenger, bool withAll = false) override virtual
Implements Transport.
{
    std::lock_guard<std::mutex> guard(Lock);
    if (_passengers.insert(passenger).second)
    {
        if (Player* plr = passenger->ToPlayer())
            sScriptMgr->OnAddPassenger(ToTransport(), plr);
        if (withAll)
        {
            if (Transport* t = passenger->GetTransport()) // SHOULD NEVER HAPPEN
                t->RemovePassenger(passenger, false);
            float x, y, z, o;
            passenger->GetPosition(x, y, z, o);
            CalculatePassengerOffset(x, y, z, &o);
            passenger->SetTransport(this);
            passenger->m_movementInfo.flags |= MOVEMENTFLAG_ONTRANSPORT;
            passenger->m_movementInfo.transport.guid = GetGUID();
            passenger->m_movementInfo.transport.pos.Relocate(x, y, z, o);
            if (passenger->ToUnit())
            {
                passenger->ToUnit()->AddUnitState(UNIT_STATE_IGNORE_PATHFINDING);
            }
        }
    }
}
References Transport::_passengers, Unit::AddUnitState(), Transport::CalculatePassengerOffset(), MovementInfo::flags, Object::GetGUID(), Position::GetPosition(), WorldObject::GetTransport(), MovementInfo::TransportInfo::guid, Lock, WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, MovementInfo::TransportInfo::pos, Position::Relocate(), WorldObject::SetTransport(), sScriptMgr, Object::ToPlayer(), GameObject::ToTransport(), Object::ToUnit(), MovementInfo::transport, and UNIT_STATE_IGNORE_PATHFINDING.
Referenced by Battleground::AddCreature(), and PassengerController::SummonCreatures().
BuildUpdate()
void MotionTransport::BuildUpdate (UpdateDataMapType & data_map, UpdatePlayerSet &) override virtual
Reimplemented from WorldObject.
{
    Map::PlayerList const& players = GetMap()->GetPlayers();
    if (players.IsEmpty())
        return;
    for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
        BuildFieldsUpdate(itr->GetSource(), data_map);
    ClearUpdateMask(true);
}
References MapRefMgr::begin(), Object::BuildFieldsUpdate(), Object::ClearUpdateMask(), MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), and LinkedListHead::IsEmpty().
CalculateSegmentPos()
float MotionTransport::CalculateSegmentPos (float perc) private
{
    KeyFrame const& frame = *_currentFrame;
    const float speed = float(m_goInfo->moTransport.moveSpeed);
    const float accel = float(m_goInfo->moTransport.accelRate);
    float timeSinceStop = frame.TimeFrom + (now - (1.0f / IN_MILLISECONDS) * frame.DepartureTime);
    float timeUntilStop = frame.TimeTo - (now - (1.0f / IN_MILLISECONDS) * frame.DepartureTime);
    float segmentPos, dist;
    float accelTime = _transportInfo->accelTime;
    float accelDist = _transportInfo->accelDist;
    // calculate from nearest stop, less confusing calculation...
    if (timeSinceStop < timeUntilStop)
    {
        if (timeSinceStop < accelTime)
            dist = 0.5f * accel * timeSinceStop * timeSinceStop;
        else
            dist = accelDist + (timeSinceStop - accelTime) * speed;
        segmentPos = dist - frame.DistSinceStop;
    }
    else
    {
        if (timeUntilStop < _transportInfo->accelTime)
            dist = 0.5f * accel * timeUntilStop * timeUntilStop;
        else
            dist = accelDist + (timeUntilStop - accelTime) * speed;
        segmentPos = frame.DistUntilStop - dist;
    }
    return segmentPos / frame.NextDistFromPrev;
}
References _currentFrame, _transportInfo, TransportTemplate::accelDist, GameObjectTemplate::accelRate, TransportTemplate::accelTime, KeyFrame::DepartureTime, KeyFrame::DistSinceStop, KeyFrame::DistUntilStop, IN_MILLISECONDS, GameObject::m_goInfo, GameObjectTemplate::moTransport, GameObjectTemplate::moveSpeed, KeyFrame::NextDistFromPrev, KeyFrame::TimeFrom, and KeyFrame::TimeTo.
Referenced by Update().
CleanupsBeforeDelete()
void MotionTransport::CleanupsBeforeDelete (bool finalCleanup = true) override virtual
Reimplemented from GameObject.
{
    UnloadStaticPassengers();
    while (!_passengers.empty())
    {
        WorldObject* obj = *_passengers.begin();
        RemovePassenger(obj);
        obj->SetTransport(nullptr);
        obj->m_movementInfo.transport.Reset();
        obj->m_movementInfo.RemoveMovementFlag(MOVEMENTFLAG_ONTRANSPORT);
    }
    GameObject::CleanupsBeforeDelete(finalCleanup);
}
References Transport::_passengers, GameObject::CleanupsBeforeDelete(), WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, MovementInfo::RemoveMovementFlag(), RemovePassenger(), MovementInfo::TransportInfo::Reset(), WorldObject::SetTransport(), MovementInfo::transport, and UnloadStaticPassengers().
CreateGOPassenger()
GameObject * MotionTransport::CreateGOPassenger (ObjectGuid::LowType guid, GameObjectData const * data)
{
    Map* map = GetMap();
    GameObject* go = new GameObject();
    ASSERT(!sObjectMgr->IsGameObjectStaticTransport(data->id));
    if (!go->LoadGameObjectFromDB(guid, map, false))
    {
        delete go;
        return nullptr;
    }
    float x = data->posX;
    float y = data->posY;
    float z = data->posZ;
    float o = data->orientation;
    go->SetTransport(this);
    go->m_movementInfo.transport.guid = GetGUID();
    go->m_movementInfo.transport.pos.Relocate(x, y, z, o);
    CalculatePassengerPosition(x, y, z, &o);
    go->Relocate(x, y, z, o);
    if (!go->IsPositionValid())
    {
        LOG_ERROR("entities.transport", "GameObject ({}) not created. Suggested coordinates aren't valid (X: {} Y: {})",
            go->GetGUID().ToString(), go->GetPositionX(), go->GetPositionY());
        delete go;
        return nullptr;
    }
    if (!map->AddToMap(go))
    {
        delete go;
        return nullptr;
    }
    _staticPassengers.insert(go);
    return go;
}
References _staticPassengers, Map::AddToMap(), ASSERT, Transport::CalculatePassengerPosition(), GameObject::GameObject(), Object::GetGUID(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), MovementInfo::TransportInfo::guid, GameObjectData::id, Position::IsPositionValid(), GameObject::LoadGameObjectFromDB(), LOG_ERROR, WorldObject::m_movementInfo, GameObjectData::orientation, MovementInfo::TransportInfo::pos, GameObjectData::posX, GameObjectData::posY, GameObjectData::posZ, Position::Relocate(), WorldObject::SetTransport(), sObjectMgr, ObjectGuid::ToString(), and MovementInfo::transport.
Referenced by LoadStaticPassengers().
CreateMoTrans()
bool MotionTransport::CreateMoTrans (ObjectGuid::LowType guidlow, uint32 entry, uint32 mapid, float x, float y, float z, float ang, uint32 animprogress)
{
    Relocate(x, y, z, ang);
    if (!IsPositionValid())
    {
        LOG_ERROR("entities.transport", "Transport (GUID: {}) not created. Suggested coordinates isn't valid (X: {} Y: {})",
                       guidlow, x, y);
        return false;
    }
    Object::_Create(guidlow, 0, HighGuid::Mo_Transport);
    GameObjectTemplate const* goinfo = sObjectMgr->GetGameObjectTemplate(entry);
    if (!goinfo)
    {
        LOG_ERROR("entities.transport", "Transport not created: entry in `gameobject_template` not found, guidlow: {} map: {}  (X: {} Y: {} Z: {}) ang: {}", guidlow, mapid, x, y, z, ang);
        return false;
    }
    m_goInfo = goinfo;
    TransportTemplate const* tInfo = sTransportMgr->GetTransportTemplate(entry);
    if (!tInfo)
    {
        LOG_ERROR("entities.transport", "Transport {} (name: {}) will not be created, missing `transport_template` entry.", entry, goinfo->name);
        return false;
    }
    _transportInfo = tInfo;
    // initialize waypoints
    _nextFrame = tInfo->keyFrames.begin();
    _currentFrame = _nextFrame++;
    _triggeredArrivalEvent = false;
    _triggeredDepartureEvent = false;
    if (GameObjectTemplateAddon const* addon = GetTemplateAddon())
    {
        SetUInt32Value(GAMEOBJECT_FACTION, addon->faction);
        ReplaceAllGameObjectFlags((GameObjectFlags)addon->flags);
    }
    SetObjectScale(goinfo->size);
    SetPathProgress(0);
    SetPeriod(tInfo->pathTime);
    SetEntry(goinfo->entry);
    SetDisplayId(goinfo->displayId);
    SetGoState(!goinfo->moTransport.canBeStopped ? GO_STATE_READY : GO_STATE_ACTIVE);
    SetGoType(GAMEOBJECT_TYPE_MO_TRANSPORT);
    SetGoAnimProgress(animprogress);
    SetName(goinfo->name);
    // pussywizard: no WorldRotation for MotionTransports
    SetLocalRotation(G3D::Quat());
    // pussywizard: no PathRotation for MotionTransports
    SetTransportPathRotation(0.0f, 0.0f, 0.0f, 1.0f);
    m_model = CreateModel();
    return true;
}
References Object::_Create(), _currentFrame, _nextFrame, _transportInfo, _triggeredArrivalEvent, _triggeredDepartureEvent, GameObjectTemplate::canBeStopped, GameObject::CreateModel(), GameObjectTemplate::displayId, GameObjectTemplate::entry, GAMEOBJECT_FACTION, GAMEOBJECT_TYPE_MO_TRANSPORT, GameObject::GetTemplateAddon(), GO_STATE_ACTIVE, GO_STATE_READY, Position::IsPositionValid(), TransportTemplate::keyFrames, LOG_ERROR, GameObject::m_goInfo, GameObject::m_model, GameObjectTemplate::moTransport, GameObjectTemplate::name, TransportTemplate::pathTime, Position::Relocate(), GameObject::ReplaceAllGameObjectFlags(), GameObject::SetDisplayId(), Object::SetEntry(), GameObject::SetGoAnimProgress(), GameObject::SetGoState(), GameObject::SetGoType(), GameObject::SetLocalRotation(), WorldObject::SetName(), Object::SetObjectScale(), Transport::SetPathProgress(), SetPeriod(), GameObject::SetTransportPathRotation(), Object::SetUInt32Value(), GameObjectTemplate::size, sObjectMgr, and sTransportMgr.
Referenced by TransportMgr::CreateTransport().
CreateNPCPassenger()
Creature * MotionTransport::CreateNPCPassenger (ObjectGuid::LowType guid, CreatureData const * data)
@HACK - transport models are not added to map's dynamic LoS calculations because the current GameObjectModel cannot be moved without recreating
{
    Map* map = GetMap();
    Creature* creature = new Creature();
    if (!creature->LoadCreatureFromDB(guid, map, false))
    {
        delete creature;
        return nullptr;
    }
    float x = data->posX;
    float y = data->posY;
    float z = data->posZ;
    float o = data->orientation;
    creature->SetTransport(this);
    creature->AddUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT);
    creature->m_movementInfo.transport.guid = GetGUID();
    creature->m_movementInfo.transport.pos.Relocate(x, y, z, o);
    CalculatePassengerPosition(x, y, z, &o);
    creature->Relocate(x, y, z, o);
    creature->SetHomePosition(creature->GetPositionX(), creature->GetPositionY(), creature->GetPositionZ(), creature->GetOrientation());
    creature->SetTransportHomePosition(creature->m_movementInfo.transport.pos);
    creature->AddUnitState(UNIT_STATE_IGNORE_PATHFINDING);
    if (!creature->IsPositionValid())
    {
        LOG_ERROR("entities.transport", "Creature ({}) not created. Suggested coordinates aren't valid (X: {} Y: {})",
            creature->GetGUID().ToString(), creature->GetPositionX(), creature->GetPositionY());
        delete creature;
        return nullptr;
    }
    if (!map->AddToMap(creature))
    {
        delete creature;
        return nullptr;
    }
    _staticPassengers.insert(creature);
    sScriptMgr->OnAddCreaturePassenger(this, creature);
    return creature;
}
References _staticPassengers, Map::AddToMap(), Unit::AddUnitMovementFlag(), Unit::AddUnitState(), Transport::CalculatePassengerPosition(), Object::GetGUID(), WorldObject::GetMap(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), MovementInfo::TransportInfo::guid, Position::IsPositionValid(), Creature::LoadCreatureFromDB(), LOG_ERROR, WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, CreatureData::orientation, MovementInfo::TransportInfo::pos, CreatureData::posX, CreatureData::posY, CreatureData::posZ, Position::Relocate(), Creature::SetHomePosition(), WorldObject::SetTransport(), Creature::SetTransportHomePosition(), sScriptMgr, ObjectGuid::ToString(), MovementInfo::transport, and UNIT_STATE_IGNORE_PATHFINDING.
Referenced by LoadStaticPassengers().
DelayedTeleportTransport()
void MotionTransport::DelayedTeleportTransport () private
{
    if (!_delayedTeleport)
        return;
    _delayedTeleport = false;
    uint32 newMapId = _nextFrame->Node->mapid;
    float x = _nextFrame->Node->x,
          y = _nextFrame->Node->y,
          z = _nextFrame->Node->z,
          o = _nextFrame->InitialOrientation;
    PassengerSet _passengersCopy = _passengers;
    for (PassengerSet::iterator itr = _passengersCopy.begin(); itr != _passengersCopy.end(); )
    {
        WorldObject* obj = (*itr++);
        if (_passengers.find(obj) == _passengers.end())
            continue;
        switch (obj->GetTypeId())
        {
            case TYPEID_UNIT:
                _passengers.erase(obj);
                if (!obj->ToCreature()->IsPet())
                    obj->ToCreature()->DespawnOrUnsummon();
                break;
            case TYPEID_GAMEOBJECT:
                _passengers.erase(obj);
                obj->ToGameObject()->Delete();
                break;
            case TYPEID_DYNAMICOBJECT:
                _passengers.erase(obj);
                if (Unit* caster = obj->ToDynObject()->GetCaster())
                    if (Spell* s = caster->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
                        if (obj->ToDynObject()->GetSpellId() == s->GetSpellInfo()->Id)
{
                            s->SendChannelUpdate(0);
                            s->SendInterrupted(0);
                            caster->RemoveOwnedAura(s->GetSpellInfo()->Id, caster->GetGUID());
                        }
                obj->AddObjectToRemoveList();
                break;
            case TYPEID_PLAYER:
                {
                    float destX, destY, destZ, destO;
                    obj->m_movementInfo.transport.pos.GetPosition(destX, destY, destZ, destO);
                    TransportBase::CalculatePassengerPosition(destX, destY, destZ, &destO, x, y, z, o);
                    if (!obj->ToPlayer()->TeleportTo(newMapId, destX, destY, destZ, destO, TELE_TO_NOT_LEAVE_TRANSPORT))
                        _passengers.erase(obj);
                }
                break;
            default:
                break;
        }
    }
    Map* newMap = sMapMgr->CreateBaseMap(newMapId);
    GetMap()->RemoveFromMap<MotionTransport>(this, false);
    newMap->LoadGrid(x, y); // xinef: load before adding passengers to new map
    SetMap(newMap);
    Relocate(x, y, z, o);
    GetMap()->AddToMap<MotionTransport>(this);
    LoadStaticPassengers();
}
References _delayedTeleport, _nextFrame, Transport::_passengers, WorldObject::AddObjectToRemoveList(), Map::AddToMap(), TransportBase::CalculatePassengerPosition(), CURRENT_CHANNELED_SPELL, GameObject::Delete(), Creature::DespawnOrUnsummon(), DynamicObject::GetCaster(), WorldObject::GetMap(), Position::GetPosition(), DynamicObject::GetSpellId(), Object::GetTypeId(), Unit::IsPet(), Map::LoadGrid(), LoadStaticPassengers(), WorldObject::m_movementInfo, MovementInfo::TransportInfo::pos, Position::Relocate(), Map::RemoveFromMap(), WorldObject::SetMap(), sMapMgr, TELE_TO_NOT_LEAVE_TRANSPORT, Player::TeleportTo(), Object::ToCreature(), Object::ToDynObject(), Object::ToGameObject(), Object::ToPlayer(), MovementInfo::transport, TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by DelayedUpdate().
DelayedUpdate()
void MotionTransport::DelayedUpdate (uint32 diff)
{
    if (GetKeyFrames().size() <= 1)
        return;
    DelayedTeleportTransport();
}
References DelayedTeleportTransport(), and GetKeyFrames().
Referenced by Map::DelayedUpdate().
DoEventIfAny()
void MotionTransport::DoEventIfAny (KeyFrame const & node, bool departure) private
{
    if (uint32 eventid = departure ? node.Node->departureEventID : node.Node->arrivalEventID)
    {
        //LOG_DEBUG("maps.script", "Taxi {} event {} of node {} of {} path", departure ? "departure" : "arrival", eventid, node.Node->index, GetName());
        GetMap()->ScriptsStart(sEventScripts, eventid, this, this);
        EventInform(eventid);
    }
}
References TaxiPathNodeEntry::arrivalEventID, TaxiPathNodeEntry::departureEventID, GameObject::EventInform(), WorldObject::GetMap(), KeyFrame::Node, Map::ScriptsStart(), and sEventScripts.
Referenced by Update().
EnableMovement()
void MotionTransport::EnableMovement (bool enabled)
{
    if (!GetGOInfo()->moTransport.canBeStopped)
        return;
    _pendingStop = !enabled;
}
References _pendingStop, GameObjectTemplate::canBeStopped, and GameObject::GetGOInfo().
Referenced by npc_gunship::npc_gunshipAI::JustDied(), BattlegroundIC::SetupBattleground(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), and instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update().
GetDebugInfo()
std::string MotionTransport::GetDebugInfo () const override virtual
Reimplemented from GameObject.
{
    std::stringstream sstr;
    sstr << GameObject::GetDebugInfo();
    return sstr.str();
}
References GameObject::GetDebugInfo().
GetKeyFrames()
KeyFrameVec const & MotionTransport::GetKeyFrames () const inline
{ return _transportInfo->keyFrames; }
References _transportInfo, and TransportTemplate::keyFrames.
Referenced by DelayedUpdate(), MoveToNextWaypoint(), and Update().
GetPeriod()
uint32 MotionTransport::GetPeriod () const inline
{ return GetUInt32Value(GAMEOBJECT_LEVEL); }
References GAMEOBJECT_LEVEL, and Object::GetUInt32Value().
Referenced by Update().
GetStaticPassengers()
PassengerSet const & MotionTransport::GetStaticPassengers () const inline
{ return _staticPassengers; }
References _staticPassengers.
GetTransportTemplate()
TransportTemplate const * MotionTransport::GetTransportTemplate () const inline
{ return _transportInfo; }
References _transportInfo.
IsMoving()
bool MotionTransport::IsMoving () const inline private
Helpers to know if stop frame was reached.
{ return _isMoving; }
References _isMoving.
Referenced by Update().
LoadStaticPassengers()
void MotionTransport::LoadStaticPassengers ()
{
    if (PassengersLoaded())
        return;
    SetPassengersLoaded(true);
    if (uint32 mapId = GetGOInfo()->moTransport.mapID)
    {
        CellObjectGuidsMap const& cells = sObjectMgr->GetMapObjectGuids(mapId, GetMap()->GetSpawnMode());
        CellGuidSet::const_iterator guidEnd;
        for (CellObjectGuidsMap::const_iterator cellItr = cells.begin(); cellItr != cells.end(); ++cellItr)
        {
            // Creatures on transport
            guidEnd = cellItr->second.creatures.end();
            for (CellGuidSet::const_iterator guidItr = cellItr->second.creatures.begin(); guidItr != guidEnd; ++guidItr)
                CreateNPCPassenger(*guidItr, sObjectMgr->GetCreatureData(*guidItr));
            // GameObjects on transport
            guidEnd = cellItr->second.gameobjects.end();
            for (CellGuidSet::const_iterator guidItr = cellItr->second.gameobjects.begin(); guidItr != guidEnd; ++guidItr)
                CreateGOPassenger(*guidItr, sObjectMgr->GetGameObjectData(*guidItr));
        }
    }
}
References CreateGOPassenger(), CreateNPCPassenger(), GameObject::GetGOInfo(), WorldObject::GetMap(), GameObjectTemplate::mapID, PassengersLoaded(), SetPassengersLoaded(), and sObjectMgr.
Referenced by DelayedTeleportTransport(), Update(), and UpdatePosition().
MoveToNextWaypoint()
void MotionTransport::MoveToNextWaypoint () private
{
    // Clear events flagging
    _triggeredArrivalEvent = false;
    _triggeredDepartureEvent = false;
    // Set frames
    _currentFrame = _nextFrame++;
    if (_nextFrame == GetKeyFrames().end())
        _nextFrame = GetKeyFrames().begin();
}
References _currentFrame, _nextFrame, _triggeredArrivalEvent, _triggeredDepartureEvent, and GetKeyFrames().
Referenced by Update().
PassengersLoaded()
bool MotionTransport::PassengersLoaded () const inline
{ return _passengersLoaded; }
References _passengersLoaded.
Referenced by LoadStaticPassengers().
RemovePassenger()
void MotionTransport::RemovePassenger (WorldObject * passenger, bool withAll = false) override virtual
Implements Transport.
{
    std::lock_guard<std::mutex> guard(Lock);
    if (_passengers.erase(passenger) || _staticPassengers.erase(passenger))
    {
        if (Player* plr = passenger->ToPlayer())
        {
            sScriptMgr->OnRemovePassenger(ToTransport(), plr);
            plr->SetFallInformation(GameTime::GetGameTime().count(), plr->GetPositionZ());
        }
        if (withAll)
        {
            passenger->SetTransport(nullptr);
            passenger->m_movementInfo.flags &= ~MOVEMENTFLAG_ONTRANSPORT;
            passenger->m_movementInfo.transport.guid.Clear();
            passenger->m_movementInfo.transport.pos.Relocate(0.0f, 0.0f, 0.0f, 0.0f);
            if (passenger->ToUnit())
            {
                passenger->ToUnit()->ClearUnitState(UNIT_STATE_IGNORE_PATHFINDING);
            }
        }
    }
}
References Transport::_passengers, _staticPassengers, ObjectGuid::Clear(), Unit::ClearUnitState(), MovementInfo::flags, GameTime::GetGameTime(), MovementInfo::TransportInfo::guid, Lock, WorldObject::m_movementInfo, MovementInfo::TransportInfo::pos, Position::Relocate(), WorldObject::SetTransport(), sScriptMgr, Object::ToPlayer(), GameObject::ToTransport(), Object::ToUnit(), MovementInfo::transport, and UNIT_STATE_IGNORE_PATHFINDING.
Referenced by CleanupsBeforeDelete().
SetMoving()
void MotionTransport::SetMoving (bool val) inline private
{ _isMoving = val; }
References _isMoving.
Referenced by Update().
SetPassengersLoaded()
void MotionTransport::SetPassengersLoaded (bool loaded) inline
{ _passengersLoaded = loaded; }
References _passengersLoaded.
Referenced by LoadStaticPassengers(), and UnloadStaticPassengers().
SetPeriod()
void MotionTransport::SetPeriod (uint32 period) inline
{ SetUInt32Value(GAMEOBJECT_LEVEL, period); }
References GAMEOBJECT_LEVEL, and Object::SetUInt32Value().
Referenced by CreateMoTrans().
TeleportTransport()
bool MotionTransport::TeleportTransport (uint32 newMapid, float x, float y, float z, float o) private
{
    Map const* oldMap = GetMap();
    if (oldMap->GetId() != newMapid)
    {
        _delayedTeleport = true;
        UnloadStaticPassengers();
        return true;
    }
    else
    {
        // Teleport players, they need to know it
        for (PassengerSet::iterator itr = _passengers.begin(); itr != _passengers.end(); ++itr)
        {
            if ((*itr)->IsPlayer())
            {
                float destX, destY, destZ, destO;
                (*itr)->m_movementInfo.transport.pos.GetPosition(destX, destY, destZ, destO);
                TransportBase::CalculatePassengerPosition(destX, destY, destZ, &destO, x, y, z, o);
                (*itr)->ToUnit()->NearTeleportTo(destX, destY, destZ, destO);
            }
        }
        UpdatePosition(x, y, z, o);
        return false;
    }
}
References _delayedTeleport, Transport::_passengers, TransportBase::CalculatePassengerPosition(), Map::GetId(), WorldObject::GetMap(), UnloadStaticPassengers(), and UpdatePosition().
Referenced by Update().
UnloadNonStaticPassengers()
void MotionTransport::UnloadNonStaticPassengers ()
{
    for (PassengerSet::iterator itr = _passengers.begin(); itr != _passengers.end(); )
    {
        if ((*itr)->IsPlayer())
        {
            ++itr;
            continue;
        }
        PassengerSet::iterator itr2 = itr++;
        (*itr2)->AddObjectToRemoveList();
    }
}
References Transport::_passengers.
Referenced by ResetEncounterEvent::Execute().
UnloadStaticPassengers()
void MotionTransport::UnloadStaticPassengers ()
{
    SetPassengersLoaded(false);
    while (!_staticPassengers.empty())
    {
        WorldObject* obj = *_staticPassengers.begin();
        obj->AddObjectToRemoveList();   // also removes from _staticPassengers
    }
}
References _staticPassengers, WorldObject::AddObjectToRemoveList(), and SetPassengersLoaded().
Referenced by CleanupsBeforeDelete(), TeleportTransport(), and ~MotionTransport().
Update()
void MotionTransport::Update (uint32 diff) override virtual
Reimplemented from GameObject.
{
    uint32 const positionUpdateDelay = 1;
    if (AI())
        AI()->UpdateAI(diff);
    else if (!AIM_Initialize())
        LOG_ERROR("entities.transport", "Could not initialize GameObjectAI for Transport");
    if (GetKeyFrames().size() <= 1)
        return;
    if (IsMoving() || !_pendingStop)
        SetPathProgress(GetPathProgress() + diff);
    uint32 timer = GetPathProgress() % GetPeriod();
    // Set current waypoint
    // Desired outcome: _currentFrame->DepartureTime < timer < _nextFrame->ArriveTime
    // ... arrive | ... delay ... | departure
    //      event /         event /
    for (;;)
    {
        if (timer >= _currentFrame->ArriveTime)
        {
            if (!_triggeredArrivalEvent)
            {
                DoEventIfAny(*_currentFrame, false);
                _triggeredArrivalEvent = true;
            }
            if (timer < _currentFrame->DepartureTime)
            {
                SetMoving(false);
                if (_pendingStop && GetGoState() != GO_STATE_READY)
                {
                    SetGoState(GO_STATE_READY);
                    SetPathProgress(GetPathProgress() / GetPeriod());
                    SetPathProgress(GetPathProgress() * GetPeriod());
                    SetPathProgress(GetPathProgress() + _currentFrame->ArriveTime);
                }
                break;  // its a stop frame and we are waiting
            }
        }
        if (timer >= _currentFrame->DepartureTime && !_triggeredDepartureEvent)
        {
            DoEventIfAny(*_currentFrame, true); // departure event
            _triggeredDepartureEvent = true;
        }
        // not waiting anymore
        SetMoving(true);
        // Enable movement
        if (GetGOInfo()->moTransport.canBeStopped)
            SetGoState(GO_STATE_ACTIVE);
        if (timer >= _currentFrame->DepartureTime && timer < _currentFrame->NextArriveTime)
            break;  // found current waypoint
        MoveToNextWaypoint();
        sScriptMgr->OnRelocate(this, _currentFrame->Node->index, _currentFrame->Node->mapid, _currentFrame->Node->x, _currentFrame->Node->y, _currentFrame->Node->z);
        //LOG_DEBUG("entities.transport", "Transport {} ({}) moved to node {} {} {} {} {}", GetEntry(), GetName(), _currentFrame->Node->index, _currentFrame->Node->mapid, _currentFrame->Node->x, _currentFrame->Node->y, _currentFrame->Node->z);
        // Departure event
        if (_currentFrame->IsTeleportFrame())
            if (TeleportTransport(_nextFrame->Node->mapid, _nextFrame->Node->x, _nextFrame->Node->y, _nextFrame->Node->z, _nextFrame->InitialOrientation))
                return; // Update more in new map thread
    }
    // Set position
    _positionChangeTimer.Update(diff);
    if (_positionChangeTimer.Passed())
    {
        _positionChangeTimer.Reset(positionUpdateDelay);
        if (IsMoving())
        {
            float t = CalculateSegmentPos(float(timer) * 0.001f);
            G3D::Vector3 pos, dir;
            _currentFrame->Spline->evaluate_percent(_currentFrame->Index, t, pos);
            _currentFrame->Spline->evaluate_derivative(_currentFrame->Index, t, dir);
            UpdatePosition(pos.x, pos.y, pos.z, NormalizeOrientation(std::atan2(dir.y, dir.x) + M_PI));
        }
        else
        {
            /* There are four possible scenarios that trigger loading/unloading passengers:
              1. transport moves from inactive to active grid
              2. the grid that transport is currently in becomes active
              3. transport moves from active to inactive grid
              4. the grid that transport is currently in unloads
            */
            if (_staticPassengers.empty() && GetMap()->IsGridLoaded(GetPositionX(), GetPositionY())) // 2.
                LoadStaticPassengers();
        }
    }
    sScriptMgr->OnTransportUpdate(this, diff);
}
References _currentFrame, _nextFrame, _pendingStop, _positionChangeTimer, _staticPassengers, _triggeredArrivalEvent, _triggeredDepartureEvent, GameObject::AI(), GameObject::AIM_Initialize(), CalculateSegmentPos(), GameObjectTemplate::canBeStopped, DoEventIfAny(), GameObject::GetGOInfo(), GameObject::GetGoState(), GetKeyFrames(), WorldObject::GetMap(), Transport::GetPathProgress(), GetPeriod(), Position::GetPositionX(), Position::GetPositionY(), GO_STATE_ACTIVE, GO_STATE_READY, IsMoving(), LoadStaticPassengers(), LOG_ERROR, MoveToNextWaypoint(), Position::NormalizeOrientation(), TimeTrackerSmall::Passed(), TimeTrackerSmall::Reset(), GameObject::SetGoState(), SetMoving(), Transport::SetPathProgress(), sScriptMgr, TeleportTransport(), TimeTrackerSmall::Update(), GameObjectAI::UpdateAI(), and UpdatePosition().
Referenced by Map::Update().
UpdatePassengerPositions()
void MotionTransport::UpdatePassengerPositions (PassengerSet & passengers) private
{
    for (PassengerSet::iterator itr = passengers.begin(); itr != passengers.end(); ++itr)
    {
        WorldObject* passenger = *itr;
        // transport teleported but passenger not yet (can happen for players)
        if (passenger->GetMap() != GetMap())
            continue;
        // if passenger is on vehicle we have to assume the vehicle is also on transport and its the vehicle that will be updating its passengers
        if (Unit* unit = passenger->ToUnit())
            if (unit->GetVehicle())
                continue;
        // Do not use Unit::UpdatePosition here, we don't want to remove auras as if regular movement occurred
        float x, y, z, o;
        passenger->m_movementInfo.transport.pos.GetPosition(x, y, z, o);
        CalculatePassengerPosition(x, y, z, &o);
        // check if position is valid
        if (!Acore::IsValidMapCoord(x, y, z))
            continue;
        switch (passenger->GetTypeId())
        {
            case TYPEID_UNIT:
                {
                    Creature* creature = passenger->ToCreature();
                    GetMap()->CreatureRelocation(creature, x, y, z, o);
                    creature->GetTransportHomePosition(x, y, z, o);
                    CalculatePassengerPosition(x, y, z, &o);
                    creature->SetHomePosition(x, y, z, o);
                }
                break;
            case TYPEID_PLAYER:
                if (passenger->IsInWorld())
                    GetMap()->PlayerRelocation(passenger->ToPlayer(), x, y, z, o);
                break;
            case TYPEID_GAMEOBJECT:
                GetMap()->GameObjectRelocation(passenger->ToGameObject(), x, y, z, o);
                break;
            case TYPEID_DYNAMICOBJECT:
                GetMap()->DynamicObjectRelocation(passenger->ToDynObject(), x, y, z, o);
                break;
            default:
                break;
        }
    }
}
References Transport::CalculatePassengerPosition(), Map::CreatureRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), WorldObject::GetMap(), Position::GetPosition(), Creature::GetTransportHomePosition(), Object::GetTypeId(), Object::IsInWorld(), Acore::IsValidMapCoord(), WorldObject::m_movementInfo, Map::PlayerRelocation(), MovementInfo::TransportInfo::pos, Creature::SetHomePosition(), Object::ToCreature(), Object::ToDynObject(), Object::ToGameObject(), Object::ToPlayer(), Object::ToUnit(), MovementInfo::transport, TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by UpdatePosition().
UpdatePosition()
void MotionTransport::UpdatePosition (float x, float y, float z, float o)
{
    if (!GetMap()->IsGridLoaded(x, y)) // pussywizard: should not happen, but just in case
        GetMap()->LoadGrid(x, y);
    Relocate(x, y, z, o);
    UpdateModelPosition();
    UpdatePassengerPositions(_passengers);
    if (_staticPassengers.empty())
        LoadStaticPassengers();
    else
        UpdatePassengerPositions(_staticPassengers);
}
References Transport::_passengers, _staticPassengers, WorldObject::GetMap(), Map::LoadGrid(), LoadStaticPassengers(), Position::Relocate(), GameObject::UpdateModelPosition(), and UpdatePassengerPositions().
Referenced by TeleportTransport(), and Update().
Friends And Related Function Documentation
TransportMgr::CreateTransport
MotionTransport * TransportMgr::CreateTransport (uint32 , ObjectGuid::LowType , Map *) friend
Member Data Documentation
_currentFrame
KeyFrameVec::const_iterator MotionTransport::_currentFrame private
Referenced by CalculateSegmentPos(), CreateMoTrans(), MoveToNextWaypoint(), and Update().
_delayedTeleport
bool MotionTransport::_delayedTeleport private
Referenced by DelayedTeleportTransport(), and TeleportTransport().
_isMoving
bool MotionTransport::_isMoving private
Referenced by IsMoving(), and SetMoving().
_nextFrame
KeyFrameVec::const_iterator MotionTransport::_nextFrame private
Referenced by CreateMoTrans(), DelayedTeleportTransport(), MoveToNextWaypoint(), and Update().
_passengersLoaded
bool MotionTransport::_passengersLoaded private
Referenced by PassengersLoaded(), and SetPassengersLoaded().
_pendingStop
bool MotionTransport::_pendingStop private
Referenced by EnableMovement(), and Update().
_positionChangeTimer
TimeTrackerSmall MotionTransport::_positionChangeTimer private
Referenced by Update().
_staticPassengers
PassengerSet MotionTransport::_staticPassengers private
Referenced by CreateGOPassenger(), CreateNPCPassenger(), GetStaticPassengers(), RemovePassenger(), UnloadStaticPassengers(), Update(), and UpdatePosition().
_transportInfo
TransportTemplate const* MotionTransport::_transportInfo private
Referenced by CalculateSegmentPos(), CreateMoTrans(), GetKeyFrames(), and GetTransportTemplate().
_triggeredArrivalEvent
bool MotionTransport::_triggeredArrivalEvent private
These are needed to properly control events triggering only once for each frame.
Referenced by CreateMoTrans(), MoveToNextWaypoint(), and Update().
_triggeredDepartureEvent
bool MotionTransport::_triggeredDepartureEvent private
Referenced by CreateMoTrans(), MoveToNextWaypoint(), and Update().
Lock
std::mutex MotionTransport::Lock mutable private
Referenced by AddPassenger(), and RemovePassenger().