AzerothCore: npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI Struct Reference
npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI Struct Reference
Public Member Functions
npc_tirions_gambit_tirionAI (Creature *creature)
void Reset () override
void SetData (uint32 type, uint32 data) override
void DoAction (int32 param) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void WaypointReached (uint32 pointId) override
void DoSummonAction (uint32 entry, uint8 id, int32 param=0)
void UpdateEscortAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_tirions_gambit_tirionAI()
npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::npc_tirions_gambit_tirionAI (Creature * creature) inline
                                                        : npc_escortAI(creature), summons(me)
        {
        }
Member Function Documentation
DoAction()
void npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_START_EVENT)
            {
                me->setActive(true);
                Talk(0);
                events.Reset();
                summons.DespawnAll();
                Start(false, false);
                int8 i = -1;
                std::list<Creature*> cList;
                GetCreatureListWithEntryInGrid(cList, me, NPC_DISGUISED_CRUSADER, 15.0f);
                for (std::list<Creature*>::const_iterator itr = cList.begin(); itr != cList.end(); ++itr, ++i)
                {
                    (*itr)->SetWalk(true);
                    (*itr)->GetMotionMaster()->MoveFollow(me, 1.0f, Position::NormalizeOrientation(M_PI * i / 2.0f));
                    summons.Summon(*itr);
                }
            }
        }
References ACTION_START_EVENT, SummonList::DespawnAll(), GetCreatureListWithEntryInGrid(), ScriptedAI::me, Position::NormalizeOrientation(), NPC_DISGUISED_CRUSADER, WorldObject::setActive(), npc_escortAI::Start(), SummonList::Summon(), and summons.
DoSummonAction()
void npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoSummonAction (uint32 entry, uint8 id, int32 param = 0) inline
        {
            for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                    if (summon->GetEntry() == entry)
                    {
                        switch (id)
{
                            case ACTION_SUMMON_MOVE_STRAIGHT:
                                summon->GetMotionMaster()->MovePoint(1, summon->GetPositionX() - param, summon->GetPositionY() + param * 2 + 3, summon->GetPositionZ());
                                break;
                            case ACTION_SUMMON_EMOTE:
                                summon->SetUInt32Value(UNIT_NPC_EMOTESTATE, param);
                                break;
                            case ACTION_SUMMON_DESPAWN:
                                summon->DespawnOrUnsummon(param);
                                break;
                            case ACTION_SUMMON_ORIENTATION:
                                summon->SetFacingTo(param / 100.0f);
                                break;
                            case ACTION_SUMMON_TALK:
                                summon->AI()->Talk(param);
                                break;
                            case ACTION_SUMMON_STAND_STATE:
                                summon->SetStandState(param);
                                break;
                        }
                    }
        }
References ACTION_SUMMON_DESPAWN, ACTION_SUMMON_EMOTE, ACTION_SUMMON_MOVE_STRAIGHT, ACTION_SUMMON_ORIENTATION, ACTION_SUMMON_STAND_STATE, ACTION_SUMMON_TALK, SummonList::begin(), SummonList::end(), ObjectAccessor::GetCreature(), ScriptedAI::me, summons, and UNIT_NPC_EMOTESTATE.
Referenced by UpdateEscortAI().
JustSummoned()
void npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(summon);
            if (summon->GetEntry() == NPC_CHOSEN_ZEALOT || summon->GetEntry() == NPC_TIRION_LICH_KING)
                summon->SetWalk(true);
            else if (summon->GetEntry() != NPC_INVOKER_BASALEPH)
            {
                summon->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                summon->SetImmuneToAll(true);
                summon->GetMotionMaster()->MovePoint(4, 6135.97f, 2753.84f, 573.92f);
            }
        }
References EMOTE_STATE_READY2H, Object::GetEntry(), Unit::GetMotionMaster(), MotionMaster::MovePoint(), NPC_CHOSEN_ZEALOT, NPC_INVOKER_BASALEPH, NPC_TIRION_LICH_KING, Unit::SetImmuneToAll(), Unit::SetUInt32Value(), Creature::SetWalk(), SummonList::Summon(), summons, and UNIT_NPC_EMOTESTATE.
Reset()
void npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            me->setActive(false);
            me->SetStandState(UNIT_STAND_STATE_STAND);
        }
References ScriptedAI::me, WorldObject::setActive(), Unit::SetStandState(), and UNIT_STAND_STATE_STAND.
SetData()
void npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
        {
            if (type == 1 && data == 1)
                events.ScheduleEvent(EVENT_SCENE_0 + 30, 10s);
        }
References EVENT_SCENE_0.
SummonedCreatureDespawn()
void npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Despawn(summon);
        }
References SummonList::Despawn(), and summons.
UpdateEscortAI()
void npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_START_SCENE:
                    Talk(2);
                    DoSummonAction(NPC_DISGUISED_CRUSADER, ACTION_SUMMON_ORIENTATION, 200);
                    me->SummonCreature(NPC_CHOSEN_ZEALOT, 6160.74f, 2695.90f, 573.92f, 2.04f, TEMPSUMMON_TIMED_DESPAWN, 5 * MINUTE * IN_MILLISECONDS);
                    me->SummonCreature(NPC_CHOSEN_ZEALOT, 6164.98f, 2697.90f, 573.92f, 2.04f, TEMPSUMMON_TIMED_DESPAWN, 5 * MINUTE * IN_MILLISECONDS);
                    me->SummonCreature(NPC_CHOSEN_ZEALOT, 6161.26f, 2700.05f, 573.92f, 2.04f, TEMPSUMMON_TIMED_DESPAWN, 5 * MINUTE * IN_MILLISECONDS);
                    DoSummonAction(NPC_CHOSEN_ZEALOT, ACTION_SUMMON_MOVE_STRAIGHT, 27);
                    events.ScheduleEvent(EVENT_SCENE_0, 30s);
                    break;
                case EVENT_SCENE_0:
                    DoSummonAction(NPC_CHOSEN_ZEALOT, ACTION_SUMMON_STAND_STATE, UNIT_STAND_STATE_KNEEL);
                    me->SummonGameObject(GO_FROZEN_HEART, 6132.38f, 2760.76f, 574.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 180);
                    events.ScheduleEvent(EVENT_SCENE_0 + 1, 10s);
                    break;
                case EVENT_SCENE_0+1:
                    DoSummonAction(NPC_CHOSEN_ZEALOT, ACTION_SUMMON_STAND_STATE, UNIT_STAND_STATE_STAND);
                    events.ScheduleEvent(EVENT_SCENE_0 + 2, 2s);
                    break;
                case EVENT_SCENE_0+2:
                    DoSummonAction(NPC_CHOSEN_ZEALOT, ACTION_SUMMON_MOVE_STRAIGHT, -27);
                    DoSummonAction(NPC_CHOSEN_ZEALOT, ACTION_SUMMON_DESPAWN, 20000);
                    events.ScheduleEvent(EVENT_SCENE_0 + 3, 2s);
                    break;
                case EVENT_SCENE_0+3:
                    Talk(3);
                    if (Creature* cr = me->SummonCreature(NPC_TIRION_LICH_KING, 6161.26f, 2700.05f, 573.92f, 2.04f, TEMPSUMMON_TIMED_DESPAWN, 5 * MINUTE * IN_MILLISECONDS))
                        cr->GetMotionMaster()->MovePoint(2, 6131.93f, 2756.84f, 573.92f);
                    events.ScheduleEvent(EVENT_SCENE_0 + 4, 4s);
                    break;
                case EVENT_SCENE_0+4:
                    Talk(4);
                    me->SetFacingTo(4.42f);
                    events.ScheduleEvent(EVENT_SCENE_0 + 5, 25s);
                    break;
                case EVENT_SCENE_0+5:
                    DoSummonAction(NPC_TIRION_LICH_KING, ACTION_SUMMON_ORIENTATION, 11);
                    events.ScheduleEvent(EVENT_SCENE_0 + 6, 4s);
                    break;
                case EVENT_SCENE_0+6:
                    DoSummonAction(NPC_TIRION_LICH_KING, ACTION_SUMMON_TALK, 0);
                    me->LoadEquipment(2, true);
                    SetEscortPaused(false);
                    events.ScheduleEvent(EVENT_SCENE_0 + 7, 6s);
                    break;
                case EVENT_SCENE_0+7:
                    DoSummonAction(NPC_TIRION_LICH_KING, ACTION_SUMMON_TALK, 1);
                    break;
                case EVENT_SCENE_0+8:
                    Talk(5);
                    events.ScheduleEvent(EVENT_SCENE_0 + 9, 5s);
                    break;
                case EVENT_SCENE_0+9:
                    DoSummonAction(NPC_TIRION_LICH_KING, ACTION_SUMMON_TALK, 2);
                    events.ScheduleEvent(EVENT_SCENE_0 + 10, 11s);
                    break;
                case EVENT_SCENE_0+10:
                    Talk(6);
                    events.ScheduleEvent(EVENT_SCENE_0 + 11, 6s);
                    break;
                case EVENT_SCENE_0+11:
                    DoSummonAction(NPC_TIRION_LICH_KING, ACTION_SUMMON_TALK, 3);
                    events.ScheduleEvent(EVENT_SCENE_0 + 12, 7s);
                    break;
                case EVENT_SCENE_0+12:
                    DoSummonAction(NPC_TIRION_LICH_KING, ACTION_SUMMON_TALK, 4);
                    events.ScheduleEvent(EVENT_SCENE_0 + 13, 5s);
                    break;
                case EVENT_SCENE_0+13:
                    Talk(7);
                    events.ScheduleEvent(EVENT_SCENE_0 + 14, 14s);
                    break;
                case EVENT_SCENE_0+14:
                    Talk(8);
                    events.ScheduleEvent(EVENT_SCENE_0 + 15, 3s);
                    break;
                case EVENT_SCENE_0+15:
                    {
                        me->CastSpell(me, SPELL_TIRION_SMASH_HEART, true);
                        events.ScheduleEvent(EVENT_SCENE_0 + 16, 1200ms);
                        uint8 i = 0;
                        for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr, ++i)
                            if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                                if (summon->GetEntry() == NPC_DISGUISED_CRUSADER)
{
                                    summon->SetWalk(false);
                                    summon->GetMotionMaster()->MovePoint(2, 6132.38f + 4 * cos(2 * M_PI * (i / 3.0)), 2760.76f + 4 * std::sin(2 * M_PI * (i / 3.0)), me->GetPositionZ());
                                }
                        break;
                    }
                case EVENT_SCENE_0+16:
                    me->CastSpell(me, SPELL_HEART_EXPLOSION, true);
                    me->CastSpell(me, SPELL_HEART_EXPLOSION_EFF, true);
                    me->SetStandState(UNIT_STAND_STATE_DEAD);
                    DoSummonAction(NPC_TIRION_LICH_KING, ACTION_SUMMON_TALK, 5);
                    if (GameObject* go = me->FindNearestGameObject(GO_FROZEN_HEART, 20.0f))
                        go->Delete();
                    events.ScheduleEvent(EVENT_SCENE_0 + 17, 2s);
                    break;
                case EVENT_SCENE_0+17:
                    DoSummonAction(NPC_TIRION_LICH_KING, ACTION_SUMMON_STAND_STATE, UNIT_STAND_STATE_KNEEL);
                    events.ScheduleEvent(EVENT_SCENE_0 + 170, 3s);
                    break;
                case EVENT_SCENE_0+170:
                    DoSummonAction(NPC_DISGUISED_CRUSADER, ACTION_SUMMON_ORIENTATION, 500);
                    DoSummonAction(NPC_DISGUISED_CRUSADER, ACTION_SUMMON_EMOTE, EMOTE_STATE_READY2H);
                    if (Creature* cr = me->FindNearestCreature(NPC_DISGUISED_CRUSADER, 10.0f))
                        cr->AI()->Talk(0);
                    events.ScheduleEvent(EVENT_SCENE_0 + 18, 1s);
                    break;
                case EVENT_SCENE_0+18:
                    {
                        DoSummonAction(NPC_TIRION_LICH_KING, ACTION_SUMMON_TALK, 6);
                        std::list<Creature*> zealotList;
                        Position pos1 = {6160.0f, 2765.0f, 573.92f, 0.0f};
                        Position pos2 = {6115.0f, 2742.0f, 573.92f, 0.0f};
                        me->GetCreaturesWithEntryInRange(zealotList, 100.0f, NPC_CHOSEN_ZEALOT);
                        for (std::list<Creature*>::const_iterator itr = zealotList.begin(); itr != zealotList.end(); ++itr)
{
                            (*itr)->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY_UNARMED);
                            if ((*itr)->GetPositionX() > 6150.0f)
{
                                Position tpos = pos1;
                                (*itr)->MovePosition(tpos, frand(1.0f, 14.0f), frand(3.14f, 4.14f));
                                (*itr)->GetMotionMaster()->MovePoint(3, tpos.GetPositionX(), tpos.GetPositionY(), tpos.GetPositionZ());
                            }
                            else
{
                                Position tpos = pos2;
                                (*itr)->MovePosition(tpos, frand(1.0f, 14.0f), frand(0.0f, 1.0f));
                                (*itr)->GetMotionMaster()->MovePoint(3, tpos.GetPositionX(), tpos.GetPositionY(), tpos.GetPositionZ());
                            }
                        }
                        events.ScheduleEvent(EVENT_SCENE_0 + 19, 3s);
                        break;
                    }
                case EVENT_SCENE_0+19:
                    me->SummonCreatureGroup(1);
                    events.ScheduleEvent(EVENT_SCENE_0 + 20, 3700ms);
                    break;
                case EVENT_SCENE_0+20:
                    {
                        for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                            if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
{
                                summon->SetImmuneToAll(false);
                                if (summon->GetEntry() >= NPC_TIRION_EBON_KNIGHT && summon->GetEntry() <= NPC_TIRION_MOGRAINE)
{
                                    if (summon->GetEntry() == NPC_TIRION_MOGRAINE)
                                        summon->SetHomePosition(6135.97f, 2753.84f, 573.92f, 3.70f);
                                    else
                                        summon->SetHomePosition(6138.36f + frand(-2.0f, 2.0f), 2749.25f + frand(-2.0f, 2.0f), 573.92f, 2.03f);
                                }
                            }
                        DoSummonAction(NPC_TIRION_THASSARIAN, ACTION_SUMMON_TALK, 0);
                        std::list<Creature*> zealotList;
                        me->GetCreaturesWithEntryInRange(zealotList, 100.0f, NPC_CHOSEN_ZEALOT);
                        Unit* target = me->FindNearestCreature(NPC_TIRION_MOGRAINE, 100.0f);
                        for (std::list<Creature*>::const_iterator itr = zealotList.begin(); itr != zealotList.end(); ++itr)
{
                            if (!target)
                                target = (*itr)->SelectNearestTarget(40.0f);
                            if (target)
                                (*itr)->AI()->AttackStart(target);
                        }
                        break;
                    }
                case EVENT_SCENE_0+30:
                    for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                        if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                            if (summon->GetEntry() >= NPC_TIRION_EBON_KNIGHT && summon->GetEntry() <= NPC_TIRION_MOGRAINE)
{
                                if (summon->GetEntry() == NPC_TIRION_MOGRAINE)
                                    summon->GetMotionMaster()->MovePoint(6, 6135.97f, 2753.84f, 573.92f);
                                else
                                    summon->GetMotionMaster()->MovePoint(6, 6138.36f + frand(-2.0f, 2.0f), 2749.25f + frand(-2.0f, 2.0f), 573.92f);
                            }
                    events.ScheduleEvent(EVENT_SCENE_0 + 310, 4s);
                    break;
                case EVENT_SCENE_0+310:
                    DoSummonAction(NPC_TIRION_MOGRAINE, ACTION_SUMMON_TALK, 0);
                    DoSummonAction(NPC_TIRION_LICH_KING, ACTION_SUMMON_STAND_STATE, UNIT_STAND_STATE_STAND);
                    me->SummonGameObject(GO_ESCAPE_PORTAL, 6133.83f, 2757.24f, 573.914f, 1.97f, 0.0f, 0.0f, 0.0f, 0.0f, 60);
                    me->CastSpell(me, SPELL_TIRIONS_GAMBIT_CREDIT, true);
                    events.ScheduleEvent(EVENT_SCENE_0 + 31, 6s);
                    DoSummonAction(NPC_DISGUISED_CRUSADER, ACTION_SUMMON_EMOTE, EMOTE_ONESHOT_NONE);
                    break;
                case EVENT_SCENE_0+31:
                    DoSummonAction(NPC_TIRION_THASSARIAN, ACTION_SUMMON_TALK, 1);
                    events.ScheduleEvent(EVENT_SCENE_0 + 32, 7s);
                    break;
                case EVENT_SCENE_0+32:
                    DoSummonAction(NPC_TIRION_MOGRAINE, ACTION_SUMMON_TALK, 1);
                    events.ScheduleEvent(EVENT_SCENE_0 + 33, 7s);
                    break;
                case EVENT_SCENE_0+33:
                    for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                        if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
{
                            if (summon->GetEntry() == NPC_TIRION_LICH_KING)
                                summon->CastSpell(summon, SPELL_LICH_KINGS_FURY, false);
                            summon->DespawnOrUnsummon(summon->GetEntry() == NPC_TIRION_LICH_KING ? 10000 : 4000);
                        }
                    me->DespawnOrUnsummon(10000);
                    break;
            }
        }
References ACTION_SUMMON_DESPAWN, ACTION_SUMMON_EMOTE, ACTION_SUMMON_MOVE_STRAIGHT, ACTION_SUMMON_ORIENTATION, ACTION_SUMMON_STAND_STATE, ACTION_SUMMON_TALK, SummonList::begin(), Unit::CastSpell(), Creature::DespawnOrUnsummon(), DoSummonAction(), EMOTE_ONESHOT_NONE, EMOTE_STATE_READY2H, EMOTE_STATE_READY_UNARMED, SummonList::end(), EVENT_SCENE_0, EVENT_START_SCENE, WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), frand(), ObjectAccessor::GetCreature(), WorldObject::GetCreaturesWithEntryInRange(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_ESCAPE_PORTAL, GO_FROZEN_HEART, IN_MILLISECONDS, Creature::LoadEquipment(), ScriptedAI::me, MINUTE, NPC_CHOSEN_ZEALOT, NPC_DISGUISED_CRUSADER, NPC_TIRION_EBON_KNIGHT, NPC_TIRION_LICH_KING, NPC_TIRION_MOGRAINE, NPC_TIRION_THASSARIAN, npc_escortAI::SetEscortPaused(), Unit::SetFacingTo(), Unit::SetStandState(), SPELL_HEART_EXPLOSION, SPELL_HEART_EXPLOSION_EFF, SPELL_LICH_KINGS_FURY, SPELL_TIRION_SMASH_HEART, SPELL_TIRIONS_GAMBIT_CREDIT, WorldObject::SummonCreature(), WorldObject::SummonCreatureGroup(), WorldObject::SummonGameObject(), summons, TEMPSUMMON_TIMED_DESPAWN, UNIT_NPC_EMOTESTATE, UNIT_STAND_STATE_DEAD, UNIT_STAND_STATE_KNEEL, and UNIT_STAND_STATE_STAND.
WaypointReached()
void npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::WaypointReached (uint32 pointId) inline override virtual
Implements npc_escortAI.
        {
            switch (pointId)
            {
                case 6:
                    me->SummonCreature(NPC_INVOKER_BASALEPH, 6130.26f, 2764.83f, 573.92f, 5.19f, TEMPSUMMON_TIMED_DESPAWN, 10 * MINUTE * IN_MILLISECONDS);
                    Talk(1);
                    break;
                case 15:
                    {
                        uint8 i = 1;
                        for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr, ++i)
                            if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                                if (summon->GetEntry() == NPC_DISGUISED_CRUSADER)
{
                                    summon->GetMotionMaster()->Clear(false);
                                    summon->GetMotionMaster()->MovePoint(1, 6165.3f + 3 * i, 2759.85f + 1.5f * i, 573.914f);
                                }
                        break;
                    }
                case 17:
                    SetEscortPaused(true);
                    events.ScheduleEvent(EVENT_START_SCENE, 7s);
                    break;
                case 19:
                    SetEscortPaused(true);
                    events.ScheduleEvent(EVENT_SCENE_0 + 8, 5s);
                    break;
            }
        }
References SummonList::begin(), SummonList::end(), EVENT_SCENE_0, EVENT_START_SCENE, ObjectAccessor::GetCreature(), IN_MILLISECONDS, ScriptedAI::me, MINUTE, NPC_DISGUISED_CRUSADER, NPC_INVOKER_BASALEPH, npc_escortAI::SetEscortPaused(), WorldObject::SummonCreature(), summons, and TEMPSUMMON_TIMED_DESPAWN.
Member Data Documentation
events
EventMap npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::events
summons
SummonList npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::summons
Referenced by DoAction(), DoSummonAction(), JustSummoned(), SummonedCreatureDespawn(), UpdateEscortAI(), and WaypointReached().