AzerothCore: go_fel_crystalforge Class Reference
go_fel_crystalforge Class Reference
Public Member Functions
go_fel_crystalforge ()
bool OnGossipHello (Player *player, GameObject *go) override
bool OnGossipSelect (Player *player, GameObject *go, uint32, uint32 action) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, GameObject *)
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnModifyHealth (GameObject *, Unit *, int32 &, SpellInfo const *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
go_fel_crystalforge()
go_fel_crystalforge::go_fel_crystalforge () inline
: GameObjectScript("go_fel_crystalforge") { }
Member Function Documentation
OnGossipHello()
bool go_fel_crystalforge::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
    {
        if (go->GetGoType() == GAMEOBJECT_TYPE_QUESTGIVER) /* != GAMEOBJECT_TYPE_QUESTGIVER) */
            player->PrepareQuestMenu(go->GetGUID()); /* return true*/
        AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_FEL_CRYSTALFORGE_ITEM_1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
        AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_FEL_CRYSTALFORGE_ITEM_5, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
        SendGossipMenuFor(player, GOSSIP_FEL_CRYSTALFORGE_TEXT, go->GetGUID());
        return true;
    }
References AddGossipItemFor(), GAMEOBJECT_TYPE_QUESTGIVER, GameObject::GetGoType(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_FEL_CRYSTALFORGE_ITEM_1, GOSSIP_FEL_CRYSTALFORGE_ITEM_5, GOSSIP_FEL_CRYSTALFORGE_TEXT, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Player::PrepareQuestMenu(), and SendGossipMenuFor().
OnGossipSelect()
bool go_fel_crystalforge::OnGossipSelect (Player * player, GameObject * go, uint32 , uint32 action) inline override virtual
Reimplemented from GameObjectScript.
    {
        ClearGossipMenuFor(player);
        switch (action)
        {
            case GOSSIP_ACTION_INFO_DEF:
                player->CastSpell(player, SPELL_CREATE_1_FLASK_OF_BEAST, false);
                AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_FEL_CRYSTALFORGE_ITEM_RETURN, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                SendGossipMenuFor(player, GOSSIP_FEL_CRYSTALFORGE_ITEM_TEXT_RETURN, go->GetGUID());
                break;
            case GOSSIP_ACTION_INFO_DEF + 1:
                player->CastSpell(player, SPELL_CREATE_5_FLASK_OF_BEAST, false);
                AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_FEL_CRYSTALFORGE_ITEM_RETURN, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                SendGossipMenuFor(player, GOSSIP_FEL_CRYSTALFORGE_ITEM_TEXT_RETURN, go->GetGUID());
                break;
            case GOSSIP_ACTION_INFO_DEF + 2:
                AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_FEL_CRYSTALFORGE_ITEM_1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
                AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_FEL_CRYSTALFORGE_ITEM_5, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                SendGossipMenuFor(player, GOSSIP_FEL_CRYSTALFORGE_TEXT, go->GetGUID());
                break;
        }
        return true;
    }
References AddGossipItemFor(), Unit::CastSpell(), ClearGossipMenuFor(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_FEL_CRYSTALFORGE_ITEM_1, GOSSIP_FEL_CRYSTALFORGE_ITEM_5, GOSSIP_FEL_CRYSTALFORGE_ITEM_RETURN, GOSSIP_FEL_CRYSTALFORGE_ITEM_TEXT_RETURN, GOSSIP_FEL_CRYSTALFORGE_TEXT, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, SendGossipMenuFor(), SPELL_CREATE_1_FLASK_OF_BEAST, and SPELL_CREATE_5_FLASK_OF_BEAST.