AzerothCore: achievement_portal_jockey Class Reference
achievement_portal_jockey Class Reference
Public Member Functions
achievement_portal_jockey ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
virtual bool OnCheck (Player *, Unit *, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_portal_jockey()
achievement_portal_jockey::achievement_portal_jockey () inline
: AchievementCriteriaScript("achievement_portal_jockey") { }
Member Function Documentation
OnCheck()
bool achievement_portal_jockey::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
    {
        return target && target->GetEntry() == NPC_VALITHRIA_DREAMWALKER && !target->GetAI()->GetData(MISSED_PORTALS);
    }
References Unit::GetAI(), UnitAI::GetData(), Object::GetEntry(), MISSED_PORTALS, and NPC_VALITHRIA_DREAMWALKER.