AzerothCore: BossAI Class Reference
BossAI Class Reference
#include "ScriptedCreature.h"
Public Member Functions
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Protected Member Functions
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
bool _ProccessHealthCheckEvent (uint8 healthPct, uint32 damage, std::function< void()> exec) const
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes
EventMap events
SummonList summons
TaskScheduler scheduler
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Private Attributes
uint32 const _bossId
std::list< HealthCheckEventData > _healthCheckEvents
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Detailed Description
Constructor & Destructor Documentation
BossAI()
BossAI::BossAI (Creature * creature, uint32 bossId)
                                                : ScriptedAI(creature),
    instance(creature->GetInstanceScript()),
    summons(creature),
    _bossId(bossId)
{
    if (instance)
        SetBoundary(instance->GetBossBoundary(bossId));
}
References InstanceScript::GetBossBoundary(), instance, and CreatureAI::SetBoundary().
~BossAI()
BossAI::~BossAI () inline override
{}
Member Function Documentation
_JustDied()
void BossAI::_JustDied () protected
{
    events.Reset();
    scheduler.CancelAll();
    summons.DespawnAll();
    _healthCheckEvents.clear();
    if (instance)
    {
        instance->SetBossState(_bossId, DONE);
        instance->SaveToDB();
    }
}
References _bossId, _healthCheckEvents, TaskScheduler::CancelAll(), SummonList::DespawnAll(), DONE, instance, InstanceScript::SaveToDB(), scheduler, InstanceScript::SetBossState(), and summons.
Referenced by boss_high_king_maulgar::DoAction(), JustDied(), boss_halycon::boss_halyconAI::JustDied(), boss_highlord_omokk::boss_highlordomokkAI::JustDied(), boss_mor_grayhoof::JustDied(), boss_quartermaster_zigris::JustDied(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::JustDied(), boss_broodlord::boss_broodlordAI::JustDied(), boss_nefarian::JustDied(), boss_razorgore::boss_razorgoreAI::JustDied(), boss_ragnaros::boss_ragnarosAI::JustDied(), boss_malchezaar::JustDied(), boss_apothecary_hummel::boss_apothecary_hummelAI::JustDied(), boss_akilzon::boss_akilzonAI::JustDied(), boss_arlokk::boss_arlokkAI::JustDied(), boss_gahzranka::boss_gahzrankaAI::JustDied(), boss_hakkar::boss_hakkarAI::JustDied(), boss_jeklik::JustDied(), boss_thekal::boss_thekalAI::JustDied(), boss_venoxis::boss_venoxisAI::JustDied(), boss_lieutenant_drake::JustDied(), boss_aeonus::JustDied(), boss_chrono_lord_deja::JustDied(), boss_temporus::JustDied(), boss_isalien::JustDied(), boss_moam::JustDied(), boss_rajaxx::JustDied(), boss_sartura::JustDied(), boss_skeram::JustDied(), boss_amanitar::JustDied(), boss_elder_nadox::JustDied(), boss_volazj::JustDied(), boss_jedoga_shadowseeker::JustDied(), boss_taldaram::JustDied(), boss_sartharion::boss_sartharionAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_festergut::boss_festergutAI::JustDied(), boss_lord_marrowgar::JustDied(), boss_professor_putricide::boss_professor_putricideAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), boss_sindragosa::boss_sindragosaAI::JustDied(), boss_the_lich_king::boss_the_lich_kingAI::JustDied(), boss_sister_svalna::boss_sister_svalnaAI::JustDied(), boss_exarch_maladaar::JustDied(), boss_nexusprince_shaffar::JustDied(), boss_tavarok::JustDied(), boss_darkweaver_syth::JustDied(), boss_talon_king_ikiss::JustDied(), boss_ambassador_hellmaw::JustDied(), boss_blackheart_the_inciter::JustDied(), boss_grandmaster_vorpil::JustDied(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustDied(), boss_mennu_the_betrayer::JustDied(), boss_hydromancer_thespia::JustDied(), boss_mekgineer_steamrigger::JustDied(), boss_warlord_kalithresh::JustDied(), boss_swamplord_muselek::JustDied(), boss_gruul::JustDied(), boss_high_king_maulgar::JustDied(), boss_kelidan_the_breaker::JustDied(), boss_the_maker::JustDied(), boss_omor_the_unscarred::JustDied(), boss_watchkeeper_gargolmar::JustDied(), boss_grand_warlock_nethekurse::JustDied(), boss_dalliah_the_doomsayer::JustDied(), boss_harbinger_skyriss::JustDied(), boss_zereketh_the_unbound::JustDied(), boss_commander_sarannis::JustDied(), boss_high_botanist_freywinn::JustDied(), boss_thorngrin_the_tender::JustDied(), boss_warp_splinter::JustDied(), boss_gatewatcher_gyrokill::JustDied(), boss_gatewatcher_iron_hand::JustDied(), boss_mechano_lord_capacitus::JustDied(), boss_nethermancer_sepethrea::JustDied(), boss_pathaleon_the_calculator::JustDied(), boss_jarien::JustDied(), boss_sothos::JustDied(), boss_epoch_hunter::JustDied(), and boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied().
_JustEngagedWith()
void BossAI::_JustEngagedWith () protected
{
    me->SetCombatPulseDelay(5);
    me->setActive(true);
    DoZoneInCombat();
    ScheduleTasks();
    if (instance)
    {
        // bosses do not respawn, check only on enter combat
        if (!instance->CheckRequiredBosses(_bossId))
        {
            EnterEvadeMode();
            return;
        }
        instance->SetBossState(_bossId, IN_PROGRESS);
    }
}
References _bossId, InstanceScript::CheckRequiredBosses(), CreatureAI::DoZoneInCombat(), CreatureAI::EnterEvadeMode(), IN_PROGRESS, instance, ScriptedAI::me, ScheduleTasks(), WorldObject::setActive(), InstanceScript::SetBossState(), and Creature::SetCombatPulseDelay().
Referenced by boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent(), JustEngagedWith(), boss_anubshiah::boss_anubshiahAI::JustEngagedWith(), boss_eviscerator::boss_evisceratorAI::JustEngagedWith(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::JustEngagedWith(), boss_grizzle::boss_grizzleAI::JustEngagedWith(), boss_hedrum::boss_hedrumAI::JustEngagedWith(), boss_magmus::boss_magmusAI::JustEngagedWith(), boss_moira_bronzebeardAI::JustEngagedWith(), boss_high_priestess_thaurissanAI::JustEngagedWith(), boss_okthor::boss_okthorAI::JustEngagedWith(), boss_drakkisath::boss_drakkisathAI::JustEngagedWith(), boss_gyth::boss_gythAI::JustEngagedWith(), boss_halycon::boss_halyconAI::JustEngagedWith(), boss_highlord_omokk::boss_highlordomokkAI::JustEngagedWith(), boss_mor_grayhoof::JustEngagedWith(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::JustEngagedWith(), boss_rend_blackhand::boss_rend_blackhandAI::JustEngagedWith(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::JustEngagedWith(), boss_the_beast::boss_thebeastAI::JustEngagedWith(), boss_urok_doomhowl::boss_urok_doomhowlAI::JustEngagedWith(), boss_warmaster_voone::boss_warmastervooneAI::JustEngagedWith(), boss_razorgore::boss_razorgoreAI::JustEngagedWith(), boss_baron_geddon::boss_baron_geddonAI::JustEngagedWith(), boss_garr::boss_garrAI::JustEngagedWith(), boss_gehennas::boss_gehennasAI::JustEngagedWith(), boss_lucifron::boss_lucifronAI::JustEngagedWith(), boss_magmadar::boss_magmadarAI::JustEngagedWith(), boss_majordomo::boss_majordomoAI::JustEngagedWith(), boss_ragnaros::boss_ragnarosAI::JustEngagedWith(), boss_shazzrah::boss_shazzrahAI::JustEngagedWith(), boss_sulfuron::boss_sulfuronAI::JustEngagedWith(), boss_nightbane::JustEngagedWith(), boss_malchezaar::JustEngagedWith(), boss_jarien::JustEngagedWith(), boss_sothos::JustEngagedWith(), boss_arlokk::boss_arlokkAI::JustEngagedWith(), boss_gahzranka::boss_gahzrankaAI::JustEngagedWith(), boss_grilek::boss_grilekAI::JustEngagedWith(), boss_hakkar::boss_hakkarAI::JustEngagedWith(), boss_hazzarah::JustEngagedWith(), boss_mandokir::boss_mandokirAI::JustEngagedWith(), boss_renataki::boss_renatakiAI::JustEngagedWith(), boss_thekal::boss_thekalAI::JustEngagedWith(), boss_venoxis::boss_venoxisAI::JustEngagedWith(), boss_wushoolay::boss_wushoolayAI::JustEngagedWith(), boss_epoch_hunter::JustEngagedWith(), boss_lieutenant_drake::JustEngagedWith(), boss_chrono_lord_deja::JustEngagedWith(), boss_temporus::JustEngagedWith(), boss_isalien::JustEngagedWith(), boss_skeram::JustEngagedWith(), boss_elder_nadox::JustEngagedWith(), boss_volazj::JustEngagedWith(), boss_jedoga_shadowseeker::JustEngagedWith(), boss_taldaram::JustEngagedWith(), boss_sister_svalna::boss_sister_svalnaAI::JustEngagedWith(), boss_exarch_maladaar::JustEngagedWith(), boss_shirrak_the_dead_watcher::JustEngagedWith(), boss_nexusprince_shaffar::JustEngagedWith(), boss_tavarok::JustEngagedWith(), boss_anzu::JustEngagedWith(), boss_darkweaver_syth::JustEngagedWith(), boss_talon_king_ikiss::JustEngagedWith(), boss_ambassador_hellmaw::JustEngagedWith(), boss_blackheart_the_inciter::JustEngagedWith(), boss_mennu_the_betrayer::JustEngagedWith(), boss_quagmirran::JustEngagedWith(), boss_rokmar_the_crackler::JustEngagedWith(), boss_hydromancer_thespia::JustEngagedWith(), boss_mekgineer_steamrigger::JustEngagedWith(), boss_warlord_kalithresh::JustEngagedWith(), boss_ghazan::JustEngagedWith(), boss_hungarfen::JustEngagedWith(), boss_swamplord_muselek::JustEngagedWith(), boss_the_black_stalker::JustEngagedWith(), boss_gruul::JustEngagedWith(), boss_high_king_maulgar::JustEngagedWith(), boss_broggok::JustEngagedWith(), boss_kelidan_the_breaker::JustEngagedWith(), boss_the_maker::JustEngagedWith(), boss_omor_the_unscarred::JustEngagedWith(), boss_watchkeeper_gargolmar::JustEngagedWith(), boss_dalliah_the_doomsayer::JustEngagedWith(), boss_zereketh_the_unbound::JustEngagedWith(), boss_commander_sarannis::JustEngagedWith(), boss_high_botanist_freywinn::JustEngagedWith(), boss_laj::JustEngagedWith(), boss_thorngrin_the_tender::JustEngagedWith(), boss_warp_splinter::JustEngagedWith(), boss_gatewatcher_gyrokill::JustEngagedWith(), boss_gatewatcher_iron_hand::JustEngagedWith(), boss_mechano_lord_capacitus::JustEngagedWith(), boss_nethermancer_sepethrea::JustEngagedWith(), boss_pathaleon_the_calculator::JustEngagedWith(), boss_sartharion::boss_sartharionAI::JustEngagedWith(), boss_murmur::JustEngagedWith(), boss_grand_warlock_nethekurse::JustEngagedWith(), boss_jeklik::PathEndReached(), boss_vazruden_the_herald::SummonedCreatureDies(), and boss_anub_arak::boss_anub_arakAI::UpdateAI().
_JustReachedHome()
void BossAI::_JustReachedHome () inline protected
{ me->setActive(false); }
References ScriptedAI::me, and WorldObject::setActive().
Referenced by JustReachedHome(), boss_majordomo::boss_majordomoAI::JustReachedHome(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustReachedHome(), boss_festergut::boss_festergutAI::JustReachedHome(), boss_lord_marrowgar::JustReachedHome(), boss_professor_putricide::boss_professor_putricideAI::JustReachedHome(), boss_rotface::boss_rotfaceAI::JustReachedHome(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustReachedHome(), and boss_ghazan::JustReachedHome().
_ProccessHealthCheckEvent()
bool BossAI::_ProccessHealthCheckEvent (uint8 healthPct, uint32 damage, std::function< void()> exec) const protected
{
    if (me->HealthBelowPctDamaged(healthPct, damage))
    {
        exec();
        return true;
    }
    return false;
}
References Unit::HealthBelowPctDamaged(), and ScriptedAI::me.
Referenced by DamageTaken().
_Reset()
void BossAI::_Reset () protected
{
    if (!me->IsAlive())
        return;
    me->SetCombatPulseDelay(0);
    me->ResetLootMode();
    events.Reset();
    scheduler.CancelAll();
    summons.DespawnAll();
    _healthCheckEvents.clear();
    if (instance)
        instance->SetBossState(_bossId, NOT_STARTED);
}
References _bossId, _healthCheckEvents, TaskScheduler::CancelAll(), SummonList::DespawnAll(), instance, Unit::IsAlive(), ScriptedAI::me, NOT_STARTED, Creature::ResetLootMode(), scheduler, InstanceScript::SetBossState(), Creature::SetCombatPulseDelay(), and summons.
Referenced by Reset(), boss_magmus::boss_magmusAI::Reset(), boss_halycon::boss_halyconAI::Reset(), boss_highlord_omokk::boss_highlordomokkAI::Reset(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::Reset(), boss_quartermaster_zigris::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::Reset(), boss_the_beast::boss_thebeastAI::Reset(), boss_chromaggus::boss_chromaggusAI::Reset(), boss_victor_nefarius::boss_victor_nefariusAI::Reset(), boss_nefarian::Reset(), boss_razorgore::boss_razorgoreAI::Reset(), boss_vaelastrasz::boss_vaelAI::Reset(), boss_baron_geddon::boss_baron_geddonAI::Reset(), boss_garr::boss_garrAI::Reset(), boss_golemagg::boss_golemaggAI::Reset(), boss_ragnaros::boss_ragnarosAI::Reset(), boss_malchezaar::Reset(), boss_terestian_illhoof::Reset(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::Reset(), boss_apothecary_hummel::boss_apothecary_hummelAI::Reset(), boss_jarien::Reset(), boss_sothos::Reset(), boss_akilzon::boss_akilzonAI::Reset(), boss_arlokk::boss_arlokkAI::Reset(), boss_gahzranka::boss_gahzrankaAI::Reset(), boss_hakkar::boss_hakkarAI::Reset(), boss_jeklik::Reset(), boss_renataki::boss_renatakiAI::Reset(), boss_thekal::boss_thekalAI::Reset(), boss_venoxis::boss_venoxisAI::Reset(), boss_captain_skarloc::Reset(), boss_epoch_hunter::Reset(), boss_lieutenant_drake::Reset(), boss_isalien::Reset(), boss_moam::Reset(), boss_sartura::Reset(), boss_skeram::Reset(), boss_amanitar::Reset(), boss_elder_nadox::Reset(), boss_volazj::Reset(), boss_jedoga_shadowseeker::Reset(), boss_taldaram::Reset(), boss_sartharion::boss_sartharionAI::Reset(), boss_sartharion_dragonAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), boss_festergut::boss_festergutAI::Reset(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::Reset(), boss_lord_marrowgar::Reset(), boss_professor_putricide::boss_professor_putricideAI::Reset(), boss_rotface::boss_rotfaceAI::Reset(), boss_sindragosa::boss_sindragosaAI::Reset(), boss_the_lich_king::boss_the_lich_kingAI::Reset(), boss_sister_svalna::boss_sister_svalnaAI::Reset(), boss_exarch_maladaar::Reset(), boss_shirrak_the_dead_watcher::Reset(), boss_nexusprince_shaffar::Reset(), boss_tavarok::Reset(), boss_anzu::Reset(), boss_darkweaver_syth::Reset(), boss_talon_king_ikiss::Reset(), boss_ambassador_hellmaw::Reset(), boss_blackheart_the_inciter::Reset(), boss_grandmaster_vorpil::Reset(), boss_murmur::Reset(), boss_mennu_the_betrayer::Reset(), boss_quagmirran::Reset(), boss_rokmar_the_crackler::Reset(), boss_warlord_kalithresh::Reset(), boss_ghazan::Reset(), boss_hungarfen::Reset(), boss_swamplord_muselek::Reset(), boss_gruul::Reset(), boss_high_king_maulgar::Reset(), boss_broggok::Reset(), boss_kelidan_the_breaker::Reset(), boss_the_maker::Reset(), boss_omor_the_unscarred::Reset(), boss_vazruden_the_herald::Reset(), boss_watchkeeper_gargolmar::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), boss_dalliah_the_doomsayer::Reset(), boss_harbinger_skyriss::Reset(), boss_wrath_scryer_soccothrates::Reset(), boss_commander_sarannis::Reset(), boss_laj::Reset(), boss_thorngrin_the_tender::Reset(), and boss_pathaleon_the_calculator::Reset().
CanRespawn()
bool BossAI::CanRespawn () override virtual
Reimplemented from CreatureAI.
{
    if (instance)
    {
        if (instance->GetBossState(_bossId) == DONE)
        {
            return false;
        }
    }
    return true;
}
References _bossId, DONE, InstanceScript::GetBossState(), and instance.
DamageTaken()
void BossAI::DamageTaken (Unit * attacker, uint32 & damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_eviscerator::boss_evisceratorAI, boss_mor_grayhoof, boss_jeklik, boss_renataki::boss_renatakiAI, boss_venoxis::boss_venoxisAI, boss_isalien, boss_kurinnaxx, boss_huhuran, boss_sartura, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_professor_putricide::boss_professor_putricideAI, boss_gyth::boss_gythAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_quartermaster_zigris, boss_warmaster_voone::boss_warmastervooneAI, boss_nefarian, boss_razorgore::boss_razorgoreAI, boss_baron_geddon::boss_baron_geddonAI, boss_golemagg::boss_golemaggAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_attumen, boss_midnight, boss_apothecary_hummel::boss_apothecary_hummelAI, boss_muru::boss_muruAI, boss_thekal::boss_thekalAI, boss_onyxia, boss_ayamiss, boss_eye_of_cthun, boss_ouro, boss_elder_nadox, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_sartharion::boss_sartharionAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_sindragosa::boss_sindragosaAI, boss_gothik::boss_gothikAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_commander_sarannis, boss_alar::boss_alarAI, boss_viscidus, boss_kalecgos::boss_kalecgosAI, boss_buru, boss_twinemperorsAI, boss_halion::boss_halionAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_the_lich_king::boss_the_lich_kingAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_brutallus::boss_brutallusAI, boss_bug_trio, boss_hadronox::boss_hadronoxAI, and boss_razuvious::boss_razuviousAI.
{
    if (!_healthCheckEvents.empty())
    {
        _healthCheckEvents.remove_if([&](HealthCheckEventData data) -> bool
        {
            return _ProccessHealthCheckEvent(data._healthPct, damage, data._exec);
        });
    }
}
References HealthCheckEventData::_exec, _healthCheckEvents, HealthCheckEventData::_healthPct, and _ProccessHealthCheckEvent().
ExecuteEvent()
virtual void BossAI::ExecuteEvent (uint32) inline virtual
Reimplemented in boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_warmaster_voone::boss_warmastervooneAI, boss_baron_geddon::boss_baron_geddonAI, boss_gehennas::boss_gehennasAI, boss_lucifron::boss_lucifronAI, boss_magmadar::boss_magmadarAI, boss_shazzrah::boss_shazzrahAI, boss_sulfuron::boss_sulfuronAI, boss_amanitar, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_sartharion_shadron::boss_sartharion_shadronAI, and boss_sartharion_vesperon::boss_sartharion_vesperonAI.
{ }
Referenced by boss_sartharion_dragonAI::UpdateAI(), and UpdateAI().
JustDied()
void BossAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_gyth::boss_gythAI, boss_halycon::boss_halyconAI, boss_highlord_omokk::boss_highlordomokkAI, boss_mor_grayhoof, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_quartermaster_zigris, boss_rend_blackhand::boss_rend_blackhandAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_broodlord::boss_broodlordAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_nefarian, boss_razorgore::boss_razorgoreAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_attumen, boss_nightbane, boss_malchezaar, boss_servant_quarters, boss_shade_of_aran, boss_terestian_illhoof, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_apothecary_hummel::boss_apothecary_hummelAI, boss_baroness_anastari::boss_baroness_anastariAI, boss_sacrolash::boss_sacrolashAI, boss_alythess::boss_alythessAI, boss_akilzon::boss_akilzonAI, boss_arlokk::boss_arlokkAI, boss_gahzranka::boss_gahzrankaAI, boss_hakkar::boss_hakkarAI, boss_jeklik, boss_mandokir::boss_mandokirAI, boss_thekal::boss_thekalAI, boss_venoxis::boss_venoxisAI, boss_archimonde::boss_archimondeAI, boss_captain_skarloc, boss_lieutenant_drake, boss_aeonus, boss_chrono_lord_deja, boss_temporus, boss_isalien, boss_moam, boss_rajaxx, boss_eye_of_cthun, boss_sartura, boss_skeram, boss_viscidus, boss_amanitar, boss_elder_nadox, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_sartharion::boss_sartharionAI, boss_sartharion_dragonAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_lord_marrowgar, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_sindragosa::boss_sindragosaAI, boss_the_lich_king::boss_the_lich_kingAI, boss_sister_svalna::boss_sister_svalnaAI, boss_exarch_maladaar, boss_nexusprince_shaffar, boss_tavarok, boss_darkweaver_syth, boss_talon_king_ikiss, boss_ambassador_hellmaw, boss_blackheart_the_inciter, boss_grandmaster_vorpil, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_mennu_the_betrayer, boss_hydromancer_thespia, boss_mekgineer_steamrigger, boss_warlord_kalithresh, boss_swamplord_muselek, boss_gruul, boss_high_king_maulgar, boss_kelidan_the_breaker, boss_the_maker, boss_omor_the_unscarred, boss_watchkeeper_gargolmar, boss_grand_warlock_nethekurse, npc_warden_mellichar::npc_warden_mellicharAI, boss_dalliah_the_doomsayer, boss_harbinger_skyriss, boss_wrath_scryer_soccothrates, boss_zereketh_the_unbound, boss_commander_sarannis, boss_high_botanist_freywinn, boss_thorngrin_the_tender, boss_warp_splinter, boss_gatewatcher_gyrokill, boss_gatewatcher_iron_hand, boss_mechano_lord_capacitus, boss_nethermancer_sepethrea, boss_pathaleon_the_calculator, boss_lord_valthalak::boss_lord_valthalakAI, boss_curator, boss_maiden_of_virtue, boss_moroes, boss_netherspite, boss_jarien, boss_sothos, boss_brutallus::boss_brutallusAI, boss_felmyst::boss_felmystAI, boss_kalecgos::boss_kalecgosAI, boss_marli, boss_epoch_hunter, boss_ayamiss, boss_buru, boss_kurinnaxx, boss_bug_trio, boss_cthun, boss_twinemperorsAI, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, boss_krik_thir::boss_krik_thirAI, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_novos::boss_novosAI, boss_tharon_ja::boss_tharon_jaAI, boss_trollgore::boss_trollgoreAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_moorabi::boss_moorabiAI, boss_slad_ran::boss_slad_ranAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_four_horsemen::boss_four_horsemenAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, boss_grobbulus::boss_grobbulusAI, boss_heigan::boss_heiganAI, boss_kelthuzad::boss_kelthuzadAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_noth::boss_nothAI, boss_patchwerk::boss_patchwerkAI, boss_razuvious::boss_razuviousAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_anomalus::boss_anomalusAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_keristrasza::boss_keristraszaAI, boss_magus_telestra::boss_magus_telestraAI, boss_ormorok::boss_ormorokAI, boss_pandemonius, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_mother_shahraz::boss_shahrazAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_supremus::boss_supremusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_najentus::boss_najentusAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_lady_vashj::boss_lady_vashjAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_magtheridon, boss_porung, boss_warbringer_omrogg, boss_warchief_kargath_bladefist, boss_alar::boss_alarAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_kaelthas::boss_kaelthasAI, and boss_void_reaver::boss_void_reaverAI.
{ _JustDied(); }
References _JustDied().
Referenced by boss_lord_valthalak::boss_lord_valthalakAI::JustDied(), boss_curator::JustDied(), boss_maiden_of_virtue::JustDied(), boss_moroes::JustDied(), boss_netherspite::JustDied(), boss_brutallus::boss_brutallusAI::JustDied(), boss_felmyst::boss_felmystAI::JustDied(), boss_kalecgos::boss_kalecgosAI::JustDied(), boss_marli::JustDied(), boss_ayamiss::JustDied(), boss_buru::JustDied(), boss_kurinnaxx::JustDied(), boss_bug_trio::JustDied(), boss_cthun::JustDied(), boss_twinemperorsAI::JustDied(), boss_anub_arak::boss_anub_arakAI::JustDied(), boss_hadronox::boss_hadronoxAI::JustDied(), boss_krik_thir::boss_krik_thirAI::JustDied(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustDied(), boss_general_zarithrian::boss_general_zarithrianAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustDied(), boss_novos::boss_novosAI::JustDied(), boss_tharon_ja::boss_tharon_jaAI::JustDied(), boss_trollgore::boss_trollgoreAI::JustDied(), boss_eck::boss_eckAI::JustDied(), boss_gal_darah::boss_gal_darahAI::JustDied(), boss_moorabi::boss_moorabiAI::JustDied(), boss_slad_ran::boss_slad_ranAI::JustDied(), boss_anubrekhan::boss_anubrekhanAI::JustDied(), boss_faerlina::boss_faerlinaAI::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), boss_gluth::boss_gluthAI::JustDied(), boss_gothik::boss_gothikAI::JustDied(), boss_grobbulus::boss_grobbulusAI::JustDied(), boss_heigan::boss_heiganAI::JustDied(), boss_kelthuzad::boss_kelthuzadAI::JustDied(), boss_loatheb::boss_loathebAI::JustDied(), boss_maexxna::boss_maexxnaAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_patchwerk::boss_patchwerkAI::JustDied(), boss_razuvious::boss_razuviousAI::JustDied(), boss_sapphiron::boss_sapphironAI::JustDied(), boss_thaddius::boss_thaddiusAI::JustDied(), boss_anomalus::boss_anomalusAI::JustDied(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::JustDied(), boss_keristrasza::boss_keristraszaAI::JustDied(), boss_magus_telestra::boss_magus_telestraAI::JustDied(), boss_ormorok::boss_ormorokAI::JustDied(), boss_pandemonius::JustDied(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::JustDied(), boss_mother_shahraz::boss_shahrazAI::JustDied(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustDied(), boss_shade_of_akama::boss_shade_of_akamaAI::JustDied(), boss_supremus::boss_supremusAI::JustDied(), boss_teron_gorefiend::boss_teron_gorefiendAI::JustDied(), boss_najentus::boss_najentusAI::JustDied(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustDied(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustDied(), boss_lady_vashj::boss_lady_vashjAI::JustDied(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustDied(), boss_the_lurker_below::boss_the_lurker_belowAI::JustDied(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::JustDied(), boss_magtheridon::JustDied(), boss_porung::JustDied(), boss_warbringer_omrogg::JustDied(), boss_warchief_kargath_bladefist::JustDied(), boss_alar::boss_alarAI::JustDied(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::JustDied(), boss_kaelthas::boss_kaelthasAI::JustDied(), and boss_void_reaver::boss_void_reaverAI::JustDied().
JustEngagedWith()
void BossAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
Reimplemented in boss_sartharion_dragonAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_anubshiah::boss_anubshiahAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_eviscerator::boss_evisceratorAI, boss_gorosh_the_dervish::boss_gorosh_the_dervishAI, boss_grizzle::boss_grizzleAI, boss_hedrum::boss_hedrumAI, boss_magmus::boss_magmusAI, boss_moira_bronzebeardAI, boss_high_priestess_thaurissanAI, boss_okthor::boss_okthorAI, boss_drakkisath::boss_drakkisathAI, boss_gyth::boss_gythAI, boss_halycon::boss_halyconAI, boss_highlord_omokk::boss_highlordomokkAI, boss_mor_grayhoof, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_the_beast::boss_thebeastAI, boss_urok_doomhowl::boss_urok_doomhowlAI, boss_warmaster_voone::boss_warmastervooneAI, boss_nefarian, boss_razorgore::boss_razorgoreAI, boss_baron_geddon::boss_baron_geddonAI, boss_garr::boss_garrAI, boss_gehennas::boss_gehennasAI, boss_lucifron::boss_lucifronAI, boss_magmadar::boss_magmadarAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_shazzrah::boss_shazzrahAI, boss_sulfuron::boss_sulfuronAI, boss_nightbane, boss_malchezaar, boss_servant_quarters, boss_shade_of_aran, boss_terestian_illhoof, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_baroness_anastari::boss_baroness_anastariAI, boss_jarien, boss_sothos, boss_akilzon::boss_akilzonAI, boss_arlokk::boss_arlokkAI, boss_gahzranka::boss_gahzrankaAI, boss_grilek::boss_grilekAI, boss_hakkar::boss_hakkarAI, boss_hazzarah, boss_jeklik, boss_mandokir::boss_mandokirAI, boss_renataki::boss_renatakiAI, boss_thekal::boss_thekalAI, boss_venoxis::boss_venoxisAI, boss_wushoolay::boss_wushoolayAI, boss_archimonde::boss_archimondeAI, boss_captain_skarloc, boss_epoch_hunter, boss_lieutenant_drake, boss_aeonus, boss_chrono_lord_deja, boss_temporus, boss_isalien, boss_rajaxx, boss_cthun, boss_skeram, boss_amanitar, boss_elder_nadox, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, boss_lord_marrowgar, boss_sister_svalna::boss_sister_svalnaAI, boss_exarch_maladaar, boss_shirrak_the_dead_watcher, boss_nexusprince_shaffar, boss_tavarok, boss_anzu, boss_darkweaver_syth, boss_talon_king_ikiss, boss_ambassador_hellmaw, boss_blackheart_the_inciter, boss_grandmaster_vorpil, boss_the_lurker_below::boss_the_lurker_belowAI, boss_mennu_the_betrayer, boss_quagmirran, boss_rokmar_the_crackler, boss_hydromancer_thespia, boss_mekgineer_steamrigger, boss_warlord_kalithresh, boss_ghazan, boss_hungarfen, boss_swamplord_muselek, boss_the_black_stalker, boss_gruul, boss_high_king_maulgar, boss_broggok, boss_kelidan_the_breaker, boss_the_maker, boss_omor_the_unscarred, boss_watchkeeper_gargolmar, npc_warden_mellichar::npc_warden_mellicharAI, boss_dalliah_the_doomsayer, boss_harbinger_skyriss, boss_wrath_scryer_soccothrates, boss_zereketh_the_unbound, boss_commander_sarannis, boss_high_botanist_freywinn, boss_laj, boss_thorngrin_the_tender, boss_warp_splinter, boss_gatewatcher_gyrokill, boss_gatewatcher_iron_hand, boss_mechano_lord_capacitus, boss_nethermancer_sepethrea, boss_pathaleon_the_calculator, boss_ayamiss, boss_sartharion::boss_sartharionAI, boss_the_lich_king::boss_the_lich_kingAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_quartermaster_zigris, boss_broodlord::boss_broodlordAI, boss_chromaggus::boss_chromaggusAI, boss_ebonroc::boss_ebonrocAI, boss_firemaw::boss_firemawAI, boss_flamegor::boss_flamegorAI, boss_vaelastrasz::boss_vaelAI, boss_curator, boss_maiden_of_virtue, boss_midnight, boss_moroes, boss_netherspite, boss_brutallus::boss_brutallusAI, boss_sacrolash::boss_sacrolashAI, boss_alythess::boss_alythessAI, boss_felmyst::boss_felmystAI, boss_kalecgos::boss_kalecgosAI, boss_muru::boss_muruAI, boss_jindo, boss_marli, boss_onyxia, boss_buru, boss_moam, boss_ossirian, boss_kri, boss_vem, boss_yauj, boss_eye_of_cthun, boss_fankriss, boss_huhuran, boss_ouro, boss_sartura, boss_twinemperorsAI, boss_veknilash, boss_veklor, boss_viscidus, boss_krik_thir::boss_krik_thirAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_dred::boss_dredAI, boss_novos::boss_novosAI, boss_tharon_ja::boss_tharon_jaAI, boss_trollgore::boss_trollgoreAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_moorabi::boss_moorabiAI, boss_slad_ran::boss_slad_ranAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_sindragosa::boss_sindragosaAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_four_horsemen::boss_four_horsemenAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, boss_grobbulus::boss_grobbulusAI, boss_heigan::boss_heiganAI, boss_kelthuzad::boss_kelthuzadAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_noth::boss_nothAI, boss_patchwerk::boss_patchwerkAI, boss_razuvious::boss_razuviousAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_anomalus::boss_anomalusAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_keristrasza::boss_keristraszaAI, boss_magus_telestra::boss_magus_telestraAI, boss_ormorok::boss_ormorokAI, boss_pandemonius, boss_murmur, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_mother_shahraz::boss_shahrazAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_supremus::boss_supremusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_najentus::boss_najentusAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_lady_vashj::boss_lady_vashjAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_magtheridon, boss_grand_warlock_nethekurse, boss_porung, boss_warbringer_omrogg, boss_warchief_kargath_bladefist, boss_alar::boss_alarAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_kaelthas::boss_kaelthasAI, and boss_void_reaver::boss_void_reaverAI.
{ _JustEngagedWith(); }
References _JustEngagedWith().
Referenced by boss_bug_trio::EnterCombatWithTrio(), boss_ayamiss::JustEngagedWith(), boss_lord_valthalak::boss_lord_valthalakAI::JustEngagedWith(), boss_quartermaster_zigris::JustEngagedWith(), boss_broodlord::boss_broodlordAI::JustEngagedWith(), boss_chromaggus::boss_chromaggusAI::JustEngagedWith(), boss_ebonroc::boss_ebonrocAI::JustEngagedWith(), boss_firemaw::boss_firemawAI::JustEngagedWith(), boss_flamegor::boss_flamegorAI::JustEngagedWith(), boss_vaelastrasz::boss_vaelAI::JustEngagedWith(), boss_curator::JustEngagedWith(), boss_maiden_of_virtue::JustEngagedWith(), boss_midnight::JustEngagedWith(), boss_moroes::JustEngagedWith(), boss_netherspite::JustEngagedWith(), boss_brutallus::boss_brutallusAI::JustEngagedWith(), boss_sacrolash::boss_sacrolashAI::JustEngagedWith(), boss_alythess::boss_alythessAI::JustEngagedWith(), boss_felmyst::boss_felmystAI::JustEngagedWith(), boss_kalecgos::boss_kalecgosAI::JustEngagedWith(), boss_muru::boss_muruAI::JustEngagedWith(), boss_jindo::JustEngagedWith(), boss_marli::JustEngagedWith(), boss_onyxia::JustEngagedWith(), boss_buru::JustEngagedWith(), boss_moam::JustEngagedWith(), boss_ossirian::JustEngagedWith(), boss_eye_of_cthun::JustEngagedWith(), boss_fankriss::JustEngagedWith(), boss_huhuran::JustEngagedWith(), boss_ouro::JustEngagedWith(), boss_sartura::JustEngagedWith(), boss_twinemperorsAI::JustEngagedWith(), boss_viscidus::JustEngagedWith(), boss_krik_thir::boss_krik_thirAI::JustEngagedWith(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustEngagedWith(), boss_general_zarithrian::boss_general_zarithrianAI::JustEngagedWith(), boss_halion::boss_halionAI::JustEngagedWith(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustEngagedWith(), boss_dred::boss_dredAI::JustEngagedWith(), boss_novos::boss_novosAI::JustEngagedWith(), boss_tharon_ja::boss_tharon_jaAI::JustEngagedWith(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustEngagedWith(), boss_eck::boss_eckAI::JustEngagedWith(), boss_gal_darah::boss_gal_darahAI::JustEngagedWith(), boss_moorabi::boss_moorabiAI::JustEngagedWith(), boss_slad_ran::boss_slad_ranAI::JustEngagedWith(), boss_anubrekhan::boss_anubrekhanAI::JustEngagedWith(), boss_faerlina::boss_faerlinaAI::JustEngagedWith(), boss_four_horsemen::boss_four_horsemenAI::JustEngagedWith(), boss_gluth::boss_gluthAI::JustEngagedWith(), boss_gothik::boss_gothikAI::JustEngagedWith(), boss_grobbulus::boss_grobbulusAI::JustEngagedWith(), boss_heigan::boss_heiganAI::JustEngagedWith(), boss_kelthuzad::boss_kelthuzadAI::JustEngagedWith(), boss_loatheb::boss_loathebAI::JustEngagedWith(), boss_maexxna::boss_maexxnaAI::JustEngagedWith(), boss_noth::boss_nothAI::JustEngagedWith(), boss_patchwerk::boss_patchwerkAI::JustEngagedWith(), boss_razuvious::boss_razuviousAI::JustEngagedWith(), boss_sapphiron::boss_sapphironAI::JustEngagedWith(), boss_thaddius::boss_thaddiusAI::JustEngagedWith(), boss_anomalus::boss_anomalusAI::JustEngagedWith(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::JustEngagedWith(), boss_keristrasza::boss_keristraszaAI::JustEngagedWith(), boss_magus_telestra::boss_magus_telestraAI::JustEngagedWith(), boss_ormorok::boss_ormorokAI::JustEngagedWith(), boss_pandemonius::JustEngagedWith(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::JustEngagedWith(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustEngagedWith(), boss_mother_shahraz::boss_shahrazAI::JustEngagedWith(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustEngagedWith(), boss_shade_of_akama::boss_shade_of_akamaAI::JustEngagedWith(), boss_supremus::boss_supremusAI::JustEngagedWith(), boss_teron_gorefiend::boss_teron_gorefiendAI::JustEngagedWith(), boss_najentus::boss_najentusAI::JustEngagedWith(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustEngagedWith(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustEngagedWith(), boss_lady_vashj::boss_lady_vashjAI::JustEngagedWith(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustEngagedWith(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::JustEngagedWith(), boss_magtheridon::JustEngagedWith(), boss_porung::JustEngagedWith(), boss_warbringer_omrogg::JustEngagedWith(), boss_warchief_kargath_bladefist::JustEngagedWith(), boss_alar::boss_alarAI::JustEngagedWith(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::JustEngagedWith(), boss_kaelthas::boss_kaelthasAI::JustEngagedWith(), and boss_void_reaver::boss_void_reaverAI::JustEngagedWith().
JustReachedHome()
void BossAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Reimplemented in boss_victor_nefarius::boss_victor_nefariusAI, boss_majordomo::boss_majordomoAI, boss_moroes, boss_kalecgos::boss_kalecgosAI, boss_arlokk::boss_arlokkAI, boss_aeonus, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_gal_darah::boss_gal_darahAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_lord_marrowgar, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_ghazan, boss_grand_warlock_nethekurse, and boss_alar::boss_alarAI.
{ _JustReachedHome(); }
References _JustReachedHome().
Referenced by boss_moroes::JustReachedHome(), boss_kalecgos::boss_kalecgosAI::JustReachedHome(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustReachedHome(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustReachedHome(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustReachedHome(), boss_gal_darah::boss_gal_darahAI::JustReachedHome(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustReachedHome(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustReachedHome(), and boss_alar::boss_alarAI::JustReachedHome().
JustSummoned()
void BossAI::JustSummoned (Creature * summon) override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_exarch_maladaar, boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_grobbulus::boss_grobbulusAI, boss_kelthuzad::boss_kelthuzadAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_razuvious::boss_razuviousAI, boss_thaddius::boss_thaddiusAI, boss_ossirian, boss_skeram, boss_mekgineer_steamrigger, boss_gyth::boss_gythAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_razorgore::boss_razorgoreAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_curator, boss_attumen, boss_midnight, boss_nightbane, boss_sacrolash::boss_sacrolashAI, boss_felmyst::boss_felmystAI, boss_muru::boss_muruAI, boss_hazzarah, boss_jindo, boss_captain_skarloc, boss_isalien, boss_onyxia, boss_eye_of_cthun, boss_amanitar, boss_jedoga_shadowseeker, boss_taldaram, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, boss_krik_thir::boss_krik_thirAI, boss_sartharion::boss_sartharionAI, boss_sartharion_dragonAI, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_novos::boss_novosAI, boss_trollgore::boss_trollgoreAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_gal_darah::boss_gal_darahAI, boss_slad_ran::boss_slad_ranAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_sindragosa::boss_sindragosaAI, boss_the_lich_king::boss_the_lich_kingAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, boss_noth::boss_nothAI, boss_anomalus::boss_anomalusAI, boss_magus_telestra::boss_magus_telestraAI, boss_ormorok::boss_ormorokAI, boss_shirrak_the_dead_watcher, boss_nexusprince_shaffar, boss_grandmaster_vorpil, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_supremus::boss_supremusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_lady_vashj::boss_lady_vashjAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_mennu_the_betrayer, boss_the_black_stalker, boss_omor_the_unscarred, boss_vazruden_the_herald, boss_warchief_kargath_bladefist, npc_warden_mellichar::npc_warden_mellicharAI, boss_harbinger_skyriss, boss_alar::boss_alarAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_kaelthas::boss_kaelthasAI, boss_mechano_lord_capacitus, boss_nethermancer_sepethrea, boss_vaelastrasz::boss_vaelAI, boss_terestian_illhoof, boss_archimonde::boss_archimondeAI, boss_broggok, and boss_ayamiss.
{
    summons.Summon(summon);
    if (me->IsEngaged())
        DoZoneInCombat(summon);
}
References CreatureAI::DoZoneInCombat(), Unit::IsEngaged(), ScriptedAI::me, SummonList::Summon(), and summons.
Referenced by boss_skeram::JustSummoned(), boss_victor_nefarius::boss_victor_nefariusAI::JustSummoned(), boss_ragnaros::boss_ragnarosAI::JustSummoned(), boss_attumen::JustSummoned(), boss_midnight::JustSummoned(), boss_jindo::JustSummoned(), boss_sartharion_dragonAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_the_black_stalker::JustSummoned(), and boss_harbinger_skyriss::JustSummoned().
Reset()
void BossAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_magmus::boss_magmusAI, boss_gyth::boss_gythAI, boss_halycon::boss_halyconAI, boss_highlord_omokk::boss_highlordomokkAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_mor_grayhoof, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_quartermaster_zigris, boss_rend_blackhand::boss_rend_blackhandAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_the_beast::boss_thebeastAI, boss_chromaggus::boss_chromaggusAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_nefarian, boss_razorgore::boss_razorgoreAI, boss_vaelastrasz::boss_vaelAI, boss_baron_geddon::boss_baron_geddonAI, boss_garr::boss_garrAI, boss_golemagg::boss_golemaggAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_curator, boss_attumen, boss_midnight, boss_moroes, boss_netherspite, boss_nightbane, boss_malchezaar, boss_servant_quarters, boss_shade_of_aran, boss_terestian_illhoof, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_apothecary_hummel::boss_apothecary_hummelAI, boss_baroness_anastari::boss_baroness_anastariAI, boss_jarien, boss_sothos, boss_brutallus::boss_brutallusAI, boss_sacrolash::boss_sacrolashAI, boss_alythess::boss_alythessAI, boss_felmyst::boss_felmystAI, boss_kalecgos::boss_kalecgosAI, boss_muru::boss_muruAI, boss_akilzon::boss_akilzonAI, boss_arlokk::boss_arlokkAI, boss_gahzranka::boss_gahzrankaAI, boss_grilek::boss_grilekAI, boss_hakkar::boss_hakkarAI, boss_jeklik, boss_mandokir::boss_mandokirAI, boss_marli, boss_renataki::boss_renatakiAI, boss_thekal::boss_thekalAI, boss_venoxis::boss_venoxisAI, boss_archimonde::boss_archimondeAI, boss_captain_skarloc, boss_epoch_hunter, boss_lieutenant_drake, boss_isalien, boss_onyxia, boss_ayamiss, boss_kurinnaxx, boss_moam, boss_ossirian, boss_bug_trio, boss_eye_of_cthun, boss_cthun, boss_fankriss, boss_huhuran, boss_ouro, boss_sartura, boss_skeram, boss_viscidus, boss_amanitar, boss_elder_nadox, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, boss_krik_thir::boss_krik_thirAI, boss_sartharion::boss_sartharionAI, boss_sartharion_dragonAI, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_sartharion_shadron::boss_sartharion_shadronAI, boss_sartharion_vesperon::boss_sartharion_vesperonAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_dred::boss_dredAI, boss_novos::boss_novosAI, boss_tharon_ja::boss_tharon_jaAI, boss_trollgore::boss_trollgoreAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_moorabi::boss_moorabiAI, boss_slad_ran::boss_slad_ranAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_lord_marrowgar, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_sindragosa::boss_sindragosaAI, boss_the_lich_king::boss_the_lich_kingAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_sister_svalna::boss_sister_svalnaAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_four_horsemen::boss_four_horsemenAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, boss_grobbulus::boss_grobbulusAI, boss_heigan::boss_heiganAI, boss_kelthuzad::boss_kelthuzadAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_noth::boss_nothAI, boss_patchwerk::boss_patchwerkAI, boss_razuvious::boss_razuviousAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_anomalus::boss_anomalusAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_keristrasza::boss_keristraszaAI, boss_magus_telestra::boss_magus_telestraAI, boss_ormorok::boss_ormorokAI, boss_exarch_maladaar, boss_shirrak_the_dead_watcher, boss_nexusprince_shaffar, boss_tavarok, boss_anzu, boss_darkweaver_syth, boss_talon_king_ikiss, boss_ambassador_hellmaw, boss_blackheart_the_inciter, boss_grandmaster_vorpil, boss_murmur, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_mother_shahraz::boss_shahrazAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_supremus::boss_supremusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_najentus::boss_najentusAI, boss_illidari_council::boss_illidari_councilAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_lady_vashj::boss_lady_vashjAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_mennu_the_betrayer, boss_quagmirran, boss_rokmar_the_crackler, boss_warlord_kalithresh, boss_ghazan, boss_hungarfen, boss_swamplord_muselek, boss_gruul, boss_high_king_maulgar, boss_broggok, boss_kelidan_the_breaker, boss_the_maker, boss_omor_the_unscarred, boss_vazruden_the_herald, boss_watchkeeper_gargolmar, boss_magtheridon, boss_grand_warlock_nethekurse, boss_warchief_kargath_bladefist, npc_warden_mellichar::npc_warden_mellicharAI, boss_dalliah_the_doomsayer, boss_harbinger_skyriss, boss_wrath_scryer_soccothrates, boss_commander_sarannis, boss_laj, boss_thorngrin_the_tender, boss_alar::boss_alarAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_kaelthas::boss_kaelthasAI, boss_void_reaver::boss_void_reaverAI, and boss_pathaleon_the_calculator.
{ _Reset(); }
References _Reset().
Referenced by boss_jindo::EnterEvadeMode(), boss_lord_valthalak::boss_lord_valthalakAI::Reset(), boss_curator::Reset(), boss_midnight::Reset(), boss_moroes::Reset(), boss_netherspite::Reset(), boss_nightbane::Reset(), boss_shade_of_aran::Reset(), boss_brutallus::boss_brutallusAI::Reset(), boss_sacrolash::boss_sacrolashAI::Reset(), boss_alythess::boss_alythessAI::Reset(), boss_felmyst::boss_felmystAI::Reset(), boss_kalecgos::boss_kalecgosAI::Reset(), boss_muru::boss_muruAI::Reset(), boss_grilek::boss_grilekAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), boss_marli::Reset(), boss_onyxia::Reset(), boss_ayamiss::Reset(), boss_kurinnaxx::Reset(), boss_ossirian::Reset(), boss_bug_trio::Reset(), boss_eye_of_cthun::Reset(), boss_cthun::Reset(), boss_fankriss::Reset(), boss_huhuran::Reset(), boss_viscidus::Reset(), boss_anub_arak::boss_anub_arakAI::Reset(), boss_hadronox::boss_hadronoxAI::Reset(), boss_krik_thir::boss_krik_thirAI::Reset(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::Reset(), boss_general_zarithrian::boss_general_zarithrianAI::Reset(), boss_halion::boss_halionAI::Reset(), boss_saviana_ragefire::boss_saviana_ragefireAI::Reset(), boss_dred::boss_dredAI::Reset(), boss_novos::boss_novosAI::Reset(), boss_tharon_ja::boss_tharon_jaAI::Reset(), boss_trollgore::boss_trollgoreAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), boss_eck::boss_eckAI::Reset(), boss_gal_darah::boss_gal_darahAI::Reset(), boss_moorabi::boss_moorabiAI::Reset(), boss_slad_ran::boss_slad_ranAI::Reset(), boss_anubrekhan::boss_anubrekhanAI::Reset(), boss_faerlina::boss_faerlinaAI::Reset(), boss_four_horsemen::boss_four_horsemenAI::Reset(), boss_gluth::boss_gluthAI::Reset(), boss_gothik::boss_gothikAI::Reset(), boss_grobbulus::boss_grobbulusAI::Reset(), boss_heigan::boss_heiganAI::Reset(), boss_kelthuzad::boss_kelthuzadAI::Reset(), boss_loatheb::boss_loathebAI::Reset(), boss_maexxna::boss_maexxnaAI::Reset(), boss_noth::boss_nothAI::Reset(), boss_patchwerk::boss_patchwerkAI::Reset(), boss_razuvious::boss_razuviousAI::Reset(), boss_sapphiron::boss_sapphironAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_anomalus::boss_anomalusAI::Reset(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::Reset(), boss_keristrasza::boss_keristraszaAI::Reset(), boss_magus_telestra::boss_magus_telestraAI::Reset(), boss_ormorok::boss_ormorokAI::Reset(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::Reset(), boss_illidan_stormrage::boss_illidan_stormrageAI::Reset(), boss_mother_shahraz::boss_shahrazAI::Reset(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::Reset(), boss_shade_of_akama::boss_shade_of_akamaAI::Reset(), boss_supremus::boss_supremusAI::Reset(), boss_teron_gorefiend::boss_teron_gorefiendAI::Reset(), boss_najentus::boss_najentusAI::Reset(), boss_illidari_council::boss_illidari_councilAI::Reset(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::Reset(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::Reset(), boss_lady_vashj::boss_lady_vashjAI::Reset(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::Reset(), boss_the_lurker_below::boss_the_lurker_belowAI::Reset(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::Reset(), boss_magtheridon::Reset(), boss_warchief_kargath_bladefist::Reset(), boss_alar::boss_alarAI::Reset(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::Reset(), boss_kaelthas::boss_kaelthasAI::Reset(), and boss_void_reaver::boss_void_reaverAI::Reset().
ScheduleHealthCheckEvent() [1/2]
void BossAI::ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
{
    for (auto const& checks : healthPct)
    {
        _healthCheckEvents.push_back(HealthCheckEventData(checks, exec));
    }
}
References _healthCheckEvents.
ScheduleHealthCheckEvent() [2/2]
void BossAI::ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
Parameters
healthPct The health percent at which the code will be executed.
exec The fuction to be executed.
{
    _healthCheckEvents.push_back(HealthCheckEventData(healthPct, exec));
};
References _healthCheckEvents.
Referenced by boss_mekgineer_steamrigger::JustEngagedWith(), boss_pathaleon_the_calculator::JustEngagedWith(), boss_curator::Reset(), boss_moroes::Reset(), boss_nightbane::Reset(), boss_malchezaar::Reset(), boss_shade_of_aran::Reset(), boss_exarch_maladaar::Reset(), boss_anzu::Reset(), boss_darkweaver_syth::Reset(), boss_talon_king_ikiss::Reset(), boss_mennu_the_betrayer::Reset(), boss_rokmar_the_crackler::Reset(), boss_ghazan::Reset(), boss_hungarfen::Reset(), boss_high_king_maulgar::Reset(), boss_omor_the_unscarred::Reset(), boss_watchkeeper_gargolmar::Reset(), boss_magtheridon::Reset(), boss_grand_warlock_nethekurse::Reset(), boss_dalliah_the_doomsayer::Reset(), boss_harbinger_skyriss::Reset(), boss_wrath_scryer_soccothrates::Reset(), and boss_thorngrin_the_tender::Reset().
ScheduleTasks()
virtual void BossAI::ScheduleTasks () inline virtual
Reimplemented in boss_attumen, boss_ayamiss, and boss_cthun.
{ }
Referenced by _JustEngagedWith().
SummonedCreatureDespawn()
void BossAI::SummonedCreatureDespawn (Creature * summon) override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_anubrekhan::boss_anubrekhanAI, boss_gothik::boss_gothikAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_ossirian, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_sindragosa::boss_sindragosaAI, boss_grobbulus::boss_grobbulusAI, boss_nexusprince_shaffar, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_supremus::boss_supremusAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, and boss_vazruden_the_herald.
{
    summons.Despawn(summon);
}
References SummonList::Despawn(), and summons.
Referenced by boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn(), and boss_sindragosa::boss_sindragosaAI::SummonedCreatureDespawn().
SummonedCreatureDespawnAll()
void BossAI::SummonedCreatureDespawnAll () override virtual
Reimplemented from CreatureAI.
{
    summons.DespawnAll();
}
References SummonList::DespawnAll(), and summons.
TeleportCheaters()
void BossAI::TeleportCheaters () protected
{
    float x, y, z;
    me->GetPosition(x, y, z);
    ThreatContainer::StorageType threatList = me->GetThreatMgr().GetThreatList();
    for (ThreatContainer::StorageType::const_iterator itr = threatList.begin(); itr != threatList.end(); ++itr)
        if (Unit* target = (*itr)->getTarget())
            if (target->GetTypeId() == TYPEID_PLAYER && !IsInBoundary(target))
                target->NearTeleportTo(x, y, z, 0);
}
References Position::GetPosition(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), CreatureAI::IsInBoundary(), ScriptedAI::me, and TYPEID_PLAYER.
UpdateAI()
void BossAI::UpdateAI (uint32 diff) override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_sartharion_dragonAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_anubshiah::boss_anubshiahAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_eviscerator::boss_evisceratorAI, boss_gorosh_the_dervish::boss_gorosh_the_dervishAI, boss_grizzle::boss_grizzleAI, boss_hedrum::boss_hedrumAI, boss_magmus::boss_magmusAI, boss_moira_bronzebeardAI, boss_high_priestess_thaurissanAI, boss_okthor::boss_okthorAI, boss_drakkisath::boss_drakkisathAI, boss_gyth::boss_gythAI, boss_halycon::boss_halyconAI, boss_highlord_omokk::boss_highlordomokkAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_mor_grayhoof, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_quartermaster_zigris, boss_rend_blackhand::boss_rend_blackhandAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_the_beast::boss_thebeastAI, boss_urok_doomhowl::boss_urok_doomhowlAI, boss_broodlord::boss_broodlordAI, boss_chromaggus::boss_chromaggusAI, boss_ebonroc::boss_ebonrocAI, boss_firemaw::boss_firemawAI, boss_flamegor::boss_flamegorAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_nefarian, boss_razorgore::boss_razorgoreAI, boss_vaelastrasz::boss_vaelAI, boss_garr::boss_garrAI, boss_golemagg::boss_golemaggAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_curator, boss_attumen, boss_midnight, boss_moroes, boss_netherspite, boss_nightbane, boss_servant_quarters, boss_shade_of_aran, boss_terestian_illhoof, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_apothecary_hummel::boss_apothecary_hummelAI, boss_baroness_anastari::boss_baroness_anastariAI, boss_jarien, boss_sothos, boss_brutallus::boss_brutallusAI, boss_sacrolash::boss_sacrolashAI, boss_alythess::boss_alythessAI, boss_felmyst::boss_felmystAI, boss_kalecgos::boss_kalecgosAI, boss_muru::boss_muruAI, boss_akilzon::boss_akilzonAI, boss_arlokk::boss_arlokkAI, boss_gahzranka::boss_gahzrankaAI, boss_grilek::boss_grilekAI, boss_hakkar::boss_hakkarAI, boss_hazzarah, boss_jeklik, boss_jindo, boss_mandokir::boss_mandokirAI, boss_marli, boss_renataki::boss_renatakiAI, boss_thekal::boss_thekalAI, boss_venoxis::boss_venoxisAI, boss_wushoolay::boss_wushoolayAI, boss_archimonde::boss_archimondeAI, boss_captain_skarloc, boss_epoch_hunter, boss_lieutenant_drake, boss_isalien, boss_onyxia, boss_ayamiss, boss_buru, boss_kurinnaxx, boss_moam, boss_ossirian, boss_rajaxx, boss_bug_trio, boss_eye_of_cthun, boss_cthun, boss_fankriss, boss_huhuran, boss_ouro, boss_sartura, boss_skeram, boss_twinemperorsAI, boss_viscidus, boss_elder_nadox, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, boss_krik_thir::boss_krik_thirAI, boss_sartharion::boss_sartharionAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_dred::boss_dredAI, boss_novos::boss_novosAI, boss_tharon_ja::boss_tharon_jaAI, boss_trollgore::boss_trollgoreAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_moorabi::boss_moorabiAI, boss_slad_ran::boss_slad_ranAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_lord_marrowgar, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, boss_sindragosa::boss_sindragosaAI, boss_the_lich_king::boss_the_lich_kingAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_sister_svalna::boss_sister_svalnaAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_four_horsemen::boss_four_horsemenAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, boss_grobbulus::boss_grobbulusAI, boss_heigan::boss_heiganAI, boss_kelthuzad::boss_kelthuzadAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_noth::boss_nothAI, boss_patchwerk::boss_patchwerkAI, boss_razuvious::boss_razuviousAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_anomalus::boss_anomalusAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_keristrasza::boss_keristraszaAI, boss_magus_telestra::boss_magus_telestraAI, boss_ormorok::boss_ormorokAI, boss_exarch_maladaar, boss_shirrak_the_dead_watcher, boss_nexusprince_shaffar, boss_anzu, boss_ambassador_hellmaw, boss_blackheart_the_inciter, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_mother_shahraz::boss_shahrazAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_supremus::boss_supremusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_najentus::boss_najentusAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_lady_vashj::boss_lady_vashjAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_ghazan, boss_hungarfen, boss_the_black_stalker, boss_gruul, boss_high_king_maulgar, boss_the_maker, boss_omor_the_unscarred, boss_watchkeeper_gargolmar, boss_magtheridon, boss_grand_warlock_nethekurse, boss_warbringer_omrogg, boss_warchief_kargath_bladefist, npc_warden_mellichar::npc_warden_mellicharAI, boss_wrath_scryer_soccothrates, boss_alar::boss_alarAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_kaelthas::boss_kaelthasAI, boss_void_reaver::boss_void_reaverAI, boss_illidari_council::boss_illidari_councilAI, and boss_vazruden_the_herald.
{
    if (!UpdateVictim())
    {
        return;
    }
    events.Update(diff);
    scheduler.Update(diff);
    if (me->HasUnitState(UNIT_STATE_CASTING))
    {
        return;
    }
    while (uint32 const eventId = events.ExecuteEvent())
    {
        ExecuteEvent(eventId);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
    }
    DoMeleeAttackIfReady();
}
References UnitAI::DoMeleeAttackIfReady(), ExecuteEvent(), Unit::HasUnitState(), ScriptedAI::me, scheduler, UNIT_STATE_CASTING, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_bossId
uint32 const BossAI::_bossId private
Referenced by _JustDied(), _JustEngagedWith(), _Reset(), and CanRespawn().
_healthCheckEvents
std::list<HealthCheckEventData> BossAI::_healthCheckEvents private
Referenced by _JustDied(), _Reset(), DamageTaken(), and ScheduleHealthCheckEvent().
events
EventMap BossAI::events protected
instance
InstanceScript* const BossAI::instance
Referenced by _JustDied(), _JustEngagedWith(), _Reset(), boss_hakkar::boss_hakkarAI::ApplyHakkarPowerStacks(), boss_felmyst::boss_felmystAI::boss_felmystAI(), boss_prince_valanar_icc::boss_prince_valanarAI::boss_prince_valanarAI(), boss_victor_nefarius::boss_victor_nefariusAI::boss_victor_nefariusAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothrates(), BossAI(), boss_majordomo::boss_majordomoAI::CanAIAttack(), boss_pathaleon_the_calculator::CanAIAttack(), boss_keristrasza::boss_keristraszaAI::CanRemovePrison(), CanRespawn(), boss_moira_bronzebeardAI::CastOnEmperorIfPossible(), boss_prince_valanar_icc::boss_prince_valanarAI::CheckRoom(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::CleanAuras(), boss_sartharion_dragonAI::ClearInstance(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ClearInstance(), boss_kalecgos::boss_kalecgosAI::ClearPlayerAuras(), boss_prince_valanar_icc::boss_prince_valanarAI::DamageDealt(), boss_attumen::DamageTaken(), boss_sindragosa::boss_sindragosaAI::DamageTaken(), boss_buru::DamageTaken(), boss_halion::boss_halionAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken(), boss_bug_trio::DamageTaken(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), boss_taldaram::DoAction(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::DoAction(), boss_sindragosa::boss_sindragosaAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), boss_broggok::DoAction(), boss_pathaleon_the_calculator::DoAction(), boss_kalecgos::boss_kalecgosAI::DoAction(), boss_onyxia::DoAction(), boss_hadronox::boss_hadronoxAI::DoAction(), boss_illidari_council::boss_illidari_councilAI::DoAction(), boss_razorgore::boss_razorgoreAI::DoChangePhase(), boss_bug_trio::EnterCombatWithTrio(), boss_gyth::boss_gythAI::EnterEvadeMode(), boss_rend_blackhand::boss_rend_blackhandAI::EnterEvadeMode(), boss_attumen::EnterEvadeMode(), boss_sacrolash::boss_sacrolashAI::EnterEvadeMode(), boss_alythess::boss_alythessAI::EnterEvadeMode(), boss_buru::EnterEvadeMode(), boss_amanitar::EnterEvadeMode(), boss_halion::boss_halionAI::EnterEvadeMode(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterEvadeMode(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterEvadeMode(), boss_festergut::boss_festergutAI::EnterEvadeMode(), boss_rotface::boss_rotfaceAI::EnterEvadeMode(), boss_sindragosa::boss_sindragosaAI::EnterEvadeMode(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), boss_illidan_stormrage::boss_illidan_stormrageAI::EnterEvadeMode(), boss_ouro::EnterEvadeMode(), boss_bug_trio::EvadeAllBosses(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_twinemperorsAI::GetTwin(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::GoToMinchar(), boss_netherspite::HandleDoors(), boss_warbringer_omrogg::HandleHeadTalk(), boss_nightbane::HandleTerraceDoors(), boss_malchezaar::Initialize(), boss_urok_doomhowl::boss_urok_doomhowlAI::InitializeAI(), boss_majordomo::boss_majordomoAI::InitializeAI(), boss_taldaram::InitializeAI(), boss_ambassador_hellmaw::InitializeAI(), boss_warchief_kargath_bladefist::InitializeAI(), boss_aeonus::IsSummonedBy(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::JustDied(), boss_gyth::boss_gythAI::JustDied(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::JustDied(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::JustDied(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::JustDied(), boss_victor_nefarius::boss_victor_nefariusAI::JustDied(), boss_razorgore::boss_razorgoreAI::JustDied(), boss_nightbane::JustDied(), boss_malchezaar::JustDied(), boss_shade_of_aran::JustDied(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::JustDied(), boss_baroness_anastari::boss_baroness_anastariAI::JustDied(), boss_sacrolash::boss_sacrolashAI::JustDied(), boss_alythess::boss_alythessAI::JustDied(), boss_akilzon::boss_akilzonAI::JustDied(), boss_mandokir::boss_mandokirAI::JustDied(), boss_thekal::boss_thekalAI::JustDied(), boss_lieutenant_drake::JustDied(), boss_rajaxx::JustDied(), boss_eye_of_cthun::JustDied(), boss_viscidus::JustDied(), boss_amanitar::JustDied(), boss_sartharion_dragonAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_festergut::boss_festergutAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), boss_sindragosa::boss_sindragosaAI::JustDied(), boss_sister_svalna::boss_sister_svalnaAI::JustDied(), boss_talon_king_ikiss::JustDied(), boss_hydromancer_thespia::JustDied(), boss_warlord_kalithresh::JustDied(), boss_high_king_maulgar::JustDied(), boss_kelidan_the_breaker::JustDied(), boss_the_maker::JustDied(), boss_dalliah_the_doomsayer::JustDied(), boss_lord_valthalak::boss_lord_valthalakAI::JustDied(), boss_moroes::JustDied(), boss_brutallus::boss_brutallusAI::JustDied(), boss_felmyst::boss_felmystAI::JustDied(), boss_buru::JustDied(), boss_kurinnaxx::JustDied(), boss_bug_trio::JustDied(), boss_cthun::JustDied(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_novos::boss_novosAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_shade_of_akama::boss_shade_of_akamaAI::JustDied(), boss_warchief_kargath_bladefist::JustDied(), boss_sartharion_dragonAI::JustEngagedWith(), boss_magmus::boss_magmusAI::JustEngagedWith(), boss_razorgore::boss_razorgoreAI::JustEngagedWith(), boss_nightbane::JustEngagedWith(), boss_malchezaar::JustEngagedWith(), boss_shade_of_aran::JustEngagedWith(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::JustEngagedWith(), boss_akilzon::boss_akilzonAI::JustEngagedWith(), boss_hakkar::boss_hakkarAI::JustEngagedWith(), boss_volazj::JustEngagedWith(), boss_anub_arak::boss_anub_arakAI::JustEngagedWith(), boss_lord_marrowgar::JustEngagedWith(), boss_sister_svalna::boss_sister_svalnaAI::JustEngagedWith(), boss_kelidan_the_breaker::JustEngagedWith(), boss_the_maker::JustEngagedWith(), boss_dalliah_the_doomsayer::JustEngagedWith(), boss_sartharion::boss_sartharionAI::JustEngagedWith(), boss_the_lich_king::boss_the_lich_kingAI::JustEngagedWith(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustEngagedWith(), boss_sacrolash::boss_sacrolashAI::JustEngagedWith(), boss_alythess::boss_alythessAI::JustEngagedWith(), boss_onyxia::JustEngagedWith(), boss_buru::JustEngagedWith(), boss_halion::boss_halionAI::JustEngagedWith(), boss_trollgore::boss_trollgoreAI::JustEngagedWith(), boss_prince_valanar_icc::boss_prince_valanarAI::JustEngagedWith(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustEngagedWith(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustEngagedWith(), boss_festergut::boss_festergutAI::JustEngagedWith(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustEngagedWith(), boss_professor_putricide::boss_professor_putricideAI::JustEngagedWith(), boss_rotface::boss_rotfaceAI::JustEngagedWith(), boss_sindragosa::boss_sindragosaAI::JustEngagedWith(), boss_warchief_kargath_bladefist::JustEngagedWith(), boss_majordomo::boss_majordomoAI::JustReachedHome(), boss_arlokk::boss_arlokkAI::JustReachedHome(), boss_aeonus::JustReachedHome(), boss_prince_valanar_icc::boss_prince_valanarAI::JustReachedHome(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustReachedHome(), boss_festergut::boss_festergutAI::JustReachedHome(), boss_lord_marrowgar::JustReachedHome(), boss_professor_putricide::boss_professor_putricideAI::JustReachedHome(), boss_rotface::boss_rotfaceAI::JustReachedHome(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustReachedHome(), boss_attumen::JustSummoned(), boss_eye_of_cthun::JustSummoned(), boss_sartharion_dragonAI::JustSummoned(), boss_midnight::KilledUnit(), boss_mandokir::boss_mandokirAI::KilledUnit(), boss_mandokir::boss_mandokirAI::MovementInform(), boss_bug_trio::MovementInform(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::MovementInform(), boss_professor_putricide::boss_professor_putricideAI::MovementInform(), boss_lady_vashj::boss_lady_vashjAI::MovementInform(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::OpenDoors(), boss_kaelthas::boss_kaelthasAI::PrepareAdvisors(), boss_magmus::boss_magmusAI::Reset(), boss_gyth::boss_gythAI::Reset(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_razorgore::boss_razorgoreAI::Reset(), boss_majordomo::boss_majordomoAI::Reset(), boss_nightbane::Reset(), boss_shade_of_aran::Reset(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::Reset(), boss_baroness_anastari::boss_baroness_anastariAI::Reset(), boss_felmyst::boss_felmystAI::Reset(), boss_akilzon::boss_akilzonAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), boss_thekal::boss_thekalAI::Reset(), boss_onyxia::Reset(), boss_bug_trio::Reset(), boss_ouro::Reset(), boss_volazj::Reset(), boss_anub_arak::boss_anub_arakAI::Reset(), boss_sartharion::boss_sartharionAI::Reset(), boss_sartharion_dragonAI::Reset(), boss_general_zarithrian::boss_general_zarithrianAI::Reset(), boss_novos::boss_novosAI::Reset(), boss_prince_valanar_icc::boss_prince_valanarAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), boss_lord_marrowgar::Reset(), boss_professor_putricide::boss_professor_putricideAI::Reset(), boss_the_lich_king::boss_the_lich_kingAI::Reset(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset(), boss_warlord_kalithresh::Reset(), boss_kelidan_the_breaker::Reset(), boss_the_maker::Reset(), boss_magtheridon::Reset(), boss_grand_warlock_nethekurse::Reset(), boss_warchief_kargath_bladefist::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), boss_dalliah_the_doomsayer::Reset(), boss_wrath_scryer_soccothrates::Reset(), boss_pathaleon_the_calculator::Reset(), boss_sartharion::boss_sartharionAI::RespawnDragons(), boss_thekal::boss_thekalAI::ReviveZealot(), boss_magtheridon::ScheduleCombatEvents(), boss_ayamiss::ScheduleTasks(), boss_cthun::ScheduleTasks(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SetData(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SetGate(), boss_kaelthas::boss_kaelthasAI::SetRoomState(), boss_victor_nefarius::boss_victor_nefariusAI::sGossipSelect(), boss_onyxia::SpellHitTarget(), boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::SummonedCreatureDies(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP1(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), and boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateRunes().
scheduler
TaskScheduler BossAI::scheduler protected
Referenced by _JustDied(), _Reset(), boss_anzu::boss_anzu(), boss_apothecary_hummel::boss_apothecary_hummelAI::boss_apothecary_hummelAI(), boss_blackheart_the_inciter::boss_blackheart_the_inciter(), boss_captain_skarloc::boss_captain_skarloc(), boss_darkweaver_syth::boss_darkweaver_syth(), boss_epoch_hunter::boss_epoch_hunter(), boss_exarch_maladaar::boss_exarch_maladaar(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokill(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_hand(), boss_ghazan::boss_ghazan(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurse(), boss_harbinger_skyriss::boss_harbinger_skyriss(), boss_high_king_maulgar::boss_high_king_maulgar(), boss_kelidan_the_breaker::boss_kelidan_the_breaker(), boss_lieutenant_drake::boss_lieutenant_drake(), boss_magtheridon::boss_magtheridon(), boss_maiden_of_virtue::boss_maiden_of_virtue(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitus(), boss_mekgineer_steamrigger::boss_mekgineer_steamrigger(), boss_mennu_the_betrayer::boss_mennu_the_betrayer(), boss_moroes::boss_moroes(), boss_murmur::boss_murmur(), boss_nethermancer_sepethrea::boss_nethermancer_sepethrea(), boss_nexusprince_shaffar::boss_nexusprince_shaffar(), boss_nightbane::boss_nightbane(), boss_omor_the_unscarred::boss_omor_the_unscarred(), boss_pandemonius::boss_pandemonius(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculator(), boss_quagmirran::boss_quagmirran(), boss_rokmar_the_crackler::boss_rokmar_the_crackler(), boss_shade_of_aran::boss_shade_of_aran(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcher(), boss_swamplord_muselek::boss_swamplord_muselek(), boss_talon_king_ikiss::boss_talon_king_ikiss(), boss_tavarok::boss_tavarok(), boss_terestian_illhoof::boss_terestian_illhoof(), boss_the_black_stalker::boss_the_black_stalker(), boss_the_maker::boss_the_maker(), boss_thorngrin_the_tender::boss_thorngrin_the_tender(), boss_warbringer_omrogg::boss_warbringer_omrogg(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefist(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmar(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothrates(), boss_zereketh_the_unbound::boss_zereketh_the_unbound(), boss_ayamiss::DamageTaken(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), boss_broggok::DoAction(), boss_magtheridon::DoAction(), boss_grand_warlock_nethekurse::DoAction(), boss_pathaleon_the_calculator::DoAction(), boss_moroes::InitializeGuests(), boss_grand_warlock_nethekurse::IntroRP(), boss_attumen::IsSummonedBy(), boss_malchezaar::JustEngagedWith(), boss_shade_of_aran::JustEngagedWith(), boss_terestian_illhoof::JustEngagedWith(), boss_epoch_hunter::JustEngagedWith(), boss_lieutenant_drake::JustEngagedWith(), boss_aeonus::JustEngagedWith(), boss_chrono_lord_deja::JustEngagedWith(), boss_temporus::JustEngagedWith(), boss_exarch_maladaar::JustEngagedWith(), boss_shirrak_the_dead_watcher::JustEngagedWith(), boss_nexusprince_shaffar::JustEngagedWith(), boss_tavarok::JustEngagedWith(), boss_anzu::JustEngagedWith(), boss_darkweaver_syth::JustEngagedWith(), boss_talon_king_ikiss::JustEngagedWith(), boss_ambassador_hellmaw::JustEngagedWith(), boss_blackheart_the_inciter::JustEngagedWith(), boss_grandmaster_vorpil::JustEngagedWith(), boss_mennu_the_betrayer::JustEngagedWith(), boss_quagmirran::JustEngagedWith(), boss_rokmar_the_crackler::JustEngagedWith(), boss_hydromancer_thespia::JustEngagedWith(), boss_mekgineer_steamrigger::JustEngagedWith(), boss_warlord_kalithresh::JustEngagedWith(), boss_ghazan::JustEngagedWith(), boss_swamplord_muselek::JustEngagedWith(), boss_the_black_stalker::JustEngagedWith(), boss_gruul::JustEngagedWith(), boss_high_king_maulgar::JustEngagedWith(), boss_kelidan_the_breaker::JustEngagedWith(), boss_the_maker::JustEngagedWith(), boss_omor_the_unscarred::JustEngagedWith(), boss_watchkeeper_gargolmar::JustEngagedWith(), boss_dalliah_the_doomsayer::JustEngagedWith(), boss_harbinger_skyriss::JustEngagedWith(), boss_zereketh_the_unbound::JustEngagedWith(), boss_commander_sarannis::JustEngagedWith(), boss_high_botanist_freywinn::JustEngagedWith(), boss_laj::JustEngagedWith(), boss_thorngrin_the_tender::JustEngagedWith(), boss_warp_splinter::JustEngagedWith(), boss_gatewatcher_gyrokill::JustEngagedWith(), boss_gatewatcher_iron_hand::JustEngagedWith(), boss_mechano_lord_capacitus::JustEngagedWith(), boss_nethermancer_sepethrea::JustEngagedWith(), boss_pathaleon_the_calculator::JustEngagedWith(), boss_curator::JustEngagedWith(), boss_maiden_of_virtue::JustEngagedWith(), boss_midnight::JustEngagedWith(), boss_moroes::JustEngagedWith(), boss_netherspite::JustEngagedWith(), boss_pandemonius::JustEngagedWith(), boss_murmur::JustEngagedWith(), boss_magtheridon::JustEngagedWith(), boss_grand_warlock_nethekurse::JustEngagedWith(), boss_porung::JustEngagedWith(), boss_warchief_kargath_bladefist::JustEngagedWith(), boss_gruul::KilledUnit(), boss_high_king_maulgar::KilledUnit(), boss_omor_the_unscarred::KilledUnit(), boss_watchkeeper_gargolmar::KilledUnit(), boss_magtheridon::KilledUnit(), boss_moroes::KilledUnit(), boss_ayamiss::MovementInform(), boss_warchief_kargath_bladefist::MovementInform(), boss_malchezaar::Reset(), boss_ayamiss::Reset(), boss_eye_of_cthun::Reset(), boss_cthun::Reset(), boss_exarch_maladaar::Reset(), boss_anzu::Reset(), boss_talon_king_ikiss::Reset(), boss_high_king_maulgar::Reset(), boss_omor_the_unscarred::Reset(), boss_watchkeeper_gargolmar::Reset(), boss_magtheridon::Reset(), boss_magtheridon::ScheduleCombatEvents(), boss_nightbane::ScheduleFly(), boss_nightbane::ScheduleGround(), boss_commander_sarannis::ScheduleReinforcements(), boss_eye_of_cthun::ScheduleTask(), boss_attumen::ScheduleTasks(), boss_ayamiss::ScheduleTasks(), boss_cthun::ScheduleTasks(), boss_grand_warlock_nethekurse::SetData(), boss_terestian_illhoof::SpellHit(), boss_cthun::SummonedCreatureDies(), boss_warchief_kargath_bladefist::SummonedCreatureDies(), boss_netherspite::SwitchToBanishPhase(), boss_netherspite::SwitchToPortalPhase(), boss_nightbane::TakeOff(), boss_shade_of_aran::TriggerArcaneCooldown(), boss_shade_of_aran::TriggerFireCooldown(), boss_shade_of_aran::TriggerFrostCooldown(), UpdateAI(), boss_curator::UpdateAI(), boss_midnight::UpdateAI(), boss_moroes::UpdateAI(), boss_netherspite::UpdateAI(), boss_nightbane::UpdateAI(), boss_terestian_illhoof::UpdateAI(), boss_apothecary_hummel::boss_apothecary_hummelAI::UpdateAI(), boss_epoch_hunter::UpdateAI(), boss_lieutenant_drake::UpdateAI(), boss_ayamiss::UpdateAI(), boss_cthun::UpdateAI(), boss_exarch_maladaar::UpdateAI(), boss_nexusprince_shaffar::UpdateAI(), boss_anzu::UpdateAI(), boss_ambassador_hellmaw::UpdateAI(), boss_blackheart_the_inciter::UpdateAI(), boss_ghazan::UpdateAI(), boss_the_black_stalker::UpdateAI(), boss_gruul::UpdateAI(), boss_high_king_maulgar::UpdateAI(), boss_the_maker::UpdateAI(), boss_omor_the_unscarred::UpdateAI(), boss_watchkeeper_gargolmar::UpdateAI(), boss_magtheridon::UpdateAI(), boss_grand_warlock_nethekurse::UpdateAI(), and boss_warchief_kargath_bladefist::UpdateAI().
summons
SummonList BossAI::summons protected
Referenced by _JustDied(), _Reset(), boss_volazj::CheckPhaseMinions(), boss_sartharion_dragonAI::ClearInstance(), boss_sartharion::boss_sartharionAI::DamageTaken(), boss_illidan_stormrage::boss_illidan_stormrageAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_victor_nefarius::boss_victor_nefariusAI::DoAction(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), boss_taldaram::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), boss_drakkari_colossus::boss_drakkari_colossusAI::DoAction(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_krik_thir::boss_krik_thirAI::GetData(), boss_professor_putricide::boss_professor_putricideAI::GetData(), boss_moroes::GetRandomGuest(), boss_moroes::InitializeGuests(), boss_sacrolash::boss_sacrolashAI::JustDied(), boss_alythess::boss_alythessAI::JustDied(), boss_viscidus::JustDied(), boss_sartharion_dragonAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustDied(), boss_malchezaar::JustEngagedWith(), boss_sindragosa::boss_sindragosaAI::JustEngagedWith(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustEngagedWith(), boss_ossirian::JustSummoned(), JustSummoned(), boss_gyth::boss_gythAI::JustSummoned(), boss_rend_blackhand::boss_rend_blackhandAI::JustSummoned(), boss_razorgore::boss_razorgoreAI::JustSummoned(), boss_curator::JustSummoned(), boss_nightbane::JustSummoned(), boss_sacrolash::boss_sacrolashAI::JustSummoned(), boss_felmyst::boss_felmystAI::JustSummoned(), boss_muru::boss_muruAI::JustSummoned(), boss_hazzarah::JustSummoned(), boss_isalien::JustSummoned(), boss_onyxia::JustSummoned(), boss_eye_of_cthun::JustSummoned(), boss_amanitar::JustSummoned(), boss_jedoga_shadowseeker::JustSummoned(), boss_taldaram::JustSummoned(), boss_anub_arak::boss_anub_arakAI::JustSummoned(), boss_hadronox::boss_hadronoxAI::JustSummoned(), boss_krik_thir::boss_krik_thirAI::JustSummoned(), boss_sartharion::boss_sartharionAI::JustSummoned(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustSummoned(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustSummoned(), boss_general_zarithrian::boss_general_zarithrianAI::JustSummoned(), boss_halion::boss_halionAI::JustSummoned(), boss_novos::boss_novosAI::JustSummoned(), boss_trollgore::boss_trollgoreAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_slad_ran::boss_slad_ranAI::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_professor_putricide::boss_professor_putricideAI::JustSummoned(), boss_rotface::boss_rotfaceAI::JustSummoned(), boss_sindragosa::boss_sindragosaAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_anomalus::boss_anomalusAI::JustSummoned(), boss_magus_telestra::boss_magus_telestraAI::JustSummoned(), boss_ormorok::boss_ormorokAI::JustSummoned(), boss_grandmaster_vorpil::JustSummoned(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::JustSummoned(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustSummoned(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustSummoned(), boss_supremus::boss_supremusAI::JustSummoned(), boss_teron_gorefiend::boss_teron_gorefiendAI::JustSummoned(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustSummoned(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustSummoned(), boss_lady_vashj::boss_lady_vashjAI::JustSummoned(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustSummoned(), boss_the_lurker_below::boss_the_lurker_belowAI::JustSummoned(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::JustSummoned(), boss_omor_the_unscarred::JustSummoned(), boss_vazruden_the_herald::JustSummoned(), boss_warchief_kargath_bladefist::JustSummoned(), npc_warden_mellichar::npc_warden_mellicharAI::JustSummoned(), boss_alar::boss_alarAI::JustSummoned(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::JustSummoned(), boss_kaelthas::boss_kaelthasAI::JustSummoned(), boss_nethermancer_sepethrea::JustSummoned(), boss_broggok::JustSummoned(), boss_ayamiss::JustSummoned(), boss_illidan_stormrage::boss_illidan_stormrageAI::MovementInform(), boss_jedoga_shadowseeker::MovementInform(), boss_the_lich_king::boss_the_lich_kingAI::MovementInform(), boss_kaelthas::boss_kaelthasAI::PrepareAdvisors(), boss_gyth::boss_gythAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_razorgore::boss_razorgoreAI::Reset(), boss_majordomo::boss_majordomoAI::Reset(), boss_isalien::Reset(), boss_hadronox::boss_hadronoxAI::Reset(), boss_prince_valanar_icc::boss_prince_valanarAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset(), boss_the_lurker_below::boss_the_lurker_belowAI::Reset(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), boss_vazruden_the_herald::SetData(), boss_kaelthas::boss_kaelthasAI::SetData(), boss_the_lich_king::boss_the_lich_kingAI::SpellHitTarget(), boss_taldaram::SpellHitTarget(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonChannelers(), boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn(), SummonedCreatureDespawn(), boss_ossirian::SummonedCreatureDespawn(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDespawn(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::SummonedCreatureDespawn(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonedCreatureDespawn(), boss_illidan_stormrage::boss_illidan_stormrageAI::SummonedCreatureDespawn(), boss_supremus::boss_supremusAI::SummonedCreatureDespawn(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::SummonedCreatureDespawn(), boss_vazruden_the_herald::SummonedCreatureDespawn(), SummonedCreatureDespawnAll(), boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDies(), boss_moam::SummonedCreatureDies(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), boss_victor_nefarius::boss_victor_nefariusAI::SummonedCreatureDies(), boss_ragnaros::boss_ragnarosAI::SummonedCreatureDies(), boss_hazzarah::SummonedCreatureDies(), boss_krik_thir::boss_krik_thirAI::SummonedCreatureDies(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDies(), boss_anzu::SummonedCreatureDies(), boss_illidan_stormrage::boss_illidan_stormrageAI::SummonedCreatureDies(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::SummonedCreatureDies(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::SummonedCreatureDies(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonedCreatureDies(), boss_the_black_stalker::SummonedCreatureDies(), boss_vazruden_the_herald::SummonedCreatureDies(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), boss_high_botanist_freywinn::SummonedCreatureDies(), boss_kaelthas::boss_kaelthasAI::SummonedCreatureDies(), boss_viscidus::SummonedCreatureDies(), boss_jedoga_shadowseeker::SummonedCreatureDies(), boss_sartharion::boss_sartharionAI::SummonLavaWaves(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), and boss_vazruden_the_herald::UpdateAI().