AzerothCore: AllSpellScript Class Reference
AllSpellScript Class Reference
#include "AllSpellScript.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnCalcMaxDuration (Aura const *, int32 &)
virtual bool CanModAuraEffectDamageDone (AuraEffect const *, Unit *, AuraApplication const *, uint8, bool)
virtual bool CanModAuraEffectModDamagePercentDone (AuraEffect const *, Unit *, AuraApplication const *, uint8, bool)
virtual void OnSpellCheckCast (Spell *, bool, SpellCastResult &)
virtual bool CanPrepare (Spell *, SpellCastTargets const *, AuraEffect const *)
virtual bool CanScalingEverything (Spell *)
virtual bool CanSelectSpecTalent (Spell *)
virtual void OnScaleAuraUnitAdd (Spell *, Unit *, uint32, bool, bool, uint8, TargetInfo &)
virtual void OnRemoveAuraScaleTargets (Spell *, TargetInfo &, uint8, bool &)
virtual void OnBeforeAuraRankForLevel (SpellInfo const *, SpellInfo const *, uint8)
virtual void OnDummyEffect (WorldObject *, uint32, SpellEffIndex, GameObject *)
This hook called after spell dummy effect.
virtual void OnDummyEffect (WorldObject *, uint32, SpellEffIndex, Creature *)
This hook called after spell dummy effect.
virtual void OnDummyEffect (WorldObject *, uint32, SpellEffIndex, Item *)
This hook called after spell dummy effect.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
AllSpellScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
AllSpellScript()
AllSpellScript::AllSpellScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<AllSpellScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanModAuraEffectDamageDone()
virtual bool AllSpellScript::CanModAuraEffectDamageDone (AuraEffect const * , Unit * , AuraApplication const * , uint8 , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::CanModAuraEffectDamageDone().
CanModAuraEffectModDamagePercentDone()
virtual bool AllSpellScript::CanModAuraEffectModDamagePercentDone (AuraEffect const * , Unit * , AuraApplication const * , uint8 , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::CanModAuraEffectModDamagePercentDone().
CanPrepare()
virtual bool AllSpellScript::CanPrepare (Spell * , SpellCastTargets const * , AuraEffect const *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanPrepare().
CanScalingEverything()
virtual bool AllSpellScript::CanScalingEverything (Spell *) inline virtual
{ return false; }
Referenced by ScriptMgr::CanScalingEverything().
CanSelectSpecTalent()
virtual bool AllSpellScript::CanSelectSpecTalent (Spell *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanSelectSpecTalent().
IsDatabaseBound()
bool AllSpellScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
OnBeforeAuraRankForLevel()
virtual void AllSpellScript::OnBeforeAuraRankForLevel (SpellInfo const * , SpellInfo const * , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeAuraRankForLevel().
OnCalcMaxDuration()
virtual void AllSpellScript::OnCalcMaxDuration (Aura const * , int32 &) inline virtual
{ }
Referenced by ScriptMgr::OnCalcMaxDuration().
OnDummyEffect() [1/3]
virtual void AllSpellScript::OnDummyEffect (WorldObject * , uint32 , SpellEffIndex , Creature *) inline virtual
This hook called after spell dummy effect.
Parameters
caster Contains information about the WorldObject
spellID Contains information about the spell id
effIndex Contains information about the SpellEffIndex
creatureTarget Contains information about the Creature
{ }
OnDummyEffect() [2/3]
virtual void AllSpellScript::OnDummyEffect (WorldObject * , uint32 , SpellEffIndex , GameObject *) inline virtual
This hook called after spell dummy effect.
Parameters
caster Contains information about the WorldObject
spellID Contains information about the spell id
effIndex Contains information about the SpellEffIndex
gameObjTarget Contains information about the GameObject
{ }
Referenced by ScriptMgr::OnDummyEffect().
OnDummyEffect() [3/3]
virtual void AllSpellScript::OnDummyEffect (WorldObject * , uint32 , SpellEffIndex , Item *) inline virtual
This hook called after spell dummy effect.
Parameters
caster Contains information about the WorldObject
spellID Contains information about the spell id
effIndex Contains information about the SpellEffIndex
itemTarget Contains information about the Item
{ }
OnRemoveAuraScaleTargets()
virtual void AllSpellScript::OnRemoveAuraScaleTargets (Spell * , TargetInfo & , uint8 , bool &) inline virtual
{ }
Referenced by ScriptMgr::OnRemoveAuraScaleTargets().
OnScaleAuraUnitAdd()
virtual void AllSpellScript::OnScaleAuraUnitAdd (Spell * , Unit * , uint32 , bool , bool , uint8 , TargetInfo &) inline virtual
{ }
Referenced by ScriptMgr::OnScaleAuraUnitAdd().
OnSpellCheckCast()
virtual void AllSpellScript::OnSpellCheckCast (Spell * , bool , SpellCastResult &) inline virtual
{ }
Referenced by ScriptMgr::OnSpellCheckCast().