AzerothCore: Acore::Time Namespace Reference
Acore::Time Namespace Reference
Functions
template<class T >
AC_COMMON_API uint32 TimeStringTo (std::string_view timeString)
template<class T >
AC_COMMON_API std::string ToTimeString (uint64 durationTime, TimeOutput timeOutput=TimeOutput::Seconds, TimeFormat timeFormat=TimeFormat::ShortText)
template<class T >
AC_COMMON_API std::string ToTimeString (std::string_view durationTime, TimeOutput timeOutput=TimeOutput::Seconds, TimeFormat timeFormat=TimeFormat::ShortText)
AC_COMMON_API std::string ToTimeString (Microseconds durationTime, TimeOutput timeOutput=TimeOutput::Seconds, TimeFormat timeFormat=TimeFormat::ShortText)
AC_COMMON_API time_t LocalTimeToUTCTime (time_t time)
AC_COMMON_API time_t GetLocalHourTimestamp (time_t time, uint8 hour, bool onlyAfterTime=true)
AC_COMMON_API std::tm TimeBreakdown (time_t t=0)
AC_COMMON_API std::string TimeToTimestampStr (Seconds time=0s, std::string_view fmt={})
AC_COMMON_API std::string TimeToHumanReadable (Seconds time=0s, std::string_view fmt={})
AC_COMMON_API time_t GetNextTimeWithDayAndHour (int8 dayOfWeek, int8 hour)
AC_COMMON_API time_t GetNextTimeWithMonthAndHour (int8 month, int8 hour)
AC_COMMON_API uint32 GetSeconds (Seconds time=0s)
AC_COMMON_API uint32 GetMinutes (Seconds time=0s)
AC_COMMON_API uint32 GetHours (Seconds time=0s)
AC_COMMON_API uint32 GetDayInWeek (Seconds time=0s)
AC_COMMON_API uint32 GetDayInMonth (Seconds time=0s)
AC_COMMON_API uint32 GetDayInYear (Seconds time=0s)
AC_COMMON_API uint32 GetMonth (Seconds time=0s)
AC_COMMON_API uint32 GetYear (Seconds time=0s)
Function Documentation
GetDayInMonth()
uint32 Acore::Time::GetDayInMonth (Seconds time = 0s)
{
    if (time == 0s)
    {
        time = GetEpochTime();
    }
    return TimeBreakdown(time.count()).tm_mday;
}
References GetEpochTime(), and TimeBreakdown().
GetDayInWeek()
uint32 Acore::Time::GetDayInWeek (Seconds time = 0s)
{
    if (time == 0s)
    {
        time = GetEpochTime();
    }
    return TimeBreakdown(time.count()).tm_wday;
}
References GetEpochTime(), and TimeBreakdown().
GetDayInYear()
uint32 Acore::Time::GetDayInYear (Seconds time = 0s)
{
    if (time == 0s)
    {
        time = GetEpochTime();
    }
    return TimeBreakdown(time.count()).tm_yday;
}
References GetEpochTime(), and TimeBreakdown().
Referenced by Weather::ReGenerate().
GetHours()
uint32 Acore::Time::GetHours (Seconds time = 0s)
{
    if (time == 0s)
    {
        time = GetEpochTime();
    }
    return TimeBreakdown(time.count()).tm_hour;
}
References GetEpochTime(), and TimeBreakdown().
GetLocalHourTimestamp()
time_t Acore::Time::GetLocalHourTimestamp (time_t time, uint8 hour, bool onlyAfterTime = true)
{
    tm timeLocal = TimeBreakdown(time);
    timeLocal.tm_hour = 0;
    timeLocal.tm_min = 0;
    timeLocal.tm_sec = 0;
    time_t midnightLocal = mktime(&timeLocal);
    time_t hourLocal = midnightLocal + hour * HOUR;
    if (onlyAfterTime && hourLocal <= time)
    {
        hourLocal += DAY;
    }
    return hourLocal;
}
References DAY, HOUR, and TimeBreakdown().
GetMinutes()
uint32 Acore::Time::GetMinutes (Seconds time = 0s)
{
    if (time == 0s)
    {
        time = GetEpochTime();
    }
    return TimeBreakdown(time.count()).tm_min;
}
References GetEpochTime(), and TimeBreakdown().
Referenced by npc_dark_iron_attack_generator::AllowStart().
GetMonth()
uint32 Acore::Time::GetMonth (Seconds time = 0s)
{
    if (time == 0s)
    {
        time = GetEpochTime();
    }
    return TimeBreakdown(time.count()).tm_mon;
}
References GetEpochTime(), and TimeBreakdown().
Referenced by Player::_LoadBrewOfTheMonth().
GetNextTimeWithDayAndHour()
time_t Acore::Time::GetNextTimeWithDayAndHour (int8 dayOfWeek, int8 hour)
{
    if (hour < 0 || hour > 23)
    {
        hour = 0;
    }
    tm localTm = TimeBreakdown();
    localTm.tm_hour = hour;
    localTm.tm_min = 0;
    localTm.tm_sec = 0;
    if (dayOfWeek < 0 || dayOfWeek > 6)
    {
        dayOfWeek = (localTm.tm_wday + 1) % 7;
    }
    uint32 add;
    if (localTm.tm_wday >= dayOfWeek)
    {
        add = (7 - (localTm.tm_wday - dayOfWeek)) * DAY;
    }
    else
    {
        add = (dayOfWeek - localTm.tm_wday) * DAY;
    }
    return mktime(&localTm) + add;
}
References DAY, and TimeBreakdown().
Referenced by World::CalendarDeleteOldEvents(), World::InitCalendarOldEventsDeletionTime(), World::InitDailyQuestResetTime(), World::InitGuildResetTime(), World::InitMonthlyQuestResetTime(), World::InitRandomBGResetTime(), World::InitWeeklyQuestResetTime(), World::ResetDailyQuests(), World::ResetGuildCap(), World::ResetRandomBG(), and World::ResetWeeklyQuests().
GetNextTimeWithMonthAndHour()
time_t Acore::Time::GetNextTimeWithMonthAndHour (int8 month, int8 hour)
{
    if (hour < 0 || hour > 23)
    {
        hour = 0;
    }
    tm localTm = TimeBreakdown();
    localTm.tm_mday = 1;
    localTm.tm_hour = hour;
    localTm.tm_min = 0;
    localTm.tm_sec = 0;
    if (month < 0 || month > 11)
    {
        month = (localTm.tm_mon + 1) % 12;
        if (!month)
        {
            localTm.tm_year += 1;
        }
    }
    else if (localTm.tm_mon >= month)
    {
        localTm.tm_year += 1;
    }
    localTm.tm_mon = month;
    return mktime(&localTm);
}
References TimeBreakdown().
Referenced by World::ResetMonthlyQuests().
GetSeconds()
uint32 Acore::Time::GetSeconds (Seconds time = 0s)
{
    if (time == 0s)
    {
        time = GetEpochTime();
    }
    return TimeBreakdown(time.count()).tm_sec;
}
References GetEpochTime(), and TimeBreakdown().
GetYear()
uint32 Acore::Time::GetYear (Seconds time = 0s)
{
    if (time == 0s)
    {
        time = GetEpochTime();
    }
    return TimeBreakdown(time.count()).tm_year;
}
References GetEpochTime(), and TimeBreakdown().
LocalTimeToUTCTime()
time_t Acore::Time::LocalTimeToUTCTime (time_t time)
{
#if AC_PLATFORM == AC_PLATFORM_WINDOWS
    return time + _timezone;
#else
    return time + timezone;
#endif
}
TimeBreakdown()
std::tm Acore::Time::TimeBreakdown (time_t t = 0)
{
    if (!time)
    {
        time = GetEpochTime().count();
    }
    std::tm timeLocal;
    localtime_r(&time, &timeLocal);
    return timeLocal;
}
References GetEpochTime(), and localtime_r().
Referenced by ByteBuffer::AppendPackedTime(), GetDayInMonth(), GetDayInWeek(), GetDayInYear(), GetHours(), GetLocalHourTimestamp(), GetMinutes(), GetMonth(), GetNextTimeWithDayAndHour(), GetNextTimeWithMonthAndHour(), GetSeconds(), GetYear(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListHelper(), ban_commandscript::HandleBanListIPCommand(), go_firework_show::InitShow(), AchievementCriteriaData::Meets(), GameEventMgr::SetHolidayEventTime(), go_bells::go_bellsAI::UpdateAI(), and npc_elder_clearwater::npc_elder_clearwaterAI::UpdateAI().
TimeStringTo()
template<class T > AC_COMMON_API uint32 Acore::Time::TimeStringTo (std::string_view timeString)
TimeToHumanReadable()
std::string Acore::Time::TimeToHumanReadable (Seconds time = 0s, std::string_view fmt = {})
{
    std::stringstream ss;
    std::string format{ fmt };
    time_t t = time.count();
    if (format.empty())
    {
        format = "%a %b %d %Y %X";
    }
    ss << std::put_time(std::localtime(&t), format.c_str());
    return ss.str();
}
Referenced by misc_commandscript::HandleMuteInfoHelper().
TimeToTimestampStr()
std::string Acore::Time::TimeToTimestampStr (Seconds time = 0s, std::string_view fmt = {})
{
    std::stringstream ss;
    std::string format{ fmt };
    time_t t = time.count();
    if (format.empty())
    {
        format = "%Y-%m-%d %X";
    }
    ss << std::put_time(std::localtime(&t), format.c_str());
    return ss.str();
}
Referenced by Log::GetTimestampStr(), LogMessage::getTimeStr(), character_commandscript::HandleCharacterDeletedListHelper(), and event_commandscript::HandleEventInfoCommand().
ToTimeString() [1/3]
std::string Acore::Time::ToTimeString (Microseconds durationTime, TimeOutput timeOutput = TimeOutput::Seconds, TimeFormat timeFormat = TimeFormat::ShortText)
{
    return ToTimeString<Microseconds>(durationTime.count(), timeOutput, timeFormat);
}
ToTimeString() [2/3]
template<class T > AC_COMMON_API std::string Acore::Time::ToTimeString (std::string_view durationTime, TimeOutput timeOutput = TimeOutput::Seconds, TimeFormat timeFormat = TimeFormat::ShortText)
ToTimeString() [3/3]
template<class T > AC_COMMON_API std::string Acore::Time::ToTimeString (uint64 durationTime, TimeOutput timeOutput = TimeOutput::Seconds, TimeFormat timeFormat = TimeFormat::ShortText)