AzerothCore: boss_alar Struct Reference
boss_alar Struct Reference
Public Member Functions
boss_alar (Creature *creature)
void Reset () override
void JustReachedHome () override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
bool CanAIAttack (Unit const *victim) const override
void EnterEvadeMode (EvadeReason why) override
void JustDied (Unit *killer) override
void MoveInLineOfSight (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void PretendToDie (Creature *creature)
void ScheduleAbilities ()
void SpawnPhoenixes (uint8 count, Unit *targetToSpawnAt)
void DoDiveBomb ()
void MovementInform (uint32 type, uint32 id) override
void ScheduleMainSpellAttack (std::chrono::seconds timer)
void ConstructWaypointsAndMove ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Position DeterminePhoenixPosition (Position playerPosition)
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
bool _hasPretendedToDie
bool _canAttackCooldown
bool _baseAttackOverride
bool _spawnPhoenixes
bool _noMelee
uint8 _platform
uint8 _platformRoll
uint8 _noQuillTimes
std::chrono::seconds _platformMoveRepeatTimer
TaskScheduler _transitionScheduler
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_alar()
boss_alar::boss_alar (Creature * creature) inline
                                  : BossAI(creature, DATA_ALAR)
    {
        me->SetCombatMovement(false);
        scheduler.SetValidator([this]
        {
            return !me->HasUnitState(UNIT_STATE_CASTING);
        });
    }
References Unit::HasUnitState(), ScriptedAI::me, CreatureAI::scheduler, Creature::SetCombatMovement(), TaskScheduler::SetValidator(), and UNIT_STATE_CASTING.
Member Function Documentation
CanAIAttack()
bool boss_alar::CanAIAttack (Unit const * victim) const inline override virtual
Reimplemented from UnitAI.
    {
        if (me->isMoving())
            return true;
        return _hasPretendedToDie || me->IsWithinMeleeRange(victim);
    }
References _hasPretendedToDie, Unit::isMoving(), Unit::IsWithinMeleeRange(), and ScriptedAI::me.
ConstructWaypointsAndMove()
void boss_alar::ConstructWaypointsAndMove () inline
    {
        me->StopMoving();
        if (WaypointPath const* i_path = sWaypointMgr->GetPath(me->GetWaypointPath()))
        {
            Movement::PointsArray pathPoints;
            pathPoints.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
            for (uint8 i = 0; i < i_path->size(); ++i)
            {
                WaypointData const* node = i_path->at(i);
                pathPoints.push_back(G3D::Vector3(node->x, node->y, node->z));
            }
            me->GetMotionMaster()->MoveSplinePath(&pathPoints);
        }
    }
References Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Creature::GetWaypointPath(), ScriptedAI::me, MotionMaster::MoveSplinePath(), Unit::StopMoving(), sWaypointMgr, WaypointData::x, WaypointData::y, and WaypointData::z.
Referenced by JustReachedHome(), MovementInform(), and Reset().
DamageTaken()
void boss_alar::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
    {
        if (damage >= me->GetHealth() && _platform < POINT_MIDDLE)
        {
            damage = 0;
            if (!_hasPretendedToDie)
            {
                _hasPretendedToDie = true;
                DoCastSelf(SPELL_EMBER_BLAST, true);
                PretendToDie(me);
                _transitionScheduler.Schedule(1s, [this](TaskContext)
                {
                    me->SetVisible(false);
                }).Schedule(8s, [this](TaskContext)
                {
                    me->SetPosition(alarPoints[POINT_MIDDLE]);
                }).Schedule(12s, [this](TaskContext)
                {
                    me->SetStandState(UNIT_STAND_STATE_STAND);
                    me->SetVisible(true);
                    DoCastSelf(SPELL_CLEAR_ALL_DEBUFFS, true);
                    DoCastSelf(SPELL_REBIRTH_PHASE2);
                }).Schedule(16001ms, [this](TaskContext)
                {
                    me->SetHealth(me->GetMaxHealth());
                    me->SetReactState(REACT_AGGRESSIVE);
                    _noMelee = false;
                    me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    _platform = POINT_MIDDLE;
                    me->ResumeChasingVictim();
                    ScheduleAbilities();
                });
            }
        }
    }
References _hasPretendedToDie, _noMelee, _platform, _transitionScheduler, alarPoints, UnitAI::DoCastSelf(), Unit::GetHealth(), Unit::GetMaxHealth(), ScriptedAI::me, POINT_MIDDLE, PretendToDie(), REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Creature::ResumeChasingVictim(), TaskScheduler::Schedule(), ScheduleAbilities(), Unit::SetHealth(), Creature::SetPosition(), Creature::SetReactState(), Unit::SetStandState(), Unit::SetVisible(), SPELL_CLEAR_ALL_DEBUFFS, SPELL_EMBER_BLAST, SPELL_REBIRTH_PHASE2, UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_STAND.
DeterminePhoenixPosition()
Position boss_alar::DeterminePhoenixPosition (Position playerPosition) inline
    {
        // set finalPosition to playerPosition in case the fraction fails
        Position finalPosition = playerPosition;
        float playerXPosition = playerPosition.GetPositionX();
        float playerYPosition = playerPosition.GetPositionY();
        float centreXPosition = alarPoints[POINT_MIDDLE].GetPositionX();
        float centreYPosition = alarPoints[POINT_MIDDLE].GetPositionY();
        float deltaX = std::abs(playerXPosition-centreXPosition);
        float deltaY = std::abs(playerYPosition-centreYPosition);
        int8 signMultiplier[2] = {1, 1};
        // if fraction has x position 0.0f we get nan as a result
        if (float playerFraction = deltaX/deltaY)
        {
            // player angle based on delta X and delta Y
            float playerAngle = std::atan(playerFraction);
            float phoenixDeltaYPosition = std::cos(playerAngle)*INNER_CIRCLE_RADIUS;
            float phoenixDeltaXPosition = std::sin(playerAngle)*INNER_CIRCLE_RADIUS;
            // as calculations are absolute values we have to multiply in the end
            // should be negative if player position was further down than centre
            if (playerXPosition < centreXPosition)
                signMultiplier[0] = -1;
            if (playerYPosition < centreYPosition)
                signMultiplier[1] = -1;
            // phoenix position based on set distance
            finalPosition = {centreXPosition+signMultiplier[0]*phoenixDeltaXPosition, centreYPosition+signMultiplier[1]*phoenixDeltaYPosition, 0.0f, 0.0f};
        }
        return finalPosition;
    }
References alarPoints, Position::GetPositionX(), Position::GetPositionY(), INNER_CIRCLE_RADIUS, and POINT_MIDDLE.
Referenced by SpawnPhoenixes().
DoDiveBomb()
void boss_alar::DoDiveBomb () inline
    {
        _noMelee = true;
        scheduler.Schedule(2s, [this](TaskContext)
        {
            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 110.0f, true))
                SpawnPhoenixes(2, target);
        }).Schedule(6s, [this](TaskContext)
        {
            me->SetModelVisible(true);
            DoCastSelf(SPELL_REBIRTH_DIVE);
        }).Schedule(10s, [this](TaskContext)
        {
            me->ResumeChasingVictim();
            _noMelee = false;
        });
        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 90.0f, true))
        {
            DoCast(target, SPELL_DIVE_BOMB);
            me->SetPosition(*target);
            me->StopMovingOnCurrentPos();
        }
        me->RemoveAurasDueToSpell(SPELL_DIVE_BOMB_VISUAL);
    }
References _noMelee, UnitAI::DoCast(), UnitAI::DoCastSelf(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), Creature::ResumeChasingVictim(), TaskScheduler::Schedule(), CreatureAI::scheduler, UnitAI::SelectTarget(), Unit::SetModelVisible(), Creature::SetPosition(), SpawnPhoenixes(), SPELL_DIVE_BOMB, SPELL_DIVE_BOMB_VISUAL, SPELL_REBIRTH_DIVE, and Unit::StopMovingOnCurrentPos().
Referenced by MovementInform().
EnterEvadeMode()
void boss_alar::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from BossAI.
    {
        if (why == EVADE_REASON_BOUNDARY)
            BossAI::EnterEvadeMode(why);
        else if (me->GetThreatMgr().GetThreatList().empty())
            BossAI::EnterEvadeMode(why);
    }
References BossAI::EnterEvadeMode(), CreatureAI::EVADE_REASON_BOUNDARY, ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), and ScriptedAI::me.
JustDied()
void boss_alar::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
    {
        BossAI::JustDied(killer);
        me->SetModelVisible(true);
        me->GetMap()->DoForAllPlayers([&](Player* player)
        {
            if (player->GetQuestStatus(QUEST_RUSE_OF_THE_ASHTONGUE) == QUEST_STATUS_INCOMPLETE && player->HasAura(SPELL_ASHTONGUE_RUSE))
                player->AreaExploredOrEventHappens(QUEST_RUSE_OF_THE_ASHTONGUE);
        });
    }
References Player::AreaExploredOrEventHappens(), Map::DoForAllPlayers(), WorldObject::GetMap(), Player::GetQuestStatus(), Unit::HasAura(), BossAI::JustDied(), ScriptedAI::me, QUEST_RUSE_OF_THE_ASHTONGUE, QUEST_STATUS_INCOMPLETE, Unit::SetModelVisible(), and SPELL_ASHTONGUE_RUSE.
JustEngagedWith()
void boss_alar::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        BossAI::JustEngagedWith(who);
        scheduler.Schedule(0s, [this](TaskContext context)
        {
            if (roll_chance_i(20 * _noQuillTimes))
            {
                _noQuillTimes = 0;
                _platformRoll = RAND(0, 1);
                _platform = _platformRoll ? 0 : 3;
                me->GetMotionMaster()->MovePoint(POINT_QUILL, alarPoints[POINT_QUILL], false, true);
                _platformMoveRepeatTimer = 16s;
            }
            else
            {
                if (_noQuillTimes++ > 0)
                {
                    me->SetOrientation(alarPoints[_platform].GetOrientation());
                    SpawnPhoenixes(1, me);
                }
                me->GetMotionMaster()->MovePoint(POINT_PLATFORM, alarPoints[_platform], false, true);
                _platform = (_platform+1)%4;
                _platformMoveRepeatTimer = 30s;
            }
            context.Repeat(_platformMoveRepeatTimer);
        });
        ScheduleMainSpellAttack(0s);
    }
References _noQuillTimes, _platform, _platformMoveRepeatTimer, _platformRoll, alarPoints, Unit::GetMotionMaster(), BossAI::JustEngagedWith(), ScriptedAI::me, MotionMaster::MovePoint(), POINT_PLATFORM, POINT_QUILL, RAND(), TaskContext::Repeat(), roll_chance_i(), TaskScheduler::Schedule(), ScheduleMainSpellAttack(), CreatureAI::scheduler, Position::SetOrientation(), and SpawnPhoenixes().
JustReachedHome()
void boss_alar::JustReachedHome () inline override virtual
Reimplemented from BossAI.
    {
        BossAI::JustReachedHome();
        if (me->IsEngaged())
            ConstructWaypointsAndMove();
    }
References ConstructWaypointsAndMove(), Unit::IsEngaged(), BossAI::JustReachedHome(), and ScriptedAI::me.
MoveInLineOfSight()
void boss_alar::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{ }
MovementInform()
void boss_alar::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type != POINT_MOTION_TYPE)
        {
            if (type == ESCORT_MOTION_TYPE && me->movespline->Finalized() && !me->IsInCombat())
                ConstructWaypointsAndMove();
            return;
        }
        switch (id)
        {
            case POINT_QUILL:
                scheduler.CancelGroup(GROUP_FLAME_BUFFET);
                scheduler.Schedule(1s, [this](TaskContext)
                {
                    DoCastSelf(SPELL_FLAME_QUILLS);
                });
                ScheduleMainSpellAttack(13s);
                break;
            case POINT_DIVE:
                scheduler.Schedule(1s, [this](TaskContext)
                {
                    DoCastSelf(SPELL_DIVE_BOMB_VISUAL);
                }).Schedule(5s, [this](TaskContext)
                {
                    DoDiveBomb();
                });
                break;
            default:
                return;
        }
    }
References TaskScheduler::CancelGroup(), ConstructWaypointsAndMove(), UnitAI::DoCastSelf(), DoDiveBomb(), ESCORT_MOTION_TYPE, Movement::MoveSpline::Finalized(), GROUP_FLAME_BUFFET, Unit::IsInCombat(), ScriptedAI::me, Unit::movespline, POINT_DIVE, POINT_MOTION_TYPE, POINT_QUILL, TaskScheduler::Schedule(), ScheduleMainSpellAttack(), CreatureAI::scheduler, SPELL_DIVE_BOMB_VISUAL, and SPELL_FLAME_QUILLS.
PretendToDie()
void boss_alar::PretendToDie (Creature * creature) inline
    {
        _noMelee = true;
        scheduler.CancelAll();
        creature->InterruptNonMeleeSpells(true);
        creature->RemoveAllAuras();
        creature->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        creature->SetReactState(REACT_PASSIVE);
        creature->GetMotionMaster()->MovementExpired(false);
        creature->GetMotionMaster()->MoveIdle();
        creature->SetStandState(UNIT_STAND_STATE_DEAD);
    }
References _noMelee, TaskScheduler::CancelAll(), Unit::GetMotionMaster(), Unit::InterruptNonMeleeSpells(), MotionMaster::MoveIdle(), MotionMaster::MovementExpired(), REACT_PASSIVE, Unit::RemoveAllAuras(), CreatureAI::scheduler, Creature::SetReactState(), Unit::SetStandState(), Unit::SetUnitFlag(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_DEAD.
Referenced by DamageTaken().
Reset()
void boss_alar::Reset () inline override virtual
Reimplemented from BossAI.
    {
        BossAI::Reset();
        _canAttackCooldown = true;
        _baseAttackOverride = false;
        _spawnPhoenixes = false;
        _hasPretendedToDie = false;
        _transitionScheduler.CancelAll();
        _platform = 0;
        _noMelee = false;
        _platformRoll = 0;
        _noQuillTimes = 0;
        _platformMoveRepeatTimer = 16s;
        me->SetModelVisible(true);
        me->SetReactState(REACT_AGGRESSIVE);
        ConstructWaypointsAndMove();
        me->m_Events.KillAllEvents(false);
    }
References _baseAttackOverride, _canAttackCooldown, _hasPretendedToDie, _noMelee, _noQuillTimes, _platform, _platformMoveRepeatTimer, _platformRoll, _spawnPhoenixes, _transitionScheduler, TaskScheduler::CancelAll(), ConstructWaypointsAndMove(), EventProcessor::KillAllEvents(), Unit::m_Events, ScriptedAI::me, REACT_AGGRESSIVE, BossAI::Reset(), Unit::SetModelVisible(), and Creature::SetReactState().
ScheduleAbilities()
void boss_alar::ScheduleAbilities () inline
    {
        _transitionScheduler.CancelAll();
        ScheduleTimedEvent(57s, [&]
        {
            DoCastVictim(SPELL_MELT_ARMOR);
        }, 60s);
        ScheduleTimedEvent(10s, [&]
        {
            DoCastRandomTarget(SPELL_CHARGE, 0, 50.0f);
        }, 30s);
        ScheduleTimedEvent(20s, [&]
        {
            // find spell from sniffs?
            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 50.0f, true))
                me->SummonCreature(NPC_FLAME_PATCH, *target, TEMPSUMMON_TIMED_DESPAWN, 2 * MINUTE * IN_MILLISECONDS);
        }, 30s);
        ScheduleTimedEvent(34s, [&]
        {
            me->GetMotionMaster()->MovePoint(POINT_DIVE, alarPoints[POINT_DIVE], false, true);
            scheduler.DelayAll(15s);
        }, 57s);
        me->m_Events.AddEventAtOffset([&] {
            DoCastSelf(SPELL_BERSERK, true);
        }, 10min);
        ScheduleMainSpellAttack(0s);
    }
References _transitionScheduler, EventProcessor::AddEventAtOffset(), alarPoints, TaskScheduler::CancelAll(), TaskScheduler::DelayAll(), UnitAI::DoCastRandomTarget(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), Unit::GetMotionMaster(), IN_MILLISECONDS, Unit::m_Events, ScriptedAI::me, MINUTE, NPC_FLAME_PATCH, POINT_DIVE, ScheduleMainSpellAttack(), CreatureAI::scheduler, ScriptedAI::ScheduleTimedEvent(), UnitAI::SelectTarget(), SPELL_BERSERK, SPELL_CHARGE, SPELL_MELT_ARMOR, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
Referenced by DamageTaken().
ScheduleMainSpellAttack()
void boss_alar::ScheduleMainSpellAttack (std::chrono::seconds timer) inline
    {
        scheduler.Schedule(timer, GROUP_FLAME_BUFFET, [this](TaskContext context)
        {
            if (!me->SelectNearestTarget(me->GetCombatReach()) && !me->isMoving())
                DoCastVictim(SPELL_FLAME_BUFFET);
            context.Repeat(2s);
        });
    }
References UnitAI::DoCastVictim(), Unit::GetCombatReach(), GROUP_FLAME_BUFFET, Unit::isMoving(), ScriptedAI::me, TaskContext::Repeat(), TaskScheduler::Schedule(), CreatureAI::scheduler, Creature::SelectNearestTarget(), and SPELL_FLAME_BUFFET.
Referenced by JustEngagedWith(), MovementInform(), and ScheduleAbilities().
SpawnPhoenixes()
void boss_alar::SpawnPhoenixes (uint8 count, Unit * targetToSpawnAt) inline
    {
        if (targetToSpawnAt)
        {
            Position spawnPosition = DeterminePhoenixPosition(targetToSpawnAt->GetPosition());
            for (uint8 i = 0; i < count; ++i)
            {
                me->SummonCreature(NPC_EMBER_OF_ALAR, spawnPosition, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000);
            }
        }
    }
References DeterminePhoenixPosition(), Position::GetPosition(), ScriptedAI::me, NPC_EMBER_OF_ALAR, WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
Referenced by DoDiveBomb(), and JustEngagedWith().
UpdateAI()
void boss_alar::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
    {
        _transitionScheduler.Update(diff);
        if (!UpdateVictim())
            return;
        scheduler.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
            return;
        if (!_noMelee)
            DoMeleeAttackIfReady();
    }
References _noMelee, _transitionScheduler, UnitAI::DoMeleeAttackIfReady(), Unit::HasUnitState(), ScriptedAI::me, CreatureAI::scheduler, UNIT_STATE_CASTING, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_baseAttackOverride
bool boss_alar::_baseAttackOverride private
Referenced by Reset().
_canAttackCooldown
bool boss_alar::_canAttackCooldown private
Referenced by Reset().
_hasPretendedToDie
bool boss_alar::_hasPretendedToDie private
Referenced by CanAIAttack(), DamageTaken(), and Reset().
_noMelee
bool boss_alar::_noMelee private
Referenced by DamageTaken(), DoDiveBomb(), PretendToDie(), Reset(), and UpdateAI().
_noQuillTimes
uint8 boss_alar::_noQuillTimes private
Referenced by JustEngagedWith(), and Reset().
_platform
uint8 boss_alar::_platform private
Referenced by DamageTaken(), JustEngagedWith(), and Reset().
_platformMoveRepeatTimer
std::chrono::seconds boss_alar::_platformMoveRepeatTimer private
Referenced by JustEngagedWith(), and Reset().
_platformRoll
uint8 boss_alar::_platformRoll private
Referenced by JustEngagedWith(), and Reset().
_spawnPhoenixes
bool boss_alar::_spawnPhoenixes private
Referenced by Reset().
_transitionScheduler
TaskScheduler boss_alar::_transitionScheduler private
Referenced by DamageTaken(), Reset(), ScheduleAbilities(), and UpdateAI().