AzerothCore: instance_pit_of_saron::instance_pit_of_saron_InstanceScript Struct Reference
instance_pit_of_saron::instance_pit_of_saron_InstanceScript Struct Reference
Public Member Functions
instance_pit_of_saron_InstanceScript (Map *map)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *) override
uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
void SetGuidData (uint32 type, ObjectGuid data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 type) const override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
TeamId teamIdInInstance
uint32 InstanceProgress
std::string str_data
ObjectGuid NPC_LeaderFirstGUID
ObjectGuid NPC_LeaderSecondGUID
ObjectGuid NPC_TyrannusEventGUID
ObjectGuid NPC_Necrolyte1GUID
ObjectGuid NPC_Necrolyte2GUID
ObjectGuid NPC_GuardFirstGUID
ObjectGuid NPC_GuardSecondGUID
ObjectGuid NPC_SindragosaGUID
ObjectGuid NPC_GarfrostGUID
ObjectGuid NPC_MartinOrGorkunGUID
ObjectGuid NPC_RimefangGUID
ObjectGuid NPC_TyrannusGUID
ObjectGuid GO_IceWallGUID
bool bAchievEleven
bool bAchievDontLookUp
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_pit_of_saron_InstanceScript()
instance_pit_of_saron::instance_pit_of_saron_InstanceScript::instance_pit_of_saron_InstanceScript (Map * map) inline
                                                       : InstanceScript(map)
        {
            SetHeaders(DataHeader);
        }
References DataHeader, and InstanceScript::SetHeaders().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_pit_of_saron::instance_pit_of_saron_InstanceScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case 12993: // Doesn't Go to Eleven (4524)
                    return bAchievEleven;
            }
            return false;
        }
References bAchievEleven.
GetCreatureEntry()
uint32 instance_pit_of_saron::instance_pit_of_saron_InstanceScript::GetCreatureEntry (ObjectGuid::LowType , CreatureData const * data) inline override virtual
Reimplemented from ZoneScript.
        {
            if (teamIdInInstance == TEAM_NEUTRAL)
            {
                Map::PlayerList const& players = instance->GetPlayers();
                if (!players.IsEmpty())
                    if (Player* player = players.begin()->GetSource())
                        teamIdInInstance = player->GetTeamId();
            }
            uint32 entry = data->id1;
            switch (entry)
            {
                case NPC_RESCUED_ALLIANCE_SLAVE:
                    if (teamIdInInstance == TEAM_HORDE)
                        return 0;
                    break;
                case NPC_RESCUED_HORDE_SLAVE:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        return 0;
                    break;
            }
            return entry;
        }
References MapRefMgr::begin(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), CreatureData::id1, InstanceScript::instance, LinkedListHead::IsEmpty(), NPC_RESCUED_ALLIANCE_SLAVE, NPC_RESCUED_HORDE_SLAVE, TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, and teamIdInInstance.
GetData()
uint32 instance_pit_of_saron::instance_pit_of_saron_InstanceScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_INSTANCE_PROGRESS:
                    return InstanceProgress;
                case DATA_TEAMID_IN_INSTANCE:
                    return teamIdInInstance;
                case DATA_GARFROST:
                    return m_auiEncounter[0];
                case DATA_ICK:
                    return m_auiEncounter[1];
                case DATA_TYRANNUS:
                    return m_auiEncounter[2];
            }
            return 0;
        }
References DATA_GARFROST, DATA_ICK, DATA_INSTANCE_PROGRESS, DATA_TEAMID_IN_INSTANCE, DATA_TYRANNUS, InstanceProgress, m_auiEncounter, and teamIdInInstance.
Referenced by OnGameObjectCreate(), and SetData().
GetGuidData()
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case DATA_TYRANNUS_EVENT_GUID:
                    return NPC_TyrannusEventGUID;
                case DATA_NECROLYTE_1_GUID:
                    return NPC_Necrolyte1GUID;
                case DATA_NECROLYTE_2_GUID:
                    return NPC_Necrolyte2GUID;
                case DATA_GUARD_1_GUID:
                    return NPC_GuardFirstGUID;
                case DATA_GUARD_2_GUID:
                    return NPC_GuardSecondGUID;
                case DATA_LEADER_FIRST_GUID:
                    return NPC_LeaderFirstGUID;
                case DATA_GARFROST_GUID:
                    return NPC_GarfrostGUID;
                case DATA_MARTIN_OR_GORKUN_GUID:
                    return NPC_MartinOrGorkunGUID;
                case DATA_RIMEFANG_GUID:
                    return NPC_RimefangGUID;
                case DATA_TYRANNUS_GUID:
                    return NPC_TyrannusGUID;
                case DATA_LEADER_SECOND_GUID:
                    return NPC_LeaderSecondGUID;
                case DATA_SINDRAGOSA_GUID:
                    return NPC_SindragosaGUID;
            }
            return ObjectGuid::Empty;
        }
References DATA_GARFROST_GUID, DATA_GUARD_1_GUID, DATA_GUARD_2_GUID, DATA_LEADER_FIRST_GUID, DATA_LEADER_SECOND_GUID, DATA_MARTIN_OR_GORKUN_GUID, DATA_NECROLYTE_1_GUID, DATA_NECROLYTE_2_GUID, DATA_RIMEFANG_GUID, DATA_SINDRAGOSA_GUID, DATA_TYRANNUS_EVENT_GUID, DATA_TYRANNUS_GUID, ObjectGuid::Empty, NPC_GarfrostGUID, NPC_GuardFirstGUID, NPC_GuardSecondGUID, NPC_LeaderFirstGUID, NPC_LeaderSecondGUID, NPC_MartinOrGorkunGUID, NPC_Necrolyte1GUID, NPC_Necrolyte2GUID, NPC_RimefangGUID, NPC_SindragosaGUID, NPC_TyrannusEventGUID, and NPC_TyrannusGUID.
Referenced by OnPlayerEnter().
Initialize()
void instance_pit_of_saron::instance_pit_of_saron_InstanceScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
            teamIdInInstance = TEAM_NEUTRAL;
            InstanceProgress = INSTANCE_PROGRESS_NONE;
            bAchievEleven = true;
            bAchievDontLookUp = true;
        }
References bAchievDontLookUp, bAchievEleven, INSTANCE_PROGRESS_NONE, InstanceProgress, m_auiEncounter, TEAM_NEUTRAL, and teamIdInInstance.
IsEncounterInProgress()
bool instance_pit_of_saron::instance_pit_of_saron_InstanceScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                if (m_auiEncounter[i] == IN_PROGRESS) return true;
            return false;
        }
References IN_PROGRESS, m_auiEncounter, and MAX_ENCOUNTER.
OnCreatureCreate()
void instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            if (teamIdInInstance == TEAM_NEUTRAL)
            {
                Map::PlayerList const& players = instance->GetPlayers();
                if (!players.IsEmpty())
                    if (Player* player = players.begin()->GetSource())
                        teamIdInInstance = player->GetTeamId();
            }
            switch (creature->GetEntry())
            {
                case NPC_SYLVANAS_PART1:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_JAINA_PART1);
                    NPC_LeaderFirstGUID = creature->GetGUID();
                    switch (InstanceProgress)
                    {
                        case INSTANCE_PROGRESS_FINISHED_INTRO:
                            creature->SetPosition(LeaderIntroPos);
                            break;
                        case INSTANCE_PROGRESS_FINISHED_KRICK_SCENE:
                        case INSTANCE_PROGRESS_AFTER_WARN_1:
                        case INSTANCE_PROGRESS_AFTER_WARN_2:
                        case INSTANCE_PROGRESS_AFTER_TUNNEL_WARN:
                        case INSTANCE_PROGRESS_TYRANNUS_INTRO:
                            creature->SetPosition(SBSLeaderEndPos);
                            break;
                    }
                    break;
                case NPC_SYLVANAS_PART2:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_JAINA_PART2);
                    NPC_LeaderSecondGUID = creature->GetGUID();
                    break;
                case NPC_TYRANNUS_EVENT:
                    if (!NPC_TyrannusEventGUID)
                    {
                        switch (InstanceProgress)
{
                            case INSTANCE_PROGRESS_FINISHED_INTRO:
                                creature->SetPosition(SBSTyrannusStartPos);
                                break;
                            case INSTANCE_PROGRESS_FINISHED_KRICK_SCENE:
                                creature->SetPosition(PTSTyrannusWaitPos1);
                                break;
                            case INSTANCE_PROGRESS_AFTER_WARN_1:
                                creature->SetPosition(PTSTyrannusWaitPos2);
                                break;
                            case INSTANCE_PROGRESS_AFTER_WARN_2:
                                creature->SetPosition(PTSTyrannusWaitPos3);
                                break;
                            case INSTANCE_PROGRESS_AFTER_TUNNEL_WARN:
                            case INSTANCE_PROGRESS_TYRANNUS_INTRO:
                                creature->SetPosition(SBSTyrannusStartPos);
                                break;
                        }
                        NPC_TyrannusEventGUID = creature->GetGUID();
                    }
                    break;
                case NPC_LORALEN:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_ELANDRA);
                    if (!NPC_GuardFirstGUID)
                        NPC_GuardFirstGUID = creature->GetGUID();
                    break;
                case NPC_KALIRA:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_KORELN);
                    if (!NPC_GuardSecondGUID)
                        NPC_GuardSecondGUID = creature->GetGUID();
                    break;
                case NPC_HORDE_SLAVE_1:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_ALLIANCE_SLAVE_1);
                    break;
                case NPC_HORDE_SLAVE_2:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_ALLIANCE_SLAVE_2);
                    break;
                case NPC_HORDE_SLAVE_3:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_ALLIANCE_SLAVE_3);
                    break;
                case NPC_HORDE_SLAVE_4:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_ALLIANCE_SLAVE_4);
                    break;
                case NPC_GORKUN_IRONSKULL_1:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_MARTIN_VICTUS_1);
                    break;
                case NPC_GARFROST:
                    NPC_GarfrostGUID = creature->GetGUID();
                    break;
                case NPC_FREED_SLAVE_1_HORDE:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_FREED_SLAVE_1_ALLIANCE);
                    break;
                case NPC_FREED_SLAVE_2_HORDE:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_FREED_SLAVE_2_ALLIANCE);
                    break;
                case NPC_FREED_SLAVE_3_HORDE:
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_FREED_SLAVE_3_ALLIANCE);
                    break;
                case NPC_GORKUN_IRONSKULL_2:
                    if (NPC_MartinOrGorkunGUID)
                        if (Creature* c = instance->GetCreature(NPC_MartinOrGorkunGUID))
{
                            c->AI()->DoAction(1); // despawn summons
                            c->DespawnOrUnsummon();
                        }
                    if (teamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_MARTIN_VICTUS_2);
                    NPC_MartinOrGorkunGUID = creature->GetGUID();
                    break;
                case NPC_RIMEFANG:
                    NPC_RimefangGUID = creature->GetGUID();
                    if (m_auiEncounter[2] == DONE)
                        creature->SetVisible(false);
                    break;
                case NPC_TYRANNUS:
                    if (NPC_TyrannusGUID)
                        if (Creature* c = instance->GetCreature(NPC_TyrannusGUID))
                            c->DespawnOrUnsummon();
                    NPC_TyrannusGUID = creature->GetGUID();
                    if (m_auiEncounter[2] == DONE)
                        creature->SetVisible(false);
                    break;
                case NPC_SINDRAGOSA:
                    NPC_SindragosaGUID = creature->GetGUID();
                    break;
            }
        }
References MapRefMgr::begin(), DONE, Map::GetCreature(), Object::GetEntry(), Object::GetGUID(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), InstanceScript::instance, INSTANCE_PROGRESS_AFTER_TUNNEL_WARN, INSTANCE_PROGRESS_AFTER_WARN_1, INSTANCE_PROGRESS_AFTER_WARN_2, INSTANCE_PROGRESS_FINISHED_INTRO, INSTANCE_PROGRESS_FINISHED_KRICK_SCENE, INSTANCE_PROGRESS_TYRANNUS_INTRO, InstanceProgress, LinkedListHead::IsEmpty(), LeaderIntroPos, m_auiEncounter, NPC_ALLIANCE_SLAVE_1, NPC_ALLIANCE_SLAVE_2, NPC_ALLIANCE_SLAVE_3, NPC_ALLIANCE_SLAVE_4, NPC_ELANDRA, NPC_FREED_SLAVE_1_ALLIANCE, NPC_FREED_SLAVE_1_HORDE, NPC_FREED_SLAVE_2_ALLIANCE, NPC_FREED_SLAVE_2_HORDE, NPC_FREED_SLAVE_3_ALLIANCE, NPC_FREED_SLAVE_3_HORDE, NPC_GARFROST, NPC_GarfrostGUID, NPC_GORKUN_IRONSKULL_1, NPC_GORKUN_IRONSKULL_2, NPC_GuardFirstGUID, NPC_GuardSecondGUID, NPC_HORDE_SLAVE_1, NPC_HORDE_SLAVE_2, NPC_HORDE_SLAVE_3, NPC_HORDE_SLAVE_4, NPC_JAINA_PART1, NPC_JAINA_PART2, NPC_KALIRA, NPC_KORELN, NPC_LeaderFirstGUID, NPC_LeaderSecondGUID, NPC_LORALEN, NPC_MARTIN_VICTUS_1, NPC_MARTIN_VICTUS_2, NPC_MartinOrGorkunGUID, NPC_RIMEFANG, NPC_RimefangGUID, NPC_SINDRAGOSA, NPC_SindragosaGUID, NPC_SYLVANAS_PART1, NPC_SYLVANAS_PART2, NPC_TYRANNUS, NPC_TYRANNUS_EVENT, NPC_TyrannusEventGUID, NPC_TyrannusGUID, PTSTyrannusWaitPos1, PTSTyrannusWaitPos2, PTSTyrannusWaitPos3, SBSLeaderEndPos, SBSTyrannusStartPos, Creature::SetPosition(), Unit::SetVisible(), TEAM_ALLIANCE, TEAM_NEUTRAL, teamIdInInstance, and Creature::UpdateEntry().
OnGameObjectCreate()
void instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_ICE_WALL:
                    GO_IceWallGUID = go->GetGUID();
                    if (GetData(DATA_GARFROST) == DONE && GetData(DATA_ICK) == DONE)
                        go->SetGoState(GO_STATE_ACTIVE);
                    break;
            }
        }
References DATA_GARFROST, DATA_ICK, DONE, GetData(), Object::GetEntry(), Object::GetGUID(), GO_ICE_WALL, GO_IceWallGUID, GO_STATE_ACTIVE, and GameObject::SetGoState().
OnPlayerEnter()
void instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnPlayerEnter (Player *) inline override virtual
Reimplemented from InstanceScript.
        {
            instance->LoadGrid(LeaderIntroPos.GetPositionX(), LeaderIntroPos.GetPositionY());
            if (Creature* c = instance->GetCreature(GetGuidData(DATA_LEADER_FIRST_GUID)))
                c->AI()->SetData(DATA_START_INTRO, 0);
        }
References DATA_LEADER_FIRST_GUID, DATA_START_INTRO, Map::GetCreature(), GetGuidData(), Position::GetPositionX(), Position::GetPositionY(), InstanceScript::instance, LeaderIntroPos, and Map::LoadGrid().
ReadSaveDataMore()
void instance_pit_of_saron::instance_pit_of_saron_InstanceScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> m_auiEncounter[0];
            data >> m_auiEncounter[1];
            data >> m_auiEncounter[2];
            data >> InstanceProgress;
        }
References InstanceProgress, and m_auiEncounter.
SetData()
void instance_pit_of_saron::instance_pit_of_saron_InstanceScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_INSTANCE_PROGRESS:
                    if (InstanceProgress < data)
                    {
                        InstanceProgress = data;
                        if (InstanceProgress == INSTANCE_PROGRESS_TYRANNUS_INTRO && instance->GetDifficulty() == DUNGEON_DIFFICULTY_HEROIC && bAchievDontLookUp) // achiev Don't Look Up (4525)
                            DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, 72845);
                    }
                    break;
                case DATA_GARFROST:
                    m_auiEncounter[0] = data;
                    if (data == DONE)
                        instance->SummonCreature(NPC_GORKUN_IRONSKULL_1, FBSSpawnPos);
                    else // NOT_STARTED, IN_PROGRESS
                        bAchievEleven = true;
                    if (data == DONE && GetData(DATA_ICK) == DONE)
                        if (GameObject* icewall = instance->GetGameObject(GO_IceWallGUID))
                            icewall->SetGoState(GO_STATE_ACTIVE);
                    break;
                case DATA_ICK:
                    m_auiEncounter[1] = data;
                    if (data == DONE && GetData(DATA_GARFROST) == DONE)
                        if (GameObject* icewall = instance->GetGameObject(GO_IceWallGUID))
                            icewall->SetGoState(GO_STATE_ACTIVE);
                    break;
                case DATA_TYRANNUS:
                    m_auiEncounter[2] = data;
                    if (data == DONE)
                        instance->SummonCreature(NPC_SYLVANAS_PART2, TSLeaderSpawnPos);
                    break;
                case DATA_ACHIEV_ELEVEN:
                    bAchievEleven = false;
                    break;
                case DATA_ACHIEV_DONT_LOOK_UP:
                    bAchievDontLookUp = false;
                    break;
            }
            if (data == DONE || type == DATA_INSTANCE_PROGRESS)
                SaveToDB();
        }
References ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, bAchievDontLookUp, bAchievEleven, DATA_ACHIEV_DONT_LOOK_UP, DATA_ACHIEV_ELEVEN, DATA_GARFROST, DATA_ICK, DATA_INSTANCE_PROGRESS, DATA_TYRANNUS, DONE, InstanceScript::DoUpdateAchievementCriteria(), DUNGEON_DIFFICULTY_HEROIC, FBSSpawnPos, GetData(), Map::GetDifficulty(), Map::GetGameObject(), GO_IceWallGUID, GO_STATE_ACTIVE, InstanceScript::instance, INSTANCE_PROGRESS_TYRANNUS_INTRO, InstanceProgress, m_auiEncounter, NPC_GORKUN_IRONSKULL_1, NPC_SYLVANAS_PART2, InstanceScript::SaveToDB(), Map::SummonCreature(), and TSLeaderSpawnPos.
SetGuidData()
void instance_pit_of_saron::instance_pit_of_saron_InstanceScript::SetGuidData (uint32 type, ObjectGuid data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_NECROLYTE_1_GUID:
                    NPC_Necrolyte1GUID = data;
                    break;
                case DATA_NECROLYTE_2_GUID:
                    NPC_Necrolyte2GUID = data;
                    break;
                case DATA_MARTIN_OR_GORKUN_GUID:
                    NPC_MartinOrGorkunGUID = data;
                    break;
            }
        }
References DATA_MARTIN_OR_GORKUN_GUID, DATA_NECROLYTE_1_GUID, DATA_NECROLYTE_2_GUID, NPC_MartinOrGorkunGUID, NPC_Necrolyte1GUID, and NPC_Necrolyte2GUID.
WriteSaveDataMore()
void instance_pit_of_saron::instance_pit_of_saron_InstanceScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << m_auiEncounter[0] << ' '
                << m_auiEncounter[1] << ' '
                << m_auiEncounter[2] << ' '
                << InstanceProgress;
        }
References InstanceProgress, and m_auiEncounter.
Member Data Documentation
bAchievDontLookUp
bool instance_pit_of_saron::instance_pit_of_saron_InstanceScript::bAchievDontLookUp
Referenced by Initialize(), and SetData().
bAchievEleven
bool instance_pit_of_saron::instance_pit_of_saron_InstanceScript::bAchievEleven
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
GO_IceWallGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::GO_IceWallGUID
Referenced by OnGameObjectCreate(), and SetData().
InstanceProgress
uint32 instance_pit_of_saron::instance_pit_of_saron_InstanceScript::InstanceProgress
Referenced by GetData(), Initialize(), OnCreatureCreate(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
m_auiEncounter
uint32 instance_pit_of_saron::instance_pit_of_saron_InstanceScript::m_auiEncounter[MAX_ENCOUNTER]
Referenced by GetData(), Initialize(), IsEncounterInProgress(), OnCreatureCreate(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
NPC_GarfrostGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_GarfrostGUID
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_GuardFirstGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_GuardFirstGUID
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_GuardSecondGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_GuardSecondGUID
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_LeaderFirstGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_LeaderFirstGUID
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_LeaderSecondGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_LeaderSecondGUID
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_MartinOrGorkunGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_MartinOrGorkunGUID
Referenced by GetGuidData(), OnCreatureCreate(), and SetGuidData().
NPC_Necrolyte1GUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_Necrolyte1GUID
Referenced by GetGuidData(), and SetGuidData().
NPC_Necrolyte2GUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_Necrolyte2GUID
Referenced by GetGuidData(), and SetGuidData().
NPC_RimefangGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_RimefangGUID
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_SindragosaGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_SindragosaGUID
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_TyrannusEventGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_TyrannusEventGUID
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_TyrannusGUID
ObjectGuid instance_pit_of_saron::instance_pit_of_saron_InstanceScript::NPC_TyrannusGUID
Referenced by GetGuidData(), and OnCreatureCreate().
str_data
std::string instance_pit_of_saron::instance_pit_of_saron_InstanceScript::str_data
teamIdInInstance
TeamId instance_pit_of_saron::instance_pit_of_saron_InstanceScript::teamIdInInstance
Referenced by GetCreatureEntry(), GetData(), Initialize(), and OnCreatureCreate().