AzerothCore: azerothcore-wotlk/src/server/scripts/Kalimdor/kalimdor_script_loader.cpp File Reference
kalimdor_script_loader.cpp File Reference
Functions
void AddSC_instance_blackfathom_deeps ()
void AddSC_hyjal ()
void AddSC_boss_archimonde ()
void AddSC_instance_mount_hyjal ()
void AddSC_boss_rage_winterchill ()
void AddSC_boss_anetheron ()
void AddSC_boss_kazrogal ()
void AddSC_boss_azgalor ()
void AddSC_boss_captain_skarloc ()
void AddSC_boss_epoch_hunter ()
void AddSC_boss_lieutenant_drake ()
void AddSC_instance_old_hillsbrad ()
void AddSC_old_hillsbrad ()
void AddSC_boss_aeonus ()
void AddSC_boss_chrono_lord_deja ()
void AddSC_boss_temporus ()
void AddSC_the_black_morass ()
void AddSC_instance_the_black_morass ()
void AddSC_boss_epoch ()
void AddSC_boss_infinite_corruptor ()
void AddSC_boss_salramm ()
void AddSC_boss_mal_ganis ()
void AddSC_boss_meathook ()
void AddSC_culling_of_stratholme ()
void AddSC_instance_culling_of_stratholme ()
void AddSC_boss_isalien ()
void AddSC_instance_dire_maul ()
void AddSC_instance_maraudon ()
void AddSC_boss_onyxia ()
void AddSC_instance_onyxias_lair ()
void AddSC_instance_ragefire_chasm ()
void AddSC_razorfen_downs ()
void AddSC_instance_razorfen_downs ()
void AddSC_instance_razorfen_kraul ()
void AddSC_boss_kurinnaxx ()
void AddSC_boss_rajaxx ()
void AddSC_boss_moam ()
void AddSC_boss_buru ()
void AddSC_boss_ayamiss ()
void AddSC_boss_ossirian ()
void AddSC_ruins_of_ahnqiraj ()
void AddSC_instance_ruins_of_ahnqiraj ()
void AddSC_boss_cthun ()
void AddSC_boss_viscidus ()
void AddSC_boss_fankriss ()
void AddSC_boss_huhuran ()
void AddSC_bug_trio ()
void AddSC_boss_sartura ()
void AddSC_boss_skeram ()
void AddSC_boss_twinemperors ()
void AddSC_boss_ouro ()
void AddSC_npc_anubisath_sentinel ()
void AddSC_temple_of_ahnqiraj ()
void AddSC_instance_temple_of_ahnqiraj ()
void AddSC_instance_wailing_caverns ()
void AddSC_zulfarrak ()
void AddSC_instance_zulfarrak ()
void AddSC_ashenvale ()
void AddSC_azshara ()
void AddSC_azuremyst_isle ()
void AddSC_bloodmyst_isle ()
void AddSC_boss_azuregos ()
void AddSC_darkshore ()
void AddSC_desolace ()
void AddSC_durotar ()
void AddSC_dustwallow_marsh ()
void AddSC_felwood ()
void AddSC_feralas ()
void AddSC_moonglade ()
void AddSC_orgrimmar ()
void AddSC_silithus ()
void AddSC_stonetalon_mountains ()
void AddSC_tanaris ()
void AddSC_the_barrens ()
void AddSC_thousand_needles ()
void AddSC_thunder_bluff ()
void AddSC_ungoro_crater ()
void AddSC_winterspring ()
void AddKalimdorScripts ()
Function Documentation
AddKalimdorScripts()
void AddKalimdorScripts ()
{
    AddSC_instance_blackfathom_deeps();     //Blackfathom Depths
    AddSC_hyjal();                          //CoT Battle for Mt. Hyjal
    AddSC_boss_archimonde();
    AddSC_instance_mount_hyjal();
    AddSC_boss_rage_winterchill();
    AddSC_boss_anetheron();
    AddSC_boss_kazrogal();
    AddSC_boss_azgalor();
    AddSC_boss_captain_skarloc();           //CoT Old Hillsbrad
    AddSC_boss_epoch_hunter();
    AddSC_boss_lieutenant_drake();
    AddSC_instance_old_hillsbrad();
    AddSC_old_hillsbrad();
    AddSC_boss_aeonus();                    //CoT The Black Morass
    AddSC_boss_chrono_lord_deja();
    AddSC_boss_temporus();
    AddSC_the_black_morass();
    AddSC_instance_the_black_morass();
    AddSC_boss_epoch();                     //CoT Culling Of Stratholme
    AddSC_boss_infinite_corruptor();
    AddSC_boss_salramm();
    AddSC_boss_mal_ganis();
    AddSC_boss_meathook();
    AddSC_culling_of_stratholme();
    AddSC_instance_culling_of_stratholme();
    AddSC_boss_isalien();
    AddSC_instance_dire_maul();             //Dire Maul
    AddSC_instance_maraudon();              //Maraudon
    AddSC_boss_onyxia();                    //Onyxia's Lair
    AddSC_instance_onyxias_lair();
    AddSC_instance_ragefire_chasm();        //Ragefire Chasm
    AddSC_razorfen_downs();
    AddSC_instance_razorfen_downs();        //Razorfen Downs
    AddSC_instance_razorfen_kraul();        //Razorfen Kraul
    AddSC_boss_kurinnaxx();                 //Ruins of ahn'qiraj
    AddSC_boss_rajaxx();
    AddSC_boss_moam();
    AddSC_boss_buru();
    AddSC_boss_ayamiss();
    AddSC_boss_ossirian();
    AddSC_ruins_of_ahnqiraj();
    AddSC_instance_ruins_of_ahnqiraj();
    AddSC_boss_cthun();                     //Temple of ahn'qiraj
    AddSC_boss_viscidus();
    AddSC_boss_fankriss();
    AddSC_boss_huhuran();
    AddSC_bug_trio();
    AddSC_boss_sartura();
    AddSC_boss_skeram();
    AddSC_boss_twinemperors();
    AddSC_boss_ouro();
    AddSC_npc_anubisath_sentinel();
    AddSC_temple_of_ahnqiraj();
    AddSC_instance_temple_of_ahnqiraj();
    AddSC_instance_wailing_caverns();       //Wailing caverns
    AddSC_zulfarrak();
    AddSC_instance_zulfarrak();             //Zul'Farrak instance script
    AddSC_ashenvale();
    AddSC_azshara();
    AddSC_azuremyst_isle();
    AddSC_bloodmyst_isle();
    AddSC_boss_azuregos();
    AddSC_darkshore();
    AddSC_desolace();
    AddSC_durotar();
    AddSC_dustwallow_marsh();
    AddSC_felwood();
    AddSC_feralas();
    AddSC_moonglade();
    AddSC_orgrimmar();
    AddSC_silithus();
    AddSC_stonetalon_mountains();
    AddSC_tanaris();
    AddSC_the_barrens();
    AddSC_thousand_needles();
    AddSC_thunder_bluff();
    AddSC_ungoro_crater();
    AddSC_winterspring();
}
References AddSC_ashenvale(), AddSC_azshara(), AddSC_azuremyst_isle(), AddSC_bloodmyst_isle(), AddSC_boss_aeonus(), AddSC_boss_anetheron(), AddSC_boss_archimonde(), AddSC_boss_ayamiss(), AddSC_boss_azgalor(), AddSC_boss_azuregos(), AddSC_boss_buru(), AddSC_boss_captain_skarloc(), AddSC_boss_chrono_lord_deja(), AddSC_boss_cthun(), AddSC_boss_epoch(), AddSC_boss_epoch_hunter(), AddSC_boss_fankriss(), AddSC_boss_huhuran(), AddSC_boss_infinite_corruptor(), AddSC_boss_isalien(), AddSC_boss_kazrogal(), AddSC_boss_kurinnaxx(), AddSC_boss_lieutenant_drake(), AddSC_boss_mal_ganis(), AddSC_boss_meathook(), AddSC_boss_moam(), AddSC_boss_onyxia(), AddSC_boss_ossirian(), AddSC_boss_ouro(), AddSC_boss_rage_winterchill(), AddSC_boss_rajaxx(), AddSC_boss_salramm(), AddSC_boss_sartura(), AddSC_boss_skeram(), AddSC_boss_temporus(), AddSC_boss_twinemperors(), AddSC_boss_viscidus(), AddSC_bug_trio(), AddSC_culling_of_stratholme(), AddSC_darkshore(), AddSC_desolace(), AddSC_durotar(), AddSC_dustwallow_marsh(), AddSC_felwood(), AddSC_feralas(), AddSC_hyjal(), AddSC_instance_blackfathom_deeps(), AddSC_instance_culling_of_stratholme(), AddSC_instance_dire_maul(), AddSC_instance_maraudon(), AddSC_instance_mount_hyjal(), AddSC_instance_old_hillsbrad(), AddSC_instance_onyxias_lair(), AddSC_instance_ragefire_chasm(), AddSC_instance_razorfen_downs(), AddSC_instance_razorfen_kraul(), AddSC_instance_ruins_of_ahnqiraj(), AddSC_instance_temple_of_ahnqiraj(), AddSC_instance_the_black_morass(), AddSC_instance_wailing_caverns(), AddSC_instance_zulfarrak(), AddSC_moonglade(), AddSC_npc_anubisath_sentinel(), AddSC_old_hillsbrad(), AddSC_orgrimmar(), AddSC_razorfen_downs(), AddSC_ruins_of_ahnqiraj(), AddSC_silithus(), AddSC_stonetalon_mountains(), AddSC_tanaris(), AddSC_temple_of_ahnqiraj(), AddSC_the_barrens(), AddSC_the_black_morass(), AddSC_thousand_needles(), AddSC_thunder_bluff(), AddSC_ungoro_crater(), AddSC_winterspring(), and AddSC_zulfarrak().
AddSC_ashenvale()
void AddSC_ashenvale ()
{
    new npc_muglash();
}
Referenced by AddKalimdorScripts().
AddSC_azshara()
void AddSC_azshara ()
{
    new npc_rizzle_sprysprocket();
    new npc_depth_charge();
}
Referenced by AddKalimdorScripts().
AddSC_azuremyst_isle()
void AddSC_azuremyst_isle ()
{
    new npc_draenei_survivor();
    new npc_injured_draenei();
    new npc_magwin();
    new npc_death_ravager();
    new go_ravager_cage();
    new npc_stillpine_capitive();
    new go_bristlelimb_cage();
    RegisterSpellScript(spell_inoculate_nestlewood_owlkin);
}
References RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_bloodmyst_isle()
void AddSC_bloodmyst_isle ()
{
    new npc_webbed_creature();
}
Referenced by AddKalimdorScripts().
AddSC_boss_aeonus()
void AddSC_boss_aeonus ()
{
    RegisterTheBlackMorassCreatureAI(boss_aeonus);
}
References RegisterTheBlackMorassCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_anetheron()
void AddSC_boss_anetheron ()
{
    RegisterHyjalAI(boss_anetheron);
    RegisterSpellScript(spell_anetheron_sleep);
}
References RegisterHyjalAI, and RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_boss_archimonde()
void AddSC_boss_archimonde ()
{
    RegisterSpellScript(spell_red_sky_effect);
    RegisterSpellScript(spell_doomfire);
    RegisterHyjalAI(boss_archimonde);
    RegisterHyjalAI(npc_ancient_wisp);
    RegisterHyjalAI(npc_doomfire_spirit);
}
References RegisterHyjalAI, and RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_boss_ayamiss()
void AddSC_boss_ayamiss ()
{
    RegisterRuinsOfAhnQirajCreatureAI(boss_ayamiss);
    RegisterRuinsOfAhnQirajCreatureAI(npc_hive_zara_larva);
    RegisterRuinsOfAhnQirajCreatureAI(npc_hive_zara_swarmer);
    RegisterSpellScript(spell_ayamiss_swarmer_teleport_trigger);
    RegisterSpellScript(spell_ayamiss_swarmer_swarm);
    RegisterSpellScript(spell_ayamiss_swarmer_start_loop);
    RegisterSpellScriptWithArgs(spell_gen_ayamiss_swarmer_loop, "spell_gen_ayamiss_swarmer_loop_1", (NPC_HIVEZARA_SWARMER + 5) * 10);
    RegisterSpellScriptWithArgs(spell_gen_ayamiss_swarmer_loop, "spell_gen_ayamiss_swarmer_loop_2", (NPC_HIVEZARA_SWARMER + 6) * 10);
    RegisterSpellScriptWithArgs(spell_gen_ayamiss_swarmer_loop, "spell_gen_ayamiss_swarmer_loop_3", (NPC_HIVEZARA_SWARMER + 7) * 10);
}
References NPC_HIVEZARA_SWARMER, RegisterRuinsOfAhnQirajCreatureAI, RegisterSpellScript, and RegisterSpellScriptWithArgs.
Referenced by AddKalimdorScripts().
AddSC_boss_azgalor()
void AddSC_boss_azgalor ()
{
    RegisterHyjalAI(boss_azgalor);
    RegisterSpellAndAuraScriptPair(spell_azgalor_doom, spell_azgalor_doom_aura);
}
References RegisterHyjalAI, and RegisterSpellAndAuraScriptPair.
Referenced by AddKalimdorScripts().
AddSC_boss_azuregos()
void AddSC_boss_azuregos ()
{
    new boss_azuregos();
    RegisterSpellScript(spell_arcane_vacuum);
    RegisterSpellScript(spell_mark_of_frost_freeze);
}
References RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_boss_buru()
void AddSC_boss_buru ()
{
    RegisterRuinsOfAhnQirajCreatureAI(boss_buru);
    RegisterRuinsOfAhnQirajCreatureAI(npc_buru_egg);
    RegisterSpellScript(spell_egg_explosion);
}
References RegisterRuinsOfAhnQirajCreatureAI, and RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_boss_captain_skarloc()
void AddSC_boss_captain_skarloc ()
{
    RegisterOldHillsbradCreatureAI(boss_captain_skarloc);
}
References RegisterOldHillsbradCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_chrono_lord_deja()
void AddSC_boss_chrono_lord_deja ()
{
    RegisterTheBlackMorassCreatureAI(boss_chrono_lord_deja);
}
References RegisterTheBlackMorassCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_cthun()
void AddSC_boss_cthun ()
{
    RegisterTempleOfAhnQirajCreatureAI(boss_eye_of_cthun);
    RegisterTempleOfAhnQirajCreatureAI(boss_cthun);
    RegisterTempleOfAhnQirajCreatureAI(npc_eye_tentacle);
    RegisterTempleOfAhnQirajCreatureAI(npc_claw_tentacle);
    RegisterTempleOfAhnQirajCreatureAI(npc_giant_claw_tentacle);
    RegisterTempleOfAhnQirajCreatureAI(npc_giant_eye_tentacle);
    RegisterSpellScript(spell_cthun_dark_glare);
    RegisterSpellScript(spell_cthun_digestive_acid);
    new at_cthun_stomach_exit();
    new at_cthun_center();
}
References RegisterSpellScript, and RegisterTempleOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_epoch()
void AddSC_boss_epoch ()
{
    new boss_epoch();
}
Referenced by AddKalimdorScripts().
AddSC_boss_epoch_hunter()
void AddSC_boss_epoch_hunter ()
{
    RegisterOldHillsbradCreatureAI(boss_epoch_hunter);
}
References RegisterOldHillsbradCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_fankriss()
void AddSC_boss_fankriss ()
{
    RegisterTempleOfAhnQirajCreatureAI(boss_fankriss);
}
References RegisterTempleOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_huhuran()
void AddSC_boss_huhuran ()
{
    RegisterTempleOfAhnQirajCreatureAI(boss_huhuran);
    RegisterSpellScript(spell_huhuran_wyvern_sting);
    RegisterSpellScript(spell_huhuran_poison_bolt);
}
References RegisterSpellScript, and RegisterTempleOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_infinite_corruptor()
void AddSC_boss_infinite_corruptor ()
{
    new boss_infinite_corruptor();
}
Referenced by AddKalimdorScripts().
AddSC_boss_isalien()
void AddSC_boss_isalien ()
{
    RegisterDireMaulCreatureAI(boss_isalien);
}
References RegisterDireMaulCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_kazrogal()
void AddSC_boss_kazrogal ()
{
    RegisterHyjalAI(boss_kazrogal);
    RegisterSpellAndAuraScriptPair(spell_mark_of_kazrogal, spell_mark_of_kazrogal_aura);
}
References RegisterHyjalAI, and RegisterSpellAndAuraScriptPair.
Referenced by AddKalimdorScripts().
AddSC_boss_kurinnaxx()
void AddSC_boss_kurinnaxx ()
{
    RegisterRuinsOfAhnQirajCreatureAI(boss_kurinnaxx);
    RegisterGameObjectAI(go_sand_trap);
}
References RegisterGameObjectAI, and RegisterRuinsOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_lieutenant_drake()
void AddSC_boss_lieutenant_drake ()
{
    RegisterOldHillsbradCreatureAI(boss_lieutenant_drake);
}
References RegisterOldHillsbradCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_mal_ganis()
void AddSC_boss_mal_ganis ()
{
    new boss_mal_ganis();
}
Referenced by AddKalimdorScripts().
AddSC_boss_meathook()
void AddSC_boss_meathook ()
{
    new boss_meathook();
}
Referenced by AddKalimdorScripts().
AddSC_boss_moam()
void AddSC_boss_moam ()
{
    RegisterRuinsOfAhnQirajCreatureAI(boss_moam);
    RegisterSpellScript(spell_moam_mana_drain_filter);
    RegisterSpellScript(spell_moam_summon_mana_fiends);
}
References RegisterRuinsOfAhnQirajCreatureAI, and RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_boss_onyxia()
void AddSC_boss_onyxia ()
{
    RegisterOnyxiasLairCreatureAI(boss_onyxia);
    RegisterOnyxiasLairCreatureAI(npc_onyxian_lair_guard);
}
References RegisterOnyxiasLairCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_ossirian()
void AddSC_boss_ossirian ()
{
    RegisterRuinsOfAhnQirajCreatureAI(boss_ossirian);
    new go_ossirian_crystal();
    RegisterCreatureAI(npc_anubisath_guardian);
    RegisterSpellScript(spell_crystal_weakness);
    RegisterSpellScript(spell_aq_shadow_storm);
}
References RegisterCreatureAI, RegisterRuinsOfAhnQirajCreatureAI, and RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_boss_ouro()
void AddSC_boss_ouro ()
{
    RegisterTempleOfAhnQirajCreatureAI(npc_ouro_spawner);
    RegisterTempleOfAhnQirajCreatureAI(boss_ouro);
    RegisterTempleOfAhnQirajCreatureAI(npc_dirt_mound);
}
References RegisterTempleOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_rage_winterchill()
void AddSC_boss_rage_winterchill ()
{
    RegisterHyjalAI(boss_rage_winterchill);
}
References RegisterHyjalAI.
Referenced by AddKalimdorScripts().
AddSC_boss_rajaxx()
void AddSC_boss_rajaxx ()
{
    RegisterRuinsOfAhnQirajCreatureAI(boss_rajaxx);
    RegisterSpellScript(spell_rajaxx_thundercrash);
    RegisterRuinsOfAhnQirajCreatureAI(npc_general_andorov);
}
References RegisterRuinsOfAhnQirajCreatureAI, and RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_boss_salramm()
void AddSC_boss_salramm ()
{
    new boss_salramm();
    RegisterSpellScript(spell_boss_salramm_steal_flesh_aura);
}
References RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_boss_sartura()
void AddSC_boss_sartura ()
{
    RegisterTempleOfAhnQirajCreatureAI(boss_sartura);
    RegisterTempleOfAhnQirajCreatureAI(npc_sartura_royal_guard);
}
References RegisterTempleOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_skeram()
void AddSC_boss_skeram ()
{
    RegisterTempleOfAhnQirajCreatureAI(boss_skeram);
    RegisterSpellScript(spell_skeram_arcane_explosion);
}
References RegisterSpellScript, and RegisterTempleOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_temporus()
void AddSC_boss_temporus ()
{
    RegisterTheBlackMorassCreatureAI(boss_temporus);
}
References RegisterTheBlackMorassCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_twinemperors()
void AddSC_boss_twinemperors ()
{
    RegisterTempleOfAhnQirajCreatureAI(boss_veknilash);
    RegisterTempleOfAhnQirajCreatureAI(boss_veklor);
    new at_twin_emperors();
    RegisterSpellScript(spell_mutate_explode_bug);
}
References RegisterSpellScript, and RegisterTempleOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_boss_viscidus()
void AddSC_boss_viscidus ()
{
    RegisterTempleOfAhnQirajCreatureAI(boss_viscidus);
    RegisterTempleOfAhnQirajCreatureAI(boss_glob_of_viscidus);
    RegisterTempleOfAhnQirajCreatureAI(npc_toxic_slime);
    RegisterSpellScript(spell_explode_trigger);
    RegisterSpellScript(spell_summon_toxin_slime);
}
References RegisterSpellScript, and RegisterTempleOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_bug_trio()
void AddSC_bug_trio ()
{
    RegisterTempleOfAhnQirajCreatureAI(boss_kri);
    RegisterTempleOfAhnQirajCreatureAI(boss_vem);
    RegisterTempleOfAhnQirajCreatureAI(boss_yauj);
    RegisterSpellScript(spell_vem_knockback);
    RegisterSpellScript(spell_vem_vengeance);
}
References RegisterSpellScript, and RegisterTempleOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_culling_of_stratholme()
void AddSC_culling_of_stratholme ()
{
    new npc_arthas();
    new npc_crate_helper();
    new npc_cos_chromie_start();
    new npc_cos_chromie_middle();
    new npc_cos_stratholme_citizien();
}
References npc_arthas::npc_arthas().
Referenced by AddKalimdorScripts().
AddSC_darkshore()
void AddSC_darkshore ()
{
    // Ours
    new npc_murkdeep();
    new npc_rabid_thistle_bear();
    new npc_tharnarian();
    // Theirs
    new npc_kerlonian();
    new npc_prospector_remtravel();
}
Referenced by AddKalimdorScripts().
AddSC_desolace()
void AddSC_desolace ()
{
    // Ours
    new npc_cork_gizelton();
    // Theirs
    new npc_aged_dying_ancient_kodo();
}
Referenced by AddKalimdorScripts().
AddSC_durotar()
void AddSC_durotar ()
{
    new npc_tiger_matriarch_credit();
    new npc_tiger_matriarch();
    new npc_troll_volunteer();
    RegisterSpellScript(spell_mount_check_aura);
    RegisterSpellScript(spell_voljin_war_drums);
    RegisterSpellScript(spell_voodoo);
}
References RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_dustwallow_marsh()
void AddSC_dustwallow_marsh ()
{
    RegisterSpellScript(spell_ooze_zap);
    RegisterSpellScript(spell_ooze_zap_channel_end);
    RegisterSpellScript(spell_energize_aoe);
}
References RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_felwood()
void AddSC_felwood ()
{
    new npcs_riverbreeze_and_silversky();
    new at_ancient_leaf();
}
Referenced by AddKalimdorScripts().
AddSC_feralas()
void AddSC_feralas ()
{
    RegisterSpellScript(spell_gordunni_trap);
}
References RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_hyjal()
void AddSC_hyjal ()
{
    new npc_hyjal_jaina();
    new npc_hyjal_thrall();
    new npc_hyjal_tyrande();
    RegisterHyjalAI(npc_hyjal_ground_trash);
    RegisterHyjalAI(npc_hyjal_gargoyle);
    RegisterHyjalAI(npc_hyjal_frost_wyrm);
    RegisterSpellScript(spell_cannibalize_heal);
}
References RegisterHyjalAI, and RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_instance_blackfathom_deeps()
void AddSC_instance_blackfathom_deeps ()
{
    new instance_blackfathom_deeps();
}
Referenced by AddKalimdorScripts().
AddSC_instance_culling_of_stratholme()
void AddSC_instance_culling_of_stratholme ()
{
    new instance_culling_of_stratholme();
}
Referenced by AddKalimdorScripts().
AddSC_instance_dire_maul()
void AddSC_instance_dire_maul ()
{
    new instance_dire_maul();
}
Referenced by AddKalimdorScripts().
AddSC_instance_maraudon()
void AddSC_instance_maraudon ()
{
    new instance_maraudon();
}
Referenced by AddKalimdorScripts().
AddSC_instance_mount_hyjal()
void AddSC_instance_mount_hyjal ()
{
    new instance_hyjal();
}
Referenced by AddKalimdorScripts().
AddSC_instance_old_hillsbrad()
void AddSC_instance_old_hillsbrad ()
{
    new instance_old_hillsbrad();
}
Referenced by AddKalimdorScripts().
AddSC_instance_onyxias_lair()
void AddSC_instance_onyxias_lair ()
{
    new instance_onyxias_lair();
}
Referenced by AddKalimdorScripts().
AddSC_instance_ragefire_chasm()
void AddSC_instance_ragefire_chasm ()
{
    new instance_ragefire_chasm();
}
Referenced by AddKalimdorScripts().
AddSC_instance_razorfen_downs()
void AddSC_instance_razorfen_downs ()
{
    new instance_razorfen_downs();
}
Referenced by AddKalimdorScripts().
AddSC_instance_razorfen_kraul()
void AddSC_instance_razorfen_kraul ()
{
    new instance_razorfen_kraul();
}
Referenced by AddKalimdorScripts().
AddSC_instance_ruins_of_ahnqiraj()
void AddSC_instance_ruins_of_ahnqiraj ()
{
    new instance_ruins_of_ahnqiraj();
}
Referenced by AddKalimdorScripts().
AddSC_instance_temple_of_ahnqiraj()
void AddSC_instance_temple_of_ahnqiraj ()
{
    new instance_temple_of_ahnqiraj();
}
Referenced by AddKalimdorScripts().
AddSC_instance_the_black_morass()
void AddSC_instance_the_black_morass ()
{
    new instance_the_black_morass();
}
Referenced by AddKalimdorScripts().
AddSC_instance_wailing_caverns()
void AddSC_instance_wailing_caverns ()
{
    new instance_wailing_caverns();
}
Referenced by AddKalimdorScripts().
AddSC_instance_zulfarrak()
void AddSC_instance_zulfarrak ()
{
    new instance_zulfarrak();
    RegisterSpellScript(spell_zulfarrak_summon_zulfarrak_zombies);
    RegisterSpellScript(spell_zulfarrak_unlocking);
}
References RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_moonglade()
void AddSC_moonglade ()
{
    new npc_bunthen_plainswind();
    new npc_great_bear_spirit();
    new npc_silva_filnaveth();
    new npc_clintar_spirit();
    new npc_omen();
    new npc_giant_spotlight();
}
Referenced by AddKalimdorScripts().
AddSC_npc_anubisath_sentinel()
void AddSC_npc_anubisath_sentinel ()
{
    new npc_anubisath_sentinel();
    RegisterSpellScript(spell_anubisath_mortal_strike);
    RegisterSpellScript(spell_mana_burn_area);
}
References RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_old_hillsbrad()
void AddSC_old_hillsbrad ()
{
    new npc_thrall_old_hillsbrad();
    new npc_taretha();
}
Referenced by AddKalimdorScripts().
AddSC_orgrimmar()
void AddSC_orgrimmar ()
{
    new npc_shenthul();
    new npc_thrall_warchief();
}
Referenced by AddKalimdorScripts().
AddSC_razorfen_downs()
void AddSC_razorfen_downs ()
{
    new npc_belnistrasz();
    new npc_idol_room_spawner();
}
Referenced by AddKalimdorScripts().
AddSC_ruins_of_ahnqiraj()
void AddSC_ruins_of_ahnqiraj ()
{
    RegisterRuinsOfAhnQirajCreatureAI(npc_hivezara_stinger);
    RegisterRuinsOfAhnQirajCreatureAI(npc_obsidian_destroyer);
    RegisterSpellScript(spell_drain_mana);
}
References RegisterRuinsOfAhnQirajCreatureAI, and RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_silithus()
void AddSC_silithus ()
{
    new go_crystalline_tear();
    new npc_anachronos_quest_trigger();
    new npc_anachronos_the_ancient();
    new npc_qiraj_war_spawn();
    new go_wind_stone();
}
References npc_qiraj_war_spawn::npc_qiraj_war_spawn().
Referenced by AddKalimdorScripts().
AddSC_stonetalon_mountains()
void AddSC_stonetalon_mountains ()
{
    new npc_braug_dimspirit();
    new npc_kaya_flathoof();
}
Referenced by AddKalimdorScripts().
AddSC_tanaris()
void AddSC_tanaris ()
{
    new npc_aquementas();
    new npc_custodian_of_time();
    new npc_steward_of_time();
    new npc_stone_watcher_of_norgannon();
    new npc_tooga();
}
Referenced by AddKalimdorScripts().
AddSC_temple_of_ahnqiraj()
void AddSC_temple_of_ahnqiraj ()
{
    RegisterTempleOfAhnQirajCreatureAI(npc_anubisath_defender);
    RegisterTempleOfAhnQirajCreatureAI(npc_vekniss_stinger);
    RegisterTempleOfAhnQirajCreatureAI(npc_obsidian_eradicator);
    RegisterTempleOfAhnQirajCreatureAI(npc_anubisath_warder);
    RegisterTempleOfAhnQirajCreatureAI(npc_obsidian_nullifier);
    RegisterTempleOfAhnQirajCreatureAI(npc_ahnqiraji_critter);
    RegisterSpellScript(spell_aggro_drones);
    RegisterSpellScript(spell_nullify);
    new at_battleguard_sartura();
}
References RegisterSpellScript, and RegisterTempleOfAhnQirajCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_the_barrens()
void AddSC_the_barrens ()
{
    new npc_gilthares();
    new npc_taskmaster_fizzule();
    new npc_twiggy_flathead();
    new npc_wizzlecrank_shredder();
}
Referenced by AddKalimdorScripts().
AddSC_the_black_morass()
void AddSC_the_black_morass ()
{
    RegisterTheBlackMorassCreatureAI(npc_medivh_bm);
    RegisterTheBlackMorassCreatureAI(npc_time_rift);
    RegisterTheBlackMorassCreatureAI(npc_black_morass_summoned_add);
    RegisterSpellScript(spell_black_morass_corrupt_medivh);
}
References RegisterSpellScript, and RegisterTheBlackMorassCreatureAI.
Referenced by AddKalimdorScripts().
AddSC_thousand_needles()
void AddSC_thousand_needles ()
{
    new npc_lakota_windsong();
    new npc_paoka_swiftmountain();
    new npc_plucky();
    RegisterSpellScript(spell_panther_cage_key);
}
References RegisterSpellScript.
Referenced by AddKalimdorScripts().
AddSC_thunder_bluff()
void AddSC_thunder_bluff ()
{
    new npc_cairne_bloodhoof();
}
Referenced by AddKalimdorScripts().
AddSC_ungoro_crater()
void AddSC_ungoro_crater ()
{
    new npc_ame();
    new npc_ringo();
}
Referenced by AddKalimdorScripts().
AddSC_winterspring()
void AddSC_winterspring ()
{
    // Theirs
    new npc_rivern_frostwind();
    new npc_ranshalla();
    new go_elune_fire();
}
Referenced by AddKalimdorScripts().
AddSC_zulfarrak()
void AddSC_zulfarrak ()
{
    new npc_sergeant_bly();
    new npc_weegli_blastfuse();
    new npc_shadowpriest_sezziz();
    new go_troll_cage();
}
Referenced by AddKalimdorScripts().