AzerothCore: TemporaryThreatModifierEvent Class Reference
TemporaryThreatModifierEvent Class Reference
#include "Creature.h"
Public Member Functions
TemporaryThreatModifierEvent (Creature &owner, ObjectGuid threatVictimGUID, float threatValue)
bool Execute (uint64 e_time, uint32 p_time) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature & m_owner
ObjectGuid m_threatVictimGUID
float m_threatValue
Detailed Description
Constructor & Destructor Documentation
TemporaryThreatModifierEvent()
TemporaryThreatModifierEvent::TemporaryThreatModifierEvent (Creature & owner, ObjectGuid threatVictimGUID, float threatValue) inline
: BasicEvent(), m_owner(owner), m_threatVictimGUID(threatVictimGUID), m_threatValue(threatValue) { }
Member Function Documentation
Execute()
bool TemporaryThreatModifierEvent::Execute (uint64 e_time, uint32 p_time) override virtual
Reimplemented from BasicEvent.
{
    if (Unit* victim = ObjectAccessor::GetUnit(m_owner, m_threatVictimGUID))
    {
        if (m_owner.IsInCombatWith(victim))
        {
            m_owner.GetThreatMgr().ModifyThreatByPercent(victim, -100); // Reset threat to zero.
            m_owner.GetThreatMgr().AddThreat(victim, m_threatValue);  // Set to the previous value it had, first before modification.
        }
    }
    return true;
}
References ThreatMgr::AddThreat(), Unit::GetThreatMgr(), ObjectAccessor::GetUnit(), Unit::IsInCombatWith(), m_owner, m_threatValue, m_threatVictimGUID, and ThreatMgr::ModifyThreatByPercent().
Member Data Documentation
m_owner
Creature& TemporaryThreatModifierEvent::m_owner private
Referenced by Execute().
m_threatValue
float TemporaryThreatModifierEvent::m_threatValue private
Referenced by Execute().
m_threatVictimGUID
ObjectGuid TemporaryThreatModifierEvent::m_threatVictimGUID private
Referenced by Execute().