AzerothCore: AllCreatureScript Class Reference
AllCreatureScript Class Reference
#include "AllCreatureScript.h"
Public Member Functions
virtual void OnAllCreatureUpdate (Creature *, uint32)
virtual void OnBeforeCreatureSelectLevel (const CreatureTemplate *, Creature *, uint8 &)
virtual void Creature_SelectLevel (const CreatureTemplate *, Creature *)
virtual void OnCreatureAddWorld (Creature *)
This hook runs after add creature in world.
virtual void OnCreatureRemoveWorld (Creature *)
This hook runs after remove creature in world.
virtual void OnCreatureSaveToDB (Creature *)
This hook runs after creature has been saved to DB.
virtual bool CanCreatureGossipHello (Player *, Creature *)
This hook called when a player opens a gossip dialog with the creature.
virtual bool CanCreatureGossipSelect (Player *, Creature *, uint32, uint32)
This hook called when a player selects a gossip item in the creature's gossip menu.
virtual bool CanCreatureGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
This hook called when a player selects a gossip with a code in the creature's gossip menu.
virtual bool CanCreatureQuestAccept (Player *, Creature *, Quest const *)
virtual bool CanCreatureQuestReward (Player *, Creature *, Quest const *, uint32)
virtual CreatureAI * GetCreatureAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Protected Member Functions
AllCreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
AllCreatureScript()
AllCreatureScript::AllCreatureScript (const char * name) protected
                                                     :
    ScriptObject(name)
{
    ScriptRegistry<AllCreatureScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanCreatureGossipHello()
virtual bool AllCreatureScript::CanCreatureGossipHello (Player * , Creature *) inline virtual
This hook called when a player opens a gossip dialog with the creature.
Parameters
player Contains information about the Player
creature Contains information about the Creature
Returns
False if you want to continue, true if you want to disable
{ return false; }
Referenced by ScriptMgr::OnGossipHello().
CanCreatureGossipSelect()
virtual bool AllCreatureScript::CanCreatureGossipSelect (Player * , Creature * , uint32 , uint32) inline virtual
This hook called when a player selects a gossip item in the creature's gossip menu.
Parameters
player Contains information about the Player
creature Contains information about the Creature
sender Contains information about the sender type
action Contains information about the action id
Returns
False if you want to continue, true if you want to disable
{ return false; }
Referenced by ScriptMgr::OnGossipSelect().
CanCreatureGossipSelectCode()
virtual bool AllCreatureScript::CanCreatureGossipSelectCode (Player * , Creature * , uint32 , uint32 , const char *) inline virtual
This hook called when a player selects a gossip with a code in the creature's gossip menu.
Parameters
player Contains information about the Player
creature Contains information about the Creature
sender Contains information about the sender type
action Contains information about the action id
code Contains information about the code entered
Returns
True if you want to continue, false if you want to disable
{ return false; }
Referenced by ScriptMgr::OnGossipSelectCode().
CanCreatureQuestAccept()
virtual bool AllCreatureScript::CanCreatureQuestAccept (Player * , Creature * , Quest const *) inline virtual
{ return false; }
Referenced by ScriptMgr::OnQuestAccept().
CanCreatureQuestReward()
virtual bool AllCreatureScript::CanCreatureQuestReward (Player * , Creature * , Quest const * , uint32) inline virtual
{ return false; }
Referenced by ScriptMgr::OnQuestReward().
Creature_SelectLevel()
virtual void AllCreatureScript::Creature_SelectLevel (const CreatureTemplate * , Creature *) inline virtual
{ }
Referenced by ScriptMgr::Creature_SelectLevel().
GetCreatureAI()
virtual CreatureAI * AllCreatureScript::GetCreatureAI (Creature *) const inline virtual
{ return nullptr; }
Referenced by ScriptMgr::GetCreatureAI().
OnAllCreatureUpdate()
virtual void AllCreatureScript::OnAllCreatureUpdate (Creature * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnCreatureUpdate().
OnBeforeCreatureSelectLevel()
virtual void AllCreatureScript::OnBeforeCreatureSelectLevel (const CreatureTemplate * , Creature * , uint8 &) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeCreatureSelectLevel().
OnCreatureAddWorld()
virtual void AllCreatureScript::OnCreatureAddWorld (Creature *) inline virtual
This hook runs after add creature in world.
Parameters
creature Contains information about the Creature
{ }
Referenced by ScriptMgr::OnCreatureAddWorld().
OnCreatureRemoveWorld()
virtual void AllCreatureScript::OnCreatureRemoveWorld (Creature *) inline virtual
This hook runs after remove creature in world.
Parameters
creature Contains information about the Creature
{ }
Referenced by ScriptMgr::OnCreatureRemoveWorld().
OnCreatureSaveToDB()
virtual void AllCreatureScript::OnCreatureSaveToDB (Creature *) inline virtual
This hook runs after creature has been saved to DB.
Parameters
creature Contains information about the Creature
{ }
Referenced by ScriptMgr::OnCreatureSaveToDB().
OnFfaPvpStateUpdate()
virtual void AllCreatureScript::OnFfaPvpStateUpdate (Creature * , bool) inline virtual
{}
Referenced by ScriptMgr::OnFfaPvpStateUpdate().