AzerothCore: AllGameObjectScript Class Reference
AllGameObjectScript Class Reference
#include "AllGameObjectScript.h"
Public Member Functions
virtual void OnGameObjectAddWorld (GameObject *)
This hook runs after add game object in world.
virtual void OnGameObjectSaveToDB (GameObject *)
This hook runs after the game object iis saved to the database.
virtual void OnGameObjectRemoveWorld (GameObject *)
This hook runs after remove game object in world.
virtual void OnGameObjectUpdate (GameObject *, uint32)
This hook runs after remove game object in world.
virtual bool CanGameObjectGossipHello (Player *, GameObject *)
virtual bool CanGameObjectGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool CanGameObjectGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool CanGameObjectQuestAccept (Player *, GameObject *, Quest const *)
virtual bool CanGameObjectQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual void OnGameObjectDestroyed (GameObject *, Player *)
virtual void OnGameObjectDamaged (GameObject *, Player *)
virtual void OnGameObjectModifyHealth (GameObject *, Unit *, int32 &, SpellInfo const *)
virtual void OnGameObjectLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetGameObjectAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Protected Member Functions
AllGameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
AllGameObjectScript()
AllGameObjectScript::AllGameObjectScript (const char * name) protected
                                                         :
    ScriptObject(name)
{
    ScriptRegistry<AllGameObjectScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanGameObjectGossipHello()
virtual bool AllGameObjectScript::CanGameObjectGossipHello (Player * , GameObject *) inline virtual
{ return false; }
Referenced by ScriptMgr::OnGossipHello().
CanGameObjectGossipSelect()
virtual bool AllGameObjectScript::CanGameObjectGossipSelect (Player * , GameObject * , uint32 , uint32) inline virtual
{ return false; }
Referenced by ScriptMgr::OnGossipSelect().
CanGameObjectGossipSelectCode()
virtual bool AllGameObjectScript::CanGameObjectGossipSelectCode (Player * , GameObject * , uint32 , uint32 , const char *) inline virtual
{ return false; }
Referenced by ScriptMgr::OnGossipSelectCode().
CanGameObjectQuestAccept()
virtual bool AllGameObjectScript::CanGameObjectQuestAccept (Player * , GameObject * , Quest const *) inline virtual
{ return false; }
Referenced by ScriptMgr::OnQuestAccept().
CanGameObjectQuestReward()
virtual bool AllGameObjectScript::CanGameObjectQuestReward (Player * , GameObject * , Quest const * , uint32) inline virtual
{ return false; }
Referenced by ScriptMgr::OnQuestReward().
GetGameObjectAI()
virtual GameObjectAI * AllGameObjectScript::GetGameObjectAI (GameObject *) const inline virtual
{ return nullptr; }
Referenced by ScriptMgr::GetGameObjectAI().
OnGameObjectAddWorld()
virtual void AllGameObjectScript::OnGameObjectAddWorld (GameObject *) inline virtual
This hook runs after add game object in world.
Parameters
go Contains information about the GameObject
{ }
Referenced by ScriptMgr::OnGameObjectAddWorld().
OnGameObjectDamaged()
virtual void AllGameObjectScript::OnGameObjectDamaged (GameObject * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnGameObjectDamaged().
OnGameObjectDestroyed()
virtual void AllGameObjectScript::OnGameObjectDestroyed (GameObject * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnGameObjectDestroyed().
OnGameObjectLootStateChanged()
virtual void AllGameObjectScript::OnGameObjectLootStateChanged (GameObject * , uint32 , Unit *) inline virtual
{ }
Referenced by ScriptMgr::OnGameObjectLootStateChanged().
OnGameObjectModifyHealth()
virtual void AllGameObjectScript::OnGameObjectModifyHealth (GameObject * , Unit * , int32 & , SpellInfo const *) inline virtual
{ }
Referenced by ScriptMgr::OnGameObjectModifyHealth().
OnGameObjectRemoveWorld()
virtual void AllGameObjectScript::OnGameObjectRemoveWorld (GameObject *) inline virtual
This hook runs after remove game object in world.
Parameters
go Contains information about the GameObject
{ }
Referenced by ScriptMgr::OnGameObjectRemoveWorld().
OnGameObjectSaveToDB()
virtual void AllGameObjectScript::OnGameObjectSaveToDB (GameObject *) inline virtual
This hook runs after the game object iis saved to the database.
Parameters
go Contains information about the GameObject
{ }
Referenced by ScriptMgr::OnGameObjectSaveToDB().
OnGameObjectStateChanged()
virtual void AllGameObjectScript::OnGameObjectStateChanged (GameObject * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnGameObjectStateChanged().
OnGameObjectUpdate()
virtual void AllGameObjectScript::OnGameObjectUpdate (GameObject * , uint32) inline virtual
This hook runs after remove game object in world.
Parameters
go Contains information about the GameObject
{ }
Referenced by ScriptMgr::OnGameObjectUpdate().