AzerothCore: Acore::AIRelocationNotifier Struct Reference
Acore::AIRelocationNotifier Struct Reference
#include "GridNotifiers.h"
Public Member Functions
AIRelocationNotifier (Unit &unit)
template<class T >
void Visit (GridRefMgr< T > &)
void Visit (CreatureMapType &)
Public Attributes
Unit & i_unit
bool isCreature
Detailed Description
Constructor & Destructor Documentation
AIRelocationNotifier()
Acore::AIRelocationNotifier::AIRelocationNotifier (Unit & unit) inline explicit
: i_unit(unit), isCreature(unit.IsCreature())  {}
Member Function Documentation
Visit() [1/2]
void AIRelocationNotifier::Visit (CreatureMapType & m)
{
    bool self = isCreature && !((Creature*)(&i_unit))->IsMoveInLineOfSightStrictlyDisabled();
    for (CreatureMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
    {
        Creature* c = iter->GetSource();
        // NOTIFY_VISIBILITY_CHANGED | NOTIFY_AI_RELOCATION does not guarantee that unit will do it itself (because distance is also checked), but screw it, it's not that important
        if (!c->isNeedNotify(NOTIFY_VISIBILITY_CHANGED | NOTIFY_AI_RELOCATION) && !c->IsMoveInLineOfSightStrictlyDisabled())
            CreatureUnitRelocationWorker(c, &i_unit);
        if (self)
            CreatureUnitRelocationWorker((Creature*)&i_unit, c);
    }
}
References GridRefMgr< OBJECT >::begin(), CreatureUnitRelocationWorker(), GridRefMgr< OBJECT >::end(), i_unit, isCreature, Creature::IsMoveInLineOfSightStrictlyDisabled(), WorldObject::isNeedNotify(), NOTIFY_AI_RELOCATION, and NOTIFY_VISIBILITY_CHANGED.
Visit() [2/2]
template<class T > void Acore::AIRelocationNotifier::Visit (GridRefMgr< T > &) inline
{}
Member Data Documentation
i_unit
Unit& Acore::AIRelocationNotifier::i_unit
Referenced by Visit().
isCreature
bool Acore::AIRelocationNotifier::isCreature
Referenced by Visit().