AzerothCore: npc_pilgrims_bounty_chair Struct Reference
npc_pilgrims_bounty_chair Struct Reference
Public Member Functions
npc_pilgrims_bounty_chair (Creature *creature)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void PassengerBoarded (Unit *who, int8, bool apply) override
== Fields =======================================
Creature * GetPlate ()
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void DoAction (int32 param) override
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
ObjectGuid plateGUID
uint32 timerSpawnPlate
uint32 timerRotateChair
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from VehicleAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_pilgrims_bounty_chair()
npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chair (Creature * creature) inline
                                                  : VehicleAI(creature)
    {
        plateGUID.Clear();
        timerSpawnPlate = 1;
        timerRotateChair = 0;
        me->SetReactState(REACT_PASSIVE);
    }
References ObjectGuid::Clear(), CreatureAI::me, plateGUID, REACT_PASSIVE, Creature::SetReactState(), timerRotateChair, and timerSpawnPlate.
Member Function Documentation
AttackStart()
void npc_pilgrims_bounty_chair::AttackStart (Unit *) inline override virtual
Reimplemented from VehicleAI.
{}
DamageTaken()
void npc_pilgrims_bounty_chair::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
    {
        damage = 0;
    }
DoAction()
void npc_pilgrims_bounty_chair::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
    {
        switch (param)
        {
            case SPELL_VISUAL_THROW_TURKEY:
            case SPELL_VISUAL_BOUNCE_TURKEY:
                me->CastSpell(me, SPELL_STORE_TURKEY, true);
                me->CastSpell(me, SPELL_CAN_EAT_TURKEY, true);
                if (Unit* plate = GetPlate())
                    plate->CastSpell(plate, SPELL_PLATE_TURKEY, true);
                break;
            case SPELL_VISUAL_THROW_STUFFING:
            case SPELL_VISUAL_BOUNCE_STUFFING:
                me->CastSpell(me, SPELL_STORE_STUFFING, true);
                me->CastSpell(me, SPELL_CAN_EAT_STUFFING, true);
                if (Unit* plate = GetPlate())
                    plate->CastSpell(plate, SPELL_PLATE_STUFFING, true);
                break;
            case SPELL_VISUAL_THROW_PIE:
            case SPELL_VISUAL_BOUNCE_PIE:
                me->CastSpell(me, SPELL_STORE_PIE, true);
                me->CastSpell(me, SPELL_CAN_EAT_PIE, true);
                if (Unit* plate = GetPlate())
                    plate->CastSpell(plate, SPELL_PLATE_PIE, true);
                break;
            case SPELL_VISUAL_THROW_CRANBERRY:
            case SPELL_VISUAL_BOUNCE_CRANBERRY:
                me->CastSpell(me, SPELL_STORE_CRANBERRY, true);
                me->CastSpell(me, SPELL_CAN_EAT_CRANBERRY, true);
                if (Unit* plate = GetPlate())
                    plate->CastSpell(plate, SPELL_PLATE_CRANBERRY, true);
                break;
            case SPELL_VISUAL_THROW_SWEET_POTATO:
            case SPELL_VISUAL_BOUNCE_SWEET_POTATO:
                me->CastSpell(me, SPELL_STORE_SWEET_POTATO, true);
                me->CastSpell(me, SPELL_CAN_EAT_SWEET_POTATO, true);
                if (Unit* plate = GetPlate())
                    plate->CastSpell(plate, SPELL_PLATE_SWEET_POTATO, true);
                break;
            // AURA REMOVAL
            case SPELL_STORE_SWEET_POTATO:
                me->RemoveAura(SPELL_CAN_EAT_SWEET_POTATO);
                if (Unit* plate = GetPlate())
                    plate->RemoveAura(SPELL_PLATE_SWEET_POTATO);
                break;
            case SPELL_STORE_TURKEY:
                me->RemoveAura(SPELL_CAN_EAT_TURKEY);
                if (Unit* plate = GetPlate())
                    plate->RemoveAura(SPELL_PLATE_TURKEY);
                break;
            case SPELL_STORE_PIE:
                me->RemoveAura(SPELL_CAN_EAT_PIE);
                if (Unit* plate = GetPlate())
                    plate->RemoveAura(SPELL_PLATE_PIE);
                break;
            case SPELL_STORE_STUFFING:
                me->RemoveAura(SPELL_CAN_EAT_STUFFING);
                if (Unit* plate = GetPlate())
                    plate->RemoveAura(SPELL_PLATE_STUFFING);
                break;
            case SPELL_STORE_CRANBERRY:
                me->RemoveAura(SPELL_CAN_EAT_CRANBERRY);
                if (Unit* plate = GetPlate())
                    plate->RemoveAura(SPELL_PLATE_CRANBERRY);
                break;
        }
    }
References Unit::CastSpell(), GetPlate(), CreatureAI::me, Unit::RemoveAura(), SPELL_CAN_EAT_CRANBERRY, SPELL_CAN_EAT_PIE, SPELL_CAN_EAT_STUFFING, SPELL_CAN_EAT_SWEET_POTATO, SPELL_CAN_EAT_TURKEY, SPELL_PLATE_CRANBERRY, SPELL_PLATE_PIE, SPELL_PLATE_STUFFING, SPELL_PLATE_SWEET_POTATO, SPELL_PLATE_TURKEY, SPELL_STORE_CRANBERRY, SPELL_STORE_PIE, SPELL_STORE_STUFFING, SPELL_STORE_SWEET_POTATO, SPELL_STORE_TURKEY, SPELL_VISUAL_BOUNCE_CRANBERRY, SPELL_VISUAL_BOUNCE_PIE, SPELL_VISUAL_BOUNCE_STUFFING, SPELL_VISUAL_BOUNCE_SWEET_POTATO, SPELL_VISUAL_BOUNCE_TURKEY, SPELL_VISUAL_THROW_CRANBERRY, SPELL_VISUAL_THROW_PIE, SPELL_VISUAL_THROW_STUFFING, SPELL_VISUAL_THROW_SWEET_POTATO, and SPELL_VISUAL_THROW_TURKEY.
GetPlate()
Creature * npc_pilgrims_bounty_chair::GetPlate () inline
{ return plateGUID ? ObjectAccessor::GetCreature(*me, plateGUID) : nullptr; }
References ObjectAccessor::GetCreature(), CreatureAI::me, and plateGUID.
Referenced by DoAction(), and UpdateAI().
MoveInLineOfSight()
void npc_pilgrims_bounty_chair::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from VehicleAI.
{}
PassengerBoarded()
void npc_pilgrims_bounty_chair::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
    {
        if (apply && who->IsPlayer())
            who->ToPlayer()->SetClientControl(me, 0, true);
    }
References Object::IsPlayer(), CreatureAI::me, Player::SetClientControl(), and Object::ToPlayer().
SpellHit()
void npc_pilgrims_bounty_chair::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from CreatureAI.
    {
        switch (spellInfo->Id)
        {
            case SPELL_FEAST_ON_SWEET_POTATOES:
                if (Aura* aur = me->GetAura(SPELL_STORE_SWEET_POTATO))
                    aur->ModStackAmount(-1);
                break;
            case SPELL_FEAST_ON_TURKEY:
                if (Aura* aur = me->GetAura(SPELL_STORE_TURKEY))
                    aur->ModStackAmount(-1);
                break;
            case SPELL_FEAST_ON_PIE:
                if (Aura* aur = me->GetAura(SPELL_STORE_PIE))
                    aur->ModStackAmount(-1);
                break;
            case SPELL_FEAST_ON_STUFFING:
                if (Aura* aur = me->GetAura(SPELL_STORE_STUFFING))
                    aur->ModStackAmount(-1);
                break;
            case SPELL_FEAST_ON_CRANBERRY:
                if (Aura* aur = me->GetAura(SPELL_STORE_CRANBERRY))
                    aur->ModStackAmount(-1);
                break;
        }
    }
References Unit::GetAura(), SpellInfo::Id, CreatureAI::me, SPELL_FEAST_ON_CRANBERRY, SPELL_FEAST_ON_PIE, SPELL_FEAST_ON_STUFFING, SPELL_FEAST_ON_SWEET_POTATOES, SPELL_FEAST_ON_TURKEY, SPELL_STORE_CRANBERRY, SPELL_STORE_PIE, SPELL_STORE_STUFFING, SPELL_STORE_SWEET_POTATO, and SPELL_STORE_TURKEY.
SpellHitTarget()
void npc_pilgrims_bounty_chair::SpellHitTarget (Unit * target, SpellInfo const * spellInfo) inline override virtual
Reimplemented from CreatureAI.
    {
        Unit* charm = target->GetCharm();
        if (!charm || !charm->ToCreature())
            return;
        charm->ToCreature()->AI()->DoAction(spellInfo->Id);
    }
References Creature::AI(), UnitAI::DoAction(), Unit::GetCharm(), SpellInfo::Id, and Object::ToCreature().
UpdateAI()
void npc_pilgrims_bounty_chair::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from VehicleAI.
    {
        if (timerSpawnPlate)
        {
            timerSpawnPlate += diff;
            if (timerSpawnPlate >= 1000)
            {
                if (Vehicle* table = me->GetVehicle())
                    if (Unit* plateHolder = table->GetPassenger(6))
                    {
                        SeatMap::const_iterator itr = table->GetSeatIteratorForPassenger(me);
                        if (itr == table->Seats.end())
                            return;
                        uint8 vehicleSeatId = itr->first;
                        Creature* plate = me->SummonCreature(NPC_STRUDY_PLATE, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0.0f);
                        if (!plate)
                            return;
                        plateGUID = plate->GetGUID();
                        plate->EnterVehicle(plateHolder, vehicleSeatId);
                        timerSpawnPlate = 0;
                        timerRotateChair = 1;
                    }
            }
        }
        if (timerRotateChair)
        {
            timerRotateChair += diff;
            if (timerRotateChair >= 1000)
            {
                if (Creature* plate = GetPlate())
                    me->SetFacingToObject(plate);
                timerRotateChair = 0;
            }
        }
    }
References Unit::EnterVehicle(), Object::GetGUID(), GetPlate(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicle(), CreatureAI::me, NPC_STRUDY_PLATE, plateGUID, Unit::SetFacingToObject(), WorldObject::SummonCreature(), timerRotateChair, and timerSpawnPlate.
Member Data Documentation
plateGUID
ObjectGuid npc_pilgrims_bounty_chair::plateGUID
Referenced by GetPlate(), npc_pilgrims_bounty_chair(), and UpdateAI().
timerRotateChair
uint32 npc_pilgrims_bounty_chair::timerRotateChair
Referenced by npc_pilgrims_bounty_chair(), and UpdateAI().
timerSpawnPlate
uint32 npc_pilgrims_bounty_chair::timerSpawnPlate
Referenced by npc_pilgrims_bounty_chair(), and UpdateAI().