AzerothCore: GmTicket Class Reference
GmTicket Class Reference
#include "TicketMgr.h"
Public Member Functions
GmTicket ()
GmTicket (Player *player)
~GmTicket ()
bool IsClosed () const
bool IsCompleted () const
bool IsFromPlayer (ObjectGuid guid) const
bool IsAssigned () const
bool IsAssignedTo (ObjectGuid guid) const
bool IsAssignedNotTo (ObjectGuid guid) const
uint32 GetId () const
Player * GetPlayer () const
std::string const & GetPlayerName () const
std::string const & GetMessage () const
Player * GetAssignedPlayer () const
ObjectGuid GetAssignedToGUID () const
std::string GetAssignedToName () const
uint64 GetLastModifiedTime () const
GMTicketEscalationStatus GetEscalatedStatus () const
void SetEscalatedStatus (GMTicketEscalationStatus escalatedStatus)
void SetAssignedTo (ObjectGuid guid, bool isAdmin)
void SetClosedBy (ObjectGuid value)
void SetResolvedBy (ObjectGuid value)
void SetCompleted ()
void SetMessage (std::string const &message)
void SetComment (std::string const &comment)
void SetViewed ()
void SetUnassigned ()
void SetPosition (uint32 mapId, float x, float y, float z)
void SetGmAction (uint32 needResponse, bool needMoreHelp)
void AppendResponse (std::string const &response)
std::string GetResponse ()
void DeleteResponse ()
bool LoadFromDB (Field *fields)
void SaveToDB (CharacterDatabaseTransaction trans) const
void DeleteFromDB ()
void WritePacket (WorldPacket &data) const
void SendResponse (WorldSession *session) const
void TeleportTo (Player *player) const
std::string FormatMessageString (ChatHandler &handler, bool detailed=false) const
std::string FormatMessageString (ChatHandler &handler, const char *szClosedName, const char *szAssignedToName, const char *szUnassignedName, const char *szDeletedName) const
void SetChatLog (std::list< uint32 > time, std::string const &log)
std::string const & GetChatLog () const
Private Attributes
uint32 _id
ObjectGuid _playerGuid
TicketType _type
std::string _playerName
float _posX
float _posY
float _posZ
uint16 _mapId
std::string _message
uint64 _createTime
uint64 _lastModifiedTime
ObjectGuid _closedBy
ObjectGuid _resolvedBy
ObjectGuid _assignedTo
std::string _comment
bool _completed
GMTicketEscalationStatus _escalatedStatus
bool _viewed
bool _needResponse
bool _needMoreHelp
std::string _response
std::string _chatLog
Detailed Description
Constructor & Destructor Documentation
GmTicket() [1/2]
GmTicket::GmTicket ()
                   : _id(0), _type(TICKET_TYPE_OPEN), _posX(0), _posY(0), _posZ(0), _mapId(0), _createTime(0), _lastModifiedTime(0),
    _completed(false), _escalatedStatus(TICKET_UNASSIGNED), _viewed(false), _needResponse(false), _needMoreHelp(false) { }
GmTicket() [2/2]
GmTicket::GmTicket (Player * player)
                                 : _type(TICKET_TYPE_OPEN), _createTime(GameTime::GetGameTime().count()), _lastModifiedTime(GameTime::GetGameTime().count()),
    _completed(false), _escalatedStatus(TICKET_UNASSIGNED), _viewed(false), _needMoreHelp(false)
{
    _id = sTicketMgr->GenerateTicketId();
    _playerName = player->GetName();
    _playerGuid = player->GetGUID();
}
References _id, _playerGuid, _playerName, Object::GetGUID(), WorldObject::GetName(), and sTicketMgr.
~GmTicket()
GmTicket::~GmTicket ()
{ }
Member Function Documentation
AppendResponse()
void GmTicket::AppendResponse (std::string const & response) inline
{ _response += response; }
References _response.
Referenced by ticket_commandscript::HandleGMTicketCompleteCommand(), and ticket_commandscript::TicketResponseAppend().
DeleteFromDB()
void GmTicket::DeleteFromDB ()
{
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GM_TICKET);
    stmt->SetData(0, _id);
    CharacterDatabase.Execute(stmt);
}
References _id, CHAR_DEL_GM_TICKET, CharacterDatabase, and PreparedStatementBase::SetData().
DeleteResponse()
void GmTicket::DeleteResponse () inline
{ _response = ""; }
References _response.
Referenced by ticket_commandscript::HandleGMTicketResponseDeleteCommand().
FormatMessageString() [1/2]
std::string GmTicket::FormatMessageString (ChatHandler & handler, bool detailed = false) const
{
    time_t curTime = GameTime::GetGameTime().count();
    std::stringstream ss;
    ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTGUID, _id);
    ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTNAME, _playerName.c_str());
    ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTAGECREATE, (secsToTimeString(curTime - _createTime, true)).c_str());
    ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTAGE, (secsToTimeString(curTime - _lastModifiedTime, true)).c_str());
    std::string name;
    if (sCharacterCache->GetCharacterNameByGuid(_assignedTo, name))
    {
        ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTASSIGNEDTO, name.c_str());
    }
    if (detailed)
    {
        ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTMESSAGE, _message.c_str());
        if (!_comment.empty())
            ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTCOMMENT, _comment.c_str());
        if (!_response.empty())
            ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTRESPONSE, _response.c_str());
    }
    return ss.str();
}
References _assignedTo, _comment, _createTime, _id, _lastModifiedTime, _message, _playerName, _response, GameTime::GetGameTime(), LANG_COMMAND_TICKETLISTAGE, LANG_COMMAND_TICKETLISTAGECREATE, LANG_COMMAND_TICKETLISTASSIGNEDTO, LANG_COMMAND_TICKETLISTCOMMENT, LANG_COMMAND_TICKETLISTGUID, LANG_COMMAND_TICKETLISTMESSAGE, LANG_COMMAND_TICKETLISTNAME, LANG_COMMAND_TICKETLISTRESPONSE, ChatHandler::PGetParseString(), sCharacterCache, and secsToTimeString().
Referenced by ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketGetByIdCommand(), ticket_commandscript::HandleGMTicketGetByNameCommand(), ticket_commandscript::HandleGMTicketResponseDeleteCommand(), ticket_commandscript::HandleGMTicketResponseShowCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), and ticket_commandscript::TicketResponseAppend().
FormatMessageString() [2/2]
std::string GmTicket::FormatMessageString (ChatHandler & handler, const char * szClosedName, const char * szAssignedToName, const char * szUnassignedName, const char * szDeletedName) const
{
    std::stringstream ss;
    ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTGUID, _id);
    ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTNAME, _playerName.c_str());
    if (szClosedName)
        ss << handler.PGetParseString(LANG_COMMAND_TICKETCLOSED, szClosedName);
    if (szAssignedToName)
        ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTASSIGNEDTO, szAssignedToName);
    if (szUnassignedName)
        ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTUNASSIGNED, szUnassignedName);
    if (szDeletedName)
        ss << handler.PGetParseString(LANG_COMMAND_TICKETDELETED, szDeletedName);
    return ss.str();
}
References _id, _playerName, LANG_COMMAND_TICKETCLOSED, LANG_COMMAND_TICKETDELETED, LANG_COMMAND_TICKETLISTASSIGNEDTO, LANG_COMMAND_TICKETLISTGUID, LANG_COMMAND_TICKETLISTNAME, LANG_COMMAND_TICKETLISTUNASSIGNED, and ChatHandler::PGetParseString().
GetAssignedPlayer()
Player * GmTicket::GetAssignedPlayer () const inline
{ return ObjectAccessor::FindConnectedPlayer(_assignedTo); }
References _assignedTo, and ObjectAccessor::FindConnectedPlayer().
Referenced by ticket_commandscript::HandleGMTicketUnAssignCommand().
GetAssignedToGUID()
ObjectGuid GmTicket::GetAssignedToGUID () const inline
{ return _assignedTo; }
References _assignedTo.
Referenced by ticket_commandscript::HandleGMTicketUnAssignCommand().
GetAssignedToName()
std::string GmTicket::GetAssignedToName () const inline
    {
        std::string name;
        // save queries if ticket is not assigned
        if (_assignedTo)
        {
            sCharacterCache->GetCharacterNameByGuid(_assignedTo, name);
        }
        return name;
    }
References _assignedTo, and sCharacterCache.
Referenced by ticket_commandscript::HandleGMTicketCommentCommand(), and ticket_commandscript::HandleGMTicketUnAssignCommand().
GetChatLog()
std::string const & GmTicket::GetChatLog () const inline
{ return _chatLog; }
References _chatLog.
GetEscalatedStatus()
GMTicketEscalationStatus GmTicket::GetEscalatedStatus () const inline
{ return _escalatedStatus; }
References _escalatedStatus.
Referenced by ticket_commandscript::HandleGMTicketEscalateCommand().
GetId()
uint32 GmTicket::GetId () const inline
{ return _id; }
References _id.
Referenced by TicketMgr::AddTicket(), Player::DeleteFromDB(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), WorldSession::HandleGMTicketCreateOpcode(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketResponseDeleteCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), TicketMgr::LoadTickets(), and ticket_commandscript::TicketResponseAppend().
GetLastModifiedTime()
uint64 GmTicket::GetLastModifiedTime () const inline
{ return _lastModifiedTime; }
References _lastModifiedTime.
GetMessage()
std::string const & GmTicket::GetMessage () const inline
{ return _message; }
References _message.
GetPlayer()
Player * GmTicket::GetPlayer () const inline
{ return ObjectAccessor::FindConnectedPlayer(_playerGuid); }
References _playerGuid, and ObjectAccessor::FindConnectedPlayer().
Referenced by ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), and ticket_commandscript::HandleGMTicketEscalateCommand().
GetPlayerName()
std::string const & GmTicket::GetPlayerName () const inline
{ return _playerName; }
References _playerName.
GetResponse()
std::string GmTicket::GetResponse () inline
{ return _response; }
References _response.
Referenced by ticket_commandscript::HandleGMTicketResponseShowCommand().
IsAssigned()
bool GmTicket::IsAssigned () const inline
{ return _assignedTo; }
References _assignedTo.
Referenced by ticket_commandscript::HandleGMTicketUnAssignCommand(), and IsAssignedNotTo().
IsAssignedNotTo()
bool GmTicket::IsAssignedNotTo (ObjectGuid guid) const inline
{ return IsAssigned() && !IsAssignedTo(guid); }
References IsAssigned(), and IsAssignedTo().
Referenced by ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketResponseDeleteCommand(), and ticket_commandscript::TicketResponseAppend().
IsAssignedTo()
bool GmTicket::IsAssignedTo (ObjectGuid guid) const inline
{ return guid == _assignedTo; }
References _assignedTo.
Referenced by ticket_commandscript::HandleGMTicketAssignToCommand(), and IsAssignedNotTo().
IsClosed()
bool GmTicket::IsClosed () const inline
{ return  _type != TICKET_TYPE_OPEN; }
References _type, and TICKET_TYPE_OPEN.
Referenced by TicketMgr::AddTicket(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), WorldSession::HandleGMTicketCreateOpcode(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketEscalateCommand(), ticket_commandscript::HandleGMTicketGetByIdCommand(), ticket_commandscript::HandleGMTicketResponseDeleteCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), TicketMgr::LoadTickets(), and ticket_commandscript::TicketResponseAppend().
IsCompleted()
bool GmTicket::IsCompleted () const inline
{ return _completed; }
References _completed.
Referenced by ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), WorldSession::HandleGMTicketCreateOpcode(), ticket_commandscript::HandleGMTicketEscalateCommand(), and ticket_commandscript::HandleGMTicketGetByIdCommand().
IsFromPlayer()
bool GmTicket::IsFromPlayer (ObjectGuid guid) const inline
{ return guid == _playerGuid; }
References _playerGuid.
LoadFromDB()
bool GmTicket::LoadFromDB (Field * fields)
{
    //  0    1        2       3       4          5        6      7     8     9          10            11         12         13       14        15         16        17        18         19
    // id, type, playerGuid, name, message, createTime, mapId, posX, posY, posZ, lastModifiedTime, closedBy, assignedTo, comment, response, completed, escalated, viewed, haveTicket, resolvedBy
    uint8 index = 0;
    _id                 = fields[  index].Get<uint32>();
    _type               = TicketType(fields[++index].Get<uint8>());
    _playerGuid         = ObjectGuid::Create<HighGuid::Player>(fields[++index].Get<uint32>());
    _playerName         = fields[++index].Get<std::string>();
    _message            = fields[++index].Get<std::string>();
    _createTime         = fields[++index].Get<uint32>();
    _mapId              = fields[++index].Get<uint16>();
    _posX               = fields[++index].Get<float>();
    _posY               = fields[++index].Get<float>();
    _posZ               = fields[++index].Get<float>();
    _lastModifiedTime   = fields[++index].Get<uint32>();
    _closedBy           = ObjectGuid::Create<HighGuid::Player>(fields[++index].Get<int32>());
    _assignedTo         = ObjectGuid::Create<HighGuid::Player>(fields[++index].Get<uint32>());
    _comment            = fields[++index].Get<std::string>();
    _response           = fields[++index].Get<std::string>();
    _completed          = fields[++index].Get<bool>();
    _escalatedStatus    = GMTicketEscalationStatus(fields[++index].Get<uint8>());
    _viewed             = fields[++index].Get<bool>();
    _needMoreHelp       = fields[++index].Get<bool>();
    _resolvedBy         = ObjectGuid::Create<HighGuid::Player>(fields[++index].Get<int32>());
    return true;
}
References _assignedTo, _closedBy, _comment, _completed, _createTime, _escalatedStatus, _id, _lastModifiedTime, _mapId, _message, _needMoreHelp, _playerGuid, _playerName, _posX, _posY, _posZ, _resolvedBy, _response, _type, _viewed, and Field::Get().
Referenced by TicketMgr::LoadTickets().
SaveToDB()
void GmTicket::SaveToDB (CharacterDatabaseTransaction trans) const
{
    //  0    1       2         3          4          5        6     7     8     9           10           11          12        13        14        15         16        17         18          19
    // id, type, playerGuid, name, description, createTime, mapId, posX, posY, posZ, lastModifiedTime, closedBy, assignedTo, comment, response, completed, escalated, viewed, needMoreHelp, resolvedBy
    uint8 index = 0;
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_REP_GM_TICKET);
    stmt->SetData(  index, _id);
    stmt->SetData (++index, uint8(_type));
    stmt->SetData(++index, _playerGuid.GetCounter());
    stmt->SetData(++index, _playerName);
    stmt->SetData(++index, _message);
    stmt->SetData(++index, uint32(_createTime));
    stmt->SetData(++index, _mapId);
    stmt->SetData (++index, _posX);
    stmt->SetData (++index, _posY);
    stmt->SetData (++index, _posZ);
    stmt->SetData(++index, uint32(_lastModifiedTime));
    stmt->SetData (++index, int32(_closedBy.GetCounter()));
    stmt->SetData(++index, _assignedTo.GetCounter());
    stmt->SetData(++index, _comment);
    stmt->SetData(++index, _response);
    stmt->SetData  (++index, _completed);
    stmt->SetData (++index, uint8(_escalatedStatus));
    stmt->SetData  (++index, _viewed);
    stmt->SetData  (++index, _needMoreHelp);
    stmt->SetData (++index, int32(_resolvedBy.GetCounter()));
    CharacterDatabase.ExecuteOrAppend(trans, stmt);
}
References _assignedTo, _closedBy, _comment, _completed, _createTime, _escalatedStatus, _id, _lastModifiedTime, _mapId, _message, _needMoreHelp, _playerGuid, _playerName, _posX, _posY, _posZ, _resolvedBy, _response, _type, _viewed, CHAR_REP_GM_TICKET, CharacterDatabase, ObjectGuid::GetCounter(), and PreparedStatementBase::SetData().
Referenced by TicketMgr::AddTicket(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketGetByIdCommand(), ticket_commandscript::HandleGMTicketGetByNameCommand(), ticket_commandscript::HandleGMTicketResponseDeleteCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), and ticket_commandscript::TicketResponseAppend().
SendResponse()
void GmTicket::SendResponse (WorldSession * session) const
{
    WorldPacket data(SMSG_GMRESPONSE_RECEIVED);
    data << uint32(1);          // responseID
    data << uint32(_id);        // ticketID
    data << _message.c_str();
    std::size_t len = _response.size();
    char const* s = _response.c_str();
    for (int i = 0; i < 4; i++)
    {
        if (len)
        {
            std::size_t writeLen = std::min<size_t>(len, 3999);
            data.append(s, writeLen);
            len -= writeLen;
            s += writeLen;
        }
        data << uint8(0);
    }
    session->SendPacket(&data);
}
References _id, _message, _response, ByteBuffer::append(), WorldSession::SendPacket(), and SMSG_GMRESPONSE_RECEIVED.
Referenced by ticket_commandscript::HandleGMTicketCompleteCommand().
SetAssignedTo()
void GmTicket::SetAssignedTo (ObjectGuid guid, bool isAdmin) inline
    {
        _assignedTo = guid;
        if (isAdmin && _escalatedStatus == TICKET_IN_ESCALATION_QUEUE)
            _escalatedStatus = TICKET_ESCALATED_ASSIGNED;
        else if (_escalatedStatus == TICKET_UNASSIGNED)
            _escalatedStatus = TICKET_ASSIGNED;
    }
References _assignedTo, _escalatedStatus, TICKET_ASSIGNED, TICKET_ESCALATED_ASSIGNED, TICKET_IN_ESCALATION_QUEUE, and TICKET_UNASSIGNED.
Referenced by ticket_commandscript::HandleGMTicketAssignToCommand().
SetChatLog()
void GmTicket::SetChatLog (std::list< uint32 > time, std::string const & log)
{
    std::stringstream ss(log);
    std::stringstream newss;
    std::string line;
    while (std::getline(ss, line) && !time.empty())
    {
        newss << secsToTimeString(time.front()) << ": " << line << "\n";
        time.pop_front();
    }
    _chatLog = newss.str();
}
References _chatLog, and secsToTimeString().
Referenced by WorldSession::HandleGMTicketCreateOpcode().
SetClosedBy()
void GmTicket::SetClosedBy (ObjectGuid value) inline
{ _closedBy = value; _type = TICKET_TYPE_CLOSED; }
References _closedBy, _type, and TICKET_TYPE_CLOSED.
SetComment()
void GmTicket::SetComment (std::string const & comment) inline
{ _comment = comment; }
References _comment.
Referenced by ticket_commandscript::HandleGMTicketCommentCommand().
SetCompleted()
void GmTicket::SetCompleted () inline
{ _completed = true; }
References _completed.
Referenced by ticket_commandscript::HandleGMTicketCompleteCommand().
SetEscalatedStatus()
void GmTicket::SetEscalatedStatus (GMTicketEscalationStatus escalatedStatus) inline
{ _escalatedStatus = escalatedStatus; }
References _escalatedStatus.
Referenced by ticket_commandscript::HandleGMTicketEscalateCommand().
SetGmAction()
void GmTicket::SetGmAction (uint32 needResponse, bool needMoreHelp)
{
    _needResponse = (needResponse == 17);   // Requires GM response. 17 = true, 1 = false (17 is default)
    _needMoreHelp = needMoreHelp;           // Requests further GM interaction on a ticket to which a GM has already responded. Basically means "has a new ticket"
}
References _needMoreHelp, and _needResponse.
Referenced by WorldSession::HandleGMTicketCreateOpcode().
SetMessage()
void GmTicket::SetMessage (std::string const & message)
{
    _message = message;
    _lastModifiedTime = uint64(GameTime::GetGameTime().count());
}
References _lastModifiedTime, _message, and GameTime::GetGameTime().
Referenced by WorldSession::HandleGMTicketCreateOpcode().
SetPosition()
void GmTicket::SetPosition (uint32 mapId, float x, float y, float z)
{
    _mapId = mapId;
    _posX = x;
    _posY = y;
    _posZ = z;
}
References _mapId, _posX, _posY, and _posZ.
Referenced by WorldSession::HandleGMTicketCreateOpcode().
SetResolvedBy()
void GmTicket::SetResolvedBy (ObjectGuid value) inline
{ _resolvedBy = value; }
References _resolvedBy.
Referenced by ticket_commandscript::HandleGMTicketCompleteCommand().
SetUnassigned()
void GmTicket::SetUnassigned ()
{
    _assignedTo.Clear();
    switch (_escalatedStatus)
    {
        case TICKET_ASSIGNED:
            _escalatedStatus = TICKET_UNASSIGNED;
            break;
        case TICKET_ESCALATED_ASSIGNED:
            _escalatedStatus = TICKET_IN_ESCALATION_QUEUE;
            break;
        case TICKET_UNASSIGNED:
        case TICKET_IN_ESCALATION_QUEUE:
        default:
            break;
    }
}
References _assignedTo, _escalatedStatus, ObjectGuid::Clear(), TICKET_ASSIGNED, TICKET_ESCALATED_ASSIGNED, TICKET_IN_ESCALATION_QUEUE, and TICKET_UNASSIGNED.
Referenced by ticket_commandscript::HandleGMTicketUnAssignCommand().
SetViewed()
void GmTicket::SetViewed () inline
{ _viewed = true; }
References _viewed.
Referenced by ticket_commandscript::HandleGMTicketGetByIdCommand(), and ticket_commandscript::HandleGMTicketGetByNameCommand().
TeleportTo()
void GmTicket::TeleportTo (Player * player) const
{
    player->TeleportTo(_mapId, _posX, _posY, _posZ, 0.0f, 0);
}
References _mapId, _posX, _posY, _posZ, and Player::TeleportTo().
Referenced by go_commandscript::HandleGoTicketCommand().
WritePacket()
void GmTicket::WritePacket (WorldPacket & data) const
{
    data << uint32(GMTICKET_STATUS_HASTEXT);
    data << uint32(_id);
    data << _message;
    data << uint8(_needMoreHelp);
    data << GetAge(_lastModifiedTime);
    if (GmTicket* ticket = sTicketMgr->GetOldestOpenTicket())
        data << GetAge(ticket->GetLastModifiedTime());
    else
        data << float(0);
    // I am not sure how blizzlike this is, and we don't really have a way to find out
    data << GetAge(sTicketMgr->GetLastChange());
    data << uint8(std::min(_escalatedStatus, TICKET_IN_ESCALATION_QUEUE));                              // escalated data
    data << uint8(_viewed ? GMTICKET_OPENEDBYGM_STATUS_OPENED : GMTICKET_OPENEDBYGM_STATUS_NOT_OPENED); // whether or not it has been viewed
}
References _escalatedStatus, _id, _lastModifiedTime, _message, _needMoreHelp, _viewed, GetAge(), GMTICKET_OPENEDBYGM_STATUS_NOT_OPENED, GMTICKET_OPENEDBYGM_STATUS_OPENED, GMTICKET_STATUS_HASTEXT, sTicketMgr, and TICKET_IN_ESCALATION_QUEUE.
Referenced by TicketMgr::SendTicket().
Member Data Documentation
_assignedTo
ObjectGuid GmTicket::_assignedTo private
Referenced by FormatMessageString(), GetAssignedPlayer(), GetAssignedToGUID(), GetAssignedToName(), IsAssigned(), IsAssignedTo(), LoadFromDB(), SaveToDB(), SetAssignedTo(), and SetUnassigned().
_chatLog
std::string GmTicket::_chatLog private
Referenced by GetChatLog(), and SetChatLog().
_closedBy
ObjectGuid GmTicket::_closedBy private
Referenced by LoadFromDB(), SaveToDB(), and SetClosedBy().
_comment
std::string GmTicket::_comment private
Referenced by FormatMessageString(), LoadFromDB(), SaveToDB(), and SetComment().
_completed
bool GmTicket::_completed private
Referenced by IsCompleted(), LoadFromDB(), SaveToDB(), and SetCompleted().
_createTime
uint64 GmTicket::_createTime private
Referenced by FormatMessageString(), LoadFromDB(), and SaveToDB().
_escalatedStatus
GMTicketEscalationStatus GmTicket::_escalatedStatus private
Referenced by GetEscalatedStatus(), LoadFromDB(), SaveToDB(), SetAssignedTo(), SetEscalatedStatus(), SetUnassigned(), and WritePacket().
_id
uint32 GmTicket::_id private
Referenced by DeleteFromDB(), FormatMessageString(), GetId(), GmTicket(), LoadFromDB(), SaveToDB(), SendResponse(), and WritePacket().
_lastModifiedTime
uint64 GmTicket::_lastModifiedTime private
Referenced by FormatMessageString(), GetLastModifiedTime(), LoadFromDB(), SaveToDB(), SetMessage(), and WritePacket().
_mapId
uint16 GmTicket::_mapId private
Referenced by LoadFromDB(), SaveToDB(), SetPosition(), and TeleportTo().
_message
std::string GmTicket::_message private
Referenced by FormatMessageString(), GetMessage(), LoadFromDB(), SaveToDB(), SendResponse(), SetMessage(), and WritePacket().
_needMoreHelp
bool GmTicket::_needMoreHelp private
Todo:
: find out the use of this, and then store it in DB
Referenced by LoadFromDB(), SaveToDB(), SetGmAction(), and WritePacket().
_needResponse
bool GmTicket::_needResponse private
Referenced by SetGmAction().
_playerGuid
ObjectGuid GmTicket::_playerGuid private
Referenced by GetPlayer(), GmTicket(), IsFromPlayer(), LoadFromDB(), and SaveToDB().
_playerName
std::string GmTicket::_playerName private
Referenced by FormatMessageString(), GetPlayerName(), GmTicket(), LoadFromDB(), and SaveToDB().
_posX
float GmTicket::_posX private
Referenced by LoadFromDB(), SaveToDB(), SetPosition(), and TeleportTo().
_posY
float GmTicket::_posY private
Referenced by LoadFromDB(), SaveToDB(), SetPosition(), and TeleportTo().
_posZ
float GmTicket::_posZ private
Referenced by LoadFromDB(), SaveToDB(), SetPosition(), and TeleportTo().
_resolvedBy
ObjectGuid GmTicket::_resolvedBy private
Referenced by LoadFromDB(), SaveToDB(), and SetResolvedBy().
_response
std::string GmTicket::_response private
Referenced by AppendResponse(), DeleteResponse(), FormatMessageString(), GetResponse(), LoadFromDB(), SaveToDB(), and SendResponse().
_type
TicketType GmTicket::_type private
Referenced by IsClosed(), LoadFromDB(), SaveToDB(), and SetClosedBy().
_viewed
bool GmTicket::_viewed private
Referenced by LoadFromDB(), SaveToDB(), SetViewed(), and WritePacket().