AzeorthCore: OutdoorPvPNA Class Reference
OutdoorPvPNA Class Reference
#include "OutdoorPvPNA.h"
Public Member Functions
OutdoorPvPNA ()
bool SetupOutdoorPvP () override
void HandlePlayerEnterZone (Player *player, uint32 zone) override
void HandlePlayerLeaveZone (Player *player, uint32 zone) override
bool Update (uint32 diff) override
void FillInitialWorldStates (WorldPacket &data) override
void SendRemoveWorldStates (Player *player) override
void HandleKillImpl (Player *player, Unit *killed) override
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
~OutdoorPvP () override
void DeleteSpawns ()
virtual void FillInitialWorldStates (WorldPacket &)
virtual bool HandleAreaTrigger (Player *player, uint32 trigger)
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual bool HandleOpenGo (Player *player, GameObject *go)
virtual bool SetupOutdoorPvP ()
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SendUpdateWorldState (uint32 field, uint32 value)
virtual bool Update (uint32 diff)
virtual void HandleKill (Player *killer, Unit *killed)
virtual void HandleKillImpl (Player *, Unit *)
bool IsInsideObjective (Player *player) const
virtual void AwardKillBonus (Player *)
uint32 GetTypeId ()
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipid)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
void TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2=0, Player *sameMapPlr=nullptr)
Map * GetMap () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
OPvPCapturePointNA * m_obj
Additional Inherited Members
Public Types inherited from OutdoorPvP
typedef std::map< ObjectGuid::LowType, OPvPCapturePoint * > OPvPCapturePointMap
typedef std::pair< ObjectGuid::LowType, GameObject * > GoScriptPair
typedef std::pair< ObjectGuid::LowType, Creature * > CreatureScriptPair
Protected Member Functions inherited from OutdoorPvP
virtual void SendRemoveWorldStates (Player *)
void BroadcastPacket (WorldPacket &data) const
virtual void HandlePlayerEnterZone (Player *player, uint32 zone)
virtual void HandlePlayerLeaveZone (Player *player, uint32 zone)
virtual void HandlePlayerResurrects (Player *player, uint32 zone)
void AddCapturePoint (OPvPCapturePoint *cp)
OPvPCapturePoint * GetCapturePoint (ObjectGuid::LowType spawnId) const
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player const *player) const
void TeamCastSpell (TeamId team, int32 spellId, Player *sameMapPlr=nullptr)
void SetMapFromZone (uint32 zone)
Protected Attributes inherited from OutdoorPvP
OPvPCapturePointMap m_capturePoints
PlayerSet m_players [2]
uint32 m_TypeId
bool m_sendUpdate
std::map< ObjectGuid::LowType, GameObject * > m_GoScriptStore
std::map< ObjectGuid::LowType, Creature * > m_CreatureScriptStore
Map * m_map
Detailed Description
Constructor & Destructor Documentation
OutdoorPvPNA()
OutdoorPvPNA::OutdoorPvPNA ()
{
    m_TypeId = OUTDOOR_PVP_NA;
    m_obj = nullptr;
}
References m_obj, OutdoorPvP::m_TypeId, and OUTDOOR_PVP_NA.
Member Function Documentation
FillInitialWorldStates()
void OutdoorPvPNA::FillInitialWorldStates (WorldPacket & data) override virtual
Reimplemented from OutdoorPvP.
{
    m_obj->FillInitialWorldStates(data);
}
References OPvPCapturePointNA::FillInitialWorldStates(), and m_obj.
HandleKillImpl()
void OutdoorPvPNA::HandleKillImpl (Player * player, Unit * killed) override virtual
Reimplemented from OutdoorPvP.
{
    if (killed->GetTypeId() == TYPEID_PLAYER && player->GetTeamId() != killed->ToPlayer()->GetTeamId())
    {
        player->KilledMonsterCredit(NA_CREDIT_MARKER);
        player->CastSpell(player, player->GetTeamId() == TEAM_ALLIANCE ? NA_KILL_TOKEN_ALLIANCE : NA_KILL_TOKEN_HORDE, true);
    }
}
References Unit::CastSpell(), Player::GetTeamId(), Object::GetTypeId(), Player::KilledMonsterCredit(), NA_CREDIT_MARKER, NA_KILL_TOKEN_ALLIANCE, NA_KILL_TOKEN_HORDE, TEAM_ALLIANCE, Object::ToPlayer(), and TYPEID_PLAYER.
HandlePlayerEnterZone()
void OutdoorPvPNA::HandlePlayerEnterZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
{
    // add buffs
    if (player->GetTeamId() == m_obj->GetControllingFaction())
        player->CastSpell(player, NA_CAPTURE_BUFF, true);
    OutdoorPvP::HandlePlayerEnterZone(player, zone);
}
References Unit::CastSpell(), OPvPCapturePointNA::GetControllingFaction(), Player::GetTeamId(), OutdoorPvP::HandlePlayerEnterZone(), m_obj, and NA_CAPTURE_BUFF.
HandlePlayerLeaveZone()
void OutdoorPvPNA::HandlePlayerLeaveZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
{
    // remove buffs
    player->RemoveAurasDueToSpell(NA_CAPTURE_BUFF);
    OutdoorPvP::HandlePlayerLeaveZone(player, zone);
}
References OutdoorPvP::HandlePlayerLeaveZone(), NA_CAPTURE_BUFF, and Unit::RemoveAurasDueToSpell().
SendRemoveWorldStates()
void OutdoorPvPNA::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
{
    player->SendUpdateWorldState(NA_UI_HORDE_GUARDS_SHOW, 0);
    player->SendUpdateWorldState(NA_UI_ALLIANCE_GUARDS_SHOW, 0);
    player->SendUpdateWorldState(NA_UI_GUARDS_MAX, 0);
    player->SendUpdateWorldState(NA_UI_GUARDS_LEFT, 0);
    player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_DISPLAY, 0);
    player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_POS, 0);
    player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_N, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_NEU_H, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_NEU_A, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_H, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_A, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_NEU_H, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_NEU_A, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_H, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_A, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_WEST_NEU_H, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_WEST_NEU_A, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_WEST_H, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_WEST_A, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_EAST_NEU_H, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_EAST_NEU_A, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_EAST_H, 0);
    player->SendUpdateWorldState(NA_MAP_WYVERN_EAST_A, 0);
    player->SendUpdateWorldState(NA_MAP_HALAA_NEUTRAL, 0);
    player->SendUpdateWorldState(NA_MAP_HALAA_NEU_A, 0);
    player->SendUpdateWorldState(NA_MAP_HALAA_NEU_H, 0);
    player->SendUpdateWorldState(NA_MAP_HALAA_HORDE, 0);
    player->SendUpdateWorldState(NA_MAP_HALAA_ALLIANCE, 0);
}
References NA_MAP_HALAA_ALLIANCE, NA_MAP_HALAA_HORDE, NA_MAP_HALAA_NEU_A, NA_MAP_HALAA_NEU_H, NA_MAP_HALAA_NEUTRAL, NA_MAP_WYVERN_EAST_A, NA_MAP_WYVERN_EAST_H, NA_MAP_WYVERN_EAST_NEU_A, NA_MAP_WYVERN_EAST_NEU_H, NA_MAP_WYVERN_NORTH_A, NA_MAP_WYVERN_NORTH_H, NA_MAP_WYVERN_NORTH_NEU_A, NA_MAP_WYVERN_NORTH_NEU_H, NA_MAP_WYVERN_SOUTH_A, NA_MAP_WYVERN_SOUTH_H, NA_MAP_WYVERN_SOUTH_NEU_A, NA_MAP_WYVERN_SOUTH_NEU_H, NA_MAP_WYVERN_WEST_A, NA_MAP_WYVERN_WEST_H, NA_MAP_WYVERN_WEST_NEU_A, NA_MAP_WYVERN_WEST_NEU_H, NA_UI_ALLIANCE_GUARDS_SHOW, NA_UI_GUARDS_LEFT, NA_UI_GUARDS_MAX, NA_UI_HORDE_GUARDS_SHOW, NA_UI_TOWER_SLIDER_DISPLAY, NA_UI_TOWER_SLIDER_N, NA_UI_TOWER_SLIDER_POS, and Player::SendUpdateWorldState().
SetupOutdoorPvP()
bool OutdoorPvPNA::SetupOutdoorPvP () override virtual
Reimplemented from OutdoorPvP.
{
    //    m_TypeId = OUTDOOR_PVP_NA; _MUST_ be set in ctor, because of spawns cleanup
    // add the zones affected by the pvp buff
    RegisterZone(NA_BUFF_ZONE);
    SetMapFromZone(NA_BUFF_ZONE);
    // halaa
    m_obj = new OPvPCapturePointNA(this);
    if (!m_obj)
        return false;
    AddCapturePoint(m_obj);
    return true;
}
References OutdoorPvP::AddCapturePoint(), m_obj, NA_BUFF_ZONE, OutdoorPvP::RegisterZone(), and OutdoorPvP::SetMapFromZone().
Update()
bool OutdoorPvPNA::Update (uint32 diff) override virtual
Reimplemented from OutdoorPvP.
{
    return m_obj->Update(diff);
}
References m_obj, and OPvPCapturePointNA::Update().
Member Data Documentation
m_obj
OPvPCapturePointNA* OutdoorPvPNA::m_obj private
Referenced by FillInitialWorldStates(), HandlePlayerEnterZone(), OutdoorPvPNA(), SetupOutdoorPvP(), and Update().