AzerothCore: DynTreeImpl Struct Reference
DynTreeImpl Struct Reference
Public Types
typedef GameObjectModel Model
typedef ParentTree base
Public Types inherited from RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >
enum { CELL_NUMBER = 64 }
typedef G3D::Table< const T *, NodeArray< Node > > MemberTable
Public Member Functions
DynTreeImpl ()
void insert (const Model &mdl)
void remove (const Model &mdl)
void balance ()
void update (uint32 difftime)
Public Member Functions inherited from RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >
RegularGrid2D ()
~RegularGrid2D ()
void insert (const T &value)
void remove (const T &value)
void balance ()
bool contains (const T &value) const
int size () const
Node & getGridFor (float fx, float fy)
Node & getGrid (int x, int y)
template<typename RayCallback >
void intersectRay (const G3D::Ray &ray, RayCallback &intersectCallback, float max_dist, bool stopAtFirstHit)
template<typename RayCallback >
void intersectRay (const G3D::Ray &ray, RayCallback &intersectCallback, float &max_dist, const G3D::Vector3 &end, bool stopAtFirstHit)
template<typename IsectCallback >
void intersectPoint (const G3D::Vector3 &point, IsectCallback &intersectCallback)
template<typename RayCallback >
void intersectZAllignedRay (const G3D::Ray &ray, RayCallback &intersectCallback, float &max_dist)
Public Attributes
TimeTrackerSmall rebalance_timer
int unbalanced_times
Public Attributes inherited from RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >
MemberTable memberTable
Node * nodes [CELL_NUMBER][CELL_NUMBER]
Detailed Description
Member Typedef Documentation
base
typedef ParentTree DynTreeImpl::base
Model
typedef GameObjectModel DynTreeImpl::Model
Constructor & Destructor Documentation
DynTreeImpl()
DynTreeImpl::DynTreeImpl () inline
                  :
        rebalance_timer(CHECK_TREE_PERIOD),
        unbalanced_times(0)
    {
    }
Member Function Documentation
balance()
void DynTreeImpl::balance () inline
    {
        base::balance();
        unbalanced_times = 0;
    }
References RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::balance(), and unbalanced_times.
Referenced by DynamicMapTree::balance(), and update().
insert()
void DynTreeImpl::insert (const Model & mdl) inline
    {
        base::insert(mdl);
        ++unbalanced_times;
    }
References RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::insert(), and unbalanced_times.
Referenced by DynamicMapTree::insert().
remove()
void DynTreeImpl::remove (const Model & mdl) inline
    {
        base::remove(mdl);
        ++unbalanced_times;
    }
References RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::remove(), and unbalanced_times.
Referenced by DynamicMapTree::remove().
update()
void DynTreeImpl::update (uint32 difftime) inline
    {
        if (!size())
        {
            return;
        }
        rebalance_timer.Update(difftime);
        if (rebalance_timer.Passed())
        {
            rebalance_timer.Reset(CHECK_TREE_PERIOD);
            if (unbalanced_times > 0)
            {
                balance();
            }
        }
    }
References balance(), anonymous_namespace{DynamicTree.cpp}::CHECK_TREE_PERIOD, TimeTrackerSmall::Passed(), rebalance_timer, TimeTrackerSmall::Reset(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::size(), unbalanced_times, and TimeTrackerSmall::Update().
Referenced by DynamicMapTree::update().
Member Data Documentation
rebalance_timer
TimeTrackerSmall DynTreeImpl::rebalance_timer
Referenced by update().
unbalanced_times
int DynTreeImpl::unbalanced_times
Referenced by balance(), insert(), remove(), and update().