AzerothCore: VileSpiritActivateEvent Class Reference
VileSpiritActivateEvent Class Reference
Public Member Functions
VileSpiritActivateEvent (Creature *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _owner
Detailed Description
Constructor & Destructor Documentation
VileSpiritActivateEvent()
VileSpiritActivateEvent::VileSpiritActivateEvent (Creature * owner) inline explicit
: _owner(owner) {}
Member Function Documentation
Execute()
bool VileSpiritActivateEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        _owner->SetReactState(REACT_AGGRESSIVE);
        _owner->CastSpell(_owner, SPELL_VILE_SPIRIT_MOVE_SEARCH, true);
        _owner->CastSpell((Unit*)nullptr, SPELL_VILE_SPIRIT_DAMAGE_SEARCH, true);
        return true;
    }
References _owner, Unit::CastSpell(), REACT_AGGRESSIVE, Creature::SetReactState(), SPELL_VILE_SPIRIT_DAMAGE_SEARCH, and SPELL_VILE_SPIRIT_MOVE_SEARCH.
Referenced by spell_the_lich_king_trigger_vile_spirit::ActivateSpirit().
Member Data Documentation
_owner
Creature* VileSpiritActivateEvent::_owner private
Referenced by Execute().