AzerothCore: instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript Struct Reference
instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript Struct Reference
Public Member Functions
instance_icecrown_citadel_InstanceMapScript (InstanceMap *map)
void FillInitialWorldStates (WorldPacket &data) override
void OnPlayerAreaUpdate (Player *player, uint32, uint32 newArea) override
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data) override
uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry) override
void OnUnitDeath (Unit *unit) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 type) const override
void HandleDropAttempt (bool drop=true)
void RemoveBackPack ()
bool SetBossState (uint32 type, EncounterState state) override
void SpawnGunship ()
void SetData (uint32 type, uint32 data) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
bool CheckRequiredBosses (uint32 bossId, Player const *player) const override
bool CheckPlagueworks (uint32 bossId) const
bool CheckCrimsonHalls (uint32 bossId) const
bool CheckFrostwingHalls (uint32 bossId) const
bool CheckLowerSpire (uint32 bossId) const
void CheckLichKingAvailability ()
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
void Update (uint32 diff) override
void ProcessEvent (WorldObject *source, uint32 eventId) override
void SetPositionTraps (GameObject *go)
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
bool IsBuffAvailable
uint32 WeeklyQuestId10
ObjectGuid WeeklyQuestNpcGUID [WeeklyNPCs]
ObjectGuid PutricideEnteranceDoorGUID
uint32 PutricideEventProgress
ObjectGuid GasReleaseValveGUID
ObjectGuid OozeReleaseValveGUID
bool LichKingHeroicAvailable
uint32 LichKingRandomWhisperTimer
uint32 DarkwhisperElevatorTimer
ObjectGuid ScourgeTransporterFirstGUID
EventMap Events
ObjectGuid LadyDeathwhisperGUID
ObjectGuid LadyDeathwisperElevatorGUID
ObjectGuid GunshipGUID
ObjectGuid EnemyGunshipGUID
ObjectGuid GunshipArmoryGUID
ObjectGuid DeathbringerSaurfangGUID
ObjectGuid DeathbringerSaurfangDoorGUID
ObjectGuid DeathbringerSaurfangEventGUID
ObjectGuid DeathbringersCacheGUID
ObjectGuid SaurfangTeleportGUID
ObjectGuid PlagueSigilGUID
ObjectGuid BloodwingSigilGUID
ObjectGuid FrostwingSigilGUID
ObjectGuid PutricidePipeGUIDs [2]
ObjectGuid PutricideGateGUIDs [2]
ObjectGuid PutricideCollisionGUID
ObjectGuid FestergutGUID
ObjectGuid RotfaceGUID
ObjectGuid ProfessorPutricideGUID
ObjectGuid PutricideTableGUID
ObjectGuid BloodCouncilGUIDs [3]
ObjectGuid BloodCouncilControllerGUID
ObjectGuid BloodQueenLanaThelGUID
ObjectGuid CrokScourgebaneGUID
ObjectGuid CrokCaptainGUIDs [4]
ObjectGuid SisterSvalnaGUID
ObjectGuid ValithriaDreamwalkerGUID
ObjectGuid ValithriaLichKingGUID
ObjectGuid ValithriaTriggerGUID
ObjectGuid PutricadeTrapGUID
ObjectGuid SindragosaGauntletGUID
ObjectGuid SindragosaGUID
ObjectGuid SpinestalkerGUID
ObjectGuid RimefangGUID
ObjectGuid TheLichKingTeleportGUID
ObjectGuid TheLichKingGUID
ObjectGuid TheLichKingLhGUID
ObjectGuid HighlordTirionFordringGUID
ObjectGuid TerenasMenethilGUID
ObjectGuid ArthasPlatformGUID
ObjectGuid ArthasPrecipiceGUID
ObjectGuid FrozenThroneEdgeGUID
ObjectGuid FrozenThroneWindGUID
ObjectGuid FrozenThroneWarningGUID
ObjectGuid FrozenBolvarGUID
ObjectGuid PillarsChainedGUID
ObjectGuid PillarsUnchainedGUID
TeamId TeamIdInInstance
uint32 ColdflameJetsState
std::set< ObjectGuid::LowType > FrostwyrmGUIDs
std::set< ObjectGuid::LowType > SpinestalkerTrash
std::set< ObjectGuid::LowType > RimefangTrash
uint32 BloodQuickeningState
uint32 HeroicAttempts
uint16 BloodQuickeningMinutes
uint32 BloodPrinceTrashCount
bool IsBonedEligible
bool IsOozeDanceEligible
bool IsNauseaEligible
bool IsOrbWhispererEligible
bool IsSindragosaIntroDone
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_icecrown_citadel_InstanceMapScript()
instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::instance_icecrown_citadel_InstanceMapScript (InstanceMap * map) inline
                                                                      : InstanceScript(map)
        {
            // pussywizard:
            IsBuffAvailable = true;
            WeeklyQuestId10 = 0;
            PutricideEventProgress = 0;
            LichKingHeroicAvailable = true;
            LichKingRandomWhisperTimer = 120 * IN_MILLISECONDS;
            DarkwhisperElevatorTimer = 3000;
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTERS);
            SetPersistentDataCount(MAX_DATA_INDEXES);
            LoadBossBoundaries(boundaries);
            LoadObjectData(creatureData, nullptr);
            LoadDoorData(doorData);
            TeamIdInInstance = TEAM_NEUTRAL;
            HeroicAttempts = MaxHeroicAttempts;
            IsBonedEligible = true;
            IsOozeDanceEligible = true;
            IsNauseaEligible = true;
            IsOrbWhispererEligible = true;
            ColdflameJetsState = NOT_STARTED;
            BloodQuickeningState = NOT_STARTED;
            BloodQuickeningMinutes = 0;
            BloodPrinceTrashCount = 0;
            IsSindragosaIntroDone = false;
        }
References BloodPrinceTrashCount, BloodQuickeningMinutes, BloodQuickeningState, boundaries, ColdflameJetsState, creatureData, DarkwhisperElevatorTimer, DataHeader, doorData, HeroicAttempts, IN_MILLISECONDS, IsBonedEligible, IsBuffAvailable, IsNauseaEligible, IsOozeDanceEligible, IsOrbWhispererEligible, IsSindragosaIntroDone, LichKingHeroicAvailable, LichKingRandomWhisperTimer, InstanceScript::LoadBossBoundaries(), InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), MAX_DATA_INDEXES, MAX_ENCOUNTERS, MaxHeroicAttempts, NOT_STARTED, PutricideEventProgress, InstanceScript::SetBossNumber(), InstanceScript::SetHeaders(), InstanceScript::SetPersistentDataCount(), TEAM_NEUTRAL, TeamIdInInstance, and WeeklyQuestId10.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case CRITERIA_BONED_10N:
                case CRITERIA_BONED_25N:
                case CRITERIA_BONED_10H:
                case CRITERIA_BONED_25H:
                    return IsBonedEligible;
                case CRITERIA_DANCES_WITH_OOZES_10N:
                case CRITERIA_DANCES_WITH_OOZES_25N:
                case CRITERIA_DANCES_WITH_OOZES_10H:
                case CRITERIA_DANCES_WITH_OOZES_25H:
                    return IsOozeDanceEligible;
                case CRITERIA_NAUSEA_10N:
                case CRITERIA_NAUSEA_25N:
                case CRITERIA_NAUSEA_10H:
                case CRITERIA_NAUSEA_25H:
                    return IsNauseaEligible;
                case CRITERIA_ORB_WHISPERER_10N:
                case CRITERIA_ORB_WHISPERER_25N:
                case CRITERIA_ORB_WHISPERER_10H:
                case CRITERIA_ORB_WHISPERER_25H:
                    return IsOrbWhispererEligible;
                // Only one criteria for both modes, need to do it like this
                case CRITERIA_KILL_LANA_THEL_10M:
                    return instance->ToInstanceMap()->GetMaxPlayers() == 10;
                case CRITERIA_KILL_LANA_THEL_25M:
                    return instance->ToInstanceMap()->GetMaxPlayers() == 25;
                default:
                    break;
            }
            return false;
        }
References CRITERIA_BONED_10H, CRITERIA_BONED_10N, CRITERIA_BONED_25H, CRITERIA_BONED_25N, CRITERIA_DANCES_WITH_OOZES_10H, CRITERIA_DANCES_WITH_OOZES_10N, CRITERIA_DANCES_WITH_OOZES_25H, CRITERIA_DANCES_WITH_OOZES_25N, CRITERIA_KILL_LANA_THEL_10M, CRITERIA_KILL_LANA_THEL_25M, CRITERIA_NAUSEA_10H, CRITERIA_NAUSEA_10N, CRITERIA_NAUSEA_25H, CRITERIA_NAUSEA_25N, CRITERIA_ORB_WHISPERER_10H, CRITERIA_ORB_WHISPERER_10N, CRITERIA_ORB_WHISPERER_25H, and CRITERIA_ORB_WHISPERER_25N.
CheckCrimsonHalls()
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckCrimsonHalls (uint32 bossId) const inline
        {
            switch (bossId)
            {
                case DATA_THE_LICH_KING:
                    if (GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) != DONE)
                    {
                        return false;
                    }
                    [[fallthrough]];
                case DATA_BLOOD_QUEEN_LANA_THEL:
                    if (GetBossState(DATA_BLOOD_PRINCE_COUNCIL) != DONE)
                        return false;
                    break;
                default:
                    break;
            }
            return true;
        }
References DATA_BLOOD_PRINCE_COUNCIL, DATA_BLOOD_QUEEN_LANA_THEL, DATA_THE_LICH_KING, and DONE.
CheckFrostwingHalls()
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckFrostwingHalls (uint32 bossId) const inline
        {
            switch (bossId)
            {
                case DATA_THE_LICH_KING:
                    if (GetBossState(DATA_SINDRAGOSA) != DONE)
                    {
                        return false;
                    }
                    [[fallthrough]];
                case DATA_SINDRAGOSA:
                    if (GetBossState(DATA_VALITHRIA_DREAMWALKER) != DONE)
                    {
                        return false;
                    }
                    if (GetBossState(DATA_SINDRAGOSA_GAUNTLET) != DONE)
                    {
                        return false;
                    }
                    break;
                default:
                    break;
            }
            return true;
        }
References DATA_SINDRAGOSA, DATA_SINDRAGOSA_GAUNTLET, DATA_THE_LICH_KING, DATA_VALITHRIA_DREAMWALKER, and DONE.
CheckLichKingAvailability()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckLichKingAvailability () inline
        {
            if (GetBossState(DATA_PROFESSOR_PUTRICIDE) == DONE && GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) == DONE && GetBossState(DATA_SINDRAGOSA) == DONE)
            {
                if (GameObject* teleporter = instance->GetGameObject(TheLichKingTeleportGUID))
                {
                    teleporter->SetGoState(GO_STATE_ACTIVE);
                    std::list<Creature*> stalkers;
                    GetCreatureListWithEntryInGrid(stalkers, teleporter, NPC_INVISIBLE_STALKER, 100.0f);
                    if (stalkers.empty())
                        return;
                    stalkers.sort(Acore::ObjectDistanceOrderPred(teleporter));
                    stalkers.front()->CastSpell((Unit*)nullptr, SPELL_ARTHAS_TELEPORTER_CEREMONY, false);
                    stalkers.pop_front();
                    for (std::list<Creature*>::iterator itr = stalkers.begin(); itr != stalkers.end(); ++itr)
                        (*itr)->AI()->Reset();
                }
            }
        }
References DATA_BLOOD_QUEEN_LANA_THEL, DATA_PROFESSOR_PUTRICIDE, DATA_SINDRAGOSA, DONE, GetCreatureListWithEntryInGrid(), GO_STATE_ACTIVE, NPC_INVISIBLE_STALKER, and SPELL_ARTHAS_TELEPORTER_CEREMONY.
Referenced by SetBossState().
CheckLowerSpire()
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckLowerSpire (uint32 bossId) const inline
        {
            switch (bossId)
            {
                case DATA_THE_LICH_KING:
                case DATA_SINDRAGOSA:
                case DATA_BLOOD_QUEEN_LANA_THEL:
                case DATA_PROFESSOR_PUTRICIDE:
                case DATA_VALITHRIA_DREAMWALKER:
                case DATA_BLOOD_PRINCE_COUNCIL:
                case DATA_ROTFACE:
                case DATA_FESTERGUT:
                    if (GetBossState(DATA_DEATHBRINGER_SAURFANG) != DONE)
                    {
                        return false;
                    }
                    [[fallthrough]];
                case DATA_DEATHBRINGER_SAURFANG:
                    if (GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) != DONE)
                    {
                        return false;
                    }
                    [[fallthrough]];
                case DATA_ICECROWN_GUNSHIP_BATTLE:
                    if (GetBossState(DATA_LADY_DEATHWHISPER) != DONE)
                    {
                        return false;
                    }
                    [[fallthrough]];
                case DATA_LADY_DEATHWHISPER:
                    if (GetBossState(DATA_LORD_MARROWGAR) != DONE)
                    {
                        return false;
                    }
                    [[fallthrough]];
                case DATA_LORD_MARROWGAR:
                default:
                    break;
            }
            return true;
        }
References DATA_BLOOD_PRINCE_COUNCIL, DATA_BLOOD_QUEEN_LANA_THEL, DATA_DEATHBRINGER_SAURFANG, DATA_FESTERGUT, DATA_ICECROWN_GUNSHIP_BATTLE, DATA_LADY_DEATHWHISPER, DATA_LORD_MARROWGAR, DATA_PROFESSOR_PUTRICIDE, DATA_ROTFACE, DATA_SINDRAGOSA, DATA_THE_LICH_KING, DATA_VALITHRIA_DREAMWALKER, and DONE.
CheckPlagueworks()
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckPlagueworks (uint32 bossId) const inline
        {
            switch (bossId)
            {
                case DATA_THE_LICH_KING:
                    if (GetBossState(DATA_PROFESSOR_PUTRICIDE) != DONE)
                    {
                        return false;
                    }
                    [[fallthrough]];
                case DATA_PROFESSOR_PUTRICIDE:
                    if (GetBossState(DATA_FESTERGUT) != DONE || GetBossState(DATA_ROTFACE) != DONE)
                        return false;
                    break;
                default:
                    break;
            }
            return true;
        }
References DATA_FESTERGUT, DATA_PROFESSOR_PUTRICIDE, DATA_ROTFACE, DATA_THE_LICH_KING, and DONE.
CheckRequiredBosses()
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckRequiredBosses (uint32 bossId, Player const * player) const inline override virtual
Reimplemented from InstanceScript.
        {
            if (player && player->GetSession() && player->GetSession()->GetSecurity() >= SEC_MODERATOR)
            {
                return true;
            }
            switch (bossId)
            {
                case DATA_THE_LICH_KING:
                    if (!CheckPlagueworks(bossId))
                        return false;
                    if (!CheckCrimsonHalls(bossId))
                        return false;
                    if (!CheckFrostwingHalls(bossId))
                        return false;
                    break;
                case DATA_SINDRAGOSA:
                case DATA_VALITHRIA_DREAMWALKER:
                    if (!CheckFrostwingHalls(bossId))
                        return false;
                    break;
                case DATA_BLOOD_QUEEN_LANA_THEL:
                case DATA_BLOOD_PRINCE_COUNCIL:
                    if (!CheckCrimsonHalls(bossId))
                        return false;
                    break;
                case DATA_FESTERGUT:
                case DATA_ROTFACE:
                case DATA_PROFESSOR_PUTRICIDE:
                    if (!CheckPlagueworks(bossId))
                        return false;
                    break;
                default:
                    break;
            }
            if (!CheckLowerSpire(bossId))
                return false;
            return true;
        }
References DATA_BLOOD_PRINCE_COUNCIL, DATA_BLOOD_QUEEN_LANA_THEL, DATA_FESTERGUT, DATA_PROFESSOR_PUTRICIDE, DATA_ROTFACE, DATA_SINDRAGOSA, DATA_THE_LICH_KING, DATA_VALITHRIA_DREAMWALKER, WorldSession::GetSecurity(), Player::GetSession(), and SEC_MODERATOR.
FillInitialWorldStates()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::FillInitialWorldStates (WorldPacket & data) inline override virtual
Reimplemented from InstanceScript.
        {
            if (instance->IsHeroic())
            {
                data << uint32(WORLDSTATE_SHOW_TIMER) << uint32(BloodQuickeningState == IN_PROGRESS);
                data << uint32(WORLDSTATE_EXECUTION_TIME) << uint32(BloodQuickeningMinutes);
                data << uint32(WORLDSTATE_SHOW_ATTEMPTS) << uint32(1);
                data << uint32(WORLDSTATE_ATTEMPTS_REMAINING) << uint32(HeroicAttempts);
                data << uint32(WORLDSTATE_ATTEMPTS_MAX) << uint32(MaxHeroicAttempts);
            }
        }
References BloodQuickeningMinutes, BloodQuickeningState, HeroicAttempts, IN_PROGRESS, InstanceScript::instance, Map::IsHeroic(), MaxHeroicAttempts, WORLDSTATE_ATTEMPTS_MAX, WORLDSTATE_ATTEMPTS_REMAINING, WORLDSTATE_EXECUTION_TIME, WORLDSTATE_SHOW_ATTEMPTS, and WORLDSTATE_SHOW_TIMER.
GetCreatureEntry()
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetCreatureEntry (ObjectGuid::LowType , CreatureData const * data) inline override virtual
Reimplemented from ZoneScript.
        {
            if (TeamIdInInstance == TEAM_NEUTRAL)
            {
                Map::PlayerList const& players = instance->GetPlayers();
                if (!players.IsEmpty())
                    if (Player* player = players.begin()->GetSource())
                        TeamIdInInstance = player->GetTeamId();
            }
            uint32 entry = data->id1;
            switch (entry)
            {
                case NPC_HORDE_GUNSHIP_CANNON:
                case NPC_ORGRIMS_HAMMER_CREW:
                case NPC_SKY_REAVER_KORM_BLACKSCAR:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        return 0;
                    break;
                case NPC_ALLIANCE_GUNSHIP_CANNON:
                case NPC_SKYBREAKER_DECKHAND:
                case NPC_HIGH_CAPTAIN_JUSTIN_BARTLETT:
                    if (TeamIdInInstance == TEAM_HORDE)
                        return 0;
                    break;
                case NPC_ZAFOD_BOOMBOX:
                    if (GameObjectTemplate const* go = sObjectMgr->GetGameObjectTemplate(GO_THE_SKYBREAKER_A))
                        if ((TeamIdInInstance == TEAM_ALLIANCE && data->mapid == go->moTransport.mapID) ||
                                (TeamIdInInstance == TEAM_HORDE && data->mapid != go->moTransport.mapID))
                            return entry;
                    return 0;
                case NPC_IGB_MURADIN_BRONZEBEARD:
                    if ((TeamIdInInstance == TEAM_ALLIANCE && data->posX > 10.0f) ||
                            (TeamIdInInstance == TEAM_HORDE && data->posX < 10.0f))
                        return entry;
                    return 0;
                case NPC_SPIRE_FROSTWYRM:
                    if ((TeamIdInInstance == TEAM_ALLIANCE && data->posY < 2200.0f) || (TeamIdInInstance == TEAM_HORDE && data->posY > 2200.0f))
                        return 0;
                    break;
            }
            return entry;
        }
References MapRefMgr::begin(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), GO_THE_SKYBREAKER_A, CreatureData::id1, InstanceScript::instance, LinkedListHead::IsEmpty(), CreatureData::mapid, NPC_ALLIANCE_GUNSHIP_CANNON, NPC_HIGH_CAPTAIN_JUSTIN_BARTLETT, NPC_HORDE_GUNSHIP_CANNON, NPC_IGB_MURADIN_BRONZEBEARD, NPC_ORGRIMS_HAMMER_CREW, NPC_SKY_REAVER_KORM_BLACKSCAR, NPC_SKYBREAKER_DECKHAND, NPC_SPIRE_FROSTWYRM, NPC_ZAFOD_BOOMBOX, CreatureData::posX, CreatureData::posY, sObjectMgr, TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, and TeamIdInInstance.
GetData()
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_BUFF_AVAILABLE:
                    return (IsBuffAvailable ? 1 : 0);
                case DATA_WEEKLY_QUEST_ID:
                    return WeeklyQuestId10;
                case DATA_PUTRICIDE_TRAP_STATE:
                    if (!(PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE) || !(PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE))
                        return TO_BE_DECIDED;
                    if (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_TRAP_INPROGRESS)
                        return IN_PROGRESS;
                    if (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_TRAP_FINISHED)
                        return DONE;
                    return NOT_STARTED;
                case DATA_HAS_LIMITED_ATTEMPTS:
                    return (instance->IsHeroic() ? 1 : 0);
                case DATA_LK_HC_AVAILABLE:
                    return (LichKingHeroicAvailable ? 1 : 0);
                case DATA_SINDRAGOSA_FROSTWYRMS:
                    return FrostwyrmGUIDs.size();
                case DATA_SPINESTALKER:
                    return SpinestalkerTrash.size();
                case DATA_RIMEFANG:
                    return RimefangTrash.size();
                case DATA_COLDFLAME_JETS:
                    return ColdflameJetsState;
                case DATA_TEAMID_IN_INSTANCE:
                    return TeamIdInInstance;
                case DATA_BLOOD_QUICKENING_STATE:
                    return BloodQuickeningState;
                case DATA_HEROIC_ATTEMPTS:
                    return HeroicAttempts;
                case DATA_SINDRAGOSA_INTRO:
                    return (IsSindragosaIntroDone ? 1 : 0);
                default:
                    break;
            }
            return 0;
        }
References BloodQuickeningState, ColdflameJetsState, DATA_BLOOD_QUICKENING_STATE, DATA_BUFF_AVAILABLE, DATA_COLDFLAME_JETS, DATA_HAS_LIMITED_ATTEMPTS, DATA_HEROIC_ATTEMPTS, DATA_LK_HC_AVAILABLE, DATA_PUTRICIDE_TRAP_STATE, DATA_RIMEFANG, DATA_SINDRAGOSA_FROSTWYRMS, DATA_SINDRAGOSA_INTRO, DATA_SPINESTALKER, DATA_TEAMID_IN_INSTANCE, DATA_WEEKLY_QUEST_ID, DONE, FrostwyrmGUIDs, HeroicAttempts, IN_PROGRESS, InstanceScript::instance, IsBuffAvailable, Map::IsHeroic(), IsSindragosaIntroDone, LichKingHeroicAvailable, NOT_STARTED, PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE, PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE, PUTRICIDE_EVENT_FLAG_TRAP_FINISHED, PUTRICIDE_EVENT_FLAG_TRAP_INPROGRESS, PutricideEventProgress, RimefangTrash, SpinestalkerTrash, TeamIdInInstance, TO_BE_DECIDED, and WeeklyQuestId10.
Referenced by HandleDropAttempt(), OnCreatureCreate(), OnUnitDeath(), and SetBossState().
GetGameObjectEntry()
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetGameObjectEntry (ObjectGuid::LowType , uint32 entry) inline override virtual
Reimplemented from ZoneScript.
        {
            if (TeamIdInInstance == TEAM_NEUTRAL)
            {
                Map::PlayerList const& players = instance->GetPlayers();
                if (!players.IsEmpty())
                    if (Player* player = players.begin()->GetSource())
                        TeamIdInInstance = player->GetTeamId();
            }
            switch (entry)
            {
                case GO_GUNSHIP_ARMORY_H_10N:
                case GO_GUNSHIP_ARMORY_H_25N:
                case GO_GUNSHIP_ARMORY_H_10H:
                case GO_GUNSHIP_ARMORY_H_25H:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        return 0;
                    break;
                case GO_GUNSHIP_ARMORY_A_10N:
                case GO_GUNSHIP_ARMORY_A_25N:
                case GO_GUNSHIP_ARMORY_A_10H:
                case GO_GUNSHIP_ARMORY_A_25H:
                    if (TeamIdInInstance == TEAM_HORDE)
                        return 0;
                    break;
            }
            return entry;
        }
References MapRefMgr::begin(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), GO_GUNSHIP_ARMORY_A_10H, GO_GUNSHIP_ARMORY_A_10N, GO_GUNSHIP_ARMORY_A_25H, GO_GUNSHIP_ARMORY_A_25N, GO_GUNSHIP_ARMORY_H_10H, GO_GUNSHIP_ARMORY_H_10N, GO_GUNSHIP_ARMORY_H_25H, GO_GUNSHIP_ARMORY_H_25N, InstanceScript::instance, LinkedListHead::IsEmpty(), TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, and TeamIdInInstance.
GetGuidData()
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case DATA_LADY_DEATHWHISPER:
                    return LadyDeathwhisperGUID;
                case DATA_ICECROWN_GUNSHIP_BATTLE:
                    return GunshipGUID;
                case DATA_ENEMY_GUNSHIP:
                    return EnemyGunshipGUID;
                case DATA_DEATHBRINGER_SAURFANG:
                    return DeathbringerSaurfangGUID;
                case DATA_SAURFANG_EVENT_NPC:
                    return DeathbringerSaurfangEventGUID;
                case GO_SAURFANG_S_DOOR:
                    return DeathbringerSaurfangDoorGUID;
                case GO_SCOURGE_TRANSPORTER_SAURFANG:
                    return SaurfangTeleportGUID;
                case DATA_FESTERGUT:
                    return FestergutGUID;
                case DATA_ROTFACE:
                    return RotfaceGUID;
                case DATA_PROFESSOR_PUTRICIDE:
                    return ProfessorPutricideGUID;
                case DATA_PUTRICIDE_TABLE:
                    return PutricideTableGUID;
                case DATA_PRINCE_KELESETH_GUID:
                    return BloodCouncilGUIDs[0];
                case DATA_PRINCE_TALDARAM_GUID:
                    return BloodCouncilGUIDs[1];
                case DATA_PRINCE_VALANAR_GUID:
                    return BloodCouncilGUIDs[2];
                case DATA_BLOOD_PRINCES_CONTROL:
                    return BloodCouncilControllerGUID;
                case DATA_BLOOD_QUEEN_LANA_THEL:
                    return BloodQueenLanaThelGUID;
                case DATA_CROK_SCOURGEBANE:
                    return CrokScourgebaneGUID;
                case DATA_CAPTAIN_ARNATH:
                case DATA_CAPTAIN_BRANDON:
                case DATA_CAPTAIN_GRONDEL:
                case DATA_CAPTAIN_RUPERT:
                    return CrokCaptainGUIDs[type - DATA_CAPTAIN_ARNATH];
                case DATA_SISTER_SVALNA:
                    return SisterSvalnaGUID;
                case DATA_VALITHRIA_DREAMWALKER:
                    return ValithriaDreamwalkerGUID;
                case DATA_VALITHRIA_LICH_KING:
                    return ValithriaLichKingGUID;
                case DATA_VALITHRIA_TRIGGER:
                    return ValithriaTriggerGUID;
                case NPC_SINDRAGOSA_GAUNTLET:
                    return SindragosaGauntletGUID;
                case NPC_PUTRICADES_TRAP:
                    return PutricadeTrapGUID;
                case DATA_SINDRAGOSA:
                    return SindragosaGUID;
                case DATA_SPINESTALKER:
                    return SpinestalkerGUID;
                case DATA_RIMEFANG:
                    return RimefangGUID;
                case DATA_THE_LICH_KING:
                    return TheLichKingGUID;
                case DATA_HIGHLORD_TIRION_FORDRING:
                    return HighlordTirionFordringGUID;
                case DATA_ARTHAS_PLATFORM:
                    return ArthasPlatformGUID;
                case DATA_TERENAS_MENETHIL:
                    return TerenasMenethilGUID;
                default:
                    break;
            }
            return ObjectGuid::Empty;
        }
References ArthasPlatformGUID, BloodCouncilControllerGUID, BloodCouncilGUIDs, BloodQueenLanaThelGUID, CrokCaptainGUIDs, CrokScourgebaneGUID, DATA_ARTHAS_PLATFORM, DATA_BLOOD_PRINCES_CONTROL, DATA_BLOOD_QUEEN_LANA_THEL, DATA_CAPTAIN_ARNATH, DATA_CAPTAIN_BRANDON, DATA_CAPTAIN_GRONDEL, DATA_CAPTAIN_RUPERT, DATA_CROK_SCOURGEBANE, DATA_DEATHBRINGER_SAURFANG, DATA_ENEMY_GUNSHIP, DATA_FESTERGUT, DATA_HIGHLORD_TIRION_FORDRING, DATA_ICECROWN_GUNSHIP_BATTLE, DATA_LADY_DEATHWHISPER, DATA_PRINCE_KELESETH_GUID, DATA_PRINCE_TALDARAM_GUID, DATA_PRINCE_VALANAR_GUID, DATA_PROFESSOR_PUTRICIDE, DATA_PUTRICIDE_TABLE, DATA_RIMEFANG, DATA_ROTFACE, DATA_SAURFANG_EVENT_NPC, DATA_SINDRAGOSA, DATA_SISTER_SVALNA, DATA_SPINESTALKER, DATA_TERENAS_MENETHIL, DATA_THE_LICH_KING, DATA_VALITHRIA_DREAMWALKER, DATA_VALITHRIA_LICH_KING, DATA_VALITHRIA_TRIGGER, DeathbringerSaurfangDoorGUID, DeathbringerSaurfangEventGUID, DeathbringerSaurfangGUID, ObjectGuid::Empty, EnemyGunshipGUID, FestergutGUID, GO_SAURFANG_S_DOOR, GO_SCOURGE_TRANSPORTER_SAURFANG, GunshipGUID, HighlordTirionFordringGUID, LadyDeathwhisperGUID, NPC_PUTRICADES_TRAP, NPC_SINDRAGOSA_GAUNTLET, ProfessorPutricideGUID, PutricadeTrapGUID, PutricideTableGUID, RimefangGUID, RotfaceGUID, SaurfangTeleportGUID, SindragosaGauntletGUID, SindragosaGUID, SisterSvalnaGUID, SpinestalkerGUID, TerenasMenethilGUID, TheLichKingGUID, ValithriaDreamwalkerGUID, ValithriaLichKingGUID, and ValithriaTriggerGUID.
HandleDropAttempt()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::HandleDropAttempt (bool drop = true) inline
        {
            if (!GetData(DATA_HAS_LIMITED_ATTEMPTS))
                return;
            if (drop && HeroicAttempts)
            {
                --HeroicAttempts;
                DoUpdateWorldState(WORLDSTATE_ATTEMPTS_REMAINING, HeroicAttempts);
                SaveToDB();
            }
            if (HeroicAttempts)
                return;
            if (GetBossState(DATA_ROTFACE) == DONE && GetBossState(DATA_FESTERGUT) == DONE)
                if (Creature* professor = instance->GetCreature(ProfessorPutricideGUID))
                    if (professor->IsAlive())
                        professor->SetVisible(false);
            if (Creature* bq = instance->GetCreature(BloodQueenLanaThelGUID))
                if (bq->IsAlive())
                    bq->SetVisible(false);
            if (Creature* sindra = instance->GetCreature(SindragosaGUID))
                if (sindra->IsAlive())
                    sindra->SetVisible(false);
            if (Creature* theLichKing = instance->GetCreature(TheLichKingGUID))
                if (theLichKing->IsAlive())
                    theLichKing->SetVisible(false);
        }
References BloodQueenLanaThelGUID, DATA_FESTERGUT, DATA_HAS_LIMITED_ATTEMPTS, DATA_ROTFACE, DONE, InstanceScript::DoUpdateWorldState(), InstanceScript::GetBossState(), Map::GetCreature(), GetData(), HeroicAttempts, InstanceScript::instance, ProfessorPutricideGUID, InstanceScript::SaveToDB(), SindragosaGUID, TheLichKingGUID, and WORLDSTATE_ATTEMPTS_REMAINING.
Referenced by SetBossState().
OnCreatureCreate()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            if (TeamIdInInstance == TEAM_NEUTRAL)
            {
                Map::PlayerList const& players = instance->GetPlayers();
                if (!players.IsEmpty())
                    if (Player* player = players.begin()->GetSource())
                        TeamIdInInstance = player->GetTeamId();
            }
            // apply ICC buff to pets/summons
            if (GetData(DATA_BUFF_AVAILABLE) && creature->GetOwnerGUID().IsPlayer() && creature->HasUnitTypeMask(UNIT_MASK_MINION | UNIT_MASK_GUARDIAN | UNIT_MASK_CONTROLABLE_GUARDIAN) && creature->CanHaveThreatList())
                if (Unit* owner = creature->GetOwner())
                    if (Player* plr = owner->ToPlayer())
                    {
                        SpellAreaForAreaMapBounds saBounds = sSpellMgr->GetSpellAreaForAreaMapBounds(4812);
                        for (SpellAreaForAreaMap::const_iterator itr = saBounds.first; itr != saBounds.second; ++itr)
                            if ((itr->second->raceMask & plr->getRaceMask()) && !creature->HasAura(itr->second->spellId))
                                if (SpellInfo const* si = sSpellMgr->GetSpellInfo(itr->second->spellId))
                                    if (si->HasAura(SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT))
                                        creature->AddAura(itr->second->spellId, creature);
                    }
            // fighting npcs in Rampart of Skulls
            std::string name1("Skybreaker ");
            std::string name2("Kor'kron ");
            if (!creature->GetTransport() && creature->GetPositionZ() <= 205.0f && creature->GetExactDist2d(-439.0f, 2210.0f) <= 150.0f && (creature->GetEntry() == 37544 || creature->GetEntry() == 37545 || creature->GetName().compare(0, name1.length(), name1) == 0 || creature->GetName().compare(0, name2.length(), name2) == 0))
                creature->AddToNotify(NOTIFY_AI_RELOCATION);
            // pussywizard: check weekly here, before possible UpdateEntry
            // allow creating all of them, because after killing Marrowgar some have to appear, so just hide them
            switch (creature->GetEntry())
            {
                case NPC_INFILTRATOR_MINCHAR:
                case NPC_KOR_KRON_LIEUTENANT:
                case NPC_ALCHEMIST_ADRIANNA:
                case NPC_ALRIN_THE_AGILE:
                case NPC_INFILTRATOR_MINCHAR_BQ:
                case NPC_MINCHAR_BEAM_STALKER:
                case NPC_VALITHRIA_DREAMWALKER_QUEST:
                    for (uint8 i = 0; i < WeeklyNPCs; ++i)
                        if (WeeklyQuestData[i].creatureEntry == creature->GetEntry())
{
                            WeeklyQuestNpcGUID[i] = creature->GetGUID();
                            if (WeeklyQuestId10 != WeeklyQuestData[i].questId[0])
                                creature->SetVisible(false);
                            else if (WeeklyQuestData[i].creatureEntry == NPC_VALITHRIA_DREAMWALKER_QUEST && GetBossState(DATA_VALITHRIA_DREAMWALKER) != DONE)
                                creature->SetVisible(false);
                        }
                    break;
            }
            switch (creature->GetEntry())
            {
                case NPC_KOR_KRON_GENERAL:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_ALLIANCE_COMMANDER);
                    break;
                case NPC_KOR_KRON_LIEUTENANT:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_SKYBREAKER_LIEUTENANT);
                    break;
                case NPC_TORTUNOK:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_ALANA_MOONSTRIKE);
                    break;
                case NPC_GERARDO_THE_SUAVE:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_TALAN_MOONSTRIKE);
                    break;
                case NPC_UVLUS_BANEFIRE:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_MALFUS_GRIMFROST);
                    break;
                case NPC_IKFIRUS_THE_VILE:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_YILI);
                    break;
                case NPC_VOL_GUK:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_JEDEBIA);
                    break;
                case NPC_HARAGG_THE_UNSEEN:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_NIBY_THE_ALMIGHTY);
                    break;
                case NPC_GARROSH_HELLSCREAM:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_KING_VARIAN_WRYNN);
                    // Xinef: summon in case of instance unload
                    if (GetBossState(DATA_THE_LICH_KING) == DONE)
                    {
                        instance->SummonCreature(NPC_LADY_JAINA_PROUDMOORE_QUEST, JainaSpawnPos);
                        instance->SummonCreature(NPC_MURADIN_BRONZEBEARD_QUEST, MuradinSpawnPos);
                        instance->SummonCreature(NPC_UTHER_THE_LIGHTBRINGER_QUEST, UtherSpawnPos);
                        instance->SummonCreature(NPC_LADY_SYLVANAS_WINDRUNNER_QUEST, SylvanasSpawnPos);
                    }
                    break;
                case NPC_LADY_DEATHWHISPER:
                    LadyDeathwhisperGUID = creature->GetGUID();
                    break;
                case NPC_DEATHBRINGER_SAURFANG:
                    DeathbringerSaurfangGUID = creature->GetGUID();
                    break;
                case NPC_SE_HIGH_OVERLORD_SAURFANG:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                    {
                        creature->UpdateEntry(NPC_SE_MURADIN_BRONZEBEARD, true);
                        creature->LoadEquipment();
                    }
                    DeathbringerSaurfangEventGUID = creature->GetGUID();
                    creature->LastUsedScriptID = creature->GetScriptId();
                    break;
                case NPC_SE_MURADIN_BRONZEBEARD:
                    DeathbringerSaurfangEventGUID = creature->GetGUID();
                    break;
                case NPC_HIGH_OVERLORD_SAURFANG_DUMMY:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                    {
                        creature->UpdateEntry(NPC_MURADIN_BRONZEBEARD_DUMMY, creature->GetCreatureData());
                        creature->LoadEquipment();
                    }
                    break;
                case NPC_SE_KOR_KRON_REAVER:
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_SE_SKYBREAKER_MARINE);
                    break;
                case NPC_FESTERGUT:
                    FestergutGUID = creature->GetGUID();
                    break;
                case NPC_ROTFACE:
                    RotfaceGUID = creature->GetGUID();
                    break;
                case NPC_PROFESSOR_PUTRICIDE:
                    ProfessorPutricideGUID = creature->GetGUID();
                    if (GetBossState(DATA_ROTFACE) == DONE && GetBossState(DATA_FESTERGUT) == DONE && !HeroicAttempts && GetData(DATA_HAS_LIMITED_ATTEMPTS) && creature->IsAlive())
                        creature->SetVisible(false);
                    break;
                case NPC_PRINCE_KELESETH:
                    BloodCouncilGUIDs[0] = creature->GetGUID();
                    break;
                case NPC_PRINCE_TALDARAM:
                    BloodCouncilGUIDs[1] = creature->GetGUID();
                    break;
                case NPC_PRINCE_VALANAR:
                    BloodCouncilGUIDs[2] = creature->GetGUID();
                    break;
                case NPC_BLOOD_ORB_CONTROLLER:
                    BloodCouncilControllerGUID = creature->GetGUID();
                    break;
                case NPC_BLOOD_QUEEN_LANA_THEL:
                    BloodQueenLanaThelGUID = creature->GetGUID();
                    if (!HeroicAttempts && GetData(DATA_HAS_LIMITED_ATTEMPTS) && creature->IsAlive())
                        creature->SetVisible(false);
                    break;
                case NPC_CROK_SCOURGEBANE:
                    CrokScourgebaneGUID = creature->GetGUID();
                    break;
                // we can only do this because there are no gaps in their entries
                case NPC_CAPTAIN_ARNATH:
                case NPC_CAPTAIN_BRANDON:
                case NPC_CAPTAIN_GRONDEL:
                case NPC_CAPTAIN_RUPERT:
                    CrokCaptainGUIDs[creature->GetEntry() - NPC_CAPTAIN_ARNATH] = creature->GetGUID();
                    break;
                case NPC_SISTER_SVALNA:
                    SisterSvalnaGUID = creature->GetGUID();
                    break;
                case NPC_VALITHRIA_DREAMWALKER:
                    ValithriaDreamwalkerGUID = creature->GetGUID();
                    break;
                case NPC_THE_LICH_KING_VALITHRIA:
                    ValithriaLichKingGUID = creature->GetGUID();
                    break;
                case NPC_THE_LICH_KING_LH:
                    TheLichKingLhGUID = creature->GetGUID();
                    break;
                case NPC_GREEN_DRAGON_COMBAT_TRIGGER:
                    ValithriaTriggerGUID = creature->GetGUID();
                    break;
                case NPC_PUTRICADES_TRAP:
                    PutricadeTrapGUID = creature->GetGUID();
                    break;
                case NPC_SINDRAGOSA_GAUNTLET:
                    SindragosaGauntletGUID = creature->GetGUID();
                    break;
                case NPC_SINDRAGOSA:
                    SindragosaGUID = creature->GetGUID();
                    if (!HeroicAttempts && GetData(DATA_HAS_LIMITED_ATTEMPTS) && creature->IsAlive())
                        creature->SetVisible(false);
                    break;
                case NPC_SPINESTALKER:
                    SpinestalkerGUID = creature->GetGUID();
                    break;
                case NPC_RIMEFANG:
                    RimefangGUID = creature->GetGUID();
                    break;
                case NPC_INVISIBLE_STALKER:
                    // Teleporter visual at center
                    if (creature->GetExactDist2d(4357.052f, 2769.421f) < 10.0f && GetBossState(DATA_PROFESSOR_PUTRICIDE) == DONE && GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) == DONE && GetBossState(DATA_SINDRAGOSA) == DONE)
                        creature->CastSpell(creature, SPELL_ARTHAS_TELEPORTER_CEREMONY, false);
                    break;
                case NPC_THE_LICH_KING:
                    TheLichKingGUID = creature->GetGUID();
                    if (!HeroicAttempts && GetData(DATA_HAS_LIMITED_ATTEMPTS) && creature->IsAlive())
                        creature->SetVisible(false);
                    break;
                case NPC_HIGHLORD_TIRION_FORDRING_LK:
                    HighlordTirionFordringGUID = creature->GetGUID();
                    break;
                case NPC_TERENAS_MENETHIL_FROSTMOURNE:
                case NPC_TERENAS_MENETHIL_FROSTMOURNE_H:
                    TerenasMenethilGUID = creature->GetGUID();
                    break;
                case NPC_INFILTRATOR_MINCHAR_BQ:
                    if (BloodQuickeningState == DONE)
                        creature->DespawnOrUnsummon(1);
                    break;
                case NPC_MINCHAR_BEAM_STALKER:
                    if (BloodQuickeningState != DONE)
                    {
                        uint32 spellId = 0;
                        if (creature->GetPositionY() > 2790.0f && creature->GetPositionZ() > 420.0f)
                            spellId = BLOOD_BEAM_VISUAL_RHAND;
                        else if (creature->GetPositionY() < 2790.0f && creature->GetPositionZ() > 420.0f)
                            spellId = BLOOD_BEAM_VISUAL_LHAND;
                        else if (creature->GetPositionY() < 2790.0f && creature->GetPositionZ() < 420.0f)
                            spellId = BLOOD_BEAM_VISUAL_LLEG;
                        else
                            spellId = BLOOD_BEAM_VISUAL_RLEG;
                        creature->m_Events.AddEvent(new DelayedCastMincharEvent(creature, spellId), creature->m_Events.CalculateTime(1000));
                    }
                    break;
                case NPC_SKYBREAKER_DECKHAND:
                case NPC_ORGRIMS_HAMMER_CREW:
                    if (!creature->IsAlive())
                        creature->Respawn();
                    break;
                default:
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References Unit::AddAura(), EventProcessor::AddEvent(), WorldObject::AddToNotify(), MapRefMgr::begin(), BLOOD_BEAM_VISUAL_LHAND, BLOOD_BEAM_VISUAL_LLEG, BLOOD_BEAM_VISUAL_RHAND, BLOOD_BEAM_VISUAL_RLEG, BloodCouncilControllerGUID, BloodCouncilGUIDs, BloodQueenLanaThelGUID, BloodQuickeningState, EventProcessor::CalculateTime(), Unit::CanHaveThreatList(), Unit::CastSpell(), CrokCaptainGUIDs, CrokScourgebaneGUID, DATA_BLOOD_QUEEN_LANA_THEL, DATA_BUFF_AVAILABLE, DATA_FESTERGUT, DATA_HAS_LIMITED_ATTEMPTS, DATA_PROFESSOR_PUTRICIDE, DATA_ROTFACE, DATA_SINDRAGOSA, DATA_THE_LICH_KING, DATA_VALITHRIA_DREAMWALKER, DeathbringerSaurfangEventGUID, DeathbringerSaurfangGUID, Creature::DespawnOrUnsummon(), DONE, FestergutGUID, InstanceScript::GetBossState(), Creature::GetCreatureData(), GetData(), Object::GetEntry(), Position::GetExactDist2d(), Object::GetGUID(), WorldObject::GetName(), Unit::GetOwner(), Unit::GetOwnerGUID(), Map::GetPlayers(), Position::GetPositionY(), Position::GetPositionZ(), Creature::GetScriptId(), Reference< TO, FROM >::GetSource(), WorldObject::GetTransport(), Unit::HasAura(), Unit::HasUnitTypeMask(), HeroicAttempts, HighlordTirionFordringGUID, InstanceScript::instance, Unit::IsAlive(), LinkedListHead::IsEmpty(), ObjectGuid::IsPlayer(), JainaSpawnPos, LadyDeathwhisperGUID, WorldObject::LastUsedScriptID, Creature::LoadEquipment(), WorldObject::m_Events, MuradinSpawnPos, NOTIFY_AI_RELOCATION, NPC_ALANA_MOONSTRIKE, NPC_ALCHEMIST_ADRIANNA, NPC_ALLIANCE_COMMANDER, NPC_ALRIN_THE_AGILE, NPC_BLOOD_ORB_CONTROLLER, NPC_BLOOD_QUEEN_LANA_THEL, NPC_CAPTAIN_ARNATH, NPC_CAPTAIN_BRANDON, NPC_CAPTAIN_GRONDEL, NPC_CAPTAIN_RUPERT, NPC_CROK_SCOURGEBANE, NPC_DEATHBRINGER_SAURFANG, NPC_FESTERGUT, NPC_GARROSH_HELLSCREAM, NPC_GERARDO_THE_SUAVE, NPC_GREEN_DRAGON_COMBAT_TRIGGER, NPC_HARAGG_THE_UNSEEN, NPC_HIGH_OVERLORD_SAURFANG_DUMMY, NPC_HIGHLORD_TIRION_FORDRING_LK, NPC_IKFIRUS_THE_VILE, NPC_INFILTRATOR_MINCHAR, NPC_INFILTRATOR_MINCHAR_BQ, NPC_INVISIBLE_STALKER, NPC_JEDEBIA, NPC_KING_VARIAN_WRYNN, NPC_KOR_KRON_GENERAL, NPC_KOR_KRON_LIEUTENANT, NPC_LADY_DEATHWHISPER, NPC_LADY_JAINA_PROUDMOORE_QUEST, NPC_LADY_SYLVANAS_WINDRUNNER_QUEST, NPC_MALFUS_GRIMFROST, NPC_MINCHAR_BEAM_STALKER, NPC_MURADIN_BRONZEBEARD_DUMMY, NPC_MURADIN_BRONZEBEARD_QUEST, NPC_NIBY_THE_ALMIGHTY, NPC_ORGRIMS_HAMMER_CREW, NPC_PRINCE_KELESETH, NPC_PRINCE_TALDARAM, NPC_PRINCE_VALANAR, NPC_PROFESSOR_PUTRICIDE, NPC_PUTRICADES_TRAP, NPC_RIMEFANG, NPC_ROTFACE, NPC_SE_HIGH_OVERLORD_SAURFANG, NPC_SE_KOR_KRON_REAVER, NPC_SE_MURADIN_BRONZEBEARD, NPC_SE_SKYBREAKER_MARINE, NPC_SINDRAGOSA, NPC_SINDRAGOSA_GAUNTLET, NPC_SISTER_SVALNA, NPC_SKYBREAKER_DECKHAND, NPC_SKYBREAKER_LIEUTENANT, NPC_SPINESTALKER, NPC_TALAN_MOONSTRIKE, NPC_TERENAS_MENETHIL_FROSTMOURNE, NPC_TERENAS_MENETHIL_FROSTMOURNE_H, NPC_THE_LICH_KING, NPC_THE_LICH_KING_LH, NPC_THE_LICH_KING_VALITHRIA, NPC_TORTUNOK, NPC_UTHER_THE_LIGHTBRINGER_QUEST, NPC_UVLUS_BANEFIRE, NPC_VALITHRIA_DREAMWALKER, NPC_VALITHRIA_DREAMWALKER_QUEST, NPC_VOL_GUK, NPC_YILI, InstanceScript::OnCreatureCreate(), ProfessorPutricideGUID, PutricadeTrapGUID, Creature::Respawn(), RimefangGUID, RotfaceGUID, Unit::SetVisible(), SindragosaGauntletGUID, SindragosaGUID, SisterSvalnaGUID, SPELL_ARTHAS_TELEPORTER_CEREMONY, SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT, SpinestalkerGUID, sSpellMgr, Map::SummonCreature(), SylvanasSpawnPos, TEAM_ALLIANCE, TEAM_NEUTRAL, TeamIdInInstance, TerenasMenethilGUID, TheLichKingGUID, TheLichKingLhGUID, Object::ToPlayer(), UNIT_MASK_CONTROLABLE_GUARDIAN, UNIT_MASK_GUARDIAN, UNIT_MASK_MINION, Creature::UpdateEntry(), UtherSpawnPos, ValithriaDreamwalkerGUID, ValithriaLichKingGUID, ValithriaTriggerGUID, WeeklyNPCs, WeeklyQuestData, WeeklyQuestId10, and WeeklyQuestNpcGUID.
OnCreatureRemove()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureRemove (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            if (creature->GetEntry() == NPC_SINDRAGOSA)
                SindragosaGUID.Clear();
            InstanceScript::OnCreatureRemove(creature);
        }
References ObjectGuid::Clear(), Object::GetEntry(), NPC_SINDRAGOSA, InstanceScript::OnCreatureRemove(), and SindragosaGUID.
OnGameObjectCreate()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            if (TeamIdInInstance == TEAM_NEUTRAL)
            {
                Map::PlayerList const& players = instance->GetPlayers();
                if (!players.IsEmpty())
                    if (Player* player = players.begin()->GetSource())
                        TeamIdInInstance = player->GetTeamId();
            }
            switch (go->GetEntry())
            {
                case GO_SPIRIT_ALARM_1:
                case GO_SPIRIT_ALARM_2:
                case GO_SPIRIT_ALARM_3:
                case GO_SPIRIT_ALARM_4:
                    SetPositionTraps(go);
                    break;
                case GO_GEIST_ALARM_1:
                case GO_GEIST_ALARM_2:
                    go->SetPosition(go->GetPositionX() + urand(0, 2) * 20.0f * (go->GetEntry() == GO_GEIST_ALARM_1 ? -1.0f : 1.0f), go->GetPositionY(), go->GetPositionZ(), go->GetOrientation());
                    break;
                case GO_DOODAD_ICECROWN_ICEWALL02:
                case GO_ICEWALL:
                case GO_LORD_MARROWGAR_S_ENTRANCE:
                case GO_ORATORY_OF_THE_DAMNED_ENTRANCE:
                case GO_ORANGE_PLAGUE_MONSTER_ENTRANCE:
                case GO_GREEN_PLAGUE_MONSTER_ENTRANCE:
                case GO_CRIMSON_HALL_DOOR:
                case GO_BLOOD_ELF_COUNCIL_DOOR:
                case GO_BLOOD_ELF_COUNCIL_DOOR_RIGHT:
                case GO_DOODAD_ICECROWN_BLOODPRINCE_DOOR_01:
                case GO_DOODAD_ICECROWN_GRATE_01:
                case GO_GREEN_DRAGON_BOSS_ENTRANCE:
                case GO_GREEN_DRAGON_BOSS_EXIT:
                case GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_02:
                case GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_03:
                case GO_SINDRAGOSA_SHORTCUT_ENTRANCE_DOOR:
                case GO_SINDRAGOSA_SHORTCUT_EXIT_DOOR:
                case GO_ICE_WALL:
                case GO_SINDRAGOSA_ENTRANCE_DOOR:
                    AddDoor(go);
                    break;
                case GO_SCIENTIST_ENTRANCE:
                    PutricideEnteranceDoorGUID = go->GetGUID();
                    HandleGameObject(PutricideEnteranceDoorGUID, PutricideEventProgress & PUTRICIDE_EVENT_FLAG_TRAP_FINISHED, go);
                    break;
                // these 2 gates are functional only on 25man modes
                case GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_01:
                case GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_04:
                    if (instance->Is25ManRaid())
                        AddDoor(go);
                    break;
                case GO_LADY_DEATHWHISPER_ELEVATOR:
                    LadyDeathwisperElevatorGUID = go->GetGUID();
                    break;
                case GO_THE_SKYBREAKER_H:
                case GO_ORGRIMS_HAMMER_A:
                    EnemyGunshipGUID = go->GetGUID();
                    break;
                case GO_GUNSHIP_ARMORY_H_10N:
                case GO_GUNSHIP_ARMORY_H_25N:
                case GO_GUNSHIP_ARMORY_H_10H:
                case GO_GUNSHIP_ARMORY_H_25H:
                case GO_GUNSHIP_ARMORY_A_10N:
                case GO_GUNSHIP_ARMORY_A_25N:
                case GO_GUNSHIP_ARMORY_A_10H:
                case GO_GUNSHIP_ARMORY_A_25H:
                    GunshipArmoryGUID = go->GetGUID();
                    break;
                case GO_SAURFANG_S_DOOR:
                    DeathbringerSaurfangDoorGUID = go->GetGUID();
                    AddDoor(go);
                    break;
                case GO_DEATHBRINGER_S_CACHE_10N:
                case GO_DEATHBRINGER_S_CACHE_25N:
                case GO_DEATHBRINGER_S_CACHE_10H:
                case GO_DEATHBRINGER_S_CACHE_25H:
                    DeathbringersCacheGUID = go->GetGUID();
                    break;
                case GO_SCOURGE_TRANSPORTER_SAURFANG:
                    SaurfangTeleportGUID = go->GetGUID();
                    break;
                case GO_PLAGUE_SIGIL:
                    PlagueSigilGUID = go->GetGUID();
                    if (GetBossState(DATA_PROFESSOR_PUTRICIDE) == DONE)
                        HandleGameObject(PlagueSigilGUID, false, go);
                    break;
                case GO_BLOODWING_SIGIL:
                    BloodwingSigilGUID = go->GetGUID();
                    if (GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) == DONE)
                        HandleGameObject(BloodwingSigilGUID, false, go);
                    break;
                case GO_SIGIL_OF_THE_FROSTWING:
                    FrostwingSigilGUID = go->GetGUID();
                    if (GetBossState(DATA_SINDRAGOSA) == DONE)
                        HandleGameObject(FrostwingSigilGUID, false, go);
                    break;
                case GO_SCIENTIST_AIRLOCK_DOOR_COLLISION:
                    PutricideCollisionGUID = go->GetGUID();
                    HandleGameObject(PutricideCollisionGUID, ((PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE) && (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE)), go);
                    break;
                case GO_SCIENTIST_AIRLOCK_DOOR_ORANGE:
                    PutricideGateGUIDs[0] = go->GetGUID();
                    if ((PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE) && (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE))
                        go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
                    else
                        HandleGameObject(PutricideGateGUIDs[0], !(PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE), go);
                    break;
                case GO_SCIENTIST_AIRLOCK_DOOR_GREEN:
                    PutricideGateGUIDs[1] = go->GetGUID();
                    if ((PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE) && (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE))
                        go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
                    else
                        HandleGameObject(PutricideGateGUIDs[1], !(PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE), go);
                    break;
                case GO_DOODAD_ICECROWN_ORANGETUBES02:
                    PutricidePipeGUIDs[0] = go->GetGUID();
                    if (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE)
                        HandleGameObject(PutricidePipeGUIDs[0], true, go);
                    break;
                case GO_DOODAD_ICECROWN_GREENTUBES02:
                    PutricidePipeGUIDs[1] = go->GetGUID();
                    if (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE)
                        HandleGameObject(PutricidePipeGUIDs[1], true, go);
                    break;
                case GO_GAS_RELEASE_VALVE:
                    GasReleaseValveGUID = go->GetGUID();
                    if (GetBossState(DATA_FESTERGUT) != DONE)
                        go->SetGameObjectFlag(GO_FLAG_INTERACT_COND | GO_FLAG_NOT_SELECTABLE);
                    break;
                case GO_OOZE_RELEASE_VALVE:
                    OozeReleaseValveGUID = go->GetGUID();
                    if (GetBossState(DATA_ROTFACE) != DONE)
                        go->SetGameObjectFlag(GO_FLAG_INTERACT_COND | GO_FLAG_NOT_SELECTABLE);
                    break;
                case GO_DRINK_ME:
                    PutricideTableGUID = go->GetGUID();
                    break;
                case GO_CACHE_OF_THE_DREAMWALKER_10N:
                case GO_CACHE_OF_THE_DREAMWALKER_25N:
                case GO_CACHE_OF_THE_DREAMWALKER_10H:
                case GO_CACHE_OF_THE_DREAMWALKER_25H:
                    if (Creature* valithria = instance->GetCreature(ValithriaDreamwalkerGUID))
                        go->SetLootRecipient(valithria);
                    go->RemoveGameObjectFlag(GO_FLAG_LOCKED | GO_FLAG_NOT_SELECTABLE | GO_FLAG_NODESPAWN);
                    break;
                case GO_SCOURGE_TRANSPORTER_LK:
                    TheLichKingTeleportGUID = go->GetGUID();
                    if (GetBossState(DATA_PROFESSOR_PUTRICIDE) == DONE && GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) == DONE && GetBossState(DATA_SINDRAGOSA) == DONE)
                        go->SetGoState(GO_STATE_ACTIVE);
                    break;
                case GO_ARTHAS_PLATFORM:
                    // this enables movement at The Frozen Throne, when printed this value is 0.000000f
                    // however, when represented as integer client will accept only this value
                    go->SetUInt32Value(GAMEOBJECT_PARENTROTATION, 5535469);
                    ArthasPlatformGUID = go->GetGUID();
                    break;
                case GO_ARTHAS_PRECIPICE:
                    go->SetUInt32Value(GAMEOBJECT_PARENTROTATION, 4178312);
                    ArthasPrecipiceGUID = go->GetGUID();
                    break;
                case GO_DOODAD_ICECROWN_THRONEFROSTYEDGE01:
                    FrozenThroneEdgeGUID = go->GetGUID();
                    break;
                case GO_DOODAD_ICECROWN_THRONEFROSTYWIND01:
                    FrozenThroneWindGUID = go->GetGUID();
                    break;
                case GO_DOODAD_ICECROWN_SNOWEDGEWARNING01:
                    FrozenThroneWarningGUID = go->GetGUID();
                    break;
                case GO_FROZEN_LAVAMAN:
                    FrozenBolvarGUID = go->GetGUID();
                    if (GetBossState(DATA_THE_LICH_KING) == DONE)
                        go->SetRespawnTime(7 * DAY);
                    break;
                case GO_LAVAMAN_PILLARS_CHAINED:
                    PillarsChainedGUID = go->GetGUID();
                    if (GetBossState(DATA_THE_LICH_KING) == DONE)
                        go->SetRespawnTime(7 * DAY);
                    break;
                case GO_LAVAMAN_PILLARS_UNCHAINED:
                    PillarsUnchainedGUID = go->GetGUID();
                    if (GetBossState(DATA_THE_LICH_KING) == DONE)
                        go->SetRespawnTime(7 * DAY);
                    break;
                case GO_SCOURGE_TRANSPORTER_FIRST:
                    AddDoor(go);
                    ScourgeTransporterFirstGUID = go->GetGUID();
                    if (GetBossState(DATA_LORD_MARROWGAR) == DONE)
                        go->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                    break;
                default:
                    break;
            }
        }
References InstanceScript::AddDoor(), ArthasPlatformGUID, ArthasPrecipiceGUID, MapRefMgr::begin(), BloodwingSigilGUID, DATA_BLOOD_QUEEN_LANA_THEL, DATA_FESTERGUT, DATA_LORD_MARROWGAR, DATA_PROFESSOR_PUTRICIDE, DATA_ROTFACE, DATA_SINDRAGOSA, DATA_THE_LICH_KING, DAY, DeathbringerSaurfangDoorGUID, DeathbringersCacheGUID, DONE, EnemyGunshipGUID, FrostwingSigilGUID, FrozenBolvarGUID, FrozenThroneEdgeGUID, FrozenThroneWarningGUID, FrozenThroneWindGUID, GAMEOBJECT_PARENTROTATION, GasReleaseValveGUID, InstanceScript::GetBossState(), Map::GetCreature(), Object::GetEntry(), Object::GetGUID(), Position::GetOrientation(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Reference< TO, FROM >::GetSource(), GO_ARTHAS_PLATFORM, GO_ARTHAS_PRECIPICE, GO_BLOOD_ELF_COUNCIL_DOOR, GO_BLOOD_ELF_COUNCIL_DOOR_RIGHT, GO_BLOODWING_SIGIL, GO_CACHE_OF_THE_DREAMWALKER_10H, GO_CACHE_OF_THE_DREAMWALKER_10N, GO_CACHE_OF_THE_DREAMWALKER_25H, GO_CACHE_OF_THE_DREAMWALKER_25N, GO_CRIMSON_HALL_DOOR, GO_DEATHBRINGER_S_CACHE_10H, GO_DEATHBRINGER_S_CACHE_10N, GO_DEATHBRINGER_S_CACHE_25H, GO_DEATHBRINGER_S_CACHE_25N, GO_DOODAD_ICECROWN_BLOODPRINCE_DOOR_01, GO_DOODAD_ICECROWN_GRATE_01, GO_DOODAD_ICECROWN_GREENTUBES02, GO_DOODAD_ICECROWN_ICEWALL02, GO_DOODAD_ICECROWN_ORANGETUBES02, GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_01, GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_02, GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_03, GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_04, GO_DOODAD_ICECROWN_SNOWEDGEWARNING01, GO_DOODAD_ICECROWN_THRONEFROSTYEDGE01, GO_DOODAD_ICECROWN_THRONEFROSTYWIND01, GO_DRINK_ME, GO_FLAG_INTERACT_COND, GO_FLAG_LOCKED, GO_FLAG_NODESPAWN, GO_FLAG_NOT_SELECTABLE, GO_FROZEN_LAVAMAN, GO_GAS_RELEASE_VALVE, GO_GEIST_ALARM_1, GO_GEIST_ALARM_2, GO_GREEN_DRAGON_BOSS_ENTRANCE, GO_GREEN_DRAGON_BOSS_EXIT, GO_GREEN_PLAGUE_MONSTER_ENTRANCE, GO_GUNSHIP_ARMORY_A_10H, GO_GUNSHIP_ARMORY_A_10N, GO_GUNSHIP_ARMORY_A_25H, GO_GUNSHIP_ARMORY_A_25N, GO_GUNSHIP_ARMORY_H_10H, GO_GUNSHIP_ARMORY_H_10N, GO_GUNSHIP_ARMORY_H_25H, GO_GUNSHIP_ARMORY_H_25N, GO_ICE_WALL, GO_ICEWALL, GO_LADY_DEATHWHISPER_ELEVATOR, GO_LAVAMAN_PILLARS_CHAINED, GO_LAVAMAN_PILLARS_UNCHAINED, GO_LORD_MARROWGAR_S_ENTRANCE, GO_OOZE_RELEASE_VALVE, GO_ORANGE_PLAGUE_MONSTER_ENTRANCE, GO_ORATORY_OF_THE_DAMNED_ENTRANCE, GO_ORGRIMS_HAMMER_A, GO_PLAGUE_SIGIL, GO_SAURFANG_S_DOOR, GO_SCIENTIST_AIRLOCK_DOOR_COLLISION, GO_SCIENTIST_AIRLOCK_DOOR_GREEN, GO_SCIENTIST_AIRLOCK_DOOR_ORANGE, GO_SCIENTIST_ENTRANCE, GO_SCOURGE_TRANSPORTER_FIRST, GO_SCOURGE_TRANSPORTER_LK, GO_SCOURGE_TRANSPORTER_SAURFANG, GO_SIGIL_OF_THE_FROSTWING, GO_SINDRAGOSA_ENTRANCE_DOOR, GO_SINDRAGOSA_SHORTCUT_ENTRANCE_DOOR, GO_SINDRAGOSA_SHORTCUT_EXIT_DOOR, GO_SPIRIT_ALARM_1, GO_SPIRIT_ALARM_2, GO_SPIRIT_ALARM_3, GO_SPIRIT_ALARM_4, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_THE_SKYBREAKER_H, GunshipArmoryGUID, InstanceScript::HandleGameObject(), InstanceScript::instance, Map::Is25ManRaid(), LinkedListHead::IsEmpty(), LadyDeathwisperElevatorGUID, OozeReleaseValveGUID, PillarsChainedGUID, PillarsUnchainedGUID, PlagueSigilGUID, PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE, PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE, PUTRICIDE_EVENT_FLAG_TRAP_FINISHED, PutricideCollisionGUID, PutricideEnteranceDoorGUID, PutricideEventProgress, PutricideGateGUIDs, PutricidePipeGUIDs, PutricideTableGUID, GameObject::RemoveGameObjectFlag(), SaurfangTeleportGUID, ScourgeTransporterFirstGUID, GameObject::SetGameObjectFlag(), GameObject::SetGoState(), GameObject::SetLootRecipient(), GameObject::SetPosition(), SetPositionTraps(), GameObject::SetRespawnTime(), Object::SetUInt32Value(), TEAM_NEUTRAL, TeamIdInInstance, TheLichKingTeleportGUID, urand(), and ValithriaDreamwalkerGUID.
OnGameObjectRemove()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_DOODAD_ICECROWN_ICEWALL02:
                case GO_ICEWALL:
                case GO_LORD_MARROWGAR_S_ENTRANCE:
                case GO_ORATORY_OF_THE_DAMNED_ENTRANCE:
                case GO_SAURFANG_S_DOOR:
                case GO_ORANGE_PLAGUE_MONSTER_ENTRANCE:
                case GO_GREEN_PLAGUE_MONSTER_ENTRANCE:
                case GO_SCIENTIST_ENTRANCE:
                case GO_CRIMSON_HALL_DOOR:
                case GO_BLOOD_ELF_COUNCIL_DOOR:
                case GO_BLOOD_ELF_COUNCIL_DOOR_RIGHT:
                case GO_DOODAD_ICECROWN_BLOODPRINCE_DOOR_01:
                case GO_DOODAD_ICECROWN_GRATE_01:
                case GO_GREEN_DRAGON_BOSS_ENTRANCE:
                case GO_GREEN_DRAGON_BOSS_EXIT:
                case GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_01:
                case GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_02:
                case GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_03:
                case GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_04:
                //case GO_SINDRAGOSA_ENTRANCE_DOOR:
                case GO_SINDRAGOSA_SHORTCUT_ENTRANCE_DOOR:
                case GO_SINDRAGOSA_SHORTCUT_EXIT_DOOR:
                case GO_ICE_WALL:
                case GO_SCOURGE_TRANSPORTER_FIRST:
                    RemoveDoor(go);
                    break;
                case GO_THE_SKYBREAKER_A:
                case GO_ORGRIMS_HAMMER_H:
                    GunshipGUID.Clear();
                    break;
                default:
                    break;
            }
        }
References ObjectGuid::Clear(), Object::GetEntry(), GO_BLOOD_ELF_COUNCIL_DOOR, GO_BLOOD_ELF_COUNCIL_DOOR_RIGHT, GO_CRIMSON_HALL_DOOR, GO_DOODAD_ICECROWN_BLOODPRINCE_DOOR_01, GO_DOODAD_ICECROWN_GRATE_01, GO_DOODAD_ICECROWN_ICEWALL02, GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_01, GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_02, GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_03, GO_DOODAD_ICECROWN_ROOSTPORTCULLIS_04, GO_GREEN_DRAGON_BOSS_ENTRANCE, GO_GREEN_DRAGON_BOSS_EXIT, GO_GREEN_PLAGUE_MONSTER_ENTRANCE, GO_ICE_WALL, GO_ICEWALL, GO_LORD_MARROWGAR_S_ENTRANCE, GO_ORANGE_PLAGUE_MONSTER_ENTRANCE, GO_ORATORY_OF_THE_DAMNED_ENTRANCE, GO_ORGRIMS_HAMMER_H, GO_SAURFANG_S_DOOR, GO_SCIENTIST_ENTRANCE, GO_SCOURGE_TRANSPORTER_FIRST, GO_SINDRAGOSA_SHORTCUT_ENTRANCE_DOOR, GO_SINDRAGOSA_SHORTCUT_EXIT_DOOR, GO_THE_SKYBREAKER_A, GunshipGUID, and InstanceScript::RemoveDoor().
OnPlayerAreaUpdate()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnPlayerAreaUpdate (Player * player, uint32 , uint32 newArea) inline override virtual
Reimplemented from InstanceScript.
        {
            if (newArea == 4890 /*Putricide's Laboratory of Alchemical Horrors and Fun*/ ||
                    newArea == 4891 /*The Sanctum of Blood*/ ||
                    newArea == 4889 /*The Frost Queen's Lair*/ ||
                    newArea == 4859 /*The Frozen Throne*/ ||
                    newArea == 4910 /*Frostmourne*/)
            {
                player->SendInitWorldStates(player->GetZoneId(), player->GetAreaId());
            }
            else
            {
                player->SendUpdateWorldState(WORLDSTATE_SHOW_ATTEMPTS, 0);
            }
        }
References WorldObject::GetAreaId(), WorldObject::GetZoneId(), Player::SendInitWorldStates(), Player::SendUpdateWorldState(), and WORLDSTATE_SHOW_ATTEMPTS.
OnPlayerEnter()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
        {
            if (TeamIdInInstance == TEAM_NEUTRAL)
                TeamIdInInstance = player->GetTeamId();
            // for professor putricide hc
            DoRemoveAurasDueToSpellOnPlayers(SPELL_GAS_VARIABLE);
            DoRemoveAurasDueToSpellOnPlayers(SPELL_OOZE_VARIABLE);
            if (GetBossState(DATA_LADY_DEATHWHISPER) == DONE && GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) != DONE)
                SpawnGunship();
            if (GetBossState(DATA_SINDRAGOSA) != DONE && IsSindragosaIntroDone && !GetCreature(DATA_SINDRAGOSA) && Events.GetTimeUntilEvent(EVENT_RESPAWN_SINDRAGOSA) == Milliseconds::max())
            {
                Events.ScheduleEvent(EVENT_RESPAWN_SINDRAGOSA, 30s);
            }
            if (IsBuffAvailable)
            {
                SpellAreaForAreaMapBounds saBounds = sSpellMgr->GetSpellAreaForAreaMapBounds(4812);
                for (SpellAreaForAreaMap::const_iterator itr = saBounds.first; itr != saBounds.second; ++itr)
                    if ((itr->second->raceMask & player->getRaceMask()) && !player->HasAura(itr->second->spellId))
                    {
                        if (SpellInfo const* si = sSpellMgr->GetSpellInfo(itr->second->spellId))
{
                            if (si->HasAura(SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT))
{
                                DoCastSpellOnPlayer(player, itr->second->spellId, false, false);
                            }
                        }
                    }
            }
        }
References DATA_ICECROWN_GUNSHIP_BATTLE, DATA_LADY_DEATHWHISPER, DATA_SINDRAGOSA, InstanceScript::DoCastSpellOnPlayer(), DONE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), EVENT_RESPAWN_SINDRAGOSA, InstanceScript::GetBossState(), InstanceScript::GetCreature(), Unit::getRaceMask(), Player::GetTeamId(), Unit::HasAura(), IsBuffAvailable, IsSindragosaIntroDone, SpawnGunship(), SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT, SPELL_GAS_VARIABLE, SPELL_OOZE_VARIABLE, sSpellMgr, TEAM_NEUTRAL, and TeamIdInInstance.
OnUnitDeath()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            Creature* creature = unit->ToCreature();
            if (!creature)
                return;
            // fighting npcs in Rampart of Skulls
            std::string name1("Skybreaker ");
            std::string name2("Kor'kron ");
            if (!creature->GetTransport() && creature->GetPositionZ() <= 205.0f && creature->GetExactDist2d(-439.0f, 2210.0f) <= 150.0f && (creature->GetEntry() == 37544 || creature->GetEntry() == 37545 || creature->GetName().compare(0, name1.length(), name1) == 0 || creature->GetName().compare(0, name2.length(), name2) == 0))
                if (!creature->GetLootRecipient())
                    creature->m_Events.AddEvent(new RespawnEvent(*creature), creature->m_Events.CalculateTime(3000));
            switch (creature->GetEntry())
            {
                case NPC_YMIRJAR_BATTLE_MAIDEN:
                case NPC_YMIRJAR_DEATHBRINGER:
                case NPC_YMIRJAR_FROSTBINDER:
                case NPC_YMIRJAR_HUNTRESS:
                case NPC_YMIRJAR_WARLORD:
                    if (Creature* crok = instance->GetCreature(CrokScourgebaneGUID))
                        crok->AI()->SetGUID(creature->GetGUID(), ACTION_VRYKUL_DEATH);
                    break;
                case NPC_FROSTWING_WHELP:
                    if (FrostwyrmGUIDs.empty())
                        return;
                    if (creature->AI()->GetData(1/*DATA_FROSTWYRM_OWNER*/) == DATA_SPINESTALKER)
                    {
                        SpinestalkerTrash.erase(creature->GetSpawnId());
                        if (SpinestalkerTrash.empty())
                            if (Creature* spinestalk = instance->GetCreature(SpinestalkerGUID))
                                spinestalk->AI()->DoAction(ACTION_START_FROSTWYRM);
                    }
                    else
                    {
                        RimefangTrash.erase(creature->GetSpawnId());
                        if (RimefangTrash.empty())
                            if (Creature* spinestalk = instance->GetCreature(RimefangGUID))
                                spinestalk->AI()->DoAction(ACTION_START_FROSTWYRM);
                    }
                    break;
                case NPC_RIMEFANG:
                case NPC_SPINESTALKER:
                    {
                        if (GetData(DATA_HAS_LIMITED_ATTEMPTS) && !HeroicAttempts)
                            return;
                        if (GetBossState(DATA_SINDRAGOSA) == DONE)
                            return;
                        FrostwyrmGUIDs.erase(creature->GetSpawnId());
                        if (FrostwyrmGUIDs.empty())
{
                            instance->LoadGrid(SindragosaSpawnPos.GetPositionX(), SindragosaSpawnPos.GetPositionY());
                            if (Creature* boss = instance->SummonCreature(NPC_SINDRAGOSA, SindragosaSpawnPos))
                                boss->AI()->DoAction(ACTION_START_FROSTWYRM);
                        }
                        break;
                    }
                case NPC_DEATHSPEAKER_SERVANT:
                    if (Creature* c = unit->SummonCreature(WORLD_TRIGGER, *unit, TEMPSUMMON_TIMED_DESPAWN, 10000))
                    {
                        c->CastSpell(c, VOID_ZONE_VISUAL, true);
                        unit->SummonCreature(NPC_RISEN_DEATHSPEAKER_SERVANT, *unit, TEMPSUMMON_MANUAL_DESPAWN);
                        unit->ToCreature()->DespawnOrUnsummon(3000);
                    }
                    break;
                default:
                    break;
            }
        }
References ACTION_START_FROSTWYRM, ACTION_VRYKUL_DEATH, EventProcessor::AddEvent(), Creature::AI(), EventProcessor::CalculateTime(), CrokScourgebaneGUID, DATA_HAS_LIMITED_ATTEMPTS, DATA_SINDRAGOSA, DATA_SPINESTALKER, Creature::DespawnOrUnsummon(), DONE, FrostwyrmGUIDs, InstanceScript::GetBossState(), Map::GetCreature(), GetData(), UnitAI::GetData(), Object::GetEntry(), Position::GetExactDist2d(), Object::GetGUID(), Creature::GetLootRecipient(), WorldObject::GetName(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Creature::GetSpawnId(), WorldObject::GetTransport(), HeroicAttempts, InstanceScript::instance, Map::LoadGrid(), WorldObject::m_Events, NPC_DEATHSPEAKER_SERVANT, NPC_FROSTWING_WHELP, NPC_RIMEFANG, NPC_RISEN_DEATHSPEAKER_SERVANT, NPC_SINDRAGOSA, NPC_SPINESTALKER, NPC_YMIRJAR_BATTLE_MAIDEN, NPC_YMIRJAR_DEATHBRINGER, NPC_YMIRJAR_FROSTBINDER, NPC_YMIRJAR_HUNTRESS, NPC_YMIRJAR_WARLORD, RimefangGUID, RimefangTrash, SindragosaSpawnPos, SpinestalkerGUID, SpinestalkerTrash, Map::SummonCreature(), WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, Object::ToCreature(), VOID_ZONE_VISUAL, and WORLD_TRIGGER.
ProcessEvent()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent (WorldObject * source, uint32 eventId) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (eventId)
            {
                case EVENT_ENEMY_GUNSHIP_DESPAWN:
                    if (GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) == DONE)
                    {
                        if (GameObject* go = source->ToGameObject())
                            if (MotionTransport* transport = go->ToMotionTransport())
                                transport->UnloadNonStaticPassengers();
                        source->AddObjectToRemoveList();
                    }
                    break;
                case EVENT_ENEMY_GUNSHIP_COMBAT:
                    if (Creature* captain = source->FindNearestCreature(TeamIdInInstance == TEAM_HORDE ? NPC_IGB_HIGH_OVERLORD_SAURFANG : NPC_IGB_MURADIN_BRONZEBEARD, 200.0f))
                    {
                        captain->AI()->DoAction(ACTION_ENEMY_GUNSHIP_TALK);
                    }
                    [[fallthrough]];
                case EVENT_PLAYERS_GUNSHIP_SPAWN:
                case EVENT_PLAYERS_GUNSHIP_COMBAT:
                    if (GameObject* go = source->ToGameObject())
                        if (MotionTransport* transport = go->ToMotionTransport())
                            transport->EnableMovement(false);
                    break;
                case EVENT_PLAYERS_GUNSHIP_SAURFANG:
                    if (GameObject* go = source->ToGameObject())
                        if (MotionTransport* transport = go->ToMotionTransport())
{
                            transport->setActive(false);
                            transport->EnableMovement(false);
                            //After movement is stopped remove the backpack
                            RemoveBackPack();
                        }
                    if (Creature* captain = source->FindNearestCreature(TeamIdInInstance == TEAM_HORDE ? NPC_IGB_HIGH_OVERLORD_SAURFANG : NPC_IGB_MURADIN_BRONZEBEARD, 200.0f))
                        captain->AI()->DoAction(ACTION_EXIT_SHIP);
                    break;
                case EVENT_QUAKE:
                    if (GameObject* warning = instance->GetGameObject(FrozenThroneWarningGUID))
                        warning->SetGoState(GO_STATE_ACTIVE);
                    Events.ScheduleEvent(EVENT_QUAKE_SHATTER, 5s);
                    break;
                case EVENT_SECOND_REMORSELESS_WINTER:
                    if (GameObject* platform = instance->GetGameObject(ArthasPlatformGUID))
                    {
                        platform->SetDestructibleState(GO_DESTRUCTIBLE_DESTROYED);
                        Events.ScheduleEvent(EVENT_REBUILD_PLATFORM, 1500ms);
                    }
                    break;
                case EVENT_TELEPORT_TO_FROSMOURNE: // Harvest Soul (normal mode)
                    if (Creature* terenas = instance->SummonCreature(NPC_TERENAS_MENETHIL_FROSTMOURNE, TerenasSpawn, nullptr, 65000))
                    {
                        terenas->AI()->DoAction(ACTION_FROSTMOURNE_INTRO);
                        std::list<Creature*> triggers;
                        GetCreatureListWithEntryInGrid(triggers, terenas, NPC_WORLD_TRIGGER_INFINITE_AOI, 100.0f);
                        if (!triggers.empty())
{
                            triggers.sort(Acore::ObjectDistanceOrderPred(terenas, false));
                            Unit* visual = triggers.front();
                            visual->CastSpell(visual, SPELL_FROSTMOURNE_TELEPORT_VISUAL, true);
                        }
                        if (Creature* warden = instance->SummonCreature(NPC_SPIRIT_WARDEN, SpiritWardenSpawn, nullptr, 65000))
{
                            terenas->AI()->AttackStart(warden);
                            warden->AddThreat(terenas, 300000.0f);
                        }
                    }
                    break;
                case EVENT_FESTERGUT_VALVE_USED:
                    if (!(PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE))
                    {
                        if (GameObject* goGas = instance->GetGameObject(GasReleaseValveGUID))
                            goGas->SetGameObjectFlag(GO_FLAG_INTERACT_COND | GO_FLAG_NOT_SELECTABLE);
                        PutricideEventProgress |= PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE;
                        if (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE)
{
                            HandleGameObject(PutricideCollisionGUID, true);
                            for (uint8 i = 0; i < 2; ++i)
                                if (GameObject* go = instance->GetGameObject(PutricideGateGUIDs[i]))
                                    go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
                        }
                        else
                            HandleGameObject(PutricideGateGUIDs[0], false);
                        HandleGameObject(PutricidePipeGUIDs[0], true);
                        SaveToDB();
                    }
                    break;
                case EVENT_ROTFACE_VALVE_USED:
                    if (!(PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE))
                    {
                        if (GameObject* goOoze = instance->GetGameObject(OozeReleaseValveGUID))
                            goOoze->SetGameObjectFlag(GO_FLAG_INTERACT_COND | GO_FLAG_NOT_SELECTABLE);
                        PutricideEventProgress |= PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE;
                        if (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE)
{
                            HandleGameObject(PutricideCollisionGUID, true);
                            for (uint8 i = 0; i < 2; ++i)
                                if (GameObject* go = instance->GetGameObject(PutricideGateGUIDs[i]))
                                    go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
                        }
                        else
                            HandleGameObject(PutricideGateGUIDs[1], false);
                        HandleGameObject(PutricidePipeGUIDs[1], true);
                        SaveToDB();
                    }
                    break;
            }
        }
References ACTION_ENEMY_GUNSHIP_TALK, ACTION_EXIT_SHIP, ACTION_FROSTMOURNE_INTRO, WorldObject::AddObjectToRemoveList(), Unit::CastSpell(), DATA_ICECROWN_GUNSHIP_BATTLE, DONE, EVENT_ENEMY_GUNSHIP_COMBAT, EVENT_ENEMY_GUNSHIP_DESPAWN, EVENT_FESTERGUT_VALVE_USED, EVENT_PLAYERS_GUNSHIP_COMBAT, EVENT_PLAYERS_GUNSHIP_SAURFANG, EVENT_PLAYERS_GUNSHIP_SPAWN, EVENT_QUAKE, EVENT_QUAKE_SHATTER, EVENT_REBUILD_PLATFORM, EVENT_ROTFACE_VALVE_USED, EVENT_SECOND_REMORSELESS_WINTER, EVENT_TELEPORT_TO_FROSMOURNE, WorldObject::FindNearestCreature(), GetCreatureListWithEntryInGrid(), GO_DESTRUCTIBLE_DESTROYED, GO_FLAG_INTERACT_COND, GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, NPC_IGB_HIGH_OVERLORD_SAURFANG, NPC_IGB_MURADIN_BRONZEBEARD, NPC_SPIRIT_WARDEN, NPC_TERENAS_MENETHIL_FROSTMOURNE, NPC_WORLD_TRIGGER_INFINITE_AOI, PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE, PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE, SPELL_FROSTMOURNE_TELEPORT_VISUAL, SpiritWardenSpawn, WorldObject::SummonCreature(), TEAM_HORDE, TerenasSpawn, Object::ToGameObject(), and GameObject::ToMotionTransport().
ReadSaveDataMore()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> HeroicAttempts;
            uint32 temp = 0;
            data >> temp;
            if (temp == IN_PROGRESS)
            {
                ColdflameJetsState = NOT_STARTED;
            }
            else
            {
                ColdflameJetsState = temp ? DONE : NOT_STARTED;
            }
            data >> BloodQuickeningState;
            data >> BloodQuickeningMinutes;
            if (BloodQuickeningState == IN_PROGRESS)
            {
                Events.ScheduleEvent(EVENT_UPDATE_EXECUTION_TIME, 1min);
                DoUpdateWorldState(WORLDSTATE_SHOW_TIMER, 1);
                DoUpdateWorldState(WORLDSTATE_EXECUTION_TIME, BloodQuickeningMinutes);
            }
            data >> WeeklyQuestId10;
            data >> PutricideEventProgress;
            PutricideEventProgress &= ~PUTRICIDE_EVENT_FLAG_TRAP_INPROGRESS;
            data >> LichKingHeroicAvailable;
            data >> BloodPrinceTrashCount;
            data >> IsBuffAvailable;
            data >> IsSindragosaIntroDone;
            SetData(DATA_BUFF_AVAILABLE, IsBuffAvailable);
        }
References DATA_BUFF_AVAILABLE, DONE, EVENT_UPDATE_EXECUTION_TIME, IN_PROGRESS, NOT_STARTED, WORLDSTATE_EXECUTION_TIME, and WORLDSTATE_SHOW_TIMER.
RemoveBackPack()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::RemoveBackPack () inline
        {
            for (auto const& itr : instance->GetPlayers())
                if (Player* _player = itr.GetSource())
                    _player->DestroyItemCount(ITEM_GOBLIN_ROCKET_PACK, _player->GetItemCount(ITEM_GOBLIN_ROCKET_PACK), true);
        }
References Map::GetPlayers(), InstanceScript::instance, and ITEM_GOBLIN_ROCKET_PACK.
SetBossState()
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            switch (type)
            {
                case DATA_LORD_MARROWGAR:
                    if (state == DONE)
                    {
                        WeeklyQuestId10 = RAND(QUEST_BLOOD_QUICKENING_10, QUEST_RESIDUE_RENDEZVOUS_10, QUEST_RESPITE_FOR_A_TORMENTED_SOUL_10, QUEST_DEPROGRAMMING_10, QUEST_SECURING_THE_RAMPARTS_10);
                        SetData(DATA_WEEKLY_QUEST_ID, 0); // show required hidden npcs
                        if (GameObject* transporter = instance->GetGameObject(ScourgeTransporterFirstGUID))
                            transporter->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                        SaveToDB();
                    }
                    break;
                case DATA_LADY_DEATHWHISPER:
                    if (state == DONE)
                        SpawnGunship();
                    break;
                case DATA_ICECROWN_GUNSHIP_BATTLE:
                    if (state == DONE)
                    {
                        if (GameObject* loot = instance->GetGameObject(GunshipArmoryGUID))
{
                            loot->SetLootRecipient(instance);
                            loot->RemoveGameObjectFlag(GO_FLAG_LOCKED | GO_FLAG_NOT_SELECTABLE | GO_FLAG_NODESPAWN);
                        }
                    }
                    else if (state == FAIL)
                        Events.ScheduleEvent(EVENT_RESPAWN_GUNSHIP, 30s);
                    break;
                case DATA_DEATHBRINGER_SAURFANG:
                    switch (state)
                    {
                        case DONE:
                            if (GameObject* loot = instance->GetGameObject(DeathbringersCacheGUID))
{
                                if (Creature* deathbringer = instance->GetCreature(DeathbringerSaurfangGUID))
                                    loot->SetLootRecipient(deathbringer);
                                loot->RemoveGameObjectFlag(GO_FLAG_LOCKED | GO_FLAG_NOT_SELECTABLE | GO_FLAG_NODESPAWN);
                            }
                            [[fallthrough]];
                        case NOT_STARTED:
                            if (GameObject* teleporter = instance->GetGameObject(SaurfangTeleportGUID))
{
                                HandleGameObject(SaurfangTeleportGUID, true, teleporter);
                                teleporter->RemoveGameObjectFlag(GO_FLAG_IN_USE);
                            }
                            break;
                        default:
                            break;
                    }
                    break;
                case DATA_FESTERGUT:
                    if (state == DONE)
                    {
                        if (GameObject* go = instance->GetGameObject(GasReleaseValveGUID))
                            go->RemoveGameObjectFlag(GO_FLAG_INTERACT_COND | GO_FLAG_NOT_SELECTABLE);
                        if (GetBossState(DATA_ROTFACE) == DONE)
                            HandleDropAttempt(false);
                    }
                    break;
                case DATA_ROTFACE:
                    if (state == DONE)
                    {
                        if (GameObject* go = instance->GetGameObject(OozeReleaseValveGUID))
                            go->RemoveGameObjectFlag(GO_FLAG_INTERACT_COND | GO_FLAG_NOT_SELECTABLE);
                        if (GetBossState(DATA_FESTERGUT) == DONE)
                            HandleDropAttempt(false);
                    }
                    break;
                case DATA_PROFESSOR_PUTRICIDE:
                    HandleGameObject(PutricideEnteranceDoorGUID, (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_TRAP_FINISHED) && state != IN_PROGRESS);
                    HandleGameObject(PlagueSigilGUID, state != DONE);
                    if (state == DONE)
                        CheckLichKingAvailability();
                    else if (state == FAIL)
                        HandleDropAttempt();
                    if (state == DONE && !instance->IsHeroic() && LichKingHeroicAvailable)
                    {
                        LichKingHeroicAvailable = false;
                        SaveToDB();
                    }
                    break;
                case DATA_BLOOD_QUEEN_LANA_THEL:
                    HandleGameObject(BloodwingSigilGUID, state != DONE);
                    if (state == DONE)
                        CheckLichKingAvailability();
                    else if (state == FAIL)
                        HandleDropAttempt();
                    if (state == DONE && !instance->IsHeroic() && LichKingHeroicAvailable)
                    {
                        LichKingHeroicAvailable = false;
                        SaveToDB();
                    }
                    break;
                case DATA_VALITHRIA_DREAMWALKER:
                    if (state == DONE)
                        SetData(DATA_WEEKLY_QUEST_ID, GetData(DATA_WEEKLY_QUEST_ID)); // will show weekly quest npc if necessary
                    break;
                case DATA_SINDRAGOSA:
                    HandleGameObject(FrostwingSigilGUID, state != DONE);
                    if (state == DONE)
                        CheckLichKingAvailability();
                    else if (state == FAIL)
                    {
                        IsSindragosaIntroDone = true;
                        HandleDropAttempt();
                        if (instance->IsHeroic())
{
                            if (HeroicAttempts)
{
                                Events.ScheduleEvent(EVENT_RESPAWN_SINDRAGOSA, 30s);
                            }
                        }
                        else
{
                            Events.ScheduleEvent(EVENT_RESPAWN_SINDRAGOSA, 30s);
                        }
                    }
                    if (state == DONE && !instance->IsHeroic() && LichKingHeroicAvailable)
                    {
                        LichKingHeroicAvailable = false;
                        SaveToDB();
                    }
                    break;
                case DATA_THE_LICH_KING:
                    {
                        // dramatically increase visibility range during fight to seeing frostmourne room
                        instance->SetVisibilityRange(state == IN_PROGRESS ? 500.0f : 200.0f);
                        if (state == FAIL)
{
                            Events.CancelEvent(EVENT_QUAKE_SHATTER);
                            Events.CancelEvent(EVENT_REBUILD_PLATFORM);
                            HandleDropAttempt();
                        }
                        if (state == DONE)
{
                            if (GameObject* bolvar = instance->GetGameObject(FrozenBolvarGUID))
                                bolvar->SetRespawnTime(7 * DAY);
                            if (GameObject* pillars = instance->GetGameObject(PillarsChainedGUID))
                                pillars->SetRespawnTime(7 * DAY);
                            if (GameObject* pillars = instance->GetGameObject(PillarsUnchainedGUID))
                                pillars->SetRespawnTime(7 * DAY);
                            instance->LoadGrid(JainaSpawnPos.GetPositionX(), JainaSpawnPos.GetPositionY());
                            instance->SummonCreature(NPC_LADY_JAINA_PROUDMOORE_QUEST, JainaSpawnPos);
                            instance->SummonCreature(NPC_MURADIN_BRONZEBEARD_QUEST, MuradinSpawnPos);
                            instance->SummonCreature(NPC_UTHER_THE_LIGHTBRINGER_QUEST, UtherSpawnPos);
                            instance->SummonCreature(NPC_LADY_SYLVANAS_WINDRUNNER_QUEST, SylvanasSpawnPos);
                        }
                        break;
                    }
                default:
                    break;
            }
            return true;
        }
References BloodwingSigilGUID, CheckLichKingAvailability(), DATA_BLOOD_QUEEN_LANA_THEL, DATA_DEATHBRINGER_SAURFANG, DATA_FESTERGUT, DATA_ICECROWN_GUNSHIP_BATTLE, DATA_LADY_DEATHWHISPER, DATA_LORD_MARROWGAR, DATA_PROFESSOR_PUTRICIDE, DATA_ROTFACE, DATA_SINDRAGOSA, DATA_THE_LICH_KING, DATA_VALITHRIA_DREAMWALKER, DATA_WEEKLY_QUEST_ID, DAY, DeathbringerSaurfangGUID, DeathbringersCacheGUID, DONE, EVENT_QUAKE_SHATTER, EVENT_REBUILD_PLATFORM, EVENT_RESPAWN_GUNSHIP, EVENT_RESPAWN_SINDRAGOSA, FAIL, FrostwingSigilGUID, FrozenBolvarGUID, GasReleaseValveGUID, InstanceScript::GetBossState(), Map::GetCreature(), GetData(), Map::GetGameObject(), Position::GetPositionX(), Position::GetPositionY(), GO_FLAG_IN_USE, GO_FLAG_INTERACT_COND, GO_FLAG_LOCKED, GO_FLAG_NODESPAWN, GO_FLAG_NOT_SELECTABLE, GunshipArmoryGUID, HandleDropAttempt(), InstanceScript::HandleGameObject(), HeroicAttempts, IN_PROGRESS, InstanceScript::instance, Map::IsHeroic(), IsSindragosaIntroDone, JainaSpawnPos, LichKingHeroicAvailable, Map::LoadGrid(), MuradinSpawnPos, NOT_STARTED, NPC_LADY_JAINA_PROUDMOORE_QUEST, NPC_LADY_SYLVANAS_WINDRUNNER_QUEST, NPC_MURADIN_BRONZEBEARD_QUEST, NPC_UTHER_THE_LIGHTBRINGER_QUEST, OozeReleaseValveGUID, PillarsChainedGUID, PillarsUnchainedGUID, PlagueSigilGUID, PUTRICIDE_EVENT_FLAG_TRAP_FINISHED, PutricideEnteranceDoorGUID, PutricideEventProgress, QUEST_BLOOD_QUICKENING_10, QUEST_DEPROGRAMMING_10, QUEST_RESIDUE_RENDEZVOUS_10, QUEST_RESPITE_FOR_A_TORMENTED_SOUL_10, QUEST_SECURING_THE_RAMPARTS_10, RAND(), SaurfangTeleportGUID, InstanceScript::SaveToDB(), ScourgeTransporterFirstGUID, InstanceScript::SetBossState(), SetData(), Map::SetVisibilityRange(), SpawnGunship(), Map::SummonCreature(), SylvanasSpawnPos, UtherSpawnPos, and WeeklyQuestId10.
Referenced by SetData(), and SpawnGunship().
SetData()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_BUFF_AVAILABLE:
                    IsBuffAvailable = !!data;
                    if (!IsBuffAvailable)
                    {
                        instance->DoForAllPlayers([&](Player* player)
{
                            player->UpdateAreaDependentAuras(player->GetAreaId());
                            for (Unit::ControlSet::const_iterator itr = player->m_Controlled.begin(); itr != player->m_Controlled.end(); ++itr)
{
                                Unit::AuraMap& am = (*itr)->GetOwnedAuras();
                                for (Unit::AuraMap::iterator itra = am.begin(); itra != am.end();)
                                    switch (itra->second->GetId())
{
                                        // Hellscream's Warsong
                                        case 73816:
                                        case 73818:
                                        case 73819:
                                        case 73820:
                                        case 73821:
                                        case 73822:
                                            // Strength of Wrynn
                                        case 73762:
                                        case 73824:
                                        case 73825:
                                        case 73826:
                                        case 73827:
                                        case 73828:
                                            (*itr)->RemoveOwnedAura(itra);
                                            break;
                                        default:
                                            ++itra;
                                            break;
                                    }
                            }
                        });
                    }
                    SaveToDB();
                    break;
                case DATA_WEEKLY_QUEST_ID:
                    for (uint8 i = 0; i < WeeklyNPCs; ++i)
                        if (WeeklyQuestData[i].questId[0] == WeeklyQuestId10 && (WeeklyQuestData[i].creatureEntry != NPC_VALITHRIA_DREAMWALKER_QUEST || GetBossState(DATA_VALITHRIA_DREAMWALKER) == DONE) /*appears after killing valithria*/)
                            if (WeeklyQuestNpcGUID[i])
                                if (Creature* c = instance->GetCreature(WeeklyQuestNpcGUID[i]))
                                    c->SetVisible(true);
                    break;
                case DATA_PUTRICIDE_TRAP_STATE:
                    if (data == NOT_STARTED)
                    {
                        PutricideEventProgress &= ~PUTRICIDE_EVENT_FLAG_TRAP_INPROGRESS;
                        HandleGameObject(PutricideCollisionGUID, ((PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE) && (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE)));
                        if ((PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE) && (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE))
{
                            for (uint8 i = 0; i < 2; ++i)
                                if (GameObject* go = instance->GetGameObject(PutricideGateGUIDs[i]))
                                    go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
                        }
                        else
{
                            HandleGameObject(PutricideGateGUIDs[0], !(PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE));
                            HandleGameObject(PutricideGateGUIDs[1], !(PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE));
                        }
                        SaveToDB();
                    }
                    else if (data == IN_PROGRESS)
                    {
                        PutricideEventProgress |= PUTRICIDE_EVENT_FLAG_TRAP_INPROGRESS;
                        HandleGameObject(PutricideCollisionGUID, false);
                        HandleGameObject(PutricideGateGUIDs[0], false);
                        HandleGameObject(PutricideGateGUIDs[1], false);
                        SaveToDB();
                    }
                    else if (data == DONE)
                    {
                        PutricideEventProgress &= ~PUTRICIDE_EVENT_FLAG_TRAP_INPROGRESS;
                        PutricideEventProgress |= PUTRICIDE_EVENT_FLAG_TRAP_FINISHED;
                        HandleGameObject(PutricideEnteranceDoorGUID, true);
                        HandleGameObject(PutricideCollisionGUID, ((PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE) && (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE)));
                        if ((PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE) && (PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE))
{
                            for (uint8 i = 0; i < 2; ++i)
                                if (GameObject* go = instance->GetGameObject(PutricideGateGUIDs[i]))
                                    go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
                        }
                        else
{
                            HandleGameObject(PutricideGateGUIDs[0], !(PutricideEventProgress & PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE));
                            HandleGameObject(PutricideGateGUIDs[1], !(PutricideEventProgress & PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE));
                        }
                        SaveToDB();
                    }
                    return;
                case DATA_BONED_ACHIEVEMENT:
                    IsBonedEligible = !!data;
                    break;
                case DATA_OOZE_DANCE_ACHIEVEMENT:
                    IsOozeDanceEligible = !!data;
                    break;
                case DATA_NAUSEA_ACHIEVEMENT:
                    IsNauseaEligible = !!data;
                    break;
                case DATA_ORB_WHISPERER_ACHIEVEMENT:
                    IsOrbWhispererEligible = !!data;
                    break;
                case DATA_SINDRAGOSA_FROSTWYRMS:
                    FrostwyrmGUIDs.insert(data);
                    break;
                case DATA_SPINESTALKER:
                    SpinestalkerTrash.insert(data);
                    break;
                case DATA_RIMEFANG:
                    RimefangTrash.insert(data);
                    break;
                case DATA_COLDFLAME_JETS:
                    ColdflameJetsState = data;
                    if (ColdflameJetsState == DONE)
                        SaveToDB();
                    break;
                case DATA_BLOOD_QUICKENING_STATE:
                    {
                        if (data == IN_PROGRESS && BloodQuickeningState != NOT_STARTED)
                            break;
                        if (BloodQuickeningState == data)
                            break;
                        if (WeeklyQuestId10 != QUEST_BLOOD_QUICKENING_10)
                            break;
                        switch (data)
{
                            case IN_PROGRESS:
                                Events.ScheduleEvent(EVENT_UPDATE_EXECUTION_TIME, 1min);
                                BloodQuickeningMinutes = 30;
                                DoUpdateWorldState(WORLDSTATE_SHOW_TIMER, 1);
                                DoUpdateWorldState(WORLDSTATE_EXECUTION_TIME, BloodQuickeningMinutes);
                                break;
                            case DONE:
                                Events.CancelEvent(EVENT_UPDATE_EXECUTION_TIME);
                                BloodQuickeningMinutes = 0;
                                DoUpdateWorldState(WORLDSTATE_SHOW_TIMER, 0);
                                break;
                            default:
                                break;
                        }
                        BloodQuickeningState = data;
                        SaveToDB();
                        break;
                    }
                case DATA_BPC_TRASH_DIED:
                    {
                        if (++BloodPrinceTrashCount >= 4)
{
                            SetBossState(DATA_BLOOD_PRINCE_TRASH, NOT_STARTED);
                            SetBossState(DATA_BLOOD_PRINCE_TRASH, DONE);
                        }
                        SaveToDB();
                        break;
                    }
                default:
                    break;
            }
        }
References BloodPrinceTrashCount, BloodQuickeningMinutes, BloodQuickeningState, ColdflameJetsState, DATA_BLOOD_PRINCE_TRASH, DATA_BLOOD_QUICKENING_STATE, DATA_BONED_ACHIEVEMENT, DATA_BPC_TRASH_DIED, DATA_BUFF_AVAILABLE, DATA_COLDFLAME_JETS, DATA_NAUSEA_ACHIEVEMENT, DATA_OOZE_DANCE_ACHIEVEMENT, DATA_ORB_WHISPERER_ACHIEVEMENT, DATA_PUTRICIDE_TRAP_STATE, DATA_RIMEFANG, DATA_SINDRAGOSA_FROSTWYRMS, DATA_SPINESTALKER, DATA_VALITHRIA_DREAMWALKER, DATA_WEEKLY_QUEST_ID, Map::DoForAllPlayers(), DONE, InstanceScript::DoUpdateWorldState(), EVENT_UPDATE_EXECUTION_TIME, FrostwyrmGUIDs, WorldObject::GetAreaId(), InstanceScript::GetBossState(), Map::GetCreature(), Map::GetGameObject(), GO_STATE_ACTIVE_ALTERNATIVE, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, IsBonedEligible, IsBuffAvailable, IsNauseaEligible, IsOozeDanceEligible, IsOrbWhispererEligible, Unit::m_Controlled, NOT_STARTED, NPC_VALITHRIA_DREAMWALKER_QUEST, PUTRICIDE_EVENT_FLAG_FESTERGUT_VALVE, PUTRICIDE_EVENT_FLAG_ROTFACE_VALVE, PUTRICIDE_EVENT_FLAG_TRAP_FINISHED, PUTRICIDE_EVENT_FLAG_TRAP_INPROGRESS, PutricideCollisionGUID, PutricideEnteranceDoorGUID, PutricideEventProgress, PutricideGateGUIDs, QUEST_BLOOD_QUICKENING_10, RimefangTrash, InstanceScript::SaveToDB(), SetBossState(), SpinestalkerTrash, Player::UpdateAreaDependentAuras(), WeeklyNPCs, WeeklyQuestData, WeeklyQuestId10, WeeklyQuestNpcGUID, WORLDSTATE_EXECUTION_TIME, and WORLDSTATE_SHOW_TIMER.
Referenced by SetBossState().
SetPositionTraps()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetPositionTraps (GameObject * go) inline
        {
            std::vector<Position> trapPositions;
            switch (go->GetEntry())
            {
                case GO_SPIRIT_ALARM_1:
                    trapPositions = GoSpiritAlarm_1;
                    break;
                case GO_SPIRIT_ALARM_2:
                    trapPositions = GoSpiritAlarm_2;
                    break;
                case GO_SPIRIT_ALARM_3:
                    trapPositions = GoSpiritAlarm_3;
                    break;
                case GO_SPIRIT_ALARM_4:
                    trapPositions = GoSpiritAlarm_4;
                    break;
                default:
                    return;
            }
            go->Relocate(Acore::Containers::SelectRandomContainerElement(trapPositions));
        }
References Object::GetEntry(), GO_SPIRIT_ALARM_1, GO_SPIRIT_ALARM_2, GO_SPIRIT_ALARM_3, GO_SPIRIT_ALARM_4, GoSpiritAlarm_1, GoSpiritAlarm_2, GoSpiritAlarm_3, GoSpiritAlarm_4, Position::Relocate(), and Acore::Containers::SelectRandomContainerElement().
Referenced by OnGameObjectCreate().
SpawnGunship()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SpawnGunship () inline
        {
            if (!GunshipGUID && instance->HavePlayers())
            {
                SetBossState(DATA_ICECROWN_GUNSHIP_BATTLE, NOT_STARTED);
                uint32 gunshipEntry = TeamIdInInstance == TEAM_HORDE ? GO_ORGRIMS_HAMMER_H : GO_THE_SKYBREAKER_A;
                if (MotionTransport* gunship = sTransportMgr->CreateTransport(gunshipEntry, 0, instance))
                {
                    GunshipGUID = gunship->GetGUID();
                    gunship->setActive(false);
                }
            }
        }
References DATA_ICECROWN_GUNSHIP_BATTLE, GO_ORGRIMS_HAMMER_H, GO_THE_SKYBREAKER_A, GunshipGUID, Map::HavePlayers(), InstanceScript::instance, NOT_STARTED, SetBossState(), sTransportMgr, TEAM_HORDE, and TeamIdInInstance.
Referenced by OnPlayerEnter(), and SetBossState().
Update()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            // Xinef: A Feast of Souls (24547) whispers
            if (LichKingRandomWhisperTimer <= diff)
            {
                LichKingRandomWhisperTimer = urand(100, 300) * IN_MILLISECONDS;
                Map::PlayerList const& players = instance->GetPlayers();
                if (!players.IsEmpty())
                    if (Player* player = players.begin()->GetSource())
                        if (player->GetQuestStatus(QUEST_A_FEAST_OF_SOULS) == QUEST_STATUS_INCOMPLETE)
{
                            if (Creature* theLichKing = instance->GetCreature(TheLichKingLhGUID))
{
                                theLichKing->AI()->Talk(SAY_SOULS_LICH_KING_RAND_WHISPER, player);
                            }
                        }
            }
            else
                LichKingRandomWhisperTimer -= diff;
            if (DarkwhisperElevatorTimer <= diff)
            {
                DarkwhisperElevatorTimer = 3000;
                if (GetBossState(DATA_LADY_DEATHWHISPER) == DONE)
                    if (GameObject* elevator = instance->GetGameObject(LadyDeathwisperElevatorGUID))
                        if (StaticTransport* trans = elevator->ToStaticTransport())
{
                            if (trans->GetGoState() == GO_STATE_READY && trans->GetPathProgress() == 0)
                                trans->SetGoState(GO_STATE_ACTIVE);
                            else if (trans->GetGoState() == GO_STATE_ACTIVE && trans->GetPathProgress() == trans->GetPauseTime())
                                trans->SetGoState(GO_STATE_READY);
                        }
            }
            else
                DarkwhisperElevatorTimer -= diff;
            if (Events.Empty())
                return;
            Events.Update(diff);
            while (uint32 eventId = Events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_UPDATE_EXECUTION_TIME:
{
                            --BloodQuickeningMinutes;
                            if (BloodQuickeningMinutes)
{
                                Events.ScheduleEvent(EVENT_UPDATE_EXECUTION_TIME, 1min);
                                DoUpdateWorldState(WORLDSTATE_SHOW_TIMER, 1);
                                DoUpdateWorldState(WORLDSTATE_EXECUTION_TIME, BloodQuickeningMinutes);
                            }
                            else
{
                                BloodQuickeningState = DONE;
                                DoUpdateWorldState(WORLDSTATE_SHOW_TIMER, 0);
                                if (Creature* bq = instance->GetCreature(BloodQueenLanaThelGUID))
                                    bq->AI()->DoAction(ACTION_KILL_MINCHAR);
                            }
                            SaveToDB();
                            break;
                        }
                    case EVENT_QUAKE_SHATTER:
{
                            if (GameObject* platform = instance->GetGameObject(ArthasPlatformGUID))
                                platform->SetDestructibleState(GO_DESTRUCTIBLE_DAMAGED);
                            if (GameObject* edge = instance->GetGameObject(FrozenThroneEdgeGUID))
                                edge->SetGoState(GO_STATE_ACTIVE);
                            if (GameObject* wind = instance->GetGameObject(FrozenThroneWindGUID))
                                wind->SetGoState(GO_STATE_READY);
                            if (GameObject* warning = instance->GetGameObject(FrozenThroneWarningGUID))
                                warning->SetGoState(GO_STATE_READY);
                            if (Creature* theLichKing = instance->GetCreature(TheLichKingGUID))
                                theLichKing->AI()->DoAction(ACTION_RESTORE_LIGHT);
                            break;
                        }
                    case EVENT_REBUILD_PLATFORM:
                        if (GameObject* platform = instance->GetGameObject(ArthasPlatformGUID))
                            platform->SetDestructibleState(GO_DESTRUCTIBLE_REBUILDING, nullptr, true);
                        if (GameObject* edge = instance->GetGameObject(FrozenThroneEdgeGUID))
                            edge->SetGoState(GO_STATE_READY);
                        if (GameObject* wind = instance->GetGameObject(FrozenThroneWindGUID))
                            wind->SetGoState(GO_STATE_ACTIVE);
                        break;
                    case EVENT_RESPAWN_GUNSHIP:
                        SpawnGunship();
                        break;
                    case EVENT_RESPAWN_SINDRAGOSA:
                        if (!GetCreature(DATA_SINDRAGOSA))
{
                            if (Creature* sindragosa = instance->SummonCreature(NPC_SINDRAGOSA, SindragosaSpawnPos))
{
                                sindragosa->setActive(true);
                                sindragosa->SetDisableGravity(true);
                                sindragosa->GetMotionMaster()->MovePath(NPC_SINDRAGOSA * 10, true);
                                if (TempSummon* summon = sindragosa->ToTempSummon())
{
                                    summon->SetTempSummonType(TEMPSUMMON_DEAD_DESPAWN);
                                }
                            }
                        }
                        // Could happen more than once if more than one player enters before she respawns.
                        Events.CancelEvent(EVENT_RESPAWN_SINDRAGOSA);
                        break;
                    default:
                        break;
                }
            }
        }
References ACTION_KILL_MINCHAR, ACTION_RESTORE_LIGHT, MapRefMgr::begin(), DATA_LADY_DEATHWHISPER, DATA_SINDRAGOSA, DONE, EVENT_QUAKE_SHATTER, EVENT_REBUILD_PLATFORM, EVENT_RESPAWN_GUNSHIP, EVENT_RESPAWN_SINDRAGOSA, EVENT_UPDATE_EXECUTION_TIME, Reference< TO, FROM >::GetSource(), GO_DESTRUCTIBLE_DAMAGED, GO_DESTRUCTIBLE_REBUILDING, GO_STATE_ACTIVE, GO_STATE_READY, IN_MILLISECONDS, LinkedListHead::IsEmpty(), NPC_SINDRAGOSA, QUEST_A_FEAST_OF_SOULS, QUEST_STATUS_INCOMPLETE, SAY_SOULS_LICH_KING_RAND_WHISPER, SindragosaSpawnPos, WorldObject::SummonCreature(), TEMPSUMMON_DEAD_DESPAWN, GameObject::ToStaticTransport(), Unit::ToTempSummon(), urand(), WORLDSTATE_EXECUTION_TIME, and WORLDSTATE_SHOW_TIMER.
WriteSaveDataMore()
void instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << HeroicAttempts << ' '
                << ColdflameJetsState << ' '
                << BloodQuickeningState << ' '
                << BloodQuickeningMinutes << ' '
                << WeeklyQuestId10 << ' '
                << PutricideEventProgress << ' '
                << uint32(LichKingHeroicAvailable ? 1 : 0) << ' '
                << BloodPrinceTrashCount << ' '
                << uint32(IsBuffAvailable ? 1 : 0) << ' '
                << uint32(IsSindragosaIntroDone ? 1 : 0);
        }
Member Data Documentation
ArthasPlatformGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ArthasPlatformGUID protected
Referenced by GetGuidData(), and OnGameObjectCreate().
ArthasPrecipiceGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ArthasPrecipiceGUID protected
Referenced by OnGameObjectCreate().
BloodCouncilControllerGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::BloodCouncilControllerGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
BloodCouncilGUIDs
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::BloodCouncilGUIDs[3] protected
Referenced by GetGuidData(), and OnCreatureCreate().
BloodPrinceTrashCount
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::BloodPrinceTrashCount protected
Referenced by instance_icecrown_citadel_InstanceMapScript(), and SetData().
BloodQueenLanaThelGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::BloodQueenLanaThelGUID protected
Referenced by GetGuidData(), HandleDropAttempt(), and OnCreatureCreate().
BloodQuickeningMinutes
uint16 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::BloodQuickeningMinutes protected
Referenced by FillInitialWorldStates(), instance_icecrown_citadel_InstanceMapScript(), and SetData().
BloodQuickeningState
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::BloodQuickeningState protected
Referenced by FillInitialWorldStates(), GetData(), instance_icecrown_citadel_InstanceMapScript(), OnCreatureCreate(), and SetData().
BloodwingSigilGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::BloodwingSigilGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
ColdflameJetsState
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ColdflameJetsState protected
Referenced by GetData(), instance_icecrown_citadel_InstanceMapScript(), and SetData().
CrokCaptainGUIDs
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CrokCaptainGUIDs[4] protected
Referenced by GetGuidData(), and OnCreatureCreate().
CrokScourgebaneGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CrokScourgebaneGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), and OnUnitDeath().
DarkwhisperElevatorTimer
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::DarkwhisperElevatorTimer protected
Referenced by instance_icecrown_citadel_InstanceMapScript().
DeathbringerSaurfangDoorGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::DeathbringerSaurfangDoorGUID protected
Referenced by GetGuidData(), and OnGameObjectCreate().
DeathbringerSaurfangEventGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::DeathbringerSaurfangEventGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
DeathbringerSaurfangGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::DeathbringerSaurfangGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), and SetBossState().
DeathbringersCacheGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::DeathbringersCacheGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
EnemyGunshipGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::EnemyGunshipGUID protected
Referenced by GetGuidData(), and OnGameObjectCreate().
Events
EventMap instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Events protected
FestergutGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::FestergutGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
FrostwingSigilGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::FrostwingSigilGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
FrostwyrmGUIDs
std::set<ObjectGuid::LowType> instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::FrostwyrmGUIDs protected
Referenced by GetData(), OnUnitDeath(), and SetData().
FrozenBolvarGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::FrozenBolvarGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
FrozenThroneEdgeGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::FrozenThroneEdgeGUID protected
Referenced by OnGameObjectCreate().
FrozenThroneWarningGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::FrozenThroneWarningGUID protected
Referenced by OnGameObjectCreate().
FrozenThroneWindGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::FrozenThroneWindGUID protected
Referenced by OnGameObjectCreate().
GasReleaseValveGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GasReleaseValveGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
GunshipArmoryGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GunshipArmoryGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
GunshipGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GunshipGUID protected
Referenced by GetGuidData(), OnGameObjectRemove(), and SpawnGunship().
HeroicAttempts
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::HeroicAttempts protected
Referenced by FillInitialWorldStates(), GetData(), HandleDropAttempt(), instance_icecrown_citadel_InstanceMapScript(), OnCreatureCreate(), OnUnitDeath(), and SetBossState().
HighlordTirionFordringGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::HighlordTirionFordringGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
IsBonedEligible
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::IsBonedEligible protected
Referenced by instance_icecrown_citadel_InstanceMapScript(), and SetData().
IsBuffAvailable
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::IsBuffAvailable protected
Referenced by GetData(), instance_icecrown_citadel_InstanceMapScript(), OnPlayerEnter(), and SetData().
IsNauseaEligible
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::IsNauseaEligible protected
Referenced by instance_icecrown_citadel_InstanceMapScript(), and SetData().
IsOozeDanceEligible
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::IsOozeDanceEligible protected
Referenced by instance_icecrown_citadel_InstanceMapScript(), and SetData().
IsOrbWhispererEligible
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::IsOrbWhispererEligible protected
Referenced by instance_icecrown_citadel_InstanceMapScript(), and SetData().
IsSindragosaIntroDone
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::IsSindragosaIntroDone protected
Referenced by GetData(), instance_icecrown_citadel_InstanceMapScript(), OnPlayerEnter(), and SetBossState().
LadyDeathwhisperGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::LadyDeathwhisperGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
LadyDeathwisperElevatorGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::LadyDeathwisperElevatorGUID protected
Referenced by OnGameObjectCreate().
LichKingHeroicAvailable
bool instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::LichKingHeroicAvailable protected
Referenced by GetData(), instance_icecrown_citadel_InstanceMapScript(), and SetBossState().
LichKingRandomWhisperTimer
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::LichKingRandomWhisperTimer protected
Referenced by instance_icecrown_citadel_InstanceMapScript().
OozeReleaseValveGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OozeReleaseValveGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
PillarsChainedGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::PillarsChainedGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
PillarsUnchainedGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::PillarsUnchainedGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
PlagueSigilGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::PlagueSigilGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
ProfessorPutricideGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProfessorPutricideGUID protected
Referenced by GetGuidData(), HandleDropAttempt(), and OnCreatureCreate().
PutricadeTrapGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::PutricadeTrapGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
PutricideCollisionGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::PutricideCollisionGUID protected
Referenced by OnGameObjectCreate(), and SetData().
PutricideEnteranceDoorGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::PutricideEnteranceDoorGUID protected
Referenced by OnGameObjectCreate(), SetBossState(), and SetData().
PutricideEventProgress
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::PutricideEventProgress protected
Referenced by GetData(), instance_icecrown_citadel_InstanceMapScript(), OnGameObjectCreate(), SetBossState(), and SetData().
PutricideGateGUIDs
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::PutricideGateGUIDs[2] protected
Referenced by OnGameObjectCreate(), and SetData().
PutricidePipeGUIDs
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::PutricidePipeGUIDs[2] protected
Referenced by OnGameObjectCreate().
PutricideTableGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::PutricideTableGUID protected
Referenced by GetGuidData(), and OnGameObjectCreate().
RimefangGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::RimefangGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), and OnUnitDeath().
RimefangTrash
std::set<ObjectGuid::LowType> instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::RimefangTrash protected
Referenced by GetData(), OnUnitDeath(), and SetData().
RotfaceGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::RotfaceGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
SaurfangTeleportGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SaurfangTeleportGUID protected
Referenced by GetGuidData(), OnGameObjectCreate(), and SetBossState().
ScourgeTransporterFirstGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ScourgeTransporterFirstGUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
SindragosaGauntletGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SindragosaGauntletGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
SindragosaGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SindragosaGUID protected
Referenced by GetGuidData(), HandleDropAttempt(), OnCreatureCreate(), and OnCreatureRemove().
SisterSvalnaGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SisterSvalnaGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
SpinestalkerGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SpinestalkerGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), and OnUnitDeath().
SpinestalkerTrash
std::set<ObjectGuid::LowType> instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SpinestalkerTrash protected
Referenced by GetData(), OnUnitDeath(), and SetData().
TeamIdInInstance
TeamId instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::TeamIdInInstance protected
Referenced by GetCreatureEntry(), GetData(), GetGameObjectEntry(), instance_icecrown_citadel_InstanceMapScript(), OnCreatureCreate(), OnGameObjectCreate(), OnPlayerEnter(), and SpawnGunship().
TerenasMenethilGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::TerenasMenethilGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
TheLichKingGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::TheLichKingGUID protected
Referenced by GetGuidData(), HandleDropAttempt(), and OnCreatureCreate().
TheLichKingLhGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::TheLichKingLhGUID protected
Referenced by OnCreatureCreate().
TheLichKingTeleportGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::TheLichKingTeleportGUID protected
Referenced by OnGameObjectCreate().
ValithriaDreamwalkerGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ValithriaDreamwalkerGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), and OnGameObjectCreate().
ValithriaLichKingGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ValithriaLichKingGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
ValithriaTriggerGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ValithriaTriggerGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
WeeklyQuestId10
uint32 instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::WeeklyQuestId10 protected
Referenced by GetData(), instance_icecrown_citadel_InstanceMapScript(), OnCreatureCreate(), SetBossState(), and SetData().
WeeklyQuestNpcGUID
ObjectGuid instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::WeeklyQuestNpcGUID[WeeklyNPCs] protected
Referenced by OnCreatureCreate(), and SetData().