AzerothCore: anonymous_namespace{Errors.cpp} Namespace Reference
anonymous_namespace{Errors.cpp} Namespace Reference
Functions
MakeMessage
Make message for display erros
Parameters
messageType Message type (ASSERTION FAILED, FATAL ERROR, ERROR) end etc
file Path to file
line Line number in file
function Functionn name
message Condition to string format
fmtMessage [optional] Display format message after condition
debugInfo [optional] Display debug info
std::string MakeMessage (std::string_view messageType, std::string_view file, uint32 line, std::string_view function, std::string_view message, std::string_view fmtMessage={}, std::string_view debugInfo={})
MakeAbortMessage
Make message for display erros
Parameters
file Path to file
line Line number in file
function Functionn name
fmtMessage [optional] Display format message after condition
std::string MakeAbortMessage (std::string_view file, uint32 line, std::string_view function, std::string_view fmtMessage={})
Function Documentation
MakeAbortMessage()
std::string anonymous_namespace{Errors.cpp}::MakeAbortMessage (std::string_view file, uint32 line, std::string_view function, std::string_view fmtMessage = {}) inline
                                                                                                                             {})
    {
        std::string msg = Acore::StringFormat("\n>> ABORTED\n\n# Location '{}:{}'\n# Function '{}'\n", file, line, function);
        if (!fmtMessage.empty())
        {
            msg.append(Acore::StringFormat("# Message '{}'\n", fmtMessage));
        }
        return Acore::StringFormat(
            "\n#{0:-^{2}}#\n"
            " {1: ^{2}} \n"
            "#{0:-^{2}}#\n", "", msg, 70);
    }
Referenced by Acore::Abort().
MakeMessage()
std::string anonymous_namespace{Errors.cpp}::MakeMessage (std::string_view messageType, std::string_view file, uint32 line, std::string_view function, std::string_view message, std::string_view fmtMessage = {}, std::string_view debugInfo = {}) inline
                                                            {}, std::string_view debugInfo = {})
    {
        std::string msg = Acore::StringFormat("\n>> {}\n\n# Location: {}:{}\n# Function: {}\n# Condition: {}\n", messageType, file, line, function, message);
        if (!fmtMessage.empty())
        {
            msg.append(Acore::StringFormat("# Message: {}\n", fmtMessage));
        }
        if (!debugInfo.empty())
        {
            msg.append(Acore::StringFormat("\n# Debug info: {}\n", debugInfo));
        }
        return Acore::StringFormat(
            "#{0:-^{2}}#\n"
            " {1: ^{2}} \n"
            "#{0:-^{2}}#\n", "", msg, 70);
    }
Referenced by Acore::Assert(), Acore::Error(), Acore::Fatal(), and Acore::Warning().