AzerothCore: SACActivateEvent Class Reference
SACActivateEvent Class Reference
Public Member Functions
SACActivateEvent (Creature *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _owner
Detailed Description
Constructor & Destructor Documentation
SACActivateEvent()
SACActivateEvent::SACActivateEvent (Creature * owner) inline
: _owner(owner) {}
Member Function Documentation
Execute()
bool SACActivateEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        if (!_owner->IsAlive())
            return true;
        _owner->GetMotionMaster()->MoveRandom(5.0f);
        _owner->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        _owner->SetReactState(REACT_AGGRESSIVE);
        _owner->CastSpell(_owner, SPELL_SAC_GHOUL_AREA_AURA, true);
        return true;
    }
References _owner, Unit::CastSpell(), Unit::GetMotionMaster(), Unit::IsAlive(), MotionMaster::MoveRandom(), REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Creature::SetReactState(), SPELL_SAC_GHOUL_AREA_AURA, and UNIT_FLAG_NOT_SELECTABLE.
Member Data Documentation
_owner
Creature* SACActivateEvent::_owner private
Referenced by Execute().