AzerothCore: UnboundPlagueTargetSelector Class Reference
UnboundPlagueTargetSelector Class Reference
Public Member Functions
UnboundPlagueTargetSelector (Creature *source)
bool operator() (WorldObject *object) const
Private Attributes
Creature const * _source
Detailed Description
Constructor & Destructor Documentation
UnboundPlagueTargetSelector()
UnboundPlagueTargetSelector::UnboundPlagueTargetSelector (Creature * source) inline
: _source(source) { }
Member Function Documentation
operator()()
bool UnboundPlagueTargetSelector::operator() (WorldObject * object) const inline
    {
        if (!object)
            return false;
        if (Player* p = object->ToPlayer())
        {
            if (p == _source->GetVictim() || p->GetExactDist(_source) >= 45.0f)
                return false;
            return true;
        }
        return false;
    }
References _source, Position::GetExactDist(), Unit::GetVictim(), and Object::ToPlayer().
Member Data Documentation
_source
Creature const* UnboundPlagueTargetSelector::_source private
Referenced by operator()().