AzerothCore: Acore::BattlegroundChatBuilder Class Reference
Acore::BattlegroundChatBuilder Class Reference
Public Member Functions
BattlegroundChatBuilder (ChatMsg msgtype, uint32 textId, Player const *source, va_list *args=nullptr)
void operator() (WorldPacket &data, LocaleConstant loc_idx)
Private Member Functions
void do_helper (WorldPacket &data, char const *text)
Private Attributes
ChatMsg _msgtype
uint32 _textId
Player const * _source
va_list * _args
Detailed Description
Constructor & Destructor Documentation
BattlegroundChatBuilder()
Acore::BattlegroundChatBuilder::BattlegroundChatBuilder (ChatMsg msgtype, uint32 textId, Player const * source, va_list * args = nullptr) inline
            : _msgtype(msgtype), _textId(textId), _source(source), _args(args) { }
Member Function Documentation
do_helper()
void Acore::BattlegroundChatBuilder::do_helper (WorldPacket & data, char const * text) inline private
        {
            ChatHandler::BuildChatPacket(data, _msgtype, LANG_UNIVERSAL, _source, _source, text);
        }
References _msgtype, _source, ChatHandler::BuildChatPacket(), and LANG_UNIVERSAL.
Referenced by operator()().
operator()()
void Acore::BattlegroundChatBuilder::operator() (WorldPacket & data, LocaleConstant loc_idx) inline
        {
            char const* text = sObjectMgr->GetAcoreString(_textId, loc_idx);
            if (_args)
            {
                // we need copy va_list before use or original va_list will corrupted
                va_list ap;
                va_copy(ap, *_args);
                char str[2048];
                vsnprintf(str, 2048, text, ap);
                va_end(ap);
                do_helper(data, &str[0]);
            }
            else
                do_helper(data, text);
        }
References _args, _textId, do_helper(), and sObjectMgr.
Member Data Documentation
_args
va_list* Acore::BattlegroundChatBuilder::_args private
Referenced by operator()().
_msgtype
ChatMsg Acore::BattlegroundChatBuilder::_msgtype private
Referenced by do_helper().
_source
Player const* Acore::BattlegroundChatBuilder::_source private
Referenced by do_helper().
_textId
uint32 Acore::BattlegroundChatBuilder::_textId private
Referenced by operator()().