AzerothCore: npc_nelson::npc_nelsonAI Struct Reference
npc_nelson::npc_nelsonAI Struct Reference
Public Member Functions
npc_nelsonAI (Creature *creature)
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *, Unit *killer) override
void Reset () override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void SpellHit (Unit *, SpellInfo const *Spell) override
void DoAction (int32 action) override
Public Member Functions inherited from NPCStaveQuestAI
NPCStaveQuestAI (Creature *creature)
uint32 GetFormEntry (std::string)
bool InNormalForm ()
void RevealForm ()
void StorePlayerGUID ()
Player * GetGossipPlayer ()
bool IsAllowedEntry (uint32)
bool UnitIsUnfair (Unit *unit)
bool IsFairFight ()
bool ValidThreatlist ()
void SetHomePosition ()
void PrepareForEncounter ()
void ClearLootIfUnfair (Unit *killer)
bool PlayerEligibleForReward (Unit *killer)
void StoreAttackerGuidValue (Unit *attacker)
bool QuestIncomplete (Unit *unit, uint32 questItem)
void ResetState (uint32)
void EvadeOnFeignDeath ()
virtual void AttackStart (Unit *)
virtual void AttackedBy (Unit *)
virtual void JustDied (Unit *)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
bool shouldDespawn
Public Attributes inherited from NPCStaveQuestAI
ObjectGuid gossipPlayerGUID
ObjectGuid playerGUID
bool encounterStarted
ThreatContainer::StorageType const & threatList = me->GetThreatMgr().GetThreatList()
std::map< int, int > entryKeys
std::map< int, std::map< std::string, int > > entryList
std::vector< uint64 > attackerGuids
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_nelsonAI()
npc_nelson::npc_nelsonAI::npc_nelsonAI (Creature * creature) inline
: NPCStaveQuestAI(creature) { }
Member Function Documentation
DoAction()
void npc_nelson::npc_nelsonAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == EVENT_ENCOUNTER_START)
            {
                PrepareForEncounter();
                events.ScheduleEvent(EVENT_ENCOUNTER_START, 5000);
            }
        }
References EVENT_ENCOUNTER_START, and NPCStaveQuestAI::PrepareForEncounter().
JustEngagedWith()
void npc_nelson::npc_nelsonAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            RevealForm();
            me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            if (InNormalForm())
            {
                return;
            }
            if (encounterStarted)
            {
                me->CastSpell(me, NELSON_SPELL_SOUL_FLAME, true);
            }
            if (who && (UnitIsUnfair(who) || !QuestIncomplete(who, NELSON_HEAD)))
            {
                me->CastSpell(who, SPELL_FOOLS_PLIGHT, true);
            }
            events.ScheduleEvent(EVENT_FOOLS_PLIGHT, urand(2000, 3000));
            events.ScheduleEvent(EVENT_RANGE_CHECK, 1000);
            events.ScheduleEvent(EVENT_UNFAIR_FIGHT, 1000);
            events.ScheduleEvent(NELSON_EVENT_DREADFUL_FRIGHT, 10000);
            events.ScheduleEvent(NELSON_EVENT_CREEPING_DOOM, 5000);
        }
References Unit::CastSpell(), NPCStaveQuestAI::encounterStarted, EVENT_FOOLS_PLIGHT, EVENT_RANGE_CHECK, EVENT_UNFAIR_FIGHT, NPCStaveQuestAI::InNormalForm(), ScriptedAI::me, NELSON_EVENT_CREEPING_DOOM, NELSON_EVENT_DREADFUL_FRIGHT, NELSON_HEAD, NELSON_SPELL_SOUL_FLAME, NPCStaveQuestAI::QuestIncomplete(), Unit::RemoveNpcFlag(), NPCStaveQuestAI::RevealForm(), SPELL_FOOLS_PLIGHT, UNIT_NPC_FLAG_GOSSIP, NPCStaveQuestAI::UnitIsUnfair(), and urand().
JustSummoned()
void npc_nelson::npc_nelsonAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!summon)
            {
                return;
            }
            // Workaround for increasing the Summoned Guardian damage by using the template modifier value
            summon->Unit::UpdateDamagePhysical(BASE_ATTACK);
            if (me->IsInCombat())
            {
                summon->AI()->AttackStart(me->GetVictim());
            }
        }
References Creature::AI(), UnitAI::AttackStart(), BASE_ATTACK, Unit::GetVictim(), Unit::IsInCombat(), and ScriptedAI::me.
Reset()
void npc_nelson::npc_nelsonAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            ResetState(NELSON_SPELL_CRIPPLING_CLIP);
            shouldDespawn = false;
            events.Reset();
            me->RemoveAllMinionsByEntry(CREEPING_DOOM_ENTRY);
        }
References CREEPING_DOOM_ENTRY, ScriptedAI::me, NELSON_SPELL_CRIPPLING_CLIP, Unit::RemoveAllMinionsByEntry(), NPCStaveQuestAI::ResetState(), and shouldDespawn.
SpellHit()
void npc_nelson::npc_nelsonAI::SpellHit (Unit * , SpellInfo const * Spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (InNormalForm())
            {
                return;
            }
            if (me->HasAura(NELSON_SPELL_SOUL_FLAME) && me->HasAura(NELSON_WEAKNESS_FROST_TRAP))
            {
                me->RemoveAura(NELSON_SPELL_SOUL_FLAME);
            }
            if (!me->HasAura(NELSON_SPELL_CRIPPLING_CLIP) && Spell->Id == NELSON_WEAKNESS_WING_CLIP)
            {
                me->AddAura(NELSON_SPELL_CRIPPLING_CLIP, me);
                me->TextEmote(NELSON_WEAKNESS_EMOTE);
            }
        }
References Unit::AddAura(), Unit::HasAura(), NPCStaveQuestAI::InNormalForm(), ScriptedAI::me, NELSON_SPELL_CRIPPLING_CLIP, NELSON_SPELL_SOUL_FLAME, NELSON_WEAKNESS_EMOTE, NELSON_WEAKNESS_FROST_TRAP, NELSON_WEAKNESS_WING_CLIP, Unit::RemoveAura(), and Unit::TextEmote().
SummonedCreatureDies()
void npc_nelson::npc_nelsonAI::SummonedCreatureDies (Creature * , Unit * killer) inline override virtual
Reimplemented from CreatureAI.
        {
            // This should trigger the despawn event when a another player or unit
            // kills a creeping doom unit
            if (UnitIsUnfair(killer))
            {
                shouldDespawn = true;
            }
        }
References shouldDespawn, and NPCStaveQuestAI::UnitIsUnfair().
UpdateAI()
void npc_nelson::npc_nelsonAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            events.Update(diff);
            uint32 eventId = events.ExecuteEvent();
            // Out of combat events
            switch (eventId)
            {
                case EVENT_ENCOUNTER_START:
                    me->Say(NELSON_SAY);
                    me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    events.ScheduleEvent(EVENT_REVEAL, 5000);
                    break;
                case EVENT_REVEAL:
                    RevealForm();
                    break;
            }
            if (UpdateVictim())
            {
                // This should prevent hunters from staying in combat when feign death is used and there is a bystander with 0 threat
                EvadeOnFeignDeath();
            }
            else
            {
                return;
            }
            if (me->HasUnitState(UNIT_STATE_CASTING))
            {
                events.RepeatEvent(1000);
                return;
            }
            // In combat events
            switch (eventId)
            {
                case EVENT_FOOLS_PLIGHT:
                    if (UnitIsUnfair(me->GetVictim()) || !QuestIncomplete(me->GetVictim(), NELSON_HEAD))
                    {
                        me->CastSpell(me->GetVictim(), SPELL_FOOLS_PLIGHT, true);
                    }
                    events.RepeatEvent(urand(3000, 6000));
                    break;
                case EVENT_RANGE_CHECK:
                    if (!me->GetVictim()->IsWithinDist2d(me, 60.0f))
                    {
                        EnterEvadeMode();
                    }
                    else
                    {
                        events.RepeatEvent(2000);
                    }
                    break;
                case EVENT_UNFAIR_FIGHT:
                    if (!ValidThreatlist() || shouldDespawn)
                    {
                        SetHomePosition();
                        me->RemoveAllMinionsByEntry(CREEPING_DOOM_ENTRY);
                        me->SetUnitFlag(UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_ATTACKABLE_1);
                        me->SetImmuneToAll(true);
                        me->CombatStop(true);
                        me->Say(NELSON_DESPAWN_SAY);
                        me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                        me->DespawnOrUnsummon(5000);
                        break;
                    }
                    events.RepeatEvent(2000);
                    break;
                case NELSON_EVENT_DREADFUL_FRIGHT:
                    me->CastSpell(me->GetVictim(), NELSON_SPELL_DREADFUL_FRIGHT, false);
                    events.RepeatEvent(urand(12000, 19000));
                    break;
                case NELSON_EVENT_CREEPING_DOOM:
                    me->CastSpell(me->GetVictim(), NELSON_SPELL_CREEPING_DOOM, false);
                    events.RepeatEvent(urand(10000, 12000));
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::CastSpell(), Unit::CombatStop(), CREEPING_DOOM_ENTRY, Creature::DespawnOrUnsummon(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_TALK, CreatureAI::EnterEvadeMode(), NPCStaveQuestAI::EvadeOnFeignDeath(), EVENT_ENCOUNTER_START, EVENT_FOOLS_PLIGHT, EVENT_RANGE_CHECK, EVENT_REVEAL, EVENT_UNFAIR_FIGHT, Unit::GetVictim(), Unit::HandleEmoteCommand(), Unit::HasUnitState(), WorldObject::IsWithinDist2d(), ScriptedAI::me, NELSON_DESPAWN_SAY, NELSON_EVENT_CREEPING_DOOM, NELSON_EVENT_DREADFUL_FRIGHT, NELSON_HEAD, NELSON_SAY, NELSON_SPELL_CREEPING_DOOM, NELSON_SPELL_DREADFUL_FRIGHT, NPCStaveQuestAI::QuestIncomplete(), Unit::RemoveAllMinionsByEntry(), Unit::RemoveUnitFlag(), NPCStaveQuestAI::RevealForm(), Unit::Say(), NPCStaveQuestAI::SetHomePosition(), Unit::SetImmuneToAll(), Unit::SetUnitFlag(), shouldDespawn, SPELL_FOOLS_PLIGHT, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_ATTACKABLE_1, UNIT_STATE_CASTING, NPCStaveQuestAI::UnitIsUnfair(), CreatureAI::UpdateVictim(), urand(), and NPCStaveQuestAI::ValidThreatlist().
Member Data Documentation
events
EventMap npc_nelson::npc_nelsonAI::events
shouldDespawn
bool npc_nelson::npc_nelsonAI::shouldDespawn
Referenced by Reset(), SummonedCreatureDies(), and UpdateAI().