AzerothCore: instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript Struct Reference
instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript Struct Reference
Public Member Functions
instance_halls_of_reflection_InstanceMapScript (Map *pMap)
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 type) const override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
void OnUnitDeath (Unit *unit) override
void RandomizeCompositionsAndShow ()
void AddWave1 ()
void DoWipe1 ()
void Update (uint32 diff) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 EncounterMask
TeamId TeamIdInInstance
ObjectGuid NPC_FalricGUID
ObjectGuid NPC_MarwynGUID
ObjectGuid NPC_LichKingIntroGUID
ObjectGuid NPC_LeaderIntroGUID
ObjectGuid NPC_GuardGUID
ObjectGuid NPC_UtherGUID
ObjectGuid NPC_LichKingGUID
ObjectGuid NPC_LeaderGUID
ObjectGuid NPC_IceWallTargetGUID [4]
ObjectGuid NPC_AltarBunnyGUID
ObjectGuid NPC_QuelDelarGUID
ObjectGuid NPC_ShipCaptainGUID
ObjectGuid GO_FrostmourneGUID
ObjectGuid GO_FrostmourneAltarGUID
ObjectGuid GO_FrontDoorGUID
ObjectGuid GO_ArthasDoorGUID
ObjectGuid GO_CaveInGUID
ObjectGuid GO_DoorBeforeThroneGUID
ObjectGuid GO_DoorAfterThroneGUID
ObjectGuid GO_IceWallGUID
ObjectGuid NPC_TrashGUID [NUM_OF_TRASH]
bool TrashActive [NUM_OF_TRASH]
uint8 TrashCounter
uint32 chosenComposition [8][5]
uint8 WaveNumber
uint32 NextWaveTimer
uint16 CheckPlayersTimer
uint16 ResumeFirstEventTimer
uint8 ResumeFirstEventStep
bool bFinished5Waves
uint8 reqKillCount
bool IsDuringLKFight
uint32 BatteredHiltStatus
ObjectGuid NPC_FrostswornGeneralGUID
ObjectGuid NPC_SpiritualReflectionGUID [5]
uint32 outroTimer
uint8 outroStep
MotionTransport * T1
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_halls_of_reflection_InstanceMapScript()
instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::instance_halls_of_reflection_InstanceMapScript (Map * pMap) inline
                                                                  : InstanceScript(pMap)
        {
            SetHeaders(DataHeader);
        };
References DataHeader, and InstanceScript::SetHeaders().
Member Function Documentation
AddWave1()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::AddWave1 () inline
        {
            if (WaveNumber >= 10)
                return;
            ++WaveNumber;
            if (WaveNumber >= 6)
                bFinished5Waves = true;
            DoUpdateWorldState(WORLD_STATE_HOR_COUNTER, 1);
            DoUpdateWorldState(WORLD_STATE_HOR_WAVE_COUNT, WaveNumber);
            HandleGameObject(GO_FrontDoorGUID, false);
            // some of them could go back to spawn due to vanish, etc.
            // on activating next wave make those attack again
            for (uint8 i = 0; i < NUM_OF_TRASH; ++i)
                if (TrashActive[i])
                    if (Creature* c = instance->GetCreature(NPC_TrashGUID[i]))
                        if (c->IsAlive() && !c->IsInCombat())
                            c->AI()->DoAction(1);
            if (WaveNumber == 5 || WaveNumber == 10)
            {
                NextWaveTimer = 0;
                if (WaveNumber == 5)
                {
                    if (Creature* falric = instance->GetCreature(NPC_FalricGUID))
                    {
                        if (falric->IsAlive())
                            falric->AI()->DoAction(1);
                        else
                            NextWaveTimer = 1;
                    }
                }
                else
                {
                    if (Creature* marwyn = instance->GetCreature(NPC_MarwynGUID))
                        if (marwyn->IsAlive()) // should always be true, but just in case
                            marwyn->AI()->DoAction(1);
                }
            }
            else
            {
                NextWaveTimer = 150000;
                uint8 num_to_activate = 5;
                if (WaveNumber <= 2)
                    num_to_activate = 3;
                else if (WaveNumber <= 4)
                    num_to_activate = 4;
                reqKillCount += num_to_activate;
                for (uint8 i = 0; i < num_to_activate; ++i)
                {
                    uint32 entry = chosenComposition[WaveNumber - (WaveNumber > 5 ? 2 : 1)][i];
                    bool forward = !!urand(0, 1);
                    for (int8 j = (forward ? 0 : NUM_OF_TRASH - 1); (forward ? j<NUM_OF_TRASH : j >= 0); (forward ? ++j : --j))
                        if (!TrashActive[j])
                            if (Creature* c = instance->GetCreature(NPC_TrashGUID[j]))
                                if (c->GetEntry() == entry)
{
                                    TrashActive[j] = true;
                                    c->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                                    c->SetImmuneToAll(false);
                                    c->AI()->DoAction(1);
                                    break;
                                }
                }
            }
        }
References bFinished5Waves, chosenComposition, InstanceScript::DoUpdateWorldState(), Map::GetCreature(), GO_FrontDoorGUID, InstanceScript::HandleGameObject(), InstanceScript::instance, NextWaveTimer, NPC_FalricGUID, NPC_MarwynGUID, NPC_TrashGUID, NUM_OF_TRASH, reqKillCount, TrashActive, UNIT_FLAG_NOT_SELECTABLE, urand(), WaveNumber, WORLD_STATE_HOR_COUNTER, and WORLD_STATE_HOR_WAVE_COUNT.
Referenced by SetData(), and Update().
DoWipe1()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::DoWipe1 () inline
        {
            if (!WaveNumber)
                return;
            DoUpdateWorldState(WORLD_STATE_HOR_COUNTER, 0);
            DoUpdateWorldState(WORLD_STATE_HOR_WAVE_COUNT, 0);
            HandleGameObject(GO_FrontDoorGUID, true);
            TrashCounter = NUM_OF_TRASH;
            WaveNumber = 0;
            NextWaveTimer = 0;
            memset(&chosenComposition, 0, sizeof(chosenComposition));
            for (uint8 i = 0; i < NUM_OF_TRASH; ++i)
                if (TrashActive[i])
                    if (Creature* c = instance->GetCreature(NPC_TrashGUID[i]))
                    {
                        c->GetThreatMgr().ClearAllThreat();
                        c->CombatStop(true);
                        c->InterruptNonMeleeSpells(true);
                        c->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        c->SetImmuneToAll(true);
                        c->Respawn(true);
                        c->UpdatePosition(c->GetHomePosition(), true);
                        c->StopMovingOnCurrentPos();
                    }
            memset(&TrashActive, 0, sizeof(TrashActive));
            if (Creature* falric = instance->GetCreature(NPC_FalricGUID))
                falric->AI()->EnterEvadeMode();
            if (Creature* marwyn = instance->GetCreature(NPC_MarwynGUID))
                marwyn->AI()->EnterEvadeMode();
            ResumeFirstEventTimer = 5000;
            ResumeFirstEventStep = 2;
            reqKillCount = 0;
        }
References chosenComposition, InstanceScript::DoUpdateWorldState(), Map::GetCreature(), GO_FrontDoorGUID, InstanceScript::HandleGameObject(), InstanceScript::instance, NextWaveTimer, NPC_FalricGUID, NPC_MarwynGUID, NPC_TrashGUID, NUM_OF_TRASH, reqKillCount, ResumeFirstEventStep, ResumeFirstEventTimer, TrashActive, TrashCounter, UNIT_FLAG_NOT_SELECTABLE, WaveNumber, WORLD_STATE_HOR_COUNTER, and WORLD_STATE_HOR_WAVE_COUNT.
Referenced by SetData(), and Update().
GetData()
uint32 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_INTRO:
                case DATA_FALRIC:
                case DATA_MARWYN:
                case DATA_FROSTSWORN_GENERAL:
                case DATA_LK_INTRO:
                case DATA_LICH_KING:
                    return EncounterMask & (1 << type);
                case DATA_WAVE_NUMBER:
                    return (uint32)WaveNumber;
                case DATA_BATTERED_HILT:
                    return BatteredHiltStatus;
            }
            return 0;
        }
References BatteredHiltStatus, DATA_BATTERED_HILT, DATA_FALRIC, DATA_FROSTSWORN_GENERAL, DATA_INTRO, DATA_LICH_KING, DATA_LK_INTRO, DATA_MARWYN, DATA_WAVE_NUMBER, EncounterMask, and WaveNumber.
GetGuidData()
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case NPC_DARK_RANGER_LORALEN:
                    return NPC_GuardGUID;
                case NPC_LICH_KING_EVENT:
                    return NPC_LichKingIntroGUID;
                case NPC_UTHER:
                    return NPC_UtherGUID;
                case DATA_FALRIC:
                    return NPC_FalricGUID;
                case DATA_MARWYN:
                    return NPC_MarwynGUID;
                case NPC_LICH_KING_BOSS:
                    return NPC_LichKingGUID;
                case NPC_SYLVANAS_PART2:
                    return NPC_LeaderGUID;
                case NPC_ICE_WALL_TARGET:
                case NPC_ICE_WALL_TARGET+1:
                case NPC_ICE_WALL_TARGET+2:
                case NPC_ICE_WALL_TARGET+3:
                    return NPC_IceWallTargetGUID[type - NPC_ICE_WALL_TARGET];
                case GO_FROSTMOURNE:
                    return GO_FrostmourneGUID;
                case GO_ARTHAS_DOOR:
                    return GO_ArthasDoorGUID;
                case GO_FRONT_DOOR:
                    return GO_FrontDoorGUID;
            }
            return ObjectGuid::Empty;
        }
References DATA_FALRIC, DATA_MARWYN, ObjectGuid::Empty, GO_ARTHAS_DOOR, GO_ArthasDoorGUID, GO_FRONT_DOOR, GO_FrontDoorGUID, GO_FROSTMOURNE, GO_FrostmourneGUID, NPC_DARK_RANGER_LORALEN, NPC_FalricGUID, NPC_GuardGUID, NPC_ICE_WALL_TARGET, NPC_IceWallTargetGUID, NPC_LeaderGUID, NPC_LICH_KING_BOSS, NPC_LICH_KING_EVENT, NPC_LichKingGUID, NPC_LichKingIntroGUID, NPC_MarwynGUID, NPC_SYLVANAS_PART2, NPC_UTHER, and NPC_UtherGUID.
Initialize()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            EncounterMask = 0;
            TeamIdInInstance = TEAM_NEUTRAL;
            memset(&TrashActive, 0, sizeof(TrashActive));
            TrashCounter = 0;
            memset(&chosenComposition, 0, sizeof(chosenComposition));
            WaveNumber = 0;
            NextWaveTimer = 0;
            CheckPlayersTimer = 5000;
            ResumeFirstEventTimer = 0;
            ResumeFirstEventStep = 0;
            bFinished5Waves = false;
            reqKillCount = 0;
            IsDuringLKFight = false;
            BatteredHiltStatus = 0;
            outroTimer = 0;
            outroStep = 0;
            T1 = nullptr;
        }
References BatteredHiltStatus, bFinished5Waves, CheckPlayersTimer, chosenComposition, EncounterMask, IsDuringLKFight, NextWaveTimer, outroStep, outroTimer, reqKillCount, ResumeFirstEventStep, ResumeFirstEventTimer, T1, TEAM_NEUTRAL, TeamIdInInstance, TrashActive, TrashCounter, and WaveNumber.
IsEncounterInProgress()
bool instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            return (instance->HavePlayers() && WaveNumber)  || IsDuringLKFight; // during LK fight npcs are active and will unset this variable
        }
References Map::HavePlayers(), InstanceScript::instance, IsDuringLKFight, and WaveNumber.
OnCreatureCreate()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            if (TeamIdInInstance == TEAM_NEUTRAL)
            {
                Map::PlayerList const& players = instance->GetPlayers();
                if (!players.IsEmpty())
                    for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                        if (Player* p = itr->GetSource())
                            if (!p->IsGameMaster())
{
                                TeamIdInInstance = p->GetTeamId();
                                break;
                            }
            }
            switch (creature->GetEntry())
            {
                case NPC_SYLVANAS_PART1:
                    creature->SetVisible(false);
                    creature->SetSpeed(MOVE_RUN, 1.1);
                    NPC_LeaderIntroGUID = creature->GetGUID();
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_JAINA_PART1);
                    creature->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                    creature->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                    break;
                case NPC_DARK_RANGER_LORALEN:
                    creature->SetVisible(false);
                    NPC_GuardGUID = creature->GetGUID();
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_ARCHMAGE_KORELN);
                    break;
                case NPC_UTHER:
                    creature->SetVisible(false);
                    NPC_UtherGUID = creature->GetGUID();
                    creature->SetReactState(REACT_PASSIVE);
                    break;
                case NPC_LICH_KING_EVENT:
                    creature->SetVisible(false);
                    NPC_LichKingIntroGUID = creature->GetGUID();
                    creature->SetReactState(REACT_PASSIVE);
                    creature->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                    break;
                case NPC_FALRIC:
                    creature->SetVisible(false);
                    NPC_FalricGUID = creature->GetGUID();
                    creature->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                    break;
                case NPC_MARWYN:
                    creature->SetVisible(false);
                    NPC_MarwynGUID = creature->GetGUID();
                    creature->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                    break;
                case NPC_WAVE_MERCENARY:
                case NPC_WAVE_FOOTMAN:
                case NPC_WAVE_RIFLEMAN:
                case NPC_WAVE_PRIEST:
                case NPC_WAVE_MAGE:
                    if (TrashCounter < NUM_OF_TRASH)
                        NPC_TrashGUID[TrashCounter++] = creature->GetGUID();
                    if (!(EncounterMask & (1 << DATA_MARWYN)) && !creature->IsAlive())
                        creature->Respawn();
                    creature->SetVisible(false);
                    break;
                case NPC_FROSTSWORN_GENERAL:
                    if (!(EncounterMask & (1 << DATA_MARWYN)))
                    {
                        creature->SetVisible(false);
                        creature->SetReactState(REACT_PASSIVE);
                    }
                    NPC_FrostswornGeneralGUID = creature->GetGUID();
                    break;
                case NPC_SPIRITUAL_REFLECTION:
                    for (uint8 i = 0; i < 5; ++i)
                        if (!NPC_SpiritualReflectionGUID[i])
{
                            NPC_SpiritualReflectionGUID[i] = creature->GetGUID();
                            break;
                        }
                    creature->SetVisible(false);
                    break;
                case NPC_LICH_KING_BOSS:
                    if (!(EncounterMask & (1 << DATA_FROSTSWORN_GENERAL)))
                        creature->SetVisible(false);
                    if (!(EncounterMask & (1 << DATA_LK_INTRO)))
                    {
                        creature->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_ATTACK2HTIGHT); //the fight cannot be in the form of an emote, it is causing bugs
                        creature->CastSpell(creature, SPELL_SOUL_REAPER, true);
                    }
                    else if (!(EncounterMask & (1 << DATA_LICH_KING)))
                        creature->AddAura(TeamIdInInstance == TEAM_ALLIANCE ? SPELL_JAINA_ICE_PRISON : SPELL_SYLVANAS_DARK_BINDING, creature);
                    else
                        creature->SetVisible(false);
                    NPC_LichKingGUID = creature->GetGUID();
                    creature->SetHealth((creature->GetMaxHealth() * 3) / 4);
                    creature->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                    break;
                case NPC_SYLVANAS_PART2:
                    if (!creature->IsAlive())
                        creature->Respawn();
                    NPC_LeaderGUID = creature->GetGUID();
                    creature->SetWalk(false);
                    creature->SetSheath(SHEATH_STATE_MELEE);
                    if (TeamIdInInstance == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_JAINA_PART2);
                    creature->SetWalk(false);
                    creature->SetHealth(creature->GetMaxHealth() / 20);
                    if (!(EncounterMask & (1 << DATA_FROSTSWORN_GENERAL)))
                        creature->SetVisible(false);
                    if (!(EncounterMask & (1 << DATA_LK_INTRO)))
                    {
                        creature->SetSheath(SHEATH_STATE_MELEE);
                        creature->SetUInt32Value(UNIT_NPC_EMOTESTATE, TeamIdInInstance == TEAM_ALLIANCE ? EMOTE_ONESHOT_ATTACK2HTIGHT : EMOTE_ONESHOT_ATTACK1H); //the fight cannot be in the form of an emote, it is causing bugs.
                        creature->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                        creature->CastSpell(creature, TeamIdInInstance == TEAM_ALLIANCE ? SPELL_JAINA_ICE_BARRIER : SPELL_SYLVANAS_CLOAK_OF_DARKNESS, true);
                    }
                    else if (!(EncounterMask & (1 << DATA_LICH_KING)))
                    {
                        creature->RemoveNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
                        creature->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        creature->UpdatePosition(LeaderEscapePos, true);
                        creature->StopMovingOnCurrentPos();
                    }
                    else
                    {
                        instance->LoadGrid(PathWaypoints[PATH_WP_COUNT - 1].GetPositionX(), PathWaypoints[PATH_WP_COUNT - 1].GetPositionY());
                        creature->UpdatePosition(PathWaypoints[PATH_WP_COUNT - 1], true);
                        creature->StopMovingOnCurrentPos();
                    }
                    creature->SetSheath(SHEATH_STATE_MELEE);
                    creature->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                    break;
                case NPC_ICE_WALL_TARGET:
                    if (creature->GetPositionX() > 5525.0f)
                        NPC_IceWallTargetGUID[0] = creature->GetGUID();
                    else if (creature->GetPositionX() > 5475.0f)
                        NPC_IceWallTargetGUID[1] = creature->GetGUID();
                    else if (creature->GetPositionX() > 5400.0f)
                        NPC_IceWallTargetGUID[2] = creature->GetGUID();
                    else
                        NPC_IceWallTargetGUID[3] = creature->GetGUID();
                    break;
                case NPC_ALTAR_BUNNY:
                    NPC_AltarBunnyGUID = creature->GetGUID();
                    break;
                case NPC_QUEL_DELAR:
                    NPC_QuelDelarGUID = creature->GetGUID();
                    creature->SetReactState(REACT_PASSIVE);
                    break;
                case NPC_HIGH_CAPTAIN_JUSTIN_BARLETT:
                case NPC_SKY_REAVER_KORM_BLACKSKAR:
                    NPC_ShipCaptainGUID = creature->GetGUID();
                    break;
            }
        }
References Unit::AddAura(), Unit::AddUnitMovementFlag(), MapRefMgr::begin(), Unit::CastSpell(), DATA_FROSTSWORN_GENERAL, DATA_LICH_KING, DATA_LK_INTRO, DATA_MARWYN, EMOTE_ONESHOT_ATTACK1H, EMOTE_ONESHOT_ATTACK2HTIGHT, EncounterMask, MapRefMgr::end(), Object::GetEntry(), Object::GetGUID(), Unit::GetMaxHealth(), Map::GetPlayers(), Position::GetPositionX(), InstanceScript::instance, Unit::IsAlive(), LinkedListHead::IsEmpty(), LeaderEscapePos, Map::LoadGrid(), MOVE_RUN, MOVEMENTFLAG_WALKING, NPC_ALTAR_BUNNY, NPC_AltarBunnyGUID, NPC_ARCHMAGE_KORELN, NPC_DARK_RANGER_LORALEN, NPC_FALRIC, NPC_FalricGUID, NPC_FROSTSWORN_GENERAL, NPC_FrostswornGeneralGUID, NPC_GuardGUID, NPC_HIGH_CAPTAIN_JUSTIN_BARLETT, NPC_ICE_WALL_TARGET, NPC_IceWallTargetGUID, NPC_JAINA_PART1, NPC_JAINA_PART2, NPC_LeaderGUID, NPC_LeaderIntroGUID, NPC_LICH_KING_BOSS, NPC_LICH_KING_EVENT, NPC_LichKingGUID, NPC_LichKingIntroGUID, NPC_MARWYN, NPC_MarwynGUID, NPC_QUEL_DELAR, NPC_QuelDelarGUID, NPC_ShipCaptainGUID, NPC_SKY_REAVER_KORM_BLACKSKAR, NPC_SPIRITUAL_REFLECTION, NPC_SpiritualReflectionGUID, NPC_SYLVANAS_PART1, NPC_SYLVANAS_PART2, NPC_TrashGUID, NPC_UTHER, NPC_UtherGUID, NPC_WAVE_FOOTMAN, NPC_WAVE_MAGE, NPC_WAVE_MERCENARY, NPC_WAVE_PRIEST, NPC_WAVE_RIFLEMAN, NUM_OF_TRASH, PATH_WP_COUNT, PathWaypoints, REACT_PASSIVE, Unit::RemoveNpcFlag(), Unit::RemoveUnitMovementFlag(), Creature::Respawn(), Unit::SetHealth(), Unit::SetNpcFlag(), Creature::SetReactState(), Unit::SetSheath(), Unit::SetSpeed(), Unit::SetUInt32Value(), Unit::SetVisible(), Creature::SetWalk(), SHEATH_STATE_MELEE, SPELL_JAINA_ICE_BARRIER, SPELL_JAINA_ICE_PRISON, SPELL_SOUL_REAPER, SPELL_SYLVANAS_CLOAK_OF_DARKNESS, SPELL_SYLVANAS_DARK_BINDING, Unit::StopMovingOnCurrentPos(), TEAM_ALLIANCE, TEAM_NEUTRAL, TeamIdInInstance, TrashCounter, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, Creature::UpdateEntry(), and Unit::UpdatePosition().
OnGameObjectCreate()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_FROSTMOURNE:
                    GO_FrostmourneGUID = go->GetGUID();
                    HandleGameObject(ObjectGuid::Empty, false, go);
                    if (EncounterMask & (1 << DATA_INTRO))
                        go->SetPhaseMask(2, true);
                    break;
                case GO_FROSTMOURNE_ALTAR:
                    GO_FrostmourneAltarGUID = go->GetGUID();
                    break;
                case GO_FRONT_DOOR:
                    GO_FrontDoorGUID = go->GetGUID();
                    HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_ARTHAS_DOOR:
                    GO_ArthasDoorGUID = go->GetGUID();
                    HandleGameObject(ObjectGuid::Empty, (EncounterMask & (1 << DATA_MARWYN)), go);
                    break;
                case GO_CAVE_IN:
                    GO_CaveInGUID = go->GetGUID();
                    break;
                case GO_DOOR_BEFORE_THRONE:
                    GO_DoorBeforeThroneGUID = go->GetGUID();
                    break;
                case GO_DOOR_AFTER_THRONE:
                    GO_DoorAfterThroneGUID = go->GetGUID();
                    break;
                case GO_ICE_WALL:
                    GO_IceWallGUID = go->GetGUID();
                    break;
            }
        }
References DATA_INTRO, DATA_MARWYN, ObjectGuid::Empty, EncounterMask, Object::GetEntry(), Object::GetGUID(), GO_ARTHAS_DOOR, GO_ArthasDoorGUID, GO_CAVE_IN, GO_CaveInGUID, GO_DOOR_AFTER_THRONE, GO_DOOR_BEFORE_THRONE, GO_DoorAfterThroneGUID, GO_DoorBeforeThroneGUID, GO_FRONT_DOOR, GO_FrontDoorGUID, GO_FROSTMOURNE, GO_FROSTMOURNE_ALTAR, GO_FrostmourneAltarGUID, GO_FrostmourneGUID, GO_ICE_WALL, GO_IceWallGUID, InstanceScript::HandleGameObject(), and GameObject::SetPhaseMask().
OnUnitDeath()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            if (WaveNumber && reqKillCount)
                if (unit->GetEntry() == NPC_WAVE_MERCENARY || unit->GetEntry() == NPC_WAVE_FOOTMAN || unit->GetEntry() == NPC_WAVE_RIFLEMAN || unit->GetEntry() == NPC_WAVE_PRIEST || unit->GetEntry() == NPC_WAVE_MAGE)
                    if ((--reqKillCount) == 0 && WaveNumber % 5 && NextWaveTimer > 5000)
                        NextWaveTimer = 5000;
            if (unit->GetEntry() == NPC_QUEL_DELAR)
                if (Creature* c = instance->GetCreature(NPC_UtherGUID))
                {
                    c->SetStandState(UNIT_STAND_STATE_STAND);
                    c->SetWalk(false);
                    c->GetMotionMaster()->MovePoint(0, 5313.92f, 1989.36f, 707.70f);
                    c->m_Events.AddEvent(new UtherBatteredHiltEvent(*c, 9), c->m_Events.CalculateTime(7000));
                }
        }
References Map::GetCreature(), Object::GetEntry(), InstanceScript::instance, NextWaveTimer, NPC_QUEL_DELAR, NPC_UtherGUID, NPC_WAVE_FOOTMAN, NPC_WAVE_MAGE, NPC_WAVE_MERCENARY, NPC_WAVE_PRIEST, NPC_WAVE_RIFLEMAN, reqKillCount, UNIT_STAND_STATE_STAND, and WaveNumber.
RandomizeCompositionsAndShow()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::RandomizeCompositionsAndShow () inline
        {
            uint8 r1 = urand(0, 1), r2 = urand(2, 3);
            for (uint8 i = 0; i < 5; ++i)
            {
                chosenComposition[0][i] = allowedCompositions[r1][i];
                chosenComposition[1][i] = allowedCompositions[r1 == 0 ? 1 : 0][i];
                chosenComposition[2][i] = allowedCompositions[r2][i];
                chosenComposition[3][i] = allowedCompositions[r2 == 2 ? 3 : 2][i];
            }
            bool left[4] = {true, true, true, true};
            for (uint8 k = 4; k > 0; --k)
            {
                uint8 r = urand(0, k - 1);
                uint8 ur = 0;
                for (uint8 j = 0; j < 4; ++j)
                    if (left[j])
                    {
                        if (ur == r)
{
                            left[j] = false;
                            for (uint8 i = 0; i < 5; ++i)
                                chosenComposition[8 - k][i] = allowedCompositions[j + 4][i];
                            break;
                        }
                        ++ur;
                    }
            }
            if (bFinished5Waves)
            {
                for (; WaveNumber < 4; ++WaveNumber)
                {
                    uint8 num_to_activate;
                    if (WaveNumber <= 1)
                        num_to_activate = 3;
                    else
                        num_to_activate = 4;
                    for (uint8 i = 0; i < num_to_activate; ++i)
                    {
                        uint32 entry = chosenComposition[WaveNumber][i];
                        bool forward = !!urand(0, 1);
                        for (int8 j = (forward ? 0 : NUM_OF_TRASH - 1); (forward ? j<NUM_OF_TRASH : j >= 0); (forward ? ++j : --j))
                            if (!TrashActive[j])
                                if (Creature* c = instance->GetCreature(NPC_TrashGUID[j]))
                                    if (c->GetEntry() == entry)
{
                                        TrashActive[j] = true;
                                        Unit::Kill(c, c);
                                        break;
                                    }
                    }
                }
                WaveNumber = 5;
            }
            for (uint8 i = 0; i < NUM_OF_TRASH; ++i)
                if (!TrashActive[i])
                    if (Creature* c = instance->GetCreature(NPC_TrashGUID[i]))
                    {
                        c->SetVisible(true);
                        c->CastSpell(c, SPELL_WELL_OF_SOULS_VISUAL, false);
                    }
        }
References allowedCompositions, bFinished5Waves, chosenComposition, Map::GetCreature(), InstanceScript::instance, Unit::Kill(), NPC_TrashGUID, NUM_OF_TRASH, SPELL_WELL_OF_SOULS_VISUAL, TrashActive, urand(), and WaveNumber.
Referenced by SetData().
ReadSaveDataMore()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> EncounterMask;
            BatteredHiltStatus = (EncounterMask & (1 << DATA_BATTERED_HILT)) ? BHSF_FINISHED : BHSF_NONE;
        }
References BatteredHiltStatus, BHSF_FINISHED, BHSF_NONE, DATA_BATTERED_HILT, and EncounterMask.
SetData()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_INTRO:
                    EncounterMask |= (1 << DATA_INTRO);
                    AddWave1();
                    break;
                case ACTION_SHOW_TRASH:
                    RandomizeCompositionsAndShow();
                    break;
                case DATA_FALRIC:
                    if (WaveNumber)
                    {
                        if (data == NOT_STARTED)
                            DoWipe1();
                        else if (data == DONE)
{
                            NextWaveTimer = 60000;
                            EncounterMask |= (1 << DATA_FALRIC);
                        }
                    }
                    break;
                case DATA_MARWYN:
                    if (WaveNumber)
                    {
                        if (data == NOT_STARTED)
                            DoWipe1();
                        else if (data == DONE)
{
                            EncounterMask |= (1 << DATA_MARWYN);
                            HandleGameObject(GO_FrontDoorGUID, true);
                            HandleGameObject(GO_ArthasDoorGUID, true);
                            if (Creature* c = instance->GetCreature(NPC_FrostswornGeneralGUID))
{
                                c->SetVisible(true);
                                c->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                                c->SetReactState(REACT_AGGRESSIVE);
                            }
                            if (Creature* c = instance->GetCreature(NPC_FrostswornGeneralGUID))
{
                                c->HandleEmoteCommand(EMOTE_ONESHOT_EMERGE);
                            }
                            WaveNumber = 0;
                            DoUpdateWorldState(WORLD_STATE_HOR_COUNTER, 0);
                            // give quest
                            Map::PlayerList const& pl = instance->GetPlayers();
                            for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                                if (Player* p = itr->GetSource())
                                    p->CastSpell(p, p->GetTeamId() == TEAM_ALLIANCE ? SPELL_HOR_START_QUEST_ALLY : SPELL_HOR_START_QUEST_HORDE, true);
                        }
                    }
                    break;
                case DATA_FROSTSWORN_GENERAL:
                    EncounterMask |= (1 << DATA_FROSTSWORN_GENERAL);
                    if (data == DONE)
                    {
                        if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
                            c->SetVisible(true);
                        if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
                            c->SetVisible(true);
                    }
                    break;
                case ACTION_SPIRITUAL_REFLECTIONS_COPY:
                    {
                        uint8 i = 0;
                        Map::PlayerList const& pl = instance->GetPlayers();
                        for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                            if (Player* p = itr->GetSource())
                                if (p->IsAlive() && !p->IsGameMaster())
                                    if (Creature* c = instance->GetCreature(NPC_SpiritualReflectionGUID[i++]))
{
                                        if (!c->IsAlive())
                                            c->Respawn();
                                        c->SetCanFly(true);
                                        c->SetDisableGravity(true);
                                        c->SetVisible(true);
                                        Item* i;
                                        i = p->GetWeaponForAttack(BASE_ATTACK);
                                        c->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, i ? i->GetEntry() : 0);
                                        i = p->GetWeaponForAttack(OFF_ATTACK);
                                        c->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, i ? i->GetEntry() : 0);
                                        i = p->GetWeaponForAttack(RANGED_ATTACK);
                                        c->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 2, i ? i->GetEntry() : 0);
                                        p->CastSpell(c, SPELL_HOR_CLONE, true);
                                        p->CastSpell(c, SPELL_HOR_CLONE_NAME, true);
                                    }
                    }
                    break;
                case ACTION_SPIRITUAL_REFLECTIONS_ACTIVATE:
                    if (Creature* fg = instance->GetCreature(NPC_FrostswornGeneralGUID))
                        for (uint8 i = 0; i < 5; ++i)
                            if (Creature* c = instance->GetCreature(NPC_SpiritualReflectionGUID[i]))
                                if (c->IsVisible())
{
                                    c->SetInCombatWithZone();
                                    c->SetCanFly(false);
                                    c->SetDisableGravity(false);
                                    c->GetMotionMaster()->MoveJump(fg->GetPositionX(), fg->GetPositionY(), fg->GetPositionZ(), 20.0f, 10.0f);
                                }
                    break;
                case ACTION_SPIRITUAL_REFLECTIONS_HIDE:
                    for (uint8 i = 0; i < 5; ++i)
                        if (Creature* c = instance->GetCreature(NPC_SpiritualReflectionGUID[i]))
                            c->AI()->EnterEvadeMode();
                    break;
                case DATA_LK_INTRO:
                    EncounterMask |= (1 << DATA_LK_INTRO);
                    if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
                        c->AI()->DoAction(ACTION_START_INTRO);
                    break;
                case ACTION_START_LK_FIGHT:
                    IsDuringLKFight = true;
                    DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_RETREATING_TIMED_EVENT);
                    DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_RETREATING_TIMED_EVENT);
                    break;
                case ACTION_STOP_LK_FIGHT:
                    if (!IsDuringLKFight)
                    {
                        break;
                    }
                    instance->LoadGrid(LeaderEscapePos.GetPositionX(), LeaderEscapePos.GetPositionY());
                    if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
                    {
                        if (!c->IsAlive())
{
                            c->Respawn();
                            if (TeamIdInInstance == TEAM_ALLIANCE)
                                c->UpdateEntry(NPC_JAINA_PART2);
                        }
                        c->GetThreatMgr().ClearAllThreat();
                        c->CombatStop(true);
                        c->InterruptNonMeleeSpells(true);
                        c->GetMotionMaster()->Clear();
                        c->GetMotionMaster()->MoveIdle();
                        c->UpdatePosition(LeaderEscapePos, true);
                        c->StopMovingOnCurrentPos();
                        c->RemoveNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
                        c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        c->SetHealth(c->GetMaxHealth() / 20);
                        c->AI()->Reset();
                        c->setActive(false);
                        c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                        c->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                    }
                    if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
                    {
                        c->GetThreatMgr().ClearAllThreat();
                        c->CombatStop(true);
                        c->InterruptNonMeleeSpells(true);
                        c->GetMotionMaster()->Clear();
                        c->GetMotionMaster()->MoveIdle();
                        c->UpdatePosition(c->GetHomePosition(), true);
                        c->StopMovingOnCurrentPos();
                        c->RemoveAllAuras();
                        c->AddAura(TeamIdInInstance == TEAM_ALLIANCE ? SPELL_JAINA_ICE_PRISON : SPELL_SYLVANAS_DARK_BINDING, c);
                        c->AI()->Reset();
                        c->setActive(false);
                        c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                        c->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                        c->SetSpeed(MOVE_RUN, c->GetCreatureTemplate()->speed_run);
                    }
                    IsDuringLKFight = false;
                    outroTimer = 0;
                    outroStep = 0;
                    [[fallthrough]];
                case ACTION_DELETE_ICE_WALL:
                    HandleGameObject(GO_IceWallGUID, true);
                    GO_IceWallGUID.Clear();
                    break;
                case DATA_LICH_KING:
                    if (data == DONE)
                    {
                        instance->LoadGrid(PathWaypoints[0].GetPositionX(), PathWaypoints[0].GetPositionY());
                        EncounterMask |= (1 << DATA_LICH_KING);
                        if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
                            c->setActive(false);
                        if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
                            c->setActive(false);
                        IsDuringLKFight = false;
                        outroStep = 1;
                        outroTimer = 0;
                    }
                    break;
                case DATA_BATTERED_HILT:
                    {
                        if (EncounterMask & (1 << DATA_BATTERED_HILT))
                            return;
                        switch (data)
{
                            case 1: // talked to leader
                                EncounterMask |= (1 << DATA_BATTERED_HILT);
                                SaveToDB();
                                break;
                            case 2:
                                if (BatteredHiltStatus)
                                    break;
                                BatteredHiltStatus |= BHSF_STARTED;
                                if (Creature* c = instance->GetCreature(NPC_AltarBunnyGUID))
                                    c->CastSpell(c, 70720, true);
                                if (Creature* c = instance->GetCreature(NPC_UtherGUID))
                                    c->m_Events.AddEvent(new UtherBatteredHiltEvent(*c, 1), c->m_Events.CalculateTime(3000));
                                break;
                            case 3:
                                if ((BatteredHiltStatus & BHSF_STARTED) == 0 || (BatteredHiltStatus & BHSF_THROWN))
                                    break;
                                BatteredHiltStatus |= BHSF_THROWN;
                                if (Creature* c = instance->GetCreature(NPC_UtherGUID))
{
                                    c->m_Events.AddEvent(new UtherBatteredHiltEvent(*c, 3), c->m_Events.CalculateTime(5500));
                                }
                                break;
                            case 4:
                                if (Creature* c = instance->GetCreature(NPC_QuelDelarGUID))
{
                                    c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                    c->SetSpeed(MOVE_RUN, 2.5f);
                                }
                                break;
                            case 5:
                                if (Creature* c = instance->GetCreature(NPC_UtherGUID))
                                    c->m_Events.AddEvent(new UtherBatteredHiltEvent(*c, 6), c->m_Events.CalculateTime(3000));
                                break;
                            case 6:
                                if (Creature* c = instance->GetCreature(NPC_QuelDelarGUID))
{
                                    c->SetSpeed(MOVE_RUN, c->GetCreatureTemplate()->speed_run);
                                    c->GetMotionMaster()->MoveLand(0, c->GetPositionX(), c->GetPositionY(), 707.70f, 7.0f);
                                }
                                break;
                            case 7:
                                if (Creature* c = instance->GetCreature(NPC_QuelDelarGUID))
{
                                    c->SetReactState(REACT_AGGRESSIVE);
                                    c->SetImmuneToAll(false);
                                    c->RemoveAurasDueToSpell(70300);
                                }
                                break;
                            case 8:
                                if (Creature* c = instance->GetCreature(NPC_QuelDelarGUID))
                                    c->SetInCombatWithZone();
                                break;
                            case 9:
                                EncounterMask |= (1 << DATA_BATTERED_HILT);
                                BatteredHiltStatus |= BHSF_FINISHED;
                                SaveToDB();
                                break;
                        }
                    }
                    return;
            }
            if (data == DONE)
                SaveToDB();
        }
References ACHIEV_RETREATING_TIMED_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, ACTION_DELETE_ICE_WALL, ACTION_SHOW_TRASH, ACTION_SPIRITUAL_REFLECTIONS_ACTIVATE, ACTION_SPIRITUAL_REFLECTIONS_COPY, ACTION_SPIRITUAL_REFLECTIONS_HIDE, ACTION_START_INTRO, ACTION_START_LK_FIGHT, ACTION_STOP_LK_FIGHT, AddWave1(), BASE_ATTACK, BatteredHiltStatus, MapRefMgr::begin(), BHSF_FINISHED, BHSF_STARTED, BHSF_THROWN, ObjectGuid::Clear(), DATA_BATTERED_HILT, DATA_FALRIC, DATA_FROSTSWORN_GENERAL, DATA_INTRO, DATA_LICH_KING, DATA_LK_INTRO, DATA_MARWYN, DONE, InstanceScript::DoStartTimedAchievement(), InstanceScript::DoStopTimedAchievement(), InstanceScript::DoUpdateWorldState(), DoWipe1(), EMOTE_ONESHOT_EMERGE, EMOTE_ONESHOT_NONE, EncounterMask, MapRefMgr::end(), Map::GetCreature(), Object::GetEntry(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), GO_ArthasDoorGUID, GO_FrontDoorGUID, GO_IceWallGUID, InstanceScript::HandleGameObject(), InstanceScript::instance, IsDuringLKFight, LeaderEscapePos, Map::LoadGrid(), MOVE_RUN, MOVEMENTFLAG_WALKING, NextWaveTimer, NOT_STARTED, NPC_AltarBunnyGUID, NPC_FrostswornGeneralGUID, NPC_JAINA_PART2, NPC_LeaderGUID, NPC_LichKingGUID, NPC_QuelDelarGUID, NPC_SpiritualReflectionGUID, NPC_UtherGUID, OFF_ATTACK, outroStep, outroTimer, PathWaypoints, RandomizeCompositionsAndShow(), RANGED_ATTACK, REACT_AGGRESSIVE, InstanceScript::SaveToDB(), Object::SetUInt32Value(), SPELL_HOR_CLONE, SPELL_HOR_CLONE_NAME, SPELL_HOR_START_QUEST_ALLY, SPELL_HOR_START_QUEST_HORDE, SPELL_JAINA_ICE_PRISON, SPELL_SYLVANAS_DARK_BINDING, TEAM_ALLIANCE, TeamIdInInstance, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, UNIT_VIRTUAL_ITEM_SLOT_ID, WaveNumber, and WORLD_STATE_HOR_COUNTER.
Referenced by Update().
Update()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!instance->HavePlayers())
                return;
            if (CheckPlayersTimer <= diff)
            {
                CheckPlayersTimer = 5000;
                if ((EncounterMask & (1 << DATA_INTRO)) && !(EncounterMask & (1 << DATA_MARWYN))) // first event
                {
                    Map::PlayerList const& pl = instance->GetPlayers();
                    if (WaveNumber || NextWaveTimer)
                    {
                        bool allDead = true;
                        bool outOfRange = false;
                        for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                            if (Player* p = itr->GetSource())
{
                                if (p->IsGameMaster())
                                    continue;
                                if (p->IsAlive())
                                    allDead = false;
                                if (p->GetExactDist2d(&CenterPos) > MAX_DIST_FROM_CENTER_IN_COMBAT)
{
                                    outOfRange = true;
                                    break;
                                }
                            }
                        if (allDead || outOfRange)
                            DoWipe1();
                    }
                    else if (!ResumeFirstEventTimer)
                    {
                        bool allInRangeAndAlive = (instance->GetPlayersCountExceptGMs() > 0);
                        for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                            if (Player* p = itr->GetSource())
                                if (!p->IsGameMaster() && (p->GetExactDist2d(&CenterPos) > MAX_DIST_FROM_CENTER_TO_START || !p->IsAlive()))
{
                                    allInRangeAndAlive = false;
                                    break;
                                }
                        if (allInRangeAndAlive)
{
                            ResumeFirstEventTimer = 1;
                            ResumeFirstEventStep = 0;
                        }
                    }
                }
            }
            else
                CheckPlayersTimer -= diff;
            if (NextWaveTimer)
            {
                if (NextWaveTimer <= diff)
                {
                    NextWaveTimer = 0;
                    AddWave1();
                }
                else
                    NextWaveTimer -= diff;
            }
            if (ResumeFirstEventTimer)
            {
                if (ResumeFirstEventTimer <= diff)
                {
                    switch (ResumeFirstEventStep) // After a wipe
                    {
                        case 0:
                            if (Creature* pFalric = instance->GetCreature(NPC_FalricGUID))
{
                                pFalric->UpdatePosition(5274.9f, 2039.2f, 709.319f, 5.4619f, true);
                                pFalric->StopMovingOnCurrentPos();
                                pFalric->SetVisible(true);
                                if (pFalric->IsAlive())
{
                                    pFalric->GetMotionMaster()->MovePoint(0, FalricMovePos);
                                    if (Aura* a = pFalric->AddAura(SPELL_SHADOWMOURNE_VISUAL, pFalric))
                                        a->SetDuration(8000);
                                }
                            }
                            if (Creature* pMarwyn = instance->GetCreature(NPC_MarwynGUID))
{
                                pMarwyn->UpdatePosition(5343.77f, 1973.86f, 709.319f, 2.35173f, true);
                                pMarwyn->StopMovingOnCurrentPos();
                                pMarwyn->SetVisible(true);
                                if (pMarwyn->IsAlive())
{
                                    pMarwyn->GetMotionMaster()->MovePoint(0, MarwynMovePos);
                                    if (Aura* a = pMarwyn->AddAura(SPELL_SHADOWMOURNE_VISUAL, pMarwyn))
                                        a->SetDuration(8000);
                                }
                                pMarwyn->AI()->Talk(EMOTE_MARWYN_INTRO_SPIRIT);
                            }
                            ++ResumeFirstEventStep;
                            ResumeFirstEventTimer = 7500;
                            break;
                        case 1:
                            if (Creature* pFalric = instance->GetCreature(NPC_FalricGUID))
{
                                if (pFalric->IsAlive())
{
                                    pFalric->AI()->Talk(SAY_FALRIC_INTRO_2); // Between wave 1 and 4
                                }
                                else
{
                                    if (Creature* marwyn = instance->GetCreature(NPC_MarwynGUID))
{
                                        marwyn->AI()->Talk(SAY_MARWYN_WIPE_AFTER_FALRIC); // Between wave 6 and 9
                                    }
                                }
                            }
                            SetData(ACTION_SHOW_TRASH, 1);
                            ResumeFirstEventStep = 0;
                            ResumeFirstEventTimer = 0;
                            NextWaveTimer = 7000;
                            break;
                        default:
                            for (uint8 i = 0; i < NUM_OF_TRASH; ++i)
                                if (Creature* c = instance->GetCreature(NPC_TrashGUID[i]))
                                    c->SetVisible(false);
                            if (Creature* falric = instance->GetCreature(NPC_FalricGUID))
                                falric->SetVisible(false);
                            if (Creature* marwyn = instance->GetCreature(NPC_MarwynGUID))
                                marwyn->SetVisible(false);
                            ResumeFirstEventStep = 0;
                            ResumeFirstEventTimer = 0;
                            break;
                    }
                }
                else
                    ResumeFirstEventTimer -= diff;
            }
            if (outroStep)
            {
                if (outroTimer <= diff)
                {
                    switch (outroStep)
                    {
                        case 1:
                            if (Creature* lk = instance->GetCreature(NPC_LichKingGUID))
{
                                lk->UpdatePosition(PathWaypoints[PATH_WP_COUNT - 2], true);
                                lk->StopMovingOnCurrentPos();
                                lk->RemoveAllAuras();
                                lk->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_CUSTOM_SPELL_02);
                                if (!lk->IsVisible())
                                    lk->SetVisible(true);
                                if (Creature* leader = instance->GetCreature(NPC_LeaderGUID))
{
                                    leader->UpdatePosition(PathWaypoints[PATH_WP_COUNT - 1], true);
                                    leader->StopMovingOnCurrentPos();
                                    leader->RemoveAllAuras();
                                    leader->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_READY1H);
                                    if (!leader->IsVisible())
                                        leader->SetVisible(true);
                                    lk->CastSpell(leader, SPELL_HARVEST_SOUL, false);
                                }
                            }
                            ++outroStep;
                            outroTimer = 500;
                            break;
                        case 2:
{
                                uint32 entry = TeamIdInInstance == TEAM_ALLIANCE ? GO_THE_SKYBREAKER : GO_ORGRIMS_HAMMER;
                                T1 = sTransportMgr->CreateTransport(entry, 0, instance);
                                ++outroStep;
                                outroTimer = TeamIdInInstance == TEAM_ALLIANCE ? 10000 : 10500;
                            }
                            break;
                        case 3:
                            if (T1)
                                T1->EnableMovement(false);
                            if (Creature* c = instance->GetCreature(NPC_ShipCaptainGUID))
                                c->AI()->Talk(TeamIdInInstance == TEAM_ALLIANCE ? SAY_FIRE_ALLY : SAY_FIRE_HORDE);
                            if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
{
                                c->RemoveAllAuras();
                                c->CastSpell(c, SPELL_GUNSHIP_CANNON_FIRE_PERIODIC, true);
                            }
                            if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
{
                                c->InterruptNonMeleeSpells(true);
                                c->RemoveAllAuras();
                            }
                            ++outroStep;
                            outroTimer = 5000;
                            break;
                        case 4:
                            HandleGameObject(GO_CaveInGUID, false);
                            ++outroStep;
                            outroTimer = 3000;
                            break;
                        case 5:
                            if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
                                c->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                            if (Creature* c = instance->GetCreature(NPC_LichKingGUID))
{
                                c->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                                c->GetThreatMgr().ClearAllThreat();
                                c->CombatStop(true);
                                c->InterruptNonMeleeSpells(true);
                                c->SetVisible(false);
                            }
                            if (instance->IsHeroic())
                                instance->ToInstanceMap()->PermBindAllPlayers();
                            if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
                                c->CastSpell(c, SPELL_ACHIEVEMENT_CHECK, true);
                            ++outroStep;
                            outroTimer = 1000;
                            break;
                        case 6:
                            if (T1)
                                T1->EnableMovement(true);
                            ++outroStep;
                            outroTimer = 3500;
                            break;
                        case 7:
                            if (T1)
                                T1->EnableMovement(false);
                            if (Creature* leader = instance->GetCreature(NPC_LeaderGUID))
{
                                uint8 index = TeamIdInInstance == TEAM_ALLIANCE ? 0 : 1;
                                for (uint8 i = 0; i < 3; ++i)
                                    if (StairsPos[index][i].GetPositionX())
                                        if (GameObject* go = leader->SummonGameObject(TeamIdInInstance == TEAM_ALLIANCE ? GO_STAIRS_ALLIANCE : GO_STAIRS_HORDE, StairsPos[index][i].GetPositionX(), StairsPos[index][i].GetPositionY(), StairsPos[index][i].GetPositionZ(), StairsPos[index][i].GetOrientation(), 0.0f, 0.0f, 0.0f, 0.0f, 86400, false))
                                            go->SetGameObjectFlag(GO_FLAG_INTERACT_COND | GO_FLAG_NOT_SELECTABLE);
                                //Position pos = TeamIdInInstance == TEAM_ALLIANCE ? AllyPortalPos : HordePortalPos;
                                //leader->SummonGameObject(GO_PORTAL_TO_DALARAN, pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), pos.GetOrientation(), 0.0f, 0.0f, 0.0f, 0.0f, 86400);
                                //pos = TeamIdInInstance == TEAM_ALLIANCE ? AllyChestPos : HordeChestPos;
                                //leader->SummonGameObject(instance->GetSpawnMode() ? GO_CHEST_HEROIC : GO_CHEST_NORMAL, pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), pos.GetOrientation(), 0.0f, 0.0f, 0.0f, 0.0f, 86400);
                            }
                            ++outroStep;
                            outroTimer = 1000;
                            break;
                        case 8:
                            if (Creature* c = instance->GetCreature(NPC_ShipCaptainGUID))
                                c->AI()->Talk(TeamIdInInstance == TEAM_ALLIANCE ? SAY_ONBOARD_ALLY : SAY_ONBOARD_HORDE);
                            if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
{
                                c->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                c->GetMotionMaster()->MovePoint(0, WalkCaveInPos);
                                c->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP); // need gossip ID 10931
                            }
                            ++outroStep;
                            outroTimer = 6000;
                            break;
                        case 9:
                            if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
                                c->AI()->Talk(TeamIdInInstance == TEAM_ALLIANCE ? SAY_JAINA_FINAL_1 : SAY_SYLVANA_FINAL);
                            HandleGameObject(GO_CaveInGUID, true);
                            ++outroStep;
                            outroTimer = 11000;
                            break;
                        case 10:
                            ++outroStep;
                            outroTimer = 0;
                            for (Map::PlayerList::const_iterator itr = instance->GetPlayers().begin(); itr != instance->GetPlayers().end(); ++itr)
                                if (Player* p = itr->GetSource())
                                    p->KilledMonsterCredit(NPC_WRATH_OF_THE_LICH_KING_CREDIT);
                            if (TeamIdInInstance == TEAM_ALLIANCE)
                                if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
{
                                    c->AI()->Talk(SAY_JAINA_FINAL_2);
                                    outroTimer = 10000;
                                }
                            break;
                        case 11:
                            if (Creature* c = instance->GetCreature(NPC_LeaderGUID))
                                c->SetNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
                            ++outroStep;
                            outroTimer = 300 * 1000;
                            break;
                        case 12:
                            outroStep = 0;
                            outroTimer = 0;
                            if (T1)
                                T1->setActive(false);
                            break;
                    }
                }
                else
                    outroTimer -= diff;
            }
        }
References ACTION_SHOW_TRASH, AddWave1(), MapRefMgr::begin(), CenterPos, CheckPlayersTimer, DATA_INTRO, DATA_MARWYN, DoWipe1(), EMOTE_MARWYN_INTRO_SPIRIT, EMOTE_ONESHOT_CUSTOM_SPELL_02, EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_READY1H, MotionTransport::EnableMovement(), EncounterMask, MapRefMgr::end(), FalricMovePos, Map::GetCreature(), Position::GetOrientation(), Map::GetPlayers(), Map::GetPlayersCountExceptGMs(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_CaveInGUID, GO_FLAG_INTERACT_COND, GO_FLAG_NOT_SELECTABLE, GO_ORGRIMS_HAMMER, GO_STAIRS_ALLIANCE, GO_STAIRS_HORDE, GO_THE_SKYBREAKER, InstanceScript::HandleGameObject(), Map::HavePlayers(), InstanceScript::instance, Map::IsHeroic(), MarwynMovePos, MAX_DIST_FROM_CENTER_IN_COMBAT, MAX_DIST_FROM_CENTER_TO_START, MOVEMENTFLAG_WALKING, NextWaveTimer, NPC_FalricGUID, NPC_LeaderGUID, NPC_LichKingGUID, NPC_MarwynGUID, NPC_ShipCaptainGUID, NPC_TrashGUID, NPC_WRATH_OF_THE_LICH_KING_CREDIT, NUM_OF_TRASH, outroStep, outroTimer, PATH_WP_COUNT, PathWaypoints, InstanceMap::PermBindAllPlayers(), ResumeFirstEventStep, ResumeFirstEventTimer, SAY_FALRIC_INTRO_2, SAY_FIRE_ALLY, SAY_FIRE_HORDE, SAY_JAINA_FINAL_1, SAY_JAINA_FINAL_2, SAY_MARWYN_WIPE_AFTER_FALRIC, SAY_ONBOARD_ALLY, SAY_ONBOARD_HORDE, SAY_SYLVANA_FINAL, WorldObject::setActive(), SetData(), SPELL_ACHIEVEMENT_CHECK, SPELL_GUNSHIP_CANNON_FIRE_PERIODIC, SPELL_HARVEST_SOUL, SPELL_SHADOWMOURNE_VISUAL, StairsPos, sTransportMgr, WorldObject::SummonGameObject(), T1, TEAM_ALLIANCE, TeamIdInInstance, Map::ToInstanceMap(), UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, WalkCaveInPos, and WaveNumber.
WriteSaveDataMore()
void instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << EncounterMask;
        }
References EncounterMask.
Member Data Documentation
BatteredHiltStatus
uint32 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::BatteredHiltStatus
Referenced by GetData(), Initialize(), ReadSaveDataMore(), and SetData().
bFinished5Waves
bool instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::bFinished5Waves
Referenced by AddWave1(), Initialize(), and RandomizeCompositionsAndShow().
CheckPlayersTimer
uint16 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::CheckPlayersTimer
Referenced by Initialize(), and Update().
chosenComposition
uint32 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::chosenComposition[8][5]
Referenced by AddWave1(), DoWipe1(), Initialize(), and RandomizeCompositionsAndShow().
EncounterMask
uint32 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::EncounterMask
Referenced by GetData(), Initialize(), OnCreatureCreate(), OnGameObjectCreate(), ReadSaveDataMore(), SetData(), Update(), and WriteSaveDataMore().
GO_ArthasDoorGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GO_ArthasDoorGUID
Referenced by GetGuidData(), OnGameObjectCreate(), and SetData().
GO_CaveInGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GO_CaveInGUID
Referenced by OnGameObjectCreate(), and Update().
GO_DoorAfterThroneGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GO_DoorAfterThroneGUID
Referenced by OnGameObjectCreate().
GO_DoorBeforeThroneGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GO_DoorBeforeThroneGUID
Referenced by OnGameObjectCreate().
GO_FrontDoorGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GO_FrontDoorGUID
Referenced by AddWave1(), DoWipe1(), GetGuidData(), OnGameObjectCreate(), and SetData().
GO_FrostmourneAltarGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GO_FrostmourneAltarGUID
Referenced by OnGameObjectCreate().
GO_FrostmourneGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GO_FrostmourneGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GO_IceWallGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GO_IceWallGUID
Referenced by OnGameObjectCreate(), and SetData().
IsDuringLKFight
bool instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::IsDuringLKFight
Referenced by Initialize(), IsEncounterInProgress(), and SetData().
NextWaveTimer
uint32 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NextWaveTimer
Referenced by AddWave1(), DoWipe1(), Initialize(), OnUnitDeath(), SetData(), and Update().
NPC_AltarBunnyGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_AltarBunnyGUID
Referenced by OnCreatureCreate(), and SetData().
NPC_FalricGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_FalricGUID
Referenced by AddWave1(), DoWipe1(), GetGuidData(), OnCreatureCreate(), and Update().
NPC_FrostswornGeneralGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_FrostswornGeneralGUID
Referenced by OnCreatureCreate(), and SetData().
NPC_GuardGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_GuardGUID
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_IceWallTargetGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_IceWallTargetGUID[4]
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_LeaderGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_LeaderGUID
Referenced by GetGuidData(), OnCreatureCreate(), SetData(), and Update().
NPC_LeaderIntroGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_LeaderIntroGUID
Referenced by OnCreatureCreate().
NPC_LichKingGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_LichKingGUID
Referenced by GetGuidData(), OnCreatureCreate(), SetData(), and Update().
NPC_LichKingIntroGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_LichKingIntroGUID
Referenced by GetGuidData(), and OnCreatureCreate().
NPC_MarwynGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_MarwynGUID
Referenced by AddWave1(), DoWipe1(), GetGuidData(), OnCreatureCreate(), and Update().
NPC_QuelDelarGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_QuelDelarGUID
Referenced by OnCreatureCreate(), and SetData().
NPC_ShipCaptainGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_ShipCaptainGUID
Referenced by OnCreatureCreate(), and Update().
NPC_SpiritualReflectionGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_SpiritualReflectionGUID[5]
Referenced by OnCreatureCreate(), and SetData().
NPC_TrashGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_TrashGUID[NUM_OF_TRASH]
Referenced by AddWave1(), DoWipe1(), OnCreatureCreate(), RandomizeCompositionsAndShow(), and Update().
NPC_UtherGUID
ObjectGuid instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::NPC_UtherGUID
Referenced by GetGuidData(), OnCreatureCreate(), OnUnitDeath(), and SetData().
outroStep
uint8 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::outroStep
Referenced by Initialize(), SetData(), and Update().
outroTimer
uint32 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::outroTimer
Referenced by Initialize(), SetData(), and Update().
reqKillCount
uint8 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::reqKillCount
Referenced by AddWave1(), DoWipe1(), Initialize(), and OnUnitDeath().
ResumeFirstEventStep
uint8 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::ResumeFirstEventStep
Referenced by DoWipe1(), Initialize(), and Update().
ResumeFirstEventTimer
uint16 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::ResumeFirstEventTimer
Referenced by DoWipe1(), Initialize(), and Update().
T1
MotionTransport* instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::T1
Referenced by Initialize(), and Update().
TeamIdInInstance
TeamId instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::TeamIdInInstance
Referenced by Initialize(), OnCreatureCreate(), SetData(), and Update().
TrashActive
bool instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::TrashActive[NUM_OF_TRASH]
Referenced by AddWave1(), DoWipe1(), Initialize(), and RandomizeCompositionsAndShow().
TrashCounter
uint8 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::TrashCounter
Referenced by DoWipe1(), Initialize(), and OnCreatureCreate().
WaveNumber
uint8 instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::WaveNumber
Referenced by AddWave1(), DoWipe1(), GetData(), Initialize(), IsEncounterInProgress(), OnUnitDeath(), RandomizeCompositionsAndShow(), SetData(), and Update().