AzerothCore: instance_blood_furnace::instance_blood_furnace_InstanceMapScript Struct Reference
instance_blood_furnace::instance_blood_furnace_InstanceMapScript Struct Reference
Public Member Functions
instance_blood_furnace_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnUnitDeath (Unit *unit) override
void OnGameObjectCreate (GameObject *go) override
ObjectGuid GetGuidData (uint32 data) const override
bool SetBossState (uint32 type, EncounterState state) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
void ResetPrisons ()
void ResetPrisoners (GuidSet prisoners)
void ResetPrisoner (Creature *prisoner)
void StorePrisoner (Creature *creature)
void PrisonerDied (ObjectGuid guid)
void ActivateCell (uint8 id)
void ActivatePrisoners (GuidSet prisoners)
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 _auiEncounter [MAX_ENCOUNTER]
ObjectGuid _doorGUIDs [6]
ObjectGuid _prisonGUIDs [4]
GuidSet _prisonersCell [4]
uint8 _prisonerCounter [4]
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_blood_furnace_InstanceMapScript()
instance_blood_furnace::instance_blood_furnace_InstanceMapScript::instance_blood_furnace_InstanceMapScript (Map * map) inline
                                                           : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(EncounterCount);
            LoadDoorData(doorData);
            LoadObjectData(creatureData, gameobjectData);
        }
References creatureData, DataHeader, doorData, EncounterCount, gameobjectData, InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
ActivateCell()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ActivateCell (uint8 id) inline
        {
            switch (id)
            {
                case DATA_PRISON_CELL1:
                case DATA_PRISON_CELL2:
                case DATA_PRISON_CELL3:
                case DATA_PRISON_CELL4:
                    HandleGameObject(_prisonGUIDs[id - DATA_PRISON_CELL1], true);
                    ActivatePrisoners(_prisonersCell[id - DATA_PRISON_CELL1]);
                    break;
                case DATA_BROGGOK_REAR_DOOR:
                    if (GameObject* go = GetGameObject(DATA_BROGGOK_REAR_DOOR))
                    {
                        HandleGameObject(ObjectGuid::Empty, true, go);
                    }
                    if (Creature* broggok = GetCreature(DATA_BROGGOK))
                    {
                        broggok->AI()->DoAction(ACTION_ACTIVATE_BROGGOK);
                    }
                    break;
            }
        }
References _prisonersCell, _prisonGUIDs, ACTION_ACTIVATE_BROGGOK, ActivatePrisoners(), DATA_BROGGOK, DATA_BROGGOK_REAR_DOOR, DATA_PRISON_CELL1, DATA_PRISON_CELL2, DATA_PRISON_CELL3, DATA_PRISON_CELL4, ObjectGuid::Empty, InstanceScript::GetCreature(), InstanceScript::GetGameObject(), and InstanceScript::HandleGameObject().
Referenced by PrisonerDied(), and SetBossState().
ActivatePrisoners()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ActivatePrisoners (GuidSet prisoners) inline
        {
            for (ObjectGuid const& guid : prisoners)
                if (Creature* prisoner = instance->GetCreature(guid))
                {
                    prisoner->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    prisoner->SetImmuneToAll(false);
                    prisoner->SetInCombatWithZone();
                }
        }
References Map::GetCreature(), InstanceScript::instance, and UNIT_FLAG_NON_ATTACKABLE.
Referenced by ActivateCell().
GetData()
uint32 instance_blood_furnace::instance_blood_furnace_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_THE_MAKER:
                case DATA_KELIDAN:
                    return _auiEncounter[type];
            }
            return 0;
        }
References _auiEncounter, DATA_KELIDAN, and DATA_THE_MAKER.
Referenced by OnGameObjectCreate().
GetGuidData()
ObjectGuid instance_blood_furnace::instance_blood_furnace_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (data)
            {
                case DATA_DOOR1:
                case DATA_DOOR2:
                case DATA_DOOR3:
                case DATA_DOOR6:
                    return _doorGUIDs[data - DATA_DOOR1];
                case DATA_PRISON_CELL1:
                case DATA_PRISON_CELL2:
                case DATA_PRISON_CELL3:
                case DATA_PRISON_CELL4:
                    return _prisonGUIDs[data - DATA_PRISON_CELL1];
            }
            return ObjectGuid::Empty;
        }
References _doorGUIDs, _prisonGUIDs, DATA_DOOR1, DATA_DOOR2, DATA_DOOR3, DATA_DOOR6, DATA_PRISON_CELL1, DATA_PRISON_CELL2, DATA_PRISON_CELL3, DATA_PRISON_CELL4, and ObjectGuid::Empty.
Initialize()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            memset(&_auiEncounter, 0, sizeof(_auiEncounter));
            memset(&_prisonerCounter, 0, sizeof(_prisonerCounter));
        }
References _auiEncounter, and _prisonerCounter.
OnCreatureCreate()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            if (creature->GetEntry() == NPC_NASCENT_FEL_ORC)
            {
                StorePrisoner(creature);
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References Object::GetEntry(), NPC_NASCENT_FEL_ORC, InstanceScript::OnCreatureCreate(), and StorePrisoner().
OnGameObjectCreate()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            if (go->GetEntry() == 181766)                //Final exit door
                _doorGUIDs[0] = go->GetGUID();
            if (go->GetEntry() == 181811)               //The Maker Front door
                _doorGUIDs[1] = go->GetGUID();
            if (go->GetEntry() == 181812)                //The Maker Rear door
            {
                _doorGUIDs[2] = go->GetGUID();
                if (GetData(DATA_THE_MAKER) == DONE)
                    HandleGameObject(go->GetGUID(), true);
            }
            if (go->GetEntry() == 181823)               //Kelidan exit door
                _doorGUIDs[5] = go->GetGUID();
            if (go->GetEntry() == 181821)               //Broggok prison cell front right
                _prisonGUIDs[0] = go->GetGUID();
            if (go->GetEntry() == 181818)               //Broggok prison cell back right
                _prisonGUIDs[1] = go->GetGUID();
            if (go->GetEntry() == 181820)               //Broggok prison cell front left
                _prisonGUIDs[2] = go->GetGUID();
            if (go->GetEntry() == 181817)               //Broggok prison cell back left
                _prisonGUIDs[3] = go->GetGUID();
            InstanceScript::OnGameObjectCreate(go);
        }
References _doorGUIDs, _prisonGUIDs, DATA_THE_MAKER, DONE, GetData(), Object::GetEntry(), Object::GetGUID(), InstanceScript::HandleGameObject(), and InstanceScript::OnGameObjectCreate().
OnUnitDeath()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            if (unit && unit->IsCreature() && unit->GetEntry() == NPC_NASCENT_FEL_ORC)
                PrisonerDied(unit->GetGUID());
        }
References Object::GetEntry(), Object::GetGUID(), Object::IsCreature(), NPC_NASCENT_FEL_ORC, and PrisonerDied().
PrisonerDied()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::PrisonerDied (ObjectGuid guid) inline
        {
            if (_prisonersCell[0].find(guid) != _prisonersCell[0].end() && --_prisonerCounter[0] <= 0)
                ActivateCell(DATA_PRISON_CELL2);
            else if (_prisonersCell[1].find(guid) != _prisonersCell[1].end() && --_prisonerCounter[1] <= 0)
                ActivateCell(DATA_PRISON_CELL3);
            else if (_prisonersCell[2].find(guid) != _prisonersCell[2].end() && --_prisonerCounter[2] <= 0)
                ActivateCell(DATA_PRISON_CELL4);
            else if (_prisonersCell[3].find(guid) != _prisonersCell[3].end() && --_prisonerCounter[3] <= 0)
                ActivateCell(DATA_BROGGOK_REAR_DOOR);
        }
References _prisonerCounter, _prisonersCell, ActivateCell(), DATA_BROGGOK_REAR_DOOR, DATA_PRISON_CELL2, DATA_PRISON_CELL3, and DATA_PRISON_CELL4.
Referenced by OnUnitDeath().
ResetPrisoner()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ResetPrisoner (Creature * prisoner) inline
        {
            if (!prisoner->IsAlive())
                prisoner->Respawn(true);
            prisoner->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            prisoner->SetImmuneToAll(true);
        }
References Unit::IsAlive(), Creature::Respawn(), Unit::SetImmuneToAll(), Unit::SetUnitFlag(), and UNIT_FLAG_NON_ATTACKABLE.
Referenced by ResetPrisoners(), and StorePrisoner().
ResetPrisoners()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ResetPrisoners (GuidSet prisoners) inline
        {
            for (ObjectGuid const& guid : prisoners)
                if (Creature* prisoner = instance->GetCreature(guid))
                    ResetPrisoner(prisoner);
        }
References Map::GetCreature(), InstanceScript::instance, and ResetPrisoner().
Referenced by ResetPrisons().
ResetPrisons()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ResetPrisons () inline
        {
            for (uint8 i = 0; i < 4; ++i)
            {
                _prisonerCounter[i] = _prisonersCell[i].size();
                ResetPrisoners(_prisonersCell[i]);
                HandleGameObject(_prisonGUIDs[i], false);
            }
        }
References _prisonerCounter, _prisonersCell, _prisonGUIDs, InstanceScript::HandleGameObject(), and ResetPrisoners().
Referenced by SetBossState().
SetBossState()
bool instance_blood_furnace::instance_blood_furnace_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            if (type == DATA_BROGGOK)
            {
                if (state == IN_PROGRESS)
                {
                    ActivateCell(DATA_PRISON_CELL1);
                    HandleGameObject(_doorGUIDs[3], false);
                }
                else if (state == NOT_STARTED)
                {
                    ResetPrisons();
                    HandleGameObject(_doorGUIDs[4], false);
                    HandleGameObject(_doorGUIDs[3], true);
                    if (GameObject* lever = GetGameObject(DATA_BROGGOK_LEVER))
                    {
                        lever->Respawn();
                    }
                }
            }
            return true;
        }
References _doorGUIDs, ActivateCell(), DATA_BROGGOK, DATA_BROGGOK_LEVER, DATA_PRISON_CELL1, InstanceScript::GetGameObject(), InstanceScript::HandleGameObject(), IN_PROGRESS, NOT_STARTED, ResetPrisons(), and InstanceScript::SetBossState().
SetData()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_THE_MAKER:
                case DATA_KELIDAN:
                    _auiEncounter[type] = data;
                    break;
            }
            if (data == DONE)
                SaveToDB();
        }
References _auiEncounter, DATA_KELIDAN, DATA_THE_MAKER, DONE, and InstanceScript::SaveToDB().
StorePrisoner()
void instance_blood_furnace::instance_blood_furnace_InstanceMapScript::StorePrisoner (Creature * creature) inline
        {
            float posX = creature->GetPositionX();
            float posY = creature->GetPositionY();
            if (posX >= 405.0f && posX <= 423.0f)
            {
                if (posY >= 106.0f && posY <= 123.0f)
                {
                    _prisonersCell[0].insert(creature->GetGUID());
                    ++_prisonerCounter[0];
                    ResetPrisoner(creature);
                }
                else if (posY >= 76.0f && posY <= 91.0f)
                {
                    _prisonersCell[1].insert(creature->GetGUID());
                    ++_prisonerCounter[1];
                    ResetPrisoner(creature);
                }
            }
            else if (posX >= 490.0f && posX <= 506.0f)
            {
                if (posY >= 106.0f && posY <= 123.0f)
                {
                    _prisonersCell[2].insert(creature->GetGUID());
                    ++_prisonerCounter[2];
                    ResetPrisoner(creature);
                }
                else if (posY >= 76.0f && posY <= 91.0f)
                {
                    _prisonersCell[3].insert(creature->GetGUID());
                    ++_prisonerCounter[3];
                    ResetPrisoner(creature);
                }
            }
        }
References _prisonerCounter, _prisonersCell, Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), and ResetPrisoner().
Referenced by OnCreatureCreate().
Member Data Documentation
_auiEncounter
uint32 instance_blood_furnace::instance_blood_furnace_InstanceMapScript::_auiEncounter[MAX_ENCOUNTER]
Referenced by GetData(), Initialize(), and SetData().
_doorGUIDs
ObjectGuid instance_blood_furnace::instance_blood_furnace_InstanceMapScript::_doorGUIDs[6]
Referenced by GetGuidData(), OnGameObjectCreate(), and SetBossState().
_prisonerCounter
uint8 instance_blood_furnace::instance_blood_furnace_InstanceMapScript::_prisonerCounter[4]
Referenced by Initialize(), PrisonerDied(), ResetPrisons(), and StorePrisoner().
_prisonersCell
GuidSet instance_blood_furnace::instance_blood_furnace_InstanceMapScript::_prisonersCell[4]
Referenced by ActivateCell(), PrisonerDied(), ResetPrisons(), and StorePrisoner().
_prisonGUIDs
ObjectGuid instance_blood_furnace::instance_blood_furnace_InstanceMapScript::_prisonGUIDs[4]
Referenced by ActivateCell(), GetGuidData(), OnGameObjectCreate(), and ResetPrisons().