AzerothCore: BoneStormMoveTargetSelector Struct Reference
BoneStormMoveTargetSelector Struct Reference
Public Member Functions
BoneStormMoveTargetSelector (Creature *source)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
Detailed Description
Constructor & Destructor Documentation
BoneStormMoveTargetSelector()
BoneStormMoveTargetSelector::BoneStormMoveTargetSelector (Creature * source) inline
: _source(source) { }
Member Function Documentation
operator()()
bool BoneStormMoveTargetSelector::operator() (Unit const * target) const inline
    {
        if (!target)
            return false;
        if (target->GetExactDist(_source) > 175.0f)
            return false;
        if (!target->IsPlayer())
            return false;
        if (target->GetPositionX() > -337.0f)
            return false;
        return target != _source->GetVictim();
    }
References _source, Position::GetExactDist(), Position::GetPositionX(), Unit::GetVictim(), and Object::IsPlayer().
Member Data Documentation
_source
Creature const* BoneStormMoveTargetSelector::_source private
Referenced by operator()().