AzeorthCore: pet_commandscript Class Reference
pet_commandscript Class Reference
Public Member Functions
pet_commandscript ()
ChatCommandTable GetCommands () const override
virtual std::vector< Acore::ChatCommands::ChatCommandBuilder > GetCommands () const =0
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandlePetCreateCommand (ChatHandler *handler)
static bool HandlePetLearnCommand (ChatHandler *handler, SpellInfo const *spell)
static bool HandlePetUnlearnCommand (ChatHandler *handler, SpellInfo const *spell)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
pet_commandscript()
pet_commandscript::pet_commandscript () inline
: CommandScript("pet_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable pet_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable petCommandTable =
        {
            { "create",  HandlePetCreateCommand,  SEC_GAMEMASTER, Console::No },
            { "learn",   HandlePetLearnCommand,   SEC_GAMEMASTER, Console::No },
            { "unlearn", HandlePetUnlearnCommand, SEC_GAMEMASTER, Console::No }
        };
        static ChatCommandTable commandTable =
        {
            { "pet", petCommandTable }
        };
        return commandTable;
    }
References HandlePetCreateCommand(), HandlePetLearnCommand(), HandlePetUnlearnCommand(), and SEC_GAMEMASTER.
HandlePetCreateCommand()
static bool pet_commandscript::HandlePetCreateCommand (ChatHandler * handler) inline static
    {
        Player* player = handler->GetSession()->GetPlayer();
        Creature* creatureTarget = handler->getSelectedCreature();
        if (!creatureTarget || creatureTarget->IsPet() || creatureTarget->GetTypeId() == TYPEID_PLAYER)
        {
            handler->PSendSysMessage(LANG_SELECT_CREATURE);
            handler->SetSentErrorMessage(true);
            return false;
        }
        CreatureTemplate const* creatrueTemplate = sObjectMgr->GetCreatureTemplate(creatureTarget->GetEntry());
        // Creatures with family 0 crashes the server
        if (!creatrueTemplate->family)
        {
            handler->PSendSysMessage(LANG_CREATURE_NON_TAMEABLE, creatrueTemplate->Entry);
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (player->IsExistPet())
        {
            handler->SendSysMessage(LANG_YOU_ALREADY_HAVE_PET);
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (!player->CreatePet(creatureTarget))
        {
            handler->PSendSysMessage(LANG_CREATURE_NON_TAMEABLE, creatrueTemplate->Entry);
            handler->SetSentErrorMessage(true);
            return false;
        }
        return true;
    }
References Player::CreatePet(), CreatureTemplate::Entry, CreatureTemplate::family, Object::GetEntry(), WorldSession::GetPlayer(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), Object::GetTypeId(), Player::IsExistPet(), Unit::IsPet(), LANG_CREATURE_NON_TAMEABLE, LANG_SELECT_CREATURE, LANG_YOU_ALREADY_HAVE_PET, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), sObjectMgr, and TYPEID_PLAYER.
Referenced by GetCommands().
HandlePetLearnCommand()
static bool pet_commandscript::HandlePetLearnCommand (ChatHandler * handler, SpellInfo const * spell) inline static
    {
        if (!spell)
        {
            handler->PSendSysMessage(LANG_COMMAND_NOSPELLFOUND);
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (!SpellMgr::IsSpellValid(spell))
        {
            handler->PSendSysMessage(LANG_COMMAND_SPELL_BROKEN, spell->Id);
            handler->SetSentErrorMessage(true);
            return false;
        }
        Pet* pet = handler->GetSession()->GetPlayer()->GetPet();
        if (!pet)
        {
            handler->PSendSysMessage("You have no pet");
            handler->SetSentErrorMessage(true);
            return false;
        }
        SpellScriptsBounds bounds = sObjectMgr->GetSpellScriptsBounds(spell->Id);
        uint32 spellDifficultyId = sSpellMgr->GetSpellDifficultyId(spell->Id);
        if (bounds.first != bounds.second || spellDifficultyId)
        {
            handler->PSendSysMessage("Spell %u cannot be learnt using a command!", spell->Id);
            handler->SetSentErrorMessage(true);
            return false;
        }
        // Check if pet already has it
        if (pet->HasSpell(spell->Id))
        {
            handler->PSendSysMessage("Pet already has spell: %u", spell->Id);
            handler->SetSentErrorMessage(true);
            return false;
        }
        pet->learnSpell(spell->Id);
        handler->PSendSysMessage("Pet has learned spell %u", spell->Id);
        return true;
    }
References Player::GetPet(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Pet::HasSpell(), SpellInfo::Id, SpellMgr::IsSpellValid(), LANG_COMMAND_NOSPELLFOUND, LANG_COMMAND_SPELL_BROKEN, Pet::learnSpell(), ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), sObjectMgr, and sSpellMgr.
Referenced by GetCommands().
HandlePetUnlearnCommand()
static bool pet_commandscript::HandlePetUnlearnCommand (ChatHandler * handler, SpellInfo const * spell) inline static
    {
        if (!spell)
        {
            handler->PSendSysMessage(LANG_COMMAND_NOSPELLFOUND);
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (!SpellMgr::IsSpellValid(spell))
        {
            handler->PSendSysMessage(LANG_COMMAND_SPELL_BROKEN, spell->Id);
            handler->SetSentErrorMessage(true);
            return false;
        }
        Pet* pet = handler->GetSession()->GetPlayer()->GetPet();
        if (!pet)
        {
            handler->PSendSysMessage("You have no pet");
            handler->SetSentErrorMessage(true);
            return false;
        }
        if (pet->HasSpell(spell->Id))
        {
            pet->removeSpell(spell->Id, false);
        }
        else
        {
            handler->PSendSysMessage("Pet doesn't have that spell");
        }
        return true;
    }
References Player::GetPet(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Pet::HasSpell(), SpellInfo::Id, SpellMgr::IsSpellValid(), LANG_COMMAND_NOSPELLFOUND, LANG_COMMAND_SPELL_BROKEN, ChatHandler::PSendSysMessage(), Pet::removeSpell(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().