AzeorthCore: boss_yoggsaron_sara::boss_yoggsaron_saraAI Struct Reference
boss_yoggsaron_sara::boss_yoggsaron_saraAI Struct Reference
Public Member Functions
boss_yoggsaron_saraAI (Creature *pCreature)
void AttackStart (Unit *) override
void MoveInLineOfSight (Unit *) override
void JustSummoned (Creature *cr) override
void SpawnClouds ()
void SpawnWeels ()
void EnterEvadeMode (EvadeReason why) override
void EnableSara (bool apply)
void Reset () override
void InitFight (Unit *target)
void SaveKeepers ()
void InformCloud ()
void SpawnTentacle (uint32 entry)
void SummonDeathOrbs ()
void AddPortals ()
void SpellSounds ()
void KilledUnit (Unit *who) override
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
uint32 GetData (uint32 param) const override
void DoAction (int32 param) override
void DamageTaken (Unit *who, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
Cast Spell.
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
Play sound.
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
Reset Threat.
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
Modify Unit Threat.
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
Teleport player.
void DoTeleportAll (float x, float y, float z, float o)
Teleport all.
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
Set Combat Movement.
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectTargetMethod targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
uint32 _initFight
ObjectGuid _keepersGUID [4]
uint8 _summonedGuardiansCount
uint32 _p2TalkTimer
bool _secondPhase
float _summonSpeed
uint8 _currentIllusion
bool _isIllusionReversed
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_yoggsaron_saraAI()
boss_yoggsaron_sara::boss_yoggsaron_saraAI::boss_yoggsaron_saraAI (Creature * pCreature) inline
                                                   : ScriptedAI(pCreature), summons(pCreature)
        {
            m_pInstance = pCreature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and m_pInstance.
Member Function Documentation
AddPortals()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::AddPortals () inline
        {
            _summonSpeed -= 0.1f;
            Creature* cr = nullptr;
            // Spawn Portals
            for (uint8 i = 0; i < RAID_MODE(4, 10); ++i)
            {
                if ((cr = me->SummonCreature(NPC_DESCEND_INTO_MADNESS, yoggPortalLoc[i].x, yoggPortalLoc[i].y, yoggPortalLoc[i].z, 0, TEMPSUMMON_TIMED_DESPAWN, 25000)))
                {
                    cr->SetUnitFlag(UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_NON_ATTACKABLE);
                    cr->SetArmor(_currentIllusion);
                }
            }
            EntryCheckPredicate pred(NPC_BRAIN_OF_YOGG_SARON);
            summons.DoAction(_currentIllusion, pred);
            if (_isIllusionReversed)
                _currentIllusion = _currentIllusion == 3 ? 1 : (_currentIllusion + 1);
            else
                _currentIllusion = _currentIllusion == 1 ? 3 : (_currentIllusion - 1);
        }
References _currentIllusion, _isIllusionReversed, _summonSpeed, SummonList::DoAction(), ScriptedAI::me, NPC_BRAIN_OF_YOGG_SARON, NPC_DESCEND_INTO_MADNESS, ScriptedAI::RAID_MODE(), Unit::SetArmor(), Unit::SetUnitFlag(), WorldObject::SummonCreature(), summons, TEMPSUMMON_TIMED_DESPAWN, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, LocationsXY::x, LocationsXY::y, yoggPortalLoc, and LocationsXY::z.
Referenced by UpdateAI().
AttackStart()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
{ }
Referenced by InitFight().
DamageTaken()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken (Unit * who, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (who && who->GetEntry() == NPC_GUARDIAN_OF_YS && !_secondPhase)
            {
                damage = 25000;
                // START PHASE 2
                if (me->GetHealth() <= damage)
                {
                    _secondPhase = true;
                    damage = 0;
                    events.SetPhase(EVENT_PHASE_TWO);
                    me->SetHealth(me->GetMaxHealth());
                    if (Creature* cr = me->SummonCreature(NPC_YOGG_SARON, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), M_PI))
                        cr->SetVisible(false);
                    _p2TalkTimer++;
                    me->Yell("I am the lucid dream.", LANG_UNIVERSAL);
                    me->PlayDirectSound(SARA_P2_START);
                }
                return;
            }
            damage = 0;
        }
References _p2TalkTimer, _secondPhase, EVENT_PHASE_TWO, Object::GetEntry(), Unit::GetHealth(), Unit::GetMaxHealth(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), LANG_UNIVERSAL, ScriptedAI::me, NPC_GUARDIAN_OF_YS, NPC_YOGG_SARON, WorldObject::PlayDirectSound(), SARA_P2_START, Unit::SetHealth(), WorldObject::SummonCreature(), and Unit::Yell().
DoAction()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_BRAIN_DAMAGED)
            {
                summons.DoAction(ACTION_REMOVE_STUN);
                EntryCheckPredicate pred2(NPC_YOGG_SARON);
                summons.DoAction(ACTION_YOGG_SARON_START_P3, pred2);
                EntryCheckPredicate pred3(NPC_THORIM_KEEPER);
                summons.DoAction(ACTION_THORIM_START_STORM, pred3);
                if (!(_keepersGUID[0] && _keepersGUID[1] && _keepersGUID[2] && _keepersGUID[3]) && me->GetMap()->Is25ManRaid())
                    summons.DoAction(ACTION_YOGG_SARON_HARD_MODE, pred2);
                summons.DespawnEntry(NPC_DEATH_ORB);
                events.SetPhase(EVENT_PHASE_THREE);
                me->RemoveAllAuras();
                me->SetVisible(false);
                return;
            }
            else if (param == ACTION_YOGG_SARON_DEATH)
            {
                summons.DespawnEntry(NPC_VOICE_OF_YOGG_SARON);
                summons.DespawnEntry(NPC_BRAIN_OF_YOGG_SARON);
                summons.DespawnEntry(NPC_MIMIRON_KEEPER);
                summons.DespawnEntry(NPC_HODIR_KEEPER);
                summons.DespawnEntry(NPC_FREYA_KEEPER);
                summons.DespawnEntry(NPC_THORIM_KEEPER);
                summons.DespawnEntry(NPC_SANITY_WELL);
                Unit::Kill(me, me);
                return;
            }
            // Determine shatter duration
            if (param <= 0)
                return;
            // Illusion shatters (param - stun time)
            WorldPacket data;
            ChatHandler::BuildChatPacket(data, CHAT_MSG_RAID_BOSS_EMOTE, LANG_UNIVERSAL, me, nullptr, "Illusion shatters and a path to the central chamber opens!");
            me->SendMessageToSetInRange(&data, 500, false);
            uint32 timer = events.GetNextEventTime(EVENT_SARA_P2_OPEN_PORTALS);
            uint32 portalTime = (timer > events.GetTimer() ? timer - events.GetTimer() : 0);
            events.DelayEvents(param + 100);
            events.RescheduleEvent(EVENT_SARA_P2_OPEN_PORTALS, portalTime, 0, EVENT_PHASE_TWO);
            events.ScheduleEvent(EVENT_SARA_P2_REMOVE_STUN, param, 0, EVENT_PHASE_TWO);
            me->CastSpell(me, SPELL_SHATTERED_ILLUSION, true);
        }
References _keepersGUID, ACTION_BRAIN_DAMAGED, ACTION_REMOVE_STUN, ACTION_THORIM_START_STORM, ACTION_YOGG_SARON_DEATH, ACTION_YOGG_SARON_HARD_MODE, ACTION_YOGG_SARON_START_P3, ChatHandler::BuildChatPacket(), Unit::CastSpell(), CHAT_MSG_RAID_BOSS_EMOTE, SummonList::DespawnEntry(), SummonList::DoAction(), EVENT_PHASE_THREE, EVENT_PHASE_TWO, EVENT_SARA_P2_OPEN_PORTALS, EVENT_SARA_P2_REMOVE_STUN, WorldObject::GetMap(), Map::Is25ManRaid(), Unit::Kill(), LANG_UNIVERSAL, ScriptedAI::me, NPC_BRAIN_OF_YOGG_SARON, NPC_DEATH_ORB, NPC_FREYA_KEEPER, NPC_HODIR_KEEPER, NPC_MIMIRON_KEEPER, NPC_SANITY_WELL, NPC_THORIM_KEEPER, NPC_VOICE_OF_YOGG_SARON, NPC_YOGG_SARON, Unit::RemoveAllAuras(), WorldObject::SendMessageToSetInRange(), Unit::SetVisible(), SPELL_SHATTERED_ILLUSION, and summons.
EnableSara()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnableSara (bool apply) inline
        {
            if (apply)
            {
                me->RemoveUnitFlag(UNIT_FLAG_DISABLE_MOVE);
                me->DisableRotate(false);
                me->ClearUnitState(UNIT_STATE_ROOT);
            }
            else
            {
                me->SetUnitFlag(UNIT_FLAG_DISABLE_MOVE);
                me->DisableRotate(true);
                me->AddUnitState(UNIT_STATE_ROOT);
            }
        }
References Unit::AddUnitState(), Unit::ClearUnitState(), Unit::DisableRotate(), ScriptedAI::me, Unit::RemoveUnitFlag(), Unit::SetUnitFlag(), UNIT_FLAG_DISABLE_MOVE, and UNIT_STATE_ROOT.
Referenced by Reset().
EnterEvadeMode()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!_EnterEvadeMode(why))
                return;
            Position pos;
            pos = me->GetHomePosition();
            me->NearTeleportTo(pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), pos.GetOrientation());
            Reset();
            me->setActive(false);
        }
References CreatureAI::_EnterEvadeMode(), Creature::GetHomePosition(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, Unit::NearTeleportTo(), Reset(), and WorldObject::setActive().
Referenced by UpdateAI().
GetData()
uint32 boss_yoggsaron_sara::boss_yoggsaron_saraAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_GET_KEEPERS_COUNT)
            {
                uint8 _count = 0;
                for (uint8 i = 0; i < 4; ++i)
                    if (_keepersGUID[i])
                        ++_count;
                return _count;
            }
            else if (param == DATA_GET_SARA_PHASE)
                return _secondPhase;
            return 4; // just to be sure, return max numer of keepers
        }
References _keepersGUID, _secondPhase, DATA_GET_KEEPERS_COUNT, and DATA_GET_SARA_PHASE.
InformCloud()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud () inline
        {
            Creature* cloud = nullptr;
            for (SummonList::const_iterator itr = summons.begin(); itr != summons.end();)
            {
                Creature* summon = ObjectAccessor::GetCreature(*me, *itr);
                ++itr;
                if (!summon || summon->GetEntry() != NPC_OMINOUS_CLOUD || me->GetDistance(summon) < 20)
                    continue;
                if ((!cloud || (urand(0, 1) && !summon->HasAura(SPELL_SUMMON_GUARDIAN_OF_YS))))
                    cloud = summon;
            }
            if (cloud)
                cloud->AI()->DoAction(ACTION_START_SUMMONING);
        }
References ACTION_START_SUMMONING, Creature::AI(), SummonList::begin(), UnitAI::DoAction(), SummonList::end(), ObjectAccessor::GetCreature(), WorldObject::GetDistance(), Object::GetEntry(), Unit::HasAura(), ScriptedAI::me, NPC_OMINOUS_CLOUD, SPELL_SUMMON_GUARDIAN_OF_YS, summons, and urand().
Referenced by UpdateAI().
InitFight()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::InitFight (Unit * target) inline
        {
            if (!m_pInstance)
                return;
            // some simple hack checks
            if (m_pInstance->GetData(TYPE_VEZAX) != DONE || m_pInstance->GetData(TYPE_XT002) != DONE)
                return;
            m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, CRITERIA_NOT_GETTING_OLDER);
            m_pInstance->SetData(TYPE_YOGGSARON, IN_PROGRESS);
            me->SetInCombatWithZone();
            AttackStart(target);
            me->CastSpell(me, SPELL_SANITY_BASE, true);
            SaveKeepers();
            events.ScheduleEvent(EVENT_SARA_P1_DOORS_CLOSE, 15000, 0, EVENT_PHASE_ONE);
            events.ScheduleEvent(EVENT_SARA_P1_BERSERK, 900000, 0, 0);
            events.ScheduleEvent(EVENT_SARA_P1_SUMMON, 0, 0, EVENT_PHASE_ONE);
            events.SetPhase(EVENT_PHASE_ONE);
            me->Yell("The time to strike at the head of the beast will soon be upon us! Focus your anger and hatred on his minions!", LANG_UNIVERSAL);
            me->PlayDirectSound(SARA_AGGRO);
            me->setActive(true);
        }
References ACHIEVEMENT_TIMED_TYPE_EVENT, AttackStart(), Unit::CastSpell(), CRITERIA_NOT_GETTING_OLDER, DONE, InstanceScript::DoStartTimedAchievement(), EVENT_PHASE_ONE, EVENT_SARA_P1_BERSERK, EVENT_SARA_P1_DOORS_CLOSE, EVENT_SARA_P1_SUMMON, ZoneScript::GetData(), IN_PROGRESS, LANG_UNIVERSAL, m_pInstance, ScriptedAI::me, WorldObject::PlayDirectSound(), SARA_AGGRO, SaveKeepers(), WorldObject::setActive(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), SPELL_SANITY_BASE, TYPE_VEZAX, TYPE_XT002, TYPE_YOGGSARON, and Unit::Yell().
Referenced by UpdateAI().
JustSummoned()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(cr);
            if (cr->GetEntry() >= NPC_FREYA_KEEPER && cr->GetEntry() <= NPC_THORIM_KEEPER)
            {
                if (cr->GetEntry() == NPC_FREYA_KEEPER)
                    cr->CastSpell(cr, SPELL_CONJURE_SANITY_WELL, false);
                _keepersGUID[cr->GetEntry() - NPC_FREYA_KEEPER] = cr->GetGUID();
            }
            else if (cr->GetEntry() == NPC_SANITY_WELL)
                cr->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_SCALE, true);
        }
References _keepersGUID, Unit::ApplySpellImmune(), Unit::CastSpell(), Object::GetEntry(), Object::GetGUID(), IMMUNITY_STATE, NPC_FREYA_KEEPER, NPC_SANITY_WELL, NPC_THORIM_KEEPER, SPELL_AURA_MOD_SCALE, SPELL_CONJURE_SANITY_WELL, SummonList::Summon(), and summons.
KilledUnit()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (who->GetTypeId() != TYPEID_PLAYER)
                return;
            if (urand(0, 1))
            {
                me->Yell("Could they have been saved?", LANG_UNIVERSAL);
                me->PlayDirectSound(SARA_P1_KILL2);
            }
            else
            {
                me->Yell("Powerless to act...", LANG_UNIVERSAL);
                me->PlayDirectSound(SARA_P1_KILL1);
            }
        }
References Object::GetTypeId(), LANG_UNIVERSAL, ScriptedAI::me, WorldObject::PlayDirectSound(), SARA_P1_KILL1, SARA_P1_KILL2, TYPEID_PLAYER, urand(), and Unit::Yell().
MoveInLineOfSight()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{ }
Reset()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.DoAction(ACTION_DESPAWN_ADDS);
            events.Reset();
            summons.DespawnAll();
            me->SetVisible(true);
            me->SetDisplayId(me->GetNativeDisplayId());
            me->SetDisableGravity(true);
            EnableSara(false);
            SpawnClouds();
            _initFight = 1;
            for (uint8 i = 0; i < 4; ++i)
                _keepersGUID[i].Clear();
            _summonedGuardiansCount = 0;
            _p2TalkTimer = 0;
            _secondPhase = false;
            _summonSpeed = 1.0f;
            _currentIllusion = urand(1, 3);
            _isIllusionReversed = urand(0, 1);
            if (m_pInstance)
            {
                m_pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, CRITERIA_NOT_GETTING_OLDER);
                m_pInstance->DoRemoveAurasDueToSpellOnPlayers(SPELL_SANITY);
                m_pInstance->SetData(TYPE_YOGGSARON, NOT_STARTED);
                if (GameObject* go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_YOGG_SARON_DOORS)))
                    go->SetGoState(GO_STATE_ACTIVE);
            }
        }
References _currentIllusion, _initFight, _isIllusionReversed, _keepersGUID, _p2TalkTimer, _secondPhase, _summonedGuardiansCount, _summonSpeed, ACHIEVEMENT_TIMED_TYPE_EVENT, ACTION_DESPAWN_ADDS, CRITERIA_NOT_GETTING_OLDER, SummonList::DespawnAll(), SummonList::DoAction(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), InstanceScript::DoStopTimedAchievement(), EnableSara(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), Unit::GetNativeDisplayId(), GO_STATE_ACTIVE, GO_YOGG_SARON_DOORS, m_pInstance, ScriptedAI::me, NOT_STARTED, ZoneScript::SetData(), Creature::SetDisableGravity(), Creature::SetDisplayId(), Unit::SetVisible(), SpawnClouds(), SPELL_SANITY, summons, TYPE_YOGGSARON, and urand().
Referenced by EnterEvadeMode().
SaveKeepers()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SaveKeepers () inline
        {
            for (uint8 i = 0; i < 4; ++i)
                if (m_pInstance->GetData(TYPE_WATCHERS) & (1 << i))
                    switch (i)
                    {
                        case KEEPER_FREYA:
                            SpawnWeels();
                            me->SummonCreature(NPC_FREYA_KEEPER, 1939.32f, 42.165f, 338.415f, 5.17955f);
                            break;
                        case KEEPER_HODIR:
                            me->SummonCreature(NPC_HODIR_KEEPER, 1939.13f, -90.8332f, 338.415f, 1.00123f);
                            break;
                        case KEEPER_MIMIRON:
                            me->SummonCreature(NPC_MIMIRON_KEEPER, 2036.81f, 25.6646f, 338.415f, 3.74227f);
                            break;
                        case KEEPER_THORIM:
                            me->SummonCreature(NPC_THORIM_KEEPER, 2036.59f, -73.8499f, 338.415f, 2.34819f);
                            break;
                    }
        }
References ZoneScript::GetData(), KEEPER_FREYA, KEEPER_HODIR, KEEPER_MIMIRON, KEEPER_THORIM, m_pInstance, ScriptedAI::me, NPC_FREYA_KEEPER, NPC_HODIR_KEEPER, NPC_MIMIRON_KEEPER, NPC_THORIM_KEEPER, SpawnWeels(), WorldObject::SummonCreature(), and TYPE_WATCHERS.
Referenced by InitFight().
SpawnClouds()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnClouds () inline
        {
            for (uint8 i = 0; i < 6; ++i)
            {
                float Zplus = i > 2 ? (i - 2) * 1.6f : 0;
                if (i % 2)
                    me->SummonCreature(NPC_OMINOUS_CLOUD, me->GetPositionX() + 8 + i * 7, me->GetPositionY() + 8 + i * 7, 326 + Zplus, 0);
                else
                    me->SummonCreature(NPC_OMINOUS_CLOUD, me->GetPositionX() - 8 - i * 7, me->GetPositionY() - 8 - i * 7, 326 + Zplus, 0);
            }
        }
References Position::GetPositionX(), Position::GetPositionY(), ScriptedAI::me, NPC_OMINOUS_CLOUD, and WorldObject::SummonCreature().
Referenced by Reset().
SpawnTentacle()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnTentacle (uint32 entry) inline
        {
            uint32 dist = urand(38, 48);
            float o = rand_norm() * M_PI * 2;
            float Zplus = (dist - 38) / 6.5f;
            if (Creature* cr = me->SummonCreature(entry, me->GetPositionX() + dist * cos(o), me->GetPositionY() + dist * std::sin(o), 327.2 + Zplus, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000))
            {
                cr->CastSpell(cr, SPELL_TENTACLE_ERUPT, true);
                cr->CastSpell(cr, SPELL_VOID_ZONE_SMALL, true);
                cr->HandleEmoteCommand(EMOTE_ONESHOT_EMERGE);
            }
        }
References EMOTE_ONESHOT_EMERGE, Position::GetPositionX(), Position::GetPositionY(), ScriptedAI::me, rand_norm(), SPELL_TENTACLE_ERUPT, SPELL_VOID_ZONE_SMALL, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
SpawnWeels()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnWeels () inline
        {
            me->SummonCreature(NPC_SANITY_WELL, 2042.56f, -40.3667f, 329.274f, 0.0f);
            me->SummonCreature(NPC_SANITY_WELL, 1975.89f, 40.0216f, 331.1f, 0.0f);
            me->SummonCreature(NPC_SANITY_WELL, 1987.12f, -91.2702f, 330.186f, 0.0f);
            me->SummonCreature(NPC_SANITY_WELL, 1900.48f, -51.2386f, 332.13f, 0.0f);
            me->SummonCreature(NPC_SANITY_WELL, 1899.94f, 0.330621f, 332.296f, 0.0f);
        }
References ScriptedAI::me, NPC_SANITY_WELL, and WorldObject::SummonCreature().
Referenced by SaveKeepers().
SpellHitTarget()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpellHitTarget (Unit * target, SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_SANITY)
                if (Aura* aur = target->GetAura(SPELL_SANITY))
                    aur->SetStackAmount(100);
        }
References Unit::GetAura(), SpellInfo::Id, and SPELL_SANITY.
SpellSounds()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpellSounds () inline
        {
            if (urand(0, 9))
                return;
            if (urand(0, 1))
            {
                me->Yell(_secondPhase ? "Tremble, mortals, before the coming of the end!" : "Yes! YES! Show them no mercy! Give no pause to your attacks!", LANG_UNIVERSAL);
                me->PlayDirectSound(_secondPhase ? SARA_P2_CAST2 : SARA_P1_CAST1);
            }
            else
            {
                me->Yell(_secondPhase ? "Suffocate upon your own hate!" : "Let hatred and rage guide your blows!", LANG_UNIVERSAL);
                me->PlayDirectSound(_secondPhase ? SARA_P2_CAST1 : SARA_P1_CAST2);
            }
        }
References _secondPhase, LANG_UNIVERSAL, ScriptedAI::me, WorldObject::PlayDirectSound(), SARA_P1_CAST1, SARA_P1_CAST2, SARA_P2_CAST1, SARA_P2_CAST2, urand(), and Unit::Yell().
Referenced by UpdateAI().
SummonDeathOrbs()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SummonDeathOrbs () inline
        {
            for (uint8 i = 0; i < 4; ++i)
            {
                uint32 dist = urand(38, 48);
                float o = rand_norm() * M_PI * 2;
                float Zplus = (dist - 38) / 6.5f;
                me->SummonCreature(NPC_DEATH_ORB, me->GetPositionX() + dist * cos(o), me->GetPositionY() + dist * std::sin(o), 327.2 + Zplus, 0, TEMPSUMMON_TIMED_DESPAWN, 20000);
            }
        }
References Position::GetPositionX(), Position::GetPositionY(), ScriptedAI::me, NPC_DEATH_ORB, rand_norm(), WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (_initFight)
            {
                _initFight += diff;
                if (_initFight > 5000)
                {
                    if (Unit* target = SelectTargetFromPlayerList(90))
                    {
                        _initFight = 0;
                        InitFight(target);
                    }
                    else
                        _initFight = 1;
                }
                return;
            }
            if (!SelectTargetFromPlayerList(90, SPELL_INSANE1))
            {
                m_pInstance->DoRemoveAurasDueToSpellOnPlayers(SPELL_INSANE1);
                EnterEvadeMode(EVADE_REASON_OTHER);
                return;
            }
            if (_p2TalkTimer)
            {
                _p2TalkTimer += diff;
                if (_p2TalkTimer >= 4000 && _p2TalkTimer < 20000)
                {
                    EntryCheckPredicate pred(NPC_OMINOUS_CLOUD);
                    summons.DoAction(ACTION_UNSUMMON_CLOUDS, pred);
                    me->Yell("The monster in your nightmares.", LANG_UNIVERSAL);
                    _p2TalkTimer = 20000;
                }
                else if (_p2TalkTimer >= 25000 && _p2TalkTimer < 40000)
                {
                    summons.DespawnEntry(NPC_OMINOUS_CLOUD);
                    me->Yell("The fiend of a thousand faces.", LANG_UNIVERSAL);
                    _p2TalkTimer = 40000;
                }
                else if (_p2TalkTimer >= 44500 && _p2TalkTimer < 60000)
                {
                    me->Yell("Cower before my true form.", LANG_UNIVERSAL);
                    _p2TalkTimer = 60000;
                }
                else if (_p2TalkTimer >= 64000)
                {
                    EntryCheckPredicate pred(NPC_YOGG_SARON);
                    summons.DoAction(ACTION_YOGG_SARON_START_YELL, pred);
                    _p2TalkTimer = 0;
                    events.ScheduleEvent(EVENT_SARA_P2_START, 500, 0, EVENT_PHASE_TWO);
                }
                return;
            }
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch(events.ExecuteEvent())
            {
                case EVENT_SARA_P1_DOORS_CLOSE:
                    // Whispers of YS
                    me->SummonCreature(NPC_VOICE_OF_YOGG_SARON, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                    if (m_pInstance)
                        if (GameObject* go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_YOGG_SARON_DOORS)))
                            go->SetGoState(GO_STATE_READY);
                    events.ScheduleEvent(EVENT_SARA_P1_SPELLS, 0, 1, EVENT_PHASE_ONE);
                    break;
                case EVENT_SARA_P1_SUMMON:
                    events.RepeatEvent(20000 - (std::min(_summonedGuardiansCount, (uint8)5) * 2000));
                    ++_summonedGuardiansCount;
                    InformCloud();
                    break;
                case EVENT_SARA_P1_SPELLS:
                    {
                        uint32 spell = RAND(SPELL_SARAS_ANGER_TARGET_SELECTOR, SPELL_SARAS_BLESSING_TARGET_SELECTOR, SPELL_SARAS_FAVOR_TARGET_SELECTOR);
                        me->CastCustomSpell(spell, SPELLVALUE_MAX_TARGETS, 1, nullptr, false);
                        SpellSounds();
                        events.RepeatEvent(me->GetMap()->Is25ManRaid() ? urand(0, 3000) : 4000 + urand(0, 2000));
                        break;
                    }
                case EVENT_SARA_P2_START:
                    {
                        EntryCheckPredicate pred(NPC_YOGG_SARON);
                        summons.DoAction(ACTION_YOGG_SARON_APPEAR, pred);
                        events.RescheduleEvent(EVENT_SARA_P2_SPAWN_START_TENTACLES, 500, 0, EVENT_PHASE_TWO);
                        // Spawn Brain!
                        me->SummonCreature(NPC_BRAIN_OF_YOGG_SARON, 1981.3f, -25.43f, 265);
                        break;
                    }
                case EVENT_SARA_P2_MALADY:
                    me->CastCustomSpell(SPELL_MALADY_OF_THE_MIND, SPELLVALUE_MAX_TARGETS, 1, me, false);
                    events.RepeatEvent(20000);
                    break;
                case EVENT_SARA_P2_PSYCHOSIS:
                    SpellSounds();
                    me->CastCustomSpell(SPELL_PSYCHOSIS, SPELLVALUE_MAX_TARGETS, 1, me, false);
                    events.RepeatEvent(3500);
                    break;
                case EVENT_SARA_P2_DEATH_RAY:
                    SummonDeathOrbs();
                    events.RepeatEvent(20000);
                    break;
                case EVENT_SARA_P2_SUMMON_T1: // CRUSHER
                    SpawnTentacle(NPC_CRUSHER_TENTACLE);
                    events.RepeatEvent((50000 + urand(0, 10000)) * _summonSpeed);
                    break;
                case EVENT_SARA_P2_SUMMON_T2: // CONSTRICTOR
                    SpawnTentacle(NPC_CONSTRICTOR_TENTACLE);
                    events.RepeatEvent((15000 + urand(0, 5000)) * _summonSpeed);
                    break;
                case EVENT_SARA_P2_SUMMON_T3: // CORRUPTOR
                    SpawnTentacle(NPC_CORRUPTOR_TENTACLE);
                    events.RepeatEvent((30000 + urand(0, 10000)) * _summonSpeed);
                    break;
                case EVENT_SARA_P2_BRAIN_LINK:
                    me->CastCustomSpell(SPELL_BRAIN_LINK, SPELLVALUE_MAX_TARGETS, 1, me, false);
                    events.RepeatEvent(30000);
                    break;
                case EVENT_SARA_P2_OPEN_PORTALS:
                    {
                        AddPortals();
                        EntryCheckPredicate pred(NPC_YOGG_SARON);
                        summons.DoAction(ACTION_YOGG_SARON_OPEN_PORTAL_YELL, pred);
                        events.RepeatEvent(80000);
                        break;
                    }
                case EVENT_SARA_P2_REMOVE_STUN:
                    {
                        me->RemoveAura(SPELL_SHATTERED_ILLUSION);
                        summons.DoAction(ACTION_REMOVE_STUN);
                        break;
                    }
                case EVENT_SARA_P2_SPAWN_START_TENTACLES:
                    me->SetOrientation(M_PI);
                    me->SetDisplayId(SARA_TRANSFORM_MODEL);
                    me->SendMonsterMove(me->GetPositionX(), me->GetPositionY(), 355, 2000, SPLINEFLAG_FLYING);
                    me->SetPosition(me->GetPositionX(), me->GetPositionY(), 355, me->GetOrientation());
                    SpawnTentacle(NPC_CRUSHER_TENTACLE);
                    SpawnTentacle(NPC_CONSTRICTOR_TENTACLE);
                    SpawnTentacle(NPC_CORRUPTOR_TENTACLE);
                    SpawnTentacle(NPC_CORRUPTOR_TENTACLE);
                    events.ScheduleEvent(EVENT_SARA_P2_MALADY, 7000, 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_PSYCHOSIS, 3000, 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_DEATH_RAY, 15000, 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_SUMMON_T1, 50000 + urand(0, 10000), 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_SUMMON_T2, 15000 + urand(0, 5000), 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_SUMMON_T3, 30000 + urand(0, 10000), 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_BRAIN_LINK, 0, 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_OPEN_PORTALS, 60000, 0, EVENT_PHASE_TWO);
                    break;
                case EVENT_SARA_P1_BERSERK:
                    me->CastSpell(me, SPELL_EXTINGUISH_ALL_LIFE, true);
                    events.RepeatEvent(5000);
                    break;
            }
        }
References _initFight, _p2TalkTimer, _summonedGuardiansCount, _summonSpeed, ACTION_REMOVE_STUN, ACTION_UNSUMMON_CLOUDS, ACTION_YOGG_SARON_APPEAR, ACTION_YOGG_SARON_OPEN_PORTAL_YELL, ACTION_YOGG_SARON_START_YELL, AddPortals(), Unit::CastCustomSpell(), Unit::CastSpell(), SummonList::DespawnEntry(), SummonList::DoAction(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_PHASE_ONE, EVENT_PHASE_TWO, EVENT_SARA_P1_BERSERK, EVENT_SARA_P1_DOORS_CLOSE, EVENT_SARA_P1_SPELLS, EVENT_SARA_P1_SUMMON, EVENT_SARA_P2_BRAIN_LINK, EVENT_SARA_P2_DEATH_RAY, EVENT_SARA_P2_MALADY, EVENT_SARA_P2_OPEN_PORTALS, EVENT_SARA_P2_PSYCHOSIS, EVENT_SARA_P2_REMOVE_STUN, EVENT_SARA_P2_SPAWN_START_TENTACLES, EVENT_SARA_P2_START, EVENT_SARA_P2_SUMMON_T1, EVENT_SARA_P2_SUMMON_T2, EVENT_SARA_P2_SUMMON_T3, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_STATE_READY, GO_YOGG_SARON_DOORS, Unit::HasUnitState(), InformCloud(), InitFight(), Map::Is25ManRaid(), LANG_UNIVERSAL, m_pInstance, ScriptedAI::me, NPC_BRAIN_OF_YOGG_SARON, NPC_CONSTRICTOR_TENTACLE, NPC_CORRUPTOR_TENTACLE, NPC_CRUSHER_TENTACLE, NPC_OMINOUS_CLOUD, NPC_VOICE_OF_YOGG_SARON, NPC_YOGG_SARON, RAND(), Unit::RemoveAura(), SARA_TRANSFORM_MODEL, ScriptedAI::SelectTargetFromPlayerList(), Unit::SendMonsterMove(), Creature::SetDisplayId(), Position::SetOrientation(), Creature::SetPosition(), SpawnTentacle(), SPELL_BRAIN_LINK, SPELL_EXTINGUISH_ALL_LIFE, SPELL_INSANE1, SPELL_MALADY_OF_THE_MIND, SPELL_PSYCHOSIS, SPELL_SARAS_ANGER_TARGET_SELECTOR, SPELL_SARAS_BLESSING_TARGET_SELECTOR, SPELL_SARAS_FAVOR_TARGET_SELECTOR, SPELL_SHATTERED_ILLUSION, SpellSounds(), SPELLVALUE_MAX_TARGETS, SPLINEFLAG_FLYING, WorldObject::SummonCreature(), SummonDeathOrbs(), summons, UNIT_STATE_CASTING, urand(), and Unit::Yell().
Member Data Documentation
_currentIllusion
uint8 boss_yoggsaron_sara::boss_yoggsaron_saraAI::_currentIllusion
Referenced by AddPortals(), and Reset().
_initFight
uint32 boss_yoggsaron_sara::boss_yoggsaron_saraAI::_initFight
Referenced by Reset(), and UpdateAI().
_isIllusionReversed
bool boss_yoggsaron_sara::boss_yoggsaron_saraAI::_isIllusionReversed
Referenced by AddPortals(), and Reset().
_keepersGUID
ObjectGuid boss_yoggsaron_sara::boss_yoggsaron_saraAI::_keepersGUID[4]
Referenced by DoAction(), GetData(), JustSummoned(), and Reset().
_p2TalkTimer
uint32 boss_yoggsaron_sara::boss_yoggsaron_saraAI::_p2TalkTimer
Referenced by DamageTaken(), Reset(), and UpdateAI().
_secondPhase
bool boss_yoggsaron_sara::boss_yoggsaron_saraAI::_secondPhase
Referenced by DamageTaken(), GetData(), Reset(), and SpellSounds().
_summonedGuardiansCount
uint8 boss_yoggsaron_sara::boss_yoggsaron_saraAI::_summonedGuardiansCount
Referenced by Reset(), and UpdateAI().
_summonSpeed
float boss_yoggsaron_sara::boss_yoggsaron_saraAI::_summonSpeed
Referenced by AddPortals(), Reset(), and UpdateAI().
events
EventMap boss_yoggsaron_sara::boss_yoggsaron_saraAI::events
m_pInstance
InstanceScript* boss_yoggsaron_sara::boss_yoggsaron_saraAI::m_pInstance
Referenced by boss_yoggsaron_saraAI(), InitFight(), Reset(), SaveKeepers(), and UpdateAI().
summons
SummonList boss_yoggsaron_sara::boss_yoggsaron_saraAI::summons
Referenced by AddPortals(), DoAction(), InformCloud(), JustSummoned(), Reset(), and UpdateAI().