AzerothCore: AchievementCriteriaDataSet Struct Reference
AchievementCriteriaDataSet Struct Reference
#include "AchievementMgr.h"
Public Types
typedef std::vector< AchievementCriteriaData > Storage
Public Member Functions
AchievementCriteriaDataSet ()=default
void Add (AchievementCriteriaData const &data)
bool Meets (Player const *source, Unit const *target, uint32 miscvalue=0) const
void SetCriteriaId (uint32 id)
Private Attributes
uint32 _criteria_id {0}
Storage _storage
Detailed Description
Member Typedef Documentation
Storage
typedef std::vector<AchievementCriteriaData> AchievementCriteriaDataSet::Storage
Constructor & Destructor Documentation
AchievementCriteriaDataSet()
AchievementCriteriaDataSet::AchievementCriteriaDataSet () default
Member Function Documentation
Add()
void AchievementCriteriaDataSet::Add (AchievementCriteriaData const & data) inline
{ _storage.push_back(data); }
References _storage.
Referenced by AchievementGlobalMgr::LoadAchievementCriteriaData().
Meets()
bool AchievementCriteriaDataSet::Meets (Player const * source, Unit const * target, uint32 miscvalue = 0) const
{
    for (Storage::const_iterator itr = _storage.begin(); itr != _storage.end(); ++itr)
        if (!itr->Meets(_criteria_id, source, target, miscvalue))
            return false;
    return true;
}
References _criteria_id, and _storage.
Referenced by AchievementMgr::UpdateAchievementCriteria().
SetCriteriaId()
void AchievementCriteriaDataSet::SetCriteriaId (uint32 id) inline
{_criteria_id = id;}
References _criteria_id.
Referenced by AchievementGlobalMgr::LoadAchievementCriteriaData().
Member Data Documentation
_criteria_id
uint32 AchievementCriteriaDataSet::_criteria_id {0} private
Referenced by Meets(), and SetCriteriaId().
_storage
Storage AchievementCriteriaDataSet::_storage private
Referenced by Add(), and Meets().