AzerothCore: npc_warden_mellichar::npc_warden_mellicharAI Struct Reference
npc_warden_mellichar::npc_warden_mellicharAI Struct Reference
Public Member Functions
npc_warden_mellicharAI (Creature *creature)
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void Reset () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void SetData (uint32 type, uint32 data) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_warden_mellicharAI()
npc_warden_mellichar::npc_warden_mellicharAI::npc_warden_mellicharAI (Creature * creature) inline
                                                   : BossAI(creature, DATA_WARDEN_MELLICHAR)
        {
        }
Member Function Documentation
AttackStart()
void npc_warden_mellichar::npc_warden_mellicharAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
{ }
Referenced by UpdateAI().
DamageTaken()
void npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
        {
            if (attacker && attacker->GetCharmerOrOwnerOrOwnGUID().IsPlayer() && damage > 0 && !me->isActiveObject())
            {
                me->setActive(true);
                me->InterruptNonMeleeSpells(false);
                me->SetImmuneToAll(true);
                events.ScheduleEvent(EVENT_WARDEN_INTRO1, 1500);
                events.ScheduleEvent(EVENT_WARDEN_CHECK_PLAYERS, 1000);
                instance->SetBossState(DATA_WARDEN_MELLICHAR, IN_PROGRESS);
            }
            damage = 0;
        }
References DATA_WARDEN_MELLICHAR, EVENT_WARDEN_CHECK_PLAYERS, EVENT_WARDEN_INTRO1, Unit::GetCharmerOrOwnerOrOwnGUID(), IN_PROGRESS, BossAI::instance, Unit::InterruptNonMeleeSpells(), WorldObject::isActiveObject(), ObjectGuid::IsPlayer(), ScriptedAI::me, WorldObject::setActive(), InstanceScript::SetBossState(), and Unit::SetImmuneToAll().
JustDied()
void npc_warden_mellichar::npc_warden_mellicharAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            me->setActive(false);
        }
References ScriptedAI::me, and WorldObject::setActive().
JustEngagedWith()
void npc_warden_mellichar::npc_warden_mellicharAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
{ }
JustSummoned()
void npc_warden_mellichar::npc_warden_mellicharAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            summons.Summon(summon);
        }
References SummonList::Summon(), and BossAI::summons.
MoveInLineOfSight()
void npc_warden_mellichar::npc_warden_mellicharAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{ }
Reset()
void npc_warden_mellichar::npc_warden_mellicharAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            _Reset();
            me->setActive(false);
            me->SetImmuneToAll(false);
            me->RemoveDynamicFlag(UNIT_DYNFLAG_DEAD);
            me->RemoveUnitFlag2(UNIT_FLAG2_FEIGN_DEATH);
            me->CastSpell((Unit*)nullptr, SPELL_TARGET_OMEGA, false);
            instance->HandleGameObject(instance->GetGuidData(DATA_WARDENS_SHIELD), true);
            instance->SetBossState(DATA_WARDEN_MELLICHAR, NOT_STARTED);
        }
References BossAI::_Reset(), Unit::CastSpell(), DATA_WARDEN_MELLICHAR, DATA_WARDENS_SHIELD, InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), BossAI::instance, ScriptedAI::me, NOT_STARTED, Object::RemoveDynamicFlag(), Unit::RemoveUnitFlag2(), WorldObject::setActive(), InstanceScript::SetBossState(), Unit::SetImmuneToAll(), SPELL_TARGET_OMEGA, UNIT_DYNFLAG_DEAD, and UNIT_FLAG2_FEIGN_DEATH.
SetData()
void npc_warden_mellichar::npc_warden_mellicharAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
        {
            if (data == FAIL)
            {
                CreatureAI::EnterEvadeMode();
                return;
            }
            if (data != DONE)
                return;
            switch (type)
            {
                case DATA_WARDEN_1:
                    events.ScheduleEvent(EVENT_WARDEN_INTRO8, 2000);
                    break;
                case DATA_WARDEN_3:
                    events.ScheduleEvent(EVENT_WARDEN_INTRO19, 2000);
                    break;
                case DATA_WARDEN_4:
                    events.ScheduleEvent(EVENT_WARDEN_INTRO24, 2000);
                    break;
            }
        }
References DATA_WARDEN_1, DATA_WARDEN_3, DATA_WARDEN_4, DONE, CreatureAI::EnterEvadeMode(), EVENT_WARDEN_INTRO19, EVENT_WARDEN_INTRO24, EVENT_WARDEN_INTRO8, and FAIL.
SummonedCreatureDies()
void npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            if (summon->GetEntry() == NPC_HARBINGER_SKYRISS)
            {
                me->KillSelf();
                me->setActive(false);
                instance->SetBossState(DATA_WARDEN_MELLICHAR, DONE);
                if (Creature* creature = summons.GetCreatureWithEntry(NPC_MILLHOUSE))
                {
                    if (IsHeroic())
                    {
                        instance->DoCastSpellOnPlayers(SPELL_QID10886);
                    }
                    creature->AI()->Talk(SAY_COMPLETE);
                    creature->ReplaceAllNpcFlags(UNIT_NPC_FLAG_GOSSIP);
                }
            }
        }
References DATA_WARDEN_MELLICHAR, InstanceScript::DoCastSpellOnPlayers(), DONE, SummonList::GetCreatureWithEntry(), Object::GetEntry(), BossAI::instance, ScriptedAI::IsHeroic(), Unit::KillSelf(), ScriptedAI::me, NPC_HARBINGER_SKYRISS, NPC_MILLHOUSE, SAY_COMPLETE, WorldObject::setActive(), InstanceScript::SetBossState(), SPELL_QID10886, BossAI::summons, and UNIT_NPC_FLAG_GOSSIP.
UpdateAI()
void npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_WARDEN_CHECK_PLAYERS:
                    if (!SelectTargetFromPlayerList(100.0f))
                    {
                        CreatureAI::EnterEvadeMode();
                        return;
                    }
                    events.ScheduleEvent(EVENT_WARDEN_CHECK_PLAYERS, 1000);
                    break;
                case EVENT_WARDEN_INTRO1:
                    Talk(YELL_INTRO1);
                    me->SetFacingTo(M_PI / 2.0f);
                    me->CastSpell(me, SPELL_BUBBLE_VISUAL, false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO2, 1400);
                    break;
                case EVENT_WARDEN_INTRO2:
                    instance->HandleGameObject(instance->GetGuidData(DATA_WARDENS_SHIELD), false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO3, 20000);
                    break;
                case EVENT_WARDEN_INTRO3:
                    Talk(YELL_INTRO2);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO4, 5000);
                    break;
                case EVENT_WARDEN_INTRO4:
                    me->SetFacingTo(0.5f);
                    me->CastSpell((Unit*)nullptr, SPELL_TARGET_ALPHA, false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO5, 2000);
                    break;
                case EVENT_WARDEN_INTRO5:
                    instance->SetData(DATA_WARDEN_1, IN_PROGRESS);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO6, 3000);
                    break;
                case EVENT_WARDEN_INTRO6:
                    me->SetFacingTo(M_PI * 1.5f);
                    me->CastSpell((Unit*)nullptr, SPELL_TARGET_OMEGA, false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO7, 5000);
                    break;
                case EVENT_WARDEN_INTRO7:
                    me->SummonCreature(RAND(NPC_TRICKSTER, NPC_PH_HUNTER), 478.326f, -148.505f, 42.56f, 3.19f, TEMPSUMMON_MANUAL_DESPAWN);
                    // Wait for kill
                    break;
                case EVENT_WARDEN_INTRO8:
                    Talk(YELL_RELEASE1);
                    me->InterruptNonMeleeSpells(false);
                    me->SetFacingTo(2.6f);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO10, 4000);
                    break;
                case EVENT_WARDEN_INTRO10:
                    me->CastSpell((Unit*)nullptr, SPELL_TARGET_BETA, false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO11, 2000);
                    break;
                case EVENT_WARDEN_INTRO11:
                    Talk(YELL_RELEASE2A);
                    instance->SetData(DATA_WARDEN_2, IN_PROGRESS);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO12, 2000);
                    break;
                case EVENT_WARDEN_INTRO12:
                    me->SetFacingTo(M_PI * 1.5f);
                    me->CastSpell((Unit*)nullptr, SPELL_TARGET_OMEGA, false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO13, 6000);
                    break;
                case EVENT_WARDEN_INTRO13:
                    me->SummonCreature(NPC_MILLHOUSE, 413.292f, -148.378f, 42.56f, 6.27f, TEMPSUMMON_MANUAL_DESPAWN);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO14, 14000);
                    break;
                case EVENT_WARDEN_INTRO14:
                    Talk(YELL_RELEASE2B);
                    me->InterruptNonMeleeSpells(false);
                    me->SetFacingTo(3.3f);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO15, 5000);
                    break;
                case EVENT_WARDEN_INTRO15:
                    me->CastSpell((Unit*)nullptr, SPELL_TARGET_DELTA, false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO16, 2000);
                    break;
                case EVENT_WARDEN_INTRO16:
                    instance->SetData(DATA_WARDEN_3, IN_PROGRESS);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO17, 2000);
                    break;
                case EVENT_WARDEN_INTRO17:
                    me->SetFacingTo(M_PI * 1.5f);
                    me->CastSpell((Unit*)nullptr, SPELL_TARGET_OMEGA, false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO18, 6000);
                    break;
                case EVENT_WARDEN_INTRO18:
                    me->SummonCreature(RAND(NPC_AKKIRIS, NPC_SULFURON), 420.179f, -174.396f, 42.58f, 0.02f, TEMPSUMMON_MANUAL_DESPAWN);
                    // Wait for kill
                    break;
                case EVENT_WARDEN_INTRO19:
                    Talk(YELL_RELEASE3);
                    me->InterruptNonMeleeSpells(false);
                    me->SetFacingTo(6.05f);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO20, 4000);
                    break;
                case EVENT_WARDEN_INTRO20:
                    me->CastSpell((Unit*)nullptr, SPELL_TARGET_GAMMA, false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO21, 2000);
                    break;
                case EVENT_WARDEN_INTRO21:
                    instance->SetData(DATA_WARDEN_4, IN_PROGRESS);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO22, 2000);
                    break;
                case EVENT_WARDEN_INTRO22:
                    me->SetFacingTo(M_PI * 1.5f);
                    me->CastSpell((Unit*)nullptr, SPELL_TARGET_OMEGA, false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO23, 6000);
                    break;
                case EVENT_WARDEN_INTRO23:
                    me->SummonCreature(RAND(NPC_TW_DRAK, NPC_BL_DRAK), 471.795f, -174.58f, 42.58f, 3.06f, TEMPSUMMON_MANUAL_DESPAWN);
                    // Wait for kill
                    break;
                case EVENT_WARDEN_INTRO24:
                    instance->SetData(DATA_WARDEN_5, IN_PROGRESS);
                    Talk(YELL_RELEASE4);
                    me->InterruptNonMeleeSpells(false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO25, 8000);
                    break;
                case EVENT_WARDEN_INTRO25:
                    if (Creature* cr = me->SummonCreature(NPC_HARBINGER_SKYRISS, 445.763f, -191.639f, 44.64f, 1.60f, TEMPSUMMON_MANUAL_DESPAWN))
                    {
                        cr->SetImmuneToAll(true);
                        cr->CastSpell(cr, SPELL_TELEPORT_VISUAL, true);
                    }
                    events.ScheduleEvent(EVENT_WARDEN_INTRO26, 1000);
                    break;
                case EVENT_WARDEN_INTRO26:
                    if (Creature* creature = summons.GetCreatureWithEntry(NPC_HARBINGER_SKYRISS))
                        creature->AI()->Talk(SAY_HARBINGER_INTRO);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO27, 23000);
                    break;
                case EVENT_WARDEN_INTRO27:
                    Talk(YELL_WELCOME);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO28, 5000);
                    break;
                case EVENT_WARDEN_INTRO28:
                    instance->HandleGameObject(instance->GetGuidData(DATA_WARDENS_SHIELD), true);
                    if (Creature* creature = summons.GetCreatureWithEntry(NPC_HARBINGER_SKYRISS))
                        creature->CastSpell((Unit*)nullptr, SPELL_MIND_REND, false);
                    events.ScheduleEvent(EVENT_WARDEN_INTRO29, 4000);
                    break;
                case EVENT_WARDEN_INTRO29:
                    events.Reset();
                    me->SetDynamicFlag(UNIT_DYNFLAG_DEAD);
                    me->SetUnitFlag2(UNIT_FLAG2_FEIGN_DEATH);
                    if (Creature* creature = summons.GetCreatureWithEntry(NPC_HARBINGER_SKYRISS))
                    {
                        creature->SetImmuneToAll(false);
                        if (Player* player = SelectTargetFromPlayerList(50.0f))
                            AttackStart(player);
                    }
                    break;
            }
        }
References AttackStart(), Unit::CastSpell(), DATA_WARDEN_1, DATA_WARDEN_2, DATA_WARDEN_3, DATA_WARDEN_4, DATA_WARDEN_5, DATA_WARDENS_SHIELD, CreatureAI::EnterEvadeMode(), EVENT_WARDEN_CHECK_PLAYERS, EVENT_WARDEN_INTRO1, EVENT_WARDEN_INTRO10, EVENT_WARDEN_INTRO11, EVENT_WARDEN_INTRO12, EVENT_WARDEN_INTRO13, EVENT_WARDEN_INTRO14, EVENT_WARDEN_INTRO15, EVENT_WARDEN_INTRO16, EVENT_WARDEN_INTRO17, EVENT_WARDEN_INTRO18, EVENT_WARDEN_INTRO19, EVENT_WARDEN_INTRO2, EVENT_WARDEN_INTRO20, EVENT_WARDEN_INTRO21, EVENT_WARDEN_INTRO22, EVENT_WARDEN_INTRO23, EVENT_WARDEN_INTRO24, EVENT_WARDEN_INTRO25, EVENT_WARDEN_INTRO26, EVENT_WARDEN_INTRO27, EVENT_WARDEN_INTRO28, EVENT_WARDEN_INTRO29, EVENT_WARDEN_INTRO3, EVENT_WARDEN_INTRO4, EVENT_WARDEN_INTRO5, EVENT_WARDEN_INTRO6, EVENT_WARDEN_INTRO7, EVENT_WARDEN_INTRO8, SummonList::GetCreatureWithEntry(), InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), IN_PROGRESS, BossAI::instance, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, NPC_AKKIRIS, NPC_BL_DRAK, NPC_HARBINGER_SKYRISS, NPC_MILLHOUSE, NPC_PH_HUNTER, NPC_SULFURON, NPC_TRICKSTER, NPC_TW_DRAK, RAND(), SAY_HARBINGER_INTRO, ScriptedAI::SelectTargetFromPlayerList(), ZoneScript::SetData(), Object::SetDynamicFlag(), Unit::SetFacingTo(), Unit::SetUnitFlag2(), SPELL_BUBBLE_VISUAL, SPELL_MIND_REND, SPELL_TARGET_ALPHA, SPELL_TARGET_BETA, SPELL_TARGET_DELTA, SPELL_TARGET_GAMMA, SPELL_TARGET_OMEGA, SPELL_TELEPORT_VISUAL, WorldObject::SummonCreature(), BossAI::summons, TEMPSUMMON_MANUAL_DESPAWN, UNIT_DYNFLAG_DEAD, UNIT_FLAG2_FEIGN_DEATH, YELL_INTRO1, YELL_INTRO2, YELL_RELEASE1, YELL_RELEASE2A, YELL_RELEASE2B, YELL_RELEASE3, YELL_RELEASE4, and YELL_WELCOME.