document.write(`
  <a id="Global:AddTaxiPath" class="fn" href="../Global/AddTaxiPath.html">AddTaxiPath</a>
  <a id="Global:AddVendorItem" class="fn" href="../Global/AddVendorItem.html">AddVendorItem</a>
  <a id="Global:AuthDBExecute" class="fn" href="../Global/AuthDBExecute.html">AuthDBExecute</a>
  <a id="Global:AuthDBQuery" class="fn" href="../Global/AuthDBQuery.html">AuthDBQuery</a>
  <a id="Global:AuthDBQueryAsync" class="fn" href="../Global/AuthDBQueryAsync.html">AuthDBQueryAsync</a>
  <a id="Global:Ban" class="fn" href="../Global/Ban.html">Ban</a>
  <a id="Global:CharDBExecute" class="fn" href="../Global/CharDBExecute.html">CharDBExecute</a>
  <a id="Global:CharDBQuery" class="fn" href="../Global/CharDBQuery.html">CharDBQuery</a>
  <a id="Global:CharDBQueryAsync" class="fn" href="../Global/CharDBQueryAsync.html">CharDBQueryAsync</a>
  <a id="Global:ClearBattleGroundEvents" class="fn" href="../Global/ClearBattleGroundEvents.html">ClearBattleGroundEvents</a>
  <a id="Global:ClearCreatureEvents" class="fn" href="../Global/ClearCreatureEvents.html">ClearCreatureEvents</a>
  <a id="Global:ClearCreatureGossipEvents" class="fn" href="../Global/ClearCreatureGossipEvents.html">ClearCreatureGossipEvents</a>
  <a id="Global:ClearGameObjectEvents" class="fn" href="../Global/ClearGameObjectEvents.html">ClearGameObjectEvents</a>
  <a id="Global:ClearGameObjectGossipEvents" class="fn" href="../Global/ClearGameObjectGossipEvents.html">ClearGameObjectGossipEvents</a>
  <a id="Global:ClearGroupEvents" class="fn" href="../Global/ClearGroupEvents.html">ClearGroupEvents</a>
  <a id="Global:ClearGuildEvents" class="fn" href="../Global/ClearGuildEvents.html">ClearGuildEvents</a>
  <a id="Global:ClearInstanceEvents" class="fn" href="../Global/ClearInstanceEvents.html">ClearInstanceEvents</a>
  <a id="Global:ClearItemEvents" class="fn" href="../Global/ClearItemEvents.html">ClearItemEvents</a>
  <a id="Global:ClearItemGossipEvents" class="fn" href="../Global/ClearItemGossipEvents.html">ClearItemGossipEvents</a>
  <a id="Global:ClearMapEvents" class="fn" href="../Global/ClearMapEvents.html">ClearMapEvents</a>
  <a id="Global:ClearPacketEvents" class="fn" href="../Global/ClearPacketEvents.html">ClearPacketEvents</a>
  <a id="Global:ClearPlayerEvents" class="fn" href="../Global/ClearPlayerEvents.html">ClearPlayerEvents</a>
  <a id="Global:ClearPlayerGossipEvents" class="fn" href="../Global/ClearPlayerGossipEvents.html">ClearPlayerGossipEvents</a>
  <a id="Global:ClearServerEvents" class="fn" href="../Global/ClearServerEvents.html">ClearServerEvents</a>
  <a id="Global:ClearSpellEvents" class="fn" href="../Global/ClearSpellEvents.html">ClearSpellEvents</a>
  <a id="Global:ClearUniqueCreatureEvents" class="fn" href="../Global/ClearUniqueCreatureEvents.html">ClearUniqueCreatureEvents</a>
  <a id="Global:CreateLongLong" class="fn" href="../Global/CreateLongLong.html">CreateLongLong</a>
  <a id="Global:CreateLuaEvent" class="fn" href="../Global/CreateLuaEvent.html">CreateLuaEvent</a>
  <a id="Global:CreatePacket" class="fn" href="../Global/CreatePacket.html">CreatePacket</a>
  <a id="Global:CreateULongLong" class="fn" href="../Global/CreateULongLong.html">CreateULongLong</a>
  <a id="Global:GetActiveGameEvents" class="fn" href="../Global/GetActiveGameEvents.html">GetActiveGameEvents</a>
  <a id="Global:GetAreaName" class="fn" href="../Global/GetAreaName.html">GetAreaName</a>
  <a id="Global:GetCoreExpansion" class="fn" href="../Global/GetCoreExpansion.html">GetCoreExpansion</a>
  <a id="Global:GetCoreName" class="fn" href="../Global/GetCoreName.html">GetCoreName</a>
  <a id="Global:GetCoreVersion" class="fn" href="../Global/GetCoreVersion.html">GetCoreVersion</a>
  <a id="Global:GetCurrTime" class="fn" href="../Global/GetCurrTime.html">GetCurrTime</a>
  <a id="Global:GetGUIDEntry" class="fn" href="../Global/GetGUIDEntry.html">GetGUIDEntry</a>
  <a id="Global:GetGUIDLow" class="fn" href="../Global/GetGUIDLow.html">GetGUIDLow</a>
  <a id="Global:GetGUIDType" class="fn" href="../Global/GetGUIDType.html">GetGUIDType</a>
  <a id="Global:GetGameTime" class="fn" href="../Global/GetGameTime.html">GetGameTime</a>
  <a id="Global:GetGossipMenuOptionLocale" class="fn" href="../Global/GetGossipMenuOptionLocale.html">GetGossipMenuOptionLocale</a>
  <a id="Global:GetGuildByLeaderGUID" class="fn" href="../Global/GetGuildByLeaderGUID.html">GetGuildByLeaderGUID</a>
  <a id="Global:GetGuildByName" class="fn" href="../Global/GetGuildByName.html">GetGuildByName</a>
  <a id="Global:GetItemGUID" class="fn" href="../Global/GetItemGUID.html">GetItemGUID</a>
  <a id="Global:GetItemLink" class="fn" href="../Global/GetItemLink.html">GetItemLink</a>
  <a id="Global:GetItemTemplate" class="fn" href="../Global/GetItemTemplate.html">GetItemTemplate</a>
  <a id="Global:GetLuaEngine" class="fn" href="../Global/GetLuaEngine.html">GetLuaEngine</a>
  <a id="Global:GetMapById" class="fn" href="../Global/GetMapById.html">GetMapById</a>
  <a id="Global:GetMapEntrance" class="fn" href="../Global/GetMapEntrance.html">GetMapEntrance</a>
  <a id="Global:GetObjectGUID" class="fn" href="../Global/GetObjectGUID.html">GetObjectGUID</a>
  <a id="Global:GetOwnerHalaa" class="fn" href="../Global/GetOwnerHalaa.html">GetOwnerHalaa</a>
  <a id="Global:GetPlayerByGUID" class="fn" href="../Global/GetPlayerByGUID.html">GetPlayerByGUID</a>
  <a id="Global:GetPlayerByName" class="fn" href="../Global/GetPlayerByName.html">GetPlayerByName</a>
  <a id="Global:GetPlayerCount" class="fn" href="../Global/GetPlayerCount.html">GetPlayerCount</a>
  <a id="Global:GetPlayerGUID" class="fn" href="../Global/GetPlayerGUID.html">GetPlayerGUID</a>
  <a id="Global:GetPlayersInWorld" class="fn" href="../Global/GetPlayersInWorld.html">GetPlayersInWorld</a>
  <a id="Global:GetQuest" class="fn" href="../Global/GetQuest.html">GetQuest</a>
  <a id="Global:GetRealmID" class="fn" href="../Global/GetRealmID.html">GetRealmID</a>
  <a id="Global:GetSpellInfo" class="fn" href="../Global/GetSpellInfo.html">GetSpellInfo</a>
  <a id="Global:GetStateInstanceId" class="fn" href="../Global/GetStateInstanceId.html">GetStateInstanceId</a>
  <a id="Global:GetStateMap" class="fn" href="../Global/GetStateMap.html">GetStateMap</a>
  <a id="Global:GetStateMapId" class="fn" href="../Global/GetStateMapId.html">GetStateMapId</a>
  <a id="Global:GetTimeDiff" class="fn" href="../Global/GetTimeDiff.html">GetTimeDiff</a>
  <a id="Global:GetUnitGUID" class="fn" href="../Global/GetUnitGUID.html">GetUnitGUID</a>
  <a id="Global:HttpRequest" class="fn" href="../Global/HttpRequest.html">HttpRequest</a>
  <a id="Global:IsBagPos" class="fn" href="../Global/IsBagPos.html">IsBagPos</a>
  <a id="Global:IsBankPos" class="fn" href="../Global/IsBankPos.html">IsBankPos</a>
  <a id="Global:IsCompatibilityMode" class="fn" href="../Global/IsCompatibilityMode.html">IsCompatibilityMode</a>
  <a id="Global:IsEquipmentPos" class="fn" href="../Global/IsEquipmentPos.html">IsEquipmentPos</a>
  <a id="Global:IsGameEventActive" class="fn" href="../Global/IsGameEventActive.html">IsGameEventActive</a>
  <a id="Global:IsInventoryPos" class="fn" href="../Global/IsInventoryPos.html">IsInventoryPos</a>
  <a id="Global:Kick" class="fn" href="../Global/Kick.html">Kick</a>
  <a id="Global:LookupEntry" class="fn" href="../Global/LookupEntry.html">LookupEntry</a>
  <a id="Global:PerformIngameSpawn" class="fn" href="../Global/PerformIngameSpawn.html">PerformIngameSpawn</a>
  <a id="Global:PrintDebug" class="fn" href="../Global/PrintDebug.html">PrintDebug</a>
  <a id="Global:PrintError" class="fn" href="../Global/PrintError.html">PrintError</a>
  <a id="Global:PrintInfo" class="fn" href="../Global/PrintInfo.html">PrintInfo</a>
  <a id="Global:RegisterBGEvent" class="fn" href="../Global/RegisterBGEvent.html">RegisterBGEvent</a>
  <a id="Global:RegisterCreatureEvent" class="fn" href="../Global/RegisterCreatureEvent.html">RegisterCreatureEvent</a>
  <a id="Global:RegisterCreatureGossipEvent" class="fn" href="../Global/RegisterCreatureGossipEvent.html">RegisterCreatureGossipEvent</a>
  <a id="Global:RegisterGameObjectEvent" class="fn" href="../Global/RegisterGameObjectEvent.html">RegisterGameObjectEvent</a>
  <a id="Global:RegisterGameObjectGossipEvent" class="fn" href="../Global/RegisterGameObjectGossipEvent.html">RegisterGameObjectGossipEvent</a>
  <a id="Global:RegisterGroupEvent" class="fn" href="../Global/RegisterGroupEvent.html">RegisterGroupEvent</a>
  <a id="Global:RegisterGuildEvent" class="fn" href="../Global/RegisterGuildEvent.html">RegisterGuildEvent</a>
  <a id="Global:RegisterInstanceEvent" class="fn" href="../Global/RegisterInstanceEvent.html">RegisterInstanceEvent</a>
  <a id="Global:RegisterItemEvent" class="fn" href="../Global/RegisterItemEvent.html">RegisterItemEvent</a>
  <a id="Global:RegisterItemGossipEvent" class="fn" href="../Global/RegisterItemGossipEvent.html">RegisterItemGossipEvent</a>
  <a id="Global:RegisterMapEvent" class="fn" href="../Global/RegisterMapEvent.html">RegisterMapEvent</a>
  <a id="Global:RegisterPacketEvent" class="fn" href="../Global/RegisterPacketEvent.html">RegisterPacketEvent</a>
  <a id="Global:RegisterPlayerEvent" class="fn" href="../Global/RegisterPlayerEvent.html">RegisterPlayerEvent</a>
  <a id="Global:RegisterPlayerGossipEvent" class="fn" href="../Global/RegisterPlayerGossipEvent.html">RegisterPlayerGossipEvent</a>
  <a id="Global:RegisterServerEvent" class="fn" href="../Global/RegisterServerEvent.html">RegisterServerEvent</a>
  <a id="Global:RegisterSpellEvent" class="fn" href="../Global/RegisterSpellEvent.html">RegisterSpellEvent</a>
  <a id="Global:RegisterUniqueCreatureEvent" class="fn" href="../Global/RegisterUniqueCreatureEvent.html">RegisterUniqueCreatureEvent</a>
  <a id="Global:ReloadEluna" class="fn" href="../Global/ReloadEluna.html">ReloadEluna</a>
  <a id="Global:RemoveEventById" class="fn" href="../Global/RemoveEventById.html">RemoveEventById</a>
  <a id="Global:RemoveEvents" class="fn" href="../Global/RemoveEvents.html">RemoveEvents</a>
  <a id="Global:RunCommand" class="fn" href="../Global/RunCommand.html">RunCommand</a>
  <a id="Global:SaveAllPlayers" class="fn" href="../Global/SaveAllPlayers.html">SaveAllPlayers</a>
  <a id="Global:SendMail" class="fn" href="../Global/SendMail.html">SendMail</a>
  <a id="Global:SendWorldMessage" class="fn" href="../Global/SendWorldMessage.html">SendWorldMessage</a>
  <a id="Global:SetOwnerHalaa" class="fn" href="../Global/SetOwnerHalaa.html">SetOwnerHalaa</a>
  <a id="Global:StartGameEvent" class="fn" href="../Global/StartGameEvent.html">StartGameEvent</a>
  <a id="Global:StopGameEvent" class="fn" href="../Global/StopGameEvent.html">StopGameEvent</a>
  <a id="Global:VendorRemoveAllItems" class="fn" href="../Global/VendorRemoveAllItems.html">VendorRemoveAllItems</a>
  <a id="Global:VendorRemoveItem" class="fn" href="../Global/VendorRemoveItem.html">VendorRemoveItem</a>
  <a id="Global:WorldDBExecute" class="fn" href="../Global/WorldDBExecute.html">WorldDBExecute</a>
  <a id="Global:WorldDBQuery" class="fn" href="../Global/WorldDBQuery.html">WorldDBQuery</a>
  <a id="Global:WorldDBQueryAsync" class="fn" href="../Global/WorldDBQueryAsync.html">WorldDBQueryAsync</a>
  <a id="Global:bit_and" class="fn" href="../Global/bit_and.html">bit_and</a>
  <a id="Global:bit_lshift" class="fn" href="../Global/bit_lshift.html">bit_lshift</a>
  <a id="Global:bit_not" class="fn" href="../Global/bit_not.html">bit_not</a>
  <a id="Global:bit_or" class="fn" href="../Global/bit_or.html">bit_or</a>
  <a id="Global:bit_rshift" class="fn" href="../Global/bit_rshift.html">bit_rshift</a>
  <a id="Global:bit_xor" class="fn" href="../Global/bit_xor.html">bit_xor</a>
`);