AzerothCore: PlayerDump Class Reference
PlayerDump Class Reference
#include "PlayerDump.h"
Static Public Member Functions
static void InitializeTables ()
Protected Member Functions
PlayerDump ()
Detailed Description
Constructor & Destructor Documentation
PlayerDump()
PlayerDump::PlayerDump () inline protected
{ }
Member Function Documentation
InitializeTables()
void PlayerDump::InitializeTables () static
{
    uint32 oldMSTime = getMSTime();
    for (DumpTable const& dumpTable : DumpTables)
    {
        TableStruct t;
        t.TableName = dumpTable.Name;
        QueryResult result = CharacterDatabase.Query("DESC {}", dumpTable.Name);
        // prepared statement is correct (checked at startup) so table must exist
        ASSERT(result);
        int32 i = 0;
        do
        {
            std::string columnName = (*result)[0].Get<std::string>();
            t.FieldIndices.emplace(columnName, i++);
            TableField f;
            f.FieldName = columnName;
            bool toUpperResult = Utf8ToUpperOnlyLatin(columnName);
            ASSERT(toUpperResult);
            t.TableFields.emplace_back(std::move(f));
        } while (result->NextRow());
        switch (dumpTable.Type)
        {
        case DTT_CHARACTER:
            MarkWhereField(t, "guid");
            MarkDependentColumn(t, "guid", GUID_TYPE_CHAR);
            MarkDependentColumn(t, "account", GUID_TYPE_ACCOUNT);
            MarkDependentColumn(t, "deleteInfos_Account", GUID_TYPE_NULL);
            MarkDependentColumn(t, "deleteInfos_Name", GUID_TYPE_NULL);
            MarkDependentColumn(t, "deleteDate", GUID_TYPE_NULL);
            break;
        case DTT_CHAR_TABLE:
            MarkWhereField(t, "guid");
            MarkDependentColumn(t, "guid", GUID_TYPE_CHAR);
            break;
        case DTT_EQSET_TABLE:
            MarkWhereField(t, "guid");
            MarkDependentColumn(t, "guid", GUID_TYPE_CHAR);
            MarkDependentColumn(t, "setguid", GUID_TYPE_EQUIPMENT_SET);
            // item0 - item18
            for (uint32 j = 0; j < EQUIPMENT_SLOT_END; ++j)
            {
                std::string itColumn = Acore::StringFormat("item{}", j);
                MarkDependentColumn(t, itColumn, GUID_TYPE_ITEM);
            }
            break;
        case DTT_INVENTORY:
            MarkWhereField(t, "guid");
            MarkDependentColumn(t, "guid", GUID_TYPE_CHAR);
            MarkDependentColumn(t, "bag", GUID_TYPE_ITEM);
            MarkDependentColumn(t, "item", GUID_TYPE_ITEM);
            break;
        case DTT_MAIL:
            MarkWhereField(t, "receiver");
            MarkDependentColumn(t, "id", GUID_TYPE_MAIL);
            MarkDependentColumn(t, "receiver", GUID_TYPE_CHAR);
            break;
        case DTT_MAIL_ITEM:
            MarkWhereField(t, "mail_id");
            MarkDependentColumn(t, "mail_id", GUID_TYPE_MAIL);
            MarkDependentColumn(t, "item_guid", GUID_TYPE_ITEM);
            MarkDependentColumn(t, "receiver", GUID_TYPE_CHAR);
            break;
        case DTT_ITEM:
            MarkWhereField(t, "guid");
            MarkDependentColumn(t, "guid", GUID_TYPE_ITEM);
            MarkDependentColumn(t, "owner_guid", GUID_TYPE_CHAR);
            break;
        case DTT_ITEM_GIFT:
            MarkWhereField(t, "item_guid");
            MarkDependentColumn(t, "guid", GUID_TYPE_CHAR);
            MarkDependentColumn(t, "item_guid", GUID_TYPE_ITEM);
            break;
        case DTT_PET:
            MarkWhereField(t, "owner");
            MarkDependentColumn(t, "id", GUID_TYPE_PET);
            MarkDependentColumn(t, "owner", GUID_TYPE_CHAR);
            break;
        case DTT_PET_TABLE:
            MarkWhereField(t, "guid");
            MarkDependentColumn(t, "guid", GUID_TYPE_PET);
            break;
        default:
            LOG_FATAL("server.loading", "Wrong dump table type {}, probably added a new table type without updating code", uint32(dumpTable.Type));
            ABORT();
            return;
        }
        CharacterTables.emplace_back(std::move(t));
    }
    // perform some sanity checks
    for (TableStruct const& tableStruct : CharacterTables)
    {
        if (tableStruct.WhereFieldName.empty())
        {
            LOG_FATAL("server.loading", "Table `{}` defined in player dump doesn't have a WHERE query field", tableStruct.TableName);
            ABORT();
        }
    }
    for (BaseTable const& baseTable : BaseTables)
        AssertBaseTable(baseTable);
    ASSERT(CharacterTables.size() == DUMP_TABLE_COUNT);
    LOG_INFO("server.loading", ">> Initialized Tables For PlayerDump in {} ms.", GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References ABORT, ASSERT, AssertBaseTable(), BaseTables, CharacterDatabase, CharacterTables, DTT_CHAR_TABLE, DTT_CHARACTER, DTT_EQSET_TABLE, DTT_INVENTORY, DTT_ITEM, DTT_ITEM_GIFT, DTT_MAIL, DTT_MAIL_ITEM, DTT_PET, DTT_PET_TABLE, DUMP_TABLE_COUNT, DumpTables, EQUIPMENT_SLOT_END, TableStruct::FieldIndices, TableField::FieldName, getMSTime(), GetMSTimeDiffToNow(), GUID_TYPE_ACCOUNT, GUID_TYPE_CHAR, GUID_TYPE_EQUIPMENT_SET, GUID_TYPE_ITEM, GUID_TYPE_MAIL, GUID_TYPE_NULL, GUID_TYPE_PET, LOG_FATAL, LOG_INFO, MarkDependentColumn(), MarkWhereField(), Acore::StringFormat(), TableStruct::TableFields, TableStruct::TableName, and Utf8ToUpperOnlyLatin().
Referenced by World::SetInitialWorldSettings().