AzerothCore: go_ossirian_crystal::go_ossirian_crystalAI Struct Reference
go_ossirian_crystal::go_ossirian_crystalAI Struct Reference
Public Member Functions
go_ossirian_crystalAI (GameObject *go)
void SetGUID (ObjectGuid guid, int32 type) override
bool GossipHello (Player *, bool reportUse) override
void DoAction (int32 action) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Private Attributes
InstanceScript * _instance
ObjectGuid _triggerGUID
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_ossirian_crystalAI()
go_ossirian_crystal::go_ossirian_crystalAI::go_ossirian_crystalAI (GameObject * go) inline
: GameObjectAI(go), _instance(go->GetInstanceScript()) { }
Member Function Documentation
DoAction()
void go_ossirian_crystal::go_ossirian_crystalAI::DoAction (int32 action) inline override virtual
Reimplemented from GameObjectAI.
        {
            if (action == ACTION_DESPAWN_TRIGGER)
            {
                if (Creature* trigger = ObjectAccessor::GetCreature(*me, _triggerGUID))
                {
                    trigger->DespawnOrUnsummon();
                }
            }
        }
References _triggerGUID, ACTION_DESPAWN_TRIGGER, ObjectAccessor::GetCreature(), and GameObjectAI::me.
GossipHello()
bool go_ossirian_crystal::go_ossirian_crystalAI::GossipHello (Player * , bool reportUse) inline override virtual
Reimplemented from GameObjectAI.
        {
            if (reportUse)
            {
                if (!_instance)
                    return true;
                Creature* ossirian = _instance->GetCreature(DATA_OSSIRIAN);
                if (!ossirian)
                    return true;
                if (Creature* trigger = ObjectAccessor::GetCreature(*me, _triggerGUID))
                {
                    if (!trigger->HasUnitState(UNIT_STATE_CASTING))
                    {
                        ossirian->AI()->SetGUID(me->GetGUID(), ACTION_TRIGGER_WEAKNESS);
                        trigger->CastSpell(trigger, spellWeakness[urand(0, 4)], false);
                    }
                }
            }
            return false;
        }
References _instance, _triggerGUID, ACTION_TRIGGER_WEAKNESS, Creature::AI(), DATA_OSSIRIAN, InstanceScript::GetCreature(), ObjectAccessor::GetCreature(), Object::GetGUID(), GameObjectAI::me, UnitAI::SetGUID(), spellWeakness, UNIT_STATE_CASTING, and urand().
SetGUID()
void go_ossirian_crystal::go_ossirian_crystalAI::SetGUID (ObjectGuid guid, int32 type) inline override virtual
Reimplemented from GameObjectAI.
        {
            if (type == GUID_TRIGGER_PAIR)
            {
                _triggerGUID = guid;
            }
        }
References _triggerGUID, and GUID_TRIGGER_PAIR.
Member Data Documentation
_instance
InstanceScript* go_ossirian_crystal::go_ossirian_crystalAI::_instance private
Referenced by GossipHello().
_triggerGUID
ObjectGuid go_ossirian_crystal::go_ossirian_crystalAI::_triggerGUID private
Referenced by DoAction(), GossipHello(), and SetGUID().