AzerothCore: DispelInfo Class Reference
DispelInfo Class Reference
#include "Unit.h"
Public Member Functions
DispelInfo (Unit *dispeller, uint32 dispellerSpellId, uint8 chargesRemoved)
Unit * GetDispeller () const
uint32 GetDispellerSpellId () const
uint8 GetRemovedCharges () const
void SetRemovedCharges (uint8 amount)
Private Attributes
Unit * _dispellerUnit
uint32 _dispellerSpell
uint8 _chargesRemoved
Detailed Description
Constructor & Destructor Documentation
DispelInfo()
DispelInfo::DispelInfo (Unit * dispeller, uint32 dispellerSpellId, uint8 chargesRemoved) inline explicit
                                                                                        :
        _dispellerUnit(dispeller), _dispellerSpell(dispellerSpellId), _chargesRemoved(chargesRemoved) {}
Member Function Documentation
GetDispeller()
Unit * DispelInfo::GetDispeller () const inline
{ return _dispellerUnit; }
References _dispellerUnit.
Referenced by spell_hexlord_unstable_affliction::HandleDispel(), spell_faction_champion_warl_unstable_affliction_aura::HandleDispel(), and spell_warl_unstable_affliction::HandleDispel().
GetDispellerSpellId()
uint32 DispelInfo::GetDispellerSpellId () const inline
{ return _dispellerSpell; }
References _dispellerSpell.
GetRemovedCharges()
uint8 DispelInfo::GetRemovedCharges () const inline
{ return _chargesRemoved; }
References _chargesRemoved.
Referenced by spell_dru_lifebloom::HandleDispel(), and Unit::RemoveAurasDueToSpellByDispel().
SetRemovedCharges()
void DispelInfo::SetRemovedCharges (uint8 amount) inline
    {
        _chargesRemoved = amount;
    }
References _chargesRemoved.
Referenced by spell_halion_marks_aura::BeforeDispel().
Member Data Documentation
_chargesRemoved
uint8 DispelInfo::_chargesRemoved private
Referenced by GetRemovedCharges(), and SetRemovedCharges().
_dispellerSpell
uint32 DispelInfo::_dispellerSpell private
Referenced by GetDispellerSpellId().
_dispellerUnit
Unit* DispelInfo::_dispellerUnit private
Referenced by GetDispeller().