AzerothCore: IgbArtilleryCheck Class Reference
IgbArtilleryCheck Class Reference
Public Member Functions
IgbArtilleryCheck (uint32 entry)
bool operator() (WorldObject *unit)
Private Attributes
uint32 _entry
Detailed Description
Constructor & Destructor Documentation
IgbArtilleryCheck()
IgbArtilleryCheck::IgbArtilleryCheck (uint32 entry) inline
: _entry(entry) {}
Member Function Documentation
operator()()
bool IgbArtilleryCheck::operator() (WorldObject * unit) inline
    {
        return !unit->IsPlayer() || unit->GetPositionZ() > 478.0f || !unit->GetTransport() || unit->GetTransport()->GetEntry() != _entry
        || unit->GetMapHeight(unit->GetPhaseMask(), unit->GetPositionX(), unit->GetPositionY(), unit->GetPositionZ()) < 465.0f;
    }
References _entry, Object::GetEntry(), WorldObject::GetMapHeight(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), WorldObject::GetTransport(), and Object::IsPlayer().
Member Data Documentation
_entry
uint32 IgbArtilleryCheck::_entry private
Referenced by operator()().