AzerothCore: boss_mandokir::boss_mandokirAI Struct Reference
boss_mandokir::boss_mandokirAI Struct Reference
Public Member Functions
boss_mandokirAI (Creature *creature)
void Reset () override
void JustDied (Unit *) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void KilledUnit (Unit *victim) override
void DoAction (int32 action) override
void SetGUID (ObjectGuid const guid, int32 type) override
void MovementInform (uint32 type, uint32 id) override
void CalculateThreat (Unit *hatedUnit, float &threat, SpellInfo const *threatSpell) override
void DamageDealt (Unit *doneTo, uint32 &damage, DamageEffectType) override
Called at any Damage to any victim (before damage apply)
bool OnTeleportUnreacheablePlayer (Player *player) override
void DoMeleeAttackIfReady (bool ignoreCasting)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint8 killCount
ObjectGuid reviveGUID
bool _useExecute
std::pair< ObjectGuid, float > _chargeTarget
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_mandokirAI()
boss_mandokir::boss_mandokirAI::boss_mandokirAI (Creature * creature) inline
: BossAI(creature, DATA_MANDOKIR) { }
Member Function Documentation
CalculateThreat()
void boss_mandokir::boss_mandokirAI::CalculateThreat (Unit * hatedUnit, float & threat, SpellInfo const * threatSpell) inline override virtual
Reimplemented from CreatureAI.
        {
            if (_chargeTarget.first == hatedUnit->GetGUID())
            {
                // Do not count DOTs/HOTs
                if (!(threatSpell && (threatSpell->HasAura(SPELL_AURA_DAMAGE_SHIELD) || threatSpell->HasAttribute(SPELL_ATTR0_CU_NO_INITIAL_THREAT))))
                {
                    _chargeTarget.second += threat;
                }
            }
        }
References _chargeTarget, Object::GetGUID(), SpellInfo::HasAttribute(), SpellInfo::HasAura(), SPELL_ATTR0_CU_NO_INITIAL_THREAT, and SPELL_AURA_DAMAGE_SHIELD.
DamageDealt()
void boss_mandokir::boss_mandokirAI::DamageDealt (Unit * , uint32 & , DamageEffectType) inline override virtual
Called at any Damage to any victim (before damage apply)
Reimplemented from UnitAI.
        {
            if (doneTo && doneTo == me->GetVictim())
            {
                if (doneTo->HealthBelowPctDamaged(20, damage))
                {
                    if (!_useExecute)
                    {
                        _useExecute = true;
                        events.ScheduleEvent(EVENT_EXECUTE, 1s);
                    }
                }
                else if (_useExecute)
                {
                    _useExecute = false;
                    events.CancelEvent(EVENT_EXECUTE);
                }
            }
        }
References _useExecute, EVENT_EXECUTE, Unit::GetVictim(), Unit::HealthBelowPctDamaged(), and ScriptedAI::me.
DoAction()
void boss_mandokir::boss_mandokirAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == ACTION_START_REVIVE)
            {
                std::list<Creature*> creatures;
                GetCreatureListWithEntryInGrid(creatures, me, NPC_CHAINED_SPIRIT, 200.0f);
                if (creatures.empty())
                    return;
                for (std::list<Creature*>::iterator itr = creatures.begin(); itr != creatures.end(); ++itr)
                {
                    if (Creature* chainedSpirit = ObjectAccessor::GetCreature(*me, (*itr)->GetGUID()))
                    {
                        chainedSpirit->AI()->SetGUID(reviveGUID);
                        chainedSpirit->AI()->DoAction(ACTION_REVIVE);
                        reviveGUID.Clear();
                    }
                }
            }
        }
References ACTION_REVIVE, ACTION_START_REVIVE, ObjectGuid::Clear(), ObjectAccessor::GetCreature(), GetCreatureListWithEntryInGrid(), Object::GetGUID(), ScriptedAI::me, NPC_CHAINED_SPIRIT, and reviveGUID.
DoMeleeAttackIfReady()
void boss_mandokir::boss_mandokirAI::DoMeleeAttackIfReady (bool ignoreCasting) inline
        {
            if (!ignoreCasting && me->HasUnitState(UNIT_STATE_CASTING))
            {
                return;
            }
            Unit* victim = me->GetVictim();
            if (!victim || !victim->IsInWorld())
                return;
            if (!me->IsWithinMeleeRange(victim))
                return;
            //Make sure our attack is ready and we aren't currently casting before checking distance
            if (me->isAttackReady())
            {
                // xinef: prevent base and off attack in same time, delay attack at 0.2 sec
                if (me->haveOffhandWeapon())
                    if (me->getAttackTimer(OFF_ATTACK) < ATTACK_DISPLAY_DELAY)
                        me->setAttackTimer(OFF_ATTACK, ATTACK_DISPLAY_DELAY);
                me->AttackerStateUpdate(victim, BASE_ATTACK, false, ignoreCasting);
                me->resetAttackTimer();
            }
            if (me->haveOffhandWeapon() && me->isAttackReady(OFF_ATTACK))
            {
                // xinef: delay main hand attack if both will hit at the same time (players code)
                if (me->getAttackTimer(BASE_ATTACK) < ATTACK_DISPLAY_DELAY)
                    me->setAttackTimer(BASE_ATTACK, ATTACK_DISPLAY_DELAY);
                me->AttackerStateUpdate(victim, OFF_ATTACK, false, ignoreCasting);
                me->resetAttackTimer(OFF_ATTACK);
            }
        }
References ATTACK_DISPLAY_DELAY, Unit::AttackerStateUpdate(), BASE_ATTACK, Unit::getAttackTimer(), Unit::GetVictim(), Unit::HasUnitState(), Unit::haveOffhandWeapon(), Unit::isAttackReady(), Object::IsInWorld(), Unit::IsWithinMeleeRange(), ScriptedAI::me, OFF_ATTACK, Unit::resetAttackTimer(), Unit::setAttackTimer(), and UNIT_STATE_CASTING.
JustDied()
void boss_mandokir::boss_mandokirAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            std::list<Creature*> chainedSpirits;
            GetCreatureListWithEntryInGrid(chainedSpirits, me, NPC_CHAINED_SPIRIT, 200.f);
            for (Creature* spirit : chainedSpirits)
                spirit->DespawnOrUnsummon();
            instance->SetBossState(DATA_MANDOKIR, DONE);
            instance->SaveToDB();
        }
References DATA_MANDOKIR, DONE, GetCreatureListWithEntryInGrid(), BossAI::instance, ScriptedAI::me, NPC_CHAINED_SPIRIT, InstanceScript::SaveToDB(), and InstanceScript::SetBossState().
JustEngagedWith()
void boss_mandokir::boss_mandokirAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            _JustEngagedWith();
            events.ScheduleEvent(EVENT_OVERPOWER, 1s);
            events.ScheduleEvent(EVENT_MORTAL_STRIKE, 14s, 28s);
            events.ScheduleEvent(EVENT_WHIRLWIND, 24s, 30s);
            events.ScheduleEvent(EVENT_CHECK_OHGAN, 1s);
            events.ScheduleEvent(EVENT_WATCH_PLAYER, 12s, 24s);
            events.ScheduleEvent(EVENT_CHARGE_PLAYER, 30s, 40s);
            events.ScheduleEvent(EVENT_CLEAVE, 1s);
            me->SetHomePosition(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), me->GetOrientation());
            Talk(SAY_AGGRO);
            me->Dismount();
            // Summon Ohgan (Spell missing) TEMP HACK
            me->SummonCreature(NPC_OHGAN, me->GetPositionX() - 3, me->GetPositionY(), me->GetPositionZ(), me->GetOrientation(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 35000);
            for (int i = 0; i < CHAINED_SPIRIT_COUNT; ++i)
            {
                me->SummonCreature(NPC_CHAINED_SPIRIT, PosSummonChainedSpirits[i], TEMPSUMMON_CORPSE_DESPAWN);
            }
            DoZoneInCombat();
        }
References BossAI::_JustEngagedWith(), CHAINED_SPIRIT_COUNT, Unit::Dismount(), CreatureAI::DoZoneInCombat(), EVENT_CHARGE_PLAYER, EVENT_CHECK_OHGAN, EVENT_CLEAVE, EVENT_MORTAL_STRIKE, EVENT_OVERPOWER, EVENT_WATCH_PLAYER, EVENT_WHIRLWIND, Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, NPC_CHAINED_SPIRIT, NPC_OHGAN, PosSummonChainedSpirits, SAY_AGGRO, Creature::SetHomePosition(), WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_DESPAWN, and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
KilledUnit()
void boss_mandokir::boss_mandokirAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!victim->IsPlayer())
                return;
            reviveGUID = victim->GetGUID();
            RevivePlayer(victim, reviveGUID);
            if (++killCount == 3)
            {
                Talk(SAY_DING_KILL);
                if (Creature* jindo = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_JINDO)))
                {
                    if (jindo->IsAlive())
                    {
                        jindo->AI()->Talk(SAY_GRATS_JINDO);
                    }
                }
                DoCastSelf(SPELL_LEVEL_UP, true);
                killCount = 0;
            }
        }
References DATA_JINDO, UnitAI::DoCastSelf(), ObjectAccessor::GetCreature(), Object::GetGUID(), InstanceScript::GetGuidData(), BossAI::instance, Object::IsPlayer(), killCount, ScriptedAI::me, reviveGUID, RevivePlayer(), SAY_DING_KILL, SAY_GRATS_JINDO, and SPELL_LEVEL_UP.
MovementInform()
void boss_mandokir::boss_mandokirAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type == WAYPOINT_MOTION_TYPE)
            {
                me->SetWalk(false);
                if (id == POINT_MANDOKIR_END)
                {
                    me->SetHomePosition(PosMandokir[0]);
                    instance->SetBossState(DATA_MANDOKIR, NOT_STARTED);
                }
            }
        }
References DATA_MANDOKIR, BossAI::instance, ScriptedAI::me, NOT_STARTED, POINT_MANDOKIR_END, PosMandokir, InstanceScript::SetBossState(), Creature::SetHomePosition(), Creature::SetWalk(), and WAYPOINT_MOTION_TYPE.
OnTeleportUnreacheablePlayer()
bool boss_mandokir::boss_mandokirAI::OnTeleportUnreacheablePlayer (Player * player) inline override virtual
Reimplemented from CreatureAI.
        {
            DoCast(player, SPELL_SUMMON_PLAYER, true);
            return true;
        }
References UnitAI::DoCast(), and SPELL_SUMMON_PLAYER.
Reset()
void boss_mandokir::boss_mandokirAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            BossAI::Reset();
            killCount = 0;
            if (me->GetPositionZ() > 140.0f)
            {
                events.ScheduleEvent(EVENT_CHECK_START, 1000);
                if (Creature* speaker = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_VILEBRANCH_SPEAKER)))
                {
                    if (!speaker->IsAlive())
                    {
                        speaker->Respawn(true);
                    }
                }
            }
            me->RemoveAurasDueToSpell(SPELL_FRENZY);
            me->SetImmuneToAll(false);
            instance->SetBossState(DATA_OHGAN, NOT_STARTED);
            me->Mount(MODEL_OHGAN_MOUNT);
            reviveGUID.Clear();
            _useExecute = false;
            _chargeTarget.first.Clear();
        }
References _chargeTarget, _useExecute, ObjectGuid::Clear(), DATA_OHGAN, EVENT_CHECK_START, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Position::GetPositionZ(), BossAI::instance, killCount, ScriptedAI::me, MODEL_OHGAN_MOUNT, Unit::Mount(), NOT_STARTED, NPC_VILEBRANCH_SPEAKER, Unit::RemoveAurasDueToSpell(), BossAI::Reset(), reviveGUID, InstanceScript::SetBossState(), Unit::SetImmuneToAll(), and SPELL_FRENZY.
SetGUID()
void boss_mandokir::boss_mandokirAI::SetGUID (ObjectGuid const guid, int32 type) inline override virtual
Reimplemented from UnitAI.
        {
            if (type == ACTION_CHARGE)
            {
                if (_chargeTarget.first == guid && _chargeTarget.second > 0.f)
                {
                    if (Unit* target = ObjectAccessor::GetUnit(*me, _chargeTarget.first))
                    {
                        me->RemoveAurasDueToSpell(SPELL_WHIRLWIND);
                        DoCast(target, SPELL_WATCH_CHARGE, true);
                    }
                }
            }
            else
            {
                reviveGUID = guid;
            }
        }
References _chargeTarget, ACTION_CHARGE, UnitAI::DoCast(), ObjectAccessor::GetUnit(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), reviveGUID, SPELL_WATCH_CHARGE, and SPELL_WHIRLWIND.
UpdateAI()
void boss_mandokir::boss_mandokirAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            events.Update(diff);
            if (!UpdateVictim())
            {
                if (instance->GetBossState(DATA_MANDOKIR) == NOT_STARTED || instance->GetBossState(DATA_MANDOKIR) == SPECIAL)
                {
                    while (uint32 eventId = events.ExecuteEvent())
                    {
                        switch (eventId)
{
                            case EVENT_CHECK_START:
                                if (instance->GetBossState(DATA_MANDOKIR) == SPECIAL)
{
                                    me->GetMotionMaster()->MovePoint(0, PosMandokir[1].m_positionX, PosMandokir[1].m_positionY, PosMandokir[1].m_positionZ);
                                    events.ScheduleEvent(EVENT_STARTED, 6s);
                                }
                                else
{
                                    events.ScheduleEvent(EVENT_CHECK_START, 1s);
                                }
                                break;
                            case EVENT_STARTED:
                                me->SetImmuneToAll(false);
                                me->SetInCombatWithZone();
                                break;
                            default:
                                break;
                        }
                    }
                }
                return;
            }
            if (me->HasUnitState(UNIT_STATE_CASTING) || me->HasUnitState(UNIT_STATE_CHARGING))
            {
                if (me->GetCurrentSpellCastTime(SPELL_WATCH) >= 0)
                {
                    DoMeleeAttackIfReady(true);
                }
                return;
            }
            while (uint32 eventId = events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_OVERPOWER:
                        if (DoCastVictim(SPELL_OVERPOWER) == SPELL_CAST_OK)
{
                            events.ScheduleEvent(EVENT_OVERPOWER, 6s, 8s);
                        }
                        else
{
                            events.ScheduleEvent(EVENT_OVERPOWER, 1s);
                        }
                        break;
                    case EVENT_MORTAL_STRIKE:
                        DoCastVictim(SPELL_MORTAL_STRIKE);
                        events.ScheduleEvent(EVENT_MORTAL_STRIKE, 14s, 28s);
                        break;
                    case EVENT_WHIRLWIND:
                        DoCast(me, SPELL_WHIRLWIND);
                        events.ScheduleEvent(EVENT_WHIRLWIND, 22s,  26s);
                        break;
                    case EVENT_CHECK_OHGAN:
                        if (instance->GetBossState(DATA_OHGAN) == DONE)
{
                            DoCast(me, SPELL_FRENZY);
                            Talk(SAY_OHGAN_DEAD);
                        }
                        else
{
                            events.ScheduleEvent(EVENT_CHECK_OHGAN, 1s);
                        }
                        break;
                    case EVENT_WATCH_PLAYER:
                        if (Unit* player = SelectTarget(SelectTargetMethod::Random, 0, 100, true))
{
                            DoCast(player, SPELL_WATCH);
                            Talk(SAY_WATCH, player);
                            _chargeTarget = std::make_pair(player->GetGUID(), 0.f);
                        }
                        events.ScheduleEvent(EVENT_WATCH_PLAYER, 12s, 24s);
                        break;
                    case EVENT_CHARGE_PLAYER:
                        if (Unit* target = SelectTarget(SelectTargetMethod::MinDistance, 0, [this](Unit const* target)
{
                                if (!me || !target)
                                    return false;
                                if (!target->IsPlayer() || !me->IsWithinLOSInMap(target))
                                    return false;
                                return true;
                            }))
{
                            DoCast(target, SPELL_CHARGE);
                            events.DelayEvents(1500ms);
                            if (Unit* mainTarget = SelectTarget(SelectTargetMethod::MaxThreat, 0, 100.0f))
{
                                me->GetThreatMgr().ModifyThreatByPercent(mainTarget, -100);
                            }
                        }
                        events.ScheduleEvent(EVENT_CHARGE_PLAYER, 30s, 40s);
                        break;
                    case EVENT_EXECUTE:
                        DoCastVictim(SPELL_EXECUTE, true);
                        events.ScheduleEvent(EVENT_EXECUTE, 7s, 14s);
                        break;
                    case EVENT_CLEAVE:
{
                            std::list<Unit*> meleeRangeTargets;
                            auto i = me->GetThreatMgr().GetThreatList().begin();
                            for (; i != me->GetThreatMgr().GetThreatList().end(); ++i)
{
                                Unit* target = (*i)->getTarget();
                                if (me->IsWithinMeleeRange(target))
{
                                    meleeRangeTargets.push_back(target);
                                }
                            }
                            if (meleeRangeTargets.size() >= 5)
{
                                DoCastVictim(SPELL_MANDOKIR_CLEAVE);
                                events.ScheduleEvent(EVENT_CLEAVE, 10s, 20s);
                            }
                            else
{
                                events.ScheduleEvent(EVENT_CLEAVE, 1s);
                            }
                            break;
                        }
                    default:
                        break;
                }
            }
            DoMeleeAttackIfReady(false);
        }
References _chargeTarget, DATA_MANDOKIR, DATA_OHGAN, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), DONE, EVENT_CHARGE_PLAYER, EVENT_CHECK_OHGAN, EVENT_CHECK_START, EVENT_CLEAVE, EVENT_EXECUTE, EVENT_MORTAL_STRIKE, EVENT_OVERPOWER, EVENT_STARTED, EVENT_WATCH_PLAYER, EVENT_WHIRLWIND, InstanceScript::GetBossState(), Unit::GetCurrentSpellCastTime(), Unit::GetMotionMaster(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), Unit::HasUnitState(), BossAI::instance, Object::IsPlayer(), WorldObject::IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), ScriptedAI::me, ThreatMgr::ModifyThreatByPercent(), MotionMaster::MovePoint(), NOT_STARTED, PosMandokir, SAY_OHGAN_DEAD, SAY_WATCH, UnitAI::SelectTarget(), Unit::SetImmuneToAll(), Creature::SetInCombatWithZone(), SPECIAL, SPELL_CAST_OK, SPELL_CHARGE, SPELL_EXECUTE, SPELL_FRENZY, SPELL_MANDOKIR_CLEAVE, SPELL_MORTAL_STRIKE, SPELL_OVERPOWER, SPELL_WATCH, SPELL_WHIRLWIND, UNIT_STATE_CASTING, UNIT_STATE_CHARGING, and CreatureAI::UpdateVictim().
Member Data Documentation
_chargeTarget
std::pair<ObjectGuid, float> boss_mandokir::boss_mandokirAI::_chargeTarget private
Referenced by CalculateThreat(), Reset(), SetGUID(), and UpdateAI().
_useExecute
bool boss_mandokir::boss_mandokirAI::_useExecute private
Referenced by DamageDealt(), and Reset().
killCount
uint8 boss_mandokir::boss_mandokirAI::killCount private
Referenced by KilledUnit(), and Reset().
reviveGUID
ObjectGuid boss_mandokir::boss_mandokirAI::reviveGUID private
Referenced by DoAction(), KilledUnit(), Reset(), and SetGUID().