AzerothCore: azerothcore-wotlk/src/server/game/Handlers/CalendarHandler.cpp File Reference
CalendarHandler.cpp File Reference
#include "ArenaTeamMgr.h"
#include "CalendarMgr.h"
#include "DatabaseEnv.h"
#include "DisableMgr.h"
#include "GameEventMgr.h"
#include "GameTime.h"
#include "GuildMgr.h"
#include "InstanceSaveMgr.h"
#include "Log.h"
#include "ObjectAccessor.h"
#include "Opcodes.h"
#include "Player.h"
#include "SocialMgr.h"
#include "WorldSession.h"
#include <utf8.h>
Functions
bool validUtf8String (WorldPacket &recvData, std::string &s, std::string action, ObjectGuid playerGUID)
Function Documentation
validUtf8String()
bool validUtf8String (WorldPacket & recvData, std::string & s, std::string action, ObjectGuid playerGUID)
{
    if (!utf8::is_valid(s.begin(), s.end()))
    {
        LOG_INFO("network.opcode", "CalendarHandler: Player ({}) attempt to {} an event with invalid name or description (packet modification)",
            playerGUID.ToString(), action);
        recvData.rfinish();
        return false;
    }
    return true;
}
References LOG_INFO, ByteBuffer::rfinish(), and ObjectGuid::ToString().
Referenced by WorldSession::HandleCalendarAddEvent(), and WorldSession::HandleCalendarUpdateEvent().