AzerothCore: lfg Namespace Reference
lfg Namespace Reference
User to World Communication
Classes
class Lfg5Guids
struct LFGDungeonData
class LfgGroupData
class LFGGroupScript
struct LfgJoinResultData
class LFGMgr
struct LfgPlayerBoot
class LfgPlayerData
struct LfgPlayerRewardData
class LFGPlayerScript
struct LfgProposal
struct LfgProposalPlayer
class LFGQueue
struct LfgQueueData
struct LfgQueueStatusData
struct LfgReward
struct LfgRoleCheck
struct LfgUpdateData
struct LfgWaitTime
struct RBEntryInfo
struct RBInternalInfo
Typedefs
typedef std::list< Lfg5Guids > Lfg5GuidsList
typedef std::set< uint32 > LfgDungeonSet
typedef std::map< uint32, uint32 > LfgLockMap
typedef std::map< ObjectGuid, LfgLockMap > LfgLockPartyMap
typedef GuidSet LfgGuidSet
typedef GuidList LfgGuidList
typedef std::map< ObjectGuid, uint8 > LfgRolesMap
typedef std::map< ObjectGuid, ObjectGuid > LfgGroupsMap
typedef std::map< uint8, LFGQueue > LfgQueueContainer
typedef std::multimap< uint32, LfgReward const * > LfgRewardContainer
typedef std::pair< LfgRewardContainer::const_iterator, LfgRewardContainer::const_iterator > LfgRewardContainerBounds
typedef std::map< uint8, LfgDungeonSet > LfgCachedDungeonContainer
typedef std::map< ObjectGuid, LfgAnswer > LfgAnswerContainer
typedef std::map< ObjectGuid, LfgRoleCheck > LfgRoleCheckContainer
typedef std::map< uint32, LfgProposal > LfgProposalContainer
typedef std::map< ObjectGuid, LfgProposalPlayer > LfgProposalPlayerContainer
typedef std::map< ObjectGuid, LfgPlayerBoot > LfgPlayerBootContainer
typedef std::map< ObjectGuid, LfgGroupData > LfgGroupDataContainer
typedef std::map< ObjectGuid, LfgPlayerData > LfgPlayerDataContainer
typedef std::unordered_map< uint32, LFGDungeonData > LFGDungeonContainer
typedef std::map< uint32, LfgWaitTime > LfgWaitTimesContainer
typedef std::map< ObjectGuid, LfgQueueData > LfgQueueDataContainer
typedef std::list< Lfg5Guids > LfgCompatibleContainer
Enumerations
enum LFGEnum {
LFG_TANKS_NEEDED = 1 ,
LFG_HEALERS_NEEDED = 1 ,
LFG_DPS_NEEDED = 3
}
enum LfgRoles {
PLAYER_ROLE_NONE = 0x00 ,
PLAYER_ROLE_LEADER = 0x01 ,
PLAYER_ROLE_TANK = 0x02 ,
PLAYER_ROLE_HEALER = 0x04 ,
PLAYER_ROLE_DAMAGE = 0x08
}
enum LfgUpdateType {
LFG_UPDATETYPE_DEFAULT = 0 ,
LFG_UPDATETYPE_LEADER_UNK1 = 1 ,
LFG_UPDATETYPE_LEAVE_RAIDBROWSER = 2 ,
LFG_UPDATETYPE_JOIN_RAIDBROWSER = 3 ,
LFG_UPDATETYPE_ROLECHECK_ABORTED = 4 ,
LFG_UPDATETYPE_JOIN_QUEUE = 5 ,
LFG_UPDATETYPE_ROLECHECK_FAILED = 6 ,
LFG_UPDATETYPE_REMOVED_FROM_QUEUE = 7 ,
LFG_UPDATETYPE_PROPOSAL_FAILED = 8 ,
LFG_UPDATETYPE_PROPOSAL_DECLINED = 9 ,
LFG_UPDATETYPE_GROUP_FOUND = 10 ,
LFG_UPDATETYPE_ADDED_TO_QUEUE = 12 ,
LFG_UPDATETYPE_PROPOSAL_BEGIN = 13 ,
LFG_UPDATETYPE_UPDATE_STATUS = 14 ,
LFG_UPDATETYPE_GROUP_MEMBER_OFFLINE = 15 ,
LFG_UPDATETYPE_GROUP_DISBAND_UNK16 = 16
}
enum LfgState {
LFG_STATE_NONE ,
LFG_STATE_ROLECHECK ,
LFG_STATE_QUEUED ,
LFG_STATE_PROPOSAL ,
LFG_STATE_BOOT ,
LFG_STATE_DUNGEON ,
LFG_STATE_FINISHED_DUNGEON ,
LFG_STATE_RAIDBROWSER
}
enum LfgLockStatusType {
LFG_LOCKSTATUS_INSUFFICIENT_EXPANSION = 1 ,
LFG_LOCKSTATUS_TOO_LOW_LEVEL = 2 ,
LFG_LOCKSTATUS_TOO_HIGH_LEVEL = 3 ,
LFG_LOCKSTATUS_TOO_LOW_GEAR_SCORE = 4 ,
LFG_LOCKSTATUS_TOO_HIGH_GEAR_SCORE = 5 ,
LFG_LOCKSTATUS_RAID_LOCKED = 6 ,
LFG_LOCKSTATUS_ATTUNEMENT_TOO_LOW_LEVEL = 1001 ,
LFG_LOCKSTATUS_ATTUNEMENT_TOO_HIGH_LEVEL = 1002 ,
LFG_LOCKSTATUS_QUEST_NOT_COMPLETED = 1022 ,
LFG_LOCKSTATUS_MISSING_ITEM = 1025 ,
LFG_LOCKSTATUS_NOT_IN_SEASON = 1031 ,
LFG_LOCKSTATUS_MISSING_ACHIEVEMENT = 1034
}
Instance lock types.
enum LfgAnswer {
LFG_ANSWER_PENDING = -1 ,
LFG_ANSWER_DENY = 0 ,
LFG_ANSWER_AGREE = 1
}
Answer state (Also used to check compatibilites)
enum LfgOptions {
LFG_OPTION_ENABLE_DUNGEON_FINDER = 0x01 ,
LFG_OPTION_ENABLE_RAID_BROWSER = 0x02 ,
LFG_OPTION_ENABLE_SEASONAL_BOSSES = 0x04
}
enum LFGMgrEnum {
LFG_TIME_ROLECHECK = 45 * IN_MILLISECONDS ,
LFG_TIME_BOOT = 120 ,
LFG_TIME_PROPOSAL = 40 ,
LFG_QUEUEUPDATE_INTERVAL = 8 * IN_MILLISECONDS ,
LFG_SPELL_DUNGEON_COOLDOWN = 71328 ,
LFG_SPELL_DUNGEON_DESERTER = 71041 ,
LFG_SPELL_LUCK_OF_THE_DRAW = 72221 ,
LFG_GROUP_KICK_VOTES_NEEDED = 3
}
enum LfgFlags {
LFG_FLAG_UNK1 = 0x1 ,
LFG_FLAG_UNK2 = 0x2 ,
LFG_FLAG_SEASONAL = 0x4 ,
LFG_FLAG_UNK3 = 0x8
}
enum LfgType {
LFG_TYPE_NONE = 0 ,
LFG_TYPE_DUNGEON = 1 ,
LFG_TYPE_RAID = 2 ,
LFG_TYPE_ZONE = 4 ,
LFG_TYPE_HEROIC = 5 ,
LFG_TYPE_RANDOM = 6
}
Determines the type of instance.
enum LfgProposalState {
LFG_PROPOSAL_INITIATING = 0 ,
LFG_PROPOSAL_FAILED = 1 ,
LFG_PROPOSAL_SUCCESS = 2
}
Proposal states.
enum LfgTeleportError {
LFG_TELEPORTERROR_OK = 0 ,
LFG_TELEPORTERROR_PLAYER_DEAD = 1 ,
LFG_TELEPORTERROR_FALLING = 2 ,
LFG_TELEPORTERROR_IN_VEHICLE = 3 ,
LFG_TELEPORTERROR_FATIGUE = 4 ,
LFG_TELEPORTERROR_INVALID_LOCATION = 6 ,
LFG_TELEPORTERROR_COMBAT = 8
}
Teleport errors.
enum LfgJoinResult {
LFG_JOIN_OK = 0 ,
LFG_JOIN_FAILED = 1 ,
LFG_JOIN_GROUPFULL = 2 ,
LFG_JOIN_INTERNAL_ERROR = 4 ,
LFG_JOIN_NOT_MEET_REQS = 5 ,
LFG_JOIN_PARTY_NOT_MEET_REQS = 6 ,
LFG_JOIN_MIXED_RAID_DUNGEON = 7 ,
LFG_JOIN_MULTI_REALM = 8 ,
LFG_JOIN_DISCONNECTED = 9 ,
LFG_JOIN_PARTY_INFO_FAILED = 10 ,
LFG_JOIN_DUNGEON_INVALID = 11 ,
LFG_JOIN_DESERTER = 12 ,
LFG_JOIN_PARTY_DESERTER = 13 ,
LFG_JOIN_RANDOM_COOLDOWN = 14 ,
LFG_JOIN_PARTY_RANDOM_COOLDOWN = 15 ,
LFG_JOIN_TOO_MUCH_MEMBERS = 16 ,
LFG_JOIN_USING_BG_SYSTEM = 17
}
Queue join results.
enum LfgRoleCheckState {
LFG_ROLECHECK_DEFAULT = 0 ,
LFG_ROLECHECK_FINISHED = 1 ,
LFG_ROLECHECK_INITIALITING = 2 ,
LFG_ROLECHECK_MISSING_ROLE = 3 ,
LFG_ROLECHECK_WRONG_ROLES = 4 ,
LFG_ROLECHECK_ABORTED = 5 ,
LFG_ROLECHECK_NO_ROLE = 6
}
Role check states.
enum LfgUpdateFlag {
LFG_UPDATE_FLAG_NONE = 0x00 ,
LFG_UPDATE_FLAG_CHARACTERINFO = 0x01 ,
LFG_UPDATE_FLAG_COMMENT = 0x02 ,
LFG_UPDATE_FLAG_GROUPLEADER = 0x04 ,
LFG_UPDATE_FLAG_GROUPGUID = 0x08 ,
LFG_UPDATE_FLAG_ROLES = 0x10 ,
LFG_UPDATE_FLAG_AREA = 0x20 ,
LFG_UPDATE_FLAG_STATUS = 0x40 ,
LFG_UPDATE_FLAG_BINDED = 0x80
}
enum LfgSeasonalDungeons {
LFG_DUNGEON_HEADLESS_HORSEMAN = 285 ,
LFG_DUNGEON_FROST_LORD_AHUNE = 286 ,
LFG_DUNGEON_COREN_DIREBREW = 287 ,
LFG_DUNGEON_CROWN_CHEMICAL_CO = 288
}
enum LfgCompatibility {
LFG_COMPATIBILITY_PENDING ,
LFG_INCOMPATIBLES_WRONG_GROUP_SIZE ,
LFG_INCOMPATIBLES_TOO_MUCH_PLAYERS ,
LFG_INCOMPATIBLES_MULTIPLE_LFG_GROUPS ,
LFG_INCOMPATIBLES_HAS_IGNORES ,
LFG_INCOMPATIBLES_NO_ROLES ,
LFG_INCOMPATIBLES_NO_DUNGEONS ,
LFG_COMPATIBLES_WITH_LESS_PLAYERS ,
LFG_COMPATIBLES_MATCH
}
Functions
std::string ConcatenateDungeons (LfgDungeonSet const &dungeons)
std::string GetRolesString (uint8 roles)
std::string GetStateString (LfgState state)
template<typename T , FMT_ENABLE_IF(std::is_enum_v< T >) >
auto format_as (T f)
void AddSC_LFGScripts ()
Typedef Documentation
Lfg5GuidsList
typedef std::list<Lfg5Guids> lfg::Lfg5GuidsList
LfgAnswerContainer
typedef std::map<ObjectGuid, LfgAnswer> lfg::LfgAnswerContainer
LfgCachedDungeonContainer
typedef std::map<uint8, LfgDungeonSet> lfg::LfgCachedDungeonContainer
LfgCompatibleContainer
typedef std::list<Lfg5Guids> lfg::LfgCompatibleContainer
LFGDungeonContainer
typedef std::unordered_map<uint32, LFGDungeonData> lfg::LFGDungeonContainer
LfgDungeonSet
typedef std::set<uint32> lfg::LfgDungeonSet
LfgGroupDataContainer
typedef std::map<ObjectGuid, LfgGroupData> lfg::LfgGroupDataContainer
LfgGroupsMap
typedef std::map<ObjectGuid, ObjectGuid> lfg::LfgGroupsMap
LfgGuidList
typedef GuidList lfg::LfgGuidList
LfgGuidSet
typedef GuidSet lfg::LfgGuidSet
LfgLockMap
typedef std::map<uint32, uint32> lfg::LfgLockMap
LfgLockPartyMap
typedef std::map<ObjectGuid, LfgLockMap> lfg::LfgLockPartyMap
LfgPlayerBootContainer
typedef std::map<ObjectGuid, LfgPlayerBoot> lfg::LfgPlayerBootContainer
LfgPlayerDataContainer
typedef std::map<ObjectGuid, LfgPlayerData> lfg::LfgPlayerDataContainer
LfgProposalContainer
typedef std::map<uint32, LfgProposal> lfg::LfgProposalContainer
LfgProposalPlayerContainer
typedef std::map<ObjectGuid, LfgProposalPlayer> lfg::LfgProposalPlayerContainer
LfgQueueContainer
typedef std::map<uint8, LFGQueue> lfg::LfgQueueContainer
LfgQueueDataContainer
typedef std::map<ObjectGuid, LfgQueueData> lfg::LfgQueueDataContainer
LfgRewardContainer
typedef std::multimap<uint32, LfgReward const*> lfg::LfgRewardContainer
LfgRewardContainerBounds
typedef std::pair<LfgRewardContainer::const_iterator, LfgRewardContainer::const_iterator> lfg::LfgRewardContainerBounds
LfgRoleCheckContainer
typedef std::map<ObjectGuid, LfgRoleCheck> lfg::LfgRoleCheckContainer
LfgRolesMap
typedef std::map<ObjectGuid, uint8> lfg::LfgRolesMap
LfgWaitTimesContainer
typedef std::map<uint32, LfgWaitTime> lfg::LfgWaitTimesContainer
Enumeration Type Documentation
LfgAnswer
enum lfg::LfgAnswer
Answer state (Also used to check compatibilites)
Enumerator
LFG_ANSWER_PENDING
LFG_ANSWER_DENY
LFG_ANSWER_AGREE
    {
        LFG_ANSWER_PENDING                           = -1,
        LFG_ANSWER_DENY                              = 0,
        LFG_ANSWER_AGREE                             = 1
    };
LfgCompatibility
enum lfg::LfgCompatibility
Enumerator
LFG_COMPATIBILITY_PENDING
LFG_INCOMPATIBLES_WRONG_GROUP_SIZE
LFG_INCOMPATIBLES_TOO_MUCH_PLAYERS
LFG_INCOMPATIBLES_MULTIPLE_LFG_GROUPS
LFG_INCOMPATIBLES_HAS_IGNORES
LFG_INCOMPATIBLES_NO_ROLES
LFG_INCOMPATIBLES_NO_DUNGEONS
LFG_COMPATIBLES_WITH_LESS_PLAYERS
LFG_COMPATIBLES_MATCH
    {
        LFG_COMPATIBILITY_PENDING,
        LFG_INCOMPATIBLES_WRONG_GROUP_SIZE,
        LFG_INCOMPATIBLES_TOO_MUCH_PLAYERS,
        LFG_INCOMPATIBLES_MULTIPLE_LFG_GROUPS,
        LFG_INCOMPATIBLES_HAS_IGNORES,
        LFG_INCOMPATIBLES_NO_ROLES,
        LFG_INCOMPATIBLES_NO_DUNGEONS,
        LFG_COMPATIBLES_WITH_LESS_PLAYERS,                     // Values under this = not compatible (do not modify order)
        LFG_COMPATIBLES_MATCH                                  // Must be the last one
    };
LFGEnum
enum lfg::LFGEnum
Enumerator
LFG_TANKS_NEEDED
LFG_HEALERS_NEEDED
LFG_DPS_NEEDED
    {
        LFG_TANKS_NEEDED                             = 1,
        LFG_HEALERS_NEEDED                           = 1,
        LFG_DPS_NEEDED                               = 3
    };
LfgFlags
enum lfg::LfgFlags
Enumerator
LFG_FLAG_UNK1
LFG_FLAG_UNK2
LFG_FLAG_SEASONAL
LFG_FLAG_UNK3
    {
        LFG_FLAG_UNK1                                = 0x1,
        LFG_FLAG_UNK2                                = 0x2,
        LFG_FLAG_SEASONAL                            = 0x4,
        LFG_FLAG_UNK3                                = 0x8
    };
LfgJoinResult
enum lfg::LfgJoinResult
Queue join results.
Enumerator
LFG_JOIN_OK
LFG_JOIN_FAILED
LFG_JOIN_GROUPFULL
LFG_JOIN_INTERNAL_ERROR
LFG_JOIN_NOT_MEET_REQS
LFG_JOIN_PARTY_NOT_MEET_REQS
LFG_JOIN_MIXED_RAID_DUNGEON
LFG_JOIN_MULTI_REALM
LFG_JOIN_DISCONNECTED
LFG_JOIN_PARTY_INFO_FAILED
LFG_JOIN_DUNGEON_INVALID
LFG_JOIN_DESERTER
LFG_JOIN_PARTY_DESERTER
LFG_JOIN_RANDOM_COOLDOWN
LFG_JOIN_PARTY_RANDOM_COOLDOWN
LFG_JOIN_TOO_MUCH_MEMBERS
LFG_JOIN_USING_BG_SYSTEM
    {
        // 3 = No client reaction | 18 = "Rolecheck failed"
        LFG_JOIN_OK                                  = 0,      // Joined (no client msg)
        LFG_JOIN_FAILED                              = 1,      // RoleCheck Failed
        LFG_JOIN_GROUPFULL                           = 2,      // Your group is full
        LFG_JOIN_INTERNAL_ERROR                      = 4,      // Internal LFG Error
        LFG_JOIN_NOT_MEET_REQS                       = 5,      // You do not meet the requirements for the chosen dungeons
        LFG_JOIN_PARTY_NOT_MEET_REQS                 = 6,      // One or more party members do not meet the requirements for the chosen dungeons
        LFG_JOIN_MIXED_RAID_DUNGEON                  = 7,      // You cannot mix dungeons, raids, and random when picking dungeons
        LFG_JOIN_MULTI_REALM                         = 8,      // The dungeon you chose does not support players from multiple realms
        LFG_JOIN_DISCONNECTED                        = 9,      // One or more party members are pending invites or disconnected
        LFG_JOIN_PARTY_INFO_FAILED                   = 10,     // Could not retrieve information about some party members
        LFG_JOIN_DUNGEON_INVALID                     = 11,     // One or more dungeons was not valid
        LFG_JOIN_DESERTER                            = 12,     // You can not queue for dungeons until your deserter debuff wears off
        LFG_JOIN_PARTY_DESERTER                      = 13,     // One or more party members has a deserter debuff
        LFG_JOIN_RANDOM_COOLDOWN                     = 14,     // You can not queue for random dungeons while on random dungeon cooldown
        LFG_JOIN_PARTY_RANDOM_COOLDOWN               = 15,     // One or more party members are on random dungeon cooldown
        LFG_JOIN_TOO_MUCH_MEMBERS                    = 16,     // You can not enter dungeons with more that 5 party members
        LFG_JOIN_USING_BG_SYSTEM                     = 17      // You can not use the dungeon system while in BG or arenas
    };
LfgLockStatusType
enum lfg::LfgLockStatusType
Instance lock types.
Enumerator
LFG_LOCKSTATUS_INSUFFICIENT_EXPANSION
LFG_LOCKSTATUS_TOO_LOW_LEVEL
LFG_LOCKSTATUS_TOO_HIGH_LEVEL
LFG_LOCKSTATUS_TOO_LOW_GEAR_SCORE
LFG_LOCKSTATUS_TOO_HIGH_GEAR_SCORE
LFG_LOCKSTATUS_RAID_LOCKED
LFG_LOCKSTATUS_ATTUNEMENT_TOO_LOW_LEVEL
LFG_LOCKSTATUS_ATTUNEMENT_TOO_HIGH_LEVEL
LFG_LOCKSTATUS_QUEST_NOT_COMPLETED
LFG_LOCKSTATUS_MISSING_ITEM
LFG_LOCKSTATUS_NOT_IN_SEASON
LFG_LOCKSTATUS_MISSING_ACHIEVEMENT
    {
        LFG_LOCKSTATUS_INSUFFICIENT_EXPANSION        = 1,
        LFG_LOCKSTATUS_TOO_LOW_LEVEL                 = 2,
        LFG_LOCKSTATUS_TOO_HIGH_LEVEL                = 3,
        LFG_LOCKSTATUS_TOO_LOW_GEAR_SCORE            = 4,
        LFG_LOCKSTATUS_TOO_HIGH_GEAR_SCORE           = 5,
        LFG_LOCKSTATUS_RAID_LOCKED                   = 6,
        LFG_LOCKSTATUS_ATTUNEMENT_TOO_LOW_LEVEL      = 1001,
        LFG_LOCKSTATUS_ATTUNEMENT_TOO_HIGH_LEVEL     = 1002,
        LFG_LOCKSTATUS_QUEST_NOT_COMPLETED           = 1022,
        LFG_LOCKSTATUS_MISSING_ITEM                  = 1025,
        LFG_LOCKSTATUS_NOT_IN_SEASON                 = 1031,
        LFG_LOCKSTATUS_MISSING_ACHIEVEMENT           = 1034
    };
LFGMgrEnum
enum lfg::LFGMgrEnum
Enumerator
LFG_TIME_ROLECHECK
LFG_TIME_BOOT
LFG_TIME_PROPOSAL
LFG_QUEUEUPDATE_INTERVAL
LFG_SPELL_DUNGEON_COOLDOWN
LFG_SPELL_DUNGEON_DESERTER
LFG_SPELL_LUCK_OF_THE_DRAW
LFG_GROUP_KICK_VOTES_NEEDED
    {
        LFG_TIME_ROLECHECK                           = 45 * IN_MILLISECONDS,
        LFG_TIME_BOOT                                = 120,
        LFG_TIME_PROPOSAL                            = 40,
        LFG_QUEUEUPDATE_INTERVAL                     = 8 * IN_MILLISECONDS,
        LFG_SPELL_DUNGEON_COOLDOWN                   = 71328,
        LFG_SPELL_DUNGEON_DESERTER                   = 71041,
        LFG_SPELL_LUCK_OF_THE_DRAW                   = 72221,
        LFG_GROUP_KICK_VOTES_NEEDED                  = 3
    };
LfgOptions
enum lfg::LfgOptions
Enumerator
LFG_OPTION_ENABLE_DUNGEON_FINDER
LFG_OPTION_ENABLE_RAID_BROWSER
LFG_OPTION_ENABLE_SEASONAL_BOSSES
    {
        LFG_OPTION_ENABLE_DUNGEON_FINDER             = 0x01,
        LFG_OPTION_ENABLE_RAID_BROWSER               = 0x02,
        LFG_OPTION_ENABLE_SEASONAL_BOSSES            = 0x04
    };
LfgProposalState
enum lfg::LfgProposalState
Proposal states.
Enumerator
LFG_PROPOSAL_INITIATING
LFG_PROPOSAL_FAILED
LFG_PROPOSAL_SUCCESS
    {
        LFG_PROPOSAL_INITIATING                      = 0,
        LFG_PROPOSAL_FAILED                          = 1,
        LFG_PROPOSAL_SUCCESS                         = 2
    };
LfgRoleCheckState
enum lfg::LfgRoleCheckState
Role check states.
Enumerator
LFG_ROLECHECK_DEFAULT
LFG_ROLECHECK_FINISHED
LFG_ROLECHECK_INITIALITING
LFG_ROLECHECK_MISSING_ROLE
LFG_ROLECHECK_WRONG_ROLES
LFG_ROLECHECK_ABORTED
LFG_ROLECHECK_NO_ROLE
    {
        LFG_ROLECHECK_DEFAULT                        = 0,      // Internal use = Not initialized.
        LFG_ROLECHECK_FINISHED                       = 1,      // Role check finished
        LFG_ROLECHECK_INITIALITING                   = 2,      // Role check begins
        LFG_ROLECHECK_MISSING_ROLE                   = 3,      // Someone didn't selected a role after 2 mins
        LFG_ROLECHECK_WRONG_ROLES                    = 4,      // Can't form a group with that role selection
        LFG_ROLECHECK_ABORTED                        = 5,      // Someone leave the group
        LFG_ROLECHECK_NO_ROLE                        = 6       // Someone selected no role
    };
LfgRoles
enum lfg::LfgRoles
Enumerator
PLAYER_ROLE_NONE
PLAYER_ROLE_LEADER
PLAYER_ROLE_TANK
PLAYER_ROLE_HEALER
PLAYER_ROLE_DAMAGE
    {
        PLAYER_ROLE_NONE                             = 0x00,
        PLAYER_ROLE_LEADER                           = 0x01,
        PLAYER_ROLE_TANK                             = 0x02,
        PLAYER_ROLE_HEALER                           = 0x04,
        PLAYER_ROLE_DAMAGE                           = 0x08
    };
LfgSeasonalDungeons
enum lfg::LfgSeasonalDungeons
Enumerator
LFG_DUNGEON_HEADLESS_HORSEMAN
LFG_DUNGEON_FROST_LORD_AHUNE
LFG_DUNGEON_COREN_DIREBREW
LFG_DUNGEON_CROWN_CHEMICAL_CO
    {
        LFG_DUNGEON_HEADLESS_HORSEMAN   = 285,
        LFG_DUNGEON_FROST_LORD_AHUNE    = 286,
        LFG_DUNGEON_COREN_DIREBREW      = 287,
        LFG_DUNGEON_CROWN_CHEMICAL_CO   = 288
    };
LfgState
enum lfg::LfgState
Enumerator
LFG_STATE_NONE
LFG_STATE_ROLECHECK
LFG_STATE_QUEUED
LFG_STATE_PROPOSAL
LFG_STATE_BOOT
LFG_STATE_DUNGEON
LFG_STATE_FINISHED_DUNGEON
LFG_STATE_RAIDBROWSER
    {
        LFG_STATE_NONE,                                        // Not using LFG / LFR
        LFG_STATE_ROLECHECK,                                   // Rolecheck active
        LFG_STATE_QUEUED,                                      // Queued
        LFG_STATE_PROPOSAL,                                    // Proposal active
        LFG_STATE_BOOT,                                        // Vote kick active
        LFG_STATE_DUNGEON,                                     // In LFG Group, in a Dungeon
        LFG_STATE_FINISHED_DUNGEON,                            // In LFG Group, in a finished Dungeon
        LFG_STATE_RAIDBROWSER                                  // Using Raid finder
    };
LfgTeleportError
enum lfg::LfgTeleportError
Teleport errors.
Enumerator
LFG_TELEPORTERROR_OK
LFG_TELEPORTERROR_PLAYER_DEAD
LFG_TELEPORTERROR_FALLING
LFG_TELEPORTERROR_IN_VEHICLE
LFG_TELEPORTERROR_FATIGUE
LFG_TELEPORTERROR_INVALID_LOCATION
LFG_TELEPORTERROR_COMBAT
    {
        // 7 = "You can't do that right now" | 5 = No client reaction
        LFG_TELEPORTERROR_OK                         = 0,      // Internal use
        LFG_TELEPORTERROR_PLAYER_DEAD                = 1,
        LFG_TELEPORTERROR_FALLING                    = 2,
        LFG_TELEPORTERROR_IN_VEHICLE                 = 3,
        LFG_TELEPORTERROR_FATIGUE                    = 4,
        LFG_TELEPORTERROR_INVALID_LOCATION           = 6,
        LFG_TELEPORTERROR_COMBAT                     = 8       // FIXME - It can be 7 or 8 (Need proper data)
    };
LfgType
enum lfg::LfgType
Determines the type of instance.
Enumerator
LFG_TYPE_NONE
LFG_TYPE_DUNGEON
LFG_TYPE_RAID
LFG_TYPE_ZONE
LFG_TYPE_HEROIC
LFG_TYPE_RANDOM
    {
        LFG_TYPE_NONE                                = 0,
        LFG_TYPE_DUNGEON                             = 1,
        LFG_TYPE_RAID                                = 2,
        LFG_TYPE_ZONE                                = 4,
        LFG_TYPE_HEROIC                              = 5,
        LFG_TYPE_RANDOM                              = 6
    };
LfgUpdateFlag
enum lfg::LfgUpdateFlag
Enumerator
LFG_UPDATE_FLAG_NONE
LFG_UPDATE_FLAG_CHARACTERINFO
LFG_UPDATE_FLAG_COMMENT
LFG_UPDATE_FLAG_GROUPLEADER
LFG_UPDATE_FLAG_GROUPGUID
LFG_UPDATE_FLAG_ROLES
LFG_UPDATE_FLAG_AREA
LFG_UPDATE_FLAG_STATUS
LFG_UPDATE_FLAG_BINDED
    {
        LFG_UPDATE_FLAG_NONE          = 0x00,
        LFG_UPDATE_FLAG_CHARACTERINFO = 0x01,
        LFG_UPDATE_FLAG_COMMENT       = 0x02,
        LFG_UPDATE_FLAG_GROUPLEADER   = 0x04,
        LFG_UPDATE_FLAG_GROUPGUID     = 0x08,
        LFG_UPDATE_FLAG_ROLES         = 0x10,
        LFG_UPDATE_FLAG_AREA          = 0x20,
        LFG_UPDATE_FLAG_STATUS        = 0x40,
        LFG_UPDATE_FLAG_BINDED        = 0x80
    };
LfgUpdateType
enum lfg::LfgUpdateType
Enumerator
LFG_UPDATETYPE_DEFAULT
LFG_UPDATETYPE_LEADER_UNK1
LFG_UPDATETYPE_LEAVE_RAIDBROWSER
LFG_UPDATETYPE_JOIN_RAIDBROWSER
LFG_UPDATETYPE_ROLECHECK_ABORTED
LFG_UPDATETYPE_JOIN_QUEUE
LFG_UPDATETYPE_ROLECHECK_FAILED
LFG_UPDATETYPE_REMOVED_FROM_QUEUE
LFG_UPDATETYPE_PROPOSAL_FAILED
LFG_UPDATETYPE_PROPOSAL_DECLINED
LFG_UPDATETYPE_GROUP_FOUND
LFG_UPDATETYPE_ADDED_TO_QUEUE
LFG_UPDATETYPE_PROPOSAL_BEGIN
LFG_UPDATETYPE_UPDATE_STATUS
LFG_UPDATETYPE_GROUP_MEMBER_OFFLINE
LFG_UPDATETYPE_GROUP_DISBAND_UNK16
    {
        LFG_UPDATETYPE_DEFAULT                       = 0,      // Internal Use
        LFG_UPDATETYPE_LEADER_UNK1                   = 1,      // FIXME: At group leave
        LFG_UPDATETYPE_LEAVE_RAIDBROWSER             = 2,
        LFG_UPDATETYPE_JOIN_RAIDBROWSER              = 3,
        LFG_UPDATETYPE_ROLECHECK_ABORTED             = 4,
        LFG_UPDATETYPE_JOIN_QUEUE                    = 5,
        LFG_UPDATETYPE_ROLECHECK_FAILED              = 6,
        LFG_UPDATETYPE_REMOVED_FROM_QUEUE            = 7,
        LFG_UPDATETYPE_PROPOSAL_FAILED               = 8,
        LFG_UPDATETYPE_PROPOSAL_DECLINED             = 9,
        LFG_UPDATETYPE_GROUP_FOUND                   = 10,
        LFG_UPDATETYPE_ADDED_TO_QUEUE                = 12,
        LFG_UPDATETYPE_PROPOSAL_BEGIN                = 13,
        LFG_UPDATETYPE_UPDATE_STATUS                 = 14,
        LFG_UPDATETYPE_GROUP_MEMBER_OFFLINE          = 15,
        LFG_UPDATETYPE_GROUP_DISBAND_UNK16           = 16,     // FIXME: Sometimes at group disband
    };
Function Documentation
AddSC_LFGScripts()
void lfg::AddSC_LFGScripts ()
    {
        new LFGPlayerScript();
        new LFGGroupScript();
    }
Referenced by ScriptMgr::Initialize().
ConcatenateDungeons()
std::string lfg::ConcatenateDungeons (LfgDungeonSet const & dungeons)
    {
        std::string dungeonstr = "";
        if (!dungeons.empty())
        {
            std::ostringstream o;
            LfgDungeonSet::const_iterator it = dungeons.begin();
            o << (*it);
            for (++it; it != dungeons.end(); ++it)
                o << ", " << uint32(*it);
            dungeonstr = o.str();
        }
        return dungeonstr;
    }
Referenced by GetPlayerInfo().
format_as()
template<typename T , FMT_ENABLE_IF(std::is_enum_v< T >) > auto lfg::format_as (T f)
{ return fmt::underlying(f); }
GetRolesString()
std::string lfg::GetRolesString (uint8 roles)
    {
        std::string rolesstr = "";
        if (roles & PLAYER_ROLE_TANK)
            rolesstr.append(sObjectMgr->GetAcoreStringForDBCLocale(LANG_LFG_ROLE_TANK));
        if (roles & PLAYER_ROLE_HEALER)
        {
            if (!rolesstr.empty())
                rolesstr.append(", ");
            rolesstr.append(sObjectMgr->GetAcoreStringForDBCLocale(LANG_LFG_ROLE_HEALER));
        }
        if (roles & PLAYER_ROLE_DAMAGE)
        {
            if (!rolesstr.empty())
                rolesstr.append(", ");
            rolesstr.append(sObjectMgr->GetAcoreStringForDBCLocale(LANG_LFG_ROLE_DAMAGE));
        }
        if (roles & PLAYER_ROLE_LEADER)
        {
            if (!rolesstr.empty())
                rolesstr.append(", ");
            rolesstr.append(sObjectMgr->GetAcoreStringForDBCLocale(LANG_LFG_ROLE_LEADER));
        }
        if (rolesstr.empty())
            rolesstr.append(sObjectMgr->GetAcoreStringForDBCLocale(LANG_LFG_ROLE_NONE));
        return rolesstr;
    }
References LANG_LFG_ROLE_DAMAGE, LANG_LFG_ROLE_HEALER, LANG_LFG_ROLE_LEADER, LANG_LFG_ROLE_NONE, LANG_LFG_ROLE_TANK, PLAYER_ROLE_DAMAGE, PLAYER_ROLE_HEALER, PLAYER_ROLE_LEADER, PLAYER_ROLE_TANK, and sObjectMgr.
Referenced by GetPlayerInfo().
GetStateString()
std::string lfg::GetStateString (LfgState state)
    {
        int32 entry = LANG_LFG_ERROR;
        switch (state)
        {
            case LFG_STATE_NONE:
                entry = LANG_LFG_STATE_NONE;
                break;
            case LFG_STATE_ROLECHECK:
                entry = LANG_LFG_STATE_ROLECHECK;
                break;
            case LFG_STATE_QUEUED:
                entry = LANG_LFG_STATE_QUEUED;
                break;
            case LFG_STATE_PROPOSAL:
                entry = LANG_LFG_STATE_PROPOSAL;
                break;
            case LFG_STATE_DUNGEON:
                entry = LANG_LFG_STATE_DUNGEON;
                break;
            case LFG_STATE_BOOT:
                entry = LANG_LFG_STATE_BOOT;
                break;
            case LFG_STATE_FINISHED_DUNGEON:
                entry = LANG_LFG_STATE_FINISHED_DUNGEON;
                break;
            case LFG_STATE_RAIDBROWSER:
                entry = LANG_LFG_STATE_RAIDBROWSER;
                break;
        }
        return std::string(sObjectMgr->GetAcoreStringForDBCLocale(entry));
    }
References LANG_LFG_ERROR, LANG_LFG_STATE_BOOT, LANG_LFG_STATE_DUNGEON, LANG_LFG_STATE_FINISHED_DUNGEON, LANG_LFG_STATE_NONE, LANG_LFG_STATE_PROPOSAL, LANG_LFG_STATE_QUEUED, LANG_LFG_STATE_RAIDBROWSER, LANG_LFG_STATE_ROLECHECK, LFG_STATE_BOOT, LFG_STATE_DUNGEON, LFG_STATE_FINISHED_DUNGEON, LFG_STATE_NONE, LFG_STATE_PROPOSAL, LFG_STATE_QUEUED, LFG_STATE_RAIDBROWSER, LFG_STATE_ROLECHECK, and sObjectMgr.
Referenced by GetPlayerInfo(), lfg_commandscript::HandleLfgGroupInfoCommand(), and lfg::LFGMgr::SetState().