AzerothCore: UnitAI Class Reference
UnitAI Class Reference abstract
#include "UnitAI.h"
Public Member Functions
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Static Public Member Functions
static void FillAISpellInfo ()
Static Public Attributes
static AISpellInfoType * AISpellInfo
Protected Attributes
Unit *const me
Private Member Functions
ThreatMgr & GetThreatMgr ()
void SortByDistance (std::list< Unit * > &list, bool ascending=true)
Detailed Description
Constructor & Destructor Documentation
UnitAI()
UnitAI::UnitAI (Unit * unit) inline explicit
: me(unit) {}
~UnitAI()
virtual UnitAI::~UnitAI () inline virtual
{}
Member Function Documentation
AttackStart()
void UnitAI::AttackStart (Unit * victim) virtual
Reimplemented in NPCStaveQuestAI, VehicleAI, PassiveAI, NullCreatureAI, ScriptedAI, FollowerAI, npc_chesspiece, npc_demon_chain, npc_janalai_hatcher, npc_dark_iron_attack_mole_machine, npc_dark_iron_guzzler, npc_brewfest_super_brew_trigger, boss_headless_horseman_pumpkin, npc_pilgrims_bounty_chair, npc_taretha::npc_tarethaAI, npc_medivh_bm, npc_depth_charge::npc_depth_chargeAI, npc_amanitar_mushrooms, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, npc_pos_leader::npc_pos_leaderAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_the_lich_king_controller::npc_the_lich_king_controllerAI, npc_valithria_cloud::npc_valithria_cloudAI, npc_vortex_ride::npc_vortex_rideAI, npc_scion_of_eternity::npc_scion_of_eternityAI, npc_hover_disk::npc_hover_diskAI, npc_alexstrasza::npc_alexstraszaAI, npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI, npc_spark_of_ionar::npc_spark_of_ionarAI, npc_assembly_lightning::npc_assembly_lightningAI, boss_flame_leviathan_seat::boss_flame_leviathan_seatAI, npc_mimirons_inferno::npc_mimirons_infernoAI, boss_kologarn_arms::boss_kologarn_armsAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI, npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI, boss_thorim_sif::boss_thorim_sifAI, boss_thorim_lightning_orb::boss_thorim_lightning_orbAI, boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI, npc_xt002_heart::npc_xt002_heartAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_yoggsaron::boss_yoggsaronAI, npc_ichor_globule::npc_ichor_globuleAI, npc_warmage_coldarra::npc_warmage_coldarraAI, npc_mageguard_dalaran::npc_mageguard_dalaranAI, npc_frosthound::npc_frosthoundAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_icefang::npc_icefangAI, boss_illidari_council, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_vazruden_the_herald, npc_warden_mellichar::npc_warden_mellicharAI, npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, npc_ritual_channeler::npc_ritual_channelerAI, PossessedAI, PetAI, boss_ragnaros::boss_ragnarosAI, npc_gunship_mage::npc_gunship_mageAI, npc_gunship_gunner::npc_gunship_gunnerAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, CasterAI, TotemAI, npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI, boss_drekthar::boss_drektharAI, boss_vanndar::boss_vanndarAI, boss_priestess_lackey_commonAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, boss_malygos::boss_malygosAI, npc_nexus_lord::npc_nexus_lordAI, boss_swamplord_muselek, ArcherAI, TurretAI, npc_escortAI, SmartAI, boss_nightbane, boss_shade_of_aran, npc_koltira_deathweaver::npc_koltira_deathweaverAI, boss_brutallus, boss_kiljaeden, npc_daphne_stilwell::npc_daphne_stilwellAI, boss_halazzi, npc_hyjal_ground_trash, npc_hyjal_gargoyle, npc_hyjal_frost_wyrm, boss_veklor, npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI, npc_twilight_volunteer, boss_halion::boss_halionAI, boss_faction_championsAI, npc_snobold_vassal::npc_snobold_vassalAI, boss_jormungarAI, boss_icehowl::boss_icehowlAI, npc_ghostly_priest::npc_ghostly_priestAI, npc_phantom_mage::npc_phantom_mageAI, npc_shadowy_mercenary::npc_shadowy_mercenaryAI, npc_spectral_footman::npc_spectral_footmanAI, npc_tortured_rifleman::npc_tortured_riflemanAI, npc_living_mojo::npc_living_mojoAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, npc_dark_nucleus::npc_dark_nucleusAI, npc_ball_of_flame::npc_ball_of_flameAI, npc_vengeful_shade::npc_vengeful_shadeAI, npc_raging_spirit::npc_raging_spiritAI, npc_suppresser::npc_suppresserAI, npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI, npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI, npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI, npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI, npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI, boss_four_horsemen::boss_four_horsemenAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, boss_magus_telestra, boss_urom::boss_uromAI, npc_hol_monument::npc_hol_monumentAI, boss_algalon_the_observer::boss_algalon_the_observerAI, boss_flame_leviathan::boss_flame_leviathanAI, npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI, npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI, boss_kologarn::boss_kologarnAI, boss_mimiron::boss_mimironAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, boss_keleseth, boss_archavon::boss_archavonAI, boss_emalon::boss_emalonAI, boss_koralon::boss_koralonAI, boss_toravon::boss_toravonAI, violet_hold_trashAI, npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI, npc_ravenous_worg::npc_ravenous_worgAI, boss_ambassador_hellmaw, boss_high_nethermancer_zerevor, boss_lady_malande, boss_leotheras_the_blind, boss_the_lurker_below, boss_olm_the_summoner, boss_kiggler_the_crazed, boss_krosh_firehand, boss_nazan, npc_millhouse_manastorm::npc_millhouse_manastormAI, boss_high_astromancer_solarian, boss_kaelthas, npc_capernian, npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI, and npc_pet_gen_gnomish_flame_turret.
{
    if (victim && me->Attack(victim, true))
        me->GetMotionMaster()->MoveChase(victim);
}
References Unit::Attack(), Unit::GetMotionMaster(), me, and MotionMaster::MoveChase().
Referenced by ScriptedAI::AttackStart(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::AttackStart(), boss_brutallus::AttackStart(), boss_halazzi::AttackStart(), boss_halion::boss_halionAI::AttackStart(), boss_faction_championsAI::AttackStart(), npc_ravenous_worg::npc_ravenous_worgAI::AttackStart(), boss_kaelthas::AttackStart(), npc_anubisath_sentinel::aqsentinelAI::CallBuddiesToAttack(), instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::CallNextRajaxxLeader(), Unit::CombatStart(), Spell::DoAllEffectOnTarget(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), AssistDelayEvent::Execute(), StartMovementEvent::Execute(), spell_random_aggro::HandleOnHit(), WorldSession::HandlePetActionHelper(), spell_the_lich_king_vile_spirit_move_target_search::HandleScript(), spell_pursue::HandleScript(), npc_beryl_sorcerer::npc_beryl_sorcererAI::JustEngagedWith(), npc_toc_warlock::npc_toc_warlockAI::JustSummoned(), npc_toc_hunter::npc_toc_hunterAI::JustSummoned(), npc_toc_boomkin::npc_toc_boomkinAI::JustSummoned(), boss_maexxna::boss_maexxnaAI::JustSummoned(), npc_frosthound::npc_frosthoundAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::JustSummoned(), boss_urom::boss_uromAI::JustSummoned(), npc_hor_lich_king::npc_hor_lich_kingAI::JustSummoned(), WorldBossAI::JustSummoned(), npc_grimstone::npc_grimstoneAI::JustSummoned(), boss_gyth::boss_gythAI::JustSummoned(), boss_curator::JustSummoned(), boss_midnight::JustSummoned(), boss_nightbane::JustSummoned(), boss_sacrolash::JustSummoned(), npc_demonic_vapor_trail::JustSummoned(), boss_onyxia::JustSummoned(), boss_black_knight::boss_black_knightAI::JustSummoned(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), npc_precious_icc::npc_precious_iccAI::JustSummoned(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::JustSummoned(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::JustSummoned(), boss_gluth::boss_gluthAI::JustSummoned(), boss_gothik::boss_gothikAI::JustSummoned(), boss_volkhan::boss_volkhanAI::JustSummoned(), boss_nexusprince_shaffar::JustSummoned(), npc_akama_illidan::JustSummoned(), npc_creature_generator_akama::JustSummoned(), boss_the_black_stalker::JustSummoned(), boss_nethermancer_sepethrea::JustSummoned(), npc_nelson::npc_nelsonAI::JustSummoned(), boss_balinda::JustSummoned(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::JustSummoned(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::JustSummoned(), npc_thrall_bfu::npc_thrall_bfuAI::JustSummoned(), npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::JustSummoned(), boss_archimonde::JustSummoned(), npc_muglash::npc_muglashAI::JustSummoned(), npc_kaya_flathoof::npc_kaya_flathoofAI::JustSummoned(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::JustSummoned(), npc_ame::npc_ameAI::JustSummoned(), npc_emily::npc_emilyAI::JustSummoned(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::JustSummoned(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), npc_kurenai_captive::npc_kurenai_captiveAI::JustSummoned(), npc_bessy::npc_bessyAI::JustSummoned(), npc_buru_egg::JustSummoned(), CreatureGroup::MemberEngagingTarget(), CreatureAI::MoveInLineOfSight(), npc_air_force_bots::npc_air_force_botsAI::MoveInLineOfSight(), npc_pet_mage_mirror_image::MySelectNextTarget(), npc_ulduar_expedition_commander::OnGossipSelect(), boss_azuregos::OnGossipSelect(), Acore::CallOfHelpCreatureInRangeDo::operator()(), Unit::PetSpellFail(), SmartScript::ProcessAction(), npc_heated_battle::npc_heated_battleAI::Reset(), Resurrect(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), CreatureAI::SetGazeOn(), spell_putricide_ooze_channel::StartAttack(), brann_bronzebeard::brann_bronzebeardAI::SummonCreatures(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::SummonsAction(), Unit::TauntApply(), Unit::TauntFadeOut(), Pet::Update(), SimpleCharmedAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::UpdateAI(), npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_freya_ward::npc_freya_wardAI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), CreatureAI::UpdateVictim(), CreatureAI::UpdateVictimWithGaze(), and npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached().
AttackStartCaster()
void UnitAI::AttackStartCaster (Unit * victim, float dist)
{
    if (victim && me->Attack(victim, false))
        me->GetMotionMaster()->MoveChase(victim, dist);
}
References Unit::Attack(), Unit::GetMotionMaster(), me, and MotionMaster::MoveChase().
Referenced by CasterAI::AttackStart(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::AttackStart(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::AttackStart(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::AttackStart(), boss_faction_championsAI::AttackStart(), boss_prince_keleseth_icc::boss_prince_kelesethAI::AttackStart(), npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI::AttackStart(), npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI::AttackStart(), npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI::AttackStart(), npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI::AttackStart(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::AttackStart(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::AttackStart(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::AttackStart(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::AttackStart(), boss_keleseth::AttackStart(), boss_high_nethermancer_zerevor::AttackStart(), and boss_leotheras_the_blind::AttackStart().
CanAIAttack()
virtual bool UnitAI::CanAIAttack (Unit const *) const inline virtual
Reimplemented in boss_majordomo::boss_majordomoAI, boss_ick::boss_ickAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, npc_gunship_mage::npc_gunship_mageAI, npc_gunship_rocketeer::npc_gunship_rocketeerAI, npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI, boss_talon_king_ikiss, boss_ambassador_hellmaw, boss_pathaleon_the_calculator, boss_hodir::boss_hodirAI, npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI, npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI, boss_razorgore::boss_razorgoreAI, boss_kalecgos, boss_sathrovarr, boss_hazzarah, boss_jindo, boss_renataki::boss_renatakiAI, boss_anubarak_trial::boss_anubarak_trialAI, npc_swarm_scarab::npc_swarm_scarabAI, npc_nerubian_burrower::npc_nerubian_burrowerAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_igb_ship_crew::npc_igb_ship_crewAI, npc_gunship_boarding_addAI, npc_gunship_gunner::npc_gunship_gunnerAI, boss_lord_marrowgar, boss_professor_putricide::boss_professor_putricideAI, boss_sindragosa::boss_sindragosaAI, boss_the_lich_king::boss_the_lich_kingAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, npc_shambling_horror_icc::npc_shambling_horror_iccAI, npc_raging_spirit::npc_raging_spiritAI, npc_terenas_menethil::npc_terenas_menethilAI, npc_icc_lk_checktarget::npc_icc_lk_checktargetAI, npc_lk_wicked_spirit::npc_lk_wicked_spiritAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, npc_risen_archmage::npc_risen_archmageAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, npc_argent_captainAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, npc_icc_severed_essence::npc_icc_severed_essenceAI, npc_icc_spire_frostwyrm, npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI, npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI, npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI, boss_thorim_arena_npcs::boss_thorim_arena_npcsAI, npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI, boss_illidan_stormrage, boss_nethermancer_sepethrea, npc_arcanite_dragonling, boss_chromaggus::boss_chromaggusAI, boss_ragnaros::boss_ragnarosAI, npc_thrall_bfu::npc_thrall_bfuAI, npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI, boss_ouro, boss_murmur, boss_alar, TurretAI, SmartAI, boss_selin_fireheart, boss_halion::boss_halionAI, boss_tyrannus::boss_tyrannusAI, npc_pos_freed_slave::npc_pos_freed_slaveAI, boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI, npc_mindless_ghoul::npc_mindless_ghoulAI, boss_gurtogg_bloodboil, npc_parasitic_shadowfiend, and npc_inner_demon.
{ return true; }
Referenced by npc_escortAI::AssistPlayerInCombatAgainst().
DamageDealt()
virtual void UnitAI::DamageDealt (Unit * , uint32 & , DamageEffectType) inline virtual
Called at any Damage to any victim (before damage apply)
Reimplemented in boss_kologarn_eyebeam::boss_kologarn_eyebeamAI, SmartAI, boss_mandokir::boss_mandokirAI, boss_janalai, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_valanar_icc::boss_prince_valanarAI, and npc_ball_of_flame::npc_ball_of_flameAI.
{ }
Referenced by Unit::DealDamage().
DamageTaken()
virtual void UnitAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented in boss_eviscerator::boss_evisceratorAI, ScriptedAI, boss_mor_grayhoof, boss_renataki::boss_renatakiAI, boss_isalien, boss_huhuran, boss_sartura, boss_garfrost::boss_garfrostAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_professor_putricide::boss_professor_putricideAI, boss_eregos::boss_eregosAI, boss_yoggsaron_influence_tentacle::boss_yoggsaron_influence_tentacleAI, npc_your_inner_turmoil::npc_your_inner_turmoilAI, boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI, boss_balinda, boss_lord_valthalak::boss_lord_valthalakAI, npc_blackhand_incarcerator::npc_blackhand_incarceratorAI, boss_quartermaster_zigris, boss_warmaster_voone::boss_warmastervooneAI, boss_razorgore::boss_razorgoreAI, boss_baron_geddon::boss_baron_geddonAI, boss_golemagg::boss_golemaggAI, npc_core_rager::npc_core_ragerAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, npc_mc_core_hound::npc_mc_core_houndAI, npc_chess_move_trigger, boss_attumen, boss_midnight, npc_netherspite_infernal, boss_julianne, boss_romulo, npc_mograine::npc_mograineAI, boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI, boss_kormok, boss_apothecary_hummel::boss_apothecary_hummelAI, boss_muru, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, npc_batrider, npc_dark_iron_guzzler, npc_coren_direbrew, boss_headless_horseman, boss_headless_horseman_head, npc_pilgrims_bounty_chair, npc_ancient_wisp, boss_onyxia, npc_anubisath_guardian, boss_eye_of_cthun, boss_ouro, npc_anubisath_sentinel::aqsentinelAI, npc_anubisath_defender, npc_amanitar_mushrooms, boss_elder_nadox, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_sartharion::boss_sartharionAI, boss_eadric::boss_eadricAI, boss_paletress::boss_paletressAI, npc_argent_soldier::npc_argent_soldierAI, boss_black_knight::boss_black_knightAI, boss_grand_champion::boss_grand_championAI, npc_announcer_toc5::npc_announcer_toc5AI, npc_frost_sphere::npc_frost_sphereAI, npc_anubarak_spike::npc_anubarak_spikeAI, boss_bronjahm::boss_bronjahmAI, boss_ick::boss_ickAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, boss_drakkari_colossus::boss_drakkari_colossusAI, npc_gunship::npc_gunshipAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_gunship_boarding_addAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_sindragosa::boss_sindragosaAI, npc_shambling_horror_icc::npc_shambling_horror_iccAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, npc_terenas_menethil::npc_terenas_menethilAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, boss_gothik::boss_gothikAI, npc_gothik_trigger::npc_gothik_triggerAI, npc_tesla::npc_teslaAI, boss_malygos::boss_malygosAI, npc_vortex_ride::npc_vortex_rideAI, npc_power_spark::npc_power_sparkAI, npc_crystalline_frayer, npc_spark_of_ionar::npc_spark_of_ionarAI, brann_bronzebeard::brann_bronzebeardAI, boss_algalon_the_observer::boss_algalon_the_observerAI, npc_collapsing_star::npc_collapsing_starAI, npc_pool_of_tar::npc_pool_of_tarAI, boss_freya::boss_freyaAI, boss_hodir::boss_hodirAI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, boss_razorscale::boss_razorscaleAI, npc_xt002_heart::npc_xt002_heartAI, npc_xt002_boombot::npc_xt002_boombotAI, boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, boss_ingvar_the_plunderer, npc_vrykul_skeleton, npc_tournament_training_dummy::npc_tournament_training_dummyAI, npc_still_at_it_trigger::npc_still_at_it_triggerAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, npc_akama_illidan, npc_maiev_illidan, boss_illidari_council, boss_illidari_council_memberAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, boss_essence_of_desire::boss_essence_of_desireAI, npc_akama_shade, boss_the_lurker_below, boss_vazruden, npc_shattered_hand_scout, npc_millhouse_manastorm::npc_millhouse_manastormAI, boss_alar, advisor_baseAI, npc_magister_aledis, boss_ysondre::boss_ysondreAI, boss_lethon::boss_lethonAI, boss_emeriss::boss_emerissAI, boss_taerar::boss_taerarAI, npc_training_dummy::npc_training_dummyAI, npc_hor_leader_second::npc_hor_leader_secondAI, npc_ice_tomb::npc_ice_tombAI, npc_blistering_zombie::npc_blistering_zombieAI, npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI, npc_molten_golem::npc_molten_golemAI, npc_dark_nucleus::npc_dark_nucleusAI, npc_centrifuge_construct::npc_centrifuge_constructAI, boss_nightbane, boss_thekal, BossAI, boss_felblood_kaelthas, boss_halazzi, boss_illidan_stormrage, boss_viscidus, npc_garr_firesworn::npc_garr_fireswornAI, npc_death_knight_initiate::npc_death_knight_initiateAI, boss_buru, boss_twinemperorsAI, npc_tiger_matriarch::npc_tiger_matriarchAI, boss_halion::boss_halionAI, boss_twilight_halion::boss_twilight_halionAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_the_lich_king::boss_the_lich_kingAI, npc_ulduar_iron_construct::npc_ulduar_iron_constructAI, npc_warden_mellichar::npc_warden_mellicharAI, npc_artorius::npc_artoriusAI, npc_franklin::npc_franklinAI, SmartAI, npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI, npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI, boss_shade_of_aran, boss_kiljaeden, boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI, boss_thorim_start_npcs::boss_thorim_start_npcsAI, npc_heated_battle::npc_heated_battleAI, npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI, boss_mal_ganis::boss_mal_ganisAI, boss_bug_trio, boss_hadronox::boss_hadronoxAI, boss_razuvious::boss_razuviousAI, boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI, boss_kologarn::boss_kologarnAI, boss_kologarn_arms::boss_kologarn_armsAI, boss_thorim::boss_thorimAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, boss_yoggsaron_brain::boss_yoggsaron_brainAI, and npc_wild_wyrm::npc_wild_wyrmAI.
{}
Referenced by Unit::DealDamage().
DoAction()
virtual void UnitAI::DoAction (int32) inline virtual
Reimplemented in npc_grand_magister_rommath::npc_grand_magister_rommathAI, boss_twin_valkyrAI, npc_fos_leader::npc_fos_leaderAI, boss_falric::boss_falricAI, boss_marwyn::boss_marwynAI, npc_ghostly_priest::npc_ghostly_priestAI, npc_phantom_mage::npc_phantom_mageAI, npc_shadowy_mercenary::npc_shadowy_mercenaryAI, npc_spectral_footman::npc_spectral_footmanAI, npc_tortured_rifleman::npc_tortured_riflemanAI, npc_hor_lich_king::npc_hor_lich_kingAI, boss_krick::boss_krickAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, npc_icc_ice_sphere::npc_icc_ice_sphereAI, npc_icc_severed_essence::npc_icc_severed_essenceAI, npc_ulduar_toasty_fire::npc_ulduar_toasty_fireAI, npc_vh_void_sentry::npc_vh_void_sentryAI, npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI, boss_victor_nefarius::boss_victor_nefariusAI, npc_drakonid_spawner, boss_razorgore::boss_razorgoreAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, boss_nightbane, boss_dorothee, boss_roar, boss_strawman, boss_tinhead, boss_julianne, boss_romulo, npc_dkc1_gothik::npc_dkc1_gothikAI, boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI, boss_apothecary_hummel::boss_apothecary_hummelAI, npc_apothecary_genericAI, boss_jarien, boss_sothos, npc_eris_hevenfire::npc_eris_hevenfireAI, npc_harrison_jones, npc_amanishi_lookout, npc_amanishi_tempest, boss_mandokir::boss_mandokirAI, npc_chained_spirit, boss_thekal, npc_coren_direbrew, npc_direbrew_antagonist, boss_anetheron, boss_archimonde, boss_azgalor, boss_kazrogal, boss_rage_winterchill, npc_hyjal_ground_trash, npc_hyjal_gargoyle, npc_hyjal_frost_wyrm, boss_ayamiss, boss_bug_trio, boss_eye_of_cthun, boss_twinemperorsAI, npc_thrall_warchief::npc_thrall_warchiefAI, boss_jedoga_shadowseeker, npc_twilight_volunteer, npc_taldaram_flamesphere, boss_taldaram, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, npc_xerestrasza::npc_xerestraszaAI, npc_halion_controller::npc_halion_controllerAI, npc_orb_carrier::npc_orb_carrierAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_valanar_icc::boss_prince_valanarAI, npc_ball_of_flame::npc_ball_of_flameAI, npc_kinetic_bomb::npc_kinetic_bombAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI, npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI, npc_saurfang_event::npc_saurfang_eventAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, npc_bone_spike::npc_bone_spikeAI, boss_professor_putricide::boss_professor_putricideAI, npc_big_ooze::npc_big_oozeAI, boss_sindragosa::boss_sindragosaAI, npc_spinestalker::npc_spinestalkerAI, npc_rimefang::npc_rimefangAI, boss_the_lich_king::boss_the_lich_kingAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, npc_strangulate_vehicle::npc_strangulate_vehicleAI, npc_terenas_menethil::npc_terenas_menethilAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, npc_the_lich_king_controller::npc_the_lich_king_controllerAI, npc_risen_archmage::npc_risen_archmageAI, npc_frost_freeze_trap::npc_frost_freeze_trapAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, boss_sister_svalna::boss_sister_svalnaAI, npc_argent_captainAI, npc_icc_spire_frostwyrm, npc_ioc_gunship_captain::npc_ioc_gunship_captainAI, boss_razuvious_minion::boss_razuvious_minionAI, brann_bronzebeard::brann_bronzebeardAI, boss_algalon_the_observer::boss_algalon_the_observerAI, npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI, npc_living_constellation::npc_living_constellationAI, boss_flame_leviathan::boss_flame_leviathanAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_flames_initial::npc_ulduar_flames_initialAI, boss_fathomlord_karathress, boss_fathomguard_tidalvess, boss_the_lurker_below, boss_ahune, npc_frozen_core, npc_ahune_bunny, boss_broggok, boss_magtheridon, boss_grand_warlock_nethekurse, npc_simon_bunny::npc_simon_bunnyAI, npc_shattrath_daily_quest, npc_artorius::npc_artoriusAI, npc_nelson::npc_nelsonAI, boss_midnight, boss_akilzon, boss_halazzi, boss_cthun, npc_muglash::npc_muglashAI, npc_hor_leader::npc_hor_leaderAI, npc_hor_leader_second::npc_hor_leader_secondAI, boss_leotheras_the_blind, boss_high_king_maulgar, boss_pathaleon_the_calculator, npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI, npc_pos_leader_second::npc_pos_leader_secondAI, boss_sartharion_dragonAI, TotemAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, npc_chesspiece, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, npc_madrigosa, boss_sacrolash, boss_alythess, boss_felmyst, boss_kalecgos, boss_sathrovarr, boss_kiljaeden, npc_kalecgos_kj, npc_costumed_orphan_matron, npc_hallows_end_soh, boss_headless_horseman, npc_pilgrims_bounty_chair, boss_infinite_corruptor::boss_infinite_corruptorAI, npc_arthas::npc_arthasAI, npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, npc_medivh_bm, boss_onyxia, boss_hadronox::boss_hadronoxAI, npc_anub_ar_crusher::npc_anub_ar_crusherAI, boss_sartharion::boss_sartharionAI, npc_twilight_summon::npc_twilight_summonAI, boss_paletress::boss_paletressAI, boss_black_knight::boss_black_knightAI, npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI, boss_grand_champion::boss_grand_championAI, boss_anubarak_trial::boss_anubarak_trialAI, npc_swarm_scarab::npc_swarm_scarabAI, npc_anubarak_spike::npc_anubarak_spikeAI, npc_snobold_vassal::npc_snobold_vassalAI, boss_gormok::boss_gormokAI, boss_jormungarAI, npc_concentrated_ball::npc_concentrated_ballAI, boss_tharon_ja::boss_tharon_jaAI, boss_tyrannus::boss_tyrannusAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_drakkari_elemental::boss_drakkari_elementalAI, npc_living_mojo::npc_living_mojoAI, npc_icc_blood_beast::npc_icc_blood_beastAI, npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI, npc_icc_putricades_trap::npc_icc_putricades_trapAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_thaddius_summon::boss_thaddius_summonAI, npc_power_spark::npc_power_sparkAI, npc_hover_disk::npc_hover_diskAI, npc_spark_of_ionar::npc_spark_of_ionarAI, boss_volkhan::boss_volkhanAI, npc_molten_golem::npc_molten_golemAI, boss_sjonnir::boss_sjonnirAI, boss_steelbreaker::boss_steelbreakerAI, boss_auriaya::boss_auriayaAI, npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI, npc_freya_ward::npc_freya_wardAI, npc_mimirons_inferno::npc_mimirons_infernoAI, boss_freya::boss_freyaAI, boss_freya_summons::boss_freya_summonsAI, boss_vezax::boss_vezaxAI, boss_kologarn::boss_kologarnAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI, boss_thorim::boss_thorimAI, boss_thorim_sif::boss_thorim_sifAI, boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI, boss_xt002::boss_xt002AI, npc_xt002_heart::npc_xt002_heartAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_yoggsaron::boss_yoggsaronAI, boss_yoggsaron_brain::boss_yoggsaron_brainAI, boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI, boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI, boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI, boss_yoggsaron_keeper, npc_ulduar_keeper::npc_ulduar_keeperAI, boss_skarvald_the_constructor, boss_dalronn_the_controller, boss_palehoof::boss_palehoofAI, npc_massive_jormungar::npc_massive_jormungarAI, npc_ferocious_rhino::npc_ferocious_rhinoAI, npc_ravenous_furbolg::npc_ravenous_furbolgAI, npc_frenzied_worgen::npc_frenzied_worgenAI, boss_skadi::boss_skadiAI, boss_skadi_grauf::boss_skadi_graufAI, boss_ichoron::boss_ichoronAI, npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI, boss_ambassador_hellmaw, boss_illidan_stormrage, npc_akama_illidan, npc_maiev_illidan, npc_blade_of_azzinoth, boss_illidari_council, boss_illidari_council_memberAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, boss_essence_of_desire::boss_essence_of_desireAI, boss_essence_of_anger::boss_essence_of_angerAI, npc_akama_shade, npc_creature_generator_akama, boss_kelidan_the_breaker, boss_nazan, npc_pet_gen_argent_pony_bridle, npc_elder_clearwater::npc_elder_clearwaterAI, SmartAI, npc_stolen_soul, boss_ghazan, npc_scarlet_miner_cart::npc_scarlet_miner_cartAI, npc_brew_bubble, npc_taretha::npc_tarethaAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI, and npc_spring_rabbit::npc_spring_rabbitAI.
{}
Referenced by boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations(), spell_the_lich_king_ice_burst_target_search::CheckTargetCount(), spell_algalon_big_bang::CheckTargets(), instance_karazhan::instance_karazhan_InstanceMapScript::DoAction(), SummonList::DoAction(), BattlegroundIC::HandleCapturedNodes(), spell_halion_twilight_division::HandleDummy(), spell_magtheridon_shadow_grasp_visual::HandleDummyApply(), spell_algalon_trigger_3_adds::HandleDummyEffect(), spell_tharon_ja_dummy_aura::HandleEffectRemove(), spell_kiljaeden_darkness_aura::HandleRemove(), spell_taldaram_summon_flame_ball::HandleScript(), spell_ayamiss_swarmer_swarm::HandleScript(), spell_xt002_gravity_bomb_damage::HandleScript(), spell_the_lich_king_quake::HandleSendEvent(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), npc_brew_bubble::MoveInLineOfSight(), spell_pilgrims_bounty_serve_generic::OnAuraRemove(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnCreatureCreate(), go_palehoof_sphere::OnGossipHello(), npc_pet_gen_argent_pony_bridle::OnGossipSelect(), boss_majordomo::OnGossipSelect(), npc_highlord_darion_mograine::OnGossipSelect(), npc_arthas::OnGossipSelect(), npc_high_overlord_saurfang_icc::OnGossipSelect(), npc_muradin_bronzebeard_icc::OnGossipSelect(), brann_bronzebeard::OnGossipSelect(), npc_ulduar_keeper::OnGossipSelect(), npc_fos_leader::OnGossipSelect(), npc_hor_leader::OnGossipSelect(), npc_thrall_old_hillsbrad::OnGossipSelect(), npc_hor_leader_second::OnGossipSelect(), npc_tirions_gambit_tirion::OnGossipSelect(), npc_artorius::OnGossipSelect(), npc_nelson::OnGossipSelect(), spell_xt002_gravity_bomb_aura::OnPeriodic(), instance_ulduar::instance_ulduar_InstanceMapScript::OnPlayerEnter(), boss_apothecary_hummel::OnQuestReward(), npc_thrall_warchief::OnQuestReward(), npc_elder_clearwater::OnQuestReward(), spell_electrial_storm::OnRemove(), FrostwingGauntletRespawner::operator()(), PretendToDie(), Resurrect(), boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI::SpellHit(), npc_pilgrims_bounty_chair::SpellHitTarget(), boss_zuramat::boss_zuramatAI::SummonedCreatureDespawn(), and boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI().
DoAddAuraToAllHostilePlayers()
SpellCastResult UnitAI::DoAddAuraToAllHostilePlayers (uint32 spellid)
{
    if (me->IsInCombat())
    {
        ThreatContainer::StorageType threatlist = me->GetThreatMgr().GetThreatList();
        for (ThreatContainer::StorageType::const_iterator itr = threatlist.begin(); itr != threatlist.end(); ++itr)
        {
            if (Unit* unit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid()))
            {
                if (unit->IsPlayer())
                {
                    me->AddAura(spellid, unit);
                    return SPELL_CAST_OK;
                }
            }
            else
                return SPELL_FAILED_BAD_TARGETS;
        }
    }
    return SPELL_FAILED_CUSTOM_ERROR;
}
References Unit::AddAura(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), ObjectAccessor::GetUnit(), Unit::IsInCombat(), me, SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, and SPELL_FAILED_CUSTOM_ERROR.
DoCast() [1/2]
SpellCastResult UnitAI::DoCast (uint32 spellId)
{
    Unit* target = nullptr;
    switch (AISpellInfo[spellId].target)
    {
        default:
        case AITARGET_SELF:
            target = me;
            break;
        case AITARGET_VICTIM:
            target = me->GetVictim();
            break;
        case AITARGET_ENEMY:
            {
                if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId))
                {
                    bool playerOnly = spellInfo->HasAttribute(SPELL_ATTR3_ONLY_ON_PLAYER);
                    target = SelectTarget(SelectTargetMethod::Random, 0, spellInfo->GetMaxRange(false), playerOnly);
                }
                break;
            }
        case AITARGET_ALLY:
            target = me;
            break;
        case AITARGET_BUFF:
            target = me;
            break;
        case AITARGET_DEBUFF:
            {
                if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId))
                {
                    bool playerOnly = spellInfo->HasAttribute(SPELL_ATTR3_ONLY_ON_PLAYER);
                    float range = spellInfo->GetMaxRange(false);
                    DefaultTargetSelector targetSelector(me, range, playerOnly, true, -(int32)spellId);
                    if (!(spellInfo->AuraInterruptFlags & AURA_INTERRUPT_FLAG_NOT_VICTIM)
                            && targetSelector(me->GetVictim()))
                        target = me->GetVictim();
                    else
                        target = SelectTarget(SelectTargetMethod::Random, 0, targetSelector);
                }
                break;
            }
    }
    if (target)
        me->CastSpell(target, spellId, false);
    return SPELL_FAILED_BAD_TARGETS;
}
References AISpellInfo, AITARGET_ALLY, AITARGET_BUFF, AITARGET_DEBUFF, AITARGET_ENEMY, AITARGET_SELF, AITARGET_VICTIM, AURA_INTERRUPT_FLAG_NOT_VICTIM, Unit::CastSpell(), Unit::GetVictim(), me, SelectTarget(), SPELL_ATTR3_ONLY_ON_PLAYER, SPELL_FAILED_BAD_TARGETS, and sSpellMgr.
Referenced by boss_marli::_chargePlayer(), boss_marli::_schedulePhaseTroll(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::AttackStart(), boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent(), boss_ouro::CastGroundRupture(), boss_moira_bronzebeardAI::CastOnEmperorIfPossible(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), boss_thekal::CheckPhaseTransition(), boss_eviscerator::boss_evisceratorAI::DamageTaken(), boss_renataki::boss_renatakiAI::DamageTaken(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::DamageTaken(), boss_lord_valthalak::boss_lord_valthalakAI::DamageTaken(), boss_julianne::DamageTaken(), boss_kormok::DamageTaken(), boss_ysondre::boss_ysondreAI::DamageTaken(), boss_lethon::boss_lethonAI::DamageTaken(), boss_emeriss::boss_emerissAI::DamageTaken(), boss_taerar::boss_taerarAI::DamageTaken(), boss_archimonde::DoAction(), boss_professor_putricide::boss_professor_putricideAI::DoAction(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::DoAction(), npc_simon_bunny::npc_simon_bunnyAI::DoAction(), boss_alythess::DoAction(), npc_blade_of_azzinoth::DoAction(), DoCastMaxThreat(), DoCastRandomTarget(), DoCastSelf(), DoCastVictim(), npc_ranshalla::npc_ranshallaAI::DoChannelTorchSpell(), boss_alar::DoDiveBomb(), boss_skeram::DoTeleport(), boss_halazzi::EnterPhase(), boss_baron_geddon::boss_baron_geddonAI::ExecuteEvent(), boss_gehennas::boss_gehennasAI::ExecuteEvent(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_sulfuron::boss_sulfuronAI::ExecuteEvent(), boss_amanitar::ExecuteEvent(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_ahune::ExecuteEvent(), emerald_dragonAI::ExecuteEvent(), boss_taerar::boss_taerarAI::ExecuteEvent(), npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::FinishQuest(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), npc_simon_bunny::npc_simon_bunnyAI::GiveRewardForLevel(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), npc_echo_of_medivh::HandleCheat(), boss_grand_warlock_nethekurse::IntroRP(), boss_attumen::IsSummonedBy(), npc_tiger_matriarch::npc_tiger_matriarchAI::IsSummonedBy(), npc_invisible_tractor_beam_source::IsSummonedBy(), npc_kilrek::JustDied(), npc_anubisath_sentinel::aqsentinelAI::JustDied(), npc_omen::npc_omenAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), CasterAI::JustEngagedWith(), boss_terestian_illhoof::JustEngagedWith(), boss_bigbadwolf::JustEngagedWith(), boss_priestess_delrissa::JustEngagedWith(), boss_kormok::JustEngagedWith(), boss_akilzon::JustEngagedWith(), npc_healing_ward::JustEngagedWith(), npc_zealot_lorkhan::JustEngagedWith(), npc_coren_direbrew_sisters::JustEngagedWith(), npc_hyjal_jaina::hyjalJainaAI::JustEngagedWith(), npc_hyjal_thrall::hyjalThrallAI::JustEngagedWith(), npc_hyjal_ground_trash::JustEngagedWith(), boss_lieutenant_drake::JustEngagedWith(), npc_obsidian_destroyer::JustEngagedWith(), npc_eye_tentacle::JustEngagedWith(), npc_anubisath_defender::JustEngagedWith(), npc_obsidian_eradicator::JustEngagedWith(), npc_obsidian_nullifier::JustEngagedWith(), npc_centrifuge_construct::npc_centrifuge_constructAI::JustEngagedWith(), boss_keleseth::JustEngagedWith(), boss_exarch_maladaar::JustEngagedWith(), boss_anzu::JustEngagedWith(), boss_talon_king_ikiss::JustEngagedWith(), npc_flame_of_azzinoth::JustEngagedWith(), boss_doomlord_kazzak::boss_doomlordkazzakAI::JustEngagedWith(), boss_swamplord_muselek::JustEngagedWith(), npc_underbat::JustEngagedWith(), boss_gruul::JustEngagedWith(), boss_kiggler_the_crazed::JustEngagedWith(), boss_blindeye_the_seer::JustEngagedWith(), boss_harbinger_skyriss::JustEngagedWith(), boss_pathaleon_the_calculator::JustEngagedWith(), npc_maghar_captive::npc_maghar_captiveAI::JustEngagedWith(), npc_kurenai_captive::npc_kurenai_captiveAI::JustEngagedWith(), boss_curator::JustEngagedWith(), boss_apoko::JustEngagedWith(), boss_zelfan::JustEngagedWith(), boss_selin_fireheart::JustEngagedWith(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::JustEngagedWith(), boss_brutallus::JustEngagedWith(), boss_sacrolash::JustEngagedWith(), boss_alythess::JustEngagedWith(), boss_alyson_antille::JustEngagedWith(), boss_janalai::JustEngagedWith(), npc_hivezara_stinger::JustEngagedWith(), boss_vem::JustEngagedWith(), boss_yauj::JustEngagedWith(), boss_fankriss::JustEngagedWith(), boss_twinemperorsAI::JustEngagedWith(), npc_vekniss_stinger::JustEngagedWith(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustEngagedWith(), boss_commander_stoutbeard::JustEngagedWith(), boss_erekem::boss_erekemAI::JustEngagedWith(), boss_gurtogg_bloodboil::JustEngagedWith(), boss_najentus::JustEngagedWith(), boss_fathomguard_caribdis::JustEngagedWith(), boss_high_astromancer_solarian::JustEngagedWith(), boss_anetheron::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_illidan_stormrage::JustSummoned(), npc_blade_of_azzinoth::JustSummoned(), boss_felblood_kaelthas::LapseAction(), npc_drakuru_shackles::npc_drakuru_shacklesAI::LockRageclaw(), npc_earthen_ring_flamecaller::LookOpening(), npc_depth_charge::npc_depth_chargeAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), npc_daranelle::npc_daranelleAI::MoveInLineOfSight(), npc_hive_zara_larva::MovementInform(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::MovementInform(), boss_lady_vashj::MovementInform(), npc_fel_guard_hound::npc_fel_guard_houndAI::MovementInform(), boss_shade_of_akama::MovementInform(), npc_chained_spirit::MovementInform(), npc_akilzon_eagle::MovementInform(), npc_ancestral_wolf::npc_ancestral_wolfAI::npc_ancestral_wolfAI(), npc_hyjal_tyrande::OnGossipSelect(), boss_mandokir::boss_mandokirAI::OnTeleportUnreacheablePlayer(), npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::PassengerBoarded(), boss_jeklik::PathEndReached(), npc_simon_bunny::npc_simon_bunnyAI::PlayColor(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), npc_plucky::npc_pluckyAI::ReceiveEmote(), npc_zulian_prowler::npc_zulian_prowlerAI::Reset(), npc_belnistrasz::npc_belnistraszAI::Reset(), npc_giant_eye_tentacle::Reset(), npc_draenei_survivor::npc_draenei_survivorAI::Reset(), npc_troll_volunteer::npc_troll_volunteerAI::Reset(), npc_plucky::npc_pluckyAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), npc_violet_hold_defense_system::Reset(), npc_hidden_cultist::npc_hidden_cultistAI::Reset(), npc_cosmetic_toy_plane::Reset(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::Reset(), npc_blessed_banner::npc_blessed_bannerAI::Reset(), npc_captured_rageclaw::npc_captured_rageclawAI::Reset(), emerald_dragonAI::Reset(), npc_dancing_flames::npc_dancing_flamesAI::Reset(), boss_illidan_stormrage::ScheduleAbilities(), boss_julianne::ScheduleCombat(), boss_nightbane::ScheduleFly(), boss_nightbane::ScheduleGround(), boss_supremus::SchedulePhase(), boss_baroness_anastari::boss_baroness_anastariAI::SchedulePossession(), boss_commander_sarannis::ScheduleReinforcements(), boss_attumen::ScheduleTasks(), boss_ayamiss::ScheduleTasks(), boss_cthun::ScheduleTasks(), boss_mandokir::boss_mandokirAI::SetGUID(), boss_murmur::SetGUID(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::SetGUID(), npc_kerlonian::npc_kerlonianAI::SetSleeping(), npc_lake_frog::npc_lake_frogAI::sGossipSelect(), boss_strawman::SpellHit(), npc_argent_captainAI::SpellHit(), npc_gothik_trigger::npc_gothik_triggerAI::SpellHit(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::SpellHit(), npc_captured_rageclaw::npc_captured_rageclawAI::SpellHit(), npc_zuljin_vortex::SpellHit(), npc_forest_frog::SpellHit(), npc_draenei_survivor::npc_draenei_survivorAI::SpellHit(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), npc_wounded_skirmisher::SpellHit(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::SpellHit(), npc_greengill_slave::npc_greengill_slaveAI::SpellHit(), npc_chesspiece::SpellHitTarget(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SpellHitTarget(), boss_hydross_the_unstable::SummonMovementInform(), npc_drakuru_shackles::npc_drakuru_shacklesAI::UnlockRageclaw(), CombatAI::UpdateAI(), CasterAI::UpdateAI(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), ironhand_guardian::ironhand_guardianAI::UpdateAI(), boss_anubshiah::boss_anubshiahAI::UpdateAI(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::UpdateAI(), boss_hedrum::boss_hedrumAI::UpdateAI(), boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI::UpdateAI(), boss_okthor::boss_okthorAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), boss_gyth::boss_gythAI::UpdateAI(), boss_halycon::boss_halyconAI::UpdateAI(), boss_lord_valthalak::boss_lord_valthalakAI::UpdateAI(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_flamegor::boss_flamegorAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_nefarian::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), npc_flamewaker_priest::npc_flamewaker_priestAI::UpdateAI(), npc_chesspiece::UpdateAI(), npc_cyclone::UpdateAI(), npc_scarlet_miner::npc_scarlet_minerAI::UpdateAI(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), npc_snowfall_glade_playmate::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_onyxia::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_skeram::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), npc_aquementas::npc_aquementasAI::UpdateAI(), npc_cairne_bloodhoof::npc_cairne_bloodhoofAI::UpdateAI(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), boss_elder_nadox::UpdateAI(), boss_volazj::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), boss_taldaram::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), npc_captain_rupert::npc_captain_rupertAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), npc_vrykul_skeleton::UpdateAI(), npc_enslaved_proto_drake::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_binder::npc_azure_binderAI::UpdateAI(), npc_azure_mage_slayer::npc_azure_mage_slayerAI::UpdateAI(), npc_azure_raider::npc_azure_raiderAI::UpdateAI(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), npc_azure_spellbreaker::npc_azure_spellbreakerAI::UpdateAI(), npc_azure_captain::npc_azure_captainAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::UpdateAI(), npc_minigob_manabonk::UpdateAI(), npc_dalaran_mage::npc_dalaran_mageAI::UpdateAI(), npc_dalaran_warrior::npc_dalaran_warriorAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), npc_frozen_core::UpdateAI(), npc_ahune_bunny::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), npc_simon_bunny::npc_simon_bunnyAI::UpdateAI(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::UpdateAI(), npc_magister_aledis::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), npc_warmage_coldarra::npc_warmage_coldarraAI::UpdateAI(), npc_zulaman_hostage::npc_zulaman_hostageAI::UpdateAI(), npc_warmage_violetstand::UpdateAI(), npc_wg_spirit_guide::npc_wg_spirit_guideAI::UpdateAI(), npc_apothecary_hanes::npc_Apothecary_HanesAI::UpdateEscortAI(), npc_kurenai_captive::npc_kurenai_captiveAI::UpdateEscortAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::WaypointReached(), npc_custodian_of_time::npc_custodian_of_timeAI::WaypointReached(), and npc_isla_starmane::npc_isla_starmaneAI::WaypointReached().
DoCast() [2/2]
SpellCastResult UnitAI::DoCast (Unit * victim, uint32 spellId, bool triggered = false)
{
    if (!victim)
        return SPELL_FAILED_BAD_TARGETS;
    if (me->HasUnitState(UNIT_STATE_CASTING) && !triggered)
        return SPELL_FAILED_SPELL_IN_PROGRESS;
    return me->CastSpell(victim, spellId, triggered);
}
References Unit::CastSpell(), Unit::HasUnitState(), me, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_SPELL_IN_PROGRESS, and UNIT_STATE_CASTING.
DoCastAOE()
SpellCastResult UnitAI::DoCastAOE (uint32 spellId, bool triggered = false)
{
    if (!triggered && me->HasUnitState(UNIT_STATE_CASTING))
        return SPELL_FAILED_SPELL_IN_PROGRESS;
    return me->CastSpell((Unit*)nullptr, spellId, triggered);
}
References Unit::CastSpell(), Unit::HasUnitState(), me, SPELL_FAILED_SPELL_IN_PROGRESS, and UNIT_STATE_CASTING.
Referenced by boss_marli::_schedulePhaseSpider(), boss_mor_grayhoof::CastRandomSpell(), boss_razorgore::boss_razorgoreAI::DamageTaken(), boss_golemagg::boss_golemaggAI::DamageTaken(), boss_midnight::DamageTaken(), boss_muru::DamageTaken(), advisor_baseAI::DamageTaken(), npc_garr_firesworn::npc_garr_fireswornAI::DamageTaken(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), npc_thrall_warchief::npc_thrall_warchiefAI::DoAction(), boss_sindragosa::boss_sindragosaAI::DoAction(), boss_icehowl::boss_icehowlAI::DoTrampleIfValid(), npc_giant_claw_tentacle::Emerge(), boss_ouro::Emerge(), boss_baron_geddon::boss_baron_geddonAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_amanitar::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), spell_ayamiss_swarmer_start_loop::HandleScript(), npc_shade_of_jindo::IsSummonedBy(), npc_kiljaeden_controller::JustDied(), boss_moam::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_professor_putricide::boss_professor_putricideAI::JustDied(), boss_sindragosa::boss_sindragosaAI::JustDied(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::JustDied(), advisor_baseAI::JustDied(), boss_brutallus::JustDied(), boss_balinda::JustEngagedWith(), boss_majordomo::boss_majordomoAI::JustEngagedWith(), boss_malchezaar::JustEngagedWith(), boss_terestian_illhoof::JustEngagedWith(), boss_bigbadwolf::JustEngagedWith(), boss_sothos::JustEngagedWith(), boss_zuljin::JustEngagedWith(), npc_vilebranch_speaker::JustEngagedWith(), boss_azuregos::boss_azuregosAI::JustEngagedWith(), boss_aeonus::JustEngagedWith(), boss_chrono_lord_deja::JustEngagedWith(), boss_temporus::JustEngagedWith(), boss_isalien::JustEngagedWith(), npc_anubisath_guardian::JustEngagedWith(), npc_obsidian_destroyer::JustEngagedWith(), npc_anubisath_defender::JustEngagedWith(), npc_obsidian_eradicator::JustEngagedWith(), npc_anubisath_warder::JustEngagedWith(), npc_obsidian_nullifier::JustEngagedWith(), npc_yor::JustEngagedWith(), boss_talon_king_ikiss::JustEngagedWith(), boss_ambassador_hellmaw::JustEngagedWith(), boss_blackheart_the_inciter::JustEngagedWith(), boss_grandmaster_vorpil::JustEngagedWith(), boss_doomwalker::JustEngagedWith(), boss_quagmirran::JustEngagedWith(), boss_mekgineer_steamrigger::JustEngagedWith(), boss_hungarfen::JustEngagedWith(), boss_kiggler_the_crazed::JustEngagedWith(), boss_krosh_firehand::JustEngagedWith(), boss_kelidan_the_breaker::JustEngagedWith(), boss_dalliah_the_doomsayer::JustEngagedWith(), boss_zereketh_the_unbound::JustEngagedWith(), boss_high_botanist_freywinn::JustEngagedWith(), boss_thorngrin_the_tender::JustEngagedWith(), boss_warp_splinter::JustEngagedWith(), boss_mechano_lord_capacitus::JustEngagedWith(), boss_pathaleon_the_calculator::JustEngagedWith(), boss_vaelastrasz::boss_vaelAI::JustEngagedWith(), boss_maiden_of_virtue::JustEngagedWith(), boss_netherspite::JustEngagedWith(), boss_ellris_duskhallow::JustEngagedWith(), boss_yazzai::JustEngagedWith(), boss_warlord_salaris::JustEngagedWith(), boss_garaxxas::JustEngagedWith(), boss_apoko::JustEngagedWith(), boss_zelfan::JustEngagedWith(), boss_selin_fireheart::JustEngagedWith(), boss_kalecgos::JustEngagedWith(), boss_marli::JustEngagedWith(), boss_azgalor::JustEngagedWith(), boss_kazrogal::JustEngagedWith(), boss_yauj::JustEngagedWith(), boss_veknilash::JustEngagedWith(), boss_commander_stoutbeard::JustEngagedWith(), boss_murmur::JustEngagedWith(), boss_high_nethermancer_zerevor::JustEngagedWith(), boss_mother_shahraz::JustEngagedWith(), boss_warchief_kargath_bladefist::JustEngagedWith(), boss_aeonus::JustReachedHome(), boss_aeonus::MoveInLineOfSight(), boss_chrono_lord_deja::MoveInLineOfSight(), boss_kaelthas::MoveInLineOfSight(), boss_nefarian::MovementInform(), boss_zuljin::MovementInform(), npc_shattered_hand_scout::MovementInform(), boss_majordomo::boss_majordomoAI::MovementInform(), boss_warchief_kargath_bladefist::MovementInform(), boss_shade_of_aran::OnPowerUpdate(), boss_gyth::boss_gythAI::Reset(), boss_shade_of_aran::Reset(), boss_kalec::Reset(), npc_kiljaeden_controller::Reset(), boss_kiljaeden::Reset(), boss_janalai::Reset(), npc_shade_of_jindo::Reset(), boss_archimonde::Reset(), npc_eye_tentacle::Reset(), npc_claw_tentacle::Reset(), npc_giant_claw_tentacle::Reset(), npc_giant_eye_tentacle::Reset(), boss_talon_king_ikiss::Reset(), boss_hungarfen::Reset(), boss_magtheridon::Reset(), npc_amanishi_tempest::ScheduleEvents(), boss_nightbane::ScheduleFly(), boss_nightbane::ScheduleGround(), boss_ayamiss::ScheduleTasks(), boss_laj::ScheduleTasks(), npc_gothik_trigger::npc_gothik_triggerAI::SpellHit(), boss_urom::boss_uromAI::SpellHit(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::SpellHit(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), boss_hydross_the_unstable::SummonTaintedElementalOOC(), boss_fankriss::SummonWorms(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_nefarian::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_garr::boss_garrAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_chesspiece::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), boss_onyxia::UpdateAI(), npc_onyxian_lair_guard::UpdateAI(), boss_buru::UpdateAI(), boss_moam::UpdateAI(), boss_ossirian::UpdateAI(), boss_huhuran::UpdateAI(), boss_skeram::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), npc_azure_captain::npc_azure_captainAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), npc_violet_hold_defense_system::UpdateAI(), npc_magister_aledis::UpdateAI(), and npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI().
DoCastMaxThreat()
SpellCastResult UnitAI::DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition = 0, float dist = 0.0f, bool playerOnly = true, bool triggered = false)
Cast spell on the top threat target, which may not be the current victim.
Cast spell on the max threat target, which may not always be the current victim.
Parameters
uint32 spellId Spell ID to cast.
uint32 Threat table position.
float dist Distance from caster to target.
bool playerOnly Select players only, excludes pets and other npcs.
bool triggered Triggered cast (full triggered mask).
Returns
SpellCastResult
{
    if (Unit* target = SelectTarget(SelectTargetMethod::MaxThreat, threatTablePosition, dist, playerOnly))
    {
        return DoCast(target, spellId, triggered);
    }
    return SPELL_FAILED_BAD_TARGETS;
}
References DoCast(), SelectTarget(), and SPELL_FAILED_BAD_TARGETS.
Referenced by boss_moroes::JustEngagedWith().
DoCastRandomTarget()
SpellCastResult UnitAI::DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition = 0, float dist = 0.0f, bool playerOnly = true, bool triggered = false, bool withTank = true)
Cast the spell on a random unit from the threat list.
{
    if (Unit* target = SelectTarget(SelectTargetMethod::Random, threatTablePosition, dist, playerOnly, withTank))
    {
        return DoCast(target, spellId, triggered);
    }
    return SPELL_FAILED_BAD_TARGETS;
}
References DoCast(), SelectTarget(), and SPELL_FAILED_BAD_TARGETS.
Referenced by boss_marli::_schedulePhaseSpider(), boss_marli::_schedulePhaseTroll(), boss_broggok::DoAction(), boss_warmaster_voone::boss_warmastervooneAI::ExecuteEvent(), boss_sulfuron::boss_sulfuronAI::ExecuteEvent(), boss_servant_quarters::JustEngagedWith(), boss_dorothee::JustEngagedWith(), boss_strawman::JustEngagedWith(), boss_priestess_delrissa::JustEngagedWith(), boss_vexallus::JustEngagedWith(), boss_jarien::JustEngagedWith(), boss_sothos::JustEngagedWith(), boss_entropius::JustEngagedWith(), boss_twilight_corrupter::JustEngagedWith(), boss_akilzon::JustEngagedWith(), boss_zuljin::JustEngagedWith(), boss_venoxis::JustEngagedWith(), boss_azuregos::boss_azuregosAI::JustEngagedWith(), boss_archimonde::JustEngagedWith(), boss_isalien::JustEngagedWith(), npc_anubisath_guardian::JustEngagedWith(), npc_icc_spire_frostwyrm::JustEngagedWith(), boss_exarch_maladaar::JustEngagedWith(), boss_tavarok::JustEngagedWith(), boss_darkweaver_syth::JustEngagedWith(), boss_blackheart_the_inciter::JustEngagedWith(), boss_grandmaster_vorpil::JustEngagedWith(), boss_doomwalker::JustEngagedWith(), boss_quagmirran::JustEngagedWith(), boss_rokmar_the_crackler::JustEngagedWith(), boss_hydromancer_thespia::JustEngagedWith(), boss_mekgineer_steamrigger::JustEngagedWith(), boss_warlord_kalithresh::JustEngagedWith(), boss_ghazan::JustEngagedWith(), boss_the_black_stalker::JustEngagedWith(), boss_gruul::JustEngagedWith(), boss_olm_the_summoner::JustEngagedWith(), boss_the_maker::JustEngagedWith(), boss_omor_the_unscarred::JustEngagedWith(), boss_nazan::JustEngagedWith(), boss_harbinger_skyriss::JustEngagedWith(), boss_zereketh_the_unbound::JustEngagedWith(), boss_thorngrin_the_tender::JustEngagedWith(), boss_gatewatcher_gyrokill::JustEngagedWith(), boss_pathaleon_the_calculator::JustEngagedWith(), boss_maiden_of_virtue::JustEngagedWith(), boss_felblood_kaelthas::JustEngagedWith(), boss_ellris_duskhallow::JustEngagedWith(), boss_yazzai::JustEngagedWith(), boss_apoko::JustEngagedWith(), boss_zelfan::JustEngagedWith(), boss_selin_fireheart::JustEngagedWith(), boss_nalorakk::JustEngagedWith(), npc_batrider::JustEngagedWith(), boss_anetheron::JustEngagedWith(), boss_azgalor::JustEngagedWith(), boss_kazrogal::JustEngagedWith(), boss_rage_winterchill::JustEngagedWith(), boss_veknilash::JustEngagedWith(), boss_anubrekhan::boss_anubrekhanAI::JustEngagedWith(), boss_pandemonius::JustEngagedWith(), boss_murmur::JustEngagedWith(), boss_high_nethermancer_zerevor::JustEngagedWith(), boss_fathomguard_sharkkis::JustEngagedWith(), boss_fathomguard_caribdis::JustEngagedWith(), boss_grand_warlock_nethekurse::JustEngagedWith(), boss_high_astromancer_solarian::JustEngagedWith(), boss_void_reaver::JustEngagedWith(), boss_nazan::MovementInform(), boss_felmyst::MovementInform(), boss_kaelthas::MovementInform(), boss_jeklik::PathEndReached(), boss_malchezaar::Reset(), boss_high_king_maulgar::Reset(), boss_alar::ScheduleAbilities(), boss_illidan_stormrage::ScheduleAbilities(), boss_julianne::ScheduleCombat(), boss_romulo::ScheduleCombat(), npc_capernian::ScheduleEvents(), npc_telonicus::ScheduleEvents(), boss_nightbane::ScheduleGround(), boss_supremus::SchedulePhase(), boss_the_lurker_below::SchedulerPhaseOne(), boss_lady_vashj::ScheduleSpells(), boss_hydross_the_unstable::SetForm(), boss_nalorakk::ShapeShift(), boss_netherspite::SwitchToBanishPhase(), boss_netherspite::SwitchToPortalPhase(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_golemagg::boss_golemaggAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), boss_jindo::UpdateAI(), boss_huhuran::UpdateAI(), and boss_viscidus::UpdateAI().
DoCastSelf()
SpellCastResult UnitAI::DoCastSelf (uint32 spellId, bool triggered = false) inline
{ return DoCast(me, spellId, triggered); }
References DoCast(), and me.
Referenced by boss_marli::_schedulePhaseSpider(), boss_marli::_schedulePhaseTroll(), boss_hakkar::boss_hakkarAI::ApplyHakkarPowerStacks(), boss_high_nethermancer_zerevor::CastDampenMagicIfPossible(), boss_moira_bronzebeardAI::CastOnEmperorIfPossible(), boss_mor_grayhoof::CastRandomSpell(), boss_thekal::CheckPhaseTransition(), boss_mor_grayhoof::DamageTaken(), boss_huhuran::DamageTaken(), boss_sartura::DamageTaken(), boss_quartermaster_zigris::DamageTaken(), boss_golemagg::boss_golemaggAI::DamageTaken(), npc_core_rager::npc_core_ragerAI::DamageTaken(), npc_mc_core_hound::npc_mc_core_houndAI::DamageTaken(), boss_apothecary_hummel::boss_apothecary_hummelAI::DamageTaken(), boss_muru::DamageTaken(), npc_batrider::DamageTaken(), npc_anubisath_guardian::DamageTaken(), boss_ouro::DamageTaken(), npc_anubisath_sentinel::aqsentinelAI::DamageTaken(), npc_anubisath_defender::DamageTaken(), npc_amanitar_mushrooms::DamageTaken(), boss_volazj::DamageTaken(), boss_sartharion::boss_sartharionAI::DamageTaken(), boss_freya::boss_freyaAI::DamageTaken(), boss_hodir::boss_hodirAI::DamageTaken(), boss_vazruden::DamageTaken(), npc_millhouse_manastorm::npc_millhouse_manastormAI::DamageTaken(), boss_alar::DamageTaken(), advisor_baseAI::DamageTaken(), boss_viscidus::DamageTaken(), npc_garr_firesworn::npc_garr_fireswornAI::DamageTaken(), boss_buru::DamageTaken(), boss_shade_of_aran::DamageTaken(), boss_leotheras_the_blind::DemonTime(), boss_victor_nefarius::boss_victor_nefariusAI::DoAction(), boss_jarien::DoAction(), boss_sothos::DoAction(), boss_bug_trio::DoAction(), boss_twinemperorsAI::DoAction(), npc_twilight_volunteer::DoAction(), boss_taldaram::DoAction(), npc_frozen_core::DoAction(), npc_ahune_bunny::DoAction(), boss_broggok::DoAction(), boss_cthun::DoAction(), boss_leotheras_the_blind::DoAction(), boss_pathaleon_the_calculator::DoAction(), boss_kalecgos::DoAction(), boss_sathrovarr::DoAction(), boss_sartharion::boss_sartharionAI::DoAction(), npc_ulduar_keeper::npc_ulduar_keeperAI::DoAction(), boss_illidan_stormrage::DoAction(), npc_akama_illidan::DoAction(), npc_maiev_illidan::DoAction(), boss_illidari_council::DoAction(), boss_illidari_council_memberAI::DoAction(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::DoAction(), npc_creature_generator_akama::DoAction(), boss_razorgore::boss_razorgoreAI::DoChangePhase(), boss_alar::DoDiveBomb(), boss_bug_trio::DoFinalSpell(), boss_leotheras_the_blind::ElfTime(), npc_giant_claw_tentacle::Emerge(), boss_ouro::Emerge(), boss_ahune::Emerge(), boss_buru::EnterEvadeMode(), boss_nethermancer_sepethrea::EnterEvadeMode(), boss_ouro::EnterEvadeMode(), boss_halazzi::EnterPhase(), boss_warmaster_voone::boss_warmastervooneAI::ExecuteEvent(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_sulfuron::boss_sulfuronAI::ExecuteEvent(), boss_amanitar::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_ahune::ExecuteEvent(), boss_kaelthas::ExecuteMiddleEvent(), boss_janalai::FireWall(), boss_felblood_kaelthas::GravityLapseSequence(), boss_janalai::HatchAllEggs(), npc_midsummer_bonfire::Ignite(), npc_frozen_core::Initialize(), npc_eye_of_acherus::InitializeAI(), boss_kiljaeden::InitializeAI(), npc_toxic_slime::InitializeAI(), boss_taldaram::InitializeAI(), boss_ambassador_hellmaw::InitializeAI(), npc_rancid_mushroom::InitializeAI(), npc_ahune_ice_spear_bunny::InitializeAI(), npc_underbog_mushroom::InitializeAI(), boss_kormok::IsSummonedBy(), npc_shade_of_jindo::IsSummonedBy(), npc_hyjal_jaina::hyjalJainaAI::IsSummonedBy(), npc_taldaram_flamesphere::IsSummonedBy(), npc_blade_of_azzinoth::IsSummonedBy(), npc_supremus_punch_invisible_stalker::IsSummonedBy(), npc_raging_flames::IsSummonedBy(), npc_drakonid_spawner::IsSummonedBy(), boss_attumen::IsSummonedBy(), npc_demon_chain::IsSummonedBy(), npc_anubisath_guardian::JustDied(), npc_obsidian_destroyer::JustDied(), npc_anubisath_sentinel::aqsentinelAI::JustDied(), npc_anubisath_defender::JustDied(), boss_volazj::JustDied(), npc_taldaram_flamesphere::JustDied(), npc_frozen_core::JustDied(), boss_nethermancer_sepethrea::JustDied(), npc_buru_egg::JustDied(), boss_teron_gorefiend::JustDied(), boss_garr::boss_garrAI::JustEngagedWith(), boss_majordomo::boss_majordomoAI::JustEngagedWith(), boss_servant_quarters::JustEngagedWith(), boss_terestian_illhoof::JustEngagedWith(), boss_dorothee::JustEngagedWith(), boss_roar::JustEngagedWith(), boss_tinhead::JustEngagedWith(), boss_priestess_delrissa::JustEngagedWith(), boss_sothos::JustEngagedWith(), boss_kalec::JustEngagedWith(), boss_akilzon::JustEngagedWith(), boss_zuljin::JustEngagedWith(), boss_renataki::boss_renatakiAI::JustEngagedWith(), boss_thekal::JustEngagedWith(), npc_zealot_lorkhan::JustEngagedWith(), npc_zealot_zath::JustEngagedWith(), boss_venoxis::JustEngagedWith(), npc_coren_direbrew_sisters::JustEngagedWith(), boss_azuregos::boss_azuregosAI::JustEngagedWith(), npc_hyjal_jaina::hyjalJainaAI::JustEngagedWith(), npc_hyjal_thrall::hyjalThrallAI::JustEngagedWith(), npc_hyjal_tyrande::hyjalTyrandeAI::JustEngagedWith(), npc_hyjal_ground_trash::JustEngagedWith(), boss_epoch_hunter::JustEngagedWith(), boss_lieutenant_drake::JustEngagedWith(), boss_aeonus::JustEngagedWith(), boss_temporus::JustEngagedWith(), npc_anubisath_guardian::JustEngagedWith(), npc_dirt_mound::JustEngagedWith(), npc_anubisath_defender::JustEngagedWith(), boss_volazj::JustEngagedWith(), boss_exarch_maladaar::JustEngagedWith(), boss_nexusprince_shaffar::JustEngagedWith(), boss_tavarok::JustEngagedWith(), boss_anzu::JustEngagedWith(), boss_ambassador_hellmaw::JustEngagedWith(), boss_blackheart_the_inciter::JustEngagedWith(), boss_grandmaster_vorpil::JustEngagedWith(), npc_akama_illidan::JustEngagedWith(), boss_essence_of_suffering::boss_essence_of_sufferingAI::JustEngagedWith(), boss_essence_of_desire::boss_essence_of_desireAI::JustEngagedWith(), boss_essence_of_anger::boss_essence_of_angerAI::JustEngagedWith(), boss_doomlord_kazzak::boss_doomlordkazzakAI::JustEngagedWith(), boss_doomwalker::JustEngagedWith(), boss_mennu_the_betrayer::JustEngagedWith(), boss_rokmar_the_crackler::JustEngagedWith(), boss_mekgineer_steamrigger::JustEngagedWith(), boss_warlord_kalithresh::JustEngagedWith(), boss_the_black_stalker::JustEngagedWith(), boss_gruul::JustEngagedWith(), boss_high_king_maulgar::JustEngagedWith(), boss_olm_the_summoner::JustEngagedWith(), boss_blindeye_the_seer::JustEngagedWith(), boss_krosh_firehand::JustEngagedWith(), boss_kelidan_the_breaker::JustEngagedWith(), boss_omor_the_unscarred::JustEngagedWith(), boss_dalliah_the_doomsayer::JustEngagedWith(), boss_high_botanist_freywinn::JustEngagedWith(), boss_thorngrin_the_tender::JustEngagedWith(), boss_gatewatcher_iron_hand::JustEngagedWith(), boss_mechano_lord_capacitus::JustEngagedWith(), boss_nethermancer_sepethrea::JustEngagedWith(), boss_pathaleon_the_calculator::JustEngagedWith(), boss_sartharion::boss_sartharionAI::JustEngagedWith(), boss_curator::JustEngagedWith(), boss_maiden_of_virtue::JustEngagedWith(), boss_moroes::JustEngagedWith(), boss_netherspite::JustEngagedWith(), boss_felblood_kaelthas::JustEngagedWith(), boss_priestess_lackey_commonAI::JustEngagedWith(), boss_kagani_nightstrike::JustEngagedWith(), boss_yazzai::JustEngagedWith(), boss_brutallus::JustEngagedWith(), boss_sacrolash::JustEngagedWith(), boss_alythess::JustEngagedWith(), boss_muru::JustEngagedWith(), boss_halazzi::JustEngagedWith(), boss_hexlord_malacrass::JustEngagedWith(), boss_alyson_antille::JustEngagedWith(), boss_janalai::JustEngagedWith(), boss_nalorakk::JustEngagedWith(), boss_jeklik::JustEngagedWith(), npc_batrider::JustEngagedWith(), npc_ohgan::npc_ohganAI::JustEngagedWith(), boss_anetheron::JustEngagedWith(), boss_azgalor::JustEngagedWith(), boss_kazrogal::JustEngagedWith(), boss_rage_winterchill::JustEngagedWith(), boss_buru::JustEngagedWith(), boss_kurinnaxx::JustEngagedWith(), boss_ossirian::JustEngagedWith(), boss_vem::JustEngagedWith(), boss_twinemperorsAI::JustEngagedWith(), boss_anubrekhan::boss_anubrekhanAI::JustEngagedWith(), boss_commander_stoutbeard::JustEngagedWith(), boss_pandemonius::JustEngagedWith(), boss_gurtogg_bloodboil::JustEngagedWith(), boss_illidan_stormrage::JustEngagedWith(), boss_mother_shahraz::JustEngagedWith(), boss_supremus::JustEngagedWith(), boss_teron_gorefiend::JustEngagedWith(), boss_najentus::JustEngagedWith(), boss_fathomlord_karathress::JustEngagedWith(), boss_fathomguard_sharkkis::JustEngagedWith(), boss_fathomguard_caribdis::JustEngagedWith(), boss_hydross_the_unstable::JustEngagedWith(), boss_lady_vashj::JustEngagedWith(), boss_morogrim_tidewalker::JustEngagedWith(), boss_high_astromancer_solarian::JustEngagedWith(), boss_void_reaver::JustEngagedWith(), boss_lethon::boss_lethonAI::JustEngagedWith(), npc_flame_of_azzinoth::JustSummoned(), boss_twilight_corrupter::KilledUnit(), boss_mandokir::boss_mandokirAI::KilledUnit(), boss_volazj::KilledUnit(), boss_doomlord_kazzak::boss_doomlordkazzakAI::KilledUnit(), npc_earthen_ring_flamecaller::LookOpening(), npc_ouro_spawner::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::MoveInLineOfSight(), npc_shattered_hand_scout::MoveInLineOfSight(), npc_earthen_ring_flamecaller::MovementInform(), npc_eye_of_acherus::MovementInform(), boss_zuljin::MovementInform(), npc_harrison_jones::MovementInform(), boss_ayamiss::MovementInform(), boss_bug_trio::MovementInform(), npc_twilight_volunteer::MovementInform(), npc_vehicle_d16_propelled_delivery::npc_vehicle_d16_propelled_deliveryAI::MovementInform(), boss_illidan_stormrage::MovementInform(), npc_akama_illidan::MovementInform(), boss_lady_vashj::MovementInform(), boss_nazan::MovementInform(), boss_alar::MovementInform(), boss_felmyst::MovementInform(), npc_akama_shade::MovementInform(), boss_kaelthas::MovementInform(), boss_jedoga_shadowseeker::MovementInform(), npc_vics_flying_machine::npc_vics_flying_machineAI::MovementInform(), boss_glob_of_viscidus::MovementInform(), boss_shade_of_aran::OnPowerUpdate(), boss_jeklik::PathEndReached(), npc_akama_illidan::PathEndReached(), npc_hyjal_jaina::hyjalJainaAI::PathEndReached(), npc_hive_zara_swarmer::PathEndReached(), boss_kaelthas::PhaseEnchantedWeaponsExecute(), boss_nefarian::Reset(), boss_golemagg::boss_golemaggAI::Reset(), npc_core_rager::npc_core_ragerAI::Reset(), npc_chesspiece::Reset(), boss_curator::Reset(), boss_moroes::Reset(), boss_malchezaar::Reset(), boss_servant_quarters::Reset(), boss_felblood_kaelthas::Reset(), boss_vexallus::Reset(), boss_brutallus::Reset(), boss_sacrolash::Reset(), boss_alythess::Reset(), boss_kalec::Reset(), boss_sathrovarr::Reset(), npc_kiljaeden_controller::Reset(), boss_kiljaeden::Reset(), boss_entropius::Reset(), npc_singularity::Reset(), boss_hexlord_malacrass::Reset(), boss_janalai::Reset(), npc_zuljin_vortex::Reset(), boss_jeklik::Reset(), boss_ayamiss::Reset(), npc_ouro_spawner::Reset(), npc_dirt_mound::Reset(), npc_kerlonian::npc_kerlonianAI::Reset(), npc_amanitar_mushrooms::Reset(), npc_ahnkahar_nerubian::Reset(), npc_ulduar_keeper::npc_ulduar_keeperAI::Reset(), boss_exarch_maladaar::Reset(), boss_darkweaver_syth::Reset(), boss_talon_king_ikiss::Reset(), boss_illidan_stormrage::Reset(), npc_akama_illidan::Reset(), npc_akama_shade::Reset(), boss_teron_gorefiend::Reset(), boss_najentus::Reset(), boss_leotheras_the_blind::Reset(), boss_mennu_the_betrayer::Reset(), boss_rokmar_the_crackler::Reset(), boss_ghazan::Reset(), boss_hungarfen::Reset(), boss_high_king_maulgar::Reset(), boss_kelidan_the_breaker::Reset(), boss_omor_the_unscarred::Reset(), boss_watchkeeper_gargolmar::Reset(), boss_magtheridon::Reset(), npc_target_trigger::Reset(), boss_grand_warlock_nethekurse::Reset(), boss_harbinger_skyriss::Reset(), boss_laj::Reset(), boss_high_astromancer_solarian::Reset(), boss_pathaleon_the_calculator::Reset(), boss_alar::ScheduleAbilities(), boss_illidan_stormrage::ScheduleAbilities(), boss_julianne::ScheduleCombat(), boss_romulo::ScheduleCombat(), boss_magtheridon::ScheduleCombatEvents(), npc_lord_sanguinar::ScheduleEvents(), boss_felmyst::ScheduleFlightAbilities(), boss_supremus::SchedulePhase(), boss_baroness_anastari::boss_baroness_anastariAI::SchedulePossession(), boss_the_lurker_below::SchedulerPhaseOne(), boss_lady_vashj::ScheduleSpells(), npc_giant_claw_tentacle::ScheduleTasks(), boss_ayamiss::ScheduleTasks(), boss_laj::ScheduleTasks(), npc_warchief_portal::SetData(), boss_hydross_the_unstable::SetForm(), npc_thassarian2::npc_thassarian2AI::sGossipHello(), boss_nalorakk::ShapeShift(), npc_netherspite_infernal::SpellHit(), npc_maiev_illidan::SpellHit(), boss_viscidus::SpellHit(), boss_zuljin::SpellHitTarget(), npc_midsummer_bonfire::StampOut(), boss_felmyst::StartIntro(), npc_giant_claw_tentacle::Submerge(), boss_ouro::Submerge(), boss_ahune::Submerge(), boss_cthun::SummonedCreatureDies(), boss_apothecary_hummel::boss_apothecary_hummelAI::SummonedCreatureDies(), boss_jedoga_shadowseeker::SummonedCreatureDies(), boss_terestian_illhoof::SummonKilrek(), boss_fathomguard_tidalvess::SummonTotem(), boss_netherspite::SwitchToBanishPhase(), boss_netherspite::SwitchToPortalPhase(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::UpdateAI(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_garr::boss_garrAI::UpdateAI(), boss_golemagg::boss_golemaggAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_chesspiece::UpdateAI(), npc_eye_of_acherus::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), npc_forest_frog::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::UpdateAI(), boss_jindo::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), npc_coren_direbrew::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_onyxian_lair_guard::UpdateAI(), boss_buru::UpdateAI(), boss_moam::UpdateAI(), boss_ossirian::UpdateAI(), boss_huhuran::UpdateAI(), boss_sartura::UpdateAI(), npc_sartura_royal_guard::UpdateAI(), boss_viscidus::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), npc_amanitar_mushrooms::UpdateAI(), boss_elder_nadox::UpdateAI(), npc_ahnkahar_nerubian::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), npc_taldaram_flamesphere::UpdateAI(), boss_taldaram::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), boss_noth::boss_nothAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_minigob_manabonk::UpdateAI(), boss_gathios_the_shatterer::UpdateAI(), boss_lady_malande::UpdateAI(), boss_veras_darkshadow::UpdateAI(), npc_frozen_core::UpdateAI(), npc_ahune_bunny::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), npc_general_andorov::UpdateEscortAI(), and npc_barnes::npc_barnesAI::WaypointReached().
DoCastToAllHostilePlayers()
SpellCastResult UnitAI::DoCastToAllHostilePlayers (uint32 spellid, bool triggered = false)
To specify the caster as target if the spell is self-cast.
{
    if (me->IsInCombat())
    {
        ThreatContainer::StorageType threatlist = me->GetThreatMgr().GetThreatList();
        for (ThreatContainer::StorageType::const_iterator itr = threatlist.begin(); itr != threatlist.end(); ++itr)
        {
            if (Unit* unit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid()))
            {
                if (unit->IsPlayer())
                    return me->CastSpell(unit, spellid, triggered);
            }
            else
                return SPELL_FAILED_BAD_TARGETS;
        }
    }
    return SPELL_FAILED_CUSTOM_ERROR;
}
References Unit::CastSpell(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), ObjectAccessor::GetUnit(), Unit::IsInCombat(), me, SPELL_FAILED_BAD_TARGETS, and SPELL_FAILED_CUSTOM_ERROR.
DoCastVictim()
SpellCastResult UnitAI::DoCastVictim (uint32 spellId, bool triggered = false)
{
    if (Unit* victim = me->GetVictim())
        return DoCast(victim, spellId, triggered);
    return SPELL_FAILED_BAD_TARGETS;
}
References DoCast(), Unit::GetVictim(), me, and SPELL_FAILED_BAD_TARGETS.
Referenced by boss_marli::_schedulePhaseSpider(), boss_marli::_schedulePhaseTroll(), boss_mor_grayhoof::CastRandomSpell(), boss_thekal::CheckPhaseTransition(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), boss_broggok::DoAction(), boss_ouro::Emerge(), boss_halazzi::EnterPhase(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::ExecuteEvent(), boss_warmaster_voone::boss_warmastervooneAI::ExecuteEvent(), boss_gehennas::boss_gehennasAI::ExecuteEvent(), boss_lucifron::boss_lucifronAI::ExecuteEvent(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_sulfuron::boss_sulfuronAI::ExecuteEvent(), boss_amanitar::ExecuteEvent(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_ysondre::boss_ysondreAI::ExecuteEvent(), boss_emeriss::boss_emerissAI::ExecuteEvent(), boss_attumen::IsSummonedBy(), npc_inner_demon::IsSummonedBy(), boss_balinda::JustEngagedWith(), boss_malchezaar::JustEngagedWith(), boss_servant_quarters::JustEngagedWith(), npc_kilrek::JustEngagedWith(), boss_terestian_illhoof::JustEngagedWith(), npc_tito::JustEngagedWith(), boss_roar::JustEngagedWith(), boss_strawman::JustEngagedWith(), boss_tinhead::JustEngagedWith(), boss_crone::JustEngagedWith(), boss_bigbadwolf::JustEngagedWith(), boss_kormok::JustEngagedWith(), boss_baroness_anastari::boss_baroness_anastariAI::JustEngagedWith(), boss_jarien::JustEngagedWith(), boss_sothos::JustEngagedWith(), boss_kalec::JustEngagedWith(), boss_sathrovarr::JustEngagedWith(), boss_twilight_corrupter::JustEngagedWith(), boss_akilzon::JustEngagedWith(), boss_gahzranka::JustEngagedWith(), npc_shade_of_jindo::JustEngagedWith(), npc_vilebranch_speaker::JustEngagedWith(), boss_thekal::JustEngagedWith(), npc_zealot_lorkhan::JustEngagedWith(), npc_zealot_zath::JustEngagedWith(), npc_hallows_end_soh::JustEngagedWith(), boss_azuregos::boss_azuregosAI::JustEngagedWith(), npc_hyjal_jaina::hyjalJainaAI::JustEngagedWith(), npc_hyjal_tyrande::hyjalTyrandeAI::JustEngagedWith(), npc_hyjal_ground_trash::JustEngagedWith(), npc_hyjal_gargoyle::JustEngagedWith(), npc_hyjal_frost_wyrm::JustEngagedWith(), boss_epoch_hunter::JustEngagedWith(), boss_lieutenant_drake::JustEngagedWith(), boss_aeonus::JustEngagedWith(), boss_chrono_lord_deja::JustEngagedWith(), boss_temporus::JustEngagedWith(), npc_claw_tentacle::JustEngagedWith(), npc_icc_spire_frostwyrm::JustEngagedWith(), boss_keleseth::JustEngagedWith(), boss_nexusprince_shaffar::JustEngagedWith(), boss_tavarok::JustEngagedWith(), boss_ambassador_hellmaw::JustEngagedWith(), npc_akama_illidan::JustEngagedWith(), npc_maiev_illidan::JustEngagedWith(), npc_flame_of_azzinoth::JustEngagedWith(), boss_essence_of_desire::boss_essence_of_desireAI::JustEngagedWith(), boss_essence_of_anger::boss_essence_of_angerAI::JustEngagedWith(), npc_akama_shade::JustEngagedWith(), boss_doomlord_kazzak::boss_doomlordkazzakAI::JustEngagedWith(), boss_doomwalker::JustEngagedWith(), boss_mennu_the_betrayer::JustEngagedWith(), boss_quagmirran::JustEngagedWith(), boss_rokmar_the_crackler::JustEngagedWith(), boss_mekgineer_steamrigger::JustEngagedWith(), boss_warlord_kalithresh::JustEngagedWith(), boss_ghazan::JustEngagedWith(), boss_swamplord_muselek::JustEngagedWith(), boss_gruul::JustEngagedWith(), boss_high_king_maulgar::JustEngagedWith(), boss_olm_the_summoner::JustEngagedWith(), boss_kiggler_the_crazed::JustEngagedWith(), boss_krosh_firehand::JustEngagedWith(), boss_vazruden::JustEngagedWith(), boss_watchkeeper_gargolmar::JustEngagedWith(), boss_dalliah_the_doomsayer::JustEngagedWith(), boss_commander_sarannis::JustEngagedWith(), boss_gatewatcher_gyrokill::JustEngagedWith(), boss_gatewatcher_iron_hand::JustEngagedWith(), boss_mechano_lord_capacitus::JustEngagedWith(), boss_nethermancer_sepethrea::JustEngagedWith(), boss_curator::JustEngagedWith(), boss_midnight::JustEngagedWith(), boss_moroes::JustEngagedWith(), boss_felblood_kaelthas::JustEngagedWith(), boss_kagani_nightstrike::JustEngagedWith(), boss_ellris_duskhallow::JustEngagedWith(), boss_eramas_brightblaze::JustEngagedWith(), boss_yazzai::JustEngagedWith(), boss_warlord_salaris::JustEngagedWith(), boss_garaxxas::JustEngagedWith(), boss_apoko::JustEngagedWith(), boss_zelfan::JustEngagedWith(), boss_brutallus::JustEngagedWith(), boss_sacrolash::JustEngagedWith(), boss_alythess::JustEngagedWith(), boss_kalecgos::JustEngagedWith(), boss_nalorakk::JustEngagedWith(), npc_batrider::JustEngagedWith(), npc_ohgan::npc_ohganAI::JustEngagedWith(), boss_marli::JustEngagedWith(), boss_azgalor::JustEngagedWith(), boss_kazrogal::JustEngagedWith(), boss_kurinnaxx::JustEngagedWith(), boss_kri::JustEngagedWith(), boss_vem::JustEngagedWith(), boss_yauj::JustEngagedWith(), boss_fankriss::JustEngagedWith(), boss_veknilash::JustEngagedWith(), boss_veklor::JustEngagedWith(), boss_commander_stoutbeard::JustEngagedWith(), boss_murmur::JustEngagedWith(), boss_gurtogg_bloodboil::JustEngagedWith(), boss_high_nethermancer_zerevor::JustEngagedWith(), boss_mother_shahraz::JustEngagedWith(), boss_fathomguard_tidalvess::JustEngagedWith(), boss_morogrim_tidewalker::JustEngagedWith(), boss_grand_warlock_nethekurse::JustEngagedWith(), boss_porung::JustEngagedWith(), boss_void_reaver::JustEngagedWith(), boss_ayamiss::MovementInform(), boss_nazan::MovementInform(), boss_servant_quarters::MovementInform(), boss_felmyst::MovementInform(), boss_kaelthas::MovementInform(), boss_jeklik::PathEndReached(), boss_malchezaar::Reset(), npc_apothecary_baxter::Reset(), npc_amanishi_tempest::Reset(), boss_archimonde::Reset(), npc_stolen_soul::Reset(), boss_high_king_maulgar::Reset(), boss_high_astromancer_solarian::Reset(), boss_alar::ScheduleAbilities(), boss_illidan_stormrage::ScheduleAbilities(), boss_romulo::ScheduleCombat(), boss_magtheridon::ScheduleCombatEvents(), npc_telonicus::ScheduleEvents(), npc_thaladred::ScheduleEvents(), boss_nightbane::ScheduleFly(), boss_nightbane::ScheduleGround(), boss_alar::ScheduleMainSpellAttack(), boss_lady_vashj::ScheduleSpells(), npc_giant_claw_tentacle::ScheduleTasks(), boss_attumen::ScheduleTasks(), boss_ayamiss::ScheduleTasks(), boss_laj::ScheduleTasks(), boss_nalorakk::ShapeShift(), npc_daphne_stilwell::npc_daphne_stilwellAI::Update(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), npc_phalanx::npc_phalanxAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_anubshiah::boss_anubshiahAI::UpdateAI(), boss_eviscerator::boss_evisceratorAI::UpdateAI(), boss_general_angerforge::boss_general_angerforgeAI::UpdateAI(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_hedrum::boss_hedrumAI::UpdateAI(), boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI::UpdateAI(), boss_magmus::boss_magmusAI::UpdateAI(), boss_moira_bronzebeardAI::UpdateAI(), boss_high_priestess_thaurissanAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), boss_gyth::boss_gythAI::UpdateAI(), boss_halycon::boss_halyconAI::UpdateAI(), boss_highlord_omokk::boss_highlordomokkAI::UpdateAI(), boss_lord_valthalak::boss_lord_valthalakAI::UpdateAI(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_quartermaster_zigris::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::UpdateAI(), boss_broodlord::boss_broodlordAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_ebonroc::boss_ebonrocAI::UpdateAI(), boss_firemaw::boss_firemawAI::UpdateAI(), boss_flamegor::boss_flamegorAI::UpdateAI(), boss_nefarian::UpdateAI(), boss_razorgore::boss_razorgoreAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_flamewaker_priest::npc_flamewaker_priestAI::UpdateAI(), npc_mc_core_hound::npc_mc_core_houndAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), npc_sentinel_leader::UpdateAI(), npc_sentinel_infiltrator::UpdateAI(), npc_corporal_keeshan::npc_corporal_keeshanAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::UpdateAI(), boss_jindo::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_onyxia::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_buru::UpdateAI(), boss_ossirian::UpdateAI(), boss_huhuran::UpdateAI(), boss_sartura::UpdateAI(), npc_sartura_royal_guard::UpdateAI(), boss_skeram::UpdateAI(), npc_death_ravager::npc_death_ravagerAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_aquementas::npc_aquementasAI::UpdateAI(), npc_cairne_bloodhoof::npc_cairne_bloodhoofAI::UpdateAI(), npc_ame::npc_ameAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), boss_elder_nadox::UpdateAI(), boss_volazj::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_twilight_summon::npc_twilight_summonAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), boss_lady_vashj::UpdateAI(), boss_leotheras_the_blind::UpdateAI(), boss_omor_the_unscarred::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), npc_aeranas::npc_aeranasAI::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_general_andorov::UpdateEscortAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), and npc_kurenai_captive::npc_kurenai_captiveAI::UpdateEscortAI().
DoGetSpellMaxRange()
float UnitAI::DoGetSpellMaxRange (uint32 spellId, bool positive = false)
{
    SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
    return spellInfo ? spellInfo->GetMaxRange(positive) : 0;
}
References SpellInfo::GetMaxRange(), and sSpellMgr.
DoMeleeAttackIfReady()
void UnitAI::DoMeleeAttackIfReady ()
{
    if (me->HasUnitState(UNIT_STATE_CASTING))
        return;
    Unit* victim = me->GetVictim();
    if (!victim || !victim->IsInWorld())
        return;
    if (!me->IsWithinMeleeRange(victim))
        return;
    //Make sure our attack is ready and we aren't currently casting before checking distance
    if (me->isAttackReady())
    {
        // xinef: prevent base and off attack in same time, delay attack at 0.2 sec
        if (me->HasOffhandWeaponForAttack())
            if (me->getAttackTimer(OFF_ATTACK) < ATTACK_DISPLAY_DELAY)
                me->setAttackTimer(OFF_ATTACK, ATTACK_DISPLAY_DELAY);
        me->AttackerStateUpdate(victim);
        me->resetAttackTimer();
    }
    if (me->HasOffhandWeaponForAttack() && me->isAttackReady(OFF_ATTACK))
    {
        // xinef: delay main hand attack if both will hit at the same time (players code)
        if (me->getAttackTimer(BASE_ATTACK) < ATTACK_DISPLAY_DELAY)
            me->setAttackTimer(BASE_ATTACK, ATTACK_DISPLAY_DELAY);
        me->AttackerStateUpdate(victim, OFF_ATTACK);
        me->resetAttackTimer(OFF_ATTACK);
    }
}
References ATTACK_DISPLAY_DELAY, Unit::AttackerStateUpdate(), BASE_ATTACK, Unit::getAttackTimer(), Unit::GetVictim(), Unit::HasOffhandWeaponForAttack(), Unit::HasUnitState(), Unit::isAttackReady(), Object::IsInWorld(), Unit::IsWithinMeleeRange(), me, OFF_ATTACK, Unit::resetAttackTimer(), Unit::setAttackTimer(), and UNIT_STATE_CASTING.
Referenced by PetAI::_doMeleeAttack(), boss_twin_valkyrAI::myDoMeleeAttackIfReady(), boss_sartharion_dragonAI::UpdateAI(), CombatAI::UpdateAI(), ArcherAI::UpdateAI(), ReactorAI::UpdateAI(), ScriptedAI::UpdateAI(), BossAI::UpdateAI(), WorldBossAI::UpdateAI(), SmartAI::UpdateAI(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), boss_balinda::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), npc_phalanx::npc_phalanxAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_anubshiah::boss_anubshiahAI::UpdateAI(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::UpdateAI(), boss_eviscerator::boss_evisceratorAI::UpdateAI(), boss_general_angerforge::boss_general_angerforgeAI::UpdateAI(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_hedrum::boss_hedrumAI::UpdateAI(), boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI::UpdateAI(), boss_magmus::boss_magmusAI::UpdateAI(), boss_moira_bronzebeardAI::UpdateAI(), boss_high_priestess_thaurissanAI::UpdateAI(), boss_okthor::boss_okthorAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), boss_gyth::boss_gythAI::UpdateAI(), boss_halycon::boss_halyconAI::UpdateAI(), boss_highlord_omokk::boss_highlordomokkAI::UpdateAI(), boss_lord_valthalak::boss_lord_valthalakAI::UpdateAI(), boss_mor_grayhoof::UpdateAI(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_quartermaster_zigris::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::UpdateAI(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::UpdateAI(), boss_broodlord::boss_broodlordAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_ebonroc::boss_ebonrocAI::UpdateAI(), boss_firemaw::boss_firemawAI::UpdateAI(), boss_flamegor::boss_flamegorAI::UpdateAI(), boss_nefarian::UpdateAI(), boss_razorgore::boss_razorgoreAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_garr::boss_garrAI::UpdateAI(), boss_golemagg::boss_golemaggAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_flamewaker_priest::npc_flamewaker_priestAI::UpdateAI(), npc_mc_core_hound::npc_mc_core_houndAI::UpdateAI(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), boss_attumen::UpdateAI(), boss_midnight::UpdateAI(), boss_moroes::UpdateAI(), boss_netherspite::UpdateAI(), boss_nightbane::UpdateAI(), npc_malchezaar_axe::UpdateAI(), boss_servant_quarters::UpdateAI(), npc_kilrek::UpdateAI(), boss_dorothee::UpdateAI(), npc_tito::UpdateAI(), boss_roar::UpdateAI(), boss_strawman::UpdateAI(), boss_tinhead::UpdateAI(), boss_crone::UpdateAI(), boss_bigbadwolf::UpdateAI(), boss_julianne::UpdateAI(), boss_romulo::UpdateAI(), boss_priestess_lackey_commonAI::UpdateAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_scarlet_courier::npc_scarlet_courierAI::UpdateAI(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_mograine::npc_mograineAI::UpdateAI(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), boss_kormok::UpdateAI(), npc_scholomance_occultist::npc_scholomance_occultistAI::UpdateAI(), boss_apothecary_hummel::boss_apothecary_hummelAI::UpdateAI(), npc_apothecary_baxter::UpdateAI(), boss_baroness_anastari::boss_baroness_anastariAI::UpdateAI(), boss_jarien::UpdateAI(), boss_sothos::UpdateAI(), boss_felmyst::UpdateAI(), boss_kalec::UpdateAI(), boss_sathrovarr::UpdateAI(), boss_kiljaeden::UpdateAI(), boss_twilight_corrupter::UpdateAI(), npc_supervisor_raelen::UpdateAI(), npc_eastvale_peasent::UpdateAI(), npc_partygoer_pather::UpdateAI(), npc_partygoer::UpdateAI(), npc_sentinel_leader::UpdateAI(), npc_sentinel_infiltrator::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_corporal_keeshan::npc_corporal_keeshanAI::UpdateAI(), pyrewood_ambush::pyrewood_ambushAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), boss_alyson_antille::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_zulian_prowler::npc_zulian_prowlerAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::UpdateAI(), boss_jindo::UpdateAI(), npc_healing_ward::UpdateAI(), npc_shade_of_jindo::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), npc_ohgan::npc_ohganAI::UpdateAI(), npc_vilebranch_speaker::UpdateAI(), npc_spawn_of_marli::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_thekal::UpdateAI(), npc_zealot_lorkhan::UpdateAI(), npc_zealot_zath::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), npc_coren_direbrew::UpdateAI(), npc_coren_direbrew_sisters::UpdateAI(), npc_hallows_end_soh::UpdateAI(), boss_headless_horseman::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), npc_hyjal_jaina::hyjalJainaAI::UpdateAI(), npc_hyjal_thrall::hyjalThrallAI::UpdateAI(), npc_hyjal_tyrande::hyjalTyrandeAI::UpdateAI(), npc_hyjal_ground_trash::UpdateAI(), npc_hyjal_gargoyle::UpdateAI(), npc_hyjal_frost_wyrm::UpdateAI(), boss_epoch::boss_epochAI::UpdateAI(), boss_infinite_corruptor::boss_infinite_corruptorAI::UpdateAI(), boss_mal_ganis::boss_mal_ganisAI::UpdateAI(), boss_meathook::boss_meathookAI::UpdateAI(), boss_salramm::boss_salrammAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_lieutenant_drake::UpdateAI(), boss_isalien::UpdateAI(), boss_onyxia::UpdateAI(), npc_onyxian_lair_guard::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_buru::UpdateAI(), boss_moam::UpdateAI(), boss_ossirian::UpdateAI(), npc_anubisath_guardian::UpdateAI(), npc_hivezara_stinger::UpdateAI(), npc_obsidian_destroyer::UpdateAI(), boss_bug_trio::UpdateAI(), npc_claw_tentacle::UpdateAI(), npc_giant_claw_tentacle::UpdateAI(), boss_huhuran::UpdateAI(), boss_ouro::UpdateAI(), boss_sartura::UpdateAI(), npc_sartura_royal_guard::UpdateAI(), boss_skeram::UpdateAI(), boss_twinemperorsAI::UpdateAI(), boss_viscidus::UpdateAI(), npc_anubisath_defender::UpdateAI(), npc_vekniss_stinger::UpdateAI(), npc_obsidian_eradicator::UpdateAI(), npc_anubisath_warder::UpdateAI(), npc_obsidian_nullifier::UpdateAI(), npc_muglash::npc_muglashAI::UpdateAI(), npc_death_ravager::npc_death_ravagerAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::UpdateAI(), npc_tharnarian::npc_tharnarianAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_shenthul::npc_shenthulAI::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), npc_aquementas::npc_aquementasAI::UpdateAI(), npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI::UpdateAI(), npc_plucky::npc_pluckyAI::UpdateAI(), npc_cairne_bloodhoof::npc_cairne_bloodhoofAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), boss_elder_nadox::UpdateAI(), npc_ahnkahar_nerubian::UpdateAI(), boss_volazj::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), npc_twilight_volunteer::UpdateAI(), boss_taldaram::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), boss_hadronox::boss_hadronoxAI::UpdateAI(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_twilight_summon::npc_twilight_summonAI::UpdateAI(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), boss_eadric::boss_eadricAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), npc_argent_soldier::npc_argent_soldierAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_swarm_scarab::npc_swarm_scarabAI::UpdateAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI(), npc_toc_druid::npc_toc_druidAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_paladin::npc_toc_paladinAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), npc_toc_boomkin::npc_toc_boomkinAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI(), npc_toc_pet_warlock::npc_toc_pet_warlockAI::UpdateAI(), npc_toc_pet_hunter::npc_toc_pet_hunterAI::UpdateAI(), boss_jaraxxus::boss_jaraxxusAI::UpdateAI(), npc_fel_infernal::npc_fel_infernalAI::UpdateAI(), npc_mistress_of_pain::npc_mistress_of_painAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_dred::boss_dredAI::UpdateAI(), boss_tharon_ja::boss_tharon_jaAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_bronjahm::boss_bronjahmAI::UpdateAI(), boss_devourer_of_souls::boss_devourer_of_soulsAI::UpdateAI(), npc_fos_leader::npc_fos_leaderAI::UpdateAI(), boss_falric::boss_falricAI::UpdateAI(), boss_marwyn::boss_marwynAI::UpdateAI(), npc_ghostly_priest::npc_ghostly_priestAI::UpdateAI(), npc_phantom_mage::npc_phantom_mageAI::UpdateAI(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::UpdateAI(), npc_spectral_footman::npc_spectral_footmanAI::UpdateAI(), boss_frostsworn_general::boss_frostsworn_generalAI::UpdateAI(), npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI::UpdateAI(), npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), boss_drakkari_colossus::boss_drakkari_colossusAI::UpdateAI(), boss_drakkari_elemental::boss_drakkari_elementalAI::UpdateAI(), npc_living_mojo::npc_living_mojoAI::UpdateAI(), boss_eck::boss_eckAI::UpdateAI(), boss_gal_darah::boss_gal_darahAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), boss_slad_ran::boss_slad_ranAI::UpdateAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), npc_stinky_icc::npc_stinky_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), npc_vengeful_shade::npc_vengeful_shadeAI::UpdateAI(), npc_darnavan::npc_darnavanAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), npc_putricide_oozeAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), npc_little_ooze::npc_little_oozeAI::UpdateAI(), npc_big_ooze::npc_big_oozeAI::UpdateAI(), npc_precious_icc::npc_precious_iccAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_blistering_zombie::npc_blistering_zombieAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), npc_captain_rupert::npc_captain_rupertAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI::UpdateAI(), npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI::UpdateAI(), npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI::UpdateAI(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::UpdateAI(), npc_icc_severed_essence::npc_icc_severed_essenceAI::UpdateAI(), npc_icc_spire_frostwyrm::UpdateAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::UpdateAI(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::UpdateAI(), boss_isle_of_conquest::boss_isle_of_conquestAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), boss_heigan::boss_heiganAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::UpdateAI(), boss_loatheb::boss_loathebAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_noth::boss_nothAI::UpdateAI(), boss_patchwerk::boss_patchwerkAI::UpdateAI(), boss_razuvious_minion::boss_razuvious_minionAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_nexus_lord::npc_nexus_lordAI::UpdateAI(), boss_anomalus::UpdateAI(), boss_keristrasza::UpdateAI(), boss_magus_telestra::UpdateAI(), boss_ormorok::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), npc_stormforged_lieutenant::npc_stormforged_lieutenantAI::UpdateAI(), boss_ionar::boss_ionarAI::UpdateAI(), boss_loken::boss_lokenAI::UpdateAI(), boss_volkhan::boss_volkhanAI::UpdateAI(), npc_molten_golem::npc_molten_golemAI::UpdateAI(), npc_hol_monument::npc_hol_monumentAI::UpdateAI(), boss_krystallus::boss_krystallusAI::UpdateAI(), boss_maiden_of_grief::boss_maiden_of_griefAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_steelbreaker::boss_steelbreakerAI::UpdateAI(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_auriaya::boss_auriayaAI::UpdateAI(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::UpdateAI(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::UpdateAI(), boss_freya_summons::boss_freya_summonsAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI::UpdateAI(), npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI::UpdateAI(), npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::UpdateAI(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::UpdateAI(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), npc_xt002_pummeller::npc_xt002_pummellerAI::UpdateAI(), boss_yoggsaron_guardian_of_ys::boss_yoggsaron_guardian_of_ysAI::UpdateAI(), boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI::UpdateAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::UpdateAI(), boss_ingvar_the_plunderer::UpdateAI(), npc_vrykul_skeleton::UpdateAI(), boss_skarvald_the_constructor::UpdateAI(), boss_dalronn_the_controller::UpdateAI(), npc_enslaved_proto_drake::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), npc_ferocious_rhino::npc_ferocious_rhinoAI::UpdateAI(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::UpdateAI(), npc_frenzied_worgen::npc_frenzied_worgenAI::UpdateAI(), boss_skadi::boss_skadiAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), boss_koralon::boss_koralonAI::UpdateAI(), boss_toravon::boss_toravonAI::UpdateAI(), boss_cyanigosa::boss_cyanigosaAI::UpdateAI(), boss_erekem::boss_erekemAI::UpdateAI(), npc_erekem_guard::npc_erekem_guardAI::UpdateAI(), boss_lavanthor::boss_lavanthorAI::UpdateAI(), boss_moragg::boss_moraggAI::UpdateAI(), boss_xevozz::boss_xevozzAI::UpdateAI(), boss_zuramat::boss_zuramatAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_binder::npc_azure_binderAI::UpdateAI(), npc_azure_mage_slayer::npc_azure_mage_slayerAI::UpdateAI(), npc_azure_raider::npc_azure_raiderAI::UpdateAI(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), npc_azure_spellbreaker::npc_azure_spellbreakerAI::UpdateAI(), npc_azure_captain::npc_azure_captainAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_dalaran_mage::npc_dalaran_mageAI::UpdateAI(), npc_dalaran_warrior::npc_dalaran_warriorAI::UpdateAI(), npc_q24545_vegard::npc_q24545_vegardAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_wounded_skirmisher::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::UpdateAI(), npc_iron_watcher::npc_iron_watcherAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), boss_exarch_maladaar::UpdateAI(), npc_stolen_soul::UpdateAI(), boss_nexusprince_shaffar::UpdateAI(), npc_yor::UpdateAI(), boss_anzu::UpdateAI(), boss_ambassador_hellmaw::UpdateAI(), boss_blackheart_the_inciter::UpdateAI(), npc_akama_illidan::UpdateAI(), npc_maiev_illidan::UpdateAI(), npc_parasitic_shadowfiend::UpdateAI(), npc_flame_of_azzinoth::UpdateAI(), boss_gathios_the_shatterer::UpdateAI(), boss_high_nethermancer_zerevor::UpdateAI(), boss_veras_darkshadow::UpdateAI(), boss_essence_of_suffering::boss_essence_of_sufferingAI::UpdateAI(), boss_essence_of_desire::boss_essence_of_desireAI::UpdateAI(), boss_essence_of_anger::boss_essence_of_angerAI::UpdateAI(), boss_shade_of_akama::UpdateAI(), npc_akama_shade::UpdateAI(), boss_teron_gorefiend::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::UpdateAI(), boss_fathomguard_sharkkis::UpdateAI(), boss_fathomguard_tidalvess::UpdateAI(), boss_fathomguard_caribdis::UpdateAI(), boss_lady_vashj::UpdateAI(), boss_leotheras_the_blind::UpdateAI(), npc_inner_demon::UpdateAI(), boss_ghazan::UpdateAI(), boss_hungarfen::UpdateAI(), boss_the_black_stalker::UpdateAI(), npc_underbat::UpdateAI(), boss_gruul::UpdateAI(), boss_high_king_maulgar::UpdateAI(), boss_olm_the_summoner::UpdateAI(), boss_kiggler_the_crazed::UpdateAI(), boss_blindeye_the_seer::UpdateAI(), boss_krosh_firehand::UpdateAI(), boss_the_maker::UpdateAI(), boss_omor_the_unscarred::UpdateAI(), boss_nazan::UpdateAI(), boss_vazruden::UpdateAI(), boss_watchkeeper_gargolmar::UpdateAI(), boss_magtheridon::UpdateAI(), boss_grand_warlock_nethekurse::UpdateAI(), boss_warchief_kargath_bladefist::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_alar::UpdateAI(), advisor_baseAI::UpdateAI(), npc_raging_flames::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), npc_aeranas::npc_aeranasAI::UpdateAI(), npc_fel_guard_hound::npc_fel_guard_houndAI::UpdateAI(), npc_magister_aledis::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), npc_captain_saeed::npc_captain_saeedAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), emerald_dragonAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), npc_chicken_cluck::npc_chicken_cluckAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::UpdateAI(), AggressorAI::UpdateAI(), PossessedAI::UpdateAI(), npc_greengill_slave::npc_greengill_slaveAI::UpdateAI(), npc_marzon_silent_blade::npc_marzon_silent_bladeAI::UpdateAI(), npc_batrider::UpdateAI(), npc_hor_raging_ghoul::npc_hor_raging_ghoulAI::UpdateAI(), npc_centrifuge_construct::npc_centrifuge_constructAI::UpdateAI(), npc_xt002_life_spark::npc_xt002_life_sparkAI::UpdateAI(), boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI::UpdateAI(), npc_future_you::npc_future_youAI::UpdateAI(), npc_tallhorn_stag::npc_tallhorn_stagAI::UpdateAI(), npc_bushwhacker::npc_bushwhackerAI::UpdateAI(), outdoorpvp_na_halaa_creatures::UpdateAI(), npc_infernal_attacker::npc_infernal_attackerAI::UpdateAI(), npc_precious::npc_preciousAI::UpdateAI(), npc_escortAI::UpdateEscortAI(), npc_rinji::npc_rinjiAI::UpdateEscortAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_general_andorov::UpdateEscortAI(), npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::UpdateEscortAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), boss_bjarngrim::boss_bjarngrimAI::UpdateEscortAI(), npc_apothecary_hanes::npc_Apothecary_HanesAI::UpdateEscortAI(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::UpdateEscortAI(), npc_kurenai_captive::npc_kurenai_captiveAI::UpdateEscortAI(), npc_isla_starmane::npc_isla_starmaneAI::UpdateEscortAI(), npc_bonker_togglevolt::npc_bonker_togglevoltAI::UpdateEscortAI(), npc_kerlonian::npc_kerlonianAI::UpdateFollowerAI(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), npc_ringo::npc_ringoAI::UpdateFollowerAI(), and FollowerAI::UpdateFollowerAI().
DoSpellAttackIfReady()
bool UnitAI::DoSpellAttackIfReady (uint32 spell)
{
    if (me->HasUnitState(UNIT_STATE_CASTING) || !me->isAttackReady())
        return true;
    if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spell))
    {
        if (me->IsWithinCombatRange(me->GetVictim(), spellInfo->GetMaxRange(false)))
        {
            me->CastSpell(me->GetVictim(), spell, false);
            me->resetAttackTimer();
            return true;
        }
    }
    return false;
}
References Unit::CastSpell(), Unit::GetVictim(), Unit::HasUnitState(), Unit::isAttackReady(), Unit::IsWithinCombatRange(), me, Unit::resetAttackTimer(), sSpellMgr, and UNIT_STATE_CASTING.
Referenced by ArcherAI::UpdateAI(), TurretAI::UpdateAI(), npc_lava_spawn::UpdateAI(), boss_jormungarAI::UpdateAI(), npc_tortured_rifleman::npc_tortured_riflemanAI::UpdateAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI::UpdateAI(), npc_pet_gen_valkyr_guardian::UpdateAI(), boss_sjonnir_dwarf::boss_sjonnir_dwarfAI::UpdateAI(), and npc_pet_gen_gnomish_flame_turret::UpdateAI().
DoSpellAttackToRandomTargetIfReady()
void UnitAI::DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition = 0, float dist = 0.f, bool playerOnly = true)
{
    if (me->HasUnitState(UNIT_STATE_CASTING) || !me->isAttackReady())
        return;
    if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spell))
    {
        if (Unit* target = SelectTarget(SelectTargetMethod::Random, threatTablePosition, dist, playerOnly))
        {
            if (me->IsWithinCombatRange(target, spellInfo->GetMaxRange(false)))
            {
                me->CastSpell(target, spell, false);
                me->resetAttackTimer();
            }
        }
    }
}
References Unit::CastSpell(), Unit::HasUnitState(), Unit::isAttackReady(), Unit::IsWithinCombatRange(), me, Unit::resetAttackTimer(), SelectTarget(), sSpellMgr, and UNIT_STATE_CASTING.
Referenced by boss_ouro::DamageTaken().
FillAISpellInfo()
void UnitAI::FillAISpellInfo () static
{
    AISpellInfo = new AISpellInfoType[sSpellMgr->GetSpellInfoStoreSize()];
    AISpellInfoType* AIInfo = AISpellInfo;
    SpellInfo const* spellInfo;
    for (uint32 i = 0; i < sSpellMgr->GetSpellInfoStoreSize(); ++i, ++AIInfo)
    {
        spellInfo = sSpellMgr->GetSpellInfo(i);
        if (!spellInfo)
            continue;
        if (spellInfo->HasAttribute(SPELL_ATTR0_ALLOW_CAST_WHILE_DEAD))
            AIInfo->condition = AICOND_DIE;
        else if (spellInfo->IsPassive() || spellInfo->GetDuration() == -1)
            AIInfo->condition = AICOND_AGGRO;
        else
            AIInfo->condition = AICOND_COMBAT;
        if (AIInfo->cooldown < spellInfo->RecoveryTime)
            AIInfo->cooldown = spellInfo->RecoveryTime;
        if (!spellInfo->GetMaxRange(false))
            UPDATE_TARGET(AITARGET_SELF)
            else
            {
                for (uint32 j = 0; j < MAX_SPELL_EFFECTS; ++j)
                {
                    uint32 targetType = spellInfo->Effects[j].TargetA.GetTarget();
                    if (targetType == TARGET_UNIT_TARGET_ENEMY
                            || targetType == TARGET_DEST_TARGET_ENEMY)
                        UPDATE_TARGET(AITARGET_VICTIM)
                        else if (targetType == TARGET_UNIT_DEST_AREA_ENEMY)
                            UPDATE_TARGET(AITARGET_ENEMY)
                            if (spellInfo->Effects[j].Effect == SPELL_EFFECT_APPLY_AURA)
{
                                if (targetType == TARGET_UNIT_TARGET_ENEMY)
                                    UPDATE_TARGET(AITARGET_DEBUFF)
                                    else if (spellInfo->IsPositive())
                                        UPDATE_TARGET(AITARGET_BUFF)
                                    }
                }
            }
        AIInfo->realCooldown = spellInfo->RecoveryTime + spellInfo->StartRecoveryTime;
        AIInfo->maxRange = spellInfo->GetMaxRange(false) * 3 / 4;
    }
}
References AICOND_AGGRO, AICOND_COMBAT, AICOND_DIE, AISpellInfo, AITARGET_BUFF, AITARGET_DEBUFF, AITARGET_ENEMY, AITARGET_SELF, AITARGET_VICTIM, AISpellInfoType::condition, AISpellInfoType::cooldown, SpellInfo::Effects, SpellInfo::GetDuration(), SpellInfo::GetMaxRange(), SpellInfo::HasAttribute(), SpellInfo::IsPassive(), SpellInfo::IsPositive(), MAX_SPELL_EFFECTS, AISpellInfoType::maxRange, AISpellInfoType::realCooldown, SpellInfo::RecoveryTime, SPELL_ATTR0_ALLOW_CAST_WHILE_DEAD, SPELL_EFFECT_APPLY_AURA, sSpellMgr, SpellInfo::StartRecoveryTime, TARGET_DEST_TARGET_ENEMY, TARGET_UNIT_DEST_AREA_ENEMY, TARGET_UNIT_TARGET_ENEMY, and UPDATE_TARGET.
Referenced by ScriptMgr::FillSpellSummary().
GetData()
virtual uint32 UnitAI::GetData (uint32) const inline virtual
Reimplemented in npc_death_knight_initiate::npc_death_knight_initiateAI, boss_hadronox::boss_hadronoxAI, boss_krik_thir::boss_krik_thirAI, boss_dred::boss_dredAI, boss_novos::boss_novosAI, boss_slad_ran::boss_slad_ranAI, boss_anomalus, boss_magus_telestra, npc_captain_saeed::npc_captain_saeedAI, boss_sartharion::boss_sartharionAI, boss_keristrasza, boss_devourer_of_souls::boss_devourer_of_soulsAI, npc_gunship::npc_gunshipAI, boss_vezax::boss_vezaxAI, boss_hodir::boss_hodirAI, boss_ignis::boss_ignisAI, boss_mimiron::boss_mimironAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI, SmartAI, boss_algalon_the_observer::boss_algalon_the_observerAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_auriaya::boss_auriayaAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_freya::boss_freyaAI, boss_kologarn::boss_kologarnAI, boss_thorim::boss_thorimAI, boss_xt002::boss_xt002AI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, boss_yoggsaron::boss_yoggsaronAI, boss_yoggsaron_brain::boss_yoggsaron_brainAI, npc_pet_gen_argent_pony_bridle, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, npc_general_andorov, boss_elder_nadox, boss_jedoga_shadowseeker, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_festergut::boss_festergutAI, boss_professor_putricide::boss_professor_putricideAI, boss_sindragosa::boss_sindragosaAI, npc_sindragosa_trash::npc_sindragosa_trashAI, boss_the_lich_king::boss_the_lich_kingAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_valithria_portal::npc_valithria_portalAI, npc_elder_clearwater::npc_elder_clearwaterAI, npc_wormhole::npc_wormholeAI, npc_hallows_end_soh, boss_gal_darah::boss_gal_darahAI, npc_living_constellation::npc_living_constellationAI, and npc_ulduar_vx001::npc_ulduar_vx001AI.
{ return 0; }
Referenced by boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations(), instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::CallNextRajaxxLeader(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::CheckAchievementCriteriaMeet(), spell_putricide_mutation_init::CheckRequirementInternal(), spell_putricide_unstable_experiment::HandleScript(), spell_putricide_mutated_transformation::HandleSummon(), npc_risen_guardian::npc_risen_guardianAI::IsSummonedBy(), achievement_respect_your_elders::OnCheck(), achievement_hadronox_denied::OnCheck(), achievement_watch_him_die::OnCheck(), achievement_better_off_dred::OnCheck(), achievement_oh_novos::OnCheck(), achievement_share_the_love::OnCheck(), achievement_snakes_whyd_it_have_to_be_snakes::OnCheck(), achievement_flu_shot_shortage::OnCheck(), achievement_im_on_a_boat::OnCheck(), achievement_all_you_can_eat::OnCheck(), achievement_been_waiting_long_time::OnCheck(), achievement_neck_deep_in_vile::OnCheck(), achievement_portal_jockey::OnCheck(), achievement_chaos_theory::OnCheck(), achievement_split_personality::OnCheck(), achievement_algalon_he_feeds_on_your_tears::OnCheck(), achievement_algalon_herald_of_the_titans::OnCheck(), achievement_flame_leviathan_towers::OnCheck(), achievement_flame_leviathan_shutout::OnCheck(), achievement_freya_getting_back_to_nature::OnCheck(), achievement_freya_knock_on_wood::OnCheck(), achievement_smell_saronite::OnCheck(), achievement_shadowdodger::OnCheck(), achievement_cheese_the_freeze::OnCheck(), achievement_getting_cold_in_here::OnCheck(), achievement_i_could_say_that_this_cache_was_rare::OnCheck(), achievement_i_have_the_coolest_friends::OnCheck(), achievement_ignis_shattered::OnCheck(), achievement_mimiron_firefighter::OnCheck(), achievement_mimiron_set_up_us_the_bomb_11::OnCheck(), achievement_mimiron_set_up_us_the_bomb_12::OnCheck(), achievement_mimiron_set_up_us_the_bomb_13::OnCheck(), achievement_quick_shave::OnCheck(), achievement_yogg_saron_drive_me_crazy::OnCheck(), achievement_yogg_saron_kiss_and_make_up::OnCheck(), achievement_intense_cold::OnCheck(), npc_pet_gen_argent_pony_bridle::OnGossipHello(), npc_highlord_darion_mograine::OnGossipHello(), npc_captain_saeed::OnGossipHello(), npc_elder_clearwater::OnGossipHello(), npc_wormhole::OnGossipHello(), npc_death_knight_initiate::OnGossipSelect(), npc_elder_clearwater::OnQuestReward(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), OrderWhelpTargetSelector::operator()(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SummonedCreatureDespawn(), and npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI().
GetDebugInfo()
std::string UnitAI::GetDebugInfo () const virtual
{
    std::stringstream sstr;
    sstr << std::boolalpha
        << "Me: " << (me ? me->GetDebugInfo() : "NULL");
    return sstr.str();
}
References Unit::GetDebugInfo(), and me.
GetGUID()
virtual ObjectGuid UnitAI::GetGUID (int32 = 0) const inline virtual
Reimplemented in npc_coren_direbrew_sisters, boss_lord_marrowgar, SmartAI, boss_zuljin, and npc_unworthy_initiate_anchor::npc_unworthy_initiate_anchorAI.
{ return ObjectGuid::Empty; }
References ObjectGuid::Empty.
Referenced by spell_send_mug_target_picker::FilterTargets(), spell_marrowgar_bone_spike_graveyard::HandleSpikes(), npc_death_knight_initiate::OnGossipHello(), and boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SummonedCreatureDespawn().
GetThreatMgr()
ThreatMgr & UnitAI::GetThreatMgr () private
{
    return me->GetThreatMgr();
}
References Unit::GetThreatMgr(), and me.
Referenced by SelectTarget(), and SelectTargetList().
HealDone()
virtual void UnitAI::HealDone (Unit * , uint32 &) inline virtual
Called when the unit heals.
{}
Referenced by Unit::DealHeal().
HealReceived()
virtual void UnitAI::HealReceived (Unit * , uint32 &) inline virtual
Called when the creature receives heal.
Reimplemented in SmartAI, and boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI.
{}
Referenced by Unit::DealHeal().
InitializeAI()
virtual void UnitAI::InitializeAI () inline virtual
Reimplemented in CombatAI, CasterAI, SmartAI, npc_rookery_hatcher::npc_rookery_hatcherAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_urok_doomhowl::boss_urok_doomhowlAI, boss_majordomo::boss_majordomoAI, boss_moroes, boss_felblood_kaelthas, boss_priestess_delrissa, npc_eye_of_acherus, npc_scarlet_ghoul::npc_scarlet_ghoulAI, boss_kiljaeden, boss_twilight_corrupter, npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI, boss_venoxis, boss_captain_skarloc, boss_lieutenant_drake, boss_kurinnaxx, boss_moam, boss_ossirian, npc_general_andorov, boss_sartura, boss_glob_of_viscidus, npc_toxic_slime, npc_cork_gizelton::npc_cork_gizeltonAI, npc_troll_volunteer::npc_troll_volunteerAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, boss_volazj, boss_taldaram, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_valanar_icc::boss_prince_valanarAI, npc_spinestalker::npc_spinestalkerAI, npc_rimefang::npc_rimefangAI, npc_sindragosa_trash::npc_sindragosa_trashAI, npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI, boss_sapphiron::boss_sapphironAI, boss_malygos::boss_malygosAI, boss_flame_leviathan::boss_flame_leviathanAI, npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI, boss_razorscale::boss_razorscaleAI, npc_preparations_for_war_vehicle, npc_hourglass_of_eternity::npc_hourglass_of_eternityAI, npc_lord_arete::npc_lord_areteAI, npc_bushwhacker::npc_bushwhackerAI, boss_ambassador_hellmaw, npc_rancid_mushroom, npc_ahune_ice_spear_bunny, boss_ghazan, npc_underbog_mushroom, boss_warchief_kargath_bladefist, npc_millhouse_manastorm::npc_millhouse_manastormAI, boss_dalliah_the_doomsayer, boss_wrath_scryer_soccothrates, npc_raging_flames, npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI, npc_pet_dk_army_of_the_dead::npc_pet_dk_army_of_the_deadAI, npc_pet_dk_dancing_rune_weapon::npc_pet_dk_dancing_rune_weaponAI, npc_pet_gen_valkyr_guardian, npc_pet_gen_imp_in_a_bottle, npc_pet_mage_mirror_image, npc_pet_pri_lightwell, npc_pet_shaman_earth_elemental, npc_pet_shaman_fire_elemental, npc_precious::npc_preciousAI, and npc_wormhole::npc_wormholeAI.
{ if (!me->isDead()) Reset(); }
References Unit::isDead(), me, and Reset().
Referenced by Creature::AIM_Initialize(), CombatAI::InitializeAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::InitializeAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::InitializeAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::InitializeAI(), boss_majordomo::boss_majordomoAI::InitializeAI(), boss_moroes::InitializeAI(), boss_felblood_kaelthas::InitializeAI(), boss_priestess_delrissa::InitializeAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::InitializeAI(), boss_kiljaeden::InitializeAI(), boss_twilight_corrupter::InitializeAI(), boss_captain_skarloc::InitializeAI(), npc_cork_gizelton::npc_cork_gizeltonAI::InitializeAI(), boss_volazj::InitializeAI(), boss_taldaram::InitializeAI(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::InitializeAI(), boss_drakkari_colossus::boss_drakkari_colossusAI::InitializeAI(), boss_eck::boss_eckAI::InitializeAI(), boss_gal_darah::boss_gal_darahAI::InitializeAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::InitializeAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::InitializeAI(), boss_prince_valanar_icc::boss_prince_valanarAI::InitializeAI(), boss_sapphiron::boss_sapphironAI::InitializeAI(), boss_flame_leviathan::boss_flame_leviathanAI::InitializeAI(), npc_preparations_for_war_vehicle::InitializeAI(), boss_warchief_kargath_bladefist::InitializeAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::InitializeAI(), boss_dalliah_the_doomsayer::InitializeAI(), boss_wrath_scryer_soccothrates::InitializeAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), npc_pet_dk_dancing_rune_weapon::npc_pet_dk_dancing_rune_weaponAI::InitializeAI(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), and npc_pet_pri_lightwell::InitializeAI().
JustEnteredCombat()
virtual void UnitAI::JustEnteredCombat (Unit *) inline virtual
Called when the unit enters combat.
Note
NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
Todo:
Never invoked right now. Preparation for Combat Threat refactor
{ }
JustExitedCombat()
virtual void UnitAI::JustExitedCombat () inline virtual
Called when the unit leaves combat.
Todo:
Never invoked right now. Preparation for Combat Threat refactor
{ }
OnCalculateMeleeDamageReceived()
virtual void UnitAI::OnCalculateMeleeDamageReceived (uint32 & , Unit *) inline virtual
Called during damage calculations.
Reimplemented in npc_inner_demon.
{}
Referenced by Unit::CalculateMeleeDamage().
OnCalculatePeriodicTickReceived()
virtual void UnitAI::OnCalculatePeriodicTickReceived (uint32 & , Unit *) inline virtual
Called during calculation when receiving periodic healing or damage (DoT or HoT)
Reimplemented in npc_inner_demon.
{}
Referenced by AuraEffect::HandlePeriodicDamageAurasTick(), AuraEffect::HandlePeriodicHealAurasTick(), and AuraEffect::HandlePeriodicHealthLeechAuraTick().
OnCalculateSpellDamageReceived()
virtual void UnitAI::OnCalculateSpellDamageReceived (int32 & , Unit *) inline virtual
Reimplemented in npc_inner_demon.
{}
Referenced by Unit::CalculateSpellDamageTaken().
OnCharmed()
virtual void UnitAI::OnCharmed (bool apply) pure virtual
Called when unit is charmed.
Implemented in npc_vengeful_spirit, VehicleAI, PlayerAI, CreatureAI, SmartAI, boss_razorgore::boss_razorgoreAI, npc_chesspiece, npc_eye_of_acherus, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_pet_dk_risen_ally::npc_pet_dk_risen_allyAI, npc_controller, NullCreatureAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, npc_strangulate_vehicle::npc_strangulate_vehicleAI, npc_assembly_lightning::npc_assembly_lightningAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, npc_frosthound::npc_frosthoundAI, and npc_icefang::npc_icefangAI.
OnPowerUpdate()
virtual void UnitAI::OnPowerUpdate (Powers , int32 , int32 , uint32) inline virtual
Called when the creature power updates.
Reimplemented in boss_shade_of_aran, and boss_selin_fireheart.
{}
Referenced by Unit::ModifyPower().
Reset()
virtual void UnitAI::Reset () inline virtual
Reimplemented in CombatAI, GuardAI, ScriptedAI, BossAI, WorldBossAI, npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI, boss_balinda, boss_drekthar::boss_drektharAI, boss_galvangar::boss_galvangarAI, boss_vanndar::boss_vanndarAI, npc_grimstone::npc_grimstoneAI, npc_phalanx::npc_phalanxAI, npc_rocknot::npc_rocknotAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_general_angerforge::boss_general_angerforgeAI, boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI, boss_magmus::boss_magmusAI, boss_doomrel::boss_doomrelAI, boss_gyth::boss_gythAI, boss_halycon::boss_halyconAI, boss_highlord_omokk::boss_highlordomokkAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_mor_grayhoof, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, npc_blackhand_incarcerator::npc_blackhand_incarceratorAI, boss_quartermaster_zigris, boss_rend_blackhand::boss_rend_blackhandAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_the_beast::boss_thebeastAI, boss_chromaggus::boss_chromaggusAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_nefarian, npc_corrupted_totem, boss_razorgore::boss_razorgoreAI, boss_vaelastrasz::boss_vaelAI, boss_baron_geddon::boss_baron_geddonAI, boss_garr::boss_garrAI, boss_golemagg::boss_golemaggAI, npc_core_rager::npc_core_ragerAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, npc_flamewaker_priest::npc_flamewaker_priestAI, npc_mc_core_hound::npc_mc_core_houndAI, npc_lava_spawn, boss_mr_smite::boss_mr_smiteAI, npc_echo_of_medivh, npc_chesspiece, boss_curator, boss_attumen, boss_midnight, boss_moroes, boss_netherspite, boss_nightbane, boss_malchezaar, boss_servant_quarters, boss_shade_of_aran, npc_kilrek, npc_demon_chain, boss_terestian_illhoof, boss_dorothee, boss_tinhead, boss_crone, npc_cyclone, boss_julianne, boss_romulo, npc_barnes::npc_barnesAI, npc_image_of_medivh::npc_image_of_medivhAI, boss_felblood_kaelthas, boss_priestess_delrissa, boss_priestess_lackey_commonAI, boss_garaxxas, boss_selin_fireheart, boss_vexallus, npc_death_knight_initiate::npc_death_knight_initiateAI, npc_unworthy_initiate::npc_unworthy_initiateAI, npc_scarlet_miner::npc_scarlet_minerAI, npc_crusade_persuaded::npc_crusade_persuadedAI, npc_koltira_deathweaver::npc_koltira_deathweaverAI, npc_scarlet_courier::npc_scarlet_courierAI, npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI, npc_a_special_surprise::npc_a_special_surpriseAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI, npc_mograine::npc_mograineAI, boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI, npc_fairbanks::npc_fairbanksAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_kormok, boss_apothecary_hummel::boss_apothecary_hummelAI, npc_apothecary_baxter, boss_baroness_anastari::boss_baroness_anastariAI, boss_jarien, boss_sothos, boss_brutallus, boss_sacrolash, boss_alythess, boss_felmyst, npc_demonic_vapor, npc_demonic_vapor_trail, boss_kalecgos, boss_kalec, boss_sathrovarr, npc_kiljaeden_controller, boss_kiljaeden, npc_kalecgos_kj, boss_muru, boss_entropius, npc_singularity, boss_twilight_corrupter, npc_eris_hevenfire::npc_eris_hevenfireAI, npc_supervisor_raelen, npc_eastvale_peasent, npc_partygoer_pather, npc_partygoer, npc_ranger_lilatha, npc_sentinel_leader, npc_sentinel_infiltrator, npc_rinji::npc_rinjiAI, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, npc_corporal_keeshan::npc_corporal_keeshanAI, npc_deathstalker_erland::npc_deathstalker_erlandAI, pyrewood_ambush::pyrewood_ambushAI, npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI, npc_marzon_silent_blade::npc_marzon_silent_bladeAI, npc_tyrion_spybot::npc_tyrion_spybotAI, npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI, npc_highborne_lamenter::npc_highborne_lamenterAI, npc_varian_wrynn::npc_varian_wrynnAI, npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI, boss_blight_worm::boss_blight_wormAI, npc_thrall_bfu::npc_thrall_bfuAI, npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI, npc_the_scourge_cauldron::npc_the_scourge_cauldronAI, npc_daphne_stilwell::npc_daphne_stilwellAI, npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI, boss_akilzon, npc_akilzon_eagle, boss_halazzi, boss_hexlord_malacrass, boss_alyson_antille, boss_janalai, npc_janalai_hatcher, boss_nalorakk, boss_zuljin, npc_zuljin_vortex, npc_harrison_jones, npc_amanishi_lookout, npc_amanishi_tempest, boss_arlokk::boss_arlokkAI, npc_zulian_prowler::npc_zulian_prowlerAI, boss_grilek::boss_grilekAI, boss_hakkar::boss_hakkarAI, boss_jeklik, npc_batrider, npc_healing_ward, npc_shade_of_jindo, boss_mandokir::boss_mandokirAI, npc_ohgan::npc_ohganAI, npc_chained_spirit, npc_vilebranch_speaker, boss_marli, npc_spawn_of_marli, boss_renataki::boss_renatakiAI, boss_thekal, npc_zealot_lorkhan, npc_zealot_zath, boss_venoxis, npc_dark_iron_attack_generator, npc_dark_iron_attack_mole_machine, npc_dark_iron_guzzler, npc_brewfest_super_brew_trigger, npc_brew_bubble, npc_coren_direbrew, npc_direbrew_minion, npc_winterfin_playmate, npc_snowfall_glade_playmate, npc_the_biggest_tree, npc_high_oracle_soo_roo, npc_elder_kekek, npc_the_etymidian, npc_alexstraza_the_lifebinder, npc_costumed_orphan_matron, npc_soh_fire_trigger, npc_hallows_end_soh, npc_hallows_end_train_fire, boss_headless_horseman, boss_headless_horseman_head, boss_headless_horseman_pumpkin, npc_love_in_air_snivel, boss_azuregos::boss_azuregosAI, npc_ancient_wisp, npc_doomfire_spirit, boss_archimonde, boss_kazrogal, npc_hyjal_jaina::hyjalJainaAI, npc_hyjal_thrall::hyjalThrallAI, npc_hyjal_tyrande::hyjalTyrandeAI, npc_hyjal_ground_trash, npc_hyjal_gargoyle, npc_hyjal_frost_wyrm, boss_epoch::boss_epochAI, boss_infinite_corruptor::boss_infinite_corruptorAI, boss_mal_ganis::boss_mal_ganisAI, boss_meathook::boss_meathookAI, boss_salramm::boss_salrammAI, npc_arthas::npc_arthasAI, npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI, boss_captain_skarloc, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, npc_taretha::npc_tarethaAI, npc_medivh_bm, npc_time_rift, boss_isalien, boss_onyxia, npc_belnistrasz::npc_belnistraszAI, boss_ayamiss, boss_moam, boss_ossirian, npc_anubisath_guardian, npc_hivezara_stinger, npc_obsidian_destroyer, boss_bug_trio, boss_eye_of_cthun, boss_cthun, npc_eye_tentacle, npc_claw_tentacle, npc_giant_claw_tentacle, npc_giant_eye_tentacle, boss_fankriss, boss_huhuran, npc_ouro_spawner, boss_ouro, npc_dirt_mound, boss_sartura, npc_sartura_royal_guard, boss_skeram, boss_viscidus, npc_anubisath_sentinel::aqsentinelAI, npc_anubisath_defender, npc_vekniss_stinger, npc_obsidian_eradicator, npc_anubisath_warder, npc_obsidian_nullifier, npc_ahnqiraji_critter, npc_muglash::npc_muglashAI, npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI, npc_depth_charge::npc_depth_chargeAI, npc_draenei_survivor::npc_draenei_survivorAI, npc_injured_draenei::npc_injured_draeneiAI, npc_magwin::npc_magwinAI, npc_death_ravager::npc_death_ravagerAI, npc_stillpine_capitive::npc_stillpine_capitiveAI, npc_webbed_creature::npc_webbed_creatureAI, npc_murkdeep::npc_murkdeepAI, npc_kerlonian::npc_kerlonianAI, npc_prospector_remtravel::npc_prospector_remtravelAI, npc_rabid_thistle_bear::npc_rabid_thistle_bearAI, npc_tharnarian::npc_tharnarianAI, npc_troll_volunteer::npc_troll_volunteerAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_giant_spotlight::npc_giant_spotlightAI, npc_shenthul::npc_shenthulAI, npc_thrall_warchief::npc_thrall_warchiefAI, npc_anachronos_the_ancient::npc_anachronos_the_ancientAI, npc_qiraj_war_spawn::npc_qiraj_war_spawnAI, npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI, npc_kaya_flathoof::npc_kaya_flathoofAI, npc_aquementas::npc_aquementasAI, npc_custodian_of_time::npc_custodian_of_timeAI, npc_tooga::npc_toogaAI, npc_gilthares::npc_giltharesAI, npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI, npc_twiggy_flathead::npc_twiggy_flatheadAI, npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI, npc_lakota_windsong::npc_lakota_windsongAI, npc_paoka_swiftmountain::npc_paoka_swiftmountainAI, npc_plucky::npc_pluckyAI, npc_cairne_bloodhoof::npc_cairne_bloodhoofAI, npc_ame::npc_ameAI, npc_ringo::npc_ringoAI, npc_ranshalla::npc_ranshallaAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI, boss_amanitar, npc_amanitar_mushrooms, boss_elder_nadox, npc_ahnkahar_nerubian, boss_volazj, boss_jedoga_shadowseeker, boss_taldaram, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, npc_anub_ar_crusher::npc_anub_ar_crusherAI, boss_krik_thir::boss_krik_thirAI, boss_sartharion::boss_sartharionAI, boss_sartharion_dragonAI, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_sartharion_shadron::boss_sartharion_shadronAI, boss_sartharion_vesperon::boss_sartharion_vesperonAI, npc_twilight_summon::npc_twilight_summonAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, npc_xerestrasza::npc_xerestraszaAI, boss_general_zarithrian::boss_general_zarithrianAI, npc_onyx_flamecaller::npc_onyx_flamecallerAI, boss_halion::boss_halionAI, boss_twilight_halion::boss_twilight_halionAI, npc_halion_controller::npc_halion_controllerAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_eadric::boss_eadricAI, boss_paletress::boss_paletressAI, npc_memory::npc_memoryAI, npc_argent_soldier::npc_argent_soldierAI, boss_black_knight::boss_black_knightAI, npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI, npc_black_knight_ghoul::npc_black_knight_ghoulAI, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI, boss_grand_champion::boss_grand_championAI, npc_announcer_toc5::npc_announcer_toc5AI, boss_anubarak_trial::boss_anubarak_trialAI, npc_swarm_scarab::npc_swarm_scarabAI, npc_nerubian_burrower::npc_nerubian_burrowerAI, npc_anubarak_spike::npc_anubarak_spikeAI, boss_jaraxxus::boss_jaraxxusAI, npc_fel_infernal::npc_fel_infernalAI, npc_mistress_of_pain::npc_mistress_of_painAI, npc_snobold_vassal::npc_snobold_vassalAI, boss_gormok::boss_gormokAI, boss_dred::boss_dredAI, boss_novos::boss_novosAI, boss_tharon_ja::boss_tharon_jaAI, boss_trollgore::boss_trollgoreAI, boss_bronjahm::boss_bronjahmAI, npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, npc_fos_leader::npc_fos_leaderAI, boss_falric::boss_falricAI, boss_marwyn::boss_marwynAI, npc_hor_leader::npc_hor_leaderAI, npc_ghostly_priest::npc_ghostly_priestAI, npc_phantom_mage::npc_phantom_mageAI, npc_shadowy_mercenary::npc_shadowy_mercenaryAI, npc_spectral_footman::npc_spectral_footmanAI, npc_tortured_rifleman::npc_tortured_riflemanAI, boss_frostsworn_general::boss_frostsworn_generalAI, npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI, npc_hor_lich_king::npc_hor_lich_kingAI, npc_hor_leader_second::npc_hor_leader_secondAI, npc_hor_raging_ghoul::npc_hor_raging_ghoulAI, npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI, npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI, boss_garfrost::boss_garfrostAI, boss_ick::boss_ickAI, boss_tyrannus::boss_tyrannusAI, npc_pos_leader::npc_pos_leaderAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, npc_pos_after_first_boss::npc_pos_after_first_bossAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_drakkari_elemental::boss_drakkari_elementalAI, npc_living_mojo::npc_living_mojoAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_moorabi::boss_moorabiAI, boss_slad_ran::boss_slad_ranAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_valanar_icc::boss_prince_valanarAI, npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI, npc_dark_nucleus::npc_dark_nucleusAI, npc_kinetic_bomb::npc_kinetic_bombAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI, npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI, boss_festergut::boss_festergutAI, npc_stinky_icc::npc_stinky_iccAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, npc_cult_fanatic::npc_cult_fanaticAI, npc_cult_adherent::npc_cult_adherentAI, npc_vengeful_shade::npc_vengeful_shadeAI, npc_darnavan::npc_darnavanAI, boss_lord_marrowgar, boss_professor_putricide::boss_professor_putricideAI, boss_rotface::boss_rotfaceAI, npc_precious_icc::npc_precious_iccAI, boss_sindragosa::boss_sindragosaAI, npc_spinestalker::npc_spinestalkerAI, npc_rimefang::npc_rimefangAI, npc_sindragosa_trash::npc_sindragosa_trashAI, boss_the_lich_king::boss_the_lich_kingAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, npc_shambling_horror_icc::npc_shambling_horror_iccAI, npc_raging_spirit::npc_raging_spiritAI, npc_spirit_warden::npc_spirit_wardenAI, npc_lk_wicked_spirit::npc_lk_wicked_spiritAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, npc_the_lich_king_controller::npc_the_lich_king_controllerAI, npc_risen_archmage::npc_risen_archmageAI, npc_valithria_cloud::npc_valithria_cloudAI, npc_blazing_skeleton::npc_blazing_skeletonAI, npc_gluttonous_abomination::npc_gluttonous_abominationAI, npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI, npc_rotting_frost_giant::npc_rotting_frost_giantAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, boss_sister_svalna::boss_sister_svalnaAI, npc_argent_captainAI, npc_captain_arnath::npc_captain_arnathAI, npc_captain_brandon::npc_captain_brandonAI, npc_captain_grondel::npc_captain_grondelAI, npc_captain_rupert::npc_captain_rupertAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, npc_impaling_spear::npc_impaling_spearAI, npc_arthas_teleport_visual::npc_arthas_teleport_visualAI, npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI, npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI, npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI, npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, npc_icc_spire_frostwyrm, npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI, npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI, npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI, npc_icc_putricades_trap::npc_icc_putricades_trapAI, boss_isle_of_conquest::boss_isle_of_conquestAI, boss_anubrekhan::boss_anubrekhanAI, boss_faerlina::boss_faerlinaAI, boss_four_horsemen::boss_four_horsemenAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, npc_boss_gothik_minion::npc_boss_gothik_minionAI, boss_grobbulus::boss_grobbulusAI, boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI, boss_heigan::boss_heiganAI, boss_kelthuzad::boss_kelthuzadAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_noth::boss_nothAI, boss_patchwerk::boss_patchwerkAI, boss_razuvious::boss_razuviousAI, boss_razuvious_minion::boss_razuvious_minionAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_thaddius_summon::boss_thaddius_summonAI, boss_malygos::boss_malygosAI, boss_anomalus, boss_keristrasza, boss_magus_telestra, boss_ormorok, npc_crystal_spike, npc_crystalline_frayer, boss_drakos::boss_drakosAI, npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI, boss_eregos::boss_eregosAI, boss_urom::boss_uromAI, boss_varos::boss_varosAI, npc_centrifuge_construct::npc_centrifuge_constructAI, boss_bjarngrim::boss_bjarngrimAI, npc_stormforged_lieutenant::npc_stormforged_lieutenantAI, boss_ionar::boss_ionarAI, npc_spark_of_ionar::npc_spark_of_ionarAI, boss_loken::boss_lokenAI, boss_volkhan::boss_volkhanAI, npc_molten_golem::npc_molten_golemAI, npc_hol_monument::npc_hol_monumentAI, boss_krystallus::boss_krystallusAI, boss_maiden_of_grief::boss_maiden_of_griefAI, boss_sjonnir::boss_sjonnirAI, boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI, brann_bronzebeard::brann_bronzebeardAI, dark_rune_protectors::dark_rune_protectorsAI, dark_rune_stormcaller::dark_rune_stormcallerAI, iron_golem_custodian::iron_golem_custodianAI, boss_algalon_the_observer::boss_algalon_the_observerAI, npc_living_constellation::npc_living_constellationAI, npc_algalon_worm_hole::npc_algalon_worm_holeAI, boss_steelbreaker::boss_steelbreakerAI, boss_runemaster_molgeim::boss_runemaster_molgeimAI, npc_assembly_lightning::npc_assembly_lightningAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_auriaya::boss_auriayaAI, npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI, npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_flame_leviathan_seat::boss_flame_leviathan_seatAI, npc_freya_ward::npc_freya_wardAI, npc_hodirs_fury::npc_hodirs_furyAI, npc_mimirons_inferno::npc_mimirons_infernoAI, npc_thorims_hammer::npc_thorims_hammerAI, npc_brann_radio::npc_brann_radioAI, npc_mechanolift::npc_mechanoliftAI, boss_freya::boss_freyaAI, boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI, boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI, boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI, boss_freya_lifebinder::boss_freya_lifebinderAI, boss_freya_healthy_spore::boss_freya_healthy_sporeAI, boss_freya_summons::boss_freya_summonsAI, boss_freya_nature_bomb::boss_freya_nature_bombAI, boss_vezax::boss_vezaxAI, boss_hodir::boss_hodirAI, npc_ulduar_iron_construct::npc_ulduar_iron_constructAI, boss_ignis::boss_ignisAI, boss_kologarn::boss_kologarnAI, boss_kologarn_arms::boss_kologarn_armsAI, boss_kologarn_pit_kill_bunny, boss_mimiron::boss_mimironAI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI, npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI, npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI, npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI, npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI, npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI, boss_thorim::boss_thorimAI, boss_thorim_sif::boss_thorim_sifAI, boss_thorim_lightning_orb::boss_thorim_lightning_orbAI, boss_thorim_trap::boss_thorim_trapAI, boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI, boss_thorim_pillar::boss_thorim_pillarAI, boss_thorim_start_npcs::boss_thorim_start_npcsAI, boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI, boss_thorim_runic_colossus::boss_thorim_runic_colossusAI, boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI, boss_thorim_arena_npcs::boss_thorim_arena_npcsAI, boss_xt002::boss_xt002AI, npc_xt002_scrapbot::npc_xt002_scrapbotAI, npc_xt002_pummeller::npc_xt002_pummellerAI, npc_xt002_boombot::npc_xt002_boombotAI, npc_xt002_life_spark::npc_xt002_life_sparkAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_yoggsaron_guardian_of_ys::boss_yoggsaron_guardian_of_ysAI, boss_yoggsaron_brain::boss_yoggsaron_brainAI, boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI, boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI, boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI, boss_yoggsaron_llane::boss_yoggsaron_llaneAI, boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI, boss_yoggsaron_voice::boss_yoggsaron_voiceAI, npc_ulduar_keeper::npc_ulduar_keeperAI, npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, boss_ingvar_the_plunderer, npc_vrykul_skeleton, boss_skarvald_the_constructor, boss_dalronn_the_controller, npc_dragonflayer_forge_master, npc_enslaved_proto_drake, boss_palehoof::boss_palehoofAI, npc_massive_jormungar::npc_massive_jormungarAI, npc_ferocious_rhino::npc_ferocious_rhinoAI, npc_ravenous_furbolg::npc_ravenous_furbolgAI, npc_frenzied_worgen::npc_frenzied_worgenAI, boss_skadi::boss_skadiAI, boss_skadi_grauf::boss_skadi_graufAI, boss_svala::boss_svalaAI, boss_ymiron::boss_ymironAI, boss_archavon::boss_archavonAI, boss_emalon::boss_emalonAI, boss_koralon::boss_koralonAI, boss_toravon::boss_toravonAI, npc_frozen_orb::npc_frozen_orbAI, npc_frozen_orb_stalker::npc_frozen_orb_stalkerAI, boss_cyanigosa::boss_cyanigosaAI, boss_erekem::boss_erekemAI, npc_erekem_guard::npc_erekem_guardAI, boss_ichoron::boss_ichoronAI, boss_lavanthor::boss_lavanthorAI, boss_moragg::boss_moraggAI, boss_xevozz::boss_xevozzAI, boss_zuramat::boss_zuramatAI, npc_azure_invader::npc_azure_invaderAI, npc_azure_binder::npc_azure_binderAI, npc_azure_mage_slayer::npc_azure_mage_slayerAI, npc_azure_raider::npc_azure_raiderAI, npc_azure_stalker::npc_azure_stalkerAI, npc_azure_spellbreaker::npc_azure_spellbreakerAI, npc_azure_captain::npc_azure_captainAI, npc_azure_sorceror::npc_azure_sorcerorAI, npc_violet_hold_defense_system, npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI, npc_lurgglbr::npc_lurgglbrAI, npc_beryl_sorcerer::npc_beryl_sorcererAI, npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI, npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI, npc_mootoo_the_younger::npc_mootoo_the_youngerAI, npc_bonker_togglevolt::npc_bonker_togglevoltAI, npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI, npc_warmage_coldarra::npc_warmage_coldarraAI, npc_hidden_cultist::npc_hidden_cultistAI, npc_bloodmage_laurith::npc_bloodmage_laurithAI, npc_thassarian::npc_thassarianAI, npc_thassarian2::npc_thassarian2AI, npc_counselor_talbot::npc_counselor_talbotAI, npc_warmage_violetstand, npc_shandy_dalaran::npc_shandy_dalaranAI, npc_mageguard_dalaran::npc_mageguard_dalaranAI, npc_minigob_manabonk, npc_dalaran_mage::npc_dalaran_mageAI, npc_dalaran_warrior::npc_dalaran_warriorAI, npc_cosmetic_toy_plane, npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI, npc_future_you::npc_future_youAI, npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI, npc_heated_battle::npc_heated_battleAI, npc_q24545_lich_king::npc_q24545_lich_kingAI, npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI, npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI, npc_torturer_lecraft::npc_torturer_lecraftAI, npc_emily::npc_emilyAI, npc_mrfloppy::npc_mrfloppyAI, npc_tallhorn_stag::npc_tallhorn_stagAI, npc_amberpine_woodsman::npc_amberpine_woodsmanAI, npc_wounded_skirmisher, npc_venture_co_straggler::npc_venture_co_stragglerAI, npc_lake_frog::npc_lake_frogAI, npc_your_inner_turmoil::npc_your_inner_turmoilAI, npc_apothecary_hanes::npc_Apothecary_HanesAI, npc_plaguehound_tracker::npc_plaguehound_trackerAI, npc_battle_at_valhalas::npc_battle_at_valhalasAI, npc_llod_generic::npc_llod_genericAI, npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI, npc_tournament_training_dummy::npc_tournament_training_dummyAI, npc_blessed_banner::npc_blessed_bannerAI, npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI, npc_still_at_it_trigger::npc_still_at_it_triggerAI, npc_engineer_helice::npc_engineer_heliceAI, npc_jungle_punch_target::npc_jungle_punch_targetAI, npc_iron_watcher::npc_iron_watcherAI, npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_brunnhildar_prisoner::npc_brunnhildar_prisonerAI, npc_freed_protodrake::npc_freed_protodrakeAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, npc_drakuru_shackles::npc_drakuru_shacklesAI, npc_captured_rageclaw::npc_captured_rageclawAI, npc_released_offspring_harkoa::npc_released_offspring_harkoaAI, npc_crusade_recruit::npc_crusade_recruitAI, npc_storm_cloud::npc_storm_cloudAI, boss_exarch_maladaar, npc_stolen_soul, boss_shirrak_the_dead_watcher, boss_nexusprince_shaffar, npc_yor, boss_tavarok, boss_anzu, npc_anzu_spirit, boss_darkweaver_syth, boss_talon_king_ikiss, boss_ambassador_hellmaw, boss_blackheart_the_inciter, boss_grandmaster_vorpil, npc_voidtraveler, boss_murmur, boss_gurtogg_bloodboil, boss_illidan_stormrage, npc_akama_illidan, npc_maiev_illidan, boss_illidari_council_memberAI, boss_high_nethermancer_zerevor, boss_mother_shahraz, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, boss_essence_of_desire::boss_essence_of_desireAI, boss_essence_of_anger::boss_essence_of_angerAI, boss_shade_of_akama, npc_akama_shade, npc_creature_generator_akama, npc_ashtongue_channeler, boss_supremus, boss_teron_gorefiend, boss_najentus, boss_doomlord_kazzak::boss_doomlordkazzakAI, boss_doomwalker, boss_fathomlord_karathress, boss_fathomguard_sharkkis, boss_fathomguard_tidalvess, boss_fathomguard_caribdis, boss_hydross_the_unstable, boss_lady_vashj, boss_leotheras_the_blind, boss_the_lurker_below, boss_morogrim_tidewalker, npc_earthen_ring_flamecaller, boss_mennu_the_betrayer, boss_rokmar_the_crackler, boss_warlord_kalithresh, boss_ghazan, boss_hungarfen, boss_swamplord_muselek, npc_underbat, boss_gruul, boss_high_king_maulgar, boss_olm_the_summoner, boss_kiggler_the_crazed, boss_blindeye_the_seer, boss_krosh_firehand, boss_broggok, boss_kelidan_the_breaker, boss_the_maker, boss_omor_the_unscarred, boss_vazruden_the_herald, boss_nazan, boss_vazruden, boss_watchkeeper_gargolmar, boss_magtheridon, npc_target_trigger, boss_grand_warlock_nethekurse, npc_shattered_hand_scout, boss_warchief_kargath_bladefist, npc_millhouse_manastorm::npc_millhouse_manastormAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_dalliah_the_doomsayer, boss_harbinger_skyriss, boss_wrath_scryer_soccothrates, boss_laj, boss_thorngrin_the_tender, boss_alar, boss_high_astromancer_solarian, boss_kaelthas, advisor_baseAI, boss_void_reaver, npc_raging_flames, boss_pathaleon_the_calculator, npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI, npc_deaths_fel_cannon::npc_deaths_fel_cannonAI, npc_nether_drake::npc_nether_drakeAI, npc_daranelle::npc_daranelleAI, npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI, npc_aeranas::npc_aeranasAI, npc_ancestral_wolf::npc_ancestral_wolfAI, npc_wounded_blood_elf::npc_wounded_blood_elfAI, npc_fel_guard_hound::npc_fel_guard_houndAI, npc_magister_aledis, npc_maghar_captive::npc_maghar_captiveAI, npc_creditmarker_visit_with_ancestors::npc_creditmarker_visit_with_ancestorsAI, npc_kurenai_captive::npc_kurenai_captiveAI, npc_captain_saeed::npc_captain_saeedAI, npc_commander_dawnforge::npc_commander_dawnforgeAI, npc_bessy::npc_bessyAI, npc_maxx_a_million_escort::npc_maxx_a_million_escortAI, npc_invis_infernal_caster::npc_invis_infernal_casterAI, npc_infernal_attacker::npc_infernal_attackerAI, npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI, npc_enslaved_netherwing_drake, npc_dragonmaw_peon::npc_dragonmaw_peonAI, npc_torloth_the_magnificent::npc_torloth_the_magnificentAI, npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, npc_illidari_spawn::npc_illidari_spawnAI, npc_enraged_spirit::npc_enraged_spiritAI, npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI, npc_korkron_or_wildhammer, dragonmaw_race_npc, npc_kservant::npc_kservantAI, npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI, npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI, npc_pet_gen_argent_pony_bridle, npc_pet_gen_gnomish_flame_turret, npc_pet_gen_toxic_wasteling, npc_pet_hunter_snake_trap, npc_pet_mage_mirror_image, npc_pet_pri_shadowfiend, emerald_dragonAI, npc_dream_fog::npc_dream_fogAI, boss_ysondre::boss_ysondreAI, boss_lethon::boss_lethonAI, boss_emeriss::boss_emerissAI, boss_taerar::boss_taerarAI, guard_shattrath_scryer::guard_shattrath_scryerAI, guard_shattrath_aldor::guard_shattrath_aldorAI, npc_artorius::npc_artoriusAI, npc_precious::npc_preciousAI, npc_simone::npc_simoneAI, npc_nelson::npc_nelsonAI, npc_franklin::npc_franklinAI, npc_training_dummy::npc_training_dummyAI, npc_target_dummy::npc_target_dummyAI, npc_air_force_bots::npc_air_force_botsAI, npc_chicken_cluck::npc_chicken_cluckAI, npc_dancing_flames::npc_dancing_flamesAI, npc_doctor::npc_doctorAI, npc_injured_patient::npc_injured_patientAI, npc_garments_of_quests::npc_garments_of_questsAI, npc_guardian::npc_guardianAI, npc_steam_tonk::npc_steam_tonkAI, npc_firework::npc_fireworkAI, npc_spring_rabbit::npc_spring_rabbitAI, and npc_arcanite_dragonling.
{};
Referenced by CreatureAI::EnterEvadeMode(), ValithriaDespawner::Execute(), InitializeAI(), CreatureAI::JustRespawned(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::npc_infra_green_bomber_genericAI(), FrostwingGauntletRespawner::operator()(), ValithriaDespawner::operator()(), npc_batrider::Reset(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::Reset(), npc_pet_pri_shadowfiend::Reset(), and Creature::Respawn().
SelectTarget() [1/2]
template<class PREDICATE > Unit * UnitAI::SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const & predicate) inline
    {
        ThreatMgr& mgr = GetThreatMgr();
        // shortcut: if we ignore the first <offset> elements, and there are at most <offset> elements, then we ignore ALL elements
        if (mgr.GetThreatListSize() <= position)
            return nullptr;
        std::list<Unit*> targetList;
        SelectTargetList(targetList, mgr.GetThreatListSize(), targetType, position, predicate);
        // maybe nothing fulfills the predicate
        if (targetList.empty())
            return nullptr;
        switch (targetType)
        {
        case SelectTargetMethod::MaxThreat:
        case SelectTargetMethod::MinThreat:
        case SelectTargetMethod::MaxDistance:
        case SelectTargetMethod::MinDistance:
            return targetList.front();
        case SelectTargetMethod::Random:
            return Acore::Containers::SelectRandomContainerElement(targetList);
        default:
            return nullptr;
        }
    }
References ThreatMgr::GetThreatListSize(), GetThreatMgr(), Acore::Containers::SelectRandomContainerElement(), and SelectTargetList().
SelectTarget() [2/2]
Unit * UnitAI::SelectTarget (SelectTargetMethod targetType, uint32 position = 0, float dist = 0.0f, bool playerOnly = false, bool withTank = true, int32 aura = 0)
{
    return SelectTarget(targetType, position, DefaultTargetSelector(me, dist, playerOnly, withTank, aura));
}
References me, and SelectTarget().
Referenced by boss_marli::_chargePlayer(), WorldBossAI::_JustEngagedWith(), boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent(), boss_mor_grayhoof::CastRandomSpell(), npc_dirt_mound::ChaseNewTarget(), boss_buru::ChaseNewVictim(), boss_thekal::CheckPhaseTransition(), npc_ghostly_priest::npc_ghostly_priestAI::DoAction(), npc_phantom_mage::npc_phantom_mageAI::DoAction(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::DoAction(), npc_spectral_footman::npc_spectral_footmanAI::DoAction(), npc_tortured_rifleman::npc_tortured_riflemanAI::DoAction(), boss_ayamiss::DoAction(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::DoAction(), boss_sacrolash::DoAction(), boss_alythess::DoAction(), DoCast(), DoCastMaxThreat(), DoCastRandomTarget(), boss_alar::DoDiveBomb(), DoSpellAttackToRandomTargetIfReady(), npc_giant_claw_tentacle::Emerge(), boss_ouro::Emerge(), boss_halazzi::EnterPhase(), StartMovementEvent::Execute(), boss_baron_geddon::boss_baron_geddonAI::ExecuteEvent(), boss_gehennas::boss_gehennasAI::ExecuteEvent(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_amanitar::ExecuteEvent(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), npc_dream_fog::npc_dream_fogAI::GetRandomUnitFromDragonThreatList(), SmartScript::GetTargets(), spell_shadowblink::HandleDummy(), boss_ragnaros::boss_ragnarosAI::HandleEmerge(), boss_kaelthas::IntroduceNewAdvisor(), npc_supremus_punch_invisible_stalker::IsSummonedBy(), boss_sartharion_dragonAI::JustEngagedWith(), npc_malchezaar_axe::JustEngagedWith(), boss_servant_quarters::JustEngagedWith(), boss_terestian_illhoof::JustEngagedWith(), boss_bigbadwolf::JustEngagedWith(), boss_priestess_delrissa::JustEngagedWith(), boss_akilzon::JustEngagedWith(), npc_coren_direbrew_sisters::JustEngagedWith(), npc_hallows_end_soh::JustEngagedWith(), npc_hyjal_jaina::hyjalJainaAI::JustEngagedWith(), npc_hyjal_thrall::hyjalThrallAI::JustEngagedWith(), npc_hyjal_ground_trash::JustEngagedWith(), boss_lieutenant_drake::JustEngagedWith(), npc_eye_tentacle::JustEngagedWith(), npc_anubisath_defender::JustEngagedWith(), boss_keleseth::JustEngagedWith(), boss_exarch_maladaar::JustEngagedWith(), boss_anzu::JustEngagedWith(), boss_talon_king_ikiss::JustEngagedWith(), npc_flame_of_azzinoth::JustEngagedWith(), boss_doomlord_kazzak::boss_doomlordkazzakAI::JustEngagedWith(), boss_hungarfen::JustEngagedWith(), boss_swamplord_muselek::JustEngagedWith(), npc_underbat::JustEngagedWith(), boss_gruul::JustEngagedWith(), boss_kiggler_the_crazed::JustEngagedWith(), boss_watchkeeper_gargolmar::JustEngagedWith(), boss_harbinger_skyriss::JustEngagedWith(), boss_pathaleon_the_calculator::JustEngagedWith(), boss_curator::JustEngagedWith(), boss_kagani_nightstrike::JustEngagedWith(), boss_selin_fireheart::JustEngagedWith(), boss_brutallus::JustEngagedWith(), boss_sacrolash::JustEngagedWith(), boss_alythess::JustEngagedWith(), boss_janalai::JustEngagedWith(), boss_kazrogal::JustEngagedWith(), boss_kurinnaxx::JustEngagedWith(), npc_hivezara_stinger::JustEngagedWith(), boss_vem::JustEngagedWith(), boss_fankriss::JustEngagedWith(), npc_vekniss_stinger::JustEngagedWith(), boss_commander_stoutbeard::JustEngagedWith(), boss_gurtogg_bloodboil::JustEngagedWith(), boss_high_nethermancer_zerevor::JustEngagedWith(), boss_teron_gorefiend::JustEngagedWith(), boss_najentus::JustEngagedWith(), boss_fathomlord_karathress::JustEngagedWith(), boss_fathomguard_sharkkis::JustEngagedWith(), boss_high_astromancer_solarian::JustEngagedWith(), boss_maexxna::boss_maexxnaAI::JustSummoned(), boss_ingvar_the_plunderer::JustSummoned(), WorldBossAI::JustSummoned(), boss_vexallus::JustSummoned(), boss_sacrolash::JustSummoned(), npc_demonic_vapor_trail::JustSummoned(), boss_jindo::JustSummoned(), boss_gal_darah::boss_gal_darahAI::JustSummoned(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), npc_precious_icc::npc_precious_iccAI::JustSummoned(), boss_gothik::boss_gothikAI::JustSummoned(), boss_volkhan::boss_volkhanAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), boss_the_black_stalker::JustSummoned(), boss_lady_vashj::MovementInform(), boss_jeklik::PathEndReached(), boss_felblood_kaelthas::Reset(), npc_giant_eye_tentacle::Reset(), npc_swarm_scarab::npc_swarm_scarabAI::Reset(), boss_alar::ScheduleAbilities(), boss_romulo::ScheduleCombat(), npc_thaladred::ScheduleEvents(), boss_nightbane::ScheduleFly(), boss_nightbane::ScheduleGround(), boss_supremus::SchedulePhase(), boss_baroness_anastari::boss_baroness_anastariAI::SchedulePossession(), boss_attumen::ScheduleTasks(), boss_ayamiss::ScheduleTasks(), boss_cthun::ScheduleTasks(), npc_anubarak_spike::npc_anubarak_spikeAI::SelectNewTarget(), SelectTarget(), spell_marrowgar_coldflame::SelectTarget(), advisor_baseAI::SpellHit(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::SpellHitTarget(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SpellHitTarget(), boss_akilzon::SummonEagles(), boss_anubshiah::boss_anubshiahAI::UpdateAI(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::UpdateAI(), boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI::UpdateAI(), boss_okthor::boss_okthorAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_nefarian::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_flamewaker_priest::npc_flamewaker_priestAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_scholomance_occultist::npc_scholomance_occultistAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_akilzon_eagle::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_zulian_prowler::npc_zulian_prowlerAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), boss_headless_horseman::UpdateAI(), boss_epoch::boss_epochAI::UpdateAI(), boss_infinite_corruptor::boss_infinite_corruptorAI::UpdateAI(), boss_mal_ganis::boss_mal_ganisAI::UpdateAI(), boss_meathook::boss_meathookAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_onyxia::UpdateAI(), boss_sartura::UpdateAI(), npc_sartura_royal_guard::UpdateAI(), boss_skeram::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_cairne_bloodhoof::npc_cairne_bloodhoofAI::UpdateAI(), boss_volazj::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), boss_taldaram::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), boss_hadronox::boss_hadronoxAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), boss_eadric::boss_eadricAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), npc_argent_soldier::npc_argent_soldierAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_paladin::npc_toc_paladinAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_toc_boomkin::npc_toc_boomkinAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI(), boss_jaraxxus::boss_jaraxxusAI::UpdateAI(), npc_fel_infernal::npc_fel_infernalAI::UpdateAI(), npc_mistress_of_pain::npc_mistress_of_painAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), boss_tharon_ja::boss_tharon_jaAI::UpdateAI(), boss_bronjahm::boss_bronjahmAI::UpdateAI(), boss_devourer_of_souls::boss_devourer_of_soulsAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::UpdateAI(), boss_eck::boss_eckAI::UpdateAI(), boss_gal_darah::boss_gal_darahAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), npc_captain_rupert::npc_captain_rupertAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::UpdateAI(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::UpdateAI(), boss_isle_of_conquest::boss_isle_of_conquestAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_anomalus::UpdateAI(), boss_keristrasza::UpdateAI(), boss_magus_telestra::UpdateAI(), boss_ormorok::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), boss_ionar::boss_ionarAI::UpdateAI(), npc_hol_monument::npc_hol_monumentAI::UpdateAI(), boss_krystallus::boss_krystallusAI::UpdateAI(), boss_maiden_of_grief::boss_maiden_of_griefAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_steelbreaker::boss_steelbreakerAI::UpdateAI(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::UpdateAI(), boss_freya_summons::boss_freya_summonsAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_kologarn::boss_kologarnAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::UpdateAI(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::UpdateAI(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::UpdateAI(), boss_skarvald_the_constructor::UpdateAI(), boss_dalronn_the_controller::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), npc_ferocious_rhino::npc_ferocious_rhinoAI::UpdateAI(), boss_skadi::boss_skadiAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), boss_toravon::boss_toravonAI::UpdateAI(), boss_cyanigosa::boss_cyanigosaAI::UpdateAI(), boss_erekem::boss_erekemAI::UpdateAI(), boss_moragg::boss_moraggAI::UpdateAI(), boss_zuramat::boss_zuramatAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_binder::npc_azure_binderAI::UpdateAI(), npc_azure_mage_slayer::npc_azure_mage_slayerAI::UpdateAI(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), npc_azure_spellbreaker::npc_azure_spellbreakerAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), boss_lady_malande::UpdateAI(), boss_the_lurker_below::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), npc_zuljin_vortex::UpdateAI(), and boss_bjarngrim::boss_bjarngrimAI::UpdateEscortAI().
SelectTargetList() [1/2]
template<class PREDICATE > void UnitAI::SelectTargetList (std::list< Unit * > & targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const & predicate) inline
    {
        targetList.clear();
        ThreatMgr& mgr = GetThreatMgr();
        // shortcut: we're gonna ignore the first <offset> elements, and there's at most <offset> elements, so we ignore them all - nothing to do here
        if (mgr.GetThreatListSize() <= position)
            return;
        if (targetType == SelectTargetMethod::MaxDistance || targetType == SelectTargetMethod::MinDistance)
        {
            for (ThreatReference const* ref : mgr.GetUnsortedThreatList())
            {
                if (ref->IsOffline())
                    continue;
                targetList.push_back(ref->GetVictim());
            }
        }
        else
        {
            Unit* currentVictim = mgr.GetCurrentVictim();
            if (currentVictim)
                targetList.push_back(currentVictim);
            for (ThreatReference const* ref : mgr.GetSortedThreatList())
            {
                if (ref->IsOffline())
                    continue;
                Unit* thisTarget = ref->GetVictim();
                if (thisTarget != currentVictim)
                    targetList.push_back(thisTarget);
            }
        }
        // shortcut: the list isn't gonna get any larger
        if (targetList.size() <= position)
        {
            targetList.clear();
            return;
        }
        // right now, list is unsorted for DISTANCE types - re-sort by SelectTargetMethod::MaxDistance
        if (targetType == SelectTargetMethod::MaxDistance || targetType == SelectTargetMethod::MinDistance)
            SortByDistance(targetList, targetType == SelectTargetMethod::MinDistance);
        // now the list is MAX sorted, reverse for MIN types
        if (targetType == SelectTargetMethod::MinThreat)
            targetList.reverse();
        // ignore the first <offset> elements
        while (position)
        {
            targetList.pop_front();
            --position;
        }
        // then finally filter by predicate
        targetList.remove_if([&predicate](Unit* target) { return !predicate(target); });
        if (targetList.size() <= num)
            return;
        if (targetType == SelectTargetMethod::Random)
            Acore::Containers::RandomResize(targetList, num);
        else
            targetList.resize(num);
    }
References ThreatMgr::GetCurrentVictim(), ThreatMgr::GetSortedThreatList(), ThreatMgr::GetThreatListSize(), GetThreatMgr(), ThreatMgr::GetUnsortedThreatList(), Unit::GetVictim(), Acore::Containers::RandomResize(), and SortByDistance().
SelectTargetList() [2/2]
void UnitAI::SelectTargetList (std::list< Unit * > & targetList, uint32 num, SelectTargetMethod targetType, uint32 position = 0, float dist = 0.0f, bool playerOnly = false, bool withTank = true, int32 aura = 0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
Not among the first <offset> entries in <targetType> order (or SelectTargetMethod::MaxThreat order, if <targetType> is SelectTargetMethod::Random).
Within at most <dist> yards (if dist > 0.0f)
At least -<dist> yards away (if dist < 0.0f)
Is a player (if playerOnly = true)
Not the current tank (if withTank = false)
Has aura with ID <aura> (if aura > 0)
Does not have aura with ID -<aura> (if aura < 0) The resulting targets are stored in <targetList> (which is cleared first).
{
    SelectTargetList(targetList, num, targetType, position, DefaultTargetSelector(me, dist, playerOnly, withTank, aura));
}
References me, and SelectTargetList().
Referenced by boss_maexxna::boss_maexxnaAI::DoCastWebWrap(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), npc_obsidian_destroyer::JustEngagedWith(), SelectTarget(), SelectTargetList(), boss_festergut::boss_festergutAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), and boss_rotface::boss_rotfaceAI::UpdateAI().
SetData()
virtual void UnitAI::SetData (uint32 , uint32) inline virtual
Reimplemented in boss_svala::boss_svalaAI, npc_blackhand_incarcerator::npc_blackhand_incarceratorAI, boss_grand_warlock_nethekurse, boss_slad_ran::boss_slad_ranAI, boss_warbringer_omrogg, npc_eris_hevenfire::npc_eris_hevenfireAI, npc_cork_gizelton::npc_cork_gizeltonAI, boss_professor_putricide::boss_professor_putricideAI, npc_invis_infernal_caster::npc_invis_infernal_casterAI, npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI, SmartAI, ironhand_guardian::ironhand_guardianAI, npc_halion_controller::npc_halion_controllerAI, boss_hodir::boss_hodirAI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI, boss_arlokk::boss_arlokkAI, boss_garfrost::boss_garfrostAI, boss_ignis::boss_ignisAI, npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI, boss_janalai, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, npc_alexstraza_the_lifebinder, npc_dirt_mound, boss_sartharion::boss_sartharionAI, npc_saurfang_event::npc_saurfang_eventAI, boss_festergut::boss_festergutAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, gunship_npc_AI, npc_gunship_boarding_addAI, npc_sindragosa_trash::npc_sindragosa_trashAI, npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI, npc_enslaved_proto_drake, npc_q24545_lich_king::npc_q24545_lich_kingAI, npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI, boss_vazruden_the_herald, npc_warden_mellichar::npc_warden_mellicharAI, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI, boss_teron_gorefiend, boss_volazj, boss_the_lich_king::boss_the_lich_kingAI, boss_the_beast::boss_thebeastAI, boss_dred::boss_dredAI, boss_novos::boss_novosAI, npc_pos_leader::npc_pos_leaderAI, boss_anomalus, boss_keristrasza, npc_shandy_dalaran::npc_shandy_dalaranAI, npc_shattered_hand_scout, npc_warchief_portal, npc_simon_bunny::npc_simon_bunnyAI, boss_grand_champion::boss_grand_championAI, npc_argent_soldier::npc_argent_soldierAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, npc_supervisor_raelen, npc_eastvale_peasent, boss_thekal, npc_idol_room_spawner::npc_idol_room_spawnerAI, npc_thassarian2::npc_thassarian2AI, boss_mimiron::boss_mimironAI, npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI, and npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI.
{}
Referenced by RestoreAttack::Execute(), spell_kiljaeden_sinister_reflection_clone::FilterTargets(), spell_herald_volzaj_insanity::HandleAfterCast(), spell_hodir_flash_freeze_aura::HandleEffectPeriodic(), npc_commandscript::HandleNpcSetDataCommand(), spell_putricide_unstable_experiment::HandleScript(), spell_frostwarden_handler_focus_fire::HandleScript(), npc_risen_guardian::npc_risen_guardianAI::KilledUnit(), npc_shandy_dalaran::OnGossipSelect(), npc_eris_hevenfire::OnQuestAccept(), at_blackrock_stadium::OnTrigger(), SmartScript::ProcessAction(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), and boss_razorscale::boss_razorscaleAI::UpdateAI().
SetGUID()
virtual void UnitAI::SetGUID (ObjectGuid , int32 = 0) inline virtual
Reimplemented in boss_mandokir::boss_mandokirAI, boss_razorgore::boss_razorgoreAI, npc_ohgan::npc_ohganAI, npc_chained_spirit, boss_ossirian, boss_chromaggus::boss_chromaggusAI, boss_shade_of_aran, npc_coren_direbrew_sisters, npc_gunship::npc_gunshipAI, npc_simon_bunny::npc_simon_bunnyAI, SmartAI, boss_ragnaros::boss_ragnarosAI, boss_murmur, npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI, boss_archimonde, npc_putricide_oozeAI, npc_ice_tomb::npc_ice_tombAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, npc_dream_fog::npc_dream_fogAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, npc_kernobee::npc_kernobeeAI, npc_scarlet_ghoul::npc_scarlet_ghoulAI, npc_unworthy_initiate_anchor::npc_unworthy_initiate_anchorAI, npc_scarlet_miner_cart::npc_scarlet_miner_cartAI, npc_eris_hevenfire::npc_eris_hevenfireAI, npc_ball_of_flame::npc_ball_of_flameAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, npc_bloodmage_laurith::npc_bloodmage_laurithAI, npc_q24545_lich_king::npc_q24545_lich_kingAI, npc_kurenai_captive::npc_kurenai_captiveAI, npc_cork_gizelton::npc_cork_gizeltonAI, npc_captain_saeed::npc_captain_saeedAI, and npc_tharnarian::npc_tharnarianAI.
{}
Referenced by spell_blood_queen_bloodbolt::FilterTargets(), go_ossirian_crystal::go_ossirian_crystalAI::GossipHello(), spell_send_mug_target_picker::HandleDummy(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustSummoned(), boss_grandmaster_vorpil::JustSummoned(), emerald_dragonAI::JustSummoned(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), npc_captain_saeed::OnGossipSelect(), npc_kernobee::OnQuestAccept(), npc_kurenai_captive::OnQuestAccept(), npc_eris_hevenfire::OnQuestAccept(), npc_cork_gizelton::OnQuestAccept(), npc_lady_sylvanas_windrunner::OnQuestReward(), npc_tharnarian::OnQuestReward(), and spell_the_lich_king_valkyr_target_search::SelectTarget().
sGossipHello()
virtual void UnitAI::sGossipHello (Player *) inline virtual
Reimplemented in npc_thassarian2::npc_thassarian2AI, SmartAI, npc_echo_of_medivh, npc_chesspiece, npc_maredis_firestar::npc_maredis_firestarAI, npc_costumed_orphan_matron, npc_sergeant_bly::npc_sergeant_blyAI, and npc_weegli_blastfuse::npc_weegli_blastfuseAI.
{}
Referenced by WorldSession::HandleGossipHelloOpcode(), and WorldSession::HandleQuestgiverHelloOpcode().
sGossipSelect()
virtual void UnitAI::sGossipSelect (Player * , uint32 , uint32) inline virtual
Reimplemented in npc_tirion_fordring_tft::npc_tirion_fordringAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, boss_apothecary_hummel::boss_apothecary_hummelAI, npc_coren_direbrew, npc_pet_trainer::npc_pet_trainerAI, npc_stable_master::npc_stable_masterAI, SmartAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_vaelastrasz::boss_vaelAI, npc_harrison_jones, npc_brewfest_keg_reciver, npc_cairne_bloodhoof::npc_cairne_bloodhoofAI, npc_thassarian2::npc_thassarian2AI, npc_echo_of_medivh, npc_chesspiece, npc_tharnarian::npc_tharnarianAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_hidden_cultist::npc_hidden_cultistAI, npc_general_andorov, npc_maredis_firestar::npc_maredis_firestarAI, npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI, npc_zafod_boombox::npc_zafod_boomboxAI, npc_lake_frog::npc_lake_frogAI, npc_crusade_recruit::npc_crusade_recruitAI, npc_akama_illidan, npc_akama_shade, and npc_magister_aledis.
{}
Referenced by WorldSession::HandleGossipSelectOptionOpcode().
sGossipSelectCode()
virtual void UnitAI::sGossipSelectCode (Player * , uint32 , uint32 , char const *) inline virtual
Reimplemented in SmartAI.
{}
Referenced by WorldSession::HandleGossipSelectOptionOpcode().
sOnGameEvent()
virtual void UnitAI::sOnGameEvent (bool , uint16) inline virtual
Reimplemented in SmartAI, and npc_cameron.
{}
SortByDistance()
void UnitAI::SortByDistance (std::list< Unit * > & list, bool ascending = true) private
{
    list.sort(Acore::ObjectDistanceOrderPred(me, ascending));
}
References me.
Referenced by SelectTargetList().
sQuestAccept()
virtual void UnitAI::sQuestAccept (Player * , Quest const *) inline virtual
Reimplemented in npc_costumed_orphan_matron, npc_belnistrasz::npc_belnistraszAI, dragonmaw_race_npc, SmartAI, npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI, npc_ranger_lilatha, npc_rinji::npc_rinjiAI, npc_corporal_keeshan::npc_corporal_keeshanAI, npc_muglash::npc_muglashAI, npc_magwin::npc_magwinAI, and npc_wounded_blood_elf::npc_wounded_blood_elfAI.
{}
Referenced by Player::AddQuestAndCheckCompletion().
sQuestComplete()
virtual void UnitAI::sQuestComplete (Player * , Quest const *) inline virtual
{}
sQuestReward()
virtual void UnitAI::sQuestReward (Player * , Quest const * , uint32) inline virtual
Reimplemented in SmartAI.
{}
Referenced by WorldSession::HandleQuestgiverChooseRewardOpcode().
sQuestSelect()
virtual void UnitAI::sQuestSelect (Player * , Quest const *) inline virtual
{}
SummonMovementInform()
virtual void UnitAI::SummonMovementInform (Creature * , uint32 , uint32) inline virtual
Called when a summon reaches a waypoint or point movement finished.
Reimplemented in boss_hydross_the_unstable, and boss_razorgore::boss_razorgoreAI.
{ }
UpdateAI()
virtual void UnitAI::UpdateAI (uint32) pure virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implemented in boss_sartharion_dragonAI, CombatAI, CasterAI, ArcherAI, TurretAI, VehicleAI, ReactorAI, TotemAI, SimpleCharmedAI, ScriptedAI, BossAI, WorldBossAI, npc_escortAI, SmartAI, npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI, boss_balinda, boss_drekthar::boss_drektharAI, boss_galvangar::boss_galvangarAI, boss_vanndar::boss_vanndarAI, ironhand_guardian::ironhand_guardianAI, npc_phalanx::npc_phalanxAI, npc_rocknot::npc_rocknotAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_anubshiah::boss_anubshiahAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_eviscerator::boss_evisceratorAI, boss_general_angerforge::boss_general_angerforgeAI, boss_gorosh_the_dervish::boss_gorosh_the_dervishAI, boss_grizzle::boss_grizzleAI, boss_hedrum::boss_hedrumAI, boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI, boss_magmus::boss_magmusAI, boss_moira_bronzebeardAI, boss_high_priestess_thaurissanAI, boss_okthor::boss_okthorAI, boss_doomrel::boss_doomrelAI, boss_drakkisath::boss_drakkisathAI, boss_gyth::boss_gythAI, boss_halycon::boss_halyconAI, boss_highlord_omokk::boss_highlordomokkAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_mor_grayhoof, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, npc_blackhand_incarcerator::npc_blackhand_incarceratorAI, boss_quartermaster_zigris, boss_rend_blackhand::boss_rend_blackhandAI, npc_rookery_hatcher::npc_rookery_hatcherAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_the_beast::boss_thebeastAI, boss_urok_doomhowl::boss_urok_doomhowlAI, npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI, boss_broodlord::boss_broodlordAI, boss_chromaggus::boss_chromaggusAI, boss_ebonroc::boss_ebonrocAI, boss_firemaw::boss_firemawAI, boss_flamegor::boss_flamegorAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_nefarian, npc_corrupted_totem, npc_drakonid_spawner, boss_razorgore::boss_razorgoreAI, boss_vaelastrasz::boss_vaelAI, boss_garr::boss_garrAI, boss_golemagg::boss_golemaggAI, npc_core_rager::npc_core_ragerAI, boss_majordomo::boss_majordomoAI, boss_ragnaros::boss_ragnarosAI, npc_flamewaker_priest::npc_flamewaker_priestAI, npc_mc_core_hound::npc_mc_core_houndAI, npc_lava_spawn, boss_mr_smite::boss_mr_smiteAI, npc_kernobee::npc_kernobeeAI, npc_echo_of_medivh, npc_chesspiece, boss_attumen, boss_midnight, boss_moroes, boss_netherspite, boss_nightbane, npc_netherspite_infernal, npc_malchezaar_axe, boss_servant_quarters, boss_shade_of_aran, npc_kilrek, boss_dorothee, npc_tito, boss_roar, boss_strawman, boss_tinhead, boss_crone, npc_cyclone, boss_bigbadwolf, boss_julianne, boss_romulo, npc_barnes::npc_barnesAI, npc_image_of_medivh::npc_image_of_medivhAI, boss_felblood_kaelthas, boss_priestess_lackey_commonAI, npc_eye_of_acherus, npc_death_knight_initiate::npc_death_knight_initiateAI, npc_scarlet_ghoul::npc_scarlet_ghoulAI, npc_dkc1_gothik::npc_dkc1_gothikAI, npc_scarlet_cannon::npc_scarlet_cannonAI, npc_unworthy_initiate::npc_unworthy_initiateAI, npc_scarlet_miner::npc_scarlet_minerAI, npc_crusade_persuaded::npc_crusade_persuadedAI, npc_scarlet_courier::npc_scarlet_courierAI, npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI, npc_a_special_surprise::npc_a_special_surpriseAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI, npc_mograine::npc_mograineAI, boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI, boss_kormok, npc_scholomance_occultist::npc_scholomance_occultistAI, boss_apothecary_hummel::boss_apothecary_hummelAI, npc_apothecary_baxter, boss_baroness_anastari::boss_baroness_anastariAI, boss_jarien, boss_sothos, npc_madrigosa, boss_felmyst, npc_demonic_vapor_trail, boss_kalec, boss_sathrovarr, npc_kiljaeden_controller, boss_kiljaeden, npc_kalecgos_kj, boss_entropius, npc_singularity, npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI, boss_twilight_corrupter, npc_eris_hevenfire::npc_eris_hevenfireAI, npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI, npc_cameron, npc_supervisor_raelen, npc_eastvale_peasent, npc_partygoer_pather, npc_partygoer, npc_sentinel_leader, npc_sentinel_infiltrator, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, npc_grand_magister_rommath::npc_grand_magister_rommathAI, npc_corporal_keeshan::npc_corporal_keeshanAI, pyrewood_ambush::pyrewood_ambushAI, npc_ravenclaw_apparition::npc_ravenclaw_apparitionAI, npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI, npc_highborne_lamenter::npc_highborne_lamenterAI, npc_varian_wrynn::npc_varian_wrynnAI, npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI, boss_blight_worm::boss_blight_wormAI, npc_thrall_bfu::npc_thrall_bfuAI, npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI, npc_akilzon_eagle, boss_alyson_antille, npc_janalai_hatcher, boss_nalorakk, npc_forest_frog, npc_harrison_jones, npc_amanishi_tempest, boss_arlokk::boss_arlokkAI, npc_zulian_prowler::npc_zulian_prowlerAI, boss_grilek::boss_grilekAI, boss_hakkar::boss_hakkarAI, boss_hazzarah, boss_jindo, npc_healing_ward, npc_shade_of_jindo, boss_mandokir::boss_mandokirAI, npc_ohgan::npc_ohganAI, npc_vilebranch_speaker, npc_spawn_of_marli, boss_renataki::boss_renatakiAI, boss_thekal, npc_zealot_lorkhan, npc_zealot_zath, boss_wushoolay::boss_wushoolayAI, npc_dark_iron_attack_generator, npc_dark_iron_attack_mole_machine, npc_dark_iron_guzzler, npc_brewfest_super_brew_trigger, npc_brew_bubble, npc_coren_direbrew, npc_coren_direbrew_sisters, npc_winterfin_playmate, npc_snowfall_glade_playmate, npc_the_biggest_tree, npc_high_oracle_soo_roo, npc_elder_kekek, npc_the_etymidian, npc_alexstraza_the_lifebinder, npc_costumed_orphan_matron, npc_hallows_end_soh, npc_hallows_end_train_fire, boss_headless_horseman, boss_headless_horseman_head, boss_headless_horseman_pumpkin, npc_love_in_air_supply_sentry, npc_love_in_air_snivel, npc_love_in_air_snivel_real, npc_midsummer_bonfire, npc_midsummer_torch_target, npc_midsummer_ribbon_pole_target, npc_pilgrims_bounty_chair, boss_azuregos::boss_azuregosAI, npc_ancient_wisp, npc_doomfire_spirit, npc_hyjal_jaina::hyjalJainaAI, npc_hyjal_thrall::hyjalThrallAI, npc_hyjal_tyrande::hyjalTyrandeAI, npc_hyjal_ground_trash, npc_hyjal_gargoyle, npc_hyjal_frost_wyrm, boss_epoch::boss_epochAI, boss_infinite_corruptor::boss_infinite_corruptorAI, boss_mal_ganis::boss_mal_ganisAI, boss_meathook::boss_meathookAI, boss_salramm::boss_salrammAI, npc_arthas::npc_arthasAI, npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI, boss_captain_skarloc, boss_lieutenant_drake, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, npc_medivh_bm, npc_time_rift, boss_isalien, boss_onyxia, npc_onyxian_lair_guard, npc_belnistrasz::npc_belnistraszAI, boss_buru, boss_moam, boss_ossirian, npc_anubisath_guardian, boss_rajaxx, npc_hivezara_stinger, npc_obsidian_destroyer, boss_bug_trio, boss_cthun, npc_eye_tentacle, npc_claw_tentacle, npc_giant_claw_tentacle, npc_giant_eye_tentacle, boss_huhuran, boss_ouro, npc_dirt_mound, boss_sartura, npc_sartura_royal_guard, boss_skeram, boss_twinemperorsAI, boss_viscidus, boss_glob_of_viscidus, npc_anubisath_defender, npc_vekniss_stinger, npc_obsidian_eradicator, npc_anubisath_warder, npc_obsidian_nullifier, npc_ahnqiraji_critter, npc_muglash::npc_muglashAI, npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI, npc_depth_charge::npc_depth_chargeAI, npc_draenei_survivor::npc_draenei_survivorAI, npc_death_ravager::npc_death_ravagerAI, npc_stillpine_capitive::npc_stillpine_capitiveAI, npc_murkdeep::npc_murkdeepAI, npc_rabid_thistle_bear::npc_rabid_thistle_bearAI, npc_tharnarian::npc_tharnarianAI, npc_tiger_matriarch_credit::npc_tiger_matriarch_creditAI, npc_tiger_matriarch::npc_tiger_matriarchAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_omen::npc_omenAI, npc_giant_spotlight::npc_giant_spotlightAI, npc_shenthul::npc_shenthulAI, npc_thrall_warchief::npc_thrall_warchiefAI, npc_anachronos_the_ancient::npc_anachronos_the_ancientAI, npc_qiraj_war_spawn::npc_qiraj_war_spawnAI, npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI, npc_aquementas::npc_aquementasAI, npc_custodian_of_time::npc_custodian_of_timeAI, npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI, npc_twiggy_flathead::npc_twiggy_flatheadAI, npc_plucky::npc_pluckyAI, npc_cairne_bloodhoof::npc_cairne_bloodhoofAI, npc_ame::npc_ameAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI, npc_amanitar_mushrooms, boss_elder_nadox, npc_ahnkahar_nerubian, boss_volazj, boss_jedoga_shadowseeker, npc_twilight_volunteer, npc_taldaram_flamesphere, boss_taldaram, boss_anub_arak::boss_anub_arakAI, boss_hadronox::boss_hadronoxAI, npc_anub_ar_crusher::npc_anub_ar_crusherAI, boss_krik_thir::boss_krik_thirAI, boss_sartharion::boss_sartharionAI, npc_twilight_summon::npc_twilight_summonAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI, npc_xerestrasza::npc_xerestraszaAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_halion::boss_halionAI, boss_twilight_halion::boss_twilight_halionAI, npc_halion_controller::npc_halion_controllerAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_eadric::boss_eadricAI, boss_paletress::boss_paletressAI, npc_memory::npc_memoryAI, npc_argent_soldier::npc_argent_soldierAI, boss_black_knight::boss_black_knightAI, npc_black_knight_ghoul::npc_black_knight_ghoulAI, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI, boss_grand_champion::boss_grand_championAI, boss_anubarak_trial::boss_anubarak_trialAI, npc_swarm_scarab::npc_swarm_scarabAI, npc_frost_sphere::npc_frost_sphereAI, npc_nerubian_burrower::npc_nerubian_burrowerAI, npc_anubarak_spike::npc_anubarak_spikeAI, boss_faction_championsAI, npc_toc_druid::npc_toc_druidAI, npc_toc_shaman::npc_toc_shamanAI, npc_toc_paladin::npc_toc_paladinAI, npc_toc_priest::npc_toc_priestAI, npc_toc_shadow_priest::npc_toc_shadow_priestAI, npc_toc_warlock::npc_toc_warlockAI, npc_toc_mage::npc_toc_mageAI, npc_toc_hunter::npc_toc_hunterAI, npc_toc_boomkin::npc_toc_boomkinAI, npc_toc_warrior::npc_toc_warriorAI, npc_toc_dk::npc_toc_dkAI, npc_toc_rogue::npc_toc_rogueAI, npc_toc_enh_shaman::npc_toc_enh_shamanAI, npc_toc_retro_paladin::npc_toc_retro_paladinAI, npc_toc_pet_warlock::npc_toc_pet_warlockAI, npc_toc_pet_hunter::npc_toc_pet_hunterAI, boss_jaraxxus::boss_jaraxxusAI, npc_fel_infernal::npc_fel_infernalAI, npc_mistress_of_pain::npc_mistress_of_painAI, npc_snobold_vassal::npc_snobold_vassalAI, boss_gormok::boss_gormokAI, boss_jormungarAI, boss_icehowl::boss_icehowlAI, boss_twin_valkyrAI, boss_dred::boss_dredAI, boss_novos::boss_novosAI, boss_tharon_ja::boss_tharon_jaAI, boss_trollgore::boss_trollgoreAI, boss_bronjahm::boss_bronjahmAI, npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, npc_fos_leader::npc_fos_leaderAI, boss_falric::boss_falricAI, boss_marwyn::boss_marwynAI, npc_hor_leader::npc_hor_leaderAI, npc_ghostly_priest::npc_ghostly_priestAI, npc_phantom_mage::npc_phantom_mageAI, npc_phantom_hallucination::npc_phantom_hallucinationAI, npc_shadowy_mercenary::npc_shadowy_mercenaryAI, npc_spectral_footman::npc_spectral_footmanAI, npc_tortured_rifleman::npc_tortured_riflemanAI, boss_frostsworn_general::boss_frostsworn_generalAI, npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI, npc_hor_lich_king::npc_hor_lich_kingAI, npc_hor_leader_second::npc_hor_leader_secondAI, npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI, npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI, boss_garfrost::boss_garfrostAI, boss_ick::boss_ickAI, boss_krick::boss_krickAI, boss_tyrannus::boss_tyrannusAI, npc_pos_leader::npc_pos_leaderAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, npc_pos_after_first_boss::npc_pos_after_first_bossAI, npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI, npc_pos_icicle_trigger::npc_pos_icicle_triggerAI, npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI, npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI, npc_pos_leader_second::npc_pos_leader_secondAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_drakkari_elemental::boss_drakkari_elementalAI, npc_living_mojo::npc_living_mojoAI, boss_eck::boss_eckAI, boss_gal_darah::boss_gal_darahAI, boss_moorabi::boss_moorabiAI, boss_slad_ran::boss_slad_ranAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_valanar_icc::boss_prince_valanarAI, npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI, npc_dark_nucleus::npc_dark_nucleusAI, npc_kinetic_bomb::npc_kinetic_bombAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI, npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI, npc_icc_blood_beast::npc_icc_blood_beastAI, boss_festergut::boss_festergutAI, npc_stinky_icc::npc_stinky_iccAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_gunship_boarding_addAI, npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI, npc_gunship_boarding_add::npc_gunship_boarding_add_realAI, npc_gunship_mage::npc_gunship_mageAI, npc_gunship_gunner::npc_gunship_gunnerAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, npc_cult_fanatic::npc_cult_fanaticAI, npc_cult_adherent::npc_cult_adherentAI, npc_vengeful_shade::npc_vengeful_shadeAI, npc_darnavan::npc_darnavanAI, boss_lord_marrowgar, npc_coldflame::npc_coldflameAI, npc_bone_spike::npc_bone_spikeAI, boss_professor_putricide::boss_professor_putricideAI, npc_putricide_oozeAI, boss_rotface::boss_rotfaceAI, npc_little_ooze::npc_little_oozeAI, npc_big_ooze::npc_big_oozeAI, npc_precious_icc::npc_precious_iccAI, boss_sindragosa::boss_sindragosaAI, npc_ice_tomb::npc_ice_tombAI, npc_spinestalker::npc_spinestalkerAI, npc_rimefang::npc_rimefangAI, npc_sindragosa_trash::npc_sindragosa_trashAI, boss_the_lich_king::boss_the_lich_kingAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, npc_shambling_horror_icc::npc_shambling_horror_iccAI, npc_icc_ice_sphere::npc_icc_ice_sphereAI, npc_raging_spirit::npc_raging_spiritAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, npc_strangulate_vehicle::npc_strangulate_vehicleAI, npc_terenas_menethil::npc_terenas_menethilAI, npc_spirit_warden::npc_spirit_wardenAI, npc_lk_spirit_bomb::npc_lk_spirit_bombAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, npc_the_lich_king_controller::npc_the_lich_king_controllerAI, npc_risen_archmage::npc_risen_archmageAI, npc_valithria_cloud::npc_valithria_cloudAI, npc_blazing_skeleton::npc_blazing_skeletonAI, npc_blistering_zombie::npc_blistering_zombieAI, npc_gluttonous_abomination::npc_gluttonous_abominationAI, npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI, npc_rotting_frost_giant::npc_rotting_frost_giantAI, npc_frost_freeze_trap::npc_frost_freeze_trapAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, boss_sister_svalna::boss_sister_svalnaAI, npc_captain_arnath::npc_captain_arnathAI, npc_captain_brandon::npc_captain_brandonAI, npc_captain_grondel::npc_captain_grondelAI, npc_captain_rupert::npc_captain_rupertAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, npc_impaling_spear::npc_impaling_spearAI, npc_arthas_teleport_visual::npc_arthas_teleport_visualAI, npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI, npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI, npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI, npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, npc_icc_severed_essence::npc_icc_severed_essenceAI, npc_icc_spire_frostwyrm, npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI, npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI, npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI, npc_icc_putricades_trap::npc_icc_putricades_trapAI, npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI, npc_ioc_gunship_captain::npc_ioc_gunship_captainAI, boss_isle_of_conquest::boss_isle_of_conquestAI, boss_faerlina::boss_faerlinaAI, boss_four_horsemen::boss_four_horsemenAI, boss_gluth::boss_gluthAI, boss_gothik::boss_gothikAI, npc_boss_gothik_minion::npc_boss_gothik_minionAI, boss_grobbulus::boss_grobbulusAI, boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI, boss_heigan::boss_heiganAI, boss_kelthuzad::boss_kelthuzadAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, boss_loatheb::boss_loathebAI, boss_maexxna::boss_maexxnaAI, boss_noth::boss_nothAI, boss_patchwerk::boss_patchwerkAI, boss_razuvious::boss_razuviousAI, boss_razuvious_minion::boss_razuvious_minionAI, boss_sapphiron::boss_sapphironAI, boss_thaddius::boss_thaddiusAI, boss_thaddius_summon::boss_thaddius_summonAI, boss_naxxramas_misc::boss_naxxramas_miscAI, boss_malygos::boss_malygosAI, npc_vortex_ride::npc_vortex_rideAI, npc_power_spark::npc_power_sparkAI, npc_nexus_lord::npc_nexus_lordAI, npc_scion_of_eternity::npc_scion_of_eternityAI, npc_hover_disk::npc_hover_diskAI, npc_alexstrasza::npc_alexstraszaAI, boss_anomalus, boss_keristrasza, boss_magus_telestra, boss_ormorok, npc_crystal_spike, npc_crystalline_frayer, boss_drakos::boss_drakosAI, npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI, boss_eregos::boss_eregosAI, boss_urom::boss_uromAI, boss_varos::boss_varosAI, npc_oculus_drakegiver::npc_oculus_drakegiverAI, npc_oculus_drake::npc_oculus_drakeAI, npc_stormforged_lieutenant::npc_stormforged_lieutenantAI, boss_ionar::boss_ionarAI, boss_loken::boss_lokenAI, boss_volkhan::boss_volkhanAI, npc_molten_golem::npc_molten_golemAI, npc_hol_monument::npc_hol_monumentAI, boss_krystallus::boss_krystallusAI, boss_maiden_of_grief::boss_maiden_of_griefAI, boss_sjonnir::boss_sjonnirAI, boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI, boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI, dark_rune_protectors::dark_rune_protectorsAI, dark_rune_stormcaller::dark_rune_stormcallerAI, iron_golem_custodian::iron_golem_custodianAI, boss_algalon_the_observer::boss_algalon_the_observerAI, npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI, npc_living_constellation::npc_living_constellationAI, npc_algalon_worm_hole::npc_algalon_worm_holeAI, boss_steelbreaker::boss_steelbreakerAI, boss_runemaster_molgeim::boss_runemaster_molgeimAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_auriaya::boss_auriayaAI, npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI, npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_flame_leviathan_seat::boss_flame_leviathan_seatAI, boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI, npc_freya_ward::npc_freya_wardAI, npc_hodirs_fury::npc_hodirs_furyAI, npc_mimirons_inferno::npc_mimirons_infernoAI, npc_thorims_hammer::npc_thorims_hammerAI, npc_storm_beacon_spawn::npc_storm_beacon_spawnAI, boss_flame_leviathan_safety_container::boss_flame_leviathan_safety_containerAI, npc_mechanolift::npc_mechanoliftAI, boss_freya::boss_freyaAI, boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI, boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI, boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI, boss_freya_lifebinder::boss_freya_lifebinderAI, boss_freya_healthy_spore::boss_freya_healthy_sporeAI, boss_freya_summons::boss_freya_summonsAI, boss_freya_nature_bomb::boss_freya_nature_bombAI, boss_vezax::boss_vezaxAI, npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI, boss_hodir::boss_hodirAI, npc_ulduar_icicle::npc_ulduar_icicleAI, npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI, npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI, npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI, npc_ulduar_iron_construct::npc_ulduar_iron_constructAI, boss_ignis::boss_ignisAI, boss_kologarn::boss_kologarnAI, boss_kologarn_eyebeam::boss_kologarn_eyebeamAI, boss_kologarn_pit_kill_bunny, boss_mimiron::boss_mimironAI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI, npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI, npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI, npc_ulduar_flames_initial::npc_ulduar_flames_initialAI, npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI, npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI, npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI, npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI, boss_thorim::boss_thorimAI, boss_thorim_sif::boss_thorim_sifAI, boss_thorim_trap::boss_thorim_trapAI, boss_thorim_pillar::boss_thorim_pillarAI, boss_thorim_start_npcs::boss_thorim_start_npcsAI, boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI, boss_thorim_runic_colossus::boss_thorim_runic_colossusAI, boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI, boss_thorim_arena_npcs::boss_thorim_arena_npcsAI, boss_xt002::boss_xt002AI, npc_xt002_heart::npc_xt002_heartAI, npc_xt002_pummeller::npc_xt002_pummellerAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, boss_yoggsaron_guardian_of_ys::boss_yoggsaron_guardian_of_ysAI, boss_yoggsaron::boss_yoggsaronAI, boss_yoggsaron_brain::boss_yoggsaron_brainAI, boss_yoggsaron_death_orb::boss_yoggsaron_death_orbAI, boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI, boss_yoggsaron_keeper, boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI, boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI, boss_yoggsaron_llane::boss_yoggsaron_llaneAI, boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI, boss_yoggsaron_voice::boss_yoggsaron_voiceAI, npc_ulduar_keeper::npc_ulduar_keeperAI, npc_ulduar_snow_mound, npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, boss_ingvar_the_plunderer, npc_vrykul_skeleton, boss_skarvald_the_constructor, boss_dalronn_the_controller, npc_enslaved_proto_drake, boss_palehoof::boss_palehoofAI, npc_massive_jormungar::npc_massive_jormungarAI, npc_ferocious_rhino::npc_ferocious_rhinoAI, npc_ravenous_furbolg::npc_ravenous_furbolgAI, npc_frenzied_worgen::npc_frenzied_worgenAI, boss_skadi::boss_skadiAI, boss_skadi_grauf::boss_skadi_graufAI, boss_svala::boss_svalaAI, boss_ymiron::boss_ymironAI, boss_archavon::boss_archavonAI, boss_emalon::boss_emalonAI, boss_koralon::boss_koralonAI, boss_toravon::boss_toravonAI, npc_frozen_orb::npc_frozen_orbAI, boss_cyanigosa::boss_cyanigosaAI, boss_erekem::boss_erekemAI, npc_erekem_guard::npc_erekem_guardAI, boss_lavanthor::boss_lavanthorAI, boss_moragg::boss_moraggAI, boss_xevozz::boss_xevozzAI, boss_zuramat::boss_zuramatAI, npc_vh_void_sentry::npc_vh_void_sentryAI, npc_vh_teleportation_portal::npc_vh_teleportation_portalAI, violet_hold_trashAI, npc_azure_invader::npc_azure_invaderAI, npc_azure_binder::npc_azure_binderAI, npc_azure_mage_slayer::npc_azure_mage_slayerAI, npc_azure_raider::npc_azure_raiderAI, npc_azure_stalker::npc_azure_stalkerAI, npc_azure_spellbreaker::npc_azure_spellbreakerAI, npc_azure_captain::npc_azure_captainAI, npc_azure_sorceror::npc_azure_sorcerorAI, npc_azure_saboteur::npc_azure_saboteurAI, npc_violet_hold_defense_system, npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI, npc_lurgglbr::npc_lurgglbrAI, npc_beryl_sorcerer::npc_beryl_sorcererAI, npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI, npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI, npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI, npc_hidden_cultist::npc_hidden_cultistAI, npc_bloodmage_laurith::npc_bloodmage_laurithAI, npc_thassarian::npc_thassarianAI, npc_thassarian2::npc_thassarian2AI, npc_counselor_talbot::npc_counselor_talbotAI, npc_preparations_for_war_vehicle, npc_shandy_dalaran::npc_shandy_dalaranAI, npc_archmage_landalock::npc_archmage_landalockAI, npc_minigob_manabonk, npc_dalaran_mage::npc_dalaran_mageAI, npc_dalaran_warrior::npc_dalaran_warriorAI, npc_cosmetic_toy_plane, npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI, npc_hourglass_of_eternity::npc_hourglass_of_eternityAI, npc_wintergarde_gryphon, npc_q24545_lich_king::npc_q24545_lich_kingAI, npc_q24545_vegard::npc_q24545_vegardAI, npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI, npc_torturer_lecraft::npc_torturer_lecraftAI, npc_ravenous_worg::npc_ravenous_worgAI, npc_amberpine_woodsman::npc_amberpine_woodsmanAI, npc_wounded_skirmisher, npc_venture_co_straggler::npc_venture_co_stragglerAI, npc_lake_frog::npc_lake_frogAI, npc_your_inner_turmoil::npc_your_inner_turmoilAI, npc_battle_at_valhalas::npc_battle_at_valhalasAI, npc_llod_generic::npc_llod_genericAI, npc_lord_arete::npc_lord_areteAI, npc_boneguard_footman::npc_boneguard_footmanAI, npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI, npc_tournament_training_dummy::npc_tournament_training_dummyAI, npc_blessed_banner::npc_blessed_bannerAI, npc_frostbrood_skytalon::npc_frostbrood_skytalonAI, npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI, npc_still_at_it_trigger::npc_still_at_it_triggerAI, npc_jungle_punch_target::npc_jungle_punch_targetAI, npc_frosthound::npc_frosthoundAI, npc_iron_watcher::npc_iron_watcherAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_freed_protodrake::npc_freed_protodrakeAI, npc_icefang::npc_icefangAI, npc_hyldsmeet_protodrake::npc_hyldsmeet_protodrakeAI, npc_wg_queue::npc_wg_queueAI, npc_wg_siege_machine::npc_wg_siege_machineAI, npc_feedin_da_goolz::npc_feedin_da_goolzAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, npc_drakuru_shackles::npc_drakuru_shacklesAI, npc_crusade_recruit::npc_crusade_recruitAI, boss_exarch_maladaar, npc_stolen_soul, boss_shirrak_the_dead_watcher, boss_nexusprince_shaffar, npc_yor, boss_anzu, npc_anzu_spirit, boss_ambassador_hellmaw, boss_blackheart_the_inciter, npc_voidtraveler, npc_akama_illidan, npc_maiev_illidan, npc_parasitic_shadowfiend, npc_flame_of_azzinoth, boss_illidari_council, boss_gathios_the_shatterer, boss_high_nethermancer_zerevor, boss_lady_malande, boss_veras_darkshadow, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, boss_essence_of_desire::boss_essence_of_desireAI, boss_essence_of_anger::boss_essence_of_angerAI, boss_shade_of_akama, npc_akama_shade, npc_creature_generator_akama, npc_ashtongue_channeler, npc_supremus_punch_invisible_stalker, boss_teron_gorefiend, boss_doomlord_kazzak::boss_doomlordkazzakAI, boss_doomwalker, boss_fathomguard_sharkkis, boss_fathomguard_tidalvess, boss_fathomguard_caribdis, boss_lady_vashj, boss_leotheras_the_blind, npc_inner_demon, boss_the_lurker_below, npc_rancid_mushroom, npc_frozen_core, npc_ahune_bunny, npc_earthen_ring_flamecaller, npc_ahune_ice_spear_bunny, boss_ghazan, boss_hungarfen, npc_underbog_mushroom, boss_the_black_stalker, npc_underbat, boss_gruul, boss_high_king_maulgar, boss_olm_the_summoner, boss_kiggler_the_crazed, boss_blindeye_the_seer, boss_krosh_firehand, boss_the_maker, boss_omor_the_unscarred, boss_nazan, boss_vazruden, boss_watchkeeper_gargolmar, boss_magtheridon, npc_target_trigger, boss_grand_warlock_nethekurse, npc_shattered_hand_scout, boss_warbringer_omrogg, boss_warchief_kargath_bladefist, npc_warchief_portal, npc_millhouse_manastorm::npc_millhouse_manastormAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_wrath_scryer_soccothrates, boss_alar, boss_high_astromancer_solarian, boss_kaelthas, advisor_baseAI, npc_raging_flames, npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI, npc_nether_drake::npc_nether_drakeAI, npc_simon_bunny::npc_simon_bunnyAI, npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI, npc_aeranas::npc_aeranasAI, npc_fel_guard_hound::npc_fel_guard_houndAI, npc_magister_aledis, npc_maghar_captive::npc_maghar_captiveAI, npc_captain_saeed::npc_captain_saeedAI, npc_commander_dawnforge::npc_commander_dawnforgeAI, npc_invis_infernal_caster::npc_invis_infernal_casterAI, npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI, npc_enslaved_netherwing_drake, npc_dragonmaw_peon::npc_dragonmaw_peonAI, npc_torloth_the_magnificent::npc_torloth_the_magnificentAI, npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, npc_illidari_spawn::npc_illidari_spawnAI, npc_enraged_spirit::npc_enraged_spiritAI, npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI, dragonmaw_race_npc, npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI, npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI, npc_pet_gen_soul_trader_beacon, npc_pet_gen_argent_pony_bridle, npc_pet_gen_target_following_bomb, npc_pet_gen_valkyr_guardian, npc_pet_gen_imp_in_a_bottle, npc_pet_gen_wind_rider_cub, npc_pet_gen_plump_turkey, npc_pet_gen_toxic_wasteling, npc_pet_gen_fetch_ball, npc_pet_darting_hatchling, npc_pet_hunter_snake_trap, npc_pet_mage_mirror_image, npc_pet_shaman_earth_elemental, npc_pet_shaman_fire_elemental, emerald_dragonAI, npc_dream_fog::npc_dream_fogAI, boss_taerar::boss_taerarAI, guard_shattrath_scryer::guard_shattrath_scryerAI, guard_shattrath_aldor::guard_shattrath_aldorAI, trigger_periodic::trigger_periodicAI, npc_artorius::npc_artoriusAI, npc_simone::npc_simoneAI, npc_nelson::npc_nelsonAI, npc_franklin::npc_franklinAI, npc_elder_clearwater::npc_elder_clearwaterAI, npc_riggle_bassbait::npc_riggle_bassbaitAI, npc_training_dummy::npc_training_dummyAI, npc_target_dummy::npc_target_dummyAI, npc_chicken_cluck::npc_chicken_cluckAI, npc_dancing_flames::npc_dancing_flamesAI, npc_doctor::npc_doctorAI, npc_injured_patient::npc_injured_patientAI, npc_garments_of_quests::npc_garments_of_questsAI, npc_spring_rabbit::npc_spring_rabbitAI, npc_arcanite_dragonling, npc_crashin_thrashin_robot, npc_koltira_deathweaver::npc_koltira_deathweaverAI, npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI, npc_tyrion_spybot::npc_tyrion_spybotAI, npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI, boss_ichoron::boss_ichoronAI, npc_ichor_globule::npc_ichor_globuleAI, npc_warmage_coldarra::npc_warmage_coldarraAI, npc_engineer_helice::npc_engineer_heliceAI, npc_maxx_a_million_escort::npc_maxx_a_million_escortAI, AggressorAI, PassiveAI, PossessedAI, NullCreatureAI, CritterAI, PetAI, FollowerAI, npc_demonic_vapor, npc_greengill_slave::npc_greengill_slaveAI, npc_marzon_silent_blade::npc_marzon_silent_bladeAI, npc_zuljin_vortex, npc_zulaman_hostage::npc_zulaman_hostageAI, npc_batrider, npc_chained_spirit, npc_buru_egg, npc_injured_draenei::npc_injured_draeneiAI, npc_orb_carrier::npc_orb_carrierAI, npc_announcer_toc5::npc_announcer_toc5AI, npc_concentrated_ball::npc_concentrated_ballAI, npc_hor_raging_ghoul::npc_hor_raging_ghoulAI, npc_gunship::npc_gunshipAI, npc_gunship_rocketeer::npc_gunship_rocketeerAI, npc_suppresser::npc_suppresserAI, npc_gothik_trigger::npc_gothik_triggerAI, boss_maexxna_webwrap::boss_maexxna_webwrapAI, npc_tesla::npc_teslaAI, npc_centrifuge_construct::npc_centrifuge_constructAI, npc_spark_of_ionar::npc_spark_of_ionarAI, boss_sjonnir_dwarf::boss_sjonnir_dwarfAI, npc_assembly_lightning::npc_assembly_lightningAI, boss_kologarn_arms::boss_kologarn_armsAI, npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI, npc_xt002_scrapbot::npc_xt002_scrapbotAI, npc_xt002_boombot::npc_xt002_boombotAI, npc_xt002_life_spark::npc_xt002_life_sparkAI, boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI, boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI, npc_frost_tomb, npc_warmage_violetstand, npc_mageguard_dalaran::npc_mageguard_dalaranAI, npc_future_you::npc_future_youAI, npc_q24545_vegard_dummy::npc_q24545_vegard_dummyAI, npc_mrfloppy::npc_mrfloppyAI, npc_tallhorn_stag::npc_tallhorn_stagAI, npc_bushwhacker::npc_bushwhackerAI, npc_brunnhildar_prisoner::npc_brunnhildar_prisonerAI, npc_wg_spirit_guide::npc_wg_spirit_guideAI, outdoorpvp_na_halaa_creatures, boss_vazruden_the_herald, npc_deaths_fel_cannon::npc_deaths_fel_cannonAI, npc_infernal_attacker::npc_infernal_attackerAI, npc_pet_gen_gnomish_flame_turret, npc_precious::npc_preciousAI, and npc_guardian::npc_guardianAI.
Referenced by Creature::Update(), and npc_gunship_mage::npc_gunship_mageAI::UpdateAI().
Member Data Documentation
AISpellInfo
AISpellInfoType * UnitAI::AISpellInfo static
Referenced by DoCast(), FillAISpellInfo(), GetAISpellInfo(), CasterAI::InitializeAI(), CombatAI::JustDied(), CasterAI::JustEngagedWith(), CombatAI::JustEngagedWith(), and CombatAI::UpdateAI().
me
Unit* const UnitAI::me protected
Referenced by AttackStart(), AttackStartCaster(), DoAddAuraToAllHostilePlayers(), DoCast(), DoCastAOE(), DoCastSelf(), DoCastToAllHostilePlayers(), DoCastVictim(), DoMeleeAttackIfReady(), DoSpellAttackIfReady(), DoSpellAttackToRandomTargetIfReady(), GetDebugInfo(), GetThreatMgr(), InitializeAI(), boss_jeklik::Reset(), SelectTarget(), SelectTargetList(), and SortByDistance().