AzerothCore: achievement_cant_do_that_while_stunned Class Reference
achievement_cant_do_that_while_stunned Class Reference
Public Member Functions
achievement_cant_do_that_while_stunned ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
virtual bool OnCheck (Player *, Unit *, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_cant_do_that_while_stunned()
achievement_cant_do_that_while_stunned::achievement_cant_do_that_while_stunned () inline
: AchievementCriteriaScript("achievement_cant_do_that_while_stunned") {}
Member Function Documentation
OnCheck()
bool achievement_cant_do_that_while_stunned::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
    {
        bool allow = target && target->GetAuraCount(SPELL_SUPERCHARGE) >= 2;
        if (!allow)
            return false;
        if (InstanceScript* instance = target->GetInstanceScript())
            if (Creature* cr = ObjectAccessor::GetCreature(*target, instance->GetGuidData(DATA_BRUNDIR)))
                return cr->AI()->GetData(DATA_BRUNDIR);
        return false;
    }
References DATA_BRUNDIR, Unit::GetAuraCount(), ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), and SPELL_SUPERCHARGE.