AzerothCore: boss_svala::boss_svalaAI Struct Reference
boss_svala::boss_svalaAI Struct Reference
Public Member Functions
boss_svalaAI (Creature *creature)
void Reset () override
void EnterEvadeMode (EvadeReason why) override
void SetData (uint32 data, uint32 param) override
void JustSummoned (Creature *summon) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
ObjectGuid ArthasGUID
bool Started
InstanceScript * instance
EventMap events
EventMap events2
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_svalaAI()
boss_svala::boss_svalaAI::boss_svalaAI (Creature * creature) inline
                                         : ScriptedAI(creature), summons(me)
        {
            instance = creature->GetInstanceScript();
            Started = false;
            ArthasGUID.Clear();
        }
References ArthasGUID, ObjectGuid::Clear(), WorldObject::GetInstanceScript(), instance, and Started.
Member Function Documentation
EnterEvadeMode()
void boss_svala::boss_svalaAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            me->SetControlled(false, UNIT_STATE_ROOT);
            ScriptedAI::EnterEvadeMode(why);
        }
References CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
JustDied()
void boss_svala::boss_svalaAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.DespawnAll();
            Talk(SAY_DEATH);
            if (instance)
                instance->SetData(DATA_SVALA_SORROWGRAVE, DONE);
        }
References DATA_SVALA_SORROWGRAVE, SummonList::DespawnAll(), DONE, instance, SAY_DEATH, ZoneScript::SetData(), and summons.
JustEngagedWith()
void boss_svala::boss_svalaAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            me->SetInCombatWithZone();
            Talk(SAY_AGGRO);
            events.ScheduleEvent(EVENT_SORROWGRAVE_SS, 3s);
            events.ScheduleEvent(EVENT_SORROWGRAVE_FLAMES, 11s);
            events.ScheduleEvent(EVENT_SORROWGRAVE_RITUAL, 25s);
            if (instance)
                instance->SetData(DATA_SVALA_SORROWGRAVE, IN_PROGRESS);
        }
References DATA_SVALA_SORROWGRAVE, EVENT_SORROWGRAVE_FLAMES, EVENT_SORROWGRAVE_RITUAL, EVENT_SORROWGRAVE_SS, IN_PROGRESS, instance, ScriptedAI::me, SAY_AGGRO, ZoneScript::SetData(), and Creature::SetInCombatWithZone().
JustSummoned()
void boss_svala::boss_svalaAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(summon);
            if (summon->GetEntry() == NPC_RITUAL_CHANNELER)
                summon->CastSpell(summon, SPELL_TELEPORT_VISUAL, true);
        }
References Unit::CastSpell(), Object::GetEntry(), NPC_RITUAL_CHANNELER, SPELL_TELEPORT_VISUAL, SummonList::Summon(), and summons.
KilledUnit()
void boss_svala::boss_svalaAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->GetEntry() == NPC_SCOURGE_HULK && instance)
            {
                instance->SetData(DATA_SVALA_ACHIEVEMENT, true);
                instance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, 26555, 1, nullptr);
            }
            if (victim->IsPlayer())
                Talk(SAY_SLAY);
        }
References ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, DATA_SVALA_ACHIEVEMENT, InstanceScript::DoUpdateAchievementCriteria(), Object::GetEntry(), instance, Object::IsPlayer(), NPC_SCOURGE_HULK, SAY_SLAY, and ZoneScript::SetData().
Reset()
void boss_svala::boss_svalaAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            if (instance)
            {
                instance->SetData(DATA_SVALA_SORROWGRAVE, NOT_STARTED);
                instance->SetData(DATA_SVALA_ACHIEVEMENT, false);
            }
            summons.DespawnAll();
            events.Reset();
            events2.Reset();
            if (!Started)
                me->SetImmuneToAll(true);
            else
            {
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->SetImmuneToAll(false);
                me->SetHover(true);
            }
        }
References DATA_SVALA_ACHIEVEMENT, DATA_SVALA_SORROWGRAVE, SummonList::DespawnAll(), events2, instance, ScriptedAI::me, NOT_STARTED, Unit::RemoveUnitFlag(), EventMap::Reset(), ZoneScript::SetData(), Creature::SetHover(), Unit::SetImmuneToAll(), Started, summons, and UNIT_FLAG_NON_ATTACKABLE.
SetData()
void boss_svala::boss_svalaAI::SetData (uint32 data, uint32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (data != 1 || param != 1 || Started || (instance && instance->GetData(DATA_SVALA_SORROWGRAVE) == DONE))
                return;
            me->SetImmuneToAll(true);
            Started = true;
            me->setActive(true);
            events2.ScheduleEvent(EVENT_SVALA_START, 5000);
            if (Creature* pArthas = me->SummonCreature(NPC_ARTHAS, 295.81f, -366.16f, 92.57f, 1.58f, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 59000))
                ArthasGUID = pArthas->GetGUID();
            if (instance)
            {
                instance->SetData(DATA_SVALA_SORROWGRAVE, IN_PROGRESS);
                if (GameObject* mirror = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_SVALA_MIRROR)))
                    mirror->SetGoState(GO_STATE_READY);
            }
        }
References ArthasGUID, DATA_SVALA_SORROWGRAVE, DONE, EVENT_SVALA_START, events2, ZoneScript::GetData(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_STATE_READY, GO_SVALA_MIRROR, IN_PROGRESS, instance, ScriptedAI::me, NPC_ARTHAS, EventMap::ScheduleEvent(), WorldObject::setActive(), ZoneScript::SetData(), Unit::SetImmuneToAll(), Started, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN.
UpdateAI()
void boss_svala::boss_svalaAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            events2.Update(diff);
            switch (events2.ExecuteEvent())
            {
                case EVENT_SVALA_START:
                    Talk(TALK_INTRO_S1);
                    events2.ScheduleEvent(EVENT_SVALA_TALK1, 8s);
                    break;
                case EVENT_SVALA_TALK1:
                    if (Creature* Arthas = ObjectAccessor::GetCreature(*me, ArthasGUID))
                        Arthas->AI()->Talk(TALK_INTRO_A1);
                    events2.ScheduleEvent(EVENT_SVALA_TALK2, 9s);
                    break;
                case EVENT_SVALA_TALK2:
                    if (Creature* Arthas = ObjectAccessor::GetCreature(*me, ArthasGUID))
                        Arthas->CastSpell(me, SPELL_ARTHAS_TRANSFORMING_SVALA, false);
                    me->CastSpell(me, SPELL_SVALA_TRANSFORMING2, true);
                    events2.ScheduleEvent(EVENT_SVALA_TALK3, 3s);
                    break;
                case EVENT_SVALA_TALK3:
                    me->SetFloatValue(UNIT_FIELD_HOVERHEIGHT, 6.0f);
                    me->SetHover(true);
                    me->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
                    events2.ScheduleEvent(30, 1s);
                    events2.ScheduleEvent(EVENT_SVALA_TALK4, 9s);
                    break;
                case 30:
                    {
                        WorldPacket data(SMSG_SPLINE_MOVE_SET_HOVER, 9);
                        data << me->GetPackGUID();
                        me->SendMessageToSet(&data, false);
                        break;
                    }
                case EVENT_SVALA_TALK4:
                    {
                        me->CastSpell(me, SPELL_SVALA_TRANSFORMING1, true);
                        me->UpdateEntry(NPC_SVALA_SORROWGRAVE);
                        me->SetCorpseDelay(sWorld->getIntConfig(CONFIG_CORPSE_DECAY_ELITE));
                        me->SetFloatValue(UNIT_FIELD_HOVERHEIGHT, 6.0f);
                        me->SetImmuneToAll(true);
                        if (Creature* Arthas = ObjectAccessor::GetCreature(*me, ArthasGUID))
                            Arthas->InterruptNonMeleeSpells(false);
                        me->RemoveAllAuras();
                        me->SetWalk(false);
                        events2.ScheduleEvent(EVENT_SVALA_TALK5, 2s);
                        std::list<Creature*> creatureList;
                        me->GetCreaturesWithEntryInRange(creatureList, 100.0f, NPC_DRAGONFLAYER_SPECTATOR);
                        for (std::list<Creature*>::const_iterator itr = creatureList.begin(); itr != creatureList.end(); ++itr)
                            (*itr)->AI()->SetData(1, 2);
                        break;
                    }
                case EVENT_SVALA_TALK5:
                    Talk(TALK_INTRO_S2);
                    events2.ScheduleEvent(EVENT_SVALA_TALK6, 12s);
                    break;
                case EVENT_SVALA_TALK6:
                    if (Creature* Arthas = ObjectAccessor::GetCreature(*me, ArthasGUID))
                        Arthas->AI()->Talk(TALK_INTRO_A2);
                    events2.ScheduleEvent(EVENT_SVALA_TALK7, 9s);
                    break;
                case EVENT_SVALA_TALK7:
                    me->SetFacingTo(M_PI / 2.0f);
                    Talk(TALK_INTRO_S3);
                    if (GameObject* mirror = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_SVALA_MIRROR)))
                        mirror->SetGoState(GO_STATE_ACTIVE);
                    events2.ScheduleEvent(EVENT_SVALA_TALK8, 13s);
                    break;
                case EVENT_SVALA_TALK8:
                    me->GetMotionMaster()->MoveFall(0, true);
                    events2.ScheduleEvent(EVENT_SVALA_TALK9, 2s);
                    break;
                case EVENT_SVALA_TALK9:
                    me->SetFloatValue(UNIT_FIELD_HOVERHEIGHT, 3.0f);
                    me->SetImmuneToAll(false);
                    me->LoadEquipment(1, true);
                    me->setActive(false);
                    if (Player* target = SelectTargetFromPlayerList(100.0f))
                        AttackStart(target);
                    return;
            }
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_SORROWGRAVE_SS:
                    me->CastSpell(me->GetVictim(), IsHeroic() ? SPELL_SINSTER_STRIKE_H : SPELL_SINSTER_STRIKE_N, false);
                    events.ScheduleEvent(EVENT_SORROWGRAVE_SS, 3s, 5s);
                    break;
                case EVENT_SORROWGRAVE_FLAMES:
                    summons.DespawnAll();
                    me->CastSpell(me, SPELL_CALL_FLAMES, false);
                    events.ScheduleEvent(EVENT_SORROWGRAVE_FLAMES2, 500ms);
                    events.ScheduleEvent(EVENT_SORROWGRAVE_FLAMES2, 1s);
                    events.ScheduleEvent(EVENT_SORROWGRAVE_FLAMES, 8s, 12s);
                    break;
                case EVENT_SORROWGRAVE_FLAMES2:
                    {
                        std::list<Creature*> braziers;
                        me->GetCreaturesWithEntryInRange(braziers, 100.0f, NPC_FLAME_BRAZIER);
                        if (!braziers.empty())
{
                            for (std::list<Creature*>::const_iterator itr = braziers.begin(); itr != braziers.end(); ++itr)
                                (*itr)->CastCustomSpell(SPELL_BALL_OF_FLAME, SPELLVALUE_MAX_TARGETS, 1, (*itr), true);
                        }
                        break;
                    }
                case EVENT_SORROWGRAVE_RITUAL:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true))
                    {
                        Talk(SAY_SACRIFICE_PLAYER);
                        for (uint8 i = 0; i < 3; ++i)
                            if (Creature* cr = me->SummonCreature(NPC_RITUAL_CHANNELER, RitualChannelerLoc[i], TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 360000))
                                cr->AI()->AttackStart(target);
                        me->GetMotionMaster()->MoveIdle();
                        DoTeleportPlayer(target, 296.632f, -346.075f, 90.63f, 4.6f);
                        me->NearTeleportTo(296.632f, -346.075f, 110.0f, 4.6f, false);
                        me->SetControlled(true, UNIT_STATE_ROOT);
                        me->RemoveAurasByType(SPELL_AURA_PERIODIC_DAMAGE);
                        me->RemoveAurasByType(SPELL_AURA_PERIODIC_DAMAGE_PERCENT);
                        me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    }
                    events.DelayEvents(25001); // +1 just to be sure
                    events.ScheduleEvent(EVENT_SORROWGRAVE_RITUAL_SPELLS, 0ms);
                    events.ScheduleEvent(EVENT_SORROWGRAVE_FINISH_RITUAL, 25s);
                    return;
                case EVENT_SORROWGRAVE_RITUAL_SPELLS:
                    //me->CastSpell(me, SPELL_RITUAL_OF_THE_SWORD, false);
                    me->CastSpell(me, SPELL_RITUAL_STRIKE, true);
                    return;
                case EVENT_SORROWGRAVE_FINISH_RITUAL:
                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    me->SetControlled(false, UNIT_STATE_ROOT);
                    AttackStart(me->GetVictim());
                    me->GetMotionMaster()->MoveFall(0, true);
                    summons.DespawnAll();
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::AddUnitState(), ArthasGUID, ScriptedAI::AttackStart(), Unit::CastSpell(), CONFIG_CORPSE_DECAY_ELITE, SummonList::DespawnAll(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoTeleportPlayer(), EVENT_SORROWGRAVE_FINISH_RITUAL, EVENT_SORROWGRAVE_FLAMES, EVENT_SORROWGRAVE_FLAMES2, EVENT_SORROWGRAVE_RITUAL, EVENT_SORROWGRAVE_RITUAL_SPELLS, EVENT_SORROWGRAVE_SS, EVENT_SVALA_START, EVENT_SVALA_TALK1, EVENT_SVALA_TALK2, EVENT_SVALA_TALK3, EVENT_SVALA_TALK4, EVENT_SVALA_TALK5, EVENT_SVALA_TALK6, EVENT_SVALA_TALK7, EVENT_SVALA_TALK8, EVENT_SVALA_TALK9, events2, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), WorldObject::GetCreaturesWithEntryInRange(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Object::GetPackGUID(), Unit::GetVictim(), GO_STATE_ACTIVE, GO_SVALA_MIRROR, Unit::HasUnitState(), instance, ScriptedAI::IsHeroic(), Creature::LoadEquipment(), ScriptedAI::me, MotionMaster::MoveFall(), MotionMaster::MoveIdle(), Unit::NearTeleportTo(), NPC_DRAGONFLAYER_SPECTATOR, NPC_FLAME_BRAZIER, NPC_RITUAL_CHANNELER, NPC_SVALA_SORROWGRAVE, Unit::RemoveAllAuras(), Unit::RemoveAurasByType(), Unit::RemoveUnitFlag(), RitualChannelerLoc, SAY_SACRIFICE_PLAYER, EventMap::ScheduleEvent(), UnitAI::SelectTarget(), ScriptedAI::SelectTargetFromPlayerList(), WorldObject::SendMessageToSet(), WorldObject::setActive(), Unit::SetControlled(), Creature::SetCorpseDelay(), Unit::SetFacingTo(), Object::SetFloatValue(), Creature::SetHover(), Unit::SetImmuneToAll(), Unit::SetUnitFlag(), Creature::SetWalk(), SMSG_SPLINE_MOVE_SET_HOVER, SPELL_ARTHAS_TRANSFORMING_SVALA, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_DAMAGE_PERCENT, SPELL_BALL_OF_FLAME, SPELL_CALL_FLAMES, SPELL_RITUAL_STRIKE, SPELL_SINSTER_STRIKE_H, SPELL_SINSTER_STRIKE_N, SPELL_SVALA_TRANSFORMING1, SPELL_SVALA_TRANSFORMING2, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), summons, sWorld, TALK_INTRO_A1, TALK_INTRO_A2, TALK_INTRO_S1, TALK_INTRO_S2, TALK_INTRO_S3, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, UNIT_FIELD_HOVERHEIGHT, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, UNIT_STATE_NO_ENVIRONMENT_UPD, UNIT_STATE_ROOT, EventMap::Update(), Creature::UpdateEntry(), and CreatureAI::UpdateVictim().
Member Data Documentation
ArthasGUID
ObjectGuid boss_svala::boss_svalaAI::ArthasGUID
Referenced by boss_svalaAI(), SetData(), and UpdateAI().
events
EventMap boss_svala::boss_svalaAI::events
events2
EventMap boss_svala::boss_svalaAI::events2
Referenced by Reset(), SetData(), and UpdateAI().
instance
InstanceScript* boss_svala::boss_svalaAI::instance
Referenced by boss_svalaAI(), JustDied(), JustEngagedWith(), KilledUnit(), Reset(), SetData(), and UpdateAI().
Started
bool boss_svala::boss_svalaAI::Started
Referenced by boss_svalaAI(), Reset(), and SetData().
summons
SummonList boss_svala::boss_svalaAI::summons
Referenced by JustDied(), JustSummoned(), Reset(), and UpdateAI().