AzerothCore: spell_class_call_handler Class Reference
spell_class_call_handler Class Reference
Private Member Functions
PrepareSpellScript (spell_class_call_handler)
bool Validate (SpellInfo const *) override
void FilterTargets (std::list< WorldObject * > &targets)
void HandleOnHitRogue (SpellEffIndex)
void HandleOnHitWarlock ()
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
FilterTargets()
void spell_class_call_handler::FilterTargets (std::list< WorldObject * > & targets) inline private
    {
        if (SpellInfo const* spellInfo = GetSpellInfo())
        {
            targets.remove_if([spellInfo](WorldObject const* target) -> bool
            {
                Player const* player = target->ToPlayer();
                if (!player || player->IsClass(CLASS_DEATH_KNIGHT)) // ignore all death knights from whatever spell, for some reason the condition below is not working x.x
                {
                    return true;
                }
                auto it = classCallSpells.find(spellInfo->Id);
                if (it != classCallSpells.end()) // should never happen but only to be sure.
                {
                    return target->ToPlayer()->getClass() != it->second;
                }
                return false;
            });
        }
    }
References CLASS_DEATH_KNIGHT, classCallSpells, SpellScript::GetSpellInfo(), Player::IsClass(), and Object::ToPlayer().
Referenced by Register().
HandleOnHitRogue()
void spell_class_call_handler::HandleOnHitRogue (SpellEffIndex) inline private
    {
        Unit* caster = GetCaster();
        Unit* target = GetHitUnit();
        if (!caster || !target)
        {
            return;
        }
        Position tp = caster->GetFirstCollisionPosition(5.f, 0.f);
        target->NearTeleportTo(tp.GetPositionX(), tp.GetPositionY(), tp.GetPositionZ(), tp.GetOrientation());
    }
References SpellScript::GetCaster(), WorldObject::GetFirstCollisionPosition(), SpellScript::GetHitUnit(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), and Unit::NearTeleportTo().
Referenced by Register().
HandleOnHitWarlock()
void spell_class_call_handler::HandleOnHitWarlock () inline private
    {
        if (Unit* target = GetHitUnit())
        {
            target->CastSpell(target, SPELL_SUMMON_INFERNALS, true);
        }
    }
References SpellScript::GetHitUnit(), and SPELL_SUMMON_INFERNALS.
Referenced by Register().
PrepareSpellScript()
spell_class_call_handler::PrepareSpellScript (spell_class_call_handler) private
Register()
void spell_class_call_handler::Register () inline override private virtual
Implements _SpellScript.
    {
        OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_class_call_handler::FilterTargets, EFFECT_ALL, TARGET_UNIT_SRC_AREA_ENEMY);
        if (m_scriptSpellId == SPELL_ROGUE)
        {
            OnEffectLaunchTarget += SpellEffectFn(spell_class_call_handler::HandleOnHitRogue, EFFECT_0, SPELL_EFFECT_APPLY_AURA);
        }
        else if (m_scriptSpellId == SPELL_WARLOCK)
        {
            OnHit += SpellHitFn(spell_class_call_handler::HandleOnHitWarlock);
        }
    }
References EFFECT_0, EFFECT_ALL, FilterTargets(), HandleOnHitRogue(), HandleOnHitWarlock(), _SpellScript::m_scriptSpellId, SpellScript::OnEffectLaunchTarget, SpellScript::OnHit, SpellScript::OnObjectAreaTargetSelect, SPELL_EFFECT_APPLY_AURA, SPELL_ROGUE, SPELL_WARLOCK, SpellEffectFn, SpellHitFn, SpellObjectAreaTargetSelectFn, and TARGET_UNIT_SRC_AREA_ENEMY.
Validate()
bool spell_class_call_handler::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo({ SPELL_SUMMON_INFERNALS });
    }
References SPELL_SUMMON_INFERNALS, and _SpellScript::ValidateSpellInfo().