AzerothCore: PetAura Class Reference
PetAura Class Reference
#include "SpellMgr.h"
Public Member Functions
PetAura ()
PetAura (uint32 petEntry, uint32 aura, bool _removeOnChangePet, int _damage)
uint32 GetAura (uint32 petEntry) const
void AddAura (uint32 petEntry, uint32 aura)
bool IsRemovedOnChangePet () const
int32 GetDamage () const
Private Types
typedef std::unordered_map< uint32, uint32 > PetAuraMap
Private Attributes
PetAuraMap auras
bool removeOnChangePet {false}
int32 damage {0}
Detailed Description
Member Typedef Documentation
PetAuraMap
typedef std::unordered_map<uint32, uint32> PetAura::PetAuraMap private
Constructor & Destructor Documentation
PetAura() [1/2]
PetAura::PetAura () inline
    {
        auras.clear();
    }
References auras.
PetAura() [2/2]
PetAura::PetAura (uint32 petEntry, uint32 aura, bool _removeOnChangePet, int _damage) inline
                                                                                :
        removeOnChangePet(_removeOnChangePet), damage(_damage)
    {
        auras[petEntry] = aura;
    }
References auras.
Member Function Documentation
AddAura()
void PetAura::AddAura (uint32 petEntry, uint32 aura) inline
    {
        auras[petEntry] = aura;
    }
References auras.
GetAura()
uint32 PetAura::GetAura (uint32 petEntry) const inline
    {
        PetAuraMap::const_iterator itr = auras.find(petEntry);
        if (itr != auras.end())
            return itr->second;
        PetAuraMap::const_iterator itr2 = auras.find(0);
        if (itr2 != auras.end())
            return itr2->second;
        return 0;
    }
References auras.
Referenced by Unit::CastPetAura(), Unit::IsPetAura(), and Unit::RemovePetAura().
GetDamage()
int32 PetAura::GetDamage () const inline
    {
        return damage;
    }
References damage.
Referenced by Unit::CastPetAura().
IsRemovedOnChangePet()
bool PetAura::IsRemovedOnChangePet () const inline
    {
        return removeOnChangePet;
    }
References removeOnChangePet.
Referenced by Pet::CastPetAuras().
Member Data Documentation
auras
PetAuraMap PetAura::auras private
Referenced by AddAura(), GetAura(), and PetAura().
damage
int32 PetAura::damage {0} private
Referenced by GetDamage().
removeOnChangePet
bool PetAura::removeOnChangePet {false} private
Referenced by IsRemovedOnChangePet().