AzeorthCore: npc_sentinel_infiltrator Struct Reference
npc_sentinel_infiltrator Struct Reference
Public Member Functions
npc_sentinel_infiltrator (Creature *creature)
void Initialize ()
void Reset () override
void MovementInform (uint32 type, uint32 id) override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
bool _fleedForAssistance
int32 _path
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_sentinel_infiltrator()
npc_sentinel_infiltrator::npc_sentinel_infiltrator (Creature * creature) inline
                                                 : ScriptedAI(creature)
    {
        Initialize();
    }
References Initialize().
Member Function Documentation
EnterCombat()
void npc_sentinel_infiltrator::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        _events.ScheduleEvent(EVENT_GOUGE2, urand(9000, 15000));
        _events.ScheduleEvent(EVENT_BACKSTAB2, urand(3000, 5000));
    }
References _events, EVENT_BACKSTAB2, EVENT_GOUGE2, EventMap::ScheduleEvent(), and urand().
Initialize()
void npc_sentinel_infiltrator::Initialize () inline
    {
        _path = me->GetWaypointPath();
    }
References _path, Creature::GetWaypointPath(), and ScriptedAI::me.
Referenced by npc_sentinel_infiltrator().
MovementInform()
void npc_sentinel_infiltrator::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type == WAYPOINT_MOTION_TYPE)
        {
            switch (_path)
            {
            case PATH_ONE:
                switch (id)
                {
                    case 5:
                    case 8:
                    case 14:
                    case 18:
                        Creature* SentinelInfiltrator = me->FindNearestCreature(NPC_SENTINEL_INFILTRATOR, 3.5f, true);
                        if (SentinelInfiltrator)
{
                            me->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                            SentinelInfiltrator->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                            _events.ScheduleEvent(EVENT_TALK2, 2000);
                        }
                        break;
                }
                break;
            case PATH_TWO:
                switch (id)
                {
                    case 5:
                    case 7:
                    case 14:
                    case 17:
                        Creature* SentinelInfiltrator = me->FindNearestCreature(NPC_SENTINEL_INFILTRATOR, 3.5f, true);
                        if (SentinelInfiltrator)
{
                            me->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                            SentinelInfiltrator->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                            _events.ScheduleEvent(EVENT_TALK, 2000);
                        }
                        break;
                }
                break;
            }
        }
    }
References _events, _path, EMOTE_ONESHOT_SALUTE, EVENT_TALK, EVENT_TALK2, WorldObject::FindNearestCreature(), Unit::HandleEmoteCommand(), ScriptedAI::me, NPC_SENTINEL_INFILTRATOR, PATH_ONE, PATH_TWO, EventMap::ScheduleEvent(), and WAYPOINT_MOTION_TYPE.
Reset()
void npc_sentinel_infiltrator::Reset () inline override virtual
Reimplemented from ScriptedAI.
    {
        _fleedForAssistance = false;
    }
References _fleedForAssistance.
UpdateAI()
void npc_sentinel_infiltrator::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
    {
        _events.Update(diff);
        if (!UpdateVictim())
        {
            while (uint32 eventId = _events.ExecuteEvent())
            {
                switch (eventId)
                {
                case EVENT_TALK2:
                {
                    Creature* SentinelInfiltrator = me->FindNearestCreature(NPC_SENTINEL_INFILTRATOR, 3.5f, true);
                    if (SentinelInfiltrator)
                    {
                        SentinelInfiltrator->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                    }
                    _events.ScheduleEvent(EVENT_QUESTION, 2000);
                    break;
                }
                case EVENT_QUESTION2:
                {
                    me->HandleEmoteCommand(EMOTE_ONESHOT_QUESTION);
                    _events.ScheduleEvent(EVENT_EXCLAMATION, 1000);
                    break;
                }
                case EVENT_EXCLAMATION:
                {
                    Creature* SentinelInfiltrator = me->FindNearestCreature(NPC_SENTINEL_INFILTRATOR, 3.5f, true);
                    if (SentinelInfiltrator)
                    {
                        SentinelInfiltrator->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);
                    }
                    _events.ScheduleEvent(EVENT_SALUTE, 3000);
                    break;
                }
                case EVENT_SALUTE:
                {
                    Creature* SentinelInfiltrator = me->FindNearestCreature(NPC_SENTINEL_INFILTRATOR, 3.5f, true);
                    if (SentinelInfiltrator)
                    {
                        me->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                        SentinelInfiltrator->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                        break;
                    }
                }
                default:
                    break;
                }
            }
            return;
        }
        while (uint32 eventId = _events.ExecuteEvent())
        {
            switch (eventId)
            {
            case EVENT_GOUGE2:
                DoCastVictim(SPELL_GOUGE, true);
                _events.ScheduleEvent(EVENT_GOUGE2, urand(9000, 15000));
                break;
            case EVENT_BACKSTAB2:
                DoCastVictim(SPELL_BACKSTAB, true);
                _events.ScheduleEvent(EVENT_BACKSTAB, urand(7000, 11000));
                break;
            default:
                break;
            }
        }
        if (me->HealthBelowPct(15) && !_fleedForAssistance)
        {
            _fleedForAssistance = true;
            me->DoFleeToGetAssistance();
            Talk(EMOTE_FLEE);
        }
        DoMeleeAttackIfReady();
    }
References _events, _fleedForAssistance, UnitAI::DoCastVictim(), Creature::DoFleeToGetAssistance(), UnitAI::DoMeleeAttackIfReady(), EMOTE_FLEE, EMOTE_ONESHOT_EXCLAMATION, EMOTE_ONESHOT_QUESTION, EMOTE_ONESHOT_SALUTE, EMOTE_ONESHOT_TALK, EVENT_BACKSTAB, EVENT_BACKSTAB2, EVENT_EXCLAMATION, EVENT_GOUGE2, EVENT_QUESTION, EVENT_QUESTION2, EVENT_SALUTE, EVENT_TALK2, EventMap::ExecuteEvent(), WorldObject::FindNearestCreature(), Unit::HandleEmoteCommand(), Unit::HealthBelowPct(), ScriptedAI::me, NPC_SENTINEL_INFILTRATOR, EventMap::ScheduleEvent(), SPELL_BACKSTAB, SPELL_GOUGE, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_events
EventMap npc_sentinel_infiltrator::_events private
Referenced by EnterCombat(), MovementInform(), and UpdateAI().
_fleedForAssistance
bool npc_sentinel_infiltrator::_fleedForAssistance private
Referenced by Reset(), and UpdateAI().
_path
int32 npc_sentinel_infiltrator::_path private
Referenced by Initialize(), and MovementInform().