AzerothCore: ObjectRegistry< T, Key > Class Template Reference
ObjectRegistry< T, Key > Class Template Reference final
#include "ObjectRegistry.h"
Public Types
typedef std::map< Key, std::unique_ptr< T > > RegistryMapType
Public Member Functions
T const * GetRegistryItem (Key const &key) const
Returns a registry item.
bool InsertItem (T *obj, Key const &key, bool force=false)
Inserts a registry item.
bool HasItem (Key const &key) const
Returns true if registry contains an item.
RegistryMapType const & GetRegisteredItems () const
Return the map of registered items.
Static Public Member Functions
static ObjectRegistry< T, Key > * instance ()
Private Member Functions
ObjectRegistry ()
~ObjectRegistry ()
Private Attributes
RegistryMapType _registeredObjects
Detailed Description
template<class T, class Key = std::string>
class ObjectRegistry< T, Key >
ObjectRegistry holds all registry item of the same type
Member Typedef Documentation
RegistryMapType
template<class T , class Key = std::string> typedef std::map<Key, std::unique_ptr<T> > ObjectRegistry< T, Key >::RegistryMapType
Constructor & Destructor Documentation
ObjectRegistry()
template<class T , class Key = std::string> ObjectRegistry< T, Key >::ObjectRegistry () inline private
{ }
~ObjectRegistry()
template<class T , class Key = std::string> ObjectRegistry< T, Key >::~ObjectRegistry () inline private
{ }
Member Function Documentation
GetRegisteredItems()
template<class T , class Key = std::string> RegistryMapType const & ObjectRegistry< T, Key >::GetRegisteredItems () const inline
Return the map of registered items.
    {
        return _registeredObjects;
    }
References ObjectRegistry< T, Key >::_registeredObjects.
GetRegistryItem()
template<class T , class Key = std::string> T const * ObjectRegistry< T, Key >::GetRegistryItem (Key const & key) const inline
Returns a registry item.
    {
        auto itr = _registeredObjects.find(key);
        if (itr == _registeredObjects.end())
            return nullptr;
        return itr->second.get();
    }
References ObjectRegistry< T, Key >::_registeredObjects.
Referenced by FactorySelector::SelectFactory().
HasItem()
template<class T , class Key = std::string> bool ObjectRegistry< T, Key >::HasItem (Key const & key) const inline
Returns true if registry contains an item.
    {
        return (_registeredObjects.count(key) > 0);
    }
References ObjectRegistry< T, Key >::_registeredObjects.
InsertItem()
template<class T , class Key = std::string> bool ObjectRegistry< T, Key >::InsertItem (T * obj, Key const & key, bool force = false) inline
Inserts a registry item.
    {
        auto itr = _registeredObjects.find(key);
        if (itr != _registeredObjects.end())
        {
            if (!force)
            {
                return false;
            }
            _registeredObjects.erase(itr);
        }
        _registeredObjects.emplace(std::piecewise_construct, std::forward_as_tuple(key), std::forward_as_tuple(obj));
        return true;
    }
References ObjectRegistry< T, Key >::_registeredObjects.
instance()
template<class T , class Key = std::string> static ObjectRegistry< T, Key > * ObjectRegistry< T, Key >::instance () inline static
    {
        static ObjectRegistry<T, Key>* instance = new ObjectRegistry<T, Key>();
        return instance;
    }
References ObjectRegistry< T, Key >::instance().
Referenced by ObjectRegistry< T, Key >::instance(), and FactoryHolder< T, O, Key >::RegisterSelf().
Member Data Documentation
_registeredObjects
template<class T , class Key = std::string> RegistryMapType ObjectRegistry< T, Key >::_registeredObjects private
Referenced by ObjectRegistry< T, Key >::GetRegisteredItems(), ObjectRegistry< T, Key >::GetRegistryItem(), ObjectRegistry< T, Key >::HasItem(), and ObjectRegistry< T, Key >::InsertItem().