AzerothCore: instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript Struct Reference
instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript Struct Reference
Public Member Functions
instance_ruby_sanctum_InstanceMapScript (InstanceMap *map)
void OnPlayerEnter (Player *) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetGuidData (uint32 type) const override
bool SetBossState (uint32 type, EncounterState state) override
void FillInitialWorldStates (WorldPacket &data) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
ObjectGuid BaltharusTheWarbornGUID
ObjectGuid XerestraszaGUID
ObjectGuid GeneralZarithrianGUID
ObjectGuid ZarithrianSpawnStalkerGUID [2]
ObjectGuid HalionGUID
ObjectGuid TwilightHalionGUID
ObjectGuid HalionControllerGUID
ObjectGuid OrbCarrierGUID
ObjectGuid FlameRingGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_ruby_sanctum_InstanceMapScript()
instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::instance_ruby_sanctum_InstanceMapScript (InstanceMap * map) inline
                                                                  : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTERS);
            LoadBossBoundaries(boundaries);
            LoadDoorData(doorData);
        }
References boundaries, DataHeader, doorData, InstanceScript::LoadBossBoundaries(), InstanceScript::LoadDoorData(), MAX_ENCOUNTERS, InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
FillInitialWorldStates()
void instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::FillInitialWorldStates (WorldPacket & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << uint32(WORLDSTATE_CORPOREALITY_MATERIAL) << uint32(50);
            data << uint32(WORLDSTATE_CORPOREALITY_TWILIGHT) << uint32(50);
            data << uint32(WORLDSTATE_CORPOREALITY_TOGGLE) << uint32(0);
        }
References WORLDSTATE_CORPOREALITY_MATERIAL, WORLDSTATE_CORPOREALITY_TOGGLE, and WORLDSTATE_CORPOREALITY_TWILIGHT.
GetGuidData()
ObjectGuid instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (type)
            {
                case NPC_BALTHARUS_THE_WARBORN:
                    return BaltharusTheWarbornGUID;
                case NPC_XERESTRASZA:
                    return XerestraszaGUID;
                case NPC_GENERAL_ZARITHRIAN:
                    return GeneralZarithrianGUID;
                case DATA_ZARITHRIAN_SPAWN_STALKER_1:
                case DATA_ZARITHRIAN_SPAWN_STALKER_2:
                    return ZarithrianSpawnStalkerGUID[type - DATA_ZARITHRIAN_SPAWN_STALKER_1];
                case NPC_HALION_CONTROLLER:
                    return HalionControllerGUID;
                case NPC_HALION:
                    return HalionGUID;
                case NPC_TWILIGHT_HALION:
                    return TwilightHalionGUID;
                case NPC_ORB_CARRIER:
                    return OrbCarrierGUID;
                case GO_FLAME_RING:
                    return FlameRingGUID;
            }
            return ObjectGuid::Empty;
        }
References BaltharusTheWarbornGUID, DATA_ZARITHRIAN_SPAWN_STALKER_1, DATA_ZARITHRIAN_SPAWN_STALKER_2, ObjectGuid::Empty, FlameRingGUID, GeneralZarithrianGUID, GO_FLAME_RING, HalionControllerGUID, HalionGUID, NPC_BALTHARUS_THE_WARBORN, NPC_GENERAL_ZARITHRIAN, NPC_HALION, NPC_HALION_CONTROLLER, NPC_ORB_CARRIER, NPC_TWILIGHT_HALION, NPC_XERESTRASZA, OrbCarrierGUID, TwilightHalionGUID, XerestraszaGUID, and ZarithrianSpawnStalkerGUID.
OnCreatureCreate()
void instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_BALTHARUS_THE_WARBORN:
                    BaltharusTheWarbornGUID = creature->GetGUID();
                    break;
                case NPC_XERESTRASZA:
                    XerestraszaGUID = creature->GetGUID();
                    break;
                case NPC_GENERAL_ZARITHRIAN:
                    GeneralZarithrianGUID = creature->GetGUID();
                    break;
                case NPC_ZARITHRIAN_SPAWN_STALKER:
                    if (!ZarithrianSpawnStalkerGUID[0])
                        ZarithrianSpawnStalkerGUID[0] = creature->GetGUID();
                    else
                        ZarithrianSpawnStalkerGUID[1] = creature->GetGUID();
                    break;
                case NPC_HALION:
                    HalionGUID = creature->GetGUID();
                    break;
                case NPC_TWILIGHT_HALION:
                    TwilightHalionGUID = creature->GetGUID();
                    break;
                case NPC_HALION_CONTROLLER:
                    HalionControllerGUID = creature->GetGUID();
                    break;
                case NPC_ORB_CARRIER:
                    OrbCarrierGUID = creature->GetGUID();
                    break;
                case NPC_LIVING_INFERNO:
                case NPC_LIVING_EMBER:
                case NPC_METEOR_STRIKE_NORTH:
                case NPC_METEOR_STRIKE_SOUTH:
                case NPC_METEOR_STRIKE_EAST:
                case NPC_METEOR_STRIKE_WEST:
                case NPC_METEOR_STRIKE_FLAME:
                case NPC_COMBUSTION:
                case NPC_CONSUMPTION:
                    if (Creature* halion = instance->GetCreature(HalionGUID))
                        halion->AI()->JustSummoned(creature);
                    break;
            }
        }
References BaltharusTheWarbornGUID, GeneralZarithrianGUID, Map::GetCreature(), Object::GetEntry(), Object::GetGUID(), HalionControllerGUID, HalionGUID, InstanceScript::instance, NPC_BALTHARUS_THE_WARBORN, NPC_COMBUSTION, NPC_CONSUMPTION, NPC_GENERAL_ZARITHRIAN, NPC_HALION, NPC_HALION_CONTROLLER, NPC_LIVING_EMBER, NPC_LIVING_INFERNO, NPC_METEOR_STRIKE_EAST, NPC_METEOR_STRIKE_FLAME, NPC_METEOR_STRIKE_NORTH, NPC_METEOR_STRIKE_SOUTH, NPC_METEOR_STRIKE_WEST, NPC_ORB_CARRIER, NPC_TWILIGHT_HALION, NPC_XERESTRASZA, NPC_ZARITHRIAN_SPAWN_STALKER, OrbCarrierGUID, TwilightHalionGUID, XerestraszaGUID, and ZarithrianSpawnStalkerGUID.
OnGameObjectCreate()
void instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_FIRE_FIELD:
                case GO_FLAME_WALLS:
                case GO_BURNING_TREE_1:
                case GO_BURNING_TREE_2:
                case GO_BURNING_TREE_3:
                case GO_BURNING_TREE_4:
                case GO_TWILIGHT_FLAME_RING:
                    AddDoor(go);
                    break;
                case GO_FLAME_RING:
                    FlameRingGUID = go->GetGUID();
                    break;
            }
        }
References InstanceScript::AddDoor(), FlameRingGUID, Object::GetEntry(), Object::GetGUID(), GO_BURNING_TREE_1, GO_BURNING_TREE_2, GO_BURNING_TREE_3, GO_BURNING_TREE_4, GO_FIRE_FIELD, GO_FLAME_RING, GO_FLAME_WALLS, and GO_TWILIGHT_FLAME_RING.
OnGameObjectRemove()
void instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_FIRE_FIELD:
                case GO_FLAME_WALLS:
                case GO_BURNING_TREE_1:
                case GO_BURNING_TREE_2:
                case GO_BURNING_TREE_3:
                case GO_BURNING_TREE_4:
                    RemoveDoor(go);
                    break;
            }
        }
References Object::GetEntry(), GO_BURNING_TREE_1, GO_BURNING_TREE_2, GO_BURNING_TREE_3, GO_BURNING_TREE_4, GO_FIRE_FIELD, GO_FLAME_WALLS, and InstanceScript::RemoveDoor().
OnPlayerEnter()
void instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnPlayerEnter (Player *) inline override virtual
Reimplemented from InstanceScript.
        {
            if (GetBossState(DATA_HALION_INTRO_DONE) != DONE && GetBossState(DATA_GENERAL_ZARITHRIAN) == DONE)
            {
                instance->LoadGrid(3156.0f, 537.0f);
                if (Creature* halionController = instance->GetCreature(HalionControllerGUID))
                    halionController->AI()->DoAction(ACTION_INTRO_HALION);
            }
        }
References ACTION_INTRO_HALION, DATA_GENERAL_ZARITHRIAN, DATA_HALION_INTRO_DONE, DONE, InstanceScript::GetBossState(), Map::GetCreature(), HalionControllerGUID, InstanceScript::instance, and Map::LoadGrid().
SetBossState()
bool instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            switch (type)
            {
                case DATA_HALION_INTRO_DONE:
                    if (state != DONE)
                    {
                        SetBossState(DATA_HALION_INTRO1, NOT_STARTED);
                        SetBossState(DATA_HALION_INTRO2, NOT_STARTED);
                    }
                    break;
                case DATA_SAVIANA_RAGEFIRE:
                case DATA_BALTHARUS_THE_WARBORN:
                    if (GetBossState(DATA_BALTHARUS_THE_WARBORN) == DONE && GetBossState(DATA_SAVIANA_RAGEFIRE) == DONE)
                        if (Creature* zarithrian = instance->GetCreature(GeneralZarithrianGUID))
{
                            zarithrian->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                            zarithrian->SetImmuneToPC(false);
                        }
                    break;
                case DATA_GENERAL_ZARITHRIAN:
                    if (state == DONE)
                        if (Creature* halionController = instance->GetCreature(HalionControllerGUID))
                            halionController->AI()->DoAction(ACTION_INTRO_HALION);
                    break;
                case DATA_HALION:
                    DoUpdateWorldState(WORLDSTATE_CORPOREALITY_TOGGLE, 0);
                    DoUpdateWorldState(WORLDSTATE_CORPOREALITY_TWILIGHT, 0);
                    DoUpdateWorldState(WORLDSTATE_CORPOREALITY_MATERIAL, 0);
                    HandleGameObject(FlameRingGUID, true);
                    break;
            }
            return true;
        }
References ACTION_INTRO_HALION, DATA_BALTHARUS_THE_WARBORN, DATA_GENERAL_ZARITHRIAN, DATA_HALION, DATA_HALION_INTRO1, DATA_HALION_INTRO2, DATA_HALION_INTRO_DONE, DATA_SAVIANA_RAGEFIRE, DONE, InstanceScript::DoUpdateWorldState(), FlameRingGUID, GeneralZarithrianGUID, InstanceScript::GetBossState(), Map::GetCreature(), HalionControllerGUID, InstanceScript::HandleGameObject(), InstanceScript::instance, NOT_STARTED, InstanceScript::SetBossState(), SetBossState(), UNIT_FLAG_NOT_SELECTABLE, WORLDSTATE_CORPOREALITY_MATERIAL, WORLDSTATE_CORPOREALITY_TOGGLE, and WORLDSTATE_CORPOREALITY_TWILIGHT.
Referenced by SetBossState().
Member Data Documentation
BaltharusTheWarbornGUID
ObjectGuid instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::BaltharusTheWarbornGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
FlameRingGUID
ObjectGuid instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::FlameRingGUID protected
Referenced by GetGuidData(), OnGameObjectCreate(), and SetBossState().
GeneralZarithrianGUID
ObjectGuid instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::GeneralZarithrianGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), and SetBossState().
HalionControllerGUID
ObjectGuid instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::HalionControllerGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), OnPlayerEnter(), and SetBossState().
HalionGUID
ObjectGuid instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::HalionGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
OrbCarrierGUID
ObjectGuid instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OrbCarrierGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
TwilightHalionGUID
ObjectGuid instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::TwilightHalionGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
XerestraszaGUID
ObjectGuid instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::XerestraszaGUID protected
Referenced by GetGuidData(), and OnCreatureCreate().
ZarithrianSpawnStalkerGUID
ObjectGuid instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::ZarithrianSpawnStalkerGUID[2] protected
Referenced by GetGuidData(), and OnCreatureCreate().