AzerothCore: DBCFileLoader::Record Class Reference
DBCFileLoader::Record Class Reference
#include "DBCFileLoader.h"
Public Member Functions
float getFloat (std::size_t field) const
uint32 getUInt (std::size_t field) const
uint8 getUInt8 (std::size_t field) const
const char * getString (std::size_t field) const
Private Member Functions
Record (DBCFileLoader &file_, unsigned char *offset_)
Private Attributes
unsigned char * offset
DBCFileLoader & file
Friends
class DBCFileLoader
Detailed Description
Constructor & Destructor Documentation
Record()
DBCFileLoader::Record::Record (DBCFileLoader & file_, unsigned char * offset_) inline private
: offset(offset_), file(file_) { }
Member Function Documentation
getFloat()
float DBCFileLoader::Record::getFloat (std::size_t field) const inline
        {
            ASSERT(field < file.fieldCount);
            float val = *reinterpret_cast<float*>(offset + file.GetOffset(field));
            EndianConvert(val);
            return val;
        }
References ASSERT, EndianConvert(), DBCFileLoader::fieldCount, file, DBCFileLoader::GetOffset(), and offset.
Referenced by DBCFileLoader::AutoProduceData().
getString()
const char * DBCFileLoader::Record::getString (std::size_t field) const inline
        {
            ASSERT(field < file.fieldCount);
            std::size_t stringOffset = getUInt(field);
            ASSERT(stringOffset < file.stringSize);
            return reinterpret_cast<char*>(file.stringTable + stringOffset);
        }
References ASSERT, DBCFileLoader::fieldCount, file, getUInt(), DBCFileLoader::stringSize, and DBCFileLoader::stringTable.
Referenced by DBCFileLoader::AutoProduceStrings().
getUInt()
uint32 DBCFileLoader::Record::getUInt (std::size_t field) const inline
        {
            ASSERT(field < file.fieldCount);
            uint32 val = *reinterpret_cast<uint32*>(offset + file.GetOffset(field));
            EndianConvert(val);
            return val;
        }
References ASSERT, EndianConvert(), DBCFileLoader::fieldCount, file, DBCFileLoader::GetOffset(), and offset.
Referenced by DBCFileLoader::AutoProduceData(), and getString().
getUInt8()
uint8 DBCFileLoader::Record::getUInt8 (std::size_t field) const inline
        {
            ASSERT(field < file.fieldCount);
            return *reinterpret_cast<uint8*>(offset + file.GetOffset(field));
        }
References ASSERT, DBCFileLoader::fieldCount, file, DBCFileLoader::GetOffset(), and offset.
Referenced by DBCFileLoader::AutoProduceData().
Friends And Related Function Documentation
DBCFileLoader
friend class DBCFileLoader friend
Member Data Documentation
file
DBCFileLoader& DBCFileLoader::Record::file private
Referenced by getFloat(), getString(), getUInt(), and getUInt8().
offset
unsigned char* DBCFileLoader::Record::offset private
Referenced by getFloat(), getUInt(), and getUInt8().