AzerothCore: SpellInfoVisitor Struct Reference
SpellInfoVisitor Struct Reference
Public Types
using value_type = SpellInfo const *
Public Member Functions
value_type operator() (Hyperlink< enchant > enchant) const
value_type operator() (Hyperlink< glyph > glyph) const
value_type operator() (Hyperlink< spell > spell) const
value_type operator() (Hyperlink< talent > talent) const
value_type operator() (Hyperlink< trade > trade) const
value_type operator() (uint32 spellId) const
Detailed Description
Member Typedef Documentation
value_type
using SpellInfoVisitor::value_type = SpellInfo const*
Member Function Documentation
operator()() [1/6]
value_type SpellInfoVisitor::operator() (Hyperlink< enchant > enchant) const inline
{ return enchant; };
Referenced by operator()().
operator()() [2/6]
value_type SpellInfoVisitor::operator() (Hyperlink< glyph > glyph) const inline
{ return operator()(glyph->Glyph->SpellId); };
References operator()().
Referenced by operator()().
operator()() [3/6]
value_type SpellInfoVisitor::operator() (Hyperlink< spell > spell) const inline
{ return *spell; }
operator()() [4/6]
value_type SpellInfoVisitor::operator() (Hyperlink< talent > talent) const inline
    {
        return operator()(talent->Talent->RankID[talent->Rank - 1]);
    };
References operator()().
operator()() [5/6]
value_type SpellInfoVisitor::operator() (Hyperlink< trade > trade) const inline
{ return trade->Spell; };
operator()() [6/6]
value_type SpellInfoVisitor::operator() (uint32 spellId) const inline
{ return sSpellMgr->GetSpellInfo(spellId); }
References sSpellMgr.