AzerothCore: instance_shattered_halls::instance_shattered_halls_InstanceMapScript Struct Reference
instance_shattered_halls::instance_shattered_halls_InstanceMapScript Struct Reference
Public Member Functions
instance_shattered_halls_InstanceMapScript (Map *map)
void Initialize () override
void OnPlayerEnter (Player *player) override
void OnGameObjectCreate (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
bool SetBossState (uint32 type, EncounterState state) override
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 data) const override
void Update (uint32 diff) override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
ObjectGuid warchiefKargathGUID
ObjectGuid nethekurseDoor1GUID
ObjectGuid nethekurseDoor2GUID
ObjectGuid executionerGUID
ObjectGuid prisonerGUID [3]
uint32 RescueTimer
TeamId TeamIdInInstance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_shattered_halls_InstanceMapScript()
instance_shattered_halls::instance_shattered_halls_InstanceMapScript::instance_shattered_halls_InstanceMapScript (Map * map) inline
: InstanceScript(map) { }
Member Function Documentation
GetGuidData()
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (data)
            {
                case DATA_PRISONER_1:
                case DATA_PRISONER_2:
                case DATA_PRISONER_3:
                    return prisonerGUID[data - DATA_PRISONER_1];
                case DATA_EXECUTIONER:
                    return executionerGUID;
            }
            return ObjectGuid::Empty;
        }
References DATA_EXECUTIONER, DATA_PRISONER_1, DATA_PRISONER_2, DATA_PRISONER_3, ObjectGuid::Empty, executionerGUID, and prisonerGUID.
Initialize()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetBossNumber(ENCOUNTER_COUNT);
            TeamIdInInstance = TEAM_NEUTRAL;
            RescueTimer = 100 * MINUTE * IN_MILLISECONDS;
        }
References ENCOUNTER_COUNT, IN_MILLISECONDS, MINUTE, RescueTimer, InstanceScript::SetBossNumber(), TEAM_NEUTRAL, and TeamIdInInstance.
OnCreatureCreate()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            if (TeamIdInInstance == TEAM_NEUTRAL)
            {
                Map::PlayerList const& players = instance->GetPlayers();
                if (!players.IsEmpty())
                    if (Player* player = players.begin()->GetSource())
                        TeamIdInInstance = player->GetTeamId();
            }
            switch (creature->GetEntry())
            {
                case NPC_WARCHIEF_KARGATH:
                    warchiefKargathGUID = creature->GetGUID();
                    break;
                case NPC_SHATTERED_EXECUTIONER:
                    if (RescueTimer > 25 * MINUTE * IN_MILLISECONDS)
                        creature->AddLootMode(2);
                    executionerGUID = creature->GetGUID();
                    break;
                case NPC_RIFLEMAN_BROWNBEARD:
                    if (TeamIdInInstance == TEAM_HORDE)
                        creature->UpdateEntry(NPC_KORAG_PROUDMANE);
                    prisonerGUID[0] = creature->GetGUID();
                    break;
                case NPC_CAPTAIN_ALINA:
                    if (TeamIdInInstance == TEAM_HORDE)
                        creature->UpdateEntry(NPC_CAPTAIN_BONESHATTER);
                    prisonerGUID[1] = creature->GetGUID();
                    break;
                case NPC_PRIVATE_JACINT:
                    if (TeamIdInInstance == TEAM_HORDE)
                        creature->UpdateEntry(NPC_SCOUT_ORGARR);
                    prisonerGUID[2] = creature->GetGUID();
                    break;
            }
        }
References Creature::AddLootMode(), MapRefMgr::begin(), executionerGUID, Object::GetEntry(), Object::GetGUID(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), IN_MILLISECONDS, InstanceScript::instance, LinkedListHead::IsEmpty(), MINUTE, NPC_CAPTAIN_ALINA, NPC_CAPTAIN_BONESHATTER, NPC_KORAG_PROUDMANE, NPC_PRIVATE_JACINT, NPC_RIFLEMAN_BROWNBEARD, NPC_SCOUT_ORGARR, NPC_SHATTERED_EXECUTIONER, NPC_WARCHIEF_KARGATH, prisonerGUID, RescueTimer, TEAM_HORDE, TEAM_NEUTRAL, TeamIdInInstance, Creature::UpdateEntry(), and warchiefKargathGUID.
OnGameObjectCreate()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_GRAND_WARLOCK_CHAMBER_DOOR_1:
                    nethekurseDoor1GUID = go->GetGUID();
                    if (GetBossState(DATA_NETHEKURSE) == DONE)
                        HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
                case GO_GRAND_WARLOCK_CHAMBER_DOOR_2:
                    nethekurseDoor2GUID = go->GetGUID();
                    if (GetBossState(DATA_NETHEKURSE) == DONE)
                        HandleGameObject(ObjectGuid::Empty, true, go);
                    break;
            }
        }
References DATA_NETHEKURSE, DONE, ObjectGuid::Empty, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_GRAND_WARLOCK_CHAMBER_DOOR_1, GO_GRAND_WARLOCK_CHAMBER_DOOR_2, InstanceScript::HandleGameObject(), nethekurseDoor1GUID, and nethekurseDoor2GUID.
OnPlayerEnter()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
        {
            if (TeamIdInInstance == TEAM_NEUTRAL)
                TeamIdInInstance = player->GetTeamId();
        }
References Player::GetTeamId(), TEAM_NEUTRAL, and TeamIdInInstance.
ReadSaveDataMore()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> RescueTimer;
        }
References RescueTimer.
SetBossState()
bool instance_shattered_halls::instance_shattered_halls_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            switch (type)
            {
                case DATA_NETHEKURSE:
                    if (state == IN_PROGRESS)
                    {
                        HandleGameObject(nethekurseDoor1GUID, false);
                        HandleGameObject(nethekurseDoor2GUID, false);
                    }
                    else
                    {
                        HandleGameObject(nethekurseDoor1GUID, true);
                        HandleGameObject(nethekurseDoor2GUID, true);
                    }
                    break;
            }
            return true;
        }
References DATA_NETHEKURSE, InstanceScript::HandleGameObject(), IN_PROGRESS, nethekurseDoor1GUID, nethekurseDoor2GUID, and InstanceScript::SetBossState().
SetData()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == DATA_ENTERED_ROOM && data == DATA_ENTERED_ROOM && RescueTimer == 100 * MINUTE * IN_MILLISECONDS)
            {
                DoCastSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_1);
                instance->LoadGrid(230, -80);
                if (Creature* kargath = instance->GetCreature(warchiefKargathGUID))
                    sCreatureTextMgr->SendChat(kargath, TeamIdInInstance == TEAM_ALLIANCE ? 3 : 4, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_MAP);
                RescueTimer = 80 * MINUTE * IN_MILLISECONDS;
            }
        }
References CHAT_MSG_ADDON, DATA_ENTERED_ROOM, InstanceScript::DoCastSpellOnPlayers(), Map::GetCreature(), IN_MILLISECONDS, InstanceScript::instance, LANG_ADDON, Map::LoadGrid(), MINUTE, RescueTimer, sCreatureTextMgr, SPELL_KARGATHS_EXECUTIONER_1, TEAM_ALLIANCE, TeamIdInInstance, TEXT_RANGE_MAP, and warchiefKargathGUID.
Update()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            if (RescueTimer && RescueTimer < 100 * MINUTE * IN_MILLISECONDS)
            {
                RescueTimer -= std::min(RescueTimer, diff);
                if ((RescueTimer / IN_MILLISECONDS) == 25 * MINUTE)
                {
                    DoRemoveAurasDueToSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_1);
                    DoCastSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_2);
                    if (Creature* prisoner = instance->GetCreature(prisonerGUID[0]))
                        Unit::Kill(prisoner, prisoner);
                    if (Creature* executioner = instance->GetCreature(executionerGUID))
                        executioner->RemoveLootMode(2);
                }
                else if ((RescueTimer / IN_MILLISECONDS) == 15 * MINUTE)
                {
                    DoRemoveAurasDueToSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_2);
                    DoCastSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_3);
                    if (Creature* prisoner = instance->GetCreature(prisonerGUID[1]))
                        Unit::Kill(prisoner, prisoner);
                }
                else if ((RescueTimer / IN_MILLISECONDS) == 0)
                {
                    DoRemoveAurasDueToSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_3);
                    if (Creature* prisoner = instance->GetCreature(prisonerGUID[2]))
                        Unit::Kill(prisoner, prisoner);
                }
            }
        }
References InstanceScript::DoCastSpellOnPlayers(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), executionerGUID, Map::GetCreature(), IN_MILLISECONDS, InstanceScript::instance, Unit::Kill(), MINUTE, prisonerGUID, RescueTimer, SPELL_KARGATHS_EXECUTIONER_1, SPELL_KARGATHS_EXECUTIONER_2, and SPELL_KARGATHS_EXECUTIONER_3.
WriteSaveDataMore()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << RescueTimer;
        }
References RescueTimer.
Member Data Documentation
executionerGUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::executionerGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), and Update().
nethekurseDoor1GUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::nethekurseDoor1GUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
nethekurseDoor2GUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::nethekurseDoor2GUID protected
Referenced by OnGameObjectCreate(), and SetBossState().
prisonerGUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::prisonerGUID[3] protected
Referenced by GetGuidData(), OnCreatureCreate(), and Update().
RescueTimer
uint32 instance_shattered_halls::instance_shattered_halls_InstanceMapScript::RescueTimer protected
Referenced by Initialize(), OnCreatureCreate(), ReadSaveDataMore(), SetData(), Update(), and WriteSaveDataMore().
TeamIdInInstance
TeamId instance_shattered_halls::instance_shattered_halls_InstanceMapScript::TeamIdInInstance protected
Referenced by Initialize(), OnCreatureCreate(), OnPlayerEnter(), and SetData().
warchiefKargathGUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::warchiefKargathGUID protected
Referenced by OnCreatureCreate(), and SetData().