AzeorthCore: PlayerScript Class Reference
PlayerScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
virtual void OnPlayerReleasedGhost (Player *)
virtual void OnSendInitialPacketsBeforeAddToMap (Player *, WorldPacket &)
virtual void OnBattlegroundDesertion (Player *, BattlegroundDesertionType const)
virtual void OnPlayerCompleteQuest (Player *, Quest const *)
virtual void OnPVPKill (Player *, Player *)
virtual void OnPlayerPVPFlagChange (Player *, bool)
virtual void OnCreatureKill (Player *, Creature *)
virtual void OnCreatureKilledByPet (Player *, Creature *)
virtual void OnPlayerKilledByCreature (Creature *, Player *)
virtual void OnLevelChanged (Player *, uint8)
virtual void OnFreeTalentPointsChanged (Player *, uint32)
virtual void OnTalentsReset (Player *, bool)
virtual void OnBeforeUpdate (Player *, uint32)
virtual void OnUpdate (Player *, uint32)
virtual void OnMoneyChanged (Player *, int32 &)
virtual void OnBeforeLootMoney (Player *, Loot *)
virtual void OnGiveXP (Player *, uint32 &, Unit *)
virtual bool OnReputationChange (Player *, uint32, int32 &, bool)
virtual void OnReputationRankChange (Player *, uint32, ReputationRank, ReputationRank, bool)
virtual void OnLearnSpell (Player *, uint32)
virtual void OnForgotSpell (Player *, uint32)
virtual void OnDuelRequest (Player *, Player *)
virtual void OnDuelStart (Player *, Player *)
virtual void OnDuelEnd (Player *, Player *, DuelCompleteType)
virtual void OnChat (Player *, uint32, uint32, std::string &)
virtual void OnBeforeSendChatMessage (Player *, uint32 &, uint32 &, std::string &)
virtual void OnChat (Player *, uint32, uint32, std::string &, Player *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Group *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Guild *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Channel *)
virtual void OnEmote (Player *, uint32)
virtual void OnTextEmote (Player *, uint32, uint32, ObjectGuid)
virtual void OnSpellCast (Player *, Spell *, bool)
virtual void OnLoadFromDB (Player *)
virtual void OnLogin (Player *)
virtual void OnLogout (Player *)
virtual void OnCreate (Player *)
virtual void OnDelete (ObjectGuid, uint32)
virtual void OnFailedDelete (ObjectGuid, uint32)
virtual void OnSave (Player *)
virtual void OnBindToInstance (Player *, Difficulty, uint32, bool)
virtual void OnUpdateZone (Player *, uint32, uint32)
virtual void OnUpdateArea (Player *, uint32, uint32)
virtual void OnMapChanged (Player *)
virtual bool OnBeforeTeleport (Player *, uint32, float, float, float, float, uint32, Unit *)
virtual void OnUpdateFaction (Player *)
virtual void OnAddToBattleground (Player *, Battleground *)
virtual void OnQueueRandomDungeon (Player *, uint32 &)
virtual void OnRemoveFromBattleground (Player *, Battleground *)
virtual void OnAchiComplete (Player *, AchievementEntry const *)
virtual bool OnBeforeAchiComplete (Player *, AchievementEntry const *)
virtual void OnCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual bool OnBeforeCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual void OnAchiSave (CharacterDatabaseTransaction, Player *, uint16, CompletedAchievementData)
virtual void OnCriteriaSave (CharacterDatabaseTransaction, Player *, uint16, CriteriaProgress)
virtual void OnGossipSelect (Player *, uint32, uint32, uint32)
virtual void OnGossipSelectCode (Player *, uint32, uint32, uint32, const char *)
virtual void OnBeingCharmed (Player *, Unit *, uint32, uint32)
virtual void OnAfterSetVisibleItemSlot (Player *, uint8, Item *)
virtual void OnAfterMoveItemFromInventory (Player *, Item *, uint8, uint8, bool)
virtual void OnEquip (Player *, Item *, uint8, uint8, bool)
virtual void OnPlayerJoinBG (Player *)
virtual void OnPlayerJoinArena (Player *)
virtual void GetCustomGetArenaTeamId (Player const *, uint8, uint32 &) const
virtual void GetCustomArenaPersonalRating (Player const *, uint8, uint32 &) const
virtual void OnGetMaxPersonalArenaRatingRequirement (Player const *, uint32, uint32 &) const
virtual void OnLootItem (Player *, Item *, uint32, ObjectGuid)
virtual void OnStoreNewItem (Player *, Item *, uint32)
virtual void OnCreateItem (Player *, Item *, uint32)
virtual void OnQuestRewardItem (Player *, Item *, uint32)
virtual void OnGroupRollRewardItem (Player *, Item *, uint32, RollVote, Roll *)
virtual bool OnBeforeOpenItem (Player *, Item *)
virtual bool OnBeforeQuestComplete (Player *, uint32)
virtual void OnQuestComputeXP (Player *, Quest const *, uint32 &)
virtual void OnBeforeDurabilityRepair (Player *, ObjectGuid, ObjectGuid, float &, uint8)
virtual void OnBeforeBuyItemFromVendor (Player *, ObjectGuid, uint32, uint32 &, uint8, uint8, uint8)
virtual void OnBeforeStoreOrEquipNewItem (Player *, uint32, uint32 &, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnAfterStoreOrEquipNewItem (Player *, uint32, Item *, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnAfterUpdateMaxPower (Player *, Powers &, float &)
virtual void OnAfterUpdateMaxHealth (Player *, float &)
virtual void OnBeforeUpdateAttackPowerAndDamage (Player *, float &, float &, bool)
virtual void OnAfterUpdateAttackPowerAndDamage (Player *, float &, float &, float &, float &, bool)
virtual void OnBeforeInitTalentForLevel (Player *, uint8 &, uint32 &)
virtual void OnFirstLogin (Player *)
virtual void OnSetMaxLevel (Player *, uint32 &)
virtual bool CanJoinInBattlegroundQueue (Player *, ObjectGuid, BattlegroundTypeId, uint8, GroupJoinBattlegroundResult &)
virtual bool ShouldBeRewardedWithMoneyInsteadOfExp (Player *)
virtual void OnBeforeTempSummonInitStats (Player *, TempSummon *, uint32 &)
virtual void OnBeforeGuardianInitStatsForLevel (Player *, Guardian *, CreatureTemplate const *, PetType &)
virtual void OnAfterGuardianInitStatsForLevel (Player *, Guardian *)
virtual void OnBeforeLoadPetFromDB (Player *, uint32 &, uint32 &, bool &, bool &)
virtual bool CanJoinInArenaQueue (Player *, ObjectGuid, uint8, BattlegroundTypeId, uint8, uint8, GroupJoinBattlegroundResult &)
virtual bool CanBattleFieldPort (Player *, uint8, BattlegroundTypeId, uint8)
virtual bool CanGroupInvite (Player *, std::string &)
virtual bool CanGroupAccept (Player *, Group *)
virtual bool CanSellItem (Player *, Item *, Creature *)
virtual bool CanSendMail (Player *, ObjectGuid, ObjectGuid, std::string &, std::string &, uint32, uint32, Item *)
virtual void PetitionBuy (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void PetitionShowList (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void OnRewardKillRewarder (Player *, bool, float &)
virtual bool CanGiveMailRewardAtGiveLevel (Player *, uint8)
virtual void OnDeleteFromDB (CharacterDatabaseTransaction, uint32)
virtual bool CanRepopAtGraveyard (Player *)
virtual void OnGetMaxSkillValue (Player *, uint32, int32 &, bool)
virtual bool OnUpdateFishingSkill (Player *, int32, int32, int32, int32)
virtual bool CanAreaExploreAndOutdoor (Player *)
virtual void OnVictimRewardBefore (Player *, Player *, uint32 &, uint32 &)
virtual void OnVictimRewardAfter (Player *, Player *, uint32 &, uint32 &, float &)
virtual void OnCustomScalingStatValueBefore (Player *, ItemTemplate const *, uint8, bool, uint32 &)
virtual void OnCustomScalingStatValue (Player *, ItemTemplate const *, uint32 &, int32 &, uint8, uint32, ScalingStatValuesEntry const *)
virtual bool CanArmorDamageModifier (Player *)
virtual void OnGetFeralApBonus (Player *, int32 &, int32, ItemTemplate const *, ScalingStatValuesEntry const *)
virtual bool CanApplyWeaponDependentAuraDamageMod (Player *, Item *, WeaponAttackType, AuraEffect const *, bool)
virtual bool CanApplyEquipSpell (Player *, SpellInfo const *, Item *, bool, bool)
virtual bool CanApplyEquipSpellsItemSet (Player *, ItemSetEffect *)
virtual bool CanCastItemCombatSpell (Player *, Unit *, WeaponAttackType, uint32, uint32, Item *, ItemTemplate const *)
virtual bool CanCastItemUseSpell (Player *, Item *, SpellCastTargets const &, uint8, uint32)
virtual void OnApplyAmmoBonuses (Player *, ItemTemplate const *, float &)
virtual bool CanEquipItem (Player *, uint8, uint16 &, Item *, bool, bool)
virtual bool CanUnequipItem (Player *, uint16, bool)
virtual bool CanUseItem (Player *, ItemTemplate const *, InventoryResult &)
virtual bool CanSaveEquipNewItem (Player *, Item *, uint16, bool)
virtual bool CanApplyEnchantment (Player *, Item *, EnchantmentSlot, bool, bool, bool)
virtual void OnGetQuestRate (Player *, float &)
virtual bool PassedQuestKilledMonsterCredit (Player *, Quest const *, uint32, uint32, ObjectGuid)
virtual bool CheckItemInSlotAtLoadInventory (Player *, Item *, uint8, uint8 &, uint16 &)
virtual bool NotAvoidSatisfy (Player *, DungeonProgressionRequirements const *, uint32, bool)
virtual bool NotVisibleGloballyFor (Player *, Player const *)
virtual void OnGetArenaPersonalRating (Player *, uint8, uint32 &)
virtual void OnGetArenaTeamId (Player *, uint8, uint32 &)
virtual void OnIsFFAPvP (Player *, bool &)
virtual void OnFfaPvpStateUpdate (Player *, bool)
virtual void OnIsPvP (Player *, bool &)
virtual void OnGetMaxSkillValueForLevel (Player *, uint16 &)
virtual bool NotSetArenaTeamInfoField (Player *, uint8, ArenaTeamInfoType, uint32)
virtual bool CanJoinLfg (Player *, uint8, lfg::LfgDungeonSet &, const std::string &)
virtual bool CanEnterMap (Player *, MapEntry const *, InstanceTemplate const *, MapDifficulty const *, bool)
virtual bool CanInitTrade (Player *, Player *)
virtual void OnSetServerSideVisibility (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnSetServerSideVisibilityDetect (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnPlayerResurrect (Player *, float, bool)
virtual void OnBeforeChooseGraveyard (Player *, TeamId, bool, uint32 &)
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &)
This hook called before player sending message in default chat.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Player *)
This hook called before player sending message to other player via private.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Group *)
This hook called before player sending message to group.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Guild *)
This hook called before player sending message to guild.
virtual bool CanPlayerUseChat (Player *, uint32, uint32, std::string &, Channel *)
This hook called before player sending message to channel.
virtual void OnPlayerLearnTalents (Player *, uint32, uint32, uint32)
This hook called after player learning talents.
virtual void OnPlayerEnterCombat (Player *, Unit *)
This hook called after player entering combat.
virtual void OnPlayerLeaveCombat (Player *)
This hook called after player leave combat.
virtual void OnQuestAbandon (Player *, uint32)
This hook called after player abandoning quest.
virtual void AnticheatSetSkipOnePacketForASH (Player *, bool)
virtual void AnticheatSetCanFlybyServer (Player *, bool)
virtual void AnticheatSetUnderACKmount (Player *)
virtual void AnticheatSetRootACKUpd (Player *)
virtual void AnticheatSetJumpingbyOpcode (Player *, bool)
virtual void AnticheatUpdateMovementInfo (Player *, MovementInfo const &)
virtual bool AnticheatHandleDoubleJump (Player *, Unit *)
virtual bool AnticheatCheckMovementInfo (Player *, MovementInfo const &, Unit *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
PlayerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
PlayerScript()
PlayerScript::PlayerScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<PlayerScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
AnticheatCheckMovementInfo()
virtual bool PlayerScript::AnticheatCheckMovementInfo (Player * , MovementInfo const & , Unit * , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::AnticheatCheckMovementInfo().
AnticheatHandleDoubleJump()
virtual bool PlayerScript::AnticheatHandleDoubleJump (Player * , Unit *) inline virtual
{ return true; }
Referenced by ScriptMgr::AnticheatHandleDoubleJump().
AnticheatSetCanFlybyServer()
virtual void PlayerScript::AnticheatSetCanFlybyServer (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::AnticheatSetCanFlybyServer().
AnticheatSetJumpingbyOpcode()
virtual void PlayerScript::AnticheatSetJumpingbyOpcode (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::AnticheatSetJumpingbyOpcode().
AnticheatSetRootACKUpd()
virtual void PlayerScript::AnticheatSetRootACKUpd (Player *) inline virtual
{ }
Referenced by ScriptMgr::AnticheatSetRootACKUpd().
AnticheatSetSkipOnePacketForASH()
virtual void PlayerScript::AnticheatSetSkipOnePacketForASH (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::AnticheatSetSkipOnePacketForASH().
AnticheatSetUnderACKmount()
virtual void PlayerScript::AnticheatSetUnderACKmount (Player *) inline virtual
{ }
Referenced by ScriptMgr::AnticheatSetUnderACKmount().
AnticheatUpdateMovementInfo()
virtual void PlayerScript::AnticheatUpdateMovementInfo (Player * , MovementInfo const &) inline virtual
{ }
Referenced by ScriptMgr::AnticheatUpdateMovementInfo().
CanApplyEnchantment()
virtual bool PlayerScript::CanApplyEnchantment (Player * , Item * , EnchantmentSlot , bool , bool , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::CanApplyEnchantment().
CanApplyEquipSpell()
virtual bool PlayerScript::CanApplyEquipSpell (Player * , SpellInfo const * , Item * , bool , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::CanApplyEquipSpell().
CanApplyEquipSpellsItemSet()
virtual bool PlayerScript::CanApplyEquipSpellsItemSet (Player * , ItemSetEffect *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanApplyEquipSpellsItemSet().
CanApplyWeaponDependentAuraDamageMod()
virtual bool PlayerScript::CanApplyWeaponDependentAuraDamageMod (Player * , Item * , WeaponAttackType , AuraEffect const * , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::CanApplyWeaponDependentAuraDamageMod().
CanAreaExploreAndOutdoor()
virtual bool PlayerScript::CanAreaExploreAndOutdoor (Player *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanAreaExploreAndOutdoor().
CanArmorDamageModifier()
virtual bool PlayerScript::CanArmorDamageModifier (Player *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanArmorDamageModifier().
CanBattleFieldPort()
virtual bool PlayerScript::CanBattleFieldPort (Player * , uint8 , BattlegroundTypeId , uint8) inline virtual
{ return true; }
Referenced by ScriptMgr::CanBattleFieldPort().
CanCastItemCombatSpell()
virtual bool PlayerScript::CanCastItemCombatSpell (Player * , Unit * , WeaponAttackType , uint32 , uint32 , Item * , ItemTemplate const *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanCastItemCombatSpell().
CanCastItemUseSpell()
virtual bool PlayerScript::CanCastItemUseSpell (Player * , Item * , SpellCastTargets const & , uint8 , uint32) inline virtual
{ return true; }
Referenced by ScriptMgr::CanCastItemUseSpell().
CanEnterMap()
virtual bool PlayerScript::CanEnterMap (Player * , MapEntry const * , InstanceTemplate const * , MapDifficulty const * , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::CanEnterMap().
CanEquipItem()
virtual bool PlayerScript::CanEquipItem (Player * , uint8 , uint16 & , Item * , bool , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::CanEquipItem().
CanGiveMailRewardAtGiveLevel()
virtual bool PlayerScript::CanGiveMailRewardAtGiveLevel (Player * , uint8) inline virtual
{ return true; }
Referenced by ScriptMgr::CanGiveMailRewardAtGiveLevel().
CanGroupAccept()
virtual bool PlayerScript::CanGroupAccept (Player * , Group *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanGroupAccept().
CanGroupInvite()
virtual bool PlayerScript::CanGroupInvite (Player * , std::string &) inline virtual
{ return true; }
Referenced by ScriptMgr::CanGroupInvite().
CanInitTrade()
virtual bool PlayerScript::CanInitTrade (Player * , Player *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanInitTrade().
CanJoinInArenaQueue()
virtual bool PlayerScript::CanJoinInArenaQueue (Player * , ObjectGuid , uint8 , BattlegroundTypeId , uint8 , uint8 , GroupJoinBattlegroundResult &) inline virtual
{ return true; }
Referenced by ScriptMgr::CanJoinInArenaQueue().
CanJoinInBattlegroundQueue()
virtual bool PlayerScript::CanJoinInBattlegroundQueue (Player * , ObjectGuid , BattlegroundTypeId , uint8 , GroupJoinBattlegroundResult &) inline virtual
{ return true; }
Referenced by ScriptMgr::CanJoinInBattlegroundQueue().
CanJoinLfg()
virtual bool PlayerScript::CanJoinLfg (Player * , uint8 , lfg::LfgDungeonSet & , const std::string &) inline virtual
{ return true; }
Referenced by ScriptMgr::CanJoinLfg().
CanPlayerUseChat() [1/5]
virtual bool PlayerScript::CanPlayerUseChat (Player * , uint32 , uint32 , std::string &) inline virtual
This hook called before player sending message in default chat.
Parameters
player Contains information about the Player sender
type Contains information about the chat message type
language Contains information about the language type
msg Contains information about the message
Returns
True if you want to continue sending the message, false if you want to disable sending the message
{ return true; }
Referenced by ScriptMgr::CanPlayerUseChat().
CanPlayerUseChat() [2/5]
virtual bool PlayerScript::CanPlayerUseChat (Player * , uint32 , uint32 , std::string & , Channel *) inline virtual
This hook called before player sending message to channel.
Parameters
player Contains information about the Player sender
type Contains information about the chat message type
language Contains information about the language type
msg Contains information about the message
channel Contains information about the Channel
Returns
True if you want to continue sending the message, false if you want to disable sending the message
{ return true; }
CanPlayerUseChat() [3/5]
virtual bool PlayerScript::CanPlayerUseChat (Player * , uint32 , uint32 , std::string & , Group *) inline virtual
This hook called before player sending message to group.
Parameters
player Contains information about the Player sender
type Contains information about the chat message type
language Contains information about the language type
msg Contains information about the message
group Contains information about the Group
Returns
True if you want to continue sending the message, false if you want to disable sending the message
{ return true; }
CanPlayerUseChat() [4/5]
virtual bool PlayerScript::CanPlayerUseChat (Player * , uint32 , uint32 , std::string & , Guild *) inline virtual
This hook called before player sending message to guild.
Parameters
player Contains information about the Player sender
type Contains information about the chat message type
language Contains information about the language type
msg Contains information about the message
guild Contains information about the Guild
Returns
True if you want to continue sending the message, false if you want to disable sending the message
{ return true; }
CanPlayerUseChat() [5/5]
virtual bool PlayerScript::CanPlayerUseChat (Player * , uint32 , uint32 , std::string & , Player *) inline virtual
This hook called before player sending message to other player via private.
Parameters
player Contains information about the Player sender
type Contains information about the chat message type
language Contains information about the language type
msg Contains information about the message
receiver Contains information about the Player receiver
Returns
True if you want to continue sending the message, false if you want to disable sending the message
{ return true; }
CanRepopAtGraveyard()
virtual bool PlayerScript::CanRepopAtGraveyard (Player *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanRepopAtGraveyard().
CanSaveEquipNewItem()
virtual bool PlayerScript::CanSaveEquipNewItem (Player * , Item * , uint16 , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::CanSaveEquipNewItem().
CanSellItem()
virtual bool PlayerScript::CanSellItem (Player * , Item * , Creature *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanSellItem().
CanSendMail()
virtual bool PlayerScript::CanSendMail (Player * , ObjectGuid , ObjectGuid , std::string & , std::string & , uint32 , uint32 , Item *) inline virtual
{ return true; }
Referenced by ScriptMgr::CanSendMail().
CanUnequipItem()
virtual bool PlayerScript::CanUnequipItem (Player * , uint16 , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::CanUnequipItem().
CanUseItem()
virtual bool PlayerScript::CanUseItem (Player * , ItemTemplate const * , InventoryResult &) inline virtual
{ return true; }
Referenced by ScriptMgr::CanUseItem().
CheckItemInSlotAtLoadInventory()
virtual bool PlayerScript::CheckItemInSlotAtLoadInventory (Player * , Item * , uint8 , uint8 & , uint16 &) inline virtual
{ return true; }
Referenced by ScriptMgr::CheckItemInSlotAtLoadInventory().
GetCustomArenaPersonalRating()
virtual void PlayerScript::GetCustomArenaPersonalRating (Player const * , uint8 , uint32 &) const inline virtual
{ }
Referenced by ScriptMgr::GetCustomArenaPersonalRating().
GetCustomGetArenaTeamId()
virtual void PlayerScript::GetCustomGetArenaTeamId (Player const * , uint8 , uint32 &) const inline virtual
{ }
Referenced by ScriptMgr::GetCustomGetArenaTeamId().
NotAvoidSatisfy()
virtual bool PlayerScript::NotAvoidSatisfy (Player * , DungeonProgressionRequirements const * , uint32 , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::NotAvoidSatisfy().
NotSetArenaTeamInfoField()
virtual bool PlayerScript::NotSetArenaTeamInfoField (Player * , uint8 , ArenaTeamInfoType , uint32) inline virtual
{ return true; }
Referenced by ScriptMgr::NotSetArenaTeamInfoField().
NotVisibleGloballyFor()
virtual bool PlayerScript::NotVisibleGloballyFor (Player * , Player const *) inline virtual
{ return true; }
Referenced by ScriptMgr::NotVisibleGloballyFor().
OnAchiComplete()
virtual void PlayerScript::OnAchiComplete (Player * , AchievementEntry const *) inline virtual
{ }
Referenced by ScriptMgr::OnAchievementComplete().
OnAchiSave()
virtual void PlayerScript::OnAchiSave (CharacterDatabaseTransaction , Player * , uint16 , CompletedAchievementData) inline virtual
{ }
Referenced by ScriptMgr::OnAchievementSave().
OnAddToBattleground()
virtual void PlayerScript::OnAddToBattleground (Player * , Battleground *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAddToBattleground().
OnAfterGuardianInitStatsForLevel()
virtual void PlayerScript::OnAfterGuardianInitStatsForLevel (Player * , Guardian *) inline virtual
{ }
Referenced by ScriptMgr::OnAfterGuardianInitStatsForLevel().
OnAfterMoveItemFromInventory()
virtual void PlayerScript::OnAfterMoveItemFromInventory (Player * , Item * , uint8 , uint8 , bool) inline virtual
{ }
Referenced by ScriptMgr::OnAfterPlayerMoveItemFromInventory().
OnAfterSetVisibleItemSlot()
virtual void PlayerScript::OnAfterSetVisibleItemSlot (Player * , uint8 , Item *) inline virtual
{ }
Referenced by ScriptMgr::OnAfterPlayerSetVisibleItemSlot().
OnAfterStoreOrEquipNewItem()
virtual void PlayerScript::OnAfterStoreOrEquipNewItem (Player * , uint32 , Item * , uint8 , uint8 , uint8 , ItemTemplate const * , Creature * , VendorItem const * , bool) inline virtual
{ };
Referenced by ScriptMgr::OnAfterStoreOrEquipNewItem().
OnAfterUpdateAttackPowerAndDamage()
virtual void PlayerScript::OnAfterUpdateAttackPowerAndDamage (Player * , float & , float & , float & , float & , bool) inline virtual
{ }
Referenced by ScriptMgr::OnAfterUpdateAttackPowerAndDamage().
OnAfterUpdateMaxHealth()
virtual void PlayerScript::OnAfterUpdateMaxHealth (Player * , float &) inline virtual
{ }
Referenced by ScriptMgr::OnAfterUpdateMaxHealth().
OnAfterUpdateMaxPower()
virtual void PlayerScript::OnAfterUpdateMaxPower (Player * , Powers & , float &) inline virtual
{ }
Referenced by ScriptMgr::OnAfterUpdateMaxPower().
OnApplyAmmoBonuses()
virtual void PlayerScript::OnApplyAmmoBonuses (Player * , ItemTemplate const * , float &) inline virtual
{ }
Referenced by ScriptMgr::OnApplyAmmoBonuses().
OnBattlegroundDesertion()
virtual void PlayerScript::OnBattlegroundDesertion (Player * , BattlegroundDesertionType const) inline virtual
{ }
Referenced by ScriptMgr::OnBattlegroundDesertion().
OnBeforeAchiComplete()
virtual bool PlayerScript::OnBeforeAchiComplete (Player * , AchievementEntry const *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnBeforeAchievementComplete().
OnBeforeBuyItemFromVendor()
virtual void PlayerScript::OnBeforeBuyItemFromVendor (Player * , ObjectGuid , uint32 , uint32 & , uint8 , uint8 , uint8) inline virtual
{ };
Referenced by ScriptMgr::OnBeforeBuyItemFromVendor().
OnBeforeChooseGraveyard()
virtual void PlayerScript::OnBeforeChooseGraveyard (Player * , TeamId , bool , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeChooseGraveyard().
OnBeforeCriteriaProgress()
virtual bool PlayerScript::OnBeforeCriteriaProgress (Player * , AchievementCriteriaEntry const *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnBeforeCriteriaProgress().
OnBeforeDurabilityRepair()
virtual void PlayerScript::OnBeforeDurabilityRepair (Player * , ObjectGuid , ObjectGuid , float & , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnBeforePlayerDurabilityRepair().
OnBeforeGuardianInitStatsForLevel()
virtual void PlayerScript::OnBeforeGuardianInitStatsForLevel (Player * , Guardian * , CreatureTemplate const * , PetType &) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeGuardianInitStatsForLevel().
OnBeforeInitTalentForLevel()
virtual void PlayerScript::OnBeforeInitTalentForLevel (Player * , uint8 & , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeInitTalentForLevel().
OnBeforeLoadPetFromDB()
virtual void PlayerScript::OnBeforeLoadPetFromDB (Player * , uint32 & , uint32 & , bool & , bool &) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeLoadPetFromDB().
OnBeforeLootMoney()
virtual void PlayerScript::OnBeforeLootMoney (Player * , Loot *) inline virtual
{}
Referenced by ScriptMgr::OnBeforeLootMoney().
OnBeforeOpenItem()
virtual bool PlayerScript::OnBeforeOpenItem (Player * , Item *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnBeforeOpenItem().
OnBeforeQuestComplete()
virtual bool PlayerScript::OnBeforeQuestComplete (Player * , uint32) inline virtual
{ return true; }
Referenced by ScriptMgr::OnBeforePlayerQuestComplete().
OnBeforeSendChatMessage()
virtual void PlayerScript::OnBeforeSendChatMessage (Player * , uint32 & , uint32 & , std::string &) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeSendChatMessage().
OnBeforeStoreOrEquipNewItem()
virtual void PlayerScript::OnBeforeStoreOrEquipNewItem (Player * , uint32 , uint32 & , uint8 , uint8 , uint8 , ItemTemplate const * , Creature * , VendorItem const * , bool) inline virtual
{ };
Referenced by ScriptMgr::OnBeforeStoreOrEquipNewItem().
OnBeforeTeleport()
virtual bool PlayerScript::OnBeforeTeleport (Player * , uint32 , float , float , float , float , uint32 , Unit *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnBeforePlayerTeleport().
OnBeforeTempSummonInitStats()
virtual void PlayerScript::OnBeforeTempSummonInitStats (Player * , TempSummon * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeTempSummonInitStats().
OnBeforeUpdate()
virtual void PlayerScript::OnBeforeUpdate (Player * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnBeforePlayerUpdate().
OnBeforeUpdateAttackPowerAndDamage()
virtual void PlayerScript::OnBeforeUpdateAttackPowerAndDamage (Player * , float & , float & , bool) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeUpdateAttackPowerAndDamage().
OnBeingCharmed()
virtual void PlayerScript::OnBeingCharmed (Player * , Unit * , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeingCharmed().
OnBindToInstance()
virtual void PlayerScript::OnBindToInstance (Player * , Difficulty , uint32 , bool) inline virtual
Reimplemented in lfg::LFGPlayerScript.
{ }
Referenced by ScriptMgr::OnPlayerBindToInstance().
OnChat() [1/5]
virtual void PlayerScript::OnChat (Player * , uint32 , uint32 , std::string &) inline virtual
Reimplemented in ChatLogScript.
{ }
Referenced by ScriptMgr::OnPlayerChat().
OnChat() [2/5]
virtual void PlayerScript::OnChat (Player * , uint32 , uint32 , std::string & , Channel *) inline virtual
Reimplemented in ChatLogScript.
{ }
OnChat() [3/5]
virtual void PlayerScript::OnChat (Player * , uint32 , uint32 , std::string & , Group *) inline virtual
Reimplemented in ChatLogScript.
{ }
OnChat() [4/5]
virtual void PlayerScript::OnChat (Player * , uint32 , uint32 , std::string & , Guild *) inline virtual
Reimplemented in ChatLogScript.
{ }
OnChat() [5/5]
virtual void PlayerScript::OnChat (Player * , uint32 , uint32 , std::string & , Player *) inline virtual
Reimplemented in ChatLogScript.
{ }
OnCreate()
virtual void PlayerScript::OnCreate (Player *) inline virtual
Reimplemented in CharacterActionIpLogger.
{ }
Referenced by ScriptMgr::OnPlayerCreate().
OnCreateItem()
virtual void PlayerScript::OnCreateItem (Player * , Item * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnCreateItem().
OnCreatureKill()
virtual void PlayerScript::OnCreatureKill (Player * , Creature *) inline virtual
{ }
Referenced by ScriptMgr::OnCreatureKill().
OnCreatureKilledByPet()
virtual void PlayerScript::OnCreatureKilledByPet (Player * , Creature *) inline virtual
{ }
Referenced by ScriptMgr::OnCreatureKilledByPet().
OnCriteriaProgress()
virtual void PlayerScript::OnCriteriaProgress (Player * , AchievementCriteriaEntry const *) inline virtual
{ }
Referenced by ScriptMgr::OnCriteriaProgress().
OnCriteriaSave()
virtual void PlayerScript::OnCriteriaSave (CharacterDatabaseTransaction , Player * , uint16 , CriteriaProgress) inline virtual
{ }
Referenced by ScriptMgr::OnCriteriaSave().
OnCustomScalingStatValue()
virtual void PlayerScript::OnCustomScalingStatValue (Player * , ItemTemplate const * , uint32 & , int32 & , uint8 , uint32 , ScalingStatValuesEntry const *) inline virtual
{ }
Referenced by ScriptMgr::OnCustomScalingStatValue().
OnCustomScalingStatValueBefore()
virtual void PlayerScript::OnCustomScalingStatValueBefore (Player * , ItemTemplate const * , uint8 , bool , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnCustomScalingStatValueBefore().
OnDelete()
virtual void PlayerScript::OnDelete (ObjectGuid , uint32) inline virtual
Reimplemented in CharacterDeleteActionIpLogger.
{ }
Referenced by ScriptMgr::OnPlayerDelete().
OnDeleteFromDB()
virtual void PlayerScript::OnDeleteFromDB (CharacterDatabaseTransaction , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnDeleteFromDB().
OnDuelEnd()
virtual void PlayerScript::OnDuelEnd (Player * , Player * , DuelCompleteType) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerDuelEnd().
OnDuelRequest()
virtual void PlayerScript::OnDuelRequest (Player * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerDuelRequest().
OnDuelStart()
virtual void PlayerScript::OnDuelStart (Player * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerDuelStart().
OnEmote()
virtual void PlayerScript::OnEmote (Player * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerEmote().
OnEquip()
virtual void PlayerScript::OnEquip (Player * , Item * , uint8 , uint8 , bool) inline virtual
{ }
Referenced by ScriptMgr::OnEquip().
OnFailedDelete()
virtual void PlayerScript::OnFailedDelete (ObjectGuid , uint32) inline virtual
Reimplemented in CharacterDeleteActionIpLogger.
{ }
Referenced by ScriptMgr::OnPlayerFailedDelete().
OnFfaPvpStateUpdate()
virtual void PlayerScript::OnFfaPvpStateUpdate (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::OnFfaPvpStateUpdate().
OnFirstLogin()
virtual void PlayerScript::OnFirstLogin (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnFirstLogin().
OnForgotSpell()
virtual void PlayerScript::OnForgotSpell (Player * , uint32) inline virtual
{}
Referenced by ScriptMgr::OnPlayerForgotSpell().
OnFreeTalentPointsChanged()
virtual void PlayerScript::OnFreeTalentPointsChanged (Player * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerFreeTalentPointsChanged().
OnGetArenaPersonalRating()
virtual void PlayerScript::OnGetArenaPersonalRating (Player * , uint8 , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnGetArenaPersonalRating().
OnGetArenaTeamId()
virtual void PlayerScript::OnGetArenaTeamId (Player * , uint8 , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnGetArenaTeamId().
OnGetFeralApBonus()
virtual void PlayerScript::OnGetFeralApBonus (Player * , int32 & , int32 , ItemTemplate const * , ScalingStatValuesEntry const *) inline virtual
{ }
Referenced by ScriptMgr::OnGetFeralApBonus().
OnGetMaxPersonalArenaRatingRequirement()
virtual void PlayerScript::OnGetMaxPersonalArenaRatingRequirement (Player const * , uint32 , uint32 &) const inline virtual
{}
Referenced by ScriptMgr::OnGetMaxPersonalArenaRatingRequirement().
OnGetMaxSkillValue()
virtual void PlayerScript::OnGetMaxSkillValue (Player * , uint32 , int32 & , bool) inline virtual
{ }
Referenced by ScriptMgr::OnGetMaxSkillValue().
OnGetMaxSkillValueForLevel()
virtual void PlayerScript::OnGetMaxSkillValueForLevel (Player * , uint16 &) inline virtual
{ }
Referenced by ScriptMgr::OnGetMaxSkillValueForLevel().
OnGetQuestRate()
virtual void PlayerScript::OnGetQuestRate (Player * , float &) inline virtual
{ }
Referenced by ScriptMgr::OnGetQuestRate().
OnGiveXP()
virtual void PlayerScript::OnGiveXP (Player * , uint32 & , Unit *) inline virtual
{ }
Referenced by ScriptMgr::OnGivePlayerXP().
OnGossipSelect()
virtual void PlayerScript::OnGossipSelect (Player * , uint32 , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnGossipSelect().
OnGossipSelectCode()
virtual void PlayerScript::OnGossipSelectCode (Player * , uint32 , uint32 , uint32 , const char *) inline virtual
{ }
Referenced by ScriptMgr::OnGossipSelectCode().
OnGroupRollRewardItem()
virtual void PlayerScript::OnGroupRollRewardItem (Player * , Item * , uint32 , RollVote , Roll *) inline virtual
{ }
Referenced by ScriptMgr::OnGroupRollRewardItem().
OnIsFFAPvP()
virtual void PlayerScript::OnIsFFAPvP (Player * , bool &) inline virtual
{ }
Referenced by ScriptMgr::OnIsFFAPvP().
OnIsPvP()
virtual void PlayerScript::OnIsPvP (Player * , bool &) inline virtual
{ }
Referenced by ScriptMgr::OnIsPvP().
OnLearnSpell()
virtual void PlayerScript::OnLearnSpell (Player * , uint32) inline virtual
{}
Referenced by ScriptMgr::OnPlayerLearnSpell().
OnLevelChanged()
virtual void PlayerScript::OnLevelChanged (Player * , uint8) inline virtual
Reimplemented in lfg::LFGPlayerScript.
{ }
Referenced by ScriptMgr::OnPlayerLevelChanged().
OnLoadFromDB()
virtual void PlayerScript::OnLoadFromDB (Player *) inline virtual
{ };
Referenced by ScriptMgr::OnPlayerLoadFromDB().
OnLogin()
virtual void PlayerScript::OnLogin (Player *) inline virtual
Reimplemented in lfg::LFGPlayerScript, CharacterActionIpLogger, and ServerMailReward.
{ }
Referenced by ScriptMgr::OnPlayerLogin().
OnLogout()
virtual void PlayerScript::OnLogout (Player *) inline virtual
Reimplemented in lfg::LFGPlayerScript, and CharacterActionIpLogger.
{ }
Referenced by ScriptMgr::OnPlayerLogout().
OnLootItem()
virtual void PlayerScript::OnLootItem (Player * , Item * , uint32 , ObjectGuid) inline virtual
{ }
Referenced by ScriptMgr::OnLootItem().
OnMapChanged()
virtual void PlayerScript::OnMapChanged (Player *) inline virtual
Reimplemented in lfg::LFGPlayerScript.
{ }
OnMoneyChanged()
virtual void PlayerScript::OnMoneyChanged (Player * , int32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerMoneyChanged().
OnPlayerCompleteQuest()
virtual void PlayerScript::OnPlayerCompleteQuest (Player * , Quest const *) inline virtual
Reimplemented in QuestApprenticeAnglerPlayerScript.
{ }
Referenced by ScriptMgr::OnPlayerCompleteQuest().
OnPlayerEnterCombat()
virtual void PlayerScript::OnPlayerEnterCombat (Player * , Unit *) inline virtual
This hook called after player entering combat.
Parameters
player Contains information about the Player
Unit Contains information about the Unit
{ }
Referenced by ScriptMgr::OnPlayerEnterCombat().
OnPlayerJoinArena()
virtual void PlayerScript::OnPlayerJoinArena (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerJoinArena().
OnPlayerJoinBG()
virtual void PlayerScript::OnPlayerJoinBG (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerJoinBG().
OnPlayerKilledByCreature()
virtual void PlayerScript::OnPlayerKilledByCreature (Creature * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerKilledByCreature().
OnPlayerLearnTalents()
virtual void PlayerScript::OnPlayerLearnTalents (Player * , uint32 , uint32 , uint32) inline virtual
This hook called after player learning talents.
Parameters
player Contains information about the Player
talentId Contains information about the talent id
talentRank Contains information about the talent rank
spellid Contains information about the spell id
{ }
Referenced by ScriptMgr::OnPlayerLearnTalents().
OnPlayerLeaveCombat()
virtual void PlayerScript::OnPlayerLeaveCombat (Player *) inline virtual
This hook called after player leave combat.
Parameters
player Contains information about the Player
{ }
Referenced by ScriptMgr::OnPlayerLeaveCombat().
OnPlayerPVPFlagChange()
virtual void PlayerScript::OnPlayerPVPFlagChange (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerPVPFlagChange().
OnPlayerReleasedGhost()
virtual void PlayerScript::OnPlayerReleasedGhost (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerReleasedGhost().
OnPlayerResurrect()
virtual void PlayerScript::OnPlayerResurrect (Player * , float , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerResurrect().
OnPVPKill()
virtual void PlayerScript::OnPVPKill (Player * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPVPKill().
OnQuestAbandon()
virtual void PlayerScript::OnQuestAbandon (Player * , uint32) inline virtual
This hook called after player abandoning quest.
Parameters
player Contains information about the Player
questId Contains information about the quest id
{ }
Referenced by ScriptMgr::OnQuestAbandon().
OnQuestComputeXP()
virtual void PlayerScript::OnQuestComputeXP (Player * , Quest const * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnQuestComputeXP().
OnQuestRewardItem()
virtual void PlayerScript::OnQuestRewardItem (Player * , Item * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnQuestRewardItem().
OnQueueRandomDungeon()
virtual void PlayerScript::OnQueueRandomDungeon (Player * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerQueueRandomDungeon().
OnRemoveFromBattleground()
virtual void PlayerScript::OnRemoveFromBattleground (Player * , Battleground *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerRemoveFromBattleground().
OnReputationChange()
virtual bool PlayerScript::OnReputationChange (Player * , uint32 , int32 & , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerReputationChange().
OnReputationRankChange()
virtual void PlayerScript::OnReputationRankChange (Player * , uint32 , ReputationRank , ReputationRank , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerReputationRankChange().
OnRewardKillRewarder()
virtual void PlayerScript::OnRewardKillRewarder (Player * , bool , float &) inline virtual
{ }
Referenced by ScriptMgr::OnRewardKillRewarder().
OnSave()
virtual void PlayerScript::OnSave (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerSave().
OnSendInitialPacketsBeforeAddToMap()
virtual void PlayerScript::OnSendInitialPacketsBeforeAddToMap (Player * , WorldPacket &) inline virtual
{}
Referenced by ScriptMgr::OnSendInitialPacketsBeforeAddToMap().
OnSetMaxLevel()
virtual void PlayerScript::OnSetMaxLevel (Player * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnSetMaxLevel().
OnSetServerSideVisibility()
virtual void PlayerScript::OnSetServerSideVisibility (Player * , ServerSideVisibilityType & , AccountTypes &) inline virtual
{ }
Referenced by ScriptMgr::OnSetServerSideVisibility().
OnSetServerSideVisibilityDetect()
virtual void PlayerScript::OnSetServerSideVisibilityDetect (Player * , ServerSideVisibilityType & , AccountTypes &) inline virtual
{ }
Referenced by ScriptMgr::OnSetServerSideVisibilityDetect().
OnSpellCast()
virtual void PlayerScript::OnSpellCast (Player * , Spell * , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerSpellCast().
OnStoreNewItem()
virtual void PlayerScript::OnStoreNewItem (Player * , Item * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnStoreNewItem().
OnTalentsReset()
virtual void PlayerScript::OnTalentsReset (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerTalentsReset().
OnTextEmote()
virtual void PlayerScript::OnTextEmote (Player * , uint32 , uint32 , ObjectGuid) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerTextEmote().
OnUpdate()
virtual void PlayerScript::OnUpdate (Player * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerUpdate().
OnUpdateArea()
virtual void PlayerScript::OnUpdateArea (Player * , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerUpdateArea().
OnUpdateFaction()
virtual void PlayerScript::OnUpdateFaction (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerUpdateFaction().
OnUpdateFishingSkill()
virtual bool PlayerScript::OnUpdateFishingSkill (Player * , int32 , int32 , int32 , int32) inline virtual
{ return true; }
Referenced by ScriptMgr::OnUpdateFishingSkill().
OnUpdateZone()
virtual void PlayerScript::OnUpdateZone (Player * , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerUpdateZone().
OnVictimRewardAfter()
virtual void PlayerScript::OnVictimRewardAfter (Player * , Player * , uint32 & , uint32 & , float &) inline virtual
{ }
Referenced by ScriptMgr::OnVictimRewardAfter().
OnVictimRewardBefore()
virtual void PlayerScript::OnVictimRewardBefore (Player * , Player * , uint32 & , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnVictimRewardBefore().
PassedQuestKilledMonsterCredit()
virtual bool PlayerScript::PassedQuestKilledMonsterCredit (Player * , Quest const * , uint32 , uint32 , ObjectGuid) inline virtual
{ return true; }
Referenced by ScriptMgr::PassedQuestKilledMonsterCredit().
PetitionBuy()
virtual void PlayerScript::PetitionBuy (Player * , Creature * , uint32 & , uint32 & , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::PetitionBuy().
PetitionShowList()
virtual void PlayerScript::PetitionShowList (Player * , Creature * , uint32 & , uint32 & , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::PetitionShowList().
ShouldBeRewardedWithMoneyInsteadOfExp()
virtual bool PlayerScript::ShouldBeRewardedWithMoneyInsteadOfExp (Player *) inline virtual
{ return false; }
Referenced by ScriptMgr::ShouldBeRewardedWithMoneyInsteadOfExp().