AzerothCore: npc_cos_chromie_start Class Reference
npc_cos_chromie_start Class Reference
Public Member Functions
npc_cos_chromie_start ()
bool OnQuestAccept (Player *, Creature *creature, const Quest *pQuest)
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32)
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_cos_chromie_start()
npc_cos_chromie_start::npc_cos_chromie_start () inline
: CreatureScript("npc_cos_chromie_start") { }
Member Function Documentation
OnGossipSelect()
bool npc_cos_chromie_start::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32) inline virtual
Reimplemented from CreatureScript.
    {
        // final menu id, show crates if hidden and add item if missing
        if (player->PlayerTalkClass->GetGossipMenu().GetMenuId() == 9595)
        {
            if (InstanceScript* pInstance = creature->GetInstanceScript())
            {
                if (pInstance->GetData(DATA_ARTHAS_EVENT) == COS_PROGRESS_NOT_STARTED)
                {
                    pInstance->SetData(DATA_SHOW_CRATES, 1);
                }
            }
            if (!player->HasItemCount(ITEM_ARCANE_DISRUPTOR))
            {
                creature->CastSpell(player, SPELL_SUMMON_ARCANE_DISRUPTOR);
            }
        }
        // Skip Event
        else if (player->PlayerTalkClass->GetGossipMenu().GetMenuId() == 11277)
        {
            if (InstanceScript* pInstance = creature->GetInstanceScript())
            {
                if (pInstance->GetData(DATA_ARTHAS_EVENT) == COS_PROGRESS_NOT_STARTED)
                {
                    pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_FINISHED_INTRO);
                    if (Creature* arthas = ObjectAccessor::GetCreature(*creature, pInstance->GetGuidData(DATA_ARTHAS)))
                    {
                        arthas->AI()->Reset();
                    }
                }
                player->NearTeleportTo(LeaderIntroPos2.GetPositionX(), LeaderIntroPos2.GetPositionY(), LeaderIntroPos2.GetPositionZ(), LeaderIntroPos2.GetOrientation());
            }
        }
        // return false to display last windows
        return false;
    }
References Unit::CastSpell(), COS_PROGRESS_FINISHED_INTRO, COS_PROGRESS_NOT_STARTED, DATA_ARTHAS, DATA_ARTHAS_EVENT, DATA_SHOW_CRATES, ObjectAccessor::GetCreature(), PlayerMenu::GetGossipMenu(), WorldObject::GetInstanceScript(), GossipMenu::GetMenuId(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Player::HasItemCount(), ITEM_ARCANE_DISRUPTOR, LeaderIntroPos2, Unit::NearTeleportTo(), Player::PlayerTalkClass, and SPELL_SUMMON_ARCANE_DISRUPTOR.
OnQuestAccept()
bool npc_cos_chromie_start::OnQuestAccept (Player * , Creature * creature, const Quest * pQuest) inline virtual
Reimplemented from CreatureScript.
    {
        if (pQuest->GetQuestId() == QUEST_DISPELLING_ILLUSIONS)
        {
            if (InstanceScript* pInstance = creature->GetInstanceScript())
            {
                pInstance->SetData(DATA_SHOW_CRATES, 1);
            }
        }
        return true;
    }
References DATA_SHOW_CRATES, WorldObject::GetInstanceScript(), Quest::GetQuestId(), and QUEST_DISPELLING_ILLUSIONS.