AzerothCore: npc_thrall_warchief Class Reference
npc_thrall_warchief Class Reference
Classes
struct npc_thrall_warchiefAI
Public Member Functions
npc_thrall_warchief ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
bool OnQuestReward (Player *, Creature *creature, Quest const *quest, uint32) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Todo:
verify abilities/timers
Constructor & Destructor Documentation
npc_thrall_warchief()
npc_thrall_warchief::npc_thrall_warchief () inline
: CreatureScript("npc_thrall_warchief") { }
Member Function Documentation
GetAI()
CreatureAI * npc_thrall_warchief::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return new npc_thrall_warchiefAI(creature);
    }
OnGossipHello()
bool npc_thrall_warchief::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (creature->IsQuestGiver())
        {
            player->PrepareQuestMenu(creature->GetGUID());
        }
        if (player->GetQuestStatus(QUEST_WHAT_THE_WIND_CARRIES) == QUEST_STATUS_INCOMPLETE)
        {
            AddGossipItemFor(player, GOSSIP_MENU_THRALL, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
        }
        SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
        return true;
    }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_MENU_THRALL, GOSSIP_SENDER_MAIN, Unit::IsQuestGiver(), Player::PrepareQuestMenu(), QUEST_STATUS_INCOMPLETE, QUEST_WHAT_THE_WIND_CARRIES, and SendGossipMenuFor().
OnGossipSelect()
bool npc_thrall_warchief::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
    {
        ClearGossipMenuFor(player);
        uint32 DiscussionOrder = action - GOSSIP_ACTION_INFO_DEF;
        if (DiscussionOrder>= 1 && DiscussionOrder <= 6)
        {
            uint32 NextAction = GOSSIP_ACTION_INFO_DEF + DiscussionOrder + 1;
            uint32 GossipResponse = GOSSIP_RESPONSE_THRALL_FIRST + DiscussionOrder - 1;
            AddGossipItemFor(player, GOSSIP_MENU_THRALL + DiscussionOrder, 0, GOSSIP_SENDER_MAIN, NextAction);
            SendGossipMenuFor(player, GossipResponse, creature->GetGUID());
        }
        else if (DiscussionOrder == 7)
        {
            CloseGossipMenuFor(player);
            player->AreaExploredOrEventHappens(QUEST_WHAT_THE_WIND_CARRIES);
        }
        return true;
    }
References AddGossipItemFor(), Player::AreaExploredOrEventHappens(), ClearGossipMenuFor(), CloseGossipMenuFor(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_MENU_THRALL, GOSSIP_RESPONSE_THRALL_FIRST, GOSSIP_SENDER_MAIN, QUEST_WHAT_THE_WIND_CARRIES, and SendGossipMenuFor().
OnQuestReward()
bool npc_thrall_warchief::OnQuestReward (Player * , Creature * creature, Quest const * quest, uint32) inline override virtual
Reimplemented from CreatureScript.
    {
        if (quest->GetQuestId() == QUEST_FOR_THE_HORDE)
        {
            if (creature && creature->AI())
            {
                creature->AI()->DoAction(ACTION_START_TALKING);
            }
        }
        return true;
    }
References ACTION_START_TALKING, Creature::AI(), UnitAI::DoAction(), Quest::GetQuestId(), and QUEST_FOR_THE_HORDE.