AzerothCore: SlaveRunEvent Class Reference
SlaveRunEvent Class Reference
Public Member Functions
SlaveRunEvent (Creature &owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature & _owner
Detailed Description
Constructor & Destructor Documentation
SlaveRunEvent()
SlaveRunEvent::SlaveRunEvent (Creature & owner) inline
: _owner(owner) { }
Member Function Documentation
Execute()
bool SlaveRunEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        uint32 pointId = 0;
        float minDist = _owner.GetExactDist2dSq(&slaveFreePos[pointId]);
        for (uint32 i = 1; i < 4; ++i)
        {
            float dist = _owner.GetExactDist2dSq(&slaveFreePos[i]);
            if (dist < minDist)
            {
                minDist = dist;
                pointId = i;
            }
        }
        if (minDist < 200.0f * 200.0f)
            _owner.GetMotionMaster()->MovePoint(0, slaveFreePos[pointId], true, false);
        return true;
    }
References _owner, Position::GetExactDist2dSq(), Unit::GetMotionMaster(), MotionMaster::MovePoint(), and slaveFreePos.
Member Data Documentation
_owner
Creature& SlaveRunEvent::_owner private
Referenced by Execute().