AzerothCore: SOAPCommand Class Reference
SOAPCommand Class Reference
#include "ACSoap.h"
Public Member Functions
SOAPCommand ()
~SOAPCommand ()
void appendToPrintBuffer (std::string_view msg)
void setCommandSuccess (bool val)
bool hasCommandSucceeded () const
Static Public Member Functions
static void print (void *callbackArg, std::string_view msg)
static void commandFinished (void *callbackArg, bool success)
Public Attributes
bool m_success
std::string m_printBuffer
std::promise< void > finishedPromise
Detailed Description
Constructor & Destructor Documentation
SOAPCommand()
SOAPCommand::SOAPCommand () inline
                  :
        m_success(false) { }
~SOAPCommand()
SOAPCommand::~SOAPCommand () inline
{ }
Member Function Documentation
appendToPrintBuffer()
void SOAPCommand::appendToPrintBuffer (std::string_view msg) inline
    {
        m_printBuffer += msg;
    }
References m_printBuffer.
commandFinished()
void SOAPCommand::commandFinished (void * callbackArg, bool success) static
{
    SOAPCommand* con = (SOAPCommand*)soapconnection;
    con->setCommandSuccess(success);
}
References setCommandSuccess().
Referenced by ns1__executeCommand().
hasCommandSucceeded()
bool SOAPCommand::hasCommandSucceeded () const inline
    {
        return m_success;
    }
References m_success.
Referenced by ns1__executeCommand().
print()
static void SOAPCommand::print (void * callbackArg, std::string_view msg) inline static
    {
        ((SOAPCommand*)callbackArg)->appendToPrintBuffer(msg);
    }
Referenced by ns1__executeCommand().
setCommandSuccess()
void SOAPCommand::setCommandSuccess (bool val) inline
    {
        m_success = val;
        finishedPromise.set_value();
    }
References finishedPromise, and m_success.
Referenced by commandFinished().
Member Data Documentation
finishedPromise
std::promise<void> SOAPCommand::finishedPromise
Referenced by ns1__executeCommand(), and setCommandSuccess().
m_printBuffer
std::string SOAPCommand::m_printBuffer
Referenced by appendToPrintBuffer(), and ns1__executeCommand().
m_success
bool SOAPCommand::m_success
Referenced by hasCommandSucceeded(), and setCommandSuccess().