AzeorthCore: boss_devourer_of_souls::boss_devourer_of_soulsAI Struct Reference
boss_devourer_of_souls::boss_devourer_of_soulsAI Struct Reference
Public Member Functions
boss_devourer_of_soulsAI (Creature *creature)
void Reset () override
uint32 GetData (uint32 id) const override
void EnterCombat (Unit *) override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
bool CanAIAttack (Unit const *target) const override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void JustSummoned (Creature *summon) override
void EnterEvadeMode (EvadeReason why) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
Cast Spell.
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
Play sound.
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
Reset Threat.
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
Modify Unit Threat.
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
Teleport player.
void DoTeleportAll (float x, float y, float z, float o)
Teleport all.
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
Set Combat Movement.
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectTargetMethod targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
bool bAchiev
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_devourer_of_soulsAI()
boss_devourer_of_souls::boss_devourer_of_soulsAI::boss_devourer_of_soulsAI (Creature * creature) inline
                                                     : ScriptedAI(creature), summons(me)
        {
            pInstance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
CanAIAttack()
bool boss_devourer_of_souls::boss_devourer_of_soulsAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
{ return target->GetPositionZ() > 706.5f; }
References Position::GetPositionZ().
EnterCombat()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_FACE_AGGRO);
            DoZoneInCombat();
            events.Reset();
            events.RescheduleEvent(EVENT_SPELL_PHANTOM_BLAST, 5000);
            events.RescheduleEvent(EVENT_SPELL_MIRRORED_SOUL, 9000);
            events.RescheduleEvent(EVENT_SPELL_WELL_OF_SOULS, urand(6000, 8000));
            events.RescheduleEvent(EVENT_SPELL_UNLEASHED_SOULS, urand(18000, 20000));
            events.RescheduleEvent(EVENT_SPELL_WAILING_SOULS, 65000);
            if (pInstance)
                pInstance->SetData(DATA_DEVOURER, IN_PROGRESS);
            // Suport for Quest Tempering the Blade
            Map::PlayerList const& pList = me->GetMap()->GetPlayers();
            for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
            {
                Player* player = itr->GetSource();
                if ((player->GetTeamId() == TEAM_ALLIANCE && player->GetQuestStatus(QUEST_TEMPERING_THE_BLADE_A) == QUEST_STATUS_INCOMPLETE) ||
                        (player->GetTeamId() == TEAM_HORDE && player->GetQuestStatus(QUEST_TEMPERING_THE_BLADE_H) == QUEST_STATUS_INCOMPLETE))
                {
                    if (!me->FindNearestCreature(NPC_CRUCIBLE_OF_SOULS, 100.0f))
                        me->SummonCreature(NPC_CRUCIBLE_OF_SOULS, 5672.29f, 2520.69f, 713.44f, 0.96f);
                }
            }
        }
References MapRefMgr::begin(), DATA_DEVOURER, CreatureAI::DoZoneInCombat(), MapRefMgr::end(), EVENT_SPELL_MIRRORED_SOUL, EVENT_SPELL_PHANTOM_BLAST, EVENT_SPELL_UNLEASHED_SOULS, EVENT_SPELL_WAILING_SOULS, EVENT_SPELL_WELL_OF_SOULS, WorldObject::FindNearestCreature(), WorldObject::GetMap(), Map::GetPlayers(), Player::GetQuestStatus(), Player::GetTeamId(), IN_PROGRESS, ScriptedAI::me, NPC_CRUCIBLE_OF_SOULS, pInstance, QUEST_STATUS_INCOMPLETE, QUEST_TEMPERING_THE_BLADE_A, QUEST_TEMPERING_THE_BLADE_H, SAY_FACE_AGGRO, ZoneScript::SetData(), WorldObject::SummonCreature(), TEAM_ALLIANCE, TEAM_HORDE, and urand().
EnterEvadeMode()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            me->SetControlled(false, UNIT_STATE_ROOT);
            me->DisableRotate(false);
            ScriptedAI::EnterEvadeMode(why);
        }
References Unit::DisableRotate(), CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
GetData()
uint32 boss_devourer_of_souls::boss_devourer_of_soulsAI::GetData (uint32 id) const inline override virtual
Reimplemented from UnitAI.
        {
            if (id == 1)
                return bAchiev;
            return 0;
        }
References bAchiev.
JustDied()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_FACE_DEATH);
            summons.DespawnAll();
            if (pInstance)
                pInstance->SetData(DATA_DEVOURER, DONE);
        }
References DATA_DEVOURER, SummonList::DespawnAll(), DONE, pInstance, SAY_FACE_DEATH, ZoneScript::SetData(), and summons.
JustSummoned()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (summon->GetEntry() != NPC_CRUCIBLE_OF_SOULS)
                summons.Summon(summon);
            if (summon->GetEntry() == 36595)
                if (Player* plr = summon->SelectNearestPlayer(100.0f))
                {
                    summon->AddThreat(plr, 100000.0f);
                    summon->AI()->AttackStart(plr);
                }
        }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), Object::GetEntry(), NPC_CRUCIBLE_OF_SOULS, WorldObject::SelectNearestPlayer(), SummonList::Summon(), and summons.
KilledUnit()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->GetTypeId() != TYPEID_PLAYER)
                return;
            int32 textId = 0;
            switch (me->GetDisplayId())
            {
                case DISPLAY_ANGER:
                    textId =  SAY_FACE_ANGER_SLAY;
                    break;
                case DISPLAY_SORROW:
                    textId = SAY_FACE_SORROW_SLAY;
                    break;
                case DISPLAY_DESIRE:
                    textId = SAY_FACE_DESIRE_SLAY;
                    break;
                default:
                    break;
            }
            if (textId)
                Talk(textId);
        }
References DISPLAY_ANGER, DISPLAY_DESIRE, DISPLAY_SORROW, Unit::GetDisplayId(), Object::GetTypeId(), ScriptedAI::me, SAY_FACE_ANGER_SLAY, SAY_FACE_DESIRE_SLAY, SAY_FACE_SORROW_SLAY, and TYPEID_PLAYER.
Reset()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            bAchiev = true;
            me->SetControlled(false, UNIT_STATE_ROOT);
            me->DisableRotate(false);
            me->SetReactState(REACT_AGGRESSIVE);
            events.Reset();
            summons.DespawnAll();
            if (pInstance)
                pInstance->SetData(DATA_DEVOURER, NOT_STARTED);
        }
References bAchiev, DATA_DEVOURER, SummonList::DespawnAll(), Unit::DisableRotate(), ScriptedAI::me, NOT_STARTED, pInstance, REACT_AGGRESSIVE, Unit::SetControlled(), ZoneScript::SetData(), Creature::SetReactState(), summons, and UNIT_STATE_ROOT.
SpellHitTarget()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spell->Id == SPELL_PHANTOM_BLAST_H)
                bAchiev = false;
            else if (spell->Id == SPELL_WAILING_SOULS_TARGETING)
            {
                me->SetOrientation(me->GetAngle(target));
                me->SetControlled(true, UNIT_STATE_ROOT);
                me->DisableRotate(true);
                me->SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
                me->SetReactState(REACT_PASSIVE);
                me->GetMotionMaster()->Clear(false);
                me->GetMotionMaster()->MoveIdle();
                me->StopMovingOnCurrentPos();
                me->SetFacingToObject(target);
                me->SendMovementFlagUpdate();
                me->CastSpell(me, SPELL_WAILING_SOULS, false);
            }
        }
References bAchiev, Unit::CastSpell(), MotionMaster::Clear(), Unit::DisableRotate(), ObjectGuid::Empty, Position::GetAngle(), Unit::GetMotionMaster(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MoveIdle(), REACT_PASSIVE, Unit::SendMovementFlagUpdate(), Unit::SetControlled(), Unit::SetFacingToObject(), Object::SetGuidValue(), Position::SetOrientation(), Creature::SetReactState(), SPELL_PHANTOM_BLAST_H, SPELL_WAILING_SOULS, SPELL_WAILING_SOULS_TARGETING, Unit::StopMovingOnCurrentPos(), UNIT_FIELD_TARGET, and UNIT_STATE_ROOT.
UpdateAI()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (Spell* s = me->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
                if (s->m_spellInfo->Id == SPELL_MIRRORED_SOUL)
                {
                    switch (events.ExecuteEvent())
                    {
                        case 0:
                            break;
                        case EVENT_SPELL_PHANTOM_BLAST:
                            me->CastSpell(me->GetVictim(), SPELL_PHANTOM_BLAST, false);
                            events.RepeatEvent(5000);
                            break;
                        default:
                            events.RepeatEvent(1000);
                            break;
                    }
                    if (!me->GetCurrentSpell(CURRENT_GENERIC_SPELL))
                    {
                        me->ClearUnitState(UNIT_STATE_CASTING);
                        DoMeleeAttackIfReady();
                        me->AddUnitState(UNIT_STATE_CASTING);
                    }
                    return;
                }
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch(events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_SPELL_PHANTOM_BLAST:
                    me->CastSpell(me->GetVictim(), SPELL_PHANTOM_BLAST, false);
                    events.RepeatEvent(5000);
                    break;
                case EVENT_SPELL_MIRRORED_SOUL:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 90.0f, true))
                    {
                        me->CastSpell(target, SPELL_MIRRORED_SOUL, false);
                        me->setAttackTimer(BASE_ATTACK, 2500);
                        Talk(EMOTE_MIRRORED_SOUL);
                    }
                    events.RepeatEvent(urand(20000, 30000));
                    break;
                case EVENT_SPELL_WELL_OF_SOULS:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 40.0f, true))
                        me->CastSpell(target, SPELL_WELL_OF_SOULS, false);
                    events.RepeatEvent(urand(25000, 30000));
                    events.DelayEventsToMax(4000, 0);
                    break;
                case EVENT_SPELL_UNLEASHED_SOULS:
                    me->CastSpell(me, SPELL_UNLEASHED_SOULS, false);
                    Talk(SAY_FACE_UNLEASH_SOUL);
                    Talk(EMOTE_UNLEASH_SOUL);
                    events.RepeatEvent(urand(30000, 40000));
                    events.DelayEventsToMax(5000, 0);
                    me->setAttackTimer(BASE_ATTACK, 5500);
                    break;
                case EVENT_SPELL_WAILING_SOULS:
                    Talk(SAY_FACE_WAILING_SOUL);
                    Talk(EMOTE_WAILING_SOUL);
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true))
                        me->CastCustomSpell(SPELL_WAILING_SOULS_TARGETING, SPELLVALUE_MAX_TARGETS, 1, target, false);
                    events.RepeatEvent(80000);
                    events.DelayEventsToMax(20000, 0);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::AddUnitState(), BASE_ATTACK, Unit::CastCustomSpell(), Unit::CastSpell(), Unit::ClearUnitState(), CURRENT_CHANNELED_SPELL, CURRENT_GENERIC_SPELL, UnitAI::DoMeleeAttackIfReady(), EMOTE_MIRRORED_SOUL, EMOTE_UNLEASH_SOUL, EMOTE_WAILING_SOUL, EVENT_SPELL_MIRRORED_SOUL, EVENT_SPELL_PHANTOM_BLAST, EVENT_SPELL_UNLEASHED_SOULS, EVENT_SPELL_WAILING_SOULS, EVENT_SPELL_WELL_OF_SOULS, Unit::GetCurrentSpell(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, SAY_FACE_UNLEASH_SOUL, SAY_FACE_WAILING_SOUL, UnitAI::SelectTarget(), Unit::setAttackTimer(), SPELL_MIRRORED_SOUL, SPELL_PHANTOM_BLAST, SPELL_UNLEASHED_SOULS, SPELL_WAILING_SOULS_TARGETING, SPELL_WELL_OF_SOULS, SPELLVALUE_MAX_TARGETS, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
bAchiev
bool boss_devourer_of_souls::boss_devourer_of_soulsAI::bAchiev
Referenced by GetData(), Reset(), and SpellHitTarget().
events
EventMap boss_devourer_of_souls::boss_devourer_of_soulsAI::events
pInstance
InstanceScript* boss_devourer_of_souls::boss_devourer_of_soulsAI::pInstance
Referenced by boss_devourer_of_soulsAI(), EnterCombat(), JustDied(), and Reset().
summons
SummonList boss_devourer_of_souls::boss_devourer_of_soulsAI::summons
Referenced by JustDied(), JustSummoned(), and Reset().