AzerothCore: Channel::PlayerInfo Struct Reference
Channel::PlayerInfo Struct Reference
Public Member Functions
bool HasFlag (uint8 flag) const
void SetFlag (uint8 flag)
bool IsOwner () const
void SetOwner (bool state)
bool IsOwnerGM () const
void SetOwnerGM (bool on)
bool IsModerator () const
void SetModerator (bool state)
bool IsMuted () const
void SetMuted (bool state)
Public Attributes
ObjectGuid player
uint8 flags
Player * plrPtr
Private Attributes
bool _gmStatus = false
Detailed Description
Member Function Documentation
HasFlag()
bool Channel::PlayerInfo::HasFlag (uint8 flag) const inline
{ return flags & flag; }
References flags.
Referenced by SetFlag().
IsModerator()
bool Channel::PlayerInfo::IsModerator () const inline
{ return flags & MEMBER_FLAG_MODERATOR; }
References flags, and MEMBER_FLAG_MODERATOR.
Referenced by Channel::Say(), and Channel::SetModerator().
IsMuted()
bool Channel::PlayerInfo::IsMuted () const inline
{ return flags & MEMBER_FLAG_MUTED; }
References flags, and MEMBER_FLAG_MUTED.
Referenced by Channel::Say(), and Channel::SetMute().
IsOwner()
bool Channel::PlayerInfo::IsOwner () const inline
{ return flags & MEMBER_FLAG_OWNER; }
References flags, and MEMBER_FLAG_OWNER.
IsOwnerGM()
bool Channel::PlayerInfo::IsOwnerGM () const inline
{ return _gmStatus; }
References _gmStatus.
SetFlag()
void Channel::PlayerInfo::SetFlag (uint8 flag) inline
{ if (!HasFlag(flag)) flags |= flag; }
References flags, and HasFlag().
SetModerator()
void Channel::PlayerInfo::SetModerator (bool state) inline
        {
            if (state) flags |= MEMBER_FLAG_MODERATOR;
            else flags &= ~MEMBER_FLAG_MODERATOR;
        }
References flags, and MEMBER_FLAG_MODERATOR.
Referenced by Channel::SetModerator(), and Channel::SetOwner().
SetMuted()
void Channel::PlayerInfo::SetMuted (bool state) inline
        {
            if (state) flags |= MEMBER_FLAG_MUTED;
            else flags &= ~MEMBER_FLAG_MUTED;
        }
References flags, and MEMBER_FLAG_MUTED.
Referenced by Channel::SetMute().
SetOwner()
void Channel::PlayerInfo::SetOwner (bool state) inline
        {
            if (state) flags |= MEMBER_FLAG_OWNER;
            else flags &= ~MEMBER_FLAG_OWNER;
        }
References flags, and MEMBER_FLAG_OWNER.
Referenced by Channel::SetOwner().
SetOwnerGM()
void Channel::PlayerInfo::SetOwnerGM (bool on) inline
{ _gmStatus = on; }
References _gmStatus.
Member Data Documentation
_gmStatus
bool Channel::PlayerInfo::_gmStatus = false private
Referenced by IsOwnerGM(), and SetOwnerGM().
flags
uint8 Channel::PlayerInfo::flags
Referenced by HasFlag(), IsModerator(), IsMuted(), IsOwner(), Channel::JoinChannel(), SetFlag(), SetModerator(), Channel::SetModerator(), Channel::SetMute(), SetMuted(), SetOwner(), and Channel::SetOwner().
player
ObjectGuid Channel::PlayerInfo::player
Referenced by Channel::JoinChannel().
plrPtr
Player* Channel::PlayerInfo::plrPtr
Referenced by Channel::JoinChannel(), Channel::Say(), Channel::SetModerator(), and Channel::SetOwner().