AzerothCore: Model Class Reference
Model Class Reference
#include "model.h"
Public Member Functions
bool open ()
bool ConvertToVMAPModel (char const *outfilename)
Model (std::string &filename)
~Model ()
Public Attributes
ModelHeader header
Vec3D * vertices
uint16 * indices
Private Member Functions
void _unload ()
Private Attributes
std::string filename
Detailed Description
Constructor & Destructor Documentation
Model()
Model::Model (std::string & filename)
                                : filename(filename), header(), vertices(nullptr), indices(nullptr)
{
}
~Model()
Model::~Model () inline
{ _unload(); }
References _unload().
Member Function Documentation
_unload()
void Model::_unload () inline private
    {
        delete[] vertices;
        delete[] indices;
        vertices = nullptr;
        indices = nullptr;
    }
References indices, and vertices.
Referenced by open(), and ~Model().
ConvertToVMAPModel()
bool Model::ConvertToVMAPModel (char const * outfilename)
{
    int N[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    FILE* output = fopen(outfilename, "wb");
    if (!output)
    {
        printf("Can't create the output file '%s'\n", outfilename);
        return false;
    }
    fwrite(VMAP::RAW_VMAP_MAGIC, 8, 1, output);
    uint32 nVertices = header.nBoundingVertices;
    fwrite(&nVertices, sizeof(int), 1, output);
    uint32 nofgroups = 1;
    fwrite(&nofgroups, sizeof(uint32), 1, output);
    fwrite(N, 4 * 3, 1, output); // rootwmoid, flags, groupid
    fwrite(N, sizeof(float), 3 * 2, output); //bbox, only needed for WMO currently
    fwrite(N, 4, 1, output); // liquidflags
    fwrite("GRP ", 4, 1, output);
    uint32 branches = 1;
    int wsize;
    wsize = sizeof(branches) + sizeof(uint32) * branches;
    fwrite(&wsize, sizeof(int), 1, output);
    fwrite(&branches, sizeof(branches), 1, output);
    uint32 nIndexes = header.nBoundingTriangles;
    fwrite(&nIndexes, sizeof(uint32), 1, output);
    fwrite("INDX", 4, 1, output);
    wsize = sizeof(uint32) + sizeof(unsigned short) * nIndexes;
    fwrite(&wsize, sizeof(int), 1, output);
    fwrite(&nIndexes, sizeof(uint32), 1, output);
    if (nIndexes > 0)
    {
        for (uint32 i = 0; i < nIndexes; ++i)
        {
            if ((i % 3) - 1 == 0 && i + 1 < nIndexes)
            {
                uint16 tmp = indices[i];
                indices[i] = indices[i + 1];
                indices[i + 1] = tmp;
            }
        }
        fwrite(indices, sizeof(unsigned short), nIndexes, output);
    }
    fwrite("VERT", 4, 1, output);
    wsize = sizeof(int) + sizeof(float) * 3 * nVertices;
    fwrite(&wsize, sizeof(int), 1, output);
    fwrite(&nVertices, sizeof(int), 1, output);
    if (nVertices > 0)
    {
        for (uint32 vpos = 0; vpos < nVertices; ++vpos)
        {
            float tmp = vertices[vpos].y;
            vertices[vpos].y = -vertices[vpos].z;
            vertices[vpos].z = tmp;
        }
        fwrite(vertices, sizeof(float) * 3, nVertices, output);
    }
    fclose(output);
    return true;
}
References header, indices, ModelHeader::nBoundingTriangles, ModelHeader::nBoundingVertices, VMAP::RAW_VMAP_MAGIC, vertices, Vec3D::y, and Vec3D::z.
Referenced by ExtractSingleModel().
open()
bool Model::open ()
{
    MPQFile f(filename.c_str());
    if (f.isEof())
    {
        f.close();
        // Do not show this error on console to avoid confusion, the extractor can continue working even if some models fail to load
        //printf("Error loading model %s\n", filename.c_str());
        return false;
    }
    _unload();
    memcpy(&header, f.getBuffer(), sizeof(ModelHeader));
    if (header.nBoundingTriangles > 0)
    {
        f.seek(0);
        f.seekRelative(header.ofsBoundingVertices);
        vertices = new Vec3D[header.nBoundingVertices];
        f.read(vertices, header.nBoundingVertices * 12);
        for (uint32 i = 0; i < header.nBoundingVertices; i++)
            vertices[i] = fixCoordSystem(vertices[i]);
        f.seek(0);
        f.seekRelative(header.ofsBoundingTriangles);
        indices = new uint16[header.nBoundingTriangles];
        f.read(indices, header.nBoundingTriangles * 2);
        f.close();
    }
    else
    {
        //printf("not included %s\n", filename.c_str());
        f.close();
        return false;
    }
    return true;
}
References _unload(), MPQFile::close(), filename, fixCoordSystem(), MPQFile::getBuffer(), header, indices, MPQFile::isEof(), ModelHeader::nBoundingTriangles, ModelHeader::nBoundingVertices, ModelHeader::ofsBoundingTriangles, ModelHeader::ofsBoundingVertices, MPQFile::read(), MPQFile::seek(), MPQFile::seekRelative(), and vertices.
Referenced by ExtractSingleModel().
Member Data Documentation
filename
std::string Model::filename private
Referenced by open().
header
ModelHeader Model::header
Referenced by ConvertToVMAPModel(), and open().
indices
uint16* Model::indices
Referenced by _unload(), ConvertToVMAPModel(), and open().
vertices
Vec3D* Model::vertices
Referenced by _unload(), ConvertToVMAPModel(), and open().