AzerothCore: PreparedStatementTask Class Reference
PreparedStatementTask Class Reference
#include "PreparedStatement.h"
Public Member Functions
PreparedStatementTask (PreparedStatementBase *stmt, bool async=false)
~PreparedStatementTask () override
bool Execute () override
PreparedQueryResultFuture GetFuture ()
Public Member Functions inherited from SQLOperation
SQLOperation ()=default
virtual ~SQLOperation ()=default
virtual int call ()
virtual bool Execute ()=0
virtual void SetConnection (MySQLConnection *con)
Protected Attributes
PreparedStatementBase * m_stmt
bool m_has_result
PreparedQueryResultPromise * m_result
Additional Inherited Members
Public Attributes inherited from SQLOperation
MySQLConnection * m_conn {nullptr}
Detailed Description
Constructor & Destructor Documentation
PreparedStatementTask()
PreparedStatementTask::PreparedStatementTask (PreparedStatementBase * stmt, bool async = false)
                                                                                    :
    m_stmt(stmt),
    m_result(nullptr)
{
    m_has_result = async; // If it's async, then there's a result
    if (async)
        m_result = new PreparedQueryResultPromise();
}
References m_has_result, and m_result.
~PreparedStatementTask()
PreparedStatementTask::~PreparedStatementTask () override
{
    delete m_stmt;
    if (m_has_result && m_result)
        delete m_result;
}
References m_has_result, m_result, and m_stmt.
Member Function Documentation
Execute()
bool PreparedStatementTask::Execute () override virtual
Implements SQLOperation.
{
    if (m_has_result)
    {
        PreparedResultSet* result = m_conn->Query(m_stmt);
        if (!result || !result->GetRowCount())
        {
            delete result;
            m_result->set_value(PreparedQueryResult(nullptr));
            return false;
        }
        m_result->set_value(PreparedQueryResult(result));
        return true;
    }
    return m_conn->Execute(m_stmt);
}
References MySQLConnection::Execute(), PreparedResultSet::GetRowCount(), SQLOperation::m_conn, m_has_result, m_result, m_stmt, and MySQLConnection::Query().
GetFuture()
PreparedQueryResultFuture PreparedStatementTask::GetFuture () inline
{ return m_result->get_future(); }
Referenced by DatabaseWorkerPool< T >::AsyncQuery().
Member Data Documentation
m_has_result
bool PreparedStatementTask::m_has_result protected
Referenced by Execute(), PreparedStatementTask(), and ~PreparedStatementTask().
m_result
PreparedQueryResultPromise* PreparedStatementTask::m_result protected
Referenced by Execute(), PreparedStatementTask(), and ~PreparedStatementTask().
m_stmt
PreparedStatementBase* PreparedStatementTask::m_stmt protected
Referenced by Execute(), and ~PreparedStatementTask().