AzerothCore: anonymous_namespace{Config.cpp} Namespace Reference
anonymous_namespace{Config.cpp} Namespace Reference
Functions
bool IsAppConfig (std::string_view fileName)
bool IsLoggingSystemOptions (std::string_view optionName)
template<typename Format , typename... Args>
void PrintError (std::string_view filename, Format &&fmt, Args &&... args)
void AddKey (std::string const &optionName, std::string const &optionKey, std::string_view fileName, bool isOptional, bool isReload)
bool ParseFile (std::string const &file, bool isOptional, bool isReload)
bool LoadFile (std::string const &file, bool isOptional, bool isReload)
Variables
std::string _filename
std::vector< std::string > _additonalFiles
std::vector< std::string > _args
std::unordered_map< std::string, std::string > _configOptions
std::mutex _configLock
Function Documentation
AddKey()
void anonymous_namespace{Config.cpp}::AddKey (std::string const & optionName, std::string const & optionKey, std::string_view fileName, bool isOptional, bool isReload)
    {
        auto const& itr = _configOptions.find(optionName);
        // Check old option
        if (isOptional && itr == _configOptions.end())
        {
            if (!IsLoggingSystemOptions(optionName) && !isReload)
            {
                PrintError(fileName, "> Config::LoadFile: Found incorrect option '{}' in config file '{}'. Skip", optionName, fileName);
#ifdef CONFIG_ABORT_INCORRECT_OPTIONS
                ABORT("> Core can't start if found incorrect options");
#endif
                return;
            }
        }
        // Check exit option
        if (itr != _configOptions.end())
        {
            _configOptions.erase(optionName);
        }
        _configOptions.emplace(optionName, optionKey);
    }
References _configOptions, ABORT, IsLoggingSystemOptions(), and PrintError().
Referenced by ParseFile().
IsAppConfig()
bool anonymous_namespace{Config.cpp}::IsAppConfig (std::string_view fileName)
    {
        size_t foundAuth = fileName.find("authserver.conf");
        size_t foundWorld = fileName.find("worldserver.conf");
        return foundAuth != std::string_view::npos || foundWorld != std::string_view::npos;
    }
Referenced by PrintError().
IsLoggingSystemOptions()
bool anonymous_namespace{Config.cpp}::IsLoggingSystemOptions (std::string_view optionName)
    {
        size_t foundAppender = optionName.find("Appender.");
        size_t foundLogger = optionName.find("Logger.");
        return foundAppender != std::string_view::npos || foundLogger != std::string_view::npos;
    }
Referenced by AddKey().
LoadFile()
bool anonymous_namespace{Config.cpp}::LoadFile (std::string const & file, bool isOptional, bool isReload)
    {
        try
        {
            return ParseFile(file, isOptional, isReload);
        }
        catch (const std::exception& e)
        {
            PrintError(file, "> {}", e.what());
        }
        return false;
    }
References ParseFile(), and PrintError().
ParseFile()
bool anonymous_namespace{Config.cpp}::ParseFile (std::string const & file, bool isOptional, bool isReload)
    {
        std::ifstream in(file);
        if (in.fail())
        {
            if (isOptional)
            {
                // No display erorr if file optional
                return false;
            }
            throw ConfigException(Acore::StringFormatFmt("Config::LoadFile: Failed open {}file '{}'", isOptional ? "optional " : "", file));
        }
        uint32 count = 0;
        uint32 lineNumber = 0;
        std::unordered_map<std::string /*name*/, std::string /*value*/> fileConfigs;
        auto IsDuplicateOption = [&](std::string const& confOption)
        {
            auto const& itr = fileConfigs.find(confOption);
            if (itr != fileConfigs.end())
            {
                PrintError(file, "> Config::LoadFile: Dublicate key name '{}' in config file '{}'", confOption, file);
                return true;
            }
            return false;
        };
        while (in.good())
        {
            lineNumber++;
            std::string line;
            std::getline(in, line);
            // read line error
            if (!in.good() && !in.eof())
            {
                throw ConfigException(Acore::StringFormatFmt("> Config::LoadFile: Failure to read line number {} in file '{}'", lineNumber, file));
            }
            // remove whitespace in line
            line = Acore::String::Trim(line, in.getloc());
            if (line.empty())
            {
                continue;
            }
            // comments
            if (line[0] == '#' || line[0] == '[')
            {
                continue;
            }
            size_t found = line.find_first_of('#');
            if (found != std::string::npos)
            {
                line = line.substr(0, found);
            }
            auto const equal_pos = line.find('=');
            if (equal_pos == std::string::npos || equal_pos == line.length())
            {
                PrintError(file, "> Config::LoadFile: Failure to read line number {} in file '{}'. Skip this line", lineNumber, file);
                continue;
            }
            auto entry = Acore::String::Trim(line.substr(0, equal_pos), in.getloc());
            auto value = Acore::String::Trim(line.substr(equal_pos + 1, std::string::npos), in.getloc());
            value.erase(std::remove(value.begin(), value.end(), '"'), value.end());
            // Skip if 2+ same options in one config file
            if (IsDuplicateOption(entry))
            {
                continue;
            }
            // Add to temp container
            fileConfigs.emplace(entry, value);
            count++;
        }
        // No lines read
        if (!count)
        {
            if (isOptional)
            {
                // No display erorr if file optional
                return false;
            }
            throw ConfigException(Acore::StringFormatFmt("Config::LoadFile: Empty file '{}'", file));
        }
        // Add correct keys if file load without errors
        for (auto const& [entry, key] : fileConfigs)
        {
            AddKey(entry, key, file, isOptional, isReload);
        }
        return true;
    }
References AddKey(), PrintError(), Acore::StringFormatFmt(), and Acore::String::Trim().
Referenced by LoadFile().
PrintError()
template<typename Format , typename... Args> void anonymous_namespace{Config.cpp}::PrintError (std::string_view filename, Format && fmt, Args &&... args) inline
    {
        std::string message = Acore::StringFormatFmt(std::forward<Format>(fmt), std::forward<Args>(args)...);
        if (IsAppConfig(filename))
        {
            fmt::print("{}\n", message);
        }
        else
        {
            LOG_ERROR("server.loading", message);
        }
    }
References IsAppConfig(), LOG_ERROR, and Acore::StringFormatFmt().
Referenced by AddKey(), LoadFile(), and ParseFile().
Variable Documentation
_additonalFiles
std::vector<std::string> anonymous_namespace{Config.cpp}::_additonalFiles
_args
std::vector<std::string> anonymous_namespace{Config.cpp}::_args
_configLock
std::mutex anonymous_namespace{Config.cpp}::_configLock
_configOptions
std::unordered_map<std::string , std::string > anonymous_namespace{Config.cpp}::_configOptions
Referenced by AddKey(), and ConfigMgr::GetValueDefault< std::string >().
_filename
std::string anonymous_namespace{Config.cpp}::_filename
Referenced by ConfigMgr::GetValueDefault< std::string >().