AzerothCore: GlobalScript Class Reference
GlobalScript Class Reference
#include "GlobalScript.h"
Public Member Functions
virtual void OnItemDelFromDB (CharacterDatabaseTransaction, ObjectGuid::LowType)
virtual void OnMirrorImageDisplayItem (Item const *, uint32 &)
virtual void OnAfterRefCount (Player const *, LootStoreItem *, Loot &, bool, uint16, uint32 &, LootStore const &)
virtual void OnAfterCalculateLootGroupAmount (Player const *, Loot &, uint16, uint32 &, LootStore const &)
virtual void OnBeforeDropAddItem (Player const *, Loot &, bool, uint16, LootStoreItem *, LootStore const &)
virtual bool OnItemRoll (Player const *, LootStoreItem const *, float &, Loot &, LootStore const &)
virtual bool OnBeforeLootEqualChanced (Player const *, std::list< LootStoreItem * >, Loot &, LootStore const &)
virtual void OnInitializeLockedDungeons (Player *, uint8 &, uint32 &, lfg::LFGDungeonData const *)
virtual void OnAfterInitializeLockedDungeons (Player *)
virtual void OnBeforeUpdateArenaPoints (ArenaTeam *, std::map< ObjectGuid, uint32 > &)
virtual void OnAfterUpdateEncounterState (Map *, EncounterCreditType, uint32, Unit *, Difficulty, std::list< DungeonEncounter const * > const *, uint32, bool)
virtual void OnBeforeWorldObjectSetPhaseMask (WorldObject const *, uint32 &, uint32 &, bool &, bool &)
virtual bool OnIsAffectedBySpellModCheck (SpellInfo const *, SpellInfo const *, SpellModifier const *)
virtual bool OnSpellHealingBonusTakenNegativeModifiers (Unit const *, Unit const *, SpellInfo const *, float &)
virtual void OnLoadSpellCustomAttr (SpellInfo *)
virtual bool OnAllowedForPlayerLootCheck (Player const *, ObjectGuid)
virtual bool OnAllowedToLootContainerCheck (Player const *, ObjectGuid)
virtual void OnInstanceIdRemoved (uint32)
virtual void OnBeforeSetBossState (uint32, EncounterState, EncounterState, Map *)
virtual void AfterInstanceGameObjectCreate (Map *, GameObject *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
GlobalScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
GlobalScript()
GlobalScript::GlobalScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<GlobalScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
AfterInstanceGameObjectCreate()
virtual void GlobalScript::AfterInstanceGameObjectCreate (Map * , GameObject *) inline virtual
{ }
Referenced by ScriptMgr::AfterInstanceGameObjectCreate().
OnAfterCalculateLootGroupAmount()
virtual void GlobalScript::OnAfterCalculateLootGroupAmount (Player const * , Loot & , uint16 , uint32 & , LootStore const &) inline virtual
{ }
Referenced by ScriptMgr::OnAfterCalculateLootGroupAmount().
OnAfterInitializeLockedDungeons()
virtual void GlobalScript::OnAfterInitializeLockedDungeons (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnAfterInitializeLockedDungeons().
OnAfterRefCount()
virtual void GlobalScript::OnAfterRefCount (Player const * , LootStoreItem * , Loot & , bool , uint16 , uint32 & , LootStore const &) inline virtual
{ }
Referenced by ScriptMgr::OnAfterRefCount().
OnAfterUpdateEncounterState()
virtual void GlobalScript::OnAfterUpdateEncounterState (Map * , EncounterCreditType , uint32 , Unit * , Difficulty , std::list< DungeonEncounter const * > const * , uint32 , bool) inline virtual
{ }
Referenced by ScriptMgr::OnAfterUpdateEncounterState().
OnAllowedForPlayerLootCheck()
virtual bool GlobalScript::OnAllowedForPlayerLootCheck (Player const * , ObjectGuid) inline virtual
{ return false; };
Referenced by ScriptMgr::OnAllowedForPlayerLootCheck().
OnAllowedToLootContainerCheck()
virtual bool GlobalScript::OnAllowedToLootContainerCheck (Player const * , ObjectGuid) inline virtual
{ return false; };
Referenced by ScriptMgr::OnAllowedToLootContainerCheck().
OnBeforeDropAddItem()
virtual void GlobalScript::OnBeforeDropAddItem (Player const * , Loot & , bool , uint16 , LootStoreItem * , LootStore const &) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeDropAddItem().
OnBeforeLootEqualChanced()
virtual bool GlobalScript::OnBeforeLootEqualChanced (Player const * , std::list< LootStoreItem * > , Loot & , LootStore const &) inline virtual
{ return true; }
Referenced by ScriptMgr::OnBeforeLootEqualChanced().
OnBeforeSetBossState()
virtual void GlobalScript::OnBeforeSetBossState (uint32 , EncounterState , EncounterState , Map *) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeSetBossState().
OnBeforeUpdateArenaPoints()
virtual void GlobalScript::OnBeforeUpdateArenaPoints (ArenaTeam * , std::map< ObjectGuid, uint32 > &) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeUpdateArenaPoints().
OnBeforeWorldObjectSetPhaseMask()
virtual void GlobalScript::OnBeforeWorldObjectSetPhaseMask (WorldObject const * , uint32 & , uint32 & , bool & , bool &) inline virtual
{ }
Referenced by ScriptMgr::OnBeforeWorldObjectSetPhaseMask().
OnInitializeLockedDungeons()
virtual void GlobalScript::OnInitializeLockedDungeons (Player * , uint8 & , uint32 & , lfg::LFGDungeonData const *) inline virtual
{ }
Referenced by ScriptMgr::OnInitializeLockedDungeons().
OnInstanceIdRemoved()
virtual void GlobalScript::OnInstanceIdRemoved (uint32) inline virtual
{ }
Referenced by ScriptMgr::OnInstanceIdRemoved().
OnIsAffectedBySpellModCheck()
virtual bool GlobalScript::OnIsAffectedBySpellModCheck (SpellInfo const * , SpellInfo const * , SpellModifier const *) inline virtual
{ return true; };
Referenced by ScriptMgr::OnIsAffectedBySpellModCheck().
OnItemDelFromDB()
virtual void GlobalScript::OnItemDelFromDB (CharacterDatabaseTransaction , ObjectGuid::LowType) inline virtual
{ }
Referenced by ScriptMgr::OnGlobalItemDelFromDB().
OnItemRoll()
virtual bool GlobalScript::OnItemRoll (Player const * , LootStoreItem const * , float & , Loot & , LootStore const &) inline virtual
{ return true; };
Referenced by ScriptMgr::OnItemRoll().
OnLoadSpellCustomAttr()
virtual void GlobalScript::OnLoadSpellCustomAttr (SpellInfo *) inline virtual
{ }
Referenced by ScriptMgr::OnLoadSpellCustomAttr().
OnMirrorImageDisplayItem()
virtual void GlobalScript::OnMirrorImageDisplayItem (Item const * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnGlobalMirrorImageDisplayItem().
OnSpellHealingBonusTakenNegativeModifiers()
virtual bool GlobalScript::OnSpellHealingBonusTakenNegativeModifiers (Unit const * , Unit const * , SpellInfo const * , float &) inline virtual
{ return false; };
Referenced by ScriptMgr::OnSpellHealingBonusTakenNegativeModifiers().