AzerothCore: npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI Struct Reference
npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI Struct Reference
Public Member Functions
npc_ulduar_expedition_engineerAI (Creature *pCreature)
void Reset () override
void SetData (uint32 id, uint32) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
bool working
uint16 timer
ObjectGuid fixingGUID
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_ulduar_expedition_engineerAI()
npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::npc_ulduar_expedition_engineerAI (Creature * pCreature) inline
                                                              : NullCreatureAI(pCreature)
        {
            pInstance = me->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), CreatureAI::me, and pInstance.
Member Function Documentation
Reset()
void npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            working = false;
            timer = 0;
            fixingGUID.Clear();
        }
References ObjectGuid::Clear(), fixingGUID, timer, and working.
Referenced by SetData(), and UpdateAI().
SetData()
void npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::SetData (uint32 id, uint32) inline override virtual
Reimplemented from UnitAI.
        {
            switch (id)
            {
                case 1: // start/resume repairing
                    working = true;
                    timer = 0;
                    fixingGUID.Clear();
                    break;
                case 2: // stop repairing
                    Reset();
                    me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_STAND);
                    me->GetMotionMaster()->MoveTargetedHome();
                    break;
            }
        }
References ObjectGuid::Clear(), EMOTE_STATE_STAND, fixingGUID, Unit::GetMotionMaster(), CreatureAI::me, MotionMaster::MoveTargetedHome(), Reset(), Unit::SetUInt32Value(), timer, UNIT_NPC_EMOTESTATE, and working.
UpdateAI()
void npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from NullCreatureAI.
        {
            if (working)
            {
                if (timer <= diff)
                {
                    timer = 3000;
                    if (fixingGUID)
                    {
                        if (Creature* c = ObjectAccessor::GetCreature(*me, fixingGUID))
                            if (me->GetExactDist2dSq(c) <= 25.0f)
{
                                if (me->GetUInt32Value(UNIT_NPC_EMOTESTATE) != EMOTE_STATE_WORK )
                                    me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_WORK);
                                if (std::fabs(me->GetOrientation() - me->GetAngle(c)) > M_PI / 4)
                                    me->SetFacingToObject(c);
                                c->AI()->SetData(2, 0);
                                if (c->AI()->GetData(2))
                                    fixingGUID.Clear();
                            }
                    }
                    if (!fixingGUID)
                    {
                        Creature* razorscale = nullptr;
                        if (ObjectGuid rsGUID = pInstance->GetGuidData(TYPE_RAZORSCALE))
                            razorscale = ObjectAccessor::GetCreature(*me, rsGUID);
                        if (!razorscale || !razorscale->IsInCombat())
{
                            Reset();
                            me->GetMotionMaster()->MoveTargetedHome();
                            return;
                        }
                        for( int i = 0; i < 4; ++i )
                            if (ObjectGuid fs_GUID = pInstance->GetGuidData(DATA_HARPOON_FIRE_STATE_1 + i))
                                if (Creature* fs = ObjectAccessor::GetCreature(*me, fs_GUID))
                                    if (!fs->AI()->GetData(2))
{
                                        float a = rand_norm() * M_PI;
                                        me->GetMotionMaster()->MovePoint(0, fs->GetPositionX() + 3.0f * cos(a), fs->GetPositionY() + 3.0f * std::sin(a), fs->GetPositionZ());
                                        fixingGUID = fs->GetGUID();
                                        return;
                                    }
                        Reset(); // all harpoons repaired
                        me->GetMotionMaster()->MoveTargetedHome();
                    }
                }
                else
                    timer -= diff;
            }
            else if (me->GetUInt32Value(UNIT_NPC_EMOTESTATE) == EMOTE_STATE_WORK)
                me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_STAND);
        }
References ObjectGuid::Clear(), DATA_HARPOON_FIRE_STATE_1, EMOTE_STATE_STAND, EMOTE_STATE_WORK, fixingGUID, Position::GetAngle(), ObjectAccessor::GetCreature(), Position::GetExactDist2dSq(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetOrientation(), Object::GetUInt32Value(), Unit::IsInCombat(), CreatureAI::me, MotionMaster::MovePoint(), MotionMaster::MoveTargetedHome(), pInstance, rand_norm(), Reset(), Unit::SetFacingToObject(), Unit::SetUInt32Value(), timer, TYPE_RAZORSCALE, UNIT_NPC_EMOTESTATE, and working.
Member Data Documentation
fixingGUID
ObjectGuid npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::fixingGUID
Referenced by Reset(), SetData(), and UpdateAI().
pInstance
InstanceScript* npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::pInstance
Referenced by npc_ulduar_expedition_engineerAI(), and UpdateAI().
timer
uint16 npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::timer
Referenced by Reset(), SetData(), and UpdateAI().
working
bool npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::working
Referenced by Reset(), SetData(), and UpdateAI().