AzerothCore: Acore::ChatCommands::AccountIdentifier Struct Reference
Acore::ChatCommands::AccountIdentifier Struct Reference
#include "ChatCommandTags.h"
Public Types
using value_type = uint32
Public Types inherited from Acore::Impl::ChatCommands::ContainerTag
using ChatCommandResult = Acore::Impl::ChatCommands::ChatCommandResult
Public Member Functions
operator uint32 () const
operator std::string const & () const
operator std::string_view () const
uint32 GetID () const
std::string const & GetName () const
ChatCommandResult TryConsume (ChatHandler const *handler, std::string_view args)
Private Attributes
uint32 _id
std::string _name
Detailed Description
Member Typedef Documentation
value_type
using Acore::ChatCommands::AccountIdentifier::value_type = uint32
Member Function Documentation
GetID()
uint32 Acore::ChatCommands::AccountIdentifier::GetID () const inline
{ return _id; }
Referenced by account_commandscript::HandleAccountSetEmailCommand(), character_commandscript::HandlePDumpCopyCommand(), and character_commandscript::HandlePDumpLoadCommand().
GetName()
std::string const & Acore::ChatCommands::AccountIdentifier::GetName () const inline
{ return _name; }
Referenced by account_commandscript::HandleAccountSetEmailCommand(), character_commandscript::HandlePDumpCopyCommand(), and character_commandscript::HandlePDumpLoadCommand().
operator std::string const &()
Acore::ChatCommands::AccountIdentifier::operator std::string const & () const inline
{ return _name; }
operator std::string_view()
Acore::ChatCommands::AccountIdentifier::operator std::string_view () const inline
{ return { _name }; }
operator uint32()
Acore::ChatCommands::AccountIdentifier::operator uint32 () const inline
{ return _id; }
TryConsume()
ChatCommandResult Acore::ChatCommands::AccountIdentifier::TryConsume (ChatHandler const * handler, std::string_view args)
{
    std::string_view text;
    ChatCommandResult next = ArgInfo<std::string_view>::TryConsume(text, handler, args);
    if (!next)
        return next;
    // first try parsing as account name
    _name.assign(text);
    if (!Utf8ToUpperOnlyLatin(_name))
        return GetAcoreString(handler, LANG_CMDPARSER_INVALID_UTF8);
    _id = AccountMgr::GetId(_name);
    if (_id) // account with name exists, we are done
        return next;
    // try parsing as account id instead
    Optional<uint32> id = Acore::StringTo<uint32>(text, 10);
    if (!id)
        return FormatAcoreString(handler, LANG_CMDPARSER_ACCOUNT_NAME_NO_EXIST, _name);
    _id = *id;
    if (AccountMgr::GetName(_id, _name))
        return next;
    else
        return FormatAcoreString(handler, LANG_CMDPARSER_ACCOUNT_ID_NO_EXIST, _id);
}
References Acore::Impl::ChatCommands::FormatAcoreString(), Acore::Impl::ChatCommands::GetAcoreString(), AccountMgr::GetId(), AccountMgr::GetName(), LANG_CMDPARSER_ACCOUNT_ID_NO_EXIST, LANG_CMDPARSER_ACCOUNT_NAME_NO_EXIST, LANG_CMDPARSER_INVALID_UTF8, and Utf8ToUpperOnlyLatin().
Member Data Documentation
_id
uint32 Acore::ChatCommands::AccountIdentifier::_id private
_name
std::string Acore::ChatCommands::AccountIdentifier::_name private