AzerothCore: boss_archimonde::boss_archimondeAI Struct Reference
boss_archimonde::boss_archimondeAI Struct Reference
Public Member Functions
boss_archimondeAI (Creature *creature)
void Reset () override
void DoCastProtection ()
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void KilledUnit (Unit *victim) override
void GainSoulCharge (Player *victim)
void JustDied (Unit *) override
bool CanUseFingerOfDeath ()
void JustSummoned (Creature *summoned) override
void DoCastDoomfire ()
void SummonDoomfire (Unit *target)
void UnleashSoulCharge ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
EventMap events
ObjectGuid DoomfireSpiritGUID
ObjectGuid WorldTreeGUID
uint8 SoulChargeCount
uint8 WispCount
SummonList summons
bool Enraged
bool BelowTenPercent
bool HasProtected
bool IsChanneling
std::list< Unit * > fingerOfDeathTargets
std::list< Unit * > spellEffectTargets
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
bool _ProccessHealthCheckEvent (uint8 healthPct, uint32 damage, std::function< void()> exec) const
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
TaskScheduler scheduler
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_archimondeAI()
boss_archimonde::boss_archimondeAI::boss_archimondeAI (Creature * creature) inline
                                              : BossAI(creature, BOSS_ARCHIMONDE), summons(me),
            Enraged(false), BelowTenPercent(false), HasProtected(false), IsChanneling(false)
        {
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
CanUseFingerOfDeath()
bool boss_archimonde::boss_archimondeAI::CanUseFingerOfDeath () inline
        {
            // Cast finger of death below 10% health
            if (BelowTenPercent)
                return true;
            if (me->IsAlive())
            {
                /* Reset the list before checking for new targets
                 * else we will be using old targets that could have
                 * been distant but are no longer.*/
                fingerOfDeathTargets.clear();
                // First we check if our current victim is in melee range or not.
                Unit* victim = me->GetVictim();
                if (victim && me->IsWithinMeleeRange(victim))
                    return false;
                ThreatContainer::StorageType const& threatlist = me->GetThreatMgr().GetThreatList();
                if (threatlist.empty())
                    return false;
                auto itr = threatlist.begin();
                for (; itr != threatlist.end(); ++itr)
                {
                    Unit* unit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid());
                    if (unit && unit->IsAlive() && me->IsWithinMeleeRange(unit))
                        fingerOfDeathTargets.push_back(unit);
                }
                /* Previous check searched for targets in meele range and
                 * added it to targets list. If there are no targets in meele
                 * range return true, which makes Archimonde cast Finger of Death.
                */
                return fingerOfDeathTargets.empty();
            }
            return false;
        }
References BelowTenPercent, fingerOfDeathTargets, ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::IsAlive(), Unit::IsWithinMeleeRange(), and ScriptedAI::me.
Referenced by UpdateAI().
DoCastDoomfire()
void boss_archimonde::boss_archimondeAI::DoCastDoomfire () inline
        {
            // Three doomfire can be up at the same time
            Talk(SAY_DOOMFIRE);
            Unit* temp = SelectTarget(SelectTargetMethod::Random, 1);
            if (!temp)
                temp = me->GetVictim();
            //replace with spell cast 31903 once implicitTarget 73 implemented
            SummonDoomfire(temp);
        }
References Unit::GetVictim(), ScriptedAI::me, SAY_DOOMFIRE, UnitAI::SelectTarget(), and SummonDoomfire().
Referenced by UpdateAI().
DoCastProtection()
void boss_archimonde::boss_archimondeAI::DoCastProtection () inline
        {
            // lets get spell info
            SpellInfo const* info = sSpellMgr->GetSpellInfo(SPELL_PROTECTION_OF_ELUNE);
            if (!info)
                return;
            // Now lets get archimode threat list
            ThreatContainer::StorageType const& t_list = me->GetThreatMgr().GetThreatList();
            if (t_list.empty())
                return;
            ThreatContainer::StorageType::const_iterator itr = t_list.begin();
            if (Unit* target = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid()))
                if (target->IsAlive() && target->GetTypeId() == TYPEID_PLAYER)
                    spellEffectTargets.push_back(target);
            for (auto iter = spellEffectTargets.begin(); iter != spellEffectTargets.end(); ++iter)
                if (Unit* target = *iter)
                {
                    target->AddAura(SPELL_PROTECTION_OF_ELUNE, target);
                    // Immunity against Hand of death
                    target->ApplySpellImmune(SPELL_HAND_OF_DEATH, IMMUNITY_ID, SPELL_HAND_OF_DEATH, true);
                    target->ApplySpellImmune(0, IMMUNITY_ID, SPELL_HAND_OF_DEATH, true);
                }
        }
References ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), ObjectAccessor::GetUnit(), IMMUNITY_ID, ScriptedAI::me, SPELL_HAND_OF_DEATH, SPELL_PROTECTION_OF_ELUNE, spellEffectTargets, sSpellMgr, and TYPEID_PLAYER.
Referenced by UpdateAI().
GainSoulCharge()
void boss_archimonde::boss_archimondeAI::GainSoulCharge (Player * victim) inline
        {
            switch (victim->getClass())
            {
                case CLASS_PRIEST:
                case CLASS_PALADIN:
                case CLASS_WARLOCK:
                    victim->CastSpell(me, SPELL_SOUL_CHARGE_RED, true);
                    break;
                case CLASS_MAGE:
                case CLASS_ROGUE:
                case CLASS_WARRIOR:
                    victim->CastSpell(me, SPELL_SOUL_CHARGE_YELLOW, true);
                    break;
                case CLASS_DRUID:
                case CLASS_SHAMAN:
                case CLASS_HUNTER:
                    victim->CastSpell(me, SPELL_SOUL_CHARGE_GREEN, true);
                    break;
            }
            events.ScheduleEvent(EVENT_SPELL_UNLEASH_SOUL_CHARGES, urand(2000, 10000));
            ++SoulChargeCount;
        }
References Unit::CastSpell(), CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, EVENT_SPELL_UNLEASH_SOUL_CHARGES, Unit::getClass(), ScriptedAI::me, SoulChargeCount, SPELL_SOUL_CHARGE_GREEN, SPELL_SOUL_CHARGE_RED, SPELL_SOUL_CHARGE_YELLOW, and urand().
Referenced by KilledUnit().
JustDied()
void boss_archimonde::boss_archimondeAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            Talk(SAY_DEATH);
            instance->SetData(DATA_ARCHIMONDEEVENT, DONE);
            instance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, me->GetEntry(), 1, me);
            // Reset scheduled events
            events.CancelEvent(EVENT_SPELL_FEAR);
            events.CancelEvent(EVENT_SPELL_AIR_BURST);
            events.CancelEvent(EVENT_SPELL_GRIP_OF_THE_LEGION);
            events.CancelEvent(EVENT_SPELL_UNLEASH_SOUL_CHARGES);
            events.CancelEvent(EVENT_SPELL_DOOMFIRE);
            events.CancelEvent(EVENT_SPELL_FINGER_OF_DEATH);
            events.CancelEvent(EVENT_SPELL_HAND_OF_DEATH);
            events.CancelEvent(EVENT_SPELL_PROTECTION_OF_ELUNE);
            events.CancelEvent(EVENT_ENRAGE);
            spellEffectTargets.clear();
            fingerOfDeathTargets.clear();
            summons.DespawnAll();
        }
References ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, DATA_ARCHIMONDEEVENT, SummonList::DespawnAll(), DONE, InstanceScript::DoUpdateAchievementCriteria(), EVENT_ENRAGE, EVENT_SPELL_AIR_BURST, EVENT_SPELL_DOOMFIRE, EVENT_SPELL_FEAR, EVENT_SPELL_FINGER_OF_DEATH, EVENT_SPELL_GRIP_OF_THE_LEGION, EVENT_SPELL_HAND_OF_DEATH, EVENT_SPELL_PROTECTION_OF_ELUNE, EVENT_SPELL_UNLEASH_SOUL_CHARGES, fingerOfDeathTargets, Object::GetEntry(), instance, ScriptedAI::me, SAY_DEATH, ZoneScript::SetData(), spellEffectTargets, and summons.
JustEngagedWith()
void boss_archimonde::boss_archimondeAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            me->InterruptSpell(CURRENT_CHANNELED_SPELL);
            Talk(SAY_AGGRO);
            DoZoneInCombat();
            instance->SetData(DATA_ARCHIMONDEEVENT, IN_PROGRESS);
            events.ScheduleEvent(EVENT_SPELL_AIR_BURST, urand(25000, 35000));
            events.ScheduleEvent(EVENT_SPELL_DOOMFIRE, urand(10000, 20000));
            events.ScheduleEvent(EVENT_SPELL_FEAR, 42000);
            events.ScheduleEvent(EVENT_SPELL_GRIP_OF_THE_LEGION, 2000);
            events.ScheduleEvent(EVENT_SPELL_FINGER_OF_DEATH, 1000);
        }
References CURRENT_CHANNELED_SPELL, DATA_ARCHIMONDEEVENT, CreatureAI::DoZoneInCombat(), EVENT_SPELL_AIR_BURST, EVENT_SPELL_DOOMFIRE, EVENT_SPELL_FEAR, EVENT_SPELL_FINGER_OF_DEATH, EVENT_SPELL_GRIP_OF_THE_LEGION, IN_PROGRESS, instance, Unit::InterruptSpell(), ScriptedAI::me, SAY_AGGRO, ZoneScript::SetData(), and urand().
JustSummoned()
void boss_archimonde::boss_archimondeAI::JustSummoned (Creature * summoned) inline override virtual
Reimplemented from BossAI.
        {
            summons.Summon(summoned);
            if (summoned->GetEntry() == CREATURE_ANCIENT_WISP)
                summoned->AI()->AttackStart(me);
            else
            {
                summoned->SetFaction(me->GetFaction());
                summoned->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                summoned->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            }
            if (summoned->GetEntry() == CREATURE_DOOMFIRE_SPIRIT)
            {
                DoomfireSpiritGUID = summoned->GetGUID();
            }
            if (summoned->GetEntry() == CREATURE_DOOMFIRE)
            {
                summoned->CastSpell(summoned, SPELL_DOOMFIRE_SPAWN, false);
                summoned->CastSpell(summoned, SPELL_DOOMFIRE, true, 0, 0, me->GetGUID());
                if (Unit* DoomfireSpirit = ObjectAccessor::GetUnit(*me, DoomfireSpiritGUID))
                {
                    summoned->GetMotionMaster()->MoveFollow(DoomfireSpirit, 0.0f, 0.0f);
                    DoomfireSpiritGUID.Clear();
                }
            }
        }
References Creature::AI(), UnitAI::AttackStart(), Unit::CastSpell(), ObjectGuid::Clear(), CREATURE_ANCIENT_WISP, CREATURE_DOOMFIRE, CREATURE_DOOMFIRE_SPIRIT, DoomfireSpiritGUID, Object::GetEntry(), Unit::GetFaction(), Object::GetGUID(), Unit::GetMotionMaster(), ObjectAccessor::GetUnit(), ScriptedAI::me, MotionMaster::MoveFollow(), Unit::SetFaction(), Unit::SetUnitFlag(), SPELL_DOOMFIRE, SPELL_DOOMFIRE_SPAWN, SummonList::Summon(), summons, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
KilledUnit()
void boss_archimonde::boss_archimondeAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_SLAY);
            if (victim && victim->GetTypeId() == TYPEID_PLAYER)
                GainSoulCharge(victim->ToPlayer());
        }
References GainSoulCharge(), Object::GetTypeId(), SAY_SLAY, Object::ToPlayer(), and TYPEID_PLAYER.
Reset()
void boss_archimonde::boss_archimondeAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            instance->SetData(DATA_ARCHIMONDEEVENT, NOT_STARTED);
            DoomfireSpiritGUID.Clear();
            WorldTreeGUID.Clear();
            WispCount = 0;
            Enraged = false;
            BelowTenPercent = false;
            HasProtected = false;
            IsChanneling = false;
            // Reset player's immunity to Spells
            for (auto it = spellEffectTargets.begin(); it != spellEffectTargets.end(); ++it)
            {
                Unit* affected_unit = ObjectAccessor::GetUnit(*me, (*it)->GetGUID());
                // Remove Immunity against Hand of death
                affected_unit->ApplySpellImmune(SPELL_HAND_OF_DEATH, IMMUNITY_ID, SPELL_HAND_OF_DEATH, false);
                affected_unit->ApplySpellImmune(0, IMMUNITY_ID, SPELL_HAND_OF_DEATH, false);
            }
            spellEffectTargets.clear();
            fingerOfDeathTargets.clear();
            summons.DespawnAll();
            events.ScheduleEvent(EVENT_DRAIN_WORLD_TREE, 0);
        }
References Unit::ApplySpellImmune(), BelowTenPercent, ObjectGuid::Clear(), DATA_ARCHIMONDEEVENT, SummonList::DespawnAll(), DoomfireSpiritGUID, Enraged, EVENT_DRAIN_WORLD_TREE, fingerOfDeathTargets, Object::GetGUID(), ObjectAccessor::GetUnit(), HasProtected, IMMUNITY_ID, instance, IsChanneling, ScriptedAI::me, NOT_STARTED, ZoneScript::SetData(), SPELL_HAND_OF_DEATH, spellEffectTargets, summons, WispCount, and WorldTreeGUID.
SummonDoomfire()
void boss_archimonde::boss_archimondeAI::SummonDoomfire (Unit * target) inline
        {
            Unit* doomfire1 = me->SummonCreature(CREATURE_DOOMFIRE_SPIRIT,
                                                 target->GetPositionX() + 15.0f, target->GetPositionY() + 15.0f, target->GetPositionZ(), 0,
                                                 TEMPSUMMON_TIMED_DESPAWN, 27000);
            Unit* doomfire2 = me->SummonCreature(CREATURE_DOOMFIRE,
                                                 target->GetPositionX() - 15.0f, target->GetPositionY() - 15.0f, target->GetPositionZ(), 0,
                                                 TEMPSUMMON_TIMED_DESPAWN, 27000);
            doomfire1->SetVisible(false);
            doomfire2->SetVisible(false);
        }
References CREATURE_DOOMFIRE, CREATURE_DOOMFIRE_SPIRIT, Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, Unit::SetVisible(), WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
Referenced by DoCastDoomfire().
UnleashSoulCharge()
void boss_archimonde::boss_archimondeAI::UnleashSoulCharge () inline
        {
            me->InterruptNonMeleeSpells(false);
            uint32 chargeSpell = 0;
            uint32 unleashSpell = 0;
            switch (urand(0, 2))
            {
                case 0:
                    chargeSpell = SPELL_SOUL_CHARGE_RED;
                    unleashSpell = SPELL_UNLEASH_SOUL_RED;
                    break;
                case 1:
                    chargeSpell = SPELL_SOUL_CHARGE_YELLOW;
                    unleashSpell = SPELL_UNLEASH_SOUL_YELLOW;
                    break;
                case 2:
                    chargeSpell = SPELL_SOUL_CHARGE_GREEN;
                    unleashSpell = SPELL_UNLEASH_SOUL_GREEN;
                    break;
            }
            if (me->HasAura(chargeSpell))
            {
                me->RemoveAuraFromStack(chargeSpell);
                DoCastVictim(unleashSpell);
                SoulChargeCount--;
            }
        }
References UnitAI::DoCastVictim(), Unit::HasAura(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, Unit::RemoveAuraFromStack(), SoulChargeCount, SPELL_SOUL_CHARGE_GREEN, SPELL_SOUL_CHARGE_RED, SPELL_SOUL_CHARGE_YELLOW, SPELL_UNLEASH_SOUL_GREEN, SPELL_UNLEASH_SOUL_RED, SPELL_UNLEASH_SOUL_YELLOW, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_archimonde::boss_archimondeAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
        {
            events.Update(diff);
            // Event for draining the tree
            if (!me->IsInCombat())
            {
                // Do not let the raid skip straight to Archimonde. Visible and hostile ONLY if Azagalor is finished.
                if ((instance->GetData(DATA_AZGALOREVENT) < DONE) && (me->IsVisible() || (me->GetFaction() != FACTION_FRIENDLY)))
                {
                    me->SetVisible(false);
                    me->SetFaction(FACTION_FRIENDLY);
                }
                if ((instance->GetData(DATA_AZGALOREVENT) >= DONE) && (!me->IsVisible() || (me->GetFaction() == FACTION_FRIENDLY)))
                {
                    me->SetFaction(FACTION_DRAGONKIN);
                    me->SetVisible(true);
                }
                switch (events.ExecuteEvent())
                {
                    case EVENT_DRAIN_WORLD_TREE:
                        if (!IsChanneling)
{
                            Creature* temp = me->SummonCreature(CREATURE_CHANNEL_TARGET, NordrassilLoc, TEMPSUMMON_TIMED_DESPAWN, 1200000);
                            if (temp)
                                WorldTreeGUID = temp->GetGUID();
                            if (Unit* Nordrassil = ObjectAccessor::GetUnit(*me, WorldTreeGUID))
{
                                Nordrassil->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                                Nordrassil->SetDisplayId(11686);
                                DoCast(Nordrassil, SPELL_DRAIN_WORLD_TREE);
                                IsChanneling = true;
                            }
                        }
                        if (Unit* Nordrassil = ObjectAccessor::GetUnit(*me, WorldTreeGUID))
                            Nordrassil->CastSpell(me, SPELL_DRAIN_WORLD_TREE_2, true);
                        break;
                }
            }
            if (!UpdateVictim())
                return;
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            if (me->HealthBelowPct(10) && !BelowTenPercent)
                events.ScheduleEvent(EVENT_BELOW_10_PERCENT_HP, 0);
            switch (events.ExecuteEvent())
            {
                case EVENT_CHECK_WORLD_TREE_DISTANCE:
                    {
                        // If Archimonde is too close to the world tree this will ENRAGE him
                        Creature* Check = me->SummonCreature(CREATURE_CHANNEL_TARGET, NordrassilLoc, TEMPSUMMON_TIMED_DESPAWN, 2000);
                        if (Check)
{
                            Check->SetVisible(false);
                            if (me->IsWithinDistInMap(Check, 75))
{
                                events.ScheduleEvent(EVENT_TOO_CLOSE_TO_WORLD_TREE, 0);
                                break;
                            }
                        }
                        events.RepeatEvent(5000);
                        break;
                    }
                case EVENT_BELOW_10_PERCENT_HP:
                    DoCastProtection();     // Protection of Elune against Finger and Hand of Death
                    BelowTenPercent = true;
                    me->GetMotionMaster()->Clear(false);
                    me->GetMotionMaster()->MoveIdle();
                    events.ScheduleEvent(EVENT_ENRAGE, 0);
                    events.ScheduleEvent(EVENT_ENRAGE_ROOT, 0);
                    events.ScheduleEvent(EVENT_SUMMON_WISPS, 1000);
                    events.ScheduleEvent(EVENT_SPELL_HAND_OF_DEATH, 1500);
                    events.ScheduleEvent(EVENT_SPELL_FINGER_OF_DEATH, 2500);
                    break;
                case EVENT_SUMMON_WISPS:
                    // If there are more than 30 Wisps then kill Archimonde
                    if (WispCount >= 30)
                    {
                        Unit::DealDamage(me, me, me->GetHealth(), nullptr, DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, nullptr, false);
                        return;     // Finish the encounter and no more event repeat
                    }
                    DoSpawnCreature(CREATURE_ANCIENT_WISP, float(rand() % 40), float(rand() % 40), 0, 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 15000);
                    ++WispCount;
                    events.ScheduleEvent(EVENT_SUMMON_WISPS, 1500);
                    break;
                case EVENT_SPELL_HAND_OF_DEATH:
                    DoCastVictim(SPELL_RED_SKY_EFFECT);
                    DoCastVictim(SPELL_HAND_OF_DEATH);
                    events.ScheduleEvent(EVENT_SPELL_HAND_OF_DEATH, 3000);
                    break;
                case EVENT_SPELL_FINGER_OF_DEATH:
                    if (CanUseFingerOfDeath())
                    {
                        Unit* target = SelectTarget(SelectTargetMethod::Random, 0);
                        DoCast(target, SPELL_FINGER_OF_DEATH);
                        DoCastVictim(SPELL_RED_SKY_EFFECT);
                    }
                    events.ScheduleEvent(EVENT_SPELL_FINGER_OF_DEATH, 3500);
                    break;
                case EVENT_SPELL_GRIP_OF_THE_LEGION:
                    DoCast(SelectTarget(SelectTargetMethod::Random, 0), SPELL_GRIP_OF_THE_LEGION);
                    events.ScheduleEvent(EVENT_SPELL_GRIP_OF_THE_LEGION, urand(5000, 25000));
                    break;
                case EVENT_SPELL_AIR_BURST:
                    Talk(SAY_AIR_BURST);
                    DoCast(SelectTarget(SelectTargetMethod::Random, 0), SPELL_AIR_BURST);
                    events.ScheduleEvent(EVENT_SPELL_AIR_BURST, urand(25000, 40000));
                    break;
                case EVENT_SPELL_FEAR:
                    DoCastVictim(SPELL_FEAR);
                    events.ScheduleEvent(EVENT_SPELL_FEAR, 42000);
                    break;
                case EVENT_SPELL_DOOMFIRE:
                    DoCastDoomfire();
                    events.ScheduleEvent(EVENT_SPELL_DOOMFIRE, 20000);
                    break;
                case EVENT_SPELL_UNLEASH_SOUL_CHARGES:
                    UnleashSoulCharge();
                    break;
                case EVENT_ENRAGE:
                    Talk(SAY_ENRAGE);
                    break;
                case EVENT_TOO_CLOSE_TO_WORLD_TREE:
                    // People dragged the boss near the check and now wipe
                    events.ScheduleEvent(EVENT_ENRAGE, 0);
                    events.ScheduleEvent(EVENT_SPELL_HAND_OF_DEATH, 1000);
                    break;
                case EVENT_ENRAGE_ROOT:
                    me->GetMotionMaster()->Clear(false);
                    me->GetMotionMaster()->MoveIdle();
                    break;
            }
            DoMeleeAttackIfReady();
        }
References BelowTenPercent, CanUseFingerOfDeath(), MotionMaster::Clear(), CREATURE_ANCIENT_WISP, CREATURE_CHANNEL_TARGET, DATA_AZGALOREVENT, Unit::DealDamage(), DIRECT_DAMAGE, UnitAI::DoCast(), DoCastDoomfire(), DoCastProtection(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), DONE, ScriptedAI::DoSpawnCreature(), EVENT_BELOW_10_PERCENT_HP, EVENT_CHECK_WORLD_TREE_DISTANCE, EVENT_DRAIN_WORLD_TREE, EVENT_ENRAGE, EVENT_ENRAGE_ROOT, EVENT_SPELL_AIR_BURST, EVENT_SPELL_DOOMFIRE, EVENT_SPELL_FEAR, EVENT_SPELL_FINGER_OF_DEATH, EVENT_SPELL_GRIP_OF_THE_LEGION, EVENT_SPELL_HAND_OF_DEATH, EVENT_SPELL_UNLEASH_SOUL_CHARGES, EVENT_SUMMON_WISPS, EVENT_TOO_CLOSE_TO_WORLD_TREE, FACTION_DRAGONKIN, FACTION_FRIENDLY, ZoneScript::GetData(), Unit::GetFaction(), Object::GetGUID(), Unit::GetHealth(), Unit::GetMotionMaster(), ObjectAccessor::GetUnit(), Unit::HasUnitState(), Unit::HealthBelowPct(), instance, IsChanneling, Unit::IsInCombat(), Unit::IsVisible(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, MotionMaster::MoveIdle(), NordrassilLoc, SAY_AIR_BURST, SAY_ENRAGE, UnitAI::SelectTarget(), Unit::SetFaction(), Unit::SetVisible(), SPELL_AIR_BURST, SPELL_DRAIN_WORLD_TREE, SPELL_DRAIN_WORLD_TREE_2, SPELL_FEAR, SPELL_FINGER_OF_DEATH, SPELL_GRIP_OF_THE_LEGION, SPELL_HAND_OF_DEATH, SPELL_RED_SKY_EFFECT, SPELL_SCHOOL_MASK_NORMAL, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_CASTING, UnleashSoulCharge(), CreatureAI::UpdateVictim(), urand(), WispCount, and WorldTreeGUID.
Member Data Documentation
BelowTenPercent
bool boss_archimonde::boss_archimondeAI::BelowTenPercent
Referenced by CanUseFingerOfDeath(), Reset(), and UpdateAI().
DoomfireSpiritGUID
ObjectGuid boss_archimonde::boss_archimondeAI::DoomfireSpiritGUID
Referenced by JustSummoned(), and Reset().
Enraged
bool boss_archimonde::boss_archimondeAI::Enraged
Referenced by Reset().
events
EventMap boss_archimonde::boss_archimondeAI::events
fingerOfDeathTargets
std::list<Unit*> boss_archimonde::boss_archimondeAI::fingerOfDeathTargets
Referenced by CanUseFingerOfDeath(), JustDied(), and Reset().
HasProtected
bool boss_archimonde::boss_archimondeAI::HasProtected
Referenced by Reset().
instance
InstanceScript* boss_archimonde::boss_archimondeAI::instance
Referenced by boss_archimondeAI(), JustDied(), JustEngagedWith(), Reset(), and UpdateAI().
IsChanneling
bool boss_archimonde::boss_archimondeAI::IsChanneling
Referenced by Reset(), and UpdateAI().
SoulChargeCount
uint8 boss_archimonde::boss_archimondeAI::SoulChargeCount
Referenced by GainSoulCharge(), and UnleashSoulCharge().
spellEffectTargets
std::list<Unit*> boss_archimonde::boss_archimondeAI::spellEffectTargets
Referenced by DoCastProtection(), JustDied(), and Reset().
summons
SummonList boss_archimonde::boss_archimondeAI::summons
Referenced by JustDied(), JustSummoned(), and Reset().
WispCount
uint8 boss_archimonde::boss_archimondeAI::WispCount
Referenced by Reset(), and UpdateAI().
WorldTreeGUID
ObjectGuid boss_archimonde::boss_archimondeAI::WorldTreeGUID
Referenced by Reset(), and UpdateAI().