AzerothCore: Acore::Crypto::ARC4 Class Reference
Acore::Crypto::ARC4 Class Reference
#include "ARC4.h"
Public Member Functions
ARC4 ()
~ARC4 ()
void Init (uint8 const *seed, size_t len)
template<typename Container >
void Init (Container const &c)
void UpdateData (uint8 *data, size_t len)
template<typename Container >
void UpdateData (Container &c)
Private Attributes
EVP_CIPHER_CTX * _ctx
Detailed Description
Constructor & Destructor Documentation
ARC4()
Acore::Crypto::ARC4::ARC4 ()
                      : _ctx(EVP_CIPHER_CTX_new())
{
#if OPENSSL_VERSION_NUMBER >= 0x30000000L
    _cipher = EVP_CIPHER_fetch(nullptr, "RC4", nullptr);
#else
    EVP_CIPHER const* _cipher = EVP_rc4();
#endif
    EVP_CIPHER_CTX_init(_ctx);
    int result = EVP_EncryptInit_ex(_ctx, _cipher, nullptr, nullptr, nullptr);
    ASSERT(result == 1);
}
References _ctx, and ASSERT.
~ARC4()
Acore::Crypto::ARC4::~ARC4 ()
{
    EVP_CIPHER_CTX_free(_ctx);
#if OPENSSL_VERSION_NUMBER >= 0x30000000L
    EVP_CIPHER_free(_cipher);
#endif
}
Member Function Documentation
Init() [1/2]
template<typename Container > void Acore::Crypto::ARC4::Init (Container const & c) inline
{ Init(std::data(c), std::size(c)); }
References Init().
Referenced by Init().
Init() [2/2]
void Acore::Crypto::ARC4::Init (uint8 const * seed, size_t len)
{
    int result1 = EVP_CIPHER_CTX_set_key_length(_ctx, len);
    ASSERT(result1 == 1);
    int result2 = EVP_EncryptInit_ex(_ctx, nullptr, nullptr, seed, nullptr);
    ASSERT(result2 == 1);
}
References ASSERT.
Referenced by WardenMac::HandleHashResult(), WardenWin::HandleHashResult(), AuthCrypt::Init(), WardenMac::Init(), and WardenWin::Init().
UpdateData() [1/2]
template<typename Container > void Acore::Crypto::ARC4::UpdateData (Container & c) inline
{ UpdateData(std::data(c), std::size(c)); }
References UpdateData().
Referenced by UpdateData().
UpdateData() [2/2]
void Acore::Crypto::ARC4::UpdateData (uint8 * data, size_t len)
{
    int outlen = 0;
    int result1 = EVP_EncryptUpdate(_ctx, data, &outlen, data, len);
    ASSERT(result1 == 1);
    int result2 = EVP_EncryptFinal_ex(_ctx, data, &outlen);
    ASSERT(result2 == 1);
}
References ASSERT.
Referenced by Warden::DecryptData(), AuthCrypt::DecryptRecv(), Warden::EncryptData(), AuthCrypt::EncryptSend(), and AuthCrypt::Init().
Member Data Documentation
_ctx
EVP_CIPHER_CTX* Acore::Crypto::ARC4::_ctx private
Referenced by ARC4().