AzerothCore: MPQArchive Class Reference
MPQArchive Class Reference
#include "mpq_libmpq04.h"
Public Member Functions
MPQArchive (const char *filename)
~MPQArchive ()
void close ()
void GetFileListTo (vector< string > &filelist)
MPQArchive (const char *filename)
~MPQArchive ()
void GetFileListTo (vector< string > &filelist)
Public Attributes
mpq_archive_s * mpq_a
Private Member Functions
void close ()
bool isOpened () const
Detailed Description
Constructor & Destructor Documentation
MPQArchive() [1/2]
MPQArchive::MPQArchive (const char * filename)
{
    int result = libmpq__archive_open(&mpq_a, filename, -1);
    printf("Opening %s\n", filename);
    if (result)
    {
        switch (result)
        {
            case LIBMPQ_ERROR_OPEN :
                printf("Error opening archive '%s': Does file really exist?\n", filename);
                break;
            case LIBMPQ_ERROR_FORMAT :            /* bad file format */
                printf("Error opening archive '%s': Bad file format\n", filename);
                break;
            case LIBMPQ_ERROR_SEEK :         /* seeking in file failed */
                printf("Error opening archive '%s': Seeking in file failed\n", filename);
                break;
            case LIBMPQ_ERROR_READ :              /* Read error in archive */
                printf("Error opening archive '%s': Read error in archive\n", filename);
                break;
            case LIBMPQ_ERROR_MALLOC :               /* maybe not enough memory? :) */
                printf("Error opening archive '%s': Maybe not enough memory\n", filename);
                break;
            default:
                printf("Error opening archive '%s': Unknown error\n", filename);
                break;
        }
        return;
    }
    gOpenArchives.push_front(this);
}
References gOpenArchives, and mpq_a.
~MPQArchive() [1/2]
MPQArchive::~MPQArchive () inline
{ close(); }
References close().
MPQArchive() [2/2]
MPQArchive::MPQArchive (const char * filename)
~MPQArchive() [2/2]
MPQArchive::~MPQArchive () inline
{ if (isOpened()) close(); }
References close(), and isOpened().
Member Function Documentation
close() [1/2]
void MPQArchive::close ()
{
    //gOpenArchives.erase(erase(&mpq_a);
    libmpq__archive_close(mpq_a);
}
References mpq_a.
Referenced by ~MPQArchive().
close() [2/2]
void MPQArchive::close () private
GetFileListTo() [1/2]
void MPQArchive::GetFileListTo (vector< string > & filelist) inline
    {
        uint32_t filenum;
        if (libmpq__file_number(mpq_a, "(listfile)", &filenum)) return;
        libmpq__off_t size, transferred;
        libmpq__file_unpacked_size(mpq_a, filenum, &size);
        char* buffer = new char[size + 1];
        buffer[size] = '\0';
        libmpq__file_read(mpq_a, filenum, (unsigned char*)buffer, size, &transferred);
        char seps[] = "\n";
        char* token;
        token = strtok( buffer, seps );
        uint32 counter = 0;
        while ((token != nullptr) && (counter < size))
        {
            //cout << token << endl;
            token[strlen(token) - 1] = 0;
            string s = token;
            filelist.push_back(s);
            counter += strlen(token) + 2;
            token = strtok(nullptr, seps);
        }
        delete[] buffer;
    }
References mpq_a.
GetFileListTo() [2/2]
void MPQArchive::GetFileListTo (vector< string > & filelist) inline
    {
        uint32_t filenum;
        if (libmpq__file_number(mpq_a, "(listfile)", &filenum)) return;
        libmpq__off_t size, transferred;
        libmpq__file_unpacked_size(mpq_a, filenum, &size);
        char* buffer = new char[size + 1];
        buffer[size] = '\0';
        libmpq__file_read(mpq_a, filenum, (unsigned char*)buffer, size, &transferred);
        char seps[] = "\n";
        char* token;
        token = strtok( buffer, seps );
        uint32 counter = 0;
        while ((token != nullptr) && (counter < size))
        {
            //cout << token << endl;
            token[strlen(token) - 1] = 0;
            string s = token;
            filelist.push_back(s);
            counter += strlen(token) + 2;
            token = strtok(nullptr, seps);
        }
        delete[] buffer;
    }
References mpq_a.
isOpened()
bool MPQArchive::isOpened () const private
{
    return std::find(gOpenArchives.begin(), gOpenArchives.end(), this) != gOpenArchives.end();
}
References gOpenArchives.
Referenced by ~MPQArchive().
Member Data Documentation
mpq_a
mpq_archive_s * MPQArchive::mpq_a
Referenced by close(), GetFileListTo(), and MPQArchive().