AzerothCore: ScriptObject Class Reference
ScriptObject Class Reference
#include "ScriptObject.h"
Public Member Functions
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Protected Member Functions
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Private Attributes
const std::string _name
const uint16 _totalAvailableHooks
Friends
class ScriptMgr
Detailed Description
Constructor & Destructor Documentation
ScriptObject()
ScriptObject::ScriptObject (const char * name, uint16 totalAvailableHooks = 0) inline protected
                                                                   : _name(std::string(name)), _totalAvailableHooks(totalAvailableHooks)
    {
    }
~ScriptObject()
virtual ScriptObject::~ScriptObject () protected virtual default
Member Function Documentation
checkValidity()
virtual void ScriptObject::checkValidity () inline virtual
Reimplemented in BattlegroundMapScript, InstanceMapScript, and WorldMapScript.
{ }
GetName()
const std::string & ScriptObject::GetName () const inline
{ return _name; }
References _name.
Referenced by ScriptMgr::CreateAuraScripts(), and ScriptMgr::CreateSpellScripts().
GetTotalAvailableHooks()
uint16 ScriptObject::GetTotalAvailableHooks () inline
{ return _totalAvailableHooks; }
References _totalAvailableHooks.
isAfterLoadScript()
virtual bool ScriptObject::isAfterLoadScript () const inline virtual
Reimplemented in BattlegroundMapScript, and WorldMapScript.
{ return IsDatabaseBound(); }
References IsDatabaseBound().
IsDatabaseBound()
virtual bool ScriptObject::IsDatabaseBound () const inline virtual
Reimplemented in AchievementCriteriaScript, AchievementScript, AllBattlegroundScript, AllCommandScript, AllSpellScript, AreaTriggerScript, ArenaScript, ArenaTeamScript, BattlegroundScript, ConditionScript, CreatureScript, DatabaseScript, GameObjectScript, GroupScript, GuildScript, InstanceMapScript, ItemScript, LootScript, MiscScript, OutdoorPvPScript, PetScript, SpellScriptLoader, TransportScript, WeatherScript, and WorldObjectScript.
{ return false; }
Referenced by isAfterLoadScript().
Friends And Related Function Documentation
ScriptMgr
friend class ScriptMgr friend
Member Data Documentation
_name
const std::string ScriptObject::_name private
Referenced by GetName().
_totalAvailableHooks
const uint16 ScriptObject::_totalAvailableHooks private
Referenced by GetTotalAvailableHooks().