AzerothCore: Logger Class Reference
Logger Class Reference
#include "Logger.h"
Public Member Functions
Logger (std::string const &name, LogLevel level)
void addAppender (uint8 type, Appender *appender)
void delAppender (uint8 type)
std::string const & getName () const
LogLevel getLogLevel () const
void setLogLevel (LogLevel level)
void write (LogMessage *message) const
Private Attributes
std::string name
LogLevel level
std::unordered_map< uint8, Appender * > appenders
Detailed Description
Constructor & Destructor Documentation
Logger()
Logger::Logger (std::string const & name, LogLevel level)
: name(_name), level(_level) { }
Member Function Documentation
addAppender()
void Logger::addAppender (uint8 type, Appender * appender)
{
    appenders[id] = appender;
}
References appenders.
Referenced by Log::ReadLoggersFromConfig().
delAppender()
void Logger::delAppender (uint8 type)
{
    appenders.erase(id);
}
References appenders.
getLogLevel()
LogLevel Logger::getLogLevel () const
{
    return level;
}
References level.
Referenced by Log::ShouldLog().
getName()
std::string const & Logger::getName () const
{
    return name;
}
References name.
setLogLevel()
void Logger::setLogLevel (LogLevel level)
{
    level = _level;
}
References level.
write()
void Logger::write (LogMessage * message) const
{
    if (!level || level < message->level || message->text.empty())
    {
        //fprintf(stderr, "Logger::write: Logger %s, Level %u. Msg %s Level %u WRONG LEVEL MASK OR EMPTY MSG\n", getName().c_str(), getLogLevel(), message.text.c_str(), message.level);
        return;
    }
    for (std::pair<uint8 const, Appender*> const& appender : appenders)
        if (appender.second)
        {
            appender.second->write(message);
        }
}
References appenders, level, and LogMessage::text.
Referenced by LogOperation::call(), and Log::write().
Member Data Documentation
appenders
std::unordered_map<uint8, Appender*> Logger::appenders private
Referenced by addAppender(), delAppender(), and write().
level
LogLevel Logger::level private
Referenced by getLogLevel(), setLogLevel(), and write().
name
std::string Logger::name private
Referenced by getName().