AzerothCore: boss_nefarian Struct Reference
boss_nefarian Struct Reference
Public Member Functions
boss_nefarian (Creature *creature)
void Initialize ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void MovementInform (uint32 type, uint32 id) override
void PathEndReached (uint32) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
bool Phase3
bool _introDone
std::set< uint8 > classesPresent
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
bool _ProccessHealthCheckEvent (uint8 healthPct, uint32 damage, std::function< void()> exec) const
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
TaskScheduler scheduler
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_nefarian()
boss_nefarian::boss_nefarian (Creature * creature) inline
                                      : BossAI(creature, DATA_NEFARIAN), _introDone(false)
    {
        Initialize();
    }
References Initialize().
Member Function Documentation
DamageTaken()
void boss_nefarian::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from BossAI.
    {
        if (me->HealthBelowPctDamaged(20, damage) && !Phase3)
        {
            std::list<Creature*> constructList;
            me->GetCreatureListWithEntryInGrid(constructList, NPC_BONE_CONSTRUCT, 500.0f);
            for (Creature* const& summon : constructList)
            {
                if (summon && !summon->IsAlive())
                {
                    summon->Respawn();
                    summon->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    summon->SetReactState(REACT_AGGRESSIVE);
                    summon->SetStandState(UNIT_STAND_STATE_STAND);
                    DoZoneInCombat(summon);
                }
            }
            Phase3 = true;
            Talk(SAY_RAISE_SKELETONS);
        }
    }
References CreatureAI::DoZoneInCombat(), WorldObject::GetCreatureListWithEntryInGrid(), Unit::HealthBelowPctDamaged(), ScriptedAI::me, NPC_BONE_CONSTRUCT, Phase3, REACT_AGGRESSIVE, SAY_RAISE_SKELETONS, UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_STAND.
Initialize()
void boss_nefarian::Initialize () inline
    {
        Phase3 = false;
    }
References Phase3.
Referenced by boss_nefarian(), and Reset().
JustDied()
void boss_nefarian::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
    {
        _JustDied();
        Talk(SAY_DEATH);
    }
References BossAI::_JustDied(), and SAY_DEATH.
JustEngagedWith()
void boss_nefarian::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
{}
KilledUnit()
void boss_nefarian::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (rand32() % 5)
        {
            return;
        }
        Talk(SAY_SLAY, victim);
    }
References rand32(), and SAY_SLAY.
MovementInform()
void boss_nefarian::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
    {
        if (type != WAYPOINT_MOTION_TYPE)
        {
            return;
        }
        if (id == 3)
        {
            Talk(SAY_INTRO);
        }
        if (id == 5)
        {
            DoCastAOE(SPELL_SHADOWFLAME_INITIAL);
        }
    }
References UnitAI::DoCastAOE(), SAY_INTRO, SPELL_SHADOWFLAME_INITIAL, and WAYPOINT_MOTION_TYPE.
PathEndReached()
void boss_nefarian::PathEndReached (uint32) inline override virtual
Reimplemented from CreatureAI.
    {
        me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
        me->SetCanFly(false);
        me->SetDisableGravity(false);
        Position land = me->GetPosition();
        me->GetMotionMaster()->MoveLand(0, land, 8.5f);
        me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        me->GetMotionMaster()->MoveIdle();
        me->SetReactState(REACT_AGGRESSIVE);
        DoZoneInCombat();
        if (me->GetVictim())
        {
            AttackStart(me->GetVictim());
        }
        events.ScheduleEvent(EVENT_SHADOWFLAME, 12s);
        events.ScheduleEvent(EVENT_FEAR, 25s, 35s);
        events.ScheduleEvent(EVENT_VEILOFSHADOW, 25s, 35s);
        events.ScheduleEvent(EVENT_CLEAVE, 7s);
        events.ScheduleEvent(EVENT_TAILLASH, 10s);
        events.ScheduleEvent(EVENT_CLASSCALL, 30s, 35s);
        _introDone = true;
    }
References _introDone, ScriptedAI::AttackStart(), CreatureAI::DoZoneInCombat(), EMOTE_ONESHOT_LAND, EVENT_CLASSCALL, EVENT_CLEAVE, EVENT_FEAR, EVENT_SHADOWFLAME, EVENT_TAILLASH, EVENT_VEILOFSHADOW, Unit::GetMotionMaster(), Position::GetPosition(), Unit::GetVictim(), Unit::HandleEmoteCommand(), ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MoveLand(), REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetReactState(), and UNIT_FLAG_NOT_SELECTABLE.
Reset()
void boss_nefarian::Reset () inline override virtual
Reimplemented from BossAI.
    {
        Initialize();
        me->SetReactState(REACT_PASSIVE);
        me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        me->SetCanFly(true);
        me->SetDisableGravity(true);
        if (_introDone) // already in combat, reset properly.
        {
            _Reset();
            if (Creature* victor = me->FindNearestCreature(NPC_VICTOR_NEFARIUS, 200.f, true))
            {
                if (victor->AI())
                {
                    victor->AI()->DoAction(ACTION_RESET);
                }
            }
            me->DespawnOrUnsummon();
        }
        classesPresent.clear();
    }
References _introDone, BossAI::_Reset(), ACTION_RESET, classesPresent, Creature::DespawnOrUnsummon(), WorldObject::FindNearestCreature(), Initialize(), ScriptedAI::me, NPC_VICTOR_NEFARIUS, REACT_PASSIVE, Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetReactState(), Unit::SetUnitFlag(), and UNIT_FLAG_NOT_SELECTABLE.
UpdateAI()
void boss_nefarian::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
    {
        if (!UpdateVictim())
        {
            return;
        }
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
        while (uint32 eventId = events.ExecuteEvent())
        {
            switch (eventId)
            {
                case EVENT_SHADOWFLAME:
                    DoCastVictim(SPELL_SHADOWFLAME);
                    events.ScheduleEvent(EVENT_SHADOWFLAME, 12s);
                    break;
                case EVENT_FEAR:
                    DoCastVictim(SPELL_BELLOWINGROAR);
                    events.ScheduleEvent(EVENT_FEAR, 25s, 35s);
                    break;
                case EVENT_VEILOFSHADOW:
                    DoCastVictim(SPELL_VEILOFSHADOW);
                    events.ScheduleEvent(EVENT_VEILOFSHADOW, 25s, 35s);
                    break;
                case EVENT_CLEAVE:
                    DoCastVictim(SPELL_CLEAVE);
                    events.ScheduleEvent(EVENT_CLEAVE, 7s);
                    break;
                case EVENT_TAILLASH:
                    // Cast NYI since we need a better check for behind target
                    DoCastAOE(SPELL_TAILLASH);
                    events.ScheduleEvent(EVENT_TAILLASH, 10s);
                    break;
                case EVENT_CLASSCALL:
                    if (classesPresent.empty())
                    {
                        for (auto& ref : me->GetThreatMgr().GetThreatList())
{
                            if (ref->getTarget() && ref->getTarget()->GetTypeId() == TYPEID_PLAYER)
{
                                classesPresent.insert(ref->getTarget()->getClass());
                            }
                        }
                    }
                    uint8 targetClass = Acore::Containers::SelectRandomContainerElement(classesPresent);
                    classesPresent.erase(targetClass);
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, ClassCallSelector(me, targetClass)))
                    {
                        switch (target->getClass())
{
                            case CLASS_MAGE:
                                Talk(SAY_MAGE);
                                DoCast(me, SPELL_MAGE);
                                break;
                            case CLASS_WARRIOR:
                                Talk(SAY_WARRIOR);
                                DoCast(me, SPELL_WARRIOR);
                                break;
                            case CLASS_DRUID:
                                Talk(SAY_DRUID);
                                DoCast(target, SPELL_DRUID);
                                break;
                            case CLASS_PRIEST:
                                Talk(SAY_PRIEST);
                                DoCast(me, SPELL_PRIEST);
                                break;
                            case CLASS_PALADIN:
                                Talk(SAY_PALADIN);
                                DoCast(me, SPELL_PALADIN);
                                break;
                            case CLASS_SHAMAN:
                                Talk(SAY_SHAMAN);
                                DoCast(me, SPELL_SHAMAN);
                                break;
                            case CLASS_WARLOCK:
                                Talk(SAY_WARLOCK);
                                DoCast(me, SPELL_WARLOCK);
                                break;
                            case CLASS_HUNTER:
                                Talk(SAY_HUNTER);
                                DoCast(me, SPELL_HUNTER);
                                break;
                            case CLASS_ROGUE:
                                Talk(SAY_ROGUE);
                                DoCast(me, SPELL_ROGUE);
                                break;
                            case CLASS_DEATH_KNIGHT:
                                Talk(SAY_DEATH_KNIGHT);
                                me->GetMap()->DoForAllPlayers([&](Player* p)
{
                                    if (!p->IsGameMaster())
{
                                        me->CastSpell(p, SPELL_DEATH_KNIGHT, true);
                                    }
                                });
                                break;
                            default:
                                break;
                        }
                    }
                    events.ScheduleEvent(EVENT_CLASSCALL, 30s, 35s);
                    break;
            }
            if (me->HasUnitState(UNIT_STATE_CASTING))
            {
                return;
            }
        }
        DoMeleeAttackIfReady();
    }
References CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, classesPresent, UnitAI::DoCast(), UnitAI::DoCastAOE(), UnitAI::DoCastVictim(), Map::DoForAllPlayers(), UnitAI::DoMeleeAttackIfReady(), EVENT_CLASSCALL, EVENT_CLEAVE, EVENT_FEAR, EVENT_SHADOWFLAME, EVENT_TAILLASH, EVENT_VEILOFSHADOW, WorldObject::GetMap(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), Unit::HasUnitState(), Player::IsGameMaster(), ScriptedAI::me, SAY_DEATH_KNIGHT, SAY_DRUID, SAY_HUNTER, SAY_MAGE, SAY_PALADIN, SAY_PRIEST, SAY_ROGUE, SAY_SHAMAN, SAY_WARLOCK, SAY_WARRIOR, Acore::Containers::SelectRandomContainerElement(), UnitAI::SelectTarget(), SPELL_BELLOWINGROAR, SPELL_CLEAVE, SPELL_DRUID, SPELL_HUNTER, SPELL_MAGE, SPELL_PALADIN, SPELL_PRIEST, SPELL_ROGUE, SPELL_SHADOWFLAME, SPELL_SHAMAN, SPELL_TAILLASH, SPELL_VEILOFSHADOW, SPELL_WARLOCK, SPELL_WARRIOR, TYPEID_PLAYER, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_introDone
bool boss_nefarian::_introDone private
Referenced by PathEndReached(), and Reset().
classesPresent
std::set<uint8> boss_nefarian::classesPresent private
Referenced by Reset(), and UpdateAI().
Phase3
bool boss_nefarian::Phase3 private
Referenced by DamageTaken(), and Initialize().