document.write(`
  <a id="Object:GetByteValue" class="fn" href="../Object/GetByteValue.html">GetByteValue</a>
  <a id="Object:GetEntry" class="fn" href="../Object/GetEntry.html">GetEntry</a>
  <a id="Object:GetFloatValue" class="fn" href="../Object/GetFloatValue.html">GetFloatValue</a>
  <a id="Object:GetGUID" class="fn" href="../Object/GetGUID.html">GetGUID</a>
  <a id="Object:GetGUIDLow" class="fn" href="../Object/GetGUIDLow.html">GetGUIDLow</a>
  <a id="Object:GetInt32Value" class="fn" href="../Object/GetInt32Value.html">GetInt32Value</a>
  <a id="Object:GetScale" class="fn" href="../Object/GetScale.html">GetScale</a>
  <a id="Object:GetTypeId" class="fn" href="../Object/GetTypeId.html">GetTypeId</a>
  <a id="Object:GetUInt16Value" class="fn" href="../Object/GetUInt16Value.html">GetUInt16Value</a>
  <a id="Object:GetUInt32Value" class="fn" href="../Object/GetUInt32Value.html">GetUInt32Value</a>
  <a id="Object:GetUInt64Value" class="fn" href="../Object/GetUInt64Value.html">GetUInt64Value</a>
  <a id="Object:HasFlag" class="fn" href="../Object/HasFlag.html">HasFlag</a>
  <a id="Object:IsInWorld" class="fn" href="../Object/IsInWorld.html">IsInWorld</a>
  <a id="Object:IsPlayer" class="fn" href="../Object/IsPlayer.html">IsPlayer</a>
  <a id="Object:RemoveFlag" class="fn" href="../Object/RemoveFlag.html">RemoveFlag</a>
  <a id="Object:SetByteValue" class="fn" href="../Object/SetByteValue.html">SetByteValue</a>
  <a id="Object:SetFlag" class="fn" href="../Object/SetFlag.html">SetFlag</a>
  <a id="Object:SetFloatValue" class="fn" href="../Object/SetFloatValue.html">SetFloatValue</a>
  <a id="Object:SetInt16Value" class="fn" href="../Object/SetInt16Value.html">SetInt16Value</a>
  <a id="Object:SetInt32Value" class="fn" href="../Object/SetInt32Value.html">SetInt32Value</a>
  <a id="Object:SetScale" class="fn" href="../Object/SetScale.html">SetScale</a>
  <a id="Object:SetUInt16Value" class="fn" href="../Object/SetUInt16Value.html">SetUInt16Value</a>
  <a id="Object:SetUInt32Value" class="fn" href="../Object/SetUInt32Value.html">SetUInt32Value</a>
  <a id="Object:SetUInt64Value" class="fn" href="../Object/SetUInt64Value.html">SetUInt64Value</a>
  <a id="Object:ToCorpse" class="fn" href="../Object/ToCorpse.html">ToCorpse</a>
  <a id="Object:ToCreature" class="fn" href="../Object/ToCreature.html">ToCreature</a>
  <a id="Object:ToGameObject" class="fn" href="../Object/ToGameObject.html">ToGameObject</a>
  <a id="Object:ToPlayer" class="fn" href="../Object/ToPlayer.html">ToPlayer</a>
  <a id="Object:ToUnit" class="fn" href="../Object/ToUnit.html">ToUnit</a>
  <a id="Object:UpdateUInt32Value" class="fn" href="../Object/UpdateUInt32Value.html">UpdateUInt32Value</a>
`);