AzerothCore: boss_yoggsaron_sara::boss_yoggsaron_saraAI Struct Reference
boss_yoggsaron_sara::boss_yoggsaron_saraAI Struct Reference
Public Member Functions
boss_yoggsaron_saraAI (Creature *pCreature)
void AttackStart (Unit *) override
void MoveInLineOfSight (Unit *) override
void JustSummoned (Creature *summon) override
void SpawnClouds ()
void EnterEvadeMode (EvadeReason why) override
void EnableSara (bool apply)
void Reset () override
void InitFight (Unit *target)
void DespawnGossipKeepers ()
void UpdateKeeperSpawns ()
void InformCloud ()
void SpawnTentacle (uint32 entry)
void SummonDeathOrbs ()
void AddPortals ()
void KilledUnit (Unit *who) override
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
uint32 GetData (uint32 param) const override
void DoAction (int32 param) override
void DamageTaken (Unit *who, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
uint32 _initFight
uint8 _summonedGuardiansCount
uint32 _p2TalkTimer
bool _secondPhase
float _summonSpeed
uint8 _currentIllusion
bool _isIllusionReversed
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_yoggsaron_saraAI()
boss_yoggsaron_sara::boss_yoggsaron_saraAI::boss_yoggsaron_saraAI (Creature * pCreature) inline
                                                   : ScriptedAI(pCreature), summons(pCreature)
        {
            m_pInstance = pCreature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and m_pInstance.
Member Function Documentation
AddPortals()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::AddPortals () inline
        {
            _summonSpeed -= 0.1f;
            Creature* cr = nullptr;
            // Spawn Portals
            for (uint8 i = 0; i < RAID_MODE(4, 10); ++i)
            {
                if ((cr = me->SummonCreature(NPC_DESCEND_INTO_MADNESS, yoggPortalLoc[i].x, yoggPortalLoc[i].y, yoggPortalLoc[i].z, 0, TEMPSUMMON_TIMED_DESPAWN, 25000)))
                {
                    cr->SetUnitFlag(UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_NON_ATTACKABLE);
                    cr->SetArmor(_currentIllusion);
                }
            }
            EntryCheckPredicate pred(NPC_BRAIN_OF_YOGG_SARON);
            summons.DoAction(_currentIllusion, pred);
            if (_isIllusionReversed)
                _currentIllusion = _currentIllusion == 3 ? 1 : (_currentIllusion + 1);
            else
                _currentIllusion = _currentIllusion == 1 ? 3 : (_currentIllusion - 1);
        }
References _currentIllusion, _isIllusionReversed, _summonSpeed, SummonList::DoAction(), ScriptedAI::me, NPC_BRAIN_OF_YOGG_SARON, NPC_DESCEND_INTO_MADNESS, ScriptedAI::RAID_MODE(), Unit::SetArmor(), Unit::SetUnitFlag(), WorldObject::SummonCreature(), summons, TEMPSUMMON_TIMED_DESPAWN, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, LocationsXY::x, LocationsXY::y, yoggPortalLoc, and LocationsXY::z.
Referenced by UpdateAI().
AttackStart()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
{ }
Referenced by InitFight().
DamageTaken()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (who && who->GetEntry() == NPC_GUARDIAN_OF_YS && !_secondPhase)
            {
                damage = 25000;
                // START PHASE 2
                if (me->GetHealth() <= damage)
                {
                    _secondPhase = true;
                    damage = 0;
                    events.SetPhase(EVENT_PHASE_TWO);
                    me->SetHealth(me->GetMaxHealth());
                    if (Creature* cr = me->SummonCreature(NPC_YOGG_SARON, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), M_PI))
                        cr->SetVisible(false);
                    _p2TalkTimer++;
                    Talk(SAY_SARA_TRANSFORM_1);
                }
                return;
            }
            damage = 0;
        }
References _p2TalkTimer, _secondPhase, EVENT_PHASE_TWO, Object::GetEntry(), Unit::GetHealth(), Unit::GetMaxHealth(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, NPC_GUARDIAN_OF_YS, NPC_YOGG_SARON, SAY_SARA_TRANSFORM_1, Unit::SetHealth(), and WorldObject::SummonCreature().
DespawnGossipKeepers()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::DespawnGossipKeepers () inline
        {
            for (uint8 i = KEEPER_FREYA; i <= KEEPER_THORIM; i++)
                summons.DespawnEntry(TABLE_GOSSIP_ENTRY[i]);
        }
References SummonList::DespawnEntry(), KEEPER_FREYA, KEEPER_THORIM, summons, and TABLE_GOSSIP_ENTRY.
Referenced by InitFight().
DoAction()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_SARA_UPDATE_SUMMON_KEEPERS)
            {
                UpdateKeeperSpawns();
            }
            else if (param == ACTION_BRAIN_DAMAGED)
            {
                summons.DoAction(ACTION_REMOVE_STUN);
                EntryCheckPredicate pred2(NPC_YOGG_SARON);
                summons.DoAction(ACTION_YOGG_SARON_START_P3, pred2);
                EntryCheckPredicate pred3(NPC_THORIM_KEEPER);
                summons.DoAction(ACTION_THORIM_START_STORM, pred3);
                if (me->GetMap()->Is25ManRaid() && (GetData(DATA_GET_KEEPERS_COUNT) > 0))
                    summons.DoAction(ACTION_YOGG_SARON_HARD_MODE, pred2);
                summons.DespawnEntry(NPC_DEATH_ORB);
                events.SetPhase(EVENT_PHASE_THREE);
                me->RemoveAllAuras();
                me->SetVisible(false);
                return;
            }
            else if (param == ACTION_YOGG_SARON_DEATH)
            {
                // Despawn everything but Yogg-Saron's corpse
                summons.DoAction(ACTION_DESPAWN_ADDS);
                summons.DespawnEntry(NPC_CRUSHER_TENTACLE);
                summons.DespawnEntry(NPC_CONSTRICTOR_TENTACLE);
                summons.DespawnEntry(NPC_CORRUPTOR_TENTACLE);
                summons.DespawnEntry(NPC_VOICE_OF_YOGG_SARON);
                summons.DespawnEntry(NPC_BRAIN_OF_YOGG_SARON);
                summons.DespawnEntry(NPC_MIMIRON_GOSSIP);
                summons.DespawnEntry(NPC_HODIR_GOSSIP);
                summons.DespawnEntry(NPC_FREYA_GOSSIP);
                summons.DespawnEntry(NPC_THORIM_GOSSIP);
                summons.DespawnEntry(NPC_MIMIRON_KEEPER);
                summons.DespawnEntry(NPC_HODIR_KEEPER);
                summons.DespawnEntry(NPC_FREYA_KEEPER);
                summons.DespawnEntry(NPC_THORIM_KEEPER);
                summons.DespawnEntry(NPC_SANITY_WELL);
                me->KillSelf();
                return;
            }
            // Determine shatter duration
            if (param <= 0)
                return;
            // Illusion shatters (param - stun time)
            if (Creature* yoggb = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(NPC_BRAIN_OF_YOGG_SARON)))
            {
                yoggb->AI()->Talk(EMOTE_YOGG_SARON_BRAIN_SHATTERED);
            }
            uint32 timer = events.GetNextEventTime(EVENT_SARA_P2_OPEN_PORTALS);
            uint32 portalTime = (timer > events.GetTimer() ? timer - events.GetTimer() : 0);
            events.DelayEvents(param + 100);
            events.RescheduleEvent(EVENT_SARA_P2_OPEN_PORTALS, portalTime, 0, EVENT_PHASE_TWO);
            events.ScheduleEvent(EVENT_SARA_P2_REMOVE_STUN, param, 0, EVENT_PHASE_TWO);
            me->CastSpell(me, SPELL_SHATTERED_ILLUSION, true);
        }
References ACTION_BRAIN_DAMAGED, ACTION_DESPAWN_ADDS, ACTION_REMOVE_STUN, ACTION_SARA_UPDATE_SUMMON_KEEPERS, ACTION_THORIM_START_STORM, ACTION_YOGG_SARON_DEATH, ACTION_YOGG_SARON_HARD_MODE, ACTION_YOGG_SARON_START_P3, Unit::CastSpell(), DATA_GET_KEEPERS_COUNT, SummonList::DespawnEntry(), SummonList::DoAction(), EMOTE_YOGG_SARON_BRAIN_SHATTERED, EVENT_PHASE_THREE, EVENT_PHASE_TWO, EVENT_SARA_P2_OPEN_PORTALS, EVENT_SARA_P2_REMOVE_STUN, ObjectAccessor::GetCreature(), GetData(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), Map::Is25ManRaid(), Unit::KillSelf(), ScriptedAI::me, NPC_BRAIN_OF_YOGG_SARON, NPC_CONSTRICTOR_TENTACLE, NPC_CORRUPTOR_TENTACLE, NPC_CRUSHER_TENTACLE, NPC_DEATH_ORB, NPC_FREYA_GOSSIP, NPC_FREYA_KEEPER, NPC_HODIR_GOSSIP, NPC_HODIR_KEEPER, NPC_MIMIRON_GOSSIP, NPC_MIMIRON_KEEPER, NPC_SANITY_WELL, NPC_THORIM_GOSSIP, NPC_THORIM_KEEPER, NPC_VOICE_OF_YOGG_SARON, NPC_YOGG_SARON, Unit::RemoveAllAuras(), Unit::SetVisible(), SPELL_SHATTERED_ILLUSION, summons, and UpdateKeeperSpawns().
EnableSara()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnableSara (bool apply) inline
        {
            if (apply)
            {
                me->RemoveUnitFlag(UNIT_FLAG_DISABLE_MOVE);
                me->DisableRotate(false);
                me->ClearUnitState(UNIT_STATE_ROOT);
            }
            else
            {
                me->SetUnitFlag(UNIT_FLAG_DISABLE_MOVE);
                me->DisableRotate(true);
                me->AddUnitState(UNIT_STATE_ROOT);
            }
        }
References Unit::AddUnitState(), Unit::ClearUnitState(), Unit::DisableRotate(), ScriptedAI::me, Unit::RemoveUnitFlag(), Unit::SetUnitFlag(), UNIT_FLAG_DISABLE_MOVE, and UNIT_STATE_ROOT.
Referenced by Reset().
EnterEvadeMode()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!_EnterEvadeMode(why))
                return;
            Position pos;
            pos = me->GetHomePosition();
            me->NearTeleportTo(pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), pos.GetOrientation());
            Reset();
            me->setActive(false);
        }
References CreatureAI::_EnterEvadeMode(), Creature::GetHomePosition(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, Unit::NearTeleportTo(), Reset(), and WorldObject::setActive().
Referenced by UpdateAI().
GetData()
uint32 boss_yoggsaron_sara::boss_yoggsaron_saraAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_GET_KEEPERS_COUNT)
            {
                uint8 _count = 0;
                for (uint8 i = 0; i < 4; ++i)
                    if (m_pInstance->GetData(TYPE_WATCHERS) & (1 << i))
                        ++_count;
                return _count;
            }
            else if (param == DATA_GET_SARA_PHASE)
                return _secondPhase;
            return 4; // just to be sure, return max numer of keepers
        }
References _secondPhase, DATA_GET_KEEPERS_COUNT, DATA_GET_SARA_PHASE, ZoneScript::GetData(), m_pInstance, and TYPE_WATCHERS.
Referenced by DoAction().
InformCloud()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud () inline
        {
            Creature* cloud = nullptr;
            for (SummonList::const_iterator itr = summons.begin(); itr != summons.end();)
            {
                Creature* summon = ObjectAccessor::GetCreature(*me, *itr);
                ++itr;
                if (!summon || summon->GetEntry() != NPC_OMINOUS_CLOUD || me->GetDistance(summon) < 20)
                    continue;
                if ((!cloud || (urand(0, 1) && !summon->HasAura(SPELL_SUMMON_GUARDIAN_OF_YS))))
                    cloud = summon;
            }
            if (cloud)
                cloud->AI()->DoAction(ACTION_START_SUMMONING);
        }
References ACTION_START_SUMMONING, Creature::AI(), SummonList::begin(), UnitAI::DoAction(), SummonList::end(), ObjectAccessor::GetCreature(), WorldObject::GetDistance(), Object::GetEntry(), Unit::HasAura(), ScriptedAI::me, NPC_OMINOUS_CLOUD, SPELL_SUMMON_GUARDIAN_OF_YS, summons, and urand().
Referenced by UpdateAI().
InitFight()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::InitFight (Unit * target) inline
        {
            if (!m_pInstance)
                return;
            // some simple hack checks
            if (m_pInstance->GetData(TYPE_VEZAX) != DONE || m_pInstance->GetData(TYPE_XT002) != DONE)
                return;
            m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, CRITERIA_NOT_GETTING_OLDER);
            m_pInstance->SetData(TYPE_YOGGSARON, IN_PROGRESS);
            me->SetInCombatWithZone();
            AttackStart(target);
            DespawnGossipKeepers();
            // Engage Keepers
            summons.DoZoneInCombat();
            me->CastSpell(me, SPELL_SANITY_BASE, true);
            events.ScheduleEvent(EVENT_SARA_P1_DOORS_CLOSE, 15s, 0, EVENT_PHASE_ONE);
            events.ScheduleEvent(EVENT_SARA_P1_BERSERK, 15min, 0, 0);
            events.ScheduleEvent(EVENT_SARA_P1_SUMMON, 0ms, 0, EVENT_PHASE_ONE);
            events.SetPhase(EVENT_PHASE_ONE);
            Talk(SAY_SARA_AGGRO);
            me->setActive(true);
        }
References ACHIEVEMENT_TIMED_TYPE_EVENT, AttackStart(), Unit::CastSpell(), CRITERIA_NOT_GETTING_OLDER, DespawnGossipKeepers(), DONE, InstanceScript::DoStartTimedAchievement(), SummonList::DoZoneInCombat(), EVENT_PHASE_ONE, EVENT_SARA_P1_BERSERK, EVENT_SARA_P1_DOORS_CLOSE, EVENT_SARA_P1_SUMMON, ZoneScript::GetData(), IN_PROGRESS, m_pInstance, ScriptedAI::me, SAY_SARA_AGGRO, WorldObject::setActive(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), SPELL_SANITY_BASE, summons, TYPE_VEZAX, TYPE_XT002, and TYPE_YOGGSARON.
Referenced by UpdateAI().
JustSummoned()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(summon);
        }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (who->IsPlayer())
            {
                Talk(SAY_SARA_KILL);
            }
        }
References Object::IsPlayer(), and SAY_SARA_KILL.
MoveInLineOfSight()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{ }
Reset()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!_secondPhase) // Phase 1 wipe
            {
                me->GetMap()->DoForAllPlayers([&](Player* player)
                {
                    if (Creature* voice = me->FindNearestCreature(NPC_VOICE_OF_YOGG_SARON, 10.0f))
                    {
                        voice->AI()->Talk(WHISPER_VOICE_PHASE_1_WIPE, player);
                    }
                });
            }
            summons.DoAction(ACTION_DESPAWN_ADDS);
            events.Reset();
            summons.DespawnAll();
            me->SetVisible(true);
            me->SetDisplayId(me->GetNativeDisplayId());
            me->SetDisableGravity(true);
            EnableSara(false);
            SpawnClouds();
            _initFight = 1;
            UpdateKeeperSpawns();
            _summonedGuardiansCount = 0;
            _p2TalkTimer = 0;
            _secondPhase = false;
            _summonSpeed = 1.0f;
            _currentIllusion = urand(1, 3);
            _isIllusionReversed = urand(0, 1);
            if (m_pInstance)
            {
                m_pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, CRITERIA_NOT_GETTING_OLDER);
                m_pInstance->DoRemoveAurasDueToSpellOnPlayers(SPELL_SANITY);
                m_pInstance->SetData(TYPE_YOGGSARON, NOT_STARTED);
                if (GameObject* go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_YOGG_SARON_DOORS)))
                    go->SetGoState(GO_STATE_ACTIVE);
            }
        }
References _currentIllusion, _initFight, _isIllusionReversed, _p2TalkTimer, _secondPhase, _summonedGuardiansCount, _summonSpeed, ACHIEVEMENT_TIMED_TYPE_EVENT, ACTION_DESPAWN_ADDS, CRITERIA_NOT_GETTING_OLDER, SummonList::DespawnAll(), SummonList::DoAction(), Map::DoForAllPlayers(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), InstanceScript::DoStopTimedAchievement(), EnableSara(), WorldObject::FindNearestCreature(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetNativeDisplayId(), GO_STATE_ACTIVE, GO_YOGG_SARON_DOORS, m_pInstance, ScriptedAI::me, NOT_STARTED, NPC_VOICE_OF_YOGG_SARON, ZoneScript::SetData(), Creature::SetDisableGravity(), Creature::SetDisplayId(), Unit::SetVisible(), SpawnClouds(), SPELL_SANITY, summons, TYPE_YOGGSARON, UpdateKeeperSpawns(), and urand().
Referenced by EnterEvadeMode().
SpawnClouds()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnClouds () inline
        {
            for (uint8 i = 0; i < 6; ++i)
            {
                float Zplus = i > 2 ? (i - 2) * 1.6f : 0;
                if (i % 2)
                    me->SummonCreature(NPC_OMINOUS_CLOUD, me->GetPositionX() + 8 + i * 7, me->GetPositionY() + 8 + i * 7, 326 + Zplus, 0);
                else
                    me->SummonCreature(NPC_OMINOUS_CLOUD, me->GetPositionX() - 8 - i * 7, me->GetPositionY() - 8 - i * 7, 326 + Zplus, 0);
            }
        }
References Position::GetPositionX(), Position::GetPositionY(), ScriptedAI::me, NPC_OMINOUS_CLOUD, and WorldObject::SummonCreature().
Referenced by Reset().
SpawnTentacle()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnTentacle (uint32 entry) inline
        {
            uint32 dist = urand(38, 48);
            float o = rand_norm() * M_PI * 2;
            float Zplus = (dist - 38) / 6.5f;
            if (Creature* cr = me->SummonCreature(entry, me->GetPositionX() + dist * cos(o), me->GetPositionY() + dist * std::sin(o), 327.2 + Zplus, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000))
            {
                cr->CastSpell(cr, SPELL_TENTACLE_ERUPT, true);
                cr->CastSpell(cr, SPELL_VOID_ZONE_SMALL, true);
                cr->HandleEmoteCommand(EMOTE_ONESHOT_EMERGE);
            }
        }
References EMOTE_ONESHOT_EMERGE, Position::GetPositionX(), Position::GetPositionY(), ScriptedAI::me, rand_norm(), SPELL_TENTACLE_ERUPT, SPELL_VOID_ZONE_SMALL, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
SpellHitTarget()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpellHitTarget (Unit * target, SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (spellInfo->Id == SPELL_SANITY)
                if (Aura* aur = target->GetAura(SPELL_SANITY))
                    aur->SetStackAmount(100);
        }
References Unit::GetAura(), SpellInfo::Id, and SPELL_SANITY.
SummonDeathOrbs()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::SummonDeathOrbs () inline
        {
            for (uint8 i = 0; i < 4; ++i)
            {
                uint32 dist = urand(38, 48);
                float o = rand_norm() * M_PI * 2;
                float Zplus = (dist - 38) / 6.5f;
                me->SummonCreature(NPC_DEATH_ORB, me->GetPositionX() + dist * cos(o), me->GetPositionY() + dist * std::sin(o), 327.2 + Zplus, 0, TEMPSUMMON_TIMED_DESPAWN, 20000);
            }
        }
References Position::GetPositionX(), Position::GetPositionY(), ScriptedAI::me, NPC_DEATH_ORB, rand_norm(), WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (_initFight)
            {
                _initFight += diff;
                if (_initFight > 5000)
                {
                    if (Unit* target = SelectTargetFromPlayerList(90))
                    {
                        _initFight = 0;
                        InitFight(target);
                    }
                    else
                        _initFight = 1;
                }
                return;
            }
            if (!SelectTargetFromPlayerList(90, SPELL_INSANE1))
            {
                m_pInstance->DoRemoveAurasDueToSpellOnPlayers(SPELL_INSANE1);
                EnterEvadeMode(EVADE_REASON_OTHER);
                return;
            }
            if (_p2TalkTimer)
            {
                _p2TalkTimer += diff;
                if (_p2TalkTimer >= 4000 && _p2TalkTimer < 20000)
                {
                    EntryCheckPredicate pred(NPC_OMINOUS_CLOUD);
                    summons.DoAction(ACTION_UNSUMMON_CLOUDS, pred);
                    Talk(SAY_SARA_TRANSFORM_2);
                    _p2TalkTimer = 20000;
                }
                else if (_p2TalkTimer >= 25000 && _p2TalkTimer < 40000)
                {
                    summons.DespawnEntry(NPC_OMINOUS_CLOUD);
                    Talk(SAY_SARA_TRANSFORM_3);
                    _p2TalkTimer = 40000;
                }
                else if (_p2TalkTimer >= 44500 && _p2TalkTimer < 60000)
                {
                    Talk(SAY_SARA_TRANSFORM_4);
                    _p2TalkTimer = 60000;
                }
                else if (_p2TalkTimer >= 64000)
                {
                    EntryCheckPredicate pred(NPC_YOGG_SARON);
                    summons.DoAction(ACTION_YOGG_SARON_START_YELL, pred);
                    _p2TalkTimer = 0;
                    events.ScheduleEvent(EVENT_SARA_P2_START, 500ms, 0, EVENT_PHASE_TWO);
                }
                return;
            }
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_SARA_P1_DOORS_CLOSE:
                    // Whispers of YS
                    me->SummonCreature(NPC_VOICE_OF_YOGG_SARON, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                    if (m_pInstance)
                        if (GameObject* go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_YOGG_SARON_DOORS)))
                            go->SetGoState(GO_STATE_READY);
                    events.ScheduleEvent(EVENT_SARA_P1_SPELLS, 0ms, 1, EVENT_PHASE_ONE);
                    break;
                case EVENT_SARA_P1_SUMMON:
                    events.RepeatEvent(20000 - (std::min(_summonedGuardiansCount, (uint8)5) * 2000));
                    ++_summonedGuardiansCount;
                    InformCloud();
                    break;
                case EVENT_SARA_P1_SPELLS:
                    {
                        uint32 spell = RAND(SPELL_SARAS_ANGER_TARGET_SELECTOR, SPELL_SARAS_BLESSING_TARGET_SELECTOR, SPELL_SARAS_FAVOR_TARGET_SELECTOR);
                        if (urand(0, 2))
{
                            if (spell == SPELL_SARAS_ANGER_TARGET_SELECTOR)
{
                                Talk(SAY_SARA_ANGER);
                            }
                            else if (spell == SPELL_SARAS_FAVOR_TARGET_SELECTOR)
{
                                Talk(SAY_SARA_FERVOR_HIT);
                            }
                        }
                        me->CastCustomSpell(spell, SPELLVALUE_MAX_TARGETS, 1, nullptr, false);
                        events.RepeatEvent(me->GetMap()->Is25ManRaid() ? urand(0, 3000) : 4000 + urand(0, 2000));
                        break;
                    }
                case EVENT_SARA_P2_START:
                    {
                        EntryCheckPredicate pred(NPC_YOGG_SARON);
                        summons.DoAction(ACTION_YOGG_SARON_APPEAR, pred);
                        events.RescheduleEvent(EVENT_SARA_P2_SPAWN_START_TENTACLES, 500, 0, EVENT_PHASE_TWO);
                        // Spawn Brain!
                        me->SummonCreature(NPC_BRAIN_OF_YOGG_SARON, 1981.3f, -25.43f, 265);
                        break;
                    }
                case EVENT_SARA_P2_MALADY:
                    me->CastCustomSpell(SPELL_MALADY_OF_THE_MIND, SPELLVALUE_MAX_TARGETS, 1, me, false);
                    events.Repeat(20s);
                    break;
                case EVENT_SARA_P2_PSYCHOSIS:
                    if ((urand(0, 9)) == 0)  // Rarely said (as it's casted every 3.5s)
                    {
                        Talk(SAY_SARA_PSYCHOSIS_HIT);
                    }
                    me->CastCustomSpell(SPELL_PSYCHOSIS, SPELLVALUE_MAX_TARGETS, 1, me, false);
                    events.Repeat(3500ms);
                    break;
                case EVENT_SARA_P2_DEATH_RAY:
                    Talk(SAY_SARA_DEATH_RAY);
                    SummonDeathOrbs();
                    events.Repeat(20s);
                    break;
                case EVENT_SARA_P2_SUMMON_T1: // CRUSHER
                    SpawnTentacle(NPC_CRUSHER_TENTACLE);
                    events.RepeatEvent((50000 + urand(0, 10000)) * _summonSpeed);
                    break;
                case EVENT_SARA_P2_SUMMON_T2: // CONSTRICTOR
                    SpawnTentacle(NPC_CONSTRICTOR_TENTACLE);
                    events.RepeatEvent((15000 + urand(0, 5000)) * _summonSpeed);
                    break;
                case EVENT_SARA_P2_SUMMON_T3: // CORRUPTOR
                    SpawnTentacle(NPC_CORRUPTOR_TENTACLE);
                    events.RepeatEvent((30000 + urand(0, 10000)) * _summonSpeed);
                    break;
                case EVENT_SARA_P2_BRAIN_LINK:
                    me->CastCustomSpell(SPELL_BRAIN_LINK, SPELLVALUE_MAX_TARGETS, 1, me, false);
                    events.Repeat(30s);
                    break;
                case EVENT_SARA_P2_OPEN_PORTALS:
                    {
                        AddPortals();
                        EntryCheckPredicate pred(NPC_YOGG_SARON);
                        summons.DoAction(ACTION_YOGG_SARON_OPEN_PORTAL_YELL, pred);
                        events.Repeat(80s);
                        break;
                    }
                case EVENT_SARA_P2_REMOVE_STUN:
                    {
                        me->RemoveAura(SPELL_SHATTERED_ILLUSION);
                        summons.DoAction(ACTION_REMOVE_STUN);
                        break;
                    }
                case EVENT_SARA_P2_SPAWN_START_TENTACLES:
                    me->SetOrientation(M_PI);
                    me->SetDisplayId(SARA_TRANSFORM_MODEL);
                    me->NearTeleportTo(me->GetPositionX(), me->GetPositionY(), 355, me->GetOrientation());
                    me->SetPosition(me->GetPositionX(), me->GetPositionY(), 355, me->GetOrientation());
                    SpawnTentacle(NPC_CRUSHER_TENTACLE);
                    SpawnTentacle(NPC_CONSTRICTOR_TENTACLE);
                    SpawnTentacle(NPC_CORRUPTOR_TENTACLE);
                    SpawnTentacle(NPC_CORRUPTOR_TENTACLE);
                    events.ScheduleEvent(EVENT_SARA_P2_MALADY, 7s, 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_PSYCHOSIS, 3s, 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_DEATH_RAY, 15s, 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_SUMMON_T1, 50s, 60s, 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_SUMMON_T2, 15s, 20s, 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_SUMMON_T3, 30000 + urand(0, 10000), 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_BRAIN_LINK, 0, 0, EVENT_PHASE_TWO);
                    events.ScheduleEvent(EVENT_SARA_P2_OPEN_PORTALS, 60000, 0, EVENT_PHASE_TWO);
                    break;
                case EVENT_SARA_P1_BERSERK:
                    if (me->GetInstanceScript())
                    {
                        if (Creature* yogg = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(TYPE_YOGGSARON)))
{
                            yogg->AI()->Talk(EMOTE_YOGG_SARON_BERSERK);
                        }
                    }
                    me->CastSpell(me, SPELL_EXTINGUISH_ALL_LIFE, true);
                    events.Repeat(5s);
                    break;
            }
        }
References _initFight, _p2TalkTimer, _summonedGuardiansCount, _summonSpeed, ACTION_REMOVE_STUN, ACTION_UNSUMMON_CLOUDS, ACTION_YOGG_SARON_APPEAR, ACTION_YOGG_SARON_OPEN_PORTAL_YELL, ACTION_YOGG_SARON_START_YELL, AddPortals(), Unit::CastCustomSpell(), Unit::CastSpell(), SummonList::DespawnEntry(), SummonList::DoAction(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), EMOTE_YOGG_SARON_BERSERK, EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_PHASE_ONE, EVENT_PHASE_TWO, EVENT_SARA_P1_BERSERK, EVENT_SARA_P1_DOORS_CLOSE, EVENT_SARA_P1_SPELLS, EVENT_SARA_P1_SUMMON, EVENT_SARA_P2_BRAIN_LINK, EVENT_SARA_P2_DEATH_RAY, EVENT_SARA_P2_MALADY, EVENT_SARA_P2_OPEN_PORTALS, EVENT_SARA_P2_PSYCHOSIS, EVENT_SARA_P2_REMOVE_STUN, EVENT_SARA_P2_SPAWN_START_TENTACLES, EVENT_SARA_P2_START, EVENT_SARA_P2_SUMMON_T1, EVENT_SARA_P2_SUMMON_T2, EVENT_SARA_P2_SUMMON_T3, ObjectAccessor::GetCreature(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_STATE_READY, GO_YOGG_SARON_DOORS, Unit::HasUnitState(), InformCloud(), InitFight(), Map::Is25ManRaid(), m_pInstance, ScriptedAI::me, Unit::NearTeleportTo(), NPC_BRAIN_OF_YOGG_SARON, NPC_CONSTRICTOR_TENTACLE, NPC_CORRUPTOR_TENTACLE, NPC_CRUSHER_TENTACLE, NPC_OMINOUS_CLOUD, NPC_VOICE_OF_YOGG_SARON, NPC_YOGG_SARON, RAND(), Unit::RemoveAura(), SARA_TRANSFORM_MODEL, SAY_SARA_ANGER, SAY_SARA_DEATH_RAY, SAY_SARA_FERVOR_HIT, SAY_SARA_PSYCHOSIS_HIT, SAY_SARA_TRANSFORM_2, SAY_SARA_TRANSFORM_3, SAY_SARA_TRANSFORM_4, ScriptedAI::SelectTargetFromPlayerList(), Creature::SetDisplayId(), Position::SetOrientation(), Creature::SetPosition(), SpawnTentacle(), SPELL_BRAIN_LINK, SPELL_EXTINGUISH_ALL_LIFE, SPELL_INSANE1, SPELL_MALADY_OF_THE_MIND, SPELL_PSYCHOSIS, SPELL_SARAS_ANGER_TARGET_SELECTOR, SPELL_SARAS_BLESSING_TARGET_SELECTOR, SPELL_SARAS_FAVOR_TARGET_SELECTOR, SPELL_SHATTERED_ILLUSION, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), SummonDeathOrbs(), summons, TYPE_YOGGSARON, UNIT_STATE_CASTING, and urand().
UpdateKeeperSpawns()
void boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateKeeperSpawns () inline
        {
            for (uint8 i = KEEPER_FREYA; i <= KEEPER_THORIM; i++)
            {
                if (m_pInstance->GetData(TYPE_WATCHERS) & (1 << i))
                {
                    if (!summons.HasEntry(TABLE_KEEPER_ENTRY[i]))
                        me->SummonCreature(TABLE_KEEPER_ENTRY[i], KeepersPos[i]);
                }
                else if (m_pInstance->GetData(TABLE_KEEPER_TYPE[i]) == DONE)
                {
                    if (!summons.HasEntry(TABLE_GOSSIP_ENTRY[i]))
                        me->SummonCreature(TABLE_GOSSIP_ENTRY[i], GossipKeepersPos[i]);
                }
            }
        }
References DONE, ZoneScript::GetData(), GossipKeepersPos, SummonList::HasEntry(), KEEPER_FREYA, KEEPER_THORIM, KeepersPos, m_pInstance, ScriptedAI::me, WorldObject::SummonCreature(), summons, TABLE_GOSSIP_ENTRY, TABLE_KEEPER_ENTRY, TABLE_KEEPER_TYPE, and TYPE_WATCHERS.
Referenced by DoAction(), and Reset().
Member Data Documentation
_currentIllusion
uint8 boss_yoggsaron_sara::boss_yoggsaron_saraAI::_currentIllusion
Referenced by AddPortals(), and Reset().
_initFight
uint32 boss_yoggsaron_sara::boss_yoggsaron_saraAI::_initFight
Referenced by Reset(), and UpdateAI().
_isIllusionReversed
bool boss_yoggsaron_sara::boss_yoggsaron_saraAI::_isIllusionReversed
Referenced by AddPortals(), and Reset().
_p2TalkTimer
uint32 boss_yoggsaron_sara::boss_yoggsaron_saraAI::_p2TalkTimer
Referenced by DamageTaken(), Reset(), and UpdateAI().
_secondPhase
bool boss_yoggsaron_sara::boss_yoggsaron_saraAI::_secondPhase
Referenced by DamageTaken(), GetData(), and Reset().
_summonedGuardiansCount
uint8 boss_yoggsaron_sara::boss_yoggsaron_saraAI::_summonedGuardiansCount
Referenced by Reset(), and UpdateAI().
_summonSpeed
float boss_yoggsaron_sara::boss_yoggsaron_saraAI::_summonSpeed
Referenced by AddPortals(), Reset(), and UpdateAI().
events
EventMap boss_yoggsaron_sara::boss_yoggsaron_saraAI::events
m_pInstance
InstanceScript* boss_yoggsaron_sara::boss_yoggsaron_saraAI::m_pInstance
Referenced by boss_yoggsaron_saraAI(), GetData(), InitFight(), Reset(), UpdateAI(), and UpdateKeeperSpawns().
summons
SummonList boss_yoggsaron_sara::boss_yoggsaron_saraAI::summons
Referenced by AddPortals(), DespawnGossipKeepers(), DoAction(), InformCloud(), InitFight(), JustSummoned(), Reset(), UpdateAI(), and UpdateKeeperSpawns().