AzerothCore: instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript Struct Reference
instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript Struct Reference
Public Member Functions
instance_vault_of_archavon_InstanceMapScript (Map *map)
void Initialize () override
void OnPlayerEnter (Player *) override
void Update (uint32 diff) override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *creature) override
ObjectGuid GetGuidData (uint32 identifier) const override
uint32 GetData (uint32 identifier) const override
void SetData (uint32 type, uint32 data) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
time_t ArchavonDeath
time_t EmalonDeath
time_t KoralonDeath
uint32 checkTimer
bool stoned
uint32 m_auiEncounter [MAX_ENCOUNTER]
ObjectGuid bossGUIDs [MAX_ENCOUNTER]
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_vault_of_archavon_InstanceMapScript()
instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::instance_vault_of_archavon_InstanceMapScript (Map * map) inline
                                                               : InstanceScript(map)
        {
        }
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case CRITERIA_EARTH_WIND_FIRE_10:
                case CRITERIA_EARTH_WIND_FIRE_25:
                    if (ArchavonDeath && EmalonDeath && KoralonDeath)
                    {
                        // instance difficulty check is already done in db (achievement_criteria_data)
                        // int() for Visual Studio, compile errors with std::abs(time_t)
                        return (std::abs(int(ArchavonDeath - EmalonDeath)) < MINUTE && \
                                std::abs(int(EmalonDeath - KoralonDeath)) < MINUTE && \
                                std::abs(int(KoralonDeath - ArchavonDeath)) < MINUTE);
                    }
                    break;
                default:
                    break;
            }
            return false;
        }
References ArchavonDeath, CRITERIA_EARTH_WIND_FIRE_10, CRITERIA_EARTH_WIND_FIRE_25, EmalonDeath, KoralonDeath, and MINUTE.
GetData()
uint32 instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::GetData (uint32 identifier) const inline override virtual
Reimplemented from ZoneScript.
        {
            if (identifier == DATA_STONED)
                return (uint32)stoned;
            return 0;
        }
References DATA_STONED, and stoned.
GetGuidData()
ObjectGuid instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::GetGuidData (uint32 identifier) const inline override virtual
Reimplemented from InstanceScript.
        {
            if (identifier < MAX_ENCOUNTER)
                return bossGUIDs[identifier];
            return ObjectGuid::Empty;
        }
References bossGUIDs, ObjectGuid::Empty, and MAX_ENCOUNTER.
Initialize()
void instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetHeaders(DataHeader);
            memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
            ArchavonDeath = 0;
            EmalonDeath = 0;
            KoralonDeath = 0;
            checkTimer = 0;
            stoned = false;
        }
References ArchavonDeath, checkTimer, DataHeader, EmalonDeath, KoralonDeath, m_auiEncounter, InstanceScript::SetHeaders(), and stoned.
IsEncounterInProgress()
bool instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                if (m_auiEncounter[i] == IN_PROGRESS)
                    return true;
            Battlefield* bf = sBattlefieldMgr->GetBattlefieldByBattleId(BATTLEFIELD_BATTLEID_WG);
            if (!bf || bf->IsWarTime() || bf->GetTimer() <= 10 * MINUTE * IN_MILLISECONDS)
                return true;
            return false;
        }
References BATTLEFIELD_BATTLEID_WG, Battlefield::GetTimer(), IN_MILLISECONDS, IN_PROGRESS, Battlefield::IsWarTime(), m_auiEncounter, MAX_ENCOUNTER, MINUTE, and sBattlefieldMgr.
OnCreatureCreate()
void instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case CREATURE_TORAVON:
                    bossGUIDs[EVENT_TORAVON] = creature->GetGUID();
                    break;
                case CREATURE_ARCHAVON:
                    bossGUIDs[EVENT_ARCHAVON] = creature->GetGUID();
                    break;
                case CREATURE_KORALON:
                    bossGUIDs[EVENT_KORALON] = creature->GetGUID();
                    break;
                case CREATURE_EMALON:
                    bossGUIDs[EVENT_EMALON] = creature->GetGUID();
                    break;
            }
        }
References bossGUIDs, CREATURE_ARCHAVON, CREATURE_EMALON, CREATURE_KORALON, CREATURE_TORAVON, EVENT_ARCHAVON, EVENT_EMALON, EVENT_KORALON, EVENT_TORAVON, Object::GetEntry(), and Object::GetGUID().
OnPlayerEnter()
void instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::OnPlayerEnter (Player *) inline override virtual
Reimplemented from InstanceScript.
        {
            if (stoned)
            {
                for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                    if (Creature* cr = instance->GetCreature(bossGUIDs[i]))
                        if (!cr->IsInCombat())
                            cr->RemoveAllAuras();
                stoned = false;
            }
        }
References bossGUIDs, Map::GetCreature(), InstanceScript::instance, MAX_ENCOUNTER, and stoned.
ReadSaveDataMore()
void instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> m_auiEncounter[0];
            data >> m_auiEncounter[1];
            data >> m_auiEncounter[2];
            data >> m_auiEncounter[3];
        }
References m_auiEncounter.
SetData()
void instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case EVENT_ARCHAVON:
                case EVENT_EMALON:
                case EVENT_KORALON:
                case EVENT_TORAVON:
                    m_auiEncounter[type] = data;
                    break;
            }
            if (data == DONE)
            {
                SaveToDB();
                switch (type)
                {
                    case EVENT_ARCHAVON:
                        ArchavonDeath = GameTime::GetGameTime().count();
                        break;
                    case EVENT_EMALON:
                        EmalonDeath = GameTime::GetGameTime().count();
                        break;
                    case EVENT_KORALON:
                        KoralonDeath = GameTime::GetGameTime().count();
                        break;
                    default:
                        return;
                }
                // on every death of Archavon, Emalon and Koralon check our achievement
                DoCastSpellOnPlayers(SPELL_EARTH_WIND_FIRE_ACHIEVEMENT_CHECK);
            }
        }
References ArchavonDeath, InstanceScript::DoCastSpellOnPlayers(), DONE, EmalonDeath, EVENT_ARCHAVON, EVENT_EMALON, EVENT_KORALON, EVENT_TORAVON, GameTime::GetGameTime(), KoralonDeath, m_auiEncounter, InstanceScript::SaveToDB(), and SPELL_EARTH_WIND_FIRE_ACHIEVEMENT_CHECK.
Update()
void instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            checkTimer += diff;
            if (checkTimer >= 60000)
            {
                checkTimer -= 60000; // one minute
                if (Battlefield* bf = sBattlefieldMgr->GetBattlefieldByBattleId(BATTLEFIELD_BATTLEID_WG))
                {
                    if (!bf->IsWarTime())
                    {
                        if (bf->GetTimer() <= (16 * MINUTE * IN_MILLISECONDS) && bf->GetTimer() >= (15 * MINUTE * IN_MILLISECONDS))
{
                            Map::PlayerList const& PlayerList = instance->GetPlayers();
                            if (!PlayerList.IsEmpty())
                                for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
                                    if (Player* player = i->GetSource())
                                        player->TextEmote("This instance will reset in 15 minutes.", nullptr, true);
                        }
                        else if (bf->GetTimer() <= (10 * MINUTE * IN_MILLISECONDS) && bf->GetTimer() >= (9 * MINUTE * IN_MILLISECONDS))
{
                            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                                if (Creature* cr = instance->GetCreature(bossGUIDs[i]))
                                    if (!cr->IsInCombat())
{
                                        cr->RemoveAllAuras();
                                        if (Aura* aur = cr->AddAura(SPELL_STONED_AURA, cr))
{
                                            aur->SetMaxDuration(60 * MINUTE * IN_MILLISECONDS);
                                            aur->SetDuration(60 * MINUTE * IN_MILLISECONDS);
                                        }
                                    }
                            stoned = true;
                        }
                        else if (bf->GetTimer() <= (2 * MINUTE * IN_MILLISECONDS) && bf->GetTimer() > (MINUTE * IN_MILLISECONDS))
{
                            Map::PlayerList const& PlayerList = instance->GetPlayers();
                            if (!PlayerList.IsEmpty())
                                for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
                                    if (Player* player = i->GetSource())
                                        player->TextEmote("This instance is about to reset. Prepare to be removed.", nullptr, true);
                        }
                        else if (bf->GetTimer() <= MINUTE * IN_MILLISECONDS)
{
                            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                                if (Creature* cr = instance->GetCreature(bossGUIDs[i]))
                                    if (cr->IsInCombat() && cr->AI())
                                        cr->AI()->EnterEvadeMode();
                            Map::PlayerList const& PlayerList = instance->GetPlayers();
                            if (!PlayerList.IsEmpty())
                                for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
                                    if (Player* player = i->GetSource())
                                        player->TeleportTo(player->m_homebindMapId, player->m_homebindX, player->m_homebindY, player->m_homebindZ, player->GetOrientation());
                        }
                    }
                }
            }
        }
References BATTLEFIELD_BATTLEID_WG, MapRefMgr::begin(), bossGUIDs, checkTimer, MapRefMgr::end(), Map::GetCreature(), Map::GetPlayers(), IN_MILLISECONDS, InstanceScript::instance, LinkedListHead::IsEmpty(), MAX_ENCOUNTER, MINUTE, sBattlefieldMgr, SPELL_STONED_AURA, and stoned.
WriteSaveDataMore()
void instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << m_auiEncounter[0] << ' '
                << m_auiEncounter[1] << ' '
                << m_auiEncounter[2] << ' '
                << m_auiEncounter[3];
        }
References m_auiEncounter.
Member Data Documentation
ArchavonDeath
time_t instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::ArchavonDeath private
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
bossGUIDs
ObjectGuid instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::bossGUIDs[MAX_ENCOUNTER] private
Referenced by GetGuidData(), OnCreatureCreate(), OnPlayerEnter(), and Update().
checkTimer
uint32 instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::checkTimer private
Referenced by Initialize(), and Update().
EmalonDeath
time_t instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::EmalonDeath private
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
KoralonDeath
time_t instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::KoralonDeath private
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
m_auiEncounter
uint32 instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::m_auiEncounter[MAX_ENCOUNTER] private
Referenced by Initialize(), IsEncounterInProgress(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
stoned
bool instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::stoned private
Referenced by GetData(), Initialize(), OnPlayerEnter(), and Update().