AzerothCore: boss_yoggsaron_cloud::boss_yoggsaron_cloudAI Struct Reference
boss_yoggsaron_cloud::boss_yoggsaron_cloudAI Struct Reference
Public Member Functions
boss_yoggsaron_cloudAI (Creature *pCreature)
void JustSummoned (Creature *cr) override
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void WaypointReached (uint32) override
void Reset () override
void DoAction (int32 param) override
void InitWaypoint ()
void UpdateEscortAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
uint32 _checkTimer
bool _isSummoning
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_yoggsaron_cloudAI()
boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::boss_yoggsaron_cloudAI (Creature * pCreature) inline
                                                    : npc_escortAI(pCreature)
        {
            InitWaypoint();
            Reset();
            Start(false, true, ObjectGuid::Empty, nullptr, false, true);
        }
References ObjectGuid::Empty, InitWaypoint(), Reset(), and npc_escortAI::Start().
Member Function Documentation
AttackStart()
void boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::AttackStart (Unit *) inline override virtual
Reimplemented from npc_escortAI.
{}
DoAction()
void boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_UNSUMMON_CLOUDS)
            {
                me->RemoveAllAuras();
            }
            else if (param == ACTION_START_SUMMONING)
            {
                _isSummoning = true;
                me->CastSpell(me, SPELL_SUMMON_GUARDIAN_OF_YS, true);
            }
        }
References _isSummoning, ACTION_START_SUMMONING, ACTION_UNSUMMON_CLOUDS, Unit::CastSpell(), ScriptedAI::me, Unit::RemoveAllAuras(), and SPELL_SUMMON_GUARDIAN_OF_YS.
InitWaypoint()
void boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::InitWaypoint () inline
        {
            float dist = Middle.GetExactDist(me);
            if (me->GetPositionX() > Middle.GetPositionX())
            {
                for (uint8 i = 0; i <= dist; ++i)
                {
                    float angle = M_PI * 2 / dist * i;
                    AddWaypoint(i, Middle.GetPositionX() + dist * cos(angle), Middle.GetPositionY() + dist * std::sin(angle), me->GetPositionZ(), 0);
                }
            }
            else
            {
                for (uint8 i = 0; i <= dist; ++i)
                {
                    float angle = M_PI * 2 - (M_PI * 2 / dist * i);
                    AddWaypoint(i, Middle.GetPositionX() + dist * cos(angle), Middle.GetPositionY() + dist * std::sin(angle), me->GetPositionZ(), 0);
                }
            }
        }
References npc_escortAI::AddWaypoint(), Position::GetExactDist(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, and Middle.
Referenced by boss_yoggsaron_cloudAI().
JustSummoned()
void boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
        {
            cr->ToTempSummon()->SetTempSummonType(TEMPSUMMON_CORPSE_DESPAWN);
            _isSummoning = false;
            if (me->GetInstanceScript())
                if (Creature* sara = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(NPC_SARA)))
                    sara->AI()->JustSummoned(cr);
        }
References _isSummoning, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), ScriptedAI::me, NPC_SARA, TempSummon::SetTempSummonType(), TEMPSUMMON_CORPSE_DESPAWN, and Unit::ToTempSummon().
MoveInLineOfSight()
void boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from npc_escortAI.
{}
Reset()
void boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            me->CastSpell(me, SPELL_CLOUD_VISUAL, true);
            _checkTimer = 0;
            _isSummoning = false;
        }
References _checkTimer, _isSummoning, Unit::CastSpell(), ScriptedAI::me, and SPELL_CLOUD_VISUAL.
Referenced by boss_yoggsaron_cloudAI().
UpdateEscortAI()
void boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
        {
            _checkTimer += diff;
            if (_checkTimer >= 500 && !_isSummoning)
            {
                Unit* who = me->SelectNearbyTarget(nullptr, 6.0f);
                if (who && who->IsPlayer() && !me->HasAura(SPELL_SUMMON_GUARDIAN_OF_YS) && !who->HasAura(SPELL_HODIR_FLASH_FREEZE))
                {
                    _isSummoning = true;
                    Talk(0, who);
                    me->CastSpell(me, SPELL_SUMMON_GUARDIAN_OF_YS, true);
                }
                _checkTimer = 0;
            }
        }
References _checkTimer, _isSummoning, Unit::CastSpell(), Unit::HasAura(), Object::IsPlayer(), ScriptedAI::me, Unit::SelectNearbyTarget(), SPELL_HODIR_FLASH_FREEZE, and SPELL_SUMMON_GUARDIAN_OF_YS.
WaypointReached()
void boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::WaypointReached (uint32) inline override virtual
Implements npc_escortAI.
{}
Member Data Documentation
_checkTimer
uint32 boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::_checkTimer
Referenced by Reset(), and UpdateEscortAI().
_isSummoning
bool boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::_isSummoning
Referenced by DoAction(), JustSummoned(), Reset(), and UpdateEscortAI().