AzerothCore: SmartScriptHolder Struct Reference
SmartScriptHolder Struct Reference
#include "SmartScriptMgr.h"
Public Member Functions
SmartScriptHolder ()
uint32 GetScriptType () const
uint32 GetEventType () const
uint32 GetActionType () const
uint32 GetTargetType () const
bool operator< (SmartScriptHolder const &other) const
Public Attributes
int32 entryOrGuid
SmartScriptType source_type
uint32 event_id
uint32 link
SmartEvent event
SmartAction action
SmartTarget target
uint32 timer
uint32 priority
bool active
bool runOnce
bool enableTimed
Static Public Attributes
static constexpr uint32 DEFAULT_PRIORITY = std::numeric_limits<uint32>::max()
Detailed Description
Constructor & Destructor Documentation
SmartScriptHolder()
SmartScriptHolder::SmartScriptHolder () inline
                        : entryOrGuid(0), source_type(SMART_SCRIPT_TYPE_CREATURE)
        , event_id(0), link(0), event(), action(), target(), timer(0), priority(DEFAULT_PRIORITY), active(false), runOnce(false)
        , enableTimed(false) {}
Member Function Documentation
GetActionType()
uint32 SmartScriptHolder::GetActionType () const inline
{ return (uint32)action.type; }
References action, and SmartAction::type.
Referenced by SmartAIMgr::CheckUnusedActionParams(), SmartAIMgr::CheckUnusedEventParams(), SmartAIMgr::CheckUnusedTargetParams(), SmartScript::GetTargets(), SmartAIMgr::IsAreaTriggerValid(), SmartAIMgr::IsCreatureValid(), SmartAIMgr::IsEmoteValid(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsGameObjectValid(), SmartAIMgr::IsItemValid(), SmartAIMgr::IsMinMaxValid(), SmartAIMgr::IsQuestValid(), SmartAIMgr::IsSoundValid(), SmartAIMgr::IsSpellValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextEmoteValid(), SmartAIMgr::IsTextValid(), SmartAIMgr::NotNULL(), SmartScript::ProcessAction(), SmartScript::SetScript9(), and SmartScript::UpdateTimer().
GetEventType()
uint32 SmartScriptHolder::GetEventType () const inline
{ return (uint32)event.type; }
Referenced by SmartAIMgr::CheckUnusedEventParams(), SmartScript::InitTimer(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextValid(), SmartScript::ProcessAction(), SmartScript::ProcessEvent(), SmartScript::SetScript9(), and SmartScript::UpdateTimer().
GetScriptType()
uint32 SmartScriptHolder::GetScriptType () const inline
{ return (uint32)source_type; }
References source_type.
Referenced by SmartAIMgr::CheckUnusedActionParams(), SmartAIMgr::CheckUnusedEventParams(), SmartAIMgr::CheckUnusedTargetParams(), SmartScript::GetTargets(), SmartScript::InstallTemplate(), SmartAIMgr::IsAreaTriggerValid(), SmartAIMgr::IsCreatureValid(), SmartAIMgr::IsEmoteValid(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsGameObjectValid(), SmartAIMgr::IsItemValid(), SmartAIMgr::IsMinMaxValid(), SmartAIMgr::IsQuestValid(), SmartAIMgr::IsSoundValid(), SmartAIMgr::IsSpellValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextEmoteValid(), SmartAIMgr::IsTextValid(), SmartAIMgr::NotNULL(), SmartScript::ProcessAction(), SmartScript::SetScript9(), and SmartScript::UpdateTimer().
GetTargetType()
uint32 SmartScriptHolder::GetTargetType () const inline
{ return (uint32)target.type; }
References target, and SmartTarget::type.
Referenced by SmartAIMgr::CheckUnusedTargetParams(), SmartScript::GetTargets(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextValid(), SmartScript::ProcessAction(), and SmartScript::ProcessEvent().
operator<()
bool SmartScriptHolder::operator< (SmartScriptHolder const & other) const inline
    {
        return std::tie(priority, entryOrGuid, source_type, event_id, link) < std::tie(other.priority, other.entryOrGuid, other.source_type, other.event_id, other.link);
    }
References entryOrGuid, event_id, link, priority, and source_type.
Member Data Documentation
action
SmartAction SmartScriptHolder::action
Referenced by SmartAIMgr::CheckUnusedActionParams(), SmartScript::CreateSmartEvent(), GetActionType(), SmartScript::InstallTemplate(), SmartAIMgr::IsEventValid(), SmartAIMgr::LoadSmartAIFromDB(), SmartScript::ProcessAction(), SmartScript::SetScript9(), and SmartScript::UpdateTimer().
active
bool SmartScriptHolder::active
Referenced by SmartScript::CheckTimer(), SmartScript::InitTimer(), SmartScript::ProcessEvent(), SmartScript::RecalcTimer(), and SmartScript::UpdateTimer().
DEFAULT_PRIORITY
constexpr uint32 SmartScriptHolder::DEFAULT_PRIORITY = std::numeric_limits<uint32>::max() static constexpr
Referenced by SmartScript::OnReset(), SmartScript::RaisePriority(), and SmartScript::UpdateTimer().
enableTimed
bool SmartScriptHolder::enableTimed
Referenced by SmartScript::UpdateTimer().
entryOrGuid
int32 SmartScriptHolder::entryOrGuid
Referenced by SmartAIMgr::CheckUnusedActionParams(), SmartAIMgr::CheckUnusedEventParams(), SmartAIMgr::CheckUnusedTargetParams(), SmartScript::GetTargets(), SmartScript::InstallTemplate(), SmartAIMgr::IsAreaTriggerValid(), SmartAIMgr::IsCreatureValid(), SmartAIMgr::IsEmoteValid(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsGameObjectValid(), SmartAIMgr::IsItemValid(), SmartAIMgr::IsMinMaxValid(), SmartAIMgr::IsQuestValid(), SmartAIMgr::IsSoundValid(), SmartAIMgr::IsSpellValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextEmoteValid(), SmartAIMgr::IsTextValid(), SmartAIMgr::LoadSmartAIFromDB(), SmartAIMgr::NotNULL(), operator<(), SmartScript::ProcessAction(), SmartScript::ProcessTimedAction(), and SmartScript::SetScript9().
event
SmartEvent SmartScriptHolder::event
Referenced by SmartAIMgr::CheckUnusedEventParams(), SmartScript::CreateSmartEvent(), SmartScript::InitTimer(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextValid(), SmartAIMgr::LoadSmartAIFromDB(), SmartScript::ProcessAction(), SmartScript::ProcessEvent(), SmartScript::RetryLater(), and SmartScript::UpdateTimer().
event_id
uint32 SmartScriptHolder::event_id
Referenced by SmartAIMgr::CheckUnusedActionParams(), SmartAIMgr::CheckUnusedEventParams(), SmartAIMgr::CheckUnusedTargetParams(), SmartScript::GetTargets(), SmartAIMgr::IsAreaTriggerValid(), SmartAIMgr::IsCreatureValid(), SmartAIMgr::IsEmoteValid(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsGameObjectValid(), SmartAIMgr::IsItemValid(), SmartAIMgr::IsMinMaxValid(), SmartAIMgr::IsQuestValid(), SmartAIMgr::IsSoundValid(), SmartAIMgr::IsSpellValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextEmoteValid(), SmartAIMgr::IsTextValid(), SmartAIMgr::LoadSmartAIFromDB(), SmartAIMgr::NotNULL(), operator<(), SmartScript::ProcessTimedAction(), and SmartScript::UpdateTimer().
link
uint32 SmartScriptHolder::link
Referenced by SmartAIMgr::IsEventValid(), SmartAIMgr::LoadSmartAIFromDB(), and operator<().
priority
uint32 SmartScriptHolder::priority
Referenced by operator<(), SmartScript::RaisePriority(), and SmartScript::UpdateTimer().
runOnce
bool SmartScriptHolder::runOnce
Referenced by SmartScript::ProcessAction(), SmartScript::ProcessEvent(), and SmartScript::RetryLater().
source_type
SmartScriptType SmartScriptHolder::source_type
Referenced by SmartScript::CreateSmartEvent(), GetScriptType(), SmartAIMgr::LoadSmartAIFromDB(), operator<(), and SmartScript::ProcessTimedAction().
target
SmartTarget SmartScriptHolder::target
Referenced by SmartAIMgr::CheckUnusedTargetParams(), SmartScript::CreateSmartEvent(), SmartScript::GetTargets(), GetTargetType(), SmartScript::InstallTemplate(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::LoadSmartAIFromDB(), and SmartScript::ProcessAction().
timer
uint32 SmartScriptHolder::timer
Referenced by SmartScript::RaisePriority(), SmartScript::RecalcTimer(), and SmartScript::UpdateTimer().