AzerothCore: BasicEvent Class Reference
BasicEvent Class Reference
#include "EventProcessor.h"
Public Member Functions
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Types
enum class AbortState : uint8 {
STATE_RUNNING ,
STATE_ABORT_SCHEDULED ,
STATE_ABORTED
}
Private Member Functions
void SetAborted ()
bool IsRunning () const
bool IsAbortScheduled () const
bool IsAborted () const
Private Attributes
AbortState m_abortState {AbortState::STATE_RUNNING}
uint64 m_addTime {0}
uint64 m_execTime {0}
uint8 m_eventGroup {0}
Friends
class EventProcessor
Detailed Description
Member Enumeration Documentation
AbortState
enum class BasicEvent::AbortState : uint8 strong private
Enumerator
STATE_RUNNING
STATE_ABORT_SCHEDULED
STATE_ABORTED
    {
        STATE_RUNNING,
        STATE_ABORT_SCHEDULED,
        STATE_ABORTED
        };
Constructor & Destructor Documentation
BasicEvent()
BasicEvent::BasicEvent () default
~BasicEvent()
virtual BasicEvent::~BasicEvent () virtual default
Member Function Documentation
Abort()
virtual void BasicEvent::Abort (uint64) inline virtual
Reimplemented in SpellEvent, BGQueueInviteEvent, BGQueueRemoveEvent, and AuctionListOwnerItemsDelayEvent.
{ }           // this method executes when the event is aborted
Execute()
virtual bool BasicEvent::Execute (uint64 , uint32) inline virtual
Reimplemented in SpellEvent, BGQueueInviteEvent, BGQueueRemoveEvent, AssistDelayEvent, ForcedDespawnDelayEvent, TemporaryThreatModifierEvent, ForcedUnsummonDelayEvent, RedirectSpellEvent, VehicleDespawnEvent, AuctionListOwnerItemsDelayEvent, ReflectEvent, BattleExperienceEvent, LambdaBasicEvent< T >, KillMagnetEvent, AuraMunchingQueue, RestoreAttack, OrcMoveEvent, OrcDeathEvent, DelayedSummonEvent, CorruptTriggers, CastArmageddon, MoveDelayed, FixOrientation, NpcRunToHome, DelayedWindstoneSummonEvent, DelayedTalk, RestoreFight, SendEncounterUnit, HideNpcEvent, UtherBatteredHiltEvent, SlaveRunEvent, RestoreFight, StandUpEvent, ShockVortexExplodeEvent, DelayedMovementEvent, ResetEncounterEvent, DaranavanMoveEvent, FrostwyrmLandEvent, FrostBombExplosion, IceTombSummonEvent, StartMovementEvent, VileSpiritActivateEvent, TriggerWickedSpirit, LichKingDeathEvent, LichKingMovieEvent, DelayedCastEvent, AuraRemoveEvent, ValithriaDespawner, CaptainSurviveTalk, RespawnEvent, DelayedCastMincharEvent, EoEDrakeEnterVehicleEvent, ChargeRifts, CosmicSmashDamageEvent, CastRunesEvent, BoomEvent, SACActivateEvent, SACDeactivateEvent, VerasEnvenom, SuckBackEvent, CastQuill, lapseTeleport, DeathEvent, and PartyTimeEmoteEvent.
{ return true; }
IsAborted()
bool BasicEvent::IsAborted () const inline private
{ return (m_abortState == AbortState::STATE_ABORTED); }
References m_abortState, and STATE_ABORTED.
Referenced by SetAborted().
IsAbortScheduled()
bool BasicEvent::IsAbortScheduled () const inline private
{ return (m_abortState == AbortState::STATE_ABORT_SCHEDULED); }
References m_abortState, and STATE_ABORT_SCHEDULED.
IsDeletable()
virtual bool BasicEvent::IsDeletable () const inline virtual
Reimplemented in SpellEvent.
{ return true; }   // this event can be safely deleted
IsRunning()
bool BasicEvent::IsRunning () const inline private
{ return (m_abortState == AbortState::STATE_RUNNING); }
References m_abortState, and STATE_RUNNING.
Referenced by ScheduleAbort().
ScheduleAbort()
void BasicEvent::ScheduleAbort ()
{
    ASSERT(IsRunning()
           && "Tried to scheduled the abortion of an event twice!");
    m_abortState = AbortState::STATE_ABORT_SCHEDULED;
}
References ASSERT, IsRunning(), m_abortState, and STATE_ABORT_SCHEDULED.
SetAborted()
void BasicEvent::SetAborted () private
{
    ASSERT(!IsAborted()
           && "Tried to abort an already aborted event!");
    m_abortState = AbortState::STATE_ABORTED;
}
References ASSERT, IsAborted(), m_abortState, and STATE_ABORTED.
Friends And Related Function Documentation
EventProcessor
friend class EventProcessor friend
Member Data Documentation
m_abortState
AbortState BasicEvent::m_abortState {AbortState::STATE_RUNNING} private
Referenced by IsAborted(), IsAbortScheduled(), IsRunning(), ScheduleAbort(), and SetAborted().
m_addTime
uint64 BasicEvent::m_addTime {0} private
m_eventGroup
uint8 BasicEvent::m_eventGroup {0} private
m_execTime
uint64 BasicEvent::m_execTime {0} private