AzerothCore: go_suppression_device::go_suppression_deviceAI Struct Reference
go_suppression_device::go_suppression_deviceAI Struct Reference
Public Member Functions
go_suppression_deviceAI (GameObject *go)
void InitializeAI () override
void UpdateAI (uint32 diff) override
void DoAction (int32 action) override
void Activate ()
void Deactivate ()
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Private Attributes
InstanceScript * _instance
EventMap _events
bool _active
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_suppression_deviceAI()
go_suppression_device::go_suppression_deviceAI::go_suppression_deviceAI (GameObject * go) inline
: GameObjectAI(go), _instance(go->GetInstanceScript()), _active(true) { }
Member Function Documentation
Activate()
void go_suppression_device::go_suppression_deviceAI::Activate () inline
            {
                if (_active)
                    return;
                _active = true;
                if (me->GetGoState() == GO_STATE_ACTIVE)
                    me->SetGoState(GO_STATE_READY);
                me->SetLootState(GO_READY);
                me->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                _events.ScheduleEvent(EVENT_SUPPRESSION_CAST, 5s);
                me->Respawn();
            }
References _active, _events, EVENT_SUPPRESSION_CAST, GameObject::GetGoState(), GO_FLAG_NOT_SELECTABLE, GO_READY, GO_STATE_ACTIVE, GO_STATE_READY, GameObjectAI::me, GameObject::RemoveGameObjectFlag(), GameObject::Respawn(), EventMap::ScheduleEvent(), GameObject::SetGoState(), and GameObject::SetLootState().
Referenced by UpdateAI().
Deactivate()
void go_suppression_device::go_suppression_deviceAI::Deactivate () inline
            {
                if (!_active)
                    return;
                _active = false;
                me->SetGoState(GO_STATE_ACTIVE);
                me->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                _events.CancelEvent(EVENT_SUPPRESSION_CAST);
            }
References _active, _events, EventMap::CancelEvent(), EVENT_SUPPRESSION_CAST, GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, GameObjectAI::me, GameObject::SetGameObjectFlag(), and GameObject::SetGoState().
Referenced by DoAction(), and InitializeAI().
DoAction()
void go_suppression_device::go_suppression_deviceAI::DoAction (int32 action) inline override virtual
Reimplemented from GameObjectAI.
            {
                if (action == ACTION_DEACTIVATE)
                {
                    _events.CancelEvent(EVENT_SUPPRESSION_RESET);
                }
                else if (action == ACTION_DISARMED)
                {
                    Deactivate();
                    _events.CancelEvent(EVENT_SUPPRESSION_CAST);
                    if (_instance->GetBossState(DATA_BROODLORD_LASHLAYER) != DONE)
                    {
                        _events.ScheduleEvent(EVENT_SUPPRESSION_RESET, 30s, 120s);
                    }
                }
            }
References _events, _instance, ACTION_DEACTIVATE, ACTION_DISARMED, EventMap::CancelEvent(), DATA_BROODLORD_LASHLAYER, Deactivate(), DONE, EVENT_SUPPRESSION_CAST, EVENT_SUPPRESSION_RESET, InstanceScript::GetBossState(), and EventMap::ScheduleEvent().
InitializeAI()
void go_suppression_device::go_suppression_deviceAI::InitializeAI () inline override virtual
Reimplemented from GameObjectAI.
            {
                if (_instance->GetBossState(DATA_BROODLORD_LASHLAYER) == DONE)
                {
                    Deactivate();
                    return;
                }
                _events.ScheduleEvent(EVENT_SUPPRESSION_CAST, 5s);
            }
References _events, _instance, DATA_BROODLORD_LASHLAYER, Deactivate(), DONE, EVENT_SUPPRESSION_CAST, InstanceScript::GetBossState(), and EventMap::ScheduleEvent().
UpdateAI()
void go_suppression_device::go_suppression_deviceAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from GameObjectAI.
            {
                _events.Update(diff);
                while (uint32 eventId = _events.ExecuteEvent())
                {
                    switch (eventId)
                    {
                        case EVENT_SUPPRESSION_CAST:
                            if (me->GetGoState() == GO_STATE_READY)
{
                                me->CastSpell(nullptr, SPELL_SUPPRESSION_AURA);
                                me->SendCustomAnim(0);
                            }
                            _events.ScheduleEvent(EVENT_SUPPRESSION_CAST, 5s);
                            break;
                        case EVENT_SUPPRESSION_RESET:
                            Activate();
                            break;
                    }
                }
            }
References _events, Activate(), GameObject::CastSpell(), EVENT_SUPPRESSION_CAST, EVENT_SUPPRESSION_RESET, EventMap::ExecuteEvent(), GameObject::GetGoState(), GO_STATE_READY, GameObjectAI::me, EventMap::ScheduleEvent(), GameObject::SendCustomAnim(), SPELL_SUPPRESSION_AURA, and EventMap::Update().
Member Data Documentation
_active
bool go_suppression_device::go_suppression_deviceAI::_active private
Referenced by Activate(), and Deactivate().
_events
EventMap go_suppression_device::go_suppression_deviceAI::_events private
Referenced by Activate(), Deactivate(), DoAction(), InitializeAI(), and UpdateAI().
_instance
InstanceScript* go_suppression_device::go_suppression_deviceAI::_instance private
Referenced by DoAction(), and InitializeAI().