AzerothCore: npc_captain_saeed Class Reference
npc_captain_saeed Class Reference
Classes
struct npc_captain_saeedAI
Public Member Functions
npc_captain_saeed ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_captain_saeed()
npc_captain_saeed::npc_captain_saeed () inline
: CreatureScript("npc_captain_saeed") { }
Member Function Documentation
GetAI()
CreatureAI * npc_captain_saeed::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return new npc_captain_saeedAI(creature);
    }
OnGossipHello()
bool npc_captain_saeed::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (creature->IsQuestGiver())
            player->PrepareQuestMenu(creature->GetGUID());
        if (player->GetQuestStatus(QUEST_DIMENSIUS_DEVOURING) == QUEST_STATUS_INCOMPLETE)
        {
            if (!creature->AI()->GetData(1))
                AddGossipItemFor(player, GOSSIP_MENU_SAEED, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
            else
                AddGossipItemFor(player, GOSSIP_MENU_SAEED, 1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
        }
        SendGossipMenuFor(player, creature->AI()->GetData(1) ? TEXT_NPC_SAEED_START_FIGHT : TEXT_NPC_SAEED_DEFAULT, creature->GetGUID());
        return true;
    }
References AddGossipItemFor(), Creature::AI(), UnitAI::GetData(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_MENU_SAEED, GOSSIP_SENDER_MAIN, Unit::IsQuestGiver(), Player::PrepareQuestMenu(), QUEST_DIMENSIUS_DEVOURING, QUEST_STATUS_INCOMPLETE, SendGossipMenuFor(), TEXT_NPC_SAEED_DEFAULT, and TEXT_NPC_SAEED_START_FIGHT.
OnGossipSelect()
bool npc_captain_saeed::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
    {
        ClearGossipMenuFor(player);
        if (uiAction == GOSSIP_ACTION_INFO_DEF + 1)
        {
            creature->AI()->SetGUID(player->GetGUID(), DATA_START_ENCOUNTER);
            player->KilledMonsterCredit(creature->GetEntry());
        }
        else if (uiAction == GOSSIP_ACTION_INFO_DEF + 2)
        {
            creature->AI()->SetGUID(player->GetGUID(), DATA_START_FIGHT);
        }
        CloseGossipMenuFor(player);
        return true;
    }
References Creature::AI(), ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_START_ENCOUNTER, DATA_START_FIGHT, Object::GetEntry(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, Player::KilledMonsterCredit(), and UnitAI::SetGUID().