AzerothCore: achievement_arena_by_type Class Reference
achievement_arena_by_type Class Reference
Public Member Functions
achievement_arena_by_type (char const *name, uint8 arenaType)
bool OnCheck (Player *source, Unit *, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
virtual bool OnCheck (Player *, Unit *, uint32)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Private Attributes
uint8 const _arenaType
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
achievement_arena_by_type()
achievement_arena_by_type::achievement_arena_by_type (char const * name, uint8 arenaType) inline
                                                                 : AchievementCriteriaScript(name),
        _arenaType(arenaType)
    {
    }
Member Function Documentation
OnCheck()
bool achievement_arena_by_type::OnCheck (Player * source, Unit * , uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
    {
        return source->InArena() && source->GetBattleground()->GetArenaType() == _arenaType;
    }
References _arenaType, Battleground::GetArenaType(), Player::GetBattleground(), and Player::InArena().
Member Data Documentation
_arenaType
uint8 const achievement_arena_by_type::_arenaType private
Referenced by OnCheck().