AzerothCore: WaypointMovementGenerator< Creature > Class Reference
WaypointMovementGenerator< Creature > Class Reference
#include "WaypointMovementGenerator.h"
Public Member Functions
WaypointMovementGenerator (uint32 _path_id=0, bool _repeating=true, bool _stalled=false)
~WaypointMovementGenerator ()
void DoInitialize (Creature *)
void DoFinalize (Creature *)
void DoReset (Creature *)
bool DoUpdate (Creature *, uint32 diff)
void Pause (uint32 timer=0)
void Resume (uint32 overrideTimer)
void MovementInform (Creature *)
MovementGeneratorType GetMovementGeneratorType ()
void LoadPath (Creature *)
Public Member Functions inherited from MovementGeneratorMedium< Creature, WaypointMovementGenerator< Creature > >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual void Initialize (Unit *)=0
virtual void Finalize (Unit *)=0
virtual void Reset (Unit *)=0
virtual bool Update (Unit *, uint32 time_diff)=0
virtual MovementGeneratorType GetMovementGeneratorType ()=0
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual void Pause (uint32)
virtual void Resume (uint32)
virtual bool GetResetPosition (float &, float &, float &)
Public Member Functions inherited from PathMovementBase< T, P >
PathMovementBase ()
PathMovementBase (P path)
virtual ~PathMovementBase ()
uint32 GetCurrentNode () const
Private Member Functions
void Stop (int32 time)
bool Stopped ()
bool CanMove (int32 diff)
void OnArrived (Creature *)
bool StartMove (Creature *)
void StartMoveNow (Creature *creature)
Private Attributes
TimeTrackerSmall i_nextMoveTime
bool m_isArrivalDone
uint32 path_id
bool repeating
bool stalled
Additional Inherited Members
Protected Attributes inherited from PathMovementBase< T, P >
P i_path
uint32 i_currentNode
Detailed Description
Constructor & Destructor Documentation
WaypointMovementGenerator()
WaypointMovementGenerator< Creature >::WaypointMovementGenerator (uint32 _path_id = 0, bool _repeating = true, bool _stalled = false) inline
        : PathMovementBase((WaypointPath const*)nullptr), i_nextMoveTime(0), m_isArrivalDone(false), path_id(_path_id), repeating(_repeating), stalled(_stalled)  {}
~WaypointMovementGenerator()
WaypointMovementGenerator< Creature >::~WaypointMovementGenerator () inline
{ i_path = nullptr; }
Member Function Documentation
CanMove()
bool WaypointMovementGenerator< Creature >::CanMove (int32 diff) inline private
    {
        i_nextMoveTime.Update(diff);
        return i_nextMoveTime.Passed();
    }
DoFinalize()
void WaypointMovementGenerator< Creature >::DoFinalize (Creature * creature)
{
    creature->ClearUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
    creature->SetWalk(false);
}
References Unit::ClearUnitState(), Creature::SetWalk(), UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoInitialize()
void WaypointMovementGenerator< Creature >::DoInitialize (Creature * creature)
{
    LoadPath(creature);
    creature->AddUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
}
References Unit::AddUnitState(), UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoReset()
void WaypointMovementGenerator< Creature >::DoReset (Creature * creature)
{
    if (stalled)
    {
        return;
    }
    creature->AddUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
    StartMoveNow(creature);
}
References Unit::AddUnitState(), UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoUpdate()
bool WaypointMovementGenerator< Creature >::DoUpdate (Creature * creature, uint32 diff)
{
    // Waypoint movement can be switched on/off
    // This is quite handy for escort quests and other stuff
    if (stalled)
    {
        Stop(1000);
        return true;
    }
    if (creature->HasUnitState(UNIT_STATE_NOT_MOVE) || creature->IsMovementPreventedByCasting())
    {
        creature->StopMoving();
        Stop(1000);
        return true;
    }
    // prevent a crash at empty waypoint path.
    if (!i_path || i_path->empty())
        return false;
    // Xinef: Dont allow dead creatures to move
    if (!creature->IsAlive())
        return false;
    if (Stopped())
    {
        if (CanMove(diff))
            return StartMove(creature);
    }
    else
    {
        bool finished = creature->movespline->Finalized();
        // xinef: code to detect pre-empetively if we should start movement to next waypoint
        // xinef: do not start pre-empetive movement if current node has delay or we are ending waypoint movement
        //if (!finished && !i_path->at(i_currentNode)->delay && ((i_currentNode != i_path->size() - 1) || repeating))
        //    finished = (creature->movespline->_Spline().length(creature->movespline->_currentSplineIdx() + 1) - creature->movespline->timePassed()) < 200;
        if (finished)
        {
            OnArrived(creature);
            return StartMove(creature);
        }
    }
    return true;
}
References Movement::MoveSpline::Finalized(), Unit::HasUnitState(), Unit::IsAlive(), Creature::IsMovementPreventedByCasting(), Unit::movespline, Unit::StopMoving(), and UNIT_STATE_NOT_MOVE.
GetMovementGeneratorType()
MovementGeneratorType WaypointMovementGenerator< Creature >::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
{ return WAYPOINT_MOTION_TYPE; }
References WAYPOINT_MOTION_TYPE.
LoadPath()
void WaypointMovementGenerator< Creature >::LoadPath (Creature * creature)
{
    if (!path_id)
        path_id = creature->GetWaypointPath();
    i_path = sWaypointMgr->GetPath(path_id);
    if (!i_path)
    {
        // No movement found for entry
        LOG_ERROR("sql.sql", "WaypointMovementGenerator::LoadPath: creature {} ({}) doesn't have waypoint path id: {}",
            creature->GetName(), creature->GetGUID().ToString(), path_id);
        return;
    }
    StartMoveNow(creature);
}
References Object::GetGUID(), WorldObject::GetName(), Creature::GetWaypointPath(), LOG_ERROR, sWaypointMgr, and ObjectGuid::ToString().
MovementInform()
void WaypointMovementGenerator< Creature >::MovementInform (Creature * creature)
{
    if (creature->AI())
        creature->AI()->MovementInform(WAYPOINT_MOTION_TYPE, i_currentNode);
    if (Unit* owner = creature->GetCharmerOrOwner())
    {
        if (UnitAI* AI = owner->GetAI())
        {
            AI->SummonMovementInform(creature, WAYPOINT_MOTION_TYPE, i_currentNode);
        }
    }
    else
    {
        if (TempSummon* tempSummon = creature->ToTempSummon())
        {
            if (Unit* owner = tempSummon->GetSummonerUnit())
            {
                if (UnitAI* AI = owner->GetAI())
                {
                    AI->SummonMovementInform(creature, WAYPOINT_MOTION_TYPE, i_currentNode);
                }
            }
        }
    }
}
References Creature::AI(), Unit::GetCharmerOrOwner(), CreatureAI::MovementInform(), Unit::ToTempSummon(), and WAYPOINT_MOTION_TYPE.
OnArrived()
void WaypointMovementGenerator< Creature >::OnArrived (Creature * creature) private
{
    if (!i_path || i_path->empty())
        return;
    if (m_isArrivalDone)
        return;
    creature->ClearUnitState(UNIT_STATE_ROAMING_MOVE);
    m_isArrivalDone = true;
    if (i_path->at(i_currentNode)->event_id && urand(0, 99) < i_path->at(i_currentNode)->event_chance)
    {
        LOG_DEBUG("maps.script", "Creature movement start script {} at point {} for {}.",
            i_path->at(i_currentNode)->event_id, i_currentNode, creature->GetGUID().ToString());
        creature->ClearUnitState(UNIT_STATE_ROAMING_MOVE);
        creature->GetMap()->ScriptsStart(sWaypointScripts, i_path->at(i_currentNode)->event_id, creature, nullptr);
    }
    // Inform script
    MovementInform(creature);
    creature->UpdateWaypointID(i_currentNode);
    if (i_path->at(i_currentNode)->delay)
    {
        creature->ClearUnitState(UNIT_STATE_ROAMING_MOVE);
        Stop(i_path->at(i_currentNode)->delay);
    }
}
References Unit::ClearUnitState(), Object::GetGUID(), WorldObject::GetMap(), LOG_DEBUG, Map::ScriptsStart(), sWaypointScripts, ObjectGuid::ToString(), UNIT_STATE_ROAMING_MOVE, Creature::UpdateWaypointID(), and urand().
Pause()
void WaypointMovementGenerator< Creature >::Pause (uint32 timer = 0) virtual
Reimplemented from MovementGenerator.
{
    if (timer)
        i_nextMoveTime.Reset(timer);
    else
    {
        // No timer? Will be paused forever until ::Resume is called
        stalled = true;
        i_nextMoveTime.Reset(1);
    }
}
Resume()
void WaypointMovementGenerator< Creature >::Resume (uint32 overrideTimer) virtual
Reimplemented from MovementGenerator.
{
    stalled = false;
}
StartMove()
bool WaypointMovementGenerator< Creature >::StartMove (Creature * creature) private
If creature is on transport, we assume waypoints set in DB are already transport offsets
Do not use formationDest here, MoveTo requires transport offsets due to DisableTransportPathTransformations() call but formationDest contains global coordinates
{
    if (!i_path || i_path->empty())
        return false;
    // Xinef: Dont allow dead creatures to move
    if (!creature->IsAlive())
        return false;
    if (Stopped())
        return true;
    bool transportPath = creature->HasUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT) && creature->GetTransGUID();
    if (m_isArrivalDone)
    {
        // Xinef: not true... update this at every waypoint!
        //if ((i_currentNode == i_path->size() - 1) && !repeating) // If that's our last waypoint
        {
            float x = i_path->at(i_currentNode)->x;
            float y = i_path->at(i_currentNode)->y;
            float z = i_path->at(i_currentNode)->z;
            float o = creature->GetOrientation();
            if (!transportPath)
                creature->SetHomePosition(x, y, z, o);
            else
            {
                if (Transport* trans = (creature->GetTransport() ? creature->GetTransport()->ToMotionTransport() : nullptr))
                {
                    o -= trans->GetOrientation();
                    creature->SetTransportHomePosition(x, y, z, o);
                    trans->CalculatePassengerPosition(x, y, z, &o);
                    creature->SetHomePosition(x, y, z, o);
                }
                else
                    transportPath = false;
                // else if (vehicle) - this should never happen, vehicle offsets are const
            }
        }
        // Xinef: moved the upper IF here
        if ((i_currentNode == i_path->size() - 1) && !repeating) // If that's our last waypoint
        {
            creature->AI()->PathEndReached(path_id);
            creature->GetMotionMaster()->Initialize();
            return false;
        }
        i_currentNode = (i_currentNode + 1) % i_path->size();
    }
    // xinef: do not initialize motion if we got stunned in movementinform
    if (creature->HasUnitState(UNIT_STATE_NOT_MOVE) || creature->IsMovementPreventedByCasting())
    {
        return true;
    }
    WaypointData const* node = i_path->at(i_currentNode);
    m_isArrivalDone = false;
    creature->AddUnitState(UNIT_STATE_ROAMING_MOVE);
    Movement::Location formationDest(node->x, node->y, node->z, 0.0f);
    Movement::MoveSplineInit init(creature);
    if (transportPath)
    {
        init.DisableTransportPathTransformations();
        if (TransportBase* trans = creature->GetDirectTransport())
            trans->CalculatePassengerPosition(formationDest.x, formationDest.y, formationDest.z, &formationDest.orientation);
    }
    float z = node->z;
    creature->UpdateAllowedPositionZ(node->x, node->y, z);
    init.MoveTo(node->x, node->y, z, true, true);
    if (node->orientation.has_value() && node->delay > 0)
        init.SetFacing(*node->orientation);
    switch (node->move_type)
    {
        case WAYPOINT_MOVE_TYPE_LAND:
            init.SetAnimation(Movement::ToGround);
            break;
        case WAYPOINT_MOVE_TYPE_TAKEOFF:
            init.SetAnimation(Movement::ToFly);
            break;
        case WAYPOINT_MOVE_TYPE_RUN:
            init.SetWalk(false);
            break;
        case WAYPOINT_MOVE_TYPE_WALK:
            init.SetWalk(true);
            break;
        default:
            break;
    }
    init.Launch();
    //Call for creature group update
    if (creature->GetFormation() && creature->GetFormation()->GetLeader() == creature)
        creature->GetFormation()->LeaderMoveTo(formationDest.x, formationDest.y, formationDest.z, node->move_type);
    return true;
}
References Unit::AddUnitState(), Creature::AI(), WaypointData::delay, Movement::MoveSplineInit::DisableTransportPathTransformations(), Unit::GetDirectTransport(), Creature::GetFormation(), CreatureGroup::GetLeader(), Unit::GetMotionMaster(), Position::GetOrientation(), Unit::GetTransGUID(), WorldObject::GetTransport(), Unit::HasUnitMovementFlag(), Unit::HasUnitState(), MotionMaster::Initialize(), Unit::IsAlive(), Creature::IsMovementPreventedByCasting(), Movement::MoveSplineInit::Launch(), CreatureGroup::LeaderMoveTo(), WaypointData::move_type, MOVEMENTFLAG_ONTRANSPORT, Movement::MoveSplineInit::MoveTo(), Movement::Location::orientation, WaypointData::orientation, CreatureAI::PathEndReached(), Movement::MoveSplineInit::SetAnimation(), Movement::MoveSplineInit::SetFacing(), Creature::SetHomePosition(), Creature::SetTransportHomePosition(), Movement::MoveSplineInit::SetWalk(), Movement::ToFly, Movement::ToGround, GameObject::ToMotionTransport(), UNIT_STATE_NOT_MOVE, UNIT_STATE_ROAMING_MOVE, WorldObject::UpdateAllowedPositionZ(), WAYPOINT_MOVE_TYPE_LAND, WAYPOINT_MOVE_TYPE_RUN, WAYPOINT_MOVE_TYPE_TAKEOFF, WAYPOINT_MOVE_TYPE_WALK, WaypointData::x, WaypointData::y, and WaypointData::z.
StartMoveNow()
void WaypointMovementGenerator< Creature >::StartMoveNow (Creature * creature) inline private
    {
        i_nextMoveTime.Reset(0);
        StartMove(creature);
    }
Stop()
void WaypointMovementGenerator< Creature >::Stop (int32 time) inline private
{ i_nextMoveTime.Reset(time);}
Stopped()
bool WaypointMovementGenerator< Creature >::Stopped () inline private
{ return !i_nextMoveTime.Passed();}
Member Data Documentation
i_nextMoveTime
TimeTrackerSmall WaypointMovementGenerator< Creature >::i_nextMoveTime private
m_isArrivalDone
bool WaypointMovementGenerator< Creature >::m_isArrivalDone private
path_id
uint32 WaypointMovementGenerator< Creature >::path_id private
repeating
bool WaypointMovementGenerator< Creature >::repeating private
stalled
bool WaypointMovementGenerator< Creature >::stalled private