AzeorthCore: boss_koralon::boss_koralonAI Struct Reference
boss_koralon::boss_koralonAI Struct Reference
Public Member Functions
boss_koralonAI (Creature *creature)
void Reset () override
void AttackStart (Unit *who) override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
uint32 rotateTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_koralonAI()
boss_koralon::boss_koralonAI::boss_koralonAI (Creature * creature) inline
                                           : ScriptedAI(creature)
        {
            pInstance = me->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
AttackStart()
void boss_koralon::boss_koralonAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (me->HasAura(SPELL_STONED_AURA))
                return;
            ScriptedAI::AttackStart(who);
        }
References ScriptedAI::AttackStart(), Unit::HasAura(), ScriptedAI::me, and SPELL_STONED_AURA.
EnterCombat()
void boss_koralon::boss_koralonAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            me->CastSpell(me, SPELL_BURNING_FURY, true);
            events.ScheduleEvent(EVENT_BURNING_BREATH, 10000);
            events.ScheduleEvent(EVENT_METEOR_FISTS, 30000);
            events.ScheduleEvent(EVENT_FLAME_CINDER, 20000);
            if (pInstance)
                pInstance->SetData(EVENT_KORALON, IN_PROGRESS);
        }
References Unit::CastSpell(), EVENT_BURNING_BREATH, EVENT_FLAME_CINDER, EVENT_KORALON, EVENT_METEOR_FISTS, IN_PROGRESS, ScriptedAI::me, pInstance, ZoneScript::SetData(), and SPELL_BURNING_FURY.
JustDied()
void boss_koralon::boss_koralonAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (pInstance)
                pInstance->SetData(EVENT_KORALON, DONE);
        }
References DONE, EVENT_KORALON, pInstance, and ZoneScript::SetData().
Reset()
void boss_koralon::boss_koralonAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            rotateTimer = 0;
            events.Reset();
            if (pInstance)
            {
                if (pInstance->GetData(DATA_STONED))
                {
                    if (Aura* aur = me->AddAura(SPELL_STONED_AURA, me))
                    {
                        aur->SetMaxDuration(60 * MINUTE * IN_MILLISECONDS);
                        aur->SetDuration(60 * MINUTE * IN_MILLISECONDS);
                    }
                }
                pInstance->SetData(EVENT_KORALON, NOT_STARTED);
            }
        }
References Unit::AddAura(), DATA_STONED, EVENT_KORALON, ZoneScript::GetData(), IN_MILLISECONDS, ScriptedAI::me, MINUTE, NOT_STARTED, pInstance, rotateTimer, ZoneScript::SetData(), and SPELL_STONED_AURA.
UpdateAI()
void boss_koralon::boss_koralonAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (rotateTimer)
            {
                me->SetUInt64Value(UNIT_FIELD_CHANNEL_OBJECT, 0);
                rotateTimer += diff;
                if (rotateTimer >= 3000)
                {
                    if (!me->HasUnitMovementFlag(MOVEMENTFLAG_LEFT))
                    {
                        me->SetUnitMovementFlags(MOVEMENTFLAG_LEFT);
                        me->SendMovementFlagUpdate();
                        rotateTimer = 1;
                        return;
                    }
                    else
                    {
                        me->RemoveUnitMovementFlag(MOVEMENTFLAG_LEFT);
                        me->SendMovementFlagUpdate();
                        rotateTimer = 0;
                        return;
                    }
                }
            }
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_BURNING_BREATH:
                    rotateTimer = 1500;
                    me->CastSpell(me, SPELL_BURNING_BREATH, false);
                    events.RepeatEvent(45000);
                    break;
                case EVENT_METEOR_FISTS:
                    me->CastSpell(me, SPELL_METEOR_FISTS, true);
                    events.RepeatEvent(45000);
                    break;
                case EVENT_FLAME_CINDER:
                    me->CastSpell(me, SPELL_FLAMING_CINDER, true);
                    events.RepeatEvent(30000);
                    break;
                default:
                    break;
            }
            DoMeleeAttackIfReady();
        }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_BURNING_BREATH, EVENT_FLAME_CINDER, EVENT_METEOR_FISTS, Unit::HasUnitMovementFlag(), Unit::HasUnitState(), ScriptedAI::me, MOVEMENTFLAG_LEFT, Unit::RemoveUnitMovementFlag(), rotateTimer, Unit::SendMovementFlagUpdate(), Object::SetUInt64Value(), Unit::SetUnitMovementFlags(), SPELL_BURNING_BREATH, SPELL_FLAMING_CINDER, SPELL_METEOR_FISTS, UNIT_FIELD_CHANNEL_OBJECT, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_koralon::boss_koralonAI::events
pInstance
InstanceScript* boss_koralon::boss_koralonAI::pInstance
Referenced by boss_koralonAI(), EnterCombat(), JustDied(), and Reset().
rotateTimer
uint32 boss_koralon::boss_koralonAI::rotateTimer
Referenced by Reset(), and UpdateAI().