AzerothCore: boss_archimonde Struct Reference
boss_archimonde Struct Reference
Public Member Functions
boss_archimonde (Creature *creature)
void Reset () override
void DoAction (int32 action) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void KilledUnit (Unit *) override
void SetGUID (ObjectGuid guid, int32 type) override
void EnterEvadeMode (EvadeReason why) override
void JustSummoned (Creature *summoned) override
void DoCastDoomFire ()
void UnleashSoulCharge ()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint8 _wispCount
bool _isChanneling
bool _enraged
std::vector< uint32 > _availableAuras
std::vector< uint32 > _availableSpells
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_archimonde()
boss_archimonde::boss_archimonde (Creature * creature) inline
                                        : BossAI(creature, DATA_ARCHIMONDE)
    {
        scheduler.SetValidator([&]
        {
            return !me->HasUnitState(UNIT_STATE_CASTING);
        });
    }
References Unit::HasUnitState(), ScriptedAI::me, CreatureAI::scheduler, TaskScheduler::SetValidator(), and UNIT_STATE_CASTING.
Member Function Documentation
DoAction()
void boss_archimonde::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        switch (action)
        {
            case ACTION_BECOME_ACTIVE_AND_CHANNEL:
                me->SetReactState(REACT_AGGRESSIVE);
                me->SetVisible(true);
                if (!_isChanneling)
                {
                    if (Creature* nordrassil = me->SummonCreature(CREATURE_CHANNEL_TARGET, nordrassilPosition, TEMPSUMMON_TIMED_DESPAWN, 1200000))
                    {
                        DoCast(nordrassil, SPELL_DRAIN_WORLD_TREE);
                        _isChanneling = true;
                        nordrassil->AI()->DoCast(me, SPELL_DRAIN_WORLD_TREE_2, true);
                    }
                }
                break;
        }
    }
References _isChanneling, ACTION_BECOME_ACTIVE_AND_CHANNEL, CREATURE_CHANNEL_TARGET, UnitAI::DoCast(), ScriptedAI::me, nordrassilPosition, REACT_AGGRESSIVE, Creature::SetReactState(), Unit::SetVisible(), SPELL_DRAIN_WORLD_TREE, SPELL_DRAIN_WORLD_TREE_2, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
Referenced by Reset().
DoCastDoomFire()
void boss_archimonde::DoCastDoomFire () inline
    {
        // hack because spell doesn't work?
        Talk(SAY_DOOMFIRE);
        float angle = 2 * M_PI * rand() / RAND_MAX;
        float x = me->GetPositionX() + DOOMFIRE_OFFSET * cos(angle);
        float y = me->GetPositionY() + DOOMFIRE_OFFSET * sin(angle);
        Position spiritPosition = Position(x, y, me->GetPositionZ(), Position::NormalizeOrientation(angle + M_PI)); //spirit faces archimonde on spawn
        Position doomfirePosition = Position(x, y, me->GetPositionZ());
        if (Creature* doomfireSpirit = me->SummonCreature(CREATURE_DOOMFIRE_SPIRIT, spiritPosition, TEMPSUMMON_TIMED_DESPAWN, 27000))
        {
            if (Creature* doomfire = me->SummonCreature(CREATURE_DOOMFIRE, doomfirePosition, TEMPSUMMON_TIMED_DESPAWN, 27000))
            {
                doomfireSpirit->SetWalk(false);
                doomfireSpirit->SetReactState(REACT_PASSIVE);
                doomfire->SetReactState(REACT_PASSIVE);
                doomfire->GetMotionMaster()->MoveFollow(doomfireSpirit, 0.0f, 0.0f);
            }
        }
    }
References CREATURE_DOOMFIRE, CREATURE_DOOMFIRE_SPIRIT, DOOMFIRE_OFFSET, Position::NormalizeOrientation(), REACT_PASSIVE, SAY_DOOMFIRE, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
Referenced by JustEngagedWith().
EnterEvadeMode()
void boss_archimonde::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from BossAI.
    {
        instance->SetData(DATA_RESET_NIGHT_ELF, 1);
        BossAI::EnterEvadeMode(why);
    }
References DATA_RESET_NIGHT_ELF, and BossAI::EnterEvadeMode().
JustEngagedWith()
void boss_archimonde::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
    {
        _JustEngagedWith();
        me->InterruptNonMeleeSpells(false);
        Talk(SAY_AGGRO);
        ScheduleTimedEvent(25s, 35s, [&]
        {
            if (DoCastRandomTarget(SPELL_AIR_BURST, 1) == SPELL_CAST_OK)
            {
                scheduler.DelayGroup(GROUP_FEAR, 5s);
                Talk(SAY_AIR_BURST);
            }
        }, 25s, 40s);
        ScheduleTimedEvent(8s, [&]
        {
            DoCastDoomFire();
        }, 8s);
        ScheduleTimedEvent(25s, 35s, [&]
        {
            DoCastRandomTarget(SPELL_GRIP_OF_THE_LEGION);
        }, 5s, 25s);
        ScheduleTimedEvent(5s, [&]
        {
            if (me->GetExactDist2d(nordrassilPosition) < 75.0f)
            {
                if (!_enraged)
                {
                    _enraged = true;
                    Talk(SAY_ENRAGE);
                    ScheduleTimedEvent(1s, [&]
                    {
                        DoCastVictim(SPELL_RED_SKY_EFFECT);
                        DoCastVictim(SPELL_HAND_OF_DEATH);
                    }, 3s);
                }
            }
        }, 5s);
        ScheduleTimedEvent(5000ms, [&]
        {
            bool noPlayersInRange = true;
            if (Map* map = me->GetMap())
            {
                map->DoForAllPlayers([&noPlayersInRange, this](Player* player)
                {
                    if (me->IsWithinMeleeRange(player))
                    {
                        noPlayersInRange = false;
                        return false;
                    }
                    return true;
                });
            }
            if (noPlayersInRange)
            {
                DoCastRandomTarget(SPELL_FINGER_OF_DEATH);
            }
        }, 3500ms);
        ScheduleTimedEvent(10min, [&]
        {
            DoCastVictim(SPELL_RED_SKY_EFFECT);
            DoCastVictim(SPELL_HAND_OF_DEATH);
        }, 3s);
        scheduler.Schedule(40s, GROUP_FEAR, [this](TaskContext context)
        {
            DoCastAOE(SPELL_FEAR);
            context.Repeat(42s);
        });
        instance->SetData(DATA_SPAWN_WAVES, 1);
    }
References BossAI::_JustEngagedWith(), TaskScheduler::DelayGroup(), DoCastDoomFire(), UnitAI::DoCastRandomTarget(), Position::GetExactDist2d(), GROUP_FEAR, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, nordrassilPosition, SAY_AGGRO, SAY_AIR_BURST, CreatureAI::scheduler, ScriptedAI::ScheduleTimedEvent(), SPELL_AIR_BURST, SPELL_CAST_OK, and SPELL_GRIP_OF_THE_LEGION.
JustSummoned()
void boss_archimonde::JustSummoned (Creature * summoned) inline override virtual
Reimplemented from BossAI.
    {
        BossAI::JustSummoned(summoned);
        if (summoned->GetEntry() == CREATURE_ANCIENT_WISP)
        {
            summoned->AI()->AttackStart(me);
        }
        else if (summoned->GetEntry() == CREATURE_DOOMFIRE)
        {
            summoned->CastSpell(summoned, SPELL_DOOMFIRE_SPAWN);
            summoned->CastSpell(summoned, SPELL_DOOMFIRE, true, 0, 0, me->GetGUID());
        }
        else
        {
            summoned->SetFaction(me->GetFaction()); //remove?
            summoned->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            summoned->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
        }
    }
References Creature::AI(), UnitAI::AttackStart(), Unit::CastSpell(), CREATURE_ANCIENT_WISP, CREATURE_DOOMFIRE, Object::GetEntry(), BossAI::JustSummoned(), Unit::SetFaction(), Unit::SetUnitFlag(), SPELL_DOOMFIRE, SPELL_DOOMFIRE_SPAWN, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
KilledUnit()
void boss_archimonde::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
    {
        Talk(SAY_SLAY);
    }
References SAY_SLAY.
Reset()
void boss_archimonde::Reset () inline override virtual
Reimplemented from BossAI.
    {
        _Reset();
        _wispCount = 0;
        _isChanneling = false;
        _enraged = false;
        _availableAuras.clear();
        _availableSpells.clear();
        if (instance->GetBossState(DATA_AZGALOR) != DONE)
        {
            me->SetVisible(false);
            me->SetReactState(REACT_PASSIVE);
        }
        else
        {
            DoAction(ACTION_BECOME_ACTIVE_AND_CHANNEL);
        }
        ScheduleHealthCheckEvent(10, [&]{
            scheduler.CancelAll();
            me->SetReactState(REACT_PASSIVE);
            DoCastAOE(SPELL_PROTECTION_OF_ELUNE, true);
            Talk(SAY_ENRAGE);
            _enraged = true;
            me->GetMotionMaster()->Clear(false);
            me->GetMotionMaster()->MoveIdle();
            ScheduleTimedEvent(1s, [&]
            {
                if (_wispCount >= 30)
                {
                    me->KillSelf();
                }
                Position wispPosition = { me->GetPositionX() + float(rand() % WISP_OFFSET), me->GetPositionY() + float(rand() % WISP_OFFSET), me->GetPositionZ(), 0.0f };
                if (Creature* wisp = me->SummonCreature(CREATURE_ANCIENT_WISP, wispPosition))
                {
                    wisp->AI()->DoCast(me, SPELL_ANCIENT_SPARK);
                    ++_wispCount;
                }
            }, 1500ms);
            ScheduleTimedEvent(1500ms, [&]
            {
                DoCastVictim(SPELL_RED_SKY_EFFECT);
                DoCastVictim(SPELL_HAND_OF_DEATH);
            }, 3s);
        });
    }
References _availableAuras, _availableSpells, _enraged, _isChanneling, BossAI::_Reset(), _wispCount, ACTION_BECOME_ACTIVE_AND_CHANNEL, TaskScheduler::CancelAll(), MotionMaster::Clear(), CREATURE_ANCIENT_WISP, DATA_AZGALOR, DoAction(), UnitAI::DoCastAOE(), UnitAI::DoCastVictim(), DONE, InstanceScript::GetBossState(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), BossAI::instance, Unit::KillSelf(), ScriptedAI::me, MotionMaster::MoveIdle(), REACT_PASSIVE, SAY_ENRAGE, BossAI::ScheduleHealthCheckEvent(), CreatureAI::scheduler, ScriptedAI::ScheduleTimedEvent(), Creature::SetReactState(), Unit::SetVisible(), SPELL_HAND_OF_DEATH, SPELL_PROTECTION_OF_ELUNE, SPELL_RED_SKY_EFFECT, WorldObject::SummonCreature(), and WISP_OFFSET.
SetGUID()
void boss_archimonde::SetGUID (ObjectGuid guid, int32 type) inline override virtual
Reimplemented from UnitAI.
    {
        if (type == GUID_GAIN_SOUL_CHARGE_PLAYER)
        {
            if (Player* player = ObjectAccessor::GetPlayer(*me, guid))
            {
                switch (player->getClass())
                {
                    case CLASS_MAGE:
                    case CLASS_PRIEST:
                    case CLASS_WARLOCK:
                        player->CastSpell(me, SPELL_SOUL_CHARGE_RED, true);
                        break;
                    case CLASS_DEATH_KNIGHT:
                    case CLASS_PALADIN:
                    case CLASS_ROGUE:
                    case CLASS_WARRIOR:
                        player->CastSpell(me, SPELL_SOUL_CHARGE_YELLOW, true);
                        break;
                    case CLASS_DRUID:
                    case CLASS_HUNTER:
                    case CLASS_SHAMAN:
                        player->CastSpell(me, SPELL_SOUL_CHARGE_GREEN, true);
                        break;
                    case CLASS_NONE:
                    default:
                        break;
                }
                scheduler.Schedule(2s, 10s, [this](TaskContext)
                {
                    UnleashSoulCharge();
                });
            }
        }
    }
References CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_NONE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, ObjectAccessor::GetPlayer(), GUID_GAIN_SOUL_CHARGE_PLAYER, SPELL_SOUL_CHARGE_GREEN, SPELL_SOUL_CHARGE_RED, and SPELL_SOUL_CHARGE_YELLOW.
UnleashSoulCharge()
void boss_archimonde::UnleashSoulCharge () inline
    {
        me->InterruptNonMeleeSpells(false);
        //add all auras to spells
        for (uint8 n = 0; n < 3; ++n)
        {
            if (me->HasAura(availableChargeAurasAndSpells[n][0]))
            {
                _availableAuras.push_back(availableChargeAurasAndSpells[n][0]);
                _availableSpells.push_back(availableChargeAurasAndSpells[n][1]);
            }
        }
        //only unleash when we found spells and auras
        if (!_availableAuras.empty() && !_availableSpells.empty())
        {
            //coin flip to swap front and back item
            if (urand(0, 1))
            {
                _availableAuras.insert(_availableAuras.begin(), _availableAuras.back());
                _availableAuras.pop_back();
                _availableSpells.insert(_availableSpells.begin(), _availableSpells.back());
                _availableSpells.pop_back();
            }
            //remove aura and cast spell
            me->RemoveAuraFromStack(_availableAuras.front());
            DoCastVictim(_availableSpells.front());
            //clear to clean vectors
            _availableAuras.clear();
            _availableSpells.clear();
        }
    }
References availableChargeAurasAndSpells, and urand().
Member Data Documentation
_availableAuras
std::vector<uint32> boss_archimonde::_availableAuras private
Referenced by Reset().
_availableSpells
std::vector<uint32> boss_archimonde::_availableSpells private
Referenced by Reset().
_enraged
bool boss_archimonde::_enraged private
Referenced by Reset().
_isChanneling
bool boss_archimonde::_isChanneling private
Referenced by DoAction(), and Reset().
_wispCount
uint8 boss_archimonde::_wispCount private
Referenced by Reset().