AzerothCore: AddonMgr Namespace Reference
AddonMgr Namespace Reference
Namespaces
namespace anonymous_namespace{AddonMgr.cpp}
Typedefs
typedef std::list< BannedAddon > BannedAddonList
Functions
void LoadFromDB ()
void SaveAddon (AddonInfo const &addon)
SavedAddon const * GetAddonInfo (const std::string &name)
BannedAddonList const * GetBannedAddons ()
Typedef Documentation
BannedAddonList
typedef std::list<BannedAddon> AddonMgr::BannedAddonList
Function Documentation
GetAddonInfo()
SavedAddon const * AddonMgr::GetAddonInfo (const std::string & name)
    {
        for (auto const& addon : m_knownAddons)
        {
            if (addon.Name == name)
            {
                return &addon;
            }
        }
        return nullptr;
    }
Referenced by WorldSession::ReadAddonsInfo().
GetBannedAddons()
BannedAddonList const * AddonMgr::GetBannedAddons ()
    {
        return &m_bannedAddons;
    }
Referenced by WorldSession::SendAddonsInfo().
LoadFromDB()
void AddonMgr::LoadFromDB ()
    {
        uint32 oldMSTime = getMSTime();
        QueryResult result = CharacterDatabase.Query("SELECT name, crc FROM addons");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 known addons. DB table `addons` is empty!");
            LOG_INFO("server.loading", " ");
            return;
        }
        uint32 count = 0;
        do
        {
            Field* fields = result->Fetch();
            std::string name = fields[0].Get<std::string>();
            uint32 crc = fields[1].Get<uint32>();
            m_knownAddons.push_back(SavedAddon(name, crc));
            ++count;
        } while (result->NextRow());
        LOG_INFO("server.loading", ">> Loaded {} known addons in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
        LOG_INFO("server.loading", " ");
        oldMSTime = getMSTime();
        result = CharacterDatabase.Query("SELECT id, name, version, UNIX_TIMESTAMP(timestamp) FROM banned_addons");
        if (result)
        {
            uint32 count2 = 0;
            uint32 offset = 102;
            do
            {
                Field* fields = result->Fetch();
                BannedAddon addon{};
                addon.Id = fields[0].Get<uint32>() + offset;
                addon.Timestamp = uint32(fields[3].Get<uint64>());
                addon.NameMD5 = Acore::Crypto::MD5::GetDigestOf(fields[1].Get<std::string>());
                addon.VersionMD5 = Acore::Crypto::MD5::GetDigestOf(fields[2].Get<std::string>());
                m_bannedAddons.emplace_back(addon);
                ++count2;
            } while (result->NextRow());
            LOG_INFO("server.loading", ">> Loaded {} banned addons in {} ms", count2, GetMSTimeDiffToNow(oldMSTime));
            LOG_INFO("server.loading", " ");
        }
    }
References CharacterDatabase, Field::Get(), Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigestOf(), getMSTime(), GetMSTimeDiffToNow(), BannedAddon::Id, LOG_INFO, and LOG_WARN.
Referenced by World::SetInitialWorldSettings().
SaveAddon()
void AddonMgr::SaveAddon (AddonInfo const & addon)
    {
        std::string name = addon.Name;
        CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_ADDON);
        stmt->SetData(0, name);
        stmt->SetData(1, addon.CRC);
        CharacterDatabase.Execute(stmt);
        m_knownAddons.push_back(SavedAddon(addon.Name, addon.CRC));
    }
References CHAR_INS_ADDON, CharacterDatabase, AddonInfo::CRC, AddonInfo::Name, and PreparedStatementBase::SetData().
Referenced by WorldSession::ReadAddonsInfo().