AzerothCore: Acore::AnyAoETargetUnitInObjectRangeCheck Class Reference
Acore::AnyAoETargetUnitInObjectRangeCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
AnyAoETargetUnitInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range)
bool operator() (Unit *u)
Private Attributes
bool i_targetForPlayer
WorldObject const * i_obj
Unit const * i_funit
SpellInfo const * _spellInfo
float i_range
Detailed Description
Constructor & Destructor Documentation
AnyAoETargetUnitInObjectRangeCheck()
Acore::AnyAoETargetUnitInObjectRangeCheck::AnyAoETargetUnitInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range) inline
            : i_obj(obj), i_funit(funit), _spellInfo(nullptr), i_range(range)
        {
            Unit const* check = i_funit;
            Unit const* owner = i_funit->GetOwner();
            if (owner)
                check = owner;
            i_targetForPlayer = (check->IsPlayer());
            if (i_obj->IsDynamicObject())
                _spellInfo = sSpellMgr->GetSpellInfo(((DynamicObject*)i_obj)->GetSpellId());
        }
References _spellInfo, Unit::GetOwner(), i_funit, i_obj, i_targetForPlayer, Object::IsDynamicObject(), Object::IsPlayer(), and sSpellMgr.
Member Function Documentation
operator()()
bool Acore::AnyAoETargetUnitInObjectRangeCheck::operator() (Unit * u) inline
        {
            // Check contains checks for: live, non-selectable, non-attackable flags, flight check and GM check, ignore totems
            if (Creature* creature = u->ToCreature())
            {
                if (creature->IsTotem())
                {
                    return false;
                }
                if (creature->IsAvoidingAOE())
                {
                    return false;
                }
            }
            if (i_funit->_IsValidAttackTarget(u, _spellInfo, i_obj->IsDynamicObject() ? i_obj : nullptr) && i_obj->IsWithinDistInMap(u, i_range,true,false))
                return true;
            return false;
        }
References Unit::_IsValidAttackTarget(), _spellInfo, i_funit, i_obj, i_range, Object::IsDynamicObject(), WorldObject::IsWithinDistInMap(), and Object::ToCreature().
Member Data Documentation
_spellInfo
SpellInfo const* Acore::AnyAoETargetUnitInObjectRangeCheck::_spellInfo private
Referenced by AnyAoETargetUnitInObjectRangeCheck(), and operator()().
i_funit
Unit const* Acore::AnyAoETargetUnitInObjectRangeCheck::i_funit private
Referenced by AnyAoETargetUnitInObjectRangeCheck(), and operator()().
i_obj
WorldObject const* Acore::AnyAoETargetUnitInObjectRangeCheck::i_obj private
Referenced by AnyAoETargetUnitInObjectRangeCheck(), and operator()().
i_range
float Acore::AnyAoETargetUnitInObjectRangeCheck::i_range private
Referenced by operator()().
i_targetForPlayer
bool Acore::AnyAoETargetUnitInObjectRangeCheck::i_targetForPlayer private
Referenced by AnyAoETargetUnitInObjectRangeCheck().