AzerothCore: boss_algalon_the_observer::boss_algalon_the_observerAI Struct Reference
boss_algalon_the_observer::boss_algalon_the_observerAI Struct Reference
Public Member Functions
boss_algalon_the_observerAI (Creature *creature)
bool IsValidHeraldItem (ItemTemplate const *item)
bool DoCheckHeraldOfTheTitans ()
void AttackStart (Unit *who) override
uint32 GetData (uint32 param) const override
void CallConstellations ()
void EnterEvadeMode (EvadeReason why) override
void Reset () override
void KilledUnit (Unit *victim) override
void DoAction (int32 action) override
void JustReachedHome () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void MovementInform (uint32 movementType, uint32 pointId) override
void JustSummoned (Creature *summon) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
bool IsInRoom ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
SummonList summons
InstanceScript * m_pInstance
bool _firstPull
bool _fightWon
bool _phaseTwo
bool _fedOnTears
bool _heraldOfTheTitans
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_algalon_the_observerAI()
boss_algalon_the_observer::boss_algalon_the_observerAI::boss_algalon_the_observerAI (Creature * creature) inline
                                                        : ScriptedAI(creature), summons(me)
        {
            _fedOnTears = true;
            _firstPull = true;
            _fightWon = false;
            m_pInstance = me->GetInstanceScript();
        }
References _fedOnTears, _fightWon, _firstPull, WorldObject::GetInstanceScript(), m_pInstance, and ScriptedAI::me.
Member Function Documentation
AttackStart()
void boss_algalon_the_observer::boss_algalon_the_observerAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (_fightWon)
                return;
            ScriptedAI::AttackStart(who);
        }
References _fightWon, and ScriptedAI::AttackStart().
Referenced by UpdateAI().
CallConstellations()
void boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations () inline
        {
            uint8 _count = 0;
            for (SummonList::const_iterator i = summons.begin(); i != summons.end(); )
            {
                Creature* summon = ObjectAccessor::GetCreature(*me, *i++);
                if (summon && summon->GetEntry() == NPC_LIVING_CONSTELLATION && !summon->AI()->GetData(0))
                {
                    ++_count;
                    summon->AI()->DoAction(ACTION_ACTIVATE_STAR);
                    if (_count >= 3)
                        break;
                }
            }
        }
References ACTION_ACTIVATE_STAR, Creature::AI(), SummonList::begin(), UnitAI::DoAction(), SummonList::end(), ObjectAccessor::GetCreature(), UnitAI::GetData(), Object::GetEntry(), ScriptedAI::me, NPC_LIVING_CONSTELLATION, and summons.
Referenced by UpdateAI().
DamageTaken()
void boss_algalon_the_observer::boss_algalon_the_observerAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (_fightWon)
            {
                damage = 0;
                return;
            }
            if (!_phaseTwo && me->HealthBelowPctDamaged(20, damage))
            {
                _phaseTwo = true;
                Talk(SAY_ALGALON_PHASE_TWO);
                summons.DespawnEntry(NPC_LIVING_CONSTELLATION);
                summons.DespawnEntry(NPC_COLLAPSING_STAR);
                summons.DespawnEntry(NPC_BLACK_HOLE);
                summons.DespawnEntry(NPC_ALGALON_VOID_ZONE_VISUAL_STALKER);
                events.CancelEvent(EVENT_SUMMON_COLLAPSING_STAR);
                events.CancelEvent(EVENT_ACTIVATE_LIVING_CONSTELLATION);
                for (uint32 i = 0; i < COLLAPSING_STAR_COUNT; ++i)
                    me->SummonCreature(NPC_WORM_HOLE, CollapsingStarPos[i], TEMPSUMMON_MANUAL_DESPAWN);
            }
            else if (me->HealthBelowPctDamaged(2, damage) && !_fightWon)
            {
                _fightWon = true;
                damage = 0;
                me->SetReactState(REACT_PASSIVE);
                me->AttackStop();
                me->SetFaction(FACTION_FRIENDLY);
                me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                events.Reset();
                summons.DespawnAll();
                me->InterruptNonMeleeSpells(false);
                events.SetPhase(PHASE_ROLE_PLAY);
                events.ScheduleEvent(EVENT_OUTRO_START, 1500ms);
                events.ScheduleEvent(EVENT_OUTRO_1, 7200ms);
                events.ScheduleEvent(EVENT_OUTRO_2, 8700ms);
            }
        }
References _fightWon, _phaseTwo, Unit::AttackStop(), COLLAPSING_STAR_COUNT, CollapsingStarPos, SummonList::DespawnAll(), SummonList::DespawnEntry(), EVENT_ACTIVATE_LIVING_CONSTELLATION, EVENT_OUTRO_1, EVENT_OUTRO_2, EVENT_OUTRO_START, EVENT_SUMMON_COLLAPSING_STAR, FACTION_FRIENDLY, Unit::HealthBelowPctDamaged(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, NPC_ALGALON_VOID_ZONE_VISUAL_STALKER, NPC_BLACK_HOLE, NPC_COLLAPSING_STAR, NPC_LIVING_CONSTELLATION, NPC_WORM_HOLE, PHASE_ROLE_PLAY, REACT_PASSIVE, SAY_ALGALON_PHASE_TWO, Unit::SetFaction(), Creature::SetReactState(), Unit::SetUnitFlag(), WorldObject::SummonCreature(), summons, TEMPSUMMON_MANUAL_DESPAWN, and UNIT_FLAG_NOT_SELECTABLE.
DoAction()
void boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            switch (action)
            {
                case ACTION_START_INTRO:
                    {
                        me->SetImmuneToPC(true);
                        me->SetUnitFlag2(UNIT_FLAG2_DO_NOT_FADE_IN);
                        me->SetDisableGravity(true);
                        me->CastSpell(me, SPELL_ARRIVAL, true);
                        me->CastSpell(me, SPELL_RIDE_THE_LIGHTNING, true);
                        me->GetMotionMaster()->MovePoint(POINT_ALGALON_LAND, AlgalonLandPos);
                        me->SetHomePosition(AlgalonLandPos);
                        Movement::MoveSplineInit init(me);
                        init.MoveTo(AlgalonLandPos.GetPositionX(), AlgalonLandPos.GetPositionY(), AlgalonLandPos.GetPositionZ());
                        init.SetOrientationFixed(true);
                        init.Launch();
                        events.Reset();
                        events.SetPhase(PHASE_ROLE_PLAY);
                        events.ScheduleEvent(EVENT_INTRO_1, 5s, 0, PHASE_ROLE_PLAY);
                        events.ScheduleEvent(EVENT_INTRO_2, 15s, 0, PHASE_ROLE_PLAY);
                        events.ScheduleEvent(EVENT_INTRO_3, 23s, 0, PHASE_ROLE_PLAY);
                        events.ScheduleEvent(EVENT_INTRO_FINISH, 36s, 0, PHASE_ROLE_PLAY);
                        break;
                    }
                case ACTION_DESPAWN_ALGALON:
                    _fightWon = true;
                    events.Reset();
                    summons.DespawnAll();
                    events.SetPhase(PHASE_ROLE_PLAY);
                    events.ScheduleEvent(EVENT_DESPAWN_ALGALON_1, 5s);
                    events.ScheduleEvent(EVENT_DESPAWN_ALGALON_2, 17s);
                    events.ScheduleEvent(EVENT_DESPAWN_ALGALON_3, 26s);
                    if (me->IsInCombat())
                        events.ScheduleEvent(EVENT_DESPAWN_ALGALON_4, 26s);
                    events.ScheduleEvent(EVENT_DESPAWN_ALGALON_5, 32s);
                    me->DespawnOrUnsummon(39000);
                    me->SetReactState(REACT_PASSIVE);
                    me->AttackStop();
                    me->SetFaction(FACTION_FRIENDLY);
                    me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    me->InterruptNonMeleeSpells(false);
                    if (m_pInstance)
                        m_pInstance->SetData(TYPE_ALGALON, NOT_STARTED);
                    break;
                case ACTION_INIT_ALGALON:
                    _firstPull = false;
                    _fedOnTears = false;
                    me->SetImmuneToPC(false);
                    break;
                case ACTION_ASCEND:
                    summons.DespawnAll();
                    events.SetPhase(PHASE_BIG_BANG);
                    events.ScheduleEvent(EVENT_ASCEND_TO_THE_HEAVENS, 1500ms);
                    break;
                case ACTION_FEEDS_ON_TEARS_FAILED:
                    _fedOnTears = false;
            }
        }
References _fedOnTears, _fightWon, _firstPull, ACTION_ASCEND, ACTION_DESPAWN_ALGALON, ACTION_FEEDS_ON_TEARS_FAILED, ACTION_INIT_ALGALON, ACTION_START_INTRO, AlgalonLandPos, Unit::AttackStop(), Unit::CastSpell(), SummonList::DespawnAll(), Creature::DespawnOrUnsummon(), EVENT_ASCEND_TO_THE_HEAVENS, EVENT_DESPAWN_ALGALON_1, EVENT_DESPAWN_ALGALON_2, EVENT_DESPAWN_ALGALON_3, EVENT_DESPAWN_ALGALON_4, EVENT_DESPAWN_ALGALON_5, EVENT_INTRO_1, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_INTRO_FINISH, FACTION_FRIENDLY, Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::InterruptNonMeleeSpells(), Unit::IsInCombat(), Movement::MoveSplineInit::Launch(), m_pInstance, ScriptedAI::me, MotionMaster::MovePoint(), Movement::MoveSplineInit::MoveTo(), NOT_STARTED, PHASE_BIG_BANG, PHASE_ROLE_PLAY, POINT_ALGALON_LAND, REACT_PASSIVE, ZoneScript::SetData(), Creature::SetDisableGravity(), Unit::SetFaction(), Creature::SetHomePosition(), Unit::SetImmuneToPC(), Movement::MoveSplineInit::SetOrientationFixed(), Creature::SetReactState(), Unit::SetUnitFlag(), Unit::SetUnitFlag2(), SPELL_ARRIVAL, SPELL_RIDE_THE_LIGHTNING, summons, TYPE_ALGALON, UNIT_FLAG2_DO_NOT_FADE_IN, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by EnterEvadeMode(), and IsInRoom().
DoCheckHeraldOfTheTitans()
bool boss_algalon_the_observer::boss_algalon_the_observerAI::DoCheckHeraldOfTheTitans () inline
        {
            if (!_heraldOfTheTitans)
                return true;
            Map::PlayerList const& pl = me->GetMap()->GetPlayers();
            for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                if (Player* plr = itr->GetSource())
                    if (!plr->IsGameMaster() && plr->IsInCombat() /*performance*/)
                    {
                        for (uint8 i = EQUIPMENT_SLOT_START; i < EQUIPMENT_SLOT_END; ++i) // loop through equipped items
                            if (Item* item = plr->GetItemByPos(INVENTORY_SLOT_BAG_0, i))
                                if (!IsValidHeraldItem(item->GetTemplate()))
{
                                    _heraldOfTheTitans = false;
                                    return true;
                                }
                    }
            return false;
        }
References _heraldOfTheTitans, MapRefMgr::begin(), MapRefMgr::end(), EQUIPMENT_SLOT_END, EQUIPMENT_SLOT_START, WorldObject::GetMap(), Map::GetPlayers(), INVENTORY_SLOT_BAG_0, IsValidHeraldItem(), and ScriptedAI::me.
Referenced by JustEngagedWith(), and UpdateAI().
EnterEvadeMode()
void boss_algalon_the_observer::boss_algalon_the_observerAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            if (_fightWon)
                return;
            if (SelectTargetFromPlayerList(120.0f))
            {
                me->SetInCombatWithZone();
                return;
            }
            else if (events.GetPhaseMask() & PHASE_NORMAL)
            {
                DoAction(ACTION_ASCEND);
                return;
            }
            if (m_pInstance)
                m_pInstance->SetData(TYPE_ALGALON, FAIL);
            ScriptedAI::EnterEvadeMode(why);
        }
References _fightWon, ACTION_ASCEND, DoAction(), CreatureAI::EnterEvadeMode(), FAIL, m_pInstance, ScriptedAI::me, PHASE_NORMAL, ScriptedAI::SelectTargetFromPlayerList(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), and TYPE_ALGALON.
Referenced by JustEngagedWith().
GetData()
uint32 boss_algalon_the_observer::boss_algalon_the_observerAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_HAS_FED_ON_TEARS)
                return _fedOnTears;
            if (param == DATA_HERALD_OF_THE_TITANS)
                return _heraldOfTheTitans;
            return 0;
        }
References _fedOnTears, _heraldOfTheTitans, DATA_HAS_FED_ON_TEARS, and DATA_HERALD_OF_THE_TITANS.
IsInRoom()
bool boss_algalon_the_observer::boss_algalon_the_observerAI::IsInRoom () inline
        {
            if (me->GetExactDist2d(&me->GetHomePosition()) > 45.f || me->GetPositionZ() < 410.f)
            {
                DoAction(ACTION_ASCEND);
                return false;
            }
            return true;
        }
References ACTION_ASCEND, DoAction(), Position::GetExactDist2d(), Creature::GetHomePosition(), Position::GetPositionZ(), and ScriptedAI::me.
Referenced by UpdateAI().
IsValidHeraldItem()
bool boss_algalon_the_observer::boss_algalon_the_observerAI::IsValidHeraldItem (ItemTemplate const * item) inline
        {
            if (!item) // should not happen, but checked in GetAverageItemLevel()
                return true;
            if (item->ItemLevel <= 226 || (item->ItemLevel <= 232 && (
                                               item->InventoryType == INVTYPE_SHIELD ||
                                               item->Class == ITEM_CLASS_WEAPON ||
                                               (item->Class == ITEM_CLASS_ARMOR && (item->InventoryType == INVTYPE_RELIC || item->InventoryType == INVTYPE_HOLDABLE))
                                           )))
                return true;
            return false;
        }
References ItemTemplate::Class, ItemTemplate::InventoryType, INVTYPE_HOLDABLE, INVTYPE_RELIC, INVTYPE_SHIELD, ITEM_CLASS_ARMOR, ITEM_CLASS_WEAPON, and ItemTemplate::ItemLevel.
Referenced by DoCheckHeraldOfTheTitans().
JustEngagedWith()
void boss_algalon_the_observer::boss_algalon_the_observerAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            if (_fightWon)
                return;
            if (!m_pInstance)
            {
                EnterEvadeMode(EVADE_REASON_OTHER);
                return;
            }
            uint32 introDelay = 0;
            me->setActive(true);
            me->SetInCombatWithZone();
            me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            me->SetImmuneToNPC(true);
            events.Reset();
            events.SetPhase(PHASE_ROLE_PLAY);
            if (!_firstPull)
            {
                events.ScheduleEvent(EVENT_START_COMBAT, 0ms);
                introDelay = 8000;
            }
            else
            {
                summons.DespawnEntry(NPC_AZEROTH);
                _firstPull = false;
                Talk(SAY_ALGALON_START_TIMER);
                introDelay = 22000;
                events.ScheduleEvent(EVENT_START_COMBAT, 14s);
                m_pInstance->SetData(DATA_DESPAWN_ALGALON, 0);
            }
            events.ScheduleEvent(EVENT_REMOVE_UNNATTACKABLE, introDelay - 500);
            events.ScheduleEvent(EVENT_INTRO_TIMER_DONE, introDelay);
            events.ScheduleEvent(EVENT_QUANTUM_STRIKE, 3500 + introDelay);
            events.ScheduleEvent(EVENT_PHASE_PUNCH, 15500 + introDelay);
            events.ScheduleEvent(EVENT_SUMMON_COLLAPSING_STAR, 16500 + introDelay);
            events.ScheduleEvent(EVENT_COSMIC_SMASH, 25000 + introDelay);
            events.ScheduleEvent(EVENT_ACTIVATE_LIVING_CONSTELLATION, 50500 + introDelay);
            events.ScheduleEvent(EVENT_BIG_BANG, 90000 + introDelay);
            events.ScheduleEvent(EVENT_ASCEND_TO_THE_HEAVENS, 360000 + introDelay);
            events.ScheduleEvent(EVENT_CHECK_HERALD_ITEMS, 5s);
            DoCheckHeraldOfTheTitans();
        }
References _fightWon, _firstPull, DATA_DESPAWN_ALGALON, SummonList::DespawnEntry(), DoCheckHeraldOfTheTitans(), EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_ACTIVATE_LIVING_CONSTELLATION, EVENT_ASCEND_TO_THE_HEAVENS, EVENT_BIG_BANG, EVENT_CHECK_HERALD_ITEMS, EVENT_COSMIC_SMASH, EVENT_INTRO_TIMER_DONE, EVENT_PHASE_PUNCH, EVENT_QUANTUM_STRIKE, EVENT_REMOVE_UNNATTACKABLE, EVENT_START_COMBAT, EVENT_SUMMON_COLLAPSING_STAR, m_pInstance, ScriptedAI::me, NPC_AZEROTH, PHASE_ROLE_PLAY, SAY_ALGALON_START_TIMER, WorldObject::setActive(), ZoneScript::SetData(), Unit::SetImmuneToNPC(), Creature::SetInCombatWithZone(), Unit::SetUnitFlag(), summons, and UNIT_FLAG_NOT_SELECTABLE.
JustReachedHome()
void boss_algalon_the_observer::boss_algalon_the_observerAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
        {
            me->setActive(false);
        }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.Summon(summon);
            switch (summon->GetEntry())
            {
                case NPC_AZEROTH:
                    me->CastSpell(summon, SPELL_REORIGINATION, true);
                    break;
                case NPC_BLACK_HOLE:
                    summon->CastSpell((Unit*)nullptr, SPELL_BLACK_HOLE_TRIGGER, true);
                    summon->CastSpell(summon, SPELL_CONSTELLATION_PHASE_TRIGGER, true);
                    summon->CastSpell((Unit*)nullptr, SPELL_BLACK_HOLE_EXPLOSION, false);
                    summon->CastSpell(summon, SPELL_SUMMON_VOID_ZONE_VISUAL, true);
                    break;
                case NPC_ALGALON_VOID_ZONE_VISUAL_STALKER:
                    summon->CastSpell(summon, SPELL_VOID_ZONE_VISUAL, true);
                    break;
                case NPC_ALGALON_STALKER_ASTEROID_TARGET_01:
                    summon->CastSpell(summon, SPELL_COSMIC_SMASH_VISUAL_STATE, true);
                    break;
                case NPC_ALGALON_STALKER_ASTEROID_TARGET_02:
                    {
                        float x = summon->GetPositionX();
                        float y = summon->GetPositionY();
                        float z = summon->GetPositionZ() + 35.0f;
                        float o = summon->GetOrientation();
                        summon->GetMotionMaster()->Clear();
                        summon->SetHomePosition(x, y, z, o);
                        summon->UpdatePosition(x, y, z, o, true);
                        summon->StopMovingOnCurrentPos();
                        summon->m_Events.AddEvent(new CosmicSmashDamageEvent(summon), summon->m_Events.CalculateTime(4000));
                        break;
                    }
                case NPC_UNLEASHED_DARK_MATTER:
                    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100.0f, true))
                        if (summon->Attack(target, true))
                            summon->GetMotionMaster()->MoveChase(target);
                    break;
            }
        }
References EventProcessor::AddEvent(), Unit::Attack(), EventProcessor::CalculateTime(), Unit::CastSpell(), MotionMaster::Clear(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::m_Events, ScriptedAI::me, MotionMaster::MoveChase(), NPC_ALGALON_STALKER_ASTEROID_TARGET_01, NPC_ALGALON_STALKER_ASTEROID_TARGET_02, NPC_ALGALON_VOID_ZONE_VISUAL_STALKER, NPC_AZEROTH, NPC_BLACK_HOLE, NPC_UNLEASHED_DARK_MATTER, UnitAI::SelectTarget(), Creature::SetHomePosition(), SPELL_BLACK_HOLE_EXPLOSION, SPELL_BLACK_HOLE_TRIGGER, SPELL_CONSTELLATION_PHASE_TRIGGER, SPELL_COSMIC_SMASH_VISUAL_STATE, SPELL_REORIGINATION, SPELL_SUMMON_VOID_ZONE_VISUAL, SPELL_VOID_ZONE_VISUAL, Unit::StopMovingOnCurrentPos(), SummonList::Summon(), summons, and Unit::UpdatePosition().
KilledUnit()
void boss_algalon_the_observer::boss_algalon_the_observerAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!victim->IsPlayer() || urand(0, 2))
                return;
            Talk(SAY_ALGALON_KILL);
        }
References Object::IsPlayer(), SAY_ALGALON_KILL, and urand().
MovementInform()
void boss_algalon_the_observer::boss_algalon_the_observerAI::MovementInform (uint32 movementType, uint32 pointId) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (movementType != POINT_MOTION_TYPE)
                return;
            if (pointId == POINT_ALGALON_LAND)
                me->SetDisableGravity(false);
            else if (pointId == POINT_ALGALON_OUTRO)
            {
                me->SetFacingTo(1.605703f);
                events.ScheduleEvent(EVENT_OUTRO_3, 1200ms);
                events.ScheduleEvent(EVENT_OUTRO_4, 2400ms);
                events.ScheduleEvent(EVENT_OUTRO_5, 8500ms);
                events.ScheduleEvent(EVENT_OUTRO_6, 15s + 500ms);
                events.ScheduleEvent(EVENT_OUTRO_7, 55s + 500ms);
                events.ScheduleEvent(EVENT_OUTRO_8, 73s + 500ms);
                events.ScheduleEvent(EVENT_OUTRO_9, 85s + 500ms);
                events.ScheduleEvent(EVENT_OUTRO_10, 101s + 500ms);
                events.ScheduleEvent(EVENT_OUTRO_11, 117s + 500ms);
            }
        }
References EVENT_OUTRO_10, EVENT_OUTRO_11, EVENT_OUTRO_3, EVENT_OUTRO_4, EVENT_OUTRO_5, EVENT_OUTRO_6, EVENT_OUTRO_7, EVENT_OUTRO_8, EVENT_OUTRO_9, ScriptedAI::me, POINT_ALGALON_LAND, POINT_ALGALON_OUTRO, POINT_MOTION_TYPE, Creature::SetDisableGravity(), and Unit::SetFacingTo().
Reset()
void boss_algalon_the_observer::boss_algalon_the_observerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            if (_fightWon)
                return;
            events.Reset();
            summons.DespawnAll();
            me->SetReactState(REACT_PASSIVE);
            me->SetImmuneToPC(false);
            me->SetSheath(SHEATH_STATE_UNARMED);
            me->SetFaction(190);
            me->CastSpell(me, SPELL_DUAL_WIELD, true);
            _phaseTwo = false;
            _heraldOfTheTitans = true;
            if (m_pInstance->GetData(TYPE_ALGALON) == FAIL)
            {
                _firstPull = false;
            }
            if (m_pInstance)
                m_pInstance->SetData(TYPE_ALGALON, NOT_STARTED);
        }
References _fightWon, _firstPull, _heraldOfTheTitans, _phaseTwo, Unit::CastSpell(), SummonList::DespawnAll(), FAIL, ZoneScript::GetData(), m_pInstance, ScriptedAI::me, NOT_STARTED, REACT_PASSIVE, ZoneScript::SetData(), Unit::SetFaction(), Unit::SetImmuneToPC(), Creature::SetReactState(), Unit::SetSheath(), SHEATH_STATE_UNARMED, SPELL_DUAL_WIELD, summons, and TYPE_ALGALON.
UpdateAI()
void boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!(events.GetPhaseMask() & PHASE_MASK_NO_UPDATE) && (!UpdateVictim() || !IsInRoom()))
                return;
            events.Update(diff);
            if (!(events.GetPhaseMask() & PHASE_MASK_NO_CAST_CHECK) && me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_INTRO_1:
                    me->RemoveAurasDueToSpell(SPELL_RIDE_THE_LIGHTNING);
                    Talk(SAY_ALGALON_INTRO_1);
                    break;
                case EVENT_INTRO_2:
                    me->CastSpell((Unit*)nullptr, SPELL_SUMMON_AZEROTH, true);
                    Talk(SAY_ALGALON_INTRO_2);
                    break;
                case EVENT_INTRO_3:
                    Talk(SAY_ALGALON_INTRO_3);
                    break;
                case EVENT_INTRO_FINISH:
                    events.Reset();
                    me->SetImmuneToPC(false);
                    if (Creature* brann = ObjectAccessor::GetCreature(*me, m_pInstance->GetGuidData(NPC_BRANN_BRONZBEARD_ALG)))
                        brann->AI()->DoAction(ACTION_FINISH_INTRO);
                    break;
                case EVENT_START_COMBAT:
                    m_pInstance->SetData(TYPE_ALGALON, IN_PROGRESS);
                    Talk(SAY_ALGALON_AGGRO);
                    break;
                case EVENT_REMOVE_UNNATTACKABLE:
                    me->SetSheath(SHEATH_STATE_MELEE);
                    me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    me->SetImmuneToNPC(false);
                    break;
                case EVENT_INTRO_TIMER_DONE:
                    events.SetPhase(PHASE_NORMAL);
                    me->CastSpell((Unit*)nullptr, SPELL_SUPERMASSIVE_FAIL, true);
                    // Hack: _IsValidTarget failed earlier due to flags, call AttackStart again
                    me->SetReactState(REACT_AGGRESSIVE);
                    me->SetFaction(FACTION_MONSTER);
                    if (Player* target = SelectTargetFromPlayerList(150.0f))
                        AttackStart(target);
                    me->SetInCombatWithZone();
                    for (uint32 i = 0; i < LIVING_CONSTELLATION_COUNT; ++i)
                        me->SummonCreature(NPC_LIVING_CONSTELLATION, ConstellationPos[i], TEMPSUMMON_DEAD_DESPAWN);
                    break;
                case EVENT_QUANTUM_STRIKE:
                    me->CastSpell(me->GetVictim(), SPELL_QUANTUM_STRIKE, false);
                    events.Repeat(3000ms, 4500ms);
                    break;
                case EVENT_PHASE_PUNCH:
                    me->CastSpell(me->GetVictim(), SPELL_PHASE_PUNCH, false);
                    events.Repeat(15s + 500ms);
                    break;
                case EVENT_SUMMON_COLLAPSING_STAR:
                    Talk(SAY_ALGALON_COLLAPSING_STAR);
                    Talk(EMOTE_ALGALON_COLLAPSING_STAR);
                    for (uint8 i = 0; i < COLLAPSING_STAR_COUNT; ++i)
                        me->SummonCreature(NPC_COLLAPSING_STAR, CollapsingStarPos[i], TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000);
                    events.Repeat(1min);
                    break;
                case EVENT_COSMIC_SMASH:
                    Talk(EMOTE_ALGALON_COSMIC_SMASH);
                    me->CastCustomSpell(SPELL_COSMIC_SMASH, SPELLVALUE_MAX_TARGETS, RAID_MODE(1, 3), (Unit*)nullptr);
                    events.Repeat(25s + 500ms);
                    break;
                case EVENT_ACTIVATE_LIVING_CONSTELLATION:
                    {
                        if (events.GetPhaseMask() & PHASE_MASK_NO_UPDATE)
{
                            events.Repeat(4s);
                            break;
                        }
                        CallConstellations();
                        //me->CastSpell(me, SPELL_TRIGGER_3_ADDS, true);
                        events.Repeat(50s);
                        break;
                    }
                case EVENT_BIG_BANG:
                    {
                        Talk(SAY_ALGALON_BIG_BANG);
                        Talk(EMOTE_ALGALON_BIG_BANG);
                        EntryCheckPredicate pred(NPC_LIVING_CONSTELLATION);
                        summons.DoAction(ACTION_BIG_BANG, pred);
                        me->CastSpell((Unit*)nullptr, SPELL_BIG_BANG, false);
                        events.Repeat(90s + 500ms);
                        break;
                    }
                case EVENT_ASCEND_TO_THE_HEAVENS:
                    Talk(SAY_ALGALON_ASCEND);
                    me->CastSpell((Unit*)nullptr, SPELL_ASCEND_TO_THE_HEAVENS, false);
                    events.ScheduleEvent(EVENT_EVADE, 2500ms);
                    break;
                case EVENT_EVADE:
                    events.Reset();
                    ScriptedAI::EnterEvadeMode();
                    return;
                case EVENT_OUTRO_START:
                    if (m_pInstance)
                    {
                        m_pInstance->SetData(TYPE_ALGALON, DONE);
                        m_pInstance->SetData(DATA_ALGALON_DEFEATED, 1);
                    }
                    break;
                case EVENT_OUTRO_1:
                    me->RemoveAllAuras();
                    me->SetUnitFlag(UNIT_FLAG_RENAME);
                    break;
                case EVENT_OUTRO_2:
                {
                    Player* lootRecipent = me->GetLootRecipient();
                    _EnterEvadeMode();
                    // LootRecipent is cleared in _EnterEvadeMode, restore it
                    me->SetLootRecipient(lootRecipent);
                    me->GetMotionMaster()->MovePoint(POINT_ALGALON_OUTRO, AlgalonOutroPos);
                    break;
                }
                case EVENT_OUTRO_3:
                    me->CastSpell((Unit*)nullptr, SPELL_KILL_CREDIT);
                    // Summon Chest
                    if (GameObject* go = me->SummonGameObject(RAID_MODE(GO_ALGALON_CHEST, GO_ALGALON_CHEST_HERO), 1632.1f, -306.561f, 417.321f, 4.69494f, 0, 0, 0, 1, 0))
                    {
                        go->ReplaceAllGameObjectFlags((GameObjectFlags)0);
                        go->SetLootRecipient(me);
                    }
                    break;
                case EVENT_OUTRO_4:
                    me->CastSpell((Unit*)nullptr, SPELL_SUPERMASSIVE_FAIL);
                    me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    break;
                case EVENT_OUTRO_5:
                    if (Creature* brann = me->SummonCreature(NPC_BRANN_BRONZBEARD_ALG, BrannOutroPos[0], TEMPSUMMON_TIMED_DESPAWN, 131500))
                        brann->AI()->DoAction(ACTION_OUTRO);
                    break;
                case EVENT_OUTRO_6:
                    Talk(SAY_ALGALON_OUTRO_1);
                    me->SetStandState(UNIT_STAND_STATE_KNEEL);
                    break;
                case EVENT_OUTRO_7:
                    Talk(SAY_ALGALON_OUTRO_2);
                    break;
                case EVENT_OUTRO_8:
                    Talk(SAY_ALGALON_OUTRO_3);
                    break;
                case EVENT_OUTRO_9:
                    Talk(SAY_ALGALON_OUTRO_4);
                    break;
                case EVENT_OUTRO_10:
                    Talk(SAY_ALGALON_OUTRO_5);
                    break;
                case EVENT_OUTRO_11:
                    me->SetStandState(UNIT_STAND_STATE_STAND);
                    me->CastSpell(me, SPELL_TELEPORT, false);
                    me->DespawnOrUnsummon(3000);
                    break;
                case EVENT_DESPAWN_ALGALON_1:
                    Talk(SAY_ALGALON_DESPAWN_1);
                    break;
                case EVENT_DESPAWN_ALGALON_2:
                    Talk(SAY_ALGALON_DESPAWN_2);
                    break;
                case EVENT_DESPAWN_ALGALON_3:
                    Talk(SAY_ALGALON_DESPAWN_3);
                    break;
                case EVENT_DESPAWN_ALGALON_4:
                    me->CastSpell((Unit*)nullptr, SPELL_ASCEND_TO_THE_HEAVENS, false);
                    break;
                case EVENT_DESPAWN_ALGALON_5:
                    me->SetStandState(UNIT_STAND_STATE_STAND);
                    me->CastSpell(me, SPELL_TELEPORT, false);
                    me->DespawnOrUnsummon(3000);
                    break;
                case EVENT_CHECK_HERALD_ITEMS:
                    if (!DoCheckHeraldOfTheTitans())
                        events.Repeat(5s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References CreatureAI::_EnterEvadeMode(), ACTION_BIG_BANG, ACTION_FINISH_INTRO, ACTION_OUTRO, AlgalonOutroPos, AttackStart(), BrannOutroPos, CallConstellations(), Unit::CastCustomSpell(), Unit::CastSpell(), COLLAPSING_STAR_COUNT, CollapsingStarPos, ConstellationPos, DATA_ALGALON_DEFEATED, Creature::DespawnOrUnsummon(), SummonList::DoAction(), DoCheckHeraldOfTheTitans(), UnitAI::DoMeleeAttackIfReady(), DONE, EMOTE_ALGALON_BIG_BANG, EMOTE_ALGALON_COLLAPSING_STAR, EMOTE_ALGALON_COSMIC_SMASH, CreatureAI::EnterEvadeMode(), EVENT_ACTIVATE_LIVING_CONSTELLATION, EVENT_ASCEND_TO_THE_HEAVENS, EVENT_BIG_BANG, EVENT_CHECK_HERALD_ITEMS, EVENT_COSMIC_SMASH, EVENT_DESPAWN_ALGALON_1, EVENT_DESPAWN_ALGALON_2, EVENT_DESPAWN_ALGALON_3, EVENT_DESPAWN_ALGALON_4, EVENT_DESPAWN_ALGALON_5, EVENT_EVADE, EVENT_INTRO_1, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_INTRO_FINISH, EVENT_INTRO_TIMER_DONE, EVENT_OUTRO_1, EVENT_OUTRO_10, EVENT_OUTRO_11, EVENT_OUTRO_2, EVENT_OUTRO_3, EVENT_OUTRO_4, EVENT_OUTRO_5, EVENT_OUTRO_6, EVENT_OUTRO_7, EVENT_OUTRO_8, EVENT_OUTRO_9, EVENT_OUTRO_START, EVENT_PHASE_PUNCH, EVENT_QUANTUM_STRIKE, EVENT_REMOVE_UNNATTACKABLE, EVENT_START_COMBAT, EVENT_SUMMON_COLLAPSING_STAR, FACTION_MONSTER, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Creature::GetLootRecipient(), Unit::GetMotionMaster(), Unit::GetVictim(), GO_ALGALON_CHEST, GO_ALGALON_CHEST_HERO, Unit::HasUnitState(), IN_PROGRESS, IsInRoom(), LIVING_CONSTELLATION_COUNT, m_pInstance, ScriptedAI::me, MotionMaster::MovePoint(), NPC_BRANN_BRONZBEARD_ALG, NPC_COLLAPSING_STAR, NPC_LIVING_CONSTELLATION, PHASE_MASK_NO_CAST_CHECK, PHASE_MASK_NO_UPDATE, PHASE_NORMAL, POINT_ALGALON_OUTRO, ScriptedAI::RAID_MODE(), REACT_AGGRESSIVE, Unit::RemoveAllAuras(), Unit::RemoveAurasDueToSpell(), Unit::RemoveUnitFlag(), SAY_ALGALON_AGGRO, SAY_ALGALON_ASCEND, SAY_ALGALON_BIG_BANG, SAY_ALGALON_COLLAPSING_STAR, SAY_ALGALON_DESPAWN_1, SAY_ALGALON_DESPAWN_2, SAY_ALGALON_DESPAWN_3, SAY_ALGALON_INTRO_1, SAY_ALGALON_INTRO_2, SAY_ALGALON_INTRO_3, SAY_ALGALON_OUTRO_1, SAY_ALGALON_OUTRO_2, SAY_ALGALON_OUTRO_3, SAY_ALGALON_OUTRO_4, SAY_ALGALON_OUTRO_5, ScriptedAI::SelectTargetFromPlayerList(), ZoneScript::SetData(), Unit::SetFaction(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPC(), Creature::SetInCombatWithZone(), Creature::SetLootRecipient(), Creature::SetReactState(), Unit::SetSheath(), Unit::SetStandState(), Unit::SetUnitFlag(), SHEATH_STATE_MELEE, SPELL_ASCEND_TO_THE_HEAVENS, SPELL_BIG_BANG, SPELL_COSMIC_SMASH, SPELL_KILL_CREDIT, SPELL_PHASE_PUNCH, SPELL_QUANTUM_STRIKE, SPELL_RIDE_THE_LIGHTNING, SPELL_SUMMON_AZEROTH, SPELL_SUPERMASSIVE_FAIL, SPELL_TELEPORT, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), WorldObject::SummonGameObject(), summons, TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_DEAD_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, TYPE_ALGALON, UNIT_FLAG_NOT_SELECTABLE, UNIT_FLAG_RENAME, UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_STAND, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_fedOnTears
bool boss_algalon_the_observer::boss_algalon_the_observerAI::_fedOnTears
Referenced by boss_algalon_the_observerAI(), DoAction(), and GetData().
_fightWon
bool boss_algalon_the_observer::boss_algalon_the_observerAI::_fightWon
Referenced by AttackStart(), boss_algalon_the_observerAI(), DamageTaken(), DoAction(), EnterEvadeMode(), JustEngagedWith(), and Reset().
_firstPull
bool boss_algalon_the_observer::boss_algalon_the_observerAI::_firstPull
Referenced by boss_algalon_the_observerAI(), DoAction(), JustEngagedWith(), and Reset().
_heraldOfTheTitans
bool boss_algalon_the_observer::boss_algalon_the_observerAI::_heraldOfTheTitans
Referenced by DoCheckHeraldOfTheTitans(), GetData(), and Reset().
_phaseTwo
bool boss_algalon_the_observer::boss_algalon_the_observerAI::_phaseTwo
Referenced by DamageTaken(), and Reset().
events
EventMap boss_algalon_the_observer::boss_algalon_the_observerAI::events
m_pInstance
InstanceScript* boss_algalon_the_observer::boss_algalon_the_observerAI::m_pInstance
Referenced by boss_algalon_the_observerAI(), DoAction(), EnterEvadeMode(), JustEngagedWith(), Reset(), and UpdateAI().
summons
SummonList boss_algalon_the_observer::boss_algalon_the_observerAI::summons
Referenced by CallConstellations(), DamageTaken(), DoAction(), JustEngagedWith(), JustSummoned(), Reset(), and UpdateAI().