AzerothCore: boss_kologarn::boss_kologarnAI Struct Reference
boss_kologarn::boss_kologarnAI Struct Reference
Public Member Functions
boss_kologarnAI (Creature *pCreature)
void MoveInLineOfSight (Unit *who) override
void EnterEvadeMode (EvadeReason why) override
void AttachLeftArm ()
void AttachRightArm ()
void Reset () override
void DoAction (int32 param) override
uint32 GetData (uint32 param) const override
void AttackStart (Unit *who) override
void JustSummoned (Creature *cr) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void PassengerBoarded (Unit *who, int8, bool apply) override
== Fields =======================================
void DamageTaken (Unit *who, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * m_pInstance
Vehicle * vehicle
ObjectGuid _left
ObjectGuid _right
EventMap events
SummonList summons
Unit * eyebeamTarget
bool _looksAchievement
bool breathReady
uint8 _rubbleAchievement
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_kologarnAI()
boss_kologarn::boss_kologarnAI::boss_kologarnAI (Creature * pCreature) inline
                                             : ScriptedAI(pCreature), vehicle(me->GetVehicleKit()), summons(me), breathReady(false)
        {
            m_pInstance = me->GetInstanceScript();
            eyebeamTarget = nullptr;
            assert(vehicle);
            me->SetStandState(UNIT_STAND_STATE_SUBMERGED);
        }
References eyebeamTarget, WorldObject::GetInstanceScript(), m_pInstance, ScriptedAI::me, Unit::SetStandState(), UNIT_STAND_STATE_SUBMERGED, and vehicle.
Member Function Documentation
AttachLeftArm()
void boss_kologarn::boss_kologarnAI::AttachLeftArm () inline
        {
            if (Unit* arm = ObjectAccessor::GetCreature(*me, _left))
                arm->SetHealth(arm->GetMaxHealth());
            else if (Creature* accessory = me->SummonCreature(NPC_LEFT_ARM, *me, TEMPSUMMON_MANUAL_DESPAWN))
            {
                accessory->AddUnitTypeMask(UNIT_MASK_ACCESSORY);
                if (!me->HandleSpellClick(accessory, 0))
                    accessory->DespawnOrUnsummon();
                else
                {
                    _left = accessory->GetGUID();
                    accessory->SetOrientation(M_PI);
                    accessory->CastSpell(accessory, SPELL_ARM_RESPAWN_VISUAL, true);
                }
            }
        }
References _left, ObjectAccessor::GetCreature(), Unit::HandleSpellClick(), ScriptedAI::me, NPC_LEFT_ARM, SPELL_ARM_RESPAWN_VISUAL, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, and UNIT_MASK_ACCESSORY.
Referenced by Reset(), and UpdateAI().
AttachRightArm()
void boss_kologarn::boss_kologarnAI::AttachRightArm () inline
        {
            if (Unit* arm = ObjectAccessor::GetCreature(*me, _right))
                arm->SetHealth(arm->GetMaxHealth());
            else if (Creature* accessory = me->SummonCreature(NPC_RIGHT_ARM, *me, TEMPSUMMON_MANUAL_DESPAWN))
            {
                accessory->AddUnitTypeMask(UNIT_MASK_ACCESSORY);
                if (!me->HandleSpellClick(accessory, 1))
                    accessory->DespawnOrUnsummon();
                else
                {
                    _right = accessory->GetGUID();
                    accessory->SetOrientation(M_PI);
                    accessory->CastSpell(accessory, SPELL_ARM_RESPAWN_VISUAL, true);
                }
            }
        }
References _right, ObjectAccessor::GetCreature(), Unit::HandleSpellClick(), ScriptedAI::me, NPC_RIGHT_ARM, SPELL_ARM_RESPAWN_VISUAL, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, and UNIT_MASK_ACCESSORY.
Referenced by Reset(), and UpdateAI().
AttackStart()
void boss_kologarn::boss_kologarnAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            me->Attack(who, true);
        }
References Unit::Attack(), and ScriptedAI::me.
DamageTaken()
void boss_kologarn::boss_kologarnAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from ScriptedAI.
        {
            if (who && who->GetEntry() == me->GetEntry() && me->GetHealth())
            {
                damage = std::min(damage, me->GetHealth() - 1);
                me->LowerPlayerDamageReq(damage);
            }
        }
References Object::GetEntry(), Unit::GetHealth(), Creature::LowerPlayerDamageReq(), and ScriptedAI::me.
DoAction()
void boss_kologarn::boss_kologarnAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_KOLOGARN_LOOKS_ACHIEV)
                _looksAchievement = false;
            if (param == DATA_KOLOGARN_RUBBLE_ACHIEV)
            {
                // Means arm died
                if (m_pInstance && (!_left || !_right))
                    m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEVEMENT_DISARMED_CRITERIA);
                ++_rubbleAchievement;
            }
        }
References _left, _looksAchievement, _right, _rubbleAchievement, ACHIEVEMENT_DISARMED_CRITERIA, ACHIEVEMENT_TIMED_TYPE_EVENT, DATA_KOLOGARN_LOOKS_ACHIEV, DATA_KOLOGARN_RUBBLE_ACHIEV, InstanceScript::DoStartTimedAchievement(), and m_pInstance.
EnterEvadeMode()
void boss_kologarn::boss_kologarnAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!_EnterEvadeMode(why))
                return;
            Reset();
            me->setActive(false);
        }
References CreatureAI::_EnterEvadeMode(), ScriptedAI::me, Reset(), and WorldObject::setActive().
Referenced by UpdateAI().
GetData()
uint32 boss_kologarn::boss_kologarnAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_KOLOGARN_LOOKS_ACHIEV)
                return _looksAchievement;
            else if (param == DATA_KOLOGARN_RUBBLE_ACHIEV)
                return (_rubbleAchievement >= 5);
            else if (param == DATA_KOLOGARN_ARMS_ACHIEV)
                return !_rubbleAchievement;
            return 0;
        }
References _looksAchievement, _rubbleAchievement, DATA_KOLOGARN_ARMS_ACHIEV, DATA_KOLOGARN_LOOKS_ACHIEV, and DATA_KOLOGARN_RUBBLE_ACHIEV.
JustDied()
void boss_kologarn::boss_kologarnAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.DespawnAll();
            me->StopMoving();
            if (m_pInstance)
                m_pInstance->SetData(TYPE_KOLOGARN, DONE);
            Talk(SAY_DEATH);
            if (m_pInstance)
            {
                // Open the door inside Kologarn chamber
                if (GameObject* door = m_pInstance->instance->GetGameObject(m_pInstance->GetGuidData(GO_KOLOGARN_DOORS)))
                    door->SetGoState(GO_STATE_ACTIVE);
            }
            if (GameObject* bridge = me->FindNearestGameObject(GO_KOLOGARN_BRIDGE, 100))
                bridge->SetGoState(GO_STATE_READY);
            // Summon Chest
            if (GameObject* go = me->SummonGameObject(RAID_MODE(GO_KOLOGARN_CHEST, GO_KOLOGARN_CHEST_HERO), 1839.62f, -35.98f, 448.81f, 3.6f, 0, 0, 0, 0, 7 * 86400))
            {
                me->RemoveGameObject(go, false);
                go->SetSpellId(1); // hack to make it despawn
                go->ReplaceAllGameObjectFlags((GameObjectFlags)0);
                go->SetLootRecipient(me);
            }
            if (Creature* arm = ObjectAccessor::GetCreature(*me, _left))
                arm->DespawnOrUnsummon(3000); // visual
            if (Creature* arm = ObjectAccessor::GetCreature(*me, _right))
                arm->DespawnOrUnsummon(3000); // visual
            me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            me->SetDisableGravity(true);
        }
References _left, _right, SummonList::DespawnAll(), DONE, WorldObject::FindNearestGameObject(), ObjectAccessor::GetCreature(), Map::GetGameObject(), InstanceScript::GetGuidData(), GO_KOLOGARN_BRIDGE, GO_KOLOGARN_CHEST, GO_KOLOGARN_CHEST_HERO, GO_KOLOGARN_DOORS, GO_STATE_ACTIVE, GO_STATE_READY, InstanceScript::instance, m_pInstance, ScriptedAI::me, ScriptedAI::RAID_MODE(), Unit::RemoveGameObject(), SAY_DEATH, ZoneScript::SetData(), Creature::SetDisableGravity(), Unit::SetUnitFlag(), Unit::StopMoving(), WorldObject::SummonGameObject(), summons, TYPE_KOLOGARN, and UNIT_FLAG_NOT_SELECTABLE.
JustEngagedWith()
void boss_kologarn::boss_kologarnAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            if (m_pInstance)
                m_pInstance->SetData(TYPE_KOLOGARN, IN_PROGRESS);
            events.ScheduleEvent(EVENT_SMASH, 8s);
            events.ScheduleEvent(EVENT_SWEEP, 17s);
            events.ScheduleEvent(EVENT_GRIP, 15s);
            events.ScheduleEvent(EVENT_FOCUSED_EYEBEAM, 10s);
            events.ScheduleEvent(EVENT_PREPARE_BREATH, 3s);
            //events.ScheduleEvent(EVENT_ENRAGE, x); no info
            Talk(SAY_AGGRO);
            me->setActive(true);
            // Close the door inside Kologarn chamber
            if (m_pInstance)
            {
                if (GameObject* door = m_pInstance->instance->GetGameObject(m_pInstance->GetGuidData(GO_KOLOGARN_DOORS)))
                {
                    door->SetGoState(GO_STATE_READY);
                }
            }
        }
References EVENT_FOCUSED_EYEBEAM, EVENT_GRIP, EVENT_PREPARE_BREATH, EVENT_SMASH, EVENT_SWEEP, Map::GetGameObject(), InstanceScript::GetGuidData(), GO_KOLOGARN_DOORS, GO_STATE_READY, IN_PROGRESS, InstanceScript::instance, m_pInstance, ScriptedAI::me, SAY_AGGRO, WorldObject::setActive(), ZoneScript::SetData(), and TYPE_KOLOGARN.
JustSummoned()
void boss_kologarn::boss_kologarnAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (cr->GetEntry() != NPC_LEFT_ARM && cr->GetEntry() != NPC_RIGHT_ARM)
                summons.Summon(cr);
        }
References Object::GetEntry(), NPC_LEFT_ARM, NPC_RIGHT_ARM, SummonList::Summon(), and summons.
KilledUnit()
void boss_kologarn::boss_kologarnAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!urand(0, 2))
                return;
            Talk(SAY_SLAY);
        }
References SAY_SLAY, and urand().
MoveInLineOfSight()
void boss_kologarn::boss_kologarnAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
        {
            if (who->IsPlayer() && me->GetExactDist2d(who) < 45.0f && me->getStandState() == UNIT_STAND_STATE_SUBMERGED)
            {
                me->SetStandState(UNIT_STAND_STATE_STAND);
                if (Unit* arm = ObjectAccessor::GetCreature(*me, _left))
                    arm->CastSpell(arm, SPELL_ARM_RESPAWN_VISUAL, true);
                if (Unit* arm = ObjectAccessor::GetCreature(*me, _right))
                    arm->CastSpell(arm, SPELL_ARM_RESPAWN_VISUAL, true);
            }
            if (me->GetExactDist2d(who) < 30.0f)
                ScriptedAI::MoveInLineOfSight(who);
        }
References _left, _right, ObjectAccessor::GetCreature(), Position::GetExactDist2d(), Unit::getStandState(), Object::IsPlayer(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), Unit::SetStandState(), SPELL_ARM_RESPAWN_VISUAL, UNIT_STAND_STATE_STAND, and UNIT_STAND_STATE_SUBMERGED.
PassengerBoarded()
void boss_kologarn::boss_kologarnAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
        {
            if (!me->IsAlive())
                return;
            if (!apply)
            {
                // left arm
                if (who->GetGUID() == _left)
                {
                    _left.Clear();
                    if (me->IsInCombat())
                    {
                        Talk(SAY_LEFT_ARM_GONE);
                        events.ScheduleEvent(EVENT_RESTORE_ARM_LEFT, 50s);
                    }
                }
                else
                {
                    _right.Clear();
                    if (me->IsInCombat())
                    {
                        Talk(SAY_RIGHT_ARM_GONE);
                        events.ScheduleEvent(EVENT_RESTORE_ARM_RIGHT, 50s);
                    }
                }
                me->CastSpell(me, SPELL_ARM_DEAD, true);
                if (!_right && !_left)
                    events.ScheduleEvent(EVENT_STONE_SHOUT, 5s);
            }
        }
References _left, _right, Unit::CastSpell(), ObjectGuid::Clear(), EVENT_RESTORE_ARM_LEFT, EVENT_RESTORE_ARM_RIGHT, EVENT_STONE_SHOUT, Object::GetGUID(), Unit::IsAlive(), Unit::IsInCombat(), ScriptedAI::me, SAY_LEFT_ARM_GONE, SAY_RIGHT_ARM_GONE, and SPELL_ARM_DEAD.
Reset()
void boss_kologarn::boss_kologarnAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            _rubbleAchievement = 0;
            _looksAchievement = true;
            me->SetDisableGravity(true);
            me->DisableRotate(true);
            events.Reset();
            summons.DespawnAll();
            if (m_pInstance)
            {
                m_pInstance->SetData(TYPE_KOLOGARN, NOT_STARTED);
                // Open the door inside Kologarn chamber
                if (GameObject* door = m_pInstance->instance->GetGameObject(m_pInstance->GetGuidData(GO_KOLOGARN_DOORS)))
                    door->SetGoState(GO_STATE_ACTIVE);
            }
            AttachLeftArm();
            AttachRightArm();
            // Reset breath on pull
            breathReady = false;
        }
References _looksAchievement, _rubbleAchievement, AttachLeftArm(), AttachRightArm(), breathReady, SummonList::DespawnAll(), Unit::DisableRotate(), Map::GetGameObject(), InstanceScript::GetGuidData(), GO_KOLOGARN_DOORS, GO_STATE_ACTIVE, InstanceScript::instance, m_pInstance, ScriptedAI::me, NOT_STARTED, ZoneScript::SetData(), Creature::SetDisableGravity(), summons, and TYPE_KOLOGARN.
Referenced by EnterEvadeMode().
UpdateAI()
void boss_kologarn::boss_kologarnAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
            {
                EnterEvadeMode(EVADE_REASON_OTHER);
                return;
            }
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case EVENT_PREPARE_BREATH:
                    breathReady = true;
                    break;
                case EVENT_STONE_SHOUT:
                    if (_left || _right)
                    {
                        return;
                    }
                    me->CastSpell(me->GetVictim(), SPELL_STONE_SHOUT, false);
                    events.ScheduleEvent(EVENT_STONE_SHOUT, 2s);
                    break;
                case EVENT_SMASH:
                    if (_left && _right)
                        me->CastSpell(me->GetVictim(), SPELL_OVERHEAD_SMASH, false);
                    else if (_left || _right)
                        me->CastSpell(me->GetVictim(), SPELL_ONEARMED_OVERHEAD_SMASH, false);
                    events.DelayEvents(1s);
                    events.ScheduleEvent(EVENT_SMASH, 14s);
                    return;
                case EVENT_SWEEP:
                    if (_left)
                    {
                        if (Creature* cr = me->FindNearestCreature(NPC_SWEEP_TRIGGER, 300))
                            cr->CastSpell(cr, SPELL_ARM_SWEEP, false);
                        if (urand(0, 1))
                            Talk(SAY_SHOCKWAVE);
                    }
                    events.DelayEvents(1s);
                    events.ScheduleEvent(EVENT_SWEEP, 17s);
                    return;
                case EVENT_GRIP:
                    events.ScheduleEvent(EVENT_GRIP, 25s);
                    if (!_right)
                        break;
                    me->CastSpell(me, SPELL_STONE_GRIP, false);
                    Talk(SAY_GRAB_PLAYER);
                    Talk(EMOTE_STONE_GRIP);
                    return;
                case EVENT_FOCUSED_EYEBEAM:
                {
                    events.ScheduleEvent(EVENT_FOCUSED_EYEBEAM, 20s);
                    if ((eyebeamTarget = SelectTarget(SelectTargetMethod::MinDistance, 0, 0, true)))
                    {
                        me->CastSpell(eyebeamTarget, SPELL_FOCUSED_EYEBEAM_SUMMON, false);
                    }
                    Talk(EMOTE_EYES);
                    return;
                }
                case EVENT_RESTORE_ARM_LEFT:
                    // shouldn't happen
                    AttachLeftArm();
                    return;
                case EVENT_RESTORE_ARM_RIGHT:
                    // shouldn't happen
                    AttachRightArm();
                    return;
            }
            //Make sure our attack is ready and we aren't currently casting before checking distance
            if (me->isAttackReady() && me->GetVictim()) // victim could die by a spell (IMPORTANT!!!) and kologarn entered evade mode
            {
                //If we are within range melee the target
                if (me->IsWithinMeleeRange(me->GetVictim()))
                {
                    me->AttackerStateUpdate(me->GetVictim());
                    me->resetAttackTimer();
                    return;
                }
                else if (Unit* tgt = me->SelectNearbyTarget())
                {
                    me->AttackerStateUpdate(tgt);
                    me->resetAttackTimer();
                    return;
                }
                if (breathReady)
                    me->CastSpell(me->GetVictim(), SPELL_PETRIFYING_BREATH, false);
                me->resetAttackTimer();
            }
        }
References _left, _right, AttachLeftArm(), AttachRightArm(), Unit::AttackerStateUpdate(), breathReady, Unit::CastSpell(), EMOTE_EYES, EMOTE_STONE_GRIP, EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_FOCUSED_EYEBEAM, EVENT_GRIP, EVENT_PREPARE_BREATH, EVENT_RESTORE_ARM_LEFT, EVENT_RESTORE_ARM_RIGHT, EVENT_SMASH, EVENT_STONE_SHOUT, EVENT_SWEEP, eyebeamTarget, WorldObject::FindNearestCreature(), Unit::GetVictim(), Unit::HasUnitState(), Unit::isAttackReady(), Unit::IsWithinMeleeRange(), ScriptedAI::me, NPC_SWEEP_TRIGGER, Unit::resetAttackTimer(), SAY_GRAB_PLAYER, SAY_SHOCKWAVE, Unit::SelectNearbyTarget(), UnitAI::SelectTarget(), SPELL_ARM_SWEEP, SPELL_FOCUSED_EYEBEAM_SUMMON, SPELL_ONEARMED_OVERHEAD_SMASH, SPELL_OVERHEAD_SMASH, SPELL_PETRIFYING_BREATH, SPELL_STONE_GRIP, SPELL_STONE_SHOUT, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_left
ObjectGuid boss_kologarn::boss_kologarnAI::_left
Referenced by AttachLeftArm(), DoAction(), JustDied(), MoveInLineOfSight(), PassengerBoarded(), and UpdateAI().
_looksAchievement
bool boss_kologarn::boss_kologarnAI::_looksAchievement
Referenced by DoAction(), GetData(), and Reset().
_right
ObjectGuid boss_kologarn::boss_kologarnAI::_right
Referenced by AttachRightArm(), DoAction(), JustDied(), MoveInLineOfSight(), PassengerBoarded(), and UpdateAI().
_rubbleAchievement
uint8 boss_kologarn::boss_kologarnAI::_rubbleAchievement
Referenced by DoAction(), GetData(), and Reset().
breathReady
bool boss_kologarn::boss_kologarnAI::breathReady
Referenced by Reset(), and UpdateAI().
events
EventMap boss_kologarn::boss_kologarnAI::events
eyebeamTarget
Unit* boss_kologarn::boss_kologarnAI::eyebeamTarget
Referenced by boss_kologarnAI(), and UpdateAI().
m_pInstance
InstanceScript* boss_kologarn::boss_kologarnAI::m_pInstance
Referenced by boss_kologarnAI(), DoAction(), JustDied(), JustEngagedWith(), and Reset().
summons
SummonList boss_kologarn::boss_kologarnAI::summons
Referenced by JustDied(), JustSummoned(), and Reset().
vehicle
Vehicle* boss_kologarn::boss_kologarnAI::vehicle
Referenced by boss_kologarnAI().