AzeorthCore: startFollow Class Reference
startFollow Class Reference
Public Member Functions
startFollow (Unit *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool Execute (uint64, uint32)
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Unit * _owner
Detailed Description
Constructor & Destructor Documentation
startFollow()
startFollow::startFollow (Unit * owner) inline
: _owner(owner)  { }
Member Function Documentation
Execute()
bool startFollow::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        if (InstanceScript* instance = _owner->GetInstanceScript())
            if (Creature* vashj = ObjectAccessor::GetCreature(*_owner, instance->GetGuidData(NPC_LADY_VASHJ)))
                _owner->GetMotionMaster()->MoveFollow(vashj, 3.0f, vashj->GetAngle(_owner), MOTION_SLOT_CONTROLLED);
        return true;
    }
References _owner, ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), Unit::GetMotionMaster(), MOTION_SLOT_CONTROLLED, MotionMaster::MoveFollow(), and NPC_LADY_VASHJ.
Member Data Documentation
_owner
Unit* startFollow::_owner private
Referenced by Execute().