AzerothCore: go_evil_book_for_dummies Class Reference
go_evil_book_for_dummies Class Reference
Public Member Functions
go_evil_book_for_dummies ()
bool HasLeatherSpecialty (Player *player)
bool OnGossipHello (Player *player, GameObject *gameobject) override
void SendActionMenu (Player *player, GameObject *, uint32 uiAction)
void SendConfirmLearn (Player *player, GameObject *gameobject, uint32 uiAction)
void SendConfirmUnlearn (Player *player, GameObject *gameobject, uint32 uiAction)
bool OnGossipSelect (Player *player, GameObject *gameobject, uint32 uiSender, uint32 uiAction) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, GameObject *)
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnModifyHealth (GameObject *, Unit *, int32 &, SpellInfo const *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
go_evil_book_for_dummies()
go_evil_book_for_dummies::go_evil_book_for_dummies () inline
: GameObjectScript("go_evil_book_for_dummies") { }
Member Function Documentation
HasLeatherSpecialty()
bool go_evil_book_for_dummies::HasLeatherSpecialty (Player * player) inline
    {
        return (player->HasSpell(S_DRAGON) || player->HasSpell(S_ELEMENTAL) || player->HasSpell(S_TRIBAL));
    }
References Player::HasSpell(), S_DRAGON, S_ELEMENTAL, and S_TRIBAL.
Referenced by OnGossipHello().
OnGossipHello()
bool go_evil_book_for_dummies::OnGossipHello (Player * player, GameObject * gameobject) inline override virtual
Reimplemented from GameObjectScript.
    {
        //ENGINEERING SPEC
        if (player->HasSkill(SKILL_ENGINEERING) && player->GetBaseSkillValue(SKILL_ENGINEERING) >= 225 && player->GetLevel() >= 35)
        {
            if (player->GetQuestRewardStatus(3643) || player->GetQuestRewardStatus(3641) || player->GetQuestRewardStatus(3639))
            {
                if (player->HasSpell(S_GOBLIN)) // Has Goblin specialization
                {
                    AddGossipItemFor(player, 0, GOSSIP_UNLEARN_GOBLIN, GOSSIP_SENDER_UNLEARN, GOSSIP_ACTION_INFO_DEF + 3, BOX_UNLEARN_ENGIN_SPEC, DoHighUnlearnCost(player), false);
                }
                else if (player->HasSpell(S_GNOMISH)) // Has Gnomish specialization
                {
                    AddGossipItemFor(player, 0, GOSSIP_UNLEARN_GNOMISH, GOSSIP_SENDER_UNLEARN, GOSSIP_ACTION_INFO_DEF + 4, BOX_UNLEARN_ENGIN_SPEC, DoHighUnlearnCost(player), false);
                }
                else // does not have any specialization
                {
                    AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_GOBLIN, GOSSIP_SENDER_LEARN, GOSSIP_ACTION_INFO_DEF + 1, BOX_LEARN_ENGIN_SPEC, DoLearnCost(player), false);
                    AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_GNOMISH, GOSSIP_SENDER_LEARN, GOSSIP_ACTION_INFO_DEF + 2, BOX_LEARN_ENGIN_SPEC, DoLearnCost(player), false);
                }
            }
        }
        //LEATHERWORKING SPEC
        if (player->HasSkill(SKILL_LEATHERWORKING) && player->GetBaseSkillValue(SKILL_LEATHERWORKING) >= 225 && player->GetLevel() >= 40)
        {
            if (!HasLeatherSpecialty(player) && (player->GetQuestRewardStatus(5141) || player->GetQuestRewardStatus(5143) || player->GetQuestRewardStatus(5144) || player->GetQuestRewardStatus(5145) || player->GetQuestRewardStatus(5146) || player->GetQuestRewardStatus(5148)))
            {
                AddGossipItemFor(player, GOSSIP_MENU_GO_SOOTHSAYING_FOR_DUMMIES, GOSSIP_MENU_OPTION_GO_LEARN_DRAGONSCALE, GOSSIP_SENDER_LEARN, GOSSIP_ACTION_INFO_DEF + 5);
                AddGossipItemFor(player, GOSSIP_MENU_GO_SOOTHSAYING_FOR_DUMMIES, GOSSIP_MENU_OPTION_GO_LEARN_ELEMENTAL, GOSSIP_SENDER_LEARN, GOSSIP_ACTION_INFO_DEF + 6);
                AddGossipItemFor(player, GOSSIP_MENU_GO_SOOTHSAYING_FOR_DUMMIES, GOSSIP_MENU_OPTION_GO_LEARN_TRIBAL, GOSSIP_SENDER_LEARN, GOSSIP_ACTION_INFO_DEF + 7);
            }
        }
        SendGossipMenuFor(player, player->GetGossipTextId(gameobject), gameobject->GetGUID());
        return true;
    }
References AddGossipItemFor(), BOX_LEARN_ENGIN_SPEC, BOX_UNLEARN_ENGIN_SPEC, DoHighUnlearnCost(), DoLearnCost(), Player::GetBaseSkillValue(), Player::GetGossipTextId(), Object::GetGUID(), Unit::GetLevel(), Player::GetQuestRewardStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_LEARN_GNOMISH, GOSSIP_LEARN_GOBLIN, GOSSIP_MENU_GO_SOOTHSAYING_FOR_DUMMIES, GOSSIP_MENU_OPTION_GO_LEARN_DRAGONSCALE, GOSSIP_MENU_OPTION_GO_LEARN_ELEMENTAL, GOSSIP_MENU_OPTION_GO_LEARN_TRIBAL, GOSSIP_SENDER_LEARN, GOSSIP_SENDER_UNLEARN, GOSSIP_UNLEARN_GNOMISH, GOSSIP_UNLEARN_GOBLIN, HasLeatherSpecialty(), Player::HasSkill(), Player::HasSpell(), S_GNOMISH, S_GOBLIN, SendGossipMenuFor(), SKILL_ENGINEERING, and SKILL_LEATHERWORKING.
OnGossipSelect()
bool go_evil_book_for_dummies::OnGossipSelect (Player * player, GameObject * gameobject, uint32 uiSender, uint32 uiAction) inline override virtual
Reimplemented from GameObjectScript.
    {
        ClearGossipMenuFor(player);
        switch (uiSender)
        {
            case GOSSIP_SENDER_LEARN:
                SendActionMenu(player, gameobject, uiAction);
                break;
            case GOSSIP_SENDER_UNLEARN:
                SendActionMenu(player, gameobject, uiAction);
                break;
        }
        return true;
    }
References ClearGossipMenuFor(), GOSSIP_SENDER_LEARN, GOSSIP_SENDER_UNLEARN, and SendActionMenu().
SendActionMenu()
void go_evil_book_for_dummies::SendActionMenu (Player * player, GameObject * , uint32 uiAction) inline
    {
        switch (uiAction)
        {
            // Learn Goblin
            case GOSSIP_ACTION_INFO_DEF + 1:
                ProcessCastaction(player, nullptr, S_GOBLIN, S_LEARN_GOBLIN, DoLearnCost(player));
                break;
            // Learn Gnomish
            case GOSSIP_ACTION_INFO_DEF + 2:
                ProcessCastaction(player, nullptr, S_GNOMISH, S_LEARN_GNOMISH, DoLearnCost(player));
                break;
            //Unlearn Goblin
            case GOSSIP_ACTION_INFO_DEF + 3:
                ProcessUnlearnAction(player, nullptr, S_UNLEARN_GOBLIN, 0, DoHighUnlearnCost(player));
                break;
            //Unlearn Gnomish
            case GOSSIP_ACTION_INFO_DEF + 4:
                ProcessUnlearnAction(player, nullptr, S_UNLEARN_GNOMISH, 0, DoHighUnlearnCost(player));
                break;
            //Learn Dragon
            case GOSSIP_ACTION_INFO_DEF + 5:
                ProcessCastaction(player, nullptr, S_DRAGON, S_LEARN_DRAGON, 0);
                break;
            //Learn Elemental
            case GOSSIP_ACTION_INFO_DEF + 6:
                ProcessCastaction(player, nullptr, S_ELEMENTAL, S_LEARN_ELEMENTAL, 0);
                break;
            //Learn Tribal
            case GOSSIP_ACTION_INFO_DEF + 7:
                ProcessCastaction(player, nullptr, S_TRIBAL, S_LEARN_TRIBAL, 0);
                break;
        }
    }
References DoHighUnlearnCost(), DoLearnCost(), GOSSIP_ACTION_INFO_DEF, ProcessCastaction(), ProcessUnlearnAction(), S_DRAGON, S_ELEMENTAL, S_GNOMISH, S_GOBLIN, S_LEARN_DRAGON, S_LEARN_ELEMENTAL, S_LEARN_GNOMISH, S_LEARN_GOBLIN, S_LEARN_TRIBAL, S_TRIBAL, S_UNLEARN_GNOMISH, and S_UNLEARN_GOBLIN.
Referenced by OnGossipSelect().
SendConfirmLearn()
void go_evil_book_for_dummies::SendConfirmLearn (Player * player, GameObject * gameobject, uint32 uiAction) inline
    {
        switch (uiAction)
        {
            // Goblin
            case GOSSIP_ACTION_INFO_DEF + 1:
                AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_GOBLIN, GOSSIP_SENDER_CHECK, uiAction);
                SendGossipMenuFor(player, player->GetGossipTextId(gameobject), gameobject->GetGUID());
                break;
            // Gnomish
            case GOSSIP_ACTION_INFO_DEF + 2:
                AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_GNOMISH, GOSSIP_SENDER_CHECK, uiAction);
                SendGossipMenuFor(player, player->GetGossipTextId(gameobject), gameobject->GetGUID());
                break;
        }
    }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_LEARN_GNOMISH, GOSSIP_LEARN_GOBLIN, GOSSIP_SENDER_CHECK, and SendGossipMenuFor().
SendConfirmUnlearn()
void go_evil_book_for_dummies::SendConfirmUnlearn (Player * player, GameObject * gameobject, uint32 uiAction) inline
    {
        switch (uiAction)
        {
            // Goblin
            case GOSSIP_ACTION_INFO_DEF + 3:
                AddGossipItemFor(player, 0, GOSSIP_UNLEARN_GOBLIN, GOSSIP_SENDER_CHECK, uiAction, BOX_UNLEARN_ENGIN_SPEC, DoHighUnlearnCost(player), false);
                SendGossipMenuFor(player, player->GetGossipTextId(gameobject), gameobject->GetGUID());
                break;
            // Gnomish
            case GOSSIP_ACTION_INFO_DEF + 4:
                AddGossipItemFor(player, 0, GOSSIP_UNLEARN_GNOMISH, GOSSIP_SENDER_CHECK, uiAction, BOX_UNLEARN_ENGIN_SPEC, DoHighUnlearnCost(player), false);
                SendGossipMenuFor(player, player->GetGossipTextId(gameobject), gameobject->GetGUID());
                break;
        }
    }
References AddGossipItemFor(), BOX_UNLEARN_ENGIN_SPEC, DoHighUnlearnCost(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_CHECK, GOSSIP_UNLEARN_GNOMISH, GOSSIP_UNLEARN_GOBLIN, and SendGossipMenuFor().