AzeorthCore: AsyncAcceptor Class Reference
AsyncAcceptor Class Reference
#include "AsyncAcceptor.h"
Public Types
typedef void(* AcceptCallback) (tcp::socket &&newSocket, uint32 threadIndex)
Public Member Functions
AsyncAcceptor (Acore::Asio::IoContext &ioContext, std::string const &bindIp, uint16 port)
template<class T >
void AsyncAccept ()
template<AcceptCallback acceptCallback>
void AsyncAcceptWithCallback ()
bool Bind ()
void Close ()
void SetSocketFactory (std::function< std::pair< tcp::socket *, uint32 >()> func)
Private Member Functions
std::pair< tcp::socket *, uint32 > DefeaultSocketFactory ()
Private Attributes
tcp::acceptor _acceptor
tcp::endpoint _endpoint
tcp::socket _socket
std::atomic< bool > _closed
std::function< std::pair< tcp::socket *, uint32 >()> _socketFactory
Detailed Description
Member Typedef Documentation
AcceptCallback
typedef void(* AsyncAcceptor::AcceptCallback) (tcp::socket &&newSocket, uint32 threadIndex)
Constructor & Destructor Documentation
AsyncAcceptor()
AsyncAcceptor::AsyncAcceptor (Acore::Asio::IoContext & ioContext, std::string const & bindIp, uint16 port) inline
                                                                                       :
        _acceptor(ioContext), _endpoint(Acore::Net::make_address(bindIp), port),
        _socket(ioContext), _closed(false), _socketFactory(std::bind(&AsyncAcceptor::DefeaultSocketFactory, this))
    {
    }
Member Function Documentation
AsyncAccept()
template<class T > void AsyncAcceptor::AsyncAccept
{
    _acceptor.async_accept(_socket, [this](boost::system::error_code error)
    {
        if (!error)
        {
            try
            {
                // this-> is required here to fix an segmentation fault in gcc 4.7.2 - reason is lambdas in a templated class
                std::make_shared<T>(std::move(this->_socket))->Start();
            }
            catch (boost::system::system_error const& err)
            {
                LOG_INFO("network", "Failed to retrieve client's remote address {}", err.what());
            }
        }
        // lets slap some more this-> on this so we can fix this bug with gcc 4.7.2 throwing internals in yo face
        if (!_closed)
            this->AsyncAccept<T>();
    });
}
References _acceptor, _closed, _socket, and LOG_INFO.
AsyncAcceptWithCallback()
template<AcceptCallback acceptCallback> void AsyncAcceptor::AsyncAcceptWithCallback () inline
    {
        tcp::socket* socket;
        uint32 threadIndex;
        std::tie(socket, threadIndex) = _socketFactory();
        _acceptor.async_accept(*socket, [this, socket, threadIndex](boost::system::error_code error)
        {
            if (!error)
            {
                try
                {
                    socket->non_blocking(true);
                    acceptCallback(std::move(*socket), threadIndex);
                }
                catch (boost::system::system_error const& err)
                {
                    LOG_INFO("network", "Failed to initialize client's socket {}", err.what());
                }
            }
            if (!_closed)
                this->AsyncAcceptWithCallback<acceptCallback>();
        });
    }
References _acceptor, _closed, _socketFactory, and LOG_INFO.
Referenced by AuthSocketMgr::StartNetwork(), and WorldSocketMgr::StartWorldNetwork().
Bind()
bool AsyncAcceptor::Bind () inline
    {
        boost::system::error_code errorCode;
        _acceptor.open(_endpoint.protocol(), errorCode);
        if (errorCode)
        {
            LOG_INFO("network", "Failed to open acceptor {}", errorCode.message());
            return false;
        }
#if AC_PLATFORM != AC_PLATFORM_WINDOWS
        _acceptor.set_option(boost::asio::ip::tcp::acceptor::reuse_address(true), errorCode);
        if (errorCode)
        {
            LOG_INFO("network", "Failed to set reuse_address option on acceptor {}", errorCode.message());
            return false;
        }
#endif
        _acceptor.bind(_endpoint, errorCode);
        if (errorCode)
        {
            LOG_INFO("network", "Could not bind to {}:{} {}", _endpoint.address().to_string(), _endpoint.port(), errorCode.message());
            return false;
        }
        _acceptor.listen(ACORE_MAX_LISTEN_CONNECTIONS, errorCode);
        if (errorCode)
        {
            LOG_INFO("network", "Failed to start listening on {}:{} {}", _endpoint.address().to_string(), _endpoint.port(), errorCode.message());
            return false;
        }
        return true;
    }
References _acceptor, _endpoint, ACORE_MAX_LISTEN_CONNECTIONS, and LOG_INFO.
Referenced by SocketMgr< SocketType >::StartNetwork().
Close()
void AsyncAcceptor::Close () inline
    {
        if (_closed.exchange(true))
            return;
        boost::system::error_code err;
        _acceptor.close(err);
    }
References _acceptor, and _closed.
Referenced by SocketMgr< SocketType >::StopNetwork().
DefeaultSocketFactory()
std::pair< tcp::socket *, uint32 > AsyncAcceptor::DefeaultSocketFactory () inline private
{ return std::make_pair(&_socket, 0); }
References _socket.
SetSocketFactory()
void AsyncAcceptor::SetSocketFactory (std::function< std::pair< tcp::socket *, uint32 >()> func) inline
{ _socketFactory = func; }
References _socketFactory.
Referenced by SocketMgr< SocketType >::StartNetwork().
Member Data Documentation
_acceptor
tcp::acceptor AsyncAcceptor::_acceptor private
Referenced by AsyncAccept(), AsyncAcceptWithCallback(), Bind(), and Close().
_closed
std::atomic<bool> AsyncAcceptor::_closed private
Referenced by AsyncAccept(), AsyncAcceptWithCallback(), and Close().
_endpoint
tcp::endpoint AsyncAcceptor::_endpoint private
Referenced by Bind().
_socket
tcp::socket AsyncAcceptor::_socket private
Referenced by AsyncAccept(), and DefeaultSocketFactory().
_socketFactory
std::function<std::pair<tcp::socket*, uint32>()> AsyncAcceptor::_socketFactory private
Referenced by AsyncAcceptWithCallback(), and SetSocketFactory().