name: generate-doxygen-doc
on:
  workflow_dispatch:
  schedule:
    - cron: '30 20 * * 1'

jobs:
  build-doxygen-doc:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: "clone azerothcore-wotlk source"
        run: |
          git clone --single-branch https://github.com/azerothcore/azerothcore-wotlk
          mv azerothcore-wotlk pages/doxygen/azerothcore-wotlk

      - name: "run doxygen"
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            working-directory: 'pages/doxygen/'
            doxyfile-path: 'Doxyfile'

      - name: "check doxygen output"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd pages/doxygen/
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          rm -rf azerothcore-wotlk
          git add .
          git commit -m "chore: update doxygen documentation"
          git push
