name: generate-doxygen-doc
on:
  workflow_dispatch:

jobs:
  build-doxygen-doc:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: "clone azerothcore-wotlk source"
        run: |
          git clone --single-branch https://github.com/azerothcore/azerothcore-wotlk
          mv azerothcore-wotlk pages/doxygen/azerothcore-wotlk

      - name: "run doxygen"
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            working-directory: 'pages/doxygen/'
            doxyfile-path: 'Doxyfile'

      - name: "check doxygen output"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          cd pages/doxygen/
          ls
