name: generate-doxygen-doc
on:
  workflow_dispatch:

jobs:
  build-doxygen-doc:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: "run scripts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --single-branch https://github.com/azerothcore/azerothcore-wotlk
          mkdir docs
          mkdir azerothcore-wotlk/docs

      - name: "doxygen-doc"
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            working-directory: 'azerothcore-wotlk/src'
            # doxyfile-path: 'docs/Doxygen'
