name: generate-doxygen-doc
on:
  workflow_dispatch:

jobs:
  build-doxygen-doc:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: "run scripts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --single-branch https://github.com/azerothcore/azerothcore-wotlk
  

      - name: Action Doxygen and GitHub Pages
        id: ghaction
        uses: AgarwalSaurav/ghaction-doxygen-ghpages@release/v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: pages/doxygen/
          doxyfile-path: Doxyfile
          html-output-folder: pages/doxygen/
          target-folder: pages/doxygen/
