AzeorthCore: GroupScript Class Reference
GroupScript Class Reference
#include "ScriptMgr.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnAddMember (Group *, ObjectGuid)
virtual void OnInviteMember (Group *, ObjectGuid)
virtual void OnRemoveMember (Group *, ObjectGuid, RemoveMethod, ObjectGuid, const char *)
virtual void OnChangeLeader (Group *, ObjectGuid, ObjectGuid)
virtual void OnDisband (Group *)
virtual bool CanGroupJoinBattlegroundQueue (Group const *, Player *, Battleground const *, uint32, bool, uint32)
virtual void OnCreate (Group *, Player *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
GroupScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
GroupScript()
GroupScript::GroupScript (const char * name) protected
    : ScriptObject(name)
{
    ScriptRegistry<GroupScript>::AddScript(this);
}
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
CanGroupJoinBattlegroundQueue()
virtual bool GroupScript::CanGroupJoinBattlegroundQueue (Group const * , Player * , Battleground const * , uint32 , bool , uint32) inline virtual
{ return true; }
Referenced by ScriptMgr::CanGroupJoinBattlegroundQueue().
IsDatabaseBound()
bool GroupScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
OnAddMember()
virtual void GroupScript::OnAddMember (Group * , ObjectGuid) inline virtual
Reimplemented in lfg::LFGGroupScript.
{ }
Referenced by ScriptMgr::OnGroupAddMember().
OnChangeLeader()
virtual void GroupScript::OnChangeLeader (Group * , ObjectGuid , ObjectGuid) inline virtual
Reimplemented in lfg::LFGGroupScript.
{ }
Referenced by ScriptMgr::OnGroupChangeLeader().
OnCreate()
virtual void GroupScript::OnCreate (Group * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnCreate().
OnDisband()
virtual void GroupScript::OnDisband (Group *) inline virtual
Reimplemented in lfg::LFGGroupScript.
{ }
Referenced by ScriptMgr::OnGroupDisband().
OnInviteMember()
virtual void GroupScript::OnInviteMember (Group * , ObjectGuid) inline virtual
Reimplemented in lfg::LFGGroupScript.
{ }
Referenced by ScriptMgr::OnGroupInviteMember().
OnRemoveMember()
virtual void GroupScript::OnRemoveMember (Group * , ObjectGuid , RemoveMethod , ObjectGuid , const char *) inline virtual
Reimplemented in lfg::LFGGroupScript.
{ }
Referenced by ScriptMgr::OnGroupRemoveMember().