AzerothCore: lfg::LFGGroupScript Class Reference
lfg::LFGGroupScript Class Reference
#include "LFGScripts.h"
Public Member Functions
LFGGroupScript ()
void OnAddMember (Group *group, ObjectGuid guid) override
void OnRemoveMember (Group *group, ObjectGuid guid, RemoveMethod method, ObjectGuid kicker, char const *reason) override
void OnDisband (Group *group) override
void OnChangeLeader (Group *group, ObjectGuid newLeaderGuid, ObjectGuid oldLeaderGuid) override
void OnInviteMember (Group *group, ObjectGuid guid) override
Public Member Functions inherited from GroupScript
bool IsDatabaseBound () const override
virtual void OnAddMember (Group *, ObjectGuid)
virtual void OnInviteMember (Group *, ObjectGuid)
virtual void OnRemoveMember (Group *, ObjectGuid, RemoveMethod, ObjectGuid, const char *)
virtual void OnChangeLeader (Group *, ObjectGuid, ObjectGuid)
virtual void OnDisband (Group *)
virtual bool CanGroupJoinBattlegroundQueue (Group const *, Player *, Battleground const *, uint32, bool, uint32)
virtual void OnCreate (Group *, Player *)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from GroupScript
GroupScript (const char *name, std::vector< uint16 > enabledHooks=std::vector< uint16 >())
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
LFGGroupScript()
lfg::LFGGroupScript::LFGGroupScript ()
                                   :
        GroupScript("LFGGroupScript",
        {
            GROUPHOOK_ON_ADD_MEMBER,
            GROUPHOOK_ON_REMOVE_MEMBER,
            GROUPHOOK_ON_DISBAND,
            GROUPHOOK_ON_CHANGE_LEADER,
            GROUPHOOK_ON_INVITE_MEMBER
        })
    {
    }
References GROUPHOOK_ON_ADD_MEMBER, GROUPHOOK_ON_CHANGE_LEADER, GROUPHOOK_ON_DISBAND, GROUPHOOK_ON_INVITE_MEMBER, and GROUPHOOK_ON_REMOVE_MEMBER.
Member Function Documentation
OnAddMember()
void lfg::LFGGroupScript::OnAddMember (Group * group, ObjectGuid guid) override virtual
Reimplemented from GroupScript.
    {
        if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
            return;
        ObjectGuid gguid = group->GetGUID();
        ObjectGuid leader = group->GetLeaderGUID();
        if (leader == guid)
        {
            LOG_DEBUG("lfg", "LFGScripts::OnAddMember [{}]: added [{}] leader [{}]", gguid.ToString(), guid.ToString(), leader.ToString());
            sLFGMgr->SetLeader(gguid, guid);
        }
        else
        {
            LfgState gstate = sLFGMgr->GetState(gguid);
            LfgState state = sLFGMgr->GetState(guid);
            LOG_DEBUG("lfg", "LFGScripts::OnAddMember [{}]: added [{}] leader [{}] gstate: {}, state: {}",
                gguid.ToString(), guid.ToString(), leader.ToString(), gstate, state);
            if (state == LFG_STATE_QUEUED)
                sLFGMgr->LeaveLfg(guid);
            if (gstate == LFG_STATE_QUEUED)
                sLFGMgr->LeaveLfg(gguid);
        }
        if (!group->isLFGGroup())
        {
            sLFGMgr->LeaveAllLfgQueues(leader, true, gguid); // pussywizard: invited, queued, party formed, neither party nor new member are queued, but leader is in queue solo!
            sLFGMgr->LeaveAllLfgQueues(guid, false);
        }
        sLFGMgr->SetGroup(guid, gguid);
        sLFGMgr->AddPlayerToGroup(gguid, guid);
        // pussywizard: after all necessary actions handle raid browser
        if (sLFGMgr->GetState(guid) == LFG_STATE_RAIDBROWSER)
            sLFGMgr->LeaveLfg(guid);
    }
References Group::GetGUID(), Group::GetLeaderGUID(), Group::isLFGGroup(), lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, lfg::LFG_STATE_QUEUED, lfg::LFG_STATE_RAIDBROWSER, LOG_DEBUG, sLFGMgr, and ObjectGuid::ToString().
OnChangeLeader()
void lfg::LFGGroupScript::OnChangeLeader (Group * group, ObjectGuid newLeaderGuid, ObjectGuid oldLeaderGuid) override virtual
Reimplemented from GroupScript.
    {
        if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
            return;
        ObjectGuid gguid = group->GetGUID();
        LOG_DEBUG("lfg", "LFGScripts::OnChangeLeader [{}]: old [{}] new [{}]",
            gguid.ToString(), newLeaderGuid.ToString(), oldLeaderGuid.ToString());
        sLFGMgr->SetLeader(gguid, newLeaderGuid);
        // pussywizard: after all necessary actions handle raid browser
        if (sLFGMgr->GetState(oldLeaderGuid) == LFG_STATE_RAIDBROWSER)
            sLFGMgr->LeaveLfg(oldLeaderGuid);
    }
References Group::GetGUID(), lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, lfg::LFG_STATE_RAIDBROWSER, LOG_DEBUG, sLFGMgr, and ObjectGuid::ToString().
OnDisband()
void lfg::LFGGroupScript::OnDisband (Group * group) override virtual
Reimplemented from GroupScript.
    {
        if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
            return;
        ObjectGuid gguid = group->GetGUID();
        LOG_DEBUG("lfg", "LFGScripts::OnDisband [{}]", gguid.ToString());
        // pussywizard: after all necessary actions handle raid browser
        if (sLFGMgr->GetState(group->GetLeaderGUID()) == LFG_STATE_RAIDBROWSER)
            sLFGMgr->LeaveLfg(group->GetLeaderGUID());
        sLFGMgr->RemoveGroupData(gguid);
    }
References Group::GetGUID(), Group::GetLeaderGUID(), lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, lfg::LFG_STATE_RAIDBROWSER, LOG_DEBUG, sLFGMgr, and ObjectGuid::ToString().
OnInviteMember()
void lfg::LFGGroupScript::OnInviteMember (Group * group, ObjectGuid guid) override virtual
Reimplemented from GroupScript.
    {
        // used only with EXTRA_LOGS
        (void)guid;
        if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
            return;
        ObjectGuid gguid = group->GetGUID();
        ObjectGuid leader = group->GetLeaderGUID();
        LOG_DEBUG("lfg", "LFGScripts::OnInviteMember [{}]: invite [{}] leader [{}]", gguid.ToString(), guid.ToString(), leader.ToString());
        // No gguid ==  new group being formed
        // No leader == after group creation first invite is new leader
        // leader and no gguid == first invite after leader is added to new group (this is the real invite)
        if (leader && !gguid)
        {
            sLFGMgr->LeaveLfg(leader);
            sLFGMgr->LeaveAllLfgQueues(leader, true);
        }
    }
References Group::GetGUID(), Group::GetLeaderGUID(), lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, LOG_DEBUG, sLFGMgr, and ObjectGuid::ToString().
OnRemoveMember()
void lfg::LFGGroupScript::OnRemoveMember (Group * group, ObjectGuid guid, RemoveMethod method, ObjectGuid kicker, char const * reason) override virtual
Reimplemented from GroupScript.
    {
        // used only with EXTRA_LOGS
        (void)kicker;
        (void)reason;
        if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
            return;
        ObjectGuid gguid = group->GetGUID();
        LOG_DEBUG("lfg", "LFGScripts::OnRemoveMember [{}]: remove [{}] Method: {} Kicker: [{}] Reason: {}",
            gguid.ToString(), guid.ToString(), method, kicker.ToString(), (reason ? reason : ""));
        bool isLFG = group->isLFGGroup();
        LfgState state = sLFGMgr->GetState(gguid);
        uint32 dungeonId = sLFGMgr->GetDungeon(gguid, false);
        // If group is being formed after proposal success do nothing more
        if (state == LFG_STATE_PROPOSAL && method == GROUP_REMOVEMETHOD_DEFAULT)
        {
            // LfgData: Remove player from group
            sLFGMgr->SetGroup(guid, ObjectGuid::Empty);
            sLFGMgr->RemovePlayerFromGroup(gguid, guid);
            return;
        }
        sLFGMgr->LeaveLfg(guid);
        sLFGMgr->LeaveAllLfgQueues(guid, true, gguid);
        sLFGMgr->SetGroup(guid, ObjectGuid::Empty);
        uint8 players = sLFGMgr->RemovePlayerFromGroup(gguid, guid);
        // pussywizard: after all necessary actions handle raid browser
        // pussywizard: already done above
        //if (sLFGMgr->GetState(guid) == LFG_STATE_RAIDBROWSER)
        //  sLFGMgr->LeaveLfg(guid);
        // Xinef: only LFG groups can go below
        if (!isLFG)
            return;
        if (state != LFG_STATE_FINISHED_DUNGEON && group) // Need more players to finish the dungeon
        {
            if (Player* leader = ObjectAccessor::FindConnectedPlayer(sLFGMgr->GetLeader(gguid)))
            {
                sLFGMgr->SetDungeon(gguid, dungeonId);
                leader->GetSession()->SendLfgOfferContinue(sLFGMgr->GetDungeon(gguid, false));
            }
        }
        if (Player* player = ObjectAccessor::FindConnectedPlayer(guid))
        {
            // xinef: fixed dungeon deserter
            if (method != GROUP_REMOVEMETHOD_KICK_LFG && state != LFG_STATE_FINISHED_DUNGEON &&
                    player->HasAura(LFG_SPELL_DUNGEON_COOLDOWN) && players >= LFG_GROUP_KICK_VOTES_NEEDED &&
                    sWorld->getBoolConfig(CONFIG_LFG_CAST_DESERTER))
            {
                player->AddAura(LFG_SPELL_DUNGEON_DESERTER, player);
            }
            //else if (state == LFG_STATE_BOOT)
            // Update internal kick cooldown of kicked
            player->GetSession()->SendLfgUpdateParty(LfgUpdateData(LFG_UPDATETYPE_LEADER_UNK1));
            if (player->GetMap()->IsDungeon())            // Teleport player out the dungeon
            {
                // Xinef: no longer valid sLFGMgr->TeleportPlayer(player, true);
                if (!player->IsBeingTeleportedFar() && player->GetMapId() == sLFGMgr->GetDungeonMapId(gguid))
                    player->TeleportToEntryPoint();
            }
        }
    }
References CONFIG_LFG_CAST_DESERTER, ObjectGuid::Empty, ObjectAccessor::FindConnectedPlayer(), Group::GetGUID(), GROUP_REMOVEMETHOD_DEFAULT, GROUP_REMOVEMETHOD_KICK_LFG, Group::isLFGGroup(), lfg::LFG_GROUP_KICK_VOTES_NEEDED, lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, lfg::LFG_SPELL_DUNGEON_COOLDOWN, lfg::LFG_SPELL_DUNGEON_DESERTER, lfg::LFG_STATE_FINISHED_DUNGEON, lfg::LFG_STATE_PROPOSAL, lfg::LFG_UPDATETYPE_LEADER_UNK1, LOG_DEBUG, sLFGMgr, sWorld, and ObjectGuid::ToString().