AzerothCore: boss_zuljin::boss_zuljinAI Struct Reference
boss_zuljin::boss_zuljinAI Struct Reference
Public Member Functions
boss_zuljinAI (Creature *creature)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void AttackStart (Unit *who) override
void DoMeleeAttackIfReady ()
void SpawnAdds ()
void DespawnAdds ()
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void EnterPhase (uint32 NextPhase)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat (NOTE: Creature engage logic should NOT be here, but in JustEngagedWith, which happens once threat is established!)
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the max threat target, which may not always be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
ObjectGuid SpiritGUID [4]
ObjectGuid ClawTargetGUID
ObjectGuid TankGUID
uint32 Phase
uint32 health_20
uint32 Intro_Timer
uint32 Berserk_Timer
uint32 Whirlwind_Timer
uint32 Grievous_Throw_Timer
uint32 Creeping_Paralysis_Timer
uint32 Overpower_Timer
uint32 Claw_Rage_Timer
uint32 Lynx_Rush_Timer
uint32 Claw_Counter
uint32 Claw_Loop_Timer
uint32 Flame_Whirl_Timer
uint32 Flame_Breath_Timer
uint32 Pillar_Of_Fire_Timer
SummonList Summons
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_zuljinAI()
boss_zuljin::boss_zuljinAI::boss_zuljinAI (Creature * creature) inline
                                          : ScriptedAI(creature), Summons(me)
        {
            instance = creature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
AttackStart()
void boss_zuljin::boss_zuljinAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (Phase == 2)
                AttackStartNoMove(who);
            else
                ScriptedAI::AttackStart(who);
        }
References ScriptedAI::AttackStart(), and ScriptedAI::AttackStartNoMove().
Referenced by EnterPhase(), and UpdateAI().
DespawnAdds()
void boss_zuljin::boss_zuljinAI::DespawnAdds () inline
        {
            for (uint8 i = 0; i < 4; ++i)
            {
                if (SpiritGUID[i])
                {
                    if (Unit* temp = ObjectAccessor::GetUnit(*me, SpiritGUID[i]))
                    {
                        temp->SetVisible(false);
                        temp->setDeathState(DEAD);
                    }
                }
                SpiritGUID[i].Clear();
            }
        }
References ObjectGuid::Clear(), DEAD, ObjectAccessor::GetUnit(), ScriptedAI::me, and SpiritGUID.
DoMeleeAttackIfReady()
void boss_zuljin::boss_zuljinAI::DoMeleeAttackIfReady () inline
        {
            if (!me->IsNonMeleeSpellCast(false))
            {
                if (me->isAttackReady() && me->IsWithinMeleeRange(me->GetVictim()))
                {
                    if (Phase == 1 && !Overpower_Timer)
                    {
                        uint32 health = me->GetVictim()->GetHealth();
                        me->AttackerStateUpdate(me->GetVictim());
                        if (me->GetVictim() && health == me->GetVictim()->GetHealth())
{
                            DoCastVictim(SPELL_OVERPOWER, false);
                            Overpower_Timer = 5000;
                        }
                    }
                    else me->AttackerStateUpdate(me->GetVictim());
                    me->resetAttackTimer();
                }
            }
        }
References Unit::AttackerStateUpdate(), UnitAI::DoCastVictim(), Unit::GetHealth(), Unit::GetVictim(), Unit::isAttackReady(), Unit::IsNonMeleeSpellCast(), Unit::IsWithinMeleeRange(), ScriptedAI::me, Overpower_Timer, Unit::resetAttackTimer(), and SPELL_OVERPOWER.
Referenced by UpdateAI().
EnterPhase()
void boss_zuljin::boss_zuljinAI::EnterPhase (uint32 NextPhase) inline
        {
            switch (NextPhase)
            {
                case 0:
                    break;
                case 1:
                case 2:
                case 3:
                case 4:
                    me->NearTeleportTo(CENTER_X, CENTER_Y, CENTER_Z, me->GetOrientation());
                    DoResetThreatList();
                    me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID, 0);
                    me->RemoveAurasDueToSpell(Transform[Phase].unaura);
                    DoCast(me, Transform[Phase].spell);
                    Talk(Transform[Phase].text);
                    if (Phase > 0)
                    {
                        if (Unit* Temp = ObjectAccessor::GetUnit(*me, SpiritGUID[Phase - 1]))
                            Temp->SetUInt32Value(UNIT_FIELD_BYTES_1, UNIT_STAND_STATE_DEAD);
                    }
                    if (Unit* Temp = ObjectAccessor::GetUnit(*me, SpiritGUID[NextPhase - 1]))
                        Temp->CastSpell(me, SPELL_SIPHON_SOUL, false); // should m cast on temp
                    if (NextPhase == 2)
                    {
                        me->GetMotionMaster()->Clear();
                        DoCast(me, SPELL_ENERGY_STORM, true); // enemy aura
                        for (uint8 i = 0; i < 4; ++i)
{
                            Creature* Vortex = DoSpawnCreature(CREATURE_FEATHER_VORTEX, 0, 0, 0, 0, TEMPSUMMON_CORPSE_DESPAWN, 0);
                            if (Vortex)
{
                                Vortex->CastSpell(Vortex, SPELL_CYCLONE_PASSIVE, true);
                                Vortex->CastSpell(Vortex, SPELL_CYCLONE_VISUAL, true);
                                Vortex->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                                Vortex->SetSpeed(MOVE_RUN, 1.0f);
                                Vortex->AI()->AttackStart(SelectTarget(SelectTargetMethod::Random, 0));
                                DoZoneInCombat(Vortex);
                            }
                        }
                    }
                    else
                        AttackStart(me->GetVictim());
                    if (NextPhase == 3)
                    {
                        me->RemoveAurasDueToSpell(SPELL_ENERGY_STORM);
                        Summons.DespawnEntry(CREATURE_FEATHER_VORTEX);
                        me->GetMotionMaster()->MoveChase(me->GetVictim());
                    }
                    break;
                default:
                    break;
            }
            Phase = NextPhase;
        }
References Creature::AI(), UnitAI::AttackStart(), AttackStart(), Unit::CastSpell(), CENTER_X, CENTER_Y, CENTER_Z, MotionMaster::Clear(), CREATURE_FEATHER_VORTEX, UnitAI::DoCast(), ScriptedAI::DoResetThreatList(), ScriptedAI::DoSpawnCreature(), CreatureAI::DoZoneInCombat(), Unit::GetMotionMaster(), Position::GetOrientation(), ObjectAccessor::GetUnit(), Unit::GetVictim(), ScriptedAI::me, MOVE_RUN, MotionMaster::MoveChase(), Unit::NearTeleportTo(), Unit::RemoveAurasDueToSpell(), UnitAI::SelectTarget(), Unit::SetSpeed(), Object::SetUInt32Value(), Unit::SetUnitFlag(), SPELL_CYCLONE_PASSIVE, SPELL_CYCLONE_VISUAL, SPELL_ENERGY_STORM, SPELL_SIPHON_SOUL, SpiritGUID, TEMPSUMMON_CORPSE_DESPAWN, Transform, UNIT_FIELD_BYTES_1, UNIT_FLAG_NOT_SELECTABLE, UNIT_STAND_STATE_DEAD, and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by JustEngagedWith(), and UpdateAI().
JustDied()
void boss_zuljin::boss_zuljinAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            instance->SetData(DATA_ZULJINEVENT, DONE);
            Talk(YELL_DEATH);
            Summons.DespawnEntry(CREATURE_COLUMN_OF_FIRE);
            if (Unit* Temp = ObjectAccessor::GetUnit(*me, SpiritGUID[3]))
                Temp->SetUInt32Value(UNIT_FIELD_BYTES_1, UNIT_STAND_STATE_DEAD);
        }
References CREATURE_COLUMN_OF_FIRE, DATA_ZULJINEVENT, DONE, ObjectAccessor::GetUnit(), instance, ScriptedAI::me, ZoneScript::SetData(), SpiritGUID, UNIT_FIELD_BYTES_1, UNIT_STAND_STATE_DEAD, and YELL_DEATH.
JustEngagedWith()
void boss_zuljin::boss_zuljinAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            instance->SetData(DATA_ZULJINEVENT, IN_PROGRESS);
            DoZoneInCombat();
            Talk(YELL_INTRO);
            SpawnAdds();
            EnterPhase(0);
        }
References DATA_ZULJINEVENT, CreatureAI::DoZoneInCombat(), EnterPhase(), IN_PROGRESS, instance, ZoneScript::SetData(), SpawnAdds(), and YELL_INTRO.
JustSummoned()
void boss_zuljin::boss_zuljinAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            Summons.Summon(summon);
        }
KilledUnit()
void boss_zuljin::boss_zuljinAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (Intro_Timer)
                return;
            Talk(YELL_KILL);
        }
References Intro_Timer, and YELL_KILL.
Reset()
void boss_zuljin::boss_zuljinAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            instance->SetData(DATA_ZULJINEVENT, NOT_STARTED);
            Phase = 0;
            health_20 = me->CountPctFromMaxHealth(20);
            Intro_Timer = 37000;
            Berserk_Timer = 600000;
            Whirlwind_Timer = 7000;
            Grievous_Throw_Timer = 8000;
            Creeping_Paralysis_Timer = 7000;
            Overpower_Timer = 0;
            Claw_Rage_Timer = 5000;
            Lynx_Rush_Timer = 14000;
            Claw_Loop_Timer = 0;
            Claw_Counter = 0;
            Flame_Whirl_Timer = 5000;
            Flame_Breath_Timer = 6000;
            Pillar_Of_Fire_Timer = 7000;
            ClawTargetGUID.Clear();
            TankGUID.Clear();
            Summons.DespawnAll();
            me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID, 33975);
            //me->SetUInt32Value(UNIT_VIRTUAL_ITEM_INFO, 218172674);
            //me->SetByteValue(UNIT_FIELD_BYTES_2, 0, SHEATH_STATE_MELEE);
        }
References Berserk_Timer, Claw_Counter, Claw_Loop_Timer, Claw_Rage_Timer, ClawTargetGUID, ObjectGuid::Clear(), Unit::CountPctFromMaxHealth(), Creeping_Paralysis_Timer, DATA_ZULJINEVENT, Flame_Breath_Timer, Flame_Whirl_Timer, Grievous_Throw_Timer, health_20, instance, Intro_Timer, Lynx_Rush_Timer, ScriptedAI::me, NOT_STARTED, Overpower_Timer, Pillar_Of_Fire_Timer, ZoneScript::SetData(), Object::SetUInt32Value(), TankGUID, UNIT_VIRTUAL_ITEM_SLOT_ID, and Whirlwind_Timer.
SpawnAdds()
void boss_zuljin::boss_zuljinAI::SpawnAdds () inline
        {
            for (uint8 i = 0; i < 4; ++i)
            {
                Creature* creature = me->SummonCreature(SpiritInfo[i].entry, SpiritInfo[i].x, SpiritInfo[i].y, SpiritInfo[i].z, SpiritInfo[i].orient, TEMPSUMMON_DEAD_DESPAWN, 0);
                if (creature)
                {
                    creature->CastSpell(creature, SPELL_SPIRIT_AURA, true);
                    creature->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    creature->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                    SpiritGUID[i] = creature->GetGUID();
                }
            }
        }
References Unit::CastSpell(), Object::GetGUID(), ScriptedAI::me, Unit::RemoveUnitFlag(), Unit::SetUnitFlag(), SPELL_SPIRIT_AURA, SpiritGUID, SpiritInfo, WorldObject::SummonCreature(), TEMPSUMMON_DEAD_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by JustEngagedWith().
SummonedCreatureDespawn()
void boss_zuljin::boss_zuljinAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
        {
            Summons.Despawn(summon);
        }
UpdateAI()
void boss_zuljin::boss_zuljinAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (!TankGUID)
            {
                if (!UpdateVictim())
                    return;
                if (me->GetHealth() < health_20 * (4 - Phase))
                    EnterPhase(Phase + 1);
            }
            if (Berserk_Timer <= diff)
            {
                DoCast(me, SPELL_BERSERK, true);
                Talk(YELL_BERSERK);
                Berserk_Timer = 60000;
            }
            else Berserk_Timer -= diff;
            switch (Phase)
            {
                case 0:
                    if (Intro_Timer)
                    {
                        if (Intro_Timer <= diff)
{
                            Talk(YELL_AGGRO);
                            Intro_Timer = 0;
                        }
                        else Intro_Timer -= diff;
                    }
                    if (Whirlwind_Timer <= diff)
                    {
                        DoCast(me, SPELL_WHIRLWIND);
                        Whirlwind_Timer = urand(15000, 20000);
                    }
                    else Whirlwind_Timer -= diff;
                    if (Grievous_Throw_Timer <= diff)
                    {
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 100, true))
                            DoCast(target, SPELL_GRIEVOUS_THROW, false);
                        Grievous_Throw_Timer = 10000;
                    }
                    else Grievous_Throw_Timer -= diff;
                    break;
                case 1:
                    if (Creeping_Paralysis_Timer <= diff)
                    {
                        DoCast(me, SPELL_CREEPING_PARALYSIS);
                        Creeping_Paralysis_Timer = 20000;
                    }
                    else Creeping_Paralysis_Timer -= diff;
                    if (Overpower_Timer <= diff)
                    {
                        // implemented in DoMeleeAttackIfReady()
                        Overpower_Timer = 0;
                    }
                    else Overpower_Timer -= diff;
                    break;
                case 2:
                    return;
                case 3:
                    if (Claw_Rage_Timer <= diff)
                    {
                        if (!TankGUID)
{
                            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
{
                                TankGUID = me->GetVictim()->GetGUID();
                                me->SetSpeed(MOVE_RUN, 5.0f);
                                AttackStart(target); // change victim
                                Claw_Rage_Timer = 0;
                                Claw_Loop_Timer = 500;
                                Claw_Counter = 0;
                            }
                        }
                        else if (!Claw_Rage_Timer) // do not do this when Lynx_Rush
{
                            if (Claw_Loop_Timer <= diff)
{
                                Unit* target = me->GetVictim();
                                if (!target || !target->isTargetableForAttack()) target = ObjectAccessor::GetUnit(*me, TankGUID);
                                if (!target || !target->isTargetableForAttack()) target = SelectTarget(SelectTargetMethod::Random, 0);
                                if (target)
{
                                    AttackStart(target);
                                    if (me->IsWithinMeleeRange(target))
{
                                        DoCast(target, SPELL_CLAW_RAGE_DAMAGE, true);
                                        ++Claw_Counter;
                                        if (Claw_Counter == 12)
{
                                            Claw_Rage_Timer = urand(15000, 20000);
                                            me->SetSpeed(MOVE_RUN, 1.2f);
                                            AttackStart(ObjectAccessor::GetUnit(*me, TankGUID));
                                            TankGUID.Clear();
                                            return;
                                        }
                                        else
                                            Claw_Loop_Timer = 500;
                                    }
                                }
                                else
{
                                    EnterEvadeMode(); // if (target)
                                    return;
                                }
                            }
                            else Claw_Loop_Timer -= diff;
                        } //if (TankGUID)
                    }
                    else Claw_Rage_Timer -= diff;
                    if (Lynx_Rush_Timer <= diff)
                    {
                        if (!TankGUID)
{
                            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
{
                                TankGUID = me->GetVictim()->GetGUID();
                                me->SetSpeed(MOVE_RUN, 5.0f);
                                AttackStart(target); // change victim
                                Lynx_Rush_Timer = 0;
                                Claw_Counter = 0;
                            }
                        }
                        else if (!Lynx_Rush_Timer)
{
                            Unit* target = me->GetVictim();
                            if (!target || !target->isTargetableForAttack())
{
                                target = SelectTarget(SelectTargetMethod::Random, 0);
                                AttackStart(target);
                            }
                            if (target)
{
                                if (me->IsWithinMeleeRange(target))
{
                                    DoCast(target, SPELL_LYNX_RUSH_DAMAGE, true);
                                    ++Claw_Counter;
                                    if (Claw_Counter == 9)
{
                                        Lynx_Rush_Timer = urand(15000, 20000);
                                        me->SetSpeed(MOVE_RUN, 1.2f);
                                        AttackStart(ObjectAccessor::GetUnit(*me, TankGUID));
                                        TankGUID.Clear();
                                    }
                                    else
                                        AttackStart(SelectTarget(SelectTargetMethod::Random, 0));
                                }
                            }
                            else
{
                                EnterEvadeMode(); // if (target)
                                return;
                            }
                        } //if (TankGUID)
                    }
                    else Lynx_Rush_Timer -= diff;
                    break;
                case 4:
                    if (Flame_Whirl_Timer <= diff)
                    {
                        DoCast(me, SPELL_FLAME_WHIRL);
                        Flame_Whirl_Timer = 12000;
                    }
                    Flame_Whirl_Timer -= diff;
                    if (Pillar_Of_Fire_Timer <= diff)
                    {
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
                            DoCast(target, SPELL_SUMMON_PILLAR);
                        Pillar_Of_Fire_Timer = 10000;
                    }
                    else Pillar_Of_Fire_Timer -= diff;
                    if (Flame_Breath_Timer <= diff)
                    {
                        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0))
                            me->SetInFront(target);
                        DoCast(me, SPELL_FLAME_BREATH);
                        Flame_Breath_Timer = 10000;
                    }
                    else Flame_Breath_Timer -= diff;
                    break;
                default:
                    break;
            }
            if (!TankGUID)
                DoMeleeAttackIfReady();
        }
References AttackStart(), Berserk_Timer, Claw_Counter, Claw_Loop_Timer, Claw_Rage_Timer, ObjectGuid::Clear(), Creeping_Paralysis_Timer, UnitAI::DoCast(), DoMeleeAttackIfReady(), CreatureAI::EnterEvadeMode(), EnterPhase(), Flame_Breath_Timer, Flame_Whirl_Timer, Object::GetGUID(), Unit::GetHealth(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Grievous_Throw_Timer, health_20, Intro_Timer, Unit::isTargetableForAttack(), Unit::IsWithinMeleeRange(), Lynx_Rush_Timer, ScriptedAI::me, MOVE_RUN, Overpower_Timer, Pillar_Of_Fire_Timer, UnitAI::SelectTarget(), Unit::SetInFront(), Unit::SetSpeed(), SPELL_BERSERK, SPELL_CLAW_RAGE_DAMAGE, SPELL_CREEPING_PARALYSIS, SPELL_FLAME_BREATH, SPELL_FLAME_WHIRL, SPELL_GRIEVOUS_THROW, SPELL_LYNX_RUSH_DAMAGE, SPELL_SUMMON_PILLAR, SPELL_WHIRLWIND, TankGUID, CreatureAI::UpdateVictim(), urand(), Whirlwind_Timer, YELL_AGGRO, and YELL_BERSERK.
Member Data Documentation
Berserk_Timer
uint32 boss_zuljin::boss_zuljinAI::Berserk_Timer
Referenced by Reset(), and UpdateAI().
Claw_Counter
uint32 boss_zuljin::boss_zuljinAI::Claw_Counter
Referenced by Reset(), and UpdateAI().
Claw_Loop_Timer
uint32 boss_zuljin::boss_zuljinAI::Claw_Loop_Timer
Referenced by Reset(), and UpdateAI().
Claw_Rage_Timer
uint32 boss_zuljin::boss_zuljinAI::Claw_Rage_Timer
Referenced by Reset(), and UpdateAI().
ClawTargetGUID
ObjectGuid boss_zuljin::boss_zuljinAI::ClawTargetGUID
Referenced by Reset().
Creeping_Paralysis_Timer
uint32 boss_zuljin::boss_zuljinAI::Creeping_Paralysis_Timer
Referenced by Reset(), and UpdateAI().
Flame_Breath_Timer
uint32 boss_zuljin::boss_zuljinAI::Flame_Breath_Timer
Referenced by Reset(), and UpdateAI().
Flame_Whirl_Timer
uint32 boss_zuljin::boss_zuljinAI::Flame_Whirl_Timer
Referenced by Reset(), and UpdateAI().
Grievous_Throw_Timer
uint32 boss_zuljin::boss_zuljinAI::Grievous_Throw_Timer
Referenced by Reset(), and UpdateAI().
health_20
uint32 boss_zuljin::boss_zuljinAI::health_20
Referenced by Reset(), and UpdateAI().
instance
InstanceScript* boss_zuljin::boss_zuljinAI::instance
Referenced by boss_zuljinAI(), JustDied(), JustEngagedWith(), and Reset().
Intro_Timer
uint32 boss_zuljin::boss_zuljinAI::Intro_Timer
Referenced by KilledUnit(), Reset(), and UpdateAI().
Lynx_Rush_Timer
uint32 boss_zuljin::boss_zuljinAI::Lynx_Rush_Timer
Referenced by Reset(), and UpdateAI().
Overpower_Timer
uint32 boss_zuljin::boss_zuljinAI::Overpower_Timer
Referenced by DoMeleeAttackIfReady(), Reset(), and UpdateAI().
Phase
uint32 boss_zuljin::boss_zuljinAI::Phase
Pillar_Of_Fire_Timer
uint32 boss_zuljin::boss_zuljinAI::Pillar_Of_Fire_Timer
Referenced by Reset(), and UpdateAI().
SpiritGUID
ObjectGuid boss_zuljin::boss_zuljinAI::SpiritGUID[4]
Referenced by DespawnAdds(), EnterPhase(), JustDied(), and SpawnAdds().
Summons
SummonList boss_zuljin::boss_zuljinAI::Summons
TankGUID
ObjectGuid boss_zuljin::boss_zuljinAI::TankGUID
Referenced by Reset(), and UpdateAI().
Whirlwind_Timer
uint32 boss_zuljin::boss_zuljinAI::Whirlwind_Timer
Referenced by Reset(), and UpdateAI().