AzerothCore: instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript Struct Reference
instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript Struct Reference
Public Member Functions
instance_serpentshrine_cavern_InstanceMapScript (Map *map)
void Initialize () override
bool SetBossState (uint32 type, EncounterState state) override
void OnGameObjectCreate (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void SetData (uint32 type, uint32) override
uint32 GetData (uint32 type) const override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid _shieldGeneratorGUID [4]
int32 _aliveKeepersCount
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_serpentshrine_cavern_InstanceMapScript()
instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::instance_serpentshrine_cavern_InstanceMapScript (Map * map) inline
: InstanceScript(map) { }
Member Function Documentation
GetData()
uint32 instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == DATA_ALIVE_KEEPERS)
                return _aliveKeepersCount;
            return 0;
        }
References _aliveKeepersCount, and DATA_ALIVE_KEEPERS.
Initialize()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTERS);
            LoadDoorData(doorData);
            LoadObjectData(creatureData, gameObjectData);
            LoadMinionData(minionData);
            LoadBossBoundaries(boundaries);
            _aliveKeepersCount = 0;
        }
References _aliveKeepersCount, boundaries, creatureData, DataHeader, doorData, gameObjectData, InstanceScript::LoadBossBoundaries(), InstanceScript::LoadDoorData(), InstanceScript::LoadMinionData(), InstanceScript::LoadObjectData(), MAX_ENCOUNTERS, minionData, InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
OnCreatureCreate()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_COILFANG_SHATTERER:
                case NPC_COILFANG_PRIESTESS:
                    if (creature->GetPositionX() > 190.0f)
                        --_aliveKeepersCount;
                    break;
                case NPC_CYCLONE_KARATHRESS:
                    creature->GetMotionMaster()->MoveRandom(50.0f);
                    break;
                case NPC_ENCHANTED_ELEMENTAL:
                case NPC_COILFANG_ELITE:
                case NPC_COILFANG_STRIDER:
                case NPC_TAINTED_ELEMENTAL:
                    if (Creature* vashj = GetCreature(DATA_LADY_VASHJ))
                        vashj->AI()->JustSummoned(creature);
                    break;
                case NPC_SEER_OLUM:
                    creature->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    creature->RemoveNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
                    break;
                default:
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References _aliveKeepersCount, DATA_LADY_VASHJ, InstanceScript::GetCreature(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPositionX(), MotionMaster::MoveRandom(), NPC_COILFANG_ELITE, NPC_COILFANG_PRIESTESS, NPC_COILFANG_SHATTERER, NPC_COILFANG_STRIDER, NPC_CYCLONE_KARATHRESS, NPC_ENCHANTED_ELEMENTAL, NPC_SEER_OLUM, NPC_TAINTED_ELEMENTAL, InstanceScript::OnCreatureCreate(), Unit::RemoveNpcFlag(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAG_QUESTGIVER.
OnGameObjectCreate()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (go->GetEntry())
            {
                case GO_SHIELD_GENERATOR1:
                case GO_SHIELD_GENERATOR2:
                case GO_SHIELD_GENERATOR3:
                case GO_SHIELD_GENERATOR4:
                    _shieldGeneratorGUID[go->GetEntry() - GO_SHIELD_GENERATOR1] = go->GetGUID();
                    break;
            }
            InstanceScript::OnGameObjectCreate(go);
        }
References _shieldGeneratorGUID, Object::GetEntry(), Object::GetGUID(), GO_SHIELD_GENERATOR1, GO_SHIELD_GENERATOR2, GO_SHIELD_GENERATOR3, GO_SHIELD_GENERATOR4, and InstanceScript::OnGameObjectCreate().
SetBossState()
bool instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            if (type == DATA_LADY_VASHJ)
                for (uint8 i = 0; i < 4; ++i)
                    if (GameObject* gobject = instance->GetGameObject(_shieldGeneratorGUID[i]))
                        gobject->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
            return true;
        }
References _shieldGeneratorGUID, DATA_LADY_VASHJ, Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::instance, and InstanceScript::SetBossState().
Referenced by SetData().
SetData()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::SetData (uint32 type, uint32) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_PLATFORM_KEEPER_RESPAWNED:
                    if (_aliveKeepersCount < MAX_KEEPER_COUNT)
                    {
                        ++_aliveKeepersCount;
                    }
                    break;
                case DATA_PLATFORM_KEEPER_DIED:
                    if (_aliveKeepersCount > MIN_KEEPER_COUNT)
                    {
                        --_aliveKeepersCount;
                    }
                    break;
                case DATA_BRIDGE_ACTIVATED:
                    SetBossState(DATA_BRIDGE_EMERGED, NOT_STARTED);
                    SetBossState(DATA_BRIDGE_EMERGED, DONE);
                    break;
                case DATA_ACTIVATE_SHIELD:
                    if (Creature* vashj = GetCreature(DATA_LADY_VASHJ))
                    {
                        for (auto const& shieldGuid : _shieldGeneratorGUID)
{
                            if (GameObject* gobject = instance->GetGameObject(shieldGuid))
{
                                gobject->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                vashj->SummonTrigger(gobject->GetPositionX(), gobject->GetPositionY(), gobject->GetPositionZ(), 0.0f, 0);
                            }
                        }
                    }
                    break;
            }
        }
References _aliveKeepersCount, _shieldGeneratorGUID, DATA_ACTIVATE_SHIELD, DATA_BRIDGE_ACTIVATED, DATA_BRIDGE_EMERGED, DATA_LADY_VASHJ, DATA_PLATFORM_KEEPER_DIED, DATA_PLATFORM_KEEPER_RESPAWNED, DONE, InstanceScript::GetCreature(), Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::instance, MAX_KEEPER_COUNT, MIN_KEEPER_COUNT, NOT_STARTED, and SetBossState().
Member Data Documentation
_aliveKeepersCount
int32 instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::_aliveKeepersCount private
Referenced by GetData(), Initialize(), OnCreatureCreate(), and SetData().
_shieldGeneratorGUID
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::_shieldGeneratorGUID[4] private
Referenced by OnGameObjectCreate(), SetBossState(), and SetData().