AzerothCore: WorldPacket Class Reference
WorldPacket Class Reference
#include "WorldPacket.h"
Public Member Functions
WorldPacket ()
WorldPacket (uint16 opcode, std::size_t res=200)
WorldPacket (WorldPacket &&packet) noexcept
WorldPacket (WorldPacket &&packet, TimePoint receivedTime)
WorldPacket (WorldPacket const &right)
WorldPacket & operator= (WorldPacket const &right)
WorldPacket & operator= (WorldPacket &&right) noexcept
WorldPacket (uint16 opcode, MessageBuffer &&buffer)
void Initialize (uint16 opcode, std::size_t newres=200)
uint16 GetOpcode () const
void SetOpcode (uint16 opcode)
TimePoint GetReceivedTime () const
Public Member Functions inherited from ByteBuffer
ByteBuffer ()
ByteBuffer (std::size_t reserve)
ByteBuffer (ByteBuffer &&buf) noexcept
ByteBuffer (ByteBuffer const &right)=default
ByteBuffer (MessageBuffer &&buffer)
virtual ~ByteBuffer ()=default
ByteBuffer & operator= (ByteBuffer const &right)
ByteBuffer & operator= (ByteBuffer &&right) noexcept
void clear ()
template<typename T >
void append (T value)
template<typename T >
void put (std::size_t pos, T value)
ByteBuffer & operator<< (bool value)
ByteBuffer & operator<< (uint8 value)
ByteBuffer & operator<< (uint16 value)
ByteBuffer & operator<< (uint32 value)
ByteBuffer & operator<< (uint64 value)
ByteBuffer & operator<< (int8 value)
ByteBuffer & operator<< (int16 value)
ByteBuffer & operator<< (int32 value)
ByteBuffer & operator<< (int64 value)
ByteBuffer & operator<< (float value)
ByteBuffer & operator<< (double value)
ByteBuffer & operator<< (std::string_view value)
ByteBuffer & operator<< (std::string const &str)
ByteBuffer & operator<< (char const *str)
ByteBuffer & operator>> (bool &value)
ByteBuffer & operator>> (uint8 &value)
ByteBuffer & operator>> (uint16 &value)
ByteBuffer & operator>> (uint32 &value)
ByteBuffer & operator>> (uint64 &value)
ByteBuffer & operator>> (int8 &value)
ByteBuffer & operator>> (int16 &value)
ByteBuffer & operator>> (int32 &value)
ByteBuffer & operator>> (int64 &value)
ByteBuffer & operator>> (float &value)
ByteBuffer & operator>> (double &value)
ByteBuffer & operator>> (std::string &value)
uint8 & operator[] (std::size_t const pos)
uint8 const & operator[] (std::size_t const pos) const
std::size_t rpos () const
std::size_t rpos (std::size_t rpos_)
void rfinish ()
std::size_t wpos () const
std::size_t wpos (std::size_t wpos_)
template<typename T >
void read_skip ()
void read_skip (std::size_t skip)
template<typename T >
T read ()
template<typename T >
T read (std::size_t pos) const
void read (uint8 *dest, std::size_t len)
template<std::size_t Size>
void read (std::array< uint8, Size > &arr)
void readPackGUID (uint64 &guid)
std::string ReadCString (bool requireValidUtf8=true)
uint32 ReadPackedTime ()
ByteBuffer & ReadPackedTime (uint32 &time)
uint8 * contents ()
uint8 const * contents () const
std::size_t size () const
bool empty () const
void resize (std::size_t newsize)
void reserve (std::size_t ressize)
void shrink_to_fit ()
void append (char const *src, std::size_t cnt)
template<class T >
void append (const T *src, std::size_t cnt)
void append (uint8 const *src, std::size_t cnt)
void append (ByteBuffer const &buffer)
template<std::size_t Size>
void append (std::array< uint8, Size > const &arr)
void appendPackXYZ (float x, float y, float z)
void appendPackGUID (uint64 guid)
void AppendPackedTime (time_t time)
void put (std::size_t pos, uint8 const *src, std::size_t cnt)
void print_storage () const
void textlike () const
void hexlike () const
template<>
void read_skip ()
template<>
void read_skip ()
Protected Attributes
uint16 m_opcode {NULL_OPCODE}
TimePoint m_receivedTime
Protected Attributes inherited from ByteBuffer
std::size_t _rpos {0}
std::size_t _wpos {0}
std::vector< uint8 > _storage
Additional Inherited Members
Static Public Attributes inherited from ByteBuffer
static constexpr std::size_t DEFAULT_SIZE = 0x1000
Detailed Description
Constructor & Destructor Documentation
WorldPacket() [1/6]
WorldPacket::WorldPacket () inline
: ByteBuffer(0) { }
WorldPacket() [2/6]
WorldPacket::WorldPacket (uint16 opcode, std::size_t res = 200) inline explicit
                                                             :
        ByteBuffer(res), m_opcode(opcode) { }
WorldPacket() [3/6]
WorldPacket::WorldPacket (WorldPacket && packet) inline noexcept
                                               :
        ByteBuffer(std::move(packet)), m_opcode(packet.m_opcode) { }
WorldPacket() [4/6]
WorldPacket::WorldPacket (WorldPacket && packet, TimePoint receivedTime) inline
                                                              :
        ByteBuffer(std::move(packet)), m_opcode(packet.m_opcode), m_receivedTime(receivedTime) { }
WorldPacket() [5/6]
WorldPacket::WorldPacket (WorldPacket const & right) inline
                                          :
        ByteBuffer(right), m_opcode(right.m_opcode) { }
WorldPacket() [6/6]
WorldPacket::WorldPacket (uint16 opcode, MessageBuffer && buffer) inline
                                                       :
        ByteBuffer(std::move(buffer)), m_opcode(opcode) { }
Member Function Documentation
GetOpcode()
uint16 WorldPacket::GetOpcode () const inline
{ return m_opcode; }
References m_opcode.
Referenced by WorldSession::DosProtection::EvaluateOpcode(), WorldSession::Handle_Deprecated(), WorldSession::Handle_EarlyProccess(), WorldSession::Handle_NULL(), WorldSession::Handle_ServerSide(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleChannelDeclineInvite(), WorldSession::HandleChannelList(), WorldSession::HandleCharFactionOrRaceChange(), debug_commandscript::HandleDebugSendOpcodeCommand(), WorldSession::HandleForceSpeedChangeAck(), WorldSession::HandleMovementOpcodes(), PacketLog::LogPacket(), WorldSession::LogUnexpectedOpcode(), WorldSession::LogUnprocessedTail(), EncryptableAndCompressiblePacket::NeedsCompression(), MapSessionFilter::Process(), WorldSessionFilter::Process(), WorldSocket::ReadDataHandler(), WorldSocket::SendPacketAndLogOpcode(), WorldSocket::Update(), and WorldSession::Update().
GetReceivedTime()
TimePoint WorldPacket::GetReceivedTime () const inline
{ return m_receivedTime; }
References m_receivedTime.
Referenced by WorldSession::HandleTimeSyncResp().
Initialize()
void WorldPacket::Initialize (uint16 opcode, std::size_t newres = 200) inline
    {
        clear();
        _storage.reserve(newres);
        m_opcode = opcode;
    }
References ByteBuffer::_storage, ByteBuffer::clear(), and m_opcode.
Referenced by AddonHandler::BuildAddonPacket(), BattlegroundMgr::BuildBattlegroundListPacket(), BattlegroundMgr::BuildBattlegroundStatusPacket(), ChatHandler::BuildChatPacket(), Unit::BuildCooldownPacket(), BattlegroundMgr::BuildGroupJoinedBattlegroundPacket(), Unit::BuildHeartBeatMsg(), WorldSession::BuildPartyMemberStatsChangedPacket(), BattlegroundMgr::BuildPlayerJoinedBattlegroundPacket(), BattlegroundMgr::BuildPlayerLeftBattlegroundPacket(), Battleground::BuildPvPLogDataPacket(), ArenaSpectator::CreatePacket(), Group::Disband(), Unit::Dismount(), Player::DuelComplete(), Spell::EffectBind(), AuraEffect::HandleAuraSetVehicle(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), WorldSession::HandleReadItem(), WorldSession::HandleTurnInPetitionOpcode(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), CreatureTemplate::InitializeQueryData(), ItemTemplate::InitializeQueryData(), Quest::InitializeQueryData(), SocialMgr::MakeFriendStatusPacket(), Channel::MakeNotifyPacket(), ChannelMgr::MakeNotOnPacket(), Unit::Mount(), Acore::EmoteChatBuilder::operator()(), Group::RemoveMember(), ReputationMgr::SendForceReactions(), Player::SendInitialPacketsBeforeAddToMap(), Spell::SendInterrupted(), Player::SendSavedInstances(), WorldSession::SendTradeStatus(), Player::SetCanFly(), Creature::SetCanFly(), Creature::SetDisableGravity(), Player::SetDisableGravity(), Player::SetFeatherFall(), Creature::SetFeatherFall(), Player::SetHover(), Player::SetMovement(), Unit::SetSpeed(), Player::SetWaterWalking(), and Creature::SetWaterWalking().
operator=() [1/2]
WorldPacket & WorldPacket::operator= (WorldPacket && right) inline noexcept
    {
        if (this != &right)
        {
            m_opcode = right.m_opcode;
            ByteBuffer::operator=(std::move(right));
        }
        return *this;
    }
References m_opcode, and ByteBuffer::operator=().
operator=() [2/2]
WorldPacket & WorldPacket::operator= (WorldPacket const & right) inline
    {
        if (this != &right)
        {
            m_opcode = right.m_opcode;
            ByteBuffer::operator=(right);
        }
        return *this;
    }
References m_opcode, and ByteBuffer::operator=().
SetOpcode()
void WorldPacket::SetOpcode (uint16 opcode) inline
{ m_opcode = opcode; }
References m_opcode.
Referenced by UpdateData::BuildPacket(), EncryptableAndCompressiblePacket::CompressIfNeeded(), WorldSession::HandleClientCastFlags(), gm_commandscript::HandleGMFlyCommand(), WorldSession::HandleUpdateMissileTrajectory(), Movement::MoveSplineInit::Launch(), WorldSession::SendCalendarRaidLockout(), and Movement::MoveSplineInit::Stop().
Member Data Documentation
m_opcode
uint16 WorldPacket::m_opcode {NULL_OPCODE} protected
Referenced by GetOpcode(), Initialize(), operator=(), and SetOpcode().
m_receivedTime
TimePoint WorldPacket::m_receivedTime protected
Referenced by GetReceivedTime().