AzerothCore: go_ahune_ice_stone Class Reference
go_ahune_ice_stone Class Reference
Public Member Functions
go_ahune_ice_stone ()
bool OnGossipHello (Player *player, GameObject *go) override
bool OnGossipSelect (Player *player, GameObject *go, uint32, uint32 action) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, GameObject *)
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnModifyHealth (GameObject *, Unit *, int32 &, SpellInfo const *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
go_ahune_ice_stone()
go_ahune_ice_stone::go_ahune_ice_stone () inline
: GameObjectScript("go_ahune_ice_stone") { }
Member Function Documentation
OnGossipHello()
bool go_ahune_ice_stone::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
    {
        if (!player || !go)
            return true;
        if (!player->IsGameMaster())
        {
            if (Group const* group = player->GetGroup())
            {
                if (sLFGMgr->GetDungeon(group->GetGUID()) != lfg::LFG_DUNGEON_FROST_LORD_AHUNE)
                {
                    return true;
                }
            }
        }
        if (go->FindNearestCreature(NPC_AHUNE, 200.0f, true))
            return true;
        AddGossipItemFor(player, GOSSIP_ICON_CHAT, "Disturb the stone and summon Lord Ahune.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1337);
        SendGossipMenuFor(player, GOSSIP_TEXT_ID, go->GetGUID());
        return true;
    }
References AddGossipItemFor(), WorldObject::FindNearestCreature(), Player::GetGroup(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID, Player::IsGameMaster(), lfg::LFG_DUNGEON_FROST_LORD_AHUNE, NPC_AHUNE, SendGossipMenuFor(), and sLFGMgr.
OnGossipSelect()
bool go_ahune_ice_stone::OnGossipSelect (Player * player, GameObject * go, uint32 , uint32 action) inline override virtual
Reimplemented from GameObjectScript.
    {
        if (!player || !go)
            return true;
        if (!player->IsGameMaster())
        {
            if (Group const* group = player->GetGroup())
            {
                if (sLFGMgr->GetDungeon(group->GetGUID()) != lfg::LFG_DUNGEON_FROST_LORD_AHUNE)
                {
                    return true;
                }
            }
        }
        if (action != GOSSIP_ACTION_INFO_DEF + 1337)
            return true;
        if (go->FindNearestCreature(NPC_AHUNE, 200.0f, true))
            return true;
        if (Creature* c = go->SummonCreature(NPC_AHUNE, AhuneSummonPos, TEMPSUMMON_MANUAL_DESPAWN))
        {
            player->DestroyItemCount(ITEM_MAGMA_TOTEM, 1, true, false);
            player->AreaExploredOrEventHappens(QUEST_SUMMON_AHUNE); // auto rewarded
            c->SetVisible(false);
            c->SetDisplayId(AHUNE_DEFAULT_MODEL);
            c->SetFloatValue(UNIT_FIELD_COMBATREACH, 18.0f);
            if (c->AI())
            {
                c->AI()->SetGUID(player->GetGUID(), SET_GUID_INVOKER);
            }
            if (Creature* bunny = go->SummonCreature(NPC_AHUNE_SUMMON_LOC_BUNNY, AhuneSummonPos, TEMPSUMMON_TIMED_DESPAWN, 12000))
                if (Creature* crystal_trigger = go->SummonCreature(WORLD_TRIGGER, go->GetPositionX(), go->GetPositionY(), 5.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 12000))
                    crystal_trigger->CastSpell(bunny, SPELL_STARTING_BEAM, false);
        }
        CloseGossipMenuFor(player);
        return true;
    }
References AHUNE_DEFAULT_MODEL, AhuneSummonPos, Player::AreaExploredOrEventHappens(), CloseGossipMenuFor(), Player::DestroyItemCount(), WorldObject::FindNearestCreature(), Player::GetGroup(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), GOSSIP_ACTION_INFO_DEF, Player::IsGameMaster(), ITEM_MAGMA_TOTEM, lfg::LFG_DUNGEON_FROST_LORD_AHUNE, NPC_AHUNE, NPC_AHUNE_SUMMON_LOC_BUNNY, QUEST_SUMMON_AHUNE, SET_GUID_INVOKER, sLFGMgr, SPELL_STARTING_BEAM, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_COMBATREACH, and WORLD_TRIGGER.