AzerothCore: boss_majordomo::boss_majordomoAI Struct Reference
boss_majordomo::boss_majordomoAI Struct Reference
Public Member Functions
boss_majordomoAI (Creature *creature)
void JustDied (Unit *) override
void JustSummoned (Creature *summon) override
void InitializeAI () override
void Reset () override
bool CanAIAttack (Unit const *) const override
void KilledUnit (Unit *victim) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void SummonedCreatureDies (Creature *summon, Unit *) override
void JustReachedHome () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MovementInform (uint32 type, uint32 pointId) override
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void DoAction (int32 action) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
GuidSet static_minionsGUIDS
GuidSet aliveMinionsGUIDS
std::unordered_map< uint32, MajordomoAddData > majordomoSummonsData
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_majordomoAI()
boss_majordomo::boss_majordomoAI::boss_majordomoAI (Creature * creature) inline
: BossAI(creature, DATA_MAJORDOMO_EXECUTUS) {}
Member Function Documentation
CanAIAttack()
bool boss_majordomo::boss_majordomoAI::CanAIAttack (Unit const *) const inline override virtual
Reimplemented from UnitAI.
        {
            return instance->GetBossState(DATA_MAJORDOMO_EXECUTUS) != DONE;
        }
References DATA_MAJORDOMO_EXECUTUS, DONE, InstanceScript::GetBossState(), and BossAI::instance.
DamageTaken()
void boss_majordomo::boss_majordomoAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from BossAI.
        {
            if (events.IsInPhase(PHASE_COMBAT) && me->GetHealth() <= damage)
            {
                damage = 0;
            }
        }
References Unit::GetHealth(), ScriptedAI::me, and PHASE_COMBAT.
DoAction()
void boss_majordomo::boss_majordomoAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == ACTION_START_RAGNAROS_INTRO && !events.IsInPhase(PHASE_RAGNAROS_SUMMONING))
            {
                events.SetPhase(PHASE_RAGNAROS_SUMMONING);
                events.ScheduleEvent(EVENT_RAGNAROS_SUMMON_1, 5s, PHASE_RAGNAROS_SUMMONING, PHASE_RAGNAROS_SUMMONING);
            }
        }
References ACTION_START_RAGNAROS_INTRO, EVENT_RAGNAROS_SUMMON_1, and PHASE_RAGNAROS_SUMMONING.
InitializeAI()
void boss_majordomo::boss_majordomoAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
        {
            BossAI::InitializeAI();
            if (instance->GetBossState(DATA_MAJORDOMO_EXECUTUS) != DONE)
            {
                events.SetPhase(PHASE_COMBAT);
                std::list<TempSummon*> p_summons;
                me->SummonCreatureGroup(SUMMON_GROUP_ADDS, &p_summons);
                if (!p_summons.empty())
                {
                    for (TempSummon const* summon : p_summons)
                    {
                        if (summon)
{
                            static_minionsGUIDS.insert(summon->GetGUID());
                            majordomoSummonsData[summon->GetGUID().GetCounter()] = MajordomoAddData(summon->GetGUID(), summon->GetEntry(), summon->GetPosition());
                        }
                    }
                }
            }
            else
            {
                events.SetPhase(PHASE_NONE);
                me->SetImmuneToAll(true);
                me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                me->SetFaction(FACTION_MAJORDOMO_FRIENDLY);
            }
        }
References DATA_MAJORDOMO_EXECUTUS, DONE, FACTION_MAJORDOMO_FRIENDLY, InstanceScript::GetBossState(), UnitAI::InitializeAI(), BossAI::instance, majordomoSummonsData, ScriptedAI::me, PHASE_COMBAT, PHASE_NONE, Unit::SetFaction(), Unit::SetImmuneToAll(), Unit::SetNpcFlag(), static_minionsGUIDS, SUMMON_GROUP_ADDS, WorldObject::SummonCreatureGroup(), and UNIT_NPC_FLAG_GOSSIP.
JustDied()
void boss_majordomo::boss_majordomoAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
        {
            Talk(SAY_DEATH);
            me->DespawnOrUnsummon(10s, 0s);
        }
References Creature::DespawnOrUnsummon(), ScriptedAI::me, and SAY_DEATH.
JustEngagedWith()
void boss_majordomo::boss_majordomoAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from BossAI.
        {
            if (!events.IsInPhase(PHASE_COMBAT))
            {
                return;
            }
            _JustEngagedWith();
            DoCastAOE(SPELL_SEPARATION_ANXIETY);
            Talk(SAY_AGGRO);
            DoCastSelf(SPELL_AEGIS_OF_RAGNAROS, true);
            events.ScheduleEvent(EVENT_SHIELD_REFLECTION, 30s, PHASE_COMBAT, PHASE_COMBAT);
            events.ScheduleEvent(EVENT_TELEPORT_RANDOM, 25s, PHASE_COMBAT, PHASE_COMBAT);
            events.ScheduleEvent(EVENT_TELEPORT_TARGET, 15s, PHASE_COMBAT, PHASE_COMBAT);
            aliveMinionsGUIDS.clear();
            aliveMinionsGUIDS = static_minionsGUIDS;
        }
References BossAI::_JustEngagedWith(), aliveMinionsGUIDS, UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), EVENT_SHIELD_REFLECTION, EVENT_TELEPORT_RANDOM, EVENT_TELEPORT_TARGET, PHASE_COMBAT, SAY_AGGRO, SPELL_AEGIS_OF_RAGNAROS, SPELL_SEPARATION_ANXIETY, and static_minionsGUIDS.
JustReachedHome()
void boss_majordomo::boss_majordomoAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
        {
            _JustReachedHome();
            if (instance->GetBossState(DATA_MAJORDOMO_EXECUTUS) == DONE)
            {
                events.Reset();
                events.SetPhase(PHASE_DEFEAT_OUTRO);
                events.ScheduleEvent(EVENT_DEFEAT_OUTRO_1, 7500ms, PHASE_DEFEAT_OUTRO, PHASE_DEFEAT_OUTRO);
            }
        }
References BossAI::_JustReachedHome(), DATA_MAJORDOMO_EXECUTUS, DONE, EVENT_DEFEAT_OUTRO_1, InstanceScript::GetBossState(), BossAI::instance, and PHASE_DEFEAT_OUTRO.
JustSummoned()
void boss_majordomo::boss_majordomoAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
        {
            if (summon->GetEntry() == NPC_RAGNAROS)
            {
                summon->CastSpell(summon, SPELL_RAGNAROS_FADE);
                summon->CastSpell(summon, SPELL_RAGNAROS_SUBMERGE_EFFECT, true);
                summon->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                summon->SetImmuneToAll(true);
                summon->SetReactState(REACT_PASSIVE);
            }
        }
References Unit::CastSpell(), Object::GetEntry(), NPC_RAGNAROS, REACT_PASSIVE, Unit::SetImmuneToAll(), Creature::SetReactState(), Unit::SetUnitFlag(), SPELL_RAGNAROS_FADE, SPELL_RAGNAROS_SUBMERGE_EFFECT, and UNIT_FLAG_NON_ATTACKABLE.
KilledUnit()
void boss_majordomo::boss_majordomoAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (roll_chance_i(25) && victim->IsPlayer())
            {
                Talk(SAY_SLAY);
            }
        }
References Object::IsPlayer(), roll_chance_i(), and SAY_SLAY.
MovementInform()
void boss_majordomo::boss_majordomoAI::MovementInform (uint32 type, uint32 pointId) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (type == POINT_MOTION_TYPE && pointId == POINT_RAGNAROS_SUMMON)
            {
                DoCastAOE(SPELL_SUMMON_RAGNAROS);
                events.ScheduleEvent(EVENT_RAGNAROS_SUMMON_2, 11500ms, PHASE_RAGNAROS_SUMMONING, PHASE_RAGNAROS_SUMMONING);
            }
        }
References UnitAI::DoCastAOE(), EVENT_RAGNAROS_SUMMON_2, PHASE_RAGNAROS_SUMMONING, POINT_MOTION_TYPE, POINT_RAGNAROS_SUMMON, and SPELL_SUMMON_RAGNAROS.
Reset()
void boss_majordomo::boss_majordomoAI::Reset () inline override virtual
Reimplemented from BossAI.
        {
            me->ResetLootMode();
            events.Reset();
            aliveMinionsGUIDS.clear();
            if (instance->GetBossState(DATA_MAJORDOMO_EXECUTUS) != DONE)
            {
                events.SetPhase(PHASE_COMBAT);
                instance->SetBossState(DATA_MAJORDOMO_EXECUTUS, NOT_STARTED);
                for (auto const& summon : majordomoSummonsData)
                {
                    if (ObjectAccessor::GetCreature(*me, summon.second.guid))
                    {
                        continue;
                    }
                    if (Creature* spawn = me->SummonCreature(summon.second.creatureEntry, summon.second.spawnPos))
                    {
                        static_minionsGUIDS.erase(summon.second.guid); // Erase the guid from the previous, no longer existing, spawn.
                        static_minionsGUIDS.insert(spawn->GetGUID());
                        majordomoSummonsData.erase(summon.second.guid.GetCounter());
                        majordomoSummonsData[spawn->GetGUID().GetCounter()] = MajordomoAddData(spawn->GetGUID(), spawn->GetEntry(), spawn->GetPosition());
                    }
                }
                me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            }
            else
            {
                static_minionsGUIDS.clear();
                majordomoSummonsData.clear();
                summons.DespawnAll();
            }
        }
References aliveMinionsGUIDS, DATA_MAJORDOMO_EXECUTUS, SummonList::DespawnAll(), DONE, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), BossAI::instance, majordomoSummonsData, ScriptedAI::me, NOT_STARTED, PHASE_COMBAT, Unit::RemoveNpcFlag(), Creature::ResetLootMode(), InstanceScript::SetBossState(), static_minionsGUIDS, WorldObject::SummonCreature(), BossAI::summons, and UNIT_NPC_FLAG_GOSSIP.
SpellHit()
void boss_majordomo::boss_majordomoAI::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (events.IsInPhase(PHASE_DEFEAT_OUTRO) && spellInfo->Id == SPELL_TELEPORT_SELF)
            {
                me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                me->SetHomePosition(MajordomoRagnaros);
                me->NearTeleportTo(MajordomoRagnaros.GetPositionX(), MajordomoRagnaros.GetPositionY(), MajordomoRagnaros.GetPositionZ(), MajordomoRagnaros.GetOrientation());
                events.SetPhase(PHASE_NONE);
            }
        }
References Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), SpellInfo::Id, MajordomoRagnaros, ScriptedAI::me, Unit::NearTeleportTo(), PHASE_DEFEAT_OUTRO, PHASE_NONE, Creature::SetHomePosition(), Unit::SetNpcFlag(), SPELL_TELEPORT_SELF, and UNIT_NPC_FLAG_GOSSIP.
SummonedCreatureDies()
void boss_majordomo::boss_majordomoAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            aliveMinionsGUIDS.erase(summon->GetGUID());
            if (summon->GetEntry() == NPC_FLAMEWAKER_HEALER || summon->GetEntry() == NPC_FLAMEWAKER_ELITE)
            {
                uint32 const remainingAdds = std::count_if(aliveMinionsGUIDS.begin(), aliveMinionsGUIDS.end(), [](ObjectGuid const& summonGuid)
                {
                    return summonGuid.GetEntry() == NPC_FLAMEWAKER_HEALER || summonGuid.GetEntry() == NPC_FLAMEWAKER_ELITE;
                });
                // Last remaining add
                if (remainingAdds == 1)
                {
                    Talk(SAY_LAST_ADD);
                    DoCastAOE(SPELL_CHAMPION);
                }
                // 50% of adds
                else if (remainingAdds == 4)
                {
                    DoCastAOE(SPELL_IMMUNE_POLY);
                }
                else if (!remainingAdds)
                {
                    static_minionsGUIDS.clear();
                    instance->SetBossState(DATA_MAJORDOMO_EXECUTUS, DONE);
                    events.CancelEventGroup(PHASE_COMBAT);
                    me->GetMap()->UpdateEncounterState(ENCOUNTER_CREDIT_KILL_CREATURE, me->GetEntry(), me);
                    me->SetImmuneToAll(true);
                    me->SetFaction(FACTION_MAJORDOMO_FRIENDLY);
                    EnterEvadeMode();
                    Talk(SAY_DEFEAT);
                    return;
                }
                DoCastAOE(SPELL_ENCOURAGEMENT);
            }
        }
References aliveMinionsGUIDS, DATA_MAJORDOMO_EXECUTUS, UnitAI::DoCastAOE(), DONE, ENCOUNTER_CREDIT_KILL_CREATURE, BossAI::EnterEvadeMode(), FACTION_MAJORDOMO_FRIENDLY, Object::GetEntry(), Object::GetGUID(), WorldObject::GetMap(), BossAI::instance, ScriptedAI::me, NPC_FLAMEWAKER_ELITE, NPC_FLAMEWAKER_HEALER, PHASE_COMBAT, SAY_DEFEAT, SAY_LAST_ADD, InstanceScript::SetBossState(), Unit::SetFaction(), Unit::SetImmuneToAll(), SPELL_CHAMPION, SPELL_ENCOURAGEMENT, SPELL_IMMUNE_POLY, static_minionsGUIDS, and Map::UpdateEncounterState().
UpdateAI()
void boss_majordomo::boss_majordomoAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from BossAI.
        {
            switch (events.GetPhaseMask())
            {
                case  (1 << (PHASE_COMBAT - 1)):
                {
                    if (!UpdateVictim())
                    {
                        return;
                    }
                    events.Update(diff);
                    if (me->HasUnitState(UNIT_STATE_CASTING))
                    {
                        return;
                    }
                    while (uint32 const eventId = events.ExecuteEvent())
                    {
                        switch (eventId)
{
                            case EVENT_SHIELD_REFLECTION:
{
                                if (rand_chance() <= 50.f)
{
                                    DoCastSelf(SPELL_MAGIC_REFLECTION);
                                }
                                else
{
                                    DoCastSelf(SPELL_DAMAGE_REFLECTION);
                                }
                                events.RepeatEvent(30000);
                                break;
                            }
                            case EVENT_TELEPORT_RANDOM:
{
                                if (Unit* target = SelectTarget(SelectTargetMethod::Random, 1, 0.0f, true))
{
                                    DoCastSelf(SPELL_HATE_TO_ZERO, true);
                                    DoCast(target, SPELL_TELEPORT_RANDOM);
                                }
                                events.RepeatEvent(30000);
                                break;
                            }
                            case EVENT_TELEPORT_TARGET:
{
                                DoCastSelf(SPELL_HATE_TO_ZERO, true);
                                DoCastAOE(SPELL_TELEPORT_TARGET);
                                events.RepeatEvent(30000);
                                break;
                            }
                        }
                        if (me->HasUnitState(UNIT_STATE_CASTING))
{
                            return;
                        }
                    }
                    DoMeleeAttackIfReady();
                    break;
                }
                case (1 << (PHASE_DEFEAT_OUTRO - 1)):
                {
                    events.Update(diff);
                    while (uint32 const eventId = events.ExecuteEvent())
                    {
                        switch (eventId)
{
                            case EVENT_DEFEAT_OUTRO_1:
{
                                Talk(SAY_DEFEAT_2);
                                events.ScheduleEvent(EVENT_DEFEAT_OUTRO_2, 8s, PHASE_DEFEAT_OUTRO, PHASE_DEFEAT_OUTRO);
                                break;
                            }
                            case EVENT_DEFEAT_OUTRO_2:
{
                                Talk(SAY_DEFEAT_3);
                                events.ScheduleEvent(EVENT_DEFEAT_OUTRO_3, 21500ms, PHASE_DEFEAT_OUTRO, PHASE_DEFEAT_OUTRO);
                                break;
                            }
                            case EVENT_DEFEAT_OUTRO_3:
{
                                DoCastSelf(SPELL_TELEPORT_SELF);
                                break;
                            }
                        }
                    }
                    break;
                }
                case (1 << (PHASE_RAGNAROS_SUMMONING - 1)):
                {
                    events.Update(diff);
                    while (uint32 const eventId = events.ExecuteEvent())
                    {
                        switch (eventId)
{
                            case EVENT_RAGNAROS_SUMMON_1:
{
                                if (GameObject* lavaSplash = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(DATA_LAVA_SPLASH)))
{
                                    lavaSplash->SetRespawnTime(900);
                                    lavaSplash->Refresh();
                                }
                                if (GameObject* lavaSteam = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(DATA_LAVA_STEAM)))
{
                                    lavaSteam->SetRespawnTime(900);
                                    lavaSteam->Refresh();
                                }
                                Talk(SAY_RAG_SUM_2);
                                // Next event will get triggered in MovementInform
                                me->SetWalk(true);
                                me->GetMotionMaster()->MovePoint(POINT_RAGNAROS_SUMMON, MajordomoMoveRagPos, true, false);
                                break;
                            }
                            case EVENT_RAGNAROS_SUMMON_2:
{
                                if (GameObject* lavaSteam = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(DATA_LAVA_STEAM)))
{
                                    me->SetFacingToObject(lavaSteam);
                                }
                                Talk(SAY_SUMMON_MAJ);
                                events.ScheduleEvent(EVENT_RAGNAROS_SUMMON_3, 16700ms, PHASE_RAGNAROS_SUMMONING, PHASE_RAGNAROS_SUMMONING);
                                events.ScheduleEvent(EVENT_RAGNAROS_EMERGE, 15s, PHASE_RAGNAROS_SUMMONING, PHASE_RAGNAROS_SUMMONING);
                                break;
                            }
                            case EVENT_RAGNAROS_SUMMON_3:
{
                                if (Creature* ragnaros = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_RAGNAROS)))
{
                                    ragnaros->AI()->Talk(SAY_ARRIVAL1_RAG);
                                }
                                events.ScheduleEvent(EVENT_RAGNAROS_SUMMON_4, 11700ms, PHASE_RAGNAROS_SUMMONING, PHASE_RAGNAROS_SUMMONING);
                                break;
                            }
                            case EVENT_RAGNAROS_SUMMON_4:
{
                                Talk(SAY_ARRIVAL2_MAJ);
                                events.ScheduleEvent(EVENT_RAGNAROS_SUMMON_5, 8700ms, PHASE_RAGNAROS_SUMMONING, PHASE_RAGNAROS_SUMMONING);
                                break;
                            }
                            case EVENT_RAGNAROS_SUMMON_5:
{
                                if (Creature* ragnaros = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_RAGNAROS)))
{
                                    ragnaros->AI()->Talk(SAY_ARRIVAL3_RAG);
                                }
                                events.ScheduleEvent(EVENT_RAGNAROS_SUMMON_6, 16500ms, PHASE_RAGNAROS_SUMMONING, PHASE_RAGNAROS_SUMMONING);
                                break;
                            }
                            case EVENT_RAGNAROS_SUMMON_6:
{
                                if (Creature* ragnaros = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_RAGNAROS)))
{
                                    ragnaros->CastSpell(me, SPELL_ELEMENTAL_FIRE, true);
                                    ragnaros->AI()->DoAction(ACTION_FINISH_RAGNAROS_INTRO);
                                }
                                break;
                            }
                            // Additional events
                            case EVENT_RAGNAROS_EMERGE:
{
                                if (Creature* ragnaros = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_RAGNAROS)))
{
                                    ragnaros->RemoveAurasDueToSpell(SPELL_RAGNAROS_FADE);
                                    ragnaros->CastSpell(ragnaros, SPELL_RAGNA_EMERGE);
                                }
                            }break;
                        }
                    }
                    break;
                }
            }
        }
References ACTION_FINISH_RAGNAROS_INTRO, DATA_LAVA_SPLASH, DATA_LAVA_STEAM, DATA_RAGNAROS, UnitAI::DoCast(), UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), UnitAI::DoMeleeAttackIfReady(), EVENT_DEFEAT_OUTRO_1, EVENT_DEFEAT_OUTRO_2, EVENT_DEFEAT_OUTRO_3, EVENT_RAGNAROS_EMERGE, EVENT_RAGNAROS_SUMMON_1, EVENT_RAGNAROS_SUMMON_2, EVENT_RAGNAROS_SUMMON_3, EVENT_RAGNAROS_SUMMON_4, EVENT_RAGNAROS_SUMMON_5, EVENT_RAGNAROS_SUMMON_6, EVENT_SHIELD_REFLECTION, EVENT_TELEPORT_RANDOM, EVENT_TELEPORT_TARGET, ObjectAccessor::GetCreature(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Unit::HasUnitState(), BossAI::instance, MajordomoMoveRagPos, ScriptedAI::me, MotionMaster::MovePoint(), PHASE_COMBAT, PHASE_DEFEAT_OUTRO, PHASE_RAGNAROS_SUMMONING, POINT_RAGNAROS_SUMMON, rand_chance(), SAY_ARRIVAL1_RAG, SAY_ARRIVAL2_MAJ, SAY_ARRIVAL3_RAG, SAY_DEFEAT_2, SAY_DEFEAT_3, SAY_RAG_SUM_2, SAY_SUMMON_MAJ, UnitAI::SelectTarget(), Unit::SetFacingToObject(), Creature::SetWalk(), SPELL_DAMAGE_REFLECTION, SPELL_ELEMENTAL_FIRE, SPELL_HATE_TO_ZERO, SPELL_MAGIC_REFLECTION, SPELL_RAGNA_EMERGE, SPELL_RAGNAROS_FADE, SPELL_TELEPORT_RANDOM, SPELL_TELEPORT_SELF, SPELL_TELEPORT_TARGET, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
aliveMinionsGUIDS
GuidSet boss_majordomo::boss_majordomoAI::aliveMinionsGUIDS private
Referenced by JustEngagedWith(), Reset(), and SummonedCreatureDies().
majordomoSummonsData
std::unordered_map<uint32, MajordomoAddData> boss_majordomo::boss_majordomoAI::majordomoSummonsData private
Referenced by InitializeAI(), and Reset().
static_minionsGUIDS
GuidSet boss_majordomo::boss_majordomoAI::static_minionsGUIDS private
Referenced by InitializeAI(), JustEngagedWith(), Reset(), and SummonedCreatureDies().