AzerothCore: _SpellScript Class Reference
_SpellScript Class Reference abstract
#include "SpellScript.h"
Classes
class EffectAuraNameCheck
class EffectHook
class EffectNameCheck
Public Member Functions
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Protected Member Functions
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Static Private Member Functions
template<typename Iterator >
static bool _ValidateSpellInfo (Iterator begin, Iterator end)
static bool _ValidateSpellInfo (uint32 spellId)
Detailed Description
Constructor & Destructor Documentation
_SpellScript()
_SpellScript::_SpellScript () inline
: m_currentScriptState(SPELL_SCRIPT_STATE_NONE), m_scriptName(nullptr), m_scriptSpellId(0) {}
~_SpellScript()
virtual _SpellScript::~_SpellScript () inline virtual
{}
Member Function Documentation
_GetScriptName()
std::string const * _SpellScript::_GetScriptName () const
{
    return m_scriptName;
}
References m_scriptName.
_Init()
void _SpellScript::_Init (std::string const * scriptname, uint32 spellId) virtual
{
    m_currentScriptState = SPELL_SCRIPT_STATE_NONE;
    m_scriptName = scriptname;
    m_scriptSpellId = spellId;
}
References m_currentScriptState, m_scriptName, m_scriptSpellId, and SPELL_SCRIPT_STATE_NONE.
Referenced by ScriptMgr::CreateAuraScripts(), ScriptMgr::CreateSpellScripts(), and ObjectMgr::ValidateSpellScripts().
_Register()
void _SpellScript::_Register () virtual
{
    m_currentScriptState = SPELL_SCRIPT_STATE_REGISTRATION;
    Register();
    m_currentScriptState = SPELL_SCRIPT_STATE_NONE;
}
References m_currentScriptState, Register(), SPELL_SCRIPT_STATE_NONE, and SPELL_SCRIPT_STATE_REGISTRATION.
Referenced by ObjectMgr::ValidateSpellScripts().
_Unload()
void _SpellScript::_Unload () virtual
{
    m_currentScriptState = SPELL_SCRIPT_STATE_UNLOADING;
    Unload();
    m_currentScriptState = SPELL_SCRIPT_STATE_NONE;
}
References m_currentScriptState, SPELL_SCRIPT_STATE_NONE, SPELL_SCRIPT_STATE_UNLOADING, and Unload().
_Validate()
bool _SpellScript::_Validate (SpellInfo const * entry) protected virtual
Reimplemented in SpellScript, and AuraScript.
{
    if (!Validate(entry))
    {
        LOG_ERROR("scripts.spells", "_SpellScript::_Validate: Spell `{}` did not pass Validate() function of script `{}` - script will not be added to the spell", entry->Id, m_scriptName->c_str());
        return false;
    }
    return true;
}
References SpellInfo::Id, LOG_ERROR, m_scriptName, and Validate().
Referenced by SpellScript::_Validate(), and AuraScript::_Validate().
_ValidateSpellInfo() [1/2]
template<typename Iterator > static bool _SpellScript::_ValidateSpellInfo (Iterator begin, Iterator end) inline static private
    {
        bool allValid = true;
        while (begin != end)
        {
            if (!_ValidateSpellInfo(*begin))
            {
                allValid = false;
            }
            ++begin;
        }
        return allValid;
    }
References _ValidateSpellInfo().
Referenced by _ValidateSpellInfo(), and ValidateSpellInfo().
_ValidateSpellInfo() [2/2]
bool _SpellScript::_ValidateSpellInfo (uint32 spellId) static private
{
    if (!sSpellMgr->GetSpellInfo(spellId))
    {
        LOG_ERROR("scripts.spells", "_SpellScript::ValidateSpellInfo: Spell {} does not exist.", spellId);
        return false;
    }
    return true;
}
References LOG_ERROR, and sSpellMgr.
Load()
virtual bool _SpellScript::Load () inline virtual
Reimplemented in spell_hate_to_zero::spell_hate_to_zero_SpellScript, spell_mc_play_dead::spell_mc_play_dead_AuraScript, spell_malchezaar_enfeeble, spell_shadowfang_keep_forsaken_skills::spell_shadowfang_keep_forsaken_skills_AuraScript, spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript, spell_uldaman_stoned::spell_uldaman_stoned_AuraScript, spell_brewfest_main_ram_buff, spell_hallows_end_bucket_lands, spell_midsummer_fling_torch, spell_black_morass_corrupt_medivh, spell_ayamiss_swarmer_swarm, spell_ayamiss_swarmer_start_loop, spell_gen_ayamiss_swarmer_loop, spell_herald_volzaj_insanity, spell_volazj_whisper, spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript, spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript, spell_wailing_souls_periodic::spell_wailing_souls_periodic_AuraScript, spell_shield_of_bones::spell_shield_of_bones_AuraScript, spell_taldaram_summon_flame_ball::spell_taldaram_summon_flame_ball_SpellScript, spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript, spell_deathbringer_blood_power::spell_deathbringer_blood_power_AuraScript, spell_deathbringer_blood_nova_targeting::spell_deathbringer_blood_nova_targeting_SpellScript, spell_deathbringer_boiling_blood::spell_deathbringer_boiling_blood_SpellScript, spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript, spell_igb_rocket_pack_useable::spell_igb_rocket_pack_useable_AuraScript, spell_igb_check_for_players::spell_igb_check_for_players_SpellScript, spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript, spell_igb_explosion_main::spell_igb_explosion_main_AuraScript, spell_igb_teleport_players_on_victory::spell_igb_teleport_players_on_victory_SpellScript, spell_igb_overheat::spell_igb_overheat_AuraScript, spell_igb_cannon_blast::spell_igb_cannon_blast_SpellScript, spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript, spell_marrowgar_bone_slice::spell_marrowgar_bone_slice_SpellScript, spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript, spell_rotface_mutated_infection::spell_rotface_mutated_infection_SpellScript, spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript, spell_the_lich_king_quake::spell_the_lich_king_quake_SpellScript, spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript, spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript, spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript, spell_the_lich_king_vile_spirits::spell_the_lich_king_vile_spirits_AuraScript, spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript, spell_the_lich_king_harvest_soul::spell_the_lich_king_harvest_soul_AuraScript, spell_the_lich_king_restore_soul::spell_the_lich_king_restore_soul_SpellScript, spell_dreamwalker_nightmare_cloud::spell_dreamwalker_nightmare_cloud_AuraScript, spell_dreamwalker_decay_periodic_timer::spell_dreamwalker_decay_periodic_timer_AuraScript, spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript, spell_dreamwalker_summon_suppresser_effect::spell_dreamwalker_summon_suppresser_effect_SpellScript, spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript, spell_eoe_ph3_surge_of_power::spell_eoe_ph3_surge_of_power_SpellScript, spell_boss_magus_telestra_summon_telestra_clones::spell_boss_magus_telestra_summon_telestra_clones_AuraScript, spell_algalon_big_bang::spell_algalon_big_bang_SpellScript, spell_shield_generator::spell_shield_generator_AuraScript, spell_ulduar_stone_grip_cast_target::spell_ulduar_stone_grip_cast_target_SpellScript, spell_mimiron_p3wx2_laser_barrage::spell_mimiron_p3wx2_laser_barrage_AuraScript, spell_shredder_delivery::spell_shredder_delivery_SpellScript, spell_close_rift::spell_close_rift_AuraScript, spell_wintergrasp_rp_gg::spell_wintergrasp_rp_gg_SpellScript, spell_illidan_demon_transform1::spell_illidan_demon_transform1_AuraScript, spell_illidan_demon_transform2::spell_illidan_demon_transform2_AuraScript, spell_illidan_cage_trap::spell_illidan_cage_trap_SpellScript, spell_teron_gorefiend_shadowy_construct, spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript, spell_morogrim_tidewalker_watery_grave, spell_botanica_shift_form::spell_botanica_shift_form_AuraScript, spell_kaelthas_kael_phase_two::spell_kaelthas_kael_phase_two_SpellScript, spell_kaelthas_flame_strike::spell_kaelthas_flame_strike_AuraScript, spell_kaelthas_gravity_lapse::spell_kaelthas_gravity_lapse_SpellScript, spell_dk_anti_magic_shell_raid, spell_dk_anti_magic_shell_self, spell_dk_anti_magic_zone, spell_dk_blood_boil, spell_dk_blood_gorged, spell_dk_corpse_explosion, spell_dk_icebound_fortitude, spell_dk_raise_dead, spell_dk_scourge_strike, spell_dk_spell_deflection, spell_dk_will_of_the_necropolis, spell_dru_moonkin_form_passive, spell_dru_primal_tenacity, spell_dru_rip, spell_dru_savage_defense, spell_dru_swift_flight_passive, spell_dru_t10_restoration_4p_bonus, spell_the_flag_of_ownership, spell_gen_absorb0_hitlimit1, spell_gen_pet_summoned, spell_pvp_trinket_wotf_shared_cd, spell_gen_divine_storm_cd_reset, spell_gen_profession_research, spell_gen_clone_weapon_aura, spell_gen_seaforium_blast, spell_gen_turkey_marker, spell_gen_vehicle_scaling_aura, spell_gen_oracle_wolvar_reputation, spell_gen_spirit_healer_res, spell_gen_on_tournament_mount, spell_gen_tournament_pennant, spell_gen_despawn_self, spell_gen_replenishment_aura, spell_hun_aspect_of_the_beast, spell_hun_readiness, spell_hun_scatter_shot, spell_hun_pet_heart_of_the_phoenix, spell_hun_pet_carrion_feeder, spell_hun_target_self_and_pet, spell_item_feast, spell_item_deviate_fish, spell_item_make_a_wish, spell_item_noggenfogger_elixir, spell_item_savory_deviate_delight, spell_item_scroll_of_recall, spell_item_dimensional_ripper_area52, spell_item_underbelly_elixir, spell_item_book_of_glyph_mastery, spell_item_ashbringer, spell_item_purify_helboar_meat, spell_item_socrethars_stone, spell_item_demon_broiled_surprise, spell_item_nitro_boots, spell_item_teach_language, spell_item_rocket_boots, spell_item_healing_injector, spell_item_mana_injector, spell_item_chicken_cover, spell_item_worn_troll_dice, spell_mage_arcane_blast, spell_mage_cold_snap, spell_mage_focus_magic, spell_pal_ardent_defender, spell_pal_divine_sacrifice, spell_pal_divine_storm, spell_pal_hand_of_sacrifice_aura, spell_pal_lay_on_hands, spell_pri_guardian_spirit, spell_pri_lightwell, spell_pri_mana_leech, spell_pri_penance, spell_pri_renew, spell_q10714_on_spirits_wings, spell_q13086_last_line_of_defence, spell_quest_dragonmaw_race_generic, spell_q5206_test_fetid_skull, spell_q6124_6129_apply_salve, spell_q11730_ultrasonic_screwdriver, spell_q12937_relief_for_the_fallen, spell_q12659_ahunaes_knife, spell_q9874_liquid_fire, spell_q12805_lifeblood_dummy, spell_q9452_cast_net, spell_q13011_bear_flank_master, spell_q12690_burst_at_the_seams, spell_rog_blade_flurry, spell_rog_cheat_death, spell_rog_deadly_poison, spell_rog_nerves_of_steel, spell_rog_preparation, spell_rog_rupture, spell_rog_shiv, spell_rog_tricks_of_the_trade, spell_sha_astral_shift, spell_sha_chain_heal, spell_warl_improved_demonic_tactics, spell_warl_life_tap, spell_warl_curse_of_doom, spell_warr_sweeping_strikes, and spell_warr_vigilance.
{ return true; }
Referenced by AuraScript::_Load(), and SpellScript::_Load().
Register()
virtual void _SpellScript::Register () pure virtual
Implemented in spell_transitus_shield_beam::spell_transitus_shield_beam_AuraScript, spell_mage_fingers_of_frost_proc_aura, spell_mage_fingers_of_frost_proc, spell_gyth_chromatic_protection, spell_blackrock_spire_call_of_vaelastrasz, spell_suppression_aura, spell_gen_elemental_shield, spell_gen_brood_power, spell_class_call_handler, aura_class_call_wild_magic, aura_class_call_siphon_blessing, spell_class_call_polymorph, spell_corrupted_totems, spell_shadowblink, spell_spawn_drakonid, spell_egg_event::spell_egg_eventSpellScript, spell_vael_burning_adrenaline, spell_bwl_shadowflame::spell_bwl_shadowflame_SpellScript, spell_geddon_inferno::spell_geddon_inferno_AuraScript, spell_geddon_armageddon::spell_geddon_armageddon_AuraScript, spell_garr_separation_nexiety::spell_garr_separation_nexiety_AuraScript, spell_garr_frenzy::spell_garr_frenzy_SpellScript, spell_magmadar_lava_bomb::spell_magmadar_lava_bomb_SpellScript, spell_hate_to_zero::spell_hate_to_zero_SpellScript, spell_majordomo_separation_nexiety::spell_majordomo_separation_nexiety_AuraScript, spell_summon_ragnaros::spell_summon_ragnaros_SpellScript, spell_ragnaros_lava_burst_randomizer, spell_ragnaros_summon_sons_of_flame, spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript, spell_mc_play_dead::spell_mc_play_dead_AuraScript, spell_gnomeregan_radiation_bolt::spell_gnomeregan_radiation_bolt_SpellScript, spell_midnight_fixate, spell_moroes_vanish, spell_nether_portal_perseverence, spell_malchezaar_enfeeble, spell_flamewreath, spell_flamewreath_aura, spell_karazhan_brittle_bones::spell_karazhan_brittle_bones_AuraScript, spell_karazhan_overload::spell_karazhan_overload_AuraScript, spell_karazhan_blink::spell_karazhan_blink_SpellScript, spell_karazhan_temptation, spell_mt_phoenix_burn, spell_q12641_death_comes_from_on_high_summon_ghouls::spell_q12641_death_comes_from_on_high_summon_ghouls_SpellScript, spell_item_gift_of_the_harvester::spell_item_gift_of_the_harvester_SpellScript, spell_q12698_the_gift_that_keeps_on_giving::spell_q12698_the_gift_that_keeps_on_giving_SpellScript, spell_death_knight_initiate_visual, spell_q12779_an_end_to_all_things, spell_chapter5_light_of_dawn_aura::spell_chapter5_light_of_dawn_aura_AuraScript, spell_chapter5_rebuke::spell_chapter5_rebuke_SpellScript, spell_kormok_summon_bone_mages, spell_kormok_summon_bone_minions, spell_scholomance_fixate::spell_scholomance_fixate_AuraScript, spell_scholomance_boon_of_life::spell_scholomance_boon_of_life_AuraScript, spell_apothecary_lingering_fumes, spell_apothecary_validate_area, spell_apothecary_throw_cologne, spell_apothecary_throw_perfume, spell_apothecary_perfume_spill, spell_apothecary_cologne_spill, spell_shadowfang_keep_haunting_spirits::spell_shadowfang_keep_haunting_spirits_AuraScript, spell_shadowfang_keep_forsaken_skills::spell_shadowfang_keep_forsaken_skills_AuraScript, spell_temple_of_atal_hakkar_hex_of_jammal_an::spell_temple_of_atal_hakkar_hex_of_jammal_an_AuraScript, spell_temple_of_atal_hakkar_awaken_the_soulflayer::spell_temple_of_atal_hakkar_awaken_the_soulflayer_SpellScript, spell_madrigosa_activate_barrier::spell_madrigosa_activate_barrier_SpellScript, spell_madrigosa_deactivate_barrier::spell_madrigosa_deactivate_barrier_SpellScript, spell_brutallus_burn::spell_brutallus_burn_SpellScript, spell_eredar_twins_apply_dark_touched::spell_eredar_twins_apply_dark_touched_SpellScript, spell_eredar_twins_apply_flame_touched::spell_eredar_twins_apply_flame_touched_SpellScript, spell_eredar_twins_handle_touch::spell_eredar_twins_handle_touch_SpellScript, spell_eredar_twins_blaze::spell_eredar_twins_blaze_SpellScript, spell_felmyst_fog_of_corruption::spell_felmyst_fog_of_corruption_SpellScript, spell_felmyst_fog_of_corruption_charm::spell_felmyst_fog_of_corruption_charm_AuraScript, spell_felmyst_open_brutallus_back_doors::spell_felmyst_open_brutallus_back_doors_SpellScript, spell_kalecgos_spectral_blast_dummy::spell_kalecgos_spectral_blast_dummy_SpellScript, spell_kalecgos_curse_of_boundless_agony::spell_kalecgos_curse_of_boundless_agony_AuraScript, spell_kalecgos_spectral_realm_dummy::spell_kalecgos_spectral_realm_dummy_SpellScript, spell_kalecgos_spectral_realm::spell_kalecgos_spectral_realm_AuraScript, spell_kiljaeden_shadow_spike::spell_kiljaeden_shadow_spike_AuraScript, spell_kiljaeden_sinister_reflection::spell_kiljaeden_sinister_reflection_SpellScript, spell_kiljaeden_sinister_reflection_clone::spell_kiljaeden_sinister_reflection_clone_SpellScript, spell_kiljaeden_flame_dart::spell_kiljaeden_flame_dart_SpellScript, spell_kiljaeden_darkness::spell_kiljaeden_darkness_AuraScript, spell_kiljaeden_power_of_the_blue_flight::spell_kiljaeden_power_of_the_blue_flight_SpellScript, spell_kiljaeden_vengeance_of_the_blue_flight::spell_kiljaeden_vengeance_of_the_blue_flight_AuraScript, spell_kiljaeden_armageddon_periodic::spell_kiljaeden_armageddon_periodic_AuraScript, spell_kiljaeden_armageddon_missile::spell_kiljaeden_armageddon_missile_SpellScript, spell_kiljaeden_dragon_breath::spell_kiljaeden_dragon_breath_SpellScript, spell_muru_summon_blood_elves_periodic::spell_muru_summon_blood_elves_periodic_AuraScript, spell_muru_darkness::spell_muru_darkness_AuraScript, spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript, spell_entropius_void_zone_visual::spell_entropius_void_zone_visual_AuraScript, spell_entropius_black_hole_effect::spell_entropius_black_hole_effect_SpellScript, spell_cataclysm_breath::spell_cataclysm_breath_SpellScript, spell_uldaman_sub_boss_agro_keepers::spell_uldaman_sub_boss_agro_keepers_SpellScript, spell_uldaman_stoned::spell_uldaman_stoned_AuraScript, spell_uldaman_boss_agro_archaedas::spell_uldaman_boss_agro_archaedas_SpellScript, spell_razelikh_teleport_group::spell_razelikh_teleport_group_SpellScript, spell_bh_cleanse_quel_delar::spell_bh_cleanse_quel_delar_SpellScript, spell_blight_worm_ingest::spell_blight_worm_ingest_SpellScript, spell_hexlord_unstable_affliction::spell_hexlord_unstable_affliction_AuraScript, spell_gahzranka_slam, spell_pagles_point_cast, spell_blood_siphon, spell_hakkar_power_down, spell_chain_burn, spell_batrider_bomb, spell_random_aggro, spell_delusions_of_jindo, spell_threatening_gaze::spell_threatening_gaze_AuraScript, spell_mandokir_charge, spell_threatening_gaze_charge, spell_hatch_eggs, spell_enveloping_webs, spell_marli_transform, spell_axe_flurry, spell_brewfest_main_ram_buff, spell_brewfest_ram_fatigue, spell_brewfest_apple_trap, spell_catch_the_wild_wolpertinger, spell_brewfest_fill_keg, spell_brewfest_unfill_keg, spell_brewfest_toss_mug, spell_brewfest_add_mug, spell_brewfest_reveler_transform, spell_brewfest_relay_race_force_cast, spell_direbrew_summon_mole_machine_target_picker, spell_send_mug_target_picker, spell_request_second_mug, spell_send_mug_control_aura, spell_barreled_control_aura, spell_direbrew_disarm, spell_hallows_end_trick, spell_hallows_end_put_costume, spell_hallows_end_trick_or_treat, spell_hallows_end_candy, spell_hallows_end_candy_pirate_costume, spell_hallows_end_tricky_treat, spell_hallows_end_bucket_lands, spell_hallows_end_base_fire, spell_love_in_air_perfume_immune, spell_item_create_heart_candy, spell_love_is_in_the_air_romantic_picnic, spell_gen_aura_service_uniform, spell_gen_crab_disguise, spell_midsummer_ribbon_pole_firework, spell_midsummer_ribbon_pole, spell_midsummer_ribbon_pole_visual, spell_midsummer_torch_quest, spell_midsummer_fling_torch, spell_midsummer_juggling_torch, spell_midsummer_torch_catch, spell_pilgrims_bounty_pass_generic, spell_pilgrims_bounty_feast_on_generic, spell_pilgrims_bounty_turkey_tracker, spell_pilgrims_bounty_serve_generic, spell_pilgrims_bounty_food_aura, spell_pilgrims_bounty_food, spell_winter_veil_mistletoe, spell_winter_wondervolt_trap, spell_winter_veil_racer_rocket_slam, spell_winter_veil_racer_slam_hit, spell_winter_veil_shoot_air_rifle, spell_arcane_vacuum, spell_mark_of_frost_freeze, spell_red_sky_effect::spell_red_sky_effect_SpellScript, spell_finger_of_death::spell_finger_of_death_SpellScript, spell_hand_of_death::spell_hand_of_death_SpellScript, spell_mark_of_kazrogal::spell_mark_of_kazrogal_SpellScript, spell_mark_of_kazrogal::spell_mark_of_kazrogal_AuraScript, spell_boss_salramm_steal_flesh::spell_boss_salramm_steal_flesh_AuraScript, spell_black_morass_corrupt_medivh, spell_ayamiss_swarmer_teleport_trigger, spell_ayamiss_swarmer_swarm, spell_ayamiss_swarmer_start_loop, spell_gen_ayamiss_swarmer_loop, spell_egg_explosion, spell_moam_mana_drain_filter, spell_moam_summon_mana_fiends, spell_crystal_weakness, spell_aq_shadow_storm, spell_rajaxx_thundercrash, spell_drain_mana, spell_vem_knockback, spell_vem_vengeance, spell_cthun_dark_glare, spell_cthun_digestive_acid, spell_huhuran_wyvern_sting, spell_huhuran_poison_bolt, spell_skeram_arcane_explosion, spell_mutate_explode_bug, spell_explode_trigger, spell_summon_toxin_slime, spell_anubisath_mortal_strike, spell_mana_burn_area, spell_aggro_drones, spell_nullify, spell_inoculate_nestlewood_owlkin, spell_mount_check::spell_mount_check_AuraScript, spell_voljin_war_drums::spell_voljin_war_drums_SpellScript, spell_voodoo::spell_voodoo_SpellScript, spell_ooze_zap::spell_ooze_zap_SpellScript, spell_ooze_zap_channel_end::spell_ooze_zap_channel_end_SpellScript, spell_energize_aoe::spell_energize_aoe_SpellScript, spell_gordunni_trap::spell_gordunni_trap_SpellScript, spell_panther_cage_key, spell_zulfarrak_summon_zulfarrak_zombies::spell_zulfarrak_summon_zulfarrak_zombies_SpellScript, spell_zulfarrak_unlocking::spell_zulfarrak_unlocking_SpellScript, spell_amanitar_remove_mushroom_power, spell_ahn_kahet_swarmer_aura, spell_herald_volzaj_insanity, spell_volazj_whisper, spell_random_lightning_visual_effect, spell_prince_taldaram_conjure_flame_sphere, spell_prince_taldaram_flame_sphere_summon, spell_shadow_sickle_periodic_damage, spell_azjol_nerub_carrion_beetels, spell_azjol_nerub_pound, spell_azjol_nerub_impale_summon, spell_hadronox_summon_periodic::spell_hadronox_summon_periodic_AuraScript, spell_hadronox_leech_poison::spell_hadronox_leech_poison_AuraScript, spell_azjol_nerub_fixate::spell_azjol_nerub_fixate_SpellScript, spell_azjol_nerub_web_wrap::spell_azjol_nerub_web_wrap_AuraScript, spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript, spell_baltharus_enervating_brand_trigger::spell_baltharus_enervating_brand_trigger_SpellScript, spell_halion_meteor_strike_targeting::spell_halion_meteor_strike_targeting_SpellScript, spell_halion_meteor_strike_marker::spell_halion_meteor_strike_marker_AuraScript, spell_halion_meteor_strike_spread::spell_halion_meteor_strike_spread_AuraScript, spell_halion_blazing_aura::spell_halion_blazing_aura_SpellScript, spell_halion_combustion_consumption::spell_halion_combustion_consumption_AuraScript, spell_halion_marks::spell_halion_marks_AuraScript, spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript, spell_halion_clear_debuffs::spell_halion_clear_debuffs_SpellScript, spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript, spell_halion_twilight_phasing::spell_halion_twilight_phasing_AuraScript, spell_halion_twilight_realm::spell_halion_twilight_realm_AuraScript, spell_halion_leave_twilight_realm::spell_halion_leave_twilight_realm_AuraScript, spell_halion_twilight_cutter_periodic::spell_halion_twilight_cutter_periodic_AuraScript, spell_halion_twilight_cutter::spell_halion_twilight_cutter_SpellScript, spell_halion_summon_exit_portals::spell_halion_summon_exit_portals_SpellScript, spell_halion_twilight_division::spell_halion_twilight_division_SpellScript, spell_halion_twilight_mending::spell_halion_twilight_mending_SpellScript, spell_saviana_conflagration_init::spell_saviana_conflagration_init_SpellScript, spell_saviana_conflagration_throwback::spell_saviana_conflagration_throwback_SpellScript, spell_ruby_sanctum_rallying_shout::spell_ruby_sanctum_rallying_shout_SpellScript, spell_eadric_radiance::spell_eadric_radiance_SpellScript, spell_toc5_light_rain::spell_toc5_light_rain_SpellScript, spell_pursuing_spikes::spell_pursuing_spikesAuraScript, spell_gen_leeching_swarm::spell_gen_leeching_swarm_AuraScript, spell_gen_leeching_swarm_dmg::spell_gen_leeching_swarm_dmg_SpellScript, spell_faction_champion_warl_unstable_affliction::spell_faction_champion_warl_unstable_affliction_AuraScript, spell_toc25_mistress_kiss::spell_toc25_mistress_kiss_AuraScript, spell_mistress_kiss_area::spell_mistress_kiss_area_SpellScript, spell_valkyr_touch::spell_valkyr_touchAuraScript, spell_valkyr_ball_periodic_dummy::spell_valkyr_ball_periodic_dummyAuraScript, spell_dred_grievious_bite::spell_dred_grievious_bite_AuraScript, spell_dred_raptor_call::spell_dred_raptor_call_SpellScript, spell_novos_despawn_crystal_handler::spell_novos_despawn_crystal_handler_SpellScript, spell_novos_crystal_handler_death::spell_novos_crystal_handler_death_AuraScript, spell_novos_summon_minions::spell_novos_summon_minions_SpellScript, spell_tharon_ja_curse_of_life::spell_tharon_ja_curse_of_life_AuraScript, spell_tharon_ja_dummy::spell_tharon_ja_dummy_AuraScript, spell_tharon_ja_clear_gift_of_tharon_ja::spell_tharon_ja_clear_gift_of_tharon_ja_SpellScript, spell_trollgore_consume::spell_trollgore_consume_SpellScript, spell_trollgore_corpse_explode::spell_trollgore_corpse_explode_AuraScript, spell_trollgore_invader_taunt::spell_trollgore_invader_taunt_SpellScript, spell_dtk_raise_dead::spell_dtk_raise_dead_AuraScript, spell_dtk_summon_random_drakkari::spell_dtk_summon_random_drakkari_SpellScript, spell_bronjahm_magic_bane::spell_bronjahm_magic_bane_SpellScript, spell_bronjahm_soulstorm_channel_ooc::spell_bronjahm_soulstorm_channel_ooc_AuraScript, spell_bronjahm_soulstorm_visual::spell_bronjahm_soulstorm_visual_AuraScript, spell_bronjahm_soulstorm_targeting::spell_bronjahm_soulstorm_targeting_SpellScript, spell_wailing_souls_periodic::spell_wailing_souls_periodic_AuraScript, spell_shield_of_bones::spell_shield_of_bones_AuraScript, spell_hor_shared_suffering::spell_hor_shared_sufferingAuraScript, spell_hor_gunship_cannon_fire::spell_hor_gunship_cannon_fireAuraScript, spell_garfrost_permafrost::spell_garfrost_permafrost_SpellScript, spell_krick_explosive_barrage::spell_krick_explosive_barrage_AuraScript, spell_exploding_orb_auto_grow::spell_exploding_orb_auto_grow_AuraScript, spell_pos_empowered_blizzard::spell_pos_empowered_blizzardAuraScript, spell_pos_slave_trigger_closest::spell_pos_slave_trigger_closestSpellScript, spell_pos_rimefang_frost_nova::spell_pos_rimefang_frost_novaSpellScript, spell_pos_blight::spell_pos_blightAuraScript, spell_pos_glacial_strike::spell_pos_glacial_strikeAuraScript, spell_drakkari_colossus_emerge::spell_drakkari_colossus_emerge_SpellScript, spell_drakkari_colossus_surge::spell_drakkari_colossus_surge_SpellScript, spell_drakkari_colossus_face_me::spell_drakkari_colossus_face_me_SpellScript, spell_galdarah_impaling_charge::spell_galdarah_impaling_charge_SpellScript, spell_galdarah_transform::spell_galdarah_transform_SpellScript, spell_moorabi_mojo_frenzy::spell_moorabi_mojo_frenzy_AuraScript, spell_sladran_grip_of_sladran::spell_sladran_grip_of_sladran_AuraScript, spell_blood_council_shadow_prison::spell_blood_council_shadow_prison_AuraScript, spell_blood_council_shadow_prison_damage::spell_blood_council_shadow_prison_SpellScript, spell_taldaram_glittering_sparks::spell_taldaram_glittering_sparks_SpellScript, spell_taldaram_summon_flame_ball::spell_taldaram_summon_flame_ball_SpellScript, spell_taldaram_ball_of_inferno_flame::spell_taldaram_ball_of_inferno_flame_SpellScript, spell_valanar_kinetic_bomb::spell_valanar_kinetic_bomb_SpellScript, spell_valanar_kinetic_bomb::spell_valanar_kinetic_bomb_AuraScript, spell_valanar_kinetic_bomb_absorb::spell_valanar_kinetic_bomb_absorb_AuraScript, spell_valanar_kinetic_bomb_knockback::spell_valanar_kinetic_bomb_knockback_SpellScript, spell_valanar_kinetic_bomb_summon::spell_valanar_kinetic_bomb_summon_SpellScript, spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript, spell_blood_queen_pact_of_the_darkfallen_dmg::spell_blood_queen_pact_of_the_darkfallen_dmg_AuraScript, spell_blood_queen_pact_of_the_darkfallen::spell_blood_queen_pact_of_the_darkfallen_SpellScript, spell_blood_queen_pact_of_the_darkfallen_dmg_target::spell_blood_queen_pact_of_the_darkfallen_dmg_SpellScript, spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript, spell_blood_queen_frenzied_bloodthirst::spell_blood_queen_frenzied_bloodthirst_AuraScript, spell_blood_queen_essence_of_the_blood_queen::spell_blood_queen_essence_of_the_blood_queen_AuraScript, spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript, spell_blood_queen_swarming_shadows_floor_dmg::spell_blood_queen_swarming_shadows_floor_dmg_SpellScript, spell_blood_queen_presence_of_the_darkfallen::spell_blood_queen_presence_of_the_darkfallen_SpellScript, spell_deathbringer_blood_link_aura::spell_deathbringer_blood_link_AuraScript, spell_deathbringer_blood_link_blood_beast_aura::spell_deathbringer_blood_link_blood_beast_aura_AuraScript, spell_deathbringer_blood_link::spell_deathbringer_blood_link_SpellScript, spell_deathbringer_blood_power::spell_deathbringer_blood_power_SpellScript, spell_deathbringer_blood_power::spell_deathbringer_blood_power_AuraScript, spell_deathbringer_blood_nova_targeting::spell_deathbringer_blood_nova_targeting_SpellScript, spell_deathbringer_boiling_blood::spell_deathbringer_boiling_blood_SpellScript, spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript, spell_festergut_blighted_spores::spell_festergut_blighted_spores_AuraScript, spell_festergut_gastric_bloat::spell_festergut_gastric_bloat_SpellScript, spell_igb_rocket_pack::spell_igb_rocket_pack_AuraScript, spell_igb_rocket_pack_useable::spell_igb_rocket_pack_useable_AuraScript, spell_igb_teleport_to_enemy_ship::spell_igb_teleport_to_enemy_ship_SpellScript, spell_igb_check_for_players::spell_igb_check_for_players_SpellScript, spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript, spell_igb_explosion_main::spell_igb_explosion_main_AuraScript, spell_igb_explosion::spell_igb_explosion_SpellScript, spell_igb_teleport_players_on_victory::spell_igb_teleport_players_on_victory_SpellScript, spell_igb_periodic_trigger_with_power_cost::spell_igb_periodic_trigger_with_power_cost_AuraScript, spell_igb_overheat::spell_igb_overheat_AuraScript, spell_igb_cannon_blast::spell_igb_cannon_blast_SpellScript, spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript, spell_igb_burning_pitch_selector::spell_igb_burning_pitch_selector_SpellScript, spell_igb_burning_pitch::spell_igb_burning_pitch_SpellScript, spell_igb_rocket_artillery::spell_igb_rocket_artillery_SpellScript, spell_igb_rocket_artillery_explosion::spell_igb_rocket_artillery_explosion_SpellScript, spell_igb_below_zero::spell_igb_below_zero_SpellScript, spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript, spell_igb_battle_experience_check, spell_deathwhisper_mana_barrier::spell_deathwhisper_mana_barrier_AuraScript, spell_deathwhisper_dark_reckoning, spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript, spell_marrowgar_bone_spike_graveyard::spell_marrowgar_bone_spike_graveyard_SpellScript, spell_marrowgar_coldflame_bonestorm::spell_marrowgar_coldflame_SpellScript, spell_marrowgar_bone_storm::spell_marrowgar_bone_storm_SpellScript, spell_marrowgar_bone_slice::spell_marrowgar_bone_slice_SpellScript, spell_putricide_slime_puddle::spell_putricide_slime_puddle_SpellScript, spell_putricide_slime_puddle_spawn::spell_putricide_slime_puddle_spawn_SpellScript, spell_putricide_grow_stacker::spell_putricide_grow_stacker_AuraScript, spell_putricide_unstable_experiment::spell_putricide_unstable_experiment_SpellScript, spell_putricide_tear_gas_effect::spell_putricide_tear_gas_effect_SpellScript, spell_putricide_gaseous_bloat::spell_putricide_gaseous_bloat_AuraScript, spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript, spell_putricide_ooze_eruption_searcher::spell_putricide_ooze_eruption_searcher_SpellScript, spell_putricide_mutated_plague::spell_putricide_mutated_plague_AuraScript, spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript, spell_putricide_unbound_plague_dmg::spell_putricide_unbound_plague_dmg_AuraScript, spell_putricide_choking_gas_bomb::spell_putricide_choking_gas_bomb_SpellScript, spell_putricide_clear_aura_effect_value::spell_putricide_clear_aura_effect_value_SpellScript, spell_putricide_mutation_init::spell_putricide_mutation_init_SpellScript, spell_putricide_mutation_init::spell_putricide_mutation_init_AuraScript, spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript, spell_putricide_mutated_transformation_dismiss::spell_putricide_mutated_transformation_dismiss_AuraScript, spell_putricide_mutated_transformation_dmg::spell_putricide_mutated_transformation_dmg_SpellScript, spell_putricide_eat_ooze::spell_putricide_eat_ooze_SpellScript, spell_putricide_regurgitated_ooze::spell_putricide_regurgitated_ooze_SpellScript, spell_rotface_mutated_infection::spell_rotface_mutated_infection_SpellScript, spell_rotface_mutated_infection::spell_rotface_mutated_infection_AuraScript, spell_rotface_little_ooze_combine::spell_rotface_little_ooze_combine_SpellScript, spell_rotface_large_ooze_combine::spell_rotface_large_ooze_combine_SpellScript, spell_rotface_large_ooze_buff_combine::spell_rotface_large_ooze_buff_combine_SpellScript, spell_rotface_unstable_ooze_explosion_init::spell_rotface_unstable_ooze_explosion_init_SpellScript, spell_rotface_unstable_ooze_explosion::spell_rotface_unstable_ooze_explosion_SpellScript, spell_rotface_unstable_ooze_explosion_suicide::spell_rotface_unstable_ooze_explosion_suicide_AuraScript, spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript, spell_sindragosa_unchained_magic::spell_sindragosa_unchained_magic_SpellScript, spell_sindragosa_unchained_magic::spell_sindragosa_unchained_magic_AuraScript, spell_sindragosa_permeating_chill::spell_sindragosa_permeating_chill_AuraScript, spell_sindragosa_instability::spell_sindragosa_instability_AuraScript, spell_sindragosa_icy_grip::spell_sindragosa_icy_grip_SpellScript, spell_sindragosa_icy_grip_jump::spell_sindragosa_icy_grip_jump_SpellScript, spell_sindragosa_frost_beacon::spell_sindragosa_frost_beacon_AuraScript, spell_sindragosa_ice_tomb_filter::spell_sindragosa_ice_tomb_filter_SpellScript, spell_sindragosa_ice_tomb::spell_sindragosa_ice_tomb_SpellScript, spell_sindragosa_ice_tomb::spell_sindragosa_ice_tomb_AuraScript, spell_sindragosa_mystic_buffet::spell_sindragosa_mystic_buffet_SpellScript, spell_sindragosa_soul_preservation::spell_sindragosa_soul_preservation_AuraScript, spell_rimefang_icy_blast::spell_rimefang_icy_blast_SpellScript, spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript, spell_frostwarden_handler_focus_fire::spell_frostwarden_handler_focus_fire_SpellScript, spell_frostwarden_handler_focus_fire::spell_frostwarden_handler_focus_fire_AuraScript, spell_sindragosa_frost_breath::spell_sindragosa_frost_breath_SpellScript, spell_the_lich_king_quake::spell_the_lich_king_quake_SpellScript, spell_the_lich_king_jump::spell_the_lich_king_jump_SpellScript, spell_the_lich_king_jump_remove_aura::spell_the_lich_king_jump_SpellScript, spell_the_lich_king_play_movie::spell_the_lich_king_play_movie_SpellScript, spell_the_lich_king_infest::spell_the_lich_king_infest_AuraScript, spell_the_lich_king_necrotic_plague::spell_the_lich_king_necrotic_plague_AuraScript, spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_SpellScript, spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript, spell_the_lich_king_shadow_trap_visual::spell_the_lich_king_shadow_trap_visual_AuraScript, spell_the_lich_king_shadow_trap_periodic::spell_the_lich_king_shadow_trap_periodic_SpellScript, spell_the_lich_king_ice_burst_target_search::spell_the_lich_king_ice_burst_target_search_SpellScript, spell_the_lich_king_raging_spirit::spell_the_lich_king_raging_spirit_SpellScript, spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript, spell_the_lich_king_soul_reaper::spell_the_lich_king_soul_reaper_AuraScript, spell_the_lich_king_summon_into_air::spell_the_lich_king_summon_into_air_SpellScript, spell_the_lich_king_teleport_to_frostmourne_hc::spell_the_lich_king_teleport_to_frostmourne_hc_SpellScript, spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript, spell_the_lich_king_cast_back_to_caster::spell_the_lich_king_cast_back_to_caster_SpellScript, spell_the_lich_king_life_siphon::spell_the_lich_king_life_siphon_SpellScript, spell_the_lich_king_vile_spirits::spell_the_lich_king_vile_spirits_AuraScript, spell_the_lich_king_vile_spirits_visual::spell_the_lich_king_vile_spirits_visual_SpellScript, spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript, spell_the_lich_king_vile_spirit_damage_target_search::spell_the_lich_king_vile_spirit_damage_target_search_SpellScript, spell_the_lich_king_harvest_soul::spell_the_lich_king_harvest_soul_AuraScript, spell_the_lich_king_lights_favor::spell_the_lich_king_lights_favor_AuraScript, spell_the_lich_king_restore_soul::spell_the_lich_king_restore_soul_SpellScript, spell_the_lich_king_dark_hunger::spell_the_lich_king_dark_hunger_AuraScript, spell_the_lich_king_soul_rip::spell_the_lich_king_soul_rip_AuraScript, spell_the_lich_king_summon_spirit_bomb::spell_the_lich_king_summon_spirit_bomb_SpellScript, spell_the_lich_king_trigger_vile_spirit::spell_the_lich_king_trigger_vile_spirit_SpellScript, spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript, spell_dreamwalker_twisted_nightmares::spell_dreamwalker_twisted_nightmares_SpellScript, spell_dreamwalker_nightmare_cloud::spell_dreamwalker_nightmare_cloud_AuraScript, spell_dreamwalker_mana_void::spell_dreamwalker_mana_void_AuraScript, spell_dreamwalker_decay_periodic_timer::spell_dreamwalker_decay_periodic_timer_AuraScript, spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript, spell_dreamwalker_summon_suppresser::spell_dreamwalker_summon_suppresser_AuraScript, spell_dreamwalker_summon_suppresser_effect::spell_dreamwalker_summon_suppresser_effect_SpellScript, spell_valithria_suppression::spell_valithria_suppression_AuraScript, spell_icc_stoneform::spell_icc_stoneform_AuraScript, spell_icc_sprit_alarm::spell_icc_sprit_alarm_SpellScript, spell_icc_geist_alarm::spell_icc_geist_alarm_SpellScript, spell_frost_giant_death_plague::spell_frost_giant_death_plague_SpellScript, spell_icc_harvest_blight_specimen::spell_icc_harvest_blight_specimen_SpellScript, spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript, spell_svalna_remove_spear::spell_svalna_remove_spear_SpellScript, spell_icc_soul_missile::spell_icc_soul_missile_SpellScript, spell_icc_web_wrap::spell_icc_web_wrap_AuraScript, spell_icc_dark_reckoning::spell_icc_dark_reckoning_AuraScript, spell_stinky_precious_decimate::spell_stinky_precious_decimate_SpellScript, spell_icc_yf_frozen_orb::spell_icc_yf_frozen_orb_AuraScript, spell_icc_yh_volley::spell_icc_yh_volley_AuraScript, spell_icc_yd_summon_undead::spell_icc_yd_summon_undead_SpellScript, spell_icc_shattered_bones::spell_icc_shattered_bones_SpellScript, spell_trigger_spell_from_caster::spell_trigger_spell_from_caster_SpellScript, spell_ioc_repair_turret::spell_ioc_repair_turret_AuraScript, spell_ioc_bomb_blast_criteria::spell_ioc_bomb_blast_criteria_SpellScript, spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript, spell_ioc_parachute_ic::spell_ioc_parachute_ic_AuraScript, spell_ioc_launch::spell_ioc_launch_SpellScript, spell_four_horsemen_mark::spell_four_horsemen_mark_AuraScript, spell_four_horsemen_consumption, spell_gluth_decimate::spell_gluth_decimate_SpellScript, spell_gothik_shadow_bolt_volley::spell_gothik_shadow_bolt_volley_SpellScript, spell_grobbulus_poison::spell_grobbulus_poison_SpellScript, spell_grobbulus_mutating_injection::spell_grobbulus_mutating_injection_AuraScript, spell_kelthuzad_frost_blast::spell_kelthuzad_frost_blast_SpellScript, spell_kelthuzad_detonate_mana::spell_kelthuzad_detonate_mana_AuraScript, spell_sapphiron_frost_explosion::spell_sapphiron_frost_explosion_SpellScript, spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript, spell_thaddius_polarity_shift::spell_thaddius_polarity_shift_SpellScript, spell_eoe_ph3_surge_of_power::spell_eoe_ph3_surge_of_power_SpellScript, spell_boss_magus_telestra_summon_telestra_clones::spell_boss_magus_telestra_summon_telestra_clones_AuraScript, spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript, spell_oculus_stop_time::spell_oculus_stop_time_AuraScript, spell_oculus_evasive_maneuvers::spell_oculus_evasive_maneuvers_AuraScript, spell_oculus_shock_lance::spell_oculus_shock_lance_SpellScript, spell_oculus_temporal_rift::spell_oculus_temporal_rift_AuraScript, spell_oculus_touch_the_nightmare::spell_oculus_touch_the_nightmare_SpellScript, spell_oculus_dream_funnel::spell_oculus_dream_funnel_AuraScript, spell_oculus_call_ruby_emerald_amber_drake::spell_oculus_call_ruby_emerald_amber_drake_SpellScript, spell_oculus_ride_ruby_emerald_amber_drake_que::spell_oculus_ride_ruby_emerald_amber_drake_que_AuraScript, spell_oculus_evasive_charges::spell_oculus_evasive_chargesAuraScript, spell_oculus_soar::spell_oculus_soarAuraScript, spell_oculus_rider_aura::spell_oculus_rider_auraAuraScript, spell_oculus_drake_flag::spell_oculus_drake_flagAuraScript, spell_loken_pulsing_shockwave::spell_loken_pulsing_shockwave_SpellScript, spell_krystallus_shatter::spell_krystallus_shatter_SpellScript, spell_krystallus_shatter_effect::spell_krystallus_shatter_effect_SpellScript, spell_hos_dark_matter::spell_hos_dark_matter_AuraScript, spell_algalon_phase_punch::spell_algalon_phase_punch_AuraScript, spell_algalon_collapse::spell_algalon_collapse_AuraScript, spell_algalon_trigger_3_adds::spell_algalon_trigger_3_adds_SpellScript, spell_algalon_cosmic_smash_damage::spell_algalon_cosmic_smash_damage_SpellScript, spell_algalon_big_bang::spell_algalon_big_bang_SpellScript, spell_algalon_remove_phase::spell_algalon_remove_phase_AuraScript, spell_algalon_supermassive_fail::spell_algalon_supermassive_fail_SpellScript, spell_shield_of_runes::spell_shield_of_runes_AuraScript, spell_assembly_meltdown::spell_assembly_meltdown_SpellScript, spell_assembly_rune_of_summoning::spell_assembly_rune_of_summoning_AuraScript, spell_auriaya_sentinel_blast::spell_auriaya_sentinel_blast_SpellScript, spell_load_into_catapult::spell_load_into_catapult_AuraScript, spell_auto_repair::spell_auto_repair_SpellScript, spell_systems_shutdown::spell_systems_shutdown_AuraScript, spell_pursue::spell_pursue_SpellScript, spell_vehicle_throw_passenger::spell_vehicle_throw_passenger_SpellScript, spell_tar_blaze::spell_tar_blaze_AuraScript, spell_vehicle_grab_pyrite::spell_vehicle_grab_pyrite_SpellScript, spell_vehicle_circuit_overload::spell_vehicle_circuit_overload_AuraScript, spell_orbital_supports::spell_orbital_supports_AuraScript, spell_thorims_hammer::spell_thorims_hammer_SpellScript, spell_shield_generator::spell_shield_generator_AuraScript, spell_demolisher_ride_vehicle::spell_demolisher_ride_vehicle_SpellScript, spell_mark_of_the_faceless_periodic::spell_mark_of_the_faceless_periodic_AuraScript, spell_mark_of_the_faceless_drainhealth::spell_mark_of_the_faceless_drainhealth_SpellScript, spell_saronite_vapors_damage::spell_saronite_vapors_damage_SpellScript, spell_hodir_shatter_chest::spell_hodir_shatter_chestSpellScript, spell_hodir_biting_cold_main_aura::spell_hodir_biting_cold_main_aura_AuraScript, spell_hodir_biting_cold_player_aura::spell_hodir_biting_cold_player_aura_AuraScript, spell_hodir_periodic_icicle::spell_hodir_periodic_icicle_SpellScript, spell_hodir_flash_freeze::spell_hodir_flash_freeze_SpellScript, spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript, spell_hodir_storm_power::spell_hodir_storm_power_AuraScript, spell_hodir_storm_cloud::spell_hodir_storm_cloud_AuraScript, spell_hodir_toasty_fire::spell_hodir_toasty_fire_AuraScript, spell_hodir_starlight::spell_hodir_starlight_AuraScript, spell_ignis_scorch::spell_ignis_scorch_AuraScript, spell_ignis_grab_initial::spell_ignis_grab_initial_SpellScript, spell_ignis_slag_pot::spell_ignis_slag_pot_AuraScript, spell_ulduar_stone_grip_cast_target::spell_ulduar_stone_grip_cast_target_SpellScript, spell_ulduar_stone_grip::spell_ulduar_stone_grip_AuraScript, spell_ulduar_squeezed_lifeless::spell_ulduar_squeezed_lifeless_SpellScript, spell_kologarn_stone_shout::spell_kologarn_stone_shout_AuraScript, spell_kologarn_stone_shout::spell_kologarn_stone_shout_SpellScript, spell_mimiron_rapid_burst::spell_mimiron_rapid_burst_AuraScript, spell_mimiron_p3wx2_laser_barrage::spell_mimiron_p3wx2_laser_barrage_AuraScript, spell_thorim_lightning_pillar_P2::spell_thorim_lightning_pillar_P2_AuraScript, spell_thorim_trash_impale::spell_thorim_trash_impale_AuraScript, spell_xt002_tympanic_tantrum::spell_xt002_tympanic_tantrum_SpellScript, spell_xt002_gravity_bomb_aura::spell_xt002_gravity_bomb_aura_AuraScript, spell_xt002_gravity_bomb_aura::spell_xt002_gravity_bomb_aura_SpellScript, spell_xt002_gravity_bomb_damage::spell_xt002_gravity_bomb_damage_SpellScript, spell_xt002_searing_light_spawn_life_spark::spell_xt002_searing_light_spawn_life_spark_AuraScript, spell_xt002_searing_light_spawn_life_spark::spell_xt002_searing_light_spawn_life_spark_SpellScript, spell_yogg_saron_malady_of_the_mind::spell_yogg_saron_malady_of_the_mind_AuraScript, spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_AuraScript, spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_SpellScript, spell_yogg_saron_shadow_beacon::spell_yogg_saron_shadow_beacon_AuraScript, spell_yogg_saron_destabilization_matrix::spell_yogg_saron_destabilization_matrix_SpellScript, spell_yogg_saron_titanic_storm::spell_yogg_saron_titanic_storm_SpellScript, spell_yogg_saron_lunatic_gaze::spell_yogg_saron_lunatic_gaze_SpellScript, spell_yogg_saron_protective_gaze::spell_yogg_saron_protective_gaze_AuraScript, spell_yogg_saron_empowered::spell_yogg_saron_empowered_AuraScript, spell_yogg_saron_insane_periodic_trigger::spell_yogg_saron_insane_periodic_trigger_SpellScript, spell_yogg_saron_insane::spell_yogg_saron_insane_AuraScript, spell_yogg_saron_sanity_well::spell_yogg_saron_sanity_well_AuraScript, spell_yogg_saron_sanity_reduce::spell_yogg_saron_sanity_reduce_SpellScript, spell_yogg_saron_empowering_shadows::spell_yogg_saron_empowering_shadows_SpellScript, spell_yogg_saron_in_the_maws_of_the_old_god::spell_yogg_saron_in_the_maws_of_the_old_god_SpellScript, spell_yogg_saron_target_selectors::spell_yogg_saron_target_selectors_SpellScript, spell_yogg_saron_grim_reprisal::spell_yogg_saron_grim_reprisal_AuraScript, spell_ulduar_energy_sap::spell_ulduar_energy_sap_AuraScript, spell_ulduar_arachnopod_damaged::spell_ulduar_arachnopod_damaged_AuraScript, spell_frost_tomb::spell_frost_tombAuraScript, spell_ticking_time_bomb::spell_ticking_time_bomb_AuraScript, spell_svala_ritual_strike::spell_svala_ritual_strike_SpellScript, spell_svala_ritual_strike::spell_svala_ritual_strike_AuraScript, spell_utgarde_pinnacle_beast_mark, spell_archavon_rock_shards::spell_archavon_rock_shards_SpellScript, spell_voa_overcharge::spell_voa_overcharge_AuraScript, spell_voa_lightning_nova::spell_voa_lightning_nova_SpellScript, spell_voa_flaming_cinder::spell_voa_flaming_cinder_SpellScript, spell_koralon_meteor_fists::spell_koralon_meteor_fists_AuraScript, spell_flame_warder_meteor_fists::spell_flame_warder_meteor_fists_AuraScript, spell_optic_link::spell_optic_linkAuraScript, spell_destroy_door_seal::spell_destroy_door_sealAuraScript, spell_q11919_q11940_drake_hunt::spell_q11919_q11940_drake_hunt_AuraScript, spell_arcane_chains_character_force_cast::spell_arcane_chains_character_force_cast_SpellScript, spell_q11719_bloodspore_ruination_45997::spell_q11719_bloodspore_ruination_45997_SpellScript, spell_q12237_rescue_villager, spell_q12237_drop_off_villager, spell_call_wintergarde_gryphon, spell_q12478_frostmourne_cavern::spell_q12478_frostmourne_cavern_SpellScript, spell_q12243_fire_upon_the_waters::spell_q12243_fire_upon_the_waters_AuraScript, spell_q24545_aod_special::spell_q24545_aod_special_SpellScript, spell_q12096_q12092_dummy::spell_q12096_q12092_dummy_SpellScript, spell_q12096_q12092_bark::spell_q12096_q12092_bark_SpellScript, spell_dragonblight_corrosive_spit, spell_q12227_outhouse_groans, spell_q12227_camera_shake, spell_renew_skirmisher, spell_shredder_delivery::spell_shredder_delivery_SpellScript, spell_infected_worgen_bite::spell_infected_worgen_bite_AuraScript, spell_vehicle_warhead_fuse::spell_vehicle_warhead_fuse_SpellScript, spell_warhead_detonate::spell_warhead_detonate_SpellScript, spell_z_check::spell_z_check_AuraScript, spell_warhead_fuse::spell_warhead_fuse_AuraScript, spell_frog_kiss, spell_switch_infragreen_bomber_station::spell_switch_infragreen_bomber_station_SpellScript, spell_charge_shield_bomber::spell_charge_shield_bomber_SpellScript, spell_charge_shield_bomber::spell_charge_shield_bomber_AuraScript, spell_fight_fire_bomber::spell_fight_fire_bomber_SpellScript, spell_anti_air_rocket_bomber::spell_anti_air_rocket_bomber_SpellScript, spell_onslaught_or_call_bone_gryphon::spell_onslaught_or_call_bone_gryphon_SpellScript, spell_deliver_gryphon, spell_q12726_song_of_wind_and_water::spell_q12726_song_of_wind_and_water_SpellScript, spell_q12620_the_lifewarden_wrath::spell_q12620_the_lifewarden_wrath_SpellScript, spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript, spell_shango_tracks::spell_shango_tracks_SpellScript, spell_q12611_deathbolt, spell_q13003_thursting_hodirs_spear::spell_q13003_thursting_hodirs_spear_AuraScript, spell_q13007_iron_colossus::spell_q13007_iron_colossus_SpellScript, spell_close_rift::spell_close_rift_AuraScript, spell_q12823_remove_collapsing_cave_aura, spell_wintergrasp_force_building::spell_wintergrasp_force_building_SpellScript, spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript, spell_wintergrasp_rp_gg::spell_wintergrasp_rp_gg_SpellScript, spell_wintergrasp_portal::spell_wintergrasp_portal_SpellScript, spell_wintergrasp_water::spell_wintergrasp_water_SpellScript, spell_wintergrasp_hide_small_elementals::spell_wintergrasp_hide_small_elementals_AuraScript, spell_wg_reduce_damage_by_distance::spell_wg_reduce_damage_by_distance_SpellScript, spell_auchenai_possess, spell_talon_king_ikiss_blink, spell_murmur_thundering_storm, spell_shockwave_knockback, spell_murmur_sonic_boom_effect, spell_mark_of_malice, spell_gurtogg_bloodboil::spell_gurtogg_bloodboil_SpellScript, spell_gurtogg_eject::spell_gurtogg_eject_SpellScript, spell_illidan_draw_soul::spell_illidan_draw_soul_SpellScript, spell_illidan_parasitic_shadowfiend::spell_illidan_parasitic_shadowfiend_AuraScript, spell_illidan_parasitic_shadowfiend_trigger::spell_illidan_parasitic_shadowfiend_trigger_AuraScript, spell_illidan_parasitic_shadowfiend_trigger::spell_illidan_parasitic_shadowfiend_trigger_SpellScript, spell_illidan_glaive_throw::spell_illidan_glaive_throw_SpellScript, spell_illidan_tear_of_azzinoth_summon_channel::spell_illidan_tear_of_azzinoth_summon_channel_AuraScript, spell_illidan_shadow_prison::spell_illidan_shadow_prison_SpellScript, spell_illidan_demon_transform1::spell_illidan_demon_transform1_AuraScript, spell_illidan_demon_transform2::spell_illidan_demon_transform2_AuraScript, spell_illidan_flame_burst::spell_illidan_flame_burst_SpellScript, spell_illidan_found_target::spell_illidan_found_target_SpellScript, spell_illidan_cage_trap::spell_illidan_cage_trap_SpellScript, spell_illidan_cage_trap_stun::spell_illidan_cage_trap_stun_AuraScript, spell_mother_shahraz_random_periodic::spell_mother_shahraz_random_periodic_AuraScript, spell_mother_shahraz_beam_periodic::spell_mother_shahraz_beam_periodic_AuraScript, spell_mother_shahraz_saber_lash::spell_mother_shahraz_saber_lash_AuraScript, spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript, spell_mother_shahraz_fatal_attraction_dummy::spell_mother_shahraz_fatal_attraction_dummy_SpellScript, spell_mother_shahraz_fatal_attraction_aura::spell_mother_shahraz_fatal_attraction_aura_AuraScript, spell_reliquary_of_souls_aura_of_suffering::spell_reliquary_of_souls_aura_of_suffering_AuraScript, spell_reliquary_of_souls_fixate::spell_reliquary_of_souls_fixate_SpellScript, spell_reliquary_of_souls_fixate::spell_reliquary_of_souls_fixate_AuraScript, spell_reliquary_of_souls_aura_of_desire::spell_reliquary_of_souls_aura_of_desire_AuraScript, spell_reliquary_of_souls_aura_of_anger::spell_reliquary_of_souls_aura_of_anger_AuraScript, spell_reliquary_of_souls_spite::spell_reliquary_of_souls_spite_AuraScript, spell_shade_of_akama_shade_soul_channel, spell_shade_of_akama_akama_soul_expel, spell_teron_gorefiend_shadow_of_death, spell_teron_gorefiend_spirit_lance, spell_teron_gorefiend_spiritual_vengeance, spell_teron_gorefiend_shadowy_construct, spell_najentus_needle_spine, spell_najentus_hurl_spine, spell_illidari_council_balance_of_power::spell_illidari_council_balance_of_power_AuraScript, spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript, spell_illidari_council_reflective_shield::spell_illidari_council_reflective_shield_AuraScript, spell_illidari_council_judgement::spell_illidari_council_judgement_SpellScript, spell_illidari_council_deadly_strike::spell_illidari_council_deadly_strike_AuraScript, spell_black_template_harpooners_mark::spell_black_template_harpooners_mark_AuraScript, spell_black_template_free_friend::spell_black_template_free_friend_SpellScript, spell_black_temple_curse_of_the_bleakheart::spell_black_temple_curse_of_the_bleakheart_AuraScript, spell_black_temple_skeleton_shot::spell_black_temple_skeleton_shot_AuraScript, spell_black_temple_wyvern_sting::spell_black_temple_wyvern_sting_AuraScript, spell_black_temple_charge_rage::spell_black_temple_charge_rage_AuraScript, spell_black_temple_shadow_inferno::spell_black_temple_shadow_inferno_AuraScript, spell_black_temple_spell_absorption::spell_black_temple_spell_absorption_AuraScript, spell_black_temple_bloodbolt::spell_black_temple_bloodbolt_SpellScript, spell_black_temple_consuming_strikes::spell_black_temple_consuming_strikes_AuraScript, spell_black_temple_curse_of_vitality::spell_black_temple_curse_of_vitality_AuraScript, spell_black_temple_dementia::spell_black_temple_dementia_AuraScript, spell_mark_of_kazzak::spell_mark_of_kazzak_AuraScript, spell_karathress_power_of_tidalvess, spell_karathress_power_of_caribdis, spell_hydross_cleansing_field_aura, spell_hydross_cleansing_field_command, spell_hydross_mark_of_hydross, spell_lady_vashj_magic_barrier, spell_lady_vashj_remove_tainted_cores, spell_lady_vashj_summon_sporebat, spell_lady_vashj_spore_drop_effect, spell_leotheras_whirlwind, spell_leotheras_chaos_blast, spell_leotheras_insidious_whisper, spell_leotheras_insidious_whisper_aura, spell_leotheras_demon_link, spell_leotheras_clear_consuming_madness, spell_lurker_below_spout, spell_lurker_below_spout_cone, spell_morogrim_tidewalker_watery_grave, spell_morogrim_tidewalker_water_globule_new_target, spell_serpentshrine_cavern_serpentshrine_parasite, spell_serpentshrine_cavern_serpentshrine_parasite_trigger_aura, spell_serpentshrine_cavern_serpentshrine_parasite_trigger, spell_serpentshrine_cavern_infection, spell_serpentshrine_cavern_coilfang_water, spell_warlords_rage, spell_spore_cloud, spell_despawn_underbog_mushrooms, spell_the_black_stalker_levitate, spell_the_black_stalker_levitation_pulse, spell_the_black_stalker_someone_grab_me, spell_the_black_stalker_magnetic_pull, spell_fungal_decay, spell_allergies, spell_gruul_ground_slam, spell_tractor_beam_creator, spell_gruul_ground_slam_trigger, spell_gruul_shatter, spell_gruul_shatter_effect, spell_broggok_poison_cloud, spell_vazruden_fireball, spell_vazruden_call_nazan, spell_gargolmar_retalliation, spell_magtheridon_blaze, spell_magtheridon_shadow_grasp, spell_magtheridon_quake, spell_magtheridon_debris_target_selector, spell_tsh_shadow_bolt, spell_target_fissures, spell_tsh_shoot_flame_arrow, spell_burning_maul, spell_blade_dance_targeting, spell_arcatraz_soul_steal::spell_arcatraz_soul_steal_AuraScript, spell_zereketh_seed_of_corruption, spell_commander_sarannis_arcane_devastation, spell_commander_sarannis_summon_reinforcements, spell_botanica_call_of_the_falcon::spell_botanica_call_of_the_falcon_AuraScript, spell_botanica_shift_form::spell_botanica_shift_form_AuraScript, spell_alar_flame_quills::spell_alar_flame_quills_AuraScript, spell_alar_ember_blast::spell_alar_ember_blast_SpellScript, spell_alar_ember_blast_death::spell_alar_ember_blast_death_AuraScript, spell_alar_dive_bomb::spell_alar_dive_bomb_AuraScript, spell_astromancer_wrath_of_the_astromancer::spell_astromancer_wrath_of_the_astromancer_AuraScript, spell_astromancer_solarian_transform::spell_astromancer_solarian_transform_AuraScript, spell_kaelthas_kael_phase_two::spell_kaelthas_kael_phase_two_SpellScript, spell_kaelthas_remote_toy::spell_kaelthas_remote_toy_AuraScript, spell_kaelthas_summon_weapons::spell_kaelthas_summon_weapons_SpellScript, spell_kaelthas_resurrection::spell_kaelthas_resurrection_SpellScript, spell_kaelthas_mind_control::spell_kaelthas_mind_control_SpellScript, spell_kaelthas_burn::spell_kaelthas_burn_AuraScript, spell_kaelthas_flame_strike::spell_kaelthas_flame_strike_AuraScript, spell_kaelthas_gravity_lapse::spell_kaelthas_gravity_lapse_SpellScript, spell_kaelthas_nether_beam::spell_kaelthas_nether_beam_SpellScript, spell_kaelthas_summon_nether_vapor::spell_kaelthas_summon_nether_vapor_SpellScript, spell_the_eye_countercharge::spell_the_eye_counterchargeScript, spell_capacitus_polarity_charge, spell_capacitus_polarity_charge_aura, spell_capacitus_polarity_shift, spell_ragin_flames_inferno, spell_npc22275_crystal_prison::spell_npc22275_crystal_prison_AuraScript, spell_oscillating_field::spell_oscillating_field_SpellScript, spell_q10935_the_exorcism_of_colonel_jules::spell_q10935_the_exorcism_of_colonel_jules_SpellScript, spell_q10190_battery_recharging_blaster, spell_q10190_battery_recharging_blaster_aura, spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript, spell_calling_korkron_or_wildhammer, spell_disrupt_summoning_ritual, spell_q10930_big_bone_worm::spell_q10930_big_bone_worm_SpellScript, spell_q10930_big_bone_worm::spell_q10930_big_bone_worm_AuraScript, spell_q10929_fumping::spell_q10929_fumping_SpellScript, spell_q10929_fumping::spell_q10929_fumping_AuraScript, spell_q10036_torgos::spell_q10036_torgos_SpellScript, spell_q10923_evil_draws_near_summon::spell_q10923_evil_draws_near_summon_SpellScript, spell_q10923_evil_draws_near_periodic::spell_q10923_evil_draws_near_periodic_AuraScript, spell_q10923_evil_draws_near_visual::spell_q10923_evil_draws_near_visual_SpellScript, spell_q10898_skywing::spell_q10898_skywing_SpellScript, spell_pet_dk_gargoyle_strike, spell_pet_gen_valkyr_guardian_smite, spell_dk_wandering_plague, spell_dk_raise_ally, spell_dk_raise_ally_trigger, spell_dk_aotd_taunt, spell_dk_death_and_decay, spell_dk_death_and_decay_aura, spell_dk_master_of_ghouls, spell_dk_chains_of_ice, spell_dk_chains_of_ice_aura, spell_dk_bloodworms, spell_dk_summon_gargoyle, spell_dk_improved_blood_presence_proc, spell_dk_wandering_plague_aura, spell_dk_rune_of_the_fallen_crusader, spell_dk_bone_shield, spell_dk_hungering_cold, spell_dk_blood_caked_blade, spell_dk_dancing_rune_weapon, spell_dk_dancing_rune_weapon_visual, spell_dk_scent_of_blood_trigger, spell_dk_pet_scaling, spell_dk_anti_magic_shell_raid, spell_dk_anti_magic_shell_self, spell_dk_anti_magic_zone, spell_dk_blood_boil, spell_dk_blood_gorged, spell_dk_corpse_explosion, spell_dk_death_coil, spell_dk_death_gate, spell_dk_death_grip, spell_dk_death_pact, spell_dk_death_strike, spell_dk_ghoul_explode, spell_dk_ghoul_thrash, spell_dk_icebound_fortitude, spell_dk_improved_blood_presence, spell_dk_improved_frost_presence, spell_dk_improved_unholy_presence, spell_dk_pestilence, spell_dk_presence, spell_dk_raise_dead, spell_dk_rune_tap_party, spell_dk_scent_of_blood, spell_dk_scourge_strike, spell_dk_spell_deflection, spell_dk_vampiric_blood, spell_dk_will_of_the_necropolis, spell_dru_bear_form_passive, spell_dru_t10_balance_4p_bonus, spell_dru_nurturing_instinct, spell_dru_feral_swiftness, spell_dru_omen_of_clarity, spell_dru_brambles_treant, spell_dru_barkskin, spell_dru_treant_scaling, spell_dru_dash, spell_dru_dash_aura, spell_dru_enrage, spell_dru_glyph_of_starfire, spell_dru_idol_lifebloom, spell_dru_innervate, spell_dru_lifebloom, spell_dru_living_seed, spell_dru_living_seed_proc, spell_dru_moonkin_form_passive, spell_dru_owlkin_frenzy, spell_dru_predatory_strikes, spell_dru_primal_tenacity, spell_dru_rip, spell_dru_savage_defense, spell_dru_savage_roar, spell_dru_savage_roar_aura, spell_dru_starfall_aoe, spell_dru_starfall_dummy, spell_dru_survival_instincts, spell_dru_survival_instincts_aura, spell_dru_swift_flight_passive, spell_dru_tiger_s_fury, spell_dru_typhoon, spell_dru_t10_restoration_4p_bonus, spell_dru_wild_growth, spell_dru_berserk, spell_dru_moonkin_form_passive_proc, spell_gen_5000_gold, spell_gen_model_visible, spell_the_flag_of_ownership, spell_gen_have_item_auras, spell_gen_mine_sweeper, spell_gen_reduced_above_60, spell_gen_reduced_above_60_aura, spell_gen_relocaste_dest, spell_gen_allow_proc_from_spells_with_cost, spell_gen_bg_preparation, spell_gen_disabled_above_level, spell_pet_hit_expertise_scalling, spell_gen_grow_flower_patch, spell_gen_rallying_cry_of_the_dragonslayer, spell_gen_adals_song_of_battle, spell_gen_disabled_above_63, spell_gen_black_magic_enchant, spell_gen_area_aura_select_players, spell_gen_select_target_count, spell_gen_use_spell_base_level_check, spell_gen_proc_from_direct_damage, spell_gen_no_offhand_proc, spell_gen_proc_on_self, spell_gen_proc_not_self, spell_gen_baby_murloc_passive, spell_gen_baby_murloc, spell_gen_fixate, spell_gen_fixate_aura, spell_gen_proc_above_75, spell_gen_periodic_knock_away, spell_gen_knock_away, spell_gen_mod_radius_by_caster_scale, spell_gen_proc_reduced_above_60, spell_gen_visual_dummy_stun, spell_gen_random_target32, spell_gen_hate_to_zero, spell_gen_focused_bursts, spell_gen_flurry_of_claws, spell_gen_throw_back, spell_gen_haunted, spell_gen_haunted_aura, spell_gen_absorb0_hitlimit1, spell_gen_adaptive_warding, spell_gen_av_drekthar_presence, spell_gen_burn_brutallus, spell_gen_cannibalize, spell_gen_clear_debuffs, spell_gen_create_lance, spell_gen_moss_covered_feet, spell_gen_netherbloom, spell_gen_nightmare_vine, spell_gen_obsidian_armor, spell_gen_parachute, spell_gen_pet_summoned, spell_gen_remove_flight_auras, spell_gen_elune_candle, spell_gen_feign_death_all_flags, spell_gen_feign_death_no_dyn_flag, spell_gen_feign_death_no_prevent_emotes, spell_gen_teleporting, spell_pvp_trinket_wotf_shared_cd, spell_gen_animal_blood, spell_spawn_blood_pool, spell_gen_divine_storm_cd_reset, spell_gen_profession_research, spell_gen_clone, spell_gen_clone_weapon, spell_gen_clone_weapon_aura, spell_gen_seaforium_blast, spell_gen_turkey_marker, spell_gen_lifeblood, spell_gen_allow_cast_from_item_only, spell_gen_vehicle_scaling, spell_gen_vehicle_scaling_aura, spell_gen_oracle_wolvar_reputation, spell_gen_damage_reduction_aura, spell_gen_dummy_trigger, spell_gen_spirit_healer_res, spell_gen_gadgetzan_transporter_backfire, spell_gen_gnomish_transporter, spell_gen_gryphon_wyvern_mount_check, spell_gen_dalaran_disguise, spell_gen_break_shield, spell_gen_mounted_charge, spell_gen_defend, spell_gen_throw_shield, spell_gen_tournament_duel, spell_gen_summon_tournament_mount, spell_gen_on_tournament_mount, spell_gen_tournament_pennant, spell_gen_ds_flush_knockback, spell_gen_count_pct_from_max_hp, spell_gen_despawn_self, spell_gen_bandage, spell_gen_paralytic_poison, spell_gen_prevent_emotes, spell_gen_blade_warding, spell_gen_lifebloom, spell_gen_summon_elemental, spell_gen_mount, spell_gen_upper_deck_create_foam_sword, spell_gen_bonked, spell_gen_gift_of_naaru, spell_gen_replenishment, spell_gen_replenishment_aura, spell_gen_spectator_cheer_trigger, spell_gen_vendor_bark_trigger, spell_gen_whisper_gulch_yogg_saron_whisper, spell_gen_eject_all_passengers, spell_gen_eject_passenger, spell_gen_charmed_unit_spell_cooldown, spell_contagion_of_rot, spell_silithyst, spell_gen_holiday_buff_food, spell_gen_arcane_charge, spell_gen_remove_impairing_auras, spell_gen_consume, spell_gen_apply_aura_after_expiration, spell_gen_basic_campfire, spell_freezing_circle, spell_gen_threshalisk_charge, spell_gen_shriveling_gaze, spell_gen_curse_of_pain, spell_gen_spirit_of_competition_participant, spell_gen_spirit_of_competition_winner, spell_gen_valthalak_amulet, spell_gen_planting_scourge_banner, spell_gen_jubling_cooldown, spell_gen_yehkinya_bramble, spell_gen_choking_vines, spell_hun_check_pet_los, spell_hun_cower, spell_hun_wyvern_sting, spell_hun_animal_handler, spell_hun_generic_scaling, spell_hun_taming_the_beast, spell_hun_aspect_of_the_beast, spell_hun_ascpect_of_the_viper, spell_hun_chimera_shot, spell_hun_improved_mend_pet, spell_hun_invigoration, spell_hun_last_stand_pet, spell_hun_masters_call, spell_hun_readiness, spell_hun_scatter_shot, spell_hun_sniper_training, spell_hun_pet_heart_of_the_phoenix, spell_hun_pet_carrion_feeder, spell_hun_misdirection, spell_hun_misdirection_proc, spell_hun_disengage, spell_hun_tame_beast, spell_hun_viper_attack_speed, spell_hun_glyph_of_arcane_shot, spell_hun_volley_trigger, spell_hun_lock_and_load, spell_hun_intimidation, spell_hun_bestial_wrath, spell_hun_target_self_and_pet, spell_item_massive_seaforium_charge, spell_item_titanium_seal_of_dalaran, spell_item_mind_amplify_dish, spell_item_runescroll_of_fortitude, spell_item_branns_communicator, spell_item_goblin_gumbo_kettle, spell_item_with_mount_speed, spell_item_magic_dust, spell_item_toy_train_set, spell_item_rocket_chicken, spell_item_sleepy_willy, spell_item_lil_phylactery, spell_item_shifting_naaru_silver, spell_item_toxic_wasteling, spell_item_lil_xt, spell_item_essence_of_life, spell_item_crazy_alchemists_potion, spell_item_skull_of_impeding_doom, spell_item_feast, spell_item_gnomish_universal_remote, spell_item_powerful_anti_venom, spell_item_strong_anti_venom, spell_item_anti_venom, spell_item_gnomish_shrink_ray, spell_item_goblin_weather_machine, spell_item_goblin_weather_machine_aura, spell_item_light_lamp, spell_item_fetch_ball, spell_item_oracle_ablutions, spell_item_trauma, spell_item_blade_ward_enchant, spell_item_blood_draining_enchant, spell_item_dragon_kite_summon_lightning_bunny, spell_item_enchanted_broom_periodic, spell_item_summon_or_dismiss, spell_item_draenic_pale_ale, spell_item_direbrew_remote, spell_item_direbrew_remote_aura, spell_item_eye_of_gruul_healing_discount, spell_item_summon_argent_knight, spell_item_instant_statue, spell_item_trigger_spell, spell_item_aegis_of_preservation, spell_item_arcane_shroud, spell_item_valanyr_hammer_of_ancient_kings, spell_item_brittle_armor, spell_item_blessing_of_ancient_kings, spell_item_defibrillate, spell_item_desperate_defense, spell_item_deviate_fish, spell_item_party_time, spell_item_echoes_of_light, spell_item_fate_rune_of_unsurpassed_vigor, spell_item_flask_of_the_north, spell_item_gnomish_death_ray, spell_item_make_a_wish, spell_item_mercurial_shield, spell_item_mingos_fortune_generator, spell_item_necrotic_touch, spell_item_net_o_matic, spell_item_noggenfogger_elixir, spell_item_piccolo_of_the_flaming_fire, spell_item_savory_deviate_delight, spell_item_scroll_of_recall, spell_item_dimensional_ripper_area52, spell_item_unsated_craving, spell_item_shadows_fate, spell_item_shadowmourne, spell_item_shadowmourne_soul_fragment, spell_item_six_demon_bag, spell_item_the_eye_of_diminution, spell_item_underbelly_elixir, spell_item_book_of_glyph_mastery, spell_item_map_of_the_geyser_fields, spell_item_vanquished_clutches, spell_item_ashbringer, spell_magic_eater_food, spell_item_shimmering_vessel, spell_item_purify_helboar_meat, spell_item_reindeer_transformation, spell_item_nigh_invulnerability, spell_item_poultryizer, spell_item_socrethars_stone, spell_item_demon_broiled_surprise, spell_item_complete_raptor_capture, spell_item_impale_leviroth, spell_item_brewfest_mount_transformation, spell_item_nitro_boots, spell_item_teach_language, spell_item_rocket_boots, spell_item_healing_injector, spell_item_mana_injector, spell_item_pygmy_oil, spell_item_unusual_compass, spell_item_chicken_cover, spell_item_refocus, spell_item_muisek_vessel, spell_item_greatmothers_soulcatcher, spell_item_eggnog, spell_item_goblin_bomb, spell_item_linken_boomerang, spell_item_recall, spell_item_wraith_scythe_drain_life, spell_item_mirrens_drinking_hat, spell_item_snowman, spell_item_freeze_rookery_egg, spell_item_green_whelp_armor, spell_item_elixir_of_shadows, spell_item_worn_troll_dice, spell_item_venomhide_feed, spell_item_scroll_of_retribution, spell_mage_arcane_blast, spell_mage_burning_determination, spell_mage_molten_armor, spell_mage_mirror_image, spell_mage_burnout, spell_mage_burnout_trigger, spell_mage_pet_scaling, spell_mage_brain_freeze, spell_mage_glyph_of_eternal_water, spell_mage_combustion_proc, spell_mage_blast_wave, spell_mage_cold_snap, spell_mage_fire_frost_ward, spell_mage_focus_magic, spell_mage_ice_barrier_aura, spell_mage_ice_barrier, spell_mage_ignite, spell_mage_living_bomb, spell_mage_mana_shield, spell_mage_master_of_elements, spell_mage_polymorph_cast_visual, spell_mage_summon_water_elemental, spell_pal_seal_of_command_aura, spell_pal_seal_of_command, spell_pal_divine_intervention, spell_pal_seal_of_light, spell_pal_sacred_shield_base, spell_pal_ardent_defender, spell_pal_avenging_wrath, spell_pal_blessing_of_faith, spell_pal_blessing_of_sanctuary, spell_pal_divine_sacrifice, spell_pal_divine_storm, spell_pal_divine_storm_dummy, spell_pal_exorcism_and_holy_wrath_damage, spell_pal_eye_for_an_eye, spell_pal_glyph_of_holy_light, spell_pal_guarded_by_the_light, spell_pal_hand_of_sacrifice_aura, spell_pal_hand_of_sacrifice, spell_pal_hand_of_salvation, spell_pal_holy_shock, spell_pal_judgement, spell_pal_judgement_of_command, spell_pal_lay_on_hands, spell_pal_righteous_defense, spell_pal_seal_of_righteousness, spell_pri_shadowfiend_scaling, spell_pri_circle_of_healing, spell_pri_divine_aegis, spell_pri_divine_hymn, spell_pri_glyph_of_prayer_of_healing, spell_pri_guardian_spirit, spell_pri_hymn_of_hope, spell_pri_item_greater_heal_refund, spell_pri_lightwell, spell_pri_lightwell_renew, spell_pri_mana_burn, spell_pri_mana_leech, spell_pri_mind_sear, spell_pri_pain_and_suffering_proc, spell_pri_penance, spell_pri_power_word_shield_aura, spell_pri_power_word_shield, spell_pri_prayer_of_mending_heal, spell_pri_renew, spell_pri_shadow_word_death, spell_pri_vampiric_touch, spell_pri_mind_control, spell_pri_t4_4p_bonus, spell_q11065_wrangle_some_aether_rays, spell_q11065_wrangle_some_aether_rays_aura, spell_image_of_drakuru_reagent_check, spell_q12014_steady_as_a_rock, spell_q11026_a11051_banish_the_demons_aura, spell_q11026_a11051_banish_the_demons, spell_q10525_vision_guide, spell_q11322_q11317_the_cleansing, spell_q10714_on_spirits_wings, spell_q10720_the_smallest_creature, spell_q13086_last_line_of_defence, spell_q12943_shadow_vault_decree, spell_q10769_dissension_amongst_the_ranks_aura, spell_q10769_dissension_amongst_the_ranks, spell_q11520_discovering_your_roots, spell_quest_dragonmaw_race_generic, spell_q11670_it_was_the_orcs_honest, spell_quest_test_flight_charging, spell_q12274_a_fall_from_grace_costume, spell_q13369_fate_up_against_your_will, spell_q11198_take_down_tethyr, spell_q11653_youre_not_so_big_now, spell_q10985_light_of_the_naaru, spell_generic_quest_update_entry_SpellScript, spell_q1846_bending_shinbone, spell_q2203_thaumaturgy_channel, spell_q5206_test_fetid_skull, spell_q6124_6129_apply_salve, spell_q11396_11399_force_shield_arcane_purple_x3, spell_q11396_11399_scourging_crystal_controller, spell_q11396_11399_scourging_crystal_controller_dummy, spell_q11587_arcane_prisoner_rescue, spell_q11730_ultrasonic_screwdriver, spell_q12459_seeds_of_natures_wrath, spell_q12634_despawn_fruit_tosser, spell_q12683_take_sputum_sample, spell_q12851_going_bearback, spell_q12937_relief_for_the_fallen, spell_q10041_q10040_who_are_they, spell_symbol_of_life_dummy, spell_q12659_ahunaes_knife, spell_q9874_liquid_fire, spell_q12805_lifeblood_dummy, spell_q13280_13283_plant_battle_standard, spell_q14112_14145_chum_the_water, spell_q9452_cast_net, spell_q12987_read_pronouncement, spell_q12277_wintergarde_mine_explosion, spell_q12066_bunny_kill_credit, spell_q12735_song_of_cleansing, spell_q11010_q11102_q11023_aggro_check_aura, spell_q11010_q11102_q11023_aggro_check, spell_q11010_q11102_q11023_aggro_burst, spell_q11010_q11102_q11023_choose_loc, spell_q11010_q11102_q11023_q11008_check_fly_mount, spell_q12661_q12669_q12676_q12677_q12713_summon_stefan, spell_q12730_quenching_mist, spell_q13291_q13292_q13239_q13261_frostbrood_skytalon_grab_decoy, spell_q13291_q13292_q13239_q13261_armored_decoy_summon_skytalon, spell_q13011_bear_flank_master, spell_q12690_burst_at_the_seams, spell_q12308_escape_from_silverbrook, spell_q12308_escape_from_silverbrook_summon_worgen, spell_q12641_death_comes_from_on_high, spell_q12619_emblazon_runeblade, spell_q12619_emblazon_runeblade_effect, spell_q12919_gymers_grab, spell_q12919_gymers_throw, spell_q9718_crow_transform, spell_q5056_summon_shy_rotam, spell_q4735_collect_rookery_egg, spell_q10651_q10692_book_of_fel_names, spell_q9847_a_spirit_ally, spell_rog_savage_combat, spell_rog_combat_potency, spell_rog_blade_flurry, spell_rog_cheat_death, spell_rog_deadly_poison, spell_rog_killing_spree::spell_rog_killing_spree_SpellScript, spell_rog_killing_spree::spell_rog_killing_spree_AuraScript, spell_rog_nerves_of_steel, spell_rog_preparation, spell_rog_prey_on_the_weak, spell_rog_rupture, spell_rog_shiv, spell_rog_tricks_of_the_trade, spell_rog_tricks_of_the_trade_proc, spell_rog_pickpocket, spell_sha_totem_of_wrath, spell_sha_spirit_walk, spell_sha_t10_restoration_4p_bonus, spell_sha_totemic_mastery, spell_sha_feral_spirit_scaling, spell_sha_fire_elemental_scaling, spell_sha_ancestral_awakening_proc, spell_sha_astral_shift, spell_sha_bloodlust, spell_sha_chain_heal, spell_sha_cleansing_totem_pulse, spell_sha_earth_shield, spell_sha_earthbind_totem, spell_sha_earthen_power, spell_sha_earthliving_weapon, spell_sha_fire_nova, spell_sha_flame_shock, spell_sha_healing_stream_totem, spell_sha_heroism, spell_sha_item_lightning_shield, spell_sha_item_lightning_shield_trigger, spell_sha_item_mana_surge, spell_sha_item_t10_elemental_2p_bonus, spell_sha_lava_lash, spell_sha_mana_spring_totem, spell_sha_mana_tide_totem, spell_sha_sentry_totem, spell_sha_thunderstorm, spell_sha_flurry_proc, spell_sha_t8_electrified, spell_warl_eye_of_kilrogg, spell_warl_shadowflame, spell_warl_seduction, spell_warl_improved_demonic_tactics, spell_warl_ritual_of_summoning, spell_warl_demonic_aegis, spell_warl_demonic_knowledge, spell_warl_generic_scaling, spell_warl_infernal_scaling, spell_warl_banish, spell_warl_demonic_empowerment, spell_warl_create_healthstone, spell_warl_everlasting_affliction, spell_warl_ritual_of_doom_effect, spell_warl_seed_of_corruption, spell_warl_soulshatter, spell_warl_siphon_life, spell_warl_life_tap, spell_warl_demonic_circle_summon, spell_warl_demonic_circle_teleport, spell_warl_fel_synergy, spell_warl_haunt, spell_warl_haunt_aura, spell_warl_unstable_affliction, spell_warl_curse_of_doom, spell_warl_health_funnel, spell_warl_shadow_ward, spell_warl_glyph_of_shadowflame, spell_warl_drain_soul, spell_warl_shadowburn, spell_warl_glyph_of_felguard, spell_warl_glyph_of_voidwalker, spell_warr_mocking_blow, spell_warr_victory_rush, spell_warr_intervene, spell_warr_improved_spell_reflection, spell_warr_improved_spell_reflection_trigger, spell_warr_improved_spell_reflection_trigger_aura, spell_warr_last_stand, spell_warr_deep_wounds, spell_warr_charge, spell_warr_slam, spell_warr_damage_shield, spell_warr_execute, spell_warr_concussion_blow, spell_warr_bloodthirst, spell_warr_bloodthirst_heal, spell_warr_overpower, spell_warr_intimidating_shout, spell_warr_rend, spell_warr_shattering_throw, spell_warr_sweeping_strikes, spell_warr_vigilance, spell_warr_vigilance_trigger, spell_warr_glyph_of_sunder_armor, spell_warr_t3_prot_8p_bonus, spell_warr_retaliation, spell_dream_fog_sleep::spell_dream_fog_sleep_SpellScript, spell_shadow_bolt_whirl, and spell_mark_of_nature::spell_mark_of_nature_SpellScript.
Referenced by _Register().
Unload()
virtual void _SpellScript::Unload () inline virtual
Reimplemented in spell_garfrost_permafrost::spell_garfrost_permafrost_SpellScript.
{}
Referenced by _Unload().
Validate()
virtual bool _SpellScript::Validate (SpellInfo const *) inline virtual
Reimplemented in spell_gyth_chromatic_protection, spell_gen_elemental_shield, spell_gen_brood_power, spell_class_call_handler, aura_class_call_wild_magic, aura_class_call_siphon_blessing, spell_corrupted_totems, spell_shadowblink, spell_spawn_drakonid, spell_vael_burning_adrenaline, spell_bwl_shadowflame::spell_bwl_shadowflame_SpellScript, spell_geddon_inferno::spell_geddon_inferno_AuraScript, spell_garr_separation_nexiety::spell_garr_separation_nexiety_AuraScript, spell_garr_frenzy::spell_garr_frenzy_SpellScript, spell_magmadar_lava_bomb::spell_magmadar_lava_bomb_SpellScript, spell_majordomo_separation_nexiety::spell_majordomo_separation_nexiety_AuraScript, spell_ragnaros_lava_burst_randomizer, spell_ragnaros_summon_sons_of_flame, spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript, spell_flamewreath, spell_flamewreath_aura, spell_kormok_summon_bone_mages, spell_kormok_summon_bone_minions, spell_apothecary_validate_area, spell_apothecary_throw_cologne, spell_apothecary_throw_perfume, spell_apothecary_perfume_spill, spell_apothecary_cologne_spill, spell_razelikh_teleport_group::spell_razelikh_teleport_group_SpellScript, spell_blight_worm_ingest::spell_blight_worm_ingest_SpellScript, spell_hexlord_unstable_affliction::spell_hexlord_unstable_affliction_AuraScript, spell_blood_siphon, spell_batrider_bomb, spell_delusions_of_jindo, spell_direbrew_summon_mole_machine_target_picker, spell_request_second_mug, spell_send_mug_control_aura, spell_direbrew_disarm, spell_item_create_heart_candy, spell_gen_aura_service_uniform, spell_gen_crab_disguise, spell_midsummer_fling_torch, spell_midsummer_juggling_torch, spell_midsummer_torch_catch, spell_winter_veil_mistletoe, spell_arcane_vacuum, spell_mark_of_frost_freeze, spell_mark_of_kazrogal::spell_mark_of_kazrogal_AuraScript, spell_ayamiss_swarmer_teleport_trigger, spell_ayamiss_swarmer_start_loop, spell_ooze_zap::spell_ooze_zap_SpellScript, spell_ooze_zap_channel_end::spell_ooze_zap_channel_end_SpellScript, spell_energize_aoe::spell_energize_aoe_SpellScript, spell_volazj_whisper, spell_prince_taldaram_conjure_flame_sphere, spell_gen_leeching_swarm::spell_gen_leeching_swarm_AuraScript, spell_faction_champion_warl_unstable_affliction::spell_faction_champion_warl_unstable_affliction_AuraScript, spell_blood_queen_pact_of_the_darkfallen_dmg::spell_blood_queen_pact_of_the_darkfallen_dmg_AuraScript, spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript, spell_blood_queen_essence_of_the_blood_queen::spell_blood_queen_essence_of_the_blood_queen_AuraScript, spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript, spell_festergut_blighted_spores::spell_festergut_blighted_spores_AuraScript, spell_festergut_gastric_bloat::spell_festergut_gastric_bloat_SpellScript, spell_igb_rocket_pack::spell_igb_rocket_pack_AuraScript, spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript, spell_rotface_unstable_ooze_explosion_init::spell_rotface_unstable_ooze_explosion_init_SpellScript, spell_sindragosa_unchained_magic::spell_sindragosa_unchained_magic_AuraScript, spell_sindragosa_instability::spell_sindragosa_instability_AuraScript, spell_sindragosa_icy_grip::spell_sindragosa_icy_grip_SpellScript, spell_sindragosa_frost_beacon::spell_sindragosa_frost_beacon_AuraScript, spell_sindragosa_ice_tomb::spell_sindragosa_ice_tomb_SpellScript, spell_rimefang_icy_blast::spell_rimefang_icy_blast_SpellScript, spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript, spell_the_lich_king_play_movie::spell_the_lich_king_play_movie_SpellScript, spell_the_lich_king_necrotic_plague::spell_the_lich_king_necrotic_plague_AuraScript, spell_the_lich_king_ice_burst_target_search::spell_the_lich_king_ice_burst_target_search_SpellScript, spell_the_lich_king_soul_reaper::spell_the_lich_king_soul_reaper_AuraScript, spell_the_lich_king_life_siphon::spell_the_lich_king_life_siphon_SpellScript, spell_the_lich_king_dark_hunger::spell_the_lich_king_dark_hunger_AuraScript, spell_trigger_spell_from_caster::spell_trigger_spell_from_caster_SpellScript, spell_grobbulus_mutating_injection::spell_grobbulus_mutating_injection_AuraScript, spell_kelthuzad_detonate_mana::spell_kelthuzad_detonate_mana_AuraScript, spell_thaddius_polarity_shift::spell_thaddius_polarity_shift_SpellScript, spell_oculus_stop_time::spell_oculus_stop_time_AuraScript, spell_oculus_evasive_maneuvers::spell_oculus_evasive_maneuvers_AuraScript, spell_oculus_shock_lance::spell_oculus_shock_lance_SpellScript, spell_oculus_temporal_rift::spell_oculus_temporal_rift_AuraScript, spell_yogg_saron_grim_reprisal::spell_yogg_saron_grim_reprisal_AuraScript, spell_ticking_time_bomb::spell_ticking_time_bomb_AuraScript, spell_utgarde_pinnacle_beast_mark, spell_koralon_meteor_fists::spell_koralon_meteor_fists_AuraScript, spell_flame_warder_meteor_fists::spell_flame_warder_meteor_fists_AuraScript, spell_q12227_outhouse_groans, spell_q12227_camera_shake, spell_vehicle_warhead_fuse::spell_vehicle_warhead_fuse_SpellScript, spell_warhead_detonate::spell_warhead_detonate_SpellScript, spell_frog_kiss, spell_deliver_gryphon, spell_close_rift::spell_close_rift_AuraScript, spell_wintergrasp_force_building::spell_wintergrasp_force_building_SpellScript, spell_talon_king_ikiss_blink, spell_shockwave_knockback, spell_mark_of_malice, spell_mark_of_kazzak::spell_mark_of_kazzak_AuraScript, spell_the_black_stalker_levitate, spell_the_black_stalker_levitation_pulse, spell_the_black_stalker_someone_grab_me, spell_the_black_stalker_magnetic_pull, spell_gruul_ground_slam, spell_gruul_ground_slam_trigger, spell_gruul_shatter, spell_blade_dance_targeting, spell_zereketh_seed_of_corruption, spell_commander_sarannis_arcane_devastation, spell_commander_sarannis_summon_reinforcements, spell_dk_anti_magic_shell_self, spell_dk_anti_magic_zone, spell_dk_blood_boil, spell_dk_blood_gorged, spell_dk_corpse_explosion, spell_dk_death_coil, spell_dk_death_strike, spell_dk_ghoul_explode, spell_dk_ghoul_thrash, spell_dk_improved_blood_presence, spell_dk_improved_frost_presence, spell_dk_improved_unholy_presence, spell_dk_presence, spell_dk_raise_dead, spell_dk_scent_of_blood, spell_dk_scourge_strike, spell_dru_bear_form_passive, spell_dru_enrage, spell_dru_glyph_of_starfire, spell_dru_lifebloom, spell_dru_living_seed, spell_dru_living_seed_proc, spell_dru_savage_roar_aura, spell_dru_survival_instincts_aura, spell_gen_mine_sweeper, spell_gen_adaptive_warding, spell_gen_cannibalize, spell_gen_create_lance, spell_gen_moss_covered_feet, spell_gen_netherbloom, spell_gen_nightmare_vine, spell_gen_obsidian_armor, spell_gen_parachute, spell_gen_elune_candle, spell_gen_teleporting, spell_pvp_trinket_wotf_shared_cd, spell_gen_animal_blood, spell_gen_divine_storm_cd_reset, spell_gen_clone_weapon_aura, spell_gen_seaforium_blast, spell_gen_turkey_marker, spell_gen_damage_reduction_aura, spell_gen_dummy_trigger, spell_gen_dalaran_disguise, spell_gen_defend, spell_gen_tournament_duel, spell_gen_summon_tournament_mount, spell_gen_on_tournament_mount, spell_gen_bandage, spell_gen_paralytic_poison, spell_gen_blade_warding, spell_gen_lifebloom, spell_gen_summon_elemental, spell_gen_mount, spell_gen_bonked, spell_gen_replenishment, spell_gen_whisper_gulch_yogg_saron_whisper, spell_gen_holiday_buff_food, spell_gen_consume, spell_gen_apply_aura_after_expiration, spell_freezing_circle, spell_gen_threshalisk_charge, spell_gen_shriveling_gaze, spell_gen_curse_of_pain, spell_gen_spirit_of_competition_participant, spell_gen_spirit_of_competition_winner, spell_gen_jubling_cooldown, spell_gen_choking_vines, spell_hun_aspect_of_the_beast, spell_hun_ascpect_of_the_viper, spell_hun_chimera_shot, spell_hun_improved_mend_pet, spell_hun_invigoration, spell_hun_last_stand_pet, spell_hun_masters_call, spell_hun_sniper_training, spell_hun_pet_heart_of_the_phoenix, spell_hun_pet_carrion_feeder, spell_hun_misdirection, spell_hun_viper_attack_speed, spell_hun_glyph_of_arcane_shot, spell_hun_lock_and_load, spell_item_with_mount_speed, spell_item_eye_of_gruul_healing_discount, spell_item_instant_statue, spell_item_trigger_spell, spell_item_aegis_of_preservation, spell_item_blessing_of_ancient_kings, spell_item_defibrillate, spell_item_desperate_defense, spell_item_deviate_fish, spell_item_fate_rune_of_unsurpassed_vigor, spell_item_flask_of_the_north, spell_item_gnomish_death_ray, spell_item_make_a_wish, spell_item_mingos_fortune_generator, spell_item_necrotic_touch, spell_item_net_o_matic, spell_item_noggenfogger_elixir, spell_item_savory_deviate_delight, spell_item_shadowmourne, spell_item_shadowmourne_soul_fragment, spell_item_six_demon_bag, spell_item_underbelly_elixir, spell_item_vanquished_clutches, spell_item_purify_helboar_meat, spell_item_reindeer_transformation, spell_item_nigh_invulnerability, spell_item_poultryizer, spell_item_socrethars_stone, spell_item_demon_broiled_surprise, spell_item_complete_raptor_capture, spell_item_impale_leviroth, spell_item_brewfest_mount_transformation, spell_item_nitro_boots, spell_item_teach_language, spell_item_rocket_boots, spell_item_pygmy_oil, spell_item_chicken_cover, spell_item_eggnog, spell_item_goblin_bomb, spell_item_worn_troll_dice, spell_mage_burnout, spell_mage_combustion_proc, spell_mage_incanters_absorbtion_base_AuraScript, spell_mage_blast_wave, spell_mage_fire_frost_ward, spell_mage_focus_magic, spell_mage_ignite, spell_mage_master_of_elements, spell_mage_polymorph_cast_visual, spell_pal_ardent_defender, spell_pal_avenging_wrath, spell_pal_blessing_of_faith, spell_pal_blessing_of_sanctuary, spell_pal_divine_storm, spell_pal_divine_storm_dummy, spell_pal_eye_for_an_eye, spell_pal_guarded_by_the_light, spell_pal_judgement, spell_pal_lay_on_hands, spell_pal_righteous_defense, spell_pal_seal_of_righteousness, spell_pri_circle_of_healing, spell_pri_divine_aegis, spell_pri_glyph_of_prayer_of_healing, spell_pri_guardian_spirit, spell_pri_item_greater_heal_refund, spell_pri_mana_leech, spell_pri_power_word_shield_aura, spell_pri_prayer_of_mending_heal, spell_pri_renew, spell_pri_vampiric_touch, spell_pri_t4_4p_bonus, spell_q2203_thaumaturgy_channel, spell_q5206_test_fetid_skull, spell_q11396_11399_scourging_crystal_controller, spell_q11396_11399_scourging_crystal_controller_dummy, spell_q11587_arcane_prisoner_rescue, spell_q11730_ultrasonic_screwdriver, spell_q12634_despawn_fruit_tosser, spell_q12937_relief_for_the_fallen, spell_q10041_q10040_who_are_they, spell_q14112_14145_chum_the_water, spell_q12730_quenching_mist, spell_q13291_q13292_q13239_q13261_frostbrood_skytalon_grab_decoy, spell_q13011_bear_flank_master, spell_q12690_burst_at_the_seams, spell_q12308_escape_from_silverbrook, spell_q12641_death_comes_from_on_high, spell_q12919_gymers_grab, spell_rog_blade_flurry, spell_rog_cheat_death, spell_rog_killing_spree::spell_rog_killing_spree_SpellScript, spell_rog_killing_spree::spell_rog_killing_spree_AuraScript, spell_rog_preparation, spell_rog_prey_on_the_weak, spell_rog_shiv, spell_rog_tricks_of_the_trade, spell_sha_ancestral_awakening_proc, spell_sha_bloodlust, spell_sha_cleansing_totem_pulse, spell_sha_earth_shield, spell_sha_earthbind_totem, spell_sha_earthliving_weapon, spell_sha_flame_shock, spell_sha_healing_stream_totem, spell_sha_heroism, spell_sha_item_lightning_shield, spell_sha_item_lightning_shield_trigger, spell_sha_item_mana_surge, spell_sha_item_t10_elemental_2p_bonus, spell_sha_mana_spring_totem, spell_sha_mana_tide_totem, spell_sha_sentry_totem, spell_sha_t8_electrified, spell_warl_demonic_empowerment, spell_warl_create_healthstone, spell_warl_soulshatter, spell_warl_siphon_life, spell_warl_life_tap, spell_warl_demonic_circle_summon, spell_warl_demonic_circle_teleport, spell_warl_fel_synergy, spell_warl_haunt_aura, spell_warl_unstable_affliction, spell_warl_curse_of_doom, spell_warl_health_funnel, spell_warl_glyph_of_shadowflame, spell_warl_drain_soul, spell_warr_intervene, spell_warr_improved_spell_reflection, spell_warr_improved_spell_reflection_trigger, spell_warr_last_stand, spell_warr_deep_wounds, spell_warr_charge, spell_warr_slam, spell_warr_damage_shield, spell_warr_execute, spell_warr_bloodthirst, spell_warr_overpower, spell_warr_sweeping_strikes, spell_warr_vigilance, spell_warr_vigilance_trigger, spell_warr_retaliation, spell_shadow_bolt_whirl, spell_mark_of_nature::spell_mark_of_nature_SpellScript, spell_deathwhisper_dark_reckoning, spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript, spell_mage_living_bomb, spell_dragonblight_corrosive_spit, spell_broggok_poison_cloud, spell_dk_will_of_the_necropolis, spell_dru_wild_growth, spell_gen_eject_passenger, spell_pal_holy_shock, spell_pri_penance, and spell_sha_fire_nova.
{ return true; }
Referenced by _Validate().
ValidateSpellInfo() [1/2]
static bool _SpellScript::ValidateSpellInfo (std::initializer_list< uint32 > spellIds) inline static
    {
        return _ValidateSpellInfo(spellIds.begin(), spellIds.end());
    }
References _ValidateSpellInfo().
Referenced by spell_midsummer_ribbon_pole::PrepareAuraScript(), spell_mount_check::spell_mount_check_AuraScript::PrepareAuraScript(), spell_gen_break_shield::PrepareSpellScript(), spell_gen_gadgetzan_transporter_backfire::PrepareSpellScript(), spell_gen_gnomish_transporter::PrepareSpellScript(), spell_gen_mounted_charge::PrepareSpellScript(), spell_item_linken_boomerang::PrepareSpellScript(), spell_mage_summon_water_elemental::PrepareSpellScript(), spell_q12274_a_fall_from_grace_costume::PrepareSpellScript(), spell_voljin_war_drums::spell_voljin_war_drums_SpellScript::PrepareSpellScript(), spell_voodoo::spell_voodoo_SpellScript::PrepareSpellScript(), spell_gyth_chromatic_protection::Validate(), spell_gen_elemental_shield::Validate(), spell_gen_brood_power::Validate(), spell_class_call_handler::Validate(), aura_class_call_wild_magic::Validate(), aura_class_call_siphon_blessing::Validate(), spell_corrupted_totems::Validate(), spell_shadowblink::Validate(), spell_spawn_drakonid::Validate(), spell_vael_burning_adrenaline::Validate(), spell_bwl_shadowflame::spell_bwl_shadowflame_SpellScript::Validate(), spell_geddon_inferno::spell_geddon_inferno_AuraScript::Validate(), spell_garr_separation_nexiety::spell_garr_separation_nexiety_AuraScript::Validate(), spell_garr_frenzy::spell_garr_frenzy_SpellScript::Validate(), spell_magmadar_lava_bomb::spell_magmadar_lava_bomb_SpellScript::Validate(), spell_majordomo_separation_nexiety::spell_majordomo_separation_nexiety_AuraScript::Validate(), spell_ragnaros_lava_burst_randomizer::Validate(), spell_ragnaros_summon_sons_of_flame::Validate(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::Validate(), spell_flamewreath::Validate(), spell_flamewreath_aura::Validate(), spell_kormok_summon_bone_mages::Validate(), spell_kormok_summon_bone_minions::Validate(), spell_apothecary_validate_area::Validate(), spell_apothecary_throw_cologne::Validate(), spell_apothecary_throw_perfume::Validate(), spell_apothecary_perfume_spill::Validate(), spell_apothecary_cologne_spill::Validate(), spell_razelikh_teleport_group::spell_razelikh_teleport_group_SpellScript::Validate(), spell_blight_worm_ingest::spell_blight_worm_ingest_SpellScript::Validate(), spell_hexlord_unstable_affliction::spell_hexlord_unstable_affliction_AuraScript::Validate(), spell_blood_siphon::Validate(), spell_batrider_bomb::Validate(), spell_delusions_of_jindo::Validate(), spell_direbrew_summon_mole_machine_target_picker::Validate(), spell_request_second_mug::Validate(), spell_send_mug_control_aura::Validate(), spell_direbrew_disarm::Validate(), spell_item_create_heart_candy::Validate(), spell_gen_aura_service_uniform::Validate(), spell_gen_crab_disguise::Validate(), spell_midsummer_fling_torch::Validate(), spell_midsummer_juggling_torch::Validate(), spell_midsummer_torch_catch::Validate(), spell_winter_veil_mistletoe::Validate(), spell_arcane_vacuum::Validate(), spell_mark_of_frost_freeze::Validate(), spell_mark_of_kazrogal::spell_mark_of_kazrogal_AuraScript::Validate(), spell_ayamiss_swarmer_teleport_trigger::Validate(), spell_ayamiss_swarmer_start_loop::Validate(), spell_ooze_zap::spell_ooze_zap_SpellScript::Validate(), spell_ooze_zap_channel_end::spell_ooze_zap_channel_end_SpellScript::Validate(), spell_energize_aoe::spell_energize_aoe_SpellScript::Validate(), spell_volazj_whisper::Validate(), spell_prince_taldaram_conjure_flame_sphere::Validate(), spell_gen_leeching_swarm::spell_gen_leeching_swarm_AuraScript::Validate(), spell_faction_champion_warl_unstable_affliction::spell_faction_champion_warl_unstable_affliction_AuraScript::Validate(), spell_blood_queen_pact_of_the_darkfallen_dmg::spell_blood_queen_pact_of_the_darkfallen_dmg_AuraScript::Validate(), spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::Validate(), spell_blood_queen_essence_of_the_blood_queen::spell_blood_queen_essence_of_the_blood_queen_AuraScript::Validate(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::Validate(), spell_festergut_blighted_spores::spell_festergut_blighted_spores_AuraScript::Validate(), spell_festergut_gastric_bloat::spell_festergut_gastric_bloat_SpellScript::Validate(), spell_igb_rocket_pack::spell_igb_rocket_pack_AuraScript::Validate(), spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::Validate(), spell_rotface_unstable_ooze_explosion_init::spell_rotface_unstable_ooze_explosion_init_SpellScript::Validate(), spell_sindragosa_instability::spell_sindragosa_instability_AuraScript::Validate(), spell_sindragosa_icy_grip::spell_sindragosa_icy_grip_SpellScript::Validate(), spell_sindragosa_frost_beacon::spell_sindragosa_frost_beacon_AuraScript::Validate(), spell_rimefang_icy_blast::spell_rimefang_icy_blast_SpellScript::Validate(), spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript::Validate(), spell_the_lich_king_necrotic_plague::spell_the_lich_king_necrotic_plague_AuraScript::Validate(), spell_the_lich_king_ice_burst_target_search::spell_the_lich_king_ice_burst_target_search_SpellScript::Validate(), spell_the_lich_king_soul_reaper::spell_the_lich_king_soul_reaper_AuraScript::Validate(), spell_the_lich_king_life_siphon::spell_the_lich_king_life_siphon_SpellScript::Validate(), spell_the_lich_king_dark_hunger::spell_the_lich_king_dark_hunger_AuraScript::Validate(), spell_trigger_spell_from_caster::spell_trigger_spell_from_caster_SpellScript::Validate(), spell_grobbulus_mutating_injection::spell_grobbulus_mutating_injection_AuraScript::Validate(), spell_kelthuzad_detonate_mana::spell_kelthuzad_detonate_mana_AuraScript::Validate(), spell_thaddius_polarity_shift::spell_thaddius_polarity_shift_SpellScript::Validate(), spell_oculus_stop_time::spell_oculus_stop_time_AuraScript::Validate(), spell_oculus_evasive_maneuvers::spell_oculus_evasive_maneuvers_AuraScript::Validate(), spell_oculus_shock_lance::spell_oculus_shock_lance_SpellScript::Validate(), spell_oculus_temporal_rift::spell_oculus_temporal_rift_AuraScript::Validate(), spell_yogg_saron_grim_reprisal::spell_yogg_saron_grim_reprisal_AuraScript::Validate(), spell_ticking_time_bomb::spell_ticking_time_bomb_AuraScript::Validate(), spell_utgarde_pinnacle_beast_mark::Validate(), spell_koralon_meteor_fists::spell_koralon_meteor_fists_AuraScript::Validate(), spell_flame_warder_meteor_fists::spell_flame_warder_meteor_fists_AuraScript::Validate(), spell_q12227_outhouse_groans::Validate(), spell_q12227_camera_shake::Validate(), spell_frog_kiss::Validate(), spell_deliver_gryphon::Validate(), spell_close_rift::spell_close_rift_AuraScript::Validate(), spell_wintergrasp_force_building::spell_wintergrasp_force_building_SpellScript::Validate(), spell_shockwave_knockback::Validate(), spell_mark_of_malice::Validate(), spell_mark_of_kazzak::spell_mark_of_kazzak_AuraScript::Validate(), spell_the_black_stalker_levitate::Validate(), spell_the_black_stalker_levitation_pulse::Validate(), spell_the_black_stalker_someone_grab_me::Validate(), spell_the_black_stalker_magnetic_pull::Validate(), spell_gruul_ground_slam::Validate(), spell_gruul_ground_slam_trigger::Validate(), spell_gruul_shatter::Validate(), spell_blade_dance_targeting::Validate(), spell_zereketh_seed_of_corruption::Validate(), spell_commander_sarannis_arcane_devastation::Validate(), spell_commander_sarannis_summon_reinforcements::Validate(), spell_dk_anti_magic_shell_self::Validate(), spell_dk_anti_magic_zone::Validate(), spell_dk_blood_boil::Validate(), spell_dk_blood_gorged::Validate(), spell_dk_corpse_explosion::Validate(), spell_dk_death_coil::Validate(), spell_dk_death_strike::Validate(), spell_dk_ghoul_explode::Validate(), spell_dk_ghoul_thrash::Validate(), spell_dk_improved_blood_presence::Validate(), spell_dk_improved_frost_presence::Validate(), spell_dk_improved_unholy_presence::Validate(), spell_dk_presence::Validate(), spell_dk_raise_dead::Validate(), spell_dk_scent_of_blood::Validate(), spell_dk_scourge_strike::Validate(), spell_dru_bear_form_passive::Validate(), spell_dru_enrage::Validate(), spell_dru_glyph_of_starfire::Validate(), spell_dru_lifebloom::Validate(), spell_dru_living_seed::Validate(), spell_dru_living_seed_proc::Validate(), spell_dru_savage_roar_aura::Validate(), spell_dru_survival_instincts_aura::Validate(), spell_gen_mine_sweeper::Validate(), spell_gen_adaptive_warding::Validate(), spell_gen_cannibalize::Validate(), spell_gen_create_lance::Validate(), spell_gen_moss_covered_feet::Validate(), spell_gen_nightmare_vine::Validate(), spell_gen_obsidian_armor::Validate(), spell_gen_parachute::Validate(), spell_gen_elune_candle::Validate(), spell_gen_teleporting::Validate(), spell_pvp_trinket_wotf_shared_cd::Validate(), spell_gen_animal_blood::Validate(), spell_gen_divine_storm_cd_reset::Validate(), spell_gen_clone_weapon_aura::Validate(), spell_gen_seaforium_blast::Validate(), spell_gen_turkey_marker::Validate(), spell_gen_damage_reduction_aura::Validate(), spell_gen_dummy_trigger::Validate(), spell_gen_dalaran_disguise::Validate(), spell_gen_defend::Validate(), spell_gen_tournament_duel::Validate(), spell_gen_summon_tournament_mount::Validate(), spell_gen_on_tournament_mount::Validate(), spell_gen_bandage::Validate(), spell_gen_blade_warding::Validate(), spell_gen_lifebloom::Validate(), spell_gen_summon_elemental::Validate(), spell_gen_bonked::Validate(), spell_gen_replenishment::Validate(), spell_gen_whisper_gulch_yogg_saron_whisper::Validate(), spell_gen_holiday_buff_food::Validate(), spell_gen_consume::Validate(), spell_gen_apply_aura_after_expiration::Validate(), spell_freezing_circle::Validate(), spell_gen_threshalisk_charge::Validate(), spell_gen_shriveling_gaze::Validate(), spell_gen_curse_of_pain::Validate(), spell_gen_spirit_of_competition_participant::Validate(), spell_gen_spirit_of_competition_winner::Validate(), spell_gen_jubling_cooldown::Validate(), spell_gen_choking_vines::Validate(), spell_hun_aspect_of_the_beast::Validate(), spell_hun_ascpect_of_the_viper::Validate(), spell_hun_chimera_shot::Validate(), spell_hun_improved_mend_pet::Validate(), spell_hun_invigoration::Validate(), spell_hun_last_stand_pet::Validate(), spell_hun_masters_call::Validate(), spell_hun_sniper_training::Validate(), spell_hun_pet_heart_of_the_phoenix::Validate(), spell_hun_pet_carrion_feeder::Validate(), spell_hun_misdirection::Validate(), spell_hun_viper_attack_speed::Validate(), spell_hun_glyph_of_arcane_shot::Validate(), spell_hun_lock_and_load::Validate(), spell_item_eye_of_gruul_healing_discount::Validate(), spell_item_instant_statue::Validate(), spell_item_trigger_spell::Validate(), spell_item_aegis_of_preservation::Validate(), spell_item_blessing_of_ancient_kings::Validate(), spell_item_desperate_defense::Validate(), spell_item_deviate_fish::Validate(), spell_item_fate_rune_of_unsurpassed_vigor::Validate(), spell_item_flask_of_the_north::Validate(), spell_item_gnomish_death_ray::Validate(), spell_item_make_a_wish::Validate(), spell_item_mingos_fortune_generator::Validate(), spell_item_necrotic_touch::Validate(), spell_item_net_o_matic::Validate(), spell_item_noggenfogger_elixir::Validate(), spell_item_shadowmourne::Validate(), spell_item_shadowmourne_soul_fragment::Validate(), spell_item_six_demon_bag::Validate(), spell_item_underbelly_elixir::Validate(), spell_item_vanquished_clutches::Validate(), spell_item_purify_helboar_meat::Validate(), spell_item_reindeer_transformation::Validate(), spell_item_nigh_invulnerability::Validate(), spell_item_poultryizer::Validate(), spell_item_socrethars_stone::Validate(), spell_item_demon_broiled_surprise::Validate(), spell_item_complete_raptor_capture::Validate(), spell_item_brewfest_mount_transformation::Validate(), spell_item_nitro_boots::Validate(), spell_item_teach_language::Validate(), spell_item_rocket_boots::Validate(), spell_item_pygmy_oil::Validate(), spell_item_chicken_cover::Validate(), spell_item_eggnog::Validate(), spell_item_goblin_bomb::Validate(), spell_mage_burnout::Validate(), spell_mage_combustion_proc::Validate(), spell_mage_incanters_absorbtion_base_AuraScript::Validate(), spell_mage_blast_wave::Validate(), spell_mage_fire_frost_ward::Validate(), spell_mage_focus_magic::Validate(), spell_mage_ignite::Validate(), spell_mage_master_of_elements::Validate(), spell_pal_ardent_defender::Validate(), spell_pal_avenging_wrath::Validate(), spell_pal_blessing_of_faith::Validate(), spell_pal_blessing_of_sanctuary::Validate(), spell_pal_divine_storm::Validate(), spell_pal_divine_storm_dummy::Validate(), spell_pal_eye_for_an_eye::Validate(), spell_pal_guarded_by_the_light::Validate(), spell_pal_judgement::Validate(), spell_pal_lay_on_hands::Validate(), spell_pal_righteous_defense::Validate(), spell_pal_seal_of_righteousness::Validate(), spell_pri_circle_of_healing::Validate(), spell_pri_divine_aegis::Validate(), spell_pri_glyph_of_prayer_of_healing::Validate(), spell_pri_guardian_spirit::Validate(), spell_pri_item_greater_heal_refund::Validate(), spell_pri_mana_leech::Validate(), spell_pri_power_word_shield_aura::Validate(), spell_pri_prayer_of_mending_heal::Validate(), spell_pri_renew::Validate(), spell_pri_vampiric_touch::Validate(), spell_pri_t4_4p_bonus::Validate(), spell_q2203_thaumaturgy_channel::Validate(), spell_q5206_test_fetid_skull::Validate(), spell_q11396_11399_scourging_crystal_controller::Validate(), spell_q11396_11399_scourging_crystal_controller_dummy::Validate(), spell_q11587_arcane_prisoner_rescue::Validate(), spell_q11730_ultrasonic_screwdriver::Validate(), spell_q12634_despawn_fruit_tosser::Validate(), spell_q12937_relief_for_the_fallen::Validate(), spell_q10041_q10040_who_are_they::Validate(), spell_q14112_14145_chum_the_water::Validate(), spell_q12730_quenching_mist::Validate(), spell_q13291_q13292_q13239_q13261_frostbrood_skytalon_grab_decoy::Validate(), spell_q13011_bear_flank_master::Validate(), spell_q12690_burst_at_the_seams::Validate(), spell_q12308_escape_from_silverbrook::Validate(), spell_q12641_death_comes_from_on_high::Validate(), spell_q12919_gymers_grab::Validate(), spell_rog_blade_flurry::Validate(), spell_rog_cheat_death::Validate(), spell_rog_killing_spree::spell_rog_killing_spree_SpellScript::Validate(), spell_rog_killing_spree::spell_rog_killing_spree_AuraScript::Validate(), spell_rog_preparation::Validate(), spell_rog_prey_on_the_weak::Validate(), spell_rog_shiv::Validate(), spell_rog_tricks_of_the_trade::Validate(), spell_sha_ancestral_awakening_proc::Validate(), spell_sha_bloodlust::Validate(), spell_sha_cleansing_totem_pulse::Validate(), spell_sha_earth_shield::Validate(), spell_sha_earthbind_totem::Validate(), spell_sha_earthliving_weapon::Validate(), spell_sha_flame_shock::Validate(), spell_sha_healing_stream_totem::Validate(), spell_sha_heroism::Validate(), spell_sha_item_lightning_shield::Validate(), spell_sha_item_lightning_shield_trigger::Validate(), spell_sha_item_mana_surge::Validate(), spell_sha_item_t10_elemental_2p_bonus::Validate(), spell_sha_mana_spring_totem::Validate(), spell_sha_mana_tide_totem::Validate(), spell_sha_sentry_totem::Validate(), spell_sha_t8_electrified::Validate(), spell_warl_demonic_empowerment::Validate(), spell_warl_create_healthstone::Validate(), spell_warl_soulshatter::Validate(), spell_warl_siphon_life::Validate(), spell_warl_life_tap::Validate(), spell_warl_demonic_circle_summon::Validate(), spell_warl_demonic_circle_teleport::Validate(), spell_warl_fel_synergy::Validate(), spell_warl_haunt_aura::Validate(), spell_warl_unstable_affliction::Validate(), spell_warl_curse_of_doom::Validate(), spell_warl_health_funnel::Validate(), spell_warl_glyph_of_shadowflame::Validate(), spell_warl_drain_soul::Validate(), spell_warr_intervene::Validate(), spell_warr_improved_spell_reflection::Validate(), spell_warr_improved_spell_reflection_trigger::Validate(), spell_warr_last_stand::Validate(), spell_warr_deep_wounds::Validate(), spell_warr_charge::Validate(), spell_warr_slam::Validate(), spell_warr_damage_shield::Validate(), spell_warr_execute::Validate(), spell_warr_bloodthirst::Validate(), spell_warr_overpower::Validate(), spell_warr_sweeping_strikes::Validate(), spell_warr_vigilance::Validate(), spell_warr_vigilance_trigger::Validate(), spell_warr_retaliation::Validate(), spell_shadow_bolt_whirl::Validate(), spell_mark_of_nature::spell_mark_of_nature_SpellScript::Validate(), spell_deathwhisper_dark_reckoning::Validate(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::Validate(), spell_dragonblight_corrosive_spit::Validate(), and WeatherForcast().
ValidateSpellInfo() [2/2]
template<class T > static bool _SpellScript::ValidateSpellInfo (T const & spellIds) inline static
    {
        return _ValidateSpellInfo(std::begin(spellIds), std::end(spellIds));
    }
References _ValidateSpellInfo().
Member Data Documentation
m_currentScriptState
uint8 _SpellScript::m_currentScriptState protected
Referenced by SpellScript::_FinishScriptCall(), AuraScript::_FinishScriptCall(), _Init(), AuraScript::_IsDefaultActionPrevented(), AuraScript::_PrepareScriptCall(), SpellScript::_PrepareScriptCall(), _Register(), _Unload(), AuraScript::GetTarget(), SpellScript::IsInCheckCastHook(), SpellScript::IsInEffectHook(), SpellScript::IsInHitPhase(), SpellScript::IsInTargetHook(), and AuraScript::PreventDefaultAction().
m_scriptName
std::string const* _SpellScript::m_scriptName protected
Referenced by _GetScriptName(), _Init(), _Validate(), SpellScript::_Validate(), AuraScript::_Validate(), SpellScript::GetEffectValue(), SpellScript::GetHitAura(), SpellScript::GetHitCreature(), SpellScript::GetHitDamage(), SpellScript::GetHitDest(), SpellScript::GetHitGObj(), SpellScript::GetHitHeal(), SpellScript::GetHitItem(), SpellScript::GetHitPlayer(), SpellScript::GetHitUnit(), AuraScript::GetTarget(), AuraScript::PreventDefaultAction(), SpellScript::PreventHitAura(), SpellScript::PreventHitDefaultEffect(), SpellScript::PreventHitEffect(), SpellScript::SetCustomCastResultMessage(), SpellScript::SetEffectValue(), SpellScript::SetHitDamage(), and SpellScript::SetHitHeal().
m_scriptSpellId
uint32 _SpellScript::m_scriptSpellId protected
Referenced by _Init(), SpellScript::GetEffectValue(), SpellScript::GetHitAura(), SpellScript::GetHitCreature(), SpellScript::GetHitDamage(), SpellScript::GetHitDest(), SpellScript::GetHitGObj(), SpellScript::GetHitHeal(), SpellScript::GetHitItem(), SpellScript::GetHitPlayer(), SpellScript::GetHitUnit(), spell_item_with_mount_speed::getMountSpellId(), AuraScript::GetTarget(), spell_magmadar_lava_bomb::spell_magmadar_lava_bomb_SpellScript::HandleDummy(), spell_mutate_explode_bug::HandleOnHit(), spell_utgarde_pinnacle_beast_mark::HandleProc(), spell_brewfest_reveler_transform::OnApply(), spell_black_morass_corrupt_medivh::PeriodicTick(), AuraScript::PreventDefaultAction(), SpellScript::PreventHitAura(), SpellScript::PreventHitDefaultEffect(), SpellScript::PreventHitEffect(), spell_class_call_handler::Register(), spell_brewfest_ram_fatigue::Register(), spell_midsummer_fling_torch::Register(), spell_pilgrims_bounty_food_aura::Register(), spell_pilgrims_bounty_food::Register(), spell_winter_veil_shoot_air_rifle::Register(), spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::Register(), spell_kologarn_stone_shout::spell_kologarn_stone_shout_AuraScript::Register(), spell_kologarn_stone_shout::spell_kologarn_stone_shout_SpellScript::Register(), spell_charge_shield_bomber::spell_charge_shield_bomber_SpellScript::Register(), spell_charge_shield_bomber::spell_charge_shield_bomber_AuraScript::Register(), spell_auchenai_possess::Register(), spell_dk_death_and_decay::Register(), spell_dk_death_and_decay_aura::Register(), spell_dk_pet_scaling::Register(), spell_dk_death_grip::Register(), spell_dru_treant_scaling::Register(), spell_gen_mine_sweeper::Register(), spell_gen_reduced_above_60_aura::Register(), spell_gen_mounted_charge::Register(), spell_gen_defend::Register(), spell_hun_generic_scaling::Register(), spell_hun_aspect_of_the_beast::Register(), spell_item_shifting_naaru_silver::Register(), spell_item_lil_xt::Register(), spell_mage_pet_scaling::Register(), spell_pal_seal_of_command_aura::Register(), spell_pal_seal_of_command::Register(), spell_pri_shadowfiend_scaling::Register(), spell_q11026_a11051_banish_the_demons_aura::Register(), spell_q11026_a11051_banish_the_demons::Register(), spell_q10769_dissension_amongst_the_ranks_aura::Register(), spell_q10769_dissension_amongst_the_ranks::Register(), spell_quest_test_flight_charging::Register(), spell_sha_feral_spirit_scaling::Register(), spell_sha_fire_elemental_scaling::Register(), spell_warl_generic_scaling::Register(), spell_warl_infernal_scaling::Register(), SpellScript::SetCustomCastResultMessage(), SpellScript::SetEffectValue(), SpellScript::SetHitDamage(), and SpellScript::SetHitHeal().