AzerothCore: go_chromaggus_lever::go_chromaggus_leverAI Struct Reference
go_chromaggus_lever::go_chromaggus_leverAI Struct Reference
Public Member Functions
go_chromaggus_leverAI (GameObject *go)
bool GossipHello (Player *player, bool reportUse) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Private Attributes
InstanceScript * _instance
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_chromaggus_leverAI()
go_chromaggus_lever::go_chromaggus_leverAI::go_chromaggus_leverAI (GameObject * go) inline
: GameObjectAI(go), _instance(go->GetInstanceScript()) { }
Member Function Documentation
GossipHello()
bool go_chromaggus_lever::go_chromaggus_leverAI::GossipHello (Player * player, bool reportUse) inline override virtual
Reimplemented from GameObjectAI.
            {
                if (reportUse)
                {
                    if (_instance->GetBossState(DATA_CHROMAGGUS) != DONE && _instance->GetBossState(DATA_CHROMAGGUS) != IN_PROGRESS)
                    {
                        if (Creature* creature = _instance->GetCreature(DATA_CHROMAGGUS))
{
                            creature->SetHomePosition(homePos);
                            creature->GetMotionMaster()->MovePath(creature->GetEntry() * 10, false);
                            creature->AI()->SetGUID(player->GetGUID(), GUID_LEVER_USER);
                        }
                        if (GameObject* go = _instance->GetGameObject(DATA_GO_CHROMAGGUS_DOOR))
                            _instance->HandleGameObject(ObjectGuid::Empty, true, go);
                    }
                    me->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE | GO_FLAG_IN_USE);
                    me->SetGoState(GO_STATE_ACTIVE);
                }
                return true;
            }
References _instance, DATA_CHROMAGGUS, DATA_GO_CHROMAGGUS_DOOR, DONE, ObjectGuid::Empty, InstanceScript::GetBossState(), InstanceScript::GetCreature(), InstanceScript::GetGameObject(), Object::GetGUID(), GO_FLAG_IN_USE, GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, GUID_LEVER_USER, InstanceScript::HandleGameObject(), homePos, IN_PROGRESS, GameObjectAI::me, GameObject::SetGameObjectFlag(), and GameObject::SetGoState().
Member Data Documentation
_instance
InstanceScript* go_chromaggus_lever::go_chromaggus_leverAI::_instance private
Referenced by GossipHello().