AzerothCore: MalleableGooSelector Struct Reference
MalleableGooSelector Struct Reference
Public Member Functions
MalleableGooSelector (Unit const *unit)
bool operator() (Unit const *target) const
Private Attributes
Unit const * me
Detailed Description
Constructor & Destructor Documentation
MalleableGooSelector()
MalleableGooSelector::MalleableGooSelector (Unit const * unit) inline
: me(unit) { }
Member Function Documentation
operator()()
bool MalleableGooSelector::operator() (Unit const * target) const inline
    {
        if (!me || !target || !target->IsPlayer())
            return false;
        if (me->IsWithinCombatRange(target, 7.0f))
            return false;
        return me->IsValidAttackTarget(target);
    }
References Object::IsPlayer(), Unit::IsValidAttackTarget(), Unit::IsWithinCombatRange(), and me.
Member Data Documentation
me
Unit const* MalleableGooSelector::me private
Referenced by operator()().