AzerothCore: boss_skadi_grauf::boss_skadi_graufAI Struct Reference
boss_skadi_grauf::boss_skadi_graufAI Struct Reference
Public Member Functions
boss_skadi_graufAI (Creature *pCreature)
void Reset () override
void DoAction (int32 param) override
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
void SpawnFlameTriggers (uint8 point)
void MovementInform (uint32, uint32 Id) override
uint8 SelectNextPos (uint8 Position)
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void RemoveSkadi (bool withEvade)
void CheckPlayers ()
void SpawnHelpers (uint8 Spot)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
uint8 currentPos
uint8 AchievementHitCount
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from VehicleAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_skadi_graufAI()
boss_skadi_grauf::boss_skadi_graufAI::boss_skadi_graufAI (Creature * pCreature) inline
                                                : VehicleAI(pCreature), summons(me)
        {
            m_pInstance = pCreature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and m_pInstance.
Member Function Documentation
CheckPlayers()
void boss_skadi_grauf::boss_skadi_graufAI::CheckPlayers () inline
        {
            Map::PlayerList const& pList = me->GetMap()->GetPlayers();
            for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
            {
                if (itr->GetSource()->GetPositionX() < 320.0f || itr->GetSource()->IsGameMaster() || !itr->GetSource()->IsAlive())
                    continue;
                return;
            }
            RemoveSkadi(true);
        }
References MapRefMgr::begin(), MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), CreatureAI::me, and RemoveSkadi().
Referenced by UpdateAI().
DoAction()
void boss_skadi_grauf::boss_skadi_graufAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_START_EVENT)
            {
                events.RescheduleEvent(EVENT_GRAUF_CHECK, 5s);
                events.RescheduleEvent(EVENT_GRAUF_START, 2s);
            }
            else if (param == ACTION_REMOVE_SKADI)
            {
                if (Unit* passenger = me->GetVehicleKit()->GetPassenger(0))
                    if (Creature* skadi = passenger->ToCreature())
                        skadi->AI()->Talk(SAY_DRAKE_DEATH);
                me->GetMotionMaster()->MovePoint(10, 480.0f, -513.0f, 108.0f);
                events.ScheduleEvent(EVENT_GRAUF_REMOVE_SKADI, 2s);
            }
            else if (param == ACTION_MYGIRL_ACHIEVEMENT)
            {
                AchievementHitCount++;
                if (AchievementHitCount >= 3 && m_pInstance)
                    m_pInstance->SetData(DATA_SKADI_ACHIEVEMENT, true);
            }
        }
References AchievementHitCount, ACTION_MYGIRL_ACHIEVEMENT, ACTION_REMOVE_SKADI, ACTION_START_EVENT, DATA_SKADI_ACHIEVEMENT, EVENT_GRAUF_CHECK, EVENT_GRAUF_REMOVE_SKADI, EVENT_GRAUF_START, Unit::GetMotionMaster(), Vehicle::GetPassenger(), Unit::GetVehicleKit(), m_pInstance, CreatureAI::me, MotionMaster::MovePoint(), SAY_DRAKE_DEATH, ZoneScript::SetData(), and Object::ToCreature().
JustEngagedWith()
void boss_skadi_grauf::boss_skadi_graufAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from CreatureAI.
        {
            me->SetInCombatWithZone();
        }
References CreatureAI::me, and Creature::SetInCombatWithZone().
MovementInform()
void boss_skadi_grauf::boss_skadi_graufAI::MovementInform (uint32 , uint32 Id) inline override virtual
Reimplemented from CreatureAI.
        {
            switch (Id)
            {
                case 0:
                case 1:
                    me->RemoveAurasDueToSpell(SPELL_FREEZING_CLOUD_VISUAL);
                    me->SetFacingTo(M_PI * 2);
                    break;
                case 2:
                case 3:
                    if (m_pInstance)
                        m_pInstance->SetData(SKADI_IN_RANGE, 1);
                    Talk(EMOTE_RANGE);
                    me->SetFacingTo(M_PI);
                    break;
            }
        }
References EMOTE_RANGE, m_pInstance, CreatureAI::me, Unit::RemoveAurasDueToSpell(), ZoneScript::SetData(), Unit::SetFacingTo(), SKADI_IN_RANGE, and SPELL_FREEZING_CLOUD_VISUAL.
RemoveSkadi()
void boss_skadi_grauf::boss_skadi_graufAI::RemoveSkadi (bool withEvade) inline
        {
            if (Unit* skadi = me->GetVehicleKit()->GetPassenger(0))
            {
                summons.DespawnAll();
                skadi->ExitVehicle();
                if (withEvade)
                {
                    skadi->ToCreature()->AI()->EnterEvadeMode();
                    skadi->UpdatePosition(343.02f, -507.325f, 104.567f, M_PI, true);
                }
                else
                    skadi->ToCreature()->AI()->DoAction(ACTION_PHASE2);
                skadi->StopMovingOnCurrentPos();
            }
        }
References ACTION_PHASE2, SummonList::DespawnAll(), Vehicle::GetPassenger(), Unit::GetVehicleKit(), CreatureAI::me, and summons.
Referenced by CheckPlayers(), and UpdateAI().
Reset()
void boss_skadi_grauf::boss_skadi_graufAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            events.Reset();
            summons.DespawnAll();
            currentPos = 0;
            AchievementHitCount = 0;
            me->RemoveAllAuras();
        }
References AchievementHitCount, currentPos, SummonList::DespawnAll(), CreatureAI::me, Unit::RemoveAllAuras(), and summons.
SelectNextPos()
uint8 boss_skadi_grauf::boss_skadi_graufAI::SelectNextPos (uint8 Position) inline
        {
            switch (Position)
            {
                case 0:
                case 1:
                    return 2 + urand(0, 1);
                default:
                    if (me->GetPositionY() < -515.0f)
                        return 1;
                    else
                        return 0;
            }
        }
References Position::GetPositionY(), CreatureAI::me, and urand().
Referenced by UpdateAI().
SpawnFlameTriggers()
void boss_skadi_grauf::boss_skadi_graufAI::SpawnFlameTriggers (uint8 point) inline
        {
            for(uint8 j = 0; j < 50; ++j)
            {
                if (point == 1)
                    me->SummonCreature(NPC_BREATH_TRIGGER, 480.0f - (j * 3), -518.0f + (j / 16.0f), 105.0f, 0, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 30000);
                else
                    me->SummonCreature(NPC_BREATH_TRIGGER, 480.0f - (j * 3), -510.0f + (j / 16.0f), 105.0f, 0, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 30000);
            }
            // and out of loop, cover the small room
            if (point == 0)
            {
                Creature* cr;
                if ((cr = me->SummonCreature(NPC_BREATH_TRIGGER, 483, -484.9f, 105, 0, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 30000)))
                    cr->CastSpell(cr, cr->GetMap()->IsHeroic() ? SPELL_FREEZING_CLOUD_H : SPELL_FREEZING_CLOUD_N, true);
                if ((cr = me->SummonCreature(NPC_BREATH_TRIGGER, 471.0f, -484.7f, 105, 0, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 30000)))
                    cr->CastSpell(cr, cr->GetMap()->IsHeroic() ? SPELL_FREEZING_CLOUD_H : SPELL_FREEZING_CLOUD_N, true);
                for (uint8 j = 0; j < 7; j++)
                    if ((cr = me->SummonCreature(NPC_BREATH_TRIGGER, 477.0f, -507.0f + (j * 3), 105.0f, 0, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 30000)))
                        cr->CastSpell(cr, cr->GetMap()->IsHeroic() ? SPELL_FREEZING_CLOUD_H : SPELL_FREEZING_CLOUD_N, true);
            }
        }
References Unit::CastSpell(), WorldObject::GetMap(), Map::IsHeroic(), CreatureAI::me, NPC_BREATH_TRIGGER, SPELL_FREEZING_CLOUD_H, SPELL_FREEZING_CLOUD_N, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN.
Referenced by UpdateAI().
SpawnHelpers()
void boss_skadi_grauf::boss_skadi_graufAI::SpawnHelpers (uint8 Spot) inline
        {
            if (Creature* Harpooner = me->SummonCreature(NPC_YMIRJAR_HARPOONER, TrashPosition[Spot].GetPositionX() + rand() % 5, TrashPosition[Spot].GetPositionY() + rand() % 5, TrashPosition[Spot].GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000))
            {
                Harpooner->SetInCombatWithZone();
                summons.Summon(Harpooner);
            }
            if (Creature* Second = me->SummonCreature((urand(0, 1) ? NPC_YMIRJAR_WARRIOR : NPC_YMIRJAR_WITCH_DOCTOR), TrashPosition[Spot].GetPositionX() + rand() % 5, TrashPosition[Spot].GetPositionY() + rand() % 5, TrashPosition[Spot].GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000))
            {
                Second->SetInCombatWithZone();
                summons.Summon(Second);
            }
        }
References Position::GetPositionX(), CreatureAI::me, NPC_YMIRJAR_HARPOONER, NPC_YMIRJAR_WARRIOR, NPC_YMIRJAR_WITCH_DOCTOR, SummonList::Summon(), WorldObject::SummonCreature(), summons, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, TrashPosition, and urand().
Referenced by UpdateAI().
SpellHitTarget()
void boss_skadi_grauf::boss_skadi_graufAI::SpellHitTarget (Unit * target, SpellInfo const * spellInfo) inline override virtual
Reimplemented from CreatureAI.
        {
            if (spellInfo->Id == 47593) // SPELL_FREEZING_CLOUD_VISUAL trigger
                target->CastSpell(target, me->GetMap()->IsHeroic() ? SPELL_FREEZING_CLOUD_H : SPELL_FREEZING_CLOUD_N, true);
        }
References Unit::CastSpell(), WorldObject::GetMap(), SpellInfo::Id, Map::IsHeroic(), CreatureAI::me, SPELL_FREEZING_CLOUD_H, and SPELL_FREEZING_CLOUD_N.
UpdateAI()
void boss_skadi_grauf::boss_skadi_graufAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from VehicleAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_GRAUF_CHECK:
                    {
                        CheckPlayers();
                        events.Repeat(2s);
                        break;
                    }
                case EVENT_GRAUF_START:
                    {
                        me->GetMotionMaster()->Clear(true);
                        me->GetMotionMaster()->MoveTakeoff(10, SkadiPosition[0].GetPositionX(), SkadiPosition[0].GetPositionY(), SkadiPosition[0].GetPositionZ(), 3.0f);
                        SpawnHelpers(0);
                        SpawnHelpers(0);
                        events.ScheduleEvent(EVENT_GRAUF_MOVE, 15s);
                        events.ScheduleEvent(EVENT_GRAUF_SUMMON_HELPERS, 20s);
                        break;
                    }
                case EVENT_GRAUF_MOVE:
                    {
                        AchievementHitCount = 0;
                        uint8 targetPoint = SelectNextPos(currentPos);
                        me->GetMotionMaster()->MovePoint(targetPoint, SkadiPosition[targetPoint].GetPositionX(), SkadiPosition[targetPoint].GetPositionY(), SkadiPosition[targetPoint].GetPositionZ());
                        if (targetPoint <= 1)
{
                            Talk(EMOTE_DEEP_BREATH);
                            SpawnFlameTriggers(targetPoint);
                            me->CastSpell(me, SPELL_FREEZING_CLOUD_VISUAL, false);
                        }
                        if (m_pInstance)
                            m_pInstance->SetData(SKADI_IN_RANGE, 0);
                        currentPos = targetPoint;
                        events.Repeat(25s);
                        break;
                    }
                case EVENT_GRAUF_SUMMON_HELPERS:
                    {
                        SpawnHelpers(1);
                        events.Repeat(15s);
                        break;
                    }
                case EVENT_GRAUF_REMOVE_SKADI:
                    {
                        RemoveSkadi(false);
                        me->DespawnOrUnsummon();
                        break;
                    }
            }
        }
References AchievementHitCount, Unit::CastSpell(), CheckPlayers(), MotionMaster::Clear(), currentPos, Creature::DespawnOrUnsummon(), EMOTE_DEEP_BREATH, EVENT_GRAUF_CHECK, EVENT_GRAUF_MOVE, EVENT_GRAUF_REMOVE_SKADI, EVENT_GRAUF_START, EVENT_GRAUF_SUMMON_HELPERS, Unit::GetMotionMaster(), m_pInstance, CreatureAI::me, MotionMaster::MovePoint(), MotionMaster::MoveTakeoff(), RemoveSkadi(), SelectNextPos(), ZoneScript::SetData(), SKADI_IN_RANGE, SkadiPosition, SpawnFlameTriggers(), SpawnHelpers(), and SPELL_FREEZING_CLOUD_VISUAL.
Member Data Documentation
AchievementHitCount
uint8 boss_skadi_grauf::boss_skadi_graufAI::AchievementHitCount
Referenced by DoAction(), Reset(), and UpdateAI().
currentPos
uint8 boss_skadi_grauf::boss_skadi_graufAI::currentPos
Referenced by Reset(), and UpdateAI().
events
EventMap boss_skadi_grauf::boss_skadi_graufAI::events
m_pInstance
InstanceScript* boss_skadi_grauf::boss_skadi_graufAI::m_pInstance
Referenced by boss_skadi_graufAI(), DoAction(), MovementInform(), and UpdateAI().
summons
SummonList boss_skadi_grauf::boss_skadi_graufAI::summons
Referenced by RemoveSkadi(), Reset(), and SpawnHelpers().