AzerothCore: boss_xt002::boss_xt002AI Struct Reference
boss_xt002::boss_xt002AI Struct Reference
Public Member Functions
boss_xt002AI (Creature *pCreature)
void RescheduleEvents ()
void Reset () override
void JustSummoned (Creature *cr) override
void SummonedCreatureDespawn (Creature *cr) override
void AttachHeart ()
void JustReachedHome () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void KilledUnit (Unit *victim) override
void JustDied (Unit *) override
void DoAction (int32 param) override
uint32 GetData (uint32 param) const override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * m_pInstance
uint8 _healthCheck
bool _hardMode
bool _nerfAchievement
bool _gravityAchievement
EventMap events
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_xt002AI()
boss_xt002::boss_xt002AI::boss_xt002AI (Creature * pCreature) inline
                                          : ScriptedAI(pCreature), summons(me)
        {
            m_pInstance = pCreature->GetInstanceScript();
        }
References WorldObject::GetInstanceScript(), and m_pInstance.
Member Function Documentation
AttachHeart()
void boss_xt002::boss_xt002AI::AttachHeart () inline
        {
            if (Unit* heart = me->GetVehicleKit() ? me->GetVehicleKit()->GetPassenger(HEART_VEHICLE_SEAT) : nullptr)
                heart->SetHealth(heart->GetMaxHealth());
            else if (Creature* accessory = me->SummonCreature(NPC_XT002_HEART, *me, TEMPSUMMON_MANUAL_DESPAWN))
            {
                accessory->AddUnitTypeMask(UNIT_MASK_ACCESSORY);
                if (!me->HandleSpellClick(accessory, 0))
                    accessory->DespawnOrUnsummon();
            }
        }
References Vehicle::GetPassenger(), Unit::GetVehicleKit(), Unit::HandleSpellClick(), HEART_VEHICLE_SEAT, ScriptedAI::me, NPC_XT002_HEART, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, and UNIT_MASK_ACCESSORY.
Referenced by JustEngagedWith().
DoAction()
void boss_xt002::boss_xt002AI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_XT002_NERF_ENGINEERING)
            {
                _nerfAchievement = false;
                return;
            }
            if (param == DATA_XT002_GRAVITY_ACHIEV)
            {
                _gravityAchievement = false;
                return;
            }
            if (!me->IsAlive() || _hardMode)
                return;
            // heart destory
            if (param == ACTION_HEART_BROKEN)
            {
                _hardMode = true;
                me->SetLootMode(3); // hard mode + normal loot
                me->SetMaxHealth(me->GetMaxHealth());
                me->SetHealth(me->GetMaxHealth());
                me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_STAND); // emerge
                me->CastSpell(me, SPELL_HEARTBREAK, true);
                Talk(EMOTE_HEART_CLOSED);
                events.ScheduleEvent(EVENT_REMOVE_EMOTE, 4s);
                return;
            }
            // damage from heart
            if (param > 0)
            {
                // avoid reducing health under 1
                int32 _final = std::min(param, int32(me->GetHealth() - 1));
                me->ModifyHealth(-_final);
                me->LowerPlayerDamageReq(_final);
            }
        }
References _gravityAchievement, _hardMode, _nerfAchievement, ACTION_HEART_BROKEN, Unit::CastSpell(), DATA_XT002_GRAVITY_ACHIEV, DATA_XT002_NERF_ENGINEERING, EMOTE_HEART_CLOSED, EVENT_REMOVE_EMOTE, Unit::GetHealth(), Unit::GetMaxHealth(), Unit::IsAlive(), Creature::LowerPlayerDamageReq(), ScriptedAI::me, Unit::ModifyHealth(), Object::SetByteValue(), Unit::SetHealth(), Creature::SetLootMode(), Unit::SetMaxHealth(), SPELL_HEARTBREAK, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_FIELD_BYTES_1, and UNIT_STAND_STATE_STAND.
GetData()
uint32 boss_xt002::boss_xt002AI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
        {
            if (param == DATA_XT002_NERF_ENGINEERING)
                return _nerfAchievement;
            else if (param == DATA_XT002_GRAVITY_ACHIEV)
                return _gravityAchievement;
            return 0;
        }
References _gravityAchievement, _nerfAchievement, DATA_XT002_GRAVITY_ACHIEV, and DATA_XT002_NERF_ENGINEERING.
JustDied()
void boss_xt002::boss_xt002AI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
        {
            Talk(SAY_DEATH);
            if (m_pInstance)
            {
                m_pInstance->SetData(TYPE_XT002, DONE);
                if (GameObject* pGo = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_XT002_DOORS)))
                    pGo->SetGoState(GO_STATE_ACTIVE);
            }
            // Despawn summons
            summons.DespawnAll();
        }
References SummonList::DespawnAll(), DONE, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_STATE_ACTIVE, GO_XT002_DOORS, m_pInstance, ScriptedAI::me, SAY_DEATH, ZoneScript::SetData(), summons, and TYPE_XT002.
JustEngagedWith()
void boss_xt002::boss_xt002AI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from ScriptedAI.
        {
            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
            events.ScheduleEvent(EVENT_ENRAGE, 10min, 0, 0);
            events.ScheduleEvent(EVENT_CHECK_ROOM, 5s, 0, 0);
            RescheduleEvents(); // Other events are scheduled here
            me->setActive(true);
            Talk(SAY_AGGRO);
            if (m_pInstance)
            {
                m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEVEMENT_MUST_DECONSTRUCT_FASTER);
                m_pInstance->SetData(TYPE_XT002, IN_PROGRESS);
                if (GameObject* pGo = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_XT002_DOORS)))
                    pGo->SetGoState(GO_STATE_READY);
            }
            me->CallForHelp(175);
            me->SetInCombatWithZone();
            AttachHeart();
        }
References ACHIEVEMENT_MUST_DECONSTRUCT_FASTER, ACHIEVEMENT_TIMED_TYPE_EVENT, AttachHeart(), Creature::CallForHelp(), InstanceScript::DoStartTimedAchievement(), EMOTE_ONESHOT_NONE, EVENT_CHECK_ROOM, EVENT_ENRAGE, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_STATE_READY, GO_XT002_DOORS, IN_PROGRESS, m_pInstance, ScriptedAI::me, RescheduleEvents(), SAY_AGGRO, WorldObject::setActive(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), Unit::SetUInt32Value(), TYPE_XT002, and UNIT_NPC_EMOTESTATE.
JustReachedHome()
void boss_xt002::boss_xt002AI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
{ me->setActive(false); }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_xt002::boss_xt002AI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
{ summons.Summon(cr); }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_xt002::boss_xt002AI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
        {
            if (victim->IsPlayer() && !urand(0, 2))
            {
                Talk(SAY_SLAY);
            }
        }
References Object::IsPlayer(), SAY_SLAY, and urand().
RescheduleEvents()
void boss_xt002::boss_xt002AI::RescheduleEvents () inline
        {
            events.RescheduleEvent(EVENT_GRAVITY_BOMB, 1s, 1);
            events.RescheduleEvent(EVENT_TYMPANIC_TANTARUM, 1min, 1);
            if (!_hardMode)
                events.RescheduleEvent(EVENT_HEALTH_CHECK, 2s, 1);
        }
References _hardMode, EVENT_GRAVITY_BOMB, EVENT_HEALTH_CHECK, and EVENT_TYMPANIC_TANTARUM.
Referenced by JustEngagedWith(), and UpdateAI().
Reset()
void boss_xt002::boss_xt002AI::Reset () inline override virtual
Reimplemented from ScriptedAI.
        {
            summons.DespawnAll();
            events.Reset();
            me->ResetLootMode();
            me->RemoveAllAuras();
            // first heart expose
            _healthCheck = 75;
            _hardMode = false;
            _nerfAchievement = true;
            _gravityAchievement = true;
            me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_STAND); // emerge
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
            me->SetControlled(false, UNIT_STATE_STUNNED);
            if (m_pInstance)
            {
                m_pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEVEMENT_MUST_DECONSTRUCT_FASTER);
                m_pInstance->SetData(TYPE_XT002, NOT_STARTED);
                if (GameObject* pGo = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_XT002_DOORS)))
                    pGo->SetGoState(GO_STATE_ACTIVE);
            }
        }
References _gravityAchievement, _hardMode, _healthCheck, _nerfAchievement, ACHIEVEMENT_MUST_DECONSTRUCT_FASTER, ACHIEVEMENT_TIMED_TYPE_EVENT, SummonList::DespawnAll(), InstanceScript::DoStopTimedAchievement(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_STATE_ACTIVE, GO_XT002_DOORS, m_pInstance, ScriptedAI::me, NOT_STARTED, Unit::RemoveAllAuras(), Unit::RemoveUnitFlag(), Creature::ResetLootMode(), Object::SetByteValue(), Unit::SetControlled(), ZoneScript::SetData(), summons, TYPE_XT002, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_FIELD_BYTES_1, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STAND_STATE_STAND, and UNIT_STATE_STUNNED.
SummonedCreatureDespawn()
void boss_xt002::boss_xt002AI::SummonedCreatureDespawn (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
{ summons.Despawn(cr); }
References SummonList::Despawn(), and summons.
UpdateAI()
void boss_xt002::boss_xt002AI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from ScriptedAI.
        {
            if (!UpdateVictim())
                return;
            events.Update(diff);
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                // Control events
                case EVENT_HEALTH_CHECK:
                    if (_hardMode)
                    {
                        return;
                    }
                    if (me->HealthBelowPct(_healthCheck))
                    {
                        _healthCheck -= 25;
                        me->SetControlled(true, UNIT_STATE_STUNNED);
                        me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_SUBMERGED); // submerge with animation
                        Talk(SAY_HEART_OPENED);
                        events.CancelEventGroup(1);
                        events.ScheduleEvent(EVENT_START_SECOND_PHASE, 5s);
                        return;
                    }
                    events.Repeat(1s);
                    break;
                case EVENT_CHECK_ROOM:
                    events.Repeat(5s);
                    if (me->GetPositionX() < 722 || me->GetPositionX() > 987 || me->GetPositionY() < -139 || me->GetPositionY() > 124)
                        EnterEvadeMode();
                    return;
                // Abilities events
                case EVENT_GRAVITY_BOMB:
                    me->CastCustomSpell(SPELL_GRAVITY_BOMB, SPELLVALUE_MAX_TARGETS, 1, me, true);
                    events.ScheduleEvent(EVENT_SEARING_LIGHT, 10s, 1);
                    break;
                case EVENT_SEARING_LIGHT:
                    me->CastCustomSpell(SPELL_SEARING_LIGHT, SPELLVALUE_MAX_TARGETS, 1, me, true);
                    events.ScheduleEvent(EVENT_GRAVITY_BOMB, 10s, 1);
                    break;
                case EVENT_TYMPANIC_TANTARUM:
                    Talk(EMOTE_TYMPANIC_TANTRUM);
                    Talk(SAY_TYMPANIC_TANTRUM);
                    me->CastSpell(me, SPELL_TYMPANIC_TANTARUM, true);
                    events.Repeat(1min);
                    return;
                case EVENT_ENRAGE:
                    Talk(SAY_BERSERK);
                    me->CastSpell(me, SPELL_XT002_ENRAGE, true);
                    break;
                // Animation events
                case EVENT_START_SECOND_PHASE:
                    Talk(EMOTE_HEART_OPENED);
                    me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                    if (Unit* heart = me->GetVehicleKit() ? me->GetVehicleKit()->GetPassenger(HEART_VEHICLE_SEAT) : nullptr)
                        heart->GetAI()->DoAction(ACTION_AWAKEN_HEART);
                    events.ScheduleEvent(EVENT_RESTORE, 30s);
                    return;
                // Restore from heartbreak
                case EVENT_RESTORE:
                    if (_hardMode)
                    {
                        return;
                    }
                    Talk(SAY_HEART_CLOSED);
                    me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_STAND); // emerge
                    // Hide heart
                    if (Unit* heart = me->GetVehicleKit() ? me->GetVehicleKit()->GetPassenger(HEART_VEHICLE_SEAT) : nullptr)
                        heart->GetAI()->DoAction(ACTION_HIDE_HEART);
                    events.ScheduleEvent(EVENT_REMOVE_EMOTE, 4s);
                    return;
                case EVENT_REMOVE_EMOTE:
                    me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                    me->SetControlled(false, UNIT_STATE_STUNNED);
                    RescheduleEvents();
                    return;
            }
            // Disabled by stunned state
            DoMeleeAttackIfReady();
        }
References _hardMode, _healthCheck, ACTION_AWAKEN_HEART, ACTION_HIDE_HEART, Unit::CastCustomSpell(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EMOTE_HEART_OPENED, EMOTE_TYMPANIC_TANTRUM, CreatureAI::EnterEvadeMode(), EVENT_CHECK_ROOM, EVENT_ENRAGE, EVENT_GRAVITY_BOMB, EVENT_HEALTH_CHECK, EVENT_REMOVE_EMOTE, EVENT_RESTORE, EVENT_SEARING_LIGHT, EVENT_START_SECOND_PHASE, EVENT_TYMPANIC_TANTARUM, Vehicle::GetPassenger(), Position::GetPositionX(), Position::GetPositionY(), Unit::GetVehicleKit(), Unit::HasUnitState(), Unit::HealthBelowPct(), HEART_VEHICLE_SEAT, ScriptedAI::me, Unit::RemoveUnitFlag(), RescheduleEvents(), SAY_BERSERK, SAY_HEART_CLOSED, SAY_HEART_OPENED, SAY_TYMPANIC_TANTRUM, Object::SetByteValue(), Unit::SetControlled(), Unit::SetUnitFlag(), SPELL_GRAVITY_BOMB, SPELL_SEARING_LIGHT, SPELL_TYMPANIC_TANTARUM, SPELL_XT002_ENRAGE, SPELLVALUE_MAX_TARGETS, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_FIELD_BYTES_1, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STAND_STATE_STAND, UNIT_STAND_STATE_SUBMERGED, UNIT_STATE_CASTING, UNIT_STATE_STUNNED, and CreatureAI::UpdateVictim().
Member Data Documentation
_gravityAchievement
bool boss_xt002::boss_xt002AI::_gravityAchievement
Referenced by DoAction(), GetData(), and Reset().
_hardMode
bool boss_xt002::boss_xt002AI::_hardMode
Referenced by DoAction(), RescheduleEvents(), Reset(), and UpdateAI().
_healthCheck
uint8 boss_xt002::boss_xt002AI::_healthCheck
Referenced by Reset(), and UpdateAI().
_nerfAchievement
bool boss_xt002::boss_xt002AI::_nerfAchievement
Referenced by DoAction(), GetData(), and Reset().
events
EventMap boss_xt002::boss_xt002AI::events
m_pInstance
InstanceScript* boss_xt002::boss_xt002AI::m_pInstance
Referenced by boss_xt002AI(), JustDied(), JustEngagedWith(), and Reset().
summons
SummonList boss_xt002::boss_xt002AI::summons
Referenced by JustDied(), JustSummoned(), Reset(), and SummonedCreatureDespawn().