AzerothCore: Acore::AnyGroupedUnitInObjectRangeCheck Class Reference
Acore::AnyGroupedUnitInObjectRangeCheck Class Reference
#include "GridNotifiers.h"
Public Member Functions
AnyGroupedUnitInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range, bool raid)
bool operator() (Unit *u)
Private Attributes
WorldObject const * _source
Unit const * _refUnit
float _range
bool _raid
Detailed Description
Constructor & Destructor Documentation
AnyGroupedUnitInObjectRangeCheck()
Acore::AnyGroupedUnitInObjectRangeCheck::AnyGroupedUnitInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range, bool raid) inline
: _source(obj), _refUnit(funit), _range(range), _raid(raid) {}
Member Function Documentation
operator()()
bool Acore::AnyGroupedUnitInObjectRangeCheck::operator() (Unit * u) inline
        {
            if (_raid)
            {
                if (!_refUnit->IsInRaidWith(u))
                    return false;
            }
            else if (!_refUnit->IsInPartyWith(u))
                return false;
            return !_refUnit->IsHostileTo(u) && u->IsAlive() && _source->IsWithinDistInMap(u, _range);
        }
References _raid, _range, _refUnit, _source, Unit::IsAlive(), Unit::IsHostileTo(), Unit::IsInPartyWith(), Unit::IsInRaidWith(), and WorldObject::IsWithinDistInMap().
Member Data Documentation
_raid
bool Acore::AnyGroupedUnitInObjectRangeCheck::_raid private
Referenced by operator()().
_range
float Acore::AnyGroupedUnitInObjectRangeCheck::_range private
Referenced by operator()().
_refUnit
Unit const* Acore::AnyGroupedUnitInObjectRangeCheck::_refUnit private
Referenced by operator()().
_source
WorldObject const* Acore::AnyGroupedUnitInObjectRangeCheck::_source private
Referenced by operator()().