AzerothCore: npc_crusade_persuaded::npc_crusade_persuadedAI Struct Reference
npc_crusade_persuaded::npc_crusade_persuadedAI Struct Reference
Public Member Functions
npc_crusade_persuadedAI (Creature *creature)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void SpellHit (Unit *caster, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from CombatAI
CombatAI (Creature *c)
void InitializeAI () override
void Reset () override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void JustDied (Unit *killer) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
const uint32 SAY_AGGRO_CHANCE = 33
const uint32 PERSUADE_SUCCESS_CHANCE = 3
const uint32 SPEECH_TIMER_DEFAULT = 1000
const uint32 SPEECH_TIMER_FOR_ROLEPLAY = 8000
const uint32 SPEECH_COUNTER_PREVENT_SUCCESS_ROLEPLAY = 0
const uint32 SPEECH_COUNTER_START_SUCCESS_ROLEPLAY = 1
uint32 speechTimer
uint32 speechCounter
ObjectGuid playerGUID
bool persuaded
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CombatAI
static int32 Permissible (Creature const *)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CombatAI
EventMap events
SpellVct spells
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_crusade_persuadedAI()
npc_crusade_persuaded::npc_crusade_persuadedAI::npc_crusade_persuadedAI (Creature * creature) inline
: CombatAI(creature) { }
Member Function Documentation
JustEngagedWith()
void npc_crusade_persuaded::npc_crusade_persuadedAI::JustEngagedWith (Unit * who) inline override virtual
Called for reaction when initially engaged.
Parameters
who Who 'me' Engaged combat with
Reimplemented from CombatAI.
        {
            if (roll_chance_i(SAY_AGGRO_CHANCE))
                Talk(SAY_AGGRO);
        }
References roll_chance_i(), SAY_AGGRO, and SAY_AGGRO_CHANCE.
Reset()
void npc_crusade_persuaded::npc_crusade_persuadedAI::Reset () inline override virtual
Reimplemented from CombatAI.
        {
            speechTimer = 0;
            speechCounter = SPEECH_COUNTER_PREVENT_SUCCESS_ROLEPLAY;
            playerGUID.Clear();
            me->SetReactState(REACT_AGGRESSIVE);
            me->RestoreFaction();
        }
References ObjectGuid::Clear(), CreatureAI::me, playerGUID, REACT_AGGRESSIVE, Unit::RestoreFaction(), Creature::SetReactState(), SPEECH_COUNTER_PREVENT_SUCCESS_ROLEPLAY, speechCounter, and speechTimer.
SpellHit()
void npc_crusade_persuaded::npc_crusade_persuadedAI::SpellHit (Unit * caster, SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
        {
            if (spell->Id == SPELL_PERSUASIVE_STRIKE && caster->IsPlayer() && me->IsAlive() && !speechCounter)
            {
                if (Player* player = caster->ToPlayer())
                {
                    playerGUID = player->GetGUID();
                    speechTimer = SPEECH_TIMER_DEFAULT;
                    speechCounter = SPEECH_COUNTER_START_SUCCESS_ROLEPLAY;
                    uint32 persuadeRoll = urand(1, 10);
                    sCreatureTextMgr->SendChat(me, SAY_PERSUADE_RAND, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_NEUTRAL, false, player);
                    if (persuadeRoll <= PERSUADE_SUCCESS_CHANCE && player->GetQuestStatus(QUEST_HOW_TO_WIN_FRIENDS) == QUEST_STATUS_INCOMPLETE)
                    {
                        persuaded = true;
                        me->SetFaction(player->GetFaction());
                        me->CombatStop(true);
                        me->GetMotionMaster()->MoveIdle();
                        me->SetReactState(REACT_PASSIVE);
                    }
                    else
                        persuaded = false;
                }
            }
        }
References CHAT_MSG_ADDON, Unit::CombatStop(), Unit::GetMotionMaster(), SpellInfo::Id, Unit::IsAlive(), Object::IsPlayer(), LANG_ADDON, CreatureAI::me, MotionMaster::MoveIdle(), persuaded, playerGUID, QUEST_HOW_TO_WIN_FRIENDS, QUEST_STATUS_INCOMPLETE, REACT_PASSIVE, SAY_PERSUADE_RAND, sCreatureTextMgr, Unit::SetFaction(), Creature::SetReactState(), SPEECH_COUNTER_START_SUCCESS_ROLEPLAY, SPEECH_TIMER_DEFAULT, speechCounter, speechTimer, SPELL_PERSUASIVE_STRIKE, TEAM_NEUTRAL, TEXT_RANGE_NORMAL, Object::ToPlayer(), and urand().
UpdateAI()
void npc_crusade_persuaded::npc_crusade_persuadedAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Reimplemented from CombatAI.
        {
            if (speechCounter)
            {
                if (speechTimer <= diff)
                {
                    Player* player = ObjectAccessor::GetPlayer(*me, playerGUID);
                    if (!player)
                    {
                        EnterEvadeMode();
                        return;
                    }
                    if (persuaded)
                    {
                        switch (speechCounter)
{
                        case 1:
                            Talk(SAY_PERSUADED1);
                            speechTimer = SPEECH_TIMER_FOR_ROLEPLAY;
                            break;
                        case 2:
                            Talk(SAY_PERSUADED2);
                            speechTimer = SPEECH_TIMER_FOR_ROLEPLAY;
                            break;
                        case 3:
                            Talk(SAY_PERSUADED3);
                            speechTimer = SPEECH_TIMER_FOR_ROLEPLAY;
                            break;
                        case 4:
                            Talk(SAY_PERSUADED4);
                            speechTimer = SPEECH_TIMER_FOR_ROLEPLAY;
                            break;
                        case 5:
                            sCreatureTextMgr->SendChat(me, SAY_PERSUADED5, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_NEUTRAL, false, player);
                            speechTimer = SPEECH_TIMER_FOR_ROLEPLAY;
                            break;
                        case 6:
                            Talk(SAY_PERSUADED6);
                            Unit::Kill(player, me);
                            speechCounter = SPEECH_COUNTER_PREVENT_SUCCESS_ROLEPLAY;
                            player->GroupEventHappens(QUEST_HOW_TO_WIN_FRIENDS, me);
                            return;
                        }
                        ++speechCounter;
                    }
                    else
                    {
                        Talk(SAY_CRUSADER);
                        speechCounter = SPEECH_COUNTER_PREVENT_SUCCESS_ROLEPLAY;
                    }
                }
                else
                    speechTimer = (speechTimer > diff) ? (speechTimer - diff) : 0;
                return;
            }
            CombatAI::UpdateAI(diff);
        }
References CHAT_MSG_ADDON, CreatureAI::EnterEvadeMode(), ObjectAccessor::GetPlayer(), Player::GroupEventHappens(), Unit::Kill(), LANG_ADDON, CreatureAI::me, persuaded, playerGUID, QUEST_HOW_TO_WIN_FRIENDS, SAY_CRUSADER, SAY_PERSUADED1, SAY_PERSUADED2, SAY_PERSUADED3, SAY_PERSUADED4, SAY_PERSUADED5, SAY_PERSUADED6, sCreatureTextMgr, SPEECH_COUNTER_PREVENT_SUCCESS_ROLEPLAY, SPEECH_TIMER_FOR_ROLEPLAY, speechCounter, speechTimer, TEAM_NEUTRAL, TEXT_RANGE_NORMAL, and CombatAI::UpdateAI().
Member Data Documentation
PERSUADE_SUCCESS_CHANCE
const uint32 npc_crusade_persuaded::npc_crusade_persuadedAI::PERSUADE_SUCCESS_CHANCE = 3
persuaded
bool npc_crusade_persuaded::npc_crusade_persuadedAI::persuaded
Referenced by SpellHit(), and UpdateAI().
playerGUID
ObjectGuid npc_crusade_persuaded::npc_crusade_persuadedAI::playerGUID
Referenced by Reset(), SpellHit(), and UpdateAI().
SAY_AGGRO_CHANCE
const uint32 npc_crusade_persuaded::npc_crusade_persuadedAI::SAY_AGGRO_CHANCE = 33
Referenced by JustEngagedWith().
SPEECH_COUNTER_PREVENT_SUCCESS_ROLEPLAY
const uint32 npc_crusade_persuaded::npc_crusade_persuadedAI::SPEECH_COUNTER_PREVENT_SUCCESS_ROLEPLAY = 0
Referenced by Reset(), and UpdateAI().
SPEECH_COUNTER_START_SUCCESS_ROLEPLAY
const uint32 npc_crusade_persuaded::npc_crusade_persuadedAI::SPEECH_COUNTER_START_SUCCESS_ROLEPLAY = 1
Referenced by SpellHit().
SPEECH_TIMER_DEFAULT
const uint32 npc_crusade_persuaded::npc_crusade_persuadedAI::SPEECH_TIMER_DEFAULT = 1000
Referenced by SpellHit().
SPEECH_TIMER_FOR_ROLEPLAY
const uint32 npc_crusade_persuaded::npc_crusade_persuadedAI::SPEECH_TIMER_FOR_ROLEPLAY = 8000
Referenced by UpdateAI().
speechCounter
uint32 npc_crusade_persuaded::npc_crusade_persuadedAI::speechCounter
Referenced by Reset(), SpellHit(), and UpdateAI().
speechTimer
uint32 npc_crusade_persuaded::npc_crusade_persuadedAI::speechTimer
Referenced by Reset(), SpellHit(), and UpdateAI().